### ISSUE TITLE
Implement Kubernetes 1.8 CRD validation

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1000]
Kubernetes 1.8 has a (alpha) feature for CRD validation making it possible to validate CRD values.

This would allow to prevent bad user input for CRDs.

Thanks to @kokhang for bringing this new feature up in #991!

**Comment by bassam** [comment]
This would be a great addition for 0.7, also note that there is a new working group forming to address CRD shortcomings and we should get involved there:

https://groups.google.com/forum/m/#!msg/kubernetes-sig-cli/axv_RxpyX3k/U_6-_wlRAAAJ

**Comment by jbw976** [comment]
API aggregation may enable us to perform some of this rich validation easier.
