### ISSUE TITLE
rgw-multisite-testing integration test is failing due to connection error

### ISSUE THREAD

**Issue by travisn** [rook/rook#10021]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Since earlier today, the `rgw-multisite-testing` integration test is failing, The test log shows the error:
```
Invoked as: /usr/bin/s3cmd -v -d --config=s3cfg --access_key=fGxqUzlMMEZSOFtPLFo= --secret_key=RFVKMT41PyJJWiZhXmhYPCVKKERYLWRMMDY7TA== --host=10.99.130.67 mb s3://bkt
Problem: <class 'ConnectionRefusedError: [Errno 111] Connection refused
S3cmd:   2.0.1
python:   3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0]
environment LANG=C.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3073, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2989, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 232, in cmd_bucket_create
    response = s3.bucket_create(uri.bucket(), cfg.bucket_location)
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 397, in bucket_create
    response = self.send_request(request)
  File "/usr/lib/python3/dist-packages/S3/S3.py", line 1249, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/usr/lib/python3/dist-packages/S3/ConnMan.py", line 253, in get
    conn.c.connect()
  File "/usr/lib/python3.6/http/client.py", line 956, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

The [action history](https://github.com/rook/rook/actions/workflows/canary-integration-test.yml?query=branch%3Amaster) shows that this started happening today after the merge of #9997, which was purely documentation for the upgrade guide except a change to the .mgr pool example, but I don't see how that would be related to this failure of rgw connections.

**Expected behavior:**
Passing tests

**How to reproduce it (minimal and precise):**

Look at the CI history for the rgw-multisite test

**Comment by BlaineEXE** [comment]
I don't see how docs could cause the failure. I wonder if it's just coincidental that the failures are happening since that PR. Could there be an underlying issue? Perhaps Azure is a little bit slower now? Or a Ceph change?
