### ISSUE TITLE
PV definitions do not get updated when mon IPs change

### ISSUE THREAD

**Issue by Ulexus** [rook/rook#1005]
When monitors change IPs, the PV defintions do not get their `spec.rbd.monitors` lists updated.  This causes the kubelet's execution of the related `rbd` commands to fail, which causes the volumes to timeout waiting to mount.

Manually updating the PV definitions causes them to start working again.

**Comment by galexrt** [comment]
@Ulexus This will be fixed by the rook flex volume plugin from @kokhang  https://github.com/rook/rook/pull/882 that will be included in the v0.6 release.

/cc @travisn @kokhang

**Comment by Ulexus** [comment]
I was thinking that was probably the case, but I figured it would be best to log it.

**Comment by Ulexus** [comment]
Good to hear.  Thanks!

**Comment by kokhang** [comment]
@Ulexus the PR for rook to use a flexvolume plugin has just been merged. This will use a different way to attach rbd volumes and no longer will use the kubernetes rbd plugin. https://github.com/rook/rook/issues/432

The new flexvolume also ensures that the mon-ip used are the latest.
You shouldnt see this issue anymore. Please report back if you see any more issues. Thanks

**Comment by Ulexus** [comment]
@kokhang Thanks; I've been monitoring the flexvolume PR.  I'm looking forward to trying v0.6
