### ISSUE TITLE
rook 1.8.3 - redeploying init chart takes approx. 20 min.

### ISSUE THREAD

**Issue by hezise** [rook/rook#10061]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
when redeploying rook-init chart in verstion 1.8.3 it takes approx. 20 min.
while in 1.5.8 it takes a few seconds
both are running under helm 3.2.1

**Expected behavior:**
takes a few min
**How to reproduce it (minimal and precise):**

need to deploy the init cahrt ( which deploy the operator)
then redeploy it.

I don't know what logs to add, since its the same chart nothing really happens, that's why it's strange to me.
attached are the charts

you can see below the time stamp

### Rook 1.5.8
**Wed Apr 13 08:48:52 UTC 2022**
Release "adcc-infra-rook-init" has been upgraded. Happy Helming!
NAME: adcc-infra-rook-init
LAST DEPLOYED: Wed Apr 13 08:48:53 2022
NAMESPACE: rook-ceph
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
The Rook Operator has been installed. Check its status by running:
  kubectl --namespace rook-ceph get pods -l "app=rook-ceph-operator"

Visit https://rook.io/docs/rook/master for instructions on how to create and configure Rook clusters

Note: You cannot just create a CephCluster resource, you need to also create a namespace and
install suitable RBAC roles and role bindings for the cluster. The Rook Operator will not do
this for you. Sample CephCluster manifest templates that include RBAC resources are available:

- https://rook.github.io/docs/rook/master/ceph-quickstart.html
- https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml

Important Notes:
- The links above are for the unreleased master version, if you deploy a different release you must find matching manifests.
- You must customise the 'CephCluster' resource at the bottom of the sample manifests to met your situation.
- Each CephCluster must be deployed to its own namespace, the samples use `rook-ceph` for the cluster.
- The sample manifests assume you also installed the rook-ceph operator in the `rook-ceph` namespace.
- The helm chart includes all the RBAC required to create a CephCluster CRD in the same namespace.
- Any disk devices you add to the cluster in the 'CephCluster' must be empty (no filesystem and no partitions).
- In the 'CephCluster' you must refer to disk devices by their '/dev/something' name, e.g. 'sdb' or 'xvde'.
**Wed Apr 13 08:48:57 UTC 2022**

### Rook 1.8.3
**Tue Apr 12 20:47:47 UTC 2022**
Release "adcc-infra-rook-init" has been upgraded. Happy Helming!
NAME: adcc-infra-rook-init
LAST DEPLOYED: Tue Apr 12 20:47:49 2022
NAMESPACE: rook-ceph
STATUS: deployed
REVISION: 5
TEST SUITE: None
NOTES:
The Rook Operator has been installed. Check its status by running:
  kubectl --namespace rook-ceph get pods -l "app=rook-ceph-operator"

Visit https://rook.io/docs/rook/latest for instructions on how to create and configure Rook clusters

Important Notes:
- You must customize the 'CephCluster' resource in the sample manifests for your cluster.
- Each CephCluster must be deployed to its own namespace, the samples use `rook-ceph` for the namespace.
- The sample manifests assume you also installed the rook-ceph operator in the `rook-ceph` namespace.
- The helm chart includes all the RBAC required to create a CephCluster CRD in the same namespace.
- Any disk devices you add to the cluster in the 'CephCluster' must be empty (no filesystem and no partitions).
**Tue Apr 12 21:06:39 UTC 2022**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):
Linux node1 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
VMWARE

* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.8.3
go: go1.16.13

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)

* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubespray2.15

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
[helm-init-1.5.8.zip](https://github.com/rook/rook/files/8480807/helm-init-1.5.8.zip)
[helm-init-1.8.3.zip](https://github.com/rook/rook/files/8480815/helm-init-1.8.3.zip)

**Comment by travisn** [comment]
@hezise 
- Does this repro consistently for you across different versions of the helm chart? 
- During the 20 minute delay, does the operator pod start? Or this is just the time for the helm install command to complete? If it's just for helm to complete, it sounds like something external to anything rook can control.

**Comment by hezise** [comment]
hi @travisn ,
I'm using the flags --wait and --timeout 360 that means it waits up to 6 min for all components in the chart to be deployed otherwise it fails the deployment.
I can see also in the log that nothing happens to operator and if there was an error helm should fails it once it reaches timeout.
I know that this mechanism is working, because I've tested it. ( deploying bad chart )
All my other charts ( including 1.5.8 ) are redeployed within seconds.
that's why I think that there is maybe another thing causing that.

**Comment by hezise** [comment]
hi @travisn,
I tested it with helm 3.7.2 and it took several seconds.
I'm closing the issue
thanks for you quick response
