### ISSUE TITLE
options to configure rook-ceph containers args ..

### ISSUE THREAD

**Issue by hackaholic** [rook/rook#10072]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

One cannot change ars for csi-porviosioner container, like --timeout
 **csi-provisioner**:
    Container ID:  docker://c830f588d7ebc80ea63fe79d1c5fa60e02c4b45852b1fdd36af2130bcc16926b
    Image:         rt-monitoring_csi_provisioner:v2.0.4
    Image ID:      docker://sha256:82a3b8324d58f06137c68f3a866f42b0e75bec9759a85406eef0f33738cadc9a
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=0
      **--timeout=150s**
      --retry-interval-start=500ms
      --leader-election=true
      --leader-election-namespace=rook-ceph

 
Environment:
OS (e.g. from /etc/os-release):
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Kernel (e.g. uname -a):
uname -a
Linux pwconfig-k8s-master0 3.10.0-1160.42.2.el7.x86_64 

https://github.com/rook/rook/pull/1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Cloud provider or hardware configuration:
Rook version (use rook version inside of a Rook Pod):
{
"mon": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 3
},
"mgr": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 2
},
"osd": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 6
},
"mds": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 2
},
"overall": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 13
}
}
Storage backend version (e.g. for ceph do ceph -v):
ceph -v
ceph version 16.2.2 (e8f22dde28889481f4dda2beb8a07788204821d3) pacific (stable)
Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

**Comment by Madhu-1** [comment]
We can make the timeout configurable it might help in some cases.

**Comment by hackaholic** [comment]
@Madhu-1 yes, as sometime is kube-api dosent respond or restart, In some cases I have seen k8s api unresponsive for more than 150 sec, so in that case I want to increase the timeout.
 **not only timeout any other parameters should be configurable.**

**Comment by Madhu-1** [comment]
> @Madhu-1 yes, as sometime is kube-api dosent respond or restart, In some cases I have seen k8s api unresponsive for more than 150 sec, so in that case I want to increase the timeout. **not only timeout any other parameters should be configurable.**

Please list the what other options you think need to be configurable. #10074 makes timeout configurable for now.

**Comment by hackaholic** [comment]
These below option needs to be configurable:
**--leader-election-lease-duration <duration>**: Duration, in seconds, that non-leader candidates will wait to force acquire leadership. Defaults to 15 seconds.

**--leader-election-renew-deadline <duration>**: Duration, in seconds, that the acting leader will retry refreshing leadership before giving up. Defaults to 10 seconds.

**--leader-election-retry-period <duration>**: Duration, in seconds, the LeaderElector clients should wait between tries of actions. Defaults to 5 seconds.


If its possible then make all the configuration configurable: https://github.com/kubernetes-csi/external-provisioner
