### ISSUE TITLE
upgraded to 1.9.0 and ceph 17.1 and require_osd_release not updated automatically

### ISSUE THREAD

**Issue by taxilian** [rook/rook#10084]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

After upgrading my cluster to 1.9.0 and to ceph 17.1 my cluster was left in a warning state with `OSD_UPGRADE_FINISHED: all OSDs are running quincy or later but require_osd_release < quincy`

**Expected behavior:**

The operator should have set the expected version

**How to reproduce it (minimal and precise):**

I upgraded from 1.8.7, but I think I must have accidentally applied an update from another cluster which set the ceph version to 17.1 before I upgraded the operator with the helm chart -- it immediately started to upgrade to 17.1 as soon as I applied 1.9.0 and I had allow unsupported versions off. I don't know if that's required to reproduce this issue or not, but as it may be relevant I wanted to mention it.

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 20.04
* Kernel (e.g. `uname -a`): 5.4.0-107-generic
* Cloud provider or hardware configuration: bare metal, assorted hardware
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.9.0, go: go1.16.15
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): `17.1.0 (c675060073a05d40ef404d5921c81178a52af6e0) quincy (dev)`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm / bare metal

**Comment by travisn** [comment]
I was able to repro by:
1. Install Rook v1.9 with Ceph v16.2.7
2. Update to Ceph v17.1
3. See the warnings.

The rook operator needs to set the minimum osd version after all the OSDs are upgraded. 

In the meantime, the workaround is to run this from the toolbox:
```
ceph osd require-osd-release quincy
```
