### ISSUE TITLE
Defaulting priorityClassName

### ISSUE THREAD

**Issue by timbuchwaldt** [rook/rook#10090]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Default the priorityClassName to `system-node-critical`.

**What is use case behind this feature:**
rook-ceph is an integral part of the cluster that in most usecases should not be de-scheduleable. 

In a recent outage I saw the storage nodes under high disk pressure (fluentbit spooling went crazy, filling up /) and k8s evicing all rook-ceph pods, only for them to be immediately rescheduled, ending up with ca. 12k (evicted) pods in the namespace, which wasn't well received by the apiserver. This should be prevented in many ways (e.g. ensuring the logging service can't exhibit this behavior), but also IMHO all rook-ceph pods by default should be marked as `system-node-criticial` and a deliberate choice to not run them in this mode should be made by the administrator in case it's not desired.

**Environment**:
Especially bare-metal environments with directly attached disks.

**Comment by travisn** [comment]
Agreed on this, it has been on the back of my mind for too long, time to take care of it!

**Comment by timbuchwaldt** [comment]
Glad to hear I could give the push needed, thank you for the change! :)
