### ISSUE TITLE
ceph-fs-mirror daemon unable to find a keyring 

### ISSUE THREAD

**Issue by BayOfBlackFox** [rook/rook#10105]
Is this a bug report or feature request?

    Bug Report

Deviation from expected behavior:
auth: unable to find a keyring on /etc/ceph/ceph.client.mirror.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory

Expected behavior:

How to reproduce it (minimal and precise):

    Install CephFilesystemMirror with filesystem-mirror.yaml 
    Add mirroring to CephFilesystem
    Add peer from list of Kubernetes Secrets containing the peer token
logs output:
```debug 2022-04-19T15:30:18.249+0000 7f353ffeff80  0 set uid:gid to 167:167 (ceph:ceph)
debug 2022-04-19T15:30:18.249+0000 7f353ffeff80  0 ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable), process cephfs-mirror, pid 1
debug 2022-04-19T15:30:18.249+0000 7f353ffeff80  0 pidfile_write: ignore empty --pid-file
debug 2022-04-19T15:30:18.253+0000 7f353ffeff80  1 mgrc service_daemon_register cephfs-mirror.450319 metadata {arch=x86_64,ceph_release=pacific,ceph_version=ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable),ceph_version_short=16.2.7,container_hostname=dg-k8s-master-1,container_image=quay.io/ceph/ceph:v16.2.7,cpu=Intel(R) Xeon(R) CPU E3-1230 v6 @ 3.50GHz,distro=centos,distro_description=CentOS Stream 8,distro_version=8,hostname=dg-k8s-master-1,id=fs-mirror,instance_id=450319,kernel_description=#121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022,kernel_version=5.4.0-107-generic,mem_cgroup_limit=1073741824,mem_swap_kb=0,mem_total_kb=32703016,os=Linux,pod_name=rook-ceph-fs-mirror-77674f667b-b777n,pod_namespace=rook-ceph}
debug 2022-04-19T15:30:22.269+0000 7f352d971700  0 cephfs::mirror::PeerReplayer(2b56d9fe-c01c-4fef-a826-3de534707242) init: remote monitor host=[v2:192.168.3.10:3300,v1:192.168.3.10:6789]
2022-04-19T15:30:22.281+0000 7f352d971700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.mirror.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2022-04-19T15:30:22.285+0000 7f352d971700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.mirror.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2022-04-19T15:30:22.285+0000 7f352d971700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.mirror.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory```

**Comment by leseb** [comment]
This is a bit misleading message that does not necessarily mean things are not working. Can verify the status of the mirroring and/or see if it is working?
IIRC this was fixed in a Ceph version I just don't remember which one.

**Comment by BayOfBlackFox** [comment]
I see that the client is in the filesystem, but mirroring does not work. I think that when creating folders on the first cluster, they should appear on the second cluster.
![изображение](https://user-images.githubusercontent.com/25629980/164189877-38ac8a76-ec19-489a-9ac9-956a46230817.png)

**Comment by MurzNN** [comment]
The Rook's `keyring-store` configuration is mounted into the `/etc/ceph/keyring-store/` directory, but, regarding to logs, cephfs mirror daemon doesn't try to find it in that directory, with keeping scan defaults directories (/etc/ceph/ceph.client.mirror.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin).

So as workaround we can manually set the keyring path via editing configmap `rook-config-override` like this:
```
[global]
osd pool default size = 2
# workaround for https://github.com/rook/rook/issues/10105
keyring = /etc/ceph/keyring-store
```
This should fix those errors in logs.
