### ISSUE TITLE
Update min K8s version supported to 1.17 

### ISSUE THREAD

**Issue by travisn** [rook/rook#10115]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
K8s 1.16 is currently the min version supported by Rook, but it has the following limitations:
- CSI has a number of limitations such as snapshots are not stable
- Priority classes are not supported

The proposal is to remove support for K8s 1.16 in the next Rook v1.9.x release. 
- Development will be simplified since the CI does not need to run on that version. 
- The min version tested by the CI will now be v1.17.x
- Rook is not prevented from running on K8s 1.16 and may certainly continue running there, it is just not tested by the CI

**Comment by muenchdo** [comment]
We are still using K8s 1.16 in some places

**Comment by travisn** [comment]
> We are still using K8s 1.16 in some places

What version of Rook are those running? If older than v1.9, they will be fine to continue for example on v1.8. The future v1.8 releases will also continue to support K8s 1.16.

**Comment by muenchdo** [comment]
> What version of Rook are those running?

We're on v1.8, which should be fine for us as long as it will continue to support K8s 1.16.
