### ISSUE TITLE
All Rook metadata should be durable

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1011]
This builds on #726, where the longer term solution would be to ensure that the metadata and configuration of the entire cluster is “durable”.  Everything should be regenerateable or backed by a volume. The cluster can live on volumes and operator state.

Imagine running Rook in AWS, the user should be able to specify that all Mon/OSD metadata gets stored on underlying volumes (local storage, EBS, etc.).  If all pods are terminated (but not the PVCs), then new pods should be able to be brought back up with no state being lost and the cluster returns to healthy.

“Zapping” the cluster is a second step that involves zapping the underlying volumes that are storing config/metadata.

**Comment by bassam** [comment]
Said differently, if the cluster is completely destroyed and a new cluster is brought back up with the same Rook state that was in etcd (CRDs, etc.), and the persistent volumes (underneath MON, OSDs), the cluster should look and behave like the old cluster before it was destroyed.

**Comment by barakmich** [comment]
I'd like to request this specifically, with a few more details:

Suppose I have some durable storage on bare-metal, on which I'm storing all of `/var/lib/rook`, the OSD data, and the MON data. These are safe throughout.

Now suppose my cluster gets completely fried. etcd loses it's mind, and everything in the cluster needs rebuilding.

My data, in some sense, is still present, but now I've lost all mapping between where the MONs live, where the data is, etc, etc...

It'd be fantastic if Rook were to snapshot its necessary state, perhaps in the controller, to rebuild from "my data is on disk, but the cluster has forgotten". I'll accept that it may be necessary to reconnect some PVCs to extant PVs, but the PVs should get recreated from the fact the underlying pools and objects exist.

**Comment by bassam** [comment]
@barakmich that should be possible if we can find all the underlying `/var/lib/rook` dirs. There is enough state in those directories to bring up the cluster.

Would be great if we also snapshotted the CRDs somewhere as you point out.

**Comment by barakmich** [comment]
@bassam Good to know. Should I file a separate issue?

**Comment by mingfang** [comment]
I have a similar scenario such that Rook takes over the EBS volumes so that my hosts are ephemeral.
The EBS volumes should be partitioned so that /var/lib/rook can live in one partition and bluestore can take over the rest.  That way no matter what host the EBS device is attached Rook can simply continue working.

**Comment by liewegas** [comment]
If we're only concerned about OSD data, then partitions won't be needed. ceph-volume labels the LVM volumes with the metadata needed, so you just need to map one EBS volume per OSD, and it will be able to be attached to any host, discovered, and the OSD started.  Once we make the ceph-volume switch in 0.9.

The mon data, on the other hand, has no magic.  It's just a directory with some random files and a rocksdb.  Usually it is on the boot device and is never reattached to another host.

**Comment by Timer** [comment]
Would love to see this. Bump. :-)

**Comment by galexrt** [comment]
For `ceph-volume` OSDs the metadata will be durable, see https://github.com/rook/rook/pull/2242/files/3a599e7fb43a4509efb4fbae36cdc7ccb751a347#diff-da4992f27747434e67a1ec76d4411fa0. Thanks @travisn!

**Comment by kfox1111** [comment]
Is this still relevant?

**Comment by travisn** [comment]
With the feature of backing mons and OSDs by PVs, and [this guide](https://rook.io/docs/rook/v1.1/disaster-recovery.html) for disaster recovery when K8s completely fails, I believe we are covered for this original issue. There is certainly room for improvement in the disaster recovery guide, but let's close this original issue.
