### ISSUE TITLE
Is Rook suitable to be used on a public cloud?

### ISSUE THREAD

**Issue by fzyzcjy** [rook/rook#10152]
Hi thanks for the library! I wonder whether it is suitable to be used on a public cloud? When I self-create the kubernetes cluster (using microk8s), the public cloud I am using does not provide CSI provisioners, so I want to use Rook. However, the disks attached to cloud servers are not "physical" disks that is "physically" directly connected to the server, but instead cloud disks. Therefore, I wonder whether Rook is suitable for this case since it adds another indirection?

**Comment by fzyzcjy** [comment]
@travisn Well, for cluster-on-pvc, I guess it is not possible for my public cloud. The reason is that, my public cloud does *not* provide any storage provisioner if I create my own k8s cluster (unlike AWS or GCE). That is mainly why I have to create my own.

By the way, I have just read your blog about half an hour ago, and then see your reply ;)

**Comment by chrisjsimpson** [comment]
To add to this, dependong on public cloud provider your instances may or may not passthrough enough information to ceph to detect the 'virtual' disks.

commands to help:
```
ceph orch device ls
#probing
cephadm shell lsmcli ldl
```
