### ISSUE TITLE
Support for ceph-fuse

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1015]
In the very immediate future, rook will rely on ceph-fuse to mount cephfs. Currently it is using the kernel driver. 

In order to do this, we need to add ceph-fuse to the container image.

**Comment by bassam** [comment]
repurposing the ticket to support ceph-fuse.

**Comment by drake7707** [comment]
Any updates on this? I've run into an issue where I can't use block storage devices because I'm running from a separate network namespace and the kernel driver only supports the initial network namespace and I can't specify --net=host to circumvent this.
