### ISSUE TITLE
mon: quorumStatus.MonMap.Mons changed to Quorum

### ISSUE THREAD

**Issue by fengjiankui121** [rook/rook#10165]
**Is this a bug report or feature request?**
* Bug Report

During mon's health check, when the mon isn't in the clusterInfo, but is in quorum and there are enough mons in quorum, remove it.

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by fengjiankui121** [comment]
The current condition for judging whether a mon should be deleted is whether there are enough mons in the monMap.The relevant code is as follows：

if _, ok := monsNotFound[mon.Name]; ok {
delete(monsNotFound, mon.Name)
} else {
if inQuorum && **len(quorumStatus.MonMap.Mons) > desiredMonCount** {
logger.Warningf("mon %q not in source of truth but in quorum, removing", mon.Name)
if err := c.removeMon(mon.Name); err != nil {

**Comment by fengjiankui121** [comment]
It should be changed to:

if _, ok := monsNotFound[mon.Name]; ok {
delete(monsNotFound, mon.Name)
} else {
if inQuorum && **len(quorumStatus.Quorum) > desiredMonCount** {
logger.Warningf("mon %q not in source of truth but in quorum, removing", mon.Name)
if err := c.removeMon(mon.Name); err != nil {

**Comment by travisn** [comment]
Thanks for pointing out this improvement, it looks technically correct to me. Would you like to open a PR with this improvement? See the [developer guide](https://rook.github.io/docs/rook/v1.9/development-flow.html#submitting-a-pull-request).

How did you find this? Did you see an issue in a live cluster where a mon was removed when it shouldn't be?

**Comment by fengjiankui121** [comment]
@travisn  Yes, I would like.
