### ISSUE TITLE
Dynamically expand or SHRINK pvc 

### ISSUE THREAD

**Issue by Daxcor69** [rook/rook#10188]
**What should the feature do:**
Currently there is only a provision to expand a volume.  When I look the ceph docs I find this:

Ceph Block Device images are thin provisioned. They don’t actually use any physical storage until you begin saving data to them. However, they do have a maximum capacity that you set with the --size option. If you want to increase (or decrease) the maximum size of a Ceph Block Device image, execute the following:

rbd resize --image foo --size 2048

**What is use case behind this feature:**

My customers can change how  much storage they want to purchase.  If they purchase too much, I want to give them the ability to change their plan to a smaller storage amount.  This would hinge on the fact that their actual data present would fit the new size.

**Environment**:
rook/ceph Block

**Comment by Madhu-1** [comment]
Dynamically expansion can be configured by external operators. SHRINK is not something supported by kubernetes.

**Comment by parth-gr** [comment]
https://github.com/rook/rook/blob/master/tests/scripts/auto-grow-storage.sh this may help you
