### ISSUE TITLE
Error upgrading rook-ceph-cluster 1.9.2 via helm

### ISSUE THREAD

**Issue by encausticcello** [rook/rook#10192]
Hi, we're attempting to upgrade a 1.8.x cluster to 1.9.2 using Helm. The operator upgrade went fine, however, when we try to upgrade we're getting the following helm error:

Error: UPGRADE FAILED: cannot patch "ceph-objectstore" with kind CephObjectStore: Internal error occurred: failed calling webhook "cephobjectstore-wh-rook-ceph-admission-controller-rook-ceph.rook.io": Post "[https://rook-ceph-admission-controller.rook-ceph.svc:443/validate-ceph-rook-io-v1-cephobjectstore?timeout=5s](https://rook-ceph-admission-controller.rook-ceph.svc/validate-ceph-rook-io-v1-cephobjectstore?timeout=5s)": dial tcp 10.43.60.90:443: connect: connection refused

We're using the new values for cephObjectStores (it looks like the only update here is adding resource request/limits + priorityClassName)

**Comment by travisn** [comment]
@encausticcello Please share the rook operator log to see if there was some error starting the admission controller.
If this is blocking your upgrade, note you can disable the admission controller with [this setting](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml#L407).

**Comment by encausticcello** [comment]
I'm not seeing any errors in the operator. I have noticed 1.9.2 of the operator is frequently getting OOMKilled events and restarting. The cluster upgrade still seems to have completed, even though helm upgrade threw the error above. I tried helm upgrade again, commenting out the resources + priorityClassName in the helm chart, and the helm upgrade was successful. 

However, in troubleshooting an ingress rule, it seems that the admission controller is intermittently failing to connect.

[rook-ceph-operator-7f8597fd56-dwfb7_rook-ceph-operator.log](https://github.com/rook/rook/files/8592526/rook-ceph-operator-7f8597fd56-dwfb7_rook-ceph-operator.log)

**Comment by ondrej-smola** [comment]
Same here, 
when upgrading from 1.9.0 to 1.9.2 using ansible/helm got 

`
fatal: [k8s-master1.maas]: FAILED! => {"changed": false, "command": "/usr/local/bin/helm --version=v1.9.2 upgrade -i --reset-values --values=/etc/ng/ceph.yml rook-ceph-cluster rook/rook-ceph-cluster", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: UPGRADE FAILED: cannot patch \"ceph-objectstore\" with kind CephObjectStore: Internal error occurred: failed calling webhook \"cephobjectstore-wh-rook-ceph-admission-controller-ceph.rook.io\": failed to call webhook: Post \"https://rook-ceph-admission-controller.ceph.svc:443/validate-ceph-rook-io-v1-cephobjectstore?timeout=5s\": dial tcp 10.20.114.33:443: connect: connection refused\n", "stderr": "Error: UPGRADE FAILED: cannot patch \"ceph-objectstore\" with kind CephObjectStore: Internal error occurred: failed calling webhook \"cephobjectstore-wh-rook-ceph-admission-controller-ceph.rook.io\": failed to call webhook: Post \"https://rook-ceph-admission-controller.ceph.svc:443/validate-ceph-rook-io-v1-cephobjectstore?timeout=5s\": dial tcp 10.20.114.33:443: connect: connection refused\n", "stderr_lines": ["Error: UPGRADE FAILED: cannot patch \"ceph-objectstore\" with kind CephObjectStore: Internal error occurred: failed calling webhook \"cephobjectstore-wh-rook-ceph-admission-controller-ceph.rook.io\": failed to call webhook: Post \"https://rook-ceph-admission-controller.ceph.svc:443/validate-ceph-rook-io-v1-cephobjectstore?timeout=5s\": dial tcp 10.20.114.33:443: connect: connection refused"], "stdout": "", "stdout_lines": []}
`

No errors in operator logs, whole cluster seems to upgrade afterwards.

**Comment by travisn** [comment]
Were the operator and cluster charts upgraded around the same time? Perhaps the operator just happened to restart at the time the cluster chart was updated. If the operator is down it would cause the error, but a retry will likely succeed since the operator was only down temporarily.

**Comment by travisn** [comment]
That's helpful, the 256Mi default must not be sufficient for the memory limit.
