### ISSUE TITLE
document description error

### ISSUE THREAD

**Issue by Aurorxa** [rook/rook#10194]
**Is this a bug report or feature request?**
* Bug Report
  there has a command in this page "https://rook.io/docs/rook/v1.9/quickstart.html",
```shell
git clone --single-branch --branch v1.9.2 https://github.com/rook/rook.git
cd rook/deploy/examples
kubectl create -f crds.yaml -f common.yaml -f operator.yaml
kubectl create -f cluster.yaml
```
when i use this command in k8s (v1.21.10) ，i found this error，csi-cephfsplugin-provisioner and csi-rbdplugin-provisioner is alaways 5/6 and CrashLoopBackOff ，but when is use the following command，i found the error disappear
```shell
wget https://github.com/rook/rook/archive/refs/tags/v1.9.2.zip
unzip v1.9.2.zip
cd rook/deploy/examples
kubectl create -f crds.yaml -f common.yaml -f operator.yaml
kubectl create -f cluster.yaml
```

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by travisn** [comment]
@Aurorxa Do you have the pod logs and the pod description for the pods in crashloopbackoff? There isn't enough info to debug here. And it must be a coincidence with the commands you used to get the repo since there would be no difference in those two methods for how the pods are created. But more details will help determine.

**Comment by Aurorxa** [comment]
Sorry, when I retest today, I don't know why it seems that it can be started. It's hateful that I didn't save the error log at the beginning. It is also possible that the configuration of the machine is too low, because I remember that I have several nodes, and I have assigned 1 core。
![Snipaste_2022-05-03_14-44-11](https://user-images.githubusercontent.com/25677587/166413868-a3f6049f-c8d7-49c2-bca0-913089cae7f9.PNG)
