### ISSUE TITLE
Need a way to specify which disks to use and not use

### ISSUE THREAD

**Issue by bassam** [rook/rook#102]
Currently `CASTLED_DATA_DEVICES` supports devices name such as sdb which are not stable and could vary on every boot. We need to support different options for specifying which disks to use and not use for storage.

One option would be to let the user use ALL disks for storage except the system disk. It would be easy to find the system disk and exclude it. For example,

```
CASTLED_DATA_DEVICES=all
```

For this case, the system disk should be excluded and become an INFO message, instead of:

```
Oct 24 16:03:26 castle00 rkt[1528]: 2016-10-24 16:03:26.685353 I | ERROR: failed to config osd on device sdd. failed device sdd. device sdd already formatted with ext4
```

Another option would be to support an arbitrary filtering criteria for disks based on information obtainable by libblkid or lsblk, for example:

```
CASTLED_DATA_DEVICES=“SUSBSYSTEM=block:scsi:pci,SIZE>=5TB"
```

**Comment by travisn** [comment]
Using the properties of lsblk, sgdisk, etc, it's clear that we could develop a language for specifying which block devices to use. As long as a human is involved, he could make the right decision to select the serial number, device type, name, uuid, size, model, partition properties, etc. 

What is not clear is how the user could automate selecting the right devices. The user would hopefully have a homogeneous set of machines where he can say "go use all the devices with property X". Still, he needs to make sure he doesn’t select the device with the system volume. In some cases he may know which device the system is on and in homogeneous environments it might be really difficult to distinguish.

In our simple vagrant environment there are only a couple properties of lsblk that could differentiate the system volume. It happens to have `TRAN="ata"`, while the raw devices have `TRAN="sata"`, and the size is different. We could use those properties reliably in our example, but in a sample app we should rather use a more general approach and leave the advanced criteria for a more advanced sample.
 
Thus, we come back to the simple example use the `all` option, where we automatically exclude certain devices that we don’t think meet the criteria, such as if they have partitions or a file system. This is implemented with https://github.com/rook/rook/pull/287.

For advanced cases, we can support the language of inclusion based on the lsblk properties. This would allow an admin to be certain that he is selecting the devices with a certain serial number or other specific properties. This implementation could wait for a future version of rook.

**Comment by bzub** [comment]
Further discussion in #397
