### ISSUE TITLE
Phantom OSD can not be deleted

### ISSUE THREAD

**Issue by mosesdd** [rook/rook#10215]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
According to the [documentation](https://github.com/rook/rook/blob/master/Documentation/ceph-advanced-configuration.md#phantom-osd-removal) it should be possible to delete phantom OSDs but the ceph command expects a numerical value

`[rook@rook-ceph-tools-87994b6fd-c657z /]$ ceph osd out -7`
`Error EINVAL: expected numerical value, got: -7invalid osd id-22`

**Expected behavior:**
Phantom OSD gets deleted
**How to reproduce it (minimal and precise):**

Try to delete host without any osd attached

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.9.2
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by mosesdd** [comment]
I found a way to fix this, the phantom host can be deleted with:

`ceph osd crush remove <hostname>`

**Comment by travisn** [comment]
@mosesdd Does this doc on [OSD Removal](https://rook.github.io/docs/rook/v1.9/ceph-osd-mgmt.html#remove-an-osd) answer the question?

**Comment by mosesdd** [comment]
@travisn No it doesn't. There is now word about deleting phantom OSDs

**Comment by travisn** [comment]
Got it. So all the steps in that section on removing a phantom id worked for you, except that one that required the host name? I didn't even realize any of those would work with the negative id.

In any case, we should probably move these instructions to the doc on [OSD Management](https://rook.github.io/docs/rook/v1.9/ceph-osd-mgmt.html). @galexrt sound good?
