### ISSUE TITLE
rook-ceph-mgr needs to be HA

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1022]
The rook-ceph-mgr deployment is currently deploying one ceph-mgr pod. From today's ceph talk, it was suggested to have more than one in order to do an active-backup HA.

It was also suggested to be placed along side the monitors.

**Comment by bassam** [comment]
> It was also suggested to be placed along side the monitors.

I don't think thats needed in a K8S deployment. The advice is great when you are deploying ceph directly on nodes.

**Comment by travisn** [comment]
This was actually fixed by #1048. Now we have a standby mgr
