### ISSUE TITLE
Mention the discover daemon in the troubleshoot readme to solve problems with missing osd-prepare pods

### ISSUE THREAD

**Issue by Atomique** [rook/rook#10220]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
I had an issue while deploying the rook-ceph cluster into Kubernetes. The operator didn't create the osd-prepare Pods. While searching for the root-cause of this problem, I landed at this documentation: https://github.com/rook/rook/blob/master/Documentation/ceph-common-issues.md#osd-pods-are-not-created-on-my-devices 
But there was no hint how to solve this. After discussing this issue with Alexander on Slack, I found out that I need to enable the discover daemon, if I want to create them for RAW-Devices. 

Links he gave me to solve this: 
https://rook.io/docs/rook/v1.9/quickstart.html#deploy-the-rook-operator 
https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml#L381

**What is use case behind this feature:**
Maybe it would be a nice idea to add this to the documentation to make it easier to deploy rook-ceph and fix the issue by my own!

**Environment**:
I just tried to deploy rook-ceph in version 1.9.2 via helm/manifest on kubernetes 1.21 (RKE2 cluster), but this shouldn't be neccessary to know for this topic.

**Comment by travisn** [comment]
The discover daemon is only needed for a very small scenario, which is to actively watch for hotplug devices on which new OSDs could be created at a later time. The discover daemon therefore does not commonly need to be enabled in most clusters. Rook finds everything it needs to create OSDs when the OSD prepare jobs are run. 

If the OSD prepare jobs are not created, this should mean that the Ceph mons did not form quorum, which is described in [this topic](https://rook.github.io/docs/rook/v1.9/ceph-common-issues.html#monitors-are-the-only-pods-running). 

The documentation could certainly be clarified on these two points.
