### ISSUE TITLE
test: Add bluestore coverage in the integration tests

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1023]
We currently only use filestore in the integration tests, but we should also be testing bluestore as well, as that is now the default data path in Luminous.

The issue is that Rook only supports block devices (not directories) for bluestore and our integration test environments (kubeadm, minikube, AWS, GCE) don't all have available block devices for bluestore.  This could be made easier with #398, but for now it would be nice for our integration tests to ensure that block devices are available on the nodes under test and to use bluestore for the OSDs.

**Comment by DanKerns** [comment]
This isn't just a test issue. It's something the cluster needs to support that it doesn't today.
