### ISSUE TITLE
Recreated as operator's StrategyType

### ISSUE THREAD

**Issue by fengjiankui121** [rook/rook#10237]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

Recreated as operator's StrategyType

**How to reproduce it (minimal and precise):**

1. During the upgrade of rook, the mirror and cluster of rook have changed.
2. The StrategyType of the operator is set to RollingUpdate,
3. Upgrade rook, cluster upgrade successfully
3. The newly created operator pod was not started successfully
4. The operator pod before the upgrade is still running
5. At this point, the operator pod before the upgrade will run according to the upgraded cluster

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by fengjiankui121** [comment]
@travisn 
1. right
2. the failure is that the previous operator still exists, causing the newly created operator to fail to be created successfully.

**Comment by sp98** [comment]
@fengjiankui121 Need some information about the `Steps to reproduce` mentioned in the description. 

>>  6. At this point, the operator pod before the upgrade will run according to the upgraded cluster

If I'm not wrong, the rook operator upgrade is the first step. After the operator pod (with upgraded rook image) is started, other resources get upgraded. How came we reach a situation where cluster is upgraded before the operator starts with the upgraded image (as mentioned in step 6)?
