### ISSUE TITLE
add more ceph telemetry metrics

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#10251]
* Feature Request

**What should the feature do:**
Add more metrics to the Ceph `config-key` database for reporting via Ceph telemetry. We already implement `rook-version` in #10161.

### Potential other metrics that might be good for Rook to collect:
- [ ] `rook-kubernetes-version` - kubernetes version, which is similar to the already collected os/kernel versions
- [ ] `rook-ceph-csi-version` - Ceph CSI version
  - already collected in CSI code, but we might want to return it back to the operator to report it at a higher level
- [ ] num CSI plugin pods running - this gives idea of how many k8s nodes are in the k8s cluster that are allowed to use Ceph storage but may not show the full size of the k8s cluster
  - we can count plugin pods separately; this is easier since each daemonset is a different label, plus it can show if some CSI drivers are ever disabled
  - `rook-num-csi-rbd-plugin-pods`
  - `rook-num-csi-cephfs-plugin-pods`
  - `rook-num-csi-nfs-plugin-pods`
- [ ] `rook-num-nodes` - num nodes on which the cluster has running pods 
  - since clusters with portable PVCs have one "node" per PVC, this will help show the actual node count for Rook installs in portable environments
- [ ] `rook-num-storage-classes` number of storageclasses related to the current ceph cluster. we can also break this up by specific kinds of storage classes, but the overall may be useful if new classes are added in the future
  - [ ] `rook-num-rbd-storage-classes`
  - [ ] `rook-num-cephfs-storage-classes`
  - [ ] `rook-num-nfs-storage-classes`
  - [ ] `rook-num-bucket-storage-classes` (count num classes for lib-bucket-provisioner)
- [ ] `rook-num-storage-class-device-sets` - number of storageclassdevicesets
  - it might also be useful to collect some more info about the device sets in a structure that could tell us de-identified info about the sets like below. Mostly, I think portable is the interesting field. Ceph already does something like this for pools:
  - ```json
    "rook-storage-class-device-sets": [
      {
        "count": 3,
        "config": [],
        "portable": true,
      },
      "etc..."
    ]
    ```
  - this might not be good because this allows the values in the config-key db to be arbitrarily sized, but the scope should normally be fairly small. Not sure if the telemetry team would be okay with this or not.
  - we could alternatively have a `rook-num-portable-storage-class-device-sets` field.
- [ ] `rook-mons-are-pvc` - true/false mons are on PVC
- [ ] `rook-network-provider` - e.g., default, host, multus
- [ ] `rook-external-mode` - true/false if external mode cluster
 
Thought:
[Travis] Count of each type of CR: cluster, object, file, object store, mirror, bucket topic, bucket notification, etc.
[Blaine] This seems good, but this will be a hard catch-up game to play with features added to Rook with Ceph versions. We were told we can't have an arbitrary structure in the keys we provide, but maybe an exception could be made for this specific case?

### Information we are interested in that is already collected by telemetry:
- RBD pools (name is stripped) and number of them
- filesystems & mds info
- RGW count, zonegroups, zones

### Other metrics that Ceph might collect:
- number of NFS clusters
  - Ceph can count NFS clusters by listing the namespaces in the `.nfs` pool and report those namespaces that have `conf-nfs.<namespace>` objects present
- filesystem mirroring info

**Comment by travisn** [comment]
> * kubernetes version, which is similar to the already collected os/kernel versions

+1

> * CSI driver versions (important to show only version and not image name since image name could have organization name in it)
>   
>   * this may be really hard for Rook to collect; maybe we should consider if the CSI drivers can add this info to the config-key database

Rook runs a detect csi version job, so we should actually have this version already.

> * num CSI plugin pods running (count rbd, cephfs, and nfs separately) - this gives idea of how many k8s nodes are in the k8s cluster using Ceph storage (but may not show the full size of the k8s cluster)

What if we report the following?
- Number of K8s nodes
- Number of rbd volume plugin pods
- Number of cephfs volume plugin pods

> * num nodes on which the cluster has running pods - since clusters with portable PVCs have one "node" per PVC, this will help show the actual node count for Rook installs in portable environments

Is this the number of nodes on which ceph daemons are running? Perhaps we could gather that simply by the number of crash collector pods, which should have one per node with ceph daemons.

> * [addendum] number of storageclasses related to the current ceph cluster (can break up by block, file, nfs, and bucket if desired)
 
+1 for counting each type of storage class

Here are a few more I might add to the wish list:
- Number of storageClassDeviceSets
- Whether mons are backed by PVCs
- `network.provider` from the cluster CR (multus, host, or default)
- Count of each type of CR: cluster, object, file, object store, mirror, bucket topic, bucket notification, etc
- Whether external mode (though perhaps this is easily implied by 0 mons, 0 osds, etc)

**Comment by BlaineEXE** [comment]
> > * num nodes on which the cluster has running pods - since clusters with portable PVCs have one "node" per PVC, this will help show the actual node count for Rook installs in portable environments
> 
> Is this the number of nodes on which ceph daemons are running? Perhaps we could gather that simply by the number of crash collector pods, which should have one per node with ceph daemons.

I thought about that as a shorthand for finding the info, but the crash collectors can be disabled. For those clusters, we couldn't get this info. We could give a `nil` value (or `undefined` or `n/a` or something) if they have crash collectors disabled. Or we could go the long route to get it in such a way that it's possible each time.

> > * [addendum] number of storageclasses related to the current ceph cluster (can break up by block, file, nfs, and bucket if desired)
> 
> +1 for counting each type of storage class
> 
> Here are a few more I might add to the wish list:
> 
> * Number of storageClassDeviceSets
> * Whether mons are backed by PVCs
> * `network.provider` from the cluster CR (multus, host, or default)
> * Count of each type of CR: cluster, object, file, object store, mirror, bucket topic, bucket notification, etc
> * Whether external mode (though perhaps this is easily implied by 0 mons, 0 osds, etc)

I think all these are good ideas and very possible with the exception of the count of each CR. This seems good, but it could lead to a hard catch-up game to play with features added to Rook and with Ceph versions. We were told we can't have an arbitrary structure in the keys we provide, but maybe an exception could be made for this specific case since it won't have user identifiable info? I'd rather not have a lot of back-and-forth between telemetry collected when features are added to Rook as much as we can help it.

> Number of K8s nodes

I wonder if this would be over-stepping the bounds of what it is useful for Ceph to know. I think it's more important to know how many nodes have Ceph storage enabled than the total size of the k8s cluster. I think `rook-num-csi-rbd-plugin-pods` (and the others) may be more relevant for Ceph telemetry.

**Comment by travisn** [comment]
> I think all these are good ideas and very possible with the exception of the count of each CR. This seems good, but it could lead to a hard catch-up game to play with features added to Rook and with Ceph versions. We were told we can't have an arbitrary structure in the keys we provide, but maybe an exception could be made for this specific case since it won't have user identifiable info? I'd rather not have a lot of back-and-forth between telemetry collected when features are added to Rook as much as we can help it.

Yeah, would be nice if we could have that structure for CRD types to avoid going back and forth. But we don't add CRDs very often either.

>> Number of K8s nodes

> I wonder if this would be over-stepping the bounds of what it is useful for Ceph to know. I think it's more important to know how many nodes have Ceph storage enabled than the total size of the k8s cluster. I think rook-num-csi-rbd-plugin-pods (and the others) may be more relevant for Ceph telemetry.

I'm thinking of this as adding rook metrics, not just ceph, so overall node count seems useful. Most of the time it will likely be the same as other node metrics, but will be interesting to see how many clusters choose to use a subset of nodes for rook.

**Comment by BlaineEXE** [comment]
Closing to discuss as a design doc in #10254
