### ISSUE TITLE
Unable to create Ceph snapshots using cluster-on-pvc configuration on GKE.

### ISSUE THREAD

**Issue by ptmkarvinen** [rook/rook#10270]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

`sudo mkdir /files/.snap/mysnapshot`

returns

`mkdir: can't create directory '/files/.snap/mysnapshot': Permission denied`

**Expected behavior:**

The above command would create a Ceph snapshot.

**How to reproduce it (minimal and precise):**

1. git clone --single-branch --depth=1 --branch v1.8.9 https://github.com/rook/rook.git
2. change storageClassName to "standard-rwo" on rook/deploy/examples/cluster-on-pvc.yaml (both mon and storageClassDeviceSets).
3. kubectl create -f crds.yaml -f common.yaml -f operator.yaml
4. kubectl create -f cluster-on-pvc.yaml
5. kubectl create -f csi/cephfs/storageclass.yaml
6. kubectl create -f filesystem.yaml
7. create a claim to consume (example file below)
8. mount claim to a pod (mountPath /files), attempt to create a snapshot using "sudo mkdir /files/.snap/mysnapshot".

The volume is fully usable on the pod otherwise, and is not in ReadOnly mode.

**File(s) to submit**:

claim.yaml:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testclaim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
```

**Environment**:
* OS (e.g. from /etc/os-release):

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

* Kernel (e.g. `uname -a`):

Linux gke-xxxx-xxxx-xxxxx-default-pool-xxxxxxxx-xxxx 5.4.0-1065-gke #68-Ubuntu SMP Wed Mar 2 14:58:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:

Google Kubernetes Engine (GKE)

* Rook version (use `rook version` inside of a Rook Pod):

rook: v1.8.9
go: go1.16.15

* Storage backend version (e.g. for ceph do `ceph -v`):

ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)

* Kubernetes version (use `kubectl version`):

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

GKE

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

HEALTH_OK

**Comment by Rakshith-R** [comment]
@ptmkarvinen please refer to https://github.com/rook/rook/blob/master/Documentation/ceph-csi-snapshot.md.

**Comment by ptmkarvinen** [comment]
Hey,

Isn't that for pvc snapshots? CephFS has a built-in snapshot feature as documented here https://docs.ceph.com/en/quincy/dev/cephfs-snapshots/, is this method not usable with the csi-plugin? It definitely works on a configuration without it.

**Comment by Rakshith-R** [comment]
> Hey,
> 
> Isn't that for pvc snapshots? CephFS has a built-in snapshot feature as documented here https://docs.ceph.com/en/quincy/dev/cephfs-snapshots/, is this method not usable with the csi-plugin? It definitely works on a configuration without it.

Cephfs Pvc is basically a cephfs subvolume. https://docs.ceph.com/en/quincy/cephfs/fs-volumes.html#fs-subvolumes
You should be using a k8s snapshot implementation, which takes cephcsi supported snapshot of entire subvolume.

**Comment by Rakshith-R** [comment]
> Hey,
> 
> Isn't that for pvc snapshots? CephFS has a built-in snapshot feature as documented here https://docs.ceph.com/en/quincy/dev/cephfs-snapshots/, is this method not usable with the csi-plugin? It definitely works on a configuration without it.

Cephfs Pvc is basically a cephfs subvolume. https://docs.ceph.com/en/quincy/cephfs/fs-volumes.html#fs-subvolumes
You should be using a k8s snapshot implementation, which takes cephcsi supported snapshot of entire subvolume.

**Comment by Madhu-1** [comment]
> Hey,
> 
> Isn't that for pvc snapshots? CephFS has a built-in snapshot feature as documented here https://docs.ceph.com/en/quincy/dev/cephfs-snapshots/, is this method not usable with the csi-plugin? It definitely works on a configuration without it.

This is not a supported feature. If you need snapshot functionality please make use of kubernetes volumesnapshots https://github.com/rook/rook/blob/master/Documentation/ceph-csi-snapshot.md.

**Comment by ptmkarvinen** [comment]
Hey,

Thank you for the clarification. You may close the issue.

Have a nice week! :)
