### ISSUE TITLE
enable features for DR site backup of k8s PVC filestore and object store.

### ISSUE THREAD

**Issue by alokhom** [rook/rook#10287]
**Feature to backup and restore PVCs. filestore content, object store contents into a new location (instance) different from the rook ceph storage instance**

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
* It should make use of CRDs and establish operator pods to help the user make a live copy of PVC/k8s-manifests into a all-new location which is nothing but another instance of k8s rook-ceph storage. 

**What is use case behind this feature:**
* Adoption of this feature will help the user plan a DR site to keep a live copy of all the k8s resources and pvc data to the most minimal RPO ( recovery point objective) if the production cluster is not recoverable. 

**Environment**:
* any 1.2x version k8s with rook-ceph deployed ( source cluster) 
* any 1.2x version k8s with rook-ceph DR instance deployed
* Pods with PVC created using several storage classes of rook-ceph in source cluster. 
* CRD based backup operator pods using a CR spec with DR site to copy from source RBD to remote RBD. 
![image](https://user-images.githubusercontent.com/12021776/169366604-ba9bb78c-4ab7-4eea-8670-cb71e6256a06.png)

**Comment by travisn** [comment]
In Slack I just shared these two topics for RBD mirroring. (Our docs are going through some changes, so I'll post the new links)
- [RBD Mirroring](https://rook.github.io/docs/rook/latest/Storage-Configuration/Block-Storage-RBD/rbd-mirroring/)
- [Failover/failback](https://rook.github.io/docs/rook/latest/Storage-Configuration/Block-Storage-RBD/rbd-async-disaster-recovery-failover-failback/)

There are also topics for other types of mirroring:
- [CephFS Mirroring](https://rook.github.io/docs/rook/latest/CRDs/Shared-Filesystem/ceph-fs-mirror-crd/)
- [RGW Multisite](https://rook.github.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite/)

Does that answer the feature request already? Or can you describe what is missing?

**Comment by alokhom** [comment]
Yes, i have seen them. These are specialised skills and I am not sure many k8s users who just want to get started have all the ceph skills. 

I have personally witnessed a situation when a decision to adopt rook-ceph was being taken by a large enterprise and the big question that was asked was how do you backup the data because there were competitive storage solutions who also provided backup/restore as well besides cloud native storage. My answer was if there an external consumption of ceph to make the PVCs for the pods in a k8s cluster, the data always remains external and there is no problem, but in the hyperconverged ceph it is always possible to lose the cluster storage nodes. So its hard to say if we can get the data back to the Pods in a new cluster or how much time it would take to recover data. I request you to make a feature( CRD / opertor) which will encapsulate the best of the above ceph links that you have provided and enable the k8s user to just configure a DR site to backup his data. And that could any pod PVC data. So that, it is recoverable in a new cluster or use up the DR cluster to rebuild the pods and keep low downtime. At the moment we donot have a definite downtime of getting back the ceph cluster inside k8s if something happens.

**Comment by travisn** [comment]
For offsite backup/restore of PVs, Velero has worked well for many users. Are you looking for individual PV backup, or to backup/restore the entire Ceph cluster? If it's the entire cluster, that's really where the DR becomes useful with the mirroring.

**Comment by thotz** [comment]
Wrt RGW IMO multisite replication will be replicating data between two clusters, but k8s resources like `obc` and' cephobjectstoreusers' are not handled correctly. So

**Comment by mrhein** [comment]
you can combine velero for config with https://github.com/kubernetes-csi/external-snapshotter/releases cronmanaged via https://github.com/backube/snapscheduler and both variants @travisn wrote (cephfs + rdb) the underling network can be paired with cluster mesh if you use something like cilium
