### ISSUE TITLE
make build is failing on master with invalid version dependency on libopenstorage/secrets

### ISSUE THREAD

**Issue by gauravsitlani** [rook/rook#10297]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
On my new laptop I'm trying to build Rook on Fedora 36 and its failing with the following Error :

```
=== ensuring modules are tidied
go: downloading github.com/tencentcloud/tencentcloud-sdk-go v3.0.171+incompatible
go: github.com/libopenstorage/secrets@v0.0.0-20210709082113-dde442ea20ec requires
	github.com/hashicorp/vault@v1.4.2 requires
	github.com/hashicorp/go-kms-wrapping@v0.5.1 requires
	github.com/hashicorp/vault/sdk@v0.1.14-0.20191229212425-c478d00be0d6: invalid version: unknown revision c478d00be0d6
make: *** [build/makelib/golang.mk:174: go.mod.check] Error 1
```

**Expected behavior:**
Build shouldn't fail.

**How to reproduce it (minimal and precise):**
1. Cloned the rook repository
2. Ran `make build --debug` to build rook

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Fedora 36 
* Kernel (e.g. `uname -a`): 5.17.5-300.fc36.x86_64

**Comment by gauravsitlani** [comment]
@thotz I had noticed you had reported similar issue before on : https://github.com/libopenstorage/secrets/issues/50
Is the current issue similar to that ?

**Comment by thotz** [comment]
@gauravsitlani please refer https://github.com/rook/rook/issues/6583

**Comment by gauravsitlani** [comment]
@thotz thanks. The issue went away after following : https://github.com/rook/rook/pull/6602#issuecomment-854994236
