### ISSUE TITLE
object: supporting aws sse:s3 in RGW

### ISSUE THREAD

**Issue by thotz** [rook/rook#10317]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Configure RGW to handle `sse:s3` requests from client

**What is use case behind this feature:**
The server side encryption for s3 protocol

**Environment**:

**Comment by thotz** [comment]
Design doc posted in https://github.com/rook/rook/pull/10318

**Comment by travisn** [comment]
Implemented by #10204.
