### ISSUE TITLE
Single node can't use useOperatorHostNetwork

### ISSUE THREAD

**Issue by M-Gregoire** [rook/rook#10334]
* Bug Report

**Deviation from expected behavior:**

I've deployed `rook` (Using Helm) in a k3s single-node cluster and want to be able to mount volumes from outside the cluster. To do so, I've set `useOperatorHostNetwork` to `true` in the operator values (As described [here](https://github.com/rook/rook/issues/4601#issuecomment-570225323)).

I've set only one `mon` as I can't have more than 1 per node (As described [here](https://github.com/rook/rook/issues/2594#issuecomment-463413426)):

```
<snip>
    configOverride: |
      [global]
      osd_pool_default_size = 1
      mon_warn_on_pool_no_redundancy = false
      bdev_flock_retry = 20
      bluefs_buffered_io = false
    cephClusterSpec:
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
        allowMultiplePerNode: true
<snip>
``` 

**Expected behavior:**

However, setting `useOperatorHostNetwork` to `true` doesn't seems to have any effect on the mon (The cluster was recreated from scratch): `mon` is still using an internal IP (`10.43.85.117`) and is not accessible from the outside (`<external_ip>:6789`).

The operator does use the correct external IP.

Also, I was expecting no service creation for the mon, but:
```
kubectl get svc -n rook-ceph
NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
csi-rbdplugin-metrics      ClusterIP   10.43.25.33     <none>        8080/TCP,8081/TCP   2m16s
csi-cephfsplugin-metrics   ClusterIP   10.43.171.194   <none>        8080/TCP,8081/TCP   2m16s
rook-ceph-mon-a            ClusterIP   10.43.216.213   <none>        6789/TCP,3300/TCP   2m12s
rook-ceph-mgr-dashboard    ClusterIP   10.43.9.250     <none>        8443/TCP            69s
rook-ceph-mgr              ClusterIP   10.43.159.28    <none>        9283/TCP            69s
```

I'm not sure this is a bug in the Helm Chart, due to the fact I only have one node with one mon or simply a mistake on my part (Most likely!)

Thank you for any help you might provide.

Note:
```
$ ceph health
HEALTH_OK

$ ceph osd status
ID  HOST     USED  AVAIL  WR OPS  WR DATA  RD OPS  RD DATA  STATE      
 0  <host>  5584k   439G      0        0       0        0   exists,up  
 
 $ ceph mon stat  
e1: 1 mons at {a=[v2:10.43.216.213:3300/0,v1:10.43.216.213:6789/0]}, election epoch 3, leader 0 a, quorum 0 a
```

**Comment by Madhu-1** [comment]
@M-Gregoire please paste `cluster CR yaml output` and `kubectl get po -nrook-ceph`

**Comment by Madhu-1** [comment]
@M-Gregoire useOperatorHostNetwork is only to run rook operator pod in host networking not to create ceph cluster on host networking. you need to enable host networking when creating the ceph cluster here https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L126-L129

**Comment by M-Gregoire** [comment]
> @M-Gregoire useOperatorHostNetwork is only to run rook operator pod in host networking not to create ceph cluster on host networking. you need to enable host networking when creating the ceph cluster here https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L126-L129

Thanks a lot! That did fixed it immediately and everything works as intended. 

Sorry I missed it.
