### ISSUE TITLE
Log level is not inherited by Rook components other than Rook-operator

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1033]
If the rook operator is started with a non-default log-level, pods that are created by the operator such as mon, osd, rgw etc are not passed the log-level and use the default.

Thanks @galexrt for finding this issue in https://github.com/rook/rook/pull/882#issuecomment-333365055.

**Comment by kokhang** [comment]
There are two ways being discussed to solve it. One to have a single argument that is applied on all the components or having separate arguments for each components. For example

ROOK_LOG_LEVEL = "Debug"
vs
ROOK_OPERATOR_LOG_LEVEL = "Debug"
ROOK_MON_LOG_LEVEL = "Debug"
ROOK_OSD_LOG_LEVEL = "Debug"
ROOK_AGENT_LOG_LEVEL = "Debug"
...

**Comment by travisn** [comment]
Besides the rook daemon log settings, we need to consider how we can pass different log levels to the ceph daemons. Individual components of ceph can be enabled at different log levels within a given daemon. See http://docs.ceph.com/docs/kraken/rados/troubleshooting/log-and-debug/#subsystem-log-and-debug-settings

Some requirements for logging that would be ideal:
- The log settings can be specified for the operator to initialize rook with the desired log settings
- The log settings can be updated on live pods
- The log settings are granular by daemon
- The log settings are granular for ceph components within a daemon

In ceph this may be easier in `mimic` when all settings will be stored centrally in the mons, so we may not get all these requirements to start with.

**Comment by kokhang** [comment]
Ahh i see your point. Perhaps we can have two args. One to control the Rook log level and another to control the "backend" (in this case ceph) log level.
The rook log level would just be applied to Rook, which include operators, mds, mons, osd etc.
The rook log level arg can be set in the operator manifest whereas the "backend" log level can be set in the Cluster CRD.

**Comment by travisn** [comment]
it's still important to make the settings granular. we shouldn't just assume the same logging level is desired for all components. I don't think this should be exposed in the CRD either. Debug log levels are more of a short-term troubleshooting task that don't seem like a part of the crds.

**Comment by jbw976** [comment]
Ignoring the topic of granularity (rook components and ceph components), I did just want to make sure it's know that we already have a simplistic conversion from the user specified Rook log level to the corresponding Ceph log level that will in turn be set: https://github.com/rook/rook/blob/master/pkg/ceph/mon/config.go#L324

e.g., if the user specifies DEBUG to a Rook daemon, then it will set the Ceph log level to 10 in it's config file.

**Comment by jbw976** [comment]
Also, to specify ceph log levels more directly, the config file override can be used.  That may very well be an easy, straightforward, granular means for the user to specify exactly the Ceph logging level they want for the Ceph components they want, without us having to write any more code or design any new features.

**Comment by travisn** [comment]
@jbw976 good point, we already have the flexibility for ceph logging with the config file override. So it's really a question of log level for the rook components

**Comment by travisn** [comment]
i think a simple solution is to add new settings to the config override ConfigMap. Right now there is a value for `config`, which is for ceph. What if we added the following?
- `mon-log-level`
- `mgr-logl-level`
- `osd-log-level`
- `rgw-log-level`
- `mds-log-level`

We can map it into the pods with an environment variable that is transparent to the daemon that it comes from a CM.

**Comment by mickymiek** [comment]
Unless I'm missing something and it's already been done since, I think this issue should be reopened. No way of managing log levels per component is a real pain when using a centralized logging system for example.

**Comment by travisn** [comment]
@mickymiek The current approach for increasing log level is that the [ROOK_LOG_LEVEL](https://rook.io/docs/rook/v1.2/ceph-advanced-configuration.html#custom-cephconf-settings) can be set for the operator. The log level for ceph daemons would be increased by using [custom ceph settings](https://rook.io/docs/rook/v1.2/ceph-advanced-configuration.html#custom-cephconf-settings) to increase the log level of the individual ceph components. Does that work for you? Or can you clarify what you see needed?

**Comment by leseb** [comment]
I think @mickymiek  meant logging for each Rook's subsystem (go packages) not Ceph daemon logging level but I might be wrong.

**Comment by mickymiek** [comment]
@travisn I was talking about your latest comment here: https://github.com/rook/rook/issues/1033#issuecomment-337761946

I think it would be nice/easier to have a way to tell Ceph (probably in the config-override CM) the verbosity we want for each of its components (mon,osd,mgr...) maybe with values like "debug", "info", "warn", "error", without going into the details of Ceph configuration. What do you think?

**Comment by travisn** [comment]
> @travisn I was talking about your latest comment here: [#1033 (comment)](https://github.com/rook/rook/issues/1033#issuecomment-337761946)
> 
> I think it would be nice/easier to have a way to tell Ceph (probably in the config-override CM) the verbosity we want for each of its components (mon,osd,mgr...) maybe with values like "debug", "info", "warn", "error", without going into the details of Ceph configuration. What do you think?

@mickymiek With the flexibility of the config override CM, I don't see us adding a different verbosity level for the ceph components. If you want to change the logging level for ceph components, you should understand how to configure the ceph components with the ceph config override.
 
> By the way, shouldn't CSI components log levels be configurable as well? I think it is hardcoded to `--v=5` for now

Agreed that the csi driver log level should be configurable. Want to open a separate issue for that?

**Comment by mickymiek** [comment]
> @mickymiek With the flexibility of the config override CM, I don't see us adding a different verbosity level for the ceph components. If you want to change the logging level for ceph components, you should understand how to configure the ceph components with the ceph config override.

Alright.

> Agreed that the csi driver log level should be configurable. Want to open a separate issue for that?

Sure, here it is: https://github.com/rook/rook/issues/4690


Closing this then, thank you.
