### ISSUE TITLE
Placement for osd-prepare

### ISSUE THREAD

**Issue by caffeinism** [rook/rook#10331]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
It seems obvious that the placement setting of osd should also work for osd-prepare. But it doesn't seem to be the case now. When a specific placement is specified in the OSD, osd-prepare is not deployed.

```
  placement:
    osd:
      nodeAffinity:
         ...
      tolerations:
         ...
```

```
rook-ceph-osd-prepare-storage-03--1-qpjjx              0/1     Pending
```

```
 node(s) had taint, that the pod didn't tolerate
```

**Comment by travisn** [comment]
The `placement.osd` is expected to be applied to the osd prepare jobs. Perhaps there is some issue with the whitespace in the cluster CR? If you run `kubectl -n rook-ceph get cephcluster -o yaml` do you see the tolerations as expected? As another data point, have you tried applying the tolerations to some other component such as mon or mgr to confirm they are applied?

**Comment by caffeinism** [comment]
Originally, I was using it by setting it to placement/all. However, I changed `all` to `osd` to get rid of mon, which made it impossible to deploy osd-prepare as an issue. However, when using `all`, it worked normally, so I think it was not a problem with cluster CR.

**Comment by caffeinism** [comment]
Aha I forgot to comment on the code as prepareosd! It seems to be resolved. I will close the issue.
