### ISSUE TITLE
[ERR] MGR_MODULE_ERROR: Module 'dashboard' has failed: OSError("No socket could be created -- (('10.xx.xx.xx', 8443): [Errno 99] Cannot assign requested addre ss)",)

### ISSUE THREAD

**Issue by sharmavickram** [rook/rook#10355]
I had configured ceph as storage to my cluster, all services are running fine except ceph dashboard.
![image](https://user-images.githubusercontent.com/9397194/171162145-c1d443f7-3b04-4b68-9172-61af8302e8bd.png)

initially it was working i created bucket using ceph dashboard UI but now i am not able to access dashboard.

please help me in fixing this issue.

**Comment by parth-gr** [comment]
Hey, Please share the operator logs and rook version, 
feels like mgr pod has stopped running, Any specific step you did?

**Comment by sharmavickram** [comment]
osd's and mgr's was crashing so i restarted them

**Comment by sharmavickram** [comment]
@parth-gr 
![image](https://user-images.githubusercontent.com/9397194/171165629-0c10350e-3e88-47a7-8c65-7c7010693eda.png)

**Comment by parth-gr** [comment]
Maybe the IP address is wrong with Prometheus and what dashboard except,

Do `ceph config dump` in the toolbox

**Comment by sharmavickram** [comment]
> 

![image](https://user-images.githubusercontent.com/9397194/171332750-1f3f2f4e-59a2-47a5-810e-ebe39caecf0d.png)

**Comment by parth-gr** [comment]
Can you try removing this adresses `ceph config rm mgr.a mgr/prometheus/a/server_addr` and `ceph config rm mgr.a mgr/dashboard/a/server_addr` and re-start mgr pod o r operator pod,
And share the mgr logs after it.

And if this doesn't helps try disabling the Prometheus `ceph mgr module disable prometheus`.

**Comment by parth-gr** [comment]
Have you tried the above steps, 
removing the address and disabling Prometheus?

**Comment by sharmavickram** [comment]
![image](https://user-images.githubusercontent.com/9397194/171342740-bd9eebac-b439-4c69-b557-05f47ec2848b.png)


![image](https://user-images.githubusercontent.com/9397194/171342640-8aeca8a3-2b9a-4f26-be08-8392b7c16439.png)

**Comment by parth-gr** [comment]
Now re-start the operator and check the health

**Comment by parth-gr** [comment]
Is both the mgr pod running on same node, 

`Kubectl get pods -nrook-ceph -o describe` and check it,

And can you share the logs of mgr

**Comment by sharmavickram** [comment]
> -o describe

![image](https://user-images.githubusercontent.com/9397194/171345617-3d93420e-4d3d-4c7e-96d9-8dfc55c468db.png)

**Comment by parth-gr** [comment]
Seems like the IP by which it is creating the socket is not equal to what mgr IP is,
@jmolmo @travisn that make sense?

**Comment by parth-gr** [comment]
You cannot change Ip, but you can match it with the right one
