### ISSUE TITLE
How to add osd startup parameter bluefs-shared-alloc-size

### ISSUE THREAD

**Issue by clcc2019** [rook/rook#10394]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/46099295/172127192-a7fabdd8-e508-4bb0-8e42-618f1094ab6d.png">

How to add osd startup parameter bluefs-shared-alloc-size=4096？

**Comment by travisn** [comment]
You can either use the [ceph.conf overrides](https://rook.github.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-configuration/#custom-cephconf-settings) or set mon config store options. There is no way to customize the command line parameters for the osd pod without a code change. Please confirm if the overrides work for you.
