### ISSUE TITLE
accomodate changes from  `node-role.kubernetes.io/master` to `node-role.kubernetes.io/control-plane` 

### ISSUE THREAD

**Issue by humblec** [rook/rook#10398]
From kube v1.24 onwards, Kubeadm applies a "node-role" label to its control plane Nodes. Currently this label key is `node-role.kubernetes.io/master` which is renamed to` node-role.kubernetes.io/control-plane`. Kubeadm also uses the same "node-role" as key for a taint it applies on control plane Nodes. This taint key should also be renamed to "node-role.kubernetes.io/control-plane".
Refer #https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint

Considering rook has some references to `master` [1] we have to accommodate the same.

https://github.com/rook/rook/blob/master/deploy/examples/cluster-stretched.yaml#L60
https://github.com/rook/rook/blob/master/deploy/examples/cluster-stretched-aws.yaml#L132

**Comment by travisn** [comment]
Sounds good to rename these example labels, some others were already previously updated, but these were missed. @humblec Are you planning to open the PR?

**Comment by humblec** [comment]
> Sounds good to rename these example labels, some others were already previously updated, but these were missed. @humblec Are you planning to open the PR?

Sure, I can open a PR @travisn

**Comment by galexrt** [comment]
Closing as already resolved in #10405.
