### ISSUE TITLE
Ceph occupies space and is not released

### ISSUE THREAD

**Issue by liwh1111** [rook/rook#10391]
The capacity of CEPH has been increasing. Although some contents in PVC have been deleted, the capacity of CEPH has not decreased. May I ask how to deal with this?

Some ways to deal with it online:

1. Specify discard parameters when mounting the file system, for example, "mount -t ext4 -o discard device mountpoint".

2. "fstrim -v mountpoint"

Have excuse me what good solution?

**Comment by Madhu-1** [comment]
Try https://rook.io/docs/rook/v1.9/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/#csi-addons-operation to reclaim the space for rbd PVC.

**Comment by Madhu-1** [comment]
discard will have performance issues.  fstrim can be automated with csi-addons-operator.

**Comment by liwh1111** [comment]
Ok, let me see. Thank you very much

**Comment by voarsh2** [comment]
> discard will have performance issues. fstrim can be automated with csi-addons-operator.

From this link, https://rook.io/docs/rook/v1.9/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/#csi-addons-operation, I see it only mentions one target PVC per cron job. I'd like it to be done for all PVC's. I have 60+. Would be painful to set this up for all one them individually? Any ideas?

**Comment by Madhu-1** [comment]
> see it only mentions one target PVC per cron job. I'd like it to be done for all PVC's. I have 60+. Would be painful to set this up for al

Please try annotation way of reclaiming the space https://github.com/csi-addons/kubernetes-csi-addons/blob/v0.5.0/docs/reclaimspace.md#annotating-perstentvolumeclaims

**Comment by luckydogxf** [comment]
I  run into the same issue.
Neither `fstrim --all -v` nor ` csi-addons-operator` works. That's pretty weird.
