### ISSUE TITLE
how to acess cluster deployed by rook from external network?

### ISSUE THREAD

**Issue by hejiwen** [rook/rook#10410]
I deploy a cluster by rook and export mon‘s port， then replace the ceph.conf mon ip with the host's ip and export port，and copy the file to client node which not in the k8s cluster,   run ceph -s，but it doesn't work。

I use nc to test mon ip and port，it works fine，can't you give me some advice to deploy a cluster ，I can acess the cluster by client node which not in the k8s cluster？

**Comment by hejiwen** [comment]
thanks for you reply，i have deployed a cluster by host networking，and can access from external network。
  network:
    provider: host


I have 2 NIC and want to  used for public and network sperately for osd daemon ，how can I config with host networking  like multus as follows to assign IP  for public and network?

  network:
    provider: multus
    selectors:
      public: rook-ceph/rook-public-nw
      cluster: rook-ceph/rook-cluster-nw

**Comment by travisn** [comment]
@hejiwen Does this topic on the [OSD Dedicated Network](https://rook.github.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-configuration/#osd-dedicated-network) answer your question?

**Comment by hejiwen** [comment]
@travisn Thank you very much， this topic solves my problem.

**Comment by hejiwen** [comment]
@travisn  I have a question about mon:

I use host networking and osd dedicated network solution to deply a cluster， it works fine， but I found that the mon‘s public addr differ from osd’s public network,  as follows,  how can I config to make sure mon's public is same with osd's public?


[global]
fsid                = 8d1cd0b7-7c8d-440b-af57-0ab8abb13b74
mon initial members = a b c
mon host            = [v2:192.168.1.1:3300,v1:192.168.1.1:6789],[v2:192.168.1.3:3300,v1:192.168.1.3:6789],[v2:192.168.1.2:3300,v1:192.168.1.2:6789]
public_network      = 172.168.1.0/24
cluster_network     = 192.168.1.0/24

**Comment by travisn** [comment]
With host networking, rook uses the host ips for the mon endpoints. This won't be configurable from the ceph.conf overrides. The mons are treated differently than other daemons. See the [Ceph Network guide](https://docs.ceph.com/en/latest/rados/configuration/network-config-ref/) for more details.

**Comment by hejiwen** [comment]
thank you very much。

with multus networking， the cluster's mon ip also bind to manager NIC(eth0), can you give me some tips to use public NIC(net1)。

[root@rook-ceph-mon-b-57dd9786f7-h7ktk ceph]# netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 172.10.219.96:3300      0.0.0.0:*               LISTEN      -
tcp        0      0 172.10.219.96:6789      0.0.0.0:*               LISTEN      -


[root@rook-ceph-mon-b-57dd9786f7-h7ktk ceph]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1480
        inet 172.10.219.96  netmask 255.255.255.255  broadcast 172.10.219.96
        ether 7a:1e:5f:6a:35:fd  txqueuelen 0  (Ethernet)
        RX packets 6354546  bytes 8596358254 (8.0 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6594947  bytes 4368773946 (4.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2  bytes 100 (100.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 100 (100.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

net1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.18  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 52:54:00:fd:ca:40  txqueuelen 0  (Ethernet)
        RX packets 15281  bytes 1498525 (1.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by fmount** [comment]
Hi @hejiwen, 
in my understanding multus has no support for kubernetes Service, hence you can't bind the daemon to the rook-public-nw attachment definition.
Not sure @travisn can help pointing to a workaround or a known way to do that, but afaik it's not possible.

**Comment by travisn** [comment]
I see there is a [limitation documented here](https://rook.io/docs/rook/latest/CRDs/ceph-cluster-crd/#known-limitations-with-multus) for the mons being accessible via multus. @leseb Any update on that?

**Comment by leseb** [comment]
> I see there is a [limitation documented here](https://rook.io/docs/rook/latest/CRDs/ceph-cluster-crd/#known-limitations-with-multus) for the mons being accessible via multus. @leseb Any update on that?

No updates, investigation must be done to try out https://github.com/k8snetworkplumbingwg/multus-service, which isn't ready for production yet.

**Comment by jwalzer** [comment]
This is to us and our customer still an open question: 
How can I use the rook ceph cluster from outside K8s. We have the public/external network in the pods via multus, but we would like the mons and the osds to bind to the addresses in this network and not the container network.

**Comment by parth-gr** [comment]
@jwalzer you may use Mutus network to deploy rook https://rook.io/docs/rook/latest/CRDs/Cluster/network-providers/#multus
cc @BlaineEXE for more thoughts

**Comment by BlaineEXE** [comment]
To access the Rook-Ceph cluster from outside Kubernetes, you must use host networking.
