### ISSUE TITLE
RGW multisite: delete pools created by zones

### ISSUE THREAD

**Issue by thotz** [rook/rook#10415]
**Is this a bug report or feature request?**
* Feature request

**Deviation from expected behavior:**
Pools created while zone creation is not deleted when zone is removed

**Expected behavior:**
Pools created by zones, need to remove if zone is deleted

**How to reproduce it (minimal and precise):**

creates zone and delete zones
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by mgugino-uipath** [comment]
This is covered via documentation: https://github.com/rook/rook/blob/master/design/ceph/object/zone.md#deleting-and-reconfiguring-the-ceph-object-zone

**Comment by thotz** [comment]
> This is covered via documentation: https://github.com/rook/rook/blob/master/design/ceph/object/zone.md#deleting-and-reconfiguring-the-ceph-object-zone

I understand we manually do this, but idea is to automate it like during the deletion of Zone CR and if there are rgw servers in the zone then the deletion will be blocked until it is removed

**Comment by mgugino-uipath** [comment]
> I understand we manually do this, but idea is to automate it like during the deletion of Zone CR and if there are rgw servers in the zone then the deletion will be blocked until it is removed

My point is, it's not a bug if it's documented behavior, it's working as intended.

Changing this behavior would be a substantial change to the API, and should be an opt-in change to the CR if this is going to be implemented.  EG: 
```
spec:
...
  deletePoolsWhenDeleted: false
```

or similar.

**Comment by thotz** [comment]
> > I understand we manually do this, but idea is to automate it like during the deletion of Zone CR and if there are rgw servers in the zone then the deletion will be blocked until it is removed
> 
> My point is, it's not a bug if it's documented behavior, it's working as intended.
> 
> Changing this behavior would be a substantial change to the API, and should be an opt-in change to the CR if this is going to be implemented. EG:
> 
> ```
> spec:
> ...
>   deletePoolsWhenDeleted: false
> ```
> 
> or similar.

There is preservepool option for cephobjecstore CR, planning to add similar option for Zone CR.
