### ISSUE TITLE
RGW multisite: convert exisitng single site rgw server into multisite

### ISSUE THREAD

**Issue by thotz** [rook/rook#10416]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
converting single site rgw to multisite

**What is use case behind this feature:**
If the zone is not configured then the ceph object store will be created with realm/zone/zone group  ceph object's store name. Later if user needs to convert the single multisite, there are no specific steps for that via Rook.

**Environment**:

**Comment by mgugino-uipath** [comment]
You can create the corresponding realm/zg/zone objects, and update the objectstore object, and it should behave as multisite.  I cannot remember if the objectstore object encounters any reconcile errors, but worst case, you can delete the objectstore object and recreate, deleting the object won't remove the data, though the rgws you have deployed will be terminated until the objectstore object is recreated.

**Comment by thotz** [comment]
The above steps will work but it will destroy the old data since pools for cephobjectstore are changed. My idea was to extend simple plain object store to multisite without losing existing data
