### ISSUE TITLE
RGW mulitsite: add information about Endpoint details in zone group in realm secret

### ISSUE THREAD

**Issue by thotz** [rook/rook#10414]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently, users need to run radosgw-admin commands to fetch details endpoint for realm pull. instead, encode it to realm secret  or provide a configmap containing endpoints part of master zonegroup

**What is use case behind this feature:**
Make

**Environment**:

Multicluster environments

**Comment by BlaineEXE** [comment]
This seems like it is a potential implementation detail taken from https://github.com/rook/rook/pull/10323. Can we close this for now, and open it again if this implementation is the one we choose?
