### ISSUE TITLE
RBAC permissions for operator vs cluster components

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1041]
Rook currently uses 3 different service accounts: rook-operator, rook-api, rook-ceph-osd.  We need to straighten out the following:
* Should cluster components (OSDs, mons, etc.) each have their own service account, or just 1 service account that they all use?
    * rook-operator needs to be cross namespace and it should only be used by the operator and agents.
* rook-ceph-osd should be scoped to just its namespace (i.e., it should be using a `role` not a `clusterrole`)
    * should rook-api be scoped to a single namespace this way as well?

**Comment by kokhang** [comment]
I propose to have two roles. One for the operator (which includes agents) and one for Clusters (osd, mon, api, rgw etc). I think it just makes it easier to manage. A rook cluster is seems as a unit and created as a unit (via the CRD) that encompasses mons, osds, api etc. So it seems naturally to have a role/service account that is applicable at a cluster level.

**Comment by travisn** [comment]
@jbw976  yes, rook-api should be scoped to a single namespace like the osds

**Comment by bassam** [comment]
we also need to consider the rook-agent now. I think we should use the principle of least privileged to sort these. The operator is highly privileged (it can start pods in different namespaces, etc.), if the other roles have the same level of privileges then lets group them (i.e. they can use the same service account), otherwise lets use difference service accounts for the sub-groups.

**Comment by jbw976** [comment]
Note that with #1077 I have made it so that the RBAC permissions for API and OSD are now just scoped to the namespace they are running in.  Them having k8s cluster wide permissions was actually preventing our integration test for multiple rook clusters from passing.

I still vote for the principle of least privileges such that each component that needs RBAC should have its own set of permissions.  We have the operator, API and OSD in place, so I think the only other one would be rook-agent.

**Comment by bassam** [comment]
@jbw976 completely agree. Let’s make it happen :-)

**Comment by bassam** [comment]
I think this should be in 0.6, right?
