### ISSUE TITLE
DOC missing for SubVolumeGroup in external cluster

### ISSUE THREAD

**Issue by lugg1** [rook/rook#10427]
* Bug Report

**Bug Report**
Missing documentation for [subvolumegroup (PR 9694)](https://github.com/rook/rook/pull/9694) to handle in [external cluster](https://rook.io/docs/rook/v1.8/ceph-cluster-crd.html#external-cluster)

**Comment by travisn** [comment]
@lugg1 Are you seeing specific issues with the subvolume groups in the external cluster, or it's just not clear how to configure it?

The [external cluster documentation]((https://rook.io/docs/rook/v1.9/CRDs/ceph-cluster-crd/#external-cluster)) is intended to be refactored to its own doc, and expanded upon. Thanks for the feedback!

**Comment by lugg1** [comment]
It is not clear how to use the subvolume groups of ceph filesystem in the storageclass of a external cluster.

**Comment by parth-gr** [comment]
@lugg1 as per the commit what we have know is ``` If the present cluster CephCluster is external, the controller
(cephFilesystemSubVolumeGroup) won't handle creation nor deletion of sub-volume groups.
It just assumes that the given name is correct and the controller goes ahead with the
ceph-csi configuration. ```

So we need to create and delete it manually, like for example: `ceph fs subvolumegroup create volName groupName`

It is the same for rados namespace for now as they need to be created externally, 
If there is a requirement specifically to add it so we can work upon it.
Thanks!

Refer: https://docs.ceph.com/en/quincy/cephfs/fs-volumes/#fs-subvolumes for more information on subvolumes

**Comment by Madhu-1** [comment]
Okay, looks like the issue doesn't capture details. This is a request on how to consume the clusterID generated when subvolumegroup and RadosNamespace are created. i think we need two trackers one for external cluster documentation and another one for consumption of subvolumegroup and radosnamespace in storageclasses.

**Comment by parth-gr** [comment]
> Okay, looks like the issue doesn't capture details. This is a request on how to consume the clusterID generated when subvolumegroup and RadosNamespace are created. i think we need two trackers one for external cluster documentation and another one for consumption of subvolumegroup and radosnamespace in storageclasses.

@Madhu-1 thanks for the clarification, so need to understand the process we need to add after subvolume manuall creation,

I got linked one discussion related to this https://github.com/rook/rook/issues/9551#issuecomment-1032846294, but updating the cluster-id would help and maybe why??

**Comment by Madhu-1** [comment]
> > Okay, looks like the issue doesn't capture details. This is a request on how to consume the clusterID generated when subvolumegroup and RadosNamespace are created. i think we need two trackers one for external cluster documentation and another one for consumption of subvolumegroup and radosnamespace in storageclasses.
> 
> @Madhu-1 thanks for the clarification, so need to understand the process we need to add after subvolume manuall creation,
> 
> I got linked one discussion related to this [#9551 (comment)](https://github.com/rook/rook/issues/9551#issuecomment-1032846294), but updating the cluster-id would help and maybe why??

https://www.mrajanna.com/Consuming-storage-from-exteranal-ceph-in-rook/ might help you on how to consumer external storage for subvolumegroup/radosnamespace.

**Comment by parth-gr** [comment]
> > > Okay, looks like the issue doesn't capture details. This is a request on how to consume the clusterID generated when subvolumegroup and RadosNamespace are created. i think we need two trackers one for external cluster documentation and another one for consumption of subvolumegroup and radosnamespace in storageclasses.
> > 
> > 
> > @Madhu-1 thanks for the clarification, so need to understand the process we need to add after subvolume manuall creation,
> > I got linked one discussion related to this [#9551 (comment)](https://github.com/rook/rook/issues/9551#issuecomment-1032846294), but updating the cluster-id would help and maybe why??
> 
> https://www.mrajanna.com/Consuming-storage-from-exteranal-ceph-in-rook/ might help you on how to consumer external storage for subvolumegroup/radosnamespace.

thanks this will really help
