### ISSUE TITLE
Changes in config.StoreConfig.DatabaseSizeMB lead to restart of osd with device.storeConfig.DatabaseSizeMB set

### ISSUE THREAD

**Issue by fengjiankui121** [rook/rook#10434]
The envs in the deployment of osd contain config.StoreConfig.DatabaseSizeMB, and the change of config.StoreConfig.DatabaseSizeMB will cause the restart of osd.

The relevant code is as follows：rook\pkg\operator\ceph\cluster\osd\envs.go

func (c *Cluster) getConfigEnvVars(osdProps osdProperties, dataDir string) []v1.EnvVar {
.....

	if osdProps.storeConfig.DatabaseSizeMB != 0 {
		envVars = append(envVars, v1.EnvVar{Name: osdDatabaseSizeEnvVarName, Value: strconv.Itoa(osdProps.storeConfig.DatabaseSizeMB)})
	}

.....	
	
}

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
Correct, any change to the OSD pod spec will lead to a restart. If you change that value, why would you not expect the OSD to restart?

**Comment by fengjiankui121** [comment]
> Correct, any change to the OSD pod spec will lead to a restart. If you change that value, why would you not expect the OSD to restart?

@travisn  
For the osd with device.storeConfig.DatabaseSizeMB set, the ROOK_OSD_DATABASE_SIZE in the env of the osd pod is config.storeConfig.DatabaseSizeMB

As shown below, the actual databaseSizeMB of osd is 2048, while the ROOK_OSD_DATABASE_SIZE in env is 1024:
    storage:
      config:
        databaseSizeMB: "1024"
        metadataDevice: ""
      nodes:
      - config: null
        devices:
        - config: 
		    databaseSizeMB: "2048"
          name: vdc
        name: node01

> Correct, any change to the OSD pod spec will lead to a restart. If you change that value, why would you not expect the OSD to restart?

**Comment by travisn** [comment]
Oh, the issue is that you expected 2048 to be applied to that vdc OSD on node01, but instead you see 1024?

**Comment by travisn** [comment]
Ok, I ran a quick test, and I see that the `config` is not being applied from the individual device section. The `config` is only honored from `storage.config`, or under an individual node. So in this case, you could apply different database size for the node. Does that help your scenario? Of course, this doesn't work if you need different settings for OSDs on the same node.
```yaml
    storage:
      config:
        databaseSizeMB: "1024" # applies to OSDs on nodes 2 and 3
      nodes:
      - name: node01
        config: 
           databaseSizeMB: "2048"
        devices:
          name: vdc
      - name: node02
        devices:
          name: vdc
      - name: node03
        devices:
          name: vdc        
```

**Comment by fengjiankui121** [comment]
> Ok, I ran a quick test, and I see that the `config` is not being applied from the individual device section. The `config` is only honored from `storage.config`, or under an individual node. So in this case, you could apply different database size for the node. Does that help your scenario? Of course, this doesn't work if you need different settings for OSDs on the same node.
> 
> ```yaml
>     storage:
>       config:
>         databaseSizeMB: "1024" # applies to OSDs on nodes 2 and 3
>       nodes:
>       - name: node01
>         config: 
>            databaseSizeMB: "2048"
>         devices:
>           name: vdc
>       - name: node02
>         devices:
>           name: vdc
>       - name: node03
>         devices:
>           name: vdc        
> ```

@travisn What is the role of databaseSize in the environment variable of osd pod? Is it possible to remove from environment variables?

**Comment by travisn** [comment]
> @travisn What is the role of databaseSize in the environment variable of osd pod? Is it possible to remove from environment variables?

In the [default cluster.yaml example](https://github.com/rook/rook/blob/master/deploy/examples/cluster.yaml#L231), this setting is commented out with the description:
```
# databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
```

If it is not specified, Ceph will default to an appropriate size for its metadata.

**Comment by fengjiankui121** [comment]
> > I mean it is only removed from the environment variables of the osd pod and kept in the cluster.yaml. Because the prepare job needs to specify the metadata size when creating an OSD through ceph-volume, but the role of putting it in the environment variable of the OSD pod has not yet been found.
> 
> Oh, the env var on the osd pod likely isn't used anymore, it must be legacy. If the correct databasSizeMB is being applied in the osd prepare pod, the env var on the osd daemon would be ignored. Did you see the correct size is set in the osd prepare pod?

@travisn Yes，the correct databasSizeMB is being applied in the osd prepare pod.

**Comment by fengjiankui121** [comment]
> > > I mean it is only removed from the environment variables of the osd pod and kept in the cluster.yaml. Because the prepare job needs to specify the metadata size when creating an OSD through ceph-volume, but the role of putting it in the environment variable of the OSD pod has not yet been found.
> > 
> > 
> > Oh, the env var on the osd pod likely isn't used anymore, it must be legacy. If the correct databasSizeMB is being applied in the osd prepare pod, the env var on the osd daemon would be ignored. Did you see the correct size is set in the osd prepare pod?
> 
> @travisn Yes，the correct databasSizeMB is being applied in the osd prepare pod.

@travisn Can the env be ignored?

**Comment by travisn** [comment]
Yes, I expect it will be ignored since it's only used during provisioning.

**Comment by fengjiankui121** [comment]
> Yes, I expect it will be ignored since it's only used during provisioning.

@travisn Would you allow me to submit a pr for this issue

**Comment by travisn** [comment]
> > Yes, I expect it will be ignored since it's only used during provisioning.
> 
> @travisn Would you allow me to submit a pr for this issue

Certainly! The fix you are proposing is to not add this env var to the OSD pod?

**Comment by fengjiankui121** [comment]
> > > Yes, I expect it will be ignored since it's only used during provisioning.
> > 
> > 
> > @travisn Would you allow me to submit a pr for this issue
> 
> Certainly! The fix you are proposing is to not add this env var to the OSD pod?

@travisn Yes, Is this method feasible?

**Comment by travisn** [comment]
> > > > Yes, I expect it will be ignored since it's only used during provisioning.
> > > 
> > > 
> > > @travisn Would you allow me to submit a pr for this issue
> > 
> > 
> > Certainly! The fix you are proposing is to not add this env var to the OSD pod?
> 
> @travisn Yes, Is this method feasible?

If you are observing the correct value applied in the OSD from the prepare pod, and it is being ignored by the OSD daemon pod, then there is no need for the var on the OSD daemon pod.
