### ISSUE TITLE
OSD gets killed on devicehealth scraping

### ISSUE THREAD

**Issue by l0nax** [rook/rook#10443]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

The SMART data gets scraped.

**How to reproduce it (minimal and precise):**

The OSD gets restarted as soon as the devicehealth is scraped, e.g., by executing `ceph device scrape-daemon-health-metrics osd.2`.

The OSD container gets restarted by kubernetes because the liveness probe command (`ceph --admin-daemon /run/ceph/ceph-osd.2.asok status`) fails three times in a row.
Within the pod, I'm able to execute the `smartctl` command without any errors.

**File(s) to submit**:

Last few lines of the OSD log:
```
debug -7> 2022-05-09T10:54:38.559+0000 7f975380e700 10 monclient: _check_auth_rotating have uptodate secrets (they expire after 2022-05-09T10:54:08.561261+0000)
debug -6> 2022-05-09T10:54:39.559+0000 7f975380e700 10 monclient: tick
debug -5> 2022-05-09T10:54:39.559+0000 7f975380e700 10 monclient: _check_auth_rotating have uptodate secrets (they expire after 2022-05-09T10:54:09.561363+0000)
debug -4> 2022-05-09T10:54:40.559+0000 7f975380e700 10 monclient: tick
debug -3> 2022-05-09T10:54:40.559+0000 7f975380e700 10 monclient: _check_auth_rotating have uptodate secrets (they expire after 2022-05-09T10:54:10.561470+0000)
debug -2> 2022-05-09T10:54:41.439+0000 7f9768245700 10 monclient: get_auth_request con 0x55c8063da000 auth_method 0
debug -1> 2022-05-09T10:54:41.439+0000 7f9768a46700 10 monclient: get_auth_request con 0x55c7e90f1c00 auth_method 0
debug 0> 2022-05-09T10:54:41.443+0000 7f974b7fe700 -1 ** Caught signal (Segmentation fault) *
in thread 7f974b7fe700 thread_name:safe_timer

ceph version 17.2.0 (43e2e60a7559d3f46c9d53f1ca875fd499a1e35e) quincy (stable)
 1: /lib64/libpthread.so.0(+0x12ce0) [0x7f976ca3fce0]
 2: (BlueStore::_txc_create(BlueStore::Collection*, BlueStore::OpSequencer*, std::__cxx11::list&lt;Context*, std::allocator&lt;Context*&gt; >, boost::intrusive_ptr&lt;TrackedOp&gt;)+0x3ae) [0x55c7e502855e]
 3: (BlueStore::queue_transactions(boost::intrusive_ptr&lt;ObjectStore::CollectionImpl&gt;&, std::vector&lt;ceph::os::Transaction, std::allocator&lt;ceph::os::Transaction&gt; >&, boost::intrusive_ptr&lt;TrackedOp&gt;, ThreadPool::TPHandle)+0x260) [0x55c7e508d3e0]
 4: (non-virtual thunk to PrimaryLogPG::queue_transactions(std::vector&lt;ceph::os::Transaction, std::allocator&lt;ceph::os::Transaction&gt; >&, boost::intrusive_ptr&lt;OpRequest&gt;)+0x55) [0x55c7e4c8d2e5]
 5: (ReplicatedBackend::submit_transaction(hobject_t const&, object_stat_sum_t const&, eversion_t const&, std::unique_ptr&lt;PGTransaction, std::default_delete&lt;PGTransaction&gt; >&&, eversion_t const&, eversion_t const&, std::vector&lt;pg_log_entry_t, std::allocator&lt;pg_log_entry_t&gt; >&&, std::optional&lt;pg_hit_set_history_t&gt;&, Context*, unsigned long, osd_reqid_t, boost::intrusive_ptr&lt;OpRequest&gt;)+0xca8) [0x55c7e4ea7f98]
 6: (PrimaryLogPG::issue_repop(PrimaryLogPG::RepGather*, PrimaryLogPG::OpContext*)+0xc90) [0x55c7e4bf3da0]
 7: (PrimaryLogPG::simple_opc_submit(std::unique_ptr&lt;PrimaryLogPG::OpContext, std::default_delete&lt;PrimaryLogPG::OpContext&gt; >)+0x120) [0x55c7e4bf6000]
 8: (PrimaryLogPG::handle_watch_timeout(std::shared_ptr&lt;Watch&gt;)+0xb99) [0x55c7e4bf83f9]
 9: (HandleWatchTimeout::complete(int)+0x11b) [0x55c7e4b7a4ab]
 10: (CommonSafeTimer&lt;std::mutex&gt;::timer_thread()+0x11a) [0x55c7e51f8afa]
 11: (CommonSafeTimerThread&lt;std::mutex&gt;::entry()+0x11) [0x55c7e51fa121]
 12: /lib64/libpthread.so.0(+0x81cf) [0x7f976ca351cf]
 13: clone()
 NOTE: a copy of the executable, or `objdump -rdS &lt;executable&gt;` is needed to interpret this.
--- logging levels ---
0/ 5 none
0/ 1 lockdep
0/ 1 context
1/ 1 crush
1/ 5 mds
1/ 5 mds_balancer
1/ 5 mds_locker
1/ 5 mds_log
1/ 5 mds_log_expire
1/ 5 mds_migrator
0/ 1 buffer
0/ 1 timer
0/ 1 filer
0/ 1 striper
0/ 1 objecter
0/ 5 rados
0/ 5 rbd
0/ 5 rbd_mirror
0/ 5 rbd_replay
0/ 5 rbd_pwl
0/ 5 journaler
0/ 5 objectcacher
0/ 5 immutable_obj_cache
0/ 5 client
1/ 5 osd
0/ 5 optracker
0/ 5 objclass
1/ 3 filestore
1/ 3 journal
0/ 0 ms
1/ 5 mon
0/10 monc
1/ 5 paxos
0/ 5 tp
1/ 5 auth
1/ 5 crypto
1/ 1 finisher
1/ 1 reserver
1/ 5 heartbeatmap
1/ 5 perfcounter
1/ 5 rgw
1/ 5 rgw_sync
1/ 5 rgw_datacache
1/10 civetweb
1/ 5 javaclient
1/ 5 asok
1/ 1 throttle
0/ 0 refs
1/ 5 compressor
1/ 5 bluestore
1/ 5 bluefs
1/ 3 bdev
1/ 5 kstore
4/ 5 rocksdb
4/ 5 leveldb
4/ 5 memdb
1/ 5 fuse
2/ 5 mgr
1/ 5 mgrc
1/ 5 dpdk
1/ 5 eventtrace
1/ 5 prioritycache
0/ 5 test
0/ 5 cephfs_mirror
0/ 5 cephsqlite
0/ 5 seastore
0/ 5 seastore_onode
0/ 5 seastore_odata
0/ 5 seastore_omap
0/ 5 seastore_tm
0/ 5 seastore_cleaner
0/ 5 seastore_lba
0/ 5 seastore_cache
0/ 5 seastore_journal
0/ 5 seastore_device
0/ 5 alienstore
1/ 5 mclock
2/-2 (syslog threshold)
99/99 (stderr threshold)
-- pthread ID / name mapping for recent threads ---
7f9746ff5700 /
```

**Environment**:
* OS (e.g. from /etc/os-release): Arch LInux
* Kernel (e.g. `uname -a`): 5.18.3-arch1-1
* Cloud provider or hardware configuration: –
* Rook version (use `rook version` inside of a Rook Pod): v1.9.3
* Storage backend version (e.g. for ceph do `ceph -v`): 17.2.0 (43e2e60a7559d3f46c9d53f1ca875fd499a1e35e) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.21.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On-Premise (kubeadm)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] 
(https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_WARN

**Comment by l0nax** [comment]
> 2. You're scraping the metrics directly by exec'ing to the pod?

No, I execute the scrape command within the `toolbox` pod.

> 1. How long does it take to scrape the metrics? Longer than three liveness probe checks?

Yes, it's roughly within the three liveness probe checks.

All OSDs have the same liveness probe period set to 10 seconds:
```
    livenessProbe:
      exec:
        command:
        - env
        - -i
        - sh
        - -c
        - ceph --admin-daemon /run/ceph/ceph-osd.9.asok status
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
```

Once I execute i.e. `ceph device scrape-daemon-health-metrics osd.9`  the OSD gets restarted by K8s because the liveness probe failed (roughly 28 seconds after I executed the scrape command):
```
Events:
  Type     Reason     Age                 From     Message
  ----     ------     ----                ----     -------
  Normal   Pulled     7h4m (x4 over 3d)   kubelet  Container image "registry.fab/library/ceph/ceph:v17.2.0-20220611" already present on machine
  Normal   Created    7h4m (x4 over 3d)   kubelet  Created container osd
  Normal   Started    7h4m (x4 over 3d)   kubelet  Started container osd
  Warning  Unhealthy  6s (x12 over 2d7h)  kubelet  Liveness probe failed:
  Normal   Killing    6s (x4 over 2d7h)   kubelet  Container osd failed liveness probe, will be restarted
```

The scrape commands exits with _0_:
```bash
~$ date; ceph device scrape-daemon-health-metrics osd.9; echo $?; date
Fri Jun 17 07:19:45 UTC 2022
0
Fri Jun 17 07:20:13 UTC 2022
```

> 3. Have you tried [disabling the liveness probe or increasing the timeouts on the liveness probe](https://rook.io/docs/rook/latest/CRDs/ceph-cluster-crd/#health-settings)? It would be helpful to understand what liveness probe settings work better for you.

I disabled the liveness checks for the OSDs via the `CephCluster` resource and tried to scape the health metrics again. The command succeeded after 7 minutes and 59 seconds:
```bash
~$ date; ceph device scrape-daemon-health-metrics osd.9; echo $?; date
Fri Jun 17 07:35:01 UTC 2022
0
Fri Jun 17 07:43:00 UTC 2022

~$ ceph device get-health-metrics WDC_WD8003FFBX-XXXXXXX_XXXXXXXX
{
    "20220617-074300": {
        "ata_apm": {
            "enabled": true,
            "level": 164,
            "max_performance": false,
            "min_power": false,
            "string": "intermediate level without standby",
            "with_standby": false
        },
[...]
}
```

I tried the scrape command a second time and it only took again 7 minutes and 49 seconds.
```bash
~$ date; ceph device scrape-daemon-health-metrics osd.9; echo $?; date
Fri Jun 17 07:47:12 UTC 2022
0
Fri Jun 17 07:55:01 UTC 2022
```

With a higher liveness probe interval, it seems to work. For the data nodes, we used the RHEL distro before and then switched to _Arch_. On the RHEL it never took that long to scrape the metrics.

Do you have any ideas why it now takes so long or ideas how to debug the root cause @travisn?

**Comment by travisn** [comment]
That's really unexpected that scraping the metrics from an OSD went from ~30s to ~8 minutes. I wouldn't expect the liveness probe itself to affect the metrics. Even 30s seems like a long response time, but I'm not familiar with this command to know what is normal. If you scrape for a specific timestamp is it faster?
@pcuzner thoughts?

**Comment by l0nax** [comment]
What do you mean by scraping for a specific timestamp?

**Comment by travisn** [comment]
From the [Ceph documentation](https://docs.ceph.com/en/latest/rados/operations/devices/#scraping), I see this option:
```
ceph device get-health-metrics <devid> [sample-timestamp]
```

**Comment by l0nax** [comment]
`get-health-metrics` returns the stored health metrics whilst `scrape-health-metrics` actually executes the `smartctl` command – if I'm not totally wrong.

**Comment by BlaineEXE** [comment]
This seems like it is worth posting a bug to the Ceph project. IMO, the OSD should **not** be going unresponsive when someone queries metrics from it.
