### ISSUE TITLE
Rook-ceph cluster OSD's and Mgr pods are failing after restoration

### ISSUE THREAD

**Issue by yashg-altair** [rook/rook#10441]
The requirement is to have a Backup setup by taking backup of whole AKS cluster and restoring it to another azure AKS cluster.
I used velero to backup all the K8's resources even CRD's to azure storage and then tried to restore it on another AKS cluster.
The restoration was successful as there were no errors reported but rook-ceph cluster OSD's were failing with **Init:CrashLoopBackOff** error and mgr pod being stuck at **Init:1/3 state** state.

Please find the logs for the same.

### 1. Logs for mgr pod 
a. of mgr container

![image](https://user-images.githubusercontent.com/107452803/173490452-e34d6e56-2134-41ba-a96d-aabe3387a487.png)
b. of chown-container-data-dir
 
![image](https://user-images.githubusercontent.com/107452803/173490687-676cd499-5ae0-44f6-a562-debced9d2ae9.png)

c. of init-set-dashboard-server-addr
![image](https://user-images.githubusercontent.com/107452803/173490846-1ead9ebe-121b-4d73-9df6-401abf3a9725.png)
d. of init-set-prometheus-server-addr
![image](https://user-images.githubusercontent.com/107452803/173490996-f5c96e58-758e-405b-bff8-c1a782fbdda8.png)

### **Describe command output of mgr pod**

![image](https://user-images.githubusercontent.com/107452803/173491559-671a6475-3934-45a9-b59c-ac9afd905c16.png)
![image](https://user-images.githubusercontent.com/107452803/173491593-0e2fb1ef-be8f-4c90-a14b-e06a162c1f44.png)
![image](https://user-images.githubusercontent.com/107452803/173491669-762fd276-a02e-45c3-8ae5-a62cbf3a7b98.png)
![image](https://user-images.githubusercontent.com/107452803/173491701-8ce683db-ec14-406a-bd2e-b3382bc7d56b.png)
![image](https://user-images.githubusercontent.com/107452803/173491854-253c3c62-b659-4c81-bbd3-5b12c4947d4d.png)

### 2. Logs of one of the OSD out of 3
a. of container OSD
![image](https://user-images.githubusercontent.com/107452803/173491157-84d3788b-3496-479b-adb6-33a8e836c067.png)

b. of blkdevmapper
![image](https://user-images.githubusercontent.com/107452803/173491268-7e9b5218-9873-4206-bd9a-01c50a032a05.png)
c. of activate
![image](https://user-images.githubusercontent.com/107452803/173491305-3ee0286e-68f5-42ae-b6a9-7c5c56fab977.png)
d. of expand-bluefs
![image](https://user-images.githubusercontent.com/107452803/173491366-e4f1f091-0755-4ee0-bf77-63383f67c6b1.png)
e. chown-container-data-dir
![image](https://user-images.githubusercontent.com/107452803/173491409-a13ead55-fa38-4d9e-b865-8ac6d01e9039.png)

### **Describe command output of OSD pod**

![image](https://user-images.githubusercontent.com/107452803/173491941-f5706795-cd28-48d0-a81d-c1e67fed0e49.png)
![image](https://user-images.githubusercontent.com/107452803/173491989-851d4cff-0eaf-4aab-8966-0641fddc9819.png)
![image](https://user-images.githubusercontent.com/107452803/173492038-241bd276-abe7-421f-82d4-09e8322b36b0.png)
![image](https://user-images.githubusercontent.com/107452803/173492068-29ae3def-592d-4770-a12a-ea02f31d171c.png)
![image](https://user-images.githubusercontent.com/107452803/173492099-57b10851-69aa-48ae-b562-d91f02b13189.png)

### 3. Logs of rook-ceph operator

![image](https://user-images.githubusercontent.com/107452803/173492255-3a7a435d-b8f0-4c07-8c96-43194c8881cb.png)
![image](https://user-images.githubusercontent.com/107452803/173492313-61f1c5f3-281b-4318-81a4-946c66af15ff.png)
![image](https://user-images.githubusercontent.com/107452803/173492358-fa64700f-2ff3-4892-a88d-4acd8312fed2.png)

**Comment by parth-gr** [comment]
Are you able to run ceph commands manually 

`ceph health` on the toolbox?

**Comment by yashg-altair** [comment]
> Are you able to run ceph commands manually
> 
> `ceph health` on the toolbox?

No, the ceph commands are getting timed out.

**Comment by travisn** [comment]
@yashg-altair Did you follow the [disaster recovery guide](https://rook.io/docs/rook/latest/Troubleshooting/disaster-recovery/#backing-up-and-restoring-a-cluster-based-on-pvcs-into-a-new-kubernetes-cluster) to attempt the full backup and restore? 

For DR scenarios, you could also consider better mirroring solutions such as [RBD Mirroring](https://rook.io/docs/rook/latest/Storage-Configuration/Block-Storage-RBD/rbd-async-disaster-recovery-failover-failback/).

**Comment by yashg-altair** [comment]
> @yashg-altair Did you follow the [disaster recovery guide](https://rook.io/docs/rook/latest/Troubleshooting/disaster-recovery/#backing-up-and-restoring-a-cluster-based-on-pvcs-into-a-new-kubernetes-cluster) to attempt the full backup and restore?
> 
> For DR scenarios, you could also consider better mirroring solutions such as [RBD Mirroring](https://rook.io/docs/rook/latest/Storage-Configuration/Block-Storage-RBD/rbd-async-disaster-recovery-failover-failback/).

I have seen it but we preferably wants to use a backup and restore tool like velero which can backup all the applications running on the cluster and restore successfully. I also followed the disaster recovery guide shared by you but one of the mon out of three is failing with a warning of **Back-off restarting failed container**. What should we do now?

**Comment by travisn** [comment]
1. What does `ceph status` show in the toolbox?
2. What do the logs show for the failing mon container?
3. If the other two mons are in quorum, rook should actually failover the bad mon and create a new one.
4. Please share the operator log.
