### ISSUE TITLE
preservePoolsOnDelete==true may cause the file system to be deleted

### ISSUE THREAD

**Issue by R-omk** [rook/rook#10466]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The option `PreserveFilesystemOnDelete` is not actually set to true when the option `preservePoolsOnDelete` is set. **This causes the file system to be deleted if the file system manifest is accidentally deleted.** What really happened to me.

```
..
2022-06-17 09:50:21.806251 I | ceph-file-controller: CephFilesystem "rook-ceph/cephfs" can be deleted safely. deleting CephFilesystem "rook-ceph/cephfs"
..
2022-06-17 09:50:34.962522 I | op-mds: successfully deleted mds config for "mds.cephfs-a" in mon configuration database
2022-06-17 09:50:34.962529 I | cephclient: deleting ceph auth "mds.cephfs-a"
..
2022-06-17 09:50:39.356766 I | op-mds: successfully deleted mds CephX key for "mds.cephfs-a"

..
2022-06-17 09:50:47.366301 I | cephclient: deleting ceph auth "mds.cephfs-b"
2022-06-17 09:51:02.759762 I | op-mds: successfully deleted mds CephX key for "mds.cephfs-b"
2022-06-17 09:51:02.759782 I | ceph-file-controller: downing filesystem "cephfs"
..
2022-06-17 09:51:03.771935 I | ceph-file-controller: downed filesystem "cephfs"
2022-06-17 09:51:07.825223 I | cephclient: PreservePoolsOnDelete is set in filesystem cephfs. Pools not deleted
..
```

The last line (`Pools not deleted`) from the logs proves that the option to disable deleting pools was actually set.
https://github.com/rook/rook/blob/4079a66a8d1d99287d200661dfc381942dd6ef66/pkg/daemon/ceph/client/filesystem.go#L299-L317

The code at the link above proves that the deletion of the file system actually started

https://github.com/rook/rook/blob/4079a66a8d1d99287d200661dfc381942dd6ef66/pkg/operator/ceph/file/filesystem.go#L112-L113

And from this it follows that the option  `PreserveFilesystemOnDelete` was not implicitly set to true.

It turns out that the following code does not take part in the removal process, but is only decorative in order to write a line to the logs that the option is deprecated.
https://github.com/rook/rook/blob/4079a66a8d1d99287d200661dfc381942dd6ef66/pkg/operator/ceph/file/controller.go#L411-L418

**Expected behavior:**

If `preservePoolsOnDelete` option is set, then the file system should not be deleted.
As it is described here 
https://github.com/rook/rook/blob/v1.9.5/Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md?plain=1#L194-L196

**Environment**:
* Rook version: 1.9.5
* Storage backend version (e.g. for ceph do `ceph -v`):  v16.2.9
* Kubernetes version (use `kubectl version`): 1.23.7

--

related  https://github.com/rook/rook/issues/6492  https://github.com/rook/rook/pull/6495

**Comment by travisn** [comment]
#9915 is in progress to better prevent deletion of the filesystem.

For the last issue, the CephBlockPool CR has been deleted, and the operator is blocked from deleting it, but you want to undelete it? In that case, you can try re-creating the CephBlockPool CR similar to described in the topic [Restoring CRDs after deletion](https://rook.io/docs/rook/latest/Troubleshooting/disaster-recovery/#restoring-crds-after-deletion).

**Comment by R-omk** [comment]
> you can try re-creating the CephBlockPool CR

@travisn
thanks, I've figured this out by now. It worked out.

Now I'm trying to understand out how to save the file system, even taking into account that existing pv can be connected to it, maybe there is already a similar instruction somewhere?

**Comment by travisn** [comment]
> Now I'm trying to understand out how to save the file system, even taking into account that existing pv can be connected to it, maybe there is already a similar instruction somewhere?

This is the error for the filesystem not being created with error 22? This is happening when the operator tries to create the filesystem with this command:
```
ceph fs new <fsname> <metadataPool> <dataPool>
```
Which in your case I believe would be:
```
ceph fs new cephfs cephfs-metadata cephfs-data0
```
You could get the exact command if you enabled debug logging in the operator.
If you run that in the toolbox do you get any more details in the error?

**Comment by R-omk** [comment]
I followed [this](https://docs.ceph.com/en/quincy/cephfs/recover-fs-after-mon-store-loss/) instruction, found in the logs confirmation that the `fscid` was indeed equal to `1` and executed these commands:

```
ceph fs new cephfs cephfs-metadata cephfs-data0 --fscid 1 --force --recover 
ceph fs add_data_pool cephfs cephfs-cephfs-data-pool-ec
ceph fs set cephfs joinable true
ceph fs status
```

and now I have 
```
Events:
Normal   ReconcileSucceeded  3m48s               rook-ceph-file-controller  successfully configured CephFilesystem "rook-ceph/cephfs"
```
and all pods mounted to their pv   
🎉🎉🎉
