### ISSUE TITLE
Run two MGRs to have one in standby mode

### ISSUE THREAD

**Issue by travisn** [rook/rook#1048]
Currently Rook is only running a single MGR pod. We should run two so one is in standby mode and provide faster failover than if we have to wait for kubernetes to bring up another pod.

**Comment by galexrt** [comment]
@travisn Should this be configurable or simply set the replicas to 2?

**Comment by travisn** [comment]
I haven't seen a reason that it would need to be configurable. Having 2 replicas seems sufficient for HA.

**Comment by kokhang** [comment]
Needs to revert this issue in order to get prometheus metrics thru the ceph-mgr working.

**Comment by wangxiao86** [comment]
@travisn  After I modify the mgr code according to  #3028 and I set the mgr Replicas to 2,  my test result is : The active mgr daemon return the prometheus metrics, another standby mgr daemon return an empty answer.

**Comment by galexrt** [comment]
Closing this in favor of #1796, as it has more information on the status of implementing this.
