### ISSUE TITLE
The 404 Not found in Doc

### ISSUE THREAD

**Issue by zeaone** [rook/rook#10482]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/15962991/174920255-d06e7f5f-6b6f-4525-9061-3d0dbd1f7652.png">
At the bottom of this page, the link to the  **design section guideline**  is  **404**

**Comment by parth-gr** [comment]
@zeaone can you refer to https://github.com/rook/rook/blob/master/Documentation/Contributing/development-flow.md this for now

**Comment by parth-gr** [comment]
Thanks for raising this I also see some other places in docs and code that url links are not working,

[Alexander](https://github.com/galexrt) can you please look into these broken links

**Comment by parth-gr** [comment]
Some more places https://rook.io/docs/rook/latest/CRDs/ceph-cluster-crd/#commands-on-the-k8s-consumer-cluster

Ig we need to overlook the docs, and find the links broken and fix them

**Comment by parth-gr** [comment]
The error is `https://rook.io/docs/rook/latest/development-flow.html#design-document` 

This should be updated to `https://rook.io/docs/rook/v1.9/Contributing/development-flow/#design-document`

**Comment by zeaone** [comment]
Thanks, new link is working.

**Comment by zeaone** [comment]
> The error is `https://rook.io/docs/rook/latest/development-flow.html#design-document`
> 
> This should be updated to `https://rook.io/docs/rook/v1.9/Contributing/development-flow/#design-document`

Thanks, new link is working.

**Comment by galexrt** [comment]
We need to update the link in the `design/README.md` to point to https://rook.io/docs/rook/v1.9/Contributing/development-flow/

**Comment by Sheetalpamecha** [comment]
@galexrt I can send a PR for it.
