### ISSUE TITLE
nbd modprobe failed

### ISSUE THREAD

**Issue by liwh1111** [rook/rook#10483]
Install ROOK1.9.0, check csi-rbdplugin error, will this affect rook?

k8s version: 1.20.14
rook: 1.9.0
kernel version: 3.10.0-1127.el7.x86_64

![image](https://user-images.githubusercontent.com/63097736/174921585-74d0657c-6f91-48c1-9910-a1e3bf295d78.png)

**Comment by parth-gr** [comment]
Are you able to create and provision rbd pvc,

@Madhu-1 may would be aware of this error

**Comment by Madhu-1** [comment]
You dont have nbd module installed. this is just a warning you can discard it.

**Comment by liwh1111** [comment]
@parth-gr The provision rbd pvc was created successfully and is ready for use
![image](https://user-images.githubusercontent.com/63097736/174947842-642e0ede-5696-42d9-aeea-ebddbf3b3cbf.png)

@Madhu-1 ok

**Comment by Rakshith-R** [comment]
> You dont have nbd module installed. this is just a warning you can discard it.


>> @Madhu-1 ok

Closing the issue as the doubt is resolved.
