### ISSUE TITLE
Automate Assign issues to issue commenters 

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#10492]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
If a user comes and is a non-collaborator and they wanna try to work on the issue,
they should auto-asign by just putting a comment  `//assign`.

We can discuss further on this,
and how to add this may be by a script or Bot. 

**What is use case behind this feature:**

**Environment**:

**Comment by BlaineEXE** [comment]
This is more streamlined: https://github.com/bdougie/take-action
