### ISSUE TITLE
Use of CEPHFS subpath instead of /volumes/csi/

### ISSUE THREAD

**Issue by m4w0lf** [rook/rook#10508]
Hi everyone,
I'm currently struggling with the follwing problem:
csi-provisioner-cephfs seems to be unable to use a subpath of ceph file system, instead of using / (and then /volumes/csi)

is there any kind of parameter in order to change this default behaviour?

Thank you,
Alex

**Comment by Madhu-1** [comment]
@m4w0lf this is not possible. we will use default /volumes/csi when creating PVC with cephfs, this is not configurable.
