### ISSUE TITLE
Need a new Rook architecture image to include the new rook-agents and rook-flexvolumes

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1051]
This is the current image that needs to be updated. https://github.com/rook/rook/blob/master/Documentation/media/kubernetes.png

**Comment by bassam** [comment]
how about this one:

<img width="1622" alt="screen shot 2017-10-09 at 11 18 16 am" src="https://user-images.githubusercontent.com/1463491/31352424-9237989c-ace3-11e7-8cfe-3500cde9e57d.png">

**Comment by kokhang** [comment]
That is also outdated. The rook volume plugin is not part of kubelet. It lives in two places. Hosts (driver) and agent pods (logic).
