### ISSUE TITLE
Updating port of an external object store does not update health checker

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#10515]
**Is this a bug report or feature request?**
* Bug Report

Updating the port of an external object store does not update the health checker routine. For example, if the user initially supplies port `80` and changes the spec to `8080` afterwards, the health checker keeps trying to check port `80`. 

The easiest way to resolve this may be to stop the health checking goroutine and restart it every time the CephObjectStore is reconciled so it gets the latest version of the object store spec.

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by taxilian** [comment]
I am seeing this as well :-/ trying to figure out how to resolve it without deleting and re-adding the object store...

**Comment by taxilian** [comment]
Ahh, looks like restarting the rook-ceph-operator pod did it

**Comment by BlaineEXE** [comment]
Resolved by https://github.com/rook/rook/pull/11124
