### ISSUE TITLE
Pods are scheduled on nodes without the csi-rbdplugin

### ISSUE THREAD

**Issue by telmich** [rook/rook#10522]
**Is this a bug report or feature request?**
* Bug Report

Pods that are scheduled on control planes (having `node-role.kubernetes.io/control-plane:NoSchedule`) and using PVCs based on rook fail to unmap the RBD image. 

We have a funky stale RBD situation: it seems for some reason (??) the RBD image was mounted, but there is no csi-rbdplugin pod running, so the deletion of the pod left an rbd mapping, which prevents the pvc to be mounted elsewhere.

**Deviation from expected behavior:**

Either the csi-rbdplugin shouldhave a toleration for the above taint or pods that are scheduled on the control plane nodes should not be able to schedule/execute if they reference a PVC that is rook/rbd based.

**Expected behavior:**

Either

* run csi-rbdplugin with control plane tolerations
* or do not schedule pods using pvcs from rook onto the control plane

**How to reproduce it (minimal and precise):**

* Schedule pods on the control plane

**File(s) to submit**:

**Environment**:
* OS (e.g. from /etc/os-release): Alpine Linux
* Kernel (e.g. `uname -a`): 5.15.37-1-lts
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.9.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.9 (4c3647a322c0ff5a1dd2344e039859dcbd28c830) pacific (stable)
* Kubernetes version (use `kubectl version`): 1.24.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
[rook@rook-ceph-tools-temp /]$ ceph health
HEALTH_OK

**Comment by telmich** [comment]
Not sure if this is related, but trying to manually unmap on the node, I get the following errors:

```
[13:34] server63.place10:~# rbd device unmap /dev/rbd6
did not load config file, using default settings.
2022-06-28T13:36:44.163+0200 7f47a2aa0b58 -1 Errors while parsing config file!
2022-06-28T13:36:44.163+0200 7f47a2aa0b58 -1 can't open ceph.conf: (2) No such file or directory
2022-06-28T13:36:44.163+0200 7f47a2aa0b58 -1 Errors while parsing config file!
2022-06-28T13:36:44.163+0200 7f47a2aa0b58 -1 can't open ceph.conf: (2) No such file or directory
rbd: sysfs write failed
rbd: unmap failed: (16) Resource busy
[13:36] server63.place10:~# dmesg |tail -n 5
[4463246.225785] unregister_netdevice: waiting for lo to become free. Usage count = 2
[4463256.279159] unregister_netdevice: waiting for lo to become free. Usage count = 2
[4463266.332100] unregister_netdevice: waiting for lo to become free. Usage count = 2
[4463276.572129] unregister_netdevice: waiting for lo to become free. Usage count = 2
[4463286.838252] unregister_netdevice: waiting for lo to become free. Usage count = 2
[13:36] server63.place10:~# 

```

**Comment by BlaineEXE** [comment]
If you wish to run pods on tainted nodes, you need to configure the Rook CSI drivers with a placement configurations to tolerate those taints. The `operator.yaml` manifest has those configs included in the `rook-ceph-operator-config` configmap

**Comment by telmich** [comment]
@BlaineEXE That totally makes sense. However: pods that reference rook PVCs *are* already running on the control plane nodes, even without adding tolerations in the operator.yaml. 
Or in other words: it totally makes sense to specify them, without specifying them, pods *are* scheduled and are *started* on control planed nodes just by referencing the PVCs and from what I can see, they work.

Until the pods are destroyed, because the maps are not removed. This is at least as far as I can see atm.

**Comment by BlaineEXE** [comment]
This still sounds like Kubernetes behavior. I don't see how Rook can control what pods are allowed to be scheduled.
