### ISSUE TITLE
Use assimilate-conf to ingest multiple ceph settings instead of individual sets on the mon store

### ISSUE THREAD

**Issue by travisn** [rook/rook#10531]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
For every setting in the mon store, rook has a separate call to add or update the setting. We should consider using [ceph config assimilate-conf](https://docs.ceph.com/en/latest/rados/configuration/ceph-conf/) to ingest groups of settings at the same time. 

For example, to enable msgr2, we have three settings currently [here](https://github.com/rook/rook/blob/afba7ec5e917985296d20ab4911350ff8a6cc6b3/pkg/operator/ceph/cluster/cluster.go#L612-L620). These could be added with a single command for better efficiency.

**What is use case behind this feature:**
Simplify operator code for configuring the mon store, and improve the performance of a reconcile.

**Comment by subhamkrai** [comment]
@travisn I'm interested in picking this, I don't have the bandwidth for now but I think since this is a 1.10 feature, we have time and I can assign it to myself?

**Comment by travisn** [comment]
I would think the INPUT_FILE is a temporary file that has the settings to be applied, then it's deleted after the assimilate-conf command is run.

**Comment by BlaineEXE** [comment]
That was my thinking as well. It should be a temp file. And the OUTPUT_FILE should be cleaned up as well.

**Comment by subhamkrai** [comment]
That sounds good, will start working on this
