### ISSUE TITLE
build: snapshot and publish yaml files and other artifacts

### ISSUE THREAD

**Issue by bassam** [rook/rook#1053]
We should also consider snapshotting all our yaml files, replacing the version numbers etc. and pushing them to our S3 bucket.

**Comment by travisn** [comment]
We need to publish the yaml files with the release. #1318 and #1325 are both a result of the same underlying cause of users who run the `alpha` version of the operator and then use the yaml from `master`. Since master is not backward compatible with the current `alpha`, users are seeing errors.
