### ISSUE TITLE
Using mismatch operator version and ceph breaks rgw

### ISSUE THREAD

**Issue by mgugino-uipath** [rook/rook#10538]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Mixing ceph 16.x and 15.x components breaks rgw syncing and possibly other issues

**Expected behavior:**
Operator should clearly define which versions it supports

**How to reproduce it (minimal and precise):**
Setup multi-site utilizing rook-ceph v1.8.9 and ceph 15.2.9.  Create users and buckets via rook-ceph-tools pod also on v1.8.9.  Sometimes (not sure the trigger) data and metadata sync seems to complete break.

**File(s) to submit**:

Encountered the bug listed here: https://tracker.ceph.com/issues/51096

I was able to see the 500 errors from RGW while metadata sync was running.
```
debug 2022-06-30T04:05:19.511+0000 7f2c59232700  1 ====== starting new request req=0x7f2be31456b0 =====
debug 2022-06-30T04:05:19.512+0000 7f2c59232700  0 ERROR: could not decode buffer info, caught buffer::error
debug 2022-06-30T04:05:19.512+0000 7f2c59232700 -1 ERROR: do_read_bucket_instance_info failed: -5
debug 2022-06-30T04:05:19.512+0000 7f2c59232700  0 req 26 0.001000018s NOTICE: couldn't get bucket from bucket_name (name=mybucket)
debug 2022-06-30T04:05:19.512+0000 7f2c59232700  1 op->ERRORHANDLER: err_no=-5 new_err_no=-5
debug 2022-06-30T04:05:19.512+0000 7f2c59232700  0 WARNING: set_req_state_err err_no=5 resorting to 500
debug 2022-06-30T04:05:19.512+0000 7f2c4ca19700  1 ====== req done req=0x7f2be31456b0 op status=0 http_status=500 latency=0.001000018s ======
debug 2022-06-30T04:05:19.512+0000 7f2c4ca19700  1 beast: 0x7f2be31456b0: 10.42.5.69 - - [2022-06-30T04:05:19.512416+0000] "GET /mybucket/?acl HTTP/1.1" 500 226 - "aws-sdk-dotnet-coreclr/3.7.0.28 aws-sdk-dotnet-core/3.7.0.27 .NET_Core/3.1.22 OS/Linux_4.18.0-193.75.1.el8_2.x86_64_#1_SMP_Tue_Feb_8_09:21:43_EST_2022 ClientAsync" -
debug 2022-06-30T04:05:22.214+0000 7f2c4e21c700  1 ====== starting new request req=0x7f2be30c46b0 =====
```

**Comment by thotz** [comment]
Checking from @cbodley from the upstream tracker and errors in the logs both look like a similar issue.  Here sync failed while decoding the bucket info. And as per @cbodley the bucket layout changed from octopus to pacific which may trigger this failure.  @cbodley do we support two different ceph versions with multisite.

**Comment by mgugino-uipath** [comment]
FYI, we're not attempting two separate versions of ceph in multisite, each ceph cluster is the same version, only the operator and tools pods have different ceph binary versions than the ceph cluster itself.

**Comment by thotz** [comment]
@mgugino-uipath : can you please confirm all the rgw pods in the same ceph versions by running `ceph version` from each pod? Is this error happens when you execute `realm pull` from toolbox pod or something? AFAIR the `realm pull` executed from operator pod during reconciliation of `cephObjectStoreRealm`but not sure whether it is executed every time or just during creation. I can check on that part. Can you please run rgw in more verbose log level and share that o/p?

**Comment by mgugino-uipath** [comment]
All the rgw pods are the same version.  realm pull works fine, it's run via the operator the first time, there's not normally a need to run it from the toolbox pod.

The problem seems to be, when a 16.x client performs bucket create or modify operations on a 15.x cluster, those buckets get stored with the 16.x format.  Then the RGWs attempt to read that data at some point and are unable to decode them, that's the error message we're seeing in the first comment.

Anyway, this issue was closed as won't fix in ceph.  Having 16.x clients talk to 15.x clusters is not supported, but rook doesn't specify this, nor do newer operators ship 15.x clients.

**Comment by godber** [comment]
We've just hit this issue as well:

With rook 1.6, while still using Octopus, any `radosgw-admin bucket ...` command that modifies a bucket will upgrade the Octopus bucket to Pacific and then be unreadable by the Octopus version of the RGWs.

At least that's what we think happened.

**Comment by subhamkrai** [comment]
> We've just hit this issue as well:
> 
> With rook 1.6, while still using Octopus, any `radosgw-admin bucket ...` command that modifies a bucket will upgrade the Octopus bucket to Pacific and then be unreadable by the Octopus version of the RGWs.
> 
> At least that's what we think happened.

I think this might be fixed in newer releases

**Comment by david-caro** [comment]
For future reference, upgrading the packages to a newer release worked for us: https://phabricator.wikimedia.org/T376673
