### ISSUE TITLE
N osds: 0 up, N in for v4/v6 Dual-Stack Cluster

### ISSUE THREAD

**Issue by nikhiljha** [rook/rook#10548]
I figured out this issue already, but this seemed basically un-debuggable so I'm making a GitHub issue to add this failure case to the QuickStart documentation.

DId you just make a new rook-ceph cluster? v4/v6 dual stack? All your OSDs come up and appear to not have errors, but your OSDs show as down and your ceph commands all hang? Somehow some network requests return but with empty responses(???) - tricking you into thinking your network is fine?

```
$ ceph pg 1.0 query
Couldn't parse JSON : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/bin/ceph", line 1310, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1230, in main
```

Well, I'm here to tell you that your network is not fine. You forgot to do...

```
  network:
    dualStack: true
```

in your CephCluster config! After changing that the PGs become available and everything works great.

**Comment by sp98** [comment]
@nikhiljha This is already covered in the cluster CRD documentation [here](https://rook.io/docs/rook/v1.9/CRDs/ceph-cluster-crd/?h=network+configuration+settings#network-configuration-settings)

This doesn't look like something that should be added to the quick start documentation.

Let me know if that works and feel free to close this bug if it does.

**Comment by nikhiljha** [comment]
I know, I saw that documentation. I feel like there has to be a way to give this better first-class IPv6 support though -- maybe the example CRD should include this but commented out?

**Comment by sp98** [comment]
Do you mean the example [CR]?  It mentions about `dualStack` and comments it out already. (https://github.com/rook/rook/blob/8b512a14bb5726c8b7368c796ea60add2529f0e7/deploy/examples/cluster.yaml#L108)?

IMO, the current documentation should suffice. But I'll check with the team and get back to you.
