### ISSUE TITLE
dashboard's object gateway 500

### ISSUE THREAD

**Issue by ningjunwei2** [rook/rook#10557]
os ubuntu 20.04. Linux rd-k8s-ceph-test-master-01 5.11.0-49-generic https://github.com/rook/rook/issues/55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
kubectl ： v1.23.2

my ceph dashboard have problem，my object gateway is 500，other panel is ok。

![image](https://user-images.githubusercontent.com/88232846/177530773-a2adde3a-e335-4a71-b79f-f6e6cb6b9bc7.png)
![image](https://user-images.githubusercontent.com/88232846/177530797-c8eda3bc-a9d0-4cf3-b4fa-c7687e6505d8.png)
![image](https://user-images.githubusercontent.com/88232846/177531080-924313c6-ccf6-498c-86b2-3cd1ec9c4d91.png)

**Comment by sp98** [comment]
@ningjunwei2 Can you try disabling (`dasbhoard.enabled: false`) the dashboard from the cluster CR ? 
And once the dashboard is disabled,  enable (dasbhoard.enabled: true`) it again. 

The issue looks related to https://github.com/rook/rook/issues/9660

**Comment by ningjunwei2** [comment]
@sp98 I try disable dashboard.enabled:false, then  I enable true for it . But  it is still the same

**Comment by ningjunwei2** [comment]
> @sp98 I try disable dashboard.enabled:false, then I enable true for it . But it is still the same

is right for the  log  "unable to get monitor info from DNS SRV with service name: ceph-mon" ?
