### ISSUE TITLE
Rook 1.9.7 toolbox version

### ISSUE THREAD

**Issue by anthonyeleven** [rook/rook#10597]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

OSD container:
sh-4.4# ceph -v
ceph version 17.2.1 (ec95624474b1871a821a912b8c3af68f8f8e7aa1) quincy (stable)

toolbox:
sh-4.4$ ceph -v
ceph version 16.2.9 (4c3647a322c0ff5a1dd2344e039859dcbd28c830) pacific (stable)

**Expected behavior:**

Toolbox CLI version matches the daemon container version.  Since the toolbox image is not part of the upstream ceph/ceph release, how does one match the toolbox version to the release?

**How to reproduce it (minimal and precise):**

  toolbox:
    enabled: true
    image: registry.company.com:5000/rook/ceph:v1.9.7
    
cephClusterSpec:
    cephVersion:
      image: registry.indexexchange.com:5000/ceph/ceph:v17.2.1

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 8
* Kernel (e.g. `uname -a`): 5.18.5-1.el8.elrepo.x86_64
* Cloud provider or hardware configuration: Dell DL430
* Rook version (use `rook version` inside of a Rook Pod): sh-4.4$ rook version
rook: v1.9.7
go: go1.17.11
* Storage backend version (e.g. for ceph do `ceph -v`): 17.2.1
* Kubernetes version (use `kubectl version`):
* Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:26:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): no idea
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by travisn** [comment]
The ceph version inside the base image for the toolbox is the same as the operator, it might not match the running version of the ceph daemons. That said, there is a change in the master branch that will be part of the Rook v1.10 release where the toolbox will allow you to specify the ceph image, instead of the rook image, so you could easily test it with v17.2.1. The [new toolbox spec](https://github.com/rook/rook/blob/master/deploy/examples/toolbox.yaml) should fully work with earlier versions of Rook if you want to test it out now.

**Comment by subhamkrai** [comment]
@anthonyeleven 1 .10 will somewhere around 2nd half of next month @travisn can answer better.
But I think you can run toolbox yaml from the master which will give you the option to change ceph version. See https://github.com/rook/rook/blob/master/deploy/examples/toolbox.yaml

**Comment by anthonyeleven** [comment]
Thanks!  In our case we'll wait for 1.10, this will be a good test case for upgrading Rook before we get to real production.
