### ISSUE TITLE
minio pvc FailedMount

### ISSUE THREAD

**Issue by clcc2019** [rook/rook#10603]
MountVolume.MountDevice failed for volume "pvc-a27b1cfb-194e-4a1e-845f-342e0b792299" : rpc error: code = Internal desc = rbd image replicapool/csi-vol-6547ec07-a9a4-11ec-8794-4a4838419698 is still being used
  Warning  FailedMount             3m20s              kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[minio-token-bbp7n data]: timed out waiting for the condition
  Warning  FailedMount             64s (x8 over 19m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data minio-token-bbp7n]: timed out waiting for the condition

use rbd unmap /dev/rbd*,
restart pod

**Comment by Madhu-1** [comment]
RWO pod is expected to run on only one node at a time. if you have issue with node failure please try node-loss in the [csi troubleshooting guide](https://rook.io/docs/rook/latest/Troubleshooting/ceph-csi-common-issues/#node-loss) @travisn shared

**Comment by clcc2019** [comment]
> RWO pod is expected to run on only one node at a time. if you have issue with node failure please try node-loss in the [csi troubleshooting guide](https://rook.io/docs/rook/latest/Troubleshooting/ceph-csi-common-issues/#node-loss) @travisn shared

This is not a duplicate mount issue, we store a lot of metadata in minio which makes the pod mount volume timeout

**Comment by clcc2019** [comment]
The ceph rbd is correctly mounted to the node and can access the file, but the pod shows that the mount has timed out. After about 12 hours, the pod is running.
