### ISSUE TITLE
mon liveness probe execution error

### ISSUE THREAD

**Issue by vicnoah** [rook/rook#10621]
Manually executing the command in pod returns this error, which causes the cluster storage to drop out frequently
```
env -i sh -c ceph --admin-daemon /run/ceph/ceph-mon.b.asok mon_status
unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] RADOS object not found (error connecting to the cluster)
```

**Comment by travisn** [comment]
As a test workaround, does the mon stay healthy if the [liveness probe is disabled](https://rook.io/docs/rook/latest/CRDs/Cluster/ceph-cluster-crd/#health-settings)? You could also try adjusting the timeouts or other parameters on the liveness probe.

**Comment by vicnoah** [comment]
> As a test workaround, does the mon stay healthy if the [liveness probe is disabled](https://rook.io/docs/rook/latest/CRDs/Cluster/ceph-cluster-crd/#health-settings)? You could also try adjusting the timeouts or other parameters on the liveness probe.

I found that all the probes of rook-ceph are not working properly, when I turn off the probes everything is fine. But the csi plugin sometimes restarts.
