### ISSUE TITLE
Add Rook to the Rancher Catalog

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#1064]
Rancher has a catalog of applications that you can install with the click of a button. This makes those applications super accessible on Rancher.

In the interests of getting Rook available to more people we should add it to the Rancher Catalog.

**Comment by michalmikolajczyk** [comment]
Rook Operator is available from their Helm charts https://charts.rook.io/alpha `alpha` is the official release channel and `master` is the latest.

https://rook.io/docs/rook/v0.7/helm-operator.html

FYI I managed to spin up a Rook cluster in Rancher 2.0 and consume a PV by a PVC, which specified the Rook storage class. The cluster and storage class had to be created using kubectl.

**Comment by jbw976** [comment]
@galexrt will follow up to see what it takes to be added to the catalog.
