### ISSUE TITLE
OSD is not created. Objectstore pods not starting

### ISSUE THREAD

**Issue by hohoqq** [rook/rook#10648]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
`ceph status`
```
  cluster:
    id:     6ed9be8d-fa05-4463-a199-fd74d2678464
    health: HEALTH_WARN
            1 MDSs report slow metadata IOs
            Reduced data availability: 10 pgs inactive
            OSD count 0 < osd_pool_default_size 3
 
  services:
    mon: 3 daemons, quorum a,b,c (age 25m)
    mgr: a(active, since 25m), standbys: b
    mds: 1/1 daemons up, 1 standby
    osd: 0 osds: 0 up, 0 in
 
  data:
    volumes: 1/1 healthy
    pools:   10 pools, 10 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             10 unknown
```

`kubectl describe pod rook-ceph-rgw-ceph-objectstore-a-6bb94dd6c-8bfcv -n rook-ceph`
```
...
Warning  Unhealthy    40s (x129 over 25m)  kubelet            Startup probe failed: dial tcp 10.233.70.74:8080: connect: connection refused
...
```

**Expected behavior:**
rook-ceph-rgw-ceph-objectstore pods starting and healthy.
Cluster health is healthy

**How to reproduce it (minimal and precise):**
Install [Rook Ceph Operator](https://github.com/rook/rook/blob/master/Documentation/Helm-Charts/operator-chart.md) and [Rook Ceph Cluster](https://github.com/rook/rook/blob/master/Documentation/Helm-Charts/ceph-cluster-chart.md)

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
[cluster.yaml.txt](https://github.com/rook/rook/files/9211481/cluster.yaml.txt)

* Operator's logs, if necessary
[rook-ceph-operator-689b4ffd6c-9rjj5.log](https://github.com/rook/rook/files/9211486/rook-ceph-operator-689b4ffd6c-9rjj5.log)

**Environment**:
* OS (e.g. from /etc/os-release): Oracle Linux Server 8.6
* Kernel (e.g. `uname -a`): Linux test-cp1-k8s 5.4.17-2136.308.9.el8uek.x86_64 #2 SMP Mon Jun 13 20:36:40 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):
```
NAME             	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                   	APP VERSION
rook-ceph        	rook-ceph	1       	2022-07-28 14:05:53.165304895 +0000 UTC	deployed	rook-ceph-v1.9.7        	v1.9.7     
rook-ceph-cluster	rook-ceph	1       	2022-07-28 14:07:14.387928288 +0000 UTC	deployed	rook-ceph-cluster-v1.9.7	v1.9.7
```
* Kubernetes version (use `kubectl version`): v1.22.5

**Comment by hohoqq** [comment]
```
kubectl -n rook-ceph get pod -l app=rook-ceph-osd-prepare
No resources found in rook-ceph namespace.
```

**Comment by satoru-takeuchi** [comment]
I guess there is a problem in CephCluster CR. Could you show me your `cluster.yaml` and the result of `lsblk` in a node on which you want to create OSDs. If you use PVCs to create OSDs, please show me the manifests of these OSDs.

**Comment by hohoqq** [comment]
@satoru-takeuchi Here are cluster.yaml (added .txt because Github don't accept .yaml):

- [cluster.yaml.txt](https://github.com/rook/rook/files/9216451/cluster.yaml.txt)
- [rook-ceph-operator-689b4ffd6c-9rjj5.log](https://github.com/rook/rook/files/9216450/rook-ceph-operator-689b4ffd6c-9rjj5.log)

```
lsblk 
NAME              MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                 8:0    0   40G  0 disk 
├─sda1              8:1    0  600M  0 part /boot/efi
├─sda2              8:2    0    1G  0 part /boot
└─sda3              8:3    0 38.4G  0 part 
  └─ol-root       252:0    0 38.4G  0 lvm  /
sdb                 8:16   0   10G  0 disk 
└─sdb1              8:17   0   10G  0 part 
  └─datavg-datalv 252:1    0   10G  0 lvm  /mnt/data
sdc                 8:32   0  100G  0 disk 
sdd                 8:48   0  100G  0 disk 
sde                 8:64   0  100G  0 disk 
sdf                 8:80   0  100G  0 disk 
sr0                11:0    1 1024M  0 rom
```

sdc-sdf are for OSD.

**Comment by hohoqq** [comment]
> If you use PVCs to create OSDs, please show me the manifests of these OSDs.

When installing via helm charts, do I need to add something to make the OSD pods appear? Now we have `rook-ceph-rgw-ceph-objectstore-a` pod restarting, 0 OSD in ceph status

**Comment by zhucan** [comment]
@hohoqq Could you show the full logs of the operator? there is no any logs for creating osd.

**Comment by hohoqq** [comment]
@zhucan Sorry. Didn't pay attention.
[rook-ceph-operator.log](https://github.com/rook/rook/files/9218371/rook-ceph-operator.log)

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/181737056-e5dc14a2-cf0d-4016-bfa9-ad520fd6d997.png)
@hohoqq Take look at the cluster.yaml, the rbac  is missing.

**Comment by hohoqq** [comment]
Shouldn't Helm create this resource? 
Please suggest what needs to be changed to fix this?

**Comment by zhucan** [comment]
The value.yaml is? Do you enable the monitoring?

**Comment by hohoqq** [comment]
Indeed, the monitoring was true. Fixed it and now osds are up and running. Thank you!
