### ISSUE TITLE
CephObjectStoreZone pool spec cannot be updated

### ISSUE THREAD

**Issue by thotz** [rook/rook#10640]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The zones creation by ceph-object-zone-controller only creates pools if the zone doesn't already exist. If a user updates the pool spec after zone creation, the pools won't be updated, but the reconcile will still succeed, suggesting that the pools have the latest config when they do not in reality.

**Expected behavior:**
The pool create/update should be called on every reconcile.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by BlaineEXE** [comment]
RGW may create pools if Rook doesn't, so in this case RGW may create pools automatically. However, the pool properties may not be set as specified by the user, which is an issue.

**Comment by thotz** [comment]
@BlaineEXE: I am trying to understand the underlying here, Here zones will be created after creating pools, so if operator restarts how it results in creating zone without creating pools.
```
createPoolsAndZone() {
object.CreatePools()
..
..
\\ zone creation
    args := []string{"zone", "create", realmArg, zoneGroupArg, zoneArg, accessKeyArg, secretKeyArg}

    if zoneIsMaster {
        // master zone does not exist yet for zone group
        args = append(args, "--master")
    }   
    if len(zone.Spec.CustomEndpoints) > 0 { 
        // If custom endpoint list defined set those values
        zoneEndpoints := strings.Join(zone.Spec.CustomEndpoints, ",")
        args = append(args, fmt.Sprintf("--endpoints=%s", zoneEndpoints))
    }   
    output, err := object.RunAdminCommandNoMultisite(objContext, false, args...)
    if err != nil {
        return errors.Wrapf(err, "failed to create ceph zone %q for reason %q", zone.Name, output)
    }   
    logger.Debugf("created ceph zone %q", zone.Name)
}
```

**Comment by BlaineEXE** [comment]
After poking through the code, you are right. It's not an idempotency issue, but the pools still won't be updated if a user changes the pool spec. I'll rename the issue and change the description.
