### ISSUE TITLE
Re-added osd but did not join the cluster normally

### ISSUE THREAD

**Issue by yxiaoy6** [rook/rook#10656]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
![image](https://user-images.githubusercontent.com/43592152/182132898-fff5c78f-bbd6-4a29-ad40-c277ab507d4f.png)

**Expected behavior:**

**How to reproduce it (minimal and precise):**

I first removed 192.168.22.80 and osd, and then rejoined the cluster
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
![image](https://user-images.githubusercontent.com/43592152/182133400-16e08710-c9a8-4328-87f9-361d7ad75960.png)

* Operator's logs, if necessary
* <html>
<body>

2022-08-01 10:45:59.894413 I \| op-osd: start running osds in namespace "rook-ceph"
--
Mon, Aug 1 2022 6:45:59 pm | 2022-08-01 10:45:59.894425 I \| op-osd: wait timeout for healthy OSDs during upgrade or restart is "10m0s"
Mon, Aug 1 2022 6:45:59 pm | 2022-08-01 10:45:59.909080 I \| op-osd: start provisioning the OSDs on PVCs, if needed
Mon, Aug 1 2022 6:45:59 pm | 2022-08-01 10:45:59.912501 I \| op-osd: no storageClassDeviceSets defined to configure OSDs on PVCs
Mon, Aug 1 2022 6:45:59 pm | 2022-08-01 10:45:59.912514 I \| op-osd: start provisioning the OSDs on nodes, if needed
Mon, Aug 1 2022 6:45:59 pm | 2022-08-01 10:45:59.972337 I \| op-osd: 3 of the 3 storage nodes are valid
Mon, Aug 1 2022 6:46:00 pm | 2022-08-01 10:46:00.366129 I \| op-k8sutil: Removing previous job rook-ceph-osd-prepare-cn-shanghai.192.168.22.79 to start a new one
Mon, Aug 1 2022 6:46:00 pm | 2022-08-01 10:46:00.382688 I \| op-k8sutil: batch job rook-ceph-osd-prepare-cn-shanghai.192.168.22.79 still exists
Mon, Aug 1 2022 6:46:00 pm | 2022-08-01 10:46:00.554055 I \| op-mgr: successful modules: prometheus
Mon, Aug 1 2022 6:46:00 pm | 2022-08-01 10:46:00.555844 I \| op-config: setting "global"="osd_pool_default_pg_autoscale_mode"="on" option to the mon configuration database
Mon, Aug 1 2022 6:46:01 pm | 2022-08-01 10:46:01.106732 I \| op-config: successfully set "global"="osd_pool_default_pg_autoscale_mode"="on" option to the mon configuration database
Mon, Aug 1 2022 6:46:01 pm | 2022-08-01 10:46:01.106754 I \| op-config: setting "global"="mon_pg_warn_min_per_osd"="0" option to the mon configuration database
Mon, Aug 1 2022 6:46:01 pm | 2022-08-01 10:46:01.694258 I \| op-config: successfully set "global"="mon_pg_warn_min_per_osd"="0" option to the mon configuration database
Mon, Aug 1 2022 6:46:01 pm | 2022-08-01 10:46:01.694278 I \| op-mgr: successful modules: mgr module(s) from the spec
Mon, Aug 1 2022 6:46:03 pm | 2022-08-01 10:46:03.387980 I \| op-k8sutil: batch job rook-ceph-osd-prepare-cn-shanghai.192.168.22.79 deleted
Mon, Aug 1 2022 6:46:03 pm | 2022-08-01 10:46:03.395721 I \| op-osd: started OSD provisioning job for node "cn-shanghai.192.168.22.79"
Mon, Aug 1 2022 6:46:03 pm | 2022-08-01 10:46:03.413260 I \| op-k8sutil: Removing previous job rook-ceph-osd-prepare-cn-shanghai.192.168.22.80 to start a new one
Mon, Aug 1 2022 6:46:03 pm | 2022-08-01 10:46:03.451902 I \| op-k8sutil: batch job rook-ceph-osd-prepare-cn-shanghai.192.168.22.80 still exists
Mon, Aug 1 2022 6:46:05 pm | 2022-08-01 10:46:05.560736 I \| op-mgr: the dashboard secret was already generated
Mon, Aug 1 2022 6:46:05 pm | 2022-08-01 10:46:05.560751 I \| op-mgr: setting ceph dashboard "admin" login creds
Mon, Aug 1 2022 6:46:06 pm | 2022-08-01 10:46:06.007457 I \| op-mgr: successfully set ceph dashboard creds
Mon, Aug 1 2022 6:46:06 pm | 2022-08-01 10:46:06.457825 I \| op-k8sutil: batch job rook-ceph-osd-prepare-cn-shanghai.192.168.22.80 deleted
Mon, Aug 1 2022 6:46:06 pm | 2022-08-01 10:46:06.466233 I \| op-osd: started OSD provisioning job for node "cn-shanghai.192.168.22.80"
Mon, Aug 1 2022 6:46:06 pm | 2022-08-01 10:46:06.506207 I \| op-k8sutil: Removing previous job rook-ceph-osd-prepare-cn-shanghai.192.168.31.206 to start a new one
Mon, Aug 1 2022 6:46:06 pm | 2022-08-01 10:46:06.530791 I \| op-k8sutil: batch job rook-ceph-osd-prepare-cn-shanghai.192.168.31.206 still exists
Mon, Aug 1 2022 6:46:08 pm | 2022-08-01 10:46:08.340240 I \| op-mgr: successful modules: dashboard
Mon, Aug 1 2022 6:46:09 pm | 2022-08-01 10:46:09.535731 I \| op-k8sutil: batch job rook-ceph-osd-prepare-cn-shanghai.192.168.31.206 deleted
Mon, Aug 1 2022 6:46:09 pm | 2022-08-01 10:46:09.544194 I \| op-osd: started OSD provisioning job for node "cn-shanghai.192.168.31.206"
Mon, Aug 1 2022 6:46:09 pm | 2022-08-01 10:46:09.549598 I \| op-osd: OSD orchestration status for node cn-shanghai.192.168.22.79 is "orchestrating"
Mon, Aug 1 2022 6:46:09 pm | 2022-08-01 10:46:09.549630 I \| op-osd: OSD orchestration status for node cn-shanghai.192.168.22.80 is "starting"
Mon, Aug 1 2022 6:46:09 pm | 2022-08-01 10:46:09.549639 I \| op-osd: OSD orchestration status for node cn-shanghai.192.168.31.206 is "starting"
Mon, Aug 1 2022 6:46:11 pm | 2022-08-01 10:46:11.072144 I \| op-osd: updating OSD 0 on node "cn-shanghai.192.168.22.80"
Mon, Aug 1 2022 6:46:11 pm | 2022-08-01 10:46:11.104641 I \| op-osd: OSD orchestration status for node cn-shanghai.192.168.22.79 is "completed"
Mon, Aug 1 2022 6:46:11 pm | 2022-08-01 10:46:11.112641 I \| op-osd: OSD orchestration status for node cn-shanghai.192.168.22.80 is "orchestrating"
Mon, Aug 1 2022 6:46:12 pm | 2022-08-01 10:46:12.630975 I \| op-osd: updating OSD 1 on node "cn-shanghai.192.168.31.206"
Mon, Aug 1 2022 6:46:12 pm | 2022-08-01 10:46:12.662053 I \| op-osd: OSD orchestration status for node cn-shanghai.192.168.31.206 is "orchestrating"
Mon, Aug 1 2022 6:46:12 pm | 2022-08-01 10:46:12.662260 I \| op-osd: OSD orchestration status for node cn-shanghai.192.168.22.80 is "completed"
Mon, Aug 1 2022 6:46:14 pm | 2022-08-01 10:46:14.212014 I \| op-osd: updating OSD 2 on node "cn-shanghai.192.168.22.79"
Mon, Aug 1 2022 6:46:14 pm | 2022-08-01 10:46:14.248077 I \| op-osd: OSD orchestration status for node cn-shanghai.192.168.31.206 is "completed"
Mon, Aug 1 2022 6:46:14 pm | 2022-08-01 10:46:14.993590 I \| op-mon: checking if multiple mons are on the same node
Mon, Aug 1 2022 6:46:15 pm | 2022-08-01 10:46:15.735799 I \| op-osd: updating OSD 3 on node "cn-shanghai.192.168.22.79"
Mon, Aug 1 2022 6:46:16 pm | 2022-08-01 10:46:16.613033 I \| cephclient: successfully disallowed pre-pacific osds and enabled all new pacific-only functionality
Mon, Aug 1 2022 6:46:16 pm | 2022-08-01 10:46:16.613054 I \| op-osd: finished running OSDs in namespace "rook-ceph"
Mon, Aug 1 2022 6:46:16 pm | 2022-08-01 10:46:16.613060 I \| ceph-cluster-controller: done reconciling ceph cluster in namespace "rook-ceph"
Mon, Aug 1 2022 6:46:16 pm | 2022-08-01 10:46:16.626103 I \| ceph-cluster-controller: reporting cluster telemetry

</body>
</html>
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):CentOS Linux release 7.9.2009 (Core)
* Kernel (e.g. `uname -a`):3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:Cloud provider
* Rook version (use `rook version` inside of a Rook Pod):rook-1.9.7
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.9
* Kubernetes version (use `kubectl version`): v1.21.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): ack
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] HEALTH_OK(https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by sp98** [comment]
Hi @yxiaoy6  Please confirm if you followed the steps to [remove the osd](https://rook.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-osd-mgmt/?h=osd+management#remove-an-osd) and [add the osd back.](https://rook.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-osd-mgmt/?h=osd+management#remove-an-osd)

**Comment by sp98** [comment]
> Hi @yxiaoy6 Please confirm if you followed the steps to [remove the osd](https://rook.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-osd-mgmt/?h=osd+management#remove-an-osd) and [add the osd back.](https://rook.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-osd-mgmt/?h=osd+management#remove-an-osd)

@yxiaoy6 any update on this?

**Comment by yxiaoy6** [comment]
> 

Thanks, it's working fine now
