### ISSUE TITLE
Create cluster-peer-token secret for external mode clusters

### ISSUE THREAD

**Issue by vbnrh** [rook/rook#10660]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
For external mode clusters, create a secret with the FSID of the cluster. 

**What is use case behind this feature:**
For Disaster Recovery, we require to have the FSID of the cluster to correctly sync data with backup clusters. This is already being done by Rook for converged mode and is used by MCO operator for bootstrapping the clusters for DR.  Now for external mode we require the details for the Operator to function properly for Metro DR usage.

**Comment by vbnrh** [comment]
@travisn Please take a look

**Comment by travisn** [comment]
Are the following valid assumptions about the FSID for the external cluster scenario?
- The FSID is uniquely generated for the local Rook cluster that is configured to connect to an external Ceph Cluster. 
- The FSID is different from the Ceph FSID of the external cluster

I see the secret is generated in [GenerateBootstrapPeerSecret()](https://github.com/rook/rook/blob/de448d31f9c3fb21420b783d4a2f9e788bfa83a9/pkg/operator/ceph/controller/mirror_peer.go#L118-L150). So the external cluster could likely call that helper and create a new secret.

**Comment by vbnrh** [comment]
@travisn From my point of understanding, the FSID generated for converged mode ( cluster-peer-token-* ) is the Ceph FSID. We use it to identify between regional (different ceph fsids to two different cephclusters)  and metro (same fsid to one external ceph cluster).

So in this case, I assume the FSID is the external CephFSID but you could correct me if i am wrong. I am not sure whether Rook cluster's own FSID is used in the converged mode generated secret.

**Comment by parth-gr** [comment]
@vbnrh Yes the FSID is the cephFSID,

There already a `rook-ceph-mon` secret created which contains the cephFSID so you can make use of it,

```
"name": "rook-ceph-mon",
                "kind": "Secret",
                "data": {
                    "admin-secret": "admin-secret",
                    "fsid": self.out_map["ROOK_EXTERNAL_FSID"],
                    "mon-secret": "mon-secret",
                },
```

Or let me know there is a requirement to create a separate secret just for FSID.

**Comment by vbnrh** [comment]
@parth-gr thanks, i will try to make use of this secret. If it works, i'll close the issue
