### ISSUE TITLE
How to recover a deleted ceph cluster

### ISSUE THREAD

**Issue by ningjunwei2** [rook/rook#10671]
os ubuntu 20.04. Linux rd-k8s-ceph-test-master-01 5.11.0-49-generic https://github.com/rook/rook/issues/55 SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
kubectl ： v1.23.2
ceph:v16.2.9
rook:v1.9.5
![image](https://user-images.githubusercontent.com/88232846/182522477-5cfacca2-8186-4e2a-884f-d782afff2e6f.png)
my rook ceph cluster  is deleting， how should i restore it？

**Comment by ningjunwei2** [comment]
> @ningjunwei2 take a look at https://github.com/rook/rook/blob/master/Documentation/Troubleshooting/disaster-recovery.md#restoring-crds-after-deletion
thanks

**Comment by Rakshith-R** [comment]
Closing this issue, since the query is answered. 

@ningjunwei2 feel free to open a discussion thread if you any more queries
