### ISSUE TITLE
external cluster - waiting for ceph monitors upgrade to finish. (Compare CommitID)

### ISSUE THREAD

**Issue by jclab-joseph** [rook/rook#10688]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Ceph-object-controller is not able to create ObjectStore. Instead it is stuck with the follwing error message:
```
ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph-external/my-store". waiting for ceph monitors upgrade to finish. current version: 16.2.9-0 pacific. expected version: 16.2.9-0 pacific. will reconcile again in 1m0s
```

Maybe same issue #9544

**Expected behavior:**
Ceph-object-controller should successfully create ObjectStore.

**How to reproduce it (minimal and precise):**

Same #9544

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): Ubuntu 20.04 LTS
* Cloud provider or hardware configuration: On-premise
* Rook version (use `rook version` inside of a Rook Pod): 1.9.8
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.9
* Kubernetes version (use `kubectl version`): v1.20.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On-premise
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

---

Maybe related code : 
https://github.com/rook/rook/blob/v1.9.8/pkg/operator/ceph/object/controller.go#L327

---

Probably because of DeepEquals. I'm using Proxmox and this is a different build commit. It seems that DeepEquals compares up to CommitID.

**Comment by jclab-joseph** [comment]
@travisn 
I don't know what object-external.yaml means.

What I've checked is this:
- Check the version with ceph --version in proxmox. (The same is shown in CephCluster's status.)
- Check the version with ceph --version in the ceph docker image.
- Both versions are the same, only the commit id is different.
- Install canonical ceph on proxmox. rook-ceph-operator no longer throws an error.

It seems to me that #9633 will not solve it. This PR has only the csi version changed.

**Comment by parth-gr** [comment]
> Both versions are the same, only the commit id is different.

What commit-id is difference?

> Install canonical ceph on proxmox. rook-ceph-operator no longer throws an error.

Does this solves your problem?

**Comment by travisn** [comment]
@jclab-joseph I was referring to [this example external object manifest](https://github.com/rook/rook/blob/master/deploy/examples/object-external.yaml).

**Comment by jclab-joseph** [comment]
In proxmox : ` ceph version 16.2.9 (a569859f5e07da0c4c39da81d5fb5675cd95da49) pacific (stable)`
In docker : `ceph version 16.2.9 (4c3647a322c0ff5a1dd2344e039859dcbd28c830) pacific (stable)`

Canonical ceph means that installed it with cephadm.
This solved the problem.

**Comment by parth-gr** [comment]
Yaa so the problem is with `DeepEqual` ,

So what do you want us to fix, I see in the latest ceph versions we install ceph using `cephadm` only

**Comment by jclab-joseph** [comment]
I'd like to suggest comparing the version parts (major, minor,...) instead of DeepEqual.

Installing with cephadm from Proxmox is not a normal way. I have a dependency problem.

**Comment by parth-gr** [comment]
>I'd like to suggest comparing the version parts (major, minor,... without CommitID) instead of DeepEqual.
Installing with cephadm from Proxmox is not a normal way. I have a dependency problem.

Okay, thanks for the information.

> I used object.yaml instead of object-external.yaml . CephCluster used cluster-external-management.yaml .

We are into more investigation of `cluster-external-management.yaml` currently need to check from you, 
That the [cluster-external.yaml](https://github.com/rook/rook/blob/master/deploy/examples/cluster-external.yaml) already makes the cephcluster spec to external, so there is an extra need to add `cluster-external-management.yaml ` ?

**Comment by jclab-joseph** [comment]
I referenced this link: https://documentation.suse.com/ses/7.1/html/ses-all/admin-caasp-crd.html

And I see below
> WARNING: If you plan to create CRs (pool, rgw, mds, nfs) in the external cluster, you MUST inject the client.admin keyring as well as injecting cluster-external-management.yaml

So, Instead of using create-external-cluster-resources.py , I imported the cluster information using ROOK_EXTERNAL_ADMIN_SECRET .
