### ISSUE TITLE
Deleting a bucket on object store is taking a long time via Rook API

### ISSUE THREAD

**Issue by dangula** [rook/rook#1068]
Calling the delete bucket API to delete is taking a long time. It is very noticeable when there is a large number of objects in the bucket.  The API deleting all the objects from the bucket before deleting the bucket. As a result, the bucket might be available for hours even after delete bucket API is called.   We need to look at ways to speed up delete bucket.

**Comment by travisn** [comment]
not sure we have control over this, but will take a look

**Comment by travisn** [comment]
need to check with the ceph team if there is any way we can accelerate the deletion of the bucket.

**Comment by kokhang** [comment]
Rook-api is being deprecated. I did try deleting a bucket with a few objects with 10G. It went pretty quick. But i did use an S3 client and not via the API.
