### ISSUE TITLE
only few pod when i apply cluster.yaml  the cluster installed by kind

### ISSUE THREAD

**Issue by bruse-peng** [rook/rook#10697]
when i kubectl apply -f cluster.yaml why only has a few pods not like the document list below:
kind v0.14.0 go1.18.2 linux/amd64
![image](https://user-images.githubusercontent.com/47881861/183877074-9e74f257-d17b-4a30-8547-d86ac0c23a89.png)

![image](https://user-images.githubusercontent.com/47881861/183877281-56acff28-da58-473b-9bc5-1c425767841c.png)

**Comment by zhucan** [comment]
Can you paste the logs of  operator? @bruse-peng

**Comment by bruse-peng** [comment]
> Can you paste the logs of operator? @bruse-peng 

我的问题需要等很久才会显示其他的pod，按照官方文档，不需要apply 几个yaml文件就行，不需要修改什么吧？除了cluster。yaml里面的dataDirHostPath 是吧？

**Comment by zhucan** [comment]
only need to exec "kubectl apply -f dcluster.yaml" if you want to use all devices on all nodes.

**Comment by bruse-peng** [comment]
when i edit service rook-ceph-mgr-dashboard  from ClsuterIP to NodePort,after few seconds it revovery  ClsuterIP again what is th reason
![image](https://user-images.githubusercontent.com/47881861/184119901-596bfd13-82bb-4a7b-baee-c2048c91a373.png)

**Comment by travisn** [comment]
@bruse-peng Rook reconciles these services to what it expects for access internal to the cluster. See [this topic](https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-dashboard/#viewing-the-dashboard-external-to-the-cluster) and create a new service for external access to the dashboard.

**Comment by bruse-peng** [comment]
> @bruse-peng Rook reconciles these services to what it expects for access internal to the cluster. See [this topic](https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-dashboard/#viewing-the-dashboard-external-to-the-cluster) and create a new service for external access to the dashboard.
question 1:
tell me why i can not change the service  cluster type ?

question 2:
if i want change the default images should i remove annotation below and change the image?

![image](https://user-images.githubusercontent.com/47881861/184269892-7d1283e8-71f2-4e7b-8762-14216cb3ef90.png)

question3:
 i am in china ,  many images are blocked by firewall  should you push the image into  alibaba image registry

**Comment by bruse-peng** [comment]
my kubernets cluster installed by kind  but when i install rook-ceph-mgr-dashboard-external-https  it can not access
![image](https://user-images.githubusercontent.com/47881861/184272469-cf7ebdb1-481b-4492-86ed-3e341bc93948.png)

![image](https://user-images.githubusercontent.com/47881861/184272483-501d047e-55c9-4d60-91bc-6b01ca698e84.png)
![image](https://user-images.githubusercontent.com/47881861/184272514-75462979-ed2c-4f6f-9ae0-75c105260541.png)

**Comment by zhucan** [comment]
> > @bruse-peng Rook reconciles these services to what it expects for access internal to the cluster. See [this topic](https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-dashboard/#viewing-the-dashboard-external-to-the-cluster) and create a new service for external access to the dashboard.
> > question 1:
> > tell me why i can not change the service  cluster type ?
> 
> question 2: if i want change the default images should i remove annotation below and change the image?
> 
> ![image](https://user-images.githubusercontent.com/47881861/184269892-7d1283e8-71f2-4e7b-8762-14216cb3ef90.png)
> 
> question3: i am in china , many images are blocked by firewall should you push the image into alibaba image registry
 You only need to push the image to the alibaba image registry.

**Comment by zhucan** [comment]
for question 2: you only neeed to push image to the alibaba image repo and  modifty the image repo in the yaml with the new repo.

**Comment by zhucan** [comment]
for question 3:  https://localip:30357

**Comment by bruse-peng** [comment]
in pod i can not access rook-ceph-mgr-dashboard below

![image](https://user-images.githubusercontent.com/47881861/184285793-e7abd224-b387-4017-817c-7c8f0daccbc3.png)

**Comment by travisn** [comment]
If you curl the IP do you get a response? 
```
curl -k https://10.96.246.14:8443
```
