### ISSUE TITLE
ci: use github Ubuntu 20.04 actions runner

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#10698]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Currently, we use the Ubuntu 18.04 actions runner. [This runner will be deprecated at the beginning of Dec](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/). So should change the runner to 20.04 (or [22.04](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/)?).

We once tried to move to 20.04. However, we hit #7327 and decided to stick with 18.04.

**Comment by galexrt** [comment]
I stumbled upon the github action we use for setting up minikube and found out that the action added support for Ubuntu 22.04 in the latest 2.7.0 release, see https://github.com/manusa/actions-setup-minikube/releases/tag/v2.7.0

Maybe updating to that version helps with the issue(s) we have (https://github.com/rook/rook/blob/master/.github/workflows/integration-test-config/action.yaml#L20).

**Comment by subhamkrai** [comment]
> I stumbled upon the github action we use for setting up minikube and found out that the action added support for Ubuntu 22.04 in the latest 2.7.0 release, see https://github.com/manusa/actions-setup-minikube/releases/tag/v2.7.0
> 
> Maybe updating to that version helps with the issue(s) we have (https://github.com/rook/rook/blob/master/.github/workflows/integration-test-config/action.yaml#L20).

I tried but that didn't work that's why I backed to using 20.04 but I'll be continuing looking to other options to fix the issue. Thanks
