### ISSUE TITLE
CephPoolGrowthWarning grouping

### ISSUE THREAD

**Issue by jdloft** [rook/rook#10691]
**Is this a bug report or feature request?**

* Bug Report

**Bug Report**

**Deviation from expected behavior:**

CephPoolGrowthWarning doesn't exclude instance and pod from grouping.

```
found duplicate series for the match group {pool_id="1"} on the left hand-side of the operation:
[{container="mgr", endpoint="http-metrics", instance="10.96.225.241:9283", job="rook-ceph-mgr", namespace="rook-ceph", pod="rook-ceph-mgr-b-d6c68d96c-8wbq5", pool_id="1", service="rook-ceph-mgr"},
{container="mgr", endpoint="http-metrics", instance="10.96.117.113:9283", job="rook-ceph-mgr", namespace="rook-ceph", pod="rook-ceph-mgr-b-7864dd989f-5lq27", pool_id="1", service="rook-ceph-mgr"}];
many-to-many matching not allowed: matching labels must be unique on one side
```

**How to reproduce it (minimal and precise):**
Restart any mgr pod.

#10070 reported that the `CephPoolGrowthWarning` rule was failing and it was removed with e45781d0d3a5adece2dcfb40a7e04bdf99a5c77a but was added back (unintentionally?) with dc53497d374ef2efd36a583b0ebe6eba22525e6c. Do we want to keep it? If so, we should exclude `instance` and `pod` from the groupright.

**Comment by jdloft** [comment]
Something like taking the max value would probably work since we don't expect the same mgr to be reporting metrics at the same time.
```
(predict_linear((max(ceph_pool_percent_used) without (pod, instance))[2d:1h], 3600 * 24 * 5) * on(pool_id) group_right() ceph_pool_metadata)
```

**Comment by travisn** [comment]
Yeah the rule was removed based on [this discussion](https://github.com/rook/rook/issues/10070#issuecomment-1099455108), and it does appear unintentional that it came back without being fixed. 

@jdloft Are you able to test that new condition on your cluster to see if it works as expected? I'm not sure on the details of the syntax.

**Comment by jdloft** [comment]
Yes, I currently have that syntax deployed and it is working. It essentially takes the max value for each hour in the 2d window and uses it to compute the predict_linear.
