### ISSUE TITLE
The controller continues to hold the expired certificate

### ISSUE THREAD

**Issue by superbrothers** [rook/rook#10719]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I faced the following error:

> CephBlockPool/rook-ceph/ceph-blockpool dry-run failed, reason: InternalError, error: Internal error occurred: failed calling webhook "cephblockpool-wh-rook-ceph-admission-controller-rook-ceph.rook.io": failed to call webhook: Post "https://rook-ceph-admission-controller.rook-ceph.svc:443/validate-ceph-rook-io-v1-cephblockpool?timeout=5s": x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "serial:336976302276413441245920813253687075705")

Helm chart now uses a certificate generated by cert-manager with the following PR, but that certificate has expired.

- https://github.com/rook/rook/pull/7325

The certificate was automatically renewed by cert-manager, but the controller did not have the ability to reload the renewed certificate (probably) and kept the old one, causing this problem.

https://github.com/rook/rook/blob/de448d31f9c3fb21420b783d4a2f9e788bfa83a9/pkg/operator/ceph/webhook.go#L47-L115

**Expected behavior:**

The certificate is reloaded.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.9.7
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): v1.24.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by subhamkrai** [comment]
@superbrothers for now you can disable the webhook until we fix his https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml#L412 here

**Comment by DjVinnii** [comment]
This problem also occurred to me today. A quick restart of the operator pod did the trick for me.

**Comment by subhamkrai** [comment]
> This problem also occurred to me today. A quick restart of the operator pod did the trick for me.

missed the track, will back to this. Good to hear it's working for you now

**Comment by subhamkrai** [comment]
@superbrothers @DjVinnii could you help to repro it, I failing to repro. I had my certificate reloaded and I didn't restart the rook operator pod but still everything is working

see my operator pod running time
```yaml
state:
      running:
        startedAt: "2022-12-13T13:03:23Z"
```
and operator logs when creating blockpool
```yaml
2022-12-13 14:13:38.914871 I | rook-ceph-webhook: validate create cephblockpool &{{CephBlockPool ceph.rook.io/v1} {replicapool  rook-ceph  0ef5a1e7-bef5-49df-a2e7-be86a481a6e3  1 2022-12-13 14:13:38 +0000 UTC <nil> <nil> map[] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"ceph.rook.io/v1","kind":"CephBlockPool","metadata":{"annotations":{},"name":"replicapool","namespace":"rook-ceph"},"spec":{"failureDomain":"osd","replicated":{"size":1}}}
] [] [] [{kubectl-client-side-apply Update ceph.rook.io/v1 2022-12-13 14:13:38 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{".":{},"f:failureDomain":{},"f:replicated":{".":{},"f:size":{}}}} }]} { {osd    {1 0 false 0  <nil>} {0 0 } map[] false {false  [] <nil>} {{false nil }} {<nil> <nil> <nil>}}} <nil>}
```
and my certificate see the revision
```yaml
status:
    conditions:
    - lastTransitionTime: "2022-12-13T13:03:24Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2022-12-13T14:57:24Z"
    notBefore: "2022-12-13T13:57:24Z"
    renewalTime: "2022-12-13T14:51:24Z"
    revision: 2
```

**Comment by superbrothers** [comment]
@subhamkrai 

You can repro with the following steps:

```
$ kind version
kind v0.17.0 go1.19.2 linux/amd64

$ kind create cluster

$ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

# Installing cert-manager
$ helm repo add jetstack https://charts.jetstack.io
$ helm repo update
$ helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true

# Installing rook-ceph which is patched "Changing webhook certificate duration to 1h" (default duration is 90 days)
# https://github.com/superbrothers/rook/commit/1f2fcb89d0f1e141d1fa0d7235ab7c4300a4e718
$ helm repo add rook-ceph https://charts.rook.io/release
$ helm repo update
$ helm install rook-ceph rook-ceph/rook-ceph --namespace rook-ceph --create-namespace --set image.repository=ghcr.io/superbrothers/rook/ceph --set image.tag=v1.10.5-1f2fcb89d

# You can see the status of the Certificate object held by the rook-ceph operator
$ k get -n rook-ceph certificate rook-admission-controller-cert -o yaml | grep statu
s: -A 20
status:
  conditions:
  - lastTransitionTime: "2022-12-18T01:54:58Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2022-12-18T02:54:58Z"
  notBefore: "2022-12-18T01:54:58Z"
  renewalTime: "2022-12-18T02:34:58Z"
  revision: 1

# You can see the status of the certificate held by rook-ceph-operator. It is the same with the Certificate object.
$ k exec -n rook-ceph deploy/rook-ceph-operator -- cat /etc/webhook/tls.crt | openssl x509 -text | grep Validity -A 2
        Validity
            Not Before: Dec 18 01:54:58 2022 GMT
            Not After : Dec 18 02:54:58 2022 GMT

# The server-side dry-run is succeeded
$ cat <<EOL >cephblockpool.yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
  deviceClass: hdd
EOL
$ k apply -f cephblockpool.yaml --dry-run=server
cephblockpool.ceph.rook.io/replicapool created (server dry run)
```

After a few hours...

```
# You can see the status of the Certificate object. It was renewd several times.
$ k get -n rook-ceph certificate rook-admission-controller-cert -o yaml | grep status: -A 20
status:
  conditions:
  - lastTransitionTime: "2022-12-18T01:54:58Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2022-12-18T07:34:58Z"
  notBefore: "2022-12-18T06:34:58Z"
  renewalTime: "2022-12-18T07:14:58Z"
  revision: 8
  
# But the certificate held by rook-ceph operator has not been renewed and the operator continues to hold the old one.
$ k exec -n rook-ceph deploy/rook-ceph-operator -- cat /etc/webhook/tls.crt | openssl x509 -text | grep Validity -A 2
        Validity
            Not Before: Dec 18 01:54:58 2022 GMT
            Not After : Dec 18 02:54:58 2022 GMT

# Therefore, the server-side dry-run isn't succeeded due to the certificate has expired.
$ k apply -f cephblockpool.yaml --dry-run=server
Error from server (InternalError): error when creating "cephblockpool.yaml": Internal error occurred: failed calling webhook "cephblockpool-wh-rook-ceph-admission-controller-rook-ceph.rook.io": failed to call webhook: Post "https://rook-ceph-admission-controller.rook-ceph.svc:443/validate-ceph-rook-io-v1-cephblockpool?timeout=5s": x509: certificate has expired or is not yet valid: current time 2022-12-18T06:38:31Z is after 2022-12-18T02:54:58Z
```

**Comment by sbidoul** [comment]
I faced a similar (certificate signed by unknown authority) issue today during a routine `helm upgrade` (without any change).

`Error: UPGRADE FAILED: cannot patch "rook-ceph" with kind CephCluster: Internal error occurred: failed calling webhook "cephcluster-wh-rook-ceph-admission-controller-rook-ceph.rook.io": failed to call webhook: Post "[https://rook-ceph-admission-controller.rook-ceph.svc:443/validate-ceph-rook-io-v1-cephcluster?timeout=5s](https://rook-ceph-admission-controller.rook-ceph.svc/validate-ceph-rook-io-v1-cephcluster?timeout=5s)": x509: certificate signed by unknown authority`

A restart of the operator resolved it.

**Comment by jhoblitt** [comment]
I have encountered this too with rook 1.9.9. Restarting the operator did not change the behavior.  Deleting the rook-ceph-webhook validatingwebhookconfigurations and restarting the operator seemed to resolve the error and allow the rook-ceph-cluster chart to be redeployed (but there was something else strange going on in that helm wasn't properly updating the rook-ceph cephcluster resource and it had to be manually patched).

**Comment by jhoblitt** [comment]
The TLS cert used by the operator does appear to have updated... probably when the webhook was recreated?

 ```bash
$ k get -n rook-ceph certificate rook-admission-controller-cert -o yaml | grep status: -A 20
status:
  conditions:
  - lastTransitionTime: "2022-08-25T19:35:44Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2023-03-23T19:35:44Z"
  notBefore: "2022-12-23T19:35:44Z"
  renewalTime: "2023-02-21T19:35:44Z"
  revision: 3
$ k exec -n rook-ceph deploy/rook-ceph-operator -- cat /etc/webhook/tls.crt | openssl x509 -text | grep Validity -A 2
        Validity
            Not Before: Dec 23 19:35:44 2022 GMT
            Not After : Mar 23 19:35:44 2023 GMT
```

**Comment by subhamkrai** [comment]
@jhoblitt @sbidoul @superbrothers @DjVinnii with the latest rook release v1.10.9 we have disabled the webhook by default until we fix the root cause. Hopefully, soon we'll fix the issue we're distracted with other priority things. Thanks

**Comment by toabi** [comment]
Just noticed this in a 1.9.12 install - I checked the secret and it contained a still valid certificate. Restarting the operator was the only thing necessary.
