### ISSUE TITLE
Automated OSD removal

### ISSUE THREAD

**Issue by jpds** [rook/rook#1071]
Rook requires an automated way to remove an OSD from the cluster. I have a phantom one in one of my clusters and I'm not sure where it came from.

Code from the standalone version of Rook can be used for this at: https://github.com/rook/rook/blob/6795f08990e197db7965cb8cdf2bb3c75422e8de/pkg/ceph/osd/agent.go#L238

**Comment by galexrt** [comment]
@jpds I also had a phantom OSD and you can try running the following commands (to temporarily fix it):
Replace `<ID>` with the OSD ID from the following command:
```
$ ceph osd tree
```
Run the commands even if one errors.
```
$ ceph osd out <ID>
$ ceph osd crush remove osd.<ID>
$ ceph auth del osd.<ID>
$ ceph osd rm <ID>
```
(Source: https://www.sebastien-han.fr/blog/2015/12/11/ceph-properly-remove-an-osd/)

These commands removed the OSD successfully from the osd tree map and "fixed" the cluster to go back into `HEALTH_OK` state again.

**Comment by travisn** [comment]
@galexrt @jpds any more steps for a repro? not sure how to detect when to automatically remove the osd. Shall we document the cleanup steps in the advanced configuration page?

**Comment by galexrt** [comment]
@travisn I'm not sure if we can safely automate this.
But yes we should definitely document these cleanup steps in case of a phantom OSD.
I could document it.

**Comment by galexrt** [comment]
I should be ready with a PR for documenting this and adding some documentation about `hostNetwork` by this evening.
