### ISSUE TITLE
The status of cephblockpoool is always "Progressing"?

### ISSUE THREAD

**Issue by zhucan** [rook/rook#10712]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The status of the cephblockpool is always "Progressing"

**Expected behavior:**
The status of the cephblockpool is active or failed.

**How to reproduce it (minimal and precise):**
1. create a empty crushroot
![image](https://user-images.githubusercontent.com/13997135/184274606-31405e82-d06c-4c21-a65e-b3e285199cdc.png)
2. create a cephblockpool use the empty curshroot
      apiVersion: ceph.rook.io/v1
      kind: CephBlockPool
      metadata:
        creationTimestamp: "2022-08-11T11:46:54Z"
        finalizers:
        - cephblockpool.ceph.rook.io
        generation: 2
        name: replicapool1
        namespace: rook-ceph
        resourceVersion: "1633985"
        uid: e8238c65-fc96-4534-b60c-f137cbe7d43e
      spec:
        **crushRoot: ssd**
        erasureCoded:
          codingChunks: 0
          dataChunks: 0
        failureDomain: host
        mirroring:
          mode: image
        parameters:
          compression_mode: none
        quotas: {}
        replicated:
          requireSafeReplicaSize: true
          size: 3
        statusCheck:
          mirror:
            interval: 1m0s
      status:
        phase: Progressing
3.  Check the cephblockpool's status
    ❯ kubectl get cephblockpool -n rook-ceph
    NAME           PHASE
    replicapool    Ready
    replicapool1   Progressing
    replicapool2   Ready 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.9.8
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.10
* Kubernetes version (use `kubectl version`): 1.22.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by zhucan** [comment]
Beacuse of the  invalid crushroot, hangs on "rbd pool init replicapool1 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring", there is no timeout config for this cmd:
https://github.com/rook/rook/blob/113970c4163fd3ff4dba18ee5271693fe16a016a/pkg/operator/ceph/pool/controller.go#L390

**Comment by travisn** [comment]
Right, we would need to use `RunWithTimeout()` since `rbd` doesn't have a built-in timeout parameter. Want to open a PR for that?

**Comment by zhucan** [comment]
Ok
