### ISSUE TITLE
Add cephfs-shell to the admin tool pod

### ISSUE THREAD

**Issue by ktarplee** [rook/rook#10731]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
For maintaining the ceph filesystem the command `cephfs-shell` is handy.  It is currently unavailable in the rook-ceph-tool pod.  It would be nice if this package could be added to that image.

https://docs.ceph.com/en/latest/man/8/cephfs-shell/

**What is use case behind this feature:**

It is convenient to be able to create and delete files and directories without having to mount the filesystem in a pod.  That is why the `cephfs-shell` command was created.

**Environment**:

**Comment by travisn** [comment]
The rook toolbox is based on the ceph image. Any desired tools would need to be added to the base ceph image with a request in the [ceph-container](https://github.com/ceph/ceph-container) repo.
