### ISSUE TITLE
Rook operator doesn't recreate third mon

### ISSUE THREAD

**Issue by jpds** [rook/rook#1073]
I upgraded my rook cluster from 1.7.5 to 1.8 with kubespray and as part of its upgrade process, it drains the nodes and cordons them before readding them to the cluster, post-upgrade.

This appears to have taken out my third rook mon, and the health checks from the operator expect and find the other two, but it isn't recreating the third monitor.

**Comment by travisn** [comment]
From the logs, we see that there are two healthy quorum members: mon3 and mon4:
```
{Quorum:[0 1] MonMap:{Mons:[{Name:rook-ceph-mon3 Rank:0 Address:10.233.28.73:6790/0} {Name:rook-ceph-mon4 Rank:1 Address:10.233.42.161:6790/0}]}}
```

But Rook thinks there are three mons: mon1, mon2, and mon3:
```
op-mon: Checking health for mons. &{FSID:881e92a6-637b-4b7c-a173-4347e9494a24 MonitorSecret:<secret> AdminSecret:<secret> Name:rook Monitors:map[rook-ceph-mon3:0xc4204d51e0 rook-ceph-mon1:0xc4204d5220 rook-ceph-mon2:0xc4204d5260]}
```
A couple of issues here:
- The configmap is missing mon4 and should not include mon1 or mon2. The operator needs to reconcile the configmap with the authoritative monmap.
- The operator is not adding a third monitor. The health check only loops over the mons in the mon map and won't notice if a mon is missing from the mon map.
https://github.com/rook/rook/blob/master/pkg/operator/mon/health.go#L79
