### ISSUE TITLE
CephNFS - allow setting hostNetwork: false

### ISSUE THREAD

**Issue by taxilian** [rook/rook#10749]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Allow you to set hostNetwork: false on the NFS Ganesha pods even if your cluster uses host networking.

My recommendation would be to put it on `spec.server.hostNetwork`.

**What is use case behind this feature:**

I want to be able to expose NFS shares from ceph but some of my nodes already have nfs shares on them -- this basically renders nfs unusable to me in my cluster because if the pod starts up on one of those nodes it will simply fail to work. I need to be able to have it come up without host network.

A similar feature was recently added for (I assume) the same reasons for the CephObjectStore resource

**Comment by taxilian** [comment]
This is really needed, please don't mark it as won'tfix!

**Comment by BlaineEXE** [comment]
Would it make more sense to allow a `port` configuration for the CephNFSes?

**Comment by taxilian** [comment]
I'm not sure what you mean by that; the issue is that if you use host networking for your ceph cluster (which is recommended in several places in the documentation) then it will use host networking for any NFS pods that are created.... but if you do that, then it tries to use the NFS ports on the host network as well. On my network that renders the NFS pod unusable because I have NFS shares on my nodes already that I use for other administration.

If it were just possible to set hostNetwork: false somewhere like you can with a RBG gateway pod then this wouldn't be an issue because I could just set up a loadbalancer for it and access it that way.

**Comment by taxilian** [comment]
If someone can point me in the right direction I'm willing to implement this -- it should be fairly straightforward for someone who knows the code since it's just a question of adding a check when creating the deployment

**Comment by taxilian** [comment]
Please don't close this, please fix it instead. I'd still like to use it.
