### ISSUE TITLE
Incomplete note about rbd mirroring

### ISSUE THREAD

**Issue by nirs** [rook/rook#10741]
RBD mirroring docs:
https://www.rook.io/docs/rook/v1.9/Storage-Configuration/Block-Storage-RBD/rbd-mirroring/#rbd-mirroring

Contains incomplete note:

    This document sheds light on rbd mirroring and how to set it up using rook.
    For steps on failover or failback scenarios

Looks like text was truncated by mistake.

**Comment by nirs** [comment]
Ping

**Comment by subhamkrai** [comment]
@gauravsitlani FYI this coming from https://github.com/rook/rook/pull/10265/files#diff-896a1fac51e7601b3adacb44cc5397056e4e00f64066c331243d1086f0d2ff64L30
