### ISSUE TITLE
Run a bot to automatically rebase before merge

### ISSUE THREAD

**Issue by travisn** [rook/rook#1075]
When multiple PRs need to be merged, there is a significant delay while each one must be rebased manually after the previous one is merged. Then the PR must wait for CI again. We need an automated approach for rebasing when we're ready for merge that does not have to wait on the manual rebase and CI. If there are merge conflicts, of course the merge would need to be manual.

Perhaps a bot such as https://github.com/chrisledet/rebasebot. Ideally the bot could also delay the master build while a batch of PRs are merged.

In the meantime, a workaround is to add `[skip ci]` to the first PR comment.

**Comment by kokhang** [comment]
I prefer to take it a step further. I would like the bot to rebase for me and run CI tests. And then if ci passes, it merges the PR with the latest rebase. It should only need user intervention if there is conflict during the rbase.

**Comment by travisn** [comment]
the urgency of this is less now that we have found the github option that does not require rebasing before merge to master

**Comment by travisn** [comment]
closing this for now. The behavior of not requiring a rebase as long as there are no merge conflicts seems exactly what we want, at least until we have much higher volume of merges.
