### ISSUE TITLE
Use direct reference to links in docs

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#10766]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I see some docs mentioning the link to the doc in a manner like 
https://github.com/rook/rook/blame/master/.github/ISSUE_TEMPLATE/bug_report.md#L39
`[Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox))`

We can use direct reference something like `/Documentation/Troubleshooting//ceph-toolbox/#interactive-toolbox` 

So the ask is if we should the direct links instead of indirect links.

@galexrt please share your thoughts.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment]
@galexrt also need to understand how we are handling the doc version for a specific rook doc releases.

**Comment by galexrt** [comment]
> @galexrt also need to understand how we are handling the doc version for a specific rook doc releases.

Are you talking about the aliases like `latest-release` and `latest`?

**Comment by parth-gr** [comment]
NO, how we segregate 1.9 and 1.8 etc

**Comment by parth-gr** [comment]
Closing as it is not a issue
