### ISSUE TITLE
The Func SetDefaultConfigs of mon looks like run more than once

### ISSUE THREAD

**Issue by zeaone** [rook/rook#10775]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
the func SetDefaultConfigs will run more than 1  time
**Expected behavior:**
the func SetDefaultConfigs should run 1 time
**How to reproduce it (minimal and precise):**

every time to create cluster will reproduce
the code was in this place [`pkg/operator/ceph/cluster/mon/mon.go`](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/mon/mon.go)  The specific location is in lines 252-255 of this file

**Comment by travisn** [comment]
@zeaone Why should this only run once? Rook is a desired state operator, which means every time it runs, it will ensure the desired state. Do you want to override the default settings in `SetDefaultConfigs()`?
