### ISSUE TITLE
How To Retrieve Ceph Pod Coredump?

### ISSUE THREAD

**Issue by drohnow** [rook/rook#10788]
We have an issue where the rgw-rook-ceph-store pod is continuously crashing and is impacting storage access for our application.

rook-ceph        rook-ceph-rgw-rook-ceph-store-a-7c8ddb9dcd-rxkl4          1/1     Running     866 (4d3h ago)    7d7h

The pod debug indicates that there is a segfault:

debug 2022-08-18T19:52:38.827+0000 7f7932d82280  0 deferred set uid:gid to 167:167 (ceph:ceph)
debug 2022-08-18T19:52:38.827+0000 7f7932d82280  0 ceph version 15.2.11 (e3523634d9c2227df9af89a4eac33d16738c49cb) octopus (stable), process radosgw, pid 1
debug 2022-08-18T19:52:38.827+0000 7f7932d82280  0 framework: beast
debug 2022-08-18T19:52:38.827+0000 7f7932d82280  0 framework conf key: port, val: 8080
debug 2022-08-18T19:52:38.827+0000 7f7932d82280  1 radosgw_Main not setting numa affinity
debug 2022-08-18T19:52:39.069+0000 7f7932d82280  0 framework: beast
debug 2022-08-18T19:52:39.069+0000 7f7932d82280  0 framework conf key: ssl_certificate, val: config://rgw/cert/$realm/$zone.crt
debug 2022-08-18T19:52:39.069+0000 7f7932d82280  0 framework conf key: ssl_private_key, val: config://rgw/cert/$realm/$zone.key
debug 2022-08-18T19:52:39.069+0000 7f7932d82280  0 starting handler: beast
debug 2022-08-18T19:52:39.072+0000 7f7932d82280  0 WARNING: cannot open socket for endpoint=[::]:8080, Address family not supported by protocol
debug 2022-08-18T19:52:39.074+0000 7f7932d82280  0 set uid:gid to 167:167 (ceph:ceph)
debug 2022-08-18T19:52:39.090+0000 7f7932d82280  1 mgrc service_daemon_register rgw.rook.ceph.store.a metadata {arch=x86_64,ceph_release=octopus,ceph_version=ceph version 15.2.11 (e3523634d9c2227df9af89a4eac33d16738c49cb) octopus (stable),ceph_version_short=15.2.11,container_hostname=rook-ceph-rgw-rook-ceph-store-a-7c8ddb9dcd-rxkl4,container_image=ceph/ceph:v15.2.11,cpu=Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz,distro=centos,distro_description=CentOS Linux 8,distro_version=8,frontend_config#0=beast port=8080,frontend_type#0=beast,hostname=btsttlvpcd306,kernel_description=#1 SMP Fri Sep 24 10:17:16 UTC 2021,kernel_version=3.10.0-1160.45.1.el7.x86_64,mem_swap_kb=0,mem_total_kb=8154912,num_handles=1,os=Linux,pid=1,pod_name=rook-ceph-rgw-rook-ceph-store-a-7c8ddb9dcd-rxkl4,pod_namespace=rook-ceph,zone_id=a7255025-ad98-4e20-a81e-71df4f745e7b,zone_name=rook-ceph-store,zonegroup_id=ace5ce93-3a48-4ecf-8c35-c75525b5b4c3,zonegroup_name=rook-ceph-store}
debug 2022-08-18T19:52:42.985+0000 7f78f23ae700  1 ====== starting new request req=0x7f7932d586b0 =====
debug 2022-08-18T19:52:42.992+0000 7f78f1bad700  1 ====== starting new request req=0x7f7932cd76b0 =====
debug 2022-08-18T19:52:43.023+0000 7f78e6b97700  1 ====== req done req=0x7f7932d586b0 op status=0 http_status=200 latency=0.038000246s ======
debug 2022-08-18T19:52:43.023+0000 7f78e6b97700  1 beast: 0x7f7932d586b0: ***HIDDEN*** - - [2022-08-18T19:52:43.023758+0000] "GET /docker-registry?max-keys=1&prefix= HTTP/1.1" 200 756 - "aws-sdk-go/1.15.11 (go1.11.2; linux; amd64)" -
debug 2022-08-18T19:52:43.027+0000 7f78df388700  1 ====== req done req=0x7f7932cd76b0 op status=0 http_status=200 latency=0.035000227s ======
debug 2022-08-18T19:52:43.027+0000 7f78df388700  1 beast: 0x7f7932cd76b0: ***HIDDEN*** - - [2022-08-18T19:52:43.027758+0000] "GET /docker-registry?max-keys=1&prefix= HTTP/1.1" 200 756 - "aws-sdk-go/1.15.11 (go1.11.2; linux; amd64)" -
debug 2022-08-18T19:52:45.910+0000 7f78d1b6d700  1 ====== starting new request req=0x7f7932c566b0 =====
debug 2022-08-18T19:52:45.915+0000 7f78d036a700  1 ====== req done req=0x7f7932c566b0 op status=-2 http_status=204 latency=0.005000032s ======
debug 2022-08-18T19:52:45.915+0000 7f78d036a700  1 beast: 0x7f7932c566b0: ***HIDDEN*** - - [2022-08-18T19:52:45.915777+0000] "DELETE /rook-ceph-bucket-checker-d330e0c4-309d-4b4c-ab0b-dfe0a9e957b3/rookHealthCheckTestObject HTTP/1.1" 204 0 - "aws-sdk-go/1.35.24 (go1.16.3; linux; amd64)" -
debug 2022-08-18T19:52:45.916+0000 7f78f3bb1700  1 ====== starting new request req=0x7f7932c566b0 =====
debug 2022-08-18T19:52:45.943+0000 7f78cbb61700  1 ====== req done req=0x7f7932c566b0 op status=0 http_status=200 latency=0.027000174s ======
debug 2022-08-18T19:52:45.943+0000 7f78cbb61700  1 beast: 0x7f7932c566b0: ***HIDDEN*** - - [2022-08-18T19:52:45.943777+0000] "PUT /rook-ceph-bucket-checker-d330e0c4-309d-4b4c-ab0b-dfe0a9e957b3 HTTP/1.1" 200 0 - "aws-sdk-go/1.35.24 (go1.16.3; linux; amd64)" - 
debug 2022-08-18T19:52:45.943+0000 7f78c935c700  1 ====== starting new request req=0x7f7932c566b0 =====
*** Caught signal (Segmentation fault) **
 in thread 7f78c6b57700 thread_name:radosgw
 ceph version 15.2.11 (e3523634d9c2227df9af89a4eac33d16738c49cb) octopus (stable)
 1: (()+0x12b20) [0x7f79273fbb20]
debug 2022-08-18T19:52:45.946+0000 7f78c6b57700 -1 *** Caught signal (Segmentation fault) **
 in thread 7f78c6b57700 thread_name:radosgw

 ceph version 15.2.11 (e3523634d9c2227df9af89a4eac33d16738c49cb) octopus (stable)
 1: (()+0x12b20) [0x7f79273fbb20]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

What is the best way to retrieve a coredump from this pod so we can diagnose the segfault?

**Comment by drohnow** [comment]
Just checking in on this one.  Any recommendation here?

**Comment by drohnow** [comment]
Hi @subhamkrai!  For sure! Here you go:  


[rook-ceph-operator-5557df7466-62tqm-previous.log](https://github.com/rook/rook/files/9446787/rook-ceph-operator-5557df7466-62tqm-previous.log)
[rook-ceph-operator-5557df7466-62tqm.log](https://github.com/rook/rook/files/9446789/rook-ceph-operator-5557df7466-62tqm.log)

**Comment by travisn** [comment]
@drohnow Rook has a crash collector daemon that watches for the dumps and reports them to ceph, so they can be viewed from the toolbox. Do [these commands](https://docs.ceph.com/en/latest/mgr/crash/) in the toolbox help?

**Comment by drohnow** [comment]
Specifically this is the 

> 

Oh super!  Thanks @travisn.  We will give it a go and get back to y'all.

**Comment by drohnow** [comment]
@travisn We executed the directions to configure the crash module but received the error below when attempting to fetch the key:

kubectl exec -it deployment/rook-ceph-tools -n rook-ceph -- ceph auth get-or-create client.crash mon 'profile crash' mgr 'profile crash'
**Error EINVAL: key for client.crash exists but cap mgr does not match**

What would be the course of action to recover from this error?

**Comment by travisn** [comment]
Do you see a crash collector pod already running? It should have collected the crashes for you and reported them to ceph. From the toolbox, do other commands such as `ceph crash ls` show info about crashes?

**Comment by drohnow** [comment]
@travisn I can see information about crashes: here is command and associated output.

kubectl exec -it deployment/rook-ceph-tools -n rook-ceph -- ceph crash ls-new

2022-08-30T14:58:21.814136Z_a6cf2c04-7018-4f74-9989-e2bf1cc1a83b  client.rgw.rook.ceph.store.a   *
2022-08-30T15:03:40.365653Z_6cf97f14-2995-4182-a451-72f4eb4af359  client.rgw.rook.ceph.store.a   *
2022-08-30T15:08:56.176513Z_24c81c1c-79d5-4852-b5cd-4751e219eeb6  client.rgw.rook.ceph.store.a   *
2022-08-30T15:14:31.977920Z_5187fa6c-aa6d-42f1-9f94-f18be7f99e2f  client.rgw.rook.ceph.store.a   *
2022-08-30T15:19:50.921948Z_4c53b153-0a6d-410d-b157-a4cacdf3ed7e  client.rgw.rook.ceph.store.a   *
2022-08-30T15:25:11.625857Z_6c685943-53e2-4e7d-be4c-54a9dcdbffea  client.rgw.rook.ceph.store.a   *
2022-08-30T15:30:22.670320Z_43b91f67-e338-4e11-a913-0850ad964524  client.rgw.rook.ceph.store.a   *
2022-08-30T15:36:05.798419Z_2a97fccb-701c-4b11-8725-a48bfab1fb98  client.rgw.rook.ceph.store.a   *
2022-08-30T15:41:25.973359Z_b8592eb9-b9b7-47d3-8900-76036b6ee5c3  client.rgw.rook.ceph.store.a   *
2022-08-30T15:46:46.827022Z_8550d58f-a2ff-4abb-96e9-59bf40292ce1  client.rgw.rook.ceph.store.a   *
2022-08-30T15:52:06.868853Z_cb240d8b-7429-4a45-87f8-8b9ef4855d97  client.rgw.rook.ceph.store.a   *
2022-08-30T15:57:28.806244Z_a567df45-b9f3-4cce-bb23-185b84f50fb5  client.rgw.rook.ceph.store.a   *
2022-08-30T16:02:49.980521Z_2d6ca24d-c043-4bcd-8107-a785e81ff8a1  client.rgw.rook.ceph.store.a   *
2022-08-30T16:08:10.598087Z_cb5f4647-f6ec-4f1e-a227-29892569d4c2  client.rgw.rook.ceph.store.a   *
2022-08-30T16:13:30.293324Z_1fa2d670-f86e-41ab-b19e-498f0fbd931e  client.rgw.rook.ceph.store.a   *
2022-08-30T16:18:49.321566Z_d6ff9fa2-3245-41ab-9070-b14004b9a1b6  client.rgw.rook.ceph.store.a   *
2022-08-30T16:24:22.887566Z_961a1493-9c91-4921-a0cb-6b943b3fe20b  client.rgw.rook.ceph.store.a   *
2022-08-30T16:29:42.014789Z_0bf7923c-d9f6-4953-bac5-6ebedb381938  client.rgw.rook.ceph.store.a   *
2022-08-30T16:35:02.384158Z_c9b646a8-45cd-4d8f-9f40-b7814716a902  client.rgw.rook.ceph.store.a   *
2022-08-30T16:40:16.146312Z_daf4ec2c-c5b5-4ccc-b813-55c5a2c7067e  client.rgw.rook.ceph.store.a   *
2022-08-30T16:45:54.334475Z_0f8ddb4b-7989-4d44-802c-778b5768f12d  client.rgw.rook.ceph.store.a   *
2022-08-30T16:51:00.719910Z_2bdf041d-7fe4-4e78-8bec-3a94a4fd825e  client.rgw.rook.ceph.store.a   *
2022-08-30T16:56:46.707296Z_525f1834-71e9-497a-a144-673cd631eb15  client.rgw.rook.ceph.store.a   *
2022-08-30T17:03:13.330809Z_859db4bb-7ba0-4852-a016-80e964bdc2e8  client.rgw.rook.ceph.store.a   *
2022-08-30T17:08:35.304162Z_f0527cd0-2d62-48d5-b611-845a8cf19184  client.rgw.rook.ceph.store.a   *
2022-08-30T17:13:54.367023Z_e6a1afd6-1b84-4345-b683-a3b89d602c82  client.rgw.rook.ceph.store.a   *
2022-08-30T17:19:13.053681Z_5e77caea-f9a9-48ba-8d37-2a86b4e6731b  client.rgw.rook.ceph.store.a   *

**Comment by travisn** [comment]
Ok great, so that answers your question? You can also get details about each crash with `ceph crash info <crashid>`.

**Comment by drohnow** [comment]
Ok, got it.  Here is the crash info (below).  I expected to see information that would allow us to understand the issue; however, I don't see any info that is an indicator of the issue or is actionable.  Any recommendations here?

kubectl exec -it deployment/rook-ceph-tools -n rook-ceph -- ceph crash info 2022-08-30T14:58:21.814136Z_a6cf2c04-7018-4f74-9989-e2bf1cc1a83b


{
    "backtrace": [
        "(()+0x12b20) [0x7f8b36d0eb20]"
    ],
    "ceph_version": "15.2.11",
    "crash_id": "2022-08-30T14:58:21.814136Z_a6cf2c04-7018-4f74-9989-e2bf1cc1a83b",
    "entity_name": "client.rgw.rook.ceph.store.a",
    "os_id": "centos",
    "os_name": "CentOS Linux",
    "os_version": "8",
    "os_version_id": "8",
    "process_name": "radosgw",
    "stack_sig": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
    "timestamp": "2022-08-30T14:58:21.814136Z",
    "utsname_hostname": "rook-ceph-rgw-rook-ceph-store-a-7c8ddb9dcd-rxkl4",
    "utsname_machine": "x86_64",
    "utsname_release": "3.10.0-1160.45.1.el7.x86_64",
    "utsname_sysname": "Linux",
    "utsname_version": "[#1](https://puppetlabs.zendesk.com/agent/tickets/1) SMP Fri Sep 24 10:17:16 UTC 2021"
}

**Comment by travisn** [comment]
hmm, the backtrace is certainly not helpful. All of the traces are this unhelpful?

**Comment by drohnow** [comment]
Yes, unfortunately.  Any other recourse or recommendation on how to 1) remediate the crash and/or 2) understand root cause

**Comment by drohnow** [comment]
@travisn Just checking in hear as we continue to see the seg fault but the crash dumps are not revealing anything meaningful.

Here is the latest error message from the rgw pod logs:
grep -irn seg rook-ceph-rgw-rook-ceph-store-a-5dd9d75d8f-tgmmt
rook-ceph-rgw-rook-ceph-store-a-5dd9d75d8f-tgmmt/rgw.log:35:*** Caught signal (Segmentation fault) **
rook-ceph-rgw-rook-ceph-store-a-5dd9d75d8f-tgmmt/rgw.log:39:debug 2022-09-01T18:36:31.745+0000 7f81ad60b700 -1 *** Caught signal (Segmentation fault) **
rook-ceph-rgw-rook-ceph-store-a-5dd9d75d8f-tgmmt/rgw.log:1209:debug      0> 2022-09-01T18:36:31.745+0000 7f81ad60b700 -1 *** Caught signal (Segmentation fault) **
rook-ceph-rgw-rook-ceph-store-a-5dd9d75d8f-tgmmt/rgw.log:2490:debug      0> 2022-09-01T18:36:31.745+0000 7f81ad60b700 -1 *** Caught signal (Segmentation fault) **
rook-ceph-rgw-rook-ceph-store-a-5dd9d75d8f-tgmmt/rgw-previous.log:35:*** Caught signal (Segmentation fault) **
rook-ceph-rgw-rook-ceph-store-a-5dd9d75d8f-tgmmt/rgw-previous.log:39:debug 2022-09-01T18:36:31.745+0000 7f81ad60b700 -1 *** Caught signal (Segmentation fault) **
rook-ceph-rgw-rook-ceph-store-a-5dd9d75d8f-tgmmt/rgw-previous.log:1209:debug      0> 2022-09-01T18:36:31.745+0000 7f81ad60b700 -1 *** Caught signal (Segmentation fault) **
rook-ceph-rgw-rook-ceph-store-a-5dd9d75d8f-tgmmt/rgw-previous.log:2490:debug      0> 2022-09-01T18:36:31.745+0000 7f81ad60b700 -1 *** Caught signal (Segmentation fault) **

What is the next course of action to recover from this issue?  The fact that rgw is offline is causing an application to be down as well.

**Comment by drohnow** [comment]
@travisn I am re-reading the crash module documentation; my understanding is that the crash info command (ceph crash info <crashid>) only provides the summary of the crash. How do we get to the meta file to see the contents of the crash dump?  (doc says run this command:  ceph crash post -i <metafile>). 

However we received an error when we ran this command (see above as well): 

kubectl exec -it deployment/rook-ceph-tools -n rook-ceph -- ceph auth get-or-create client.crash mon 'profile crash' mgr 'profile crash'
Error EINVAL: key for client.crash exists but cap mgr does not match.

How can we retrieve the contents of the crash dumps?

**Comment by drohnow** [comment]
@travisn Just checking for an update.  Thx.

**Comment by diamonwiggins** [comment]
Hello 👋 . I'm working with @drohnow on this issue and just an FYI that our customer in this case is considering reinstalling. If we can't get the next steps for gathering the core dump or any diagnostic information before then, we'd still be interested in knowing so we can update our docs in case something like this happens again.

**Comment by gauravsitlani** [comment]
Hi @diamonwiggins i can share the steps for gathering coredump

**Comment by gauravsitlani** [comment]
@diamonwiggins is the process continuously segfaulting or you're trying to collect it on a live running process ?

**Comment by thotz** [comment]
Is there any anyway to core file @travisn , at least I can with RGW devs, the log says the PUT operation on the bucket ended up segfaulting, can you increase log level of RGW pod from toolbox pod and collect the logs again

**Comment by leseb** [comment]
Has anyone looked into `/var/lib/systemd/coredump` on the host machine were the rgw is crashing?

**Comment by gauravsitlani** [comment]
@leseb I looked into `/var/lib/systemd/coredump` directory on the host with the default core_pattern i.e. : `|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e` during my testing but the coredump file wasn't present.

**Comment by leseb** [comment]
> @leseb I looked into `/var/lib/systemd/coredump` directory on the host with the default core_pattern i.e. : `|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e` during my testing but the coredump file wasn't present.
> 
> For my testing, I tried killing the RGW process on both the host and inside the pod as well with : `kill -6 <pid>` and `kill -11 <pid>` signals. But the coredump wasn't present.

Can you enable the logCollector and try again?  I think we either need `ShareProcessNamespace` or `HostPID` for this to work correctly.

**Comment by gauravsitlani** [comment]
Hi @leseb after enabling `logCollector` when i killed the RGW process with `kill -6 <pid>` and `kill -11 <pid>` signals, I noticed the coredump files in that directory : 
```
[root@centos-4gb-hel1-2 ~]# ls -lhsa /var/lib/systemd/coredump
total 20M
4.0K drwxr-xr-x. 2 root root 4.0K Oct 17 12:48 .
4.0K drwxr-xr-x. 5 root root 4.0K Aug  4 17:27 ..
 11M -rw-r-----. 1 root root  11M Oct 17 12:46 core.radosgw.167.07252b56047f4152a3254ca840eb312e.1297423.1666010765000000.lz4
 10M -rw-r-----. 1 root root  10M Oct 17 12:48 core.radosgw.167.07252b56047f4152a3254ca840eb312e.1299581.1666010894000000.lz4
``` 

This essentially means that we need to have logCollector enabled regarding the same. I can test and try for the other daemons and we can update that in the docs.

**Comment by travisn** [comment]
I wonder if we should always enable the needed property so the core dumps would be enabled by default. But at the same time, `ShareProcessNamespace` and `HostPID` are significant privileges to have enabled by default, so maybe we should just document to enable the log collector since that gives the privileges.
