### ISSUE TITLE
PodSecurityPolicy has been deprecated but is still used in the example and prevents install on K8s 1.25

### ISSUE THREAD

**Issue by akessner** [rook/rook#10792]
**Is this a bug report or feature request?**

* Bug Report

**Bug Report**

**Expected behavior:**

No warnings when installing the examples.

**Deviation from expected behavior:**

This line of the common config in the examples is throwing an error:
https://github.com/rook/rook/blob/386117de4be610fb3af4d3f7016c0ae213cd42d2/deploy/examples/common.yaml#L755

'Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+'

**How to reproduce it (minimal and precise):**

Create a new cluster version 1.21+
Install the example
See the warning.
If you create a new cluster with v1.25, the example config will break.

**Comment by jinjimosd** [comment]
I just created a new k8s cluster, deployed rook-ceph and found out it's not compatible with v1.25. I am waiting for the next update from rook-ceph.

**Comment by Madhu-1** [comment]
@travisn this need to be considered for the next rook release

**Comment by travisn** [comment]
We will need to break out the PSP to a separate yaml for those users still requiring it on older clusters, but avoid breaking 1.25 deployments. @BlaineEXE could you take a look?

**Comment by BlaineEXE** [comment]
Yeah. Let's split out the psp to a new yaml for 1.10.

**Comment by travisn** [comment]
Reopening to get the psp removed from common.yaml.

**Comment by travisn** [comment]
Fixed now with #10816, to be backported to v1.9.10
