### ISSUE TITLE
Failed to create CephObjectStore, object store deployments, pools, crush rules

### ISSUE THREAD

**Issue by hohoqq** [rook/rook#10805]
**Is this a bug report or feature request?**
* Bug Report

**Expected behavior:**

We can create thousands of CephObjectStore.

**How to reproduce it (minimal and precise):**

1. Deploy Rook operator with [Helm chart](https://github.com/rook/rook/tree/master/deploy/charts/rook-ceph) v.1.9.9
2. Deploy Ceph cluster with [Helm chart](https://github.com/rook/rook/tree/master/deploy/charts/rook-ceph-cluster)  v.1.9.9
3. Create 50 CephObjectStore instances. 
4. Creation of 43+ instance fail.

**Logs to submit**:

* Operator's logs, if necessary

`E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/ceph-objectstore-46". failed to create object store deployments: failed to create object pools: failed to create metadata pools: failed to create pool "ceph-objectstore-46.rgw.control": failed to create replicated crush rule "ceph-objectstore-46.rgw.control": failed to create crush rule ceph-objectstore-46.rgw.control: exit status 28`

Experimentally, we managed to find out that CRUSH rule 257+ cannot be created. Pools and profiles in the amount of 257+ are created normally.

```
# ceph osd crush rule create-erasure test-10 test-10.data_ecprofile
Error ENOSPC: failed to add rule 256 because (28) No space left on device
```

```
ceph osd crush rule create-replicated test-10 default host
Error ENOSPC: failed to add rule 256 because (28) No space left on device
```

**Cluster Status to submit**:

```
$ ceph -s
  cluster:
    id:     33b3053d-5921-4720-8155-8e55879ed82f
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 52m)
    mgr: b(active, since 43m)
    mds: 1/1 daemons up, 1 hot standby
    osd: 16 osds: 16 up (since 44m), 16 in (since 44m)
    rgw: 41 daemons active (4 hosts, 41 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   256 pools, 3121 pgs
    objects: 13.48k objects, 1.1 MiB
    usage:   3.4 GiB used, 1.6 TiB / 1.6 TiB avail
    pgs:     3121 active+clean
 
  io:
    client:   60 KiB/s rd, 3.1 KiB/s wr, 71 op/s rd, 32 op/s wr
```

**Environment**:
* OS (e.g. from /etc/os-release): Oracle Linux Server 8.6
* Kernel (e.g. `uname -a`): 5.4.17-2136.308.9.el8uek.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.9.9
go: go1.17.12
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.10 
* Kubernetes version (use `kubectl version`): v1.22.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Installed on virtal machines with Kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
HEALTH_WARN 1 pools have many more objects per pg than average

**Comment by hohoqq** [comment]
Redepoyed cluster with ceph version 16.2.10. Problem still exists.

Is it possible to remove this restriction (256+ crush rules)? Or set to use one CRUSH rule and profile for all pools?

**Comment by travisn** [comment]
Ceph must have that limit because it's really not designed to run with hundreds of pools and so many PGs. Are you creating so many object stores because you need multitenancy? If so, I'd suggest breaking it down into smaller rook clusters and have multiple rook clusters per K8s cluster.

**Comment by vumrao** [comment]
Also if the use case is to have multiple ObjectStore daemons (RGWs) to provide more client connections and more parallel work behind LB that is fully supported in standalone Ceph I am not sure if the rook is capable enough to have different objectstorage(RGW) pods using same rgw_realm, zongroup, zones!

**Comment by vumrao** [comment]
> Also if the use case is to have multiple ObjectStore daemons (RGWs) to provide more client connections and more parallel work behind LB that is fully supported in standalone Ceph I am not sure if the rook is capable enough to have different objectstorage(RGW) pods using same rgw_realm, zongroup, zones!

Just like multiple MGR, MON, OSD, and MDS daemons!

**Comment by travisn** [comment]
> > Also if the use case is to have multiple ObjectStore daemons (RGWs) to provide more client connections and more parallel work behind LB that is fully supported in standalone Ceph I am not sure if the rook is capable enough to have different objectstorage(RGW) pods using same rgw_realm, zongroup, zones!
> 
> Just like multiple MGR, MON, OSD, and MDS daemons!

Rook does allow creating multiple object stores, which will create separate pools and rgw pods for each store. Each object store will have separate realms, zone groups, and zones.

**Comment by vumrao** [comment]
> > > Also if the use case is to have multiple ObjectStore daemons (RGWs) to provide more client connections and more parallel work behind LB that is fully supported in standalone Ceph I am not sure if the rook is capable enough to have different objectstorage(RGW) pods using same rgw_realm, zongroup, zones!
> > 
> > 
> > Just like multiple MGR, MON, OSD, and MDS daemons!
> 
> Rook does allow creating multiple object stores, which will create separate pools and rgw pods for each store. Each object store will have separate realms, zone groups, and zones.

Okay, I think then we should open a feature request where if admin/user wants they can have multiple endpoints(RGW PODs) within single realm, zonegroup and zone! FYI @thotz !

**Comment by hohoqq** [comment]
Thank you for your answers!

> Are you creating so many object stores because you need multitenancy? If so, I'd suggest breaking it down into smaller rook clusters and have multiple rook clusters per K8s cluster.

Yes, we need multitenancy. 

According to my calculations, the minimum starting config of each Rook cluster (the sum of the requests of the required pods) is 30 CPU, 80 GB RAM. Recommended (sum of the limits) - 62 CPU, 100 GB RAM. It is very wasteful to maintain such a backend for every 40 object stores.

> Okay, I think then we should open a feature request where if admin/user wants they can have multiple endpoints(RGW PODs) within single realm, zonegroup and zone! FYI @thotz !

If multiple object stores within single realm, zonegroup and zone solve the problem, that would be great! 

Perhaps there is another option to provide multitenancy? For example, isolating the buckets of different users of the same object store in some way?

**Comment by hohoqq** [comment]
Perhaps we can move the already created object stores in one realm, zonegroup and zone, crush rule and delete the other ones?

**Comment by vumrao** [comment]
> Perhaps we can move the already created object stores in one realm, zonegroup, zone and crush rule and delete the other ones?

if possible you could do that!

Also, @hohoqq I have done some testing and I think you can use the `instances` field in objectCRD. https://rook.io/docs/rook/v1.10/CRDs/Object-Storage/ceph-object-store-crd/#example

`The number of pods in the rgw deployment`
    `instances: 1`

If you have different nodes to deploy RGW you can easily deploy the number of instances in the same objectstore - realm,zonegroup, and zone!

The only problem I see right now that you can not have multiple instances in the same node because the port coniguration does not take multiple values and maybe more coding in the backend to have multiple instances to be run on the same node.
But from my testing, it looks like you want to use the `instances` field to have more RGWs in the same realm, zonegroup, and zone!

HTH!

**Comment by vumrao** [comment]
@thotz WDYT - is it possible to add such config to have multiple instances of RGWs possible in one node? just like what we have in standalone ceph?

**Comment by thotz** [comment]
@vumrao there are two ways to increase RGW instances in Rook,
1.) as you increase the instance count in the cephobjectstore, it will increase the RGW pod and services. If you use Pod affinity then rgws servers will be running in different servers. I am not quite sure how we can n servers in a node. The drawback of the this method, all the rgw servers will be unique. For example the port issue which u mentioned, or it need to use same SSL certs etc
2.) with help of multisite configurations: Create a realm CR, zonegroup CR and zone CR. Now you can create n objectstore referring to that zone. Here each servers will leave independent configs, but this adds the complexity of multisite into the cluster.

**Comment by travisn** [comment]
Multiple rgw pods can run on a node, it's not a problem unless host networking is configured. Each object store could configure where its rgw pods run with the [placement](https://github.com/rook/rook/blob/release-1.10/deploy/examples/object.yaml#L58-L81), but does the placement really matter? 

@thotz A couple questions:
1. Are you saying multiple object stores could share the same pools? Or that is just a feature request that's not implemented yet?
2. Multisite seems like an independent question. The scenario is just about many small isolated object stores, right?

**Comment by thotz** [comment]
> Multiple rgw pods can run on a node, it's not a problem unless host networking is configured. Each object store could configure where its rgw pods run with the [placement](https://github.com/rook/rook/blob/release-1.10/deploy/examples/object.yaml#L58-L81), but does the placement really matter?
> 
> @thotz A couple questions:
> 
>     1. Are you saying multiple object stores could share the same pools? Or that is just a feature request that's not implemented yet?

Yes, if multisite is configured, then pools are linked with Zone, not stores It is not a feature request already implemented with mutlisite. Otherwise we can have multiple instance of RGW with single object store CR. But the downside is all the object stores will same set of configurations. 

> 
>     2. Multisite seems like an independent question. The scenario is just about many small isolated object stores, right?

**Comment by hohoqq** [comment]
Thank you for your answers! 

@thotz Multiple CephObjectStores really works in one Zone! I created 150 of them without problems. And now the question - is it possible to somehow isolate them from each other? 

Now, if I created a bucket "test" in one CephObjectStore, I can no longer create a bucket with the same name "test" in another - 409 BucketAlreadyExists.

Another problem is security - if I set Full control permissions for bucket for AWS users in one CephObjectStore, I can manage this bucket from another CephObjectStore:

![image](https://user-images.githubusercontent.com/64099513/191226900-7e3ff97d-c3a3-45bb-be26-1663285d7f1c.png)

If I start creating new Zone for each CephObjectStore for obtaining a separate Pool, then the restriction on the number of Crush rules will appear again.

> Otherwise we can have multiple instance of RGW with single object store CR

instances: n in object store CR will create some RGW pods. But the service will be one for them, as well as the storage (CephObjectStore) itself and data in it. Or did I understand something incorrectly?

**Comment by hohoqq** [comment]
Maybe we can somehow create different Pools using one Crush rule?

**Comment by travisn** [comment]
> Maybe we can somehow create different Pools using one Crush rule?

Even if different pools are created with the same Crush rule, Ceph will quickly hit other limits, such as number of PGs per OSD. 

Sharing a zone for multiple objects stores doesn't give good security separation as you already pointed out. 

@hohoqq Would [OBCs](https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/) give you sufficient multi-tenancy for a single object store? Each bucket claim would result in a bucket that only that client has access to.

**Comment by hohoqq** [comment]
@travisn Thank you for this proposal. 

Is it impossible to create a bucket claim with the help of S3 API? Our goal is to create many independent repositories controlled via S3 API.

Concerning other limits, except Crush rules. I could not find an information of such restrictions in Ceph. Limiting the number of PGs per OSD can be disabled. And in the [Ceph documentation there are arguments about how 50,000 groups will work](https://docs.ceph.com/en/latest/rados/operations/placement-groups/#choosing-the-number-of-placement-groups). It seems to me that it would be a good idea at least to try to follow the path of creating different pools with the same Crush rule and test it.

**Comment by travisn** [comment]
> Is it impossible to create a bucket claim with the help of S3 API? Our goal is to create many independent repositories controlled via S3 API.

Are you saying you want to create a bucket claim with the S3 API instead of with the OBC CRD? The S3 API doesn't know about K8s, so maybe I misunderstood the question.

**Comment by hohoqq** [comment]
@travisn Without the ability to create buckets through S3 API, the result is no longer a full-featured S3-compatible storage.

For now I see the only way to provide full S3 functionality, isolation with multiple S3 storages is to create different Pools using one Crush rule. Is it possible to test this option?

**Comment by travisn** [comment]
Buckets can be created already today with the full S3 API, that will work fine. But whoever has those s3 creds to create buckets is an admin, so if you want to have isolated admins, then correct, you would need separate object stores each with their own pools. 

Perhaps in the pool spec we could add a property `existingCrushRuleName` that would be used for the pool instead of always using the rule name that matches the pool name. For rook to configure, it would require a code change. But first I'd suggest you prototype the approach so you can verify that the pools will still scale. I believe you'll hit other limits very quickly when you have so many pools. Although to create a prototype, I don't see how you can do it without changing rook code to skip creating the crush rule and use a different crush rule name. See the [createReplicatedPoolForApp() function](https://github.com/rook/rook/blob/de448d31f9c3fb21420b783d4a2f9e788bfa83a9/pkg/daemon/ceph/client/pool.go#L416-L443).

**Comment by hohoqq** [comment]
> But first I'd suggest you prototype the approach so you can verify that the pools will still scale. I believe you'll hit other limits very quickly when you have so many pools. Although to create a prototype, I don't see how you can do it without changing rook code to skip creating the crush rule and use a different crush rule name. See the [createReplicatedPoolForApp() function](https://github.com/rook/rook/blob/de448d31f9c3fb21420b783d4a2f9e788bfa83a9/pkg/daemon/ceph/client/pool.go#L416-L443).

Thank you for this suggestion. If I understand correctly, I can just hardcode `crushRuleName = "CrushRule"` in the code for testing purposes. But I don't know how to apply this part of the code to a cluster deployed through a helm chart. Please clarify this moment.

**Comment by travisn** [comment]
> > But first I'd suggest you prototype the approach so you can verify that the pools will still scale. I believe you'll hit other limits very quickly when you have so many pools. Although to create a prototype, I don't see how you can do it without changing rook code to skip creating the crush rule and use a different crush rule name. See the [createReplicatedPoolForApp() function](https://github.com/rook/rook/blob/de448d31f9c3fb21420b783d4a2f9e788bfa83a9/pkg/daemon/ceph/client/pool.go#L416-L443).
> 
> Thank you for this suggestion. If I understand correctly, I can just hardcode `crushRuleName = "CrushRule"` in the code for testing purposes. But I don't know how to apply this part of the code to a cluster deployed through a helm chart. Please clarify this moment.

You'll need to build a new rook operator image (see the [development guide](https://rook.io/docs/rook/latest/Contributing/development-flow/)), push it to a repository where your cluster has access, then set your image in the values.yaml to apply with the helm chart.

**Comment by hohoqq** [comment]
@travisn 
> But first I'd suggest you prototype the approach so you can verify that the pools will still scale. I believe you'll hit other limits very quickly when you have so many pools.

Created 252 isolated RGWs with 1764 pools, 20273 pgs. 

![ceph-252-rgw](https://user-images.githubusercontent.com/64099513/205916850-7890a1a5-09fc-4b71-9e71-f926304809aa.JPG)

Faced a limit on the number of CRUSH rules. For each erasure code pool Rook still creates a new CRUSH rule.

![image](https://user-images.githubusercontent.com/64099513/205918191-9e91f0c5-47df-4dbb-a1d5-f26501196c66.png)

Is this installation enough to test the workability of the hypothesis? Is it possible to add the ability to use one CRUSH rule for many pools, both replicated and erasure code?

**Comment by travisn** [comment]
@hohoqq Wow that's a lot of object stores you were able to get running in the same cluster! Sounds good to go ahead with a change for allowing the same crush rule to be used on the pools. Are you interested in opening a PR for this? It may just move faster than waiting to see who else can pick it up. 

@cbodley @mkogan1 @mattbenjamin Any alternatives to consider when running so many object stores in the same cluster? For example, is it possible to use pool namespaces instead of so many individual metadata pools?

**Comment by cbodley** [comment]
yes @travisn, rgw supports namespacing for all of its pool names using the `:` separator, so you certainly could share pools to scale up the number of objectstores

https://docs.ceph.com/en/quincy/radosgw/pools/#pool-namespaces

**Comment by travisn** [comment]
> yes @travisn, rgw supports namespacing for all of its pool names using the `:` separator, so you certainly could share pools to scale up the number of objectstores
> 
> https://docs.ceph.com/en/quincy/radosgw/pools/#pool-namespaces

Does this mean Rook could choose to create a single pool instead of creating all these separate pools? 
```
my-store.rgw.meta
my-store.rgw.log
my-store.rgw.otp
my-store.rgw.buckets.index
my-store.rgw.control
```
In a test cluster I see the output of `radosgw-admin zone get` with various namespaces, but reading the topic I don't see if it's possible to consolidate all these pools.

**Comment by cbodley** [comment]
> Does this mean Rook could choose to create a single pool instead of creating all these separate pools?

within a zone, rgw has different requirements for the different pools. for example, some pools like .rgw.buckets.data can be erasure-coded, but others cannot (because they use omap). other pools like .rgw.buckets.index and .rgw.log are more latency-sensitive so tend to be on faster media

so rather than consolidating the different pools within a zone, i was suggesting that you create one set of pools and share those across multiple zones under different namespaces

for example, instead of these defaults:
```json
"user_keys_pool": "zone-name.rgw.meta:users.keys",
"user_email_pool": "zone-name.rgw.meta:users.email",
"user_swift_pool": "zone-name.rgw.meta:users.swift",
"user_uid_pool": "zone-name.rgw.meta:users.uid",
```
a collection of objectstores could use pool names of the form:
```json
"user_keys_pool": "collection.rgw.meta:zone-name.users.keys",
"user_email_pool": "collection.rgw.meta:zone-name.users.email",
"user_swift_pool": "collection.rgw.meta:zone-name.users.swift",
"user_uid_pool": "collection.rgw.meta:zone-name.users.uid",
```

**Comment by travisn** [comment]
Got it, so we could potentially create the same set of pools, but just create them once, and create rados namespaces for the different object store zones. @hohoqq Would RADOS namespaces within the pools still give you the isolation you're looking for? I assume so. We should just track that work item with a new issue if you want to open it.

**Comment by hohoqq** [comment]
> Got it, so we could potentially create the same set of pools, but just create them once, and create rados namespaces for the different object store zones. @hohoqq Would RADOS namespaces within the pools still give you the isolation you're looking for? I assume so. We should just track that work item with a new issue if you want to open it.

Please advise if it is possible to manually create a recommended set of pools and split them between multiple Rados object stores? I would like to test whether this will give the desired isolation. I could not find the necessary actions in the documentation.

And I also ask you to clarify what issue I need to open? Is it a Feature Request to use the same set of pools with multiple Rados object stores isolated with namespaces?

**Comment by travisn** [comment]
> > Got it, so we could potentially create the same set of pools, but just create them once, and create rados namespaces for the different object store zones. @hohoqq Would RADOS namespaces within the pools still give you the isolation you're looking for? I assume so. We should just track that work item with a new issue if you want to open it.
> 
> Please advise if it is possible to manually create a recommended set of pools and split them between multiple Rados object stores? I would like to test whether this will give the desired isolation. I could not find the necessary actions in the documentation.

Perhaps the following would allow you to prototype this:
1. Create the multiple object stores with Rook as you're already doing
2. From the toolbox, run `radosgw-admin` to update the object stores with those pool properties to use the namespaces all in the same pool. 

I'm not sure if the second step is possible, to modify the running object store, but I can't think of another way without making the code changes to rook.

> And I also ask you to clarify what issue I need to open? Is it a Feature Request to use the same set of pools with multiple Rados object stores isolated with namespaces?

Yes, if you can confirm that this approach works for you, a github issue to track the feature request to use the same set of pools with the namespaces.

**Comment by cbodley** [comment]
> I'm not sure if the second step is possible, to modify the running object store, but I can't think of another way without making the code changes to rook.

you'd want to stop any running radosgws first. they will have created some of these pools already, so you may need to clean some of those up

then you can use `radosgw-admin zone get --rgw-zone=name > zone.json` to read the zone as json, edit the pool names in `zone.json`, then write it back with `radosgw-admin zone set < zone.json`

**Comment by hohoqq** [comment]
Yes, this works great! 2 isolated object stores in one set of pools.

@cbodley, @travisn thank you!

Created [Feature Request](https://github.com/rook/rook/issues/11411).

**Comment by BlaineEXE** [comment]
@travisn I wonder if it might be best to manage the collected pools using a CephBlock CR like we do for the `.nfs` or `.mgr` pools, and allow users to specify those named pools in the ObjectStore CR. That way users could have control over what storage media those pools use, placement, encoding, etc.

**Comment by travisn** [comment]
Discussion moved to #11411.
