### ISSUE TITLE
CephNFS does not work properly with multus enabled

### ISSUE THREAD

**Issue by Rakshith-R** [rook/rook#10812]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
https://github.com/rook/rook/runs/8068748535?check_suite_focus=true
Testing cephnfs with multus fails.

**Expected behavior:**
cephnfs should run successfully with mutlus.

**How to reproduce it (minimal and precise):**

- deploy a multus based ceph cluster
- Apply CephNFS CR

**Logs to submit**:

refer https://github.com/rook/rook/runs/8068748535?check_suite_focus=true

**Comment by parth-gr** [comment]
./assign

**Comment by Rakshith-R** [comment]
NFS pods need to come up with ready state and csi should be able to create PVC, 
the related pr only has partial fixes.

This issue can only be marked resolved after all related TODOs are uncommented.

**Comment by parth-gr** [comment]
> NFS pods need to come up with ready state and csi should be able to create PVC, the related pr only has partial fixes.
> 
> This issue can only be marked resolved after all related TODOs are uncommented.

Please refer the follow-up issue opened for the same https://github.com/rook/rook/issues/11039,
And can you please elaborate the ` TODOs are uncommented` in the follow up issue
