### ISSUE TITLE
Optionally include clientID/clientKey and/or adminID/adminKey to secret generated from CephClient

### ISSUE THREAD

**Issue by polivbr** [rook/rook#10810]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Optionally include clientID/clientKey and/or adminID/adminKey to secret generated from CephClient.

**What is use case behind this feature:**

This would allow the generated secret to be directly used by the CSI driver without having to extract the key and generate a new secret.

**Comment by polivbr** [comment]
Sorry... I should have been more clear. The CSI driver needs a secret with "clientID" and "clientKey" fields (for static PVs) or "adminID" and "adminKey" (for provisioned PVs). Currently I have to create a CephClient, programatically extract the key from  the generated secret, and write out a new secret with clientID/clientKey fields for the CSI driver to consume. It would be very handy if the secret generated by the operator included these fields automatically and could be directly consumed by the CSI driver.

**Comment by travisn** [comment]
So you are creating the secrets used by the [storage class](https://github.com/rook/rook/blob/master/deploy/examples/csi/rbd/storageclass.yaml#L67-L72)? 

Those secrets have "userID" and "userKey" entries such as:
```
data:
  userID: Y3NpLXJiZC1ub2Rl
  userKey: QVFDd0VRMWpmaXo0TmhBQW9SWjhIYzh5blpBcWs1a1lFeS80Y3c9PQ==
```
What if the ceph client CR added those keys to the same secret it's already generating? Or you're asking for a separate secret to be written?

**Comment by polivbr** [comment]
Sorry.. my bad. I meant userID/userKey, not clientID/clientKey. I was just thinking they could be written to the same secret that's already being generated. Kills two birds with one stone.

**Comment by travisn** [comment]
Sure, that seems simple enough just to write two more keys to the same secret.

**Comment by manikanth04** [comment]
@travisn I am interested to work on this.

**Comment by parth-gr** [comment]
@manikanth04 can I know your progress on this? Are you planning to open a PR?
