### ISSUE TITLE
Convert all the troubleshooting docs to use the krew plugin,

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#10829]
Agreed, would be a good to convert all the troubleshooting docs to use the krew plugin, and in a follow-up PR instead of this one.

_Originally posted by @travisn in https://github.com/rook/rook/pull/10768#pullrequestreview-1084343772_

Place to encourage users will be where we are calling to visit the toolbox document,

Like https://rook.io/docs/rook/v1.9/Upgrade/health-verification/#status-output
[Quickstart doc](https://rook.io/docs/rook/v1.9/Getting-Started/quickstart/#cluster-environments)

**Comment by manikanth04** [comment]
@parth-gr I am interested to work on this. Could you please assign this issue to me

**Comment by parth-gr** [comment]
For sure, thanks for taking this up!!

In future you can also use auto assign issues by https://github.com/parth-gr/rook/pull/1 `/assign`

**Comment by travisn** [comment]
@manikanth04 Before you start updating the docs, I would suggest that we discuss here which specific changes to make in the docs, and will be good as small PRs instead of one big change to the docs. Thanks for working on this!

**Comment by travisn** [comment]
Rather than track this effort with an issue, we can update the docs over time as we touch related areas
