### ISSUE TITLE
the osd resize support for lvm-based OSDs

### ISSUE THREAD

**Issue by andy108369** [rook/rook#10835]
I've noticed there is `getExpandPVCInitContainer` function but is only for the `raw` devices, not for the `lvm`:
https://github.com/rook/rook/blob/v1.9.9/pkg/operator/ceph/cluster/osd/spec.go#L503-L530

Please support the osd resize for lvm-based OSDs.

Ref.
- https://github.com/rook/rook/discussions/10214#discussioncomment-3507328

**Comment by phifre** [comment]
Could this be implemented for PVC based **and** host based clusters?

After adding support for lvm host based clusters in 1.9.8 there is to my understanding no way to resize the lv without recreating the osd.

So this should especially be added [here](https://github.com/rook/rook/blob/v1.9.9/pkg/operator/ceph/cluster/osd/spec.go#L528).

**Comment by satoru-takeuchi** [comment]
@phifre Theoretically both types can support this feature. I'll check whether it can actually do it.

**Comment by abh** [comment]
FWIW I did the bluefs-bdev-expand command from https://github.com/rook/rook/issues/2997#issuecomment-1237966127 and it solved it for me on an LVM backed OSD.

**Comment by travisn** [comment]
This is fixed by #11483

**Comment by satoru-takeuchi** [comment]
@travisn Although lvm mode OSD resize is supported now in host-based cluster, it's not supported yet in PVC-based cluster. I'll submit a PR soon.

**Comment by travisn** [comment]
> @travisn Although lvm mode OSD resize is supported now in host-based cluster, it's not supported yet in PVC-based cluster. I'll submit a PR soon.

Ok thanks, I see it's only for raw mode on PVCs.

**Comment by andy108369** [comment]
@travisn @satoru-takeuchi any updates on this one?

**Comment by satoru-takeuchi** [comment]
@travisn @andy108369 I haven't work on this feature becaude I was busy recently. 
Probably I'll be able to handle it next week.
