### ISSUE TITLE
monitors keep rebooting and PVC are not being served. 

### ISSUE THREAD

**Issue by leasley199** [rook/rook#10851]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Pods staring post helm deploy, but 2 of the 3 monitor instance keep restarting in error and PVC can not be served. Happening in two seperate K8s Clusters. 

**Expected behavior:**
Monitors to become healthy upon initial deployment and storage claims to be deligated to requested pods.

**How to reproduce it (minimal and precise):**
- helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph
- helm install --create-namespace --namespace rook-ceph rook-ceph-cluster --set operatorNamespace=rook-ceph rook-release/rook-ceph-cluster

**Logs to submit**:
mon.ev@1(electing) e29 collect_metadata :  no unique device id for : fallback method has no model nor serial'
debug 2022-08-31T21:39:01.816+0000 7f8b17d1c700  0 mon.ev@1(leader) e29 handle_command mon_command({"prefix": "osd pool create", "pool": "ceph-blockpool", "pg_num": 0, "pool_type": "replicated", "erasure_code_profile": "ceph-blockpool", "size": 3, "format": "json"} v 0) v1
debug 2022-08-31T21:39:01.816+0000 7f8b17d1c700  0 log_channel(audit) log [INF] : from='client.40844148 ' entity='client.admin' cmd=[{"prefix": "osd pool create", "pool": "ceph-blockpool", "pg_num": 0, "pool_type": "replicated", "erasure_code_profile": "ceph-blockpool", "size": 3, "format": "json"}]: dispatch
debug 2022-08-31T21:39:59.583+0000 7f8b1e529700 -1 received  signal: Terminated from Kernel ( Could be generated by pthread_kill(), raise(), abort(), alarm() ) UID: 0
debug 2022-08-31T21:39:59.583+0000 7f8b1e529700 -1 mon.ev@1(leader) e29 *** Got Signal Terminated ***
debug 2022-08-31T21:39:59.583+0000 7f8b1e529700  1 mon.ev@1(leader) e29 shutdown

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:
Cluster in error

* Output of krew commands, if necessary

   `kubectl rook-ceph health`
Info:  Checking if at least three mon pods are running on different nodes
Warning:  At least three mon pods should running on different nodes
rook-ceph-mon-eq-7fcc7d6956-snkgt                         0/1     CrashLoopBackOff   27 (2m30s ago)   102m
rook-ceph-mon-ev-c4f9ddbc5-wlzr4                          0/1     CrashLoopBackOff   27 (2m57s ago)   103m
rook-ceph-mon-ew-6dc9475867-98ht8                         1/1     Running            0                119m

   `kubectl rook-ceph ceph status`
timed out

**Environment**:
* OS (e.g. from /etc/os-release):  Fedora CoreOS 36.20220522.
* Kernel (e.g. `uname -a`): 5.17.9-300.fc36.x86_64
* Cloud provider or hardware configuration: on-prem
* Rook version (use `rook version` inside of a Rook Pod): 1.9.9 & 1.9.10
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.10 (45fa1a083152e41a408d15505f594ec5f1b4fe17) pacific (stable)
* Kubernetes version (use `kubectl version`): 1.22.10 & 1.23.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Vanilla 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
Wow, you've had a lot of mon failures if your mon IDs are up to eq, ev, and ew. This typically indicates a configuration issue with the network, try checking the [Ceph network requirements](https://docs.ceph.com/en/latest/rados/configuration/network-config-ref/). While you're investigating your network config, you might also see if it helps to disable or change the params for the [liveness probes](https://rook.io/docs/rook/latest/CRDs/Cluster/ceph-cluster-crd/#health-settings) on the mons.

**Comment by leasley199** [comment]
@travisn problem with the liveness probe option is that it just silents the mon pods as opposed to resolving the problem. We are using cilium CNI and 3 of of the 5 clusters we have built work with no issues for rook-ceph, which is weird. Also, yea haha eq - ew mons; not sure why but it decided to deploy out of box with those tags. Do you know what requirements need to be met for K8s networking, we are using portmap chaining-mode.

**Comment by travisn** [comment]
> @travisn problem with the liveness probe option is that it just silents the mon pods as opposed to resolving the problem. 

Yes, changing the liveness probe is just a workaround to see if it helps temporarily.

> We are using cilium CNI and 3 of of the 5 clusters we have built work with no issues for rook-ceph, which is weird. 

You don't know of any difference between the clusters? I wonder if there is some obscure network setting that is different and causing the problem.

> Also, yea haha eq - ew mons; not sure why but it decided to deploy out of box with those tags. 

If the cluster has been running for a while on the flaky network, rook could have easily arrived at those mons after many failovers. 

> Do you know what requirements need to be met for K8s networking, we are using portmap chaining-mode.

The Ceph network doc linked in my previous place is the best place to look.
