### ISSUE TITLE
Need ability to set the priorityClassName on the rook-ceph-tools pod created by the operator

### ISSUE THREAD

**Issue by tonygilkerson** [rook/rook#10905]
* Feature Request

**What should the feature do:**

Allow the user to specify `priorityClassName` in a `values.yaml` file when doing a `helm install` of the operator chart located here `https://charts.rook.io/release`

The following values already exist for a similar purpose in the chart's `values.yaml`:
```sh
priorityClassName
csi.pluginPriorityClassName	
csi.provisionerPriorityClassName
discover.priorityClassName
```

so maybe all that is needed is something like:

```sh
tools.priorityClassName
```

**What is use case behind this feature:**

Our cluster is ofter over allocated and we use priorityClasses to identify critical services.  In this way the non-critical services get killed off by the k8s scheduler first when there is resource contention.  We want the ability to identify the all rook-ceph workloads as a critical service and to do that we need to set it priorityClassName.

**Environment**:

**Comment by travisn** [comment]
Did you enable the `toolbox.priorityClassName` property in [this example](https://github.com/rook/rook/blob/release-1.10/deploy/charts/rook-ceph-cluster/values.yaml#L34-L35)?
