### ISSUE TITLE
failed to create an encrypted osd on part

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#10911]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Failed to create an encrypted OSD on a partition with the following storage configuration.

```
# kubectl -n rook logs rook-ceph-osd-prepare-cephtest-7rwgv
....
2022-08-20 13:13:16.796500 D | exec: ceph-volume lvm batch: error: /dev/sde1 is a partition, please pass LVs or raw block devices
2022-08-20 13:13:16.828908 C | rookcmd: failed to configure devices: failed to initialize osd: failed ceph-volume report: exit status 2
```

Originally reported in the following slack discussions.
https://rook-io.slack.com/archives/CK9CF5H2R/p1661341359420179
https://rook-io.slack.com/archives/CK9CF5H2R/p1661001784710299

We should skip creating an osd in this case because Ceph doesn't support lvm mode encrypted OSD. Although [recent Ceph supports raw mode encrypted device](https://github.com/ceph/ceph/commit/159c30d29f009c07e51a4bd7cd5ecea8cf6c8739), Rook doesn't support this configuration.

**Expected behavior:**

Skip creating an osd in this case. 

**How to reproduce it (minimal and precise):**

1. Prepare a raw partition.
2. Create a cluster with the following storage configuration.

```
  storage:
    useAllDevices: true
    useAllNodes: true
    config:
      encryptedDevice: "true"
```

**Comment by binacloud** [comment]
Hi @satoru-takeuchi is there any update to this feature? it's really important to set up production-ready clusters for small to medium data center.
