### ISSUE TITLE
Raw OSD increment not add as available space but as taken

### ISSUE THREAD

**Issue by samos667** [rook/rook#10930]
* Bug Report

**Expected behavior:**
When i increment RAW virtual disk in proxmox of the OSD, the size incremented is not added as available but as taken.

**How to reproduce it (minimal and precise):**
Deploy rook-ceph with HELM on 6 proxmox VM. With the default configuration. Each kubernetes worker need to have 1 disk unused for rook can use it as OSD.
In my setup, disks are virtualized with VirtIO block.
So, when the cluster is deployed with the 3 OSD of workers, i stop the OSD with kubectl -n rook-ceph scale deployment rook-ceph-osd-<id> --replicas=0.
After this i increment the virtual disk from 100GB to 150GB (in proxmox).
When i start the OSD with  rook-ceph scale deployment rook-ceph-osd-<id> --replicas=1, the OSD start correclty but the new space incremented is considered as taken.
![image](https://user-images.githubusercontent.com/50653464/189065558-6ab13233-bbd9-4e7b-8a35-d25909ef54af.png)

Log of OSD after restart:
[logs-from-osd-in-rook-ceph-osd-2-78c9b4cc96-klw9k.log](https://github.com/rook/rook/files/9524783/logs-from-osd-in-rook-ceph-osd-2-78c9b4cc96-klw9k.log)

**Environment**:
* OS (e.g. from /etc/os-release):
![image](https://user-images.githubusercontent.com/50653464/189061436-33e67aa5-8663-4aa3-8fa4-46582c27a78e.png)

* Kernel (e.g. `uname -a`): Linux k8s-dev-11 5.10.0-15-amd64 '#' 1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.10.0-alpha.0.95.gc7ab01b94 
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.10 (45fa1a083152e41a408d15505f594ec5f1b4fe17) pacific (stable)
* Kubernetes version (use `kubectl version`): 1.24.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare-metal multi-master
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): 
![image](https://user-images.githubusercontent.com/50653464/189062309-98827e88-1264-40a1-be86-9663e9189ae3.png)

**Comment by travisn** [comment]
@samos667 Do the OSD pod specs have an init container that expands the size of the OSD? The command of the container would be `ceph-bluestore-tool` and an arg: `bluefs-bdev-expand1`. If so, it is expected to expand. If not, sounds like a bug that the init container is missing.

**Comment by samos667** [comment]
No, there is no init container to run ceph-bluestore-tool.

`apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 6b329cc7dd7b35d3b8dfe02282a0f2d273bbb575b0ffdd3b3d12eb4e2adb2fe8
    cni.projectcalico.org/podIP: 10.10.186.131/32
    cni.projectcalico.org/podIPs: 10.10.186.131/32
  creationTimestamp: "2022-09-08T07:37:30Z"
  generateName: rook-ceph-osd-2-78c9b4cc96-
  labels:
    app: rook-ceph-osd
    app.kubernetes.io/component: cephclusters.ceph.rook.io
    app.kubernetes.io/created-by: rook-ceph-operator
    app.kubernetes.io/instance: "2"
    app.kubernetes.io/managed-by: rook-ceph-operator
    app.kubernetes.io/name: ceph-osd
    app.kubernetes.io/part-of: rook-ceph
    ceph-osd-id: "2"
    ceph-version: 16.2.10-0
    ceph_daemon_id: "2"
    ceph_daemon_type: osd
    failure-domain: k8s-dev-32
    osd: "2"
    pod-template-hash: 78c9b4cc96
    portable: "false"
    rook-version: v1.10.0-alpha.0.95.gc7ab01b94
    rook.io/operator-namespace: rook-ceph
    rook_cluster: rook-ceph
    topology-location-host: k8s-dev-32
    topology-location-root: default
  name: rook-ceph-osd-2-78c9b4cc96-klw9k
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: rook-ceph-osd-2-78c9b4cc96
    uid: 18dd1d0d-1e2a-4d98-815c-e544227f3203
  resourceVersion: "7606082"
  uid: 9d5ba5cf-e448-411d-b695-ed3d170828bc
spec:
  affinity: {}
  containers:
  - args:
    - --foreground
    - --id
    - "2"
    - --fsid
    - 720a9347-d59d-4fa9-934c-98cf1bec5e9a
    - --setuser
    - ceph
    - --setgroup
    - ceph
    - --crush-location=root=default host=k8s-dev-32
    - --log-to-stderr=true
    - --err-to-stderr=true
    - --mon-cluster-log-to-stderr=true
    - '--log-stderr-prefix=debug '
    - --default-log-to-file=false
    - --default-mon-cluster-log-to-file=false
    - --ms-learn-addr-from-peer=false
    command:
    - ceph-osd
    env:
    - name: ROOK_NODE_NAME
      value: k8s-dev-32
    - name: ROOK_CLUSTER_ID
      value: 05ef71f2-3a3f-4a57-9307-1f33abcae7ef
    - name: ROOK_CLUSTER_NAME
      value: rook-ceph
    - name: ROOK_PRIVATE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: ROOK_PUBLIC_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: POD_NAMESPACE
      value: rook-ceph
    - name: ROOK_MON_ENDPOINTS
      valueFrom:
        configMapKeyRef:
          key: data
          name: rook-ceph-mon-endpoints
    - name: ROOK_MON_SECRET
      valueFrom:
        secretKeyRef:
          key: mon-secret
          name: rook-ceph-mon
    - name: ROOK_CEPH_USERNAME
      valueFrom:
        secretKeyRef:
          key: ceph-username
          name: rook-ceph-mon
    - name: ROOK_CEPH_SECRET
      valueFrom:
        secretKeyRef:
          key: ceph-secret
          name: rook-ceph-mon
    - name: ROOK_CONFIG_DIR
      value: /var/lib/rook
    - name: ROOK_CEPH_CONFIG_OVERRIDE
      value: /etc/rook/config/override.conf
    - name: ROOK_FSID
      valueFrom:
        secretKeyRef:
          key: fsid
          name: rook-ceph-mon
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ROOK_CRUSHMAP_ROOT
      value: default
    - name: ROOK_CRUSHMAP_HOSTNAME
      value: k8s-dev-32
    - name: CEPH_VOLUME_DEBUG
      value: "1"
    - name: CEPH_VOLUME_SKIP_RESTORECON
      value: "1"
    - name: DM_DISABLE_UDEV
      value: "1"
    - name: ROOK_OSDS_PER_DEVICE
      value: "1"
    - name: CONTAINER_IMAGE
      value: quay.io/ceph/ceph:v16.2.10
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.memory
    - name: POD_MEMORY_REQUEST
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: requests.memory
    - name: POD_CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "1"
          resource: limits.cpu
    - name: POD_CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: requests.cpu
    - name: ROOK_OSD_UUID
      value: 1e3fbfe3-a2f5-4b57-9ad4-6fb283c0612f
    - name: ROOK_OSD_ID
      value: "2"
    - name: ROOK_CEPH_MON_HOST
      valueFrom:
        secretKeyRef:
          key: mon_host
          name: rook-ceph-config
    - name: CEPH_ARGS
      value: -m $(ROOK_CEPH_MON_HOST)
    - name: ROOK_BLOCK_PATH
      value: /dev/vdb
    - name: ROOK_CV_MODE
      value: raw
    - name: ROOK_OSD_DEVICE_CLASS
      value: hdd
    envFrom:
    - configMapRef:
        name: rook-ceph-osd-env-override
        optional: true
    image: quay.io/ceph/ceph:v16.2.10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - env
        - -i
        - sh
        - -c
        - ceph --admin-daemon /run/ceph/ceph-osd.2.asok status
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
    name: osd
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 4Gi
    securityContext:
      privileged: true
      readOnlyRootFilesystem: false
      runAsUser: 0
    startupProbe:
      exec:
        command:
        - env
        - -i
        - sh
        - -c
        - ceph --admin-daemon /run/ceph/ceph-osd.2.asok status
      failureThreshold: 720
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/rook
      name: rook-data
    - mountPath: /etc/ceph
      name: rook-config-override
      readOnly: true
    - mountPath: /var/log/ceph
      name: rook-ceph-log
    - mountPath: /var/lib/ceph/crash
      name: rook-ceph-crash
    - mountPath: /dev
      name: devices
    - mountPath: /run/udev
      name: run-udev
    - mountPath: /var/lib/ceph/osd/ceph-2
      name: activate-osd
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nxfpl
      readOnly: true
    workingDir: /var/log/ceph
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - /bin/bash
    - -c
    - "\nset -o errexit\nset -o pipefail\nset -o nounset # fail if variables are unset\nset
      -o xtrace\n\nOSD_ID=\"$ROOK_OSD_ID\"\nCEPH_FSID=720a9347-d59d-4fa9-934c-98cf1bec5e9a\nOSD_UUID=1e3fbfe3-a2f5-4b57-9ad4-6fb283c0612f\nOSD_STORE_FLAG=\"--bluestore\"\nOSD_DATA_DIR=/var/lib/ceph/osd/ceph-\"$OSD_ID\"\nCV_MODE=raw\nDEVICE=\"$ROOK_BLOCK_PATH\"\n\n#
      \"ceph.conf\" must have the \"fsid\" global configuration to activate encrypted
      OSDs\n# after the following Ceph's PR is merged.\n# https://github.com/ceph/ceph/commit/25655e5a8829e001adf467511a6bde8142b0a575\n#
      This limitation will be removed later. After that, we can remove this\n# fsid
      injection code. Probably a good time is when to remove Quincy support.\n# https://github.com/rook/rook/pull/10333#discussion_r892817877\ncp
      --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf\npython3 -c
      \"\nimport configparser\n\nconfig = configparser.ConfigParser()\nconfig.read('/etc/ceph/ceph.conf')\n\nif
      not config.has_section('global'):\n    config['global'] = {}\n\nif not config.has_option('global','fsid'):\n
      \   config['global']['fsid'] = '$CEPH_FSID'\n\nwith open('/etc/ceph/ceph.conf',
      'w') as configfile:\n    config.write(configfile)\n\"\n\n# create new keyring\nceph
      -n client.admin auth get-or-create osd.\"$OSD_ID\" mon 'allow profile osd' mgr
      'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring\n\n#
      active the osd with ceph-volume\nif [[ \"$CV_MODE\" == \"lvm\" ]]; then\n\tTMP_DIR=$(mktemp
      -d)\n\n\t# activate osd\n\tceph-volume lvm activate --no-systemd \"$OSD_STORE_FLAG\"
      \"$OSD_ID\" \"$OSD_UUID\"\n\n\t# copy the tmpfs directory to a temporary directory\n\t#
      this is needed because when the init container exits, the tmpfs goes away and
      its content with it\n\t# this will result in the emptydir to be empty when accessed
      by the main osd container\n\tcp --verbose --no-dereference \"$OSD_DATA_DIR\"/*
      \"$TMP_DIR\"/\n\n\t# unmount the tmpfs since we don't need it anymore\n\tumount
      \"$OSD_DATA_DIR\"\n\n\t# copy back the content of the tmpfs into the original
      osd directory\n\tcp --verbose --no-dereference \"$TMP_DIR\"/* \"$OSD_DATA_DIR\"\n\n\t#
      retain ownership of files to the ceph user/group\n\tchown --verbose --recursive
      ceph:ceph \"$OSD_DATA_DIR\"\n\n\t# remove the temporary directory\n\trm --recursive
      --force \"$TMP_DIR\"\nelse\n\t# 'ceph-volume raw list' (which the osd-prepare
      job uses to report OSDs on nodes)\n\t#  returns user-friendly device names which
      can change when systems reboot. To\n\t# keep OSD pods from crashing repeatedly
      after a reboot, we need to check if the\n\t# block device we have is still correct,
      and if it isn't correct, we need to\n\t# scan all the disks to find the right
      one.\n\tOSD_LIST=\"$(mktemp)\"\n\n\tfunction find_device() {\n\t\t# jq would
      be preferable, but might be removed for hardened Ceph images\n\t\t# python3
      should exist in all containers having Ceph\n\t\tpython3 -c \"\nimport sys, json\nfor
      _, info in json.load(sys.stdin).items():\n\tif info['osd_id'] == $OSD_ID:\n\t\tprint(info['device'],
      end='')\n\t\tprint('found device: ' + info['device'], file=sys.stderr) # log
      the disk we found to stderr\n\t\tsys.exit(0)  # don't keep processing once the
      disk is found\nsys.exit('no disk found with OSD ID $OSD_ID')\n\"\n\t}\n\n\tceph-volume
      raw list \"$DEVICE\" > \"$OSD_LIST\"\n\tcat \"$OSD_LIST\"\n\n\tif ! find_device
      < \"$OSD_LIST\"; then\n\t\tceph-volume raw list > \"$OSD_LIST\"\n\t\tcat \"$OSD_LIST\"\n\n\t\tDEVICE=\"$(find_device
      < \"$OSD_LIST\")\"\n\tfi\n\t[[ -z \"$DEVICE\" ]] && { echo \"no device\" ; exit
      1 ; }\n\n\t# ceph-volume raw mode only supports bluestore so we don't need to
      pass a store flag\n\tceph-volume raw activate --device \"$DEVICE\" --no-systemd
      --no-tmpfs\nfi\n"
    env:
    - name: CEPH_VOLUME_DEBUG
      value: "1"
    - name: CEPH_VOLUME_SKIP_RESTORECON
      value: "1"
    - name: DM_DISABLE_UDEV
      value: "1"
    - name: ROOK_CEPH_MON_HOST
      valueFrom:
        secretKeyRef:
          key: mon_host
          name: rook-ceph-config
    - name: CEPH_ARGS
      value: -m $(ROOK_CEPH_MON_HOST)
    - name: ROOK_BLOCK_PATH
      value: /dev/vdb
    - name: ROOK_METADATA_DEVICE
    - name: ROOK_WAL_DEVICE
    - name: ROOK_OSD_ID
      value: "2"
    envFrom:
    - configMapRef:
        name: rook-ceph-osd-env-override
        optional: true
    image: quay.io/ceph/ceph:v16.2.10
    imagePullPolicy: IfNotPresent
    name: activate
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 4Gi
    securityContext:
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/ceph/osd/ceph-2
      name: activate-osd
    - mountPath: /dev
      name: devices
    - mountPath: /etc/temp-ceph
      name: rook-config-override
      readOnly: true
    - mountPath: /etc/ceph/admin-keyring-store/
      name: rook-ceph-admin-keyring
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nxfpl
      readOnly: true
  - args:
    - --verbose
    - --recursive
    - ceph:ceph
    - /var/log/ceph
    - /var/lib/ceph/crash
    command:
    - chown
    image: quay.io/ceph/ceph:v16.2.10
    imagePullPolicy: IfNotPresent
    name: chown-container-data-dir
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 4Gi
    securityContext:
      privileged: true
      readOnlyRootFilesystem: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/rook
      name: rook-data
    - mountPath: /etc/ceph
      name: rook-config-override
      readOnly: true
    - mountPath: /var/log/ceph
      name: rook-ceph-log
    - mountPath: /var/lib/ceph/crash
      name: rook-ceph-crash
    - mountPath: /dev
      name: devices
    - mountPath: /run/udev
      name: run-udev
    - mountPath: /var/lib/ceph/osd/ceph-2
      name: activate-osd
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-nxfpl
      readOnly: true
  nodeName: k8s-dev-32
  nodeSelector:
    kubernetes.io/hostname: k8s-dev-32
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: rook-ceph-osd
  serviceAccountName: rook-ceph-osd
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /var/lib/rook
      type: ""
    name: rook-data
  - name: rook-config-override
    projected:
      defaultMode: 420
      sources:
      - configMap:
          items:
          - key: config
            mode: 292
            path: ceph.conf
          name: rook-config-override
  - hostPath:
      path: /var/lib/rook/rook-ceph/log
      type: ""
    name: rook-ceph-log
  - hostPath:
      path: /var/lib/rook/rook-ceph/crash
      type: ""
    name: rook-ceph-crash
  - hostPath:
      path: /dev
      type: ""
    name: devices
  - hostPath:
      path: /run/udev
      type: ""
    name: run-udev
  - hostPath:
      path: /var/lib/rook/rook-ceph/720a9347-d59d-4fa9-934c-98cf1bec5e9a_1e3fbfe3-a2f5-4b57-9ad4-6fb283c0612f
      type: DirectoryOrCreate
    name: activate-osd
  - name: rook-ceph-admin-keyring
    secret:
      defaultMode: 420
      secretName: rook-ceph-admin-keyring
  - name: kube-api-access-nxfpl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-09-08T07:37:33Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-09-08T07:37:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-09-08T07:37:50Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-09-08T07:37:30Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c1a5d5543c6f8532fa733f235cbf7bc96ab9317446c02694b3631effcc1e334b
    image: quay.io/ceph/ceph:v16.2.10
    imageID: quay.io/ceph/ceph@sha256:c5fd9d806c54e5cc9db8efd50363e1edf7af62f101b264dccacb9d6091dcf7aa
    lastState: {}
    name: osd
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-09-08T07:37:34Z"
  hostIP: 172.16.31.189
  initContainerStatuses:
  - containerID: containerd://9a6f4f39f51a92c977ea24b3f70d27b246c57dc2990aed08f8d2b803b02fcdf5
    image: quay.io/ceph/ceph:v16.2.10
    imageID: quay.io/ceph/ceph@sha256:c5fd9d806c54e5cc9db8efd50363e1edf7af62f101b264dccacb9d6091dcf7aa
    lastState: {}
    name: activate
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://9a6f4f39f51a92c977ea24b3f70d27b246c57dc2990aed08f8d2b803b02fcdf5
        exitCode: 0
        finishedAt: "2022-09-08T07:37:32Z"
        reason: Completed
        startedAt: "2022-09-08T07:37:31Z"
  - containerID: containerd://de24e2cf3cc69e87d71f9e7ea027fab74f088004ffb02aa0879110b62293ceee
    image: quay.io/ceph/ceph:v16.2.10
    imageID: quay.io/ceph/ceph@sha256:c5fd9d806c54e5cc9db8efd50363e1edf7af62f101b264dccacb9d6091dcf7aa
    lastState: {}
    name: chown-container-data-dir
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://de24e2cf3cc69e87d71f9e7ea027fab74f088004ffb02aa0879110b62293ceee
        exitCode: 0
        finishedAt: "2022-09-08T07:37:32Z"
        reason: Completed
        startedAt: "2022-09-08T07:37:32Z"
  phase: Running
  podIP: 10.10.186.131
  podIPs:
  - ip: 10.10.186.131
  qosClass: Burstable
  startTime: "2022-09-08T07:37:30Z"
`

**Comment by samos667** [comment]
No, there is no init container to run ceph-bluestore-tool command.

[Here ](https://gist.github.com/samos667/574ce39fb129250897800006ae050ccd#file-osd-pod-2-yaml) a dump of my pod YAML.

**Comment by satoru-takeuchi** [comment]
@samos667 @travisn ok, i'll try to reproduce this problem.

**Comment by andy108369** [comment]
I think that's when a single drive gets split into a more than 1 OSD, so the LVM gets there, leading to https://github.com/rook/rook/issues/10835

**Comment by samos667** [comment]
@andy108369 Each OSD are on unique drive. Its 3 node proxmox cluster and worker are split on each of them. So each OSD are provided by different disk.

But i have a question about this, proxmox provide virtual disk with LVM and interface it with virtIO. And in my VM, disks are announced as /dev/vdX. I don't know if Ceph "see" it as LVM-based because of this.

**Comment by samos667** [comment]
> @samos667 can you please share the output from these commands?
> 
> > run them on one of your nodes where you have the OSDs
> 
> ```
> lsblk -f
> pvs
> vgs
> lvs
> ```

https://asciinema.org/a/uTGG829bLYJUDTyIu3B2yXFnb

**Comment by cupnes** [comment]
@samos667 Sorry for the late reply. I succeeded to reproduce your problem. This problem happened because the host-based cluster doesn't have host-based cluster doesn't have `expand-bluefs` init container. I guess that you use the host-based cluster. Is it correct?

**Comment by samos667** [comment]
> @samos667 Sorry for the late reply. I succeeded to reproduce your problem. This problem happened because the host-based cluster doesn't have host-based cluster doesn't have `ceph-bluestore-tool bluefs-bdev-expand` init container. I guess that you use the host-based cluster. Is it correct?

Sorry for my late reply, so to "solve" my problem is to passtrought the disks directly from proxmox.
I'm not quite sure what you mean by host-based.

**Comment by samos667** [comment]
Oh thanks so is that for my case ! Thanks you all !
