### ISSUE TITLE
Unsure if bug or feature request

### ISSUE THREAD

**Issue by cccsss01** [rook/rook#10958]
https://rook.io/docs/rook/v1.10/CRDs/Object-Storage/ceph-object-store-crd/
Selecting Pool CRD sends you to Block Pool CRD, as I'm looking at Object storage, and not Block Storage, I am not confident this is correct.

If this is correct, simply labeling the link Pool CRD to Block Pool CRD would be beneficial, as well as a note, stating they use the same CRD's.

**Comment by travisn** [comment]
Yes, the Pool CRD refers to the Block Pool CRD.
