### ISSUE TITLE
Create clear uninstall/clean documentation

### ISSUE THREAD

**Issue by cccsss01** [rook/rook#10953]
Currently it is difficult to find the uninstall/clear rook, and clean the disk.  

Creating a separate tab in the left pane of https://rook.io/docs/rook/v1.10/Troubleshooting could be ideal.

But I believe this should be as common as the install, is the uninstall/restore as well.  I think having it in two locations troubleshooting and https://rook.io/docs/rook/v1.10/Getting-Started would be great.

Adding the teardown in the panel so that it can be easily accessible would be great as well.

**Comment by travisn** [comment]
Have you found the [cleanup guide](https://rook.io/docs/rook/latest/Storage-Configuration/ceph-teardown/) in the Storage Configuration tab? Agreed it can be difficult to find though.

**Comment by cccsss01** [comment]
> Have you found the [cleanup guide](https://rook.io/docs/rook/latest/Storage-Configuration/ceph-teardown/) in the Storage Configuration tab? Agreed it can be difficult to find though.

Yep, i've found it.  I believe that's an important peace that should warrant it's own tab in the left pane, and/or top pane.

**Comment by travisn** [comment]
I could vote for moving the Cleanup page from the `Storage Configuration` tab to the `Getting Started` tab, as the last topic on the page. That would be more discoverable than buried in the storage config. @galexrt wdyt?

**Comment by cccsss01** [comment]
I'd prefer both
