### ISSUE TITLE
CI failed because actions-setup-minikube failed to extract crictl

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#10964]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Sometimes CI failed because actions-setup-minikube failed to extract crictl.

https://github.com/rook/rook/actions/runs/3039246303/jobs/4903811060#step:3:203

In this case, arm64 `ubuntu-focal-aarch64-01` runner is used.

@travisn @subhamkrai I guess the root cause is that the self-hosted- runner used by `canary-arm64` is `ubuntu-focal-aarch64-01` and this runner has `ubuntu-20.04` label.

https://github.com/rook/rook/blob/master/.github/workflows/daily-nightly-jobs.yml#L13

Then sometimes most workflows, they uses `ubuntu-20.04` runner, are scheduled to `ubuntu-focal-aarch64-01` by accident.
If my assumption is correct, renaming the `ubuntu-20.04` label in `ubuntu-focal-aarch64-01` to another name like `ubuntu-20.04-arm` and specifying the new label in `canary-arm64` resolved this problem.

**Expected behavior:**

CI doesn't fail to extract crictl.

**How to reproduce it (minimal and precise):**

Run CI several times.

**Comment by travisn** [comment]
@satoru-takeuchi Thanks for looking at this, do you want to open a PR or should @subhamkrai look at it?

**Comment by satoru-takeuchi** [comment]
@travisn This problem can't be resolved only by PR. We need to change the label of `ubuntu-focal-aarch64-01` self-hosted runner. Probably only Red Hat guys can access this runner. I can't access "settings" tab of rook repo.

https://docs.github.com/en/actions/hosting-your-own-runners/using-labels-with-self-hosted-runners

**Comment by parth-gr** [comment]
[mon]
 mon compact on start = true

**Comment by BlaineEXE** [comment]
I worry about compact on start because (1) that only applies on mon start afaiu, and (2) it makes the monitors take longer to start up. I think it might be better to use  `mon_data_size_warn` and `mon_data_avail_warn`

**Comment by travisn** [comment]
@BlaineEXE Is this comment meant for #10971?

**Comment by travisn** [comment]
On the runner, I updated the label from `ubuntu-20.04` to `ubuntu-20.04-arm64`
