### ISSUE TITLE
CI: Has health warning most of the time

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#10971]
**Is this a bug report or feature request?**
* Bug Report
* CI has ceph cluster heath warning always
 `ceph-cluster-controller: Health: "HEALTH_WARN", code: "MON_DISK_LOW", message: "mon a is low on available space"`
**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment]
[mon]
mon compact on start = true

**Comment by parth-gr** [comment]
right place for this comment https://github.com/rook/rook/issues/10964#issuecomment-1245614096

**Comment by BlaineEXE** [comment]
I worry about compact on start because (1) that only applies on mon start afaiu, and (2) it makes the monitors take longer to start up. I think it might be better to use  `mon_data_size_warn` and `mon_data_avail_warn`
