### ISSUE TITLE
support encrypted osd on partition

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#10984]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Support encrypted osd on partition. We've not support this feature but [Recent Ceph supports raw mode encrypted device](https://github.com/ceph/ceph/commit/159c30d29f009c07e51a4bd7cd5ecea8cf6c8739).

**Comment by satoru-takeuchi** [comment]
ref. #10911

**Comment by satoru-takeuchi** [comment]
@nbisson Not yet. I'll,try it after implementing #10835

**Comment by satoru-takeuchi** [comment]
@aauroy I'm in charge of this feature. It's delayed because I've been busy for several months. I'll implement it when I get an extra time.

**Comment by binacloud** [comment]
Can this be re-opened ? I see that the commit was already done in September 2023 but it's still not merged to release 1.15 and 1.16, in November 2024.

I'm puzzled as to why this feature is still not implemented after 3 years as it's a very important factor to qualify Rook as production-ready,

**Comment by KKonak** [comment]
Waiting for this capability to be merged as well. Any reason as to why it has not?

**Comment by satoru-takeuchi** [comment]
@KKonak It's due to lack of my development resource.

https://github.com/rook/rook/issues/15073#issuecomment-2505197439
> To support this feature, I guess we should change over 1000 lines of code. Unfortunately I've not had enough time to implement this feature.

**Comment by KKonak** [comment]
@satoru-takeuchi thanks for the reply, I was not aware it required so many changes under the hood. I understand thank you!!
