### ISSUE TITLE
Make rook helm chart CIS compliant

### ISSUE THREAD

**Issue by ifalex** [rook/rook#10994]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Rook/ceph should be CIS compliant.
Currently having rook/ceph included in a PAAS solution fail to pass some Kubernetes CIS tests/recommandations.

**What is use case behind this feature:**
CIS - 5.4.1 Prefer using secrets as files over secrets as environment variables

There a couple objects created by rook operators that use secrets as environment variables instead of files which is the best practice considered by Kubernetes CIS.

On rook version 1.9.9 on a 3 nodes k8s cluster this is the result we get on running the CIS test for 5.4.1:

kubectl get all -o jsonpath='{range .items[?(@..secretKeyRef)]} {.kind} {.metadata.name} {"\n"}{end}' -A  | grep rook
 Pod rook-ceph-ceph-tools-0 
 Pod rook-ceph-crashcollector-node-1-7685f96cc8-429pc 
 Pod rook-ceph-crashcollector-node-2-f65d8bc89-2m2f2 
 Pod rook-ceph-crashcollector-node-3-55668b799d-5nqqj 
 Pod rook-ceph-mds-rook-ceph-ceph-fs-a-6649855745-98tsd 
 Pod rook-ceph-mds-rook-ceph-ceph-fs-b-7b6cd7dc47-k6mv4 
 Pod rook-ceph-mgr-a-64659c8d4f-mv7cz 
 Pod rook-ceph-mon-a-669455ccb8-4b58p 
 Pod rook-ceph-mon-b-7d87d7566c-wjtcd 
 Pod rook-ceph-mon-c-67c64f98d6-xlp68 
 Pod rook-ceph-osd-0-b99646748-zxpwz 
 Pod rook-ceph-osd-1-857766f74b-tswhd 
 Pod rook-ceph-osd-2-679d9cf649-hfpl5 
 Pod rook-ceph-osd-prepare-node-1-kkb7h 
 Pod rook-ceph-osd-prepare-node-2-kcgr6 
 Pod rook-ceph-osd-prepare-node-3-r82x8 
 Deployment rook-ceph-crashcollector-node-1 
 Deployment rook-ceph-crashcollector-node-2 
 Deployment rook-ceph-crashcollector-node-3 
 Deployment rook-ceph-mds-rook-ceph-ceph-fs-a 
 Deployment rook-ceph-mds-rook-ceph-ceph-fs-b 
 Deployment rook-ceph-mgr-a 
 Deployment rook-ceph-mon-a 
 Deployment rook-ceph-mon-b 
 Deployment rook-ceph-mon-c 
 Deployment rook-ceph-osd-0 
 Deployment rook-ceph-osd-1 
 Deployment rook-ceph-osd-2 
 ReplicaSet rook-ceph-crashcollector-node-1-7685f96cc8 
 ReplicaSet rook-ceph-crashcollector-node-2-5dd5db9895 
 ReplicaSet rook-ceph-crashcollector-node-2-f65d8bc89 
 ReplicaSet rook-ceph-crashcollector-node-3-55668b799d 
 ReplicaSet rook-ceph-crashcollector-node-3-7df4cb97fb 
 ReplicaSet rook-ceph-mds-rook-ceph-ceph-fs-a-6649855745 
 ReplicaSet rook-ceph-mds-rook-ceph-ceph-fs-b-7b6cd7dc47 
 ReplicaSet rook-ceph-mgr-a-64659c8d4f 
 ReplicaSet rook-ceph-mon-a-669455ccb8 
 ReplicaSet rook-ceph-mon-b-7d87d7566c 
 ReplicaSet rook-ceph-mon-c-67c64f98d6 
 ReplicaSet rook-ceph-osd-0-b99646748 
 ReplicaSet rook-ceph-osd-1-857766f74b 
 ReplicaSet rook-ceph-osd-2-679d9cf649 
 StatefulSet rook-ceph-ceph-tools 
 Job rook-ceph-osd-prepare-node-1 
 Job rook-ceph-osd-prepare-node-2 
 Job rook-ceph-osd-prepare-node-3 

Excepting  StatefulSet rook-ceph-ceph-tools  which can be fixed easily, the rest are coming mostly from operators.

**Comment by travisn** [comment]
CIS - 5.4.1 states that it is preferred to use files instead of env vars in case the pod were to inadvertently log its environment. While this is a valid concern, we are not aware of any instances of the ceph pods actually logging their secrets. If you find any instances of this happening, we will fix them. But to change the general design of using env vars would be a big undertaking that I don't see being done unless there is more evidence of a real issue.

**Comment by travisn** [comment]
#11331 is the first step in this direction, will work on additional improvements as well.
