### ISSUE TITLE
Have a proper uninstall functionality

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#10993]
**Is this a bug report or feature request?**
* Feature Request
There is no proper methods for complete uninstall of rook-ceph cluster,
We do support it in docs https://github.com/rook/rook/blob/master/design/ceph/ceph-cluster-cleanup.md#cleanup-job-spec https://rook.io/docs/rook/latest/Storage-Configuration/ceph-teardown/#delete-the-data-on-hosts

But it never automated the job creation for deleting and wiping up the data.

I would recommend creating a uninstall CR or a single job for this.

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
Are you referring to the cleanupPolicy with the `yes-really-destroy-data`? It's documented [here](https://rook.io/docs/rook/latest/Storage-Configuration/ceph-teardown/#delete-the-cephcluster-crd), so we should be already covered for this automation. 

Although a related thought is that the krew plugin could have a command that force deletes a cluster, removes finalizers, etc.

**Comment by parth-gr** [comment]
https://rook.io/docs/rook/latest/Storage-Configuration/ceph-teardown/#zapping-devices
I can't see these steps any where in the repo

**Comment by travisn** [comment]
It's a bit higher on the page, around this:
WARNING: DATA WILL BE PERMANENTLY DELETED AFTER DELETING THE CephCluster CR WITH cleanupPolicy.

**Comment by parth-gr** [comment]
> It's a bit higher on the page, around this: WARNING: DATA WILL BE PERMANENTLY DELETED AFTER DELETING THE CephCluster CR WITH cleanupPolicy.

Thnkx @travisn I see this job it runs `ceph clean` on all nodes,

But how about 
```
DISK="/dev/sdX"

# Zap the disk to a fresh, usable state (zap-all is important, b/c MBR has to be clean)
sgdisk --zap-all $DISK

# Wipe a large portion of the beginning of the disk to remove more LVM metadata that may be present
dd if=/dev/zero of="$DISK" bs=1M count=100 oflag=direct,dsync

# SSDs may be better cleaned with blkdiscard instead of dd
blkdiscard $DISK

# Inform the OS of partition table changes
partprobe $DISK

```

These cmds, I can't see if we run them

**Comment by travisn** [comment]
The implementation of disk cleanup is found [here](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/cleanup/disk.go). It doesn't run those exact commands from the cleanup docs though.

**Comment by parth-gr** [comment]
@travisn 
Continuing the discussion here with you,

>The implementation of disk cleanup is found [here](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/cleanup/disk.go). It doesn't run those exact commands from the cleanup docs though.

Should we add the [Zapping disk ](https://rook.github.io/docs/rook/v1.10/Getting-Started/ceph-teardown/#zapping-devices)steps also for the clean-up, as this is something we propose to the users when the data on the host is not deleted.

Second thing:
There can be any specific reason for a particular disk not being cleaned up,

If someone is on bare metal and uses these steps probably it would be sufficient, right.
https://access.redhat.com/articles/6525111

**Comment by travisn** [comment]
We don't need the full list of steps from the upstream cleanup doc since the job is intended to do some very specific cleanup depending on the scenario, detect if it's a raw or lvm OSD and do the proper cleanup, etc. 

But one shortcoming of the cleanup job is that it only wipes disks that are under `/dev` from a host-based install. As seen in the method [cleanupJobTemplateSpec()](https://github.com/rook/rook/blob/2965373ea9b45a475222a84c17fd4fb9008ffb03/pkg/operator/ceph/cluster/cleanup.go#L143-L171), only the `/dev` and dataDirHostPath are mounted to the pod for cleanup. This means that OSDs from PVs would **not** be wiped by the cleanup job. The cleanup steps to wipe local PVs would still need to be done separately from the cleanup jobs. Neither do I see in that downstream doc the steps to wipe a disk from a local PV.

**Comment by parth-gr** [comment]
> We don't need the full list of steps from the upstream cleanup doc since the job is intended to do some very specific cleanup depending on the scenario, detect if it's a raw or lvm OSD and do the proper cleanup, etc.
> 
> But one shortcoming of the cleanup job is that it only wipes disks that are under `/dev` from a host-based install. As seen in the method [cleanupJobTemplateSpec()](https://github.com/rook/rook/blob/2965373ea9b45a475222a84c17fd4fb9008ffb03/pkg/operator/ceph/cluster/cleanup.go#L143-L171), only the `/dev` and dataDirHostPath are mounted to the pod for cleanup. This means that OSDs from PVs would **not** be wiped by the cleanup job. The cleanup steps to wipe local PVs would still need to be done separately from the cleanup jobs. Neither do I see in that downstream doc the steps to wipe a disk from a local PV.

Should it need a separate job for local PVC or just an additional doc step for this cleanup?

**Comment by travisn** [comment]
IIRC we decided not to launch a cleanup job for the PVs since 1) they might not need cleanup (e.g. ebs or other cloud volumes), and 2) even if we wiped the disk there might be other cleanup steps (e.g. cleanup a symlink for LSO). 

@sp98 For LSO, there is documentation for cleaning up the PVs, correct? In that case, we should just point them to LSO cleanup guide.

**Comment by parth-gr** [comment]
> IIRC we decided not to launch a cleanup job for the PVs since 1) they might not need cleanup (e.g. ebs or other cloud volumes), and 2) even if we wiped the disk there might be other cleanup steps (e.g. cleanup a symlink for LSO).
> 
> @sp98 For LSO, there is documentation for cleaning up the PVs, correct? In that case, we should just point them to LSO cleanup guide.

@travisn 
Are you telling about this step,
```
8) Remove the LocalVolume resources (if any).
Use the following steps to remove the LocalVolume resources that were used to provision the PVs in the current or previous OpenShift Data Foundation version. Also, ensure that these resources are not being used by other tenants on the cluster.

For each of the local volumes, do the following:
i. Identify the LocalVolume and the corresponding StorageClassName being used by OpenShift Data Foundation.
ii. Set the variable LV to the name of the LocalVolume and variable SC to the name of the StorageClass.
For example:

[Raw](https://access.redhat.com/articles/6525111#)
$ LV=localblock
$ SC=localblock
```

This was there in the doc I see

**Comment by travisn** [comment]
Yes, that should do it.
