### ISSUE TITLE
Does Rook CephFS shared file access from multiple writers require file locking?

### ISSUE THREAD

**Issue by jfathman** [rook/rook#11009]
I have Rook CephFS working on a three node microk8s cluster.  I can write and read a shared file from any of the three cluster nodes.

Does Rook CephFS serialize write access to the shared file, or do I need to add application level file locking to prevent write contention?

**Comment by travisn** [comment]
@jfathman The CephFS volumes are safe to share from multiple clients in RWX mode, this is what it's design specifically for, to avoid corruption. See also the Ceph docs on [CephFS](https://docs.ceph.com/en/latest/cephfs/).
