### ISSUE TITLE
unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory

### ISSUE THREAD

**Issue by Tomor1984** [rook/rook#11015]
### Discussed in https://github.com/rook/rook/discussions/11014

<div type='discussions-op-text'>

<sup>Originally posted by **Tomor1984** September 19, 2022</sup>
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  rbd:
    monitors:
      - '10.97.25.174:6789'
      - '10.105.228.58:6789'
      - '10.107.57.169:6789'
    pool: rbd
    image: foo
    fsType: ext4
    readOnly: true
    user: admin
    secretRef:
      name: ceph-secret
    keyring: /etc/ceph/keyring
  persistentVolumeReclaimPolicy: Recycle
![image](https://user-images.githubusercontent.com/64009485/190969033-15357139-d813-4258-9898-84341b41c82c.png)

---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
data:
  key: QVFEZ1ZQOWl1T2dDQmhBQWRzeURQKzM5ZjByaTJuXXXXXXXXXXX
![image](https://user-images.githubusercontent.com/64009485/190969778-c12b3c1a-c75f-4a3d-a88a-9a85b718241c.png)

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.0
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
![image](https://user-images.githubusercontent.com/64009485/190969430-860bb8c6-0673-408f-a74e-321bcb74a409.png)
![image](https://user-images.githubusercontent.com/64009485/190969506-8b33821a-1cfa-466e-99f4-3997a7d7cfb8.png)

</div>

**Comment by Madhu-1** [comment]
Please refer to https://www.rook.io/docs/rook/v1.9/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/#static-provisioning for static pvc. You need to alter driverName and clusterID and other things as per your requirement and also the current one you are using is too old and not supported/tested with Rook.

**Comment by Tomor1984** [comment]
> 需要更改[静态](https://www.rook.io/docs/rook/v1.9/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/#static-provisioning)pvc.io/docs/rook.io/docs/rook/v1.9/ceph-csi-drivers/#static-provision 。创建您可以创建您的目录[和](https://github.com/rook/rook/tree/master/deploy/examples/csi)）的版本太旧，并且不受 Rook 支持/测试。

Thanks, I'll try
