### ISSUE TITLE
Allow Updates to Cluster CRD for dynamic storage

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1101]
It would be nice to be able to change certain properties about the cluster on the fly.
What should be allowed to be updated in the cluster CRD?

I was thinking for the first step about `monCount` to be updatable.

**Comment by jpds** [comment]
Another thing I would like is to have the static hosts/devices list to be updatable. Right now I work around this by `useAllNodes` and `useAllDevices` to `true` and making sure by block devices are OK to wipe.

**Comment by travisn** [comment]
This would be great to put in a design document under /design folder. Deciding what is updateable is definitely an explicit decision. Some properties can be updated, while others will be ignored if updated. It would be good to open a separate ticket for each of the properties that we plan to update.

Here is just a sample of thoughts on the properties.

Properties we absolutely need to be updateable:
- `versionTag`: Will trigger an upgrade to the software.
- `nodes`: Need to add new nodes

Properties we might consider updating: 
- `hostNetwork`: While it would be possible to re-create pods with this changed setting, it likely isn't worth the dev effort unless there is a clear scenario for changing the setting.
- `placement`: could be updated, but perhaps an update would only apply to new pods being created. At least for OSD pods, it would be disruptive if you changed the placement scheme.
- `deviceFilter`: Apply only to new OSDs. Or should existing OSD pods be re-created to pick up the setting?

Not updateable:
- `dataDirHostPath`

**Comment by jpds** [comment]
Another thing that could be useful here is increasing the size of a replicated pool.

**Comment by jbw976** [comment]
Adding this to the 0.7 milestone as it fits within the theme of "adding / removing nodes and disk drives (lifecycle issues, failures, etc.)".  We should get a design written up for this soon.

**Comment by galexrt** [comment]
With changes made to the health check in https://github.com/rook/rook/commit/e7d20647aa120dda0145a116b89943c83315f55b, updating the `placement` is now possible.

**Comment by dimm0** [comment]
Are we any closer to adding nodes to an existing cluster? 😊

**Comment by jbw976** [comment]
Yes @dimm0, I need to incorporate the feedback on the design in #1248 then I will start on the implementation.  Those will happen as soon as I get my bug fixes in for an upcoming 0.6.1 minor release, such as #1195.  Thanks for your patience! :)
