### ISSUE TITLE
What's wrong?

### ISSUE THREAD

**Issue by lovese** [rook/rook#11026]
Install ROOK1.10.1, check csi-rbdplugin error, will this affect rook?

k8s version: 1.23.8
rook: 1.10.1
kernel version: 3.10.0-1160.76.1.el7.x86_64
os:  centos7.9

![image](https://user-images.githubusercontent.com/13268438/191245472-5aab0627-9e92-439e-8738-ab567768a7e0.png)

**Comment by lovese** [comment]
Prompt to pull the image failed

**Comment by subhamkrai** [comment]
> Prompt to pull the image failed

@lovese can you describe the event of one of the failing pods?

**Comment by lovese** [comment]
Thank you ,just Internet problem.
