### ISSUE TITLE
ceph-spec: CR has changed for "ceph-filesystem" - MetadaServer ActiveCount changed in a continous loop

### ISSUE THREAD

**Issue by quetdn** [rook/rook#11027]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Active MDS count changes every some minutes

**Expected behavior:**
Active MDS remains constant

**How to reproduce it (minimal and precise):**

ROOK 1.9.9 Ceph: Pacific 
Upgrade Ceph to Quincy. Explained behavior started. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

Sample behaviour: 
**********************************************************************************************************************************************
2022-09-20 17:32:28.014271 I | ceph-spec: CR has changed for "ceph-filesystem". diff=  v1.FilesystemSpec{
  	... // 2 identical fields
  	PreservePoolsOnDelete:      false,
  	PreserveFilesystemOnDelete: false,
  	MetadataServer: v1.MetadataServerSpec{
- 		ActiveCount:   3,
+ 		ActiveCount:   5,
  		ActiveStandby: true,
  		Placement:     {NodeAffinity: &{RequiredDuringSchedulingIgnoredDuringExecution: &{NodeSelectorTerms: {{MatchExpressions: {{Key: "kubernetes.io/hostname", Operator: "Exists"}}}}}}},
  		... // 6 identical fields
  	},
  	Mirroring:   nil,
  	StatusCheck: {},
  }
2022-09-20 17:32:31.151173 I | ceph-spec: CR has changed for "ceph-filesystem". diff=  v1.FilesystemSpec{
  	... // 2 identical fields
  	PreservePoolsOnDelete:      false,
  	PreserveFilesystemOnDelete: false,
  	MetadataServer: v1.MetadataServerSpec{
- 		ActiveCount:   5,
+ 		ActiveCount:   3,
  		ActiveStandby: true,
  		Placement:     {NodeAffinity: &{RequiredDuringSchedulingIgnoredDuringExecution: &{NodeSelectorTerms: {{MatchExpressions: {{Key: "kubernetes.io/hostname", Operator: "Exists"}}}}}}},
  		... // 6 identical fields
  	},
  	Mirroring:   nil,
  	StatusCheck: {},
  }
2022-09-20 17:32:35.822387 I | ceph-spec: parsing mon endpoints: i=10.107.249.71:6789,g=10.100.43.18:6789,a=10.109.109.155:6789
2022-09-20 17:32:35.822424 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v17.2.3-20220805...
2022-09-20 17:32:37.117350 I | ceph-spec: detected ceph image version: "17.2.3-0 quincy"
2022-09-20 17:32:40.709426 I | ceph-file-controller: start running mdses for filesystem "ceph-filesystem"
2022-09-20 17:32:41.593249 I | ceph-spec: CR has changed for "ceph-filesystem". diff=  v1.FilesystemSpec{
  	... // 2 identical fields
  	PreservePoolsOnDelete:      false,
  	PreserveFilesystemOnDelete: false,
  	MetadataServer: v1.MetadataServerSpec{
- 		ActiveCount:   3,
+ 		ActiveCount:   5,
  		ActiveStandby: true,
  		Placement:     {NodeAffinity: &{RequiredDuringSchedulingIgnoredDuringExecution: &{NodeSelectorTerms: {{MatchExpressions: {{Key: "kubernetes.io/hostname", Operator: "Exists"}}}}}}},
  		... // 6 identical fields
  	},
***********************************************************************************************************************************************

* Operator's logs

* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

[rook@rook-ceph-tools-fccf4459b-kfqqg /]$ ceph health
HEALTH_OK
[rook@rook-ceph-tools-fccf4459b-kfqqg /]$ ceph -s
  cluster:
    id:     5035b7d0-5e11-4af2-be63-2b54464cfc95
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,g,i (age 8h)
    mgr: a(active, since 8h)
    mds: 5/5 daemons up, 8 standby, 5 hot standby
    osd: 14 osds: 14 up (since 8h), 13 in (since 2d)
 
  data:
    volumes: 2/2 healthy
    pools:   7 pools, 289 pgs
    objects: 774.92k objects, 2.5 TiB
    usage:   7.5 TiB used, 11 TiB / 18 TiB avail
    pgs:     288 active+clean
             1   active+clean+scrubbing+deep
 
  io:
    client:   6.2 KiB/s rd, 77 KiB/s wr, 10 op/s rd, 8 op/s wr

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): 
Description:	Ubuntu 22.04.1 LTS

* Kernel (e.g. `uname -a`): 
Linux k8s2700 5.15.0-47-generic#51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration: Baremetal 
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.9.0-alpha.0.189.gbb5812316
go: go1.17.9
* Storage backend version (e.g. for ceph do `ceph -v`): 
[root@rook-ceph-mds-ceph-filesystem-i-574d4b584-w8w6p ceph]# ceph -v
ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)

$ kubectl -n $ROOK_CLUSTER_NAMESPACE get deployments -l rook_cluster=$ROOK_CLUSTER_NAMESPACE -o jsonpath='{range .items[*]}{.metadata.name}{"  \treq/upd/avl: "}{.spec.replicas}{"/"}{.status.updatedReplicas}{"/"}{.status.readyReplicas}{"  \tceph-version="}{.metadata.labels.ceph-version}{"\n"}{end}'
rook-ceph-crashcollector-k8s2620  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-crashcollector-k8s2700  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-crashcollector-k8s3550h  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-crashcollector-k8s8750h  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-crashcollector-k8snuc  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-a  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-b  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-c  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-d  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-e  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-f  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-g  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-h  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-i  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-ceph-filesystem-j  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-cephfs-volumes-a  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-cephfs-volumes-b  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-cephfs-volumes-c  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mds-cephfs-volumes-d  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mgr-a  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mon-a  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mon-g  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-mon-i  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-nfs-cluster-nfs-a  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-0  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-1  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-10  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-11  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-12  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-13  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-2  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-3  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-4  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-5  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-6  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-7  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-8  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0
rook-ceph-osd-9  	req/upd/avl: 1/1/1  	ceph-version=17.2.3-0

* Kubernetes version (use `kubectl version`):
clientVersion:
  buildDate: "2022-09-14T19:49:27Z"
  compiler: gc
  gitCommit: e4d4e1ab7cf1bf15273ef97303551b279f0920a9
  gitTreeState: clean
  gitVersion: v1.25.1
  goVersion: go1.19.1
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-09-14T19:42:30Z"
  compiler: gc
  gitCommit: e4d4e1ab7cf1bf15273ef97303551b279f0920a9
  gitTreeState: clean
  gitVersion: v1.25.1
  goVersion: go1.19.1
  major: "1"
  minor: "25"
  platform: linux/amd64

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
[cluster.txt](https://github.com/rook/rook/files/9610321/cluster.txt)
[Operator-log.txt](https://github.com/rook/rook/files/9610322/Operator-log.txt)

**Comment by travisn** [comment]
Are you sure you don't have a rogue script that is updating the filesystem CR? Rook really doesn't ever update the CR specs automatically. Rook only responds to the CR updates and only updates status on the CRs.

**Comment by quetdn** [comment]
No, I do not have anything that changes the CR. I tested that when I manually change the ActiveCount the behavior is the same. Something changes this value again constantly. But I do not know what is changing it. The operator detects those changes and starts creating or removing MDS pods.
In fact, with Pacific the number of MDS was stable, and after migration to Quincy that behavior started. 
I have two CephFilesystem Pools, and the other one is working fine.

**Comment by travisn** [comment]
How are you changing the value? Are you using a helm chart, or applying a yaml, or kubectl edit, or something else?

**Comment by quetdn** [comment]
I edit with Lens or kubectl edit  cephfilesystem.ceph.rook.io -n rook-ceph ceph-filesystem

**Comment by quetdn** [comment]
After your comment, I was looking for another way to change the value. 
I did with kubectl patch:
kubectl -n rook-ceph patch  cephfilesystems ceph-filesystem --type=merge -p "{\"spec\": {\"metadataServer\": {\"activeCount\": 1}}}"

But, that happened after some seconds: 
2022-09-22 09:22:18.525688 I | ceph-spec: CR has changed for "ceph-filesystem". diff=  v1.FilesystemSpec{
  	... // 2 identical fields
  	PreservePoolsOnDelete:      false,
  	PreserveFilesystemOnDelete: false,
  	MetadataServer: v1.MetadataServerSpec{
- 		ActiveCount:   1,
+ 		ActiveCount:   4,
  		ActiveStandby: true,
  		Placement:     {NodeAffinity: &{RequiredDuringSchedulingIgnoredDuringExecution: &{NodeSelectorTerms: {{MatchExpressions: {{Key: "kubernetes.io/hostname", Operator: "Exists"}}}}}}},
  		... // 6 identical fields
  	},
  	Mirroring:   nil,
  	StatusCheck: {},
  }
2022-09-22 09:22:21.545059 I | ceph-spec: CR has changed for "ceph-filesystem". diff=  v1.FilesystemSpec{
  	... // 2 identical fields
  	PreservePoolsOnDelete:      false,
  	PreserveFilesystemOnDelete: false,
  	MetadataServer: v1.MetadataServerSpec{
- 		ActiveCount:   4,
+ 		ActiveCount:   3,
  		ActiveStandby: true,
  		Placement:     {NodeAffinity: &{RequiredDuringSchedulingIgnoredDuringExecution: &{NodeSelectorTerms: {{MatchExpressions: {{Key: "kubernetes.io/hostname", Operator: "Exists"}}}}}}},
  		... // 6 identical fields
  	},
  	Mirroring:   nil,
  	StatusCheck: {},
  }
2022-09-22 09:22:24.681660 I | ceph-spec: CR has changed for "ceph-filesystem". diff=  v1.FilesystemSpec{
  	... // 2 identical fields
  	PreservePoolsOnDelete:      false,
  	PreserveFilesystemOnDelete: false,
  	MetadataServer: v1.MetadataServerSpec{
- 		ActiveCount:   3,
+ 		ActiveCount:   4,
  		ActiveStandby: true,
  		Placement:     {NodeAffinity: &{RequiredDuringSchedulingIgnoredDuringExecution: &{NodeSelectorTerms: {{MatchExpressions: {{Key: "kubernetes.io/hostname", Operator: "Exists"}}}}}}},
  		... // 6 identical fields
  	},
  	Mirroring:   nil,
  	StatusCheck: {},

**Comment by travisn** [comment]
That's very bizarre. Do you have multiple clusters with this issue, or just this one?

**Comment by quetdn** [comment]
Only one cluster.

**Comment by quetdn** [comment]
Following this note: 
"Ceph NFS management with the Rook mgr module enabled has a breaking regression with the Ceph Quincy v17.2.1 release"
I have disabled mgr module. 
**The problem disappeared**.  
mds_autoscaler is on, and as documented:
"The MDS Autoscaler Module monitors file systems to ensure sufficient MDS daemons are available. It works by adjusting the placement specification for the orchestrator backend of the MDS service" 
Could it be because MDS Autoscaler and orchestrator were doing those changes?
