### ISSUE TITLE
Raw partitions get skipped by rook-discover

### ISSUE THREAD

**Issue by dkeven** [rook/rook#11038]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Raw partitions aren't picked up by rook-discover, when `useAllDevices` is set to true

**Expected behavior:**
Raw partitions should be picked up by rook-discover, according to the documentation.

**How to reproduce it (minimal and precise):**

Plug in a disk with a single, unformatted partition (In my case it's a SSD with a raw GPT partition), and then wait for an OSD to be created on that partition, but nothing happens.

**Logs to submit**:
The raw partition in the device list is `dfa1`, here is the output of `fdisk -l`:

```
# fdisk -l /dev/dfa
Disk /dev/dfa: 2.93 TiB, 3200000196608 bytes, 6250000384 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 32768 bytes
Disklabel type: gpt
Disk identifier: 6BEE73E7-F3D8-5641-8A5E-4048E16DF439

Device     Start        End    Sectors  Size Type
/dev/dfa1   2048 6250000350 6249998303  2.9T Linux filesystem
```

And here is the output of `lsblk -f`:

```
# lsblk -f /dev/dfa
NAME   FSTYPE LABEL UUID FSAVAIL FSUSE% MOUNTPOINT
dfa
`-dfa1
# lsblk -f /dev/dfa1
NAME FSTYPE LABEL UUID FSAVAIL FSUSE% MOUNTPOINT
dfa1
```

Here is the log of the corresponding `rook-discover` daemon pod, I've only retained parts that I think is necessary:

```
2022-09-22 09:06:03.832293 D | rook-discover: localdevice "dfa1": &{Name:dfa1 Parent:dfa HasChildren:false DevLinks: Size:3199999131136 UUID: Serial: Type:part Rotational:false Readonly:false Partitions:[] Filesystem: Vendor: Model: WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/dfa1 KernelName:dfa1 Encrypted:false}
2022-09-22 09:06:03.832305 I | rook-discover: localdevices: "sda1, sda2, dfa1"
2022-09-22 09:06:03.832312 I | rook-discover: Getting ceph-volume inventory information
2022-09-22 09:06:03.832324 D | exec: Running command: ceph-volume inventory --format json
2022-09-22 09:07:33.804281 I | rook-discover: available devices: []
2022-09-22 09:07:33.827225 D | rook-discover: last devices []
2022-09-22 09:07:33.827306 I | rook-discover: using the regular expressions ["(?i)dm-[0-9]+" "(?i)rbd[0-9]+" "(?i)nbd[0-9]+"]
2022-09-22 09:07:33.852424 D | rook-discover: udevadm monitor: monitor will print the received events for:
2022-09-22 09:07:33.852663 D | rook-discover: udevadm monitor: UDEV - the event which udev sends out after rule processing
2022-09-22 09:07:33.852738 D | rook-discover: udevadm monitor: KERNEL - the kernel uevent
2022-09-22 09:07:33.852764 D | rook-discover: udevadm monitor:
```

We can notice from the log that `dfa1` was discovered but filtered out eventually, so the `rook-discover` did not update the configmap to notify `rook-operator`, thus an OSD was not created as expected.

I looked into the source code of `rook-discover`, and found that every localdevice that is of type `"part"` is filtered out, I don't understand why, as raw partitions is also valid for OSDs by design.

https://github.com/rook/rook/blob/41acfe38d53b406885452844f5589bcf34c18363/pkg/daemon/discover/discover.go#L437-L439

Also, in the discover code, partitions of disks are retrieved:
https://github.com/rook/rook/blob/41acfe38d53b406885452844f5589bcf34c18363/pkg/daemon/discover/discover.go#L441-L445

But before this, disks with partitions are already filtered out by:
https://github.com/rook/rook/blob/41acfe38d53b406885452844f5589bcf34c18363/pkg/clusterd/disk.go#L98-L100
This operation seems unnecessary.

**Comment by sp98** [comment]
> I looked into the source code of `rook-discover`, and found that every localdevice that is of type `"part"` is filtered out, I don't understand why, as raw partitions is also valid for OSDs by design.

Raw partitions are supported by design.  The code snippet here only skips the partitions (with `part` label) but they get added in the `LocalDisk` struct intitalized in this method [here](https://github.com/rook/rook/blob/dbb98224bcef0a542d1df18c813e199eb16a01d3/pkg/daemon/discover/discover.go#L453)

So this behavior with this code snippet correct, its not filtering out partitions.

**Comment by sp98** [comment]
@dkeven Can you please share the complete operator logs and also the logs from osd prepare pods. Thanks.

**Comment by sp98** [comment]
> Plug in a disk with a single, unformatted partition (In my case it's a SSD with a raw GPT partition), and then wait for an OSD to be created on that partition, but nothing happens.

were there any osds running before new disk was plugged in?

**Comment by dkeven** [comment]
> > Plug in a disk with a single, unformatted partition (In my case it's a SSD with a raw GPT partition), and then wait for an OSD to be created on that partition, but nothing happens.
> 
> were there any osds running before new disk was plugged in?

Yeah, there is already an OSD running on a different HDD.

**Comment by sp98** [comment]
> > > Plug in a disk with a single, unformatted partition (In my case it's a SSD with a raw GPT partition), and then wait for an OSD to be created on that partition, but nothing happens.
> > 
> > 
> > were there any osds running before new disk was plugged in?
> 
> Yeah, there is already an OSD running on a different HDD on the same node(and other nodes, too)

Thanks. I think I'm able to reproduce this issue locally and what you mentioned in the description might be the correct root cause. I'll check a bit more and update you.

**Comment by dkeven** [comment]
> 
> 
> 
> > I looked into the source code of `rook-discover`, and found that every localdevice that is of type `"part"` is filtered out, I don't understand why, as raw partitions is also valid for OSDs by design.
> 
> Raw partitions are supported by design.  The code snippet here only skips the partitions (with `part` label) but they get added in the `LocalDisk` struct intitalized in this method [here](https://github.com/rook/rook/blob/dbb98224bcef0a542d1df18c813e199eb16a01d3/pkg/daemon/discover/discover.go#L453)
> 
> So this behavior with this code snippet correct, its not filtering out partitions. 

Correct me if I'm wrong, but before all of this, all disks that have partitions within it were alreay filtered out in
 https://github.com/rook/rook/blob/41acfe38d53b406885452844f5589bcf34c18363/pkg/clusterd/disk.go#L98-L100

Same with our target partition's parent disk, and there's even a followed logging, which makes it more like an intentional behavior.

Also, even if our target partition's parent disk managed to survive, it will be marked as not empty, and I don't think rook operator will use a not empty disk, either, see:

https://github.com/rook/rook/blob/41acfe38d53b406885452844f5589bcf34c18363/pkg/daemon/discover/discover.go#L455

https://github.com/rook/rook/blob/41acfe38d53b406885452844f5589bcf34c18363/pkg/clusterd/disk.go#L49
