### ISSUE TITLE
build broken on master (as of 2965373) by github.com/hashicorp/vault/sdk

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#11045]
```bash
$ go version
go version go1.18.6 linux/amd64
```

```
go: downloading github.com/tencentcloud/tencentcloud-sdk-go v3.0.171+incompatible
go: github.com/libopenstorage/secrets@v0.0.0-20220710000753-f1eb4e951e29 requires
	github.com/hashicorp/vault@v1.4.2 requires
	github.com/hashicorp/go-kms-wrapping@v0.5.1 requires
	github.com/hashicorp/vault/sdk@v0.1.14-0.20191229212425-c478d00be0d6: invalid version: unknown revision c478d00be0d6
```

**Comment by travisn** [comment]
There is a tip in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#build) on how to set a proxy to help with this error. This error isn't happening in the CI, so it seems local to your build.

**Comment by jhoblitt** [comment]
Eh, interesting. I thought that if `GOPROXY` was unset that it defaulted to the google proxy.  Setting the env var does get the build working but the that/ref does not exist in the source repo.  The build is only working because the google proxy, thus far, doesn't expire content.

**Comment by travisn** [comment]
Good to hear it's building for you now, but we should certainly look into fixing this issue.
