### ISSUE TITLE
 RADOS permission denied (error connecting to the cluster) . 

### ISSUE THREAD

**Issue by stronger123456789** [rook/rook#11049]
Who can help to analysis this? 

]#kubectl -n rook-ceph-external  get CephCluster 
NAME                 DATADIRHOSTPATH   MONCOUNT   AGE   PHASE       MESSAGE                                     HEALTH
rook-ceph-external                                36h   Connected   Failed to configure external ceph cluster   HEALTH_ERR
[root@dc8-r2-srv31-init external_cluster]#                       kubectl -n rook-ceph get service rook-ceph-rgw-my-store

[root@dc8-r2-srv31-init external_cluster]# kubectl -n rook-ceph logs -l app=rook-ceph-operator
2022-09-24 15:10:27.877963 W | op-mon: failed to check mon health. failed to get external mon quorum status: mon quorum status failed: [errno 13] RADOS permission denied (error connecting to the cluster)
. 
2022-09-24 15:11:00.873120 E | ceph-cluster-controller: failed to get ceph status. failed to get status. . [errno 13] RADOS permission denied (error connecting to the cluster): exit status 13
2022-09-24 15:11:13.136589 W | op-mon: failed to check mon health. failed to get external mon quorum status: mon quorum status failed: [errno 13] RADOS permission denied (error connecting to the cluster)
. 
2022-09-24 15:11:58.394357 W | op-mon: failed to check mon health. failed to get external mon quorum status: mon quorum status failed: [errno 13] RADOS permission denied (error connecting to the cluster)
. 
2022-09-24 15:12:01.180426 E | ceph-cluster-controller: failed to get ceph status. failed to get status. . [errno 13] RADOS permission denied (error connecting to the cluster): exit status 13
2022-09-24 15:12:43.652253 W | op-mon: failed to check mon health. failed to get external mon quorum status: mon quorum status failed: [errno 13] RADOS permission denied (error connecting to the cluster)

**Comment by microyahoo** [comment]
Your ceph cluster is `HEALTH_ERR`, so you should make sure ceph cluster is OK/WARN before to create object store.

**Comment by stronger123456789** [comment]
Thanks, yes my ceph cluster if OK,

**Comment by parth-gr** [comment]
Your ceph cluster and its connection to external rook looks in bad state,
Do you see the keyring file present in ceph cluster ,check in /etc/ceph/ directory

Can you describe the scenario that you are trying to achieve looks like you are creating rgw over external-cluster.

**Comment by stronger123456789** [comment]
Hi Author,
     Yes, I can see the keyring  under in /etc/ceph directory.

]# ls -l
total 36
-rw-rw-r-- 1 ceph ceph 1302 Aug 19 15:59 ceph-dashboard.crt
-rw------- 1 ceph ceph 1704 Aug 19 15:59 ceph-dashboard.key
-r-------- 1 ceph ceph  151 Aug 19 15:47 ceph.client.admin.keyring
-rw------- 1 ceph ceph  131 Aug 19 16:02 ceph.client.crash.keyring
-rw-r--r-- 1 ceph ceph  489 Aug 19 15:46 ceph.conf
-r-------- 1 ceph ceph  142 Aug 19 15:48 ceph.mgr.dc8-r1-srv1.keyring
-r-------- 1 ceph ceph  142 Aug 19 15:48 ceph.mgr.dc8-r1-srv3.keyring
-r-------- 1 ceph ceph  142 Aug 19 15:48 ceph.mgr.dc8-r1-srv5.keyring
-r-------- 1 root root   77 Aug 19 15:46 ceph.mon.keyring

**Comment by parth-gr** [comment]
Are you able to run ceph cmds in the ceph cluster??
ceph -s, etc

**Comment by stronger123456789** [comment]
Yes, the ceph command is ok

# ceph mon stat
e1: 3 mons at {dc8-r1-srv1=[v2:10.252.11.61:3300/0,v1:10.252.11.61:6789/0],dc8-r1-srv3=[v2:10.252.11.63:3300/0,v1:10.252.11.63:6789/0],dc8-r1-srv5=[v2:10.252.11.65:3300/0,v1:10.252.11.65:6789/0]}, election epoch 54, leader 0 dc8-r1-srv1, quorum 0,1,2 dc8-r1-srv1,dc8-r1-srv3,dc8-r1-srv5
***@***.*** ceph]# ceph -s
  cluster:
    id:     4849e591-27f7-477b-9544-7e5bcc02362e
    health: HEALTH_OK
  services:
    mon: 3 daemons, quorum dc8-r1-srv1,dc8-r1-srv3,dc8-r1-srv5 (age 6d)
    mgr: dc8-r1-srv3(active, since 6d), standbys: dc8-r1-srv1, dc8-r1-srv5
    osd: 72 osds: 72 up (since 6d), 72 in (since 6d)
    rgw: 3 daemons active (dc8-r1-srv2.rgw0, dc8-r1-srv4.rgw0, dc8-r1-srv6.rgw0)
  data:
    pools:   5 pools, 160 pgs
    objects: 226 objects, 7.5 KiB
    usage:   73 GiB used, 251 TiB / 252 TiB avail
    pgs:     160 active+clean
  io:
    client:   32 KiB/s rd, 0 B/s wr, 31 op/s rd, 21 op/s wr

**Comment by parth-gr** [comment]
`RADOS permission denied (error connecting to the cluster)` didn't give much hint,

Can you also please share describe even of cephcluster,
`kubectl describe cephcluster -nnamespace -o yaml`

**Comment by stronger123456789** [comment]
Hi,
You can check this logs
***@***.*** ~]# kubectl describe pod rook-ceph-operator-7b6b8b87d-txdz9 -n rook-ceph
Name:         rook-ceph-operator-7b6b8b87d-txdz9
Namespace:    rook-ceph
Priority:     0
Node:         dc8-r2-srv11/10.141.2.111
Start Time:   Fri, 23 Sep 2022 02:31:37 +0000
Labels:       app=rook-ceph-operator
              pod-template-hash=7b6b8b87d
Annotations:  cni.projectcalico.org/podIP: 10.2.5.11/32
              cni.projectcalico.org/podIPs: 10.2.5.11/32
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "k8s-pod-network",
                    "ips": [
                        "10.2.5.11"
                    ],
                    "default": true,
                    "dns": {}
                }]
              kubernetes.io/psp: privileged
Status:       Running
IP:           10.2.5.11
IPs:
  IP:           10.2.5.11
Controlled By:  ReplicaSet/rook-ceph-operator-7b6b8b87d
Containers:
  rook-ceph-operator:
    Container ID:  containerd://1f899cf8f527fe08598709dfd531b64a7907b17299adfe611dca81029f960528
    Image:         rook/ceph:v1.5.10
    Image ID:      ***@***.******@***.***:9326f601f190ad1cf2422520671e2ff6b7c7a4d5712894b71516589e90f7f462>
    Port:          <none>
    Host Port:     <none>
    Args:
      ceph
      operator
    State:          Running
      Started:      Fri, 23 Sep 2022 02:39:20 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      ROOK_CURRENT_NAMESPACE_ONLY:               false
      ROOK_ALLOW_MULTIPLE_FILESYSTEMS:           false
      ROOK_LOG_LEVEL:                            INFO
      ROOK_DISCOVER_DEVICES_INTERVAL:            60m
      ROOK_HOSTPATH_REQUIRES_PRIVILEGED:         false
      ROOK_ENABLE_SELINUX_RELABELING:            true
      ROOK_ENABLE_FSGROUP:                       true
      ROOK_DISABLE_DEVICE_HOTPLUG:               false
      DISCOVER_DAEMON_UDEV_BLACKLIST:            (?i)dm-[0-9]+,(?i)rbd[0-9]+,(?i)nbd[0-9]+
      ROOK_ENABLE_FLEX_DRIVER:                   false
      ROOK_ENABLE_DISCOVERY_DAEMON:              false
      ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS:  5
      NODE_NAME:                                  (v1:spec.nodeName)
      POD_NAME:                                  rook-ceph-operator-7b6b8b87d-txdz9 (v1:metadata.name)
      POD_NAMESPACE:                             rook-ceph (v1:metadata.namespace)
    Mounts:
      /etc/ceph from default-config-dir (rw)
      /var/lib/rook from rook-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-h55c6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  rook-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-config-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
 kube-api-access-h55c6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>

**Comment by parth-gr** [comment]
I am more interested in this output
`kubectl describe cephcluster rook-ceph-external -n rook-ceph-external`

**Comment by stronger123456789** [comment]
Thank you for care:
# kubectl describe cephcluster rook-ceph-external -n rook-ceph-external
Name:         rook-ceph-external
Namespace:    rook-ceph-external
Labels:       <none>
Annotations:  <none>
API Version:  ceph.rook.io/v1
Kind:         CephCluster
Metadata:
  Creation Timestamp:  2022-09-23T02:53:18Z
  Finalizers:
    cephcluster.ceph.rook.io
  Generation:  2
  Managed Fields:
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:crashCollector:
          .:
          f:disable:
        f:external:
          .:
          f:enable:
        f:healthCheck:
    Manager:      kubectl-create
    Operation:    Update
    Time:         2022-09-23T02:53:18Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"cephcluster.ceph.rook.io":
      f:spec:
        f:cephVersion:
        f:cleanupPolicy:
          .:
          f:sanitizeDisks:
        f:dashboard:
        f:disruptionManagement:
        f:healthCheck:
          f:daemonHealth:
        f:logCollector:
        f:mgr:
        f:mon:
        f:monitoring:
        f:network:
          .:
          f:hostNetwork:
          f:provider:
          f:selectors:
        f:removeOSDsIfOutAndSafeToRemove:
        f:security:
          .:
          f:kms:
        f:storage:
          .:
          f:config:
          f:storageClassDeviceSets:
      f:status:
        .:
        f:ceph:
        f:conditions:
        f:message:
        f:phase:
        f:state:
    Manager:         rook
    Operation:       Update
    Time:            2022-09-23T02:53:25Z
  Resource Version:  3071308
  UID:               daa071b1-18e3-49bd-8bcb-58799bedde92
Spec:
  Ceph Version:
  Cleanup Policy:
    Sanitize Disks:
  Crash Collector:
    Disable:  true
  Dashboard:
  Disruption Management:
  External:
    Enable:  true
  Health Check:
    Daemon Health:
      Mon:
        Interval:  45s
      Osd:
      Status:
  Log Collector:
  Mgr:
  Mon:
  Monitoring:
  Network:
    Host Network:                          false
    Provider:
    Selectors:                             <nil>
  Remove OS Ds If Out And Safe To Remove:  false
  Security:
    Kms:
  Storage:
    Config:                     <nil>
    Storage Class Device Sets:  <nil>
Status:
  Ceph:
    Capacity:
    Details:
      Error:
        Message:   failed to get status. . [errno 13] RADOS permission denied (error connecting to the cluster): exit status 13
        Severity:  Urgent
    Health:        HEALTH_ERR
    Last Checked:  2022-09-27T12:25:16Z
  Conditions:
    Last Heartbeat Time:   2022-09-23T02:53:21Z
    Last Transition Time:  2022-09-23T02:53:21Z
    Message:               Attempting to connect to an external Ceph cluster
    Reason:                ClusterConnecting
    Status:                True
    Type:                  Connecting
    Last Heartbeat Time:   2022-09-27T12:25:16Z
    Last Transition Time:  2022-09-23T02:53:25Z
    Message:               Failed to configure external ceph cluster
    Reason:                ClusterConnected
    Status:                False
    Type:                  Connected
  Message:                 Failed to configure external ceph cluster
  Phase:                   Connected
  State:                   Error
Events:                    <none>
***@***.*** ~]#

**Comment by stronger123456789** [comment]
Yes
***@***.*** /]# ceph health detail
HEALTH_OK

**Comment by parth-gr** [comment]
This is the first time you are trying to connect to the external cluster???

Can you check check the communication of mon's with the cluster by sh into them, are the configured correctly with this cluster.

**Comment by stronger123456789** [comment]
I found below error from CEPH dockers.

debug 2022-09-24 16:08:01.106 7f0f856ea700  0 cephx server client.healthchecker:  attempt to reclaim global_id 24693 without presenting ticket
debug 2022-09-24 16:08:01.106 7f0f856ea700  0 cephx server client.healthchecker:  could not verify old ticket

**Comment by kehao95** [comment]
Happened to me, turns out to be the ceph-tools' version lower than the cluster. Fixed by upgrading tools version

**Comment by parth-gr** [comment]
> Happened to me, turns out to be the ceph-tools' version lower than the cluster. Fixed by upgrading tools version

Do you mean the toolbox, I don't think toolbox has any impact on cephcluster

**Comment by sinawic** [comment]
I'm trying to use the rook's `create-external-cluster-resources.py`

as a result I'm getting this
`rados.PermissionDeniedError: [errno 13] RADOS permission denied (error connecting to the cluster)`

anyone got any idea. what can be wrong?

**Comment by parth-gr** [comment]
Where you are running this script, you need to run on top of ceph standalone cluster,
PLease open a seprate issue with the deatils
