### ISSUE TITLE
Add metadata to OSD pod about rotational disks

### ISSUE THREAD

**Issue by umangachapagain** [rook/rook#11059]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
If OSD prepare pod detects rotational disk, label or annotate the OSD pod with that information.

**What is use case behind this feature:**
We want to know if OSDs are using rotational disks or not. Having this metadata as label would allow us to query all OSDs using rotational disks.

**Environment**:

**Comment by parth-gr** [comment]
The operator should self detect if the disk is rotational,
Or user provide this information while providing the disk?

**Comment by sp98** [comment]
`ceph osd tree` output can be used to get this information.  Will that help?

**Comment by travisn** [comment]
I'm assuming ceph commands aren't an option to run directly in this scenario. @umangachapagain?

**Comment by umangachapagain** [comment]
> I'm assuming ceph commands aren't an option to run directly in this scenario. @umangachapagain?

It's not. We can not run ceph commands to get this info. It needs to be on some K8s resource.

**Comment by richardelling** [comment]
caveat: the rotation information delivered to Linux, and subsequent consumers such as ceph, is unreliable. It has the best chance of working for real hardware, but is not 100% correct for all hardware in the universe. For virtual disks, all bets are off.
