### ISSUE TITLE
PVs unable to be attached to the pods

### ISSUE THREAD

**Issue by tayyabjamadar** [rook/rook#11050]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
We have an application that uses cephfs RWX volume, on a couple of nodes the volume is not being attached to pods. Pod events  log says that it is unable to attach or mount volumes with additional info saying timed out waiting for the condition and the given volume already exists, and similar logs are shown by the `csi-cephfs-plugin` container as well. Upon looking at the processes in the container, it seems the `umount` command which is still unmounting the volume from previously deleted pod is in hung state.  

**Expected behavior:**
The volume must get mounted easily

Any help around fixing this issue is appreciated.

**Comment by Madhu-1** [comment]
@tayyabjamadar is your ceph cluster healthy? please share `ceph -s` output

**Comment by tayyabjamadar** [comment]
`  cluster:
    id:     4bf363ae-b772-4a18-ad95-2c071db26e67
    health: HEALTH_ERR
            1 filesystem is degraded
            1 filesystem has a failed mds daemon
            1 filesystem is offline
            insufficient standby MDS daemons available

  services:
    mon: 3 daemons, quorum f,h,i (age 2d)
    mgr: a(active, since 2w)
    mds: 1/2 daemons up (1 failed), 1 hot standby
    osd: 18 osds: 18 up (since 2d), 18 in (since 2d)

  data:
    volumes: 1/2 healthy, 1 failed
    pools:   6 pools, 1344 pgs
    objects: 1.18M objects, 4.4 TiB
    usage:   13 TiB used, 50 TiB / 63 TiB avail
    pgs:     1344 active+clean
  @Madhu-1 `

**Comment by Madhu-1** [comment]
You need to fix the ceph cluster health https://rook.io/docs/rook/v1.9/Troubleshooting/ceph-common-issues/, one ceph health is back to `OK` state things should be back to normal

**Comment by tayyabjamadar** [comment]
Just deleted the fs which was causing the issue, The health state is now OK, but still facing the error with volume attachments

**Comment by Madhu-1** [comment]
try deleting the rook operator pod or csi pods

**Comment by tayyabjamadar** [comment]
Tried with suggested pods restarts, but no luck in that.  This has been resolved after the node host restart, will keep you guys updated if this re-emerges. Thanks

**Comment by tayyabjamadar** [comment]
Closing since not facing anymore will re-open if see this again.
