### ISSUE TITLE
Allow disabling the automatic configuration of `mgr/prometheus/rbd_stats_pools`.

### ISSUE THREAD

**Issue by ikogan** [rook/rook#11056]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently, the Rook operator sets the `mgr/prometheus/rbd_stats_pools` configuration to include any Ceph pool that corresponds to a `CephBlockPool` resource that has `enableRBDStatus: true`. This is generally good but causes problems if Rook's pools are not the only ones in the cluster. If no `CephBlockPool` resources exist, it simply unsets the configuration entirely.

It should be possible to disable managing this item, perhaps in the `CephCluster` resource's `monitoring` property.

**What is use case behind this feature:**
I'm using a Proxmox managed Ceph cluster which has a variety of pools. I set `mgr/prometheus/rbd_stats_pools` manually and include both the Rook managed pools _and_ Proxmox's pools. Right now I would have to define a CephBlockPool for all of Proxmox's pools as well and that's somewhat scary, I don't want two tools managing the same pools.

**Environment**:

- Kubernetes Distribution: Rancher RKE1
- Kubernetes Version: v1.21.12
- Ceph Version: 16.2.9
- Rook Version: 1.10.1

```bash
❯ sudo ceph osd lspools
4 rbd
9 device_health_metrics
10 rbd-capacity
18 clusterfs-capacity_data
19 clusterfs-capacity_metadata
25 k8s-rbd-performance
26 k8s-rbd-capacity
27 cephfs.clusterfs-performance.meta
28 cephfs.clusterfs-performance.data
29 .rgw.root
30 default.rgw.log
31 default.rgw.control
32 default.rgw.meta
```
```bash
❯ sudo ceph config dump
WHO                MASK  LEVEL     OPTION                                 VALUE                                 RO
global                   advanced  osd_pool_default_pg_autoscale_mode     on                                      
  mon                    advanced  auth_allow_insecure_global_id_reclaim  false                                   
  mgr                    advanced  mgr/influx/hostname                    influxdb.mydomain.private             * 
  mgr                    advanced  mgr/influx/password                    _                                     * 
  mgr                    advanced  mgr/influx/port                        443                                   * 
  mgr                    advanced  mgr/influx/ssl                         true                                  * 
  mgr                    advanced  mgr/influx/username                    ceph                                  * 
  mgr                    advanced  mgr/prometheus/rbd_stats_pools         k8s-rbd-capacity,k8s-rbd-performance  * 
  mgr                    advanced  mgr/prometheus/standby_behaviour       default                                 
  mgr                    advanced  mgr/zabbix/identifier                  pve1.mydomain.local                   * 
  mgr                    advanced  mgr/zabbix/zabbix_host                 zabbix.mydomain.private               * 
  mgr                    advanced  mgr/zabbix/zabbix_sender               /usr/bin/zabbix_sender                * 
    mgr.pve1             advanced  mgr/prometheus/server_addr             10.10.0.1                             * 
    mgr.pve2             advanced  mgr/prometheus/server_addr             10.10.0.2                             * 
    mgr.pve3             advanced  mgr/prometheus/server_addr             10.10.0.3                             * 
    mgr.pve4             advanced  mgr/prometheus/server_addr             10.10.0.4                             * 
    mgr.pve5             advanced  mgr/prometheus/server_addr             10.10.0.5                             * 
  osd                    dev       bluestore_fsck_quick_fix_on_mount      true                                    
```

**Comment by parth-gr** [comment]
I didn't understand your feature request,
Are you trying to say you have both kinds of pool in `CephBlockPool` the ceph and the proxmox managed,
And you want ceph pools to be managed and other to be disable?

**Comment by ikogan** [comment]
Rook sets `mgr/prometheus/rbd_stats_pools` to a comma separated list of the names of all `CephBlockPool` resources that have `enableRBDStats = true`. It does not care what was in there before. I believe that a brand new Rook install with 0 `CephBlockPool` resource will always just wipe out `mgr/prometheus/rbd_stats_pools` no matter what was in there before. At the very least, in my cluster, having defined at least _one_ `CephBlockPool` with `enableRBDStats = true` causes Rook to _replace_ all of the pools I've manually added to `mgr/prometheus/rbd_stats_pools` with just that single `CephBlockPool`.

The _only_ way to get _all_ of my pools into `mgr/prometheus/rbd_stats_pools` is to define each one as `CephBlockPool`. There are several downsides to this:

1. I have to make sure that any pool settings I have, like compression, is mirrored correctly in my `CephBlockPool` or Rook will change it. If I have something else managing this pool, they could get into a fight.
2. What happens if I now want to delete this `CephBlockPool` resource? My guess is that Rook will happily delete the underlying pool, which it did not create. This would be quite funny as that would result in the deletion of the Kubernetes cluster that Rook lives in. In effect, Rook would commit suicide.

So, I think a couple of options would be acceptable:

1. Modify the way Rook sets `mgr/prometheus/rbd_stats_pools` to not remove existing entries but only add/remove ones that it manages. This can get tricky, I imagine, since once a `CephBlockPool` no longer exists, Rook doesn't know that the pool should not be in `mgr/prometheus/rbd_stats_pools`. I imagine ensuring that the pool is removed from `mgr/prometheus/rbd_stats_pools` before the finalizer on the `CephBlockPool` is removed would help with this?
2. Provide a way for to completely ignore `mgr/prometheus/rbd_stats_pools` and let me manage it myself.
3. Provide a way to define a `CephBlockPool` as "external" or something so that Rook does not try to change the pool properties but _does_ get it added to `mgr/prometheus/rbd_stats_pools`.

To try to be very clear about my problem: I have pools in my Ceph cluster that are not managed by Rook. Rook removes these pools from `mgr/prometheus/rbd_stats_pools`. I would like it not to do that.
