### ISSUE TITLE
rgw-admin-ops-user cannot create bucket checker user

### ISSUE THREAD

**Issue by mgugino-uipath** [rook/rook#11068]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Bucket health checks fail, cephobjectstore goes into Failed status with error 'failed to get details from ceph object user <bucket-checker-user>: InvalidAccessKeyId ... <long token>'

Digging into this, I see a 403 on the rgw pod logs for the GET for that user.  I hopped onto the tools pod, radosgw-admin confirms rgw-admin-ops-user is present and the bucket checker user is not.

Restarting the operator does not resolve the issue.

Deleting the rgw-admin-ops-user user and restarting the operator does resolve the issue.

**Expected behavior:**
rgw-admin-ops-user should have proper permissions to create bucket user

**How to reproduce it (minimal and precise):**
We're attempting to use multisite ceph via the operator.  We configure cephobjectstore/zone/zg/realm appropriately.  We also have a job that executes after the rgw pod comes online (single rgw replica) that deletes default zone, and zonegroup

The script looks something like this:
```
  kubectl -n "${namespace}" exec "${pod_name}" -- radosgw-admin zone delete  --rgw-zone=default >> /dev/null || true
  kubectl -n "${namespace}" exec "${pod_name}" -- radosgw-admin zonegroup delete --rgw-zonegroup=default >> /dev/null || true
  kubectl -n "${namespace}" exec "${pod_name}" -- radosgw-admin period update --commit >> /dev/null || true

  # Delete default osd pool
  for iter in $(kubectl -n "${namespace}" exec "${pod_name}" -- ceph osd pool ls | grep -E '^default\.')
  do
    kubectl -n "${namespace}" exec "${pod_name}" -- ceph osd pool rm "${iter}" "${iter}" --yes-i-really-really-mean-it >> /dev/null || true
  done
}
```

It's unclear whether or not deleting the default zone and zonegroup and the period commit are having any impact.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.8.9
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): ceph is healthy

**Comment by mgugino-uipath** [comment]
I hit this again on another run without executing the default zone deletes as well.

**Comment by shubham-uipath** [comment]
Team looks like this issue is not yet fixed and could observe few occurrences of this bug.

**Comment by travisn** [comment]
@shubham-uipath What version of Rook are you running? The bucket health checker was removed a while back in #11124, but if you're running a recent version of Rook, I want to be clear about the issue you're seeing, and either reopen this one or open a new issue if it's not related to the bucket health checker.

**Comment by shubham-uipath** [comment]
@travisn  rook version in this env is pretty old  1.5.9 . 
Do you think removing bucket health check from this old cephobjectstore cr based on 1.5.4 rook should be okay ?   
I'm not sure if in recent rook version something else have been added to compensate bucket health check removal.

**Comment by travisn** [comment]
The bucket health check was just removed, and not replaced by anything else. It was attempting to check if the object store was healthy, but it wasn't really necessary.

**Comment by thotz** [comment]
> @travisn rook version in this env is pretty old 1.5.9 . Do you think removing bucket health check from this old cephobjectstore cr based on 1.5.4 rook should be okay ? I'm not sure if in recent rook version something else have been added to compensate bucket health check removal.

U can disable the health checker in the old version via ObjectStoreCRD
