### ISSUE TITLE
create-external-cluster-resources.py didn't properly handle --rgw-tls-cert-path parameter

### ISSUE THREAD

**Issue by dahorak** [rook/rook#11060]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When is the `create-external-cluster-resources.py` script called with `--rgw-endpoint` and `--rgw-tls-cert-path` parameters (first pointing to the RGW Endpoint, second to the path with certificate, it fails with following vague error:
```
Execution Failed: unable to connect to endpoint: <IP>:443
```
The problem is, that the path from `--rgw-tls-cert-path` parameter is used in `validate_rgw_endpoint_tls_cert`, which return the _content_ of the cert file.
And then in the `endpoint_dial` method, the _content_ of the cert file is passed to `requests.head(...)` as `verify` parameter:
```
r = requests.head(ep, timeout=timeout, verify=cert)
```
But it expect _path_ to the cert, not the content of the cert.

**Expected behavior:**
The `create-external-cluster-resources.py` script will properly handle the certificate provided via `--rgw-tls-cert-path` argument.

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux 8.6 (Ootpa)
* Kernel (e.g. `uname -a`): 4.18.0-372.26.1.el8_6.x86_64
* Rook version (use `rook version` inside of a Rook Pod): v4.12.0-0.ffcae8e019e3e67f76c70c9badde72646034ec79
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7-126.el8cp (fe0af61d104d48cb9d116cde6e593b5fc8c197e4) pacific (stable)
* Kubernetes version (use `kubectl version`):  v1.24.0+8c7c967
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift

**Comment by parth-gr** [comment]
./assign

**Comment by dahorak** [comment]
There is also similar problem in the `get_rgw_fsid` method. In following code:
```
            r = requests.get(
                request_url,
                auth=S3Auth(access_key, secret_key, rgw_endpoint),
                cert=cert,
                verify=verify,
            )
```
It uses both `cert` and `verify` arguments of the `get` method, but in wrong meaning[1]:

> **cert** – (optional) if String, path to ssl _client_ cert file (.pem). If Tuple, (‘cert’, ‘key’) pair.
> **verify** – (optional) Either a boolean, in which case it controls whether we verify the server’s TLS certificate, or a string, in which case it must be a path to a CA bundle to use. Defaults to True.

[1] https://requests.readthedocs.io/en/latest/api/
