### ISSUE TITLE
unable to delete cephobjecstore resources when health checks are failing

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#11078]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

`cephobjectstore` deletion seems to hang indefinitely when bucket checks are enabled but failing.  The operator will actually create pools and attempt to stand up an rgw deploy even while the `cephobjectstore` object is in the `Deleting` phase.

Here is an example of trying to delete the `cephobjectstore` for which no deploy/pod exists (something went wrong while testing).

```
  Type     Reason           Age                     From                         Message
  ----     ------           ----                    ----                         -------
  Warning  ReconcileFailed  30m (x17 over 50m)      rook-ceph-object-controller  failed to reconcile CephObjectStore "rook-ceph/lfa". failed to create object store deployments: failed to configure multisite for object store: failed create ceph multisite for object-store ["lfa"]: failed to commit config changes after creating multisite config for CephObjectStore "rook-ceph/lfa": failed to commit RGW configuration period changes%!(EXTRA []string=[]): exit status 22
  Warning  ReconcileFailed  6m29s (x4 over 19m)     rook-ceph-object-controller  failed to reconcile CephObjectStore "rook-ceph/lfa". failed to create object store deployments: failed to configure multisite for object store: failed create ceph multisite for object-store ["lfa"]: failed to commit config changes after creating multisite config for CephObjectStore "rook-ceph/lfa": failed to commit RGW configuration period changes%!(EXTRA []string=[]): exit status 22
  Warning  ReconcileFailed  2m33s (x12 over 6m17s)  rook-ceph-object-controller  failed to reconcile CephObjectStore "rook-ceph/lfa". failed to get dependents of CephObjectStore "rook-ceph/lfa": failed to list buckets in CephObjectStore "rook-ceph/lfa": Get "http://rook-ceph-rgw-lfa.rook-ceph.svc:80/admin/bucket?": dial tcp 10.43.45.94:80: connect: connection refused
```

**Expected behavior:**

The `cephobjectstore` quietly falls on its sword when asked to. :)

**How to reproduce it (minimal and precise):**
- enable bucket checks
- break the check... for example by deleting the `dashboard-admin` user
- delete `cephobjectstore` resource

**Environment**:
* rook 1.9.9, 1.10.1, 1.10.2

**Comment by travisn** [comment]
The bucket health check was removed with #11124, but doesn't look like it's in a release yet. But it's surprising that the reconcile continues to attempt to configure the object store even though it is deleted. Perhaps a workaround is to restart the operator so it won't continue the reconcile. @BlaineEXE other thoughts on this cleanup issue?
