### ISSUE TITLE
support setting --debug-rgw=<x/y> flag in rgw deploys

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#11074]
**What should the feature do:**

Provide a mechanism to set the `--debug-rgw=<x/y>` flag on rgw deploys to allow controlling log verbosity.

**What is use case behind this feature:**

I needed to manual edit the deploy to set this flag while debugging #4315 / #8750.

**Environment**:

* ceph 17.2.3
* rook 1.10.2

**Comment by travisn** [comment]
The log level should also be customizable from the toolbox with a command such as: `ceph config set client.rgw debug_rgw 20`

**Comment by jhoblitt** [comment]
I will give it a try.  `client.rgw` isn't listed on https://docs.ceph.com/en/latest/rados/troubleshooting/log-and-debug/#subsystem-log-and-debug-settings , which I did check before resorting to cli switches.

**Comment by jhoblitt** [comment]
`ceph config set client.rgw debug_rgw 20` is confirmed as working. Thank you!
