### ISSUE TITLE
Lots of `ldconfig` zombie processes

### ISSUE THREAD

**Issue by vertexvaar** [rook/rook#11082]
**Is this a bug report or feature request?**
* Bug Report (Or rather looking for help)

**Deviation from expected behavior:**
We are experiencing a growing amount of zombie processes, all `ldconfig` as childs of ceph-osd, ceph-mds, and ceph-mgr. Only `ldconfig` zombie processes exist and only ceph processes have zombies.
Sending `SIGCHLD` to any of the parents does not kill the zombies.

<details>
<summary>Process tree (taken from node 3 of 5)</summary>
<pre>
$ pstree -ps | grep ldconfig
           |-containerd-shim(3375)-+-ceph-osd(5238)-+-ldconfig(31032)
           |                       |                |-ldconfig(726110)
           |                       |                |-ldconfig(1068331)
           |                       |                |-ldconfig(1193550)
           |                       |                |-ldconfig(1465279)
           |                       |                |-ldconfig(1670170)
           |                       |                |-ldconfig(1933371)
           |                       |                |-ldconfig(2229304)
           |                       |                |-ldconfig(2284008)
           |                       |                |-ldconfig(2456469)
           |                       |                |-ldconfig(3533905)
           |-containerd-shim(55443)-+-ceph-mds(55784)-+-ldconfig(723240)
           |                        |                 |-ldconfig(1983120)
           |                        |                 |-ldconfig(2365585)
           |                        |                 |-ldconfig(2410809)
           |                        |                 |-ldconfig(3820394)
           |                        |                 |-ldconfig(3861422)
           |                        |                 |-ldconfig(4129141)
           |-containerd-shim(107172)-+-ceph-mgr(107322)-+-ldconfig(108022)
           |                         |                  |-ldconfig(385183)
           |                         |                  |-ldconfig(795456)
           |                         |                  |-ldconfig(918118)
           |                         |                  |-ldconfig(1051799)
           |                         |                  |-ldconfig(1347628)
           |                         |                  |-ldconfig(2490626)
           |                         |                  |-ldconfig(2663950)
           |                         |                  |-ldconfig(2681035)
           |                         |                  |-ldconfig(2742307)
           |                         |                  |-ldconfig(3227915)
           |                         |                  |-ldconfig(3253930)
           |                         |                  |-ldconfig(3710570)
</pre>
</details>
<details>
<summary>process list filtered for zombies</summary>
<pre>
$ ps aux | awk '$8 ~ /^[Zz]/'
root       31032  0.0  0.0      0     0 ?        Z    Sep22   0:00 [ldconfig] <defunct>
root      108022  0.0  0.0      0     0 ?        Z    Sep25   0:00 [ldconfig] <defunct>
root      385183  0.0  0.0      0     0 ?        Z    Sep25   0:00 [ldconfig] <defunct>
root      723240  0.0  0.0      0     0 ?        Z    Sep28   0:00 [ldconfig] <defunct>
root      726110  0.0  0.0      0     0 ?        Z    Sep27   0:00 [ldconfig] <defunct>
root      795456  0.0  0.0      0     0 ?        Z    Sep27   0:00 [ldconfig] <defunct>
root      918118  0.0  0.0      0     0 ?        Z    Sep27   0:00 [ldconfig] <defunct>
root     1051799  0.0  0.0      0     0 ?        Z    Sep24   0:00 [ldconfig] <defunct>
root     1068331  0.0  0.0      0     0 ?        Z    Sep28   0:00 [ldconfig] <defunct>
root     1193550  0.0  0.0      0     0 ?        Z    Sep28   0:00 [ldconfig] <defunct>
root     1347628  0.0  0.0      0     0 ?        Z    Sep26   0:00 [ldconfig] <defunct>
root     1465279  0.0  0.0      0     0 ?        Z    01:44   0:00 [ldconfig] <defunct>
root     1670170  0.0  0.0      0     0 ?        Z    03:30   0:00 [ldconfig] <defunct>
root     1933371  0.0  0.0      0     0 ?        Z    Sep26   0:00 [ldconfig] <defunct>
root     1983120  0.0  0.0      0     0 ?        Z    06:13   0:00 [ldconfig] <defunct>
root     2229304  0.0  0.0      0     0 ?        Z    08:23   0:00 [ldconfig] <defunct>
root     2284008  0.0  0.0      0     0 ?        Z    08:52   0:00 [ldconfig] <defunct>
root     2365585  0.0  0.0      0     0 ?        Z    09:34   0:00 [ldconfig] <defunct>
root     2410809  0.0  0.0      0     0 ?        Z    09:58   0:00 [ldconfig] <defunct>
root     2456469  0.0  0.0      0     0 ?        Z    Sep26   0:00 [ldconfig] <defunct>
root     2490626  0.0  0.0      0     0 ?        Z    Sep26   0:00 [ldconfig] <defunct>
root     2663950  0.0  0.0      0     0 ?        Z    Sep26   0:00 [ldconfig] <defunct>
root     2681035  0.0  0.0      0     0 ?        Z    Sep27   0:00 [ldconfig] <defunct>
root     2742307  0.0  0.0      0     0 ?        Z    Sep23   0:00 [ldconfig] <defunct>
root     3227915  0.0  0.0      0     0 ?        Z    Sep23   0:00 [ldconfig] <defunct>
root     3253930  0.0  0.0      0     0 ?        Z    Sep23   0:00 [ldconfig] <defunct>
root     3533905  0.0  0.0      0     0 ?        Z    Sep26   0:00 [ldconfig] <defunct>
root     3710570  0.0  0.0      0     0 ?        Z    Sep28   0:00 [ldconfig] <defunct>
root     3820394  0.0  0.0      0     0 ?        Z    Sep26   0:00 [ldconfig] <defunct>
root     3861422  0.0  0.0      0     0 ?        Z    Sep28   0:00 [ldconfig] <defunct>
root     4129141  0.0  0.0      0     0 ?        Z    Sep28   0:00 [ldconfig] <defunct>
</pre>
</details>

**Expected behavior:**
* Zombie processes are reaped by the OS as they would normally.
* `kill -s SIGCHLD 107172` kills all zombie processes of `ceph-mgr`

**How to reproduce it (minimal and precise):**
I am sorry, we can not formulate steps to reproduce this. We are searching for hints where to start.

**Environment**:
* OS: Ubuntu 20.04.5
* Kernel: Linux [redacted] 5.4.0-126-generic # 142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: 5 VMs on-location server hardware, 2CPU 8Gb per Node
* Rook version: rook: v1.8.6 go: go1.16.14
* Storage backend version: ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version: Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
    Kustomize Version: v4.5.4
    Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type: K3S
* Storage backend status: HEALTH_OK

**Comment by parth-gr** [comment]
The above output is from your machine, not inside the cluster,

Do you want to have `kill zombie process` feature or what do you aspect from this?

**Comment by travisn** [comment]
We used to have `tini` running as pid 1 so that the zombies would be cleaned up (removed in #8805), but when we removed it, we didn't anticipate that the ceph daemons would have child processes. @leseb thoughts?
