### ISSUE TITLE
Ceph dashboard can't serve on privileged ports (< 1024)

### ISSUE THREAD

**Issue by kierdavis** [rook/rook#11092]
**Is this a bug report or feature request?**
* Bug Report

**How to reproduce it (minimal and precise):**

Set `spec.dashboard.port` to 80 on a CephCluster instance and wait for reconciliation.

**Expected behavior:**

Either:
* the dashboard becomes accessible at the service address on port 80, or
* it's documented that values below 1024 aren't permitted, and any attempt to modify a CephCluster in this manner will be denied without the operator making any changes to the live Deployment or Service.

**Deviation from expected behavior:**

Connections to the service address on port 80 are refused.
The mgr's log reports that it failed to open a listening socket:

```cherrypy.process.wspbus.ChannelFailures: OSError("No socket could be created -- (('::', 80, 0, 0): [Errno 13] Permission denied)",)```

A permission denied error is understandable since rook has configured the mgr to listen on port 80, but hasn't issued it with `CAP_NET_BIND_SERVICE`.

Additionally, if I revert my change to the CephCluster, rook reverts its changes to the mgr service & deployment, but not to the ceph configuration store - the mgr process is still trying to open a socket on port 80. I needed to manually execute:

```sh
ceph config set mgr.a mgr/dashboard/server_port 7000
ceph config set mgr.b mgr/dashboard/server_port 7000
```

to restore functionality on the old port. This might be because the cluster health is HEALTH_ERR due to the failure in the dashboard module, I assume that's preventing reconciliation from fully completing.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary: https://gist.github.com/kierdavis/6d3984b072d62439aba6841c31744192

**Logs to submit**:

mgr log up to the point of failure: https://gist.github.com/kierdavis/0ec019130fe2fc49c737642bbbcd5b20

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): Talos Linux v1.2.1
* Kernel (e.g. `uname -a`): v5.15.65
* Cloud provider or hardware configuration: GCP VMs
* Rook version (use `rook version` inside of a Rook Pod): rook v1.10.1 / go: go1.18.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.25.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Talos Linux
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Motivation**:

This cluster is part of a tightly-knit environment where kubernetes services are available to the end user without an intervening ingress or load balancer. As a result it'd be convenient to access web UIs on the standard HTTP port - together with a simple CNAME DNS record, I'd be able to simply type `http://ceph.mycluster` into a browser. I'm able to configure other web apps such as Grafana in this manner, so rook-ceph is unfortunately the outlier here.

**Proposed solution(s)**:

The key takeaway is that rook currently uses the same port number for the service and for the pods, but there's no reason at the Kubernetes level why this needs to be the case. I'd expect that `spec.dashboard.port` would accept the full range of values permitted for a service port, and that the choice of port on the underlying pods would be an implementation detail that the cluster administrator shouldn't have to think about.

Ideas:
* Use a constant value (e.g. the current default of 7000) as the pod port number, regardless of the value of `spec.dashboard.port`.
  * Caveat(s): may be considered backwards-incompatible.
* Use `spec.dashboard.port` as the pod port number, unless it's less than 1024, in which case 7000 is used instead.
  * This still changes existing behaviour, but IMO it's a pure bug fix since values below 1024 are currently unusable.
* Keep all existing behaviour as-is and introduce a new CRD field like `spec.dashboard.servicePort` which overrides `spec.dashboard.port` in service contexts when present.
  * Caveat(s): this new field might be easily confused with the `port` field, making for a sub-par user experience.
* As above, but `spec.dashboard.podPort` instead.
* Imbue the mgr pods with `CAP_NET_BIND_SERVICE`.
  * Caveat(s): this is counter to the principle of least privilege.

**Comment by travisn** [comment]
Good discussion points, I went with the second bullet in #11104. Agreed this is optimal since there will be no concern for backward compatibility, and no need for exposing a new setting.

**Comment by kierdavis** [comment]
Nice, thank you!
