### ISSUE TITLE
LVM volumes not picked up

### ISSUE THREAD

**Issue by abh** [rook/rook#11095]
I'm running 1.10.2 (ceph 17.2.4) and my new LVM volumes aren't being picked up by osd-prepare.

The host is configured in the cluster with the following (I've tried various variations):

```
    - name: kn1
      devices:
      - name: "/dev/mapper/vgsdc-rook"
      - name: "/dev/disk/by-id/dm-name-vgsdd-rook"
```

It seems like `ceph-volume` is failing, but no output is added to the logs (I think).

```
2022-10-01 01:13:31.581028 D | exec: Running command: ceph-volume lvm list --format json vgsdd/rook
2022-10-01 01:13:31.933172 I | cephosd: skipping device "dm-2": failed to check if the device "dm-2" is available. failed to determine if the device was available. failed to determine if the device "/dev/mapper/vgsdd-rook" is available. failed to execute ceph-volume lvm list on LV "vgsdd/rook". exit status 1.
```

The full osd-prepare output is attached.

[osd-prepare.txt](https://github.com/rook/rook/files/9689257/osd-prepare.txt)

**Comment by abh** [comment]
Curiously when I changed one of the disks to just be a raw disk (removed the VG / PV and passed /dev/disk/by-id/scsi-... in the cluster parameter) both that disk and the LVM volume was picked up and used.

**Comment by satoru-takeuchi** [comment]
> Curiously when I changed one of the disks to just be a raw disk (removed the VG / PV and passed /dev/disk/by-id/scsi-... in the cluster parameter) both that disk and the LVM volume was picked up and used.

I have three questions.
- Does "/dev/mapper/vgsdc-rook" is on top of a vg consist of sdc and "/dev/disk/by-id/dm-name-vgsdd-rook" is on top of a vg consist of sdd?
- Could you provide the result of lsblk and blkid?

**Comment by abh** [comment]
@satoru-takeuchi -- yeah, exactly. It was an attempt at dividing one of the disks (sdc) up to also be used for local storage on the node.

```
# pvs; vgs ; lvs
  PV         VG    Fmt  Attr PSize    PFree
  /dev/sdc   vgsdc lvm2 a--  <447.13g <147.13g
  /dev/sdd   vgsdd lvm2 a--  <447.13g   <7.13g
  VG    #PV #LV #SN Attr   VSize    VFree
  vgsdc   1   1   0 wz--n- <447.13g <147.13g
  vgsdd   1   1   0 wz--n- <447.13g   <7.13g
  LV   VG    Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  rook vgsdc -wi-a----- 300.00g
  rook vgsdd -wi-a----- 440.00g
```

```
# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0    7:0    0    62M  1 loop /snap/core20/1611
loop1    7:1    0  67.8M  1 loop /snap/lxd/22753
loop2    7:2    0    47M  1 loop /snap/snapd/16292
loop3    7:3    0    48M  1 loop /snap/snapd/17029
loop4    7:4    0  63.2M  1 loop /snap/core20/1623
sda      8:0    0 111.8G  0 disk
├─sda1   8:1    0   512M  0 part /boot/efi
├─sda2   8:2    0   1.9G  0 part [SWAP]
└─sda3   8:3    0 109.4G  0 part /
sdb      8:16   0 111.8G  0 disk
sdc      8:32   0 447.1G  0 disk
└─vgsdc-rook
       253:1    0   300G  0 lvm
sdd      8:48   0 447.1G  0 disk
└─vgsdd-rook
       253:2    0   440G  0 lvm
[ skipping the rbd interfaces mounted to kube pods ]
```

```
# blkid
/dev/sda1: LABEL_FATBOOT="EFI" LABEL="EFI" UUID="E823-E51E" TYPE="vfat" PARTLABEL="BIOS" PARTUUID="c9901780-b7f6-4916-b0ad-09ac6aeefbb2"
/dev/sda2: UUID="c6374a9f-cb46-4cf1-a08c-a80213a43092" TYPE="swap" PARTLABEL="SWAP" PARTUUID="c1460b2b-1099-4369-b50f-c90b6d3bea64"
/dev/sda3: LABEL="ROOT" UUID="3cc244c2-7ab7-4e45-9d0e-6d1774fc32d6" TYPE="ext4" PARTLABEL="ROOT" PARTUUID="6b5bebe6-c1df-4690-a377-318ad102b05c"
/dev/loop0: TYPE="squashfs"
/dev/loop1: TYPE="squashfs"
/dev/loop2: TYPE="squashfs"
/dev/loop3: TYPE="squashfs"
/dev/loop4: TYPE="squashfs"
/dev/sdd: UUID="Ir6Zsn-6VfG-N80D-XL7X-TZV5-dDYm-XUFAvC" TYPE="LVM2_member"
/dev/sdc: UUID="52IbTl-h27E-vomi-E0YV-FBNd-pGDz-TLvUKm" TYPE="LVM2_member"
```

**Comment by satoru-takeuchi** [comment]
@abh In my environment (both rook v1.10.2 and v1.10.3) succeeded in create two OSDs.

```
    nodes:
      - name: tea
        devices:
          - name: "/dev/mapper/vgsdb-rook"
          - name: "/dev/disk/by-id/dm-name-vgsdc-rook"
```

Could you show me your cluster.yaml and the OS version (e.g. Ubuntu 20.04)?

**Comment by baoroushi** [comment]
> @abh In my environment (both rook v1.10.2 and v1.10.3) succeeded in create two OSDs.
> 
> ```
>     nodes:
>       - name: tea
>         devices:
>           - name: "/dev/mapper/vgsdb-rook"
>           - name: "/dev/disk/by-id/dm-name-vgsdc-rook"
> ```
> 
> Could you show me your cluster.yaml and the OS version (e.g. Ubuntu 20.04)?


Hi ,  my environment rook-ceph v1.10.7 , OS version centos 7.6,  Kuberneters v1.20.15,  Unable to recognize OSD, Is there a problem with the configuration？

# pvs; vgs ; lvs
  PV         VG    Fmt  Attr PSize    PFree
  /dev/sda3  VG VolGroup lvm2  [<1.09TiB / 490.11 GiB free]
  VG    #PV #LV #SN Attr   VSize    VFree
  VolGroup   1   11   0 wz--n- <1.09t <490.11g

  LV   VG    Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  ceph-0 VolGroup -wi-a----- 100.00g
  ceph-1 VolGroup -wi-a----- 100.00g
  ceph-2 VolGroup -wi-a----- 100.00g
  
# lsblk
NAME                                   MAJ:MIN  RM    SIZE    RO     TYPE     MOUNTPOINT
sda
|-sda3
     |-ceph-0                           253:0         0        100G  0        lvm
     |-ceph-1                           253:0         0        100G  0        lvm
     |-ceph-2                          253:0         0        100G  0        lvm
     
# cat cluster.yaml
..................................
   storage:
        useAllNodes: false
        useAllDevices: false
        config:
        nodes:
             -   name:   "192.168.1.100"
                 devices:
                      - name: "/dev/mapper/VolGroup--ceph--0"
                      - name: "/dev/mapper/VolGroup--ceph--1"
                      - name: "/dev/mapper/VolGroup--ceph--2"
....................................

**Comment by satoru-takeuchi** [comment]
@baoroushi Could you provide the log of osd-prepare-pod?

**Comment by baoroushi** [comment]
> @baoroushi Could you provide the log of osd-prepare-pod?

The pod log of "osd prepare pod" is not created automatically。

**Comment by baoroushi** [comment]
The rook-ceph-operator log displays "warnings go:70] storage.k8s. io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s. io/v1 CSIDriver"  ， CSIDriver does not support v1.22+K8S version？

**Comment by baoroushi** [comment]
> @baoroushi What does `automatically` in this case? In my understanding, once you apply cluster.yaml, or edit cephcluster CR and restart the operator pod, `rook-ceph-osd-prepare-XXX` pod runs and its log can be get by `kubectl logs.`

Hi, Can you help me look at the ceph-volume.log log? I'm not sure what the problem is.
[ceph-volume.log](https://github.com/rook/rook/files/10266305/ceph-volume.log)

**Comment by satoru-takeuchi** [comment]
This message means the deprecation and the removal of the  `storage.k8s. io/v1beta1 CSIDriver` API. If you use v1.20.15 as you described, this API its deprecated but is still alive.

Could you answer this question?
https://github.com/rook/rook/issues/11095#issuecomment-1357341690

**Comment by baoroushi** [comment]
> 

I'm not sure. I changed to a K8S environment, k8s version 1.20.15. Redeploy and modify the cluster.yaml file. It is found that the rook-ceph-osd-prepare-XXX is not created automatically. Check the rook-ceph-operator-XXX log, and the following prompt is given: 

2022-12-21 03:35:15.740051 I | op-osd: start running osds in namespace "rook-ceph"
2022-12-21 03:35:15.740062 I | op-osd: wait timeout for healthy OSDs during upgrade or restart is "10m0s"
2022-12-21 03:35:15.745469 I | op-osd: start provisioning the OSDs on PVCs, if needed
2022-12-21 03:35:15.925615 I | op-osd: no storageClassDeviceSets defined to configure OSDs on PVCs
2022-12-21 03:35:15.925636 I | op-osd: start provisioning the OSDs on nodes, if needed
2022-12-21 03:35:16.129366 I | op-osd: 0 of the 3 storage nodes are valid
2022-12-21 03:35:16.129386 W | op-osd: no valid nodes available to run osds on nodes in namespace "rook-ceph"

**Comment by satoru-takeuchi** [comment]
@baoroushi 

```
2022-12-21 03:35:16.129386 W | op-osd: no valid nodes available to run osds on nodes in namespace "rook-ceph"
```

This message means the node "192.168.1.100" was not selected to run a prepare job. Cloud you run `kubectl get node` and verify whether "192.168.1.100" exists or not.

**Comment by baoroushi** [comment]
> @baoroushi
> 
> ```
> 2022-12-21 03:35:16.129386 W | op-osd: no valid nodes available to run osds on nodes in namespace "rook-ceph"
> ```
> 
> This message means the node "192.168.1.100" was not selected to run a prepare job. Cloud you run `kubectl get node` and verify whether "192.168.1.100" exists or not.

NAME              STATUS                     ROLES                 AGE   VERSION
rdbsz2d5bj06u19   Ready,SchedulingDisabled   compute,master,node   83d   v1.20.15
rdbsz2d5bj06u21   Ready                      compute,node          83d   v1.20.15
rdbsz2d5bj09u19   Ready,SchedulingDisabled   compute,master,node   83d   v1.20.15
rdbsz2d5bj09u21   Ready                      compute,node          83d   v1.20.15
rdbsz2d5bj10u19   Ready,SchedulingDisabled   compute,master,node   83d   v1.20.15
rdbsz2d5bj10u21   Ready                      compute,node          83d   v1.20.15

**Comment by satoru-takeuchi** [comment]
Please specify the correct node name (e.g. one of node resource names like "rdbsz2d5bj06u19" than "192.168.1.100"). If the tagret node is marked "SchedulingDisabled", you also neeed to uncordon the node. After that, restart the operator pod. Then you will find osds if the device selection is correct.

**Comment by baoroushi** [comment]
> Please specify the correct node name (e.g. one of node resource names like "rdbsz2d5bj06u19" than "192.168.1.100"). If the tagret node is marked "SchedulingDisabled", you also neeed to uncordon the node. After that, restart the operator pod. Then you will find osds if the device selection is correct.

OK, The rook deph has worked normally. Thank you very much for your support！

**Comment by baoroushi** [comment]
> Please specify the correct node name (e.g. one of node resource names like "rdbsz2d5bj06u19" than "192.168.1.100"). If the tagret node is marked "SchedulingDisabled", you also neeed to uncordon the node. After that, restart the operator pod. Then you will find osds if the device selection is correct.

OK, The rook-ceph has worked normally. Thank you very much for your support！
