### ISSUE TITLE
disruptionmanagement, removed host "has flags noout"

### ISSUE THREAD

**Issue by abh** [rook/rook#11100]
Running 1.10.2, with the disruption management feature enabled.

We're moving a cluster to new hardware a node at a time. One of the removed notes got "stuck" with the noout flag, despite being long since removed. It's possible that this node got drained and then removed abruptly without all the resources cleared off first.

```
[WRN] OSD_FLAGS: 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set
    host kw5 has flags noout
```

The ceph dashboard doesn't show the node, and the `ceph orch` commands don't work (or I don't know how to invoke them).

The `rook-ceph-pdbstatemap` configmap has the line

>   kw5-noout-last-set-at: "2022-10-03T07:01:43Z"

How do I clear the `noout` flag from this node?

**Comment by travisn** [comment]
@abh From the toolbox, try unsetting the noout something like this:
```
ceph osd unset-group noout kw5
```

**Comment by abh** [comment]
Yes, that fixed it! We decommissioned a handful of other nodes since and this scenario didn't reappear. Hopefully if someone else runs into it they'll search the issues and find this.

Thank you, @travisn!
