### ISSUE TITLE
rbd error on pod reschedule

### ISSUE THREAD

**Issue by jpds** [rook/rook#1110]
Hello,

On one of my rescheduled pods, I'm getting this error in `kubectl describe po/`:

```
  Warning  FailedMount  1m  kubelet, node-a  MountVolume.SetUp failed for volume "pvc-67c766b2-adba-11e7-9694-52540068863c" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume replicapool/pvc-67c766b2-adba-11e7-9694-52540068863c: failed to map image replicapool/pvc-67c766b2-adba-11e7-9694-52540068863c cluster rook. failed to map image replicapool/pvc-67c766b2-adba-11e7-9694-52540068863c: Failed to complete rbd: exit status 2. output: 2017-10-20 13:14:23.960752 7fd158dbb0c0 -1 did not load config file, using default settings.
2017-10-20 13:14:23.963865 7fd158dbb0c0 -1 Errors while parsing config file!
2017-10-20 13:14:23.963872 7fd158dbb0c0 -1 parse_file: cannot open /etc/ceph/rook.conf: (2) No such file or directory
2017-10-20 13:14:23.963872 7fd158dbb0c0 -1 parse_file: cannot open ~/.ceph/rook.conf: (2) No such file or directory
2017-10-20 13:14:23.963873 7fd158dbb0c0 -1 parse_file: cannot open rook.conf: (2) No such file or directory
2017-10-20 13:14:23.965938 7fd158dbb0c0 -1 Errors while parsing config file!
2017-10-20 13:14:23.965944 7fd158dbb0c0 -1 parse_file: cannot open /etc/ceph/rook.conf: (2) No such file or directory
2017-10-20 13:14:23.965945 7fd158dbb0c0 -1 parse_file: cannot open ~/.ceph/rook.conf: (2) No such file or directory
2017-10-20 13:14:23.965946 7fd158dbb0c0 -1 parse_file: cannot open rook.conf: (2) No such file or directory
sh: 1: /sbin/modinfo: not found
sh: 1: /sbin/modprobe: not found
rbd: failed to load rbd kernel module (127)
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (2) No such file or directory
```

Interestingly, there's nothing related to rbd in the hosts dmesg.

**Comment by kokhang** [comment]
@jpds what os is this node running and what kernel version?

**Comment by jpds** [comment]
Debian 9 with `4.12.0-0.bpo.1-amd64` kernel, has been running rook for a few weeks now.

**Comment by jpds** [comment]
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2017-10-12T15:23:39Z
  generation: 1
  labels:
    app: rook-agent
  name: rook-agent
  namespace: rook-system
  resourceVersion: "2570114"
  selfLink: /apis/extensions/v1beta1/namespaces/rook-system/daemonsets/rook-agent
  uid: 53158f5a-af61-11e7-bf0e-525400f15fe7
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rook-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-agent
    spec:
      containers:
      - args:
        - agent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: rook/rook:master
        imagePullPolicy: IfNotPresent
        name: rook-agent
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /flexmnt
          name: flexvolume
        - mountPath: /dev
          name: dev
        - mountPath: /sys
          name: sys
        - mountPath: /lib/modules
          name: libmodules
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-operator
      serviceAccountName: rook-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
          type: ""
        name: flexvolume
      - hostPath:
          path: /dev
          type: ""
        name: dev
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /lib/modules
          type: ""
        name: libmodules
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 8
  desiredNumberScheduled: 8
  numberAvailable: 8
  numberMisscheduled: 0
  numberReady: 8
  observedGeneration: 1
  updatedNumberScheduled: 8

**Comment by kokhang** [comment]
Looks like you are using an older version. This fix was in last week

**Comment by jpds** [comment]
Fixed by updating rook image on nodes, deleting `rook-system` namespace and redeploying operator.

**Comment by kilsoo75** [comment]
Hi ~
I installed the rook on my k8s cluster today but I got the same issue on my k8s environment. 

**[environment]**
- OS : CentOS Linux release 7.4.1708 (Core)
- ROOK image : rook/rook:master (v0.6.0)
- Log
_2018-02-21 01:33:50.520556 E | flexdriver: Attach volume replicapool/pvc-03a5fc0d-1624-11e8-9c9e-0699d760d333 failed: failed to attach volume replicapool/pvc-03a5fc0d-1624-11e8-9c9e-0699d760d333: failed to map image replicapool/pvc-03a5fc0d-1624-11e8-9c9e-0699d760d333 cluster rook. failed to map image replicapool/pvc-03a5fc0d-1624-11e8-9c9e-0699d760d333: Failed to complete rbd: exit status 2. output: modinfo: ERROR: could not get modinfo from 'rbd': Exec format error
modprobe: ERROR: could not insert 'rbd': Exec format error
rbd: failed to load rbd kernel module (1)
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (2) No such file or directory_


I can load the module info on the node like following but I could not load the module info on the rook-agent container like following.

**[on the node]**
[root@k8s-dev-node04 ~]# modinfo rbd
filename:       /lib/modules/3.10.0-693.11.6.el7.x86_64/kernel/drivers/block/rbd.ko.xz
license:        GPL
description:    RADOS Block Device (RBD) driver
author:         Jeff Garzik <jeff@garzik.org>
author:         Yehuda Sadeh <yehuda@hq.newdream.net>
author:         Sage Weil <sage@newdream.net>
author:         Alex Elder <elder@inktank.com>
rhelversion:    7.4
srcversion:     B41E51769EC95E3DBDB16AB
depends:        libceph
intree:         Y
vermagic:       3.10.0-693.11.6.el7.x86_64 SMP mod_unload modversions
signer:         CentOS Linux kernel signing key
sig_key:        2C:BC:98:70:54:63:43:CA:3A:E1:20:C2:BC:EB:98:44:01:95:59:62
sig_hashalgo:   sha256
parm:           single_major:Use a single major number for all rbd devices (default: false) (bool)

** [on the rook-agent container]**
~ » kubectl exec -it rook-agent-bj7cd -n rook-system bash                                                                                                                                              kilsookang@Kilsoos-MacBook-Pro
root@k8s-dev-node05:/# modinfo rbd
filename:       /lib/modules/3.10.0-693.11.6.el7.x86_64/kernel/drivers/block/rbd.ko.xz
modinfo: ERROR: could not get modinfo from 'rbd': Exec format error

**Comment by jbw976** [comment]
We've seen this before on 3.x kernels.  If it's not feasible to upgrade the kernels then a workaround suggested by @kokhang would be:
> for 3.x, the workaround is to manually do 'modprobe rbd' in all nodes. It should work after that

**Comment by kilsoo75** [comment]
@jbw976 Many thanks for your mention. I did the 'modprobe rbd' on the host node and the container mounted the volume successfully. Additionally, I will try to upgrade the kernel version of host machine.

**Comment by motecshine** [comment]
@jbw976  `3.10.0-862.3.2.el7.x86_64` thks a lot  , `modprobe rbd` work for me

**Comment by 2fst4u** [comment]
> @jbw976 Many thanks for your mention. I did the 'modprobe rbd' on the host node and the container mounted the volume successfully. Additionally, I will try to upgrade the kernel version of host machine.

7 years later and many versions on this still solved it for me too.
