### ISSUE TITLE
The cluster chart can't create an external cluster 

### ISSUE THREAD

**Issue by LoicGombeaud** [rook/rook#11114]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Using the `rook-ceph-cluster` chart, when I try to create a cluster with `cephClusterSpec.external.enable: true`, the creation fails because of the default values : they include entries for `mon`, `dashboard`, `monitoring`, `network`, `disruptionManagement`, `storage`, which is not compatible with an external cluster.

The incompatibility is understandable, but it contradicts [the documentation](https://github.com/rook/rook/blob/master/Documentation/CRDs/Cluster/ceph-cluster-crd.md#cluster-settings):

> If this setting is enabled **all** the other options will be ignored except `cephVersion.image` and `dataDirHostPath`.

This issue is aggravated by the fact that I am using the `rook-ceph-cluster` as a subchart, and due to a [bug in Helm](https://github.com/helm/helm/issues/9136) I am unable to unset/remove the incompatible keys.

**Expected behavior:**

Setting `cephClusterSpec.external.enable: true` creates an external cluster.

**How to reproduce it (minimal and precise):**

```
helm repo add rook https://charts.rook.io/release
helm install rook-ceph-cluster rook/rook-ceph-cluster --set cephClusterSpec.external.enable=true
```

**File(s) to submit**:

* CR manifest generated by the chart : [generated-cluster-cr.yaml.txt](https://github.com/rook/rook/files/9723500/generated-cluster-cr.yaml.txt)

**Logs to submit**:

No logs, as the CR isn't created

**Cluster Status to submit**:

N/A

**Comment by travisn** [comment]
Instead of setting a single property with `--set`, how about specifying a the full values.yaml as recommended in the [Rook helm docs](https://rook.io/docs/rook/latest/Helm-Charts/ceph-cluster-chart/#release)? This should allow you to replace the whole cluster spec with the external cluster spec.

**Comment by LoicGombeaud** [comment]
> Instead of setting a single property with `--set`, how about specifying a the full values.yaml as recommended in the [Rook helm docs](https://rook.io/docs/rook/latest/Helm-Charts/ceph-cluster-chart/#release)? This should allow you to replace the whole cluster spec with the external cluster spec.

Thanks for the suggestion; this is actually what I do in my workflow, I only used the `--set` to showcase a reproducible example.

Using a `values.yaml` file doesn't solve the issue, because the `cephClusterSpec` map gets merged (and not replaced) with the one defined in the `values.yaml` file of the chart. A possible solution would be to set e.g. `cephClusterSpec.mon` to `null` to unset it, but as mentioned I use the chart as a subchart (in an ArgoCD repo), and due to the helm bug linked above, this method doesn't work.
