### ISSUE TITLE
Switch to host networking on a running cluster

### ISSUE THREAD

**Issue by ammarzuberi** [rook/rook#11121]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The documentation states that it's not possible to switch a running cluster using overlay networking to host networking. My feature request is either more documentation around how it could be changed manually and/or support in the operator for redeploying pods with host networking.

**What is use case behind this feature:**
I initially deployed Rook with Ceph using Calico, but have started to run into performance limitations of the overlay network. I'd like to switch over to using host networking but it's not supported.

I realize that this is a contrived edge case problem and I imagine the functionality will not be implemented in the operator. If someone could provide a high level "push in the right direction" I'd be happy to try do the surgery on my cluster and write a doc outlining the process.

Thanks!

**Comment by travisn** [comment]
The main challenge is converting the mons. The mon IP is a core part of their ceph identity. In a host network cluster, the mons use the host IP, while in a cluster network the mons will use the clusterIP of a K8s service created by the operator. So if you have a host network, you could try the following to convert the mons:
1. Change the setting in the cluster CR from host networking. You'll likely need to first to disable the [admission controller](https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml#L617). 
2. Take down a mon and trigger a [mon failover](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor). If all goes well, a new mon will be created based on the cluster network.
3. Repeat step 2 for each mon until all are converted.

The difficult part will be if the operator gets confused between steps 1 and 2 when mons are still on host networking but it tries to update their pod spec to not use host networking.

**Comment by ammarzuberi** [comment]
Thanks a lot for the reply - this does help. However, I don't think I was clear in communicating that I want to switch from overlay networking (calico) **to host networking**, not the other way around as you described.

**Comment by travisn** [comment]
Yes I would anticipate the process is the same either way. 

I'm taking a look at how we could make this conversion work more smoothly. In a quick test conversion, the operator was stuck as I suspected after step 1. I'll report back when I find something more helpful on how to get this working...

**Comment by travisn** [comment]
With the change in #11211, the mons will remember their individual network config and be able to continue running after the host network setting is changed. Then the mons could be failed over to the alternate network settings.
