### ISSUE TITLE
Documentation: How to use ceph-bluestore-tool

### ISSUE THREAD

**Issue by mattster98** [rook/rook#11135]
* Feature Request

**What should the feature do:**
Document how to run/use the ceph-bluestore-tool in the rook-ceph environment.

**What is use case behind this feature:**
I upgraded ceph and need to update the BlueStore omap usage stats - automatic methods aren't working so guidance is to run the tool manually to see what is going on.  I can't find any explanation on how to run it in this environment.  Found hints that "krew" enabled this, but still unclear how to run the tool and what device path to use.

**Environment**:
Rook 1.7.11 Ceph 16.2.10

**Comment by travisn** [comment]
Yes, you're on the right track with the krew plugin. The procedure would be the following on a running rook cluster:
1. Determine an OSD that needs maintenance
2. Start the [debug pod for the OSD](https://github.com/rook/kubectl-rook-ceph/blob/master/docs/debug.md) with the krew plugin. This will stop the OSD daemon and replace it with a "debug" pod where you can run the ceph tools while the daemon is not running.
3. Exec to the osd debug pod and run `ceph-bluestore-tool`. See the [Ceph docs](https://docs.ceph.com/en/latest/man/8/ceph-bluestore-tool/) for usage. For the device path, look at the osd prepare pod logs that created the OSD to see what path would correspond to the OSD.
4. When done, stop the debug pod which will restore the OSD daemon to running state

**Comment by mattster98** [comment]
Wow, once you say it, it seems obvious. :)

Thanks so much!
