### ISSUE TITLE
Allow setting bluestoreDirBlockSizeRatio for bluestore

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1113]
I redeployed a cluster yesterday and just noticed that previously I had about 57TB cluster capacity and now "only" 54TB storage.
After finding https://github.com/rook/rook/pull/1077#discussion-diff-145284151R47 and talking to @jbw976:

***

**Chat Log**:

Alexander Trost [9:24 AM] 
I just redeployed my cluster and was wondering why I now have 3TB less storage (before redeploy 57.5TB, after 54.8TB). (edited)

[9:24] 
@jbw976 I was wondering if this is caused by 1077 (https://github.com/rook/rook/pull/1077#discussion-diff-145284151R47) (the cluster uses bluestore)? (edited)

jbw976 [4:28 PM] 
@galexrt are you using bluestore on directories or devices?

Alexander Trost [4:29 PM] 
@jbw976 both.

jbw976 [4:31 PM] 
I believe with raw devices that we will still use the entire device. but for directories, yes that 90% value will be used in an attempt to not let the entire file system fill up. especially since the default is on the root file system.

[4:31] 
what do you think of that?

Alexander Trost [4:39 PM] 
@jbw976 I like the idea of not letting the file system fill up completely (when there is something else running on the file system). In my case I have a dedicated partition for the directory, so I want to use it to "100%". (edited)

Alexander Trost [5:07 PM] 
Would there be a way to change this?

jbw976 [5:37 PM] 
right now there isn’t, but we could consider exposing it as a storage config setting, similar to how we expose `databaseSizeMB` etc. in https://rook.io/docs/rook/master/cluster-crd.html#storage-configuration-settings

[5:38] 
and let it be known that @kokhang suggested this in the PR but I was confident that it was not necessary.

Alexander Trost [5:54 PM] 
@jbw976 Well there is always that one guy that needs it :wink:

[5:55] 
Should I go ahead and create an issue to track it?

Travis [6:06 PM] 
yes, sounds good to have an issue tracking it. What if we always used 100% for user-specified directories? If we're using the default dir under /var/lib/rook then we could set it to 90%. Just trying to avoid a new setting unless it's necessary.

***

The "issue" with the "loss" of 3TB seems to be caused by the default value (being `0.9`) for the Bluestore directory size ratio.

It would good to a) have this variable configurable or b) use other defaults (like @travisn wrote in his message).

**Comment by kokhang** [comment]
if we need the swap space, instead of a % value, should it be actual size? like 500mb or something?

**Comment by galexrt** [comment]
Anyone having something against for now using other defaults for paths other than `/var/lib/rook`?

One question when going for using other default would then be, what percentage should be used?
In my case the directory is a single partition dedicated for rook, so I'd prefer a percentage of `1` or to leave a little bit of space `0.99` or even `0.999`.
Should the directory given for rook OSD be assumed to be dedicated `100%` for rook or "shared" with "other" applications and therefore leave some space?

**Comment by travisn** [comment]
My view in this area is that we should make rook flexible to work for the most environments possible and be generous with our assumptions. The admin will then have to manage that flexibility according to best practices, or else manage the complexity himself. For example, a best practice would be that you should only use one directory on a dedicated volume and Rook should allow you to use 100% of the space. If you decide to put two directories on the same volume (not a best practice), the behavior may not be optimal, such as metrics being inaccurate, or you run out of space sooner than expected. 

We can't put restrictions in place that fit every scenario, thus let's keep it flexible and document best practices and warnings.

**Comment by jbw976** [comment]
I know this makes sense for bluestore because you can directly influence the size of the backing store with `bluestore_block_size`: https://github.com/rook/ceph/blob/rook-luminous/src/common/options.cc#L3153

But does filestore have something similar? can you set a quota like this for filestore?

**Comment by galexrt** [comment]
@jbw976 I haven't found an option for filestore on the link you provided and also here http://docs.ceph.com/docs/giant/rados/configuration/filestore-config-ref/. It seems that filestore normally uses "100%" of the directory provided.

How should we continue on this? Adding the option for bluestore only?

**Comment by galexrt** [comment]
@travisn @jbw976 @kokhang Do you see anything against setting the `bluestoreDirBlockSizeRatio` to `1`?
Setting it to `1` wouldn't make a difference to `filestore`, as it seems to be thinly provisioned.

**Comment by jbw976** [comment]
Yes, I think the original intent of this value (to prevent the disk from filling up) isn't actually being met because there are no checks later on to prevent other usage of the disk from filling it up before the bluestore block file has filled it up itself. OSDs also have a near-full and full ratio that would start turning away requests before the disk is full.

This const isn't really providing value and could be set to 1.0 or removed entirely.

**Comment by jbw976** [comment]
I believe the true intent of this issue has been addressed with #1249.  I don't think this setting needs to be exposed to users.
