### ISSUE TITLE
[Help]It's there a way to recover shared file system that were mistakenly deleted.

### ISSUE THREAD

**Issue by ericjee** [rook/rook#11137]
Hi Community,  I deleted `CephFilesystems` from my production cluster for some stupid reason. Now MDS is gone, cephfs data pool and metadata are also gone.
Do I get a chance to recover the filesystem? I only got my disk backup for osds.

ceph status, I can see my used capacity keep reducing.
`
  cluster:
    id:     148c8fc8-692f-4a1c-a008-1a83f3fbbb14
    health: HEALTH_WARN
            nobackfill,norebalance,norecover,noscrub,nodeep-scrub flag(s) set
            3 osds down
            Reduced data availability: 112 pgs inactive, 112 pgs peering
            Degraded data redundancy: 2290/226068 objects degraded (1.013%), 1 pg degraded, 1 pg undersized
            11 pgs not deep-scrubbed in time
            1404 slow ops, oldest one blocked for 9752 sec, daemons [osd.1,osd.2,osd.3] have slow ops.

  services:
    mon: 3 daemons, quorum b,c,e (age 0.872083s)
    mgr: a(active, since 13h)
    osd: 6 osds: 3 up (since 0.784414s), 6 in (since 12h); 9 remapped pgs
         flags nobackfill,norebalance,norecover,noscrub,nodeep-scrub

  data:
    volumes: 1/1 healthy
    pools:   8 pools, 201 pgs
    objects: 75.36k objects, 216 GiB
    usage:   8.2 TiB used, 21 TiB / 29 TiB avail
    pgs:     55.721% pgs not active
             2290/226068 objects degraded (1.013%)
             4580/226068 objects misplaced (2.026%)
             104 peering
             88  active+clean
             8   remapped+peering
             1   active+undersized+degraded+remapped+backfilling

  progress:
    Global Recovery Event (5h)
      [============................] (remaining: 7h)
`

**Comment by travisn** [comment]
What pools are remaining? Does `ceph osd pool ls detail` in the toolbox show that the pools still exist or that they were really deleted? By default the filesystem and pools should be preserved in ceph even when the filesystem is deleted, according to [this setting](https://github.com/rook/rook/blob/master/deploy/examples/filesystem.yaml#L44).

**Comment by travisn** [comment]
@ericjee Were you able to recover it?
