### ISSUE TITLE
Can't mount CephNFS exports manual/external 

### ISSUE THREAD

**Issue by PSTobiasMueller** [rook/rook#11132]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I can´t mount created persistent volumes that are exports on a nfs Ganesha server create via CephNFS
```
mount -t nfs4 -o proto=tcp -o ro  rook-ceph-nfs-my-nfs-a:/0001-0009-rook-ceph-0000000000000001-a70688cd-489b-11ed-8db8-d267945ee329 /mnt/test
mount: /mnt/test: cannot mount rook-ceph-nfs-my-nfs-a:/0001-0009-rook-ceph-0000000000000001-a70688cd-489b-11ed-8db8-d267945ee329 read-only.
```

**Expected behavior:**
I can mount the exports as described in the [documentation](https://rook.io/docs/rook/v1.9/ceph-nfs-crd.html)

**How to reproduce it (minimal and precise):**
I installed Rook.IO on a fresh RKE Cluster via Helm Chart. The worker node have a additional second disk for the Ceph cluster.
Operator Values:
```
csi:
  nfs:
    enabled: true

enableDiscoveryDaemon: true
```
After the Operator I installed the cluster helm chart with the default values. The operator did create a healthy cluster successfully. the next step was do deploy the [nfs.yaml](https://github.com/rook/rook/blob/a809de25741555f113b4beb1ea8058d9468f8e07/deploy/examples/nfs.yaml) from the examples folder. Thereafter i created the [storage class](https://github.com/rook/rook/blob/a809de25741555f113b4beb1ea8058d9468f8e07/deploy/examples/csi/nfs/storageclass.yaml), also from the examples. I changed the settings for `fsName`and `pool` to fit the deployed filesystem and pool.

I was now able to successfully deploy a pvc with ReadWriteMany Policy and let multiple pods consume that volume without problem.

But I wasn't able to manually mount the pv on a plain ubuntu pod i deployed in the rook-ceps namespace. I always receive the read-only error.

**File(s) to submit**:

Cluster.yaml
```
apiVersion: v1
items:
- apiVersion: ceph.rook.io/v1
  kind: CephCluster
  metadata:
    annotations:
      meta.helm.sh/release-name: rook-ceph-cluster
      meta.helm.sh/release-namespace: rook-ceph
    creationTimestamp: "2022-10-10T12:13:48Z"
    finalizers:
    - cephcluster.ceph.rook.io
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
    name: rook-ceph
    namespace: rook-ceph
    resourceVersion: "28002"
    uid: a5a35a84-808c-4168-9672-18b37283387a
  spec:
    cephVersion:
      image: quay.io/ceph/ceph:v17.2.3
    cleanupPolicy:
      sanitizeDisks:
        dataSource: zero
        iteration: 1
        method: quick
    crashCollector: {}
    dashboard:
      enabled: true
      ssl: true
    dataDirHostPath: /var/lib/rook
    disruptionManagement:
      machineDisruptionBudgetNamespace: openshift-machine-api
      managePodBudgets: true
      osdMaintenanceTimeout: 30
    external: {}
    healthCheck:
      daemonHealth:
        mon:
          interval: 45s
        osd:
          interval: 1m0s
        status:
          interval: 1m0s
      livenessProbe:
        mgr: {}
        mon: {}
        osd: {}
    logCollector: {}
    mgr:
      count: 2
      modules:
      - enabled: true
        name: pg_autoscaler
    mon:
      count: 3
    monitoring: {}
    network: {}
    priorityClassNames:
      mgr: system-cluster-critical
      mon: system-node-critical
      osd: system-node-critical
    resources:
      cleanup:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 100Mi
      crashcollector:
        limits:
          cpu: 500m
          memory: 60Mi
        requests:
          cpu: 100m
          memory: 60Mi
      logcollector:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 100Mi
      mgr:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      mgr-sidecar:
        limits:
          cpu: 500m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 40Mi
      mon:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 1Gi
      osd:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 4Gi
      prepareosd:
        requests:
          cpu: 500m
          memory: 50Mi
    security:
      kms: {}
    storage:
      useAllDevices: true
      useAllNodes: true
    waitTimeoutForHealthyOSDInMinutes: 10

```

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:
```
  cluster:
    id:     3cb2b4e1-4f9e-4410-946a-36570b8ce46d
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 90m)
    mgr: a(active, since 89m), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 5 osds: 5 up (since 106s), 5 in (since 2m)
    rgw: 1 daemon active (1 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   13 pools, 369 pgs
    objects: 385 objects, 738 KiB
    usage:   197 MiB used, 1.2 TiB / 1.2 TiB avail
    pgs:     369 active+clean
 
  io:
    client:   1.3 KiB/s rd, 2 op/s rd, 0 op/s wr
```
* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.5 LTS (Focal Fossa)
* Kernel (e.g. `uname -a`): 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: on-Premise, Ubuntu VMs on vSphere
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.10.3 / go: go1.18.6
* Storage backend version (e.g. for ceph do `ceph -v`):ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)
* Kubernetes version (use `kubectl version`): 1.23.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by BlaineEXE** [comment]
The first thing I notice is that normally, `rook-ceph-nfs-my-nfs-a` wouldn't be a valid DNS name unless you have set this via some ingress/load balancer. If you haven't specifically done this, you will need the service "address" and not the service "name".

**Comment by PSTobiasMueller** [comment]
For the tests I've deployed a ubuntu pod inside the rook-ceph namespace. That's why i could call the service directly.  But i tried it with the ip of the service and the ip of the pod, too. I always get the same error.
