### ISSUE TITLE
Add CI test for external ceph cluster with SSL enabled for RGW

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#11149]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

The feature should test the `--rgw-tls-cert-path`  functionality on a cluster where SSL enabled for RGW

Steps:
1) Need to figure out how to get ceph cluster where SSL enabled for RGW
2) Test python script using --rgw-tls-cert-path flag

**What is use case behind this feature:**

**Environment**:

**Comment by parth-gr** [comment]
Procedure needs to follow

1) Create a root CA
2) Create a certificate  request for the RGW daemon 
3) Sign the certificate request using the root CA
4) Create a spec file as described in https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/5/html-single/object_gateway_guide/index#configuring-ssl-for-beast_rgw

**Comment by jalajk24** [comment]
Can I proceed on this issue? I am new to open source and don't know a lot on how to proceed with this.

**Comment by BlaineEXE** [comment]
I was planning on taking this up. I have several files that should help us in testing already set up from my manual tests. @jalajk24 perhaps I could `@` you on the PR, and you could see an example and ask questions to help get started with Rook?
