### ISSUE TITLE
Convert to a controller-runtime-compatible structured logger

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#11148]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

The controller-runtime project supports using a `logr`-compatible logger. It would be good for Rook to convert to using controller-runtime's logger, which also means switching to `logr` or a `logr`-compatible logger implementation.

**What is use case behind this feature:**

`logr` is a "structured" logger that has some benefits (and some drawbacks) compared to a non-structured logger. Information is added to a structured logger not by printf calls but by adding key-value pairs. 

For example, instead of `logf("%s %s/%s <log message>", <resource Kind>, <resource Namespace>, <resource Name>)`, a structured logger would do `log("kind", <resource Kind>, "namespace", <resource Namespace>, "name", <resource Name>, "<log message>")`. 

Further, controller-runtime allows information to be added to a logger piece-by-piece rather than all at once. For example:

```go
func (r *MemcachedReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
    log := logr.FromContext(ctx)
    stdInfo := []string{
        "controller", "object-controller", 
        "kind", "CephObjectStore", 
        "name", req.NamespacedName.String(),
    } // set standard info for logging and returning errors
    log = log.WithValues("name", req.NamespacedName.String()) # all subsequent logs will have "name" set
    // ...
    subFunction(ctx, log) // sub-functions should be given parent's logger
} 
```

Benefits:
- information doesn't need to be added to individual log items repeatedly
  - developers of sub-functions don't need to check all of parent context when writing logs
  - ^ this is the primary issue; it's too easy for even seasoned devs to forget to include kind, namespace, and name of a resource in logs, which makes debugging challenging in operators running Ceph in multiple namespaces.
- because logs are output in the same style repeatedly, which makes logs smaller when compressed
- logs are more searchable by keys (e.g., logs for rados pools which should have `pool=X`)

Drawbacks:
- many of us find logr-style logging to be harder to read with default settings
- the logger is no longer global and must be passed to all functions that wish to log (this will be a lot of code churn)

**Comment by BlaineEXE** [comment]
I did a quick test to see if we could get something that looks a lot more like the current rook logging, and I think it looks good:

https://go.dev/play/p/svrpLNTUkAc


```
2009-11-10 23:00:00.000000 E | .controller.one: starting reconciliation 
2009-11-10 23:00:02.000000 I | .controller.one.client: fetching object key=obj3  
2009-11-10 23:00:02.000000 I | .controller.one.client: pretending to deserialize object key=obj3  json=[insert real json here]  
2009-11-10 23:00:02.000000 I | .controller.one: reconciling object for key key=obj3  object={Name:obj3 Kind:one Details:1}  
2009-11-10 23:00:02.000000 I | .controller.one: updating object object={Name:obj3 Kind:one Details:1}  key=obj3  details=2  
2009-11-10 23:00:02.000000 I | .controller.one.client: saving object key=obj3  object={Name:obj3 Kind:one Details:2}  
2009-11-10 23:00:02.000000 I | .controller.one.client: pretending to post object key=obj3  url=https://fake.test  
```

**Comment by BlaineEXE** [comment]
Controller-runtime adds all of this information to the logger by default. I only configured the logger itself to blindly print the args with no processing.

```
"level"=0 "msg"="logr logger" "controller"="ceph-cluster-controller" "object"={"name":"my-cluster","namespace":"rook-ceph"} "namespace"="rook-ceph" "name"="my-cluster" "reconcileID"="79a57af4-fd40-4274-bc75-248459c14e4f"
```

**Comment by travisn** [comment]
> Drawbacks:
> - many of us find logr-style logging to be harder to read with default settings
> - the logger is no longer global and must be passed to all functions that wish to log (this will be a lot of code churn)

If the logs become less readable, IMO it would be a regression that doesn't outweigh the benefits of the structured logging. We've put a lot of effort into making the logging readable which makes troubleshooting more feasible.  

I don't doubt that the new logging would help ensure we have all the details of everything that is logged, such as the resource name and namespace it belongs to. But since there is a single cephcluster CR and a single Rook operator in the vast majority of cases, it doesn't seem worth the change.
