### ISSUE TITLE
image: rook/ceph:VERSION

### ISSUE THREAD

**Issue by vyom-soft** [rook/rook#11153]
Kubernetes v1.24.6
In the values.yaml file, For the toolbox what should be the value of VERSION
I used v1.10.3. ToolBox never get installed
MountVolume.SetUp failed for volume "mon-endpoint-volume" : configmap "rook-ceph-mon-endpoints" not found

kubectl describe pod rook-ceph-tools-55d94c94b-6sht7 -n rook-ceph
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/18686082/196189270-eaf7972e-ac7f-4b17-bf34-c21a0b719857.png">

Thank you.

**Comment by DjVinnii** [comment]
If I'm correct, the toolbox also uses Ceph images as of Rook v1.10. `quay.io/ceph/ceph:v17.2.3` would be a valid image. There is an open PR to fix this in the Helm charts: #11127

**Comment by vyom-soft** [comment]
I used quay.io/ceph/ceph:v17.2.3 for the toolbox. The same error persist.


toolbox:
  enabled: true
  image: **quay.io/ceph/ceph:v17.2.3**
  tolerations: []
  affinity: {}
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "100m"
      memory: "128Mi"


`Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    3m52s                 default-scheduler  Successfully assigned rook-ceph/rook-ceph-tools-55d94c94b-6sht7 to node3
  Warning  FailedMount  109s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[mon-endpoint-volume], unattached volumes=[mon-endpoint-volume kube-api-access-jltxd ceph-config]: timed out waiting for the condition`

**Comment by Madhu-1** [comment]
can you please provide `kubectl get pods` output to check is ceph cluster is created and we have all the requried pods?

**Comment by vyom-soft** [comment]
> can you please provide `kubectl get pods` output to check is ceph cluster is created and we have all the requried pods?

@Madhu-1 Thank you.
I don't think it is created. 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/18686082/196164639-48298cc3-b494-454f-8da8-1b22c6129b83.png">

**Comment by Madhu-1** [comment]
okay that is the problem, once ceph cluster is created toolbox will go to running state. That is expected.

**Comment by vyom-soft** [comment]
> okay that is the problem, once ceph cluster is created toolbox will go to running state. That is expected.

Thank you for. I have attached the operator & cluster yaml.  
Once the ceph cluster is created. May I know how long it will take to create it?.

**Comment by Madhu-1** [comment]
@DjVinnii what version of Rook you are using? please share rook operator logs and rook operator and cluster yaml outputs.

**Comment by vyom-soft** [comment]
I am using Helm chart to install. 
Attached is the rook operator log. 
I already attached the ceph-cluster-values & operator-values  yaml file above. Please see the same.
[rook-ceph-operator-5-log.txt](https://github.com/rook/rook/files/9800089/rook-ceph-operator-5-log.txt)

**Comment by Madhu-1** [comment]
value files are not helpful as it doesnt container more details (status), having `kubectl get -oyaml` files helps

**Comment by vyom-soft** [comment]
> value files are not helpful as it doesnt container more details (status), having `kubectl get -oyaml` files helps

<img width="428" alt="image" src="https://user-images.githubusercontent.com/18686082/196183049-7d688b29-5f61-40eb-8a36-d89ef1ff371a.png">
[rook-ceph-tools-deployment.txt](https://github.com/rook/rook/files/9800719/rook-ceph-tools-deployment.txt)
[rook-ceph-operator-deployment.txt](https://github.com/rook/rook/files/9800720/rook-ceph-operator-deployment.txt)

Unfortunately no ceph cluster is created till now.

Helm command used to install operator & then ceph cluster.
`helm install -f ./rook-operator-values.yaml --namespace rook-ceph rook-ceph rook-release/rook-ceph `

`helm install --namespace rook-ceph rook-ceph-cluster \
   --set operatorNamespace=rook-ceph rook-release/rook-ceph-cluster -f ceph-cluster-values.yaml`

Please let me know any other info are required.

**Comment by travisn** [comment]
Some questions:
- Please share the log for the operator pod
- After creating the helm charts, do you see the cephcluster CR exists? For example: `kubectl -n rook-ceph get cephcluster`

**Comment by vyom-soft** [comment]
> * ase share the log for the operator pod

Thank you for the attention. 
[rook-ceph-operator-5-log.txt](https://github.com/rook/rook/files/9809473/rook-ceph-operator-5-log.txt)

After execution of the above Helm chart command, The cephcluster  CR is not getting created. The toolbox get blocked as mentioned above. I am not sure where I am going wrong.

**Comment by travisn** [comment]
Whitespace is a common issue with yaml since indentation must be exact. However, it's not obvious to me in your ceph-cluster-values.txt what the issue is with your spec. Since the cephcluster CR is not being created, something must not be correct in the values.

**Comment by vyom-soft** [comment]
> Whitespace is a common issue with yaml since indentation must be exact. However, it's not obvious to me in your ceph-cluster-values.txt what the issue is with your spec. Since the cephcluster CR is not being created, something must not be correct in the values.

Thank you for introspection, indeed there was problem with values file, the alignment was not correct. 
I after going thoroughly again. I see cluster in progressing state.
[ceph-cluster-dep.txt](https://github.com/rook/rook/files/9839244/ceph-cluster-dep.txt)

<img width="781" alt="image" src="https://user-images.githubusercontent.com/18686082/197203499-7e5a7e86-0d20-4d00-a042-98e83e850c29.png">

**Comment by travisn** [comment]
Do you see mon pods now? The toolbox seems to be failing because the mons weren't created, but that doesn't match with the above message that the OSDs are being configured. The operator log may show some error.

**Comment by vyom-soft** [comment]
The operator log  
[rook-ceph-operator-log.txt](https://github.com/rook/rook/files/9839644/rook-ceph-operator-log.txt)

**Comment by travisn** [comment]
The toolbox pod is still crashing? Try deleting and re-creating it.

**Comment by vyom-soft** [comment]
> The toolbox pod is still crashing? Try deleting and re-creating it.

After reinstalling toolbox. It is running fine. thank you 
<img width="740" alt="image" src="https://user-images.githubusercontent.com/18686082/197386257-62c324f5-1ba0-4a5f-bf8e-489595465a94.png">

**Comment by travisn** [comment]
You have zero OSDs. See [this topic](https://rook.io/docs/rook/latest/Troubleshooting/ceph-common-issues/#osd-pods-are-not-created-on-my-devices) and the osd prepare logs to see how to create OSDs.

**Comment by vyom-soft** [comment]
> this topic

<img width="563" alt="image" src="https://user-images.githubusercontent.com/18686082/197600277-a522c0e1-057c-4122-8d1d-facfc2b31706.png">

**Comment by vyom-soft** [comment]
I have 6 nodes available. 
# Ability to override ceph.conf   [ceph-conf](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L15)
configOverride: |
  [global]
  mon_allow_pool_delete = true
  osd_pool_default_size = 6
  osd_pool_default_min_size = 4

Can I proceed this configs. To avoid that too many PGs per OSD

**Comment by vyom-soft** [comment]
> I have 8 nodes and would like to assign 6 nodes for storage.
> 
> storage: useAllNodes: false useAllDevices: true #deviceFilter: config: nodes: - name: "node3" devices: # specific devices to use for storage can be specified for each node - name: "sdb" - name: "node4" devices: - name: "sdb" - name: "node5" devices: - name: "sdb" - name: "node6" devices: - name: "sdb" - name: "node7" devices: - name: "sdb" - name: "node8" devices: - name: "sdb"
> 
> ##Ability to override ceph.conf [ceph-conf](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L15) configOverride: | [global] mon_allow_pool_delete = true osd_pool_default_size = 6 osd_pool_default_min_size = 4
> 
> Can I proceed with this configs. To avoid that too many PGs per OSD
> 
> _Generated rook-config-override has a bug_
> 
> apiVersion: v1 data: config: |**2**
> 
> ```
> [global]
> mon_allow_pool_delete = true
> osd_pool_default_size = 6
> osd_pool_default_min_size = 4
> ```
> 
> kind: ConfigMap metadata: annotations: meta.helm.sh/release-name: rook-ceph-cluster meta.helm.sh/release-namespace: rook-ceph creationTimestamp: "2022-10-26T11:25:35Z" labels: app.kubernetes.io/managed-by: Helm name: rook-config-override namespace: rook-ceph resourceVersion: "8037545" uid: d12bb61a-8e00-4eb1-89d7-753e61d0be53
> 
> I dont know why that **2** is appended in rook-config-override ?. I have verified the values.yaml correctly.

I edited the rook-config-override and applied it.  kubectl -n rook-ceph edit configmap rook-config-override

And then I read this also [rook-config-override](https://rook.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-configuration/#example) i.e I restarted the operator 
The changes are not seen in the cluster ? 
[rook-config-override.txt](https://github.com/rook/rook/files/9870749/rook-config-override.txt)

**Comment by travisn** [comment]
> The changes are not seen in the cluster ? Why is again only 2 osd seen ...

You'll need to look at the osd prepare logs on each node where you don't see an osd pod created. Rook must be skipping the `sdb` devices if they appear in use. If so, try [wiping them clean](https://rook.io/docs/rook/latest/Getting-Started/ceph-teardown/#zapping-devices) again on those nodes where they aren't being created.

> I edited the rook-config-override and applied it. kubectl -n rook-ceph edit configmap rook-config-override

Instead of setting those ceph settings in the override, with rook you'll need to set them in the pool spec, for example like this:
```yaml
  replicated:
    size: 6
  parameters:
    min_size: "4"
```

**Comment by travisn** [comment]
You need quotes around the "4" in parameters. I know it's confusing since `size: 6` does not need quotes around the 6.

**Comment by vyom-soft** [comment]
> You need quotes around the "4" in parameters. I know it's confusing since `size: 6` does not need quotes around the 6.

Thank you for the attention. I did not use the min_size as. I went ahead without it. I think it is not working even after surrounding with quotes. I used the replicated with size 6.
I did cleaned up as per suggestion. ([wiping them clean](https://rook.io/docs/rook/latest/Getting-Started/ceph-teardown/#zapping-devices))

As of now the status is still in WARN 

And in the operator log .
| op-osd: waiting... 6 of 6 OSD prepare jobs have finished processing and 2 of 6 OSDs have been updated
 | op-osd: OSD 5 is not ok-to-stop. will try updating it again later
 | op-osd: OSD 2 is not ok-to-stop. will try updating it again later
 | op-osd: OSD 3 is not ok-to-stop. will try updating it again later
| op-osd: OSD 4 is not ok-to-stop. will try updating it again later

bash-4.4$ ceph -s
  cluster:
    id:     500a3a7e-26ff-4e74-af4a-d1146c2d0425
    health: **HEALTH_WARN**
            clock skew detected on mon.b, mon.c

  services:
    mon: 3 daemons, quorum a,b,c (age 41m)
    mgr: a(active, since 39m), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 6 osds: 6 up (since 40m), 6 in (since 40m)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   12 pools, 337 pgs
    objects: 232 objects, 460 KiB
    usage:   196 MiB used, 600 GiB / 600 GiB avail
    pgs:     337 active+clean

  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
I did verifid the provision logs, seems fine. (attached)
[rook-ceph-osd-prepare-node6-8-provision.txt](https://github.com/rook/rook/files/9882451/rook-ceph-osd-prepare-node6-8-provision.txt)

Please suggest what else I should look for. thank you.
