### ISSUE TITLE
crush map not updated after modifying deviceClass of exsting object store pool

### ISSUE THREAD

**Issue by jansmets** [rook/rook#11155]
Rook 1.9.12
Ceph 17.2.3

I have an all nvme cluster where I have initially created 2 pools :

```
cephBlockPools:
  - name: apps
    spec:
      failureDomain: host
      replicated:
        size: 3
      deviceClass: nvme
<snip>
cephObjectStores:
  - name: s3
    spec:
      metadataPool:
        failureDomain: host
        replicated:
          size: 3
      dataPool:
        failureDomain: host
        replicated:
          size: 3
<snip>
```

Note that the object store pools do not have a         deviceClass.

The crush map for the block pool is
```
    {
        "rule_id": 1,
        "rule_name": "apps",
        "type": 1,
        "steps": [
            {
                "op": "take",
                "item": -2,
                "item_name": "default~nvme"
            },
            {
                "op": "chooseleaf_firstn",
                "num": 0,
                "type": "host"
            },
            {
                "op": "emit"
            }
        ]
    },
```

The crush map for the rgw DATA pool is:

```
    {
        "rule_id": 8,
        "rule_name": "s3.rgw.buckets.data",
        "type": 1,
        "steps": [
            {
                "op": "take",
                "item": -1,
                "item_name": "default"
            },
            {
                "op": "chooseleaf_firstn",
                "num": 0,
                "type": "host"
            },
            {
                "op": "emit"
            }
        ]
    }
```
So far this is all expected.

Next I changed the object store pools to add `deviceClass: nvme`
The operator logs show this is being picked up:
```
2022-10-16 08:21:09.299635 I | ceph-spec: CR has changed for "s3". diff=  v1.ObjectStoreSpec{
        MetadataPool: v1.PoolSpec{
                FailureDomain:   "host",
                CrushRoot:       "",
-               DeviceClass:     "",
+               DeviceClass:     "nvme",
                CompressionMode: "",
                Replicated:      {Size: 3},
                ... // 6 identical fields
        },
        DataPool: v1.PoolSpec{
                FailureDomain:   "host",
                CrushRoot:       "",
-               DeviceClass:     "",
+               DeviceClass:     "nvme",
                CompressionMode: "",
                Replicated:      {Size: 3},
                ... // 6 identical fields
        },
```

However I was expecting the crush map to change from `default` to `default~nvme`

(slightly offtopic... but for reference...)

The main reason why I was looking at this is that I'm trying to figure out why the PG autoscaler isn't working
`ceph osd pool autoscale-status` returns nothing (it is enabled in mgr, enabled on pool, etc) , which seems to indicate that one pool may span multiple crush roots.  (as per the Note at https://docs.ceph.com/en/latest/rados/operations/placement-groups/)
And indeed the mgr reports:
```
debug 2022-10-16T09:30:13.405+0000 7f7dd06a4700  0 [pg_autoscaler ERROR root] pool 10 has overlapping roots: {-1, -2}
```
which is : 
```
pool 10 'apps' replicated size 3 min_size 2 crush_rule 1 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 7205 flags hashpspool,selfmanaged_snaps stripe_width 0 application rbd
```
In that regard it's probably better if I remove the deviceClass from the 'apps' block pool (?)

```
ceph osd crush tree --show-shadow
ID   CLASS  WEIGHT     TYPE NAME
 -2   nvme  128.07947  root default~nvme
 -4   nvme   32.01987      host node140~nvme
  2   nvme    2.91089          osd.2
<snip>
 -6   nvme   32.01987      host node141~nvme
  1   nvme    2.91089          osd.1
<snip>
 -8   nvme   32.01987      host node142~nvme
  0   nvme    2.91089          osd.0
<snip>
-10   nvme   32.01987      host node143~nvme
 10   nvme    2.91089          osd.10
<snip>
 -1         128.07947  root default
 -3          32.01987      host node140
  2   nvme    2.91089          osd.2
<snip>
 -5          32.01987      host node141
  1   nvme    2.91089          osd.1
<snip>
 -7          32.01987      host node142
  0   nvme    2.91089          osd.0
<snip>
 -9          32.01987      host node143
 10   nvme    2.91089          osd.10
<snip>
```

**Comment by travisn** [comment]
IIRC the deviceClass is only set during initial pool creation and the crush rule will not be updated later. You may need to either delete the pool and create it again to have a clean slate, or you may try updating the device class manually from the toolbox if you can find the needed ceph commands. And we should likely have the operator support the deviceClass update as well.

**Comment by travisn** [comment]
For example, to change the device class on a pool you could first create a new pool with `deviceClass: nvme`. You won't use this pool, but rook will create the needed CRUSH rule for you. 

Then from the toolbox, run a command to update the original pool to use the new CRUSH rule. For this example, let's say the original pool is named `pool1` and the temporary pool is `pool1-nvme`.
```
ceph osd pool set pool1 crush_rule pool1-nvme
```

Then if you look at the pool details, you will see two pools consuming the same crush_rule:
```
bash-4.4$ ceph osd pool ls detail
...
pool 3 'pool1' replicated size 1 min_size 1 crush_rule 4 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 48 flags hashpspool,selfmanaged_snaps stripe_width 0 application rbd
pool 4 'pool1-nvme' replicated size 1 min_size 1 crush_rule 4 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 46 flags hashpspool,selfmanaged_snaps stripe_width 0 application rbd

```

**Comment by jansmets** [comment]
For reference,
I had one pool that was created with deviceClass: nvme and other pools without it. 
For te 'apps' pool the crush root was 'default~nvme'. 
Having pools with different crush roots breaks the pg autoscaler. 

```
    {
        "rule_id": 1,
        "rule_name": "apps",
        "type": 1,
        "steps": [
            {
                "op": "take",
                "item": -2,
                "item_name": "default~nvme"
            },
            {
                "op": "chooseleaf_firstn",
                "num": 0,
                "type": "host"
            },
            {
                "op": "emit"
            }
        ]
    },
```
Te resolve I first renamed the existing crush rule:
`ceph osd crush rule rename apps apps-nvme`
Then created a new crush rule with the correct root: (`default` instead of `default~nvme`)
`ceph osd crush rule create-simple apps default host firstn`
You can verify that the rules are similar with `ceph osd crush rule dump` (except for the root ofcourse)
As last step change the crush rule of the relevant pool(s)
`ceph osd pool set apps crush_rule apps`
After that my autoscale started working (`ceph osd pool autoscale-status`)
