### ISSUE TITLE
Documenting steps for capturing coredump of a process

### ISSUE THREAD

**Issue by gauravsitlani** [rook/rook#11151]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
- Collect the coredump of a process.

**What is use case behind this feature:**
- For troubleshooting purposes.

**Environment**:

There are 2 cases for capturing the coredump:
1. For a process which is segfaulting
2. Capture the coredump of a live process.

**Comment by gauravsitlani** [comment]
1. Here are the steps for the process which is segfaulting:

For example for a monitor pod/process:
- Make sure to check if the pod/deployment has the following securityContext:
```
    securityContext:
       privileged: true
```
- Take a backup of the deployment.
- Copy the command of the process from the pod from `ps aux|grep <ceph_process>` output
- Remove the startup and liveness probes from the deployment.
- Modify the deployment, remove the command of the respective ceph process and add a `sleep` command there for example `sleep 3600` based on how frequent the process is seg faulting.
- Navigate into the container for the respective process:
```
# kubectl -n rook-ceph exec -it deploy/rook-ceph-mon-d -- bash
```
- Take a backup of the current `core_pattern` :
```
# sysctl -a|grep core_pattern
```

- Modify the `core_pattern`:
```
# sysctl -w kernel.core_pattern="/tmp/core.%e.%p.%h.%t"
```

- Navigate to the `/tmp/` directory and check for the core file.

**Comment by gauravsitlani** [comment]
@travisn @galexrt can you please review the above steps for documentation purposes. 

If we can make the above coredump collection process easier, maybe we can automate this in `rook-ceph` krew plugin if possible.

**Comment by travisn** [comment]
Based on [this comment](https://github.com/rook/rook/issues/10788#issuecomment-1279179168), it's expected for the core dumps to be on the host without any further config from Rook. If we can confirm this, I don't know that we have much to do in rook or krew.

**Comment by gauravsitlani** [comment]
@travisn based on the default kernel core_pattern i didn't find the coredump at the location @leseb mentioned.

**Comment by gauravsitlani** [comment]
Based on [this comment](https://github.com/rook/rook/issues/10788#issuecomment-1280809186l) i think we should have `logCollector` enabled in order to collect the coredump . @travisn do you think we should have it enabled by default ?
