### ISSUE TITLE
Add k8s manifest format option to create-external-cluster-resources.py

### ISSUE THREAD

**Issue by AlexHill** [rook/rook#11157]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
[create-external-cluster-resources.py](https://github.com/rook/rook/blob/v1.10.3/deploy/examples/create-external-cluster-resources.py) should have a `--format manifest` option which directly generates a valid K8s manifest that describes the K8s resources required to integrate with an external cluster. That manifest could then be applied to the cluster using kubectl without the need for import-external-cluster.sh.

Additionally, it would be good if this script could output to stderr status messages indicating when anything is changed or created on the Ceph side.

**What is use case behind this feature:**
This was motivated by the difficultly in writing an Ansible role that implements the [documented external cluster process](https://rook.io/docs/rook/v1.10/CRDs/Cluster/external-cluster/), but I believe would simplify the process for all users. Slack discussion has also raised the use-case of GitOps-driven cluster management which relies on manifests.

[Slack discussion here](https://rook-io.slack.com/archives/CK9CF5H2R/p1665464169001099)

In detail:
When following best practices, Ansible tasks should a) be idempotent and b) accurately report whether anything was changed by running them. This isn't possible to achieve with the current external cluster process but could be with a few minor tweaks.

The current process boils down to
1. run create-external-cluster-resources.py to ensure that the necessary entities (auth etc) exist on the Ceph side
2. copy the output of that, in the form of environment variable exports, into a shell
3. run [import-external-cluster.sh](https://github.com/rook/rook/blob/v1.10.3/deploy/examples/import-external-cluster.sh) with those env vars, which invokes `kubectl create` to create the necessary resources.

Step 3 can't be repeated because it issues `kubectl create` commands which fail on a second invocation due to the resource already existing.

If create-external-cluster-resources.py generated a manifest directly, the equivalent steps would be.
1. run create-external-cluster-resources.py to ensure that the necessary entities (auth etc) exist on the Ceph side
2. pass the output to `kubectl create -f`

However the key thing is that that manifest could be used in other ways, i.e. with `kubectl apply`, committed to a repository as part of a GitOps workflow, or in my case passed to the `kubernetes.core.k8s` Ansible module.

**Comment by AlexHill** [comment]
_further activity_

**Comment by lknite** [comment]
Somehow, after standing up a cluster, it needs to be easy to add to 'argocd' or 'flux' a helm chart with the correct information which can then be targeted to all clusters which will consume the source ceph cluster.

I'm new to ceph, have setup a ceph cluster using the two helm charts, and have been working for a few days to get the right files to deploy to client clusters by following [external-cluster](https://rook.io/docs/rook/v1.10/CRDs/Cluster/external-cluster/?h=external#multi-tenancy), yet so far haven't been able to succeed.  Maybe the steps aren't specific enough, because I was able to spin things up so quickly using helm, that perhaps my environment isn't ready to run the create-external-cluster-resources.py, but really ... shouldn't the scripts run within the deployed pods where all the needed tools and libraries are already present?

**Comment by parth-gr** [comment]
> Somehow, after standing up a cluster, it needs to be easy to add to 'argocd' or 'flux' a helm chart with the correct information which can then be targeted to all clusters which will consume the source ceph cluster.
> 
> I'm new to ceph, have setup a ceph cluster using the two helm charts, and have been working for a few days to get the right files to deploy to client clusters by following [external-cluster](https://rook.io/docs/rook/v1.10/CRDs/Cluster/external-cluster/?h=external#multi-tenancy), yet so far haven't been able to succeed. Maybe the steps aren't specific enough, because I was able to spin things up so quickly using helm, that perhaps my environment isn't ready to run the create-external-cluster-resources.py, but really ... shouldn't the scripts run within the deployed pods where all the needed tools and libraries are already present?

You have to run python script on source ceph cluster RHCS

**Comment by lknite** [comment]
Having a little more experience now, maybe a script something like:
python3 ./get-external-cluster-resources.py <storage-class>
python3 ./get-external-cluster-resources.py ceph-block > external-resources-ceph-block.yaml
python3 ./get-external-cluster-resources.py ceph-filesystem > external-resources-ceph-filesystem.yaml

This would be more around the import-external-cluster.py script than the create-external-cluster-resources.py though.

**Comment by lknite** [comment]
In that documentation it mentions things to deploy, I would think the existing 'rook' helm chart would do these steps automatically, or a new 3rd helm chart for the external cluster:

Deploy Rook, create [common.yaml](https://github.com/rook/rook/blob/master/deploy/examples/common.yaml), [crds.yaml](https://github.com/rook/rook/blob/master/deploy/examples/crds.yaml) and [operator.yaml](https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml) manifests.

Create [common-external.yaml](https://github.com/rook/rook/blob/master/deploy/examples/common-external.yaml) and [cluster-external.yaml](https://github.com/rook/rook/blob/master/deploy/examples/cluster-external.yaml)

**Comment by lknite** [comment]
bump

**Comment by lknite** [comment]
Bump, ok, I'll submit a pull request...

**Comment by lknite** [comment]
bump again, should have some time this month to work on this

**Comment by lknite** [comment]
Pull request submitted https://github.com/rook/rook/pull/12710

**Comment by lknite** [comment]
My script doesn't work anymore, seems the import-external-cluster.sh script has been changed.  I'm guessing we won't get this feature until one of the maintainers begins experimenting with argocd or flux.

**Comment by lknite** [comment]
note, the script won't work if you are in the context of the ceph cluster, it must be a different context in order for the files to be generated.

**Comment by lknite** [comment]
Updated work-around script:
```
cat export-external-cluster.sh 
#!/bin/bash
###############################

USAGE=$(cat <<-'EOF'
# download the create-external-cluster-resource.py script
pushd /tmp || exit
curl -LOs https://raw.githubusercontent.com/rook/rook/master/deploy/examples/create-external-cluster-resources.py
popd || exit

# cp script into toolbox pod
toolbox=$(kubectl -n rook-ceph get pod -l app=rook-ceph-tools -o jsonpath='{.items[*].metadata.name}')
kubectl -n rook-ceph cp /tmp/create-external-cluster-resources.py $toolbox:/etc/ceph/

# run script via the toolbox pod (you have to specify what you are exporting here, e.g. 'rbd-data-pool-name')
kubectl -n rook-ceph exec -it $toolbox -- python3 /etc/ceph/create-external-cluster-resources.py \
  --rbd-data-pool-name ceph-rbd \
  --cephfs-filesystem-name cephfs \
  --namespace rook-ceph \
  --format bash > env.sh
EOF
)

# Check for required parameter
if [ -z $1 ] || [ -z $2 ]; then
  echo "Syntax:"
  echo ""
  echo "$0 <fullPath>/env.sh <outputPath>"
  echo ""
  echo "..."
  echo "To generate 'env.sh' perform something similar to:"
  echo ""
  echo "$USAGE"

  exit 1
fi

# load up passed in variables
SOURCE=$1
OUTPUT=$2

# make sure output folder exists
if [ ! -d $OUTPUT ]; then
  echo "Output folder '$OUTPUT' not found, abort."

  exit 1
fi

# change into output folder
pushd $OUTPUT > /dev/null || exit

# make sure source file exists
if [ ! -f $SOURCE ]; then
  echo "Source file '$SOURCE' not found, be sure to use full path, abort."

  popd > /dev/null || exit
  exit 1
fi

# download the import-external-cluster.sh script, we will modify this to export values
echo -n "downloading import-external-cluster.sh, we will modify this to export values ..."
curl -LOs https://raw.githubusercontent.com/rook/rook/master/deploy/examples/import-external-cluster.sh
echo " done"

# convert import script to dump yaml files named with the function name rather than run kubectl apply
# or, if the previous technique didn't work then try to make it display the resource to standard out
# also be sure to add in '---' between resources
echo -n "generating modified export script ..."
cp ./import-external-cluster.sh ./tmp-import.sh
sed 's/| kubectl create -f -/| tee "${FUNCNAME}.yaml"/g' ./tmp-import.sh > tmp-import-one.sh
sed 's/  create \\/  create --dry-run=client -o yaml \\/g' ./tmp-import-one.sh > tmp-import-two.sh
sed 's/  kubectl -n/  echo "---"; kubectl -n/g' ./tmp-import-two.sh > tmp-import.sh
sed -i '/tee/a ---' tmp-import.sh
echo " done"

# need to remove '\r' from environment script
echo -n 'removing "\r" from environment script, if present ...'
sed -i "s/\r//g" $SOURCE
echo " done"

# load up the environment variables generated before using 'create-external-cluster-resources.py' via the toolbox pod
. $SOURCE

# run import script which will generate yaml files and also dump to standout additional resources
echo -n "generating resources external clusters will need ..."
bash ./tmp-import.sh > additional-resources.yaml
echo " done"

# download additional required resources
echo -n "downloading additional required resources 'common-external.yaml' & 'cluster-external.yaml' ..."
curl -LOs https://raw.githubusercontent.com/rook/rook/master/deploy/examples/common-external.yaml
sed -i 's/rook-ceph-external # namespace:cluster/rook-ceph/g' ./common-external.yaml
curl -LOs https://raw.githubusercontent.com/rook/rook/master/deploy/examples/cluster-external.yaml
sed -i 's/rook-ceph-external # namespace:cluster/rook-ceph/g' ./cluster-external.yaml
echo " done"

# cleanup, remove the modified script we created so only usable files are left
# cleanup, remove the generated 'tmp-import.sh' script used to export resources
echo -n "cleaning up ..."
rm import-external-cluster.sh
rm tmp-import.sh
rm tmp-import-one.sh
rm tmp-import-two.sh
echo " done"

# return to original folder
popd > /dev/null || exit
```

**Comment by lknite** [comment]
now reinstalling, visiting this ticket to remember how to get the needed exported yaml
