### ISSUE TITLE
Importance of PDB for Rook

### ISSUE THREAD

**Issue by zeaone** [rook/rook#11174]
The usage scenarios of PDB are limited. Protection of the cluster by the PDB except for executing the `kubectl drain` command. Does the production environment need to enable PDB?

**Comment by sp98** [comment]
The main use case is to prevent data unavailability or loss that might happen in case of node drain event. For example: OSD pdb will prevent users from draining more than one OSD pods from different failure domain. 

It is recommended to use it for the production environment. User can also remove it from the cephCluster CR.

**Comment by sp98** [comment]
Closing this for now. Please open a github discussion or reach out on Rook slack if you want to discuss more about this.
