### ISSUE TITLE
NetworkPolicy implementation

### ISSUE THREAD

**Issue by jpds** [rook/rook#1117]
Rook should have a Kubernetes NetworkPolicy defined to control traffic travelling between different Rook components.

An easy way to test this would be to use canal as a CNI to enforce the policies.

**Comment by stefanfritsch** [comment]
Hi,

as a stopgap until this is implemented, is there some documentation which traffic needs to be allowed if we want to enable NetworkPolicy ourselves?

Cordoning off the rook namespaces will keep the volumes from working but which pods need to be accessible for everything to work?

Thanks,
Stefan

**Comment by matthiasritter** [comment]
Hi,
we'd be interested, too.
I've tested a few things but haven't found a working solution yet.
Thanks,
Matthias

**Comment by travisn** [comment]
Rook has [network policy](https://github.com/rook/rook/blob/release-1.4/cluster/examples/kubernetes/ceph/cluster.yaml#L70-L84) in the cluster CR, for example to use host networking or multus. Another option for the OSD cluster network is also described [here](https://rook.github.io/docs/rook/v1.4/ceph-advanced-configuration.html#osd-dedicated-network).
