### ISSUE TITLE
rename the master branch to main

### ISSUE THREAD

**Issue by gauravsitlani** [rook/rook#11196]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
- Rename the master branch to main

**What is use case behind this feature:**
- In an effort to use more inclusive language, suggesting to rename the master branch to main.

**Environment**:

**Comment by travisn** [comment]
I hope everyone feels we have a very inclusive culture in practice in the rook community. In my view, the name of the branch does not reflect being inclusive or not, but it's about the words and actions of the team members. Given the amount of disruption this would cause for everyone on the project and the pain of renaming the branch, impact on the CI, etc, my vote is to not change it.

**Comment by subhamkrai** [comment]
> I hope everyone feels we have a very inclusive culture in practice in the rook community. In my view, the name of the branch does not reflect being inclusive or not, but it's about the words and actions of the team members. Given the amount of disruption this would cause for everyone on the project and the pain of renaming the branch, impact on the CI, etc, my vote is to not change it.

+1

also, I feel like I have finger memory I always type `master` and kind of daily practice now 😅

**Comment by zalsader** [comment]
If we ever revisit this decision in the future, Github has an official guide on how to do this: https://github.com/github/renaming
