### ISSUE TITLE
timeout expired waiting for volumes to attach/mount for pod on rancher

### ISSUE THREAD

**Issue by xetys** [rook/rook#1119]
Hey rook guys,

I struggled the whole weekend on trying to bring up a rook cluster with dynamic provisioning on my rancher 1.6 managed kubernetes cluster.

## the issue

When I try to deploy the mysql-wordpress example, the PV is created like charm, but the pod fails to start because of

```
Unable to mount volumes for pod "wordpress-mysql-918363043-g21k7_default(e878aa1f-b78a-11e7-9a26-02ca365dab4f)": timeout expired waiting for volumes to attach/mount for pod "default"/"wordpress-mysql-918363043-g21k7". list of unattached/unmounted volumes=[mysql-persistent-storage]

Error syncing pod
```

## What I already tried

* I installed RBD to my host
* I installed all CRDs, like Cluster and Pool, and it seems that none of the components are reporting any issues. The pod just doesn't connect to the volume

Thanks in advance

**Comment by kokhang** [comment]
@xetys are you using coreos? and can you share the logs of the `rook-agents`. `kubectl -n rook-system logs <rook-agent pod>`

**Comment by xetys** [comment]
I'm using ubuntu 16.04

```
# kubectl logs -n rook-system rook-agent-dv9kw
2017-10-23 00:38:56.513214 I | rook: starting Rook v0.5.0-192.g1e17da7 with arguments '/usr/local/bin/rook agent'
2017-10-23 00:38:56.514521 I | rook: flag values: --help=false, --log-level=INFO
2017-10-23 00:38:56.515469 I | rook: starting rook agent
2017-10-23 00:38:56.515797 I | exec: Running command: modinfo -F parm rbd
2017-10-23 00:38:56.524938 I | exec: Running command: modprobe rbd single_major=Y
2017-10-23 00:38:56.752670 I | rook-flexvolume: Rook Flexvolume configured
2017-10-23 00:38:56.752802 I | rook-flexvolume: Listening on unix socket for Kubernetes volume attach commands.
```

**Comment by kokhang** [comment]
Looks like the agents installed propertly. But no attachment requests have been detected. Can you give me more information about the volume you are trying to use. Do `kubectl get pv <pv name>`

**Comment by kokhang** [comment]
@xetys please head over to our rook slack in https://github.com/rook/rook#contact.  You will find us there and should be able to assist you better.

**Comment by xetys** [comment]
Here is the solution we figured out on slack:


```
$ mount --bind /var/lib/rancher/etc/vol-plugins /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
```

and then redeploy the kubernetes stack with additional kubelet flag: `--volume-plugin-dir=/var/lib/rancher/etc/vol-plugins`


Maybe an upgrade to the docs to close this issue?

**Comment by jbw976** [comment]
I believe we have determined that the bind mount is not needed.  For Rancher, this should be all that's needed according to @kokhang on Slack:
> there is a workaround to make flexvolume work with rancher. It is to pass `--volume-plugin-dir=/var/lib/rancher/etc/volumeplugins` to kubelet and restart prior to deploying rook. Kudos to @mein_man for helping with this
> I'll document this and look for a permanent fix so we don't have to do modify kubelet
> @theagent I think rancher provides a way to update kubelet easily. @mein_man can correct me but I think it is Rancher UpToDate

**Comment by xetys** [comment]
Hey, I did a test with a fresh environment to prove that fact. It's sufficient just to add the kubelet flag, and it works.

**Comment by jbw976** [comment]
Thanks for confirming and for all your help @xetys.  The documentation for pre-reqs has been updated in master: https://github.com/rook/rook/blob/master/Documentation/k8s-pre-reqs.md#rancher
