### ISSUE TITLE
If etcd state is lost, cluster may be unrecoverable

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#112]
If the state stored in etcd is lost it may not be possible to recover the cluster.
1. The etcd state should be backed up somewhere.
2. In the case of an etcd state loss the cluster should be able to come up with empty etcd.

Number 2 is a problem because the discovery.etcd.io token names etcd members which are nolonger valid.  This could be fixed by an enhanced discovery service.

Steps to reproduce:
1. Issue a new discovery token.
2. Boot a multi-node cluster onto ramfs and allow the cluster to come up.
3. Reboot the cluster with the same discovery token from step 1.
4. Nodes will hang because of the confused state of etcd.

Expected - either:
- Etcd state would be restored from backup OR
- Discovery information would be reset and the cluster would be brought up "cold".

Dan

**Comment by travisn** [comment]
Closing all tickets related to standalone. See #985.
