### ISSUE TITLE
MountVolume.MountDevice failed for volume "pvc" :- is still being used

### ISSUE THREAD

**Issue by voarsh2** [rook/rook#11201]
After  an ETCD restore of the cluster I have several issues around deleting PVC's, but I would need to check if the RBD image for them actually exists.

The main issue I am having is some workloads are not able to use PVC's because of the following error:

MountVolume.MountDevice failed for volume "pvc-df5fa52a-6c5e-4d7e-81aa-275c99affc74" : rpc error: code = Internal desc = rbd image replicapool/csi-vol-fe8ab815-02a8-11ed-90c3-4e2c2a481635 is still being used

PVC: pvc-df5fa52a-6c5e-4d7e-81aa-275c99affc74

RBD image: csi-vol-fe8ab815-02a8-11ed-90c3-4e2c2a481635

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I see no reference to the PVC for mounting in the provision pod.

[csi-rbdplugin-provisioner-9999d984f-lsdww_csi-rbdplugin.log](https://github.com/rook/rook/files/9851802/csi-rbdplugin-provisioner-9999d984f-lsdww_csi-rbdplugin.log)
[csi-rbdplugin-provisioner-9999d984f-lsdww_csi-provisioner.log](https://github.com/rook/rook/files/9851803/csi-rbdplugin-provisioner-9999d984f-lsdww_csi-provisioner.log)

Can see the RBD image is there, Volume has the image referenced. I can see VolumeAttachments only has one reference, and created when I try and run the workload - looks fine

**How to reproduce it (minimal and precise):**

Restore ETCD for a K8 cluster, you'll find some volumes (that existed at the time of the backup) could throw this error.

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Kernel (e.g. `uname -a`):
```
Linux worker1 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
```
rook: v1.9.9
go: go1.17.12
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
ceph version 16.2.10 (45fa1a083152e41a408d15505f594ec5f1b4fe17) pacific (stable)
```
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-13T19:01:10Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
HEALTH_WARN 21 daemons have recently crashed

**Comment by travisn** [comment]
Please give more background on the etcd restore.
1. Is this a test or was there an issue in the production cluster?
2. Were the PVCs created between the time of etcd backup and the restore? If so, some CRs for the volume attachments may be missing.
3. This only affects some PVCs, correct? Can you think of anything else different for the PVCs affected?

**Comment by Madhu-1** [comment]
@voarsh2 please also refer to https://rook.io/docs/rook/v1.10/Troubleshooting/ceph-csi-common-issues/#node-loss if there is node loss/ or node IP's got changed.

**Comment by voarsh2** [comment]
> @voarsh2 please also refer to https://rook.io/docs/rook/v1.10/Troubleshooting/ceph-csi-common-issues/#node-loss if there is node loss/ or node IP's got changed.

No node IP's changed, at the time of ETCD restore, all nodes were were running fine.

Trying to use this PVC just results in container creating (forever) and the error listed in the issue:
"rbd image replicapool/csi-vol-fe8ab815-02a8-11ed-90c3-4e2c2a481635 is still being used"


> Please give more background on the etcd restore.

> Is this a test or was there an issue in the production cluster?

This was a production environment. There were issues that required restoring ETCD - dangling orphaned CSI snapshots in Ceph that had no references, ETCD restore was used to restore VolumeSnapshot/VolumeSnapshotContents. Ceph images aren't super descriptive, making it difficult to work out if it is a source image, and what is a snapshot when trying to clean up redundant images for reclaiming storage space - perhaps someone here knows how to accurately work out how to find snapshots of RBD images. Kasten K10 suddenly having trouble creating snapshots.

> Were the PVCs created between the time of etcd backup and the restore? If so, some CRs for the volume attachments may be missing.

I didn't realise there were Custom Resources for PVC volume attachments.

Is there a different way I may copy/recreate the data to a new PVC despite not being able to mount this PVC - for data recovery?

> This only affects some PVCs, correct? Can you think of anything else different for the PVCs affected?

This particular PVC was created 3 months ago.  The ETCD restore was from the 8th this month, I do not know if this "glitch" for the rbd image is because the workload was running/restarting multiple times during the cluster ETCD restore.
Sorry if my reply isn't so helpful in reproducing this issue.

**Comment by Madhu-1** [comment]
>@voarsh2 please also refer to https://rook.io/docs/rook/v1.10/Troubleshooting/ceph-csi-common-issues/#node-loss if there is node loss/ or node IP's got changed.

>> No node IP's changed, at the time of ETCD restore, all nodes were were running fine.

>> Trying to use this PVC just results in container creating (forever) and the error listed in the issue:
"rbd image replicapool/csi-vol-fe8ab815-02a8-11ed-90c3-4e2c2a481635 is still being used"

If you are seeing this error in the csi-rbdplugin daemonset pods means some one already holds a lock on this one, if you are sure about that **No one** is using this rbd image you can go and remove the wather, the above paste link will help you.

>> I have found a similar issue when trying to delete some PVC's- the csi-rbdplugin-provisioner shows image is still being used.

Same here if someone is using the rbd image cephcsi will not allow to delete it, if you are sure that ** No one ** is using it, you can go ahead and remove the watcher, it will help to remove the rbd image and the PV.

**Comment by voarsh2** [comment]
> > >
> 
> If you are seeing this error in the csi-rbdplugin daemonset pods means some one already holds a lock on this one, if you are sure about that **No one** is using this rbd image you can go and remove the wather, the above paste link will help you.

The CSI doc page doesn't have documentation on removing a watcher.

I tried rbd showmapped - and I don't see ```csi-vol-fe8ab815-02a8-11ed-90c3-4e2c2a481635``` as mapped.

I ran this:
```
rbd status -p replicapool csi-vol-fe8ab815-02a8-11ed-90c3-4e2c2a481635   
Watchers:
        watcher=10.42.182.0:0/2359070641 client.35594571 cookie=18446462598732840969
```

If it were mapped I could do:
```
rbd unmap /dev/rbdX
```

```
bash-4.4$ rbd lock ls -p replicapool csi-vol-fe8ab815-02a8-11ed-90c3-4e2c2a481635

bash-4.4$ rbd lock rm -p replicapool csi-vol-fe8ab815-02a8-11ed-90c3-4e2c2a481635
rbd: lock id was not specified
```


So, I am not really sure how to remove the watcher.

**Comment by voarsh2** [comment]
No one can tell me how to mount this rbd/volume so I can fsck it?

**Comment by Madhu-1** [comment]
If you are trying it from the toolbox pod you need to try it from the direct-mount jobhttps://rook.io/docs/rook/v1.10/Troubleshooting/direct-tools/?h=map+rbd#start-the-direct-mount-pod

**Comment by voarsh2** [comment]
> If you are trying it from the toolbox pod you need to try it from the direct-mount jobhttps://rook.io/docs/rook/v1.10/Troubleshooting/direct-tools/?h=map+rbd#start-the-direct-mount-pod

Thanks for the heads up - I was able to mount and fsck the image.

**Comment by yan636** [comment]
Is there a fix for this?

**Comment by Madhu-1** [comment]
> Is there a fix for this?

What fix are you looking for? If it's for `is still being used,` its a safer check to avoid corruption, there is no automated way of recovery, it still needs admin intervention.

**Comment by Madhu-1** [comment]
Closing this onf as user is able to mount and run fsck on the image and able to recover
