### ISSUE TITLE
CephObjectStore in external mode with SSL-enabled RGW does not work

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#11208]
**Is this a bug report or feature request?**
* Bug Report

I'm trying to configure External mode cluster with SSL enabled for RGW.

In the events I see following error, which seems to be the root cause:
```
failed to reconcile CephObjectStoreUser "<NAMESPACE>/<USERNAME>". failed to create/update object store user "<USERNAME>": failed to get details from ceph object user "<USERNAME>": Get "https://rook-ceph-rgw-<STORENAME>.<NAMESPACE>.svc:443/admin/user?format=json&amp;uid=<USERNAME>": x509: certificate is valid for *.<RGWNODE>, <RGWNODE>, not rook-ceph-rgw-<STORENAME>.<NAMESPACE>.svc
```

**Deviation from expected behavior:**

The certificate SSL/TLS certificate is only valid for specific nodes that contain Ceph RGWs. Attempting to address the RGWs via the Kubernetes Service DNS name won't work.

**Expected behavior:**

Users should not have to add the Kubernetes Service endpoint to their certificates to make Rook able to create users (or buckets). Rook should use the endpooint(s) defined in the CephObjectStore CRD directly.

**How to reproduce it (minimal and precise):**

Create an external CephObjectStore and a CephObjectStoreUser for the store.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by leseb** [comment]
A few questions:

- Have we considered allowing insecure TLS? for `CephObjectStoreUser`, I believe libbucketprov allows it already so users could work around that problem
- Aren't we breaking the transparency promise between managed and external clusters? One goal was to provide the same experience, thus creating a Service with the endpoint slice.
- I wonder if we have a list of what we "lose" by removing the usage of Services, for instance, if we pass a single gw (like proposed) for each request, what if that gateway goes down? How is the service refreshed with a new running gw? It's probably worth exploring how the internal Kube DNS does a health check and if it does at all.

**Comment by BlaineEXE** [comment]
I wonder if Kube DNS does anything at all given the struct's description:

```
// EndpointAddress is a tuple that describes single IP address.
// +structType=atomic
type EndpointAddress struct {
	// The IP of this endpoint.
	// May not be loopback (127.0.0.0/8), link-local (169.254.0.0/16),
	// or link-local multicast ((224.0.0.0/24).
	// IPv6 is also accepted but not fully supported on all platforms. Also, certain
	// kubernetes components, like kube-proxy, are not IPv6 ready.
	// TODO: This should allow hostname or IP, See #4447.
	IP string `json:"ip" protobuf:"bytes,1,opt,name=ip"`
	// The Hostname of this endpoint
	// +optional
	Hostname string `json:"hostname,omitempty" protobuf:"bytes,3,opt,name=hostname"`
	// Optional: Node hosting this endpoint. This can be used to determine endpoints local to a node.
	// +optional
	NodeName *string `json:"nodeName,omitempty" protobuf:"bytes,4,opt,name=nodeName"`
	// Reference to object providing the endpoint.
	// +optional
	TargetRef *ObjectReference `json:"targetRef,omitempty" protobuf:"bytes,2,opt,name=targetRef"`
}
```

**Comment by BlaineEXE** [comment]
> A few questions:
> 
> * Have we considered allowing insecure TLS? for `CephObjectStoreUser`, I believe libbucketprov allows it already so users could work around that problem

Can we do this for an external RGW where Rook can't control its configuration? I have assumed not, but I may be wrong.

> * Aren't we breaking the transparency promise between managed and external clusters? One goal was to provide the same experience, thus creating a Service with the endpoint slice.

In some ways, I think the proposed changes are more transparent. But they do break the promise of being the same experience for both cases for sure. That's an important consideration.

One thing of note is that the Endpoint we create can't route to another Service in my testing (https://github.com/rook/rook/issues/10489), so we aren't able to create an external mode CephObjectStore that references another CephObjectStore in the same k8s cluster.

> * I wonder if we have a list of what we "lose" by removing the usage of Services, for instance, if we pass a single gw (like proposed) for each request, what if that gateway goes down? How is the service refreshed with a new running gw? It's probably worth exploring how the internal Kube DNS does a health check and if it does at all.

With the implementation I'm working on in https://github.com/rook/rook/pull/11202, if a gateway is down, a reconcile will fail, but the next reconcile will choose another endpoint at random to try again. This is the same behavior as how k8s sets up Services, so that doesn't really change.

And as mentioned in the update above, kube DNS isn't updating a down address to be in the `NotReadyAddresses` subset once the address is unavailable.

I think the only thing we are "losing" is having the same experience for both Rook-hosted and externally-hosted RGWs.

**Comment by BlaineEXE** [comment]
> > A few questions:
> > 
> > * Have we considered allowing insecure TLS? for `CephObjectStoreUser`, I believe libbucketprov allows it already so users could work around that problem
> 
> Can we do this for an external RGW where Rook can't control its configuration? I have assumed not, but I may be wrong.

I joined the RGW upstream sync today and got some clarification. Indeed, Rook can use insecure TLS for the connection. This is certainly an option. However, I think this may not be something we want to do realistically. Using an insecure connection means that Rook would be susceptible to man-in-the-middle attacks. My inclination is to prioritize security over a consistent experience. 

In an attempt to give users a consistent experience, I would propose to include `Endpoints` in the CephObjectStore Status as a first-class, typed field. This would be the most correct place for any other consumers to determine the endpoint(s) their applications may use to access the CephObjectStore. 

@leseb what do you think about these details?

**Comment by BlaineEXE** [comment]
I created an external mode CephObjectStore and confirmed that when a Service is created with no selectors and the Endpoints object is created manually with IPs in the `addresses` field, Kubernetes doesn't do any health checking to ensure the endpoints are reachable. None of the addresses move to `notReadyAddresses`, and curl calls to the service sometimes succeed and sometimes fail. It appears that we don't get any extra features by setting Endpoints; we would have to manage the health of them ourselves.
