### ISSUE TITLE
Need to check the fs whether it's exists

### ISSUE THREAD

**Issue by zhucan** [rook/rook#11204]
https://github.com/rook/rook/blob/0937eaee38999ddf3eaf618b5933112dc9128d1b/pkg/operator/ceph/file/controller.go#L248
if we delete the ceph fs with "ceph cmd" and the delete ceph fs from apiserver, because of the ceph fs not in backend storage, so check the dependencies failed, the ceph fs will not be deleted  forever. we need to remove fanalizer manually.

**Comment by zhucan** [comment]
But I think before we check the dependencies, we need to check the cephfs whether it exists.

**Comment by travisn** [comment]
Would you like to open a PR to check for it?

**Comment by zhucan** [comment]
yes
