### ISSUE TITLE
dependabot workflow automation for updating dependency

### ISSUE THREAD

**Issue by Rajpratik71** [rook/rook#11215]

**Comment by travisn** [comment]
@Rajpratik71 Could you provide more details about the bot?

**Comment by Rajpratik71** [comment]
Hi @travisn ,

@dependabot is used for automatically updating known dependency updates.

It will open a PR if it finds a version update in "go.mod" file.

Mainly it will add automation for updating versions, those PR will automatically got tested by CI.

Earlier it was a separate project but now it is natively integrated with Github as Github acquired it in [2019](https://www.crunchbase.com/acquisition/github-acquires-dependabot--2585bd2b) .

See this [official doc](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) for more details.

**Comment by travisn** [comment]
Thanks for the pointer, let's give it a try.
