### ISSUE TITLE
Can not delete an objectstore that if it's status is failure.

### ISSUE THREAD

**Issue by zhucan** [rook/rook#11212]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
The objectstore can be deleted successfully

**How to reproduce it (minimal and precise):**
1. Set the name of object store is "os-0f66d936-cd12-430a-841c-de9ea90dbe33"
2. Create the object store with this name
3. The deployment of the rgw will not be deployed but the pools was created successfully
4. The status of the objectsore is failure
5. Delete the objectstore and the status is always deleting

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary

Create failures: because of the name is too long.
`2022-10-26 06:26:40.207447 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/os-0f66d936-cd12-430a-841c-de9ea90dbe33". failed to create object store deployments: failed to create object store "os-0f66d936-cd12-430a-841c-de9ea90dbe33": failed to start rgw pods: failed to create rgw deployment: Deployment.apps "rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33-a" is invalid: [spec.template.spec.volumes[5].name: Invalid value: "rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33-mime-types": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[5].name: Not found: "rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33-mime-types"]`

Delete failures: because of can not found the dependencies
`2022-10-26 06:30:25.739609 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/os-0f66d936-cd12-430a-841c-de9ea90dbe33". failed to get dependents of CephObjectStore "rook-ceph/os-0f66d936-cd12-430a-841c-de9ea90dbe33": failed to list buckets in CephObjectStore "rook-ceph/os-0f66d936-cd12-430a-841c-de9ea90dbe33": Get "http://rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33.rook-ceph.svc:80/admin/bucket?": dial tcp 10.110.36.7:80: connect: connection refused`

**Cluster Status to submit**:
```
❯ ceph -s 

  cluster:
    id:     777ab30d-9dbe-418e-a1b3-6c6750e1f6ef
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 3h)
    mgr: b(active, since 3h), standbys: a
    osd: 6 osds: 6 up (since 45m), 6 in (since 45m)
 
  data:
    pools:   8 pools, 129 pgs
    objects: 28 objects, 5.6 KiB
    usage:   64 MiB used, 600 GiB / 600 GiB avail
    pgs:     129 active+clean
```

* Output of krew commands, if necessary
```
❯ kubectl get cephobjectstore -n rook-ceph
NAME                                      PHASE
os-0f66d936-cd12-430a-841c-de9ea90dbe33   Deleting

```
**Environment**:
* OS (e.g. from /etc/os-release):  CentOS Linux release 7.8.2003 (Core)
* Kernel (e.g. `uname -a`): .10.0-1127.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.9.8
* Storage backend version (e.g. for ceph do `ceph -v`): v16.2.10
* Kubernetes version (use `kubectl version`): v1.22.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment]
My major concern is 
```
2022-10-26 06:26:40.207447 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/os-0f66d936-cd12-430a-841c-de9ea90dbe33". failed to create object store deployments: failed to create object store "os-0f66d936-cd12-430a-841c-de9ea90dbe33": failed to start rgw pods: failed to create rgw deployment: Deployment.apps "rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33-a" is invalid: [spec.template.spec.volumes[5].name: Invalid value: "rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33-mime-types": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[5].name: Not found: "rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33-mime-types"]
```

Object store not creating just because of name error,
i see the c.store.name is big `os-0f66d936-cd12-430a-841c-de9ea90dbe33` which has to be reduced

**Comment by parth-gr** [comment]
THis name is probably given by user through CRD which needs to be small by defalut from the user end,

Should be need to add checks for name passing through the crds?

**Comment by BlaineEXE** [comment]
The easiest fix for this would be to add validation to the CRD to limit the length of the cephobjectstore name to 38 chars.

**Comment by zhucan** [comment]
> My major concern is
> 
> ```
> 2022-10-26 06:26:40.207447 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/os-0f66d936-cd12-430a-841c-de9ea90dbe33". failed to create object store deployments: failed to create object store "os-0f66d936-cd12-430a-841c-de9ea90dbe33": failed to start rgw pods: failed to create rgw deployment: Deployment.apps "rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33-a" is invalid: [spec.template.spec.volumes[5].name: Invalid value: "rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33-mime-types": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[5].name: Not found: "rook-ceph-rgw-os-0f66d936-cd12-430a-841c-de9ea90dbe33-mime-types"]
> ```
> 
> Object store not creating just because of name error, i see the c.store.name is big `os-0f66d936-cd12-430a-841c-de9ea90dbe33` which has to be reduced

yes, because of the name is too long,  so we can not delete the objectstore in the faliure status.

**Comment by parth-gr** [comment]
I was also thinking the above validation also for `labels`
