### ISSUE TITLE
rook-ceph not starting properly on kylin V10 SP1

### ISSUE THREAD

**Issue by greatljn** [rook/rook#11253]
rook Version：1.7.7
ceph Version：16.2.5
system Version：Kylin V10 SP1
kernel Version: 4.19.90-17.ky10.x86_64
Kubernetes Version：1.16.8
the rook-ceph cluster started at  first
![image](https://user-images.githubusercontent.com/17653563/199180330-9d404c47-1ea6-4974-beaf-e1290e92541e.png)
but then we found the obc we created stuck at pending status
![image](https://user-images.githubusercontent.com/17653563/199180598-477d3bdd-6a09-4b98-b551-702146a99602.png)
we entered into the toolbox pod, and we found all the ceph commands were very slow or just timeout
![image](https://user-images.githubusercontent.com/17653563/199180743-b691d1b5-773f-4620-ab44-84059ea74770.png)
we tried to trace the command and were stuck at
![image](https://user-images.githubusercontent.com/17653563/199181082-35fdb6a5-c052-412e-ad1b-c9fc68f14d77.png)
does anyone have any idea~

**Comment by clcc2019** [comment]
As far as I know it's a compatibility issue

**Comment by travisn** [comment]
@greatljn Does the rook operator log also show timeouts or other errors?

**Comment by greatljn** [comment]
> @greatljn Does the rook operator log also show timeouts or other errors?

yes, it will show ceph get version or status timeout, and radosgw-admin create/get user timeout
![image](https://user-images.githubusercontent.com/17653563/199392894-608bdaed-439c-4ff4-b805-1a79f84cf713.png)

**Comment by greatljn** [comment]
> As far as I know it's a compatibility issue

thanks, we will try some other way

**Comment by greatljn** [comment]
> @greatljn Does the rook operator log also show timeouts or other errors?

Do you know what exactly causes the compatible problem？

**Comment by travisn** [comment]
What do the logs for the rook-ceph-mgr-a pod show? That pod seems to be crashing and restarting frequently. It shouldn't cause all the failures you're seeing, but perhaps it is related.

**Comment by greatljn** [comment]
> What do the logs for the rook-ceph-mgr-a pod show? That pod seems to be crashing and restarting frequently. It shouldn't cause all the failures you're seeing, but perhaps it is related.

sometimes, the mgr pod just quit without any logs
and other times, it started for a while and then show logs as below
![image](https://user-images.githubusercontent.com/17653563/199664732-3c86448f-9777-40b9-b62d-423db7dc2a56.png)

**Comment by clcc2019** [comment]
Create 3 mons normally, check the mon node process after initialization, you will find that ms_dispatch and fn_monstore will have cpu 100% problem, and pg pool is being created at this time. Quickly kill these two processes ceph cluster is normal.

**Comment by greatljn** [comment]
> ms_dispatch

I ran in kubernetes, and didn't find ms_dispatch and fn_monstore in osd pods

**Comment by microyahoo** [comment]
hi @dgzdot, looks like it related with https://github.com/rook/rook/issues/10110#issuecomment-1464898937
