### ISSUE TITLE
Crash loop for CrashCollector for not supporting taint `node-role.kubernetes.io/control-plane=:NoSchedule`

### ISSUE THREAD

**Issue by yajo** [rook/rook#11258]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
If one of my nodes have the taint `node-role.kubernetes.io/control-plane=:NoSchedule`, the operator attempts to schedule its crashcollector pod, which fails always.

I managed to workaround the problem by adding this configuration to the cluster:

        placement:
          all:
            tolerations:
              - key: node-role.kubernetes.io/control-plane
                effect: NoSchedule
                operator: Exists

It seems however that there's no way to specify placement constrains specific to crashcollector pods.

**Expected behavior:** If the crashcollector is really required, then that taint should be tolerated. Otherwise, the deployment should be just removed.

**How to reproduce it (minimal and precise):**

1. Taint a server with `node-role.kubernetes.io/control-plane=:NoSchedule`
2. Deploy a ceph cluster.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
[rook-ceph.yaml.txt](https://github.com/rook/rook/files/9929739/rook-ceph.yaml.txt)

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): NixOS 22.05 (Quokka)
* Kernel (e.g. `uname -a`): Linux k3s-server01 5.15.58 #1-NixOS SMP Fri Jul 29 15:25:34 UTC 2022 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Hetzner Cloud
* Rook version (use `rook version` inside of a Rook Pod): v1.10.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10+k3s1", GitCommit:"826b9498df9578509e8c4b6906071592a6295159", GitTreeState:"clean", BuildDate:"1970-01-01T01:01:01Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTH_WARN mon b is low on available space; 1 daemons have recently crashed; Telemetry requires re-opt-in`

**Comment by travisn** [comment]
@yajo The crash collector pods are expected to start on each node where a ceph daemon pod (mon, mgr, osd, mds, rgw) is running. Are those pods running on the tainted nodes as well? It would be unexpected if the crash collector daemon  were started on tainted nodes with no other ceph pods.

**Comment by yajo** [comment]
> Are those pods running on the tainted nodes as well?

Yes, they are.

**Comment by travisn** [comment]
The crash collector has tolerations that are added from the same tolerations that had been applied to the ceph pods as seen [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/crash/reconcile.go#L193-L203). When the crash collector was not starting due to the lack of tolerations, the other ceph pods had the tolerations, right? They should have been picked up.

**Comment by yajo** [comment]
I think that the main problem was that I first deployed rook, and later I added the taints to those nodes. Strangely, all pods kept running instead of becoming faulty.

Later, when upgrading Rook, it attempted to recreate some pods, and then it became unable to schedule them.

**Comment by travisn** [comment]
Understood now, the tolerations needed to be applied before applying the taints in order to continue uninterrupted.

**Comment by yajo** [comment]
Then I guess this was my fault. Seems like `NoSchedule` doesn't have an effect if it was previously scheduled. Weird, I thought k8s was "declarative". Thanks anyway!

**Comment by travisn** [comment]
> Then I guess this was my fault. Seems like `NoSchedule` doesn't have an effect if it was previously scheduled. Weird, I thought k8s was "declarative". Thanks anyway!

Taints are certainly more disruptive than the average declarative state
