### ISSUE TITLE
Ability to set resources on discovery DaemonSet

### ISSUE THREAD

**Issue by bootc** [rook/rook#11265]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
It should be possible to set `resources` on the `rook-discover` DaemonSet / Pods.

**What is use case behind this feature:**
I have a cluster where it's particularly important to be able to manage resource requests/limits for all pods, and the `rook-discover` pods are the only ones I seem to be unable to configure resources on.

**Environment**:
Using Rook 1.10.4.

See also https://rook-io.slack.com/archives/C46Q5UC05/p1667495402580909?thread_ts=1667485901.577159&cid=C46Q5UC05

**Comment by parth-gr** [comment]
Does the resources property for `rook-discover` should be listed in CLuster CR, asking this because it is created during operator directly not exposing any other details from the cluster

**Comment by travisn** [comment]
> Does the resources property for `rook-discover` should be listed in CLuster CR, asking this because it is created during operator directly not exposing any other details from the cluster

The discover daemon is started similar to the csi driver, it corresponds to the overall operator and not to the cephcluster CR. So these resources would follow as similar pattern as the other [discovery settings](https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml#L544-L568).

**Comment by parth-gr** [comment]
./assign
