### ISSUE TITLE
Rook Flexvolume needs to improve to be able to run in all K8S cluster without admin intervention

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1127]
We have seen numerous issues with Rook not being able to map volumes when Kubelet is configured or deployed in certain ways. Here are the issues I have seen so far:

CoreOS:
- Kubelet runs in a container. The default flexvolume plugin dir is not host bind mounted.
- CoreOs has `/usr` directory readOnly. Thus the K8S default flexvolume plugin dir (`/usr/libexec/kubernetes/kubelet-plugins/volume/exec`) does not work.

Rancher:
- Same both issues as CoreOS.

Atomic:
- Kubelet is containerized however flexvolume plugin is able to configure. However the Kubernetes internal flexvolume plugin framework is not able to get output response from the driver. The output is always empty string.

**Comment by jbw976** [comment]
A Kubernetes feature has been opened to track this work: https://github.com/kubernetes/features/issues/500

**Comment by jbw976** [comment]
I'm beginning to think that it would be a worthwhile effort, independent of whether we can get something into upstream Kubernetes, to find and fix the Kubelet deployments/manifests in upstream OSs and environments also.  For example, can we open a PR in the following upstreams:
* CoreOS: update the kubelet.service unit file to pass the `--volume-plugin-dir` flag.  All CoreOS users would get a default that works with doing nothing.
* Rancher: update their Kubelet deployment to pass the `--volume-plugin-dir` flag for `/var/lib/rancher/...` by default, without user intervention.

If we can fix these in the OS/environments themselves, then a Kubernetes fix becomes slightly less essential (but we would definitely still want it).
