### ISSUE TITLE
install jenkins in K8s with rook-ceph, with error "failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Internal desc = rados: ret=-22, Invalid argument: "invalid pool layout 'replicapool' -- need a valid data pool""

### ISSUE THREAD

**Issue by BinaryWorld2099** [rook/rook#11272]
I was trying to install jenkins with three replica and Access Modes ReadWriteMany in PVC, in K8s with rook-ceph, 
with error "failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Internal desc = rados: ret=-22, Invalid argument: "invalid pool layout 'replicapool' -- need a valid data pool""

below is my yaml config
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - name: replicated
      replicated:
        size: 3
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  clusterID: rook-ceph
  pool: replicapool
  provisionVolume: "true"
  fsName: myfs
  imageFormat: "2"
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete

apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  failureDomain: host
  replicated:
    size: 3
  parameters:
    autoscale_mode: "on"

error:
![image](https://user-images.githubusercontent.com/106383882/200271751-784822a0-aa6b-4664-83cf-39ec9db85c88.png)

failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Internal desc = rados: ret=-22, Invalid argument: "invalid pool layout 'replicapool' -- need a valid data pool"

**Comment by zhucan** [comment]
The pool whether it's exists? and the status is? please run "rados lspool" and show the results.

**Comment by Madhu-1** [comment]
@BinaryWorld2099 can you please paste below output from the toolbox pod?

`ceph -s`
'ceph fs ls`

and more over you are mixing both rbd and cephfs terminologies in storageclass.

**Comment by Madhu-1** [comment]
Delete storageclass and PVC and Remove the below from your storageclass and recreate storageclass and PVC

```
pool: replicapool
provisionVolume: "true"
imageFormat: "2"
imageFeatures: layering
```

**Comment by BinaryWorld2099** [comment]
![image](https://user-images.githubusercontent.com/106383882/200273667-cd5514b5-be27-44e9-a486-d671a4afc3b5.png)

**Comment by BinaryWorld2099** [comment]
Trying you suggestion


> 

trying your suggestion, thanks

**Comment by BinaryWorld2099** [comment]
> Delete storageclass and PVC and Remove the below from your storageclass and recreate storageclass and PVC

pool: replicapool
provisionVolume: "true"
imageFormat: "2"
imageFeatures: layering
> 
> > 
> 
> trying your suggestion, thanks

**Comment by BinaryWorld2099** [comment]
> Delete storageclass and PVC and Remove the below from your storageclass and recreate storageclass and PVC
> 
> ```
> pool: replicapool
> provisionVolume: "true"
> imageFormat: "2"
> imageFeatures: layering
> ```

seems working now, thanks
Where can I check the related configuration?

**Comment by BinaryWorld2099** [comment]
One more thing,
What does "ret=-22" means in the error message?

**Comment by Madhu-1** [comment]
> > Delete storageclass and PVC and Remove the below from your storageclass and recreate storageclass and PVC
> > ```
> > pool: replicapool
> > provisionVolume: "true"
> > imageFormat: "2"
> > imageFeatures: layering
> > ```
> 
> seems working now, thanks Where can I check the related configuration?

please refer to https://rook.io/docs/rook/v1.10/Getting-Started/example-configurations/#shared-filesystem
