### ISSUE TITLE
[RFE] Ceph cluster logs should go to separate log files not in monitor log files

### ISSUE THREAD

**Issue by vumrao** [rook/rook#11282]
[RFE] Ceph cluster logs should go to separate log files, not in monitor log files 

Version of all relevant components (if applicable):
ODF 4.x

This feature will make sure that rook deployed Ceph has the default behavior that a default Ceph deployment will have. 

In Ceph the cluster logs are very important from a troubleshooting point of view and for now in the rook deployed cluster these logs go to monitor logs which makes it hard to make a clear investigation.

The cluster logs channel includes logs files like:

1. Ceph Audit log - ceph.audit.log
2. Cluster log - ceph.log

In Ceph this tuning is controlled via a tuning option called mon_cluster_log_to_file = true!

Downstream BZ - https://bugzilla.redhat.com/show_bug.cgi?id=2141094

**Comment by travisn** [comment]
There was some discussion in the past related to this in #9580. The takeaway was that all the info was available in the single log, so why separate it? Keeping a single log per daemon simplifies the log rotation as well.

If we look at an extract from the mon pod log, we see the different debug, audit, and cluster logs together:
```
debug 2022-11-08T20:37:04.388+0000 7fa012687700  0 log_channel(audit) log [DBG] : from='admin socket' entity='admin socket' cmd='mon_status' args=[]: dispatch
debug 2022-11-08T20:37:04.388+0000 7fa012687700  0 log_channel(audit) log [DBG] : from='admin socket' entity='admin socket' cmd=mon_status args=[]: finished
audit 2022-11-08T20:37:04.389506+0000 mon.h (mon.2) 68 : audit [DBG] from='admin socket' entity='admin socket' cmd='mon_status' args=[]: dispatch
audit 2022-11-08T20:37:04.389636+0000 mon.h (mon.2) 69 : audit [DBG] from='admin socket' entity='admin socket' cmd=mon_status args=[]: finished
cluster 2022-11-08T20:37:06.197129+0000 mgr.a (mgr.84261) 199 : cluster [DBG] pgmap v210: 1 pgs: 1 active+clean; 449 KiB data, 59 MiB used, 120 GiB / 120 GiB avail
cluster 2022-11-08T20:37:08.197717+0000 mgr.a (mgr.84261) 200 : cluster [DBG] pgmap v211: 1 pgs: 1 active+clean; 449 KiB data, 59 MiB used, 120 GiB / 120 GiB avail
audit 2022-11-08T20:37:09.925746+0000 mon.g (mon.1) 198 : audit [DBG] from='admin socket' entity='admin socket' cmd='mon_status' args=[]: dispatch
audit 2022-11-08T20:37:09.925934+0000 mon.g (mon.1) 199 : audit [DBG] from='admin socket' entity='admin socket' cmd=mon_status args=[]: finished
```

Would it not be simple enough to grep for the needed prefix if only certain lines are required?

**Comment by vumrao** [comment]
@subhamkrai @travisn this was requested mainly to have the same streamlined troubleshooting process b/w standalone Cephadm, ceph-ansible deployed Ceph and rook deployed Ceph. If there has been already discussed in the past and it makes the issue complicated on log rotation we can live with grep commands :)
