### ISSUE TITLE
Rook Flexvolume does not work properly on non-homogenous K8S cluster

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1128]
The rook-agents needs to hostpath mount the flexvolume plugin dir in order to be able to install the flexvolume driver. The operator self-discovers the flexvolume plugin dir from its own kubelet's configuration (kubelet that is running the operator) and uses this directory to hostpath mount as it  deploys the rook-agents via daemonset. 

The issue happens if another node's kubelet is configured to have a different flexvolume plugin dir, this directory would not be hostpath mounted and therefore the driver will not be installed property.

**Comment by kokhang** [comment]
Two solutions that i can think of:

1- Improve flexvolume in K8S in a way where the individual pods are told of the flexvolume plugin dir and have it automatically hostpath mounted. This is kind of similar to the downward API but aside from getting the flexvolume directory in an enviroment variable, the pod also hostpath mounts it so that the flexvolume driver can be installed.

2- Instead of using a Daemonset to deploy the rook-agents, we could use Deployment resource with affinity so that they are deployed in every node. In this case we will need to ensure that the agents is deployed on every node. We also need to watch for nodes so that agents are deployed as new nodes are added. This will solve this problem since we can query each individual kubelet's configuration and tailored each deployment appropriately.

**Comment by jbw976** [comment]
Here's a snippet from a design proposal draft that briefly addressed heterogeneous environments:

> To aid in deployment of Flexvolume drivers, the plugin directories should be exposed to pods via the downward API.  For example, a [recommended approach for deploying drivers](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/flexvolume-deployment.md#recommended-driver-deployment-method) is to use a DaemonSet.  There would be no manual intervention necessary if the pods spawned by this DaemonSet had access to the plugin directory via the downward API.  Note that in the case of containerized Kubelets, it is important that the true host path of the bind mounted plugin dir is what gets conveyed to the pods so that they can install their drivers on the host’s filesystem in the correct location.
