### ISSUE TITLE
CI fails intermittently on TestHelmUpgradeSuite test

### ISSUE THREAD

**Issue by peng225** [rook/rook#11291]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

TestHelmUpgradeSuite test failed repeatedly as follows.
https://github.com/rook/rook/actions/runs/3429367420/jobs/5722535828

```
--- FAIL: TestCephUpgradeSuite (1175.69s)
    --- FAIL: TestCephUpgradeSuite/TestUpgradeHelm (1171.27s)
FAIL
FAIL	github.com/rook/rook/tests/integration	1175.760s
FAIL
Error: Process completed with exit code 1.
```

This test is kicked by the following backport PR.
https://github.com/rook/rook/pull/11287

But it also occurs on other backport PR's CI.
https://github.com/rook/rook/actions/runs/3423194091/jobs/5701510139

**Expected behavior:**

Pass the test on CI.

**Comment by parth-gr** [comment]
https://github.com/rook/rook/actions/runs/3436742359/jobs/5730628343 It ran fine on my latest push,
Looks like a intermittent, you can re-run the test

**Comment by satoru-takeuchi** [comment]
This test failed in #11287 seven times. However, it might be resolved by some reasons. I'll try again.

**Comment by travisn** [comment]
Sometimes I have seen that to get a clean test run we need to force push to the branch instead of re-running the same job. This issue does seem intermittent though, not related to #11287.

**Comment by travisn** [comment]
I went ahead and merged #11287. The tests are passing in master since #11268 was merged. Let's keep an eye on this test to see if it becomes consistent besides that PR though.

**Comment by travisn** [comment]
It looks like the helm upgrade test on K8s 1.19 is failing consistently only in the release-1.10 branch since #11202 was backported, but in the master branch it is passing.

**Comment by travisn** [comment]
The error seems related to `status.endpoints` on the object store:
```
Error: UPGRADE FAILED: cannot patch "ceph-objectstore-test" with kind CephObjectStore: CephObjectStore.ceph.rook.io "ceph-objectstore-test" is invalid: status.endpoints: Required value , err -> exit status 1
    ceph_upgrade_test.go:445: 
        	Error Trace:	/home/runner/work/rook/rook/tests/integration/ceph_upgrade_test.go:445
        	            				/home/runner/work/rook/rook/tests/integration/ceph_upgrade_test.go:134
        	            				/home/runner/work/rook/rook/tests/integration/ceph_upgrade_test.go:104
```

**Comment by satoru-takeuchi** [comment]
Close this for now since it can be bypassed by [this way](https://github.com/rook/rook/issues/11291#issuecomment-1310361026)
