### ISSUE TITLE
Support erasure coding for block and shared filesystem

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1129]
In Luminous, erasure coding is supported for RBD and CephFS now (in addition to the RGW support that has been there since firefly):
http://ceph.com/community/new-luminous-erasure-coding-rbd-cephfs/

We'd need to make a couple updates to take advantage of this (full steps are in the article).

**Comment by travisn** [comment]
i believe our file system crd is already following these steps to set the EC pools up as expected. Seems like we should set the overwrites for all EC pools

**Comment by jbw976** [comment]
This issue looks like it covers #1360 and #1500

**Comment by tonya11en** [comment]
Filesystem is definitely already doing the right thing here:
https://github.com/rook/rook/blob/f192defee101b918a5cb3987cca954a6419a29be/pkg/daemon/ceph/mds/filesystem.go#L86

One problem I foresee with enabling EC overwrites for all EC pools is that it's unnecessary for object stores, so I'll just switch off overwrites for object storage to avoid any unnecessary performance degradation.

**Comment by tonya11en** [comment]
We're having difficulty getting this issue assigned to me, so I'll just link the PR: https://github.com/rook/rook/pull/1651
