### ISSUE TITLE
Setting configOverride fails in rook-ceph-cluster Helm chart

### ISSUE THREAD

**Issue by rmvangun** [rook/rook#11302]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Setting `configOverride` value in rook-ceph-cluster chart results in the following error as the configmap has already been created:

```
Helm upgrade failed: rendered manifests contain a resource that already exists. Unable to continue with update: ConfigMap "rook-config-override" in namespace "rook-ceph" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rook-ceph-cluster"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "rook-ceph"
```

**Expected behavior:**
Setting `configOverride` value in rook-ceph-cluster chart successfully creates a `rook-config-override` configmap

**Environment**:
* Helm version: rook-ceph-cluster v1.10.5

**Comment by parth-gr** [comment]
Can share more details on how the config map was before and what you have updated,

Seems like the upgrade might fail because the formatting was not in the correct manner and would be missing some mandatory values.

**Comment by travisn** [comment]
Helm adds a couple annotations to all the resources it owns. Look at the annotations the other resources have for helm, then add those to the configmap before installing the helm chart. And we should add these annotations to the rook docs too.

**Comment by rmvangun** [comment]
Okay got it. It seems that if you were to create the configmap ahead of time, you wouldn't use the `configOverride` property either as you would be managing this file out-of-band with the helm chart. So not sure when the `configOverride` property would be in use?

**Comment by travisn** [comment]
Oh I see the issue now with this sequence of events
1. Create the operator helm chart. 
2. The operator starts and creates the default (empty) config overrides configmap
3. Create the cluster helm chart

Step 3 fails if you set the `configOverride` property. If you were to create the cluster helm chart at the same time as the operator chart (and before the operator starts the first time), the cluster chart would be able to create the configmap successfully. 

So when the operator creates the default configmap, it should create those helm annotations in case the cluster chart is installed with it. 

For now the workaround is to create/update the configmap separately from the helm chart.

**Comment by travisn** [comment]
The helm annotations should be added by the operator [here](https://github.com/rook/rook/blob/fcf634e3b7808e4338e7fd261c047aae4793e99b/pkg/operator/ceph/cluster/utils.go#L39) when the default configmap is created.

**Comment by travisn** [comment]
@rmvangun Do you have more details on your repro steps? After taking a closer look, I'm not seeing how this issue could realistically be hit by my steps in [this comment](https://github.com/rook/rook/issues/11302#issuecomment-1329991009). The operator will create the empty configmap if it doesn't exist, but the operator doesn't reconcile the cluster and create the configmap until the CephCluster CR is created. Since you would be creating the CephCluster CR with the cluster helm chart, the configmap would also be created by the helm chart before the operator has a chance to create the configmap.

**Comment by holmesb** [comment]
Me too. "_create the cluster helm chart at the same time as the operator chart_" - yes works at initial install, but not after. rook-config-override cm is created by value `configOverride`, but not if the operator has created it first. Cannot assign `configOverride` value after operator has created the ceph cluster. 

Repro:
1. Create a ceph cluster using helm without setting `configOverride`. Wait for operator to provision all resources.
2. Assign a `configOverride` value in rook-ceph-cluster and try to deploy the helm release.

One solution is to force the rook-ceph-cluster chart to **always** create the cm by setting a dummy heredoc in default values:
```
configOverride: |
  [global]
```

Unf, can't assign to blank. Helm doesn't create cm if instead use:
```
configOverride: |

```


As background, here's the cm in state where it can be managed in helm:
```
~/$ kubectl describe cm rook-config-override
Name:         rook-config-override
Namespace: rook-ceph
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: rook-ceph-cluster
              meta.helm.sh/release-namespace: rook-ceph
```

And here it cannot be managed in helm:
```
~$ kubectl describe cm rook-config-override
Name:         rook-config-override
Namespace: rook-ceph
Labels:       <none>
Annotations:  <none>
```
