### ISSUE TITLE
Is it a bug that failureDomain doesn't change?

### ISSUE THREAD

**Issue by jclab-joseph** [rook/rook#11313]
**Is this a bug report or feature request?**
Bug Report

**Deviation from expected behavior:**

Replaced failureDomain in CephBlockPool or CephObjectStore .
It is detected. but it does not change.

is this a bug? Is this intentional?
If that's intended, I think the Operator should at least throw an error.

**Expected behavior:**

crush_rule should change. (Or throw an error)

**How to reproduce it (minimal and precise):**

- Create CephBlockPool.
- Wait for the Pool ready.
- Change a failureDomain.

**Logs to submit**:

```
2022-11-14 07:19:08.793295 I | ceph-spec: CR has changed for "blockpool". diff=  v1.PoolSpec{
- 	FailureDomain: "host",
+ 	FailureDomain: "osd",
  	CrushRoot:     "",
  	DeviceClass:   "",
  	... // 8 identical fields
  }
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04
* Kernel (e.g. `uname -a`): 5.4.0
* Cloud provider or hardware configuration: On-premise
* Rook version (use `rook version` inside of a Rook Pod): v1.5.8
* Storage backend version (e.g. for ceph do `ceph -v`):  `ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)`
* Kubernetes version (use `kubectl version`): v1.21.4

**Comment by parth-gr** [comment]
According to the rook Ceph-block-pool-crd [docs](https://github.com/rook/rook/blame/master/Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md#L194)  I can see the failureDomain can be changed.

Can you update the logs of the operator and what is the failuredomain and to what you are trying to change it.

But I see this feature is introduced from 1.8 so you need to update the rook version for it

**Comment by jclab-joseph** [comment]
Thank you.
Rook I used is out of date, so I close the issue.
