### ISSUE TITLE
For object storage, rook uses different provisioner names per CephCluster

### ISSUE THREAD

**Issue by haslersn** [rook/rook#11326]
Currently rook spawns a separate object bucket provisioner goroutine per CephCluster, each watching for a different "provisioner name". Example:

```
2022-11-17 17:30:53.529361 I | op-bucket-prov: ceph bucket provisioner launched watching for provisioner "rook-ceph.ceph.rook.io/bucket"
2022-11-17 17:30:56.729940 I | op-bucket-prov: ceph bucket provisioner launched watching for provisioner "rook-ceph-external.ceph.rook.io/bucket"
```

However, the [documentation here](https://rook.io/docs/rook/v1.10/Storage-Configuration/Object-Storage-RGW/object-storage/?h=objectbucketclaim#create-a-bucket) states the following:

> Change "rook-ceph" provisioner prefix to match the operator namespace if needed

With rook's current behavior, however, the prefix needs to match the cluster namespace. This is contrary to what we have with FS and block, I think. Also, it's technically not required, because the cluster namespace can be inferred from the `objectStoreNamespace`  field of the BucketOptions (i.e. `options.Parameters["objectStoreNamespace"]`), because the CephObjectStore needs to be in the same namespace as the CephCluster.

For these reasons I think the behavior should be changed. There are two possible solutions to implement this in the software:

- Either one keeps multiple provisioner goroutines, but all of them watch for the same provisioner name (if this is supported by lib-bucket-provisioner). Then the provisioner must discard incoming requests where the `objectStoreNamespace` doesn't match.
- Or one only runs a single provisioner goroutine that is responsible for all CephClusters. In that case, the Provisioner data structure needs to be changed in order to store information about multiple CephClusters instead of just a single one.

**Is this a bug report or feature request?**
* Bug Report

**Environment**:
* Rook version: v1.10.5

**Comment by BlaineEXE** [comment]
This behavior is what was originally intended. We could change it, and I think your reasoning makes sense. However, it would disrupt any existing deployments and mean users would need to update their storage class definitions.

The library Rook uses for OBCs is going to be replaced by COSI in the coming year or so, and I think it would be a better long-term experience for users to not force any OBC Charles until we are ready to move to COSI.
