### ISSUE TITLE
ceph-fuse no longer working with rook 1.10.5 and ceph 17.2.5

### ISSUE THREAD

**Issue by raz3k** [rook/rook#11329]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** ceph-fuse does not mount it prints out an error message

**Expected behavior:** ceph-fuse mounts the filesystem like in rook 1.9.9

**How to reproduce it (minimal and precise):**
On the toolbox sts, also mount /dev/fuse as a volume mount from the host
`mkdir /tmp/aa`
`ceph-fuse /tmp/aa`

```
ceph-fuse[110]: starting ceph client
2022-11-18T09:36:57.255+0000 7f15890ed3c0 -1 init, newargv = 0x558b01319420 newargc=15
ceph-fuse[110]: fuse failed to start
2022-11-18T09:36:57.281+0000 7f15890ed3c0 -1 fuse_ll: already_fuse_mounted: statx(/tmp/aa) failed with error (22) Invalid argument
```

This used to work on rook 1.9.9, the aleady_fuse_mounted message is misleading as the folder is empty.

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7
* Kernel (e.g. `uname -a`): 3.10.0-1127.el7.x86_64
* Cloud provider or hardware configuration: 3 master+worker each has 8 cores and 16 Gb of RAM
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.10.5 go: go1.18.7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`): 1.24.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):  health: HEALTH_WARN noout flag(s) set

**Comment by raz3k** [comment]
i tried using several directories but same issue occurs. problem is with  `fuse failed to start`

**Comment by travisn** [comment]
Ceph is HEALTH_OK, right? Not sure what would have changed since the version when you had it working, it seems environmental.
