### ISSUE TITLE
specify filesystem name in ReplicationController

### ISSUE THREAD

**Issue by beatlejuse** [rook/rook#1133]
i'm creating Filesystem with name "myfs"
https://github.com/rook/rook/blob/master/Documentation/k8s-filesystem.md#create-the-file-system
and use it by pod in ReplicationController
https://github.com/rook/rook/blob/master/Documentation/k8s-filesystem.md#consume-the-file-system
please help me to understand, how can i specify filesystem name (in ReplicationController config), if i create many filesystems for many pods?

**Comment by travisn** [comment]
The CephFS volume plugin does not support multiple file systems. We are adding a rook filesystem dynamic provisioner, which will be merged any day now, that will support multiple file systems by name. 
https://github.com/rook/rook/pull/1115

For the new documentation in the PR, see:
https://github.com/kokhang/rook/blob/6b9b914142befee26e9534517319819966006de2/Documentation/k8s-filesystem.md

**Comment by beatlejuse** [comment]
thank you! I'll be waiting!
