### ISSUE TITLE
object: need to support to set bucket quota

### ISSUE THREAD

**Issue by zhucan** [rook/rook#11335]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
limit the objects  in the bucket

**What is use case behind this feature:**

**Environment**:

**Comment by zhucan** [comment]
https://github.com/ceph/go-ceph/blob/b956ad18da9ca157cd25f074db8e1a9f100514aa/rgw/admin/bucket_quota.go#L13

**Comment by travisn** [comment]
The `maxObjects` and `maxSize` can be set in the OBC. See [this topic](https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/?h=bucket#obc-custom-resource).

**Comment by zhucan** [comment]
@travisn It's invalid.

**Comment by zhucan** [comment]
https://github.com/rook/rook/blob/7278fb9e56fcdb5c02836e6ff1da0947e71ade04/pkg/operator/ceph/object/bucket/provisioner.go#L573 Only support set user quota, not support set bucket quota

**Comment by travisn** [comment]
With OBCs there is a user created per bucket, so setting the user and bucket quota seems the same.
@BlaineEXE thoughts?

**Comment by zhucan** [comment]
@travisn Maybe because of the bucket and user is one to one, no need to set quota to user and bucket at same time, but the in the fact, the user with the bucket is one to many, so we need to create bucket with special user

**Comment by BlaineEXE** [comment]
The library Rook uses to provide OBCs is deprecated and only receives bug fixes. OBCs are intended to be a self-service way of claiming a bucket for object storage where each bucket has a specific set of credentials.

If you need to create a one-to-many relationship between users and buckets, you will have to use manual tooling. Using OBCs outside of their intended purpose can't be supported.

**Comment by microyahoo** [comment]
Hi @travisn @thotz @BlaineEXE I plan to submit a PR to implement this feature, roughly divided into two steps
1. The current [ObjectBucketClaimSpec.AdditionalConfig](https://github.com/kube-object-storage/lib-bucket-provisioner/blob/d1a8c34382f127670e363ae925ae6087e8b2c7bf/pkg/apis/objectbucket.io/v1alpha1/objectbucketclaim_types.go#L51) stores the bucket's `max-objects` and `max-size`, and we can also record the `user-id` in it. In this way, this step does not need to modify the `lib-bucket-provisioner` library, and at the same time realizes the feature of specifying the user when creating a bucket.
2. Modify the `lib-bucket-provisioner` library, add the `UserID` field in [ObjectBucketClaimSpec](https://github.com/kube-object-storage/lib-bucket-provisioner/blob/d1a8c34382f127670e363ae925ae6087e8b2c7bf/pkg/apis/objectbucket.io/v1alpha1/objectbucketclaim_types.go#L31), and replace the temporary storage in `AdditionalConfig` in the above step.
Any thoughts and comments are welcome, thanks.

**Comment by BlaineEXE** [comment]
It seems like only step 1 would be needed to me. Thanks for offering to take this on.
