### ISSUE TITLE
Slow Recovery ceph cluster in kubernetes.

### ISSUE THREAD

**Issue by rfarajro** [rook/rook#11349]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Slow Recovery

**Expected behavior:**
Ceph cluster does not change osd parameters to improve recovery speed. Example: osd_max_backfills, osd_recovery_max_active, etc.

command with no expected result: ceph tell 'osd.*' injectargs --osd_max_backfills=2 --recovery_max_active=2
command with default config: 
ceph config show osd.0 | grep osd_recovery_max_active
osd_recovery_max_active                          1000
ceph config show osd.0 | grep osd_recovery_max_active
osd_recovery_max_active                          1000

**How to reproduce it (minimal and precise):**
Rebalance ceph cluster when adding new or moving OSD.

**Cluster Status to submit**:
HEALTH_WARM

**Environment**:
* OS (e.g. from /etc/os-release): RedHat 8.5
* Kernel (e.g. `uname -a`): 4.18.0-348.el8.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.10.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.3
* Kubernetes version (use `kubectl version`): v1.23.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Vanilla
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
Instead of `ceph tell`, try a `ceph config set` command such as: `ceph config set global osd_max_backfills 2`

**Comment by rfarajro** [comment]
> Instead of `ceph tell`, try a `ceph config set` command such as: `ceph config set global osd_max_backfills 2`

 Hi, thanks for answering.

 Command does not work, same situation:
bash-4.4$ ceph config set global osd_max_backfills 2

bash-4.4$ ceph config show osd.0 | grep osd_max_backfills
osd_max_backfills                                1000

Greetings!!

**Comment by travisn** [comment]
Interesting, I though `ceph config show` and `ceph config get` would be the same value, but they are not:
```
bash-4.4$ ceph config get osd.0 osd_max_backfills
1
bash-4.4$ ceph config set global osd_max_backfills 5
bash-4.4$ ceph config get osd.0 osd_max_backfills
5
bash-4.4$ ceph config show osd.0 osd_max_backfills
1000
```

**Comment by satoru-takeuchi** [comment]
These values sometimes differ from each other.

https://docs.ceph.com/en/quincy/man/8/ceph/
> Please note, unlike get, which only shows the options managed by monitor, show displays all the configurations being actively used.

**Comment by rfarajro** [comment]
Hi, thanks for your answering.

 The question is, i have 2 k8s environments each one with their own ceph cluster , in one of them works but in the other does not work.

Does not work:
bash-4.4$ ceph config get osd.0 osd_max_backfills
2
bash-4.4$ ceph config set global osd_max_backfills 1
bash-4.4$ ceph config get osd.0 osd_max_backfills
2
bash-4.4$

Work:
bash-4.4$ ceph config get osd.0 osd_max_backfills
1
bash-4.4$ ceph config set global osd_max_backfills 2
bash-4.4$ ceph config get osd.0 osd_max_backfills
2
bash-4.4$ ceph config set global osd_max_backfills 1 
bash-4.4$ ceph config get osd.0 osd_max_backfills
1

 Regrads.

**Comment by travisn** [comment]
They are the same ceph version?

**Comment by rfarajro** [comment]
> They are the same ceph version?

Yes.

Does not work:
kubectl exec -ti -n rook-ceph rook-ceph-tools-7c8ddb978b-x9kjf -- ceph --version
ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)

Works:
kubectl exec -ti -n rook-ceph rook-ceph-tools-7c8ddb978b-4bsfx -- ceph --version
ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)

Regards.

**Comment by rfarajro** [comment]
Hi,
 
 I found the solution. I set the parameters at global and osd level.

To show all configuration:
#ceph config dump

To set parameters:
ceph config set global <parameter> <value>
ceph config set osd <parameter> <value>

To remove parameter once recover finish:
ceph config rm global <parameter> <value>
ceph config rm osd <parameter> <value>

Regards.
