### ISSUE TITLE
PrometheusRules alerting on non-rookCeph related nodes

### ISSUE THREAD

**Issue by dml872** [rook/rook#11351]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The CephNodeNetworkPacketDrops is alerting on systems/nodes that are unrelated to RookCeph. The expression uses node-exporter metrics but is not ceph specific (i.e. namespace or similar)

**Expected behavior:**
Alert should only fire for Ceph nodes.

**How to reproduce it (minimal and precise):**
Have node-exporter on other nodes reporting to prometheus.

**Environment**:
* OS (e.g. from /etc/os-release): N/A
* Kernel (e.g. `uname -a`): N/A
* Cloud provider or hardware configuration: N/A
* Rook version (use `rook version` inside of a Rook Pod): v1.10.0
* Storage backend version (e.g. for ceph do `ceph -v`): 17.2.3
* Kubernetes version (use `kubectl version`): 1.24.7_rke2r1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_WARN

**Comment by avanthakkar** [comment]
Looking at the alert https://github.com/rook/rook/blob/master/deploy/examples/monitoring/localrules.yaml#L663, seems like it's only `device` label. Maybe filtering alert based on `instance` label too(which prometheus adds by default to all metrics https://prometheus.io/docs/concepts/jobs_instances/) can help here. 
For e.g. if all ceph nodes(hostnames) are having prefix `ceph-node-` then filtering based on this instance label could help solve the issue. 
But the only challenge is to predict prefix, as it may differ as per user's choice.
