### ISSUE TITLE
Rook OSD daemon changes all the nodes hostnames

### ISSUE THREAD

**Issue by dedsm** [rook/rook#1135]
In my cluster, it seems the OSD daemon is changing the node hostname, causing kubelet restarts to fail when trying to register the node.

hostnames are changed according to this code https://github.com/rook/rook/blob/307adad72982257bbb11bbd48342fc4d6760d3f7/pkg/ceph/osd/daemon.go#L98, don't know if it's actually there but it rings all the bells.

my nodes FQDN go from host.domain.com to host-domain-com after starting the rook pods.

**Comment by travisn** [comment]
Hmm, changing the node name was only intended to affect the osd pod, for the purpose of naming the node in the crush map. If it's affecting the naming on the host it is very unexpected and we will need to find another way to accomplish this.

**Comment by dgonzalezruiz** [comment]
I support this. This will potentially mess up your cluster. In my case, it did mess up the monitoring, since the hostnames where changed and I used hostname filtering. (issue fixed now).\
It only affected me when setting `hostNetwork` to true.

**Comment by travisn** [comment]
ok, looks like we can set a `crush location` in the ceph config file on the osd without messing with the hostname, which will not have any unintended side effects.
http://docs.ceph.com/docs/master/rados/operations/crush-map/#crush-location

**Comment by jbw976** [comment]
are we not already specifying the crush location when adding the OSD to the crush map @travisn? https://github.com/rook/rook/blob/master/pkg/ceph/osd/device.go#L622

i recall in the past that even when we set `host=` that Ceph would use a name with dashes instead.  you may run into that, just a heads up.
