### ISSUE TITLE
Rgw pools pg_num is 32, historically it has been set to 8

### ISSUE THREAD

**Issue by emosbaugh** [rook/rook#11366]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Rgw pools pg_num is 32, historically it has been set to 8.

```
$ kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph osd pool get rook-ceph-store.rgw.buckets.index  pg_num
pg_num: 32
```

root cause seems to be

```
2022-11-29 19:27:26.559787 W | ceph-object-controller: failed to adjust the PG count for rgw metadata pools. using the general default. failed to get config setting "rgw_rados_pool_pg_num_min" for user "mon.": exit status 2
```

```
$ kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph config get mon.
WHO     MASK  LEVEL     OPTION                                 VALUE       RO
mon           advanced  auth_allow_insecure_global_id_reclaim  false
global        basic     log_to_file                            true
global        advanced  mon_allow_pool_delete                  true
global        advanced  mon_allow_pool_size_one                true
global        advanced  mon_cluster_log_file
global        advanced  mon_pg_warn_min_per_osd                0
global        basic     ms_client_mode                         crc secure  *
global        basic     ms_cluster_mode                        crc secure  *
global        advanced  ms_osd_compress_mode                   none
global        basic     ms_service_mode                        crc secure  *
ethan@ethanm-rook-12:~$ kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph config get mon. rgw_rados_pool_pg_num_min
Error ENOENT: unrecognized key 'rgw_rados_pool_pg_num_min'
command terminated with exit code 2
```

has the option been removed in ceph?

https://tracker.ceph.com/issues/54277
https://ceph.io/en/news/blog/2022/v17-2-1-quincy-released/

rook version v1.10.6
ceph version 17.2.5

**Expected behavior:**

Rgw pools should have pg_num set to 8

**How to reproduce it (minimal and precise):**

helm install 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
Thanks for reporting, we need to get #11024 merged.

**Comment by emosbaugh** [comment]
Apologies. I'm having trouble understanding the proposed change. What will the expected pg_num be for rgw pools? Will it be 8 as it was for pacific?

```
$ kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph config get mon. pg_num_min
Error ENOENT: unrecognized key 'pg_num_min'
command terminated with exit code 2
```

**Comment by travisn** [comment]
The PR needs an update, hopefully [this comment](https://github.com/rook/rook/pull/11024/files#r1035340974) clarifies.

**Comment by emosbaugh** [comment]
Thank you. I will keep my eye on that conversation. For the time being can you recommend a workaround? Optionally I can use the latest pacific release rather than quincy.

Ultimately my issue is that with a similar cluster topology as I've had in the past with 3 nodes, 1 osd per node, I am receiving the following error:

```
2022-11-29 19:27:03.955317 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/rook-ceph-store". failed to create object store deployments: failed to create object pools: failed to create metadata pools: failed to create pool "rook-ceph-store.rgw.buckets.index": failed to set size property to replicated pool "rook-ceph-store.rgw.buckets.index" to 3: failed to set pool property "size" on pool "rook-ceph-store.rgw.buckets.index": exit status 34
```

```
$ kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph osd pool set rook-ceph-store.rgw.buckets.index size 3
Error ERANGE: pool id 8 pg_num 32 size 3 would mean 755 total pgs, which exceeds max 750 (mon_max_pg_per_osd 250 * num_in_osds 3)
command terminated with exit code 34
```

**Comment by travisn** [comment]
For now, try setting the pg_num_min to 8 on each of the rgw pools (except the data pool). Then the autoscaler will reduce the PGs to 8 after a few minutes.
```
ceph osd pool set <poolName> pg_num_min 8
```

**Comment by subhamkrai** [comment]
#11024 will fix

**Comment by emosbaugh** [comment]
Thanks!
