### ISSUE TITLE
Improve messages to user for flexvolume issues

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1136]
@DanKerns had some good ideas for how to improve the current negative experience with deploying and consuming storage via the flexvolume.

When the rook-agent fails to install the driver (e.g. because its a read-only filesystem), we should log a USEFUL message that says how to work around it and link to our useful docs.

Even on a successful driver deploy, log a reminder to restart the kubelet (if running on pre 1.8) and link to our useful docs.

Having a FAQ entry point to link to may make this smoother as opposed to linking deep into installation instructions.

**Comment by galexrt** [comment]
Can we use the termination log for that? See https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/#setting-the-termination-log-file.

Running the example from the Kubernetes documentation the output of a `kubectl describe` looks like this after exit: https://gist.github.com/galexrt/2e4f9324c6df630f139073659fa1e031

**Comment by jbw976** [comment]
Good question @galexrt.  After some debugging yesterday, I actually found that when the flexvolume plugin dir is on a read-only filesystem, the error message below is actually coming from the container runtime when it is attempting to bindmount the plugin dir, getting ready for the agent pod to consume it.  The agent pod actually never gets to launch at all:
```
Error: failed to start container "rook-agent": Error response from daemon: {"message":"mkdir /usr/libexec/kubernetes: read-only file system"}
```
`daemon` in that message means the Docker daemon.

@kokhang suggested that the operator could do a test to see if the plugin dir is writeable before it creates the agent DaemonSet.  After thinking about that, I'm not sure that would work for a couple reasons:
1. the operator would have already had to bind mount this dir from the host before it was started, thus causing the same failure for the operator to even launch
1. this would only be checking locally on the host that the operator is on and for heteregenous environments, where the config could be different on the node the agent is running on, this doesn't give us a confident response.

I'm wondering how best to approach this, perhaps the operator could wait for the agent pods to launch and if they crash then check the error for the agent pods via the k8s API and see if it's related to a read-only file system.

Also, @kokhang and I disagreed about the behavior in the case that we do figure out a reliable means of telling if the agents were not able to mount or write to the plugin dir.  @kokhang thinks the operator should fail completely so that the user cannot proceed with creating Rook cluster instances.  I'm not sure this is fair since Rook storage can be used outside of the volume plugin (e.g. RGW object storage, `rookctl` usage), but it would be a very noticeable means of getting the user's attention that something went wrong in the rook-system namespace before they proceed on with creating clusters thinking everything is OK.  Thoughts?

**Comment by kokhang** [comment]
@jbw976 i think you can get the permissions using https://golang.org/pkg/os/#File.Stat. That will tell you whether the directory is RW or RO. But you are right about the operator having to bind mouth this first. 

Now that im thinking about it, perhaps having the rook-agents crashlooping if the plugin-dir is RO may be ok. We could document to users to ensure rook-agents are `running` just like we documented when creating `cluster` CRD.

**Comment by travisn** [comment]
agreed, makes sense to crashloop to follow the k8s pattern of retrying, and allowing rook to continue for all other scenarios. Blocking the scenarios unnecessarily isn't a good thing.

**Comment by jbw976** [comment]
The intent is to instead of getting a crashloop message for the agent pod which is not user friendly,
 we wanted to show a crashloop message that is much more friendly (i.e. it tells the user exactly what to do and links to our Rook docs).  Since no Rook code gets to run before the crashloop happens, that isn't directly possible.

Alternatives such as sending out an init container to all nodes in the cluster to check if the plugin dir is accessible/writeable feel like they will add more complexity and new failure possibilities than is worth it.  I'm thinking that beefing up the docs in a way that allows the user to easily find their FAQ based on their symptoms and that points to exactly what to do for each environment will be the best approach.

Note that the 2nd portion of this issue is still very valuable, I will continue working on adding friendly messaging after a "successful" driver installation that reminds the user to restart the kubelet if on 1.7- and also points to our docs.
