### ISSUE TITLE
docs: Adding a glossary

### ISSUE THREAD

**Issue by zalsader** [rook/rook#11367]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add a glossary page to the documentation that conatins definitions for common abbreviations or concepts. Examples: [Kubernetes](https://kubernetes.io/docs/reference/glossary/?fundamental=true), [Ceph](https://docs.ceph.com/en/latest/glossary/), [OpenShift](https://docs.openshift.com/container-platform/4.11/architecture/index.html).

**What is use case behind this feature:**
Having a glossary would make understanding basic concepts in the docs easier for new and existing readers.

**Comment by travisn** [comment]
Sounds great to have a glossary added to the Rook docs. On the glossary page it would be good to link those pages mentioned above, and then add some specific Rook terms. 

Newcomers, please comment in this issue on the terms that would be helpful in the glossary that are not already in the other three linked glossaries.

**Comment by zalsader** [comment]
Some concepts might be woth repeating here if they are being used often.

- Ceph-related: OSD, MON, MDS, RBD.
- K8s-related: Affinity, Tolerations, CSI, PVC, sidecar, CRD.
- Rook: Object Bucket Claim (OBC), Object Bucket (OB)... maybe an entry with the definition of each CRD?

**Comment by galexrt** [comment]
* Ceph-related: MGR, "Maps" (mon map, osd map, pg map; might be too much for the Rook docs but at least linking to the Ceph docs should be good)

I think each word should have a short description to give users a good start to understanding and a link to some docs related to that word.

**Comment by ideepika** [comment]
some more I can think of: toolbox pod, krew, ceph config(with where it is present), Ceph CSI driver, storageclass, Finalizer
