### ISSUE TITLE
Allow to control .mgr pool

### ISSUE THREAD

**Issue by blackliner** [rook/rook#11368]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
I want to be able to control the configuration of the automatically created `.mgr` pool. Specifically, I am interested in changing the failure domain from `host` to `osd` or `rack`.

**Current Workaround:**
Manually edit the crushmap -> https://access.redhat.com/solutions/6518681

```
ceph osd getcrushmap -o /tmp/cm.bin
crushtool -d /tmp/cm.bin -o /tmp/cm.ascii
# vi /tmp/cm.ascii
...
# rules
rule replicated_rule {
        id 0
        type replicated
        step take default
        step chooseleaf firstn 0 type host # << change this to osd or rack
        step emit
}
...
crushtool -c /tmp/cm.ascii -o /tmp/cm_updated.bin
ceph osd setcrushmap -i /tmp/cm_updated.bin
```

**Comment by zhucan** [comment]
@blackliner https://github.com/rook/rook/blob/master/deploy/examples/cluster-test.yaml delete the .mgr pool manually and then create  it with yaml(example of pool) with assigned crush root.

**Comment by blackliner** [comment]
Thanks, less manual, but still manual I'd say. What would happen if we'd create the .mgr as a k8s CephBlockPool object while the old one still exists? Will it be overwritten?

**Comment by travisn** [comment]
See [this example](https://github.com/rook/rook/blob/master/deploy/examples/pool-builtin-mgr.yaml) for configuring the `.mgr` pool. If you create this CR after the cluster is already running, most essential properties will be applied, such as replica count. But there are other pool properties such as crushRoot that can only be set at pool creation. So you shouldn't need to delete the pool before creating the CR.

**Comment by blackliner** [comment]
Ok, we are getting closer :-) One issue I have is that when bootstrapping (which I did a lot lately), this would then still involve manual steps

**Comment by travisn** [comment]
What's the manual step? I wouldn't consider creating the pool CR a manual step.

**Comment by blackliner** [comment]
you say this needs to be done AFTER the cluster is created. If I add this as part of the GitOps repo, deployed by ArgoCD, I do not have control over when this happens. So I need to manually do this after everything is setup

**Comment by blackliner** [comment]
So to rephrase, I can create the kubernetes resource CephBlockPool which defines `.mgr` at any time, no dependencies? I.e it can be deployed even before the rook operator runs?

**Comment by blackliner** [comment]
Bump

**Comment by travisn** [comment]
> So to rephrase, I can create the CephBlockPool CR which defines `.mgr` at any time, no dependencies? I.e it can be deployed even before the rook operator runs? Because I have no control over when this is done by ArgoCD.
> 
> I am asking because you sounded like the cluster needs to create the .mgr first, and then I can modify it with my CR. Not the other way round.

The CephBlockPool CR can be created at any time, before or after the rook operator or cluster CR. The only dependency is that the Rook CRDs must be created before you can create any of the Rook CRs.

**Comment by blackliner** [comment]
Thanks for your suggestion @kukacz , it is accepted by the cluster 👍

**Comment by blackliner** [comment]
Fyi, https://github.com/rook/rook/blob/release-1.11/deploy/examples/nfs.yaml#L106 says that the metadata pools need to be created first, to avoid issues. Do we know which settings can be overridden during runtime and which not?

**Comment by travisn** [comment]
The `replicated.size` can certainly be updated at runtime. IIRC the `failureDomain` cannot be updated after pool creation. Any other properties in particular you're wondering about? In any case, we should make this answer clear in the docs.

**Comment by uhthomas** [comment]
I'm seeing conflicting information here.

I'm trying to set the device class for the `.mgr` pool in relation to #11764. I can create the CephBlockPool, but rook doesn't seem to reassign the crush rule.

```
bash-4.4$ ceph osd pool get .mgr all
size: 3
min_size: 2
pg_num: 1
pgp_num: 1
crush_rule: replicated_rule
hashpspool: true
nodelete: false
nopgchange: false
nosizechange: false
write_fadvise_dontneed: false
noscrub: false
nodeep-scrub: false
use_gmt_hitset: 1
fast_read: 0
compression_mode: none
pg_autoscale_mode: on
pg_num_min: 1
eio: false
bulk: false
pg_num_max: 32
```

```
# rules
rule replicated_rule {
        id 0
        type replicated
        step take default
        step chooseleaf firstn 0 type host
        step emit
}
rule .mgr {
        id 14
        type replicated
        step take default class hdd
        step chooseleaf firstn 0 type host
        step emit
}
```

**Comment by uhthomas** [comment]
I see this behaviour is known, at least. Is there a solution in the meantime?

https://github.com/rook/kubectl-rook-ceph/issues/87

**Comment by uhthomas** [comment]
I manually changed the crush rule and that seems to have helped. 

```
bash-4.4$ ceph osd pool set .mgr crush_rule .mgr
set pool 2 crush_rule to .mgr
```

**Comment by uhthomas** [comment]
Though, it does not look like changing the device class for any pools will work. I had to manually update the crush map to specify the default device class. I don't get why, as ceph supports changing device classes for pools.

**Comment by uhthomas** [comment]
Looks like manually setting the device classes for all pools fixed the pg autoscaler as expected :)

![image](https://user-images.githubusercontent.com/9749173/230638538-810196e1-701c-439c-b4eb-ddacd3114e2c.png)

That said - Is there anything we can do to help with this? It seems fragile and weird for the pg autoscaler to completely stop working under these circumstances. It even took a while to find the problem as the ceph dashboard was otherwise "happy".

**Comment by travisn** [comment]
Is the issue that the device class had to be updated for all pools, not just the single pool where you updated the crush rule? Changing the device class is something we want to support in the krew plugin as you mentioned with https://github.com/rook/kubectl-rook-ceph/issues/87. Is there something else you're looking for?

**Comment by uhthomas** [comment]
I guess it's a few things:
- Is it possible to provide better visibility into potentially critical issues like this? There were 5x fewer PGs than there should have been in my case, without any loud errors or good explanation for as to why.
- Is it not possible to update the crush rules when the CRD is changed? It seems weird to have to manually modify the crush rules. For the case of `.mgr` the pool was pointing to the wrong crush rule, and the crush rules themselves for all other pools just weren't updated.
- Is it possible to avoid this sort of situation in the first place, maybe by setting a default device class? I'm not sure it is desirable to use multiple kinds of devices for a single rule?

**Comment by travisn** [comment]
> I guess it's a few things:
> 
> * Is it possible to provide better visibility into potentially critical issues like this? There were 5x fewer PGs than there should have been in my case, without any loud errors or good explanation for as to why.

Rook has left PG management up to the Ceph layer. Before the autoscaler things were more difficult, but there hasn't been a general need for controlling the PGs.  More specific control of the PGs will be better enabled by #11967. 

Any alerts we really should be raised by Ceph as health warnings. Perhaps you could open a ceph tracker bug to request this.

> * Is it not possible to update the crush rules when the CRD is changed? It seems weird to have to manually modify the crush rules. For the case of `.mgr` the pool was pointing to the wrong crush rule, and the crush rules themselves for all other pools just weren't updated.

Agreed, manually updating crush rules is not where we want to be, it is just the reality for a corner case. If there are specific scenarios like this to fix, then it just becomes a resource question for who is motivated to fix it.

> * Is it possible to avoid this sort of situation in the first place, maybe by setting a default device class? I'm not sure it is desirable to use multiple kinds of devices for a single rule?

A default device class is set for OSDs at the Ceph level, but I don't see that Rook has the needed context about what default device class to set on the pools. Rook doesn't even know what device classes are going to exist until the OSDs are created, and if there are multiple device classes, rook wouldn't know which one to pick. 

I do agree that multiple kinds of devices shouldn't be used for a single pool. The common case is that device classes are not needed since all OSDs are most commonly the same device class. So if multiple device classes are there, I see no recourse other than to require the admin to set these device classes in the pool CR.

**Comment by uhthomas** [comment]
Makes sense, thank you for your insight on all of these points. To summarise, it sounds like three things should happen:

1. Raise a bug on the ceph tracker.
2. Open a rook bug for updating crush rules.
3. Maybe update some documentation somewhere to mention this device class case. I was thinking something near onboarding?

**Comment by travisn** [comment]
As far as documentation, perhaps what we need is a topic like "Getting Started FAQ", that introduces the concepts such as device classes, topology, and so on. This doc could then link to the more detailed docs that already exist.

**Comment by subhamkrai** [comment]
> As far as documentation, perhaps what we need is a "Getting Started FAQ", that introduces the concepts such as device classes, topology, and so on. This doc could then link to the more detailed docs that already exist.

we already have something similar https://rook.github.io/docs/rook/latest/Getting-Started/glossary/
