### ISSUE TITLE
HELM: StorageClasses get created even when cephBlockPools is not existing

### ISSUE THREAD

**Issue by blackliner** [rook/rook#11365]
This is imho a bug in the HELM chart template. Even if there is no cephBlockPools to iterate through, the storage classes still get created.

https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml

**Comment by parth-gr** [comment]
I see this file is creating both block pool and SC so whats the problem

**Comment by blackliner** [comment]
I do not want to create anything, so I comment out the whole cephBlockPools. The block pool and the storage class are still created though

**Comment by blackliner** [comment]
Thanks, that did the trick!
