### ISSUE TITLE
FailedMount rbd image replicapool/csi-vol-xxx is still being used

### ISSUE THREAD

**Issue by nirav-chotai** [rook/rook#11372]
We are using Rook with Ceph on K8s through the operator. 

Recently there was pod restart noticed in the production for running ArangoDB with the storage given by rook-ceph

Since then, application is not coming up
```
  Warning  FailedMount  5m6s (x208 over 9h)  kubelet  MountVolume.MountDevice failed for volume "pvc-b38f1217-e007-433f-bc62-15b66e6671db" : rpc error: code = Internal desc = rbd image replicapool/csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c is still being used
```

As highlighted by many on, https://github.com/rook/rook/issues/4772
I have checked all the `rbdplugin` as well as `provisioner` pods, running command `rbd device list`
And couldn't find anywhere `csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c`

Still when I checked from the toolbox, I can see below

```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# rbd info replicapool/csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c
rbd image 'csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c':
        size 100 GiB in 25600 objects
        order 22 (4 MiB objects)
        snapshot_count: 0
        id: aa3e569bdb2d66
        block_name_prefix: rbd_data.aa3e569bdb2d66
        format: 2
        features: layering
        op_features: 
        flags: 
        create_timestamp: Wed Feb 17 04:09:13 2021
        access_timestamp: Wed Feb 17 04:09:13 2021
        modify_timestamp: Wed Feb 17 04:09:13 2021
[root@rook-ceph-tools-68958dbb7f-klmcn /]# 
```
As I cannot find `csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c` ahywhere, I cannot unmap/unmount etc.

Is there any way to fix this problem and bring the production application back to up and running, without losing any data?

**Comment by nirav-chotai** [comment]
Exactly followed https://github.com/rook/rook/pull/8322/files
But there is no `csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c` in any of the pods.

**Comment by Rakshith-R** [comment]
@nirav-chotai 

You can get client ip by running 
```
rbd status replicapool/csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c
```

It should look something like 
```
$ rbd status <image_name>
Watchers:
watcher=172.21.12.201:0/4225036114 client.17881 cookie=18446462598732840961
```

The ip should help you locate where the image was mapped. 
Was k8s node replacement done ? 

you can use the entire ip with port (e.g., `172.21.12.201:0/4225036114`) to blocklist it with cmd given here https://github.com/rook/rook/blob/master/Documentation/Troubleshooting/ceph-csi-common-issues.md#blocklisting-a-node 

This should allow the rbd image to be mapped on new node. 
Remember to remove the blocklist after the pod starts.

**Comment by nirav-chotai** [comment]
@Rakshith-R , thanks for your help on this one.

```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# rbd status replicapool/csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c
Watchers:
        watcher=192.168.152.128:0/765081214 client.35935078 cookie=18446462598732841662
```

And then when I tried blocklist, it seems didn't work
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph osd blocklist add 192.168.152.128:0/765081214
no valid command found; 10 closest matches:
osd perf
osd df [plain|tree] [class|name] [<filter>]
osd blocked-by
osd pool stats [<pool_name>]
osd pool scrub <who>...
osd pool deep-scrub <who>...
osd pool repair <who>...
osd pool force-recovery <who>...
osd pool force-backfill <who>...
osd pool cancel-force-recovery <who>...
Error EINVAL: invalid command
```

There is no node removal or replacement done. 

Am I using the correct command for blocklisting?

**Comment by nirav-chotai** [comment]
Moreover, after few mins, I can see below now
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# rbd status replicapool/csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c
Watchers:
        watcher=192.168.105.64:0/1807917246 client.39530356 cookie=140106061080480
        watcher=192.168.152.128:0/765081214 client.35935078 cookie=18446462598732841662
```

I checked for both IP addresses, but couldn't find any of them
```
 ~/ kubectl get po -o wide -A | grep -i 192.168.152.128                                                                                   
 ~/ kubectl get po -o wide -A | grep -i 192.168.105.64               
 ~/ 
```

**Comment by nirav-chotai** [comment]
@Rakshith-R , thanks for your help, I figured it out

https://rook.io/docs/rook/v1.9/Troubleshooting/ceph-csi-common-issues/#blocklisting-a-node

If the Ceph version is at least Pacific(v16.2.x), run the following command:
```
$ ceph osd blocklist add <NODE_IP> # get the node IP you want to blocklist
blocklisting <NODE_IP>
```

If the Ceph version is Octopus(v15.2.x) or older, run the following command:
```
$ ceph osd blacklist add <NODE_IP> # get the node IP you want to blacklist
blacklisting <NODE_IP>
```

In my environment,

```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# rbd status replicapool/csi-vol-e4d2d56e-70d5-11eb-9a1b-9ef3bde4434c
Watchers:
        watcher=192.168.152.128:0/765081214 client.35935078 cookie=18446462598732841662

[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph osd blacklist add 192.168.152.128:0/765081214
blacklisting 192.168.152.128:0/765081214 until 2022-12-05T19:54:52.268412+0000 (3600 sec)

[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph osd blacklist rm 192.168.152.128:0/765081214
un-blacklisting 192.168.152.128:0/765081214
[root@rook-ceph-tools-68958dbb7f-klmcn /]# 
```

**Comment by nirav-chotai** [comment]
This is resolved.
