### ISSUE TITLE
Support to monitor  rgw 

### ISSUE THREAD

**Issue by zhucan** [rook/rook#11370]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
```
ceph daemon  /var/run/ceph/ceph-client.rgw.os.dsglczutvqsgowpz.a.13.94802665027016.asok perf dump

    "rgw": {
        "req": 334795,
        "failed_req": 1294,
        "get": 74425,
        "get_b": 31888854734,
        "get_initial_lat": {
            "avgcount": 3341,
            "sum": 129.872878066,
            "avgtime": 0.038872456
        },
        "put": 74844,
        "put_b": 833752530103,
        "put_initial_lat": {
            "avgcount": 74844,
            "sum": 25895.854595270,
            "avgtime": 0.345997736
        },
        "qlen": 0,
        "qactive": 0,
        "cache_hit": 1582165,
        "cache_miss": 44823,
        "keystone_token_cache_hit": 0,
        "keystone_token_cache_miss": 0,
        "gc_retire_object": 4130,
        "lc_expire_current": 0,
        "lc_expire_noncurrent": 0,
        "lc_expire_dm": 0,
        "lc_transition_current": 0,
        "lc_transition_noncurrent": 0,
        "lc_abort_mpu": 0,
        "pubsub_event_triggered": 0,
        "pubsub_event_lost": 0,
        "pubsub_store_ok": 0,
        "pubsub_store_fail": 0,
        "pubsub_events": 0,
        "pubsub_push_ok": 0,
        "pubsub_push_failed": 0,
        "pubsub_push_pending": 0,
        "pubsub_missing_conf": 0
    },

```

**What is use case behind this feature:**
monitor  live upload and download bytes on each rgw with exporter

**Environment**:

**Comment by zhucan** [comment]
we can only run this cmd "ceph daemon  /var/run/ceph/ceph-client.rgw.os.dsglczutvqsgowpz.a.13.94802665027016.asok perf dump" in the rgw container, but now we want to mount the path to container of exporter that we can run this cmd in the exporter container, so we can get the puts and gets from each rgw(because of we wiil deploy the export under all storage node)

**Comment by avanthakkar** [comment]
> we can only run this cmd "ceph daemon /var/run/ceph/ceph-client.rgw.os.dsglczutvqsgowpz.a.13.94802665027016.asok perf dump" in the rgw container, but now we want to mount the path to container of exporter that we can run this cmd in the exporter container, so we can get the puts and gets from each rgw(because of we wiil deploy the export under all storage node)

The new ceph-exporter daemon is doing something similar to what you mentioned. https://github.com/ceph/ceph/pull/46213
Currently the implementation of it is going on rook side. Design doc https://github.com/rook/rook/pull/11360
Basically this pod will have a hostPath which will have socket files of all ceph daemons running, so exporter can then using socket client fetches perf counters (`perf dump/schema`) and exports them in form of prometheus metrics.
Hope the info is helpful!

**Comment by avanthakkar** [comment]
Forgot to mention: The existing prometheus exporter in mgr prometheus module already exports all the perf counters  as prometheus metrics at  `9283` port , so you can scrape `/metrics` in your existing prometheus config.

**Comment by zhucan** [comment]
@avanthakkar The ceph version must be "quincy"?

**Comment by avanthakkar** [comment]
> @avanthakkar The ceph version must be "quincy"?

For `ceph-exporter`, yes! The daemon is there starting from version `17.2.5`

**Comment by zhucan** [comment]
if the rook support to suppose the sock to the hostpath, we can develop a export to monitor it, no need to wait the 17.2.5. @avanthakkar

**Comment by zhucan** [comment]
@avanthakkar The "ceph-exporter" can monitor buckets the images?
