### ISSUE TITLE
Add steps about create external storage cluster based on rook as source in document.

### ISSUE THREAD

**Issue by AKS74n** [rook/rook#11404]
**Is this a bug report or feature request?**

* Feature Request

**Feature Request**

**Are there any similar features already existing:**
Dunno but I think many.

**What should the feature do:**
The current external storage cluster page in online documentation explain how to connect exist ceph cluster into rook environment. The document is talked about "bridge" to ceph cluster built by ceph-deploy or ceph-ansible, etc. But some cases would be deploy a central rook-ceph storage and let other k8s cluster can import and use as storageclass backend or sth, so that these clusters no need to build another own rook-ceph cluster and use it as "rook client".

But there're few steps that require different operation like:

1. Create `rook-ceph-toolbox` if current cluster doesn't have.
2. Copy `create-external-cluster-resources.py` into `/etc/ceph/` of toolbox.
3. Login into toolbox, execute `create-external-cluster-resources.py` with needed options to create require users and keys.

I wish these additional steps can add into document, so that user can know how to use the script if they choose rook-ceph as external source.

**What would be solved through this feature:**
Let user know how to use "create users and keys" script under rook-ceph source.

(My English is not so well, probably had some unclear explanation.)

**Comment by parth-gr** [comment]
> k8s cluster can import and use as storageclass backend or sth

Can you explain a real-time use case, So I can add it as an example of this document
@AKS74n

**Comment by AKS74n** [comment]
In our case, we have multiple K8S clusters for each team. And we wanna centralize our storage place. So we used one of the K8S cluster to deploy the central rook-ceph cluster. 

Once deployed, we only apply rook's crds, common, and operator on each external K8S cluster. Then pre-create pools for these k8s on rook-ceph cluster. Use `create-external-cluster-resources.py` to export (or generate) the info with new pool name and import to these k8s.

After that, use `cluster-external.yaml` to create rook external cluster that binding to central rook-ceph. So that all these k8s will use a same rook-ceph cluster when create storageclass and PVC.

All above is what we wanna do. And seems like it could based on I can get correct information on external k8s.

**Comment by parth-gr** [comment]
Thats great thanks

**Comment by AKS74n** [comment]
I saw the document updated due to commit merged. The usage and steps explanation are great!
Due to the merge, I think I can close this issue now. Thanks for rook development team!

**Comment by lknite** [comment]
Where should the './create-external-cluster-resources.py' script be run?  Exec into one of the pods to run it or run it on a system with kubectl to the source ceph cluster?

**Comment by parth-gr** [comment]
> Where should the './create-external-cluster-resources.py' script be run? Exec into one of the pods to run it or run it on a system with kubectl configured to use the source ceph cluster?

You can run it in the toolbox pod as described in the docs, If you want to connect to already running rook ceph cluster externally.
