### ISSUE TITLE
ProvisioningFailed' failed to provision volume with StorageClass "ceph-block": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-fd already exists

### ISSUE THREAD

**Issue by vyom-soft** [rook/rook#11428]
Hello,

with rook-ceph : v1.10.7 (helm chart)

I am seeing the above error after reinstallation. I have also read the previous similar message posted as issues here. 
And in the [trouble](https://rook.io/docs/rook/v1.9/Troubleshooting/ceph-csi-common-issues/)  under common issue, it says to 
restart the csi-rbdplugin-provisioner & csi-rbdplugin pods.

Unfortunately it does not help to get rid of the problem. Please advise.

[csi-rbdplugin-provisioner-log.txt](https://github.com/rook/rook/files/10215898/csi-rbdplugin-provisioner-log.txt)

<img width="652" alt="image" src="https://user-images.githubusercontent.com/18686082/207272646-ffe748a5-d88e-4da6-a700-d58aeb124fa1.png">

**Comment by sp98** [comment]
Can you provide the `ceph status` output?

**Comment by vyom-soft** [comment]
> Can you provide the `ceph status` output?

<img width="627" alt="image" src="https://user-images.githubusercontent.com/18686082/207262765-a940b03f-f571-4fbf-8e83-f03af247231e.png">

**Comment by sp98** [comment]
We usually see this behavior when there is a ceph health issue,  slow ops or network issue.  Can you try by fixing the ceph health and see if that fixes your original issue.

**Comment by vyom-soft** [comment]
> We usually see this behavior when there is a ceph health issue, slow ops or network issue. Can you try by fixing the ceph health and see if that fixes your original issue.

I do not think it has to do anything with health, slow ops or network.

**Comment by travisn** [comment]
> I do not think it has to do anything with health, slow ops or network.

Did you fix the health issues yet? 

> clock skew

This can cause unpredictable failures. You'll want to make sure the clocks are sync'd with ntp

> OSD count 3 < osd_pool_default_size 6

Did you intend to have replica 6??? No volumes can be provisioned if you have replica 6 and only 3 osds.

**Comment by vyom-soft** [comment]
> > I do not think it has to do anything with health, slow ops or network.
> 
> Did you fix the health issues yet?
> 
> > clock skew 
> 
> This can cause unpredictable failures. You'll want to make sure the clocks are sync'd with ntp
> 
> > OSD count 3 < osd_pool_default_size 6
> 
> Did you intend to have replica 6??? No volumes can be provisioned if you have replica 6 and only 3 osds.
Many thanks for the advise.

In my previous installation, [11153](https://github.com/rook/rook/issues/11153) I did had clock skew present earlier and all the 6 OSD were allocated. The volumes were provisioned properly was working all good. On Friday the complete H/W was brought down and restarted & I see this behaviour. 

I have destroyed the complete rook-ceph cluster now, cleanup of disk has been done as instructed in the manual.

**Comment by vyom-soft** [comment]
After complete wipe of or ceph cluster including device cleanup.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/18686082/208747034-791c7b08-c343-42f6-bfa3-08e6582f510f.png">

**Comment by Madhu-1** [comment]
Closing this one as it works without any issues.
