### ISSUE TITLE
Use `--default-*` flags for logging to stderr 

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#11429]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Rook should use `--default-log-to-stderr`, `--default-mon-cluster-log-to-stderr`, `--default-err-to-stderr`, and `--default-log-stderr-prefix` options if they are available so users can override these settings if they so desire.

**What is use case behind this feature:**
Some users have wished to change these options for whatever reasons in the past. With `--default-*`  versions, Rook can set CLI options that will ensure the average user will still get all logs to stderr as they would expect, but advanced users could enjoy different behavior.

**Environment**:

**Comment by parth-gr** [comment]
`--default-log-to-stderr` would these flags intend to have a separate output of logging, for rook operator logs?

**Comment by BlaineEXE** [comment]
> `--default-log-to-stderr` would these flags intend to have a separate output of logging, for rook operator logs?

Good clarification. These should be for the Ceph daemons pods and not for operator `ceph ...` cli ops.

**Comment by parth-gr** [comment]
Interesting we should keep alive
