### ISSUE TITLE
Remove PSPs from prerequisite docs

### ISSUE THREAD

**Issue by Abdullah-alfadhel** [rook/rook#11431]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
update the document for rook pre-requisites  the latest kubernetes version
**What is use case behind this feature:**
the new kubernetes version doesn't support the pod security policy as in the link:
https://kubernetes.io/docs/concepts/security/pod-security-policy/

**Environment**:
Kubernetes v1.25+

**Comment by travisn** [comment]
@Abdullah-alfadhel What version of Rook are you using? The latest versions of v1.9 and v1.10 are not expected to be using the PSPs.

**Comment by Abdullah-alfadhel** [comment]
you are right, rook doesn't need any update. But the documentation needs one, the prerequisite still points to apply psp.yaml

**Comment by travisn** [comment]
I see, the [PSP doc](https://rook.io/docs/rook/latest/Getting-Started/Prerequisites/pod-security-policies/) makes it look like the PSPs may be required. 

I'm thinking we can remove that doc, but leave other references to psp.yaml in case they are needed still. 
@BlaineEXE thoughts?

**Comment by Abdullah-alfadhel** [comment]
and in the quick start guide also. 

![image](https://user-images.githubusercontent.com/61710409/207774431-e4f9ed2e-4df3-48cf-8da7-f9d57b51f6a9.png)
