### ISSUE TITLE
rook-ceph-tools (error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)'))

### ISSUE THREAD

**Issue by ivanovpavel1983** [rook/rook#11464]
I installed simple ceph cluster(rook version is [v1.10.7](https://github.com/rook/rook/releases/tag/v1.10.7)) with default name rook-ceph.
I'm trying to install orch with rook-ceph-tools pod but can't connect to cluster.

![image](https://user-images.githubusercontent.com/5180093/208652611-59e117d2-5191-4ac3-b998-d28e1263678a.png)

![image](https://user-images.githubusercontent.com/5180093/208652773-b8f04f32-252a-408e-ab30-c802bca7fd1c.png)

![image](https://user-images.githubusercontent.com/5180093/208653401-6ed2086c-2d9e-4874-b528-d449fa5d8948.png)

**Comment by travisn** [comment]
If the toolbox commands are failing, this usually means the mons are not in quorum. What pods do you have running in the `rook-ceph` namespace? I'm suspecting only the mons are running (and not the mgr or osds). Try [this topic](https://rook.io/docs/rook/latest/Troubleshooting/ceph-common-issues/#monitors-are-the-only-pods-running) for ideas on getting the mons running in quorum.

**Comment by parth-gr** [comment]
And can you also share the details of ceph.conf
I suspect it to be empty

**Comment by ivanovpavel1983** [comment]
Mons are in quorum, cluster works well:

![image](https://user-images.githubusercontent.com/5180093/208706367-20f86944-8c23-4751-b27e-e00971e3a5a9.png)

**Comment by ivanovpavel1983** [comment]
> And can you also share the details of ceph.conf I suspect it to be empty

Yes of course.
Here is:
![image](https://user-images.githubusercontent.com/5180093/208706900-f473bf1f-1cd0-4981-9d62-6931f7a98b41.png)

**Comment by ivanovpavel1983** [comment]
> If the toolbox commands are failing, this usually means the mons are not in quorum. What pods do you have running in the `rook-ceph` namespace? I'm suspecting only the mons are running (and not the mgr or osds). Try [this topic](https://rook.io/docs/rook/latest/Troubleshooting/ceph-common-issues/#monitors-are-the-only-pods-running) for ideas on getting the mons running in quorum.

This is the list of pods in rook-ceph ns:
![image](https://user-images.githubusercontent.com/5180093/208708181-b8fb8c96-c294-461b-8a6f-602114b44f07.png)

**Comment by travisn** [comment]
What version of the toolbox pod are you running? Since the cluster seems healthy other than the toolbox I wonder if this could be a regression from #11434.

I'm guessing you're running the version of the toolbox that hasn't been released yet. Try the [v1.10.7 toolbox](https://github.com/rook/rook/blob/v1.10.7/deploy/examples/toolbox.yaml) instead.

**Comment by ivanovpavel1983** [comment]
I'm using version v.1.4.6.
![image](https://user-images.githubusercontent.com/5180093/208725688-f45c7fe5-a30a-45c9-bce5-3ec276d9f64c.png)

![image](https://user-images.githubusercontent.com/5180093/208725809-ff7f0011-6397-4517-a846-f1623328ba38.png)

Or is it better to install it separately manually?

**Comment by travisn** [comment]
Your original issue said you installed v1.10.7. Are you mixing versions? You need to install the toolbox from the same version as the operator.

**Comment by ivanovpavel1983** [comment]
Yes, I'm a fool .. I don't know where I got it from .. Probably from some example.
Thanks a lot. Have a nice day!
![image](https://user-images.githubusercontent.com/5180093/208731728-9c0d758f-565d-48e2-b4de-3f55bb99f685.png)

**Comment by erictarrence** [comment]
> If the toolbox commands are failing, this usually means the mons are not in quorum. What pods do you have running in the `rook-ceph` namespace? I'm suspecting only the mons are running (and not the mgr or osds). Try [this topic](https://rook.io/docs/rook/latest/Troubleshooting/ceph-common-issues/#monitors-are-the-only-pods-running) for ideas on getting the mons running in quorum.

This problem also occurred after my rook-ceph-operator pod was restarted repeatedly.

```
# kubectl -n rook-ceph get svc -l app=rook-ceph-mon -o jsonpath='{.items[0].spec.clusterIP}'
172.23.4.200

# kubectl -n rook-ceph exec deploy/rook-ceph-operator -- curl $(kubectl -n rook-ceph get svc -l app=rook-ceph-mon -o jsonpath='{.items[0].spec.clusterIP}'):3300 2>/dev/null
ceph v2

# kubectl -n rook-ceph get pod -o wide -l ceph_daemon_type=mon
NAME                               READY   STATUS    RESTARTS       AGE    IP              NODE      NOMINATED NODE   READINESS GATES
rook-ceph-mon-b-76b7dd565f-26wzh   2/2     Running   24 (16d ago)   207d   192.168.0.169   node169   <none>           <none>
rook-ceph-mon-e-f88457bc7-59fwq    2/2     Running   28 (16d ago)   221d   192.168.0.168   node168   <none>           <none>
rook-ceph-mon-f-97794cbd5-tszw4    2/2     Running   24 (16d ago)   230d   192.168.0.167   node167   <none>           <none>



#  kubectl -n rook-ceph exec -it rook-ceph-operator-c65586dd9-q9cb2 -- sh

sh-4.4$ curl http://172.23.4.200:3300  2>/dev/null
ceph v2
sh-4.4$ ceph -v
ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
sh-4.4$ ceph -s
Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
sh-4.4$ ceph status
Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
sh-4.4$ 
sh-4.4$ cd /var/lib/rook/rook-ceph/
sh-4.4$ ls
client.admin.keyring  rook-ceph.config
sh-4.4$ cat rook-ceph.config 
[global]
fsid                = 8e633ee3-e904-42b1-a710-1fc07bd4e988
mon initial members = b f e
mon host            = [v2:192.168.0.169:3300,v1:192.168.0.169:6789],[v2:192.168.0.167:3300,v1:192.168.0.167:6789],[v2:192.168.0.168:3300,v1:192.168.0.168:6789]
public network      = 192.168.0.0/23
cluster network     = 192.168.8.0/24
public addr         = 
cluster addr        = 

[osd]
osd crush update on start = false


kubectl  -n rook-ceph get svc rook-ceph-mon -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-08T11:29:29Z"
  labels:
    app: rook-ceph-mon
  name: rook-ceph-mon
  namespace: rook-ceph
  resourceVersion: "130326883"
  uid: c4b746e5-c9b3-40be-9859-9f4c89e49a6c
spec:
  clusterIP: 172.23.4.200
  clusterIPs:
  - 172.23.4.200
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-msgr2
    port: 3300
    protocol: TCP
    targetPort: 3300
  - name: tcp-msgr1
    port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app: rook-ceph-mon
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
[root@test-alma9-k
```

**Comment by erictarrence** [comment]
> And can you also share the details of ceph.conf I suspect it to be empty



> And can you also share the details of ceph.conf I suspect it to be empty

The /etc/ceph directory of rook-ceph-operator pod is empty and there is no ceph.conf file. How to solve the problem?

```
#  kubectl -n rook-ceph exec -it rook-ceph-operator-c65586dd9-q9cb2 -- sh

sh-4.4$ ls /etc/ceph
sh-4.4$ ls /var/lib/rook/
rook-ceph
```
