### ISSUE TITLE
Generate CRD types with 1.8 generator

### ISSUE THREAD

**Issue by travisn** [rook/rook#1146]
K8s 1.8 comes with a new code generator for CRDs to use the same code generation as in-tree types. See https://blog.openshift.com/kubernetes-deep-dive-code-generation-customresources/

We may need to hold off doing this until we are ready to stop supporting TPRs (pre-1.7).

**Comment by travisn** [comment]
While upgrading the operator-kit to the 1.8 client, I verified that the sample walkthrough was able to be deployed on 1.6 with TPRs as well. So it is looking like we can continue to support TPRs on 1.6 with this change

**Comment by bassam** [comment]
@travisn let's proceed with completing the PR then, and then extract the pieces to go into the operator-kit. what do you think?

**Comment by travisn** [comment]
Fixed by #1153. With this change the TPRs are still supported by Rook
