### ISSUE TITLE
K8S-Rook-ceph-operator error

### ISSUE THREAD

**Issue by musayldrm11** [rook/rook#11475]
Hi 

We have a kubernetes cluster ,we are using rook-ceph also.Rook-ceph operator is not working.
We are getting that error on rook-ceph-operator .

K8s-cluster version  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1"
Rook-ceph version  ceph version 16.2.6

The Error

onnecting to the cluster)\n'
2022-11-25T11:39:03.805243782+03:00 stderr F WARNING:ceph-crash:post /var/lib/ceph/crash/2022-11-25T08:37:53.732561Z_15e833c7-ff84-46ac-a1ef-a676f3b52d9c as client.crash.rook-ceph-crashcollector-kubeprodworker03-988bd9687-9gl68 failed: b'2022-11-25T08:39:00.801+0000 7f2ea4895700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]\n2022-11-25T08:39:00.801+0000 7f2e9ffff700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]\n2022-11-25T08:39:03.801+0000 7f2e9ffff700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]\n2022-11-25T08:39:03.801+0000 7f2e9f7fe700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]\n[errno 13] RADOS permission denied (error connecting to the cluster)\n'

**Comment by travisn** [comment]
This error is in the operator log? What does `ceph status` show in the toolbox? Is Ceph HEALTH_OK?

**Comment by musayldrm11** [comment]
> This error is in the operator log? What does `ceph status` show in the toolbox? Is Ceph HEALTH_OK?

Status
waiting
Last Status
terminated
Reason:Reason: Error - exit code: 1
Started at: 2023-01-03T14:52:44+03:00
Finished at: 2023-01-03T14:55:15+03:00

**Comment by travisn** [comment]
Please run `ceph status` in the [Rook toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/) and share the output.

Do you have any more details about the repro steps or what happened in the cluster? Was the cluster healthy previously, or you're setting up the cluster for the first time?

**Comment by musayldrm11** [comment]
ı can access rook-ceph operator pod ,we set cluster with kubespray

**Comment by nkalmar-kx** [comment]
We are hitting this issue sometimes, and it's a bit of a hussle to fix.
get-or-create creates a new key, one that does not match the one in the keyring file saved on the node.
That keyring is mounted as well, and I can print it in the init script. tryed to change the get-or-create to use that keyring file:

ceph -n client.admin auth get-or-create osd.3 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k **/var/lib/ceph/osd/ceph-3/keyring**

So instead of /etc/ceph/admin-keyring-store/keyring I use the already saved keyring on the node, which if I manually enter in ceph auth it works. But with this new command I get the same handle_auth_bad_method error in the init container:

```
 ceph -n client.admin auth get-or-create osd.3 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /var/lib/ceph/osd/ceph-3/keyring
2023-04-15T17:07:50.531+0000 7fd6cd061700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2023-04-15T17:07:50.531+0000 7fd6cd862700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2023-04-15T17:07:50.539+0000 7fd6cc860700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
[errno 13] RADOS permission denied (error connecting to the cluster)
```

This seems like a bug on ceph side, one that does not have a solution, only manual hacking. Is there any plans to fix this? 
We can't invalidate or remove the keyring already saved on the node, a new one is generated if new osd pod is initiated, but that won't match the already existing one, so it won't get accepted. And it's quite a trickery to get the original keyring, especially trying to autoamte it.

**Comment by bartlaarhoven** [comment]
I ran into this issue as well recently, for me it happened after freshly reinstalling the nodes (going from CentOS 7 to Debian 12) but using the same disks.

For me, the solution was to do a `fdisk -w always /dev/sda` on the disks used as OSD. That, combined with multitudes of `ceph auth del osd.0` and deleting the deployment, did the trick in the end.

In case someone runs into this in a similar situation, I hope this helps.

**Comment by wkjun** [comment]
> Just figured I'd document what I used to solve this in case it helps someone else.
> 
> Basically I followed #4238, specifically [this comment](https://github.com/rook/rook/issues/4238#issuecomment-664627282).
> 
> ```
> cat <<EOF > osd.2.export
>     [osd.2]
>     key = ${obfuscated}
>     caps mon = "allow profile osd"
>     caps mgr = "allow profile osd"
>     caps osd = "allow *"
> EOF
> ceph auth import -i osd.2.export
> >> imported keyring
> ```
> 
> After this I just restarted the OSD pod and it came up without issues.
> 
> The thing that's confusing for me and that I don't understand is, I can see there's an init container running the below command, which I think should be the same as the one I ran manually, but it didn't work even though it says it did? The actual value of the key is the same as my manual run as well.
> 
> ```
> ceph -n client.admin auth get-or-create osd.2 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
> >>[osd.2]
> >>	key = ${obfuscated}
> ```
> 
> Either way I'm happy! also really appreciate all of the fantastic work you all do on this great project.

```
 cat <<EOF > osd.2.export
[osd.2]
key = ${obfuscated}
caps mon = "allow profile osd"
caps mgr = "allow profile osd"
caps osd = "allow *"
EOF
ceph auth import -i osd.2.export
...imported keyring
```
the  in front of  [osd.2]  show have no space ,otherwise `ceph auth import -i `  output this error:

```
Error EINVAL: error decoding keyring cannot parse buffer: Malformed input
```
