### ISSUE TITLE
[question] integration with another operator

### ISSUE THREAD

**Issue by vsoch** [rook/rook#11481]
Hiya! I think I could open this on the slack, but since it's the holiday I thought this might be better to catch someone in the new year. Basically, I'm interested in a storage solution for an operator I'm developing for Flux, meaning we can run HPC-type workloads in Kubernetes https://github.com/flux-framework/flux-operator. I've mostly been doing local development with MiniKube, and of course in this context a local host volume works fine, but today I tried for the first time to deploy to GKE, and the persistent volume claim (that needs to be ReadWriteMany) of course failed! I'm looking into robust solutions to deploy storage (ideally controlled by our operator to avoid complexity) and most of what I've seen talks about setting up NFS https://medium.com/@Sushil_Kumar/readwritemany-persistent-volumes-in-google-kubernetes-engine-a0b93e203180. I saw a suggestion for Rook here https://discuss.kubernetes.io/t/how-to-setup-a-readwritemany-and-readwriteonce-storageclass/12097 and while it looks like this is an operator in and of itself (which might not be ideal to require two operators) I thought it might be that someone else had come here with a similar need and I'd open up an issue for discussion! Is there some use case for rook, or an underlying volume type / service that rook uses, that we could use in the Flux Operator? Thanks for your wisdom - and apologies if this is super noob question I'm new to developing for Kubernetes (and really loving it so far!)

**Comment by travisn** [comment]
If you need a RWX volume, you will want to use a CephFS volume, which Rook will help you configure. See the [Getting Started](https://rook.io/docs/rook/latest/Getting-Started/quickstart/) guide to setup the Rook cluster, and then create the [Ceph Filesystem](https://rook.io/docs/rook/latest/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage/).

**Comment by vsoch** [comment]
Thank you! I’ll try that.

**Comment by vsoch** [comment]
As a final update to the issue, I decided not to use rook.
