### ISSUE TITLE
Helm chart should include necessary RBAC for external clusters

### ISSUE THREAD

**Issue by lknite** [rook/rook#11480]
* Feature Request

**What should the feature do:**
An additional helm chart which, upon installing, sets up a cephfs storageclass which is able to consume ceph setup on a different kubernetes cluster.

Found this design document which is talking about the feature, though not from a helm chart perspective.
https://github.com/rook/rook/blob/master/design/ceph/ceph-external-cluster.md

**What is use case behind this feature:**
I've setup cephfs on a cluster using the two helm charts.  Everything is working.  Am able to provision a pvc.

Now, from a couple other clusters dev/prod, I'd like to add a default storageclass which when I create a pvc, is able to use the ceph server setup on the first cluster.

A 3rd helm chart is not needed if the operator chart had values which could be set for a client install, not sure if a 3rd chart is necessary, but maybe it is to keep things simple by keeping a server setup separate from a client setup.  Either way would work.

Maybe?
rook-ceph-server-operator
rook-ceph-server-cluster
rook-ceph-client-operator
rook-ceph-client-cluster

Add a setting in the existing helm charts to use a 'loadbalancer' or 'nodeip' ip for the mons, since that is needed for the ceph server to be consumed remotely.  Maybe an option called 'enableExternalAccess: true' or something similar will set up the hosted cluster in such a way as to be ready to be consumed from an outside k8s cluster.

**Environment**:
- standard k8s cluster setup using kubeadm with 3 control plane nodes, 3 worker nodes & an haproxy in front
- deploy ceph using the two existing helm charts
- another standard k8s cluster setup
- deploy 3rd helm chart with values.yaml specifying the ip of the mons of the ceph server, and whatever else is necessary

**Comment by parth-gr** [comment]
Is your requirement related to this,
https://github.com/rook/rook/blob/master/Documentation/CRDs/Cluster/external-cluster.md#exporting-rook-to-another-cluster
As it connects to a central external server.

Provided it by helm chart??

**Comment by lknite** [comment]
Yes, I am working to implement the steps on that page.  So far I have:
- setup a kubernetes cluster just for ceph
- deployed ceph using the two helm charts
- tested, was able to request a pvc successfully on the ceph source server (made sure 'network.provider: host' was set)
- deployed rook operator on an external cluster (with an empty values.yaml)
- applied a 'CephCluster' object via cluster-external.yaml
- generated the needed resources using 'create-external-cluster-resources.py', and then applied to external cluster (https://github.com/rook/rook/issues/11157)

I was hoping everything would be working at this point, but so far no luck.  I must be missing a step, or perhaps I needed to set some options in the rook operator helm chart on the external cluster?  Because I'm not sure, I wondered if it might make sense to have a 3rd helm chart.  Such a chart could include the 'cephcluster' automatically, as that seems to only be needed in the external cluster scenario... and maybe some other things I don't know about?

**Comment by lknite** [comment]
In that documentation it mentions things to deploy, I would think the existing 'rook' helm chart would do these steps automatically if 'external' is selected, or a new 3rd helm chart for the external cluster:

Deploy Rook, create [common.yaml](https://github.com/rook/rook/blob/master/deploy/examples/common.yaml), [crds.yaml](https://github.com/rook/rook/blob/master/deploy/examples/crds.yaml) and [operator.yaml](https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml) manifests.

Create [common-external.yaml](https://github.com/rook/rook/blob/master/deploy/examples/common-external.yaml) and [cluster-external.yaml](https://github.com/rook/rook/blob/master/deploy/examples/cluster-external.yaml)

I'm betting those first three have already been taken care of by the rook operator helm chart, and I already added the cluster-external.yam so I'm working on the common-external.yaml in case I need to do that manually.  Not sure if that already taken care of by the rook operator.

**Comment by lknite** [comment]
I was able to get it working by adding 'common-external.yaml' & 'cluster-external' in addition to deploying the rook operator with an empty values.yaml & adding in the resources generated by my modified import script here:  https://github.com/rook/rook/issues/11157

Though its working now, I'm still interested in making this simpler in the future by including the 'common-external.yaml' and 'cluster-external.yaml' in the helm chart somehow.  But wanted to updated the notes for anyone coming across this ticket later.

**Comment by travisn** [comment]
> I was able to get it working by adding 'common-external.yaml' & 'cluster-external' in addition to deploying the rook operator with an empty values.yaml & adding in the resources generated by my modified import script here: #11157
> 
> Though its working now, I'm still interested in making this simpler in the future by including the 'common-external.yaml' and 'cluster-external.yaml' in the helm chart somehow. But wanted to updated the notes for anyone coming across this ticket later.

Agreed, the helm chart should include the needed RBAC automatically if it's an external cluster.

**Comment by travisn** [comment]
@lknite I believe you can actually accomplish your goal of the external cluster by using only the helm charts. 

First, install the two helm charts on your source cluster. Sounds like this is already fully working.

Then install the helm charts on the external cluster, but with one important modification... The `cephClusterSpec` in the values.yaml must be overridden to be the spec for the external cluster. So you could copy the cluster-external.yaml spec into the `cephClusterSpec` of the values.yaml, and use that to override the default values. 

In my testing I found that the external RBAC existed and the CephCluster CR was created as expected with the spec that matched the cluster-external.yaml example (since that's what I copied to cephClusterSpec). And there was no need to separately create the cluster-external.yaml or common-external.yaml. Does this work for you?

**Comment by lknite** [comment]
At this point I've got a ceph cluster up and lots deployed into it, don't have my test setup anymore.  If it's working for you, and working the way you expect users should be setting things up, then I think we are good to go.  Next time I install I'll reference this ticket and try using this method.  Hopefully others will come across this ticket to know this is the method they should use.
