### ISSUE TITLE
pvc timed out waiting for the condition

### ISSUE THREAD

**Issue by clcc2019** [rook/rook#11490]
error
```yaml
Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[rules default-token-wqbpp config storage scratch]: timed out waiting for the condition
```
When there are too many files and paths stored in pvc, the startup pod cannot be quickly hung on the volume, and it takes 30+ minutes to wait according to the number of files

**Environment**:
* OS (e.g. from /etc/os-release):debian11
* Kernel (e.g. `uname -a`): 4.19
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`): all
* Kubernetes version (use `kubectl version`):v1.20
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by Madhu-1** [comment]
please check https://rook.io/docs/rook/v1.10/Troubleshooting/ceph-csi-common-issues/

**Comment by Doublefull** [comment]
Hi! Same issue. How did you manage to solve it?

**Comment by clcc2019** [comment]
> Hi! Same issue. How did you manage to solve it?

Can't solve it, just wait，see: fsGroupChangePolicy，https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by Doublefull** [comment]
I tried setting fsGroupChangePolicy to OnRootMismatch, but I have this errors even with empty rook-ceph volumes, so I don't belive the problem is with permissions changing. Pods are starting very slowly but no problem occurs if I use other type of volume  with another storage class.
