### ISSUE TITLE
RBD Mirror Daemon not syncing images

### ISSUE THREAD

**Issue by dexma-dev** [rook/rook#11492]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
RBD mirror daemon should sync images.

**How to reproduce it (minimal and precise):**
- install helm operator
- create cluster cr
- create block pool
- enable mirroring
- create test image
- enable image mirroring via volume replication

I followed [the documentation](https://rook.io/docs/rook/latest/Storage-Configuration/Block-Storage-RBD/rbd-mirroring/) on how to setup the rbd mirroring between two ceph clusters. 
After creating the volume replication object for a test pvc, the mirror daemon outputs the following error:

```
debug 2023-01-02T14:56:46.915+0000 7f0f929a26c0 0 rbd::mirror::PoolReplayer: 0x561b025b9800 init_rados: reverting global config option override: keyring: /etc/ceph/keyring-store/keyring -> /etc/ceph/96677e18-48e8-4fb8-8a5f-0dcc7d7f1eb9.client.rbd-mirror-peer.keyring,/etc/ceph/96677e18-48e8-4fb8-8a5f-0dcc7d7f1eb9.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin
debug 2023-01-02T14:56:46.915+0000 7f0f929a26c0 0 rbd::mirror::PoolReplayer: 0x561b025b9800 init_rados: reverting global config option override: mon_host: [v2:10.0.0.24:3300,v1:10.0.0.24:6789],[v2:10.0.0.7:3300,v1:10.0.0.7:6789],[v2:10.0.0.3:3300,v1:10.0.0.3:6789],[v2:10.0.0.4:3300,v1:10.0.0.4:6789] ->
debug 2023-01-02T14:56:46.915+0000 7f0f929a26c0 -1 Errors while parsing config file!
debug 2023-01-02T14:56:46.915+0000 7f0f929a26c0 -1 can't open 96677e18-48e8-4fb8-8a5f-0dcc7d7f1eb9.conf: (2) No such file or directory
debug 2023-01-02T14:56:47.183+0000 7f0f929a26c0 0 rbd::mirror::PoolReplayer: 0x561b03e9bb00 init_rados: reverting global config option override: keyring: /etc/ceph/keyring-store/keyring -> /etc/ceph/96677e18-48e8-4fb8-8a5f-0dcc7d7f1eb9.client.rbd-mirror-peer.keyring,/etc/ceph/96677e18-48e8-4fb8-8a5f-0dcc7d7f1eb9.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin
debug 2023-01-02T14:56:47.183+0000 7f0f929a26c0 0 rbd::mirror::PoolReplayer: 0x561b03e9bb00 init_rados: reverting global config option override: mon_host: [v2:10.0.0.24:3300,v1:10.0.0.24:6789],[v2:10.0.0.7:3300,v1:10.0.0.7:6789],[v2:10.0.0.3:3300,v1:10.0.0.3:6789],[v2:10.0.0.4:3300,v1:10.0.0.4:6789] ->
debug 2023-01-02T14:56:47.183+0000 7f0f929a26c0 -1 Errors while parsing config file!
debug 2023-01-02T14:56:47.183+0000 7f0f929a26c0 -1 can't open 96677e18-48e8-4fb8-8a5f-0dcc7d7f1eb9.conf: (2) No such file or directory
debug 2023-01-02T14:57:17.864+0000 7f0f7a509700 -1 librbd::managed_lock::GetLockerRequest: 0x561b05779110 handle_get_lockers: failed to retrieve lockers: (2) No such file or directory
debug 2023-01-02T14:57:17.880+0000 7f0f79d08700 -1 librbd::managed_lock::GetLockerRequest: 0x561b05779490 handle_get_lockers: failed to retrieve lockers: (2) No such file or directory
debug 2023-01-02T15:57:18.011010780+01:00 2023-01-02T14:57:18.004+0000 7f0f87d24700 -1 librbd::managed_lock::GetLockerRequest: 0x561b05779570 handle_get_lockers: failed to retrieve lockers: (2) No such file or directory2023-01-02T15:57:18.011021681+01:00
debug 2023-01-02T15:57:18.129115001+01:00 2023-01-02T14:57:18.128+0000 7f0f87523700 -1 librbd::managed_lock::GetLockerRequest: 0x561b057795e0 handle_get_lockers: failed to retrieve lockers: (2) No such file or directory2023-01-02T15:57:18.129151050+01:00
```

I have no idea where to problem is coming from. None of the sidecars of the csi provisioner is reporting any error.
Any idea what might be the problem?
I can enable the image mirroring via the ceph dashboard and the mirroring process seems to be allright.

**Comment by Madhu-1** [comment]
Hey @dexma-dev couple of questions

* can you please paste the blockpool yaml output from both clusters?
* can you please paste the pool mirror status from the toolbox pods?
* Check images are mirrored in the remote clusters.

**Comment by dexma-dev** [comment]
@Madhu-1 After some further investigation i think i found the problem.
I created the csi-addons controller als described in the [ceph csi driver docs](https://rook.io/docs/rook/v1.10/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/#csi-addons-controller).

Now the synchronization is working as expected. 
As the creation of the csi-addons-controller is not described in the [rbd mirroring docs](https://rook.io/docs/rook/v1.10/Storage-Configuration/Block-Storage-RBD/rbd-mirroring/#enable-csi-replication-sidecars), this should be added or clarified.

**Comment by Madhu-1** [comment]
@dexma-dev please feel free to send a PR to update the rbd mirroring docs

**Comment by TheCodingSheikh** [comment]
Are the ceph clusters in different kubernetes clusters, if so how did you manage to make them reachable to each other? Im stuck at this point and so such clarification in the documentation

**Comment by mdsahelpv** [comment]
Am.also stuck at these.point because am talking about rook ceph in 2 kubernetes cluster.  Not 2 rook ceph cluster in 1 kubernetes. No matter which documents and steps I tried I couldn't make it work..
