### ISSUE TITLE
osd mon mgr not runnning

### ISSUE THREAD

**Issue by Xsy2002** [rook/rook#11501]
![image](https://user-images.githubusercontent.com/67572942/210709932-f4122792-71b5-4db1-bdee-ab00ea117820.png)

**Comment by Xsy2002** [comment]
https://rook.github.io/docs/rook/v1.8/quickstart.html  I refer to this document

**Comment by Xsy2002** [comment]
this is error info （ Health check failed: mon is allowing insecure global_id reclaim 
cluster Health check failed: mon is allowing insecure global_id reclaim）

**Comment by Xsy2002** [comment]
is pvc info （）
![image](https://user-images.githubusercontent.com/67572942/210710391-a28b0ae7-9ce7-4550-826b-56e550177007.png)

**Comment by travisn** [comment]
Please see the [troubleshooting guide for mons not forming quorum](https://rook.github.io/docs/rook/v1.10/Troubleshooting/ceph-common-issues/#monitors-are-the-only-pods-running). Likely there is a network issue.

**Comment by Xsy2002** [comment]
I see to info 
![image](https://user-images.githubusercontent.com/67572942/210913230-ba59a882-93d5-4c94-ae05-24f665958917.png)

**Comment by Xsy2002** [comment]
ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to start mon pods: failed to check mon quorum a: failed to wait for mon quorum: exceeded max retry count waiting for monitors to reach quorum

**Comment by Xsy2002** [comment]
Whether to delete rook hostpath in the rook environment?

**Comment by Xsy2002** [comment]
Or it doesn't support secondary installation?
