### ISSUE TITLE
cephfs: pod pvc mount error - unable to get monitor info from DNS SRV with service name: ceph-mon

### ISSUE THREAD

**Issue by delorsh** [rook/rook#11521]
**Is this a bug report or feature request?**

Bug report

**Deviation from expected behavior:**

pods are unable to mount provisioned storage.

**How to reproduce it (minimal and precise):**

Installed rook-ceph cluster on 3 machines successfully a few weeks ago. Now creating a similar cluster on another set of machines.
Using the quickstart guide as a test.

**Result**: PVCs are successfully bound, but pods get the following error message:

```
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Normal   Scheduled               113s  default-scheduler        Successfully assigned default/csicephfs-demo-pod to node1
  Normal   SuccessfulAttachVolume  113s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-152e4fc2-78d6-42b5-b7eb-abee0075efa6"
  Warning  FailedMount             30s   kubelet                  MountVolume.MountDevice failed for volume "pvc-152e4fc2-78d6-42b5-b7eb-abee0075efa6" : rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 10.152.183.85:3300,10.152.183.179:3300,10.152.183.170:3300:/volumes/csi/csi-vol-5dea2fc5-903a-11ed-9c55-966dac29b811/8c3dab4c-243f-489e-be89-97bee4b30d8a /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/b941d4a346d3c4385779e206d76a2e31f472825c057f64a973d64dac957a70b6/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-3166377907,mds_namespace=myfs,_netdev] stderr: unable to get monitor info from DNS SRV with service name: ceph-mon
2023-01-09T17:51:39.771+0000 7f9a29f55f40 -1 failed for service _ceph-mon._tcp
mount error: no mds server is up or the cluster is laggy
```

csi-cephfs pod log is full of these messages:
```
libceph: mon0 (1)10.152.183.85:3300 socket closed (con state V1_BANNER)
```

ceph status is ok.

microk8s internal DNS is (seems to be?) working properly, as other namespaces and even rook-ceph components are fine.

Following the quickstart documentation, everything is good up to this point:

```
$ kubectl create -f deploy/examples/csi/cephfs/pvc.yaml
$ kubectl get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc   Bound    pvc-152e4fc2-78d6-42b5-b7eb-abee0075efa6   1Gi        RWO            rook-cephfs    41m
$ kubectl create -f deploy/examples/csi/cephfs/pod.yaml
$ kubectl get -f deploy/examples/csi/cephfs/pod.yaml
NAME                 READY   STATUS              RESTARTS   AGE
csicephfs-demo-pod   0/1     ContainerCreating   0          42m
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

my changes to cluster.yaml:

```
# enable rook module
mgr: 
  modules:
      - name: pg_autoscaler
        enabled: true
      - name: rook
        enabled: true

network:
    connections:
      encryption:
        enabled: true

crashCollector:
    disable: true
```
**Logs to submit**:

Not familiar enough with rook-ceph yet to know which logs to submit.

Strange csi-cephfsplugin logs of node1 where the pod is scheduled to run:

```
[...]
[371099.447054] libceph: mon0 (1)10.152.183.85:3300 socket closed (con state V1_BANNER)
[371099.963784] libceph: mon0 (1)10.152.183.85:3300 socket closed (con state V1_BANNER)
[371100.987662] libceph: mon0 (1)10.152.183.85:3300 socket closed (con state V1_BANNER)
[371103.292448] libceph: mon2 (1)10.152.183.170:3300 socket closed (con state V1_BANNER)
[371104.572185] libceph: mon2 (1)10.152.183.170:3300 socket closed (con state V1_BANNER)
[371106.108341] libceph: mon1 (1)10.152.183.179:3300 socket closed (con state V1_BANNER)
[371107.388394] libceph: mon1 (1)10.152.183.179:3300 socket closed (con state V1_BANNER)
[371108.154964] ceph: No mds server is up or the cluster is laggy
[371108.155806] libceph: mon0 (1)10.152.183.85:3300 socket closed (con state V1_BANNER)
[371251.260682] libceph: mon2 (1)10.152.183.170:3300 socket closed (con state V1_BANNER)
[371252.540466] libceph: mon2 (1)10.152.183.170:3300 socket closed (con state V1_BANNER)
[...]
```

**Cluster Status to submit**:

```
cluster:
    id:     940a37a5-7a56-4556-9d62-a631f65bef5d
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 52m)
    mgr: b(active, since 51m), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 51m), 3 in (since 52m)

  data:
    volumes: 1/1 healthy
    pools:   3 pools, 49 pgs
    objects: 28 objects, 633 KiB
    usage:   84 MiB used, 840 GiB / 840 GiB avail
    pgs:     49 active+clean

  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr
```

```
$ ceph fs status
myfs - 1 clients
====
RANK      STATE        MDS       ACTIVITY     DNS    INOS   DIRS   CAPS
 0        active      myfs-a  Reqs:    0 /s    26     22     19      6
0-s   standby-replay  myfs-b  Evts:    0 /s    25     13     10      0
      POOL         TYPE     USED  AVAIL
 myfs-metadata   metadata   660k   265G
myfs-replicated    data    12.0k   265G
MDS version: ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
```

```
$ ceph fs ls
name: myfs, metadata pool: myfs-metadata, data pools: [myfs-replicated ]
```

rook:

```
$ kubectl get pod -n rook-ceph
NAME                                            READY   STATUS      RESTARTS   AGE
rook-ceph-operator-56b85d8f69-mq2rp             1/1     Running     0          70m
rook-discover-4pf6p                             1/1     Running     0          70m
rook-discover-bzfv6                             1/1     Running     0          70m
rook-discover-qbw2p                             1/1     Running     0          70m
csi-cephfsplugin-h5gr9                          2/2     Running     0          68m
csi-rbdplugin-xdkww                             2/2     Running     0          68m
csi-rbdplugin-rsnh4                             2/2     Running     0          68m
csi-rbdplugin-provisioner-5f888dd9f4-tdkf7      5/5     Running     0          68m
csi-rbdplugin-8hvql                             2/2     Running     0          68m
csi-cephfsplugin-72rpl                          2/2     Running     0          68m
csi-cephfsplugin-provisioner-685ff8c9d7-jcnmc   5/5     Running     0          68m
csi-cephfsplugin-6vc2f                          2/2     Running     0          68m
csi-cephfsplugin-provisioner-685ff8c9d7-khfg4   5/5     Running     0          68m
csi-rbdplugin-provisioner-5f888dd9f4-d5t76      5/5     Running     0          68m
rook-ceph-mon-a-65bdc7765b-gnbdn                2/2     Running     0          68m
rook-ceph-mon-b-565b9968c-j64fx                 2/2     Running     0          68m
rook-ceph-mon-c-68f5bc86b5-dtsff                2/2     Running     0          68m
rook-ceph-mgr-b-87994b84d-lf8r6                 3/3     Running     0          67m
rook-ceph-mgr-a-5994b8dbc5-99ptw                3/3     Running     0          67m
rook-ceph-osd-1-5cdfd77b87-wcdfm                2/2     Running     0          67m
rook-ceph-osd-0-5794d7b868-2rmpw                2/2     Running     0          67m
rook-ceph-osd-2-6b48f78c58-q5nxr                2/2     Running     0          67m
rook-ceph-mds-myfs-a-54695fc877-v8tw8           2/2     Running     0          64m
rook-ceph-mds-myfs-b-6d5b4788bb-b2t6p           2/2     Running     0          64m
rook-ceph-tools-7c4b8bb9b5-gpzrq                1/1     Running     0          53m
rook-ceph-osd-prepare-database03-npn9h          0/1     Completed   0          9m48s
rook-ceph-osd-prepare-database01-72q8v          0/1     Completed   0          9m45s
rook-ceph-osd-prepare-database02-g6nxm          0/1     Completed   0          9m42s
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04.1
* Kernel (e.g. `uname -a`): 5.15.0-56-generic 62-Ubuntu (x86_64)
* Cloud provider or hardware configuration: bare metal Dell servers
* Rook version (use `rook version` inside of a Rook Pod): v1.10.8
* Storage backend version (e.g. for ceph do `ceph -v`): 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`): MicroK8s v1.26.0 revision 4390
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): microk8s (snap)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by travisn** [comment]
@delorsh In the cluster where it was working correctly, were there any differences in the cluster configuration? For example, was the network encryption enabled in that cluster as well?

**Comment by travisn** [comment]
If you're reinstalling, just make sure to following the [cleanup guide](https://rook.io/docs/rook/latest/Getting-Started/ceph-teardown/#delete-the-data-on-hosts), especially to delete the data on the hosts before installing again. As long as your three OSDs are created, it sounds like it was successful. 

Also look through the [CSI troubleshooting guide](https://rook.io/docs/rook/latest/Troubleshooting/ceph-csi-common-issues/) and see if there are any errors in the csi logs.

**Comment by travisn** [comment]
Actually, this may be fixed in the next release in the next couple days with #11523, if you want to test the encryption again soon.

**Comment by travisn** [comment]
> Actually, this may be fixed in the next release in the next couple days with #11523, if you want to test the encryption again soon.

Wait, maybe not since that's for rbd, but you're testing with cephfs volumes

**Comment by Madhu-1** [comment]
i tried with cephfs but because of kernel version i got below error

```
[  511.378049] ceph: Unknown parameter 'ms_mode'
[  511.977924] ceph: Unknown parameter 'ms_mode'
[  513.088257] ceph: Unknown parameter 'ms_mode'
[  515.207342] ceph: Unknown parameter 'ms_mode'
[  519.373179] ceph: Unknown parameter 'ms_mode'
[  527.503393] ceph: Unknown parameter 'ms_mode'
[  543.608241] ceph: Unknown parameter 'ms_mode'
[  575.829500] ceph: Unknown parameter 'ms_mode'
[  627.079992] ceph: Unknown parameter 'ms_mode'
[  635.222962] ceph: Unknown parameter 'ms_mode'
[  732.486985] ceph: Unknown parameter 'ms-mode'
```

@delorsh can you try adding below to your cephfs storageclass?

```
kernelMountOptions: ms_mode=prefer_crc
```

**Comment by joshperry** [comment]
Can confirm that `kernelMountOptions` works for mounting cephfs with the kernel module. I'm not sure where to change that setting in the codebase to make a patch like @Madhu-1 's

**Comment by zer0def** [comment]
In case anyone else stumbles by this issue and feels that altering the operator's `csi.cephFSKernelMountOptions` is backwards due to a smaller order resource's option (in this case: `CephCluster`'s `.spec.network.(compression|encryption).enabled=true`) warrating this, it should be noted that the built-in [`StorageClass`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#storageclass-v1-storage-k8s-io) resource takes mount options under `.mountOptions` as an array of strings, which ends up comma-joined.

**Comment by parth-gr** [comment]
@zer0def do you feel like this information should be updated in the docs?

**Comment by zer0def** [comment]
@parth-gr I'll refer to #12721 per your remark in [issue 11978's comment](https://github.com/rook/rook/issues/11978#issuecomment-1733129472).

Long story short, one could hypothetically run multiple Ceph clusters on the same Kubernetes cluster, so configuring an upstream component (here: operator) in adherence with downstream resources' expectations feels backwards, while StorageClass is neatly downstream from CephCluster via CephFilesystem.

**Comment by tetofonta** [comment]
HAd a similar problem where I configured the cluster for using osd encryption and network encryption with messenger protocol v1 disabled so messenger  v2 was forced.

Checking dmesg logs appeared the host wasn't connecting to the monitors because V1_BANNER. Resolved by adding 
```
mountOptions: 
  - ms_mode=secure
```
to the storageclass. Thankyou @zer0def for the hint.

**Comment by travisn** [comment]
Instead of in the storage class, you could also set it in the operator settings as seen [here](https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml#L489-L491)
