### ISSUE TITLE
rbd pvc map is failing with the encryption and compression enabled

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#11522]
```
sh-4.4# rbd --id csi-rbd-node -m 172.20.140.187:3300,172.20.104.208:3300,172.20.188.93:3300 --key=AQCqJ71jrg54HRAAde8KRRYjEwwr8xxxdzQ== map ocs-storagecluster-cephblockpool/csi-vol-973c00b8-90c4-11ed-94bc-0a580a83000f --device-type krbd --options noudev               
rbd: failed to get mon address (possible ms_mode mismatch)
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (2) No such file or directory
```

when the `rbd map` is run with `ms_mode=secure` the map succeed

```
sh-4.4# rbd --id csi-rbd-node -m 172.20.140.187:3300,172.20.104.208:3300,172.20.188.93:3300 --key=AQCqJ71jrg54HRAAde8KRRYjEwccccxddzQ/dzQ== map ocs-storagecluster-cephblockpool/csi-vol-973c00b8-90c4-11ed-94bc-0a580a83000f --device-type krbd --options noudev,ms_mode=secure
/dev/rbd0
```

I got to know from @idryomov that we need to set `ms_mode` option on the client side or else this is expected because v1 ports are assumed by default in the kernel client.

We have 2 options like below

* set `ms_mode` in storageclass parameters
* set `ms_mode` in ceph.conf >  this will not work as cephcsi is supposed with work with multiple ceph clusters, 1 cluster might have v1 ports and another cluster might have v2 ports enabled.

Thanks to @idryomov for helping to understand this one.

**Comment by Madhu-1** [comment]
```
sh-4.4$ rbd config global set global rbd_default_map_options ms_mode=secure
sh-4.4$ exit
exit
[🎩︎]mrajanna@fedora ~ $]oc exec -it csi-rbdplugin-9x7fp -c csi-rbdplugin -- sh
sh-4.4# rbd --id csi-rbd-node -m 172.30.140.187:3300,172.30.104.208:3300,172.30.188.93:3300 --key=AQCqJ71jrg54HRAAde8KRRYjEwwr8idpQm/dzQ== map ocs-storagecluster-cephblockpool/csi-vol-973c00b8-90c4-11ed-94bc-0a580a83000f --device-type krbd --options noudev               
/dev/rbd0
sh-4.4# 
```

**Comment by idryomov** [comment]
>     * set `ms_mode` in ceph.conf >  this will not work as cephcsi is supposed with work with multiple ceph clusters, 1 cluster might have v1 ports and another cluster might have v2 ports enabled.

There is `rbd_default_map_options` config option which can be set in global config.  The mapping options in `rbd_default_map_options` get combined with the options specified on the command line.

**Comment by Madhu-1** [comment]
Thanks @idryomov

**Comment by idryomov** [comment]
> There is `rbd_default_map_options` config option which can be set in global config. The mapping options in `rbd_default_map_options` get combined with the options specified on the command line.

Also, in case of conflicts, the options specified on the command line win, which means that the user has the ability to override the global setting via the storageclass.

**Comment by idryomov** [comment]
> sh-4.4# rbd --id csi-rbd-node -m 172.30.140.187:3300,172.30.104.208:3300,172.30.188.93:3300 --key=AQCqJ71jrg54HRAAde8KRRYjEwwr8idpQm/dzQ== map ocs-storagecluster-cephblockpool/csi-vol-973c00b8-90c4-11ed-94bc-0a580a83000f --device-type krbd --options noudev               
> /dev/rbd0

To be give users ability to select between v1 and v2, you would need to pass both v1 and v2 addresses to `rbd map`: `-m [v2:1.2.3.4:3300,v1:1.2.3.4:6789],[v2:5.6.7.8:3300,v1:5.6.7.8:6789],...`

**Comment by Madhu-1** [comment]
> > sh-4.4# rbd --id csi-rbd-node -m 172.30.140.187:3300,172.30.104.208:3300,172.30.188.93:3300 --key=AQCqJ71jrg54HRAAde8KRRYjEwwr8idpQm/dzQ== map ocs-storagecluster-cephblockpool/csi-vol-973c00b8-90c4-11ed-94bc-0a580a83000f --device-type krbd --options noudev
> > /dev/rbd0
> 
> To be give users ability to select between v1 and v2 on the fly, you would need to pass both v1 and v2 addresses to `rbd map`: `-m [v2:1.2.3.4:3300,v1:1.2.3.4:6789],[v2:5.6.7.8:3300,v1:5.6.7.8:6789],...`

Mon IP:port is generated from Rook for csi. When encryption is enabled, only the v2 port is present. Do you mean we should keep both v1 and v2 in monitors for cephcsi and set `ms_mode in global config`?

**Comment by Madhu-1** [comment]
```
sh-4.4$ ceph mon dump
epoch 3
fsid 923d4c68-7810-4e08-b65a-6de422ba4768
last_changed 2023-01-10T08:53:55.552581+0000
created 2023-01-10T08:52:54.331171+0000
min_mon_release 17 (quincy)
election_strategy: 1
0: v2:172.20.14.187:3300/0 mon.a
1: v2:172.20.10.208:3300/0 mon.b
2: v2:172.20.18.93:3300/0 mon.c
dumped monmap epoch 3
```

the mon port is 3300 in ceph mon dump also. just adding v1 and v2 ports to csi commands didn't work.

**Comment by Madhu-1** [comment]
cc @travisn

**Comment by idryomov** [comment]
If `ceph mon dump` lists only v2 ports, it's a v2-only cluster.  Obviously, the user doesn't have a choice in this case.
