### ISSUE TITLE
CephNFS: Active-Active High-Availability NFS Servers with single client endpoint

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#11526]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Active-active HA with CephNFS still has some drawbacks that make use in production challenging, especially during NFS server failure. Ideally, the CephNFS cluster can be accessed via a single endpoint regardless of the number of NFS servers currently active. When an active NFS server fails, we should ensure that a replacement is able to come online quickly, and if it can't, Rook should make sure the overall NFS cluster is still able to serve client requests and ensure clients connected to a downed server are rerouted to an active server.

Important Background:
- the NFS v4.1+ protocols assume that clients always try to connect to the same NFS server once they make an initial successful connection
  - if a client connects to a different server, it must give up its file locks and any in-progress reads/writes
- all NFS servers in the cluster may be unresponsive to client traffic while a peer server is failed and recovering

Initial investigation and planning suggests that HAProxy's sticky sessions can help keep clients connected to a single NFS server after an initial successful connection. 

NFS-Ganesha is working to allow the proxy protocol that will be critical for some clients to connect to Ganesha through a load balancer like HAProxy. https://github.com/nfs-ganesha/nfs-ganesha/issues/879

Unless it's absolutely necessary for Rook to manage HAProxy, we should rely on users to configure the HAProxy server. HAProxy has a very large and complex configuration scope, and there is substantial risk of Rook contending against users to configure HAProxy. Allowing users maximum flexibility also means Rook's complexity can be kept to only what is strictly necessary. In this case, Rook should provide a working example of an HAProxy deployment that follows safe best-practices for users that should be suitable for 80%+ of users who don't need complex HAProxy configurations.

**Comment by BlaineEXE** [comment]
Actually starting to look back at this now

**Comment by visbits** [comment]
This is a really large oversight in ganesha ever being a viable product in a storage solution.

Currently if you don't want security ganesha works, if you want security you can't have high availability.. also a problem.
