### ISSUE TITLE
[Feature Request] Add support for `servicemonitor` in helm chart

### ISSUE THREAD

**Issue by kawhicurry** [rook/rook#11539]
Yes, only `prometheusrules` exists in helm chart.

**Is this a bug report or feature request?**
Feature Request

**What should the feature do:**
Add support for `servicemonitor` in helm chart.

**What is use case behind this feature:**
Install `servicemonitor` when prometheus-operator exists in cluster when installing with helm charts.

**Environment**:

Any

**Comment by sp98** [comment]
I think its up to user requirements as to what monitoring stack resource they want to install with prometheus operator.  Prometheus Operator also provide a [bundle.yaml](https://github.com/prometheus-operator/prometheus-operator/blob/main/bundle.yaml) config to install most of the monitoring stack resource CRDs

**Comment by travisn** [comment]
Rook does create a service monitor if the `monitoring.enabled` is `true` in the CephCluster CR. 
@kawhicurry Do you have [that setting](https://github.com/rook/rook/blob/release-1.10/deploy/charts/rook-ceph-cluster/values.yaml#L44-L47) enabled?

**Comment by kawhicurry** [comment]
@travisn  Yes, it's enabled. But no `servicemonitor` is created in my cluster and I can't find any related sources in helm charts except for a `rolebindings`.

I finally find a `servicemonitor` [here](https://github.com/rook/rook/blob/release-1.10/deploy/examples/monitoring/service-monitor.yaml). It's strange that it's not included in helm charts.

**Comment by sp98** [comment]
@kawhicurry please share the operator logs

**Comment by kawhicurry** [comment]
I think I got the point. I didn't set `monitoring.enabled` to `true` when I'm installing the operator at the first time. I enabled it with `helm upgrade` after I've installed a cluster.

Another point is I mix up the `monitoring.enabled` in both `operator` chart and `cluster` chart.

The operator won't create `serviceMonitor` now. So I have to deploy it manually.

Thanks for help.

**Comment by travisn** [comment]
Oh I should have mentioned you need to set `monitoring.enabled` in both the operator chart and the cluster chart.

**Comment by nathandorsey** [comment]
While I do see the creation of the servicemonitor working, it would be nice to have an option to customize it. For instance, many helm charts include an "additionalLabels" portion in their monitoring sections. In my case, the Prometheus instance will not pick up servicemonitors and rules without the "release" label. So while this helm chart creates the monitor, I still need to edit the manifest afterwards.

```
  labels:
    release: prometheus-stack
```
