### ISSUE TITLE
Must use "tpl" function to render template values

### ISSUE THREAD

**Issue by ldominguezBold** [rook/rook#11530]
Hi, I'm deploying a rook cluster, but i found with an issue that need to redeploy it, using the default configuration, that use `csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"` in some places let unusable the storage class:
![image](https://user-images.githubusercontent.com/121127413/211905053-bedc0973-ff6d-449d-b089-cb4f73cac962.png)
with error on deploying a PVC: `failed to provision volume with StorageClass "ceph-block": "{{ .Release.Namespace }}" is not a valid namespace name` and of course that parameter can't be changed on storageclass, need to be removed.

This is because on helm definition, here: https://github.com/rook/rook/blob/ac7f4c74b51f232b82b83a8a515dfed088dd1167/deploy/charts/rook-ceph-cluster/values.yaml#L461 is defined, even on default value from repository is defined as is. Searching how is defined the cluster i see that to include the storage definition you are using the `toYaml` here https://github.com/rook/rook/blob/ac7f4c74b51f232b82b83a8a515dfed088dd1167/deploy/charts/rook-ceph-cluster/templates/cephcluster.yaml#L19, but must be used the `tpl` function to get that template String replaced.

**Comment by travisn** [comment]
You must be using the wrong values.yaml. The `tpl` was added to the template yesterday with #11517 and backported to the 1.10 branch. The new helm chart is planned to be released tomorrow for v1.10.9. Until then, make sure you're using the correct version of the values.yaml that does not use the template such as https://github.com/rook/rook/blob/v1.10.8/deploy/charts/rook-ceph-cluster/values.yaml.

**Comment by ldominguezBold** [comment]
That was the issue, thanks.
