### ISSUE TITLE
dashboard Object gateway doesn't show

### ISSUE THREAD

**Issue by liu1032015185** [rook/rook#11545]
On dashboard,when I click Object gateway, Page not found.
500 - Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
vim 
In toolbox, when I input "radosgw-admin user info --uid=my-user"， Program stucked, no output

my cluster.yaml 's  network is like this:
  provider: multus
    selectors:
      public: default/rook-public-nw
      cluster: default/rook-cluster-nw

I don't know if it is related to it.

**Comment by parth-gr** [comment]
is the ceph cluster healthy?
Can you please share the operator logs
