### ISSUE TITLE
PVC mounts fail in v1.10.9 clusters when encryption is not enabled and kernel is older

### ISSUE THREAD

**Issue by voarsh2** [rook/rook#11541]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
I was able to mount PVC's with this new EC pool, but it now seems I can't with all PVC's I have. 

**How to reproduce it (minimal and precise):**

Make the following:
[https://github.com/rook/rook/blob/master/deploy/examples/csi/rbd/storageclass-ec.yaml
https://github.com/rook/rook/blob/master/deploy/examples/pool-ec.yaml](https://github.com/rook/rook/blob/master/deploy/examples/csi/rbd/storageclass-ec.yaml)

**Logs to submit**:

Pod logs:

```
MountVolume.MountDevice failed for volume "pvc-9fda23c7-6ed9-4287-b04c-2cee7cd20a34" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.43.112.135:6789,10.43.80.29:6789,10.43.48.191:6789,10.43.136.249:6789,10.43.74.119:6789 --keyfile=***stripped*** map replicapool/csi-vol-c84112c7-943a-11ed-8dae-6edda849eb24 --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed rbd: map failed: (22) Invalid argument
```

* Operator's logs, if necessary
````

2023-01-15 12:29:56.339869 E \| ceph-block-pool-controller: failed to reconcile CephBlockPool "rook-ceph/ec-data-pool". failed to create pool "ec-data-pool".: failed to create pool "ec-data-pool".: failed to create pool "ec-data-pool": failed to create erasure code profile for pool "ec-data-pool": failed to look up default erasure code profile: failed to get erasure-code-profile for "default": exit status 1
--
Sun, Jan 15 2023 12:29:57 pm | 2023-01-15 12:29:57.318449 E \| ceph-block-pool-controller: failed to reconcile CephBlockPool "rook-ceph/replicated-metadata-pool". failed to create pool "replicated-metadata-pool".: failed to create pool "replicated-metadata-pool".: failed to create pool "replicated-metadata-pool": failed to create replicated crush rule "replicated-metadata-pool": failed to create crush rule replicated-metadata-pool: exit status 1
Sun, Jan 15 2023 12:29:58 pm | 2023-01-15 12:29:58.530240 E \| ceph-block-pool-controller: failed to reconcile CephBlockPool "rook-ceph/ec-data-pool". failed to create pool "ec-data-pool".: failed to create pool "ec-data-pool".: failed to create pool "ec-data-pool": failed to create erasure code profile for pool "ec-data-pool": failed to look up default erasure code profile: failed to get erasure-code-profile for "default": exit status 1
```


**Cluster Status to submit**:
```
  cluster:
    id:     cb794671-ea06-4e89-8661-ce00ba0134d5
    health: HEALTH_WARN
            clock skew detected on mon.bl
            mon bc is low on available space
            40 daemons have recently crashed
            2 mgr modules have recently crashed
 
  services:
    mon: 5 daemons, quorum ay,bc,bf,bg,bl (age 2h)
    mgr: b(active, since 50m), standbys: a
    mds: 2/2 daemons up, 2 hot standby
    osd: 6 osds: 6 up (since 35m), 6 in (since 17h); 13 remapped pgs
 
  data:
    volumes: 2/2 healthy
    pools:   11 pools, 88 pgs
    objects: 3.87M objects, 984 GiB
    usage:   2.8 TiB used, 2.5 TiB / 5.3 TiB avail
    pgs:     603009/11623113 objects misplaced (5.188%)
             75 active+clean
             11 active+remapped+backfilling
             2  active+clean+remapped
 
  io:
    client:   1.6 MiB/s rd, 2.7 MiB/s wr, 620 op/s rd, 172 op/s wr
    recovery: 848 KiB/s, 14 objects/s
 
  progress:
    Global Recovery Event (45m)
      [========================....] (remaining: 6m)
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 21
* Kernel (e.g. `uname -a`): 20.04.1-Ubuntu
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.10.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.1 (ec95624474b1871a821a912b8c3af68f8f8e7aa1) quincy (stable)
* Kubernetes version (use `kubectl version`): 1.23
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE 1
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_WARN clock skew detected on mon.bl; mon bc is low on available space; 40 daemons have recently crashed; 2 mgr modules have recently crashed

**Comment by voarsh2** [comment]
I am seeing this though:






```
2023-01-15 16:42:24.522640 I \| ceph-block-pool-controller: creating pool "replicated-metadata-pool" in namespace "rook-ceph"
--
Sun, Jan 15 2023 4:42:25 pm | 2023-01-15 16:42:25.453645 E \| ceph-block-pool-controller: failed to reconcile CephBlockPool "rook-ceph/replicated-metadata-pool". failed to create pool "replicated-metadata-pool".: failed to create pool "replicated-metadata-pool".: failed to create pool "replicated-metadata-pool": failed to create replicated crush rule "replicated-metadata-pool": failed to create crush rule replicated-metadata-pool: exit status 1
Sun, Jan 15 2023 4:42:25 pm | 2023-01-15 16:42:25.515424 I \| ceph-block-pool-controller: creating pool "ec-data-pool" in namespace "rook-ceph"
Sun, Jan 15 2023 4:42:26 pm | 2023-01-15 16:42:26.434179 E \| ceph-block-pool-controller: failed to reconcile CephBlockPool "rook-ceph/ec-data-pool". failed to create pool "ec-data-pool".: failed to create pool "ec-data-pool".: failed to create pool "ec-data-pool": failed to create erasure code profile for pool "ec-data-pool": failed to look up default erasure code profile: failed to get erasure-code-profile for "default": exit status 1
Sun, Jan 15 2023 4:42:26 pm | 2023-01-15 16:42:26.458534 I \| ceph-block-pool-controller: creating pool "replicated-metadata-pool" in namespace "rook-ceph"
Sun, Jan 15 2023 4:42:43 pm | 2023-01-15 16:42:43.612790 I \| ceph-block-pool-controller: initializing pool "replicated-metadata-pool" for RBD use
Sun, Jan 15 2023 4:42:45 pm | 2023-01-15 16:42:45.008935 I \| ceph-block-pool-controller: successfully initialized pool "replicated-metadata-pool" for RBD use
Sun, Jan 15 2023 4:42:55 pm | 2023-01-15 16:42:55.908134 I \| ceph-block-pool-controller: creating pool "ec-data-pool" in namespace "rook-ceph"
Sun, Jan 15 2023 4:43:33 pm | 2023-01-15 16:43:33.904850 I \| ceph-block-pool-controller: initializing pool "ec-data-pool" for RBD use
Sun, Jan 15 2023 4:43:36 pm | 2023-01-15 16:43:36.204385 I \| ceph-block-pool-controller: successfully initialized pool "ec-data-pool" for RBD use
Sun, Jan 15 2023 4:43:52 pm | 2023-01-15 16:43:52.809503 I \| ceph-block-pool-controller: creating pool "replicapool" in namespace "rook-ceph"
Sun, Jan 15 2023 4:44:24 pm | 2023-01-15 16:44:24.505594 I \| ceph-block-pool-controller: initializing pool "replicapool" for RBD use
Sun, Jan 15 2023 4:44:25 pm | 2023-01-15 16:44:25.716398 I \| ceph-block-pool-controller: successfully initialized pool "replicapool" for RBD use
```

But I am not able to mount volumes or mount cloned volumes......

**Comment by voarsh2** [comment]
I am also seeing this problem for PVC's that have nothing to do with with new EC Pool...

**Comment by cayla** [comment]
Ahha

> It's strange, I redeployed it on a different node and it didn't throw any error.
They had differing kernel's:
Working one: Linux worker2 5.11.0-49-generic https://github.com/rook/rook/issues/55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Non-working: Linux worker1 5.4.0-136-generic https://github.com/rook/rook/pull/153-Ubuntu SMP Thu Nov 24 15:56:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Thanks for confirming the theory I am working on right now.

I had the same issue as you after upgrading from 1.9.10 to 1.10.9.

I suspect it was https://github.com/rook/rook/pull/11523

I was digging around and saw this comment: 

https://github.com/rook/rook/blob/ae408e354443ab8af9ade5768371e7ac82c1233c/deploy/examples/cluster.yaml#L78-L86

Even though encryption isn't enabled by default, I think this is now a hard requirement.

I am installing `linux-generic-hwe-20.04` on my nodes and rebooting to confirm it fixes the issue, but your comment gives me a lot of hope.

FWIW, this was my debugging path:

New PVCs were failing to mount.  Existing, mounted PVCs were fine.

New pods showed the following event:

```
MountVolume.MountDevice failed for volume "pvc-8c3d89f2-577d-41fd-a812-45bcbfa321de" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.108.70.247:6789,10.107.78.45:6789,10.103.81.145:6789 --keyfile=***stripped*** map replicapool/csi-vol-ff706135-94ec-11ed-aec5-5607db29eeaf --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
```

This was echo'd in the `csi-rbdplugin`:

```
Warning  FailedMount             13s (x6 over 30s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-8c3d89f2-577d-41fd-a812-45bcbfa321de" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.103.81.145:6789,10.108.70.247:6789,10.107.78.45:6789 --keyfile=***strip
ped*** map replicapool/csi-vol-ff706135-94ec-11ed-aec5-5607db29eeaf --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
```

`dmesg` on the node showed:

```
ibceph: bad option at 'ms_mode=prefer-crc'
```

Googling for that led to me to the aforementioned merged PR.

I was trying to reckon how this config passed down and saw:

```
bash-4.4$ ceph config dump | grep crc
global                basic     ms_client_mode                         crc secure          *
global                basic     ms_cluster_mode                        crc secure          *
global                basic     ms_service_mode                        crc secure          *
global                advanced  rbd_default_map_options                ms_mode=prefer-crc  *
bash-4.4$
``` 

and finally made my way back to the `cluster.yaml` where I saw the comment about the kernel version and inspiration struck.

I am not a rook or ceph expert by any means, but writing it all out here for anyone else that stumbles on this.

**Comment by voarsh2** [comment]
Thanks for your comment!
I will need to check back on this later on today, eager to see what your results are, and if it is indeed an outdated kernel issue.

**Comment by voarsh2** [comment]
Did you get any issue from the Rook Operator about failing to reconcile the erasure-code-profile stuff?

**Comment by cayla** [comment]
I am not using EC, so yeah, it being multiple issues is a distinct possibility.

**Comment by cayla** [comment]
I noted it in an edit above, but in case it was missed, upgrading the kernel to 5.11+ completely resolved my issues.  I have a fat and happy ceph cluster once again.

**Comment by voarsh2** [comment]
> I noted it in an edit above, but in case it was missed, upgrading the kernel to 5.11+ completely resolved my issues. I have a fat and happy ceph cluster once again.

Great to hear. :)
I will be either installing that dependency or upgrading kernel (bigger undertaking ATM). I am hoping someone can chime in about the Rook Operating errors regarding my EC pool that isn't reconciling..... :D

**Comment by cayla** [comment]
@Madhu-1 I don’t know what to say. Encryption has never been enabled on this cluster. In fact, we barely deviate from the defaults. Some resource blocks, some bits about discovery, monitoring, and not much else.

**Comment by voarsh2** [comment]
> @Madhu-1 I don’t know what to say. Encryption has never been enabled on this cluster yet that config was set. In fact, we barely deviate from the defaults. Some resource blocks, some bits about discovery, monitoring, and not much else.

Have to agree on this one - I do not have encryption on, and this error with an older kernel only cropped up with 10.8.9 Rook Ceph update

**Comment by voarsh2** [comment]
> @voarsh2 I think ec pool was created successfully after sometime in your cluster. You can execute ceph commands and verify. for rbd map, failure upgrading the kernel might be required. check `dmesg` logs for more details.

Yes, it is there and I am using it, but I don't like the fact that the Rook Operator complains that it can't reconcile the settings, so to speak. Makes me worried for updates........ When I look at the Pool in Ceph Dashboard, I can see the default profile just fine.......

**Comment by voarsh2** [comment]
> > I noted it in an edit above, but in case it was missed, upgrading the kernel to 5.11+ completely resolved my issues. I have a fat and happy ceph cluster once again.
> 
> Great to hear. :) I will be either installing that dependency or upgrading kernel (bigger undertaking ATM). I am hoping someone can chime in about the Rook Operating errors regarding my EC pool that isn't reconciling..... :D

Can confirm the issue around mounting was resolved with installing the linux-generic-hwe-20.04 dependency... :)

**Comment by Rakshith-R** [comment]
> @cayla, the above default rbd map option `ms_mode=prefer-crc` will be set only if you have encryption enabled, not for normal clusters.

@Madhu-1 , I think the code at line 605 below is not checking `.Enabled` settings but existence of `c.Spec.Network.Connections.Encryption` setting. 

@travisn is the the intention to enable this by default and have users remove `c.Spec.Network.Connections.Encryption` setting if not required ?

https://github.com/rook/rook/blob/91beb549be3720a1278c3b5c67934f46555e1db5/pkg/operator/ceph/cluster/cluster.go#L605-L625

**Comment by travisn** [comment]
@Rakshith-R Agreed that you've identified the issue. Due to that setting not being available in older kernels, we should not set that if encryption is not enabled. However, if encryption had been enabled and now is being disabled, rook should remove that setting from the mon store. So it seems that if encryption is not enabled, rook needs to query the mon store to see if it was set and needs to be disabled.

**Comment by travisn** [comment]
And I'd suggest we get a fix in for this soon and get a new release out.

**Comment by bauerjs1** [comment]
> @Rakshith-R Agreed that you've identified the issue. Due to that setting not being available in older kernels, we should not set that if encryption is not enabled. However, if encryption had been enabled and now is being disabled, rook should remove that setting from the mon store. So it seems that if encryption is not enabled, rook needs to query the mon store to see if it was set and needs to be disabled.

@travisn I still had the exact same issue with `rook/ceph:v1.12.9` on a fresh cluster and updated the Linux kernel to resolve.

Context: When using the `rook-ceph-cluster` Helm chart, encryption is disabled by default by setting
```yaml
kind: CephCluster
spec:
  network:
    connections:
      encryption:
        enabled: false
```
so the `spec.network.connections.encryption` section is always present.

**Comment by travisn** [comment]
@bauerjs1 What type of volume were you creating? If a cephfs volume, make sure you have enabled the [cephfs kernel mount options](https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml#L486-L488).

**Comment by bauerjs1** [comment]
@travisn yes for `cephfs` I needed the kernel mount options, but this particular issue came up when I tested `ceph-block`/RBD volumes.
