### ISSUE TITLE
How to set up multiple networks

### ISSUE THREAD

**Issue by liu1032015185** [rook/rook#11552]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

-----------------

Hi all,
my server ip is eth0:10.110.199.0/24    eth1:192.168.1.0/24
my pod ip is 10.233.0.0/32

```
vim cluster.yaml
  provider: multus
    selectors:
      public: default/rook-public-nw
      cluster: default/rook-cluster-nw


my rook-cluster-nw conf is like this
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: rook-cluster-nw
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "cluster-nad",
      "type": "macvlan",
      "master": "eth1",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.233.0.0/24"
      }
    }'

my rook-public-nw is like this
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: rook-public-nw
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "public-nad",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.110.0.0/24"
      }
    }'

```

**Is my profile written correctly？**
and my rgw doesn't work correctly,Thanks

**Comment by BlaineEXE** [comment]
It seems like you may be configuring rook-cluster-nw to overlap with your pod overlay network. I'm not sure that would cause an RGW issue, but that could be an issue. Otherwise, that config 

Also, we will need more information about how the RGW is not working correctly to debug.

**Comment by liu1032015185** [comment]
Can you provide correct examples? I can't find complete examples on the official website. Thanks!

**Comment by BlaineEXE** [comment]
When you filed an issue, you should have seen an issue template, which it seems you deleted. The issue template explains which files and logs we usually request for debugging issues. In addition to the normal ones, a `kubectl describe` of the RGW pod and `kubectl logs` from the RGW pod will be helpful here.

**Comment by liu1032015185** [comment]
I just want to know how to configure dual(public and cluster) networks in rook-ceph. I can't find complete examples on the rook-ceph official website. how to write rook-public-nw and rook-cluster-nw, Especially **"range"** and **"macvlan or ipvlan"**
my server ip is eth0:10.110.199.0/24 eth1:192.168.1.0/24
my pod ip is 10.233.0.0/32   **how to write range in rook-public-nw.yaml and rook-cluster-nw.yaml**

I have deleted the cluster because it cannot work, so So I can't provide logs. Here is my environment information

Environment:

OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Kernel (e.g. uname -a): Linux master1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Rook version (use rook version inside of a Rook Pod): 1.9.2
Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}


Thanks!

**Comment by BlaineEXE** [comment]
You config looks correct to me, but this is really more about how multus is configured and less about how Rook is configured.

This explains in more detail how macvlan is configured in multus: https://docs.openshift.com/container-platform/4.5/networking/multiple_networks/configuring-macvlan.html
