### ISSUE TITLE
Ceph CSI is not cleaning up the storage even after deleting PVCs

### ISSUE THREAD

**Issue by nirav-chotai** [rook/rook#11562]
We are using Ceph with Rook to provide block storage and file storage to the applications running on K8s.

Here is current status:
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph -s
  cluster:
    id:     c40d82d5-3193-457d-a628-a3db67839a37
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum g,j,l (age 9d)
    mgr: a(active, since 20m)
    osd: 10 osds: 10 up (since 2w), 10 in (since 2w)
 
  data:
    pools:   4 pools, 193 pgs
    objects: 8.28M objects, 31 TiB
    usage:   94 TiB used, 33 TiB / 127 TiB avail
    pgs:     193 active+clean
 
  io:
    client:   1.7 KiB/s rd, 10 MiB/s wr, 0 op/s rd, 161 op/s wr
 
[root@rook-ceph-tools-68958dbb7f-klmcn /]# 
```

Even if I sum up, then all the applications are using only 4 TB, i.e. 4 TB x 3 = 12 TB at max.
This is evident that after deletion of PVCs, storage is not removed from Ceph RBD Cluster. 
Upon further research, I find that there are no `discard` `mountOptions` given to the Storage Class
```
 ~/ kubectl describe sc rook-ceph-block                                                                                                   
Name:                  rook-ceph-block
IsDefaultClass:        No
Annotations:           meta.helm.sh/release-name=rook-ceph-cluster,meta.helm.sh/release-namespace=rook-ceph
Provisioner:           rook-ceph.rbd.csi.ceph.com
Parameters:            clusterID=rook-ceph,csi.storage.k8s.io/controller-expand-secret-name=rook-csi-rbd-provisioner,csi.storage.k8s.io/controller-expand-secret-namespace=rook-ceph,csi.storage.k8s.io/fstype=ext4,csi.storage.k8s.io/node-stage-secret-name=rook-csi-rbd-node,csi.storage.k8s.io/node-stage-secret-namespace=rook-ceph,csi.storage.k8s.io/provisioner-secret-name=rook-csi-rbd-provisioner,csi.storage.k8s.io/provisioner-secret-namespace=rook-ceph,imageFeatures=layering,imageFormat=2,pool=replicapool
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
 ~/ 
```
Current Versions:
- Rook: v1.4.3
- Ceph: 15.2.4
- cephcsi:v3.1.0
- csi-attacher:v2.1.0
- csi-node-driver-registrar:v2.0.1
- csi-provisioner:v1.6.0
- csi-resizer:v0.4.0
- csi-snapshotter:v2.1.1

If we edit storage class and add `discard` `mountOptions`, then will that automatically take care of all previous PVCs and cleanup the storage, or will have only effect on any new PVCs going to be created in future after this change?

And most important, how to cleanup the storage in this current environment? What are the best ways to handle the storage?

**Comment by Madhu-1** [comment]
@nirav-chotai, the above is the behavior of the rbd pvc. You can find some details here: https://github.com/rook/rook/issues/3832. You can use the discard mount option or reclaimspace jobs to reclaim the space.

Discard mount option is only applicable for the PVC created after adding the discard mount options to the storageclass. If the PVC and PV are deleted, the storage space should get recovered automatically because the rbd image in the backend will get deleted. 

As you are on the old version of Rook, I am not sure if you are hitting any known ceph bugs.

**Comment by Madhu-1** [comment]
@nirav-chotai, you can do it or you can delete it and recreate this storageclass with the discard mount option. Make sure adding the discard mount option doesn't cause any performance issues

**Comment by Madhu-1** [comment]
Yes, that is the one I am referring to, cephcsi v3.5 is deprecated, and only 3.6 and 3.7 is supported. AFAIK we never tested with Kubernetes 1.18, please test it out and see if it works.
