### ISSUE TITLE
Move "How to run tests" instructions to developer 

### ISSUE THREAD

**Issue by galexrt** [rook/rook#11574]
**Is this a bug report or feature request?**
* Feature Request

**What should the change do:**

Let's move the "test framework" instructions to the "contributing" docs section.
https://github.com/rook/rook/blob/master/tests/README.md

I think adding a link or even the contents of that README.md to the https://rook.io/docs/rook/v1.10/Contributing/development-flow/ would make sense.

Any input?

**What is use case behind this feature:**

Making it easier for new comers to find the info on how to test, e.g., new changes.

**Comment by travisn** [comment]
Sounds good to move that page to a new test page in the docs. 
- @jmolmo How about adding the changes to #11573 in a new test doc? That PR could be updated after the new doc is created for this issue.
- The content of the test readme focuses a lot on how to run the smoke suite locally, so we should make some updates at the same time. The more effective approach now with the github actions is to just open a PR and then ssh to the action if it fails. You just have to pay attention and ssh within an hour of the failure.

**Comment by divaspathak** [comment]
I want to work on this issue. Can you please assign it to me?

**Comment by travisn** [comment]
> I want to work on this issue. Can you please assign it to me?

@galexrt Were you planning on working on this? If not, @divaspathak see [here](https://rook.io/docs/rook/latest/Contributing/development-flow/#self-assign-issue) on self-assigning.

**Comment by galexrt** [comment]
> > I want to work on this issue. Can you please assign it to me?
> 
> @galexrt Were you planning on working on this? If not, @divaspathak see [here](https://rook.io/docs/rook/latest/Contributing/development-flow/#self-assign-issue) on self-assigning.

I'm fine with someone else working on this. @divaspathak feel free to take care of these docs changes, thanks!
