### ISSUE TITLE
Update CNCF Landcape Summary Table with Rook details

### ISSUE THREAD

**Issue by siforster** [rook/rook#11599]
Hi All,

The CNCF Business Value Subcommittee has developed a project summary table to supplement the CNCF Landscape and include further information about CNCF projects for the wider cloud native community. We would like to request the Rook project submit a PR to the CNCF Landscape repository with additional details that will help further inform the community about your project and its use cases through the popular landscape and this new addition.

The table is located here: https://landscape.cncf.io/summary
There are directions located here: https://github.com/cncf/landscape/blob/master/readme_summary.md

Many thanks for this - we hope it will help further get the word out about your project.

Simon Forster
CNCF Business Value Subcomittee

**Comment by subhamkrai** [comment]
@travisn @BlaineEXE @galexrt @satoru-takeuchi ^^

**Comment by galexrt** [comment]
So we need to fill out these fields: https://github.com/cncf/landscape/blob/master/readme_summary.md#fields-to-be-populated-by-project-owners

If someone can help write and proof read the "business use" and "Use case", I can gladly take care of it.

In addition to that I think it makes sense to present the use case, descriptions, etc., at an upcoming community meeting to get community feedback on them.

**Comment by BlaineEXE** [comment]
I'm happy to discuss what @galexrt proposes, and I think a community meeting forum sounds good. Thanks!

**Comment by galexrt** [comment]
I'm going to update this comment continuously, just putting up my first rough notes already. If you have any thoughts on what should be added/modified/removed feel free to comment here.

*** 

**Fields**:

* Target Users: SRE/ DevOps Engineers
* Tags: Storage, Persistence, CSI, Operator, Kubernetes
* Use case:
	* Running Storage in Kubernetes next to applications (hyper converged).
	* Providing storage for environments such as bare metal when there is no existing storage provider.
	* ...
* Business use:
	* Ease of deploying and running storage where it is needed.
	* Dynamic provisioning reduces time for developers and engineers to run persistent applications in Kubernetes.
	* ...
* Release cadence: Every second Quarter (or every other KubeCon? :wink:)
* Integrations: Rook integrates with Kubernetes using CSI (Container Storage Interface).
* Overview video: I'll look into scribbling up a short video idea and will present it.

**Comment by travisn** [comment]
@galexrt Thanks for getting this started. A few thoughts to add:
- Use case:
   - Consistent storage platform anywhere K8s runs, whether on-premise or in the cloud
   - Overcome limitations of cloud storage providers
- Release cadence: Minor releases are approximately three times a year (similar to K8s cadence), with patch releases bi-weekly
- Integrations: Is there more detail about what integrations? Perhaps we add a statement about Rook providing an operator and CRDs.
- Overview video: There are numerous videos out there we have recorded for kubecon, or other short intros. Should we just link one of those, or you want to create a new one?

**Comment by galexrt** [comment]
@travisn 

* Use case: Thanks I added them to list!
* Release cadence: Updated as well.
* Integrations: CNCF project summary table readme[^1] there isn't too much info on what it should contain, maybe @siforster can give use some more info what this should contain.
* Overview video: I think creating a new one makes sense here in the form of a "5 min product pitch" (idea taken from the readme[^1]) to have a short and concise "This is what Rook is and can do to make your life easier".

I'll try to collect some more use and business cases/uses in today's huddle and start formulating some paragraphs then.

[^1]: https://github.com/cncf/landscape/blob/master/readme_summary.md#fields-to-be-populated-by-project-owners

**Comment by siforster** [comment]
Hi @galexrt and @travisn,
Sorry, I missed this comment and apologise for this.
With integrations, consider what technologies you integrate with, particularly those that might be well known to readers of the table.  Taking a close look at the table, you'll see that TUF, SPIFFE, Falco and WasmEdge have put in some technologies.  Perhaps consider those that may help a practitioner gain a better understanding of where Rook might fit in in say the technology stack.
Thank you for the feedback re the readme and the lack of detail re integrations.  I'll feed this back to the group for an update.

**Comment by galexrt** [comment]
This would be my final draft for the summary fields:

* Target Users: `SRE/ DevOps Engineers`
* Tags (split by comma): `Storage, Persistence, Data, CSI, Operator, Kubernetes`
* Use case: heavily based on the Rook docs getting started intro line
	```
    Rook is an open source cloud-native storage orchestrator, providing the platform, framework, and support for Ceph storage to integrate with cloud-native environments natively.
	Ceph is a distributed storage system that provides block, file, and object storage and is deployed in large-scale production clusters.
	Rook automates deployment and management of Ceph to provide self-managing, self-scaling, and self-healing storage services. The Rook operator builds on Kubernetes resources to deploy, configure, provision, scale, upgrade, and monitor Ceph.
	The storage cluster can be run hyper-converged beside your applications, in a cloud, or on bare metal. Rook provides a consistent storage platform anywhere Kubernetes runs.
	```
* Business use case:
	```
	Rook provides a consistent storage platform, whether in the cloud or on bare metal. The storage cluster is managed through Kubernetes Custom Resources, making integrating with your existing DevOps/ GitOps toolset easy.
	For your applications to consume storage, they simply need to use the Kubernetes native approach of creating a `PersistentVolumeClaim`.
	Running a Rook Ceph cluster is made accessible due to the operator pattern.
	The operator pattern allows the Rook project to handle most tasks automatically (e.g., updating to a new Ceph version). These automatic processes reduce the time spent setting up, configuring, maintaining, and updating your Rook storage cluster.
	```
* Release Rate: `Minor releases: approximately three times a year (similar to Kubernetes cadence), Patch releases: bi-weekly`
* Integration: `CSI (Container Storage Interface) Integration, Helm Chart, Prometheus
* Overview Video Url: Let's add this later when we have a good short overview video ready (still polishing my idea).

Please let me know any feedback, before I'll look into adding this info to the Rook CNCF project summary field.

**Comment by galexrt** [comment]
Resolved by https://github.com/cncf/landscape/pull/3070.
