### ISSUE TITLE
Ceph PG repair stuck forever

### ISSUE THREAD

**Issue by nirav-chotai** [rook/rook#11591]
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph -s
  cluster:
    id:     c40d82d5-3193-457d-a628-a3db67839a37
    health: HEALTH_ERR
            1 scrub errors
            Possible data damage: 1 pg inconsistent
 
  services:
    mon: 3 daemons, quorum g,j,l (age 2w)
    mgr: a(active, since 10m)
    osd: 10 osds: 10 up (since 17h), 10 in (since 3w)
 
  data:
    pools:   4 pools, 193 pgs
    objects: 8.31M objects, 32 TiB
    usage:   95 TiB used, 33 TiB / 127 TiB avail
    pgs:     192 active+clean
             1   active+clean+scrubbing+deep+inconsistent+repair
 
  io:
    client:   682 B/s rd, 6.9 MiB/s wr, 0 op/s rd, 162 op/s wr
```
and
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph health detail
HEALTH_ERR 1 scrub errors; Possible data damage: 1 pg inconsistent
[ERR] OSD_SCRUB_ERRORS: 1 scrub errors
[ERR] PG_DAMAGED: Possible data damage: 1 pg inconsistent
    pg 1.50 is active+clean+scrubbing+deep+inconsistent+repair, acting [5,17,2]
[root@rook-ceph-tools-68958dbb7f-klmcn /]# 
```
and
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph pg deep-scrub 1.50
instructing pg 1.50 on osd.5 to deep-scrub
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph pg repair 1.50
instructing pg 1.50 on osd.5 to repair
[root@rook-ceph-tools-68958dbb7f-klmcn /]# 
```
and
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph pg dump_stuck unclean
ok
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph pg dump_stuck stale
ok
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph pg dump_stuck inactive
ok
[root@rook-ceph-tools-68958dbb7f-klmcn /]# 
```
and
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# rados list-inconsistent-obj 1.50 --format=json-pretty
{
    "epoch": 667024,
    "inconsistents": []
}
[root@rook-ceph-tools-68958dbb7f-klmcn /]# 
```
Still, it's been more than 3 days, status is the same.
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph -s
  cluster:
    id:     c40d82d5-3193-457d-a628-a3db67839a37
    health: HEALTH_ERR
            1 scrub errors
            Possible data damage: 1 pg inconsistent
```
and still the same PG is in question
```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph health detail
HEALTH_ERR 1 scrub errors; Possible data damage: 1 pg inconsistent
[ERR] OSD_SCRUB_ERRORS: 1 scrub errors
[ERR] PG_DAMAGED: Possible data damage: 1 pg inconsistent
    pg 1.50 is active+clean+scrubbing+deep+inconsistent+repair, acting [5,17,2]
```
Restarting all the OSDs and underlying nodes is also not helping.

**Comment by sp98** [comment]
A couple of thoughts:
- Check the OSD logs (with debug_osd = 20) to get more details of the error if any.
- There are chances that underlying hard drives are failing. If that's the case then osds need to be removed from the cluster and replaced with new device.

**Comment by nirav-chotai** [comment]
@sp98 , checked logs on all OSDs, there are no errors. 
It seems something is happening, but might be happening at very slower speed.
What troubles is that there are no inconsistent objects for the PG, but still something is going on, keeping cluster in error state. Checked logs even after restarting OSDs, but no errors. 

Initially I thought about the same, where it will be failing drive, but all OSDs are up.
And I also validated same after reboot the underlying servers, and everything come up online without any errors.
However, that doesn't change the cluster status, and it is in error state.

**Comment by sp98** [comment]
@nirav-chotai can you share the osd.5 logs with debug_osd = 20.

**Comment by nirav-chotai** [comment]
[osd-5-and-7-logs.zip](https://github.com/rook/rook/files/10533735/osd-5-and-7-logs.zip)

@sp98 , attaching osd 5 and 7 logs, as cluster status is the same error, but PG and OSD details are changed
```
ceph health detail
HEALTH_ERR 1 scrub errors; Possible data damage: 1 pg inconsistent
[ERR] OSD_SCRUB_ERRORS: 1 scrub errors
[ERR] PG_DAMAGED: Possible data damage: 1 pg inconsistent
    pg 1.27 is active+clean+inconsistent, acting [7,2,16]
```
hence did the following
```
ceph pg repair 1.27
instructing pg 1.27 on osd.7 to repair
```

and this time, I found below error
```
debug 2023-01-30T05:58:28.680+0000 7f2493336700 -1 log_channel(cluster) log [ERR] : 1.27 shard 2 soid 1:e5e810cd:::rbd_data.aa3e56e02ae3bb.00000000001f4b91:head : candidate had a read error
```

**Comment by nirav-chotai** [comment]
@sp98 , and one more thing, is it possible to run specific OSD with debug_osd = 20?
I'm using Rook/Ceph on K8s, so I know about using `rook-config-override` ConfigMap but that will apply at cluster i.e. global level, right?

```
[osd]
        debug_osd = 20
```

**Comment by sp98** [comment]
> [osd-5-and-7-logs.zip](https://github.com/rook/rook/files/10533735/osd-5-and-7-logs.zip)
> 
> @sp98 , attaching osd 5 and 7 logs, as cluster status is the same error, but PG and OSD details are changed
> 
> ```
> ceph health detail
> HEALTH_ERR 1 scrub errors; Possible data damage: 1 pg inconsistent
> [ERR] OSD_SCRUB_ERRORS: 1 scrub errors
> [ERR] PG_DAMAGED: Possible data damage: 1 pg inconsistent
>     pg 1.27 is active+clean+inconsistent, acting [7,2,16]
> ```
> 
> hence did the following
> 
> ```
> ceph pg repair 1.27
> instructing pg 1.27 on osd.7 to repair
> ```

After running above command, can you try running `ceph -w | grep 1.27` and see if there any useful errors to encounter.
> 
> and
> 
> ```
> [root@rook-ceph-tools-68958dbb7f-klmcn /]# rados list-inconsistent-obj 1.27 --format=json-pretty
> {
>     "epoch": 666776,
>     "inconsistents": []
> }

This is strange that it shows no inconsistents. 

> [root@rook-ceph-tools-68958dbb7f-klmcn /]# 
> ```
> 
> and this time, I found below error
> 
> ```
> debug 2023-01-30T05:58:28.680+0000 7f2493336700 -1 log_channel(cluster) log [ERR] : 1.27 shard 2 soid 1:e5e810cd:::rbd_data.aa3e56e02ae3bb.00000000001f4b91:head : candidate had a read error
> ```

That's the error I see as well for pg 1.50 for OSD.5
```debug 2023-01-29T19:57:27.900+0000 7f9f4009b700 -1 log_channel(cluster) log [ERR] : 1.50 shard 2 soid 1:0b4adc11:::rbd_data.aa3e56b4760f2.00000000001607ec:head : candidate had a read error```

**Comment by harsh-p-soni** [comment]
@sp98 I tried as per your instruction but have not got anything
<img width="833" alt="Screenshot 2023-01-30 at 2 43 45 PM" src="https://user-images.githubusercontent.com/39649076/215435493-1474ea6e-d355-41b6-9bfb-9c8d5c51d646.png">

**Comment by sp98** [comment]
> @sp98 I tried as per your instruction but have not got anything <img alt="Screenshot 2023-01-30 at 2 43 45 PM" width="833" src="https://user-images.githubusercontent.com/39649076/215435493-1474ea6e-d355-41b6-9bfb-9c8d5c51d646.png">

@nirav-chotai  ok . A couple of things I can suggest at this point is: 
1. Remove the pg from the osd manually. 
2. Open an issue in  https://tracker.ceph.com/ and see what ceph team can suggest.

**Comment by nirav-chotai** [comment]
@sp98 , how to remove pg from the osd manually?

**Comment by nirav-chotai** [comment]
> @sp98 , and one more thing, is it possible to run specific OSD with debug_osd = 20? I'm using Rook/Ceph on K8s, so I know about using `rook-config-override` ConfigMap but that will apply at cluster i.e. global level, right?
> 
> ```
> [osd]
>         debug_osd = 20
> ```

and any comment for this? it will help for any further debugging.

**Comment by sp98** [comment]
> @sp98 , how to remove pg from the osd manually?
I'm checking with someone about the correct diagnostic step that can be taken. I'll get back to you as soon as I can.

**Comment by sp98** [comment]
> > @sp98 I tried as per your instruction but have not got anything <img alt="Screenshot 2023-01-30 at 2 43 45 PM" width="833" src="https://user-images.githubusercontent.com/39649076/215435493-1474ea6e-d355-41b6-9bfb-9c8d5c51d646.png">
> 
> @nirav-chotai ok . A couple of things I can suggest at this point is:
> 
> 1. Remove the pg from the osd manually.
> 2. Open an issue in  https://tracker.ceph.com/ and see what ceph team can suggest.

@nirav-chotai Please don't delete the PG yet.  Can you please open a ticket in https://tracker.ceph.com/ with all the details. Thanks.

**Comment by Matan-B** [comment]
> @sp98 , and one more thing, is it possible to run specific OSD with debug_osd = 20? I'm using Rook/Ceph on K8s, so I know about using `rook-config-override` ConfigMap but that will apply at cluster i.e. global level, right?
> 
> ```
> [osd]
>         debug_osd = 20
> ```
Yes, these configurations are global. You can set a specific OSD debug level with the following command:
`ceph tell osd.<id> config set debug_osd 20`.
As @sp98 mentioned, please open an issue in the tracker and we will continue the investigation from there.

**Comment by nirav-chotai** [comment]
@sp98  and @Matan-B , thanks for your comments, will raise an issue in https://tracker.ceph.com/

Is this related to below findings? Recently we added more storage by adding more OSDs. It shows in total storage, but `replicapool` is still showing more than 90% usage and having no effect of newly added storage?

```
[root@rook-ceph-tools-68958dbb7f-klmcn /]# ceph df
--- RAW STORAGE ---
CLASS  SIZE     AVAIL   USED    RAW USED  %RAW USED
hdd    153 TiB  75 TiB  78 TiB    78 TiB      50.97
ssd     36 TiB  19 TiB  18 TiB    18 TiB      48.98
TOTAL  189 TiB  93 TiB  96 TiB    96 TiB      50.59
 
--- POOLS ---
POOL                   ID  STORED   OBJECTS  USED     %USED  MAX AVAIL
replicapool             1   32 TiB    8.31M   96 TiB  90.48    3.3 TiB
device_health_metrics   2  3.1 MiB      237  9.4 MiB      0    3.3 TiB
myfs-metadata           3   20 MiB       23   61 MiB      0    3.3 TiB
myfs-data0              4      0 B        0      0 B      0    3.3 TiB
[root@rook-ceph-tools-68958dbb7f-klmcn /]# 
```

Am I missing anything here?

**Comment by sp98** [comment]
@nirav-chotai  not really sure if the behavior you mentioned in the above comment is related to the `Health Err` you mentioned in the ticket description.

**Comment by sp98** [comment]
@nirav-chotai Since we can't do much about the PGs in Rook and you have a ceph tracker for this, I would suggest we close this in Rook after the adding the ceph tracker link here.

**Comment by nirav-chotai** [comment]
Thanks @sp98 , you did great help. Let me close this and will open issue to ceph tracker.

**Comment by zhucan** [comment]
@nirav-chotai is there a way to slove it?

**Comment by nirav-chotai** [comment]
@zhucan , we scale up by adding few more OSDs, and waited for completion of data rebalancing, it took few days but eventually error was gone. (Then we scale down by removing additional OSDs)

**Comment by fantastic2085** [comment]
What is the link(https://tracker.ceph.com/) above the issue of this issue that I also encountered @nirav-chotai
