### ISSUE TITLE
save osd crush config

### ISSUE THREAD

**Issue by clcc2019** [rook/rook#11610]
How to save osd crush settings，Or can you save osd crush safely?

```bash
ceph osd crush set osd.x 0.5 root=newroot
```
I created a new osd crush rule, and set the osd pool to this rule, now I need to put part of the osd into the rule

**Comment by travisn** [comment]
The `ceph osd crush set` commands should persist and will not be overwritten. Ceph is only expected to set the OSD crush settings automatically the first time the OSD starts. As long as you change the setting after the OSD is first running, then it will persist.

**Comment by clcc2019** [comment]
> The `ceph osd crush set` commands should persist and will not be overwritten.

But now it's not working as expected, crush reverts to default root after a while

**Comment by parth-gr** [comment]
Can you share the rook-operator logs?

**Comment by travisn** [comment]
@clcc2019 Can you find what causes the root to revert after a while? Restarting the OSD? Restarting the operator? Something else?

**Comment by microyahoo** [comment]
hi @clcc2019, do you mean node restart results in default CRUSH map again? If yes, you can set  `osd crush update on start = false` in rook-config-override configmap, and you can reference kb of https://www.suse.com/support/kb/doc/?id=000018981

**Comment by clcc2019** [comment]
> hi @clcc2019, do you mean node restart results in default CRUSH map again? If yes, you can set `osd crush update on start = false` in rook-config-override configmap, and you can reference kb of https://www.suse.com/support/kb/doc/?id=000018981

Yes, this configuration works
