### ISSUE TITLE
Bandwidth limitation/Network QoS between nodes?

### ISSUE THREAD

**Issue by KlavsKlavsen** [rook/rook#11618]
* Feature Request

** What should the feature do **
The feature should identify interface max speed, and bandwidth limit ceph to a "percentage" of max, or network QoS (ensuring ceph packages go last atleast - so other traffic is not affected)

**What is use case behind this feature:**

We run k8s with Ceph on bare metal servers - with Hetzner. They have only one network interface, so we cannot isolate Ceph traffic to seperate network - meaning controllers (and everything else) also talk over same network.

if we have a node failure ceph needs to duplicte lost blocks to other nodes, but that takes up a LOT of bandwidth - and with Hetzner (and pretty much most physical server providers ) its often 1gb interfaces, so its an easy situation to reach - and it kills the cluster pretty much :(

Rook should ensure Ceph traffic is at lowest priority - and possibly even "prioritize ceph traffic in order of importance" so f.ex. redundancy recovering - is run at lower priority to NOT interfere with cluster normal traffic.

**Environment**:
bare metal or VM environments where you want to run Rook.. (so basicly all use cases of Rook)

**Comment by parth-gr** [comment]
So just to clairfy you are asking for, To add a Max Limit of Traffic/Network for Ceph processing?

**Comment by KlavsKlavsen** [comment]
I would simply implement it on pod network level - but yes.. bandwith limitation  or "optionally if network and cni supports" QoS instead - so all bandwidth can be used + but QoS ensures 'everybody elses traffic' reaches in time and is not affected by Ceph eating all available capacity.

**Comment by KlavsKlavsen** [comment]
this would also help Ceph endure + when OSD replication takes all available network capacity + to ensure its manager processes can still talk to each other.

**Comment by parth-gr** [comment]
Basically so the target would be ceph daemons?

**Comment by KlavsKlavsen** [comment]
Well - OSD pods would be the first one.. I expect them to be the biggest bandwidth consumers.

**Comment by KlavsKlavsen** [comment]
but if you want to go QoS route (best) - one would need to ensure default "priority" is higher than whats given to OSD pods (and that this works in network that connects nodes).. 
But just being able to set a bandwidth limit for OSD pods - would help a lot to not saturate network entirely atleast - which quickly brings down a cluster running rook-ceph (as ceph runs on nodes that also do other things)

**Comment by caffeinism** [comment]
If the node is accessible, it seems appropriate to limit it through tc(8) based on IP and port. Based on the OSD pod, it may be more difficult to set up depending on the number of OSDs per node and link bandwidth per node.

**Comment by KlavsKlavsen** [comment]
@caffeinism well yes - I would suggest limit needs to be set "centrally" on ceph - so it goes for all pods on same node.. and if thats not possible, one would probably need to f.ex. maintain a tc bandwidth limit table - which is maintained per-node to include the osd ceph pods on it.
unless there's some "smarter" way?
