### ISSUE TITLE
Set KernelMountOption for cephfs as ms_mode=secure

### ISSUE THREAD

**Issue by malayparida2000** [rook/rook#11624]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The ceph-fs volumes should have the mount option as ms_mode=secure to make them work on encryption enabled
cluster where the msgrv2 port is being used.

**What is use case behind this feature:**
In transit encryption with msgrv2, for cephfs volumes

**Environment**:

**Comment by travisn** [comment]
From a separate thread, thanks for also validating that the following storage class parameter will work until the csi driver implements this:
```
parameters:
  kernelMountOptions: ms_mode=secure
```

**Comment by cehoffman** [comment]
Is the documentation out of date? I see in the CephCluster CRD documentation for encryptino it calls out the need to set some kernel parameters on the operator. Obviously it seems less than ideal needing to modify the operator deployment depending on configuration settings of a specific CephCluster CRD instance.

<img width="734" alt="Screenshot 2023-06-29 at 2 51 42 AM" src="https://github.com/rook/rook/assets/27545/e20cb4e3-3e55-4912-b8b7-e9473b50d5fe">

If a separate issue is required to track the need for separation of the kernel parameter from the operator I'll gladly make one. I just want to get the current expectation.
