### ISSUE TITLE
OSDs on PVCs fail to create in some environments on Ceph v16.2.11 and v17.2.5

### ISSUE THREAD

**Issue by travisn** [rook/rook#11656]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSD canary tests on PVCs are failing in the following Ceph versions:
- v16.2.11
- v17.2.5, starting from the end of Jan (it's not clear why, since they were passing previously)

The OSD canary tests are **passing** against Ceph main as experimented in #11653.

As discussed in [this Rook PR to fix the CI](https://github.com/rook/rook/pull/11646#issuecomment-1425290903), as @satoru-takeuchi states, we believe it is related to https://github.com/ceph/ceph#49171. That fix is already fixed in Ceph main, but not yet backported to pacific or quincy, which explains why the latest `devel` tags in those releases are still failing.

**Expected behavior:**
Passing CI on the latest Ceph releases and `devel` tags.

**How to reproduce it (minimal and precise):**

Update the canary pvc tests [here](https://github.com/rook/rook/blob/master/tests/manifests/test-cluster-on-pvc-encrypted.yaml#L17) to run with either the tags `quay.io/ceph/daemon-base:latest-pacific-devel` or `quay.io/ceph/daemon-base:latest-quincy-devel`.

**Comment by satoru-takeuchi** [comment]
@travisn This problem was fixed in Ceh v17.2.6.

https://ceph.io/en/news/blog/2023/v17-2-6-quincy-released/
> ceph-volume: fix a bug in lsblk_all() (pr#49868, Guillaume Abrioux)

In addition, the fix was backported to v16 release branch. So it will also be fixed in v16.2.12.

**Comment by satoru-takeuchi** [comment]
Ah, you've already noticed this #12068 . Sorry for noise.
