### ISSUE TITLE
Update the image version of operator, all daemons of the ceph will be restarted?

### ISSUE THREAD

**Issue by microyahoo** [rook/rook#11657]
### Discussed in https://github.com/rook/rook/discussions/11639

<div type='discussions-op-text'>

<sup>Originally posted by **zhucan** February  9, 2023</sup>
```
rook-ceph-crashcollector-rook-node01-6db679d78c-bn26x   1/1     Running     0             20m
rook-ceph-crashcollector-rook-node02-6c4488b9fb-6jn9n   1/1     Running     0             20m
rook-ceph-crashcollector-rook-node03-67449c6d69-wwwt6   1/1     Running     0             20m
rook-ceph-mds-myfs-a-5b555c6975-gx2qc                   2/2     Running     0             19m
rook-ceph-mds-myfs-b-64fd45bb9b-qnl7s                   2/2     Running     0             19m
rook-ceph-mgr-a-5d7cd95bdc-h9knp                        3/3     Running     0             18m
rook-ceph-mgr-b-f4c757bb8-x48sj                         3/3     Running     0             18m
rook-ceph-mon-a-55dd8fd6df-fztnh                        2/2     Running     0             19m
rook-ceph-mon-b-65f8fcdf57-p5vxl                        2/2     Running     0             20m
rook-ceph-mon-d-669f75cf45-25xgc                        2/2     Running     0             19m
rook-ceph-operator-54b7bbb7c-5f6m8                      1/1     Running     0             20m
rook-ceph-osd-0-688f57df99-s9jbz                        2/2     Running     0             17m
rook-ceph-osd-1-66f67bdd7d-cf2cp                        2/2     Running     0             17m
rook-ceph-osd-2-6897688d9b-r25jd                        2/2     Running     0             16m
rook-ceph-osd-3-c4fc558f-4hsf7                          2/2     Running     0             17m
rook-ceph-osd-4-6d497dc5dd-ksb6k                        2/2     Running     0             16m
rook-ceph-osd-5-5758d5bcfc-4gsw2                        2/2     Running     0             17m
rook-ceph-osd-prepare-rook-node01--1-f55mq              0/1     Completed   0             17m
rook-ceph-osd-prepare-rook-node02--1-ftxgw              0/1     Completed   0             17m
rook-ceph-osd-prepare-rook-node03--1-ztl89              0/1     Completed   0             17m
rook-ceph-rgw-my-store-a-7c9bdcb6fd-84462               2/2     Running     0             19m
rook-ceph-rgw-my-store-a-7c9bdcb6fd-f2k5b               2/2     Running     0             19m
rook-ceph-rgw-my-store-a-7c9bdcb6fd-sh8qv               2/2     Running     0             19m
```
</div>

**Comment by travisn** [comment]
@microyahoo To help identify the issue, please provide the following:
1. Pod spec of an OSD: `kubectl -n rook-ceph get pod rook-ceph-osd-0-688f57df99-s9jbz -o yaml`
2. Restart the operator
3. After the OSD pod is restarted, get the new pod spec
4. Bonus points for diffing the pod spec to see what changed.

Thanks!

**Comment by travisn** [comment]
Or even repro steps would help. I was not able to repro this issue in my test cluster. Perhaps there is a non-default setting in the cluster CR that is related to this issue.

**Comment by microyahoo** [comment]
Hi @travisn, I have patched the code and add a log to print the diff as below. It can be seen that only the rook version has changed. In this case, there should be no need to restart the osd pods.
```
Patch: {"metadata":{"labels":{"rook-version":"v1.9.8-12.g27b085b18.dirty"}},"spec":{"template":{"metadata":{"labels":{"rook-version":"v1.9.8-12.g27b085b18.dirty"}}}}}
```

**Comment by gaord** [comment]
after upgrading rook from 1.10.1 to 1.10.11 as steps in [documents](https://rook.io/docs/rook/v1.10/Upgrade/rook-upgrade/#patch-release-upgrades), all ceph daemons get restarted. see below for minutes age(restarted) for details:

NAME                                                      READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-9clhv                                    2/2     Running     8          105d
csi-cephfsplugin-dqdwq                                    2/2     Running     10         105d
csi-cephfsplugin-mw2nn                                    2/2     Running     12         105d
csi-cephfsplugin-provisioner-57f84d6979-n9kwx             5/5     Running     0          32m
csi-cephfsplugin-provisioner-57f84d6979-r845z             5/5     Running     0          32m
csi-cephfsplugin-wcqbk                                    2/2     Running     10         105d
csi-cephfsplugin-xkn6t                                    2/2     Running     57         105d
csi-cephfsplugin-z255t                                    2/2     Running     12         105d
csi-nfsplugin-45tm2                                       2/2     Running     10         105d
csi-nfsplugin-86cl4                                       2/2     Running     12         105d
csi-nfsplugin-fd9qv                                       2/2     Running     28         89d
csi-nfsplugin-mnmrl                                       2/2     Running     10         105d
csi-nfsplugin-provisioner-666996876d-g29nx                4/4     Running     15         34d
csi-nfsplugin-provisioner-666996876d-gkwrc                4/4     Running     4          16d
csi-nfsplugin-scb8q                                       2/2     Running     8          105d
csi-nfsplugin-sqpzj                                       2/2     Running     10         105d
csi-rbdplugin-2xzr9                                       2/2     Running     12         105d
csi-rbdplugin-6smvc                                       2/2     Running     51         105d
csi-rbdplugin-g4q5x                                       2/2     Running     8          105d
csi-rbdplugin-jbjt2                                       2/2     Running     10         105d
csi-rbdplugin-mw6ff                                       2/2     Running     12         105d
csi-rbdplugin-p2fqx                                       2/2     Running     10         105d
csi-rbdplugin-provisioner-7b44545bb6-pb74v                5/5     Running     0          32m
csi-rbdplugin-provisioner-7b44545bb6-vg2jl                5/5     Running     0          32m
rook-ceph-crashcollector-10.138.55.111-54fc97f847-bdr6v   1/1     Running     0          32m
rook-ceph-crashcollector-10.138.55.112-57b44bcc58-vqj9v   1/1     Running     0          33m
rook-ceph-crashcollector-10.138.55.113-55f9fb9fd9-bjstz   1/1     Running     0          33m
rook-ceph-crashcollector-10.138.55.116-8df7c96f6-7pl6p    1/1     Running     0          33m
rook-ceph-crashcollector-10.138.55.117-7f97855cd7-lztrp   1/1     Running     0          33m
rook-ceph-crashcollector-10.138.55.120-6dbfd96584-hl8r8   1/1     Running     0          18m
rook-ceph-mds-myfs-a-6c6566c948-88d5l                     1/1     Running     0          32m
rook-ceph-mds-myfs-b-5d9fd4b4f8-n97fn                     1/1     Running     0          30m
rook-ceph-mgr-a-744f999b69-8q6nn                          2/2     Running     0          27m
rook-ceph-mgr-b-864584bdf7-j9lsc                          2/2     Running     0          25m
rook-ceph-mon-k-5b85d56488-dmbwf                          1/1     Running     0          29m
rook-ceph-mon-m-6bf68bc6d-d5phl                           1/1     Running     0          31m
rook-ceph-mon-o-5bf4cff8df-4jv2x                          1/1     Running     0          32m
rook-ceph-nfs-nfs1-a-854cc9bd5b-8t856                     2/2     Running     0          32m
rook-ceph-nfs-nfs4rgw-a-ddf7b6f7c-96sfk                   2/2     Running     0          6m27s
rook-ceph-nfs-nfs4rgw1-a-54b589dbc9-bdtkc                 2/2     Running     0          6m11s
rook-ceph-operator-77bf97d78d-z27vb                       1/1     Running     0          33m
rook-ceph-osd-0-7bd87d6d59-p7jb5                          1/1     Running     0          23m
rook-ceph-osd-1-c9fc85867-hbt76                           1/1     Running     0          22m
rook-ceph-osd-2-778c676bd-trwd8                           1/1     Running     0          20m
rook-ceph-osd-3-95b755656-828nc                           1/1     Running     0          18m
rook-ceph-osd-prepare-10.138.55.113-p7ct2                 0/1     Completed   0          16m
rook-ceph-osd-prepare-10.138.55.116-rz2kn                 0/1     Completed   0          16m
rook-ceph-osd-prepare-10.138.55.117-2nv6n                 0/1     Completed   0          16m
rook-ceph-osd-prepare-10.138.55.120-7q8mn                 0/1     Completed   0          16m
rook-ceph-rgw-my-store-a-65fbc5df4-k5h8x                  1/1     Running     198        35d
rook-ceph-tools-5d8c78cd5b-87ht2                          1/1     Running     2          34d

**Comment by travisn** [comment]
Ok, I found the issue... The operator was adding the rook-version tag to the OSD pod spec due to a shared pointer to the labels. The code intended to only add the version label to the deployment labels, but since the pod labels shared the map variable, the pod unintentionally also had the version label added. Therefore, every time rook was updated, the OSD pod spec was also updated, and therefore restarted.

**Comment by microyahoo** [comment]
we can set deployment label with `ceph.rook.io/do-not-reconcile="true"` to skip reconcile.

**Comment by gaord** [comment]
ceph crash pod is found to have rook version label set by the map pointer. Just open this issue to get the fix in.

**Comment by gaord** [comment]
> we can set deployment label with `ceph.rook.io/do-not-reconcile="true"` to skip reconcile.

good to know. it looks like not all reconcilers respect this label. at least ceph crash doesn't.

**Comment by microyahoo** [comment]
> > we can set deployment label with `ceph.rook.io/do-not-reconcile="true"` to skip reconcile.
> 
> good to know. it looks like not all reconcilers respect this label. at least ceph crash doesn't.

@gaord yes, mgrs and mds not respect this label, I have submitted a pr to handle it. https://github.com/rook/rook/pull/11802
