### ISSUE TITLE
Ceph is in the process of upgrading，some components of look ceph have not been upgraded

### ISSUE THREAD

**Issue by yangwenbo-su** [rook/rook#11677]
**question:**
I upgraded the rook-echo version according to the official website document, rook version 1.7.7 to 1.8.10 and ceph version 15.2.8 to 16.2.7. First upgraded common.yaml and crds.yaml, then upgraded operator's image version, last upgraded cephcluster version. Most components have been upgraded ,  only ceph osd version is 15.2.8, please help me.
**Official documents:**
[https://rook.io/docs/rook/v1.8/ceph-upgrade.html#csi-version](url)
**Environment**:
ubuntu20.04
kubernetes 1.19.3
**report:**
` $  kubectl describe cephcluster cephcluster rook-ceph -n rook-ceph
Name:         rook-ceph
Namespace:    rook-ceph
Labels:       <none>
Annotations:  <none>
API Version:  ceph.rook.io/v1
Kind:         CephCluster
Metadata:
  Creation Timestamp:             2021-02-25T09:20:22Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2023-02-14T02:09:59Z
  Finalizers:
    cephcluster.ceph.rook.io
  Generation:  39
  Managed Fields:
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:cephVersion:
        f:cleanupPolicy:
          .:
          f:sanitizeDisks:
            .:
            f:dataSource:
            f:iteration:
            f:method:
        f:crashCollector:
        f:dashboard:
          .:
          f:enabled:
          f:ssl:
        f:dataDirHostPath:
        f:disruptionManagement:
          .:
          f:machineDisruptionBudgetNamespace:
          f:osdMaintenanceTimeout:
        f:healthCheck:
        f:mgr:
          .:
          f:modules:
        f:mon:
        f:monitoring:
          .:
          f:rulesNamespace:
        f:removeOSDsIfOutAndSafeToRemove:
        f:storage:
          .:
          f:useAllDevices:
    Manager:      kubectl
    Operation:    Update
    Time:         2022-11-25T11:47:33Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:mon:
          f:count:
        f:monitoring:
          f:enabled:
    Manager:      node-fetch
    Operation:    Update
    Time:         2023-02-10T01:59:03Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:cephVersion:
          f:image:
        f:skipUpgradeChecks:
      f:status:
        f:ceph:
          f:versions:
            f:osd:
              f:ceph version 16.2.7 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable):
            f:overall:
              f:ceph version 16.2.7 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable):
    Manager:      kubectl-edit
    Operation:    Update
    Time:         2023-02-14T07:34:05Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"cephcluster.ceph.rook.io":
      f:spec:
        f:external:
        f:healthCheck:
          f:daemonHealth:
            .:
            f:osd:
              f:interval:
            f:status:
              f:interval:
          f:livenessProbe:
        f:logCollector:
        f:network:
          .:
          f:hostNetwork:
          f:ipFamily:
          f:provider:
          f:selectors:
        f:security:
          .:
          f:kms:
        f:storage:
          f:config:
          f:nodes:
          f:storageClassDeviceSets:
      f:status:
        .:
        f:ceph:
          .:
          f:capacity:
            f:bytesAvailable:
            f:bytesTotal:
            f:bytesUsed:
            f:lastUpdated:
          f:fsid:
          f:health:
          f:lastChanged:
          f:lastChecked:
          f:previousHealth:
          f:versions:
            .:
            f:mds:
              .:
              f:ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable):
            f:mgr:
              .:
              f:ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable):
            f:mon:
              .:
              f:ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable):
            f:osd:
            f:overall:
            f:rgw:
              .:
              f:ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable):
        f:conditions:
        f:message:
        f:phase:
        f:state:
        f:storage:
        f:version:
          .:
          f:image:
          f:version:
    Manager:         rook
    Operation:       Update
    Time:            2023-02-15T06:57:19Z
  Resource Version:  1345160523
  Self Link:         /apis/ceph.rook.io/v1/namespaces/rook-ceph/cephclusters/rook-ceph
  UID:               719ba7ef-2602-46e2-9bbc-bae926469fe5
Spec:
  Ceph Version:
    Allow Unsupported:  false
    Image:              quay.io/ceph/ceph:v16.2.7-20220216
  Cleanup Policy:
    Allow Uninstall With Volumes:  false
    Confirmation:                  
    Sanitize Disks:
      Data Source:                                    zero
      Iteration:                                      1
      Method:                                         quick
  Continue Upgrade After Checks Even If Not Healthy:  false
  Crash Collector:
    Disable:  false
  Dashboard:
    Enabled:           true
    Ssl:               true
  Data Dir Host Path:  /var/lib/rook
  Disruption Management:
    Machine Disruption Budget Namespace:  openshift-machine-api
    Manage Machine Disruption Budgets:    false
    Manage Pod Budgets:                   false
    Osd Maintenance Timeout:              30
    Pg Health Check Timeout:              0
  External:
    Enable:  false
  Health Check:
    Daemon Health:
      Mon:
        Disabled:  false
        Interval:  45s
      Osd:
        Disabled:  false
        Interval:  60s
      Status:
        Disabled:  false
        Interval:  60s
    Liveness Probe:
      Mgr:
        Disabled:  false
      Mon:
        Disabled:  false
      Osd:
        Disabled:  false
  Log Collector:
  Mgr:
    Modules:
      Enabled:  true
      Name:     pg_autoscaler
  Mon:
    Allow Multiple Per Node:  false
    Count:                    3
  Monitoring:
    Enabled:                               true
    Rules Namespace:                       rook-ceph
  Remove OS Ds If Out And Safe To Remove:  true
  Security:
    Kms:
  Skip Upgrade Checks:  true
  Storage:
    Nodes:
      Devices:
        Name:  sdb
      Name:    node-10
      Devices:
        Name:  sdb
      Name:    node-11
      Devices:
        Name:  sdb
      Name:    node-12
      Devices:
        Name:  sdb
      Name:    node-14
      Devices:
        Name:  sdc
      Name:    node-10
      Devices:
        Name:  sdc
      Name:    node-11
      Devices:
        Name:  sdc
      Name:    node-12
      Devices:
        Name:  sdc
      Name:    node-14
      Devices:
        Name:  sdb
      Name:    node-15
      Devices:
        Name:  sda
      Name:    node-15
      Devices:
        Name:  sdb
      Name:    node-16
      Devices:
        Name:         sda
      Name:           node-16
    Use All Devices:  false
    Use All Nodes:    false
Status:
  Ceph:
    Capacity:
      Bytes Available:  7857826820096
      Bytes Total:      24004773543936
      Bytes Used:       16146946723840
      Last Updated:     2023-02-14T02:09:22Z
    Fsid:               8b1fc0f1-178b-4f8e-b43d-909a293a2b60
    Health:             HEALTH_OK
    Last Changed:       2023-02-14T01:51:10Z
    Last Checked:       2023-02-14T02:09:22Z
    Previous Health:    HEALTH_WARN
    Versions:
      Mds:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable):  2
      Mgr:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable):  1
      Mon:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable):  3
      Osd:
        ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable):  12
      Overall:
        ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable):  12
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable):  11
      Rgw:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable):  5
  Conditions:
    Last Heartbeat Time:   2023-02-14T02:08:32Z
    Last Transition Time:  2023-02-14T02:08:32Z
    Message:               failed to create cluster: failed to start ceph mgr: failed to enable mgr services: failed to enable service monitor: service monitor could not be enabled: failed to retrieve servicemonitor. servicemonitors.monitoring.coreos.com "rook-ceph-mgr" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"
    Reason:                ClusterProgressing
    Status:                False
    Type:                  Progressing
    Last Heartbeat Time:   2023-02-14T02:09:22Z
    Last Transition Time:  2023-02-03T04:09:36Z
    Message:               Cluster created successfully
    Reason:                ClusterCreated
    Status:                True
    Type:                  Ready
    Last Heartbeat Time:   2023-02-15T06:57:19Z
    Last Transition Time:  2023-02-14T02:10:01Z
    Message:               CephCluster "rook-ceph/rook-ceph" will not be deleted until all dependents are removed: CephObjectStore: [my-store]
    Reason:                ObjectHasDependents
    Status:                True
    Type:                  DeletionIsBlocked
    Last Heartbeat Time:   2023-02-15T06:57:19Z
    Last Transition Time:  2023-02-14T02:10:01Z
    Message:               Deleting the CephCluster
    Reason:                ClusterDeleting
    Status:                True
    Type:                  Deleting
  Message:                 Deleting the CephCluster
  Phase:                   Deleting
  State:                   Deleting
  Storage:
    Device Classes:
      Name:  ssd
  Version:
    Image:    quay.io/ceph/ceph:v16.2.7-20220216
    Version:  16.2.7-0
Events:
  Type     Reason           Age                   From                          Message
  ----     ------           ----                  ----                          -------
  Warning  ReconcileFailed  12s (x8350 over 23h)  rook-ceph-cluster-controller  failed to reconcile CephCluster "rook-ceph/rook-ceph". CephCluster "rook-ceph/rook-ceph" will not be deleted until all dependents are removed: CephObjectStore: [my-store]
Error from server (NotFound): cephclusters.ceph.rook.io "cephcluster" not found
$ kubectl get pod -n rook-ceph
NAME                                                READY   STATUS            RESTARTS   AGE
ceph-object-controller-detect-version-fqzcq         0/1     PodInitializing   0          3s
csi-cephfsplugin-7rn2j                              3/3     Running           0          44h
csi-cephfsplugin-8r7hq                              3/3     Running           0          44h
csi-cephfsplugin-gfrhr                              3/3     Running           0          44h
csi-cephfsplugin-l2bzd                              3/3     Running           0          44h
csi-cephfsplugin-m96tl                              3/3     Running           0          44h
csi-cephfsplugin-nwxg7                              3/3     Running           0          44h
csi-cephfsplugin-p4b55                              3/3     Running           0          44h
csi-cephfsplugin-prfpr                              3/3     Running           0          44h
csi-cephfsplugin-provisioner-779df65-7zzf2          6/6     Running           0          44h
csi-cephfsplugin-provisioner-779df65-mctjg          6/6     Running           0          44h
csi-cephfsplugin-zsghf                              3/3     Running           0          44h
csi-rbdplugin-2zxgz                                 3/3     Running           0          44h
csi-rbdplugin-52cbw                                 3/3     Running           0          44h
csi-rbdplugin-786c8                                 3/3     Running           0          44h
csi-rbdplugin-f8lwt                                 3/3     Running           0          44h
csi-rbdplugin-mcvg9                                 3/3     Running           0          44h
csi-rbdplugin-provisioner-6dc4fb97bc-7gkc8          6/6     Running           0          44h
csi-rbdplugin-provisioner-6dc4fb97bc-zcndx          6/6     Running           0          44h
csi-rbdplugin-qbv94                                 3/3     Running           0          44h
csi-rbdplugin-qwklc                                 3/3     Running           0          44h
csi-rbdplugin-rc2bx                                 3/3     Running           0          44h
csi-rbdplugin-tv2nh                                 3/3     Running           0          44h
rook-ceph-crashcollector-node-10-5667bfc595-7kpdm   1/1     Running           0          40h
rook-ceph-crashcollector-node-11-7c577dd54b-grq7n   1/1     Running           0          23h
rook-ceph-crashcollector-node-12-9874f5b99-zw4s9    1/1     Running           0          23h
rook-ceph-crashcollector-node-14-7469c6689c-2np77   1/1     Running           0          23h
rook-ceph-crashcollector-node-15-59589bc6c4-qt9c4   1/1     Running           0          23h
rook-ceph-crashcollector-node-16-68d9fbdbb9-zbpxl   1/1     Running           0          23h
rook-ceph-crashcollector-node-18-6d56bdd449-ghc6s   1/1     Running           0          40h
rook-ceph-mgr-a-6f5668db86-jggcx                    1/1     Running           0          24h
rook-ceph-mon-ar-54c8994bb6-59v54                   1/1     Running           0          40h
rook-ceph-mon-as-9bc54d75c-bxxgv                    1/1     Running           0          40h
rook-ceph-mon-at-7b57cb5f4-vbplt                    1/1     Running           0          40h
rook-ceph-operator-68b64dbd4c-sw6r5                 1/1     Running           0          27h
rook-ceph-osd-0-5c9cff8f9c-7cqqz                    1/1     Running           0          3h10m
rook-ceph-osd-1-68d9c596c9-v96bm                    1/1     Running           0          3h38m
rook-ceph-osd-10-79dbd46d6f-w8pmb                   1/1     Running           0          3h37m
rook-ceph-osd-11-f84894bb5-76hs2                    1/1     Running           0          62d
rook-ceph-osd-13-5856f68d47-hmxz5                   1/1     Running           3          29d
rook-ceph-osd-14-845446cd7d-snkms                   1/1     Running           0          29d
rook-ceph-osd-3-548c4c9bfc-t8x47                    1/1     Running           0          78d
rook-ceph-osd-4-766bdb8b74-4cj8j                    1/1     Running           0          13d
rook-ceph-osd-5-7cfd7f89df-h6bqx                    1/1     Running           8          142d
rook-ceph-osd-6-66ffdd7dcd-xgnf6                    1/1     Running           0          55d
rook-ceph-osd-7-5f7b4fbb7b-k99d8                    1/1     Running           7          78d
rook-ceph-osd-9-656b7b5b8f-7h8kh                    1/1     Running           0          13d
rook-ceph-osd-prepare-node-10-hx4rp                 0/1     Completed         0          5d5h
rook-ceph-osd-prepare-node-11-q98th                 0/1     Completed         0          5d5h
rook-ceph-osd-prepare-node-12-cpktp                 0/1     Completed         0          5d5h
rook-ceph-osd-prepare-node-14-csdzl                 0/1     Completed         0          5d5h
rook-ceph-osd-prepare-node-15-pqxl4                 0/1     Completed         0          5d5h
rook-ceph-osd-prepare-node-16-z6r7f                 0/1     Completed         0          5d5h
rook-ceph-rgw-my-store-a-65857b57d7-22z9l           1/1     Running           0          23h
rook-ceph-rgw-my-store-a-65857b57d7-ctlhz           1/1     Running           0          23h
rook-ceph-rgw-my-store-a-65857b57d7-dm4rp           1/1     Running           0          23h
rook-ceph-rgw-my-store-a-65857b57d7-f7zj9           1/1     Running           1          23h
rook-ceph-rgw-my-store-a-65857b57d7-ql6jd           1/1     Running           0          23h
rook-ceph-tools-6896f9d4d9-8tthk                    1/1     Running           0          40h
$ ceph status
cluster:
    id:     8b1fc0f1-178b-4f8e-b43d-909a293a2b60
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum ar,as,at (age 20h)
    mgr: a(active, since 24h)
    osd: 12 osds: 12 up (since 3h), 12 in (since 13d)
    rgw: 5 daemons active (5 hosts, 1 zones)
 
  data:
    pools:   9 pools, 337 pgs
    objects: 20.27M objects, 4.9 TiB
    usage:   15 TiB used, 7.0 TiB / 22 TiB avail
    pgs:     336 active+clean
             1   active+clean+scrubbing+deep+repair
 
  io:
    client:   306 KiB/s rd, 340 B/s wr, 34 op/s rd, 9 op/s wr
`

**Comment by yangwenbo-su** [comment]
"rook-ceph-cluster-controller failed to reconcile CephCluster "rook-ceph/rook-ceph". CephCluster "rook-ceph/rook-ceph" will not be deleted until all dependents are removed: CephObjectStore: [my-store]"
Cephcluster has been prompting me to delete the object storage. If I delete it, the data will be lost?

**Comment by zhucan** [comment]
The pod of osd was restart? and please format the output.

**Comment by yangwenbo-su** [comment]
I has been restarted.
[osd-0.log](https://github.com/rook/rook/files/10741438/osd-0.log)

**Comment by travisn** [comment]
From this message, it appears you have marked your cephcluster CR as deleted:
```
Warning ReconcileFailed 12s (x8350 over 23h) rook-ceph-cluster-controller failed to reconcile CephCluster "rook-ceph/rook-ceph". 
CephCluster "rook-ceph/rook-ceph" will not be deleted until all dependents are removed:
```
In this case you will need to restore the CR, see the [recovery guide](https://rook.io/docs/rook/latest/Troubleshooting/disaster-recovery/#restoring-crds-after-deletion).

**Comment by yangwenbo-su** [comment]
Ok, I will not continue to operate until all data is backed up. Thank you very much
