### ISSUE TITLE
Mon failover takes extra time

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#11682]
Why the mon deployment is created before checking if it actually exist?
https://github.com/rook/rook/blob/11e80b7047553c04eeeb5c11f1c6c76fda381d5e/pkg/operator/ceph/cluster/mon/mon.go#L1250

Also why this node affinity is tied up with updates, Which might change the deployment everytime https://github.com/rook/rook/blob/11e80b7047553c04eeeb5c11f1c6c76fda381d5e/pkg/operator/ceph/cluster/mon/mon.go#L1275-L1283

**Comment by travisn** [comment]
> Why the mon deployment is created before checking if it actually exist?
 
The reconcile will re-generate the deployment and pod specs with every reconcile. If there is any difference, the pod would be updated. If the pod spec is exactly the same, K8s will ignore the update and the pod will not be updated. With this approach, we just reconcile to the desired state, and don't generally have to diff the current state.

> Also why this node affinity is tied up with updates, Which might change the deployment everytime

The node affinity will only change if there is an update to the cephcluster CR, right? Then it would be expected to update the deployment. Or can you clarify why it's not expected?

**Comment by travisn** [comment]
@parth-gr Can you answer the earlier questions to clarify why this is reopened?
