### ISSUE TITLE
Move Rook to use Go 1.19 version

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#11681]
**Is this a bug report or feature request?**
* Feature Request
Currently, csi is started using Go1.19 version and other dependent projects are planning for this, we should move and start using GO1.19 version

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by Madhu-1** [comment]
You meant go 1.19?

**Comment by Madhu-1** [comment]
Also good to update the kubernetes version to 1.26 in go.mod?

**Comment by parth-gr** [comment]
> You meant go 1.19?

Yes

**Comment by parth-gr** [comment]
> Also good to update the kubernetes version to 1.26 in go.mod?

Sure

**Comment by travisn** [comment]
Most of the github actions are already running with go 1.19. So I believe the work item is:
- Drop support for go 1.18
- Add support for go 1.20
- Update the go.mod to 1.19 and K8s 1.26
