### ISSUE TITLE
Setting network.connections.encryption.enabled causes cluster bootstrapping to never complete

### ISSUE THREAD

**Issue by gpl** [rook/rook#11691]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When using on-the-wire encryption with Ceph, we expect to be able to instantiate a new ceph rook cluster.  Instead, it stalls on the first mon until timeout. 

`2023-02-16 09:35:58.785920 I | op-mon: mons running: [a]`

**Expected behavior:**

Expected that cluster can bootstrap, however it doesn't do anything after initializing the mon.  We expect it to bring up 3 mons, but it doesn't appear to do so.

When wire encryption is set to false, the cluster immediately bootstraps mons/mgrs/osds.

**How to reproduce it (minimal and precise):**
Attempt to stand up a new ceph rook cluster, with wire encryption enabled. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): "NixOS 22.11 (Raccoon)"
* Kernel (e.g. `uname -a`): 5.15.89 #1-NixOS SMP Wed Jan 18 10:48:59 UTC 2023 x86_64 GNU/Linux
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod):  1.10
* Storage backend version (e.g. for ceph do `ceph -v`): 
* Kubernetes version (use `kubectl version`): 1.26.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
If you have the 5.15 kernel, that should be [recent enough](https://github.com/rook/rook/blob/release-1.10/deploy/examples/cluster.yaml#L82-L86). 

You are enabling the encryption from initial cluster creation, correct? There is an issue if you have an initial cluster, then later enable the encryption.

**Comment by gpl** [comment]
Yep, brand new cluster on 5.15

**Comment by travisn** [comment]
Any chance you have a firewall that would prevent some ports? The encryption uses msgr2 on port 3300, instead of msgr1 on port 6789.

**Comment by gpl** [comment]
There is no firewall in place, and we have verified that we can telnet to the single online mon when it comes up from the other hosts.

**Comment by travisn** [comment]
> There is no firewall in place, and we have verified that we can telnet to the single online mon when it comes up from the other hosts.

Can you connect from inside the operator pod to the mon port?

**Comment by gpl** [comment]
I think so - I've also got all pods running as hostNetwork.

**Comment by travisn** [comment]
Sorry, I'm not finding the issue in your env. The scenario is working in the CI and in other environments where it has been tested.

**Comment by gpl** [comment]
This is related to #10110, fixing that issue completely fixes this one.
