### ISSUE TITLE
The multi-cluster-mirroring canary test is not checking reliably for snapshots

### ISSUE THREAD

**Issue by travisn** [rook/rook#11742]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
As pointed out in #11741, the multi-cluster-mirroring test is failing consistently in master. 

It's sometimes timing out waiting for [create replicated mirrored filesystem on cluster 1](https://github.com/rook/rook/actions/runs/4187373738/jobs/7257125440):
```
+ kubectl create -f deploy/examples/filesystem-test-primary.yaml
cephfilesystem.ceph.rook.io/myfs created
+ timeout 120 sh -c 'until [ "$(kubectl -n rook-ceph get cephfilesystem myfs -o jsonpath={.status.phase}|grep -c "Ready")" -eq 1 ]; do echo "waiting for filesystem to be created" && sleep 1; done'
waiting for filesystem to be created
waiting for filesystem to be created
```

Or sometimes failing while [verify fs mirroring is working](https://github.com/rook/rook/actions/runs/4187199063/jobs/7256729212):
```
+ timeout 45 sh -c 'until [ "$(kubectl -n rook-ceph exec -t deploy/rook-ceph-fs-mirror -- ls -1 /var/run/ceph/|grep -c asok)" -lt 3 ]; do echo "waiting for connection to peer" && sleep 1; done'
Defaulted container "fs-mirror" out of: fs-mirror, chown-container-data-dir (init)
waiting for connection to peer
Defaulted container "fs-mirror" out of: fs-mirror, chown-container-data-dir (init)
waiting for connection to peer
```

Or sometimes failing while [Get the peer and verify the peer synchronization status that snaps have synced on secondary cluster](https://github.com/rook/rook/actions/runs/4180309083/jobs/7241166838):
```
++ grep snap
++ kubectl -n rook-ceph-secondary exec deploy/rook-direct-mount -- ls -lhsa /tmp/registry/volumes/_nogroup/testsubvolume/.snap
+ num_snaps_target=3
+ '[' 3 = 0 ']'
Snaps have not synced
+ echo 'Snaps have not synced'
+ exit 1
Error: Process completed with exit code 1.
```

**Expected behavior:**
Passing tests

**Comment by travisn** [comment]
@gauravsitlani Do you have time this week to investigate? We should get the CI green again soon, thanks!

**Comment by gauravsitlani** [comment]
@travisn sure, I'll keep on monitoring the CI for these failures. With https://github.com/rook/rook/pull/11822  i hope that at least we should see the less of them.

**Comment by travisn** [comment]
Reopening so we can track fixing the snapshots check that was disabled with the message:
`"Snaps have not synced. NEEDS INVESTIGATION"`

**Comment by travisn** [comment]
The failing portion of the test was disabled with #12151.
