### ISSUE TITLE
dashboard: uses internal IP rather than service load balancer IP

### ISSUE THREAD

**Issue by uhthomas** [rook/rook#11759]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The dashboard is trying to use internal IPs when visiting the endpoint generated by a service's load balancer.

![image](https://user-images.githubusercontent.com/9749173/221333741-fa380db8-011c-4e3a-b8c8-7ea152f2dc06.png)

The above screenshot should show clearly that some requests succeed, whilst others do not as they are using the internal IP.

I also saw this issue mentioned here with no resolution:

https://github.com/rook/rook/issues/4042#issuecomment-968367875

**Expected behavior:**

The dashboard should use the endpoint generated by the service's load balancer, not the internal IP.

**How to reproduce it (minimal and precise):**

Create a service with a load balancer for the dashboard as described in https://rook.io/docs/rook/v1.10/Storage-Configuration/Monitoring/ceph-dashboard/#load-balancer: 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mgr-dashboard-tailscale
  namespace: rook-ceph
spec:
  loadBalancerClass: tailscale
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: dashboard
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  sessionAffinity: None
  type: LoadBalancer
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.10.11
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by jmolmo** [comment]
@uhthomas , I think you are experimenting what is described here:
https://docs.ceph.com/en/quincy/mgr/dashboard/#disable-the-redirection

Despite the number of Ceph mgr daemons configured, only one is active, so to create a "load balancer service"  over a service provided by the Ceph manager (like dashboard) does not have too much sense.

**Comment by travisn** [comment]
Note that in v1.11 this behavior has changed so that the standby mgr will intentionally fail the readiness probe as described in  #11661.

**Comment by uhthomas** [comment]
Cool, thanks both. So it seems that this may be fixed in the latest release, v1.11.0?

**Comment by uhthomas** [comment]
Initially didn't seem to help, but after restarting all deployments in the namespace it seems to have the intended effect. Thank you!

![image](https://user-images.githubusercontent.com/9749173/222012077-25a7152d-4cc9-48fb-ab04-d7650a41d095.png)

**Comment by uhthomas** [comment]
https://github.com/rook/rook/pull/11829

**Comment by uhthomas** [comment]
Changing the standby behaviour does help. Is it possible to enable this by default?

```sh
❯ k -n rook-ceph exec rook-ceph-tools-56575d5549-7s854 -- ceph config set mgr mgr/dashboard/standby_behaviour "error"
```

**Comment by uhthomas** [comment]
Never mind, changing the standby behaviour does not help. Instead I'm presented with.


```json
{"status": "500 Internal Server Error", "detail": "Keep on looking", "request_id": "75403aef-59c2-406e-a740-aa7dba2c87d4"}                                                                                                                                                                                                                                                                                                                                                                                                       
```

**Comment by uhthomas** [comment]
Okay, so it does help, but only if the service is configured to target a specific daemon ID. I could see from the logs that some requests would go to "a" and succeed and others would go to "b" which would return a 500.

```yaml
selector:
  app:            "rook-ceph-mgr"
  ceph_daemon_id: "a"
  rook_cluster:   "rook-ceph"
```

**Comment by jmolmo** [comment]
@uhthomas , the following change fixes the problem:
https://github.com/rook/rook/pull/11845
Meanwhile, a workaround could be scale down to 1 mgr deployment.
