### ISSUE TITLE
Deployment violates PodSecurity

### ISSUE THREAD

**Issue by uhthomas** [rook/rook#11755]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

```
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "rook-ceph-operator" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "rook-ceph-operator" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "rook-ceph-operator" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/rook-ceph-operator created
```

I noticed similar problems here: https://github.com/tailscale/tailscale/issues/7359

The solution seems to be setting the correct `securityContext`.

deployment template (`.spec.template.spec`):

```yaml
securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```
container template (`.spec.template.spec.containers[]`):

```yaml
 securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
```

**Expected behavior:**

It should be possible to apply https://github.com/rook/rook/blob/v1.10.11/deploy/examples/operator.yaml.

**How to reproduce it (minimal and precise):**

Apply https://github.com/rook/rook/blob/v1.10.11/deploy/examples/operator.yaml in a Kubernetes cluster at v1.26.1.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Talos"
ID=talos
VERSION_ID=v1.3.5
PRETTY_NAME="Talos (v1.3.5)"
HOME_URL="https://www.talos.dev/"
BUG_REPORT_URL="https://github.com/siderolabs/talos/issues"
```
* Kernel (e.g. `uname -a`): not possible
* Cloud provider or hardware configuration: bare metal, Talos v1.3.5.
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"archive", BuildDate:"2023-01-18T22:38:55Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by uhthomas** [comment]
Looks like there are more PodSecurity problems.

```
$ kubectl -n rook-ceph describe replicaset.apps/rook-ceph-mon-a-canary-8446bdcb58
Events:
  Type     Reason        Age               From                   Message
  ----     ------        ----              ----                   -------
  Warning  FailedCreate  51s               replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-d4gbn" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
  Warning  FailedCreate  51s               replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-zw5nh" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
  Warning  FailedCreate  51s               replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-kkmdw" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
  Warning  FailedCreate  51s               replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-f2786" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
  Warning  FailedCreate  51s               replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-95j9j" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
  Warning  FailedCreate  51s               replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-jwzfz" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
  Warning  FailedCreate  50s               replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-jwcbw" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
  Warning  FailedCreate  50s               replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-h4mhs" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
  Warning  FailedCreate  49s               replicaset-controller  Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-n75x7" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
  Warning  FailedCreate  9s (x5 over 48s)  replicaset-controller  (combined from similar events): Error creating: pods "rook-ceph-mon-a-canary-8446bdcb58-8qhzd" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "rook-ceph-log", "rook-ceph-crash", "ceph-daemon-data")
```

**Comment by uhthomas** [comment]
So this can be worked around by setting the `pod-security.kubernetes.io/enforce=privileged` label to `privileged`.

```
kubectl label ns rook-ceph pod-security.kubernetes.io/enforce=privileged
```

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  labels:
    pod-security.kubernetes.io/enforce: privileged
```

**Comment by mmalyska** [comment]
@uhthomas I've added the label in namespace, but pods won't start. I'm running kubernetes v1.27 and still have errors about `Pod Security Admission`.

**Comment by uhthomas** [comment]
> @uhthomas I've added the label in namespace, but pods won't start. I'm running kubernetes v1.27 and still have errors about `Pod Security Admission`.

Could you post the exact error?

**Comment by mmalyska** [comment]
@uhthomas this is the error from pod
```
(combined from similar events): Error creating: pods "csi-cephfsplugin-provisioner-85b897f-g8drd" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "host-sys", "lib-modules", "host-dev")
```

I've added label on namespace
```
labels:
        pod-security.kubernetes.io/enforce: privileged
```

**Comment by uhthomas** [comment]
> @uhthomas this is the error from pod
> 
> ```
> 
> (combined from similar events): Error creating: pods "csi-cephfsplugin-provisioner-85b897f-g8drd" is forbidden: violates PodSecurity "baseline:latest": hostPath volumes (volumes "host-sys", "lib-modules", "host-dev")
> 
> ```
> 
> 
> 
> I've added label on namespace
> 
> ```
> 
> labels:
> 
>   pod-security.kubernetes.io/enforce: privileged
> 
> ```

Did you see this label after you saw the error? You could try restarting the pods?

**Comment by mmalyska** [comment]
I added label after I saw the errors. I tried restarting pods but to no avail.

**Comment by mmalyska** [comment]
@uhthomas It's is my mistake, label wasn't properly applied in namespace, now everything works as expected. Sorry for the trouble.

**Comment by bh-tt** [comment]
Aside from violating PodSecurity, it is good practice to set a number of security settings on all pods. Maybe an update to the chart allowing the user to specify the containerSecurityContext for the operator (and the tool pod, which also lacks security settings and even runs as root) is useful? That would be better than your PR @uhthomas  as any additional settings can be specified without further changes to the chart.

I could send a PR if there is interest.

**Comment by Borrelhapje** [comment]
Still useful to set security defaults on the operator and the ceph tools pod.

**Comment by subhamkrai** [comment]
> Still useful to set security defaults on the operator and the ceph tools pod.

@Borrelhapje have tried the latest version of rook https://github.com/rook/rook/blob/031f3c60e46ebf35cb8d82c13e30776d3b2d59b7/deploy/examples/operator.yaml#L603-L608

**Comment by bh-tt** [comment]
That refers to directly creating the deployment from manifests, I'm using the helm chart which does not allow setting any values: https://github.com/rook/rook/blob/031f3c60e46ebf35cb8d82c13e30776d3b2d59b7/deploy/charts/rook-ceph/templates/deployment.yaml#L34 . Let me create a PR, it's an easy fix.

**Comment by subhamkrai** [comment]
@bh-tt sounds good
