### ISSUE TITLE
PG_autoscaler is broken in case of pools overlapping roots

### ISSUE THREAD

**Issue by prazumovsky** [rook/rook#11764]
**Is this a bug report or feature request?**
* Bug Report

Since Ceph Pacific version Rook have an issue with overlapping roots for pools if CephCluster created with storageDevices which have deviceClass config specified:

```
2022-05-11T13:44:10.636+0000 7fdb9d799700  0 [pg_autoscaler ERROR root] pool 119 has overlapping roots: {-5, -1}
2022-05-11T13:44:10.640+0000 7fdb9d799700  0 [pg_autoscaler ERROR root] pool 121 has overlapping roots: {-40, -5, -1}
```

Which causes autoscale-status inaccessibility.

The following warning and documentation makes the issue clear for users: https://github.com/ceph/ceph/pull/47519.

**Deviation from expected behavior:**
1. "device_health_metrics" and ".mgr" pools, which are created by Rook automatically, conflicts with all osds created from storageDevices section with deviceClass defined. To resolve this issue we need to define one of the device class based crush rule instead of default one.
2. If CephObjectStore spec has no deviceClass specified in dataPool and/or metadataPool then "overlapping roots" error occurs. Rook CRD documentation has no clear explanation about that.
3. The same issue occurs for CephFilesystem dataPools. There is no explanation why it happens in documentation.

**Expected behavior:**
`ceph osd pool autoscale-status` returns a valid output and pg_autoscaler is working.

**How to reproduce it (minimal and precise):**
Create CephCluster with pacific version image (for example, v16.2.11), specify deviceClass config in storageDevices. For the second and third point of issue create CephObjectStore and CephFilesystem w/o deviceClass parameter in data/metadata pool spec section.

**Environment**:
* OS (e.g. from /etc/os-release):  Ubuntu 18.04 / 20.04
* Kernel (e.g. `uname -a`): 4.15 / 5.4
* Rook version (use `rook version` inside of a Rook Pod): v1.10.10
* Storage backend version (e.g. for ceph do `ceph -v`): v16.2.11
* Kubernetes version (use `kubectl version`): v1.21
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by travisn** [comment]
The `device_health_metrics` and `.mgr` pools are created automatically by Ceph with default configuration. If you have non-default settings to apply like the deviceClass, you'll need to create the [built-in mgr pool CR](https://github.com/rook/rook/blob/master/deploy/examples/pool-builtin-mgr.yaml) with your desired settings. 

So perhaps we need a paragraph in the docs for more details about what is needed for device classes when they are used. The notes about that topic are a bit scattered currently.

**Comment by degorenko** [comment]
The problem is mostly related to any pool, which is created without deviceClass - which is working fine on Octopus - and now, with new Pacific version autoscaler is broken, due to those pools have no deviceClass explicitly specified. So, i guess, it must have to at least specify in docs that need permanently set deviceClass parameter.

**Comment by travisn** [comment]
@degorenko Any suggestions on #11814 to clarify this issue?

**Comment by degorenko** [comment]
Posted some comments. Do we want to have described W/A somewhere in docs as well? How to resolve that issue?
