### ISSUE TITLE
Rook with external-Ceph-cluster: PVC creation fails due to 'rpc error: code = DeadlineExceeded'

### ISSUE THREAD

**Issue by shaan-2** [rook/rook#11783]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
PVC creation with ceph-rbd StorageClass is pending

**Expected behavior:**
PVC should be created with 'ceph-rbd StorageClass' and bounded to test Pod(mysql.yaml).

**How to reproduce it (minimal and precise):**

- Followed the steps as per https://rook.github.io/docs/rook/v1.9/CRDs/Cluster/external-cluster/ guide and had enabled the 'host networking' in operator.yaml and cluster-external.yaml.
- The CephCluster CR named 'rook-ceph-external' reflects 'Phase=Connected' & 'Message=Cluster connected successfully'
- `kubectl create -f mysql.yaml`
-- All manifest files are at https://github.com/rook/rook/tree/release-1.9/deploy/examples 

**Triage infos: All the console output are in 'Triage-info_01.txt' log-file.** [Triage-info_01.txt](https://github.com/rook/rook/files/10846163/Triage-info_01.txt)
- Although connectivity seems to be good from 'csi-rbdplugin' Container within 'pod/csi-rbdplugin-provisioner', but 'ceph -s' cmd says otherwise. 
-- Just for testing-only purpose, attempted the 'ceph -s' cmd inside the csi-rbdplugin-provisioner (leader)Pod's 'csi-provisioner' Container. It seems to be dependent on receiving 'monitor info from DNS SRV with service name: ceph-mon'. Not sure in "External Ceph" scenario, which Service in k8s would respond to it. Also, the k8s don't have any Services except 'service/rook-ceph-admission-controller'. 
- The 'ceph -s' just hangs in the 'Toolkit'. Likely reason is the hardcoded value of 'client.admin' at 'toolbox.sh. ?. 
-- Couldn't change it as '/usr/local/bin/toolbox.sh' is owned by 'root' in toolbox Container. But '-n' flag worked as a means of connectivity verification to 'external-Ceph cluster' from the k8s.

**Additional info:**
- Although currently am not using CephFS, I've created FS/volume/Data-pool and respective Ceph-principals for the same at my external-Ceph cluster. Log-file for csi-cephfsplugin-provisioner is provided below for completions - just in case of cross references.
- Ceph principals for 'client.healthchecker', 'csi-rbd-provisioner', 'csi-rbd-node', 'csi-cephfs-provisioner' & 'csi-cephfs-node' were created with appropriate 'caps'.

**Thanks much for the assistance**

**File(s) to submit**:
* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:
- rook-ceph-operator log = rook-ceph-operator-LOG.txt ; [rook-ceph-operator-LOG.txt](https://github.com/rook/rook/files/10846188/rook-ceph-operator-LOG.txt)
- csi-rbdplugin-provisioner (leader)Pod's 'csi-provisioner' Container log = rbdplugin-provisioner-csi-provisioner-LOG.txt [rbdplugin-provisioner-csi-provisioner-LOG.txt](https://github.com/rook/rook/files/10846197/rbdplugin-provisioner-csi-provisioner-LOG.txt)
- csi-rbdplugin Pod's 'driver-registrar' Container log = csi-rbdplugin-driver-registrar-LOG.txt  [csi-rbdplugin-driver-registrar-LOG.txt](https://github.com/rook/rook/files/10846199/csi-rbdplugin-driver-registrar-LOG.txt)
- csi-cephfsplugin-provisioner (leader)Pod's 'csi-provisioner' Container log = cephfsplugin-provisioner-csi-provisioner-LOG.txt 
[cephfsplugin-provisioner-csi-provisioner-LOG.txt](https://github.com/rook/rook/files/10846203/cephfsplugin-provisioner-csi-provisioner-LOG.txt)
- Ceph/rbd cmds inside csi-rbdplugin-provisioner (leader)Pod's 'csi-provisioner' Container
- triage infos = Triage-info_01.txt  [Triage-info_01.txt](https://github.com/rook/rook/files/10846163/Triage-info_01.txt)

* Operator's logs, if necessary
rook-ceph-operator-LOG.txt  (https://github.com/rook/rook/files/10846188/rook-ceph-operator-LOG.txt)

* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:
Triage-info_01.txt

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
A 3 node k8s: v1.24.10 with CNI = Flannel
* Kernel (e.g. `uname -a`):
node- Kernel & OS = `5.4.0-139-generic #156~18.04.1-Ubuntu` 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
Rook v1.9.13
ROOK_CSI_CEPH_IMAGE="quay.io/cephcsi/cephcsi:v3.6.2" (default)
ROOK_CSI_NFS_IMAGE="registry.k8s.io/sig-storage/nfsplugin:v4.0.0" (default)
ROOK_CSI_REGISTRAR_IMAGE="registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1" (default)
ROOK_CSI_PROVISIONER_IMAGE="registry.k8s.io/sig-storage/csi-provisioner:v3.1.0" (default)
ROOK_CSI_ATTACHER_IMAGE="registry.k8s.io/sig-storage/csi-attacher:v3.4.0" (default)
ROOK_CSI_SNAPSHOTTER_IMAGE="registry.k8s.io/sig-storage/csi-snapshotter:v6.0.1" (default)
ROOK_CSI_KUBELET_DIR_PATH="/var/lib/kubelet" (default)
CSI_VOLUME_REPLICATION_IMAGE="quay.io/csiaddons/volumereplication-operator:v0.3.0" (default)
ROOK_CSIADDONS_IMAGE="quay.io/csiaddons/k8s-sidecar:v0.4.0" (default)
* Storage backend version (e.g. for ceph do `ceph -v`):
External Ceph cluster: 15.2.14 (Octopus)
* Kubernetes version (use `kubectl version`):
K8s v1.24.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
On-prem k8s.
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
Triage-info_01.txt [Triage-info_01.txt](https://github.com/rook/rook/files/10846163/Triage-info_01.txt)

**Comment by parth-gr** [comment]
Can you share the rbd-provisioner pod logs,
And also rbd-pvc pod decribe

**Comment by shaan-2** [comment]
@parth-gr Thanks for the help. My bad, 'rbdplugin-provisioner-csi-provisioner-LOG.txt' is now attached.
[rbdplugin-provisioner-csi-provisioner-LOG.txt](https://github.com/rook/rook/files/10851777/rbdplugin-provisioner-csi-provisioner-LOG.txt)

Please view logs at Triage-info_02.txt. Please note that I had deliberately marked 'ceph-rbd' SC as the 'default'.

I had tried initially without ```host networking``` , it didn't worked then, so re-tried with 'host networking'.  Also, even without ```host networking``` enabled, the mons were reachable via ```curl 10.188.185.179:3300 2>/dev/null``` off 'csi-rbdplugin' and toolbox.
[Triage-info_02.txt](https://github.com/rook/rook/files/10852011/Triage-info_02.txt)

**Comment by shaan-2** [comment]
@parth-gr Please find below rbdplugin-provisioner-csi-provisioner-LOG. Thanks.
```
Defaulted container "csi-provisioner" out of: csi-provisioner, csi-resizer, csi-attacher, csi-snapshotter, csi-rbdplugin
I0227 17:57:07.463270       1 csi-provisioner.go:139] Version: v3.1.0
I0227 17:57:07.463487       1 csi-provisioner.go:162] Building kube configs for running in cluster...
I0227 17:57:09.403014       1 common.go:111] Probing CSI driver for readiness
I0227 17:57:09.421194       1 csi-provisioner.go:278] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I0227 17:57:09.422062       1 leaderelection.go:248] attempting to acquire leader lease rook-ceph/rook-ceph-rbd-csi-ceph-com...
I0227 17:57:09.443737       1 leaderelection.go:258] successfully acquired lease rook-ceph/rook-ceph-rbd-csi-ceph-com
I0227 17:57:09.551094       1 controller.go:811] Starting provisioner controller rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-5dcc5cb8b4-hs6kh_0329bef9-cafd-4aac-b98a-e1c330c7009b!
I0227 17:57:09.551351       1 volume_store.go:97] Starting save volume queue
I0227 17:57:09.552324       1 clone_controller.go:66] Starting CloningProtection controller
I0227 17:57:09.553351       1 clone_controller.go:82] Started CloningProtection controller
I0227 17:57:09.653433       1 controller.go:860] Started provisioner controller rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-5dcc5cb8b4-hs6kh_0329bef9-cafd-4aac-b98a-e1c330c7009b!
I0227 21:43:35.326297       1 controller.go:1337] provision "default/mysql-pv-claim" class "ceph-rbd": started
I0227 21:43:35.334601       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"mysql-pv-claim", UID:"aacbded2-b7eb-4c39-9cab-38015bb45436", APIVersion:"v1", ResourceVersion:"14121261", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/mysql-pv-claim"
W0227 21:46:05.364396       1 controller.go:934] Retrying syncing claim "aacbded2-b7eb-4c39-9cab-38015bb45436", failure 0
I0227 21:46:05.366390       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"mysql-pv-claim", UID:"aacbded2-b7eb-4c39-9cab-38015bb45436", APIVersion:"v1", ResourceVersion:"14121261", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ceph-rbd": rpc error: code = DeadlineExceeded desc = context deadline exceeded
E0227 21:46:05.403178       1 controller.go:957] error syncing claim "aacbded2-b7eb-4c39-9cab-38015bb45436": failed to provision volume with StorageClass "ceph-rbd": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0227 21:46:05.865139       1 controller.go:1337] provision "default/mysql-pv-claim" class "ceph-rbd": started
I0227 21:46:05.866848       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"mysql-pv-claim", UID:"aacbded2-b7eb-4c39-9cab-38015bb45436", APIVersion:"v1", ResourceVersion:"14121261", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/mysql-pv-claim"
W0227 21:46:05.879560       1 controller.go:934] Retrying syncing claim "aacbded2-b7eb-4c39-9cab-38015bb45436", failure 1
E0227 21:46:05.879620       1 controller.go:957] error syncing claim "aacbded2-b7eb-4c39-9cab-38015bb45436": failed to provision volume with StorageClass "ceph-rbd": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-aacbded2-b7eb-4c39-9cab-38015bb45436 already exists
I0227 21:46:05.879645       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"mysql-pv-claim", UID:"aacbded2-b7eb-4c39-9cab-38015bb45436", APIVersion:"v1", ResourceVersion:"14121261", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ceph-rbd": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-aacbded2-b7eb-4c39-9cab-38015bb45436 already exists
I0227 21:46:06.880793       1 controller.go:1337] provision "default/mysql-pv-claim" class "ceph-rbd": started
I0227 21:46:06.884203       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"mysql-pv-claim", UID:"aacbded2-b7eb-4c39-9cab-38015bb45436", APIVersion:"v1", ResourceVersion:"14121261", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/mysql-pv-claim"
I0227 21:46:06.892277       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"mysql-pv-claim", UID:"aacbded2-b7eb-4c39-9cab-38015bb45436", APIVersion:"v1", ResourceVersion:"14121261", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ceph-rbd": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-aacbded2-b7eb-4c39-9cab-38015bb45436 already exists
W0227 21:46:06.892587       1 controller.go:934] Retrying syncing claim "aacbded2-b7eb-4c39-9cab-38015bb45436", failure 2
E0227 21:46:06.892670       1 controller.go:957] error syncing claim "aacbded2-b7eb-4c39-9cab-38015bb45436": failed to provision volume with StorageClass "ceph-rbd": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-aacbded2-b7eb-4c39-9cab-38015bb45436 already exists
<trimmed the repeat msgs>
W0228 01:44:05.996349       1 controller.go:934] Retrying syncing claim "aacbded2-b7eb-4c39-9cab-38015bb45436", failure 56
E0228 01:44:05.996625       1 controller.go:957] error syncing claim "aacbded2-b7eb-4c39-9cab-38015bb45436": failed to provision volume with StorageClass "ceph-rbd": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-aacbded2-b7eb-4c39-9cab-38015bb45436 already exists

**Comment by shaan-2** [comment]
Reinstalled from scratch and it worked as expected - PV & PVC info below. The observation made on the Toolbox earlier still holds true - its a minor issue and the shared workaround meets the need. 
Am closing this issue, hope you are ok with that. Thanks for your time in looking into this issue - much appreciated.

Example YAMLs: [mysql.yaml](https://github.com/rook/rook/blob/release-1.9/deploy/examples/mysql.yaml) & [wordpress.yaml](https://github.com/rook/rook/blob/release-1.9/deploy/examples/wordpress.yaml).
**Successful PV/PVC creation:**
```
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mysql-pv-claim   Bound    pvc-a5fdb834-180c-4c72-b53e-b99767523386   20Gi       RWO            ceph-rbd       153m
wp-pv-claim      Bound    pvc-cb4d699f-6b34-4b1d-896b-6d19310c6d07   20Gi       RWO            ceph-rbd       152m
```

```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS   REASON   AGE
pvc-a5fdb834-180c-4c72-b53e-b99767523386   20Gi       RWO            Delete           Bound    default/mysql-pv-claim   ceph-rbd                153m
pvc-cb4d699f-6b34-4b1d-896b-6d19310c6d07   20Gi       RWO            Delete           Bound    default/wp-pv-claim      ceph-rbd                152m
```

**Comment by shaan-2** [comment]
Marking the issue closed. Thanks @parth-gr .

**Comment by Rage8327** [comment]
I am having this exact same issue today. Reinstalled multiple times and can't figure it out.

**Comment by Madhu-1** [comment]
@edbrk please refer to https://rook.io/docs/rook/latest/Troubleshooting/ceph-csi-common-issues/, it should help you. Most of the time, it could be network problem
