### ISSUE TITLE
device Filter issue when one disk mount to 2 VMs 

### ISSUE THREAD

**Issue by guu13** [rook/rook#11786]
1.  I create 2 disks (sdb  sdc) ,  
2. I mount them to  2 VMS( node2 node3) 
3. I can see 2 disks  both node2 and node3
4. I  joined 2 nodes to my k8s clusters
5. I  create rook ceph cluser used bellow cluser.yaml  ,  useAllNodes/useAllDevices  flase  
<img width="223" alt="image" src="https://user-images.githubusercontent.com/95571913/221805442-d4c8f802-8f4e-45c4-b211-8a4925d88184.png">
6.  I think : deployment osd on node2 should manage disk sdb  ,  deployment osd on node3 should manage disk sdc , but not worked
7. if I just mount sdb to node2  , mount sdc to node3 ,  it worked well .

please help 

this func .........
func getAvailableDevices(context *clusterd.Context, agent *OsdAgent) (*DeviceOsdMapping, error) {

**Comment by parth-gr** [comment]
>6. I think : deployment osd on node2 should manage disk sdb , deployment osd on node3 should manage disk sdc , but not worked 
What happened in this scenario then?

Can you please share the operator pod logs.

**Comment by uhthomas** [comment]
I would advise using a [persistent block device name](https://wiki.archlinux.org/title/persistent_block_device_naming) if possible. The persistent name can be found with `ls -l /dev/disk/by-id/`.

See https://github.com/uhthomas/automata/blob/0f3a179552717c8f59e2abc76ed52eab124e6d01/k8s/unwind/rook_ceph/ceph_cluster_list.cue#L77-L88 for an example.

**Comment by guu13** [comment]
one  node managed 2 disks ， other node no osd running

**Comment by uhthomas** [comment]
I don't believe it's possible for an OSD on one node to use a device on another. I would suggest instead mounting your other disk to the other node.

**Comment by guu13** [comment]
> I don't believe it's possible for an OSD on one node to use a device on another. I would suggest instead mounting your other disk to the other node.

My disk is attached to two nodes at the same time

**Comment by uhthomas** [comment]
I would advise not doing that.

**Comment by uhthomas** [comment]
Regardless, using a persistent block device name should help with your situation. `/dev/sdb` and `/dev/sdc` are not guaranteed to be the same block device between reboots, and I imagine that mounting the block device to two node simultaneously may also result in a situation where `sdb` and `sdc` are mixed up.

**Comment by guu13** [comment]
> I would advise not doing that.

I want to enhance rook's high availability capability. If one node down, it can be dispatched to another node.

**Comment by guu13** [comment]
> Regardless, using a persistent block device name should help with your situation. `/dev/sdb` and `/dev/sdc` are not guaranteed to be the same block device between reboots, and I imagine that mounting the block device to two node simultaneously may also result in a situation where `sdb` and `sdc` are mixed up.

got it

**Comment by uhthomas** [comment]
> > I would advise not doing that.
> 
> I want to enhance rook's high availability capability. If one node down, it can be dispatched to another node.

I appreciate that, but this is the wrong way to do it. High availability is achieved by provisioning more nodes and more block devices. If you haven't already, I'd recommend reading into Ceph more.

https://docs.ceph.com/en/quincy/start/intro/

**Comment by guu13** [comment]
> > > I would advise not doing that.
> > 
> > 
> > I want to enhance rook's high availability capability. If one node down, it can be dispatched to another node.
> 
> I appreciate that, but this is the wrong way to do it. High availability is achieved by provisioning more nodes and more block devices. If you haven't already, I'd recommend reading further into how Ceph achieves high availability.
> 
> https://docs.ceph.com/en/quincy/start/intro/

I understand what you mean, but I know that some storage,  support some special physical storage server, this server has two OS , can see all the disks at the same time, one system for some reason down, the disk is taken over by the other system.  so I want to try ......
![image](https://user-images.githubusercontent.com/95571913/222018459-12783acd-1a79-4b8c-bf1c-08bbe519834d.png)
