### ISSUE TITLE
Rook cannot deal with kubernetes cluster node deletion automatically

### ISSUE THREAD

**Issue by zeddit** [rook/rook#11784]
I am going to replace a node in k8s cluster, which means I will delete it and add a new one with some same configurations, e.g. hostname and IP address, and this node works as a ceph host with osds on it.

So I am trying to first remove rook-ceph things on this node following the guide of "Remove an OSD" in the official website, and then I delete the node from k8s cluster.

However, after doing this, in ceph toolbox, I still can find the host information of the one deleted already. e.g. when using `ceph orch host ls`, the node away from the k8s cluster is not removed at all.

Then I followed the official ceph guide for host management of removing a host with `ceph orch host rm  hostname1`, it tells me that 'Error ENOENT: This Orchestrator does not support orch host rm'.

I am worrying about if rook can handle this situation correctly that I add the new host to k8s cluster with such remaining information and states in the rook-ceph system. 

And what's the right way to remove a node and add node to rook without incurring system inconsistence? great thanks.

**Comment by parth-gr** [comment]
I guess you should stop worrying about the cleanup and add a new node and rook will take care of the rest and new mapping.

THe `ceph orch host ls` listing it maybe because the data isn't refreshed, maybe you can re-start the operator.

@travisn for more suggestions

**Comment by travisn** [comment]
`ceph orch` command are not generally supported by rook. If you want to remove the host from the CRUSH map you can instead use:
```
ceph osd crush remove <host>
```
But if you're just going to create new OSDs on a new host with the same name, you can leave that host in the crush map and the new OSDs will just show up under it when they are created.

**Comment by travisn** [comment]
Also note that if you are going to replace nodes frequently (e.g. in a cloud environment), it's recommended instead to use portable OSDs in a [PVC-based cluster](https://rook.io/docs/rook/latest/CRDs/Cluster/pvc-cluster/). Then replacing nodes is simple since you don't have to replace mons or OSDs.
