### ISSUE TITLE
mgr: upgrade image version of  the rook operator, mgr will restart

### ISSUE THREAD

**Issue by zhucan** [rook/rook#11799]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Only upgrade image's version of the rook operator from v1.9.8 to v1.10, mgr will restart

**Expected behavior:**
mgr will not restart

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:
patch: 
`op-k8sutil: {"metadata":{"annotations":{"banzaicloud.com/last-applied":"UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzsWntv2zgS/yo8boDuHizbeTbxwji4sdsam9g+x+ndXp0zaGks8UKROpJy4s3mux+GlB9xlDTp7vafW6AIZIrz4MxvXlTvaAqWRcwy2rijgk1BGHxiWUYbVCt1HYSQJUEaa1rB1ep1PgUtwYKpclULVZopCdLSBsWNociNBW2q+KOK9FWuyik1MAtRMF08EKQy0MyqcmlcGstkCLRBp6UbUiZZ/EqmkqVQaP/kMTOmbaBmm0xpxZPMQRuuJG3Q3aPqXnW3HtSLV5OIQarkhEeFvpuLdpGhVC9w61y46J+ctLWE+W51t17d3QsOqvFedFyfnbw9OqhGXNtFsRmVXZ42wJOZjDm+m3rj86Tw1INX9xVaWOOB5wNU5Slm6kaCHsIMNMgQDG18RvTwTyulN5FQm+/SCp0KFV73ka4NAqzbZnUOFRoqabUSAvXyK9dcovlOIUtOC40fK0krNHdWZvX60fH+EQtO6sf14IAdzQJ2dAjBCdT36m+jKUwPGL2/uq9Qk0GIQNeQCR4yQxu7FWpAQIg4adzRlNkwOftCQJS6+VlvltsdFbKaWYgXKKwAxxB8kKBfLKSZwOfGw5BlUirL0IZOzUyrFGwCuYet0hiYJ3vH+7Sy9c6EmjkpaGeU8Gfwvzr4f6cI/6OCdgPmbDbjkluHrkxFLWl5a2NJw39zriFq55rL+CJMIMoFl3E3lmq13LmFMPfR+rmoFRevDZhnQ8CqTAkVL34C9OBDJyTKWHfM+yvciomCcQm6SDg6xgcaBDPDo+YJ7B/vHb6dBicn7DA4YNP94Dg8OAim+7Oj3fCA7dePMCCC4BoWeLJmDWxYQz1qxUpgrNKw/OX2ChUHVgXGRqB100UNLoPWZcupkkFxzqcocdmvBZmGGb9tRjDNY+JeRjBjubBL2hkX0JwxYeDB2xIpWztxB9quufP9sN//aXLaGXycnPd7k4/9i9EPqy2IBM5EkEI6BW0e7e72uqNu62xy3jl/1xleeEIeNafuwYDNDehmAVW3EGuVZ+uVUHCQqHAubZDzqFl/vByvlmdKAzKQEb1CZ6cpwzLweR2oVxUKcu6cX6D/tN8btbq9znDSPW996NAKnTORu7iAuBoBZFrlFqqM11Y/giyfCl64Hv805kUVp/eVFedBvz3ptc5XLN9rlSLEZxxENITZ6nnAbIIhX+TnqgfsfQmri0Hr9Ov4+dzwgGmv3+68SkHMClWpIuiVKnjeOe8Pf56cdc+7o22WGozKdQjvN1hHfM4NJgGK3lvuoA0qeMqtqaaQKr14Us6w8/fLzsVvk4QJDMwzsk4Hl19zoN3SA4VZXi7hdz3KIykuGi8vOpNhq9fun096/d7pJs6LSr7a/zjgtxUz2GHYn2BRKHXtMi9WL8wZJZ1WECo54/FDvZ5NFS8XWeSgSZGDXiW9P+gMW6P+8HFwbdXKEqVPzy4vRp3h5HTYnnzqDC+6/d4G8Xz3y1SbsfesPMRJd/DiMLXM5qaaqag7wDNfVShPWfzVKa0gH+RCDJTgIRq+O+spO9BgsI2rUMHnIMGYgVZT12vCrW8gNnIw5t0KDTitUOOSe4hjQG6z5pjufI8iSRCwKOUy8K0QqelcrhXC/F2dVplR18QfkeyN83p9H/Dv3tHuD2M6ljps7vxtLPmMfCY7OiSBBFInVz8Sm4AcS0IgTBQZu4pACjkJMGETEiYQXpMZ4wIicsNtgjRkpoRQN1zGBHXNbQOlrNjs4OKYkl+JgYgEQN6Y2r9rXi1Si9+4rbfcoi5jOeMUh4gCsW0QbHEBoZIRzhH1Cs1AcxWtlw4r1PIUVG43tq0bN98bYbfu25lVdzNwDfzRcb2+vVcrq0IlaIOOTgcOZ1tE2PSviBJrsyAFq3loXkR9fHCwpo6YSaaK6aiE9Gqdu7Dtw5YTwlxzuzhV0sKt9VMJn3MBMUS04VoTN+8wbfPsT6C9BGgoItcwSjSYRImINo5egb76Y/Qd3lfoXIk8hXNsvTzsXBdW5J5VR7ydhl0GDtQctOYRuNLFor4UCz+xI5ZK+Wx11mXZ3U0twbrn/gLnOdM1oeJSLZGdUDEtJ+LTAiSamVJS/+J54jTWHmXTNQf322MkcBM6xseN0tdcxm2uH2mNEpazS3EMH983OEwFLLR8DiW9ri9DRQXqtjdqz8tuQLYLWsHp5XVs2P3UGnV+Qy3bZnj57qx7+rvwK22xnz0Ndi2dXnvQ7/ZGj/oVD/hzlm23LM6/ZShWMgAZZYpjXD3RKF1edIZlHXt5d+T44oTl+JTLfErSab/3vvth0v/UGQ677U2DuNBEHjV/xtoyqKv4+5GV2q2Lj+/6rWF70um13p11NlHn580Su3ZH/WG39+HFJJeDtsNVb9QZfmqdbezfPTQlKnXQd1uwnZY3bI9bO5fRi9tVsrq9JRkL+YyHdLPf+iXJQ+ZLS8DS6OigMd+r7+3X9+u71cOXNFaFOg/i+rWl09+I6ly2zKUBTRv1L2bxZcZ6CJWH+cpXUI+8x1n3yncHq6Jcm3JZm/q8GdziH3fRkC7r81gW7XG30xtNuu3muhKP5aAz7Pbb3dPu6OdmxLhYjOVZ/8Nk2B+h1x3h++5Zx9/HCBVrZZmFauQM7/eet/45uej+q9Osj6Wna74dy7H8jkDErSvAK0Iy4wKIVURJsSDFGiM4/qKHl9VcqBjplU1A33AD5AbIDRdig5FQsWNmXJlXuSUahGIRVvkQNLZOBTeDrGzCDUl5nFiSsCwDSW4SkCTNheWZgOVWonNJlHRKG5YCSVmYcAlj6XoDTsbU/PrXqlDxrzsPrerWxhT7iTIDYseBemjIBAuBFPdFxNncdyoxdvoEkwrhMsttITPgMvA0Y2pqbn9tZ8NttfjlUgvbhQjIykqHt2SmNGFCkI2OynjrE5swSfQ0ClKutdKlShVs3y4fdrweX9bMtXjFjiWMxpT8pUnGtD6m655vbL8jLHLOTdmt4b8AeUBEmAfagU2I4BKImm0Bz2dUjz9n7gPiLm4MojFl3DXbhMsIpL+9R6GPznrAyXi8/leqy/OHnnE8+E3i4kDn8COJlD/fDZBIyTcWvRHCWn2N6k9zixsEbAfUlEumFyRhMhKeSBefH8iUof7KY+qN8ahyvvb9KA+5XRAmI4KHQCXWbINgDnqqDDzrQGsEQEZ2D9OxjBSGCf0GI3GRKoWKg1CJ4r77tal7OfVYu1jm8W/Tfv/xTfIV1slImpX9iu9077k29h/cJh+VsT1XWhL/hA3x0go4xJw+dZlfgMJdCWs0sPFl0/mwONH2CcuVf7J137peTtTNtwSVkxesZm83MwQR/3p8fRtQ/b/PdIj4THPlHCKYMT2/1SyMhXT1RSbU3PKQCe9Ny7RdwaElbtjCUPSrnvMQWqGrkr0S87nbD6ZhoFUIXlTxfdBHkFUC9PIL8Oc7CrMZhJY2aE/5L3boUD9HSBXB1sfNXGpgYcKmAretvpU2aOeWG4sarvlv3B5cLaFmNsfSJ9CUafUfCC3i9I6uUP15Y7bCF9xC6peLocff9VZoqiKgjb2TvQrNvNPQNMWQcvU8lO/d58K7L+OyaH9XI1iZJzYIHFNMZx5Gd0vNHjTc66675nH7NJ5fwWqJ4+cQDmlmF+7C4e7+GSCvDROWDAJrkzxyDe5e7Sv09b+rKwtdVZ40pZtWr+79f3vAOR71vP9fAAAA//9QSwcIVDJEZs4KAACMJAAAUEsBAhQAFAAIAAgAAAAAAFQyRGbOCgAAjCQAAAgAAAAAAAAAAAAAAAAAAAAAAG9yaWdpbmFsUEsFBgAAAAABAAEANgAAAAQLAAAAAA=="}},"spec":{"template":{"spec":{"$setElementOrder/containers":[{"name":"mgr"},{"name":"watch-active"},{"name":"log-collector"}],"containers":[{"image":"zhucan/ceph-amd64:v20230301.5","name":"watch-active"}]}}}}`

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): 
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 
* Storage backend version (e.g. for ceph do `ceph -v`): v16.2.10
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by zhucan** [comment]
Because of the image version changed.

**Comment by travisn** [comment]
Across minor version updates, there are frequently pod spec changes in the daemons anyway, so I don't think it can be a goal to always avoid daemon restarts with minor version updates. For the watch-active sidecar, you're right that will cause the mgr to be restarted whenever there is a rook update. In 1.11 the watch-active sidecar was removed, though we may need to revert that due to #11791 if we can't find a solution.

**Comment by rkachach** [comment]
Closing since the readiness probe related chagnes were reverted by https://github.com/rook/rook/pull/11829

**Comment by zhucan** [comment]
> Closing since the readiness probe related chagnes were reverted by #11829

@rkachach Did you test on it with the reverted  branch?
