### ISSUE TITLE
Validate topology labels before cluster creation

### ISSUE THREAD

**Issue by chrisludwig** [rook/rook#11800]
This is a follow-up as #9419 seems only partly solved.

We are facing the same issues in regards to the following labels.

- topology.rook.io/chassis
- topology.rook.io/rack
- topology.rook.io/room
- topology.rook.io/row

We ended up with equal values for these in some environments, which led to the same error.

```
2023-03-01T06:07:23.434+0000 7f0a6061cf40 -1 osd.0 0 mon_cmd_maybe_osd_create fail: '(22) Invalid argument': (22) Invalid argument
2023-03-01T06:07:23.434+0000 7f0a6061cf40 -1 osd.0 0 init unable to update_crush_location: (22) Invalid argument
```

Introducing validation for only `region` and `zone` labels therefore seems insufficient.

_Originally posted by @chrisludwig in https://github.com/rook/rook/issues/9419#issuecomment-1449592563_

**Comment by travisn** [comment]
Perhaps in [this loop](https://github.com/rook/rook/blob/release-1.10/pkg/operator/ceph/cluster/osd/topology.go#L110-L117), if a duplicate value is found in the label values, it could be skipped, similar to the zone and region check. This would only check if there is a duplicate at a different level for the same OSD. For example, if there is an OSD on a node labeled with `rack=foo` and `room=foo`, this would resolve the issue. 

The harder question is if the duplicate values are found on different nodes, which this approach would not resolve.

**Comment by chrisludwig** [comment]
Yes, this should be sufficient. It seems to be true that "a value must be unique among all topology keys for a given OSD" (citing [JensErat](https://github.com/rook/rook/issues/9419#issuecomment-1024701126)). Therefore checking for duplicate values on that level should solve the issue.

Of course we have lots of duplicate values for topology labels across nodes, e.g. if they are located in the same rack or room. This is not causing an issue here as only the labels of the specific node holding the OSD are added to the container args.

```
spec:
  containers:
  - args:
[...]
    - ceph
    - --crush-location=root=default host=foo chassis=bar rack=01 room=001 row=01
```
The real nasty thing here is the deployment of already created OSDs will be updated accordingly and pods happily continue to run. Once you try to exchange a disk or add a new node to the cluster newly created OSDs will fail to come up though.

Easy to get around while changing node labels, but pretty hard to debug in the first place. Providing some useful error message in the logs would be great.
