### ISSUE TITLE
RBD and CephFS PVCs take up to 10 seconds to mount

### ISSUE THREAD

**Issue by lbogdan** [rook/rook#11805]
> **⚠️ Note:** This is somewhere between a bug and a feature request, I guess. I deleted the issue's template, as I did some troubleshooting, and this seems to be a generic issue.

Just in case, I'm on (almost, a new patch version was released overnight) latest Kubernetes `1.26.1` and `rook` `1.10.12`.

When creating pods that have RBD or CephFS PVC mounts, mounting (more specifically, attaching) them can take up to 10 seconds (a random amount of time between 0 and 10s, depending on when the pod is created and `kubelet` updates its status), delaying the pod start by that amount of time.

This seems to be a known Kubernetes issue, here's a few references:

- https://github.com/kubernetes/kubernetes/blob/8f94681cd294aa8cfd3407b8191f6c70214973a4/pkg/volume/util/operationexecutor/operation_generator.go#L1551-L1560

  ```golang
  		if !volumeToMount.ReportedInUse {
  			// If the given volume has not yet been added to the list of
  			// VolumesInUse in the node's volume status, do not proceed, return
  			// error. Caller will log and retry. The node status is updated
  			// periodically by kubelet, so it may take as much as 10 seconds
  			// before this clears.
  			// Issue #28141 to enable on demand status updates.
  			eventErr, detailedErr := volumeToMount.GenerateError("Volume has not been added to the list of VolumesInUse in the node's volume status", nil)
  			return volumetypes.NewOperationContext(eventErr, detailedErr, migrated)
  		}
  ```

- https://github.com/kubernetes/kubernetes/issues/28141

- https://github.com/kubernetes/kubernetes/issues/89313

After a long troubleshooting session, of which I won't go into details, here's what I found out: 

- `rook-ceph-operator` creates `CSIDriver`s resources, for both the `rbd` and `cephfs` CSI drivers, having hardcoded `attachRequired: true`;

- because of that, the attacher-detacher controller in `kube-controller-manager`, the `kubelet` running on the node the pod was scheduled to, and the `csi-attacher` container of `csi-[rbd|cephfs]plugin-provisioner` go through the whole PVC node attach / detach dance, BUT:

- neither `rbd` nor `cephfs` CSI plugin controller advertise the `PUBLISH_UNPUBLISH_VOLUME` capability, so `csi-attacher` uses its [`trivialHandler`](https://github.com/kubernetes-csi/external-attacher/blob/32c6854482d3d1d27ffaeeaf3a37dcc8bfb94506/cmd/csi-attacher/main.go#L231) to handle attaching / detaching, which is mostly a no-op: 

  ```golang
  // trivialHandler is a handler that marks all VolumeAttachments as attached.
  // It's used for CSI drivers that don't support ControllerPublishVolume call.
  // It uses no finalizer, deletion of VolumeAttachment is instant (as there is
  // nothing to detach).
  ```

- there was an attempt to remove the `csi-attacher` container and set `attachRequired: false`, just for the `cephfs` CSI plugin, in https://github.com/rook/rook/pull/10664, but was quickly reverted in https://github.com/rook/rook/pull/10694, because of https://github.com/rook/rook/issues/10692 ;

My question is, is there a reason for setting `attachRequired: true`, except for that (I'd say narrow) use case of not allowing CephFS RWO PVCs to be mounted on multiple nodes at the same time? Should that maybe be configurable?

I could think of, and tested, two workarounds:

- lower the `kubelet`'s `nodeStatusUpdateFrequency` to 1 second (from the 10 seconds default), which, while it works to lower the random delay to max. 1s, doesn't seem like a good idea to 10x the API server load with node updates, especially in a big cluster;

- recreate the `CSIDriver` resources with `attachRequired: false`; the field is immutable, so recreating is required; unfortunately that will kind of break `rook-ceph-operator` after a restart:

  ```log
  ceph-csi: failed to reconcile failed to configure ceph csi: failed to start ceph csi drivers: failed to create CSI driver object for "rook-ceph.rbd.csi.ceph.com": CSIDriver.storage.k8s.io "rook-ceph.rbd.csi.ceph.com" is invalid: spec.attachedRequired: Invalid value: true: field is immutable
  ```

Related Slack thread: https://rook-io.slack.com/archives/CG3HUV94J/p1677660821520389 .

**Comment by lbogdan** [comment]
<details>

  <summary>Slack thread contents, for reference:</summary>

lbogdan
  [4 hours ago](https://rook-io.slack.com/archives/CG3HUV94J/p1677660821520389)
Is there any reason that the CSIDrivers created by rook have attachRequired: true, although neither rbd nor cephfs CSI plugin controllers have the PUBLISH_UNPUBLISH_VOLUME capability?
6 replies


lbogdan
  [4 hours ago](https://rook-io.slack.com/archives/CG3HUV94J/p1677661396289129?thread_ts=1677660821.520389&cid=CG3HUV94J)
From what I understand, in this case the attach / detach operations are handled by csi-attacher's trivialHandler (https://github.com/kubernetes-csi/external-attacher/blob/32c6854482d3d1d27ffaeeaf3a37dcc8bfb94506/cmd/csi-attacher/main.go#L231), which from the comments, look like no-ops:
// trivialHandler is a handler that marks all VolumeAttachments as attached.
// It's used for CSI drivers that don't support ControllerPublishVolume call.
// It uses no finalizer, deletion of VolumeAttachment is instant (as there is
// nothing to detach).
(https://github.com/kubernetes-csi/external-attacher/blob/32c6854482d3d1d27ffaeeaf3a37dcc8bfb94506/pkg/controller/trivial_handler.go#L27-L34) (edited) 


lbogdan
  [4 hours ago](https://rook-io.slack.com/archives/CG3HUV94J/p1677661451668369?thread_ts=1677660821.520389&cid=CG3HUV94J)
This wouldn't normally be an issue, but I run into this: https://github.com/kubernetes/kubernetes/issues/89313 "Delay in attaching a volume because of 10s default kubelet syncNodeStatus interval". (edited) 


lbogdan
  [3 hours ago](https://rook-io.slack.com/archives/CG3HUV94J/p1677663182120809?thread_ts=1677660821.520389&cid=CG3HUV94J)
Related: https://kubernetes-csi.github.io/docs/skip-attach.html
Volume drivers, like NFS, for example, have no concept of an attach (ControllerPublishVolume). However, Kubernetes always executes Attach and Detach operations even if the CSI driver does not implement an attach operation (i.e. even if the CSI Driver does not implement a ControllerPublishVolume call).
This was problematic because it meant all CSI drivers had to handle Kubernetes attachment. CSI Drivers that did not implement the PUBLISH_UNPUBLISH_VOLUME controller capability could work around this by deploying an [external-attacher](https://kubernetes-csi.github.io/docs/external-attacher.html) and the external-attacher would responds to Kubernetes attach operations and simply do a noop (because the CSI driver did not advertise the PUBLISH_UNPUBLISH_VOLUME controller capability).
[...]
Specifically the attachRequired field instructs Kubernetes to skip any attach operation altogether.


lbogdan
  [3 hours ago](https://rook-io.slack.com/archives/CG3HUV94J/p1677663573050739?thread_ts=1677660821.520389&cid=CG3HUV94J)
As a workaround, I recreated the CSIDriver objects with attachRequired: false (the field is immutable, so I had to recreate them), and now PVCs mount and pods start immediately, instead of after a random wait between 0 and 10s, depending on when the pod is created and the node status is updated.


lbogdan
  [2 hours ago](https://rook-io.slack.com/archives/CG3HUV94J/p1677665624723909?thread_ts=1677660821.520389&cid=CG3HUV94J)
From what I can see, the CSIDrivers objects for rbd and cephfs (but not for nfs!) that rook-ceph-operator creates have hardcoded attachRequired: true: https://github.com/rook/rook/blob/7300dc6142a97c27a912435ffb4f8a8f31785b1c/pkg/operator/ceph/csi/spec.go#L643-L654
createCSIDriverInfo(ctx context.Context, clientset kubernetes.Interface, name, fsGroupPolicy string, attachRequired bool)
csiDriverobj.createCSIDriverInfo(r.opManagerContext, r.context.Clientset, RBDDriverName, k8sutil.GetValue(r.opConfig.Parameters, "CSI_RBD_FSGROUPPOLICY", string(k8scsi.FileFSGroupPolicy)), true)
(edited)


lbogdan
  [< 1 minute ago](https://rook-io.slack.com/archives/CG3HUV94J/p1677674067941879?thread_ts=1677660821.520389&cid=CG3HUV94J)
Opened an issue, just in case: https://github.com/rook/rook/issues/11805 .
</details>

**Comment by Madhu-1** [comment]
@lbogdan i can make it as a configurable value so that you can adjust it based on the use case and you are well aware of the consequences of changing the default values.

**Comment by lbogdan** [comment]
That would be **very nice**!

**Comment by Madhu-1** [comment]
> That would be **very nice**!
> 
> It would save me from building a custom `rook` binary and `1.10` image! slightly_smiling_face
> 
> Btw, any thoughts on the drawbacks of lowering `nodeStatusUpdateFrequency` to 1 second?

I never tried changing the default value may be it might be having effect on the API server as GET and PUT operation will be done
