### ISSUE TITLE
Improve ceph mgr HA mechanism by using a dynamic active-mgr label

### ISSUE THREAD

**Issue by rkachach** [rook/rook#11844]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Right now ceph mgr HA in rook is implemented by updating services labels (ceph_daemon_id) to force them to point to the active mgr pod. Even when this works correctly in the current implementation, the user needs to add a special label ceph-app:rook-ceph-mgr to his service.

**What is use case behind this feature:**
Use an active-mgr (or similar) label which is only added to the ceph active mgr pod. Services selectors can use this label to select the active-mgr and there's no need to internally update the `ceph_daemon_id` label (which is error an error prone mechanism).

**Environment**:

**Comment by gaord** [comment]
currently ceph_daemon_id label works fine. Wondering why need another? Could you explain your scenario a bit more?

**Comment by rkachach** [comment]
> currently ceph_daemon_id label works fine. Wondering why need another? Could you explain your scenario a bit more?

@gaord Please, have a look to the PR. It contains some explanation on the reason behind the change.

**Comment by rkachach** [comment]
> 
@gaord In the current implementation when the active manager changes, Rook internally has to find all the services that rely on the manager and one-by-one, go and update dynamically the `ceph_daemon_id=x` to point them to the new active manager pod. In the new implementation this not needed anymore. The services will have a new label `mgr_role=active` which will point them directly to the active mgr pod. Rook internally just need to keep this label updated on the corresponding mgrs pods. So overall, the new implementation requires less updates.
