### ISSUE TITLE
import-external-cluster.sh errors

### ISSUE THREAD

**Issue by Borosan** [rook/rook#11846]
Connecting to external ceph from kubernetes using rook

i have a k8s cluster 1.24 and i have a external ceph cluster (installed via cephadm )
i have created a pool (rbd) on my ceph cluster and i want to use rook on my kubernetes cluster to use my rbd pool.

**How to reproduce it (minimal and precise):**
create a ceph cluster via cephadm and follow these steps (https://rook.io/docs/rook/v1.10/CRDs/Cluster/external-cluster/#commands-on-the-k8s-consumer-cluster) to connect k8s to external ceph.

when i reached  this step:
```
. import-external-cluster.sh
```
i got these errors:

**command out out**:
---
: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
: command not found
: command not found
: command not found
-bash: import-external-cluster.sh: line 34: syntax error near unexpected token `$'{\r''
'bash: import-external-cluster.sh: line 34: `function checkEnvVars() {
---

also i have tried
```
bash -n import-external-cluster.sh
import-external-cluster.sh: line 34: syntax error near unexpected token `$'{\r''
'mport-external-cluster.sh: line 34: `function checkEnvVars() {
```
please guide me if i have to do something more that what i have found in (https://rook.io/docs/rook/v1.10/CRDs/Cluster/external-cluster/#commands-on-the-k8s-consumer-cluster)

**Environment**:
* OS (e.g. from /etc/os-release): rocky 8
* Kernel (e.g. `uname -a`): 5.4
* Cloud provider or hardware configuration: omprem
* Rook version (use `rook version` inside of a Rook Pod): 1.11.0
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`):
* Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:38:19Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): onprem
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by parth-gr** [comment]
Hey,
Did you pasted the data output to your current shell https://rook.io/docs/rook/v1.10/CRDs/Cluster/external-cluster/#2-copy-the-bash-output

**Comment by Borosan** [comment]
Yes i have done, and  before this version 1.11.0 . i had no problem with version 1.9.4.

**Comment by rkachach** [comment]
From the error:
```
import-external-cluster.sh: line 34: syntax error near unexpected token `$'{\r''
```
The '\r' character normally used as the EOL character in Windows-based systems. Did you copy the script to some Win editor?

**Comment by Borosan** [comment]
@parth-gr  No. I haven't done any upgrade! ahhh  i have the same problem with 1.9.4! now!  (during these two weeks i re installed my external ceph but the problem persists! :( )

**Comment by Borosan** [comment]
@rkachach . i changed the way i copied, i used git file and transfred it , no  changes in results!

**Comment by parth-gr** [comment]
I surely think is the env problem,
Can you try the 1.9 script and check,

`sed -i 's/\r//' import-external-cluster.sh` may try this

**Comment by parth-gr** [comment]
I will  open a PR to not to enforce these 2

Thanks

**Comment by Borosan** [comment]
and after comment several lines. the issue resolved. thank you ,
