### ISSUE TITLE
Make cr manager configurable

### ISSUE THREAD

**Issue by zhucan** [rook/rook#11854]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Make cr manager configurable. https://github.com/rook/rook/blob/6e296ecc71ea536cf577ea1d00f8ca79cb5bff60/pkg/operator/ceph/cr_manager.go#L87

**What is use case behind this feature:**
Because of separate computing and storage deployment, not need to reconcile of csi, we should disable it on the storage cluster.

**Environment**:

**Comment by travisn** [comment]
What is the need to disable some controllers? Are you concerned it is taking unnecessary resources when not in use? It should be minimal resources, so I'm not sure it's worth making it configurable.

**Comment by zhucan** [comment]
Because of we will deploy the csi on the other K8s cluster，no needed to deploy with rook cluster

**Comment by travisn** [comment]
The configmap will even be deployed if the csi controller is disabled. What issue would the configmap cause?

**Comment by zhucan** [comment]
if we not want to deploy csi, all releationships reource should not be created, isn't it?
