### ISSUE TITLE
Don't mount /dev hostPath when cluster runs with emptyDir for osd

### ISSUE THREAD

**Issue by phsiao** [rook/rook#1186]
When spec.dataDirHostPath is empty, the cluster will build osd pods that uses emptyDir for backing store.   rook still tries to mount /dev via hostPath in that case, even though there is no need for that because osd does not need to discover devices.

I think mounting /dev should be avoided when spec.dataDirHostPath is empty.

**Comment by travisn** [comment]
I believe we will also need to put restrictions in place for other properties that refer to devices. If `dataDirHostPath` is set to empty for a least privilege environment, it could also have the following implications:
- OSD pods don't need to run privileged
- `useAllDevices` must be false, `deviceFilter` and `metadataDevice` would be ignored, and `devices` underneath the `nodes` would be ignored.

@jbw976 thoughts on this?

**Comment by jbw976** [comment]
Yes @travisn that sounds about right.  Note that this general idea is also related to #400.

**Comment by phsiao** [comment]
Yes, I am reviewing the conditions/combinations, and would be happy to include the idea from #400 as well, so that it does not run as privileged when it does not need to.
