### ISSUE TITLE
Enable the rook orchestrator module by default

### ISSUE THREAD

**Issue by jmolmo** [rook/rook#11867]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Enable by default the rook orchestrator manager module. 

**What is use case behind this feature:**
The rook manager orchestrator is needed to complete certain operations. Now, users who want to use fully funcionality in dashbopard need to enable the rook orchestrator module manually. 

**Environment**:
It affects all cluster definitions where the Ceph dashboard is enabled by default

**Comment by travisn** [comment]
Agreed, let's enable it whenever the dashboard is enabled. What are the remaining issues to resolve before enabling it?

**Comment by jmolmo** [comment]
> Agreed, let's enable it whenever the dashboard is enabled. What are the remaining issues to resolve before enabling it?

I think only to have defined by default the right class storage to avoid errors when searching for devices in clusters not using physical devices. I double check this point

**Comment by galexrt** [comment]
@jmolmo have you been able to check if we can enable the rook orchestrator module by default?

**Comment by jmolmo** [comment]
> @jmolmo have you been able to check if we can enable the rook orchestrator module by default?

@galexrt , sorry for the long wait. 

The main problem here is that we do not have any kind of automatic tests to be sure that the functionality provided by the rook orchestrator is working properly.
As far as i know we have working basic functionality, but i have not tested properly deployment of services (nfs/rgw/rbd). Testing manually is not a good solution, because any modification in ceph or rook can break the "orchestrator bridge" again.

I implemented a solution for testing rook orchestrator functionality each time a new "orchestrator" labeled ceph pull request is raised in the Ceph repo. Unfortunately I haven't enough time to test this "testing solution" in deep, and to finish the definition of a set of minimum functional tests.

I have upload  the implementation to my "repos" and you can take a look if you want:
https://github.com/jmolmo/ceph-build/tree/rook-orch-e2e
https://github.com/jmolmo/ceph/tree/rook-orch-e2e

I continue very busy, but i will be glad to help anybody to continue with the work. Basically the pending work is to test the "rook environment" in the jenkins Ceph build lab and finishing test cases (very easy to define now using behave)

Once we will have automatic tests to cover automatic testing of any kind of modification in the Ceph orchestrator, we will be in shape to enable by default the rook orchestrator in Rook.
