### ISSUE TITLE
Update slack.rook.io to use slackin-extended

### ISSUE THREAD

**Issue by travisn** [rook/rook#11915]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The site https://slack.rook.io is currently down and is being investigated. 

**Follow this link to join Slack for now:**
https://rook-io.slack.com/join/shared_invite/zt-1ra2rpm6q-pso8DKHV4uOkmJSxDUWskA#/shared-invite/email

**Comment by travisn** [comment]
@zhucan Why did you unpin this? It's still a critical issue for anyone who wants to join slack.

**Comment by zhucan** [comment]
I didn't unpin this，Idon't know why accept this mesdage

**Comment by zhucan** [comment]
I didn't unpin this，Idon't know why accept this message

**Comment by zhucan** [comment]
@travisn my mistake, I'm sorry about it.

**Comment by travisn** [comment]
> @travisn my mistake, I'm sorry about it.

Ok no worries if it wasn't intentional, was just trying to understand why it was unpinned.

**Comment by alsotoes** [comment]
Hey,
I'm working with @jbw976 on this and we saw 3 main issues:

1. - Slack is blocking SSL request from deprecated nodejs runtimes
2. - API url call changed, not team_id needs to be passed as parameter not embedded into the url
3. - Deprecated version of nodejs and libraries

I'll commit the fix for 1 and 2 first so we can have the auto invite url up again.

**Comment by travisn** [comment]
slack.rook.io is back up again, though is using a link that will expire after some time. Looking forward to a solution that doesn't use an expiring link, thanks @alsotoes!

**Comment by alsotoes** [comment]
@travisn shared the extended version of slackin url: https://github.com/emedvedev/slackin-extended and after testing it seems like a faster option to put the url online again. Please consider the following environment variable names:

Original in slackin -> Change in extended version
```
SLACK_COC -> SLACKIN_COC
GOOGLE_CAPTCHA_SECRET -> RECAPTCHA_SECRET
GOOGLE_CAPTCHA_SITEKEY -> RECAPTCHA_SITEKEY
```

Recommended variables for production:
```
SLACKIN_CORS=true
SLACKIN_SILENT=true
```

Sorry about taking this long =(

**Comment by galexrt** [comment]
@alsotoes No worries, thanks for jumping in and helping!

**Comment by jbw976** [comment]
Thanks for pointing out these variable name changes @alsotoes! that will make the deployment of slackin-extended easier :)

**Comment by alsotoes** [comment]
Anything I can do to help on this matter?
[slackin-extended](https://github.com/emedvedev/slackin-extended) works pretty good.

**Comment by travisn** [comment]
The previous link stopped working, now the link to join is now updated to: https://join.slack.com/t/rook-io/shared_invite/zt-23hi9wqet-BUFB0AoXbxRPILbAxdfFiA

@jbw976 Any update on slackin-extended? Thanks!

**Comment by travisn** [comment]
@jbw976 Are you still planning on configuring slackin-extended?

**Comment by alsotoes** [comment]
I haven't been looking at this much, but I believe it's time to check it again to see what I can do with the permissions that I have over this workspace and others to test.

**Comment by jbw976** [comment]
reCaptcha is now working OK, I reused the previous keys as the newly generated keys kept giving the "invalid key type" error.

Folks are welcome to test the registration flow on https://slackin-extended.rook.io/ now, it was successful for me just now 💪

**Comment by travisn** [comment]
Works for me too, looks great!

**Comment by jbw976** [comment]
We are now live on https://slack.rook.io/ 🎉  - DNS has been switched over, certificate is OK, recaptcha is OK, registration flow looks OK ✅ 

Please let me know ASAP if anyone sees issues with creating a Rook slack account on https://slack.rook.io/ 🙇‍♂️
