### ISSUE TITLE
EC in external cluster

### ISSUE THREAD

**Issue by dragon2611** [rook/rook#11918]
Happy to submit a PR but I'll raise this first just incase it's simply a case of me getting confused over variable names VS their action

In the file deploy/examples/import-external-cluster-sh I think RBD_METADATA_EC_POOL_NAME and RBD_POOL_NAME are backwards.

given the name of the variable RBD_METADATA_EC_POOL_NAME I would expect you provide the name of the metadata pool for an EC coded pool and therefore the Data pool would be inserted in RBD_POOL_NAME

However looking at the code.

```function createECRBDStorageClass() {
cat <<eof | kubectl create -f -
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: $RBD_STORAGE_CLASS_NAME
provisioner: $RBD_PROVISIONER
parameters:
  clusterID: $CLUSTER_ID_RBD
  pool: $RBD_POOL_NAME
  dataPool: $RBD_METADATA_EC_POOL_NAME
  imageFormat: "2"
  imageFeatures: $ROOK_RBD_FEATURES
  csi.storage.k8s.io/provisioner-secret-name: "rook-$CSI_RBD_PROVISIONER_SECRET_NAME"
  csi.storage.k8s.io/provisioner-secret-namespace: $NAMESPACE
  csi.storage.k8s.io/controller-expand-secret-name:  "rook-$CSI_RBD_PROVISIONER_SECRET_NAME"
  csi.storage.k8s.io/controller-expand-secret-namespace: $NAMESPACE
  csi.storage.k8s.io/node-stage-secret-name: "rook-$CSI_RBD_NODE_SECRET_NAME"
  csi.storage.k8s.io/node-stage-secret-namespace: $NAMESPACE
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
reclaimPolicy: Delete
eof
}
```

This caused the built SC to have the Metadata pool as the data pool which of course didn't work.

**Comment by parth-gr** [comment]
@dragon2611 This was designed in the same way https://github.com/rook/rook/blob/44d58ef6053e70d69fd1532e354d50f89ac95ee5/deploy/examples/csi/rbd/storageclass-ec.yaml#L45 it's here.

The `dataPool` # The erasure coded pool must be set as the `dataPool` parameter below.

So as the code does `dataPool: $RBD_METADATA_EC_POOL_NAME`

The same is done even here.
cc @Madhu-1 


What values do you expect otherwise at the `dataPool` place

**Comment by parth-gr** [comment]
Okay,
Open a PR with the changes as you want:), 

We will look for reviews.
Also change it in the python script too.
Thanks!

**Comment by dragon2611** [comment]
Hmm 

Not sure it needs changing in the python script unless we want to change the variables entirely which I suppose we could do when using EC to make it clearer.

do we want an --rbd-data-ec-pool-name instead here to make things clearer?

I think the confusion comes from when passing it to  the python script it's 

--rbd-data-pool-name which populates RBD_POOL_NAME

--rbd-metadata-ec-pool-name populates RBD_METADATA_EC_POOL_NAME

```
python3 create-external-cluster-resources.py --rbd-data-pool-name=k8s-ec-data --namespace rook-ceph-external --rbd-metadata-ec-pool-name=k8s-ec-metadata --cephfs-data-pool-name=k8s-cephfs_data --cephfs-metadata-pool-name=k8s-cephfs_metadata --format=bash
```

```
export NAMESPACE=rook-ceph-external
export ROOK_EXTERNAL_FSID=removed
export ROOK_EXTERNAL_USERNAME=client.healthchecker
export ROOK_EXTERNAL_CEPH_MON_DATA=removed
export ROOK_EXTERNAL_USER_SECRET=removed
export CSI_RBD_NODE_SECRET=removed
export CSI_RBD_NODE_SECRET_NAME=csi-rbd-node
export CSI_RBD_PROVISIONER_SECRET=removed
export CSI_RBD_PROVISIONER_SECRET_NAME=csi-rbd-provisioner
export CEPHFS_POOL_NAME=k8s-cephfs_data
export CEPHFS_METADATA_POOL_NAME=k8s-cephfs_metadata
export CEPHFS_FS_NAME=k8s-cephfs
export CSI_CEPHFS_NODE_SECRET=removed
export CSI_CEPHFS_PROVISIONER_SECRET=removed
export CSI_CEPHFS_NODE_SECRET_NAME=csi-cephfs-node
export CSI_CEPHFS_PROVISIONER_SECRET_NAME=csi-cephfs-provisioner
export MONITORING_ENDPOINT=removed
export MONITORING_ENDPOINT_PORT=9283
export RBD_POOL_NAME=k8s-ec-data
export RBD_METADATA_EC_POOL_NAME=k8s-ec-metadata
export RGW_POOL_PREFIX=default
```
