### ISSUE TITLE
This black formater should run ever-time we save the file to make it consistent

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#11926]
@subhamkrai this black formatter isn't run https://github.com/rook/rook/pull/10399 ever-time we save the file?
If not it would be difficult to maint the format

_Originally posted by @parth-gr in https://github.com/rook/rook/issues/11885#issuecomment-1469693766_

**Comment by parth-gr** [comment]
@subhamkrai please take a look

**Comment by subhamkrai** [comment]
you can add extension in vscode like https://dev.to/adamlombard/how-to-use-the-black-python-code-formatter-in-vscode-3lo0
 or you can run command to format the source file follow this https://pypi.org/project/black/

**Comment by subhamkrai** [comment]
> Okay, Can we have this development guide then?

it is already in vscode settings https://github.com/rook/rook/blob/master/.vscode/settings.json#L11
