### ISSUE TITLE
Rebalance mon when more than one per node

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1193]
The operator should rebalance/failover a mon to another node, when there are more than one mons on one node and a node is available again to run mons.

This should happen in the mon health check loop.

**Example behavior**:
* node1: mon0
* node2: mon1
* node3: mon2

node3 fails, after mon out timeout the failover of mon2 happens and the mon2 gets failovered to node2
* node1: mon0
* node2: mon1 mon3
* ~~node3~~

When node3 is up again, the operator should see that enough nodes are available again and failover the mon3 to the node3 so there is no single point of failure when node2 would go down.
* node1: mon0
* node2: mon1
* node3: mon4

**Comment by lorenz** [comment]
I would also really like support for failure domains. I have a setup where there is one or more nodes at a single location which share a single internet connections (the cluster is built on a few residential 1Gbps symmetrical connections). I'm using failure domain zones to keep redundant workloads on at least two zones. If rook only looks at hostnames the mons could end up in one zone and the cluster could go down if a single connection disappears.

**Comment by travisn** [comment]
@lorenz agreed, would be great to take failure domains into account. Would you actually open a new issue for that? It seems independent from this issue.

**Comment by lorenz** [comment]
@travisn I mean the issue is pretty much that instead of having (in terms of affinities, I know this is not an affinity) a fixed topologyKey of `kubernetes.io/hostname` for mons that topologyKey needs to be configurable. At least to me this seems to directly affect the algorithm that will be implemented to solve this issue. If you want I'll happily open a separate issue though.

**Comment by galexrt** [comment]
I'm seeing failure domains also as an independent issue. This issue is for adding a logic to the health check to detect if more than one mon is running on a node and then to reschedule/failover the mon to a new/other ready node.

To add "custom" failure domains there would be a change in the placement logic needed and not the health check logic which is here more in focus.

@lorenz Could you please create a new issue for adding "custom" failure domains?
