### ISSUE TITLE
Encryption kms tests failing since key rotation was merged

### ISSUE THREAD

**Issue by travisn** [rook/rook#11940]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Since #11749 was merged with the key rotation implementation, several canary tests have been failing in both master and 1.11 branch where it was backported. See the failures [here](https://github.com/rook/rook/actions/runs/4366444927), or in any master or release-1.11 canary run since then.
- encryption-pvc-kms-vault-token-auth
- encryption-pvc-kms-vault-k8s-auth
- encryption-pvc-kms-ibm-kp

It is not clear why the PR did not fail all these tests before merge, but they have been failing very consistently since merge. 

The operator log in the CI appears full of this error:
```
2023-03-08 16:48:13.924048 D | ceph-spec: CephCluster "rook-ceph" status: "Progressing". "failed to perform validation before cluster creation: 
failed to validate kms connection details: failed to validate vault connection details: 
failed to find TLS connection details k8s secret \"vault-ca-cert\": client rate limiter Wait returned an error: context canceled"
2023-03-08 16:48:13.937661 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": 
failed to configure local ceph cluster: failed to perform validation before cluster creation: failed to validate kms connection details: failed to validate vault connection details:
 failed to find TLS connection details k8s secret "vault-ca-cert": client rate limiter Wait returned an error: context canceled
```

The operator log also shows the cluster CR was updated:
```
2023-03-08 16:47:29.841672 I | ceph-cluster-controller: CR has changed for "rook-ceph". diff=  v1.ClusterSpec{
  	... // 20 identical fields
  	CleanupPolicy: {},
  	HealthCheck:   {},
  	Security: v1.SecuritySpec{
  		KeyManagementService: {ConnectionDetails: {"KMS_PROVIDER": "vault", "VAULT_ADDR": "https://vault.default.svc.cluster.local:8200", "VAULT_AUTH_KUBERNETES_ROLE": "rook-ceph", "VAULT_AUTH_METHOD": "kubernetes", ...}},
  		KeyRotation: v1.KeyRotationSpec{
  			Enabled:  false,
- 			Schedule: "",
+ 			Schedule: "@weekly",
  		},
  	},
  	LogCollector: {},
  }
```

@Rakshith-R Instead of updating the CR, perhaps a simple fix is to just replace the value in the cluster.yaml before the test is started. 

**Expected behavior:**
Passing CI

**Comment by Rakshith-R** [comment]
I don't think these failures have anything to do with key rotation. 

The CR change is just default value being added and I don't think it is the reason for such huge delays.

This is coming from go-client. There might have been some change somewhere in the dependencies we are using.
We may need to use another Rate limiter or tweak its values
`client rate limiter Wait returned an error: context canceled`

https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.5/pkg/ratelimiter
https://pkg.go.dev/k8s.io/client-go/util/workqueue

Or optimise ci.

**Comment by travisn** [comment]
> I don't think these failures have anything to do with key rotation.

Agreed it's not directly from key rotation, but the CI issue was just raised since the PR merged and took a while to realize it. 

> The CR change is just default value being added and I don't think it is the reason for such huge delays.
> 
> This is coming from go-client. There might have been some change somewhere in the dependencies we are using. We may need to use another Rate limiter or tweak its values `client rate limiter Wait returned an error: context canceled`
> 
> https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.5/pkg/ratelimiter https://pkg.go.dev/k8s.io/client-go/util/workqueue
> 
> Or optimise ci.

I don't think this is an issue with delays or increasing timeouts. I wonder if we can just avoid the update that's setting the rotation to `@weekly` in the cluster CR, then these tests may start passing. There does seem like some issue, perhaps related to controller runtime update in the past couple months that is more related to this issue. We don't have these CI issues in the 1.10 branch.
