### ISSUE TITLE
Support use of resource requests/limits in pod spec for all rook pod types

### ISSUE THREAD

**Issue by phsiao** [rook/rook#1194]
For fair resource consumption and resource isolation, rook should support resource requests and limits in pod spec for all rook pod types, including osd, mon, rgw, and so on.

In some environment the use of best effort pods (pods without resource requests) is restricted because it is very difficult to schedule these pods and calculate utilization of the cluster, so it may become a friction for rook to be used more widely.

The easiest is probably to start with just resource requests with a reasonably calibrated amount for both cpu and memory, and provide ways for that to be customized further.

Resources limits might be harder to get right, as that imposes a ceiling on what a pod can use, and if done incorrectly can limit the performance of ceph system.

**Comment by galexrt** [comment]
First part of the design has been full filled, by PR #1207. Users can now specify their own requests/limits on the rook components.
The second part will be to create an automated logic to calculate these values depending on an user given "Quality of Service" class from which the values are calculated (user values take precedence over calculated values).

**Comment by travisn** [comment]
@galexrt @phsiao how about if we close this issue now since #1207 is in? Its original purpose seems fulfilled. Then you could open a new ticket to automatically set the values, which can likely wait until after 0.7

**Comment by phsiao** [comment]
SGTM.
