### ISSUE TITLE
rook-api pod is using a high amount of CPU

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1195]
We've been hearing reports recently of the rook-api pod using a lot of CPU.  This sounds like a recent regression, but i don't know the cause.  Will update this ticket when we have more information, but it definitely sounds like an issue that people are running into.

**Comment by jpds** [comment]
I also noticed that on my two clusters, rook-api was consistently using 1 CPU core.

**Comment by dgonzalezruiz** [comment]
For the records, this also happens after upgrading to 0.6. The API pod takes exactly one CPU core after some transient time. At the beginning, after restarting the pod, the consumption is just as expected from a cluster with very little usage.

**Comment by leenux** [comment]
Same.
I already used the Resources limit to limit CPU=100m by updating all yaml file,but CPU used 180-200% on 2 CPU core.

**Comment by jbw976** [comment]
@jpds @dgonzalezruiz @leenux 

do all of you have monitoring set up such that prometheus is hitting the rook-api pod on `/metrics`? i'm definitely curious if you all are seeing this without any monitoring set up.  in any case, sharing your rook-api pod logs here will be helpful.  thanks!

**Comment by jpds** [comment]
@jbw976 In my case, one cluster has metrics enabled, but the other doesn't.

**Comment by lorenz** [comment]
Happens here on 0.6 without Prometheus

**Comment by sordfish** [comment]
I can also confirm this is taking 1 cpu without Prometheus on 0.6. Deployed in Rancher.

**Comment by travisn** [comment]
@jpds @dgonzalezruiz @leenux @lorenz @sordfish do you see any more evidence of the cpu usage? 
- If you `kubectl exec` to the pod, does `top` show what process is the culprit?
- Do you have any non-default settings in your cluster.yaml? For example, is host networking enabled? 
- Does the rook-api log show any repeated or high frequency api requests?
- If you were running the 0.5.x build, did you ever notice this issue?

Note that the rook-api pod is optional, and is only used by the `rookctl` tool in the toolbox. If you are not using the toolbox, you could delete the rook-api deployment, although the operator would create it again if it restarts.

**Comment by jpds** [comment]
@travisn Yes, I first noticed this through heapster via the kubernetes-dashboard, my rook-api pod is consistently around 1000-1024m in `kubectl top pods -n rook`. top shows:

```
root         7 99.5  0.0  38140 20088 ?        Sl   Nov07 10101:02 /usr/local/bin/rook api --config-dir=/var/lib/rook --port=8124 --hostnetwork=false
```

I don't use anything fancy in cluster.yaml.

There is nothing in my rook-api log for the last 6h apart from a single rookctl status call that I just ran.

0.5 had this issue, but I've always been on master.

I think for the last bit, it'd be useful to have a flag to disable the api server.

**Comment by travisn** [comment]
@jpds @dgonzalezruiz thanks for the input. #704 is actually tracking making the api server optional as well.

**Comment by galexrt** [comment]
Additionally to the high CPU usage, there seems to be a memory leak in the rook-api, see https://snapshot.raintank.io/dashboard/snapshot/U4gIjT4oWfYjp9oSuyc711mckJRgi4xR?orgId=2
In the graphs you can also see that the rook-api takes up one CPU core from the start on.

**Comment by bassam** [comment]
possibly fix in v0.6.1

**Comment by jbw976** [comment]
@bassam suggested that the CPU usage could be directly related to the potential memory leak that @galexrt showed in the graph above.

in addition to the profiling and debugging that we need to accomplish to find root cause for this issue, @galexrt suggested potentially adding a flag so that profiling could be turned on for containers without having to build a special container image.  this may be useful in the future.  links from @galexrt for pprof:
https://golang.org/pkg/net/http/pprof/
https://golang.org/pkg/runtime/pprof/

**Comment by costrouc** [comment]
Can confirm that I have same issue 100% cpu usage on single cpu from rook api. I am running a single node cluster without Prometheus.

**Comment by jbw976** [comment]
The profiling/tracing data clearly shows that the rook-api pod is in a tight loop in the `WatchMonConfig` function: https://github.com/rook/rook/blob/028d70d4ec58653055d615b9031b1bf5aa735fc2/pkg/api/daemon.go#L78

Attaching a trace file that can be viewed interactively with `go tool trace trace.txt`: 
[trace.txt](https://github.com/rook/rook/files/1512090/trace.txt).

**Comment by bassam** [comment]
nice work @jbw976

**Comment by bassam** [comment]
are we backporting this to 0.6?

**Comment by jbw976** [comment]
yes @bassam, backporting to 0.6 with #1275
