### ISSUE TITLE
cephfs: the wrong status of cephfs with cr

### ISSUE THREAD

**Issue by zhucan** [rook/rook#11957]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
If the pg of the pool for cephfs is unknow, the status of cr can not be ready

**How to reproduce it (minimal and precise):**

1. create a new crush root, and remove osd from default crush root to new crush root
2. create a cephfs can not assign cursh root, it will use the default crush root
3. the pool will be created successfully with unknown pg 
4. the status of cr is ready

**File(s) to submit**:
cephfs.yaml
```
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ceph.rook.io/v1","kind":"CephFilesystem","metadata":{"annotations":{},"name":"myfs","namespace":"rook-ceph"},"spec":{"dataPools":[{"name":"replicated","replicated":{"size":3}}],"metadataPool":{"replicated":{"size":3}},"metadataServer":{"activeCount":1,"activeStandby":true},"preserveFilesystemOnDelete":true}}
  creationTimestamp: "2023-03-21T11:42:30Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-03-21T11:43:30Z"
  finalizers:
  - cephfilesystem.ceph.rook.io
  generation: 3
  name: myfs
  namespace: rook-ceph
  resourceVersion: "3307502"
  uid: 5226619e-8fe4-43c3-961f-3f8e97ed1d02
spec:
  dataPools:
  - erasureCoded:
      codingChunks: 0
      dataChunks: 0
    mirroring: {}
    name: replicated
    quotas: {}
    replicated:
      size: 3
    statusCheck:
      mirror: {}
  metadataPool:
    erasureCoded:
      codingChunks: 0
      dataChunks: 0
    mirroring: {}
    quotas: {}
    replicated:
      size: 3
    statusCheck:
      mirror: {}
  metadataServer:
    activeCount: 1
    activeStandby: true
    placement: {}
    resources: {}
  preserveFilesystemOnDelete: true
  statusCheck:
    mirror: {}
status:
  observedGeneration: 1
  phase: Ready
```

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by zhucan** [comment]
pg of metadata pool and datat pool:
```
root@rook-node02:/# ceph pg ls-by-pool myfs-replicated
PG     OBJECTS  DEGRADED  MISPLACED  UNFOUND  BYTES  OMAP_BYTES*  OMAP_KEYS*  LOG  STATE    SINCE  VERSION  REPORTED  UP     ACTING  SCRUB_STAMP                      DEEP_SCRUB_STAMP               
12.0         0         0          0        0      0            0           0    0  unknown    18h      0'0       0:0  []p-1   []p-1  2023-03-21T11:42:42.919223+0000  2023-03-21T11:42:42.919223+0000
12.1         0         0          0        0      0            0           0    0  unknown    18h      0'0       0:0  []p-1   []p-1  2023-03-21T11:42:42.919223+0000  2023-03-21T11:42:42.919223+0000
12.2         0         0          0        0      0            0           0    0  unknown    18h      0'0       0:0  []p-1   []p-1  2023-03-21T11:42:42.919223+0000  2023-03-21T11:42:42.919223+0000
12.3         0         0          0        0      0            0           0    0  unknown    18h      0'0       0:0  []p-1   []p-1  2023-03-21T11:42:42.919223+0000  2023-03-21T11:42:42.919223+0000
12.4         0         0          0        0      0            0           0    0  unknown    18h      0'0       0:0  []p-1   []p-1  2023-03-21T11:42:42.919223+0000  2023-03-21T11:42:42.919223+0000
12.5         0         0          0        0      0            0           0    0  unknown    18h      0'0       0:0  []p-1   []p-1  2023-03-21T11:42:42.919223+0000  2023-03-21T
```
status of cr:
```
NAME   ACTIVEMDS   AGE   PHASE
myfs   1           18h   Ready
```

**Comment by travisn** [comment]
The status `Ready` for the CRs is from the perspective of whether the reconcile is completed successfully. If the health of cephfs needs to be raised on the CR, it should be done in a separate status field. For example, in the CephCluster CR status, it's the same pattern. The ceph health is listed in a separate status field from the `Ready` status of the CR. The ceph health is updated every 60s by default (see the setting [here](https://github.com/rook/rook/blob/release-1.11/deploy/examples/cluster.yaml#L285-L287)) in a separate goroutine. If we need cephfs health status, we would similarly need to implement a goroutine that updates the health status of cephfs.

**Comment by zhucan** [comment]
Yes，so we need to create a issue for it

**Comment by zhucan** [comment]
And other question is if we create the cephfs with not exists crush root，we can delete it with the yaml，only can remove the finalized and delete the cephfs manually with ceph cmd

**Comment by travisn** [comment]
> And other question is if we create the cephfs with not exists crush root，we can delete it with the yaml，only can remove the finalizer and delete the cephfs manually with ceph cmd

What is your question? You want to delete the failed filesystem without manually removing the finalizer? In that case, rook doesn't know if it's safe to remove the filesystem.

**Comment by zhucan** [comment]
We delete the failed filesystem can only with remove finalizer an delete the filesystem with ceph cmd manually，is there a way to deal with this case？

**Comment by travisn** [comment]
See the code for handling filesystem deleting [here](https://github.com/rook/rook/blob/release-1.11/pkg/operator/ceph/file/controller.go#L250-L288). We would need to change that to allow for deleting the filesystem in that case.

**Comment by zhucan** [comment]
> See the code for handling filesystem deleting [here](https://github.com/rook/rook/blob/release-1.11/pkg/operator/ceph/file/controller.go#L250-L288). We would need to change that to allow for deleting the filesystem in that case.

I will create a issue for it firstly.
