### ISSUE TITLE
cannot mount cephfs volume with network compression or encryption

### ISSUE THREAD

**Issue by uhthomas** [rook/rook#11978]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

This is the same as #11521, but opening this as the other issue has been wrongfully closed. There have been fixes for RDB, but not CephFS.

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by uhthomas** [comment]
I believe the current workaround is to set `CSI_CEPHFS_KERNEL_MOUNT_OPTIONS: "ms_mode=secure"` in the `rook-ceph-operator-config` config map.

**Comment by travisn** [comment]
Yes, that setting is required. It's mentioned in the [cluster spec doc](https://rook.github.io/docs/rook/v1.11/CRDs/Cluster/ceph-cluster-crd/#network-configuration-settings):
```
If this setting is enabled, CephFS volumes also require setting CSI_CEPHFS_KERNEL_MOUNT_OPTIONS to "ms_mode=secure" in operator.yaml.
```
It was discussed in #11625 if there is a way to enable it automatically so you don't have to dig through the docs, but this is where it landed.

**Comment by ffdfgdfg** [comment]
Also need attention to `requireMsgr2: true`, this option needs `"ms_mode=crc"`

**Comment by travisn** [comment]
> Also need attention to `requireMsgr2: true`, this option needs `"ms_mode=crc"`

Yes, this is necessary. It's already being done for rbd, but is not mentioned in the operator.yaml comment for cephfs. @Madhu-1 want to add that?

**Comment by travisn** [comment]
Actually the cephfs mount options were already added in operator.yaml with #11625.

**Comment by zer0def** [comment]
In case anyone else stumbles by this issue and feels that altering the operator's `csi.cephFSKernelMountOptions` is backwards due to a smaller order resource's option (in this case: `CephCluster`'s `.spec.network.(compression|encryption).enabled=true`) warrating this, it should be noted that the built-in [`StorageClass`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#storageclass-v1-storage-k8s-io) takes mount options under `.mountOptions` as an array of strings, which ends up comma-joined.

**Comment by parth-gr** [comment]
I guess we already has a opened issue https://github.com/rook/rook/issues/12721
