### ISSUE TITLE
cephfilesystem is not ready state, ceph version not found for image "quay.io/ceph/ceph:v17.2.5"

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#11996]
**Is this a bug report or feature request?**
* Bug Report

in operator logs showing below error and due to this cephfilesystem is in progressing status and after some time cluster status is also going progressive status, please help on this.
```
ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)":1},"osd":{"ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)":3},"mds":{},"overall":{"ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)":7}}
2023-03-29 05:24:27.446989 D | cephclient: {"mon":{"ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)":3},"mgr":{"
ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)":1},"osd":{"ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)":3},"mds":{},"overall":{"ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)":7}}
2023-03-29 05:24:27.447077 D | ceph-cluster-controller: both cluster and image spec versions are identical, doing nothing 17.2.5-0 quincy
2023-03-29 05:24:27.447085 I | ceph-cluster-controller: cluster "rook-ceph": version "17.2.5-0 quincy" detected for image "quay.io/ceph/ceph:v17.2.5"
2023-03-29 05:24:27.449450 E | ceph-cluster-controller: failed to retrieve ceph cluster "rook-ceph" to update ceph version to {Major:17 Minor:2 Extra:5 Build:0 CommitID:98318ae89f1a893a6ded3a640405cdbb33e08757}. cephclusters.ceph.rook.io "rook-ceph" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "cephclusters" in API group "ceph.rook.io" in the namespace "rook-ceph"
2023-03-29 05:24:27.449513 D | ceph-spec: CephCluster "rook-ceph" status: "Progressing". "Configuring the Ceph cluster"
```
```
ceph-nodedaemon-controller: ceph version not found for image "quay.io/ceph/ceph:v17.2.5" used by cluster "rook-ceph" in namespace "rook-ceph". attempt to determine ceph version for the current cluster image timed out
```

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:
* Operator's logs, if necessary 
[operator.log](https://github.com/rook/rook/files/11102686/operator.log)
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 18.04.6 
* Kernel (e.g. `uname -a`): 4.15.0-206-generic
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): v1.11.1
* Storage backend version (e.g. for ceph do `ceph -v`): v17.2.5
* Kubernetes version (use `kubectl version`): v1.21.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
```
[rook@rook-ceph-tools-7f84568885-fdrbz /]$ ceph status
  cluster:
    id:     c3fb2a7b-5989-461f-9703-27f2ecaba4e9
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 38m)
    mgr: a(active, since 37m)
    osd: 3 osds: 3 up (since 37m), 3 in (since 37m)

  data:
    pools:   1 pools, 1 pgs
    objects: 2 objects, 449 KiB
    usage:   59 MiB used, 150 GiB / 150 GiB avail
    pgs:     1 active+clean

[rook@rook-ceph-tools-7f84568885-fdrbz /]$
```

**Comment by sahaniarun** [comment]
Do any one have experience setting up rook-ceph through argoCD ?
