### ISSUE TITLE
failed to reconcile CephCluster: cannot deletecollection resource

### ISSUE THREAD

**Issue by uhthomas** [rook/rook#12002]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

```
ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph osds: failed to reconcile key rotation cron jobs: failed to delete key rotation cron jobs: cronjobs.batch is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot deletecollection resource "cronjobs" in API group "batch" in the namespace "rook-ceph"
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**

Looks like the `deletecollection` is missing from https://github.com/rook/rook/blob/305aae552b9149f47222601468de100094d103a5/deploy/examples/common.yaml#L902-L907.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by sp98** [comment]
@uhthomas Hi. Can you please add more detailed steps to reproduce this issue.

**Comment by Rakshith-R** [comment]
@uhthomas 
Are you using the corresponding common.yaml ?

Deletcollection is part of cluster role rbac.
Here https://github.com/rook/rook/blob/0d909d945840dc84e328607e6788c964662017a0/deploy/examples/common.yaml#L263

**Comment by uhthomas** [comment]
> @uhthomas Are you using the corresponding common.yaml ?
> 
> Deletcollection is part of cluster role rbac. Here
> 
> https://github.com/rook/rook/blob/0d909d945840dc84e328607e6788c964662017a0/deploy/examples/common.yaml#L263

That is not really relevant. As @sp98 correctly observed, this is because the `rook-ceph-system` role does not have this permission.

**Comment by uhthomas** [comment]
> @uhthomas Hi. Can you please add more detailed steps to reproduce this issue.

Not sure - all I did was update a CephCluster CRD and saw this.

**Comment by travisn** [comment]
> > @uhthomas Hi. Can you please add more detailed steps to reproduce this issue.
> 
> Not sure - all I did was update a CephCluster CRD and saw this.

Did you also update common.yaml? Whenever the crds.yaml is updated, you also need to update the common.yaml. The `rook-ceph-global` cluster role also belongs to the `rook-ceph-system` service account, so it seems like that should be sufficient.

**Comment by uhthomas** [comment]
> > > @uhthomas Hi. Can you please add more detailed steps to reproduce this issue.
> > 
> > 
> > Not sure - all I did was update a CephCluster CRD and saw this.
> 
> Did you also update common.yaml? Whenever the crds.yaml is updated, you also need to update the common.yaml. The `rook-ceph-global` cluster role also belongs to the `rook-ceph-system` service account, so it seems like that should be sufficient.

Hm, I see.

Thank you, I was mistaken.

Given https://github.com/rook/rook/commit/f39a32fcdbd8a83693127686b0c6451aa2cb8671, this was committed days after I initially imported things. It should be okay to close this issue and the associated PR.

Sorry for the hassle.
