### ISSUE TITLE
when rook can support adding / removing an OSD node(host) by yaml or command?

### ISSUE THREAD

**Issue by mossinfan** [rook/rook#1201]
Now I meet a problem that I have set up a ceph cluster by rook with 10 OSDs node, each node has 200GB capacity, after one month, 200 GB * 10 node was not met my requirement, I want to scale out my storage, but now, rook has not the ability.
So I want to ask , when rook can support adding / removing an OSD node(host) by yaml or command?

Thanks.

**Comment by jbw976** [comment]
Hi @mossinfan, this is a feature we've been hearing about from more than just a couple users recently and I'm starting the design work this week.  You can track this effort in #1101 which will be in the 0.7 milestone.

If you have `useAllNodes:true` or `useAllDevices: true` then you could workaround this a bit as suggested in https://github.com/rook/rook/issues/1101#issuecomment-337533887.

Let us know if you have more comments or questions.  Thanks for your feedback!

**Comment by mossinfan** [comment]
good news, thank you very much.
