### ISSUE TITLE
NFS CRD not working on installation using rook 1.11

### ISSUE THREAD

**Issue by chaitusolasa** [rook/rook#12017]
Hi , I am using

https://rook.io/docs/rook/v1.11/Storage-Configuration/NFS/nfs/#enable-the-ceph-orchestrator-if-necessary

and when following steps

$ git clone --single-branch --branch v1.11.2 https://github.com/rook/rook.git
cd rook/deploy/examples
kubectl create -f crds.yaml -f common.yaml -f operator.yaml
kubectl create -f cluster.yaml

cd deploy/examples
kubectl create -f crds.yaml -f common.yaml -f operator.yaml

verify the rook-ceph-operator is in the Running state before proceeding
kubectl -n rook-ceph get pod

kubectl create -f cluster.yaml

Now when we deploy as u guys suggested

https://rook.io/docs/rook/v1.11/Storage-Configuration/NFS/nfs/#enable-the-ceph-orchestrator-if-necessary

ceph mgr module enable rook
ceph mgr module enable nfs
ceph orch set backend rook

Now we did

kubectl apply -f filesystem.yaml

kubectl apply -f nfs.yaml

And this what is happening when we described my-nfs

and this is the result

rook-ceph-nfs-controller failed to reconcile CephNFS "rook-ceph/my-nfs". failed to create ceph nfs deployments: failed to update ceph nfs "my-nfs": failed to create RADOS config object: failed to create initial rados config object: signal: interrupt
Warning ReconcileFailed 4m59s (x17 over 22m) rook-ceph-nfs-controller failed to reconcile CephNFS "rook-ceph/my-nfs". failed to create ceph nfs deployments: failed to update ceph nfs "my-nfs": failed to create RADOS config object: failed to create initial rados config object: signal: interrupt

This is happening wherever we deploy this on different clusters too. I think you guiys need to check into it and need be fixed or can you guys help me if i am doing something wrong. I am struggling with ir from multiple days

**Comment by microyahoo** [comment]
hi @chaitusolasa, how is your ceph cluster and cephfs? You should make sure your ceph cluster and cephfs are healthy before creating ceph nfs.

**Comment by parth-gr** [comment]
is multus enabled in your cluster?
