### ISSUE TITLE
rook-tools ceph no longer works

### ISSUE THREAD

**Issue by jpds** [rook/rook#1203]
After updating my `rook-tools` manifest, I can no longer use ceph commands from the `rook-tools` pod:

```
$ kubectl exec -it -n rook rook-tools -- ceph 
server name not found: rook-ceph-mon13=10.233.46.13 (Name or service not known)
unable to parse addrs in '10.233.33.241:6790,rook-ceph-mon13=10.233.46.13:6790,rook-ceph-mon15=10.233.17.75:6790,rook-ceph-mon12=10.233.8.68:6790,rook-ceph-mon11=10.233.14.128:6790'
InvalidArgumentError does not take keyword arguments
command terminated with exit code 1
```

`rookctl status` is fine.

**Comment by travisn** [comment]
@jpds sounds like there is some formatting problem with the script that initializes the toolbox. 
- What are the contents of `/etc/rook/mon-endpoints`?
- What is the output of this command? `cat /etc/rook/mon-endpoints | sed 's/rook-ceph-mon[0-9]=//g'`

**Comment by jpds** [comment]
```
root@rook-tools:/# cat /etc/rook/mon-endpoints 
rook-ceph-mon8=10.233.33.241:6790,rook-ceph-mon13=10.233.46.13:6790,rook-ceph-mon15=10.233.17.75:6790,rook-ceph-mon12=10.233.8.68:6790,rook-ceph-mon11=10.233.14.128:6790
```

And:

```
root@rook-tools:/# cat /etc/rook/mon-endpoints | sed 's/rook-ceph-mon[0-9]=//g'
10.233.33.241:6790,rook-ceph-mon13=10.233.46.13:6790,rook-ceph-mon15=10.233.17.75:6790,rook-ceph-mon12=10.233.8.68:6790,rook-ceph-mon11=10.233.14.128:6790
```

**Comment by travisn** [comment]
aha, the bug is that the mons have double digit names

**Comment by exodussystem** [comment]
I have the same issue with v0.8.1. In my case, server prefix is not 'rook-ceph-mon', just 'a','b','c'

# **ceph status** 
server name not found: a=10.233.28.142 (Name or service not known)
unable to parse addrs in 'a=10.233.28.142:6790,b=10.233.8.33:6790,c=10.233.10.79:6790'
InvalidArgumentError does not take keyword arguments

#  **cat /etc/rook/mon-endpoints**
a=10.233.28.142:6790,b=10.233.8.33:6790,c=10.233.10.79:6790

**Comment by galexrt** [comment]
@exodussystem Your toolbox image seems to be too old.
If you are using `master` as the toolbox image tag, try setting it to `v0.8.1` and/or (re-)pulling the currently used image (tag) on all your nodes.
Let us know if that fixes your issue.

**Comment by KrzysztofWloch** [comment]
Same here, on v0.8.1

**Comment by exodussystem** [comment]
@galexrt Thanks, I tried to pull the latest docker image with :master tag, it worked.

**Comment by Vanuan** [comment]
BTW, this is documented here:

https://rook.io/docs/rook/v0.8/toolbox.html

Does it mean that 0.8.2 is too old? There's no newer release.
`:master` works OTOH

**Comment by galexrt** [comment]
@exodussystem @Vanuan @KrzysztofWloch Which Rook version are you running?
You are probably running an image tag which is not `v0.8.2` (or another `v0.8.x` release), but a build from `master`.

If you are running a `master` build (everything not just having `v0.8.2` as a tag name, you also must use the `master` build tag toolbox and also switch back to a tagged release Rook version ASAP (e.g., upcoming `v0.9`) as there is no way back with the new mons in `master` and upcoming `v0.9` to `v0.8.x` release.
