### ISSUE TITLE
Allow pools to use a non-default root in the crush map

### ISSUE THREAD

**Issue by travisn** [rook/rook#1204]
When pools are created through the pool, object, or file CRD, they currently use the default root in the CRUSH map. If the ceph tools have been used to create a new root (see the advanced configuration docs), the pools should have the option to be created in any root.

**Comment by jbw976** [comment]
why was this closed @kokhang?

**Comment by travisn** [comment]
@dgonzalezruiz do you have a new PR for this issue? Would be great to have this soon. Thanks!
