### ISSUE TITLE
grafana dashboards: exclude `pod` from queries

### ISSUE THREAD

**Issue by uhthomas** [rook/rook#12050]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The metrics are scraped from the manager pods, of which there are multiple instances. The Grafana dashboards break a bit when:
- There is a new deployment for the managers
- The primary manager changes

![image](https://user-images.githubusercontent.com/9749173/230721635-551508d3-77f3-46b2-a570-bb9efa55a92c.png)

**Expected behavior:**

The dashboards should handle different manager pods.

**How to reproduce it (minimal and precise):**

Use https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-monitoring/#grafana-dashboards and trigger a new deployment of the manager. Observe there are duplicate metrics.

Side note: I was wondering if it would be possible to de duplicate this at the service monitor level but knowing which pod metrics came from could actually be useful. It may just be better to update the dashboards.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
> trigger a new deployment of the manager. Observe there are duplicate metrics.

@uhthomas What exactly does this mean? Are you changing the `mgr.count` from `1` to `2`? Or how are you triggering a new mgr? 

Are you seeing this issue with Rook v1.11.x? Or what version? 

Could you test if you see this issue with the `rook/ceph:master` image? There was a change recently merged with #11845 which may solve this issue. It has not yet been backported to v1.11 so we could give it more time to test. If you can validate this scenario is fixed, it will help know if it's ready to backport.

**Comment by uhthomas** [comment]
> > trigger a new deployment of the manager. Observe there are duplicate metrics.
> 
> @uhthomas What exactly does this mean? Are you changing the `mgr.count` from `1` to `2`? Or how are you triggering a new mgr?
> 
> Are you seeing this issue with Rook v1.11.x? Or what version?
> 
> Could you test if you see this issue with the `rook/ceph:master` image? There was a change recently merged with #11845 which may solve this issue. It has not yet been backported to v1.11 so we could give it more time to test. If you can validate this scenario is fixed, it will help know if it's ready to backport.

Sorry. This is using the absolute latest version of rook with that patch applied. This occurs when the either the deployment for the manager is changed (i.e version update, config change) or if the active manager changes.

**Comment by travisn** [comment]
> Sorry. This is using the absolute latest version of rook with that patch applied. This occurs when the either the deployment for the manager is changed (i.e version update, config change) or if the active manager changes.

Thanks for the clarification. Do you see this same behavior when the change from #11845 is not applied? For example, does the latest v1.11.3 have this behavior?

**Comment by uhthomas** [comment]
I haven't tried, though I don't see how this change would affect anything. It just seems like the queries need to be updated to exclude the pod.

**Comment by travisn** [comment]
The metrics are only expected to be scraped from the active mgr. The passive mgr pod is not expected to be queried, according to the selectors on the service monitor. However, I see now that the `mgr_role: active` selector is missing on the [service monitor](https://github.com/rook/rook/blob/master/deploy/examples/monitoring/exporter-service-monitor.yaml#L12-L16). Does adding the label `mgr_role: active` to the service monitor selector fix the issue?

**Comment by uhthomas** [comment]
> The metrics are only expected to be scraped from the active mgr. The passive mgr pod is not expected to be queried, according to the selectors on the service monitor. However, I see now that the `mgr_role: active` selector is missing on the [service monitor](https://github.com/rook/rook/blob/master/deploy/examples/monitoring/exporter-service-monitor.yaml#L12-L16). Does adding the label `mgr_role: active` to the service monitor selector fix the issue?

That's an interesting observation, though I imagine it may not be necessary? I believe the service itself will filter out the inactive mgr.

This is about longer time ranges. If the active manager stays the same for a few days, that's fine. The problem occurs when a different manager is being queried. Hopefully these screenshots can help illustrate this better.

A short time range is fine:

![image](https://user-images.githubusercontent.com/9749173/231600419-56a37a1a-6a3c-4696-ae9c-e0659191b351.png)

A longer time range is not:

![image](https://user-images.githubusercontent.com/9749173/231600449-a53c46c8-028c-4d38-9cc9-fe72b48d79a0.png)

If we take one of the broken metrics and sum by `pod` then we can see that this is because a completely different pod is being used. This is because I made a change to the CephCluster earlier (I set resource requests and limits for everything).

![image](https://user-images.githubusercontent.com/9749173/231600763-05be185b-4625-43b7-a41c-cc5004d12c81.png)

Does this make sense?

**Comment by RufatRoot** [comment]
> > The metrics are only expected to be scraped from the active mgr. The passive mgr pod is not expected to be queried, according to the selectors on the service monitor. However, I see now that the `mgr_role: active` selector is missing on the [service monitor](https://github.com/rook/rook/blob/master/deploy/examples/monitoring/exporter-service-monitor.yaml#L12-L16). Does adding the label `mgr_role: active` to the service monitor selector fix the issue?
> 
> That's an interesting observation, though I imagine it may not be necessary? I believe the service itself will filter out the inactive mgr.
> 
> This is about longer time ranges. If the active manager stays the same for a few days, that's fine. The problem occurs when a different manager is being queried. Hopefully these screenshots can help illustrate this better.
> 
> A short time range is fine:
> 
> ![image](https://user-images.githubusercontent.com/9749173/231600419-56a37a1a-6a3c-4696-ae9c-e0659191b351.png)
> 
> A longer time range is not:
> 
> ![image](https://user-images.githubusercontent.com/9749173/231600449-a53c46c8-028c-4d38-9cc9-fe72b48d79a0.png)
> 
> If we take one of the broken metrics and sum by `pod` then we can see that this is because a completely different pod is being used. This is because I made a change to the CephCluster earlier (I set resource requests and limits for everything).
> 
> ![image](https://user-images.githubusercontent.com/9749173/231600763-05be185b-4625-43b7-a41c-cc5004d12c81.png)
> 
> Does this make sense?

In this case Endpoint created without mgr_role: active which is causing Prometheus to skip this Endpoint as a target.

**Comment by travisn** [comment]
Since Rook v1.11.7 have you seen a change in behavior? With the fix of #11845 and #12268, I wonder if this is still an issue.

**Comment by RufatRoot** [comment]
> Since Rook v1.11.7 have you seen a change in behavior? With the fix of #11845 and #12268, I wonder if this is still an issue.

I was using v1.11.6. Updating chart to version v1.11.7 didn't fixed the issue as well. Also tried to completely disable monitoring for operator and cluster resources and re-enabling them again which didn't solved the issue.

**Comment by RufatRoot** [comment]
> > Since Rook v1.11.7 have you seen a change in behavior? With the fix of #11845 and #12268, I wonder if this is still an issue.
> 
> I was using v1.11.6. Updating chart to version v1.11.7 didn't fixed the issue as well. Also tried to completely disable monitoring for operator and cluster resources and re-enabling them again which didn't solved the issue.

Ignore my previous message. v1.11.7 fixed the issue.

**Comment by galexrt** [comment]
@RufatRoot Do the dashboards need to be updated or did the update to v1.11.7+ fix the dashboards for you already?

**Comment by uhthomas** [comment]
> Since Rook v1.11.7 have you seen a change in behavior? With the fix of #11845 and #12268, I wonder if this is still an issue.

This is still an issue. The dashboards will break whenever the `pod` value changes, which occurs either when a new manager deployment is created (e.g during upgrades) or if the active manager changes. The fix here is to exclude `pod` from the dashboards.

**Comment by travisn** [comment]
@uhthomas Are you still seeing this issue in v1.12?
