### ISSUE TITLE
Add official rook helm charts to ArtifactHub

### ISSUE THREAD

**Issue by zalsader** [rook/rook#12059]
It would be nice to have the official rook helm charts published on https://artifacthub.io/

Here's how to do it:
- Someone needs to create an organization in https://artifacthub.io/
- Add a repository in the organization settings
- (optional but recommended): make sure that the publisher is [verified](https://artifacthub.io/docs/topics/repositories/#verified-publisher) and [official](https://artifacthub.io/docs/topics/repositories/#official-status)

**Why?**

It makes rook easier to find and install.

**Comment by travisn** [comment]
Is it possible to completely automate this so we could make it part of our release CI workflow? If there is any manual process to updates, it will be challenging to keep updated.

**Comment by zalsader** [comment]
Once the repository is added to artifacthub, they periodically process the index.yaml file and add new versions without needing any human intervention. Once it is set up once, you don't need to do anything.

**Comment by subhamkrai** [comment]
I already see we have https://artifacthub.io/packages/helm/rook/rook-ceph

**Comment by zalsader** [comment]
> I already see we have [artifacthub.io/packages/helm/rook/rook-ceph](https://artifacthub.io/packages/helm/rook/rook-ceph)

In that case, we can [claim ownership of that package](https://artifacthub.io/docs/topics/repositories/#ownership-claim) since it was not published by a rook member

**Comment by galexrt** [comment]
We have created the Rook orga on ArtifactHub. We need the credentials for the helm chart repo server to add the file for verification.

**Comment by travisn** [comment]
@galexrt The creds are configured now, right? What is remaining?

**Comment by zalsader** [comment]
This could be closed as done since rook is on artifact hub and has official status: https://artifacthub.io/packages/helm/rook/rook-ceph
