### ISSUE TITLE
Cluster created with encryption without requiremsgr2, doesnt switch to v1 ports when encryption is disabled

### ISSUE THREAD

**Issue by malayparida2000** [rook/rook#12063]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
If a cluster is created with Encryption enabled but Requiremsgr2 is not marked true, the mons created have only v2 ports. If encryption is now disabled, Requiremsgr2 is also not marked as true,
csi driver configmap still shows v2 ports & mounting of pods fail

**Expected behavior:**
Rook should always start mons with both v1 & v2 ports.
Then csi driver should be updated to use v1 ports instead of v2 ports in the case
when encryption or compression is now disabled & require msgr2 is also not true.

**How to reproduce it (minimal and precise):**

Create cluster with encryption on, but don't requiremsgr2.
Now disable encryption, csi driver is still on v2 ports.
Try to create pvc+pod mounting will fail as the rbd map option/cephfs mount option are passing option expecting v1 port
but its actually v2 ports.

**Comment by malayparida2000** [comment]
@travisn We need to create mons with both v1 & v2 ports present always.

**Comment by travisn** [comment]
While we could choose to always enable the v1 and v2 ports, I'm concerned about this change for the following reasons:
- Switching back and forth between encryption and non-encryption does not have a smooth transition, even if we do have both ports enabled. Existing volumes would continue using their encryption setting at least until they are re-mounted.
- What is the user scenario for needing to disable encryption after it is enabled? It's just not a real user scenario from what I have heard. 
- Upstream has had this behavior for the past year. Switching back and forth between encryption and non-encryption has not been requested upstream.
- If the admin really wants to turn off encryption, it is still possible. They would just need to fail over the mons after disabling the encryption, to get the mons with v1 port enabled again.
- msgr2 is the long-term preferred protocol for ceph and eventually msgr1 would be deprecated. For clusters that have a new enough kernel and are using msgr2 features, it's a good way to start the transition and just move completely to the new protocol.

**Comment by Madhu-1** [comment]
>If the admin really wants to turn off encryption, it is still possible. They would just need to fail over the mons after disabling the encryption, to get the mons with v1 port enabled again.

I only see the option to toggle between encryption on/off when someone sees a performance issue, and I dont expect it to happen on the fly and frequently, but good to have a documented way to have this option.

**Comment by malayparida2000** [comment]
Okay, Leave aside encryption. Lets consider another scenario.
A cluster is created with Requiremsgr2, So the mons come up with only v2 ports. After some time if someone turns off RequireMSgr2. Now our mons don't have v1 ports so volume mountings will now start to fail.

>>msgr2 is the long-term preferred protocol for ceph and eventually msgr1 would be deprecated. For clusters that have a new enough kernel and are using msgr2 features, it's a good way to start the transition and just move completely to the new protocol.
Agreed, msgr2 is the way forward. But as long as ceph hasn't deprecated v1 port & rook upstream still uses v1 port by default, lets keep v1 the default in downstream ocs also & lets keep both v1 & v2 port in my opinion

**Comment by malayparida2000** [comment]
Had a discussion with Madhu over a call where he put forward some important points in favour of not having the v1 port when encryption is enabled. But another question in my mind is which port should we by default use? Like right now if somebody installs 4.13 they will start with Requiremsgr2 as true & v2 will be the only port available. Do we want it that way only? Or do we want to stick with v1 port for installations where encryption/compression is not enabled.

**Comment by travisn** [comment]
> A cluster is created with Requiremsgr2, So the mons come up with only v2 ports. After some time if someone turns off RequireMSgr2. Now our mons don't have v1 ports so volume mountings will now start to fail.

I don't see the need to support this scenario. If they have a new enough kernel to use v2, they have no reason to disable it.

> Agreed, msgr2 is the way forward. But as long as ceph hasn't deprecated v1 port ,lets keep both v1 & v2 ports available in the mons & as long as rook upstream still uses v1 port by default, lets keep v1 the default in downstream ocs also in my opinion

The only reason it's not the default upstream is because we don't know if the kernel is new enough. This reason doesn't hold for downstream, but this discussion here is only for upstream. 

> So may be the optimal solution would be to start the mons only with v2 ports, if the cluster is created with encryption or compression from the beginning. But for all other cases like even if RequireMSgr2 is true but Encryption is not enabled we can start with both v1& v2 ports. But another question in my mind is which port should we by default use? Like right now if somebody installs 4.13 they will start with Requiremsgr2 as true & v2 will be the only port available. Do we want it that way only? Or do we want to stick with v1 port for installations where encryption/compression is not enabled?

Is there any transition/upgrade issue? I still don't see a reason not to require msgr2 since the kernel is new enough. But let's not have downstream discussion here.

**Comment by malayparida2000** [comment]
Thanks @travisn @Madhu-1 . According to the discussion I think we can close this issue.
