### ISSUE TITLE
Excessive OSD memory usage

### ISSUE THREAD

**Issue by uhthomas** [rook/rook#12078]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Similar to https://github.com/rook/rook/issues/11930, maybe? There are no resource requests or limits defined on the OSD deployments.

Ceph went through a few days of recovery and some OSD pods topped out at 70Gi of memory(!!). They then stabilised at around 40Gi.

![image](https://user-images.githubusercontent.com/9749173/231577764-befcf748-a7a0-4fe7-abe2-39a92e3a82e8.png)

In total, 10 OSDs used around 256Gi of memory(!!). 

![image](https://user-images.githubusercontent.com/9749173/231578174-dd1e0e7b-b368-489f-b047-099521fc6cb0.png)

A restart of the OSD deployment shows it goes down to "normal" levels.

![image](https://user-images.githubusercontent.com/9749173/231577856-c12262d6-e2f1-44a6-8beb-24698d70ffbd.png)

**Expected behavior:**

The OSDs should not use 70Gi of memory.

**How to reproduce it (minimal and precise):**

As usual, I am really not sure. I'm just using ceph. The was a global recovery event which lasted a few days (replaced two OSDs).

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): Talos v1.3.6
* Kernel (e.g. `uname -a`): `Linux rook-ceph-tools-b84c4448f-gw9s9 5.15.102-talos #1 SMP Mon Mar 13 18:10:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.11.3
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.26.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Talos
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_WARN clock skew detected on mon.b, mon.c

**Comment by uhthomas** [comment]
`top` from inside an OSD container.

![image](https://user-images.githubusercontent.com/9749173/231580196-f2504b09-01de-4b97-a256-6a0157fa8e85.png)

**Comment by travisn** [comment]
The OSDs are designed to consume all the available memory if they are run without limits. So it is recommended to apply the resource limits, and the OSDs will stay within the bounds you set. Typically 4GB is sufficient per OSD.

**Comment by uhthomas** [comment]
Following https://docs.ceph.com/en/latest/rados/troubleshooting/memory-profiling/:

```
bash-4.4$ ceph tell osd.6 heap start_profiler
osd.6 started profiler
bash-4.4$ ceph tell osd.6 heap dump
osd.6 dumping heap profile now.
------------------------------------------------
MALLOC:    16060310368 (15316.3 MiB) Bytes in use by application
MALLOC: +            0 (    0.0 MiB) Bytes in page heap freelist
MALLOC: +   2294877000 ( 2188.6 MiB) Bytes in central cache freelist
MALLOC: +      4712448 (    4.5 MiB) Bytes in transfer cache freelist
MALLOC: +     34900312 (   33.3 MiB) Bytes in thread cache freelists
MALLOC: +    156106752 (  148.9 MiB) Bytes in malloc metadata
MALLOC:   ------------
MALLOC: =  18550906880 (17691.5 MiB) Actual memory used (physical + swap)
MALLOC: +  14371897344 (13706.1 MiB) Bytes released to OS (aka unmapped)
MALLOC:   ------------
MALLOC: =  32922804224 (31397.6 MiB) Virtual address space used
MALLOC:
MALLOC:        1962481              Spans in use
MALLOC:             41              Thread heaps in use
MALLOC:           8192              Tcmalloc page size
------------------------------------------------
Call ReleaseFreeMemory() to release freelist memory to the OS (via madvise()).
Bytes released to the OS take up virtual address space but no physical memory.
```

profile: https://gist.github.com/uhthomas/cc96208190340d8a3b1f71d9cd5866bd

**Comment by uhthomas** [comment]
> The OSDs are designed to consume all the available memory if they are run without limits. So it is recommended to apply the resource limits, and the OSDs will stay within the bounds you set. Typically 4GB is sufficient per OSD.

Ah, hm. I'll set some limits.
