### ISSUE TITLE
failed to generate osd keyring

### ISSUE THREAD

**Issue by kashif-nawaz** [rook/rook#12076]
<!-- **Are you in the right place?**

I am new to ROOk and Ceph and trying to bring up Ceph cluster over my k8s cluster using following procedure but getting error logs for osd pods "rookcmd: failed to configure devices: failed to generate osd keyring: failed to get or create auth key f" 

  for domain in worker{1..3}; do
   sudo virsh vol-create-as images ${domain}-disk-2.qcow2 50G
  done

  for domain in worker{1..3}; do   
    sudo virsh attach-disk --domain ${domain}     --source /var/lib/libvirt/images/${domain}-disk-2.qcow2      --persistent --target vdb; 
  done

 lsblk
  NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
  sr0     11:0    1  368K  0 rom
  vda    253:0    0  100G  0 disk
  `-vda1 253:1    0  100G  0 part /
  vdb    253:16   0   50G  0 disk

 git clone --single-branch --branch v1.10.4 https://github.com/rook/rook.git
 cd rook/deploy/examples
 kubectl create -f crds.yaml -f common.yaml -f operator.yaml

kubectl config set-context --current --namespace rook-ceph

 vim ~/rook/deploy/examples/cluster.yaml

storage: # cluster level storage configuration and selection
  useAllNodes: false
  useAllDevices: false
  #deviceFilter:
  nodes:
  - name: "worker4"
    devices: # specific devices to use for storage can be specified for each node
    - name: "vdb"
  - name: "worker5"
    devices:
    - name: "vdb"
  - name: "worker6"
    devices:
    - name: "vdb"
kubectl apply -f cluster.yaml

rookcmd: failed to configure devices: failed to generate osd keyring: failed to get or create auth key for client.bootstrap-osd: failed get-or-create-key client.bootstrap-osd: exit status 1
ubuntu@deployer-node:~$ kubectl logs -f rook-ceph-osd-prepare-worker5-mr8db -n rook-ceph
Error from server (NotFound): pods "rook-ceph-osd-prepare-worker5-mr8db" not found

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
Please open bugs with the issue template filled in, there are no details to troubleshoot
