### ISSUE TITLE
oomkill when removing and adding back osd-s

### ISSUE THREAD

**Issue by zlangi** [rook/rook#12091]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Expected behaviour should be for the OSD to start with its allocated 4GB of memory, but needs 16GB to able to start after recreation.

**Expected behavior:**
Expected behaviour is to start with 4GB of ram.

**How to reproduce it (minimal and precise):**
We have 2 OSD-s per nvme to utilise the full bandwidth of the nvme device.

1. disable the operator
2. out the osd-s, remove the osd-s from the working cluster, delete them from crush map
3. remove the deploment
4. remove the partition from the disk and all the remaining files remaining on the server
5. zap all the data from the disk
6. add the new disk in or use the existing one you remove the partition from
7. reenable the operator and let it to prepare the new disk and start the new osd pods
8. watch the process being out of memory killed with the following message:
```
debug 2023-04-13T14:01:11.137+0000 7f1d89b113c0  0 osd.46 3070855 done with init, starting boot process
debug 2023-04-13T14:01:45.398+0000 7f1d812fd700 -1 received  signal: Terminated from Kernel ( Could be generated by pthread_kill(), raise(), abort(), alarm() ) UID: 0
debug 2023-04-13T14:01:45.398+0000 7f1d812fd700 -1 osd.46 3070855 *** Got signal Terminated ***
debug 2023-04-13T14:01:45.398+0000 7f1d812fd700  0 osd.46 3070855 Fast Shutdown: - cct->_conf->osd_fast_shutdown = 1, null-fm = 1
debug 2023-04-13T14:01:45.398+0000 7f1d812fd700 -1 osd.46 3070855 *** Immediate shutdown (osd_fast_shutdown=true) ***
debug 2023-04-13T14:01:45.398+0000 7f1d812fd700  0 osd.46 3070855 prepare_to_stop starting shutdown
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.5 LTS
* Kernel (e.g. `uname -a`): #58~20.04.1-Ubuntu
* Cloud provider or hardware configuration: 1TB RAM, 2x AMD EPYC 7452 32-Core Processor
* Rook version (use `rook version` inside of a Rook Pod): v1.9.9
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.10
* Kubernetes version (use `kubectl version`): v1.23.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): rancher deployed k8s

Details: 
Hi dear rook team, we have a pretty standard ceph cluster, 12 nodes, 5 nvme disks per node, 2 OSD per nvme disk (120 OSD in total) setup. We have 6 cores limit set per OSD and 4GB memory per OSD.
We have been seeing weird out of memory kills when removing OSD-s from an existing working cluster and readding them (for example swapping the disk out underneath the OSD-s due to disk failure). Our OSD-s are having 4GB memory assigned to them by default and they can stop and start with this amount without problem problems, however when the OSD has to be removed due to a disk replacement event, the memory of the pod has to be increased to 16GB or the OSD's pod will be killed the following way by the kernel:
```
[12955737.402496] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=cri-containerd-8d1d3fec125feaf6a6879fda9665e91f4a7df52da8f0741610cadcdd2cbd0228.scope,mems_allowed=0-1,oom_memcg=/kubepods.slice/kubepods-podcbf40e79_e078_45cf_bbe8_f596d1636d22.slice,task_memcg=/kubepods.slice/kubepods-podcbf40e79_e078_45cf_bbe8_f596d1636d22.slice/cri-containerd-8d1d3fec125feaf6a6879fda9665e91f4a7df52da8f0741610cadcdd2cbd0228.scope,task=ceph-osd,pid=166342,uid=167
[12955737.402706] Memory cgroup out of memory: Killed process 166342 (ceph-osd) total-vm:14076784kB, anon-rss:8354824kB, file-rss:34840kB, shmem-rss:0kB, UID:167 pgtables:26668kB oom_score_adj:-997
[12955739.217158] oom_reaper: reaped process 167135 (ceph-osd), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[12955740.432518] oom_reaper: reaped process 166342 (ceph-osd), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
In order to get out of the kill loop, we have to increase the memory limit to 16GB and only then the OSD-s can finally start.

**Comment by travisn** [comment]
@rzarzynski What would cause the OSDs to require more memory the first time they start? Is it due to the large cluster, large PGs, etc? Is there a solution to allow the OSD to start with less memory?
