### ISSUE TITLE
I use rook deploy ceph on k8s, but can't use cephfs  in annother k8s, but can use at the ceph k8s.

### ISSUE THREAD

**Issue by andyzheung** [rook/rook#12096]
I have write a issue at ceph-csi github:
https://github.com/ceph/ceph-csi/issues/3749

**Comment by Madhu-1** [comment]
@andyzheung can you please check you have the required connectivity using https://rook.io/docs/rook/latest/Troubleshooting/ceph-csi-common-issues/
