### ISSUE TITLE
Unable to umount /dev/rbd1 after rbd unmap -o force /dev/rbd1 in k8s

### ISSUE THREAD

**Issue by bbccaaac** [rook/rook#12090]
**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.9.2009 (Core)
* Kernel (e.g. `uname -a`): 3.10.0-1160.el7.x86_64
* Rook version (use `rook version` inside of a Rook Pod): v1.11.2
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.24.8

Pod failed to run on other node after deployment restart.
 `Warning FailedMount  37m (x3 over 49m)   kubelet  Unable to attach or mount volumes: unmounted volumes=[host-volume-rocketmq-broker-master-prod], unattached volumes=[kube-api-access-bkf24 host-volume-rocketmq-broker-master-prod]: timed out waiting for the condition
  Warning_  FailedMount  22m (x20 over 49m)  kubelet  MountVolume.MountDevice failed for volume "pvc-6f41a030-e718-4dec-8ca8-39dc7917b547" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000002-e1cf85c6-3b08-4491-b047-4ddcf93334fe already exists
 Warning  FailedMount  10m (x11 over 38m)  kubelet  MountVolume.MountDevice failed for volume "pvc-6f41a030-e718-4dec-8ca8-39dc7917b547" : rpc error: code = Internal desc = rbd image ceph-blockpool/csi-vol-e1cf85c6-3b08-4491-b047-4ddcf93334fe is still being used`

I executed `rbd unmap -o force /dev/rbd1` on old node. New pod start. Old node still exists mounted disk.
`[root@w1 ~]#  df -h | grep rbd
/dev/rbd0                      20G  1.7G   18G   9% /var/lib/kubelet/pods/e7d3dc87-cda4-40db-8ce8-82cb32de82c8/volumes/kubernetes.io~csi/pvc-b1c66cf6-d674-40ab-b6fd-54396dd48517/mount
/dev/rbd1                      40G   74M   40G   1% /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/78b1f9019ce31b7c27fa4a6cd28693f6ee4f499c1e9d892f819d09fcf1cd42a5/globalmount/0001-0009-rook-ceph-0000000000000002-60d160ed-dba8-4267-831c-ad177b4c5e5c`

Failed to umount.
`[root@w1 ~]# umount /dev/rbd1
umount: /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/78b1f9019ce31b7c27fa4a6cd28693f6ee4f499c1e9d892f819d09fcf1cd42a5/globalmount/0001-0009-rook-ceph-0000000000000002-60d160ed-dba8-4267-831c-ad177b4c5e5c: target is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
[root@w1 ~]# ls /dev/rbd1
ls: cannot access /dev/rbd1: No such file or directory`

No return executed lsof
`[root@w1 ~]# lsof /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/78b1f9019ce31b7c27fa4a6cd28693f6ee4f499c1e9d892f819d09fcf1cd42a5/globalmount/0001-0009-rook-ceph-0000000000000002-60d160ed-dba8-4267-831c-ad177b4c5e5c
[root@test ~]#`

**Comment by Madhu-1** [comment]
@bbccaaac can you please also umount on the old node and wait for 5 to 10 minutes for watcher to go away? if you are sure that no one is using this rbd image you can try https://koor.tech/blog/2023/troubleshooting-rbd-mount-problems-rook-ceph/ to blocklist the IP (blocklist IP:nonce not just IP if the node is still part of kube cluster and you have some workloads running on it)of old node

**Comment by bbccaaac** [comment]
I tried,but the problem is still there.  I found rbd mounted twice in this k8s cluster, like this:
[root@w1 ~]# mount | grep rbd
/dev/rbd0 on /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/c14143fee9033774d6d5b05182a8e64cf0e4efa52e6b64bfdd13aeddc70a28ba/globalmount/0001-0009-rook-ceph-0000000000000002-fd42cf82-ac93-4b42-81f8-4930c365681d type ext4 (rw,relatime,stripe=1024,data=ordered,_netdev)
/dev/rbd0 on /var/lib/kubelet/pods/cba5719a-a050-44d1-94bd-94ecfe6db5fb/volumes/kubernetes.io~csi/pvc-6842e357-171f-4f01-b64c-3e5db9351abe/mount type ext4 (rw,relatime,stripe=1024,data=ordered,_netdev)

After executed 'rbd unmap -o force', the first globalmount is unable to unmount.  The second mountpoint unmounted.

**Comment by Madhu-1** [comment]
Have you tried umount with force option?

**Comment by bbccaaac** [comment]
Yes. This mount point (/var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com/c14143fee9033774d6d5b05182a8e64cf0e4efa52e6b64bfdd13aeddc70a28ba/globalmount/0001-0009-rook-ceph-0000000000000002-fd42cf82-ac93-4b42-81f8-4930c365681d) is unable to umount.  This mount point(/var/lib/kubelet/pods/cba5719a-a050-44d1-94bd-94ecfe6db5fb/volumes/kubernetes.iocsi/pvc-6842e357-171f-4f01-b64c-3e5db9351abe/mount)  was successfully unmounted.

**Comment by bbccaaac** [comment]
Although the global mount point has not been unmounted，my pod is running.
