### ISSUE TITLE
OSD pods do not start on k8s 1.6.4 and lower

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1209]
In master (and v0.6.0), OSD pods fail to start with the following message when running on Kuberenets 1.6.4 or lower:
```
$ kubectl -n rook get pod
NAME                              READY     STATUS                                         RESTARTS   AGE
rook-api-3536545610-54f3w         1/1       Running                                        0          23s
rook-ceph-mgr0-1387429650-b9xj6   1/1       Running                                        0          24s
rook-ceph-mgr1-2636939030-rmwws   1/1       Running                                        0          23s
rook-ceph-mon0-rwx00              1/1       Running                                        0          55s
rook-ceph-mon1-pfg7r              1/1       Running                                        0          44s
rook-ceph-mon2-h4d1w              1/1       Running                                        0          36s
rook-ceph-osd-32bkx               0/1       container's runAsUser breaks non-root policy   0          23s
```

This is a regression associated with #1188

This appears to be the upstream Kuberentes issue: https://github.com/kubernetes/kubernetes/issues/46996

**Comment by bassam** [comment]
The fix happened here: https://github.com/kubernetes/kubernetes/commit/07a67c252cacdb64da6dd951fcb0357aa1a10f75#diff-08c8f9ff3cc05ba7009dc6a00cba8fa7R76

It looks like we can remove this line and we would be OK: https://github.com/phsiao/rook/blob/master/pkg/operator/osd/osd.go#L292

@phsiao can you please take a look and test on < 1.6.4 and > 1.7

**Comment by phsiao** [comment]
Taking a look in a bit.
