### ISSUE TITLE
Enabling prometheus mgr module via CephCluster CR not being respected.

### ISSUE THREAD

**Issue by benlsheets** [rook/rook#12097]
Ultimately I'm trying to scrape Ceph metrics using Prometheus NOT installed via the Prometheus Operator. It was working for me until the v1.11.3 upgrade which included [this](https://github.com/rook/rook/pull/11980) change disabling the Prometheus mgr module. After upgrading to v1.11.3 my mgr pods started refusing connections on port 9283.

Initially I tried setting spec.monitoring.enabled to true in the CephCluster CR. That led to the CephCluster failing reconciliation because the ServiceMonitor CRD and permissions didn't exist.

Next I tried enabling the Prometheus mgr module via spec.mgr.modules in the CephCluster CR. The Rook-Ceph-Operator never recognizes this as a change and never updates the mgr deployments.

Next I used the rook-ceph-tools pod to manually enable the Prometheus mgr module using `ceph mgr module enable prometheus`. That fixes my issue for a while but at some point the operator or something else disables the module again.

If the intention is for the Prometheus mgr module to be governed by the spec.monitoring.enabled setting can we maybe add another sub-setting to enable or disable the use of service monitors?

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
[cluster.txt](https://github.com/rook/rook/files/11243044/cluster.txt)

* Operator's logs, if necessary
[operator-logs.txt](https://github.com/rook/rook/files/11243045/operator-logs.txt)

* Output of krew commands, if necessary
[ceph-status.txt](https://github.com/rook/rook/files/11243049/ceph-status.txt)

* OS (e.g. from /etc/os-release):
`PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy`

* Kernel (e.g. `uname -a`):
`Linux hci-01 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
`Bare metal servers`
* Rook version (use `rook version` inside of a Rook Pod):
`rook: v1.11.3
go: go1.19.7`
* Storage backend version (e.g. for ceph do `ceph -v`):
`ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)`
* Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
`kubeadm`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
`HEALTH_OK`

**Comment by travisn** [comment]
@benlsheets We weren't aware of a scenario where the prometheus module was necessary unless the prometheus operator was also available. To be clear, all you need is for the prometheus module to be enabled in ceph, correct?

To fix this, I like the approach of Rook respecting enabling the prometheus module if it's in the list of modules to enable. I imagine currently with that setting, rook is enabling the module, then immediately disabling it again when it gets to the monitoring reconcile. So the fix would be if this is found in the cluster CR, rook would honor that setting:
```yaml
modules:
  - name: prometheus
    enabled: true
```

@thenamehasbeentake As a follow up to #11980 might you be available to make that change?

**Comment by thenamehasbeentake** [comment]
> @benlsheets We weren't aware of a scenario where the prometheus module was necessary unless the prometheus operator was also available. To be clear, all you need is for the prometheus module to be enabled in ceph, correct?
> 
> To fix this, I like the approach of Rook respecting enabling the prometheus module if it's in the list of modules to enable. I imagine currently with that setting, rook is enabling the module, then immediately disabling it again when it gets to the monitoring reconcile. So the fix would be if this is found in the cluster CR, rook would honor that setting:
> 
> ```yaml
> modules:
>   - name: prometheus
>     enabled: true
> ```
> 
> @thenamehasbeentake As a follow up to #11980 might you be available to make that change?

Just change `monitoring` `enabled` true.
~~~
  monitoring:
    enabled: true
~~~
After https://github.com/rook/rook/pull/11980 merged, ceph mgr prometheus module will be disabled by default.

Now `prometheusModule` belongs to `wellKnownModule`, and it can't be configured through `modules`.
https://github.com/rook/rook/blob/e6863481ffba6b0795c167889df5e0af1f99df7a/pkg/operator/ceph/cluster/mgr/mgr.go#L492

**Comment by benlsheets** [comment]
Thank you both for your quick response.

When I set spec.monitoring.enabled to true the prometheus mgr module never gets activated. Digging around I find the CephCluster continually giving the following event:

`kubectl describe cephcluster -n rook-ceph rook-ceph`
`Warning  ReconcileFailed  4m18s (x25 over 134m)  rook-ceph-cluster-controller  failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph mgr: failed to enable mgr services: failed to enable service monitor: service monitor could not be enabled: failed to retrieve servicemonitor. servicemonitors.monitoring.coreos.com "rook-ceph-mgr" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"`

The cluster controller's reconciliation is failing because I don't have the servicemonitors.monitoring.coreos.com CRD installed in my cluster. The ServiceMonitor CRD is installed by the Prometheus Operator which I'm not using.

How hard do you think it would be to add a setting so that the cluster controller doesn't try to implement ServiceMonitors or other CRDs managed by the Prometheus Operator?

**Comment by benlsheets** [comment]
I can get a working solution by using:
`kubectl create -f https://raw.githubusercontent.com/rook/rook/v1.11.3/deploy/examples/monitoring/rbac.yaml`
`kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.64.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml`
The cluster controller is able to reconcile successfully and the prometheus mgr module is successfully activated.

I see what you're saying about it being a wellKnownModule. I also definitely understand not wanting the prometheus mgr module to be governed by both spec.monitoring and spec.mgr.modules. Could we continue the trend of using the CephCluster to configure monitoring?
Maybe changing:
https://github.com/rook/rook/blob/e6863481ffba6b0795c167889df5e0af1f99df7a/pkg/operator/ceph/cluster/mgr/mgr.go#L287
To be something like:
`if c.spec.Monitoring.Enabled && c.spec.Monitoring.CRDs.Enabled {`

**Comment by thenamehasbeentake** [comment]
> same here, i have 3 ceph clusters in my k8s cluster, I try to enable prometheus module by using toolbox pod, but when I activate all of them, there will always be one that doesn't take effect. but I edit it on web dashboard, 3 ceph cluster3 are all works.
> 
> shell in toolbox
> 
> ```shell
> ceph mgr module enable prometheus
> ceph config set mgr mgr/prometheus/server_addr 0.0.0.0
> ceph config set mgr mgr/prometheus/server_port 9283
> ```
> 
> Is there a command to enable prometheus module as always-on?
> 
> ![image](https://user-images.githubusercontent.com/73102617/233012614-4e8f6a95-d148-4a3a-bd05-b8018421e6de.png)

Ceph mgr module prometheus  configured by cephclusters CRD. You can enable like this:
~~~
[root@smd-node01-prediction-prod-sz deeproute]# kubectl get cephclusters.ceph.rook.io  -n rook-ceph
NAME        DATADIRHOSTPATH   MONCOUNT   AGE   PHASE   MESSAGE                        HEALTH      EXTERNAL
rook-ceph   /var/lib/rook     3          46h   Ready   Cluster created successfully   HEALTH_OK   
[root@smd-node01-prediction-prod-sz deeproute]# 
[root@smd-node01-prediction-prod-sz deeproute]# 
[root@smd-node01-prediction-prod-sz deeproute]# kubectl edit  cephclusters.ceph.rook.io  rook-ceph  -n rook-ceph
~~~
And edit
~~~
  monitoring:
    enabled: true
~~~

If you want set mgr/prometheus/server_port and scrape_interval, you can set value of port and interval.

**Comment by benlsheets** [comment]
> i edit cephcluster yaml, but sometime svc rook-ceph-mgr:9283/metrics is down
> 
> ```
> ...
>   mgr:
>     modules:
>       - enabled: true
>         name: pg_autoscaler
>       - enabled: true
>         name: prometheus
>   mon:
>     allowMultiplePerNode: false
>     count: 3
>   monitoring:
>     enabled: true
> ...
> ```

Use `kubectl describe cephcluster -A` and look for events describing faults from the rook cluster controller. Are you using the Prometheus Operator to manage Prometheus in your cluster?

**Comment by m1iktea** [comment]
> > i edit cephcluster yaml, but sometime svc rook-ceph-mgr:9283/metrics is down
> > ```
> > ...
> >   mgr:
> >     modules:
> >       - enabled: true
> >         name: pg_autoscaler
> >       - enabled: true
> >         name: prometheus
> >   mon:
> >     allowMultiplePerNode: false
> >     count: 3
> >   monitoring:
> >     enabled: true
> > ...
> > ```
> 
> Use `kubectl describe cephcluster -A` and look for events describing faults from the rook cluster controller. Are you using the Prometheus Operator to manage Prometheus in your cluster?

Well, This cephcluster looks ok, but  svc rook-ceph-mgr:9283/metrics in this namespace cant be access, and of course im using Prometheus Operator to manage Prometheus in my cluster.

## cephcluster
```bash
root@k8s-123-96:~# kubectl describe cephcluster -n hdd-ceph
Name:         hdd-ceph
Namespace:    hdd-ceph
Labels:       <none>
Annotations:  <none>
API Version:  ceph.rook.io/v1
Kind:         CephCluster
Metadata:
  Creation Timestamp:  2022-05-06T09:41:20Z
  Finalizers:
    cephcluster.ceph.rook.io
  Generation:  6
  Managed Fields:
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
      f:spec:
        .:
        f:cephVersion:
        f:cleanupPolicy:
          .:
          f:sanitizeDisks:
            .:
            f:dataSource:
            f:iteration:
            f:method:
        f:crashCollector:
          .:
          f:disable:
        f:dashboard:
          .:
          f:enabled:
        f:dataDirHostPath:
        f:disruptionManagement:
          .:
          f:machineDisruptionBudgetNamespace:
          f:osdMaintenanceTimeout:
        f:external:
        f:healthCheck:
          .:
          f:daemonHealth:
            .:
            f:mon:
              .:
              f:interval:
            f:osd:
            f:status:
          f:livenessProbe:
            .:
            f:mgr:
            f:mon:
            f:osd:
        f:mgr:
        f:mon:
          .:
          f:count:
        f:monitoring:
          .:
          f:rulesNamespace:
        f:resources:
          .:
          f:osd:
            .:
            f:limits:
              .:
              f:memory:
            f:requests:
              .:
              f:memory:
        f:security:
          .:
          f:kms:
        f:storage:
          .:
          f:useAllDevices:
    Manager:      Mozilla
    Operation:    Update
    Time:         2022-07-06T03:33:33Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:cephVersion:
          f:image:
    Manager:      kubectl-patch
    Operation:    Update
    Time:         2023-04-19T07:21:35Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:mgr:
          f:modules:
        f:monitoring:
          f:enabled:
    Manager:      NGA_WP_JW
    Operation:    Update
    Time:         2023-04-19T08:04:22Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:healthCheck:
          f:daemonHealth:
            f:osd:
              f:interval:
            f:status:
              f:interval:
        f:logCollector:
        f:network:
          .:
          f:multiClusterService:
        f:security:
          f:keyRotation:
            .:
            f:enabled:
        f:storage:
          f:nodes:
      f:status:
        f:ceph:
          f:capacity:
            f:bytesAvailable:
            f:bytesUsed:
            f:lastUpdated:
          f:lastChecked:
        f:conditions:
        f:message:
        f:phase:
        f:state:
    Manager:         rook
    Operation:       Update
    Time:            2023-04-19T08:05:33Z
  Resource Version:  775736148
  Self Link:         /apis/ceph.rook.io/v1/namespaces/hdd-ceph/cephclusters/hdd-ceph
  UID:               8b35adbf-22ad-4832-9e7b-xxxxxxxxxxxx
Spec:
  Ceph Version:
    Allow Unsupported:  false
    Image:              quay.io/ceph/ceph:v17.2.6-20230410
  Cleanup Policy:
    Allow Uninstall With Volumes:  false
    Confirmation:                  
    Sanitize Disks:
      Data Source:                                    zero
      Iteration:                                      1
      Method:                                         quick
  Continue Upgrade After Checks Even If Not Healthy:  false
  Crash Collector:
    Disable:  true
  Dashboard:
    Enabled:           true
    Ssl:               false
  Data Dir Host Path:  /var/lib/rook2
  Disruption Management:
    Machine Disruption Budget Namespace:  openshift-machine-api
    Manage Machine Disruption Budgets:    false
    Manage Pod Budgets:                   false
    Osd Maintenance Timeout:              30
    Pg Health Check Timeout:              0
  External:
    Enable:  false
  Health Check:
    Daemon Health:
      Mon:
        Disabled:  false
        Interval:  45s
      Osd:
        Disabled:  false
        Interval:  60s
      Status:
        Disabled:  false
        Interval:  60s
    Liveness Probe:
      Mgr:
        Disabled:  false
      Mon:
        Disabled:  false
      Osd:
        Disabled:  false
  Mgr:
    Modules:
      Enabled:  true
      Name:     pg_autoscaler
      Enabled:  true
      Name:     prometheus
  Mon:
    Allow Multiple Per Node:  false
    Count:                    3
  Monitoring:
    Enabled:                               true
  Remove OS Ds If Out And Safe To Remove:  false
  Resources:
    Osd:
      Limits:
        Memory:  32Gi
      Requests:
        Memory:  8Gi
  Security:
    Kms:
  Skip Upgrade Checks:  false
  Storage:
    Nodes:
      Device Filter:            ^sd[b-c]
      Name:                     k8s-123-106
      Device Filter:            ^sd[b-d]
      Name:                     k8s-123-92
      Device Filter:            ^sd[b-d]
      Name:                     k8s-123-93
      Device Filter:            sdb
      Name:                     k8s-123-105
      Device Filter:            sda
      Name:                     k8s-123-101
    Storage Class Device Sets:  <nil>
    Use All Devices:            false
    Use All Nodes:              false
Status:
  Ceph:
    Capacity:
      Bytes Available:  30751013765120
      Bytes Total:      36000952745984
      Bytes Used:       5249938980864
      Last Updated:     2023-04-21T01:37:08Z
    Fsid:               a5b452cc-404f-4ab3-bb3e-xxxxxxxxxx
    Health:             HEALTH_OK
    Last Changed:       2023-04-19T07:54:21Z
    Last Checked:       2023-04-21T01:37:08Z
    Previous Health:    HEALTH_WARN
    Versions:
      Mds:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable):  2
      Mgr:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable):  1
      Mon:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable):  3
      Osd:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable):  10
      Overall:
        ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable):  16
  Conditions:
    Last Heartbeat Time:   2023-04-19T08:14:23Z
    Last Transition Time:  2023-04-19T08:14:23Z
    Message:               failed to create cluster: failed to start ceph monitors: failed to start mon pods: failed to check mon quorum d: failed to wait for mon quorum: context canceled
    Reason:                ClusterProgressing
    Status:                False
    Type:                  Progressing
    Last Heartbeat Time:   2023-04-21T01:37:09Z
    Last Transition Time:  2022-05-06T09:54:06Z
    Message:               Cluster created successfully
    Reason:                ClusterCreated
    Status:                True
    Type:                  Ready
  Message:                 Cluster created successfully
  Observed Generation:     5
  Phase:                   Ready
  State:                   Created
  Storage:
    Device Classes:
      Name:  hdd
  Version:
    Image:    quay.io/ceph/ceph:v17.2.6-20230410
    Version:  17.2.6-0
Events:       <none>
```

## curl command
```bash
root@netbox-77bd4fbfb6-dhq8d:/# curl rook-ceph-mgr.hdd-ceph:9283/metrics
curl: (7) Failed to connect to rook-ceph-mgr.hdd-ceph port 9283: Connection refused
```

**Comment by toabi** [comment]
Just ugpraded to 1.11.4 (from 1.9 -> 1.10 -> …) and then I noticed this issue.

I run kube-prometheus-stack next to it which so far always worked. I enabled `spec.monitoring.enabled` and now get a `"system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"`

In the code I actually don't see that it ever has access to those resources, so is that the bug? https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/role.yaml#L6-L63

**Comment by m1iktea** [comment]
> Just ugpraded to 1.11.4 (from 1.9 -> 1.10 -> …) and then I noticed this issue.
> 
> I run kube-prometheus-stack next to it which so far always worked. I enabled `spec.monitoring.enabled` and now get a `"system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"`
> 
> In the code I actually don't see that it ever has access to those resources, so is that the bug? https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/role.yaml#L6-L63

try apply
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: rook-ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.ceph.rook.io/aggregate-to-prometheus: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-rules
  labels:
    rbac.ceph.rook.io/aggregate-to-prometheus: "true"
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: rook-ceph
```

**Comment by benlsheets** [comment]
@m1iktea I think your CephCluster is failing reconciliation like mine was but for different reasons:
> ```shell
>   Conditions:
>     Last Heartbeat Time:   2023-04-19T08:14:23Z
>     Last Transition Time:  2023-04-19T08:14:23Z
>     Message:               failed to create cluster: failed to start ceph monitors: failed to start mon pods: failed to check mon quorum d: failed to wait for mon quorum: context canceled
>     Reason:                ClusterProgressing
>     Status:                False
>     Type:                  Progressing
> ```

It looks like you should check the status of your Ceph Mon pods.

**Comment by benlsheets** [comment]
I'm closing this issue out. Not being able to install the Prometheus mgr module via spec.mgr.modules is intentional behavior since it's now being governed by spec.monitoring.enabled.

It feels like maybe there's subtleties of the behavior we could discuss but this specific issue isn't valid.

**Comment by jrcichra** [comment]
I'm also running Rook without the Prometheus Operator and do not have Prometheus Operator CRDs in my cluster, which causes the reconcile to fail when monitoring is `true`. The non-operator prometheus builds scrape targets based on the well-known prometheus annotations.

I agree with all of the above, but I think it's worth having a solution which does not require Prometheus Operator CRDs in the cluster if they're not being used.

**Comment by travisn** [comment]
Reopening so we can consider implementing the fix mentioned [here](https://github.com/rook/rook/issues/12097#issuecomment-1510672729) so we can allow the prometheus module to be enabled even when `monitoring.enabled: false`

**Comment by jrcichra** [comment]
> Reopening so we can consider implementing the fix mentioned [here](https://github.com/rook/rook/issues/12097#issuecomment-1510672729) so we can allow the prometheus module to be enabled even when `monitoring.enabled: false`

That fix would work. 

I tried enabling prometheus on v1.11.4 with monitoring disabled (for fun 😄 ) and got this message:
```
op-mgr: failed modules: "mgr module(s) from the spec". cannot configure mgr module "prometheus" that is configured with other cluster settings
```

It looks like we'd just need to tweak the check done here? https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/mgr/mgr.go#L439

Do we only want to allow enabling the `prometheus` module when `monitoring.enabled` is `false`? At first thought that sounds like a good constraint.

**Comment by benlsheets** [comment]
How do the Exporters fit in to this discussion? What is their intended function?

If they don't get installed because we're using spec.monitoring.enabled=false to sidestep the servicemonitor CRD issue then will we be missing out on metrics not available via the MGR?

**Comment by travisn** [comment]
It seems we really need two settings in the cluster CR. This proposal would allow the metrics to continue being enabled by default along with the ceph exporter when it is ready to be enabled:
```yaml
monitoring:
  # Enables the full feature with service monitor, alerts, etc. 
  # Default is false. 
  enabled: false 
  # If false, both the prometheus module and the ceph exporter daemon are enabled. 
  # If true, both the prometheus module and ceph exporter are disabled. 
  # Default is false. 
  metricsDisabled: false 
```

Trying to manage the prometheus module separately the `mgr.modules` wasn't intuitive, especially once we introduce the question of what happens with the exporter.

**Comment by benlsheets** [comment]
> It seems we really need two settings in the cluster CR. This proposal would allow the metrics to continue being enabled by default along with the ceph exporter when it is ready to be enabled. The behavior of the first setting remains unchanged for backward compatibility.
> 
> ```yaml
> monitoring:
>   # Enables the full feature with service monitor, alerts, etc. 
>   # Default is false. 
>   enabled: false 
>   # If false, both the prometheus module and the ceph exporter daemon are enabled. 
>   # If true, both the prometheus module and ceph exporter are disabled. 
>   # Default is false. 
>   metricsDisabled: false 
> ```
> 
> Trying to manage the prometheus module separately the `mgr.modules` wasn't intuitive, especially once we introduce the question of what happens with the exporter.

This feels like a workable solution to me. And it makes a certain amount of sense to separate the rook-ceph metrics from the monitoring loadout the operator will deploy.

**Comment by jrcichra** [comment]
I agree. Keeping the prometheus module ownership fully under monitoring makes the most sense for UX.

**Comment by only21tender** [comment]
rook ceph version 1.9
k8s version 1.20
I have the same probelm like @benlsheets , after I created cluster.yaml and I'm waiting for osd started，I found the pod "rook-ceph-detect-version-" was cycle restarted，and when I get ceph cluster wich -w ,I found the follow msg
```
rook-ceph   /var/lib/rook     3          19m   Progressing   failed to create cluster: failed to start ceph mgr: failed to enable mgr services: failed to enable service monitor: service monitor could not be enabled: failed to create servicemonitor. the server could not find the requested resource (post servicemonitors.monitoring.coreos.com)
```
I'm trying to edit file cluster.yaml with config prometheus open，and replace的cluster.yaml，but it is not working，I'm trying again with the methord provided by @benlsheets , to create tow files，then the osd server pod can start .

**Comment by travisn** [comment]
That error sounds like the prometheus CRDs have not been created. Did you install the [prometheus bundle](https://rook.io/docs/rook/latest-release/Storage-Configuration/Monitoring/ceph-monitoring/#prometheus-operator)?

And are you in the process of upgrading? Rook v1.9 and K8s 1.20 are very old.
