### ISSUE TITLE
support to disable "dynamic resharding" and  specified "num_shards" by user

### ISSUE THREAD

**Issue by zhucan** [rook/rook#12100]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
user can assgin 'num_shards', no need to update 'num_shards' dynamic
**What is use case behind this feature:**
because of 'Write I/Os to the target bucket are blocked and read I/Os are not during resharding process.' [](https://docs.ceph.com/en/latest/radosgw/dynamicresharding/), we wanto to assign 'num_shards' when creating bucket, and disable 'dynamic resharding' when deploying ceph cluster
**Environment**:

**Comment by zhucan** [comment]
set 'rgw_dynamic_resharding'  to ceph conf disable the 'dynamic resharding', set 'rgw_override_bucket_index_max_shards' to assign 'num_shards'?

**Comment by travisn** [comment]
@BlaineEXE @thotz Would it make sense to support the [Ceph sharding settings](https://docs.ceph.com/en/latest/radosgw/dynamicresharding/) as part of the `additionalConfig` for the OBC? And would that translate to COSI?

**Comment by travisn** [comment]
> Ceph sharding settings

Oh right, makes sense at the rgw level, so we could put them in the object store CRD.

I was looking more at the resharding config commands later in the doc, but those wouldn't even be exposed in settings. Those commands would be better from the krew plugin.
