### ISSUE TITLE
dashboard password not working

### ISSUE THREAD

**Issue by celevra** [rook/rook#12113]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
could not login with the password from 
```
kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath="{['data']['password']}" | base64 --decode && echo
```

**Expected behavior:**
password working

**How to reproduce it (minimal and precise):**
i think it has todo with the password, so setting the password should be enough
```
~ $ kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath="{['data']['password']}" | base64 --decode && echo
hztOEA'#K:l~5J_S&&Y8
```
<img width="538" alt="image" src="https://user-images.githubusercontent.com/232437/233112629-51b4bf72-d899-4ab4-a4c8-217f9d34662a.png">

workaround:
```
kubectl create -f rook/deploy/examples/toolbox.yaml
kubectl -n rook-ceph exec -it deploy/rook-ceph-tools -- bash
echo 'yourSecurePassword!' > /tmp/test
ceph dashboard ac-user-create admin -i /tmp/test administrator
```

**Comment by parth-gr** [comment]
@celevra what is the ceph or rook version you are using?

What is the difference between the rook-ceph-dashboard-password secret password and a manually created password?

**Comment by parth-gr** [comment]
And can you try deleting the secret `rook-ceph-dashboard-password ` and restart the rook operator, hopefully, rook operator will re-create it and try it again.

Till then I will try to reproduce the above issue.

**Comment by travisn** [comment]
@celevra We cannot reproduce this issue with ceph v17.2.6. Does this repro consistently for you?

**Comment by zxl716** [comment]
I also encountered the problem of being unable to log in after entering the username and password on the dashboard. The version information is as follows:

[rook@rook-ceph-operator-8596db77db-7mxrc /]$ rook version
rook: v1.11.4
go: go1.19.8
[rook@rook-ceph-operator-8596db77db-7mxrc /]$ ceph -v
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
[rook@rook-ceph-operator-8596db77db-7mxrc /]$ exit
exit
[root@master ~]# kubectl get nodes
NAME              STATUS   ROLES    AGE   VERSION
192.168.123.191   Ready    master   40h   v1.22.2
192.168.123.192   Ready    node     40h   v1.22.2
192.168.123.193   Ready    node     40h   v1.22.2
[root@master ~]# uname -r
5.4.241-1.el7.elrepo.x86_64
[root@master ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
![pwd](https://user-images.githubusercontent.com/117974675/235061597-6120e2a6-db82-4ee5-8a71-5f7360cd8bd3.png)

**Comment by zxl716** [comment]
bash-4.4$ ceph dashboard ac-user-show admin
Error ENOENT: User 'admin' does not exist
bash-4.4$

**Comment by parth-gr** [comment]
Right, I did try,
And was able to reproduce.

Looking into it.

**Comment by parth-gr** [comment]
2023-04-28 10:27:12.374392 E | op-mgr: failed modules: "dashboard". failed to initialize dashboard: failed to set login credentials for the ceph dashboard: failed to set login creds on mgr: failed to complete command for set dashboard creds: exec timeout waiting for the command ceph to return

**Comment by parth-gr** [comment]
@travisn And I also think soo we should improve the dashboard code,
Here we do not check if the `dashboard user` is created or not

And go and just create it,

So I think so there might be this check, but I doubt too why the ceph command not complain for it at the same time.

https://github.com/rook/rook/blob/844712a989224dc5ddbe5c79c0a322fcb93572c0/pkg/operator/ceph/cluster/mgr/dashboard.go#L212

**Comment by MKhazamipour** [comment]
you can set the dashboard to false in CephCluster, then re-enable it. user will be created
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
  dashboard:
    enabled: false
```
