### ISSUE TITLE
The osd pod keeps restarting, and the node resource usage is high

### ISSUE THREAD

**Issue by clcc2019** [rook/rook#12129]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
osd pod keeps restarting

**Expected behavior:**
osd is running normally

**How to reproduce it (minimal and precise):**

Run a period of events normally and actively restart the pod，

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:
```yaml
rook-ceph-operator-59b754b44c-mrd5f                  1/1     Running            0          4d2h
rook-ceph-osd-0-b55f4bd77-k4zxf                      1/1     Running            2          111m
rook-ceph-osd-2-7fb5b79466-xx6cd                     0/1     CrashLoopBackOff   8          15m
rook-ceph-osd-3-569db649b5-4vwzt                     1/1     Running            0          97m

```
```yaml

** Compaction Stats [L] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uptime(secs): 0.0 total, 0.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [L] **

** Compaction Stats [P] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0   48.39 MB   0.5      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
  L1      1/0   67.78 MB   0.4      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
  L2     19/0    1.20 GB   0.5      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
 Sum     22/0    1.31 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0

** Compaction Stats [P] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uptime(secs): 0.0 total, 0.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [P] **

debug 2023-04-22T12:40:51.835+0000 7fd614b66080  0 _get_class not permitted to load lua
debug 2023-04-22T12:40:51.835+0000 7fd614b66080  0 _get_class not permitted to load kvs
debug 2023-04-22T12:40:51.855+0000 7fd614b66080  0 <cls> /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.7/rpm/el8/BUILD/ceph-16.2.7/src/cls/cephfs/cls_cephfs.cc:201: loading cephfs
debug 2023-04-22T12:40:51.859+0000 7fd614b66080  0 _get_class not permitted to load sdk
debug 2023-04-22T12:40:51.867+0000 7fd614b66080  0 <cls> /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.7/rpm/el8/BUILD/ceph-16.2.7/src/cls/hello/cls_hello.cc:316: loading cls_hello
debug 2023-04-22T12:40:51.871+0000 7fd614b66080  0 osd.2 3478 crush map has features 432629239337189376, adjusting msgr requires for clients
debug 2023-04-22T12:40:51.871+0000 7fd614b66080  0 osd.2 3478 crush map has features 432629239337189376 was 8705, adjusting msgr requires for mons
debug 2023-04-22T12:40:51.871+0000 7fd614b66080  0 osd.2 3478 crush map has features 3314933000854323200, adjusting msgr requires for osds
debug 2023-04-22T12:40:51.871+0000 7fd614b66080  1 osd.2 3478 check_osdmap_features require_osd_release unknown -> pacific
debug 2023-04-22T12:40:53.187+0000 7fd60527e700  4 rocksdb: [compaction/compaction_job.cc:1349] [default] [JOB 3] Generated table #958931: 2048209 keys, 68737287 bytes
debug 2023-04-22T12:40:53.187+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253193814, "cf_name": "default", "job": 3, "event": "table_file_creation", "file_number": 958931, "file_size": 68737287, "table_properties": {"data_size": 63168289, "index_size": 447533, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 0, "index_value_is_delta_encoded": 0, "filter_size": 5120581, "raw_key_size": 36867947, "raw_average_key_size": 18, "raw_value_size": 32770171, "raw_average_value_size": 15, "num_data_blocks": 15517, "num_entries": 2048209, "num_deletions": 0, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "rocksdb.BuiltinBloomFilter", "column_family_name": "default", "column_family_id": 0, "comparator": "leveldb.BytewiseComparator", "merge_operator": ".T:int64_array.b:bitwise_xor", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "NoCompression", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; ", "creation_time": 1650288802, "oldest_key_time": 0, "file_creation_time": 1682167251}}
debug 2023-04-22T12:40:53.195+0000 7fd60527e700  4 rocksdb: [compaction/compaction_job.cc:1415] [default] [JOB 3] Compacted 4@0 + 1@1 files to L1 => 68737287 bytes
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.202631) [compaction/compaction_job.cc:760] [default] compacted to: files[0 1 0 0 0 0 0] max score 0.26, MB/sec: 47.0 rd, 47.0 wr, level 1, files in(4, 1) out(1) MB in(0.0, 65.6) out(65.6), read-write-amplify(34029.4) write-amplify(17014.2) OK, records in: 2048217, records dropped: 8 output_compression: NoCompression

debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.202680) EVENT_LOG_v1 {"time_micros": 1682167253202652, "job": 3, "event": "compaction_finished", "compaction_time_micros": 1461118, "compaction_time_cpu_micros": 825927, "output_level": 1, "num_output_files": 1, "total_output_size": 68737287, "num_input_records": 2048217, "num_output_records": 2048209, "num_subcompactions": 1, "output_compression": "NoCompression", "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "lsm_state": [0, 1, 0, 0, 0, 0, 0]}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253202860, "job": 3, "event": "table_file_deletion", "file_number": 958923}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253202902, "job": 3, "event": "table_file_deletion", "file_number": 958917}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253202975, "job": 3, "event": "table_file_deletion", "file_number": 958902}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253203013, "job": 3, "event": "table_file_deletion", "file_number": 958890}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253203065, "job": 3, "event": "table_file_deletion", "file_number": 958888}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203094) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203112) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203120) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203131) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203138) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203145) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203152) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203163) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203170) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:54.039+0000 7fd614b66080  0 osd.2 3478 load_pgs
```

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary
** Compaction Stats [L] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uptime(secs): 0.0 total, 0.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [L] **

** Compaction Stats [P] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0   48.39 MB   0.5      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
  L1      1/0   67.78 MB   0.4      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
  L2     19/0    1.20 GB   0.5      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
 Sum     22/0    1.31 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0

** Compaction Stats [P] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uptime(secs): 0.0 total, 0.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [P] **

debug 2023-04-22T12:40:51.835+0000 7fd614b66080  0 _get_class not permitted to load lua
debug 2023-04-22T12:40:51.835+0000 7fd614b66080  0 _get_class not permitted to load kvs
debug 2023-04-22T12:40:51.855+0000 7fd614b66080  0 <cls> /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.7/rpm/el8/BUILD/ceph-16.2.7/src/cls/cephfs/cls_cephfs.cc:201: loading cephfs
debug 2023-04-22T12:40:51.859+0000 7fd614b66080  0 _get_class not permitted to load sdk
debug 2023-04-22T12:40:51.867+0000 7fd614b66080  0 <cls> /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.2.7/rpm/el8/BUILD/ceph-16.2.7/src/cls/hello/cls_hello.cc:316: loading cls_hello
debug 2023-04-22T12:40:51.871+0000 7fd614b66080  0 osd.2 3478 crush map has features 432629239337189376, adjusting msgr requires for clients
debug 2023-04-22T12:40:51.871+0000 7fd614b66080  0 osd.2 3478 crush map has features 432629239337189376 was 8705, adjusting msgr requires for mons
debug 2023-04-22T12:40:51.871+0000 7fd614b66080  0 osd.2 3478 crush map has features 3314933000854323200, adjusting msgr requires for osds
debug 2023-04-22T12:40:51.871+0000 7fd614b66080  1 osd.2 3478 check_osdmap_features require_osd_release unknown -> pacific
debug 2023-04-22T12:40:53.187+0000 7fd60527e700  4 rocksdb: [compaction/compaction_job.cc:1349] [default] [JOB 3] Generated table #958931: 2048209 keys, 68737287 bytes
debug 2023-04-22T12:40:53.187+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253193814, "cf_name": "default", "job": 3, "event": "table_file_creation", "file_number": 958931, "file_size": 68737287, "table_properties": {"data_size": 63168289, "index_size": 447533, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 0, "index_value_is_delta_encoded": 0, "filter_size": 5120581, "raw_key_size": 36867947, "raw_average_key_size": 18, "raw_value_size": 32770171, "raw_average_value_size": 15, "num_data_blocks": 15517, "num_entries": 2048209, "num_deletions": 0, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "rocksdb.BuiltinBloomFilter", "column_family_name": "default", "column_family_id": 0, "comparator": "leveldb.BytewiseComparator", "merge_operator": ".T:int64_array.b:bitwise_xor", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "NoCompression", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; ", "creation_time": 1650288802, "oldest_key_time": 0, "file_creation_time": 1682167251}}
debug 2023-04-22T12:40:53.195+0000 7fd60527e700  4 rocksdb: [compaction/compaction_job.cc:1415] [default] [JOB 3] Compacted 4@0 + 1@1 files to L1 => 68737287 bytes
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.202631) [compaction/compaction_job.cc:760] [default] compacted to: files[0 1 0 0 0 0 0] max score 0.26, MB/sec: 47.0 rd, 47.0 wr, level 1, files in(4, 1) out(1) MB in(0.0, 65.6) out(65.6), read-write-amplify(34029.4) write-amplify(17014.2) OK, records in: 2048217, records dropped: 8 output_compression: NoCompression

debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.202680) EVENT_LOG_v1 {"time_micros": 1682167253202652, "job": 3, "event": "compaction_finished", "compaction_time_micros": 1461118, "compaction_time_cpu_micros": 825927, "output_level": 1, "num_output_files": 1, "total_output_size": 68737287, "num_input_records": 2048217, "num_output_records": 2048209, "num_subcompactions": 1, "output_compression": "NoCompression", "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "lsm_state": [0, 1, 0, 0, 0, 0, 0]}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253202860, "job": 3, "event": "table_file_deletion", "file_number": 958923}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253202902, "job": 3, "event": "table_file_deletion", "file_number": 958917}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253202975, "job": 3, "event": "table_file_deletion", "file_number": 958902}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253203013, "job": 3, "event": "table_file_deletion", "file_number": 958890}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1682167253203065, "job": 3, "event": "table_file_deletion", "file_number": 958888}
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203094) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203112) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203120) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203131) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203138) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203145) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203152) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203163) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:53.199+0000 7fd60527e700  4 rocksdb: (Original Log Time 2023/04/22-12:40:53.203170) [db_impl/db_impl_compaction_flush.cc:2611] Compaction nothing to do
debug 2023-04-22T12:40:54.039+0000 7fd614b66080  0 osd.2 3478 load_pgs
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian
* Kernel (e.g. `uname -a`): 4.19.235-1
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`): v1.9.0
* Kubernetes version (use `kubectl version`): 1.20.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by clcc2019** [comment]
```yaml
Containers:
  osd:
    Container ID:  docker://4eec218888e5963d3c2e154323b99291fe81dae177ede39479043a81ddba5a65
    Image:         docker-prod-registry.cn-hangzhou.cr.aliyuncs.com/global/ceph:v16.2.7
    Image ID:      docker-pullable://docker-prod-registry.cn-hangzhou.cr.aliyuncs.com/global/ceph@sha256:0d927ccbd8892180ee09894c2b2c26d07c938bf96a56eaee9b80fc9f26083ddb
    Port:          <none>
    Host Port:     <none>
    Command:
      ceph-osd
    Args:
      --foreground
      --id
      2
      --fsid
      fb9dcb2b-dc46-4db0-8105-2e4cbc95124d
      --setuser
      ceph
      --setgroup
      ceph
      --crush-location=root=default host=uat-k8s-node-ceph-0001
      --log-to-stderr=true
      --err-to-stderr=true
      --mon-cluster-log-to-stderr=true
      --log-stderr-prefix=debug 
      --default-log-to-file=false
      --default-mon-cluster-log-to-file=false
      --ms-learn-addr-from-peer=false
      --osd-memory-target=5G
    State:          Running
      Started:      Sat, 22 Apr 2023 21:31:32 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Sat, 22 Apr 2023 21:30:07 +0800
      Finished:     Sat, 22 Apr 2023 21:31:16 +0800
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     2
      memory:  5Gi
    Requests:
      cpu:     10m
      memory:  10Mi

```

**Comment by clcc2019** [comment]
What task is this performing, causing the memory usage to be too high, I solved it by expanding the memory

**Comment by travisn** [comment]
@rzarzynski When would it be expected that OSDs take a lot of memory at startup? Requiring more than ~5GB memory for the OSD sounds unexpected, but perhaps I'm missing some scenario.

**Comment by rzarzynski** [comment]
@travisn: huge memory pressure around `load_pgs()` smells like an instance of the `PGLog::dups` issue – see https://tracker.ceph.com/issues/53729.

**Comment by rzarzynski** [comment]
@travisn: I don't think so. I can find "pacific: osd, tools, kv: non-aggressive, on-line trimming of accumulated dups" in v16.2.11 but not in v16.2.10.
