### ISSUE TITLE
Create objectuser failed without any error messages to user

### ISSUE THREAD

**Issue by zhucan** [rook/rook#12148]
https://github.com/rook/rook/blob/844712a989224dc5ddbe5c79c0a322fcb93572c0/pkg/operator/ceph/object/user/controller.go#L209

**Comment by zhucan** [comment]
if the rgw pod is not running, create object user failed, but no any error message can be founded from the operator log and the cr.
```
[root@rook-node01 deeproute]# kubectl get objectuser -n rook-ceph my-user2 -o yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ceph.rook.io/v1","kind":"CephObjectStoreUser","metadata":{"annotations":{},"name":"my-user2","namespace":"rook-ceph"},"spec":{"displayName":"my display name","store":"os-rlpveh3aweab074o"}}
  creationTimestamp: "2023-04-28T10:15:22Z"
  finalizers:
  - cephobjectstoreuser.ceph.rook.io
  generation: 1
  name: my-user2
  namespace: rook-ceph
  resourceVersion: "597378"
  uid: 3f814d16-4da0-4e1c-b704-a550711a8b76
spec:
  displayName: my display name
  store: os-rlpveh3aweab074o
status:
  phase: ReconcileFailed
```

operator logs:
2023-04-28 11:15:41.772237 I | ceph-spec: parsing mon endpoints: a=10.x.x.85:6789,e=10.x.x.84:6789,b=10.x.x.83:6789
2023-04-28 11:15:41.772364 I | ceph-object-store-user-controller: CephObjectStore "os-rlpveh3aweab074o" found
2023-04-28 11:15:51.795512 I | ceph-spec: parsing mon endpoints: a=10.x.x.85:6789,e=10.x.x.84:6789,b=10.x.x.83:6789

**Comment by travisn** [comment]
The status on the CR is:
```
  status:
    phase: ReconcileFailed
```
How else do you prefer the status be raised to the user?

**Comment by zhucan** [comment]
But user don’t know why created failed

**Comment by travisn** [comment]
Agreed, we should have a message about the failure on the CR status.

**Comment by BlaineEXE** [comment]
What does `kubectl describe objectuser -n rook-ceph my-user2` show? There may be events captured that help as well, though the output can be made easier to see on the status I agree.

**Comment by zhucan** [comment]
@BlaineEXE
