### ISSUE TITLE
Multiple places to specify the rook version should be simplified.

### ISSUE THREAD

**Issue by dab-q** [rook/rook#1215]
The rook version has to be specified in two places.  In rook-operator.yaml there is the `image:` field, and then again in rook-cluster.yaml there is a `versionTag` field.  If these don't match, then the osd, mon, etc. pods won't be started with the same version of rook as was used to start the rook operator.  It would be simpler if the operator could pick up it's own version of rook and use that for starting up the other rook pods.

**Comment by travisn** [comment]
agreed, this is a common issue that errors happen in the cluster when they are different. The intent was originally that you might want to support clusters of different versions. The only realistic way to support versioning is for the cluster to be running the same version as the operator. 

For upgrades, the operator would be upgraded first. Then it could notice the cluster pods are an older version and upgrade.

**Comment by jbw976** [comment]
The current upgrade design allows for each Rook cluster to be independently upgraded (the user starts the upgrade when they want to) by editing the `versionTag` field in each cluster CRD.  We could instead make it more automatic by the operator trigging cluster upgrades when its own version has been updated, but do note that the current design for upgrade was going to be triggered from each cluster's `versionTag` getting updated.

**Comment by travisn** [comment]
right, the upgrade design would need to be updated. I'm thinking that we would want an `upgradePolicy` property on the cluster.yaml. The default would be to upgrade immediately when the operator is upgraded.
