### ISSUE TITLE
Unable to set monitoring.rulesNamespace

### ISSUE THREAD

**Issue by SerialVelocity** [rook/rook#12163]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I can't set `monitoring.rulesNamespace` in the Cluster CRD. It says:
```
strict decoding error: unknown field "spec.monitoring.rulesNamespace"
```

**Expected behavior:**
I can set the `monitoring.rulesNamespace`.

Your documentation says this is a valid field but the generated CRD doesn't contain this field. Are the docs out of date?

**How to reproduce it (minimal and precise):**

Set this in the Cluster:
```
  monitoring:
    enabled: true
    rulesNamespace: custom-namespace
```

**Environment**:
* Rook version: Rook 1.10.11 (from the Helm chart. Not using Helm for the ceph cluster though)

**Comment by parth-gr** [comment]
I see `rulesNamespaceOverride` as a spec
Can you try with this

**Comment by SerialVelocity** [comment]
Ah, it looks like it was removed from the ceph cluster CRD in 1.9.0. I must've missed that breaking change.

I need to switch to the Helm chart if I want to automatically install the prometheus rules.

**Comment by SerialVelocity** [comment]
Actually, I will leave this open. This is a docs issue. You still have references to it in your codebase/docs.

**Comment by parth-gr** [comment]
Can you please link the docs, where you suspect it would be changed?

**Comment by natechoiniere** [comment]
This is still an issue. The documentation here describes using rulesNamespace & gives me the same error: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-ceph-cluster-within-kubernetes-using-rook#step-2-creating-a-ceph-cluster
