### ISSUE TITLE
Allow multus validation test to have (anti-)affinities, tolerations, and other selectors specified

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#12173]
Follow-up from #12069 

https://github.com/rook/rook/blob/5a1d1f21751e4b65e6a8ce2fe62853d410c853a0/pkg/daemon/multus/client-daemonset.yaml#L25

This should be pretty straightforward, but it would be nice to have an easier way of configuring these items that isn't specifying them on the command line, which could become cumbersome. Perhaps a yaml config file using the Viper framework? https://github.com/spf13/viper

**Comment by parth-gr** [comment]
Can you please elaborate on it what needs to be done?
Just need to add the tolerations in yaml or need to add in the further codebase the code this yamls calls

Who calls this client-daemonset.yaml? Maybe can you point out where I can understand the flow

**Comment by subhamkrai** [comment]
@BlaineEXE I think this is already covered with your latest pr https://github.com/rook/rook/pull/12968 ?

**Comment by BlaineEXE** [comment]
Right! Thank you
