### ISSUE TITLE
Create a sample job manifest to run multus validation test

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#12172]
Create a sample job manifest that could run the multus validation test routine, similar to our osd-purge.yaml.

It seems a good way to make sure logs are preserved if the pod running the tool fails. This might be a good time to note that the tool is not idempotent; it will fail if a pre-existing test seems like it might be in progress. This is intentional, and subsequent runs will error with a note of how to run test cleanup if desired.

_Originally posted by @travisn in https://github.com/rook/rook/pull/12069#discussion_r1181950271_

**Comment by subhamkrai** [comment]
do we plan in the future to integrate this to krew? if yes? why do we need a job similar to osd-purge because in krew we replace the osd-purge job with the krew command.

**Comment by parth-gr** [comment]
@BlaineEXE I do the rook side changes

**Comment by travisn** [comment]
> do we plan in the future to integrate this to krew? if yes? why do we need a job similar to osd-purge because in krew we replace the osd-purge job with the krew command.

My thought is that both the job and the krew plugin are valid approaches. For example, I would think upstream admins would prefer the krew plugin, but downstream a job template may be the first choice until the krew plugin gets wider adoption.
