### ISSUE TITLE
Improve integration test coverage or block storage. 

### ISSUE THREAD

**Issue by dangula** [rook/rook#1217]
We need to improve test coverage for block storage (specially around mount/unmount secnarios). Here are some tests areas/cases that could use better coverage.

1. Intgration tests for fencing - mount with ReadwriteOnce, ReadOnly and ReadWriteMany
2. Integration tests around multiple mount and unmount. eg - mount bock storage, write data, unmount, then mount again. Make sure old data is present.

**Comment by jbw976** [comment]
we can also consider testing a StatefulSet that is using a Rook PVC.  Create StatefulSet, scale it up, failover a pod, scale it down, delete the StatefulSet.  The pods should all get to the running state and have functional data, no data loss during failover, and all artifacts should be completely cleaned up (PVs, PVCs, VolumeAttachment CRDs, etc.) by the Rook volume plugin by the end (no resource leaks).
