### ISSUE TITLE
Consolidate and parallelize integration tests to reduce run time

### ISSUE THREAD

**Issue by dangula** [rook/rook#1218]
Integration tests usually create a Rook cluster, perfrom some tests and then uninstall rook cluster. 
Intalling and uninstalling Rook cluster for each test suite is taking up a major chunk of time. We need to consolidate so test fun faster and reduce CI pipeline time. 
 We can consolidate test by not installing and unistalling Rook per suite, or by combining multiple tests into single suite.

**Comment by travisn** [comment]
This was accomplished by #4096
