### ISSUE TITLE
Remove import script step for external cluster

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12207]
**Is this a bug report or feature request?**
* Feature Request
Remove import script step for external cluster

We should be finding alternate method for that step,
1) Maybe by passing details by creating a secret,
2) Or directly injecting details to to an endpoint
etc

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
Was there feedback to get rid of the import script? While simplifying is always good, I'm not sure we can get it simpler while also keeping the implementation simple.

> We should be finding alternate method for that step,
> 1. Maybe by passing details by creating a secret

If a secret is created, that means the script would still need to create the secret, right? So in that case it seems like we anyway have to run an import script.

> 2. Or directly injecting details to to an endpoint

I don't see it practical to have an online service that helps with the cross-cluster communication. Setting up this other service would be more work than just having the import script.

**Comment by parth-gr** [comment]
After discussion we can include import script directly in the code or with cluster.yaml file to run it

**Comment by travisn** [comment]
> After discussion we can include import script directly in the code or with cluster-external.yaml file to run it

Shall we move this issue to the krew plugin repo?
