### ISSUE TITLE
Allow running Rook when RBAC is disabled

### ISSUE THREAD

**Issue by citywander** [rook/rook#1221]
In k8s 1.8.X, I want to disable RBAC and deploy rook-operator. It failed. I found in agent.go, RBAC must be enabled, maybe RBAC can be disabled.

**Comment by travisn** [comment]
@citywander it is expected that if rbac is not enabled, the rbac artifacts in rook will have no effect. Are you seeing an error in the agent when rbac is disabled?

**Comment by citywander** [comment]
Throw exception: failed to init RBAC for rook-agents. The commit: https://github.com/rook/rook/commit/544b208ac74f367f0585e5ef4f06c33e31260964#diff-530ab6493977bf91e16203c361e8ddd5.
I found when creating an agent, RBAC must be enabled.

**Comment by travisn** [comment]
@kokhang can you take a look? if it's blocking deployments where rbac is disabled we should consider a fix for 0.6.1

**Comment by kokhang** [comment]
ill look into it.

**Comment by kokhang** [comment]
@citywander what does your `--authorization-mode` look like in your environment?

**Comment by citywander** [comment]
we didn't config the option, so the default value is AlwaysAllow.
All API Options.
  - kube-apiserver
    - --bind-address={{$iface}}
    - --etcd-servers={{use "etcd_ep" .}}
    - --allow-privileged=true
    - --service-cluster-ip-range=10.3.0.0/16
    - --secure-port=443
    - --advertise-address={{$iface}}
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultStorageClass
    - --runtime-config=api/all=true
    - --logtostderr=true
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem
    # - --requestheader-allowed-names=aggregator
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --proxy-client-cert-file=/etc/kubernetes/ssl/aggregator.pem
    - --proxy-client-key-file=/etc/kubernetes/ssl/aggregator-key.pem
    - --enable-aggregator-routing=true
    - --max-mutating-requests-inflight=1000
    - --max-requests-inflight=2000

**Comment by kokhang** [comment]
@citywander i used minikube to start a cluster with authorization mode `AlwaysAllow` as follows
`minikube start --extra-config=apiserver.Authorization.Mode=AlwaysAllow`

I am not able to see an issue and the agents come up fine. What is the errors that you see from the Operator log?

**Comment by mossinfan** [comment]
@kokhang
after adjust the starting parameter of api-server as your suggest, the operator still can;t be deployed successfully

2017-11-14 03:52:14.862717 I | rook: starting Rook v0.6.0 with arguments '/usr/local/bin/rook operator'
2017-11-14 03:52:14.862802 I | rook: flag values: --help=false, --log-level=INFO, --mon-healthcheck-interval=20s, --mon-out-timeout=5m0s
2017-11-14 03:52:14.865553 I | rook: starting operator
2017-11-14 03:52:14.881723 I | opkit: creating cluster CRD
2017-11-14 03:52:14.888891 I | opkit: CRD cluster already exists
2017-11-14 03:52:14.888918 I | opkit: creating pool CRD
2017-11-14 03:52:14.896733 I | opkit: CRD pool already exists
2017-11-14 03:52:14.896757 I | opkit: creating objectstore CRD
2017-11-14 03:52:14.901069 I | opkit: CRD objectstore already exists
2017-11-14 03:52:14.901093 I | opkit: creating filesystem CRD
2017-11-14 03:52:14.907022 I | opkit: CRD filesystem already exists
2017-11-14 03:52:14.907088 I | opkit: creating volumeattachment CRD
2017-11-14 03:52:14.915368 I | opkit: CRD volumeattachment already exists
2017-11-14 03:52:17.441370 I | op-k8sutil: creating cluster role rook-agent
failed to run operator. Error starting agent daemonset: failed to init RBAC for rook-agents. failed to create/update cluster role rook-agent. clusterroles.rbac.authorization.k8s.io "rook-agent" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes/proxy"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["nodes/proxy"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["get"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["list"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["create"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["delete"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["update"]} PolicyRule{Resources:["clusters"], APIGroups:["rook.io"], Verbs:["get"]} PolicyRule{Resources:["clusters"], APIGroups:["rook.io"], Verbs:["list"]} PolicyRule{Resources:["clusters"], APIGroups:["rook.io"], Verbs:["watch"]} PolicyRule{Resources:["storageclasses"], APIGroups:["storage.k8s.io"], Verbs:["get"]}] user=&{system:serviceaccount:rook-system:default f10a3a3f-c8ee-11e7-967c-000c2991b998 [system:serviceaccounts system:serviceaccounts:rook-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]

**Comment by kokhang** [comment]
@mossinfan is the the same k8s cluster as @citywander?

**Comment by travisn** [comment]
@citywander @mossinfan if you have the option set for `--authorization-mode=AlwaysAllow`, you should not see any errors about `forbidden: attempt to grant extra privileges`. Can you check your settings again? It appears you do have RBAC enabled and it is denying access to these components which are required to run Rook.

**Comment by travisn** [comment]
please reopen if you can confirm the repro with rbac disabled

**Comment by jbguerraz** [comment]
We face the same issue here, we don't have RBAC enabled and so we can't run Rook anymore.
This on Kubernetes 1.8.3 / CoreOS (alpha).

```root      5651  1.8  0.3 1386492 372876 ?      Ssl  Nov16 206:21 /hyperkube apiserver --bind-address=*.*.*.* --etcd-servers=http://*.*.*.*:****,http://*.*.*.*:****,http://*.*.*.*:**** --allow-privileged=true --service-cluster-ip-range=10.4.0.0/14 --secure-port=443 --advertise-address=*.*.*.* --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem --client-ca-file=/etc/kubernetes/ssl/ca.pem --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem --runtime-config=extensions/v1beta1/networkpolicies=true,batch/v2alpha1=true --anonymous-auth=false --authorization-mode=AlwaysAllow```

```
2017-11-24 14:30:42.090924 I | rook: starting Rook v0.6.0-38.gdf22444 with arguments '/usr/local/bin/rook operator'
2017-11-24 14:30:42.091016 I | rook: flag values: --help=false, --log-level=INFO, --mon-healthcheck-interval=20s, --mon-out-timeout=5m0s
2017-11-24 14:30:42.091956 I | rook: starting operator
2017-11-24 14:30:44.838925 I | op-k8sutil: creating cluster role rook-agent
failed to run operator. Error starting agent daemonset: failed to init RBAC for rook-agents. failed to create/update cluster role rook-agent. clusterroles.rbac.authorization.k8s.io "rook-agent" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes/proxy"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["nodes/proxy"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["get"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["list"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["create"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["delete"]} PolicyRule{Resources:["volumeattachments"], APIGroups:["rook.io"], Verbs:["update"]} PolicyRule{Resources:["clusters"], APIGroups:["rook.io"], Verbs:["get"]} PolicyRule{Resources:["clusters"], APIGroups:["rook.io"], Verbs:["list"]} PolicyRule{Resources:["clusters"], APIGroups:["rook.io"], Verbs:["watch"]} PolicyRule{Resources:["storageclasses"], APIGroups:["storage.k8s.io"], Verbs:["get"]}] user=&amp;{system:serviceaccount:rook-system:default 8c208898-d123-11e7-ae4a-b083fee1fbb5 [system:serviceaccounts system:serviceaccounts:rook-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
```

**Comment by travisn** [comment]
the api server is acting as if RBAC is enabled. If the policy is set to `AlwaysAllow`, my understanding is that you shouldn't see this error about access being forbidden. All requests should be granted. 
```
clusterroles.rbac.authorization.k8s.io "rook-agent" is forbidden: attempt to grant extra privileges:
```

When you created the rook-operator.yaml, did you remove the `ClusterRole` definition? I'm assuming you would get a similar error with that.

I'm not seeing a command that gets the actual RBAC state on the API server. I see that you passed the expected flag to the api server, i'm just wondering if it somehow didn't pick up that flag. Could you check with sig-auth on this configuration?

**Comment by jbguerraz** [comment]
I discussed that with Jordan Liggitt from sig-auth (see https://gist.github.com/jbguerraz/cfdf8c13705d76e4e4ed92389f9cd884) and it appears as it Rook won't work without RBAC enabled. To get it working it would require non-rbac users to prepare their clusters by either granting the, at least, same RBAC permissions of the rook RBAC roles to the used user or by using the insecure port to create those roles prior to the Rook install.

**Comment by travisn** [comment]
thanks @jbguerraz this discussion with sig-auth explains it. Now I see why we are seeing failures even when the mode is AlwaysAllow. When we are requesting the RBAC permissions, we should just log that it failed and make a best effort to continue.

**Comment by kokhang** [comment]
so should i reopen my fix?

**Comment by travisn** [comment]
@kokhang yes, looks like we need it. Were you able to repro the issue to start with? With the PR I just want to make sure we get all the RBAC permissions covered. For example, the operator creates RBAC roles for both the api service and the agent. Also, can we add an e2e test for rbac being disabled?

**Comment by kokhang** [comment]
i was not able to reproduce the exact same issue but i was able to test that with this patch, Rook will work when the authentication is AlwaysAllow. If you use RBAC and set the USE_RBAC to false, then rook will correctly fail.
To disable RBAC, you would have to modify kubelet and would require a new pipeline. So it would probably be more involved.

**Comment by travisn** [comment]
@jbguerraz maybe you could verify the fix if @kokhang could publish a build for you?

**Comment by jbguerraz** [comment]
Sure thing! :-)

**Comment by jbguerraz** [comment]
@kokhang could you publish a build ?

**Comment by kokhang** [comment]
Done. The image is `kokhang/rook:rbacfix`. Make sure you use this image in the rook-operator.yaml in the `image` and also in the rook-cluster.yaml in `versionTag` use `rbacfix`. Thank you @jbguerraz

**Comment by jbguerraz** [comment]
That build works well! GG @kokhang !
Is that possible to release a 0.6.2 as 0.6.1 is already out (https://github.com/rook/rook/issues/1221#issuecomment-343380744). That would be super cool (so we can save up some time from our current sprint)

**Comment by jbw976** [comment]
I would not be against backporting this fix to the 0.6 release branch (once #1231 is in master) since it is blocking deployments without RBAC.  I've added this ticket to the v0.6 project board: https://github.com/rook/rook/projects/7

**Comment by jbguerraz** [comment]
@jbw976 @DanKerns could we backport it to 0.6 ( #1298 )  ? thank you a lot!

**Comment by DanKerns** [comment]
@jbguerraz that's the plan.
