### ISSUE TITLE
Documentation quickstart page is broken

### ISSUE THREAD

**Issue by NedkoHristov** [rook/rook#12214]
Documentation in https://rook.io/docs/rook/v1.6/ceph-quickstart.html is broken. The dropdown shows versions up to `1.9` and `latest`, but versions up to 1.6 is working.

Tested on latest Firefox and Chrome on MacOs Ventura 13.3.1.

**Comment by travisn** [comment]
v1.6 is old documentation. We had a change in format. For the latest, see the v1.11 Quickstart:
https://rook.io/docs/rook/v1.11/Getting-Started/quickstart/

**Comment by travisn** [comment]
Note that you can still access the older versions, some of the navigation to get there is apparently just broken:
- https://rook.github.io/docs/rook/v1.7/quickstart.html
- https://rook.github.io/docs/rook/v1.8/quickstart.html

**Comment by NedkoHristov** [comment]
Thanks for answering so quickly, @travisn .

> v1.6 is old documentation. We had a change in format. For the latest, see the v1.11 Quickstart: https://rook.io/docs/rook/v1.11/Getting-Started/quickstart/

Yep, I know it's old, ChatGTP suggested it 😁 But when I tried to chose the latest version I've got 404. Can you reproduce the issue?

Plus as a side note - to improve a bit of the UX `latest` should be first choice.

**Comment by travisn** [comment]
If going to the documentation from rook.io, then `latest` is the first choice. Regarding what search engines find, we have tried to unindex previous versions of the docs, but there is not a plan to fix the links from older docs.
