### ISSUE TITLE
3osd in 3host fresh install, Degraded data redundancy

### ISSUE THREAD

**Issue by cld0815** [rook/rook#12229]
a fresh install (latest version)
3 osd in 3 host
helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph
helm install --namespace rook-ceph rook-ceph-cluster  rook-release/rook-ceph-cluster `
--set operatorNamespace=rook-ceph `
--set toolbox.enabled=true

**all osd is fine**
![1683952370773](https://github.com/rook/rook/assets/30192550/9ca0fb3f-0108-4b6b-92c7-4c9498ee6bfc)

**log like this:**
5/13/23 12:20:00 PM
[WRN]
overall HEALTH_WARN Degraded data redundancy: 13/1182 objects degraded (1.100%), 2 pgs degraded, 2 pgs undersized

5/13/23 12:10:00 PM
[WRN]
pg 7.17 is stuck undersized for 44m, current state active+undersized+degraded, last acting [1,0]

5/13/23 12:10:00 PM
[WRN]
pg 7.7 is stuck undersized for 44m, current state active+undersized+degraded, last acting [1,0]

5/13/23 12:10:00 PM
[WRN]
[WRN] PG_DEGRADED: Degraded data redundancy: 13/1182 objects degraded (1.100%), 2 pgs degraded, 2 pgs undersized

5/13/23 12:10:00 PM
[WRN]
Health detail: HEALTH_WARN Degraded data redundancy: 13/1182 objects degraded (1.100%), 2 pgs degraded, 2 pgs undersized

**Comment by cld0815** [comment]
[root@rook-ceph-tools-846b5c845b-s6rxx /]# ceph status
  cluster:
    id:     72d05080-c605-473c-9552-55692cabae38
    health: HEALTH_WARN
            Degraded data redundancy: 13/1182 objects degraded (1.100%), 2 pgs degraded, 2 pgs undersized

  services:
    mon: 3 daemons, quorum a,b,c (age 2h)
    mgr: a(active, since 89m), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 88m), 3 in (since 90m)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   12 pools, 223 pgs
    objects: 394 objects, 613 KiB
    usage:   154 MiB used, 8.0 TiB / 8.0 TiB avail
    pgs:     13/1182 objects degraded (1.100%)
             221 active+clean
             2   active+undersized+degraded

  io:
    client:   1.3 KiB/s rd, 170 B/s wr, 2 op/s rd, 0 op/s wr

**Comment by cld0815** [comment]
[root@rook-ceph-tools-846b5c845b-s6rxx /]# ceph health detail
HEALTH_WARN Degraded data redundancy: 13/1182 objects degraded (1.100%), 2 pgs degraded, 2 pgs undersized
[WRN] PG_DEGRADED: Degraded data redundancy: 13/1182 objects degraded (1.100%), 2 pgs degraded, 2 pgs undersized
    pg 7.7 is stuck undersized for 2h, current state active+undersized+degraded, last acting [1,0]
    pg 7.17 is stuck undersized for 2h, current state active+undersized+degraded, last acting [1,0]

**Comment by sp98** [comment]
is the failure domain set to host and replicated size 3 ?

**Comment by cld0815** [comment]
> is the failure domain set to host and replicated size 3 ?

yes

**Comment by travisn** [comment]
Which pool(s) do the [PGs](https://docs.ceph.com/en/latest/dev/placement-group/#omap-statistics) belong to? Perhaps there is an issue with a specific pool. 
```
ceph pg dump pools
```

**Comment by cld0815** [comment]
I reinstalled it with 4 OSD and it has no warning
