### ISSUE TITLE
Unable to remove image from partial copy

### ISSUE THREAD

**Issue by echel0n-TR** [rook/rook#12233]
I was trying to copy/clone a existing image to a new image but the task got killed midway through, I've tried to `rbd rm` the image but that seems to be stuck, any help would be greatly appreciated.

**Comment by travisn** [comment]
Any repro steps, error messages, logs? Is ceph health? (`ceph status` from the toolbox.) Details will help troubleshoot.

**Comment by echel0n-TR** [comment]
we are able to now remove the image using `rbd rm`, however its extremely slow process, anything that can be done to speed this up?

**Comment by Rakshith-R** [comment]
@echel0n-TR , This seems to be a ceph specific question rather than rook one.
You can find details to get in touch with ceph developers [here](https://ceph.io/en/community/connect/).
(ceph slack join is at the end of the site).
