### ISSUE TITLE
backward compatible : set permission of volume to worldwide (777) instead of 755

### ISSUE THREAD

**Issue by porwalameet** [rook/rook#12242]
With commit: https://github.com/ceph/ceph-csi/pull/2847/commits/b79209a197195eaaf0de2e2ec7d8e5181de75a84, the volume which was mounted with permission 777 is removed . In our deployment, we still have pods which run as non-root and want to write data to the cephfs volume.

Deployment:
Kubernetes 1.24.8
Version:
 rook/ceph:v1.11.5
 ceph/ceph:v17.2.6

We are planning to take step wise, and have pods owners change their YAML slowly, however is there a way I still configure volume with permission 777 without changing any kubernetes YAML

**Comment by porwalameet** [comment]
One such example is hashicorp vault which runs with "vault" user in kubernetes environemnt. Here, when vault initializes it want to create file in volume path, since permission is set to drwxr-xr-x, the initialization fails. 

We dont want to change vault config here yet or add initContainers to change permission. Since there are many application, we want this to be handled in rook-ceph deployment only.

**Comment by porwalameet** [comment]
Also, if we go with fsGroup approach so an non-root container can write to volume,  this only works for PVC which has ReadWriteOnce(RWO) accessMode. The containers fails to write to volume when accessMode is set to ReadWriteMany(RWX).

**Comment by porwalameet** [comment]
@Madhu-1, is there any config to revert to old way. As mentioned in earlier comment, non-root container cannot write to volumes with PVC RWX: https://github.com/kubernetes/examples/issues/260

**Comment by Madhu-1** [comment]
@porwalameet Currently, there is no existing configuration for this. Would you mind sharing the pod YAML you believe a regular user would be unable to write to the CephFS RWX PVC?

**Comment by porwalameet** [comment]
@Madhu-1 , i was using this config on k8s 1.24 
`kind: PersistentVolumeClaim
metadata:
  name: sample-cephfs-pvc
  namespace: fed-smf
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: fed-smf
  labels:
    app: bb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb
  template:
    metadata:
      labels:
        app: bb
    spec:
      serviceAccount: fed-smf-serviceaccount
      containers:
      - name: bb1
        image: cnartifactoryaz.affirmednetworks.com/thirdparty_docker/busybox:1.29.3
        imagePullPolicy: IfNotPresent
        command:
        - "sleep"
        - "5000"
        volumeMounts:
        - name: data
          mountPath: /user/accounting/lcdr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 4000
          runAsNonRoot: true
          runAsUser: 4000
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
      - name: bb2
        image: cnartifactoryaz.affirmednetworks.com/thirdparty_docker/busybox:1.29.3
        imagePullPolicy: IfNotPresent
        command:
        - "sleep"
        - "5000"
        volumeMounts:
        - name: data
          mountPath: /user/accounting/lcdr
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 4000
          runAsNonRoot: true
          runAsUser: 4000
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
      securityContext:
        fsGroup: 4000
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sample-cephfs-pvc
>> kc get sc
NAME          PROVISIONER                         RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
rook-cephbp   fed-rook-ceph.rbd.csi.ceph.com      Retain          Immediate           true                   73m
rook-cephfs   fed-rook-ceph.cephfs.csi.ceph.com   Retain          Immediate           true                   73m

`

Not sure, if this is seen, even setting fsGroup the stick bit for group wasnt set. Are there any config/commands to verify from rook-ceph side?

**Comment by Madhu-1** [comment]
@porwalameet can you set fsGroup at deployment.spec.spec level as mentioned here https://github.com/ceph/ceph-csi/issues/3342#issuecomment-1225854433

```
[🎩︎]mrajanna@fedora cephfs $]kubectl create -f pvc.yaml 
persistentvolumeclaim/cephfs-pvc created
[🎩︎]mrajanna@fedora cephfs $]kubectl get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cephfs-pvc   Bound    pvc-e5f9eedc-c16d-4a15-8bea-9e380409b46e   1Gi        RWX            rook-cephfs    4s
---
apiVersion: v1
kind: Pod
metadata:
  name: csicephfs-demo-pod
spec:
  securityContext:
          fsGroup: 4000
          runAsNonRoot: true
  containers:
    - name: web-server-1
      image: busybox
      command:
        - "sleep"
        - "5000"
      securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/html
    - name: web-server-2
      image: busybox
      command:
        - "sleep"
        - "5000"
      securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 4000
          runAsNonRoot: true
          runAsUser: 2000
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cephfs-pvc
        readOnly: false

[🎩︎]mrajanna@fedora cephfs $]kubectl get po
NAME                 READY   STATUS    RESTARTS   AGE
csicephfs-demo-pod   2/2     Running   0          17s
[🎩︎]mrajanna@fedora cephfs $]kubectl exec -it csicephfs-demo-pod -- sh
Defaulted container "web-server-1" out of: web-server-1, web-server-2
~ $ 
~ $ whoami
whoami: unknown uid 1000
~ $ ls -la /var/lib/html/
total 4
drwxrwsr-x    2 root     4000             0 May 22 12:04 .
drwxr-xr-x    3 root     root          4096 May 22 12:04 ..
~ $ df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  27.9G      7.0G     19.3G  27% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     1.9G         0      1.9G   0% /sys/fs/cgroup
/dev/vda1                27.9G      7.0G     19.3G  27% /dev/termination-log
/dev/vda1                27.9G      7.0G     19.3G  27% /etc/resolv.conf
/dev/vda1                27.9G      7.0G     19.3G  27% /etc/hostname
/dev/vda1                27.9G      7.0G     19.3G  27% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
10.99.195.117:6789:/volumes/csi/csi-vol-e60a4e2b-3b62-45ba-beeb-1b852d2550d1/6fb38177-87ad-4dc0-98b7-59bcc10c11dd
                          1.0G         0      1.0G   0% /var/lib/html
tmpfs                     3.8G     12.0K      3.8G   0% /var/run/secrets/kubernetes.io/serviceaccount
tmpfs                     1.9G         0      1.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                     1.9G         0      1.9G   0% /proc/scsi
tmpfs                     1.9G         0      1.9G   0% /sys/firmware
~ $ touch /var/lib/html/a
~ $ exit
[🎩︎]mrajanna@fedora cephfs $]kubectl exec -it csicephfs-demo-pod -c web-server-2 -- sh
~ $ 
~ $ whoami
whoami: unknown uid 2000
~ $ ls -a /var/lib/www/html
.   ..  a
~ $ ls -a /var/lib/www/
.     ..    html
~ $ ls -la /var/lib/www/
total 8
drwxr-xr-x    3 root     root          4096 May 22 12:04 .
drwxr-xr-x    3 root     root          4096 May 22 12:04 ..
drwxrwsr-x    2 root     4000             1 May 22 12:05 html
~ $ touch /var/lib/www/html/b

```

**Comment by porwalameet** [comment]
@Madhu-1 , thank for quick response. However one query, have you come across instance, where the "s" bit is not set for mounted volume.? just like in your above case, i see "drwxrwsr-x", there was one occurace, i saw permission was 755 even with fsGroup. Unfortunately i am not able to repro that now.  Just want to check, if that happens, any specific logs, command output to capture?

**Comment by Madhu-1** [comment]
> for quick response. However one query, have you come across instance, where the "s" bit is not set for mounted volume.? just like in your above case, i see "drwxrwsr-x", there was one occurace, i saw permission was 755 even with fsGroup. Unfortunately i am not able to repro that now. Just want to check, if that happens, any specific logs, command output to capture?

i dont recall anything for volumes, but there was a problem with sbit not getting copied for cephfs clones https://tracker.ceph.com/issues/49903

**Comment by lion19890901** [comment]
I run an additional pod to monitor the new added pvc base on cephfs, then chmod to 777.

**Comment by davidmather** [comment]
Hi @lion19890901 

Sure the issue is that the chown command fails unless the correct user is in place even with fsgroup set and the user is defaulting to root forcing pods to run as root to have write access to the share.

['/usr/bin/chown', 'jboss_user:jboss', ' /share/node/data']
Failed to change chown directory /shared/node/data to jboss_user:jboss
b"/usr/bin/chown: changing ownership of  /shared/node/data': Operation not permitted\n"
['/usr/bin/chmod', '2775', ' /shared/node/data']
/usr/bin/chmod 2775  /shared/node/data completed succesfully!
['/usr/bin/chown', 'jboss_user:jboss', ' /shared/node/data']
Failed to change chown directory /shared/node/data to jboss_user:jboss
b"/usr/bin/chown: changing ownership of ' /shared/node/data': Operation not permitted\n"

We are trying to run on redhat openshift with the most restrictive security policy which forces a random UID meaning we have no control over the uid of the container for access to the share.

**Comment by CreadDiscans** [comment]
I didn't found configuration for default 777 mode.
So I forked ceph-csi 3.13 version and update code. [commit](https://github.com/CreadDiscans/ceph-csi/commit/6d1c656b687f392e24d62791ef1d79464cd1d9b2)
I deployed to creaddiscans/cephcsi:v3.13 as docker hub image.
The image is set in ROOK_CSI_CEPH_IMAGE field  of "rook-ceph-operator-config"  configmap
This works well for me.
