### ISSUE TITLE
`deviceClass` changes in pool object does not update crush rules 

### ISSUE THREAD

**Issue by Gentoli** [rook/rook#12263]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Updating the `deviceClass` in `CephBlockPool`, `CephFilesystem` etc is allowed but does not result in any changes to Ceph.

**Expected behavior:**
- Rook updates ceph config to reflect the change
- Rook sets the `status` to degraded to indicate the user needs to make this change manually

**How to reproduce it (minimal and precise):**

- create a `CephBlockPool` with `deviceClass` set to `ssd` 
- `ceph osd crush rule dump ceph-rbd-single-ssd`
  ``` json
  {
      "rule_id": 12,
      "rule_name": "ceph-rbd-single-ssd",
      "type": 1,
      "steps": [
          {
              "op": "take",
              "item": -9,
              "item_name": "default~ssd"
          },
          {
              "op": "choose_firstn",
              "num": 0,
              "type": "osd"
          },
          {
              "op": "emit"
          }
      ]
  }
  ```
- update `deviceClass` to `hdd`
- operator logs `cephclient: reconciling replicated pool ceph-rbd-single-ssd succeeded` ([code](https://github.com/rook/rook/blob/943128dce4b623d49c9c94e9216804139b273f0f/pkg/daemon/ceph/client/pool.go#LL472C16-L472C43)) after update or restart
- same result from `ceph osd crush rule dump ceph-rbd-single-ssd` 

**Other Notes**:
- There was https://github.com/rook/rook/issues/5463, seems like being able to update the device class is the expected behaviour.
- I don't think there is a code path in rook that does the device class change (at least for a replicated pool)
  - This is the main update function https://github.com/rook/rook/blob/943128dce4b623d49c9c94e9216804139b273f0f/pkg/daemon/ceph/client/pool.go#L412
  - The only place I see a reference to device class is [createReplicationCrushRule](https://github.com/rook/rook/blob/943128dce4b623d49c9c94e9216804139b273f0f/pkg/daemon/ceph/client/pool.go#L680).  It's ran every time an update happens, but the ceph command is only valid for creating a rule
    ``` shell
    sh-4.4$ ceph osd crush rule create-replicated ceph-rbd-single-ssd default osd ssd
    rule ceph-rbd-single-ssd already exists
    sh-4.4$ echo $?
    0
    ```

**File(s) to submit**:
N/A
**Logs to submit**:
N/A

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): `Fedora CoreOS 37.20221225.3.0`
* Kernel (e.g. `uname -a`): `Linux x10 6.0.15-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 21 18:33:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Single Node, Mix NVMe and HDDs
* Rook version (use `rook version` inside of a Rook Pod): `v4.12.0-0.f4e99907f9b9f05a190303465f61d12d5d24cace`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 16.2.10-94.el8cp (48ce8ed67474ea50f10c019b9445be7f49749d23) pacific (stable)`
* Kubernetes version (use `kubectl version`):
  ``` 
  Client Version: v1.24.1
  Kustomize Version: v4.5.4
  Server Version: v1.25.0-2655+18eadcaadf0be7-dirty
  ```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OKD
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
  ```
  HEALTH_WARN 3 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set; Reduced data availability: 1 pg inactive; 6 pool(s) have no replicas configured
  ```

**Comment by sp98** [comment]
Currently rook does not support this. Looks like manual 

Trying to understand this from ceph's perspective.  What's the impact of not having the updated deviceClass in the crush map?

$ ceph osd crush rm-device-class osd.$OSD
$ ceph osd crush set-device-class ssd osd.$OSD

**Comment by Gentoli** [comment]
@sp98 This is for the pool side OSDs are fine I think. i.e. change a ceph fs pool from hdd to ssd.

**Comment by Gentoli** [comment]
@sp98 any update for this?

**Comment by BlaineEXE** [comment]
@Gentoli, Rook does not support changing the device class after initial creation, and believe the code needed to support this is risky enough for data safety that we would want to reject a proposal to have Rook do so.

IMO, the bug here is that the operator doesn't return an error when users try changing the value. We should make sure the admission webhook rejects changes to the value as well.

**Comment by Gentoli** [comment]
@BlaineEXE Thanks for the reply. 

AFAIK updating crush rules alone should be fairly safe and should be a standard operation. **This should be the same operation/risk as failure domain updates where Rook already is capable doing.** It will cause the cluster into HEALTH_WARN state but will become healthy after data is moved. Maybe before running an update, you can require the cluster to be healthy otherwise require a `yes-i-really-mean-it` arg similar to `continueUpgradeAfterChecksEvenIfNotHealthy` on CephCluster?

> The cluster will enter HEALTH_WARN and move the objects to the right place on the ssd's or assigned device class until the cluster is HEALTHY again.
https://www.suse.com/support/kb/doc/?id=000019699


I do agree currently it's confusing applying an update results in no effect, even a message showing the mismatch in status would be nice. I would be very careful with admission webhook rejecting changes, if an user _does_ update the device class manually, preventing/missing the update on the k8s object might cause confusion when troubleshooting.

_Also: Upon further testing, it seems Rook will happily apply a new device class if a new failure domain rule is created._

**Comment by samcday** [comment]
I ran into this issue today. I have a Ceph cluster that started with some shrimpy SSD OSDs. I then added some much larger nvme drives, which were not being correctly utilized as I had initially created my ceph-blockpool with `deviceClass: ssd`. I tried to remove the device class from the CephBlockPool, then I tried setting it explicitly to nvme. Both attempts reported successful reconciliation, but no rebalancing took place.

I followed this [SUSE guide](https://www.suse.com/support/kb/doc/?id=000019699) on migrating an existing pool from one device class to another. In short, I did this:

```
ceph osd crush rule create-replicated replicated_nvme default host nvme
ceph osd pool set ceph-blockpool crush_rule replicated_nvme
```

The rebalancing is now taking place as expected.

Given that changing the CRUSH rule for a pool causes Ceph to undergo standard recovery mechanisms, it seems like it should be "safe" to reconcile device class changes for a `CephBlockPool`, right?

What if the crush rules that Rook reconciled were "versioned"? i.e the `metadata.generation` of the underlying CephBlockPool is used. This would mean each change to the blockpool would cause a new CRUSH rule to be created, and then once the pool has been successfully updated to the new rule, the old one would be deleted.

If such a proposal sounds sane, reasonable and desirable, I'd be happy to roll up my sleeves and try to contribute this. Please just let me know!

**Comment by travisn** [comment]
#13069 is actually in progress, should be coming soon...

**Comment by samcday** [comment]
Oh that's wonderful, thanks @subhamkrai !

**Comment by samcday** [comment]
The linked PR is merged and I think I saw some notes about this in 1.13,  but I don't think this issue should be closed as stale.

**Comment by subhamkrai** [comment]
already in 1.13, Thanks
