### ISSUE TITLE
Set unhealthyPodEvictionPolicy to AlwaysAllow to better drain nodes

### ISSUE THREAD

**Issue by Jeansen** [rook/rook#12262]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
With Kubernetes 1.27 `unhealthyPodEvictionPolicy` went beta and is enabled by default and set to `IfHealthyBudget` . I suggest to always set it to `AlwaysAllow`, see recommendation in https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/ and also make this configurable.

**What is use case behind this feature:**
The reasoning is my experience: whenever I drain a node with active PDBs, I had to use this logic before 1.27.

```
if kubectl drain $node_to_drain --delete-emptydir-data --ignore-daemonsets --timeout=300s; then
        echo "Node successfully drained"
        drained=true
elif kubectl -n rook-ceph get pdb rook-ceph-osd-host-$node_to_drain; then
        echo "Rook-Ceph is preventing this node from draining, retrying ..."
else
        echo "Cannot drain nodes normally, continuing with forced drain..."
        kubectl drain $node_to_drain --ignore-daemonsets --delete-emptydir-data --force --grace-period=0 --disable-eviction
        drained=true
        echo "Node successfully drained"
fi

if [[ $(hostname) =~ master0 ]]; then
    sudo kubeadm upgrade apply $(sudo kubeadm upgrade plan | grep -owP "v\d\.\d\d\.\d{1,2}" | uniq) -y
else
    sudo kubeadm upgrade node
fi
sudo apt-mark hold kubeadm

```
Now, with the default of `unhealthyPodEvictionPolicy: IfHealthyBudget`, it takes some time, but ultimately a node gets drained. My little script is no longer necessary. Anyway, with 'AlwaysAllow: unhealthyPodEvictionPolicy', I can drain nodes more flawlessly and on't have to wait for a hard eviction.

**Environment**:

Kubernetes 1.27+

**Comment by sp98** [comment]
@Jeansen Read about `unhealthyPodEvictionPolicy`

PDB implementation in Rook is more about  waiting for pods to be healthy. When a node is drained, the OSD pod in that node goes down. Rook blocks draining of other nodes until the pgs are back to active+clean. 

So I don't think `unhealthyPodEvictionPolicy` might be much of a use in rook.  If you want more fine grained controller over this, I would suggest trying out `PGHealthCheckTimeout` option.

**Comment by sp98** [comment]
@Jeansen Let me know your thoughts.

**Comment by Jeansen** [comment]
@sp98 Thanks for the details. Well, I have no strong feelings about these new settings in 1.27. I must admit, I wasn't aware of PGHealthCheckTimeout. If that's the way to got by the rook design, then that's fine with me :-) I'll close this one then.
