### ISSUE TITLE
Update CI pipeline - run integration tests on oldest and newest versions of k8s

### ISSUE THREAD

**Issue by dangula** [rook/rook#1227]
During CI, we are currently running integration tests aganist latest version of k8s for 1.6,1.7 and 1.8(1.6.11,1.7.9 and 1.8.3 as of 11/13/7). We need to update the integration test so that we run  tests aganist the oldest and newest minor version of k8s 1.6,1.7 and 1.8.

**Comment by travisn** [comment]
Let's not double the test matrix. What if we just run on the latest (1.6.11, 1.7.9, 1.8.3), and now add one more version, which is the oldest supported version? In this case I would believe that to be 1.6.0 since we have had issues running the tests on 1.5.x.
