### ISSUE TITLE
handle long slow ops in cluster

### ISSUE THREAD

**Issue by microyahoo** [rook/rook#12275]
Today, we encountered a slow ops in our production cluster, causing ops to be blocked for a long time, resulting in the cluster being unavailable like below. The cluster comes to normal after we kill the corresponding osd pod. Therefore, if slow ops blocks for more than a certain time, the corresponding osd pod should be killed, otherwise the cluster will be unavailable.
```console
[root@node01 pg]# ceph health detail                                                             
HEALTH_WARN 1 clients failing to respond to capability release; 1 MDSs report slow metadata IOs; Reduced data availability: 4 pgs inactive, 4 pgs peering; 256 slow ops, oldest one blocked for 3285 sec, osd.29 has slow ops                                                                       
[WRN] MDS_CLIENT_LATE_RELEASE: 1 clients failing to respond to capability release
     mds.cephfs-a(mds.0): Client node07.prod-k8s.bm.pd.sz.deeproute.ai:apt failing to respond to capability release client_id: 1848105444                                                           
[WRN] MDS_SLOW_METADATA_IO: 1 MDSs report slow metadata IOs
     mds.cephfs-a(mds.0): 17 slow metadata IOs are blocked > 30 secs, oldest blocked for 3065 secs                                                                                                  
[WRN] PG_AVAILABILITY: Reduced data availability: 4 pgs inactive, 4 pgs peering                                                                                                                    
  data:           
    volumes: 1/1 healthy
    pg 34.1c is stuck peering for 54m, current state peering, last acting [29,6,96,99,67,72,7,104]                                                                                                 
    pg 34.5c is stuck peering for 4m, current state remapped+peering, last acting [29,6,96,2147483647,67,72,7,104]                                                                                 
    pg 34.9c is stuck peering for 54m, current state peering, last acting [29,6,96,99,67,72,7,104]                                                                                                 
    pg 34.dc is stuck peering for 4m, current state remapped+peering, last acting [29,6,96,2147483647,67,72,7,104]                                                                                 
[WRN] SLOW_OPS: 256 slow ops, oldest one blocked for 3285 sec, osd.29 has slow ops
```

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
s3 read and write are blocked, the cluster is unavailable

**Expected behavior:**
If slow ops blocks for more than a certain time, the corresponding osd pod should be killed, otherwise the cluster will be unavailable.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by sp98** [comment]
Is the cluster back to healthy after the deleted osd pod got added back?

**Comment by microyahoo** [comment]
> Is the cluster back to healthy after the deleted osd pod got added back?

yes, it comes back to healthy after osd pod was deleted and recreated automatically again.

**Comment by microyahoo** [comment]
The issue occurs again
```console
[root@node01 pg]# ceph health detail
HEALTH_WARN Reduced data availability: 4 pgs inactive, 4 pgs peering; 20 slow ops, oldest one blocked for 1343 sec, daemons [osd.102,osd.19,osd
.23,osd.60,osd.67,osd.99] have slow ops.
[WRN] PG_AVAILABILITY: Reduced data availability: 4 pgs inactive, 4 pgs peering
    pg 34.29 is stuck peering for 21m, current state peering, last acting [60,69,55,5,67,9,12,92]
    pg 34.49 is stuck peering for 21m, current state peering, last acting [60,52,59,88,69,94,5,57]
    pg 34.a9 is stuck peering for 21m, current state peering, last acting [60,69,55,5,67,9,12,92]
    pg 34.c9 is stuck peering for 21m, current state peering, last acting [60,52,59,88,69,94,5,57]
[WRN] SLOW_OPS: 20 slow ops, oldest one blocked for 1343 sec, daemons [osd.102,osd.19,osd.23,osd.60,osd.67,osd.99] have slow ops.
```
below is output of corresponding `ceph daemon osd status`
```console
[root@node01 ceph]# ceph daemon /var/run/ceph/ceph-osd.60.asok status
{
    "cluster_fsid": "f7f1c8ba-f793-436b-bb73-0964108a30c1",
    "osd_fsid": "18f46129-c6e0-4d5e-8939-a0a657ecf2b8",
    "whoami": 60,
    "state": "active",
    "oldest_map": 48434,
    "newest_map": 63732,
    "num_pgs": 44
}
```
