### ISSUE TITLE
For external cluster storage class should be customised

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12279]
**Is this a bug report or feature request?**
* Bug Report

I think so here the in the json output the storage class name should be  variable
https://github.com/rook/rook/blob/372f0a662d20499beaac5a9523013f8cd70103c1/deploy/examples/create-external-cluster-resources.py#L1647
(Only If restricted permission flags is true)

As if we wan't to create multiple Storage Class in same cluster we need to create different storage classes to consume it so the name should be different if two or more pools exist in the same cluster.

@Madhu-1 what are your thoughts on this?

**Comment by travisn** [comment]
@parth-gr Would the solution be to take the storage class names as parameters to the script? The storage class names of `ceph-rbd`, `cephfs`, and `ceph-rgw` are certainly basic.

**Comment by parth-gr** [comment]
right, currently we just support 1 sc per pool so keeping it constant is fine
