### ISSUE TITLE
Integration tests should not run if only documentation is updated

### ISSUE THREAD

**Issue by travisn** [rook/rook#12287]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
All github actions are currently triggered by default for all PRs. If only documentation is updated, there is no need to run the integration tests. 

**Expected behavior:**
We can use [paths-ignore](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-paths-for-pull-request-or-push-events) to skip the integration test actions if only the Documentation path is updated. For example, this trigger could be added in the Canary tests, and all the integration-test-*.yaml files (wherever the `skip-ci` label is currently used):

```yaml
on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'design/**'
```

This will minimize our need for the `skip-ci` label on the PRs.

**Comment by Mourishitz** [comment]
Hello, I forked the repository to contribute.. Would like to know:

* What branch can I reference on the pull request? (example: Merging my forked repository branch on release-1.11)
* Is it necessary to remove the 'skip-ci' tag validation from the integration-test-*.yaml?

Looking forward for it! Thank you.

**Comment by Mourishitz** [comment]
Hey!! I've just created a Pull Request for this issue, thanks for supporting and hope this get the job done!

**Comment by travisn** [comment]
When opened documentation PR #12323 without the `skip-ci` label, the integration tests all ran unexpectedly. Since this PR was merged, we were hoping doc updates would automatically not run the integration tests. 
@Mourishitz Could you investigate why this isn't working as expected?

**Comment by travisn** [comment]
Nevermind, I spoke too soon. #12323 contains a file at the root of the repo, outside the docs or design folders.
