### ISSUE TITLE
support other options besides device names since those change across reboots

### ISSUE THREAD

**Issue by lorenz** [rook/rook#1228]
Currently Rook does not work with symlinked devices (/dev/zvol, /dev/disk/by-id, LVM, ...), it requires a real device inode. This makes it hard to use on block device providers (I'm personally interested in LVM and ZFS zvol) for which these inodes are not consistent across reboots. Rook code extensively works with raw inode names, so I don't really know where support for that should be implemented.

**Comment by costrouc** [comment]
Bump. I have had the same issue and would really like to use `/dev/disk/by-id/*` symlinked devices. There is no way to guarantee consistent naming to `/dev/sd* `

**Comment by mhulscher** [comment]
I too would like to be able to use `/dev/disk/by-id/*` instead of the `/dev/xxx` ...

**Comment by costrouc** [comment]
@mhulsher I forgot to update my response in this issue. I talked with the devs on slack and I looks like rook uses the `/dev/disk/by-partuuid/` once it has created the osds. This guarantees that once the osds are prepared the correct osd is always selected even if `/dev/sd*` changes. But I do agree that `by-id` would be nice to use.

**Comment by jbw976** [comment]
The issue of device names changing across reboots was addressed in the cluster update design doc at https://github.com/rook/rook/blob/master/design/cluster-update.md#device-name-changes

However, also adding support for `/dev/disk/by-id/` and the like would still be quite useful.

**Comment by sjdevries** [comment]
I'd love to see /dev/disk/by-path/

IIRC,  on my server the SAS expander backplane or the HBA has limits on mixing SAS / SATA,  ssd/hdd drives.  Specifically bays 0-1 are supposed to be the two used for cache drives when mixing types.

It would be great to be able to set metadata to the /dev/disk/by-path/ for those 2 bays and storage to the paths for the other 10.

Not sure if newer hardware has similar issues with NVMe / SAS / SATA / etc.

**Comment by pdf** [comment]
Even ignoring reboots, being able to reference backing disks by stable device names would be very useful, particularly for environments where the disks may be attached dynamically, and (along with rook) programmatically.

**Comment by jbw976** [comment]
As described in https://github.com/rook/rook/blob/master/design/multiple-storage-types-support.md#storagescopespec, a user should be able to use the StorageScopeSpec to select devices not just by name, but other more persistent properties such as `by-id` or `by-path`.

**Comment by alfredodeza** [comment]
Once rook stats using ceph-volume, this will not be a problem since LVM takes care of matching a device to its logical volume name

**Comment by lorenz** [comment]
Honestly an even better idea would be to rely on Kubernetes volumes and block devices which would make the whole detection and identity thing just go away. Security-wise it's also pretty nice since it woud forego the requirement to have any sort of privileged access.

I'm working on a CSI ZFS provisioner which can provision local volumes and block devices which could then be used to run Rook on top of it. This would allow a nicely layered setup, some sort of local storage system for things that need local storage or can live with downtime when moving storage and distributed storage systems layered on top of that.

**Comment by Bessonov** [comment]
Activity!

**Comment by travisn** [comment]
@mvollman Weren't you looking at configuring OSDs based on the full path for the device? I can't seem to find a related PR, but I was sure one was at least in progress.

**Comment by mvollman** [comment]
@travisn I am not currently looking into it.  It did come up in the scope of another PR a while back, but I was unable to add the capability at that time.  I will try to find time to take another look at it.

**Comment by pdf** [comment]
Looks like this is released with v1.1?

**Comment by tarjintor** [comment]
hello,it seems I met the problem too.
My collegue add some new disks to my cluster,and restart the node
Then the disk name changed.
I used to use device: sdb 
but now sdb is the new disk,and osd find the disk is empty and recovery now
Can we use uuid to select the osd device now?

**Comment by BlaineEXE** [comment]
Is this resolved by #4285 ?

**Comment by muhlba91** [comment]
Since we would need this change: is a backport to 1.2 planned or will the 1.3 release be available rather soon-ish? :)

**Comment by travisn** [comment]
It isn't planned for backport to 1.2. The target for 1.3 is early next week.
