### ISSUE TITLE
Chaining snapshots and clones while deleting old ones eventually makes clone unmountable

### ISSUE THREAD

**Issue by jrcichra** [rook/rook#12312]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
This was done as a stress-test of what was possible with how VolumeSnapshots are designed and how it interacts with Rook/Ceph.

When continuously snapshotting and cloning a PVC and promptly deleting previous snapshots and clones equivalent to playing a game of snake with a short tail, trying to mount and write to the 10th clone results in this error:
```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               14m                  default-scheduler        Successfully assigned default/loop-9-g6h57 to worker1
  Normal   SuccessfulAttachVolume  14m                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-7133a60b-9a4f-4584-a467-22dbead150b6"
  Warning  FailedMount             7m48s (x2 over 10m)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-api-access-p8swp data]: timed out waiting for the condition
  Warning  FailedMount             69s (x14 over 14m)   kubelet                  MountVolume.MountDevice failed for volume "pvc-7133a60b-9a4f-4584-a467-22dbead150b6" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
  Warning  FailedMount  59s (x4 over 12m)  kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-p8swp]: timed out waiting for the condition
```

My *hunch* is it has something to do with the flattening logic timing in ceph-csi but I'm not entirely sure, so I figured I'd ask here first.

**Expected behavior:**
Regardless of the number of chained snapshots and clones, a cloned volume would always be mountable.

**How to reproduce it (minimal and precise):**

With a little script and a couple of manifests, I can consistently reproduce the issue on v1.11 Rook.

In words, this script:
+ creates a PVC
+ creates a job which writes some data
+ once the job is complete, delete the job
+ take a snapshot of the PVC
+ clone the PVC and wait for everything to settle
+ clean up everything except the clone we just made
+ repeat N times excluding the bootstrap

```
==> clone-loop.sh <==
#!/bin/bash

set -oeu pipefail
set -x

# loop n times
LOOPS="${1:-10}"

# we need to set up the inital environment

export LOOP="loop-0"
cat disk.yaml | envsubst | kubectl apply -f -


for i in $(seq 0 $LOOPS) ;do
    export LOOP="loop-$i"
    # apply a job which writes some data and wait for it to complete
    cat state.yaml | envsubst | kubectl apply -f -
    kubectl wait --for=condition=complete --timeout=9999s job/$LOOP
    # delete the job
    cat state.yaml | envsubst | kubectl delete -f -
    # take a snapshot
    cat snapshot.yaml | envsubst | kubectl apply -f -
    # make a clone
    export LAST_LOOP="$LOOP"
    export LOOP="loop-$(($i+1))"
    cat clone.yaml | envsubst | kubectl apply -f -
    # wait a bit
    sleep 600
    # delete the last volume
    kubectl delete pvc "loop-$(($i))"
    # delete the last snapshot
    kubectl delete volumesnapshot "loop-$(($i))"
done



==> clone.yaml <==
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $LOOP
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-ssd
  resources:
    requests:
      storage: 100Gi
  dataSource:
    kind: VolumeSnapshot
    name: $LAST_LOOP
    apiGroup: snapshot.storage.k8s.io

==> disk.yaml <==
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loop-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-ceph-ssd

==> snapshot.yaml <==
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: $LOOP
spec:
  volumeSnapshotClassName: rook-ceph-ssd
  source:
    persistentVolumeClaimName: $LOOP

==> state.yaml <==
---
apiVersion: batch/v1
kind: Job
metadata:
  name: $LOOP
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: loop
          image: alpine
          command:
            [
              "dd",
              "if=/dev/urandom",
              "of=/data/$LOOP.img",
              "bs=1M",
              "count=1000",
            ]
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: $LOOP
```
Eventually one of the loop* job pods wont' be able to mount the clone.
When removing the delete logic, the script runs to completion.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

volumesnapshot class:
```
apiVersion: v1
items:
- apiVersion: snapshot.storage.k8s.io/v1
  deletionPolicy: Delete
  driver: rook-ceph-ssd.rbd.csi.ceph.com
  kind: VolumeSnapshotClass
  metadata:
    annotations:
      snapshot.storage.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2023-05-26T14:10:33Z"
    generation: 1
    name: rook-ceph-ssd
    resourceVersion: "850058880"
    uid: 8472b571-86e7-40fe-a602-f0ea7478ebd4
  parameters:
    clusterID: rook-ceph-ssd
    csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph-ssd
kind: List
metadata:
```

** Cluster Information **
I'm able to reproduce this by going through the Rook Quickstart with no modifications and installing the example replicated-block setup. I then install the necessary pieces for snapshots via this guide: https://rook.io/docs/rook/v1.11/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot/ and I am able to make rbd snapshots as expected.

**Logs to submit**:
Output of csi-rbdplugin-hbcdj -c csi-rbdplugin on the scheduled box for the stuck pod:
```
E0531 17:58:41.493775   15892 utils.go:210] ID: 178 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
W0531 18:00:47.404455   15892 rbd_attach.go:469] ID: 182 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a rbd: map error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
E0531 18:00:47.404629   15892 utils.go:210] ID: 182 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
W0531 18:02:53.288745   15892 rbd_attach.go:469] ID: 186 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a rbd: map error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
E0531 18:02:53.288924   15892 utils.go:210] ID: 186 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
W0531 18:04:59.134984   15892 rbd_attach.go:469] ID: 190 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a rbd: map error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
E0531 18:04:59.135216   15892 utils.go:210] ID: 190 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
W0531 18:07:04.955071   15892 rbd_attach.go:469] ID: 194 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a rbd: map error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
E0531 18:07:04.955206   15892 utils.go:210] ID: 194 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
W0531 18:09:09.891431   15892 rbd_attach.go:469] ID: 198 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a rbd: map error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
E0531 18:09:09.891563   15892 utils.go:210] ID: 198 Req-ID: 0001-0009-rook-ceph-0000000000000001-8b978541-8495-4c20-bcab-0a42fa927b5a GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian Bullseye Cloud
* Kernel (e.g. `uname -a`): 5.10.0-23-amd64
* Cloud provider or hardware configuration: kubeadm cluster inside KubeVirt with block devices as seen in the VM, but also tested on bare metal with real NVME ssds
* Rook version (use `rook version` inside of a Rook Pod): v1.11.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph:v17.2.6
* Kubernetes version (use `kubectl version`): 1.23.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by Rakshith-R** [comment]
>This was done as a stress-test of what was possible with how VolumeSnapshots are designed and how it interacts with Rook/Ceph.
>When continuously snapshotting and cloning a PVC and promptly deleting previous snapshots and clones equivalent to playing a game of snake with a short tail, trying to mount and write to the 10th clone results in this error:
> ` Warning  FailedMount             69s (x14 over 14m)   kubelet                  MountVolume.MountDevice failed for volume "pvc-7133a60b-9a4f-4584-a467-22dbead150b6" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id csi-rbd-node -m 10.110.0.127:6789,10.109.223.145:6789,10.108.43.136:6789 --keyfile=***stripped*** map replicapool/csi-vol-8b978541-8495-4c20-bcab-0a42fa927b5a --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (22) Invalid argument`
>My hunch is it has something to do with the flattening logic timing in ceph-csi but I'm not entirely sure, so I figured I'd ask here first.

@jrcichra 
Yes, I think the asynchronous flattening that may have been happening in the background could have led to this.
(I vaguely remember seeing this scenario and error in a perf test.)

>Expected behavior:
> Regardless of the number of chained snapshots and clones, a cloned volume would always be mountable.

Regarding the above expected behaviour, the decision to flattening(expensive operation) the image or allowing for chain link between
parent and child images is taken based on various factors and for striking a balance between ceph cluster performance and cephcsi's capability to snapshot/clone PVCs instantaneously.

The scenario tested here `continuously snapshotting and cloning a PVC and promptly deleting previous snapshots and clones` is an edge case and I doubt may actually occur in a production environment.

**Comment by Rakshith-R** [comment]
> @Rakshith-R understood. Thank you for your analysis and explaination. I agree it's an edge case and I personally do not need or plan to write a fix at this time. I did want to raise the issue so others who may run into it see it's a known issue.
> 
> Out of curiosity, if I did find myself in a position where a team had gotten their PVC into this situation, what are some theoretical steps could I take to attempt to recover the volume?

Flattening operation will be completed eventually. IMO, its best to wait it out (the occurrence itself will be very very rare).
You can use `ceph rbd task list` command to check for any flattening operation.

(BTW `sysfs write failed rbd: map failed: (22)` error can be caused by other
factors too, so we cannot blame this scenario every time)

> Am I able to restore RBD images out of the trash to hopefully bring back a layer that can be referenced? 

The last PVC is still very much alive and usable, just need to wait out flattening.
There will be no need to go through such extremes.

> Does Ceph CSI see those and include them in its calculations? 

It gets complicated here, so I cannot give you a direct answer.

> I may try some Ceph operations to see if anything can be done in this situation.

Have you tried waiting ? 
You can use the above task command to observe what's being flattened at what level.
Though you need to keep a track of PVC/snapshost name to rbd image name/id mapping.

**Comment by jrcichra** [comment]
Thanks for clarifying. I'll recommend that teams take it slow and not perform rapid operations.

**Comment by Madhu-1** [comment]
Did we check dmesg logs to identify why `rbd map` command failed?

**Comment by jrcichra** [comment]
No I hadn't checked. Here's the message I'm seeing on the node trying to start the pod when I get into this state:
```
[Thu Jun 15 13:29:56 2023] libceph: mon1 (1)10.32.246.133:6789 session established
[Thu Jun 15 13:29:56 2023] libceph: client21639919 fsid <REDACTED>
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e027e83966: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e0c7a89402: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e0cd1fb941: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e03bc73f96: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e038099ef2: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e03f5ce161: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e083e538ee: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e0173bbac6: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e05b8ad388: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e0f880a9e9: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e0f123f7c5: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e04fdaf8a0: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e0996a495c: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e0247cbb12: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e02f0e1e92: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: id 49c4e0b28ae1f8: unable to get image name
[Thu Jun 15 13:29:56 2023] rbd: parent chain is too long (17)
```

**Comment by Rakshith-R** [comment]
hey @jrcichra,
I've opened https://github.com/ceph/ceph-csi/issues/4013 to traige this further. 

The only WA currently is to flatten the child PVC before mounting manually.

I think we can continue triaging in that issue.

**Comment by jrcichra** [comment]
Thanks!

**Comment by parth-gr** [comment]
@Rakshith-R is this still needed to be open

**Comment by Rakshith-R** [comment]
> @Rakshith-R is this still needed to be open

The issue is still not fixed
https://github.com/ceph/ceph-csi/pull/4029
