### ISSUE TITLE
Rook on KinD/K3D will happily erase LVM partitions

### ISSUE THREAD

**Issue by dpeckett** [rook/rook#12321]
**Is this a bug report or feature request?**
* Bug Report

**Expected behavior:**

Rook should not erase LVM partitions containing data.

I'm aware now that running Rook on KinD clusters is not officially supported but there are applications where virtualization is not possible (eg. host device access). It can be useful to run for example the RADOSGW locally on a loopback device (for local development purposes).

I've been able to trace the issue down to the mitigation implemented in #9470 not working for LVM partitions due to `lsblk` not returning any filesystem information. In this case I think we should also invoke `pvs` or something to check if the partition contains LVM volumes.

I've been able to workaround this for my local dev purposes by mounting the host udev rundir into the K3D cluster (and being careful to never use useAllDevices = true).

**How to reproduce it (minimal and precise):**

Install Rook and create `cluster-test.yaml` on a KinD/K3D/Minikube-docker cluster running on a host which has LVM partitions. Any data on the LVM partitions will be destroyed.

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 11 (bullseye)
* Kernel (e.g. `uname -a`): Linux 5.10.0-23-amd64 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod): v1.11.7
* Kubernetes version (use `kubectl version`): v1.27.1+k3s1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): K3D

**Comment by travisn** [comment]
While running in a non-virtualized environment is not recommended as you noticed, adding a check for LVs before creating an OSD should be very doable so we can prevent unintentional data loss in any case.

**Comment by dpeckett** [comment]
I've created a small fork of rook that's intended to be safe for use with dev environments (btw minikube uses a containerizd kubernetes driver by default now, ask me how I found out).

Perhaps we can cherry pick some of the changes upstream.

https://github.com/gpu-ninja/rook/commit/207aa025755dcd1dccdfb6c44773ff78a903cd29

**Comment by travisn** [comment]
Yes, would be great to have some of those changes upstream. Could you [open a PR](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request) for this? I haven't looked in detail at the changes, but the PR will be a good place to discuss the details. Thanks!
