### ISSUE TITLE
command "ceph mon_status" has no response in rook-operator 0.6.0

### ISSUE THREAD

**Issue by mossinfan** [rook/rook#1233]
Now I meet a problem in the processing of installing rook.
it is that operator can't create the second ceph mon node in k8s cluster.

My k8s node and pod:
```
I068528@pvgl50801822a:~$ kubectl -n rook-system get po
NAME                             READY     STATUS    RESTARTS   AGE
rook-agent-b7ngs                 1/1       Running   0          13m
rook-agent-blpck                 1/1       Running   0          13m
rook-agent-bv6cc                 1/1       Running   0          13m
rook-agent-cm82x                 1/1       Running   0          13m
rook-agent-cz9zj                 1/1       Running   0          13m
rook-agent-h4k8x                 1/1       Running   0          13m
rook-agent-jvg62                 1/1       Running   0          13m
rook-agent-mfc28                 1/1       Running   0          13m
rook-agent-s84lt                 1/1       Running   0          13m
rook-agent-s8wdq                 1/1       Running   0          13m
rook-agent-tc95x                 1/1       Running   0          13m
rook-operator-64cd4678cd-vnlj5   1/1       Running   0          13m
```

ceph-mon0 
```
NAME                   READY     STATUS    RESTARTS   AGE
rook-ceph-mon0-5x8ff   1/1       Running   0          15m
rook-tools             1/1       Running   0          13m
```

the log of rook-operator 
```
2017-11-15 05:24:22.575430 I | exec: Running command: ceph mon_status --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/roo
k/rook/client.admin.keyring --format json --out-file /tmp/538534999
2017-11-15 05:29:22.771076 I | exec: 2017-11-15 05:29:22.741859 7f857fe9d700  0 monclient(hunting): authenticate timed out after 300
2017-11-15 05:29:22.741859 7f857fe9d700  0 monclient(hunting): authenticate timed out after 300
2017-11-15 05:29:22.741918 7f857fe9d700  0 librados: client.admin authentication error (110) Connection timed out
2017-11-15 05:29:22.741918 7f857fe9d700  0 librados: client.admin authentication error (110) Connection timed out
[errno 110] error connecting to the cluster
2017-11-15 05:29:27.771784 I | exec: Running command: ceph mon_status --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/roo
k/rook/client.admin.keyring --format json --out-file /tmp/272333770
```
-----------------------------------------------------------------------------------------------------
command "Running command: `ceph mon_status --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/roo
k/rook/client.admin.keyring --format json --out-file /tmp/538534999`

has no response.

**Comment by travisn** [comment]
@mossinfan Could this be the issue? What is the last message in the log for the mon pod?
 https://rook.io/docs/rook/master/common-problems.html#only-a-single-monitor-pod-starts-after-redeploy

**Comment by mossinfan** [comment]
@travisn I think my problem is  not the same as in the wiki.
the first mon pod was successful in my case.

the log of mon pod:
2017-11-15 06:23:25.564009 I | rook-ceph-mon0: 2017-11-15 06:23:25.563814 7f3eae530700  0 mon.rook-ceph-mon0@0(leader).data_health(3) update_stats avail 82%!t(MISSING)otal 27399 MB, used 3653 MB, avail 22535 MB

**Comment by travisn** [comment]
it looks like you started the rook-tools pod. Are you able to connect to it and execute commands? If so, what is the output of `rookctl status` or `ceph status`?
https://rook.io/docs/rook/master/common-problems.html#troubleshooting-techniques

**Comment by mossinfan** [comment]
@travisn 
after I create the rook-agent 's role and role-binding manually, the cluster has been setup successful.

**Comment by kokhang** [comment]
The operator should have created the role and binding at startup. Can you show me the logs from the operator? The beginning logs is more interesting.

**Comment by travisn** [comment]
@mossinfan please re-open if there is still an issue here

**Comment by soggiest** [comment]
I'm seeing the same issue as the original post. I've tried destroying and recreating the cluster a handful of times and I get the same response.

**Comment by HighwayofLife** [comment]
I've also started seeing this pop up, and it's stumping me at the moment.

**Comment by jiuchen1986** [comment]
Seeing this issue in v1.0.2 after redeploying. Any update on this issue?

**Comment by travisn** [comment]
@jiuchen1986 If the ceph status isn't responding, there is an issue in your environment where the mons are either not in quorum or there is not network connectivity from the client. [This topic](https://rook.io/docs/rook/v1.0/ceph-common-issues.html#monitors-are-the-only-pods-running) may help troubleshoot.
