### ISSUE TITLE
Frequent edit to cephCluster leads to controller runtime error `port 8080` already in use

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#12331]
**Is this a bug report or feature request?**
* Bug Report

When cephCluster cr is changed so frequently that the previous reconciliation is not finished and a new one is started it
results in 2 controller runtime managers active at a single time. This gives error
```
failed to run operator: gave up running the operator manager: failed to set up overall controller-runtime manager: error listening on 8080: listen tcp :8080: bind: address already in use
```
last line operator log
```
client rate limiter Wait returned an error: context canceled
```

**Deviation from expected behavior:**

frequent edits to cephCluster should not give an error

**Expected behavior:**
wait for the first reconciliation to finish before starting a new one

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by haoxiaoci** [comment]
i have this problem too in rook version v1.11.4
is there any update?
i patch 11 disks on cephcluster CR.
i got operator logs:

`
2024-11-13 09:15:58.390597 I | ceph-cluster-controller: CR has changed for "rook-ceph". diff=  v1.ClusterSpec{                                                                                 
        CephVersion: {Image: "ceph/ceph:v17.2.6"},                                                                                                                      
        Storage: v1.StorageScopeSpec{  
...
 "/dev/disk/by-id/scsi-3600605b00e7913202b4aa92512081dec", Config: {"deviceClass": "hdd"}}, {Name: "/dev/disk/by-id/scsi-3600605b00e7913202b4aa9010fdee40f", Config: {"deviceClass": "hdd"}}, {Name: "/dev/disk/by-id/scsi-3600605b00e7913202b4aa91310f14eaa", Config: {"deviceClass": "hdd"}}, ...}}},                                                                                       
                },                                                                             
                UseAllNodes:           false,                                                  
                OnlyApplyOSDPlacement: false,                                                                                                                                                  
                ... // 3 identical fields                                                      
        },                                                                                                                                                                                     
        Annotations: nil,                                                                                                                                                                      
        Labels:      nil,                                                                      
        ... // 20 identical fields                                                             
  }                                                        
2024-11-13 09:15:58.488579 I | operator: reloading operator's CRDs manager, cancelling all orchestrations!
2024-11-13 09:15:58.489316 I | operator: setting up the controller-runtime manager
2024-11-13 09:15:58.490794 I | op-k8sutil: ROOK_CURRENT_NAMESPACE_ONLY="false" (env var)
2024-11-13 09:15:58.490805 I | operator: watching all namespaces for Ceph CRs
2024-11-13 09:15:58.490829 I | operator: setting up schemes
2024-11-13 09:15:58.587944 I | operator: setting up the controller-runtime manager
2024-11-13 09:15:58.788190 C | rookcmd: failed to run operator: gave up to run the operator manager: failed to set up overall controller-runtime manager: error listening on :8080: listen tcp :8080: bind: address already in use
`
this problem happens so often that I can't ignore it.

**Comment by travisn** [comment]
1. Are you frequently updating the CephCluster CR? For example, do you see a lot of CR updates and the operator is in a loop reconciling again and again? 
2. How often do you see this error?
3. Does restarting the rook operator resolve the problem at least temporarily?
4. Please update Rook, to see if a newer version will resolve this with updates we have made to the controller runtime.
