### ISSUE TITLE
HEALTH_ERR Module 'devicehealth' has failed: unknown operation

### ISSUE THREAD

**Issue by panzehao** [rook/rook#12349]
My rook-ceph crashed because of vsphere crashed！when I restart the vm , I found some alerts,most of them restored,but there is an error: Module 'devicehealth' has failed: unknown operation

rook-ceph: ceph version 15.2.17 (8a82819d84cf884bd39c17e3236e0632ac146dc4) octopus (stable)

1 mgr crashed (restored)
2 daemons crashed (restored)
the alert "Module 'devicehealth' has failed: unknown operation " I dont know how to fix it or just archive is ok

here is logs:
6/6/23 8:40:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation

6/6/23 8:30:00 PM
[ERR]
Module 'devicehealth' has failed: unknown operation

6/6/23 8:30:00 PM
[ERR]
[ERR] MGR_MODULE_ERROR: Module 'devicehealth' has failed: unknown operation

6/6/23 8:30:00 PM
[ERR]
Health detail: HEALTH_ERR Module 'devicehealth' has failed: unknown operation

6/6/23 8:20:25 PM
[INF]
Health check cleared: RECENT_CRASH (was: 2 daemons have recently crashed)

6/6/23 8:20:00 PM
[ERR]
osd.2 crashed on host rook-ceph-osd-2-847d8658c-lcmt9 at 2023-06-06T07:39:20.912557Z

6/6/23 8:20:00 PM
[ERR]
osd.4 crashed on host rook-ceph-osd-4-784f686ccd-vfhpl at 2023-06-06T07:14:29.378134Z

6/6/23 8:20:00 PM
[ERR]
[WRN] RECENT_CRASH: 2 daemons have recently crashed

6/6/23 8:20:00 PM
[ERR]
Module 'devicehealth' has failed: unknown operation

6/6/23 8:20:00 PM
[ERR]
[ERR] MGR_MODULE_ERROR: Module 'devicehealth' has failed: unknown operation

6/6/23 8:20:00 PM
[ERR]
Health detail: HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed

6/6/23 8:19:59 PM
[INF]
Health check cleared: RECENT_MGR_MODULE_CRASH (was: 1 mgr modules have recently crashed)

6/6/23 8:10:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 8:00:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 7:50:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 7:40:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 7:30:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 7:20:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 7:10:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 7:00:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 6:50:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 6:40:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 6:30:00 PM
[ERR]
overall HEALTH_ERR Module 'devicehealth' has failed: unknown operation; 2 daemons have recently crashed; 1 mgr modules have recently crashed

6/6/23 6:20:00 PM
[ERR]
mgr module devicehealth crashed in daemon mgr.b on host rook-ceph-mgr-b-cb5f79698-v2n4r at 2023-06-06T07:16:21.180571Z

6/6/23 6:20:00 PM
[ERR]
[WRN] RECENT_MGR_MODULE_CRASH: 1 mgr modules have recently crashed

6/6/23 6:20:00 PM
[ERR]
osd.2 crashed on host rook-ceph-osd-2-847d8658c-lcmt9 at 2023-06-06T07:39:20.912557Z

6/6/23 6:20:00 PM
[ERR]
osd.4 crashed on host rook-ceph-osd-4-784f686ccd-vfhpl at 2023-06-06T07:14:29.378134Z

6/6/23 6:20:00 PM
[ERR]
[WRN] RECENT_CRASH: 2 daemons have recently crashed

6/6/23 6:20:00 PM
[ERR]
Module 'devicehealth' has failed: unknown operation

6/6/23 6:20:00 PM
[ERR]
[ERR] MGR_MODULE_ERROR: Module 'devicehealth' has failed: unknown operation

rook-ceph works fine now, but ceph health is always to be :

[root@test-master02 ~]# ceph -s
cluster:
id: 2aa064e5-1a34-403b-9e6a-bc7e2f913afa
health: HEALTH_ERR
Module 'devicehealth' has failed: unknown operation

services:
mon: 3 daemons, quorum a,b,c (age 3h)
mgr: b(active, since 17h), standbys: a
mds: 1/1 daemons up, 1 hot standby
osd: 8 osds: 8 up (since 14h), 8 in (since 16h)

data:
volumes: 1/1 healthy
pools: 4 pools, 81 pgs
objects: 3.30k objects, 9.4 GiB
usage: 33 GiB used, 1.5 TiB / 1.6 TiB avail
pgs: 81 active+clean

io:
client: 1.4 KiB/s rd, 10 KiB/s wr, 2 op/s rd, 1 op/s wr

So how can i fix it to HEALTH_OK

**Comment by TomHellier** [comment]
I've seen this ever so often, restarting the mgr pod seems to clear it

**Comment by panzehao** [comment]
> 

It works，thks a lot~
I can't find this answer on official document and google~


> I've seen this ever so often, restarting the mgr pod seems to clear it

**Comment by panzehao** [comment]
just delete mgr pods

**Comment by shubham-uipath** [comment]
But why is this issue coming at first place , Is this  some new feature in Ceph to monitor device health , which is detecting device level failures ?

Is this a known issue and fixed  in some ceph version ?
