### ISSUE TITLE
Fieldselector only works with metadata.{name/namespace}

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#12350]
**Is this a bug report or feature request?**
* Bug Report
Below code uses `spec.node` in the fieldSelector https://github.com/rook/rook/blob/12d79814d3ce52c7bcee8d40f7ceb9c046449efa/pkg/operator/ceph/cluster/cephstatus.go#L328-L330 but seems like kubernetes supports only metadata.name or metadata.namespace in the fieldSelector. See the below error
```
"spec.csi.driver" is not a known field selector: only "metadata.name", "metadata.namespace"
```

**Deviation from expected behavior:**
Using `spec.node` in the fieldSelector which is not supported. 

**Expected behavior:**
We should use anything else other than metadata.name/ metadata.namespace in fieldSelector.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by BlaineEXE** [comment]
I'm not sure this is flagging the right code line for the error. Note that the line says `spec.nodeName` for a v1/Pod resource. The error reported is for `spec.csi.driver`.

`spec.nodeName` is a valid field selector for Pods according to a quick kubectl test:
```
kubectl -n kube-system get pod --field-selector spec.nodeName=minikube
NAME                               READY   STATUS    RESTARTS      AGE
coredns-5d78c9869d-x5jcg           1/1     Running   0             52s
etcd-minikube                      1/1     Running   0             65s
kube-apiserver-minikube            1/1     Running   0             65s
kube-controller-manager-minikube   1/1     Running   0             65s
kube-proxy-p9962                   1/1     Running   0             52s
kube-scheduler-minikube            1/1     Running   0             65s
storage-provisioner                1/1     Running   1 (22s ago)   64s
```
