### ISSUE TITLE
[REOPEN] External cluster setup issues

### ISSUE THREAD

**Issue by giuseppe-martinelli** [rook/rook#12351]
[https://github.com/rook/rook/issues/6502](https://github.com/rook/rook/issues/6502)

Still there on Ceph tools v17.2.6

**Comment by parth-gr** [comment]
@giuseppe-martinelli can you elaborate on the issue, or is the same as previous one you opened?

**Comment by parth-gr** [comment]
Can you share the `ceph -s` from the external node

And also I would suggest you to follow this doc for the process it has for refined steps,
https://rook.io/docs/rook/v1.11/CRDs/Cluster/external-cluster/

**Comment by giuseppe-martinelli** [comment]
Here is requested command output:
```
root@ceph-1-n-000:~# ceph -s
  cluster:
    id:     21e95b90-06a9-11ee-ae0c-000c2947c76b
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum ceph-1-n-000,ceph-1-n-001,ceph-1-n-002 (age 12m)
    mgr: ceph-1-n-000.wtaxlb(active, since 2w), standbys: ceph-1-n-001.zciyzs
    osd: 4 osds: 4 up (since 2w), 4 in (since 2w)

  data:
    pools:   2 pools, 33 pgs
    objects: 187 objects, 279 MiB
    usage:   4.2 GiB used, 4.0 TiB / 4.0 TiB avail
    pgs:     33 active+clean


```

To configure external ceph cluster on rook I followed the document you mentioned:
https://rook.io/docs/rook/v1.11/CRDs/Cluster/external-cluster/

Rook is correctly configured in fact persistent volume are correctly claimed from the external Ceph server and assigned to pods/deployments

**Comment by parth-gr** [comment]
SO is there anything else we can help you on?

**Comment by giuseppe-martinelli** [comment]
On other installations, when Ceph cluster is deployed inside the cluster, everything works and connecting interactively to pod rook-ceph-tools I obtain ceph cluster infos (i.e. I can run ceph -s command).

As described in the linked bug, when I try to connect to the external Ceph cluster using rook-ceph-tools I cannot obtain external cluster info but if I run ceph -s command (for example) I obtain:

```
[I have no name!@rook-ceph-tools-5c76bc5fdc-5j4jd /]$ ceph -s
[errno 1] RADOS permission error (error connecting to the cluster)

```

In my expectations, if I connect interactively to rook-ceph-tools on a rook deployment connect against a remote Ceph cluster, I can operate to the remote Ceph cluster

**Comment by travisn** [comment]
What keyring are you using? The toolbox commands generally require the admin keyring.

**Comment by parth-gr** [comment]
@giuseppe-martinelli yaa there was some issue regarding just the toolbox, 

But it was not entertained yet as you can simply ssh to ceph cluster, if you want to operate ceph cluster.
Btw I hope with the documentation other things are working fine.
