### ISSUE TITLE
Operator will not find valid subnet when using Network Attachment with nested plugins

### ISSUE THREAD

**Issue by osnabrugge** [rook/rook#12357]
* Bug Report

**Deviation from expected behavior:**

**Expected behavior: Algorithm should be able to comb nested plugin format to retrieve subnet.

**How to reproduce it (minimal and precise):**
If you need to define a network attachment definition which calls for features not within SR-IOV directly such as setting the MTU, you need to define a nested plugin.  (Only way to set MTU using sriov plugin is with a nested plugin: https://github.com/k8snetworkplumbingwg/sriov-cni/issues/123#issuecomment-655546661)

**The following is a Network Attachment definition where you need to call both the SRIOV plugin and Tuning plugin to set the MTU**
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: storage-sriov-conf
  namespace: networking
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_netdevice
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "sriov",
          "vlan": 100,
          "spoofchk": "off",
          "trust": "on",
          "ipam": {
            "type": "whereabouts",
            "range": "192.168.10.0/24",
            "range_start": "192.168.10.100",
            "range_end": "192.168.10.199"
          }
        }, 
        {
          "type": "tuning",
          "mtu": 9000
        }
      ]
    }'

**The following is the same Network Attachment definition without nested plugin which functions, but is not able to set the MTU:**
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: storage-sriov-conf
  namespace: networking
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_netdevice
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "sriov",
      "vlan": 100,
      "spoofchk": "off",
      "trust": "on",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.10.0/24",
        "range_start": "192.168.10.100",
        "range_end": "192.168.10.199"
      }
    }'

I do not have the log file from the Operator as I needed to resolve the issue quickly and reverted to setting the MTU directly on the VFs to 9000 which is not ideal as other applications may need a lower MTU.  SRIOV will default the MTU to the already set MTU on the VF which means all my applications are using 9000 MTU.  The Operator simply refuses to proceed any further claiming there is no valid subnet which indicates that the algorithm being applied does not allow for searching within a nested plugin format for the network attachment.

**Comment by sp98** [comment]
@osnabrugge should it not be `plugins[0].ipam.**subnet**:192.168.10.0/24`  instead of ``plugins[0].ipam.**range**:192.168.10.0/24` that you have used?

**Comment by osnabrugge** [comment]
That doesn't make a difference. Before I switched to Sr-iov there was no need for nested formatting (and I had the exact same setup functioning for months) as we are dynamically getting the VF as required and will default to the PF MTU value.

The Sr-iov team decided not to include mtu as a configurable option and directed otherds to nest and include man an additional plug in that does allow you to define the mtu.  The problem is the rook operator's logic when validating isn't designed to handle nested plug in format.

I'd give logs, but I forgot to take them and I am rearchitecting so everything is down right now.  Once I restore I'll reproduce the issued and get some logs / screenshots
