### ISSUE TITLE
Support converting mons from hostpath to PVs, and vice versa

### ISSUE THREAD

**Issue by travisn** [rook/rook#12376]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Rook doesn't currently support that migration from mons using host path to using the PVs. With the following steps this would be possible with a code change:

1. Running cluster has mons backed by the dataDirHostPath
2. Update the cephcluster CR to use a volumeClaimTemplate
3. Rook will reconcile the mons. Existing mons should remain using the dataDirHostPath. (Requires the code change)
4. The mons need to be failed over to start using the PVs
   1. Existing mons will stay on the host path.
   2.New mons will use the volumeClaimTemplate
   3. Either Rook could do this automatically (as we implemented for submariner scenarios), or we could wait for the admin to fail them over
5. After the mons are all failed over the host path will no longer be used by mons

We already have this pattern for other scenarios like submariner, or converting to/from host networking (see #12369), but not implemented yet for converting to PVs.

**What is use case behind this feature:**
Environments may change and existing clusters may need to update whether to run the mons on hostpath or PVs.

**Comment by parth-gr** [comment]
Should we also have a similar migration for OSDS

**Comment by travisn** [comment]
> Should we also have a similar migration for OSDS

OSDs can be manually destroyed and migrated, it is too complex to try and automate. In any case, #12381 will be the needed OSD migration change.
