### ISSUE TITLE
Improve install/setup/usage docs

### ISSUE THREAD

**Issue by rimusz** [rook/rook#1237]
I find install/setup/use docs are bit confusing for new comers.
Would be nice to make it a bit more clear ones and better examples.

**Comment by rimusz** [comment]
E.g.
GKE use helm chart to install Rook
How to setup block/file/object storage 
How to use those storages with Kubernetes 
Clear short simple examples in one place

**Comment by kokhang** [comment]
@rimusz how would you organize the docs? There is quickstart docs for setting up the cluster in https://github.com/rook/rook/blob/master/Documentation/kubernetes.md#quickstart and also quick guide for setting up storage. For example: https://github.com/rook/rook/blob/master/Documentation/k8s-block.md.

Feel free to submit a PR in way to make the docs more organized.

**Comment by jbw976** [comment]
We recently reorganized the document structure on https://rook.io/docs/rook/master/ to make the setup flow easier to follow.  Let us know if there are specific changes that would still be required.  Thank you!
