### ISSUE TITLE
bucketName name collision results in deleted bucket

### ISSUE THREAD

**Issue by mitchese** [rook/rook#12389]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When specifying a bucketName in an OBC, there is no check if this bucketName is already taken. The OBC / OB is created and can reference an already-existing bucket.  Deleting the second OBC will delete the bucket for both OBCs. This has some security implications as well, as it allows any user authorized to create or delete a bucket to randomly delete others' buckets by knowing the bucketName. 

**Expected behavior:**

Creating an OBC with an existing bucketName should **either** error that the bucketName already exists and the OBC does not create an OB, **or** only delete a bucket once the last OBC referencing the bucket is deleted. 

**How to reproduce it (minimal and precise):**

First, create an OBC, and specify a bucketName:

```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: first-bucket
spec:
  bucketName: testbucket
  storageClassName: general-s3
```

Status: we have one OBC, one OB and one bucket.

Next, create a second OBC but reference the first bucketName:

```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: second-bucket
spec:
  bucketName: testbucket
  storageClassName: general-s3
```

Status: we have two OBCs, two OBs and one bucket. Using the credentials from second-bucket is denied access to the bucket (403). From the view of second-bucket, nothing is working / all access is denied. This is IMO desired, as otherwise anyone could create an OBC and then read data in any bucket. So far, everything appears to have worked correctly.

Next, Delete the OBC "second-bucket".

Expected: the second OBC/OB are deleted, but "testbucket" is left alone because it is still actively referenced by first-bucket OBC.

Actual: second-bucket OBC/OB are deleted, and testbucket is deleted.  Now "first-bucket" is referencing a non-existent bucket. Using first-buckets credentials, the bucket is entirely gone: 

```
$ s3cmd ls s3://testbucket
ERROR: Bucket 'testbucket' does not exist
ERROR: S3 error: 404 (NoSuchBucket)
$  s3cmd ls s3:// 
$
```

In this test, both first-bucket and second-bucket were created in the same namespace. You can create them in different namespaces and the result is the same.

**File(s) to submit**:

(none)

**Logs to submit**:

(none)

**Cluster Status to submit**:

(None)

**Environment**:
* OS: Ubuntu 20.04 / 22.04
* Kernel: 5.15.0-69-generic
* Cloud provider or hardware configuration: bare metal 
* Rook version (use `rook version` inside of a Rook Pod): tested against helm version 1.10.6 
* Storage backend version (e.g. for ceph do `ceph -v`): ceph 16.2.10 
* Kubernetes version (use `kubectl version`): 1.24
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubespray / selfhosted
* Storage backend status
```
$ ceph status
  cluster:
    id: 
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum j,m,n (age 7w)
    mgr: a(active, since 7w)
    mds: 2/2 daemons up, 2 hot standby
    osd: 60 osds: 60 up (since 7w), 60 in (since 10w)
    rgw: 6 daemons active (5 hosts, 2 zones)
 
  data:
    volumes: 2/2 healthy
```

**Comment by travisn** [comment]
@thotz @BlaineEXE This issue wouldn't affect COSI, right?

**Comment by thotz** [comment]
Yes @mitchese this is a day one bug in libbucket provisioner, currently only way is user need to careful. @travisn It should be handled properly by the COSI-controller AFAIR from spec discussion. But never test this scenario though

**Comment by mitchese** [comment]
While stale, IMO this is quite a big problem; Our RBAC rules prevent people from deleting things cross namespace, but this circumvents this for all obcs.  This could allow for a dev/test deleting a production bucket where they don't have access according to rbac.  We've worked around it with an OPA rule that nobody can set a bucketName for now, but it seems to me to be an issue that should be fixed.

**Comment by parth-gr** [comment]
It got closed ssems like it is same, @jiffin can you re-confirm as you mentioned it is different

**Comment by jiffin** [comment]
Hi,

    Why am I getting this email? Please cross check the mail address.

Regards
Jiffin Vincent

**Comment by parth-gr** [comment]
@thotz ^^

**Comment by thotz** [comment]
The fix is correct for this bug

**Comment by parth-gr** [comment]
okay thanks, closing as it is fixed https://github.com/rook/rook/pull/12804
