### ISSUE TITLE
External script should also create the resources

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12380]
**Is this a bug report or feature request?**
* Feature Request
External script should also create the resources

**What should the feature do:**

The python script that we have currently just look for the resources and validate them,
But we are thinking for more automated ways,
So as the script has all the access over ceph cluster Script should be itself br robust to also create the resources.

So for all the flags we pass on->

The pattern would be like this -> 1) Check if the resource exits if not exists then create them

Resources: Radosnamespace, Subvolumegroup, zone, zone groups, pools, etc

**What is use case behind this feature:**

**Environment**:

**Comment by parth-gr** [comment]
External Script: https://github.com/rook/rook/blob/master/deploy/examples/create-external-cluster-resources.py

**Comment by travisn** [comment]
To preserve backward compatibility, would a new flag be added such as `--create-resources`? By default, the resources would not be created unless that flag is passed.
