### ISSUE TITLE
csi-rbdplugin-provisioner  have crashloopbackoff

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#12394]
**Is this a bug report or feature request?**
we have 6 node cluster and we have used 3 workernodes as osd and one of the csi-rbdplugin-provisioner pod is in crashloopbackoff, due to this all application pods went error status. could you please tell me what is the reason.

what is fuctionality of csi-rbdplugin-provisioner in rook-ceph and what it will do ?

descrtiption for the csi-rbdplugin-procisioner pod
`vmauser@smaster1:~$ sudo kubectl describe po csi-rbdplugin-provisioner-84c7fb8d76-b44fq -n rook-ceph
Name:                 csi-rbdplugin-provisioner-84c7fb8d76-b44fq
Namespace:            rook-ceph
Priority:             1000000
Priority Class Name:  medium-priority
Node:                 sworker1/172.27.183.69
Start Time:           Sat, 17 Jun 2023 02:38:47 +0530
Labels:               app=csi-rbdplugin-provisioner
                      contains=csi-rbdplugin-metrics
                      pod-template-hash=84c7fb8d76
Annotations:          cni.projectcalico.org/containerID: c552ed4b7e1e0d540fd49848e067211d53972009ee3f694a60b78163bd8798b2
                      cni.projectcalico.org/podIP:
                      cni.projectcalico.org/podIPs:
Status:               Running
IP:
IPs:                  <none>
Controlled By:        ReplicaSet/csi-rbdplugin-provisioner-84c7fb8d76
Containers:
  csi-provisioner:
    Container ID:  docker://94e898394bfb3d188a3225b1c76c6a55046585d5178069fe380281be530dfbcd
    Image:         docker-registry.com/sig-storage/csi-provisioner:v3.0.0
    Image ID:      docker-pullable://docker-registry.com/sig-storage/csi-provisioner@sha256:bbae7cde811054f6a51060ba7a42d8bf2469b8c574abb50fec8b46c13e32541e
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=0
      --timeout=150s
      --retry-interval-start=500ms
      --leader-election=true
      --leader-election-namespace=rook-ceph
      --default-fstype=ext4
      --extra-create-metadata=true
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 16 Jun 2023 19:03:22 +0530
      Finished:     Fri, 16 Jun 2023 19:03:25 +0530
    Ready:          False
    Restart Count:  9
    Environment:
      ADDRESS:  unix:///csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bvfxb (ro)
  csi-resizer:
    Container ID:  docker://9d87f5a4961d81ba523b05f5731012d1f800f5dd33f50168de6e2a86cfd517b7
    Image:         docker-registry.com/sig-storage/csi-resizer:v1.3.0
    Image ID:      docker-pullable://docker-registry.com/sig-storage/csi-resizer@sha256:d2d2e429a0a87190ee73462698a02a08e555055246ad87ad979b464b999fedae
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=0
      --timeout=150s
      --leader-election
      --leader-election-namespace=rook-ceph
      --handle-volume-inuse-error=false
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 16 Jun 2023 19:03:23 +0530
      Finished:     Fri, 16 Jun 2023 19:03:25 +0530
    Ready:          False
    Restart Count:  9
    Environment:
      ADDRESS:  unix:///csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bvfxb (ro)
  csi-attacher:
    Container ID:  docker://1e7a840d9b3fa34522111447793d95f1a36efda5e6afcaddc481bf09f58c77c9
    Image:         docker-registry.com/sig-storage/csi-attacher:v3.3.0
    Image ID:      docker-pullable://docker-registry.com/sig-storage/csi-attacher@sha256:221c1c6930fb1cb93b57762a74ccb59194c4c74a63c0fd49309d1158d4f8c72c
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=0
      --timeout=150s
      --csi-address=$(ADDRESS)
      --leader-election=true
      --leader-election-namespace=rook-ceph
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 16 Jun 2023 19:03:23 +0530
      Finished:     Fri, 16 Jun 2023 19:03:25 +0530
    Ready:          False
    Restart Count:  9
    Environment:
      ADDRESS:  /csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bvfxb (ro)
  csi-snapshotter:
    Container ID:  docker://61c8c87b886522ea1881d19e858dac3e6e368410aa51aef2c205e290e1dbb868
    Image:         docker-registry.com/sig-storage/csi-snapshotter:v4.2.0
    Image ID:      docker-pullable://docker-registry.com/sig-storage/csi-snapshotter@sha256:551b9692943f915b5ee4b7274e3a918692a6175bb028f1f0236a38596c46cbe0
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=0
      --timeout=150s
      --leader-election=true
      --leader-election-namespace=rook-ceph
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 16 Jun 2023 19:03:23 +0530
      Finished:     Fri, 16 Jun 2023 19:03:25 +0530
    Ready:          False
    Restart Count:  9
    Environment:
      ADDRESS:  unix:///csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bvfxb (ro)
  csi-rbdplugin:
    Container ID:  docker://3c2ab1050c3c91a6dcaa06a4c1e3171570d89221a57d1e090633277ada800c12
    Image:         docker-registry.com/cephcsi/cephcsi:v3.4.0
    Image ID:      docker-pullable://docker-registry.com/cephcsi/cephcsi@sha256:19634b6ef9fc6df2902cf6ff0b3dbccc56a6663d0cbfd065da44ecd2f955d848
    Port:          <none>
    Host Port:     <none>
    Args:
      --nodeid=$(NODE_ID)
      --endpoint=$(CSI_ENDPOINT)
      --v=0
      --type=rbd
      --controllerserver=true
      --drivername=rook-ceph.rbd.csi.ceph.com
      --pidlimit=-1
      --metricsport=9090
      --metricspath=/metrics
      --enablegrpcmetrics=false
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 16 Jun 2023 19:03:24 +0530
      Finished:     Fri, 16 Jun 2023 19:03:25 +0530
    Ready:          False
    Restart Count:  9
    Environment:
      POD_IP:          (v1:status.podIP)
      NODE_ID:         (v1:spec.nodeName)
      POD_NAMESPACE:  rook-ceph (v1:metadata.namespace)
      CSI_ENDPOINT:   unix:///csi/csi-provisioner.sock
    Mounts:
      /csi from socket-dir (rw)
      /dev from host-dev (rw)
      /etc/ceph-csi-config/ from ceph-csi-configs (rw)
      /lib/modules from lib-modules (ro)
      /sys from host-sys (rw)
      /tmp/csi/keys from keys-tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bvfxb (ro)
  liveness-prometheus:
    Container ID:  docker://0ff39f7f1b0ce5efe0c5174740c8143c16228c237cbad6676456773186c03652
    Image:         docker-registry.com/cephcsi/cephcsi:v3.4.0
    Image ID:      docker-pullable://docker-registry.com/cephcsi/cephcsi@sha256:19634b6ef9fc6df2902cf6ff0b3dbccc56a6663d0cbfd065da44ecd2f955d848
    Port:          <none>
    Host Port:     <none>
    Args:
      --type=liveness
      --endpoint=$(CSI_ENDPOINT)
      --metricsport=9080
      --metricspath=/metrics
      --polltime=60s
      --timeout=3s
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 16 Jun 2023 19:03:24 +0530
      Finished:     Fri, 16 Jun 2023 19:03:25 +0530
    Ready:          False
    Restart Count:  9
    Environment:
      CSI_ENDPOINT:  unix:///csi/csi-provisioner.sock
      POD_IP:         (v1:status.podIP)
    Mounts:
      /csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bvfxb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  host-dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:
  host-sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  ceph-csi-configs:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      rook-ceph-csi-config
    ConfigMapOptional:  <nil>
    ConfigMapName:      rook-ceph-csi-mapping-config
    ConfigMapOptional:  <nil>
  keys-tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  kube-api-access-bvfxb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 60s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 60s
Events:
  Type     Reason                  Age                    From               Message
  ----     ------                  ----                   ----               -------
  Normal   Scheduled               <invalid>              default-scheduler  Successfully assigned rook-ceph/csi-rbdplugin-provisioner-84c7fb8d76-b44fq to sworker1
  Warning  FailedCreatePodSandBox  24m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "da70e61a4f9731daeedabdf6a35f3a461af9db68a2875f335ddb2bc419daaf0a" network for pod "csi-rbdplugin-provisioner-84c7fb8d76-b44fq": networkPlugin cni failed to set up pod "csi-rbdplugin-provisioner-84c7fb8d76-b44fq_rook-ceph" network: error getting ClusterInformation: Get "[https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default":](https://10.233.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default%22:) dial tcp 10.233.0.1:443: i/o timeout
  Normal   Pulled                  24m                    kubelet            Container image "docker-registry.com/sig-storage/csi-provisioner:v3.0.0" already present on machine
  Normal   Created                 24m                    kubelet            Created container csi-provisioner
  Normal   Started                 24m                    kubelet            Started container csi-provisioner
  Normal   Pulled                  24m                    kubelet            Container image "docker-registry.com/sig-storage/csi-resizer:v1.3.0" already present on machine
  Normal   Created                 24m                    kubelet            Created container csi-resizer
  Normal   Started                 24m                    kubelet            Started container csi-resizer
  Normal   Pulled                  24m                    kubelet            Container image "docker-registry.com/sig-storage/csi-attacher:v3.3.0" already present on machine
  Normal   Created                 24m                    kubelet            Created container csi-attacher
  Normal   Started                 24m                    kubelet            Started container csi-attacher
  Normal   Pulled                  24m                    kubelet            Container image "docker-registry.com/sig-storage/csi-snapshotter:v4.2.0" already present on machine
  Normal   Created                 24m                    kubelet            Created container csi-snapshotter
  Normal   Started                 24m                    kubelet            Started container liveness-prometheus
  Normal   Pulled                  24m                    kubelet            Container image "docker-registry.com/cephcsi/cephcsi:v3.4.0" already present on machine
  Normal   Created                 24m                    kubelet            Created container csi-rbdplugin
  Normal   Started                 24m                    kubelet            Started container csi-rbdplugin
  Normal   Pulled                  24m                    kubelet            Container image "docker-registry.com/cephcsi/cephcsi:v3.4.0" already present on machine
  Normal   Created                 24m                    kubelet            Created container liveness-prometheus
  Normal   Killing                 24m                    kubelet            Stopping container csi-provisioner
  Normal   Killing                 24m                    kubelet            Stopping container liveness-prometheus
  Normal   Killing                 24m                    kubelet            Stopping container csi-snapshotter
  Normal   Killing                 24m                    kubelet            Stopping container csi-rbdplugin
  Normal   Started                 24m                    kubelet            Started container csi-snapshotter
  Normal   SandboxChanged          4m49s (x745 over 24m)  kubelet            Pod sandbox changed, it will be killed and re-created.`
**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`): Linux master3 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: its vm's
* Rook version (use `rook version` inside of a Rook Pod): v1.8.1
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.7
* Kubernetes version (use `kubectl version`): v1.21.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
*rook@rook-ceph-tools-76598c54f4-8k2pm /]$ ceph status
  cluster:
    id:     f23a8ed5-6c7d-4ea6-ab81-6442e58f1683
    health: HEALTH_WARN
            8 stray daemon(s) not managed by cephadm
            3 stray host(s) with 8 daemon(s) not managed by cephadm

  services:
    mon: 3 daemons, quorum a,b,e (age 31h)
    mgr: a(active, since 3d)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 31h), 3 in (since 31h)

  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 19.29k objects, 2.5 GiB
    usage:   8.0 GiB used, 142 GiB / 150 GiB avail
    pgs:     65 active+clean

  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr

**Comment by vadlakiran** [comment]
@Team, could you please update on this ?

**Comment by parth-gr** [comment]
looks like a network error
```
Get "[https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default":](https://10.233.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default%22:) dial tcp 10.233.0.1:443: i/o timeout
```

Also share the operator logs
