### ISSUE TITLE
Need to print detail error, not clear for user.

### ISSUE THREAD

**Issue by zhucan** [rook/rook#12404]
https://github.com/rook/rook/blob/e9bd40c3478bcab21e3250117313517b4583cfa4/pkg/operator/ceph/cluster/nodedaemon/reconcile.go#L91

if the err is ""servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"",  the log message can not print it.

**Comment by parth-gr** [comment]
@zhucan So what it currently prints,

**Comment by zhucan** [comment]
no any errors print , only print "failed to delete service monitor for ceph exporter in namespace %q on node %q", but we don't know the details.

**Comment by parth-gr** [comment]
@zhucan is this you want https://github.com/rook/rook/pull/12468/files?

**Comment by zhucan** [comment]
I don't know if the upper call will print an error @parth-gr, need to test

**Comment by parth-gr** [comment]
So the error is already printed, update to master latest and see
```
logger.Debugf("failed to delete service monitor for ceph exporter in namespace %q on node %q. %v", ns, nodeName, err)
```

Now it will also throw an error

**Comment by travisn** [comment]
Does v1.11.9 already fix this? See [this comment](https://github.com/rook/rook/pull/12468#pullrequestreview-1515108918).

**Comment by travisn** [comment]
Since #12430, the error details are logged when it fails.
