### ISSUE TITLE
Dashboard cannot acces RGW due to Bug #56970 fix

### ISSUE THREAD

**Issue by sorinpepelea** [rook/rook#12413]
Due Bug #56970, in ceph/mgr/dashboard/services/rgw_client.py
line : 
      daemon.host = daemon_info['metadata']['hostname']
has been changed to :
      daemon.host = daemon_info['metadata']['hostname']
causing dashboard to fail in finding the RGW.
In kubernetes, dashboard pod will fail to resolve the IP of a container inside another POD, based on hostname declared in there.

So, any effort was put into solving the SSL issue by connecting to RGW using DNS name,still is to consider proper addressing the issue, like having certificates generated in the right way.
You should revert it back to IP. or ensure a way to override it when deployed in Docker/ K8s

**Comment by gaord** [comment]
this should be logged here: https://tracker.ceph.com/, for it is not a rook issue.
