### ISSUE TITLE
Impossible to join Slack at the moment

### ISSUE THREAD

**Issue by aknuds1** [rook/rook#1241]
For the moment, it's impossible to join the Rook [Slack workspace](https://rook-slackin.herokuapp.com/) - I get a page with the following error displayed:

> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details

**Comment by bassam** [comment]
@aknuds1 I'm on it. check back in a bit.

**Comment by bassam** [comment]
looks like the slack token expired. fixed.

**Comment by aknuds1** [comment]
Thanks!
