### ISSUE TITLE
In the Monitoring monitor, the definition of Lables is missing. 

### ISSUE THREAD

**Issue by pengln** [rook/rook#12438]
deploy/charts/library/templates/_recommended-labels.tpl

In the Monitoring monitor, the definition of Lables is missing. This prevents the release: prometheus tag from being added, which prevents prometheus from discovering the servicemonitor configuration

**Comment by travisn** [comment]
@pengln  The `Labels` is defined wherever `library.rook-ceph.labels` is included, so I'm not understanding the issue. Could you provide an example of the issue and what you see as the fix?

**Comment by pengln** [comment]
@travisn Include labels in the values of helm. I'm not familiar with writing helm, so I've mimicked an example, please forgive me. For example.
# in deploy/charts/rook-ceph/templates/servicemonitor.yaml 
..... from
metadata.
    name: csi-metrics
  namespace: {{ .Release.Namespace }}
  labels: {{- include "library.rook-ceph.labels" . | nindent 4 }}
...... to
metadata.
    name: csi-metrics
  namespace: {{ .Release.Namespace }}
     labels.
       {{- include "library.rook-ceph.labels" . | nindent 4 }}
  {{- if .values.monitoring.labels }}
       {{ toyaml .Values.monitoring.labels | nindent 4 }}
  {{- end }}

**Comment by travisn** [comment]
I see, this is specific to the service monitor that was just added recently with #12170. 
@jouve Could you follow up with a PR to allow adding the monitoring labels? Thanks!

**Comment by jouve** [comment]
if I understand correctly, you want a new value (`.Values.monitoring.labels`) to add additionnal labels to the servicemonitor ?

**Comment by pengln** [comment]
Yes, you're great, that's what it means. Other applications (e.g. nginx-ingress or rook-ceph) have a field like `labels` in their helm for the monitoring section (servicemonitor), which is used to add a custom label to the servicemonitor's labels, e.g. add. `release: prometheus`. This definition allows the servicemonitor to be discovered and loaded by prometheus.
