### ISSUE TITLE
Enable usage of host udev links.

### ISSUE THREAD

**Issue by cehoffman** [rook/rook#12431]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Allow usage of device names and links created from host udev rules. 

**What is use case behind this feature:**

While the `/dev/disk/by-path` and `/dev/disk/by-id` are stable, they don't help serviceability and more custom device naming can make setup and maintenance less error prone. I have seen something promising done in another project that has dynamic device discovery concerns. [This](https://github.com/balena-io-library/base-images/blob/28844485a91b1408ffc550faa3b59e64809bc453/scripts/assets/entry.sh) is their container entrypoint. I believe this in conjunction with mounting the host's udev rules would work. The location of udev rules though maybe isn't the same every where, on Talos it is `/usr/etc/udev/rules.d`.

Alternatively maybe mounting `/dev:/dev` would be sufficient, but that isn't something I've ever done.

A final middle ground solution is perhaps mounting a specific subdirectory of `/dev` like `/dev/rook-osds` and let the user populate all the symlinks into the directory with host udev rules and mount in the relevant OSD processing containers `/dev/rook-osds:/dev/rook-osds`.

**Environment**:

 Metal

**Comment by cehoffman** [comment]
Looking a bit more at the OSD prepare, I see that the inventory printout shows for the discovered devices that the property `DevLinks` has the host symlinks in it. Maybe it would be possible to setup a process by which the user specifies the desired symlink and the OSD containers recreate in the container for the device that has that DevLink from the inventory process. This would running udev daemon in the OSD containers which still preserving the symlink name from the host in OSD management.

**Comment by travisn** [comment]
DevLinks support should be there, as added in #4489 and a follow-up in #10486. Does specifying the `fullPath` for the device not pick up the symlink? If not, @satoru-takeuchi could you take a look?

**Comment by satoru-takeuchi** [comment]
@travisn sure.
