### ISSUE TITLE
Disconnecting one data zone cause crashing Ceph block pool in stretch cluster configuration.

### ISSUE THREAD

**Issue by sjevus** [rook/rook#12446]
**Is this a bug report or feature request?**
 Bug Report

**Deviation from expected behavior:**
After abrupt shutdown of one whole data zone Ceph Cluster cannot revive to normal state. PVC are not responding, new PVC cannot be created and block-pool doesnt' respond also.

**Expected behavior:**
Ceph cluster working with only one available data zone. 

**How to reproduce it (minimal and precise):**
Create stretch cluster as recommended in documentation using Rook Ceph v1.9.3, Ceph: Pacific v16.2.7, Kubernetes v1.23.15

1DC:
1. OSD - MON
2. OSD - MON
3. OSD
4. OSD

2DC:
1. OSD - MON
2. OSD - MON
3. OSD
4. OSD

3DC:
1. MON 

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
1:1 with https://github.com/rook/rook/blob/master/design/ceph/ceph-stretch-cluster.md

**Logs to submit**:

* Operator's logs, if necessary - operator doesnt log anything about
* Crashing pod(s) logs, if necessary - nothing crashing from pods level.

**Cluster Status to submit**:
HEALTH_WARN
50% pgs degraded

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 8.7
* Kernel (e.g. `uname -a`): Linux 4.18.0-425.13.1.e18_7.x86_64
* Cloud provider or hardware configuration:  6 vm masters + 8 physical machines (workers) + vm arbiter 
* Rook version (use `rook version` inside of a Rook Pod): Rook v1.9.3
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.7 Pacific stable
* Kubernetes version (use `kubectl version`): v1.23.15 
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_WARN

**Comment by travisn** [comment]
@sjevus 50% PGs degraded is expected while the dc is down. More details about the repro would help:
- Was this a test cluster or production?
- Was the dc shutdown from a power outage, network split, or other?
- When the dc comes back online does the cluster recover?
- Can applications in the remaining dc read or write data? This is what we expect to keep working. Reads/writes in the down dc are not expected to function.
- Can you test with a newer version of rook and ceph? There have been some fixes in ceph related to the handling of the dc being down. 

@kamoltat Pointers on available fixes for stretch in newer releases since v16.2.7?

**Comment by sjevus** [comment]
1. Production ready cluster with data and applications deployed.
2. Power outage/draining nodes/scaling OSDs to 0 (three options were tested). 
3. Cluster is recovering after nodes comes back online without any problem, it looks like switching to "degraded stretch cluster" doesnt work properly, I am unable to recreate any PV and block pool doesnt seems working, for example: before abrupt shutdown I am able to list block devices with rbd ls {poolname} but after this command, it doesn't work - it can be also seen (or unseen actually) in Ceph dashboard at "Pools" tab. 
4. No, applications are unable to use pvc but it does apply to each DC, even if I am turning off 2nd DC, applications from 1st DC cannot work with Ceph (probably block pool is dying). 
5. I am unable to test with newer version at this moment.

**Comment by travisn** [comment]
@sjevus 16.2.7 does not have the critical fixes necessary for stretch cluster, unfortunately. To use stretch clusters reliably you will need to upgrade to 17.2.6.
