### ISSUE TITLE
csi: drop checks for kube version 1.21 and below

### ISSUE THREAD

**Issue by Rakshith-R** [rook/rook#12443]
good time to drop this as minimum supported version in 1.21 https://rook.github.io/docs/rook/v1.11/Getting-Started/Prerequisites/prerequisites/#minimum-version

_Originally posted by @Madhu-1 in https://github.com/rook/rook/pull/12440#discussion_r1245122253_

**Comment by travisn** [comment]
The min version was already updated to 1.22 with #12392. We are not backporting this to 1.11. Unless you found some code that is leftover from 1.21 and earlier, this is already done.

**Comment by Madhu-1** [comment]
I apologize for referencing the released document. If the minimum supported version is 1.22, we need to remove some checks in csi spec.go and eliminate the code for handling csidriver betav1.

**Comment by travisn** [comment]
Shall we close this, and remove the csidriver betav1 and other obsolete code with #12441?
