### ISSUE TITLE
Improvements for Ceph COSI driver Integration

### ISSUE THREAD

**Issue by thotz** [rook/rook#12464]
**Is this a bug report or feature request?**
* TODOs need to be addressed for the ceph cosi driver integration with Rook

- [ ] Add more unit tests
- [ ] #13027
- [x] Create official image for ceph-cosi-driver
- [ ] #13024
- [x] Create users for each object store internally so that it can be added to Bucket Class
- [ ] #13026
- [ ] #13025
- [x]  Handle updates of cephcosidriver CRD and objectStore CRDs in cosi-controller

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
We really need to open separate issues for each of these work items, and provide more details for each item. Then it may be possible for others to work on them, and we can be clear about priority. 

>  Create official image for ceph-cosi-driver

This needs to be completed before we can merge the original PR, no need to track this separately.

>  Handle updates of cephcosidriver CRD and objectStore CRDs in cosi-controller

We don't already handle updates? This seems like a blocker if the CRs can't be updated, but I'm not clear from the brief description exactly what is needed.

**Comment by travisn** [comment]
@thotz Thoughts on opening separate issues as suggested [earlier](https://github.com/rook/rook/issues/12464#issuecomment-1622643810)? The keepalive label usually doesn't help fix things either because then the bot doesn't remind us about the stale issues.
