### ISSUE TITLE
Key Management System - Kubernetes Token Based Auth out of date.

### ISSUE THREAD

**Issue by tsteinholz** [rook/rook#12472]
The following documentation is out of date with Kubernetes v1.24

https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/key-management-system/#token-based-authentication

The documentation implied that a Secret is generated when a Service Account is created, however, this is no longer true in Kubernetes v1.24: https://www.linkedin.com/pulse/service-account-token-changes-kubernetes-version-124-shafeeque-aslam

Expected Behavior:

The documentation should include how to manually create a secret, or leverage some of the newer design patterns from the latest kubernetes version. Vault documentation here: https://developer.hashicorp.com/vault/docs/auth/kubernetes

**Comment by parth-gr** [comment]
still good to fix this
