### ISSUE TITLE
Use The EndpointSlice API instead of  Endpoints.

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12471]
**Is this a bug report or feature request?**
* Feature Request
The EndpointSlice API is the recommended replacement for Endpoints.

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by Nikhil-Ladha** [comment]
Hey, could you please elaborate the issue/feature in scope here?

**Comment by parth-gr** [comment]
The endpoint slice is introduced in recent version https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#endpointslice-resource
So updating the Endpoints https://kubernetes.io/docs/concepts/services-networking/service/#endpoints to endpoint slice
is kind of request

**Comment by Nikhil-Ladha** [comment]
Ack, but this would require an update to the `v0.27.4` version of the `k8s.io/api` library, I guess that's considered and we don't foresee any issues with that?

**Comment by sp98** [comment]
@parth-gr @Nikhil-Ladha Was there any previous discussion on why we need this for Rook that I  may have missed?
Based on what I read, endpointslices provide many advantages over endpoints when we number of endpoints and workloads are scaling. I don't see any scaling issues with Rook for which we want to use endpointSlices. For example, we don't recommend more than 1 rgwendpoint for an object store.

thoughts?

**Comment by parth-gr** [comment]
As per discussion we only use one endpoint per time,

So we won't merge the PR till it is really required.
@Nikhil-Ladha thanks for picking:)

**Comment by Nikhil-Ladha** [comment]
> As per discussion we only use one endpoint per time,
> 
> So we won't merge the PR till it is really required. @Nikhil-Ladha thanks for picking:)

No issues 🙂
