### ISSUE TITLE
Failed to reconcile CephCluster from failing to delete configmap from CmdReporter job

### ISSUE THREAD

**Issue by cld0815** [rook/rook#12482]
install by helm,  v1.11.7
try upgrade to v1.11.9

CephCluster Event:
failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed the ceph version check: failed to complete ceph version job: failed to run CmdReporter rook-ceph-detect-version successfully. failed to delete existing results ConfigMap rook-ceph-detect-version. failed to delete ConfigMap rook-ceph-detect-version. gave up waiting after 20 retries every 2ns seconds. <nil>

ceph-objectstore Event:
failed to reconcile CephObjectStore "rook-ceph/ceph-objectstore". failed to detect running and desired ceph version: failed to detect ceph image version: failed to complete ceph version job: failed to run CmdReporter ceph-object-controller-detect-version successfully. failed to delete existing results ConfigMap ceph-object-controller-detect-version. failed to delete ConfigMap ceph-object-controller-detect-version. gave up waiting after 20 retries every 2ns seconds. <nil>

operator log:
[rook-ceph-operator.log](https://github.com/rook/rook/files/11974040/rook-ceph-operator.log)

**Comment by parth-gr** [comment]
What did you followed for upgrade?

The delete api call is failing for you,
may be because of the network error while upgrading

Have you tried after that uprading?

And where you able to list pods?

**Comment by travisn** [comment]
@cld0815 The operator is failing to delete configmaps. Please check if you have created all the needed RBAC. Did you install with the helm chart? If so, the RBAC should not be a problem. Otherwise, try applying common.yaml again for the latest RBAC, and make sure you have the correct version of the manifest.

**Comment by cld0815** [comment]
@parth-gr 
my upgrade follow:
1. helm upgrade rook-ceph rook-release/rook-ceph
2. helm upgrade rook-ceph-cluster  rook-release/rook-ceph-cluster

after about 1 day, it seems upgrade success
![1689131073205](https://github.com/rook/rook/assets/30192550/a1be749d-c31d-4c1f-bb9e-dc3f88a8e9df)

**Comment by cld0815** [comment]
@travisn install and upgrade with the helm chart.

**Comment by cld0815** [comment]
When I upgraded the k8s version from 1.27.2 to 1.27.3, everything worked fine

**Comment by BlaineEXE** [comment]
In another report of this issue, I saw the behavior reported in this k8s bug, and if anyone else is experiencing this, I'm curious to know if the same is true for them: https://github.com/kubernetes/kubernetes/issues/105536

**Comment by pomland-94** [comment]
I have the same error, i installed the CLuster from the normal yaml files and everything works fine. Now i add some new nodes with hard disks and i get this error.
 
I re-apply the common.yaml but nothing happend.
 
```bash
[root::admingw-01]
~: kubectl --namespace rook-ceph get events
LAST SEEN   TYPE      REASON               OBJECT                                        MESSAGE
5m49s       Warning   ReconcileFailed      cephfilesystem/myfs                           failed to reconcile CephFilesystem "rook-ceph/myfs". failed to detect running and desired ceph version: failed to detect ceph image version: failed to complete ceph version job: failed to run CmdReporter ceph-file-controller-detect-version successfully. failed to run job. object is being deleted: jobs.batch "ceph-file-controller-detect-version" already exists
2m24s       Normal    ReconcileSucceeded   cephblockpool/replicapool                     successfully configured CephBlockPool "rook-ceph/replicapool"
18m         Normal    Pulling              pod/rook-ceph-mon-a-canary-744cc49fdc-dqgr7   Pulling image "rook/ceph:v1.13.5"
18m         Normal    Created              pod/rook-ceph-mon-a-canary-744cc49fdc-dqgr7   Created container mon
18m         Normal    Started              pod/rook-ceph-mon-a-canary-744cc49fdc-dqgr7   Started container mon
18m         Normal    Pulled               pod/rook-ceph-mon-a-canary-744cc49fdc-dqgr7   Successfully pulled image "rook/ceph:v1.13.5" in 783ms (783ms including waiting)
18m         Normal    Pulling              pod/rook-ceph-mon-b-canary-5b4446579d-vzb88   Pulling image "rook/ceph:v1.13.5"
18m         Normal    Created              pod/rook-ceph-mon-b-canary-5b4446579d-vzb88   Created container mon
18m         Normal    Started              pod/rook-ceph-mon-b-canary-5b4446579d-vzb88   Started container mon
18m         Normal    Pulled               pod/rook-ceph-mon-b-canary-5b4446579d-vzb88   Successfully pulled image "rook/ceph:v1.13.5" in 770ms (770ms including waiting)
18m         Normal    Pulling              pod/rook-ceph-mon-c-canary-596bb46c45-8wbxb   Pulling image "rook/ceph:v1.13.5"
18m         Normal    Pulled               pod/rook-ceph-mon-c-canary-596bb46c45-8wbxb   Successfully pulled image "rook/ceph:v1.13.5" in 782ms (782ms including waiting)
18m         Normal    Created              pod/rook-ceph-mon-c-canary-596bb46c45-8wbxb   Created container mon
18m         Normal    Started              pod/rook-ceph-mon-c-canary-596bb46c45-8wbxb   Started container mon
11m         Warning   ReconcileFailed      cephcluster/rook-ceph                         failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed the ceph version check: failed to complete ceph version job: failed to run CmdReporter rook-ceph-detect-version successfully. failed to delete existing results ConfigMap rook-ceph-detect-version. failed to delete ConfigMap rook-ceph-detect-version. gave up waiting after 20 retries every 2ns seconds. <nil>
[root::admingw-01]
~:
```
