### ISSUE TITLE
rook gets stuck reconciling when object storage claims and storage class are deleted at the same time

### ISSUE THREAD

**Issue by uhthomas** [rook/rook#12516]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I recently removed an application from a cluster and deleted both the object storage claim and the storage class at the same time. rook is now stuck reconciling.

https://github.com/uhthomas/automata/commit/0d6fc268c5b2c88d25b0089b8b87715ab838e54e

```
I0715 00:04:01.180452       1 controller.go:217]  "msg"="reconciling claim" "key"="mimir/mimir-blocks-bucket"
I0715 00:04:01.180512       1 helpers.go:107]  "msg"="getting claim for key" "key"="mimir/mimir-blocks-bucket"
I0715 00:04:01.187759       1 helpers.go:213]  "msg"="getting ObjectBucketClaim's StorageClass" "key"="mimir/mimir-blocks-bucket"
E0715 00:04:01.249825       1 controller.go:204] error syncing 'mimir/mimir-blocks-bucket': error getting StorageClass "rook-ceph-mimir-blocks-bucket": storageclasses.storage.k8s.io "rook-ceph-mimir-blocks-bucket" not found, requeuing
I0715 00:04:01.278729       1 controller.go:217]  "msg"="reconciling claim" "key"="mimir/mimir-ruler-bucket"
I0715 00:04:01.278783       1 helpers.go:107]  "msg"="getting claim for key" "key"="mimir/mimir-ruler-bucket"
I0715 00:04:01.350154       1 helpers.go:213]  "msg"="getting ObjectBucketClaim's StorageClass" "key"="mimir/mimir-ruler-bucket"
E0715 00:04:01.353837       1 controller.go:204] error syncing 'mimir/mimir-ruler-bucket': error getting StorageClass "rook-ceph-mimir-ruler-bucket": storageclasses.storage.k8s.io "rook-ceph-mimir-ruler-bucket" not found, requeuing
```

**Expected behavior:**

rook should not get stuck.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): `v1.11.8`
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
@uhthomas Did you find a workaround in order to delete the object store? If you create the storage class again, this should allow the deletion.

**Comment by uhthomas** [comment]
> @uhthomas Did you find a workaround in order to delete the object store? If you create the storage class again, this should allow the deletion.

Not yet. I'll try creating the storage class again and hope the operator recovers.

**Comment by uhthomas** [comment]
Recreating the storage class seems to have worked.

https://gist.github.com/uhthomas/0d86fa19b9c778e3f5ec028eb3617b96
