### ISSUE TITLE
unable to add new device with multiple OSDs

### ISSUE THREAD

**Issue by uhthomas** [rook/rook#12518]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I've added a new device to the ceph cluster with 2 OSDs.

https://github.com/uhthomas/automata/blob/83466606f1206d4425a6de0e7369945186c25552/k8s/unwind/rook_ceph/ceph_cluster_list.cue#L168-L172

The OSD prepare job fails: https://gist.github.com/uhthomas/dff8f117407cbcefbf662dbc226fe642

Then, the second time is succeeds and ignores the device because:

```sh
2023-07-15 23:51:00.693967 I | cephosd: skipping device "nvme0n1" because it contains a filesystem "LVM2_member"
```

**Expected behavior:**

rook should add the device with the OSDs.

**How to reproduce it (minimal and precise):**

Create a device with multiple OSDs.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.11.8
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by uhthomas** [comment]
I changed this back to a single OSD for the device and it worked fine (after an `sgdisk -Z`). I tried multiple times to zap the device before with multiple OSDs and it did not work.

**Comment by travisn** [comment]
Running multiple OSDs really isn't necessary anymore given some perf improvements over the past couple years in Ceph releases. Are you using at least Quincy now? (v17)

**Comment by uhthomas** [comment]
> Running multiple OSDs really isn't necessary anymore given some perf improvements over the past couple years in Ceph releases. Are you using at least Quincy now? (v17)

Ah, really? I always heard it was better to use multiple OSDs for NVMe devices.

I'm on `quay.io/ceph/ceph:v17.2.6`.
