### ISSUE TITLE
We have two  ParseMonEndpoints function

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12536]
**Is this a bug report or feature request?**
* Bug Report

We have two func ParseMonEndpoints(input string) map[string]*cephclient.MonInfo { functions, remove one f them

**Deviation from expected behavior:**

Code should not have duplication

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by henrydavies1** [comment]
Hello, can I pick this one up?

**Comment by parth-gr** [comment]
For sure use, and assign it to yourself.

By commenting https://github.com/rook/rook/issues/12344#issuecomment-1582660429

**Comment by henrydavies1** [comment]
Thanks

/assign
