### ISSUE TITLE
For external cluster some of the cm and secrets are duplicated

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12535]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The config map and secrets are getting duplicated in cluster and operator namespace. In latest upstream master

```
[rider@localhost rook]$ 
[rider@localhost rook]$ kubectl get cm -nrook-ceph
NAME                           DATA   AGE
kube-root-ca.crt               1      5d5h
rook-ceph-csi-config           1      5d5h
rook-ceph-csi-mapping-config   1      5d5h
rook-ceph-operator-config      31     5d5h
[rider@localhost rook]$ 
[rider@localhost rook]$ kubectl get cm -nrook-ceph-external
NAME                      DATA   AGE
kube-root-ca.crt          1      5d5h
rook-ceph-csi-config      1      5d5h
rook-ceph-mon-endpoints   5      5d5h
[rider@localhost rook]$ 
[rider@localhost rook]$ 
[rider@localhost rook]$ kubectl get secrets -nrook-ceph
NAME                                         TYPE                                  DATA   AGE
default-token-mgvxp                          kubernetes.io/service-account-token   3      5d5h
rook-ceph-cmd-reporter-token-t5bwg           kubernetes.io/service-account-token   3      5d5h
rook-ceph-mgr-token-ms2k5                    kubernetes.io/service-account-token   3      5d5h
rook-ceph-osd-token-rwqnw                    kubernetes.io/service-account-token   3      5d5h
rook-ceph-purge-osd-token-t7p5c              kubernetes.io/service-account-token   3      5d5h
rook-ceph-rgw-token-plwm2                    kubernetes.io/service-account-token   3      5d5h
rook-ceph-system-token-d9s6x                 kubernetes.io/service-account-token   3      5d5h
rook-csi-cephfs-plugin-sa-token-g4m9l        kubernetes.io/service-account-token   3      5d5h
rook-csi-cephfs-provisioner-sa-token-xrctk   kubernetes.io/service-account-token   3      5d5h
rook-csi-rbd-plugin-sa-token-rzdgb           kubernetes.io/service-account-token   3      5d5h
rook-csi-rbd-provisioner-sa-token-z64sd      kubernetes.io/service-account-token   3      5d5h
[rider@localhost rook]$ 
[rider@localhost rook]$ kubectl get secrets -nrook-ceph-external
NAME                                 TYPE                                  DATA   AGE
default-token-bv6xf                  kubernetes.io/service-account-token   3      5d5h
rook-ceph-cmd-reporter-token-fwwww   kubernetes.io/service-account-token   3      5d5h
rook-ceph-config                     kubernetes.io/rook                    2      5d5h
rook-ceph-mon                        kubernetes.io/rook                    6      5d5h
rook-csi-cephfs-node                 kubernetes.io/rook                    2      5d5h
rook-csi-cephfs-provisioner          kubernetes.io/rook                    2      5d5h
rook-csi-rbd-node                    kubernetes.io/rook                    2      5d5h
rook-csi-rbd-provisioner             kubernetes.io/rook                    2      5d5h
[rider@localhost rook]$ 

```

**Expected behavior:**

No dup[lication should exists

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
Which configmap specifically should not be duplicated? The `rook-ceph-csi-config` or another one? That configmap will be created in every namespace where there is a cephcluster. Are you sure there is not also a cephcluster CR in the `rook-ceph` namespace?

**Comment by parth-gr** [comment]
Yaa I have cephcluster in rook-ceph-external namespace only

```
[rider@localhost rook]$ kubectl get cephcluster -nrook-ceph
No resources found in rook-ceph namespace.
[rider@localhost rook]$ 
[rider@localhost rook]$ 
[rider@localhost rook]$ kubectl get cephcluster -nrook-ceph-external
NAME                 DATADIRHOSTPATH   MONCOUNT   AGE    PHASE       MESSAGE                                     HEALTH       EXTERNAL   FSID
rook-ceph-external                                5d9h   Connected   Failed to configure external ceph cluster   HEALTH_ERR   true       
[rider@localhost rook]$ 
```
