### ISSUE TITLE
CephObjectStore with disabled replication traffic should be added to Zone endpoints

### ISSUE THREAD

**Issue by polyedre** [rook/rook#12533]
* Bug Report

As previously reported in [this comment](https://github.com/rook/rook/issues/12272#issuecomment-1632770630) and [this PR](https://github.com/rook/rook/pull/12327#issuecomment-1637486526), it seems that when CephObjectStores have the option `disableMultisiteSyncTraffic` set to `true`, the operator should not add the CephObjectStore endpoint to the Zone endpoints.

We deployed two CephObjectStore as recommended when scaling the number of gateways (one CephObjectStore dedicated to running the replication threads, and the other gateways dedicated to serving user traffic). We noticed that this broke the replication. Modifying the Zone manually to only keep the endpoint of the CephObjectStore that run sync threads restarted the replication. 

I had a look at the code. It seems that the method `setMultisite` in `pkg/operator/ceph/object/objectstore.go` should not be called when `DisableMultisiteSyncTraffic` is set to `true`.

If stopping calling the line https://github.com/rook/rook/blob/647a4e3534a41015aae9bc3ed21e12b10a9f9192/pkg/operator/ceph/object/controller.go#L447 is okay to you, I could create a new PR. We may need a new unit test too.

**Comment by BlaineEXE** [comment]
Thanks @polyedre for following up. Please go ahead and open a PR for the fix.

**Comment by BlaineEXE** [comment]
FYI @alimaredia

**Comment by parth-gr** [comment]
Is this a blocking issue?
