### ISSUE TITLE
COSI driver should also run in arm64 architecture

### ISSUE THREAD

**Issue by travisn** [rook/rook#12547]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The COSI driver currently only runs on amd64. 

**Expected behavior:**
We also need images for arm64.

**How to reproduce it (minimal and precise):**

Attempt to test COSI on mac m1 (or any other arm64 machine).

**Comment by thotz** [comment]
Fixed by https://github.com/rook/rook/pull/12562 uses latest cosi-0.1.2 image which contains arm build
