### ISSUE TITLE
[kubelet root-dir changed] globalmount does not exist on node

### ISSUE THREAD

**Issue by axel7083** [rook/rook#12556]
## Environment 

- We have 4 workers node in a cluster on promise
- We have 3 OSDs on node `[2,3,4]`
- The nodes are deployed using `kubeadm`

For some reason, we had to migrate the kubelet root-dir from `/var/lib/kubelet/` to `/mnt/{disk}/kubelet` on the **[node 2]**. 

> To ensure stability we create a symlink at `/var/lib/kubelet` pointing to our new directory. Only the [node 2] had a change. The other kept the default value `/var/lib/kubelet`.

Everything is running fine on this node except no volume can be mounted on this node. The others are fine.

## Logs

On any pod with a volume that should be mount the following error is put in the events:

> MountVolume.MountDevice failed for volume "pvc-{uuid}" : rpc error: code = InvalidArgument desc = staging path /mnt/{disk}/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/{hash-value}/globalmount does not exist on node
> **Source: kubelet node2**

On the node 2 machine, the directory `/mnt/{disk}/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/` exist but is empty.

## What I tried

I cannot change the `ROOK_CSI_KUBELET_DIR_PATH` value since, only one node has the kubelet at a different location.

### remove the OSD on node 2

- drain the node 
- Removing the device node-2 in the `CephCluster` file (to keep only node-3 and node-4)
- Deleting `/var/lib/rook` folder completely 
- sgdisk the partition used by the OSD on node-2
- dd if=/dev/zero... the OSD on node-2 
- using toolbox to `ceph auth del osd.2`

### kubeadm reset the node-2

- drain the node
- remove the node from the cluster
- on node-2 `kubeadm reset`

Whatever I reconfigured the node-2, I always get the `/mnt/{disk}/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/.../globalmount does not exist on node`...

**Environment**:
* OS (e.g. from /etc/os-release):
> NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
* Kernel (e.g. `uname -a`):
> Linux node-2 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
> rook: v1.11.9
go: go1.19.10
* Storage backend version (e.g. for ceph do `ceph -v`):
> ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367)
* Kubernetes version (use `kubectl version`):
> Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.8", GitCommit:"0ce7342c984110dfc93657d64df5dc3b2c0d1fe9", GitTreeState:"clean", BuildDate:"2023-03-15T13:39:54Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
> On premise (kubeadm)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): 
> HEALTH_WARN mon a is low on available space; Degraded data redundancy: 565922/2514814 objects degraded (22.504%), 20 pgs degraded, 20 pgs undersized;

#### csi-cephfsplugin-* running on node-2

Repeating the following line:
> E0719 09:25:13.613581       1 utils.go:210] ID: 138 Req-ID: 0001-0009-rook-ceph-0000000000000001-922b458c-b13b-487d-8509-2ee928d83806 GRPC error: rpc error: code = InvalidArgument desc = staging path /mnt/{disk}/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/{some hash}/globalmount does not exist on node

## Edit 2

I restore the original root-dir of kubelet. This solution is **very not** ideal, making our cluster potentially unstable, however, it is better than not having PVC.

From what I understand the  `ROOK_CSI_KUBELET_DIR_PATH`  is general to all nodes, without letting people be able to let customize this for each node. Probably a possible improvement.

**Comment by subhamkrai** [comment]
^^@Madhu-1 @Rakshith-R thoughts?

**Comment by Rakshith-R** [comment]
>I restore the original root-dir of kubelet. This solution is very not ideal, making our cluster potentially unstable, however, it is better than not having PVC.
>From what I understand the ROOK_CSI_KUBELET_DIR_PATH is general to all nodes, without letting people be able to let customize this for each node. Probably a possible improvement.

@axel7083
It is a requirement that the kublet dir is exactly same for all node of a kubernetes cluster. 
The defective node needs to be configured similar to other nodes.

**Comment by axel7083** [comment]
> > I restore the original root-dir of kubelet. This solution is very not ideal, making our cluster potentially unstable, however, it is better than not having PVC.
> > From what I understand the ROOK_CSI_KUBELET_DIR_PATH is general to all nodes, without letting people be able to let customize this for each node. Probably a possible improvement.
> 
> @axel7083 It is a requirement that the kublet dir is exactly same for all node of a kubernetes cluster. The defective node needs to be configured similar to other nodes.

Alright, this is not documented, or not clearly said enough I think.

**Comment by Rakshith-R** [comment]
> > 
> > @axel7083 It is a requirement that the kublet dir is exactly same for all node of a kubernetes cluster. The defective node needs to be configured similar to other nodes.
> 
> Alright, this is not documented, or not clearly said enough I think.

It's a rare case that this change is required and if ever required it is meant for all the nodes in the cluster.

https://github.com/rook/rook/blob/cb44c7b88fb346f3b120e8bda769ac808ec60880/deploy/examples/operator.yaml#L140

Such discrepancies in nodes of a cluster may have other unknown consequences too.
