### ISSUE TITLE
Ceph Cluster Health "HEALTH_WARN"

### ISSUE THREAD

**Issue by snehal1797** [rook/rook#12573]
Deviation from expected behavior:
Cluster is deployed successfully but Ceph health status reported as "HEALTH_WARN"

Expected behavior:
Ceph health status should be reported as "HEALTH_OK"

I have deployed a dualstack rook ceph cluster.

Enable dualstack in ceph cluster spec:
`network:`
 `   dualStack: true`

Cluster is deployed via helm charts

Describe ceph cluster output
`NAME        DATADIRHOSTPATH   MONCOUNT   AGE    PHASE   MESSAGE                        HEALTH        EXTERNAL
rook-ceph   /var/lib/rook     3          4d2h   Ready   Cluster created successfully   HEALTH_WARN
`

**All rook-ceph components are up and running**

`
> NAME                                               READY   STATUS      RESTARTS        AGE
> csi-cephfsplugin-f6647                             3/3     Running     0               4d2h
> csi-cephfsplugin-lqlns                             3/3     Running     0               4d2h
> csi-cephfsplugin-provisioner-5fc7f9f9d9-jkmvm      5/5     Running     0               4d2h
> csi-cephfsplugin-provisioner-5fc7f9f9d9-mhfts      5/5     Running     0               4d2h
> rook-ceph-mds-ceph-filesystem-a-6d6f5b97bc-8nvdn   1/1     Running     0               4d2h
> rook-ceph-mds-ceph-filesystem-b-d66d584c7-hg47n    1/1     Running     0               4d2h
> rook-ceph-mgr-a-6df7f86f97-nhwrb                   2/2     Running     3 (4h31m ago)   3d19h
> rook-ceph-mon-a-78fc777798-lbfdt                   1/1     Running     0               4d2h
> rook-ceph-mon-b-78d477ccc-6nhdf                    1/1     Running     0               4d2h
> rook-ceph-mon-c-6686b698fb-vtdzc                   1/1     Running     0               4d2h
> rook-ceph-operator-74c749685-66jnz                 1/1     Running     0               4d2h
> rook-ceph-osd-0-6bb6879c58-wv442                   1/1     Running     0               4d2h
> rook-ceph-osd-1-6ff988756b-smfzd                   1/1     Running     0               4d2h
> rook-ceph-osd-2-86c7f85bbf-nb2ll                   1/1     Running     0               4d2h
> rook-ceph-osd-prepare-srel41anrt1rceph001-b7rpz    0/1     Completed   0               4d
> rook-ceph-osd-prepare-srel41anrt1rceph002-nrmx5    0/1     Completed   0               4d
> rook-ceph-osd-prepare-srel41anrt1rceph003-4xt54    0/1     Completed   0               4d
> rook-ceph-tools-599d44c659-s4642                   1/1     Running     0               4d2h
> rook-discover-4mbcs                                1/1     Running     0               4d2h
> rook-discover-dd977                                1/1     Running     0               4d2h
> rook-discover-vxlb6                                1/1     Running     0               4d2h

`

**Cluster Health Status**:
sh-4.4$ ceph -s
  cluster:
    id:     xxxx
    health: HEALTH_WARN
            Reduced data availability: 97 pgs inactive

  services:
    mon: 3 daemons, quorum a,b,c (age 4d)
    mgr: a(active, since 4h)
    mds: 1/1 daemons up, 1 standby
    osd: 3 osds: 3 up (since 4d), 3 in (since 4d)

  data:
    volumes: 1/1 healthy
    pools:   4 pools, 97 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             97 unknown

Mgr, OSD, Mon (ms-bind-ipv4 and ms-bind-ipv6  is set to true)

Public cidr is updated with ipv4 and ipv6 network.

Mgr pod logs:

`debug 2023-07-24T13:30:40.265+0000 7f55a733d700  0 log_channel(cluster) log [DBG] : pgmap v7909: 97 pgs: 97 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2023-07-24T13:30:42.265+0000 7f55a733d700  0 log_channel(cluster) log [DBG] : pgmap v7910: 97 pgs: 97 unknown; 0 B data, 0 B used, 0 B / 0 B avail
`

Expected behaviour:

Ceph Cluster status should be "**HEALTH_OK"**

**Comment by parth-gr** [comment]
Dual stack with IPV6 is not supported you can only use IPV4 with dual stack and if you want IPV6 then only use IPV6 cluster,

cc @sp98

**Comment by sp98** [comment]
@snehal1797 What's the rook and ceph version that you are using?  
Can you share Pod CIDRs of any of the OSD pod ?

**Comment by arun-n2020** [comment]
Another info:
we have jumbo frames "MTU 9000" for the n/w interface hosting the cluster cidr where we are seeing this issue.

**Comment by snehal1797** [comment]
One more observation:

Mgr process are listening on ipv4 as well as ipv6 addresses, but ipv6 is loopback address also ports are different for for ipv4 and ipv6.



```
tcp        0      0 10.225.x.x:6810      0.0.0.0:*               LISTEN      162xx/ceph-mgr
tcp        0      0 10.225.x.x:6811      0.0.0.0:*               LISTEN      162xx/ceph-mgr
tcp6       0      0 :::6808                 :::*                    LISTEN      162xx/ceph-mgr
tcp6       0      0 :::6809                 :::*                    LISTEN      162xx/ceph-mgr
tcp6       0      0 :::9283                 :::*                    LISTEN      162xx/ceph-mgr
```


Mon process are listening only on ipv4 address.

```
tcp        0      0 10.225.x.x:3300      0.0.0.0:*               LISTEN      150xx/ceph-mon
tcp        0      0 10.225.x.x:6789      0.0.0.0:*               LISTEN      150xx/ceph-mon

```

@sp98 Is this the expected behavior in case of dualstack rook ceph cluster?

**Comment by sp98** [comment]
@snehal1797 I'm not really sure. I'll check and get back to you on this.

**Comment by SkalaNetworks** [comment]
Hi, @sp98, do you remember if something was done about it? I got the exact same problems, switching on DualStack renders the cluster inoperable for the same reasons.

I don't understand the point of the dualStack option if the cluster still only works over IPv4? (switching the option on actually makes the cluster entirely useless as all the pgs go down).

Something doesn't seem to be clear for me, quoting @parth-gr : 
 > Dual stack with IPV6 is not supported you can only use IPV4 with dual stack and if you want IPV6 then only use IPV6 cluster

What does it mean to have "dual stack with ipv6 not supported" ?
