### ISSUE TITLE
Multiple CI runs are failing

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#12580]
**Is this a bug report or feature request?**
* Bug Report

Creating a single issue to mention what all the tests are failing in CI, difficult to create individual issues since sometimes errors are different or ci is flaky. Also, I'm a little lazy to create a create 6 or 7 different issues and copy the errors from CI and paste 😅 

1.  Upgrade Suite

- [x]     For k8s 1.27.x pr #12578 will fix
- [x]    For k8s 1.22.x individual tests are passing but overall tests are failing because the mgr pod is restarting once

2. Smoke Suite
- [x]     For k8s 1.27x only failure do 3 or 4 different issues I noticed when I was trying to look

3. Object Suite
- [ ]     For k8s 1.27.x only (Not looked at the issues)

4. Multiple Canary tests are flaky at least 3 tests are frequent
- [x]    Canary/Canary
- [x]     Canary/encryption
- [x]     Canary/lvm
- [x]     Canary/raw-disk
- [x]     Canary/Mutli-mirroring
- [ ]     Canary/Multus
Some of them are not failing frequently but better to track.

**Deviation from expected behavior:**

Multiple CIs are failing

**Expected behavior:**

All the CIs should be green

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by subhamkrai** [comment]
FYI, most of the canary test(I think apart from `multi-mirroring`and `multus`) are failing because osd are not coming for ceph is not ready.

**Comment by parth-gr** [comment]
`Canary/Canary ` is, not that intermittent it fails sometimes if the cluster creation process fais

**Comment by subhamkrai** [comment]
This pr https://github.com/rook/rook/pull/12634 will probably fix all the canary ci issues

**Comment by subhamkrai** [comment]
Closing the bigger issue since we have fewer CI issues for which we can open separate issues. Thanks
