### ISSUE TITLE
 update the rook-ceph-mon-endpoints with the csi-config-map 

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12595]
**Is this a bug report or feature request?**
* Bug Report

This is where where we update the cluster-info and that clusterinfo is used by csi-config
https://github.com/rook/rook/blob/cb44c7b88fb346f3b120e8bda769ac808ec60880/pkg/operator/ceph/controller/cluster_info.go#L277
So strongly believe now we should definitely update the rook-ceph-mon-endpoints with the csi-config-map whenever we do v2 port updation, 
https://github.com/rook/rook/blob/cb44c7b88fb346f3b120e8bda769ac808ec60880/pkg/operator/ceph/csi/cluster_config.go#L105
@travisn

_Originally posted by @parth-gr in https://github.com/rook/rook/issues/12537#issuecomment-1646046194_
       

**Deviation from expected behavior:**

The rook ceph mon endpoint config map contains a older data 
```
[rider@localhost rook]$ kubectl get cm rook-ceph-mon-endpoints -nrook-ceph-external -o yaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph-external","monitors":["10.1.115.103:6789","10.1.115.104:3300","10.1.115.107:6789"],"namespace":""}]'
  data: rhcs-1-node-1=10.1.115.104:3300,rhcs-1-node-2=10.1.115.107:6789,rhcs-1-node-3=10.1.115.103:6789
  mapping: '{"node":{}}'
  maxMonId: "2"
  outOfQuorum: ""
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-19T14:47:18Z"
  finalizers:
  - ceph.rook.io/disaster-protection
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph-external
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CephCluster
    name: rook-ceph-external
    uid: 40ad87d1-c917-47bd-b7bd-cc582096c0b7
  resourceVersion: "145626"
  uid: af6de956-177a-4828-b5cf-b2b112a7de6c
```

But the csi configmap is updated with the  PR changes, https://github.com/rook/rook/pull/12537

```
[rider@localhost rook]$ kubectl get cm rook-ceph-csi-config -nrook-ceph -o yaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph-external","monitors":["10.1.115.104:3300","10.1.115.107:3300","10.1.115.103:3300"],"namespace":"rook-ceph-external"}]'
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-13T09:26:12Z"
  name: rook-ceph-csi-config
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: false
    controller: true
    kind: Deployment
    name: rook-ceph-operator
    uid: fe2c873a-252b-4c98-859f-69983d41c67c
  resourceVersion: "309558"
  uid: ed0b2736-e111-48e7-8dc8-f34456162d19
[rider@localhost rook]$ 

```

**Expected behavior:**

Both the configmap should have the same data, as they both are interconnected

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment]
Checked in a fresh cluster on internal mode data is fine 

```
[rider@localhost Downloads]$ oc get cm rook-ceph-csi-config -nopenshift-storage -o yaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"openshift-storage","monitors":["172.30.14.58:3300","172.30.82.234:3300","172.30.235.82:3300"],"namespace":"openshift-storage"}]'
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-23T09:44:32Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:csi-cluster-config-json: {}
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"6b5ae570-e1d2-48ce-9f83-a06f1fa49a0c"}: {}
    manager: rook
    operation: Update
    time: "2023-07-26T11:40:47Z"
  name: rook-ceph-csi-config
  namespace: openshift-storage
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: false
    controller: true
    kind: Deployment
    name: rook-ceph-operator
    uid: 6b5ae570-e1d2-48ce-9f83-a06f1fa49a0c
  resourceVersion: "2462970"
  uid: 2958ffb2-01a8-490b-a855-a58e3fabad4f
[rider@localhost Downloads]$ oc get cm rook-ceph-mon-endpoints -nopenshift-storage -o yaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"openshift-storage","monitors":["172.30.14.58:3300","172.30.82.234:3300","172.30.235.82:3300"],"namespace":""}]'
  data: f=172.30.235.82:3300,d=172.30.14.58:3300,c=172.30.82.234:3300
  mapping: '{"node":{"c":null,"d":null,"f":null}}'
  maxMonId: "5"
  outOfQuorum: ""
kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-23T09:44:39Z"
  finalizers:
  - ceph.rook.io/disaster-protection
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:csi-cluster-config-json: {}
        f:data: {}
        f:mapping: {}
        f:maxMonId: {}
        f:outOfQuorum: {}
      f:metadata:
        f:finalizers:
          .: {}
          v:"ceph.rook.io/disaster-protection": {}
        f:ownerReferences:
          .: {}
          k:{"uid":"a1470db5-8f46-4b8f-85dd-07e0511d6639"}: {}
    manager: rook
    operation: Update
    time: "2023-07-26T13:55:39Z"
  name: rook-ceph-mon-endpoints
  namespace: openshift-storage
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CephCluster
    name: ocs-storagecluster-cephcluster
    uid: a1470db5-8f46-4b8f-85dd-07e0511d6639
  resourceVersion: "2530743"
  uid: 461954be-763b-4340-9eae-9c657c0c3f05
[rider@localhost Downloads]$ 


```


But it will mostly happen with upgrade, I will check that

**Comment by Madhu-1** [comment]
>csi-cluster-config-json

can be removed from the mon configmap AFAIK no one is using it and its a duplicate data

**Comment by parth-gr** [comment]
Okay thanks for that info, make sense
