### ISSUE TITLE
I'd like a command-line way to learn about monitors

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#126]
I'd like a command-line way to learn about the monitors in a cluster (where [ip, hostname], how many, health, other stats).  I'm thinking about something that works like the "node ls" command.

Perhaps "rook monitor ls" or just "rook monitors".

**Comment by jbw976** [comment]
The `rook status` command output should give you the information needed about monitors.  However, there's still the longer term UX discussion to be had on how we can meet our goal of abstracting ceph concepts out of the rook experience entirely.

**Comment by DanKerns** [comment]
I think what’s done is sufficient here for now.  Issue #212 seems more relevant.
