### ISSUE TITLE
Implement a Declarative Mechanism For Defining NFS Exports

### ISSUE THREAD

**Issue by dpeckett** [rook/rook#12621]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Either by a new resource or by additional fields on CephNFS we should have a declarative mechanism for defining NFS exports.

**What is use case behind this feature:**

Right now you have to jump into the toolbox and create the exports manually, obviously this isn't great. I open this feature request to just get a discussion going and keep track of this.

**Comment by Rakshith-R** [comment]
@dpeckett Have checked this doc ? 
NFS exports can be created like a similar already.

https://github.com/rook/rook/blob/52c9cfea9fe3c7e30f044040d468399f008379d5/Documentation/Storage-Configuration/NFS/nfs-csi-driver.md#creating-nfs-exports-via-pvc

**Comment by dpeckett** [comment]
Thanks! That was definitely an oversight on my part. We should perhaps move that out of the CSI driver section as I glossed over that, and I'm sure others will (because I'm not planning on having pods talking to storage over NFS).

**Comment by Rakshith-R** [comment]
There is a link pointing to that csi section in the main nfs.md ~

https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/NFS/nfs.md#ceph-csi-nfs-provisioner-and-nfs-csi-driver
