### ISSUE TITLE
Allow for MaxUnavailable for cephfs csi daemonset

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rook/rook#12636]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Allow me to specify max unavailable for cephfs just as rbd https://github.com/rook/rook/blob/c86fce80eac4801a0cf83f3f3f780e4f059322ed/pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml#L10-L11

**What is use case behind this feature:**
Environment with a large number of nodes and maxUnavailable of 1 never finishes updating.

**Comment by karthik-us** [comment]
@ADustyOldMuffin thanks for reporting this issue. Let me work on it.
