### ISSUE TITLE
CI:  mgr pod restarting once when upgrade to reef in CI

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#12646]
**Is this a bug report or feature request?**
* Bug Report

In ci, when mgr pod is upgraded to reef it is restarting exactly once in upgrade suite 1.22.x due to which ci is failing during teardown

https://github.com/rook/rook/actions/runs/5735701671/job/15543888482?pr=12608

```
2023-08-02 07:23:07.568019 I | testutil: number of time pod rook-ceph-mgr-a-64469797d9-tpwk4 has restarted is 1
=== NAME  TestCephUpgradeSuite
    k8s_helper.go:469: 
        	Error Trace:	/home/runner/work/rook/rook/tests/framework/utils/k8s_helper.go:469
        	            				/home/runner/work/rook/rook/tests/framework/installer/ceph_installer.go:643
        	            				/home/runner/work/rook/rook/tests/framework/installer/ceph_installer.go:633
        	            				/home/runner/work/rook/rook/tests/integration/ceph_upgrade_test.go:76
        	            				/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:205
        	            				/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:216
        	            				/home/runner/work/rook/rook/tests/integration/ceph_upgrade_test.go:59
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 1
        	Test:       	TestCephUpgradeSuite
```

```
 FAIL: TestCephUpgradeSuite (875.68s)
    --- PASS: TestCephUpgradeSuite/TestUpgradeRook (871.93s)
        --- PASS: TestCephUpgradeSuite/TestUpgradeRook/create_CephObjectStore (35.99s)
        --- PASS: TestCephUpgradeSuite/TestUpgradeRook/wait_for_RGWs_to_be_running (40.10s)
        --- PASS: TestCephUpgradeSuite/TestUpgradeRook/verify_object_store_status (25.02s)
        --- PASS: TestCephUpgradeSuite/TestUpgradeRook/verify_RGW_liveness_probes_show_healthy (0.00s)
        --- PASS: TestCephUpgradeSuite/TestUpgradeRook/verify_RGW_service_is_up (0.00s)
        --- PASS: TestCephUpgradeSuite/TestUpgradeRook/check_if_the_dashboard-admin_user_exists_in_all_existing_object_stores (0.63s)
```

**Deviation from expected behavior:**
Upgrade suite 1.22.x is failing

**Expected behavior:**
Upgrade suite 1.22.x should be passing

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by rkachach** [comment]
@subhamkrai @travisn I'd like to take care of this issue but TBH I'm not sure what's wrong and what should be fixed.
