### ISSUE TITLE
CSI holder pods are not deleted when all ceph clusters are deleted.

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#12645]
**Is this a bug report or feature request?**
* Bug Report

CSI Holder daemon sets are not deleted like the csi daemonset when a ceph cluster is deleted. This happens only when CSI is deployed with pod networkk/multus network

**Deviation from expected behavior:**

CSI Holder daemon sets are not deleted like the csi daemonset when a ceph cluster is deleted.

**Expected behavior:**

CSI Holder daemonset should also get deleted like other csi daemon set.

**How to reproduce it (minimal and precise):**

* Deploy Rook and create ceph cluster with multus
* Delete ceph cluster
* Check kubectl get pod output

**Comment by Madhu-1** [comment]
@travisn should we also delete csi holder pod just like other csi pods? and also i think we are missing the holder pod here as well https://github.com/rook/rook/blob/10a4aa716456803ecc841adeaee7280651f2a82d/pkg/operator/ceph/cluster/cephstatus.go#L315-L326, should we consider holder pod for this case as well or we just leave it as its a special case.

Need some discussion about these 2.

**Comment by travisn** [comment]
> what volumes we are talking about here? Holder pod mounts only one Host mount

That confirms my question that it has a volume. So yes, let's add it to the list of pods.

**Comment by Madhu-1** [comment]
@travisn I send #12681 to fix the delete stuck pod problem, I think we cannot handle holder daemonset deletion as a straightforward case as holder daemon sets are created per ceph cluster. we need to block ceph cluster deletion until the holder daemon sets are deleted and holder daemonset cannot be deleted if we have any application still using the PVC as holder pods are still holding the mounts.

Can we try below

* Add Holder pod as dependent to ceph cluster  by adding it to `cephClusterDependentListKinds`
* Before deleting the holder pod check all other dependents are deleted
* Delete the holder pods at last
* Delete the ceph cluster

@travisn @BlaineEXE  any suggestion?

**Comment by travisn** [comment]
Ceph cluster deletion is already blocked if there are any PVs still existing in the cluster. So I believe that case is already covered, and no need to block the cephcluster CR based on the existence of the holder daemonsets.

**Comment by Madhu-1** [comment]
> Ceph cluster deletion is already blocked if there are any PVs still existing in the cluster. So I believe that case is already covered, and no need to block the cephcluster CR based on the existence of the holder daemonsets.

ceph cluster deletion is blocked until the dependencies like blockpool, filesystem, etc are deleted and they are blocked until PV's are deleted, this is my understanding not sure it's correct. if we end up deleting the holder pods before deleting the blockpool or filesystem we might not be able to umount the application pods and in turn it can block the deleting the blockpool or filesystem.

**Comment by travisn** [comment]
> > Ceph cluster deletion is already blocked if there are any PVs still existing in the cluster. So I believe that case is already covered, and no need to block the cephcluster CR based on the existence of the holder daemonsets.
> 
> ceph cluster deletion is blocked until the dependencies like blockpool, filesystem, etc are deleted and they are blocked until PV's are deleted, this is my understanding not sure it's correct. if we end up deleting the holder pods before deleting the blockpool or filesystem we might not be able to umount the application pods and in turn it can block the deleting the blockpool or filesystem.

Right, since we have these finalizer dependencies, the holder pods should not be deleted prematurely.

**Comment by Madhu-1** [comment]
As discussed we can set the ceph cluster as the owner ref for the holder pod daemonset for proper cleanup.
