### ISSUE TITLE
Ability to export SMART metrics from devices?

### ISSUE THREAD

**Issue by evanrich** [rook/rook#12652]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**  Prometheus exporter already contains a plethora of metrics, however SMART info about connected drives is not exported.   While SMART data is available in the rook-ceph dashboard, it does not seem to get exported via the metrics endpoint.

**What is use case behind this feature:**   There are smartmontools exporters as well as various other exporters that collect SMART info.  being able to export key metrics such as SSD life remaining, TBW, POH (power on hours) etc would be key in being able to predict when drives might fail.  

**Environment**:

**Comment by richardelling** [comment]
prometheus collectors like node_exporter intentionally run as a non-root user. But in general, root access is required to read smart data directly from the drives. So in the prometheus world, folks use a root cronjob to generate a text file that is read using node_exporter's textfile collector. This is, as one would expect, ugly.

Consider using a collector like telegraf. Which can run in systemd and provide a prometheus output (prometheus-compatible scraping endpoint) on the nodes.

Also, note that for some drives, reading smart data is a disruptive event and all I/O gets quiesced. Thus it is recommended to do smart data collection at infrequent intervals. Many commercial arrays do it once a day or in some cases, once an hour.

**Comment by evanrich** [comment]
@richardelling  thats true, however this info already is scraped via either rook, the manager, the dashboard module...something:
![image](https://github.com/rook/rook/assets/518320/5d4d8fa4-7ff2-4e8e-8ceb-cfaab4faf620)

so since rook/ceph already have this info, shouldn't it be easy to add to the data already being exported via the ceph prometheus exporter?   I do agree in general that a textcollector is the general way to do this, but I figured since the data already is being presented somehow, that it could also be scraped and exported.

**Comment by richardelling** [comment]
Agree, for the limited data provided. But writing code to scrape ceph API and present as prometheus metrics is not really required for a systems solution, because you can run telegraf in a privileged container or outside of kubernetes (systemd)

**Comment by reefland** [comment]
FYI - I expanded upon previous node exporter text file collector, to gather SMART data from HDDs, SATA SSDs and NVMe devices.  Just have to enable to text file collector feature on node exporter and setup a cron job to run the script every 5 minutes or so.  The text file collector will consume the script output and import into Prometheus.

<https://github.com/reefland/smartmon_nvme>
