### ISSUE TITLE
When a new user is created, I can't see the new user created using the radosgw-admin user list.

### ISSUE THREAD

**Issue by tyxubaoying** [rook/rook#12653]
![image](https://github.com/rook/rook/assets/115436551/12eb1309-1109-4d72-adad-56d719b4b298)
[root@rook-ceph-tools-5f846f89ff-dbx75 /]# radosgw-admin user list
[
    "rook-ceph-internal-s3-user-checker-6b31dde5-0d42-49a9-ab96-1ceef0a3b447",
    "dashboard-admin",
    "s3user",
    "ceph-user-2HYhdauy"
]

**Comment by subhamkrai** [comment]
@tyxubaoying please complete the issue template. Thanks!

**Comment by tyxubaoying** [comment]
ok
