### ISSUE TITLE
Performance drop issue -- with the increasement of RBD, IOPS will drop in rook-ceph storage backend  

### ISSUE THREAD

**Issue by Yongbozzz** [rook/rook#12655]
### Benchmark environment:
Cluster of 3 nodes. 6 NVME SSD for each node. 2 OSD for each SSD.
2 core limit and 8Gi memory for each OSD
###  Benchmark method :
Run FIO job in host, one FIO job will benchmark for one RBD ,test 4k randread IOPS, here is the FIO file sample:
![image](https://github.com/rook/rook/assets/53030444/091b2091-647a-4aa9-8909-4cdbfd74f768)
(the RBD is prvoded by rook-ceph)
### Job Scaling:
We increased FIO job and noticed that the total IOPS will first increase then drop:
![image](https://github.com/rook/rook/assets/53030444/1744d188-9549-490c-b2f7-d4a1f76f1f0f)
I think that's because with the increasement of RBD device , some ceph config might be tuned to avoid resource busy competition?

**Comment by travisn** [comment]
Load and IOPS will very much depend on the specific node and cluster configuration, and the workload. I'm not clear, what is your request with this issue?

**Comment by Yongbozzz** [comment]
Sorry ,I think I should discuss it in Slack, it's more like a performance discussion but not feature request. 
 The problem is with the increasement of benchmark block device(rbd), IOPS will drop, but if I benchmark NVME SSD directly(without Ceph), performance will first grow then keep stable with the increasement of RBD.
So I wondered is there any parameter in Ceph needs to adjust with the increasement of RBD (eg, rbd_op_threads..)
