### ISSUE TITLE
Unable to delete object

### ISSUE THREAD

**Issue by tyxubaoying** [rook/rook#12674]
I created a test-bucket object, created a bucket with the name test-bucket, ran radosgw-admin bucket list and didn't see the newly created bucket, and when I was about to delete the object I got stuck, the logs look like this
<img width="1507" alt="image" src="https://github.com/rook/rook/assets/115436551/14ae31f5-0e31-46a0-9080-9e54b16c03ae">
<img width="503" alt="image" src="https://github.com/rook/rook/assets/115436551/4cfe22e5-fd87-411b-bb11-c8829d3ac7ce">

**Comment by sp98** [comment]
@tyxubaoying did you get a chance to test it out with latest rook and ceph versions?
