### ISSUE TITLE
Handle OSD flapping by stopping the OSD pod

### ISSUE THREAD

**Issue by sp98** [rook/rook#12682]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Handle OSD flapping by stopping the OSD pod

**What is use case behind this feature:**
In [Ceph](https://github.com/ceph/ceph/pull/6708), if an OSD goes down (flaps) for a certain number of times within a certain time period, the OSD is marked as down and is not started again. It is controlled by `osd_max_markdown_count` and `osd_max_markdown_period` in Ceph.

However in Rook,  if the OSD pods are flapping due to a Network issue, the pods are restarted every time due to the `RestartPolicyAlways` set on OSD pod. This impacts the System adversely. 

**Impact**
Whenever an OSD goes down or comes up, the Placement Groups (PG's) mapped to these OSD's would peer. Peering is the process of bringing all of the OSDs that store a Placement Group (PG) into agreement about the state of all of the objects (and their metadata) in that PG. And while the PG's are Peering, the IO to these PG's are blocked.

**Resolution**
This can handled by changing the OSD pod restart policy to `onFailure`. 
This restart policy ensures that the pod is restarted only if the container exited with non zero exit code, that is something went wrong. When OSDs are flapping, Ceph marks the OSDs down with exit code until `osd_max_markdown_count` and `osd_max_markdown_period` threshold are not breached. After that, ceph marks the OSD down with non-zero exit code. 
This non-zero exit code will prevent k8s from restarting OSD pod if its restart policy is set to `onFailure`

**Environment**:

**Comment by sp98** [comment]
The resolution might not work because Deployment pod only supports `always` restart policy.  I can't find any reason in the documentation. But there is a [k8s issue](https://github.com/kubernetes/kubernetes/issues/24725) for this. 

It tried with `onFailure`, but seems like only `always` is supported. 

```failed to create OSD 1 on node "minikube": failed to create deployment for OSD 1 on node "minikube": Deployment.apps "rook-ceph-osd-1" is invalid: spec.template.spec.restartPolicy: Unsupported value: "OnFailure": supported values: "Always"```

**Comment by Madhu-1** [comment]
Just throwing my idea here as deployment cannot have a restart policy

not sure but can we use container hooks and persistence storage like (configmap) to store the restart count and avoid the pod starting again if a certain count is reached if things are corrected, the configmap needs cleanup and might need a restart.

**Comment by sp98** [comment]
> Just throwing my idea here as deployment cannot have a restart policy
> 
> not sure but can we use container hooks and persistence storage like (configmap) to store the restart count and avoid the pod starting again if a certain count is reached if things are corrected, the configmap needs cleanup and might need a restart.

That is something worth looking into. It would require significant effort though.

**Comment by travisn** [comment]
To capture a separate discussion here... What if the main container running ceph-osd instead ran a bash script? The script would run ceph-osd and then if the exit code is 0, sleep for some time (perhaps 6 hours). After the sleep expires, then the OSD could automatically restart again in case it was an intermittent issue.

**Comment by sp98** [comment]
> To capture a separate discussion here... What if the main container running ceph-osd instead ran a bash script? The script would run ceph-osd and then if the exit code is 0, sleep for some time (perhaps 6 hours). After the sleep expires, then the OSD would automatically restart again in case it was an intermittent issue.

Tried with bash script and `sleep`. The liveness probe container restarts the pod.

**Comment by sp98** [comment]
> Just throwing my idea here as deployment cannot have a restart policy
> 
> not sure but can we use container hooks and persistence storage like (configmap) to store the restart count and avoid the pod starting again if a certain count is reached if things are corrected, the configmap needs cleanup and might need a restart.

Pod restart count is the metric we need to track in this case.  If OSD daemon is marked down 6 times in less than 600 seconds, then OSD pod restarts.  We need to prevent this restart.
