### ISSUE TITLE
The bucket has been successfully created, but you cannot see the successfully created bucket using the radosgw-admin bucket list command.

### ISSUE THREAD

**Issue by tyxubaoying** [rook/rook#12680]

**Comment by thotz** [comment]
@tyxubaoying do you have multiple object stores in your environment??

**Comment by tyxubaoying** [comment]
@thotz 
<img width="759" alt="image" src="https://github.com/rook/rook/assets/115436551/0acde58c-bbbe-46ab-9f1f-3c7905133f80">
Ignore pods with status init:0/1 
<img width="813" alt="image" src="https://github.com/rook/rook/assets/115436551/78b91f79-0b07-467c-85f3-0b182a9fcb6e">
One. I wanted to create multiple buckets based on the official example, which corresponds to multiple objects and sc and objectbucketstore
<img width="442" alt="image" src="https://github.com/rook/rook/assets/115436551/bea66ecb-83d0-4163-a97f-0663d73b23c1">
Now it can't be deleted, it says the storage bucket isn't cleaned.
| ceph-object-controller: failed to delete object store. buckets for objectstore "my-store" in namespace "rook-ceph" are not cleaned up. remaining buckets: [obc-default-document-bucket obc-default-test-bucket]
[root@rook-ceph-tools-5f846f89ff-dbx75 /]# radosgw-admin bucket list
[
    "rook-ceph-bucket-checker-6b31dde5-0d42-49a9-ab96-1ceef0a3b447",
    "document-bucket-d34256a3-1a89-4d5b-a733-c8bbc2029138"
]

**Comment by thotz** [comment]
Since u have multiple object stores u need to pass objectstore name as rgw-zone, rgw-zonegroup and rgw-realm for the radosgw-admin command, from the look it seems they are listing `document-bucket` object store.
`radosgw-admin bucket list --rgw-realm=my-store --rgw-zone=my-store --rgw-zonegroup=my-store`
