### ISSUE TITLE
rook-ceph-mon remains terminating after several hours of network outages

### ISSUE THREAD

**Issue by dwy12321** [rook/rook#12689]
The nodes of kubernetes is disconnect for 24 hours.  rook-ceph-mon pod keep terminating status all the time. 
how can i recover rook-ceph-mon？
![image](https://github.com/rook/rook/assets/37011422/cdca696b-a412-4bfe-b73a-a42419ec0015)

**Comment by subhamkrai** [comment]
@dwy12321 please complete the issue template
