### ISSUE TITLE
I'd like a way to generate ceph.conf and keyring data to access my cluster with RADOS

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#127]
You need a ceph.conf file to start a rados client.  With the tools as they are it is hard to create one.

I'd like to see an option to the rook tool that emits a usable ceph.conf file either to a file or on stdout.

Likewise I'd like to see a similar command that facilitates generating a keyring file for the cephx keys.

**Comment by travisn** [comment]
Closing all tickets related to standalone. See #985.
