### ISSUE TITLE
Generate multus validation job help text from `rook multus validation run --help`

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#12706]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

As a help for users and developers, use the output of `rook multus validation run --help` to generate usage text for the top of `deploy/examples/multus-validation.yaml`

```yaml
####################################################################################################
# This manifest contains a Kubernetes Job and supporting definitions for running Rook's Multus
# validation tool. The Multus validation tool's help text is copied below. Modify the Job
# definition in this manifest based on the needs of your cluster.
####################################################################################################
#
# <AUTO GENERATED HELP TEXT GOES HERE>
# 
# (auto-generated by `<command used to generate the doc text>`)
####################################################################################################
```

Help text can be generated during `make crds` via `go run cmd/rook/*.go multus validation run --help`. 

Today, the top text would look like so:

```yaml
####################################################################################################
# This manifest contains a Kubernetes Job and supporting definitions for running Rook's Multus
# validation tool. The Multus validation tool's help text is copied below. Modify the Job
# definition in this manifest based on the needs of your cluster.
####################################################################################################
#
# Run a validation test that determines whether the current Multus and system
# configurations will support Rook with Multus.
#
# This should be run BEFORE Rook is installed.
#
# This is a fairly long-running test. It starts up a web server and many
# clients to verify that Multus network communication works properly.
#
# It does *not* perform any load testing. Networks that cannot support high
# volumes of Ceph traffic may still encounter runtime issues. This may be
# particularly noticeable with high I/O load or during OSD rebalancing
# (see: https://docs.ceph.com/en/latest/architecture/#rebalancing).
# For example, during Rook or Ceph cluster upgrade.
#
# Override the kube config file location by setting the KUBECONFIG environment variable.
#
# Usage:
#   rook multus validation run [--public-network=<nad-name>] [--cluster-network=<nad-name>] [flags]
#
# Flags:
#       --cluster-network string           The name of the Network Attachment Definition (NAD) that will be used for Ceph's cluster network. This should be a namespaced name in the form <namespace>/<name> if the NAD is defined in a different namespace from the cluster namespace.
#   -c, --config string                    The validation test config file to use. This cannot be used with other flags.
#       --daemons-per-node int             The number of validation test daemons to run per node. It is recommended to set this to the maximum number of Ceph daemons that can run on any node in the worst case of node failure(s). The default value is set to the worst-case value for a Rook Ceph cluster with 3 portable OSDs, 3 portable monitors, and where all optional child resources have been created with 1 daemon such that they all might run on a single node in a failure scenario. If you aren't sure what to choose for this value, add 1 for each additional OSD beyond 3. (default 16)
#   -h, --help                             help for run
#   -n, --namespace string                 The namespace for validation test resources. It is recommended to set this to the namespace in which Rook's Ceph cluster will be installed. (default "rook-ceph")
#       --nginx-image string               The Nginx image used for the validation server and clients. (default "nginxinc/nginx-unprivileged:stable-alpine")
#       --public-network string            The name of the Network Attachment Definition (NAD) that will be used for Ceph's public network. This should be a namespaced name in the form <namespace>/<name> if the NAD is defined in a different namespace from the cluster namespace.
#       --timeout-minutes timeoutMinutes   The time to wait for resources to change to the expected state. For example, for the test web server to start, for test clients to become ready, or for test resources to be deleted. At longest, this may need to reflect the time it takes for client pods to to pull images, get address assignments, and then for each client to determine that its network connection is stable. Minimum: 1 minute. Recommended: 2 minutes or more. (default 3m0s)
#
# Global Flags:
#       --log-level string   logging level for logging/tracing output (valid values: ERROR,WARNING,INFO,DEBUG) (default "INFO")
#
# (auto-generated by `<generate cmd>`)
####################################################################################################
```

It would be nice to auto-wrap the commented output to approximately 100 lines, but that is not necessary.

**Environment**:

**Comment by BlaineEXE** [comment]
Thanks @Sheetalpamecha !  I updated the description today, so please take a look at the latest. 

I'd also like to invite @travisn and @galexrt to comment what `make ...` command seems most appropriate for auto-generating this manifest's doc.

I think `make crds` is not the best choice. Perhaps `make docs-build` @galexrt ? Any other thoughts?

**Comment by galexrt** [comment]
@BlaineEXE yeah, I think `make docs-build` makes sense in this context, though will this output also be written to a markdown file or only to that yaml file?

**Comment by travisn** [comment]
Actually, what if in this yaml file we just say to run `rook multus validation run --help` to print the help? Why do we need to include it in the yaml file automatically?

**Comment by BlaineEXE** [comment]
> Actually, what if in this yaml file we just say to run `rook multus validation run --help` to print the help? Why do we need to include it in the yaml file automatically?

The yaml file already says that. But including the output in the yaml file means that users can get up and running with less effort, and there is an amount of instruction we have to provide at the top of the manifest to tell users what it does. We can eliminate having to maintain as much duplicate doc by having the output automatically added to the top of the file, IMO

**Comment by travisn** [comment]
Another idea... Shall we create a doc page just for the validation tool? Currently it's embedded in the cluster CR page, which can be difficult to find. Then we can add more details on that doc.

**Comment by BlaineEXE** [comment]
> Another idea... Shall we create a doc page just for the validation tool? Currently it's embedded in the cluster CR page, which can be difficult to find. Then we can add more details on that doc.

That is probably a good idea regardless. And given that it is a primary goal that the validation tool itself is self-documenting, I think using the `rook multus validation run --help` output copied to the doc is a good strategy.

**Comment by BlaineEXE** [comment]
Or for docs, maybe the `runCmd.Long` text would be good to copy to the doc: 
https://github.com/rook/rook/blob/853bab398a5de0398f9fe94ec6242ff4cfeefb87/cmd/rook/userfacing/multus/validation/validation.go#L48-L68

**Comment by obnoxxx** [comment]
I am interested in taking this up, but did not want to overryde the assignment of @Sheetalpamecha ! ...

@BlaineEXE ,  I have to say that the snippets of the `multus-validation.yaml` file pasted in the PR  description do not match  at all what I see in my local checkout.

**Comment by obnoxxx** [comment]
@BlaineEXE ,  I have to say that the snippets of the `multus-validation.yaml` file pasted in the PR  description do not match  at all what I see in my local checkout.  neither with the contents of https://github.com/rook/rook/blob/master/deploy/examples/multus-validation.yaml.

I am therefore a bit unclear whether the existing file should be patched or if a new file / content should be created by the build process ...

**Comment by BlaineEXE** [comment]
I was thinking to patch the existing file by adding/replacing the `--help` output in the file header

**Comment by obnoxxx** [comment]
> I was thinking to patch the existing file by adding/replacing the `--help` output in the file header

Thanks for confirming, @BlaineEXE .

I am, however, still slightly confused by the idea to patch the manifest file:

It is a checked in file and running  `make docs-build` locally would then create unstaged and untracked changes.

wouldn't it be cleaner to just commit the changes to the yaml file directly to the tree? The help text is in the git tree already anyway: as part of thew tool code.

Even to implement the patching mechanism, I would be tempted to update the yaml file in the git tree first to match the snippet given in the issue description, which is different from the current state of the committed file. thoughts? - @BlaineEXE , @travisn , @galexrt ?

**Comment by galexrt** [comment]
> It is a checked in file and running make docs-build locally would then create unstaged and untracked changes.

That YAML file would be checked in like, e.g., the CRD API references docs file, it is generated locally and only changed when there are changes to the CRD types.go files, and only then a user has to commit that file, right @BlaineEXE ?

The patching would be run in the CI to make sure the commitor has not forgotten to run certain make targets that are needed to be run based on the code/docs changed, e.g., CRD code generation.

**Comment by obnoxxx** [comment]
> > It is a checked in file and running make docs-build locally would then create unstaged and untracked changes.
> 
> That YAML file would be checked in like, e.g., the CRD API references docs file, it is generated locally and only changed when there are changes to the CRD types.go files, and only then a user has to commit that file, right @BlaineEXE ?
> 
> The patching would be run in the CI to make sure the commitor has not forgotten to run certain make targets that are needed to be run based on the code/docs changed, e.g., CRD code generation.


Thanks @galexrt ! I am still not entirely clear despite your answer though:

I wonder if it is a common pattern in rook that make targets modify committed files so that they would need to be committed again after running the make rule.

trying various makw commands, I did al least not find any example of such a behavior.

And I would certainly be reluctant to newly introduce such a pattern if it is not already a standard in the project.

The situation would of course change for me if I learn from the maintainers that this is the rook way of doing it ...

**Comment by travisn** [comment]
There is a pattern to generate some files in Rook and have the developer commit them, for example crds.yaml and specification.md. The CI will cause errors if those files need to be updated and have not been updated by the PR author.

What is different in this case is that we would need to run the `rook` binary to generate the help text that would be updated in the documentation. This seems awkward to me since we haven't previously required running the `rook` binary on the developer machine, we've only been required to run it in a K8s environment such as the operator container. I'm not saying it can't be done, it's just a new pattern we may not want to worry about unless it's really necessary.

**Comment by BlaineEXE** [comment]
I didn't think this feature request would be such a complicated thing to explain or justify. I'm having a great deal of pain trouble seeing out of one eye right now, and I am going to write as little as possible to explain what I envision seeing:

Here is the example manifest file, broken down into sections:

Static, manually edited header marker to help auto-gen script:
```
####################################################################################################
# This manifest contains a Kubernetes Job and supporting definitions for running Rook's Multus
# validation tool. The Multus validation tool's help text is copied below. Modify the Job
# definition in this manifest based on the needs of your cluster.
####################################################################################################
# BELOW HELP TEXT IS AUTO GENERATED BY `make docs-build`
```

Auto-generated text goes next
```
<output of rook multus validation run --help goes here>
```

The rest of the manifest is manually edited and begins with a marker to help the auto-gen script.
```
# ABOVE HELP TEXT IS AUTO GENERATED BY `make docs-build`
####################################################################################################
<the rest of the manifest>
```

I continue to believe that auto generating this will be helpful for users and helpful for my own sanity. Users will consistently ask the most asinine questions about how to use the tool in order to avoid doing the simple work of running the tool with `--help` to see how to use it. If we auto-copy the help text to the top of the file, we help users, and we help my sanity both.

IMO, it is probably also helpful to copy the `Long` text from the `multus validation run` cobra command to our markdown docs as well, but I am not as concerned about that right now as I am with adding help text to the file.

I don't see any technical reason to object to using `go run...` to generate the docs locally. Golang has strong multi-platform and multi-arch support. Any machine that can run `go build` should also be fine to use `go run...` as I've suggested

**Comment by obnoxxx** [comment]
@BlaineEXE ,  I am very sorry that my comments and newbie questions caused you such a lot of frustration and pain! I was only trying to understand how to approach this best..

as per my current understanding, this request would be implemented by a series of commits like this:

1. replace the current `multus-validation.yaml` with the expanded version (with sections)that you sketched in your previous comment 
2.  modify `make docs-build` to insert the help output into the yaml



Is this more or less what you had in mind?

But I see one issue with this: according to some previous commits (e. g. by @travisn ), I would expect to commit the updated yaml file into the tree, but this would likely render it impossible to run `make docs-build` again, as it would fail on the modified yaml file ... It would be simpler to commit the file directly with the help text. after all, what is the use of an auto-generate task that can't be run twice (idempotently)? ...



So I am sorry to say this, but I am still somewhat unclear what is the best approach here.

**Comment by obnoxxx** [comment]
@BlaineEXE  wrote:

> > as per my current understanding, this request would be implemented by a series of commits like this:
> 
> Side note: Use only a single, squashed commit. The best-practice Rook follows is that if we need to revert a feature something, we should only need to revert one commit.

got it. I was aware of this standard of the rook project , and  while I personally prefer more commits that are logically separate, and in combination implement the broader change, I will of course abide to this rule when proposing a change. :-) 


> 
> > 1. replace the current `multus-validation.yaml` with the expanded version (with sections)that you sketched in your previous comment
> > 2. modify `make docs-build` to insert the help output into the yaml
> > 
> > Is this more or less what you had in mind?
> 
> Yes, mostly.

great, thanks for confirming!
> Instead of "insert," I think this is better conceptualized as "replace all comments between the markers with the help text."
> 

yeah, this is what I meant to express with my imprecise words ...

> > But I see one issue with this: according to some previous commits (e. g. by @travisn ), I would expect to commit the updated yaml file into the tree, but this would likely render it impossible to run `make docs-build` again, as it would fail on the modified yaml file ... It would be simpler to commit the file directly with the help text. after all, what is the use of an auto-generate task that can't be run twice (idempotently)? ...
> 
> I see you asked about a git tree, but to be honest, I don't really understand what were asking about. As you identified, auto-generate is not useful if it's not idempotent, so the auto-gen must be idempotent. 

glad that we agree on this.

> It sounds like doing stuff to the git tree would make the implementation non-idempotent


At least that's what I thought initially, but thinking more closely about it, I guess that if the auto-gen mechanism keeps the markers in the file, this will make sure that it remains idempotent irrespective of whether the resulting file is git-committed after the auto-gen run.

>  so let's not do anything with git here.
 right, but we wouldn't do any git committing automatically anyway. I thought that the developer was expected to commit the result og the auto-gen run. 


> Rook has doc-related CI that verifies if devs have missed running any `make ...` commands for generating stuff. See the GitHub action here: https://github.com/BlaineEXE/rook/blob/2e7f9045abf605850f1aaad4ec56a033b5a25e4a/.github/workflows/docs-check.yml#L36-L58

Thanks, this is helpful and makes a lot of sense. the same could be done with the yaml file. But I wonder if those mechanism should/could be put into make targets so that they can easily be run locally by the dev?

> 
> After looking more closely at the `make docs-build` code, I don't want to make users install `mkdocs` just to update the example manifest. I think it may end up being best if we create a new make target here: https://github.com/BlaineEXE/rook/blob/86630709b7951f0a5b494f3f27d46a08c1aadb34/Makefile#L193-L221
> 
> I'd suggest `make docs` and also have that call `helm-docs` (add simplicity for users). In the GH action code, insert a duplicate of the `Run helm-docs` step, but replace `helm-docs` with just `docs`.
> 

I am not sure that I understand the relationship between the `multus-validation.yaml` and the 
`helm-docs` target yet. I might reach out directly to discuss this part of your guidance ...

> I don't think this is truly ideal, but Rook's `make` tooling is not ideal, and this is I think the best way to handle make targets and CI right now.


Thanks for the explanations! I will try to propose a patch soon. :-)
