### ISSUE TITLE
Support CephObjectStoreUser in any namespace

### ISSUE THREAD

**Issue by os14** [rook/rook#12716]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
We want to be able to create an CephObjectStoreUser in any namespace in the cluster.
The rook-operator should create the secret with the credentials in the same namespace as the CephObjectStoreUser.

**What is use case behind this feature:**
We have a service in the cluster that is responsible for creating the buckets, so we can't use the ObjectBucketClaim resource.
The service reside in a different namespace than the rook namesapce, we want to be able to dynamically create credentials for the service and mount them.

**Environment**:
Vanilla k8s on-prem cluster.

**Comment by travisn** [comment]
You only want the object user created, and no buckets by default? So you're saying neither [OBCs](https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/) nor [COSI](https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/cosi/) match your requirements. 

Today the CephObjectStoreUser assumes in the same namespace as both the parent CephCluster and CephObjectStore. This allows clusters or object stores to be created in multiple namespaces and remain independent of one another. But perhaps for the specific case where there is only one CephCluster, this could be considered for the CephObjectStoreUser.
@BlaineEXE @thotz Thoughts?

**Comment by os14** [comment]
> You only want the object user created, and no buckets by default? So you're saying neither [OBCs](https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/) nor [COSI](https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/cosi/) match your requirements.
> 
> Today the CephObjectStoreUser assumes in the same namespace as both the parent CephCluster and CephObjectStore. This allows clusters or object stores to be created in multiple namespaces and remain independent of one another. But perhaps for the specific case where there is only one CephCluster, this could be considered for the CephObjectStoreUser. @BlaineEXE @thotz Thoughts?

yes, exactly.

**Comment by travisn** [comment]
A first run of the feature is implemented in #12730. My main concern is about how admins can control this feature. Thoughts on [this comment](https://github.com/rook/rook/pull/12730#discussion_r1295226804)?

**Comment by os14** [comment]
> A first run of the feature is implemented in #12730. My main concern is about how admins can control this feature. Thoughts on [this comment](https://github.com/rook/rook/pull/12730#discussion_r1295226804)?

The "allowUsersInAnyNamespace: true" flag sounds good imo. Can be set to be false as default.
