### ISSUE TITLE
Feature Request: Support for revisionHistoryLimit

### ISSUE THREAD

**Issue by reefland** [rook/rook#12722]
**Is this a bug report or feature request?**
* Feature Request

Enable support for `revisionHistoryLimit` to be specified in the CephCluster CR, which can then be used in the helm chart.
* To allow reducing the Kubernetes default of 10 to something else like 3 as every plugin, ceph-tools, crash collector, mds, rgw, mgr, operator, every OSD will maintain 10 copies.
* Loading the `rook-ceph` namespace and working with it from the CLI or a GUI like ArgoCD is cumbersome, waiting for all the copies of each objects to load and render.

This was discussed #12693 where @travisn started a [list of changes](https://github.com/rook/rook/discussions/12693#discussioncomment-6682721) to be considered.

**Comment by travisn** [comment]
Since this is not dependent on helm installs, I removed Helm from the title since all installs would benefit from this feature request.

**Comment by ashutosh887** [comment]
Let me work on this @subhamkrai

**Comment by subhamkrai** [comment]
@ashutosh887 I see you have commented on a few other issues to work on. How about you pick any one issue first and move to the next issue?

**Comment by ashutosh887** [comment]
@subhamkrai 
Did you assign me on any of them?

**Comment by subhamkrai** [comment]
> @subhamkrai Did you assign me on any of them?

@ashutosh887 you can self-assign this issue now https://github.com/rook/rook/blob/master/Documentation/Contributing/development-flow.md#self-assign-issue

**Comment by ashutosh887** [comment]
Thanks a lot @subhamkrai 
I didn't knew that's enabled here

/assign

**Comment by subhamkrai** [comment]
> Thanks a lot @subhamkrai I didn't knew that's enabled here
> 
> /assign

sure

**Comment by travisn** [comment]
Unassigned due to inactivity

**Comment by BlaineEXE** [comment]
I think it would be best to provide this configurable on each CRD that creates ReplicaSets as well. CephCluster, CephObjectStore, CephFilesystem, CephNFS are the big ones I can think of. 

I wonder if the other controllers should default to the CephCluster value if unset as well.

@travisn thoughts?

**Comment by obnoxxx** [comment]
changed the label from Bug to Feature since that's what the title and description say.

**Comment by travisn** [comment]
> I think it would be best to provide this configurable on each CRD that creates ReplicaSets as well. CephCluster, CephObjectStore, CephFilesystem, CephNFS are the big ones I can think of.
> 
> I wonder if the other controllers should default to the CephCluster value if unset as well.
> 
> @travisn thoughts?

If there is a reason to customize each daemon, sounds good to add it to each CR, but perhaps we just start with the CephCluster CR setting to keep it simple for all daemons to inherit.

**Comment by obnoxxx** [comment]
@Sheetalpamecha  I'm also interested in taking this up but didn't want to just take it away from you. Would you  be OK if I also started working on a patch for this? If you have already started serious work on it, I'll refrain from looking further 😄

**Comment by Sheetalpamecha** [comment]
Hey @obnoxxx I'm almost done with the patch. :)

**Comment by travisn** [comment]
@Sheetalpamecha Still planning on this?

**Comment by BlaineEXE** [comment]
I wonder if this should be an operator-scope setting, like `ROOK_REVISION_HISTORY_LIMIT`. I don't imagine that many users would want to change this setting on a per-cephcluster basis -- probably cluster-wide instead. And an operator setting might make it more clear that this behavior will be used for all Rook pods and not just the CephCluster resource.

**Comment by reefland** [comment]
Any update on this?

**Comment by parth-gr** [comment]
@travisn I can take this item? Unless anyone else is intrested.

**Comment by obnoxxx** [comment]
I'd like to give it a try.

/assign
