### ISSUE TITLE
how excecute ceph-objectstore-tool on osd  ?

### ISSUE THREAD

**Issue by konvergence** [rook/rook#12735]
**Is this a bug report or feature request?**
* Bug Report
* the osd pod thake more than 4GB (about 10GB) and take a long time to load_pgs with logs 
```
read_log_and_missing WARN num of dups exceeded 6000. You can be hit by THE DUPS BUG https://tracker.ceph.com/issues/53729. Consider ceph-objectstore-tool --op trim-pg-log-dups
```
* how to run ceph-objectstore-tool  on an OSD pod for https://tracker.ceph.com/issues/53729#note-57 ?

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

* don't really know how to reproduce
* but the bug was reported on https://tracker.ceph.com/issues/53729

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): `CentOS Stream 8` (docker image)
* Kernel (e.g. `uname -a`): `5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `rke1`
* Rook version (use `rook version` inside of a Rook Pod): `1.9.12`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 16.2.13 (5378749ba6be3a0868b51803968ee9cde4833a3e) pacific (stable)`
* Kubernetes version (use `kubectl version`): `1.24.13`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  `rancher 2.7.4/RKE1`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
```
bash-4.4$ ceph -s
  cluster:
    id:     4b32d4a0-a197-4b8c-a486-175ff97138df
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 2d)
    mgr: a(active, since 2d)
    mds: 1/1 daemons up, 1 hot standby
    osd: 6 osds: 6 up (since 68m), 6 in (since 68m)
 
  data:
    volumes: 1/1 healthy
    pools:   5 pools, 161 pgs
    objects: 202.63k objects, 264 GiB
    usage:   437 GiB used, 1.3 TiB / 1.8 TiB avail
    pgs:     161 active+clean
 
  io:
    client:   1.4 KiB/s rd, 2.7 MiB/s wr, 1 op/s rd, 72 op/s wr
```

**Comment by subhamkrai** [comment]
@konvergence you can use kubectl plugin for rook-ceph more https://github.com/rook/kubectl-rook-ceph/blob/master/docs/debug.md#debug-mode
