### ISSUE TITLE
Cluter-on-pvc.yaml example doesn't work with openshift

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#12746]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

If we use `cluster-on-pvc.yaml` to deploy rook on top of openshift it doesn't work,

One problem I saw was we need to update the storage class to `gp2-csi`
And there are other node labels issue that aboid the mon canary pods to create it and process with the deployment

**Expected behavior:**

Rook deployment should be successfully created on open shift using the examples directly.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by subhamkrai** [comment]
@parth-gr cluster-on-pvc yaml is a generalised example of PVC based cluster. It can be any other cluster than openshift+Aws also.

**Comment by travisn** [comment]
The example is only designed to work by default on AWS with the `gp2` storage class. I think the best we can do is add this comment wherever the change in storage class is needed for other platforms:
```
# IMPORTANT: Change the storage class depending on your environment
```

That comment is missing for the storage class used for the mons, but it's there on the OSDs.
