### ISSUE TITLE
HEALTH_WARN 4 mgr modules have recently crashed

### ISSUE THREAD

**Issue by dai0384448** [rook/rook#12758]
**Is this a bug report or feature request?**
* Bug Report
* 
bash-4.4$ ceph health detail
HEALTH_WARN 4 mgr modules have recently crashed
[WRN] RECENT_MGR_MODULE_CRASH: 4 mgr modules have recently crashed
    mgr module nfs crashed in daemon mgr.a on host rook-ceph-mgr-a-694cffbd6b-rszbt at 2023-08-17T08:28:45.115999Z
    mgr module nfs crashed in daemon mgr.a on host rook-ceph-mgr-a-694cffbd6b-rszbt at 2023-08-17T08:28:46.705771Z
    mgr module nfs crashed in daemon mgr.a on host rook-ceph-mgr-a-694cffbd6b-rszbt at 2023-08-21T00:38:45.153305Z
    mgr module nfs crashed in daemon mgr.a on host rook-ceph-mgr-a-694cffbd6b-rszbt at 2023-08-21T00:38:50.929734Z
bash-4.4$
bash-4.4$ ceph -s
  cluster:
    id:     f5d017a5-b412-445f-a198-180cdbdce9fe
    health: HEALTH_WARN
            4 mgr modules have recently crashed

  services:
    mon: 3 daemons, quorum a,c,b (age 3d)
    mgr: a(active, since 5h), standbys: b
    osd: 4 osds: 4 up (since 3d), 4 in (since 2w)

  data:
    pools:   2 pools, 33 pgs
    objects: 297 objects, 931 MiB
    usage:   3.4 GiB used, 397 GiB / 400 GiB avail
    pgs:     33 active+clean

**Deviation from expected behavior:**
 health: HEALTH_WARN

**Expected behavior:**
 health: HEALTH_OK

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
[root@master1 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (e.g. `uname -a`):
[root@master1 ~]# uname -a
Linux master1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
4C/16G/50G
* Rook version (use `rook version` inside of a Rook Pod):
[v1.12.1]

* Storage backend version (e.g. for ceph do `ceph -v`):
bash-4.4$ ceph -v
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)

* Kubernetes version (use `kubectl version`):
Client Version: v1.23.17
Server Version: v1.23.17

**Comment by zhucan** [comment]
can you show the crash info with cmd "ceph crash info xxx"?

**Comment by dai0384448** [comment]
bash-4.4$ ceph crash ls-new
ID                                                                ENTITY  NEW
2023-08-21T09:19:33.322424Z_b29dfd5c-2afd-4d9b-9a4a-778a5cbcfadd  mgr.a    *
bash-4.4$ ceph crash info 2023-08-21T09:19:33.322424Z_b29dfd5c-2afd-4d9b-9a4a-778a5cbcfadd
{
    "backtrace": [
        "  File \"/usr/share/ceph/mgr/nfs/module.py\", line 169, in cluster_ls\n    return available_clusters(self)",
        "  File \"/usr/share/ceph/mgr/nfs/utils.py\", line 38, in available_clusters\n    completion = mgr.describe_service(service_type='nfs')",
        "  File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 1488, in inner\n    completion = self._oremote(method_name, args, kwargs)",
        "  File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 1555, in _oremote\n    raise NoOrchestrator()",
        "orchestrator._interface.NoOrchestrator: No orchestrator configured (try `ceph orch set backend`)"
    ],
    "ceph_version": "17.2.6",
    "crash_id": "2023-08-21T09:19:33.322424Z_b29dfd5c-2afd-4d9b-9a4a-778a5cbcfadd",
    "entity_name": "mgr.a",
    "mgr_module": "nfs",
    "mgr_module_caller": "ActivePyModule::dispatch_remote cluster_ls",
    "mgr_python_exception": "NoOrchestrator",
    "os_id": "centos",
    "os_name": "CentOS Stream",
    "os_version": "8",
    "os_version_id": "8",
    "process_name": "ceph-mgr",
    "stack_sig": "b01db59d356dd52f69bfb0b128a216e7606f54a60674c3c82711c23cf64832ce",
    "timestamp": "2023-08-21T09:19:33.322424Z",
    "utsname_hostname": "rook-ceph-mgr-a-694cffbd6b-rszbt",
    "utsname_machine": "x86_64",
    "utsname_release": "3.10.0-1160.el7.x86_64",
    "utsname_sysname": "Linux",
    "utsname_version": "#1 SMP Mon Oct 19 16:18:59 UTC 2020"
}

**Comment by dai0384448** [comment]
bash-4.4$ ceph -s
  cluster:
    id:     f5d017a5-b412-445f-a198-180cdbdce9fe
    health: HEALTH_WARN
            1 mgr modules have recently crashed

  services:
    mon: 3 daemons, quorum a,c,b (age 9h)
    mgr: a(active, since 5h), standbys: b
    osd: 4 osds: 4 up (since 7d), 4 in (since 3w)

  data:
    pools:   2 pools, 33 pgs
    objects: 1.02k objects, 3.5 GiB
    usage:   12 GiB used, 388 GiB / 400 GiB avail
    pgs:     33 active+clean

  io:
    client:   2.7 KiB/s wr, 0 op/s rd, 0 op/s wr

bash-4.4$
bash-4.4$ ceph health  detail
HEALTH_WARN 1 mgr modules have recently crashed
[WRN] RECENT_MGR_MODULE_CRASH: 1 mgr modules have recently crashed
    mgr module nfs crashed in daemon mgr.a on host rook-ceph-mgr-a-694cffbd6b-rszbt at 2023-08-21T09:19:33.322424Z
bash-4.4$ ceph mgr module  enable crash
module 'crash' is already enabled (always-on)
bash-4.4$ ceph crash ls
ID                                                                ENTITY  NEW
2023-08-01T10:12:03.779803Z_ea1527a1-9064-434d-8155-bc11c9ffef02  mgr.a
2023-08-04T02:14:17.905033Z_faa1ef13-af2c-4b38-b7c1-b87f82a6510c  mgr.a
2023-08-04T02:21:50.253800Z_5b64a2bf-81b3-450b-b597-826e3be33f9c  mgr.a
2023-08-04T03:21:19.156981Z_02a2bd4b-b974-4a23-8564-fb65cbacddc6  mgr.a
2023-08-17T08:28:45.115999Z_fe38bccc-b06c-4fad-9fd7-3d907db92abe  mgr.a
2023-08-17T08:28:46.705771Z_c9bfd142-50fd-4afd-87cf-6a1ebc2ff88f  mgr.a
2023-08-21T00:38:45.153305Z_36ba20c6-8a7d-4f55-bb59-669c6feb7152  mgr.a
2023-08-21T00:38:50.929734Z_8c87caaf-6f7f-4271-b48e-de6ee556a3bc  mgr.a
2023-08-21T08:09:41.041363Z_391a0c3b-0c19-429b-b22d-4cf9a818f10a  mgr.a
2023-08-21T09:19:33.322424Z_b29dfd5c-2afd-4d9b-9a4a-778a5cbcfadd  mgr.a    *
bash-4.4$ ceph crash ls-new
ID                                                                ENTITY  NEW
2023-08-21T09:19:33.322424Z_b29dfd5c-2afd-4d9b-9a4a-778a5cbcfadd  mgr.a    *
bash-4.4$ ceph crash info 2023-08-21T09:19:33.322424Z_b29dfd5c-2afd-4d9b-9a4a-778a5cbcfadd
{
    "backtrace": [
        "  File \"/usr/share/ceph/mgr/nfs/module.py\", line 169, in cluster_ls\n    return available_clusters(self)",
        "  File \"/usr/share/ceph/mgr/nfs/utils.py\", line 38, in available_clusters\n    completion = mgr.describe_service(service_type='nfs')",
        "  File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 1488, in inner\n    completion = self._oremote(method_name, args, kwargs)",
        "  File \"/usr/share/ceph/mgr/orchestrator/_interface.py\", line 1555, in _oremote\n    raise NoOrchestrator()",
        "orchestrator._interface.NoOrchestrator: No orchestrator configured (try `ceph orch set backend`)"
    ],
    "ceph_version": "17.2.6",
    "crash_id": "2023-08-21T09:19:33.322424Z_b29dfd5c-2afd-4d9b-9a4a-778a5cbcfadd",
    "entity_name": "mgr.a",
    "mgr_module": "nfs",
    "mgr_module_caller": "ActivePyModule::dispatch_remote cluster_ls",
    "mgr_python_exception": "NoOrchestrator",
    "os_id": "centos",
    "os_name": "CentOS Stream",
    "os_version": "8",
    "os_version_id": "8",
    "process_name": "ceph-mgr",
    "stack_sig": "b01db59d356dd52f69bfb0b128a216e7606f54a60674c3c82711c23cf64832ce",
    "timestamp": "2023-08-21T09:19:33.322424Z",
    "utsname_hostname": "rook-ceph-mgr-a-694cffbd6b-rszbt",
    "utsname_machine": "x86_64",
    "utsname_release": "3.10.0-1160.el7.x86_64",
    "utsname_sysname": "Linux",
    "utsname_version": "#1 SMP Mon Oct 19 16:18:59 UTC 2020"
}

**Comment by dai0384448** [comment]
Clear the crash records that have exceeded the keep period. keep must be an integer

bash-4.4$ ceph crash prune 3
bash-4.4$ ceph crash ls
bash-4.4$

The alarm is cleared. I don't know what the impact will be, and the specific problem has not been solved.

**Comment by capfzgs** [comment]
I have met the same issue.from dashboard we can see Orchestrator is not available. 
btw,my ceph base 18.2.0(reef)

**Comment by zhucan** [comment]
do you try run "ceph orch set backend" ? @capfzgs @dai0384448

**Comment by zhucan** [comment]
realated issue https://github.com/rook/rook/issues/11316

**Comment by capfzgs** [comment]
![图片](https://github.com/rook/rook/assets/11909943/32aeee51-d6e1-4380-9bd5-f7ae17133f36)
![图片](https://github.com/rook/rook/assets/11909943/9ae6d736-5ab8-4fa5-b767-635504a708cc)
![图片](https://github.com/rook/rook/assets/11909943/6ca5deb3-264a-4565-99b4-ce9be7392b53)
![图片](https://github.com/rook/rook/assets/11909943/4d380bb2-a428-419d-84ba-87da07260c43)
can you help review attached files and give me some ideas?thanks

**Comment by travisn** [comment]
Try this from the toolbox to enable the rook orchestrator module:
```
ceph mgr module enable rook
ceph orch set backend rook
```

**Comment by capfzgs** [comment]
@travisn  Thanks for your reply.looks like this command did't help
`[root@node01 ~]# ceph mgr module enable rook
Error ENOENT: all mgr daemons do not support module 'rook', pass --force to force enablement
[root@node01 ~]# ceph orch set backend rook
Error EINVAL: Module 'rook' not found
[root@node01 ~]#
`

**Comment by zhucan** [comment]
@capfzgs  could you paste the deploy  steps and paste the yaml info?

**Comment by capfzgs** [comment]
@zhucan I have attached deploy steps. there have no yaml info.Please refer attached files.Thanks for your help.

[ceph deploy.txt](https://github.com/rook/rook/files/12646640/ceph.deploy.txt)

**Comment by zhucan** [comment]
why not use rook to deploy the ceph cluster? please show results of the "ceph mgr module ls".

**Comment by capfzgs** [comment]
@zhucan Ceph mgr module ls output in there.
`[root@node01 ~]# ceph mgr module ls
MODULE
balancer              on (always on)
crash                 on (always on)
devicehealth          on (always on)
orchestrator          on (always on)
pg_autoscaler         on (always on)
progress              on (always on)
rbd_support           on (always on)
status                on (always on)
telemetry             on (always on)
volumes               on (always on)
dashboard             on
iostat                on
nfs                   on
orch                  on
restful               on
alerts                -
diskprediction_local  -
influx                -
insights              -
localpool             -
mds_autoscaler        -
mirroring             -
osd_perf_query        -
osd_support           -
prometheus            -
rgw                   -
selftest              -
snap_schedule         -
stats                 -
telegraf              -
test_orchestrator     -
zabbix                -
[root@node01 ~]#
`

**Comment by zhucan** [comment]
@capfzgs 
```
ceph orch set backend rook
ceph orch status 
```

output is?

**Comment by zhucan** [comment]
for "nfs-ganesha is not configured", I think you not config it"https://docs.ceph.com/en/latest/cephfs/nfs/".

**Comment by capfzgs** [comment]
> @capfzgs
> 
> ```
> ceph orch set backend rook
> ceph orch status 
> ```
> 
> output is?

[root@node01 ~]# ceph mgr module enable rook Error ENOENT: all mgr daemons do not support module 'rook', pass --force to force enablement [root@node01 ~]# ceph orch set backend rook Error EINVAL: Module 'rook' not found [root@node01 ~]#

**Comment by zhucan** [comment]
because of your ceph cluster was deployed by cephadm, so I think you can run:
```
ceph orch set backend cephadm
ceph orch status
```
and show me the results.

**Comment by zhucan** [comment]
it's inconvenient. Please give me your email and I will invite you to the slack.

**Comment by zhucan** [comment]
https://docs.ceph.com/en/latest/mgr/orchestrator/ please take a look at this doc. @capfzgs

**Comment by capfzgs** [comment]
> it's inconvenient. Please give me your email and I will invite you to the slack.


554450306@qq.com

**Comment by capfzgs** [comment]
> because of your ceph cluster was deployed by cephadm, so I think you can run:
> 
> ```
> ceph orch set backend cephadm
> ceph orch status
> ```
> 
> and show me the results.

[root@node01 ~]# ceph orch set backend cephadm
Error EINVAL: Module 'cephadm' not found
[root@node01 ~]# ceph orch status
Error ENOENT: No orchestrator configured (try `ceph orch set backend`)
[root@node01 ~]#

**Comment by zhucan** [comment]
https://app.slack.com/huddle/T47C56S7Q/CK9CF5H2R @capfzgs join it.

**Comment by zhucan** [comment]
@\\

> > because of your ceph cluster was deployed by cephadm, so I think you can run:
> > ```
> > ceph orch set backend cephadm
> > ceph orch status
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and show me the results.
> 
> [root@node01 ~]# ceph orch set backend cephadm Error EINVAL: Module 'cephadm' not found [root@node01 ~]# ceph orch status Error ENOENT: No orchestrator configured (try `ceph orch set backend`) [root@node01 ~]#

I'm so sorry, you don't use rook and cephadm to deploy the ceph cluster. so you can not set backend with rook and cephadm. @capfzgs

**Comment by zhucan** [comment]
` ceph mgr module enable rook` output is?

**Comment by capfzgs** [comment]
> https://app.slack.com/huddle/T47C56S7Q/CK9CF5H2R @capfzgs join it.

Looks like my email can't join in this channel,can you help on this,Thanks

**Comment by zhucan** [comment]
Maybe you need to register a new email for it

**Comment by rkachach** [comment]
@capfzgs what ceph version are you using?

```
ceph mgr module disable rook
 ceph mgr module enable rook --force
 ceph orch set backend rook
 ceph orch status
```
