### ISSUE TITLE
Node Selector Issue on MONs and OSD after all the storage nodes reconciled in the cluster

### ISSUE THREAD

**Issue by kadasatya** [rook/rook#12757]
We have host based cluster with 3 mons and 3 osds.  When we do k8s cert renewal, and 3 storage nodes are deleted and replaced with new nodes. At this time, the mon pods, osd pods go into pending state. upon investigation we found that the node selector is still pointing to old nodes , after editing the node selector, mon pods came up, however after this OSD pods went into crashloopbackoff state.

We came to know that If we replaced the nodes for all three mons, the mon data store on disk under dataDirHostPath (default is /var/lib/rook) would be lost. The mons can't come back up unless you can restore that data from the old nodes.

As a design control, to restore mon data, we moved the /var/lib/rook folder to another disk instead of OS disk. For this we created additional disk with 5GB (which is recommended size rook-ceph documentation) and mounting the disk on every nodes recreation. We are doing the following

- Creating additional 5GB and using this disk to store /var/lib/rook. So, now rook folder is created under /rookdatastore and pointing this to dataDirHostPath: /rookdatastore/rook
- mounting the same disk on every new node recreation

Even after restoring mon and osd data,  MONs and OSDs are in pending state. As a workaround we did the following

- patched mon deployments with latest nodes
- patched rook-ceph-mon-endpoints configmap with latest nodes
- deleted osd deployments
- restarted operator

After the above steps, MONs and OSDs are up and running.  

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
Operator must update the following

1. MON and OSD deployments with latest nodes
2. rook-ceph-mon-endpoints configmap with latest nodes

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by zhucan** [comment]
If you replace the mon one by one, I don't think the data will be lose.

**Comment by kadasatya** [comment]
> If you replace the mon one by one, I don't think the data will be lose.

we are replacing nodes one by one. I will reconfirm this.

**Comment by travisn** [comment]
If you're in an environment where nodes are being replaced, it's recommended to use the [cluster-on-pvc](https://rook.io/docs/rook/latest/CRDs/Cluster/pvc-cluster/) approach so that mons and OSDs can be portable between nodes.
