### ISSUE TITLE
Build variables cause CRDs to be modified unexpectedly locally in dev env

### ISSUE THREAD

**Issue by travisn** [rook/rook#12765]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
During a local developer build, `make build` leaves two files in a modified state where:
1. The descriptions are stripped from the CRDs
2. The OB and OBC CRDs are removed from the CRDs

These two files:
```
modified:   deploy/charts/rook-ceph/templates/resources.yaml
modified:   deploy/examples/crds.yaml
```

This is caused by these two variables, which were introduced by #11668 (later updated by #11724):
```
build.common: export NO_OB_OBC_VOL_GEN=true
build.common: export MAX_DESC_LEN=0
```

Commenting out these variables allows `make build` to complete without modifying the CRDs.

@subhamkrai Why are these needed in the `build.common` variables? Aren't they only needed for csv generation, which is triggered by `make csv` (specified [here](https://github.com/rook/rook/blob/master/Makefile#L185-L186))? I know at least I've been working around this issue for months, and finally we should fix it. Perhaps it only affects arm64 builds? Otherwise, I thought more devs would complain about it.

**Expected behavior:**
`make build` should not leave any files in a modified state unless they are expected to be committed.

**How to reproduce it (minimal and precise):**

`make build`

**Comment by subhamkrai** [comment]
@travisn hmm, I have not seen anyone mentioning this before and also our CI has been green.

@BlaineEXE @sp98 @parth-gr I think you all also using mac for rook build, do you also get this issue?

**Comment by BlaineEXE** [comment]
Yes, I have been experiencing this for quite some time. My semi-educated guess from past experience is that the issue is likely related to the CSV generation. I've been hopeful that kicking the CSV gen processes out of the codebase might help resolve that for me.

**Comment by travisn** [comment]
I suspect this issue will hit all builds where the csv generation is skipped, or in other words where this message is printed:
```
NOT INCLUDING OLM/CSV TEMPLATES!
```
Adding this condition around those two vars is a hack for me locally, but that doesn't feel like the right fix:
```
ifneq ($(REAL_HOST_PLATFORM),darwin_arm64)
build.common: export NO_OB_OBC_VOL_GEN=true
build.common: export MAX_DESC_LEN=0
endif
```
