### ISSUE TITLE
Mon pod do not get into quorum with the rest of the cluster, gets killed by operator

### ISSUE THREAD

**Issue by zoliben** [rook/rook#12768]
* Bug Report
During normal operations, I have encountered an issue with a rook cluster with a quorum of 5, where one of the mon pods got killed because of OOM, but after restart, it does not get into quorum and then gets killed by the operator. A new (6th) mon pod gets started, but it also doesn't get into quorum, and after the addition times out, it does not get killed but stays around, while the initial mon pod is started again.

**Deviation from expected behavior:**
Killed mon pod does not restart, complains of slow ops and gets killed by the operator.

**Expected behavior:**
When one of the mon pods is killed, a new one is started and gets into quorum.

**How to reproduce it (minimal and precise):**
Kill one of the mon pods.

**Logs to submit**:

List of mon pods (quorum is set to 5, mon-cd gets created and killed constantly, while mon-ch is created after the first mon-cd is killed by the operator:
rook-ceph-mon-cb-d465fdf95-bx5ls                                  1/1     Running   0          82d  
rook-ceph-mon-cd-8669567f94-scb4x                                 1/1     Running   0          22s  
rook-ceph-mon-ce-cb7cf6865-s2vws                                  1/1     Running   0          27d  
rook-ceph-mon-cf-5cf9b4f44c-xqc99                                 1/1     Running   0          27d  
rook-ceph-mon-cg-545fc8b899-nrq2m                                 1/1     Running   0          11d  
rook-ceph-mon-ch-84c4cbbcd4-gn9h7                                 1/1     Running   0          4d22h

* Operator's logs, if necessary
* 
2023-08-22 11:13:48.275533 W \| op-mon: failed to find initial monitor ch in mon map
Tue, Aug 22 2023 1:13:48 pm | 2023-08-22 11:13:48.275554 W \| op-mon: monitor ch is not in quorum list
Tue, Aug 22 2023 1:13:53 pm | 2023-08-22 11:13:53.295448 I \| op-mon: mons running: [ch]
Tue, Aug 22 2023 1:13:54 pm | 2023-08-22 11:13:54.091950 W \| op-mon: failed to find initial monitor ch in mon map
Tue, Aug 22 2023 1:13:54 pm | 2023-08-22 11:13:54.091980 W \| op-mon: monitor ch is not in quorum list
Tue, Aug 22 2023 1:13:54 pm | 2023-08-22 11:13:54.106793 I \| op-mon: scaling the mon "cd" deployment to replica 1
Tue, Aug 22 2023 1:13:54 pm | 2023-08-22 11:13:54.128292 E \| op-mon: failed to failover mon "cd". failed to start new mon ch: failed to wait for mon quorum: exceeded max retry count waiting for monitors to reach quorum
Tue, Aug 22 2023 1:13:54 pm | 2023-08-22 11:13:54.128323 I \| op-mon: checking for orphaned mon resources
Tue, Aug 22 2023 1:13:54 pm | 2023-08-22 11:13:54.128335 I \| op-mon: skipping check for orphaned mon pvcs since using the host path
Tue, Aug 22 2023 1:14:39 pm | 2023-08-22 11:14:39.972530 W \| op-mon: mon "cd" NOT found in quorum and timeout exceeded, mon will be failed over
Tue, Aug 22 2023 1:14:39 pm | 2023-08-22 11:14:39.972559 I \| op-mon: Failing over monitor "cd"
Tue, Aug 22 2023 1:14:39 pm | 2023-08-22 11:14:39.979144 I \| op-mon: scaling the mon "cd" deployment to replica 0
Tue, Aug 22 2023 1:14:39 pm | 2023-08-22 11:14:39.992817 I \| op-mon: starting new mon: &{ResourceName:rook-ceph-mon-ch DaemonName:ch PublicIP: Port:6789 DataPathMap:0xc001bd28d0}
Tue, Aug 22 2023 1:14:40 pm | 2023-08-22 11:14:40.022207 I \| op-mon: deployment for mon rook-ceph-mon-ch already exists. updating if needed
Tue, Aug 22 2023 1:14:40 pm | 2023-08-22 11:14:40.046016 I \| op-k8sutil: deployment "rook-ceph-mon-ch" did not change, nothing to update
Tue, Aug 22 2023 1:14:40 pm | 2023-08-22 11:14:40.046052 I \| op-mon: waiting for mon quorum with [ch]
Tue, Aug 22 2023 1:14:40 pm | 2023-08-22 11:14:40.055369 I \| op-mon: mons running: [ch]
Tue, Aug 22 2023 1:14:40 pm | 2023-08-22 11:14:40.907282 I \| op-mon: Monitors in quorum: [cb ce cf cg]

* Output of ceph status:
  cluster:
    id:     fd1aa4cf-a87b-4d29-b45d-009baf6142ec
    health: HEALTH_WARN
            1/5 mons down, quorum cb,ce,cf,cg
 
  services:
    mon: 5 daemons, quorum cb,ce,cf,cg (age 6d), out of quorum: cd
    mgr: a(active, since 3h)
    osd: 15 osds: 15 up (since 21h), 15 in (since 11d)
 
  data:
    pools:   3 pools, 161 pgs
    objects: 211.43k objects, 766 GiB
    usage:   1.4 TiB used, 6.1 TiB / 7.5 TiB avail
    pgs:     161 active+clean
 
  io:
    client:   61 MiB/s rd, 478 KiB/s wr, 5.18k op/s rd, 40 op/s wr

* First crash of the mon-cd pod:
{
    "archived": "2023-07-19 15:12:59.426513",
    "assert_condition": "session_map.sessions.empty()",
    "assert_file": "/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/15.2.4/rpm/el8/BUILD/ceph-15.2.4/src/mon/Monitor.cc",
    "assert_func": "virtual Monitor::~Monitor()",
    "assert_line": 262,
    "assert_msg": "/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/15.2.4/rpm/el8/BUILD/ceph-15.2.4/src/mon/Monitor.cc: In function 'virtual Monitor::~Monitor()' thread 7f6e6100f700 time 2023-07-18T07:11:23.509040+0000\n/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/15.2.4/rpm/el8/BUILD/ceph-15.2.4/src/mon/Monitor.cc: 262: FAILED ceph_assert(session_map.sessions.empty())\n",
    "assert_thread_name": "ceph-mon",
    "backtrace": [
        "(()+0x12dd0) [0x7f6e55d0edd0]",
        "(gsignal()+0x10f) [0x7f6e5497770f]",
        "(abort()+0x127) [0x7f6e54961b25]",
        "(ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x1a9) [0x7f6e5820ab4d]",
        "(()+0x276d16) [0x7f6e5820ad16]",
        "(Monitor::~Monitor()+0xe52) [0x558a33193bc2]",
        "(Monitor::~Monitor()+0xd) [0x558a33193c3d]",
        "(main()+0x5661) [0x558a331263e1]",
        "(__libc_start_main()+0xf3) [0x7f6e549636a3]",
        "(_start()+0x2e) [0x558a3314fc6e]"
    ],
    "ceph_version": "15.2.4",
    "crash_id": "2023-07-18T07:11:23.511041Z_f1b73d96-eef9-4d22-9f8c-139acedc6ec2",
    "entity_name": "mon.cd",
    "os_id": "centos",
    "os_name": "CentOS Linux",
    "os_version": "8 (Core)",
    "os_version_id": "8",
    "process_name": "ceph-mon",
    "stack_sig": "5614ee01349834181c19990869a934cd459b960d250443800b648a6066e07877",
    "timestamp": "2023-07-18T07:11:23.511041Z",
    "utsname_hostname": "redactedt",
    "utsname_machine": "x86_64",
    "utsname_release": "3.10.0-1160.90.1.el7.x86_64",
    "utsname_sysname": "Linux",
    "utsname_version": "#1 SMP Thu May 4 15:21:22 UTC 2023"
}

* Second crash of the mon-cd pod:
{
    "archived": "2023-07-19 15:12:59.412881",
    "assert_condition": "session_map.sessions.empty()",
    "assert_file": "/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/15.2.4/rpm/el8/BUILD/ceph-15.2.4/src/mon/Monitor.cc",
    "assert_func": "virtual Monitor::~Monitor()",
    "assert_line": 262,
    "assert_msg": "/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/15.2.4/rpm/el8/BUILD/ceph-15.2.4/src/mon/Monitor.cc: In function 'virtual Monitor::~Monitor()' thread 7f6e6100f700 time 2023-07-18T07:11:23.509040+0000\n/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/15.2.4/rpm/el8/BUILD/ceph-15.2.4/src/mon/Monitor.cc: 262: FAILED ceph_assert(session_map.sessions.empty())\n",
    "assert_thread_name": "ceph-mon",
    "backtrace": [
        "(()+0x12dd0) [0x7f6e55d0edd0]",
        "(pthread_getname_np()+0x48) [0x7f6e55d10048]",
        "(ceph::logging::Log::dump_recent()+0x428) [0x7f6e58556e58]",
        "(()+0x4b6c1b) [0x558a333bec1b]",
        "(()+0x12dd0) [0x7f6e55d0edd0]",
        "(gsignal()+0x10f) [0x7f6e5497770f]",
        "(abort()+0x127) [0x7f6e54961b25]",
        "(ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x1a9) [0x7f6e5820ab4d]",
        "(()+0x276d16) [0x7f6e5820ad16]",
        "(Monitor::~Monitor()+0xe52) [0x558a33193bc2]",
        "(Monitor::~Monitor()+0xd) [0x558a33193c3d]",
        "(main()+0x5661) [0x558a331263e1]",
        "(__libc_start_main()+0xf3) [0x7f6e549636a3]",
        "(_start()+0x2e) [0x558a3314fc6e]"
    ],
    "ceph_version": "15.2.4",
    "crash_id": "2023-07-18T07:11:23.594307Z_cfae662c-0425-4064-bb56-2c3f765ce33e",
    "entity_name": "mon.cd",
    "os_id": "centos",
    "os_name": "CentOS Linux",
    "os_version": "8 (Core)",
    "os_version_id": "8",
    "process_name": "ceph-mon",
    "stack_sig": "7e7e314e491555efd254bc82aa1b8249c2d5565d5c2c3e048087588ea80997f9",
    "timestamp": "2023-07-18T07:11:23.594307Z",
    "utsname_hostname": "redacted",
    "utsname_machine": "x86_64",
    "utsname_release": "3.10.0-1160.90.1.el7.x86_64",
    "utsname_sysname": "Linux",
    "utsname_version": "#1 SMP Thu May 4 15:21:22 UTC 2023"
}

**Troubleshooting steps taken:**
Scaled down the operator to 0, deleted the deployments for mon-cd and mon-ch (that were not in the quorum), cleaned up the respective folders on the k8s nodes under /var/lib/rook/, scaled up the operator and waited for mon-cd to be up and running.

**Environment**:
* OS (e.g. from /etc/os-release):
CentOS Linux release 7.9.2009 (Core)
* Kernel (e.g. `uname -a`):
Linux 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
ESXi 7.0.3
* Rook version (use `rook version` inside of a Rook Pod):
1.4.4
* Storage backend version (e.g. for ceph do `ceph -v`):
15.2.4
* Kubernetes version (use `kubectl version`):
1.20.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Deployed via Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
HEALTH_WARN 1/5 mons down, quorum cb,ce,cf,cg

**Comment by travisn** [comment]
You are running Rook v1.4.4? This is very old. There have been multiple improvements to the mon failover since that release. Please follow the [Upgrade guide](https://rook.io/docs/rook/v1.12/Upgrade/rook-upgrade/) to update to a more recent release.
