### ISSUE TITLE
`mon` pods do not support `imagePullSecrets`

### ISSUE THREAD

**Issue by mjnagel** [rook/rook#12786]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** When deploying with the helm chart and using images from a private registry the `mon` pods will fail to pull images. In investigating I noticed that the `mon` pods specifically use the default service account which does not get the `imagePullSecrets` config.

**Expected behavior:** All pods should spin up using the `imagePullSecrets` either set directly in the pod or set via the service account.

**How to reproduce it (minimal and precise):** Reproduction might be difficult unless you have these images copied to a private registry somewhere. The easiest way to see the problem would be to set `imagePullSecrets` in the chart(s) when deploying and observe that the mon pods use the default service account, which does not have `imagePullSecrets` set.

**Comment by travisn** [comment]
This is related to #6673, which has had a couple attempts at setting the service account for the mons. 

Until that is implemented, hopefully this topic on [Authenticated Container Registries](https://rook.io/docs/rook/latest/Getting-Started/Prerequisites/authenticated-registry/) can help you get it working with the default service account.

**Comment by mjnagel** [comment]
@travisn awesome thanks for linking this - my github searches turned up nothing 😅 

I read through that doc and it was useful to get me going testing this out, definitely not a blocker in that regard, I'm able to patch the default SA and get started. I'll read through that other issue, I was going to take a stab at implementing but I might be in over my head 😆

**Comment by travisn** [comment]
We can likely bring back something similar to #7406, but you're right it probably won't be very simple. @parth-gr Perhaps we consider this for 1.13. At least I believe the reason it was reverted would not be an issue anymore.

**Comment by parth-gr** [comment]
Some questions in my head

Why do we directly not update the `default` SA with the registry/secrets,  and do the steps n the doc should be for https://rook.io/docs/rook/latest/Getting-Started/Prerequisites/authenticated-registry/ updating the common.yaml?

**Comment by parth-gr** [comment]
okay thanks for the inputs:)

**Comment by parth-gr** [comment]
@mjnagel yes, we have planned to come up with our next major release 1.13.

**Comment by mjnagel** [comment]
@parth-gr didn't see this make it into 1.13, just wanted to check in since this got marked as stale.
