### ISSUE TITLE
Rook can no longer auto detect the Kubelet root directory in 1.8.x

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1282]
Rook needs the kubelet root directory in order to determine where to do a global mount of devices. The global mount is then bind-mounted to the pod directory. This is consistent with how other K8s storage plugins work.

Prior to 1.8, Rook was using the `node/proxy/configz` api to determine where the root kubelet directory is. This is normally defaulted to `/var/lib/kubelet` but it can be user configurable.

As of 1.8, the autodetection of this directory doesnt work. So rook always falls back to using `/var/lib/kubelet` for the root directory. This would become an issue if an user configures kubelet to use a root directory other than the default.

The change that broke this is in https://github.com/kubernetes/kubernetes/pull/49051.

**Comment by jbw976** [comment]
This is a very similar issue to #1162, right?  Hopefully it'll be a very easy fix that is basically the same as #1255, where the kubelet root dir is added as a field to the `KubeletConfiguration` struct.

Also, I suspect the impact of this is limited because the Kubelet root dir isn't overridden by many folks, right?

**Comment by kokhang** [comment]
@jbw976 i checked the configz/ api and it is not showing there. I think there is a new way or api to get this since the change that broke was part of the new dynamic kubelet configuration feature: https://github.com/kubernetes/features/issues/281.

You are also right that not many people change the Root Directory so it probably wont have a much of an impact as the flexvolume plugin dir.

**Comment by jbw976** [comment]
Yeah, I don't see it in the upstream KubeletConfiguration type either: https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/kubelet/apis/kubeletconfig/types.go#L55

Hopefully there is a new API to get the root dir then.
