### ISSUE TITLE
User 2016 does not exist in toolbox pod 

### ISSUE THREAD

**Issue by dimm0** [rook/rook#12852]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When using the toolbox pod, user does not have home folder

**Expected behavior:**
I expect to have a user defined that I login under to the toolbox pod

**How to reproduce it (minimal and precise):**
Exec into the toolbox pod from the manifests examples folder

* Rook version (use `rook version` inside of a Rook Pod):
* v1.10.13

**Comment by travisn** [comment]
@dimm0 Sounds like you want the toolbox based on the rook operator image: [toolbox-operator-image](https://github.com/rook/rook/blob/master/deploy/examples/toolbox-operator-image.yaml) instead of the toolbox.yaml that is based off the ceph image.

**Comment by dimm0** [comment]
What's the toolbox.yaml one for?

**Comment by travisn** [comment]
Notice that the [image for toolbox.yaml](https://github.com/rook/rook/blob/master/deploy/examples/toolbox.yaml#L21) can be set to the same as for the ceph daemons in the cluster. The rook operator may have a different ceph base image than what the ceph daemons are running. It's a subtle difference and rarely important though.

**Comment by dimm0** [comment]
I'm using 1.10 version currently. I don't see the operator one there...
https://github.com/rook/rook/blob/release-1.10/deploy/examples/toolbox.yaml

**Comment by dimm0** [comment]
Can I use the 1.12 version for the toolbox for 1.10 operator?

**Comment by travisn** [comment]
> Can I use the 1.12 version for the toolbox for 1.10 operator?

Yes, it should be compatible, especially if you update the toolbox `image` to use the 1.10 image.
