### ISSUE TITLE
rook manager dashboard looking for rados gateway service with hostname:8080

### ISSUE THREAD

**Issue by mohammadfalahat** [rook/rook#12889]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

I have install latest version of rook-ceph with ceph 17.2.6, everything works fine, I configured rados gw, it works well too, but when I try to access dashboard Object Gateway menu items, It show me error:
-- The Object Gateway Service is not configured
--  Error connecting to Object Gateway

I configed secret key and access key but the problem is not related to security credentials, but the manager pod cannot even access workerhost:8080 because it resolve a public IP and port 8080 is an internal service port.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
this is the mgr container log running on worker1:

debug 2023-09-12T07:45:04.842+0000 7f07b106c700  0 [dashboard INFO rgw_client] Found RGW daemon with configuration: host=worker2, port=8080, ssl=False
debug 2023-09-12T07:45:04.858+0000 7f07b3070700  0 [dashboard INFO request] [::ffff:10.233.125.56:51492] [GET] [200] [0.043s] [admin] [577.0B] /api/summary
debug 2023-09-12T07:45:04.878+0000 7f07b58b5700  0 [dashboard INFO rgw_client] Found RGW daemon with configuration: host=worker2, port=8080, ssl=False
debug 2023-09-12T07:45:05.250+0000 7f07b106c700  0 [dashboard ERROR rest_client] RGW REST API failed GET, connection error (url=http://worker2:8080/fala/metadata/user?myself): [errno: -2] Name or service not known
debug 2023-09-12T07:45:05.250+0000 7f07b106c700  0 [dashboard ERROR rgw_client] RGW REST API cannot be reached: Name or service not known [errno -2]. Please check your configuration and that the API endpoint is accessible
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 162, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 982, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f07b082ecf8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='worker2', port=8080): Max retries exceeded with url: /fala/metadata/user?myself (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b082ecf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 398, in do_request
    url, headers=request_headers, params=params, auth=self.auth)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 548, in get
    return self.request('GET', url, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 47, in request
    return super(TimeoutRequestsSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 535, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 648, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='worker2', port=8080): Max retries exceeded with url: /fala/metadata/user?myself (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b082ecf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 417, in __init__
    self.userid = self._get_user_id(self.admin_path) if self.got_keys_from_config \
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 534, in func_wrapper
    **kwargs)
  File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 452, in _get_user_id
    response = request()
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 323, in __call__
    data, raw_content, headers)
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 500, in do_request
    ex_msg, conn_errno=errno, conn_strerror=strerror)
dashboard.rest_client.RequestException: RGW REST API cannot be reached: Name or service not known [errno -2]. Please check your configuration and that the API endpoint is accessible
debug 2023-09-12T07:45:05.254+0000 7f07b106c700  0 [dashboard INFO request] [::ffff:10.233.125.56:51500] [GET] [200] [0.421s] [admin] [85.0B] /ui-api/rgw/status
debug 2023-09-12T07:45:05.286+0000 7f07b58b5700  0 [dashboard ERROR rest_client] RGW REST API failed GET, connection error (url=http://worker2:8080/fala/metadata/user?myself): [errno: -2] Name or service not known
debug 2023-09-12T07:45:05.286+0000 7f07b58b5700  0 [dashboard ERROR rgw_client] RGW REST API cannot be reached: Name or service not known [errno -2]. Please check your configuration and that the API endpoint is accessible
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 162, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 982, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f07b6563f98>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='worker2', port=8080): Max retries exceeded with url: /fala/metadata/user?myself (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b6563f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 398, in do_request
    url, headers=request_headers, params=params, auth=self.auth)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 548, in get
    return self.request('GET', url, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 47, in request
    return super(TimeoutRequestsSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 535, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 648, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='worker2', port=8080): Max retries exceeded with url: /fala/metadata/user?myself (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f07b6563f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 417, in __init__
    self.userid = self._get_user_id(self.admin_path) if self.got_keys_from_config \
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 534, in func_wrapper
    **kwargs)
  File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 452, in _get_user_id
    response = request()
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 323, in __call__
    data, raw_content, headers)
  File "/usr/share/ceph/mgr/dashboard/rest_client.py", line 500, in do_request
    ex_msg, conn_errno=errno, conn_strerror=strerror)
dashboard.rest_client.RequestException: RGW REST API cannot be reached: Name or service not known [errno -2]. Please check your configuration and that the API endpoint is accessible
debug 2023-09-12T07:45:05.290+0000 7f07b58b5700  0 [dashboard INFO request] [::ffff:10.233.125.56:51514] [GET] [200] [0.421s] [admin] [85.0B] /ui-api/rgw/status

* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:

Kubernetes version v1.26.5

Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by falahatme** [comment]
I use Calico network plugin.

this is result for "kubectl get all -n rook-ceph" command:



root@master2:/etc# kubectl get all -n rook-ceph
NAME                                                    READY   STATUS      RESTARTS   AGE
pod/csi-cephfsplugin-75lhx                              2/2     Running     0          125m
pod/csi-cephfsplugin-7fxps                              2/2     Running     0          125m
pod/csi-cephfsplugin-kcv6g                              2/2     Running     0          125m
pod/csi-cephfsplugin-mq7c4                              2/2     Running     0          125m
pod/csi-cephfsplugin-provisioner-668dfcf95b-lllvc       5/5     Running     0          125m
pod/csi-cephfsplugin-provisioner-668dfcf95b-lpc2c       5/5     Running     0          125m
pod/csi-cephfsplugin-qhmvz                              2/2     Running     0          125m
pod/csi-cephfsplugin-v8r6t                              2/2     Running     0          125m
pod/csi-rbdplugin-clmbx                                 2/2     Running     0          125m
pod/csi-rbdplugin-m9q97                                 2/2     Running     0          125m
pod/csi-rbdplugin-provisioner-5b78f67bbb-9lhs4          5/5     Running     0          125m
pod/csi-rbdplugin-provisioner-5b78f67bbb-vgbv4          5/5     Running     0          125m
pod/csi-rbdplugin-s7x7m                                 2/2     Running     0          125m
pod/csi-rbdplugin-vtw6g                                 2/2     Running     0          125m
pod/csi-rbdplugin-w4tvh                                 2/2     Running     0          125m
pod/csi-rbdplugin-w6fn5                                 2/2     Running     0          125m
pod/rook-ceph-crashcollector-master1-648dd6894b-plj2p   1/1     Running     0          125m
pod/rook-ceph-crashcollector-master2-745b8d6757-22sgt   1/1     Running     0          125m
pod/rook-ceph-crashcollector-master3-74d6bbcb5b-txmdk   1/1     Running     0          125m
pod/rook-ceph-crashcollector-worker1-5cb75d8b58-q25dp   1/1     Running     0          124m
pod/rook-ceph-crashcollector-worker2-7df47bd4dc-skdkd   1/1     Running     0          124m
pod/rook-ceph-crashcollector-worker3-5844474bfb-2h7wk   1/1     Running     0          125m
pod/rook-ceph-mgr-a-56d8fb845b-zxrcq                    3/3     Running     0          125m
pod/rook-ceph-mgr-b-685bddd445-sfq5b                    3/3     Running     0          125m
pod/rook-ceph-mon-a-7cc9b8696-8h6tm                     2/2     Running     0          125m
pod/rook-ceph-mon-b-6854b6ccb-jqncl                     2/2     Running     0          125m
pod/rook-ceph-mon-c-69859c5c9f-db5hp                    2/2     Running     0          125m
pod/rook-ceph-mon-f-579667f569-k8nzs                    2/2     Running     0          125m
pod/rook-ceph-mon-h-7d5bfc9856-cd7pr                    2/2     Running     0          125m
pod/rook-ceph-mon-i-56f9b49bc7-qcnlf                    2/2     Running     0          125m
pod/rook-ceph-operator-d875b64b4-kjvpm                  1/1     Running     0          125m
pod/rook-ceph-osd-0-69d84db8fb-24d6d                    2/2     Running     0          125m
pod/rook-ceph-osd-1-677785758b-dlwgk                    2/2     Running     0          125m
pod/rook-ceph-osd-2-59f5f5b8f5-478bm                    2/2     Running     0          125m
pod/rook-ceph-osd-3-6b9f58f768-7v9f4                    2/2     Running     0          125m
pod/rook-ceph-osd-prepare-master1-7ggxt                 0/1     Completed   0          124m
pod/rook-ceph-osd-prepare-master2-8csnk                 0/1     Completed   0          124m
pod/rook-ceph-osd-prepare-master3-s99lm                 0/1     Completed   0          123m
pod/rook-ceph-osd-prepare-worker1-w5mr9                 0/1     Completed   0          123m
pod/rook-ceph-osd-prepare-worker2-cjdl5                 0/1     Completed   0          123m
pod/rook-ceph-osd-prepare-worker3-t6p9r                 0/1     Completed   0          123m
pod/rook-ceph-rgw-my-store-a-7494447c84-gchdv           2/2     Running     0          124m
pod/rook-ceph-tools-7cd4cd9c9c-92djb                    1/1     Running     0          125m

NAME                                             TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)             AGE
service/rook-ceph-mgr                            ClusterIP      10.233.51.66    <none>           9283/TCP            12d
service/rook-ceph-mgr-dashboard                  ClusterIP      10.233.29.191   <none>           8443/TCP            12d
service/rook-ceph-mgr-dashboard-external-https   NodePort       10.233.8.198    <none>           8443:32437/TCP      2d21h
service/rook-ceph-mon-a                          ClusterIP      10.233.57.79    <none>           6789/TCP,3300/TCP   13d
service/rook-ceph-mon-b                          ClusterIP      10.233.57.72    <none>           6789/TCP,3300/TCP   13d
service/rook-ceph-mon-c                          ClusterIP      10.233.53.207   <none>           6789/TCP,3300/TCP   13d
service/rook-ceph-mon-f                          ClusterIP      10.233.9.182    <none>           6789/TCP,3300/TCP   12d
service/rook-ceph-mon-h                          ClusterIP      10.233.55.232   <none>           6789/TCP,3300/TCP   12d
service/rook-ceph-mon-i                          ClusterIP      10.233.18.4     <none>           6789/TCP,3300/TCP   12d
service/rook-ceph-rgw-my-store                   ClusterIP      10.233.57.76    <none>           80/TCP              5d2h
service/rook-ceph-rgw-my-store-external          LoadBalancer   10.233.5.56     192.168.82.121   80:30628/TCP        4d21h

NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/csi-cephfsplugin   6         6         6       6            6           <none>          14d
daemonset.apps/csi-rbdplugin      6         6         6       6            6           <none>          13d

NAME                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/csi-cephfsplugin-provisioner       2/2     2            2           14d
deployment.apps/csi-rbdplugin-provisioner          2/2     2            2           14d
deployment.apps/rook-ceph-crashcollector-master1   1/1     1            1           3d3h
deployment.apps/rook-ceph-crashcollector-master2   1/1     1            1           12d
deployment.apps/rook-ceph-crashcollector-master3   1/1     1            1           12d
deployment.apps/rook-ceph-crashcollector-worker1   1/1     1            1           2d
deployment.apps/rook-ceph-crashcollector-worker2   1/1     1            1           12d
deployment.apps/rook-ceph-crashcollector-worker3   1/1     1            1           12d
deployment.apps/rook-ceph-mgr-a                    1/1     1            1           12d
deployment.apps/rook-ceph-mgr-b                    1/1     1            1           12d
deployment.apps/rook-ceph-mon-a                    1/1     1            1           13d
deployment.apps/rook-ceph-mon-b                    1/1     1            1           13d
deployment.apps/rook-ceph-mon-c                    1/1     1            1           13d
deployment.apps/rook-ceph-mon-f                    1/1     1            1           12d
deployment.apps/rook-ceph-mon-h                    1/1     1            1           12d
deployment.apps/rook-ceph-mon-i                    1/1     1            1           12d
deployment.apps/rook-ceph-operator                 1/1     1            1           14d
deployment.apps/rook-ceph-osd-0                    1/1     1            1           12d
deployment.apps/rook-ceph-osd-1                    1/1     1            1           12d
deployment.apps/rook-ceph-osd-2                    1/1     1            1           12d
deployment.apps/rook-ceph-osd-3                    1/1     1            1           12d
deployment.apps/rook-ceph-rgw-my-store-a           1/1     1            1           5d2h
deployment.apps/rook-ceph-tools                    1/1     1            1           14d

NAME                                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/csi-cephfsplugin-provisioner-668dfcf95b       2         2         2       14d
replicaset.apps/csi-rbdplugin-provisioner-5b78f67bbb          2         2         2       14d
replicaset.apps/rook-ceph-crashcollector-master1-648dd6894b   1         1         1       3d3h
replicaset.apps/rook-ceph-crashcollector-master2-745b8d6757   1         1         1       12d
replicaset.apps/rook-ceph-crashcollector-master3-74d6bbcb5b   1         1         1       12d
replicaset.apps/rook-ceph-crashcollector-worker1-5cb75d8b58   1         1         1       2d
replicaset.apps/rook-ceph-crashcollector-worker1-76cbf45f6d   0         0         0       47h
replicaset.apps/rook-ceph-crashcollector-worker2-7df47bd4dc   1         1         1       12d
replicaset.apps/rook-ceph-crashcollector-worker2-d78fff87c    0         0         0       12d
replicaset.apps/rook-ceph-crashcollector-worker3-5844474bfb   1         1         1       12d
replicaset.apps/rook-ceph-mgr-a-56d8fb845b                    1         1         1       3d2h
replicaset.apps/rook-ceph-mgr-a-64cb769965                    0         0         0       12d
replicaset.apps/rook-ceph-mgr-a-65968b9ffc                    0         0         0       12d
replicaset.apps/rook-ceph-mgr-a-7b9744885c                    0         0         0       12d
replicaset.apps/rook-ceph-mgr-b-685bddd445                    1         1         1       3d2h
replicaset.apps/rook-ceph-mgr-b-6dc47f9ccd                    0         0         0       12d
replicaset.apps/rook-ceph-mon-a-7cc9b8696                     1         1         1       13d
replicaset.apps/rook-ceph-mon-b-6854b6ccb                     1         1         1       13d
replicaset.apps/rook-ceph-mon-c-69859c5c9f                    1         1         1       13d
replicaset.apps/rook-ceph-mon-f-579667f569                    1         1         1       12d
replicaset.apps/rook-ceph-mon-h-7d5bfc9856                    1         1         1       12d
replicaset.apps/rook-ceph-mon-i-56f9b49bc7                    1         1         1       12d
replicaset.apps/rook-ceph-operator-59459dd8fc                 0         0         0       14d
replicaset.apps/rook-ceph-operator-d875b64b4                  1         1         1       3d2h
replicaset.apps/rook-ceph-osd-0-69d84db8fb                    1         1         1       12d
replicaset.apps/rook-ceph-osd-1-677785758b                    1         1         1       12d
replicaset.apps/rook-ceph-osd-2-59f5f5b8f5                    1         1         1       12d
replicaset.apps/rook-ceph-osd-3-6b9f58f768                    1         1         1       12d
replicaset.apps/rook-ceph-rgw-my-store-a-56b68bbf69           0         0         0       27h
replicaset.apps/rook-ceph-rgw-my-store-a-7494447c84           1         1         1       5d2h
replicaset.apps/rook-ceph-rgw-my-store-a-7bb7c88fc6           0         0         0       126m
replicaset.apps/rook-ceph-rgw-my-store-a-f4dd7c6cb            0         0         0       26h
replicaset.apps/rook-ceph-tools-7cd4cd9c9c                    1         1         1       14d

NAME                                      COMPLETIONS   DURATION   AGE
job.batch/rook-ceph-osd-prepare-master1   1/1           12s        124m
job.batch/rook-ceph-osd-prepare-master2   1/1           12s        124m
job.batch/rook-ceph-osd-prepare-master3   1/1           11s        123m
job.batch/rook-ceph-osd-prepare-worker1   1/1           8s         123m
job.batch/rook-ceph-osd-prepare-worker2   1/1           9s         123m
job.batch/rook-ceph-osd-prepare-worker3   1/1           9s         123m
root@master2:/etc#

**Comment by nizamial09** [comment]
@falahatme: this is fixed recently in the ceph dashboard, https://github.com/ceph/ceph/pull/53216 and will be available in the next release of the quincy.
