### ISSUE TITLE
s5cmd in the toolbox is downrev

### ISSUE THREAD

**Issue by anthonyeleven** [rook/rook#12883]
```
[rook@rook-ceph-tools-5ff8d58445-57hln .aws]$ /usr/local/bin/rook version
rook: v1.10.5
go: go1.18.7
[rook@rook-ceph-tools-5ff8d58445-57hln .aws]$ s5cmd version
v2.0.0-35bb2fa
```

This version lacks, for example, the `--credentials` argument.
Upstream is v2.2.1.  v2.0.0 was released 2022/07/04

Please update what's provided.

**Comment by travisn** [comment]
Should be a simple update to [S5CMD_VERSION](https://github.com/rook/rook/blob/5f509a08924c4da9ae898268e0f587e0ca1a0901/images/ceph/Makefile#L60). @parth-gr PTAL

**Comment by obnoxxx** [comment]
Thanks for assigning this to me @parth-gr ! I created an initial PR #12898  for it.
