### ISSUE TITLE
Ceph dashboard not showing stats on 18.x after upgrade

### ISSUE THREAD

**Issue by electrical** [rook/rook#12896]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Metrics are not populated
![Screenshot 2023-09-12 at 23 07 20](https://github.com/rook/rook/assets/271677/328d85bf-3617-424d-8e44-40faf89bd824)

**Expected behavior:**
In previous version we saw stats like IO throughput, traffic, etc.

**How to reproduce it (minimal and precise):**
Upgrade to ceph 18.2.x

I did see that some manager modules are not enabled like `rook` and `stats`. Not sure if these have any impact on this.

**Comment by travisn** [comment]
Duplicate of #12876?

**Comment by electrical** [comment]
> Duplicate of #12876?

Sorry, you are completely right. Closing.
