### ISSUE TITLE
Move csv generation code out of rook

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#12899]
**Is this a bug report or feature request?**
* Feature Request

Let's try to move csv generation code/script out of the rook codebase it is not used upstream any place.

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by obnoxxx** [comment]
@subhamkrai  wrote: 
> Let's try to move csv generation code/script out of the rook codebase it is not used upstream any place.

If it is not used anywhere, shouldn't we rather try and put it to use than removing it?

Is it not used for rook's entry in the  operator hub?

https://operatorhub.io/operator/rook-ceph

just a few thoughts on this request.

@travisn , @BlaineEXE , @leseb  -  what do you think?

**Comment by travisn** [comment]
The operator hub has not been updated since it was initially integrated there with Rook v1.1. Rook users just don't seem to have used it, so we haven't put effort into updating it. Unless someone can give a compelling reason to update it, it's best to remove it from Rook.
