### ISSUE TITLE
Rook v0.6.0 DiskPressure issue (filling HDDs)

### ISSUE THREAD

**Issue by bhvr-fmarceau** [rook/rook#1292]
Hello everyone,

I've been using Rook v0.6.0 for about a month and yesterday Prometheus alerted us about a DiskPressure issue on our nodes.

After verification, it appears that the "bluestore-block" file (/var/lib/rook/osdX/) uses 390GB / 453GB on one of our nodes and the disk usage is about the same on the other nodes. Still on that node, with the rest of the OS, we are using a total of 395GB / 453GB (OS only uses ~5GB). This disk space usage increase has lead to issues with Kubelet that didn't want to assign anymore pods to our nodes due to the DiskPressure alert...! To workaround this, we've changed Kubelets setting to allow nodes with less disk space to receive new pods for now...

It is important to note that we haven't recently deployed anything that should use more disk space in our Kubernetes/ Rook cluster. We only ask from Rook 4x 100GB volumes with 2 replicas (1 backup of the data) and we barely use at this time any of this space. Here's the rookctl usage information of our cluster (we have 4 nodes who each have 453GB of local storage):

```
TOTAL      USED         DATA        AVAILABLE
1.59 TiB   199.80 GiB   95.61 GiB   1.40 TiB
```

Additionally, due to the above situation, rookctl reports the following information when displaying its status:
```
OVERALL STATUS: WARNING
SUMMARY:
SEVERITY   NAME           MESSAGE
WARNING    MON_DISK_LOW   mons rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2 are low on available space
```

Now, I'm affraid that Rook/ Ceph will eventually consume more space and we'll run out of disk space. How can I limit the maximum size of the bluestore-block file?

UPDATE: As requested on Slack by The Gonsales, here's the ceph -w output:
```
$ kubectl -n rook exec -it rook-tools -- ceph -w                                                                                                                   [12:48:43]
  cluster:
    id:     9382e844-d3d3-4717-955f-9807a3babf11
    health: HEALTH_WARN
            mons rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2 are low on available space
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2
    mgr: rook-ceph-mgr1(active), standbys: rook-ceph-mgr0
    osd: 4 osds: 4 up, 4 in
 
  data:
    pools:   1 pools, 100 pgs
    objects: 25323 objects, 98016 MB
    usage:   200 GB used, 1432 GB / 1633 GB avail
    pgs:     100 active+clean
 
  io:
    client:   36163 B/s rd, 59362 B/s wr, 6 op/s rd, 13 op/s wr
 

2017-12-05 17:56:17.811683 mon.rook-ceph-mon0 [INF] mon.1 10.101.162.173:6790/0 
2017-12-05 18:00:00.000240 mon.rook-ceph-mon0 [WRN] overall HEALTH_WARN mons rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2 are low on available space
2017-12-05 18:01:17.811757 mon.rook-ceph-mon0 [INF] mon.2 10.111.26.159:6790/0 
2017-12-05 18:01:17.811829 mon.rook-ceph-mon0 [INF] mon.1 10.101.162.173:6790/0 
```

Edit by @galexrt: I have added code blocks for better readability of the snippets.

**Comment by abh** [comment]
I solved this by using block devices instead of the directories (though that led to other problems, #1305). I tried also getting the "mon osd full ratio" in the override config, but I think I'd have to clear the osd's and start over for that to (maybe?) take effect.

**Comment by galexrt** [comment]
@bhvr-fmarceau @abh What filesystem do you have under the directory/directories you experience this issue with?

**Comment by abh** [comment]
ext4, just the default CoreOS file system (I use /data/ for hostPath’s usually, so I used /data/rook-data/ for this — I was trying to make the storage stuff go in /data/rook-storage/ but with my initial config that didn’t get used).

**Comment by bhvr-fmarceau** [comment]
@galexrt ext4!

**Comment by JohnnyQQQQ** [comment]
I'm facing the same issue on ubuntu with ext4.

**Comment by galexrt** [comment]
**To document here**:
If you are using a version before v0.7, the default store type for OSDs was `bluestore`.
Bluestore won't reduce in size, as it expects either the whole device or filesystem (not recommend in general that is why the default is now dynamically in v0.7 and up) to be useable.

For users of directories with OSDs it is recommended to use `filestore` instead.

**Comment by galexrt** [comment]
I'm going to close this issue as it is as written in my previous comment a bluestore "problem" (bluestore was simply not made for being used on top of filesystems).

The default for directories since `>= v0.8` is `filestore` and devices is `bluestore`.

A fix for people in this situation would be to remove the node (as it is required with v0.7) and then recreate the node with the default/"correct" OSD store option.
