### ISSUE TITLE
External Cluster: NodeFencing creation fails due to limited permission for client.healthchecker user

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#12931]
**Is this a bug report or feature request?**
* Bug Report

When running `rbd status ...` command to get the watcher to block the IP creating network fence CR, the command fails since the user `client.healthchecker` doesn't have permission to run these types of commands.

**Deviation from expected behavior:**
NetworkFence creation fails in external mode
**Expected behavior:**
NetworkFence creation should pass in external mode.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by subhamkrai** [comment]
@parth-gr @travisn @sp98 @Madhu-1 ^^

**Comment by travisn** [comment]
How could the operator get access to the csi keyring? IIRC it is a secret, so I could see it being simple for the operator to load it. Today the operator just assumes that all commands are executed with the same keyring, so this rbd command would need to be executed separately from the normal helpers.

**Comment by Madhu-1** [comment]
Yes @travisn that's correct, from the secret in storageclass/PVC we can get the user and key and we can use that to access the rbd images

**Comment by parth-gr** [comment]
@Madhu-1 is the `"mgr": "rw"` is missing with the client.healthchecker?

**Comment by parth-gr** [comment]
I think we can give read permissions to the health checker.

**Comment by travisn** [comment]
> I think we can give read permissions to the health checker.

Would upgraded clusters also always get the permission?

**Comment by Madhu-1** [comment]
we need caps to read all images in pool for now and also we might need to read subvolumes in filesystem and also health checker should also required access to blocklist the Ip's . https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#rbd is what we have in cephcsi but we need to check what is the minimal caps for required operations

**Comment by subhamkrai** [comment]
If we update the health checker permission, the already connected will have those permission since we just run the python script only once during the cluster connection

**Comment by parth-gr** [comment]
> If we update the health checker permission, the already connected will have those permission since we just run the python script only once during the cluster connection
>Would upgraded clusters also always get the permission?

Upgraded cluster get the upgraded permissions

**Comment by subhamkrai** [comment]
> > If we update the health checker permission, the already connected will have those permission since we just run the python script only once during the cluster connection
> > Would upgraded clusters also always get the permission?
> 
> Upgraded cluster get the upgraded permissions

@Madhu-1 and @travisn so what we are planning to update?

**Comment by Madhu-1** [comment]
as it's meant for a health check as the name says my vote would be to use csi secret/user for this operation rather than adding more permission to the health check user. lets hear from @travisn what he thinks?

**Comment by travisn** [comment]
The operator was designed to work with a single keyring per ceph cluster. For a converged cluster, we use `client.admin`, and for the external cluster we of course have a less-privileged user. Perhaps it would have been better named `client.externalrook` or similar, but now we are stuck with the `client.healthchecker`. But maybe it isn't a terrible name either since it would now be checking for the health of nodes in order to fence them. 

While it's possible to use a different keyring (anything is possible in code), it's not the pattern Rook was designed for. Let's give the keyring the additional privileges. 

As a related change, I would propose that if the fencing finds it does not have privileges, it could either disable the node fencing or simply log the error and it could be ignored (and also we should not fill up the logs with this error). @subhamkrai What exactly is the behavior today if it does not have privileges in the external cluster? How verbose are the logs?

**Comment by subhamkrai** [comment]
The logs are not very verbose but with every re-reconcile we'll see the error
