### ISSUE TITLE
snyk  reports dependencies with  MPL license as vulnerabilities

### ISSUE THREAD

**Issue by obnoxxx** [rook/rook#12930]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

snyk runs after merges to master and release branches report medium severity issue warnings due to dependency projects using the MPL license. 
 
Example: https://github.com/rook/rook/actions/runs/6223395202/job/16889257921 

**Expected behavior:**
snyk  should pass without warnings and errors

**How to reproduce it (minimal and precise):**

* get a  PR merged to the master branch or a  release branch of rook.
* look for corresponding workflow runs https://github.com/rook/rook/actions?query=branch%3Amaster

**Environment**:
*  environment where this was observed: github CI 
 OS (e.g. from /etc/os-release): any
* Cloud provider or hardware configuration: any
* Rook version: current master branch
* Storage backend version ): any

* Kubernetes cluster type : any/irrelevant 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): irrelevant

**Comment by obnoxxx** [comment]
@travisn , @BlaineEXE , Possibly, we could create a snyk license  policy for rook to change the behavior?
See: https://docs.snyk.io/manage-issues/policies/license-policies/create-a-license-policy-and-rules

**Comment by travisn** [comment]
hmm, the vulnerabilities are still reported by the CI action in the [latest run with this fix](https://github.com/rook/rook/actions/runs/6302663608/job/17110310884). Perhaps we need to use the github action properties instead of the .snyk file.

**Comment by obnoxxx** [comment]
@travisn  wrote:
> hmm, the vulnerabilities are still reported by the CI action in the [latest run with this fix](https://github.com/rook/rook/actions/runs/6302663608/job/17110310884). Perhaps we need to use the github action properties instead of the .snyk file.

that is weird. the run report ends like this:


```
Organization:      travisn
Package manager:   gomodules
Target file:       go.mod
Project name:      github.com/rook/rook
Open source:       no
Project path:      /github/workspace
Local Snyk policy: found
Licenses:          enabled

Tested 805 dependencies for known issues, found 15 issues, 120 vulnerable paths.
```
why does it  say "organization: travisn" and "open source: no" ? ...

**Comment by obnoxxx** [comment]
well, I still see the original issue:
```
 Medium severity issue found in github.com/hashicorp/go-immutable-radix
  Description: MPL-2.0 license
```

etc. so the `.snyk` file does not seem to have worked quite as expected ...

**Comment by obnoxxx** [comment]
maybe this gives a clue:
https://docs.snyk.io/manage-risk/policies/the-.snyk-file


the sbyk id seems to be `snyk:lic:npm:symbol:MPL-2.0`

**Comment by travisn** [comment]
Still an issue...
