### ISSUE TITLE
Add option to operator to "tolerate" rook-agents to run on masters

### ISSUE THREAD

**Issue by abh** [rook/rook#1295]
I have the opposite request of what was done in #1168, so making it an option for the operator would be helpful.  We have some regular work loads that we allow to run on the masters, so it'd make sense to have rook-agents running there, too.

**Comment by travisn** [comment]
I believe what we want is to add an `agent` section to the `placement` element of the cluster.yaml, similar to the other daemon types. Then you can specify all the attributes desired for node and pod affinity, pod anti-affinity, and tolerations.

**Comment by kokhang** [comment]
@travisn the problem with that is that the agents are not deployed when a cluster is created. They are deployed when operator is created. Since the operator is not a CRD type (is a deployment type), we cant add custom specs.

**Comment by travisn** [comment]
ha, of course we don't have that option. So the best we can do is an env var on the operator pod that would set the toleration on the agent pod. What would we call the property? How about `AGENT_TOLERATE_NO_SCHEDULE`?

**Comment by kokhang** [comment]
@travisn i submitted a PR. I elected to have the toleration user specified. Take a look
