### ISSUE TITLE
Questions about the inconsistent results of ceph Tell and ceph config get commands?

### ISSUE THREAD

**Issue by erictarrence** [rook/rook#12953]
Why is the value of ceph tell osd.0 config get osd_recovery_max_active always 1000?

Why are the results of ceph tell osd.0 config get osd_recovery_max_active and ceph config get osd.0 osd_recovery_max_active different? Which command’s result shall prevail?

The specific relevant operation tests are as follows:

```
sh-4.4$ ceph -v
ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)


sh-4.4$  ceph tell osd.0 injectargs '--osd-max-backfills 1 --osd-recovery-max-active 1 --osd-recovery-max-single-start 1'
{}
osd_max_backfills = '1' osd_recovery_max_active = '1' 

sh-4.4$ ceph tell osd.0 config get  osd_recovery_max_active
{
    "osd_recovery_max_active": "1000"
}

sh-4.4$ ceph config get osd.0 osd_recovery_max_active
0

sh-4.4$ ceph config set osd.0 osd_recovery_max_active 1

sh-4.4$ ceph config get osd.0 osd_recovery_max_active
1

sh-4.4$ ceph tell osd.0 config get  osd_recovery_max_active
{
    "osd_recovery_max_active": "1000"
}
```

**Comment by parth-gr** [comment]
Seems like there might be bug with `ceph tell`

**Comment by erictarrence** [comment]
> ceph config set

So should I just use the ceph config set command?  and do not use the ceph tell command?

**Comment by travisn** [comment]
I believe `ceph tell` only works in daemon pods for the local daemon, and not sure if settings may be lost when the daemon is restarted. If you're using the toolbox, use `ceph config set`, which will always persist the settings.

**Comment by erictarrence** [comment]
> I believe `ceph tell` only works in daemon pods for the local daemon, and not sure if settings may be lost when the daemon is restarted. If you're using the toolbox, use `ceph config set`, which will always persist the settings.

The question now is why the results of the ceph tell osd.0 injectargs and ceph tell osd.0 config get osd_recovery_max_active commands are inconsistent?

```
sh-4.4$  ceph tell osd.0 injectargs '--osd-max-backfills 1 --osd-recovery-max-active 1 --osd-recovery-max-single-start 1'
{}
osd_max_backfills = '1' osd_recovery_max_active = '1' 

sh-4.4$ ceph tell osd.0 config get  osd_recovery_max_active
{
    "osd_recovery_max_active": "1000"
}
```
