### ISSUE TITLE
Create subvolumegroup in Rook for both External mode and internal mode

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#13040]
In cephcsi https://github.com/ceph/ceph-csi/issues/4185 we are planning to remove the subvolumegroup creation in (one or two releases) and we need some changes in Rook to adapt to the model, This issue is to discuss any concerns and track the required integration work.

cc @travisn @parth-gr

**Comment by parth-gr** [comment]
Blocks: https://github.com/rook/rook/issues/12607

**Comment by travisn** [comment]
For the design, I'm thinking we need to add the default `csi` subvolumegroup CR to the example filesystem.yaml (and helm chart), so it will be created by default whenever the filesystem is created. The admin can configure the settings on that subvolumegroup by simply changing that CR.

But what if the user chooses not to create this CR? Especially during upgrades this CR wouldn't exist. Will this not result in a broken filesystem? Does Rook need to create the default subvolumegroup when the filesystem is created even if there is no subvolumegroup CR? @Madhu-1 Is there any scenario where the default subvolumegroup should not be created by Rook?

**Comment by Madhu-1** [comment]
> For the design, I'm thinking we need to add the default `csi` subvolumegroup CR to the example filesystem.yaml (and helm chart), so it will be created by default whenever the filesystem is created. The admin can configure the settings on that subvolumegroup by simply changing that CR.
> 
> But what if the user chooses not to create this CR? Especially during upgrades this CR wouldn't exist. Will this not result in a broken filesystem? Does Rook need to create the default subvolumegroup when the filesystem is created even if there is no subvolumegroup CR? @Madhu-1 Is there any scenario where the default subvolumegroup should not be created by Rook?

I don't see any problem creating a default csi when the filesystem is created and the admin can create the subvolumegroup to override the default.

For upgraded clusters if there are cephfs PVC means the subvolumegroup is already created not a problem, one corner-case is where user created the filesystem but no cephfs PVC in that case we need to ask admin to create the group or else the cephfs PVC creation will fail

**Comment by travisn** [comment]
> I don't see any problem creating a default csi when the filesystem is created and the admin can create the subvolumegroup to override the default.

> For upgraded clusters if there are cephfs PVC means the subvolumegroup is already created not a problem, one corner-case is where user created the filesystem but no cephfs PVC in that case we need to ask admin to create the group or else the cephfs PVC creation will fail

To avoid this corner case, then Rook could always ensure the subvolumegroup is created, even if no CR. I'm understanding from your first statement that there is no problem with that.

**Comment by Madhu-1** [comment]
> > I don't see any problem creating a default csi when the filesystem is created and the admin can create the subvolumegroup to override the default.
> 
> > For upgraded clusters if there are cephfs PVC means the subvolumegroup is already created not a problem, one corner-case is where user created the filesystem but no cephfs PVC in that case we need to ask admin to create the group or else the cephfs PVC creation will fail
> 
> To avoid this corner case, then Rook could always ensure the subvolumegroup is created, even if no CR. I'm understanding from your first statement that there is no problem with that.

👍🏻

**Comment by Rakshith-R** [comment]
@parth-gr I've added code to create subvolumegroup `csi` by default too in this pr too.
It should be sufficient according to me.

https://github.com/rook/rook/pull/13327/files#diff-e7e1952f91a34f216e61da44c952c796fc630097402dd4b06a1b75274b5bb837

**Comment by parth-gr** [comment]
> @parth-gr I've added code to create subvolumegroup `csi` by default too in this pr too. It should be sufficient according to me.
> 
> https://github.com/rook/rook/pull/13327/files#diff-e7e1952f91a34f216e61da44c952c796fc630097402dd4b06a1b75274b5bb837

Added some comments

**Comment by parth-gr** [comment]
> This pr should already handle it for external mode.
> 
> #12477

Correct
