### ISSUE TITLE
Disable MDS Load Balancer "mds_bal_interval" For multiple Active MDS

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#13056]
After talking to @travisn got to know that we are not disabling the MDS load balancer [1] when we have active MDS pods, I got to know from @vshankar  that this needs to be disabled when we have active mds, and also this needs to be required for subvolumegroup pinning as well. 

@vshankar can you please confirm that we need to disable Load Balancer for this case?

cc @travisn @parth-gr 

[1] https://access.redhat.com/solutions/7026124

**Comment by vshankar** [comment]
https://github.com/ceph/ceph/pull/52196 - will disable the mds balancer by default.

**Comment by Madhu-1** [comment]
> Multiple MDS is not the default in Rook, so I imagine this issue would not commonly be hit. If this will be the default soon, shall we just wait for the fix? Or is the performance issue serious enough that we should look at enabling it for versions of ceph that don't have the fix?

The KCS i linked about says we might get into a performance issue if not disabled. depending on the ceph version, we can disable it when 2 active mds have or just provide a doc link to the user to disable it in the yaml file.

**Comment by vshankar** [comment]
> > Multiple MDS is not the default in Rook, so I imagine this issue would not commonly be hit. If this will be the default soon, shall we just wait for the fix? Or is the performance issue serious enough that we should look at enabling it for versions of ceph that don't have the fix?
> 
> The KCS i linked about says we might get into a performance issue if not disabled. depending on the ceph version, we can disable it when 2 active mds have or just provide a doc link to the user to disable it in the yaml file.

When the balancer misbehaves, it leads to huge performance degradation not only when the MDS is operational, but also during restart (due to the huge number of journal objects it has to replay which got created due to the balancer trying to migrate subtrees).
