### ISSUE TITLE
Problem with multiple ceph cluster and csi pods

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#13058]
**Is this a bug report or feature request?**
* Bug Report

This is a corner case if we have one internal ceph cluster with multus and an external ceph cluster. Today if we have a multus cluster, cephcsi will use the holder design for all the csi operators, and if we have the standard cluster cephcsi will use pod network for provisioner pod and host networking for daemonset pods. 

Support if a new ceph cluster (an external one or a ceph cluster without multus) is created in the existing setup. we might get into the problem as cephcsi will get an update to use the multus network we need to think about all the cases here

* What happens if the order of creation of the ceph cluster is changed?

If the multus ceph cluster is created first, the holder design will be used for the csi operations, and for the other cluster (non-multus) cephcsi will mount/umount the application on the normal pod network (This can lead to the series problem of downtime as the plugin pod is restarted we will lose all mounts)

if the older is changed and the multus cluster is created later point in time, cephcsi will also get updated to use the multus and if we had an existing ceph cluster before that what will happen to the already existing mounts?

* Choosing of different network configuration of csi is not possible today

We cannot say that use hostnetworking for one cluster and use multus for one cluster in the cephcsi

There could be other cases as well, will keep updating if i find one later.

cc @travisn @BlaineEXE

**Comment by travisn** [comment]
For whether to use the holder design or host networking, can this be a setting that moves into the cluster settings? The CSI driver then could choose whether to use the holder or not based on that cluster setting, if both methods could co-exist. I understand this is not possible today with the csi driver, but do you see that as a possible design change? We have other cluster-specific settings in the csi configmap, could this also be one?

**Comment by Madhu-1** [comment]
> For whether to use the holder design or host networking, can this be a setting that moves into the cluster settings? 

Yes can be done but we have only a single csi driver and we cannot run both pod network and host network.

>The CSI driver then could choose whether to use the holder or not based on that cluster setting, if both methods could co-exist. I understand this is not possible today with the csi driver, but do you see that as a possible design change? We have other cluster-specific settings in the csi configmap, could this also be one?

Currently i don't see a way with single csi driver but need to think about it for a while now.
