### ISSUE TITLE
Ceph mds reports slow requests

### ISSUE THREAD

**Issue by paramjeet01** [rook/rook#13059]
Hi,

I have multiple clients connecting to Ceph using the kernel driver. Sometimes, I encounter slow requests errors and health warnings on the Ceph dashboard. The issue seems to be resolved when I rotate the MDS pods. To delve deeper into this problem, I'm attaching the pod logs related to the 'rdlock error.'

```
debug 2023-10-17 05:12:52.602 7f1b7590b700  0 log_channel(cluster) log [WRN] : 
slow request 32.637299 seconds old, received at 2023-10-17 05:12:19.969442: 
client_request(client.1454853:16744660 getattr pAsLsXsFs #0x1001e7a95b1 
2023-10-17 05:12:19.963884 caller_uid=0, caller_gid=0{}) currently failed to rdlock, 
waiting
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian-19
* Kernel (e.g. `uname -a`):  4.9.0-19-amd64
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): v1.0.6
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.5 
* Kubernetes version (use `kubectl version`): v1.17.12
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): KOPS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):  HEALTH_WARN

**Comment by parth-gr** [comment]
Why are you using such a old version of rook?

Which pod logs are this, can you be more specific on telling on what are the errors on the dashboard

**Comment by paramjeet01** [comment]
In the dashboard, I occasionally encounter health_warn messages, and the error logs originate from the MDS servers.

**Comment by travisn** [comment]
@paramjeet01 Please review the [upgrade guide](https://rook.io/docs/rook/latest/Upgrade/rook-upgrade/#supported-versions) to update to a more recent version. It is difficult to troubleshoot such an old version.

**Comment by paramjeet01** [comment]
Planning to upgrade to new version.

**Comment by aisensiy** [comment]
I got similar issues in rook `1.11`.

![image](https://github.com/rook/rook/assets/661860/8f0ed014-8ae8-4048-8e5d-7d3a5a268344)

This is more likely a problem of ceph itself and it seems that a `rdlock` is never released. 

Environment:

- OS (e.g. from /etc/os-release): Ubunut-22.04
- Kernel (e.g. uname -a): Linux stor3 5.15.0-97-generic
- Cloud provider or hardware configuration: Bare Metal
- Rook version (use rook version inside of a Rook Pod): v1.11.10
- Storage backend version (e.g. for ceph do ceph -v): 17.2.6
- Kubernetes version (use kubectl version): v1.26.9
- Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): KubeAdam Setup
- Storage backend status (e.g. for Ceph use ceph health in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_WARN

**Comment by aisensiy** [comment]
@travisn Hope if there is some info about my issue.

**Comment by travisn** [comment]
@aisensiy Are you setting the [memory limits](https://rook.io/docs/rook/latest/CRDs/Shared-Filesystem/ceph-filesystem-crd/#mds-resources-configuration-settings) for MDS? Not sure if this is related to your issue, but the MDS can be memory hungry and should have at least 4GB memory.

**Comment by aisensiy** [comment]
Yes. Here is the usage from metrics:

```
$ kubectl top pods -n rook-ceph | grep mds

rook-ceph-mds-myfs-a-697c4887f6-lthlt                 538m         34755Mi
rook-ceph-mds-myfs-b-76f5d85f74-qxkkp                 322m         70815Mi
rook-ceph-mds-myfs-c-666b4794c4-5xt7r                 1240m        37057Mi
rook-ceph-mds-myfs-d-97fb4f8f7-gknb9                  1574m        73414Mi
rook-ceph-mds-myfs-e-57f94b889b-7fmgl                 542m         12275Mi
rook-ceph-mds-myfs-f-cd648c7b7-pb48q                  30m          11251Mi
```

**Comment by travisn** [comment]
Ok, looks like plenty of memory. The best I can do is refer to the [Ceph MDS troubleshooting guide](https://docs.ceph.com/en/reef/cephfs/troubleshooting/#slow-requests).

**Comment by bumarcell** [comment]
Sorry to post here after this issue was closed, but we're experiencing the same problem on Rook v1.14.5 and Ceph v17.2.7 with (many) kernel clients (v6.6.30)

I read the [Ceph MDS](https://docs.ceph.com/en/quincy/cephfs/troubleshooting/#slow-requests) troubleshooting guide but it didn't get me any further. Thought I would share it here maybe there are some new insights regarding this 🙏
