### ISSUE TITLE
Adding a new OSD to cluster takes a lot time

### ISSUE THREAD

**Issue by gagareg** [rook/rook#13073]
**Is this a bug report or feature request?**
* Bug Report

Hello, when I add a new OSD to cluster, it takes about 10 minutes. We see different errors in logs, but **the solution was not ordinary - increasing time for ceph Commands Timeout Seconds to 180 seconds**.

**Deviation from expected behavior:**
It should take less time

**Logs to submit**:

* Operator's logs, if necessary
```
failed to reconcile CephFilesystem "rook-ceph/ceph-filesystem". failed to create filesystem "ceph-filesystem": failed to start deployment for MDS "a" for filesystem "ceph-filesystem": failed to create mds deployment rook-ceph-mds-ceph-filesystem-a: client rate limiter Wait returned an error: context canceled

failed to reconcile CephFilesystem "rook-ceph/ceph-filesystem". failed to create filesystem "ceph-filesystem": failed to create filesystem "ceph-filesystem": failed to set pools size: failed to update datapool "ceph-filesystem-data0": failed to create replicated crush rule "ceph-filesystem-data0": failed to create crush rule ceph-filesystem-data0: context canceled

failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to set Rook and/or user-defined Ceph config options after forcefully updating the existing mons: failed to apply default Ceph configurations: failed to set all keys: failed to set ceph config in the centralized mon configuration database; output: Interrupted: exit status 4

failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to execute post actions after all the ceph monitors started: failed to configure msgr2: failed to delete msgr2 encryption settings: failed to delete one or more Ceph configs: failed to delete ceph config in the centralized mon configuration database. output: Interrupted: exit status 4: failed to delete ceph config in the centralized mon configuration database. output: Interrupted: exit status 4: failed to delete ceph config in the centralized mon configuration database. output: Interrupted: exit status 4

failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to set Rook and/or user-defined Ceph config options after forcefully updating the existing mons: failed to apply default Ceph configurations: failed to set all keys: failed to set ceph config in the centralized mon configuration database; output: Interrupted Traceback (most recent call last): File "/usr/bin/ceph", line 1326, in <module> retval = main() File "/usr/bin/ceph", line 1272, in main outf.write(outbuf) TypeError: a bytes-like object is required, not 'str': exit status 1

failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to execute post actions after all the ceph monitors started: failed to configure msgr2: failed to delete msgr2 encryption settings: failed to delete one or more Ceph configs: failed to delete ceph config in the centralized mon configuration database. output: : signal: interrupt: failed to delete ceph config in the centralized mon configuration database. output: Interrupted: exit status 4

failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to execute post actions after all the ceph monitors started: failed to configure msgr2: failed to delete msgr2 encryption settings: failed to delete one or more Ceph configs: failed to delete ceph config in the centralized mon configuration database. output: Interrupted: exit status 4: failed to delete ceph config in the centralized mon configuration database. output: Cluster connection aborted: exit status 1
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
GOOGLE_CRASH_ID=Lakitu
KERNEL_COMMIT_ID=49bc994351b9c898076f2d1e9a5d0565c5152de8
VERSION=101
VERSION_ID=101
BUILD_ID=17162.210.18
```

* Kernel (e.g. `uname -a`): 
```
Linux gke-ids-infra-gcp-runner-spot-pool-1f44d50a-5cvq 5.15.107+ #1 SMP Sat May 20 09:38:40 UTC 2023 x86_64 AMD EPYC 7B12 AuthenticAMD GNU/Linux
```
* Storage backend version (e.g. for ceph do `ceph -v`): 
```
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
```
* Kubernetes version (use `kubectl version`): v1.26.5-gke.2100
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by travisn** [comment]
@gagareg All those errors in your operator log appear that there was an issue with the mon quorum, and causing the long delays and times. 
- Was the cluster healthy before you tried to add the OSDs? `ceph status`
- Any cluster health issues now, any pods crash looping, etc?
- Can you share the full operator log?

**Comment by gagareg** [comment]
- Cluster was healthy
- No issue found. Only logs above
- Unfortunately now I have no more logs

**Comment by BlaineEXE** [comment]
Adding an OSD will almost always cause data rebalancing as Ceph's data shards are moved around within the placement groups. That data rebalancing can have many, many affects in the cluster.

Firstly, this requires all OSDs to do more work to find and move data they are in charge of. If your environment is already pushing the edges of CPU/memory usage, this increase in OSD usage could cause mons to have less CPU/memory available, destabilizing them.

The other likely factor is the network bandwidth available, especially if you only have 1 gigabit network links. When data moves around in the ceph cluster, that movement can starve out other applications that need to communicate on the network. That goes especially for the ceph mons that also need low-latency networking to remain stable with each other.

Another factor that is less likely could be disk controllers on nodes. Mons require fast SSD or better storage to be stable, so OSDs doing a lot of rebalancing through a cheap disk controller that is shared by the mon's disk can affect mon stability also.

**Comment by gagareg** [comment]
> Adding an OSD will almost always cause data rebalancing as Ceph's data shards are moved around within the placement groups. That data rebalancing can have many, many affects in the cluster.
> 
> Firstly, this requires all OSDs to do more work to find and move data they are in charge of. If your environment is already pushing the edges of CPU/memory usage, this increase in OSD usage could cause mons to have less CPU/memory available, destabilizing them.
> 
> The other likely factor is the network bandwidth available, especially if you only have 1 gigabit network links. When data moves around in the ceph cluster, that movement can starve out other applications that need to communicate on the network. That goes especially for the ceph mons that also need low-latency networking to remain stable with each other.
> 
> Another factor that is less likely could be disk controllers on nodes. Mons require fast SSD or better storage to be stable, so OSDs doing a lot of rebalancing through a cheap disk controller that is shared by the mon's disk can affect mon stability also.

It was a test cluster there was no data and loads at all on it. We use **standard-rwo** disk in gcp.

**Comment by robwithhair** [comment]
We are having this same issue.  Getting an error like the following:
```
default Ceph configurations: failed to set all keys: failed to set ceph config in the centralized mon configuration database; output: Interrupted
Traceback (most recent call last):
  File "/usr/bin/ceph", line 1327, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1273, in main
    outf.write(outbuf)
TypeError: a bytes-like object is required, not 'str': exit status 1
```
Is this a bug in the operator?

**Comment by travisn** [comment]
@robwithhair What issue is the same? You can't add OSDs or it is taking a long time? 

That error you shared indicates a ceph health issue. What does `ceph status` show? Any mons down?

**Comment by robwithhair** [comment]
Apologies, not enough info from me. We are having issues with our Mon starting but seeing this same log message in the logs. By the nature of the log message I assumed it was a bug but if not then maybe message could do with a bit of additional info to explain it is an expected message?

**Comment by travisn** [comment]
Are the mons not forming quorum in a new cluster? Or it's an existing cluster where the mons are having issues? Typically, mon quorum issues are related to a networking config or issues.

**Comment by robwithhair** [comment]
Mons stuck on 100% cpu and not starting after initial cluster install.  Apparently this is due to systemd upgrade and the number of open file handles --ulimit. Looks like it may be unrelated to the error message above and coincidental. So if the error message is expected in normal operation pls ignore.
