### ISSUE TITLE
csi-* image problem in the install

### ISSUE THREAD

**Issue by okdadmin** [rook/rook#13109]
My environment is okd4.10 and I want to install rook+ceph sds.
My problemis imagepullbackoff some image:

[root@admin.okdtst :]$ oc get pods -n rook-ceph
NAME                                                              READY   STATUS             RESTARTS   AGE
csi-cephfsplugin-44q9k                                            1/2     ImagePullBackOff   0          18h
csi-cephfsplugin-hh2zp                                            1/2     ImagePullBackOff   0          18h
csi-cephfsplugin-provisioner-6b9976c8bf-52g92                     1/5     ImagePullBackOff   0          18h
csi-cephfsplugin-provisioner-6b9976c8bf-lnrf5                     1/5     ImagePullBackOff   0          18h
csi-cephfsplugin-xn74r                                            1/2     ImagePullBackOff   0          18h
csi-rbdplugin-4vh44                                               1/2     ImagePullBackOff   0          18h
csi-rbdplugin-bxlp9                                               1/2     ImagePullBackOff   0          18h
csi-rbdplugin-provisioner-7fbb7d97f5-4r6sc                        1/5     ImagePullBackOff   0          18h
csi-rbdplugin-provisioner-7fbb7d97f5-srrnk                        1/5     ImagePullBackOff   0          18h
csi-rbdplugin-qmfkk                                               1/2     ImagePullBackOff   0          18h
rook-ceph-crashcollector-master1.okdtst.mav.hu-544fdb8d4d-9h4w2   1/1     Running            0          18h
rook-ceph-crashcollector-master2.okdtst.mav.hu-7c49778fbf-m9wkn   1/1     Running            0          18h
rook-ceph-crashcollector-master3.okdtst.mav.hu-58cd4464f8-qhtxn   1/1     Running            0          18h
rook-ceph-mgr-a-58ff5ff785-b445q                                  3/3     Running            0          18h
rook-ceph-mgr-b-595fc8fc86-sdtk8                                  3/3     Running            0          18h
rook-ceph-mon-a-756bfcd4fb-96xcq                                  2/2     Running            0          18h
rook-ceph-mon-b-865bd45646-slw6w                                  2/2     Running            0          18h
rook-ceph-mon-c-7f86f77d7b-72v7r                                  2/2     Running            0          18h
rook-ceph-operator-748cc68df7-2wfpg                               1/1     Running            0          18h
rook-ceph-osd-0-74977c94fd-8pf69                                  2/2     Running            0          18h
rook-ceph-osd-1-7b944bb474-ffxb8                                  2/2     Running            0          18h
rook-ceph-osd-2-7975bd9c4c-4q6pc                                  2/2     Running            0          18h
rook-ceph-osd-prepare-master1.okdtst.mav.hu-gld44                 0/1     Completed          0          18h
rook-ceph-osd-prepare-master2.okdtst.mav.hu-bgz92                 0/1     Completed          0          18h
rook-ceph-osd-prepare-master3.okdtst.mav.hu-sj2lb                 0/1     Completed          0          18h

oc describe pod -n rook-ceph csi-cephfsplugin-44q9k:

Events:
  Type    Reason   Age                     From     Message
  ----    ------   ----                    ----     -------
  Normal  Pulling  13m (x216 over 18h)     kubelet  Pulling image "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0"
  Normal  BackOff  2m57s (x4810 over 18h)  kubelet  Back-off pulling image "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0"

I checked image url in web:
404 page not found

How can I install rook+ceph?

THX
Laci

**Comment by Madhu-1** [comment]
```
docker pull registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
v2.8.0: Pulling from sig-storage/csi-node-driver-registrar
10f855b03c8a: Pull complete 
fe5ca62666f0: Pull complete 
fff4e558ad3a: Pull complete 
fcb6f6d2c998: Pull complete 
e8c73c638ae9: Pull complete 
1e3d9b7d1452: Pull complete 
4aa0ea1413d3: Pull complete 
7c881f9ab25e: Pull complete 
5627a970d25e: Pull complete 
ffcc01337651: Pull complete 
Digest: sha256:f6717ce72a2615c7fbc746b4068f788e78579c54c43b8716e5ce650d97af2df1
Status: Downloaded newer image for registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
```

i can pull the image.

**Comment by Madhu-1** [comment]
i think you might have some problem connecting to `registry.k8s.io` please try to pull the images manually on any one of the node and see if it works.

**Comment by okdadmin** [comment]
OKD4.10 and use CRI-O.

journal log:
[core@master1 ~]$ journalctl -b -f -u crio.service
Oct 26 09:53:06 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:06.599080267+02:00" level=info msg="Checking image status: registry.k8s.io/sig-storage/csi-resizer:v1.8.0" id=cdc0080d-bee6-4050-a18c-5542183fb769 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:06 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:06.599344331+02:00" level=info msg="Image registry.k8s.io/sig-storage/csi-resizer:v1.8.0 not found" id=cdc0080d-bee6-4050-a18c-5542183fb769 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:06 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:06.600044573+02:00" level=info msg="Checking image status: registry.k8s.io/sig-storage/csi-attacher:v4.3.0" id=c84836b7-ea55-4257-b4f9-734836655f4e name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:06 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:06.600300993+02:00" level=info msg="Image registry.k8s.io/sig-storage/csi-attacher:v4.3.0 not found" id=c84836b7-ea55-4257-b4f9-734836655f4e name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:06 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:06.600745517+02:00" level=info msg="Checking image status: registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2" id=940f2609-360b-4334-911e-d7f84262ccb5 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:06 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:06.601088252+02:00" level=info msg="Image registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2 not found" id=940f2609-360b-4334-911e-d7f84262ccb5 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:08 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:08.600065265+02:00" level=info msg="Checking image status: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0" id=7a3003d5-35dd-47fd-a79e-44315fe1cffc name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:08 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:08.600376801+02:00" level=info msg="Image registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0 not found" id=7a3003d5-35dd-47fd-a79e-44315fe1cffc name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:13 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:13.598264680+02:00" level=info msg="Checking image status: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0" id=8b47c39f-5cfe-4529-9d75-c5c9e1f074e7 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:13 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:13.598580341+02:00" level=info msg="Image registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0 not found" id=8b47c39f-5cfe-4529-9d75-c5c9e1f074e7 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:16 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:16.605317981+02:00" level=info msg="Checking image status: registry.k8s.io/sig-storage/csi-attacher:v4.3.0" id=726f9638-1866-453d-a3d5-6123e7e754dd name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:16 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:16.605818430+02:00" level=info msg="Image registry.k8s.io/sig-storage/csi-attacher:v4.3.0 not found" id=726f9638-1866-453d-a3d5-6123e7e754dd name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:16 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:16.606642720+02:00" level=info msg="Checking image status: registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2" id=5489f420-4fc6-4e8c-9b7b-328599f328d8 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:16 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:16.607101807+02:00" level=info msg="Image registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2 not found" id=5489f420-4fc6-4e8c-9b7b-328599f328d8 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:16 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:16.608524670+02:00" level=info msg="Checking image status: registry.k8s.io/sig-storage/csi-resizer:v1.8.0" id=c09d2d79-2861-4cba-8aa6-4232d65a9720 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:16 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:16.609093050+02:00" level=info msg="Image registry.k8s.io/sig-storage/csi-resizer:v1.8.0 not found" id=c09d2d79-2861-4cba-8aa6-4232d65a9720 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:16 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:16.610268324+02:00" level=info msg="Checking image status: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0" id=0de06aae-accb-4dcb-8793-b3e7d44ab686 name=/runtime.v1.ImageService/ImageStatus
Oct 26 09:53:16 master1.okdtst.mav.hu crio[2532]: time="2023-10-26 09:53:16.611606256+02:00" level=info msg="Image registry.k8s.io/sig-storage/csi-provisioner:v3.5.0 not found" id=0de06aae-accb-4dcb-8793-b3e7d44ab686 name=/runtime.v1.ImageService/ImageStatus

**Comment by Madhu-1** [comment]
As am able to pull the image (like others) it should be an issue with your environment.  Not able to help much on this one.

**Comment by okdadmin** [comment]
ok, THX

**Comment by okdadmin** [comment]
My problem is proxy server. 
Can I install the rook+ceph server from the mirror repo? I mirror the necessary repos and install them, can this be solved? This way, none of the components would use a proxy server.

**Comment by dhchen** [comment]
Change image names, pointing to your mirrored registry in operator & cluster yaml file.
