### ISSUE TITLE
Add steps to upgrade toolbox pod with upgrade docs

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13102]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Document steps to upgrade toolbox pod(toolbox.yam and toolbox-operator-image.yaml) images with the upgrade docs

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
Does #13050 answer this?

**Comment by parth-gr** [comment]
Yup that fix this
