### ISSUE TITLE
Remove CPU limits from chart

### ISSUE THREAD

**Issue by alifiroozi80** [rook/rook#13117]
Hello Folks
As you know, [Using CPU limits is not a best practice.](https://home.robusta.dev/blog/stop-using-cpu-limits/)
Please remove those

**Comment by travisn** [comment]
@alifiroozi80 Are you able to work around this by customizing the values.yaml to remove the limits?

**Comment by alifiroozi80** [comment]
Hello @travisn 
Sorry that I saw it late
Do you mean Fix it myself and Contribute?

**Comment by travisn** [comment]
To test without the limits, I was suggesting you use a custom values.yaml that overrides them so they're not set in your cluster. Then separately, someone could contribute a change to remove the limits from the helm chart.
