### ISSUE TITLE
Too low memory limits for prepare pods trigger OOMKiller for ceph-osd/rook and leaving half setup OSDs

### ISSUE THREAD

**Issue by psarossy** [rook/rook#13120]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The default memory limits are too low for the prepare pods. The prepare jobs start up but leave newly created OSDs in a broken state, as they get created in ceph, but as near the filesystem creation they run out of memory and get OOMKilled. Hence they never get their keys or deployments set up, and get skipped every time for preparation as they have the filesystem created now. 

This is similar to #12091 which didn't get a solution so creating a new ticket.

**Expected behavior:**
OSDs get created prepared and added to the cluster.

**How to reproduce it (minimal and precise):**
Running on bare metal, with Talos OS
1. Insert a disk while running 1.12.3 to 1.12.7 and 248MiB default memory limit
2. Restart Operator
3. Watch prepare jobs start up
4. See ceph-osd and rook getting OOMKilled
5. Observe broken OSDs and weep.

I fixed it by wiping the disks and bumping the memory limit to 1GiB.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
[cluster.yaml.zip](https://github.com/rook/rook/files/13199462/cluster.yaml.zip)

**Logs to submit**:

* Crashing pod(s) logs, if necessary

The pods don't crash but exit:
<img width="1758" alt="Screenshot 2023-10-29 at 17 05 08" src="https://github.com/rook/rook/assets/207358/f40c3b0f-5f5e-4d02-b5a7-e66a700eaebc">

Host node logs show OOMKill
![CB2B1BA6-2FF3-46FC-95F8-6EFE0D60260B](https://github.com/rook/rook/assets/207358/31c56a92-ebfd-45f5-ac22-20d77ffbada1)
![FC9CC536-F357-4302-AD1E-7FE68C674A61](https://github.com/rook/rook/assets/207358/cb678164-ce8a-4669-b0c2-fcae8cacdae5)

**Cluster Status to submit**:

HEALTH_WARN due to noout being set while debugging, otherwise HEALTH_OK

**Environment**:
* OS (e.g. from /etc/os-release): [Talos OS 1.5.1](https://github.com/siderolabs/talos/releases/tag/v1.5.1)
* Kernel (e.g. `uname -a`): 6.1.46
* Cloud provider or hardware configuration: 8x R720 with 12 OSDs each
* Rook version (use `rook version` inside of a Rook Pod): 1.12.3 or 1.12.7 (tried both)
* Storage backend version (e.g. for ceph do `ceph -v`): 17.2.6
* Kubernetes version (use `kubectl version`): v1.28.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Talos
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by sp98** [comment]
@psarossy Rook has the option to adjust the requests/limits via the ceph cluster [here](https://github.com/rook/rook/blob/d34d443e0fa2fc946dd56fd2b66968380e68f449/deploy/examples/cluster.yaml#L229)

I believe that should suffice to adjust the default osd prepare pod memory.

**Comment by psarossy** [comment]
Apologies, I'm going to close this, please ignore.

This deployment was based on the deployment examples with some patches, and there were OSD memory limit issues in the past that caused them to get OOMKilled, so limits/requests were assigned by one of our admins to all of them and that patch was applied here as well.
