### ISSUE TITLE
CephCluster CR offers `monitoring.interval`, but the ServiceMonitors are hardcoded to 5s

### ISSUE THREAD

**Issue by WoodyWoodsta** [rook/rook#13159]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
If I set `monitoring.interval` to an example value of `10s`, the resulting `ServiceMonitor` resources that are created do not reflect this configuration. https://github.com/rook/rook/blob/c539fb56960cda15ae1f9c339eda88cba3de3f6a/pkg/operator/k8sutil/prometheus.go#L66 hardcodes the value of the interval field to 5 seconds.

This is problematic if you have a system `scrape_timeout` of more than 5 seconds, as prometheus does not allow the `scrape_timeout` to be greater than the `scrape_interval`.

**Expected behavior:**
Setting `monitoring.interval` should be respected in the ServiceMonitor resources.

**How to reproduce it (minimal and precise):**

Set `monitoring.interval` to anything other than `"5s"`.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```yaml
...
  monitoring:
    enabled: true
    metricsDisabled: false
    interval: 10s
...
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04.3 LTS
* Kernel (e.g. `uname -a`): 5.15.0-88-generic
* Cloud provider or hardware configuration: Baremetal
* Rook version (use `rook version` inside of a Rook Pod): v1.12.7
* Storage backend version (e.g. for ceph do `ceph -v`): v18.2.0
* Kubernetes version (use `kubectl version`): 1.28.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): N/A

**Comment by WoodyWoodsta** [comment]
@travisn @rkachach It looks like 1.12 has fixed the issue for the `mgr` service monitor, but not for the `exporter` service monitor, which is still hardcoded at "5s". I'm not 100% sure where the issue is in code this time.

**Comment by rkachach** [comment]
@WoodyWoodsta you are right, the value is also hardcoded. I'll try to fix it as well :+1:.
