### ISSUE TITLE
The NFS tests in the Smoke suite are failing consistently

### ISSUE THREAD

**Issue by travisn** [rook/rook#13151]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The NFS tests in the Smoke Suite are failing consistently since earlier this week, it seems to be in any branch/PR and not related to a specific change.

See the [CI history from recent master runs](https://github.com/rook/rook/actions/workflows/integration-tests-on-release.yaml?query=branch%3Amaster).

Here are some details from [this run](https://github.com/rook/rook/actions/runs/6745656995/job/18337891293):

```
2023-11-03 13:54:43.085032 I | installer: one of the tests failed, leaving the cluster in its bad shape for investigation
--- FAIL: TestCephSmokeSuite (1392.52s)
    --- PASS: TestCephSmokeSuite/TestARookClusterInstallation_SmokeTest (0.10s)
    --- PASS: TestCephSmokeSuite/TestBlockStorage_SmokeTest (120.93s)
    --- FAIL: TestCephSmokeSuite/TestCephNFS_SmokeTest (549.46s)
```

The error appears higher in the test log:
```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Warning  FailedScheduling        5m                   default-scheduler        0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               4m59s                default-scheduler        Successfully assigned smoke-ns/file-test to fv-az881-368
  Normal   SuccessfulAttachVolume  4m59s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-704c990e-f3b6-42b9-8c16-4451854ff360"
  Warning  FailedMount             42s (x9 over 4m35s)  kubelet                  MountVolume.SetUp failed for volume "pvc-704c990e-f3b6-42b9-8c16-4451854ff360" : rpc error: code = Internal desc = nfs: failed to mount "rook-ceph-nfs-my-nfs-a.smoke-ns.svc.cluster.local:/0001-0008-smoke-ns-0000000000000001-0c959ab8-cac6-461d-8a33-7baeddbddebd" to "/var/lib/kubelet/pods/8c375e03-b01c-4ec0-[955](https://github.com/rook/rook/actions/runs/6745656995/job/18337891293#step:4:956)d-2134f829ee91/volumes/kubernetes.io~csi/pvc-704c990e-f3b6-42b9-8c16-4451854ff360/mount" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o nolock rook-ceph-nfs-my-nfs-a.smoke-ns.svc.cluster.local:/0001-0008-smoke-ns-0000000000000001-0c[959](https://github.com/rook/rook/actions/runs/6745656995/job/18337891293#step:4:960)ab8-cac6-461d-8a33-7baeddbddebd /var/lib/kubelet/pods/8c375e03-b01c-4ec0-955d-2134f829ee91/volumes/kubernetes.io~csi/pvc-704c990e-f3b6-42b9-8c16-4451854ff360/mount
Output: mount.nfs: mounting rook-ceph-nfs-my-nfs-a.smoke-ns.svc.cluster.local:/0001-0008-smoke-ns-0000000000000001-0c959ab8-cac6-461d-8a33-7baeddbddebd failed, reason given by server: No such file or directory
 stderr: ""
  Warning  FailedMount  39s (x2 over 2m56s)  kubelet  Unable to attach or mount volumes: unmounted volumes=[csivol], unattached volumes=[csivol kube-api-access-tgt4n]: timed out waiting for the condition
2023-11-03 13:42:47.720416 I | testutil: Giving up waiting for pod file-test in namespace smoke-ns to be running
    ceph_base_file_test.go:415: 
        	Error Trace:	/home/runner/work/rook/rook/tests/integration/ceph_base_file_test.go:415
        	            				/home/runner/work/rook/rook/tests/integration/ceph_base_nfs_test.go:45
        	            				/home/runner/work/rook/rook/tests/integration/ceph_smoke_test.go:116
        	Error:      	Should be true
        	Test:       	TestCephSmokeSuite/TestCephNFS_SmokeTest
        	Messages:   	make sure file-test pod is in running state
```

**Expected behavior:**
Smoke Suite should pass.

**Comment by sp98** [comment]
from the nfs pod logs:

``` sudo lsblk --paths | awk '/14G/ || /64G/ {print $1}' | head -1

06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] fsal_put :FSAL :INFO :FSAL Ceph now unused
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/0001-0008-smoke-ns-0000000000000001-cf38241d-0089-4ade-b267-8370ef25fd34) to (/volumes/csi/csi-vol-cf38241d-0089-4ade-b267-8370ef25fd34/1419597d-c560-45da-8f6a-9411be79eb43)
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] release_export :MDCACHE :INFO :Export root for export id 1 status No such file or directory
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] reread_exports :CONFIG :EVENT :Reread exports complete
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] reread_exports :EXPORT :INFO :Exports after update
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] reread_exports :EXPORT :INFO :Export     0 pseudo (/) with path (/) and tag ((null)) perms (options=0221f080/0771f3e7 no_root_squash, --r-, -4-, ---, TCP, ----,               ,         ,                ,                ,                , none, sys, krb5, krb5i, krb5p)
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): Mandatory field, cmount_path is missing from block (FSAL)
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): 1 errors while processing parameters for FSAL
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): Errors found in configuration block FSAL
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): 1 validation errors in block FSAL
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): Errors processing block (FSAL)
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":1): 1 errors while processing parameters for EXPORT
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":1): Errors processing block (EXPORT)
06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":1): 1 (export create error, missing mandatory param) errors found block EXPORT
runner@fv-az660-497:~/work/rook/rook$``` 

Still investigating.

**Comment by sp98** [comment]
@nixpanic @Rakshith-R Is there a case of missing `nfs-utils` with NFS CSI?

**Comment by Rakshith-R** [comment]
> from the nfs pod logs:
> 
> ```
> 
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] fsal_put :FSAL :INFO :FSAL Ceph now unused
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] fsal_cfg_commit :CONFIG :CRIT :Could not create export for (/0001-0008-smoke-ns-0000000000000001-cf38241d-0089-4ade-b267-8370ef25fd34) to (/volumes/csi/csi-vol-cf38241d-0089-4ade-b267-8370ef25fd34/1419597d-c560-45da-8f6a-9411be79eb43)
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] release_export :MDCACHE :INFO :Export root for export id 1 status No such file or directory
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] reread_exports :CONFIG :EVENT :Reread exports complete
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] reread_exports :EXPORT :INFO :Exports after update
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] reread_exports :EXPORT :INFO :Export     0 pseudo (/) with path (/) and tag ((null)) perms (options=0221f080/0771f3e7 no_root_squash, --r-, -4-, ---, TCP, ----,               ,         ,                ,                ,                , none, sys, krb5, krb5i, krb5p)
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): Mandatory field, cmount_path is missing from block (FSAL)
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): 1 errors while processing parameters for FSAL
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): Errors found in configuration block FSAL
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): 1 validation errors in block FSAL
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":2): Errors processing block (FSAL)
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":1): 1 errors while processing parameters for EXPORT
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":1): Errors processing block (EXPORT)
> 06/11/2023 14:44:33 : epoch 6548fbcd : smoke-ns-my-nfs : nfs-ganesha-1[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File ("rados://.nfs/my-nfs/export-1":1): 1 (export create error, missing mandatory param) errors found block EXPORT
> runner@fv-az660-497:~/work/rook/rook$
> ```
> 
> Still investigating.

Works normally with ceph v18.1 . 
Something probably changed at nfs-ganesha / ceph level.

**Comment by BlaineEXE** [comment]
> @nixpanic @Rakshith-R Is there a case of missing `nfs-utils` with NFS CSI? Adding `sudo apt install nfs-kernel-server` to the CI helped me bypass the issue.

Could you help clarify? Did you install this into the CSI driver container?

> @BlaineEXE mentioned over the slack channel that ceph is planning to minimize the base image soon, so we might something similar once that happens.

From what I see in ceph-csi, they use `quay.io/ceph/ceph:v18` as the base image. The latest version of the base image I see from 4 hours ago has `nfs-utils` installed. The latest `quay.io/cephcsi/cephcsi

**Comment by sp98** [comment]
> > Is there a case of missing `nfs-utils` with NFS CSI? Adding `sudo apt install nfs-kernel-server` to the CI helped me bypass the issue.
> 
> @sp98 Could you help clarify? Did you install this into the CSI driver container?

Just on the CI node. Not on the CSI driver container. But realized its not needed since we have nfs ganesha.

**Comment by BlaineEXE** [comment]
From Rakshith's recent addition, it seems this is related to the recent `cmount_path` addition. This is related to the Ceph/Ganesha `cmount_path` stuff. 
Work is ongoing in Ceph, so this must be an issue in Ganesha: https://github.com/ceph/ceph/pull/53925

**Comment by BlaineEXE** [comment]
Reportedly, this issue is fixed in Ganesha 5.7. I see 5.7 present in the latest quay.io/ceph/ceph:v18 image. But it's still at 5.5 in the Ceph main (daemon-base) builds. Kaleb is going to check in with "tserlin" about keeping Ceph main branch builds up to date with the latest ganesha builds.

Reportedly, Ganesha `next` is not a good choice because it sometimes contain code that will not be released: https://github.com/ceph/ceph-container/pull/2153#discussion_r1318958405

**Comment by BlaineEXE** [comment]
Closing as magically fixed, and we can reopen if that's not the case.

**Comment by BlaineEXE** [comment]
Reopening after realizing there is still a CI failure:

I realized today that there are differences between the ganesha packages present in the `v18` arm image and the `v18` x86 image. 

**ARM**
```console
[root@f011d07eaf05 /]# ganesha.nfsd -v
NFS-Ganesha Release = V5.7
```

**x86**
```console
[root@180aaa0a8afe /]# ganesha.nfsd -v
NFS-Ganesha Release = V5.6
```

**Comment by BlaineEXE** [comment]
The underlying issue is introduced with NFS-Ganesha. It seems that it is not the only issue introduced by NFS-Ganesha recently, and those issues are currently being worked around in ceph-container by changing the Ganesha version present in Ceph builds.

It will probably take some time to make sure these changes are good and that the Ganesha version is "pinned" to the proper one to work around **both** issues.
https://github.com/ceph/ceph-container/pull/2169

**Comment by BlaineEXE** [comment]
Now finally fixed with the Reef image pinned to NFS-Ganesha v5.5-1
