### ISSUE TITLE
Integration test setup is frequently failing with device not found

### ISSUE THREAD

**Issue by travisn** [rook/rook#13154]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
All integration tests that setup a K8s cluster are frequently failing with the error:

```
+ sudo udevadm control --log-priority=debug
+ sudo swapoff --all --verbose
+ sudo umount /mnt
+ sudo sed -i.bak '/\/mnt/d' /etc/fstab
+ PARTITION=1
+ sudo wipefs --all --force 1
wipefs: error: 1: probing initialization failed: No such file or directory
```

Notice that the device "1" is not found. Of course that device is not found because it is intended to be a partition name such as `sda1`. The `BLOCK` variable in the setup script must be failing to find the device on this line:
```
"${BLOCK:=$(sudo lsblk --paths | awk '/14G/ {print $1}' | head -1)}"
```

Perhaps the device is not immediately available and we need to have a simple retry.

Rerunning the tests tends to allow the tests to pass.

**Expected behavior:**
The tests should not fail.

**Comment by sp98** [comment]
mostly likely due to the disk size filter of 14G. 

``` runner@fv-az691-576:~/work/rook/rook$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0     7:0    0 63.5M  1 loop /snap/core20/2015
loop1     7:1    0 91.9M  1 loop /snap/lxd/24061
loop2     7:2    0 40.9M  1 loop /snap/snapd/20290
sda       8:0    0   86G  0 disk 
├─sda1    8:1    0 85.9G  0 part /
├─sda14   8:14   0    4M  0 part 
└─sda15   8:15   0  106M  0 part /boot/efi
sdb       8:16   0   64G  0 disk 
└─sdb1    8:17   0   64G  0 part /mnt
runner@fv-az691-576:~/work/rook/rook$ sudo lsblk --paths | awk '/14G/ {print $1}' | head -1
runner@fv-az691-576:~/work/rook/rook$ sudo lsblk --paths | awk '/64G/ {print $1}' | head -1
/dev/sdb
runner@fv-az691-576:~/work/rook/rook$ ```

**Comment by sp98** [comment]
the github is allocating both 14 and 64Gb disks to the CI tests randomly.  @travisn any idea how to tune this?
a temporary [fix](https://github.com/rook/rook/pull/13156) to filter both 14 and 64Gb disk could be used until the root cause is know.

**Comment by travisn** [comment]
Let's go with #13156 for now, thanks, not sure an alternative.
