### ISSUE TITLE
test: include more environments in our CI pipelines

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1315]
Is this a bug report or feature request?

* Feature Request

**Feature Request**

Are there any similar features already existing: Yes, we have existing CI pipelines for Amazon and Google (GCE).

What should the feature do:  We should add CI pipelines for more environments that our users are running Rook in.  Some environments to include:
* OpenShift Online: https://manage.openshift.com/ #1841 
* Tectonic: https://coreos.com/tectonic/
* Rancher: https://rancher.com/kubernetes/
* Azure: https://azure.microsoft.com/en-us/

What would be solved through this feature:  The Rook project would have more confidence in the stability and reliability across a greater number of environments and help ensure that breaking changes are caught by our tests instead of our users.  This is related to #1901 to include more architectures.

**Comment by jbw976** [comment]
Adding to the 0.7 milestone so we can perhaps address some of the higher priority pipeline.  The openshift one is sounding more important and the Ceph guys may be able to get us set up with an env for our CI.

**Comment by nakabonne** [comment]
@jbw976 Please tell me more about the environment Jenkins is running in, the information I want to know especially is as follows:
- How is the environment in which the integration test of each cloud provider is executed constructed?
- Instruction set architecture of each machine (amd64?)

Thanks.
