### ISSUE TITLE
Not able to drain the node due to emtydir

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#13168]
we have a master and 3 worker nodes running on k8s cluster and in that we have deployed the rook-ceph and we are using 3 worker nodes disk i.e 3 osd's from 3 worker nodes, 

as part of the osd's or worker node replacement we are trying to cordon and drain the worker node(before drain we have removed the osd from ceph cluster followed the doc).

while draining the worker node we are getting below issue.

`~$ sudo kubectl drain worker2 --ignore-daemonsets
node/worker2 already cordoned
error: unable to drain node "worker2", aborting command...
 
There are pending nodes to be drained:
worker2
error: cannot delete Pods with local storage (use --delete-emptydir-data to override): rook-ceph/csi-cephfsplugin-provisioner-5f459cfb94-g6ccv, rook-ceph/csi-rbdplugin-provisioner-84c7fb8d76-d4d4b, rook-ceph/rook-ceph-mds-myfs-b-6cc4cfff96-lwlpw, rook-ceph/rook-ceph-mgr-a-7d58c74554-r5pz7, rook-ceph/rook-ceph-tools-79957dbdb7-rtfww
vmauser@master1:~$`
      

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`

` ceph status
  cluster:
    id:     00770d4b-045a-4102-bd24-6855c936ad7d
    health: HEALTH_WARN
            Degraded data redundancy: 119492/358476 objects degraded (33.333%), 64 pgs degraded, 65 pgs undersized
            24 pgs not deep-scrubbed in time
            OSD count 2 < osd_pool_default_size 3

  services:
    mon: 3 daemons, quorum b,d,e (age 10d)
    mgr: a(active, since 3w)
    mds: 1/1 daemons up, 1 hot standby
    osd: 2 osds: 2 up (since 8d), 2 in (since 8d)

  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 119.49k objects, 1.6 GiB
    usage:   4.7 GiB used, 495 GiB / 500 GiB avail
    pgs:     119492/358476 objects degraded (33.333%)
             64 active+undersized+degraded
             1  active+undersized

  io:
    client:   853 B/s rd, 2 op/s rd, 0 op/s wr
`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):  NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"

* Kernel (e.g. `uname -a`): Linux master1 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: VM's
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.8.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version (use `kubectl version`): v1.23.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): VM;s, on premesis  k8s cluster
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by vadlakiran** [comment]
below is the operator.yaml file

`#################################################################################################################
# The deployment for the rook operator
# Contains the common settings for most Kubernetes deployments.
# For example, to create the rook-ceph cluster:
#   kubectl create -f crds.yaml -f common.yaml -f operator.yaml
#   kubectl create -f cluster.yaml
#
# Also see other operator sample files for variations of operator.yaml:
# - operator-openshift.yaml: Common settings for running in OpenShift
###############################################################################################################

# Rook Ceph Operator Config ConfigMap
# Use this ConfigMap to override Rook-Ceph Operator configurations.
# NOTE! Precedence will be given to this config if the same Env Var config also exists in the
#       Operator Deployment.
# To move a configuration(s) from the Operator Deployment to this ConfigMap, add the config
# here. It is recommended to then remove it from the Deployment to eliminate any future confusion.
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  # should be in the namespace of the operator
  namespace: rook-ceph # namespace:operator
data:
  # The logging level for the operator: ERROR | WARNING | INFO | DEBUG
  ROOK_LOG_LEVEL: "INFO"

  # Enable the CSI driver.
  # To run the non-default version of the CSI driver, see the override-able image properties in operator.yaml
  ROOK_CSI_ENABLE_CEPHFS: "true"
  # Enable the default version of the CSI RBD driver. To start another version of the CSI driver, see image properties below.
  ROOK_CSI_ENABLE_RBD: "true"
  ROOK_CSI_ENABLE_GRPC_METRICS: "false"

  # Set to true to enable host networking for CSI CephFS and RBD nodeplugins. This may be necessary
  # in some network configurations where the SDN does not provide access to an external cluster or
  # there is significant drop in read/write performance.
  # CSI_ENABLE_HOST_NETWORK: "true"

  # Set logging level for csi containers.
  # Supported values from 0 to 5. 0 for general useful logs, 5 for trace level verbosity.
  # CSI_LOG_LEVEL: "0"

  # Set replicas for csi provisioner deployment.
  CSI_PROVISIONER_REPLICAS: "2"

  # OMAP generator will generate the omap mapping between the PV name and the RBD image.
  # CSI_ENABLE_OMAP_GENERATOR need to be enabled when we are using rbd mirroring feature.
  # By default OMAP generator sidecar is deployed with CSI provisioner pod, to disable
  # it set it to false.
  # CSI_ENABLE_OMAP_GENERATOR: "false"

  # set to false to disable deployment of snapshotter container in CephFS provisioner pod.
  CSI_ENABLE_CEPHFS_SNAPSHOTTER: "true"

  # set to false to disable deployment of snapshotter container in RBD provisioner pod.
  CSI_ENABLE_RBD_SNAPSHOTTER: "true"

  # Enable cephfs kernel driver instead of ceph-fuse.
  # If you disable the kernel client, your application may be disrupted during upgrade.
  # See the upgrade guide: https://rook.io/docs/rook/latest/ceph-upgrade.html
  # NOTE! cephfs quota is not supported in kernel version < 4.17
  CSI_FORCE_CEPHFS_KERNEL_CLIENT: "true"

  # (Optional) policy for modifying a volume's ownership or permissions when the RBD PVC is being mounted.
  # supported values are documented at https://kubernetes-csi.github.io/docs/support-fsgroup.html
  CSI_RBD_FSGROUPPOLICY: "ReadWriteOnceWithFSType"

  # (Optional) policy for modifying a volume's ownership or permissions when the CephFS PVC is being mounted.
  # supported values are documented at https://kubernetes-csi.github.io/docs/support-fsgroup.html
  CSI_CEPHFS_FSGROUPPOLICY: "None"

  # (Optional) Allow starting unsupported ceph-csi image
  ROOK_CSI_ALLOW_UNSUPPORTED_VERSION: "false"

  # (Optional) control the host mount of /etc/selinux for csi plugin pods.
  CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT: "false"

  # The default version of CSI supported by Rook will be started. To change the version
  # of the CSI driver to something other than what is officially supported, change
  # these images to the desired release of the CSI driver.
  # ROOK_CSI_CEPH_IMAGE: "quay.io/cephcsi/cephcsi:v3.4.0"
  ROOK_CSI_CEPH_IMAGE: "docker-registry.com:5000/cephcsi/cephcsi:v3.4.0"
  # ROOK_CSI_REGISTRAR_IMAGE: "k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0"
  ROOK_CSI_REGISTRAR_IMAGE: "docker-registry.com:5000/sig-storage/csi-node-driver-registrar:v2.3.0"
  # ROOK_CSI_RESIZER_IMAGE: "k8s.gcr.io/sig-storage/csi-resizer:v1.3.0"
  ROOK_CSI_RESIZER_IMAGE: "docker-registry.com:5000/sig-storage/csi-resizer:v1.3.0"
  # ROOK_CSI_PROVISIONER_IMAGE: "k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0"
  ROOK_CSI_PROVISIONER_IMAGE: "docker-registry.com:5000/sig-storage/csi-provisioner:v3.0.0"
  # ROOK_CSI_SNAPSHOTTER_IMAGE: "k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.0"
  ROOK_CSI_SNAPSHOTTER_IMAGE: "docker-registry.com:5000/sig-storage/csi-snapshotter:v4.2.0"
  # ROOK_CSI_ATTACHER_IMAGE: "k8s.gcr.io/sig-storage/csi-attacher:v3.3.0"
  ROOK_CSI_ATTACHER_IMAGE: "docker-registry.com:5000/sig-storage/csi-attacher:v3.3.0"

  # (Optional) set user created priorityclassName for csi plugin pods.
  # CSI_PLUGIN_PRIORITY_CLASSNAME: "system-node-critical"

  # (Optional) set user created priorityclassName for csi provisioner pods.
  # CSI_PROVISIONER_PRIORITY_CLASSNAME: "system-cluster-critical"

  # CSI CephFS plugin daemonset update strategy, supported values are OnDelete and RollingUpdate.
  # Default value is RollingUpdate.
  # CSI_CEPHFS_PLUGIN_UPDATE_STRATEGY: "OnDelete"
  # CSI RBD plugin daemonset update strategy, supported values are OnDelete and RollingUpdate.
  # Default value is RollingUpdate.
  # CSI_RBD_PLUGIN_UPDATE_STRATEGY: "OnDelete"

  # kubelet directory path, if kubelet configured to use other than /var/lib/kubelet path.
  # ROOK_CSI_KUBELET_DIR_PATH: "/var/lib/kubelet"

  # Labels to add to the CSI CephFS Deployments and DaemonSets Pods.
  # ROOK_CSI_CEPHFS_POD_LABELS: "key1=value1,key2=value2"
  # Labels to add to the CSI RBD Deployments and DaemonSets Pods.
  # ROOK_CSI_RBD_POD_LABELS: "key1=value1,key2=value2"

  # (Optional) CephCSI provisioner NodeAffinity(applied to both CephFS and RBD provisioner).
  # CSI_PROVISIONER_NODE_AFFINITY: "role=storage-node; storage=rook, ceph"
  # (Optional) CephCSI provisioner tolerations list(applied to both CephFS and RBD provisioner).
  # Put here list of taints you want to tolerate in YAML format.
  # CSI provisioner would be best to start on the same nodes as other ceph daemons.
  # CSI_PROVISIONER_TOLERATIONS: |
  #   - effect: NoSchedule
  #     key: node-role.kubernetes.io/controlplane
  #     operator: Exists
  #   - effect: NoExecute
  #     key: node-role.kubernetes.io/etcd
  #     operator: Exists
  # (Optional) CephCSI plugin NodeAffinity(applied to both CephFS and RBD plugin).
  # CSI_PLUGIN_NODE_AFFINITY: "role=storage-node; storage=rook, ceph"
  # (Optional) CephCSI plugin tolerations list(applied to both CephFS and RBD plugin).
  # Put here list of taints you want to tolerate in YAML format.
  # CSI plugins need to be started on all the nodes where the clients need to mount the storage.
  # CSI_PLUGIN_TOLERATIONS: |
  #   - effect: NoSchedule
  #     key: node-role.kubernetes.io/controlplane
  #     operator: Exists
  #   - effect: NoExecute
  #     key: node-role.kubernetes.io/etcd
  #     operator: Exists

  # (Optional) CephCSI RBD provisioner NodeAffinity(if specified, overrides CSI_PROVISIONER_NODE_AFFINITY).
  # CSI_RBD_PROVISIONER_NODE_AFFINITY: "role=rbd-node"
  # (Optional) CephCSI RBD provisioner tolerations list(if specified, overrides CSI_PROVISIONER_TOLERATIONS).
  # Put here list of taints you want to tolerate in YAML format.
  # CSI provisioner would be best to start on the same nodes as other ceph daemons.
  # CSI_RBD_PROVISIONER_TOLERATIONS: |
  #   - key: node.rook.io/rbd
  #     operator: Exists
  # (Optional) CephCSI RBD plugin NodeAffinity(if specified, overrides CSI_PLUGIN_NODE_AFFINITY).
  # CSI_RBD_PLUGIN_NODE_AFFINITY: "role=rbd-node"
  # (Optional) CephCSI RBD plugin tolerations list(if specified, overrides CSI_PLUGIN_TOLERATIONS).
  # Put here list of taints you want to tolerate in YAML format.
  # CSI plugins need to be started on all the nodes where the clients need to mount the storage.
  # CSI_RBD_PLUGIN_TOLERATIONS: |
  #   - key: node.rook.io/rbd
  #     operator: Exists

  # (Optional) CephCSI CephFS provisioner NodeAffinity(if specified, overrides CSI_PROVISIONER_NODE_AFFINITY).
  # CSI_CEPHFS_PROVISIONER_NODE_AFFINITY: "role=cephfs-node"
  # (Optional) CephCSI CephFS provisioner tolerations list(if specified, overrides CSI_PROVISIONER_TOLERATIONS).
  # Put here list of taints you want to tolerate in YAML format.
  # CSI provisioner would be best to start on the same nodes as other ceph daemons.
  # CSI_CEPHFS_PROVISIONER_TOLERATIONS: |
  #   - key: node.rook.io/cephfs
  #     operator: Exists
  # (Optional) CephCSI CephFS plugin NodeAffinity(if specified, overrides CSI_PLUGIN_NODE_AFFINITY).
  # CSI_CEPHFS_PLUGIN_NODE_AFFINITY: "role=cephfs-node"
  # (Optional) CephCSI CephFS plugin tolerations list(if specified, overrides CSI_PLUGIN_TOLERATIONS).
  # Put here list of taints you want to tolerate in YAML format.
  # CSI plugins need to be started on all the nodes where the clients need to mount the storage.
  # CSI_CEPHFS_PLUGIN_TOLERATIONS: |
  #   - key: node.rook.io/cephfs
  #     operator: Exists

  # (Optional) CEPH CSI RBD provisioner resource requirement list, Put here list of resource
  # requests and limits you want to apply for provisioner pod
  # CSI_RBD_PROVISIONER_RESOURCE: |
  #  - name : csi-provisioner
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 100m
  #      limits:
  #        memory: 256Mi
  #        cpu: 200m
  #  - name : csi-resizer
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 100m
  #      limits:
  #        memory: 256Mi
  #        cpu: 200m
  #  - name : csi-attacher
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 100m
  #      limits:
  #        memory: 256Mi
  #        cpu: 200m
  #  - name : csi-snapshotter
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 100m
  #      limits:
  #        memory: 256Mi
  #        cpu: 200m
  #  - name : csi-rbdplugin
  #    resource:
  #      requests:
  #        memory: 512Mi
  #        cpu: 250m
  #      limits:
  #        memory: 1Gi
  #        cpu: 500m
  #  - name : liveness-prometheus
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 50m
  #      limits:
  #        memory: 256Mi
  #        cpu: 100m
  # (Optional) CEPH CSI RBD plugin resource requirement list, Put here list of resource
  # requests and limits you want to apply for plugin pod
  # CSI_RBD_PLUGIN_RESOURCE: |
  #  - name : driver-registrar
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 50m
  #      limits:
  #        memory: 256Mi
  #        cpu: 100m
  #  - name : csi-rbdplugin
  #    resource:
  #      requests:
  #        memory: 512Mi
  #        cpu: 250m
  #      limits:
  #        memory: 1Gi
  #        cpu: 500m
  #  - name : liveness-prometheus
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 50m
  #      limits:
  #        memory: 256Mi
  #        cpu: 100m
  # (Optional) CEPH CSI CephFS provisioner resource requirement list, Put here list of resource
  # requests and limits you want to apply for provisioner pod
  # CSI_CEPHFS_PROVISIONER_RESOURCE: |
  #  - name : csi-provisioner
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 100m
  #      limits:
  #        memory: 256Mi
  #        cpu: 200m
  #  - name : csi-resizer
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 100m
  #      limits:
  #        memory: 256Mi
  #        cpu: 200m
  #  - name : csi-attacher
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 100m
  #      limits:
  #        memory: 256Mi
  #        cpu: 200m
  #  - name : csi-cephfsplugin
  #    resource:
  #      requests:
  #        memory: 512Mi
  #        cpu: 250m
  #      limits:
  #        memory: 1Gi
  #        cpu: 500m
  #  - name : liveness-prometheus
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 50m
  #      limits:
  #        memory: 256Mi
  #        cpu: 100m
  # (Optional) CEPH CSI CephFS plugin resource requirement list, Put here list of resource
  # requests and limits you want to apply for plugin pod
  # CSI_CEPHFS_PLUGIN_RESOURCE: |
  #  - name : driver-registrar
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 50m
  #      limits:
  #        memory: 256Mi
  #        cpu: 100m
  #  - name : csi-cephfsplugin
  #    resource:
  #      requests:
  #        memory: 512Mi
  #        cpu: 250m
  #      limits:
  #        memory: 1Gi
  #        cpu: 500m
  #  - name : liveness-prometheus
  #    resource:
  #      requests:
  #        memory: 128Mi
  #        cpu: 50m
  #      limits:
  #        memory: 256Mi
  #        cpu: 100m

  # Configure CSI CSI Ceph FS grpc and liveness metrics port
  # CSI_CEPHFS_GRPC_METRICS_PORT: "9091"
  # CSI_CEPHFS_LIVENESS_METRICS_PORT: "9081"
  # Configure CSI RBD grpc and liveness metrics port
  # CSI_RBD_GRPC_METRICS_PORT: "9090"
  # CSI_RBD_LIVENESS_METRICS_PORT: "9080"

  # Whether the OBC provisioner should watch on the operator namespace or not, if not the namespace of the cluster will be used
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"

  # Whether to start the discovery daemon to watch for raw storage devices on nodes in the cluster.
  # This daemon does not need to run if you are only going to create your OSDs based on StorageClassDeviceSets with PVCs.
  ROOK_ENABLE_DISCOVERY_DAEMON: "false"
  # The timeout value (in seconds) of Ceph commands. It should be >= 1. If this variable is not set or is an invalid value, it's default to 15.
  ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: "15"
  # Enable the volume replication controller.
  # Before enabling, ensure the Volume Replication CRDs are created.
  # See https://rook.io/docs/rook/latest/ceph-csi-drivers.html#rbd-mirroring
  CSI_ENABLE_VOLUME_REPLICATION: "false"
  # CSI_VOLUME_REPLICATION_IMAGE: "quay.io/csiaddons/volumereplication-operator:v0.1.0"
  # CSI_VOLUME_REPLICATION_IMAGE: "docker-registry.com:5000/csiaddons/volumereplication-operator:v0.1.0"
---
# OLM: BEGIN OPERATOR DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/component: rook-ceph-operator
    app.kubernetes.io/part-of: rook-ceph-operator
spec:
  selector:
    matchLabels:
      app: rook-ceph-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: rook-ceph-operator
    spec:
      serviceAccountName: rook-ceph-system
      containers:
        - name: rook-ceph-operator
          #image: rook/ceph:v1.8.1
          image: docker-registry.com:5000/rook/ceph:v1.8.1
          args: ["ceph", "operator"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 2016
            runAsGroup: 2016
          volumeMounts:
            - mountPath: /var/lib/rook
              name: rook-config
            - mountPath: /etc/ceph
              name: default-config-dir
            - mountPath: /etc/webhook
              name: webhook-cert
          ports:
            - containerPort: 9443
              name: https-webhook
              protocol: TCP
          env:
            # If the operator should only watch for cluster CRDs in the same namespace, set this to "true".
            # If this is not set to true, the operator will watch for cluster CRDs in all namespaces.
            - name: ROOK_CURRENT_NAMESPACE_ONLY
              value: "false"
            # Rook Discover toleration. Will tolerate all taints with all keys.
            # Choose between NoSchedule, PreferNoSchedule and NoExecute:
            # - name: DISCOVER_TOLERATION
            #   value: "NoSchedule"
            # (Optional) Rook Discover toleration key. Set this to the key of the taint you want to tolerate
            # - name: DISCOVER_TOLERATION_KEY
            #   value: "<KeyOfTheTaintToTolerate>"
            # (Optional) Rook Discover tolerations list. Put here list of taints you want to tolerate in YAML format.
            # - name: DISCOVER_TOLERATIONS
            #   value: |
            #     - effect: NoSchedule
            #       key: node-role.kubernetes.io/controlplane
            #       operator: Exists
            #     - effect: NoExecute
            #       key: node-role.kubernetes.io/etcd
            #       operator: Exists
            # (Optional) Rook Discover priority class name to set on the pod(s)
            # - name: DISCOVER_PRIORITY_CLASS_NAME
            #   value: "<PriorityClassName>"
            # (Optional) Discover Agent NodeAffinity.
            # - name: DISCOVER_AGENT_NODE_AFFINITY
            #   value: "role=storage-node; storage=rook, ceph"
            # (Optional) Discover Agent Pod Labels.
            # - name: DISCOVER_AGENT_POD_LABELS
            #   value: "key1=value1,key2=value2"

            # The duration between discovering devices in the rook-discover daemonset.
            - name: ROOK_DISCOVER_DEVICES_INTERVAL
              value: "60m"

            # Whether to start pods as privileged that mount a host path, which includes the Ceph mon and osd pods.
            # Set this to true if SELinux is enabled (e.g. OpenShift) to workaround the anyuid issues.
            # For more details see https://github.com/rook/rook/issues/1314#issuecomment-355799641
            - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
              value: "false"

            # In some situations SELinux relabelling breaks (times out) on large filesystems, and doesn't work with cephfs ReadWriteMany volumes (last relabel wins).
            # Disable it here if you have similar issues.
            # For more details see https://github.com/rook/rook/issues/2417
            - name: ROOK_ENABLE_SELINUX_RELABELING
              value: "true"

            # In large volumes it will take some time to chown all the files. Disable it here if you have performance issues.
            # For more details see https://github.com/rook/rook/issues/2254
            - name: ROOK_ENABLE_FSGROUP
              value: "true"

            # Disable automatic orchestration when new devices are discovered
            - name: ROOK_DISABLE_DEVICE_HOTPLUG
              value: "false"

            # Provide customised regex as the values using comma. For eg. regex for rbd based volume, value will be like "(?i)rbd[0-9]+".
            # In case of more than one regex, use comma to separate between them.
            # Default regex will be "(?i)dm-[0-9]+,(?i)rbd[0-9]+,(?i)nbd[0-9]+"
            # Add regex expression after putting a comma to blacklist a disk
            # If value is empty, the default regex will be used.
            - name: DISCOVER_DAEMON_UDEV_BLACKLIST
              value: "(?i)dm-[0-9]+,(?i)rbd[0-9]+,(?i)nbd[0-9]+"

            # Time to wait until the node controller will move Rook pods to other
            # nodes after detecting an unreachable node.
            # Pods affected by this setting are:
            # mgr, rbd, mds, rgw, nfs, PVC based mons and osds, and ceph toolbox
            # The value used in this variable replaces the default value of 300 secs
            # added automatically by k8s as Toleration for
            # <node.kubernetes.io/unreachable>
            # The total amount of time to reschedule Rook pods in healthy nodes
            # before detecting a <not ready node> condition will be the sum of:
            #  --> node-monitor-grace-period: 40 seconds (k8s kube-controller-manager flag)
            #  --> ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS: 5 seconds
            - name: ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS
              value: "5"

            # The name of the node to pass with the downward API
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # The pod name to pass with the downward API
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # The pod namespace to pass with the downward API
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          # Recommended resource requests and limits, if desired
          #resources:
          #  limits:
          #    cpu: 500m
          #    memory: 256Mi
          #  requests:
          #    cpu: 100m
          #    memory: 128Mi

          #  Uncomment it to run lib bucket provisioner in multithreaded mode
          #- name: LIB_BUCKET_PROVISIONER_THREADS
          #  value: "5"

      # Uncomment it to run rook operator on the host network
      #hostNetwork: true
      volumes:
        - name: rook-config
          emptyDir: {}
        - name: default-config-dir
          emptyDir: {}
        - name: webhook-cert
          emptyDir: {}
# OLM: END OPERATOR DEPLOYMENT
`

**Comment by travisn** [comment]
The drain error can safely be ignored for these pods that are stateless. The error is complaining about the hostPath that the pods are using, but it is not a concern for the drain, as they are just logs.
rook-ceph/csi-cephfsplugin-provisioner-5f459cfb94-g6ccv, rook-ceph/csi-rbdplugin-provisioner-84c7fb8d76-d4d4b, rook-ceph/rook-ceph-mds-myfs-b-6cc4cfff96-lwlpw, rook-ceph/rook-ceph-mgr-a-7d58c74554-r5pz7, rook-ceph/rook-ceph-tools-79957dbdb7-rtfww

**Comment by vadlakiran** [comment]
@travisn due to above hostPath that the pods are using we are not able to drain the node. 
if we are draining the node, all rook-ceph pods will schedule another available node ?

**Comment by sp98** [comment]
> @travisn due to above hostPath that the pods are using we are not able to drain the node. if we are draining the node, > all rook-ceph pods will schedule another available node ?

yes

> if i want to remove the worker node from k8s cluster, worker node is part of the rook-ceph disk i.e osd, how we can stop or move the pods which are running on worker node(cordon and drain worker node) to another available worker node ?
Rook should take care of that. With respect to storage, you should be good as long as your drain one node at a time. And only drain the other node once the OSD is back and data has re balanced (pgs are active+clean)

**Comment by vadlakiran** [comment]
@sp98 Thank you 
I have tried to drain with below option 
kubectl drain worker2 --ignore-daemonsets --delete-emptydir-data

then we are getting below error message, and node is not drain , rook-ceph-mon-e-f96ff7588-nnwm9 pod is running on worker2, why its not scheduling other available worker node ?

`
error when evicting pods/"rook-ceph-mon-e-f96ff7588-nnwm9" -n "rook-ceph" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.

evicting pod rook-ceph/rook-ceph-mon-e-f96ff7588-nnwm9

error when evicting pods/"rook-ceph-mon-e-f96ff7588-nnwm9" -n "rook-ceph" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
`

**Comment by sp98** [comment]
``` error when evicting pods/"rook-ceph-mon-e-f96ff7588-nnwm9" -n "rook-ceph" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.```

We have Pod disruption budget applied on mons. This allows only one mon pod to be drained at a time. 

how many mon pods are running when you run `kubectl drain worker2 --ignore-daemonsets --delete-emptydir-data` ? (can you share the output of `kubectl get pods -n rook-ceph` ?

**Comment by vadlakiran** [comment]
`~$ sudo kubectl get pods -n rook-ceph -owide
NAME                                                    READY   STATUS      RESTARTS   AGE      NODE          NOMINATED NODE   READINESS GATES
csi-cephfsplugin-9926x                                  3/3     Running     18         118d     worker3   <none>           <none>
csi-cephfsplugin-bpz2x                                  3/3     Running     24         118d     worker2   <none>           <none>
csi-cephfsplugin-pr9mq                                  3/3     Running     30         118d     worker1   <none>           <none>
csi-cephfsplugin-provisioner-5f459cfb94-dqxw8           6/6     Running     0          55m      worker1   <none>           <none>
csi-cephfsplugin-provisioner-5f459cfb94-zf7pj           6/6     Running     24         90d      worker3   <none>           <none>
csi-rbdplugin-f58nm                                     3/3     Running     18         118d     worker3   <none>           <none>
csi-rbdplugin-nq2wm                                     3/3     Running     24         118d     worker2   <none>           <none>
csi-rbdplugin-nr7fb                                     3/3     Running     30         118d     worker1   <none>           <none>
csi-rbdplugin-provisioner-84c7fb8d76-77gbk              6/6     Running     24         90d      worker3   <none>           <none>
csi-rbdplugin-provisioner-84c7fb8d76-dlprv              6/6     Running     0          55m      worker1   <none>           <none>
rook-ceph-crashcollector-jmapworker1-8fc9c8496-d5876    1/1     Running     0          11d      worker1   <none>           <none>
rook-ceph-crashcollector-jmapworker2-798bdbd764-xcsz9   0/1     Pending     0          55m      <none>        <none>           <none>
rook-ceph-crashcollector-jmapworker3-f5b4b4f45-hhnwc    1/1     Running     4          90d      worker3   <none>           <none>
rook-ceph-mds-myfs-a-7598fc97b4-r9znp                   2/2     Running     34         90d      worker3   <none>           <none>
rook-ceph-mds-myfs-b-6cc4cfff96-dk9zp                   2/2     Running     0          55m      worker1   <none>           <none>
rook-ceph-mgr-a-7d58c74554-lhwvs                        2/2     Running     0          55m      worker3   <none>           <none>
rook-ceph-mon-b-755464db8f-jglvs                        2/2     Running     8          93d      worker3   <none>           <none>
rook-ceph-mon-d-c78846766-ls6qb                         0/2     Pending     0          55m      <none>        <none>           <none>
rook-ceph-mon-e-f96ff7588-nnwm9                         2/2     Running     0          11d      worker2   <none>           <none>
rook-ceph-osd-1-65fc776d98-5qp5f                        2/2     Running     0          11d      worker1   <none>           <none>
rook-ceph-osd-2-5b6c9f5947-hh965                        2/2     Running     8          94d      worker3   <none>           <none>
rook-ceph-osd-prepare-jmapworker1-zthl9                 0/1     Completed   0          9d       worker1   <none>           <none>
rook-ceph-osd-prepare-jmapworker3-qgwl2                 0/1     Completed   0          9d       worker3   <none>           <none>
rook-ceph-tools-79957dbdb7-tq56f                        1/1     Running     0          55m      worker1   <none>           <none>`


===================

`~$ sudo kubectl get pdb -n rook-ceph
NAME                 MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
rook-ceph-mds-myfs   1               N/A               1                     118d
rook-ceph-mon-pdb    N/A             1                 0                     118d
rook-ceph-osd        N/A             1                 1                     11d
`

**Comment by sp98** [comment]
@vadlakiran Its not very readable. Maybe try adding them in within triple quotes. 

Based on what the output you have shared, it seems that one of your mon pod `ook-ceph-mon-d-c78846766-ls6qb`  is already in pending state. 

That's the reason you are seeing the message `error when evicting pods/"rook-ceph-mon-e-f96ff7588-nnwm9" -n "rook-ceph" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.`

**Comment by vadlakiran** [comment]
@sp98 if i delete the pending pod, this will resolve the issue ?

**Comment by sp98** [comment]
It won't. You need 3 mons running for quorum. Currently you have only 3. So I would strongly advice to bring the mon quorum back before draining any other node. 

So to figure out why this mon pod was not assigned to any node.  You can check `kubectl describe pod-name -n rook-ceph` to see why this pod was not assigned to any node.

**Comment by sp98** [comment]
@vadlakiran any luck finding out why `rook-ceph-mon-d-c78846766-ls6qb` pod is pending?

**Comment by vadlakiran** [comment]
@sp98 yes i have deleted deployment which is  pending status pod, then i am able to drain the node

Thank you

**Comment by sp98** [comment]
@vadlakiran can we close this issue?

**Comment by sp98** [comment]
@vadlakiran looks like your issue is fixed. So closing this for now. Please reopen if you think issue is not resolved yet.
