### ISSUE TITLE
Test flags are not being initialized. 

### ISSUE THREAD

**Issue by dangula** [rook/rook#1316]
Test flags are not being initialized. Test flags are showing up but they are always asociated with the default values. this happed after fixing https://github.com/rook/rook/issues/1262.  where we removed flags.Parse() test EnvironmentManifest. Testify depenency is calling flag.Parse() defore the test flags are called. But calling flags.Parse() in EnvironmentManifest is causing Testify flags to not show up.  We need a fix where both test flags and testify flags are avaliable and initialized.

**Comment by jbw976** [comment]
ah, this sounds like a bit of a circular dependency between our flags being declared and parsed and the testify flags being declared and parsed.  do you understand the fix yet that would work for all sets of flags @dangula? (are there other flags we need to worry about to?)

**Comment by dangula** [comment]
i think i understand the fix, i was reading about flags and init online, people there was recomending not using flag.Parse and init() in a general purpose package, they suggest using it in a package that will be only called once.  I moved the init () from installer package to  objects package and looks like all the flags are bing declared parsed correctly, i will do some more testing and open a PR
