### ISSUE TITLE
Add device class spec for ceph fs

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13171]
**Is this a bug report or feature request?**
* Feature Request

Currently, rbd/blockpool supports adding a spec device class, by which  we can choose certain types of OSDs,
But ceph fs doesn't have such spec defination

**What should the feature do:**

Cephfs should use certain type of osds if needed

**What is use case behind this feature:**

**Environment**:

**Comment by Madhu-1** [comment]
@parth-gr cephfilesystem already supports it, please check datapool spec https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L735

**Comment by parth-gr** [comment]
I see thanks @Madhu-1
