### ISSUE TITLE
Limit the number or size of core dump files to avoid excessive storage utilization.

### ISSUE THREAD

**Issue by thenamehasbeentake** [rook/rook#13184]
### Discussed in https://github.com/rook/rook/discussions/13176

<div type='discussions-op-text'>

<sup>Originally posted by **thenamehasbeentake** November  8, 2023</sup>
We encountered the problem not long ago.
https://github.com/rook/rook/issues/9885

bluefs _allocate unable to allocate memory and the osd pod keeps trying to start and crash with large core file, causing the disk to fill up. Insufficient system disk capacity lets pods to be evicted. Shall we use logrotate to rotate /core files?</div>

## **Is this a bug report or feature request?**
* Feature Request

## **What should the feature do:**
Limit the number or size of core dump files that created when osd crash. 
kubernetes will try to start an osd again and again even if the osd crashes when it starts. One core dump file after another is created. After a while, the system disk will be filled up. Then all pod will be effect on this node.

## **What is use case behind this feature:**
Modify crds to support limit core dump files' s number or size, and rook remove part of core dump files which exceed the limit.
Just like logrotate on logs.

## **Problems I've encountered**
Core dump files directory is as same as log directory for osd. 
![image](https://github.com/rook/rook/assets/36036872/212aad59-b7fb-4d38-aa7c-72a0ef6bbe00)
Maybe we can use logrotate to limit number or size of core dump files.

By the way, osd crashes on starting:
![image](https://github.com/rook/rook/assets/36036872/8d1b5cdc-b407-480c-b387-139402b83bf9)
Pod is evicted:
![image](https://github.com/rook/rook/assets/36036872/0129c939-6579-47cf-9df7-2242fcc50d74)

**Comment by subhamkrai** [comment]
@thenamehasbeentake could you try completing the issue template? it's difficult to understand what is the issue here and what you are suggesting to fix. Thanks

**Comment by thenamehasbeentake** [comment]
> @thenamehasbeentake could you try completing the issue template? it's difficult to understand what is the issue here and what you are suggesting to fix. Thanks

I'm sorry about that. I just open the issue from discussion. The template is not automatically generated.

**Comment by sp98** [comment]
@thenamehasbeentake  Rook OSDs pod does set the `logrotate` via sidecar

``` ❯ oc exec -it -n rook-ceph rook-ceph-osd-0-ffbbb6ff9-4pzdt sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "osd" out of: osd, log-collector, activate (init), expand-bluefs (init), chown-container-data-dir (init)
sh-4.4# cat /etc/logrotate.d/ceph
/var/log/ceph/*.log {
    rotate 7
    daily
    compress
    sharedscripts
    postrotate
        killall -q -1 ceph-mon ceph-mgr ceph-mds ceph-osd ceph-fuse radosgw rbd-mirror cephfs-mirror || pkill -1 -x "ceph-mon|ceph-mgr|ceph-mds|ceph-osd|ceph-fuse|radosgw|rbd-mirror|cephfs-mirror" || true
    endscript
    missingok
    notifempty
    su root ceph
}
```

does this not help? or am I missing something here?

**Comment by thenamehasbeentake** [comment]
> @thenamehasbeentake Rook OSDs pod does set the `logrotate` via sidecar
> 
> ```
> kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
> Defaulted container "osd" out of: osd, log-collector, activate (init), expand-bluefs (init), chown-container-data-dir (init)
> sh-4.4# cat /etc/logrotate.d/ceph
> /var/log/ceph/*.log {
>     rotate 7
>     daily
>     compress
>     sharedscripts
>     postrotate
>         killall -q -1 ceph-mon ceph-mgr ceph-mds ceph-osd ceph-fuse radosgw rbd-mirror cephfs-mirror || pkill -1 -x "ceph-mon|ceph-mgr|ceph-mds|ceph-osd|ceph-fuse|radosgw|rbd-mirror|cephfs-mirror" || true
>     endscript
>     missingok
>     notifempty
>     su root ceph
> }
> ```
> 
> does this not help? or am I missing something here?

Now logrotate only support  `/var/log/ceph/*.log` log files. You can run `kill -6 <osd pid>` multiple times to simulate an exception of osd crash. And you' ll see a lot of coredump files named `core.pid` accumulated.
By the way, crashCollector in cephcluster only remove crash history in mgr but not clean coredump files.

**Comment by sp98** [comment]
> Now logrotate only support `/var/log/ceph/*.log` log files. You can run `kill -6 <osd pid>` multiple times to simulate an exception of osd crash. And you' ll see a lot of coredump files named `core.pid` accumulated. By the way, crashCollector in cephcluster only remove crash history in mgr but not clean coredump files.

so just updating the file to read the core.pid files should suffice? 

Something like:
``` /var/log/ceph/core.*
/var/log/ceph/*.log {
    rotate 7
    daily
    compress
    sharedscripts
    postrotate
        killall -q -1 ceph-mon ceph-mgr ceph-mds ceph-osd ceph-fuse radosgw rbd-mirror cephfs-mirror || pkill -1 -x "ceph-mon|ceph-mgr|ceph-mds|ceph-osd|ceph-fuse|radosgw|rbd-mirror|cephfs-mirror" || true
    endscript
    missingok
    notifempty
    su root ceph
}```

@thenamehasbeentake

**Comment by thenamehasbeentake** [comment]
> > Now logrotate only support `/var/log/ceph/*.log` log files. You can run `kill -6 <osd pid>` multiple times to simulate an exception of osd crash. And you' ll see a lot of coredump files named `core.pid` accumulated. By the way, crashCollector in cephcluster only remove crash history in mgr but not clean coredump files.
> 
> so just updating the file to read the core.pid files should suffice?
> 
> Something like:
> 
> ```
> /var/log/ceph/core.*
> /var/log/ceph/*.log {
>     rotate 7
>     daily
>     compress
>     sharedscripts
>     postrotate
>         killall -q -1 ceph-mon ceph-mgr ceph-mds ceph-osd ceph-fuse radosgw rbd-mirror cephfs-mirror || pkill -1 -x "ceph-mon|ceph-mgr|ceph-mds|ceph-osd|ceph-fuse|radosgw|rbd-mirror|cephfs-mirror" || true
>     endscript
>     missingok
>     notifempty
>     su root ceph
> }
> ```
> 
> @thenamehasbeentake

Yes. Compared with log files, core files maybe do not need to be compressed, and the trigger frequency should be changed to `hourly`.Only the latest part of the logs need to be kept. So you need to think about how to write the logrotate configuration file.

**Comment by sp98** [comment]
> Yes. Compared with log files, core files maybe do not need to be compressed, and the trigger frequency should be changed to `hourly`.Only the latest part of the logs need to be kept. So you need to think about how to write the logrotate configuration file.

Having different configurations for different types of logs files (*.logs and core.PID) will be harder to implement and manage. 

Why not use same configurations for both *.logs and core.PID files?
@thenamehasbeentake

**Comment by subhamkrai** [comment]
We give the option to change the frequency so the user can modify according to the user and agree it will be difficult to maintain two configurations.

**Comment by thenamehasbeentake** [comment]
> We give the option to change the frequency so the user can modify according to the user and agree it will be difficult to maintain two configurations.

/etc/logrotate.d/ceph is the logrotate config of ceph. We can create a new config to support it.

**Comment by thenamehasbeentake** [comment]
> We give the option to change the frequency so the user can modify according to the user and agree it will be difficult to maintain two configurations.

For coredump files, it can be simplified to retain the optional number. We create a another logrotate file unique to rook.Is this possible?

**Comment by microyahoo** [comment]
> > Now logrotate only support `/var/log/ceph/*.log` log files. You can run `kill -6 <osd pid>` multiple times to simulate an exception of osd crash. And you' ll see a lot of coredump files named `core.pid` accumulated. By the way, crashCollector in cephcluster only remove crash history in mgr but not clean coredump files.
> 
> so just updating the file to read the core.pid files should suffice?
> 
> Something like:
> 
> ```
> /var/log/ceph/core.*
> /var/log/ceph/*.log {
>     rotate 7
>     daily
>     compress
>     sharedscripts
>     postrotate
>         killall -q -1 ceph-mon ceph-mgr ceph-mds ceph-osd ceph-fuse radosgw rbd-mirror cephfs-mirror || pkill -1 -x "ceph-mon|ceph-mgr|ceph-mds|ceph-osd|ceph-fuse|radosgw|rbd-mirror|cephfs-mirror" || true
>     endscript
>     missingok
>     notifempty
>     su root ceph
> }
> ```
> 
> @thenamehasbeentake

hi @sp98, @subhamkrai,  log-collector runs with osds in `Deployments`, so multiple core dump logrotate instances will be running in one node. It's better to run `DaemonSet` to all nodes, one instance in one node.

**Comment by subhamkrai** [comment]
> > > Now logrotate only support `/var/log/ceph/*.log` log files. You can run `kill -6 <osd pid>` multiple times to simulate an exception of osd crash. And you' ll see a lot of coredump files named `core.pid` accumulated. By the way, crashCollector in cephcluster only remove crash history in mgr but not clean coredump files.
> > 
> > 
> > so just updating the file to read the core.pid files should suffice?
> > Something like:
> > ```
> > /var/log/ceph/core.*
> > /var/log/ceph/*.log {
> >     rotate 7
> >     daily
> >     compress
> >     sharedscripts
> >     postrotate
> >         killall -q -1 ceph-mon ceph-mgr ceph-mds ceph-osd ceph-fuse radosgw rbd-mirror cephfs-mirror || pkill -1 -x "ceph-mon|ceph-mgr|ceph-mds|ceph-osd|ceph-fuse|radosgw|rbd-mirror|cephfs-mirror" || true
> >     endscript
> >     missingok
> >     notifempty
> >     su root ceph
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @thenamehasbeentake
> 
> hi @sp98, @subhamkrai, log-collector runs with osds in `Deployments`, so multiple core dump logrotate instances will be running in one node. It's better to run `DaemonSet` to all nodes, one instance in one node.

@microyahoo IIRC, the log collector runs for every ceph pods and store logs on the node on which these ceph pods are deployed. If you check `LogCollectorContainer` function is called with all the ceph pods.

**Comment by microyahoo** [comment]
> @microyahoo IIRC, the log collector runs for every ceph pods and store logs on the node on which these ceph pods are deployed. If you check LogCollectorContainer function is called with all the ceph pods.

@subhamkrai, yes, but core dump logrotate is best run as a `DaemonSet`, not with all the ceph pods.
