### ISSUE TITLE
Kubernete cluster nodes hang after reboot with rook installation

### ISSUE THREAD

**Issue by yeo34th** [rook/rook#13204]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Installed Rook by following through quickstart page: https://rook.io/docs/rook/latest/Getting-Started/quickstart/ \
and kubeneretes cluster nodes hang after reboot with the following error message
`device-mapper: remove ioctl on vg00-var_lib_containerd  failed: Device or resource busy`

**Expected behavior:**

I would expect the kubeneretes cluster nodes to come up after reboot after installing rook.

**How to reproduce it (minimal and precise):**
With files from  https://github.com/rook/rook/tree/master/deploy/examples, run the following commands: \

- kubectl create -f crds.yaml
- kubectl create -f common.yaml
- kubectl create -f operator.yaml
- kubectl create -f cluster.yaml
- kubectl apply -f toolbox.yaml

**File(s) to submit:**
EC2 log obtained from console
[vm1_logs.txt](https://github.com/rook/rook/files/13351568/vm1_logs.txt)

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux 8.8 (Ootpa)
* Kernel (e.g. `uname -a`): 4.18.0-425.10.1.el8_7.x86_64
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): 1.10.13
* Storage backend version (e.g. for ceph do `ceph -v`): 17.2.6
* Kubernetes version (use `kubectl version`): v1.24.13
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): EC2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
1. Are you draining your nodes before restarting them? If not, the rbd volumes will not have a chance to unmount before the restart.
2. Is the volume from that error message an rbd volume?

**Comment by yeo34th** [comment]
> 1. Are you draining your nodes before restarting them? If not, the rbd volumes will not have a chance to unmount before the restart.
> I did not drain my nodes before restarting them. My team has a use case where the cluster should be able to come up again after a sudden power loss... 
>     2. Is the volume from that error message an rbd volume?
Volume from the error is the logical volume used for containerd which did not happen prior to rook installation

**Comment by travisn** [comment]
Have you created any rbd volumes? Or why do you suspect a Rook issue?

**Comment by yeo34th** [comment]
> Have you created any rbd volumes? Or why do you suspect a Rook issue?

yes I did. I provisioned an unformatted disk on each node to be used by rook. Used toolbox to confirm to confirm it is used by rook.

I suspect it has to do with Rook because that error only occurs when rebooting a kube node after installing Rook. I tested on over 10 ec2 instances to confirm it has do with Rook being installed on the node.

I saw that this is a common issue from  https://rook.io/docs/rook/v1.12/Troubleshooting/ceph-common-issues/#node-hangs-after-reboot but also noted that it has been fixed in Rook v1.3 or later (I am running v1.10.13)

**Comment by travisn** [comment]
The [solution](https://rook.io/docs/rook/v1.12/Troubleshooting/ceph-common-issues/#solution_6) indicates the node needs to be drained to smoothly recover.

**Comment by yeo34th** [comment]
Right I saw that from the page. 
I have a use case where the node should survive power outage or sudden reboot. 
If draining the node is the only solution to the problem, I assume Rook/ceph is not the right solution for my cluster?

**Comment by travisn** [comment]
Actually, I haven't heard of this issue for a long time, I also thought it would be fixed since v1.3. If the node is being suddenly powered off, it should come back online without any issues. How were you creating the rbd volumes. You did it in the toolbox? That's only for testing, it's not expected for production. Try creating a PVC and have an application pod running with the volume on the node. Then the CSI driver will properly handle the recovery.

**Comment by yeo34th** [comment]
I just went through the steps as indicated in the ticket with after provisioning unformatted disk and Rook pick it up automatically. 

In addition to the steps I have described in the ticket, I created filesystem and strorageclass then updated a service to use PVC using the rook storageclass to test rebooting with service using Rook but the node still didn't come up after reboot....

**Comment by pasztorl** [comment]
I also can report that stock ubuntu 22.04 + kubeadm k8s 1.27.9  + containerd 1.7.11 + latest rook + pods with rbd storage hangs if i run reboot command and never does reboot because ceph containers shuts down before other pods that uses rbd

**Comment by subhamkrai** [comment]
@pasztorl have you looked at this https://rook.io/docs/rook/latest/Storage-Configuration/Block-Storage-RBD/block-storage/#node-loss for rbd recovery?
