### ISSUE TITLE
Document how to create a storage class to consume a RADOS namespace

### ISSUE THREAD

**Issue by travisn** [rook/rook#13214]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The Rook documentation does not describe how to create a storage class that consumes a RADOS namespace. 

**Expected behavior:**
The Rook documentation should describe how to create a storage class that consumes a RADOS block pool. The steps are basically:
1. Create a CephBlockPool CR
2. Create a CephBlockPoolRadosNamespace CR
3. Extract the `clusterID` from the `status` of the CephBlockPoolRadosNamespace CR:

```
kubectl -n rook-ceph get cephblockpoolradosnamespace -o yaml
```
```yaml
  status:
    info:
      clusterID: 80fc4f4bacc064be641633e6ed25ba7e
```
4. Set the `clusterID` in the storage class to this value instead of the name of the cluster namespace.

This could be documented in the [CephBlockPoolRadosNamespace CRD topic](https://rook.io/docs/rook/latest/CRDs/Block-Storage/ceph-block-pool-rados-namespace-crd/)

**Comment by obnoxxx** [comment]
started looking into this.
As a preparation, here is a small improvement to the doc in question: #14167 14167
