### ISSUE TITLE
application not enabled on pool '.mgr'

### ISSUE THREAD

**Issue by SebTardif** [rook/rook#13210]
I used Helm chart:

      chart: rook-ceph
      version: ~1.12.7

with

      chart: rook-ceph-cluster
      version: ~1.12.7

Wait a while, then: kubectl rook-ceph ceph health detail

Return: 
```
Info: running 'ceph' command with args: [health detail]
HEALTH_WARN 1 pool(s) do not have an application enabled
[WRN] POOL_APP_NOT_ENABLED: 1 pool(s) do not have an application enabled
    application not enabled on pool '.mgr'
    use 'ceph osd pool application enable <pool-name> <app-name>', where <app-name> is 'cephfs', 'rbd', 'rgw', or freeform for custom applications.
```

I believe this is not expected since idea of rook is to do the right thing automatically.

I had to manually from the terminal run this command: kubectl rook-ceph ceph osd pool application enable .mgr mgr

**Comment by travisn** [comment]
There are two ways to create the .mgr pool. 
1. Define the CephBlockPool as in [this example](https://github.com/rook/rook/blob/master/deploy/examples/pool-builtin-mgr.yaml) and Rook will create the pool
2. Ceph will create the .mgr pool by default if Rook does not first create it.

In case 1, I see the `application: mgr` is set on the pool after Rook creates it:
```
pool 2 '.mgr' replicated size 3 min_size 2 crush_rule 2 object_hash rjenkins pg_num 32 pgp_num 1 pgp_num_target 32 autoscale_mode on last_change 24 lfor 0/0/24 flags hashpspool stripe_width 0 compression_mode none application mgr read_balance_score 3.03
```
In case 2, I see the `application: mgr` is set on the pool when ceph creates it by default.
```
pool 1 '.mgr' replicated size 1 min_size 1 crush_rule 0 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 12 flags hashpspool stripe_width 0 pg_num_max 32 pg_num_min 1 application mgr read_balance_score 3.03
```

For either case, I am not able to repro in my local minkube. The helm chart does not explicitly create the `.mgr` CephBlockPool, so ceph must be creating it by default. If you create the CephBlockPool CR does it make a difference?

**Comment by thangamani-arun** [comment]
I ses this error even now in Version
**19.2.2 (0eceb0defba60152a8182f7bd87d164b639885b8) squid (stable)** 

POOL_APP_NOT_ENABLED: 1 pool(s) do not have an application enabled
application not enabled on pool 'default.rgw.meta'
use 'ceph osd pool application enable <pool-name> <app-name>', where <app-name> is 'cephfs', 'rbd', 'rgw', or freeform for custom applications.

**Comment by thangamani-arun** [comment]
I ses this error even now in Version
**19.2.2 (0eceb0defba60152a8182f7bd87d164b639885b8) squid (stable)** 

POOL_APP_NOT_ENABLED: 1 pool(s) do not have an application enabled
application not enabled on pool 'default.rgw.meta'
use 'ceph osd pool application enable <pool-name> <app-name>', where <app-name> is 'cephfs', 'rbd', 'rgw', or freeform for custom applications.

**Comment by travisn** [comment]
@thangamani-arun What is the rook version? It is recent? Rook is expected to set the application on the rgw pools. Can you share the rook operator log?

**Comment by KKonak** [comment]
Also getting this error on Rook 1.19.3 with ceph 20.2.0 for the .mgr pool. I believe ceph is creating it as i dont define .mgr in rook-ceph-cluster helm charts. Is the guidance to define it so rook makes it instead?
[WRN] POOL_APP_NOT_ENABLED: 1 pool(s) do not have an application enabled
    application not enabled on pool '.mgr'
    use 'ceph osd pool application enable <pool-name> <app-name>', where <app-name> is 'cephfs', 'rbd', 'rgw', or freeform for custom applications.

**Comment by travisn** [comment]
@KKonak Yes, to avoid this warning, the recommendation would be to define the .mgr pool with a CephBlockPool CR, such as [this example](https://github.com/rook/rook/blob/master/deploy/examples/pool-builtin-mgr.yaml).
