### ISSUE TITLE
not able to access the ceph dashboard

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#13231]
we have installed rook-ceph on k8s and we have enabled the dashboard below is the cluster.yaml file which we have used, but dashboard is not able to access.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by rkachach** [comment]
@vadlakiran enabling the dashboard in the `cluster.yaml` is not enough. You have to create a dashboard service. Examples directory `rook/deploy/examples` comes with two example service specs `dashboard-external-https.yaml` and `dashboard-ingress-http.yaml` for secure and unsecure version. You can use anyone of them depending on your needs.

**Comment by rkachach** [comment]
@vadlakiran I'm closing this issue as no more information has been provided. Please, feel free to re-open in case you think it's a real BUG providing the detailed steps you followed to enable the dashboard.
