### ISSUE TITLE
RGW-Multisite-Test is failing in daily CI since Oct 31st

### ISSUE THREAD

**Issue by travisn** [rook/rook#13241]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The RGW-Multisite-Test is failing in the [daily CI](https://github.com/rook/rook/actions/workflows/daily-nightly-jobs.yml) for the past three weeks. The last time the job succeeded was on [Oct 30th](https://github.com/rook/rook/actions/runs/6700211113). 

This issue only affects the daily CI. When the same test runs in PRs or master/release branches, it is passing consistently. The difference of the daily CI is that it is using the tags `latest-main-devel`, `latest-quincy-devel`, `latest-reef-devel` as seen [here](`https://github.com/rook/rook/blob/master/.github/workflows/daily-nightly-jobs.yml#L362), instead of stable ceph release tags.

Since Oct 31st, the failures in the rgw multisite test include timing out waiting for the reconcile to no longer have updates needed as seen [here](https://github.com/rook/rook/actions/runs/6871074523/job/18687226428):

```
+ verify_operator_log_message 'there are no changes to commit for RGW configuration period for CephObjectStore "rook-ceph/zone-a"' rook-ceph
+ local 'message=there are no changes to commit for RGW configuration period for CephObjectStore "rook-ceph/zone-a"'
+ local namespace=rook-ceph
+ grep 'there are no changes to commit for RGW configuration period for CephObjectStore "rook-ceph/zone-a"'
+ kubectl --namespace rook-ceph logs deployment/rook-ceph-operator
+ sleep 5
+ [[ 603 -lt 600 ]]
+ echo 'timed out'
timed out
+ return 1
Error: Process completed with exit code 1.
```

And sometimes the error is that the CI times out just waiting for the build to complete before RGW is even configured. Not sure how this is related to RGW multisite, other than it is happening frequently since the same date as the other error above.
```
time="2023-11-16T00:17:05Z" level=info msg="Creating ../../build/csv/ceph/amd64/metadata/annotations.yaml"
time="2023-11-16T00:17:05Z" level=info msg="Creating bundle.Dockerfile"
time="2023-11-16T00:17:05Z" level=info msg="Bundle metadata generated successfully"
Error: The operation was canceled.
```

**Expected behavior:**
The daily CI is expected to pass consistently.

**Comment by BlaineEXE** [comment]
I'm not able to test this locally because Ceph does not build arm images with the `latest-X-devel

**Comment by BlaineEXE** [comment]
Exploring this via tmate debugging in #13250

**Comment by BlaineEXE** [comment]
This is what I see in the debug logs, and it is a little easier to see with live debugging. It seems that `radosgw-admin` is having problems getting info from RGW:

```console
[rook@rook-ceph-operator-6576499c89-tgwpk /]$ radosgw-admin period get --rgw-realm=realm-a --rgw-zonegroup=zonegroup-a --rgw-zone=zone-a --rgw-default-data-log-backing=omap --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
failed to load period: (5) Input/output error
2023-11-21T18:02:07.385+0000 7f99f443c780  0 ERROR: failed to decode obj from .rgw.root:periods.1e138cca-12b4-4999-908d-47e54e6f792d.2
```

I believe this is what happens when the version of `radosgw-admin` in the operator pod is lower than (and incompatible with) the version present in the Ceph image.

**Comment by BlaineEXE** [comment]
I wonder if the best solution to this issue would be to always "proxy" `radosgw-admin` commands through the mgr.

**Comment by travisn** [comment]
This isn't failing anymore
