### ISSUE TITLE
doc: Document steps to use read affinity feature with external ceph cluster.

### ISSUE THREAD

**Issue by Rakshith-R** [rook/rook#13243]
**Is this a bug report or feature request?**
* Documentation request

**What should the feature do:**
Document steps on how to configure read affinity for external ceph cluster and scenarios where it can be used.

**What is use case behind this feature:**
Read affinity feature can be particularly hepful with a external stretch ceph cluster.
Using this feature, we can configure ceph to serve reads from OSDs nearest to the kubernetes cluster.

refer: #13200

**Comment by travisn** [comment]
@Rakshith-R or @parth-gr Are you planning on working on this?

**Comment by parth-gr** [comment]
@travisn lemme take a look, thanks
