### ISSUE TITLE
Please support K8s on windows

### ISSUE THREAD

**Issue by AceHack** [rook/rook#1324]
Please add support for K8s on windows

**Comment by kokhang** [comment]
What errors are you seeing on Azure Container Service? I believe it should work.

**Comment by AceHack** [comment]
I'm using AKS right now, not ACS.  AKS only has linux worker nodes until the first of the year.  I didn't think ceph or this was supported on windows worker nodes which is why I asked.  I'll try and setup a ACS cluster with windows worker nodes for testing and let you know once I get the AKS linux worker nodes working first.

Thanks.

**Comment by kokhang** [comment]
@AceHack sorry for the confusion. Azure Container Service is AKS. I got it to work a few months back. Azure was spinning debian based VMs to create the kubernetes clusters. 

What errors are you seeing from AKS?

**Comment by AceHack** [comment]
I got rook working in AKS in Q1 they are adding windows server 2016 worker roles.  I would like to be able to use rook then.  Thanks.

**Comment by kokhang** [comment]
Rook currently uses ceph for its backend storage solution and ceph is primarily run in Linux and depends on kernel modules. I'm not sure if ceph could run on windows

**Comment by travisn** [comment]
Since Ceph doesn't support windows, not sure what we can do here. http://docs.ceph.com/docs/cuttlefish/faq/#do-ceph-clients-run-on-windows
