### ISSUE TITLE
rook-ceph-network-cluster-canary pod fails to use a NAD with an SRIOV interface

### ISSUE THREAD

**Issue by osnabrugge** [rook/rook#13245]
**Bug Report**

**Deviation from expected behavior:**
OSDs are able to make use of NetworkAttachmentDefinitions that contain an SRIOV interface, because you are able to apply resources so that they can request a node that has an available VF.  Since the introduction of the canary pod, clusters that make use of this can not be brought online as the pod fails to join.

This is similar to the issue here: https://github.com/rook/rook/issues/13138 except that the workaround will not work for me as I do not have a public NAD as I make use of the cluster network which multus defaults to (the Operator complains if you define an IP range without an associated NAD).

**Expected behavior:**
You should be able to apply resources to the canary pod though the CRDs / Helm Release values.yaml as you can with OSDs.  Resource constraints may not be the driver, but the ability to attach required resources.  Example below which works for OSDs:

    cephClusterSpec:
      resources:
        osd:
          requests:
            intel.com/sriov: 1
          limits:
            intel.com/sriov: 1

**How to reproduce it:**
Setup a cluster that contains:
- multus
- whereabouts
- nfd
- sriov (and sriov capable NIC with VFs defined).  

1. sriov-plugin will be defined to publish the resources which nfd will pick up an label the nodes with. 
2. Create a NAD defined for SRIOV and deploy Rook-Ceph cluster with multus network leveraging this NAD and the OSDs to request the SRIOV VF resources. 
3. Operator will spin up canary which will fail to start as it cannot request a VF.

Example NAD:
```---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: storage-sriov-conf
  namespace: kube-system
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "sriov",
      "vlan": 50,
      "spoofchk": "off",
      "trust": "on",
      "ipam": {
        "type": "whereabouts",
        "range": "10.0.3.0/16",
        "range_start": "10.0.3.100",
        "range_end": "10.0.3.120"
      }
    }'
```

File(s) to submit:

Canary Pod does not start, (shortened error message):

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "7cdb4b8cbbc546e7428110de16f2734cb227ad306912e8fb258ff22cc76298b7": plugin type="multus-shim" name="multus-cni-network" failed (add): CmdAdd (shim): CNI request failed with status 400: '&{ContainerID:7cdb4b8cbbc546e7428110de16f2734cb227ad306912e8fb258ff22cc76298b7 Netns:/var/run/netns/cni-3*****ERRORED: error configuring pod [rook-ceph/rook-ceph-network-cluster-canary-d5hsb] networking: [rook-ceph/rook-ceph-network-cluster-canary-d5hsb/0bf185ac-17b7-45de-8488-51891fa53554:storage-sriov-conf]: error adding container to network "storage-sriov-conf": SRIOV-CNI failed to load netconf: LoadConf(): VF pci addr is required '
```

**Cluster Status to submit**:

Cluster has not been created due to issue (this is a rebuild).

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 12 (bookworm) x86_64
* Kernel (e.g. `uname -a`): 6.1.0-13-amd64
* Cloud provider or hardware configuration: 6 worker nodes with NVME storage, 10Gbps SRIOV network (4VFs) and 1Gbps for Kubernetes cluster network.
* Rook version (use `rook version` inside of a Rook Pod): Rook v1.12.8
* Storage backend version (e.g. for ceph do `ceph -v`): N/A
* Kubernetes version (use `kubectl version`): v1.28.3+k3s2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): N/A

**Comment by BlaineEXE** [comment]
The canary pod uses the 'osd' placement from the CephCluster. If that placement is not configured to place OSDs on nodes where SRIOV PCI devices are present, the canary will fail.

**Comment by osnabrugge** [comment]
Thank you for the quick response @BlaineEXE.  

The canary pod does attempt to attach itself to the right host by placement strategy and it also includes the right NAD in its annotation required by multus.   The challenge is that if SRIOV has been defined as a plugin within that NAD, the SRIOV plugin will fail if the pod does not also have a [VF resource request](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin#example-deployments) and the following error message is given:

```error adding container to network "storage-sriov-conf": SRIOV-CNI failed to load netconf: LoadConf(): VF pci addr is required``` (apologies, this was at the very end of the error message that I included in my post and is the same message any pod gets, not just rook specific).

The pain is that SRIOV VFs are [extended resources ](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#consuming-extended-resources)and a NAD cannot make the request, but rather through the pod spec itself just like other resource requests and limits.  That being said, we have been able to adjust the [OSD pod resources](https://github.com/rook/rook/blob/19a176236b8074fb89a2d1d7cf3f1c01c242e7f4/deploy/charts/rook-ceph-cluster/values.yaml#L287C1-L293C22) which is why we have been able to use SRIOV with Rook up until now.

Does this help clear up the issue and what has broken?  Let me know if you need anything more or have any clever ideas for a workaround?

**Comment by BlaineEXE** [comment]
I think I understand, but I'm not experienced with this use-case. I don't have the privilege of an SRIOV environment to do testing in, or experience with one to understand all of the requirements.

I think that the only additional requirement is to be able to set resource configurations on the network canary pods. This will take some time to fix in code.

In the meantime, I'd like to understand why the workaround won't work for you.

> the workaround will not work for me as I do not have a public NAD as I make use of the cluster network which multus defaults to (the Operator complains if you define an IP range without an associated NAD).

You cannot define an IP range without an associated NAD because the NAD is always a requirement. Without the NAD, Ceph has nothing to bind to in the OSD pod. The IP range allows one to override Rook and tell Ceph the IP range(s) directly, rather than having Rook attempt to auto-detect it. If you don't use a public NAD, don't specify an IP range for the public network. Additionally, you must always specify IP ranges for the cluster network that are compatible with your SRIOV network -- that looks like "10.0.3.0/16" to me, based on your NAD configuration.

Does that allow you to work around the issue for now? If not, please provide more information, including the specific configs that are not working and the failures you're seeing.

**Comment by osnabrugge** [comment]
Glad that helped to clear things up.  It's really no different from other extended resources (GPUs, HugePages, USB devices, etc.) where they can be dynamically allocated on pod creation.  SRIOV itself just allows a single NIC to be virtualized and shared with multiple virtual machines / containers (some GPUs have this capability too).  It's more efficient, but the main appeal for me is that I can leave the network mostly unconfigured and instead of another SDN tool, leverage by GitOps via Kubernetes.. 

I might be able to help test it out if a fix ends up on the roadmap.  I say this, as I found a solution and not sure there's a alarge demand to prioritize this fix (hopefully it is not to complex - perhaps a regex to select any additional key pairs added to the OSD resource spec on the cluster CRD?).  I'm surprised that I only discovered it today as it's from the same group that maintains multus, whereaabouts, sriov-cni and sriov-plugin: [NPWG: Network Resource Injector](https://github.com/k8snetworkplumbingwg/network-resources-injector).  They essentially got around this problem by creating a mutating webhook, so instead of needing to mess with the pod's spec, the admin can now create a policy that reacts when any pod with the NAD spawns and patches it on the fly.  Worked flawlessly against the canary pod.

As for the other issue, I discovered it when attempting to use your workaround.  The Rook Operator expects that a corresponding NAD (Public and/or Cluster) is present if you define an IP address range.  I am using multus only on the cluster network and the public network does not have a NAD which multus by design will attach that interface to the default Kubernetes network.  It's actually documented by Rook too (something I verified before I went down this path as we both know 'supported' and 'works' are two very different things):

> NetworkAttachmentDefinitions are selected for the desired Ceph network using selectors. Selector values should include the namespace in which the NAD is present. public and cluster may be selected independently. [If public is left unspecified, Rook will configure Ceph to use the Kubernetes pod network for Ceph client traffic. ](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#multus) (scroll down as there was no anchor nearby).

Technically you are not blind.  If you know that a NAD is not defined, multus will attach that interface to the pod's internal/default network.  Could you query the api server for the Kubernetes cluster CIDR?

I was really happy to see your clever workaround, but quickly disappointed when the Rook Operator gave an error that I should not define an IP range when I do not have a NAD for the public network.  I actually chased that for a bit to see if there was any CNIs that I could use to create a NAD but keep the traffic inside the cluster.  I was really between a rock and hard place as it isn't like I could restore with different networks as changing after is not supported.  My apologies for not capturing the error message, but at least it is much easier to reproduce than needing SR-IOV hardware.

Thank you again for the quick support.  Although I am up and working, happy to help with both of these issues. Should I leave this issue open until you determine what the next steps are for those two bugs?

**Comment by osnabrugge** [comment]
I am glad to hear that this is triggering some updates to help out new users.

Here are a few suggestions for the doc updates:

- At least one NAD is required for the Ceph cluster network.
  - Might be useful to be explicit on the logic for multus when the Ceph public network is undefined (no NAD). 
- Doc updates (unless other scenarios for extended resources?):
  - [Resources Configuration Settings](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#cluster-wide-resources-configuration-settings)
    - Only the 'osd' pods get a cluster network attached (and canary) per the [current docs](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#multus)
    - Considerations for [node specific settings](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#node-specific-resources-for-osds) (nodes may have differing hardware/resources)
  - SR-IOV which would be a subset of [multus in the docs](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#multus)
    - Links to[ SRIOV-Plugin](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin) and [Kubernetes extended resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#extended-resources)
    - Cross-reference to the resource configuration settings

---

For these doc updates, they require code changes:

1. Operator startup (other services/events?) halts with an error message when public network is given an IP range and no NAD.
> * address(es) can optionally be provided in addition to the NAD (or NADs) to override (and bypass) Rook's auto-detection attempt
2. Defining the resources in the cluster spec is blocked due to canary. Resource do not need to be defined in the cluster spec when using network resource injector.
> * ensure docs reflect the right place to set this (probably 'all'/'osd' resources in CephCluster)

**Comment by BlaineEXE** [comment]
Thanks for the additional inputs. Getting the perspective of a user is very valuable.

> Might be useful to be explicit on the logic for multus when the Ceph public network is undefined (no NAD).

This is covered by the introductory section of the Network Configurations Settings doc today:
https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/?h=multus#ceph-public-and-cluster-networks
> Ceph daemons always use the public network, which is the Kubernetes pod network by default.

It seems like it would be useful to add a cross-link to this from the multus config section, however, as a reminder.
