### ISSUE TITLE
rook-api Error syncing pod on Azure AKS

### ISSUE THREAD

**Issue by AceHack** [rook/rook#1325]
**Bug Report**

What happened:
rook-api failed to start

What you expected to happen:
rook-api to start

How to reproduce it (minimal and precise):

Create AKS cluster 1.8.1 on Azure, 5 node, 300GB SSD OS Drive
Upgrade AKS cluster to 1.8.2
helm install --name rook --namespace rook-system rook-alpha/rook --set rbacEnable=false
kubectl create -f rook-cluster.yaml

Files included

[RookError.zip](https://github.com/rook/rook/files/1565906/RookError.zip)

**Comment by galexrt** [comment]
@AceHack Are there any logs produced for the rook-api Pod when it crashes?

**Comment by AceHack** [comment]
root@rook-tools:/# ceph status
  cluster:
    id:     3d3e5578-0b99-4529-bc2c-adfeeaacbc87
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum rook-ceph-mon1,rook-ceph-mon0,rook-ceph-mon2
    mgr: rook-ceph-mgr0(active), standbys: rook-ceph-mgr1
    osd: 5 osds: 5 up, 5 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 bytes
    usage:   105 GB used, 1448 GB / 1553 GB avail
    pgs:

root@rook-tools:/# rookctl status
failed to get status: Get http://10.0.31.91:8124/status: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by AceHack** [comment]
2017-12-17 18:37:57.483751 I | rook: starting Rook v0.6.0-96.g043cd8b with arguments '/usr/local/bin/rook api --config-dir=/var/lib/rook --port=8124 --hostnetwork=false' 
2017-12-17 18:37:57.483839 I | rook: flag values: --admin-secret=*****, --ceph-config-override=, --cluster-name=rook, --config-dir=/var/lib/rook, --fsid=, --help=false, --hostnetwork=false, --log-level=INFO, --mon-endpoints=rook-ceph-mon0=10.0.88.240:6790,rook-ceph-mon1=10.0.66.34:6790,rook-ceph-mon2=10.0.114.254:6790, --mon-secret=*****, --namespace=rook, --port=8124, --private-ipv4=127.0.0.1, --public-ipv4=127.0.0.1 
failed to get container image. cannot detect the pod name. Please provide it using the downward API in the manifest file

**Comment by kokhang** [comment]
This may be a dup of https://github.com/rook/rook/issues/1318.

Can you try the workaround steps on that issue?

**Comment by AceHack** [comment]
I don't see the work around.

He says "I was doing a completely new installation of rook when I encountered this issue so Its not an upgrade problem. Ive currently worked around it by editing the deployment and manually adding the required env vars"

But does not mention what env vars to add.

**Comment by AceHack** [comment]
I got it working when using master helm chart instead of alpha helm chart

**Comment by travisn** [comment]
Ok, if you are using the alpha helm chart, you would need to use the alpha rook-cluster.yaml that still has the `versionTag` property. For example, see https://github.com/rook/rook/blob/release-0.6/cluster/examples/kubernetes/rook-cluster.yaml

**Comment by AceHack** [comment]
which one is the newer of the two?  master or alpha?

**Comment by travisn** [comment]
Let's track this issue with #1318
