### ISSUE TITLE
Toolbox pod enhancements

### ISSUE THREAD

**Issue by anthonyeleven** [rook/rook#13263]
When execking a shell into a Rook toolbox pod, the `rook` user's home directory appears to be within the pod, not inherited from the host system.  So, no environment customization is inherited from the underlying host.  In general this is probably for the best, but in some ways it's inconvenient.

E.g. with `export HISTTIMEFORMAT='%F %T '` in `/home/rook/.bashrc`

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
When one execs a shell in a toolbox pod and runs `history`, the history items by default do not show a timestamp.  Why Bash elects to default this way eludes me; I'm pretty sure tcsh defaulted to showing timestamps.

Also, if possible, please add `mg` to the packages installed in the toolbox pod.  When I have occasion to edit a file. e.g. `s5cmd` credentials, having to use `vi` is awkward.

**What is use case behind this feature:**
It is often useful to know when commands were executed.

```
aad@LovecraftNAS:/$ history 3
  367  history 3
  368  export HISTTIMEFORMAT='%F %T '`
  369  history 3
aad@LovecraftNAS:/$ export HISTTIMEFORMAT='%F %T '
aad@LovecraftNAS:/$ history 3
  369  2023-11-26 23:23:30 history 3
  370  2023-11-26 23:23:36 export HISTTIMEFORMAT='%F %T '
  371  2023-11-26 23:23:38 history 3
aad@LovecraftNAS:/$
```

**Environment**:

Toolbox pod shell

**Comment by anthonyeleven** [comment]
done.  Example text is not from a toolbox pod but conveys the idea.

**Comment by travisn** [comment]
@anthonyeleven Have you considered using the [Rook kubectl plugin](https://rook.io/docs/rook/latest/Troubleshooting/kubectl-plugin/)? This should allow better flexibility to inherit your local env, instead of trying to tweak the toolbox to work with it.

**Comment by anthonyeleven** [comment]
That's `krew`?  I saw a presentation at Cephalocon but had not realized that it accommodates a full CLI.

**Comment by anthonyeleven** [comment]
The plugin has some value, but it does not AFAICT support any `radosgw-admin` functionality, so the toolbox is still needed.

**Comment by travisn** [comment]
> The plugin has some value, but it does not AFAICT support any `radosgw-admin` functionality, so the toolbox is still needed.

@anthonyeleven Would you mind opening an issue in the [kubectl-rook-ceph](https://github.com/rook/kubectl-rook-ceph/issues) repo with this request? @subhamkrai could take a look.

**Comment by anthonyeleven** [comment]
https://github.com/rook/kubectl-rook-ceph/issues/253 btw

**Comment by travisn** [comment]
> [rook/kubectl-rook-ceph#253](https://github.com/rook/kubectl-rook-ceph/issues/253) btw

Even better thanks!

**Comment by anthonyeleven** [comment]
bump

**Comment by travisn** [comment]
`radosgw-admin` support was added to the [kubectl v0.9.1 release](https://github.com/rook/kubectl-rook-ceph/releases/tag/v0.9.1). Any other gaping holes that prevent using it instead of modifying the toolbox?

**Comment by anthonyeleven** [comment]
Nice, thanks.  Not immediately, though I have switched companies and no longer am interacting much with Rook, modulo Atmosphere for some reason using it to deploy only RGW.

**Comment by travisn** [comment]
Ok thanks for the feedback, we'll close this since no more gaps reported.
