### ISSUE TITLE
Create tools to autocleanup dataDirHostPath

### ISSUE THREAD

**Issue by AceHack** [rook/rook#1326]
Please create in tools a way to run a single command line to clean up all dataDirHostPath from all hosts when reinstalling.

**Comment by kokhang** [comment]
I think a better way to handle this would be to have the cluster listen for sig term signal and cleanup this directory when it happens

**Comment by bassam** [comment]
When we move to local storage #796 the admin would need to remove the PV for the OSD explicitly, and that can be done from kubectl.

**Comment by jbw976** [comment]
Thanks @AceHack, we can definitely make improvements for managing the lifecycle of config/metadata in Rook clusters.  Besides the long term local storage effort in #796, a more short term effort will be tracked in #1490.
