### ISSUE TITLE
rabbitmq not binding to block storage

### ISSUE THREAD

**Issue by AceHack** [rook/rook#1327]
**Bug Report**

What happened:
rabbitmq failed with:
PersistentVolumeClaim is not bound: "rabbitmq-rabbitmq" (repeated 5 times) 

What you expected to happen:
rabbit to start sucessfully

How to reproduce it (minimal and precise):

Create AKS cluster 1.8.2 on Azure, 5 node, 300GB SSD OS Drive
```
helm install --name rook --namespace rook-system rook-master/rook --set rbacEnable=false
kubectl create -f rook-cluster.yaml
kubectl create -f rook-storageclass.yaml
helm install --name rabbitmq --set persistence.storageClass=rook-block stable/rabbitmq
```
Logs
```
root@rook-tools:/# ceph status
  cluster:
    id:     c3628414-b9f4-46f8-8bd8-9648d45e0435
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum rook-ceph-mon1,rook-ceph-mon2,rook-ceph-mon0
    mgr: rook-ceph-mgr0(active), standbys: rook-ceph-mgr1
    osd: 5 osds: 5 up, 5 in

  data:
    pools:   1 pools, 100 pgs
    objects: 1 objects, 8 bytes
    usage:   105 GB used, 1448 GB / 1553 GB avail
    pgs:     100 active+clean

root@rook-tools:/# rookctl status
OVERALL STATUS: OK

USAGE:
TOTAL      USED         DATA      AVAILABLE
1.52 TiB   105.03 GiB   8 B       1.41 TiB

MONITORS:
NAME             ADDRESS               IN QUORUM   STATUS
rook-ceph-mon1   10.0.85.215:6790/0    true        OK
rook-ceph-mon2   10.0.131.231:6790/0   true        OK
rook-ceph-mon0   10.0.253.167:6790/0   true        OK

MGRs:
NAME             STATUS
rook-ceph-mgr0   Active
rook-ceph-mgr1   Standby

OSDs:
TOTAL     UP        IN        FULL      NEAR FULL
5         5         5         false     false

PLACEMENT GROUPS (100 total):
STATE          COUNT
active+clean   100
```

**Comment by AceHack** [comment]
Here is what rabbit logged:

NAME:   rabbitmq
LAST DEPLOYED: Mon Dec 18 04:14:11 2017
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME               DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
rabbitmq-rabbitmq  1        1        1           0          1s

==> v1/Pod(related)
NAME                                READY  STATUS   RESTARTS  AGE
rabbitmq-rabbitmq-8549bd9556-f5vj8  0/1    Pending  0         1s

==> v1/Secret
NAME               TYPE    DATA  AGE
rabbitmq-rabbitmq  Opaque  2     1s

==> v1/PersistentVolumeClaim
NAME               STATUS   VOLUME      CAPACITY  ACCESS MODES  STORAGECLASS  AGE
rabbitmq-rabbitmq  Pending  rook-block  1s

==> v1/Service
NAME               TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)                                AGE
rabbitmq-rabbitmq  ClusterIP  10.0.75.19  <none>       4369/TCP,5672/TCP,25672/TCP,15672/TCP  1s

**Comment by AceHack** [comment]
Here is the claim:

{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "rabbitmq-rabbitmq",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/persistentvolumeclaims/rabbitmq-rabbitmq",
    "uid": "cf720778-e3d3-11e7-84fd-0a58ac1f0abb",
    "resourceVersion": "20589",
    "creationTimestamp": "2017-12-18T09:14:11Z",
    "annotations": {
      "control-plane.alpha.kubernetes.io/leader": "{\"holderIdentity\":\"68fbf955-e3cf-11e7-a74a-0a580af40005\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2017-12-18T09:14:11Z\",\"renewTime\":\"2017-12-18T09:31:13Z\",\"leaderTransitions\":0}",
      "volume.beta.kubernetes.io/storage-provisioner": "rook.io/block"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "8Gi"
      }
    },
    "storageClassName": "rook-block"
  },
  "status": {
    "phase": "Pending"
  }
}

**Comment by galexrt** [comment]
@AceHack Please also post the logs of the rook-operator as a gist.

**Comment by AceHack** [comment]
@galexrt https://gist.github.com/AceHack/d0779b9f9935f2ad412e2dc0afe77a3a

**Comment by AceHack** [comment]
Okay thanks for pointing me to your logs. I may have found the issue.

pool missing required overwrite support

http://tracker.ceph.com/projects/ceph/wiki/Osd_-_erasure_coding_pool_overwrite_support

I'm going to try a replica pool instead of ec pool, I'll let you know how it goes.
Thanks.

**Comment by DanKerns** [comment]
@AceHack , @galexrt : It looks like this is supported but you need to enable it.  See: http://ceph.com/community/new-luminous-erasure-coding-rbd-cephfs/

You need to run a command like `ceph osd pool set POOL_NAME allow_ec_overwrites true`

I wonder how Rook should enable this through the CRD's or if it should always be enabled.

**Comment by AceHack** [comment]
Using replica worked great, thanks for all the help!!

**Comment by AceHack** [comment]
@galexrt I would rather use ecpool, would love to know how to enable that!!  Thanks.

**Comment by galexrt** [comment]
@AceHack I suggest you checkout https://rook.io/docs/rook/master/toolbox.html to run the rook toolbox, which allows you to run the command written by @DanKerns.
If you can join our Slack, I can guide you through the procedure.

**Comment by AceHack** [comment]
Is there any reason this can't be turned on by default or at least with a flag when creating the pool?

**Comment by travisn** [comment]
We do set this property for EC pools that are used by the file system. I believe we should just set it automatically by default as well for any EC pool, but still need to read the docs closer to confirm if there is a reason not to do that.

**Comment by AceHack** [comment]
@travisn @galexrt 

I just ran the command and got a new error

ERROR: logging before flag.Parse: E1219 07:18:54.728748       8 goroutinemap.go:165] Operation for "provision-default/test-pv-claim[db845fce-e48c-11e7-84fd-0a58ac1f0abb]" failed. No retries permitted until 2017-12-19 07:18:55.728730578 +0000 UTC m=+81378.587054464 (durationBeforeRetry 1s). Error: Failed to create rook block image ec-block-pool/pvc-db845fce-e48c-11e7-84fd-0a58ac1f0abb: failed to create image pvc-db845fce-e48c-11e7-84fd-0a58ac1f0abb in pool ec-block-pool of size 1073741824: Failed to complete : exit status 95. output: 2017-12-19 07:18:54.707636 7f6e1b7fe700 -1 librbd::image::CreateRequest: 0xde48997c00 handle_add_image_to_directory: error adding image to directory: (95) Operation not supported 

very simple yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ec-block

**Comment by AceHack** [comment]
If it's any help I have my sc yaml too

apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: ec-block-pool
  namespace: rook
spec:
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ec-block
provisioner: rook.io/block
parameters:
  pool: ec-block-pool

**Comment by galexrt** [comment]
@AceHack Could you try the same with a `replicated` pool, see https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-pool.yaml#L10-L11.

I'm guessing that there is more than just this one command to watch out for when using an erasure coded pool for RBD (and CephFS) as can be seen in this section in the Ceph docs see http://docs.ceph.com/docs/master/rados/operations/erasure-code/#erasure-coding-with-overwrites.

**Comment by AceHack** [comment]
@galexrt yeah replicated pool works fine, I was just really hoping to use EC pool.  Is this expected to be supported in the future?

**Comment by galexrt** [comment]
@AceHack I personally wouldn't use EC pools for any other use cases than object store because I think that there is a good reason why the Ceph docs state:
> By default, only work with uses like RGW that perform full object writes and appends
> Source: http://docs.ceph.com/docs/master/rados/operations/erasure-code/#erasure-coding-with-overwrites

I think that we should discuss this topic further to see we should really support EC pools for other uses than object store.

**Comment by DanKerns** [comment]
@galexrt the very next sentence in the document you reference indicates that since Luminous they are supported with some caveats.  These are things the operator can easily support.

**Comment by AceHack** [comment]
@galexrt Should I make another top-level issue for EC pools and block storage?

**Comment by galexrt** [comment]
@AceHack Yes, that would be good.
I think we can close this issue as it seems to be caused by the operator not having the feature to enable the EC overwrite flag/toggle (`allow_ec_overwrites`) on Pools.
Is that okay for you?

**Comment by travisn** [comment]
Sounds good to open a new issue and reference this one. I was looking at a design for the changes so will comment on the new issue, thanks.

**Comment by AceHack** [comment]
Closing this issue and opening a feature request
https://github.com/rook/rook/issues/1360
