### ISSUE TITLE
Rollback steps

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#13284]
Hi Team,

we have installed rook-ceph in k8s cluster version v1.21.5 and rook-ceph version is v1.8.1 is running i am going to upgrade to v1.11.1 version, if its fail is there any roll back steps is there ?

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
See the [upgrade guide](https://rook.io/docs/rook/latest/Upgrade/rook-upgrade/) for the steps to upgrade from version to version. There is not a rollback guide, as there can be unknown issues with rollback especially when upgrading the data layer (ceph). If you're just upgrading Rook, you might be able to roll back by applying previous manifests, but rolling back is not tested.

**Comment by vadlakiran** [comment]
@travisn will it be possible to downgrade a ceph version from v17.2.6 to v16.2.10  ?

**Comment by travisn** [comment]
> @travisn will it be possible to downgrade a ceph version from v17.2.6 to v16.2.10 ?

It's not recommended to downgrade, especially across Ceph major releases. But if you have a staging environment where you can test it, it might be possible even if not supported.
