### ISSUE TITLE
Object store metadata should have the same durability as object store data

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#1328]
**Feature Request**

What should the feature do:

When you create an object store various ceph pools are created. The data pool(s) are created with the durability settings from the CRD but the metadata pools are always replicated. The metadata pools should have the same durability settings as the data pools by default (could be overridden for performance?)

What would be solved through this feature:

A user who configures their object store with five check disks would expect to survive any five-node failure. However, metadata is replicated (by default three times) and so this isn't true. This change would align the durability settings and by default prioritize durability.

It looks like erasure coding overwrites need to be enabled on the metadata pools with a command like 'ceph osd pool set POOL_NAME allow_ec_overwrites true'

**Comment by travisn** [comment]
based on documentation linked from #1360 and investigating its design, it doesn't appear possible to use erasure coded pools for metadata, but I will try it to confirm.

**Comment by liewegas** [comment]
Correct: some EC pools do not support omap and cannot be used for rgw indexes or rbd metadata.

**Comment by liewegas** [comment]
or cephfs metadata

**Comment by travisn** [comment]
thanks @liewegas for confirming
