### ISSUE TITLE
installation not possible in Rancher via HELM 

### ISSUE THREAD

**Issue by smirnov-mi** [rook/rook#13296]
As mentioned in slack (with no feedback yet),

trying to install rook-ceph via HELM in Rancher (latest, 2.7.9)

getting following errors:

helm install --generate-name=true --namespace=rook-ceph --timeout=10m0s --values=/home/shell/helm/values-rook-ceph-v1.12.8.yaml --version=v1.12.8 --wait=true /home/shell/helm/rook-ceph-v1.12.8.tgz
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "objectstorage-provisioner-role" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "[app.kubernetes.io/managed-by](http://app.kubernetes.io/managed-by)": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rook-ceph-v1-1701345965"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "rook-ceph"

helm install --generate-name=true --namespace=rook-ceph --timeout=10m0s --values=/home/shell/helm/values-rook-ceph-v1.12.6.yaml --version=v1.12.6 --wait=true /home/shell/helm/rook-ceph-v1.12.6.tgz
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "objectstorage-provisioner-role" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rook-ceph-v1-1701352088"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "rook-ceph"

Having NO namespace created , different error message appears:

helm install --timeout=10m0s --values=/home/shell/helm/values-rook-ceph-v1.12.8.yaml --version=v1.12.8 --wait=true rook-ceph /home/shell/helm/rook-ceph-v1.12.8.tgz
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "objectstorage-provisioner-role" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rook-ceph"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"

**Environment**:
Latest Rancher 2.7.9
Kubernetes cluster 1.26.9 on external VMs
rook-ceph "classical" installation removed just yesterday

**Comment by smirnov-mi** [comment]
I managed to install the first part (operator) after following:
1) start installation in the new namespace (failed, but NS was created);

2) manually removing following:
k delete  clusterrole objectstorage-provisioner-role
k delete clusterrolebinding cephfs-csi-nodeplugin-role objectstorage-provisioner-role-binding

3) adding following into defailt values.yaml:
app.kubernetes.io/managed-by: Helm
meta.helm.sh/release-name: rook-ceph
meta.helm.sh/release-namespace: rook-ceph

**Comment by travisn** [comment]
Did you have a previous install of Rook where you uninstalled and now you're trying to create the helm chart? The helm chart won't install if there are any of the resources leftover from the other install. Good to hear that you were able to get the operator installed now.

**Comment by smirnov-mi** [comment]
I had an "old school" installation removed indeed, going through all the steps in the official "teardown" howto. One thing was missing there indeed. I now ended up trying to install a new cluster via helm, made a mistake enabling the toolbox. It didn't come up in the 10 minutes and the whole installation went into the failed state. Now my rancher lost the connection to the rook repository.

**Comment by travisn** [comment]
Also see the [Troubleshooting guide](https://rook.io/docs/rook/latest/Troubleshooting/common-issues/).

**Comment by smirnov-mi** [comment]
I have it installed and running now, I figured out my cluster was out of CPUs, since the "example" storage classes require way more resources than my small configuration before. After adding more CPUs, removing object-storage and radically scale down the "requests" for all components in the cluster configuration, all the components came up with no errors so far.
