### ISSUE TITLE
docs: explain "too few PGs per OSD" warning

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1329]
In a lot of scenarios, the ceph status will show something like `too few PGs per OSD (25 < min 30)`, which can be fairly benign.  The consequences of too few PGs is much less severe than the consequences of too **many** PGs, as explained in this ceph blog post:
http://ceph.com/community/new-luminous-pg-overdose-protection/
> If you have way less than that the load distribution won’t be as balanced (some OSDs will store more than others), and if you have too many more than that then each OSD will be coordinating with too many other OSDs, increasing overhead and reducing overall reliability.

We should mention this in the docs/FAQs somewhere.

**Comment by pavgup** [comment]
Just ran into exactly this issue; this leaves the cluster in an "HEALTH_WARN" status, but it's unclear if this is truly a warning or something potentially more serious. I suspect docs here might be really awesome...

**Comment by MatthiasLohr** [comment]
Yes, please!

**Comment by ShakataGaNai** [comment]
Still an issue it seems. Just ran into this as well.

**Comment by philipp1992** [comment]
can someone exlain this please and how to fix?

TOO_FEW_PGS: too few PGs per OSD (26 < min 30)

**Comment by galexrt** [comment]
The warning is nothing to worry about as long as you are using a recent Ceph and Rook Ceph version (which enables the MGR (PG) balancer module).

The Ceph MGR (PG) balancer module will automatically increase (if I remember correctly even decrease) the amount of PGs per Pool as needed depending on how much data you store in the pools.

We should document this, though a new Ceph cluster will always end up in `HEALT_WARN` state until it is "used" enough for "enough" PGs to be created "per OSD".

**Comment by ShakataGaNai** [comment]
@philipp1992 - Just spin up a 2nd CephBlockPool's (a dummy one with no data, if you want). I ended up using the [storageclass-ec.yaml](https://github.com/rook/rook/blob/release-1.3/cluster/examples/kubernetes/ceph/csi/rbd/storageclass-ec.yaml) example, it runs 2 CBP's which solved the "too few PG" warning.
