### ISSUE TITLE
Refactor OSD removal

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#13292]
**Is this a bug report or feature request?**
* Bug Report
Originally posted  https://github.com/rook/rook/pull/13281#discussion_r1409591571

OSD removal code needs to be refactored https://github.com/rook/rook/blob/a19860bab0566f4d7c31170aa9191eed02a4c4cc/pkg/daemon/ceph/osd/remove.go#L89-L118

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by obnoxxx** [comment]
@subhamkrai , I am not quite convinced  that I would consider the need to refactor code as a bug. sounds like technical debt to me. Addressing this would result in a general improvement, imho. Not sure about the bugfix nature .


@travisn , @BlaineEXE - what do you think? - also not sure that this comment is relevant at all ...

**Comment by BlaineEXE** [comment]
I don't care strongly about arguing semantic differences in this case. This was created as a direct follow-up to some other work, and in that light, I could be convinced to categorize it either way. We don't have a `chore` or `cleanup` category like other projects.
