### ISSUE TITLE
Codegen CI should fail if not updated

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13290]
I haven't seen any PRs failing with the codegen being outdated. @parth-gr Did you see any failures, or could you look at if there is an issue with that codegen CI check? Thanks!

_Originally posted by @travisn in https://github.com/rook/rook/pull/13282#pullrequestreview-1753621435_

**Comment by parth-gr** [comment]
runner@fv-az889-966:~/work/rook/rook$ make codegen
mkdir -p /home/runner/work/rook/rook/.cache/tools/linux_amd64
curl -sL https://github.com/kubernetes/code-generator/archive/refs/tags/v0.20.0.tar.gz | tar -xz -C /home/runner/work/rook/rook/.cache/tools/linux_amd64
go: downloading github.com/spf13/pflag v1.0.5
go: downloading k8s.io/gengo v0.0.0-20201113003025-83324d819ded
go: downloading k8s.io/klog/v2 v2.4.0
go: downloading github.com/go-logr/logr v0.2.0
go: downloading golang.org/x/tools v0.0.0-20200616133436-c1934b75d054
go: downloading golang.org/x/mod v0.3.0
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
/opt/hostedtoolcache/go/1.20.11/x64/src/go/types/initorder.go:8:2: package container/heap is not in GOROOT (/opt/hostedtoolcache/go/1.20.11/x64/src/container/heap)
/opt/hostedtoolcache/go/1.20.11/x64/src/net/cgo_unix.go:20:2: cannot find package
/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/covercounter.go:8:2: package internal/coverage/rtcov is not in GOROOT (/opt/hostedtoolcache/go/1.20.11/x64/src/internal/coverage/rtcov)
/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/mgcpacer.go:9:2: open /opt/hostedtoolcache/go/1.20.11/x64/src/internal/goexperiment/exp_pagetrace_on.go: no such file or directory
/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/extern.go:243:2: package internal/goos is not in GOROOT (/opt/hostedtoolcache/go/1.20.11/x64/src/internal/goos)
/opt/hostedtoolcache/go/1.20.11/x64/src/go/types/api.go:34:2: package internal/types/errors is not in GOROOT (/opt/hostedtoolcache/go/1.20.11/x64/src/internal/types/errors)
/opt/hostedtoolcache/go/1.20.11/x64/src/go/constant/value.go:18:2: open /opt/hostedtoolcache/go/1.20.11/x64/src/math/big/arith_s390x_test.go: no such file or directory
/opt/hostedtoolcache/go/1.20.11/x64/src/internal/reflectlite/value.go:10:2: open /opt/hostedtoolcache/go/1.20.11/x64/src/runtime/runtime-gdb_test.go: no such file or directory
package k8s.io/code-generator/cmd/defaulter-gen
        imports github.com/spf13/pflag
        imports net: cannot find package
/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/arena.go:87:2: package runtime/internal/atomic is not in GOROOT (/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/internal/atomic)
/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/arena.go:88:2: package runtime/internal/math is not in GOROOT (/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/internal/math)
/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/cgocall.go:89:2: package runtime/internal/sys is not in GOROOT (/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/internal/sys)
/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/netpoll_epoll.go:11:2: package runtime/internal/syscall is not in GOROOT (/opt/hostedtoolcache/go/1.20.11/x64/src/runtime/internal/syscall)
/opt/hostedtoolcache/go/1.20.11/x64/src/go/printer/gobuild.go:10:2: package text/tabwriter is not in GOROOT (/opt/hostedtoolcache/go/1.20.11/x64/src/text/tabwriter)
make: *** [Makefile:170: codegen] Error 1
runner@fv-az889-966:~/work/rook/rook$

**Comment by parth-gr** [comment]
Testing Pr :https://github.com/rook/rook/pull/13307

**Comment by travisn** [comment]
@parth-gr Looks like you make a change in #13307 that would be resolved by `make crds`, but not clear if `make codegen` would be affected? Or what change did you make that would affect codegen?

**Comment by parth-gr** [comment]
Fixed by https://github.com/rook/rook/pull/14883
