### ISSUE TITLE
CRD stays after complete rook removal

### ISSUE THREAD

**Issue by smirnov-mi** [rook/rook#13294]
I finished the complete removal / withdrawing of the rook-ceph on my cluster, following the 
current documentation (1.12.8)
but one CDR stayed and must be removed manually 

cephcosidrivers.ceph.rook.io

please double check if it's covered by the removal process.

**Comment by thotz** [comment]
cephcosidrivers.ceph.rook.io may need to be added as well since Rook owns that CRD. Other resources need to be added to the clean-up guide of cosi.

**Comment by travisn** [comment]
The crds.yaml is already included in the main Rook cleanup guide for deletion, so we shouldn't need to mention that CRD separately.
