### ISSUE TITLE
With cluster-test.yaml we sould not create standby mds because of 1 node 

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13295]
**Is this a bug report or feature request?**
* Bug Report
With cluster-test.yaml we should not create standby mds because of 1 node, 
With filesystem-test.yaml it still create two mds but it shouldn't create 2 as of node limitations.

**Deviation from expected behavior:**
1 mds pod stays in pending state

**Expected behavior:**
only one mds should get created for test cluster

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
In minikube, I was able to start both mds instances perfectly fine after creating the [filesystem-test.yaml](https://github.com/rook/rook/blob/master/deploy/examples/filesystem-test.yaml). Do you see required anti-affinity being set on the mds deployments? I don't see any anti-affinity applied to the mds pods.

**Comment by parth-gr** [comment]
Yes it worked
