### ISSUE TITLE
Subvolume should be auto-removed if Subvolumegroup is deleted

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13297]
**Is this a bug report or feature request?**
* Bug Report

2023-11-30 14:19:24.244571 E | ceph-fs-subvolumegroup-controller: failed to reconcile "rook-ceph/group-a-a". failed to delete ceph filesystem subvolume group "group-a-a": failed to delete ceph filesystem subvolume group "group-a-a", remove the subvolumes first: exit status 39

**Deviation from expected behavior:**
OPerator leaves in error state

**Expected behavior:**
Get the subvolume and delete it
sh-4.4$  ceph fs subvolume ls myfs --group_name groupa
[
    {
        "name": "csi-vol-8ebbe91b-c128-4ac8-9aa9-00cddad1721a"
    }
]
sh-4.4$ 
sh-4.4$ 
sh-4.4$ ceph fs subvolume rm myfs csi-vol-8ebbe91b-c128-4ac8-9aa9-00cddad1721a --group_name groupa --force
sh-4.4$  ceph fs subvolumegroup getpath myfs groupa

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment]
we should not delete it we do not want to delete the data

**Comment by purban80** [comment]
I have the same problem after upgrading ceph.
Is there any way to prevent rook-ceph-operator from removing filesystem subvolume group or prevent it from losing data?

**Comment by Madhu-1** [comment]
> I have the same problem after upgrading ceph. Is there any way to prevent rook-ceph-operator from removing filesystem subvolume group or prevent it from losing data?

@purban80 Rook doesn't remove subvolumegroup if there are subvolumes in it. Are you sure Rook is deleting the SVG when you have subvolumes in it?

**Comment by purban80** [comment]
@parth-gr 
Logs from rook-ceph-operator pods:
2025-01-22 07:50:46.397934 I | ceph-spec: parsing mon endpoints: t=10.233.2.18:6789,u=10.233.63.189:6789,v=10.233.53.245:6789,n=10.233.26.91:6789,w=10.233.27.212:6789
2025-01-22 04:30:40.917850 I | ceph-fs-subvolumegroup-controller: deleting ceph filesystem subvolume group object "rook-ceph/ceph-filesystem-csi"
2025-01-22 04:30:40.917864 I | cephclient: deleting cephfs "ceph-filesystem" subvolume group "csi"
2025-01-22 04:30:41.352243 E | ceph-fs-subvolumegroup-controller: failed to reconcile "rook-ceph/ceph-filesystem-csi". failed to delete ceph filesystem subvolume group "ceph-filesystem-csi": failed to delete ceph filesystem subvolume group "ceph-filesystem-csi", remove the subvolumes first: exit status 39

kubectl get -n rook-ceph cephfilesystemsubvolumegroups.ceph.rook.io 
NAME                  PHASE     FILESYSTEM        QUOTA   AGE
ceph-filesystem-csi   Failure   ceph-filesystem           13d

From rook-ceph-tools:

bash-5.1$ ceph fs subvolumegroup ls ceph-filesystem      
[
    {
        "name": "csi"
    }
]

bash-5.1$ ceph fs subvolume ls ceph-filesystem --group_name csi  
[
    {
        "name": "csi-vol-e3e15dde-acd5-4dea-8f70-c7e7ffa8ab93"
    },
    {
        "name": "csi-vol-1adc866a-ca23-4b75-a3e0-915a2bf0ee77"
    },
.
.
    {
        "name": "csi-vol-747d547f-d18d-4f7a-a569-33f8eb60ac00"
    }
]


bash-5.1$ ceph fs subvolumegroup getpath ceph-filesystem csi       
/volumes/csi

**Comment by Madhu-1** [comment]
@purban80 please share the subvolumegroup CR yaml output, Rook will try to delete the SVG only if the CR is marked for deletion. and again it will fail if the subvolumes are present in the SVG in backend

**Comment by purban80** [comment]
kubectl get customresourcedefinitions.apiextensions.k8s.io cephfilesystemsubvolumegroups.ceph.rook.io -n rook-ceph -o yaml

[cephfilesystemsubvolumegroups.zip](https://github.com/user-attachments/files/18505786/cephfilesystemsubvolumegroups.zip)

kubectl get cephfilesystemsubvolumegroups.ceph.rook.io -n rook-ceph -o yaml

[ceph-filesystem-csi.zip](https://github.com/user-attachments/files/18505800/ceph-filesystem-csi.zip)

**Comment by purban80** [comment]
kubectl get customresourcedefinitions.apiextensions.k8s.io cephfilesystemsubvolumegroups.ceph.rook.io -n rook-ceph -o yaml

`apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: rook-ceph
    meta.helm.sh/release-namespace: rook-ceph
  creationTimestamp: "2023-06-02T09:01:55Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: rook-ceph
    helm.toolkit.fluxcd.io/namespace: rook-ceph
  name: cephfilesystemsubvolumegroups.ceph.rook.io
  resourceVersion: "917601786"
  uid: 3c1d3d67-7c9d-4fd2-b8e2-11dc9a7e2fce
spec:
  conversion:
    strategy: None
  group: ceph.rook.io
  names:
    kind: CephFilesystemSubVolumeGroup
    listKind: CephFilesystemSubVolumeGroupList
    plural: cephfilesystemsubvolumegroups
    singular: cephfilesystemsubvolumegroup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    - description: Name of the CephFileSystem
      jsonPath: .spec.filesystemName
      name: Filesystem
      type: string
    - jsonPath: .spec.quota
      name: Quota
      type: string
    - jsonPath: .status.info.pinning
      name: Pinning
      priority: 1
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: CephFilesystemSubVolumeGroup represents a Ceph Filesystem SubVolumeGroup
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec represents the specification of a Ceph Filesystem SubVolumeGroup
            properties:
              dataPoolName:
                description: The data pool name for the Ceph Filesystem subvolume
                  group layout, if the default CephFS pool is not desired.
                type: string
              filesystemName:
                description: |-
                  FilesystemName is the name of Ceph Filesystem SubVolumeGroup volume name. Typically it's the name of
                  the CephFilesystem CR. If not coming from the CephFilesystem CR, it can be retrieved from the
                  list of Ceph Filesystem volumes with `ceph fs volume ls`. To learn more about Ceph Filesystem
                  abstractions see https://docs.ceph.com/en/latest/cephfs/fs-volumes/#fs-volumes-and-subvolumes
                type: string
                x-kubernetes-validations:
                - message: filesystemName is immutable
                  rule: self == oldSelf
              name:
                description: The name of the subvolume group. If not set, the default
                  is the name of the subvolumeGroup CR.
                type: string
                x-kubernetes-validations:
                - message: name is immutable
                  rule: self == oldSelf
              pinning:
                description: |-
                  Pinning configuration of CephFilesystemSubVolumeGroup,
                  reference https://docs.ceph.com/en/latest/cephfs/fs-volumes/#pinning-subvolumes-and-subvolume-groups
                  only one out of (export, distributed, random) can be set at a time
                properties:
                  distributed:
                    maximum: 1
                    minimum: 0
                    nullable: true
                    type: integer
                  export:
                    maximum: 256
                    minimum: -1
                    nullable: true
                    type: integer
                  random:
                    maximum: 1
                    minimum: 0
                    nullable: true
                    type: number
                type: object
                x-kubernetes-validations:
                - message: only one pinning type should be set
                  rule: (has(self.export) && !has(self.distributed) && !has(self.random))
                    || (!has(self.export) && has(self.distributed) && !has(self.random))
                    || (!has(self.export) && !has(self.distributed) && has(self.random))
                    || (!has(self.export) && !has(self.distributed) && !has(self.random))
              quota:
                anyOf:
                - type: integer
                - type: string
                description: Quota size of the Ceph Filesystem subvolume group.
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
            required:
            - filesystemName
            type: object
          status:
            description: Status represents the status of a CephFilesystem SubvolumeGroup
            properties:
              info:
                additionalProperties:
                  type: string
                nullable: true
                type: object
              observedGeneration:
                description: ObservedGeneration is the latest generation observed
                  by the controller.
                format: int64
                type: integer
              phase:
                description: ConditionType represent a resource's status
                type: string
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: CephFilesystemSubVolumeGroup
    listKind: CephFilesystemSubVolumeGroupList
    plural: cephfilesystemsubvolumegroups
    singular: cephfilesystemsubvolumegroup
  conditions:
  - lastTransitionTime: "2023-06-02T09:01:55Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-06-02T09:02:00Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1`

kubectl get cephfilesystemsubvolumegroups.ceph.rook.io -n rook-ceph -o yaml
apiVersion: v1
items:
- apiVersion: ceph.rook.io/v1
  kind: CephFilesystemSubVolumeGroup
  metadata:
    annotations:
      meta.helm.sh/release-name: rook-ceph-cluster
      meta.helm.sh/release-namespace: rook-ceph
    creationTimestamp: "2025-01-08T22:54:44Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2025-01-09T00:03:58Z"
    finalizers:
    - cephfilesystemsubvolumegroup.ceph.rook.io
    generation: 3
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: rook-ceph-cluster
      helm.toolkit.fluxcd.io/namespace: rook-ceph
    name: ceph-filesystem-csi
    namespace: rook-ceph
    resourceVersion: "917847390"
    uid: 04f3e6bf-e3d5-4a17-8aa9-cbb74e72486e
  spec:
    dataPoolName: ""
    filesystemName: ceph-filesystem
    name: csi
    pinning:
      distributed: 1
  status:
    info:
      clusterID: 6ce7824f6ae653f41176f58ec8768ad6
      pinning: distributed=1
    observedGeneration: 2
    phase: Failure
kind: List
metadata:
  resourceVersion: ""

**Comment by purban80** [comment]
@parth-gr  Ok, thank you. Do you know how to recreate a subvolume group without losing data?

**Comment by Madhu-1** [comment]
> [@Madhu-1](https://github.com/Madhu-1) Ok, thank you. Do you know how to recreate a subvolume group without losing data?

We haven't tried it because you can remove the finalizers and try to create with the same name.

**Comment by purban80** [comment]
@Madhu-1 It worked. Thank you
