### ISSUE TITLE
pvc delete stuck on Terminating 

### ISSUE THREAD

**Issue by haoxiaoci** [rook/rook#13306]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
my cluster use rook as storageclass, when i delete a pod with pvc and pv, it should be delete for a while, but it stuck on pv, pvc status is Terminating
and it happens occasionally，most time pvc and pvc can be delete success.

```
root@node1:/root# kubectl get pod  | grep Termi
virt-launcher-test09-fld2w          0/1     Terminating   0          28d
root@node1:/root# kubectl get pvc   | grep test09
test09-rootdisk                                       Terminating   pvc-05d8a951-19b3-4094-ba0d-9b82878494e0   100Gi      RWX            csi-rbd-sc     28d

root@nt1:/home/haoxiaoci# kubectl describe pv pvc-05d8a951-19b3-4094-ba0d-9b82878494e0 
Name:            pvc-05d8a951-19b3-4094-ba0d-9b82878494e0
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: rook-ceph.rbd.csi.ceph.com
                 volume.kubernetes.io/provisioner-deletion-secret-name: rook-csi-rbd-provisioner
                 volume.kubernetes.io/provisioner-deletion-secret-namespace: rook-ceph
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    csi-rbd-sc
Status:          Bound
Claim:           default/test09-rootdisk
Reclaim Policy:  Delete
Access Modes:    RWX
VolumeMode:      Block
Capacity:        100Gi
Node Affinity:   <none>
Message:         
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            rook-ceph.rbd.csi.ceph.com
    FSType:            
    VolumeHandle:      0001-0009-rook-ceph-0000000000000001-00b65186-86fb-4ab9-8446-7a4fb850de07
    ReadOnly:          false
    VolumeAttributes:      clusterID=rook-ceph
                           imageFeatures=layering
                           imageFormat=2
                           imageName=csi-vol-00b65186-86fb-4ab9-8446-7a4fb850de07
                           journalPool=ceph-blockpool
                           pool=ceph-blockpool
                           storage.kubernetes.io/csiProvisionerIdentity=1686053941747-8081-rook-ceph.rbd.csi.ceph.com
Events:                <none>
```

and kubelet logs shows that this rbd device has been unmapped.
```
101540:I1201 17:06:23.303660  155055 reconciler.go:196] "operationExecutor.UnmountVolume started for volume \"rootdisk\" (UniqueName: \"kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-00b65186-86fb-4ab9-8446-7a4fb850de07\") pod \"4cd6a522-5f14-40f3-a0f9-898224d8fb09\" (UID: \"4cd6a522-5f14-40f3-a0f9-898224d8fb09\") "
101556:I1201 17:06:23.387904  155055 operation_generator.go:1314] UnmapVolume succeeded for volume "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-00b65186-86fb-4ab9-8446-7a4fb850de07" (OuterVolumeSpecName: "rootdisk") pod "4cd6a522-5f14-40f3-a0f9-898224d8fb09" (UID: "4cd6a522-5f14-40f3-a0f9-898224d8fb09"). InnerVolumeSpecName "pvc-05d8a951-19b3-4094-ba0d-9b82878494e0". PluginName "kubernetes.io/csi", VolumeGidValue ""
101558:I1201 17:06:23.407477  155055 reconciler.go:312] "operationExecutor.UnmountDevice started for volume \"pvc-05d8a951-19b3-4094-ba0d-9b82878494e0\" (UniqueName: \"kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-00b65186-86fb-4ab9-8446-7a4fb850de07\") on node \"node-test\" "
101569:I1201 17:06:23.791325  155055 operation_generator.go:1443] UnmapDevice succeeded for volume "pvc-05d8a951-19b3-4094-ba0d-9b82878494e0" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-00b65186-86fb-4ab9-8446-7a4fb850de07") on node "node-test" 
101571:I1201 17:06:23.817468  155055 reconciler.go:319] "Volume detached for volume \"pvc-05d8a951-19b3-4094-ba0d-9b82878494e0\" (UniqueName: \"kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-00b65186-86fb-4ab9-8446-7a4fb850de07\") on node \"node-test\" DevicePath \"/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-05d8a951-19b3-4094-ba0d-9b82878494e0/4cd6a522-5f14-40f3-a0f9-898224d8fb09\""

```
and in ceph cluster, you can see this rbd device is unmmaped, and this image has no watcher
```
[root@node1 /]# rbd showmapped | grep csi-vol-00b65186-86fb-4ab9-8446-7a4fb850de07
[root@node1 /]# rbd status  ceph-blockpool/csi-vol-00b65186-86fb-4ab9-8446-7a4fb850de07
Watchers: none
```
and pv status is bound:
```
root@node1:/root# kubectl get pv | grep pvc-05d8a951-19b3-4094-ba0d-9b82878494e0
pvc-05d8a951-19b3-4094-ba0d-9b82878494e0   100Gi      RWX            Delete           Bound      default/test09-rootdisk                                                                        csi-rbd-sc              28d

```

**Expected behavior:**
expected pvc can be delete immediately

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
PRETTY_NAME="Ubuntu 22.04 LTS"
* Kernel (e.g. `uname -a`):
Linux node1 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
v1.11.4
* Storage backend version (e.g. for ceph do `ceph -v`):
  cluster:
    id:     0a8b6eff-de30-4ac4-8fbf-954add316ca0
    health: HEALTH_WARN
            noout flag(s) set
 
  services:
    mon: 3 daemons, quorum a,c,d (age 2d)
    mgr: a(active, since 2d), standbys: b
    osd: 36 osds: 36 up (since 31h), 36 in (since 5M)
         flags noout
    rgw: 2 daemons active (2 hosts, 1 zones)
 
  data:
    pools:   10 pools, 2625 pgs
    objects: 5.28M objects, 17 TiB
    usage:   22 TiB used, 9.1 TiB / 31 TiB avail
    pgs:     2623 active+clean
             1    active+clean+scrubbing
             1    active+clean+scrubbing+deep
 
  io:
    client:   27 MiB/s rd, 34 MiB/s wr, 1.28k op/s rd, 3.35k op/s wr
* Kubernetes version (use `kubectl version`):
v1.22.6+rke2r1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
rke2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
What about the logs for the rbd volume plugin on the node where the pod was running, and the rbd provisioner logs? See the [CSI troubleshooting guide](https://rook.io/docs/rook/latest/Troubleshooting/ceph-csi-common-issues/).

**Comment by Rakshith-R** [comment]
> What about the logs for the rbd volume plugin on the node where the pod was running, and the rbd provisioner logs? See the [CSI troubleshooting guide](https://rook.io/docs/rook/latest/Troubleshooting/ceph-csi-common-issues/).

Closing the issue since its been inactive since some time.
Please reopen with necessary logs if the issue still persists.
