### ISSUE TITLE
templates/cephobjectstore-ingress.yaml fails to template when ceph object store ingress enabled on rook-ceph-cluster>=1.12.9

### ISSUE THREAD

**Issue by efbicief** [rook/rook#13317]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Error when templating when :
```
Error: template: rook-ceph-cluster/templates/cephobjectstore-ingress.yaml:8:24: executing "rook-ceph-cluster/templates/cephobjectstore-ingress.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
```

Seems to have been introduced in version 1.12.9, with commit [https://github.com/rook/rook/commit/b4e51f6d12bcc2bcb6a8293a522add5acbb4f367](https://github.com/rook/rook/commit/b4e51f6d12bcc2bcb6a8293a522add5acbb4f367). I am happy to try to fix this and create an MR.

**Expected behavior:**
Template completes successfully.

**How to reproduce it (minimal and precise):**
Using a values file including:
```
cephObjectStores:
  - name: ceph-objectstore
    ingress:
      enabled: true
```
Run:
`helm template helm-virtual/rook-ceph-cluster --values values-cluster.yaml`

**Logs to submit**:
With debug:
```
install.go:200: [debug] Original chart version: "1.12.9"
install.go:217: [debug] CHART PATH: /home/felixbo/.cache/helm/repository/rook-ceph-cluster-v1.12.9.tgz


Error: template: rook-ceph-cluster/templates/cephobjectstore-ingress.yaml:8:24: executing "rook-ceph-cluster/templates/cephobjectstore-ingress.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
helm.go:84: [debug] template: rook-ceph-cluster/templates/cephobjectstore-ingress.yaml:8:24: executing "rook-ceph-cluster/templates/cephobjectstore-ingress.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace

```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.6
* Kernel (e.g. `uname -a`): 5.15.0
* Kubernetes version (use `kubectl version`): 1.27.3

**Comment by travisn** [comment]
We're planning the v1.12.10 release tomorrow with this fix...

**Comment by efbicief** [comment]
Thank you!
