### ISSUE TITLE
unable to disable pg_autoscaler and manually set PGs on already created CephCluster

### ISSUE THREAD

**Issue by Kovendan03** [rook/rook#13346]
unable to disable pg_autoscaler and manually set PGs on already created CephCluster

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
unable to disable pg_autoscaler and manually set PGs on already created CephCluster.
**Expected behavior:**
pg auto scaler should be disabled.

**How to reproduce it (minimal and precise):**
Create a cephcluster with pg_autoscaler enabled, once the pgs are created, edit the cephcluster to disable autoscaler, enabled: false. restarted ceph monitor / mgr and operator pods after the change.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:
ceph osd pool autoscale-status
POOL           SIZE  TARGET SIZE  RATE  RAW CAPACITY   RATIO  TARGET RATIO  EFFECTIVE RATIO  BIAS  PG_NUM  NEW PG_NUM  AUTOSCALE  BULK
.mgr         12676k                3.0        85847G  0.0000                                  1.0       1              on         False
replicapool   4233G                3.0        85847G  0.1479                                  1.0     128              on         False

* Operator's logs, if necessary
* Cephcluster
*  mgr:
    count: 2
    modules:
    - enabled: false
      name: pg_autoscaler

ceph mgr module ls
MODULE
balancer              on (always on)
crash                 on (always on)
devicehealth          on (always on)
orchestrator          on (always on)
pg_autoscaler         on (always on)
progress              on (always on)
rbd_support           on (always on)
status                on (always on)
telemetry             on (always on)
volumes               on (always on)
dashboard             on
iostat                on
nfs                   on
prometheus            on

**Environment**:
* OS (e.g. from /etc/os-release):
* NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

* Kernel (e.g. `uname -a`):
* Linux mum-cloudlyte-sr01 5.4.0-166-generic #183-Ubuntu SMP Mon Oct 2 11:28:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):
* v1.11.10
* Storage backend version (e.g. for ceph do `ceph -v`):
* V17.2.6
* Kubernetes version (use `kubectl version`):
* v.1.24.0
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by BlaineEXE** [comment]
It seems like Ceph may have changed the autoscale module such that is always enabled and cannot be disabled. Rook has no control over this, but we should update our docs if that is true. 

PG autoscaling default behavior can be controlled globally via the ceph config `osd_pool_default_pg_autoscale_mode` as noted here: https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/?h=osd_pool_default_pg_autoscale_mode#mgr-settings

Set that in the override configmap or via the toolbox.

This can also be controlled on a per-CephBlockPool basis using `pg_autoscale_mode: "off"` as an additional `parameters` spec for each CephBlockPool. For already-reated CephBlockPools, you'll need to use this method.
Ref: https://rook.io/docs/rook/latest-release/CRDs/Block-Storage/ceph-block-pool-crd/?h=cephblockpool#spec

Update docs:
- https://rook.io/docs/rook/latest-release/Storage-Configuration/Advanced/configuration/?h=autoscale#default-pg-and-pgp-counts
