### ISSUE TITLE
Mon's never finish with moving from hostpath to pvc

### ISSUE THREAD

**Issue by ganniterix** [rook/rook#13343]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The cluster never finishes consolidating since mons keep getting reprovisioned.

**Expected behavior:**
Consolidation runs successfully.

**How to reproduce it (minimal and precise):**
Mons are configured as follows in a cluster running v1.12.8 as an operator.

```yaml
  mon:
    allowMultiplePerNode: false
    count: 3
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources:
          requests:
            storage: 20Gi
        storageClassName: csi-driver-lvm-linear
      status: {}
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:
```
2023-12-06 21:47:35.676908 I | op-mon: mon "f" path has changed from host path to persistent volumes
2023-12-06 21:47:35.677702 I | op-mon: fail over mon "f" due to change in mon path
2023-12-06 21:47:35.677964 I | op-mon: marking mon "f" out of quorum
2023-12-06 21:47:35.679212 W | cephclient: skipping adding mon "f" to config file, detected out of quorum
2023-12-06 21:47:35.688897 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2023-12-06 21:47:35.689479 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2023-12-06 21:47:35.718529 I | op-mon: prevent voluntary mon drain while failing over
2023-12-06 21:47:35.759192 I | op-mon: Failing over monitor "f"
2023-12-06 21:47:35.759466 I | op-mon: starting new mon: &{ResourceName:rook-ceph-mon-g DaemonName:g PublicIP: Port:6789 Zone: NodeName: DataPathMap:0x4001175c80 UseHostNetwork:true}
2023-12-06 21:47:35.786232 I | op-mon: scaling the mon "f" deployment to replica 0
2023-12-06 21:47:35.937940 I | op-mon: created canary monitor rook-ceph-mon-g-canary pvc rook-ceph-mon-g
2023-12-06 21:47:36.015043 I | op-mon: created canary deployment rook-ceph-mon-g-canary
2023-12-06 21:47:36.090688 I | op-mon: waiting for canary pod creation rook-ceph-mon-g-canary
```

**Environment**:
```
NAME="Fedora Linux"
VERSION="38 (Server Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Server Edition"
VARIANT_ID=server
```

* Kernel (e.g. `uname -a`):
```
Linux pi4k8sn00 6.6.3-100.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Tue Nov 28 19:41:45 UTC 2023 aarch64 GNU/Linux
```

* Cloud provider or hardware configuration: Raspberry Pi 4
* Rook version (use `rook version` inside of a Rook Pod): v1.12.8
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 18.2.0 (5dd24139a1eada541a3bc16b6941c5dde975e26d) reef (stable)`
* Kubernetes version (use `kubectl version`): `v1.27.3+k3s1`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): K3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTH_WARN 1/3 mons down, quorum i,k`

**Comment by sp98** [comment]
@ganniterix  a few questions:
- What happens after the logs `2023-12-06 21:47:36.090688 I | op-mon: waiting for canary pod creation rook-ceph-mon-g-canary`? Is the operator stuck at this point?  Can you share the complete operator logs?
- are pvs available for the mons that you are trying to move form hostpath to pv?

**Comment by ganniterix** [comment]
> @ganniterix a few questions:
> 
>     * What happens after the logs `2023-12-06 21:47:36.090688 I | op-mon: waiting for canary pod creation rook-ceph-mon-g-canary`? Is the operator stuck at this point?  Can you share the complete operator logs?
> 
>     * are pvs available for the mons that you are trying to move form hostpath to pv?

The original mon is scaled down to 0, the canary is promoted. A new pv is assigned to the new mon, and it becomes parti of the cluster. So in a scenario where we had a,b,c , a would be scaled down, and d created. As soon as d is up and running and part of the quorum, b is moved to e, c is moved to f ... and then it starts again with d. I will attach the operator log.

**Comment by ganniterix** [comment]
[operator-log.txt](https://github.com/rook/rook/files/13601843/operator-log.txt)

**Comment by ganniterix** [comment]
Is any additional information required? Because I'm going to revert to v1.12.7 so that hopefully I can resume using my cluster. Seems like this implementation was introduced as a "feature" in v1.12.8.

**Comment by sp98** [comment]
@ganniterix Didn't get a chance to look at the logs yet. I'll take a look today.

**Comment by sp98** [comment]
The PR that added this feature only worked for clusters that were not on Host Network. I forgot to test my changes when hostNetwork is enabled. Opened a new PR to fix hostNetwork clusters.
