### ISSUE TITLE
When the operator is executing mon failover, if the operator is deleted at this time, it will cause the mon to become unavailable. Moreover, if an OSD is restarted during this period, the OSD cannot join the cluster, and the pod status of the OSD will be crashbackoff.

### ISSUE THREAD

**Issue by zeaone** [rook/rook#13344]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**
<img width="1816" alt="image" src="https://github.com/rook/rook/assets/15962991/e358c6ea-08aa-4de5-9efd-709f16111fa1">
When the program enters the startDeployment method, if the action of executing kubectl delete pod rook-ceph-operator-xxx is performed at this time, then the data and mapping fields in the rook-ceph-endpoints ConfigMap resource will be saved with a number exceeding the value of spec.mon.count in the cephcluster file. This can cause the operator that is generated later to obtain an incorrect monMap configuration, leading to the failure of starting new (or restarted) OSD pods. mon error like this

![b47f1c30c5e272b367082e60122e181c](https://github.com/rook/rook/assets/15962991/463ca9d8-c150-4636-96fe-e8b0a5b29ebf)

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.7.11
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
Some questions:
1. Was this a test scenario, or did you hit this in a cluster?
2. Any other health issues besides a single mon being down?
3. Did starting the operator allow the mon failover to be completed?
4. Did starting the operator and then restarting the OSD allow the OSD to start again?
5. An extra mon in Rook's mon confligmap would result in an extra mon showing up in the ceph config when the OSD is started, but that is surprising that it would cause a crash. As long as two mons were still in quorum, those mons should be used without any issues.
6. Are you able to repro this?

**Comment by zeaone** [comment]
1.is in a Pre-Production Environment,and it also happend at 1.5.4 in a Production Environment
2. In the current situation, restarting any pod created by the operator (including OSDs and MGRs) using the kubectl delete po command will result in an error, preventing the pod from starting up properly.
3.Starting the operator does not complete the mon failover because of an incorrect configuration in the rook-ceph-endpoints ConfigMap file, which results in duplicate mon IP addresses. This causes all newly started pods (including OSDs) to use an incorrect monmap to connect to the mons. Due to Ceph's strong consistency check, this leads to an assert error.

operaotr's log 
<img width="2537" alt="image" src="https://github.com/rook/rook/assets/15962991/f1807f4d-95d4-49c3-aad2-ecaef6fad666">

The steps to reproduce the issue are as follows:

Delete the configuration folder of a specific mon (e.g., mon-c). This will cause the pod status of mon-c to become Error.
Wait for 600 seconds or manually execute ceph mon rm c. At this point, the corresponding monfailover method in the operator will be triggered.
After mon-d has been started, wait until there is a duplicate monIP in the rook-ceph-endpoints ConfigMap file.
Delete the operator at this time to reproduce the issue.


ps：Can I perform the deletion of `delete(c.mapping.Schedule, name)  delete(c.ClusterInfo.Monitors, name)`at the position marked in red in the following figure to solve this problem? Are there any risks involved?
<img width="1666" alt="image" src="https://github.com/rook/rook/assets/15962991/91343480-82e2-440b-a5a3-43966c1f1fb9">

**Comment by zeaone** [comment]
This problem still exists in rook1.7.11 and can be reproduced in the same way

**Comment by travisn** [comment]
Does this repro on v1.12 or newer? If so, we can investigate if a fix is needed. Refer to the [maintenance doc](https://rook.io/docs/rook/latest/Getting-Started/release-cycle/).

**Comment by zeaone** [comment]
At present, I do not have access to version 1.12 or any higher versions to conduct the relevant tests, however, upon reviewing the source code of v1.12, I've observed that the logic in question seemingly has not been altered.
