### ISSUE TITLE
Add Resource limits to rook component pods

### ISSUE THREAD

**Issue by jefflaplante** [rook/rook#1335]
Pods don't have resource requests/limits in place. This allows the various rook components to consume inordinate amounts of host resources - especially RAM. 

Please reference this issue that hasn't been touched since 2016: https://github.com/rook/rook/issues/293

Can we please have sane limits applied to the rook component pods as per this documentation on pod resource limits?:
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

I'd like a way of determining how to right size the various component's ram requirements based on volume usage, etc.

A simple cluster with one block device and a shared filesystem results in some MON pods consuming over 600Mi and OSD pods consuming over 300Mi.

This is on a Kubernetes 1.8 cluster.

```bash
# k top po -n rook | sort
NAME                                      CPU(cores)   MEMORY(bytes)
rook-agent-74wxs                          0m           8Mi
rook-agent-9sfrb                          0m           8Mi
rook-agent-gf9h9                          0m           8Mi
rook-api-5f95f65577-l9nl9                 0m           10Mi
rook-ceph-mds-mtc-data-5645dd87c9-v4cdt   1m           125Mi
rook-ceph-mds-mtc-data-5645dd87c9-vvbv7   0m           197Mi
rook-ceph-mgr0-cbb9df9d4-hddvb            1m           48Mi
rook-ceph-mgr1-cf647cfcd-bdqdz            0m           26Mi
rook-ceph-mon1-zq7sn                      1m           666Mi
rook-ceph-mon3-t7p8n                      1m           203Mi
rook-ceph-mon4-96f55                      3m           226Mi
rook-ceph-osd-9hcjm                       7m           320Mi
rook-ceph-osd-drtld                       5m           324Mi
rook-ceph-osd-vhzzl                       7m           325Mi
rook-operator-6d4474fd96-w7zt4            3m           31Mi

root@rook-tools:/# rookctl version
rook: v0.6.0-64.ge372634

# rookctl status
OVERALL STATUS: OK

USAGE:
TOTAL        USED        DATA       AVAILABLE
118.79 GiB   14.42 GiB   5.21 GiB   104.37 GiB

MONITORS:
NAME             ADDRESS                 IN QUORUM   STATUS
rook-ceph-mon4   10.106.229.73:6790/0    true        OK
rook-ceph-mon3   10.107.93.54:6790/0     true        OK
rook-ceph-mon1   10.109.171.149:6790/0   true        OK

MGRs:
NAME             STATUS
rook-ceph-mgr0   Active
rook-ceph-mgr1   Standby

OSDs:
TOTAL     UP        IN        FULL      NEAR FULL
3         3         3         false     false

PLACEMENT GROUPS (300 total):
STATE          COUNT
active+clean   300

# rookctl  filesystem list
NAME       METADATA POOL       DATA POOLS
mtc-data   mtc-data-metadata   mtc-data-data0
```

**Comment by jbw976** [comment]
Hi @jefflaplante, did you already try out the fairly new resource limiting features in your Rook Cluster yaml?
Docs: https://rook.io/docs/rook/master/cluster-crd.html#resource-requirementslimits
Sample: https://rook.io/docs/rook/master/cluster-crd.html#resource-requestslimits

**Comment by jefflaplante** [comment]
Hi @jbw976 - No, I didn't see this. I'm sorry I missed it. Excellent! Looks like it's already been taken care of with that. I see in the cephs docs that they recommend 1G of ram per daemon - what can be done to tune this for systems with ram constraints (digital ocean droplets don't have gobs of ram available to them for modest 2vcpu VMs.)  

Secondly - what is the preferred method for adding these resource limits to an existing cluster? What happens if I set the RAM limits too aggressively on OSD and MON pods?

**Comment by jpds** [comment]
> What happens if I set the RAM limits too aggressively on OSD and MON pods?

Your pod's status will go from `Running` to `OOMKilled`.

**Comment by kokhang** [comment]
@galexrt @jpds would the pod be evicted as a result of the resource limitation? And when that happens, wouldnt kubernetes controller deploy a new OSD or a new mon in order to satisfy the state?

**Comment by jpds** [comment]
@kokhang Yes, but it would come up and eventually hit the same resource limit ceiliing once more and repeat.

**Comment by jefflaplante** [comment]
So, the question remains - how do we 'right size' these pods based on projected usage of the Ceph cluster the pod components create? I restarted one of the host nodes on my small k8s cluster today and the memory usage of the ceph pods that were on it went down dramatically upon restart.

**Comment by jpds** [comment]
I suspect Ceph is doing a lot of caching for its day-to-day operations. In `rook-cluster.yaml` we already provide the user with the ability to specify resource limits - Helm as an example also does the same thing with not selecting defaults for their charts:

- https://github.com/kubernetes/charts/pull/1745#pullrequestreview-57125655

What would work for your 2 core droplets, isn't going to work for my bare-metal nodes with 32 cores and an average of 64GB of RAM with multiple TB disks stuck on the front.

As much as I'm a massive fan of Rook, it could also be argued that if you're so constrained for resources at a node level, you should be leveraging a cloud provider for Digital Ocean integration instead (a la https://github.com/kubernetes/kubernetes/issues/34783).

**Comment by galexrt** [comment]
I'm going to close this issue as the feature for resource limits/requests is already implemented.
The question about Ceph using "a lot of" resources should be cleared up by the Ceph doc page about hardware/resource recommendations: http://docs.ceph.com/docs/kraken/start/hardware-recommendations/
The Ceph doc page should help you find the "right size" for the nodes/Pods resources.
