### ISSUE TITLE
Support closing the metrics port of csi-cephfsplugin and csi-rbdplugin 

### ISSUE THREAD

**Issue by clcc2019** [rook/rook#13358]
Support closing the metrics port of csi-cephfsplugin and csi-rbdplugin because it exposes pprof information.

pprof is considered unsafe under certain policies

**Comment by travisn** [comment]
You are referring to metrics port 9080? @Rakshith-R @Madhu-1 thoughts?

**Comment by clcc2019** [comment]
> You are referring to metrics port 9080? @Rakshith-R @Madhu-1 thoughts?

yes,9081 and 9080

**Comment by Rakshith-R** [comment]
> Author

That should be disabled  by default

**Comment by 66545shiwo** [comment]
@clcc2019 hi,  do you solved it ? do u konw how to close these ports?
