### ISSUE TITLE
Documentation missing for required PSP mapping for rook-agent ServiceAccount

### ISSUE THREAD

**Issue by christianhuening** [rook/rook#1336]
Is this a bug report or feature request?

* Feature Request

**Feature Request**

We have a privileged PodSecurityPolicy running in our cluster and we also have the PodSecurityPolicy (PSP) Controller activated. So we had to figure out that we need to create a ClusterRoleBinding for the 'rook-agent' ServiceAccount in our setup. I think this information is lacking from the docs and would be very helpful to anyone who is trying to run rook on a cluster with active PSPs.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): 0.6.2
* Kubernetes version (use `kubectl version`): 1.8.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On-Prem

**Comment by dmick** [comment]
...and by PSP you mean Pod Security Policy.

**Comment by christianhuening** [comment]
yes, updated it in the description

**Comment by christianhuening** [comment]
I added documentation for PodSecurityPolicies and created a PR: https://github.com/rook/rook/pull/1348

**Comment by bassam** [comment]
I believe this one can be closed. Thanks @christianhuening!
