### ISSUE TITLE
Validation on `CephCluster.spec.dataDirHostPath` doesn't deal with optional.

### ISSUE THREAD

**Issue by gtsiam** [rook/rook#13367]
**Steps to reproduce:**
- Create a `CephCluster` with a non-default `dataDirHostPath`
- (?) I think I also changed some settings that caused `rook` to re-create my mon daemons.
- Update the `CephCluster` resource, removing the `dataDirHostPath`
- Watch as the operator gets very confused because `dataDirHostPath` effectively got updated from under it to the default value.

I just accidentally did this to my test cluster. I was able to recover it by setting the `dataDirHostPath` back to the original value and deleting the `rook-ceph-mon-*` deployments, but there should be some validation to prevent this. There already is some validation for changing the value, but it doesn't deal with the fact that it is optional.

**Solution:**
Either something like [this](https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/#immutablility-after-first-modification) or - better yet - make `dataDirHostPath` required with a `// +kubebuilder:default` annotation - the default value isn't documented anywhere anyway (I'd incorrectly assumed it was `/var/lib/rook`).

**Comment by travisn** [comment]
@gtsiam Rook v1.13 is coming with the CEL rules, which includes a fix for this where the [host path is immutable](https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L145):
```yaml
message="DataDirHostPath is immutable",rule="self == oldSelf"
```
This was covered in the past by the admission webhook, but it was not enabled by default due to various issues.

**Comment by gtsiam** [comment]
Oh; I'd seen that line but I'd assumed it wasn't running in this case because of the `// +optional` annotation. Didn't think to check `git blame` before reporting.

Thanks for the quick response.
