### ISSUE TITLE
OSDs usage is not distributed evenly

### ISSUE THREAD

**Issue by Kuanting888** [rook/rook#13376]
I have multiple OSDs, but the usage is not distributed evenly among them. This causes 2 OSDs to be full very quickly, while the others still have storage. 

I have tried to set the balancer mode to 'crush-compat' and manually edit the reweight, but it only has very less effect. 

Please advise if there is any action can be taken next to address this issue. Thanks

![Screenshot_2](https://github.com/rook/rook/assets/153601554/f38cd1e1-baae-4d8d-bfef-8ffbea3da08d)

![Screenshot_3](https://github.com/rook/rook/assets/153601554/9ea59f77-b02a-427d-939a-ca7d3a1d0998)

**Comment by zhucan** [comment]
uneven distribution of pg and weight will effect it. It is best to keep the capacity of the data disks the same. Let the pg distribution be balanced. https://github.com/digitalocean/pgremapper @Kuanting888
