### ISSUE TITLE
Allow to change the ServiceAccount with which the rook mon,osd,mgr pods are created

### ISSUE THREAD

**Issue by christianhuening** [rook/rook#1337]
Is this a bug report or feature request?

* Feature Request

**Feature Request**

Are there any similar features already existing:
no
What should the feature do:
Allow users to specify a ServiceAccount other than "default" to run the rook mon, mgr etc. Pods in the desired namespace.

What would be solved through this feature:
It would allow to explicitly bind RBAC rules and PSP Roles to that serviceAccount without having to use the default serviceAccount, which is potentially problematic.

Does this have an impact on existing features:
I don't think so.

**Comment by bassam** [comment]
As it stands the rook operator creates the service accounts dynamically for each rook namespace/cluster it creates. To better support PSP, I wonder if the rook operator should do the role binding to PSP dynamically.

In this approach the PSP Roles would have to be specified on the rook Cluster yaml.

**Comment by christianhuening** [comment]
Hm, yes I think configuring the PSP role would also be sufficient and maybe even better.

Is there any argument against being able to override the default ServiceAccount names?

**Comment by bassam** [comment]
we can go either way. as I think more about this, I think the cluster-admin should have full control of the RBAC and PSP policy that Rook uses including service account names etc. Rook should not be opinionated like it currently is. I'm going to write up a separate issue on this.

**Comment by jbw976** [comment]
Thanks for bringing this up @christianhuening, I believe this issue is now covered by #1389 and its associated design write-up: https://github.com/rook/rook/blob/master/design/security-model.md.  That issue is in the 0.8 milestone.
