### ISSUE TITLE
csi image should allow any version of image

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13387]
**Is this a bug report or feature request?**
* Bug Report
The `ROOK_CSI_CEPH_IMAGE: ` should allow specifying any kind of image it should have any supported restrictions,
This validation doesnt allow us to apply any image we build 
https://github.com/Rakshith-R/rook/blob/a3220d827de070ce2b122b8a24b36687c26f74c8/pkg/operator/ceph/csi/version.go#L33

**Deviation from expected behavior:**

```
2023-12-12 16:52:20.361407 E | ceph-csi: failed to reconcile failed to configure ceph csi: invalid csi version: failed to extract ceph CSI version: failed to parse version from: "[quay.io/nixpanic/cephcsi:pr_4316](http://quay.io/nixpanic/cephcsi:pr_4316)"
```

**Expected behavior:**
Environment variable `ROOK_CSI_CEPH_IMAGE: ` should work seamlessly

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by Rakshith-R** [comment]
@parth-gr Set this option to true 
https://github.com/rook/rook/blob/ca810f5c2c88c5dae3115422af26bdce6330759a/deploy/examples/operator.yaml#L100-L101

**Comment by parth-gr** [comment]
@Rakshith-R wont you feel like this option `ROOK_CSI_ALLOW_UNSUPPORTED_VERSION` should be auto on if we are using `ROOK_CSI_CEPH_IMAGE: `

**Comment by travisn** [comment]
> @Rakshith-R wont you feel like this option `ROOK_CSI_ALLOW_UNSUPPORTED_VERSION` should be auto on if we are using `ROOK_CSI_CEPH_IMAGE: `

You can set it to true if you're using an unsupported image. This setting is trying to make it very clear when unsupported images are used.
