### ISSUE TITLE
Example object store YAML not working on 1.8

### ISSUE THREAD

**Issue by jpds** [rook/rook#1340]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened: The example object store config at: https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-object.yaml#L2 states:

```
# For earlier versions than K8s 1.7, the kind must be Objectstore
kind: ObjectStore
```

But when I try and run this on my 1.8.2 cluster, I get:

```
error: unable to recognize "rook-object.yaml": no matches for rook.io/, Kind=ObjectStore
```

Changing `ObjectStore` to `Objectstore` makes it succeed (and later causes #1339, I believe).

**Environment**:
* OS (e.g. from /etc/os-release): Debian 9
* Kernel (e.g. `uname -a`): 4.13
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): v0.5.0-288.g0ceddcf
* Kubernetes version (use `kubectl version`): 1.8.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubespray
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK

**Comment by jpds** [comment]
This works fine on my new test 1.8.5-based Kubernetes with 0.6.2 rook.

**Comment by travisn** [comment]
The only time I would expect that error is if the operator has not been started. If you see this again can you check if the operator is running. Otherwise, want to close this?

**Comment by jpds** [comment]
The operator was running at the time, but I'll close this for now as the new cluster is fine.
