### ISSUE TITLE
TestHelmUpgradeSuite (v1.28.4) is failing on master

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13406]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
the repro I did found is the upgrade cmd is not picking the latest crds 
```
2023-12-14 13:26:39.425802 E | testutil: Errors Encountered while executing helm command . walk.go:74: found symbolic link in path: /home/runner/work/rook/rook/deploy/charts/rook-ceph-cluster/charts/library resolves to /home/runner/work/rook/rook/deploy/charts/library
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(CephFilesystemSubVolumeGroup.spec): unknown field "name" in io.rook.ceph.v1.CephFilesystemSubVolumeGroup.spec, ValidationError(CephFilesystemSubVolumeGroup.spec): unknown field "pinning" in io.rook.ceph.v1.CephFilesystemSubVolumeGroup.spec]: exit status 1

```

**Expected behavior:**
 TestHelmUpgradeSuite should run successfully

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by subhamkrai** [comment]
@travisn I don't see this issue anymore, have you noticed this CI failing recently?

**Comment by subhamkrai** [comment]
> @travisn I don't see this issue anymore, have you noticed this CI failing recently?

I see it is failing in 1.23.17 but not in 1.29.0 pr.
