### ISSUE TITLE
Encryption for Host Storage Clusters

### ISSUE THREAD

**Issue by mosesdd** [rook/rook#13410]
**Is this a bug report or feature request?**
* Feature Request

According to the [documentation](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/key-management-system/) encryption of OSDs is only possbile for PVC Storage Clusters. Is it possible to get encryption for Host Storages Cluster OSDs too?

**What should the feature do:**

Encrypt OSDs in Host Storage Cluster

**Comment by satoru-takeuchi** [comment]
You can enable OSD encryption in host-based cluster by `encryptedOSD` field. At the present, only full disks (the type of `lsblk` is `disk`) is supported. The document you pointed is for encrption using KMS. The encryption in host-based cluster doesn't use KMS.

**Comment by mosesdd** [comment]
@satoru-takeuchi thanks, is there any documentation about that?

**Comment by satoru-takeuchi** [comment]
> thanks, is there any documentation about that? Did you mean encryptedDevice because I couldn't find anything about encryptedOSD? Since when is this feature available?

Oops, sorry. I meant `encryptedDevice` described here.

https://rook.io/docs/rook/v1.12/CRDs/Cluster/ceph-cluster-crd/#osd-configuration-settings
> encryptedDevice**: Encrypt OSD volumes using dmcrypt ("true" or "false"). By default this option is disabled. See encryption for more information on encryption in Ceph.
