### ISSUE TITLE
ObjectBucket CRD contains suspect definition for authentication

### ISSUE THREAD

**Issue by Pythoner6** [rook/rook#13414]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The ObjectBucket CRD contains a field `authentication` which has both `type: object` as well as an `items` field (which I believe is meant for arrays). https://github.com/rook/rook/blob/8e704fdfd32eedccacba876d1d6373d4f7486b62/deploy/charts/rook-ceph/templates/resources.yaml#L13059 This can cause at least some tooling to throw errors - [timoni](https://github.com/stefanprodan/timoni) being the one I've run into in particular (see https://github.com/stefanprodan/timoni/issues/277). It seems some other jsonschema implementations simply ignore the items constraint in this case rather than erroring out (obviously k8s accepts the crd) though I'm not well versed enough in jsonschema/openapi/crds to know if this is really supposed to be a supported configuration.

Looking at the definition of where I believe this field is coming from https://github.com/kube-object-storage/lib-bucket-provisioner/blob/d1a8c34382f127670e363ae925ae6087e8b2c7bf/pkg/apis/objectbucket.io/v1alpha1/objectbucket_types.go#L97 I'm also not sure this field is even supposed to be showing up in the crd in the first place given it's marked as `json:"-"` and it's missing from the crd yaml in that repo as well https://github.com/kube-object-storage/lib-bucket-provisioner/blob/master/deploy/crds/objectbucket_v1alpha1_objectbucket_crd.yaml

**Comment by travisn** [comment]
Development effort is being put more into COSI instead of the OBCs, but contributions are still welcome if you would like to work on it.
