### ISSUE TITLE
can we increase the pvc dynamically

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#13437]
Hi team,
we have installed rook-ceph in kubernetes cluste and we are using cephfs as storage and our application is creating the pv and pvc respect to the rook-ceph

we have 3 pv's and each having 100 G and my totoal ceph disk is 500G.
can i increase dynamically one pv to 150G  ?

1. For issues or feature requests, please create an issue in this repository.
2. For general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://slack.rook.io/).
3. Did you already search the existing open issues for anything similar? -->

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
@vadlakiran Yes the volume can be resized, see [this topic](https://rook.io/docs/rook/latest/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/#dynamically-expand-volume) for details.

**Comment by vadlakiran** [comment]
@Team, can we get any inputs on this.

if we increase the volume using edit command, will it be effect rook-ceph pods or cluster ?

**Comment by subhamkrai** [comment]
@vadlakiran It should not affect the cluster, if you have the spare extra volume.

**Comment by Madhu-1** [comment]
dynamic resizing of the cephfs PVC should not cause any issue as it's thin provisioned. Closing this one as not an issue.
