### ISSUE TITLE
ci: add openshift origin provider

### ISSUE THREAD

**Issue by leseb** [rook/rook#1343]
**Feature Request**

Are there any similar features already existing: no

What should the feature do: test Rook on OpenShift

What would be solved through this feature: running/testing Rook on OpenShift

Does this have an impact on existing features: no

**Comment by galexrt** [comment]
@leseb There is already issue to do that, see https://github.com/rook/rook/issues/1315

**Comment by leseb** [comment]
@galexrt sorry about that, closing this in favour of #1315
