### ISSUE TITLE
reduce size of pvc

### ISSUE THREAD

**Issue by parswebserver** [rook/rook#13467]
* Feature Request

**What should the feature do:**
It is possible to increase the disk (PVC), but it is not possible to decrease it
Can you add this possibility?
that we can reduce the size of the disk (PVC)?

**Environment**:
Kubernetes v1.26.1
rook-ceph v1.13.1

**Comment by microyahoo** [comment]
> In Kubernetes v1.11 the persistent volume expansion feature is being promoted to beta. This feature allows users to easily resize an existing volume by editing the PersistentVolumeClaim (PVC) object. Users no longer have to manually interact with the storage backend or delete and recreate PV and PVC objects to increase the size of a volume. Shrinking persistent volumes is not supported
As document mentioned, shrinking persistent volumes is not supported.
https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

**Comment by parswebserver** [comment]
our Kubernetes is v1.26.1
Still not supported?

**Comment by microyahoo** [comment]
> our Kubernetes is v1.26.1 Still not supported?

hi @parswebserver, as code snippet show that it doesn't support. https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L2376-L2387

**Comment by lbogdan** [comment]
It will probably never be supported, given the complexity of shrinking a filesystem, e.g. `resize2fs` doesn't support online shrinking of an `ext4` filesystem.

What this is usually done is: create a new PVC of the lower size, copy over the data from the old PVC, and then delete it.

Out of curiosity, what is your use-case?

**Comment by parswebserver** [comment]
> It will most probably never be supported, given the complexity of shrinking a filesystem, e.g. `resize2fs` doesn't support online shrinking of an `ext4` filesystem.
> 
> What this is usually done is: create a new PVC of the lower size, copy over the data from the old PVC, and then delete it.
> 
> Out of curiosity, what is your use-case?

thank you for reply
How should we copy the data to the new pvc?
You mean there is a POD
Connect both PVC to it
And with RSYNC to move the data?

**Comment by microyahoo** [comment]
> > It will most probably never be supported, given the complexity of shrinking a filesystem, e.g. `resize2fs` doesn't support online shrinking of an `ext4` filesystem.
> > What this is usually done is: create a new PVC of the lower size, copy over the data from the old PVC, and then delete it.
> > Out of curiosity, what is your use-case?
> 
> thank you for reply How should we copy the data to the new pvc? You mean there is a POD Connect both PVC to it And with RSYNC to move the data?

you can mount the rbd/cephfs volume to local,  then copy it.

**Comment by BlaineEXE** [comment]
Rook does not implement volume resize functionality, but https://github.com/ceph/ceph-csi does. You may wish to move this feature request there.

**Comment by BlaineEXE** [comment]
Closing this to be clear that Rook cannot resolve this issue.
