### ISSUE TITLE
Give right mds permission to CephFS Provisioner user

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#13462]
**Is this a bug report or feature request?**
* Bug Report

For nodeFencing, the permission give to CephFS provisioned cephClient for mds is `*`. We should not be giving full permission to users unless required. FROM https://github.com/rook/rook/pull/13348#discussion_r1430285538

**Deviation from expected behavior:**

MDS has `*` permission in CephFS provisioned cephClient

**Expected behavior:**
Use precise permission to CephFS provisioned cephClient for MDS

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by riya-singhal31** [comment]
As per the discussion with Greg,
'that's an admin socket command, those generally require "*" ' though he's not sure on this, so checking more.
