### ISSUE TITLE
clock skew detected on mon.c

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#13465]
Hi team,

we have installed the rook-ceph on kubernetes cluster and all the worker nodes and master are in time sync with ntp server.
all servers are the same time, but still its giving clock skew with 0.01101 sec , not sure how we can resolve this.

is there any solution for this to avoid this ?

[rook@rook-ceph-tools-76598c54f4-fr26c /]$ ceph -s
  cluster:
    id:     704fb784-0d99-4655-8f69-5950b186390c
    health: HEALTH_WARN
            clock skew detected on mon.c

  services:
    mon: 3 daemons, quorum a,c,d (age 26m)
    mgr: a(active, since 27m)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 27m), 3 in (since 27m)

  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 3.08k objects, 59 MiB
    usage:   309 MiB used, 150 GiB / 150 GiB avail
    pgs:     65 active+clean

  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by zhucan** [comment]
@vadlakiran you need to deploy a ntp server to keep the time at same.

**Comment by zhucan** [comment]
like this: https://github.com/fabianlee/docker-chrony-alpine/blob/main/k8s-chrony-alpine.yaml
