### ISSUE TITLE
Service: csi-rbdplugin-metrics not be created

### ISSUE THREAD

**Issue by shilintan** [rook/rook#13476]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** Service: csi-rbdplugin-metrics not be created when CSI_ENABLE_LIVENESS: "false"

**Expected behavior:** Service: csi-rbdplugin-metrics be created when CSI_ENABLE_LIVENESS: "false"

**How to reproduce it (minimal and precise):** set CSI_ENABLE_LIVENESS: "false"

**File(s) to submit**: none

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**: none

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.13.1
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by zhucan** [comment]
@shilintan https://github.com/rook/rook/pull/13166 take look at this pr?

**Comment by Madhu-1** [comment]
>Expected behavior: Service: csi-rbdplugin-metrics be created when CSI_ENABLE_LIVENESS: "false"


This will get created when you set `CSI_ENABLE_LIVENESS` to `true`, please re-open the issue if its not the case
