### ISSUE TITLE
Integration for RGW host style bucket domains

### ISSUE THREAD

**Issue by jpds** [rook/rook#1349]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: No

What should the feature do: AWS has a concept of a "host style bucket" domains, where clients can be configured to go to:

```
host_bucket = %(bucket)s.s3.amazonaws.com
```

- https://github.com/aws/aws-sdk-go/blob/master/service/s3/host_style_bucket.go

Rook could potential implement this with the help of a wildcard DNS entry which goes to a nginx/other ingress:

https://www.hastexo.com/resources/hints-and-kinks/configuring-radosgw-behave-amazon-s3/

It would seem that the RGW just needs to have a way of setting:

`rgw dns name = domain.name`

What would be solved through this feature: Some S3 clients expect this integration.

Does this have an impact on existing features: N/A.

**Comment by jpds** [comment]
Seems Kubernetes does not support wildcard ingress definitions (kubernetes/kubernetes#41881). For now, I'd be happy to have separate ingress definitions which point to the same RGW instance (which using wildcard DNS).

**Comment by jpds** [comment]
I came across this while trying to find a fix for the issue I have in https://github.com/hashicorp/vault/issues/3728 .

**Comment by jpds** [comment]
Potentially already implemented: https://github.com/rook/rook/blob/master/pkg/daemon/ceph/rgw/daemon.go#L89

Prehaps `Host` needs to be added to the YAML/documentation?

**Comment by travisn** [comment]
agreed, it seems we need to expose the dns name to the object.yaml.

**Comment by travisn** [comment]
Right now the `rgw dns name` is set to the name of the rgw service. The side effect of this is that the hostname in the URL of s3 client requests must match that name. For now, setting the default to be blank is the right thing until it's more clear how to use the bucket names with the wildcard. 

@jpds do you have any more insight into how we can configure k8s to get this to work?

**Comment by travisn** [comment]
@jpds please reactivate if #1437 was not sufficient
