### ISSUE TITLE
Filesystem mounts limited to a namespace

### ISSUE THREAD

**Issue by abh** [rook/rook#1350]
**Feature Request**

What should the feature do:

It seems like a filesystem can be mounted by any pod in any namespace. It'd be nice if it was possible to limit a filesystem to only be mounted by pods in a certain namespace.

What would be solved through this feature:

Seperation of applications.

**Comment by dimm0** [comment]
Would be nice to have this feature

**Comment by dimm0** [comment]
Now being solved in https://github.com/rook/rook/issues/2164

**Comment by galexrt** [comment]
I think this is kind of covered by #2216, what do you think @dimm0 @abh?

**Comment by dimm0** [comment]
yes, I think it is

**Comment by travisn** [comment]
yes, fixed by #2216
