### ISSUE TITLE
cephfs snapshot mirror import is success，but daemon status peers is empty

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13502]
![image](https://github.com/rook/rook/assets/31508490/8a2802c4-f430-4315-9548-0a60598caac0)
![image](https://github.com/rook/rook/assets/31508490/7cb9e13b-daf7-48e1-999b-62b514a691d9)

**Is this a bug report or feature request?**

* Bug Report
* Feature Request

**Bug Report**

**Expected behavior:**

**Deviation from expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the GitHub UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Feature Request**

**Are there any similar features already existing:**

**What should the feature do:**

**What would be solved through this feature:**

**Does this have an impact on existing features:**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):1.13.1
* Storage backend version (e.g. for ceph do `ceph -v`):18.2.1
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
What does the [kubectl rook-ceph dr health](https://github.com/rook/kubectl-rook-ceph/tree/master?tab=readme-ov-file#commands) command show?

**Comment by 13567436138** [comment]
root@karmada-02-a:~# kubectl rook ceph dr health
Info: fetching the cephblockpools with mirroring enabled
Warning: DR is not confiqured, cephblockpool with mirroring enabled not found.


i am using cephfs mirror not rbd mirror

**Comment by 13567436138** [comment]
@travisn
