### ISSUE TITLE
I use storageclass created a pv，get pv -o yaml i see subVolumeName,but when I use command to the the subvolume it showes does not exist

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13508]
sh-4.4$ ceph fs subvolume info myfs csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6
Error ENOENT: subvolume 'csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6' does not exist

![image](https://github.com/kubernetes/kubernetes/assets/31508490/8e001610-f3b6-4617-9929-61d69866782c)

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by zhucan** [comment]
@13567436138 need to specify the subvolumegroup

1. ceph fs volume ls
output is:
```
[
    {
        "name": "cephfs"
    }
]
```
2. ceph fs subvolumegroup ls cephfs
```
output is:
[
    {
        "name": "cephfs-subvg-306a6da8-9dfa-4fb6-93f9-c4c658a2c74e"
    },
    {
        "name": "csi"
    }
]
```
3. ceph fs subvolume info cephfs csi-vol-93f24819-de90-11ed-aecd-36d0027d6d31  csi
output is:
```
{
    "atime": "2023-04-19 09:00:05",
    "bytes_pcent": "0.00",
    "bytes_quota": 53687091200,
    "bytes_used": 0,
    "created_at": "2023-04-19 09:00:05",
    "ctime": "2023-04-19 09:00:15",
    "data_pool": "cephfs-replicated-pool",
    "features": [
        "snapshot-clone",
        "snapshot-autoprotect",
        "snapshot-retention"
    ],
    "gid": 0,
    "mode": 16895,
    "mon_addrs": [
        "10.x.x.37:6789",
        "10.x.x.32:6789",
        "10.x.x.35:6789"
    ],
    "mtime": "2023-04-19 09:00:05",
    "path": "/volumes/csi/csi-vol-93f24819-de90-11ed-aecd-36d0027d6d31/6934d939-1d44-452a-aa04-e8f14f28969b",
    "pool_namespace": "",
    "state": "complete",
    "type": "subvolume",
    "uid": 0
}
```

**Comment by zhucan** [comment]
it's not bug, if you have any question that you can open the discussion under https://github.com/rook/rook/discussions

**Comment by 13567436138** [comment]
```
sh-4.4$ ceph fs subvolume info myfs csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6 csi
{
    "atime": "2024-01-05 04:11:58",
    "bytes_pcent": "0.00",
    "bytes_quota": 1073741824,
    "bytes_used": 19,
    "created_at": "2024-01-05 04:11:58",
    "ctime": "2024-01-05 04:15:18",
    "data_pool": "myfs-replicated",
    "features": [
        "snapshot-clone",
        "snapshot-autoprotect",
        "snapshot-retention"
    ],
    "gid": 0,
    "mode": 16877,
    "mon_addrs": [
        "192.168.229.182:6789",
        "192.168.229.184:6789",
        "192.168.229.186:6789"
    ],
    "mtime": "2024-01-05 04:15:18",
    "path": "/volumes/csi/csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6/7134d939-60d8-498e-aa3e-1d48efee4d89",
    "pool_namespace": "",
    "state": "complete",
    "type": "subvolume",
    "uid": 0
}
```

cluster1 is ok,but cluster2 is not ok.I have configrured mirror from cluster1 to cluster2.

sh-4.4$ ceph fs subvolume info myfs csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6 csi
Error ENOENT: subvolume 'csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6' does not exist

**Comment by 13567436138** [comment]
sh-4.4$ ceph fs subvolume ls myfs csi
[]

the subvolume is not created

**Comment by 13567436138** [comment]
sh-4.4$ ceph fs snapshot mirror daemon status
[{"daemon_id": 54598, "filesystems": [{"filesystem_id": 1, "name": "myfs", "directory_count": 0, "peers": [{"uuid": "afc319ba-b4b3-4c94-b3de-1ca344b1ce6a", "remote": {"client_name": "client.mirror", "cluster_name": "b684e736-882f-4591-9384-083acb7ec2f7", "fs_name": "myfs"}, "stats": {"failure_count": 0, "recovery_count": 0}}]}]}]

does this show sync success?

**Comment by zhucan** [comment]
> ```
> sh-4.4$ ceph fs subvolume info myfs csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6 csi
> {
>     "atime": "2024-01-05 04:11:58",
>     "bytes_pcent": "0.00",
>     "bytes_quota": 1073741824,
>     "bytes_used": 19,
>     "created_at": "2024-01-05 04:11:58",
>     "ctime": "2024-01-05 04:15:18",
>     "data_pool": "myfs-replicated",
>     "features": [
>         "snapshot-clone",
>         "snapshot-autoprotect",
>         "snapshot-retention"
>     ],
>     "gid": 0,
>     "mode": 16877,
>     "mon_addrs": [
>         "192.168.229.182:6789",
>         "192.168.229.184:6789",
>         "192.168.229.186:6789"
>     ],
>     "mtime": "2024-01-05 04:15:18",
>     "path": "/volumes/csi/csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6/7134d939-60d8-498e-aa3e-1d48efee4d89",
>     "pool_namespace": "",
>     "state": "complete",
>     "type": "subvolume",
>     "uid": 0
> }
> ```
> 
> cluster1 is ok,but cluster2 is not ok.I have configrured mirror from cluster1 to cluster2.
> 
> sh-4.4$ ceph fs subvolume info myfs csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6 csi Error ENOENT: subvolume 'csi-vol-c46f14eb-e18d-41cb-9e97-5ec5d89d2fa6' does not exist

check the subvolumegroup whether it's exists firstly, then check the subvolume whether it's exists.
