### ISSUE TITLE
Rook recreates ceph-osd-prepare pod for nodes that don't exist anymore

### ISSUE THREAD

**Issue by telmich** [rook/rook#13519]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

* rook should not try to prepare a node that does not exist anymore
* there should be no pods dangling trying to prepare nodes that don't exist

**Expected behavior:**

* a) rook detects that a certain node has been deleted and does not try to prepare osds on it
* b) (if the race condition theory below is true) Add to the documentation that there might be a need for manually cleaning prepare jobs on node removal

**How to reproduce it (minimal and precise):**

Unclear, I had a cluster before where the prepare pod would re-appear and I do have another cluster right now where the same symptom happens again.

Generally speaking the steps should be:

* Create a rook cluster with several nodes
* Delete a node
* Observe that the a pod is being recreated to try to prepare the node

I am not a 100% if this is a race condition or not, I try to add as much information as possible below, but here is a sketch on what could have happened:

* There used to be server64 in the cluster that has been removed "a long time ago"
* There still is a job (rook-ceph-osd-prepare-server64) around that is not finished
* There is a newly created pod trying to prepare server64
* The log of the the rook-operator never mentions server64, probably because it does not see it, as it does not exist
* So potentially the prepare job was created by another rook-operator, long time ago, when server64 was still around, but the prepare job never executed

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary

The operator logs do not contain the server name:

**Cluster Status to submit**:

Can be OK or WARN, in both ways it still exists.

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): alpine-linux 3.18
* Kernel (e.g. `uname -a`): Linux server101 6.6.9-0-lts #1-Alpine SMP PREEMPT_DYNAMIC Tue, 02 Jan 2024 09:10:44 +0000 x86_64 GNU/Linux
* Cloud provider or hardware configuration: hardware
* Rook version (use `rook version` inside of a Rook Pod): v1.13.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 18.2.1 (7fe91d5d5842e04be3b4f514d6dd990c54b29c76) reef (stable)
* Kubernetes version (use `kubectl version`): 1.28.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_WARN mon ad is low on available space; Degraded data redundancy: 744413/15099036 objects degraded (4.930%), 21 pgs degraded, 21 pgs undersized; 1 daemons have recently crashed

* Additional logs/output

It seems a lot of old jobs are kept for many nodes that don't exist anymore:

```
% kubectl -n rook-ceph get job | grep osd-prepare
rook-ceph-osd-prepare-server101            1/1           53s        18h
rook-ceph-osd-prepare-server116            1/1           33s        18h
rook-ceph-osd-prepare-server117            1/1           24s        18h
rook-ceph-osd-prepare-server118            1/1           21s        18h
rook-ceph-osd-prepare-server119            1/1           26s        18h
rook-ceph-osd-prepare-server22             1/1           24s        219d
rook-ceph-osd-prepare-server23             1/1           24s        219d
rook-ceph-osd-prepare-server24             1/1           22s        219d
rook-ceph-osd-prepare-server25             1/1           22s        219d
rook-ceph-osd-prepare-server26             1/1           23s        390d
rook-ceph-osd-prepare-server27             1/1           26s        390d
rook-ceph-osd-prepare-server63             1/1           23s        601d
rook-ceph-osd-prepare-server64             0/1           39d        39d
rook-ceph-osd-prepare-server66             1/1           23s        207d
rook-ceph-osd-prepare-server84             1/1           22s        282d
rook-ceph-osd-prepare-server86             1/1           21s        424d
rook-ceph-osd-prepare-server96             1/1           3m26s      18h
rook-ceph-osd-prepare-server97             1/1           31s        18h
rook-ceph-osd-prepare-server98             1/1           30s        26h
rook-ceph-osd-prepare-server99             1/1           3m25s      18h
```

vs. the nodes:

```
% kubectl get nodes
NAME        STATUS                        ROLES           AGE    VERSION
server101   Ready                         <none>          601d   v1.29.0
server116   Ready                         <none>          518d   v1.28.2
server117   Ready                         <none>          518d   v1.28.2
server118   Ready                         <none>          55d    v1.29.0
server119   Ready                         <none>          82d    v1.28.2
server131   Ready                         control-plane   281d   v1.29.0
server132   Ready                         control-plane   281d   v1.29.0
server133   Ready                         control-plane   281d   v1.29.0
server96    Ready                         <none>          311d   v1.29.0
server97    Ready                         <none>          601d   v1.29.0
server98    NotReady,SchedulingDisabled   <none>          261d   v1.28.3
server99    Ready                         <none>          353d   v1.29.0
```

When I look at the pods, only the one for server64 is still there pending:

```
% kubectl -n rook-ceph get pods| grep prepare
rook-ceph-osd-prepare-server101-jj5gh                 0/1     Completed               0                 18h
rook-ceph-osd-prepare-server116-ccw5v                 0/1     Completed               0                 18h
rook-ceph-osd-prepare-server117-89dvm                 0/1     Completed               0                 18h
rook-ceph-osd-prepare-server118-wpbml                 0/1     Completed               0                 18h
rook-ceph-osd-prepare-server119-lk8sd                 0/1     Completed               0                 18h
rook-ceph-osd-prepare-server64-cwtbz                  0/1     Pending                 0                 18d
rook-ceph-osd-prepare-server96-5k2wd                  0/1     Completed               0                 18h
rook-ceph-osd-prepare-server97-mkn25                  0/1     Completed               0                 18h
rook-ceph-osd-prepare-server99-8s6j6                  0/1     Completed               0                 18h
```

So today I deleted the job and with it the pod

```
% kubectl -n rook-ceph delete jobs rook-ceph-osd-prepare-server64
job.batch "rook-ceph-osd-prepare-server64" deleted
[10:29] nb3:~% kubectl -n rook-ceph get pods | grep server64
[10:29] nb3:~% 
```

The logs of the rook-operator:

```
[10:32] nb3:~% kubectl -n rook-ceph logs rook-ceph-operator-65648888d4-wf4q7 | grep server64 
[10:32] nb3:~% 
```

**Comment by travisn** [comment]
Rook does not automatically delete the osd prepare jobs, with the intention that their logs can be used for troubleshooting if needed. 

There is no observed side effect for these prepare jobs still existing other than perhaps it's just not as clean as expected, correct?
