### ISSUE TITLE
debug 2024-01-05T03:24:22.982+0000 7f1c95fb4700 -1 cephfs::mirror::Mirror handle_enable_mirroring: failed to initialize FSMirror for filesystem={fscid=1, fs_name=myfs}: (110) Connection timed out

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13510]
mirror pod has error：
```
debug 2024-01-05T03:24:22.982+0000 7f1c95fb4700 -1 cephfs::mirror::Mirror handle_enable_mirroring: failed to initialize FSMirror for filesystem={fscid=1, fs_name=myfs}: (110) Connection timed out
```
```
debug 2024-01-05T07:47:11.224+0000 7f8e0c7fd700 -1 cephfs::mirror::PeerReplayer(afc319ba-b4b3-4c94-b3de-1ca344b1ce6a) do_sync_snaps: failed to build remote snap map
debug 2024-01-05T07:47:11.224+0000 7f8e0c7fd700 -1 cephfs::mirror::PeerReplayer(afc319ba-b4b3-4c94-b3de-1ca344b1ce6a) sync_snaps: failed to sync snapshots for dir_root=/
debug 2024-01-05T07:48:11.560+0000 7f8e0c7fd700 -1 cephfs::mirror::PeerReplayer(afc319ba-b4b3-4c94-b3de-1ca344b1ce6a) build_snap_map: snap_path=//.snap/scheduled-2024-01-04-09_00_00_UTC has invalid metadata in remote snapshot
debug 2024-01-05T07:48:11.564+0000 7f8e0c7fd700 -1 cephfs::mirror::PeerReplayer(afc319ba-b4b3-4c94-b3de-1ca344b1ce6a) do_sync_snaps: failed to build remote snap map
debug 2024-01-05T07:48:11.564+0000 7f8e0c7fd700 -1 cephfs::mirror::PeerReplayer(afc319ba-b4b3-4c94-b3de-1ca344b1ce6a) sync_snaps: failed to sync snapshots for dir_root=/
```
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by 13567436138** [comment]
how to find this snap_path=//.snap/scheduled-2024-01-04-09_00_00_UTC
and delete it

**Comment by 13567436138** [comment]
I find the snap，but
debug 2024-01-05T03:24:22.982+0000 7f1c95fb4700 -1 cephfs::mirror::Mirror handle_enable_mirroring: failed to initialize FSMirror for filesystem={fscid=1, fs_name=myfs}: (110) Connection timed out
where did it connect to

**Comment by BlaineEXE** [comment]
You'll have to provide more information about how you have configured your cluster and the cluster you want to mirror to in order for anyone to be able to help. Those logs don't give enough information. Please include the docs you followed, the cluster setups you are using, and the manifests used.
