### ISSUE TITLE
can not create rgw pod

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13522]
```
 Warning  ReconcileFailed  10m   rook-ceph-object-controller  failed to reconcile CephObjectStore "rook-ceph/my-store-c2". failed to create object store deployments: failed to configure multisite for object store: failed create ceph multisite for object-store ["my-store-c2"]: failed to commit config changes after creating multisite config for CephObjectStore "rook-ceph/my-store-c2": failed to commit RGW configuration period changes%!(EXTRA []string=[]): exit status 22
```
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):1.13.1
* Storage backend version (e.g. for ceph do `ceph -v`):18.2.1
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by zhucan** [comment]
do you know more multisites? and you need to use multisites?

**Comment by 13567436138** [comment]
but I don't know how to fix
