### ISSUE TITLE
objectstore sync between two clusters commit got error

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13520]
**Is this a bug report or feature request?**
* Bug Report
```
bash-4.4$ radosgw-admin period update  --rgw-realm=my-store --commit
2024-01-08T04:13:59.133+0000 7fc91a44ca80  0 period (d7b40c19-8797-4c57-91e2-bc2231fa4ce1 does not have zone 9933bb3a-9706-4305-a652-626e7fbcba65 configured
2024-01-08T04:13:59.321+0000 7fc91a44ca80 -1 Cannot find zone id=9933bb3a-9706-4305-a652-626e7fbcba65 (name=my-store)
2024-01-08T04:13:59.321+0000 7fc91a44ca80  0 ERROR: failed to start notify service ((22) Invalid argument
2024-01-08T04:13:59.321+0000 7fc91a44ca80  0 ERROR: failed to init services (ret=(22) Invalid argument)
couldn't init storage provider
```
**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):1.13.1
* Storage backend version (e.g. for ceph do `ceph -v`):18.2.1
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by zhucan** [comment]
`Cannot find zone id=9933bb3a-9706-4305-a652-626e7fbcba65 (name=my-store)`  please check the zone  whether it's not exists?

**Comment by zhucan** [comment]
I don't think it's bug, but it's wrong way to use.

**Comment by 13567436138** [comment]
how to fix，If I deleted the zone，create new zone with the same name，not solve my problem

**Comment by BlaineEXE** [comment]
I'm not sure deleting the zone and recreating it -- without also deleting the CephObjectStore -- is supported. That may put Ceph into a bad internal state or have race conditions that could do that, but I'm not sure. That's definitely outside the bounds of intended and normal usage patterns.
