### ISSUE TITLE
Published "rook-ceph-cluster" helm chart is out-of-sync?

### ISSUE THREAD

**Issue by xor22h** [rook/rook#13526]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

```bash
helm pull --repo https://charts.rook.io/release rook-ceph-cluster
helm show values rook-ceph-cluster-v1.13.1.tgz | grep ceph/ceph
    image: quay.io/ceph/ceph:v17.2.6
```

**Expected behavior:**

Image should be v18.2.1

Helm values v1.13.1: https://github.com/rook/rook/blob/v1.13.1/deploy/charts/rook-ceph-cluster/values.yaml#L98C1-L99C1
Images.txt in v1.13.1 tag: https://github.com/rook/rook/blob/v1.13.1/deploy/examples/images.txt

But git Branch release-1.13: https://github.com/rook/rook/blob/release-1.13/deploy/charts/rook-ceph-cluster/values.yaml#L98C37-L98C37

**Comment by travisn** [comment]
@xor22h v1.13.1 will be included by default with the Rook v1.13.2 release planned later this week, along with other changes that have merged to the release-1.13 branch since the v1.13.1 release.
