### ISSUE TITLE
Operator panic in mds handling after #12860 / #13030

### ISSUE THREAD

**Issue by toelke** [rook/rook#13542]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behaviour:**

On rook versions after 1.12.5, I get the following log from the operator:

```
2024-01-09 16:34:01.153083 I | op-config: successfully set "mds.fs-replicated2-a"="mds_join_fs"="fs-replicated2" option to the mon configuration database
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14af1c4]

goroutine 742 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:115 +0x1a4
panic({0x1b54080?, 0x375eb60?})
        /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x218
github.com/rook/rook/pkg/operator/ceph/config.GetProbeWithDefaults(...)
        /home/runner/work/rook/rook/pkg/operator/ceph/config/probes.go:75
github.com/rook/rook/pkg/operator/ceph/config.ConfigureStartupProbe({{0x1e8626d, 0x3}, {0x4000055f50, 0x17}, {0x40037cc620, 0x1, 0x1}, {0x4004722300, 0xf, 0x10}, ...}, ...)
        /home/runner/work/rook/rook/pkg/operator/ceph/config/probes.go:57 +0xb4
github.com/rook/rook/pkg/operator/ceph/file/mds.(*Cluster).makeDeployment(0x4000801650, 0x4000800ec0, {{0x4001a40170?, 0x4001e3de10?}, {0x4001a40160?, 0x9?}})
        /home/runner/work/rook/rook/pkg/operator/ceph/file/mds/spec.go:48 +0x94
github.com/rook/rook/pkg/operator/ceph/file/mds.(*Cluster).startDeployment(0x4000801650, {0x24edf08, 0x400012e050}, {0x36bc3e8, 0x1})
        /home/runner/work/rook/rook/pkg/operator/ceph/file/mds/mds.go:184 +0x260
github.com/rook/rook/pkg/operator/ceph/file/mds.(*Cluster).Start(0x4000801650)
        /home/runner/work/rook/rook/pkg/operator/ceph/file/mds/mds.go:134 +0x2b4
github.com/rook/rook/pkg/operator/ceph/file.createFilesystem(_, _, {{{0x190417c, 0xe}, {0x4001a72040, 0xf}}, {{0x4001a40160, 0xe}, {0x0, 0x0}, ...}, ...}, ...)
        /home/runner/work/rook/rook/pkg/operator/ceph/file/filesystem.go:54 +0x130
github.com/rook/rook/pkg/operator/ceph/file.(*ReconcileCephFilesystem).reconcileCreateFilesystem(0x4000166960, 0x4000508e00)
        /home/runner/work/rook/rook/pkg/operator/ceph/file/controller.go:427 +0x180
github.com/rook/rook/pkg/operator/ceph/file.(*ReconcileCephFilesystem).reconcile(_, {{{_, _}, {_, _}}})
        /home/runner/work/rook/rook/pkg/operator/ceph/file/controller.go:335 +0x960
github.com/rook/rook/pkg/operator/ceph/file.(*ReconcileCephFilesystem).Reconcile(0x4000166960, {0x0?, 0x4000db7d08?}, {{{0x4001a40170?, 0x30?}, {0x4001a40160?, 0x7f66c1fe01?}}})
        /home/runner/work/rook/rook/pkg/operator/ceph/file/controller.go:162 +0x80
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x24eded0?, {0x24eded0?, 0x4000814690?}, {{{0x4001a40170?, 0x1a060c0?}, {0x4001a40160?, 0x4000aafdd8?}}})
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:118 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x4000166a00, {0x24edf08, 0x4000773680}, {0x1c44800?, 0x4000f394a0?})
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:314 +0x29c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x4000166a00, {0x24edf08, 0x4000773680})
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:265 +0x198
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:226 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 152
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:222 +0x43c
```

Thereafter, it exists and gets restarted, only to crash again.

Judging from the line-numbers, this is related to #12860 / #13030.

**How to reproduce it (minimal and precise):**

I guess there is something configured weirdly in my cluster. Is there anything I can do to further debug and help fix this?

<details>
<summary>helm values</summary>
<code>
cephCommandsTimeoutSeconds: "180"
csi:
  csiRBDProvisionerResource: |
    - name : csi-provisioner
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-resizer
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-attacher
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-snapshotter
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 200m
    - name : csi-rbdplugin
      resource:
        requests:
          memory: 512Mi
          cpu: 50m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : csi-omap-generator
      resource:
        requests:
          memory: 512Mi
          cpu: 50m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : liveness-prometheus
      resource:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
  csiRBDPluginResource: |
    - name : driver-registrar
      resource:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
    - name : csi-rbdplugin
      resource:
        requests:
          memory: 256Mi
          cpu: 125m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : liveness-prometheus
      resource:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
  csiCephFSPluginResource: |
    - name : driver-registrar
      resource:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
    - name : csi-cephfsplugin
      resource:
        requests:
          memory: 256Mi
          cpu: 125m
        limits:
          memory: 1Gi
          cpu: 500m
    - name : liveness-prometheus
      resource:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
</code>
</details>

**Environment**:
* OS (e.g. from /etc/os-release): Debian 11, Ubuntu 20.04
* Kernel (e.g. `uname -a`): multiple, 5.4-6.1
* Cloud provider or hardware configuration: Mixed
* Kubernetes version (use `kubectl version`): 1.25.4

**Comment by travisn** [comment]
This code path should only be hit if the `startupProbe` is specified for the filesystem. It's not set by default, and neither do I see it in your values that you shared. What does `kubectl -n rook-ceph get cephfilesystem -o yaml` show for the full manifest of the filesystem?

**Comment by toelke** [comment]
Indeed, there is

```yaml
    metadataServer:
        startupProbe:
            probe:
              timeoutSeconds: 15
```

in the file system. After removing that, rook v1.13.1 runs without error. Is there another way to specify this?

**Comment by BlaineEXE** [comment]
It seems like there must be some kind of code bug we are hitting when trying to specify different values. That's obviously not great, but here should be no need to change the `timeoutSeconds` value unless you are having problems with the probe itself. Why have you decided to specify this? Was there some issue you were trying to resolve?

**Comment by toelke** [comment]
> Why have you decided to specify this? Was there some issue you were trying to resolve?

My cluster consists of a mix of machines, some rather small (Raspberry Pi 4 2 GB) connected over a WAN mesh. Timeouts are the greatest enemy of that setup. :-D

I can, however, confirm that since I updated to 1.13.1 with the offending configuration removed, the MDS has not been restarted. So I guess the config really was not needed any more.

> [Update] I'll also note that if you added that config to work around an issue from before Rook v1.12.<something>

Yes, the config was added when we were running Rook v1.8

> In the meantime, I think/hope the failure output you provided has enough information for us to try to figure out how to repro the issue in a unit regression test, and then we can fix the issue.

I will monitor this issue and supply additional information if needed.

**Comment by toelke** [comment]
My cluster is running cleanly for a while now, so this is done. Thanks for the help!
