### ISSUE TITLE
Enable running unit tests against a custom Ceph image

### ISSUE THREAD

**Issue by travisn** [rook/rook#13545]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
If Ceph changes are being proposed, we need to enable a custom image with the change to be run against the Rook integration tests. For example, this is helpful for to test changes to ceph-volume or ceph-container. @guits 

Most of the Ceph changes impacting Rook are covered by the Canary integration tests, which run the cluster-test.yaml. 

#13544 is an example PR that was opened just to test a custom image. Ideally we would be able to trigger the canary tests from the Github UI, with the image name as input to the job. If this isn't realistic, then we can close this feature request and just open a PR similar to #13544 whenever we need to test such a change.
@subhamkrai thoughts?

**What is use case behind this feature:**
Simplifying testing of Ceph changes will ensure reliability and finding issues sooner than after the change is merged and the daily Rook CI starts failing against main or other release branches.

**Comment by subhamkrai** [comment]
@travisn can input from Github UI and trigger the canary tests in GitHub action. For more details https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by travisn** [comment]
Great, so we can hopefully use that to trigger the canary tests with a specific image. And if it's not triggered manually this setting would be blank in which case we just use the default tag that is already in cluster-test.yaml.
