### ISSUE TITLE
`rook-ceph-mgr` serviceMonitor fails after upgrade to `v1.13.2`

### ISSUE THREAD

**Issue by jimmy-ungerman** [rook/rook#13566]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After upgrading to `v1.13.2` the metrics endpoint for the rook-ceph-mgr is throwing connection refused errors.

```
➜ k port-forward svc/rook-ceph-mgr 9283  
Forwarding from 127.0.0.1:9283 -> 9283
Forwarding from [::1]:9283 -> 9283
Handling connection for 9283
E0112 08:18:58.935363   11354 portforward.go:409] an error occurred forwarding 9283 -> 9283: error forwarding port 9283 to pod 42d0b03906b646a74d7458201ca021cd262fa9cd943eac8327c71bd66346251f, uid : failed to execute portforward in network namespace "/var/run/netns/cni-414ad2ca-8861-2ac6-7c8b-b347e1d1e9de": failed to connect to localhost:9283 inside namespace "42d0b03906b646a74d7458201ca021cd262fa9cd943eac8327c71bd66346251f", IPv4: dial tcp4 127.0.0.1:9283: connect: connection refused IPv6 dial tcp6 [::1]:9283: connect: connection refused 
error: lost connection to pod
```

![Screenshot 2024-01-12 at 8 16 54 AM](https://github.com/rook/rook/assets/14128371/442e9eaf-574a-43eb-9084-41409e76b31d)

**Expected behavior:**
The metrics endpoint should be available for the serviceMonitor.

**How to reproduce it (minimal and precise):**

Upgrade to chart `v1.13.2` and attempt to hit the metrics endpoint on the `rook-ceph-mgr` service.

`kubectl port-forward svc/rook-ceph-mgr 9283:9283`

```
curl -L http://localhost:9283/metrics
curl: (52) Empty reply from server
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

Nothing at all is showing up in any logs when the request is refused.

**Cluster Status to submit**:

* Output of kubectl commands, if necessary
```
jimmy in ~ at macbook-pro
➜ kubectl -n rook-ceph exec -it deploy/rook-ceph-tools -- ceph health
HEALTH_OK
```

```
jimmy in ~ at macbook-pro
➜ kubectl -n rook-ceph exec -it deploy/rook-ceph-tools -- ceph status
  cluster:
    id:     69890505-c5b3-4412-b861-d01964924fa7
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,d (age 9h)
    mgr: a(active, since 8h), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 9h), 3 in (since 8w)
    rgw: 2 daemons active (2 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   12 pools, 169 pgs
    objects: 50.29k objects, 103 GiB
    usage:   312 GiB used, 11 TiB / 11 TiB avail
    pgs:     169 active+clean

  io:
    client:   8.8 KiB/s rd, 75 KiB/s wr, 9 op/s rd, 9 op/s wr
```

**Environment**:
* OS (e.g. from /etc/os-release): Talos v1.5.4
* Kernel (e.g. `uname -a`): 6.1.67
* Cloud provider or hardware configuration: N/A
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.28.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by mbleichner** [comment]
I had the same problem. Can you check the log of the mgr process?

In my case, the prometheus module would crash on startup because of some problem with the orchestrator. After disabling the orchestrator module (`ceph mgr module disable rook`, `ceph orch set backend ""`) and restarting, I got it to work again.

Here's the relevant part of the log, in case it helps to narrow down the issue:

```
debug 2024-01-12T11:58:27.196+0100 7f34cca4d700  1 mgr load Constructed class from module: pg_autoscaler
debug 2024-01-12T11:58:27.196+0100 7f34cca4d700  0 [progress DEBUG root] setting log level based on debug_mgr: INFO (2/5)
debug 2024-01-12T11:58:27.196+0100 7f34cca4d700  1 mgr load Constructed class from module: progress
debug 2024-01-12T11:58:27.204+0100 7f34cca4d700  0 [prometheus DEBUG root] setting log level based on debug_mgr: INFO (2/5)
debug 2024-01-12T11:58:27.204+0100 7f34cca4d700 -1 no module 'rook'
debug 2024-01-12T11:58:27.204+0100 7f34cca4d700 -1 no module 'rook'
debug 2024-01-12T11:58:27.204+0100 7f34cca4d700 -1 mgr load Failed to construct class in 'prometheus'
debug 2024-01-12T11:58:27.204+0100 7f34cca4d700 -1 mgr load Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1657, in _oremote
    return mgr.remote(o, meth, *args, **kwargs)
  File "/usr/share/ceph/mgr/mgr_module.py", line 2228, in remote
    args, kwargs)
ImportError: Module not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/prometheus/module.py", line 649, in __init__
    self.modify_instance_id = self.get_orch_status() and self.get_module_option(
  File "/usr/share/ceph/mgr/prometheus/module.py", line 869, in get_orch_status
    return self.available()[0]
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1586, in inner
    completion = self._oremote(method_name, args, kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1661, in _oremote
    f_set = self.get_feature_set()
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1586, in inner
    completion = self._oremote(method_name, args, kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 1657, in _oremote
    return mgr.remote(o, meth, *args, **kwargs)
  File "/usr/share/ceph/mgr/mgr_module.py", line 2228, in remote
    args, kwargs)
ImportError: Module not found

debug 2024-01-12T11:58:27.208+0100 7f34cca4d700 -1 mgr operator() Failed to run module in active mode ('prometheus')
```

**Comment by mbleichner** [comment]
Possibly related: https://github.com/rook/rook/issues/13527

**Comment by jimmy-ungerman** [comment]
I get the same module loading error as you do, I'm curious if there is any issue with disabling the rook module?

**Comment by jimmy-ungerman** [comment]
@mbleichner the image that @rkachach created discussed in [#13527](https://github.com/rook/rook/issues/13527) works.

Adding
```
cephClusterSpec:
  cephVersion:
    image: docker.io/rkachach/ceph:v18.2.1_patched_v1
```
To my ceph-cluster values.yaml and recycling the deployments successfully loads the prometheus module and gives metrics

**Comment by rkachach** [comment]
Duplicate: https://github.com/rook/rook/issues/13527
