### ISSUE TITLE
PVC is pending with StorageClass "rook-block" not found

### ISSUE THREAD

**Issue by Ichbinjoe** [rook/rook#1356]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
Rook complains that the `rook-block` storageclass does not exist.

What you expected to happen:
Rook creates the persistent volume claim for use.

How to reproduce it (minimal and precise):
Deploy rook (cluster/examples/kubernetes/rook-operator.yaml)
Create rook namespace
Deploy a rook clulster: https://gist.github.com/Ichbinjoe/a6b72a4d3e93e7ef8b76f4077bb29298
Deploy replicapool: https://gist.github.com/Ichbinjoe/97aa8d4083c23c53138e62288151b7ae
Deploy rook-block: https://gist.github.com/Ichbinjoe/2a6fdbcba98d64cccac060620118f3d3
Deploy a PVC: https://gist.github.com/Ichbinjoe/08dd8cd290a3900eb67dfe41ea36ecc6

Pvc hangs in `pending`, and rook-operator reports the following error:
```
E1226 22:49:50.699935       7 controller.go:584] Error getting claim "default/wp-pv-claim"'s StorageClass's fields: StorageClass "rook-block" not found
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.4.0
VERSION_ID=1576.4.0
BUILD_ID=2017-12-06-0449
PRETTY_NAME="Container Linux by CoreOS 1576.4.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
* Kernel (e.g. `uname -a`):
`Linux ***** 4.13.16-coreos-r2 #1 SMP Wed Dec 6 04:27:34 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz GenuineIntel GNU/Linux`
* Cloud provider or hardware configuration: 5 Kubernetes boxes on a LAN
* Rook version (use `rook version` inside of a Rook Pod):  rook: v0.6.1
* Kubernetes version (use `kubectl version`):
[rook-logs.gz](https://github.com/rook/rook/files/1588001/rook-logs.gz)
 ```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bootkube/matchbox/coreos
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
```
root@rook-tools:/# ceph health
HEALTH_OK
```

**Comment by kokhang** [comment]
i havent seen this issue before. Is your storageclass created? Can you do `kubectl get storageclass`?

**Comment by saravanakumar-periyasamy** [comment]
I do get the same error... and I do have the `storageclass ` created

```
kubectl get sc
NAME                   PROVISIONER     AGE
rook-block (default)   rook.io/block   1h
```

**Comment by galexrt** [comment]
@Ichbinjoe @saravanakumar-periyasamy Please try upgrading to the latest Rook version.

If you should be on `v0.6.1` please first upgrade to `v0.7.x` and then when you are on `v0.7.x`, to `v0.8.1`.

For info to upgrade, please refer to the Rook.io documentation, e.g. for v0.8.x update https://rook.io/docs/rook/v0.8/upgrade.html.
