### ISSUE TITLE
Multus and csi hostnetwork canary tests are hanging in master

### ISSUE THREAD

**Issue by travisn** [rook/rook#13578]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The multus-cluster-network and csi-hostnetwork-disabled tests are timing out in master. It seems #13420 was merged too soon, as the same tests were timing out in that PR first, but they were mistakely overlooked as an intermittent issue. As seen [here](https://github.com/rook/rook/actions/runs/7500363116/job/20418900837), they are timing out when running the cephfs tests:
```
tests/scripts/github-action-helper.sh test_csi_cephfs_workload
```
It seems the test cannot connect back to the app pod after the cephfs plugin restart:
```
++ kubectl -n rook-ceph get pod --selector=app=csi-cephfsplugin --field-selector=status.phase=Running -o name
+ kubectl -n rook-ceph delete pod/csi-cephfsplugin-j6rcv
pod "csi-cephfsplugin-j6rcv" deleted
+ kubectl exec -t pod/csicephfs-demo-pod -- dd if=/dev/random of=/var/lib/www/html/test1 oflag=direct bs=1M count=1
Error: The operation was canceled.
```

@iPraveenParihar please take a look

**Expected behavior:**
Passing canary tests in master.

**How to reproduce it (minimal and precise):**

See the [canary tests in master](https://github.com/rook/rook/actions/workflows/canary-integration-test.yml?query=branch%3Amaster) since #13420 merged.

**Comment by iPraveenParihar** [comment]
Will take a look at it.

**Comment by Madhu-1** [comment]
might be related to https://github.com/rook/rook/issues/13580

**Comment by travisn** [comment]
@iPraveenParihar Any clues yet on the failure? We need to fix these tests soon to avoid introducing other regressions to these tests.

**Comment by iPraveenParihar** [comment]
> @iPraveenParihar Any clues yet on the failure? We need to fix these tests soon to avoid introducing other regressions to these tests.

Found out that `cephFS.netNamespaceFilePath` in clusterID `rook-ceph` was not updated.
```
[
  {
    "clusterID": "rook-ceph",
    "monitors": [
      "10.111.236.158:6789"
    ],
    "cephFS": {
      "netNamespaceFilePath": "",
      "subvolumeGroup": "",
      "kernelMountOptions": "",
      "fuseMountOptions": ""
    },
    "rbd": {
      "netNamespaceFilePath": "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/rook-ceph.net.ns",
      "radosNamespace": ""
    },
    "nfs": {
      "netNamespaceFilePath": "/var/lib/kubelet/plugins/rook-ceph.nfs.csi.ceph.com/rook-ceph.net.ns"
    },
    "readAffinity": {
      "enabled": false,
      "crushLocationLabels": [
        "kubernetes.io/hostname",
        "topology.kubernetes.io/region",
        "topology.kubernetes.io/zone",
        "topology.rook.io/chassis",
        "topology.rook.io/rack",
        "topology.rook.io/row",
        "topology.rook.io/pdu",
        "topology.rook.io/pod",
        "topology.rook.io/room",
        "topology.rook.io/datacenter"
      ]
    },
    "namespace": "rook-ceph"
  },
  {
    "clusterID": "e1026845ad66577abae1d16671b464c8",
    "monitors": [
      "10.111.236.158:6789"
    ],
    "cephFS": {
      "netNamespaceFilePath": "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/my-cluster.net.ns",
      "subvolumeGroup": "csi",
      "kernelMountOptions": "",
      "fuseMountOptions": ""
    },
    "rbd": {
      "netNamespaceFilePath": "",
      "radosNamespace": ""
    },
    "nfs": {
      "netNamespaceFilePath": ""
    },
    "readAffinity": {
      "enabled": false,
      "crushLocationLabels": null
    },
    "namespace": "rook-ceph"
  }
]
```

Manually updated the `cephFS.netNamespaceFilePath`  and the test passed.
Will figure it out what missed in the code and raise a fix PR.
