### ISSUE TITLE
deviceFilter and osd prepare : /dev/dm-* are not filtered and are scanned in details

### ISSUE THREAD

**Issue by benth42** [rook/rook#13582]
Hello,

I'm contacting you about the deviceFilter functions for osd prepare.

Whatever I try, the osd prepare pod, scan in details /dev/dm-* devices. 
And for a running kubernetes clusters with a lots of stuff, it's a major inconvenient (time and risks) 

I try many many things : 
- global deviceFilters in combination  with useAllNodes set to true
- by node deviceFilters (of course useAllNodes to false)
- devicePathFilters  without success

For my last try (and logs associate) I have tested to add a partition on the device and use deviceFilter: "^sdb1"
Lots of skip is done, but /dev/dm-* are'nt.

Here some logs : 

```
 inventory: device "sde4" skipped due to filter "^sdb1"
 inventory: device "sde6" skipped due to filter "^sdb1"
inventory: device "sde9" skipped due to filter "^sdb1"
 inventory: device "sdf" skipped due to filter "^sdb1"
 inventory: device "sdf1" skipped due to filter "^sdb1"
```
and so on

but when it comes to dm, detailed scan is done
```
`exec: Running command: lsblk /dev/dm-0 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME,MOUNTPOINT,FSTYPE`
```
and so on thourgh all dm devices (well now I'm at dm-161 ... )

edit : not sure at all about the code .

Any idea to not scan /dev/dm devices ?  

Edit : and, a question, I try to manually specify device, host by host, device by device, and osd prepare still scan ? 
If devices are specified, is there a way to disable auto scan ? 

Thank you in advance. 

Regards,

**Comment by benth42** [comment]
Hello,

Ok thank you. 
Don't hesitate to ask if you need some details.

By the way, I think if detailled configuration of osd disks is provided (node and devices), no auto scan is necessary  and will be a good things.

Regards,

**Comment by satoru-takeuchi** [comment]
I succeeded to reproduce the behavior that you encountered.

> Any idea to not scan /dev/dm devices ?

I'll try to find a workaround or a fix.

**Comment by satoru-takeuchi** [comment]
@benth42 

You can avoid the detailed device scans by using [PVC-based cluster](https://github.com/rook/rook/blob/master/Documentation/CRDs/Cluster/pvc-cluster.md). In this configuration, you specify your devices for osds as PVCs. If you'd like to use `/dev/sdb1` on `node`, it's necessary to create a local PVC which points to this device.

In [host-based cluster](https://github.com/rook/rook/blob/master/Documentation/CRDs/Cluster/host-cluster.md), it's your current configuration, it's difficult to scan devices. These scans are mainly to find the alias of device names. For instance, here is a example of my local environment.

```
$ sudo lsblk /dev/dm-0 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,
NAME,KNAME,MOUNTPOINT,FSTYPE
SIZE="10733223936" ROTA="1" RO="0" TYPE="lvm" PKNAME="" NAME="/dev/mapper/testvg-testlv" KNAME="/dev/dm-0" MOUNTPOINT="" FSTYPE=""
```

This device is recognized as `/dev/dm-0` in kernel. In addition, this device has another name, `/dev/mapper/testvg-testlv` by `udev`. To match all devices listed in CephCluster CR and the existing all device name aliases, it's not avoidable to run many scans.
