### ISSUE TITLE
missing metrics

### ISSUE THREAD

**Issue by uhthomas** [rook/rook#13589]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Prior versions of rook and ceph reported lots of metrics, but now a lot are missing. I applied fixes from #12876 and #13527, but it's still roughly the same.

![image](https://github.com/rook/rook/assets/9749173/c32aa9d3-024a-461e-80fa-9181d526edff)

![image](https://github.com/rook/rook/assets/9749173/4492f56d-101b-45ba-814c-041909d90c8a)

**Expected behavior:**

All metrics should be present.

It should probably look like this:

![image](https://github.com/rook/rook/assets/9749173/4b20fa6e-fe09-444b-9cfd-8dcc2a8affc9)

**How to reproduce it (minimal and precise):**

Install rook v1.13.2 and Ceph v1.18.1, observe missing metrics.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): Talos Linux 1.6.1
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.13.2
* Storage backend version (e.g. for ceph do `ceph -v`): v1.18.1
* Kubernetes version (use `kubectl version`): v1.29.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): Healthy

**Comment by uhthomas** [comment]
Okay, I found the missing metrics. They come from the `mgr`, not `ceph-exporter`. The documentation doesn't really make this very clear, and even suggests that `ceph-exporter` is a full replacement?

https://github.com/rook/rook/blob/f46c0845eea74675fcfcd42f4a1b7244bb7349a6/design/ceph/ceph-exporter.md?

I will leave this open to understand what can be changed to make this more clear.

**Comment by rkachach** [comment]
@uhthomas I understand that there's no error with the metrics and it's just a doc issue, right?

**Comment by satoru-takeuchi** [comment]
@uhthomas 

> Install rook v1.13.2 and Ceph v1.18.1, observe missing metrics.

I hit a similar problem with rook v1.13.1 and Ceph v18.2.1.

I assumed that your Ceph version is correctly v18.2.1. Does it correct?

**Comment by travisn** [comment]
If it's v18.2.1, see #13527 for the details and a workaround.

**Comment by satoru-takeuchi** [comment]
> If it's v18.2.1, check if it's the same issue as https://github.com/rook/rook/issues/13527.

My problem seems to be different from #13527 (attached `mgr-log.txt`). I use a debian-based self-built container and would hit the following debian-specific problems.

- [ceph-exporter is not included in the deb packages](https://tracker.ceph.com/issues/64095)
- [debian packaging is missing bcrypt dependency for ceph-mgr's .requires file](https://tracker.ceph.com/issues/63637)

[mgr-log.txt](https://github.com/rook/rook/files/14017221/mgr-log.txt)

**Comment by rkachach** [comment]
@satoru-takeuchi yep, that's a different issue. Not sure if this can be fixed in Ceph project side for Debian builds.

**Comment by rkachach** [comment]
> Okay, I found the missing metrics. They come from the `mgr`, not `ceph-exporter`. The documentation doesn't really make this very clear, and even suggests that `ceph-exporter` is a full replacement?
> 
> https://github.com/rook/rook/blob/f46c0845eea74675fcfcd42f4a1b7244bb7349a6/design/ceph/ceph-exporter.md?
> 
> I will leave this open to understand what can be changed to make this more clear.

@uhthomas I reviewed the docs on https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-monitoring/#prometheus-instances and I think it's stated clearly that there're two sources of metrics c`eph-exporter` and the `mgr prometheus module`. 

From my  point of view monitoring docs are clear but if there is any section that needs improvements please let me know so I can change it.
