### ISSUE TITLE
Deploy Service and ServiceMonitor to connect to external ceph-exporter

### ISSUE THREAD

**Issue by avanthakkar** [rook/rook#13611]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Rook should deploy Service and ServiceMonitor in CephCluster namespace to connect to externl ceph-exporter in case of external mode deployment. Also metrics endpoint exposed by external exporters should be validated similar to what's done for mgr prometheus exporter.

**What is use case behind this feature:**
Supporting scraping of metrics from external Ceph exporters

**Environment**:

**Comment by travisn** [comment]
A complication is that the exporter is running on each node in the external cluster. An endpoint is needed on each node. Can the servicemonitor connect to multiple endpoints. And what will be the process to update it when the node list? We need to ensure it is not brittle.

**Comment by richardelling** [comment]
consider if you need a ServiceMonitor or just a PodMonitor, which can be easier
reference: https://prometheus-operator.dev/docs/operator/design/#podmonitor

**Comment by parth-gr** [comment]
> A complication is that the exporter is running on each node in the external cluster. An endpoint is needed on each node. Can the servicemonitor connect to multiple endpoints? And what will be the process to update it when the node list? We need to ensure it is not brittle.

I think we need endpoint slice for it https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#endpointslice-resource

**Comment by travisn** [comment]
As discussed separately, we need a design review for the approach. Scraping metrics from a list of nodes not even inside K8s doesn't seem correct.
