### ISSUE TITLE
Adding another OSD to an lvm metadata device fails

### ISSUE THREAD

**Issue by barrettMCW** [rook/rook#13634]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSD preparation job fails, metadataDevice is not found.
**Expected behavior:**
Shrink old db lvms and create new ones for new osds.
**How to reproduce it (minimal and precise):**

Use a metadataDevice for a couple osds then try adding another.
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
....
  storage:
    config:
      metadataDevice: /dev/nvme3n1
    flappingRestartIntervalHours: 0
    store: {}
    useAllDevices: true
    useAllNodes: true
  waitTimeoutForHealthyOSDInMinutes: 10

**Logs to submit**:

* Crashing pod(s) logs  (prepare osds)
2024-01-26 18:18:20.592522 D | sys: lsblk output: "SIZE=\"3840755982336\" ROTA=\"0\" RO=\"0\" TYPE=\"disk\" PKNAME=\"\" NAME=\"/dev/nvme3n1\" KNAME=\"/dev/nvme3n1\" MOUNTPOINT=\"\" FSTYPE=\"LVM2_member\""
2024-01-26T18:18:20.592567853Z 2024-01-26 18:18:20.592536 D | exec: Running command: sgdisk --print /dev/nvme3n1
2024-01-26T18:18:20.594129868Z 2024-01-26 18:18:20.594111 D | exec: Running command: udevadm info --query=property /dev/nvme3n1
2024-01-26 18:18:20.596822 D | sys: udevadm info output: "DEVLINKS=/dev/disk/by-id/lvm-pv-uuid-IdXk2O-et0v-xPzX-N3Ek-OTf5-OGch-68J1EW /dev/disk/by-path/pci-0000:84:00.0-nvme-1 /dev/disk/by-id/nvme-Micron_7450_MTFDKCC3T8TFR_22293A1C4543 /dev/disk/by-id/nvme-eui.000000000000000100a075223a1c4543 /dev/disk/by-id/nvme-Micron_7450_MTFDKCC3T8TFR_22293A1C4543_1\nDEVNAME=/dev/nvme3n1\nDEVPATH=/devices/pci0000:80/0000:80:03.3/0000:84:00.0/nvme/nvme3/nvme3n1\nDEVTYPE=disk\nDISKSEQ=9\nDM_MULTIPATH_DEVICE_PATH=0\nID_FS_TYPE=LVM2_member\nID_FS_USAGE=raid\nID_FS_UUID=IdXk2O-et0v-xPzX-N3Ek-OTf5-OGch-68J1EW\nID_FS_UUID_ENC=IdXk2O-et0v-xPzX-N3Ek-OTf5-OGch-68J1EW\nID_FS_VERSION=LVM2 001\nID_MODEL=Micron_7450_MTFDKCC3T8TFR\nID_NSID=1\nID_PATH=pci-0000:84:00.0-nvme-1\nID_PATH_TAG=pci-0000_84_00_0-nvme-1\nID_REVISION=E2MU200\nID_SERIAL=Micron_7450_MTFDKCC3T8TFR_22293A1C4543_1\nID_SERIAL_SHORT=22293A1C4543\nID_WWN=eui.000000000000000100a075223a1c4543\nMAJOR=259\nMINOR=0\nMPATH_SBIN_PATH=/sbin\nSUBSYSTEM=block\nSYSTEMD_ALIAS=/dev/block/259:0\nSYSTEMD_READY=1\nSYSTEMD_WANTS=lvm2-pvscan@259:0.service\nTAGS=:systemd:\nUSEC_INITIALIZED=3928562"
2024-01-26 18:18:20.596834 D | exec: Running command: lsblk --noheadings --path --list --output NAME /dev/nvme3n1
2024-01-26 18:18:20.597992 I | inventory: skipping device "nvme3n1" because it has child, considering the child instead.
...
2024-01-26 18:18:21.792330 I | cephosd: binary "/usr/sbin/lvm" found on the host, proceeding with osd preparation
2024-01-26 18:18:21.793933 I | cephosd: Successfully updated lvm config file "/etc/lvm/lvm.conf"
2024-01-26 18:18:21.794179 I | cephosd: configuring new LVM device sdf
2024-01-26T18:18:21.798654468Z 2024-01-26 18:18:21.798527 C | rookcmd: failed to configure devices: failed to initialize osd: metadata device /dev/nvme3n1 is not found

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

I have done both metadataDevice: nvme3n1 and /dev/nvme3n1
lsblk shows the device on all nodes

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04.3 LTS
* Kernel (e.g. `uname -a`): Linux dionysus 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: 3 x86_64 nodes 
* Rook version (use `rook version` inside of a Rook Pod): 1.13.3
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.1
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.10+rke2r1", GitCommit:"b8609d4dd75c5d6fba4a5eaa63a5507cb39a6e99", GitTreeState:"clean", BuildDate:"2023-10-18T16:30:16Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.10+rke2r1", GitCommit:"b8609d4dd75c5d6fba4a5eaa63a5507cb39a6e99", GitTreeState:"clean", BuildDate:"2023-10-18T16:30:16Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): healthy

**Comment by sp98** [comment]
@barrettMCW can you share the `lsblk` output of one of the nodes where `nvme3n1` is available?

**Comment by barrettMCW** [comment]
NAME MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0
       7:0    0  63.5M  1 loop /snap/core20/2015
...
loop4
       7:4    0  40.4M  1 loop /snap/snapd/20671
sda    8:0    0  16.4T  0 disk 
└─ceph--0018fad4--ec7c--472d--acee--5c6ad2305b48-osd--block--3b356982--71cd--4450--a117--8426d2174c4c
     253:8    0  16.4T  0 lvm  
sdb    8:16   0  18.2T  0 disk 
└─ceph--6d11166f--ef0c--4d2c--a06e--94727c59a934-osd--block--3e706c20--898e--4976--8fd2--d904c8a6f753
     253:0    0  18.2T  0 lvm  
sdc    8:32   0  16.4T  0 disk 
└─ceph--4d251ead--7e52--4301--b770--2ad6192fdb70-osd--block--fd0501c3--e32b--4ec2--b94e--7e6d354bfb2a
     253:2    0  16.4T  0 lvm  
sdd    8:48   0  18.2T  0 disk 
└─ceph--292b55f8--0f23--4d7f--a88c--af915894a3a0-osd--block--1d3af60c--d238--4eea--9ec7--ad326ec8d696
     253:4    0  18.2T  0 lvm  
sde    8:64   0  16.4T  0 disk 
└─ceph--3c0a7a64--fe23--4401--8b7e--72c13fbce90d-osd--block--e192c1ef--f391--431e--bb80--b4b2ae75168d
     253:6    0  16.4T  0 lvm  
sdf    8:80   0  18.2T  0 disk 
sdg    8:96   0  18.2T  0 disk 
nbd0  43:0    0     0B  0 disk 
...
nbd7  43:224  0     0B  0 disk 
rbd0 252:0    0   100G  0 disk /var/lib/kubelet/pods/344cb762-cec7-4b12-aa93-130575acadc0/volumes/kubernetes.io~csi/pvc-d8bbd221-9a47-4ac0-ab39-012eec5b1ecc/mount
                               /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi
                               .ceph.com/af5c0db78c316dd044c5e48533cd2549952b1acfb949c3c163
                               18574ef0d3a7e8/globalmount/0001-0009-rook-ceph-0000000000000
                               004-add81f26-0f00-44e5-9b41-5f814da49505
...
rbd3 252:48   0   100G  0 disk /var/lib/kubelet/pods/d65172ad-13b5-4e89-b3a3-198a2699c5db/volumes/kubernetes.io~csi/pvc-5bca7ff9-1aec-4cea-897c-1d2c93e9ebc4/mount
                               /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.rbd.csi
                               .ceph.com/96adff1e36231f8464fba9e78556711615a390cfea91936f6e
                               403f83312c640b/globalmount/0001-0009-rook-ceph-0000000000000
                               004-b2bd479e-98dc-4b43-8738-ccfc506564d6
nvme0n1
     259:0    0   3.5T  0 disk 
nvme1n1
     259:1    0   3.5T  0 disk 
nvme2n1
     259:2    0   3.5T  0 disk 
nvme3n1
│    259:3    0   3.5T  0 disk 
├─ceph--41226caa--c499--4330--b0d5--f3eaf04a5518-osd--db--9826873c--daec--40bd--97a6--79bc2a7bf184
│    253:1    0 715.4G  0 lvm  
├─ceph--41226caa--c499--4330--b0d5--f3eaf04a5518-osd--db--6dce529c--3be7--4195--8b12--ceea3ab42e7c
│    253:3    0 715.4G  0 lvm  
├─ceph--41226caa--c499--4330--b0d5--f3eaf04a5518-osd--db--22eec1a6--bd11--4673--a519--b33509702d40
│    253:5    0 715.4G  0 lvm  
├─ceph--41226caa--c499--4330--b0d5--f3eaf04a5518-osd--db--d799133e--7393--4a32--a146--2822a51ab7ca
│    253:7    0 715.4G  0 lvm  
└─ceph--41226caa--c499--4330--b0d5--f3eaf04a5518-osd--db--1c26b5eb--2560--4347--a56c--1d8ae6a250b1
     253:9    0 715.4G  0 lvm  
nvme4n1
│    259:4    0 894.3G  0 disk 
├─nvme4n1p1
│    259:5    0     1G  0 part /boot/efi
├─nvme4n1p2
│    259:6    0    64G  0 part [SWAP]
└─nvme4n1p3
     259:7    0 829.2G  0 part /var/lib/kubelet/pods/90d3adb7-88a8-4c23-9fb1-a3beeb416966/volume-subpaths/omero-web-config/omero-web/0
                               /
nbd8  43:256  0     0B  0 disk 
...
nbd15
      43:480  0     0B  0 disk

**Comment by sp98** [comment]
@barrettMCW Looks like its not supported based on this comment - https://github.com/rook/rook/discussions/13221#discussioncomment-7592942 

Not to confirm the reason on why its not supported.

**Comment by barrettMCW** [comment]
dang! that discussion slipped past my web search! thanks! if this is something you guys are looking to add i'm happy to help. otherwise I'd imagine that this is something i could do manually with dmsetup or lv then add those as the metadata device?

**Comment by sp98** [comment]
> dang! that discussion slipped past my web search! thanks! if this is something you guys are looking to add i'm happy to help. otherwise I'd imagine that this is something i could do manually with dmsetup or lv then add those as the metadata device?

logical volumes should work.

**Comment by barrettMCW** [comment]
gotcha, i'll do work on that. any word on reasons for not supporting? beyond that we should be good to close. 
Thanks Santosh!

**Comment by sp98** [comment]
@guits Hi. Do you know if there is any `ceph-volume` limitation for adding new OSDs to use the existing metadata device?

**Comment by guits** [comment]
@sp98 when deploying OSDs with `lvm batch` method, if you pass a db device, ceph-volume will by default basically use all the available space on it and create as many LVs as you pass block devices. If later you want to add a new OSD, then the existing db device won't be available as there's no more free space on it.

**Comment by sp98** [comment]
> gotcha, i'll do work on that. any word on reasons for not supporting? beyond that we should be good to close. Thanks Santosh!

reason for not supporting it is mentioned in the comment above.  Closing it.

**Comment by guits** [comment]
@sp98 you might want to take a look at https://docs.ceph.com/en/latest/ceph-volume/lvm/batch/#sizing

**Comment by barrettMCW** [comment]
slots seem like a good workaround! Thanks guits!
@sp98 can we configure that from the cluster crd?

**Comment by sp98** [comment]
> slots seem like a good workaround! Thanks guits! @sp98 can we configure that from the cluster crd?

Reopened. I'll take a look if we can configure this from the Ceph CRD.

**Comment by sp98** [comment]
> > slots seem like a good workaround! Thanks guits! @sp98 can we configure that from the cluster crd?
> 
> Reopened. I'll take a look if we can configure this from the Ceph CRD.

A general consensus in the team is for the user to preprovision their `metadataDisk` with partitions/lvs rather than using Rook to do it via the CephCluster CR.

**Comment by barrettMCW** [comment]
you'll want a new issue for this @eyitayoafolabi 
my issue was attempting to add drives to a metadata device that is already in use. there is no resolution for this issue barring recreating all the osds used by the metadata device and instantiating them all at the same time, or the only other option is using no metadata device and storing metadata on the new device itself.
