### ISSUE TITLE
I would like to preform some benchmarks in Azure

### ISSUE THREAD

**Issue by AceHack** [rook/rook#1363]
I would like to compare Azure's managed disks in AKS vs rook on local temporary disks i.e. /dev/sdb1.

Two questions, can you suggest a good benchmark tool that I can install easily like with a helm chart in Kubernetes.  Second is there a way to force rook to use /dev/sdb1?

Also, do you have any suggestions for optimizing these tests?

https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-sizes-specs
https://blogs.msdn.microsoft.com/mast/2013/12/06/understanding-the-temporary-drive-on-windows-azure-virtual-machines/

**Comment by galexrt** [comment]
1. `fio` is a good tool to do rand read/write and I think also sequential read/write tests. I don't think there is a helm tool, but why not spawn the rook-toolbox with a PVC from Azure attached and then use the installed `fio` on the disk (examples https://github.com/axboe/fio/tree/master/examples).
2. Currently you can only use a full disk or a mounted directory. `sdb` would need to be empty (nothing, no partitions), and than the `deviceFilter` would allow you to set the filter accordingly to for `sdb` would be `^sdb`. Single partition aren't support unless they are mounted (and formatted).

**Comment by travisn** [comment]
For reference, we ran some FIO tests against AWS, documented in our [blog](https://blog.rook.io/run-your-own-high-performance-ebs-wherever-kubernetes-runs-798a136bd808). We had similar results in GCE, although didn't make it to the blog yet.

@AceHack Is there a change still needed in Rook to support the tests, or can we close the issue? We can follow up with questions in Slack.

**Comment by AceHack** [comment]
Yeah, I can come to slack, I still don't really understand how to get rook to use my local temporary drive on the Azure VMs though.  Thanks.
