### ISSUE TITLE
rook-ceph-exporter ServiceMonitor deleted during reconcile for wrong ceph cluster (more than one ceph cluster)

### ISSUE THREAD

**Issue by briend** [rook/rook#13642]
After upgrading to Rook `1.12.10` and Ceph Reef `v18.2.1` we noticed that our ceph OSD metrics would "come and go" seemingly randomly.  When the metrics were working on one ceph cluster they would stop working on another cluster.  When looking in the namespaces for these clusters, only one cluster would have a ServiceMonitor `rook-ceph-exporter`, and it would be deleted from the other cluster's namespace.

Basically it looks like `cleanupExporterResources()` doesn't need to be called here since the exporter Service and ServiceMonitor are not related to whether there are ceph pods (regardless of namespace) on a particular node:

https://github.com/rook/rook/blob/release-1.12/pkg/operator/ceph/cluster/nodedaemon/reconcile.go#L210-L213

Because our two ceph clusters do not have any k8s nodes in common, it seems like they will just flip flop between who gets to have the ServiceMonitor, this is because `cephPods` contains a list of [all ceph pods for all ceph clusters](https://github.com/rook/rook/blob/release-1.12/pkg/operator/ceph/cluster/nodedaemon/reconcile.go#L352), but then it only considers them by [namespace in the loop](https://github.com/rook/rook/blob/release-1.12/pkg/operator/ceph/cluster/nodedaemon/reconcile.go#L142)

The Service `rook-ceph-operator` is not affected, but I think that's because the `cleanupExporterResources` function is trying to delete it from the Operator namespace instead of the appropriate ceph cluster namespace: https://github.com/rook/rook/blob/release-1.12/pkg/operator/ceph/cluster/nodedaemon/reconcile.go#L93

So we have some doubts about whether that `cleanupExporterResources` should even be called (ever?) Again, these aren't node-specific resources so there should be no reason to delete the Service or ServiceMonitor unless you actually disable monitoring entirely.   Anything that considers `hasCephPods` is probably doing something unexpected when you have > 1 ceph cluster (>1 namespace) and k8s nodes that don't share pods between them.

**Comment by travisn** [comment]
Thanks for tracking that issue down, agreed that deleting from the operator namespace is an issue. @avanthakkar Could you fix this?
