### ISSUE TITLE
kubelet stopped then rook-ceph osd pod still deleted

### ISSUE THREAD

**Issue by xinzhongyoumeng** [rook/rook#13659]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The node kubelet service stopped, then the rook-ceph osd pod deleted
**Expected behavior:**
The node kubelet service stopped, then the rook-ceph osd pod status should be Terminating
**How to reproduce it (minimal and precise):**

1.stop one node kubelet service
2.observe the osd pod status in this node
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 22.04
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: 
* Rook version (use `rook version` inside of a Rook Pod): rook-ceph-v1.11.4 rook-ceph-cluster-v1.11.6
* Storage backend version (e.g. for ceph do `ceph -v`):ceph version 17.2.6
* Kubernetes version (use `kubectl version`): 1.20.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):rke2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by xinzhongyoumeng** [comment]
If is rook operator delete the osd pod ?

**Comment by sp98** [comment]
> If is rook operator delete the osd pod ?
Yes, Rook operator deletes the pods that are in terminating state. [See](https://github.com/rook/rook/blob/4a12234bbe3a37d7b8d2017bc54d0cca3d27f64d/pkg/operator/ceph/cluster/cephstatus.go#L293)

**Comment by xinzhongyoumeng** [comment]
thank you
