### ISSUE TITLE
Ceph mds myfs is on crashloopbackoff

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#13654]
installed on k8s on rook-ceph and there will be issue on ceph-mds-myfs its keep on crashloopbackoff, could you please help me on this.  the k8s version v1.21.5 and rook-ceph version is v1.8.1, below are the ceph-mds-myfs pod logs 

NAME                                                READY   STATUS             RESTARTS   AGE
csi-cephfsplugin-lnz4t                              3/3     Running            0          19h
csi-cephfsplugin-provisioner-7cd8f84796-mvssd       6/6     Running            0          19h
csi-cephfsplugin-provisioner-7cd8f84796-vbv8b       6/6     Running            0          19h
csi-cephfsplugin-q4vcq                              3/3     Running            0          19h
csi-cephfsplugin-rlqj8                              3/3     Running            0          19h
csi-rbdplugin-d58ht                                 3/3     Running            0          19h
csi-rbdplugin-fsfff                                 3/3     Running            0          19h
csi-rbdplugin-kt6kz                                 3/3     Running            0          19h
csi-rbdplugin-provisioner-6b877776d6-tpk64          6/6     Running            0          19h
csi-rbdplugin-provisioner-6b877776d6-zb6fv          6/6     Running            0          19h
rook-ceph-crashcollector-worker4-7b75646fcc-ck4bb   1/1     Running            0          19h
rook-ceph-crashcollector-worker5-79689f55c8-l57q6   1/1     Running            0          19h
rook-ceph-crashcollector-worker6-7769cb8689-rf44s   1/1     Running            0          19h
rook-ceph-mds-myfs-a-5b84d6c7cb-q8vdx               1/2     CrashLoopBackOff   99         19h
rook-ceph-mds-myfs-b-69bccd6748-zfgnd               2/2     Running            0          19h
rook-ceph-mgr-a-ddf7cb98-xw8l2                      2/2     Running            0          19h
rook-ceph-mon-a-5bb67cd5f6-z8gbd                    2/2     Running            0          19h
rook-ceph-mon-b-5dc686789f-4l2fg                    2/2     Running            0          19h
rook-ceph-mon-c-cd764587b-9zpxw                     2/2     Running            0          19h
rook-ceph-operator-795b5c88cb-9vwsm                 1/1     Running            0          19h
rook-ceph-osd-0-5948b9bb99-pzkkg                    2/2     Running            0          19h
rook-ceph-osd-1-6dd6546777-w5m8z                    2/2     Running            0          19h
rook-ceph-osd-2-6d867c548d-nptkz                    2/2     Running            0          19h
rook-ceph-osd-prepare-worker4-79867                 0/1     Completed          0          59m
rook-ceph-osd-prepare-worker5-q5tv8                 0/1     Completed          0          59m
rook-ceph-osd-prepare-worker6-sqmbs                 0/1     Completed          0          59m
rook-ceph-tools-76598c54f4-6nb7m                    1/1     Running            0          19h
-------------------------
logs
==========
`kubectl logs -f rook-ceph-mds-myfs-a-5b84d6c7cb-q8vdx -n rook-ceph
error: a container name must be specified for pod rook-ceph-mds-myfs-a-5b84d6c7cb-q8vdx, choose one of: [mds log-collector] or one of the init containers: [chown-container-data-dir]
labadmin@master:~$ kubectl logs -f rook-ceph-mds-myfs-a-5b84d6c7cb-q8vdx -n rook-ceph mds
debug 2024-01-31T04:24:44.613+0000 7f3ec8153780  0 set uid:gid to 167:167 (ceph:ceph)
debug 2024-01-31T04:24:44.613+0000 7f3ec8153780  0 ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable), process ceph-mds, pid 10632
debug 2024-01-31T04:24:44.613+0000 7f3ec8153780  1 main not setting numa affinity
debug 2024-01-31T04:24:44.613+0000 7f3ec8153780  0 pidfile_write: ignore empty --pid-file
starting mds.myfs-a at
debug 2024-01-31T04:25:14.617+0000 7f3ec8153780  0 monclient: wait_auth_rotating timed out after 30
debug 2024-01-31T04:25:14.617+0000 7f3ec8153780 -1 mds.myfs-a unable to obtain rotating service keys; retrying

`

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by sp98** [comment]
@vadlakiran Can you trying upgrading the K8s version?  
[Prerequisite](https://rook.io/docs/rook/latest-release/Getting-Started/Prerequisites/prerequisites/#kubernetes-version) is to use 1.23 or newer version of k8s.

**Comment by vadlakiran** [comment]
@sp98 we have multiple environments with same k8s version and same rook-ceph version v1.8.1 why in this environment getting issue

**Comment by sp98** [comment]
> @sp98 we have multiple environments with same k8s version and same rook-ceph version v1.8.1 why in this environment getting issue

what environment are you using? 
Also, please provide:
- rook ceph operator logs. 
- `ceph status` output from the tool box. 
- And complete logs of the failing mds myfs pod.
