### ISSUE TITLE
non of osd is healthy

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13658]
**Is this a bug report or feature request?**
* Bug Report
```
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.2.1/rpm/el8/BUILD/ceph-18.2.1/src/common/config.cc: In function 'void md_config_t::set_val_default(ConfigValues&, const ConfigTracker&, std::string_view, const string&)' thread 7f79809f4640 time 2024-01-31T06:45:47.248926+0000
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/18.2.1/rpm/el8/BUILD/ceph-18.2.1/src/common/config.cc: 274: FAILED ceph_assert(r >= 0)
 ceph version 18.2.1 (7fe91d5d5842e04be3b4f514d6dd990c54b29c76) reef (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x135) [0x5561b42eb5b3]
 2: ceph-osd(+0x62d779) [0x5561b42eb779]
 3: (md_config_t::set_val_default(ConfigValues&, ConfigTracker const&, std::basic_string_view<char, std::char_traits<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xce) [0x5561b4b036ce]
 4: (md_config_t::parse_env(unsigned int, ConfigValues&, ConfigTracker const&, char const*)+0x57d) [0x5561b4b1795d]
 5: (global_pre_init(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const*, std::vector<char const*, std::allocator<char const*> >&, unsigned int, code_environment_t, int)+0x2f0) [0x5561b4a624c0]
 6: (global_init(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const*, std::vector<char const*, std::allocator<char const*> >&, unsigned int, code_environment_t, int, bool)+0x83) [0x5561b4a646b3]
 7: main()
 8: __libc_start_main()
 9: _start()
```
```
rook-ceph-osd-0-fc6567685-7k8g9                       1/2     CrashLoopBackOff   6 (76s ago)     8m20s
rook-ceph-osd-1-5689f5846-zt52h                       1/2     CrashLoopBackOff   6 (63s ago)     8m21s
rook-ceph-osd-2-7485788d7c-hcw2g                      1/2     CrashLoopBackOff   6 (8s ago)      7m36s
rook-ceph-osd-3-d57df89d5-bscjz                       1/2     CrashLoopBackOff   5 (103s ago)    6m57s
rook-ceph-osd-4-6c944d9fdd-bb5sg                      1/2     CrashLoopBackOff   5 (2m39s ago)   7m35s
rook-ceph-osd-5-59f46ff474-rxgbg                      1/2     CrashLoopBackOff   5 (2m16s ago)   6m58s
rook-ceph-osd-6-5d66587d48-p66fm                      1/2     CrashLoopBackOff   6 (29s ago)     7m12s
rook-ceph-osd-7-fd5d78db8-bmzvg                       1/2     CrashLoopBackOff   6 (15s ago)     7m8s
```

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):1.13.1
* Storage backend version (e.g. for ceph do `ceph -v`):18.2.1
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by sp98** [comment]
@13567436138 
- what environment are you using?
- Was there any event after which the osd pods went into CLBO? 
- Please share rook operator logs
- Please share complete logs of the OSD pod  in CLBO.

**Comment by rkachach** [comment]
@13567436138 this is a crash in ceph code. Please, open a tracker on the ceph project providing as much detailed information on how to reproduce it as possible. A BUG report describing a broken cluster status without proving more information on how you reach such state nor logs of the critical components in general is not helpful for devs.
