### ISSUE TITLE
The StorageClass "cephfs" is invalid: provisioner: Invalid value: "rook-ceph=.cephfs.csi.ceph.com":

### ISSUE THREAD

**Issue by achernya** [rook/rook#13679]
**Is this a bug report or feature request?**
Bug report

**Deviation from expected behavior:**
I believe there's a typo on https://github.com/rook/rook/blob/master/deploy/examples/import-external-cluster.sh#L27

When I attempt to use the import-external-cluster.sh script, I get the following output:

```
The StorageClass "cephfs" is invalid: provisioner: Invalid value: "rook-ceph=.cephfs.csi.ceph.com": name part must consist of alphanumeric characters, '-', '_' or '.', and must st
art and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

**Expected behavior:**
```
[snip]
storageclass.storage.k8s.io/cephfs created                                               
```

**How to reproduce it (minimal and precise):**
Follow the instructions at https://rook.io/docs/rook/latest-release/CRDs/Cluster/external-cluster/?h=external#import-the-source-data

I removed the stray `=`, and the script passes successfully. I'm happy to submit a PR --- I just want confirmation that the fix makes sense :)

**File(s) to submit**:
N/A

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
N/A

**Logs to submit**:
N/A

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):Debian GNU/Linux 12 (bookworm)
* Kernel (e.g. `uname -a`): 6.1.0-17-cloud-amd64
* Cloud provider or hardware configuration: v1.13.3
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): v1.29.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by achernya** [comment]
Looks like this was introduced in c35a8532aa39133f2780e63d9dadfccc79cce675, previously there was no `=`. @Madhu-1

**Comment by Madhu-1** [comment]
@achernya Yes if you remove `=` that is enough, please feel free to fix it :)

**Comment by achernya** [comment]
Thanks!
