### ISSUE TITLE
General inquiry : cephfs does not support  mount option discard ?

### ISSUE THREAD

**Issue by luckydogxf** [rook/rook#13678]
Hi, I'm curious.

rook-cephfs storage class does not support this option ?
```
mountOptions:
  - discard 
```
when I added it and deployed a cephfs PVC , it failed with 'invalid argument'

ceph version 
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)

The reason why I ask this is because I find all cephfs pool keeps growing even if after data on cephfs was removed.
Refer to this link [https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems#types-of-block-discard-operations_discarding-unused-blocks](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems#types-of-block-discard-operations_discarding-unused-blocks)

**Comment by luckydogxf** [comment]
Seems it's related to Base image of containers. I

**Comment by Madhu-1** [comment]
@luckydogxf thats an invalid mount option for cephfs. some details here https://github.com/ceph/ceph-csi/blob/v3.9.0/docs/ceph-csi-upgrade.md/#24-modifying-mountoptions-in-storageclass-and-persistentvolumes
