### ISSUE TITLE
Ceph: config: use default /var/lib/ceph path for ceph inside the rook container

### ISSUE THREAD

**Issue by bassam** [rook/rook#1368]
* Feature Request

Are there any similar features already existing: no.

What should the feature do:
Inside rook containers ceph should use the default data dir `/var/lib/ceph` and config dir `/etc/ceph`. When we add other backends they should also use their default data dirs.

Rook itself could have a data dir `/var/lib/rook` if needed but it should not overlap with `/var/lib/ceph` or other backends.

when using `dataDirHostPath` the operator should generate pod specs that bind mount the appropriate directories inside the container to the host, and do so in a way that can support multiple distinct clusters/namespaces running on the the same host. One possible scheme to consider on the host is as follows: `/var/lib/rook/$backend/$namespace/{lib,etc}`

this is based on a discussion that started [here](https://github.com/rook/rook/pull/1346#discussion_r159271387)

**Comment by BlaineEXE** [comment]
I think we also want to make sure that the path used on the host continues to be configurable, and I think `/var/lib/rook/$backend/$namespace/{lib,etc}` is a sensible default value.

**Comment by BlaineEXE** [comment]
I was actually thinking about this yesterday as I was working on https://github.com/rook/rook/pull/2048. I like the idea of changing the internal config dir to the default(s) and making sure multiple clusters can coexist safely.

**Comment by BlaineEXE** [comment]
@travisn, This is related to my comment https://github.com/rook/rook/pull/2114#discussion_r218525336

Since I have a lot of this info in my head from the init container refactor work, I'll pick this up next, since it seems fairly straightforward. Can you add this to 0.9 milestone?

**Comment by travisn** [comment]
Sounds good, as I mentioned separately, the challenge with this change may be around upgrades.

**Comment by BlaineEXE** [comment]
Due to the challenge with upgrades, this probably isn't worth changing, even if it's not 100% ideal. Conversation snippet logged here for future reference. Closing issue.

```
Blaine [11:49 AM]
Currently, I haven't seen anything that suggests multiple clusters could run the same daemon+name (e.g., mon-a) on the same node and not stomp each others' data. They would both write to /var/lib/rook/mon-a on the disk. I think this has to be addressed eventually, but it needn't be immediately.
travisn [11:50 AM]
ok, I didn’t see that. The requirement right now is that the user has to set a different `dataDirHostPath` to avoid clusters stomping on each other.
Blaine [11:51 AM]
I suppose that would be the other way to ensure that, yes. So maybe it doesn't need addressed. Changing it would be more for "don't allow users to shoot themselves in the foot" than necessity.
travisn [11:52 AM]
I don’t think people create multiple clusters very often either. Yeah we are probably fine.
Blaine [11:52 AM]
+1
travisn [11:53 AM]
The bigger concern for shooting themselves in the foot is usage of devices between multiple clusters
Blaine [11:53 AM]
That's a big point
travisn [11:53 AM]
if they get their settings wrong, the operator will happily stomp on the devices across clusters
```

**Comment by liewegas** [comment]
Hmm... my preference would definitely to be to fix this.  It is always going to be easier to fix sooner rather than later as the install base is only going to grow.

**Comment by travisn** [comment]
@liewegas what is the side effect of not changing this? I imagine it impacts troubleshooting since the files are in a different place than expected.

**Comment by liewegas** [comment]
Yeah.. I think the it is primarily just going to be friction when anyone looks behind the curtain.  There is also some possibility of bugs (in various tools, scripts) due to the non-standard location.

**Comment by liewegas** [comment]
Can we just update the CRD on upgrade so that legacy clusters get an explicit property specifying the old default path, and any new clusters/CRDs use a new default?

**Comment by travisn** [comment]
instead of a setting in the crd, we could write the setting to a configmap since it should be an internal implementation detail. @BlaineEXE could you take a look at this then?

**Comment by travisn** [comment]
per conversation in huddle, moving to 1.0 so we can manage the risk earlier in the cycle and time to stabilize with other features such as ceph-volume.

**Comment by BlaineEXE** [comment]
This work is being done along with the rejiggering of the daemons to be configured in the operator as much as possible. I think we can consider this completed once we have support for the mon kv store in mimic+.
