### ISSUE TITLE
Multi-Attach error for volume "pvc-xxxx-xxxx-xxxx" Volume is already exclusively attached to one node and can't be attached to another.

### ISSUE THREAD

**Issue by palthisailohith** [rook/rook#13698]
Hi team,
 
**Issue Description:**
We are encountering a multi-attach error for "Read Write Once" PVC created using RBD storage class in Rook-Ceph. The issue persists even after the pod is deleted and assigned to a different node.
 
**Environment:**
- Kubernetes version: v1.25.9
- Rook-Ceph version: v1.12.10
- Ceph version: v17.2.6
 
**Details:**
This problem was previously experienced in Ceph 1.10 version and continues in the 1.12.10 version. The current workaround involves resolving the issue temporarily by unmapping the associated RBD image with the force flag.
 
**Steps to Reproduce:**
1. Create a "Read Write Once" PVC using RBD storage class.
2. Deploy a pod using the created PVC.
3. Delete the pod and try to assign it to a different node.
 
**Expected Behavior:**
The volume should be successfully attached to the new node without encountering a multi-attach error.
 
**Additional Information:**
- Getting the below logs:
   "Multi-Attach error for volume "pvc-xx-xx-xx-xx-xx" Volume is already exclusively attached to one node and can't be attached to another"

 
**Is there any way to fix this issue permanently?**
 
Looking forward to your assistance in resolving this matter permanently.
 
Thank you!

**Comment by Madhu-1** [comment]
@palthisailohith The error you are seeing looks to be from kubernetes not by Rook.

**Comment by akash123-eng** [comment]
@Madhu-1 Yes we are aware of that this is  response by kubernetes. 
But it's happening due to rook ceph bug which doesn't release rbd image even though pod is deleted and due to which we face this multi attach error.
So wanted to know is there any permanent solution for this
Can you please help on that

**Comment by akash123-eng** [comment]
@Madhu-1 cab you please help on above

**Comment by Madhu-1** [comment]
@akash123-eng what you are experiencing is the behavior of the kubernetes. am afraid nothing is related to Rook here, its kubelet responsibility to issue RPC call to CSI to umount/unmap the rbd image from there the pod is getting deleted

**Comment by banjoh** [comment]
@palthisailohith you probably already checked this, but worth asking. Is the volume mounted by another pod running on a different node from the failing pod?

**Comment by luomengY** [comment]
> [@palthisailohith](https://github.com/palthisailohith) you probably already checked this, but worth asking. Is the volume mounted by another pod running on a different node from the failing pod?

Yes, I've encountered this issue as well.

log:
  Normal   Scheduled           6m16s  default-scheduler        Successfully assigned harbor/harbor-trivy-0 to master1
  Warning  FailedAttachVolume  6m17s  attachdetach-controller  Multi-Attach error for volume "pvc-3f44ca3f-cc06-4520-aa55-143c2edd6d8c" Volume is already exclusively attached to one node and can't be attached to another
