### ISSUE TITLE
Enabling monitoring doesn't successfully deploy related resources.

### ISSUE THREAD

**Issue by cleanior** [rook/rook#13702]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The RBAC resources related to the monitoring are not properly deployed.

The Service monitors are not deployed since the ceph-operator lacks the [proper RBAC roles](https://github.com/rook/rook/blob/v1.13.2/deploy/charts/library/templates/_cluster-monitoring.tpl).
The k8s cluster already had the prometheus operator, so the APIs and related CRDs including ServiceMonitor were there before we tried to install ceph-operator and ceph-cluster.
However, ceph-operator couldn't install the service monitor which results in failure of ceph-cluster creation.

**Expected behavior:**
When we set the **monitoring** field to **true**, the proper RBAC roles should be installed, first, successfully, so that each service monitor for ceph-operator and ceph-cluster can be installed successfully as well.

**How to reproduce it (minimal and precise):**

We used the tag, v1.13.2 and tried to install through helm chart.
Set the **monitoring** to **true** in **values.yaml** for each package, ceph-operator and ceph-cluster and install them.
The package hangs to deploy reporting **"failed to enable service monitor....."**

If we manually deploy the RBAC roles and role bindings for ceph-operator, the deployment for each are successfully done.
without manual deployment, they hang for the lacks of RBAC resources.

**Logs to submit**:

* Operator's logs, if necessary
```
ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph".
failed to reconcile cluster "rook-ceph":
failed to configure local ceph cluster:
failed to create cluster:
failed to start ceph mgr:
failed to enable mgr services:
failed to enable service monitor: service monitor could not be enabled: failed to retrieve servicemonitor.
servicemonitors.monitoring.coreos.com "rook-ceph-mgr" is forbidden:
User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"
```
```
ceph-nodedaemon-controller:
node reconcile failed:
failed to enable service monitor:
service monitor could not be enabled: failed to retrieve servicemonitor.
servicemonitors.monitoring.coreos.com "rook-ceph-exporter" is forbidden:
User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 22.04.2 LTS
* Kernel (e.g. `uname -a`): 5.15.0-91-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.13.2, go: go1.21.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 18.2.1 (7fe91d5d5842e04be3b4f514d6dd990c54b29c76) reef (stable)
* Kubernetes version (use `kubectl version`): Client Version: 1.26, Server Version: 1.26
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by rkachach** [comment]
@cleanior have you tried to apply the rbac rules on `monitoring/rbac.yaml`?

**Comment by cleanior** [comment]
> @cleanior did you try to apply the rbac rules on `monitoring/rbac.yaml`? you can find more information on [Rook Monitoring](https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-monitoring/#prometheus-consoles)

@rkachach Yeah, as I mentioned [above](https://github.com/rook/rook/issues/13702#:~:text=If%20we%20manually%20deploy%20the%20RBAC%20roles%20and%20role%20bindings%20for%20ceph%2Doperator%2C%20the%20deployment%20for%20each%20are%20successfully%20done.%0Awithout%20manual%20deployment%2C%20they%20hang%20for%20the%20lacks%20of%20RBAC%20resources.), if I manually deploy the needed [RBAC resources](https://github.com/rook/rook/blob/v1.13.2/deploy/charts/library/templates/_cluster-monitoring.tpl) which are to be installed, automatically, by enabling the **monitoring.enabled** fields in values.yaml for each package, all seems going fine. The point is that the RBAC roles and rolebindings for monitoring are not installed with the **monitoring.enabled** fields set to true.

**Comment by travisn** [comment]
@cleanior You set `monitoring.enabled: true` in both of the charts? If only one is set, the needed RBAC won't be created. If you are already setting them, perhaps there is a bug in the helm chart. Are you installing to the default `rook-ceph` namespace or a different namespace?

**Comment by cleanior** [comment]
@travisn Sorry for the delayed reply. Yes, of course I set `monitoring.enabled: true` in both of the charts, for `rook-ceph` and `rook-ceph-cluster`. And also installed using the default namespace which is `rook-ceph` as well.

**Comment by vincedihub** [comment]
i have a similar problem

```
2024-04-03 16:45:45.447706 E | ceph-nodedaemon-controller: node reconcile failed: failed to enable service monitor: service monitor could not be enabled: failed to retrieve servicemonitor. servicemonitors.monitoring.coreos.com "rook-ceph-exporter" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-cluster-global"
2024-04-03 16:45:45.880097 E | ceph-nodedaemon-controller: node reconcile failed: failed to enable service monitor: service monitor could not be enabled: failed to retrieve servicemonitor. servicemonitors.monitoring.coreos.com "rook-ceph-exporter" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-cluster-global"
2024-04-03 16:45:46.845147 E | ceph-nodedaemon-controller: node reconcile failed: failed to enable service monitor: service monitor could not be enabled: failed to retrieve servicemonitor. servicemonitors.monitoring.coreos.com "rook-ceph-exporter" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-cluster-global"
```

**Comment by travisn** [comment]
@vincedihub Did you create the `monitoring/rbac.yaml` as specified in the [prometheus config guide](https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-monitoring/#prometheus-consoles)?
