### ISSUE TITLE
ERROR: unable to open OSD superblock on /var/lib/ceph/osd/ceph-3: (2) No such file or directory    pvc based rook

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13748]
**Is this a bug report or feature request?**
* Bug Report
```
Croot@storage-b-01:~# kubectl logs -n rook-ceph rook-ceph-osd-3-5d7f669478-cn84c 
Defaulted container "osd" out of: osd, log-collector, blkdevmapper (init), activate (init), expand-bluefs (init), chown-container-data-dir (init)
debug 2024-02-11T12:46:00.648+0000 7f12e5ad8640  0 set uid:gid to 167:167 (ceph:ceph)
debug 2024-02-11T12:46:00.648+0000 7f12e5ad8640  0 ceph version 18.2.1 (7fe91d5d5842e04be3b4f514d6dd990c54b29c76) reef (stable), process ceph-osd, pid 385
debug 2024-02-11T12:46:00.648+0000 7f12e5ad8640  0 pidfile_write: ignore empty --pid-file
debug 2024-02-11T12:46:00.648+0000 7f12e5ad8640 -1 bluestore(/var/lib/ceph/osd/ceph-3/block) _read_bdev_label failed to open /var/lib/ceph/osd/ceph-3/block: (13) Permission denied
debug 2024-02-11T12:46:00.648+0000 7f12e5ad8640 -1  ** ERROR: unable to open OSD superblock on /var/lib/ceph/osd/ceph-3: (2) No such file or directory
```
**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by sp98** [comment]
Its possible that the disk backing the OSD is not available anymore or got renamed after node reboot.  
@13567436138 Can you please confirm if that's not the case?

**Comment by 13567436138** [comment]
yes i have restart the node,because i am using vmware workstation

**Comment by 13567436138** [comment]
delete all osd pod,and now all osd pod are ok.
```
bash-4.4$ ceph -s
  cluster:
    id:     7e4a1d4e-7041-454f-bbf6-6784c7a6fc90
    health: HEALTH_WARN
            Reduced data availability: 1 pg inactive
            Degraded data redundancy: 1 pg undersized
            16 daemons have recently crashed
 
  services:
    mon: 3 daemons, quorum a,b,c (age 14m)
    mgr: b(active, since 15m), standbys: a
    osd: 7 osds: 7 up (since 78s), 7 in (since 78s)
 
  data:
    pools:   1 pools, 1 pgs
    objects: 0 objects, 0 B
    usage:   994 MiB used, 34 GiB / 35 GiB avail
    pgs:     100.000% pgs not active
             1 undersized+peered
```
    pgs:     100.000% pgs not active   how to solve this problem???

**Comment by dgioulakis** [comment]
> yes i have restart the node,because i am using vmware workstation

Thanks for this! I expanded a disk on my ESXi VM while running from 128GB to 256GB. Did a rescan and Ubuntu Server picked up the new size. Ceph did as well after marking the OSD as out and down. But when the OSD started back up, Ceph reported I was using 128GB of space. After rebooting the VM, Ceph did whatever magic it needed to and now shows the correct usage and total size.

**Comment by occ** [comment]
I'm hitting a similar issue without any modifications to the underlying devices.

In the last month we've had a couple of OSDs failing to restart, getting stuck in a "pending" state. 
Log from an incident from today:

```
debug 2025-04-21T21:58:34.328+0000 7f0f5b1c6680 0 set uid:gid to 167:167 (ceph:ceph)
debug 2025-04-21T21:58:34.328+0000 7f0f5b1c6680 0 ceph version 19.2.2 (0eceb0defba60152a8182f7bd87d164b639885b8) squid (stable), process ceph-osd, pid 713
debug 2025-04-21T21:58:34.328+0000 7f0f5b1c6680 0 pidfile_write: ignore empty --pid-file
debug 2025-04-21T21:58:34.329+0000 7f0f5b1c6680 1 bdev(0x5590da32ee00 /var/lib/ceph/osd/ceph-8/block) open path /var/lib/ceph/osd/ceph-8/block
debug 2025-04-21T21:58:34.329+0000 7f0f5b1c6680 -1 bdev(0x5590da32ee00 /var/lib/ceph/osd/ceph-8/block) open open got: (13) Permission denied
debug 2025-04-21T21:58:34.329+0000 7f0f5b1c6680 -1 ** ERROR: unable to open OSD superblock on /var/lib/ceph/osd/ceph-8: (2) No such file or directory

```

I'm not sure how to debug this. If you can direct me, I can add more information.

Brief info about my cluster:
* 12 nodes with 3x NVMes per node
* Partitions are identified by partlabels (/dev/disk/by-partlabel/osd{0,1,2}
* This seems to happen after a crash or possibly an OOM-kill
* Deleting the Pod doesn't do anything, but restarting the Deployment fixes the issue - without restarting the node or touching other OSDs on the same node.
