### ISSUE TITLE
RGW Deployment should have pod anti-affinity against itself

### ISSUE THREAD

**Issue by dab-q** [rook/rook#1374]
**Bug Report**

What happened:
On a 5 node cluster, I changed the RGW deployment scale to 10, and 10 RGW pods were created across 4 nodes:
```
rook-ceph-rgw-default-2402708082-0vlxl   1/1       Running   0          12d       10.36.0.7      172.17.8.103
rook-ceph-rgw-default-2402708082-1xs3s   1/1       Running   0          1m        10.44.0.8      172.17.8.102
rook-ceph-rgw-default-2402708082-3dnbk   1/1       Running   0          12d       10.47.0.6      172.17.8.105
rook-ceph-rgw-default-2402708082-5pd93   1/1       Running   0          1m        10.36.0.9      172.17.8.103
rook-ceph-rgw-default-2402708082-flrzf   1/1       Running   0          1m        10.47.0.7      172.17.8.105
rook-ceph-rgw-default-2402708082-nkbdt   1/1       Running   0          1m        10.47.0.8      172.17.8.105
rook-ceph-rgw-default-2402708082-q5fp0   1/1       Running   0          1m        10.39.0.10     172.17.8.104
rook-ceph-rgw-default-2402708082-sqfx4   1/1       Running   0          12d       10.39.0.8      172.17.8.104
rook-ceph-rgw-default-2402708082-tcq8n   1/1       Running   0          1m        10.39.0.9      172.17.8.104
rook-ceph-rgw-default-2402708082-wmtqc   1/1       Running   0          1m        10.36.0.8      172.17.8.103
```
What you expected to happen:
The rgw pods should have anti-affinity against themselves, so that no more than one rgw pod would get scheduled on any given node.  If hostnetworking is enabled, multiple rgw pods running on the same node will clash with each other for networking resources.

How to reproduce it (minimal and precise):
```
kubectl -n rook scale --replicas=10 deployment/rook-ceph-rgw-default
```

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1590.2.0
VERSION_ID=1590.2.0
BUILD_ID=2017-12-06-0313
PRETTY_NAME="Container Linux by CoreOS 1590.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

* Kernel (e.g. `uname -a`): Linux core-01 4.14.4-coreos #1 SMP Wed Dec 6 02:57:40 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz GenuineIntel GNU/Linux

* Cloud provider or hardware configuration: coreos-vagrant VM configuration
* Rook version: v0.6.0-96.g043cd8b
* Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T18:34:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type: created via `kubeadm`
* Ceph status : HEALTH_OK

**Comment by travisn** [comment]
Today you can set the anti-affinity in the object CRD under the placement, podAntiAffinity. I believe you would want something like this:
```
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-rgw
```

**Comment by dab-q** [comment]
I'm thinking specifically about the code in pkg/operator/rgw/rgw.go where it creates the RGW Deployment, as where the AntiAffinity needs to be added.
