### ISSUE TITLE
Change the code to be explicit when setting the value of AllowPrivilegeEscalation

### ISSUE THREAD

**Issue by rkachach** [rook/rook#13749]
**Is this a bug report or feature request?**
* Feature Request

As of the docs from [security context](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1) it's not clear what's the default value of AllowPrivilegeEscalation. And there're some open issues related to this such as https://github.com/kubernetes/website/issues/30104 and https://github.com/appvia/psp-migration/issues/298. 

However, from [the code](https://github.com/kubernetes/kubernetes/blob/8b2dae57d4169e7801c870aa86f5644085518c57/pkg/securitycontext/util.go#L175) it seems that `AllowPrivilegeEscalation` default value is false. In order to avoid any confusion let's initialize explicitly the value of this field so it becomes clear how the containers security context is initialized and user can see the current value of the `privileged` and `AllowPrivilegeEscalation` fields when inspecting the containers. 

For more context, this discussion was generated upstream in slack [in the thread](https://rook-io.slack.com/archives/CK9CF5H2R/p1707309286322019)

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
Anytime the security settings are touched, there is some risk of regression, so we would need to test in different environments such as openshift. If we don't have a clear need to set this, seems like better to leave it untouched. Can you provide more context about the source of confusion? Was some upstream or downstream user asking?

**Comment by rkachach** [comment]
> Anytime the security settings are touched, there is some risk of regression, so we would need to test in different environments such as openshift. If we don't have a clear need to set this, seems like better to leave it untouched. Can you provide more context about the source of confusion? Was some upstream or downstream user asking?

I see, since it's not critical issue and the default value seems already to be false I don't really see the need for this change as it's just an enhancement.

**Comment by travisn** [comment]
Thanks for the background. I would suggest we close this issue and keep the default K8s value, just to be safe not to introduce a regression.

**Comment by rkachach** [comment]
@travisn I also agree on not running on unnecessary risks specially since there's no real security issue in this case.
