### ISSUE TITLE
Descriptions of several CRDs are broken

### ISSUE THREAD

**Issue by rkachach** [rook/rook#13765]
**Is this a bug report or feature request?**
* Bug Report
Several descriptions are broken randomly (at 100chars) such as:
https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/resources.yaml#L2198
https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/resources.yaml#L2233

Descriptions were shortened origianlly by the PR https://github.com/rook/rook/pull/13517 to solve an issue related to reaching the maximum size. The original limitation reported in https://github.com/kubernetes/kubernetes/issues/82292 is still open and it doesn't seem to be fixed in the short term.

`controller-gen` code  doesn't seem to handle correctly the description and has a `TODO` to improve that logic.. thus we can't rely on this tool doing great job for all the cases:

https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/desc_visitor.go#L62-L73

```
// truncateString truncates given desc string if it exceeds maxLen. It may
// return string with length less than maxLen even in cases where original desc
// exceeds maxLen because it tries to chop off the desc at the closest sentence
// boundary to avoid incomplete sentences.
func truncateString(desc string, maxLen int) string {
	desc = desc[0:maxLen]

	// Trying to chop off at closest sentence boundary.
	if n := strings.LastIndexFunc(desc, isSentenceTerminal); n > 0 {
		return desc[0 : n+1]
	}
	// TODO(droot): Improve the logic to chop off at closest word boundary
	// or add elipses (...) to indicate that it's chopped incase no closest
	// sentence found within maxLen.
	return desc
}
```

**Deviation from expected behavior:**
Descriptions are not meaningful 

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
An alternative we have discussed in the past is to remove the descriptions completely, but we thought truncated descriptions would be more useful than no descriptions.

**Comment by BlaineEXE** [comment]
We could also investigate:
- is there a kubebuilder directive to not generate docs for a struct node?
- could we use yq post-processing to remove descriptions below a certain depth?
- could we auto-replace docs with links to Rook docs?

**Comment by rkachach** [comment]
@BlaineEXE I like the 3rd idea about using links instead of generating the description itself. My only doubt there if this is something editors do support or the user has to visit the link manually.

**Comment by BlaineEXE** [comment]
Options 2 and 3 both would need yq post-processing I think. Maybe we could do a mix of both.

**Comment by BlaineEXE** [comment]
I reset my `build-crds.sh` script back to `MAX_DESC_LEN:=-1` (unlimited), generated CRDs, and then used this command to get an idea of what descriptions are overloading our CRDs.

```
cat deploy/examples/crds.yaml | grep description | sed 's/^[[:space:]]*//g' | sort  > descrips.yml
```

Overall I notice 2 particular places with a huge quantity of long results:
- the `status` component of `VolumeClaimTemplates` -- we don't need to include PVC status in our CRDs
- documentation for label selectors, annotations, topo spread constraints, etc. -- basically all of our `placement` configs

It may be more helpful to try to modify `types.go` to not include docs for these and then see how that changes our CRD sizes.
