### ISSUE TITLE
CephFS mount issue  happening frequently on any one random node 

### ISSUE THREAD

**Issue by akash123-eng** [rook/rook#13778]
Hi Team,

We are seeing some random CephFS mount issue. its happening on any one random node.
when we restart cephFS plugin pod for that node issue gets fixed. 
But this is happening quiet frequently and each time node is different

Logs of cephFs plugin for that node shows errors :
**An operation with given volume ID 00- already exists**

when we checked /var/log/messages of that node we see some mon session lost logs after which issue was started logs are like

**kernel libceph: mon socket closed
kernel: libeph: session lost,haunting for new mon** 

and can see some client blocklist in 
**ceph osd blocklist ls**  output but when we checked the client ip it was of a rook-ceph-mgr pod which was on different node and not node on which we were facing the issue.

there are no warning/errors in ceph status output.

So we needed your help to troubleshoot it i.e what could be the reason behind this issue  and how to fix it ? 

**Environment**: 
Kubernetes
* OS (e.g. from /etc/os-release): Centos 7.9
* Rook version (use `rook version` inside of a Rook Pod): .  rook operator 1.10.8 
* Storage backend version (e.g. for ceph do `ceph -v`): Ceph 17.2.6
* Kubernetes version (use `kubectl version`): 1.26.8

**Comment by Rakshith-R** [comment]
@akash123-eng network issues/instability may cause ceph client to be blocklisted. 
That would be the first place to check.

**Comment by akash123-eng** [comment]
Yes @Rakshith-R it's may ne due to network issue but as I mentioned in the issue blocklisted client ip is pod ip of mgr pod schedule on other node
And we are facing issue only on 1 particular node which is not present is blacklisted clients

**Comment by Rakshith-R** [comment]
> Yes @Rakshith-R it's may be due to network issue but as I mentioned in the issue blocklisted client ip is pod ip of mgr pod scheduled on other node And we are facing issue only on 1 particular node which is not present is blacklisted clients

Network issues and ceph cluster instability also causes ceph cmds issued by cephcsi to hang and lead to operation already exists error. 

Fixing that should fix everything.

**Comment by akash123-eng** [comment]
@Rakshith-R  Yes but whenever we face this issue ceph status is all healthy and fine.
And also this happens on any random node.
So I just wanted to know the sequence of the issue 
Below error from the node around the time period during when issue started not exact same time but 5-10 mins 

kernel libceph: mon socket closed
kernel: libeph: session lost,haunting for new mon

So is this any indication that this issue might cause cephFs mount issue ?

**Comment by Rakshith-R** [comment]
> @Rakshith-R Yes but whenever we face this issue ceph status is all healthy and fine. And also this happens on any random node. So I just wanted to know the sequence of the issue Below error from the node around the time period during when issue started not exact same time but 5-10 mins
> 
> kernel libceph: mon socket closed kernel: libeph: session lost,haunting for new mon
> 
> So is this any indication that this issue might cause cephFs mount issue ?

yes.
Network instability causes one command to hang, the request is retried but will not go through until the previous request errors out. The operation already exists error starts popping on the retried requests.

**Comment by akash123-eng** [comment]
ok @Rakshith-R 
is there any to prevent it ?

**Comment by Rakshith-R** [comment]
@akash123-eng 

There is an option to recover_session for cephfs kernel mounter.
I haven't tested it anytime but it may help.

https://docs.ceph.com/en/quincy/man/8/mount.ceph/#basic

you can add it here https://github.com/rook/rook/blob/4817a0442cbe96dee0d60b52acd06b1fae204ff2/Documentation/CRDs/Cluster/ceph-cluster-crd.md#csi-driver-options

**Comment by Madhu-1** [comment]
>In general, this option should not be used by most clients that have stable connections to the MDS's, but in environments where connectivity may be spotty, and availability is more important than correctness, admins may want to consider enabling it.

From https://ceph.io/en/news/blog/2020/automatic-cephfs-recovery-after-blacklisting/

**Comment by akash123-eng** [comment]
@Madhu-1  @Rakshith-R  this is happening on the node again and again and we don't see that node in osd blocklist ls.
sometimes it doesn't get fixed even after restarting cephfs plugin pod of that node and we have to reboot the node to fix the issue.
will recover_session = clean option in Ceph csi driver fix this issue from recurring it again ? and also will it have any negative effect on clients ?

**Comment by Madhu-1** [comment]
> **s** output but when we checked the client ip it was of a rook-ceph-mgr pod which was on different node and not node on which we were facing the issue.

Please check my above comment for `recover_session` flag and if you think IP is not blocklisted and you are facing the issue gain, please provided all the required logs for debugging.


>An operation with given volume ID 00- already exists

As per the issue description, i see you have an operation already exists error and I don't think this error is related to the IP blocklisting, you will get a permission denied error if the IP is blocklisted.

If you have different issue , please open different github issue lets not try to solve everything in this one.

**Comment by akash123-eng** [comment]
@Madhu-1  for permission denied error will raise different github issue but for this mount issue we are frequently facing this and cephfs plugin print only below errors for different volumes in logs nothing else :

An operation with given volume ID 00- already exists


and as mentioned it gets fixed after restarting cephfs plugin pod for that node but sometimes we have to reboot the node to fix the issue

**Comment by Madhu-1** [comment]
> @Madhu-1 for permission denied error will raise different github issue but for this mount issue we are frequently facing this and cephfs plugin print only below errors for different volumes in logs nothing else :
> 
> An operation with given volume ID 00- already exists
> 
> and as mentioned it gets fixed after restarting cephfs plugin pod for that node but sometimes we have to reboot the node to fix the issue

that is completely a workaround, we need to look at the logs and the ceph cluster details on why its happening.

**Comment by akash123-eng** [comment]
@Madhu-1  In ceph cluster status there are no warnings, all OSDs are up, all PGs are in active + clean state
which logs do you need ?

**Comment by Madhu-1** [comment]
please provide cephfs plugin logs from the node where you have the problem, make sure you set `CSI_LOG_LEVEL` to `5` ad CSI_SIDECAR_LOG_LEVEL` to `5` as well

**Comment by akash123-eng** [comment]
@Madhu-1 we are now frequently seeing this issue for other nodes 
When we exec into cephfs plugin pod it has unmount process running hung for many PVCs what could be the permanent fix for this issue ?
Can you please help us as it's critical now

**Comment by microyahoo** [comment]
you can use `strace` to track why the running process hangs

**Comment by akash123-eng** [comment]
@Rakshith-R @Madhu-1 please help to how to fix this issue

**Comment by akash123-eng** [comment]
@Madhu-1 @Rakshith-R can you please help on above issue?

**Comment by Rakshith-R** [comment]
> please provide cephfs plugin logs from the node where you have the problem, make sure you set `CSI_LOG_LEVEL` to `5` ad CSI_SIDECAR_LOG_LEVEL`to`5` as well

This isn't provided yet. Provide ceph cluster status as well.

I think the network connection between nodes and ceph cluster has degraded leading to this issue.
You'll need to verify network is stable before pointing to anything ceph related.

**Comment by akash123-eng** [comment]
In ceph status we don't see anything all osds are up,all pgs are active+clean @Rakshith-R
