### ISSUE TITLE
Document host networking in external cluster

### ISSUE THREAD

**Issue by RomLecat** [rook/rook#13796]
Hi,

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Host networking stays disabled on CephCluster resources with network.provider=host.

**Expected behavior:**
Host networking should be capable of being enabled even for external clusters.

**How to reproduce it (minimal and precise):**
I have an external Ceph cluster (on Proxmox) using IPv6 in a dedicated network. It was created using Helm (values below) with ArgoCD.
My worker k8s nodes have a NIC in that network (also with an IPv6). I want to use host networking.

**File(s) to submit**:

* values-external.yaml
```yaml
cephClusterSpec:
  external:
    enable: true
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  network:
    connections:
      provider: host

cephBlockPools: {}
cephFileSystems: {}
cephObjectStores: {}
```

* Resulting CephCluster resource (pushed by ArgoCD)
```
Name:         rook-ceph-external
Namespace:    rook-ceph-external
Labels:       argocd.argoproj.io/instance=lct1-rook-cluster
Annotations:  <none>
API Version:  ceph.rook.io/v1
Kind:         CephCluster
Metadata:
  Creation Timestamp:  2024-02-20T15:39:41Z
  Finalizers:
    cephcluster.ceph.rook.io
  Generation:        3
  Resource Version:  373617951
  UID:               6a0b1cb9-d1e1-44aa-afa4-d14498fc634b
Spec:
  Ceph Version:
    Allow Unsupported:  false
    Image:              quay.io/ceph/ceph:v18.2.1
  Cleanup Policy:
    Allow Uninstall With Volumes:  false
    Confirmation:
    Sanitize Disks:
      Data Source:                                    zero
      Iteration:                                      1
      Method:                                         quick
  Continue Upgrade After Checks Even If Not Healthy:  false
  Crash Collector:
    Disable:  true
  Csi:
    Cephfs:
    Read Affinity:
      Enabled:  false
  Dashboard:
    Enabled:           true
    Ssl:               true
  Data Dir Host Path:  /var/lib/rook
  Disruption Management:
    Manage Pod Budgets:       true
    Osd Maintenance Timeout:  30
    Pg Health Check Timeout:  0
  External:
    Enable:  true
  Health Check:
    Daemon Health:
      Mon:
        Disabled:  false
        Interval:  45s
      Osd:
        Disabled:  false
        Interval:  60s
      Status:
        Disabled:  false
        Interval:  60s
    Liveness Probe:
      Mgr:
        Disabled:  false
      Mon:
        Disabled:  false
      Osd:
        Disabled:  false
  Log Collector:
    Enabled:       true
    Max Log Size:  500M
    Periodicity:   daily
  Mgr:
    Allow Multiple Per Node:  false
    Count:                    2
    Modules:
      Enabled:  true
      Name:     pg_autoscaler
  Mon:
    Allow Multiple Per Node:  false
    Count:                    3
  Monitoring:
    Enabled:  false
  Network:
    Connections:
      Compression:
        Enabled:  false
      Encryption:
        Enabled:     false
      requireMsgr2:  false
    Multi Cluster Service:
  Priority Class Names:
    Mgr:                                   system-cluster-critical
    Mon:                                   system-node-critical
    Osd:                                   system-node-critical
  Remove OS Ds If Out And Safe To Remove:  false
  Resources:
    Cleanup:
      Limits:
        Memory:  1Gi
      Requests:
        Cpu:     500m
        Memory:  100Mi
    Crashcollector:
      Limits:
        Memory:  60Mi
      Requests:
        Cpu:     100m
        Memory:  60Mi
    Exporter:
      Limits:
        Memory:  128Mi
      Requests:
        Cpu:     50m
        Memory:  50Mi
    Logcollector:
      Limits:
        Memory:  1Gi
      Requests:
        Cpu:     100m
        Memory:  100Mi
    Mgr:
      Limits:
        Memory:  1Gi
      Requests:
        Cpu:     500m
        Memory:  512Mi
    Mgr - Sidecar:
      Limits:
        Memory:  100Mi
      Requests:
        Cpu:     100m
        Memory:  40Mi
    Mon:
      Limits:
        Memory:  2Gi
      Requests:
        Cpu:     1000m
        Memory:  1Gi
    Osd:
      Limits:
        Memory:  4Gi
      Requests:
        Cpu:     1000m
        Memory:  4Gi
    Prepareosd:
      Requests:
        Cpu:     500m
        Memory:  50Mi
  Security:
    Key Rotation:
      Enabled:  false
    Kms:
  Skip Upgrade Checks:  false
  Storage:
    Flapping Restart Interval Hours:  0
    Store:
    Use All Devices:                        true
    Use All Nodes:                          true
  Wait Timeout For Healthy OSD In Minutes:  10
Status:
  Conditions:
    Last Heartbeat Time:   2024-02-20T15:40:14Z
    Last Transition Time:  2024-02-20T15:40:14Z
    Message:               Attempting to connect to an external Ceph cluster
    Reason:                ClusterConnecting
    Status:                True
    Type:                  Connecting
  Message:                 Attempting to connect to an external Ceph cluster
  Phase:                   Connecting
  State:                   Connecting
Events:
  Type     Reason           Age   From                          Message
  ----     ------           ----  ----                          -------
  Warning  ReconcileFailed  20s   rook-ceph-cluster-controller  failed to reconcile CephCluster "rook-ceph-external/rook-ceph-external". failed to reconcile cluster "rook-ceph-external": failed to configure external ceph cluster: failed to detect and validate ceph version: failed to validate ceph version between external and local: failed to get ceph mon version: failed to run 'ceph version'. . timed out: exit status 1
```

The resulting CephCluster resource does not have network.connections.provider=host, even tho Helm renders it while templating. The value is still not set.

**Logs to submit**:

The CephCluster is unable to determine version, likely because it cannot talk to Ceph from the pods since there's no outgoing NAT.

```
Events:
  Type     Reason           Age   From                          Message
  ----     ------           ----  ----                          -------
  Warning  ReconcileFailed  20s   rook-ceph-cluster-controller  failed to reconcile CephCluster "rook-ceph-external/rook-ceph-external". failed to reconcile cluster "rook-ceph-external": failed to configure external ceph cluster: failed to detect and validate ceph version: failed to validate ceph version between external and local: failed to get ceph mon version: failed to run 'ceph version'. . timed out: exit status 1
```

Thanks

**Comment by travisn** [comment]
There is an indentation issue, the `provider` element belongs directly to the `network`, not the `connections`. Try this:
```yaml
  network:
    provider: host
```

**Comment by RomLecat** [comment]
Thanks, it did apply provider: host with this, but I still got a timeout.
I ended up enabling NAT on IPv6 and it now works properly.

**Comment by RomLecat** [comment]
It applied well, but it did not work (still got a timeout when the version check pod tried to issue "ceph version").

Yes I use an IPv6-only cluster. It was built on Proxmox and it's a non-routable /64 (in ULA) dedicated for Ceph.

**Comment by BlaineEXE** [comment]
I believe that the clue to the issue may be provided here:
> ... it's a non-routable /64 (in ULA) dedicated for Ceph.

If the network is non-routable, then Rook has no way of knowing how to reach the cluster, right?

**Comment by RomLecat** [comment]
The k8s nodes has a NIC in the Ceph network, so it cannot be reached from the pod network but can be from the host (this is why I wanted to enable host networking).

**Comment by BlaineEXE** [comment]
I see. Thanks for clarifying. 

It seems likely to me that the `rook-ceph-operator` pod isn't able to reach the cluster. It is on the pod network by default, and I'm not up to date on how the helm chart configures the operator pod with host networking (if at all).

In reality, I don't believe the CephCluster needs to have host networking enabled, but I believe the `rook-ceph-operator` pod does need `hostNetwork: true`.

**Comment by RomLecat** [comment]
I tried with ```useOperatorHostNetwork: true``` but unfortunately it does not work, the detect-version pod does not have ```hostNetwork: true``` and therefore cannot reach the cluster.

**Comment by BlaineEXE** [comment]
The detect version pod does not need to reach the cluster. It only needs to be able to query the version present in the Ceph image, which is not required for external clusters. The rook operator itself queries the external Ceph cluster's version, and so `useOperatorHostNetwork` must be enabled.

What versions of Rook and Ceph are you using? It seems like you didn't fill in that part of the issue template.

Network routing still may be an underlying issue as well. Once you set `useOperatorHostNetwork: true`, try using `ping` and `tracepath` to see if the Rook operator pod is able to reach Ceph monitors and other storage components.

**Comment by RomLecat** [comment]
I use Ceph 18.2.1 and Rook-ceph 1.13.5.

Sorry for the noise, I indeed made an error on my network configuration (I tested on a test cluster this time and forgot to add my worker node IP to the firewall of the Ceph interface). It now works fine with ```useOperatorHostNetwork: true```, thanks a lot !

**Comment by parth-gr** [comment]
> useOperatorHostNetwork

Thanks for the feedback, I think this a good area to document the external documents,

Can you share the output configurations if possible?
I will keep this issue open till it is in the docs.

**Comment by RomLecat** [comment]
Sure, my configuration is fairly simple:

values.yaml of rook-ceph:
```yaml
useOperatorHostNetwork: true
csi:
  readAffinity:
    enabled: true
```

values.yaml of rook-ceph-cluster:
```yaml
cephClusterSpec:
  external:
    enable: true
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s

cephBlockPools: {}
cephFileSystems: {}
cephObjectStores: {}
```

And I called the script like this:

```bash
python3 ./create-external-cluster-resources.py --rbd-data-pool-name k8s --cephfs-filesystem-name k8s --k8s-cluster-name k8s-test-cluster --restricted-auth-permission true --namespace rook-ceph-external --format bash --skip-monitoring-endpoint
```

Also I think there's a typo in the external cluster doc, here: https://rook.io/docs/rook/v1.12/CRDs/Cluster/external-cluster/#helm-installation
clusterNamespace should likely be "rook-ceph-external", not "rook-ceph", to match the script example above.

**Comment by Rage8327** [comment]
I do not believe this was ever done?
