### ISSUE TITLE
Use consistent logger instead of glog

### ISSUE THREAD

**Issue by travisn** [rook/rook#1380]
The provisioner packages in the operator write to the log with `glog` instead of the `logger` that is used elsewhere in rook. The `glog` logs go to the tmp folder inside the operator container so they are harder to track down and aren't collected by the `kubectl logs` command.

**Comment by kokhang** [comment]
This was introduced when @bassam moved the provisioner library to Rook in https://github.com/rook/rook/pull/1151.
