### ISSUE TITLE
Add support for Ceph Squid (v19)

### ISSUE THREAD

**Issue by travisn** [rook/rook#13804]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Rook v1.14 must add support for the Ceph Squid (v19) release. The timeline for both is in April. v1.14 is planned for early in the month and Squid will likely be later in the month. Rook can start testing with pre-release builds when available.

**What is use case behind this feature:**
Ceph releases must be supported by Rook.

**Comment by travisn** [comment]
The Squid RC is still not released. While we will plan on adding support for v19 as soon as it is released, let's not block the 1.14 release on it as it may take more time. We can officially add support in a v1.14.x since the timing didn't line up closely.

**Comment by BlaineEXE** [comment]
Still no Squid (v19) release or release candidate.

**Comment by travisn** [comment]
Support added with #14454. Tests/CI against v19.1.0 are looking good, so we will continue watching to confirm the tests pass with v19.2.0.
