### ISSUE TITLE
 cephfs: cannot proceed with mount recovery because NodeStageMountinfo record is missing  AND  globalmount: permission denied 

### ISSUE THREAD

**Issue by farhadkh000** [rook/rook#13818]
When the network is suddenly disconnected and then restored, the file mount becomes unavailable. used ceph and rook external for multi attach pvc in many pods, for r/w inside container logs  . but when disconnect network between cluster ceph and k8s cluster i get this error in new pods 
```
# k get all -n technical-app-podima-backend-p
NAME                                                  READY   STATUS                 RESTARTS       AGE
pod/podima-01-backend-dep-68dc55848-vf5lc             0/1     ContainerCreating      0              4s
pod/podima-01-backend-dep-7f5dfff645-6cww6            0/1     CreateContainerError   0 (101m ago)   6h58m
pod/podima-01-backend-dep-7f5dfff645-8xhx8            0/1     CreateContainerError   0 (101m ago)   6h58m
pod/podima-01-backend-dep-7f5dfff645-bvq5x            0/1     CreateContainerError   0 (100m ago)   6h58m
pod/podima-01-backend-filebeat-dep-6779484875-x7hdr   0/1     ContainerCreating      0  
```
```
MountVolume.SetUp failed for volume "pvc-d63621a3-d917-48fd-8c3b-aff65912f24a" : rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/e38d77457ceb9e39d5e79fc6633e88ddef8e2d1e40cc74a3b34595e06e4bf8ea/globalmount: permission denied

```
in side of ceph cluster i don't have any connection for client but in worker i have mount point for old pods with ceph machine
```
worker# df -h | grep pvc-d63621a3-d917-48fd-8c3b-aff65912f24a
10.20.32.164:6789,10.20.32.165:6789,10.20.32.163:6789:/volumes/csi/csi-vol-d0b4a5b8-5d72-46c9-b2ee-f96b89e094e0/8c83aea7-7c31-40e3-8820-9ea23767b503  122G  356M  122G   1% /var/lib/kubelet/pods/87d359da-b36b-403a-ad6c-b173e2aafdf5/volumes/kubernetes.io~csi/pvc-d63621a3-d917-48fd-8c3b-aff65912f24a/mount
```
i trying solved this problem with remove mount point in worker for old pods but this isn't a good way

**Expected behavior:**
I expect that in this situation csi or any component that is responsible for the installation path or connection between ceph and k8s workers will do this automatically.
**How to reproduce it (minimal and precise):**
   1. you need a k8s cluster and ceph cluster sepratly 
   2. used rook-external for storage provisioner 
   3. create a deployment with pvc and used cephfs storage class  
   4. Shut down the network or disconnect network beetwen clusters ( for simolation of network disaster ) 
   5. recover the network 
   6. See error 

i check many component in rook or k8s and i found this log in csi-cephfs-plogins even when i remove pvc and recreate new pvc for pods i see this log for old pvc released .

```
1 fuserecovery.go:137] ID: 878488 Req-ID: 0001-0012-rook-ceph-external-0000000000000002-d0b4a5b8-5d72-46c9-b2ee-f96b89e094e0 cephfs: mount problem detected when publishing a volume: /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/e38d77457ceb9e39d5e79fc6633e88ddef8e2d1e40cc74a3b34595e06e4bf8ea/globalmount is CORRUPTED, /var/lib/kubelet/pods/90f4c329-dc52-4e8e-ae13-1eb2f584206a/volumes/kubernetes.io~csi/pvc-d63621a3-d917-48fd-8c3b-aff65912f24a/mount is NOT_MOUNTED; attempting recovery
W0223 07:58:56.064890       1 fuserecovery.go:147] ID: 878488 Req-ID: 0001-0012-rook-ceph-external-0000000000000002-d0b4a5b8-5d72-46c9-b2ee-f96b89e094e0 cephfs: cannot proceed with mount recovery because NodeStageMountinfo record is missing
E0223 07:58:56.064905       1 nodeserver.go:476] ID: 878488 Req-ID: 0001-0012-rook-ceph-external-0000000000000002-d0b4a5b8-5d72-46c9-b2ee-f96b89e094e0 stat failed: stat /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/e38d77457ceb9e39d5e79fc6633e88ddef8e2d1e40cc74a3b34595e06e4bf8ea/globalmount: permission denied
```
and i see this log with `journalctl -xf` ,It is clear that it is still looking for mounting the path and priveios pvc(pvc-764eab41-2f85-4c21-b6a4-eff2f53723b3)  for the new pod(3243953c-0f1c-4575-a2da-25a09c1e137e )
 
```
Feb 26 11:07:51 opkbwfpsbpp0119 kubelet[332427]: E0226 11:07:51.358619  332427 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0012-rook-ceph-external-0000000000000002-b8c0e2da-d1c9-4d7d-a196-691773e00a43 podName: nodeName:}" failed. No retries permitted until 2024-02-26 11:09:53.358586805 +0000 UTC m=+6651626.117443534 (durationBeforeRetry 2m2s). Error: MountVolume.SetUp failed for volume "pvc-2f5d52a8-f0e3-435a-b429-03d62291c066" (UniqueName: "kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0012-rook-ceph-external-0000000000000002-b8c0e2da-d1c9-4d7d-a196-691773e00a43") pod "clasor-01-frontend-filebeat-dep-596cb7884f-zmd96" (UID: "3243953c-0f1c-4575-a2da-25a09c1e137e") : rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/da8c2c9c2e108aec837f8132653172c34115892f6bec6ddbb90d46e43fbbac6a/globalmount: permission denied
```
```
[root@opkbmfpsbpp0101 ~]# k -n technical-app-clasor-frontend-p get pods -o wide
NAME                                               READY   STATUS    RESTARTS   AGE    IP             NODE              NOMINATED NODE   READINESS GATES
clasor-01-frontend-dep-5dcbb96f55-5ppmb            1/1     Running   0          22d    10.156.3.155   opkbwfpsbpp0121   <none>           <none>
clasor-01-frontend-dep-5dcbb96f55-bg9jg            1/1     Running   0          22d    10.156.8.118   opkbwfpsbpp0119   <none>           <none>
clasor-01-frontend-dep-5dcbb96f55-jdnmf            1/1     Running   0          22d    10.156.3.31    opkbwfpsbpp0123   <none>           <none>
clasor-01-frontend-filebeat-dep-596cb7884f-zmd96   1/1     Running   0          3d4h   10.156.8.78    opkbwfpsbpp0119   <none>           <none>

[root@opkbmfpsbpp0101 ~]# k -n technical-app-clasor-frontend-p get pvc
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
clasor-01-frontend-log-pvc   Bound    pvc-764eab41-2f85-4c21-b6a4-eff2f53723b3   1Gi        RWX            cephfs-team-app   3d2h

[root@opkbmfpsbpp0101 ~]# k -n technical-app-clasor-frontend-p   get pod/clasor-01-frontend-filebeat-dep-596cb7884f-zmd96  -o jsonpath='{.metadata.uid}'
[root@opkbmfpsbpp0101 ~]# 3243953c-0f1c-4575-a2da-25a09c1e137e

```
**Environment**: `k8s`
* OS (e.g. from /etc/os-release):  
```
NAME="Oracle Linux Server"
VERSION="8.5"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"
ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.5 
```
* Kernel (e.g. `uname -a`): `5.4.17-2011.7.4.el8uek.x86_64 #2 SMP Fri Oct 2 14:39:04 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux `
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):` rook: v1.11.7
go: go1.19.9 `
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable) `
* Kubernetes version (use `kubectl version`): 
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"} 
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  `k8s cluster multi master `
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTH_OK`

**Comment by Rakshith-R** [comment]
@farhadkh000 , Yes that's expected, ceph cluster blocks the client due to inactivity. 
You need to reboot the node to fix this.

**Comment by farhadkh000** [comment]
> @farhadkh000 , Yes that's expected, ceph cluster blocks the client due to inactivity. You need to reboot the node to fix this.

Source text
​

Hi, in operational environments, this work is very risky and expensive,
Because my cluster is a multi-tenant environment, and if this happens and due to the number of services, the entire cluster must be reset, which causes the programs that do not use CephFS to be affected.
Is there no other solution?

**Comment by Rakshith-R** [comment]
> > @farhadkh000 , Yes that's expected, ceph cluster blocks the client due to inactivity. You need to reboot the node to fix this.
> 
> Hi, in operational environments, this work is very risky and expensive, Because my cluster is a multi-tenant environment, and if this happens and due to the number of services, the entire cluster must be reset, which causes the programs that do not use CephFS to be affected. Is there no other solution?

hey, You can also scale all the workloads using cephFS at the same time, wait for none of the pods using cephFS volumes are running and then scale them back up.

This will trigger a unmount and fresh mount of cephFS volumes.
The above procedure will not work even if a single pod using cephFS volume is still running while other are scaled down.
Only when all pods using a cephFS volume is scaled down, unmount from the node occurs.

**Comment by Madhu-1** [comment]
This is not a problem with cephcsi, if there a network disconnect for more than x minutes, we are getting error from ceph mount when we try to access, more details are captured at https://github.com/ceph/ceph-csi/issues/970

**Comment by farhadkh000** [comment]
> > > @farhadkh000 , Yes that's expected, ceph cluster blocks the client due to inactivity. You need to reboot the node to fix this.
> > 
> > 
> > Hi, in operational environments, this work is very risky and expensive, Because my cluster is a multi-tenant environment, and if this happens and due to the number of services, the entire cluster must be reset, which causes the programs that do not use CephFS to be affected. Is there no other solution?
> 
> hey, You can also scale all the workloads using cephFS at the same time, wait for none of the pods using cephFS volumes are running and then scale them back up.
> 
> This will trigger a unmount and fresh mount of cephFS volumes. The above procedure will not work even if a single pod using cephFS volume is still running while other are scaled down. Only when all pods using a cephFS volume is scaled down, unmount from the node occurs.


thanks , this is a better solution.

**Comment by akash123-eng** [comment]
@Rakshith-R @Madhu-1 
We are also facing same issue and node reboot only fixes the issue.
Is there any way to fix it permanently ?

**Comment by lastrix** [comment]
@Rakshith-R @Madhu-1 @akash123-eng
Also facing same issue
Got this in logs:
`
W1002 07:54:13.972976  851588 nodeserver.go:800] ID: 4 corrupted mount detected in "/var/lib/kubelet/pods/757737a8-4be4-4b93-b414-40b56095ee77/volumes/kubernetes.io~csi/pvc-db37c1fd-4d9c-41a1-9835-9a2bde0f1fce/mount": stat /var/lib/kubelet/pods/757737a8-4be4-4b93-b414-40b56095ee77/volumes/kubernetes.io~csi/pvc-db37c1fd-4d9c-41a1-9835-9a2bde0f1fce/mount: permission denied
`
After that only spam of messages:
`
I1002 07:56:08.557867  851588 utils.go:240] ID: 8 GRPC call: /csi.v1.Node/NodeGetVolumeStats
I1002 07:56:08.557960  851588 utils.go:241] ID: 8 GRPC request: {"volume_id":"0001-0024-30a2782f-b83c-4973-86ca-588a42426025-0000000000000004-aed78557-2559-40e2-a27c-4a6d0c5b715f","volume_path":"/var/lib/kubelet/pods/757737a8-4be4-4b93-b414-40b56095ee77/volumes/kubernetes.io~csi/pvc-db37c1fd-4d9c-41a1-9835-9a2bde0f1fce/mount"}
I1002 07:56:08.558050  851588 utils.go:247] ID: 8 GRPC response: {"volume_condition":{"abnormal":true,"message":"health-check has not responded for 114.585046 seconds"}}
`
I have found this "solution", but it looks icky: https://access.redhat.com/solutions/7004783
Restarting or scaling down is not what i really want to use. I hope for some better solution, like automatic remout or reconnect.

**Comment by microyahoo** [comment]
hi @lastrix, maybe you could try to set `mds_session_blocklist_on_timeout` to false from cephfs side. https://docs.ceph.com/en/quincy/cephfs/eviction/#advanced-configuring-blocklisting

> If you are experiencing frequent client evictions, due to slow client hosts or an unreliable network, and you cannot fix the underlying issue, then you may want to ask the MDS to be less strict.
> 
> It is possible to respond to slow clients by simply dropping their MDS sessions, but permit them to re-open sessions and permit them to continue talking to OSDs. To enable this mode, set `mds_session_blocklist_on_timeout` to false on your MDS nodes.
>
> For the equivalent behaviour on manual evictions, set `mds_session_blocklist_on_evict` to false.

**Comment by lastrix** [comment]
> hi @lastrix, maybe you could try to set `mds_session_blocklist_on_timeout` to false from cephfs side. https://docs.ceph.com/en/quincy/cephfs/eviction/#advanced-configuring-blocklisting
> 
> > If you are experiencing frequent client evictions, due to slow client hosts or an unreliable network, and you cannot fix the underlying issue, then you may want to ask the MDS to be less strict.
> > It is possible to respond to slow clients by simply dropping their MDS sessions, but permit them to re-open sessions and permit them to continue talking to OSDs. To enable this mode, set `mds_session_blocklist_on_timeout` to false on your MDS nodes.
> > For the equivalent behaviour on manual evictions, set `mds_session_blocklist_on_evict` to false.

Thanks, i'll try that. But my connection is virtual and client is multi-worker HA kubernetes cluster. I dunno how this may be unreliable. I think that this happens due to inactivity (holidays), during work week it work just fine. No issue occurs.
