### ISSUE TITLE
Mds on behind trimming causing cephFs mount issue for multiple nodes

### ISSUE THREAD

**Issue by akash123-eng** [rook/rook#13812]
Hi,

We were facing cephFs volume mount issue for multiple node and in the ceph status it was showing 

 mds slow requests
 Mds behind on trimming

We restarted cephfs plugin pods but it didn't fixed the issue.
After restarting mds pods it was resolved 
But wanted to know Root cause of this
Issue was started after 2 hours of one of the active mds crash
So does that active mds crash can cause this issue ?

**Environment**:
* OS (e.g. from /etc/os-release): centos 7.9
* Kernel version : 3.10
* Rook version (use `rook version` inside of a Rook Pod): 1.10.8
* Storage backend version (e.g. for ceph do `ceph -v`): 17.2.5
* Kubernetes version (use `kubectl version`): 1.26.8

**Comment by subhamkrai** [comment]
@akash123-eng Yes, mds crash has affects on cephfs volume mounts. CC @Rakshith-R

**Comment by akash123-eng** [comment]
@subhamkrai 
It's still happening every 3-4 weeks 

2 MDS reports slow requests 
2 MDS Behind on Trimming
mds.myfs-a(mds.1) : behind on trimming (6378/128) max_segments:128, num_segments: 6378
mds.myfs-c(mds.1):  behind on trimming (6560/128) max_segments:128, num_segments: 6560
to fix it, we have to restart all MDS pods one by one.
this is happening every 4-5 weeks.

We have seen many ceph issues related to it on ceph tracker and many people are suggesting to increase mds_cache_memory_limit
currently for our cluster mds_cache_memory_limit is set to default 4GB
mds_log_max_segments is set to default 128
Should we increase mds_cache_memory_limit to 8GB from default 4GB or is there any solution to fix this issue permanently?
