### ISSUE TITLE
Go client should call CoreV1() instead of Core()

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#1381]
While trying to debug an issue I'm having, I noticed that there are a couple of issues with the kubernetes go client that might impact the stability of Rook builds.

Firstly, the import for `k8s.io/client-go/kubernetes`, as noted by client-go's readme, will pull the unstable master version of the client.
https://github.com/rook/rook/blob/c93d4dadebc0dd27fe5199983342ec6b90a7fbaf/pkg/operator/agent/agent.go#L35

Secondly, the `clientset.Core()` method is deprecated and should be replaced with `clientset.CoreV1()` per https://github.com/kubernetes/client-go/blob/18ec62fe90328a54f7ab513d5fedf3e8650c98b5/kubernetes/clientset.go#L274
https://github.com/rook/rook/blob/c93d4dadebc0dd27fe5199983342ec6b90a7fbaf/pkg/operator/agent/agent.go#L221

Searching the Rook codebase to replace `clientset.Core()` with `clientset.CoreV1()` will be trivial, but I think there should be a larger conversation around the client-go versioning.

**Comment by travisn** [comment]
The go `dep` tool is expected to pull a particular version of the client-go package, which is found in the toml file. Does that satisfy your concern or is there another aspect I am missing?
https://github.com/rook/rook/blob/master/Gopkg.toml#L102

We definitely should be using CoreV1(), thanks for catching

**Comment by BlaineEXE** [comment]
Indeed it does! I didn't know about Toml. Thank you. I can make a patch for the `Core()` -> `CoreV1`, but it will be a little while, as I am still trying to figure out how to build containers and use those dev containers in my test env. Any tips would be appreciated.

**Comment by travisn** [comment]
You can see dev instructions [here](https://github.com/rook/rook/blob/master/INSTALL.md), and join our Rook slack group for any questions so we can help you get going!
