### ISSUE TITLE
RFE: options for OSD restart gate

### ISSUE THREAD

**Issue by anthonyeleven** [rook/rook#13811]
My understanding is that the operator gates OSD restarts via `ceph osd ok-to-stop`.  

I would like the option to change or augment this condition so that the operator will not proceed to restart the next OSD unless all PGs are `active+clean.*`

We recently adjusted our K8s `requests` and `limits`settings and experienced a subset of inactive PGs that impacted clients on an EC HDD pool.  My confidence in `ok-to-stop` has always been limited, but I don't have a smoking gun.

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
Ok, this would be even a more strict option for upgrades, such as `upgradeChecksRequireActiveCleanPGs`.
So you don't have evidence that `ok-to-stop` wasn't working, but it would help you gain more confidence in the upgrades with this extra level of assurance?

**Comment by anthonyeleven** [comment]
Exactly.

**Comment by mmaoyu** [comment]
I think this feature requires check cluster if the PGs status is clean before upgrade any osds.
Implementation steps are: 
1. Add a configuration  **UpgradeOSDRequireHealthyPGs** in crd cephcluster spec
2. Check ceph cluster whether the stataus is clean when SkipUpgradeChecks=false and UpgradeOSDRequireHealthyPGs=true in method updateExistingOSDs before pop osd query. If status is not clean or check failed return else continue upgrade logic. 

I'd like to take the issue😄
