### ISSUE TITLE
Suddenly unable to log in after upgrading to 1.13.4

### ISSUE THREAD

**Issue by ywd1988** [rook/rook#13829]
![J{3O0UL67%5T3HP JHQQEKE](https://github.com/rook/rook/assets/92080991/c0b93052-b134-4269-b63a-ceeda109b3a5)
![Y_6UJYY86A C$5AYUC9V}5H](https://github.com/rook/rook/assets/92080991/804c4a85-b366-4e97-a1dc-7b92bb6180c1)

**Comment by rkachach** [comment]
@ywd1988 can you provide mgr logs please?

**Comment by ywd1988** [comment]
> @ywd1988你能提供 mgr 日志吗？



> @ywd1988 can you provide mgr logs please?

![image](https://github.com/rook/rook/assets/92080991/2afe41ed-5454-4749-9590-2902f96b59b8)

**Comment by rkachach** [comment]
@ywd1988 was the issue solved on your side?

**Comment by ywd1988** [comment]
> @ywd1988 was the issue solved on your side?
Yes, the account is locked
