### ISSUE TITLE
csi: CSIDriverOptions are not filled when entry in csi cm is created with mon ips 

### ISSUE THREAD

**Issue by Rakshith-R** [rook/rook#13835]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
CSI configmap entry for cluster is created first with only mon ips, then CSIDriver options are added.

**Expected behavior:**

All CSI configmap entries should have CSIDriverOptions present from the time it is created.

**How to reproduce it (minimal and precise):**

- Create a new cephcluster with CSIDriverOptions e.g: readAffinity.enabled true or delete cm and operator pod on existing cluster. 
- watch the rook `rook-ceph-csi-config` cm

First the entry is created with just mon ip and then CSIDriverOptions is added.

Example:
```yaml
oc get cm rook-ceph-csi-config -oyaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"openshift-storage","monitors":["a:3300","b:3300","b:3300"],"namespace":"openshift-storage"},{"clusterID":"5bb69c306a7d011c3e91c3cec112fb7a","monitors":["a:3300","b:3300","b:3300"],"namespace":"openshift-storage","cephFS":{"subvolumeGroup":"csi","kernelMountOptions":"ms_mode=prefer-crc"}}]'
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-22T13:50:52Z"
  name: rook-ceph-csi-config
  namespace: openshift-storage
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: false
    controller: true
    kind: Deployment
    name: rook-ceph-operator
    uid: af2a4d1f-939d-4932-b116-c45f5f0b90c9
  resourceVersion: "722929"

```

Tasks to complete:

- [x] Make sure CSIDriverOptions is added in https://github.com/rook/rook/blob/ca5972dece9243901dc9dd139c6536c1db518472/pkg/operator/ceph/csi/cluster_config.go#L267 . This will fix the issue.
- [ ] Test and remove this function https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/cluster.go#L223 since it will be no longer required.

cc @travisn @Madhu-1 @iPraveenParihar 

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment]
@Rakshith-R what are the side effects of this for the new clusters,

I hope in the upgraded clusters it wont be a problem.
