### ISSUE TITLE
MountVolume.SetUp failed for volume | /var/lib/kubelet/volumeplugins/rook.io~rook/.rook.sock: connect: no such file or directory`

### ISSUE THREAD

**Issue by HBO2** [rook/rook#1383]
**Bug Report**
1. Kubernetes cluster created with 1 master and 2 nodes on CoreOs vm's. Created with Kubadm and followed all the instruction because CoreOs is rather specific, like the path of the volumePlugin. But it is working. in the sense of working Cephs block volumes.

What happened: Created successfully rook cluster, agent & operator. Checked with toolbox and every status is OK.
Next step is consuming the storage with the test mysql. The PVC & PV are created based on the mysql.yaml. But.. 
The container fails to start because of the following error:

`MountVolume.SetUp failed for volume "pvc-a61c227e-f404-11e7-a9d8-000d3a2cacb1" : mount command failed, status: Failure, reason: Rook: Error getting RPC client: error connecting to socket /var/lib/kubelet/volumeplugins/rook.io~rook/.rook.sock: dial unix /var/lib/kubelet/volumeplugins/rook.io~rook/.rook.sock: connect: no such file or directory`

What you expected to happen:
Because PVC and PV are OK , the container should mount the volume "pvc-a61c227e-f404-11e7-a9d8-000d3a2cacb1"

How to reproduce it (minimal and precise):

*ilar features already existing:

**Environment**:
* CoreOS
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: VM on Azure
* Rook version (use `rook version` inside of a Rook Pod): master/rook
* Kubernetes version (use `kubectl version`): 1.9.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kind of bare metal on Azure created with Kubadm
* Ceph status (use `ceph health` in the [Rook toolbox] "HEALTH_OK"
```
OVERALL STATUS: OK

USAGE:
TOTAL       USED        DATA      AVAILABLE
93.43 GiB   41.17 GiB   35 B      52.26 GiB

MONITORS:
NAME             ADDRESS                 IN QUORUM   STATUS
rook-ceph-mon2   10.99.190.29:6790/0     true        OK
rook-ceph-mon0   10.107.218.227:6790/0   true        OK
rook-ceph-mon1   10.109.189.2:6790/0     true        OK

MGRs:
NAME             STATUS
rook-ceph-mgr0   Active

OSDs:
TOTAL     UP        IN        FULL      NEAR FULL
2         2         2         false     false

PLACEMENT GROUPS (100 total):
STATE          COUNT
active+clean   100
```

ceph df:
```
GLOBAL:
    SIZE       AVAIL      RAW USED     %RAW USED 
    95670M     53514M       42156M         44.06 
POOLS:
    NAME     ID     USED     %USED     MAX AVAIL     OBJECTS 
    rbd      6        35         0        24365M           4
```

rados df:
```
POOL_NAME USED OBJECTS CLONES COPIES MISSING_ON_PRIMARY UNFOUND DEGRADED RD_OPS RD    WR_OPS WR   
rbd         35       4      0      8                  0       0        0     27 20480      5 3072 

total_objects    4
total_used       42156M
total_avail      53514M
total_space      95670M
```

**Comment by kokhang** [comment]
@HBO2 I think this is the same issue as https://github.com/rook/rook/issues/1330. There was a K8s 1.9.x change that broke the rook plugin auto discovery. To workaround this issue, you have to set the FLEXVOLUME_DIR _PATH env in the rook-operator.yaml. Here is an example: https://github.com/rook/rook/issues/1162#issuecomment-343743163.

**Comment by HBO2** [comment]
@kokhang Thx, for help. But, l did this already. Otherwise the agent and will not start. 

> Created with Kubadm and followed all the instruction because CoreOs is rather specific, like the path of the volumePlugin. But it is working. in the sense of working Cephs block volumes.

So, I also used the ENV trick to point to a writable dir.
The issue I have is the fact the MySql pod is not able to find the socket in the /var/lib/rook/..
dir.
I also found out after @galexrt asked me to show log of agent pod, I have an issue with "system:serviceaccount:default:rook-agent" see below:

`2018-01-07 21:02:06.481006 I | rook: starting Rook v0.6.0-136.gc93d4da with arguments '/usr/local/bin/rook agent'
2018-01-07 21:02:06.481064 I | rook: flag values: --help=false, --log-level=INFO
2018-01-07 21:02:06.482312 I | rook: starting rook agent
2018-01-07 21:02:06.492213 I | exec: Running command: modinfo -F parm rbd
2018-01-07 21:02:06.493494 I | exec: Running command: modprobe rbd single_major=Y
2018-01-07 21:02:07.620693 I | flexvolume: Rook Flexvolume configured
2018-01-07 21:02:07.620751 I | flexvolume: Deleting unix domain socket file.
2018-01-07 21:02:07.620877 I | flexvolume: Listening on unix socket for Kubernetes volume attach commands.
2018-01-07 21:02:07.622449 I | agent-cluster: start watching cluster resources
ERROR: logging before flag.Parse: E0107 21:02:07.624417       8 reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1alpha1.Cluster: clusters.rook.io is forbidden: User "system:serviceaccount:default:rook-agent" cannot list clusters.rook.io at the cluster scope
ERROR: logging before flag.Parse: E0108 20:51:45.751180       5 reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1alpha1.Cluster: clusters.rook.io is forbidden: User "system:serviceaccount:default:rook-agent" cannot list clusters.rook.io at the cluster scope`

Hope somebody can help me.

**Comment by HBO2** [comment]
HI everybody,
in order to give more context to the issue please find below the steps to recreate the error I stumbled on:

**Steps to reproduce:**

**1**. provision 3 CoreOS vm on any platform (Azure, Digital Ocean etc). I used 
Container Linux by CoreOS stable (1576.4.0)

**2.** Using Kubeadm to Create a Cluster (https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/) One master and 2 nodes. First install Kubeadm on every host by following the standard guideL (https://kubernetes.io/docs/setup/independent/install-kubeadm/)

**3.** After Kubeadm init --pod-network-cidr=10.244.0.0/16 
add flannel network with the kubectl create -f flanel.yaml (file from coreos)

**4.** Check with kubectl get nodes. You will see the master is ready, but only when flanel is installed. Otherwise Kubedns (3pods) are pending.

**5**. After installed Kubeadm on the nodes you simply use the join command to add the nodes. Check again with get nodes and in a minute you will see the nodes are ready.

**6.** I installed Kubernetes Dashboard with the regular file as mentioned on kubernetes.io

**7.** You will notice the dashboard is showing login screen because Kubeadm installs RABC by default. 

**8.** You can use the method described in https://github.com/kubernetes/dashboard/wiki/Access-control to skip the login screen and have all the option as an power user. -> (https://github.com/kubernetes/dashboard/wiki/Access-control#admin-privileges)

_Now we are heading to rook :-)_

**9.** Because using CoreOS and RABC we have to be very careful not missing a step. I used the instructions described in the Helm chart be prepared for RABC
Based on the template files of the Helm chart (https://github.com/rook/rook/tree/master/cluster/charts/rook/templates) created the following roles manual instead of using the Helm chart itself:
clusterrole-rook-operator.yaml 
clusterrolebinding-rook-operator.yaml

**10.** Next, and  super important, we have to add --volume-plugin-dir=/var/lib/kubelet/volumeplugins on every node!!. How?? 

  **10a**. Goto the node (ssh) and cd /etc/systemd/system/kubelet.service.d/ 
  **10b.** sudo vi 10-kubeadm.conf and add some values for Rook -> 
   `Environment="KUBELET_ROOK_SETTINGS=--volume-plugin-dir=/var/lib/kubelet/volumeplugins" 
     and use $KUBELET_ROOK_SETTINGS in ExecStart=/opt/bin/kubelet items.`
**don’t forget to use :**
```
sudo systemctl daemon-reload
sudo systemctl restart kubelet
```
Or even reboot the nodes.

   **10c**. Wait …. this will not work! At least not when you use Kubeadm 1.9.1. Don’t give up yet :-) because you can use a fix as mentioned by Alexander Trost in https://github.com/rook/rook/issues/1162#issuecomment-343743163
Simply add the ENV with the mentioned path and the operator and agent will start and the in the dataDirHostPath: /var/lib/rook you will see the files needed. 
In my case (I used default namespace for both operator and agent) also a folder named “default”. I am mentioning it because in this folder a socket file should be created.
**11.** Create a storage class with the replica pool
**12.** Follow the instruction for creating a mysql app
**13.** Great, PVC and PV are bound and rook cli (installed with toolbox) will show you everything is having Status OK.
**14.** PFFF,  :-(,   The mysql pod is complaining in an attempt to mount the PV. -> see above https://github.com/rook/rook/issues/1383
The following Error is displayed:
`MountVolume.SetUp failed for volume "pvc-a61c227e-f404-11e7-a9d8-000d3a2cacb1" : mount command failed, status: Failure, reason: Rook: Error getting RPC client: error connecting to socket /var/lib/kubelet/volumeplugins/rook.io~rook/.rook.sock: dial unix /var/lib/kubelet/volumeplugins/rook.io~rook/.rook.sock: connect: no such file or directory`

**15.** Alexander asked me to show him the log of the Agent pod and I discovered there is also something else going on: 

```
2018-01-07 21:02:06.481006 I | rook: starting Rook v0.6.0-136.gc93d4da with arguments '/usr/local/bin/rook agent'
2018-01-07 21:02:06.481064 I | rook: flag values: --help=false, --log-level=INFO
2018-01-07 21:02:06.482312 I | rook: starting rook agent
2018-01-07 21:02:06.492213 I | exec: Running command: modinfo -F parm rbd
2018-01-07 21:02:06.493494 I | exec: Running command: modprobe rbd single_major=Y
2018-01-07 21:02:07.620693 I | flexvolume: Rook Flexvolume configured
2018-01-07 21:02:07.620751 I | flexvolume: Deleting unix domain socket file.
2018-01-07 21:02:07.620877 I | flexvolume: Listening on unix socket for Kubernetes volume attach commands.
2018-01-07 21:02:07.622449 I | agent-cluster: start watching cluster resources
ERROR: logging before flag.Parse: E0107 21:02:07.624417       8 reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1alpha1.Cluster: clusters.rook.io is forbidden: User "system:serviceaccount:default:rook-agent" cannot list clusters.rook.io at the cluster scope
ERROR: logging before flag.Parse: E0108 20:51:45.751180       5 reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1alpha1.Cluster: clusters.rook.io is forbidden: User "system:serviceaccount:default:rook-agent" cannot list clusters.rook.io at the cluster scope
```

_Please note I was not able to understand and take action regarding_. ->

> Creating the Rook operator requires privileges for setting up RBAC. To launch the operator you need to have created your user certificate that is bound to ClusterRole cluster-admin.
> One simple way to achieve it is to assign your certificate with the system:masters group:
> -subj "/CN=admin/O=system:masters"
> system:masters is a special group that is bound to cluster-admin ClusterRole, but it can’t be easily revoked so be careful with taking that route in a production setting. Binding individual certificate to ClusterRole cluster-admin is revocable by deleting the ClusterRoleBinding.

Actually I don’;t know what to do :-(

**Comment by jbw976** [comment]
Nice writeup @HBO2 :)  The rook-agent RBAC issue does look of interest.
1. Is this causing the rook-agent pods to crash/restart?
1. does this file exist on the host's filesystem? `/var/lib/kubelet/volumeplugins/rook.io~rook/.rook.sock`
1. I notice that the rook-agent pod log indicates it's using the service account from the default namespace, which is unexpected to me.  Is the rook-agent pod running in the default namespace?   What does `kubectl get sa --all-namespaces` show?

**Comment by HBO2** [comment]
HI @jbw976 

1. NO!! I don't understand why everybody is asking because as noted at the start of the issue agents and operators are running like a baby :-). Otherwise it would be impossible to have the PV and PVC bound.
2. No, that's the problem I am trying to explain
3. Yes I decided to run all in the default namespace because why should i create 2 extra namespaces, like rook-system and rook.

oh,.. and BTW it's very confusing when creating the rook cluster that the name of the rook cluster must be the same as the namespace your creating in. But that's a side note :-)

**Comment by HBO2** [comment]
Hi @jbw976 @galexrt 
I have provisioned a new cluster like described above.
Now I used all the default setting as described on the website. (namespace: rook-system & rook)
I checked the pod agent logs and there are no errors:

both pod logs are showing this:
`2018-01-10 21:59:50.284949 I | rook: starting Rook v0.6.0-136.gc93d4da with arguments '/usr/local/bin/rook agent'
2018-01-10 21:59:50.285028 I | rook: flag values: --help=false, --log-level=INFO
2018-01-10 21:59:50.286356 I | rook: starting rook agent
2018-01-10 21:59:50.342083 I | exec: Running command: modinfo -F parm rbd
2018-01-10 21:59:50.371121 I | exec: Running command: modprobe rbd single_major=Y
2018-01-10 21:59:51.842148 I | flexvolume: Rook Flexvolume configured
2018-01-10 21:59:51.842404 I | flexvolume: Listening on unix socket for Kubernetes volume attach commands.
2018-01-10 21:59:51.844108 I | agent-cluster: start watching cluster resources`


Next I created a storage class with the replica pool is also defined , right?
And created the example mysql
The logs of the agents are the same, but the log of the operator is showing an error:
**see log:**
`2018-01-10 22:06:25.866633 I | op-osd: osd daemon set started
2018-01-10 22:06:25.866656 I | op-cluster: Done creating rook instance in namespace rook
2018-01-10 22:06:25.866670 I | op-pool: start watching pool resources in namespace rook
2018-01-10 22:06:25.866677 I | op-object: start watching object store resources in namespace rook
2018-01-10 22:06:25.866684 I | op-file: start watching filesystem resource in namespace rook
2018-01-10 22:13:14.050261 I | op-provisioner: creating volume with configuration {pool:rbd clusterName:default fstype:}
2018-01-10 22:13:14.050366 I | exec: Running command: rbd create rbd/pvc-73975fdf-f653-11e7-bf31-000d3a2cacb1 --size 1024 --cluster=default --conf=/var/lib/rook/default/default.config --keyring=/var/lib/rook/default/client.admin.keyring
E0110 22:13:14.128166       5 controller.go:801] Failed to provision volume for claim "default/mysql-pv-claim" with StorageClass "rook-block": Failed to create rook block image rbd/pvc-73975fdf-f653-11e7-bf31-000d3a2cacb1: failed to create image pvc-73975fdf-f653-11e7-bf31-000d3a2cacb1 in pool rbd of size 1073741824: Failed to complete : exit status 1. output: 
E0110 22:13:14.128669       5 goroutinemap.go:165] Operation for "provision-default/mysql-pv-claim[73975fdf-f653-11e7-bf31-000d3a2cacb1]" failed. No retries permitted until 2018-01-10 22:13:14.62865037 +0000 UTC m=+809.106575428 (durationBeforeRetry 500ms). Error: Failed to create rook block image rbd/pvc-73975fdf-f653-11e7-bf31-000d3a2cacb1: failed to create image pvc-73975fdf-f653-11e7-bf31-000d3a2cacb1 in pool rbd of size 1073741824: Failed to complete : exit status 1. output: 
2018-01-10 22:13:18.774070 I | op-provisioner: creating volume with configuration {pool:rbd clusterName:default fstype:}`

Then I checked with rook tools the status (see below) and noticed when doing "ceph df"
no pool with the name RBD is created (BTW; I renamed the replicapool to rbd instead of "replicapool"
**rookctl status**
`OVERALL STATUS: OK

USAGE:
TOTAL       USED        DATA      AVAILABLE
93.43 GiB   41.16 GiB   0 B       52.27 GiB

MONITORS:
NAME             ADDRESS                IN QUORUM   STATUS
rook-ceph-mon1   10.108.50.93:6790/0    true        OK
rook-ceph-mon0   10.111.15.191:6790/0   true        OK

MGRs:
NAME             STATUS
rook-ceph-mgr0   Active

OSDs:
TOTAL     UP        IN        FULL      NEAR FULL
2         2         2         false     false

PLACEMENT GROUPS (0 total):
STATE     COUNT
none
**root@rook-tools:/# ceph df**
GLOBAL:
    SIZE       AVAIL      RAW USED     %RAW USED 
    95670M     53524M       42146M         44.05 
POOLS:
    NAME     ID     USED     %USED     MAX AVAIL     OBJECTS 
**root@rook-tools:/# rados df**
POOL_NAME USED OBJECTS CLONES COPIES MISSING_ON_PRIMARY UNFOUND DEGRADED RD_OPS RD WR_OPS WR 

total_objects    0
total_used       42146M
total_avail      53524M
total_space      95670M`

So, no PV is created and the mysql pod cannot start because it timed out on not able to mount the volume:
<img width="984" alt="screen shot 2018-01-10 at 23 43 23" src="https://user-images.githubusercontent.com/7763328/34799440-1f4b3818-f660-11e7-8878-6781dfe05db7.png">

Hope you are able to have a better view what's going on and many thx for the effort done already!

**Comment by kokhang** [comment]
@HBO2 from `{pool:rbd clusterName:default fstype:}`, your cluster name is `default` but it should be `rook` since you are now deploying the cluster under the `rook` namespace. If this is the issue, we should have a more clear and concise error message.

**Comment by HBO2** [comment]
@kokhang Yes, a few minutes after I rote above comment, I noticed in the Kubernetes Dashboard the same and adapted the storageclass file. ...
And boem  ... everything was working!
So, issue can be closed.

**To summarise:**
1. Combination of CoreOS, Kubeadm and Kubernetes 1.9.1 makes it not possible to use the Helm method -> because you need the ENV with the path "--volume-plugin-dir"
2. When doing it without the chart, you better use the namespaces explained on the website and used in the examples
3. RABC is a challenge  because you need to create Service account ClusterRole and ClusterRoleBindig carefully. In my last attempt I even decided to use the PodSecurity guidelines because it's not how to find when you need them.
4. I also think there is an issue with the --volume-plugin-dir PATH on CoreOS. I used the second attempt an existing DIR: /etc/kubernetes/volumeplugin. Because I was sure this directory is known to the container (in CoreOS everthing is a container). Even when the replicaPoll was not created I cloud see the "/..rook.sock " files was created. With the other path, this file was never crerated. At least in my opnion. But I am not the expert :-)
5. Don't mess around with the name of the Rook cluster in combination with name used in the storageclass file (BTW: using the term cluster and setting the default name of the replicapool to replicappol is a bit confusing and when reading the log Because label name and real name is the same. It makes reading the log file a little less convenient. 

Many, many thanks for all the help. And it's great how the PV is dynamically created!!

**Comment by kokhang** [comment]
@HBO2 even though you got it to work, I'd still like to open up issues in order to improve the experience.

For 1, there is a bug https://github.com/rook/rook/issues/1330.
For 2, that seems to be a bug. Rook clusters should be able to deployed on any namespace. Could you file one?
For 3, feel free to submit an issue. Seems it is something we can also improve on.

For 4 and 5, I am not sure what the root cause were but feel free to file issues as well.

Thanks for your feedback

**Comment by maurya-m** [comment]
@kokhang , i am getting this error on my cluster setup on AWS, with 1 master , 3 nodes, check for the 

- name: FLEXVOLUME_DIR_PATH while creating the operator using the operator.yaml , no issues there.

but i am getting this similar error : 
![image](https://user-images.githubusercontent.com/46669717/53284020-25b71400-3774-11e9-8983-d5dca2e1b236.png)

Do i need to re-create the operator? what else can i check in this situation.

**Comment by maurya-m** [comment]
@kokhang , please ignore the above comment, i had to change the sc created of fs ext4 type!

**Comment by soromamadou** [comment]
I got the same issue.
To solve it, i have comment this line in "storageclass.yaml". 
fstype: xfs

like this rook is using ext4 and not xfs.

Hope it can help someone :)
