### ISSUE TITLE
Cluster rebalancing is not starting when node is out

### ISSUE THREAD

**Issue by Sunnatillo** [rook/rook#13853]
* Bug Report

**Deviation from expected behavior:**

After 6 min that the node is out, rook sets: 2024-01-23 11:55:49.631564 D` | ceph-cluster-controller: Health: "HEALTH_WARN", code: "OSD_FLAGS", message: "1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set"` ,
 this is expected
 Since we want the cluster to rebalance, we set remove the flag on the host as recommended in:
` ceph osd unset-group noout pool1-bm08ceph1-eph`
https://github.com/rook/rook/issues/11100 but the flag removal has no effect and the flag reappears after a couple of minutes, but after 30 min or so the flags are not present in the health status, but ceph is behaving as those flags would be set.
 The moment we take the osds out the cluster starts rebalancing normally, is this flags expected behaviour ?
we are using ceph ceph version 17.2.7 (b12291d110049b2f35e32e0de30d70e9a4c060d2) quincy (stable)
 and rook 1.11.11
 
**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):  rook 1.11.11
* Storage backend version: ceph version 17.2.7 (b12291d110049b2f35e32e0de30d70e9a4c060d2) quincy (stable)
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by sp98** [comment]
This is done by [Pod Disruption Budget implementation of the OSDs. ](https://github.com/rook/rook/blob/master/design/ceph/ceph-managed-disruptionbudgets.md#osds)

When a node is drained, the OSD goes down and PDBs are added to the other failure domains so that user cant drain more than one node from a different failure domains. 

When an node is drained, rook also delays it's DOWN/OUT process by placing a noout on that node. Rook removes that noout after the 30 minute timeout

**Comment by sp98** [comment]
@Sunnatillo [disabling](https://github.com/rook/rook/blob/7ca738e7b279196878d86d3d6a086693eaf1c238/deploy/examples/cluster.yaml#L274) the PDBs can be one of the options if you don't want the flag to be set.

**Comment by sp98** [comment]
@Sunnatillo Can you also share the operator logs after you have set `ceph osd unset-group noout pool1-bm08ceph1-eph`.  Thanks

**Comment by Sunnatillo** [comment]
/close
Thank you @sp98. It was indeed related to PDBs and our issue got solved.
