### ISSUE TITLE
Rook CSI plugin

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1385]
Rook needs to have a CSI plugin. Currently Rook uses a flexvolume plugin to integrate with Kubernetes. New storage features in Kubernetes are being added to support CSI based plugins and not to Flexvolume.

Using CSI will also solve some limitations we have been seeing with flexvolume. Such as https://github.com/rook/rook/issues/1330, https://github.com/rook/rook/issues/1128, https://github.com/rook/rook/issues/1282 and https://github.com/rook/rook/issues/1127.

**Comment by kokhang** [comment]
@rootfs perhaps we can start a design documentation and have it submitted to https://github.com/rook/rook/tree/master/design.

**Comment by kfox1111** [comment]
There is a project going on here too that may interest you: https://github.com/ceph/ceph-csi/

**Comment by BlaineEXE** [comment]
@rootfs Do you have some information you could provide here for me to get started looking into what kind of efforts it would require for us to help out with this?
