### ISSUE TITLE
Mons should never be placed on a node with another mon

### ISSUE THREAD

**Issue by travisn** [rook/rook#1386]
For mon stability, the operator needs to ensure that multiple mons are not placed on the same node. If you were to lose a node with multiple mons, the cluster would be lost if there are only three mons. 
- If the crd specifies more mons than the number of nodes, the operator will cap the number of mons at the number of nodes (or subtract one if there is an even number of nodes)
- If a mon fails and there are no nodes available for failover, the operator will leave that mon in quorum in hopes that it will eventually come back.

**Comment by galexrt** [comment]
@travisn and I had a talk about overall mon stability and those are all the points we found:
1. Maximum one mon per node:
    * Even more of a single point of failure when there is more than one mon on one node.
    * One should use more than three mons (5) to prevent failures in a production cluster (/ allow failure of more two mons before it gets critical).
        * Potentially the operator could reduce the quorum count for example from 5 to 3 and then scale up if that is possible.
2. Each node has an own unique (not changing) identity for a mon (an ID):
    * Prevents data pile up from mon failover due to changed mon IDs on each mon failover.
    * More stability due to the identity staying the same on each node and not having to catch up to all changes but only to the changes the last time since the mon was available.
3. MonCount influenced by node count:
    * When less than three nodes, only spawn one mon (no sense as two mons don't form a quroum).
    * When three or more nodes, spawn given monCount or three (default).
4. Mon failover:
    * Example: A three node K8s cluster. One node fails (with that the mon), no failover is done due to no increase in availability by placing two mons on one node. "Failed" mon from the node stays in quorum (as @travisn wrote) not "manually" removed.
    * When more than three nodes are available, a new mon is spawned with an existing ID for the node or a new ID for the mon (IDs are saved in the ConfigMap).
    * Data dir (and identity) stay the same per node!
    * If a mon should "always" fail during start, a check like for OSDs should be added that after X (15 tries?) failures and a "quorum" of at least two mons, would cause the removal/emptying of the mon dataDir and then restart of the mon.

**Comment by lorenz** [comment]
Just wanted to say that I'd really like if I could force the use of a specific node label (in my case `failure-domain.beta.kubernetes.io/zone`) to split the mons, since I have some sites which have more than one node but have very correlated failure modes. I wouldn't want multiple mons ending up on these since it will basically kill my cluster if two mons (I only have enough nodes for 3, not for 5) ended up in the same zone/failure domain and it went down.
