### ISSUE TITLE
[helm] Ceph documentation links are broken

### ISSUE THREAD

**Issue by Jean-Daniel** [rook/rook#13872]
**Is this a bug report or feature request?**
* Bug Report

In the `rook-ceph-cluster` helm chart values.yml file, there is a couple of links pointing to the ceph documentation to get details about some configuration parameters (like `enableRBDStats`), but there are using a wrong format pattern (using rook version and doc path) and point to non existing pages:

`https://docs.ceph.com/docs/v1.13.5/mgr/prometheus/#rbd-io-statistics` instead of `https://docs.ceph.com/en/reef/mgr/prometheus/#rbd-io-statistics` for instance.

**Comment by rkachach** [comment]
@Jean-Daniel I checked the `values.yaml` and current values are pointing to `master` (links are working correctly):

https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L442-L443

Where did you get the above `https://docs.ceph.com/docs/v1.13.5/mgr/prometheus/#rbd-io-statistics` value from?

**Comment by Jean-Daniel** [comment]
You right. This is probably the deployment script that try to replace master by the release version that alter the ceps links:

```
helm repo add rook https://charts.rook.io/release/

helm show values rook/rook-ceph-cluster | grep docs.ceph
>  # For reference: https://docs.ceph.com/docs/v1.13.5/mgr/prometheus/#rbd-io-statistics
        # https://docs.ceph.com/docs/v1.13.5/man/8/rbd/#kernel-rbd-krbd-options
        # https://docs.ceph.com/docs/v1.13.5/man/8/rbd-nbd/#options
        # https://docs.ceph.com/docs/v1.13.5/man/8/rbd/#kernel-rbd-krbd-options
        # https://docs.ceph.com/docs/v1.13.5/man/8/rbd-nbd/#options
#    # https://docs.ceph.com/docs/v1.13.5/man/8/rbd/#kernel-rbd-krbd-options
#    # https://docs.ceph.com/docs/v1.13.5/man/8/rbd-nbd/#options
#    # https://docs.ceph.com/docs/v1.13.5/man/8/rbd/#kernel-rbd-krbd-options
#    # https://docs.ceph.com/docs/v1.13.5/man/8/rbd-nbd/#options
```

**Comment by galexrt** [comment]
I found the source of the issue https://github.com/rook/rook/blob/master/build/makelib/helm.mk#L43 replaces any mentions of `master`, I'll open a PR to add quotes around the version to make sure `sed` is only targeting `"master"` instead of just the word `master` to replace it with the release version.
