### ISSUE TITLE
Mons should have one stable identity per node

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1387]
Each node has an own unique (not changing) identity for a mon (an ID):
* Prevents data pile up from mon failover due to changed mon IDs on each mon failover.
* More stability due to the identity staying the same on each node and not having to catch up to all changes but only to the changes the last time since the mon was available.

This is the second point which has been separated from #1386, see list in [comment](https://github.com/rook/rook/issues/1386#issuecomment-356119839).

**Comment by jpiper** [comment]
I don’t know if you have a plan for this, but for some other applications that I run on Kubernetes that require stable identity per node I inject spec.Node via the downward API and then use this for the node identity (or if a numeric ID is required, I usually use something derived from the IP address). Obviously you have to have your antiaffinity set up correctly for this to work!
