### ISSUE TITLE
rook-ceph provides storage type for external cluster applications?

### ISSUE THREAD

**Issue by zhangdeshuai1999** [rook/rook#13882]
I have already deployed rook-ceph in my local k8s cluster, now I have an idea, can I provide Rook-deployed ceph to my external vmware virtual machine? If you can ask what storage classes can be provided, how efficient? Are there any use methods and cases?

**Comment by rkachach** [comment]
@zhangdeshuai1999 sounds more like a discussion not a feature .. please, can you close this issue and move this to the discussions section?

**Comment by parth-gr** [comment]
@zhangdeshuai1999 you can try this out https://rook.io/docs/rook/latest-release/CRDs/Cluster/external-cluster/#exporting-rook-to-another-cluster
