### ISSUE TITLE
Improve Rook's Security Model

### ISSUE THREAD

**Issue by bassam** [rook/rook#1389]
Rook currently uses multiple namespaces and service accounts. The rook operator can create and delete namespaces, service accounts, roles and role bindings on the fly. As a result rook requires a *very* privileged service account (see [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-operator.yaml#L9)).

For production clusters this not going to work. We need to explore running in a mode where we do not have privileges to destroy the entire cluster. Also creating a deleting namespace is not necessarily something that every cluster-admin is going to want us to do.

If a cluster-admin wants to set policies (PSP, SCC, resource quotas, etc.) they need to be able to control which service accounts and namespaces Rook uses. Creating namespaces and service accounts on the fly means that these policies would need to be dynamically applied too.

This is a complicated issue but it's one that we should front load. Its come up in the following places #1314 #1337 #1348 #1211 and possible more. Also discussion on twitter here: https://twitter.com/the_sttts/status/945077544587616257

 I'm going to write a design doc and link it here when its ready.

**Comment by jpds** [comment]
Another one that would be beneficial is #1117.

**Comment by jbw976** [comment]
The design has been completed with https://github.com/rook/rook/blob/master/design/security-model.md.  The implementation is ongoing by @ichekrygin in #1471

**Comment by jbw976** [comment]
There is more work to do here to complete the design described in https://github.com/rook/rook/blob/master/design/security-model.md
