### ISSUE TITLE
Release new version including the AGENT_TOLERATION feature

### ISSUE THREAD

**Issue by christianhuening** [rook/rook#1390]
Rook 0.6.2 does not include the changes made to support the AGENT_TOLERATION ENV var (https://github.com/rook/rook/pull/1300). Sadly that is already "documented" in the example file for the rook-operator.yaml. So, could we create a new minor release to incorporate that feature? I am very dependent on it.

**Comment by jbw976** [comment]
Hi @christianhuening, just to clarify, you are saying that you do require the agent toleration functionality in Rook?

Is it possible at all for you to use `rook/rook:master` instead of one of the 0.6 releases? Thanks!

**Comment by christianhuening** [comment]
Hi @jbw976 , yes I require the agent toleration functionality, as I have 6 dedicated nodes I want to use for rook and for rook only. At the same time as I want to make sure that the rook-agents do run on these nodes (which have taints so as to not run anything else), I want to make sure rook-agent does *not* run on the master nodes. I therefore talked to @bassam yesterday and I agreed to make a PR to introduce a second ENV var which allows to specifiy a key for the tolerations, so that the agent toleration can be more specific. 

I hope to find time for the PR today or tomorrow.

**Comment by travisn** [comment]
this should not be an issue since we've released 0.7
