### ISSUE TITLE
Add a filter for docs check to detect 3rd person("you, they")

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13907]
In the docs we try not to use "you"

We can simply check this in the CI, so add a check to not use 3rd person
_Originally posted by @travisn in https://github.com/rook/rook/pull/13821#discussion_r1518267910_

**Comment by mmaoyu** [comment]
Hey,I'd like to take the issue😄.

I think the requirement is to write a workflow for filting **"you" or "they"** keyword in [Documentation](https://github.com/rook/rook/tree/master/Documentation)/ directory committed in the **added contents** 

/assign

**Comment by parth-gr** [comment]
> Hey,I'd like to take the issue😄.
> 
> I think the requirement is to write a workflow for filting **"you" or "they"** keyword in [Documentation](https://github.com/rook/rook/tree/master/Documentation)/ directory committed in the **added contents**
> 
> /assign

@mmaoyu thanks for taking it up!
Yes, we don't want our documents contain these words("you",etc), so add this check in the CI, to check it and complain if anyone has used that in the PR,
Maybe starting point to look around `[codespell]` CI and see if we can have our own dictionary, or any other logic is welcome!
