### ISSUE TITLE
Restructure the TOC in the docs

### ISSUE THREAD

**Issue by travisn** [rook/rook#1391]
The table of contents in the documentation does not flow naturally and still has artifacts related to standalone. 

- The link to "Using Rook on Tectonic Bare Metal" is the very first link in the page, which is out of place. We either need to restructure the TOC or include this content on the "Prerequisites" page.
- We really don't need a top-level "Rook" or "Kubernetes" node
- Flexvolume config is such a big issue we should make its own topic
- rookctl is deprecated

Here is a proposed structure:
- Quickstart
- Kubernetes Prerequisites
  - Flexvolume Configuration
  - Tectonic Bare Metal
- Storage
  - Block Storage
  - Object Storage
  - Shared File System
- CRDs
  - Pool
  - Cluster
  - Object Store
  - File System
- Monitoring
- Helm Chart
- Upgrades
- Tools
  - Toolbox
  - Rook Client
  - Advanced Configuration
  - Common Issues

**Comment by jbw976** [comment]
Do you know of a good way to test changes like this before it goes through the docs pipeline and gets published to the docs site?

**Comment by travisn** [comment]
I've pushed the changes for viewing here: https://ilovett.github.io/docs/rook/master/tools.html. Feedback?

**Comment by kokhang** [comment]
Im kinda not feeling it about having the title `CRDs`. Rook does use CRD (and TPR) for extending Kubernetes api but i feel that is just an implementation details. How about calling it Objects or Resources?
