### ISSUE TITLE
feat: Add the ability to specify image pull secrets for rook operator

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rook/rook#13915]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Allow me to use an image pull secret for the Rook operator deployment.

**What is use case behind this feature:**
Custom builds of Rook, but using the upstream helm chart.

**Comment by ADustyOldMuffin** [comment]
This is done via service accounts, and missed on a first pass. Apologies!

**Comment by travisn** [comment]
See also this topic: https://rook.io/docs/rook/latest/Getting-Started/Prerequisites/authenticated-registry/
