### ISSUE TITLE
OSD PDB is created when using an external cluster

### ISSUE THREAD

**Issue by mnaser** [rook/rook#13926]
When using Rook with an existing external cluster, it seems that it creates the OSD PDB regardless, which can cause the reconciler to just loop on this non-stop:

```
2024-03-13 18:03:02.328398 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2024-03-13 18:03:30.439382 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2024-03-13 18:03:33.242687 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
```

Because there are no OSD pods in the first place, however the code does not try and detect that...

https://github.com/rook/rook/blob/c409a6ae468bc9db6ad2eee1dd15e4dac9a7c03a/pkg/operator/ceph/disruption/clusterdisruption/reconcile.go#L177

I'm happy to help push a fix if we can get some guidance on how this can be solved.

**Comment by parth-gr** [comment]
@sp98 who starts the `clusterdisruption-controller`, I even cant see in the `AddToManagerFuncs` in the cr_manager list for controller runtime.https://github.com/rook/rook/blob/master/pkg/operator/ceph/cr_manager.go#L75

**Comment by parth-gr** [comment]
Thanks I saw it in the seprate function `AddToManagerFuncsMaintenance` https://github.com/rook/rook/blob/master/pkg/operator/ceph/cr_manager.go#L70 

Btw for this bug we should just add a check to the controller to skip reconcile if its is external cluster ,right?

**Comment by sp98** [comment]
@mnaser can you share the output of `ocs get pdb -n namespace` in your rook cluster ?

**Comment by travisn** [comment]
Or `kubectl get pdb -n namespace` :)
