### ISSUE TITLE
Remove PdbV1Beta1 support as k8s 1.25 doesnt support it

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13941]
**Is this a bug report or feature request?**
* Bug Report

The minimum version rook is supporting is k8s 1.25, and k8s 1.25 doesn't support it https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
So, there is no need to double-check in the code as all the versions can serve now on `policyv1`.

**Expected behavior:**

The fix would be removing this commit (https://github.com/rook/rook/pull/7977)77813f709353f73208cfab99c2ad7b99049f94db and testing it thoroughly on upgrades from 1.24 to 1.25.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
We've been using the v1 PDBs since K8s 1.21, so it will be quite low risk to make this change. If the CI passes, it should be fine. Thanks for cleaning it up!
