### ISSUE TITLE
not able to self heal

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#13957]
we have installed rook-ceph on kubernetes , every time k8s worker node reboots then rook-ceph myfs pod is not able to comeup, it went to crashloopbackoff, logs saying that key is not found.

but if restart the operator then it start and it will be running. operator need to self heal in this case ?

what all operator will self heal in the rook-ceph ? i would like make this clear for my production.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu
* Kernel (e.g. `uname -a`):  Linux master 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: vmware
* Rook version (use `rook version` inside of a Rook Pod): v1.11.11
* Storage backend version (e.g. for ceph do `ceph -v`): v1.17.6
* Kubernetes version (use `kubectl version`):v1.21.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): on premeses
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest- release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): ceph is healthy once restart the operator pod

**Comment by parth-gr** [comment]
can you share the complete logs  of rook operator the myfs pod
```
logs saying that key is not found.
```

**Comment by vadlakiran** [comment]
@parth-gr  as of now i don't have logs because i have restared the operator pod, i wanted to know that operator pod what and all it self heal ?
operator pod advantages is the self heal right, what perspective it will self heal in the rook-ceph pods ?

**Comment by parth-gr** [comment]
Yes it should self-heal, If you re-produces the same issue please cature the logs and share

**Comment by vadlakiran** [comment]
@parth-gr any document what all its self-heal ? i need specific details self heal ?

**Comment by travisn** [comment]
@vadlakiran There are many aspects of auto heal, for example:
- K8s will automatically restart failing pods, or move them to other nodes if possible
- [Mon health and failover](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/)
- [OSD health](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-osd-mgmt/)

When a single node goes down, it is not expected for any of the services to hang due to Ceph's resiliency.

Can you share the logs for the failing mds pod that showed the key error? We don't have enough details to troubleshoot.
