### ISSUE TITLE
support removing  unwanted(dead) cluster (secret) from mirroring peers.

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#13953]
> i forgot one case where we want to allow users to remove unwanted(dead) cluster mirroring peers.

Currently, if mirroring is disabled by the customer, then we remove all the peers on the pool (provided that the mirroring on the pool images is disabled). 

We don't have the automation to only remove specific/unwanted/dead peers as of now. But that looks like a valid use case and is not very difficult to implement. We can discuss more about this and maybe take it up in a future PR.

_Originally posted by @sp98 in https://github.com/rook/rook/issues/13905#issuecomment-2005968606_

**Comment by sp98** [comment]
What will be the criteria to remove the unwanted(dead) peers?  Can we simply match what is in the `spec.mirroring.secrets[]` list with the existing peers? That is, if a peer is available but its secret is not mentioned in the spec, we just delete that peer.  
@Madhu-1

**Comment by Madhu-1** [comment]
> What will be the criteria to remove the unwanted(dead) peers? Can we simply match what is in the `spec.mirroring.secrets[]` list with the existing peers? That is, if a peer is available but its secret is not mentioned in the spec, we just delete that peer. @Madhu-1

Yes, we can loop through all the peers from the `rbd mirror pool status` and remove the peers that are not present in the secrets.
