### ISSUE TITLE
use rook-1.13.6 and rook-1.13.7, It's any to deploy  one osd node to cluster 

### ISSUE THREAD

**Issue by 47295743** [rook/rook#13967]
when I use rook-1.13.6 and rook-1.13.7 to deploy ceph ,it any to deploy  one osd node in ceph cluster 

 this is my config file for node
<img width="740" alt="微信图片_20240322195037" src="https://github.com/rook/rook/assets/45836944/d3e4a8f0-e3cd-47b8-8e37-987f6f13670c">

i have three kubenetes node
[root@node146 examples]# kubectl get node
NAME      STATUS   ROLES           AGE    VERSION
node146   Ready    control-plane   391d   v1.25.1
node147   Ready    <none>          391d   v1.24.10
node148   Ready    <none>          197d   v1.24.10

kubectl get pod -n rook-ceph
rook-ceph          csi-cephfsplugin-2wpvd                              2/2     Running     0               48m     192.168.3.147    node147   <none>           <none>
rook-ceph          csi-cephfsplugin-n2m8c                              2/2     Running     0               48m     192.168.3.146    node146   <none>           <none>
rook-ceph          csi-cephfsplugin-provisioner-748998c57-7plcx        5/5     Running     0               48m     10.244.62.182    node148   <none>           <none>
rook-ceph          csi-cephfsplugin-provisioner-748998c57-g2cdg        5/5     Running     0               48m     10.244.149.17    node146   <none>           <none>
rook-ceph          csi-cephfsplugin-vr995                              2/2     Running     0               48m     192.168.3.148    node148   <none>           <none>
rook-ceph          csi-rbdplugin-pfst4                                 2/2     Running     0               48m     192.168.3.146    node146   <none>           <none>
rook-ceph          csi-rbdplugin-provisioner-5f84dbfc5b-42wt9          5/5     Running     0               48m     10.244.149.16    node146   <none>           <none>
rook-ceph          csi-rbdplugin-provisioner-5f84dbfc5b-kl8vf          5/5     Running     0               48m     10.244.62.184    node148   <none>           <none>
rook-ceph          csi-rbdplugin-wtkqs                                 2/2     Running     0               48m     192.168.3.147    node147   <none>           <none>
rook-ceph          csi-rbdplugin-xg4c7                                 2/2     Running     0               48m     192.168.3.148    node148   <none>           <none>
rook-ceph          rook-ceph-crashcollector-node146-5d5f58fbfb-4f8h8   1/1     Running     0               44m     10.244.149.19    node146   <none>           <none>
rook-ceph          rook-ceph-crashcollector-node147-575db9496f-s8lhj   1/1     Running     0               3m36s   10.244.250.203   node147   <none>           <none>
rook-ceph          rook-ceph-crashcollector-node148-57c9f79bf6-rkwwl   1/1     Running     0               47m     10.244.62.173    node148   <none>           <none>
rook-ceph          rook-ceph-exporter-node146-595894f-lw47p            1/1     Running     0               44m     10.244.149.21    node146   <none>           <none>
rook-ceph          rook-ceph-exporter-node147-76c5475584-2dqvz         1/1     Running     0               3m36s   10.244.250.232   node147   <none>           <none>
rook-ceph          rook-ceph-exporter-node148-5d8c74858f-frq6f         1/1     Running     0               47m     10.244.62.175    node148   <none>           <none>
rook-ceph          rook-ceph-mgr-a-7fbf7f6c74-9457r                    3/3     Running     0               47m     10.244.62.181    node148   <none>           <none>
rook-ceph          rook-ceph-mgr-b-766f95f8dc-ktd2r                    3/3     Running     3 (8m28s ago)   47m     10.244.149.22    node146   <none>           <none>
rook-ceph          rook-ceph-mon-a-768cb79755-mp4lf                    2/2     Running     0               47m     10.244.62.186    node148   <none>           <none>
rook-ceph          rook-ceph-mon-b-65f6cc76-nhv9c                      2/2     Running     3 (8m33s ago)   19m     10.244.149.25    node146   <none>           <none>
rook-ceph          rook-ceph-mon-c-964dbd56b-5jx8z                     2/2     Running     0               3m37s   10.244.250.252   node147   <none>           <none>
rook-ceph          rook-ceph-operator-774458699-vs95k                  1/1     Running     0               52m     10.244.62.167    node148   <none>           <none>
rook-ceph          rook-ceph-osd-0-856cd9cf48-5bb9n                    2/2     Running     3 (9m47s ago)   44m     10.244.149.18    node146   <none>           <none>
rook-ceph          rook-ceph-osd-prepare-node147-99lb9                 0/1     Completed   0               90s     10.244.250.222   node147   <none>           <none>
tigera-operator    tigera-operator-959786749-kh4zx                     1/1     Running     13 (11m ago)    73d     192.168.3.148    node148   <none>           <none>

**Comment by 47295743** [comment]
it is ony one osd node in the cluster 
rook-ceph rook-ceph-osd-0-856cd9cf48-5bb9n 2/2 Running 3 (9m47s ago) 44m 10.244.149.18 node146

**Comment by travisn** [comment]
There is only a single OSD prepare pod. This means the operator is not attempting to create an OSD on the other nodes. Search the rook operator log to see why the nodes are skipped. 

If you get the cephcluster CR, does it show all your expected nodes? If the whitespace is incorrectly, they might not show up:
```
kubectl -n rook-ceph get cephcluster -o yaml
```

Also see the [OSD troubleshooting guide](https://rook.io/docs/rook/latest/Troubleshooting/ceph-common-issues/#osd-pods-are-not-created-on-my-devices).
