### ISSUE TITLE
Use --connect-timeout with mds liveness probe to run ceph cmds

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13962]
@BlaineEXE  @parth-gr   Have we forgotten the `--connect-timeout` when `ceph fs dump` .https://github.com/rook/rook/blob/master/pkg/operator/ceph/file/mds/livenessprobe.sh    When a mon pod is pending, the `ceph fs dump `will get stuck and cause the health check to time out and mds restart

_Originally posted by @hhstu in https://github.com/rook/rook/issues/12789#issuecomment-2005688627_

**Comment by hhstu** [comment]
I can do it
