### ISSUE TITLE
External document not loading as per the markdown

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13968]
here it 1,2,1
![Screenshot from 2024-03-22 16-49-17](https://github.com/rook/rook/assets/50455445/9e789b3f-550e-43d2-b8a6-e88c871532b2)
See here it is 1,2,3
![Screenshot from 2024-03-22 16-31-55](https://github.com/rook/rook/assets/50455445/1a8867b5-4543-4e72-9eba-78e693a50bf3)

@galexrt

**Comment by BlaineEXE** [comment]
The number 3 item is still not rendering properly.

**Comment by BlaineEXE** [comment]
Also, the `note` callout below the number 3 item also isn't rendering properly.

<img width="782" alt="image" src="https://github.com/rook/rook/assets/3989526/9e7ee56d-34c4-43ee-a920-2f20124c3d32">

**Comment by BlaineEXE** [comment]
I also just noticed that the `console` keyword got included in the code block itself :/
