### ISSUE TITLE
Add a watcher for topology storageclass to auto update rook op cm

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#13963]
**Is this a bug report or feature request?**
* Feature Request

Add a watcher for topology storageclass to auto update rook op cm, with the topology configurations.

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by parth-gr** [comment]
related to https://github.com/rook/rook/pull/13955

**Comment by travisn** [comment]
Can Rook just default to all the [topology labels](https://rook.io/docs/rook/latest/CRDs/Cluster/ceph-cluster-crd/#osd-topology) that we support? Then the user rarely if ever would need to set this, and we could tell them our default.

**Comment by parth-gr** [comment]
So basically configmap has 2 fields `CSI_ENABLE_TOPOLOGY` and `CSI_TOPOLOGY_DOMAIN_LABELS` which should be updated only if the topology sc is provided, lets discuss on if we can by default make them true

**Comment by travisn** [comment]
What if we set these defaults?
- `CSI_ENABLE_TOPOLOGY: false`
- `CSI_TOPOLOGY_DOMAIN_LABELS: "topology.kubernetes.io/zone"`

But that doesn't answer the question of how to automate this. This is really a CSI setting and does not make sense for Rook to own it. There is some discussion about how to refactor the CSI driver, so let's wait for that discussion to settle to see if it will also answer this question.
