### ISSUE TITLE
Invalid spec when trying to specify the application value in a CephBlockPool

### ISSUE THREAD

**Issue by francesco995** [rook/rook#13971]
**Is this a bug report or feature request?**
* Bug Report
Its not possible to create custom CephBlockPool objects with different application other than rbd

**Deviation from expected behavior:**
When i try to specify the application for a CephBlockPool, the resource is invalid to the k8s crd (the "application" field is unrecognised

**Expected behavior:**
https://github.com/rook/rook/blob/master/Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md#spec the k8s spec documentation includes an "application" field for the blockpool, and i see its also managed in the code.

is this a bug in the crd or in the documentation? how can i create a custom CephBlockPool to use in a cephfilesystem as a cache tier pool?

**Comment by francesco995** [comment]
nvm, i see now that is just not yet released

**Comment by travisn** [comment]
Correct, we are targeting this feature with the v1.14 release planned for later next week.

**Comment by francesco995** [comment]
> Correct, we are targeting this feature with the v1.14 release planned for later next week.

thanks
