### ISSUE TITLE
bluestore OSD does not reclaim the disk space

### ISSUE THREAD

**Issue by beatlejuse** [rook/rook#1397]
Is this a bug report or feature request?

* Bug Report
**Bug Report**

What happened:
after deleting data of ceph-fs, file ceph-osd is not reduced.
when the permanent record in the ceph-fs (monitoring and logging) is very quickly running out of disk space and the cluster falls down.

What you expected to happen:
run fstrim -a on the nodes of the cluster does not affect the free space on the disks.

**Environment**:
* OS (e.g. from /etc/os-release): CoreOS 1520.8.0
* Kernel (e.g. `uname -a`): Linux wd-test-m1 4.13.9-coreos #1 SMP Thu Oct 26 03:21:00 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz GenuineIntel GNU/Linux
* Cloud provider or hardware configuration: hardware  (vmware)
* Rook version (use `rook version` inside of a Rook Pod): v0.6.2
* Kubernetes version (use `kubectl version`): api v1.8.1 / kubectl v1.6.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): none
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
HEALTH_OK

**Comment by jpds** [comment]
*Maybe* related to http://tracker.ceph.com/issues/21243

**Comment by beatlejuse** [comment]
@jpds 
it's not like.
besides, any decision, I have not seen.
since ceph-fs is not able to release Unallocated space, I believe that I need some command that will do this.

**Comment by beatlejuse** [comment]
you have a real big problem.
file bluestore-block in osd in dataDirHostPath when writing data in ceph-fs only increases and never decreases when you delete the data.
this leads to an overflow of the disk and the fall of the cluster.
judging by the fact that the documentation does not describe how to reduce the size of the file you previously did not know about this problem.
though without a solution to this question can not be called a Rook system "production ready" because it has built into it a mechanism imminent destruction.
perhaps you have very large drives, so you haven't faced this problem.
suggest to test the system on small discs that can be fast enough to populate it with data.
also, from my experience, I noticed that Kubernetes drops when the disks are filled with more than 85%

**Comment by lorenz** [comment]
Dup of #1463

**Comment by jbw976** [comment]
@beatlejuse @lorenz so a bluestore OSD's local size never decreasing does not appear to be related only to CephFS, but rather a general bluestore issue?

**Comment by lorenz** [comment]
Yes, this is not restricted to CephFS. But this is (at least to me) expected behaviour since bluestore is designed for actual disks and not files. It behaves similarly to ext4 on a loopback device which will also never free data on the underlying file (unless you use discard/unmap).

**Comment by beatlejuse** [comment]
@jbw976  @lorenz  
Oh my God!
Why did you use this defective thing?
this made Ceph doomed to die.
one day the disk space will run out and the OS will die.
and there's no way to avoid that?
now I have to use a difficult and long process of backing up data from Ceph. then I re-create ceph cluster and restore the data. 
so I avoid running out of free disk space and the OS death.
it is just incredible!

**Comment by lorenz** [comment]
@beatlejuse Don't use the Bluestore backend on shared filesystems, use Filestore instead. Unless you really know what you are doing I wouldn't use a shared filesystem for Ceph either way. It is not really designed for that and its storage accounting logic might act up if you run into edge cases.

I have one cluster where can't use a separate block device and run Filestore but you can easily kill your whole cluster by just running out of not properly accounted storage on an OSD.
If you have rook directory on a shared filesystem, you can move it to a dedicated filesystem of the same size as the original disk and mount in /var/lib/rook. This can be done in a rolling update while keeping the whole cluster online.

**Comment by beatlejuse** [comment]
ok
