### ISSUE TITLE
Object stores with shared pools return error 500 when making a multipart upload

### ISSUE THREAD

**Issue by travisn** [rook/rook#13990]
When testing object stores with shared pools, @CalmVibes found an issue... Object stores with shared pools return error 500 when making a multipart upload. Without multipart upload - works fine. Object stores without shared pools in the same cluster works fine.

![image](https://github.com/rook/rook/assets/64099513/1177711f-2f3f-4d6f-9a77-1220aed46989)

Logs of RGW container:

```
debug 2024-03-28T07:52:44.764+0000 7f023c86e700  1 ====== starting new request req=0x7f0236f60730 =====
debug 2024-03-28T07:52:45.118+0000 7f029a92a700  0 WARNING: set_req_state_err err_no=95 resorting to 500
debug 2024-03-28T07:52:45.118+0000 7f029a92a700  1 ====== req done req=0x7f0236f60730 op status=-95 http_status=500 latency=0.354032069s ======
debug 2024-03-28T07:52:45.118+0000 7f029a92a700  1 beast: 0x7f0236f60730: 10.233.67.35 - ceph-objectstore-47-user [28/Mar/2024:07:52:44.764 +0000] "PUT /test/1g-test?partNumber=1&uploadId=2~-Ua-t3p8BAc8liJ25SfWvXEMwYBqZx1 HTTP/1.1" 500 15728911 - - - latency=0.354032069s
```

The situation is the same when using S3 Browser. I couldn’t check the download of large files because I can't upload them.

Let me know if I can provide any other useful data or it would be good to check some other usage scenarios.

Otherwise, I created 100 object stores with shared pools. Namespaces are isolated - a bucket with the same name is created in different object stores. With only 2 pools for all of them.

_Originally posted by @CalmVibes in https://github.com/rook/rook/issues/11411#issuecomment-2024690250_

**Comment by cbodley** [comment]
> @cbodley How might the multi-part uploads be affected by object stores sharing pools with different RADOS namespaces?

multipart uploads rely on omap to track the individual parts. omap is not supported by ec pools, so we use the seperate 'non-ec' data pool for this. make sure that a shared non-ec data pool is provided there

**Comment by travisn** [comment]
@CalmVibes If your data pool is replicated instead of EC do the multi-part uploads work?

@cbodley So instead of the data pool:
```json
"data_extra_pool": "rgw-data-pool:store-a.buckets.non-ec"
```
We should set the metadata pool for this property, correct?
```json
"data_extra_pool": "rgw-meta-pool:store-a.buckets.non-ec"
```

In my test cluster here is the full config:
```json
{
    "id": "eb7c7d83-3297-4414-b1a1-5c49dec772cf",
    "name": "store-a",
    "domain_root": "rgw-meta-pool:store-a.meta.root",
    "control_pool": "rgw-meta-pool:store-a.control",
    "gc_pool": "rgw-meta-pool:store-a.log.gc",
    "lc_pool": "rgw-meta-pool:store-a.log.lc",
    "log_pool": "rgw-meta-pool:store-a.log",
    "intent_log_pool": "rgw-meta-pool:store-a.log.intent",
    "usage_log_pool": "rgw-meta-pool:store-a.log.usage",
    "roles_pool": "rgw-meta-pool:store-a.meta.roles",
    "reshard_pool": "rgw-meta-pool:store-a.log.reshard",
    "user_keys_pool": "rgw-meta-pool:store-a.meta.users.keys",
    "user_email_pool": "rgw-meta-pool:store-a.meta.users.email",
    "user_swift_pool": "rgw-meta-pool:store-a.meta.users.swift",
    "user_uid_pool": "rgw-meta-pool:store-a.meta.users.uid",
    "otp_pool": "rgw-meta-pool:store-a.otp",
    "system_key": {
        "access_key": "",
        "secret_key": ""
    },
    "placement_pools": [
        {
            "key": "default-placement",
            "val": {
                "index_pool": "rgw-meta-pool:store-a.buckets.index",
                "storage_classes": {
                    "STANDARD": {
                        "data_pool": "rgw-data-pool:store-a.buckets.data"
                    }
                },
                "data_extra_pool": "rgw-data-pool:store-a.buckets.non-ec",
                "index_type": 0,
                "inline_data": true
            }
        }
    ],
    "realm_id": "8f770f9c-edcc-4c91-8c1d-b50b29c3a3df",
    "notif_pool": "rgw-meta-pool:store-a.log.notif"
}
```

**Comment by travisn** [comment]
Or is there a reason to use a second data pool instead of trying to re-use the metadata pool?

**Comment by cbodley** [comment]
> We should set the metadata pool for this property, correct?
> 
> ```json
> "data_extra_pool": "rgw-meta-pool:store-a.buckets.non-ec"
> ```

👍

**Comment by travisn** [comment]
@CalmVibes The fix is merged and in the latest `rook/ceph:master` image, please test it out in a new object store. An existing object store may not be updated with this fix.

**Comment by CalmVibes** [comment]
> @CalmVibes The fix is merged and in the latest `rook/ceph:master` image, please test it out in a new object store. An existing object store may not be updated with this fix.

Can I use erasureCoded rgw-data-pool as shared pool as written in https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/object-storage/#shared-pools?

**Comment by travisn** [comment]
> > @CalmVibes The fix is merged and in the latest `rook/ceph:master` image, please test it out in a new object store. An existing object store may not be updated with this fix.
> 
> Can I use erasureCoded rgw-data-pool as shared pool as written in https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/object-storage/#shared-pools?

Yes, with the fix now you can use an EC data pool.

**Comment by CalmVibes** [comment]
Now object stores with shared pools work fine with multipart upload. Thank you.
