### ISSUE TITLE
SVG: support optional parameters when creating subvolumegroup CR

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#14004]
>ceph fs subvolumegroup create <vol_name> <group_name> [--size <size_in_bytes>] [--pool_layout <data_pool_name>] [--uid <uid>] [--gid <gid>] [--mode <octal_mode>]

subvolumegroup supports optional parameters like size, pool_layout and mode etc, where user can choose what customization they want when creating subvolumegroup, This is supported in [ceph](https://docs.ceph.com/en/latest/cephfs/fs-volumes/#fs-subvolume-groups) but Rook is not exposing additional fields for it.

**Comment by travisn** [comment]
There are a lot of options to consider in that doc. Thoughts on the specific settings required in the SubvolumeGroup CRD? The obvious ones are the quota (size) and data pool name. Other settings seem more advanced or less common.

**Comment by Madhu-1** [comment]
@travisn Yes,for now am more interested in size and datapool, can we consider other parameters as required later.

**Comment by bauerjs1** [comment]
+1

Just came accross the same issue today, when I realized the subvolumegroups have the wrong pools assigned while browsing the Ceph dashboard. It would be brilliant to have quota and data pool options in the CRD!

(Rook requires setting a replicated default data pool but I'd like to use an additional EC pool instead – however, SVGs are always assigned the default pool)
