### ISSUE TITLE
Add support for cephfs + fscrypt in dev-env

### ISSUE THREAD

**Issue by NymanRobin** [rook/rook#14035]
Change the common.yaml to reflect recent changes in ceph-csi and allow for custom Minikube VM image.

The current clusterroles in common.yaml for cephfs-csi-nodeplugin and cephfs-external-provisioner-runner do not, out of the box, support reading secrets and/or configmaps. This does not allow for the development of CephFS + fscrypt without patching this after starting the environment.

The chart changes have been made in the ceph-csi repository [here](https://github.com/ceph/ceph-csi/pull/4504). So, I think this could be done here as well?

However, to use CephFS + fscrypt, it requires a 6.6+ kernel version, and this is not something that Minikube offers out of the box. Therefore, it would be nice to also allow the possibility of setting the iso_url in the Minikube start command through environment variables.

EDIT: Setting the minikube iso is possible through environment variable export MINIKUBE_ISO_URL="[URL/FILE}"

**Comment by NymanRobin** [comment]
Hey @parth-gr,

How does this sound and maybe a more general question if there is anyway standard how the common.yaml is kept in sync with the other repositories?

If this is something that sounds good, I could go ahead with the changes

**Comment by NymanRobin** [comment]
Maybe @travisn would have some input on this?

**Comment by parth-gr** [comment]
Yes @NymanRobin that would be a good idea.

You can also join rook huddle at 9pm IST to discuss them. 
https://meet.jit.si/rook-huddle

**Comment by iamniting** [comment]
@NymanRobin Are you planning to add the permissions here in the common.yaml or shall I pick it up?

**Comment by NymanRobin** [comment]
Sorry I have been busy with another "related" issue so forgot this one! Thanks for reminding me @iamniting, I will open a PR for this
/assign

**Comment by parth-gr** [comment]
@NymanRobin make sure to have a timeline plan for completion of this.

**Comment by NymanRobin** [comment]
I opened the PR now @parth-gr, let me know if it looks good!
For the minikube-iso I noticed it works simply by environment variable so no need to change anything,
