### ISSUE TITLE
connect to seph fs from another k8s cluster

### ISSUE THREAD

**Issue by beatlejuse** [rook/rook#1403]
How can i connect to my ceph-fs from another k8s cluster (both not in federation) ?

**Environment**:
* OS (e.g. from /etc/os-release): CoreOS 1520.8.0
* Kernel (e.g. `uname -a`): Linux wd-test-m1 4.13.9-coreos #1 SMP Thu Oct 26 03:21:00 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz GenuineIntel GNU/Linux
* Cloud provider or hardware configuration: hardware  (vmware)
* Rook version (use `rook version` inside of a Rook Pod): v0.6.2
* Kubernetes version (use `kubectl version`): api v1.8.1 / kubectl v1.6.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): none
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
HEALTH_OK

**Comment by galexrt** [comment]
There is already an issue open that covers this topic: https://github.com/rook/rook/issues/966.

**Comment by beatlejuse** [comment]
ie i need to connect by the IP addresses of the mons? and the ability to obtain a list of monitors (in case they change) from the API kubernetes does not exist?

**Comment by galexrt** [comment]
When using `hostNetwork: true`, the IPs of the mon nodes and the Ceph secret token taken from the cluster namespace can be used to connect to Ceph from another cluster (as long as firewalling, etc allows cluster to cluster communication).
For `hostNetwork: false` there is currently no well working way to connect to the in cluster Ceph from another cluster without in some way interconnecting them.

**Comment by beatlejuse** [comment]
i set "hostNetwork: true."
never saw visual changes.
how to check that the key is "hostNetwork: true" work?
And how now to connect to the file system? What i need to write in the deployment?

**Comment by galexrt** [comment]
`hostNetwork: true` can only be set when initially creating the cluster, changing it during runtime won't work and probably cause issues for the already running cluster.

When you have a cluster with `hostNetwork: true` you then use the current mon nodes IPs to connect to the FS, so you can't use the Rook flexvolume plugin inside the other K8s Cluster as the info isn't there.

**Comment by beatlejuse** [comment]
@galexrt  yes, i destroy my k8s claster and recreate it with new config.
do you have a sample config or a guide on how to mount the FS using the current mon nodes IPs?

**Comment by galexrt** [comment]
For CephFS, see https://kubernetes.io/docs/concepts/storage/volumes/#cephfs-
For RBD mounting see a guide like https://sysdig.com/blog/ceph-persistent-volume-for-kubernetes-or-openshift/ or https://crondev.com/kubernetes-persistent-storage-ceph/.
Where the mon IPs are the IPs of the nodes the mons run on, need to be kept uptodate for each PersistentVolume created.

**Comment by beatlejuse** [comment]
@galexrt how can i export mons port to nodes?

**Comment by galexrt** [comment]
@beatlejuse When using `hostNetwork: true`, the other cluster is required to have access to all your Rook storage nodes from your cluster with the Ceph components MONs, OSDs and MDS on them.
You use the Node IPs on which the MONs are currently running on to connect to them from the other cluster.

For more details checkout to mount CephFS in your other cluster checkout the links from my previous comment.
