### ISSUE TITLE
Restart object user reconcile if rgw objectstore is updated

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#14050]
If the endpoint is updated in the cephobjectstore, cephobjectuser secret should get updated.

I don't see predicate functions in `https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/user/` directory, so u may need to add that functionality first and add similar changes there .  So that `Endpoint` of cephobjectstore is updated then we can either delete the existing secret for cephobjecstoreuser and then recreate it with new endpoint info or update that secret.

For COSI part we can have log messages mentioning the objectstore endpoints updated, please update your `bucketclass` and `bucketaccessclass` accordingly if any `bucketclass` or `bucketaccessclass`  exists for that objectstore

_Originally posted by @thotz in https://github.com/rook/rook/issues/12328#issuecomment-2046614161_

**Comment by parth-gr** [comment]
@thotz do you think we need this change?

**Comment by thotz** [comment]
> @thotz do you think we need this change?

@parth-gr the original PR is dropped idea, so we can move this as well
