### ISSUE TITLE
RGW SSL certificates are not reloaded after renewal/update

### ISSUE THREAD

**Issue by briend** [rook/rook#14069]
Rook `CephObjectStore` CRD seems to have pretty good support for enabling SSL on the RGW pods by providing a `sslCertificateRef` to a `tls` Secret:

https://rook.io/docs/rook/v1.13/CRDs/Object-Storage/ceph-object-store-crd/#gateway-settings

We use Cert-Manager, which automatically renews these certs.  In our testing it seems to work fine until the certs expire. Restarting an rgw pod fixes it (it begins using the updated cert). The newer Beast rgw does not appear to have any option to reload the certs without a restart (even though the cert is updated inside the pod via the Secret).  Previously, civetweb rgw did have an option to handle short-lived ssl certs.

I've filed a ceph issue here: https://tracker.ceph.com/issues/65470

I'm wondering if Rook should be monitoring the certificate and automatically rolling the RGW deployment when changes occur on the Secret.  Another idea might be a Liveness Probe that checks the cert validity and then restarts the rgw (with a long random delay?)

Perhaps I'm missing something else and there is another solution already?

**Comment by BlaineEXE** [comment]
Let's see what the Ceph project plans to do with the issue there. It seems to me that the RGW itself should reload when the file changes without need to do anything special in Rook.

**Comment by parth-gr** [comment]
@thotz would ceph be planning for it?

**Comment by thotz** [comment]
Noting much progress on ceph issue

**Comment by RealityAnomaly** [comment]
Still an issue:

```
ts=2026-08-24T19:01:03.15414733Z caller=main.go:177 level=error err="Get \"https://rook-ceph-rgw-services.rook-ceph.svc/thanos/?location=\": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2026-08-24T19:00:53Z is after 2026-08-20T18:09:24Z\nBaseFetcher: iter bucket\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata\n\t/app/pkg/block/fetcher.go:587\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch.func2\n\t/app/pkg/block/fetcher.go:663\ngithub.com/golang/groupcache/singleflight.(*Group).Do\n\t/go/pkg/mod/github.com/golang/groupcache@v0.0.0-20241129210726-2c02b8208cf8/singleflight/singleflight.go:56\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/app/pkg/block/fetcher.go
```
