### ISSUE TITLE
Try to make import and export more eaiser

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#14077]
**Is this a bug report or feature request?**
* Feature Request

Currently user runs a Python script at the RHCS cluster to export the data and then manually copy-paste it from the RHCS terminal and then paste it to the Kubernetes terminal

What if it is possible to expose the data directly to a server endpoint and the k8s cluster can auto-fetch the details from there directly?

The possible design will be:

1) Run the Python script at the RHCS cluster 
   1.1) Python script will store/output data
   1.2) The Python script should expose the data to the server endpoint

2) The K8s cluster will watch for the event if the server as an update on data and will reconcile the Ceph controller 

But the important point to think about is, where the server will be running so both the RHCS and k8s cluster can access the endpoint, would be possible to get the data like any other ceph or radosgw-admin command?

ps: maybe we can just read the file with the JSON output from the ceph cluster node?

**Environment**:

**Comment by parth-gr** [comment]
Update, look for the mon metadata values and update it using the secret

**Comment by travisn** [comment]
> So the new design will look like.
> 
> Installation:
> 
> 1. Run the python script in the RHCS cluster as usual
>    -> It will update the ceph config/mon store with the JSON data
>    -> Secondly it will create the connection key which has the information about the ceph user and mon endpoints

I like this idea, it just requires a Ceph change to allow certain mon store data to be granted access for a specific keyring. 

> 2. User has to add the connection key to the cephcluster CR
>    -> Once the key is added it will create the specific resources based on the values of the ceph mon store

We don't want the key in the CR. Instead, the key should be directly stored in the `rook-ceph-mon` secret to the values `ceph-secret` and `ceph-username`.

> 3. Cluster will be connected

After Rook connects, it would need to load the JSON and apply it from Ceph and  to the consumer cluster, right?

> Updation:
> 
> 1. The user just have to run the Python script in the RHCS cluster it will auto-update the mon store and the resources

So Rook would need to check for changes to the mon store setting and apply any updates when the JSON changes?

**Comment by parth-gr** [comment]
>After Rook connects, it would need to load the JSON and apply it from Ceph and to the consumer cluster, right?

Yes, the cluster will watch for mon-config updates and will create the resources, somewhat like https://github.com/rook/rook/issues/14076

>So Rook would need to check for changes to the mon store setting and apply any updates when the JSON changes?

Exactly it would watch for the changes in it

**Comment by travisn** [comment]
Let's open a [Ceph tracker](https://tracker.ceph.com/) with the feature request, and just summarize the requirement there. We won't gain much in trying to design it here, since the Ceph team would own the design. The feature request is just to have some mon store settings that are only available depending on the keyring.

**Comment by parth-gr** [comment]
Added a ceph tracker https://tracker.ceph.com/issues/65583
