### ISSUE TITLE
initial installation failed:  imagepullbackoff for rook-ceph-mon  (0.6.2)

### ISSUE THREAD

**Issue by mvording** [rook/rook#1407]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

Installed rook following the instructions for the rook alpha helm chart,  created a cluster based on the example yaml, only changing the host path.    Various kubernetes rook components deployed succesfully, however the rook-ceph-mon pod did not, returning the following error message:

"Failed to pull image "rook/rook:latest": rpc error: code = Unknown desc = Error response from daemon: manifest for rook/rook:latest not found"

What you expected to happen:

The cluster to deploy the pod without errors.

**Environment**:
* OS (e.g. from /etc/os-release):  ubuntu 16.04 lts
* Kernel (e.g. `uname -a`): 4.4.0-104-generic
* Cloud provider or hardware configuration:    amd64 based server
* Rook version (use `rook version` inside of a Rook Pod):   0.6.2
* Kubernetes version (use `kubectl version`):  1.9.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  baremetal using kubeadm
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
n/a

`$ helm repo add rook-alpha https://charts.rook.io/alpha
"rook-alpha" has been added to your repositories

$ helm install rook-alpha/rook
NAME:   solemn-wasp
LAST DEPLOYED: Sun Jan 14 20:39:16 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ServiceAccount
NAME           SECRETS  AGE
rook-operator  1        1s

==> v1beta1/ClusterRole
NAME           AGE
rook-operator  1s

==> v1beta1/ClusterRoleBinding
NAME           AGE
rook-operator  1s

==> v1beta1/Deployment
NAME           DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
rook-operator  1        1        1           0          1s

NOTES:
The Rook Operator has been installed. Check its status by running:
  kubectl --namespace default get pods -l "name=rook-operator"

Visit https://rook.io/docs/rook/master for instructions on how
to create & configure Rook clusters
`

**Comment by bassam** [comment]
@mvording we don't publish a `latest` tag. Try setting the versionTag to `v0.6.2`

**Comment by r-moiseev** [comment]
Same error. Im using rook-alpha chart

**Comment by travisn** [comment]
@r-moiseev After you install the rook-alpha chart, you create the cluster as a separate step. Can you confirm what the value of the `versionTag` setting is in the rook-cluster.yaml? If it is not set, you will need to set it to `v0.6.2` to match the version of the helm chart.

**Comment by mvording** [comment]
I am not sure where to put the tag in the yaml,  also it looks like versionTag was removed a few days back, is this related?

https://github.com/rook/rook/search?utf8=%E2%9C%93&q=versionTag&type=

**Comment by jbw976** [comment]
Hi @mvording, since you are using the 0.6.x release, the rook cluster yaml of interest to you would be from the release-0.6 branch.  Take a look at how the `versionTag` field is used in that branch here: https://github.com/rook/rook/blob/release-0.6/cluster/examples/kubernetes/rook-cluster.yaml#L12

You are correct that in master and going forward that `versionTag` no longer exists.  It does exist in the 0.6.x releases, so it needs to be used there.

**Comment by r-moiseev** [comment]
I guess you need tto write about version tag in docs. Because there is example without it.

**Comment by travisn** [comment]
Hi @r-moiseev for 0.6.2 docs, please see https://rook.io/docs/rook/v0.6/cluster-crd.html where the `versionTag` is mentioned.

**Comment by jbw976** [comment]
The 0.6 docs mentioned by @travisn address this issue I believe.

**Comment by baptisteArnaud** [comment]
I have this problem when trying to deploy rook-celph in my cluster using helm chart :

The command I run:
`helm install --namespace rook-ceph rook-release/rook-ceph`

Pod status : ImagePullBackOff

> Normal   Pulling    10s (x3 over 48s)  kubelet, k8s-worker-02  Pulling image "rook/ceph:v1.0.2"
> Warning  Failed     9s (x3 over 47s)   kubelet, k8s-worker-02  Failed to pull image "rook/ceph:v1.0.2": rpc error: code = Unknown desc = no matching manifest for unknown in the manifest list entries
