### ISSUE TITLE
Creating a cluster never succeeds if CSI driver is disabled

### ISSUE THREAD

**Issue by travisn** [rook/rook#14123]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Creating an issue from the discussion on #14089...

The cephcluster reconcile continuously fails if the csi driver is disabled with this setting:
```
ROOK_CSI_DISABLE_DRIVER: "true"
```

The reconcile will continuously fail with this error in the operator log:

```
2024-04-23 21:12:09.518716 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/my-cluster". 
failed to reconcile cluster "my-cluster": failed to configure local ceph cluster: failed to create cluster: 
failed to start ceph monitors: failed to initialize ceph cluster info: failed to save mons: failed to update csi cluster config: 
waiting for CSI config map to be created: configmaps "rook-ceph-csi-config" not found
```

**Expected behavior:**
The reconcile should go ahead and create the configmap to allow the reconcile to continue even if the CSI driver is not yet created.

**How to reproduce it (minimal and precise):**

1. In operator.yaml, set ROOK_CSI_DISABLE_DRIVER: "true"
2. kubectl create -f crds.yaml -f common.yaml -f operator.yaml
3. kubectl create -f cluster-test.yaml

**Comment by travisn** [comment]
Per [this comment](https://github.com/rook/rook/pull/14089#issuecomment-2071588266), seems right for the CSI controller to re-order the implementation so it always ensures the CSI configmap is created as long as it finds a cephcluster CR. @BlaineEXE Any concerns with that?

**Comment by BlaineEXE** [comment]
I think that sounds like the right approach. Even if the CSI drivers are disabled, I don't think that means the reconcile needs to be disabled. And in this case, it can make sure Rook has what it needs to continue work.

----

In the longer-term view of things, I think it might be nice to find a way for Rook to operate without CSI controller being present at all. This would give us flexibility to have other controllers 'own' the CSI driver reconciliation.

I think we could do that by separating CSI config map into 2 categories: `csi-controller-writes:csi-reads` and `others-write:csi-reads`. During reconciliation, it makes sense for Rook to create/update the 'others-write:csi-reads` map, and Rook can freely create it if it doesn't exist. Then, if the CSI controller isn't running (and the `csi-controller-writes:csi-reads` configmap isn't present), Rook isn't stuck waiting forever for it to exist.
