### ISSUE TITLE
rook-ceph-cluster: Support Prometheus rules customization

### ISSUE THREAD

**Issue by gtirloni** [rook/rook#14140]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The rook-ceph-cluster chart could support creating extra Prometheus Rules allowing customization with better configuration locality (by avoiding the need to implement it in a separate chart or using some other mechanism). Additionally, if the rules from the imported mixin could be overriden, that would be helpful as well.

**What is use case behind this feature:**
Adding more rules for Ceph clusters or customizing aspects of the rules imported from mixins (e.g. severity).

**Environment**:
Prometheus deployed by prometheus-operator (from kube-prometheus-stack)

**Comment by travisn** [comment]
Have you tried using a tool such as Kustomize as suggested in the [customize alerts topic](https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-monitoring/#customize-alerts)? Customizing alerts has had a lot of discussion in the past, and further customization is just difficult to consider.
