### ISSUE TITLE
Doc Bug: links are not properly formatted

### ISSUE THREAD

**Issue by michcl** [rook/rook#14155]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
List of links to navigate the documentation are overlapping between them.
![image](https://github.com/rook/rook/assets/147844400/ff218d75-9034-4d7d-a17a-f32c77600fa1)

**Expected behavior:**
The list of links should be hided when collapsed.
![image](https://github.com/rook/rook/assets/147844400/591c171c-71f3-4910-a114-ffc834fe16fc)

**How to reproduce it (minimal and precise):**
I found that issue on those links:
- https://rook.io/docs/rook/v1.7/quickstart.html
- https://rook.io/docs/rook/v1.7/ceph-filesystem.html
- https://rook.io/docs/rook/v1.7/pre-reqs.html

Issue happens also on other doc versions, not just v1.7.
Tried on both Chrome 124.0.6367.91 and Edge 124.0.2478.67

**Comment by travisn** [comment]
Thanks for the report, looks like it affects all the docs v1.8 and older. The new style of docs since v1.9 are not affected.

**Comment by travisn** [comment]
The older docs are now fixed with the merge of https://github.com/rook/rook.github.io/pull/158, thanks!
