### ISSUE TITLE
ubuntu:zesty has been EOLed, image won't apt-update

### ISSUE THREAD

**Issue by dmick** [rook/rook#1417]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

make failed with 404s accessing archive.ubuntu.com during cross container build

What you expected to happen:

make to succeed

How to reproduce it (minimal and precise):
make

This can be worked around with, at least, OSBASE=ubuntu:artful make.  I don't know if xenial was avoided on purpose or not, and figured later had a better chance of success.  Either way, I guess images/image.mk should be updated.

**Comment by bassam** [comment]
we used zesty to for new gcc and tools (especially to support cross compiling). Now that we are no longer building ceph xenial is a better choice. I'll fix.
