### ISSUE TITLE
Rook Ceph Cluster helm chart toolbox image value broken by default

### ISSUE THREAD

**Issue by sammcgeown** [rook/rook#14180]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Deploying the helm chart with the supplied values.yaml fails for deployment rook-ceph-tools - spec.tamplate.spec.containers[0].image Required value

**Expected behavior:**
Supplied values.yaml deploys with valid default values.

**How to reproduce it (minimal and precise):**

Deploy the rook-ceph-cluster helm chart with the supplied values.yaml

**File(s) to submit**:
n/a 

**Logs to submit**:
n/a

**Cluster Status to submit**:
n/a

**Environment**:
* OS (e.g. from /etc/os-release): talos
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: raspberry pi
* Rook version (use `rook version` inside of a Rook Pod): 
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.30.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): talos 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
Do you have the `.Values.cephClusterSpec.cephVersion.image` set? The chart is supposed to default to that value.

**Comment by sammcgeown** [comment]
Yes I do - the issue is the values.yaml provided has an incorrectly commented value for the toobox image, I've submitted #14181 to fix that 👍

**Comment by travisn** [comment]
This is causing you an error during helm installation? I don't see an issue with it, or at least I cannot repro. Here is what I tried...

1. Installing the cluster chart succeeds when there are no values overridden
2. Installing the cluster chart succeeds when this is the only values override to enable the toolbox. It will have the default image name from the `cephClusterSpec`
```
toolbox:
  # -- Enable Ceph debugging pod deployment. See [toolbox](../Troubleshooting/ceph-toolbox.md)
  enabled: true
```
3. Installing the cluster chart succeeds when an image other than the default is set for the toolbox with these values:
```
toolbox:
  # -- Enable Ceph debugging pod deployment. See [toolbox](../Troubleshooting/ceph-toolbox.md)
  enabled: true
  image: quay.io/ceph/ceph:v18
```
