### ISSUE TITLE
Automatically decide type of MDS pod scaling 

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#14185]
**Is this a bug report or feature request?**
* Feature Request

If system is out of mds pod resources, 
There is a need to scale mds pod, either
1) Horizonatlly
2) Vertically

So goal for this feature to decide automatically the type of MDS pod scaling is required

**What should the feature do:**

Provide information of scaling using Prometheus metrics

**What is use case behind this feature:**

Help user in deciding the scaling type

**Environment**:

**Comment by travisn** [comment]
Either type of scaling should help in most scenarios. If we're going to automate this decision, we need clear scenarios of when one type is better than another. We don't have clear data on that, right?
