### ISSUE TITLE
Linting jobs are failing after pylint update

### ISSUE THREAD

**Issue by NymanRobin** [rook/rook#14203]
Pylint was recently updated this made the linting job fail.

The same pipeline for same PR without python changes was passing with pylint==3.1.1 while failing with pylint==3.2.0

Failure job: https://github.com/rook/rook/actions/runs/9083271523/job/24961611571?pr=14199
Succes job: https://github.com/rook/rook/actions/runs/9078600219/job/24945965769?pr=14199

The linting issues looks like they are quite quick to fix, however it could be considered to freeze the pylint version to avoid this failures in future

**Comment by travisn** [comment]
@NymanRobin Could you open a follow-up issue to fix the errors that were suppressed. Thanks!

**Comment by NymanRobin** [comment]
Sure @travisn, here is the follow-up issue #14212
I've proposed in the issue that a potential fix could involve dropping Python 2 support. Please comment if that's not possible.
