### ISSUE TITLE
Drop support for Kubernetes 1.6.x

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1421]
Rook officially maintains support for 1.6.x and a YMMV support for 1.5.x. I think it is time to drop support for both of them. Rook strives to run natively and to be deeply integrated on Kubernetes. Rook does this by leveraging the K8S extensibility via CRDs.

CRDs were introduced on 1.7. Prior to that, Rook relied on TPRs which has been deprecated and removed from Kubernetes.

Dropping support for K8S 1.6x will make the upgrade and support a lot smoother in the future. We dont have to worry about converting all our TPR objects into CRDs.

**Comment by travisn** [comment]
Didn't we document the steps for upgrading the TPRs? I didn't think it was complicated.

**Comment by kokhang** [comment]
@travisn i havent got through the docs to verify if its simple or complicated this but why have users bother with it? Also i dont think it is that simple. We currently have 5 type of CRDs. Cluster, ObjectStore, FileSystem, Pool and VolumeAttachment. The volumeattachment worries me since it will affect the mount path. So we gotta do this right. Also remember the whole camelCase issue we have with TPR vs CRD. So names will not match exactly.

**Comment by galexrt** [comment]
We need to keep OpenShift in mind, depending on which K8s version it is based on now. Still I think it is a good idea to remove support for 1.6 and lower.
Latest OpenShift `3.7` seems to be based on K8s version `1.7`.

**Comment by travisn** [comment]
The recommendation from the discussion this morning in the community meeting is to remove 1.6 support for the 0.8 release. The 0.7 release will continue to support 1.6 with TPRs. The features in the 0.8 release will be too difficult to support with TPRs.
