### ISSUE TITLE
rook-ceph-exporter usage i would like to know

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#14244]
i have deployed the latest version of rook-ceph i.e, v1.14.4 and ceph is v18.2.2 and kubernetes version is v1.28.6

i can see the exporter pods of respective worker node, what is the use of those pods and i to remove those pods in cluster.yaml.

kubectl get pods -n rook-ceph
NAME                                                READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-gzr8w                              2/2     Running     0          116s
csi-cephfsplugin-mlgjn                              2/2     Running     0          116s
csi-cephfsplugin-provisioner-76b7548bfb-kdgr6       5/5     Running     0          116s
csi-cephfsplugin-provisioner-76b7548bfb-p667z       5/5     Running     0          116s
csi-cephfsplugin-xhnwc                              2/2     Running     0          116s
csi-rbdplugin-8955t                                 2/2     Running     0          116s
csi-rbdplugin-krlbq                                 2/2     Running     0          116s
csi-rbdplugin-provisioner-7bfcc8659c-v58bl          5/5     Running     0          116s
csi-rbdplugin-provisioner-7bfcc8659c-z5gsl          5/5     Running     0          116s
csi-rbdplugin-t4qwr                                 2/2     Running     0          116s
rook-ceph-crashcollector-worker1-78b6dffbd9-ckhmc   1/1     Running     0          42s
rook-ceph-crashcollector-worker2-f457d766-gstt7     1/1     Running     0          27s
rook-ceph-crashcollector-worker3-56dc7676c-f6f2x    1/1     Running     0          24s
rook-ceph-exporter-worker1-7dbf7897bb-9x6j8         1/1     Running     0          42s
rook-ceph-exporter-worker2-75bc5c5b4f-dsgk6         1/1     Running     0          22s
rook-ceph-exporter-worker3-858b9c4b7b-xp599         1/1     Running     0          20s
rook-ceph-mgr-a-5fd6d7969b-tdbr4                    3/3     Running     0          60s
rook-ceph-mgr-b-545f7b87c7-hlmhj                    3/3     Running     0          60s
rook-ceph-mon-a-77757fc8dd-h6vtc                    2/2     Running     0          107s
rook-ceph-mon-b-56b56d665b-vjp8z                    2/2     Running     0          83s
rook-ceph-mon-c-c84669b49-l4w5r                     2/2     Running     0          72s
rook-ceph-operator-f6f8c9d56-qkwg7                  1/1     Running     0          14h
rook-ceph-osd-0-789796cdf6-hmqg4                    2/2     Running     0          27s
rook-ceph-osd-1-746d89845b-2zm97                    2/2     Running     0          26s
rook-ceph-osd-2-cb84dd78f-d7kx8                     1/2     Running     0          25s
rook-ceph-osd-prepare-worker1-ggfrv                 0/1     Completed   0          38s
rook-ceph-osd-prepare-worker2-tntp5                 0/1     Completed   0          37s
rook-ceph-osd-prepare-worker3-pcp8z                 0/1     Completed   0          36s

**Comment by parth-gr** [comment]
@vadlakiran Ceph exporter was created to avoid performance problems at scale obtaining metrics in clusters with high number of daemons (mainly OSDs).
https://github.com/rook/rook/blob/master/design/ceph/ceph-exporter.md

**Comment by vadlakiran** [comment]
@parth-gr Thank you for details, if i don't want to enable this, where i have to mention in cluster.yml ?

**Comment by parth-gr** [comment]
@vadlakiran here is the setting for it https://github.com/rook/rook/blob/master/deploy/examples/cluster.yaml#L87

**Comment by KKonak** [comment]
Is there by chance a hidden value to change to disable this feature in the cluster helm chart values?
