### ISSUE TITLE
rook env FLEXVOLUME_DIR_PATH over kubeletConfiguration VolumePluginDir when deploying rook.

### ISSUE THREAD

**Issue by albp** [rook/rook#1425]
Hi,

coreos, tectonic,deploying rook.
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4+coreos.0", GitCommit:"4292f9682595afddbb4f8b1483673449c74f9619", GitTreeState:"clean", BuildDate:"2017-11-21T17:22:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

The problem:

`kubectl -n rook-system get pod -l app=rook-agent -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.status.containerStatuses[0].lastState.terminated.message}{"\n"}{end}'

rook-agent-kbm5t        error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins/volume/exec': mkdir /usr/libexec/kubernetes: read-only file system
rook-agent-mtq5z        error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins/volume/exec': mkdir /usr/libexec/kubernetes: read-only file system
rook-agent-z7p9l        error while creating mount source path '/usr/libexec/kubernetes/kubelet-plugins/volume/exec': mkdir /usr/libexec/kubernetes: read-only file system`

I have set in rook-operator.yaml the path
`...
        env:
        - name: FLEXVOLUME_DIR_PATH
          value: "/var/lib/kubelet/volumeplugins"
...
`

But my system always get this path from kubeletconfig

`kubectl get --raw=/api/v1/nodes/<here one of my node names>/proxy/configz |jq '.kubeletconfig.volumePluginDir'                                                                 
"/usr/libexec/kubernetes/kubelet-plugins/volume/exec/"`

In the rook-operator log:
` op-agent: discovered flexvolume dir path from source KubeletConfiguration. value: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/`

I think that i have configured correctly the tectonic config, but all the way i think that if i set the rook operator env then this env must have prioriy over kubeletconfiguration.

I see this in the code that if exists a kuebeltconfig then it dont get the env config from getDefaultFlexvolumeDir because it returns from return flexvolumeDirPath, "KubeletConfiguration" (that KubeletConfiguration string that i see in rook operator deploy log.)

[https://github.com/rook/rook/blob/master/pkg/operator/agent/agent.go#L209](https://github.com/rook/rook/blob/master/pkg/operator/agent/agent.go#L209)

`
		flexvolumeDirPath = kubeletConfiguration.KubeletConfig.VolumePluginDir
	}

	if flexvolumeDirPath != "" {
		return flexvolumeDirPath, "KubeletConfiguration"
	}

      return getDefaultFlexvolumeDir() `

How could i do that it gets the rook env FLEXVOLUME_DIR_PATH from rook operator.

Thx.
edited: i have corrected the url markup.

**Comment by kokhang** [comment]
@albp if using coreos, you also have to set the FLEXVOLUME_DIR_PATH env in the rook-operator.yaml. See here https://rook.github.io/docs/rook/master/flexvolume.html

**Comment by albp** [comment]
@kokhang thx, but my message was about that, or i dont undestrand something, read this in my previous message:

I have set in rook-operator.yaml the path
... env: - name: FLEXVOLUME_DIR_PATH value: "/var/lib/kubelet/volumeplugins" ...

but in the agent.go code if kubeletconfig.volumePluginDir exists, then it has preference over FLEXVOLUME_DIR_PATH in rook operator.

**Comment by kokhang** [comment]
@albp Ahh.. This is an issue in Kubernetes 1.9 that was introduced. With the feature addition of dynamic kubelet configuration, there were a lot of changes and it affected the `node/proxy`  API.

Here is more information about it. https://github.com/rook/rook/issues/1330

**Comment by albp** [comment]
thx @kokhang but i dont think my case was a problem of kubernetes version, or the thread you linked,  in my kubernetes i can see this volumePluginDir

kubectl get --raw=/api/v1/nodes/<here one of my node names>/proxy/configz |jq 
.kubeletconfig.volumePluginDir "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/"

Perhaps i understood bad the FLEXVOLUME_DIR_PATH?

FLEXVOLUME_DIR_PATH is programmed like a DEFAULT value, first it try to find the value from the system config and if it cant find it then it look for the value in the environment (agent.go in getDefaultFlexvolumeDir). In my system that value exists so rook ignored the FLEXVOLUME_DIR_PATH in my rook-operator.yaml.

I thought that if i set the value in my rook-operator.yaml i was saying that this value must overwritte the system config value.

**Comment by kokhang** [comment]
OK now i understand. The rook operator does not set/override the system configuration. You have to set it manually using the `--volume-plugin-dir=/var/lib/kubelet/volumeplugins` flag. What the rook-operator allows you to do is to self-discover what this system config is set to.

However, as of K8s 1.9, rook was not able to do this auto-discovery. So the workaround to tell rook what this value is. Which is via the `FLEXVOLUME_DIR_PATH` env var.

**Comment by albp** [comment]
@kokhang thanks for the detailed explanation, please close this issue.
