### ISSUE TITLE
Integrate Rook with ceph-csi-operator

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#14260]
We are working on a cephcsi operator [1] which manages the life cycle of the cephcsi driver and also provides new CR's for easy installation and configuration of cephcsi drivers.

[1] https://github.com/ceph/ceph-csi-operator/

**Comment by travisn** [comment]
For added context, design for the new csi operator is [in progress](https://github.com/ceph/ceph-csi-operator/pull/1), and we will need to add design for rook integration as well. 

A consideration is whether the new csi operator will be experimental or will be enabled by default in Rook v1.15, but likely will need to support both existing csi deployment as well as the experimental ceph-csi operator.

**Comment by travisn** [comment]
Here are some thoughts on how Rook would integrate with the CSI Operator as found in the current [design doc](https://github.com/ceph/ceph-csi-operator/blob/main/docs/design/operator.md), also with some questions and suggestions for the operator design to consider.

### CSI Operator
- Rook will define the CSI operator and related CRs such as it is deployed by default and automatically with Rook
    - Manifests:
        - operator.yaml: Include the CSI operator deployment, and default CephCSI CRs
        - crds.yaml: Include the CephCSI CRDs
        - common.yaml: Include the RBAC needed for the CSI operator
        - Consider whether to have separate manifests, particularly in the first release if the CSI operator is experimental
    - Helm chart: Seamlessly includes all the CRDs, operator, RBAC, and default CRs
- Upgrade guide needed for transitioning to the new CSI operator
    - Ideally it will all be automated, and no special instructions needed
    - Same CSI driver names should be used for a seamless upgrade

### CephCSICephCluster CRD
- Any setting in this CR either needs to be generated by Rook, or wrapped by CephCluster CR (under `spec.csi`, as we currently have today)
- How is cephConfig set today? (It’s not currently in the CephCluster CR)
    - What is the scenario for setting ceph config overrides? We don’t actually want to disable cephx auth as in the design doc example
- How is read affinity disabled? There is no setting for it, like we have in CephCluster today
- CephCluster `spec.csi` settings
    - How will the cephfs `kernelMountOptions` and `fuseMountOptions` translate to the new CRDs? They are now in the CephCSIOperatorConfig/CephCSIDriver CRDs and no need for them in the CephCluster CRD, right? 

### CephCSIConfig CRD
- The Rook operator would generate an instance of this CR for each of:
    - CephFilesystemSubVolumeGroup CRs
    - CephBlockPoolRadosNamespace CRs
- A separate instance is expected for each subvolumegroup or rados namespace, correct? 
- If it were created in the same namespace as the CephCluster, then the reference could be implicit instead of needing a cephClusterRef setting
    - If we keep the cephClusterRef, is it a ref to the namespace where the cephcluster is found? Or do we need the namespace/name pair?
- Naming: The schema is very specific to rados namespaces and subvolumegroups. Seems like we either should have separate CRDs named specifically, or find another specific name. “Config” doesn’t mean anything to me.

### CephCSIOperatorConfig CRD
- Rook will define defaults in operator.yaml, and can be customizable by users
- Naming: How about renaming to CephCSIDriverDefaults?
    - One could argue that all settings are for an operator, so calling it OperatorConfig just seems very general and unhelpful.

### CephCSIDriver CRD
- Rook will define three instances of this CR, one each for RBD, CephFS, and NFS
    - The CRs will be empty (all the settings are defined as defaults in the previous CR), or else some small set of default driver-specific settings.

### CephCSIConfigMapping
- Rook will not define any instances
- DR users will create these CRs as necessary

**Comment by Madhu-1** [comment]
> Here are some thoughts on how Rook would integrate with the CSI Operator as found in the current [design doc](https://github.com/ceph/ceph-csi-operator/blob/main/docs/design/operator.md), also with some questions and suggestions for the operator design to consider.
> 
> ### CSI Operator
> * Rook will define the CSI operator and related CRs such as it is deployed by default and automatically with Rook
>   
>   * Manifests:
>     
>     * operator.yaml: Include the CSI operator deployment, and default CephCSI CRs
>     * crds.yaml: Include the CephCSI CRDs
>     * common.yaml: Include the RBAC needed for the CSI operator
>     * Consider whether to have separate manifests, particularly in the first release if the CSI operator is experimental
>   * Helm chart: Seamlessly includes all the CRDs, operator, RBAC, and default CRs
> * Upgrade guide needed for transitioning to the new CSI operator
>   
>   * Ideally it will all be automated, and no special instructions needed
>   * Same CSI driver names should be used for a seamless upgrade
> 
> ### CephCSICephCluster CRD
> * Any setting in this CR either needs to be generated by Rook, or wrapped by CephCluster CR (under `spec.csi`, as we currently have today)
> * How is cephConfig set today? (It’s not currently in the CephCluster CR)
>   

This is with a separate configmap where user is expected to create, i need to think about moving it to new CRD (if possible) or expect the user to create the cm with specific name for this one.

>   * What is the scenario for setting ceph config overrides? We don’t actually want to disable cephx auth as in the design doc example

That was just an example as cephx is also part of configuration what user can set. 

> * How is read affinity disabled? There is no setting for it, like we have in CephCluster today
> * CephCluster `spec.csi` settings
>   

The required fields in the ReadAffinity need not to be set if the user doesn't want to have readAffinity. IMO we don't need extra flag to say enable/disable in the CRD for it.

>   * How will the cephfs `kernelMountOptions` and `fuseMountOptions` translate to the new CRDs? They are now in the CephCSIOperatorConfig/CephCSIDriver CRDs and no need for them in the CephCluster CRD, right?
> 

Those are driver level where the same configuration will be applied to the ceph cluster, but in Rook case, As Rook supports multiple cephCluster we can keep it there and translate or if we want to get rid of all csi configuration from Rook CRD we need to think about whether Rook can automate or it expect the admin to handle those.

> ### CephCSIConfig CRD
> * The Rook operator would generate an instance of this CR for each of:
>   
>   * CephFilesystemSubVolumeGroup CRs
>   * CephBlockPoolRadosNamespace CRs
> * A separate instance is expected for each subvolumegroup or rados namespace, correct?
> * If it were created in the same namespace as the CephCluster, then the reference could be implicit instead of needing a cephClusterRef setting
>   
yes, Just name is enough as it is LocalObjectRef no namespace is required.

>   * If we keep the cephClusterRef, is it a ref to the namespace where the cephcluster is found? Or do we need the namespace/name pair?
> * Naming: The schema is very specific to rados namespaces and subvolumegroups. Seems like we either should have separate CRDs named specifically, or find another specific name. “Config” doesn’t mean anything to me.
> 

This is a cephcsi (single) cluster configuration IMO if we need to have separate CRDs specific to one Key and introduce new CRDs for each support that cephcsi adds just add a new field. The name config represents it's a `config` for the cephcsi that the reason to keep it as `cephCsiConfig`. keeping this in mind IMO whatever we have makes sense and we don't need to segregate cephfs/rbd/nfs specific to a new CRD.

> ### CephCSIOperatorConfig CRD
> * Rook will define defaults in operator.yaml, and can be customizable by users
> * Naming: How about renaming to CephCSIDriverDefaults?
>   
>   * One could argue that all settings are for an operator, so calling it OperatorConfig just seems very general and unhelpful.
> 

Yes above is the argument and again its overrides the operator default for csi driver and it also contains configuration for the operator as well.

> ### CephCSIDriver CRD
> * Rook will define three instances of this CR, one each for RBD, CephFS, and NFS
>   
>   * The CRs will be empty (all the settings are defined as defaults in the previous CR), or else some small set of default driver-specific settings.
> 
> ### CephCSIConfigMapping
> * Rook will not define any instances
> * DR users will create these CRs as necessary

This means whatever we have automation in Rook Today will be moved out and the user needs to configure it?, If that's the case we need to add poolID and filesystem IDs to the BlockPool and Filesystem CR status (if not present today) to let user knows what IDs they need to consider when creating these CR's.


I hope we have considered all the cases for external ceph cluster as well.

**Comment by travisn** [comment]
@Madhu-1 Thanks for the discussion and feedback. Based on the discussion, I'll revise my designs as such. Changed lines have a `*`.

Further discussions on CRD naming will move to https://github.com/ceph/ceph-csi-operator/issues/8.

### CSI Operator
(no change from above)

### CephCSICephCluster CRD
- Any setting in this CR either needs to be generated by Rook, or wrapped by CephCluster CR (under `spec.csi`, as we currently have today)
- *cephConfig is an advanced scenario and perhaps not to be included in this CRD
- *If read affinity is disabled (in the CephCluster CR), Rook should not add the read affinity topology labels to the CR.
- *The cephfs `kernelMountOptions` and `fuseMountOptions` should move into this CR, so Rook would pass them on from the CephCluster CR.

### CephCSIConfig CRD
- The Rook operator would generate an instance of this CR for each of:
    - CephFilesystemSubVolumeGroup CRs
    - CephBlockPoolRadosNamespace CRs
- *The cephClusterRef is just the name of the CephCluster CR, in the same namespace (even though there is only one CephCluster CR per namespace)

### CephCSIOperatorConfig CRD
- Rook will define defaults in operator.yaml, and can be customizable by users

### CephCSIDriver CRD
- Rook will define three instances of this CR, one each for RBD, CephFS, and NFS
    - The CRs will be empty (all the settings are defined as defaults in the previous CR), or else some small set of default driver-specific settings.

### CephCSIConfigMapping
- *Rook will define these mappings when the rbd mirroring is enabled
