### ISSUE TITLE
 Is it compatible with rook-ceph-default  when the name of cephblockpool is not replicapool ?

### ISSUE THREAD

**Issue by mengyu1987** [rook/rook#14264]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
   It is failed occasionally when clone a datavolume from a pvc in other namespace  for concurrency  [https://github.com/kubevirt/containerized-data-importer/issues/3259](url)
**Expected behavior:**
 A question : Can cephblockpool is a Custom Name when the storageclass is set to be default class.
**How to reproduce it (minimal and precise):**

**File(s) to submit**:

> ceph-block is default class，and the pool is  ceph-blockpool.

```
[root@node152 ~]# kubectl get sc
NAME                   PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ceph-block (default)   rook-ceph.rbd.csi.ceph.com      Retain          Immediate           true                   8d
ceph-fs                rook-ceph.cephfs.csi.ceph.com   Retain          Immediate           true                   8d

[root@node152 ~]# kubectl get sc ceph-block  -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: os-rook-ceph-cluster
    meta.helm.sh/release-namespace: default
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2024-05-15T12:01:27Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: ceph-block
  resourceVersion: "8172170"
  uid: dd454972-29e1-4932-bbc1-789ef28e5c6e
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  imageFeatures: layering
  imageFormat: "2"
  pool: ceph-blockpool
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Retain
volumeBindingMode: Immediate

```

> ceph-blockpool  yaml
```
[root@node152 ~]# kubectl get cephblockpools -n rook-ceph
NAME             PHASE
ceph-blockpool   Ready
[root@node152 ~]# kubectl get cephblockpools -n rook-ceph  -o yaml
apiVersion: v1
items:
- apiVersion: ceph.rook.io/v1
  kind: CephBlockPool
  metadata:
    annotations:
      meta.helm.sh/release-name: os-rook-ceph-cluster
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2024-05-15T12:01:28Z"
    finalizers:
    - cephblockpool.ceph.rook.io
    generation: 2
    labels:
      app.kubernetes.io/managed-by: Helm
    name: ceph-blockpool
    namespace: rook-ceph
    resourceVersion: "617077"
    uid: d9386bd0-2b38-4b90-9a7f-c528ef04d05c
  spec:
    erasureCoded:
      codingChunks: 0
      dataChunks: 0
    failureDomain: host
    mirroring: {}
    quotas: {}
    replicated:
      size: 3
    statusCheck:
      mirror: {}
  status:
    observedGeneration: 2
    phase: Ready
kind: List
metadata:
  resourceVersion: ""
```

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
  NAME="H3Linux"
  VERSION="2.0.2-SP01"
* Kernel (e.g. `uname -a`):
 Linux node152 5.10.0-136.12.0.86.4.hl202.x86_64 #1 SMP Fri Mar 10 14:42:11 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
   rook/ceph:v1.13.5
* Storage backend version (e.g. for ceph do `ceph -v`):
    cephcsi:v3.10.2
    quay.io/ceph/ceph:v18.2.1
    sig-storage/csi-provisioner:v3.6.3
* Kubernetes version (use `kubectl version`):
  v1.27.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
> Expected behavior:
> A question : Can cephblockpool is a Custom Name when the storageclass is set to be default class.

Yes, the name of the cephblockpool is not important, `replicapool` is just the example pool name. If you have a different pool, as long as the name is changed everywhere in the examples, then it should work.

What error are you seeing? The clone only works sometimes? If there is a problem with the pool it will likely fail every time. Is there some Ceph health issue?
