### ISSUE TITLE
Exporter pods for external Ceph cluster are stuck Initializing

### ISSUE THREAD

**Issue by travisn** [rook/rook#14276]
Since upgrading to rook 1.13, the `rook-ceph-exporter-*` Pods for my external Ceph cluster (which is in a different namespace than the operator) are stuck at `Init:0/1` due to:

```
MountVolume.SetUp failed for volume "rook-ceph-exporter-keyring" : secret "rook-ceph-exporter-keyring" not found
```

The `rook-ceph-exporter-keyring` Secret exists in the `rook-ceph` namespace but not in the `rook-ceph-external` namespace, where the external Ceph cluster is located.

_Originally posted by @haslersn in https://github.com/rook/rook/issues/13239#issuecomment-2129291300_

**Comment by haslersn** [comment]
Possible duplicate of #14275

**Comment by travisn** [comment]
> Possible duplicate of #14275

Yes, I'll close this! :)
