### ISSUE TITLE
exporter Pods for external Ceph cluster fail to start due to missing Secret

### ISSUE THREAD

**Issue by haslersn** [rook/rook#14275]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

This came up after upgrading to rook 1.13 and was first reported by me here: https://github.com/rook/rook/pull/13239#issuecomment-2129291300

I have an external Ceph cluster with RGW daemons running in Kubernetes managed by Rook. (This is configured using a CephObjectStore resource with `.spec.gateway`.) The operator spawns `crashcollector`, `exporter`, and `rgw` Deployments.

The `exporter` Pods fail to start due to:

```
MountVolume.SetUp failed for volume "rook-ceph-exporter-keyring" : secret "rook-ceph-exporter-keyring" not found
```

The `rook-ceph-exporter-keyring` Secret exists in the `rook-ceph` namespace but not in the `rook-ceph-external` namespace, where the external Ceph cluster is configured.

**Expected behavior:**

Pods should not fail to start. Maybe these exporter Deployments should not be created at all since the external Ceph cluster might run on completely different machines.

**Environment**:
* Rook version: v1.13.9
* Storage backend version: ceph v18.2.2
* Kubernetes version: v1.26.15
* Kubernetes cluster type: kubeadm on bare metal

**Comment by parth-gr** [comment]
@BlaineEXE i think the issue if for the second case, 
> External-mode CephCluster with Local CephObjectStore (mons and osds are remote, but we run the RGW inside k8s)

@haslersn  can you share the `kubectl get cephcluster -namespaceexternal` and `kubectl get rook-opertor-pod -n operatornamesapce` and `kubectl get secret rook-ceph-exporter-keyring -n operator namespace`

For woraround:

Copy the above exporter secret to external namesapce.

And share the operator logs, because as per the code the secret should be created in cephcluster namesapce

**Comment by yaguangtang** [comment]
[rook-ceph-operator.log](https://github.com/user-attachments/files/16119890/rook-ceph-operator.log)

@parth-gr please operator pod log, this is deployed with external ceph cluster so no namespace of ceph cluster, 
ceph operator running in ceph-rook namespace, rook-ceph-rgw and rook-ceph-exporter pod running in openstack namespace, no rook-ceph-exporter-keyring in any namespace.

**Comment by parth-gr** [comment]
@yaguangtang you also have to create https://github.com/rook/rook/blob/master/deploy/examples/external/cluster-external.yaml for connecting to external ceph cluster.

**Comment by yaguangtang** [comment]
> @yaguangtang you also have to create https://github.com/rook/rook/blob/master/deploy/examples/external/cluster-external.yaml for connecting to external ceph cluster.

I did that again, still no exporter secret created, you can see from the operator log file , the rook-cephcrash-collector-keyring is created, but  the rook-ceph-exporter-keyring is not created.

**Comment by yaguangtang** [comment]
[rook-ceph-operator.log](https://github.com/user-attachments/files/16125749/rook-ceph-operator.log)
new log file

**Comment by yaguangtang** [comment]
root@instance:/home/ubuntu# kubectl logs rook-ceph-operator-bf6448797-sw5p8  -n rook-ceph|grep secret
2024-07-10 04:21:49.545178 I | ceph-cluster-controller: creating "rook-ceph-config" secret
2024-07-10 04:21:51.948217 I | ceph-csi: created kubernetes csi secrets for cluster "openstack"
2024-07-10 04:21:52.591835 I | ceph-nodedaemon-controller: created kubernetes crash collector secret for cluster "openstack"
2024-07-10 04:23:10.071081 I | ceph-object-controller: setting the dashboard api secret key
2024-07-10 04:23:10.656352 I | ceph-object-controller: done setting the dashboard api secret key

from the operator log , we can see only crash collector secret is created by nodedaemon-controller, I believe ceph exporter secret also be created by nodedaemon controller.

**Comment by yaguangtang** [comment]
@travisn Can you help review the PR for this issue, thanks.
