### ISSUE TITLE
build issue with go module checksum mismatch in the master branch  on Fedora 40.

### ISSUE THREAD

**Issue by obnoxxx** [rook/rook#14282]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
a clean master branch checkoutcurrently locally fails building for me with this error:

```console
verifying github.com/portworx/sched-ops@v0.20.4-openstorage-rc3: checksum mismatch
	downloaded: h1:46EZ+vYCJ3qmQolvgDCrGuPz8Tf0vIds41RuF0dqVEw=
	go.sum:     h1:tXnHsjZT2wZ2BCXf8avDoya7zGyCgLNUC8Upt+WEQrY=
``

**Expected behavior:**

build of a fresh checkout should succeed.

**How to reproduce it (minimal and precise):**

```console
$ git clone git@github.com:rook/rook.git
$ cd rook
$ make build
```

**File(s) to submit**:

not submitting any files or logs  since this is nor\t a runtime error but a build error.

**Environment**:
* OS(e.g. from /etc/os-release): Fedora release 40 (Forty)
* Kernel (e.g. `uname -a`): Linux curve 6.8.10-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Fri May 17 21:20:54 UTC 2024 x86_64 GNU/Linux 
* Cloud provider or hardware configuration: Lenovo Thinkpad T470s
* Rook version (use `rook version` inside of a Rook Pod): naster git branch 
* Storage backend version (e.g. for ceph do `ceph -v`): N/A
* Kubernetes version (use `kubectl version`): Client Version: v1.28.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): minikube

**Comment by BlaineEXE** [comment]
@obnoxxx what go version is being used on the system?

**Comment by BlaineEXE** [comment]
@subhamkrai @parth-gr are you using Fedora for your development? Have you ever seen this issue? Would you also note the Fedora version and go version are you currently using, so we have a reference of what is working?

**Comment by subhamkrai** [comment]
> @subhamkrai @parth-gr are you using Fedora for your development? Have you ever seen this issue? Would you also note the Fedora version and go version are you currently using, so we have a reference of what is working?

@BlaineEXE 
```
go version && cat /etc/fedora-release 
go version go1.22.1 linux/amd64
Fedora release 40 (Forty)
```

**Comment by obnoxxx** [comment]
Update:

I am still facing this issue on Fedora 40:

```console

$  go version
go version go1.22.3 linux/amd64
$


```

on a fresh master rook  clone/checkout:

```console

$ make mod.check 
=== syncing root modules with APIs modules
=== ensuring APIs modules are tidied
=== ensuring root modules are tidied
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azcore v1.12.0
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.6.0
verifying github.com/portworx/sched-ops@v0.20.4-openstorage-rc3: checksum mismatch
	downloaded: h1:46EZ+vYCJ3qmQolvgDCrGuPz8Tf0vIds41RuF0dqVEw=
	go.sum:     h1:tXnHsjZT2wZ2BCXf8avDoya7zGyCgLNUC8Upt+WEQrY=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
make: *** [build/makelib/golang.mk:179: go.mod.check] Error 1
$
```

**Comment by obnoxxx** [comment]
Update: I tried it on Ubuntu 22.04.4 with golang 1.22.5 and the issue did *not* occur.

**Comment by BlaineEXE** [comment]
Some things that you could try if you haven't:
- `go mod verify`
- delete the entire `$HOME/go` dir to clean up any go sources on the system that possibly could have some sort of corruption or misidentification

**Comment by obnoxxx** [comment]
@BlaineEXE  wrote:
> Some things that you could try if you haven't:

Thanks for the hints. comments inline below:

>     * `go mod verify`

This passes on my fedora 40 machine. 

> 
>     * delete the entire `$HOME/go` dir to clean up any go sources on the system that possibly could have some sort of corruption or misidentification


I can try that   but am a  tad reluctant since this dir  contains my rook clones and those of other golang-based projects under src.


Will report back once I have tried this.

**Comment by obnoxxx** [comment]
one more update:

I have tried it on a Fedora 39 VM.

But like on Ubuntu, I had to manually install golang 1.22 first to be able to run make commands in rook, because the system golang packages are too old (1.21).


As a consequence, I am beginning to rule out the operating system as the cause of the issue
and begin to  suspect the exact golang version to be the cause.

Maybe I should try the manual install of go 1.22.5 under /usr/local on my fedora 40 machine ...

**Comment by obnoxxx** [comment]
update:

Installed go 1.22.5 manually under /usr/local on my fedora 40 machine, but the problem persists

So I'll have to try the removal of`$HOME/go` next

**Comment by obnoxxx** [comment]
update:

with a fresh/empty `$HOME/go` directory, the issue does **not** occur on my Fedora40 machine.

Thanks for the hint, @BlaineEXE !

**Comment by obnoxxx** [comment]
since pruning `$HOME/go`settled this for me on Fedora 40 an the issue did not  even exist on Ubuntru and Fedora 39, I am closig this. It will be kept for future reference.
