### ISSUE TITLE
builds from master are dirty

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1428]
Recent builds published to docker hub have `dirty` in their tag, implying there is a local change on the Jenkins build server.  This should not be happening and we need to figure out what the cause is.

https://hub.docker.com/r/rook/rook/tags/
Example: v0.6.0-164.gf61daf9.dirty

**Comment by jbw976** [comment]
@dangula found that the `Gopkg.lock` file is updated in the local working copy on Jenkins:
```
> git status
HEAD detached at c160224
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   Gopkg.lock

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    rook-amd64.tar

> git diff HEAD Gopkg.lock
diff --git a/Gopkg.lock b/Gopkg.lock
index 2882be9..9256177 100644
--- a/Gopkg.lock
+++ b/Gopkg.lock
@@ -387,6 +387,6 @@
 [solve-meta]
   analyzer-name = "dep"
   analyzer-version = 1
-  inputs-digest = "39454bb679c497ef9ee296e5ddd81df83f1b64583ac2349bb798553e5d641ad8"
+  inputs-digest = "8cdf401487ba3a25dd7005c5e15521d72a29a67ea044a1ef203d7f51b4b84c60"
   solver-name = "gps-cdcl"
   solver-version = 1
```

strange that only the inputs-digest would change and nothing else.  this is the first commit where this started happening, but i see no dependency changes in that commit: https://github.com/rook/rook/commit/86c4962900b7dde9780c35a03ef42d299e46b9e5 (edited)

this looks helpful: https://github.com/golang/dep/issues/1392#issuecomment-346305224

**Comment by travisn** [comment]
can we just revert the file and see if the change comes back?

**Comment by jbw976** [comment]
@travisn i don't *think* there's anything to revert though.  I *believe* that each build starts with a "fresh" cloned repo and then during the build process this change gets introduced, I assume during the vendor makefile target.  I wonder if this would repo locally if we ran the same build command that Jenkins runs.

**Comment by travisn** [comment]
i ran `dep ensure` and hit the same issue locally. I'll open a PR with it.
