### ISSUE TITLE
HEALTH_WARN

### ISSUE THREAD

**Issue by msaustral** [rook/rook#14309]
Hi we have a health warning on ceph status

 1 MDSs report oversized cache
 1 clients failing to respond to capability release
 1 clients failing to advance oldest client/flush tid
 1 MDSs report slow requests

then when we see details we get this:

HEALTH_WARN 1 MDSs report oversized cache; 1 clients failing to respond to capability release; 2 clients failing to advance oldest client/flush tid; 1 MDSs report slow requests
[WRN] MDS_CACHE_OVERSIZED: 1 MDSs report oversized cache
    mds.australfs-a(mds.0): MDS cache is too large (8GB/4GB); 0 inodes in use by clients, 0 stray files
[WRN] MDS_CLIENT_LATE_RELEASE: 1 clients failing to respond to capability release
    mds.australfs-b(mds.0): Client workload-rusup:csi-cephfs-node failing to respond to capability release client_id: 6562161
[WRN] MDS_CLIENT_OLDEST_TID: 2 clients failing to advance oldest client/flush tid
    mds.australfs-b(mds.0): Client workload-rckcy:csi-cephfs-node failing to advance its oldest client/flush tid.  client_id: 6823101
    mds.australfs-b(mds.0): Client workload-rusup:csi-cephfs-node failing to advance its oldest client/flush tid.  client_id: 6562161
[WRN] MDS_SLOW_REQUEST: 1 MDSs report slow requests
    mds.australfs-b(mds.0): 22 slow requests are blocked > 30 secs

we found the description of the issue on the rook documentation but it does not say how to solve it, can you help us?

**Comment by travisn** [comment]
Have you set the memory/cpu resources on the MDS pod? See [here](https://github.com/rook/rook/blob/master/deploy/examples/filesystem.yaml#L103-L109) for an example. You likely need to increase this memory as the default is not sufficient for larger workloads. 8Gi or 16Gi, or even much higher memory is frequently needed for the MDS.

**Comment by msaustral** [comment]
Hi we do not have memory or cpu limit on MDS

![image](https://github.com/rook/rook/assets/46203943/3d5fea7b-8d05-4edf-ac87-6b113470ee01)

**Comment by msaustral** [comment]
Hi these are the 2 pods consumption:
![image](https://github.com/rook/rook/assets/46203943/a5a5bb07-6988-4cf3-824f-953ea75437ba)
![image](https://github.com/rook/rook/assets/46203943/6a941414-3d29-46eb-88af-8110db658332)

they are on different node and this is the node resource:

![image](https://github.com/rook/rook/assets/46203943/138ecdf4-43bd-45ad-8cb1-55e3f30eb004)
![image](https://github.com/rook/rook/assets/46203943/7663ebc2-4b87-4163-91ba-d02bd5bcee0a)

If i change the memory limit will get the data cluster down for recreation?

**Comment by travisn** [comment]
> If i change the memory limit will get the data cluster down for recreation?

Rook will perform a rolling update, one daemon at a time, just like an upgrade, to apply new memory limits.

**Comment by msaustral** [comment]
hi, ok, the warning is clean automatically or we have to clean it manually?

**Comment by travisn** [comment]
If the increased memory resolves the issue, then the warnings would go away automatically, but it is possible there is still some other issue besides memory.

**Comment by msaustral** [comment]
ok we will try
