### ISSUE TITLE
pgs degraded and undersized

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#14318]
we have installed the rook-ceph on kuberneres cluster and  almost 1 month down one of the osd worker node, not able to to come with health status.

how to resolve the below  status and operator logs showing that osd is down

below is the status:

kubectl -n rook-ceph exec -it deploy/rook-ceph-tools  -- ceph status
  cluster:
    id:     c826f143-8c3e-469b-805b-60e4f7dd2042
    health: HEALTH_WARN
            Degraded data redundancy: 2702/8106 objects degraded (33.333%), 61 pgs degraded, 65 pgs undersized
            65 pgs not deep-scrubbed in time
            65 pgs not scrubbed in time
 
  services:
    mon: 3 daemons, quorum a,b,c (age 24m)
    mgr: a(active, since 5w)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 2 up (since 3d), 2 in (since 3d)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 2.70k objects, 273 MiB
    usage:   1.0 GiB used, 1.2 TiB / 1.2 TiB avail
    pgs:     2702/8106 objects degraded (33.333%)
             61 active+undersized+degraded
             4  active+undersized
 
  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
 
  progress:
    Global Recovery Event (0s)

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.8.1
* Storage backend version (e.g. for ceph do `ceph -v`): v16.2.10
* Kubernetes version (use `kubectl version`): v23.5.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
kubectl -n rook-ceph exec -it deploy/rook-ceph-tools  -- ceph status
  cluster:
    id:     c826f143-8c3e-469b-805b-60e4f7dd2042
    health: HEALTH_WARN
            Degraded data redundancy: 2702/8106 objects degraded (33.333%), 61 pgs degraded, 65 pgs undersized
            65 pgs not deep-scrubbed in time
            65 pgs not scrubbed in time
 
  services:
    mon: 3 daemons, quorum a,b,c (age 24m)
    mgr: a(active, since 5w)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 2 up (since 3d), 2 in (since 3d)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 2.70k objects, 273 MiB
    usage:   1.0 GiB used, 1.2 TiB / 1.2 TiB avail
    pgs:     2702/8106 objects degraded (33.333%)
             61 active+undersized+degraded
             4  active+undersized
 
  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
 
  progress:
    Global Recovery Event (0s)

**Comment by sp98** [comment]
are you suggesting that the Node is also down? @vadlakiran

**Comment by travisn** [comment]
@vadlakiran Since you have a node down with an OSD for so long, you will need to replace the down OSD. Since you have replica 3 pools, the replicas cannot be healthy unless there are three OSDs on different nodes. See the [OSD management](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-osd-mgmt/) topic to remove the down OSD and add a new one.

**Comment by vadlakiran** [comment]
@travisn @sp98  node down with and OSD for long time, we have make it up and reassingn to k8s also osd also, there no issue on this node and osd, other node which is belongs to osd is down. but when i checked in osd status from tools pod showing down.  when i checked from osd pod it showing running.

node is down for long time i.e worker1 respective osd1
node is up and running  i.e worker3 respective osd3

once we added back to the cluster worker1, worker2 osd is showing down from tools pod.
what is the reason shoing worker3 osd is down, it should show the worker1 osd1 should show the down because long time down.

please let me know, how i can resolve this issue? i can not reinstall the rook-ceph cluster

**Comment by vadlakiran** [comment]
@travisn  below is the osd status status

`[rook@rook-ceph-tools-79957dbdb7-65t9m /]$ ceph osd tree
ID  CLASS  WEIGHT   TYPE NAME                            STATUS  REWEIGHT  PRI-AFF
-1         1.75768  root default
-3         0.58589      host rms-fut-multinode-worker01
0    hdd  0.58589          osd.0                            up   1.00000  1.00000
-5         0.58589      host rms-fut-multinode-worker02
1    hdd  0.58589          osd.1                            up   1.00000  1.00000
-7         0.58589      host rms-fut-multinode-worker03
2    hdd  0.58589          osd.2                          down         0  1.00000
[rook@rook-ceph-tools-79957dbdb7-65t9m /]$`

below is the cluster node status

`$ sudo kubectl get nodes
[sudo] password for user:
NAME                         STATUS   ROLES                  AGE    VERSION
master                         Ready    control-plane,master   177d   v1.21.5
worker01                     Ready    <none>                 177d   v1.21.5
worker02                     Ready    <none>                 177d   v1.21.5
worker03                     Ready    <none>                 177d   v1.21.5`

below is the rook-ceph pod status


$sudo kubectl -n root-ceph get pods[1P[1@k
NAME                                                              READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-25qf8                                            3/3     Running     15         177d
csi-cephfsplugin-lx6hj                                            3/3     Running     18         177d
csi-cephfsplugin-provisioner-5f459cfb94-58gmt                     6/6     30  Running     0          42d
csi-cephfsplugin-provisioner-5f459cfb94-7725g                     6/6     Running     0          40d
csi-cephfsplugin-vxnj2                                            3/3     Running     13         177d
csi-rbdplugin-bpdr9                                               3/3     Running     15         177d
csi-rbdplugin-mhmwt                                               3/3     Running     18         177d
csi-rbdplugin-provisioner-84c7fb8d76-22ctd                        6/6     Running     0          40d
csi-rbdplugin-provisioner-84c7fb8d76-7s88t                        6/6     Running     0          42d
csi-rbdplugin-rjlwg                                               3/3     Running     12         177d
rook-ceph-crashcollector-worker01-6444c78khc2   1/1     Running     0          3d15h
rook-ceph-crashcollector-worker02-5555d8kxcf9   1/1     Running     0          40d
rook-ceph-crashcollector-worker03-6586b4q7wqw   1/1     Running     0          42d
rook-ceph-mds-myfs-a-5465f6c744-5m725                             2/2     Running     7747       40d
rook-ceph-mds-myfs-b-fdd479f6-gbsb7                               2/2     Running     4          42d
rook-ceph-mgr-a-7d75d49cc8-ntwjh                                  2/2     Running     498        41d
rook-ceph-mon-a-f9b4cdb84-lwqd5                                   2/2     Running     1          3d15h
rook-ceph-mon-b-79c4bd7944-x9bvt                                  2/2     Running     0          42d
rook-ceph-mon-c-69c59b4fb9-ghvw4                                  2/2     Running     0          40d
rook-ceph-operator-6875f8d4fc-9rj88                               1/1     Running     0          41d
rook-ceph-osd-0-59c947d546-nqqfb                                  2/2     Running     0          130d
rook-ceph-osd-1-7447bdb977-dzfcq                                  2/2     Running     0          40d
rook-ceph-osd-2-bd47d5d7f-v2tx2                                   2/2     Running     0          42d
rook-ceph-osd-prepare-worker01-bt4nm            0/1     Completed   1          130d
rook-ceph-osd-prepare-worker02-x4mqz            0/1     Completed   0          40d
rook-ceph-osd-prepare-multinode-worker03-8sd5b            0/1     Completed   0          40d
rook-ceph-tools-79957dbdb7-65t9m                                  1/1     Running     0          41d
$
`

**Comment by vadlakiran** [comment]
@travisn below is the ceph status, i have restarted the osd's but no luck, there is no network connectivity issues on this cluster.
if i want to purge the OSD and start a new OSD , which OSD i have to do, i mean worker 1 osd or worker 3 osd ?

`sudo kubectl -n rook-ceph exec -it deploy/rook-ceph-tools  -- ceph status
  cluster:
    id:     c826f143-8c3e-469b-805b-60e4f7dd2042
    health: HEALTH_WARN
            Degraded data redundancy: 2702/8106 objects degraded (33.333%), 61 pgs degraded, 65 pgs undersized
            65 pgs not deep-scrubbed in time
            65 pgs not scrubbed in time
 
  services:
    mon: 3 daemons, quorum a,b,c (age 24m)
    mgr: a(active, since 5w)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 2 up (since 3d), 2 in (since 3d)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 2.70k objects, 273 MiB
    usage:   1.0 GiB used, 1.2 TiB / 1.2 TiB avail
    pgs:     2702/8106 objects degraded (33.333%)
             61 active+undersized+degraded
             4  active+undersized
 
  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
 
  progress:
    Global Recovery Event (0s)
`

**Comment by travisn** [comment]
Ok, the ceph health issues are just related to the one OSD that is down.

The `ceph osd tree` shows that osd.2 is down on worker03, so this is the OSD that would need to be replaced:
```
-7         0.58589      host rms-fut-multinode-worker03
2    hdd  0.58589          osd.2                          down         0  1.00000
```

**Comment by vadlakiran** [comment]
@travisn okay Thank you, but can we ignore the below warning on ceph health status

health: HEALTH_WARN
            Degraded data redundancy: 2702/8106 objects degraded (33.333%), 61 pgs degraded, 65 pgs undersized
            65 pgs not deep-scrubbed in time
            65 pgs not scrubbed in time

**Comment by sp98** [comment]
@vadlakiran Don't think we should ignore this warning.  You data is not replicated on all the three OSDs since 1 of the OSD is down.

**Comment by travisn** [comment]
@vadlakiran The issue is that the data is only replicated to 2 OSDs, but cannot create the 3rd replica because the OSD is down. Until the OSD is replaced, your data will not be fully replicated. The data is still safe with two replicas, but less safe than with three replicas.

**Comment by vadlakiran** [comment]
@travisn @sp98  i am attaching the 3 worker osd-prepared pods logs, please let me know any thing suspicious.
[osd-worker3.log](https://github.com/user-attachments/files/15912797/osd-worker3.log)
[osd-worker2.log](https://github.com/user-attachments/files/15912798/osd-worker2.log)
[osd-worker1.log](https://github.com/user-attachments/files/15912799/osd-worker1.log)

**Comment by vadlakiran** [comment]
@travisn did you get a time to see the logs ?

**Comment by travisn** [comment]
The OSD prepare logs do not show the issue for why the OSD is down. What about the logs for the osd.2 pod that is not showing as up? Does it show any issues? 

You may need to [purge the OSD](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-osd-mgmt/#remove-an-osd), wipe the disk, and restart the operator to create a new OSD in place of osd.2.

**Comment by vadlakiran** [comment]
@travisn  yes its osd is running when we checked the pods status, did not see any logs as well.

for purge the osd, customer might not approve as this is production environment

logs:
=====
rook-ceph-osd-0-59c947d546-nqqfb                                  2/2     Running     0          130d
rook-ceph-osd-1-7447bdb977-dzfcq                                  2/2     Running     0          40d
rook-ceph-osd-2-bd47d5d7f-v2tx2                                   2/2     Running     0          42d

**Comment by vadlakiran** [comment]
@travisn below is the present ceph status output. i can see the clock skew, is it causing the issue.

`            ceph health status
            ===================

  cluster:
    id:     c826f143-8c3e-469b-805b-60e4f7dd2042
    health: HEALTH_WARN
            clock skew detected on mon.b, mon.c
            Degraded data redundancy: 3962/11886 objects degraded (33.333%), 61 pgs degraded, 65 pgs undersized
            65 pgs not deep-scrubbed in time
            65 pgs not scrubbed in time
 
  services:
    mon: 3 daemons, quorum a,b,c (age 2d)
    mgr: a(active, since 6w)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 2 up (since 6d), 2 in (since 6d)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 3.96k objects, 351 MiB
    usage:   1.4 GiB used, 1.2 TiB / 1.2 TiB avail
    pgs:     3962/11886 objects degraded (33.333%)
             61 active+undersized+degraded
             4  active+undersized
 
  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
 
  progress:
    Global Recovery Event (0s)
      [............................] 
 

`

**Comment by travisn** [comment]
Ah yes, clock skew can cause issues such as preventing OSDs from being up. You'll need to setup a time service such as ntp to sync them.
