### ISSUE TITLE
Failed to set up rook ceph on K3S

### ISSUE THREAD

**Issue by janesenaj42** [rook/rook#14317]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Ceph cluster does not start up as expected.

**Expected behavior:**
Ceph cluster should start up in the kubernetes environment.

**How to reproduce it (minimal and precise):**

Trying to set up rook ceph using helm ([operator ](https://rook.io/docs/rook/latest-release/Helm-Charts/operator-chart/)and [cluster](https://rook.io/docs/rook/latest-release/Helm-Charts/ceph-cluster-chart/)) on a K3S cluster. The operator installs without error but when trying to install the cluster the pod `rook-ceph-detect-version` keeps failing with a `No module named 'encodings'` error. Running `python3` in the operator pod returns a `Fatal Python error: Py_Initialize: Unable to get the locale encoding` error, which does not happen in the docker image itself (tested using `docker run`). Tried setting the `LANG` environment variable in the pod but error persists. Reinstalled fresh K3S cluster but same error persists. Using rook ceph v1.14.5 and ceph v18.2.2.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
```
Current thread 0x00007f8d94001b80 (most recent call first):
2024-06-10 07:31:24.935196 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2024-06-10 07:31:24.938413 I | ceph-cluster-controller: clusterInfo not yet found, must be a new cluster.
2024-06-10 07:31:24.964206 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v18.2.2...
2024-06-10 07:31:24.969753 I | op-k8sutil: Removing previous job rook-ceph-detect-version to start a new one
2024-06-10 07:31:24.977663 I | op-k8sutil: batch job rook-ceph-detect-version still exists
2024-06-10 07:31:27.983000 I | op-k8sutil: batch job rook-ceph-detect-version deleted
2024-06-10 07:31:29.660172 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed the ceph version check: ceph version job returned failure with retcode -1. stdout: . stderr: Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

```
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): Linux 
* Kernel (e.g. `uname -a`): 3.10.0-1160.15.2.e17.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): v1.28.7+k3s1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by BlaineEXE** [comment]
If the container is returning a python error when running `ceph -v`, I would suspect some issue in the Ceph image. The ceph CLI init is python IIRC.

One thing that strikes me is that the kernel version is pretty old. Kernel `3.10.0-1160.15.2.e17.x86_64` has a release date of 3 Feb. 2021. I'm not sure if this is related or not. From what I can tell, the latest versions of K3s use kernel 4.11. I wonder if this issue resolves if k3s is upgraded.

**Comment by janesenaj42** [comment]
> If the container is returning a python error when running `ceph -v`, I would suspect some issue in the Ceph image. The ceph CLI init is python IIRC.
> 
> One thing that strikes me is that the kernel version is pretty old. Kernel `3.10.0-1160.15.2.e17.x86_64` has a release date of 3 Feb. 2021. I'm not sure if this is related or not. From what I can tell, the latest versions of K3s use kernel 4.11. I wonder if this issue resolves if k3s (or whatever base system is running) is upgraded.

Thanks for catching that. It's silly but the issue turns out to be SELinux (running K3S on CentOS VMs). Disabling SELinux and we could install the ceph cluster. Not the best practice till we find a more permanent solution.
