### ISSUE TITLE
After rook-ceph clean up, there is leftover process "[ceph-msgr]

### ISSUE THREAD

**Issue by ygao-armada** [rook/rook#14328]
**Is this a bug report or feature request?**
* Bug Report
I follow instruction on https://rook.io/docs/rook/latest/Storage-Configuration/ceph-teardown/ to clean up the rook-ceph storage

However, on each node, there is a leftover process, which can NOT be terminated by "kill -9":
`1 I root    8159    2 0 60 -20 -   0 rescue 05:09 ?    00:00:00 [ceph-msgr]`

**Deviation from expected behavior:**

**Expected behavior:**
No leftover from rook-ceph

**How to reproduce it (minimal and precise):**

1. Create the storage following: https://rook.io/docs/rook/latest/Getting-Started/quickstart/
2. Create Block Storage following: https://rook.io/docs/rook/latest/Storage-Configuration/Block-Storage-RBD/block-storage/
3. Clean up following: https://rook.io/docs/rook/latest/Storage-Configuration/ceph-teardown/
4. ssh to each node and run command: "ps -ef | grep ceph"

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 20.04.6 LTS
* Kernel (e.g. `uname -a`): 5.4.0-182-generic #202-Ubuntu SMP
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.13.6
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.1
* Kubernetes version (use `kubectl version`): 1.28.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): EKSA
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by travisn** [comment]
@rzarzynski What is the proper way to cleanup the `ceph-msgr` process?

**Comment by rzarzynski** [comment]
From the `msg/Messenger.h`:

```cpp
  // shutdown
  /**
   * Block until the Messenger has finished shutting down (according
   * to the shutdown() function).
   * It is valid to call this after calling shutdown(), but it must
   * be called before deleting the Messenger.
   */
  virtual void wait() = 0;
  /**
   * Initiate a shutdown of the Messenger.
   *
   * @return 0 on success, -errno otherwise.
   */
  virtual int shutdown() { started = false; return 0; 
```

After the shutdown sequence, it should be fine to call the destructor.

**Comment by travisn** [comment]
The `ceph-msgr` process is leftover on the host after Rook is uninstalled, I assume from the kernel drivers. Any way to terminate it other than a restart? I assume it is inactive and harmless to leave it, @ygao-armada just wanted to know how to clean it up.

**Comment by rzarzynski** [comment]
Sorry, mistakenly error-corrected to _shutdown sequence of the a userspace's msgr_. Does unloading the kernel modules get rid of the kernel thread? If not, you might to want to loop Ilya in.
