### ISSUE TITLE
PV autoprovisioning fails on K8s 1.9 with VolumeScheduling gate enabled

### ISSUE THREAD

**Issue by lorenz** [rook/rook#1433]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
When creating a PVC to provision Rook Block Storage the PVC and the PV stay pending.

Reason (excerpt from controller-manager loop):
```
E0124 18:07:06.996015       1 pv_controller_base.go:236] could not sync volume "kubeless/datadir-kafka-0": VolumeBindingMode not set for StorageClass "rook-block-ssd-3"
```

Workaround:
```
kubectl patch storageclass yourstorageclass -p '{"volumeBindingMode": "Immediate"}'
```

What you expected to happen:
The PV should go to Bound state and the PVC should bind to it

How to reproduce it (minimal and precise):
Run K8s 1.9.x with VolumeScheduling feature gate, start a Rook cluster and create a PVC.

**Environment**:
* OS (e.g. from /etc/os-release): CoreOS 1576.5.0
* Kernel (e.g. `uname -a`): 4.14.11-coreos
* Cloud provider or hardware configuration: Bare Metal
* Rook version (use `rook version` inside of a Rook Pod): v0.6.1
* Kubernetes version (use `kubectl version`): v1.9.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Vanilla
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): HEALTH_WARN, all active+clean

**Comment by lorenz** [comment]
Was an issue with not all API servers havin VolumeScheduling enabled

**Comment by FaKod** [comment]
@lorenz I assume you've enabled --feature-gates=VolumeScheduling=true for the API Servers and Kubelets?

**Comment by lorenz** [comment]
That was the issue, I have multiple masters and not all of them had it enabled on every service.
