### ISSUE TITLE
External script's mon connection info can break when external Ceph cluster has non-default ports

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#14330]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I will include some outputs from the environment where this issue was found. Please note that I have manually edited and sanitized some of the information to ensure it doesn't expose anything in the user's test environment.

The Ceph cluster's mon host looks like this (sanitized):
```
[global]
    mon host = [v2:192.168.1.1:44440,v1:192.168.1.1:44441],[v2:192.168.1.2:44440,v1:192.168.1.2:44441],[v2:192.168.1.3:44440,v1:192.168.1.3:44441]
```

When running the script, this is the output that's relevant for the mon connection (sanitized):
```
[
  {
    "name": "rook-ceph-mon-endpoints",
    "kind": "ConfigMap",
    "data": {
      "data": "c=192.168.1.3:44441",
      "maxMonId": "0",
      "mapping": "{}"
    }
  },
. . .
```

Of note, the single endpoint chosen is the v1 endpoint.

When Rook loads this ConfigMap, it translates to this `/var/lib/rook/<cluster-ns>/<cluster-ns>.conf` in the operator pod:
```
[global]
fsid                = SANITIZED-FSID
mon initial members = c
mon host            = [v2:192.168.1.3:3300,v1:192.168.1.3:44441]
 
[client.ocs]
keyring = /var/lib/rook/openshift-storage/client.ocs.keyring
```

Note that Rook has assumed port 3300 for the v2 port here.

When the Rook operator attempts to run `ceph version` (in code [here](https://github.com/rook/rook/blob/03d077aa6b82a8cbe12d672cd8b96602adb84598/pkg/daemon/ceph/client/upgrade.go#L45-L55)), it fails with a timeout. Presumably this is because the v2 port is incorrect.

I advised the user to update their ConfigMap with `c=[v2:192.168.1.3:44440,v1:192.168.1.3:44441]`, but this failed. I believe I may have gotten the configmap's data format wrong.

Ultimately, the user was able to resolve the issue by changing their Ceph cluster to use the default 6789 and 3300 ports.

**Expected behavior:**

It seems reasonable that Rook can't guarantee external Ceph clusters will use default ports. However, this seems like it must be a pretty rare install config since I don't think others have reported this issue.

It makes sense to me that the external script should be able to grab both v1 and v2 ports for one of the mons to use for the rook-ceph-mon-endpoints configmap so that the operator isn't assuming an incorrect v2 port in these cases.

**How to reproduce it (minimal and precise):**

1. Create a non-Rook Ceph cluster with non-default v1 and v2 mon ports. (This is a non-trivial task)
2. Run python import script.
3. Create resources the python import script specifies.
4. Create corresponding external mode CephCluster

**File(s) to submit**:
**Logs to submit**:

I don't have any other files or logs from the user environment other than the sanitized snippets posted above.

**Comment by parth-gr** [comment]
> It makes sense to me that the external script should be able to grab both v1 and v2 ports for one of the mons to use for the rook-ceph-mon-endpoints configmap so that the operator isn't assuming an incorrect v2 port in these cases.

We must make the python script here intelligent https://github.com/rook/rook/blob/master/deploy/examples/create-external-cluster-resources.py#L690 to grab the right ports.

Or,
Lets discuss what all combinations of mon endpoints are possible.

Will it always have v2 or v1??

**Comment by BlaineEXE** [comment]
In huddle we had some concerns that non-standard ports aren't tested to be supported in Rook's operator code either. Given the challenge devs would have setting up this condition to be tested, and given the clear rarity of the condition, we are deciding to close this as not planned at present. We can revisit this in the future if we need to.
