### ISSUE TITLE
Numerous Zombie Processes Created by Ceph OSD smartctl

### ISSUE THREAD

**Issue by Cookiery** [rook/rook#14344]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
There are zombie process on my machine and they were generated by this command (as shown).
![image](https://github.com/rook/rook/assets/33125275/091e7508-dc51-4cbc-90c4-fce7631310fe)

PPID Message:
![image](https://github.com/rook/rook/assets/33125275/4150b5fb-708c-4619-8281-7d1a42af7a01)

**Expected behavior:**
Ceph OSD should manage processes correctly, without creating zombie processes, thereby ensuring stable system performance.

**How to reproduce it (minimal and precise):**

I don't know how to reproduce it.

**Troubleshooting Attempts:**
- Restart of OSD services (temporary fix)
- System reboot (temporary fix)

No configuration changes have proven effective in addressing this issue long-term.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.4 LTS
* Kernel (e.g. `uname -a`): Linux pro-k8s-ceph12 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: hardware
* Rook version (use `rook version` inside of a Rook Pod): v1.8.3
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:29:16Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by sp98** [comment]
@rzarzynski Hi. Any idea why `ceph osd` command might be creating these zombie processes ?

**Comment by Cookiery** [comment]
@sp98 Thanks for your response. I'm not sure if the information I provided is complete. If you need any additional information, please feel free to contact me at any time.

**Comment by rzarzynski** [comment]
Redirecting the Q to @yaarith.

**Comment by sp98** [comment]
> @sp98 Thanks for your response. I'm not sure if the information I provided is complete. If you need any additional information, please feel free to contact me at any time.

@Cookiery At any point did you face `OSD flapping` issue?

**Comment by Cookiery** [comment]
@sp98 OSDs all available. 
![image](https://github.com/rook/rook/assets/33125275/9ae262c3-7f45-44a4-8576-beb00c51aacf)

**Comment by sp98** [comment]
Ok. So you mean there is OSD flapping that is happening in your cluster. Is that correct?  
If yes, then can you also confirm if you only see the zombie process when OSD flapping is happening and not when OSDs are working fine?  @Cookiery

**Comment by Cookiery** [comment]
I'm sorry, I don't know how to observe this behavior.

**Comment by sp98** [comment]
That's alright. Is it possible to try this on the latest rook-ceph version? I noticed that you are using quite an older version of Rook.

**Comment by Cookiery** [comment]
Sorry, upgrading is a big move, could we first find the problem before upgrading

**Comment by sp98** [comment]
In that case, I'll wait for @yaarith to respond

**Comment by Cookiery** [comment]
Thanks!!! @sp98

**Comment by yaarith** [comment]
Hi @Cookiery, can you please run this command:
`ps -eo pid,ppid,lstart,cmd |grep -e ceph -e smartctl`
the next time you see the zombies, and provide its output?

**Comment by Cookiery** [comment]
@yaarith Sure, here is the output
![image](https://github.com/rook/rook/assets/33125275/d9e80d18-67f5-4c16-b0e8-2171ef01559f)
![image](https://github.com/rook/rook/assets/33125275/aabc7eda-6723-48d5-8d54-6bb0ae063e77)
