### ISSUE TITLE
Support disks/dirs to be added or removed

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1435]
Is this a bug report or feature request?

* Feature Request

**Feature Request**

Are there any similar features already existing: #1101 was the implementation for adding/removing storage at then node level.

What should the feature do:  This feature would allow the user to update a cluster CRD to add and remove disks and directories.

What would be solved through this feature:  Storage resources will be dynamic in the cluster, meaning that the cluster can grow and shrink its capacity over time.

Does this have an impact on existing features: This feature depends on #1341

**Comment by jbw976** [comment]
For the case where a disk is completely dead, we can consider using the `ceph osd lost` command described here:
http://docs.ceph.com/docs/master/rados/troubleshooting/troubleshooting-pg/

**Comment by galexrt** [comment]
To note here, this in general means to add more dynamic to Rook in point of handling new/removed nodes.

Relates to at least: #2107.

**Comment by travisn** [comment]
Let's focus this issue on adding a disk to a running node. Some design points to consider:
- The operator would have a new goroutine that watches for a k8s event on a configmap that indicates a new device was added. The configmap is the one that we already have in the rook-ceph-system namespace that saves the devices detected on a node
- The discovery service should watch for a hardware event that a device was attached to the node (udev?) When the device is detected, the configmap of detected devices would be updated
- The operator would respond to the new device event by triggering a new orchestration. This would be done similarly to #2693 for handling of new nodes added to the cluster, perhaps even in the same goroutine if it makes sense to add it to the same `select` statement with a `watch`

**Comment by leseb** [comment]
I think the should replace bullet 2 with "call c-v inventory" and detect newly added drives. c-v is the source of truth here, it should be able to tell us if the disk that was added is usable or not and then we can take action. Sorta addressed by https://github.com/rook/rook/issues/2606

**Comment by travisn** [comment]
Agreed that c-v inventory should be the source of truth for available devices. And to be event driven, we will want to watch a hardware event of attaching the device so we don't need to poll frequently.

**Comment by leseb** [comment]
That also means we have to zap devices I suppose.

**Comment by noahdesu** [comment]
I'm assuming here that this should handle all of the crd `storage:` configurations such as `useAllDevices` and explicit device selection via filtering or the `devices:` list. I haven't dug into the exact mechanisms for how all this works, but if `c-v inventory` becomes the source of truth, then interestingly it would seem that the explicit `devices:` list also acts as a device filter.

**Comment by BlaineEXE** [comment]
@travis Is this work accomplished in #2936?

**Comment by travisn** [comment]
#2946 I would expect to cover these scenarios for add/remove of devices and triggering the orchestration. #2946 won't change the behavior about which devices are added/removed, but will essentially remove the need to restart the operator to pick up new devices.
