### ISSUE TITLE
Development environement sets docker-env for multi node deployments

### ISSUE THREAD

**Issue by NymanRobin** [rook/rook#14352]
Small notice I did while testing/developing some multi node features is that the `create-dev-env.sh` script sets the following command `eval "$($MINIKUBE docker-env)" ` even when you specify a `MINIKUBE_NODES` as a bigger variable than 1.

This does not work and will result in following error
```
❌  Exiting due to ENV_MULTINODE_CONFLICT: The docker-env command is incompatible with multi-node clusters. Use the 'registry' add-on: https://minikube.sigs.k8s.io/docs/handbook/registry/
```
This is just a minor inconvenience, but ideally the script could start a local kube-registry instead as this is need for local development when using the multi-node envs. Also the document could be updated to show how to push images to the local registry and use that for development.

**Comment by parth-gr** [comment]
I think we should use `--driver kvm2`

**Comment by NymanRobin** [comment]
Sorry @parth-gr, I did not fully catch this, I believe I'm using the KVM2 virtualization, but I think this error can occur with all drivers or did I miss something? I thought the error happened because each node has its own Docker runtime, making it "impossible" to select just one. If you need to build a custom image, you would need to build it on all nodes, but instead what you can do is enable the 'registry' add-on as the error message recommends and then push images through there and then the docker runtimes on the nodes can pull images from there

**Comment by NymanRobin** [comment]
I opened a PR for this @parth-gr to better demonstrate what I was after :smile:

**Comment by NymanRobin** [comment]
The registry is not needed as pointed out by @subhamkrai, the details can be seen in the attached PR!
