### ISSUE TITLE
benchmarking OSD disk.

### ISSUE THREAD

**Issue by palthisailohith** [rook/rook#14366]
Hi team,

Issue Description:
On a particluar node we are seeing high cpu utilization for OSDs than other node OSDs. We want to benchmark the disks on the particular node using fio tool.
Environment:
Kubernetes version: v1.25.9
Rook version: v1.10.8
Ceph version: v17.2.5
Details:
The question here is when we do benchmarking for the disks on which OSD's are already present in the ceph cluster using fio,does it cause any issues to the existing data or does it corrupts the existing data? How can we safely do benchmarking without disturbing the existing data.
Are there any other tools for doing the same?  and could you please provide steps to safely approach benchmarking the disks that are already present in ceph.

Steps to Reproduce:

1. Created a fio job file as following:
`[global]
ioengine=libaio
direct=1
rw=randwrite  # or randread for read tests, or readwrite for mixed tests
bs=4k         # block size
size=10G      # test file size
numjobs=1     # number of parallel jobs
runtime=60    # duration in seconds
group_reporting
 
[osd-disk-benchmark]
filename=/dev/sdd  # replace /dev/sd with your actual disk device`
2. Then using fio tool ran the above file.
Performed the above testing on test servers.

Is the above is correct and safe method to follow or does it cause any problems to the existing data? Or do you suggest any other tools to do the same.

Thank you!

**Comment by sp98** [comment]
Not sure if doing benchmark tests on OSDs with existing data is good idea. 
@shekharberry any suggestions of this?
