### ISSUE TITLE
OSD crash-looping after node reboot

### ISSUE THREAD

**Issue by bitfisher** [rook/rook#14363]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSD is crash-looping after node reboot.

`activate` fails because the wrong `DEVICE` is set.

`/dev/sde` was the correct device before reboot, but now is `/dev/sdd`!

should be `/dev/disk/by-id/scsi-350000f007424edf0` instead of `/dev/sd...`!?

* Workaround:
Delete OSD Deployment and let operator recreate a new one (operator restart needed)

**Expected behavior:**
OSD running after node reboot and correct device activated.

* Cluster CR (storage part)
`Host Storage Cluster` with `dataDirHostPath: /var/lib/rook`

```yaml
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "node-1"
        devices:
          - name: "/dev/disk/by-id/scsi-350000f0b0187f1f0"
          - name: "/dev/disk/by-id/scsi-350000f0b0187f1e0"
          - name: "/dev/disk/by-id/scsi-350000f0b0187f1d0"
          - name: "/dev/disk/by-id/scsi-350000f0003c09ab0"
      - name: "node-2"
        devices:
          - name: "/dev/disk/by-id/scsi-350000f0b0187e5b0"
          - name: "/dev/disk/by-id/scsi-350000f0b0187e6f0"
          - name: "/dev/disk/by-id/scsi-350000f0b0187e010"
          - name: "/dev/disk/by-id/scsi-350000f007424edf0"
      - name: "node-3"
        devices:
          - name: "/dev/disk/by-id/scsi-350000f0b0187f1c0"
          - name: "/dev/disk/by-id/scsi-350000f0b0187e720"
          - name: "/dev/disk/by-id/scsi-350000f0b0187e710"
          - name: "/dev/disk/by-id/scsi-350000f007424ee00"
```

**Logs to submit**:

* OSD activate log
```	
+ OSD_ID=21
+ CEPH_FSID=555a9fcd-...
+ OSD_UUID=425d3bb9-...
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-21
+ CV_MODE=raw
+ DEVICE=/dev/sde
+ cp --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf
+ python3 -c '
import configparser
config = configparser.ConfigParser()
config.read('\''/etc/ceph/ceph.conf'\'')
if not config.has_section('\''global'\''):
    config['\''global'\''] = {}
if not config.has_option('\''global'\'','\''fsid'\''):
    config['\''global'\'']['\''fsid'\''] = '\''555a9fcd-...'\''
with open('\''/etc/ceph/ceph.conf'\'', '\''w'\'') as configfile:
    config.write(configfile)
'
+ ceph -n client.admin auth get-or-create osd.21 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
[osd.21]
	key = ...
+ [[ raw == \l\v\m ]]
++ mktemp
+ OSD_LIST=/tmp/tmp.SRhTD7LJXV
+ ceph-volume raw list /dev/sde
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 41, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 174, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 130, in list
    report = self.generate(args.device)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 99, in generate
    info_devices.append(disk.lsblk(dev, abspath=True))
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 245, in lsblk
    abspath=abspath)
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 337, in lsblk_all
    raise RuntimeError(f"Error: {err}")
RuntimeError: Error: []
```

*`node-2` -> `ls -l /dev/disk/by-id/scsi-350000f0*`:
```
/dev/disk/by-id/scsi-350000f007424edf0 -> ../../sdd
/dev/disk/by-id/scsi-350000f0b0187e010 -> ../../sdc
/dev/disk/by-id/scsi-350000f0b0187e5b0 -> ../../sdb
/dev/disk/by-id/scsi-350000f0b0187e6f0 -> ../../sda
```
*`node-2` -> `lsblk -Adf -o NAME,SIZE,TYPE,FSTYPE,FSVER`:
```
NAME  SIZE TYPE FSTYPE      FSVER
sda   1.7T disk LVM2_member LVM2 001
sdb   1.7T disk LVM2_member LVM2 001
sdc   1.7T disk LVM2_member LVM2 001
sdd   3.5T disk             
sdf   2.2T disk             
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Fedora Linux"
VERSION="40.20240602.3.0 (CoreOS)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora CoreOS 40.20240602.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='40.20240602.3.0'
```
* Kernel (e.g. `uname -a`):
`Linux node-2 6.8.11-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 27 14:53:33 UTC 2024 x86_64 GNU/Linux`
* Rook version (use `rook version` inside of a Rook Pod):
`v1.14.6`
* Storage backend version (e.g. for ceph do `ceph -v`):
`quay.io/ceph/ceph:v18.2.2-20240529`
* Kubernetes version (use `kubectl version`):
`v1.28.10`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
`Baremetal`

---

Why is `activate` using `/dev/sde` instead of `/dev/disk/by-id/scsi-350000f007424edf0` as specified in storage section of `node-2`?

**Comment by bitfisher** [comment]
Maybe related to #13564

**Comment by sp98** [comment]
@bitfisher Help me understand the issue better. 

So initially the OSD.21 was set to `/dev/disk/by-id/scsi-350000f007424edf0` which was `sde` and after node reboot the OSD is pointing to `sdd` instead of `sde`.  Is that understanding correct. 

But `/dev/disk/by-id/scsi-350000f007424edf0` is pointing to `sdd` in the description above (`/dev/disk/by-id/scsi-350000f007424edf0 -> ../../sdd`).   Was it pointing to `sde` before node reboot ?

**Comment by bitfisher** [comment]
Hi @sp98 !

OSD.21 was set to `/dev/sde` although storage config was set to `/dev/disk/by-id/scsi-350000f007424edf0`.

`/dev/disk/by-id/scsi-350000f007424edf0` pointed to `/dev/sde`.

After node reboot `/dev/disk/by-id/scsi-350000f007424edf0` points to `/dev/sdd`.

**Comment by sp98** [comment]
Got it.  [This](https://github.com/rook/rook/issues/13564#issuecomment-2186152731) might be the root cause.  I think you just delete the OSD deployment and restart the rook operator. The operator will create a new deployment and this time the `ROOK_BLOCK_PATH` value would be correct.

**Comment by bitfisher** [comment]
This is exactly what i did, to solve this issue!

delete OSD deployment -> restart rook operator -> operator recreates OSD deployment with `ROOK_BLOCK_PATH` correctly set

**Comment by sp98** [comment]
> This is exactly what i did, to solve this issue!
> 
> delete OSD deployment -> restart rook operator -> operator recreates OSD deployment with `ROOK_BLOCK_PATH` correctly set

Ah! right. I missed that in the description above.
