### ISSUE TITLE
When you delete a cluster, the configmap `rook-ceph-osd-orchestration-status` and service  `rook-ceph-mgr` are not deleted

### ISSUE THREAD

**Issue by kokhang** [rook/rook#1438]
When deleting a cluster, the configmap `rook-ceph-osd-orchestration-status` and service  `rook-ceph-mgr` are not deleted.

The issue with the `rook-ceph-osd-orchestration-status` configmap not being deleted is that the rook-operator, upon cluster creation, will wait for the old osd status to update.

So i get a bunch of:
`op-osd: waiting on orchestration status update from node 172.17.4.101`

**Comment by kokhang** [comment]
Also the dataDirHostPath needs to be deleted. I know we are trying to leverage localvolume but for now can we deleted when a cluster is deleted. This can be done by listening to the TERM signal. This is currently done in the rook-agent. Rook-agent will delete the driver executeble from the host when the rook-agent pod is deleted. https://github.com/rook/rook/blob/master/pkg/daemon/agent/flexvolume/server.go#L116

**Comment by travisn** [comment]
how can the pod tell the difference between stopping and restaring, and when the user really wants to destroy the cluster? We can't delete the `dataDirHostPath` unless we know the user really wants to destroy the cluster

**Comment by kokhang** [comment]
When the user does delete the `cluster` doesnt that imply destroying the cluster and thus deleting the `dataDirHostPath`. I guess apart from checking the SIGTERM, we can check whether the cluster object is deleted.

**Comment by travisn** [comment]
the operator is aware of the cluster deletion, but the  mon and osd pods are the ones that are using the dataDirHostPath. The would require some communication between the operator and mon/osd pods to signal the deletion.

**Comment by kokhang** [comment]
Couldnt the mon or osd pod, when they get the SIGTERM, check if the cluster CRD exists? And if it doesnt exist, then it is safe to assume the user wants to destroy the cluster and thus it should delete the `dataDirHostPath`?

**Comment by travisn** [comment]
is it worth trying to get that right before we just switch to local volumes? that would also require more RBAC privileges in the mon/osd pods. Not likely a big deal, but it seems like a short term problem that already will have a solution.

**Comment by kokhang** [comment]
I want to be able to do `kubectl -n rook delete cluster rook` and then do `kubectl create -f rook-cluster.yaml`

I am not sure when LocalVolume will be on by default. Hopefully 1.10.

**Comment by kokhang** [comment]
i also noticed that if i bring up OSDs with specific directories (and different than the `dataDirHostPath`, i have to manually delete those as well.

**Comment by steven-sheehy** [comment]
I've noticed most of the [common problems](https://rook.io/docs/rook/master/common-problems.html) have a solution as delete the dataDirHostPath. This was a definite pain point for me during testing.

How about making the delete dataDirHostPath a configuration option on the Cluster? It could be similar to the volume [Reclaim Policy](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaim-policy). By default it could be retain since not losing production data is a sane default, with delete an option to solve the above.

**Comment by travisn** [comment]
Will track the dataDirHostPath cleanup question with #1490 and resolve the original intent of this issue with #1489

**Comment by MrAmbiG** [comment]
The same issuer persists as of today.

**Comment by BlaineEXE** [comment]
> The same issuer persists as of today.

Can you be a little more specific about this? Which version of Rook are you using? What resources are still remaining upon deletion?
