### ISSUE TITLE
govulncheck ci is failing

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#14388]
**Is this a bug report or feature request?**
* Bug Report

```
=== Symbol Results ===

Vulnerability #1: GO-2024-2947
    Leak of sensitive information to log files in
    github.com/hashicorp/go-retryablehttp
  More info: https://pkg.go.dev/vuln/GO-2024-2947
  Module: github.com/hashicorp/go-retryablehttp
    Found in: github.com/hashicorp/go-retryablehttp@v0.7.6
    Fixed in: github.com/hashicorp/go-retryablehttp@v0.7.7
    Example traces found:
Error:       #1: pkg/daemon/ceph/osd/kms/kms.go:287:30: kms.Config.DeleteSecret calls keyprotect.Client.DeleteKey, which eventually calls retryablehttp.Client.Do

Your code is affected by 1 vulnerability from 1 module.
This scan also found 0 vulnerabilities in packages you import and 1
vulnerability in modules you require, but your code doesn't appear to call these
vulnerabilities.
Use '-show verbose' for more details.
Error: Process completed with exit code 3.

```

https://github.com/rook/rook/actions/runs/9678931956/job/26707009523?pr=14353

**Deviation from expected behavior:**

CI should be working

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment]
@subhamkrai its failing again,
```
Vulnerability #1: GO-2024-2963
    Denial of service due to improper 100-continue handling in net/http
  More info: https://pkg.go.dev/vuln/GO-2024-2963
  Standard library
    Found in: net/http@go1.22.4
    Fixed in: net/http@go1.22.5
    Example traces found:
Error:       #1: pkg/daemon/ceph/osd/kms/kms.go:287:30: kms.Config.DeleteSecret calls keyprotect.Client.DeleteKey, which eventually calls http.Client.CloseIdleConnections
Error:       #2: pkg/operator/ceph/object/admin.go:79:26: object.debugHTTPClient.Do calls http.Client.Do
Error:       #3: tests/framework/installer/settings.go:64:27: installer.readManifestFromURL calls http.Get
Error:       #4: pkg/operator/ceph/object/admin.go:72:38: object.debugHTTPClient.Do calls httputil.DumpRequestOut, which calls http.Transport.CloseIdleConnections
Error:       #5: pkg/operator/ceph/object/admin.go:72:38: object.debugHTTPClient.Do calls httputil.DumpRequestOut, which calls http.Transport.RoundTrip

Your code is affected by 1 vulnerability from the Go standard library.
This scan also found 0 vulnerabilities in packages you import and 1
vulnerability in modules you require, but your code doesn't appear to call these
vulnerabilities.
Use '-show verbose' for more details.
```

https://github.com/rook/rook/actions/runs/9774439878/job/26982696030?pr=14396

**Comment by subhamkrai** [comment]
need specific go 1.22.5 version

**Comment by subhamkrai** [comment]
https://github.com/rook/rook/pull/14412 will fix this
