### ISSUE TITLE
CSI Bucket Provisioner fails when RGW is using a cert signed by a non-trusted CA

### ISSUE THREAD

**Issue by logan2211** [rook/rook#14393]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Bucket provisioner fails to provision buckets

**Expected behavior:**
The operator should allow a way to specify a secret & key containing the CA trust.

**How to reproduce it (minimal and precise):**

Create a RGW gateway using a cert signed by a local CA or self signed cert, create an objectbucketclaim, watch the failure in the operator log

**Logs to submit**:
```
error provisioning bucket: Provision: can't create ceph user: failed to get ceph user "obc-test-test-3fbba252-badd-4391-82fc-c4d14fbb2a5c": Get "https://rook-ceph-rgw-ceph-rgw.rook-ceph.svc:443/admin/user?format=json&uid=obc-test-test-3fbba252-badd-4391-82fc-c4d14fbb2a5c": tls: failed to verify certificate: x509: certificate signed by unknown authority, requeuing
```

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v1.14.7
* Kubernetes version (use `kubectl version`): 1.30.1

**Comment by logan2211** [comment]
I was able to resolve the trust issue by injecting my cluster CA to the operator deployment using https://github.com/microcumulus/ca-injector

**Comment by BlaineEXE** [comment]
Thanks for posting the solution, @logan2211 !

CephObjectStore also supports mounting the certificate via `sslCertificateRef` and `caBundleRef`: https://rook.io/docs/rook/latest-release/CRDs/Object-Storage/ceph-object-store-crd/#gateway-settings

**Comment by logan2211** [comment]
Yes, that will configure the gateway to serve using these certs. Unfortunately there is no configuration (that I have found) which causes the operator to trust a CA cert that the RGW gateway might be using. So if a non-public CA is used for the gateways, bucket provisioning fails with the error I gave because the operator does not trust the CA.

**Comment by BlaineEXE** [comment]
Ah, I see the issue here clearly now. The CA injector is a good tool for this, yes. Thanks for clarifying.
