### ISSUE TITLE
Ceph rgw does not report ceph_version prometheus labels

### ISSUE THREAD

**Issue by aplufr** [rook/rook#14395]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Looking at the metrics exported by ceph exporter to prometheus on `ceph_rgw_metadata` there is a label named `ceph_version` with the value `None`.

**Expected behavior:**
Prometheus label should provide the version of rgw as reported by `ceph versions` (like we have for other `ceph_*_metadata` metrics)

**How to reproduce it (minimal and precise):**

Install a rook cluster and a prometheus/grafana stack, add required annotation/labels to have ceph exporting metrics to prometheus stack

**File(s) to submit**:

Helm configuration for rook cluster (for prometheus)
```
monitoring:
  enabled: true
  createPrometheusRules: true
  prometheusRule:
    labels:
      release: prometheus-prod-ng
    annotations: {}
```

Example of metrics reported for osd metadata vs rgw

```
ceph_osd_metadata{__env="prod-ng",ceph_daemon="osd.0",ceph_version="ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)",cluster_addr="100.67.0.99",container="mgr",device_class="hdd",endpoint="http-metrics",hostname="fr0-dlabcpu-p07",instance="100.67.4.70:9283",job="rook-ceph-mgr",namespace="rook-ceph-prod",objectstore="bluestore",pod="rook-ceph-mgr-b-6d47458d67-f5sgm",prometheus="monitoring/prometheus-prod-ng-prometheus",prometheus_replica="prometheus-prometheus-prod-ng-prometheus-0",public_addr="100.67.0.99",receive="true",service="rook-ceph-mgr",tenant_id="default-tenant"}
ceph_rgw_metadata{__env="prod-ng",ceph_daemon="rgw.ceph-objectstore",ceph_version="None",container="mgr",endpoint="http-metrics",hostname="fr0-dlabcpu-p06",instance="100.67.4.70:9283",instance_id="ceph-objectstore",job="rook-ceph-mgr",namespace="rook-ceph-prod",pod="rook-ceph-mgr-b-6d47458d67-f5sgm",prometheus="monitoring/prometheus-prod-ng-prometheus",prometheus_replica="prometheus-prometheus-prod-ng-prometheus-0",receive="true",service="rook-ceph-mgr",tenant_id="default-tenant"}
```

**Environment**:
* OS (e.g. from /etc/os-release): RHEL8.9
* Kernel (e.g. `uname -a`):  Linux fr0-dlabcpu-p18  4.18.0-513.18.1.el8_9.x86_64 #1 SMP Thu Feb 1 03:51:05 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:  Cluster installed onpremise (about ~10 physicals servers)
* Rook version (use `rook version` inside of a Rook Pod): 1.14.6
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)
* Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.11+rke2r1", GitCommit:"3cd242c51317aed8858119529ccab22079f523b1", GitTreeState:"clean", BuildDate:"2023-11-15T21:08:55Z", GoVersion:"go1.20.11 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher Prime RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by rkachach** [comment]
@BlaineEXE I didn't had the time to investigate this in depth but as far as I remember this information comes from the `list_daemons` call  which is handled by the rook orchestrator module. So I'd say yes, that would require a fix in Ceph code side.
