### ISSUE TITLE
Have operator choose sane defaults for PGs based on environment

### ISSUE THREAD

**Issue by patrickstjohn** [rook/rook#1439]
Is this a bug report or feature request?

* Feature Request

**Feature Request**

Are there any similar issues already existing: #1329

What should the feature do: Choose sane-defaults for PGs based on environment and update based on environment.

What would be solved through this feature: Operator understanding the environment and putting best-practices in place. This should obviously be something that could be overridden in the event you know what you're doing. Prior to manually changing this in our environment there was the too few PGs per OSD warning as described in #1329 .

Does this have an impact on existing features: Unknown

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.3
* Kernel (e.g. `uname -a`): 4.4.113-1.el7.elrepo.x86_64
* Rook version (use `rook version` inside of a Rook Pod): v0.6.0-90.g54bb616
* Kubernetes version (use `kubectl version`): 1.8.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

```
  cluster:
    id:     e8ac6d0a-81a8-4dbe-8f57-526fc875e19a
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon2,rook-ceph-mon0,rook-ceph-mon1
    mgr: rook-ceph-mgr0(active), standbys: rook-ceph-mgr1
    mds: myfs-1/1/1 up  {0=mnkw8c=up:active}, 1 up:standby-replay
    osd: 54 osds: 54 up, 54 in
 
  data:
    pools:   3 pools, 1820 pgs
    objects: 23427 objects, 37692 MB
    usage:   160 GB used, 90319 GB / 90480 GB avail
    pgs:     1820 active+clean
```

**Comment by galexrt** [comment]
This seems to be a duplicate of https://github.com/rook/rook/issues/1191. @patrickstjohn What do you think?

**Comment by patrickstjohn** [comment]
@galexrt absolutely, apologies for missing it in my initial run-through. Count this as another vote for #1191 and I'll close this.
