### ISSUE TITLE
rook status command formatting

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#144]
This isn't a big request but the "lines" in the rook status command move around.  That is the output formatting is not stable.

For example sometimes I see:
> PLACEMENT GROUPS (2048 total):
> STATE                COUNT
> active+clean         1664
> stale+active+clean   384

and other times I see:

> PLACEMENT GROUPS (2048 total):
STATE                COUNT
stale+active+clean   384
active+clean         1664

It would be great if these always cam out in the same order in case someone tries to parse it.

(Related: The "node ls" command has no ordering although I can see how it might be OK the way it is).

**Comment by travisn** [comment]
`rookctl` is not a mainline scenario anymore so doesn't seem like we should worry about this
