### ISSUE TITLE
Klog doesnot able to create log file in Openshift

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#14400]
**Is this a bug report or feature request?**
* Bug Report

Used datadirectory host path
```
[rider@localhost ~]$ oc logs csi-rbdplugin-provisioner-7f58dcf85f-p47jv -c csi-rbdplugin
I0701 10:57:50.398044       1 cephcsi.go:191] Driver version: release-4.16 and Git version: 46e4e3fa82a32e2f0fbd74544c1f4b1ccd23c3ee
I0701 10:57:50.398044       1 cephcsi.go:191] Driver version: release-4.16 and Git version: 46e4e3fa82a32e2f0fbd74544c1f4b1ccd23c3ee
log: exiting because of error: log: unable to create log: open /var/lib/rook/cephcsi/log/rbd-provisioner/csi-rbdplugin.log: permission denied
[rider@localhost ~]$ 
[rider@localhost ~]$ oc get cephcluster
NAME                             DATADIRHOSTPATH   MONCOUNT   AGE   PHASE   MESSAGE                        HEALTH      EXTERNAL   FSID
ocs-storagecluster-cephcluster   /var/lib/rook     3          11d   Ready   Cluster created successfully   HEALTH_OK              c0c45dcc-58f7-4919-a7b4-759dfba7d27e
[rider@localhost ~]$ 


```

Used ceph log directory
```
log: exiting because of error: log: unable to create log: open /var/log/ceph/cephcsi/openshift-storage/cephcsi/log/rbd-provisioner/csi-rbdplugin.log: permission denied
[rider@localhost external-resizer]$ 
[rider@localhost external-resizer]$ 
[rider@localhost external-resizer]$ 
```

**Deviation from expected behavior:**

In minikube the file and directory was created, looks like in openshift we need provide some special permissions.
I think it is related to scc's

**Expected behavior:**

File creation should be successful

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment]
@Madhu-1 @subhamkrai @iamniting @BlaineEXE any thoughts on this?

**Comment by Madhu-1** [comment]
This looks to be an access problem, can you check do we need to have privileged access to write to hostPath in OCP? and also check user inside the container and SCC

**Comment by parth-gr** [comment]
SO the pod container has the srvice account attached, and that service account is attached to  scc, 
So something missing here
```
[rider@localhost ~]$ oc get scc rook-ceph-csi -o yaml
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- SYS_ADMIN
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  creationTimestamp: "2024-06-20T07:23:54Z"
  generation: 1
  managedFields:
  - apiVersion: security.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:allowHostDirVolumePlugin: {}
      f:allowHostIPC: {}
      f:allowHostNetwork: {}
      f:allowHostPID: {}
      f:allowHostPorts: {}
      f:allowPrivilegedContainer: {}
      f:allowedCapabilities: {}
      f:defaultAddCapabilities: {}
      f:fsGroup:
        .: {}
        f:type: {}
      f:groups: {}
      f:priority: {}
      f:readOnlyRootFilesystem: {}
      f:requiredDropCapabilities: {}
      f:runAsUser:
        .: {}
        f:type: {}
      f:seLinuxContext:
        .: {}
        f:type: {}
      f:supplementalGroups:
        .: {}
        f:type: {}
      f:users: {}
      f:volumes: {}
    manager: ocs-operator
    operation: Update
    time: "2024-07-01T11:36:05Z"
  name: rook-ceph-csi
  resourceVersion: "9050258"
  uid: 325c6c77-b475-4340-b49d-d4020e7518e8
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:openshift-storage:rook-csi-rbd-plugin-sa
- system:serviceaccount:openshift-storage:rook-csi-rbd-provisioner-sa
- system:serviceaccount:openshift-storage:rook-csi-cephfs-plugin-sa
- system:serviceaccount:openshift-storage:rook-csi-cephfs-provisioner-sa
- system:serviceaccount:openshift-storage:rook-csi-nfs-plugin-sa
- system:serviceaccount:openshift-storage:rook-csi-nfs-provisioner-sa
volumes:
- configMap
- emptyDir
- hostPath
- projected
[rider@localhost ~]$ 


```

**Comment by Madhu-1** [comment]
SCC is last concern we need to check below

can you check do we need to have privileged access to write to hostPath in OCP? and also check the user inside the container

**Comment by parth-gr** [comment]
Yes we need the privileged access,
Adding sc to the container worked 
```
securityContext:
      privileged: true
```
https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/using_hostpath.html

**Comment by parth-gr** [comment]
So this should be added by ODF???

**Comment by iamniting** [comment]
> So this should be added by ODF???

We should have a mechanism to enable this feature if we don't want it to be active by default. Then, we can use arguments via ODF to activate it.

**Comment by parth-gr** [comment]
@Madhu-1 @iamniting special thing is it is only required for deployment and daemons wont need it

**Comment by BlaineEXE** [comment]
We may need to set privileged based on the operator config `ROOK_HOSTPATH_REQUIRES_PRIVILEGED`

**Comment by parth-gr** [comment]
I see we don't have this set to csi container spec https://github.com/search?q=repo%3Arook%2Frook%20PodSecurityContext&type=code , so probably we should have it added to csi deployments
