### ISSUE TITLE
Rook should create unique cluster-id services 

### ISSUE THREAD

**Issue by salkin** [rook/rook#14403]
* Bug Report

**Deviation from expected behavior:**
When creating rook-ceph cluster with own namespace, to get unique cluster-id for beeing able to enable multicluster feature there should be unique service names created for the rook-ceph-mon-X and rook-ceph-osd-X services such that when using MCS (MultiClusterService) API the services should be unique in order to not have the MCS controller to merge the two different Rook-ceph services into a single service when the clusters to be mirrored are both created using rook-ceph.

**Expected behavior:**

When creating the rook-ceph with it's own namespace == clusterID the clusters services should also be unique:

**How to reproduce it (minimal and precise):**
By creating a cluster in it's own namespace and own name, still the mon is created with rook-ceph-mon-a. This causes issue when multicluster is enabled that both rook-ceph clusters mons if named rook-ceph-mon-a becomes available behind the same service name over the clusterset domain.

``` 
nwikgrn2-mgmt-pod-0:/# kubectl get cephcluster -n nwikgrn2
NAME       DATADIRHOSTPATH   MONCOUNT   AGE    PHASE   MESSAGE                        HEALTH        EXTERNAL   FSID
nwikgrn2   /var/lib/rook     1          6m5s   Ready   Cluster created successfully   HEALTH_WARN              c7d81845-ce53-4e86-9d05-1c5a7d1e7800
nwikgrn2-mgmt-pod-0:/# kubectl get svc -n nwikgrn2
NAME              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
rook-ceph-mgr     ClusterIP   10.3.178.91   <none>        9283/TCP            5m14s
rook-ceph-mon-a   ClusterIP   10.3.139.69   <none>        6789/TCP,3300/TCP   6m
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

**Cluster Status to submit**:

NAME       DATADIRHOSTPATH   MONCOUNT   AGE   PHASE   MESSAGE                        HEALTH        EXTERNAL   FSID
nwikgrn2   /var/lib/rook     1          18m   Ready   Cluster created successfully   HEALTH_WARN              c7d81845-ce53-4e86-9d05-1c5a7d1e7800

* Output of kubectl commands, if necessary

**Environment**:
* Talos 1.7.4
* Kernel: Linux 6.1.82-talos 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
 sh-4.4$ rook version
rook: v1.12.11
go: go1.21.6

* Storage backend version (e.g. for ceph do `ceph -v`):
sh-4.4$ ceph -v
ceph version 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)

* Kubernetes version (use `kubectl version`):
kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3

**Comment by travisn** [comment]
Services are expected to be unique across the cluster by combining the namespace in the fully qualified service name `<name>.<namespace>` as described [here](https://kubernetes.io/docs/concepts/services-networking/service/#dns). MCS must be able to take that into account, otherwise there must be common conflicts other than this rook scenario. A service is a namespaced resource, so it doesn't make sense to treat it as a cluster-wide resource. @sp98 thoughts?

**Comment by salkin** [comment]
right of course my bad. I was stuck in the thinking of the service name as I had my clusters created with same namespace name. Sorry for confusion.
