### ISSUE TITLE
The deletion of a file does not immediately remove its data in ceph PVC

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#14402]
The issue you're experiencing with the Ceph storage persistent volume, where deleting folders takes much longer than moving them

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v16.10.8
* Storage backend version (e.g. for ceph do `ceph -v`): v8.1.1
* Kubernetes version (use `kubectl version`): v23.5.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by vadlakiran** [comment]
@Rakshith-R  can we have update on this, its simple rm -rf we are doing it on pvc which backend storage is ceph

**Comment by Rakshith-R** [comment]
Ceph PVC can refer to rbd, cephfs or even nfs PVC.

Please mention which kind of PVC you are using.

If it is RBD, then refer to https://github.com/rook/rook/issues/10391 .

Please try to search for similar issues before opening a new one.

**Comment by vadlakiran** [comment]
@Rakshith-R  this is  not nfs pvc, we have cephfs and we just created pvc , its not a RBD, i have searched it but did not find any doc or issue

**Comment by Rakshith-R** [comment]
> @Rakshith-R this is not nfs pvc, we have cephfs and we just created pvc , its not a RBD, i have searched it but did not find any doc or issue

I am not aware of any cephfs folder deletion delays. 
I do know that if the folder has a large number of files/folder then cephfs is a bit slow due to all the metadata operations.

Please ask your question on https://ceph.io/en/community/connect/ ceph mailing list or ceph slack for hopefully a better answer.
