### ISSUE TITLE
Set priority class of ceph exporter pods with helm

### ISSUE THREAD

**Issue by KKonak** [rook/rook#14419]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Set priority class for the ceph exporter pod in helm chart values, like it can be done for [all other resources](https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#priority-class-names): monitor, osd, manager, and crash collector pods. 

**What is use case behind this feature:**
Setting priority for ceph exporter pods, they arent necessary so I want to set them to low priority. Additionally for my own use case all pods need a priority class to be admitted by OPA policy.

**Environment**:

Rook 1.14.3
Ceph 18.2
K8S 1.24

**Comment by travisn** [comment]
@KKonak It should be possible today. Did you try this? The `exporter` key should allow you to define it, something like this:
```yaml
  cephClusterSpec:
    priorityClassNames:
      exporter: system-node-critical
```

**Comment by KKonak** [comment]
I gave that a shot and it worked! I didn't see it defined in the docs so I wasn't sure if it was possible. Thanks for the reply!
