### ISSUE TITLE
Upgrade go version 1.22 doesnt work locally

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#14424]
**Is this a bug report or feature request?**
* Bug Report

Try running `make build`
```
[root@localhost rook]# make build
build/makelib/golang.mk:27: *** please set GO_STATIC_PACKAGES prior to including golang.mk.  Stop.
[root@localhost rook]# 
[root@localhost rook]# 
```

added GO_STATIC_PACKAGES to static value, then

```
[root@localhost rook]# make build
build/makelib/golang.mk:27: *** please set GO_STATIC_PACKAGES prior to including golang.mk.  Stop.
[root@localhost rook]# make build
=== helm package rook-ceph
==> Linting /home/rider/go/src/github.com/rook/rook/_output/rook-ceph

1 chart(s) linted, 0 chart(s) failed
Successfully packaged chart and saved it to: /home/rider/go/src/github.com/rook/rook/_output/charts/rook-ceph-v1.14.0-alpha.0.237.gfe3be82bc-dirty.tgz
=== helm package rook-ceph-cluster
==> Linting /home/rider/go/src/github.com/rook/rook/_output/rook-ceph-cluster

1 chart(s) linted, 0 chart(s) failed
Successfully packaged chart and saved it to: /home/rider/go/src/github.com/rook/rook/_output/charts/rook-ceph-cluster-v1.14.0-alpha.0.237.gfe3be82bc-dirty.tgz
=== helm index

=== syncing root modules with APIs modules
=== ensuring APIs modules are tidied
=== ensuring root modules are tidied
Updating CRD manifests
Generating ceph crds
-: # runtime/cgo
In file included from /usr/include/features.h:489,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdlib.h:25,
                 from _cgo_export.c:3:
/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
    7 | # include <gnu/stubs-32.h>
      |           ^~~~~~~~~~~~~~~~
compilation terminated.
Error: not all generators ran successfully
run `controller-gen crd:maxDescLen=-1,generateEmbeddedObjectMeta=true,allowDangerousTypes=true paths=./pkg/apis/ceph.rook.io/v1 output:crd:artifacts:config=/home/rider/go/src/github.com/rook/rook/deploy/olm/deploy/crds -w` to see all available markers, or `controller-gen crd:maxDescLen=-1,generateEmbeddedObjectMeta=true,allowDangerousTypes=true paths=./pkg/apis/ceph.rook.io/v1 output:crd:artifacts:config=/home/rider/go/src/github.com/rook/rook/deploy/olm/deploy/crds -h` for usage
make: *** [Makefile:186: crds] Error 1
[root@localhost rook]# 
[root@localhost rook]# 

```

**Deviation from expected behavior:**

Failure in building image, please verify @subhamkrai @travisn 

**Expected behavior:**

Make build should run fine locally

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
This seems like an environment issue, perhaps not related to go 1.22. If you revert back to 1.21, are you able to build (e.g. the release-1.14 branch that doesn't require 1.22)?

**Comment by sp98** [comment]
@parth-gr Where are you trying to build this? Mac?

**Comment by parth-gr** [comment]
It worked, i downloaded the wrong linux arch go binary
