### ISSUE TITLE
Ceph OSD daemon crash.

### ISSUE THREAD

**Issue by palthisailohith** [rook/rook#14426]
Hi team,

Issue Description:
We are seeing  OSD daemon crashes several times in a row.
Environment:
Kubernetes version: v1.25.9
Rook version: v1.10.8
Ceph version: v17.2.5
Below is one of the log we captured:
Bad crc in data.

What can be the reason,is there any way we can prevent this issue?
Thankyou.

**Comment by travisn** [comment]
`Bad crc in data` --> This may indicate an issue with a bad disk or otherwise corrupt data. If the OSD won't start, you many need to [replace the OSD](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-osd-mgmt/#remove-an-osd).

> What can be the reason,is there any way we can prevent this issue?

Do you have consistent repro steps? There isn't enough info to help troubleshoot.

**Comment by palthisailohith** [comment]
It is not reproducible,we are facing OSD crashes.
Below are some more logs during the crashes:
 osd.xx scrub-queue::remove_from_osd_queue removing pg failed. State was: unregistering
 osd.xx scrub-queue::remove_from_osd_queue removing pg failed. State was: unregistering
 osd.xx scrub-queue::remove_from_osd_queue removing pg failed. State was: unregistering
 osd.xx pg_epoch: xx pg[7. local-lis/les=xx n=xx lis/c=xx les/c/f=xx sis=xx pruub=xx.3s)  r=-1 mlcod 0'0 unknown NOTIFY pruub xx.@ mbc={}] enter Started/Stray
The above are some logs during the same time.
We didn't face any OSD stoppage issue,so doesn't require replacement,I guess.(Correct me if I am wrong)

**Comment by sp98** [comment]
@palthisailohith Both `Bad crc in data` and issues with `pg scrubing` indicates a some kind of failure with the hardware. 

Possible option, like Travis mentioned, is to replace this OSD.

**Comment by microyahoo** [comment]
hi @palthisailohith, You can check through `dmesg` to see if it contains any `medium error` or `unrecovered read error`.

**Comment by palthisailohith** [comment]
> hi @palthisailohith, You can check through `dmesg` to see if it contains any `medium error` or `unrecovered read error`.

Thanks,will check and let you know.

**Comment by palthisailohith** [comment]
> hi @palthisailohith, You can check through `dmesg` to see if it contains any `medium error` or `unrecovered read error`.

Nothing much from the dmesg, except for the below:
"Write cache:disabled,read cache:enabled, doesn't support DPO or FUA"
and I can see some "USB disconnect" errors.

Is there any relation with the daemon crash with the above issue?

**Comment by microyahoo** [comment]
Are you checking dmesg in the osd host?

**Comment by palthisailohith** [comment]
> Are you checking dmesg in the osd host?

Yes

**Comment by palthisailohith** [comment]
> Are you checking dmesg in the osd host?

And also the core dumps were not getting created for these crashes on that particular node, could you help on this.

**Comment by palthisailohith** [comment]
> Are you checking dmesg in the osd host?

Any update yet?

**Comment by microyahoo** [comment]
Maybe you can try to run pg deep scrub
> Then there's deep scrubbing, which is designed to catch bit-rot (aka, the correctness of the PG's), it's naturally a data intensive operation.

**Comment by palthisailohith** [comment]
> Maybe you can try to run pg deep scrub
> > Then there's deep scrubbing, which is designed to catch bit-rot (aka, the correctness of the PG's), it's naturally a data intensive operation. 

Ok,will try.
And also the core dumps were not getting created for these crashes,what could be the reason?

**Comment by palthisailohith** [comment]
> > Maybe you can try to run pg deep scrub
> > > Then there's deep scrubbing, which is designed to catch bit-rot (aka, the correctness of the PG's), it's naturally a data intensive operation. 
> 
> Ok,will try.
> And also the core dumps were not getting created for these crashes,what could be the reason?

Any update yet?

**Comment by microyahoo** [comment]
Seems  hardware is functioning normally.

**Comment by palthisailohith** [comment]
> Seems  hardware is functioning normally.

Then what can be the issue? And we are also unable to see the core log files on the OSD nodes?

**Comment by palthisailohith** [comment]
> Seems  hardware is functioning normally.

Any update on the above query yet?

**Comment by travisn** [comment]
Do you see the core dumps if you enable the `logCollector` setting as explained in the [CephCluster CR settings](https://rook.io/docs/rook/latest/CRDs/Cluster/ceph-cluster-crd/#cluster-settings)?
```
In case a daemon terminates with a segfault, the coredump files will be commonly be generated in 
/var/lib/systemd/coredump directory on the host, depending on the underlying OS location. 
```

**Comment by palthisailohith** [comment]
> Do you see the core dumps if you enable the `logCollector` setting as explained in the [CephCluster CR settings](https://rook.io/docs/rook/latest/CRDs/Cluster/ceph-cluster-crd/#cluster-settings)?
> ```
> In case a daemon terminates with a segfault, the coredump files will be commonly be generated in 
> /var/lib/systemd/coredump directory on the host, depending on the underlying OS location. 
> ```

We have enabled it,but still don't see anything in /var/lib/systemd/coredump
