### ISSUE TITLE
Modprobe Error rbdplugin Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by alb-dev** [rook/rook#14431]
*Bug Report*
During the initial setup process the "csi-rbdplugin" pods seem to fail modprobe rbd.
This results in crashloopback off for the csi-rbdplugin. 
If the "modprobe rbd" command is executed on the shell of the host the pods starts as expected

**Deviation from expected behavior:**
On Debian12 the modprobe can be executed succesfully and the pod start as expected. 

**Expected behavior:**

**How to reproduce it (minimal and precise):**
Create a k8s cluster with ubuntu 24.04LTS as Host os.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Pod's logs, if necessary
 `modprobe: ERROR: could not insert 'rbd': Key was rejected by service`

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 24.04LTS
* Kernel (e.g. `uname -a`): 6.8.0-36-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.14.8
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.30.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by Madhu-1** [comment]
same as https://github.com/ceph/ceph-csi/issues/4679

**Comment by grassdionera** [comment]
we have this issue to. it prevents the complete cluster from creating ceph or rbd volumes

**Comment by nixpanic** [comment]
The `quay.io/ceph/ceph:v18` container-image has been updated to CentOS Stream 9. The next release of Ceph-CSI should support the new **zstd** module format.
