### ISSUE TITLE
The ip address of rook-ceph mgr pod is always in blocklist

### ISSUE THREAD

**Issue by zsksy123** [rook/rook#14440]
version
```
rook_ceph:v1.12.11
ceph:v17.2.6
```
As shown below, the ip address of the mgr-b pod is 10.96.9.10

`rook-ceph-mgr-b-6d5b7cf6bb-lj9b7                      3/3     Running     0             20m   10.96.9.10      a6000-4      <none>           <none>`
As shown below, only the mgr-b pod ip is listed in the blocklist，no matter which node mgr-b is started on
```
ceph osd blocklist ls
10.96.9.10:0/2508813557 2024-07-10T08:31:08.883360+0000
10.96.9.10:0/120580002 2024-07-10T08:31:08.883360+0000
10.96.9.10:0/2868010900 2024-07-10T08:31:08.883360+0000
10.96.9.10:0/1399480183 2024-07-10T08:31:08.883360+0000
10.96.9.10:6801/2258748430 2024-07-10T08:31:08.883360+0000
10.96.9.10:6800/2258748430 2024-07-10T08:31:08.883360+0000
listed 6 entries
```
ceph health status
```
ceph -s
  cluster:
    id:     xxxxxx
    health: HEALTH_OK

  services:
    mon: 5 daemons, quorum a,b,c,d,g (age 38m)
    mgr: b(active, since 3m), standbys: a
    mds: 5/5 daemons up, 5 hot standby
......
```

mgr pod log file
[mgr-b.log](https://github.com/user-attachments/files/16140534/mgr-b.log)

**Comment by travisn** [comment]
@zsksy123 Do you have any repro steps? For example, did you enable the CSI addons to enable the [Node loss](https://rook.io/docs/rook/latest/Storage-Configuration/Block-Storage-RBD/block-storage/#node-loss) handling?

**Comment by zsksy123** [comment]
@travisn Hello, I have not enabled node loss processing

**Comment by TimeLordFang** [comment]
I have the same problem .Everyday when I open ceph dashboard, it takes a long time to load , and even returns 502.

log of active mgr pod (sometimes other XxxYyyyHandler):
```
 [rbd_support ERROR root] TrashPurgeScheduleHandler: client blocklisted
```
Wait for a while , 3 mgr pod switch roles
And the ip of previous active mgr pod is in the `ceph osd blocklist ls`

I think It may be caused by mgr  gathering OSD data concurrently.( I have 3600+ OSDs)
Is there a some configuration to change threshold of blocklist

**Comment by zsksy123** [comment]
@TimeLordFang I think It may be caused by mgr gathering OSD data concurrently. 
----------------------------------------
Can you elaborate on this reason? I don't really understand. Why would mgr be added to the blocklist

**Comment by TimeLordFang** [comment]
> ## @TimeLordFang I think It may be caused by mgr gathering OSD data concurrently.
> Can you elaborate on this reason? I don't really understand. Why would mgr be added to the blocklist
> 
> we have a cluster with less than 10 osd nodes

@zsksy123  This is my guess. Since you only have 10 osds, this should not be the reason.

**Comment by idryomov** [comment]
> @idryomov What would cause the mgr ip to get blocklisted? I only expected the blocklisting for rbd.

It is RBD -- just the part that is running as a manager module.  This includes:
- trash purge scheduler
- mirror snapshot scheduler
- support for `rbd task` commands (the manager running long-running maintenance operations on RBD images such as flattening on behalf of the user)
- support for `rbd perf` commands (the manager registering OSD perf queries)

cc @ajarr

**Comment by TimeLordFang** [comment]
> @zsksy123 I see you're on `ceph:v17.2.6`. @TimeLordFang What version of Ceph are you on?
Ceph (v17.2.7) ,Rook 1.13.1

**Comment by idryomov** [comment]
> I repeated the problem, when I restart a pod such as active mds or mgr, the pod ip previously used by the pod will be added to the blocklist，do you know why？

This is the expected behavior.  When the manager is failed over, all RADOS clients that were in use by the manager modules are blocklisted because we don't want anything tied to the previous manager instance to continue interacting with RADOS after a new manager instance goes live.

I'm a bit fuzzy on the MDS part, but there is some tight coupling between the MDS and CephFS' `volumes` manager module, so I wouldn't be surprised if failing over one also fails over the other.

**Comment by zsksy123** [comment]
@idryomov @travisn 
Hello, my problem is not just mgr's old ip being added to the bliocklist. The newly started mgr pod ip is also added to the blocklist. After ceph osd blocklist clear is executed, the newly started mgr pod ip is added to the blocklist within a few minutes or even seconds

**Comment by travisn** [comment]
> I seem to have found the cause of this problem. When I manually execute ceph mgr module enable or disable, mgr pod ip will be added to blocklist, but when I do not manually execute it, it seems that the status of the module will be automatically changed, as shown in the log. The mgr pod ip is then added to the blocklist. Now the question is why does the enbale disable module automatically happen

Rook does enable/disable modules according to settings in the CephCluster CR, but it should be a one-time update assuming you're not updating the CR. If this is a recurring event, it sounds unexpected. 

So this happened after upgrading Rook to which version? Or it happens every time you update Rook? Does it also happen if you restart the Rook operator?

**Comment by idryomov** [comment]
> After ceph osd blocklist clear is executed [...]

I'd advise against clearing the blocklist table manually.  The system adds blocklists for a reason, they shouldn't be messed with unless you really know what you are doing.

> debug 2024-07-12T07:29:42.964+0000 7f69372d5700  1 mgr handle_mgr_map respawning because set of enabled modules changed!

When a set of enabled modules changes and the manager respawns as a result, blocklisting is expected for the reasons that I outlined in https://github.com/rook/rook/issues/14440#issuecomment-2223207310.  Modules getting enabled or disabled is implemented with a "kill the current instance of the manager and create a new one from scrtach" sledge hammer because it's supposed to be a very rare operation.

**Comment by zsksy123** [comment]
> > 执行 ceph osd blocklist clear 后 [...]
> 
> 我建议不要手动清除黑名单表。系统添加黑名单是有原因的，除非你真的知道自己在做什么，否则不应该乱动它们。
> 
> > debug 2024-07-12T07:29:42.964+0000 7f69372d5700 1 mgr handle_mgr_map 重生，因为启用的模块集发生了变化！
> 
> 当一组启用的模块发生变化，管理器因此而重生时，出于我在[#14440 (评论)](https://github.com/rook/rook/issues/14440#issuecomment-2223207310)中概述的原因，预计会将其列入黑名单。启用或禁用模块是通过“杀死管理器的当前实例并从头开始创建一个新实例”这一大锤来实现的，因为这应该是一个非常罕见的操作。

The problem is that the module will be automatically updated, during which what is not done

**Comment by zsksy123** [comment]
> > 我好像找到这个问题的原因了，当我手动执行ceph mgr module enable或者disable时，mgr pod ip会被添加到blocklist中，但是当我不手动执行时，好像会自动改变模块的状态，如日志所示，然后mgr pod ip就被添加到blocklist中了，现在的问题是为什么enbale disable module会自动发生
> 
> Rook 确实会根据 CephCluster CR 中的设置启用/禁用模块，但假设您不更新 CR，这应该是一次性更新。如果这是一个重复事件，听起来就出乎意料了。
> 
> 那么这是在将 Rook 升级到哪个版本后发生的？还是每次更新 Rook 时都会发生？重新启动 Rook 运算符也会发生这种情况吗？


@travisn rook was upgraded only once after upgrading to v1.12.11

**Comment by travisn** [comment]
@zsksy123 Interesting to see the mgr module is restarted every 10 minutes. Can you find more info in the operator log for why the reconcile is being triggered so often? Or can you share the full operator log?

**Comment by zsksy123** [comment]
@travisn Ok, these are my logs of three different clusters. Among them, cluster 2 no longer has this problem after 2024.07.09. The memory and cpu resources of the node where Cluster 3 is located may be insufficient. However, the cluster1 issue requires attention because it does not have the problem of inadequate resources, but the problem still exists. In addition, I would like to ask you a question. Will changes in ceph cluster cause the mgr dashboard module to restart? For example, the osd status changes and mon restarts[cluster2-operator.log](https://github.com/user-attachments/files/16242702/cluster2-operator.log)
[cluster3-operator.log](https://github.com/user-attachments/files/16242704/cluster3-operator.log)
[cluster1-operator.log.zip](https://github.com/user-attachments/files/16242721/cluster1-operator.log.zip)

**Comment by travisn** [comment]
The operator log shows this error, though it should be independent from the dashboard restart issue:
```
2024-07-16 02:01:59.475624 E | ceph-file-controller: failed to reconcile failed to configure mirroring for filesystem "myfs".:
 failed to add snapshot schedules on filesystem "myfs": failed to add snapshot schedule every "1m" to ceph filesystem 
"myfs" on path "/". . Error ENOENT: schedule multiplier "m" not recognized: exit status 2
```

There are image timeout issues, perhaps there are issues connecting to the registry:
```
2024-06-20 09:26:37.636834 E | ceph-block-pool-controller: failed to reconcile CephBlockPool "rook-ceph/replicapool". failed to fetch ceph version from cephcluster "rook-ceph": 
attempt to determine ceph version for the current cluster image timed out
```

This issue will cause of the cephcluster reconcile getting triggered more often than it needs. Did you actually have device changes (with the intention to add OSDs)? If not, you can disable this with the setting ``.
```
2024-06-25 08:37:11.397753 I | ceph-cluster-controller: hot-plug cm watcher: 
running orchestration for namespace "rook-ceph" after device change
```

But even with that issue, the reconcile start message still shows much more often without an explanation for why it was started:
```
ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
```

Of the 129 times the reconcile was started (according to that message), the dashboard was restarted 79 times. 

Analyzing the code path that matches the operator logs, the only place I see where the dashboard module could be restarted is when the ssl cert is getting reconfigured. 
https://github.com/rook/rook/blob/9967b161f9c12a9dd899f39469d708b8f46df1da/pkg/operator/ceph/cluster/mgr/dashboard.go#L219

If you change the dashboard to not use ssl (`dashboard.ssl: false`), does it help the issue? Although if these are production clusters you likely don't want to disable ssl.

**Comment by zsksy123** [comment]
@travisn Does the problem seem to have been located as a result of the certificate reconfiguration? What triggers a certificate reconfiguration? Is there a way around this if you can't help but use ssl?

**Comment by zsksy123** [comment]
@travisn The operator log message did not match 219 lines of code, but 315 lines were found
```
2024-07-08 22:02:25.256652 I | op-mgr: the dashboard secret was already generated
2024-07-09 07:43:10.500734 I | op-mgr: the dashboard secret was already generated
2024-07-09 17:23:50.060297 I | op-mgr: the dashboard secret was already generated
2024-07-10 03:04:29.915603 I | op-mgr: the dashboard secret was already generated
2024-07-10 08:24:07.538888 I | op-mgr: the dashboard secret was already generated
2024-07-11 06:38:28.602777 I | op-mgr: the dashboard secret was already generated
2024-07-11 06:39:21.793358 I | op-mgr: the dashboard secret was already generated
2024-07-11 06:55:50.973312 I | op-mgr: the dashboard secret was already generated
2024-07-11 08:06:29.968838 I | op-mgr: the dashboard secret was already generated
2024-07-11 17:47:13.451581 I | op-mgr: the dashboard secret was already generated
2024-07-12 03:27:54.432870 I | op-mgr: the dashboard secret was already generated
2024-07-12 13:08:34.854935 I | op-mgr: the dashboard secret was already generated
2024-07-12 22:49:17.284852 I | op-mgr: the dashboard secret was already generated
2024-07-13 08:29:58.850322 I | op-mgr: the dashboard secret was already generated
2024-07-13 18:10:40.506416 I | op-mgr: the dashboard secret was already generated
2024-07-14 03:51:21.345247 I | op-mgr: the dashboard secret was already generated
2024-07-14 13:32:03.889807 I | op-mgr: the dashboard secret was already generated
2024-07-14 23:12:45.228118 I | op-mgr: the dashboard secret was already generated
2024-07-15 08:53:27.951463 I | op-mgr: the dashboard secret was already generated
2024-07-15 18:34:09.318907 I | op-mgr: the dashboard secret was already generated
```
![image](https://github.com/user-attachments/assets/29dfd798-af7b-4f72-9f1d-97f129ee3fea)

**Comment by travisn** [comment]
> @travisn Has the problem been located to be caused by certificate reconfiguration? What triggers a certificate reconfiguration? Is there a way around this if you can't help but use ssl?

Even with the certificate reconfiguration, the code path still doesn't explain to me why you are seeing this issue, so I'm not sure yet. I was just wonder if it's possible to disable the ssl temporarily to see if the issue goes away. 

Also, does it still repro after restarting the rook operator? I don't recall seeing an answer to that question.

**Comment by zsksy123** [comment]
`Also, does it still repro after restarting the rook operator? I don't recall seeing an answer to that question.`
@travisn Okay, I'll restart the operator pod and watch it for a few hours

**Comment by zsksy123** [comment]
> Even with the certificate reconfiguration, the code path still doesn't explain to me why you are seeing this issue, so I'm not sure yet. I was just wonder if it's possible to disable the ssl temporarily to see if the issue goes away.

@travisn Hello, I disabled the ssl of dashboard. After 24 hours, mgr pod ip was not added to osd blocklist

**Comment by travisn** [comment]
Ok, I found the issue that ceph is no longer returning a code to indicate that the ssl cert is already configured. Therefore, Rook believes it needs to restart the mgr module during every reconcile when `ssl: true` for the dashboard. I've opened #14484 to address this, but still investigating the fix.

**Comment by travisn** [comment]
The dashboard module will no longer be started unnecessarily when `ssl: true`. This will be in the v1.14.9 release planned for tomorrow.
