### ISSUE TITLE
Filesystem requests are deadlocked and hanging 

### ISSUE THREAD

**Issue by dmcguigankx** [rook/rook#14442]
**Is this a bug report or feature request?**
* Bug Report
We're finding that when one process writes data to disk, another opening/closing the database files seems to trigger a deadlock in Ceph and hang indefinitely. The symptoms are essentially identical to https://access.redhat.com/solutions/7048761 but we're on an OpenShift and kernel version that should be unaffected: 4.13.42 and 5.14.0-284.66.1.el9_2.x86_64 respectively. We've tested this with other Linux and OpenShift versions, and so far the only unaffected configuration has been running Linux 4.18.0 (green means clear, yellow means affected):

![image](https://github.com/rook/rook/assets/175031373/9bd7da7c-bd19-4335-81cf-6d36029a5d07)

**Deviation from expected behavior:**
Filesystem requests hang indefinitely, certain files become 'poisoned' and all requests on them hang.
**Expected behavior:**
File operations do not hang.

**How to reproduce it (minimal and precise):**
Unfortunately we've so far been unable to reproduce the issue in a redistributable form, but I have a reliable reproduction using a KX Insights database deployment that I can run diagnostics on. I've attached Ceph diagnostics and strace logs from the processes reproducing the issue, but I'd be happy to provide any other diagnostic information that would help, and I'm still working on isolating the operations that cause the deadlock so they can be reproduced.

**Logs to submit**:

[dump_ops_in_flight.json](https://github.com/user-attachments/files/16145433/dump_ops_in_flight.json) -- output of `dump_ops_in_flight` from the affected MDS.
[dump_inode.json](https://github.com/user-attachments/files/16145552/dump_inode.json) output of `dump inode` from the affected MDS.

[eoitrace.log](https://github.com/user-attachments/files/16145384/eoitrace.log) -- this is the writer process that seems to trigger the hang.
[smtrace.log](https://github.com/user-attachments/files/16145405/smtrace.log) -- this is a secondary writer process that hasn't been ruled out as a cause.
[qtrace.log](https://github.com/user-attachments/files/16145558/qtrace.log) -- this is the reader process which actually triggers the hang. It does the open-seek-close operations every second. If this process isn't running then the process in `eoitrace.log` will complete with no apparent deadlock or hang.

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```
* Kernel (e.g. `uname -a`):
`Linux rook-ceph-mds-ocs-storagecluster-cephfilesystem-a-7566fb86mfdzd 5.14.0-284.66.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 6 14:51:27 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
3 worker nodes with local disk
* Rook version (use `rook version` inside of a Rook Pod):
`rook: v4.13.10-0.7fddee9cf5ceb07a8ee7a78f0343aa118801f99d`
* Storage backend version (e.g. for ceph do `ceph -v`):
`ceph version 17.2.6-216.el9cp (2787f204195806caaa97db2b363a263d5a9fa156) quincy (stable)`
* Kubernetes version (use `kubectl version`):
` v1.26.15+4818370`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
OpenShift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
`HEALTH_WARN 2 clients failing to respond to capability release; 1 MDSs report slow requests`

**Comment by travisn** [comment]
You're running downstream ODF 4.13, please open a customer support case through the expected downstream channels for proper attention from CephFS team to look at the file sharing issue. The Rook upstream repo won't be able to help on this issue.

**Comment by dmcguigankx** [comment]
No problem, I'll raise it there then. Thanks for taking a look.

**Comment by dmcguigankx** [comment]
Hi, I've now reproduced this issue on OpenShift running Rook directly without ODF in the way. The symptoms are exactly the same as far as I can tell. Rook version is v1.14.8, Ceph version is 18.2.2.

**Comment by travisn** [comment]
> Hi, I've now reproduced this issue on OpenShift running Rook directly without ODF in the way. The symptoms are exactly the same as far as I can tell. Rook version is v1.14.8, Ceph version is 18.2.2.

Ok for ceph upstream issues, please open a [Ceph tracker](https://tracker.ceph.com/) for the cephfs team to look.

**Comment by dmcguigankx** [comment]
I've raised this with Ceph and confirmed it's a Linux cephfs client bug. Thank you for your patience.
