### ISSUE TITLE
Upgrading with helm - CRDs?

### ISSUE THREAD

**Issue by pasztorl** [rook/rook#14453]
Hi, sorry if I miss something, but I could not find the upgrade documentation if rook and ceph-cluster installed with helm charts. Helm does not upgrade the CRDs, so i'm not sure if I do an upgrade it will be fine.
Can somebody point to the documentation, or the rook operator manages the crds automatically?

**Comment by travisn** [comment]
The rook helm chart will actually update the CRDs automatically, they don't need to be managed separately. However, the [rook chart documentation](https://rook.github.io/docs/rook/latest/Helm-Charts/operator-chart/) doesn't mention this detail, since it just works automatically.

**Comment by pasztorl** [comment]
ok, so the crds not placed in the crd dir so helm actually don't know about the crds. ok, I see there is a resources.yaml in the templates. Thanks!

**Comment by pasztorl** [comment]
I wondered about the created resources will be deleted if I remove the chart, but now I see the helm.sh/resource-policy: keep which solves this problem, great. I think this is a better way than placing them to the crds directory.
