### ISSUE TITLE
MDS, insufficient standby MDS daemons available

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#14461]
Hi Team, we have deployed the rook-ceph cluster in kubernetes, below is the error we are facing, in MDS is showing up and but not showing stand by, how can we bring it, below is the before ceph status and currently we have ceph status.
Before ceph status:
==============
bash-4.4$ ceph -s
  cluster:
    id:     33be0f61-fce8-4eb8-a8e5-9dd5e2b312fc
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 7w)
    mgr: a(active, since 11d), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 7w), 3 in (since 7w)

  data:
    volumes: 1/1 healthy
    pools:   3 pools, 49 pgs
    objects: 3.90k objects, 96 MiB
    usage:   652 MiB used, 299 GiB / 300 GiB avail
    pgs:     49 active+clean

  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr

now ceph status
===========

[rook@rook-ceph-tools-76598c54f4-vnf9p /]$ ceph -s
  cluster:
    id:     7831676a-ef77-4a0f-b859-5c172f005dfe
    health: HEALTH_WARN
            insufficient standby MDS daemons available
            clock skew detected on mon.c, mon.d
            2687793 slow ops, oldest one blocked for 676548 sec, mon.c has slow ops

  services:
    mon: 3 daemons, quorum b,c,d (age 13d)
    mgr: a(active, since 11d)
    mds: 1/1 daemons up
    osd: 3 osds: 3 up (since 2d), 3 in (since 2d)

  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 71.89k objects, 1.3 GiB
    usage:   5.6 GiB used, 144 GiB / 150 GiB avail
    pgs:     65 active+clean

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu
* Kernel (e.g. `uname -a`): uname -a
Linux master 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.8.1
* Storage backend version (e.g. for ceph do `ceph -v`): v16.6.10
* Kubernetes version (use `kubectl version`):v1.23
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
Please resolve the clock skew issue, it can cause unexpected health issues with distributed systems including ceph. For example, run the ntp service to sync the clocks.
```
clock skew detected on mon.c, mon.d
```
