### ISSUE TITLE
github workflows  with excessive token-permissions

### ISSUE THREAD

**Issue by obnoxxx** [rook/rook#14466]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

the OpenSSF scorecard report https://scorecard.dev/viewer/?uri=github.com/rook/rook

reports excessive token-permissions in rook's github workflows:

```

Token-Permissions
high
Determines if the project's workflows follow the principle of least privilege.
Reason
detected GitHub workflow tokens with excessive permissions
Details
Info: jobLevel 'contents' permission set to 'read': .github/workflows/commitlint.yml:25
Info: jobLevel 'pull-requests' permission set to 'read': .github/workflows/commitlint.yml:26
Warn: no topLevel permission defined: .github/workflows/auto-assign.yaml:1
Info: topLevel 'contents' permission set to 'read': .github/workflows/build.yml:16
Warn: no topLevel permission defined: .github/workflows/canary-integration-suite.yml:1
Warn: no topLevel permission defined: .github/workflows/canary-integration-test.yml:1
Info: topLevel 'contents' permission set to 'read': .github/workflows/codegen.yml:25
Info: topLevel 'contents' permission set to 'read': .github/workflows/codespell.yaml:20
Info: topLevel 'contents' permission set to 'read': .github/workflows/commitlint.yml:20
Info: topLevel 'contents' permission set to 'read': .github/workflows/crds-gen.yml:25
Warn: no topLevel permission defined: .github/workflows/create-tag.yaml:1
Warn: no topLevel permission defined: .github/workflows/daily-nightly-jobs.yml:1
Info: topLevel 'contents' permission set to 'read': .github/workflows/docs-check.yml:20
Info: topLevel 'contents' permission set to 'read': .github/workflows/golangci-lint.yaml:20
Info: topLevel 'contents' permission set to 'read': .github/workflows/helm-lint.yaml:22
Warn: no topLevel permission defined: .github/workflows/integration-test-helm-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-mgr-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-multi-cluster-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-object-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-smoke-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-upgrade-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-tests-on-release.yaml:1
Info: topLevel 'contents' permission set to 'read': .github/workflows/linters.yaml:20
Info: topLevel 'contents' permission set to 'read': .github/workflows/mod-check.yml:25
Warn: no topLevel permission defined: .github/workflows/multus.yaml:1
Info: topLevel 'contents' permission set to 'read': .github/workflows/push-build.yaml:16
Info: topLevel 'contents' permission set to 'read': .github/workflows/rbac-gen.yaml:25
Info: topLevel 'contents' permission set to 'read': .github/workflows/shellcheck.yaml:20
Info: topLevel 'contents' permission set to 'read': .github/workflows/snyk.yaml:11
Info: topLevel 'contents' permission set to 'read': .github/workflows/stale.yaml:8
Info: topLevel 'contents' permission set to 'read': .github/workflows/unit-test.yml:32
Info: no jobLevel write permissions found
```

**Expected behavior:**

Token-Permissions should score 10  on the board. 

**How to reproduce it (minimal and precise):**

N/A

**File(s) to submit**:

N/A

**Logs to submit**:
N/A

**Cluster Status to submit**:

N/A

* Output of kubectl commands, if necessary

N/A

**Environment**:

N/A

**Comment by obnoxxx** [comment]
@travisn  I think it might make sense to address the "warn"items, i. e. add read permission where there is no top level permission. wdyt?

**Comment by travisn** [comment]
Here are my comments on each warning:
```
# I believe this needs write access to assign the github issue to a user
Warn: no topLevel permission defined: .github/workflows/auto-assign.yaml:1
# We aren't using the create-tag workflow, let's just delete this:
Warn: no topLevel permission defined: .github/workflows/create-tag.yaml:1
# Read access should be good for the integration tests:
Warn: no topLevel permission defined: .github/workflows/canary-integration-suite.yml:1
Warn: no topLevel permission defined: .github/workflows/canary-integration-test.yml:1
Warn: no topLevel permission defined: .github/workflows/daily-nightly-jobs.yml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-helm-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-mgr-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-multi-cluster-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-object-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-smoke-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-test-upgrade-suite.yaml:1
Warn: no topLevel permission defined: .github/workflows/integration-tests-on-release.yaml:1
Warn: no topLevel permission defined: .github/workflows/multus.yaml:1
```
@subhamkrai Any concerns or other comments on it?

**Comment by subhamkrai** [comment]
> Here are my comments on each warning:
> 
> ```
> # I believe this needs write access to assign the github issue to a user
> Warn: no topLevel permission defined: .github/workflows/auto-assign.yaml:1
> 
> # We aren't using the create-tag workflow, let's just delete this:
> Warn: no topLevel permission defined: .github/workflows/create-tag.yaml:1
> 
> # Read access should be good for the integration tests:
> Warn: no topLevel permission defined: .github/workflows/canary-integration-suite.yml:1
> Warn: no topLevel permission defined: .github/workflows/canary-integration-test.yml:1
> Warn: no topLevel permission defined: .github/workflows/daily-nightly-jobs.yml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-helm-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-mgr-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-multi-cluster-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-object-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-smoke-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-upgrade-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-tests-on-release.yaml:1
> Warn: no topLevel permission defined: .github/workflows/multus.yaml:1
> ```
> 
> @subhamkrai Any concerns or other comments on it?

All the comments are on point Travis, we can go ahead with your suggestions

**Comment by obnoxxx** [comment]
@travisn  wrote:

> Here are my comments on each warning:

I am going to comment inline to ask for clarification in a few cases.



> 
> ```
> # I believe this needs write access to assign the github issue to a user
> Warn: no topLevel permission defined: .github/workflows/auto-assign.yaml:1


are you suggesting to set top-level contents permissions to write for this workflow?


> # We aren't using the create-tag workflow, let's just delete this:
> Warn: no topLevel permission defined: .github/workflows/create-tag.yaml:1


Are you suggesting to remove the entire workflow file?



> 
> # Read access should be good for the integration tests:
> Warn: no topLevel permission defined: .github/workflows/canary-integration-suite.yml:1
> Warn: no topLevel permission defined: .github/workflows/canary-integration-test.yml:1
> Warn: no topLevel permission defined: .github/workflows/daily-nightly-jobs.yml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-helm-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-mgr-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-multi-cluster-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-object-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-smoke-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-test-upgrade-suite.yaml:1
> Warn: no topLevel permission defined: .github/workflows/integration-tests-on-release.yaml:1
> Warn: no topLevel permission defined: .github/workflows/multus.yaml:1

So the suggestion is to add top-level contents read permissions to all of these workflows?

> ```
