### ISSUE TITLE
operator does not have permissions to remove node when deployed via Helm

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1447]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened: When deploying Rook via Helm charts and then attempting to remove a node later on by editing the cluster CRD, the operator does not have the required permissions to do so.  This error is found in the operator log:
```
2018-01-27 14:02:37.774269 E | op-cluster: failed to update cluster in namespace rook. failed to start the osds.
1 failures encountered while running osds in namespace rook:
failed to update osd replica set for removed node 10-205-86-253.kube.aws-card-dqa.cb4good.com.
replicasets.extensions "rook-ceph-osd-10-205-86-253.kube.aws-card-dqa.cb4good.com" is forbidden:
User "system:serviceaccount:kube-system:rook-operator" cannot update replicasets.extensions in the namespace "rook"
```

How to reproduce it (minimal and precise):

1. Deploy Rook operator via a Helm chart
1. Create a Rook cluster with `useAllNodes: false` and an explicit list of nodes
1. Edit the cluster CRD to remove 1 of the nodes

**Comment by houey** [comment]
can you remove this from Github?

**Comment by jbw976** [comment]
@houey what do you mean remove this from Github? The issue is already closed, what would you like accomplished? Thanks!

**Comment by houey** [comment]
Trying to have the internal only hostname removed from this issue if possible

**Comment by jbw976** [comment]
ah sorry about that @houey, I don't see a way to delete the issue entirely, but I have scrubbed that data from the details now. hope that works, thanks!
