### ISSUE TITLE
RBD Mirror import bootstrap token infinitly loading.

### ISSUE THREAD

**Issue by TheCodingSheikh** [rook/rook#14479]
I'm trying to setup rbd mirror between two ceph clusters, each cluster in different k8s cluster, both ceph clusters have **provider: host**
tested connectivity between mons, they can reach each other
followed the documentation steps, the bootstrap token secret is not imported with rook, i tried with ceph ui and cli, it keeps loading infinitly, both clusters are in version 14.8.
no logs are appearing in the operator regarding importing the token

both mirror daemon and the mirror pool healths are OK

**Comment by travisn** [comment]
You're following [this guide](https://rook.io/docs/rook/latest/Storage-Configuration/Block-Storage-RBD/rbd-mirroring/) to setup the mirroring? 

You might try the command [kubectl rook-ceph dr health](https://github.com/rook/kubectl-rook-ceph?tab=readme-ov-file#commands) with the kubectl plugin to help troubleshoot.

**Comment by TheCodingSheikh** [comment]
@travisn yes the guide you mentioned.
I'll check with the command and update.
Much appreciated
