### ISSUE TITLE
CephCluster "rook-ceph" found but skipping reconcile since ceph health is &{Health:HEALTH_ERR Details:map[error:{Severity:Urgent Message:failed to get status

### ISSUE THREAD

**Issue by nicofnt** [rook/rook#14470]
Overview 
 It's 3 days I'm trying to run rook-ceph on a k8s cluster with 3 nodes. Tried both deploying it using helm or the let's say "classic way"
All the times, the cluster deploy ends like that:

`NAME        DATADIRHOSTPATH   MONCOUNT   AGE    PHASE   MESSAGE                                    HEALTH       EXTERNAL   FSID
rook-ceph   /var/lib/rook                         3          4m6s   Ready   Failed to configure ceph cluster  HEALTH_ERR` 

![image](https://github.com/user-attachments/assets/a768a69a-34de-42cb-a525-2db5c6b94eb9)

**How to reproduce it (minimal and precise):**
```
curl -fsSL -o operator-values.yaml https://raw.githubusercontent.com/rook/rook/master/deploy/charts/rook-ceph/values.yaml
curl -fsSL -o ceph-values.yaml https://raw.githubusercontent.com/rook/rook/master/deploy/charts/rook-ceph-cluster/values.yaml

helm repo add rook-release https://charts.rook.io/release
helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph -f operator-values.yaml
helm install --create-namespace --namespace rook-ceph rook-ceph-cluster \
   --set operatorNamespace=rook-ceph rook-release/rook-ceph-cluster -f ceph-values.yaml
```

**File(s) to submit**:

You can find operator and crash logs attached.

**Logs to submit**:

*[ceph-crash-log.zip](https://github.com/user-attachments/files/16271204/ceph-crash-log.zip)

**Environment**:
* NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
* 5.14.0-427.24.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jul 8 17:47:19 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* Rook Version: v.1.14.8
* Ceph version : 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)
* Kubernetes Version:
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): Cannot get the status

**Comment by travisn** [comment]
> Storage backend status (e.g. for Ceph use ceph health in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): Cannot get the status

In the toolbox what does `ceph status` show? If you don't get a response, or if it times out, it seems there is a network issue connecting to the mon endpoints. It's interesting that you could create all the cluster including mgr and osds though. Try [this topic](https://rook.io/docs/rook/latest/Troubleshooting/ceph-common-issues/#monitors-are-the-only-pods-running) to see if you can check the network from the operator pod and the toolbox to the mon endpoints.

**Comment by nicofnt** [comment]
Connectivity seems OK. 

![image](https://github.com/user-attachments/assets/38239611-ceba-4268-848c-6c41e7c35003)

**Comment by nicofnt** [comment]
Hi @travisn . I started a new deploy from scratch and i've seen that cluster is with HEALTH_OK but then after few minutes (1-2) it goes in an error status.

```
# bash-4.4$ ceph status
  cluster:
    id:     0e965edb-f3d2-4826-97c1-6878f683b413
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 63s)
    mgr: a(active, starting, since 9s), standbys: b
    osd: 3 osds: 3 up (since 9s), 3 in (since 29s)

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:

# bash-4.4$ ceph status
2024-07-18T10:40:55.853+0000 7f1ea93df700 -1 monclient: get_monmap_and_config failed to get config
2024-07-18T10:40:58.855+0000 7f1ea93df700 -1 monclient: get_monmap_and_config failed to get config
2024-07-18T10:41:01.859+0000 7f1ea93df700 -1 monclient: get_monmap_and_config failed to get config

# bash-4.4$ ceph status
^CCluster connection aborted

# kubectl --namespace rook-ceph get cephclusters.ceph.rook.io
NAME        DATADIRHOSTPATH   MONCOUNT   AGE     PHASE   MESSAGE                            HEALTH       EXTERNAL   FSID
rook-ceph   /data/rook        3          6m29s   Ready   Failed to configure ceph cluster   HEALTH_ERR
```

**Comment by nicofnt** [comment]
Tried these old versions and everything went smooth Strange stuff!

```
2024-07-18 14:58:28.378900 I | rookcmd: starting Rook v1.9.4 with arguments '/usr/local/bin/rook ceph operator'
2024-07-18 14:58:28.379019 I | rookcmd: flag values: --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-level=INFO, --operator-image=, --service-account=
2024-07-18 14:58:28.379023 I | cephcmd: starting Rook-Ceph operator
2024-07-18 14:58:28.527831 I | cephcmd: base ceph version inside the rook operator image is "ceph version 16.2.9 (4c3647a322c0ff5a1dd2344e039859dcbd28c830) pacific (stable)"
```

**Comment by nicofnt** [comment]
I went back and tried to troubleshoot network. I tried to use a small cidr for pod an service this time to avoid potential overlap.
But this was not resolutive.
Last thing to try, based on this old isse [https://github.com/rook/rook/issues/5065](url), would be to try a different CNI.

**Comment by nicofnt** [comment]
In the end, I was able to fix the problem. It was the same described here [https://github.com/rook/rook/issues/10110](url).
I had to add the following configurations for containerd:

```
$ vim /etc/systemd/system/containerd.service.d/override.conf

[Service]
LimitNOFILE=1048576

```

then do a `systemctl daemon-reload`; `systemctl restart containerd` and `kubectl rollout restart deployment rook-ceph-mon-a rook-ceph-mon-b rook-ceph-mon-c -n rook-ceph
`

**Comment by nicofnt** [comment]
In the end, I was able to fix the problem. It was the same described here [https://github.com/rook/rook/issues/10110](url).
I had to add the following configurations for containerd:

```
$ vim /etc/systemd/system/containerd.service.d/override.conf

[Service]
LimitNOFILE=1048576

```

then do a `systemctl daemon-reload`; `systemctl restart containerd` and `kubectl rollout restart deployment rook-ceph-mon-a rook-ceph-mon-b rook-ceph-mon-c -n rook-ceph
`

**Comment by nicofnt** [comment]
Sorry, I think I closed the issue too soon, maybe it's worth reopening it to understand if it's something Rook should solve or if it's a Ceph problem.

**Comment by travisn** [comment]
@nicofnt Good to hear that you were able to get it working. Want to open a PR to document this solution in the troubleshooting guide?

**Comment by nicofnt** [comment]
@travisn OK, I'll do it as soon as I'm free.
