### ISSUE TITLE
block storage error

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#14483]
Hi Team,

we have installed rook-ceph cluster on k8s cluster, right now we have used the filesystem storage to provision the volumes for the application , i would like to use the block storage as well in the same cluster. so i would like to use some of the application filesystem storage and some of the application block storage but when i have created the volumes for block storageclass volumes by default its type is filesystem insted of Block, if i specify the block forcefully, its not assigning the volume to the pod,

could you please help on this issue.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
bash-4.4$ ceph status
  cluster:
    id:     33be0f61-fce8-4eb8-a8e5-9dd5e2b312fc
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 6d)
    mgr: b(active, since 4d), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 6d), 3 in (since 6d)

  data:
    volumes: 1/1 healthy
    pools:   4 pools, 81 pgs
    objects: 4.06k objects, 504 MiB
    usage:   4.8 GiB used, 295 GiB / 300 GiB avail
    pgs:     81 active+clean

  io:
    client:   1.2 KiB/s rd, 20 KiB/s wr, 2 op/s rd, 1 op/s wr

  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

* Kernel (e.g. `uname -a`):
draj@master:~$ uname -a
Linux master 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
draj@master:~$

* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):v1.11.11
* Storage backend version (e.g. for ceph do `ceph -v`):v17.2.6
* Kubernetes version (use `kubectl version`):v1.23.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): on-premises
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by vadlakiran** [comment]
below is the pvc description which is block storage type,

kubectl describe pvc mongo-path-pvc
Name:          mongo-path-pvc
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Bound
Volume:        pvc-8bdb34c0-6be6-4932-bb57-782491cc7a54
Labels:        app.kubernetes.io/managed-by=Helm
Annotations:   meta.helm.sh/release-name: pv-pvc
               meta.helm.sh/release-namespace: default
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
               volume.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      50Gi
Access Modes:  RWO
VolumeMode:    Block
Used By:       database-manager-5cfcf887db-q7rp2
Events:        <none>

we are getting below events when we attach above volume to the pod

Events:
  Type     Reason       Age                        From     Message
  ----     ------       ----                       ----     -------
  Warning  FailedMount  4m43s (x31069 over 4d18h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[], failed to process volumes=[data]: volume data has volumeMode Block, but is specified in volumeMounts

**Comment by travisn** [comment]
This error describes the issue:
```
failed to process volumes=[data]: volume data has volumeMode Block, but is specified in volumeMounts
```

**Comment by Rakshith-R** [comment]
@vadlakiran, 
The below example should help you to configure a pod to use block mode pvc.
https://github.com/ceph/ceph-csi/blob/devel/examples/rbd/raw-block-pod.yaml

I think we could have such block mode examples in rook as well https://github.com/rook/rook/tree/master/deploy/examples/csi/rbd
