### ISSUE TITLE
Multus integration tests are failing since 24 July 2024

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#14497]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Multus integration tests are failing since 24 July 2024. https://github.com/rook/rook/actions/workflows/multus.yaml

These are failing in multiple repos, and after no changes to Multus, so I think there is a high probability that this is due to some change to either KinD or github action runners (related to networking or the default eth0 interface?).

**Expected behavior:**

This is high but not maximum priority. Let's definitely get this CI test green for the 1.15 release. Backport to 1.14 as well.

**Comment by subhamkrai** [comment]
I see on more tests related to holder is failing https://github.com/rook/rook/actions/runs/10093692530/job/27922067197?pr=14489

**Comment by BlaineEXE** [comment]
Fixed but forgot the PR #
