### ISSUE TITLE
rook operator on kubernetes 1.8.3 gives error

### ISSUE THREAD

**Issue by abalasu1** [rook/rook#1451]
Yes, none found.

Is this a bug report or feature request?

* Bug Report

**Bug Report**
create rook operator on kubernetes 1.8.3 gives an error.

What happened:
rook operator pod fails to come up with this error:
```
$ kubectl logs rook-operator-5c5db8db4c-hbrm8 -n rook-system
2018-01-29 16:37:43.437456 I | rook: starting Rook v0.6.0-186.g377ff43 with arguments '/usr/local/bin/rook operator'
2018-01-29 16:37:43.437551 I | rook: flag values: --help=false, --log-level=INFO, --mon-healthcheck-interval=45s, --mon-out-timeout=5m0s
2018-01-29 16:37:43.439320 I | rook: starting operator
2018-01-29 16:37:43.456615 I | op-k8sutil: returning version v1.8.3 instead of v1.8.3+icp+ee
panic: could not parse pre-release/metadata (+icp+ee) in version "v1.8.3+icp+ee"

goroutine 1 [running]:
github.com/rook/rook/vendor/k8s.io/kubernetes/pkg/util/version.MustParseSemantic(0xc42008e770, 0xd, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/kubernetes/pkg/util/version/version.go:119 +0x6c
github.com/rook/rook/vendor/github.com/rook/operator-kit.CreateCustomResources(0x1b95920, 0xc42017ef70, 0x1b893e0, 0xc420381870, 0x1dcd6500, 0xdf8475800, 0xc4205561e0, 0x5, 0x5, 0xd, ...)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/rook/operator-kit/resource.go:77 +0x91
github.com/rook/rook/pkg/operator.(*Operator).initResources(0xc420793cc0, 0xd, 0xc42001400e)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/operator.go:145 +0xdb
github.com/rook/rook/pkg/operator.(*Operator).Run(0xc420793cc0, 0xc4205561e0, 0xc42033ee50)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/operator.go:89 +0x111
main.startOperator(0x1bdfdc0, 0x1c0c0d0, 0x0, 0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/cmd/rook/operator.go:79 +0x699
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).execute(0x1bdfdc0, 0x1c0c0d0, 0x0, 0x0, 0x1bdfdc0, 0x1c0c0d0)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1bdf540, 0x1bdffe0, 0x1bdfba0, 0x1be0420)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).Execute(0x1bdf540, 0x0, 0x29)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/home/rook/go/src/github.com/rook/rook/cmd/rook/main.go:76 +0x36
```

What you expected to happen:
Expected rook operator pod to come up.

How to reproduce it (minimal and precise):

Install rook operator on IBM Cloud Private Community Edition (kubernetes 1.8.3)

**Feature Request**

Are there any similar features already existing:

What should the feature do:

What would be solved through this feature:

Does this have an impact on existing features:

**Environment**:
* OS (e.g. from /etc/os-release): redhat 7.4
* Kernel (e.g. `uname -a`):
3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linu

* Cloud provider or hardware configuration:
vmware on prem

* Rook version (use `rook version` inside of a Rook Pod):

* Kubernetes version (use `kubectl version`): 1.8.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): IBM Cloud private
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

**Comment by travisn** [comment]
@kokhang there are a number of places where rook parses the version of kubernetes to determine different behavior. In the future I'm sure there will be other needs to parse the version. In this case, yes we could create a CRD by default. But in other cases the default might not work. Is there another helper that would truncate the suffix separated by the `+`?

**Comment by kokhang** [comment]
yes i just saw that the external-storage project also uses this for parsing version. https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L304

@abalasu1 is there a way you can modify the Kubernetes version and make it SemVer compartible?

**Comment by abalasu1** [comment]
@kokhang, @travisn Thank you, I will pursue changing kubernetes version to make it SemVer compatible.

**Comment by kokhang** [comment]
I will close this issue for now. Thank you.
