### ISSUE TITLE
User still have permission on bucket after unlink

### ISSUE THREAD

**Issue by zzbmmbzz** [rook/rook#14516]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

Hi, I have an issue when trying to use command `radosgw-admin bucket unlink --bucket=<bucket-name> --uid=<uid>
As my expectiation, the user with uid will not be allowed to access the bucket  - ERROR: S3 error: 403 (InvalidAccessKeyId) - But after use the command unlink, the user still can access the bucket

**Step to Procedure**
1. create an user name **test-user** 
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: test-user
  namespace: rook-ceph
spec:
  displayName: test-user
  store: ceph-objectstore-shared
  quotas:
    maxBuckets: 1
  capabilities:
    bucket: "*"
```
2. After create user, I get the access key and access secret key and try to access bucket first -> It will be forbiddance
```
# s3cmd ls --access_key=<access_key> --secret_key=<access_secret_key> --host=<host_masked> --host-bucket=<host_masked> s3://gitlab-runner-cache/
ERROR: S3 error: 403 (InvalidAccessKeyId)
```

3. Verify with command r**adosgw-admin bucket limit check**
```
# radosgw-admin bucket limit check
[
    {
        "user_id": "test-user",
        "buckets": []
    },
    ....
]
```

4. Allow user to access the bucket by command **radosgw-admin bucket link**
```
# radosgw-admin bucket link --bucket=gitlab-runner-cache --uid=test-user
```

5. Verify again
```
# radosgw-admin bucket limit check
[ 
   {
        "user_id": "test-user",
        "buckets": [
            {
                "bucket": "gitlab-runner-cache",
                "tenant": "",
                "num_objects": 4448,
                "num_shards": 11,
                "objects_per_shard": 404,
                "fill_status": "OK"
            }
        ]
    },
    ....
]

#  s3cmd ls --access_key=<access_key> --secret_key=<access_secret_key> --host=<host_masked> --host-bucket=<host_masked> s3://gitlab-runner-cache/
```
![image](https://github.com/user-attachments/assets/3568a593-f3e8-4b5d-8ccd-16ef36317583)

6. Remove user to the bucket by command **radosgw-admin bucket unlink**
```
radosgw-admin bucket unlink --bucket=gitlab-runner-cache --uid=test-user
```

7. Verify again
```
# radosgw-admin bucket limit check
[
    {
        "user_id": "test-user",
        "buckets": []
    },
    ....
]
```
Now after remove user from bucket, I expected that the user can not access to the bucket (403 error), but it still accessed 
![image](https://github.com/user-attachments/assets/3bb06b0f-cf7c-4565-8c22-16fef29ac683)

Thanks,

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v1.11.11
* Storage backend version (e.g. for ceph do `ceph -v`): 17.2.6 (d7ff0d10654d2280e08f1ab989c7cdf3064446a5) quincy (stable)

**Comment by zhucan** [comment]
maybe you can ask for help under ceph tracker https://tracker.ceph.com/issues. it not related with rook. @zzbmmbzz

**Comment by zzbmmbzz** [comment]
I'm sorry @zhucan . I will close ticket now

**Comment by zhucan** [comment]
does not matter

**Comment by zhucan** [comment]
if "unlink", the reponse of the cmd "s3  ls" is empty, but  special the bucket like this "s3://bucket" can access it, Not sure if this design is reasonable under ceph.  @zzbmmbzz
