### ISSUE TITLE
theauto-assign action is  not working anymore

### ISSUE THREAD

**Issue by obnoxxx** [rook/rook#14518]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The self-assign action using the `/assign` keyword seems to have been broken by a recentp PR #14473
The action is still triggered but does not seem to have sufficient permissions any more to perform the assigning activity. so the issue is not getting assigned to the commenter.

Note that this is not a bug in rook's code but a misconfiguration in the github actions of this project. 

**Expected behavior:**

writing  `/assign` in an issue comment should assign the issue to the commenter.

**How to reproduce it (minimal and precise):**

write `/assign`into an issue comment an wait if the issue is getting assigned. Notice it does not get assigned.

**File(s) to submit**:

Not applicable.

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

Not applicable

**Logs to submit**:

Not applicable.

**Cluster Status to submit**:

Not applicable.

**Comment by obnoxxx** [comment]
fwiw, I assigned it manually. The previous comment was just a test.

**Comment by obnoxxx** [comment]
the fix does nor seem to have worked:

https://github.com/rook/rook/actions/runs/10185538175


reopening.

**Comment by travisn** [comment]
It works now!
