### ISSUE TITLE
format error with cluster.yaml file not able to deploy cluster

### ISSUE THREAD

**Issue by gamkiller77** [rook/rook#14515]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When running the command to deploy the cluster it errors out.

**Expected behavior:**
Create of cluster with cluster.yaml to deploy the cluster

**How to reproduce it (minimal and precise):**
Clone latest master
cd deploy/examples
kubectl -n rook-ceph get pod
Error from server (BadRequest): error when creating "cluster.yaml": CephCluster in version "v1" cannot be handled as a CephCluster: strict decoding error: unknown field "spec.csi", unknown field "spec.storage.allowDeviceClassUpdate", unknown field "spec.upgradeOSDRequiresHealthyPGs"

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
removing the fields listed as unknown lets the cluster deployed but has a lot of errors.  

**Environment**:
* OS (e.g. from /etc/os-release):Ubuntu 24.04 LTS
* Kernel (e.g. `uname -a`): Linux n1 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: ZimaBoard
* Rook version (use `rook version` inside of a Rook Pod): 
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):microk8s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): not online the basics are running fine with microk8s enable rook-ceph

**Comment by zwindler** [comment]
Hello @gamkiller77 

Why did you close the issue? I get the same error and I workaround it by commenting the line but I feel that this should be reported. Did I miss something?

**Comment by travisn** [comment]
What version of Rook exactly are you installing? It seems you have a mis-matched version of the CRDs compared to the values you are setting. Those settings that are not matching are newer that are only in master, and have not been released. So it seems you are using the released (v1.14.x) crds.yaml, while using the settings from master. Please check you are using manifests from the release branch.

**Comment by zwindler** [comment]
My bad you are right, I git cloned main

**Comment by gamkiller77** [comment]
Yup I cloned main thanks will fix my setup today.
