### ISSUE TITLE
Consider option to enable the rook-ceph-operator controller-runtime metrics port

### ISSUE THREAD

**Issue by jrcichra** [rook/rook#14538]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Support the option of enabling the rook-ceph-operator controller-runtime metrics that were disabled in this PR: https://github.com/rook/rook/pull/12194 / https://github.com/rook/rook/pull/12194/files#diff-882f257b4a6643911c35b8a03a0e29999e026ca3b8dff406566936c68f4833c7R159

It still seems that way on v1.14.x: https://github.com/rook/rook/blob/9c98467f3c328f3eb79801844b41909160fc4d8a/pkg/operator/ceph/cr_manager.go#L150

**What is use case behind this feature:**
We have alerts defined for controller-runtime metrics, such as workqueue depth. This helps us make sure Rook is not behind reconciling any resource and is useful for debugging controller-runtime. Additionally we have alerts that check the `up` target on prometheus endpoints as another data point to determine if the pod is operational.

It would be nice to retain the ability to enable the metrics endpoint for rook-ceph-operator. An option could be added to the configmap or ENVs with a configurable port number.

**Environment**:

Kubernetes 1.30
Rook v1.10.13 -> v1.11.11 (in process of getting up to 1.14.x)
Debian Bookworm

**Comment by travisn** [comment]
Sounds good to expose an env var on the operator to allow enabling the controller runtime metrics port. 
@jrcichra Are you interested in submitting a PR for this?

**Comment by jrcichra** [comment]
> Sounds good to expose an env var on the operator to allow enabling the controller runtime metrics port. @jrcichra Are you interested in submitting a PR for this?

Yes I'm interested. I'll make a PR for it. Thanks!
