### ISSUE TITLE
Use fully-qualified rook image names by default

### ISSUE THREAD

**Issue by zalsader** [rook/rook#14545]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
On some kubernetes installations, no unqualified search registries are defined, producing the following error on the `rook-ceph-csi-detect-version` pods:
```
Failed to inspect image "rook/ceph:v1.14.9": rpc error: code = Unknown desc = short-name "rook/ceph:v1.14.9" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
```

The error is solved by including the registry name `docker.io` in the image of the `rook-ceph` operator helm chart:
```yaml
image:
   repository: docker.io/rook/ceph
```

**Expected behavior:**
I think all images should use fully-qualified names (includes the repository) in case the kubernetes installation does not set the unqualified-search registries. This means changing the helm chart and the manifests in deploy/examples to use fully-qualified names for the images.

**How to reproduce it (minimal and precise):**
Have an empty `/etc/containers/registries.conf`

**Security Risk**
Not using the fully-qualified image name poses a security risk, see https://www.redhat.com/en/blog/be-careful-when-pulling-images-short-name

**Comment by zalsader** [comment]
I'm happy to do the work and submit a PR if others think this makes sense

**Comment by travisn** [comment]
Interesting that this hasn't been reported in so long, but sounds good to me to add docker.io to the image to clarify their source, thanks.
