### ISSUE TITLE
rook doesnt make object-size param configurable while creating ceph rbd images

### ISSUE THREAD

**Issue by pradn28** [rook/rook#1455]
when the provisioner creates an rbd image, it doesn't specify the `--object-size` param so it uses the default
Seeing poor performance for latency sensitive workloads like databases where a default object size of 4MB doesnt help.
So need this parameter to be configurable through rook.

http://docs.ceph.com/docs/master/man/8/rbd/
--object-size size-in-B/K/M
Specifies the object size in B/K/M. Object size will be rounded up the nearest power of two; if no suffix is given, unit B is assumed. The default object size is 4M, smallest is 4K and maximum is 32M.

**Comment by kokhang** [comment]
Wondering what is the best way to do this. One thing we can do is add these custom params to the storageclass and have the provisioner consume it when creating the volume.
