### ISSUE TITLE
Rook external s3 radosgw user quotas

### ISSUE THREAD

**Issue by icassano** [rook/rook#14555]
Hello,
My kubernetes rook installation is used for addressing external ceph cluster where users can request buckuts claim.
For each bucket claim rook creates a user and a bucket but it does not assign quotas but only max buckets = 1.
Is there any workaround or feature in road map for assigning quotas?

**Comment by travisn** [comment]
Did you see the options for [maxObjects and maxSize](https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/#example)? But since rook creates a user for each bucket, we don't have a max buckets.

**Comment by icassano** [comment]
Yes, I did but the bucket claim is a user request. I would like tu have storage limits defined by kubernetes administrator.
Ignazio
