### ISSUE TITLE
Allow using stable device names for an OSD's ROOK_BLOCK_PATH

### ISSUE THREAD

**Issue by psy-q** [rook/rook#14568]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Allow the specification of more stable device paths for `ROOK_BLOCK_PATH` to prevent OSDs pointing to the wrong devices when device names change.

As an alternative to using "plain" device paths, we could consider adding an option that allows customizing what kind of `ROOK_BLOCK_PATH` is generated for the deployment. This way, users could:

* Incorporate the disk's WWID, which should be globally unique, via `/dev/disk/by-id/wwn-0x6000c2d34db33f1234567`
* Use `/dev/disk/by-path` if the position on the disk controller doesn't change

## Caveats

This should be optional behavior and user-configurable:

* Not all systems or devices expose the WWN or WWID, it's a SCSI thing
* The kernel may not be set up to provide these symlinks in the first place

But all VMware-based OpenShift/OKD clusters are practically guaranteed to have this information whenever virtual SCSI controllers are used for disks, which is the default.

--- 
**What is use case behind this feature:**
In an OpenShift/OKD cluster on VMware, nodes may assign different device names to detected disks on reboot, particularly during OpenShift upgrades where each node is guaranteed to be rebooted at least once. This is most likely to happen when the hard disk configuration was changed since the last boot (e.g. devices removed or added).

For example, before the reboot:
| OSD deployment  | ROOK_BLOCK_PATH | Real device |
|-----------------|-----------|-------------|
| rook-ceph-osd-0 | /dev/sdd  | /dev/sdd    |
| rook-ceph-osd-1 | /dev/sdc  | /dev/sdc    |
| rook-ceph-osd-2 | /dev/sdf  | /dev/sdf    |

After the reboot, let's pretend `/dev/sdb` through `/dev/sde` were removed on the host that runs OSD 2:

| OSD deployment  | ROOK_BLOCK_PATH | Real device |
|-----------------|-----------|-------------|
| rook-ceph-osd-0 | /dev/sdd  | /dev/sdd    |
| rook-ceph-osd-1 | /dev/sdc  | /dev/sdc    |
| rook-ceph-osd-2 | **/dev/sdf**  | **/dev/sdb**    |

There's now a discrepancy between the deployment and the real device that holds the OSD's data. It seems that the operator eventually fixes this problem -- one cluster recovered on its own after about an hour. But having the option to use more stable device names would prevent such a delay and speed up OpenShift upgrades considerably.

**Environment**:
* OpenShift/OKD on VMware/vSphere
* `devicePathFilter` set so that Rook absorbs any disks attached to SCSI controller 1: `devicePathFilter: "^/dev/disk/by-path/pci-0000:13:00.0-scsi-.*"`
* `useAllDevices: false`
* Raw devices, no partitions, no LVM

## Further reading

https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/managing_storage_devices/assembly_overview-of-persistent-naming-attributes_managing-storage-devices#device-identifiers_assembly_overview-of-persistent-naming-attributes

**Comment by jskillin-idt** [comment]
Can this be reopened and considered?

**Comment by travisn** [comment]
Stable names can already be used for the OSD disks, and are certainly preferred, are you seeing it's not working? See [this example](https://github.com/rook/rook/blob/master/deploy/examples/cluster.yaml#L286).

**Comment by jskillin-idt** [comment]
This is the line that gives me trouble:
https://github.com/rook/rook/blob/v1.18.6/pkg/util/sys/device.go#L127

I've appreciated the autodiscovery making adding new disks extremely simple. Is it instead expected that an operator manually discovers and adds the disks by hand?

**Comment by jskillin-idt** [comment]
Also I apologize for my terse request earlier. I realize now that it was a rude or demanding comment, but I was just trying to check to see if this is something that was just forgotten. 🙂

**Comment by travisn** [comment]
> This is the line that gives me trouble: https://github.com/rook/rook/blob/v1.18.6/pkg/util/sys/device.go#L127

Can you expand on why listing the devices gives you trouble?

> I've appreciated the autodiscovery making adding new disks extremely simple. Is it instead expected that an operator manually discovers and adds the disks by hand?

Are you referring to adding the devices individually to the cluster CR instead of letting Rook auto discover them? 

When an OSD is provisioned based on the device name, internally Ceph will create a symlink to the device by id so that the OSD will not be affected by the device renames. 

> Also I apologize for my terse request earlier. I realize now that it was a rude or demanding comment, but I was just trying to check to see if this is something that was just forgotten. 🙂

No worries.
