### ISSUE TITLE
Will modifying the replication count result in data loss in a high-load cluster?

### ISSUE THREAD

**Issue by m1iktea** [rook/rook#14578]
**Is this a bug report or feature request?**
* Question

**Describe the problem details**
Currently, I have a Rook Ceph cluster with usage of approximately 15 terabytes out of 18 terabytes. I'm looking to reduce costs and intend to modify the `replicated.size` for both `spec.dataPools` and `spec.metadataPool` in the CephFilesystem CRD YAML file to 1. However, I'm concerned that reducing redundancy in this manner might lead to data loss, particularly in a high-load cluster environment.

```yaml
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  annotations: {}
  finalizers:
    - cephfilesystem.ceph.rook.io
  labels:
    k8slens-edit-resource-version: v1
  name: cephfs-nvme
  namespace: rook-ceph
  resourceVersion: '307553110'
spec:
  dataPools:
    - failureDomain: rack
      name: pool1
      replicated:
        size: 2
  metadataPool:
    erasureCoded:
      codingChunks: 0
      dataChunks: 0
    failureDomain: rack
    mirroring: {}
    quotas: {}
    replicated:
      size: 2
    statusCheck:
      mirror: {}
  metadataServer:
    activeCount: 3
    activeStandby: true
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/ceph-osd
                  operator: Exists
      tolerations:
        - key: cephosd
          value: 'true'
        - key: cephlocalstorage
          value: 'true'
    resources:
      limits:
        cpu: 2
        memory: 16Gi
      requests:
        cpu: 2
        memory: 16Gi
  preserveFilesystemOnDelete: false
  statusCheck:
    mirror: {}
```

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu.22.04
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.29.6 
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by travisn** [comment]
@m1iktea Reducing the redundancy to 1 is possible. Ceph will adjust the replicas down to 1 and not directly cause any data loss. However, replica 1 is **not recommended**. **The loss of any single OSD will cause the loss of all data in the pools.**
