### ISSUE TITLE
globalmount: permission denied

### ISSUE THREAD

**Issue by vadlakiran** [rook/rook#14587]
Hi Team,

we have installed rook-ceph on k8s cluster, we have installed the application as well in production, 3 worker nodes and 2 master node cluster, we are getting the permission denied to mount the path in worker1, only one pod having issue, other all pods are running fine even those are running on worker1, how i can resolve this issue ? and what is the root cause of this issue ? 

below are the logs:
-----------------------
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    117s                default-scheduler  Successfully assigned default/task-pv-pod to worker1
  Warning  FailedMount  53s (x8 over 117s)  kubelet            MountVolume.SetUp failed for volume "pvc-df9b64aa-5c90-4b17-9382-5dc677b19873" : rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-df9b64aa-5c90-4b17-9382-5dc677b19873/globalmount: permission denied
----------------------------

**How to reproduce it (minimal and precise):** not able to reproduce it on local setup

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
ceph status
  cluster:
    id:     cc9da5b7-2e86-4abc-971a-701ce9b3d532
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum c,e,f (age 8d)
    mgr: a(active, since 3h)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 8d), 3 in (since 4M)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 3.58k objects, 439 MiB
    usage:   2.0 GiB used, 1.8 TiB / 1.8 TiB avail
    pgs:     65 active+clean
 
  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr

  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 20
* Kernel (e.g. `uname -a`): Linux master1 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.8.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7 
* Kubernetes version (use `kubectl version`): v1.21.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): VMware
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
*

**Comment by vadlakiran** [comment]
@Rakshith-R  actually its tier 1 production environment, i would like to know the exactly what type of network fluctuations on worker node to cause this specific pvc got on issue ?

same worker node using osd thats why issue ?
if the network latest is there can increase the time to communicate the ceph-csi to avoid this issue in future ?

**Comment by microyahoo** [comment]
you can refer the ceph document https://docs.ceph.com/en/latest/cephfs/eviction/#automatic-client-eviction
> On an active MDS daemon, if a client has not communicated with the MDS for over session_autoclose (a file system variable) seconds (300 seconds by default), then it will be evicted automatically.

And you can set `mds_session_blocklist_on_evict` and `mds_session_blocklist_on_timeout` to false to permit re-open session and continue talking to OSDs automatically.
> It is possible to respond to slow clients by simply dropping their MDS sessions, but permit them to re-open sessions and permit them to continue talking to OSDs. To enable this mode, set mds_session_blocklist_on_timeout to false on your MDS nodes.
> 
> For the equivalent behaviour on manual evictions, set mds_session_blocklist_on_evict to false.

**Comment by vadlakiran** [comment]
@Rakshith-R  to unmount and remount the cephfs from the node, is there any impact on data ?

**Comment by Rakshith-R** [comment]
> @Rakshith-R to unmount and remount the cephfs from the node, is there any impact on data ? what is the case if once unmount and remount done if other pods not comes up, because not other pods are running the volume path is having permision denied only one pod is in crashloopbackoff

No, the mount point is already blocklisted by the ceph cluster for that pod. It doesn't affect other pods/volumes.
Just scale down and up that particular pod.


You maybe interested in using recover_session mount option too if network fluctuation in cluster is unavoidable.
https://docs.ceph.com/en/reef/man/8/mount.ceph/#basic

**Comment by vadlakiran** [comment]
@Rakshith-R 

could please see the logs of cephpluginrbd pods logs, why its locked and connection refused , is there a relation this and the specific pod 

[csi-cephfsplugin.txt](https://github.com/user-attachments/files/16707051/csi-cephfsplugin.txt)

**Comment by vadlakiran** [comment]
@Rakshith-R  Can i get any update on above logs which i shared

**Comment by vadlakiran** [comment]
@Rakshith-R 
completely scale down all the workloads using that PVC,
once i scale down the pod which are using that pvc, all went down its not deleting as well, still Teminating status only, 
without down the application is there any way to do it ?
can you please suggest the step by step please, 4 pods are running sepcific worker node which having issue and pvc using 4 pods and those pods are running in another worker nodes as well,

**Comment by Rakshith-R** [comment]
> @Rakshith-R is there any way we can see blocklisted list ?
> 
> could please see the logs of cephpluginrbd pods logs, why its locked and connection refused , is there a relation this and the specific pod
> 
> [csi-cephfsplugin.txt](https://github.com/user-attachments/files/16707051/csi-cephfsplugin.txt)

There seems to be some network issue on that node, you need to resolve that first.
None of the containers are able to communicate with k8s api server.
```
E0731 01:58:08.538611       1 leaderelection.go:330] error retrieving resource lock rook-ceph/external-attacher-leader-rook-ceph-cephfs-csi-ceph-com: Get "https://10.233.0.1:443/apis/coordination.k8s.io/v1/namespaces/rook-ceph/leases/external-attacher-leader-rook-ceph-cephfs-csi-ceph-com": dial tcp 10.233.0.1:443: connect: no route to host
```




> @Rakshith-R completely scale down all the workloads using that PVC, once i scale down the pod which are using that pvc, all went down its not deleting as well, still Teminating status only, without down the application is there any way to do it ? can you please suggest the step by step please, 4 pods are running sepcific worker node which having issue and pvc using 4 pods and those pods are running in another worker nodes as well,

Please resolve the above issue first with respect to the network.
Maybe try restarting the node ?

**Comment by vadlakiran** [comment]
@Rakshith-R we have resolved the network issue, its automatically came back and we have done steps you have provided and now issue got resolved 
But i can see still the mgr pod ip got blocklisted i can see in the ceph osd dump

]$ ceph osd dump
epoch 2363
fsid cc9da5b7-2e86-4abc-971a-701ce9b3d532
created 2023-06-06T01:35:50.252328+0000
modified 2024-08-26T12:28:14.336350+0000
flags sortbitwise,recovery_deletes,purged_snapdirs,pglog_hardlimit
crush_version 43
full_ratio 0.95
backfillfull_ratio 0.9
nearfull_ratio 0.85
require_min_compat_client luminous
min_compat_client jewel
require_osd_release quincy
stretch_mode_enabled false
pool 1 '.mgr' replicated size 3 min_size 2 crush_rule 0 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 1218 flags hashpspool stripe_width 0 pg_num_min 1 application mgr,mgr_devicehealth
pool 2 'myfs-metadata' replicated size 3 min_size 2 crush_rule 1 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 1468 flags hashpspool stripe_width 0 compression_mode none pg_autoscale_bias 4 pg_num_min 16 recovery_priority 5 application cephfs
pool 3 'myfs-replicated' replicated size 3 min_size 2 crush_rule 2 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 1469 flags hashpspool stripe_width 0 compression_mode none application cephfs
max_osd 3
osd.0 up   in  weight 1 up_from 2111 up_thru 2111 down_at 2109 last_clean_interval [1308,2110) [v2:10.233.110.40:6800/3118827730,v1:10.233.110.40:6801/3118827730] [v2:10.233.110.40:6808/3119827730,v1:10.233.110.40:6809/3119827730] exists,up 65b693e5-1abe-4f0e-8785-32cdb8dfa5e5
osd.1 up   in  weight 1 up_from 2111 up_thru 2111 down_at 2109 last_clean_interval [1307,2110) [v2:10.233.103.212:6800/237328967,v1:10.233.103.212:6801/237328967] [v2:10.233.103.212:6808/238328967,v1:10.233.103.212:6809/238328967] exists,up 70fc96d5-783c-4471-84ec-0b676b17b3ef
osd.2 up   in  weight 1 up_from 1478 up_thru 2111 down_at 1474 last_clean_interval [1308,1472) [v2:10.233.116.197:6800/1278026571,v1:10.233.116.197:6801/1278026571] [v2:10.233.116.197:6802/1278026571,v1:10.233.116.197:6803/1278026571] exists,up a21ae0f7-4ccb-4cf3-9f51-393b5a39f876
blocklist 10.233.110.55:6801/3733040993 expires 2024-08-27T11:40:45.152763+0000
blocklist 10.233.110.55:6800/3733040993 expires 2024-08-27T11:40:45.152763+0000
blocklist 10.233.110.55:0/2221299289 expires 2024-08-27T11:40:45.152763+0000
blocklist 10.233.110.55:0/1116916521 expires 2024-08-27T11:40:45.152763+0000
blocklist 10.233.110.55:0/3671819300 expires 2024-08-27T11:40:45.152763+0000
blocklist 10.233.110.55:6801/677986535 expires 2024-08-27T00:56:57.338830+0000
blocklist 10.233.110.55:6800/677986535 expires 2024-08-27T00:56:57.338830+0000
blocklist 10.233.110.55:0/3326219197 expires 2024-08-27T00:56:57.338830+0000
blocklist 10.233.110.55:0/1461519170 expires 2024-08-27T00:56:57.338830+0000
blocklist 10.233.110.55:0/438355246 expires 2024-08-27T00:56:57.338830+0000
blocklist 10.233.110.55:0/1502828088 expires 2024-08-27T11:40:45.152763+0000
blocklist 10.233.110.55:0/3717822984 expires 2024-08-27T00:56:57.338830+0000
blocklist 10.233.110.55:6801/3838075034 expires 2024-08-26T14:12:52.037392+0000
blocklist 10.233.110.55:6800/3838075034 expires 2024-08-26T14:12:52.037392+0000
blocklist 10.233.110.55:0/3981263190 expires 2024-08-26T14:12:52.037392+0000
blocklist 10.233.110.55:0/701415942 expires 2024-08-26T14:12:52.037392+0000
blocklist 10.233.110.55:0/3477460550 expires 2024-08-26T14:12:52.037392+0000
blocklist 10.233.110.55:0/603428856 expires 2024-08-26T14:12:52.037392+0000

we have restarted the mgr pod and after sometime its getting blocked, why what is the reason ?

**Comment by vadlakiran** [comment]
@Rakshith-R  any suggestion on above issue ?

**Comment by Rakshith-R** [comment]
>But i can see still the mgr pod ip got blocklisted i can see in the ceph osd dump

I'm not sure about this. Maybe try asking on ceph slack or mailing list if it still persists.

**Comment by wkjun** [comment]
this  work  for me .

on the node which pod scheduled do these commands

```
# force umount the mount point
umount  -lf /var/lib/kubelet/plugins/kubernetes.io/csi/cephfs.csi.ceph.com/1e41725250b8e8696c0a243285a60ed38cc3095b043d2cda899048cb1a01e339/globalmount
# remove the json file
rm /var/lib/kubelet/plugins/kubernetes.io/csi/cephfs.csi.ceph.com/1e41725250b8e8696c0a243285a60ed38cc3095b043d2cda899048cb1a01e339/vol_data.json
# restart kubelet
systemctl restart kubelet
```
