### ISSUE TITLE
OSD pod never come back up after upgrade

### ISSUE THREAD

**Issue by electricstrm-redgate** [rook/rook#14596]
* Bug Report

**Deviation from expected behavior:**
The osd pod never recovered. It crashed a little and then was just 0/1.
I saw the prepare set pod jus stay pending saying it couldn't find a node that had a volume.

Upgrading 
Rook: 1.13.2 to  1.14.7
ceph: v17.2.1 to 18.2.2

**Expected behavior:**

All pods are running.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

This event was in the osd pod.

 Startup probe failed: ceph daemon health check failed with the following output:
> admin_socket: exception getting command descriptions: [Errno 2] No such file or directory

**Cluster Status to submit**:
health check failed

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
 
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"

* Kernel (e.g. `uname -a`):

Linux NHARGC101 5.14.0-284.11.1.el9_2.x86_64 [#1](https://redgatesupport.zendesk.com/agent/tickets/1) SMP PREEMPT_DYNAMIC Wed Apr 12 10:45:03 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
 On premise.

* Rook version (use `rook version` inside of a Rook Pod): 1.14.7
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.2
* Kubernetes version (use `kubectl version`):  1.29

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Installed with kurl

**Comment by travisn** [comment]
Do you have the logs with more error details? There isn't much to go on here.

**Comment by electricstrm-redgate** [comment]
Unfortunately trying to get logs returned nothing else.
This also happened on a customer production load. They've now restored from backup and are reticent to try to deploy our latest release.  I'll try replicating the problem, but i t may be a few days before i get to do that.
