### ISSUE TITLE
build: Makefile problem on Mac

### ISSUE THREAD

**Issue by obnoxxx** [rook/rook#14603]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

`make test`fails with an include  error   on MacOS for current and plain master:

```console

$ make test       
build/makelib/golang.mk:27: *** please set GO_STATIC_PACKAGES prior to including golang.mk.  Stop.

$
```
The same happens for other make  targets like `make crds`, `make go.vet`, `make mod.check`, etc.

It does **not** happen on Linux for me.

**Expected behavior:**

This error calling `make` should not occur. Targets should execute as usual. 

**How to reproduce it (minimal and precise):**

* set up golang, git, and make on the host.
* `git clone` the rook repository
* `cd rook`
* `make test`

**File(s) to submit**:

** None** (not applicable.)

**Logs to submit**:

None (not applicable)

**Cluster Status to submit**:

Not applicable.

**Environment**:
* OS (e.g. from /etc/os-release): MacOS sonoma 14.6.1
* Kernel (e.g. `uname -a`): `Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64` 
* Cloud provider or hardware configuration: Apple M3 Pro chip, 36 GB RAM.
*
* Rook version (use `rook version` inside of a Rook Pod): current master

**Comment by BlaineEXE** [comment]
I have hit this before. I think these vars have been able to help `GOOS='linux' GOARCH="$($GO env GOARCH)"`.

You might also try putting the repo into the go src dir (at `$HOME/go/src/github/rook/rook`) if it isn't already. There were some tooling things that assumed that location, but I'm not sure if that's still true.

**Comment by obnoxxx** [comment]
@BlaineEXE  wrote:
> I have hit this before. I think these vars have been able to help `GOOS='linux' GOARCH="$($GO env GOARCH)"`.

Interesting: Setting these seems to have helped!

* `make go.vet`, and `make go.fmt`, and `make build` work and succeed now.
*  `make tes`does at least start but still fails with the exec format error I mentioned elsewhere.  (I guess I should create a separate issue for that...) 

> You might also try putting the repo into the go src dir (at `$HOME/go/src/github/rook/rook`) if it isn't already.

It was already there.  so this was not the issue :) 

> There were some tooling things that assumed that location, but I'm not sure if that's still true.


Thanks for your help!

Att least I can continue working in my Mac dev environment now.
But I would not claim to understand how and why `GOOS`and `GOARCH` would influence the Makefile behavior regarding the `GO_STATIC_PACKAGES`variable.

**Comment by obnoxxx** [comment]
This has not happened since a while (a few weeks). I guess we can close it.
