### ISSUE TITLE
mds livenessprobe RADOS permission denied

### ISSUE THREAD

**Issue by chri4774** [rook/rook#14665]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Hello, 
I'm not sure if this problem is on my end or a bug in rook-ceph. I've noticed in our clusters that the livenessProbe-script for the mds-pods (see https://github.com/rook/rook/blob/v1.14.7/pkg/operator/ceph/file/mds/livenessprobe.sh ) isn't really working correctly because the permission to run the "ceph fs dump" command is  denied. (output see below)

Because the script is always exiting at this step with return code 0 (see Line 11 - 16), under normal conditions this error remains unnoticed.

However when doing maintenance on a k8s node and a mon-pod is down, this becomes a problem. The ceph command is hanging in a retry loop and as soon as the timeout of livenessProbe has passed it fails. 
If the mon-pod is offline long enough  and the failureThreshold of the livenessprobe is reached, the mds container will be restarted by kubernetes. When this happens on both mds pods at the same time this will lead to an offline situation.

This issue is happening across all our stages. Apart from this issue there are no problems with the clusters. Health is in status OK, and running the "ceph fs dump" command from the ceph toolbox is working correctly.

Workaround:
Editing the cephfilesystem CR and setting "spec.metadataServer.livenessProbe.disabled: true" mitigates the issue.

**Expected behavior:**
The "ceph fs dump" command in the mds livenessProbe script should be successful when the cluster is healthy

**How to reproduce it (minimal and precise):**
Get livenessProbe script from deployment
```
$ kubectl get deploy <MDS-DEPLOYMENT-NAME> -n rook-ceph -o jsonpath='{.spec.template.spec.containers[0].livenessProbe.exec.command[4]}'`

#!/usr/bin/env bash
# do not use 'set -e -u' etc. because it is important to only fail this probe when failure is certain
# spurious failures risk destabilizing ceph or the filesystem

MDS_ID="myfs-a"
FILESYSTEM_NAME="myfs"
KEYRING="/etc/ceph/keyring-store/keyring"

outp="$(ceph fs dump --mon-host="$ROOK_CEPH_MON_HOST" --mon-initial-members="$ROOK_CEPH_MON_INITIAL_MEMBERS" --keyring "$KEYRING" --format json)"
rc=$?
if [ $rc -ne 0 ]; then
    echo "ceph MDS dump check failed with the following output:"
    echo "$outp"
    echo "passing probe to avoid restarting MDS. cannot determine if MDS is unhealthy. restarting MDS risks destabilizing ceph/filesystem, which is likely unreachable or in error state"
    exit 0
fi

# get the active and standby MDS in the fs map
standbyMds=$(echo "$outp" | jq ".standbys | map(.name) | any(.[]; . == \"$MDS_ID\")")
activeMds=$(echo "$outp" | jq ".filesystems[] | select(.mdsmap.fs_name == \"$FILESYSTEM_NAME\") | .mdsmap.info | map(.name) | any(.[]; . == \"$MDS_ID\")")

if [[ $standbyMds == true || $activeMds == true ]]; then
    echo "MDS ID present in MDS map, no need to re-start the container"
    exit 0
fi

echo "Error: MDS ID not present in MDS map"
exit 1
```
kubectl exec into MDS-Pod
```
kubectl exec -it <MDS-POD> -n rook-ceph -- bash
```
Copy/Paste the livenessProbe script to a file and run the script
```
$ cat > /tmp/liveness.sh
...
$ sh /tmp/liveness.sh
2024-08-27T13:36:24.730+0000 7f930220f700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-27T13:36:24.731+0000 7f9301a0e700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-27T13:36:24.731+0000 7f930120d700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
[errno 13] RADOS permission denied (error connecting to the cluster)
ceph MDS dump check failed with the following output:

passing probe to avoid restarting MDS. cannot determine if MDS is unhealthy. restarting MDS risks destabilizing ceph/filesystem, which is likely unreachable or in error state

$ echo $?
0
```
In order to reproduce the hanging livenessProbe you have to shutdown one mon first. (script runs forever)
```
$ kubectl scale deploy rook-ceph-operator -n rook-ceph --replicas 0
$ kubectl scale deploy rook-ceph-mon-a -n rook-ceph --replicas 0

$ kubectl exec -it <MDS-POD> -n rook-ceph -- bash
$ sh /tmp/liveness.sh
2024-08-30T11:21:55.929+0000 7f93bdd9b700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-30T11:21:55.933+0000 7f93be59c700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-30T11:21:58.934+0000 7f93bdd9b700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-30T11:21:58.937+0000 7f93bed9d700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-30T11:22:01.933+0000 7f93bdd9b700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-30T11:22:01.933+0000 7f93be59c700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-30T11:22:04.933+0000 7f93be59c700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-30T11:22:04.934+0000 7f93bdd9b700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
2024-08-30T11:22:07.935+0000 7f93bed9d700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
...
```

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux 9.4 (Plow)
* Kernel (e.g. `uname -a`): 5.14.0-427.22.1.el9_4.x86_64
* Rook version (use `rook version` inside of a Rook Pod): v1.14.7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)
* Kubernetes version (use `kubectl version`): v1.30.3+rke2r1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by microyahoo** [comment]
similar issue: https://github.com/rook/rook/issues/11475

**Comment by parth-gr** [comment]
I think mon should be in quorum to run any ceph command, so here looks like the same scenario, 
As Mons should be healthy before executing any ceph operation, right?

**Comment by BlaineEXE** [comment]
In some ways, I think this looks like the probe behaving as expected. The probe is not able to connect to the mons (reason TBD), and just as the message says, it doesn't restart the MDS so as not to disrupt the cluster. This is the safest behavior when treating Ceph as a distributed system.

In other ways, I still have concerns around having liveness probes in Rook at all, so I want to make sure to do our due diligence here.

@travisn does this line look like a msgr v2 log, from your experience?

```
2024-08-27T13:36:24.730+0000 7f930220f700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2,1]
```

I'm thinking that the connection issue here could be that v2-only is enabled, and possibly the MDS isn't aware of that. I'm not sure if this could be an upgrade corner case, or potentially something else.

**Comment by travisn** [comment]
Yes that line does look like from the msgr, though not sure if it's specific to v2. 

I wonder if we need to pass a timeout flag to the `ceph fs dump` command so it doesn't then cause the liveness probe to hang and timeout. If the dump isn't timely in its response, agreed we don't want to fail the liveness probe.

**Comment by chri4774** [comment]
I did some more research on my own and wonder whether the mds keyring is supposed to work with running ceph commands for the livenessprobe at all.
When looking at the keyringfile inside the mds pod I see
```
[root@rook-ceph-mds-myfs-a-76b7c9f94f-7dq22 tmp]# cat /etc/ceph/keyring-store/keyring

[mds.myfs-a]
key = <OBFUSCATED>
caps mon = "allow profile mds"
caps osd = "allow *"
caps mds = "allow"
```
Doing the same inside a mon pod (where the "ceph fs dump" command works) I see

```
[root@rook-ceph-mon-a-58b8f6cd5f-c4ptb ceph]# cat /etc/ceph/keyring-store/keyring

[mon.]
        key = <OBFUSCATED>
        caps mon = "allow *"


[client.admin]
        key = <OBFUSCATED>
        caps mds = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"
        caps mgr = "allow *"
```

Creating a new keyring file with the existing mds-keyring and the existing client.admin-keyring and using that file for the livenessprobe script or directly with the "ceph fs dump" command it works.

```
[root@rook-ceph-mds-myfs-a-76b7c9f94f-7dq22 ceph]# cat > /tmp/keyring
[mds.myfs-a]
key = <OBFUSCATED>
caps mon = "allow profile mds"
caps osd = "allow *"
caps mds = "allow"

[client.admin]
key = <OBFUSCATED>
caps mds = "allow *"
caps mon = "allow *"
caps osd = "allow *"
caps mgr = "allow *"

[root@rook-ceph-mds-myfs-a-76b7c9f94f-7dq22 ceph]# ceph fs dump --mon-host="$ROOK_CEPH_MON_HOST" --mon-initial-members="$ROOK_CEPH_MON_INITIAL_MEMBERS" --keyring "/tmp/keyring" --format json
...
...
dumped fsmap epoch 389

### <edit KEYRING variable in /tmp/liveness.sh> ###

[root@rook-ceph-mds-myfs-a-76b7c9f94f-7dq22 ceph]# sh /tmp/liveness.sh
dumped fsmap epoch 389
MDS ID present in MDS map, no need to re-start the container

[root@rook-ceph-mds-myfs-a-76b7c9f94f-7dq22 ceph]# echo $?
0
```
