### ISSUE TITLE
https://charts.rook.io is unreachable

### ISSUE THREAD

**Issue by steven-sheehy** [rook/rook#1467]
**Bug Report**

What happened:
[https://charts.rook.io](https://charts.rook.io) is unreachable. It is mentioned in the published [documentation](https://rook.github.io/docs/rook/v0.6/helm-operator.html) for v0.6 so I thought I would be able to connect to it.

What you expected to happen:
charts.rook.io should be reachable

How to reproduce it (minimal and precise):
````shell
$ helm repo add rook-alpha https://charts.rook.io/alpha
Error: Looks like "https://charts.rook.io/alpha" is not a valid chart repository or cannot be reached: Get https://charts.rook.io/alpha/index.yaml: dial tcp: lookup charts.rook.io on 10.0.22.45:53: no such host

```

**Comment by travisn** [comment]
there is a temporary dns resolution issue while the `rook.io` domain is being transferred to the cncf that hopefully will be resolved soon

**Comment by steven-sheehy** [comment]
Looks like it is back up. Thanks
