### ISSUE TITLE
Core dumps are not being created.

### ISSUE THREAD

**Issue by palthisailohith** [rook/rook#14681]
Hi team,
We are unable to see core dumps created for the crashes on the respective nodes,what can be the issue?
Environment:
Kubernetes version: v1.25.9
Rook version: v1.10.8
Ceph version: v17.2.5
OS:ubuntu 20.04.6 LTS (focal fossa)
We have already enabled logcollector also but still can't see any core dumps created. This is working fine with CENTOS servers but on UBUNTU servers core files are not getting created after OSD crashes with the same settings.

**Comment by palthisailohith** [comment]
Can someone help in this issue,this is in production.
@Madhu-1 @Rakshith-R @sudharsanomprakash

**Comment by travisn** [comment]
Have you enabled apport? Not sure if [this thread](https://askubuntu.com/questions/1349047/where-do-i-find-core-dump-files-and-how-do-i-view-and-analyze-the-backtrace-st) is helpful, but it does indicate core dumps are not enabled by default in ubuntu stable releases.

**Comment by palthisailohith** [comment]
> Have you enabled apport? Not sure if [this thread](https://askubuntu.com/questions/1349047/where-do-i-find-core-dump-files-and-how-do-i-view-and-analyze-the-backtrace-st) is helpful, but it does indicate core dumps are not enabled by default in ubuntu stable releases.

Yes,apport is enabled on all the servers. Any other parameters to enable?

**Comment by palthisailohith** [comment]
@travisn Are there any other parameters we can check?

**Comment by travisn** [comment]
Not that I am familiar with, I'm hoping someone else in the community may be aware
