### ISSUE TITLE
RGW: shared pools: extra `<storename>.rgw.meta` pool created

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#14708]
One issue I (Travis) noticed [with shared pools] is that an extra pool is created automatically. For example, if I create an object store named `store-d`, a pool will appear called `store-d.rgw.meta`. This could be a result of Squid, or maybe some other issue since I don't recall seeing this extra pool before.

_Originally posted by @travisn in https://github.com/rook/rook/issues/14588#issuecomment-2334832033_

Let's look into this to see if we can get this defined in the store/zone spec to go into an existing pool. Probably the existing `.rgw.meta` pool is the right place.

**Comment by travisn** [comment]
Ok, I was not able to repro this in v18.2.2, but it does repro in v19.1.1. As soon as upgrading to v19.1.1, the pool `store-a.rgw.meta` was unexpectedly created.

@cbodley What might have changed to cause this new `store-a.rgw.meta` pool to be created? Did we miss something in the zone config so it would be configured as a rados namespace instead of causing the new pool to be created?

Here is the zone config. 
```json
{
    "id": "819087c0-21ca-4bd2-a468-6f1451b7b4c9",
    "name": "store-a",
    "domain_root": "rgw-meta-pool:store-a.meta.root",
    "control_pool": "rgw-meta-pool:store-a.control",
    "gc_pool": "rgw-meta-pool:store-a.log.gc",
    "lc_pool": "rgw-meta-pool:store-a.log.lc",
    "log_pool": "rgw-meta-pool:store-a.log",
    "intent_log_pool": "rgw-meta-pool:store-a.log.intent",
    "usage_log_pool": "rgw-meta-pool:store-a.log.usage",
    "roles_pool": "rgw-meta-pool:store-a.meta.roles",
    "reshard_pool": "rgw-meta-pool:store-a.log.reshard",
    "user_keys_pool": "rgw-meta-pool:store-a.meta.users.keys",
    "user_email_pool": "rgw-meta-pool:store-a.meta.users.email",
    "user_swift_pool": "rgw-meta-pool:store-a.meta.users.swift",
    "user_uid_pool": "rgw-meta-pool:store-a.meta.users.uid",
    "otp_pool": "rgw-meta-pool:store-a.otp",
    "system_key": {
        "access_key": "",
        "secret_key": ""
    },
    "placement_pools": [
        {
            "key": "default-placement",
            "val": {
                "index_pool": "rgw-meta-pool:store-a.buckets.index",
                "storage_classes": {
                    "STANDARD": {
                        "data_pool": "rgw-data-pool:store-a.buckets.data"
                    }
                },
                "data_extra_pool": "rgw-meta-pool:store-a.buckets.non-ec",
                "index_type": 0,
                "inline_data": true
            }
        }
    ],
    "realm_id": "cce1bdf6-4ebd-4f03-971e-155b79a957b4",
    "notif_pool": "rgw-meta-pool:store-a.log.notif"
}
```

**Comment by cbodley** [comment]
hey @BlaineEXE, @travisn 

squid adds some new pools to the zone definition. make sure you're doing the same shared-pool substitution for those:
```
    "topics_pool": "default.rgw.meta:topics",
    "account_pool": "default.rgw.meta:accounts",
    "group_pool": "default.rgw.meta:groups",
```

**Comment by BlaineEXE** [comment]
@cbodley how can we get updates about when changes like this are coming down the Ceph RGW release pipeline?

**Comment by cbodley** [comment]
> @cbodley how can we get updates about when changes like this are coming down the Ceph RGW release pipeline?

i don't have a good answer for that, but perhaps it would be worth adding regression test coverage for this shared pool feature?

**Comment by travisn** [comment]
@arttor Could you pick this up since you were touching the related code recently? Thanks!
