### ISSUE TITLE
Configure prio-limit for ceph exporter container

### ISSUE THREAD

**Issue by arttor** [rook/rook#14710]
When Rook creates Ceph exporter container, it provides configuration [as container arguments](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/nodedaemon/exporter.go#L183-L186). Hovewer, the value for  `--prio-limit`  is [hardcoded to "5"](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/nodedaemon/exporter.go#L45). This option defines which performance conunters will be exported. We need to set this option to "0" to export all counters for our use-case. Is it feasible to make this option configuragble with Rook helm chart?

I am not sure what will be the best place for this configuration. If i got it right, the only existing opion relevant to exporter is [`metricsDisabled`](https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L387) in `cephCluster.Spec.Monitoring` CRD. Will it be possible to add `cephExporterPrioLimit: 0` option there?

**Comment by travisn** [comment]
Yes, makes sense to make it configurable via the cephcluster CR. What about this path? Then we can have other settings for exporter in the future if needed: `spec.monitoring.exporter.prioLimit`

**Comment by arttor** [comment]
@travisn `spec.monitoring.exporter.prioLimit` looks better. If it is ok, i will start implementation.
