### ISSUE TITLE
Allow custom annotations on crash collector deployments

### ISSUE THREAD

**Issue by francescsanjuanmrf** [rook/rook#14729]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Allow the configuration of custom annotations on crash collector deployments.

https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L265-L273

**What is use case behind this feature:**

Istio (istioctl analyze) is reporting this warning:

_Warning [IST0117] (Deployment rook-ceph/rook-ceph-crashcollector-worker01) No service associated with this deployment. Service mesh deployments must be associated with a service._

However, since the deployment does not have any listening ports, it doesn't make sense to create a service. To prevent this warning, we should add the following annotation to the deployment:

`galley.istio.io/analyze-suppress: IST0117`

This feature is also needed for applying other Istio configurations.

https://istio.io/latest/docs/reference/config/annotations/

**Comment by sp98** [comment]
@francescsanjuanmrf can you please add more details about the use case in the description.  The links are definitely helpful but more details in the description will help.

**Comment by francescsanjuanmrf** [comment]
Hi @sp98 !
Added more info about the use case
