### ISSUE TITLE
Document and clarify the relationship between cephCluster.spec.cephConfig and rook-ceph-override cm

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#14736]
https://github.com/rook/rook/pull/13246 introduced `cephCluster.spec.cephConfig` which provides similar functionality to the existing `rook-ceph-override` cm.

The current docs indicate that this feature is `experimental`:

https://github.com/rook/rook/blob/d4f3bf3f2cff7b30738eef9e9e4fab844376f773/Documentation/CRDs/Cluster/ceph-cluster-crd.md?plain=1#L828-L829

As there are two mechanism that both create ceph config values, we should document the relationship between them.  Including at least:

- Is `cephConfig` intended to replace `rook-ceph-override`?
- When should `cephConfig` be considered a stable feature?
- Which mechanism should users prefer / be encouraged to use?
- If conflicting config values are set, which takes precedence?
- Is `rook-ceph-override` going to be deprecated?

**Comment by travisn** [comment]
Please review #14752 to see if this clarifies those questions.

Also note that some of these questions may already have been addressed in the [ceph.conf topic](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-configuration/#custom-cephconf-settings).
