### ISSUE TITLE
Improvement on CephOSDFlapping expr in example monitoring rules

### ISSUE THREAD

**Issue by larsknutson** [rook/rook#14756]
* Bug Report

`CephOSDFlapping` alert rule in https://github.com/rook/rook/blob/master/deploy/examples/monitoring/localrules.yaml

**Deviation from expected behavior:**
`CephOSDFlapping` alert rule is using the expr: 

`(rate(ceph_osd_up[5m]) * on(ceph_daemon) group_left(hostname) ceph_osd_metadata) * 60 > 1`

ceph_osd_up is a gauge and would be more useful to use changes() to track amount of times this flips (or flaps). Noticed this when the thanos in cluster warned about using rate on a non-counter metric.

**Expected behavior:**
Warn when the ceph_osd_up gauge has flipped over X number of times in a time interval to indicated flapping.

Possible new expr for `CephOSDFlapping`: 

`(changes(ceph_osd_up[5m]) * on(ceph_daemon) group_left(hostname) ceph_osd_metadata) > 5`

https://prometheus.io/docs/prometheus/latest/querying/functions/#changes

**Environment**:
* Kubernetes version (use `kubectl version`): 4.16.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift

Thanks! :)

**Comment by travisn** [comment]
@larsknutson Have you tested this in your cluster to confirm the expected improvement?

Rook picked up the original prometheus rules from the [ceph repo](https://github.com/ceph/ceph/commits/main/monitoring/ceph-mixin/prometheus_alerts.yml). Ideally, any changes to the rules would be made there first with the core ceph team to review, then Rook would pick it up. Would you mind opening a [Ceph tracker](https://tracker.ceph.com/) for this suggestion? We don't really need to wait for a fix to merge to ceph first, but would be helpful to get review from them first. Thanks!
