### ISSUE TITLE
Including vendor pkgs

### ISSUE THREAD

**Issue by rootfs** [rook/rook#1478]
Is this a bug report or feature request?
* Bug Report

Include vendor repos 

**Bug Report**

What happened:
Currently vendor repos are not committed or tracked, but in event that repos disappears, there will be troubles. This is best seen in https://github.com/jteeuwen/go-bindata/issues/5

What you expected to happen:
All vendor pkgs need to be part of the repo

**Comment by rootfs** [comment]
cc @bassam

**Comment by galexrt** [comment]
Closing as written in https://github.com/rook/rook/pull/2061#issuecomment-416628159.
