### ISSUE TITLE
The mirror ID is missing the letter 'v'

### ISSUE THREAD

**Issue by lyitt1987** [rook/rook#14822]
git clone --single-branch --branch v1.15.3 https://github.com/rook/rook.git

$ grep cephcsi/cephcsi operator.yaml 
  # ROOK_CSI_CEPH_IMAGE: "quay.io/cephcsi/cephcsi:3.12.2"
The mirror ID is missing the letter 'v'

![image](https://github.com/user-attachments/assets/1d8bbf4e-229e-4cb8-8836-e9812544d366)

**Comment by Madhu-1** [comment]
@lyitt1987 feel free to send a PR , its missing here https://github.com/rook/rook/blob/0465908912a1190aeaab3114d27a192e880cb2bc/deploy/examples/operator.yaml#L130. let me know if you want us to take care of it.
