### ISSUE TITLE
RGW: Ceph managers enter in a crashloop.

### ISSUE THREAD

**Issue by dgonzalezruiz** [rook/rook#1483]
**Bug Report**

Ceph MGRs enter in a crashloop all of a sudden when the replica count if an objectstore is bigger than 1

How to reproduce it (minimal and precise):
Just set the replicacount to any natural number bigger than 1. The issue is that the rados gateways run all with the same name, and do not have any random suffix to them.

**Comment by travisn** [comment]
@dgonzalezruiz you are referring to the replica count of the rgw deployment, right? I tried a couple of different configurations and am not seeing the mgr crash. Could there be some other step to the repro? I did the following:
- Start minikube and create the 1-node rook cluster
- Edit rook-object.yaml to set the gateway instances to 3
- kubectl create -f rook-object.yaml
- Three rgw instances started successfully. The mgr pod has continued running for several minutes without crashing.
- kubectl edit deploy rook-ceph-rgw --> change the replicacount to 5
- Two more rgw pods started successfully and I have not seen the mgr crash yet.

**Comment by dgonzalezruiz** [comment]
Hi @travisn 

I haven't been able to reproduce this either in the minikube setup. This does impact both my stage and "production" clusters, though. Editing the deployment and setting the rgw host property to $HOSTNAME solves the issue, with whichever replica count of the rgw deployment. The only reason why I find this necessary is because of both the reason above (it solves the situation in my cluster) and also http://lists.ceph.com/pipermail/ceph-users-ceph.com/2017-September/020712.html

Please let me know if I can provide more insights!
