### ISSUE TITLE
Recovery Throughput Not Displayed in Ceph Dashboard After Upgrade to 19.2.0 (Squid)

### ISSUE THREAD

**Issue by SanjayM0han** [rook/rook#14874]
Hello Ceph Community,

I recently upgraded my Ceph cluster through the following versions:

17.2.7 >> 18.2.0 >> 18.2.2 >> 18.2.4 >> 19.2.0 (Squid)
After successfully upgrading to Ceph 19.2.0, I noticed that the recovery throughput is no longer visible in the new Ceph dashboard. However, old dashboard features and metrics appear to be functioning correctly, and the recovery throughput was displayed properly in the previous version of the Ceph dashboard. I am using Cephadm not rook for installation.

Old Dashboard

![96edbbc2-b053-4fb8-b9d5-f21a10007489](https://github.com/user-attachments/assets/88bd7d36-6773-4d1b-8612-3f1d884d6d6f)

New Dashboard

![aa9d73a0-df6d-4de9-963c-3880b99c39d7](https://github.com/user-attachments/assets/abe10c77-8355-47e2-8aff-263369b997f7)

Steps to reproduce:

Upgrade Ceph cluster from 17.2.7 to 19.2.0.
Access the Ceph dashboard.
Check for recovery throughput metrics in the new dashboard.
Current behavior:

Recovery throughput is not displayed in the new Ceph dashboard after upgrading.
Expected behavior:

Recovery throughput should be visible as it was in the previous versions of the Ceph dashboard.
Has anyone else encountered this issue, or are there any known fixes or workarounds? I would appreciate any insights or suggestions.

**Comment by travisn** [comment]
Please report dashboard issues with a [Ceph tracker issue](https://tracker.ceph.com/).
