### ISSUE TITLE
Pod using more than one Rook StorageClass causes failures

### ISSUE THREAD

**Issue by r0xsh** [rook/rook#1487]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

Rook can't mount fs inside a Pod :cry: 

###### Agent log
```
flexdriver: Attach volume replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 failed: failed to attach volume replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136: failed to map image replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 cluster rook. failed to map image replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136: Failed to complete rbd: exit status 2. output: rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (2) No such file or directory
```
###### `dmesg | tail` the Agent
```
[ 1098.570293] rbd: image replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 does not exist
[ 1100.854701] rbd: image replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 does not exist
[ 1105.231922] rbd: image replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 does not exist
[ 1113.427384] rbd: image replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 does not exist
[ 1129.775981] rbd: image replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 does not exist
[ 1139.936904] XFS (rbd0): Mounting V5 Filesystem
[ 1140.080881] XFS (rbd0): Ending clean mount
[ 1162.087742] rbd: image replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 does not exist
[ 1226.293773] rbd: image replicapool-hdd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 does not exist
```
> At this moment I tell myself that there is a problem when creating the volume !

But wait a minute.. here are the logs of the operator !

```
2018-02-12 15:43:06.692420 I | op-provisioner: creating volume with configuration {pool:replicapool-ssd clusterName:rook fstype:xfs}
2018-02-12 15:43:06.692440 I | exec: Running command: rbd create replicapool-ssd/pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136 --size 25600 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring
2018-02-12 15:43:08.160175 I | exec: Running command: rbd ls -l replicapool-ssd --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json
2018-02-12 15:43:08.231006 I | op-provisioner: Rook block image created: pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136
2018-02-12 15:43:08.231051 I | op-provisioner: successfully created Rook Block volume &amp;FlexVolumeSource{Driver:rook.io/rook,FSType:xfs,SecretRef:nil,ReadOnly:false,Options:map[string]string{image: pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136,pool: replicapool-hdd,storageClass: rook-block-ssd,},}
```

On my server I installed
* RBD Kernel module :green_heart: 
* Ceph `via yum install ceph ceph-common` :green_heart: 

I feel like I have already tried everything :(

What you expected to happen:

A running pod :hear_no_evil: :tada: 

How to reproduce it (minimal and precise):

`kubectl create -f rook-operator.yaml` the one i found on master

My `rook-cluster.yaml` look like this :
```
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  backend: ceph
  dataDirHostPath: /var/lib/rook
  hostNetwork: false
  monCount: 3
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    metadataDevice:
    location:
    storeConfig:
      storeType: bluestore
    nodes:
    - name: "panda"
      location: "root=hdd"
      directories:
      - path: "/storage"
    - name: "ninja"
      location: "root=ssd"
      directories:
      - path: "/storage"
```

And I created two `storageclass`
```
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool-hdd
  namespace: rook
spec:
  replicated:
    size: 1
  crushRoot: hdd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-block-hdd
provisioner: rook.io/block
parameters:
  pool: replicapool-hdd
  clusterName: rook
  fstype: xfs
---
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool-ssd
  namespace: rook
spec:
  replicated:
    size: 1
  crushRoot: ssd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-block-ssd
provisioner: rook.io/block
parameters:
  pool: replicapool-ssd
  clusterName: rook
  fstype: xfs
```

And finally it is enough to create a PVC to consume the storage and thus to reproduce my problem

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): Linux 4.15.2-1.el7.elrepo.x86_64
* Cloud provider or hardware configuration: Intel Xeon E3-1245v2 / 2 x 2To RAID 1 / RAM 32GB
* Rook version (use `rook version` inside of a Rook Pod): v0.6.0-207.g516e96f
* Kubernetes version (use `kubectl version`): v0.6.0-207.g516e96f
* Kubernetes cluster type: BareMetal
* Ceph status (use `ceph health`): HEALTH_OK

**Comment by jbw976** [comment]
From the operator logs above, the pool and storage class don't seem to be in agreement:
```
pool: replicapool-hdd,storageClass: rook-block-ssd,
```
I wonder if this mismatch is leading to the failure to find the block image?

Can you share the output of `rookctl block ls` from the [toolbox](https://rook.io/docs/rook/master/toolbox.html)?

**Comment by r0xsh** [comment]
OMG D: How could I miss that !!
I think you put your finger on the problem :)

Here are the `rookctl block ls` output
```
root@rook-tools:/# rookctl block ls
NAME                                       POOL              SIZE         DEVICE    MOUNT
pvc-e8cf0bb6-1011-11e8-be76-9c5c8e53d136   replicapool-hdd   500.00 GiB   rbd0      
pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136   replicapool-ssd   25.00 GiB    rbd
```

**Comment by r0xsh** [comment]
OMG D: How could I miss that !
I think you put your finger on the problem :)

Here are the output of `rookctl block ls`
```
NAME                                       POOL              SIZE         DEVICE    MOUNT
pvc-66b79866-101d-11e8-be76-9c5c8e53d136   replicapool-hdd   75.00 GiB    rbd1      
pvc-e8cf0bb6-1011-11e8-be76-9c5c8e53d136   replicapool-hdd   500.00 GiB   rbd0      
pvc-66abcb5a-101d-11e8-be76-9c5c8e53d136   replicapool-ssd   25.00 GiB    rbd       
pvc-6b5ad8c5-100b-11e8-be76-9c5c8e53d136   replicapool-ssd   25.00 GiB    rbd 
```

**Comment by r0xsh** [comment]
I found more precisely how to reproduce the problem :smile: 
In my deployment file I have two PVCs with two different storage class

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  [...]
spec:
  storageClassName: rook-block-ssd
[...]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  [...]
spec:
  storageClassName: rook-block-hdd
[...]
```

I tried both possible combinations (both `rook-block-ssd` and both `rook-block-hdd`) and it works perfectly :+1: 

But if the pod uses two storage class different, the problem occurs :disappointed:

**Comment by alwinmark** [comment]
As you are running Rook on a baremetal Kubernetes. What filesystem are you using? I had the same problems especially when I used replication > 1. After I changed from ext4 to xfs everything works no just as smooth as promised.

**Comment by r0xsh** [comment]
I have this problem using xfs, I'll try to inverstiger on the problem.
If it is a bug from rook, I will submit a pull request to fix that :)

**Comment by jbw976** [comment]
@r0xsh are you saying that this issue happens when 1 pod uses 2 PVCs that use different storage classes?  That would be surprising to me, but I want to confirm that's exactly what you are seeing.

**Comment by Ulexus** [comment]
I appear to have this problem: using multiple storage classes inside a single Pod.  I according to `dmesg` on the underlying node, Rook is attempting to find the rbd in the wrong pool.

For instance, I have a Pod which has a need for some not-all-that-important data which I used with my `standard` storage class, which uses an rbd pool with no replication.  That same Pod also needs a place for its long-term persistent data, which uses the `redundant` storage class, an rbd pool with a replication factor of 2.

The PVC, PV, and rbd image are all created properly, with the correct storage classes in the correct storage pools.  However, when the Pod tries to mount the volume with the `standard` storage class, it hunts for the RBD in the `redundant` pool.

Using each storage class discretely in other pods works fine.  Additionally, changing the volumes to all be in the _same_ storage class works fine.
