### ISSUE TITLE
CI failing due to mon pods going into CLBO.

### ISSUE THREAD

**Issue by sp98** [rook/rook#14877]
**Is this a bug report or feature request?**
* Bug Report
- TestCephUpgradeSuite and TestCephSmokeSuite CI test are failing constantly. 
- Mon pods seem to be in CLBO

**Deviation from expected behavior:**
- CI is failing 

**Expected behavior:**
- CI should not fail

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
[clusteryaml.txt](https://github.com/user-attachments/files/17459442/clusteryaml.txt)

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
mon pod logs
[mon.txt](https://github.com/user-attachments/files/17459433/mon.txt)

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by subhamkrai** [comment]
Similar error https://github.com/rook/rook/actions/runs/11434353002/job/31811931237?pr=14766

**Comment by travisn** [comment]
@sp98 Where are you seeing these failures? I haven't noticed them in other PRs today, for example #14880 is passing perfectly.

**Comment by sp98** [comment]
@travisn I started seeing this after rebasing with the master yesterday.  Before that, it working all good.

**Comment by sp98** [comment]
Not seeing this now. I'll close this for now and keep an eye on the CI if I hit this again.
