### ISSUE TITLE
docs: Clarify removing the cluster and finalizer

### ISSUE THREAD

**Issue by travisn** [rook/rook#1488]
When removing a cluster if the resources are not removed in the correct order, the namespace will stay in the delete pending state indefinitely.
- Document a "common problems" topic for how to remove the finalizer if needed
- Clarify documentation around ordering of cleaning up the components

**Comment by d-horner** [comment]
I have just seen this, having struggled myself, I wrote a oneliner to deal with it (if it is use to anyone in the meantime!)

`kubectl proxy &;kubectl get ns rook -o json > /tmp/rook.json ;sed -i '' '/"kubernetes"/d' /tmp/rook.json;curl -H "Content-Type: application/json" -X PUT --data-binary @/tmp/rook.json http://127.0.0.1:8001/api/v1/namespaces/rook/finalize;rm /tmp/rook.json;kill %1`

NB: sed -i '' is for macOS, if using sed on linux, remove the '' - it's just a workaround for sed -i needing an argument on macOS.

Cheers

**Comment by travisn** [comment]
@d-horner so you had to remove the finalizer on the namespace? I was thinking the issue was removing the finalizer on the cluster CRD, though I hadn't seen confirmation that it was the root cause either.

**Comment by d-horner** [comment]
Sorry I was on the way out the house before - after browsing further down my notes I do remember that the CRD caused the namespace to hang whilst "Terminating" also:

> Further inspection showed that the CustomResourceDefinition (CRD) for `cluster` was not deleting via `kubectl`. I employed the same logic as before in removing the finalizer from the Cluster definition. In this case it was `"clusters.rook.io"` and previously `"cluster.rook.io"`. Unable to pinpoint the exact mishap, I retrieved the string from `kubectl get crd --all-namespaces; kubectl describe crd clusters.rook.io`.

I was in a bit of a pickle trying to get rid of it all, browsing my shell history isn't a pretty sight!

I do think you are right concerning the CRD requiring deletion prior to the namespace, as I recall having the issue of trying to PUT the CRD json without the `"clusters.rook.io"` finalizer to the same API endpoint - after having removed the rook namespace with the above one-liner.

Seeing as I've not successfully got my PV/PVC working yet, i'll have a crack tearing down different parts of the deployment now.

**Comment by d-horner** [comment]
Ok, so I managed to replicate it with a teardown as so:

```
➜  kubernetes git:(master) ✗ kubectl delete ns rook-system
namespace "rook-system" deleted
➜  kubernetes git:(master) ✗ kubectl delete deploy rook-api -n rook
deployment "rook-api" deleted
➜  kubernetes git:(master) ✗ kubectl delete ds rook-ceph-osd -n rook
daemonset "rook-ceph-osd" deleted
➜  kubernetes git:(master) ✗ kubectl delete -n rook deploy rook-ceph-mds-testfs
deployment "rook-ceph-mds-testfs" deleted
➜  kubernetes git:(master) ✗ kubectl delete -n rook deploy rook-ceph-mgr0      
deployment "rook-ceph-mgr0" deleted
➜  kubernetes git:(master) ✗ kubectl delete ns rook
namespace "rook" deleted
➜  kubernetes git:(master) ✗ kubectl get ns
NAME          STATUS        AGE
default       Active        14d
kube-public   Active        14d
kube-system   Active        14d
rook          Terminating   7h
➜  kubernetes git:(master) ✗ kubectl get crd
NAME                        AGE
clusters.rook.io            7h
filesystems.rook.io         7h
objectstores.rook.io        7h
pools.rook.io               7h
volumeattachments.rook.io   7h
➜  kubernetes git:(master) ✗ kubectl delete crd {filesystems.rook.io,objectstores.rook.io,pools.rook.io,volumeattachments.rook.io}
customresourcedefinition "filesystems.rook.io" deleted
customresourcedefinition "objectstores.rook.io" deleted
customresourcedefinition "pools.rook.io" deleted
customresourcedefinition "volumeattachments.rook.io" deleted
➜  kubernetes git:(master) ✗ kubectl get crd
NAME               AGE
clusters.rook.io   7h
➜  kubernetes git:(master) ✗ kubectl delete crd clusters.rook.io
customresourcedefinition "clusters.rook.io" deleted
➜  kubernetes git:(master) ✗ kubectl get crd
NAME               AGE
clusters.rook.io   7h
```

Here you can see our problem persists, again it is hanging on the finalizer "customresourcecleanup.apiextensions.k8s.io", using the one-liner to patch the CRD it is immediately removed:
```
CRD=`kubectl get crd | grep cluster | cut -d" " -f1` && kubectl patch crd $CRD -p '{"metadata":{"finalizers": [null]}}'
```

```
➜  kubernetes git:(master) ✗ kubectl patch crd clusters.rook.io -p '{"metadata":{"finalizers": [null]}}'
customresourcedefinition "clusters.rook.io" patched
➜  kubernetes git:(master) ✗ kubectl get crd && kubectl get ns
No resources found.
NAME          STATUS    AGE
default       Active    14d
kube-public   Active    14d
kube-system   Active    14d
```

Et voila - lesson learnt is to delete the CRD prior to everything else. If you don't, you can patch the CRD. I'm not overly familiar with the inner workings of kubernetes yet, although I intend to! I hope this is of help to anyone. If you would like me to write it up into docs more succinctly I'm happy to do so.

_Sidenote_
I am having issues with [https://github.com/rook/rook/issues/1162#issuecomment-343743163](https://github.com/rook/rook/issues/1162#issuecomment-343743163) / [https://github.com/rook/rook/issues/1330](https://github.com/rook/rook/issues/1330) with rook-agent throwing an error that I can't work my way around! `op-k8sutil: returning version v1.9.2 instead of v1.9.2+coreos.0` I noticed you commented and likely have a far better grasp than I!

**Comment by travisn** [comment]
ok, if tearing down in that order you will definitely run into issues. The finalizer won't be automatically removed from the crd and the rook volumes won't be unmounted from any pods that may have consumed them. Thus, i'll look at making the [Teardown instructions](https://rook.io/docs/rook/master/quickstart.html#teardown) easier to find. While I'm in there I'll plan on adding a topic on how to clean up the finalizer if it is done in the wrong order, your input to this is very helpful, thanks.

**Comment by travisn** [comment]
also note that by deleting the crd properly, you should expect all the artifacts created for the cluster to be cleaned up automatically. For example, you won't need to explicitly delete the mon, osd, mgr, or mds deployments, daemonsets, or replicasets.

**Comment by d-horner** [comment]
I do think the documentation could do with a more newbie-proof level of verbosity - whilst the high level of abstraction is sterling, the issues I have faced are largely due to not having sufficient under-the-hood knowledge of kubernetes in general yet. For example, I dug this hole due to a faint recollection having read:

> # Deleting a namespace
>
> 1. Deleting a namespace with
>
> `$ kubectl delete namespaces <insert-some-namespace-name>`
>
> **WARNING, this deletes everything under the namespace!**
>
> This delete is asynchronous, so for a time you will see the namespace in the `Terminating` state.

After realising the namespace/crd hadn't followed suit, I set about trying everything to tear it down! The step by step approach above was geared more to see what I could delete with the CRD/NS hanging in a Terminating state.

Whilst I enjoy trawling through code and trial by fire, I do think a 'rook for dummies' approach might benefit adoption. I have setup ceph clusters outside of k8s and I'm very grateful for the higher level of abstraction, I don't mind digging through issues on GitHub, but they are sometimes slightly tricky following the chain. 

I could throw together a bunch of questions that I don't quite yet understand after having had a few pokes in different environments/setups and ask the floor on slack to try and close the knowledge gap? Whilst collating key bits and padding out the docs?

**Comment by travisn** [comment]
Yes, absolutely sounds great to have a "Getting Started with Rook" topic for newbies. Maybe we could also have a FAQ page next to the getting started and quickstart pages. Your thoughts and questions would provide a great start to all of that!

**Comment by travisn** [comment]
@d-horner feel free to comment on #1503 thanks!

**Comment by Inumedia** [comment]
For those who still stumble on this and get the `list element types are not identical: [[customresourcecleanup.apiextensions.k8s.io] []]` error when trying to patch like above,

this command worked for me:

`kubectl patch crd clusters.ceph.rook.io  -p '{"metadata":{"finalizers": []}}' --type=merge`

( Sorry for pinging everyone on this issue, I ran into this and spent a good couple hours figuring out how to purge the CRDs )

**Comment by travisn** [comment]
@Inumedia would be great to add this to the [help topic](https://github.com/rook/rook/blob/master/Documentation/teardown.md#removing-the-cluster-crd-finalizer) on cleaning up the crd. Want to open a PR for that? Btw, this is the command that worked on my test cluster:
```
kubectl -n rook-ceph patch clusters.ceph.rook.io rook-ceph -p '{"metadata":{"finalizers": []}}' --type=merge
```

**Comment by SDLyu** [comment]
Comman `kubectl -n rook-ceph patch clusters.ceph.rook.io rook-ceph -p '{"metadata":{"finalizers": []}}' --type=merge` works for me!

**Comment by jeffvance** [comment]
as a note to @d-horner 's patch: I had to add `--type merge` to avoid this error:
`Error from server (BadRequest): json: cannot unmarshal string into Go value of type map[string]interface {}`
My patch cmd is: `CRD=`kubectl get crd | grep cluster | cut -d" " -f1` && kubectl patch crd $CRD --type merge -p '{"metadata":{"finalizers": [null]}}'`

**Comment by pogogirls** [comment]
> @Inumedia would be great to add this to the [help topic](https://github.com/rook/rook/blob/master/Documentation/teardown.md#removing-the-cluster-crd-finalizer) on cleaning up the crd. Want to open a PR for that? Btw, this is the command that worked on my test cluster:
> 
> ```
> kubectl -n rook-ceph patch clusters.ceph.rook.io rook-ceph -p '{"metadata":{"finalizers": []}}' --type=merge
> ```
I used this method and my problem was solved

**Comment by leseb** [comment]
The doc was recently updated again: https://github.com/rook/rook/pull/3276

**Comment by bars83** [comment]
`kubectl patch crd cephclusters.ceph.rook.io -p '{"metadata":{"finalizers": []}}' --type=merge`
works for me. rook was installed with helm "rook-master/rook-ceph   v1.1.0-beta.0.422.ga625a43"

**Comment by denysvitali** [comment]
Watch out, this will patch everything rook.io related!

```
for CRD in $(kubectl get crd -n rook-ceph | grep rook.io | cut -d " " -f 1 | xargs); do kubectl patch crd -n rook-ceph $CRD --type merge -p '{"metadata":{"finalizers": [null]}}'; done
```

In my case it was:

```
cephblockpools.ceph.rook.io
cephclients.ceph.rook.io
cephfilesystems.ceph.rook.io
cephnfses.ceph.rook.io
cephobjectstores.ceph.rook.io
cephobjectstoreusers.ceph.rook.io
volumes.rook.io
```

**Comment by travisn** [comment]
@denysvitali @leseb Given the finalizers that have been added recently to the other CRs, want to update [this doc](https://rook.github.io/docs/rook/v1.3/ceph-teardown.html#removing-the-cluster-crd-finalizer) with this cleanup step in case someone needs to force the remove?

**Comment by denysvitali** [comment]
@travisn Done :+1:

**Comment by WestFarmer** [comment]
> kubectl patch crd clusters.ceph.rook.io -p '{"metadata":{"finalizers": []}}' --type=merge

for me, this one worked.
kubectl patch crd cephclusters.ceph.rook.io -p '{"metadata":{"finalizers": []}}' --type=merge
