### ISSUE TITLE
Update to more recent version of code-generator 

### ISSUE THREAD

**Issue by travisn** [rook/rook#14888]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook CI is using v0.20 of the code-generator, which is quite old. The latest version is v0.32, so it is time to update.
https://github.com/kubernetes/code-generator/tags

**Expected behavior:**
Rook should use recent tools versions

**How to reproduce it (minimal and precise):**

See Rook's version [here](https://github.com/rook/rook/blob/master/build/makelib/golang.mk#L234):
```
export CODE_GENERATOR_VERSION=0.20.0
```

**Comment by subhamkrai** [comment]
@obnoxxx seems interested in working on this; he already reached out to me and started looking so assigning it to him.

**Comment by subhamkrai** [comment]
> @obnoxxx seems interested in working on this; he already reached out to me and started looking so assigning it to him.

Also shared resources with him to contribute on this. Thanks
