### ISSUE TITLE
Automate cleaning up of the dataDirHostPath

### ISSUE THREAD

**Issue by travisn** [rook/rook#1490]
As per discussion in #1438, it would be very helpful to automate cleaning up the contents of the `dataDirHostPath` when the cluster CRD is deleted. When the mon and osd pods receive the SIGTERM, they would need to check if the cluster CRD exists and if it has been deleted, they could clean up the directory as part of the shutdown. Some considerations:
- This is a very destructive action. We may want a CRD option for whether to remove data on cleanup. On the other hand, we are already deleting secrets and other cluster metadata that will make it very difficult or impossible to restore a cluster from the persisted data. 
- This will require additional RBAC privileges for the mon and osd pods to query the status of the CRD.

**Comment by kokhang** [comment]
You can leverage the pod lifecycle hooks. https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-details

So adding a `prestop` hook that will run when the pod is terminated.

**Comment by travisn** [comment]
This will not be necessary when we move to the local storage PVs. dataDirHostPath is only a short term solution
