### ISSUE TITLE
Helm chart: Cannot set `revisionHistoryLimit: 0`

### ISSUE THREAD

**Issue by ChristianCiach** [rook/rook#14938]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When using the `rook-ceph` helm chart version , using this `values.yaml` completely ignores the configured value:

```yaml
# reduce clutter in ArgoCD UI
revisionHistoryLimit: 0
```

Every value other than `0` works as expected.

**Expected behavior:**

The generated ConfigMap `rook-ceph-operator-config` should contain the entry `ROOK_REVISION_HISTORY_LIMIT: "0"`, but it does not.

**How to reproduce it (minimal and precise):**

You can render the chart locally to observe this behavior: 

```
helm template --namespace rook-ceph rook-ceph rook-release/rook-ceph -f values.yaml
```

The issue can be workarounded by configuring the value as a String:

```yaml
# reduce clutter in ArgoCD UI
revisionHistoryLimit: "0"
```

The cause of the issue is the `if` condition inside the helm template, because `0` is a falsy value:

https://github.com/rook/rook/blob/45e05ee09f1caa402a00ccaca0b13c67a488f4e2/deploy/charts/rook-ceph/templates/configmap.yaml#L23

To fix this, I would probably just set the default value to `10` (the kubernetes default) and omit the `if` clause. 

**Environment**:
* Rook version: 1.15.4

**Comment by travisn** [comment]
Does it help to put quotes around it?
```
revisionHistoryLimit: "0"
```

**Comment by ChristianCiach** [comment]
Yes, as I've already described above :)

**Comment by obnoxxx** [comment]
@ChristianCiach , as there is a workaround,
it does not really seem to be a bug to me.

can this issue be closed?

**Comment by ChristianCiach** [comment]
I am fine with closing this issue, but as long as there is no JSON-schema for this helm chart, this is at least surprising behavior. I would expect that most people would intuitively try to configure this value as an integer, as can be seen in https://github.com/rook/rook/issues/14902.

I still think it would be better to initialize this field with a sentinel value like `-1` and change the `if` condition to check for this sentinel.
