### ISSUE TITLE
Add operator setting to include pauses during rook upgrade process

### ISSUE THREAD

**Issue by jrcichra** [rook/rook#14933]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add the ability to slow down or add pauses to the rook upgrade process. In other words, add an artificial delay between failure domain restarts.
**What is use case behind this feature:**
During upgrades I/O sensitive workloads (such as redis) on RBD are reporting timeouts during our upgrade process. Looking at the output of `ceph status` there is only a small window of time between FD restarts where all PGs are active.

```
 task redis-server:59028 blocked for more than 10 seconds.
echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
```

Adding a configurable artificial pause between steps may give clients some time to recover when upgrading larger clusters (700+ OSDs and 30+ racks).

**Environment**:

Large clusters with tens of racks and hundreds of OSDs with sensitive RBD clients.

**Comment by jrcichra** [comment]
`pkg/operator/ceph/cluster/osd/update.go` looks like the place this parameter would go: https://github.com/rook/rook/blob/45e05ee09f1caa402a00ccaca0b13c67a488f4e2/pkg/operator/ceph/cluster/osd/update.go#L80

**Comment by travisn** [comment]
These would be the most conservative upgrade settings, have you set all of these? The last one was more recently added, and if you have not yet enabled it perhaps it will help sufficiently instead of needing a new pause setting.
```
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  upgradeOSDRequiresHealthyPGs: true
```

**Comment by jrcichra** [comment]
Thanks, I believe the `upgradeOSDRequiresHealthyPGs` does exactly what I want. Even better than a pause. Thanks!
