### ISSUE TITLE
manually repair OSD after rook cluster fails after k8s node restart

### ISSUE THREAD

**Issue by beatlejuse** [rook/rook#1494]
I was faced with the problem of falling OSD after restarting any node k8s.
It is alleged that the OSD needs to stand up for himself,
But it's not working for me. 
The problem is described in more detail here: https://github.com/rook/rook/issues/1278

And here I want to discuss possible ways to get OSD to work manually.

```
ceph osd tree
ID  CLASS WEIGHT  TYPE NAME           STATUS REWEIGHT PRI-AFF
 -1       0.46196 root default
 -2       0.09239     host 10-1-29-31
  1   hdd 0.09239         osd.1           up  1.00000 1.00000
-11       0.09239     host 10-1-29-32
  4   hdd 0.09239         osd.4           up  1.00000 1.00000
 -3       0.09239     host 10-1-29-33
  0   hdd 0.09239         osd.0           up  1.00000 1.00000
 -9       0.09239     host 10-1-29-34
  2   hdd 0.09239         osd.2         down        0 1.00000
 -4       0.09239     host 10-1-29-35
  3   hdd 0.09239         osd.3           up  1.00000 1.00000
```

I have tried the following methods found in the documentation:

```
ceph osd repair osd.2
Error EAGAIN: osd.2 is not up
```

```
ceph osd up osd.2
no valid command found; 10 closest matches:
osd count-metadata <property>
osd versions
osd find <osdname (id|osd.id)>
osd metadata {<osdname (id|osd.id)>}
osd getmaxosd
osd ls-tree {<int[0-]>} {<name>}
osd getmap {<int[0-]>}
osd getcrushmap {<int[0-]>}
osd tree {<int[0-]>} {up|down|in|out|destroyed [up|down|in|out|destroyed...]}
osd ls {<int[0-]>}
Error EINVAL: invalid command
```

```
ceph-volume simple activate osd.2
\-->  RuntimeError: Expected JSON config path not found: /etc/ceph/osd/osd.2-None.json
```
all of them lead to errors and do not give the expected result.
maybe I'm moving in the wrong direction?

**Comment by travisn** [comment]
@beatlejuse there is no command for bringing the osd up because the osd daemon is responsible for reporting that it is up. Is there an osd pod running on host 10-1-29-34 where osd.2 should be running? The logs for that pod would hopefully show something about why the osd is not starting.

**Comment by beatlejuse** [comment]
because manual OSD recovery is not possible, this issue can be closed.

**Comment by travisn** [comment]
This is still an issue with osds not coming back up after being `out`. @dmick could you look into this one?

**Comment by dmick** [comment]
I'll see if I can reproduce

**Comment by zieg8301** [comment]
We think we may have found a manual recovery method.

1. Spin up fresh 3 osd cluster
2. Down a k8s node long enough for related OSD to autoout
3. Bring node back up and wait for it to reschedule all pods
4. Ceph osd rm the offending OSD
5. Kill the pod which was running the offending OSD

The pod will be rescheduled and almost immediately the OSD will be UP and IN. Cluster remains fully RW to radosgw traffic during this entire process. This has only been tested with Replicated data pools so far, testing EC pools next.

This is less than ideal, as it requires manual intervention each time an OSD auto-outs. We would definitely like to work with the team to share any information we've found to help fix this.

**Comment by dmick** [comment]
I have an osd in a bad state after a node reboot; trying to figure out what state exactly

**Comment by dmick** [comment]
(I had not previously allowed the OSD to be marked 'out'.  I waited for that, and still it came right back up and in on node restart.)

**Comment by zieg8301** [comment]
Here's another hunch: We are using hostpath/filestore in our cluster.yaml not bluestore and physical devices. One of our engineers did a little further research last night and found the following when the k8s node came back up:

After downing a node and letting the OSD autoout, we exec'd into the pod and redirected the output of ps to a file, that file contains the following: 
`[root@rook-ceph-osd-fzjnq omap]# cat junk
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 03:28 ?        00:00:00 /tini -- /usr/local/bin/rook ceph osd
root         7     1  0 03:28 ?        00:00:00 /usr/local/bin/rook ceph osd
root       274     0  0 03:29 pts/0    00:00:00 bash
root       614     7  0 03:39 ?        00:00:00 ceph-osd --foreground --id=2 --cluster=rook-ceph --osd-data=/rook/storage-dir02/osd2 --conf=/rook/storage-dir02/osd2/rook-ceph.config --keyring=/rook/storage-dir02/osd2/keyring --osd-uuid=00000000-0000-0000-0000-000000000000 --osd-journal=/rook/storage-dir02/osd2/journal`

After that, we cat the uuid from the config directory: 
`cat /rook/storage-dir02/osd2/current/omap
8175ca93-23e7-4500-a469-551a8d4a804b`

The UUIDs don't match. Have you tried using filestore/directories for your OSDs in trying to replicate this issue? We have another environment where we have access to physical devs, and are unable to reproduce this issue in said environment.

**Comment by sscheit** [comment]
Thanks @dmick  - i did find one problem in the new OSD that doesn't join the cluster.  The osd process  looks to be running with invalid uuid.  we are using hostpath

`root       614     7  0 03:39 ?        00:00:00 ceph-osd --foreground --id=2 --cluster=rook-ceph --osd-data=/rook/storage-dir02/osd2 --conf=/rook/storage-dir02/osd2/rook-ceph.config --keyring=/rook/storage-dir02/osd2/keyring --osd-uuid=00000000-0000-0000-0000-000000000000 --osd-journal=/rook/storage-dir02/osd2/journal `

**Comment by dmick** [comment]
@zieg8301 uuid mismatch would do it, and I am not using hostpath...will try.

**Comment by dmick** [comment]
is the hostpath data preserved across node restart?  obviously if the OSD data dir is deleted, restart won't work

**Comment by travisn** [comment]
ok, good to know the root cause. @dmick you're were right on track with the host path not persisting.

**Comment by dmick** [comment]
@sscheit, could nonpersistent hostpath be your problem as well?

**Comment by sscheit** [comment]
Yes, we are actually teammates...thanks for your help, again, our apologies.

**Comment by dmick** [comment]
ah.  :)  Well that's great news; thanks for your patience.

**Comment by shoaibjdev** [comment]
> We think we may have found a manual recovery method.
> 
> 1. Spin up fresh 3 osd cluster
> 2. Down a k8s node long enough for related OSD to autoout
> 3. Bring node back up and wait for it to reschedule all pods
> 4. Ceph osd rm the offending OSD
> 5. Kill the pod which was running the offending OSD
> 
> The pod will be rescheduled and almost immediately the OSD will be UP and IN. Cluster remains fully RW to radosgw traffic during this entire process. This has only been tested with Replicated data pools so far, testing EC pools next.
> 
> This is less than ideal, as it requires manual intervention each time an OSD auto-outs. We would definitely like to work with the team to share any information we've found to help fix this.

How to add new kubernetes nodes for OSD to existing rook cluster?

**Comment by alifiroozi80** [comment]
In my case, I wanted to repair the cluster, but showed the below error:

```shell
$ ceph osd repair osd.19
Error EAGAIN: osd.19 is not up
```

Here are my steps to fix this issue:

1. Reboot the target node
2. After that node brings up, disable the swap on that:

```shell
sudo swapoff -a
```

3. Re-start every deployments and daemonsets in the `rook-ceph` namespace:

```shell
kubectl -n rook-ceph get deployments.apps | awk '{print $1}' | xargs -i kubectl -n rook-ceph rollout restart deployment {}
kubectl -n rook-ceph get daemonsets | awk '{print $1}' | xargs -i kubectl -n rook-ceph rollout restart daemonsets {}
```

P.S: If you see some Pods won't be restarted, delete them manually: `kubectl -n rook-ceph delete pod/POD-NAME --force`
You have to confirm that every Pod is newly created (has been restated)

4. Wait a couple of minutes
5. Check the OSD status:

```shell
ceph osd status
```

There is a big chance, by now, every OSD would be in the `exists,up` status. but if yours weren't in that status, move on to the next step:

6. Repair target OSD manually:

```shell
ceph osd repair osd.19
```

7. Wait! That OSD should be in `exists,up` status after a few minutes.

These steps work fine in my Ceph cluster:

```yaml
Rook Version: 1.13.4
Ceph Version: 18.2.1 reef
K8s Version: 1.27.4
```

Good Luck 🍻
