### ISSUE TITLE
cancelMirrorMonitoring for CephBlockPool only works when mirroring is disabled

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#14958]
**Is this a bug report or feature request?**
* Bug Report

Currently, there is a bug in canceling the monitoring for cephblockpool mirroring, 
We need to have a extra cancel request if monitoring is disabled,
Rn it already disable when mirroring is disabled https://github.com/rook/rook/blob/master/pkg/operator/ceph/pool/controller.go#L361

Also the rados namespace mirroring is dependent on the `cephblockpool`, so do we need a watcher to watch the cephblockpool settings? @travisn 

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
> Currently, there is a bug in canceling the monitoring for cephblockpool mirroring,
> We need to have a extra cancel request if monitoring is disabled,
> Rn it already disable when mirroring is disabled https://github.com/rook/rook/blob/master/pkg/operator/ceph/pool/controller.go#L361

The bug is that changing the monitoring settings to disable the status doesn't actually disable the status?

> Also the rados namespace mirroring is dependent on the cephblockpool, so do we need a watcher to watch the cephblockpool settings? @travisn

As discussed in huddle, let's hold off on the watcher for now. It seems like enough of a corner case that they could just restart the operator if they really want to disable it. 

Another idea is that whenever we update the rados namespace mirroring status, do we retrieve the cephblockpool CR? If so, we could just detect during the refresh that it was disabled, and go ahead to disable it. Then no need for a watcher.

**Comment by parth-gr** [comment]
>The bug is that changing the monitoring settings to disable the status doesn't actually disable the status?

correct

>Another idea is that whenever we update the rados namespace mirroring status, do we retrieve the cephblockpool CR? If so, we could just detect during the refresh that it was disabled, and go ahead to disable it. Then no need for a watcher.

Nice idea I can try this out
