### ISSUE TITLE
CrashLoopBackOff in rook-ceph-osd-X:expand-bluefs

### ISSUE THREAD

**Issue by sta4152** [rook/rook#14955]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
@sta4152 There is not enough detail in this issue to troubleshoot. What version of Rook and Ceph? What do logs show for that init container? Are all OSDs crashing? Was this after an upgrade, node reboot, or what other event?

The expand-bluefs container is only needed for checking if the OSD needs to be resized when the OSD pod starts. As a workaround, you could manually try editing the OSD deployment spec to remove that init container to see if the OSD will then start successfully. Note that the next time Rook reconciles, it will restore the init container, so you will need to scale down the rook operator to try this workaround.

**Comment by sta4152** [comment]
Sorry, I must have hit the submit in a very early stage of authoring https://github.com/rook/rook/issues/14959, did not create it by intention :-(

So this one can be ignored/deleted
