### ISSUE TITLE
Ceph 18.2.2 missing metrics

### ISSUE THREAD

**Issue by davgarn** [rook/rook#14979]
Hi,

Since we have upgrade on 18.2.2 we have lost some metric from osd like "ceph_osd_op_w_in_bytes"

The only metrics answer by exporter for osd are :

`curl -s rook-ceph-mgr.rook-ceph.svc.cluster.local:9283/metrics |awk -F "[{ ]" '/^ce.*osd/ {print $1}' |sort |uniq 

ceph_cluster_osd_blocklist_count
ceph_daemon_health_metrics
ceph_disk_occupation
ceph_disk_occupation_human
ceph_mgr_module_can_run
ceph_mgr_module_status
ceph_osd_apply_latency_ms
ceph_osd_commit_latency_ms
ceph_osd_flag_nobackfill
ceph_osd_flag_nodeep_scrub
ceph_osd_flag_nodown
ceph_osd_flag_noin
ceph_osd_flag_noout
ceph_osd_flag_norebalance
ceph_osd_flag_norecover
ceph_osd_flag_noscrub
ceph_osd_flag_noup
ceph_osd_in
ceph_osd_metadata
ceph_osd_up
ceph_osd_weight
ceph_prometheus_collect_duration_seconds_count
ceph_prometheus_collect_duration_seconds_sum
`

has anyone had this problem before?

And from ceph dashboard Cluster Utilization is empty.

Regards,

**Comment by travisn** [comment]
Since Ceph v18, many of the metrics have moved to the ceph exporter. See the [reef release notes](https://docs.ceph.com/en/latest/releases/reef/#dashboard) for more clues. If still seeing issues, I'd suggest opening a [ceph tracker](https://tracker.ceph.com/).

**Comment by sp98** [comment]
@davgarn As Travis mentioned, the metric is available in `rook-ceph-exporter` pod.  All performance counters are now available in the exporter daemon. 

``` 
[root@rook-ceph-exporter-minikube-m02-5fd4cbdb94-98r6r /]# curl http://localhost:9926/metrics | grep ceph_osd_op_w_in_bytes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 64327  100 64327    0     0  3695k      0 --:--:-- --:--:-- --:--:-- 418# HELP ceph_osd_op_w_in_bytes Client data written
7k# TYPE ceph_osd_op_w_in_bytes counter
ceph_osd_op_w_in_bytes{ceph_daemon="osd.0"} 0

```

I'll go ahead and close this issue. Please open a new issue for `ceph dashboard Cluster Utilization is empty.` as its different from the current one, IMO.

**Comment by davgarn** [comment]
Ok thank you for your reply.

Regards,
