### ISSUE TITLE
 unable to get monitor info from DNS SRV with service name: ceph-mon Error in pod when mounting PVC

### ISSUE THREAD

**Issue by ravikakadia** [rook/rook#14989]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
pods are unable to mount provisioned storage.

**Expected behavior:**
Pods should mount the PVC

**How to reproduce it (minimal and precise):**

Installed rook-ceph cluster on a K8S cluster with 4 nodes (1 controller + 3 Worker) successfully using the quickstart guide. I am able to see all pods in rook-ceph NS running and no errors found in logs.
```
[admin@controller195442: ~] $ k get pods -n rook-ceph
NAME                                                         READY   STATUS      RESTARTS     AGE
csi-cephfsplugin-9whvp                                       3/3     Running     0            3d
csi-cephfsplugin-fc5s8                                       3/3     Running     1 (3d ago)   3d
csi-cephfsplugin-provisioner-6fdd9b7dd7-27wd5                6/6     Running     1 (3d ago)   3d
csi-cephfsplugin-provisioner-6fdd9b7dd7-l6r65                6/6     Running     2 (3d ago)   3d
csi-cephfsplugin-tlq9j                                       3/3     Running     1 (3d ago)   3d
csi-cephfsplugin-vp4xv                                       3/3     Running     1 (3d ago)   3d
csi-rbdplugin-5n6ll                                          3/3     Running     0            3d
csi-rbdplugin-95dpg                                          3/3     Running     1 (3d ago)   3d
csi-rbdplugin-mx75w                                          3/3     Running     1 (3d ago)   3d
csi-rbdplugin-provisioner-5d9fb8699c-bngc6                   6/6     Running     3 (3d ago)   3d
csi-rbdplugin-provisioner-5d9fb8699c-zqrw6                   6/6     Running     1 (3d ago)   3d
csi-rbdplugin-s97vx                                          3/3     Running     1 (3d ago)   3d
rook-ceph-crashcollector-controller195442-7b985c998c-qmhgk   1/1     Running     0            3d
rook-ceph-crashcollector-worker195443-5cd88776-hml78         1/1     Running     0            3d
rook-ceph-crashcollector-worker1954466-dff65bc9c-l6lsn       1/1     Running     0            3d
rook-ceph-crashcollector-worker1954467-6bcdb4796d-7bdsm      1/1     Running     0            3d
rook-ceph-exporter-controller195442-7dbdbbc995-6sn88         1/1     Running     0            3d
rook-ceph-exporter-worker195443-8f69f6b48-rn78g              1/1     Running     0            3d
rook-ceph-exporter-worker1954466-b9947b897-r5wxs             1/1     Running     0            3d
rook-ceph-exporter-worker1954467-6d88bdc988-xmr5n            1/1     Running     0            3d
rook-ceph-mds-myfs-a-6f78fb8555-995lm                        2/2     Running     0            3d
rook-ceph-mds-myfs-b-6c59d89685-4pgl7                        2/2     Running     0            3d
rook-ceph-mgr-a-7574779c65-7rbc2                             3/3     Running     0            3d
rook-ceph-mgr-b-599b446ffb-29k74                             3/3     Running     0            3d
rook-ceph-mon-a-7c6cb68c66-4m898                             2/2     Running     0            3d
rook-ceph-mon-b-5cc4bf7bf6-hb8b5                             2/2     Running     0            3d
rook-ceph-mon-c-f7dc9b94-mqcjt                               2/2     Running     0            3d
rook-ceph-operator-7b878c7c4b-5hgjv                          1/1     Running     0            3d1h
rook-ceph-osd-0-8699d8cf8d-g8kdg                             2/2     Running     0            3d
rook-ceph-osd-1-998bcc57-8pn5c                               2/2     Running     0            3d
rook-ceph-osd-2-68577d8479-zpwk4                             2/2     Running     0            3d
rook-ceph-osd-prepare-controller195442-wff5f                 0/1     Completed   0            3d
rook-ceph-osd-prepare-worker195443-mgtbz                     0/1     Completed   0            3d
rook-ceph-osd-prepare-worker1954466-2fmw9                    0/1     Completed   0            3d
rook-ceph-osd-prepare-worker1954467-6rzwd                    0/1     Completed   0            3d
rook-ceph-rgw-my-store-a-65d4855697-t4d7j                    2/2     Running     0            3h51m
rook-ceph-tools-7b67b65bd-wxmkv                              1/1     Running     0            3d
rook-ceph-tools-operator-image-86bdccc87f-ng5fs              1/1     Running     0            145m
```
Created cephfs using 
[cephfilesystem.txt](https://github.com/user-attachments/files/17700696/cephfilesystem.txt)
and cephfs stroageclass using
[cephsc.txt](https://github.com/user-attachments/files/17700701/cephsc.txt)
and pvc using 
[cephfs-pvc.txt](https://github.com/user-attachments/files/17700725/cephfs-pvc.txt)

Now I am deploying a demo pod (from deploy/example/csi/pod.yaml) to test cephfs.
I expect the pod to be created with the filesystem.
but pod is staying in containercreating stage and pod desscription shows "unable to get monitor info from DNS SRV with service name: ceph-mon"

Result: PVCs are successfully bound, but pods get the following error message:
```
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Normal   Scheduled               12s   default-scheduler        Successfully assigned default/csicephfs-demo-pod to worker1954466
  Normal   SuccessfulAttachVolume  12s   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-9a788053-f454-4270-9e1f-783d3756dd6d"
  Warning  FailedMount             10s   kubelet                  MountVolume.MountDevice failed for volume "pvc-9a788053-f454-4270-9e1f-783d3756dd6d" : rpc error: code = Internal desc = an error (exit status 32 occurred while running mount args: [-t ceph 10.100.245.171:6789,10.104.205.146:6789,10.96.21.73:6789:/volumes/csi/csi-vol-82206687-4354-441e-b7f2-8c2a533e9d84/b1a22cf7-4484-453f-b72c-cbd1ddb5e047 /var/lib/kubelt/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/240018be939e31037b18780ad9736432a9e70cc48032c4e1e71d18bc3e0c483a/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-3097879732,mds_namepace=myfs,_netdev] stderr: unable to get monitor info from DNS SRV with service name: ceph-mon
2024-11-11T10:06:52.478+0000 7f2266ce0000 -1 failed for service _ceph-mon._tcp
mount error 95 = Operation not supported


```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:
```
`[admin@controller195442: cephfs] $ k exec -it rook-ceph-tools-operator-image-86bdccc87f-ng5fs -n rook-ceph -- bash
[rook@rook-ceph-tools-operator-image-86bdccc87f-ng5fs /]$ ceph status
  cluster:
    id:     66f79a8e-4f09-4ae2-9bee-b2cf5357484c
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 3d)
    mgr: b(active, since 3d), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 3d), 3 in (since 3d)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   11 pools, 137 pgs
    objects: 387 objects, 1.8 MiB
    usage:   407 MiB used, 15 GiB / 15 GiB avail
    pgs:     137 active+clean

  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr`
```

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):  
 ```
1 NAME="Ubuntu"
  2 VERSION="18.04.6 LTS (Bionic Beaver)"
  3 ID=ubuntu
  4 ID_LIKE=debian
  5 PRETTY_NAME="Ubuntu 18.04.6 LTS"
  6 VERSION_ID="18.04"
  7 HOME_URL="https://www.ubuntu.com/"
  8 SUPPORT_URL="https://help.ubuntu.com/"
  9 BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
 10 PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
 11 VERSION_CODENAME=bionic
 12 UBUNTU_CODENAME=bionic
```
* Kernel (e.g. `uname -a`):  ``` Linux controller195442 4.15.0-1011-fips #12-Ubuntu SMP Tue Jul 2 21:04:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux ```

* Cloud provider or hardware configuration:  64 GM RAM, 14 vCPUs on each node of cluster
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.15.4 go: go1.22.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable)
* Kubernetes version (use `kubectl version`): `Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
```
rook@rook-ceph-tools-operator-image-86bdccc87f-ng5fs /]$ ceph health
HEALTH_OK

**Comment by BlaineEXE** [comment]
This seems like it could be a kube cluster networking DNS issue, but I'm not certain. @Madhu-1 or @Rakshith-R have you seen this issue before?

**Comment by ravikakadia** [comment]
@BlaineEXE  @Madhu-1 @Rakshith-R  For now I have used a workaround to fix this issue to unblock my work. Since error is regarding resolving ceph-mon SRV
I have copied the service rook-ceph-mon-a and created a new service with name ceph-mon. And it worked, my pod became running. So looks like rook-ceph filesystem.yaml example has not created ceph-mon service, but created 3 service rook-ceph-mon-a, mon-b and mon-c. Is this an issue with example file??? Do we have any other filesystem.yaml file which I can refer to which can creat ceph-mon service instead?

**Comment by ravikakadia** [comment]
Since I have copied rook-ceph-mon-a  svc and created ceph-mon svc, pods on my worker195443 node can only access cephfs as mon-a pod is running on that node. Pods on other nodes are not able to access cephfs.
Need help.

**Comment by ravikakadia** [comment]
any help is really appriciated

**Comment by Rakshith-R** [comment]
This is a really weird issue.

Ceph daemons can communicate among themselves but csi pods can't reach the service.

@ravikakadia do you have CNI configured ? 
Try flipping https://github.com/rook/rook/blob/4524f3d78ebe2457dc2e5d54b606850ab450fe7d/deploy/examples/operator.yaml#L52

**Comment by ravikakadia** [comment]
@Rakshith-R thanks for the response. Yes I am using cilium CNI. let me try above configuration. I assume I need to uninstall the rook-ceph and install it again to make this config avaialble to cluster, am I right?

**Comment by ravikakadia** [comment]
@Rakshith-R I have changed the configmap - rook-ceph-operator-config '''
 apiVersion: v1
  6 data:
  7   CSI_CEPHFS_ATTACH_REQUIRED: "true"
  8   CSI_CEPHFS_FSGROUPPOLICY: File
  9   CSI_DISABLE_HOLDER_PODS: "true"
 10   CSI_ENABLE_CEPHFS_SNAPSHOTTER: "true"
 11   CSI_ENABLE_CSIADDONS: "false"
 12   CSI_ENABLE_ENCRYPTION: "false"
 13   CSI_ENABLE_HOST_NETWORK: "true"
 14   CSI_ENABLE_LIVENESS: "false"
 15   CSI_ENABLE_NFS_SNAPSHOTTER: "true"
 16   CSI_ENABLE_RBD_SNAPSHOTTER: "true"
 17   CSI_ENABLE_TOPOLOGY: "false"
 18   CSI_ENABLE_VOLUME_GROUP_SNAPSHOT: "true"
 19   CSI_FORCE_CEPHFS_KERNEL_CLIENT: "true"
 20   CSI_GRPC_TIMEOUT_SECONDS: "150"
 21   CSI_NFS_ATTACH_REQUIRED: "true"
 22   CSI_NFS_FSGROUPPOLICY: File
 23   CSI_PLUGIN_ENABLE_SELINUX_HOST_MOUNT: "false"
 24   CSI_PLUGIN_PRIORITY_CLASSNAME: system-node-critical
 25   CSI_PROVISIONER_PRIORITY_CLASSNAME: system-cluster-critical
 26   CSI_PROVISIONER_REPLICAS: "2"
 27   CSI_RBD_ATTACH_REQUIRED: "true"
 28   CSI_RBD_FSGROUPPOLICY: File
 29   ROOK_CEPH_ALLOW_LOOP_DEVICES: "false"
 30   ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: "15"
 31   ROOK_CSI_DISABLE_DRIVER: "false"
 32   ROOK_CSI_ENABLE_CEPHFS: "true"
 33   ROOK_CSI_ENABLE_NFS: "false"
 34   ROOK_CSI_ENABLE_RBD: "true"
 35   ROOK_DISABLE_DEVICE_HOTPLUG: "false"
 36   ROOK_DISCOVER_DEVICES_INTERVAL: 60m
 37   ROOK_ENABLE_DISCOVERY_DAEMON: "false"
 38   ROOK_ENFORCE_HOST_NETWORK: "false"
 39   ROOK_LOG_LEVEL: INFO
 40   ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
 41   ROOK_OPERATOR_METRICS_BIND_ADDRESS: "0"
 42   ROOK_USE_CSI_OPERATOR: "false"
 43   ROOK_WATCH_FOR_NODE_FAILURE: "true"
 44 kind: ConfigMap
 45 metadata:
 46   creationTimestamp: "2024-11-19T06:30:20Z"
 47   name: rook-ceph-operator-config
 48   namespace: rook-ceph
 49   resourceVersion: "175816"
 50   uid: 7fad2928-d1be-4405-a468-6403aa5bb84e
'''
But facing the same issue.

**Comment by Rakshith-R** [comment]
@ravikakadia can you reinstall with whole cluster on host networking ?
https://github.com/rook/rook/blob/master/Documentation/CRDs/Cluster/network-providers.md#host-networking

Can you try finding similar issues in rook repo?
I see quite a few and they suggested using host networking too, although there maybe another solution

**Comment by ravikakadia** [comment]
Sure. Thanks @Rakshith-R

**Comment by fengxsong** [comment]
same issue here.

rook version: 1.15.3

neither `spec.network.provider: host` or default network cannot mount cephfs volumes.

rbd volumes works fines.

**Comment by Madhu-1** [comment]
what is the `ceph mon dump` are you running with v1 port or v2 port? if its v2 cephfs kernel mount options need to be set.

**Comment by ravikakadia** [comment]
@Madhu-1 ```bash-5.1$ ceph mon dump
epoch 3
fsid a7368a61-2b6d-47cb-829a-7ed5ed2f3be2
last_changed 2024-11-19T06:41:22.616780+0000
created 2024-11-19T06:40:32.115261+0000
min_mon_release 18 (reef)
election_strategy: 1
0: [v2:10.96.155.83:3300/0,v1:10.96.155.83:6789/0] mon.a
1: [v2:10.98.85.205:3300/0,v1:10.98.85.205:6789/0] mon.b
2: [v2:10.96.57.159:3300/0,v1:10.96.57.159:6789/0] mon.c
dumped monmap epoch 3
bash-5.1$
```

**Comment by Rakshith-R** [comment]
@ravikakadia Can you check kernel/journal logs on that node ?

**Comment by Madhu-1** [comment]
The above v2 is for some clusters where v2 ports are used by default, in your case its v1 and v2 port. can you try to exec into the csi cephfs plugin pod and run the `mount -t` command manually (the one is failing in the log) check dmesg logs for details

**Comment by ravikakadia** [comment]
```
[admin@controller195442: ~] $ k exec -it csi-cephfsplugin-8gqcj -n rook-ceph -c csi-cephfsplugin -- bash
[root@controller195442 /]# mount -t ceph 10.96.57.159:6789,10.96.155.83:6789,10.98.85.205:6789:/volumes/csi/csi-vol-37bef0a8-801f-4988-9aab-0dff2e2db5c3/9c9d4849-516f-4b56-a93f-4b929128a /var/lib/kubelet/plugins/kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com/2cb6c6bf3f63fc0cb7b062195d9ec04e9761a1ea1367c5c01225d23aa626b04d/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-4257516760,mds_napace=myfs,_netdev
unable to read secretfile: No such file or directory
error reading secret file: -2
failed to parse ceph_options: -2

```

**Comment by fengxsong** [comment]
according to @Madhu-1 said 

> if its v2 cephfs kernel mount options need to be set.

after setting this option, the issue resolved.

```
csi:
  cephFSKernelMountOptions: "ms_mode=prefer-crc"
```

**Comment by ravikakadia** [comment]
@fengxsong dod you have mounted raw disk or disk is formatted?

**Comment by fengxsong** [comment]
@ravikakadia rdb volumes works fine.

**Comment by cmarotta82** [comment]
> according to what @Madhu-1 said
> 
> > if its v2 cephfs kernel mount options need to be set.
> 
> after setting this option, the issue resolved.
> 
> ```
> csi:
>   cephFSKernelMountOptions: "ms_mode=prefer-crc"
> ```

Would you mind elaborating on this just a bit?

I added this to my rook-ceph cluster yaml but get this error when i try to replace

kubectl replace -f rook-ceph_cluster.yml
Error from server (BadRequest): error when replacing "rook-ceph_cluster.yml": CephCluster in version "v1" cannot be handled as a CephCluster: strict decoding error: unknown field "spec.csi.cephFSKernelMountOptions"

**Comment by fengxsong** [comment]
@cmarotta82 😂 This is used to override the default helm values.yaml.

```
helm -n rook-ceph upgrade --install --create-namespace --set csi.cephFSKernelMountOptions=ms_mode=prefer-crc rook-ceph charts/rook-ceph-v1.15.3.tgz
```

**Comment by mr-elamin** [comment]
Hi all,

I executed into the plugin container where my pod was scheduled and checked the dmesg logs, as shown in the attached screenshot. 

My problem was resolved by removing the `mountOptions: debug` mode from the configuration.

For reference, you can find the storage class configuration here: https://github.com/rook/rook/blob/master/deploy/examples/csi/cephfs/storageclass.yaml
just remove the debug option:
mountOptions:
  # uncomment the following line for debugging
  #- debug
then everything has worked 

Thank you.
![image](https://github.com/user-attachments/assets/a3f875bc-1f61-4e84-a747-ae13a60456b3)
![image](https://github.com/user-attachments/assets/a416420b-6380-47a5-a1ba-4d929b00c561)

**Comment by cmarotta82** [comment]
> Hi all,
> 
> I executed into the plugin container where my pod was scheduled and checked the dmesg logs, as shown in the attached screenshot.
> 
> My problem was resolved by removing the `mountOptions: debug` mode from the configuration.
> 
> For reference, you can find the storage class configuration here: https://github.com/rook/rook/blob/master/deploy/examples/csi/cephfs/storageclass.yaml just remove the debug option: mountOptions:
> # uncomment the following line for debugging
> 
> #- debug then everything has worked
> 
> Thank you. ![image](https://private-user-images.githubusercontent.com/105249992/390068207-a3f875bc-1f61-4e84-a747-ae13a60456b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDkyNTUsIm5iZiI6MTczMjY0ODk1NSwicGF0aCI6Ii8xMDUyNDk5OTIvMzkwMDY4MjA3LWEzZjg3NWJjLTFmNjEtNGU4NC1hNzQ3LWFlMTNhNjA0NTZiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxOTIyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTFiOGE1NmU4N2E1YTdhYTVmMDlhMWVhNTdmZDg0NzMyYzhiNGQxNTM5ZmNiMGZjODI2NmE2NGExOWNhMjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s5Y9UTfmAyVI7_NvgMXuIlU6aNV6L4_BaVisGo2u0Ug) ![image](https://private-user-images.githubusercontent.com/105249992/390068301-a416420b-6380-47a5-a1ba-4d929b00c561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NDkyNTUsIm5iZiI6MTczMjY0ODk1NSwicGF0aCI6Ii8xMDUyNDk5OTIvMzkwMDY4MzAxLWE0MTY0MjBiLTYzODAtNDdhNS1hMWJhLTRkOTI5YjAwYzU2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxOTIyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Zjg0ZTdjM2RiMGRmOTNhYjdjYzg5NTdkZWNjY2VhYjBiZWRjNjQ0NTQwOTY0Nzc1N2ExNjM0NmIwNTRmMjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UjQwA3SZSTivdyFS91NtEXGPoQtcqLC1u26EEVzJBy4)

YESSSSSS,,, this was it. Resolved my issue with 1.15.6 as well

**Comment by ravikakadia** [comment]
Updating the OS from Ubuntu 18.04 (Kernel 4.15) to Ubuntu 20.04 has resolved my original DNS SRV issue.

**Comment by ravikakadia** [comment]
OS upgrade helped in resolving the issue

**Comment by chrisblatt** [comment]
I enabled network encryption and this issue appeared for me, 
I modified this in my cephcluster and issue was resolved:
```yaml
csi:
  cephfs:
    kernelMountOptions: ms_mode=secure
```
