### ISSUE TITLE
Operator on Talos (AMD64) v1.8.1: "exec /usr/local/bin/rook: exec format error"

### ISSUE THREAD

**Issue by muhlba91** [rook/rook#14988]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The `rook-ceph-operator` pod crashes due to `exec /usr/local/bin/rook: exec format error` using the image `docker.io/rook/ceph:v1.15.5` (`docker.io/rook/ceph@sha256:b94b23ecaf32e656c2460e2420dbc328be2951c673e41b7d3f2e3fe1eddecb59`).

**Expected behavior:**
The pod should start successfully.

**How to reproduce it (minimal and precise):**
Updating from `v1.15.4` to `v1.15.5` caused this issue on a Talos v1.8.1 machine with an Intel CPU. Other pods still run on `v1.15.4` and cause the cluster to function in its "old" state.

**Environment**:
* OS (e.g. from /etc/os-release): Talos v1.8.1
* Kernel (e.g. `uname -a`): N/A
* Cloud provider or hardware configuration: Intel CPU with 64 GB memory, self-hosted
* Rook version (use `rook version` inside of a Rook Pod): `v1.15.4` running, `v1.15.5` causing the issue
* Storage backend version (e.g. for ceph do `ceph -v`): irrelevant
* Kubernetes version (use `kubectl version`): 1.31.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Talos
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): irrelevant

**Comment by BlaineEXE** [comment]
`docker.io/rook/ceph@sha256:b94b23ecaf32e656c2460e2420dbc328be2951c673e41b7d3f2e3fe1eddecb59` is an ARM image. That is likely the source of the issue.

**Comment by muhlba91** [comment]
according to my system, this is the index digest; also see here: https://hub.docker.com/layers/rook/ceph/v1.15.5/images/sha256-4d3d17546945c681991b51ed69bc8110785300b0257249fdab1167bcc3ed1e3a?context=explore

the `v1.15.4` image for me is `docker.io/rook/ceph@sha256:3c085923f4c9ac45ffd466a513fba5231f445564e572aa029c8ff6382d918f3b` which also corresponds to the index digets (https://hub.docker.com/layers/rook/ceph/v1.15.4/images/sha256-9bfbc585d815f969026080f933a79b912f5e144e7c64b41ed178135548bf158f?context=explore)

i suppose the "wrong" image is loaded onto the system, as otherwise, i wouldn't get an `exec format error`?
