### ISSUE TITLE
Limit IOPS per volume via Storageclass

### ISSUE THREAD

**Issue by alwinmark** [rook/rook#1499]
Is this a bug report or feature request?

* Feature Request

**Feature Request**

Are there any similar features already existing:

Not in Rook as far as I can tell.
In the Openstack world there is sth. similar implemented for Cinder and Nova: https://ceph.com/geen-categorie/openstack-ceph-rbd-and-qos/

Also there seems to be a mechanism in docker itself: 
https://docs.docker.com/engine/reference/commandline/run/

Or without further investigating in Ceph(RBD):
https://github.com/ceph/ceph/pull/17032

I guess the most promising would be to integrate (if it really works and exists and is working with Rook) the RBD feature, because most likely the docker feature only works on a physical device.

What should the feature do:

In an ideal world, I want to create different Storageclasses with different IOps rate limits, like:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: limited-rook-block
provisioner: rook.io/block
parameters:
  pool: replicapool
  iops_limit: 40
  clusterName: rook
```

What would be solved through this feature:

"The noisy neighbor problem". Without this feature Rook won't be useable in production, as you can slow down the whole cluster by e.g extracting a huge gzip file.

Does this have an impact on existing features:
Only if there should be a default limiting. This could help beginners from halting their whole platform but I think a appropriate value is hard to guess.

**Environment**:

As this is a general feature request, it should work on every OS and setup or at least on mine :-)
That would be:

* OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Kernel (e.g. `uname -a`):
`Linux test-k8-1 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
`bare metal`
* Rook version (use `rook version` inside of a Rook Pod):
`rook: v0.6.2 ` But this can be any future version
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.3-rancher1", GitCommit:"beb8311a9f114ba92558d8d771a81b7fb38422ae", GitTreeState:"clean", BuildDate:"2017-11-14T00:54:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
`Rancher Kubernetes (Rancher 2.0)`
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
-

**Comment by christianhuening** [comment]
Was it a decision to not do that? Or did it just went stale?

**Comment by galexrt** [comment]
It just went stale.

On the other hand from Ceph side, the kernel client and / or fuse client depending on which is used (e.g., with Ceph CSI both are possible if I remember correctly) needs to implement that as far as I know.

**Comment by christianhuening** [comment]
ping. anyone else interested in this?

**Comment by Madhu-1** [comment]
@christianhuening is this same as https://github.com/ceph/ceph-csi/issues/521

**Comment by mmgaggle** [comment]
@Madhu-1 yes, this is a dupe.

**Comment by travisn** [comment]
Closing since it's tracked in CSI. https://github.com/ceph/ceph-csi/issues/521

**Comment by anthonyeleven** [comment]
https://github.com/ceph/ceph-csi/issues/521 predicates the use of `rbd-nbd`, so I don't think that is strictly a duplicate.
