### ISSUE TITLE
OSD pods failing to start with "'osd.XX has already bound to class 'nvme', can not reset class to 'ssd'"

### ISSUE THREAD

**Issue by elias-dbx** [rook/rook#14997]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Some OSD pods fail to start after provisioning with the following error:
```
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 _get_class not permitted to load sdk
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 <cls> /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/18.2.4/rpm/el9/BUILD/ceph-18.2.4/src/cls/cephfs/cls_cephfs.cc:201: loading cephfs
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 _get_class not permitted to load lua
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 _get_class not permitted to load test_remote_reads
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 <cls> /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos9/DIST/centos9/MACHINE_SIZE/gigantic/release/18.2.4/rpm/el9/BUILD/ceph-18.2.4/src/cls/hello/cls_hello.cc:316: loading cls_hello
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 osd.86 0 crush map has features 288232575208783872, adjusting msgr requires for clients
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 osd.86 0 crush map has features 288232575208783872 was 8705, adjusting msgr requires for mons
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 osd.86 0 crush map has features 288232575208783872, adjusting msgr requires for osds
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 osd.86 0 load_pgs
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640  0 osd.86 0 load_pgs opened 0 pgs
debug 2024-11-12T17:50:23.024+0000 7f8c6c061640 -1 osd.86 0 log_to_monitors true
debug 2024-11-12T17:50:23.068+0000 7f8c6c061640  1 bluestore(/var/lib/ceph/osd/ceph-86) collect_metadata devices span numa nodes 0
debug 2024-11-12T17:50:23.072+0000 7f8c6c061640 -1 osd.86 0 mon_cmd_maybe_osd_create fail: 'osd.86 has already bound to class 'nvme', can not reset class to 'ssd'; use 'ceph osd crush rm-device-class <id>' to remove old class first': (16) Device or resource busy
debug 2024-11-12T17:50:23.072+0000 7f8c6c061640 -1 osd.86 0 mon_cmd_maybe_osd_create fail: '(22) Invalid argument': (22) Invalid argument
debug 2024-11-12T17:50:23.072+0000 7f8c6c061640 -1 osd.86 0 init unable to update_crush_location: (22) Invalid argument
```

**Expected behavior:**
OSD pods start up and join the cluster

**How to reproduce it (minimal and precise):**

**File(s) to submit**:
[osd_preprovision_job_log.txt](https://github.com/user-attachments/files/17721115/osd_preprovision_job_log.txt)

[cephcluster_crd.json](https://github.com/user-attachments/files/17721143/cephcluster_crd.json)

**Logs to submit**:

**Cluster Status to submit**:
```
bash-5.1$ ceph status
  cluster:
    id:     36bf8a9c-f238-4280-a964-220a6fb0cd5b
    health: HEALTH_WARN
            1 daemons have recently crashed

  services:
    mon: 5 daemons, quorum a,b,c,d,e (age 18h)
    mgr: b(active, since 18h), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 92 osds: 80 up (since 3m), 80 in (since 7m)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   12 pools, 169 pgs
    objects: 396 objects, 750 KiB
    usage:   4.4 GiB used, 1.1 PiB / 1.1 PiB avail
    pgs:     169 active+clean

  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

* Kernel (e.g. `uname -a`):
```
$ uname -a
Linux pdx5a-re14-10a 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
* Cloud provider or hardware configuration:
```
$ lsblk
nvme0n1                                                                                               LVM2_member LVM2 001       gJ7t0X-nUaS-Uio9-FEN4-3agD-v7hh-QPbC34
└─ceph--2e05afe2--ae11--491d--88b9--7bf7b9734058-osd--block--c36022c5--e759--4d06--8716--7b0cf14035c3
  └─lefBLC-U0R4-h95d-z33p-fDFr-HmBv-Ftufer
nvme1n1
├─nvme1n1p1                                                                                           vfat        FAT32    efi   979C-E6E6                               509.7M     0% /boot/efi
├─nvme1n1p2                                                                                           ext4        1.0      boot  d61b1b32-ad7b-44ef-bb9f-a838d49a8501      299M    31% /boot
└─nvme1n1p3                                                                                           crypto_LUKS 1              099bcb25-65a4-4ad0-9969-3aab36db886a
  └─root.crypt                                                                                        ext4        1.0      root  60519878-c215-4986-bd29-b6e2b8f99296    808.9G     3% /
```
* Rook version (use `rook version` inside of a Rook Pod):
```
v1.15.0
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
$ ceph -v
ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable)
```
* Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: v1.29.10
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.10
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
```
bare metal
```
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
```
$ ceph health
HEALTH_WARN 1 daemons have recently crashed
```

**Comment by travisn** [comment]
Did you set `allowDeviceClassUpdate: true` in your cephcluster CR? Otherwise, it's not expected that the device class would attempt to be updated. But it also seems that is a different code path where ceph is trying to apply the device class, instead of by applying that setting mentioned. 

Do you have any device class settings applied in your cephcluster CR? 

Did you purge any OSDs and now provisioning new OSDs? If so, perhaps the previous OSD was not fully purged and the new OSD with the same ID is getting confused about the device class.

**Comment by elias-dbx** [comment]
Hi, here is the storage config from the cephcluster CR (which I also linked in this bug report)
```
"storage": {
    "config": {
        "encryptedDevice": "true",
        "osdsPerDevice": "1"
    },
    "devicePathFilter": "^/dev/nvme[0-9]+n1$",
    "flappingRestartIntervalHours": 0,
    "store": {},
    "useAllDevices": false,
    "useAllNodes": true
},
```

>Did you set allowDeviceClassUpdate: true in your cephcluster CR
I don't believe we set `allowDeviceClassUpdate: true`, I can try that.

>Did you purge any OSDs and now provisioning new OSDs? If so, perhaps the previous OSD was not fully purged and the new OSD with the same ID is getting confused about the device class.

no, these are totally wiped machines and should not have any pre-existing OSDs on them

**Comment by travisn** [comment]
I see in the osd prepare pod log the device class is set to `nvme`. 

Are you having this issue with all OSDs? Or just some subset?

And the failure you're seeing is in the main container of the osd daemon? Can you share the pod spec for an OSD that is failing? I wonder if rook could be setting device class incorrectly in the osd pod spec, or if it's just ceph having an issue at osd startup.

**Comment by elias-dbx** [comment]
We are seeing this on only a subset of OSDs. We are seeing the failure in the main container of the osd daemon, here are the full logs:
[osd_logs.txt](https://github.com/user-attachments/files/17723070/osd_logs.txt)

And here is the podspec for a failing OSD pod.
[osd_pod_spec.json](https://github.com/user-attachments/files/17723046/osd_pod_spec.json)

**Comment by travisn** [comment]
In the osd pod spec, I see that the labels and property indicate that Rook intends it to be an nvme device class: 
```json
    "labels": {
...
        "device-class": "nvme",
...
"name": "ROOK_OSD_DEVICE_CLASS",
"value": "nvme"
```
@rzarzynski Why would the OSD daemon attempt to change the device class from `nvme` to `ssd`? These appear to be clean OSDs, and I don't see from Rook's perspective where `ssd` would be coming from.

**Comment by elias-dbx** [comment]
It looks like something weird is happening during osd provisioning job. It seems like the tooling is getting confused:
```
2024-11-12 17:37:39.025636 I | cephosd: osdInfo has 1 elements. [{Name:osd-block-c36022c5-e759-4d06-8716-7b0cf14035c3 Path:/dev/ceph-2e05afe2-ae11-491d-88b9-7bf7b9734058/osd-block-c36022c5-e759-4d06-8716-7b0cf14035c3 Tags:{OSDFSID:c36022c5-e759-4d06-8716-7b0cf14035c3 Encrypted:1 ClusterFSID:36bf8a9c-f238-4280-a964-220a6fb0cd5b CrushDeviceClass:nvme} Type:block}]
...
2024-11-12 17:37:40.996970 I | cephosd: setting device class "ssd" for device "/dev/mapper/lefBLC-U0R4-h95d-z33p-fDFr-HmBv-Ftufer"
2024-11-12 17:37:40.996979 I | cephosd: 1 ceph-volume raw osd devices configured on this node
2024-11-12 17:37:40.997006 I | cephosd: devices = [{ID:86 Cluster:ceph UUID:c36022c5-e759-4d06-8716-7b0cf14035c3 DevicePartUUID: DeviceClass:nvme BlockPath:/dev/ceph-2e05afe2-ae11-491d-88b9-7bf7b9734058/osd-block-c36022c5-e759-4d06-8716-7b0cf14035c3 MetadataPath: WalPath: SkipLVRelease:false Location:root=default host=pdx5a-re14-10a chassis=10 rack=14 region=pdx room=pdx5a row=e zone=pdx5 LVBackedPV:false CVMode:lvm Store:bluestore TopologyAffinity:topology.rook.io/chassis=10 Encrypted:false ExportService:false NodeName: PVCName:}]
```

The encrypted volume is recognized by osdinfo, but later on the configured device is treated as an unencrypted ssd instead of an encrypted nvme.

**Comment by travisn** [comment]
Ah good catch that the osd prepare job was getting confused by the ssd device class. I'd suggest to force it to `nvme` with this setting:
```
  storage:
    config:
      deviceClass: "nvme"
```

**Comment by elias-dbx** [comment]
Hi @travisn, the error messages around SSD deviceClass turned out to be a red herring.

The issue is that our `topology.rook.io/chassis` and `topology.rook.io/rack` label values are overlapping. We enumerate chassis from 1 to N and we also enumerate racks from 1 to M which caused the issues described here: https://github.com/rook/rook/issues/9419#issuecomment-1449592563
