### ISSUE TITLE
v1.15 upgrade guide does not mention k8s minimum version

### ISSUE THREAD

**Issue by sgielen** [rook/rook#14998]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The [upgrade guide from Rook 1.14 to 1.15](https://rook.github.io/docs/rook/v1.15/Upgrade/rook-upgrade/) does not mention the minimum k8s version of 1.26 which is mentioned in the [release notes on Github](https://github.com/rook/rook/releases/tag/v1.15.0).

**Expected behavior:**
Like the upgrade guide from [Rook 1.12 to 1.13](https://rook.io/docs/rook/v1.13/Upgrade/rook-upgrade/#supported-versions), I would expect the "breaking changes" to contain a minimum version bump.

**Comment by travisn** [comment]
The [Quickstart guide](https://rook.io/docs/rook/latest/Getting-Started/quickstart/#kubernetes-version) and [Prereqs](https://rook.io/docs/rook/latest/Getting-Started/Prerequisites/prerequisites/) do mention the supported K8s versions, but point taken to make sure it's in the upgrade guide as well. What upgrade issue did you hit due to missing this?

**Comment by sgielen** [comment]
> The [Quickstart guide](https://rook.io/docs/rook/latest/Getting-Started/quickstart/#kubernetes-version) and [Prereqs](https://rook.io/docs/rook/latest/Getting-Started/Prerequisites/prerequisites/) do mention the supported K8s versions, but point taken to make sure it's in the upgrade guide as well. What upgrade issue did you hit due to missing this?

No upgrade issues! I'm still preparing and wrote a compatibility matrix based on the upgrade guides. From this, I concluded I could upgrade Rook before I upgraded Kubernetes itself. Then I double-checked the release notes on Github and changed my plan accordingly :-)

**Comment by travisn** [comment]
The release notes are correct, squid is supported. Sounds great if you could open a PR to fix the upgrade doc, thanks!

**Comment by sgielen** [comment]
@travisn please see https://github.com/rook/rook/pull/15003 for two tiny updates to the two upgrade guides. I've assumed that the supported Squid version is the same between v1.15 and v1.16.
