### ISSUE TITLE
 Timeout expired waiting for volumes to attach/mount for pod (rook plugin not found)

### ISSUE THREAD

**Issue by NiraliSupe** [rook/rook#1501]
k8s version: v1.9
env: VirtualBox
os: Coreos

It is 1 node kubernete cluster
I followed the below steps:
1. Followed https://rook.io/docs/rook/v0.5/k8s-pre-reqs.html and updated the kubelet with
```
Environment="RKT_OPTS=--volume modprobe,kind=host,source=/usr/sbin/modprobe \
  --mount volume=modprobe,target=/usr/sbin/modprobe \
  --volume lib-modules,kind=host,source=/lib/modules \
  --mount volume=lib-modules,target=/lib/modules \
  --uuid-file-save=/var/run/kubelet-pod.uuid"
```
2. Installed ceph utility 
```
 rbd -v
ceph version 10.2.2 (45107e21c568dd033c2f0a3107dec8f0b0e58374)
```
All rook pods are working but MySQL pod fails with error 'timeout expired waiting for volumes to attach/mount for pod'
```
➜  kubectl get pod -n rook-system
NAME                             READY     STATUS    RESTARTS   AGE
rook-agent-rqw6j                 1/1       Running   0          21m
rook-operator-5457d48c94-bhh2z   1/1       Running   0          22m
➜   kubectl get pod -n rook
NAME                             READY     STATUS    RESTARTS   AGE
rook-api-848df956bf-fhmg2        1/1       Running   0          20m
rook-ceph-mgr0-cfccfd6b8-8brxz   1/1       Running   0          20m
rook-ceph-mon0-xdd77             1/1       Running   0          21m
rook-ceph-mon1-gntgh             1/1       Running   0          20m
rook-ceph-mon2-srmg8             1/1       Running   0          20m
rook-ceph-osd-84wmn              1/1       Running   0          20m
➜   kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                    STORAGECLASS   REASON    AGE
pvc-6a4c5c2a-127d-11e8-a846-080027b424ef   20Gi       RWO           Delete          Bound     default/mysql-pv-claim   rook-block               15m
➜  kubectl get pvc
NAME             STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
mysql-pv-claim   Bound     pvc-6a4c5c2a-127d-11e8-a846-080027b424ef   20Gi       RWO           rook-block     15m
kubectl get pods
NAME                               READY     STATUS              RESTARTS   AGE
wordpress-mysql-557ffc4f69-8zxsq   0/1       ContainerCreating   0          16m

```
Error when I describe pod : FailedMount	Unable to mount volumes for pod "wordpress-mysql-557ffc4f69-8zxsq_default(6a932df1-127d-11e8-a846-080027b424ef)": timeout expired waiting for volumes to attach/mount for pod "default"/"wordpress-mysql-557ffc4f69-8zxsq". list of unattached/unmounted volumes=[mysql-persistent-storage]

Also added the following option to rook-operator.yaml
```
        - name: FLEXVOLUME_DIR_PATH
          value: "/var/lib/kubelet/volumeplugins"
```
Could you please help with this? Please let me know if you need further details. I checked the similar issues but a solution is not working.

**Comment by aolwas** [comment]
Same error here

* k8s 1.9.3 deployed with kubespray on Openstack cluster
* Calico network
* rook operator v0.6.2 deployed with helm
* rook cluster from doc's example (bluestore in /var/lib/rook on every node)
* pool with 1 replica

PVC and PV creation works fine but got a timeout when mounting the PVC in a pod

**Comment by galexrt** [comment]
@NiraliSupe Can you please provide the full describe output for the Pod that is unable to mount the PV? `kubectl describe po wordpress-mysql-557ffc4f69-8zxsq`.
Also what Rook version are you running and which kernel is used?

**Comment by virtuman** [comment]
here's an example of exact same issue, same setup as @aolwas 

```
Name:           wordpress-mysql-557ffc4f69-frgkl
Namespace:      default
Node:           srv-eu1/10.0.0.11
Start Time:     Thu, 08 Mar 2018 19:08:13 +0100
Labels:         app=wordpress
                pod-template-hash=1139970925
                tier=mysql
Annotations:    <none>
Status:         Pending
IP:
Controlled By:  ReplicaSet/wordpress-mysql-557ffc4f69
Containers:
  mysql:
    Container ID:
    Image:          mysql:5.6
    Image ID:
    Port:           3306/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      MYSQL_ROOT_PASSWORD:  changeme
    Mounts:
      /var/lib/mysql from mysql-persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pw2xh (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  mysql-persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mysql-pv-claim
    ReadOnly:   false
  default-token-pw2xh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pw2xh
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age               From               Message
  ----     ------                 ----              ----               -------
  Warning  FailedScheduling       6m (x3 over 6m)   default-scheduler  pod has unbound PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled              6m                default-scheduler  Successfully assigned wordpress-mysql-557ffc4f69-frgkl to srv-eu1
  Normal   SuccessfulMountVolume  6m                kubelet, srv-eu1   MountVolume.SetUp succeeded for volume "default-token-pw2xh"
  Warning  FailedMount            17s (x3 over 4m)  kubelet, srv-eu1   Unable to mount volumes for pod "wordpress-mysql-557ffc4f69-frgkl_default(a9119056-22fb-11e8-9b2c-901b0e95a1e0)": timeout expired waiting for volumes to attach/mount for pod "default"/"wordpress-mysql-557ffc4f69-frgkl". list of unattached/unmounted volumes=[mysql-persistent-storage]
```

**Comment by virtuman** [comment]
same error here:
k8s 1.9.3
calico
rook installed using rook-master/rook helm chart with version

**Comment by jbw976** [comment]
Has the common issues entry on this topic been useful for anyone yet?  there are a few parts of it that may give some guidance: https://rook.io/docs/rook/master/common-problems.html#pod-using-rook-storage-is-not-running

the rook-agent logs and sometimes the kubelet logs for the node that the pod is scheduled on can be especially useful here too.

**Comment by aolwas** [comment]
Hi everyone, 

I've finally figured out why rook was not working on my setup. 

Using the default deploy mode, kubespray reconfigures the location for volume plugin to `/var/lib/kubelet/volume-plugins`. 

However, The Rook agent still deploy the flexvolume plugin in the default location: `/usr/libexec/kubernetes/kubelet-plugins/volume/exec`. 

Thus when trying to mount the volume in the pod, the plugin is not reachable. 

I try my rook manifests on a minikube or a kubeadm based kubespray deployment (which uses the default location) and it works as expected.

So it seems that rook does not support k8s cluster deployed with a custom volume plugin directory.

thx @jbw976 for pointing to the kubelet logs, it was the key to my debug.

**Comment by galexrt** [comment]
@aolwas There is documentation available for Rook to change the flevolume plugin path, here: https://rook.io/docs/rook/master/flexvolume.html (see the `FLEXVOLUME_DIR_PATH` env var for the rook-operator).

**Comment by aolwas** [comment]
@galexrt I honestly don't know how I have missed this. there's even a reference to this in the first post of this issue ... sorry, my bad :-(

With the env var, it works as expected.

**Comment by jbw976** [comment]
Yes @SDLyu that does look like the main issue, good debugging.  The explanation and workaround can be found in https://github.com/rook/rook/issues/1110#issuecomment-367199838.  We have a docs bug to address this with #1542, it would be great if someone could open a quick PR for this soon :)

**Comment by SDLyu** [comment]
Hi @jbw976 sorry for late response.

I already run command `modprobe rbd` and check module loaded in all nodes.

```
> lsmod | grep rbd
rbd                    83889  0
libceph               282661  1 rbd
```
But still get 

```
Unable to mount volumes for pod "test_default(18121f36-412b-11e8-9e1e-0276bbc09e35)": timeout expired waiting for volumes to attach/mount for pod "default"/"test". list of unattached/unmounted volumes=[logs]
```

<img width="1204" alt="test_-_kubernetes_dashboard_ _1_____tmux_" src="https://user-images.githubusercontent.com/2996108/38789871-c2801256-416f-11e8-9ebc-93c581516dd4.png">

**Comment by galexrt** [comment]
@SDLyu Can you check your kubelet logs if you have `no volume plugin matched` messages in it?
If so, make sure your kubelet is able to reach your flexvolume directory (e.g. `/var/lib/kubelet/volumeplugins`).
If the flexvolume directory (e.g. `/var/lib/kubelet/volumeplugins`) contains no folder named something with `rook`, then
> [...]you need to delete the rook-agent DaemonSet and restart the operator that it recreates the rook-agent DaemonSet.
> See https://github.com/rook/rook/issues/1501#issuecomment-372245658

**Comment by grebois** [comment]
Same issue with v.1.11.0, works fine with v.1.9.9

**Comment by laevilgenius** [comment]
v1.11.0, same issue.
Helm chart version `v0.7.0-278.gcbd9726`.
```
> uname -r
4.15.0-20-generic
```
Didn't see any errors in rook's pods.
Kubelet can't load flexvolume plugin:
```
[plugins.go:611] Error dynamically probing plugins: Error creating Flexvolume plugin from directory rook.io~rook-ceph-system, skipping. Error: unexpected end of JSON input
```
Eventually only `rook.io/rook` driver gets loaded, but it doesn't match to the driver in my pv (`ceph.rook.io/rook-ceph-system`), so volume mount fails. 
I'm also getting `not a flex volume` errors from [flexvolume/util.go#L60-L68](https://github.com/kubernetes/kubernetes/blob/bc98f7a5f2086a62af80ad92f7201e7af5e0ef03/pkg/volume/flexvolume/util.go#L60-L68).
Might be related to [kubernetes#60694](https://github.com/kubernetes/kubernetes/issues/60694).

**Comment by jbw976** [comment]
We ran into an issue with the 1.11 integration tests that I believe to be the same root cause.  Details of that discussion are captured in https://gist.github.com/jbw976/358b67f5c0822cd6d424cdfd2961d748

**Comment by trevex** [comment]
We also ran into the same issue on our 1.11.2 test cluster. Same symptoms as described in this issue and restarting the kubelet on the affected node helped.

@laevilgenius I noticed you fixed https://github.com/kubernetes/kubernetes/issues/60694 locally. Can you confirm this is indeed the root cause?

**Comment by laevilgenius** [comment]
@trevex I'm not 100% positive, but I've never had this issue ever since. Didn't notice any side effects as well.

**Comment by travisn** [comment]
Let's consider backporting #2068 to 0.8 to resolve this issue

**Comment by trevex** [comment]
As previously reported in slack, the PR #2068 fixes this issue for us. Since deploying the image containing the PR every node in the cluster went through multiple restarts and the issue did not reappear.

Previously a manual kubelet restart (or multiple) where necessary to get the volume plugin to load.

**Comment by jbw976** [comment]
Thank you very much for that validation @trevex.  We will discuss backporting the fix to 0.8 today in the community meeting :)

**Comment by jbw976** [comment]
I think with the combination of only probing for the specific plugin that a filesystem event was raised for (https://github.com/kubernetes/kubernetes/pull/58519/files) and bailing out on the first plugin loading failure (https://github.com/kubernetes/kubernetes/issues/60694) is causing this behavior to happen more for us now, even with some sleeps we added.

It looks like the plugin discovery/probing will happen very rapidly (30+ times in 0.2 seconds) in response to a filesystem event.  Perhaps our binary hasn't been copied/renamed to it's final place yet (race) and therefore the `init` call fails, similar to this error:
```
Aug 28 18:55:36 ip-172-31-30-198 kubelet[8015]: W0828 18:55:36.289638    8015 driver-call.go:144] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ceph.rook.io~rook/rook, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ceph.rook.io~rook/rook: no such file or directory, output: ""
Aug 28 18:55:36 ip-172-31-30-198 kubelet[8015]: E0828 18:55:36.289653    8015 plugins.go:595] Error dynamically probing plugins: Error creating Flexvolume plugin from directory ceph.rook.io~rook, skipping. Error: unexpected end of JSON input
```
This may not have been an issue in the past, because any filesystem event would cause ALL flexvolume dirs to be probed, so later events would pick up earlier plugin installs.  But now that only the flexvolume dir that has an event will get probed, and it will not be retried later on, we only get 1 chance for success and it's a small window.

One potential workaround would be to write a dummy file to each flexvolume dir later on after all the dust has settled, forcing a discovery probe once we are certain our binary is in place and ready to receive the `init` call.  Does that make sense?

**Comment by travisn** [comment]
Before we add another workaround I'd like to see if we can get traction on the upstream issue (which I just commented on) so the full fix would hopefully make it in soon. Otherwise, it does sound promising to write the dummy file, although it still seem like we could have a timing issue around when to write that file. Thanks for looking more into it.

**Comment by snowmansora** [comment]
Hi, recently I have upgraded my setup to use K8s 1.11.3.

Also, I have automation that deploys a 3 nodes K8s cluster, deploys rook-ceph, and deploys a StatefulSet that uses rook-ceph block storage on each nodes. I ran the automation multiple times, and the StatefulSet pods can never scale to all nodes because 1 or more nodes have the problem mentioned in this issue.

I am using rook 0.8.3 which I think already includes the workaround "Rook's flex drivers will be loaded more slowly to workaround a k8s race condition".

I am now thinking of updating my automation script to includes the "dummy file" logic mentioned by @jbw976. 

I think without additional workarounds, rook-ceph 0.8.3 is currently not usable on K8s 1.11.3.

**Comment by travisn** [comment]
@snowmansora looking forward to hear if writing the dummy file works for you. Before we get a fix from upstream (https://github.com/kubernetes/kubernetes/issues/60694), we will need a workaround.

**Comment by snowmansora** [comment]
@travisn 
For some unknown reason, I encounter less of this issue now, but I still hit the issue like once per 20 K8s nodes generated by automation.

I am now deploying the following DaemonSet to workaround the issue:
```
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  namespace: rook-ceph-system
  name: rook-workaround-1501
  labels:
    app: rook-workaround-1501
spec:
  selector:
    matchLabels:
      app: rook-workaround-1501
  template:
    metadata:
      labels:
        app: rook-workaround-1501
    spec:
      containers:
      - name: rook-workaround-1501
        image: rook/ceph:v0.8.3
        command: ['bash', '-c', 'set -e; while true; do cd /flexmnt; for d in * ; do if [ -d "$d" ] && [[ "$d" == *"rook"* ]]; then touch "$d"; fi; done; sleep 300; done;']
        volumeMounts:
        - name: flexvolume
          mountPath: /flexmnt
      volumes:
      - name: flexvolume
        hostPath:
          path: /var/lib/kubelet/volume-plugins
```

When the issue occurs, I manually tried to deploy the above DaemonSet, and it fixes the issue for me. Hence, I have included that in my deployment automation now. I will let it run for a while to see if it can actually workaround the issue.

But, the workaround is not that ideal, as every loop iteration will cause the volume plugin being loaded again and logs being generated. Luckily, I don't see any bad side effects at the moment. Will be great if there is a way to test the volume-plugins being loaded or not before calling the "touch" workaround.

**Comment by snowmansora** [comment]
@travisn 
For some unknown reason, I encounter less of this issue now. However, I still encounter it 1/~20 K8s nodes deployed by automation.

I am now using the following DaemonSet to workaround the issue:
```
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  namespace: rook-ceph-system
  name: rook-workaround-1501
  labels:
    app: rook-workaround-1501
spec:
  selector:
    matchLabels:
      app: rook-workaround-1501
  template:
    metadata:
      labels:
        app: rook-workaround-1501
    spec:
      containers:
      - name: rook-workaround-1501
        image: rook/ceph:v0.8.3
        command: ['bash', '-c', 'set -e; while true; do cd /flexmnt; for d in * ; do if [ -d "$d" ] && [[ "$d" == *"rook"* ]]; then touch "$d"; fi; done; sleep 300; done;']
        volumeMounts:
        - name: flexvolume
          mountPath: /flexmnt
      volumes:
      - name: flexvolume
        hostPath:
          path: /var/lib/kubelet/volume-plugins
```

Tried to deploy the above workaround manually when the issue occurs, and it seems to work. Now, I am deploying it during my automation.

However, the above workaround is not that good, as it will load the volume plugins every 5 minutes. I don't see any bad side effects at the moment other than it generates some logs. Will be great if it can check whether the volume plugins are loaded or not before applying the "touch" workaround though.

**Comment by travisn** [comment]
@snowmansora thanks for trying that out. Are you saying that even with this workaround you still see the issue on about 5% of the nodes? Or was that before this workaround?

**Comment by snowmansora** [comment]
@travisn 
The 5% is before the workaround.
I just applied the workaround to automation yesterday, so it will take some time for it to run multiple times to confirm the workaround is working for me.

**Comment by snowmansora** [comment]
@travisn FYI: After running the automation number of times which deployed around 100 nodes, all of the nodes can mount rook ceph block storage, so the workaround seems to be working for me.

**Comment by travisn** [comment]
@snowmansora great to hear the workaround is working! then we should integrate a similar workaround into the rook agent.

**Comment by travisn** [comment]
@snowmansora #2245 was merged a few days ago that will periodically refresh the drivers similar to your workaround. When you get a chance it would be great to confirm if the latest master build works for you too. Note that you'll pick up some other changes this week in master, in particular let me know if #2187 gives you any surprises.

**Comment by Duneyr** [comment]
Dirty but immediately after I ran this on all of my three nodes, everything started to ran as it should:

`ln -s /usr/libexec/kubernetes/kubelet-plugins/volume/exec/rook.io~rook /var/lib/kubelet/volume-plugins/`

**Comment by galexrt** [comment]
@Duneyr In your case the issue is not a bug, but that your flexvolume path for your kubelet is different to the one configured on the Rook Ceph Operator. See https://rook.io/docs/rook/v1.0/flexvolume.html.

**Comment by Duneyr** [comment]
@galexrt I see it even is quite well documented... Thanks!

**Comment by pogogirls** [comment]
I encountered the same problem, Through the following methods,the pod was running.
Configuring the Rook operator.yaml:
env:
[...]
- name: FLEXVOLUME_DIR_PATH
  value: "/var/lib/kubelet/volumeplugins"
