### ISSUE TITLE
Storage class clusterName should be named clusterNamespace

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1502]
Currently, when creating a cluster CRD, the cluster name and the namespace it is deployed to must match exactly.  The codebase is not 100% consistent on when it uses cluster name and when it uses the namespace.

for instance, i think the dynamic provisioner would fail to create a block image because it would use the wrong cluster name when exec’ing to `rbd`

we should either:
* perform an inventory on the codebase and fix all places where a mismatched cluster name/namespace breaks something
* add documentation or validation to enforce early on that cluster name does match the namespace, avoiding issues later on that show up and are harder to debug

**Comment by dmick** [comment]
The former is far preferable; cluster names are generally acknowledged to have been a bad idea, and using "ceph" for the name is to be strongly preferred.

I have interest in working this issue but will refrain from assigning myself until I can get my build system proved out again.

**Comment by travisn** [comment]
A few thoughts around this:
- There is one rook cluster per namespace. The name of the k8s namespace is the important thing. The `name` of the cluster CRD should be ignored everywhere by Rook, except that it is required by k8s to identify the CRD. If someone tries to create multiple cluster CRDs in the same namespace I believe we have some basic error checking, but more may be needed here.
- Today the internal ceph cluster name is the name of the CRD. But I agree that the name used by the ceph daemons should just be the default name `ceph` (as alluded to in #1347). And if we put the config files in `/etc/ceph`, the default args will just work in all the daemons. We don't gain anything by using a cluster name other than `ceph`. 
- There has been discussion in the past for allowing multiple rook clusters in the same namespace. This would mean that both the CRD name and namespace would be necessary to identify the cluster. This would complicate things and I don't recall hearing anyone asking for that feature, so I would like to put that discussion to rest.

**Comment by bassam** [comment]
#1412 makes an argument for letting the cluster-admin control namespaces and not forcing one cluster-per-namespace on them. A kubernetes namespace is a unit of security policy, quotas and other things beyond just naming.

**Comment by travisn** [comment]
I'm really just arguing for simplicity. If 99% of users are only running one storage cluster in one namespace or would be fine using multiple namespaces for multiple clusters, simplicity is good.

**Comment by liewegas** [comment]
If namespaces are a policy construct, then perhaps the cluster name and namespace name shouldn't be related at all.  For example, the cluster name (as far as kubernetes/rook are concerned) could default to ceph, but be something else if you choose to have multiple clusters within the same namespace. 

From the outside, having them both and requiring them to match seems a bit silly. 

I have no idea whether it would be useful to have multiple clusters within a single namespace, though.  Simplicity sounds good!

**Comment by bassam** [comment]
it does seem silly to require the namespace name and cluster to match.

How about the following (similar to what's in #1412):

* Keep the cluster `name` and default it to the name of the backend `ceph`
* The cluster admin should decide which namespace the pods are created in by setting `namespace`.
*  Rook pod name should use a `cluster.name` prefix for example `ceph-mon0-cv78d` etc.

So the following should be possible:

```
apiVersion: v1
kind: Namespace
metadata:
  name: myns
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: red
  namespace: myns
	...
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: blue
  namespace: myns
	...
```

**Comment by liewegas** [comment]
Works for me (if the multiple clusters per namespace is deemed worth the complexity).

**Comment by travisn** [comment]
@jbw976 where did you see it not working when the cluster name was different from the namespace? I just ran through the file, block, and object samples and all seems to be working when the name was `foo`, with a namespace of `rook`. The name `foo` looks ignored by everything as expected.

If you wanted to support multiple clusters in the same namespace, the name of the cluster would need to be included in all the resource names (deployments, pods, secrets, etc) to avoid conflicts. 

The changes from the kubectl user's perspective are nothing complicated, it's just one more bit that could go wrong.
- The storage class would need to know the name of the cluster to connect to and pass it on to the volume plugin, in addition to the namespace
- RGW clients would need to include the name as part of the dns service name.

**Comment by jbw976** [comment]
@travisn I dug into this more tonight.  Even though we have lots of places in the code using the cluster namespace and also places using the cluster name, it ends up not really mattering in the current code base for the vast majority of scenarios.

This is because when the [`ClusterInfo` struct](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/mon/info.go#L20) is persisted as a k8s secret, it actually saves the namespace as the cluster name.  Therefore, code later on that uses the cluster name is actually using the namespace, so it ends up being consistent.
https://github.com/rook/rook/blob/master/pkg/operator/cluster/ceph/mon/util.go#L69
https://github.com/rook/rook/blob/master/pkg/operator/cluster/ceph/mon/util.go#L259
https://github.com/rook/rook/blob/master/pkg/operator/cluster/ceph/mon/util.go#L287

The repro that I distinctly remember was at Kubecon last year, where Pavel ran into this issue while creating his cluster.yaml and storageclass by hand.  The dynamic provisioner will fail to create a block image if the [`clusterName` field on the storage class](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-storageclass.yaml#L25) does not match the cluster's namespace.  That is definitely possible to goof up if you have a cluster where the name doesn't match its namespace.  I was able to repro that just now.

That potentially may be the only issue here...

**Comment by travisn** [comment]
Right, if the `clusterName` on the storage class doesn't match the namespace you would have that issue. Perhaps it should be called `clusterNamespace`.
