### ISSUE TITLE
Customizing the .mgr pool with a CephObjectPool fails to set the crush rule

### ISSUE THREAD

**Issue by sfackler** [rook/rook#15025]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The .mgr pool is using crush rule 0 (aka "replicated_rule").

**Expected behavior:**
The .mgr pool is using crush rule 4 (aka ".mgr").

**How to reproduce it (minimal and precise):**

Configure a cluster with the `.mgr` pool customized via a `CephBlockPool` object (present at initial install time):

```yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  annotations:
    meta.helm.sh/release-name: rook-ceph-cluster
    meta.helm.sh/release-namespace: rook-ceph
  creationTimestamp: "2024-11-18T17:07:52Z"
  finalizers:
  - cephblockpool.ceph.rook.io
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: builtin-mgr
  namespace: rook-ceph
  resourceVersion: "7834"
  uid: ea152cf6-7028-43b8-9382-4278123dec7e
spec:
  application: ""
  erasureCoded:
    codingChunks: 0
    dataChunks: 0
  failureDomain: osd
  mirroring: {}
  name: .mgr
  quotas: {}
  replicated:
    size: 2
  statusCheck:
    mirror: {}
status:
  info:
    failureDomain: osd
    type: Replicated
  observedGeneration: 2
  phase: Ready
```

**Cluster Status to submit**:

```
$ kubectl rook-ceph ceph osd pool ls detail | grep mgr
Info: running 'ceph' command with args: [osd pool ls detail]
pool 2 '.mgr' replicated size 2 min_size 1 crush_rule 0 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 11 flags hashpspool stripe_width 0 pg_num_max 32 pg_num_min 1 application mgr read_balance_score 1.00
```

```
$ kubectl rook-ceph ceph osd crush rule dump replicated_rule
Info: running 'ceph' command with args: [osd crush rule dump replicated_rule]
{
    "rule_id": 0,
    "rule_name": "replicated_rule",
    "type": 1,
    "steps": [
        {
            "op": "take",
            "item": -1,
            "item_name": "default"
        },
        {
            "op": "chooseleaf_firstn",
            "num": 0,
            "type": "host"
        },
        {
            "op": "emit"
        }
    ]
}
```

```
$ kubectl rook-ceph ceph osd crush rule dump .mgr
Info: running 'ceph' command with args: [osd crush rule dump .mgr]
{
    "rule_id": 4,
    "rule_name": ".mgr",
    "type": 1,
    "steps": [
        {
            "op": "take",
            "item": -1,
            "item_name": "default"
        },
        {
            "op": "choose_firstn",
            "num": 0,
            "type": "osd"
        },
        {
            "op": "emit"
        }
    ]
}
```

I think this is a relatively recent regression. Looking at stacks that I have access to which are and aren't affected by this, the most I can narrow it down is that it was broken on 1.15.3 and working on 1.15.1.

**Environment**:
* OS (e.g. from /etc/os-release): Rocky 8
* Kernel (e.g. `uname -a`): Linux 4.18.0-553.22.1.el8_10.x86_64 #1 SMP Wed Sep 25 09:20:43 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: AWS (also seen on bare metal)
* Rook version (use `rook version` inside of a Rook Pod): v1.15.5
* Storage backend version (e.g. for ceph do `ceph -v`): 18.2.2
* Kubernetes version (use `kubectl version`): v1.29.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): HEALTH_OK

**Comment by travisn** [comment]
This is likely due to the new setting `enableCrushUpdates` that was introduced in #14322. Does setting `enableCrushUpdates: true` in your .mgr CephBlockPool resolve this issue? We likely should set the default on that pool to `true` since there is a race condition with Ceph creating the pool before Rook reconciles the pool the first time it is created. Other pools don't have this issue since Ceph doesn't auto-create them.

**Comment by sfackler** [comment]
Enabling that flag fixed the rule, thanks!
