### ISSUE TITLE
Rook CI builds failing on jenkins

### ISSUE THREAD

**Issue by dangula** [rook/rook#1504]
* Bug Report
 CI builds failing - GCE agents appear offline. 
**Bug Report**

What happened:
Looks like GCE build agents are offline and all build are failing 
What you expected to happen:
Build passes 
How to reproduce it (minimal and precise):
 - Run a build from jenkins.rook.io

**Comment by dangula** [comment]
fixing the by moving all build agents to aws.

**Comment by jbw976** [comment]
@dangula: @travisn updated the jenkins config so that the "test connection" buttons report success for all the GCE config.  However, we are still not seeing any GCE instances starting when a build runs.  Do you know where else we should look to remedy this issue?

**Comment by dangula** [comment]
looking at the logs will be the first step, you can find them under `Manager Config -> system log`. 
The logs are failry verbouse and they usually point to the issue. 
    If "test connection" is reporting success, then the next step would be to check slave agent configuration, under Manage Config -> configure systems. At the bottom of the page there should be multiple configurations for all the plublic cloud vendors. You can search for labels like "gce_1.6.x" or "gce_1.9.x" etc. Make sure the configuration here is correct, look at advance  settings too. These configurations take a machiene Id(something like us-east1/standard-2) and a Image Id. you the find the image id from GCE - compute Engine-> Images. There should be something obvious like Jenkins-packer-XXXX.

**Comment by travisn** [comment]
Ok, found how to apply the service account to hook up Jenkins to GCE again. The config that @jbw976 mentioned was the correct config, but had actually not been applied mistakenly. The builds are going successfully now.
