### ISSUE TITLE
Annotations applied to wrong daemons

### ISSUE THREAD

**Issue by tsufeki** [rook/rook#15055]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Annotations defined in cluster CR may be applied to wrong daemon (in addition to the correct one) if both `all` and specific sections are defined. In my case I saw annotations meant for mgr on an osd pod.

I believe Merge function in [pkg/apis/ceph.rook.io/v1/annotations.go](https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/annotations.go#L112) modifies `all` map instead of creating a new one. Similar issue for labels was fixed in 48d21947c2fade80c943cc666973f6559cb4c242, but was overlooked here.

**Expected behavior:**

Annotations are applied only to the specified daemon.

**How to reproduce it (minimal and precise):**

1. Add the snippet below to cluster CR
2. Check if pods other than mgr have `my-mgr` annotation

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

```yaml
  annotations:
    all:
      my-cluster: "foo"
    mgr:
      my-mgr: "bar"
```

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): Debian bookworm
* Kernel (e.g. `uname -a`): Linux bba01 6.1.0-27-amd64 # 1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.15.6, v1.14.4
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): v1.31.1+k3s1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by OdedViner** [comment]
The issue repuduced manually:

Tested Procedure:

1.Start minikube wiht kvm2:
```
$ minikube start --disk-size=10g --extra-disks=1 --driver kvm2
```

2.Create resources and operator
```
$ kubectl create -f crds.yaml -f common.yaml -f operator.yaml
```
```
$ kubectl get pods -n rook-ceph
NAME                                 READY   STATUS    RESTARTS   AGE
rook-ceph-operator-cf4f7dfd4-vzwbt   1/1     Running   0          89s
```

3.Create cluster-test:
````$ cd deploy/examples/
$ kubectl create -f cluster-test.yaml 
```

4.Add annotations to Cephcluster CR:
``` 
$ kubectl edit cephcluster -n rook-ceph
  spec:
    annotations:
      all:
        a: b
      mgr:
        x: z
```
5.Check annotion on osd,mg and mon:
mgr:
```
$ oc get pods rook-ceph-mgr-a-5978bb8fb7-9xdqh -n rook-ceph -o yaml | grep -i anno -B 1 -A 5
metadata:
  annotations:
    a: b
    x: z
  creationTimestamp: "2024-12-02T09:54:18Z"
  generateName: rook-ceph-mgr-a-5978bb8fb7-
  labels:
```
osd:
```
$ oc get pods rook-ceph-osd-0-758b5dfb6f-kjrkq -n rook-ceph -o yaml | grep -i anno -B 1 -A 5
metadata:
  annotations:
    a: b
    x: z
  creationTimestamp: "2024-12-02T09:54:46Z"
  generateName: rook-ceph-osd-0-758b5dfb6f-
```


x:z was added to the OSD annotations, even though it is only relevant to the MGR.
