### ISSUE TITLE
obc spec might have changed from objectBucketName to bucketName

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#15050]
**Is this a bug report or feature request?**
* Bug Report

obc notification controller showing this
```
2024-11-25 06:31:07.815342 I | ceph-bucket-notification: ObjectBucketClaim "openshift-storage/odrbucket-f475d57ec3e60649c536c7dee8ddc1cda947f34d" resource did not create the bucket yet. will retry
```
The check in the code https://github.com/rook/rook/blob/a8f8d57131fb03f0537a4711c19bcd0c3c83ae21/pkg/operator/ceph/object/notification/obc_label_controller.go#L113

Manually looking to CR, there was no `objectBucketName` but `objectBucket` was present

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by BlaineEXE** [comment]
`ObjectBucketName` is part of the OBC spec here: https://github.com/kube-object-storage/lib-bucket-provisioner/blob/d1a8c34382f127670e363ae925ae6087e8b2c7bf/pkg/apis/objectbucket.io/v1alpha1/objectbucketclaim_types.go#L53-L55

Where are you seeing only `objectBucket`?

**Comment by parth-gr** [comment]
Ahh, I actually saw `BucketName` https://github.com/kube-object-storage/lib-bucket-provisioner/blob/d1a8c34382f127670e363ae925ae6087e8b2c7bf/pkg/apis/objectbucket.io/v1alpha1/objectbucketclaim_types.go#L40

**Comment by BlaineEXE** [comment]
I believe `bucketName` is the internal RGW bucket name and `objectBucketName` is the name of the ObjectBucket (OB) resource that gets created to fulfill the OBClaim.

**Comment by parth-gr** [comment]
@BlaineEXE just checking if user is set `bucketName` will the `objectBucketName` would be present?
as in the test cluster I just saw `bucketName` in the obc spec

by which the check got failed https://github.com/kube-object-storage/lib-bucket-provisioner/blob/d1a8c34382f127670e363ae925ae6087e8b2c7bf/pkg/apis/objectbucket.io/v1alpha1/objectbucketclaim_types.go#L40
