### ISSUE TITLE
fix osd device class labels for brown field clusters

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#15082]
**Is this a bug report or feature request?**
* Bug Report

with the pr https://github.com/rook/rook/pull/15066 it fixes the problem for green field cluster,
Opening a tracker so to fix this issue with upgrades brown field clusters,

Suggestions:
1) Have a migration path between two latest releases( which will re-run prepare pods)
2) Use a new label with different name for the osd pods device class

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
This is related to updating the device class implemented in #14457.

If you set the `allowDeviceClassUpdate: true`, does it actually resolve this issue and set the correct label? If not, perhaps we can implement the fix in the same code path and require that flag to be set if they want the label to be fixed on existing OSDs.

For the fix, let's avoid requiring the osd prepare job to run again. For example, we could query ceph for the device classes assigned to the OSDs, then set the correct value from that. 

Alternatively, perhaps it is not common enough that we need to implement a fix. We could just require a manual update to the label on the OSD deployment for users who want to fix this. It would be a one-time operation that very few users likely would need to apply.

**Comment by parth-gr** [comment]
@travisn setting `allowDeviceClassUpdate: true` actually worked and changes the osd label on a brown field cluster.
