### ISSUE TITLE
CephFS saved files invalid or incomplete by using FIO verify

### ISSUE THREAD

**Issue by tw-yshuang** [rook/rook#15109]
**Is this a bug report or feature request?**

- Bug Report

**Deviation from expected behavior:**

- Using `cat` to view the file generated from `fio` shows garbled code.
- The verify by using `fio` shows the message like this:
  ```shell
  fio: verify type mismatch (46193 media, 18 given)
  fio: got pattern '22', wanted '74'. Bad bits 4
  fio: bad pattern block offset 0
  ...
  ```

**Expected behavior:**

- Using `cat` to view the file generated from `fio` shows like this:
  ```shell
  testtesttesttest...
  ```
- The verify report from the `fio` should not have the error message.

**How to reproduce it (minimal and precise):**

1. Create a Rook-Ceph cluster(Using both Helm-Chart or examples)
2. Create a filesystem pool(Using both StorageClass or Stativ PV/PVC)
3. Create a Pod that mounts the filesystem pool you just created, the container information for me is:

- image: `debian:buster`
- package from `apt`: `fio`

4. Enter to the container and execute:

   ```shell
   target_dir=/mnt/cephfs # the place that mounted the cephfs pool
   report_dir=/report # the place that you want to save the report
   size=100ki # whatever you want
   nrfiles=10 # whatever you want
   pattern=0x74657374 # means test, so the content should look like: testesttest...

   # write the test data
   fio --runtime=5M --rw=write --bs=4k --size=$size --nrfiles=$nrfiles --numjobs=16 --buffer_pattern=0x74657374 --iodepth=1 --direct=0 --ioengine=libaio --group_reporting --name=fiotest --directory=$target_dir --output $report_dir/sequential_write.log

   # Optional, synchronize cache data to the cephfs pool
   sync && echo 3 | tee /proc/sys/vm/drop_caches > /dev/null && sync

   # Optional, check the raw data
   cat $target_dir/fiotest.0.0 # expected outcome: testtesttest...

   # verify the files we just wrote
   fio --runtime=5M --verify_only --verify=pattern --verify_pattern=0x74657374 --size=$size --nrfiles=$nrfiles --numjobs=16 --bs=4k --iodepth=1 --direct=0 --name=fiotest --ioengine=libaio --group_reporting --verify_fatal=1 --verify_state_save=0 --directory=$target_dir --output $report_dir/verify_sequential_write.log
   ```

**File(s) to submit**:

- The Cluster CR (custom resource), typically called `cluster.yaml`, just change the element below:

  ```yaml
  spec.storage.useAllNodes: true
  spec.storage.useAllDevices: true
  spec.storage.node: ... # 3 nodes, each node assign one partition from lvm
  ```

**Logs to submit**:

- Operator's logs is all normal, did not show any message that related with the previous operation.

**Cluster Status to submit**:

- The rook health is `HEALTH_OK` by using `kubectl rook-ceph health`.

**Environment**:

- OS (e.g. from /etc/os-release): Ubuntu 22.04.5 LTS Server
- Kernel (e.g. `uname -a`): Linux 6.8.0-45-generic
- Rook version (use `rook version` inside of a Rook Pod): `v1.15.0` from git tag
- Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 18.2.4 (e7ad5345525c7aa95470c26863873b581076945d) reef (stable)`
- Kubernetes version (use `kubectl version`): `v1.29.9`
- Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): local cluster
- Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): will update it later.

**Comment by travisn** [comment]
Are you saying there is corruption? In any case, Rook is not in the data path and you would need to open a [Ceph tracker](https://tracker.ceph.com/) to have the cephfs team investigate.
