### ISSUE TITLE
Helm chart wait for TPRs\CRDs

### ISSUE THREAD

**Issue by TimJones** [rook/rook#1511]
**Feature Request**

A very simple quality-of-life feature for the Helm chart installation to wait until the TPRs\CRDs are available before finishing. This helps in cases such as using a [helmfile](https://github.com/roboll/helmfile) to deploy the operator, and a cluster.

I saw the idea in [prometheus-operator](https://github.com/coreos/prometheus-operator/blob/release-0.17/helm/prometheus-operator/templates/get-crd-job.yaml) and it looks very simple to adapt for rook-operator and I'd be happy to contribute it.

**Comment by jbw976** [comment]
This sounds like a very useful idea @TimJones, I like it!  I'd be happy to see a pull request with this enhancement :)

**Comment by TimJones** [comment]
Opened a PR, hope it gets in to 0.7 :)

Also noticed in the docs you're looking for contributions for charts for the resources themselves, were you thinking a chart per kind, or a generic one that can configure multiple clusters\pools\etc...
