### ISSUE TITLE
Smoke suite fails frequently waiting for rgw dashboard user creation

### ISSUE THREAD

**Issue by travisn** [rook/rook#15127]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The smoke suite is failing since the merge of #15035. 

In [this smoke suite instance](https://github.com/rook/rook/actions/runs/12260946682/job/34206813834), the error is:
```
2024-12-10 17:14:23.456433 I | integrationTest: output: . could not fetch user info: no user info saved
command terminated with exit code 22
    ceph_base_object_test.go:182: 
        	Error Trace:	/home/runner/work/rook/rook/tests/integration/ceph_base_object_test.go:182
        	Error:      	Received unexpected error:
        	            	exit status 22
        	Test:       	TestCephSmokeSuite/TestObjectStorage_SmokeTest/check_if_the_dashboard-admin_user_exists_in_all_existing_object_stores
```

Perhaps we just need the test to wait longer since the test does pass sometimes.

**Expected behavior:**
All CI should pass in master

**Comment by BlaineEXE** [comment]
I actually don't see how this could related to the COSI user backport at all. I think the timing is coincidence and maybe a red herring. 

This failure is stuck verifying the dashboard-admin user that we have had continual problems around, so I think this is something around that. It's returning code 22 (EINVAL). This looks really similar to this issue: https://github.com/rook/rook/issues/14947, but I am struggling to see how that relates to the `quay.io/ceph/ceph:v19` image used in CI which hasn't changed recently

The CephObjectSuite is where COSI is tested, and that test seems to be reliable. Interestingly though, COSI is tested **after** the dashboard-admin user. This test step passes in the object suite for reasons I don't understand at the moment.

**Comment by BlaineEXE** [comment]
The root of the issue appears to be here: https://github.com/rook/rook/blob/fc08e87d4493e1289417086220984a2b52fe9441/pkg/operator/ceph/object/objectstore.go#L1231-L1235

In this code that enables the dashboard for RGW, if the code fails, Rook just happily continues. 

I can also see instances where it seems like the dashboard might be getting stopped and restarted? I'm not 100% clear on that. But it seems like Rook is doing one thing in code and other in e2e tests. If the dashboard user reconciliation is optional enough to continue without failing the CephObjectStore reconcile, then we shouldn't be checking that it exists in our CI. What should we do to resolve this? Skip the CI check? Make the CI check an info log? Or make the user reconciliation in CephObjectStore required?

**Comment by travisn** [comment]
I can't think what else would have changed around this either. Perhaps we were waiting a while to verify the cosi user and the side effect was that this dashboard user check also succeeded. 

> I'm inclined to make the CI check informational since we have so much ongoing trouble with the RGW admin dashboard stuff.

Agreed, let's just make it informational for now, it's not critical for the CI.
