### ISSUE TITLE
ci: rgw-multisite-testing regularly fails

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#15194]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

rgw-multisite-testing CI test regularly fails. I haven't noticed any successes recently, but it's possible that it's flaky with high failure rates.

Links to failures, for comparison/investigation:
- https://github.com/rook/rook/actions/runs/12380234328/job/34556154058?pr=15192
- \<add more as needed\>

This is also preventing mergify from auto-merging backport PRs in 1.16 (and likely 1.15 also).

**Comment by travisn** [comment]
Same issue captured in #15177?

**Comment by BlaineEXE** [comment]
Oh, probably a duplicate, yes. Closing as dupe of #15177
