### ISSUE TITLE
--feature-gate is no longer present in csi-snapshotter causing container to fail.

### ISSUE THREAD

**Issue by DeprecatedLuke** [rook/rook#15221]
**Is this a bug report or feature request?**
* Bug Report

The '--feature-gate=CSIVolumeGroupSnapshot=true' is passed into csi-cephfs-plugin provisioner and csi-rbdplugin-provisioner in release v1.16, appears to be related to https://github.com/container-storage-interface/spec/pull/573.

The container will not start until the flag is removed from the deployment. However, the documentation is inconsistent since https://github.com/kubernetes-csi/external-snapshotter still claims that --feature-gate flag is required. (https://github.com/kubernetes-csi/external-snapshotter/issues/1223)

Tested versions:
 - registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0
 - registry.k8s.io/sig-storage/csi-snapshotter:v8.0.1 (default)
 
 Looking more into it, appears to be a typo. --feature-gate vs --feature-gates
 
 ---
 ```
 flag provided but not defined: -feature-gate
Usage of /csi-snapshotter:
-add_dir_header
If true, adds the file directory to the header of the log messages
-alsologtostderr
log to standard error as well as files (no effect when -logtostderr=true)
-csi-address string
Address of the CSI driver socket. (default "/run/csi/socket")
-extra-create-metadata
If set, add snapshot metadata to plugin snapshot requests as parameters.
-feature-gates value
Comma-seprated list of key=value pairs that describe feature gates for alpha/experimental features. Options are:
AllAlpha=true|false (ALPHA - default=false)
AllBeta=true|false (BETA - default=false)
CSIVolumeGroupSnapshot=true|false (BETA - default=false)
-groupsnapshot-name-prefix string
Prefix to apply to the name of a created group snapshot (default "groupsnapshot")
-groupsnapshot-name-uuid-length int
Length in characters for the generated uuid of a created group snapshot. Defaults behavior is to NOT truncate. (default -1)
-http-endpoint :8080
The TCP network address where the HTTP server for diagnostics, including metrics and leader election health check, will listen (example: :8080). The default is empty string, which means the server is disabled. Only one of `--metrics-address` and `--http-endpoint` can be set.
-kube-api-burst int
Burst to use while communicating with the kubernetes apiserver. Defaults to 10. (default 10)
-kube-api-qps float
QPS to use while communicating with the kubernetes apiserver. Defaults to 5.0. (default 5)
-kubeconfig string
Absolute path to the kubeconfig file. Required only when running out of cluster.
-leader-election
Enables leader election.
-leader-election-lease-duration duration
Duration, in seconds, that non-leader candidates will wait to force acquire leadership. Defaults to 15 seconds. (default 15s)
-leader-election-namespace string
The namespace where the leader election resource exists. Defaults to the pod namespace if not set.
-leader-election-renew-deadline duration
Duration, in seconds, that the acting leader will retry refreshing leadership before giving up. Defaults to 10 seconds. (default 10s)
-leader-election-retry-period duration
Duration, in seconds, the LeaderElector clients should wait between tries of actions. Defaults to 5 seconds. (default 5s)
-log_backtrace_at value
when logging hits line file:N, emit a stack trace
-log_dir string
If non-empty, write log files in this directory (no effect when -logtostderr=true)
-log_file string
If non-empty, use this log file (no effect when -logtostderr=true)
-log_file_max_size uint
Defines the maximum size a log file can grow to (no effect when -logtostderr=true). Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
```

**Comment by DeprecatedLuke** [comment]
Appears to be fixed in https://github.com/rook/rook/commit/477b7fd0f44719dcb737341d9efaa2510fa0ffc7, but the helm chart does not include such fix even though the version is v1.16.0.

**Comment by DeprecatedLuke** [comment]
Tracked it down to an transparent helm upgrade conflict.

**Comment by DeprecatedLuke** [comment]
Helm Chart should use 
```
  snapshotter:
    # -- Kubernetes CSI snapshotter image repository
    repository: registry.k8s.io/sig-storage/csi-snapshotter
    # -- Snapshotter image tag
    tag: v8.2.0
```

**Comment by warstrolo** [comment]
For what I have seen and my latest installation, this is included in the latest chart, the problem to the issue does not reside in the chart but in the operator code.

The operator does not check the version of CSI snapshoter that is deployed against the params it gives.

**Comment by DeprecatedLuke** [comment]
> For what I have seen and my latest installation, this is included in the latest chart, the problem to the issue does not reside in the chart but in the operator code.
> 
> The operator does not check the version of CSI snapshoter that is deployed against the params it gives.

Actually the operator helm chart just has the v8.0.1 version.

**Comment by DeprecatedLuke** [comment]
Appears to be fixed in later v1.16.0 releases. Pulled an older version of v1.16.0?

**Comment by travisn** [comment]
This was fixed by #15196, but has not been included in a release yet. See [this comment](https://github.com/rook/rook/issues/15195#issuecomment-2554471707) for a workaround, and we will get the v1.16.1 release out very soon with this fix.

**Comment by djjudas21** [comment]
Hmm I'm on RKE2 so it looks like https://github.com/rook/rook/issues/15234#issuecomment-2568945262 is relevant. Downgrading to v1.16.0 seems to work around it for now.

**Comment by DeprecatedLuke** [comment]
You are using v1alpha1 snapshotter cards. Update to v1beta1.

**Comment by Madhu-1** [comment]
Alpha CRD's are meant only for testing purpose as most of us know, we should not be using it in any production clusters as they are not suppose to be backward compatible and can break anything without any upgrade support. am not sure why RKE2 is installing the alpha CRD by default, I hope there will be an option to disable it. can someone check with RKE helm charts?
