### ISSUE TITLE
Using separate networks for Ceph cluster

### ISSUE THREAD

**Issue by hacor** [rook/rook#1523]
Hello,

I wanted to ask a question about the implementation of the [Ceph config parameters for networking](http://docs.ceph.com/docs/master/rados/configuration/network-config-ref/#ceph-networks). 
I'm trying to use different networks for my Rook cluster to be able to use QoS on my network switches to make sure the Rook cluster always has the bandwidth available it needs.
I was walking through the Rook code and a found a few references to the implementation: 
- [`rook/pkg/daemon/ceph/mon/config.go`](https://github.com/rook/rook/blob/021046792b64875b984ea1e120d722211b8addc5/pkg/daemon/ceph/mon/config.go#L69): The monitor config has the option for Public and Cluster network
- [`rook/pkg/clusterd/network.go`](https://github.com/rook/rook/blob/021046792b64875b984ea1e120d722211b8addc5/pkg/clusterd/network.go#L26): The clusterd also has the option available. It's probably just a way of testing and implementing.
Anyone who can give me a suggestion on how to start? I tried already using the `ConfigMap` override option and the cluster using `hostNetwork: true`. This was the configmap I used:

```
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook
data:
  config: |
    [global]
    public network =  10.111.0.0/16
    cluster network = 10.112.0.0/16
```

But the automatically created part of the config has an address field containing the range of the default route (`10.101.0.0/16`). I can see the override is also implemented, but Ceph uses the `public addr 10.101.0.10` and `cluster addr 10.101.0.10` fields from the generated config rather then the `public network 10.111.0.0/16` and `cluster network 10.112.0.0/16` filled with the overridden configmap.

Concerning the results from the code, it seems the option already exists, could it be they can be provided in the cluster yaml? 

Any suggestions are welcome!
I'll try to update the docs when it's working.

Best regards,
Hacor

**Comment by travisn** [comment]
@hacor these network settings are not exposed in the cluster yaml today. It was originally implemented as a feature of the standalone rook for #116, before we were focusing on kubernetes. You should be able to get this working with the configmap override. Did you try adding `public addr` and `cluster addr` to the override?

**Comment by hacor** [comment]
No, I didn't, but can I create an override per node? Because the `public addr` and `cluster addr` need to be fixed addresses not a a CIDR value as far as I remember... This means I need an address override for node1, node2, node3,... to give each of them the correct address.

**Comment by keeperAndy** [comment]
@hacor I was able to get rook to use my separate cluster network with `hostNetwork: true` using this configMap override that defines the `public addr` and `cluster addr` as empty along with the CIDRs you had already tried:

```
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: rook
data:
  config: |
    [global]
    public network =  10.111.0.0/16
    cluster network = 10.112.0.0/16
    public addr = ""
    cluster addr = ""

```

You can confirm that your OSD traffic is indeed running on the cluster network by checking that TCP ports in the 6800s are listening on the OSD nodes: `netstat -vatn | grep LISTEN | grep 680`. You should have a unique port open on each network in that range for every OSD process hosted on that node. Technically, ceph OSDs can try to use TCP ports all the way from 6800 to 7300, but generally they will start at 6800 and count up from there.

**Comment by aland-zhang** [comment]
I set rook-config-override  [global]
 public network = 192.168.192.0/24      
cluster network = 192.168.200.0/24  
public addr = ""   
cluster addr = ""

and I set  rook-ceph-mon dc  env:
           - name: ROOK_PRIVATE_IP
             Value: 192.168.200.153
           - name: ROOK_PUBLIC_IP
             Value: 192.168.192.153
But the port is only bound to an ROOK_PRIVATE_IP
netstat -nltp | grep 6790
tcp        0      0 192.168.200.153:6790    0.0.0.0:*               LISTEN      34641/ceph-mon
Executed by rook-ceph-tools:  ceph -s 
did not respond a long time. 
 because not bound ROOK_PUBLIC_IP 192.168.192.153:6790 ， 
Should be two ip are bound to the 6790 port, now only bound private ip (edited)

The ports of the two networks are bound at the same time, and both the mon and osd modules must be implemented.

**Comment by foldingbeauty** [comment]
Hi,

I tried to run Ceph through Rook with separated networks and found out that both environment variables (**ROOK_PRIVATE_IP** and **ROOK_PUBLIC_IP**) are set to PodIP. This means both EnvVars have the same IP. 

The Rook operator set both EnvVars to PodIP here:
https://github.com/rook/rook/blob/add4bd2fd252d6b78d4f93f15d96ea6f57150f24/pkg/operator/ceph/cluster/osd/pod.go#L114-L119

But the command to start Ceph OSD is forced using ROOK_PRIVATE_IP & ROOK_PUBLIC_IP here:
https://github.com/rook/rook/blob/add4bd2fd252d6b78d4f93f15d96ea6f57150f24/pkg/operator/ceph/cluster/osd/pod.go#L146-L150

You can check how Rook deploys the OSD in K8S with  `kubectl describe po/osd....` and you will find the startup variables are the same.

This shouldn't be the case IMHO. The above code will always bind the cluster to the public network, not matter what you set in your ConfigMap. Ceph is clever enough to figure out to which IP to bind to  when you set the ConfigMap like this, the Ceph OSD process will set the public to x.x.1.1 for example and the cluster to x.x.2.1 :
```
public network = x.x.1.0/24
cluster network = x.x.2.0/24
public addr = ""
cluster addr = ""
```

**How I fixed it:**

When I remove this line I can use Rook with Ceph using seperated networks:
https://github.com/rook/rook/blob/add4bd2fd252d6b78d4f93f15d96ea6f57150f24/pkg/operator/ceph/cluster/osd/pod.go#L149


At this point in time, seperated networks aren't supported. Will have a look for a proper fix and will PR the fix. Any comments welcome!

**Comment by jbw976** [comment]
Great debugging @foldingbeauty, thanks for sharing your findings.  Do you want to take a stab at submitting a PR for a code fix for this?  We are always accepting PRs :)  Here's a few useful links to help with the contributor workflow:
https://github.com/rook/rook/blob/master/CONTRIBUTING.md
https://github.com/rook/rook/blob/master/Documentation/development-flow.md

**Comment by billimek** [comment]
@foldingbeauty are you thinking of submitting a PR for this?  If not, I'm happy to.  I also desperately need this feature to leverage a dedicated 10GB network for rook/ceph.

**Comment by billimek** [comment]
#2154 submitted for this.

**Comment by caisan** [comment]
> @hacor I was able to get rook to use my separate cluster network with `hostNetwork: true` using this configMap override that defines the `public addr` and `cluster addr` as empty along with the CIDRs you had already tried:
> 
> ```
> apiVersion: v1
> metadata:
>   name: rook-config-override
>   namespace: rook
> data:
>   config: |
>     [global]
>     public network =  10.111.0.0/16
>     cluster network = 10.112.0.0/16
>     public addr = ""
>     cluster addr = ""
> ```
> You can confirm that your OSD traffic is indeed running on the cluster network by checking that TCP ports in the 6800s are listening on the OSD nodes: `netstat -vatn | grep LISTEN | grep 680`. You should have a unique port open on each network in that range for every OSD process hosted on that node. Technically, ceph OSDs can try to use TCP ports all the way from 6800 to 7300, but generally they will start at 6800 and count up from there.

hi, @hacor  could you please give more detail about how separate cluster network?
for exmaple:
Step 1:
Step 2:
....
you mean edit the configmap rook-config-override when the cluster is running? but when i do this, nothing works. rook version: 0.9.3, am i wrong?

**Comment by hacor** [comment]
@caisan It's been some time since I experimented with this setup, but I'll try my best to document as much as possible:
Interesting might be [this link](https://rook.io/docs/rook/v0.9/advanced-configuration.html#custom-cephconf-settings) to the documentation website of Rook. Let's try to take it down in steps:

- Create the following configmap in the  `rook-ceph` namespace before launching the cluster (make the necessary changes to your network ranges). Create the namespace if it doesn't exist yet.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    public network =  10.111.0.0/16
    cluster network = 10.112.0.0/16
    public addr = ""
    cluster addr = ""
```
- Now start your cluster as usual (indeed make sure that the cluster uses the `hostNetwork`) and the cluster will pick up the existing configmap and use the correct network ranges

All of this is taken from the documentation link provided at the beginning of this post.

Hopefully you succeed now!

Best regards

**Comment by caisan** [comment]
> @caisan It's been some time since I experimented with this setup, but I'll try my best to document as much as possible:
> Interesting might be [this link](https://rook.io/docs/rook/v0.9/advanced-configuration.html#custom-cephconf-settings) to the documentation website of Rook. Let's try to take it down in steps:
> 
> * Create the following configmap in the  `rook-ceph` namespace before launching the cluster (make the necessary changes to your network ranges). Create the namespace if it doesn't exist yet.
> 
> ```
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: rook-config-override
>   namespace: rook-ceph
> data:
>   config: |
>     [global]
>     public network =  10.111.0.0/16
>     cluster network = 10.112.0.0/16
>     public addr = ""
>     cluster addr = ""
> ```
> * Now start your cluster as usual (indeed make sure that the cluster uses the `hostNetwork`) and the cluster will pick up the existing configmap and use the correct network ranges
> 
> All of this is taken from the documentation link provided at the beginning of this post.
> 
> Hopefully you succeed now!
> 
> Best regards

@hacor cool, this is as same as i thought, which create configmap before `kubectl apply -f cluster.yaml`.  i will try it later. thanks a lot. Best regards

**Comment by hacor** [comment]
@caisan have you tried to restart the monitors one by one (delete the pods one by one)? If you do this always look in the toolbox with the `ceph - s` command for each mon to become stable before rebooting another.

**Comment by caisan** [comment]
> @caisan have you tried to restart the monitors one by one (delete the pods one by one)? If you do this always look in the toolbox with the `ceph - s` command for each mon to become stable before rebooting another.

restart monitor (by delete mon pods) does not work. When mon running, it still listen on 192.168.250.172:6789, which is k8s node ip, not along to the public network write in the configmap.

**Comment by caisan** [comment]
@hacor i have view the source of rook operator. when the cluster uses the hostNetwork, monitor ip is k8s node ip. and this will write to monmap, so restart mon(pod) does not work.

**Comment by kfox1111** [comment]
I just tried this, and its failing for me too. in the osd logs, it has:
2019-10-15 22:53:57.162107 I | parse error setting 'cluster_addr' to ''
2019-10-15 22:53:57.163737 I | parse error setting 'public_addr' to ''

Which I think is related.

**Comment by golgotow** [comment]
is this any progress ? using rook with only 1 network from kubernetes place it on very slow storage provider

**Comment by leseb** [comment]
> is this any progress ? using rook with only 1 network from kubernetes place it on very slow storage provider

It's now possible via Mutlus CNI. https://rook.io/docs/rook/v1.6/ceph-cluster-crd.html#multus

**Comment by bluikko** [comment]
> > is this any progress ? using rook with only 1 network from kubernetes place it on very slow storage provider
> 
> It's now possible via Mutlus CNI. https://rook.io/docs/rook/v1.6/ceph-cluster-crd.html#multus

https://github.com/rook/rook/blob/master/Documentation/ceph-advanced-configuration.md#use-hostnetwork-in-the-rook-ceph-cluster-configuration would make it look like it is possible using hostNetwork, is that not true and Multus is the only option?

**Comment by leseb** [comment]
> > > is this any progress ? using rook with only 1 network from kubernetes place it on very slow storage provider
> > 
> > 
> > It's now possible via Mutlus CNI. https://rook.io/docs/rook/v1.6/ceph-cluster-crd.html#multus
> 
> https://github.com/rook/rook/blob/master/Documentation/ceph-advanced-configuration.md#use-hostnetwork-in-the-rook-ceph-cluster-configuration would make it look like it is possible using hostNetwork, is that not true and Multus is the only option?

Both are possible.
