### ISSUE TITLE
Pick up Luminous 12.2.3

### ISSUE THREAD

**Issue by travisn** [rook/rook#1528]
Since Luminous 12.2.3 came out five days ago, I would have expected it to be picked up by the next Rook build. However, the latest master builds are still picking up 12.2.2.

The issue appears to be that the build machine is caching the docker layers. Until there is a change to the Dockerfile, 12.2.3 will not be picked up in the builds. Either we need the builds to check automatically if there is a new version of Ceph, or we need a way to manually clear the cache so the builds will pick up the new version. The latter actually seems better so we can make it an explicit decision to update Ceph. However, this still doesn't give us control over the version that is picked up in different branches (ie. `master` vs `release-0.7`)

**Comment by bassam** [comment]
once the work in the ceph-container project is complete we would be able to refer to a specific image like `ceph-base:v12.12.3` image. /cc @BlaineEXE @leseb

**Comment by travisn** [comment]
Ok, for now the easiest way to pick up 12.2.3 is to change the whitespace on [this line](https://github.com/rook/rook/blob/master/images/rook/Dockerfile.base#L19) so it will invalidate the cache. That worked for me locally.

**Comment by leseb** [comment]
I'm expecting this work to be completed this week or the next one. Once we have images online I'll submit a PR to switch.

**Comment by travisn** [comment]
The latest master build `v0.7.0-6.ga9d1528` now contains 12.2.3, as will all future builds including from the 0.7 release branch. Both jenkins agents were deleted and re-created.
