### ISSUE TITLE
Add support for NexentaEdge backend

### ISSUE THREAD

**Issue by dyusupov** [rook/rook#1532]
We need to add support for EdgeFS (OSS core of NexentaEdge) backend to be a part of 0.8 milestone if that is ok.

EdgeFS is high-performance and low-latency object storage system released under Apache License v2.0 developed in C/Go. It provides Kubernetes integrated Multi-Head Scale-Out NFS (POSIX compliant, Distributed RW access to files), Amazon S3 compatible API, iSCSI or NBD block interfaces, advanced global versioning with file-level granularity unlimited snapshots, global data deduplication and Geo-transparent access to data from on-prem, private/public clouds or small footprint edge (IoT) devices.

EdgeFS spans unlimited number of Geo-sites, connected with each other as one global name space data fabric running on top of Kubernetes platform, providing persistent, fault-talerant and high-performant volumes for Kubernetes Applications.

At each Geo-site, EdgeFS nodes deployed as containers (StatefulSet) on physical or virtual hosts, pooling all their storage capacity and presenting it as fully compatible S3/NFS/iSCSI object access for cloud-native applications running on the same or dedicated servers.

**Feature Request**

Are there any similar features already existing: no

What should the feature do:

enable use of rook.io framework to manage deployments of EdgeFS cluster namespaces

What would be solved through this feature:

normal backend operations has to be supported and verified via test suite. Test suite might need additional work

Does this have an impact on existing features:

It fits same way as Ceph does, no need to change existing APIs. It make sense to review Documentation to reflect Ceph and EdgeFS and other backends in more organized, similar ways.

**Comment by jbw976** [comment]
Keeping open as Nexenta support is in the roadmap.

**Comment by dyusupov** [comment]
Pull request was merged. Closing this issue and will open new issues for the following 0.9.x and 1.0.0
