### ISSUE TITLE
Pickup Ceph 12.2.4

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1541]
Tracking ticket because of the Ceph MGR Prometheus metrics issue users are currently experiencing.
The issue with the metrics is fixed in the latest Ceph releases.

**Comment by zhwenh** [comment]
yes,12.2.4 is released，It has modified a lot of bugs。

**Comment by bassam** [comment]
master build is broken now I'm assuming due to 12.2.4 being picked up and arm64 packages missing from upstream repos:

```
Get:17 http://ports.ubuntu.com/ubuntu-ports xenial-security/multiverse arm64 Packages [517 B]
Fetched 13.9 MB in 24s (575 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ceph-mon
E: Unable to locate package ceph-osd
E: Unable to locate package ceph-mgr
The command '/bin/bash -c CEPH_VERSION=luminous &&     apt-key add /tmp/release.asc &&     echo "deb http://download.ceph.com/debian-$CEPH_VERSION/ xenial main" | tee /etc/apt/sources.list.d/ceph-$CEPH_VERSION.list &&     DEBIAN_FRONTEND=noninteractive apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yy -q --no-install-recommends         ca-certificates         ceph-common         ceph-mon         ceph-osd         ceph-mds         ceph-mgr         kmod         radosgw         rbd-mirror &&     DEBIAN_FRONTEND=noninteractive apt-get upgrade -y &&     DEBIAN_FRONTEND=noninteractive apt-get autoremove -y &&     DEBIAN_FRONTEND=noninteractive apt-get clean &&     rm -rf         /etc/{selinux,systemd,udev}         /lib/{lsb,udev}         /tmp/*         /usr/lib/{locale,systemd,udev}         /usr/share/{doc,info,man}         /var/cache/debconf/*         /var/lib/apt/lists/*         /var/log/*         /var/tmp/*' returned a
non-zero code: 100
```

cc @leseb @dmick @liewegas any known issues?

**Comment by jbw976** [comment]
latest in master is now using 12.2.4:
```
root@rook-operator-77cf655476-dwzgj:/# ceph -v
ceph version 12.2.4 (52085d5249a80c5f5121a76d6288429f35e4e77b) luminous (stable)
```
The 0.7 release branch will pick this up as well next time we run a release build.

**Comment by JulijaB** [comment]
Hello, I am trying to run ceph-deploy install command for my nodes but I still keep receiving the error as mentioned by @bassam above - even though I am installing luminous release. Please let me know how to solve this issue? thank you

**Comment by jbw976** [comment]
@JulijaB, I'm not aware of the need to run `ceph-deploy` in any of the Rook scenarios covered in https://rook.io/docs/rook/v0.8/.  Can you provide some more context about your use case that is requiring you to run `ceph-deploy` directly?
