### ISSUE TITLE
Leverage node labels for storage devices in Cluster CRD

### ISSUE THREAD

**Issue by pierreozoux** [rook/rook#1549]
* Feature Request

**Feature Request**

Are there any similar features already existing: no

What should the feature do:
Currently, you configure the devices available in a node from the `Cluster` CRD.
Following registration/discovery pattern, it would feel nicer to set labels in the node itself to `register` what devices it has available for ceph.
Then the operator would discover them and configure ceph accordingly.

What would be solved through this feature:
In a dynamic environment, we can imagine nodes joining and leaving on there own, and this would ease the operations of such environment.

**Comment by kokhang** [comment]
@pierreozoux This is a great idea. I agree that having to specify devices on the Cluster CRD is not ideal. 

There are been talks about how to best approach this feature in the past. A proposal that has been brought forward is to leverage [LocalVolumes](https://kubernetes.io/docs/concepts/storage/volumes/#local) to define devices on nodes to be used by Rook. That way devices can be simply added/removed by adding or removing the LocalVolume resources.
 
I think this is something worth discussing with the community on how to best approach this issue.

**Comment by travisn** [comment]
I believe this is already implemented by #3093 (in v1.1)
