### ISSUE TITLE
Allow setting resources limits on the agent

### ISSUE THREAD

**Issue by beatlejuse** [rook/rook#1550]
i try to set resources limits as:
https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-cluster.yaml
and it's not working.
resource limits simply do not apply.
they are not present in a config if to look kubectl describe po.

Environment:
    OS (e.g. from /etc/os-release): CoreOS 1632.3.0
    Kernel (e.g. uname -a): Linux 4.14.19-coreos #1 SMP Wed Feb 14 03:18:05 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz GenuineIntel GNU/Linux
    Cloud provider or hardware configuration: baremetal (vmware)
    Rook version (use rook version inside of a Rook Pod): 0.6.0.219
    Kubernetes version (use kubectl version): api v1.8.6 / kubectl v1.8.6
    Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): none
    Ceph status (use ceph health in the Rook toolbox): HEALTH_OK

**Comment by galexrt** [comment]
The `v0.6.x` release didn't include resource requests and limits, see https://github.com/rook/rook/blob/release-0.6/cluster/examples/kubernetes/rook-cluster.yaml.
The feature was first included with `0.7.x`, see https://github.com/rook/rook/blob/release-0.7/cluster/examples/kubernetes/rook-cluster.yaml.

I suggest to use the specific `release-X.x` branch for the release you are running, to get the manifests that only contain the features of the release.

**Comment by beatlejuse** [comment]
@galexrt  ok.
I've updated to v0.7.0-10.g3bcee98
now resource requests and limits works for rook-operator, api, mgr, mon and osd.
But not works for mds and rook-agent

**Comment by galexrt** [comment]
The rook-agent doesn't have resource requests and limits exposed through the Cluster CRD.
Only components listed in the Cluster CRD (see https://github.com/rook/rook/blob/release-0.7/cluster/examples/kubernetes/rook-cluster.yaml#L59-L70) will receive resource requests and limits.

MDS get resource requests and limits through their respective Filesystem CRD, see https://github.com/rook/rook/blob/release-0.7/cluster/examples/kubernetes/rook-filesystem.yaml#L43-L50.

Changes to the values when a cluster already exists, won't be applied because updates to the Cluster CRD like this are currently not supported.

**Comment by galexrt** [comment]
@travisn We need to find a good way to allow setting resource limits on the rook-agent DaemonSet.
One way I can think of is to let the user create the rook-agent DaemonSet or either use flags on the operator (environment variables) to allow rook-agent DaemonSet resources to be set.

What do you think?

**Comment by travisn** [comment]
I like the idea of just letting the user create the agent daemonset. There isn’t much special about it. We can provide an example yaml that would start the agent. If you don’t create the agent yourself, the operator would still create it automatically. You would just need to create the agent before starting the operator. The operator would then recognize that the daemonset already exists and skip creating it. The same approach would apply to the new device discovery daemon.
