### ISSUE TITLE
Add NFS as a storage backend

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1551]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: Ceph is an existing storage backend for Rook and this would add NFS as another storage backend.

What should the feature do: From this feature, Rook would be able to orchestrate and deploy Network File System(s) in Kubernetes clusters.

What would be solved through this feature: Users would be able to setup and consume NFS storage.

Does this have an impact on existing features:  #1375 is the overall design for adding new storage backends to Rook, the refactoring determined by that ticket will be needed to implement this one.

**Comment by dimm0** [comment]
NFS already works fine as volumes in kubernetes. What would be the advantage of doing this with rook?

**Comment by jbw976** [comment]
@dimm0 my understanding with NFS in Kubernetes from https://kubernetes.io/docs/concepts/storage/volumes/#nfs is:
> Important: You must have your own NFS server running with the share exported before you can use it.

With the feature tracked by this issue, Rook would be able to orchestrate/deploy NFS server instances (in addition to dynamically provisioning NFS volumes) so that they user doesn't have to do that themselves.

**Comment by dimm0** [comment]
Ah! Got it. Thanks

**Comment by hunter** [comment]
What about adding support for the NFS Ganesha backend for Ceph (FS or RGW)? ceph-container already includes the packages so just a matter of exposing via Rook?

**Comment by rohan47** [comment]
Here is the design document for this feature request https://docs.google.com/document/d/1JTuSBudKD-DhEb6aWNCCVg7xP49f8FjPTSZlU-DOZRk/edit?usp=sharing
