### ISSUE TITLE
Design for volume snapshot and backup policy

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1552]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: Not within Rook, but there is a sig-storage effort for snapshot support that we should consider aligning with.  See:
https://github.com/kubernetes/kubernetes/issues/44172
https://github.com/kubernetes/features/issues/543

What should the feature do: A user of a kubernetes cluster with Rook should be able to create, manage and backup snapshots of their data that is managed by a Rook storage backend.  Policies should be defined to help configure snapshot and backup schedules, included data, retention, etc.

What would be solved through this feature:  Users will be able to safely backup their application data in a reliable and consistent manner.

**Comment by brianoppenheim** [comment]
Hi,
I'm interested in taking this up as a part of GSoC '18. I have experience with Golang as well as the theory behind distributed systems (global state and finding consistent snapshots included). Are there any prerequisites, and is this project still on the table?

**Comment by jbw976** [comment]
Awesome @brianoppenheim, thanks for reaching out and we're happy to hear your interest.  All of the [Rook projects](https://github.com/cncf/soc#rook) for Google's Summer of Code are still available, as the selection process does not start until March 27th according to the [timeline](https://summerofcode.withgoogle.com/how-it-works/#timeline).

The next step would be to submit an application/proposal to the [official site](https://summerofcode.withgoogle.com/) by March 27th.  We can help you with the specific project deliverables section of the application. Please feel free to reach out to @jbw976 and @travisn on Slack if you have any questions or need any support.  Thanks!

**Comment by travisn** [comment]
Keeping alive since it's in the roadmap

**Comment by travisn** [comment]
CSI seems to solve this for us
