### ISSUE TITLE
helm wait-on-resources-job.yaml template doesn't handle invalid semvers

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1567]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened: Installing Rook operator with Helm chart in a Kubernetes environment with an invalid k8s semver fails with the following error:
```
Error: render error in "rook/templates/wait-on-resources-job.yaml": template: rook/templates/wait-on-resources-job.yaml:25:100: executing "rook/templates/wait-on-resources-job.yaml" at <semverCompare ">=1.7...>: error calling semverCompare: Invalid Semantic Version
```

What you expected to happen: Installing Rook operator with helm to succeed

How to reproduce it (minimal and precise): Install Rook operator using the Helm v0.7.1 Helm chart using the instructions at https://rook.io/docs/rook/master/helm-operator.html.  The environment must have an invalid semver as shown in the environment section below.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v0.7.1
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.3-rancher1", GitCommit:"d5aea0c6d208786ae608d4154669de6e9319bdc7", GitTreeState:"clean", BuildDate:"2018-02-13T17:28:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jbw976** [comment]
@TimJones can any of the other functions in https://github.com/Masterminds/semver (I believe this is the library used by Helm) be used to validate the semver is valid before any other checks are performed?  Currently we are checking for empty strings at the top of the template, but if we could use a validation function from that library then we'd have all based covered without having to chase down edge cases.

**Comment by TimJones** [comment]
@jbw976 I have been looking into if the `.Capabilities.KubeVersion.GitVersion` is parsable as a semver object and using that. Then I discovered that Helm supports checking for APIs directly with `.Capabilities.APIVersions.Has` so I'm currently testing that and will move to use it if it proves fruitful :)
