### ISSUE TITLE
Replicate mgr pod

### ISSUE THREAD

**Issue by dimm0** [rook/rook#1581]
Is this a bug report or feature request?

* Feature Request

**Feature Request**

Today I rebooted the node running rook mgr0, and during the reboot all ceph IO stopped. I found that having mgr is required for running the filesystem: http://docs.ceph.com/docs/master/mgr/

Is there a way to start more than one instance of manager? Should it be the default setting?

What should the feature do:
Start several replicated instances of the manager

What would be solved through this feature:
The ceph cluster will keep working if the node running one of manager dies

Does this have an impact on existing features:
Not sure

**Environment**:
* OS (e.g. from /etc/os-release):
Centos 7
* Kernel (e.g. `uname -a`):
4.14.14-1.el7.elrepo.x86_64
* Cloud provider or hardware configuration:
baremetal
* Rook version (use `rook version` inside of a Rook Pod):
0.7.0
* Kubernetes version (use `kubectl version`):
1.9.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
Good after the manager was rebooted

**Comment by travisn** [comment]
@dimm0 we actually recently had running another mgr in standby mode. In #1334 we reverted the change due to an issue with the prometheus metrics module, and also Kubernetes is expected to failover the mgr pod. Before you rebooted the node, did you drain the pods?

**Comment by dimm0** [comment]
I couldn't drain the pods. The node ran out of memory, and I couldn't kill a single pod - that was the reason to reboot.
Tried to find the discussion about prometheus.. Could you plz direct me to that problem discussion? What exactly is the problem with prometheus?

**Comment by travisn** [comment]
In #1154 it looks like the prometheus metrics will be empty for the standby mgr. However, it's not clear to me why we would need to not have a standby mgr for this reason. @galexrt do you recall why this blocked the metrics change? In this scenario hit by @dimm0, the standby mgr would have enabled the cluster to continue working during the reboot.

**Comment by galexrt** [comment]
@travisn The metrics were not empty, the standby mgr responded with connection refused because the port is not listening until it is active.
Why is the/a mgr needed for the cluster to continue working in that case? It is a stateless part of the cluster which only:
> [...]to provide additional monitoring and interfaces to external monitoring and management systems.
> - From the Ceph Manager Daemon doc page.

> [...]the ceph-mgr daemon is required for normal operations.
> - From the Ceph Manager Daemon doc page.

But that doesn't mean that the cluster won't work when no mgr is running.
> [...]you will see a health warning to that effect, and some of the other information in the output of ceph status will be missing or stale until a mgr is started.
> - From the Ceph Manager Daemon doc page.

Overall the Ceph Manager is advertised as "not required" for the cluster to work, as seen in the last quote.

Source: http://docs.ceph.com/docs/master/mgr/

**Comment by travisn** [comment]
oh right, the mgr shouldn't be required. @dimm0 were there other pods on that node such as the `mds`? If all mds pods were down, it would certainly stop the filesystem from working.

**Comment by dimm0** [comment]
The node is also running 1 of 5 monitors, and 1 of OSD. I thought restarting an OSD shouldn't affect the IO, since the pool has replication factor of 2 and min_size 1, but now I'm looking at previous restarts for other OSD nodes, and looks like every lost of OSD causes IO to stop.. So probably it's not the MGR's fault.
My guess is that more OSDs go offline once they lose connection to the restarted one. I've seen this before, when I reboot one node, and more nodes show they're broken. Now at least it all recovers.

**Comment by travisn** [comment]
@dimm0 ok thanks for confirming. Ready to close this issue or is there something else to investigate?

**Comment by dimm0** [comment]
Let's close for now. I'll reopen if I have more troubles.
Thanks for your help!

**Comment by sebastian-philipp** [comment]
duplicates #1796
