### ISSUE TITLE
Define a CRD for object store users

### ISSUE THREAD

**Issue by travisn** [rook/rook#1583]
Creating a user for the object store requires access to the rook toolbox to run some specific commands for `radosgw-admin`. This escapes the expected pattern of using K8s resources to configure the cluster. 

A K8s secret would be created to store the sensitive secret for the user.
For object store users to query the creds for a user, two attributes would be added to the CRD under the `status` section:
- The user access key
- A reference to the K8s secret for the user's secret key

A new documentation topic would be needed under the CRD heading. This would replace the toolbox commands found [here](https://github.com/rook/rook/blob/master/Documentation/object.md#create-a-user).

**Comment by dgonzalezruiz** [comment]
I am very much interested on this! Would gladly self-assign this, as would hugely benefit from it.

My personal usecase/operation is the following: 
1) Create user
2) Configure some user settings (specifically, I change the default `max_buckets` and set an user  quota of X bytes (so that the user is only allowed to use a share of the cluster, in a more graceful way than using ceph pool quotas). Also, it would be cool if more complex configuration like IAM policies (for example, for sharing buckets among users) was possible.

Regarding the implementation, I have a doubt. This would need to be implemented both for Ceph and Minio, right?

**Comment by travisn** [comment]
@dgonzalezruiz sounds great for you to take this. Here are a few thoughts...

While we will want the users to be created for both ceph and minio, I believe the design would involve having separate CRDs for Ceph and Minio object store users. The two object stores will certainly have different features in the long term and the separate CRDs would allow them to specialize. 

Under the covers there is likely an opportunity for common implementation. This is similar to the [storage node](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L55) in the cluster crd. The `storage` node is deserialized by a type in the `rookv1alpha2` namespace as defined [here](https://github.com/rook/rook/blob/master/pkg/apis/rook.io/v1alpha2/types.go#L31). This allows multiple types of cluster CRDs to work with the storage nodes with common code, while then being able to add cluster-specific properties as needed in the rest of the CRD. Similarly, I would expect the object store user CRD will define a type in the `rookv1alpha2` namespace that will be common to ceph and minio.

**Comment by travisn** [comment]
Here are some thoughts in case someone wants to jump into getting this done...

### Design

An example CRD:
```yaml
apiVersion: ceph.rook.io/v1beta1
kind: ObjectStoreUser
metadata:
  name: my-user
  namespace: rook-ceph
spec:
  store: my-store
```

The elements of the CRD include:
- `apiVersion` & `kind`: newly defined in the CRD definition in operator.yaml.
- `name`: The name of the crd object to be created, which corresponds to the `--uid` of the radosgw-admin command
- `namespace`: Must be the same as where the rook cluster is running
- `store`: The k8s name of the object store that has been created in the cluster. In the samples, it would be `my-store` as seen in `object.yaml`.

Other properties could be added in the future as suggested by @dgonzalezruiz such as:
- `quota`: The user's quota in number of bytes
- `policy`: The IAM policy(ies) to apply to the user (this is likely a complex type or list rather than a string) 

When the CRD is created, the operator would:
1. Create the rados user with the command: `radosgw-admin user create` as seen [here](https://rook.io/docs/rook/v0.8/object.html#create-a-user)
1. Extract the access and secret keys from the `radosgw-admin` results
1. Save the access and secret keys in a K8s secret. The secret would have the properties:
  - Name: `rook-ceph-object-user-<name>`
  - Namespace: same as the cluster
  - Two `data` values: `accessKey` and `secretKey` where the two secrets are stored
4. Apply other settings/policies as defined in the CRD

### Client access
The object user creds would be needed by a client that is going to consume the object store. The user creds could be accessible by a pod started in the cluster namespace either as environment variables or mounted as a file. 

If the user creds are needed by a pod outside the namespace, the admin would need to copy the secret from the cluster namespace, or else create the RBAC role that would give the other namespace access to the secrets. The RBAC rule would allow access to all secrets, however, so it is not recommended.

### Implementation
- The CRD would need to be defined in operator.yaml, next to the [ObjectStore CRD](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L38).
- The operator should start watching for the new CRD after the [object store CRD is created](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/controller.go#L220).
- The implementation for handling the CRDs should likely go in `pkg/operator/ceph/object/user_controller.go`. It will be implemented very similarly to [controller.go](https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/controller.go) in the same folder that handles the object store CRD (you can ignore anything referring to legacy object stores).
- The operator needs to have the new CRD registered [here](https://github.com/rook/rook/blob/master/tests/integration/base_object_test.go#L54)
- When the scenario is implemented and manually tested and you're ready to add integration tests, there are [existing integration tests](https://github.com/rook/rook/blob/master/tests/integration/base_object_test.go#L54) that were commented out that we would want to re-enable now using the object user CRDs.

This implementation is focused in the ceph operator. I'm not seeing where it would make sense to share with minio, but would be great if someone with more minio perspective could chime in.

**Comment by zieg8301** [comment]
I've got a standalone controller working with similar functionality to this. I'll see if I can integrate it with the existing ceph operator successfully and may be able to get a PR opened if I can tweak mine to offer the behavior laid out above.

**Comment by travisn** [comment]
@zieg8301 It will be great to see your implementation integrated with Rook. If you have other design suggestions, my thoughts above certainly are open for discussion. Thanks!

**Comment by zieg8301** [comment]
I've used a lot of the above for inspiration, and am on the same page. The only piece I'm not 100% certain on is the namespace placement of the objectstoreuser object/secret. In our use case we only have one rook-ceph cluster running in the k8s cluster, and multiple app teams with their own namespaces. 

My standalone controller currently has the user create the objectstoreuser in their own namespace, and then creates the access secret in the same namespace. I could see how that would be difficult in a k8s cluster with multiple rook-ceph clusters running though. Definitely looking for feedback on that. I can always implement the users as described above and then tweak locally for our desired implementation.

**Comment by travisn** [comment]
@zieg8301 i'm struggling with that question too. An object store user really is something that belongs to a consumer and you likely want to create a different user for each namespace that is consuming the storage. If we followed the pattern for other k8s storage, it's as if the admin should create an "object store storageclass" that allows an object store user to be created, then an "object store PV" could be created, which would generate the user for use in a namespace. 

Alternatively, a simple approach would be if there is a `consumerNamespace` setting in the crd that would tell rook where to copy the secret. However, this means you would have to give access to Rook to write secrets to that namespace, which Rook doesn't have by default.

**Comment by zieg8301** [comment]
@travisn I've got some working code in the project, the image builds just fine (integration tests and secret extraction have yet to be implemented), however once I launch the operator in our k8s cluster, I get the following error:

`E0823 19:07:51.448877       7 reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1beta1.ObjectStoreUser: no kind "ObjectStoreUserList" is registered for version "ceph.rook.io/v1beta1"`

I saw your comment above about registering the CRD with the operator, but I think the link was incorrectly pointed at the integration tests. Could you give me some insight on where to register the CRD? Thanks.

**Comment by jbw976** [comment]
@zieg8301 i sent you an invite to the rook organization so that we can assign this issue to you, since you have started the implementation with #2076

**Comment by zieg8301** [comment]
With the PR opened, I've assigned this task to myself. Open to any feedback on #2076

Currently I've only coded actions in the operator for create/delete events. Once more specs have been added, such as the ones referenced by @dgonzalezruiz above, update event handling would likely need to be added as well. Not sure if that is worth holding the initial release for or not.
