### ISSUE TITLE
Add RBD mirroring support

### ISSUE THREAD

**Issue by inv8r** [rook/rook#1588]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: 
Yes.

What should the feature do: 
The feature should extend Rook to allow for orchestration of rbd-mirror daemon pod. See [ceph docs](http://docs.ceph.com/docs/jewel/rbd/rbd-mirroring/) for more information about RBD mirroring. 

What would be solved through this feature: 
The ability to mirror RBD pools or single volumes between clusters.

Does this have an impact on existing features: 
Not that I am aware of.

**Comment by jbw976** [comment]
I like this idea @inv8r because it helps with backups, disaster recovery and multi-cluster/multi-cloud scenarios.
