### ISSUE TITLE
Can't delete “rook” namespace

### ISSUE THREAD

**Issue by zhijiansd** [rook/rook#1595]
```
# kubectl get ns rook
NAME      STATUS        AGE
rook      Terminating   2d
```
I don't know if this is a bug。When I continue to delete，The following error occurred
```
# kubectl delete ns rook
Error from server (Conflict): Operation cannot be fulfilled on namespaces "rook": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
```
My English is not good. I hope you can read it and give me an answer.

**Comment by recall704** [comment]
```
kubectl delete -f rook-operator.yaml
kubectl delete -f rook-cluster.yaml
```

how about this ?

**Comment by zhijiansd** [comment]
Yes,After deleting, namespace rook has been in Terminating state
NAME      STATUS        AGE
rook      Terminating   2d

**Comment by travisn** [comment]
@zhijiansd can you check if the cluster crd still exists? See this help topic: https://rook.io/docs/rook/master/teardown.html#removing-the-cluster-crd-finalizer

**Comment by zhijiansd** [comment]
I cannot edit  cluster CRD
# kubectl -n rook edit cluster rook
error: clusters "rook" could not be patched: the server does not allow this method on the requested resource (patch clusters.rook.io rook)
You can run `kubectl replace -f /tmp/kubectl-edit-nyxxv.yaml` to try this update again.

**Comment by patrickstjohn** [comment]
@zhijiansd We've run into this once or twice. Verify everything in the rook ns has been deleted (any rogue pvc's etc. hanging around will also prevent the ns from cleanly deleting). In our cases once this is done deleting the CRD finalizer has allowed us to delete the ns if it's still stuck.

**Comment by PatrickHuetter** [comment]
Same problem as described in @zhijiansd answer here. Can't patch the rook cluster.

**Comment by iedwin** [comment]
I ran into this issue today as well in my k8s v1.9.0 cluster. I finally managed to delete the stuck ns by running the follow command after login into etcd pod.
```
etcdctl del /registry/rook.io/clusters/rook/rook
```

**Comment by danpe** [comment]
Thanks @iedwin! that worked!

**Comment by galexrt** [comment]
I think the docs cover the cleanup steps https://rook.io/docs/rook/v0.8/ceph-teardown.html.

Also it seems that the objects which could not be removed with the finalizers were only stuck on older versions of Kubernetes (around < 1.7) (and uneditable to fix the deletion).

If you should run into this problem again, please reopen this issue.
