### ISSUE TITLE
ceph: add mds to embedded ceph

### ISSUE THREAD

**Issue by bassamtabbara** [rook/rook#161]
Add MDS to embedded ceph and push upstream.

**Comment by hunter** [comment]
A question out of curiosity, does rook expose the standard ceph mon/osd ports? I was wondering if it was possible to run a standard `ceph-mds` (from ceph-docker) in a separate container and connect as normal. I assume the answer is yes as it seems the RBD client connects normally but thought I would check anyway.

**Comment by bassamtabbara** [comment]
you should be able to access the standard mon/osd ports. However, we are planning to add MDS (and RGW) into Rook so that they can be managed along with MON and OSD.

**Comment by hunter** [comment]
Yes, understood that it will be part of Rook. Was mostly a question out of curiosity to see if things from the community could be run. We've got a few custom Ceph tools (APIs, Prometheus exporters, etc) that would be good to run in parallel until similar features exist in Rook.

**Comment by bassamtabbara** [comment]
@hunter got it ;-)
