### ISSUE TITLE
Include Kubernetes 1.10 in testing platforms

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1623]
Our CI builds should be updated to include the new release of Kubernetes 1.10.

It would also be nice to update `minikube.sh` so that 1.10 is the new default.

**Comment by coolpalani** [comment]
Is it supporting Kubernetes 1.10.1 version

**Comment by jbw976** [comment]
Yes @coolpalani, the integration testing support that @travisn has right now in his pull request is for 1.10.1: https://github.com/rook/rook/pull/1644/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3R73

**Comment by coolpalani** [comment]
I deployed Kubernetes 1.10.2 using kubeadm and top of installed the rook but when I tried to provision storage, it's not provisioning.
