### ISSUE TITLE
Recovery after loss of (just) an OSD metadata disk is not handled cleanly

### ISSUE THREAD

**Issue by Ulexus** [rook/rook#1627]
Loss of an OSD metadata disk results in a loss of the OSD(s) using that MD (so far as I am aware), but the OSD wrapper (agent and daemon) does not appear to handle the loss (and subsequent replacement) of a metadata disk cleanly.

Currently, after replacing a metadata disk, the old metadata disk is still stored in the PerfScheme for the node, which blocks the new metadata disk from being used.

I would say that it should be easy to add a comparison for the disk IDs similar to that done for the OSD data disks, but this has the potential to impact a number of OSDs (since the default setup in Rook is to run the metadata for all OSDs on a node in a common metadata disk, so it probably merits some discussion on this before a solution is crafted.

For reference, here is what happens when a metadata disk is replaced:

```
2018-04-06 04:23:23.431822 E | op-cluster: failed to update cluster in namespace rook. failed to start the osds. 1 failures encountered while running osds in namespace rook: orchestration for node cc3.internal.cycore.io failed: &{Status:failed Message:failed to configure devices. failed to get OSD partition scheme: sdc is desired for metadata, but sdc (b5c8b8c9-acfb-439e-9653-50b9c1b1a9dd) is already the metadata device}
```

The `b5c8b8c9-acfb-439e-9653-50b9c1b1a9dd` is the GUID of the _old_ metadata disk which has died and since been replaced.  Rook refuses to allocate the replacement `sdc` (metadata) disk because the old disk is already assigned to that function.  There is no check at this point to see that that disk still exists.

**Comment by Ulexus** [comment]
It would appear this will require a bit more infrastructure than currently exists.  Presently, the OSD removal is limited to whole node removal anyway; removal of discrete OSDs is not a supported automatic operation.

Any views on the safety of comparing the stored partition schema to the current partition schema and culling discrepancies?  Unless we are dealing with removable media, I believe that should be safe enough.

**Comment by jbw976** [comment]
@Ulexus can you help me better understand the resiliency of a bluestore OSD after losing both its database and write ahead log?  Can the OSD recover at all, or would it have to be entirely scrapped? That would have a big impact on how we'd need to deal with losing the metadata disk on a node. Thanks!

**Comment by Ulexus** [comment]
I do not have an authoritative answer, as I have not looked at the code, but my understanding from experiment and personally-constructed model is that the OSD would be scrapped.  It may be theoretically possible to recover the data in the same sense that you can recover data from a filesystem whose table is corrupt, but it seems that that would be impractical as a standard practice.

**Comment by Ulexus** [comment]
I don't believe bluestore changes this general operation.  Bluestore was mainly about replacing the custom-designed store with a more modern, more standard key-value store to obtain better performance and maintainability.  (Again, this is my perception as an outsider looking in.)

**Comment by Ulexus** [comment]
Of course, I should say that you are correct:  the _deployment_ characteristics are different.  Bluestore's storage metadata is integral.  It's deployment-modeled metadata is actually its WAL, as you mention, and I don't actually see any reason that _that_ should have to scrap the OSD on its loss.

I don't actually know what the practical result of the loss of the WAL is, though.  I don't have experiment to determine that.  That would surely depend on the write resolution algorithms adopted by the monitors... and I just don't know what those are.

**Comment by travisn** [comment]
this issue will be handled by ceph-volume going forward, which is being worked on with #1342

**Comment by christianhuening** [comment]
Hey, I just ran into this with Rook 0.9.2 and Ceph 13.2.4. So assuming i am already using `ceph-volume` as this cluster was created with Rook 0.9.1. I had to remove and re-add all of my nodes one-by-one and then for the last 2 of them this error happened. 

How is this recoverable?
