### ISSUE TITLE
Service Monitor will not work if it is in rook namespace 

### ISSUE THREAD

**Issue by cornelius-keller** [rook/rook#1631]
https://github.com/rook/rook/blob/e388eae6aa257622f18ac95a158522c18b91182a/cluster/examples/kubernetes/monitoring/service-monitor.yaml#L5

The service monitor will not work as documented if it is created in the rook namespace.
See discussion here: https://github.com/coreos/prometheus-operator/pull/813

**Comment by galexrt** [comment]
@cornelius-keller It is assumed that you use the Prometheus manifests for the prometheus-operator as shown in the docs which are deployed to the `rook` namespace: https://rook.io/docs/rook/master/monitoring.html#prometheus-instances.

**Comment by cornelius-keller** [comment]
ah ok. then it will work. Sorry for confusion.

**Comment by travisn** [comment]
@cornelius-keller, shall we close this then?
