### ISSUE TITLE
rook operator terminates with fatal error if there is more than 1 container in pod

### ISSUE THREAD

**Issue by Data-drone** [rook/rook#1633]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:
rook operator terminates with a fatal error if there is more than 1 container in pod. This happens when istio sidecar is auto injected by the system. 

What you expected to happen:
rook operator should run as per normal

How to reproduce it (minimal and precise):
run `kubectl create -f rook-operator.yaml` with istio sidecar auto inject enabled.

**Environment**:
* OS Ubuntu 16.04.4 LTS 
* Kernel (e.g. `uname -a`): 4.4.0-116-generic
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod): rook doesn't deploy properly
* Kubernetes version (use `kubectl version`): Major:"1", Minor:"9", GitVersion:"v1.9.6"
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal (with kubespray)
* Ceph status (use `ceph health` in the [Rook toolbox] NA (https://Rook.io/docs/Rook/master/toolbox.html)):

**Comment by jbw976** [comment]
This also could affect other places of the code (OSD operator) where we are checking the number of containers in a pod

**Comment by muhlba91** [comment]
@Data-drone @jbw976 could you please share the configuration you used?
I tried creating a cluster using Istio 1.1.7 now and it hangs with `rook-ceph-detect-version`. This job never finishes - probably due to sidecar injection? In fact, the operator never continues bootstrapping the cluster. Also, if I kill the pod manually the operator doesn't detect multiple containers in it, resulting in:
```
2019-05-29 12:54:21.823307 E | op-cluster: unknown ceph major version. failed to get version job log to detect version. failed to read from stream. a container name must be specified for pod rook-ceph-detect-version-4qjmq, choose one of: [version istio-proxy] or one of the init containers: [istio-init]
```
