### ISSUE TITLE
CRD handling prevents updating the number of mons

### ISSUE THREAD

**Issue by travisn** [rook/rook#1636]
The operator has already implemented the ability to change the number of mons in the quorum. During the health checks, if more mons are desired, one will be added at a time. If fewer mons are desired, one at a time will be removed until we reach the desired state.

When the `monCount` is updated in the cluster CRD, the operator logs the message that the update is not supported. Restarting the operator may get past this, but usually will show the same error in the log.
```
update event for cluster rook is not supported
```

**Comment by clkao** [comment]
This is a regression of what #1096 implemented.

**Comment by travisn** [comment]
still need this...
