### ISSUE TITLE
Does recreate cluster need to delete operator and agent recreate first?

### ISSUE THREAD

**Issue by JeromeGe** [rook/rook#1646]
I deleted cluster and recreate it, sometimes it succeeded, sometimes it does not create any resources and no logs. I need to delete and recreate operator and agent before recreate cluster.

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 16.04
* Kernel (e.g. `uname -a`): 4.4.0-63-generic
* Cloud provider or hardware configuration: Aliyun cloud
* Rook version (use `rook version` inside of a Rook Pod): v0.7.0-79.g7151492
* Kubernetes version (use `kubectl version`): 1.9.2

**Comment by travisn** [comment]
@JeromeGe Could you confirm if you followed all the steps in the [cleanup guide](https://rook.io/docs/rook/master/teardown.html)? And do any pods or rook namespaces exist after you are done cleaning up? Here are some steps to troubleshoot [here](https://rook.io/docs/rook/master/common-issues.html#troubleshooting-techniques). Note that a common issue with teardown is that the crd is not removed. See [this topic](https://rook.io/docs/rook/master/teardown.html#troubleshooting).

**Comment by JeromeGe** [comment]
@travisn I deleted all the crds according to the cleanup guide. The rook namespace and pod and other resources have been deleted.

**Comment by galexrt** [comment]
@JeromeGe Did you also wait completely until all resources are cleaned up, before deleting the Rook operator?
> After those block and file resources have been cleaned up, you can then delete your Rook cluster. This is important to delete before removing the Rook operator and agent or else resources may not be cleaned up properly.
> - https://rook.io/docs/rook/master/teardown.html

**Comment by JeromeGe** [comment]
@galexrt I do not want to delete the oprator, just want to delete the cluster and recreate it. block and file resources have not yet been created.

**Comment by travisn** [comment]
@JeromeGe are you by chance running the 0.7 build? I believe there is a fix since then that will allow you to delete a cluster and create a new one without deleting the operator.

**Comment by JeromeGe** [comment]
@travisn I'm using the v0.7.0-118.gbfd48e2 version and have this problem too.

**Comment by jbw976** [comment]
I believe this has been fixed, please let us know if this can be reproduced with v0.8+ builds. thanks!
