### ISSUE TITLE
Create one osd deployment per device

### ISSUE THREAD

**Issue by travisn** [rook/rook#1656]
Per the [one osd per pod](https://github.com/rook/rook/blob/master/design/dedicated-osd-pod.md) design, the operator should create one deployment per device. First, the device will need to be provisioned with a bath job, then the osd deployment can be started.

**Comment by zhwenh** [comment]
Hello everyone, today I tested the version: rook/ceph:v0.7.0-240.gc568dd6 In the openshift 3.9 cluster(One master node,Three salve node), I found an osd deployment（name: 10.10.41.50） with two osd processes.
root       259     7  0 03:20 ?        00:00:04 ceph-osd --foreground --id=2 --cluster=rook --osd-data=/var/lib/rook/osd2 --conf=/var/lib/rook/osd2/rook.config --keyring=/var/lib/rook/osd2/keyring --osd-uuid=bf1f0544-d977-4127-a
root       508     7  0 03:20 ?        00:00:06 ceph-osd --foreground --id=3 --cluster=rook --osd-data=/var/lib/rook/osd3 --conf=/var/lib/rook/osd3/rook.config --keyring=/var/lib/rook/osd3/keyring --osd-uuid=2ef6949f-4aff-47d0-8

Did not implemented the feature "Create one osd deployment per device"! 

Other ceph related features are implemented.
this is my cluster config:
apiVersion: ceph.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook
spec:
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: true
    count: 3
  network:
    hostNetwork: true
  serviceAccount: default
  storage:
    config:
      databaseSizeMB: '1024'
      journalSizeMB: '1024'
      storeType: bluestore
      walSizeMB: '2024'
    nodes:
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: vdc
        name: 10.10.3.148
        resources: {}
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: vdc
        name: 10.10.5.180
        resources: {}
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: vdc
          - FullPath: ''
            config: null
            name: vdd
        name: 10.10.41.50
        resources: {}
    useAllDevices: false

Note that the configuration of **FLEXVOLUME_DIR_PATH** in openshift is different from that in Kubernetes.

      containers:
        - args:
            - ceph
            - operator
          env:
            - name: RBAC_ENABLED
              value: 'true'
            - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
              value: 'true'
            - name: ROOK_LOG_LEVEL
              value: INFO
            - name: ROOK_MON_HEALTHCHECK_INTERVAL
              value: 45s
            - name: ROOK_MON_OUT_TIMEOUT
              value: 300s
            - name: FLEXVOLUME_DIR_PATH
              value: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
            - name: ROOK_SKIP_SET_OWNER_REF
              value: 'true'
            - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
              value: 'true'
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
