### ISSUE TITLE
kubelet_volume* / persistent volume metrics missing

### ISSUE THREAD

**Issue by HaveFun83** [rook/rook#1659]
Is this a bug report or feature request? **BUG**

* Bug Report

**Bug Report**
/kind bug

What happened:
 I am trying to get kubelet_volume_* metrics working. According this google/cadvisor#1702 (comment) there should be support after 1.8 kube. However, I am now using kube 1.10.0 and still cannot see anything in /metrics? Should these be there or not?

```
curl -s https://localhost:10255/metrics -k|grep kubelet_volume|wc -L
0

```
```
pvc-d64b963b-4578-11e8-9cf2-d4ae526fcc30   100Gi      RWO            Delete           Bound     default/prom-test-prometheus-server         rook-block               2d

prom-test-prometheus-server         Bound     pvc-d64b963b-4578-11e8-9cf2-d4ae526fcc30   100Gi      RWO            rook-block     2d
```

What you expected to happen:
 I except that kubelet should expose prometheus volume metrics to /metrics path as well. Then it is easy to read with prometheus and to monitor the persistent volume usage status
How to reproduce it (minimal and precise):

Create the default storage-class and a persistent-volume-claim but no persistent volume metrics will be published

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 9.4
* Kernel (e.g. `uname -a`): 4.9.0-6-amd64 
* Cloud provider or hardware configuration: Bare-Metal
* Rook version (use `rook version` inside of a Rook Pod): `v0.7.0-87.g2d40c08`
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare-metal
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

```
root@rook-tools:/# ceph -s
  cluster:
    id:     6af9b6be-2998-4b56-8d62-37fa609f5bde
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon0,rook-ceph-mon2,rook-ceph-mon1
    mgr: rook-ceph-mgr0(active)
    osd: 9 osds: 9 up, 9 in
 
  data:
    pools:   2 pools, 200 pgs
    objects: 3040 objects, 10636 MB
    usage:   220 GB used, 16541 GB / 16762 GB avail
    pgs:     200 active+clean
 
  io:
    client:   42977 B/s wr, 0 op/s rd, 1 op/s wr

```
Please have a look at this issue currently it is not possible to monitor the pv usage.
tia

**Comment by jbw976** [comment]
I'm not sure I fully understand how the `kubelet_volume*` metrics feature works as described in https://github.com/kubernetes/kubernetes/issues/62644.  Is it the responsibility of each volume plugin to report metrics back to the Kubelet?  Does the in-tree Ceph RBD plugin already support this? Any pointers? Thanks!

**Comment by sordfish** [comment]
I could also do with a work around.

@jbw976 I'm no expert but looking at the cinder code mentioned in kubernetes/kubernetes#62644 this is also in the in-tree RBD plugin.

**Comment by kongslund** [comment]
It is the responsibility of each volume plugin to provide metrics. [FlexVolume](https://github.com/kubernetes/kubernetes/blob/5044a3d12cd8a7c01045651646d6a76864661027/pkg/volume/flexvolume/mounter.go#L35) and [CSI volume](https://github.com/kubernetes/kubernetes/blob/5044a3d12cd8a7c01045651646d6a76864661027/pkg/volume/csi/csi_mounter.go#L69) do not support metrics at the moment. It is not clear to me how they can acquire that information in a standard way. Metrics are not part of the [FlexVolume spec](https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md) nor the [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md) spec. Regarding CSI, I've created https://github.com/container-storage-interface/spec/issues/253.

**Comment by strowi** [comment]
Hi,

looks like at least Flexvolume might gain that ability in 1.13. https://github.com/kubernetes/kubernetes/pull/67508

**Comment by thlassche** [comment]
1.13 is in alpha now and it landed in the spec as well: 
https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetvolumestats
So I guess it can be implemented soon? @kongslund

**Comment by thlassche** [comment]
Is there an update on this?

**Comment by travisn** [comment]
@rootfs something to consider for ceph-csi, or is it already planned?

**Comment by anmolsachan** [comment]
> @rootfs something to consider for ceph-csi, or is it already planned?

@travisn This is much required for ceph-csi for integration with Openshift and OCS, since there metrics will be required to show the PV and PVC usage. I have been looking around for these metrics for monitoring use-cases. It would be great if this could be prioritized.

**Comment by HaveFun83** [comment]
@galexrt is there any tracking when this merge will be available in the stable release tree

**Comment by galexrt** [comment]
@HaveFun83 The PR got merged to `master` so it will be available in the next release `v1.1`.

If there is a high need for this to be in v1.0, I would recommend joining the Community Meeting and bringing it up as a point (best to add an agenda item point, see Readme of repo). 

@travisn @jbw976 What do you think on the spot about backporting this to v1.0 and possibly get this released in a patch release?

**Comment by HaveFun83** [comment]
Thx for the info. 
Backporting will be great if possible

**Comment by travisn** [comment]
Sounds good to backport, it's a low risk change.

**Comment by ctyjrsy** [comment]
I am running a k8s cluster on digital ocean, are do-block-storage volume type supported in prometheus monitoring via publish of kubelet_volume* metrics. I can not access these metrics via grafana (Prometheus Operator setup)

Running K8S 1.12+

**Comment by galexrt** [comment]
@ctyjrsy Are you using DigitalOcean Block storage with Rook or without Rook?

If just using DigitalOcean block storage, it depends on their Flexvolume / CSI driver to implement the needed interfaces for such metrics.

**Comment by travisn** [comment]
Will be included in v1.0.3

**Comment by onedr0p** [comment]
Do I need to do anything specific to enable these metrics? I am not seeing them in Prometheus. My rook-ceph deployment is [here](https://github.com/onedr0p/k3s-gitops/tree/master/deployments/rook-ceph)

**Comment by travisn** [comment]
@onedr0p Did you find help topic for [enabling monitoring](https://rook.io/docs/rook/v1.2/ceph-monitoring.html)?

**Comment by onedr0p** [comment]
Yes, I have done that and I can see `ceph_*` metrics in Prometheus, however no `kubelet_volume_*` metrics.

**Comment by travisn** [comment]
@onedr0p If you're using the flex driver (not enabled by default in rook anymore), the metrics should be available by default. With the CSI driver, there are some metrics enabled by default as well with [this setting](https://github.com/rook/rook/blob/release-1.2/cluster/examples/kubernetes/ceph/operator.yaml#L183-L184). [Here](https://github.com/ceph/ceph-csi/blob/ae67534a448161ed0128e0212788d268291abbc8/docs/metrics.md#grpc-metrics) is a link to more info. If you're still not finding what you need, I'd suggest a new github issue.

**Comment by dimm0** [comment]
I can see metrics fine from rook

**Comment by onedr0p** [comment]
Thanks @travisn I will debug more on my end before opening an issue.

**Comment by onedr0p** [comment]
For anyone coming here looking for the same information as me, check out this issue: https://github.com/coreos/prometheus-operator/issues/2359 and https://github.com/kubernetes/kubernetes/issues/68522

My ask to anyone here who has it working, what did you do? It seems like it doesn't work out of the box with Prometheus Operator. Does there need to be any documentation written around this?

**Comment by admincasper** [comment]
@onedr0p  Did you find anything with prometheus-operator that stops curl from working correctly on the prometheus server? The grafana dashboard that uses the same metric works fine..
