### ISSUE TITLE
graceful removal of OSDs

### ISSUE THREAD

**Issue by xetys** [rook/rook#1662]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: moving ceph mons from tainted nodes

What should the feature do: In general, the user can decide were OSDs are placed using taints/nodeSelector, but it might happen that the user still needs to remove deployed OSDs gracefully, without risking a data lost. While moving mons is straight forward, moving OSDs needs more actions. In my case I did the following:

1.  I need to set some flags for recovery:
```
# ceph osd set noscrub
# ceph osd set nodeep-scrub
```

2. get all osd ids and remove them from the crush map using

```
# ceph osd crush rm {bucket-name}
```

3.  wait until the entire recovery is done, by watching `ceph -w`

4. remove the osds so ceph notice they are down

5. purge the osds

```
# ceph osd purge {id} --yes-i-really-mean-it
```

6. reset the flags

```
# ceph osd unset noscrub
# ceph osd unset nodeep-scrub
```

What would be solved through this feature: This would ensure, everytime when OSDs are removed, ceph is in a healthy state. The background here is, that increasing OSD count changes the object placement by ceph crush algorithm, so the new OSDs got loaded immediately when they are added. There are a lot of cases when nodes with OSDs have to be deleted. In my personal case I scaled my workers with 10 additional temporary nodes, and had no nodeSelector. I ended up in performing these steps manually before drain+deleting the nodes.

This topic was already discussed with @galexrt and he asked me to place this issue here.

**Environment**: Kubernetes provisioned by https://github.com/xetys/hetzner-kube, but this issue is general
* OS (e.g. from /etc/os-release): Ubuntu 16.04
* Kernel (e.g. `uname -a`): 4.4.119
* Cloud provider or hardware configuration: 
* Rook version (use `rook version` inside of a Rook Pod): 0.7.1
* Kubernetes version (use `kubectl version`): 1.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): hetzner-kube with kubeadm

**Comment by galexrt** [comment]
@jbw976 Do you think this could be done by utilizing your logic for adding/removing directories/devices for OSDs which makes sure the cluster healthy on removal/creation?

**Comment by xetys** [comment]
A possible approach to solve this would be inventing a new CRD called "OSD".

If rook deploys a new OSD, the operator creates an OSD CRD with all relevant data (device, capacity, etc).

When a user is deleting it with a command like `kubectl delete osd osd-xxx -n rook`, the operator performs the above-mentioned steps to actually delete the OSD.

Another approach would be the same stuff but storing the metadata in config maps, what was @galexrt's suggestion. It would be easier to achieve, but I think using CRDs would be more the "kubernetes way".

**Comment by jbw976** [comment]
Thanks for the suggestion @xetys.  I think that the graceful removal of an OSD without data loss should be completely covered by the scope of #1435.  All additions and removals of storage to the cluster should be done by editing the cluster CRD, I don't think any new CRD types are needed for this.

The graceful removal of OSDs is already implemented at the node level in master (entire node's worth of OSDs can be gracefully removed), so a lot of the logic has already been written.

I'm going to close this specific issue since I believe #1435 covers it.
