### ISSUE TITLE
metadataDevice on a per node basis

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1663]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: 
Devices can be specified per node.

What should the feature do:
In the Cluster CRD there should be the possibility to specify a `metadataDevice` on a per node basis too.

What would be solved through this feature:
Allowing more granular configuration per node for the metdata device.

Does this have an impact on existing features:
No.

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

/cc @christianhuening

**Comment by galexrt** [comment]
@travisn Yeah, I looked at the docs again and found that for node settings there is a ref to the storage selection settings.

**Comment by galexrt** [comment]
@christianhuening

**Comment by christianhuening** [comment]
>because if the operator sees it is empty and then fills it with the cluster wide value would be bad for you.

It does that AFAIK as per the docs. So i meant to not specifiy the cluster wide metadataDevice but instead add it to each node settings and leave it out at the one where we dont have an nvme drive

**Comment by galexrt** [comment]
@christianhuening Yes removing the cluster wide and adding it to each node would allow to do that.

Still a better solution would be to change the type of the`metadataDevice` and other similar options from `string` to `*string`, so if unset it is `nil` and if user wants it empty it is `""`.

**Comment by mikabytes** [comment]
`metadataDevice` must be placed in a `config` object, i.e. not a sibling to the `devices` key. See [this comment](https://github.com/rook/rook/issues/9430#issuecomment-995546886) for more information. The suggestion above might have been correct for an earlier version of Rook (I'm not sure), but for 1.8.0 it won't work.
