### ISSUE TITLE
modprobe: FATAL: Module rbd not found

### ISSUE THREAD

**Issue by tobru** [rook/rook#1677]
**Bug Report**

Mounting fails:
```
Warning  FailedMount            8s (x5 over 18s)  kubelet, node4  MountVolume.SetUp failed for volume "pvc-3e76a0c6-498a-11e8-ac6f-36c9e300001a" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume replicapool/pvc-3e76a0c6-498a-11e8-ac6f-36c9e300001a: failed to map image replicapool/pvc-3e76a0c6-498a-11e8-ac6f-36c9e300001a cluster rook. failed to map image replicapool/pvc-3e76a0c6-498a-11e8-ac6f-36c9e300001a: Failed to complete rbd: exit status 2. output: modinfo: ERROR: Module rbd not found.
modprobe: FATAL: Module rbd not found in directory /lib/modules/3.10.107-pine64
rbd: failed to load rbd kernel module (1)
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (2) No such file or directory
```
`ceph-common` is installed, version `10.2.9-0ubuntu0.16.04.1`.

What you expected to happen: Mount works.

How to reproduce it (minimal and precise): Install rook as documented on an arm64 environment.

Directly on the host:
```
modprobe: FATAL: Module rbd not found in directory /lib/modules/3.10.107-pine64
```

In an agent pod:
```
# kubectl -n rook-system exec rook-agent-rhw7v modprobe rbd
modprobe: FATAL: Module rbd not found in directory /lib/modules/3.10.107-pine64
command terminated with exit code 1
```

**Environment**:
* OS (e.g. from /etc/os-release): Armbian, based on Ubuntu Xenial
* Kernel (e.g. `uname -a`): `Linux node2 3.10.107-pine64 #2 SMP PREEMPT Wed Apr 18 16:59:50 CEST 2018 aarch64 aarch64 aarch64 GNU/Linux`
* Cloud provider or hardware configuration: OrangePI
* Rook version (use `rook version` inside of a Rook Pod): v0.7.1
* Kubernetes version (use `kubectl version`): v1.9.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
@tobru You need to run `modprobe rbd` directly on the hosts, that is because of the old kernel you are using.
The issue doesn't appear with 4.x kernels (not 100% sure which minor it was fixed).

So the fix is to either add `rbd` kernel module to `modules-load.d`/`modprobe.d` on the hosts or upgrade the kernel to 4.x.

If that doesn't fix the issue, than this maybe something arm64 related which we haven't seen yet.

**Comment by tobru** [comment]
Thanks @galexrt As you may see in the description, I've already tried to run modprobe directly on the node:

```
root@node1:~# modprobe rbd
modprobe: FATAL: Module rbd not found in directory /lib/modules/3.10.107-pine64
```

Upgrading is unfortunately not possible because of the lack of hardware support (missing patches).

The question is: Where does the rbd Kernel module come from? Is it part of the Kernel, or is it installed with a package?

**Comment by tobru** [comment]
I'll ask the Armbian community if they know anything about it. In the meantime, I tried to load the module on a RasbperryPi with `Raspbian GNU/Linux 9 (stretch)` and Kernel `4.14.34-v7+`, but I hit the same issue:

```
# modprobe rbd
modprobe: FATAL: Module rbd not found in directory /lib/modules/4.14.34-v7+
```

**Comment by HaveFun83** [comment]
Maybe you can try to install inux-image-extra-`uname -r` to get the rbd kernel module.

**Comment by tobru** [comment]
Too bad, it's not available =(

```
$ apt search linux-image-extra
Sorting... Done
Full Text Search... Done
```

**Comment by galexrt** [comment]
@tobru I'm thinking that this is more or less a problem of the platform you are running on not having the `rbd` kernel modules available.
I'm not seeing what Rook can do to fix the issue.

What do you think?

**Comment by tobru** [comment]
@galexrt I agree, let's close this issue. I try to get this fixed in Armbian.

**Comment by galexrt** [comment]
@tobru Please keep us updated when this is fixed on Armbian so other Raspberry Pi users know about it.

**Comment by 0xf2** [comment]
@tobru did Armbian make any progress in this regard? Hitting this issue with Stretch.

**Comment by danacr** [comment]
I ended up just recompiling the kernel and installing the newer version: https://github.com/danacr/kubernetes-the-fun-way/blob/master/docs/04-rook-ceph.md
