### ISSUE TITLE
Support orchestration of Minio with an operator

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1680]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: The Ceph operator performs orchestration for Ceph distributed storage, which has similar concepts for deploying cloud-native storage in kubernetes.

What should the feature do:  This feature would introduce new CRD types for Minio and an operator that performs the deployment, orchestration, and management of Minio in Kubernetes.

**Comment by jbw976** [comment]
Yes @hunter you can run all the Rook operators and the storage providers that they orchestrate at the same time.  There may be a demo here at Kubecon EU that shows them all running together :)

**Comment by hunter** [comment]
Shame I couldn't make it over to Kubecon. Looking forward to seeing it shared later :)
