### ISSUE TITLE
rbd map exceed 1 minute

### ISSUE THREAD

**Issue by mhcvs2** [rook/rook#1681]
Is this a bug report or feature request?

* Bug Report
* Feature Request

**Bug Report**

What happened:
when I create a pod with ceph pvc:
```
 MountVolume.SetUp failed for volume "pvc-a39d6916-4a1f-11e8-bf47-90b8d0599f2f" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume replicapool/pvc-a39d6916-4a1f-11e8-bf47-90b8d0599f2f: failed to map image replicapool/pvc-a39d6916-4a1f-11e8-bf47-90b8d0599f2f cluster rook. failed to map image replicapool/pvc-a39d6916-4a1f-11e8-bf47-90b8d0599f2f: Failed to complete 'rbd': signal: interrupt. . output:
pod has unbound PersistentVolumeClaims (repeated 5 times) 
```
I use a device /dev/sdb which is 4TB. 

The error is because: "rbd map" command is not successfully within one minute which is specified in mon.go.

This timeout named "cmdExecuteTimeout" should be logger or config with env.

What you expected to happen:
Volume should be mounted

How to reproduce it (minimal and precise):

**Feature Request**

Are there any similar features already existing:

What should the feature do:

What would be solved through this feature:

Does this have an impact on existing features:

**Environment**:
* OS (e.g. from /etc/os-release): centos 7
* Kernel (e.g. `uname -a`): Linux node3 4.14.3-1.el7.elrepo.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

**Comment by travisn** [comment]
@mhcvs2 can you look at the logs for the rook-agent pod on that node where it was trying to mount? Perhaps it was formatting for a long time with a large volume, or else it could be an old kernel as mentioned in [this issue](https://github.com/rook/rook/issues/1110#issuecomment-367199838).

**Comment by galexrt** [comment]
This can potentially be fixed when nbd is used for mounting instead of rbd, from what I heard.
The overall problem here which was "fixed" some time ago by setting the timeout to 1 minute, needs to be looked at again.
Though the problem with simply increasing the timeout is that it is in question what type of timeout is going on, because it is either just taking an amount of time to map/mount the volume or as another example mon timeout due to cluster health issues.

Maybe @kokhang knows of a solution for this as he implemented the flexvolume agent (+ timeout)?

**Comment by patrickstjohn** [comment]
We're running into similar issues to this and #1280 that are making large deployments unusable for anything larger than a few nodes with large volumes. This appears to only really manifest itself in our case when our cluster gets filled with a fair amount of data (+1PB). My guess is things are finally getting slow enough that we're running up against the timeout value.

**Comment by patrickstjohn** [comment]
Referenced a workaround in #1280 changing the filesystem type from ext4 to xfs appears to work much better.

**Comment by jbw976** [comment]
I believe this issue is the same as #1280 so I am going to close this one for now as a duplicate.  Please let me know if there is a clear difference between these two issues, thanks!
