### ISSUE TITLE
how to add a hard disk to rook

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#1686]
how to add a hard disk to rook

**Comment by jbw976** [comment]
Hi @13567436138, currently in Rook v0.7, there is only official support for adding and removing entire nodes (with all their disks and directories).  This can be done by editing the cluster resource, as described in https://rook.io/docs/rook/master/cluster-crd.html#node-updates.

Further work to support adding and removing individual disks and directories is being tracked by #1435.

Unofficially, it could be possible to manually edit the daemonSet or replicaSet for the OSD node that you care about to update the `deviceFilter` field or list of devices.  Then delete the OSD pod so a new one with the new config will start up.  The new disks *should* get added to the cluster, but I have not tried it myself.  Keep in mind that is not a supported scenario, so only try that if you are brave and on a test cluster that is expendable.

I'm going to close this ticket in favor of #1435
