### ISSUE TITLE
how to reduce osds   osd: 10 osds: 2 up, 3 in

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#1688]
# ceph -s
  cluster:
    id:     2821d7c2-947a-4012-b2c7-ba78abaa4345
    health: HEALTH_WARN
            noscrub,nodeep-scrub flag(s) set
            1 osds down
            3 hosts (4 osds) down
            clock skew detected on mon.rook-ceph-mon4, mon.rook-ceph-mon0
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon1,rook-ceph-mon4,rook-ceph-mon0
    mgr: rook-ceph-mgr0(active)
    osd: 10 osds: 2 up, 3 in
         flags noscrub,nodeep-scrub
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 bytes
    usage:   3338 MB used, 2786 GB / 2789 GB avail
    pgs:

**Comment by travisn** [comment]
@13567436138 how many OSDs are you expecting? 5? You can use the ceph tools from the rook toolbox to remove the extra osds. The command you might want is `ceph osd crush remove <osd>`. See [this page] for more potential usage of the ceph tools. 

And was there some error condition when rook was creating the osds? We should understand why extra osds were created.
