### ISSUE TITLE
Rook operator tries to schedule mons on NotReady nodes

### ISSUE THREAD

**Issue by dimm0** [rook/rook#1699]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
I have a couple nodes in the cluster which are broken and are in NotReady state. Currently there's one mon scheduled to run on one such node, and will never start on it.

What you expected to happen:
Only schedule mons on nodes which are available

How to reproduce it (minimal and precise):
Add a node, stop docker on it. Start more mons to force it to run on that node (haven't tried but this should do it)

**Environment**:
* OS (e.g. from /etc/os-release):
CencOS 7
* Kernel (e.g. `uname -a`):
4.16.0-1.el7.elrepo.x86_64
* Cloud provider or hardware configuration:
Baremetal
* Rook version (use `rook version` inside of a Rook Pod):
0.7.1
* Kubernetes version (use `kubectl version`):
1.10.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm
* Ceph status (use `ceph health` in the [Rook toolbox]
HEALTHY_OK

**Comment by travisn** [comment]
@dimm0 is it possible that the mon had already been assigned to the node when the node was ready, then it went to the `NotReady` state? The operator checks [here](https://github.com/rook/rook/blob/c7e9b0f51988f61d7a06cb85ce58091e08624769/pkg/operator/cluster/ceph/mon/util.go#L250) if the node is ready before mons are assigned to it.

**Comment by dimm0** [comment]
That node was never ready, I'm sure about that.. It's totally broken :)

**Comment by dimm0** [comment]
Ok, closing the ticket until I'm 100% sure the node was always NotReady.
