### ISSUE TITLE
jenkins: should cancel a build run when commit is removed from branch

### ISSUE THREAD

**Issue by bassam** [rook/rook#170]
when a developer rebases commits and does a push -f to a feature branch, jenkins should stop the prior build. we should not have concurrent builds for the same PR branch.

**Comment by bassamtabbara** [comment]
![screen shot 2016-11-12 at 11 36 26 am](https://cloud.githubusercontent.com/assets/1463491/20240409/4a386e5c-a8cc-11e6-9301-caebcb5c10dc.png)

**Comment by DoubleDensity** [comment]
I vote to close this one for now as stale
