### ISSUE TITLE
Replace pkg.util.sys.Awk() with strings.Fields()

### ISSUE THREAD

**Issue by tonya11en** [rook/rook#1700]
**Feature Request**

**Are there any similar features already existing:**
No

**What should the feature do:**
Replace the custom Awk() function and all of its tests with the [strings.Fields()](https://golang.org/pkg/strings/#Fields) function found in the standard library. We don't rely on the 0th index special case and there's not a clear reason for keeping this function around.

**What would be solved through this feature:**
A leaner and cleaner code base.

**Does this have an impact on existing features:**
No, we don't rely on any special cases.

**Comment by checkaayush** [comment]
@tonya11en I'd like to take this up. Although, this would mean
```
mountPoint := Awk(Grep(output, searchFor), 3, " ")
```
will now look something like this:
 
```
slice := strings.Fields(Grep(output, searchFor))
if len(slice) >= 3 {
	mountPoint = slice[2]
}
```
Does that work?

**Comment by tonya11en** [comment]
Sure, there's nothing wrong with that. What's going on is actually clear. We might even consider renaming `Grep` to something that's actually descriptive of what it does.
