### ISSUE TITLE
jenkins: static check does not have a link in certain cases

### ISSUE THREAD

**Issue by bassamtabbara** [rook/rook#171]
In some instances the status check for jenkins is not hyperlinked:

![screen shot 2016-11-12 at 11 34 26 am](https://cloud.githubusercontent.com/assets/1463491/20240397/01c99538-a8cc-11e6-8f9f-4a8239eb182d.png)

**Comment by DoubleDensity** [comment]
I think this may have been a transient event due to job debugging on the jenkins instance; please update this issue if you see the behavior again
