### ISSUE TITLE
Provide operator support for authenticated Docker Registries

### ISSUE THREAD

**Issue by patrickstjohn** [rook/rook#1713]
* Feature Request

We are using VMWare Harbor for our private Docker registry. Rook does not currently support authenticated Docker registries. As a workaround we have an unauthenticated repository which is hosting the Rook containers but it would be ideal if the Rook operator supported this. Ideally, the imagePullSecret used to obtain the Rook operator would be included in any follow on deployments handled by the Rook operator.

**Feature Request**

Are there any similar features already existing: No, updating the rook-operator.yaml to include a imagePullSecret works for the operator image but not follow on deployments.

What should the feature do: Allow for operability with a secure Docker registry.

What would be solved through this feature: Ineroperability with production private Docker registries.

Does this have an impact on existing features: Not that I know of.

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.4
* Kernel (e.g. `uname -a`): 4.16.3-1.el7.elrepo.x86_64 #1 SMP Thu Apr 19 08:21:26 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Bare Metal
* Rook version (use `rook version` inside of a Rook Pod): v0.7.1
* Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare Metal
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
@patrickstjohn Would it be enough to add a `imagePullSecret` to "all" components created by the Rook operator?
So that an admin "only" needs to create the Secrets in the namespace(s) where the cluster and other components (rook-agent, rook-discover) will run in.

**Comment by galexrt** [comment]
@patrickstjohn Could you give the docs you sent a go to see if that works?
If it does, let us know if you are up for sending a PR to change the docs.

**Comment by danielcb** [comment]
Just found this issue and tried the suggested solution. Works as expected. If you give me a hint regarding the best place for this documentation snippet, I'll add it and possibly extend the `./cluster/kubernetes/ceph` example.

**Comment by travisn** [comment]
@danielcb What all was needed for it to work? Looks like a `kubectl patch serviceaccount` command? Perhaps you could update the docs in ceph-quickstart.md as a subsection of "Deploy the Rook Operator". Thanks!

**Comment by danielcb** [comment]
Added some docs. Let me know if it's okay this way and that's the correct spot.
