### ISSUE TITLE
the server could not find the requested resource (get clusters.rook.io)

### ISSUE THREAD

**Issue by ticruz38** [rook/rook#1715]
**Bug Report**

What happened:
On rook-operator pods log
> github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1alpha1.Cluster: the server could not find the requested resource (get clusters.rook.io)

What you expected to happen:

How to reproduce it (minimal and precise):
Initiated with kubeADM, Using calico CNI, and scaleway provider on 3 start1M machines

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04 
* Kernel (e.g. `uname -a`): Linux kube1 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Scaleway
* Rook version (use `rook version` inside of a Rook Pod): rook: v0.7.0-122.g656d223
* Kubernetes version (use `kubectl version`): 1.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubeadm
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

**Comment by ticruz38** [comment]
Scaleway recently changed their machine and infrastructure, do you think it could be related to a firewall settings?

**Comment by galexrt** [comment]
@ticruz38 Which manifests did you use to create the operator?
I suspect that you are using an old manifest which uses the `master` tag for the operator and which do not contain the CRDs and other components that the operator nowadays does not create anymore (but are created through the cluster admin).

Can you verify that you either have Rook operator running on `0.7.1` and used the https://github.com/rook/rook/tree/v0.7.1/cluster/examples/kubernetes manifests, or if you want to use `master` tag use the latest manifests from here for https://github.com/rook/rook/tree/master/cluster/examples/kubernetes.

**Comment by ticruz38** [comment]
thanks it worked as you said, I used an older version
