### ISSUE TITLE
Base discovery inventory of devices on ceph-volume

### ISSUE THREAD

**Issue by jcsp** [rook/rook#1716]
**Bug Report**

Built+installed master Rook on an existing baremetal cluster, checked the configmap output from the new drive detection code (https://github.com/rook/rook/pull/1637).

The resulting output has "empty: true" for all the hard drives in the system, including two drives already used by a baremetal Ceph cluster, and the OS drive.

Seems like the code is just reporting drives as empty if they have no filesystem on them, even if they have other partitions on them.

Here's the output for my OS drive:

```
{
  "devLinks": "/dev/disk/by-path/pci-0000:00:11.0-ata-1.0
/dev/disk/by-id/ata-VB0250EAVER_Z3TLVHEJ
/dev/disk/by-id/wwn-0x5000c50063eccddb",
  "rotational": true,
  "vendor": "",
  "uuid": "",
  "parent": "",
  "hasChildren": false,
  "wwn": "0x5000c50063eccddb",
  "wwnVendorExtension": "0x5000c50063eccddb",
  "name": "sda",
  "readOnly": false,
  "filesystem": "",
  "serial": "VB0250EAVER_Z3TLVHEJ",
  "Partitions": [
    {
      "Filesystem": "xfs",
      "Label": "",
      "Name": "sda1",
      "Size": 524288000
    },
    {
      "Filesystem": "LVM2_member",
      "Label": "",
      "Name": "sda2",
      "Size": 249533825024
    }
  ],
  "type": "disk",
  "model": "VB0250EAVER",
  "empty": true,
  "size": 250059350016
}
```

**Comment by rootfs** [comment]
cc @travisn

**Comment by jcsp** [comment]
@rootfs I think this got improved somewhat in the "pod per OSD" PR, how robust would you say it is now?

**Comment by sebastian-philipp** [comment]
This should be fixed with the upcoming c-v based inventory, right @travisn ?

**Comment by travisn** [comment]
The inventory is still based on rook's inventory so this behavior likely hasn't changed. Yes, we need to move in the direction of c-v inventory.
