### ISSUE TITLE
Helm is unable to install rook-alpha/rook -- fails to parse template version string.

### ISSUE THREAD

**Issue by ashayh** [rook/rook#1717]
**Bug Report**

What happened:

_Tried to install rook-operator from alpha repo._

What you expected to happen:

_Helm should install rook-alpha operator._

How to reproduce it (minimal and precise):
```
helm install --namespace rook-system rook-alpha/rook
Error: render error in "rook/templates/wait-on-resources-job.yaml": template: rook/templates/wait-on-resources-job.yaml:26:100: executing "rook/templates/wait-on-resources-job.yaml" at <semverCompare ">=1.7...>: error calling semver
Compare: Invalid Semantic Version
```
**Environment**:

* Cloud provider or hardware configuration:
Google
```
helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

* Rook version (use `rook version` inside of a Rook Pod):
_NA -- Ceph not installed_

* Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
_GKE_
* Ceph status (use `ceph health` in the [Rook toolbox]
(https://Rook.io/docs/Rook/master/toolbox.html)):
_NA -- Ceph not installed_

**Comment by galexrt** [comment]
@ashayh Could you try checking out the rook repository on branch `release-v0.7` and directly using the helm chart if the error persists.

@TimJones meant on Slack that it could possibly that an old Helm manifest was used.
