### ISSUE TITLE
cli: revisit whether block mount should format the volume

### ISSUE THREAD

**Issue by bassam** [rook/rook#172]
its atypical for a single CLI command to format the volume, nor are we going to support all the different mkfs people would like to do. I recommend we make formatting a separate step, or at least consider a `--noformat` option or a `--format` option.

**Comment by jbw976** [comment]
A `rook` user has hit this in #429.  There may be 2 issues here, one for always formatting in `block mount` and that unmapping may be destructive.

**Comment by DanKerns** [comment]
I just ran into this.  My filesystem got wiped when I did `rook mount` a second time on my image.

I don't think we should auto mkfs in any scenario including the first time.

**Comment by DanKerns** [comment]
Dup or #429
