### ISSUE TITLE
Add taint configuration to the rook-discover DaemonSet

### ISSUE THREAD

**Issue by emedina** [rook/rook#1732]
Is this a bug report or feature request?
Feature Request

**Feature Request**
Currently, when setting the `tolerance` for the `rook-operator` through the use of the env variable `AGENT_TOLERATION`, the DaemonSet `rook-agent` gets the toleration, but not the `rook-discover`.

What should the feature do:
Similar to this for OSDs:
https://github.com/rook/rook/blob/7230ad71d0b420b699a4967761d1e209c9582b53/pkg/apis/rook.io/v1alpha1/placement.go#L22-L40

What would be solved through this feature:
Tolerations to tainted nodes

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
* Kernel (e.g. `uname -a`): Linux med-k8s-1101-node1 4.16.8-1.el7.elrepo.x86_64 #1 SMP Wed May 9 12:59:19 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`): 0.7.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On-premise (VMs)
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): HEALTH_WARN too few PGs per OSD (14 < min 30)

**Comment by galexrt** [comment]
@emedina Can you try using the `DISCOVER_TOLERATION` and `DISCOVER_TOLERATION_KEY` variables on the operator? You may need to delete the `rook-discover` DaemonSet before updating the Rook operator env vars.

I have created a PR to document and add the env vars to the helm chart and the Rook `operator.yaml`.

**Comment by emedina** [comment]
@galexrt It works now.
