### ISSUE TITLE
ceph-authtool command fails in operator after install on baremetal rktnetes machine

### ISSUE THREAD

**Issue by t3hmrman** [rook/rook#1739]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:

When starting `rook` the `rook-agent` starts, but `rook-operator` ends up error-looping (so no `mon`s or `osd` pods are created).

Here's what the logs say:

```
2018-05-24 20:07:13.401024 I | op-mon: start running mons
2018-05-24 20:07:13.402051 I | exec: Running command: ceph-authtool --create-keyring /var/lib/rook/rook/mon.keyring --gen-key -n mon. --cap mon 'allow *'
2018-05-24 20:07:13.406401 E | op-cluster: failed to create cluster in namespace rook. failed to start the mons. failed to initialize ceph cluster info. failed to get cluster info. failed to create mon secrets. failed to gen secret. Failed to complete gen secret: signal: bad system call (core dumped)
```

It looks like the failure was during the running of `ceph-authtool` but it's not really clear *why* it failed. At first I was getting a warning about not running as PID 1, so I set the `TINI_SUBREAPER` env variable and the warning went away. It looks like the problem is deeper than that.

What you expected to happen:

The `rook-operator` to spawn all necessary pods.

How to reproduce it (minimal and precise):

0. Set up a cluster with `rkt`
1. Create `rook` resources (namespace, CRDs, deployment, etc)

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.3.1
VERSION_ID=1745.3.1
BUILD_ID=2018-05-23-0922
PRETTY_NAME="Container Linux by CoreOS 1745.3.1 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
* Kernel (e.g. `uname -a`): `Linux localhost 4.14.42-coreos #1 SMP Wed May 23 08:32:56 UTC 2018 x86_64`
* Cloud provider or hardware configuration: Baremetal
* Rook version (use `rook version` inside of a Rook Pod): v`0.7.1`
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Baremetal

* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

N/A, cluster isn't up

**Comment by t3hmrman** [comment]
I do want to note that the exact same configuration I have worked on the same exact machine when using `containerd` -- I do think it has something to do with `rkt` probably intersecting with the fact that `--cap mon 'allow *'` is being used...

**Comment by travisn** [comment]
@t3hmrman If you run the ceph-authtool command in the operator pod directly, do you get the same error with the core dump?
```
ceph-authtool --create-keyring /var/lib/rook/rook/mon.keyring --gen-key -n mon. --cap mon 'allow *'
```

**Comment by galexrt** [comment]
@t3hmrman `--cap mon 'allow *'` is a flag of the `ceph-authtool` not for the container or something.
The flag is for the `ceph-authtool` command.
The flags in this case create a "role" which has the capability to access everything of the mons (`mon allow *`) in Ceph context. This Ceph "role" is used for the mons to be able to access each other.

The actual error message (which could be caused by `ceph-authool`) is:
```
signal: bad system call (core dumped)
```

Could you check if there is a core dump on the node the rook-operator Pod runs on (command: `coredumpctl`).

**Comment by t3hmrman** [comment]
Thanks for the feedback @travisn and @galexrt -- my next step will be to increase the logging on the operator and see if I can get more output (and try and run it from a shell inside the pod). @galexrt thanks for clarifying on the meaning of `--cap`, my hunch was that it was a kernel-related option and maybe that's why the system call was core dumping. 

I will find out what's really going on by using `coredumpctl`, and try running the command directly, and report back here

**Comment by t3hmrman** [comment]
Hey I figured it out -- I noticed the `PodSecurityPolicy` in the helm chart and wondered if now (or always??) Rook required the operator to be run as a privileged pod. I could have sworn it didn't before, but for my setup that's what fixes it. 

Explains the bad system calls -- the system calls allowed by `rkt` versus `containerd` might be different, but in the end adding the `securityContext: privileged: true` to the operator deployment fixed it.

**Comment by t3hmrman** [comment]
I think I've narrowed it down a little more... Looking at the error:

```
Failed to complete gen secret: signal: bad system call (core dumped)
```

If I look [at the code that's running gen secret](https://github.com/rook/rook/blob/cd2b69915958e7453b3fc5031f59179058163dcd/pkg/operator/ceph/cluster/mon/util.go#L277), I assume it's trying to setuid to root, and that's why it's having a hard time -- I think this behavior is `rkt` specific.

**Comment by t3hmrman** [comment]
re-closing, this is an issue with `rkt`: https://github.com/rkt/rkt/issues/3823 and https://github.com/rkt/rkt/issues/3368 are the relevant issues there
