### ISSUE TITLE
Ensure upgrade guide works for upgrade to v0.8

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1749]
There have been many architectural changes in the v0.8 milestone that need to be covered in the upgrade user guide:  https://github.com/rook/rook/blob/master/Documentation/upgrade.md

The migration to support multiple storage types/providers has been included and tested, but there are some other items that will need to be addressed:
* `/run/udev` is now a required mount for the OSD pods that are using devices: #1738
* OSD pods will run 1 per device instead of 1 per node: #1656

We need to setup an existing v0.7 cluster that is using a variety of devices and directories and make sure the upgrade user guide has all the steps necessary to keep the cluster working after upgrading to v0.8.

**Comment by galexrt** [comment]
To note here: @travisn @rootfs and I are looking into the upgrade path for OSD Pods.

**Comment by travisn** [comment]
upgrading from 0.7.1 with both devices and directories worked for me, following the detailed instructions [here](https://github.com/rook/rook/blob/master/Documentation/upgrade.md).

**Comment by jbw976** [comment]
Upgrade also worked for me as well, @travisn and I have both verified and I'll close this issue.
