### ISSUE TITLE
Bug: Bluestore storage destroyed if using block storage with file system and fs being mounted

### ISSUE THREAD

**Issue by jomeier** [rook/rook#1755]
Hi,

we had a strange effect in the last week. Our ceph cluster suddenly became unavailable. 

All OSDs were in autoout state and down.

ceph-bluestore-tool fsck showed strange errors (I posted everything on the rook slack channel).

We found out that we had formatted the hard disk we used for bluestore with ext4 and mounted it to a directory before the installation of rook.

Our assumption is now, that after a restart of the hosts the linux file system check saw the ext4 fs and tried to "repair" it leading to a destruction of the bluestore data structures on the hard disk.

Is this scenario possible? If yes, the documentation should warn about mounting a block storage hard disk before we install rook.

* Bug Report

**Environment**:
* OS CentOS7
* Kernel 3.10.0-693.e17.x86_64
* Rook version (use `rook version` inside of a Rook Pod): v0.7.0-116.g82bd258
* Kubernetes version (use `kubectl version`): v1.10.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): ok

**Comment by jomeier** [comment]
This ticket can be closed. It really seems to be a fault of our own. See description above.

**Comment by jbw976** [comment]
Thank you for reporting your findings @jomeier
