### ISSUE TITLE
Unable to create volume (executable file not found in $PATH)

### ISSUE THREAD

**Issue by lyptt** [rook/rook#1758]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
I installed RabbitMQ which creates a volume and a claim. The creation process fails behind the scenes, with the following logs:

```
2018-06-01 14:54:22.271283 I | flexdriver: calling agent to attach volume replicapool/pvc-9db15eb5-65ab-11e8-9fc4-de1a100cd00f
2018-06-01 14:54:22.291544 I | ceph-volumeattacher: volume replicapool/pvc-9db15eb5-65ab-11e8-9fc4-de1a100cd00f is already attached. The device path is /dev/rbd1
2018-06-01 14:54:23.002022 I | flexdriver: E0601 14:54:22.987892    8664 mount_linux.go:140] Mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-9db15eb5-65ab-11e8-9fc4-de1a100cd00f --scope -- mount -o rw,defaults /dev/rbd1 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-9db15eb5-65ab-11e8-9fc4-de1a100cd00f
Output: Running scope as unit run-8677.scope.
mount: wrong fs type, bad option, bad superblock on /dev/rbd1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

E0601 14:54:23.000799    8664 mount_linux.go:411] format of disk "/dev/rbd1" failed: type:("ext4") target:("/var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-9db15eb5-65ab-11e8-9fc4-de1a100cd00f") options:(["rw" "defaults"])error:(executable file not found in $PATH)
2018-06-01 14:54:23.002978 E | flexdriver: mount volume replicapool/pvc-9db15eb5-65ab-11e8-9fc4-de1a100cd00f failed: failed to mount volume /dev/rbd1 [] to /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-9db15eb5-65ab-11e8-9fc4-de1a100cd00f, error executable file not found in $PATH
```

What you expected to happen:
Volume creation to work

How to reproduce it (minimal and precise):
No idea.

**Environment**:
* OS (e.g. from /etc/os-release):
CentOS 7.3
* Kernel (e.g. `uname -a`):
4.4.127-mainline-rev1 #1 SMP Sun Apr 8 10:38:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
Scaleway (bare metal)
* Rook version (use `rook version` inside of a Rook Pod):
No idea how to get this
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean
", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean
", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Kubespray
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
Don't have Rook toolbox installed

I've tried installing ceph-utils on the host OS (not inside a container or k8s), but this had no effect even though I verified rbd was present on /usr/bin, so I assume this is something to do with what's actually running on k8s itself.

**Comment by galexrt** [comment]
@lyptt You can get the Rook version by `kubectl exec`ing into one of the Pods in the namespace where you created the Rook Cluster in.

**Comment by lyptt** [comment]
Hi @galexrt, I've torn down my cluster for now, but it should be on whatever the latest is. I initialised Rook using the Kubernetes files [here](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes), replacing a few details like the device, etc.

**Comment by lyptt** [comment]
I managed to figure it out during the process of moving to a storage folder rather than a block device. I was missing the `e4fsprogs` package in my CentOS image for some reason, which meant the mkfs tools didn't exist.

It would probably be helpful if more information was present in the error, however I understand if this isn't possible / too much work.

**Comment by travisn** [comment]
@lyptt Great to hear you found the issue. At the minimum I will reopen this issue so we can document it in our troubleshooting steps.

**Comment by jbw976** [comment]
@lyptt so are we saying that it is required to have the `e4fsprogs` package on the host machine? i thought the mounting tools were included in the container image that `rook-agent` uses and that would be sufficient.  Can you help me understand why the tools included in the `rook-agent` pod's image were not sufficient?  Thank you.

**Comment by lyptt** [comment]
@jbw976 I assume that it's not using anything on the pod image to perform the formatting step. I verified this behaviour myself, and this is definitely the case. Unfortunaetly I don't know the inner workings of rook-agent, so I can't really help you further.

**Comment by andrewrynhard** [comment]
@galexrt Any insight here?

> i thought the mounting tools were included in the container image that rook-agent uses and that would be sufficient.

I am running into the same issue, and I also thought that the agent would have everything needed to handle any filesystem type.

**Comment by galexrt** [comment]
@andrewrynhard The formatting is done by kubelet AFAIK, not by the agent.
As @lyptt wrote in his case, the `e4fsprogs` were missing on his node.

**Comment by andrewrynhard** [comment]
@galexrt Thanks!
