### ISSUE TITLE
Ceph MGR not reporting metrics when osds are going down

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1759]
Is this a bug report or feature request?
* Bug Report

I have opened an issue at the Ceph bug tracker: http://tracker.ceph.com/issues/24379

**Bug Report**

What happened:
The Ceph MGR does not report Prometheus metrics when one or more OSDs are down.

What you expected to happen:
The Ceph MGR to continue reporting metrics no matter the OSD(s) status.

How to reproduce it (minimal and precise):
1. Stop Rook Ceph OSD Pods to cause OSDs going down (also block the restart of the OSDs that they are "longer" down and not just restarting in a few seconds).
2. Look at Prometheus metrics (e.g. Grafana dashboard, Prometheus console)

**Environment**:
* OS: `Container Linux by CoreOS 1745.4.0 (Rhyolite)`
* Kernel: `4.14.42-coreos`
* Cloud Provider: Bare-Metal, Dual Xeon x10 Cores, 96 GB memory,
* Rook Version: `v0.7.1`
* Kubernetes Version: `1.10.3`
* K8s Cluster Type: Bare-Metal "the-hard-way"
* Ceph Status: by now `HEALTH_OK`, during error `HEALTH_WARN`

/cc @christianhuening

**Comment by christianhuening** [comment]
Thanks for opening the issue @galexrt !
Here's the environment:
OS: Container Linux by CoreOS 1745.4.0 (Rhyolite)   
Kernel: 4.14.42-coreos   
Cloud Provider: Bare-Metal, Dual Xeon x10 Cores, 96 GB memory,    
Rook Version: 0.7.1
Kubernetes Version: 1.10.3
K8s Cluster Type: Bare-Metal "the-hard-way"
Ceph Status: by now HEALTH_OK, during error HEALTH_WARN
