### ISSUE TITLE
Ceph OSDs marked down, OSD devices being skipped on OSD pod startup

### ISSUE THREAD

**Issue by tcsullens** [rook/rook#1761]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
Ceph cluster health degraded due to OSDs showing down status.
This started occurring sometime after an initial successful setup of rook / ceph and provisioning of k8s PV resources.
Restarting OSD pods had no effect, but checking their logs show that they are skipping the devices that are supposed to be used for the OSDs (check the additional section).

How to reproduce it (minimal and precise):
Not entirely sure.

**Environment**:
* OS (e.g. from /etc/os-release):
Ubuntu 16.04.4

* Kernel (e.g. `uname -a`):
4.4.0-87-generic

* Cloud provider or hardware configuration:
On-prem, k8s nodes are virtual machines

* Rook version (use `rook version` inside of a Rook Pod):
root@rook-ceph-osd-wptdq:/# rook version
 rook: v0.7.0-134.g9b5c092

* Kubernetes version (use `kubectl version`):
1.9.5

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Rancher

* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
```
root@rook-tools:/# ceph -s
  cluster:
    id:     d7750504-0ec1-455a-9a49-f7a24cf81495
    health: HEALTH_WARN
            3 osds down
            2 hosts (4 osds) down
            Reduced data availability: 100 pgs inactive
            too few PGs per OSD (25 < min 30)

  services:
    mon: 3 daemons, quorum rook-ceph-mon4,rook-ceph-mon6,rook-ceph-mon5
    mgr: rook-ceph-mgr0(active)
    osd: 6 osds: 1 up, 4 in

  data:
    pools:   1 pools, 100 pgs
    objects: 0 objects, 0 bytes
    usage:   0 kB used, 0 kB / 0 kB avail
    pgs:     100.000% pgs unknown
             100 unknown

root@rook-tools:/#
```

* Additional:
OSD pods are showing that they are skipping the initialization/startup of the devices to be used (/dev/vd[b,c]). Initially these were clean, un-partitioned disks before the Ceph cluster setup.
```
2018-06-01 14:55:18.363113 I | exec: Running command: lsblk /dev/vdb --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2018-06-01 14:55:18.365319 I | exec: Running command: udevadm info --query=property /dev/vdb1
2018-06-01 14:55:18.367324 I | exec: Running command: udevadm info --query=property /dev/vdb1
2018-06-01 14:55:18.369345 I | exec: Running command: udevadm info --query=property /dev/vdb
2018-06-01 14:55:18.371282 I | cephosd: skipping device vdb that is in use (not by rook). fs: , ownPartitions: false
2018-06-01 14:55:18.371306 I | exec: Running command: lsblk /dev/vdc --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2018-06-01 14:55:18.372834 I | exec: Running command: udevadm info --query=property /dev/vdc1
2018-06-01 14:55:18.374247 I | exec: Running command: udevadm info --query=property /dev/vdc1
2018-06-01 14:55:18.375764 I | exec: Running command: udevadm info --query=property /dev/vdc
2018-06-01 14:55:18.377075 I | cephosd: skipping device vdc that is in use (not by rook). fs: , ownPartitions: false
```

I can provide additional information / comments as needed.

**Comment by travisn** [comment]
@tcsullens since `ownPartitions` is false, can you see what the `ID_PART_ENTRY_NAME` property is on each of the partitions? For example:
```
udevadm info --query=property /dev/vdb1 | grep ID_PART_ENTRY_NAME
```

`ownPartitions` should only be false if the partition name does not have the prefix `ROOK-OSD` as seen [here](https://github.com/rook/rook/blob/master/pkg/util/sys/device.go#L345).

**Comment by tcsullens** [comment]
Yea so the interesting thing with that is running it from the k8s nodes I see it:
```
prod-kubernetes-03.npr.org:
    ID_PART_ENTRY_NAME=ROOK-OSD2-BLOCK
prod-kubernetes-01.npr.org:
    ID_PART_ENTRY_NAME=ROOK-OSD0-BLOCK
prod-kubernetes-02.npr.org:
    ID_PART_ENTRY_NAME=ROOK-OSD1-BLOCK
```
However running it from _inside_ an OSD pod (specifically running on node 02):
```
root@rook-ceph-osd-wptdq:/# udevadm info --query=property /dev/vdb1
DEVNAME=/dev/vdb1
DEVPATH=/devices/pci0000:00/0000:00:0b.0/virtio2/block/vdb/vdb1
DEVTYPE=partition
MAJOR=253
MINOR=17
SUBSYSTEM=block
root@rook-ceph-osd-wptdq:/#
``` 
I went through all of the partitions and it's the same behavior.

**Comment by travisn** [comment]
ah, actually this should have been fixed a few days ago by #1746. Could you try a newer build?

**Comment by tcsullens** [comment]
I definitely can on Monday... though I'm not clear on how I should update my existing deployment... any documentation you could point me to there (didn't look like the upgrade docs were appropriate for this)?

**Comment by travisn** [comment]
hmm, upgrading master to master builds is difficult when so much is still changing. With #1743 coming in since the build you're running on, your best bet will be to follow the upgrade doc even if some steps are not applicable (ie. removing the legacy api service).

**Comment by galexrt** [comment]
@travisn @tcsullens It should be enough when the `master` tag is used to pull the image on all nodes and restart all Pods one by one, so they use the updated image.

**Comment by travisn** [comment]
@galexrt yes that might normally be possible, but #1743 complicated this by renaming the image

**Comment by galexrt** [comment]
@travisn Oh right, I thought he was already on the `rook/ceph` image version. Still editing the Deployments, ReplicaSets to use the `ceph` could do the trick ;)

**Comment by tcsullens** [comment]
OK I ran through the upgrade process and am now running version
`
 rook: v0.7.0-162.gd13032a
`
from the rook/ceph:master image, however I'm seeing the same behavior with the OSD pods: the devices are being skipped and the volume mount for `/run/udev/` is not in the OSD daemon set description.

I edited the deamon set directly to add the necessary volume mount.. I am thinking that in order for this to have worked I would have needed to re-create the OSD replica set instead of just updating the image (after updating the operator), but I am unsure of the impact of deleting and re-creating the OSD replica set.

I still have work to get the ceph cluster healthy but the problem outlined here is resolved for me... I think we can close this unless someone disagrees.

**Comment by jbw976** [comment]
You are definitely correct @tcsullens, the new volume mount for `/run/udev` needs to be added during the upgrade process from `v0.7`.  I've tried to capture this in #1749, so we will not exit the `v0.8` milestone until upgrade is fully vetted. Thanks for your help.
