### ISSUE TITLE
[BUG] rook/ceph-toolbox:master locale

### ISSUE THREAD

**Issue by soakes** [rook/rook#1765]
While debugging some issues, I found when executing `$ kubectl -n rook-ceph exec -it rook-ceph-tools bash` generated a load of locale error messages.

```
bash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory
```

I hate error messages of any kind so decided to squash them.  The solution is simple but you might want to add the changes in the docker image.

Run the following:
```
$ kubectl -n rook-ceph exec -it rook-ceph-tools bash
$ yum reinstall glibc-common
$ localedef -i en_US -f UTF-8 en_US.UTF-8
```

This will regenerate the locales.  If you do not reinstall `glibc-common`, `localedef` has some missing files which can be seen with strace and this stops it from regenerating the locales.

Hope this helps anyone with the same issues.

**Comment by jbw976** [comment]
Thanks for reporting this @soakes.  Do you know what steps would need to be done at image build time to prevent this?

Is it the bash shell itself that is trying to call `setlocale` which generates the error messages? i'm trying to understand better why this is happening in the first place.

**Comment by soakes** [comment]
Hi @jbw976 

You're very welcome.  

Yes its bash shell itself trying to call setlocale which the basic/common one is missing hence needed to be regenerated.

Without checking the dockerfile, the locale file(s) are missing which may be due to size/shrinking image but consuming most ppl would enter this image to do tests/tweaks etc to ceph, it would IMO be better if they were present.  

Will take a look at the dockerfile at the weekend when I should have more time, should be a very simple fix.

**Comment by checkaayush** [comment]
Seems like this is it: https://github.com/rook/rook/blob/master/images/ceph-toolbox/Dockerfile.base#L42

**Comment by travisn** [comment]
Note that this issue exists in both the `rook/ceph` and `rook/ceph-toolbox` images. I found that by adding these two lines to their dockerfiles solved this issue:
```
    yum --assumeyes reinstall glibc-common && \
    localedef -i en_US -f UTF-8 en_US.UTF-8 && \
```
Note that this adds about 12MB to the uncompressed image size. I wonder if there are any other side effects to glibc in the image that could affect ceph.

**Comment by dkerwin** [comment]
I can confirm that the localization issue still exists in the v.0.8.3 rook-tools image

**Comment by frank-carnovale** [comment]
as a short-term hack, this gets rid of the annoying mis-config; and basic ceph commands seem unaffected:
cd /etc; mv locale.conf hide-locale.conf

**Comment by travisn** [comment]
Thanks for the suggestion, this has been annoying for a long time...
