### ISSUE TITLE
latency related metrics are missing

### ISSUE THREAD

**Issue by JohnnyQQQQ** [rook/rook#1767]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:

I setup the monitoring using https://github.com/rook/rook/tree/v0.7.1/cluster/examples/kubernetes/monitoring. For some reason some metrics are missing. I don't get any latency related metrics from the `/metrics` endpoint that is scraped: `ceph_osd_apply_latency_ms`, `ceph_osd_commit_latency_ms` and `ceph_monitor_latency_seconds` are missing.

What you expected to happen:

I would expect that these important metrics are exposed. I could find some references in the code related to those metrics so I think this is a bug or a missconfiguration.

https://github.com/rook/rook/blob/f192defee101b918a5cb3987cca954a6419a29be/pkg/daemon/ceph/client/osd.go#L54

How to reproduce it (minimal and precise):

Setup rook using https://github.com/rook/rook/tree/v0.7.1/cluster/examples/kubernetes and https://github.com/rook/rook/tree/v0.7.1/cluster/examples/kubernetes/monitoring

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
`Hetzner Cloud`
* Rook version (use `rook version` inside of a Rook Pod):
`` rook: v0.7.0``
* Kubernetes version (use `kubectl version`):
```go
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
`Bare Metal`
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):
```
  cluster:
    id:     2bd6976b-a005-491e-938a-25b9b638a4da
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon0,rook-ceph-mon2,rook-ceph-mon1
    mgr: rook-ceph-mgr0(active)
    mds: nats-fs-1/1/1 up  {0=mxgs8s=up:active}, 1 up:standby-replay
    osd: 4 osds: 4 up, 4 in
 
  data:
    pools:   3 pools, 300 pgs
    objects: 944 objects, 2048 MB
    usage:   10297 MB used, 895 GB / 905 GB avail
    pgs:     300 active+clean
 
  io:
    client:   852 B/s rd, 83874 B/s wr, 1 op/s rd, 35 op/s wr
```

**Comment by JohnnyQQQQ** [comment]
Here are the metrics from the `mgr` pod 
[ceph_mgr_metics.txt](https://github.com/rook/rook/files/2068121/ceph_mgr_metics.txt)

**Comment by jbw976** [comment]
if these metrics are coming directly from ceph-mgr prometheus module, is there anything in the rook codebase that can be done to fix this? I believe that this would need a change in the ceph-mgr code, but please someone correct me if I am wrong.

**Comment by JohnnyQQQQ** [comment]
I just checked if the command works that should generate this data

```
k exec -it -n rook rook-tools -- ceph osd perf
osd commit_latency(ms) apply_latency(ms) 
  3                  2                 2 
  2                  1                 1 
  1                  1                 1 
  0                  2                 2 
```

seems to work for me when doing it manually

**Comment by JohnnyQQQQ** [comment]
I dived a little deeper, those metrics where implemented this January. The current used version is 12.2.2 from November.

I close it for now.
