### ISSUE TITLE
rook should not hang when ceph commands don't respond

### ISSUE THREAD

**Issue by jbw976** [rook/rook#179]
Some requests from rook to the ceph layer can hang (opening an IO context) if a lot of placement groups are in unhealthy states.

An example is https://github.com/rook/rook/issues/177

The UX should not hang, perhaps a timeout/watchdog should be used for requests to the ceph layer.

**Comment by jbw976** [comment]
This should probably be handled with a timeout at the mon_command layer, so layers that build on top of that (API, CLI) do not also have to implement some timeout/watchdog logic

**Comment by travisn** [comment]
with pvcs and the deprecation of api/cli, this seems obsolete, or else we should reopen with a scenario and repro relevant to the new world
