### ISSUE TITLE
Adopt usage of a Golang linter in code reviews

### ISSUE THREAD

**Issue by tonya11en** [rook/rook#1793]
Our stance on Rook's Golang style is as follows:
> Rook projects are written in golang and follows the style guidelines dictated by the go fmt as well as go vet tools.

We should be using Golint for this. Gofmt simply reformats Go code and `go vet` just reports suspicious constructs. Neither of these can be relied on for finding style issues. To adopt a common coding style (comment structures, error handling, variable naming schemes, etc) we should include Golint repots as part of the code review process.

https://github.com/golang/lint

**Comment by travisn** [comment]
Is this the same as #495? Note that `make lint` will also run it. There are only 640 issues to fix right now. :)

**Comment by tonya11en** [comment]
@travisn looks like the right thing, but I was hoping for something to stop the bleeding as the codebase grows.  It would be nice to have a way to determine new linter errors introduced with a PR.

**Comment by travisn** [comment]
This is enabled with #1543
