### ISSUE TITLE
Erasure coding pools should set min_size to the number of data chunks

### ISSUE THREAD

**Issue by mbrownie1** [rook/rook#1795]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:  By default, the min_size is set to "3" when building a 3 node OSD cluster using Rook.IO.  This is problematic since the cluster can no longer process I/O if a single OSD is lost.

root@rook-ceph-tools:/# ceph osd pool get my-store.rgw.buckets.data min_size
min_size: 3

What you expected to happen:  Expected "min_size=2" or the option to change that setting in object.yaml

How to reproduce it (minimal and precise):

Example cluster configuration that produces this issue...

**kubectl get pods -n=rook-ceph**
NAME                                     READY     STATUS    RESTARTS   AGE
rook-ceph-mgr0-d5f69ccc4-b4ksp           1/1       Running   0          1m
rook-ceph-mon0-q4wzg                     1/1       Running   0          2m
rook-ceph-mon1-xbzdm                     1/1       Running   0          2m
rook-ceph-mon2-fdhbm                     1/1       Running   0          2m
rook-ceph-osd-qvq4p                      1/1       Running   0          1m
rook-ceph-osd-x49kr                      1/1       Running   0          1m
rook-ceph-osd-z77nk                      1/1       Running   0          1m
rook-ceph-rgw-my-store-6746f9885-zpnjb   1/1       Running   0          3s
rook-ceph-tools                          1/1       Running   0          25s

**rados df**
POOL_NAME                  USED OBJECTS CLONES COPIES MISSING_ON_PRIMARY UNFOUND DEGRADED RD_OPS RD    WR_OPS WR
.rgw.root                  3647      16      0     32                  0       0        0    144 97280     32 23552
my-store.rgw.buckets.data     0       0      0      0                  0       0        0      0     0      0     0
my-store.rgw.buckets.index    0       0      0      0                  0       0        0      0     0      0     0
my-store.rgw.control          0       8      0     16                  0       0        0      0     0      0     0
my-store.rgw.log             50     177      0    354                  0       0        0    526  350k    353  1024
my-store.rgw.meta             0       0      0      0                  0       0        0      0     0      0     0

**ceph osd pool get my-store.rgw.buckets.data all**
size: 3
min_size: 3
crash_replay_interval: 0
pg_num: 100
pgp_num: 100
crush_rule: my-store.rgw.buckets.data
hashpspool: true
nodelete: false
nopgchange: false
nosizechange: false
write_fadvise_dontneed: false
noscrub: false
nodeep-scrub: false
use_gmt_hitset: 1
auid: 0
erasure_code_profile: my-store_ecprofile
fast_read: 0

**Environment**:
* OS (e.g. from /etc/os-release):  Hosts are running CentOS7
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:  internal cloud - running on commodity Dell blades - Intel
* Rook version (use `rook version` inside of a Rook Pod):  rook: v0.7.0-160.g3060813
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.13", GitCommit:"14ea65f53cdae4a5657cf38cfc8d7349b75b5512", GitTreeState:"clean", BuildDate:"2017-11-22T20:29:21Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  kubeadm

* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

health: HEALTH_WARN
            60/1486 objects misplaced (4.038%)
            Reduced data availability: 76 pgs inactive, 76 pgs incomplete, 27 pgs stale
            Degraded data redundancy: 300/1486 objects degraded (20.188%), 138 pgs degraded, 500 pgs undersized
            1 slow requests are blocked > 32 sec

  services:
    mon: 3 daemons, quorum rook-ceph-mon2,rook-ceph-mon0,rook-ceph-mon1
    mgr: rook-ceph-mgr0(active)
    osd: 3 osds: 2 up, 2 in; 24 remapped pgs
    rgw: 1 daemon active

**Comment by galexrt** [comment]
The problem is more in the point that the `min_size` is wrongly set as far as I understand from the Slack conversation.
At least for replicated pools it is `1` allowing reads (and writes) with all except one lost copies of data, which I think should also be set for erasure coded pools.

/cc @travisn Is that right?

**Comment by travisn** [comment]
@galexrt Right, this is specific to erasure coding pools that should set min_size to the number of data chunks.

**Comment by grebois** [comment]
@galexrt you can specify this on your replicapool:

```
apiVersion: ceph.rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool
  namespace: rook-ceph-system
spec:
  replicated:
    size: 3
    min_size: 2
```

**Comment by galexrt** [comment]
@grebois There is no `min_size` option on the Pool CRD, see https://rook.io/docs/rook/master/ceph-pool-crd.html#spec.

This issue is about setting the `min_size` correctly on erasure coded pools. Replicated pools are not affected as they always get `min_size` set to `1` in the "background" and as written there is no option for that on the Pool CRD (yet).
I have to say I don't see a reason to add `min_size` to the Pool CRC/Spec as at least I haven't heard of a case where, except for erasure coded pools, a `min_size` bigger than `1` should be/was used.

**Comment by galexrt** [comment]
@travisn I think we should get this in 0.8 or at least in a patch release as this blocks HA for erasure coded pools.

**Comment by jbw976** [comment]
I have put this onto the 0.8 project board (https://github.com/rook/rook/projects/9#card-11403238) to opportunistically pick up perhaps in a minor release, but I would not hold/block the 0.8.0 release for this issue.
