### ISSUE TITLE
Restructure docs navigation to support multiple providers better

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1802]
The documentation navigation on https://rook.io/docs/rook/master/ needs to be organized a little better now that Rook supports multiple storage providers.

* Users that only care about 1 of the storage providers should be able to see only docs relevant to it
* Quickstart example should link to a quickstart for each provider, right now its entirely Ceph focused

**Comment by galexrt** [comment]
I could probably take a look when I'm also redoing the theme for the docs.
In the redo of the theme, I will especially look into having a better side navigation/side toc list.

**Comment by travisn** [comment]
still very much needed

**Comment by jbw976** [comment]
Dmitry brought this up in the community meeting today, this makes even more sense now with Nexenta being added in #2268

**Comment by yanniszark** [comment]
There is now a big mass of mds under `Documentation` which makes it very difficult for a user to navigate to the things he's interested in. 
I propose that we start with the most needed thing imo, giving each storage provider its own folder. 
```
* Documentation/
  * ceph/
  * minio/
  * cockroachdb/
  * cassandra/
  * nexenta/
```
Another subfolder could be `dev`, which will contain the documents about developing in rook.
@jbw976 @travisn @galexrt what do you think about doing these as a start ? Do you agree with using a separate folder for each storage provider ?

**Comment by travisn** [comment]
Agreed, would be good to break it out in this structure. I believe the generated docs will pick up docs from all subdirectories, so if we move these source docs around he generated docs should not change.

The bigger change that will be interesting is to restructure the generated docs. I'd love it if we had a dropdown that let you select which backend you're interested in. This way you could easily see only the backend you're using.

**Comment by galexrt** [comment]
I have created an example org to try it out https://github.com/rook-new-site-design.

In this the documentation must be placed in folders, sub-folders and so on as can be seen here: https://github.com/galexrt/rook/tree/hugo_doc.
The result of this with the redesign combined is looking like this when on the docs:
![screencapture-localhost-1313-2019-01-18-19_51_44](https://user-images.githubusercontent.com/3718398/51406903-bc335c80-1b5a-11e9-9c98-8586bd062b75.png)

The whole example/demo uses https://gohugo.io/ and the theme https://themes.gohugo.io/hugo-theme-techdoc/ for the documentation (currently also main page, but that is one thing I'm working on).

**Comment by jbw976** [comment]
very cool @galexrt! a few comments:
* I like how we have more levels of nesting/indentation.  how is that controlled, is front matter still needed, or is the structure automatically picked up from the folder structure in the source repo?
* Grouping by Storage providers makes sense.  I see a few of them that are plural when they shouldn't be, like Cockroachdbs and Minios.  Is that a bug?
* I think the titles of the smaller storage providers quickstart pages could be changed to "quick start" instead of repeating the storage provider name again.  e.g., CockroachDB top level and then first nested item could be "Quick start"

**Comment by galexrt** [comment]
@jbw976
1. In directories (with "empty" `_index.md`), see https://github.com/galexrt/rook/tree/hugo_doc/Documentation for the file/dir layout currently to be seen at https://rook-new-site-design.github.io/docs/master/.
2. Are you insulting my grammar skills? :stuck_out_tongue_winking_eye: No, I just named the first `_index.md` page I created (https://github.com/galexrt/rook/blob/hugo_doc/Documentation/edgefs/crd/_index.md look at it in raw to see what it contains) and as, e.g., CRDs page is "always" this page is "always" the same I just copy and pasted it (renaming it to `CRD(s)` could be a fix also :wink:).
3. I'm happy to see commits/changes done to the branch I'm working on (you should be able to edit when I have created the PR (though the full working PR will still take a bit)).
