### ISSUE TITLE
End to end integration test for Minio

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1804]
We need an end to end integration test for Minio to sanity/smoke test its basic functionality as part of continuous integration.  This test should be dependent on #1788 so that we ensure our test solution scales as more providers are added.

**Comment by jbw976** [comment]
This effort was started in #1866 and we should finish it.  Removing @tonya11en from this issue.

**Comment by krizhan** [comment]
Hey @jbw976 I can give this task a shot.

**Comment by jbw976** [comment]
That would be great @krizhan! I'll send you an invite to join the Rook organization so we can assign this issue to you :)

**Comment by jbw976** [comment]
@krizhan please let me know when you've accepted the invitation to join the Rook organization and I'll assign this issue to you, thanks!

**Comment by krizhan** [comment]
Just did and thanks! I'll have a look at everything over the long weekend.
