### ISSUE TITLE
CockroachDB will fail to install when there's no default StorageClass

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1807]
In environments with no default storageClass, the CockroachDB operator will fail to get the cluster up and running successfully.  This is because the StatefulSet that runs the instances uses a volumeClaimTemplate that uses the default storageClass (via a null storage class name field).  If there is no default storageClass then the PVs for the instances can not be bound and the pods cannot get running.  `kubectl describe pvc` shows the root cause:
```console
> kubectl -n rook-cockroachdb describe pvc datadir-rook-cockroachdb-0
Name:          datadir-rook-cockroachdb-0
Namespace:     rook-cockroachdb
StorageClass:
Status:        Pending
Volume:
Labels:        app=rook-cockroachdb
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type    Reason         Age                From                         Message
  ----    ------         ----               ----                         -------
  Normal  FailedBinding  6s (x43 over 10m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

One way to address this is to update our documentation to provide a section on how to check if there's a default storageClass and then create one if needed.  The integration tests do exactly this.  If there is no default storageClass in the integration test environment, the tests will dynamically install the hostPath provisioner from https://github.com/MaZderMind/hostpath-provisioner.  Code can be found in the tests at https://github.com/rook/rook/blob/master/tests/framework/installer/provisioners.go#L37.

The manual instructions for docs are basically:
```console
kubectl create -f https://raw.githubusercontent.com/MaZderMind/hostpath-provisioner/master/manifests/rbac.yaml
kubectl create -f https://raw.githubusercontent.com/MaZderMind/hostpath-provisioner/master/manifests/deployment.yaml
kubectl create -f https://raw.githubusercontent.com/MaZderMind/hostpath-provisioner/master/manifests/storageclass.yaml
```

Of course, the docs could also provide instructions for how to use Rook to deploy a Ceph cluster and then use the `rook-ceph-block` storageClass to provide the underlying block storage for the CockroachDB instances.

Another option would be to update the `cluster.cockroachdb.rook.io` CRD to allow a storageClass name or a PVC template or something that the operator will use when creating cockroachdb instances.

**Comment by hunter** [comment]
Is `hostpath-provisioner` recommended? [Local volumes](https://kubernetes.io/docs/concepts/storage/volumes/#local) is beta in 1.10 and should handle scheduling workloads better than hostPath.

**Comment by jbw976** [comment]
Agreed @hunter, local volumes would be an improved solution over the hostpath provisioner.  Maybe we can give instructions for that on k8s 1.10+ but also give instructions for hostpath provisioner for older versions of kubernetes.

**Comment by hunter** [comment]
Looks as though for older versions, we can use the [external-storage](https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume#version-compatibility) version. Less features but does give an easier migration path.
