### ISSUE TITLE
recent master builds have a dirty tag

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1808]
Starting with `v0.7.0-205.g357b7b8.dirty`, image tags for all containers that Rook builds are now marked as dirty, meaning that something is changing in the local clone during the build.  I cannot reproduce this locally, so we need to investigate on the Jenkins build machine.

This started happening after the cockroachdb operator was merged to master with this commit: https://github.com/rook/rook/commit/357b7b86e78a2d3c1fa6d227426615971f5b065c

Tags:
https://hub.docker.com/r/rook/ceph/tags/
https://hub.docker.com/r/rook/cockroachdb/tags/

**Comment by jbw976** [comment]
Since I do not have the SSH key to connect to the Jenkins machines, I tried to be clever and take an EBS snapshot of their disks then examine those by attaching them to a temporary micro instance.  Unfortunately, it looks like the path where the git repo is cloned and a build is performed (e.g., `/home/ubuntu/workspace/rook_rook_master-G4HNCZNZ2QMMOJ26BOE5XMCO6OW7CRWPLLQRL3H6IRM22IZR4NPA`) is only stored in some temp space and is not present in the EBS snapshot.
```
$ ls -al /home/ubuntu/workspace/ | grep master
drwxrwxr-x  2 ubuntu ubuntu  4096 Jun 20 04:21 rook_rook_master-G4HNCZNZ2QMMOJ26BOE5XMCO6OW7CRWPLLQRL3H6IRM22IZR4NPA@tmp

$ ls -al /home/ubuntu/workspace/rook_rook_master-G4HNCZNZ2QMMOJ26BOE5XMCO6OW7CRWPLLQRL3H6IRM22IZR4NPA@tmp
total 16
drwxrwxr-x  2 ubuntu ubuntu  4096 Jun 20 04:21 .
drwxrwxr-x 64 ubuntu ubuntu 12288 Jun 20 20:18 ..
```
I need to get access to the actual Jenkins machines.

**Comment by jbw976** [comment]
Using the groovy script console in the jenkins admin UI for the slave nodes, I was able to run `git status` and see that it's the vendoring that is changing during the builds.
```
"git -C /home/ubuntu/workspace/rook_rook_master-G4HNCZNZ2QMMOJ26BOE5XMCO6OW7CRWPLLQRL3H6IRM22IZR4NPA status".execute().text
Result: HEAD detached at 48b879e
Changes not staged for commit:
	modified:   Gopkg.lock
```

**Comment by jbw976** [comment]
As far as I can tell, the changes being made to `Gopkg.lock` during the `make vendor` step of the build are only whitespace related.  Each package list is getting each entry on its own line, e.g.,:
```
 [[projects]]
   name = "github.com/stretchr/testify"
-  packages = ["assert","require","suite"]
+  packages = [
+    "assert",
+    "require",
+    "suite"
+  ]
   revision = "69483b4bd14f5845b5a1e55bca19e954e827f1d0"
   version = "v1.1.4"
```
The dep version `v0.4.1` was [released back in January](https://github.com/golang/dep/releases/tag/v0.4.1), and Gopkg.toml and Gopkg.lock haven't changed in months:
https://github.com/rook/rook/commits/master/Gopkg.toml
https://github.com/rook/rook/commits/master/Gopkg.lock

I have no idea why `make vendor` would all of a sudden be making whitespace changes during the build, that's really weird.

**Comment by jbw976** [comment]
For future knowledge, the keypair name is `CR-AWS-DD` on the Cloud - Amazon EC2 section of the main configuration page, not the credentials management page.

**Comment by jbw976** [comment]
https://github.com/golang/dep/issues/1595 and https://github.com/pelletier/go-toml/pull/217 look related to this issue.

**Comment by AntonioMeireles** [comment]
FWIW this issue come back from the grave ... (cf. https://hub.docker.com/r/rook/ceph/tags/).

have a great weekend!

**Comment by jbw976** [comment]
You are right @AntonioMeireles, thank you very much for the heads up on that! I will look into this again 😣

**Comment by jbw976** [comment]
It is the `Gopkg.lock` file changing again, but I understand why this time with help from https://github.com/golang/dep/issues/1392#issuecomment-346305224.  Only the `inputs-digest` changed.  A diff of the `dep hash-inputs` output from the last clean build and then the minio PR being merged shows a new import of `k8s.io/api/apps/v1beta2` that was previously only a transitive dependency. That's why the `inputs-digest` changed, but no other packages/versions changed in the lock file. We should probably have a better long term solution for catching this type of thing earlier on before getting to master, but simply updating the `inputs-digest` right now should get us back to clean.

**Comment by bassam** [comment]
agree. we should catch these at a PR level, i.e. ensure the `make vendor` results in no changes before committing a PR.

**Comment by jbw976** [comment]
Tracking the longer term check in #1822
