### ISSUE TITLE
cockroachdb operator should have minimal RBAC access

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1813]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: Originally captured in #1389 and implemented in #1736 for Ceph.

What should the feature do: Similar to the Ceph operator in the PR above, the cockroachdb operator should get service accounts and roles that are scoped to just the namespaces that should have cockroachdb clusters deployed and managed (as opposed to across all namespaces).

What would be solved through this feature: Security will be improved by the permissions of the operator being more scoped to only certain namespaces.

This should cover the examples/samples as well as any helm charts implemented for #1810.

**Comment by travisn** [comment]
we have a pattern to follow here...

**Comment by ZYecho** [comment]
hey @jbw976, i'm trying to fix this issue, and I find the cockroachdb pod didn't need to talk to api-server, seems we can assign a empty servicecount to it to restrict it, not sure it's right, just ping to confirm, thanks. :)
