### ISSUE TITLE
make vendor should be checked for no changes in all PRs

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1822]
We've had a couple problems in master recently where the `Gopkg.lock` file changes during `make vendor` resulting in a dirty build.  This was tracked and fixed in #1808 but we need a better long term solution.  Every PR should have a check before being merged to master that all the imports/dependencies are up to date and `make vendor` results in no changes.

Latest analysis can be read in https://github.com/rook/rook/issues/1808#issuecomment-399698086

**Comment by MartinForReal** [comment]
How about execute following command to check if Gopkg.lock should be updated and if it is abort the ci build when ci flag is set?
```
dep ensure -no-vendor
```

**Comment by galexrt** [comment]
Assigned @bassam as he has opened a PR to close this issue.
