### ISSUE TITLE
Can't create new Pods using CephFS

### ISSUE THREAD

**Issue by sinqinc** [rook/rook#1828]
**Bug Report**

What happened:
I can't create new pods using Flex Volume CephFS. The node is completely hanging and need to be rebooted because the node begin to flap the Kubernetes Cluster. The Pod cannot be removed too.

 I can create POD using RBD only if using a new claim.

the host is mounting the volume.

> Name:                      tmp-6679b8d5d6-6s66p
> Namespace:                 sinq-production
> Node:                      coreos10.qcct.net/10.0.0.100
> Start Time:                Tue, 26 Jun 2018 02:40:30 +0000
> Labels:                    pod-template-hash=2235648182
>                            workload.user.cattle.io/workloadselector=deployment-sinq-production-tmp
> Annotations:               cni.projectcalico.org/podIP=10.42.2.121/32
>                            workload.cattle.io/state={"Y29yZW9zMTAucWNjdC5uZXQ=":"local:machine-wdd4d"}
> Status:                    Terminating (expires Tue, 26 Jun 2018 02:57:45 +0000)
> Termination Grace Period:  30s
> IP:
> Controlled By:             ReplicaSet/tmp-6679b8d5d6
> Containers:
>   tmp:
>     Container ID:
>     Image:          ubuntu:xenial
>     Image ID:
>     Port:           <none>
>     State:          Terminated
>       Exit Code:    0
>       Started:      Mon, 01 Jan 0001 00:00:00 +0000
>       Finished:     Mon, 01 Jan 0001 00:00:00 +0000
>     Ready:          False
>     Restart Count:  0
>     Environment:    <none>
>     Mounts:
>       /mnt/cephfs from vol1 (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-dfp4b (ro)
> Conditions:
>   Type           Status
>   Initialized    True
>   Ready          False
>   PodScheduled   True
> Volumes:
>   vol1:
>     Type:    FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
>     Driver:      Options:  %v
> 
>     FSType:     rook.io/rook
>     SecretRef:  ceph
>     ReadOnly:   &{}
> %!(EXTRA bool=false, map[string]string=map[clusterName:rook fsName:share])  default-token-dfp4b:
>     Type:        Secret (a volume populated by a Secret)
>     SecretName:  default-token-dfp4b
>     Optional:    false
> QoS Class:       BestEffort
> Node-Selectors:  <none>
> Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
>                  node.kubernetes.io/unreachable:NoExecute for 300s
> Events:
>   Type     Reason                 Age                From                        Message
>   ----     ------                 ----               ----                        -------
>   Normal   SuccessfulMountVolume  23m                kubelet, coreos10.qcct.net  MountVolume.SetUp succeeded for volume "default-token-dfp4b"
>   Normal   SuccessfulMountVolume  23m                kubelet, coreos10.qcct.net  MountVolume.SetUp succeeded for volume "vol1"
>   Normal   Pulled                 23m                kubelet, coreos10.qcct.net  Container image "ubuntu:xenial" already present on machine
>   Normal   Created                23m                kubelet, coreos10.qcct.net  Created container
>   Warning  Failed                 21m                kubelet, coreos10.qcct.net  Error: context deadline exceeded
>   Warning  FailedSync             8m (x39 over 19m)  kubelet, coreos10.qcct.net  error determining status: rpc error: code = DeadlineExceeded desc = context deadline exceeded
> 

What you expected to happen:

Pod get created successfully.

How to reproduce it (minimal and precise):
Just create a new deployment that use CephFS.

**Environment**:
* OS (e.g. from /etc/os-release): 
CoreOS 1745.7.0
* Kernel (e.g. `uname -a`): 
4.14.48-coreos-r2
* Cloud provider or hardware configuration: 
CloudSigma (KVM)
* Rook version (use `rook version` inside of a Rook Pod):
 rook: v0.7.1
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.9-rancher1", GitCommit:"68595e18f25e24125244e9966b1e5468a98c1cd4", GitTreeState:"clean", BuildDate:"2018-03-13T04:51:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
Rancher 2.0.2 (RKE)
* Ceph status (use `ceph health` in the [Rook toolbox]
(https://Rook.io/docs/Rook/master/toolbox.html)):
  cluster:
    id:     8157e138-3969-4fbb-bed3-6a74c77432c6
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum rook-ceph-mon3,rook-ceph-mon1,rook-ceph-mon4
    mgr: rook-ceph-mgr0(active)
    mds: share-1/1/1 up  {0=mps89t=up:active}, 1 up:standby-replay
    osd: 9 osds: 9 up, 9 in

  data:
    pools:   4 pools, 400 pgs
    objects: 1017k objects, 32156 MB
    usage:   249 GB used, 285 GB / 534 GB avail
    pgs:     400 active+clean

  io:
    client:   1775 kB/s rd, 1442 kB/s wr, 207 op/s rd, 92 op/s wr

**Comment by bjornryden** [comment]
Sorry if I'm suggesting the obvious, but did you set the correct flex volume path?
https://github.com/rook/rook/blob/master/Documentation/flexvolume.md

**Comment by sinqinc** [comment]
Yes i did, i have 13 other pods connected to the same FS. The problem begin after a cluster reboot. All current pod are recreated without problem.

**Comment by sinqinc** [comment]
I can mount it in the Rook Toolbox 

`root@rook-tools:/# rookctl filesystem mount --name share --path /tmp/registry
succeeded mounting shared filesystem share at '/tmp/registry'`

**Comment by sinqinc** [comment]
it seems related to the Flex volume indeed. but.. In Rancher if I do "Add a new Persistent Volume (claim)" and use a Rook Storage Class, the deployment is created successfully

**Comment by sinqinc** [comment]
The problem seems be related to the number of files on the volume. I removed a lot of files and it can now mount without problem.

**Comment by galexrt** [comment]
@sinqinc Have you checked if disabling SELinux helps (maybe something with file labeling)? How much files did you delete from the FS? Does a "direct" mount on the host(s) work (e.g. `mount -t cephfs ...`)?

**Comment by sinqinc** [comment]
I think you should link this to #1553 

it's seems to be related.
