### ISSUE TITLE
minio operator unable to handle custom k8s domains (anything aside from cluster.local)

### ISSUE THREAD

**Issue by thrawn997** [rook/rook#1836]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
Followed the instructions from https://rook.io/docs/rook/master/minio-object-store.html

What you expected to happen:
Have a working minio cluster

How to reproduce it (minimal and precise):
change your k8s domain from cluster.local to dev.cluster.local (in kube-dns and kubelet)
Followed the instructions from https://rook.io/docs/rook/master/minio-object-store.html=
kubectl -n rook-minio logs my-store-0

Error: lookup my-store-0.my-store.rook-minio.svc.cluster.local on 10.153.0.10:53: no such host

**Comment by thrawn997** [comment]
I *think* the issue is

minioServerSuffixFmt     = "%s.svc.cluster.local"
 in 
rook/pkg/operator/minio/controller.go

I am not sure why you would need to specify this?  Using the unqualified domain should work fine in kubernetes.

**Comment by jbw976** [comment]
Thank you for reporting this issue and sharing your debugging findings @thrawn997.   I think you are right, that code you shared should probably not be hard-coding the `cluster.local` suffix: https://github.com/rook/rook/blob/master/pkg/operator/minio/controller.go#L46

Do you want to submit a pull request to fix with something that works more broadly across all kubernetes deployments?  That would be very appreciated! :bow:

**Comment by thrawn997** [comment]
Pull request submitted: https://github.com/rook/rook/pull/1838
