### ISSUE TITLE
Integration tests for OpenShift

### ISSUE THREAD

**Issue by travisn** [rook/rook#1841]
Given OpenShift's differences, particularly around security settings, we need integration tests to run as part of the CI.

**Comment by zhwenh** [comment]
I tested the rook 0.8 rook/ceph:master version today. In the openshift 3.9 version, I found it still not working or I still need to delete it.
func ClusterOwnerRef(namespace, clusterID string) metav1.OwnerReference {
//blockOwner := true
return metav1.OwnerReference{
APIVersion: ClusterResource.Version,
Kind: ClusterResource.Kind,
Name: namespace,
UID: types.UID(clusterID),
// BlockOwnerDeletion: &blockOwner,
}
}
or set blockOwner := false

The parameters set according to this document are as follows:
https://github.com/travisn/rook/blob/openshift-compatible/Documentation/openshift.md

   env:
        - name: RBAC_ENABLED
          value: 'false'
        - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
          value: 'true'
        - name: ROOK_LOG_LEVEL
          value: INFO
        - name: ROOK_MON_HEALTHCHECK_INTERVAL
          value: 45s
        - name: ROOK_MON_OUT_TIMEOUT
          value: 300s
        - name: ROOK_SKIP_SET_OWNER_REF
          value: 'true'
        - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
          value: 'true'

**Comment by travisn** [comment]
@zhwenh actually i need to merge #1729 before rook will run on openshift. Could you try building from my branch from that PR and confirm that it works for you? Thanks!

**Comment by travisn** [comment]
@zhwenh yes it is the branch in https://github.com/travisn/rook/tree/openshift-compatible

**Comment by zhwenh** [comment]
I tested https://github.com/travisn/rook/tree/openshift-compatible ，and again there's no anything created, no mon or osd pod created！

env:
- name: RBAC_ENABLED
value: 'false'
- name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
value: 'true'
- name: ROOK_LOG_LEVEL
value: INFO
- name: ROOK_MON_HEALTHCHECK_INTERVAL
value: 45s
- name: ROOK_MON_OUT_TIMEOUT
value: 300s
- name: ROOK_SKIP_SET_OWNER_REF
value: 'true'
- name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
value: 'true'


apiVersion: ceph.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook
spec:
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: true
    count: 3
  network:
    hostNetwork: false
  serviceAccount: default
  storage:
    config:
      databaseSizeMB: 1024
      journalSizeMB: 1024
      storeType: bluestore
      walSizeMB: 2024
    deviceFilter: null
    location: null
    nodes:
      - devices:
          - name: vdc
        name: 10.10.3.148
      - devices:
          - name: vdc
        name: 10.10.5.180
      - devices:
          - name: vdc
        name: 10.10.41.50
    useAllDevices: false
    useAllNodes: false

**Comment by galexrt** [comment]
@zhwenh Could you please post the Rook operator logs and also add code blocks around your manifest so it is better readable.

**Comment by zhwenh** [comment]
@travisn  Can you give me  a image which replace the docker.io/rook/ceph image for test openshift.

**Comment by zhwenh** [comment]
Great, I passed the test(https://github.com/travisn/rook/tree/openshift-compatible),
 can create mon, osd, mds normally.
name: ROOK_SKIP_SET_OWNER_REF
value: 'true'
name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
value: 'true'

[root@rook-tools-1-w6b5j /]# ceph -s
 cluster:
   id:     1a6bdf60-74a0-416f-b64b-ad1fd43ef97e
   health: HEALTH_OK

 services:
   mon: 3 daemons, quorum rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2
   mgr: a(active)
   mds: myfs1-2/2/2 up  {0=myfs1-64486b7d8d-56jx9=up:active,1=myfs1-64486b7d8d-znc56=up:active}, 2 up:standby-replay
   osd: 4 osds: 4 up, 4 in

 data:
   pools:   3 pools, 192 pgs
   objects: 34 objects, 3558 bytes
   usage:   4113 MB used, 784 GB / 788 GB avail
   pgs:     192 active+clean (edited)

apiVersion: ceph.rook.io/v1alpha1
kind: Cluster
metadata:
  clusterName: ''
  creationTimestamp: '2018-06-30T02:01:49Z'
  finalizers:
    - cluster.ceph.rook.io
  generation: 0
  name: rook-ceph
spec:
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: true
    count: 3
  network:
    hostNetwork: false
  serviceAccount: default
  storage:
    config:
      databaseSizeMB: '1024'
      journalSizeMB: '1024'
      storeType: bluestore
      walSizeMB: '2024'
    nodes:
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: vdc
        name: 10.110.3.148
        resources: {}
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: vdc
        name: 10.110.5.180
        resources: {}
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: vdc
          - FullPath: ''
            config: null
            name: vdd
        name: 10.110.41.50
        resources: {}
    useAllDevices: false

**Comment by travisn** [comment]
I see that the integration tests could be modified upstream to be supported for OpenShift by doing the following:
- Add a new boolean argument to the GetRookOperator() such as `enableOpenShift`
- If `enableOpenShift` is true, that method would also include the scc and operator settings needed to run in openshift

The follow-up step is then to enable Jenkins to run OpenShift to trigger a test with this option.
