### ISSUE TITLE
Bug: rook-tools not working anymore?

### ISSUE THREAD

**Issue by jomeier** [rook/rook#1842]
Hi,

I'm using the current documentation to install rook-tools.

I had to change the namespace in toolbox.yml from rook-ceph to rook-ceph-system but the rook-tools container doesn't start.

```
kubectl describe pod rook-ceph-tools -n rook-ceph-system 
```

show this:

```
...
  Warning  FailedMount            2s (x5 over 10s)  kubelet, chmu006w003.rsint.net  MountVolume.SetUp failed for volume "mon-endpoint-volume" : configmaps "rook-ceph-mon-endpoints" not found
```

What's the reason for that? Can someone help me in getting rook toolbox working again?

Btw: Can someone adjust the yaml file and the documentation, please?

Thanks a lot,

Josef

**Comment by galexrt** [comment]
@jomeier What Rook version are you running?
As you wrote that you had to change `rook-ceph` to `rook-ceph-system` you are probably on Rook v0.7.x using the `master` toolbox, please try with the v0.7.x toolbox, see https://rook.io/docs/rook/v0.7/toolbox.html.

**Comment by jomeier** [comment]
@galexrt 
Yes you are right. My versions of rook and the toolbox were different. My fault.

I'll close this issue.

Thanks a lot.
