### ISSUE TITLE
Pod Rescheduling - Ceph Block ReadWriteMany

### ISSUE THREAD

**Issue by dac88** [rook/rook#1844]
Hi,

If a pod is rescheduled because of a node failure, not having ReadWriteMany capability prevents the Persistent Volume from being re-used.

Is this definitely a feature that cannot be implemented or have a manual workaround? It seems to go against the design pattern of having persistent storage and ephemeral containers.

Thanks,
Dean.

**Comment by galexrt** [comment]
Duplicate of #1507.

Please close the issue if you are okay with tracking this in #1507.
