### ISSUE TITLE
Release criteria and checklist

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1846]
We need to author a set of criteria (a checklist) for everything that must be accomplished and verified before we declare a release build from master.  https://github.com/rook/rook/blob/master/build/release/README.md goes into some detail but not nearly enough.

We should use this checklist to know with confidence that we are ready for 0.8.

**Comment by travisn** [comment]
Draft of the recommended release criteria:
- All documentation is reviewed for accuracy
- Test the QuickStart guide
- Test all examples in the storage provider documentation
- Test with a single-node configuration
- Test with a multi-node configuration with at least three nodes    
- Upgrade from 0.7:
    - From a single-node cluster
    - From a multi-node cluster
    - Includes directories and devices
- Signing off on the release:
    - Each storage provider is at the declared quality (alpha, beta, stable). 
    - All maintainers sign off on the release. If unavailable, advance approval is ok.
    - Beta storage providers require multiple community members to sign off on the release
