### ISSUE TITLE
how can I add  a disk to rook cluster

### ISSUE THREAD

**Issue by zhwenh** [rook/rook#1849]
I have a question
Today,I added a hard disk to the cluster config, but new osd is not generated.
     - config: null
        devices:
          - name: vdc
          - name: vdd   #I add this disk into cluster config. but new osd is not generated
        name: 10.1.41.50

from the ROADMAP https://github.com/rook/rook/blob/master/ROADMAP.md
Ceph features and improvements:
          Disk management (1 OSD per pod, adding/removing disks)
Is this feature not yet developed?

Environment:

OS : centos 7.4
Kernel : 4.17
Rook version : rook master version ,use rook 0.8 master docker image-- docker.io/rook/ceph:master
Kubernetes version (use kubectl version): 1.9
Kubernetes cluster type:OpenShift 3.9
Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox):health OK

**Comment by galexrt** [comment]
@zhwenh For technical and non-technical general questions, as written in the issue template, we are happy to help you on our [Rook.io Slack](https://Rook-io.slack.com).

Additionally please fill out the issue template so we have the information we need to further help you, see https://github.com/rook/rook/blob/master/.github/ISSUE_TEMPLATE.md.

**Comment by rgiordani71** [comment]
@galexrt how can access on Rook.io Slack? Could you send me an invitation?
Thanks

**Comment by jbw976** [comment]
@rgiordani71 you can join the slack workspace with this link: https://rook-slackin.herokuapp.com/
