### ISSUE TITLE
Pod with dynamic volume stays in 'unknown' state if node powers off. Delete not possible

### ISSUE THREAD

**Issue by jomeier** [rook/rook#1858]
Hi,

we are using rook (ceph) as storage solution in our kubernetes cluster.

If we deploy the mysql demo from rook everything works as expected. But if we kill the node which hosts the mysql pod, the mysql pod gets this status, the newly spawned pod is stuck in ContainerCreating forever:

```NAMESPACE          NAME                                      READY     STATUS              RESTARTS   AGE       IP           NODE
default            wordpress-mysql-5f4b68789d-fsxhs          1/1       Unknown             0          10m       10.42.5.9    chmu007w001.rsint.net
default            wordpress-mysql-5f4b68789d-sqflx          0/1       ContainerCreating   0          54s       <none>       chmu004m002.rsint.net
```

Deletion of the pod with this method doesn't work:

```
kubectl delete pod wordpress-mysql-5f4b68789d-fsxhs --force --grace-period=0 --wait=false
```

The pod with the 'unknown' pod will be still there, the newly spawned pod is stuck in 'ContainerCreating'.

Shouldn't take Kubernetes take care about that we can delete also PODs which are on lost nodes?

Maybe it's also a bug somewhere in rook/ceph? 

Thanks and best regards, 

Josef

- Kubernetes version (use `kubectl version`): 1.10.3
- Cloud provider or hardware configuration: VM 
- OS (e.g. from /etc/os-release): CentOs 7.5 
- Kernel (e.g. `uname -a`): 3.10.0-862.2.3.el7.x86_64
- Install tools: Rancher RKE
- Others:

**Comment by galexrt** [comment]
@jomeier Yes, normally `--force` and `--grace-period=0` should do the job though Kubernetes seems to behave differently with `finalizers` it seems.
