### ISSUE TITLE
Non default Minio port not taken into account by the operator

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rook/rook#1860]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Whatever port you configure in Minio ObjectStore, the minio process in the container is still using port 9000 whereas Kubernetes uses the right configured port as "containerPort".

**Expected behavior:**

Either Minio process listen on the port configured in ObjectStore or remove the "port" configuration in ObjectStore.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v0.7.0-240.gc568dd6

**Comment by galexrt** [comment]
@sebastien-prudhomme Two solutions possible here:
1. Tell Minio to listen on the port.
2. Add `targetPort: 3000` to the Service and discourage use of Minio Pods directly.

I personally would go for number 2 because it feels better keeping the `containerPort` the same as the application "normally" uses and Services like this should only be accessed through their Service and not by Pod.

**Comment by sebastien-prudhomme** [comment]
If someone can explain me also why there is a service declared in the example chart as the operator creates another one.

**Comment by galexrt** [comment]
@sebastien-prudhomme You mean the https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/minio/object-store.yaml manifest (there is no chart for the Rook Minio operator yet)?

The reason for that is that the Service created by the Rook Minio operator is a headless Service. A headless Service does not do "any" load balancing (nor create/use a Service IP). The DNS record behind the Service outputs the Pod Endpoints round robin style.
A "normal" Service (`clusterIP` != `None`) creates/uses a Service IP to do "load balancing" with iptables (by default, see kube-proxy for more info).

If you want to know more about how kube-proxy does "load balancing" with iptables, I'd recommend you to checkout a diagram I made: https://docs.edenmal.moe/kubernetes/networking/explained/#service-ip-iptables.
