### ISSUE TITLE
Allow creating several Minio ObjectStores in the same namespace

### ISSUE THREAD

**Issue by sebastien-prudhomme** [rook/rook#1861]
**Is this a bug report or feature request?**

* Feature Request

**What should the feature do:**

Because the Minio operator is using the same fixed label "app: minio" for all objectstores, it's impossible to creates several objectstores in the same namespace: services created reference all pods as endpoints.

Adding another label with the objectstore name or using the objectstore name as the "app" label will allow to so such a thing.

NB: it seems that there is such a limitation with all other operators (ceph, etc)

**Comment by sebastien-prudhomme** [comment]
Looking how the coreos etcd-operator build the pods for an etcd cluster, it uses both "app: etcd" and "etcd_cluster: MY_CLUSTER_NAME" as labels.

If i follow that kind of best practices, adding "minio_objectstore" label will be a good answer to he problem.

**Comment by galexrt** [comment]
/keepalive @sebastian-philipp will look into it, to unblock your PR.

**Comment by sebastian-philipp** [comment]
Too many Sebastians here...

**Comment by galexrt** [comment]
@sebastian-philipp Sorry, my bad. I wanted to mention @sebastien-prudhomme.

**Comment by galexrt** [comment]
@sebastien-prudhomme This has been fixed now. A label named `objectstore` will now contain the value of the Object store instance.
