### ISSUE TITLE
Operator restart unexpectedly created new osds in default directory

### ISSUE THREAD

**Issue by aland-zhang** [rook/rook#1864]
**Environment**:
* OS: centos7.4
* Kernel :4.17
* Rook version :rook/ceph:v0.7.0-240.gc568dd6
* Kubernetes version:1.9.1
* Kubernetes cluster type:OpenShift 3.9 (one master node and tree compute nodes)
 I just cleaned up the cluster and rm -rf /var/lib/rook. 
I tested rook/ceph:v0.7.0-240.gc568dd6 ， found that the operator did not create osd according to the cluster configuration file. the log and config file ：https://gist.github.com/aland-zhang/71f7bc4f5461a75236d6b67757a1ae4b

apiVersion: ceph.rook.io/v1alpha1
kind: Cluster
metadata:
  clusterName: ''
  creationTimestamp: '2018-06-30T02:01:49Z'
  finalizers:
    - cluster.ceph.rook.io
  generation: 0
  name: rook-ceph
  namespace: rook
spec:
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: true
    count: 3
  network:
    hostNetwork: true
  serviceAccount: default
  storage:
    config:
      databaseSizeMB: '1024'
      journalSizeMB: '1024'
      storeType: bluestore
      walSizeMB: '2024'
    nodes:
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: vdc
          - FullPath: ''
            config: null
            name: vdd
        name: 10.10.3.148
        resources: {}
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: vdc
        name: 10.10.5.180
        resources: {}
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: vdc
          - FullPath: ''
            config: null
            name: vdd
        name: 10.10.41.50
        resources: {}
    useAllDevices: false

Just looked at the cluster situation and found that the operator created three more osd,  I only have 5 hard drives on 3 nodes. but operator created 8 osds.
osd-5 6 7 ，Not specified in the cluster configuration file, but these three osd were created，
The following is the configuration of rook-ceph-osd-5-fs-backup（Rook-ceph-osd-6-fs-backup and 7 are the same）.
Please see my cluster configuration file above and I have not set it（/var/lib/rook/osd5/bluestore-db）, but it is created automatically.
There is no new disk drive add in cluster config , but the rook-ceph-osd-prepare job is automatically up and osd is created automatically.
apiVersion: v1
data:
 bluefs: |
   1
 ceph_fsid: |
   3af30768-54fb-4338-8722-62ff7b0498d0
 fsid: |
   db08c8d7-4b02-4e2d-a3ac-0412e1c6586b
 kv_backend: |
   rocksdb
 magic: |
   ceph osd volume v026
 mkfs_done: |
   yes
 path_block.db: |
   /var/lib/rook/osd5/bluestore-db
 path_block.wal: |
   /var/lib/rook/osd5/bluestore-wal
 ready: |
   ready
 type: |
   bluestore
 whoami: |
   5
kind: ConfigMap
metadata:
 creationTimestamp: '2018-07-10T06:01:13Z'
 name: rook-ceph-osd-5-fs-backup
 namespace: rook (edited)

![1](https://user-images.githubusercontent.com/929393/42520365-a24296b4-8498-11e8-8de9-e15d66a82d26.png)

**Comment by travisn** [comment]
I was able to repro after troubleshooting these logs. When devices are set explicitly (and useAllDevices is false), if the operator is restarted, the device list is not passed to the provisioner so the operator creates new osds in the default directory.

**Comment by aland-zhang** [comment]
verion： docker.io/rook/ceph:v0.7.0-264.gdff99d5 and  openshift3.9 

Great ，I tested all the features, including Add disk、 Filesystem and ObjectStore and restarted the operator repeatedly, and there were no exceptions. Now all the functions are normal!
