### ISSUE TITLE
Design doc for Rook integration with external orchestrator

### ISSUE THREAD

**Issue by travisn** [rook/rook#1868]
We need a design doc that captures the requirements around integration of Rook with an external manager of the Ceph cluster. Some basic scenarios include:
- A Ceph cluster is already running and Kubernetes is started in the environment. Rook could potentially start managing the cluster by monitoring mons and automatic failover, scheduling RGW, MDS, and MGR pods, or detecting when OSDs are down.
- Rook starts a cluster and the user desires to manage the cluster from the Ceph dashboard. Rook should no longer manage the mons, create pools, etc.

Related documentation includes:
- [Ceph mgr design](https://github.com/ceph/ceph/pull/21046) for working with multiple orchestrators such as Rook.
- #1485 initiated some changes on skipping operations in Rook

### Approach
The point of integration between Rook and the mgr will be the Rook CRDs. When the user is configuring the cluster in the Ceph dashboard, the Mgr module will set the desired state of Rook through the CRDs. Partial management of a cluster has a large matrix of possibilities so we will need to define what state should be exposed in the CRDs. 

Settings in the Ceph CRDs would be added to accommodate the integrated/reduced automation. The settings would be explicit (rather than by omitting a setting) so it is clear that Rook will turn off functionality. The default settings would still be for full management to be performed by Rook as today.

### Mons
Due to the strong dependence of all the Rook daemons on the mon endpoints stored in the configmap `rook-ceph-mon-endpoints` and secrets for accessing the cluster, either the external orchestrator would need to create these resources in the format Rook understands or else we would need to train the daemons where to find the same metadata. With this in mind, consider the settings in the `mon` section of the Cluster CRD:
- `disableFailover`: Set to `true` when Rook should *not* monitor mon health
- `disableCreate`: Set to `true` when Rook should *not* start any mons even at cluster creation.

### OSDs
In the `storage`, `config` sections of the Cluster CRD, consider the settings:
- `disableCreation`: Assuming OSDs are created and managed externally. No device/OSD management will be done by Rook. 
- `disableMonitoring`: Don't monitor whether the OSDs are healthy 

### Pools
Pools are created by Rook when the CRD is created and deleted when the CRD is deleted. If management of pools is not desired, the Pool CRD should not be used.

### Filesystem
When creating a filesystem, Rook creates pools for the metadata and data, according to the pool configuration in the CRD. If Rook finds the pools already exist when the filesystem is created, their configuration will be skipped. When the Filesystem is deleted, Rook will delete the pools used by the filesystem. To relax this behavior, consider the settings:
- `skipPoolConfig`: Require the pools to already exist and skip all pool configuration
- `purgePoolsOnRemove`: `true` to maintain the current behavior and `false` for the pools to remain after the filesystem (and mds) is removed.

### Object store
The object store pools will have similar behavior to the filesystem pools and we could consider similar settings.

@liewegas @jcsp @dmick @rootfs @BlaineEXE

**Comment by jcsp** [comment]
Extra related document on managing OSD devices from ceph-mgr/ceph-volume via the nascent orchestrator interface: https://docs.google.com/document/d/1iwTnQc8d9W3BpQHgGYTMZSKvN6J7s0z8kQaYNxYvLho

**Comment by jcsp** [comment]
The scenario I'm most interested in at the moment is where a new mon+mgr cluster has been created, and then the user wants to drive everything else from the dashboard.  In that case, all services are Rook managed, and it's only the logical Ceph bits (filesystems, RGW zones) that need the flags for making pool creation optional.  So for me, the really essential flag is the `skipPoolConfig` on Filesystem (and subsequently Object Store).

Making management of mons and OSDs optional definitely has value for migration, but I wonder if that use case could be whittled down to just tolerating existing baremetal OSDs (i.e. just the disableMonitoring flag).  At the point that we're setting up Kubernetes/Rook, and importing keys etc into Rook, maybe it makes sense to also require that an offline move of the mons into Rook happens too.

**Comment by jcsp** [comment]
(BTW, thanks for opening this @travisn , you've inspired me to open the somewhat-related https://github.com/rook/rook/issues/1869)

**Comment by liewegas** [comment]
I think a robust "adoption" function that moves an existing cluster under ceph management is going to be pretty important (eventually!).  Having some manual steps initially is probably okay but in the end I suspect we'll have to have a process for adopt that allows rook to start managing the cluster before the mons move, since moving mons into kube will involve new ips and changes to 'mon hosts' in ceph.confs (or DNS) all over the place.  We should probably sketch out what the steps would be independent of who is doing what (rook vs human) because I suspect there are several unknowns still (for example, could the part of the cluster external to kubernetes consume the kube dns entries for latest mon ips? could that dns produce records that include the external mons?)

**Comment by travisn** [comment]
To adopt a cluster, I am seeing that we need some tool/scripts that will pick up everything needed from an existing cluster, populate the k8s configmaps, secrets, etc that Rook expects, then start the Rook operator. It won't be something that would require settings in the CRD, but will prime the pump so the operator will just think it's a normal cluster. 

After populated by the tool, the operator would see the existing configmaps, secrets, and other resources and skip creating those resources, then only create the resources that are needed. For example, the tool could generate the configmap that says what mons are supposed to be running on what nodes, then the operator would see the mon pods are *not* running and go ahead and start them. The mon pods would point to the persisted data on the given nodes that was being consumed by the previous mons with the same IDs. 

So the settings in the CRDs would still be focused around what happens when the dashboard is driving the changes and Rook needs to pull back.

**Comment by BlaineEXE** [comment]
I agree that cluster "adoption" functionality is something that needs to happen, and I want to agree and emphasize the "eventually." I think cluster adoption is not really a "basic scenario," at least as far as development effort is concerned.
I don't want to downplay the importance of this; looking toward the future here is good, and sketching out steps seems a good start. Something that I am wondering is how we would expect users to migrate from bare-metal to kubernetes+rook from a machine/os perspective. 

If I intend to "adopt" an entire cluster at once in-place, I would bring ceph offline, and then I would convert each of my nodes into a k8s minion. I might even install a new distro like coreos, which might necessitate data backup and recovery on my os disk. Once all nodes are converted to k8s minions, I need to collect all the information about where ceph data is stored for Rook as well as what roles each node had (ideally by script). At minimum, the mon and osd nodes need to be on the same nodes as the baremetal cluster I would think.

Another thought might be that I want to convert nodes one-at-a-time. This seems safer, as you'll learn quickly if something has gone wrong, and you can fix it before other nodes might be borked. But then there is a scenario where a cluster may be partly baremetal and partly k8s, and this seems precarious to me. Maybe that isn't as big an issue as I'm imagining.

Either way, I think it would be helpful for me to start at the very beginning of the process where a user wants to convert baremetal ceph to rook ceph.
