### ISSUE TITLE
Design doc for complete Ceph OSD management (SSD journals, drive replacement)

### ISSUE THREAD

**Issue by jcsp** [rook/rook#1869]
Related: https://docs.google.com/document/d/1iwTnQc8d9W3BpQHgGYTMZSKvN6J7s0z8kQaYNxYvLho (apologies for google doc, @jcsp can grant access as needed)

When driving Rook from higher level UIs, we are mostly interested in the explicit device selection format, where we pass rook a list of nodes and list of devices for each node:

```
  storage:
    nodes:
    - config: null
      devices:
      - FullPath: ""
        config: null
        name: sdb
      name: gravel2.rockery
```

The simple list of device names is quite a limited syntax, and doesn't work well for:
A) Creating OSDs that combine solid state and spinning rust storage (such as a filestore OSD with an SSD journal, or a bluestore OSD with an SSD DB partition).
B) Driving OSD replacements, where an OSD is created to take over an existing ID rather than create a new one.

These two things need to be thought of together, because at the point we implement A, the implementation of B has to handle those cases where OSDs span devices.

## Creating OSDs that use SSDs for journal/db/wal partitions

This is intended to be addressed in ceph-mgr and ceph-volume by implement a "batch prepare" operation in ceph-volume, and bubbling up that grouping of drives in ceph-mgr as a "drive group".  High level logic in ceph-mgr species which storage devices are to work together, and leaves the details of partitioning etc to ceph-volume.

Rook would need to change to enable this functionality, to enable grouping the devices within each node.  Perhaps an optional additional "device groups" field:

```
      device_groups:
      - - FullPath: ""
          config: null
          name: sdb
        - FullPath: ""
          config: null
          name: sdc
        - FullPath: ""
          config: null
          name: sdd
``` 

In the above example, with a drive group of [sdb, sdc, sdd], if one of those drives is an SSD and the others are HDDs, then ceph-volume would end up creating two OSDs, using the SSD for journals or db partitions as appropriate.  If they were all hard drives, you'd end up with three standalone OSDs.  This logic all lives down in ceph-volume, so all Rook needs to do is pass through the drives as a group, and do the prepare operation for the drives together, so that ceph-volume can partition up the SSD appropriately.

## Enabling explicit OSD replacement

Because the cluster CRD doesn't explicitly associate OSD IDs with devices, when we add a device we have no way to inform Rook that we wish to use the device as a replacement for an existing, failed OSD, rather than as a completely fresh OSD.

Consider the case of an OSD that used both a HDD and a DB partition on an SSD.  At the ceph-volume level, an efficient "replace" operation needs to find any existing SSD partitions for the defunct OSD, clear them, and use the newly freed space to create fresh partitions for the fresh hard drive that we will use as a replacement.  It then needs to format the new HDD, and assign it the same OSD ID as the drive being replaced.  

To enable Rook to make the appropriate calls to ceph-volume, we might add an optional OSD ID field to the device object in the CRD.  During initial cluster creation, this would not be set.  However, when the user performs an explicit UI operation (via ceph-mgr) to say "please use the new drive 'sdc' to replace the failed OSD 7", the resulting drive object might look like:

```
        - FullPath: ""
          config: null
          claim_osd_id: 7
          name: sdc
```

The `claim_osd_id` field would not be meaningful if applied to an SSD that was in a group with HDDs, as that SSD would be in use for journal/db partitions rather than as an OSD itself.

**Comment by travisn** [comment]
I'm struggling with using the CRD to communicate details like the OSD ID that the device corresponds to. I don't think the OSD ID belongs in the desired state, although I can't think of a different way. The OSD ID is an implementation detail. 

From the desired state perspective, replacing a disk could be similar to adding or removing disks to a node. Let's say we add a new disk to a node. Today the operator would not be aware of the new disk until someone updates the CRD to add the disk to the list of desired disks. But if he is using a device filter that already includes the disk, he shouldn't have to update the CRD. Still, we need a way to trigger the OSD provisioning/configuration to happen on the node to go configure the changed devices. The only approach that comes to mind is to update the CRD, as mentioned above. Since replacing an OSD requires more info such as the OSD ID, then it would be included in the CRD. Then when the operator is done, it could remove whatever temporary desired state was necessary from the CRD since it was only short-term desired state.

**Comment by jcsp** [comment]
Right, it doesn't exactly fit under what we'd call "desired state" --  we're kind of straining against the limits of using a declarative moment-in-time model.

An alternative way to express this is to store somewhere (an element of the cluster CRD or elsewhere) a map of "in progress" OSD ID re-mappings  that would act as an overlay on the cluster's list of devices.  That might be a bit conceptually purer, at the cost of some implementation complexity.

**Comment by BlaineEXE** [comment]
Could we implement a "desired state" with automatic replacement by adding devices from `/dev/disk/by-part/pci-0000:00:17.0-ata-1`, for example? If I understand correctly, even if I replace this disk with another one, it will still have the same pci address. If we had rook create every osd with an ID and tied to a disk by pci address above, there could be an init container that checks if the disk is empty, and if it is, it adds the disk to the cluster. If there is no osd with the id in ceph already, it simply adds it, and if there is an osd, it goes through replacement operations.

**Comment by liewegas** [comment]
We should be careful getting our hopes up about unprivileged OSDs:

- Encrypted devices will need ceph-volume to get the key metadata, fetch the decryption key from the key manager (mon normally), set up the decrypted dm volume (via cryptsetup... this needs root) and then start the OSD
- The new smartctl device metric scraping needs root.  With systemd we rely on sudoers.d to sudo smartctl.  In the container we'll do something similar.. but it will only work if the container can elevate to run smartctl
- In our shiny SPDK future OSD startup will involve reading metadata off the nvme device, telling the kernel to disable the driver, then starting up the OSD with SPDK talking directly to the device memory to do the driver in userspace.  I'm not super familiar with the innards but it will clearly require root.

**Comment by BlaineEXE** [comment]
@liewegas, I could be misunderstanding something you are trying to get at, but running applications in the container as root does not necessitate running the container with the 'privileged' flag.

Not getting our hopes up seems a wise warning, but I don't think we should make design decisions today that will corner us into using privileged containers for the forseeable future. Even if privilege is required today, it may not be so in the future. GPUs can be accessed today by k8s without privilege, and I see no reason why NVMe could not also be accessed without privilege at some point. And as I show below, I think both smartctl and cryptsetup/lvm can be used in containers without too much work.

-----

I can run smartctl from the container successfully without needing to add the `--privileged` flag to my docker command. Kubernetes should be no different. The command doesn't output much, I'm assuming because the disk is virtual.
```
blaine-dev-k8s-worker-0:~ # docker run --device=/dev/vdb:/dev/vdb -it --rm opensuse/leap:15
98420742c341:/ # smartctl -d scsi -x -T permissive /dev/vdb
smartctl 6.6 2017-11-05 r4594 [x86_64-linux-4.4.132-94.33-default] (SUSE RPM)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

Short INQUIRY response, skip product id
Read Cache is:        Unavailable
Writeback Cache is:   Unavailable

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Error Counter logging not supported

Device does not support Self Test logging
Device does not support Background scan results logging
```
-----

I was able to get cryptsetup to encrypt a device, but I was unable to mount it in the container because the kernel module was not available; this is a problem which I imagine could be fixed with more effort. fdisk works and shows that the disk is indeed encrypted. I was also able to create an lvm pv and vg, but lvcreate failed due again to my kernel not having device-mapper, which I again think is something that can be fixed fairly simply.
```
2650346d3caf:/ # zypper in device-mapper kernel-default lvm2 cryptsetup
2650346d3caf:/ # cryptsetup luksFormat /dev/vdb

WARNING!
========
This will overwrite data on /dev/vdb irrevocably.

Are you sure? (Type uppercase yes): YES  
Enter passphrase for /dev/vdb: 
Verify passphrase: 
2650346d3caf:/ # cryptsetup luksOpen /dev/vdb encryptedpart
Enter passphrase for /dev/vdb: 
Cannot initialize device-mapper. Is dm_mod kernel module loaded?
Cannot use device encryptedpart, name is invalid or still in use.
2650346d3caf:/ # modprobe dm_mod
modprobe: FATAL: Module dm_mod not found in directory /lib/modules/4.4.132-94.33-default
2650346d3caf:/ # fdisk /dev/vdb

Welcome to fdisk (util-linux 2.31.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

The old crypto_LUKS signature will be removed by a write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x1c85bad6.

Command (m for help):

2650346d3caf:/ # pvcreate /dev/vdb
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  Physical volume "/dev/vdb" successfully created.
2650346d3caf:/ # vgcreate vgroup /dev/vdb
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  Volume group "vgroup" successfully created
2650346d3caf:/ # lvcreate -L 2G -n lvol vgroup
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  /dev/mapper/control: open failed: Operation not permitted
  Failure to communicate with kernel device-mapper driver.
  Check that device-mapper is available in the kernel.
  Incompatible libdevmapper 1.03.01 (2017-12-18) and kernel driver (unknown version).
  striped: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
```

**Comment by liewegas** [comment]
> > Could we implement a "desired state" with automatic replacement by adding devices from /dev/disk/by-part/pci-0000:00:17.0-ata-1
> 
> I've found that kind of tempting, but it's quite an opinionated model (tying OSD IDs to hardware slots), and I'm not sure we can be that prescriptive.  I'd like us to be able to handle someone replacing an OSD by putting a fresh drive into a different slot, for example.
> 
> We also might sometimes need to cope with people removing and replacing drives (e.g. to transport equipment), which might not get put back into the same slot.

Also, moving all devices to a new host to cope with motherboard/NIC/whatever failure.

**Comment by BlaineEXE** [comment]
> This is a key point -- the question of whether the partitioning decisions should be made up in the ceph-mgr layer. The big idea of drive groups is that ceph-mgr only knows about the abstract concept of drives being linked, rather than the detail of exactly how they're sliced up. That's a key simplification when we're talking to orchestrators, because it means don't need a pan-orchestrator way to express disk partitioning. Complexity at the ceph-mgr<->orchestrator hop is expensive, because it gets implemented N times for the different orchestrators.

> Also, moving all devices to a new host to cope with motherboard/NIC/whatever failure.

> When it comes to device-level isolation of unprivileged containers, it should be possible for the orchestrator to remember which devices go with which OSD, by taking the output of ceph-volume when it prepares the devices. Then the orchestrator can make sure the OSD container is shown the right devices. We shouldn't write in any assumptions about partition-level isolation, because new hardware access mechanisms may not support it.

These are strong reasons. And I've been having some further thoughts over the weekend about how drive groups might work/affect Rook. For a drive to be prepared with a drive group implementation in ceph-volume, it seems to me that there will have to be an osd prepare step for the entire drive group, unless you have other thoughts. So there will be some pod that get drive group info and access to all the drives it needs, and then ceph-volume does its thing. After that, all of those osds can be started with access only to the devices they need, which should allow us to plan to run those without privilege. In this scenario, I think Sebastien's more detailed proposal still makes sense so we can know exactly which disks (and partitions?) to give to an osd pod for security.

I've also considered that the prepare pod may not need to be privileged if we map all disks to it individually. `/dev/disk/by-uuid/X` on the host would get mapped to `/dev/disk/by-uuid/X` in the prepare container for all the disks it needs. For the implementation here, and even if we still require privileged access, we should do all we can to *not* give containers access to `/dev`. That would be an easy security vulnerability to take advantage of.

**Comment by dimm0** [comment]
No progress on this yet?

I'm thinking about moving journal to faster drives, and I don't see any tips on how to do it in rook and what the caveats may be. Is that tested in rook?

**Comment by aba182** [comment]
+1 I am seeing very poor write speeds on my rook cluster and was hoping to increase performance by adding SSD's for journal operations as suggested by standard ceph deployment documentation.

**Comment by wdbasson** [comment]
+1 would like to add an SSD caching tier to our rook ceph cluster. Any documentation on how this can be achieved?

**Comment by gemfield** [comment]
@dimm0 So, what is the steps to reconfigure the journal path?

**Comment by dimm0** [comment]
Delete the whole node (first move data out), recreate the node with SSD as a journal
Only a single SSD is now supported. Also remember it uses the journal in steps: 3GB -> 30GB -> 300GB. So if you have 25GB per drive, only 3 will be used

**Comment by gemfield** [comment]
> recreate the node with SSD as a journal
Thanks. But how to do this step? Which part in cluster.yaml?

**Comment by dimm0** [comment]
Kinda like this

```yaml
    nodes:
    - name: "my-node-aaa"
      config:
        metadataDevice: "nvme0n1"
      devices:
      - name: "sdc"
```

**Comment by gemfield** [comment]
@dimm0 I have noticed this field, but never thought it is about journal...
Thanks.

**Comment by dimm0** [comment]
I never measured the performance. We have a very distributed cluster and performance depends on many factors

**Comment by gemfield** [comment]
@dimm0 Thanks.

**Comment by dimm0** [comment]
Are docs for replacing a drive with journal on NVME yet?

**Comment by travisn** [comment]
> Are docs for replacing a drive with journal on NVME yet?

@dimm0 Can you describe more what you're looking for in the docs? Does the [Replace an OSD](https://rook.github.io/docs/rook/v1.3/ceph-osd-mgmt.html#replace-an-osd) help?

**Comment by dimm0** [comment]
Does this apply to the case when and OSD has a journal LVM on another NVME?

**Comment by travisn** [comment]
You want to replace an individual OSD when there are multiple OSDs using hte same NVME for the journal with the `metadataDevice`? I don't believe `ceph-volume` supports that today.

**Comment by dimm0** [comment]
So what should I do? The drive failed..

**Comment by travisn** [comment]
The only option I can think of is to wipe all the OSDs on the node and re-create the OSDs on the node. That would of course be disruptive to more data and require more backfill.
@leseb any other ideas for replacing a single failed disk when an osd is sharing a metadataDevice with other OSDs on the node?

**Comment by leseb** [comment]
You can do this without using ceph-volume, if the NVMe drive still has the lvm for the `metadataDevice` you should wipe it and re-use it.

Manually you could try something like:

```console
ln -sf <nvme partition for db> /var/lib/ceph/osd/<osd id>/block.db
ln -sf <new block disk> /var/lib/ceph/osd/<id>/block
ceph-osd --mkfs --id <osd id> --osd-data <osd data path>
```

This is a general idea, not 100% perfect though, but something along those lines should do.

**Comment by dimm0** [comment]
Are there any updates for this? Do we not have a direct way to replace an OSD with NVME?

**Comment by travisn** [comment]
> Are there any updates for this? Do we not have a direct way to replace an OSD with NVME?

When using a single metadataDevice for multiple OSDs, replacing a single OSD is not possible. All the OSDs on the metadataDevice would need to be wiped and re-created.
