### ISSUE TITLE
After upgrade operator logs are full of errors failing to list legacy CRDs

### ISSUE THREAD

**Issue by travisn** [rook/rook#1877]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After upgrade and 0.7 CRD definitions are deleted, the logs are full of errors about not being able to find them. 
```
E0712 21:38:23.942234       5 reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1alpha1.Cluster: the server could not find the requested resource (get clusters.rook.io)
E0712 21:38:23.944036       5 reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1alpha1.Pool: the server could not find the requested resource (get pools.rook.io)
E0712 21:38:24.455772       5 reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1alpha1.ObjectStore: the server could not find the requested resource (get objectstores.rook.io)
```

**Expected behavior:**
Once the legacy CRDs are deleted, I would expect once the errors about the CRDs, then the operator would stop watching them.

**How to reproduce it (minimal and precise):**

Upgrade from 0.7 to the 0.8 candidate build, following the instructions in the upgrade guide.

**Comment by travisn** [comment]
Restarting the operator causes the operator to have a clean start and not hit this issue anymore.

**Comment by jbw976** [comment]
Do you think we should add an instruction to the upgrade guide to restart the operator after deleting the legacy CRDs?

**Comment by travisn** [comment]
@jbw976 that seems sufficient rather than worrying about a code fix
