### ISSUE TITLE
Update promote pipeline to match the release process

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1885]
Currently, the `release/promote` pipeline in Jenkins will call the `promote` target on the `build/release/Makefile`, which operates on all images (Ceph, CockroachDB, Minio) and helm charts.  This means that if we wanted to promote Ceph to the beta channel, then the other storage providers come along for the ride too.  We should be able to only promote specific storage providers instead of all of them.

**Comment by jbw976** [comment]
As @bassam suggested, we should consider removing the concept of channels completely because there is no project status as a whole.  Combine alpha/beta/stable channels into just a stable channel.  Keep master/dev as those are used in development workflow.

**Comment by jbw976** [comment]
/keepalive, we have to manually delete the beta tagged images for the other providers during each release, which is sort of busted

**Comment by travisn** [comment]
@galexrt @bassam @jbw976 Now that it has been a few days for our conversation to settle, here are my notes. Please clarify any area where there was different perspective.

The basic concern is that the current usage of alpha/beta/stable channels does not match the actual workflow of the rook release. The current release process is more precisely the following
- All new changes go into the `master` branch
- As we get closer to a release date, we ensure the necessary features and stabilization fixes are merged to give a quality release.
- For some time leading up to the planned release, there is an informal lockdown on merging major changes that are not necessary for the release.
- When ready for the release, we branch and release (ie. v0.9.0)
- As fixes are necessary on the release, we merge fixes to master, then backport to the release branch. As necessary, a patch release is cut (ie. v0.9.2)
- Other than the release branches, we don't currently have a QA/stabilization process

Per discussion, we want to do the following to match the current build process.
- Maintain two release channels: `master` and `release` (any alternatives for the latter?)
  - There would no longer be an `alpha`, `beta`, or `stable`.
  - This does not impact the CRD API levels with the same names
- Published docker images for **master** would continue to be unchanged: `master` and an increasing build number such as `v0.9.0-117.g28ebec11`
- Published docker images for **release** would have the tag `release` that represents the latest release, as well as the version number such as `v0.9.2`. 
  - Using the `release` docker tag in production would **not** be recommended. The operator is designed around the fact that it can know when there is a new version to upgrade iff the tag changes. Thus, I would argue that we don't want to publish this tag, though I know there were different perspectives on this.
  - We currently have a tag with the channel as a suffix such as `v0.9.2-stable`. I would recommend we remove that label as it is redundant (ie. `v0.9.2-release` is unnecessary)
- Helm would have two repos: `master` and `stable`. We would remove alpha, beta, and stable.
- All storage providers would have the same labels. No longer would the storage providers have different channels published.

 In the future if we change the process to match a release promotion process to alpha/beta/stable, we would re-evaluate the promotion channels to match. Declaring a certain level of stability like that would require a QA process that matches a stabilization process after either forking or greater lockdown of what goes in.
