### ISSUE TITLE
Support a new storage, Alluxio, to rook

### ISSUE THREAD

**Issue by iharijono** [rook/rook#1886]
* Feature Request
This FR is focused to add a new type of storage, Alluxio (https://www.alluxio.org), to rook.
It also serves as an initial discussion, tracking and to solicit comments and feedback about the idea.

**What should the feature do:**
Alluxio is a virtual distributed storage system at the memory speed. It unifies data access and bridges computation frameworks and various underlying storage systems.

The benefits of adding Alluxio to rook are:
1. Alluxio already integrates various different types of (distributed) storage systems (including ceph). Having Alluxio supported in rook will give allow rook to use many existing storage systems with one single implementation.
2. Alluxio will enable cloud native application to access data at memory speed.
3. Development of new different storage system in rook is not necessary anymore (as long as Alluxio supports it).
4. Alluxio is containerized and runs already in kubernetes.
5. If someone has deployed and systems or applications have already used Alluxio in production, the migration path to bring them into full cloud native or into micro service environment will be less error-prone.
6. it is minor, but just to mention it, Alluxio supports also key value store.

The downside is that Alluxio supports only File System (no block device).

**What is use case behind this feature:**
Some of the use cases are:
- Applications or system that needs access data at memory speed.
- Migration or Integration path of systems and applications into cloud native with persistency.

Your comments and opinions are greatly appreciated.

Thanks,
Indra

**Comment by patlachance** [comment]
look at https://github.com/Alluxio/alluxio-csi
