### ISSUE TITLE
The https://charts.rook.io/master seems unreachable

### ISSUE THREAD

**Issue by sdkfzv** [rook/rook#1889]
**Is this a bug report or feature request?**
* Bug Report

**How to reproduce it (minimal and precise):**
```
# helm repo add rook-master https://charts.rook.io/master
Error: Looks like "https://charts.rook.io/master" is not a valid chart repository or cannot be reached: Get https://charts.rook.io/master/index.yaml: proxyconnect tcp: tls: oversized record received with length 20527
```
If I access the https://charts.rook.io/ from the web broswer, there it shows:
`Error: [object Object]`

I aways got this result even if I used some other vpn.
So the https://charts.rook.io/ seems unreachable...

**Comment by galexrt** [comment]
@sdkfzv I'm unable to reproduce the `helm repo add` failure:
```
helm repo add rook-master https://charts.rook.io/master
"rook-master" has been added to your repositories
```

The list view on https://charts.rook.io is currently broken, see #1798.

**Comment by sdkfzv** [comment]
This should be my proxy issue.
It's ok on another machine.
