### ISSUE TITLE
Rook Docs: File links not working

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1890]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Links to files/directories in the repository are linking to the wrong location.
Example:
https://rook.io/docs/rook/v0.7/quickstart.html The `1.5 folder` link points to https://rook.io/cluster/examples/kubernetes/1.5 instead of https://github.com/rook/rook/tree/release-v0.7/cluster/examples/kubernetes/1.5.

**Expected behavior:**
The links to correctly link to the file/directory.

**Comment by travisn** [comment]
@galexrt do you have examples of the broken links in master?

**Comment by jbw976** [comment]
The operator.yaml link from https://rook.io/docs/rook/v0.8/flexvolume.html has been fixed with https://github.com/rook/rook/commit/688674f0f87bb3ae385191b723bd09ef302fd441.  The 1.5 folder link in the 0.7 docs is still broken, but I don't think a fix for that is very pressing.

**Comment by travisn** [comment]
thanks @jbw976, i missed looking into this again. @galexrt shall we close this issue then?

**Comment by galexrt** [comment]
@travisn Sure, if I should find other links that are broken I'll just go ahead and fix them (probably like here: https://github.com/rook/rook/pull/1959/files#diff-88af7af825258952a731f1fc21f53557).
