### ISSUE TITLE
Add tolerations option for Rook operator pods to Helm chart

### ISSUE THREAD

**Issue by mkjpryor-stfc** [rook/rook#1893]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The Helm chart already allows a `nodeSelector` to be set for Rook operator pods, but in order to fully control pod placement, it also needs to allow `tolerations` to be set for operator pods.

**What is use case behind this feature:**
I am setting up a cluster which has nodes specifically reserved for infrastructure (in-cluster storage, monitoring, logging, etc.). In order to achieve this, I set both a label and a taint on the infrastructure nodes. With the current Helm chart, I am able to get the operator pods to target the infrastructure nodes, but because they do not tolerate the taint they don't get scheduled.

**Comment by galexrt** [comment]
@mkjpryor-stfc We are happy to see contributions to Rook. Let us know if you would like to contribute this feature.

**Comment by mkjpryor-stfc** [comment]
@galexrt: I'm happy to make the change to the Helm chart.

**Comment by mkjpryor-stfc** [comment]
@galexrt

I was just wondering how often the Helm repository https://charts.rook.io/master gets rebuilt, and I can expect to see these changes in there?

Thanks!

**Comment by jbw976** [comment]
@mkjpryor-stfc the master channel of the helm repo gets updated with every master build.  You can follow along with master build activity here: https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/activity?branch=master

Looks like one just succeeded 31 minutes ago, `v0.7.0-290.g237c582`, which corresponds to https://github.com/rook/rook/commit/237c582ee47d7ccda28b394f67342e0c42d83b05

**Comment by mkjpryor-stfc** [comment]
@jbw976 

It doesn't seem like the builds are being propagated to the Helm repo. Even after waiting overnight, I am still only getting versions from the 13th July:

```
$ helm repo list | grep rook
rook            https://charts.rook.io/master
$ helm repo update | grep rook
...Successfully got an update from the "rook" chart repository
$ helm search rook-ceph
NAME            CHART VERSION           APP VERSION     DESCRIPTION
rook/rook-ceph  v0.7.0-284.g863c10f                     File, Block, and Object Storage Services for yo...
```

Perhaps the Helm repo updates are on a slower schedule?
