### ISSUE TITLE
rookctl command not found

### ISSUE THREAD

**Issue by pavansai1** [rook/rook#1894]
**Is this a bug report or feature request?**
* Bug Report

when i try to enter into rook-tool box pod it is showing some warnings

kubectl -n rook-ceph exec -it rook-ceph-tools /bin/bash
the above command produces the following
warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
@pavansai1 You are probably running a Rook toolbox with image tag `master`. `rookctl` and `rook-api` has been removed in `master`.

If you run Rook `v0.7.1`, use the Rook toolbox image `rook/rook:v0.7.1`. To be on the safe side, please use the v0.7 release branch for the manifests: https://github.com/rook/rook/tree/release-0.7/cluster/examples/kubernetes

**Comment by travisn** [comment]
closing since this appears already covered by other issues as @galexrt pointed out
