### ISSUE TITLE
test: include more architectures in test pipeline

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1901]
Is this a bug report or feature request?
* Feature Request

**Feature Request**

Are there any similar features already existing: Yes, we have existing CI pipelines for amd64.

What should the feature do:  We should add CI pipelines for the other architectures that we support, such as arm and arm64.  A recent regression to arm64 (#1872) was not caught before it was released in the master builds.

What would be solved through this feature:  The Rook project would have more confidence in the stability and reliability across all architectures that are supported. This is related to #1315 to include more environments.

**Comment by nakabonne** [comment]
Hey @jbw976 Can you tell me which architectures are currently supported?
I found the following definition in `build/makelib/common.mk`:

```
ALL_PLATFORMS ?= darwin_amd64 windows_amd64 linux_amd64 linux_arm64
```
Does this mean they are supported? Thanks.
