### ISSUE TITLE
Add url_prefix setting for ceph dashboard

### ISSUE THREAD

**Issue by laevilgenius** [rook/rook#1902]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add `url_prefix ` setting for ceph dashboard as described [here](http://docs.ceph.com/docs/mimic/mgr/dashboard/#reverse-proxies).

**What is use case behind this feature:**
Allows serving dashboard behind a reverse proxy under a subpath.

**Comment by jbw976** [comment]
Thanks for this idea @laevilgenius, sounds like something that could be added to the `DashboardSpec` type defined here: https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1beta1/types.go#L77

We are always accepting contributions, please feel free to take a stab at this in a pull request.  Contribution/development flow documentation can be found here: https://rook.io/docs/rook/v0.7/development-flow.html

Thanks!
