### ISSUE TITLE
Permission denied when deploying cluster.yaml with Ceph

### ISSUE THREAD

**Issue by gustavomr** [rook/rook#1911]
Hi,

I'm deploying rook with ceph following this tutorial: https://rook.github.io/docs/rook/master/ceph-quickstart.html and operator is ok, but deploying cluster.yaml I get this error:

Error message: failed to generate mon config files. failed to create keyring directory for /var/lib/rook/rook-ceph-mon0/keyring: mkdir /var/lib/rook/rook-ceph-mon0: permission denied

I saw that the directory /var/lib/rook was created at node, but describing the pod I'm getting this error. 

I'm using:

Kubernetes 1.11
Centos 7

**Comment by travisn** [comment]
@gustavomr are you running in OpenShift or other restrictive environment? If so, you likely need to set the `ROOK_HOSTPATH_REQUIRES_PRIVILEGED: true` in the operator as seen on this [page](https://rook.io/docs/rook/v0.8/openshift.html)

**Comment by gustavomr** [comment]
@travisn I'm running using virtualbox. I'm not using openshift.

**Comment by travisn** [comment]
Ok, can you check if the path is valid for `dataDirHostPath`? Likely `/var/lib/rook` is not valid. For example, in minikube you might use the path `/data/rook`.

**Comment by gustavomr** [comment]
@travisn I changed ROOK_HOSTPATH_REQUIRES_PRIVILEGED: true on operator.yaml and worked!

**Comment by travisn** [comment]
@gustavomr what type of kubernetes cluster are you running in? Is SELinux enabled? I'd like to understand why the flag was needed.

**Comment by gustavomr** [comment]
@travisn I'm using on master and nodes centos-release-7-5.1804.el7.centos.2.x86_64 and SELinux enabled. 

I checked using sestatus:

SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31

**Comment by travisn** [comment]
Ok, thanks for confirming that SELinux is enabled, that explains it.
