### ISSUE TITLE
The size is not reduced in CEPH

### ISSUE THREAD

**Issue by erickeliseo** [rook/rook#1914]
**Is this a bug report or feature request?**

Deviation from expected behavior:

Hi, I created several Cassandra, Couchbase and Elastic clusters on kubernetes and for storage I used Rook.

The inconveneinte that I have is that the size of bluestore-block is not reduced after removing the services of Cassandra, Couchbase or Elastic and their respective PVC; although I have eliminated all the PVC and RBD that I am no longer using.

I do not know if it is a problem related to ROOK or CEPH.

These tests are done with version 0.7 of rook.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core)

* Kernel (e.g. `uname -a`): Linux 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration: Phisical / Local

* Rook version (use `rook version` inside of a Rook Pod):0.7

* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Kubernetes Comminuty Edition

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
HEALTH_WARN mons rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2 are low on available space

**Comment by galexrt** [comment]
Closing as there has been no response.

It is probably that bluestore is used and bluestore does not work well with directories in terms of bluestore not "cleaning up after each itself".
