### ISSUE TITLE
rook-ceph-mgr redeploy

### ISSUE THREAD

**Issue by Ramorous** [rook/rook#1918]
I'm looking to redeploy rook-ceph-mgr-a after it was deleted/removed. I have a screenshot of configuration points and ports, but just wondering the best approach to accomplish this as the cluster is already deployed

**Comment by galexrt** [comment]
@Ramorous Restarting the Rook operator will recreate the rook-ceph-mgr Deployment and Service.

**Comment by Ramorous** [comment]
Are there any dc yaml files for rook-ceph-mgr already? Want to make sure I don't miss anything.

**Comment by galexrt** [comment]
@Ramorous What do you mean with `dc yaml files`?
The rook-ceph-mr Deployment and Service is created automatically by the Rook Ceph operator.

**Comment by Ramorous** [comment]
Is there a way to get rook-operator to recreate it with all environment variables, etc set? That's one thing I don't have a copy of.

**Comment by galexrt** [comment]
@Ramorous The Rook Ceph operator just creates it as it was newly created for a Rook Ceph cluster.
It adds the `ROOK_*` env vars as the Rook Ceph operator created it during the Rook Ceph cluster creation.

As written please try restarting the Rook Ceph operator to see that the rook-ceph-mgr Deployment and Service is recreated.

**Comment by Ramorous** [comment]
That did the trick. So far. Thanks!
