### ISSUE TITLE
Ceph Config for OSDs needs to updated on container start

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1919]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The Ceph config file is not being updated automatically (on container restart).

**Expected behavior:**
The Ceph config file being kept up-to-date all the time.

**How to reproduce it (minimal and precise):**
1. Create a Rook cluster.
1. Wait for the cluster creation to be completed.
1. As an example with custom config override, create a `rook-ceph-config-override` ConfigMap with a simple option.
1. Restart an OSD Pod.
1. Go to one of the nodes `dataDirHostPath` into an OSD dir and see that the values have not been inserted.

Only way tot update the config is to restart the Rook operator and then restart the OSD(s).

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): `v0.8.0`

As @travisn and @jbw976 talked in a meeting, `initContainers` should be used to get and generate the config parts during OSD start.

**Comment by travisn** [comment]
reopening for backport

**Comment by travisn** [comment]
Backported to 0.8 with #1969
