### ISSUE TITLE
Change the OSD Deployment updateStrategy to Recreate

### ISSUE THREAD

**Issue by galexrt** [rook/rook#1920]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When an OSD Deployment is modified right now, a new OSD Pod will be started which will crashloop at first because the old OSD Pod is still running due to the updateStrategy `rollingUpdate` used right now.

**Expected behavior:**
The current OSD Pod to terminate and then the new OSD Pod to start up.

**How to reproduce it (minimal and precise):**
Edit OSD Deployment and look at the old and new OSD Pod state.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): `v0.8.0`

For more info see #1922 (which I'm going to close as a duplicate).
Thanks to @aland-zhang for discovering this.

**Comment by travisn** [comment]
reopening for backport to 0.8

**Comment by galexrt** [comment]
Closing as the fix has been merged and backported.
