### ISSUE TITLE
Set public network and cluster network  can't access the cluster

### ISSUE THREAD

**Issue by aland-zhang** [rook/rook#1923]
Rook version (use rook version inside of a Rook Pod):
rook: v0.8.0
Kubernetes version (use kubectl version):
(using oc version instead)
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.org:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

I set rook-config-override 
 [global] 
public network = 192.168.192.0/24      
cluster network = 192.168.200.0/24

and I set  rook-ceph-mon Deployment  env:
           - name: ROOK_PRIVATE_IP
             Value: 192.168.200.153
           - name: ROOK_PUBLIC_IP
             Value: 192.168.192.153
But the port is only bound to an ROOK_PRIVATE_IP
netstat -nltp | grep 6790
tcp        0      0 192.168.200.153:6790    0.0.0.0:*               LISTEN      34641/ceph-mon
Executed by rook-ceph-tools:  ceph -s 
did not respond a long time. 
192.168.192.153 should also be bound to the 6790 port？
Rook-tools can't access the cluster。

**Comment by galexrt** [comment]
Being able to use different networks is already tracked here: #1523 and partly here #1610.
Closing this as a duplicate.

Please fill out an issue template next time.
