### ISSUE TITLE
the osd  does not automatically modify the rook.config file after modifying configmap rook-config-override

### ISSUE THREAD

**Issue by aland-zhang** [rook/rook#1924]
Rook version (use rook version inside of a Rook Pod):
rook: v0.8.0
Kubernetes version (use kubectl version):
(using oc version instead)
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master.example.org:8443
openshift v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657
Kubernetes cluster type OpenShift

After modifying configmap rook-config-override, restarting the osd pod does not automatically modify the rook.config file.
 I found osd Deployment has no env name: ROOK_CEPH_CONFIG_OVERRIDE  Value: /etc/rook/config/override.conf 
Generally, each server has 4 ssd hard disks and 20 hard disks with 10000 rpm or higher (2.1 TB/1 disk). I have 138 osd Deployment need automatically modify the rook.config file！

**Comment by galexrt** [comment]
This is tracked in #1919.
Closing as duplicate.
