### ISSUE TITLE
Should we set runAsNonRoot explicitly when false now that Kubernetes version 1.6.4 is unsupported?

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#1942]
Browsing through the code, I found the line below:

https://github.com/rook/rook/blob/986e930f5ef6fc62152090e775753813cd1d8cac/pkg/operator/ceph/cluster/osd/pod.go#L363-L365

I believe k8s 1.6 is now unsupported. Should these lines throughout the code be un-commented and changed back to `runAsNonRoot := false`?

**Comment by jbw976** [comment]
It looks that way @BlaineEXE, the fix appears to be in upstream k8s 1.7+: https://github.com/kubernetes/kubernetes/pull/47009/commits/07a67c252cacdb64da6dd951fcb0357aa1a10f75

**Comment by galexrt** [comment]
I added this to the v0.9 milestone as this seems to be a small fix to do.
@BlaineEXE Do you want to do it?

**Comment by BlaineEXE** [comment]
@galexrt Yes. I'll take it.
