### ISSUE TITLE
Paring down pod privileges

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#1944]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Reduce the privileges available to pods to the bare minimum to eliminate security vulnerabilities that may allow Rook pods to allow further intrusion into the host system(s).

**What is use case behind this feature:**
Security hardening.

-----

There are a lot of things that could be done here. When possible, we should take reasonable steps to eliminate the need of setting container privileged context to true (`spec:containers:securityContext:privileged: true`).

When we do have to set the privileged context to true, we should make use of k8s features that limit the ways that containers may be used to attack the system. "DenyEscalatingExec" is recommended by the k8s documentation. https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#denyescalatingexec We should also , perform actions that require privilege in an ephemeral job so that the system security is compromised for as little time as possible.

We should also limit container access to `/dev`. Containers should get access only to disks which they actively need. For example, Ceph OSD pod should only need access to its main osd disk and its metadata partition (or disk?). When containers to need access to `/dev`, we should take reasonable steps to allow rook to require only "readonly" access to `/dev`.

**Comment by BlaineEXE** [comment]
## Preliminary `/dev` investigation

### Testing procedure
Create a basic deployment for manually testing some of the tools that Rook uses to see if privilege can be reduced.

```test-manifest.yaml
apiVersion: extensions/v1beta1

kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    operator: rook
    storage-backend: ceph
  name: blaine-rook-ceph-agent-test
  selfLink: /apis/extensions/v1beta1/namespaces/rook-ceph-system/deployments/blaine-rook-ceph-agent-test
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: blaine-rook-ceph-agent-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blaine-rook-ceph-agent-test
    spec:
      containers:
      - args:
        - "999999999999"
        command: ["/usr/bin/sleep"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: admin:5000/ceph-amd64
        imagePullPolicy: Always
        name: blaine-rook-ceph-agent-test
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /flexmnt
          name: flexvolume
        - mountPath: /dev
          name: dev
          readOnly: true
        - mountPath: /sys
          name: sys
        - mountPath: /lib/modules
          name: libmodules
        - mountPath: /dev/vdb
          name: vdb
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-ceph-system
      serviceAccountName: rook-ceph-system
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/volume/exec/
          type: ""
        name: flexvolume
      - hostPath:
          path: /dev
          type: ""
        name: dev
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /lib/modules
          type: ""
        name: libmodules
      - hostPath:
          path: /dev/vdb
          type: ""
        name: vdb
```

1. Get a minimal Rook cluster going (mons only, no osds)
2. Use `kubectl create -n rook-ceph-system -f test-manifest.yaml` to create the deployment.
3. Attach to the test pod 'kubectl exec -it -n rook-ceph-system blaine-rook-ceph-agent-test-79476998c8-xtspd /bin/bash`

### lsblk
`lsblk` can show disk information with readonly access to `/dev`.
```
[root@blaine-dev-caasp-worker-1 /]# lsblk --all
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
vda  253:0    0  80G  0 disk 
vda1 253:1    0   2M  0 part 
vda2 253:2    0  20M  0 part 
vda3 253:3    0  80G  0 part /etc/hosts
vdb  253:16   0  10G  0 disk 
vdc  253:32   0  10G  0 disk 
vdd  253:48   0  10G  0 disk 
vde  253:64   0  10G  0 disk
```

### udevadm
`udevadm` can show disk info with readonly access to `/dev` and access to `/dev/vdb`. I did a test with /dev commented out, and RO access to `/dev` is unnecessary.
```
[root@blaine-dev-caasp-worker-1 /]# udevadm info --query=property /dev/vdb
DEVNAME=/dev/vdb
DEVPATH=/devices/pci0000:00/0000:00:06.0/virtio3/block/vdb
DEVTYPE=disk
MAJOR=253
MINOR=16
SUBSYSTEM=block
```

### sgdisk
`sgdisk` can't access `/dev/vdb` for reading in this test. I did a test with `/dev` commented out and `privileged: true`, and it succeeds. I think it could be that 'hostPath' devices do require privilege for write access.
```
[root@blaine-dev-caasp-worker-1 /]# sgdisk --zap-all /dev/vdb
Problem opening /dev/vdb for reading! Error is 1.
```
 'local' devices should allow unprivileged access to devices if/when Rook switches to using those. I don't see a good way around needing privilege until 'local' devices are available, but we are still winning even just by paring down the necessary sgdisk access to a particular device (`/dev/vdb`) instead of all of `/dev`.

**Comment by leseb** [comment]
With `ceph-volume` there is the dm aspect too, and I believe bindmounting `/dev/` is mandatory.
