### ISSUE TITLE
logging levels per package

### ISSUE THREAD

**Issue by jbw976** [rook/rook#195]
Currently with https://github.com/rook/rook/pull/192, a global log level can be set that all go packages and ceph subsystems will honor.

It would be nice if we could set logging levels per package/subsystem, e.g., clusterd logging at a different level than etcdmgr, or ceph mon subsystem logging at a different level than ceph osd subsystem.

A config file seems like a good way to control this, we could also consider env vars such as ROOKD_LOGLEVEL_*

**Comment by jbw976** [comment]
Not having this ability to specify logging level for rook packages and for ceph subsystems is making the DEBUG log spew quite hard to manage.  Implementing this would help with debugging issues (making it easier to get targeted logging)

**Comment by travisn** [comment]
our logging is quite a bit improved since this ticket and we also have other tickets such as #1033 to track the improvements.
