### ISSUE TITLE
update ceph config at runtime

### ISSUE THREAD

**Issue by jbw976** [rook/rook#196]
It would be nice if rook facilitated updating ceph config at runtime.  One example would be logging level.  Currently, we write out the ceph config file during bootstrapping, then do not touch it again.

Also, we need to look into if ceph itself supports config changes at runtime, or if a daemon recycle is needed.  I'm not sure if ceph supports that.

**Comment by bassamtabbara** [comment]
ceph supports this with inject-args through the admin socket.

**Comment by travisn** [comment]
with this being old and `mimic` moving to centralized settings, doesn't seem worth a change here.
