### ISSUE TITLE
Rook 0.8 missing many ceph-mgr prometheus metrics

### ISSUE THREAD

**Issue by fjudith** [rook/rook#1963]
**Is this a bug report or feature request?**
* Bug Report

Many metrics suchas as `ceph_client_io_write_ops`, `ceph_client_io_read_ops`  and ceph_osds_*`are still missing in Rook v0.8

**Deviation from expected behavior:**

Missing metrics

```
ceph_ods_*
ceph_monitor_*
ceph_client_*
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**

From `rook-ceph-mgr`pod, search for `ceph_client_io_write_ops` metric

```bash
curl http://localhost:9283/metrics | grep ceph_client
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04 LTS (Bionic Beaver)
* Kernel (e.g. `uname -a`): Linux proxy01 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Custom (Hetzner cloud)
* Rook version (use `rook version` inside of a Rook Pod): 0.8
* Kubernetes version (use `kubectl version`): v1.10.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): [Custom](https://github.com/fjudith/saltstack-kubernetes)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK

**Comment by fjudith** [comment]
I think i've spotted the issue.
Many of these metrics are in fact coming from [ceph-node-exporter](https://github.com/digitalocean/ceph_exporter).

I tried to implement it, but unfortunatly it relies on `ceph.conf`.
Would be great to get it implemented in rook as it allows fine [grained monitoring](https://computingforgeeks.com/monitoring-ceph-cluster-with-prometheus-and-grafana/) using prometheus and grafana

**Comment by cheethoe** [comment]
@fjudith I implemented it in my setup by using the rook toolbox as a sidecar to provide the ceph.conf
https://gist.github.com/cheethoe/40b1f2d783a7a0b84e8891dccf8b6478
Then you just have to point a prometheus servicemonitor at the service in that gist and you have yourself a working grafana dashboard.
