### ISSUE TITLE
[rook-agent] Add an option to tolerate all taint effects

### ISSUE THREAD

**Issue by laevilgenius** [rook/rook#1973]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add an option to make rook agent tolerate all taint effects, i.e.:
```yaml
tolerations:
- operator: "Exists"
```

**Comment by laevilgenius** [comment]
@galexrt Can we keep this alive?

**Comment by galexrt** [comment]
@laevilgenius I think it would be better to just use #2005 for tracking. Please go ahead and voice the need for being able to tolerate all taint effects there.
