### ISSUE TITLE
Build Rook on the controller runtime

### ISSUE THREAD

**Issue by travisn** [rook/rook#1981]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The [operator sdk](https://coreos.com/blog/introducing-operator-framework) is a better long term solution for the community. The [operator kit](https://github.com/rook/operator-kit) has not had dedicated resources and hasn't been developed in some time.

**Comment by bassam** [comment]
The other option is kubebuilder. Would be good to understand the pros/cons for each before proceeding.

**Comment by bassam** [comment]
Ignoring the dev tooling around operators, I wonder if we should focus on using the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) project instead of operator-kit as a first step. Honestly I think tools like kubebuilder, and operator-sdk might be a bit too opinionated for a project like Rook that has multiple groups/kinds, storage providers etc.

/cc @ichekrygin @jbw976

**Comment by humblec** [comment]
Indeed migrating rook to operator-sdk will be awesome! . OLM and sdk wrappers would make rook bit more readable and easy implementation.

**Comment by mykaul** [comment]
Bad bot. We still want to do it. @travisn  - can we reopen this?

**Comment by jbw976** [comment]
I don't think https://github.com/rook/rook/pull/4915 should fully close this issue, the scope of that PR seems more fine grained than this issue would require.

**Comment by leseb** [comment]
> I don't think #4915 should fully close this issue, the scope of that PR seems more fine grained than this issue would require.

Agreed, hence the `Partially close:` in the PR but it looks like Github isn't treating this the way I want :)

**Comment by travisn** [comment]
Actually I think the purpose of this issue has been completed. We have agreed to move to the controller runtime in order to improve the reliability of the rook operators. Is there any remaining question around that? I'd suggest we close this issue and open up an individual issue for each of the controllers that need to be updated so the work can be tracked appropriately. Each controller will have its own implementation and risk associated with the change. @jbw976 @leseb sound ok?

The usage of rook's operator kit was already removed with #4621, so that suggestion from the original issue description is already completed. Neither is there any plan to use the operator sdk in rook generally across all the operators. Each storage provider has the flexibility to do it already, for example as seen [here](https://github.com/rook/rook/tree/master/cluster/olm/ceph).

**Comment by jbw976** [comment]
OK that is reasonable @travisn :)

**Comment by travisn** [comment]
Ok, i'll open the individual tickets.
