### ISSUE TITLE
Flexvolume mount silently failing  [Openshift Enterprise 3.9.33]

### ISSUE THREAD

**Issue by allen13** [rook/rook#1991]
Having mounting issues in openshift 3.9 when using the flexvolume strorageclass provisioner. I have worked around this by using the traditional kubernetes.io/rbd provisioner. Additionally I have verified that the flexvolume plugin works in the recently released openshift 3.10. I would like to simply forget about this problem and move on to 3.10 but unfortunately it takes several months to upgrade our production clusters and others might run into the same issue. Willing to put in time to fix this issue myself if anyone can give me any leads.

**Deviation from expected behavior:**

Volume pretends to mount successfully but doesn't actually attach to ceph and then breaks when trying to unmount.

**Expected behavior:**
Pod successfully mounts  volume and it shows up as an rbd device (/dev/rbd0)

**How to reproduce it (minimal and precise):**

Create rook-ceph cluster on fresh install of Openshift Enterprise 3.9.33 Containerized with FLEXVOLUME_DIR_PATH=/etc/origin/kubelet-plugins/volume/exec
Create rook-ceph-block storageclass
Create test volume and run a container with mount to /var/lib/test
Container will successfully mount
Run df -ha
Mount is attached to /dev/mapper/rhel_rhel7-root which is the host
touch /var/lib/test/t1
kill pod
Unable to kill pod because of unmounting error

Log message when mounting volume:
```
MountVolume.SetUp succeeded for volume "pvc-c900eaf3-9732-11e8-9c33-080027c6ad80" (UniqueName: "flexvolume-ceph.rook.io/rook-ceph-system/cc34e6e2-9732-11e8-9c33-080027c6ad80-pvc-c900eaf3-9732-11e8-9c33-080027c6ad80") pod "rook-ceph-tools"
```

Log message when unmounting volume:
```
Aug 03 08:59:05 ocp-03 atomic-openshift-node[10903]: W0803 08:59:05.760823   10928 driver-call.go:145] FlexVolume: driver call failed: executable: /etc/origin/kubelet-plugins/volume/exec/ceph.rook.io~rook-ceph-system/rook-ceph-system, args: [unmount /var/lib/origin/openshift.local.volumes/pods/cc34e6e2-9732-11e8-9c33-080027c6ad80/volumes/ceph.rook.io~rook-ceph-system/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80], error: exit status 1, output: "2018-08-03 08:59:05.728208 I | exec: Running command: df --type ceph /var/lib/origin/openshift.local.volumes/pods/cc34e6e2-9732-11e8-9c33-080027c6ad80/volumes/ceph.rook.io~rook-ceph-system/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80\n2018-08-03 08:59:05.730747 I | df: no file systems processed\n{\"status\":\"Failure\",\"message\":\"failed to unmount volume at /var/lib/origin/openshift.local.volumes/pods/cc34e6e2-9732-11e8-9c33-080027c6ad80/volumes/ceph.rook.io~rook-ceph-system/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80: remove /var/lib/origin/openshift.local.volumes/pods/cc34e6e2-9732-11e8-9c33-080027c6ad80/volumes/ceph.rook.io~rook-ceph-system/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80: directory not empty\"}\n"
Aug 03 08:59:05 ocp-03 atomic-openshift-node[10903]: E0803 08:59:05.760970   10928 nestedpendingoperations.go:267] Operation for "\"flexvolume-ceph.rook.io/rook-ceph-system/cc34e6e2-9732-11e8-9c33-080027c6ad80-pvc-c900eaf3-9732-11e8-9c33-080027c6ad80\" (\"cc34e6e2-9732-11e8-9c33-080027c6ad80\")" failed. No retries permitted until 2018-08-03 09:00:09.760913585 -0700 PDT m=+7934.812403770 (durationBeforeRetry 1m4s). Error: "UnmountVolume.TearDown failed for volume \"test\" (UniqueName: \"flexvolume-ceph.rook.io/rook-ceph-system/cc34e6e2-9732-11e8-9c33-080027c6ad80-pvc-c900eaf3-9732-11e8-9c33-080027c6ad80\") pod \"cc34e6e2-9732-11e8-9c33-080027c6ad80\" (UID: \"cc34e6e2-9732-11e8-9c33-080027c6ad80\") : invalid character '-' after top-level value"
```

**Comment by jbw976** [comment]
Do you happen to have the full logs from the rook-ceph-agent pod on that node also?

**Comment by allen13** [comment]
Here they are. The last error repeats indefinitely.

```

2018-08-03 15:35:06.873429 I \| flexdriver: calling agent to attach volume rbd/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80
--
  | 2018-08-03 15:35:06.877045 I \| flexvolume: Creating Volume attach Resource rook-ceph-system/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80: {Image:pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 Pool:rbd ClusterNamespace:rook-ceph ClusterName: StorageClass:rook-ceph-block MountDir:/var/lib/origin/openshift.local.volumes/pods/cc34e6e2-9732-11e8-9c33-080027c6ad80/volumes/ceph.rook.io~rook-ceph-system/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 FsName: Path: RW:rw FsType: VolumeName:pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 Pod:rook-ceph-tools PodID:cc34e6e2-9732-11e8-9c33-080027c6ad80 PodNamespace:rook-ceph}
  | 2018-08-03 15:35:06.884506 I \| ceph-volumeattacher: attaching volume rbd/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 cluster rook-ceph
  | 2018-08-03 15:35:06.891682 I \| cephmon: parsing mon endpoints: rook-ceph-mon0=172.30.192.107:6790,rook-ceph-mon1=172.30.155.199:6790,rook-ceph-mon2=172.30.86.32:6790
  | 2018-08-03 15:35:06.891836 I \| op-mon: loaded: maxMonID=2, mons=map[rook-ceph-mon0:0xc4206478c0 rook-ceph-mon1:0xc420647940 rook-ceph-mon2:0xc4206479e0], mapping=&{Node:map[rook-ceph-mon0:0xc4203d82a0 rook-ceph-mon1:0xc4203d8450 rook-ceph-mon2:0xc4203d8480] Port:map[]}
  | 2018-08-03 15:35:06.892092 I \| exec: Running command: rbd map rbd/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 --id admin --cluster=rook-ceph --keyring=/tmp/rook-ceph.keyring175116050 -m 172.30.155.199:6790,172.30.86.32:6790,172.30.192.107:6790 --conf=/dev/null
  | 2018-08-03 15:35:10.878345 I \| flexdriver: E0803 08:35:07.209316   74047 mount_linux.go:140] Mount failed: exit status 32
  | Mounting command: systemd-run
  | Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 --scope -- mount -o rw,defaults /dev/rbd0 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80
  | Output: Running scope as unit run-74080.scope.
  | mount: /dev/rbd0 is write-protected, mounting read-only
  | mount: unknown filesystem type '(null)'
  |  
  | 2018-08-03 15:35:10.878773 I \| flexdriver: Ignore error about Mount failed: exit status 32. Kubernetes does this to check whether the volume has been formatted. It will format and retry again. https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/util/mount/mount_linux.go#L360
  | 2018-08-03 15:35:10.879027 I \| flexdriver: formatting volume pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 devicePath /dev/rbd0 deviceMountPath /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 fs  with options [rw]
  | 2018-08-03 15:35:10.879309 I \| flexdriver: mounting global mount path /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 on /var/lib/origin/openshift.local.volumes/pods/cc34e6e2-9732-11e8-9c33-080027c6ad80/volumes/ceph.rook.io~rook-ceph-system/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80
  | 2018-08-03 15:35:10.909210 I \| flexdriver:
  | 2018-08-03 15:35:10.909836 I \| flexdriver: volume rbd/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80 has been attached and mounted
  | 2018-08-03 15:58:00.775376 I \| flexdriver: unmounting mount dir: /var/lib/origin/openshift.local.volumes/pods/cc34e6e2-9732-11e8-9c33-080027c6ad80/volumes/ceph.rook.io~rook-ceph-system/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80
  | 2018-08-03 15:58:00.840805 I \| flexdriver:
  | 2018-08-03 15:58:01.492225 I \| flexdriver: unmounting mount dir: /var/lib/origin/openshift.local.volumes/pods/cc34e6e2-9732-11e8-9c33-080027c6ad80/volumes/ceph.rook.io~rook-ceph-system/pvc-c900eaf3-9732-11e8-9c33-080027c6ad80

```

**Comment by taemon1337** [comment]
I found the missing rbd in /var/lib/kubelet/... which is NOT mounted into the kubelet container, we use a custom /var/lib/<project>/kubelet...so is there a setting that rook/ceph uses to overwrite the default /var/lib/kubelet so it will correctly mount it back to the outside host?

**Comment by taemon1337** [comment]
So I got the rbd successfully mounted from the containerized kubelet to the host /dev/rbd0; however, the pod is STILL not using it, it still mapping the underlying logical volume. :(

**Comment by taemon1337** [comment]
https://github.com/rook/rook/issues/1330

**Comment by jmccormick2001** [comment]
I think I've hit this on ocp 3.10...using the storageclass I can create the PVC, but the Deployment fails to create a replica that uses that PVC.  If I create the pvc manually and reference it by name within
a pod it appears to work.  Here is an error from the agent log:
2018-10-11 22:52:55.227877 I | exec: Running command: rbd map replicapool/pvc-633b3973-cda8-11e8-8b69-52540096603f --id admin --cluster=rook-ceph-system --keyring=/tmp/rook-ceph-system.keyring697768531 -m 172.30.212.229:6790,172.30.190.21:6790,172.30.43.225:6790 --conf=/dev/null
2018-10-11 22:52:57.825714 I | flexdriver: E1011 18:52:55.374443   28419 mount_linux.go:151] Mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-633b3973-cda8-11e8-8b69-52540096603f --scope -- mount -t xfs -o rw,defaults /dev/rbd0 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-633b3973-cda8-11e8-8b69-52540096603f
Output: Running scope as unit run-28454.scope.
mount: wrong fs type, bad option, bad superblock on /dev/rbd0,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

2018-10-11 22:52:57.825896 I | flexdriver: Ignore error about Mount failed: exit status 32. Kubernetes does this to check whether the volume has been formatted. It will format and retry again. https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/util/mount/mount_linux.go#L360
2018-10-11 22:52:57.825966 I | flexdriver: formatting volume pvc-633b3973-cda8-11e8-8b69-52540096603f devicePath /dev/rbd0 deviceMountPath /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-633b3973-cda8-11e8-8b69-52540096603f fs xfs with options [rw]
2018-10-11 22:52:57.826034 I | flexdriver: mounting global mount path /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-633b3973-cda8-11e8-8b69-52540096603f on /var/lib/origin/openshift.local.volumes/pods/634c7652-cda8-11e8-8b69-52540096603f/volumes/ceph.rook.io~rook-ceph-system/pvc-633b3973-cda8-11e8-8b69-52540096603f
2018-10-11 22:52:57.855680 I | flexdriver: 
2018-10-11 22:52:57.855840 I | flexdriver: volume replicapool/pvc-633b3973-cda8-11e8-8b69-52540096603f has been attached and mounted

**Comment by allen13** [comment]
Since containerized kubelets are no longer supported on openshift I'm closing this issue.
