### ISSUE TITLE
FOSSA license scanning should be done on all PRs

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1993]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** The FOSSA Status license scanning should be done as a status check on every PR, to make sure that no invalid licenses are merged into master. See scan results at https://app.fossa.io/projects/git%2Bgithub.com%2Frook%2Frook

**Comment by galexrt** [comment]
@jbw976 For that to work we seem to need to manually install the FOSSA plugin on the Jenkins (see https://github.com/fossas/fossa-jenkins-plugin).

How about we reinstall the Jenkins on the latest version and then install the plugin with this task?

**Comment by bassam** [comment]
I thought there was a way to add another status check via FOSSA at the GitHub level for PR. This would not involve Jenkins which is preferable.

**Comment by galexrt** [comment]
Mhh right it seems that there is a `fossa-cli` (see https://github.com/rook/rook/pull/1441#issue-165421526) so we probably need to use that to trigger scans for PRs it seems.
