### ISSUE TITLE
Ceph config should be created with an init container

### ISSUE THREAD

**Issue by travisn** [rook/rook#2003]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The rook daemon pods that run the ceph daemons primarily have two purposes: Generate ceph config and then start the ceph daemon. Instead, an init container should be used to generate the config and then the ceph daemon can be started directly. This allows rook to get out of the business of any process management. The OSD pods recently were updated with this pattern, now we just need to update the mon, mgr, mds, and rgw daemons as well.

**Comment by travisn** [comment]
@BlaineEXE anything left for this issue? I believe we have covered it with:
- mon: #2095
- mgr: #2114
- osd: #2146
- mds: #2153
- rgw: #2191

**Comment by BlaineEXE** [comment]
I think that's everything, yes. =)

One thing I want to add just for documentation purposes is that #2193 (mdses don't scale down) is an issue that was introduced in #2153 and is a regression. That's my next development goal.
