### ISSUE TITLE
Agent and Discovery daemons should support placement options

### ISSUE THREAD

**Issue by zmlcc** [rook/rook#2005]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
[jbw976] The agent and discovery pods should support more advanced placement options, such as `nodeAffinity`, to control which nodes these pods are run on.  This could mean to not even run them at all if that's what the user desires.

**What is use case behind this feature:**
The discovery daemonset  used to collect disk information is refreshed every 30 seconds  on every node.
Usually the hard disk info of an stable cluster would not change frequently, so this behavior is not meaningful. Maybe it is enough that manually running a job to update disk information   before the first deployment of rook  or any hardware changes of the k8s cluster.

Meanwhile currently the discovery pod could only be controlled by toleration. Usually I want to specify the nodes that need to collect disk information, not the nodes that do not need to collect information. So 
I think using nodeAffinity to control discovery pod is more suitable

**Environment**:

**Comment by travisn** [comment]
@zmlcc Do you see some side effect of the frequent refresh? The idea was that we want to detect new devices that get added to a node. Certainly we need to improve this such as with a udev notification so we don't have to poll periodically.

**Comment by zmlcc** [comment]
@travisn  Actually I noticed  serious bug.  Docker overlay filesystem was broken when `docker pull image` and `sgdisk --print /dev/sdX` were executed at the same time. This bug destroyed my evevry node with kernel `4.1.0.el7.x86_64`  after I updated rook to v0.8 !!!
Fortunately, it was fixed when kernel  were upgraded to `4.14.0.el7.x86_64`

My point is that we can let  the final user to choose whether  detecting new devices automatically.   Frequent refresh on every node by default is not necessary.

**Comment by arm64b** [comment]
> Fortunately, it was fixed when kernel were upgraded to 4.14.0.el7.x86_64

@zmlcc  so is this a kernel issue?

**Comment by gtcno** [comment]
Would a simple nodeSelector environment variable for agents and discovery be enough?
Together with the toleration environment variable you can cover the following usecases:

- Run on all nodes: no tolerations/annotaitions 
- Run on dedicated nodes: label the nodes and set nodeSelector on the daemonset
- Run on on isolated, dedicated nodes(no other workloads are allowed on the nodes:  set label and 
   taint  on nodes, set nodelselector and toleration on daemon set.

**Comment by zmlcc** [comment]
@arm64b   It seems so

**Comment by jpiper** [comment]
I also encountered an issue where the discover daemon was causing disk IO issues with an application I have running. I recompiled and deployed rook without the discover daemon (by removing https://github.com/rook/rook/blob/master/pkg/operator/ceph/operator.go#L121-L124) and everything behaves as expected now. I think this feature would be good to have for those of us that have statically defined disks/directories and don't need discovery feature :)

**Comment by laevilgenius** [comment]
Also, it would be useful to be able to tolerate all taint effects, as described in #1973.

**Comment by whereisaaron** [comment]
Still an important issue

**Comment by umangachapagain** [comment]
Looking at it. Will put up a fix soon.

**Comment by davi5e** [comment]
Just to add to the current discourse, our company wishes to separate the whole Rook installation in its own Node Pool in GKE so we can use Ubuntu only in these Nodes.

If you guys need someone to test this feature, I'd be very much obliged :)

**Comment by whereisaaron** [comment]
@davi5e this was my use case too, to keep separate pool just for Ubuntu+Ceph.

Also, even if all Ubuntu, still need way to schedule only on nodes where the disks are mounted. Right now rook doesn’t support PVs. So since disks have to managed manually external to k8s, you need to be able to schedule Ceph to those specific nodes.

Since k8s doesn’t know where the Ceph local disks are, and it can’t mount the non-local disks (since they aren’t PVs), k8s can’t yet schedule Ceph services on it’s own. We need manual placement control.

**Comment by davi5e** [comment]
Is it possible to do this now? :)

@leseb

**Comment by leseb** [comment]
@davi5e yes, when Rook 1.1 will be out.
