### ISSUE TITLE
Support user-space driver

### ISSUE THREAD

**Issue by zmlcc** [rook/rook#2006]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
I have tried to use `rbd-nbd` feature-rich client to support ceph rbd image. But I noticed it was restricted by existing mechanisms. When using rbd-nbd to map rbd image,  it would create a  user-space  process to deal with network IO.  Currently ceph client map rbd image in the agent pod. If I use  `rbd-nbd`  client in the same way,  I found that
1. `rbd-nbd list-mapped` not work.  Because the  rbd-nbd process have different process id in the container and the host.
2. the rook agent became not stateless. The  rbd-nbd process would prevent agent stop/restar.

I think  any user-space driver like `rbd-nbd` would face similar problems.  Because the key reason is that the driver process is running in the container but not the host.  I hope we can build an unified architecture to support this type driver.  It is more suitable  that  any driver that use  user-space process should not  be started by the rook agent in a container， but by the flexvolume plugin in the node directly.

**What is use case behind this feature:**

**Environment**:

**Comment by galexrt** [comment]
@zmlcc I think this will be done with the Ceph CSI plugin that is currently developed.

**Comment by zmlcc** [comment]
@galexrt  If the Ceph CSI plugin was deployed in container,  I think the problem still exists

**Comment by galexrt** [comment]
@zmlcc Mhh I think this is not a problem of Rook though.

Could you please raise your concerns at the https://github.com/ceph/ceph-csi project because as far as the proposal/design for Rook to use ceph-csi is Rook would simply run the ceph-csi as is, see https://github.com/rook/rook/pull/2059.

@rootfs What do you think?

**Comment by rootfs** [comment]
I don't have rbd-nbd handy (I am running centos), @krmayankk any input? thanks.

**Comment by ianchakeres** [comment]
+ @shyam-an who's an expert.
