### ISSUE TITLE
Minio operator ignores placement in objectstores.minio.rook.io spec

### ISSUE THREAD

**Issue by jbw976** [rook/rook#2017]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** If placement information is specified in the the spec for a `objectstores.minio.rook.io` instance, then it should be applied by the operator to the minio resources that it creates.

https://github.com/rook/rook/blob/release-0.8/pkg/apis/minio.rook.io/v1alpha1/types.go#L56

**Comment by agill17** [comment]
+1 Would appreciate this!
