### ISSUE TITLE
Minio object store creation failure due to unspecified storage class in rook 0.8.1

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#2022]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The minio object store pod can't be brought up ( Pending state)  successfully. 
It looks for the unspecified storageclass as stated in the ceph-operator log. 

$ kubectl -n rook-minio get all 
NAME                   READY     STATUS    RESTARTS   AGE
pod/my-minio-store-0   0/1       Pending   0          2m

NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/minio-service    NodePort    10.254.50.134   <none>        9000:31875/TCP   2m
service/my-minio-store   ClusterIP   None            <none>        9000/TCP         2m

NAME                              DESIRED   CURRENT   AGE
statefulset.apps/my-minio-store   4         1         2m

$ kubectl -n rook-minio describe pod  my-minio-store-0
Name:               my-minio-store-0
Namespace:          rook-minio
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=minio
                    controller-revision-hash=my-minio-store-c8cbd5bc
                    statefulset.kubernetes.io/pod-name=my-minio-store-0
Annotations:        kubernetes.io/psp=privileged
Status:             Pending
IP:                 
Controlled By:      StatefulSet/my-minio-store
Containers:
  minio:
    Image:      rook/minio:v0.8.1
    Port:       9000/TCP
    Host Port:  0/TCP
    Command:
      /usr/bin/minio
    Args:
      server
      http://my-minio-store-0.my-minio-store.rook-minio/data
      http://my-minio-store-1.my-minio-store.rook-minio/data
      http://my-minio-store-2.my-minio-store.rook-minio/data
      http://my-minio-store-3.my-minio-store.rook-minio/data
    Environment:
      MINIO_ACCESS_KEY:  TEMP_DEMO_ACCESS_KEY
      MINIO_SECRET_KEY:  TEMP_DEMO_SECRET_KEY
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lzdq2 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-my-minio-store-0
    ReadOnly:   false
  default-token-lzdq2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lzdq2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  3m (x25 over 3m)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 3 times)

$ kubectl -n rook-ceph-system logs rook-ceph-operator-5cb478f65-5rgkj
...
E0813 16:14:34.085405       7 controller.go:584] Error getting claim "rook-minio/data-my-minio-store-0"'s StorageClass's fields: StorageClass "" not found
E0813 16:14:38.668475       7 controller.go:584] Error getting claim "rook-minio/data-my-minio-store-0"'s StorageClass's fields: StorageClass "" not found
E0813 16:14:49.085642       7 controller.go:584] Error getting claim "rook-minio/data-my-minio-store-0"'s StorageClass's fields: StorageClass "" not found
E0813 16:14:53.668647       7 controller.go:584] Error getting claim "rook-minio/data-my-minio-store-0"'s StorageClass's fields: StorageClass "" not found

**Expected behavior:**

**How to reproduce it (minimal and precise):**

Follow procedure  https://rook.io/docs/rook/v0.8/minio-object-store.html
kubectl create -f operator.yaml
kubectl create -f object-store.yaml

**Environment**:
* OS (e.g. from /etc/os-release):

- NAME="Red Hat Enterprise Linux Serer"
- VERSION="7.5 (Maipo)"
- ID="rhel"
- ID_LIKE="fedora"

* Kernel (e.g. `uname -a`):
Linux bcmt1-01 3.10.0-862.2.3.el7.x86_64 #1 SMP Mon Apr 30 12:37:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
openstack
* Rook version (use `rook version` inside of a Rook Pod):
0.8.1
* Kubernetes version (use `kubectl version`):

- Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

- Tectonic

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html))
[root@rook-ceph-tools /]# ceph -s
  cluster:
    id:     7ea5a033-037f-4aad-b39c-fbe08656a3ed
    health: HEALTH_WARN
            mons rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2 are low on available space
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon1,rook-ceph-mon2,rook-ceph-mon0
    mgr: a(active)
    osd: 9 osds: 9 up, 9 in
 
  data:
    pools:   2 pools, 200 pgs
    objects: 0 objects, 0 bytes
    usage:   55460 MB used, 13457 MB / 68917 MB avail
    pgs:     200 active+clean

**Comment by jbw976** [comment]
Thanks for reporting this! This is very similar to the issue that cockroachdb has when there is no default storageClass.  Relevant discussion can be found on #1807.

**Comment by yanchicago** [comment]
Followed #1807 to create the default storage class:
$ kubectl get sc
NAME                 PROVISIONER   AGE
hostpath (default)   hostpath      15m

$ kubectl get all -n rook-minio
NAME                   READY     STATUS    RESTARTS   AGE
pod/my-minio-store-0   0/1       Pending   0          33s

NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/minio-service    NodePort    10.254.55.248   <none>        9000:30266/TCP   34s
service/my-minio-store   ClusterIP   None            <none>        9000/TCP         34s

NAME                              DESIRED   CURRENT   AGE
statefulset.apps/my-minio-store   4         1         34s
$ kubectl -n rook-minio describe pod my-minio-store-0
Name:               my-minio-store-0
Namespace:          rook-minio
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=minio
                    controller-revision-hash=my-minio-store-c8cbd5bc
                    statefulset.kubernetes.io/pod-name=my-minio-store-0
Annotations:        kubernetes.io/psp=privileged
Status:             Pending
IP:                 
Controlled By:      StatefulSet/my-minio-store
Containers:
  minio:
    Image:      rook/minio:v0.8.1
    Port:       9000/TCP
    Host Port:  0/TCP
    Command:
      /usr/bin/minio
    Args:
      server
      http://my-minio-store-0.my-minio-store.rook-minio/data
      http://my-minio-store-1.my-minio-store.rook-minio/data
      http://my-minio-store-2.my-minio-store.rook-minio/data
      http://my-minio-store-3.my-minio-store.rook-minio/data
    Environment:
      MINIO_ACCESS_KEY:  TEMP_DEMO_ACCESS_KEY
      MINIO_SECRET_KEY:  TEMP_DEMO_SECRET_KEY
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zhtpf (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-my-minio-store-0
    ReadOnly:   false
  default-token-zhtpf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zhtpf
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  33s (x25 over 40s)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 3 times)
