### ISSUE TITLE
Procedure for Cluster Downscale

### ISSUE THREAD

**Issue by vvangestel** [rook/rook#2025]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Document the procedure to cleanly reduce the size of the ceph cluster.
If manual steps are required, maybe add support for a node annotation to indicate to the operator that a specific node should be cleaned up (no longer used for storage).

**What is use case behind this feature:**
Cleanly remove faulty/unused/... hardware, without simply pulling the plug and hoping the cluster won't care.
A controlled eviction can also be used to schedule/force data migration, while still allowing the machine to be functional.

**Environment**:

We are using ceph block devices.

**Comment by jbw976** [comment]
Thanks for this suggestion @vvangestel.  Do you think this issue is describing anything beyond what #1827 is already attempting to capture? I'd like to consolidate these tickets if possible, but there may be a clear difference between them.
