### ISSUE TITLE
adding drives on nodes without persitent storage fails to rediscover previous osds

### ISSUE THREAD

**Issue by jansmets** [rook/rook#2034]
Rook version: 0.8.1
I have one node (named node2) with 3 drives. They originally were on  sda/sdb/sdc This is a CoreOS/containerlinux booted node without any persistent storage. I previously tested that (pre-0.8) that OSD pods came up perfectly fine when that node was rebooted.

Today I wanted to insert another drive to provide persistent storage for rook/ceph. This is primarly for the MON data to be able to recover from cluster-wide failure where all nodes go down at the same time.

Thus, the added drive is being seated at location sda, where then the other drives become sdb/sdc/sdd.

That fails the osd pods to start:

# kubectl -n rook-ceph logs rook-ceph-osd-id-0-5cc758d7b6-sbqrc  
2018-08-16 12:56:17.503900 7f18f73d1d80 -1 bluestore(/var/lib/rook/osd0/block) _read_bdev_label failed to open /var/lib/rook/osd0/block: (2) No such file or directory  
2018-08-16 12:56:17.503934 7f18f73d1d80 -1  ** ERROR: unable to open OSD superblock on /var/lib/rook/osd0: (2) No such file or directory  
2018-08-16 12:56:17.503785 7f18f73d1d80  0 ceph version 12.2.7 (3ec878d1e53e1aeb47a9f619c49d9e7c0aa384d5) luminous (stable), process ceph-osd, pid 14938  
2018-08-16 12:56:17.503900 7f18f73d1d80 -1 bluestore(/var/lib/rook/osd0/block) _read_bdev_label failed to open /var/lib/rook/osd0/block: (2) No such file or directory  
2018-08-16 12:56:17.503934 7f18f73d1d80 -1  ** ERROR: unable to open OSD superblock on /var/lib/rook/osd0: (2) No such file or directory  

The cluster.yaml is similar to the example one provided in the documentation, except for
spec:
  dataDirHostPath: /mnt/persistent-volume/rook/var/lib/rook
 storage:  
    useAllNodes: false
    useAllDevices: true
    config:
      storeType: bluestore
    nodes:
    - name: "node2"
    - name: "node3"
    - name: "node4"
    - name: "node5"

rook-discover on node2

 rook-discover: available devices: [{Name:sdd Parent: HasChildren:false DevLinks:/dev/disk/by-id/ata-ST2000NM0011_Z1P48WR3 /dev/disk/by-id/wwn-0x5000c5004ee67703 /dev/disk/by-path/pci-0000:00:1f.2-ata-4 Size:2000398934016 UUID:170a5eb4-23eb-4d5e-babc-1285a93d6387 Serial:ST2000NM0011_Z1P48WR3 Type:disk Rotational:true Readonly:false Partitions:[{Name:sdd2 Size:21474836480 Label:ROOK-OSD3-DB Filesystem:} {Name:sdd3 Size:1978319052288 Label:ROOK-OSD3-BLOCK Filesystem:} {Name:sdd1 Size:603979776 Label:ROOK-OSD3-WAL Filesystem:}] Filesystem: Vendor: Model:ST2000NM0011 WWN:0x5000c5004ee67703 WWNVendorExtension:0x5000c5004ee67703 Empty:false} {Name:sdb Parent: HasChildren:false DevLinks:/dev/disk/by-id/ata-ST32000645NS_Z292RMLZ /dev/disk/by-id/wwn-0x5000c5004d2cf9e5 /dev/disk/by-path/pci-0000:00:1f.2-ata-2 Size:2000398934016 UUID:cecdd4b9-8100-4acb-ac1e-b604731dc177 Serial:ST32000645NS_Z292RMLZ Type:disk Rotational:true Readonly:false Partitions:[{Name:sdb2 Size:21474836480 Label:ROOK-OSD5-DB Filesystem:} {Name:sdb3 Size:1978319052288 Label:ROOK-OSD5-BLOCK Filesystem:} {Name:sdb1 Size:603979776 Label:ROOK-OSD5-WAL Filesystem:}] Filesystem: Vendor: Model:ST32000645NS WWN:0x5000c5004d2cf9e5 WWNVendorExtension:0x5000c5004d2cf9e5 Empty:false} {Name:sdc Parent: HasChildren:false DevLinks:/dev/disk/by-id/ata-ST32000645NS_Z295CDEW /dev/disk/by-id/wwn-0x5000c5004efbdcc5 /dev/disk/by-path/pci-0000:00:1f.2-ata-3 Size:2000398934016 UUID:8d69e346-10f1-428a-a505-f4c5dce3b844 Serial:ST32000645NS_Z295CDEW Type:disk Rotational:true Readonly:false Partitions:[{Name:sdc2 Size:21474836480 Label:ROOK-OSD0-DB Filesystem:} {Name:sdc3 Size:1978319052288 Label:ROOK-OSD0-BLOCK Filesystem:} {Name:sdc1 Size:603979776 Label:ROOK-OSD0-WAL Filesystem:}] Filesystem: Vendor: Model:ST32000645NS WWN:0x5000c5004efbdcc5 WWNVendorExtension:0x5000c5004efbdcc5 Empty:false}]

The config map of node2  (rook-ceph-osd-node2-config)

  partition-scheme: '{"metadata":null,"entries":[{"id":0,"osdUuid":"ad112628-b083-45c3-9b17-3d9d6550eb85","partitions":{"0":{"device":"sdb","diskUuid":"8d69e346-10f1-428a-a505-f4c5dce3b844","partitionUuid":"e1729d70-3cef-47c7-96a1-38667085153f","sizeMB":576,"offsetMB":1},"1":{"device":"sdb","diskUuid":"8d69e346-10f1-428a-a505-f4c5dce3b844","partitionUuid":"7f6a49a1-9eb9-4ad8-85aa-63f6a7b7ab14","sizeMB":20480,"offsetMB":577},"2":{"device":"sdb","diskUuid":"8d69e346-10f1-428a-a505-f4c5dce3b844","partitionUuid":"bad2cb46-7cce-4c5b-96a0-a1418f330836","sizeMB":-1,"offsetMB":21057}},"storeType":"bluestore","fsCreated":true},{"id":3,"osdUuid":"5559c34b-393f-48e5-8fe3-29d808d2b21c","partitions":{"0":{"device":"sdc","diskUuid":"170a5eb4-23eb-4d5e-babc-1285a93d6387","partitionUuid":"fcf3c14c-40ef-46ba-b6b4-e46cbad9b72d","sizeMB":576,"offsetMB":1},"1":{"device":"sdc","diskUuid":"170a5eb4-23eb-4d5e-babc-1285a93d6387","partitionUuid":"c3cf4f8e-c034-45e7-b19d-0ceda90139b2","sizeMB":20480,"offsetMB":577},"2":{"device":"sdc","diskUuid":"170a5eb4-23eb-4d5e-babc-1285a93d6387","partitionUuid":"e07a9e6e-351c-42f7-b534-aa03314627cc","sizeMB":-1,"offsetMB":21057}},"storeType":"bluestore","fsCreated":true},{"id":5,"osdUuid":"89d0bfcf-923d-4e06-879f-d4e04a93ec5f","partitions":{"0":{"device":"sda","diskUuid":"cecdd4b9-8100-4acb-ac1e-b604731dc177","partitionUuid":"44f4e8a5-ea64-4263-9412-000b30b5f0ab","sizeMB":576,"offsetMB":1},"1":{"device":"sda","diskUuid":"cecdd4b9-8100-4acb-ac1e-b604731dc177","partitionUuid":"f3ee19a4-20bf-4666-a994-a943e479bd73","sizeMB":20480,"offsetMB":577},"2":{"device":"sda","diskUuid":"cecdd4b9-8100-4acb-ac1e-b604731dc177","partitionUuid":"ae9b3128-714b-4703-bfc3-07c256f6e399","sizeMB":-1,"offsetMB":21057}},"storeType":"bluestore","fsCreated":true}]}'

The OSD-UUID (ad112628-b083-45c3-9b17-3d9d6550eb85) matches the --osd-uuid used in the OSD pods. The disk and partition UUIDs match, but not the device names (sda/sdb/sdc).

Any help is appreciated in getting this back up.

Thank you.

**Comment by lbogdan** [comment]
Afaik, rook needs `/var/lib/rook` to be persistent on the OSD nodes, hence the error `[...] failed to open /var/lib/rook/osd0/block: (2) No such file or directory`. I think what happened is editing the operator led to the operator restarting, which in turn led to running the OSD prepare job, which recovered the *lost* OSD dirs in `/var/lib/rook/osdID`.

**Comment by jansmets** [comment]
but if /block{.wal,.db} is missing it can look at it's ceph-config in the osd directory, or at the cluster cm, (rook-ceph-osd-<xyz>-config). 
All the info is there, so I don't see the requirement for persistent storage for OSD's.

**Comment by lbogdan** [comment]
That's how it works now - when an OSD starts, the init container only (re)generates `/var/lib/rook/osdID/rook-ceph.config` (and copies it to `/etc/ceph/ceph.conf`), although you're right, it has all the info to regenerate **all** required files in `/var/lib/rook/osdID`, if they are missing. Maybe open a feature request issue?
