### ISSUE TITLE
Integration test to check the support for more than one export in NFS server.

### ISSUE THREAD

**Issue by rohan47** [rook/rook#2038]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The Rook NFS operator supports multiple exports per NFS server.
This feature should add integration tests to verify the support for more than one export per NFS server as per [NFS CRD design](https://github.com/rook/rook/blob/master/design/nfs.md#nfs-crd)

**What is use case behind this feature:**
This feature will ensure that multiple exports in NFS server is well tested.

**Comment by jbw976** [comment]
it looks like the NFS operator also iterates through all the given export specs, implying that multiple exports are supported: https://github.com/rook/rook/blob/master/pkg/operator/nfs/controller.go#L120

what other work to support multiple exports would there be remaining @rohan47?

**Comment by rohan47** [comment]
Sorry for the late response.
@MartinForReal I tried out multiple exports with a similar resource definition like the one you mentioned and it works fine. Multiple exports are supported as mentioned by  @jbw976 .

@jbw976 there should be integration tests to confirm the same.

**Comment by nemesis09** [comment]
Can I work on this issue, if no one is already working?

**Comment by rohan47** [comment]
https://github.com/rook/rook/blob/master/tests/framework/installer/nfs_manifests.go#L174 adding a new export here and making necessary changes will help.

**Comment by rohan47** [comment]
@nemesis09 are you working on this?

**Comment by nemesis09** [comment]
Hi rohan47,
Sorry for the delay from my side. Yes I am working on it. But I was stuck in some personal emergency and exams. So I would need some more time. Please assign the issue to someone else if I am harming the pace of the project.
Sorry for the inconvenience caused due to me.

**Comment by ashishranjan738** [comment]
Hi @rohan47 @jbw976 can i work on this
