### ISSUE TITLE
Warning  FailedMount MountVolume.SetUp failed for volume

### ISSUE THREAD

**Issue by mailtoraja18** [rook/rook#2039]
Hello , I setup rook on aws kops cluster with local persistance. Get the below issue when i try to mount the pv claim to an image. 

Warning  FailedMount            18s (x14 over 12m)  kubelet, ip-172-20-39-84.ec2.internal  MountVolume.SetUp failed for volume "pvc-33b41077-a17e-11e8-a060-0ef229784bb2" : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd1 [xfs] to /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-33b41077-a17e-11e8-a060-0ef229784bb2, error executable file not found in $PATH

How should I solve the issue. Thanks

**Comment by lbogdan** [comment]
Check if you have a `rook-ceph-agent-xxx` (in the `rook-ceph-system` namespace) running on the node on which the pod trying to mount the PVC is scheduled, and look at its logs for more info on why the mount failed.

**Comment by lbogdan** [comment]
Looks like it can't format it on first use, you need `mkfs.xfs` (it's in the package `xfsprogs` in Ubuntu) on all nodes you want to mount rook-ceph PVCs.

**Comment by mailtoraja18** [comment]
Installed xfsprogs on the nodes and now the pods are running fine. Thanks

**Comment by lbogdan** [comment]
Nice!

I'm gonna close this, if you have further issues also take a look at the [Common Issues](https://rook.io/docs/rook/v0.8/common-issues.html) section of the documentation.
