### ISSUE TITLE
Update K8s minimum version supported by Rook from 1.7 to 1.8

### ISSUE THREAD

**Issue by travisn** [rook/rook#2040]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Given the dwindling user base on 1.7 especially in the timeframe that Rook 0.9 would be released, there is not a compelling reason to keep supporting 1.7. There is some support/dev cost to maintaining each release. As an example, #1995 would require test code to workaround a feature that is not available in 1.7.

At the same time as this change, the pre-req page should be updated with the notes from a recent community discussion on the min version that rook supports.
```
We are not keeping with the client-go matrix anymore since we don’t support older than 1.7 and that’s OK. Our docs do not state a policy to keep with client-go.  At a minimum, the newest 3-4 versions of k8s should be supported and when we consider dropping a version it needs to be discussed and rationalized for a good reason with expected minimal impact to our users.
```

**Comment by bassam** [comment]
what version of Kubernetes do OpenShift support?

**Comment by jbw976** [comment]
The latest Openshift Origin 3.10 and Openshift Container Platform 3.10 use Kubernetes 1.10 according to the [Openshift docs](https://docs.openshift.com/container-platform/3.10/architecture/infrastructure_components/kubernetes_infrastructure.html#overview).

Openshift 3.7, which was [released Nov 2017](https://github.com/openshift/origin/releases/tag/v3.7.0), uses [Kubernetes 1.7](https://docs.openshift.com/container-platform/3.7/architecture/infrastructure_components/kubernetes_infrastructure.html).

Older versions of Openshift use even older versions of Kubernetes, but I do not know the adoption percentages of the various versions.
