### ISSUE TITLE
After upgrade the cluster CRD still exists

### ISSUE THREAD

**Issue by dimm0** [rook/rook#2041]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After upgrading from 0.7.1 to 0.8.1, I see:

```
(⎈ |nautilus:rook)dimm:~ dimm$  kubectl -n rook get clusters.rook.io
NAME      AGE
rook      133d
```

**Expected behavior:**
```
$kubectl -n rook get clusters.rook.io
No resources found
```

**Environment**:
* Cloud provider or hardware configuration:
kubeadm, baremetal
* Kubernetes version (use `kubectl version`):
0.11.2

**Comment by jbw976** [comment]
As per https://rook.io/docs/rook/v0.8/upgrade.html#legacy-custom-resource-definitions-crds, the operator should have migrated and cleaned up the legacy `clusters.rook.io` instances.  Do you have your operator logs to see what might be happening?

**Comment by dimm0** [comment]
Could be related to https://github.com/rook/rook/issues/2043

**Comment by dimm0** [comment]
[op.logs.gz](https://github.com/rook/rook/files/2295824/op.logs.gz)

**Comment by dimm0** [comment]
Found this in controller logs:

`E0820 23:53:31.577505       1 garbagecollector.go:617] removeOrphanFinalizer for [v1alpha1/Cluster, namespace: rook, name: rook, uid: 4dd7a505-3913-11e8-96aa-0cc47a6be994] failed with cannot finalize owner [v1alpha1/Cluster, namespace: rook, name: rook, uid: 4dd7a505-3913-11e8-96aa-0cc47a6be994], because cannot get it: unable to get REST mapping for v1alpha1/Cluster.. The garbage collector will retry later.`

Can I delete one by hand?

**Comment by dimm0** [comment]
I did not read the docs right. The instances were gone, and I had to delete the CRD definitions manually. Closing the tocket.
