### ISSUE TITLE
BeeGFS support?

### ISSUE THREAD

**Issue by dimm0** [rook/rook#2042]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Did you think about adding the support for external BeeGFS cluster as a Persistent Volume?

**What is use case behind this feature:**
Attach to existing BeeGFS clusters

**Comment by jbw976** [comment]
hi @dimm0, what would be needed here for the support that you envision? You said external BeeGFS cluster, so would Rook not be involved in the orchestration/deployment of that cluster at all?  Are you looking for the dynamic provisioning and attaching/detaching parts?

**Comment by dimm0** [comment]
Right, currently I'm looking for a way to attach an external BeeGFS storage to the pods, and the problem is that BeeGFS requires clients to have UDP ports open from outside. So seems like it would require writing some CSI plugins, installing kernel modules, etc, all what you currently have for ceph.

Creating a BeeGFS cluster inside kubernetes is another cool option, and we'll find a use for it as well. Would be nice to compare features and speed with ceph storage.

**Comment by dimm0** [comment]
I'm trying to figure how to make this possible: https://www.beegfs.io/wiki/NetworkTuning#hn_59ca4f8bbb_4

Also I've found a docker BeeGFS volume implementation: https://github.com/RedCoolBeans/docker-volume-beegfs

**Comment by dimm0** [comment]
Still interested in seeing this

**Comment by pavgup** [comment]
I'm also interested in this, but it looks like this may be better handled outside of Rook? New CSI? Perhaps chasing the flexvolume deprecation to hack around this? To be fair, I could see Rook implementing the full beegfs setup, but I suspect that's a larger project...

**Comment by edubergeek** [comment]
Me too - please reopen for further discussion
