### ISSUE TITLE
support glusterfs

### ISSUE THREAD

**Issue by MartinForReal** [rook/rook#2044]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
rook operator can provision glusterfs cluster on k8s
**What is use case behind this feature:**
glusterfs consumes less resource(cpu memory) but still takes time to manage a cluster 
**Environment**:
on k8s environment.

**Comment by jbw976** [comment]
+1, I would love to see support for Gluster in Rook as well! There has been discussion in the past about this and I know there was some enthusiasm and demand.  Adding the "help wanted" label to hopefully get an owner for this.

**Comment by MartinForReal** [comment]
I would like to write a draft for crd definition.

**Comment by travisn** [comment]
@MartinForReal great to hear of your interest in this. Before you go too far, @JohnStrunk and @jarrpa have been working on an operator and crd for gluster and we have been discussing integration with Rook.

**Comment by MartinForReal** [comment]
I don't find any document or discussion for record. Could you please share your idea with me? @Johnstruct @jarrpa Thank you!

**Comment by rohan47** [comment]
I came across this old google doc. Not sure if this is still being considered. https://docs.google.com/document/d/13-xsk0DazYCWrsgXqnEEOYMbiqQJxL1GV6dWTpqGvwM/edit#heading=h.sp44z9itvyja

**Comment by obnoxxx** [comment]
Nice to see some interest here! Let's get discussing about possible approaches and designs, etc. 

@rohan47 writes:
> I came across this old google doc. Not sure if this is still being considered. https://docs.google.com/document/d/13-xsk0DazYCWrsgXqnEEOYMbiqQJxL1GV6dWTpqGvwM/edit#heading=h.sp44z9itvyja

Well, there are certainly several good starting points in that doc. One of the main problems originally, were (imho) that there were a couple of misconceptions or just lack of context, where we want to move with gluster. My main point of criticism for the originial document was that its proposal tries to replace several core aspects of gluster. This would render gluster unusable outside of kubernetes, or at least you would have to spend duplicate effort to keep it usable there. Our approach from gluster is to keep the core business logic close to gluster core. That includes higher level functionality like disk management, intelligent volume provisioning and day-2 operations. In the currently released world this includes the heketi component (https://github.com/heketi/heketi), but that functionality will merge with a rewritten glusterd component of gluster (https://github.com/gluster/glusterd2).  In my opinion, the operator should not implement these core aspects but reach out to them. The operator should gather the facts to take decisions on when to call which of these core functionalities. If we can agree roughly on those primitives, then we should well pursue the project of integrating a gluster operator with rook!

This is currently supposed to become the home of the gluster operator: https://github.com/gluster/anthill

And this is @jarrpa's current prototype: https://github.com/jarrpa/anthill

**Comment by bassam** [comment]
@obnoxxx the document predates glusterD2 and I agree that we should explore using glusterd2. One question that came up with the use of heketi was it's need for a backing store for it's own config. Does glusterd2 require a backing store for config too?

**Comment by obnoxxx** [comment]
@bassam writes:
> @obnoxxx the document predates glusterD2 and I agree that we should explore using glusterd2.

Is the document more than 3 years old? (glusterd2 was started in 2015. ;-) )

But glusterd2 was not in a product then, and it is not yet. It will take some time until it is. It just made it into upstream gluster 4.0 as a tech perview feature, so yeah, in that sense glusterd2 is now more there than it was before.

> One question that came up with the use of heketi was it's need for a backing store for it's own config. 

Well, we can change almost antyhing. But heketi needs to store some state.  Let me put the problem in different terms: The main problem we hat with heketi and gluster so far is that there are two places of state, one in heketi and one in gluster, and that content has some overlap. We've been working on reducing the effects.

> Does glusterd2 require a backing store for config too?

It uses an etcd to store state internal to gluster.

What's the main issue with a store for internal state of the application?

**Comment by MartinForReal** [comment]
> What's the main issue with a store for internal state of the application?

I think this internal storage makes it harder for storage controller (heketi in this case) to achieve HA
I've opened https://github.com/heketi/heketi/issues/1333 #

**Comment by obnoxxx** [comment]
@MartinForReal writes:
> @obnoxxx writes:
> > What's the main issue with a store for internal state of the application?
> 
> I think this internal storage makes it harder for storage controller (heketi in this case) to achieve HA

Well first of all, heketi is not a storage controller in the more narrow kubernetes sense, but it is a component of core gluster which in this case runs inside kubernetes. :-)

Can you be more specific how this makes it more difficult to achieve HA?

We currently have two (kind of hacky) ways to achieve HA, both based on where to store that internal state:
1. store the db on a distributed storage, in our case a gluster volume itself
2. sync the db to a kubernetes secret

> I've opened heketi/heketi#1333

Yeah it's perfectly valid to request different storage backends for the internal state. It will be some good amount of work to abstract it out though. Glusterd2 will use etcd (it's own instance) to store its state.

**Comment by MartinForReal** [comment]
> Can you be more specific how this makes it more difficult to achieve HA?

heketi use boltdb to store metadata (such as cluster info, node info, device list and bricks list). And boltdb can't be opened by two or more process at the same time. So we can't use share db pattern ( which is not a good way to achieve ha).

**Comment by MartinForReal** [comment]
I think it is reasonable to wait until glusterd2 is stable and released.

**Comment by q2dg** [comment]
Well, glusterd2 reached v5.0 past year. Maybe it's "stable and relased" already.
On the other hand, please disable the stale bot: it does much more harm than good.

**Comment by travisn** [comment]
While the stale bot may be aggressive, it's a way to prune work that nobody is picking up. If nobody is actively work on this feature request, then why keep it open? In this case, we need somebody from the community to step up and do the design and implementation work. @MartinForReal @q2dg If you're volunteering for this effort, then we can certainly reopen it.

For bugs, I fully agree that we need to make sure the bot isn't closing them when we should be fixing them.

**Comment by TomaszKlosinski** [comment]
So you're not planning to implement this?

**Comment by travisn** [comment]
Current members of the Rook community are not involved with Gluster, so we would need someone interested in developing a Gluster operator to join. Contributions always welcome!

**Comment by tangjiaxing669** [comment]
Sorry, don't you plan to support gluster at the moment?

**Comment by travisn** [comment]
@tangjiaxing669 Each storage provider really requires a dedicated team to implement and support its operator, which has not materialized for Gluster.
