### ISSUE TITLE
LVM devices aren't picked up

### ISSUE THREAD

**Issue by rclsilver** [rook/rook#2047]
**Bug Report**
LVM devices aren't picked up by monitor. 

Discovering logs: [discover.txt](https://github.com/rook/rook/files/2297148/discover.txt)

```
# lsblk --all  --list --output KNAME,TYPE,PKNAME,NAME | grep rook_device01
dm-4  lvm   md127  vg00-rook_device01
dm-4  lvm   md127  vg00-rook_device01
# lsblk /dev/dm-4 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
SIZE="107374182400" ROTA="1" RO="0" TYPE="lvm" PKNAME=""
```

**Expected behavior:**
LVM devices added.

**How to reproduce it (minimal and precise):**
```
# lvcreate -n rook_device01 -L 100G vg00
# wipefs --all --force /dev/vg00/rook_device01
$ kubectl create -f https://raw.githubusercontent.com/rook/rook/v0.8.1/cluster/examples/kubernetes/ceph/operator.yaml
$ kubectl create -f https://raw.githubusercontent.com/rook/rook/v0.8.1/cluster/examples/kubernetes/ceph/cluster.yaml
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

* Kernel (e.g. `uname -a`):
```Linux proliant.chatillon.mydomain.net 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

* Cloud provider or hardware configuration: hardware

* Rook version (use `rook version` inside of a Rook Pod): v0.8.1

* Kubernetes version (use `kubectl version`): v1.10.5

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): rancher 2.0.6

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): 
```
# ceph status
Cluster connection interrupted or timed out
```

**Comment by voron** [comment]
It looks like a missing `sys.LVMType` in [disk.go#L79](https://github.com/rook/rook/blob/1e8ff26a52cf15dad227575d5e8889ce318551e1/pkg/clusterd/disk.go#L79) to me

**Comment by danielcb** [comment]
Had a look at this, but with only limited understanding of ceph I'm stuck. As far as I understand it the correct way of deploying OSDs on LVM volumes seems to be ceph-volume (currently ceph-osd is used, when bypassing the mentioned `sys.LVMType` problem) which is also on the 0.9 roadmap. So, at least as far as I could test it, it's not as simple as fixing the check in `disk.go`.

**Comment by travisn** [comment]
This will be dependent on #1342

**Comment by travisn** [comment]
unfortunately need to move this to 1.0 as it is going to take more time than we have for 0.9

**Comment by davidkarlsen** [comment]
related to https://github.com/rook/rook/issues/1228

**Comment by clkao** [comment]
It appears #2100 code still applies cleanly (except pending notes) to master. we should probably revisit it and see if that would allow lvm.

**Comment by Informatic** [comment]
Took a look at it today - rebasing #2100 onto current master makes rook see LVM device-mapper devices, but, these need to be passed in configuration as `dm-0` (which would be much more likely to change in contrast to physical disk device names, as per #1228)

Additionally during provisioning ceph-volume seems to still fail with incomprehensible error:
```
2019-06-20 18:51:03.293452 I | exec: Running command: udevadm info --query=property /dev/sda
2019-06-20 18:51:03.297413 I | cephosd: skipping device sda that is in use (not by rook). fs: , ownPartitions: false
2019-06-20 18:51:03.297461 I | exec: Running command: lsblk /dev/dm-0 --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2019-06-20 18:51:03.300014 I | exec: Running command: udevadm info --query=property /dev/dm-0
2019-06-20 18:51:03.303236 I | cephosd: skipping device dm-0 that does not match the device filter/list ([{dm-1 1 false}]). <nil>
2019-06-20 18:51:03.315283 I | cephosd: configuring osd devices: {"Entries":{"dm-1":{"Data":-1,"Metadata":null,"Config":{"Name":"dm-1","OSDsPerDevice":1,"IsFilter":false},"LegacyPartitionsFound":false}}}                                                                                                                    
2019-06-20 18:51:03.315320 I | exec: Running command: ceph-volume lvm batch --prepare
2019-06-20 18:51:05.301345 I | cephosd: device dm-1 to be configured by ceph-volume
2019-06-20 18:51:05.301397 I | cephosd: 0/0 pre-ceph-volume osd devices succeeded on this node
2019-06-20 18:51:05.301835 I | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=ceph-waw1 --conf=/var/lib/rook/ceph-waw1/ceph-waw1.config --keyring=/var/lib/rook/ceph-waw1/client.admin.keyring --format json --out-file /tmp/907142160 
2019-06-20 18:51:06.114808 I | cephosd: configuring new device dm-1
2019-06-20 18:51:06.114912 I | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes /dev/dm-1 --osds-per-device 1 --report
2019-06-20 18:51:11.489574 I | -->  KeyError: 'rotational'
failed to configure devices. failed to configure devices with ceph-volume. failed to initialize devices. failed ceph-volume report. Failed to complete '': exit status 1.```

**Comment by leseb** [comment]
@Informatic please open an issue on https://tracker.ceph.com under the ceph-volume component with your error logs, thanks.

**Comment by Informatic** [comment]
After further research, `ceph-volume lvm batch` seems to be only suitable when using full drives. In case of setting up OSDs on already created LVs, `ceph-volume lvm create` would need to be used.  If I understand it correctly, `lvm batch` prepares LVM/VG/PV/LV on a set of drives, and then executes `lvm create` on all of them. (per http://docs.ceph.com/docs/master/ceph-volume/lvm/batch/ and http://docs.ceph.com/docs/master/ceph-volume/lvm/create/)

**Comment by w1ndy** [comment]
I wonder if it's possible to use a specific partition (e.g. sda2) on a disk to bootstrap Ceph with Rook?

**Comment by clkao** [comment]
@hSATAC did some more digging on this. while #2100 would allow the dm-0 device to be passed to osd preparation, `ceph-volume lvm batch` does not like a LV in two places that requires patching.
- dm name resolution & rotational metadata population bug triggering KeyError: 'rotational'
- there's a condition to skip LV altogether

However, it is possible to create a linear md0 device on top of the LV. the required change in rook is like #2100, but allowing LinearType. no changes to ceph-volume required.

**Comment by hSATAC** [comment]
Created #3418

By creating a linear raid on the lv and passing the linear disk to `ceph-volume`, we could use the logical volume as OSD device without patching `ceph-volume` command.

**Create a linear device**
``` bash
sudo mdadm --create --verbose /dev/md0 --level=linear --raid-devices=1 /dev/dm-0 --force
```

**Final result after ceph-volume provision**
```
sdb        8:16   0   40G  0 disk
└─vg-lv1 252:1    0   19G  0 lvm
  └─md0    9:0    0   19G  0 linear
    └─ceph--05f3b38a--967e--402e--ae84--109714f2a518-osd--data--acb5abf0--2a34--470b--b2ad--5c97a0a17cb3
```

Tested against `ceph/ceph:v13.2.4-20190109` image.

**Comment by logan2211** [comment]
Thank you @hSATAC for that insight! The mdraid linear device workaround also enables the use of partition devices (`/dev/sda3`) as OSDs. This can be done by building the linear mdraid on top of the partition device rather than a logvol.

Building single device mdraids feels very hacky though.. hopefully ceph-volume can eventually accept logvols instead. Is there an upstream bug/issue tracking the ceph-volume problems outlined in https://github.com/rook/rook/issues/2047#issuecomment-509169302?

**Comment by mohag** [comment]
This is still an issue (aka comment spam to keep the bot from closing it)

**Comment by unkls** [comment]
Any update on this ? I have an error like this. 
I try to use custom LV to provide my CRD cluster and my osd-prepare always failed.

**Comment by satoru-takeuchi** [comment]
I'll try this. However, there is one concern. @zoetrope and I are trying to fix #4582 and the fixes of #2047 and #4582 would conflict very much. In my opinion, I'd like to fix #4582 first and fix #2047 after that.

I'll discuss with @travisn about the proper way of proceeding.

**Comment by leseb** [comment]
@satoru-takeuchi c-v won't accept dm AFAIR, I even skipped them here: https://github.com/rook/rook/pull/4454.

**Comment by satoru-takeuchi** [comment]
@leseb Thank you for letting me know. I'll read #4454 .

**Comment by rjhenry** [comment]
Another individual checking in with this issue. Is there anything I can do to help move this to a resolution?

**Comment by leseb** [comment]
I tried to enable this again today but there are still 2 issues in ceph-volume preventing us from exposing LVs:

* https://tracker.ceph.com/issues/43209
* https://tracker.ceph.com/issues/43579 (do not report the correct error for dm)

```[root@c5cf18f12f05 /]# ceph-volume inventory /dev/dm-2

====== Device report /dev/dm-2 ======

     available                 False
     rejected reasons          Insufficient space (<5GB)
     path                      /dev/dm-2
     device id
```

**Comment by champtar** [comment]
isn't #4219 a workaround for this issue ? what are the drawbacks of exposing the LV as local PV ?

**Comment by satoru-takeuchi** [comment]
I guess it would work. One drawback is that the extra steps are necessary to prepare local PVs of LVs. I'm not sure whether there are any serious drawbacks.

**Comment by alamintech** [comment]
can I use LVM volume for ceph cluster, any one help me. I am a new linux user. see my image 
![lvm](https://user-images.githubusercontent.com/68062764/87704418-3085a500-c7be-11ea-9443-a8ba9f81df46.JPG)

**Comment by psavva** [comment]
I'm also interested in using a vg/lv as a storage option for ceph on rook.

Any news if or when this issue would be resolved?  Is there any roadmap for this one?

Can I do anything to help, like testing?

**Comment by alamintech** [comment]
no this is not solved from me. I am try using row disk like /dev/sdb
have any idea for LVM?

**Comment by ymmt2005** [comment]
I believe you can create a [local persistent volume](https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/) PV for the LVM logical volume,
and use it through OSD on PVC.

We are running Ceph clusters using LVM volumes through OSD on PVC.

**Comment by psavva** [comment]
I would beg for a good how to or the yaml files.
I tried all day yesterday to do it with LVM with no avail.
I tried all day today with Cluster-on-PVC.yaml and it would provision the monitors ok with the volumes I created, but not the OSDs ..  It just stayed in a lens status.  And the PVs where not being assigned to the OSDs.  I think/believe it was stuck on the job.batch osd provisioning.  I did not manage to get anything from the logs...

**Comment by zerkms** [comment]
I believe it's still the case (a comment to trigger the stale bot)

**Comment by mback2k** [comment]
This is still an issue and now the linear mdraid workaround also no longer working, because the device is not accepted.

**Comment by promasu** [comment]
My osds seem to be created the way described in this issue here (a collegue of mine did this and it's not documented)
I now had to wipe one osd and I'm not able to get it added back by the osd-prepare-node pod.
The working one looks like this

```
`-sda3`                                                                                                     8:3    0  3.2T  0 part
  `-md0                                                                                                    9:0    0  3.2T  0 linear
    `-ceph--cbead0a3--208d--4551--9c2d--55cb9badb2e7-osd--data--4d8c75d6--d047--4fbf--b9aa--b28685eb8fef 253:1    0  3.2T  0 lvm
```

with
```
# mdadm /dev/md0
/dev/md0: 3224.85GiB linear 1 devices, 0 spares.

# lvdisplay
  --- Logical volume ---
  LV Path                /dev/ceph-cbead0a3-208d-4551-9c2d-55cb9badb2e7/osd-data-4d8c75d6-d047-4fbf-b9aa-b28685eb8fef
  LV Name                osd-data-4d8c75d6-d047-4fbf-b9aa-b28685eb8fef
  VG Name                ceph-cbead0a3-208d-4551-9c2d-55cb9badb2e7
  LV UUID                TSDWxq-m0qr-PkLM-UAG1-T2Y1-omra-kTbW5A
  LV Write Access        read/write
  LV Creation host, time rook-ceph-osd-prepare-node03-h7w6q, 2020-02-15 13:32:11 +0100
  LV Status              available
  # open                 24
  LV Size                <3.15 TiB
  Current LE             3224
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:1

# blkid
/dev/sda3: UUID="67609867-d264-5543-d84b-069635a0757c" UUID_SUB="d90880fe-9b95-ed48-7054-771fc28c95ca" LABEL="node03:0" TYPE="linux_raid_member" PARTUUID="eb35dd4c-7cb3-4e1e-8c78-679ca3288a49"
/dev/md0: UUID="ySHpTs-s3jV-D6iB-zVEK-NYdg-izIr-Qy00qQ" TYPE="LVM2_member"
/dev/mapper/ceph--cbead0a3--208d--4551--9c2d--55cb9badb2e7-osd--data--4d8c75d6--d047--4fbf--b9aa--b28685eb8fef: TYPE="ceph_bluestore" PTTYPE="atari"
```

and

```
2021-02-20 18:49:53.568457 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2021-02-20 18:49:53.979231 D | cephosd: {
    "5": [
        {
            "devices": [
                "/dev/md0"
            ],
            "lv_name": "osd-data-4d8c75d6-d047-4fbf-b9aa-b28685eb8fef",
            "lv_path": "/dev/ceph-cbead0a3-208d-4551-9c2d-55cb9badb2e7/osd-data-4d8c75d6-d047-4fbf-b9aa-b28685eb8fef",
            "lv_size": "3461743640576",
            "lv_tags": "ceph.block_device=/dev/ceph-cbead0a3-208d-4551-9c2d-55cb9badb2e7/osd-data-4d8c75d6-d047-4fbf-b9aa-b28685eb8fef,ceph.block_uuid=TSDWxq-m0qr-PkLM-UAG1-T2Y1-omra-kTbW5A,ceph.cephx_lockbox_secret=,ceph.cluster_fsid=8b6ebf62-49a5-49db-b637-add2b50df4d6,ceph.cluster_name=ceph,ceph.crush_device_class=None,ceph.encrypted=0,ceph.osd_fsid=a90b09a5-0eb6-4e91-9404-52f2d8a03be2,ceph.osd_id=5,ceph.type=block,ceph.vdo=0",
            "lv_uuid": "TSDWxq-m0qr-PkLM-UAG1-T2Y1-omra-kTbW5A",
            "name": "osd-data-4d8c75d6-d047-4fbf-b9aa-b28685eb8fef",
            "path": "/dev/ceph-cbead0a3-208d-4551-9c2d-55cb9badb2e7/osd-data-4d8c75d6-d047-4fbf-b9aa-b28685eb8fef",
            "tags": {
                "ceph.block_device": "/dev/ceph-cbead0a3-208d-4551-9c2d-55cb9badb2e7/osd-data-4d8c75d6-d047-4fbf-b9aa-b28685eb8fef",
                "ceph.block_uuid": "TSDWxq-m0qr-PkLM-UAG1-T2Y1-omra-kTbW5A",
                "ceph.cephx_lockbox_secret": "",
                "ceph.cluster_fsid": "8b6ebf62-49a5-49db-b637-add2b50df4d6",
                "ceph.cluster_name": "ceph",
                "ceph.crush_device_class": "None",
                "ceph.encrypted": "0",
                "ceph.osd_fsid": "a90b09a5-0eb6-4e91-9404-52f2d8a03be2",
                "ceph.osd_id": "5",
                "ceph.type": "block",
                "ceph.vdo": "0"
            },
            "type": "block",
            "vg_name": "ceph-cbead0a3-208d-4551-9c2d-55cb9badb2e7"
        }
    ]
}
```

When I try to add only the linear md

```
/dev/md1: 3224.85GiB linear 1 devices, 0 spares.
```

The prepare pod states

```
 cephosd: skipping device "md1": ["Device type is not acceptable. It should be raw device or partition"].
```

When I create a pv on it I get

```
# blkid
/dev/md1: UUID="heVbVc-lMg3-1rvY-zBhG-6SaH-MYgP-UP5cwo" TYPE="LVM2_member"
```

With osd-prepare-node Pod-Output

```
2021-02-20 19:14:46.040140 I | cephosd: skipping device "md1" because it contains a filesystem "LVM2_member"
```

Is there currently a way to add this partition back to the cluster?

**Comment by dimm0** [comment]
Still an issue

**Comment by kompetenzlandkarte** [comment]
Is there an update for dm devices on host based clusters? Will it be possible to switch from local pvc based clusters to host based cluster again?
We are provisioned 2TB on each node via raw device mapping and multi pathing. Then we created an dm device which is skipped by rook.

**Comment by satoru-takeuchi** [comment]
> Is there an update for dm devices on host based clusters?

Not yet, LV will be supported by #7967 but mpath will not.

> Will it be possible to switch from local pvc based clusters to host based cluster again?

I guess yes, by migrating OSDs one by one. However, I've not tried yet.

> We are provisioned 2TB on each node via raw device mapping and multi pathing. Then we created an dm device which is skipped by rook.

If your cluster is host-based cluster, Rook doesn't support mpath. PVC-based cluster support mpath.

https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md#storage-class-device-sets

**Comment by dimm0** [comment]
👀

**Comment by lhzw** [comment]
![image](https://user-images.githubusercontent.com/17211510/147387867-bce2494a-9b6f-45f7-8734-87e64d16ee58.png)

**Comment by cchriso** [comment]
👀
