### ISSUE TITLE
Proper cleanup after lost nodes/OSDs

### ISSUE THREAD

**Issue by paalkr** [rook/rook#2053]
* Bug Report

**Deviation from expected behavior:**
Configmaps and deployments related to terminated k8s nodes are left dangling, and OSDs are not taken out of the ceph cluster. 

**Expected behavior:**
I would expect that configmaps and deployments for deleted/terminated/missing nodes to be removed by the operator. 

**How to reproduce it (minimal and precise):**
Create a multi node K8s cluster, and add a OSDs on each node. Terminate/delete one of the k8s nodes and watch that no cleanup is not performed.

To cleanup you have to
1. Delete the job and configmap in the rook-ceph namespace related the dead/removed node
2. Delete the deployment in the rook-ceph namespace related to the osd that was present on the dead/removed node
3. Delete the two configmaps related to the dead/removed node in the rook-ceph-system namespace
4. Restart the rook operator. 

Also dead OSDs should be removed from the ceph cluster by issuing `ceph osd purge osd.ID --yes-i-really-mean-it`, where ID is the OSD that was previously running on the terminated node.

Refer to this thread on slack for more details
https://rook-io.slack.com/messages/C46Q5UC05/convo/C46Q5UC05-1534330458.000100/ 

**Environment**:
* OS (e.g. from /etc/os-release): CoreOS
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): 0.8.1
* Kubernetes version (use `kubectl version`): 1.9.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On AWS, built with kube-aws
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
OK

**Comment by mjschmidt** [comment]
This is still an issue? Should a new issue be opened?

**Comment by paalkr** [comment]
I don't think this issue still applies.

**Comment by mjschmidt** [comment]
mmmm are osd prepare jobs the same thing? In my deployment when I use the following yaml file to [deploy a ceph cluster](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml) the osd prepare job doesn't seem to ever be cleaned up.

How to duplicate:
Create a cluster and deploy ceph with 5 nodes
turn off one worker node
simulate catastrophic node failure by removing a node not safely from Kubernetes while said node is off
reboot all nodes
the job of rook-ceph-osd-prepare-<deleted node ip> exists forever and is never cleaned up

**Comment by paalkr** [comment]
No, that is not the same issue that I initially described in the OP. I'm not sure if it's a real problem that the osd prepare jobs are not automatically garbage collected.

**Comment by mjschmidt** [comment]
It makes your UIser interface and kubectl return commands messy. I don't see a reason not to have a low priority ticket to clean up these jobs if they shouldn't exist?

But I am not on the rook-ceph team.

**Comment by travisn** [comment]
@mjschmidt Does the new [OSD removal](https://rook.io/docs/rook/v1.2/ceph-osd-mgmt.html) topic help answer the question? Rook intentionally doesn't automatically remove OSDs. If the osd prepare pods are completed, they won't have any side effects of not being cleaned up. You're just suggesting they should be deleted automatically? Or are you seeing the pods stuck in pending or failed state for the removed node?

**Comment by B1ue-W01f** [comment]
The steps outlined in this issue were invaluable in recovering from a node failure on a 3 node cluster (dropped to 2 nodes), as when adding a replacement node, rook refused to heal and the toolkit was refused connection as a result.

Followed steps 1,2 and 4 to bring the cluster back online in a degraded state and allowed recovery.
