### ISSUE TITLE
Performance tuning issue

### ISSUE THREAD

**Issue by Tee0125** [rook/rook#2057]
Hi, we tried rook to make a elastic filesystem cluster w/ ceph, and deployed to 5 nodes. 

Setup was done easily, but we met performance issue. When check performance with dd, write speed is too slow (20MB/s). Since IO load and cpu load were not high while testing, I think the reason of low performance is not on cpu or disk. (when checking hdd performance at bare metal 130MB/s was measured)

How can we achieve better performance?

**Comment by galexrt** [comment]
@Tee0125 Could you please give us more context and info.
What hardware/virtualization are you using?
What `dd` command did you use?
How fast is the Network speed between nodes `netperf`?

Please provide these and more information about the tests and test environment.

**Comment by ksingh7** [comment]
@Tee0125  
- By elastic filesystem cluster w/ Ceph, you mean CephFS share mounted to PODs ?
- How many OSDs ? Does the OSDs have SSD media for bluestore db/wal ?
- ``dd`` is single threaded, can you try using ``fio`` with multi-threads say 8 or 16 threads. Also while running test keep an eye on the `` ceph -s`` and look for any warnings there if there are any
