### ISSUE TITLE
Dynamic provisioning for NFS storage

### ISSUE THREAD

**Issue by jbw976** [rook/rook#2062]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** Currently, the NFS support in Rook requires the user to statically provision a PersistentVolume to represent the NFS volume that will be consumed by a pod.  The user has to look up the IP address of the NFS pod, copy/paste it into a PV declaration, etc., which is a cumbersome experience.  This could be improved by including a dynamic provisioner that would automate those actions for the user and generate a PV without user intervention. All the user needs to do is declare a PVC that points to this new NFS provisioner.

There would be a lot of commonality with the Ceph dynamic provisioner, perhaps a good opportunity to factor out the commonality into the Rook framework.

**Comment by MartinForReal** [comment]
How about adding a field in CRD to indicate if operator should create nfs provisioner, and create a deployment for https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client ?

**Comment by jbw976** [comment]
as @rohan47 indicated in Slack, that seems reasonable so far to use the NFS provisioner from external-storage.  There may be more that is discovered as this gets taken further, but up front that seems OK.

**Comment by rohan47** [comment]
@MartinForReal are you working on this issue?

**Comment by KaelBaldwin** [comment]
fyi https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client works well for this, you can just point it to your rook-nfs server. But it would be nice if it was built in.

**Comment by hameno** [comment]
Nice feature, but I'm wondering why two separate PVCs share the same folder on the nfs share - shouldn't that be scoped?

**Comment by rohan47** [comment]
> Nice feature, but I'm wondering why two separate PVCs share the same folder on the nfs share - shouldn't that be scoped?

What do you mean by two seperate PVCs share the same folder on the nfs share?

**Comment by stv0g** [comment]
> What do you mean by two seperate PVCs share the same folder on the nfs share?

I create an issue for this behaviour: #4982
