### ISSUE TITLE
Integration tests sometimes hang during init with kubeadm.sh script

### ISSUE THREAD

**Issue by travisn** [rook/rook#2066]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The integration tests are failing frequently in the last day getting stuck during 
```
kubeadm.sh up
```

For example, see [this build](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-2029/10/pipeline/47).

A [healthy build](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/master/runs/736/nodes/41/steps/102/log/?start=0) will print the following message twice and the continue, while the build that hangs will only print it once.
```
Reading package lists...
```

**Expected behavior:**
Successful builds on GCE with 1.9

**Comment by travisn** [comment]
This issue does not appear to happen if the Jenkins build was triggered when there are no other builds running. If there is another build already running, the second build seems to fail consistently with this error. I wonder if the second build is not getting its own fresh GCE instance.

**Comment by travisn** [comment]
Here are some more instances:
- https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-2160/1/pipeline
- https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-2159/4/pipeline/

**Comment by galexrt** [comment]
Are we caching the downloaded packages (of minikube)?
Maybe the instances we build on are getting blocked causing the `apt-get update` to never return for whatever reason.
I think the error could be around here: https://github.com/rook/rook/blob/master/tests/scripts/kubeadm-install.sh#L34-L37

**Comment by galexrt** [comment]
Still an issue.

**Comment by galexrt** [comment]
Still happening from time to time

**Comment by travisn** [comment]
Haven't seen this for a while
