### ISSUE TITLE
minikube 0.28+ VM dies after installing wordpress/mysql

### ISSUE THREAD

**Issue by jbw976** [rook/rook#2074]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** After installing mysql/wordpress, the wordpress site should be functional and accessible.  Instead, the entire minikube VM dies and things like `minikube ssh` and `minikube ip` just hang.  `kubectl` commands hang as well.

**Expected behavior:** Minikube to be functional after wordpress/mysql are installed.

**How to reproduce it (minimal and precise):**

```
cd ${GOPATH}/src/github.com/rook/rook/cluster/examples/kubernetes/ceph
kubectl create -f operator.yaml
kubectl create -f cluster.yaml
kubectl create -f storageclass.yaml
cd ${GOPATH}/src/github.com/rook/rook/cluster/examples/kubernetes
kubectl create -f mysql.yaml
kubectl create -f wordpress.yaml
```

Shortly after this point, `minikube` and `kubectl` commands hang, making this very hard to troubleshoot.

## Workaround
This behavior can be worked around by reverting minikube to v0.27.0 and Kubernetes 1.10.

**Comment by rohan47** [comment]
I faced this issue but after restarting minikube it worked fine

**Comment by galexrt** [comment]
Do we know if it is "just" an issue of the minikube VM running out of memory during the initial start of "everything"?

**Comment by jbw976** [comment]
I did not see this on `minikube version: v0.30.0` with Kubernetes `v1.12.2`, closing.

**Comment by jbw976** [comment]
Never mind, I am seeing this again right now with minikube version: `v0.30.0` with Kubernetes `v1.12.2`.

**Comment by noahdesu** [comment]
still exists in minikube v0.34.1 and whatever the default kubernetes is there v1.13.x on kvm2 vm driver.

**Comment by mykaul** [comment]
4GB sounds very small to me for everything in a VM. I had a worker with 4GB and a Master with 4GB and it hardly worked. Can you try increasing the memory dramatically, just to see where we are at?

**Comment by noahdesu** [comment]
I tried 8 GB with minikube and it fell over. This is quite problematic for developers running minikube on a laptop / desktop. I'll investigate this some more today

**Comment by noahdesu** [comment]
Root cause here is still a bot of a mystery. But using the very latest minikube/k8s I've gotten things to work alright by reducing the rbd image size in mysql.yaml and wordpress.yaml from 20GB to 2GB. If anybody wants to give that a shot, it'd be nice to have another data point or two.

**Comment by jbw976** [comment]
anecdotally, I've seen more reliable behavior when I want a few mins after deploying the ceph cluster before creating the mysql PVC.  No idea what would "settle" in that time period to make it more reliable, but it does feel that seems to work better.

**Comment by noahdesu** [comment]
same experience. inside the minikube vm it is total chaos. most processes' memory utilization seem reasonable, especially at 8GB allocated. it seems like something is bursty.

**Comment by jbw976** [comment]
@noahdesu I ran into this multiple times in a row this morning getting ready for demos today in London.  Your suggestion of bumping down the PVC storage size from 20Gi to 2Gi seemed to help.  Thanks!

**Comment by jbw976** [comment]
@galexrt suggested tailing dmesg output in another terminal when trying to repro this

**Comment by travisn** [comment]
I'd suggest we just set this to 2Gi as suggested, then verify that it doesn't repro anymore. If so, then we can troubleshoot further with the dmesg output

**Comment by noahdesu** [comment]
![image](https://user-images.githubusercontent.com/242417/54399276-e4cb6480-467a-11e9-887f-47b88a18522a.png)

there minikube just doing productive stuff

**Comment by noahdesu** [comment]
If I give kvm another CPU it happily eats up 300% CPU utilization. Inside the VM everything is totally unresponsive, even when running something like top with nice -20. So it is hard to even observe what process is eating up this CPU.

Is there a way to run the entire k8s stack / pods with a custom CPU priority?

What's so unique about this setup, anyway? I'd say it's ceph, and in particular the osd and the in-kernel rbd client all running on the same node. That probably isn't the root cause, but there are a ton of feedback loops in this resource constrained environment.

**Comment by jbw976** [comment]
Just saw this a couple times again this morning, even with the local change to only use `2Gi` for both the mysql and wordpress PVCs.

**Comment by noahdesu** [comment]
@jbw976 thanks for the data point. i'm curious if you've tried the latest minikube but with k8s downgraded? I've mostly abandoned minikube at this point, but I can't shake the feeling that this is an OS issue.

**Comment by jbw976** [comment]
@noahdesu I reproduced this with Minikube v1.0.0 and k8s v1.13.1.  What versions do you think I should try this with?

I just got bit twice in a row while presenting to a meetup audience, definitely very painful :(

If folks aren't using minikube anymore, what do you recommend for giving demos on your laptop with? or daily development work?

**Comment by noahdesu** [comment]
I just tried with 1.14.1 in my vagrant-based setup and didn't experience this issue. The next test I'd like to do in minikube is to run k8s and all pods with very restrictive memory and cpu limits so that perhaps we can run some diagnostic tools.

**Comment by itmuckel** [comment]
Same problem here. I cannot reproduce it reliably. I used `minikube ssh` and `toolbox`, installed htop there and the VM uses roughly 1.5GB RAM. 800Mb of it are my own kubernetes apps. Using `minikube dashboard` I can see that the whole rook-ceph namespace uses about 850Mb RAM. So I'm not sure about where the crash originates from, but it's not from a lack of resources.

**Comment by noahdesu** [comment]
I placed CPU limits on pods to be `100m` and got some dmesg output before lockup. kube-scheduler got OOM killed, followed by `rbd` device complaining about some stuff, and then a loop in which the `mysql` process/pod gets OOM killed which is continuously restarted. This loop continued for a while until the machine locked up. I'm not sure if another issue ended up being the cause of the lockup (since it eventually froze). Could be a memory leak somewhere.
