### ISSUE TITLE
allow ObjectStore -> sslCertificateRef with standard kubernetes.io/tls certificates

### ISSUE THREAD

**Issue by scher200** [rook/rook#2079]
Allow ObjectStore -> sslCertificateRef to use cert-manager genereated certificates.
Right now the certificate looks like:
```
{
  tls.crt: ...
  tls.key: ...
}
```
according to the docs it only eats combined pem certificates.

It would be awesome it would directly convert or eat those standardly generated acme cert-manager certificates. Because we have loads of them freely.

**Comment by Queuecumber** [comment]
cert-manager is actually just using a standard kubernetes tls secret (type `kubernetes.io/tls`) so definitely Rook should be using the standard kubernetes over anything else.

**Comment by jessynt** [comment]
any progress on this task?

**Comment by stephan2012** [comment]
Just setup a PKI infrastructure with Vault and cert-manager which can now provide short-living TLS certificates. Relying on Kubernetes standard TLS secret would allow consuming these certs easily. By the way, does Rook pickup updated certificates?

**Comment by scher200** [comment]
@stephan2012 sounds good, could you post a tutorial how to do that?

**Comment by stephan2012** [comment]
@scher200: Will try to do this in the next days.

**Comment by galexrt** [comment]
I think we can do that in an init container. Take the certs and make them into pem / `cat` them together.

I'll look into it.

**Comment by stephan2012** [comment]
> I think we can do that in an init container. Take the certs and make them into pem / `cat` them together.

That's a good start, at the moment I'm doing this externally with a script. However, an init container does not monitor the certificate for updates. This becomes important when short-living certificates are in use as suggested by Vault.

```bash
#!/bin/bash

# According to https://github.com/rook/rook/blob/master/Documentation/ceph-object-store-crd.md#gateway-settings
# the TLS certificate for Ceph RadosGW has to be specified in a special format. This scripts updates .data.cert
# from the Kubernetes TLS secret standard keys (tls.key, tls.crt, ca.crt).

NS="rook-ceph"
SECRET="tls-objectstore-int-company-com"

# Hopefully, the certificate will be be updated by cert-manager while we're reading it…
CRT="$( kubectl get secret -n ${NS} ${SECRET} -o jsonpath='{ .data.tls\.crt }' |base64 -d )"
KEY="$( kubectl get secret -n ${NS} ${SECRET} -o jsonpath='{ .data.tls\.key }' |base64 -d )"
CA="$( kubectl get secret -n ${NS} ${SECRET} -o jsonpath='{ .data.ca\.crt }' |base64 -d )"

FULLCHAIN=$( echo -e "$KEY\n$CRT\n$CA" |base64 -w 0 )

kubectl patch secret -n ${NS} ${SECRET} -p "{\"data\":{\"cert\": \"$FULLCHAIN\"}}"

# Ugly workaround…
kubectl delete pod -n ${NS} -l app=rook-ceph-rgw
```

However, a rolling update for the pods would be better. Since there's no generic solution available in Kubernetes patching the deployment seems to be the only available option. Maybe Rook can insert a placeholder environment variable, e.g. `TLS_CERTIFICATE_HASH` that can be updated by a sidecar container which would then trigger the regular rolling update process.

**Comment by schmitch** [comment]
@galexrt I would also prefer if the secret would be watched so that short living certificates could be used.

**Comment by xrow** [comment]
please also think of openshift

**Comment by ron1** [comment]
Do not auto-close this issue.

**Comment by stephan2012** [comment]
Issue is not yet solved…

**Comment by stephan2012** [comment]
Still open…

**Comment by udayjalagam** [comment]
Even I am trying to use cert-manager for certificate management for rgw . But can't do that because of how rook expect the certificates to be present.

**Comment by onmyflow** [comment]
I find it quite strange as to why ceph even expects a format like this. 
Otherwise it would be really easy to just create a cert via cert-manager in k8s.
Is it really that uncommon for somebody having to create a rgw cert with cert-manager?
I would imagine this be a very common inssue...

**Comment by stephan2012** [comment]
Let’s keep this open because using default Kubernetes TLS Secrets is still desired.

**Comment by PhoenixMage** [comment]
I am looking to use rook object stores with cert-manager also

**Comment by onmyflow** [comment]
@PhoenixMage We have solved the issue by just using a proxy that can do TLS termination. Since the S3 API is based on HTTP anyways, you can just use an everyday nginx ingress. We -- for example -- use Istios VirtualService to direct our s3.domain.tld requests to the rgw service while terminating the TLS in isto itself. It's actually very simple and much cleaner than having ceph do the termination while most of your system terminates at your ingress controller.

**Comment by PhoenixMage** [comment]
@onmyflow that's what I am doing now, and would be fine for something like istio with a sidecar and controller however we are using traefik V1 which means the SSL is not necessarily terminated on the node itself which means it will be in the clear over the cluster network which is far from ideal. Great suggestion though

**Comment by fritchie** [comment]
When using the Beast frontend with RGW you should be able to supply a separate TLS cert and key

https://docs.ceph.com/en/latest/radosgw/frontends/#options

**Comment by evankanderson** [comment]
It appears that Beast is available since v13.2.0 (Mimic), but it's not clear to me how to use rook to select which frontend to use.

**Comment by ron1** [comment]
Rook uses the beast frontend. Ceph rgw beast front-end needs to support separate ca_file parameter to achieve ideal rook integration.

**Comment by travisn** [comment]
@thotz Could you take a look at this? Perhaps some of your recent work with rgw config and tls support will already help.

**Comment by thotz** [comment]
This can be worked on IMO and I hope it is okay to include third part ca(if exists) in `tls.cert` of this secret. @travisn Do you like to depreciate existing `cert` mechanism at some point?

**Comment by travisn** [comment]
@thotz After support is added for the k8s certs, it probably makes sense to deprecate the existing format
