### ISSUE TITLE
rook user management, authorization, and authentication

### ISSUE THREAD

**Issue by jbw976** [rook/rook#209]
We need to think a bit more about our auth story for users of `rook` tool and REST API. ceph-rest-api leaves that up to app developers building on top of the API, we need to figure out what's right for us.

Managing a set of users and role based access at the rook REST API level (completely independent of cephx) makes sense. An admin would be able to add/remove authorized users and manage their roles. Roles provide different sets of of access permissions to different operations within the cluster and locally. (e.g. admin creds may be needed to create an image in the cluster, but storage operator creds are all that's needed to map/mount a local block device)

`rook` would need a log in operation.

What are the user auth/add/remove stories for etcd/etcdctl and kubernetes/kubectl?

**Comment by bassam** [comment]
I believe our plan is to rely on RBAC and K8S authorization going forward.
