### ISSUE TITLE
rook should be able to delete block images cluster wide

### ISSUE THREAD

**Issue by jbw976** [rook/rook#210]
`rook` can clean up RBDs and their mounts on the local machine but we do not have a command exposed to clean up the RBD image cluster wide. The rbd_remove API should do this for us fairly easily.

I think we should also be calling Destroy on IOContext objects that we Open for RBD operations in the API server.

**Comment by jbw976** [comment]
This will be needed for v0.4 for the Rook volume plugin work.  It doesn't necessarily need to be exposed through the rook client tool but it will need to be exposed through the API.

**Comment by kokhang** [comment]
This is needed by https://github.com/rook/rook/issues/432. The volume plugin will use Rook APi to create/delete block images.
