### ISSUE TITLE
Support Google Kubernetes Engine (and all other dynamic clusters)

### ISSUE THREAD

**Issue by tcf909** [rook/rook#2107]
**What should the feature do:**
The feature would allow you to deploy Rook in to an existing Google Kubernetes Engine cluster. Currently there are a lot of local node requirements that don't allow someone working in a dynamic environment (auto-scaling, dynamic node naming, no local storage, etc) to take advantage of Rook.

**What is use case behind this feature:**
Fewer and fewer clusters are being built once/statically. Most clusters are being dynamically deployed either via managed services like Google Kubernetes Engine, or internal systems. Most of these clusters lack local resources (at least local resources you would want to use and depend on).

A dynamic cluster allows for scaling, maintenance, and a whole slew of things that a static cluster won't ever touch.

TODO:
- [ ] Make OSD's and MONs use Pods via Deployments than can take advantage of persistent volumes rather than local storage (both EXT4 based filesystems as well as the new Raw Block Device support in K8). This would require the use of PVC's and StorageClasses.
- [ ] Use affinity and taints to fence in which nodes are used or make node selection a filter selection rather than an "ALL" or "THIS ONE NODE WITH A NAME THAT WILL NEVER BE THE SAME IN A DYNAMIC CLUSTER"
- [ ] Generally take all of the "Node" mindset out of the design architecture and use the flexible abstracted resources K8 was meant to use.

**Comment by jbw976** [comment]
Thank you for writing up this scenario and improvements @tcf909.  I believe the first one is covered by https://github.com/rook/rook/issues/919#issuecomment-419480399, which we'd love to get in for the 0.9 milestone.  @yanniszark had expressed interest in that for the Cassandra operator too.

**Comment by yanniszark** [comment]
Right now I'm working with @gnumoreno on something similar. 
We're looking into using high performance Local Volumes on a GKE environment for the cassandra/scylla operator.
We have various interesting findings and we will compile a list of scenarios with local volumes on GKE. After GKE, we also plan to investigate other Kubernetes offerings (EKS, AKS).

**Comment by jbw976** [comment]
Awesome @yanniszark, please do share your findings here.  This topic has general benefit to most all Rook storage providers.

**Comment by consideRatio** [comment]
I'll start a journey to investigate if I could resolve this manually in a somewhat sustainable way by utilizing StatefulSets and their unique PVCs per replica along with suitable labels for setting up suitable affinities. But, this is currently a naive idea formed without any actual experience with Rook. Any pointers are appreciated!

Does this seem viable? If you quickly conclude "oh this will fail due to ..." I'm all ears!

**Comment by Bessonov** [comment]
unstale

**Comment by Bessonov** [comment]
Activity!

**Comment by travisn** [comment]
With #3451 merged we have most of these changes in place. The one remaining work item is to remove the node selector from mons if backed by PVCs. @noahdesu is there a tracking issue for that?

**Comment by travisn** [comment]
This implementation was completed in v1.1 for the Ceph operator. See the example [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml) with this [doc](https://rook.io/docs/rook/v1.1/ceph-cluster-crd.html#pvc-based-cluster) for more information. 

I believe the other operators already support being backed by PVCs, Ceph was the last holdout. Please give it a try and let us know your feedback!
