### ISSUE TITLE
Potential issue for the docker image created by cross-build

### ISSUE THREAD

**Issue by arm64b** [rook/rook#2110]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
We may expect the final docker image is for other architecture like `arm64` when cross-building it on a different platform like `amd64`, but actually the cross-build will pull the base image of `amd64` instead of `arm64`. For example, if we inspect the `nfs-arm64` image generated by `make build.all` on `amd64`, we get below output:
```
$docker inspect build-c76ef25e/nfs-arm64
...
        "Architecture": "amd64",
        "Os": "linux",
...
```
**Expected behavior:**
When we do cross-build, the expected behavior is to pull the base image for the Arch we're targeting, not for the local Arch.

**How to reproduce it (minimal and precise):**

This is just for tracking purpose!

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by bassam** [comment]
@arm64b thanks for looking into this. this looks like a recent regression, as this was working in the past.

**Comment by arm64b** [comment]
@bassam, although we can build those different-Arch docker images on `amd64` with help of `binfmt` and `qemu`, but if the base image is from `amd64` and have some binaries pre-installed within that base image, we'll encounter problem if we `docker run` the final built image on, for example, `arm64` in case of binaries from `x86_64` is launched because it's `x86 64` instruction.
IOW, we can cross-build it but don't expect it can run smoothly on the target platform. We may think to use docker's `FROM --platform=arm64 busybox` syntax to address this, but this feature is not supported yet by docker AFAIK. The client side support PR: https://github.com/moby/moby/pull/36881

**Comment by bassam** [comment]
@arm64b agree we need to select the right base image. Looking at https://github.com/rook/rook/blob/master/images/nfs/Dockerfile#L17 it seems to only pull `amd64`. For ceph we do the right thing: https://github.com/rook/rook/blob/master/images/ceph/Makefile#L23

**Comment by bassam** [comment]
looks like similar issues with cockroachdb and minio images.

**Comment by arm64b** [comment]
> looks like similar issues with cockroachdb and minio images.

We need to figure out the specific arm64 docker image for those 2 components since there're not corresponding equivalent one like `nfs` under `arm64v8` prefix.

**Comment by jbw976** [comment]
Reopening this issue since it still exists for cockroachdb/minio.
