### ISSUE TITLE
Mismatch between kubernetes.io/hostname label between nodes and Cluster CRD

### ISSUE THREAD

**Issue by slayerjain** [rook/rook#2148]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:Failure in deploying OSD via Cluster CRD**

**Expected behavior: Successful deployment of the Cluster CRD**

**How to reproduce it (minimal and precise): Use kops to setup kubernetes on AWS and try to install rook 0.8.2**

**Environment**:
* OS (e.g. from /etc/os-release): Debain Jessi (kops stable channel)
* Kernel (e.g. `uname -a`): 4.4.148-k8s
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): 0.8.2
* Kubernetes version (use `kubectl version`): 1.10.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AWS using Kops
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

![screenshot from 2018-09-21 20-53-26](https://user-images.githubusercontent.com/12831254/45890446-9a121380-bde0-11e8-89fc-1922f2c6a1ee.png)
However, my label looks like: `kubernetes.io/hostname=ip-172-10-87-82`

**Comment by jbw976** [comment]
hi @slayerjain, can you share the output of the following?
```
kubectl get node --show-labels
kubectl -n rook-ceph get clusters.ceph.rook.io -o yaml
```

**Comment by slayerjain** [comment]
**kubectl get node --show-labels**

`ip-172-10-113-68.ap-southeast-1.compute.internal    Ready     node      6h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=r4.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1c,kops.k8s.io/instancegroup=nodes,kubernetes.io/hostname=ip-172-10-113-68,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-172-10-123-23.ap-southeast-1.compute.internal    Ready     master    9h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1c,kops.k8s.io/instancegroup=master-ap-southeast-1c,kubernetes.io/hostname=ip-172-10-123-23,kubernetes.io/role=master,node-role.kubernetes.io/master=
ip-172-10-124-232.ap-southeast-1.compute.internal   Ready     node      8h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=r4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1c,kops.k8s.io/instancegroup=nodes,kubernetes.io/hostname=ip-172-10-124-232,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-172-10-38-206.ap-southeast-1.compute.internal    Ready     node      6h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=r3.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1a,kops.k8s.io/instancegroup=nodes,kubernetes.io/hostname=ip-172-10-38-206,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-172-10-58-115.ap-southeast-1.compute.internal    Ready     node      6h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=r4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1a,kops.k8s.io/instancegroup=nodes,kubernetes.io/hostname=ip-172-10-58-115,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-172-10-58-235.ap-southeast-1.compute.internal    Ready     node      7h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=r4.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1a,kops.k8s.io/instancegroup=nodes,kubernetes.io/hostname=ip-172-10-58-235,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-172-10-61-20.ap-southeast-1.compute.internal     Ready     master    9h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1a,kops.k8s.io/instancegroup=master-ap-southeast-1a,kubernetes.io/hostname=ip-172-10-61-20,kubernetes.io/role=master,node-role.kubernetes.io/master=
ip-172-10-66-187.ap-southeast-1.compute.internal    Ready     node      6h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1b,kops.k8s.io/instancegroup=nodes,kubernetes.io/hostname=ip-172-10-66-187,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-172-10-74-36.ap-southeast-1.compute.internal     Ready     node      6h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=r3.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1b,kops.k8s.io/instancegroup=nodes,kubernetes.io/hostname=ip-172-10-74-36,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-172-10-78-183.ap-southeast-1.compute.internal    Ready     master    9h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t2.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1b,kops.k8s.io/instancegroup=master-ap-southeast-1b,kubernetes.io/hostname=ip-172-10-78-183,kubernetes.io/role=master,node-role.kubernetes.io/master=
ip-172-10-85-162.ap-southeast-1.compute.internal    Ready     node      6h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=r4.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1b,kops.k8s.io/instancegroup=nodes,kubernetes.io/hostname=ip-172-10-85-162,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-172-10-87-82.ap-southeast-1.compute.internal     Ready     node      7h        v1.10.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=r4.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=ap-southeast-1,failure-domain.beta.kubernetes.io/zone=ap-southeast-1b,kops.k8s.io/instancegroup=nodes,kubernetes.io/hostname=ip-172-10-87-82,kubernetes.io/role=node,node-role.kubernetes.io/node=`

**kubectl -n rook-ceph get clusters.ceph.rook.io -o yaml**
```yaml
apiVersion: v1
items:
- apiVersion: ceph.rook.io/v1beta1
  kind: Cluster
  metadata:
    clusterName: ""
    creationTimestamp: 2018-09-21T14:44:48Z
    generation: 1
    name: rook-ceph
    namespace: rook-ceph
    resourceVersion: "52103848"
    selfLink: /apis/ceph.rook.io/v1beta1/namespaces/rook-ceph/clusters/rook-ceph
    uid: e3ab334a-bdac-11e8-a2f0-06d741d6a150
  spec:
    dashboard:
      enabled: true
    dataDirHostPath: /var/lib/rook
    mon:
      allowMultiplePerNode: true
      count: 3
    network:
      hostNetwork: false
    placement:
      all:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - node
    serviceAccount: rook-ceph-cluster
    storage:
      config:
        databaseSizeMB: "1024"
        journalSizeMB: "1024"
      useAllDevices: false
      useAllNodes: true
  status:
    message: giving up creating cluster in namespace rook-ceph after 5m0s
    state: Error
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by travisn** [comment]
This is a regression in 0.8. With the redesign in osd pods, it was missed in some places that we need to use the `kubernetes.io/hostname` label to identify a node rather than it's node name. This needs to be set in several places.
- ConfigMap name `local-device-<nodeName>` in the `rook-ceph-system` namespace, written by the discovery pod and read by the operator.
- ConfigMap name `rook-ceph-osd-<nodeName>-status` in the `rook-ceph` namespace, used by the operator
- The hostname label added to the osd "prepare" and osd daemon pods.

The culprit may be in listing nodes in the `GetValidNodes` function [here](https://github.com/rook/rook/blob/master/pkg/operator/k8sutil/node.go#L81)

While it may not be common to have a different hostname label from the node name, this will be a blocking issue for those environments such as kops. I'd recommend we include this in 0.8.3.

**Comment by travisn** [comment]
Reopening for backport

**Comment by travisn** [comment]
Already backported with #2176
