### ISSUE TITLE
CRD support for printing additional columns

### ISSUE THREAD

**Issue by travisn** [rook/rook#2151]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
As of K8s 1.11, CRDs have the ability to define additional columns that can be printed with the `kubectl get` command. See the [documentation](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns). The CRDs would be more friendly with more attributes exposed.

**Comment by jbw976** [comment]
We just implemented this in the Crossplane project and it really helps improve the UX: https://github.com/crossplaneio/crossplane/commit/802aad49166b9279e82866239c32a72ed45d2a27

It can be added to the CRDs manually, but this is another great reason to incorporate a more fully functioned operator/controller framework, like Kubebuilder (#1981)

**Comment by travisn** [comment]
Some columns were actually added with #2214. I'll close this and we can add more columns later as specific needs arise.

**Comment by jbw976** [comment]
Those are only for Ceph, can we keep this open for the general desire to add custom columns for other storage providers?
