### ISSUE TITLE
Please use "COPY" instead of "ADD" in Dockerfile

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#2155]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy

Below Dockerfile has used "ADD" instead of "COPY"
./images/cockroachdb/Dockerfile:ADD rook /usr/local/bin/
./images/minio/Dockerfile:ADD rook /usr/local/bin/
./images/cross/Dockerfile:ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${ARCH} /tini
./images/ceph/Dockerfile:ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${ARCH} /tini
./images/ceph/Dockerfile:ADD rook rookflex /usr/local/bin/

**Expected behavior:**
Please use "COPY"

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
@yanchicago We are happy to take a PR to change that to the Docker best practices.
Though I have to question if ADD/COPY are allowing environment variables in the paths/URLs, at least the docs don't state too much about it..
