### ISSUE TITLE
Node id must be consistent between runs given the same data dir

### ISSUE THREAD

**Issue by travisn** [rook/rook#216]
All node configuration stored in etcd is dependent on a constant node id. If the node id changes, the cluster will think it is a new node. This could cause unpredictable side effects such as attempting to configure osds on the same storage devices. 

To make the id consistent, the node id should be cached in the data directory, similarly to the etcd discovery url and other important config.

**Comment by travisn** [comment]
A corollary to this is if a node id is not provided, we can simply generate one and cache it. The user doesn't have to be bothered by the command line option or worry whether /etc/machine-id is present.

**Comment by bassamtabbara** [comment]
I think this is cool. so essentially a random id in the data dir is sufficient to identify the node. if the data directory moves to a different host, its still the same, right?

**Comment by travisn** [comment]
correct, the data dir would be the authority
