### ISSUE TITLE
Ceph dashboard failed to start within the ceph-mgr pod when IPv6 is disabled on host

### ISSUE THREAD

**Issue by kcao3** [rook/rook#2171]
**Is this a bug report or feature request?**
* Bug Report

Does anyone run into any issue with the ceph's dashboard (listening at port tcp/7000 inside the rook-ceph-mgr pod) in an environment where IPv6 is disabled on hosts?

The following are errors captured in the ceph-mgr log:
```
ceph-mgr: log_channel (cluster) log[ERR]: Unhanded exception from module 'dashboard' while running on mgr.a: error('No socket could be created',)
ceph-mgr: dashboard serve:
ceph-mgr: Traceback (most recent call last)
ceph-mgr: File "/usr/lib64/ceph/mgr/dashboard/module.py", line 1082, in serve
ceph-mgr: cherrypy.engine.start()
ceph-mgr: File "usr/lib64/python2.7/site-packages/cherrypy/process/wspbus.py", line 250, in start
ceph-mgr:   raise e_info
ceph-mgr: ChannelFailures: error('No socket could be created',)
```

Does anyone know how to config the ceph-mgr pod so the cepth dashboard will use ipv4 only?

**Comment by galexrt** [comment]
@dmick @liewegas @travisn any idea what might cause this issue? Only thing I can think of would be that either Rook or Ceph explicitly request to listen on, e.g., `[::]:7000` instead of seeing that no IPv6 is available and using `0.0.0.0:7000`.

@kcao3 Out of personal interest, may I ask why IPv6 is disabled? I find it rather uncommon that one has IPv6 disabled on the servers (e.g., instead of just not advertising IPv6 through DHCP and so on).

**Comment by kcao3** [comment]
Here's what I found: https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/module.py#L119
server_addr = self.get_localized_config('server_addr', '::')
Is there a way to set the localized config in rook's Ceph so that the server_addr variable is set to '0.0.0.0' instead of '::' when the ceph-mgr pod is launched?

**Comment by dmick** [comment]
So, I'm a bit confused; the server port defaults to 8443 for SSL and 8080 for non-SSL; unless it's set in the ceph configuration, which I don't see, those ports should be the local listening ports.  It's entirely possible I'm missing where it's set.

**Comment by dmick** [comment]
in any event, you can certainly explicitly set the server_addr config value, too, although I'm surprised cherrypy fails rather than simply listening on the v4 address.

**Comment by kcao3** [comment]
How to explicitly set the server_address value? Can this be set in a config file somewhere when starting the rook-ceph-mgr pod? Right now I have to hack the dashboard module.py by mounting in as a k8s ConfigMap.

**Comment by dmick** [comment]
You can set it with a "ceph config" command.  I'm looking for mechanisms to run such commands defined in the container and not finding anything yet, but you can certainly use the ceph CLI "by hand" from the ceph toolbox pod to set the values.  ```ceph config set mgr mgr/dashboard/a/server_addr 0.0.0.0``` should do it, and then you'll need to restart the ceph-mgr.

**Comment by Kralor-Guldan** [comment]
Fixing this issue automatically via Rook would be awesome. 

We have IPV6 turned off in our High Performance clusters for stability, and this issue has been driving me nuts until I found this ticket.
