### ISSUE TITLE
Enable external Ceph cluster volume provisioning

### ISSUE THREAD

**Issue by galexrt** [rook/rook#2175]
**Is this a bug report or feature request?**
* Feature Request

**Feature Request**

**What should the feature do:**
The feature should allow the existing Rook Ceph mounting logic to be used with "external" Ceph cluster (~ not managed by Rook Ceph operator).

**What would be solved through this feature:**
Allowing to use the Rook Ceph mounting logic for non in Kubernetes Rook Ceph clusters.

**Does this have an impact on existing features:**
Depending on the implementation not too much.
I'm currently thinking if introducing new fields for the StorageClass which "toggle" external Ceph cluster volume provisioning is enough, because I would like to prevent to introduce two new provisioners (RBD and CephFS).
Example (pesudo code/yaml):
```
kind: StorageClass
Provisionier: ceph.rook.io/block (or fs)
Parameters:
  - CephMonAddresses
  - CephAdminSecret
  - CephMountSecret
  - ...
```

**Comment by travisn** [comment]
Today the rook dynamic provisioner translates to the rook flex driver. Are you saying the dynamic provisioner would also now be able to translate to the in-tree rbd and cephfs drivers? That could be an interesting feature for users who still need to use those drivers.

**Comment by travisn** [comment]
I'm thinking of the PersistentVolume being generated, just with a different PersistentVolumeSource. [Here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/provisioner/provisioner.go#L117) we generate it with the Rook flex driver as the PersistentVolumeSource. Would the source in this case be the in-tree rbd or cephfs driver? If not, I must not be understanding the feature.

**Comment by ghaering** [comment]
@galexrt it would be very interesting to get this to work. At EOS we want something like this, like we talked about when you where here.

**Comment by travisn** [comment]
Reopening... We have recently discussed an approach for this and have a [design document](https://github.com/rook/rook/blob/master/design/ceph-external-cluster.md).

**Comment by leseb** [comment]
I've started looking into this.

**Comment by mykaul** [comment]
@leseb - any updates?

**Comment by leseb** [comment]
@mykaul I'm busy on other PRs so no updates yet.

**Comment by dab-q** [comment]
I am very interested in this feature.  Unfortunately we are currently transitioning away from Rook to a model of an external Ceph cluster that isn't dependent on k8s being up and running, for resiliency and segmentation of services.  When Rook has the ability to use an external Ceph cluster, we could bring Rook back in and replace using the external rbd/cephfs provisioners (e.g., https://github.com/kubernetes-incubator/external-storage/tree/master/ceph)

**Comment by bradfitz** [comment]
Ping stale bot to keep this open, considering there's a design doc for it.

**Comment by travisn** [comment]
External clusters and dynamic provisioning are actually already supported in v1.1 with the external cluster feature and CSI driver.
