### ISSUE TITLE
Ceph CRD hangs / deadlock on deletion

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#2188]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Deletion of crd `clusters.ceph.rook.io` hangs

```
blaine-dev-caasp-admin:~ # kubectl describe crd clusters.ceph.rook.io
Name:         clusters.ceph.rook.io
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:             2018-10-04T01:12:39Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2018-10-04T01:40:45Z
  Finalizers:
    customresourcecleanup.apiextensions.k8s.io
  Generation:        1
  Resource Version:  10813962
  Self Link:         /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/clusters.ceph.rook.io
  UID:               963a4393-c772-11e8-a2da-fa163e803647
Spec:
  Group:  ceph.rook.io
  Names:
    Kind:       Cluster
    List Kind:  ClusterList
    Plural:     clusters
    Short Names:
      rcc
    Singular:  cluster
  Scope:       Namespaced
  Version:     v1beta1
Status:
  Accepted Names:
    Kind:       Cluster
    List Kind:  ClusterList
    Plural:     clusters
    Short Names:
      rcc
    Singular:  cluster
  Conditions:
    Last Transition Time:  2018-10-04T01:12:39Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2018-10-04T01:12:39Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
    Last Transition Time:  2018-10-04T01:30:11Z
    Message:               could not confirm zero CustomResources remaining: timed out waiting for the condition
    Reason:                InstanceDeletionCheck
    Status:                True
    Type:                  Terminating
Events:                    <none>
```

I believe this may be related to https://github.com/kubernetes/kubernetes/issues/60538#issuecomment-369099998
stating that crds with finalizers can deadlock.

**Expected behavior:**
Crd is deleted.

**How to reproduce it (minimal and precise):**
I'm really not sure how to repro this. I have deleted and reinstalled Rook clusters many times, and this is the first time I've seen the issue. It could be that I tried to install while the crd was still deleting and hit a corner case perfectly, but I really don't know. Maybe we wait and see if anyone experiences this issue again before investigating further. I don't think it's critical since it occurs when uninstalling/reinstalling a cluster. I thought it good to have this documented, however.

**Workaround:**
The workaround from the deadlock issue worked for me:
```kubectl patch crd/clusters.ceph.rook.io -p '{"metadata":{"finalizers":[]}}' --type=merge```

**Comment by galexrt** [comment]
@BlaineEXE Yes, it is documented, see https://rook.io/docs/rook/v0.8/ceph-teardown.html#troubleshooting.
I don't think we can really do anything more about this.
Problem at least for some users, is that the cleanup is not done in the correct order (e.g., deleting the operator first) causing the "process" of deleting PVC and stuff that will be deleted by the operator on delete to not happen and/or in the end effectively the finalizer not being released on the Ceph Cluster CRD because of that.
