### ISSUE TITLE
Rook Mon Low on Disk Space

### ISSUE THREAD

**Issue by airdos360** [rook/rook#2197]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

After deploying rook and adding 6Gb on a 500Gb cluster, I am continually getting this error on 1 of 4 mons.  On the system, there is 56% of the storage free (/var) so there is plenty of available space and on the Rook directory, only 3% used.

2018-10-06 20:05:09.019463 [INF]  Cluster is now healthy 
2018-10-06 20:05:09.019401 [INF]  Health check cleared: MON_DISK_LOW (was: mon d is low on available space) 
2018-10-06 20:00:00.000241 [WRN]  overall HEALTH_WARN mon d is low on available space 
2018-10-06 19:54:58.549499 [WRN]  Health check failed: mon d is low on available space (MON_DISK_LOW) 

**Environment**:
CENTOS 7
Kubernetes 1.12.1
Rook version v0.8.3

**Comment by pennpeng** [comment]
```
Overall status: HEALTH_ERR

    MGR_MODULE_ERROR: 2 modules have failed
    MON_DISK_LOW: mon a is low on available space
```

Environment:
CENTOS 7
Kubernetes 1.11.3
Rook version v0.9
ceph version: M

**Comment by travisn** [comment]
@airdos360 @pennpeng Is it intended to have four mons running? Typically there would only be three. Perhaps #2631 will help resolve this issue. If you're still having troubles with this, please reopen.

**Comment by mumrau** [comment]
I still face the same issue. I have 5 mons running but it shouldn't have anything to deal with it.

```
Overall status: HEALTH_WARN
MON_DISK_LOW: mon j is low on available space
```

I have plenty of space available it just feels like not enough space gets allocated to my monitor.

**Comment by grailsweb** [comment]
I have same issue on new cluster. Any tips to fix this issue.

I have setup `RookIO 1.4` cluster in Kubernetes 1.18.  with 3 nodes allocated 1TB storage on each of them.
after creating cluster. when I run the `ceph status` cluster status shows as `HEALTH_WARN` with `mon c is low on available space`. 

There is no data stored yet. why status how low on available space? How to clear this error?
```

    [root@rook-ceph-tools-6bdcd78654-sfjvl /]#  ceph  status
      cluster:
        id:     ad42764d-aa28-4da5-a828-2d87205aff08
        health: HEALTH_WARN
                mon c is low on available space
    
      services:
        mon: 3 daemons, quorum a,b,c (age 37m)
        mgr: a(active, since 36m)
        osd: 3 osds: 3 up (since 37m), 3 in (since 37m)
    
      data:
        pools:   1 pools, 1 pgs
        objects: 0 objects, 0 B
        usage:   3.0 GiB used, 3.6 TiB / 3.6 TiB avail
        pgs:     1 active+clean



```
All three node has same size storage:

  ```
  sdb                                                                                                    8:16   0  1.2T  0 disk
    └─ceph--a6cd601d--7584--4b1f--bf82--48c95437f351-osd--data--ae1bc856--8ded--4b1e--8c87--30ca0f0959a3 253:3    0  1.2T  0 lvm
    sdb                                                                                                    8:16   0  1.2T  0 disk
    └─ceph--ccaf7144--d6a0--441c--bcd5--6a09d056bd7a-osd--data--36a9b28c--7207--400a--936b--edfb3255ce0b 253:3    0  1.2T  0 lvm
    sdb                                                                                                    8:16   0  1.2T  0 disk
    └─ceph--53e9b8a9--8925--4b21--a6ea--f8e17a322d5c-osd--data--6b1e779c--a18a--4e4d--960e--73ca9473d02f 253:3    0  1.2T  0 lvm
```

Thanks
SR

**Comment by runzhliu** [comment]
Should check the root path `/var/lib/rook/mon-xxx/data` on the host where the monitor pod runs.
@sfgroups-k8s

**Comment by namaiiee2222** [comment]
> Should check the root path `/var/lib/rook/mon-xxx/data` on the host where the monitor pod runs.
> @sfgroups-k8s

couldn't we change the storage path? store on osds?

**Comment by cripperzprodigy** [comment]
rook 1.5.9 ..im getting this error too. despite having sufficient storage less than 10% of total space used in /var/lib/rook ... how to resolve this ?

**Comment by GoZippy** [comment]
were you able to sort this?

**Comment by BlaineEXE** [comment]
If you just want to change the threshold, this stackoverflow has info: https://stackoverflow.com/questions/63602827/rookio-ceph-cluster-mon-c-is-low-on-available-space-message

I suspect that compacting mon data will help for a short time, but eventually it will likely grow again. 

The ceph docs recommend 60GB of disk space per mon. (Ref: https://docs.ceph.com/en/latest/start/hardware-recommendations/#minimum-hardware-recommendations) You can make Ceph's space checking more robust by creating a separate partition on which mon data is stored. If you create a 100GB+ partition on nodes to use solely for mon data (use this as the Rook `dataDirHostPath`), Ceph will be able to more accurately determine when the mon is using too much space, and the mon's data storage abilities won't be affected by applications running on the OSD disk. If an OS application is logging a lot of information to `/var` on the host, this has been known to cause Ceph mon instabilities if the mon doesn't have its own partition.

**Comment by GeroL** [comment]
Thank you that helped a lot. I set the threshold for kubernetes garbage collection to a lower value and it immediately freed 40%. I will consider an additional partition when upgrading my KVM servers.

**Comment by blackliner** [comment]
I think there is a fundamental issue with how kubernetes does [garbage collection](https://kubernetes.io/docs/concepts/architecture/garbage-collection/) ([HighThresholdPercent](https://github.com/kubernetes/kubernetes/blob/f8930f980d2986f9e486b04c14c3e93e57bdbe12/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L305-L312) being 85%), and how ceph is configured to warn on low disk space (mon_data_avail_warn, being default to warning at 70% disk usage)
