### ISSUE TITLE
cluster.ceph.rook.io never deletes

### ISSUE THREAD

**Issue by Tabrizian** [rook/rook#2198]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```cluster.ceph.rook.io``` never gets deleted.

**Expected behavior:**
```cluster.ceph.rook.io``` becomes deleted after a couple of time.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

* Kernel (e.g. `uname -a`):

Linux k8s-master 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
On premise
* Rook version (use `rook version` inside of a Rook Pod):
latest rook beta installed using helm
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
On Premise
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
N/A

I want to get rid of rook and install it from scratch. I searched through all of the kubernetes objects and deleted everything named ```rook```. The only object that doesn't get deleted is ```cluster.ceph.rook.io "rook-ceph"```

**Comment by travisn** [comment]
@Tabrizian Did you try out the uninstall guide? https://rook.io/docs/rook/v0.8/ceph-teardown.html

**Comment by Tabrizian** [comment]
No, I just found it and it helped. Thank you very much!
