### ISSUE TITLE
ceph/mds: RemoveFilesystem deletes pools

### ISSUE THREAD

**Issue by jan--f** [rook/rook#2206]
```RemoveFilesystem``` removes a file system _and_ deletes the involved pools. Either the functions is badly named or it does too much. Imho it should be an option the remove the pools. One should be able to remove an fs instance but keep the pools (this should actually be the default).  Otherwise this might lead to unexpected data loss, if a user would like to, say rename a fs instance.

**Comment by devyanikota** [comment]
Hi, am a new contributor to ceph and rook. Working on my rook setup.
@travisn can I pick this issue up?
Thank you.

**Comment by leseb** [comment]
@devyanikota Please go ahead.

**Comment by travisn** [comment]
@devyanikota sounds good, i sent an invite so we can assign to you. 

There are some related discussions to this issue if you could refer to them. There is a [design doc](https://github.com/rook/rook/blob/master/design/external-management.md) that describes how the filesystem CRD is designed to allow for the dashboard to control when the pools are created and deleted. It is a different scenario than this issue, but it will be related. And there was discussion in #1900 leading up to that design doc that will be more directly related to this. The question is how to expose the option to not delete the pools in the filesystem CRD in a way that makes sense for the operator to handle.

**Comment by devyanikota** [comment]
@travisn @jcsp what I understood from the design doc is that we want the 'pools' fields(both metada and data pools) modified later to nil, post removal of rook filesystem for the operator to understand that the pools can be omitted.
Correct me if am wrong. Thanks.
[Diff](https://github.com/devyanikota/rook/commit/92f6dae694a534e4c9d61532e0b7c0bcad5ce02f)

**Comment by travisn** [comment]
@devyanikota Correct, if the crd does not specify pools, then the operator should not delete them. I think this scenario is already covered by [this check](https://github.com/rook/rook/blob/master/pkg/operator/ceph/file/filesystem.go#L111). Deleting both the filesystem and the pools will be skipped in this case. Does that work for you?

**Comment by travisn** [comment]
What I'd suggest is that we need a reclaim policy on our filesystem, objectstore, and pool CRDs. Taking the PV [reclaim policy](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaim-policy) as an example, the property might be:
```
  reclaimPolicy: retain | delete
```

This property would be added to the [PoolSpec](https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L143) type, which means that all of the pool, object store, and filesystem CRDs would automatically pick up the property in the yaml. 

The default policy in the examples could be `retain`, but if it isn't set at all, for backward compatibility the default might be `delete`.
 
@jan--f @leseb @bassam thoughts on this approach?

**Comment by devyanikota** [comment]
Hi, @jan--f @leseb @bassam any other thoughts?
Can I go ahead with this solution?

**Comment by leseb** [comment]
@devyanikota still interested in working on this? If so, then I'd suggest going ahead with @travisn's suggestion. Thanks.

**Comment by sebastian-philipp** [comment]
Relates to #2963 (where Rook creates pools)
