### ISSUE TITLE
OSDs not automatically started when adding nodes to existing cluster

### ISSUE THREAD

**Issue by dab-q** [rook/rook#2208]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I started up a 4 node k8s VM cluster, 1 k8s master node and 3 worker nodes.  Each VM has an additional 30GB virtual disk for Rook/Ceph to use.  Rook came up and the Ceph cluster was created, and OSDs were started on the 3 worker nodes.  Later on, after everything was up, I removed the master taint from the master node.  At that point, both the rook-discover and rook-ceph-agent pods were started on the master node, and the logs from the rook-discover pod shows that it sees the additional disk on the master node, and that it thinks it is empty.  But no osd-prepare or osd pods ever started.  The Ceph cluster is configured with `useAllNodes: true`

**Expected behavior:**
I expected that it Rook/Ceph would start up a rook-ceph-osd-prepare and then a rook-ceph-osd pod for the new disk.
When I killed the rook-ceph-operator pod, then the osd related pods were started up 

**How to reproduce it (minimal and precise):**
As described above, remove the master taint from the master node after the Ceph cluster is up and running.

**Environment**:
* OS (e.g. from /etc/os-release): SLES12SP3
* Kernel (e.g. `uname -a`): 4.4.73-5-default
* Cloud provider or hardware configuration: VirtualBox VMs
* Rook version (use `rook version` inside of a Rook Pod): 0.8.2
* Kubernetes version (use `kubectl version`): 1.10.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by BlaineEXE** [comment]
I believe @shaas has been working on this issue and has a PR nearing ready.

**Comment by leseb** [comment]
@BlaineEXE great! We were just discussing this with @travisn earlier today :-).
