### ISSUE TITLE
Ceph Nautilus: rook should enable the mgr/orchestrator modules

### ISSUE THREAD

**Issue by sebastian-philipp** [rook/rook#2213]
**Is this a bug report or feature request?**

✓ Feature Request

**What should the feature do:**
When creating a new cluster, Rook should enable the orchestror modules automatically:
```
rook-ceph-mon-a:/ # ceph orchestrator status
Error ENOTSUP: Module 'orchestrator_cli' is not enabled (required by command 'orchestrator status'): use `ceph mgr module enable orchestrator_cli` to enable it
rook-ceph-mon-a:/ # ceph mgr module enable orchestrator_cli
rook-ceph-mon-a:/ # ceph mgr module enable rook            
rook-ceph-mon-a:/ # ceph orchestrator set backend rook
rook-ceph-mon-a:/ # ceph orchestrator status
Backend: rook
Available: False (ceph-mgr not running in Rook cluster)
```

**What is use case behind this feature:**
The Rook module is especially designed to run within a Rook context. As it is a key-feature, we should start that module automatically. Especially with a possible integration into the mgr dashboard, the integration should work out of the box.

**Environment**:
* Ceph Nautilus (master)
* openSUSE Leap 15 based images

**Comment by travisn** [comment]
With #2187 merged the modules are enabled. However, there is an error where enabling rook as the backend fails, which will require an update to the base ceph image.

**Comment by travisn** [comment]
We'll track the remaining issue with #2263. With #2187 the code is now in place to enable the modules.
