### ISSUE TITLE
How to set rook-ceph-mgr HA

### ISSUE THREAD

**Issue by cnicy** [rook/rook#2227]
I am deploying according to the official documentation:
https://rook.io/docs/rook/v0.8/ceph-quickstart.html
But rook-ceph-mgr is only one 
How to set rook-ceph-mgr HA

[root@Master rook]# kubectl -n rook-ceph-system get pods -o wide
NAME                                 READY   STATUS    RESTARTS   AGE   IP                NODE       NOMINATED NODE
rook-ceph-agent-bhdks                1/1     Running   0          41m   10.211.55.5       node       <none>
rook-ceph-agent-djfmz                1/1     Running   0          41m   10.211.55.4       storage2   <none>
rook-ceph-agent-dllh7                1/1     Running   0          41m   10.211.55.6       storage1   <none>
rook-ceph-operator-79b8c85c6-5957h   1/1     Running   0          49m   192.168.167.193   node       <none>
rook-ceph-operator-79b8c85c6-mc9l4   1/1     Running   0          49m   192.168.167.194   node       <none>
rook-discover-4f7lb                  1/1     Running   0          41m   192.168.35.193    storage2   <none>
rook-discover-mt2wn                  1/1     Running   0          41m   192.168.200.1     storage1   <none>
rook-discover-wcq8v                  1/1     Running   0          41m   192.168.167.195   node       <none>`

[root@Master rook]# kubectl -n rook-ceph get pods -o wide
NAME                                   READY   STATUS      RESTARTS   AGE   IP               NODE       NOMINATED NODE
rook-ceph-mgr-a-8579579d44-slfcc       1/1     Running     0          15m   192.168.35.195   storage2   <none>
rook-ceph-mon-a-6c479f8444-zdpc9       1/1     Running     0          16m   192.168.200.2    storage1   <none>
rook-ceph-mon-b-6758995598-lrrtc       1/1     Running     0          16m   192.168.35.194   storage2   <none>
rook-ceph-mon-c-6f766c779c-59f9p       1/1     Running     0          16m   192.168.200.3    storage1   <none>
rook-ceph-osd-0-66f98d78c6-8dh7v       1/1     Running     0          15m   192.168.35.197   storage2   <none>
rook-ceph-osd-1-7bdff45b68-nhnrp       1/1     Running     0          15m   192.168.200.5    storage1   <none>
rook-ceph-osd-prepare-storage1-7nmck   0/1     Completed   0          15m   192.168.200.6    storage1   <none>
rook-ceph-osd-prepare-storage2-j8tr7   0/1     Completed   0          15m   192.168.35.198   storage2   <none>

**Comment by galexrt** [comment]
Currently that is not possible due to "issues" in the Ceph MGR.

I'm closing this issue in favor of #1796 as it is tracking to run (at least) two (or more) MGRs and/or clear up if it is even viable to run more than one Ceph MGRs.
