### ISSUE TITLE
add ROOK_HOSTPATH_REQUIRES_PRIVILEGED to operator helm chart

### ISSUE THREAD

**Issue by jamstar** [rook/rook#2228]
in https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml
exists 
- name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
  value: "false"

I run centos with selinx on my environment so had to add this manually to the https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/deployment.yaml.  It would be really nice if this was added to the helm operator chart as a helm variable so i could just set it instead of needing to add it.

**Comment by galexrt** [comment]
@jamstar Would you like to open a PR to add this to the Helm chart?

**Comment by jamstar** [comment]
sure! ive never done one before on github so i will have to work through it.  but it sounds like fun! ill start working on it next week.

**Comment by travisn** [comment]
@jamstar that would be great, let us know what questions you have along the way! To get started, you'll want to follow our [development guide](https://rook.io/docs/rook/v0.8/development-flow.html) to create a fork, branch, etc.

**Comment by jamstar** [comment]
I haven't forgotten about this, just had some other work stuff

**Comment by galexrt** [comment]
Added in #2737 and backported to v0.9 in #2739.
