### ISSUE TITLE
Cockroach operator: Add resource limits to Cockroach pods

### ISSUE THREAD

**Issue by EdSchouten** [rook/rook#2232]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Right now, resource limits for Cockroach containers cannot be specified. They are created without any limits in place. Ideally, the cluster configuration should allow you to specify the amount of CPU and memory.

**What is use case behind this feature:**
There are clusters on which per-container resource limits are enforced. We happen to have a cluster where we give all containers without resource limits an excruciatingly low limit, just to make sure people take the time to set up limits.

This means that Cockroach currently crashloops on startup, except if we go in and edit the statefulset manually. The question is, do we want the controller to set up those limits, or do we expect our users to edit the statefulsets manually?

**Comment by dark-shade** [comment]
I can work on this if this is still required

**Comment by jbw976** [comment]
that would be great @dark-shade, please do feel free to take on this work if you have some cycles to contribute! 🙇‍♂️

**Comment by dark-shade** [comment]
Awesome, on it :)

**Comment by travisn** [comment]
Closing the stale issue
