### ISSUE TITLE
Rook Cluster Update not work (cannot add node to ceph cluster automatically when new node added to K8s)

### ISSUE THREAD

**Issue by apacoco9861** [rook/rook#2235]
**Is this a bug report or feature request?** Yes
* Bug Report

**Deviation from expected behavior:** New nodes added to k8s but not reflected to cluster update.

**Expected behavior:** New nodes added are expected to join rook-ceph cluster

**How to reproduce it (minimal and precise):**

**Environment**: Ubuntu 18.04
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): `Linux pro-docker-2-62 4.15.0-36-generic 39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: self-own
* Rook version (use `rook version` inside of a Rook Pod):  rook: `v0.8.0-248.g0c32013`
* Kubernetes version (use `kubectl version`): `1.12.1`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Self-own K8s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

```
kubectl -n rook-ceph edit cluster.ceph.rook.io rook-ceph

apiVersion: ceph.rook.io/v1beta1
kind: Cluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ceph.rook.io/v1beta1","kind":"Cluster","metadata":{"annotations":{},"name":"rook-ceph","namespace":"rook-ceph"},"spec":{"dashboard":{"enabled":true},"dataDirHostPath":"/var/lib/rook","mon":{"allowMultiplePerNode":true,"count":3},"network":{"hostNetwork":false},"resources":null,"serviceAccount":"rook-ceph-cluster","storage":{"config":null,"deviceFilter":null,"location":null,"useAllDevices":true,"useAllNodes":true}}}
  creationTimestamp: 2018-10-16T07:56:03Z
  finalizers:
  - cluster.ceph.rook.io
  generation: 1
  name: rook-ceph
  namespace: rook-ceph
  resourceVersion: "1494227"
  selfLink: /apis/ceph.rook.io/v1beta1/namespaces/rook-ceph/clusters/rook-ceph
  uid: ee29c95b-d118-11e8-a3c2-005056b224f1
spec:
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: true
    count: 3
  network:
    hostNetwork: false
  serviceAccount: rook-ceph-cluster
  storage:
    useAllDevices: true
    useAllNodes: true
status:
  state: Created


root@pro-docker-2-62:~/rook/cluster/examples/kubernetes/ceph# kubectl -n rook-ceph get all
NAME                                               READY   STATUS      RESTARTS   AGE
pod/rook-ceph-mgr-a-bd7857c5d-6rszn                1/1     Running     1          6d22h
pod/rook-ceph-mon-a-7459db8b6d-246tw               1/1     Running     1          6d22h
pod/rook-ceph-mon-b-b4568f85b-q7qrf                1/1     Running     1          6d22h
pod/rook-ceph-mon-c-654869999c-hnjjh               1/1     Running     1          6d22h
pod/rook-ceph-osd-0-5bd7c6f65c-f48bf               1/1     Running     1          6d22h
pod/rook-ceph-osd-1-8d7b87977-h6k89                1/1     Running     1          6d22h
pod/rook-ceph-osd-2-5c656b9f47-ltkkx               1/1     Running     1          6d22h
pod/rook-ceph-osd-3-869b96686f-7pr4h               1/1     Running     1          6d22h
pod/rook-ceph-osd-4-f84ff8cd4-5tdm9                1/1     Running     1          6d22h
pod/rook-ceph-osd-5-5cb87c66f9-8wtcj               1/1     Running     1          6d22h
pod/rook-ceph-osd-6-845cd956c5-w5kvb               1/1     Running     1          6d22h
pod/rook-ceph-osd-prepare-pro-docker-2-178-f2stj   0/1     Completed   0          3d22h
pod/rook-ceph-osd-prepare-pro-docker-2-179-w45bq   0/1     Completed   0          3d22h
pod/rook-ceph-osd-prepare-pro-docker-2-180-x474j   0/1     Completed   0          3d22h
pod/rook-ceph-osd-prepare-pro-docker-2-63-bn2ws    0/1     Completed   0          3d22h
pod/rook-ceph-osd-prepare-pro-docker-2-64-5qsnn    0/1     Completed   0          3d22h
pod/rook-ceph-osd-prepare-pro-docker-2-65-s4bb4    0/1     Completed   0          3d22h
pod/rook-ceph-osd-prepare-pro-docker-2-66-742fh    0/1     Completed   0          3d22h
pod/rook-ceph-osd-prepare-pro-docker-2-67-m2v25    0/1     Completed   0          3d22h
pod/rook-ceph-osd-prepare-sys-docker-2-28-rdhgp    0/1     Completed   0          3d22h
pod/rook-ceph-tools-5bc8b8f97-6c54k                1/1     Running     1          6d22h

NAME                                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/rook-ceph-mgr                      ClusterIP   10.111.184.122   <none>        9283/TCP         6d22h
service/rook-ceph-mgr-dashboard            ClusterIP   10.106.214.203   <none>        7000/TCP         6d22h
service/rook-ceph-mgr-dashboard-external   NodePort    10.109.91.63     <none>        7000:30002/TCP   6d22h
service/rook-ceph-mon-a                    ClusterIP   10.102.227.170   <none>        6790/TCP         6d22h
service/rook-ceph-mon-b                    ClusterIP   10.99.99.205     <none>        6790/TCP         6d22h
service/rook-ceph-mon-c                    ClusterIP   10.101.132.88    <none>        6790/TCP         6d22h

NAME                              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rook-ceph-mgr-a   1         1         1            1           6d22h
deployment.apps/rook-ceph-mon-a   1         1         1            1           6d22h
deployment.apps/rook-ceph-mon-b   1         1         1            1           6d22h
deployment.apps/rook-ceph-mon-c   1         1         1            1           6d22h
deployment.apps/rook-ceph-osd-0   1         1         1            1           6d22h
deployment.apps/rook-ceph-osd-1   1         1         1            1           6d22h
deployment.apps/rook-ceph-osd-2   1         1         1            1           6d22h
deployment.apps/rook-ceph-osd-3   1         1         1            1           6d22h
deployment.apps/rook-ceph-osd-4   1         1         1            1           6d22h
deployment.apps/rook-ceph-osd-5   1         1         1            1           6d22h
deployment.apps/rook-ceph-osd-6   1         1         1            1           6d22h
deployment.apps/rook-ceph-tools   1         1         1            1           6d22h

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/rook-ceph-mgr-a-bd7857c5d    1         1         1       6d22h
replicaset.apps/rook-ceph-mon-a-7459db8b6d   1         1         1       6d22h
replicaset.apps/rook-ceph-mon-b-b4568f85b    1         1         1       6d22h
replicaset.apps/rook-ceph-mon-c-654869999c   1         1         1       6d22h
replicaset.apps/rook-ceph-osd-0-5bd7c6f65c   1         1         1       6d22h
replicaset.apps/rook-ceph-osd-1-8d7b87977    1         1         1       6d22h
replicaset.apps/rook-ceph-osd-2-5c656b9f47   1         1         1       6d22h
replicaset.apps/rook-ceph-osd-3-869b96686f   1         1         1       6d22h
replicaset.apps/rook-ceph-osd-4-f84ff8cd4    1         1         1       6d22h
replicaset.apps/rook-ceph-osd-5-5cb87c66f9   1         1         1       6d22h
replicaset.apps/rook-ceph-osd-6-845cd956c5   1         1         1       6d22h
replicaset.apps/rook-ceph-tools-5bc8b8f97    1         1         1       6d22h

NAME                                               COMPLETIONS   DURATION   AGE
job.batch/rook-ceph-osd-prepare-pro-docker-2-178   1/1           2s         3d22h
job.batch/rook-ceph-osd-prepare-pro-docker-2-179   1/1           2s         3d22h
job.batch/rook-ceph-osd-prepare-pro-docker-2-180   1/1           2s         3d22h
job.batch/rook-ceph-osd-prepare-pro-docker-2-63    1/1           2s         3d22h
job.batch/rook-ceph-osd-prepare-pro-docker-2-64    1/1           2s         3d22h
job.batch/rook-ceph-osd-prepare-pro-docker-2-65    1/1           2s         3d22h
job.batch/rook-ceph-osd-prepare-pro-docker-2-66    1/1           2s         3d22h
job.batch/rook-ceph-osd-prepare-pro-docker-2-67    1/1           3s         3d22h
job.batch/rook-ceph-osd-prepare-sys-docker-2-28    1/1           3s         3d22h
root@pro-docker-2-62:~/rook/cluster/examples/kubernetes/ceph# kubectl get nodes
NAME               STATUS   ROLES    AGE     VERSION
pro-docker-2-178   Ready    <none>   7d3h    v1.12.1
pro-docker-2-179   Ready    <none>   7d3h    v1.12.1
pro-docker-2-180   Ready    <none>   6d23h   v1.12.1
pro-docker-2-62    Ready    master   7d3h    v1.12.1
pro-docker-2-63    Ready    <none>   7d3h    v1.12.1
pro-docker-2-64    Ready    <none>   7d3h    v1.12.1
pro-docker-2-65    Ready    <none>   7d3h    v1.12.1
pro-docker-2-66    Ready    <none>   7d3h    v1.12.1
pro-docker-2-67    Ready    <none>   7d3h    v1.12.1
**sys-ceph-2-25      Ready    <none>   3h32m   v1.12.1**
sys-docker-2-28    Ready    <none>   7d3h    v1.12.1
**sys-gitlab-2-147   Ready    <none>   29h     v1.12.1**

#two newly added nodes not in cluster automatically. Any way to have them in?
sys-ceph-2-25      Ready    <none>   3h32m   v1.12.1
sys-gitlab-2-147   Ready    <none>   29h     v1.12.1
```

**Comment by jbw976** [comment]
@apacoco9861 does this comment help explain your case? https://github.com/rook/rook/issues/2112#issuecomment-427142789

Do you have the rook-ceph operator logs?

**Comment by apacoco9861** [comment]
Thanks for your information. It works. Many thanks.

I have added operator.yaml
        - name: DISCOVER_TOLERATION
          value: "PreferNoSchedule"
        - name: AGENT_TOLERATION
          value: "PreferNoSchedule"
        - name: OSD_TOLERATION
          value: "PreferNoSchedule"


root@pro-docker-2-62:~/rook/cluster/examples/kubernetes/ceph# kubectl -n rook-ceph get all
NAME                                               READY   STATUS      RESTARTS   AGE
pod/rook-ceph-mgr-a-bd7857c5d-6rszn                1/1     Running     1          7d17h
pod/rook-ceph-mon-a-7459db8b6d-246tw               1/1     Running     1          7d17h
pod/rook-ceph-mon-b-b4568f85b-q7qrf                1/1     Running     1          7d17h
pod/rook-ceph-mon-c-654869999c-hnjjh               1/1     Running     1          7d17h
pod/rook-ceph-osd-0-5bd7c6f65c-f48bf               1/1     Running     1          7d17h
pod/rook-ceph-osd-1-8d7b87977-h6k89                1/1     Running     1          7d17h
pod/rook-ceph-osd-2-5c656b9f47-ltkkx               1/1     Running     1          7d17h
pod/rook-ceph-osd-3-869b96686f-7pr4h               1/1     Running     1          7d17h
pod/rook-ceph-osd-4-f84ff8cd4-5tdm9                1/1     Running     1          7d17h
pod/rook-ceph-osd-5-5cb87c66f9-8wtcj               1/1     Running     1          7d17h
pod/rook-ceph-osd-6-845cd956c5-w5kvb               1/1     Running     1          7d17h
pod/rook-ceph-osd-prepare-pro-docker-2-178-2gnbr   0/1     Completed   0          9m10s
pod/rook-ceph-osd-prepare-pro-docker-2-179-g7xb2   0/1     Completed   0          9m8s
pod/rook-ceph-osd-prepare-pro-docker-2-180-4wk7n   0/1     Completed   0          9m6s
pod/rook-ceph-osd-prepare-pro-docker-2-63-n4ztg    0/1     Completed   0          9m4s
pod/rook-ceph-osd-prepare-pro-docker-2-64-z5xx6    0/1     Completed   0          9m2s
pod/rook-ceph-osd-prepare-pro-docker-2-65-jkzg2    0/1     Completed   0          9m
pod/rook-ceph-osd-prepare-pro-docker-2-66-2vqcb    0/1     Completed   0          8m57s
pod/rook-ceph-osd-prepare-pro-docker-2-67-fqfdk    0/1     Completed   0          8m55s
pod/rook-ceph-osd-prepare-sys-ceph-2-25-8kwwz      0/1     Completed   0          8m55s
pod/rook-ceph-osd-prepare-sys-docker-2-28-cgtmf    0/1     Completed   0          8m53s
pod/rook-ceph-osd-prepare-sys-gitlab-2-147-c9khq   0/1     Completed   0          8m53s
pod/rook-ceph-tools-5bc8b8f97-6c54k                1/1     Running     1          7d17h

NAME                                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/rook-ceph-mgr                      ClusterIP   10.111.184.122   <none>        9283/TCP         7d17h
service/rook-ceph-mgr-dashboard            ClusterIP   10.106.214.203   <none>        7000/TCP         7d17h
service/rook-ceph-mgr-dashboard-external   NodePort    10.109.91.63     <none>        7000:30002/TCP   7d17h
service/rook-ceph-mon-a                    ClusterIP   10.102.227.170   <none>        6790/TCP         7d17h
service/rook-ceph-mon-b                    ClusterIP   10.99.99.205     <none>        6790/TCP         7d17h
service/rook-ceph-mon-c                    ClusterIP   10.101.132.88    <none>        6790/TCP         7d17h

NAME                              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rook-ceph-mgr-a   1         1         1            1           7d17h
deployment.apps/rook-ceph-mon-a   1         1         1            1           7d17h
deployment.apps/rook-ceph-mon-b   1         1         1            1           7d17h
deployment.apps/rook-ceph-mon-c   1         1         1            1           7d17h
deployment.apps/rook-ceph-osd-0   1         1         1            1           7d17h
deployment.apps/rook-ceph-osd-1   1         1         1            1           7d17h
deployment.apps/rook-ceph-osd-2   1         1         1            1           7d17h
deployment.apps/rook-ceph-osd-3   1         1         1            1           7d17h
deployment.apps/rook-ceph-osd-4   1         1         1            1           7d17h
deployment.apps/rook-ceph-osd-5   1         1         1            1           7d17h
deployment.apps/rook-ceph-osd-6   1         1         1            1           7d17h
deployment.apps/rook-ceph-tools   1         1         1            1           7d17h

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/rook-ceph-mgr-a-bd7857c5d    1         1         1       7d17h
replicaset.apps/rook-ceph-mon-a-7459db8b6d   1         1         1       7d17h
replicaset.apps/rook-ceph-mon-b-b4568f85b    1         1         1       7d17h
replicaset.apps/rook-ceph-mon-c-654869999c   1         1         1       7d17h
replicaset.apps/rook-ceph-osd-0-5bd7c6f65c   1         1         1       7d17h
replicaset.apps/rook-ceph-osd-1-8d7b87977    1         1         1       7d17h
replicaset.apps/rook-ceph-osd-2-5c656b9f47   1         1         1       7d17h
replicaset.apps/rook-ceph-osd-3-869b96686f   1         1         1       7d17h
replicaset.apps/rook-ceph-osd-4-f84ff8cd4    1         1         1       7d17h
replicaset.apps/rook-ceph-osd-5-5cb87c66f9   1         1         1       7d17h
replicaset.apps/rook-ceph-osd-6-845cd956c5   1         1         1       7d17h
replicaset.apps/rook-ceph-tools-5bc8b8f97    1         1         1       7d17h

NAME                                               COMPLETIONS   DURATION   AGE
job.batch/rook-ceph-osd-prepare-pro-docker-2-178   1/1           2s         9m10s
job.batch/rook-ceph-osd-prepare-pro-docker-2-179   1/1           2s         9m8s
job.batch/rook-ceph-osd-prepare-pro-docker-2-180   1/1           2s         9m6s
job.batch/rook-ceph-osd-prepare-pro-docker-2-63    1/1           2s         9m4s
job.batch/rook-ceph-osd-prepare-pro-docker-2-64    1/1           2s         9m2s
job.batch/rook-ceph-osd-prepare-pro-docker-2-65    1/1           2s         9m
job.batch/rook-ceph-osd-prepare-pro-docker-2-66    1/1           2s         8m57s
job.batch/rook-ceph-osd-prepare-pro-docker-2-67    1/1           2s         8m55s
job.batch/rook-ceph-osd-prepare-sys-ceph-2-25      1/1           2s         8m55s
job.batch/rook-ceph-osd-prepare-sys-docker-2-28    1/1           3s         8m53s
job.batch/rook-ceph-osd-prepare-sys-gitlab-2-147   1/1           2s         8m53s

root@pro-docker-2-62:~/rook/cluster/examples/kubernetes/ceph# kubectl -n rook-ceph exec -it rook-ceph-tools-5bc8b8f97-6c54k bash
bash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory
[root@pro-docker-2-178 /]# ceph osd tree|grep host
 -2       0.46819     host pro-docker-2-180
 -3       0.97989     host pro-docker-2-63
 -4       0.97989     host pro-docker-2-64
 -9       0.46819     host pro-docker-2-65
-11       0.46819     host pro-docker-2-66
-15       0.46819     host pro-docker-2-67
-13       0.46819     host sys-docker-2-28

**Comment by apacoco9861** [comment]
when you kubectl delete pro-docker-2-66 and kubeadm --join, the rook cluster still unable to detect.

need to manual change operator.yml and cluster.yml
to comment and comment out
(in operator.yml)
- name: DISCOVER_TOLERATION
value: "PreferNoSchedule"
- name: AGENT_TOLERATION
value: "PreferNoSchedule"
- name: OSD_TOLERATION
value: "PreferNoSchedule"

(in cluster.yml) switch useAllNodes to false, apply -f and switch back to true
    useAllNodes: true
    useAllDevices: true

Only second hard disk (sdb in which ceph and ceph-common required installed before and ceph will partition it) could be detected.  Not sure if it is normal. Kindly advise.

**Comment by BlaineEXE** [comment]
Seems to be a duplicate of https://github.com/rook/rook/issues/2208. Marking as such.
