### ISSUE TITLE
failed to run rook ceph agent. failed to create volume manager Failed to complete 'check builtin kmod': exit status 1

### ISSUE THREAD

**Issue by rocket1024** [rook/rook#2236]
failed to run rook ceph agent. failed to create volume manager Failed to complete 'check builtin kmod': exit status 1

rook-ceph-system   rook-ceph-agent-nlmgm                              0/1     CrashLoopBackOff   6          7m34s
rook-ceph-system   rook-ceph-agent-ss5mf                              0/1     CrashLoopBackOff   6          7m34s
rook-ceph-system   rook-ceph-agent-xp7rd                              0/1     CrashLoopBackOff   6          7m34s
rook-ceph-system   rook-ceph-operator-7bbc5b99b8-49xh7                1/1     Running            0          7m35s
rook-ceph-system   rook-discover-nd2bj                                1/1     Running            0          7m34s
rook-ceph-system   rook-discover-tp5pw                                1/1     Running            0          7m34s
rook-ceph-system   rook-discover-vz67d                                1/1     Running            0          7m34s

yes, but no similar issue occurs
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
agent not running
**Expected behavior:**
agent should be running
**How to reproduce it (minimal and precise):**
kubectl create -f operator.yaml

latest rook from git
latest conjure-up kubernates over lxd
**Environment**:
* OS (e.g. from /etc/os-release):ubuntu16.04
* Kernel (e.g. `uname -a`): 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:xeon2680v2
* Rook version (use `rook version` inside of a Rook Pod):latest git
* Kubernetes version (use `kubectl version`):v1.12.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):lxd
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):default

**Comment by rocket1024** [comment]
WA by using below helm install, close it

helm repo add rook-beta https://charts.rook.io/beta
helm install --namespace rook-ceph-system rook-beta/rook-ceph

**Comment by n4zim** [comment]
I @rocket1024, I have the exact same issue that you had but for me nothing works... 

I tried several versions of Rook but it does the error all the time. 

Maybe you have something that could help me? Thank you!
