### ISSUE TITLE
capture ceph-csi integration plan discussion

### ISSUE THREAD

**Issue by rootfs** [rook/rook#2238]
This is to capture chats and community discussions around ceph-csi integration

The initial csi deployment is to leverage [existing ceph-csi deployments](https://github.com/ceph/ceph-csi/tree/master/deploy) . #2234 has a detail walkthrough.

Second stage is to import ceph-csi pkg and build a `rookflex` equivalent executable. Rook operator will create appropriate deployment for the executable on kubernetes 1.12+. This work will start once ceph-csi work stablizes, namely:

- ceph-csi passes csi tests
- Issue https://github.com/ceph/ceph-csi/issues/66 is resolved
- No major changes or work on latest csi spec.

@travisn @mickymiek @gman0

**Comment by gman0** [comment]
I'll pick up https://github.com/ceph/ceph-csi/issues/66 right after the summit if nobody else will do so by then.

**Comment by rootfs** [comment]
cc @rohan47

**Comment by travisn** [comment]
With the merge of #2580 I believe we're well past this issue
