### ISSUE TITLE
Creating a PVC takes a long time (~30 seconds)

### ISSUE THREAD

**Issue by lbogdan** [rook/rook#2248]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Creating a ceph PVC takes a long time (~30 seconds).

**Expected behavior:**
Creating a ceph PVC should take a few seconds.

**How to reproduce it (minimal and precise):**
Create a ceph PVC when 1000+ PVCs already present.

**Environment**:
Not relevant.

Looking at the source, [`CreateImage()`](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/client/image.go#L68) creates the ceph RBD image using `ExecuteRBDCommandNoFormat()`, and then, in order to verify that the image was created successfully, it calls [`ListImages()`](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/client/image.go#L41), which in turn executes `rbd ls -l ...`. The issue is that when the pool has thousands of images, that command is **very slow**.

Let me give you some numbers:
- An excerpt from the operator log:
```
2018-10-30 18:53:00.292968 I | op-provisioner: creating volume with configuration {pool:rbd clusterNamespace:rook-ceph fstype:ext4}
2018-10-30 18:53:00.293029 I | exec: Running command: rbd create rbd/pvc-[redacted] --size 4096 --cluster=[...]
2018-10-30 18:53:00.490360 I | exec: Running command: rbd ls -l rbd --cluster=[...] --format json
2018-10-30 18:53:28.484493 I | op-provisioner: Rook block image created: pvc-[redacted]
2018-10-30 18:53:28.486023 I | op-provisioner: successfully created Rook Block volume &FlexVolumeSource{Driver:ceph.rook.io/rook-ceph-system,FSType:ext4,SecretRef:nil,ReadOnly:false,Options:map[string]string{clusterNamespace: rook-ceph,image: pvc-[redacted],pool: rbd,storageClass: rook-ceph-block,},}
```
You can see that the time difference between the 3rd and 4th message is ~28 seconds.
- Running `rbd ls -l` command directly on the operator:
```
$ time kubectl -n rook-ceph-system exec -it rook-ceph-operator-[redacted] -- rbd ls -l rbd | wc -l
3255

real    0m22.524s
user    0m0.134s
sys     0m0.021s
```
You can see the number of existing images, and the time varying a bit, although it's never <20 seconds.

## Potential solution
Instead of doing `rbd ls -l` to list all the images and then [iterate them to find the newly created one](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/client/image.go#L105), it's possible to directly run `rbd info [<pool-name>/]<image-name> --format json` to get the image info:
```
time kubectl -n rook-ceph-system exec -it rook-ceph-operator-[redacted] -- rbd info rbd/pvc-[redacted] --format json
{"name":"pvc-[redacted]","id":"[redacted]","size":4294967296,"objects":1024,"order":22,"object_size":4194304,"block_name_prefix":"rbd_data.[redacted]","format":2,"features":["layering"],"op_features":[],"flags":[],"create_timestamp":"Tue Oct 30 18:50:48 2018"}

real    0m0.354s
user    0m0.108s
sys     0m0.045s
```
which includes all the fields of [`CephBlockImage` struct](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/client/image.go#L35).

**Comment by travisn** [comment]
since we know the pool and image name, I don't see any reason we would iterate through all of them. makes sense to query directly for the one needed.
