### ISSUE TITLE
true/false values in Affinity section

### ISSUE THREAD

**Issue by lkhomenk** [rook/rook#2249]
* Bug Report

**Deviation from expected behavior:**
cluster creation with such affinity will fail
```placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: compute
              operator: In
              values:
              - true
```
with operator error like:
```
reflector.go:205] github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:76: Failed to list *v1beta1.Cluster: v1beta1.ClusterList: Items: []v1beta1.Cluster: v1beta1.Cluster: Spec: v1beta1.ClusterSpec: Placement: v1alpha2.Placement: NodeAffinity: v1.NodeAffinity: RequiredDuringSchedulingIgnoredDuringExecution: v1.NodeSelector: NodeSelectorTerms: []v1.NodeSelectorTerm: v1.NodeSelectorTerm: MatchExpressions: []v1.NodeSelectorRequirement: v1.NodeSelectorRequirement: Values: []string: ReadString: expects " or n, but found t, error found in #10 byte of ...|values":[true]}]}]}}|..., bigger context ...|compute","operator":"In","values":[true]}]}]}}}},"resources":null,"serviceAccount":"ro|...
```
quoted values are just fine

**How to reproduce it (minimal and precise):**
create cluster with affinity similar to above 

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Rook version (use `rook version` inside of a Rook Pod): 0.8.3
* Kubernetes version (use `kubectl version`): 1.10.0+b81c8f8"
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
This is not a "direct" issue with Rook. The Kubernetes `nodeAffinity` structure does only take values of type `string` in the `values` list.
See the Kubernetes API reference https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#nodeselectorrequirement-v1-core.

An issue exists to implement CRD validation which will then hopefully prevent a malformed object to be "deployed" to Kubernetes and causing such an issue for the operator. See #1539.

Please close if you see that the #1539 fits to fix your issue and/or the documentation provided helped.

**Comment by lkhomenk** [comment]
@galexrt  thanks for pointing that out. that issues covers this one totally
