### ISSUE TITLE
Discovery not working with CRI-O >= 1.11.7

### ISSUE THREAD

**Issue by jnummelin** [rook/rook#2252]
**Is this a bug report or feature request?**
* Bug Report

Mainly to give heads-up for other users running with CRI-O and to track the related CRI-O issue.

**Deviation from expected behavior:**
Discovery pod broken:
```
2018-11-01 07:16:15.909661 I | rook-discover: failed to probe devices: failed initial hardware discovery. failed to list all devices: Failed to complete 'lsblk all': open /dev/null: permission denied. 
2018-11-01 07:16:15.909738 I | rook-discover: failed to update device configmap: failed initial hardware discovery. failed to list all devices: Failed to complete 'lsblk all': open /dev/null: permission denied. 
failed initial hardware discovery. failed to list all devices: Failed to complete 'lsblk all': open /dev/null: permission denied.
```

**Expected behavior:**

Smooth sailing :)

**How to reproduce it (minimal and precise):**

Run Rook with CRI-O runtime, version 1.11.7+. 1.11.6 (and I expect older ones too) work without problems.

The underlying CRI-O issue is this: https://github.com/kubernetes-sigs/cri-o/issues/1881

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 16.04.5 LTS`
* Kernel (e.g. `uname -a`): `Linux demo-pharos-worker-0 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: DO droplets
* Rook version (use `rook version` inside of a Rook Pod): `rook: v0.8.3`
* Kubernetes version (use `kubectl version`): 1.11.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kontena Pharos
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): 
```
open /dev/null: permission denied
```

**Comment by travisn** [comment]
@jnummelin thanks for reporting so other users can be aware of the issue. just to be clear, there is no change you're expecting on rook's side, right?

**Comment by jnummelin** [comment]
> there is no change you're expecting on rook's side, right?

Nope, no changes should be needed as this seems to be fully a bug on CRI-O side how they add some default flags to host mounts.
