### ISSUE TITLE
Rook is deleting OSDs from nodes which are temporarily disabled

### ISSUE THREAD

**Issue by dimm0** [rook/rook#2253]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently rook operator is checking whether OSD tolerations allow OSDs to be running on every node, and if not, the OSDs will silently not be created on a node. Also it will REMOVE the OSDs from such a node on restart if it finds that tolerations are not matching. This causes 2 issues:
1st issue:
https://github.com/rook/rook/issues/2235
https://github.com/rook/rook/issues/2112#issuecomment-434176672

It's really hard to debug what rook didn't like. If you just let ReplicaSets try to create the pods, it will be obvious why it's failing, and easy to fix the issue.

2nd issue:
If I temporary cordon a node to prevent user jobs from running in it and operator restarts, it will delete all OSDs from the node. I'd definitely not want that.

**Environment**:
N/A

**Comment by BlaineEXE** [comment]
Noting test cases:
- `useAllNodes: true` and `useAllDevices: true`: Rook should continue its current behavior. #2741 will eventually make Rook remove osds from nodes more gracefully.

- `useAllDevices: false` (don't care value of `useAllNodes`)
  - user changes global device filter in CRD: Rook removes osds for disks that no longer apply on all nodes
  - user changes global devices specified in CRD: rook removes osds for disks that no longer apply on all nodes
  - disk fails on one node, Rook will not remove that osd
  - `useAllNodes: false`
    - user changes device filter of node in CRD: Rook removes osds for disks that no longer apply on that node
    - user changes devices specified in CRD: Rook removes osds for disks that no longer apply on that node

- `useAllNodes: false` (don't care value of `useAllDevices`)
  - node removed from CRD: rook removes node
  - osd `placement` is used, and a node's osd placement label is removed: Rook removes node
  - node fails or is made unschedulable other than by placement label: Rook will not remove osds on that node
  - `useAllDevices: false`
    - disk is removed from an individual node's spec: Rook will remove that osd
  
- don't care value of `useAllNodes` or `useAllDevices`
  - user changes the global `directories` list: rook removes osds for directories that no longer apply on all nodes
  - dir-based osd fails: Rook does not remove that osd
  - `useAllNodes: false`
    - user changes directories list for a node: rook removes osds for directories that no longer apply on that node

**Comment by travisn** [comment]
To summarize the code changes for this issue, is all we need to do is ensure that we only remove OSDs that are a result of the user updating the CRD `nodes` or `devices` list *and* `useAllNodes: false`? Or in other words, if the K8s node status changes, we should never automatically remove an OSD.

**Comment by rohantmp** [comment]
@travisn I think we need to be able to modify the OSD timeout based on predictions of the downtime. Eg: We know a node is going to be down for ~15 minutes for maintenance. However, to do this, we need to be able to mark noout on the osd level: https://tracker.ceph.com/issues/38940

**Comment by travisn** [comment]
@rohantmp This is a specific issue about rook aggressively removing OSDs when it is not intended. Let's track the behavior around maintenance and marking osds as `noout` with #2825. Also #2741 is related.

**Comment by BlaineEXE** [comment]
Agreed, @rohantmp. I think this feature fits pretty squarely in the realm of Ceph's responsibilities. I imagine a user setting `noout` for a node's osds via Ceph's admin CLI (or the dashboard), doing maintenance, and then unsetting `noout` via the same method.
