### ISSUE TITLE
Container mounting CephFS with fsGroup stuck in ContainerCreating

### ISSUE THREAD

**Issue by dimm0** [rook/rook#2254]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Starting the container with this definition:

```
apiVersion: v1
kind: Pod
metadata:
  name: test3
  namespace: jupyterlab
spec:
  containers:
  - args:
    - "sleep"
    - "1000000000"
    image: busybox
    name: notebook
    volumeMounts:
    - mountPath: /shared
      name: jupyter
  securityContext:
    fsGroup: 100
  volumes:
  - flexVolume:
      driver: ceph.rook.io/rook
      fsType: ceph
      options:
        clusterNamespace: rook
        fsName: nautilusfs
        path: /jupyter
    name: jupyter
```

The container stays in "CoontainerCreating" for a long time and never starts.

Logs from rook-ceph-agent on the node:

```
2018-11-02 19:22:24.659207 I | flexdriver: mounting ceph filesystem nautilusfs on /var/lib/kubelet/pods/a0a805aa-ded4-11e8-ac6e-0cc47a6be994/volumes/ceph.rook.io~rook/jupyter
2018-11-02 19:22:24.743989 I | cephmon: parsing mon endpoints: rook-ceph-mon68=10.111.179.96:6790,rook-ceph-mon62=10.110.34.138:6790,rook-ceph-mon70=10.105.80.195:6790,rook-ceph-mon72=10.105.71.196:6790,rook-ceph-mon75=10.100.58.15:6790
2018-11-02 19:22:24.744058 I | op-mon: loaded: maxMonID=75, mons=map[rook-ceph-mon62:0xc420216180 rook-ceph-mon70:0xc420216220 rook-ceph-mon72:0xc420216340 rook-ceph-mon75:0xc4202163e0 rook-ceph-mon68:0xc420216100], mapping=&{Node:map[rook-ceph-mon68:0xc4205d2690 rook-ceph-mon70:0xc4205d26c0 rook-ceph-mon72:0xc4205d26f0 rook-ceph-mon75:0xc4205d2720 rook-ceph-mon62:0xc4205d2540] Port:map[]}
2018-11-02 19:22:24.745863 I | flexdriver: mounting ceph filesystem nautilusfs on 10.111.179.96:6790,10.110.34.138:6790,10.105.80.195:6790,10.105.71.196:6790,10.100.58.15:6790:/jupyter to /var/lib/kubelet/pods/a0a805aa-ded4-11e8-ac6e-0cc47a6be994/volumes/ceph.rook.io~rook/jupyter
2018-11-02 19:22:25.351412 I | flexdriver:
2018-11-02 19:22:25.351541 I | flexdriver: ceph filesystem nautilusfs has been attached and mounted
```

Once I comment out the fsGroup line, all works fine.

What's weird is that issue starts sometimes, and other times all works fine.

**Expected behavior:**
Containers can mount cephFS with fsGroup defined.

**How to reproduce it (minimal and precise):**
See above

**Environment**:
* OS (e.g. from /etc/os-release):
Centos 7.5
* Kernel (e.g. `uname -a`):
4.15.15
* Cloud provider or hardware configuration:
baremetal
* Rook version (use `rook version` inside of a Rook Pod):
0.8.2
* Kubernetes version (use `kubectl version`):
1.11.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
healthy (some S3 issues)

**Comment by dimm0** [comment]
Seems like it's chown'ing all the files, it takes ~14 minutes to start when mounting a folder with lots of files

**Comment by dimm0** [comment]
Does this https://github.com/kubernetes/kubernetes/issues/69699 apply to block volumes only, or flexVolumes too?

**Comment by travisn** [comment]
As an experiment we could try disabling fsgroup in the rook flex driver [here](https://github.com/rook/rook/blob/master/cmd/rookflex/cmd/init.go#L39), then implement a top-level chown instead of a recursive chown as seen in the [k8s codebase](https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/volume/volume_linux.go#L38). But that would impact all block and file mounts, not just the file mounts.

**Comment by anguslees** [comment]
Fwiw, this is the fsGroup cousin to #2177

**Comment by dimm0** [comment]
Which issue is now tracking this?
Should we get back to k8s, or there's hope to have this fixed in rook? It's still a big issue for us, since lots of scientists are working with large datasets

**Comment by travisn** [comment]
@JohnStrunk @humblec Have you perhaps seen this issue with mounting large Gluster volumes? We're looking for a way to workaround the recursive chown that K8s performs each time a volume is mounted. For large volumes this can take many minutes. https://github.com/kubernetes/kubernetes/issues/69699 doesn't appear to have a solution yet.

**Comment by JohnStrunk** [comment]
> @JohnStrunk @humblec Have you perhaps seen this issue with mounting large Gluster volumes?

Gluster made the choice to not chown on mount, so the in-tree gluster driver doesn't have this problem. It was a major headache for OSIO where we used flex though. For that, we got a [change for flex](https://github.com/kubernetes/kubernetes/pull/68680) merged that allows chown to be disabled.

The question that requires some thought is what the permission model is.
- For OSIO, we have a consistent uid/gid for the pods that will access the volume, so chown on each mount is not needed.
- For Heketi/Gluster, they use supplementary groups and SGID on the root of the PV to handle permissions (again skipping the chown)
- For GCS, we were planning on more the OSIO model of handing out a "777" PV root directory and letting the users manage their own permissions. (again, this relies on having a consistent uid/gid).

**Comment by dimm0** [comment]
For me the most natural way seems to chown the root folder to the pod's group and user, and let the internal folders and files be sorted out by user
This creates some problem when a single volume gets mounted by different pods with different permissions in different times, but that again can be solved by the user.

**Comment by dimm0** [comment]
@travisn did you try that "SupportsFSGroup bool `json:"supportsFSGroup"`" thing? Would it solve the problem in rook to disable chown?

**Comment by JohnStrunk** [comment]
Just for completeness, usage from the flex side is: https://github.com/gluster/gluster-subvol/commit/deffad71d5687cce2bcc6238ef23cd75789ef0c4

Add `fsGroup: false` to the list of capabilities returned from the flex init call.

**Comment by travisn** [comment]
@JohnStrunk Ah that's working now? Based on the merge date I assume it's only been in since k8s 1.13. When I tried it back in Nov I would have been using 1.12 so it didn't work for me. I'll try again, thanks!

**Comment by dimm0** [comment]
_Updating to 1.13 tomorrow..._
@jjgraham

**Comment by dimm0** [comment]
This is still not resolved
https://github.com/rook/rook/pull/2540#issuecomment-458668486

**Comment by dimm0** [comment]
FYI
https://github.com/kubernetes/community/pull/2595
https://github.com/kubernetes/enhancements/pull/696

**Comment by Negashev** [comment]
@dimm0 
Did you find a temporary solution?

**Comment by dimm0** [comment]
Tar big folders before container shutdown, untar while working with those.. Or untar to emptyDir folder
No real solution.. =(

**Comment by travisn** [comment]
Reopening for backport to 1.0

**Comment by dimm0** [comment]
Seems like fixed!!! 🎉🎉🎉🎉🎉
Thanks all 👍

**Comment by dimm0** [comment]
@travisn is this broken again in 1.0.3? My root folders are not chown'ed

**Comment by dimm0** [comment]
Hm... Seems like it stopped chown'ing the root folder 2 weeks ago. I'm looking at the PVC's created

**Comment by dimm0** [comment]
From agent logs:

```
2019-07-09 19:28:02.053325 I | flexvolume: creating Volume attach Resource rook-system/pvc-c8b33f89-fb1d-40d7-b00e-2f1cde289f4b: {Image:pvc-c8b33f89-fb1d-40d7-b00e-2f1cde289f4b BlockPool:rbd Pool:rbd ClusterNamespace:rook ClusterName: StorageClass:rook-block MountDir:/var/lib/kubelet/pods/d2026c5f-994a-4b78-bbc2-0668c7f04798/volumes/rook.io~rook-system/pvc-c8b33f89-fb1d-40d7-b00e-2f1cde289f4b FsName: Path: MountUser:admin MountSecret: RW:rw FsType:xfs FsGroup: VolumeName:pvc-c8b33f89-fb1d-40d7-b00e-2f1cde289f4b Pod:test2 PodID:d2026c5f-994a-4b78-bbc2-0668c7f04798 PodNamespace:jupyterlab}
```

FsGroup is empty, while pod has:

```
spec:
  securityContext:
    fsGroup: 100
    runAsGroup: 0
    runAsUser: 1000
```

**Comment by dimm0** [comment]
Could be update to k8s 1.15 that broke this...

**Comment by dimm0** [comment]
Still hitting this, manually chowning all new volumes for new users
All new jupyter notebooks are broken

**Comment by karolgil** [comment]
@dimm0 I suppose it's not 1.15 - we're sitting on `1.13.7` and still hitting it.

**Comment by travisn** [comment]
@dimm0 I'm rather baffled why this was working, then stopped when you updated to v1.0.3. There was not change to the flex driver in the release branch (or master) since [this change](https://github.com/rook/rook/pull/3277/commits/05f7e611c7bfe8e382baffa67f487059a1095d1f). Any more clues on your side if this is related to k8s 1.15? Or did you confirm if the fix is still working for you if you go back to v1.0.2?

**Comment by Negashev** [comment]
@dimm0 
I think this comes from the fact that some user is launched in the root directory and everything overwrites all rights, setfsGroup A dangerous tool, it demolishes all the settings, you need to use it very carefully, in my cluster I will disable FSGROUP on rook operator.

**Comment by dimm0** [comment]
I don't think it would be a good idea to rollback the rook version to check... So I can't really tell which update broke this
The main use case we have for this is Jupyter Notebooks - they always run as user 1000, never root, and new users automatically get a volume created. So when it broke, all new users registrations broke - those volumes belong to root now.

**Comment by dimm0** [comment]
Fixed in csi

**Comment by dimm0** [comment]
Finally! https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/

**Comment by travisn** [comment]
@dimm0 If I'm reading that correct, it looks like Rook would need to set `fsGroupPolicy` to `None` on the CSI driver, if `ROOK_ENABLE_FSGROUP=false`. Want to open an issue for that?

**Comment by swackhamer** [comment]
I am having an issue mounting volumes and have been tracing this down.  It looks like the `csidriver/rook-ceph.rbd.csi.ceph.com` needs to have `fsGroupPolicy: File`.  If I manually edit the CSIDriver it gets reverted.

Pods will fail to schedule due to: 
```  Warning  FailedMount             10m (x23 over 41m)  kubelet                  MountVolume.NewMounter initialization failed for volume "pvc-<uid here>" : kubernetes.io/csi: expected valid fsGroupPolicy, received nil value or empty string```

We are on version 1.20.0 k8s and I also attempted to goto `ROOK_CSI_CEPH_IMAGE: "quay.io/cephcsi/cephcsi:v3.2.0"`
`ROOK_ENABLE_FSGROUP=true` in the setup

**Comment by travisn** [comment]
The Rook operator creates the csi driver, and will reset it whenever the operator restarts. 
@dimm0 @swackhamer Who wants to open a new issue for this?

**Comment by dimm0** [comment]
I've already opened one, see link above your message
