### ISSUE TITLE
Minio pods in crash loop with `no endpoint pointing to the local machine is found.`

### ISSUE THREAD

**Issue by jbw976** [rook/rook#2258]
**Is this a bug report or feature request?**
* Bug Report

While testing latest Rook Minio operator from master on Minikube, I see the minio daemon pods are in a crash loop.

**How to reproduce it (minimal and precise):**
```
tests/scripts/minikube.sh up
cd cluster/examples/kubernetes/minio
kubectl create -f operator.yaml
kubectl create -f object-store.yaml
```

Details:
```
> kubectl -n rook-minio get pod
NAME         READY     STATUS             RESTARTS   AGE
my-store-0   0/1       CrashLoopBackOff   5          3m12s
> kubectl -n rook-minio logs my-store-0
Error: Invalid command line arguments server=‘:9000’, args=[http://my-store-0.my-store.rook-minio/data http://my-store-1.my-store.rook-minio/data http://my-store-2.my-store.rook-minio/data http://my-store-3.my-store.rook-minio/data]
```

Further information can be found in this gist: https://gist.github.com/jbw976/23d2a41835caf9f7475d2cab31448e89

**Comment by jbw976** [comment]
After updating the `rook/minio` base image to `minio/minio:RELEASE.2018-10-25T01-27-03Z`, I see more details about the error:

```
> kubectl -n rook-minio logs my-store-0
ERROR Invalid command line arguments: no endpoint pointing to the local machine is found.
      > Please provide correct combination of local/remote paths.
      HELP:
        For more information, please refer to https://docs.minio.io/docs/minio-erasure-code-quickstart-guide
```

I wonder if it's related to this change? https://github.com/rook/rook/commit/62da01c669809222136fc85e70123518d9a1a0c7

**Comment by jbw976** [comment]
It looks like that commit https://github.com/rook/rook/commit/62da01c669809222136fc85e70123518d9a1a0c7 did break Minio on Minikube, and perhaps environments that use the default cluster domain of `cluster.local`.  I'm wondering if we should either:

1. Allow the user to specify a custom cluster domain if they are using one.  The `NetworkSpec` from `rook.io/v1alpha2` may be a nice place to capture this
1. Look up the cluster domain at runtime inside the minio operator.  Not sure how best to do that.

Thoughts?

**Comment by travisn** [comment]
@jbw976 do you have an example of what option 1 would look like in the minio crd? The NetworkSpec type doesn't apply to any specific service. In this case we're appending the suffix to a specific endpoint for client communication with the service, right? If so, maybe it's a setting in the minio crd. But an example would help visualize it. Option 1 does sound better than option 2 so the admin can have control over the setting.

**Comment by jbw976** [comment]
I'm going with option 1 and a PR should be out soon.  I think that in general having a spec to capture an alternate cluster domain would be generally useful, so I think it makes sense to include as a field in the common rook.io network spec.  This is what the usage looks like in the minio object store CRD:
```
spec:
  scope:
    nodeCount: 4
  placement:
  network:
    clusterDomain: acme.com
    ports:
    - name: minio
      port: 9000
```

**Comment by travisn** [comment]
ah, the minio ports will move under the `network` element as well? I don't see the `network` used in the current minio spec. makes sense.

Will this be applicable to other operators using the `network` element? For example, should ceph be appending this suffix somewhere with the rgw services? Or is it not needed since rook doesn't generate any config to connect to the rgw?

**Comment by jbw976** [comment]
It's applicable to any storage operator that is affected by a cluster domain that has changed.  Some may not care or be affected at all.  We know that Minio is, but we haven't seen breaking functionality reported for other providers in environments where the cluster domain has been changed/customized.  I'd leave the other providers alone until an issue is reported, but having this value in the general rook.io specs is still a good idea.

**Comment by jbw976** [comment]
I've created upstream Minio issue https://github.com/minio/minio/issues/6775 to track there
