### ISSUE TITLE
CephVersion.Name is empty after editing cluster

### ISSUE THREAD

**Issue by laevilgenius** [rook/rook#2260]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
`CephVersion.Name` (mimic) is empty after editing cluster.

**Expected behavior:**
`CephVersion.Name` should survive cluster updates.

**How to reproduce it (minimal and precise):**
`kubectl edit cluster rook-ceph`

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): `master`

[onUpdate](https://github.com/rook/rook/blob/802549d33d6cb84db65ca50446c437dcd09af511/pkg/operator/ceph/cluster/controller.go#L258) logs show, that `CephVersion.Name` is empty in both old and new clusters.

**Comment by galexrt** [comment]
There is no such in the Ceph Cluster CRD, see https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md#cluster-settings.

Which documentation CRD/API docs are you referring to?

**Comment by laevilgenius** [comment]
I mean `Name` set by [setCephMajorVersion](https://github.com/rook/rook/blob/802549d33d6cb84db65ca50446c437dcd09af511/pkg/operator/ceph/cluster/cluster.go#L69).
This bug can break dashboard init: while being on `mimic` I get the following log entry:
`skipping cert and user configuration on luminous`

**Comment by travisn** [comment]
@laevilgenius the `cephVersion.Name` is intended to be detected automatically at runtime. The image is launched and `ceph --version` is called to determine what version of ceph is running. It is not intended to be persisted to the CRD.

If the `cephVersion.Name` is set in the CRD, this means the operator should ignore what it detects and treat the version as if it were the specified major version. This isn't documented because hopefully won't be needed, but was left as a back door in case there is some issue detecting the image version and the dev needs to override the detection.

**Comment by laevilgenius** [comment]
Well, as I mentioned, current behaviour breaks dashboard init: it works okay on a first run, but after CRD edit `Name` becomes empty and init code thinks it is on `luminous`.
This also breaks #1915 on `mimic`.

**Comment by travisn** [comment]
@laevilgenius i must have misunderstood the repro. You're saying that the operator thinks the 'cephVersion.Name` is set after you edit the cluster yaml, thus breaking things? I'll try the repro in a bit...

**Comment by laevilgenius** [comment]
I'll take dashboard init as an example:

On first `mgr` run everything is ok and `Name == "mimic"` here:
https://github.com/rook/rook/blob/c6c82218f9e5ce113cd5977ca67d968e40559359/pkg/operator/ceph/cluster/mgr/dashboard.go#L100-L104

Then I edit cluster (disable/enable dasboard for example), `mgr` restarts and `Name` becomes empty, so `initializeDashboard` returns early, thinking it's on `luminous`.

**Comment by travisn** [comment]
I see now, the problem is that `setCephMajorVersion()` is never called from the `onUpdate()` handler, so the `name` field remains empty. now it's obvious what you were describing...
