### ISSUE TITLE
Mon is never rescheduled

### ISSUE THREAD

**Issue by Timer** [rook/rook#2262]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Mon remains on a down host for extended period of time.

**Expected behavior:**

Mon should be moved to a new host after 5 minutes (or default) of health checking.

**How to reproduce it (minimal and precise):**

Disabling scheduling on a node containing a mon, note that after 5 minutes it hasn't been rescheduled.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): 3.10.0
* Cloud provider or hardware configuration: vmware
* Rook version (use `rook version` inside of a Rook Pod): v0.8.3
* Kubernetes version (use `kubectl version`): 1.11.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Pharos
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): 

Toolbox is unresponsive, from UI:
![image](https://user-images.githubusercontent.com/616428/48000942-0917a300-e0d5-11e8-9577-87d9c9e505da.png)
![image](https://user-images.githubusercontent.com/616428/48000956-0fa61a80-e0d5-11e8-88a3-edf6a5737b3c.png)
![image](https://user-images.githubusercontent.com/616428/48000968-1cc30980-e0d5-11e8-9c84-ce114ed95279.png)

----

```
PS C:\Users\jhaddad> kubectl get nodes
NAME           STATUS                        ROLES     AGE       VERSION
fsicentk8s01   Ready                         master    23d       v1.11.3
fsicentk8s02   Ready                         master    23d       v1.11.3
fsicentk8s03   Ready                         master    23d       v1.11.3
fsicentk8s04   Ready                         worker    23d       v1.11.3
fsicentk8s05   Ready                         worker    23d       v1.11.3
fsicentk8s06   Ready                         worker    23d       v1.11.3
fsicentk8s07   NotReady,SchedulingDisabled   worker    2d        v1.11.3
```

```
PS C:\Users\jhaddad> kubectl -n rook-ceph get pod -l app=rook-ceph-mon
NAME                    READY     STATUS    RESTARTS   AGE
rook-ceph-mon18-6ck9h   0/1       Pending   0          1d
rook-ceph-mon20-c4nxz   1/1       Running   0          1d
rook-ceph-mon21-gx6tc   1/1       Running   0          1d
```

```
PS C:\Users\jhaddad> kubectl -n rook-ceph describe pod/rook-ceph-mon18-6ck9h
Name:               rook-ceph-mon18-6ck9h
Namespace:          rook-ceph
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=rook-ceph-mon
                    mon=rook-ceph-mon18
                    mon_cluster=rook-ceph
Annotations:        kubernetes.io/psp=00-pharos-privileged
Status:             Pending
IP:
Controlled By:      ReplicaSet/rook-ceph-mon18
Containers:
  rook-ceph-mon:
    Image:      rook/ceph:v0.8.3
    Port:       6790/TCP
    Host Port:  0/TCP
    Args:
      ceph
      mon
      --config-dir=/var/lib/rook
      --name=rook-ceph-mon18
      --port=6790
      --fsid=6a23586e-45d7-453e-9f86-479f51680214
    Environment:
      ROOK_PRIVATE_IP:             (v1:status.podIP)
      ROOK_PUBLIC_IP:             10.99.131.224
      ROOK_CLUSTER_NAME:          rook-ceph
      ROOK_MON_ENDPOINTS:         <set to the key 'data' of config map 'rook-ceph-mon-endpoints'>  Optional: false
      ROOK_MON_SECRET:            <set to the key 'mon-secret' in secret 'rook-ceph-mon'>          Optional: false
      ROOK_ADMIN_SECRET:          <set to the key 'admin-secret' in secret 'rook-ceph-mon'>        Optional: false
      ROOK_CEPH_CONFIG_OVERRIDE:  /etc/rook/config/override.conf
    Mounts:
      /etc/rook/config from rook-config-override (rw)
      /var/lib/rook from rook-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-sdz4c (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  rook-data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook
    HostPathType:
  rook-config-override:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rook-config-override
    Optional:  false
  default-token-sdz4c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-sdz4c
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/hostname=fsicentk8s07
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  7m (x72777 over 1d)  default-scheduler  0/7 nodes are available: 1 node(s) were unschedulable, 6 node(s) didn't match node selector.
  Warning  FailedScheduling  2m (x101 over 4m)    default-scheduler  0/7 nodes are available: 1 node(s) were not ready, 1 node(s) were out of disk space, 1 node(s) were unschedulable, 6 node(s) didn't match node selec
tor.
```

**Comment by anguslees** [comment]
Note in particular: `Node-Selectors:  kubernetes.io/hostname=fsicentk8s07`

Should this be an anti-affinity rule instead? (ie: schedule on separate hosts without mentioning explicit hostnames)

**Comment by travisn** [comment]
Mons use the node selector because they are a stateful service and write their state to the `dataDirHostPath` on their node. If they were moved to another node, they would lose that state. 

Can you share the operator log? The operator watches the mons and if one of them falls out of quorum, the operator will fail it over to a new node. The log should show if the operator is trying to fail over the mon.

For more details on the expected failover behavior, see the [design doc](https://github.com/rook/rook/blob/master/design/mon-health.md).

**Comment by Timer** [comment]
Sorry, I spent the whole day trying to fix it before I had to nuke it and restore from a backup. 😅 

I'll try to replicate and get logs, but IIRC the operator logs didn't show anything regarding it trying to fail over (or it even knowing a mon was unhealthy).

**Comment by travisn** [comment]
@subicura this is related to #2570 and is a high priority item. For a workaround, you can do the following when the operator gets stuck like this:
1. Delete the deployment for the failed mon
2. Edit the configmap `rook-ceph-mon-endpoints` and (carefully) remove the failed mon from the list
3. Restart the operator

**Comment by ebuildy** [comment]
Hello @travisn , what is in charge of update the CM ``rook-ceph-mon-endpoints`` and also the secret ``rook-ceph-config``?  As https://stackoverflow.com/questions/63783109/rook-ceph-broken-on-kubernetes, I had to update it manualy , is it normal? Many thanks.

**Comment by travisn** [comment]
@ebuildy The operator owns updating that configmap and secret. It's not expected to update them manually unless there is some disaster recovery situation as described [here](https://rook.github.io/docs/rook/v1.4/ceph-disaster-recovery.html). Feel free to open a github issue with what you're seeing, or join the rook [Slack](https://slack.rook.io) to discuss.

**Comment by ebuildy** [comment]
Thanks you , 

I try to understand how clustering is working here. ``mon`` pod IPs are updated by operator and stored in a CM. But operator is using this CM to find ``mon`` pod and updating this CM?

So if a single ``mon`` pod IP changes, quorum is broken?

Why dont use a headless service like elasticsearch does?

**Comment by travisn** [comment]
> Thanks you ,
> 
> I try to understand how clustering is working here. `mon` pod IPs are updated by operator and stored in a CM. But operator is using this CM to find `mon` pod and updating this CM?

The CM is what the operator considers the source of truth for the mon names and their host names. If the operator restarts, it looks at the CM for this info.

> So if a single `mon` pod IP changes, quorum is broken?
> Why dont use a headless service like elasticsearch does?

Ceph does not allow the mon endpoints to change. Rook does use a service for this purpose to have a consistent endpoint for the mon.

**Comment by camilamacedo86** [comment]
Hi @travisn,

I could face this scenario by using Rook 1.0.4 in a cluster where I had one master and 3 nodes then, I remove one node and re-added a new one. See the WARNING:


By running the command `kubectl -n rook-ceph exec deployment.apps/rook-ceph-operator -- ceph status`, i.e.:

![unhelth-ceph-check](https://user-images.githubusercontent.com/7708031/214801845-8fdd31ff-05a6-4daf-90d5-dede3e4da17f.png)

**If you checked that the mon Rook pod for the purged node is still in usage:** 

By running `kubectl -n rook-ceph get pod -l app=rook-ceph-mon`, i.e.:

![mon-pod-peding](https://user-images.githubusercontent.com/7708031/214801925-0e294a1b-40f4-42f2-8c15-c955d81e0e22.png)

Therefore, I could came back to the health state by more less following your comment: https://github.com/rook/rook/issues/2262#issuecomment-460898915. Following the steps performed:

- a) Stop the Rook Operator by running: kubectl -n rook-ceph scale --replicas=0 deployment.apps/rook-ceph-operator
- b) Edit the configmap rook-ceph-mon-endpoints to (carefully) remove the purged node info from the mapping with the command kubectl -n rook-ceph edit configmaps rook-ceph-mon-endpoints Following an example:

In this example, we purged the node example-ubuntu-2204-node-c but we can still checking it in the mapping:

![Screenshot 2023-01-24 at 07 47 38](https://user-images.githubusercontent.com/7708031/214802350-da6b8b65-e5af-42a4-98e1-3601a5051b2d.png)

In this way, to workaround the scenario and try to make the Ceph came back to a health state we remived remove "c": ["Name": "example-ubuntu-2204. node-c". "Hostname" : "example-ubuntu-2204-node-c" "Address"': "10.154.0.21"},

-c) Delete the mon pod in Pending state. You can found its name by running kubectl -n rook-ceph get pod -l app=rook-ceph-mon and you can remove by running kubectl -n rook-ceph delete pod <mon-pod-name-in-pending-state>
- d)Then, rescale the Rook Operator by running: kubectl -n rook-ceph scale --replicas=1 deployment.apps/rook-ceph-operator

Then, I could check that the Ceph came back to health state and that the rook-ceph-mon-endpoints mapping was updated and resulted in have mapped only data from available nodes.

**Comment by travisn** [comment]
If you are running in the cloud where you are replacing nodes, please consider using the [PVC-based cluster](https://rook.io/docs/rook/latest/CRDs/Cluster/pvc-cluster/) instead of the host-based cluster. 

Also see the topic on [mon failover](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/) in case a mon is lost.

Please update to a newer version of Rook, since we are on v1.10 now, and v1.0 is very old.
