### ISSUE TITLE
ceph mgr is failing to start on newest docker image

### ISSUE THREAD

**Issue by killmeplz** [rook/rook#2267]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

ceph mgr is failing to start on newest docker image
i changed image tag to rook/ceph:v0.8.0-263.g9ba4fcc as a workaround

```
docker run -it rook/ceph:master ceph mgr --help
Main command for Ceph operator and daemons.

Usage:

Flags:
  -h, --help   help for ceph

Global Flags:
      --log-level string   logging level for logging/tracing output (valid values: CRITICAL,ERROR,WARNING,NOTICE,INFO,DEBUG,TRACE) (default "INFO")
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**

docker run -it rook/ceph:master ceph mgr --config-dir=/var/lib/rook

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
@killmeplz Are you trying to run Rook using direct `docker run` commands or are your Pods in Kubernetes which have been spawned by the Rook Ceph operator not starting?

**Comment by killmeplz** [comment]
@galexrt 
I got this issue on a working k8s trying to update rook cluster. But you can also reproduce it running container manually.

**Comment by travisn** [comment]
@killmeplz with the merge of #2187, the rook image no longer is used to run the ceph daemons. An image from `ceph/ceph` is used to run the daemons. Master build upgrades aren't officially supported, but you could try restarting the operator to get the update. If it doesn't work, you may need to delete the mgr deployments and then restart the operator.
