### ISSUE TITLE
Support creation of liveness probes for ceph-manager via rook operator 

### ISSUE THREAD

**Issue by christianhuening** [rook/rook#2270]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add liveness probes to manager deployments and check `/` on port `9283`
**What is use case behind this feature:**
Make sure stuck Managers are being recreated
**Environment**:

**Comment by travisn** [comment]
@christianhuening What would it take to revive #2271? Having a liveness probe on the mgr will be helpful to ensure it doesn't get stuck. Thanks!

**Comment by christianhuening** [comment]
@travisn it took your message. I totally forgot about it.
