### ISSUE TITLE
Mention ceph further up on rook.io

### ISSUE THREAD

**Issue by kamalmarhubi** [rook/rook#228]
When I first saw this project, my initial thoughts are "how is this different from ceph or gluster", and "how long will it be until this is even approaching production ready". I wouldn't want to put my trust in a distributed filesystem less than a few year old.

I think it'd be good to move mention of Ceph up above the fold so that a casual skim of the "marketing page" will catch it.

**Comment by travisn** [comment]
@kamalmarhubi we just updated rook.io. Did the change help? Thanks for the suggestion!

**Comment by travisn** [comment]
closing from the change mentioned
