### ISSUE TITLE
error: unable to recognize "cluster-ceph.yml": no matches for kind "Cluster" in version "ceph.rook.io/v1beta1"

### ISSUE THREAD

**Issue by frouzbeh** [rook/rook#2280]

**Comment by leseb** [comment]
What was the fix for this?

**Comment by frouzbeh** [comment]
@leseb I couldn't find any solution for that when it happened, but I was getting this whenever I deleted rook, so I started with a new cluster and this hasn't happened anymore.

**Comment by leseb** [comment]
@frouzbeh thanks!ç

**Comment by jxadro** [comment]
I can not be sure of this but my problem was that the hyperkube image I configured was not the one used in my k8s cluster.
