### ISSUE TITLE
Wordpress/mysql examples do not work with istio 1.0.3

### ISSUE THREAD

**Issue by mabushey** [rook/rook#2281]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Wordpress cannot talk with mysql

**Expected behavior:**
functioning demo site

**How to reproduce it (minimal and precise):**
Add namespace of wordpress to wordpress and mysql examples.

This works:
```
kind: Namespace
apiVersion: v1
metadata:
  name: wordpress 
  labels:
    env: prd
```

This is broke:
```
kind: Namespace
apiVersion: v1
metadata:
  name: wordpress 
  labels:
    env: prd
    istio-injection: enabled
```

Error:
```
$ kubectl -n wordpress logs pod/my-wordpress-79f7d47f49-m6gv2 my-wordpress

Warning: mysqli::__construct(): MySQL server has gone away in Standard input code on line 22

Warning: mysqli::__construct(): Error while reading greeting packet. PID=78 in Standard input code on line 22

Warning: mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22

MySQL Connection Error: (2006) MySQL server has gone away

Warning: mysqli::__construct(): MySQL server has gone away in Standard input code on line 22

Warning: mysqli::__construct(): Error while reading greeting packet. PID=78 in Standard input code on line 22

Warning: mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22

MySQL Connection Error: (2006) MySQL server has gone away

Warning: mysqli::__construct(): MySQL server has gone away in Standard input code on line 22

Warning: mysqli::__construct(): Error while reading greeting packet. PID=78 in Standard input code on line 22

Warning: mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22

MySQL Connection Error: (2006) MySQL server has gone away
```
**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"

nodes are running CoreOS

* Kernel (e.g. `uname -a`):
Linux ip-172-31-46-19 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
AWS - Kops/Terraform

* Rook version (use `rook version` inside of a Rook Pod):
0.8.3

* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
AWS/Kops
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
Ceph itself is fine

**Comment by cbenien** [comment]
If anyone is interested in a solution, have a look at https://github.com/istio/istio/issues/10062 

For me (Istio 1.2.5), I had to delete the default mesh policy and change the mysql yaml file by using "name: tcp" for mysql 3306 ports.
