### ISSUE TITLE
MON_CLOCK_SKEW: clock skew detected on mon.b, mon.c 

### ISSUE THREAD

**Issue by mxfj** [rook/rook#2286]
Cluster log
    Audit log

2018-11-16 19:39:35.954444 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.0784957s > max 0.05s
2018-11-16 19:39:35.954361 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.060646s > max 0.05s
2018-11-16 19:34:35.953533 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.0596566s > max 0.05s
2018-11-16 19:34:35.953483 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.0774483s > max 0.05s
2018-11-16 19:29:35.952749 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.0585322s > max 0.05s
2018-11-16 19:29:35.952711 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.0761972s > max 0.05s
2018-11-16 19:24:35.951990 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.0750271s > max 0.05s
2018-11-16 19:24:35.951901 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.0576438s > max 0.05s
2018-11-16 19:19:35.951266 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.0737409s > max 0.05s
2018-11-16 19:19:35.951188 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.0564803s > max 0.05s
2018-11-16 19:14:35.950307 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.0725444s > max 0.05s
2018-11-16 19:14:35.950145 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.0554771s > max 0.05s
2018-11-16 19:09:35.949414 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.0714002s > max 0.05s
2018-11-16 19:09:35.949371 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.0542874s > max 0.05s
2018-11-16 19:04:35.948458 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.070243s > max 0.05s
2018-11-16 19:04:35.948391 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.0533532s > max 0.05s
2018-11-16 19:00:00.000135 [WRN]  overall HEALTH_WARN clock skew detected on mon.b, mon.c
2018-11-16 18:59:35.947567 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.0691036s > max 0.05s
2018-11-16 18:59:35.947449 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.0523409s > max 0.05s
2018-11-16 18:54:35.946681 [WRN]  mon.2 10.0.3.48:6790/0 clock skew 0.0679171s > max 0.05s
2018-11-16 18:54:35.946639 [WRN]  mon.1 10.0.3.47:6790/0 clock skew 0.0512064s > max 0.05s
2018-11-16 18:49:40.054694 [WRN]  Health check update: clock skew detected on mon.b, mon.c (MON_CLOCK_SKEW)

**Comment by mxfj** [comment]
like this
[root@k8s-master1 ~]# kubectl -n rook-ceph get pod
NAME                                      READY   STATUS      RESTARTS   AGE
rook-ceph-mgr-a-558fbdbb5-mrjps           1/1     Running     0          30m
rook-ceph-mon-a-6cd54946bc-slndl          1/1     Running     0          34m
rook-ceph-mon-b-58894cfc97-9vtmx          1/1     Running     0          34m
rook-ceph-mon-d-9478f94-8fbf8             1/1     Running     0          32m
rook-ceph-osd-0-cddc6c9d9-v2hmg           1/1     Running     0          30m
rook-ceph-osd-1-955b68f5d-zpwdc           1/1     Running     0          30m
rook-ceph-osd-2-69564f498d-znrc7          1/1     Running     0          30m
rook-ceph-osd-3-648f65988-t9j4p           1/1     Running     0          30m
rook-ceph-osd-prepare-k8s-master1-72bbr   0/2     Completed   0          30m
rook-ceph-osd-prepare-k8s-master2-55mt5   0/2     Completed   0          30m
rook-ceph-osd-prepare-k8s-master3-cj92f   0/2     Completed   0          30m
rook-ceph-osd-prepare-k8s-node1-bf75l     0/2     Completed   0          30m

kubectl -n rook-ceph exec -it rook-ceph-osd-0-cddc6c9d9-v2hmg bash

cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
locale -a
yum -y install ntp ntpdate
ntpdate *.*.*.*

HEALTH_OK is ok but a moment is return to this MON_CLOCK_SKEW

**Comment by DPerkunas** [comment]
Noticed this as well, if you delete the mon pod in question, it gets recreated and health goes back to OK.

**Comment by BlaineEXE** [comment]
After speaking with some of our kubernetes experts, I believe this is an environment issue. With NTP on the host systems properly working, Kubernetes should be able to keep all pods in sync automatically. If containers have privileged access to the host system, running an NTP daemon in a container would even appear to solve this issue for an entire node.

I believe the root solution is to make sure that time synchronization daemons are running on all of your Kubernetes nodes and that they are able to sync time with either a local time server(s) or with online time servers.

**Comment by fisherwei** [comment]
i have a cluster with 3 nodes. all of nodes are same time, but rook still report clock skew.

> root@ubunut-server:~# ssh rancher@192.168.66.201 date && ssh rancher@192.168.66.202 date && ssh rancher@192.168.66.203 date
> Tue Mar 19 07:49:12 UTC 2019
> Tue Mar 19 07:49:12 UTC 2019
> Tue Mar 19 07:49:12 UTC 2019

>   cluster:
>     id:     70eef1c8-eccf-481d-9801-3968d19e8b11
>     health: HEALTH_WARN
>             clock skew detected on mon.a, mon.b

**Comment by bsord** [comment]
I am also seeing the same. Fresh deployment of 3 nodes on version 1.0.0. Confirmed all show the same time. Also specified NTP servers and ntpupdate to config all that. and still an issue.

**Comment by anguslees** [comment]
I get this frequently too fwiw.  I have ntp (systemd-timesyncd) running on all nodes, and the clocks are in sync.  I think the warning is load related (host cpu and/or network) and spurious, since the skew warning occurs more often when cluster load goes up, even though obviously the clocks don't change their accuracy during this time.

My plan is just to increase the warning threshold to 0.1s, because life is too short to worry about whether a reasonable network round trip is 48 or 58 milliseconds.

**Comment by yizhishang** [comment]
> I get this frequently too fwiw. I have ntp (systemd-timesyncd) running on all nodes, and the clocks are in sync. I think the warning is load related (host cpu and/or network) and spurious, since the skew warning occurs more often when cluster load goes up, even though obviously the clocks don't change their accuracy during this time.
> 
> My plan is just to increase the warning threshold to 0.1s, because life is too short to worry about whether a reasonable network round trip is 48 or 58 milliseconds.

Can you tell me what is it the commond to increase the warning threshold ?

**Comment by rnetser** [comment]
@anguslees I'm trying to increase the clock drift allowed to more than 0.05 but not sure how to do it as /etc/ceph/ceph.conf is readonly file in the mon pods.
Any other way of doing this?

**Comment by rnetser** [comment]
@leseb Could you please also advise?

**Comment by BlaineEXE** [comment]
See the docs section on using the override configmap

**Comment by rnetser** [comment]
Thank you, will do,

**Comment by anguslees** [comment]
Yep, check the docs.  Basically it involves creating a `rook-ceph/rook-config-override` ConfigMap, with a `config` key, and you can put various ceph settings in there. Fwiw, my config is:
```
[global]
# Default of 0.05 is too aggressive for my cluster. (seconds)
mon clock drift allowed = 0.1
# K8s image-gc-low-threshold is 80% - not much point warning
# before that point. (percent)
mon data avail warn = 20
```

**Comment by rnetser** [comment]
Thank you! That is very helpful; modified "mon clock drift allowed" as described.

**Comment by kevinsingapore** [comment]
i also have meet the same problem.
and how to solve?

**Comment by kevinsingapore** [comment]
> i also have meet the same problem.
> and how to solve?
> the warning image as below:
> ![image](https://user-images.githubusercontent.com/39163739/74592689-c1652280-505e-11ea-922c-bdd40e751fde.png)

now, i have another way to try, and it works ok!
the method is :
(1).all nodes adjust to the same ntp-server time;(e.g: ntp1.aliyun.com) 
(2).delete the mon.a mon.b.mon.c pods , then it will automatically to restart another same pod;
(3).to see the health status;(e.g: ceph status)
it will be ok!

**Comment by kevinsingapore** [comment]
> > i also have meet the same problem.
> > and how to solve?
> > the warning image as below:
> > ![image](https://user-images.githubusercontent.com/39163739/74592689-c1652280-505e-11ea-922c-bdd40e751fde.png)
> 
> now, i have another way to try, and it works ok!
> the method is :
> (1).all nodes adjust to the same ntp-server time;(e.g: ntp1.aliyun.com)
> (2).delete the mon.a mon.b mon.c pods , then it will automatically to restart another same pod;
> (3).to see the health status;(e.g: ceph status)
> it will be ok!

the next day, the warn information occurs  again. so the method isn't ok.

**Comment by kevinsingapore** [comment]
> > > i also have meet the same problem.
> > > and how to solve?
> > > the warning image as below:
> > > ![image](https://user-images.githubusercontent.com/39163739/74592689-c1652280-505e-11ea-922c-bdd40e751fde.png)
> > 
> > 
> > now, i have another way to try, and it works ok!
> > the method is :
> > (1).all nodes adjust to the same ntp-server time;(e.g: ntp1.aliyun.com)
> > (2).delete the mon.a mon.b mon.c pods , then it will automatically to restart another same pod;
> > (3).to see the health status;(e.g: ceph status)
> > it will be ok!
> 
> the next day, the warn information occurs again. so the method isn't ok.

after i have ntpdate all nodes to the same ntp-server,  it's ok again. 
and now i don't know how to solve the question.

**Comment by kevinsingapore** [comment]
> i have a cluster with 3 nodes. all of nodes are same time, but rook still report clock skew.
> 
> > root@ubunut-server:~# ssh rancher@192.168.66.201 date && ssh rancher@192.168.66.202 date && ssh rancher@192.168.66.203 date
> > Tue Mar 19 07:49:12 UTC 2019
> > Tue Mar 19 07:49:12 UTC 2019
> > Tue Mar 19 07:49:12 UTC 2019
> 
> > cluster:
> > id:     70eef1c8-eccf-481d-9801-3968d19e8b11
> > health: HEALTH_WARN
> > clock skew detected on mon.a, mon.b

i also got the same warning informaition. do u have deal with it?

**Comment by kevinsingapore** [comment]
> > > i also have meet the same problem.
> > > and how to solve?
> > > the warning image as below:
> > > ![image](https://user-images.githubusercontent.com/39163739/74592689-c1652280-505e-11ea-922c-bdd40e751fde.png)
> > 
> > 
> > now, i have another way to try, and it works ok!
> > the method is :
> > (1).all nodes adjust to the same ntp-server time;(e.g: ntp1.aliyun.com)
> > (2).delete the mon.a mon.b mon.c pods , then it will automatically to restart another same pod;
> > (3).to see the health status;(e.g: ceph status)
> > it will be ok!
> 
> the next day, the warn information occurs again. so the method isn't ok.

(1).the cause:
different nodes will have different time especially about seconds after the last adjust ntp-server time.
(2).the answer:
to build the shell script to adjust all nodes to follow the ntp-server time frequently. (e.g: every 10 minutes  to adjust again)

**Comment by prbakhsh** [comment]
To resolve warning I increased mon_clock_drift_allowed value from Ceph dashboard. In my opinion some millisecond doesnt important and 0.05 second for warn level is a little strictant
