### ISSUE TITLE
Apache Cassandra Operator (all functionality)

### ISSUE THREAD

**Issue by jbw976** [rook/rook#2294]
This ticket is for tracking the design outlined in #1910, which will incorporate a Cassandra operator into Rook.

**Comment by jbw976** [comment]
This was fixed with #2207

**Comment by yanniszark** [comment]
@jbw976 I was thinking this could be an umbrella issue to track things, not for one specific PR (title also implies that). What do you think ?

**Comment by rimolive** [comment]
I'm using OpenShift and I noticed the current implementation needs some tweaks to make this work. With that being said, I'd like to ask the following:

1) Do I need an issue opened to monitor this task?
2) Who should I ask for help if I need?

**Comment by travisn** [comment]
@rimolive Could you open a new github issue with the updates that are needed here? @yanniszark Could provide any feedback around the Cassandra PRs. Thanks!
