### ISSUE TITLE
Updating objectstore port crd should update the service port

### ISSUE THREAD

**Issue by jhzhu89** [rook/rook#2296]
Why service is not updated when updating store?

I found that even I succeeded to edit the objectstore spec, for example, change port from 80 to 1080, the service was not changed, while rgw pods were re-created with new port 1080. I am not sure if this is a bug or expected behavior? If expected, why is that?

In code the service is only created accordingly, never updated or re-created. And in the service spec, the target port is not a named port, port number is used.

https://github.com/rook/rook/blob/0a8e1096ffd4efa51527a3da6af44222353e20bf/pkg/operator/ceph/object/spec.go#L166-L195

**Comment by travisn** [comment]
It has not been implemented yet to update the object service when the crd is updated.

**Comment by giovanism** [comment]
@travisn , Can I work on this issue?

**Comment by travisn** [comment]
Yes thanks! In the link above, I believe it may be sufficient to replace the call to [Get()](https://github.com/rook/rook/blob/0a8e1096ffd4efa51527a3da6af44222353e20bf/pkg/operator/ceph/object/spec.go#L191) on line 191 with a call to `Update()`

**Comment by leseb** [comment]
@giovanism still interested to work on that?

**Comment by travisn** [comment]
@leseb With your recent updates to the rgw daemon I wonder if this may already be fixed. The object store orchestration is triggering `[Update()][https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/spec.go#L63]`, where in the past it was not. @jhzhu89 Could you check if it is fixed already in master?

**Comment by leseb** [comment]
@travisn yes I believe this is fixed and definitely with 60a860cab2b10ad50a27188596181c0635d4effa pending in https://github.com/rook/rook/pull/2901.
