### ISSUE TITLE
Why two namespaces in ceph tutorial ? 

### ISSUE THREAD

**Issue by Lexing** [rook/rook#2297]
Have a question on the namespaces in ceph tutorial:

cluster/examples/kubernetes/ceph/operator.yaml creates rook-ceph-system 

while the https://github.com/rook/rook/blob/master/Documentation/ceph-quickstart.md example creates another namespace rook-cepth

Wondering what's the reasons behind these ? Isn't using one namespace simpler ?

**Comment by fkpwolf** [comment]
`rook-ceph-system` is an Operator to create ceph cluster, which is `rook-ceph`. You can use the operator to create 1 or more Ceph cluster. Different namespace has different role and permission.

**Comment by BlaineEXE** [comment]
@fkpwolf is correct. The different namespaces help to separate roles and permissions; I usually think of `rook-ceph-system` as being similar to `kube-system` but obviously specific to Rook.

I will close this issue, and you can feel free to reopen it if there are things that can still be clarified.

**Comment by Lexing** [comment]
Thanks @fkpwolf  and @BlaineEXE  for the answers, I can understand it better now. I do have a follow up though, @fkpwolf mentioned that one namespace is created for one ceph cluster, doesn't that mean multiple namespaces will be created for multiple clusters ? I'm not quite familiar with ceph so not sure if multi-ceph cluster setup is a common thing.

**Comment by fkpwolf** [comment]
yes @Lexing namespaces in k8s is some like multi-tenancy technology.

**Comment by BlaineEXE** [comment]
While Ceph's flexibility makes it easy to run one cluster for supporting many different use-cases, multi-ceph cluster setups are sometimes desirable. With Kubernetes and Rook, Ceph-on-demand for users becomes much easier, and I believe this idea will result in a good number of kubernetes clusters wishing to run multiple independent Ceph clusters. I will also note that it would be best to use separate nodes for different clusters' osds, as there is risk of one cluster corrupting another if the clusters' storage configs overlap. Another use-case is for federated Kubernetes clusters where each datacenter in the Kubernetes global cluster has its own Ceph cluster synchronized "cache".
