### ISSUE TITLE
mds: don't report slow request for blocked filelock request

### ISSUE THREAD

**Issue by barlowliu** [rook/rook#2307]
The version of ceph used in the latest version of rook-ceph is 12.2.7. There is a bug in cephfs (reference: https://tracker.ceph.com/issues/22428), which has been fixed in ceph 13.0+.
When does rook plan to update to ceph13.0+?

**Comment by BlaineEXE** [comment]
Rook will allow updating Ceph to 13.x+ with the release of Rook 0.9 in the coming week or two.

**Comment by travisn** [comment]
@barlowliu it would be great if you could test mimic with the master builds and see if it is working for you. For a complete description, see the [design doc](https://github.com/rook/rook/blob/master/design/decouple-ceph-version.md).
