### ISSUE TITLE
Support configurable annotations for ceph operator

### ISSUE THREAD

**Issue by jslusher** [rook/rook#2308]
**What should the feature do:**
When defining a `Cluster` resource using the rook/ceph operator, there are cases when annotations added to the resulting pods would be very useful.

**What is use case behind this feature:**
 I would like to add datadog annotations to the ceph mgr pod so that it collects prometheus metrics. 

**Environment**:
Monitoring in datadog is just one example. The ability to add annotations to operators could have many uses.

**Comment by galexrt** [comment]
@travisn @jbw976 What about adding a `annotations` "list" like we currently have with the `placement` spec/structure?

**Comment by travisn** [comment]
@galexrt agreed, looks like it would follow the same pattern

**Comment by galexrt** [comment]
@travisn @jbw976 One more question is open, is On which objects should the annotations be set? Only Deployments, StatefulSet, etc. and their corresponding Pods or on "all" objects, e.g, Services, ConfigMaps too?

I'm personally favoring the former, as normally the use case with annotations is to have information on the actual workload for e.g., DataDog, Prometheus (we set those in the MGR right now, we could remove that and allow the user to set it as they want/need it).

**Comment by travisn** [comment]
Makes sense to me as well to only set it on the daemon deployments and related resources, but not all resources.
