### ISSUE TITLE
Allow creating multiple file systems

### ISSUE THREAD

**Issue by travisn** [rook/rook#231]
The initial implementation of the file system is plumbed to allow multiple file systems, but only exposes a single file system from the REST api. The api should support passing the name of the file system to add or remove the file system

**Comment by jbw976** [comment]
From http://docs.ceph.com/docs/jewel/cephfs/administration/:
> Note that by default only one filesystem is permitted: to enable creation of multiple filesystems use ceph fs flag set enable_multiple true

**Comment by jbw976** [comment]
It looks like each cephFS instance gets its own independent set of MDS instances.  1 cephFS :: many MDS, with no MDS overlap across cephFS instances.

Support for multiple file systems is still pretty early:
http://docs.ceph.com/docs/master/cephfs/experimental-features/#multiple-filesystems-within-a-ceph-cluster

**Comment by bassam** [comment]
@travisn can this be closed?

**Comment by travisn** [comment]
Yes, done with #1029
