### ISSUE TITLE
Declare Ceph CRDs as v1

### ISSUE THREAD

**Issue by travisn** [rook/rook#2316]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Per various discussions with maintainers and others, we are planning to declare the Ceph CRDs as v1 in the v0.9 release. This will require a migration of the CRDs from beta to v1, similar to what was necessary in v0.8 when the CRDs went from alpha to beta.

**Comment by travisn** [comment]
## Migration considerations
- CRD versioning was vastly improved in k8s 1.11. The [CRD versioning](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/) now can be managed during the upgrade. 
- Rook v0.9 will support k8s v1.8. Since the versioning support needed is not in v1.8, we need to implement similar type conversions to v1 as we did when converting the ceph types from alpha to beta.
- Using the old conversion mechanism, the only reasonable way to convert the types to v1 and keep the `ceph.rook.io` group is to rename the types.
- If we wanted to keep the same group and type names, we would have to do something disruptive as seen in [these v0.8 conversion steps](https://rook.io/docs/rook/v0.8/upgrade.html#appendix-upgrading-a-build-from-master). This is too risky.

## Proposal
Rename the CRD types during the conversion to v1. The following types would be given the ceph prefix:
- `Cluster` --> `CephCluster`
- `Pool` --> `CephPool`
- `Filesystem` --> `CephFilesystem`
- `ObjectStore` --> `CephObjectStore`
- `ObjectStoreUser` --> `CephObjectStoreUser`

We can also declare short names to get the original naming behavior.

There has been some healthy amount of debate in the past about giving the types a Ceph prefix like this anyway. These are my recommended type names instead of the more generic names. For example, the CRD kind for etcd is [EtcdCluster](https://github.com/coreos/etcd-operator/blob/master/example/example-etcd-cluster.yaml) rather than just `Cluster`, even though it is in the `etcd.database.coreos.com` group. It's ok if the full name is a bit redundant since the full name is rarely used. 

Going forward, we can use the versioning scheme built into v1.11 and avoid the pains of renaming, but for now there does not appear to be a better option.

@jbw976 @bassam @galexrt @liewegas

**Comment by travisn** [comment]
["Volume"](https://kubernetes.io/docs/concepts/storage/volumes/) is a term in K8s for mounting into a specific pod. Using the volume term seems like it would cause confusion between a CephFS volume and K8s volume. 

In general I would think the CRD names should stick with generally understood terms so users can more quickly understand what they might be capable of, instead of mapping them to underlying terminology. "Filesystem" and "Object store" convey the general concepts IMO.

**Comment by sebastian-philipp** [comment]
We may need to update https://github.com/ceph/ceph/blob/master/src/pybind/mgr/rook/rook_cluster.py#L22

**Comment by liewegas** [comment]
In that vein, maybe CephPool should be CephBlockPool?

**Comment by travisn** [comment]
@liewegas CephBlockPool would be fine with me since it is specific to block from the user's perspective. 

Something to consider is that internally the CRD properties for object stores and file systems use the pool type. For example, the filesystem specifies pools like so:
```
  # The metadata pool spec
  metadataPool:
    replicated:
      # Increase the replication size if you have more than one osd
      size: 1
  # The list of data pool specs
  dataPools:
    - failureDomain: osd
      replicated:
        size: 1
```

Does this mean we should rename the fields `metadataPool` to `metadataBlockPool` and `dataPools` to `dataBlockPools`? I would vote to leave them unchanged.

**Comment by liewegas** [comment]
> @liewegas CephBlockPool would be fine with me since it is specific to block from the user's perspective.
> 
> Something to consider is that internally the CRD properties for object stores and file systems use the pool type. For example, the filesystem specifies pools like so:
> 
> ```
>   # The metadata pool spec
>   metadataPool:
>     replicated:
>       # Increase the replication size if you have more than one osd
>       size: 1
>   # The list of data pool specs
>   dataPools:
>     - failureDomain: osd
>       replicated:
>         size: 1
> ```
> Does this mean we should rename the fields `metadataPool` to `metadataBlockPool` and `dataPools` to `dataBlockPools`? I would vote to leave them unchanged.

I agree.  If anything I would possibly consider avoiding "Pool" in this CRD name since it may be multiple pools... it really maps to the StorageClass, right?  CephBlockPool is probably closest to what the ceph user is thinking about, though (since in the most common case it is a single pool).

**Comment by travisn** [comment]
Sounds good, i'll go with CephBlockPool. Good point on the storage class, i'll also rename the `pool` property in the [storage class](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/storageclass.yaml#L16) to be `blockPool`. I'll just have to allow the `pool` property still for backward compatibility.

To be clear, my example snippet was from the [filesystem CRD](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/filesystem.yaml), which doesn't include `pool` in the crd name, it's just in the property names for the metadata and data pools that are created.

**Comment by BlaineEXE** [comment]
@travisn 
> Rook v0.9 will support k8s v1.8. Since the versioning support needed is not in v1.8, we need to implement similar type conversions to v1 as we did when converting the ceph types from alpha to beta.

Given the [ZDnet article](https://www.zdnet.com/google-amp/article/kubernetes-first-major-security-hole-discovered/), what if we reduced our support to v1.10, v1.11, and v1.12? Do you think this (1) makes sense and (2) saves some work here?

**Comment by galexrt** [comment]
@BlaineEXE I think we should then also move the `AppsV1` for all Deployments, StatefulSets and so on, if this change should be done.

Could you please add it to the community meeting agenda https://docs.google.com/document/d/1exd8_IG6DkdvyA0eiTtL2z5K2Ra-y68VByUUgwP7I9A/edit

**Comment by travisn** [comment]
@BlaineEXE as long as 1.10 is supported we will need the changes in this PR. It's 1.11 and newer that has the improved crd version support. There is also a bunch of related cleanup that would be good to keep with this PR anyway. Realistically, dropping 0.8 and 0.9 support immediately would be a challenge for many users. 

@galexrt moving to `AppsV1` makes sense. How do you see it tied to this change? I'd vote to do it independently and after 0.9.

**Comment by galexrt** [comment]
@travisn I see it tied to the change of reducing the Kubernetes supported versions.

In Kubernetes 1.9-1.10 >= one should "only" use the `apps/v1` APIs instead of `extensions/*` (for Deployments, StatefulSets and so on), as the `extensions/*` are possibly getting removed at one time for those objects.
