### ISSUE TITLE
mon and osd not getting scheduled on new nodes

### ISSUE THREAD

**Issue by sprdeepesh** [rook/rook#2327]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
mon and osd pods are not scheduled on newly added nodes

**Expected behavior:**
pods should get scheduled when a new node is added

**How to reproduce it (minimal and precise):**
1. Create a cluster with one master and 2 worker nodes
2. Setup rook
```
kubectl create -f operator.yaml
kubectl create -f cluster.yaml
```
3. Add 2 new worker nodes
    mon and osd pods does not run on these nodes. Dashboard shows 2 (2 up, 2 in)

4. Bring down one of the old worker node (I stopped the server to simulate node failure)
    after about 5 mins I see mon and osd pods running on new nodes as well. Dashboard shows 4 (3 up, 4 in)

Is this an expected behavior of rook? 

How can we add new nodes or replace nodes which goes down? Also how can we do backup and restore of the entire rook storage? - Is there any documentation around these.

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7.4
* Kernel (e.g. `uname -a`): 3.10.0-693.5.2.el7.x86_64
* Cloud provider or hardware configuration: Running on AWS EC2 instances, but does not have --cloud-provider enabled
* Rook version (use `rook version` inside of a Rook Pod): v0.8.3
* Kubernetes version (use `kubectl version`): v1.11.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Cluster setup using kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] (https://rook.io/docs/Rook/master/toolbox.html)): `HEALTH_WARN noscrub,nodeep-scrub flag(s) set; 1/3 mons down, quorum rook-ceph-mon3,rook-ceph-mon1`

**Comment by sprdeepesh** [comment]
So everytime we add a node do we have to restart rook operator to deploy OSD on new node? Will restarting rook operator cause any issue to existing rook PV's attached to pods?

**Comment by travisn** [comment]
@sprdeepesh I believe this will be covered by #2208. Please reopen if there is another scenario missed.
