### ISSUE TITLE
Ceph mon: support minor version updates (update deployments)

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#2331]
Currently the upgrade path for Ceph mons supports v0.8.x to v0.9.0. To support v0.9.0 -> v0.9.1, the operator needs to update the mon deployments; however, the simple approach used by the mgr and mds won't work for mons because of the double-loop which starts the mons and the fact that the monmap-init container uses the existing monmap makes the mons update every time a new mon is added.

Fix thoughts:
- `makeDeployments` can take an argument for the number of monmap mons to use for init, as long as that is deterministic with lower mon ids first.
- get rid of the double loop entirely, but this might mean duplicating some code used by `mon/health.go` (it could also be a good refactor that cleans up some stuff)

**Comment by travisn** [comment]
@BlaineEXE What if we made the following targeted fix for 0.9? 
- While interating over mons, check if the rook version and ceph versions are expected in the existing mon pod specs. If not, go ahead and call the helper to update the deployments.

This would enable upgrades, and also make sure we don't always update the mon deployments with every iteration of the loop. The only downside is if there are changes to the pod spec that wouldn't be applied. But that should only happen with master builds where the tag never changes.
