### ISSUE TITLE
How to fix: TOO_FEW_PGS

### ISSUE THREAD

**Issue by Kralor-Guldan** [rook/rook#2332]
I've looked at the related issues, and have not found a good answer.

When you have a large number of OSDs (100+), how do we fix the TOO_FEW_PGS warning?

**Comment by dimm0** [comment]
http://docs.ceph.com/docs/mimic/rados/operations/placement-groups/#set-the-number-of-placement-groups
This should be run in rook toolbox pod

**Comment by Kralor-Guldan** [comment]
This should be integrated into the filesystem and block storage options in a future release.

**Comment by Kralor-Guldan** [comment]
@dimm0 - Thank you!

**Comment by galexrt** [comment]
Reopening that we add it to the Ceph FAQ page, see #2766 or a later PR.

Also as #1191 covers automatic the calculation and Ceph is/will soon support PG down/resizing we should be good on this topic then.
