### ISSUE TITLE
rook-ceph-osd-prepare device filter

### ISSUE THREAD

**Issue by tpaoletto** [rook/rook#2336]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSD preparation failed on udev triggered device.

**Expected behavior:**
OSD preparation success.

**How to reproduce it (minimal and precise):**

If the "deviceFilter" is specified in the cluster.yaml file and it is pointing to udev-triggered devices
the rook-ceph-osd-prepare will fail.

    storage: # cluster level storage configuration and selection

    useAllNodes: true

    useAllDevices: false

    deviceFilter: "^rook."

    location:

In the rook-ceph-osd-prepare job the list of "available" devices is built by issuing:
**lsblk --all --noheadings --list --output KNAME**

**In this list all udev-triggered devices are not present.**

If you want to have a persistent-binded name on your OSDs names across cluster nodes
(eg. /dev/rook1 that points to /dev/sdh on nodeA, /dev/sdy on nodeB and /dev/sdg on nodeC)
the preparation task will not work

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804
* Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
* Cloud provider or hardware configuration: on-prem nutanix setup
* Rook version (use `rook version` inside of a Rook Pod): 0.8
* Kubernetes version (use `kubectl version`):1.8.13
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): K8S
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] (https://rook.io/docs/Rook/master/toolbox.html)): VM virtual disk on Nutanix AHV

**Comment by tpaoletto** [comment]
You can find a similar behavior on issue #1228

**Comment by galexrt** [comment]
@travisn Added to 1.0 milestone, to ensure this has either been fixed or needs to be fixed.

**Comment by travisn** [comment]
The device filter was actually just fixed with #2703, which will be included in 1.0.
