### ISSUE TITLE
Ceph mgr: old replicaset fails to scale down during upgrade

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#2337]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
During our testing, Kubernetes sometimes failed to scale down the v0.8 replicaset for the
Ceph mgr daemon. While we continue to investigate this issue, if you see two mgr pods running,
delete the old mgr replicaset in order for the new Ceph mgr to start up properly.

This has been observed on Kubernetes version v1.9.8. If you experience the issue, please let us know
on [Slack](https://rook-io.slack.com/) or on [GitHub](https://github.com/rook/rook/issues) which
Kubernetes version you are running.

**Expected behavior:**
The v0.8 mgr replicaset is scaled down.

**How to reproduce it (minimal and precise):**
Follow v0.9 upgrade guide.

**Environment**:
Kubernetes versions:
* v0.9.8
* more?

**Comment by travisn** [comment]
Removing from 0.9 as there is a workaround in the upgrade guide.
