### ISSUE TITLE
Docs: Deploy with Helm Chart will encounter error: unable to recognize "rook/cluster.yml": no matches for kind "CephCluster" in version "ceph.rook.io/v1"

### ISSUE THREAD

**Issue by litaxc** [rook/rook#2340]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
Run
```
helm install --namespace rook-ceph-system rook-beta/rook-ceph --name rook-ceph
kubectl create -f cluster.yml
```
should create the ceph cluster, but result in:
```
error: unable to recognize "rook/cluster.yml": no matches for kind "CephCluster" in version "ceph.rook.io/v1"
```
This is because CustomResourceDefinition CephCluster is not included in the helm chart. So should the chart be updated or is it requires additional steps to setup ceph cluster with helm?

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
* Kernel (e.g. `uname -a`): Linux gpu1 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`): v1.12.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by Amos-85** [comment]
Same issue for me in new rook version 0.9

**Comment by travisn** [comment]
@litaxc @Amos-85 Could you try installing the `stable` helm chart? It looks like the docs need to be updated still.
```
helm repo add rook-stable https://charts.rook.io/stable
helm install --namespace rook-ceph-system rook-stable/rook-ceph --name rook-ceph
```

**Comment by Amos-85** [comment]
Thanks @travisn  ,
I'm already use the stable chart.
@galexrt helped me on slack yesterday and there was format issues in the cluster.yaml manifest.

**Comment by kfox1111** [comment]
have chart upgrades been tested with the crd's in place? Helm has some outstanding issues with crd's.
