### ISSUE TITLE
Invalid option "dataBlockPool" for erasure coded pool

### ISSUE THREAD

**Issue by slassh** [rook/rook#2370]
* Bug Report
When you upgrade rook from v0.8.3 to v0.9 it fails to dynamically provision volumes with erasure coded pool.
` kubectl describe pvc`

` Events: 
 Warning    ProvisioningFailed    10s (x4 over 41s)  ceph.rook.io/block rook-ceph-operator-86df7b5948-n2ndx 485a0cbf-fd42-11e8-9601-caa20481834d  Failed to provision volume with StorageClass "rook-ceph-block": invalid option "dataBlockPool" for volume plugin rookVolumeProvisioner `

**Deviation from expected behavior:**
Rook should accept "dataBlockPool" attribute in storage class yaml and pass it to --data-pool in rbd create.
kubectl get pvc
NAME           STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE
pvc-postgers   Pending                                      rook-ceph-block   30s

**Expected behavior:**
rbd image with metadata replicated pool and erasure code as data pool 
**How to reproduce it (minimal and precise):**
Followed https://rook.io/docs/rook/v0.9/ceph-upgrade.html steps without getting any erros

**Environment**: 
* OS (e.g. from /etc/os-release):  Ubuntu 18.04.1 LTS
* Kernel (e.g. `uname -a`): Linux k8s-master1 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod): * rook: v0.9.0
* Kubernetes version (use `kubectl version`): Client Version: "v1.12.2"  Server Version:v1.12.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
[root@k8s-rook1 /]# ceph status
  cluster:
    id:     dd80a892-5728-4c6a-a248-8a28bd4f2400
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum rook-ceph-mon1,rook-ceph-mon0,rook-ceph-mon2
    mgr: a(active)
    osd: 3 osds: 3 up, 3 in

  data:
    pools:   2 pools, 200 pgs
    objects: 0 objects, 0B
    usage:   3.04GiB used, 184GiB / 187GiB avail
    pgs:     200 active+clean

**Comment by ky-ma** [comment]
Hello I also ran into the same issue on a clean setup of v0.9 and not from an upgrade.

**Comment by travisn** [comment]
This was caused by the renaming of types when moved to v1 in [this function](https://github.com/rook/rook/blob/b6b569ba422be38490dd94760ef26358359932cc/pkg/operator/ceph/provisioner/provisioner.go#L195). Thanks @galexrt for taking a look!
