### ISSUE TITLE
MDS image version

### ISSUE THREAD

**Issue by sinqinc** [rook/rook#2375]
I upgraded to Rook v0.9 and cephVersion.image to ceph/ceph:v13.2.2-20181023. All pods have been upgraded to that image but the MDS is still using ceph/ceph:v12.2.9-20181026. 

Is this normal ? Do I need to edit another CRD than CephCluster ?

Thank you

**Comment by travisn** [comment]
This upgrade issue was fixed in the 1.0 release. The MDS (and all daemons) will be upgraded with a ceph upgrade.
