### ISSUE TITLE
docs: adding node via rook cluster CRD is buried in the docs

### ISSUE THREAD

**Issue by frederic-loui** [rook/rook#2380]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
I read the docs in the Documention folder. However updating a cluster via CRD (adding/removing node) document is still in the design folder. I stopped by Issue #934 but could not identify if this is now possible do actually perform safe addition to the ROOK cluster.

**What is use case behind this feature:**
I fired up a cluster with one Storage node (useAllNodes is set to false). I would like to add an additional node that has a 500Gb filesystem mounted. Can I add this to the cluster via the CRD ?

**Environment**:

rook:v0.9.0

Please feel free to close this issue if this has been dealt elsewhere. And don't hesitate to point me out were I can find the link :-) Thanks !

**Comment by jbw976** [comment]
Also here's a blog post I wrote about the feature when it was originally released, if you are in a reading mood :)
https://blog.rook.io/scale-out-your-cluster-with-rook-v0-7-6abf9bcad6a6

**Comment by frederic-loui** [comment]
I'll sure read it ! (Even now...)

Le jeu. 13 déc. 2018 à 16:09, Jared Watts <notifications@github.com> a
écrit :
