### ISSUE TITLE
[rook common types] StorageSpec has Typemeta and deepcopy-gen 

### ISSUE THREAD

**Issue by yanniszark** [rook/rook#2400]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In the rook common types, `StorageScopeSpec` is not a top-level type, yet it has `Typemeta` field and `deepcopy-gen` comment. 

**Expected behavior:**
`StorageScopeSpec` should not have `Typemeta` field and `deepcopy-gen` comment. 

**How to fix:**
1. Delete `Typemeta` and `deepcopy-gen` comment.
2. Run `make codegen`
3. Check if anything broke because it used the `Deepcopy()` method. If it did, implement the method and fix it.

**Comment by jbw976** [comment]
@ZYecho I've sent you an invitation to the Assignees team of the Rook organization, so that we can assign you to this issue.  You can't assign issues in Github unless that user is a member of the organization.
