### ISSUE TITLE
[cassandra] openapi validation is outdated

### ISSUE THREAD

**Issue by yanniszark** [rook/rook#2402]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OpenAPI validation for cassandra Cluster Objects is outdated and not working correctly.

https://github.com/rook/rook/blob/master/pkg/apis/cassandra.rook.io/v1alpha1/types.go
https://github.com/rook/rook/blob/a73ffc4ac0ba76616bfa2eaa371a0373456d17f5/cluster/examples/kubernetes/cassandra/operator.yaml#L24

**Comment by jbw976** [comment]
This is the advantage of integrating with more advanced operator frameworks like kubebuilder as described in #1981.  

Crossplane has done this already and we have a make target for `make manifests` that generates all the CRD schema, validation, etc. so it is always in sync with the code:
https://github.com/crossplaneio/crossplane/blob/master/Makefile#L62-L64

**Comment by yanniszark** [comment]
Totally agree with this. 
In fact, I used the openapi-generator from controller-tools, which is the one kubebuilder uses, to fix the openapi definition this time. 
The only thing missing from kubebuilder is the ability to specify filters for the listers/informers (eg only list objects with these labels, in this namespace etc.)

**Comment by yanniszark** [comment]
This issue will be immediately fixed once we upgrade to controller-runtime+controller-tools.
