### ISSUE TITLE
FailureDomain = host not enforced?

### ISSUE THREAD

**Issue by rcgoodfellow** [rook/rook#2411]
**Is this a bug report or feature request?**
* Bug Report (possibly just documentation issue)

**Deviation from expected behavior:**
A block pool with the following deploys just fine on a cluster with just 1 worker node.

```yaml
failureDomain: host
replicated:
  size: 3
```
Here is my setup:

ceph block pool with host failure domain and a replicated size of 3
```
$kubectl describe cephblockpools replicapool -n rook-ceph

Name:         replicapool
Namespace:    rook-ceph
Labels:       <none>
Annotations:  <none>
API Version:  ceph.rook.io/v1
Kind:         CephBlockPool
Metadata:
  Creation Timestamp:  2018-12-19T23:40:11Z
  Generation:          1
  Resource Version:    337
  Self Link:           /apis/ceph.rook.io/v1/namespaces/rook-ceph/cephblockpools/replicapool
  UID:                 6cd9faad-03e7-11e9-be42-525400a8f54c
Spec:
  Failure Domain:  host
  Replicated:
    Size:  3
Events:    <none>
```

storage class that uses above replica pool
```
$kubectl describe storageclass rook-ceph-block

Name:                  rook-ceph-block
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           ceph.rook.io/block
Parameters:            blockPool=replicapool,clusterNamespace=rook-ceph
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

only 1 worker in this cluster
```
$kubectl get nodes
NAME     STATUS   ROLES    AGE   VERSION
worker   Ready    <none>   18h   v1.13.0
```

yet i have pods that have allocated block devices just fine
```
$kubectl get persistentvolumeclaims
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
elastic-pv-claim   Bound    pvc-6d1bd958-03e7-11e9-be42-525400a8f54c   2Gi        RWO            rook-ceph-block   18h
etcd-pv-claim      Bound    pvc-6cf0d73d-03e7-11e9-be42-525400a8f54c   2Gi        RWO            rook-ceph-block   18h
```

**Expected behavior:**

I would expect a failure somewhere in the chain. Either an error at the time the Ceph block pool is created or a failure (possibly delay) to schedule a pod when a persistent volume claim is present that references the block pool.

**Note:** _I do now see the 'Degraded data redundancy' warning from `ceph health`. So perhaps this is the indicator that one is living dangerously. However, this is not the expectation that is given per the [docs](https://rook.io/docs/rook/master/ceph-block.html)_

> NOTE This example requires you to have at least 3 OSDs each on a different node. This is because the replicated.size: 3 will require at least 3 OSDs and as failureDomain setting to host (default), each OSD needs to be on a different nodes.

_So perhaps this is more of a documentation issue. Given that note, I would expect the system to refuse to deploy rather than silently deploy in a risky state._

**How to reproduce it (minimal and precise):**
- Launch a single node k8s cluster
- Deploy Rook from master
- Create the `CephBlockPool` as described above
- Create a pod with a PVC and observe that it comes up

**Environment**:
* OS (e.g. from /etc/os-release):
Debian buster

* Kernel (e.g. `uname -a`):
4.16.0-2

* Cloud provider or hardware configuration:
This is in a libvirt environment. Custom k8s deployment.

* Rook version (use `rook version` inside of a Rook Pod):
v0.9.0-4.g8a49531

* Kubernetes version (use `kubectl version`):
v1.13.0

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Vanilla, self hosted, inside libvirt

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

HEALTH_WARN 58/462 objects misplaced (12.554%); Degraded data redundancy: 250/462 objects degraded (54.113%), 70 pgs degraded, 200 pgs undersized :scream_cat:

**Comment by BlaineEXE** [comment]
I am inclined to view this as a documentation issue as you mentioned. The text could be better worded to indicate that the example will work but that data redundancy will be degraded unless there are at least 3 osds on separate nodes.

This is the first time I've become aware of the `failureDomain` setting, however. The wording in the docs does suggest that because this value is `host`, the user should expect some kind of failure condition. Does @travisn or @galexrt have any thoughts?

**Comment by travisn** [comment]
It is expected that the IO will block during writes if there are not sufficient OSDs that satisfy the request. It is ceph's design to delay failing until this point in case more OSDs are configured before the time they are required during a write. Similarly, Rook does not prevent the configuration. I'm inclined to make it a doc issue as well.
