### ISSUE TITLE
Ceph dashboard fails to start on mimic with host networking

### ISSUE THREAD

**Issue by travisn** [rook/rook#2412]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The Ceph dashboard is not starting when running `mimic` and when `hostNetwork: true`.

The health status shows the following error, with a similar error in the mgr log.
```
    health: HEALTH_ERR
            Module 'dashboard' has failed: IOError("Port 8443 not free on '::'",)
```

**Expected behavior:**
The dashboard should start even when host networking is enabled.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
@travisn Which node is/was that on? `8443` is either used by another application or Kubernetes API server.

**Comment by travisn** [comment]
This was in minikube, so it likely is the k8s api server since nothing else is running. At a minimum the port needs to be configurable on the dashboard.

**Comment by travisn** [comment]
We should likely expose a setting in the cluster crd, where the default is 8443:
```
  dashboard:
    port: 8443
```

**Comment by travisn** [comment]
If this error comes up, #2468 allows the port to be configured to avoid the conflict
