### ISSUE TITLE
Selinux Labeling not working in Openshift v3.10.72

### ISSUE THREAD

**Issue by allen13** [rook/rook#2417]
Environment: Openshift v3.10.72 on Red Hat Enterprise Linux Server release 7.6 (Maipo)
Kernel: 3.10.0-862.11.6.el7.x86_64
Rook: rook/ceph:v0.9.0
Ceph: ceph/ceph:v13.2.2-20181023

Rook provisioner not labeling selinux mounts.

```
$ ls -laZ
total 4
drwxr-xr-x. 1 root root       system_u:object_r:container_file_t:s0:c10,c15   25 Dec 21 15:14 .
drwxr-xr-x. 1 root root       system_u:object_r:container_file_t:s0:c10,c15   26 Oct 24 12:20 ..
drwxr-xr-x. 1 root root       system_u:object_r:container_file_t:s0:c10,c15   40 Oct 24 12:20 apt
drwxr-xr-x. 1 root root       system_u:object_r:container_file_t:s0:c10,c15   87 Oct 24 12:20 dpkg
drwxrwsr-x. 2 root 1000230000 system_u:object_r:unlabeled_t:s0                 6 Dec 20 21:34 ec
drwxrwsrwx. 4 root 1000230000 system_u:object_r:container_file_t:s0:c10,c15   47 Dec 21 15:14 grafana
drwxr-xr-x. 2 root root       system_u:object_r:container_file_t:s0:c10,c15    6 Jun 26 12:03 misc
drwxr-xr-x. 2 root root       system_u:object_r:container_file_t:s0:c10,c15 4096 Oct 11 00:00 pam
drwxr-xr-x. 3 root root       system_u:object_r:container_file_t:s0:c10,c15   39 Oct 11 00:00 systemd
drwxrwsr-x. 2 root 1000230000 system_u:object_r:unlabeled_t:s0                18 Dec 21 15:12 two
drwxr-xr-x. 2 root root       system_u:object_r:container_file_t:s0:c10,c15   36 Oct 24 12:20 ucf
$ ls ec
ls: cannot open directory 'ec': Permission denied
```

Disabled selinux on container host machine:

`setenforce 0`

Can now succesfully create a file in the /var/lib/ec directory

Disabling selinux permanently is not an option.

**Comment by allen13** [comment]
May be related to this: https://github.com/rook/rook/blob/master/cmd/rookflex/cmd/init.go#L45

**Comment by allen13** [comment]
Changed this to true https://github.com/rook/rook/blob/master/cmd/rookflex/cmd/init.go#L45
and recompiled. It is now working. Would you accept a pull request that put this into an environment variable?

**Comment by travisn** [comment]
This was just changed with #2219 due to the perf impact when it was enabled. It seems we need to expose this as a setting to the operator so it can be set as needed. Hopefully csi will improve this situation though.

**Comment by jamstar** [comment]
its not just openshift, its anyone who runs with selinux is hit with this. i run a custom cluster with centos 7.x but run selinux.    

other than just disabling selinux, can anything be done for this?

**Comment by travisn** [comment]
No workaround other than disabling  without a code change here. We need to make this configurable in an 0.9 release (v0.9.2) soon

**Comment by allen13** [comment]
Yeah, I'll start working on something!

**Comment by allen13** [comment]
Working on this now.

**Comment by allen13** [comment]
Merge request in. Let me know if I need to add anything additional. I wasn't sure if i need to add anything to pending release notes or do any kind of testing. Plan to test this on a live cluster tommorow.
