### ISSUE TITLE
Path restriction OSD capabilities

### ISSUE THREAD

**Issue by dimm0** [rook/rook#2424]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Following the guide at https://github.com/rook/rook/blob/master/Documentation/advanced-configuration.md#use-custom-ceph-user-and-secret-for-mounting, setting the caps to `osd 'allow rw tag cephfs data=YOUR_FS_DATA_POOL'` doesn't let the client write data. I'm reading docs for mimic, and according to http://docs.ceph.com/docs/mimic/man/8/ceph-authtool/#osd-capabilities if I set it to `osd 'allow rw pool=nautilusfs-data0'`, the client writes fine. `osd 'allow rw tag cephfs pool=nautilusfs-data0'` still makes it read-only.

**Expected behavior:**
Please confirm the correct string in docs to provide enough protection and to still allow writes. I'm concerned whether this restriction really works and where did information about "(For Ceph Mimic or newer, use data=POOL_NAME instead of pool=POOL_NAME)" come from.

**How to reproduce it (minimal and precise):**
Follow the docs to restrict a path

**Environment**:
* OS (e.g. from /etc/os-release):
Centos 7
* Rook version (use `rook version` inside of a Rook Pod):
0.9
* Kubernetes version (use `kubectl version`):
1.14.2
* Ceph version:
Mimic v13.2.2-20181023

**Comment by dimm0** [comment]
After talking to @galexrt, we found that specifying the `tag cephfs` works for his new cluster, but doesn't work for mine. The filesystem can be mounted, but no data can be written to OSDs:

```root@fs-pod:/# cd /example-fs/
root@fs-pod:/example-fs# touch 1
root@fs-pod:/example-fs# echo aaa > 1
bash: echo: write error: Operation not permitted```

The caps that don't work for me:

```client.dimm
    key: <key>
    caps: [mds] allow rw path=/dimm
    caps: [mon] allow r
    caps: [osd] allow rw tag cephfs pool=nautilusfs-data0```

**Comment by dimm0** [comment]
Still there after updating to newest mimic

**Comment by jeinwag** [comment]
I just ran into the same problem on a new nautilus cluster deployed via ceph-ansible, looks like application tags are missing on the pools. This should fix it:

```
ceph osd pool application set <yout-data-pool> cephfs data <your-cephfs-name>
ceph osd pool application set <your-metadata-pool> cephfs metadata <your-cephfs-name>
```

**Comment by dimm0** [comment]
Still the same :(

```
{
    "rbd": {
        "rbd": {}
    },
    "rooks3.rgw.control": {
        "rgw": {}
    },
    "rooks3.rgw.meta": {
        "rgw": {}
    },
    "rooks3.rgw.log": {
        "rgw": {}
    },
    "rooks3.rgw.buckets.index": {
        "rgw": {}
    },
    ".rgw.root": {
        "rgw": {}
    },
    "rooks3.rgw.buckets.data": {
        "rgw": {}
    },
    "rooks3.rgw.buckets.non-ec": {
        "rgw": {}
    },
    "nautilusfs-metadata": {
        "cephfs": {
            "metadata": "nautilusfs"
        }
    },
    "nautilusfs-data0": {
        "cephfs": {
            "data": "nautilusfs"
        }
    }
}
```

```
client.dimm
	key: ...
	caps: [mds] allow rw path=/dimm
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs pool=nautilusfs-data0
```

**Comment by dimm0** [comment]
Creating activity here

**Comment by salanki** [comment]
I have the same issue.

**Comment by dimm0** [comment]
👀

**Comment by galexrt** [comment]
@dimm0 Do these instructions in the Ceph documentation https://docs.ceph.com/docs/nautilus/cephfs/client-auth/#path-restriction work for you?

**Comment by dimm0** [comment]
Nope.. Once I add a tag, it starts mounting read-only

**Comment by rmharwood** [comment]
> Nope.. Once I add a tag, it starts mounting read-only

`caps: [osd] allow rw tag cephfs pool=nautilusfs-data0`

I believe here you should have `data=nautilusfs` instead of `pool=...`

**Comment by dimm0** [comment]
Not working then... It depends on the ceph version
