### ISSUE TITLE
Ceph OSD attempts to bind to wrong IP after operator restart

### ISSUE THREAD

**Issue by areed** [rook/rook#2429]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
On a 2 node cluster after deleting the operator pod in the `rook-ceph-system` namespace and restarting the Docker container of the OSD pod in the `rook-ceph` namespace, the OSD pod gets into a CrashLoopBackoff.

**Expected behavior:**
The Docker container of the OSD pod should restart without error after deleting the operator.

**How to reproduce it (minimal and precise):**

After I brought up a 2 node cluster, the rook-ceph-osd-0 pod had ip 10.32.0.13, which matched the public addr and cluster addr config lines in the rook-ceph.config file generated by the rook-ceph-osd-prepare pod on the same node.

The 2nd node's storage wasn't being used so I deleted the operator as a workaround for https://github.com/rook/rook/issues/2208. That triggered new rook-ceph-osd-prepare jobs on both nodes in the cluster. After the jobs completed, the cluster addr and public addr in rook-ceph.config on the original node had the IP 10.32.0.27, which was the IP of the prepare pod on that node, but the OSD pod still had the ip 10.32.0.13.

When I used docker to to delete the container of the OSD pod and it restarted, it attempted to bind to the `10.32.0.27` IP and the pod got into a CrashLoopBackOff until I deleted the OSD pod.

```
areed@areed-ubuntu:~$ kubectl -n rook-ceph logs -f rook-ceph-osd-0-f6c7d5fcf-s4thl
2018-12-26 20:13:25.729506 7f2b09bf2d80  0 ceph version 12.2.8 (ae699615bac534ea496ee965ac6192cb7e0e07c0) luminous (stable), process ceph-osd, pid 20359
starting osd.0 at - osd_data /opt/replicated/rook/osd0 /opt/replicated/rook/osd0/journal
2018-12-26 20:13:25.750460 7f2b09bf2d80 -1  Processor -- bind unable to bind to 10.32.0.27:7300/0 on any port in range 6800-7300: (99) Cannot assign requested address
2018-12-26 20:13:25.750460 7f2b09bf2d80 -1  Processor -- bind unable to bind to 10.32.0.27:7300/0 on any port in range 6800-7300: (99) Cannot assign requested address
2018-12-26 20:13:25.750558 7f2b09bf2d80 -1  Processor -- bind was unable to bind. Trying again in 5 seconds
2018-12-26 20:13:25.750558 7f2b09bf2d80 -1  Processor -- bind was unable to bind. Trying again in 5 seconds
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS
* Kernel (e.g. `uname -a`): Linux areed-ubuntu 4.15.0-1025-gcp #26~16.04.1-Ubuntu SMP Wed Nov 21 10:13:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: GCE
* Rook version (use `rook version` inside of a Rook Pod): v0.9.0
* Kubernetes version (use `kubectl version`): 1.13.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH_WARN Degraded data redundancy: 249/498 objects degraded (50.000%), 94 pgs degraded, 100 pgs undersized

**Comment by travisn** [comment]
@areed Could you confirm a few items?
- Instead of using docker to delete the container, does it make a difference to delete the pod and allow the osd deployment to immediately start up a new pod? 
- Is it just the first osd with the issue, or did the second osd start with the issue as well?
- Can you share the logs of the osd pod's `config-init` init container?

**Comment by areed** [comment]
Yes that does make a difference. The OSD comes up again without error if you delete the pod. It's only if you delete the running docker container that the error occurs. I first noticed this because upgrading kubernetes with kubeadm restarts all the running containers without deleting any pods.

Yes, on a 2 node cluster it's only the first node's OSD that was already running that has the error. If I were to add a third node to the cluster and delete the operator, the first two nodes' OSDs that were already running would have the error and the third node's OSD would be ok, etc...

init container logs:
```
areed@areed-ubuntu-manager:~$ kubectl -n rook-ceph logs rook-ceph-osd-0-5f579bd94-kmpmj config-init
2018-12-28 18:42:42.753328 I | rookcmd: starting Rook v0.9.0 with arguments '/usr/local/bin/rook ceph osd init'
2018-12-28 18:42:42.753456 I | rookcmd: flag values: --cluster-id=26eaf364-0ad0-11e9-8d49-42010a800026, --encrypted-device=false, --help=false, --is-device=false, --location=, --log-level=INFO, --node-name=areed-ubuntu-manager, --osd-database-size=1024, --osd-id=0, --osd-journal-size=1024, --osd-store=, --osd-wal-size=576, --osds-per-device=1
2018-12-28 18:42:42.753464 I | cephmon: parsing mon endpoints: a=10.106.199.220:6790,b=10.99.189.80:6790,c=10.99.122.121:6790
2018-12-28 18:42:43.793057 I | cephosd: found osd 0 in dir map for path /opt/replicated/rook
2018-12-28 18:42:43.793081 I | cephosd: updating config for osd 0
2018-12-28 18:42:43.793459 I | cephconfig: writing config file /opt/replicated/rook/osd0/rook-ceph.config
2018-12-28 18:42:43.793650 I | cephconfig: copying config to /etc/ceph/ceph.conf
2018-12-28 18:42:43.793826 I | cephosd: Config file /opt/replicated/rook/osd0/rook-ceph.config:
[global]
fsid                         = fcf5ea76-3dd9-4408-8630-ab372766bc59
run dir                      = /opt/replicated/rook/osd0
mon initial members          = c a b
mon host                     = 10.99.122.121:6790,10.106.199.220:6790,10.99.189.80:6790
log file                     = /dev/stderr
mon cluster log file         = /dev/stderr
public addr                  = 10.32.0.13
cluster addr                 = 10.32.0.13
mon keyvaluedb               = rocksdb
mon_allow_pool_delete        = true
mon_max_pg_per_osd           = 1000
debug default                = 0
debug rados                  = 0
debug mon                    = 0
debug osd                    = 0
debug bluestore              = 0
debug filestore              = 0
debug journal                = 0
debug leveldb                = 0
filestore_omap_backend       = rocksdb
osd pg bits                  = 11
osd pgp bits                 = 11
osd pool default size        = 1
osd pool default min size    = 1
osd pool default pg num      = 100
osd pool default pgp num     = 100
osd max object name len      = 256
osd max object namespace len = 64
osd objectstore              = filestore
crush location               = root=default host=areed-ubuntu-manager
rbd_default_features         = 3
fatal signal handlers        = false

[osd.0]
keyring          = /opt/replicated/rook/osd0/keyring
osd journal size = 1024
```

**Comment by dimm0** [comment]
Hitting this from time to time, need to manually kill the pod

**Comment by Bfoster-melrok** [comment]
Also running into this issue

Can confirm deleting the pod manually fixes it temporarily. 

Environment:
OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
Kernel (e.g. uname -a): Linux dev-kube-1 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Cloud provider or hardware configuration: bare metal
Rook version (use rook version inside of a Rook Pod): v0.9.2
Kubernetes version (use kubectl version): 1.13.2
Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox): HEALTH_WARN
