### ISSUE TITLE
[cassandra] wrong mount point for PersistentVolume

### ISSUE THREAD

**Issue by yanniszark** [rook/rook#2443]
* Bug Report

**Deviation from expected behavior:**
The cassandra operator should mount the persistent volume under `/var/lib/cassandra`. Instead, it mounts it under `/var/lib/cassandra/data`, which is the data directory. That means the commitlog gets written in the host disk, which results in a bottleneck.

**Expected behavior:**
PersistentVolume should be mounted under `/var/lib/cassandra`.

**Comment by jbw976** [comment]
Did we want to backport this to 0.9? I'm thinking that perhaps we can just wait until 1.0 (late march timeframe) unless @yanniszark or @galexrt have a strong desire to backport to 0.9.

**Comment by yanniszark** [comment]
@jbw976 I'd prefer backporting this to v0.9.
It is a simple bug with annoying consequences, so the quicker we fix it the better.

**Comment by jbw976** [comment]
@yanniszark can you go ahead and open a pull request to backport this change to 0.9?
