### ISSUE TITLE
Ceph MON cannot connect to MGR : BADAUTHORIZER

### ISSUE THREAD

**Issue by creinig** [rook/rook#2446]
**Are you in the right place?**

* For general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://Rook-io.slack.com).
  * I tried getting an invite via https://rook-slackin.herokuapp.com/ (linked from https://rook.io/docs/rook/v0.6/common-problems.html), but the captcha config there seems to be broken & it won't accept my input due to that.
* Did you already search the existing open issues for anything similar?
  * https://github.com/rook/rook/issues/1354 might be similar. Perhaps.

**Is this a bug report or feature request?**
* Bug Report

**What happened**

1. Installed rook-ceph on a local dev cluster (2 nodes, baremetal, CentOS 7), created PersistentVolueClaims, everything worked. 
2. Node 2 crashed (network interface went down for a few hours). Node stays disconnected from k8s cluster for some time even after hardware/OS recovery (I had to research the rejoin process first)
3. After recovery, rook tries to rebalance the mons. It starts a new "-mon3" pod on node 2, which exits within a few seconds. The pod enters into "CrashLookBackOff" status soon afterwards.
4. Startup & termination of pods with a mounted PersistentVolumeClaim hangs indefinitely
5. On the underlying host, the mounts of the PVC into the pod stay even if the pod is terminated forcefully (mount of /dev/rdb0 into /var/lib/kubelet/pods/HASH/volumes/../pvc-HASH)
6. I can't really diagnose much more via the rook toolbox, since the rook-api service does not exist. I have no idea why this is the case or how it can be added manually.

**Diagnostics Info**

(1) Excerpt from the crashing mon's logs:

```
10.233.87.135:0/26 >> 10.233.121.37:6800/20 conn(0x561a304bc000 :-1 s=STATE_CONNECTING_WAIT_CONNECT_REPLY_AUTH pgs=0 cs=0 l=0).handle_connect_reply connect got BADAUTHORIZER
```

10.233.121.37 is the IP of the MGR pod. *Not* the service IP.

(2) kubectl output

```
> kubectl -n rook-ceph get all -o wide
NAME                                           READY   STATUS      RESTARTS   AGE    IP              NODE           NOMINATED NODE
pod/rook-ceph-mgr-a-5f6dd98574-tmhmz           1/1     Running     0          31d    10.233.121.37   beryllium      <none>
pod/rook-ceph-mon0-r2cwv                       1/1     Running     0          31d    10.233.121.29   beryllium      <none>
pod/rook-ceph-mon1-9w7bf                       1/1     Running     0          31d    10.233.121.38   beryllium      <none>
pod/rook-ceph-mon2-jbn5c                       1/1     Running     0          31d    10.233.121.39   beryllium      <none>
pod/rook-ceph-mon3-7l9ns                       0/1     Completed   2          28s    10.233.87.173   protactinium   <none>
pod/rook-ceph-osd-id-0-866b98745d-vzqhk        1/1     Running     0          31d    10.233.121.33   beryllium      <none>
pod/rook-ceph-osd-id-1-7749769c4d-574vl        0/1     Evicted     0          17d    <none>          protactinium   <none>
pod/rook-ceph-osd-id-1-7749769c4d-vfdbd        0/1     Evicted     0          17d    <none>          protactinium   <none>
pod/rook-ceph-osd-id-1-866cd4fc7b-f9dzf        1/1     Running     0          64m    10.233.87.186   protactinium   <none>
pod/rook-ceph-osd-prepare-beryllium-zl6hs      0/1     Completed   0          68m    10.233.121.16   beryllium      <none>
pod/rook-ceph-osd-prepare-protactinium-qmdj9   0/1     Completed   0          68m    10.233.87.141   protactinium   <none>
pod/rook-tools                                 1/1     Running     0          100m   10.233.87.191   protactinium   <none>
NAME                                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE   SELECTOR
service/rook-ceph-mgr                      ClusterIP   10.233.55.131   <none>        9283/TCP         31d   app=rook-ceph-mgr,rook_cluster=rook-ceph
service/rook-ceph-mgr-dashboard            ClusterIP   10.233.43.137   <none>        7000/TCP         31d   app=rook-ceph-mgr,rook_cluster=rook-ceph
service/rook-ceph-mgr-dashboard-external   NodePort    10.233.44.208   <none>        7000:31700/TCP   31d   app=rook-ceph-mgr,rook_cluster=rook-ceph
service/rook-ceph-mon0                     ClusterIP   10.233.29.82    <none>        6790/TCP         31d   app=rook-ceph-mon,mon=rook-ceph-mon0,mon_cluster=rook-ceph
service/rook-ceph-mon1                     ClusterIP   10.233.33.44    <none>        6790/TCP         31d   app=rook-ceph-mon,mon=rook-ceph-mon1,mon_cluster=rook-ceph
service/rook-ceph-mon2                     ClusterIP   10.233.30.22    <none>        6790/TCP         31d   app=rook-ceph-mon,mon=rook-ceph-mon2,mon_cluster=rook-ceph
service/rook-ceph-mon3                     ClusterIP   10.233.47.21    <none>        6790/TCP         28s   app=rook-ceph-mon,mon=rook-ceph-mon3,mon_cluster=rook-ceph
NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS        IMAGES             SELECTOR
deployment.apps/rook-ceph-mgr-a      1         1         1            1           31d   rook-ceph-mgr-a   rook/ceph:v0.8.3   app=rook-ceph-mgr,instance=a,rook_cluster=rook-ceph
deployment.apps/rook-ceph-osd-id-0   1         1         1            1           31d   rook-ceph-osd     rook/ceph:v0.8.3   app=rook-ceph-osd,ceph-osd-id=0,rook_cluster=rook-ceph
deployment.apps/rook-ceph-osd-id-1   1         1         1            1           30d   rook-ceph-osd     rook/ceph:v0.8.3   app=rook-ceph-osd,ceph-osd-id=1,rook_cluster=rook-ceph
NAME                                            DESIRED   CURRENT   READY   AGE   CONTAINERS        IMAGES             SELECTOR
replicaset.apps/rook-ceph-mgr-a-5f6dd98574      1         1         1       31d   rook-ceph-mgr-a   rook/ceph:v0.8.3   app=rook-ceph-mgr,instance=a,pod-template-hash=5f6dd98574,rook_cluster=rook-ceph
replicaset.apps/rook-ceph-mon0                  1         1         1       31d   rook-ceph-mon     rook/ceph:v0.8.3   app=rook-ceph-mon,mon=rook-ceph-mon0,mon_cluster=rook-ceph
replicaset.apps/rook-ceph-mon1                  1         1         1       31d   rook-ceph-mon     rook/ceph:v0.8.3   app=rook-ceph-mon,mon=rook-ceph-mon1,mon_cluster=rook-ceph
replicaset.apps/rook-ceph-mon2                  1         1         1       31d   rook-ceph-mon     rook/ceph:v0.8.3   app=rook-ceph-mon,mon=rook-ceph-mon2,mon_cluster=rook-ceph
replicaset.apps/rook-ceph-mon3                  1         1         0       28s   rook-ceph-mon     rook/ceph:v0.8.3   app=rook-ceph-mon,mon=rook-ceph-mon3,mon_cluster=rook-ceph
replicaset.apps/rook-ceph-osd-id-0-866b98745d   1         1         1       31d   rook-ceph-osd     rook/ceph:v0.8.3   app=rook-ceph-osd,ceph-osd-id=0,pod-template-hash=866b98745d,rook_cluster=rook-ceph
replicaset.apps/rook-ceph-osd-id-1-7749769c4d   0         0         0       30d   rook-ceph-osd     rook/ceph:v0.8.3   app=rook-ceph-osd,ceph-osd-id=1,pod-template-hash=7749769c4d,rook_cluster=rook-ceph
replicaset.apps/rook-ceph-osd-id-1-866cd4fc7b   1         1         1       64m   rook-ceph-osd     rook/ceph:v0.8.3   app=rook-ceph-osd,ceph-osd-id=1,pod-template-hash=866cd4fc7b,rook_cluster=rook-ceph
NAME                                           COMPLETIONS   DURATION   AGE   CONTAINERS      IMAGES             SELECTOR
job.batch/rook-ceph-osd-prepare-beryllium      1/1           3s         68m   rook-ceph-osd   rook/ceph:v0.8.3   controller-uid=4b9b2533-0f48-11e9-9826-000af74e3b38
job.batch/rook-ceph-osd-prepare-protactinium   1/1           2s         68m   rook-ceph-osd   rook/ceph:v0.8.3   controller-uid=4d01d647-0f48-11e9-9826-000af74e3b38
```

(3) ceph configs

On the underlying host, `/var/lib/rook/` exists and seems to be ok. It also contains directories `rook-ceph` and `rook-ceph-mon3` including contents with current timestamps. The contents seem to be written on each mon3 startup attempt.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
  * Local bare metal.
  * 2 Hosts with 7 cores and 64G RAM
  * Ceph data is stored in a directory on an ext4 filesystem on top of a LVM volume backed by hardware RAID
* Rook version (use `rook version` inside of a Rook Pod): v0.8.3
* Kubernetes version (use `kubectl version`):
  * Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
  * Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}  
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
  * Created locally via kubespray (which in turn uses kubeadm for much of its work)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH OK

YAMLs used to set up rook:
[01-rook-operator.yaml.txt](https://github.com/rook/rook/files/2723694/01-rook-operator.yaml.txt)
[02-rook-cluster.yaml.txt](https://github.com/rook/rook/files/2723696/02-rook-cluster.yaml.txt)

Complete log of the crashing MON pod:
[rook-mon3.log](https://github.com/rook/rook/files/2723703/rook-mon3.log)

**Comment by creinig** [comment]
"solved" the issue for now by completely taking down and re-creating the rook system.
There is still no "rook-api" pod running, but the system is usable again

**Comment by galexrt** [comment]
@creinig For Slack try using this link: https://slack.rook.io/.

Also before looking into this, you are on Rook v0.6.2 which is pretty outdated, as the current Rook release is v0.9.1. Can you try using the latest Rook version to see if you are able to reproduce?

**Comment by creinig** [comment]
That slack link worked, thanks.
Actually I seem to be using rook 0.8.3 -- the 0.6.2 is just the outdated toolbox I was using. Fixed in description..

I'll try the upgrade later, but since I'm not really willing to crash that server again I can make no promises about whether that will give more information in the short term. Longer term might be, since that box *is* kind of unstable.
