### ISSUE TITLE
Installing 'rook-ceph' helm chart on GKE fails with missing 'rbd' module

### ISSUE THREAD

**Issue by whereisaaron** [rook/rook#2448]
**Is this a bug report or feature request?**
* Bug Report

Installing the `rook-ceph` helm chart on a GKE cluster following the [chart instructions](https://github.com/rook/rook/blob/master/Documentation/helm-operator.md) and [GKE-specific instructions](https://github.com/rook/rook/blob/master/Documentation/flexvolume.md#google-kubernetes-engine-gke) fails due to missing `rbd` module.

**Deviation from expected behavior:**
The documentation suggests `rook-ceph` works on GKE but the `rbd` module appears missing on the GKE nodes images (COS version 69)? `modprobe: FATAL: Module rbd not found in directory /lib/modules/4.14.65+`

**Expected behavior:**
The documentation seems to suggest `rook-ceph` should work on GKE with just the adjusted FlexVolume path, but seems like the GKE nodes aren't built with `rbd` support? Is there a missing step in the instructions or something I missed?

**How to reproduce it (minimal and precise):**

Create GKE cluster:
```
gcloud container clusters create test1 \
 --project=rook-test \
 --cluster-version=1.11.5-gke.5 \
 --region=us-east-4 \
 --addons=HttpLoadBalancing,HorizontalPodAutoscaling,KubernetesDashboard,NetworkPolicy \
 --enable-ip-alias \
 --enable-network-policy \
 --metadata disable-legacy-endpoints=true \
 --scopes=gke-default
```
Install helm:
```
helm init
````
Add rook stable chart repo:
```
helm repo add rook-stable https://charts.rook.io/stable
```
Install the chart, with the GCE-specific FlexVolume path:
```
helm upgrade --install rook-ceph \
  --namespace rook-ceph \
  --set agent.flexVolumeDirPath=/home/kubernetes/flexvolume \
  rook-stable/rook-ceph
```
Note that agents are crashing:
```
$ kubectl get pod --namespace=rook-ceph
NAME                                  READY   STATUS             RESTARTS   AGE
rook-ceph-agent-6kll6                 0/1     CrashLoopBackOff   27         1h
rook-ceph-agent-g9z2w                 0/1     CrashLoopBackOff   27         1h
rook-ceph-agent-nsc97                 0/1     CrashLoopBackOff   27         1h
rook-ceph-operator-5dd5b9bbc6-5m5nj   1/1     Running            0          1h
rook-discover-82vxl                   1/1     Running            0          1h
rook-discover-8rklk                   1/1     Running            0          1h
rook-discover-rpjht                   1/1     Running            0          1h
```
Note that 'rbd' module appears missing (as in [troubleshooting](https://github.com/rook/rook/blob/master/Documentation/common-issues.md#rook-agent-rbd-module-missing-error)):
```
$ kubectl logs --namespace=rook-ceph rook-ceph-agent-6kll6
2019-01-03 16:47:37.354758 I | rookcmd: starting Rook v0.9.1 with arguments '/usr/local/bin/rook ceph agent'
2019-01-03 16:47:37.354846 I | rookcmd: flag values: --help=false, --log-level=INFO
2019-01-03 16:47:37.356141 I | cephcmd: starting rook ceph agent
2019-01-03 16:47:37.357009 I | exec: Running command: cat /lib/modules/4.14.65+/modules.builtin
2019-01-03 16:47:37.361450 I | exec: Running command: modinfo -F parm rbd
2019-01-03 16:47:37.363911 N | ceph-volumeattacher: failed rbd single_major check, assuming it's unsupported: failed to check for rbd module single_major param: Failed to complete 'check kmod param': exit status 1. modinfo: ERROR: Module rbd not found.
2019-01-03 16:47:37.363935 I | exec: Running command: modprobe rbd
2019-01-03 16:47:37.365052 I | modprobe rbd: modprobe: FATAL: Module rbd not found.
2019-01-03 16:47:37.365190 N | ceph-volumeattacher: failed to load kernel module rbd: failed to load kernel module rbd: Failed to complete 'modprobe rbd': exit status 1.
failed to run rook ceph agent. failed to create volume manager: failed to load kernel module rbd: Failed to complete 'modprobe rbd': exit status 1.
```
Log onto a node and test manually:
```
# modprobe rbd
modprobe: FATAL: Module rbd not found in directory /lib/modules/4.14.65+
```
Operator seemed happy when starting agents:
```
$ kubectl logs --namespace=rook-ceph rook-ceph-operator-5dd5b9bbc6-5m5nj
2019-01-03 14:56:14.225323 I | rookcmd: starting Rook v0.9.1 with arguments '/usr/local/bin/rook ceph operator'
2019-01-03 14:56:14.225461 I | rookcmd: flag values: --alsologtostderr=false, --help=false, --log-level=INFO, --log_backtrace_at=:0, --log_dir=, --logtostderr=true, --mon-healthcheck-interval=45s, --mon-out-timeout=5m0s, --stderrthreshold=2, --v=0, --vmodule=
2019-01-03 14:56:14.227107 I | cephcmd: starting operator
2019-01-03 14:56:14.353939 I | op-agent: getting flexvolume dir path from FLEXVOLUME_DIR_PATH env var
2019-01-03 14:56:14.354071 I | op-agent: discovered flexvolume dir path from source env var. value: /home/kubernetes/flexvolume
2019-01-03 14:56:14.354254 I | op-agent: no agent mount security mode given, defaulting to '%s' modeAny
2019-01-03 14:56:14.431466 I | op-agent: rook-ceph-agent daemonset already exists, updating ...
2019-01-03 14:56:14.534644 I | op-discover: rook-discover daemonset already exists, updating ...
2019-01-03 14:56:14.630950 I | operator: rook-provisioner ceph.rook.io/block started using ceph.rook.io flex vendor dir
I0103 14:56:14.631061       7 controller.go:407] Starting provisioner controller b781be8a-0f67-11e9-b158-4e0fb960bd60!
2019-01-03 14:56:14.633231 I | operator: rook-provisioner rook.io/block started using rook.io flex vendor dir
2019-01-03 14:56:14.633249 I | op-cluster: start watching clusters in all namespaces
I0103 14:56:14.633278       7 controller.go:407] Starting provisioner controller b78202ea-0f67-11e9-b158-4e0fb960bd60!
2019-01-03 14:56:14.723737 I | op-cluster: skipping watching for legacy rook cluster events (legacy cluster CRD probably doesn't exist): the server could not find the requested resource (get clusters.ceph.rook.io)
```

**Environment**:
* OS (e.g. from /etc/os-release): **Container-Optimized OS version 65 (Build 10895.91.0)**
* Kernel (e.g. `uname -a`): **Linux 4.14.65+ #1 SMP**
* Cloud provider or hardware configuration: **GKE**
* Rook version (use `rook version` inside of a Rook Pod): **v0.9.1**
* Kubernetes version (use `kubectl version`): **1.11.5-gke.5**
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): **GKE**
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): *agent crashlooping*

```
BUILD_ID=10895.91.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=ff03fe06c0fc35868c5ada1306e9471a48bec9c3
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=69
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=69
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos
```

PS. The issue template says "For general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://Rook-io.slack.com)." but it seems to require an account?

**Comment by whereisaaron** [comment]
> PS. The issue template says "For general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://Rook-io.slack.com)." but it seems to require an account?

Found that I need to go to https://slack.rook.io/ to request an account. Maybe add that link to the comment above?

**Comment by whereisaaron** [comment]
Thanks to @galexrt, the information missing from the documentation is that you can't use the default GKE configuration, you need to override GKE to use Ubuntu images for the node pool. I'll try that.

![image](https://user-images.githubusercontent.com/1109585/50660435-c1df4e80-0f6d-11e9-8e78-3a138ee9a6e5.png)

**Comment by travisn** [comment]
Fixed by #2456

**Comment by vsoch** [comment]
It looks like the workaround (using vanilla `UBUNTU`) doesn't work anymore:

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.23. This is to prepare for the removal of Dockershim in Kubernetes v1.24. We recommend that you migrate to image types based on Containerd (examples). For more information, contact Cloud Support.
```

I listed the images available and see there is an `UBUNTU_CONTAINERD`  image type:

```
validImageTypes:
- COS_CONTAINERD
- COS
- UBUNTU
- UBUNTU_CONTAINERD
- WINDOWS_LTSC
- WINDOWS_LTSC_CONTAINERD
- WINDOWS_SAC
- WINDOWS_SAC_CONTAINERD
```
so I'm going to try that, hoping that it's the standard ubuntu (with the kernel module) and they added containerd to that.

**Comment by orourkedd** [comment]
I saw the notice about the requirement for `rbd` and GKE in [2456](https://github.com/rook/rook/pull/2456). Just to be clear because there is a lot of conflicting information out there about this, as of today at least, none of the images available for GKE have `rbd` included. _This means that Rook cannot run on GKE_.

Does anyone know if there is a workaround or something?

**Comment by Sri-harsha99** [comment]
@orourkedd, Were you able to run rbd on GKE? I'm not able to get csi-rbd* pods running. Below are my pods. When I run object.yaml file, rgw pods are not online
![image](https://github.com/rook/rook/assets/44543252/c8118c39-8e9e-460e-acbe-b8f874a467aa)

![image](https://github.com/rook/rook/assets/44543252/0745ad28-6337-4f6e-8903-8a6c8877b56c)

**Comment by orourkedd** [comment]
> @orourkedd, Were you able to run rbd on GKE? I'm not able to get csi-rbd* pods running. Below are my pods. When I run object.yaml file, rgw pods are not online
> 
> ![image](https://github.com/rook/rook/assets/44543252/c8118c39-8e9e-460e-acbe-b8f874a467aa)
> 
> 
> 
> ![image](https://github.com/rook/rook/assets/44543252/0745ad28-6337-4f6e-8903-8a6c8877b56c)
> 
> 

Unfortunately, no.

**Comment by cameronraysmith** [comment]
> It looks like the workaround (using vanilla `UBUNTU`) doesn't work anymore:
> 
> ```
> ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.23. This is to prepare for the removal of Dockershim in Kubernetes v1.24. We recommend that you migrate to image types based on Containerd (examples). For more information, contact Cloud Support.
> ```
> 
> I listed the images available and see there is an `UBUNTU_CONTAINERD` image type:
> 
> ```
> validImageTypes:
> - COS_CONTAINERD
> - COS
> - UBUNTU
> - UBUNTU_CONTAINERD
> - WINDOWS_LTSC
> - WINDOWS_LTSC_CONTAINERD
> - WINDOWS_SAC
> - WINDOWS_SAC_CONTAINERD
> ```
> 
> so I'm going to try that, hoping that it's the standard ubuntu (with the kernel module) and they added containerd to that.

The `UBUNTU_CONTAINERD` node images currently seem to have the rbd module; however this can complicate the use of other tools that require `COS_CONTAINERD`.
