### ISSUE TITLE
0.9.0 chart broken rbac

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#2458]
I helm installed the rook-ceph chart into minikube using the defaults in the rook-ceph namespace. then uploaded the test ceph cluster object.

2019-01-06 20:04:06.342239 I | op-cluster: skipping watching for legacy rook cluster events (legacy cluster CRD probably doesn't exist): the server could not find the requested resource (get clusters.ceph.rook.io)
2019-01-06 20:05:53.743416 I | op-cluster: starting cluster in namespace default
2019-01-06 20:05:54.439501 W | op-k8sutil: OwnerReferences will not be set on resources created by rook. failed to test that it can be set. configmaps is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot create resource "configmaps" in API group "" in the namespace "default"
2019-01-06 20:05:54.567027 I | op-k8sutil: waiting for job rook-ceph-detect-version to complete...
2019-01-06 20:05:59.653515 E | op-cluster: failed to detect ceph version. failed to get version job log to detect version. failed to read from stream. pods "rook-ceph-detect-version-7rlrr" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "pods/log" in API group "" in the namespace "default"
2019-01-06 20:05:59.653611 E | op-cluster: unknown ceph major version. failed to get version job log to detect version. failed to read from stream. pods "rook-ceph-detect-version-7rlrr" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "pods/log" in API group "" in the namespace "default"

Looks like there is some rbac issue with the chart.

**Comment by kfox1111** [comment]
looks like it must be deployed in a particular hardcoded namespace, rook-ceph-system to work properly.

**Comment by galexrt** [comment]
@kfox1111 No, it is wanted that the user creates the RBAC for each Ceph Cluster on their own. Because users can create a Ceph cluster in *any* namespace, meaning that the bindings that would be created through the Helm chart would not be "valid" for the "user-given" namespace. This model is to prevent the Rook Ceph operator to have too much access to the cluster than needed.

If you follow the quickstart guide https://rook.io/docs/rook/v0.9/ceph-quickstart.html#create-a-rook-cluster or look at the Ceph Cluster CRD "Sample" section https://rook.io/docs/rook/v0.9/ceph-cluster-crd.html#sample you see the note that you need to create the RBAC required for the operator to be able to see the namespace with Ceph Cluster CRD and/or be able to create the components for the Ceph Cluster.

**Comment by kfox1111** [comment]
hmm.. that's https://github.com/rook/rook/issues/2109 I think.

**Comment by Bessonov** [comment]
@galexrt I spend couple of hours to get it working with helm and give up, bacause this information is missing. Look at https://github.com/rook/rook/blob/master/Documentation/helm-operator.md . There is no mention about additional rules. It's really bad. The idea behind helm is to get software working and don't bother with additional steps. Why don't not allow setting variables for namespaces?

**Comment by 2ZZ** [comment]
These resources allow the chart RBAC to work, based on https://rook.io/docs/rook/v0.9/ceph-cluster-crd.html#sample 

`apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
---
# Aspects of ceph-mgr that require access to the system namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
# Aspects of ceph-mgr that operate within the cluster's namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ceph.rook.io
  resources:
  - "*"
  verbs:
  - "*"
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-cluster-mgmt
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph
---
# Allow the osd pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-osd
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-osd
subjects:
- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: rook-ceph
---
# Allow the ceph mgr to access the cluster-specific resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-mgr
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
---
# Allow the ceph mgr to access the rook system resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-mgr-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
---
# Allow the ceph mgr to access cluster-wide resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-cluster
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-cluster
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
`
