### ISSUE TITLE
No way to specify tolerations for Ceph detect version

### ISSUE THREAD

**Issue by galexrt** [rook/rook#2461]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
While trying to look into #2384 on a one node cluster, I found that no tolerations are set on the ceph detect version Job/Pod (even if `placement.all` has a toleration in it).
This means that the Job/Pod could not start and would then timeout.

**Expected behavior:**
User being able to either specify tolerations in the Ceph Cluster CRD for the detect version Job/Pod or at least the detect Ceph version using the `placement.all` section.

**How to reproduce it (minimal and precise):**
1. Add a taint to all nodes in your cluster.
2. Add a toleration in the Cluster CRD for `all`

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v0.9.x (and earlier versions too).

**Comment by jarrpa** [comment]
I'll take a crack at this. It may take me a while, so please let me know if this becomes more urgent / higher priority.
