### ISSUE TITLE
Operator cannot communicate with latest nautilus mons

### ISSUE THREAD

**Issue by travisn** [rook/rook#2475]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When setting up a cluster with the cluster crd using the latest nautilus image (`ceph/daemon-base:latest-master`), as of today the cluster will get stuck after creating the first mon. The operator is not able to communicate with the mon to confirm that it is in quorum and that the operator can continue creating the rest of the cluster.

Note that the operator is based on the ceph/ceph:v13.2.2 image.

@liewegas Could this be related to the msgr v2 changes that just went in? Is there something needed so the nautilus mon will respond to msgr v1 communication from the operator running mimic?
 
**Expected behavior:**
The operator should be able to start a nautilus cluster.

**How to reproduce it (minimal and precise):**

- Create the operator.yaml
- Set `ceph/daemon-base:latest-master` as the cephVersion.image in the cluster.yaml
- Create the cluster.yaml
- Observe that one mon is created
- The operator log shows that it is trying to contact the mon to see if it formed quorum

Here are a few lines of the mon log that show it seems to think it is healthy.
```
2019-01-10 04:51:30.546 7f981e854e40  0 ceph version 14.0.1-2373-g97f1c05 (97f1c053fb3e2fd6ba1f61122ad4ba6ef133be5f) nautilus (dev), process ceph-mon, pid 1
...
2019-01-10 04:51:30.613 7f980317a700  1 mon.a@0(leader).paxosservice(auth 0..0) refresh upgraded, format 3 -> 0
2019-01-10 04:51:30.614 7f980317a700  0 log_channel(cluster) log [DBG] : fsmap 
2019-01-10 04:51:30.618 7f980317a700  0 mon.a@0(leader).osd e1 crush map has features 288514050185494528, adjusting msgr requires
2019-01-10 04:51:30.618 7f980317a700  0 mon.a@0(leader).osd e1 crush map has features 288514050185494528, adjusting msgr requires
2019-01-10 04:51:30.618 7f980317a700  0 mon.a@0(leader).osd e1 crush map has features 3314932999778484224, adjusting msgr requires
2019-01-10 04:51:30.618 7f980317a700  0 mon.a@0(leader).osd e1 crush map has features 288514050185494528, adjusting msgr requires
2019-01-10 04:51:30.612930 mon.a (mon.0) 0 :  [INF] mkfs 30fefc67-4868-4ddc-8350-3768d9d7fb9c
2019-01-10 04:51:30.618 7f980317a700  1 mon.a@0(leader).paxosservice(auth 1..1) refresh upgraded, format 0 -> 3
2019-01-10 04:51:30.620 7f980317a700  0 log_channel(cluster) log [DBG] : osdmap e1: 0 total, 0 up, 0 in
2019-01-10 04:51:30.621 7f980317a700  0 log_channel(cluster) log [DBG] : mgrmap e1: no daemons active

```

**Comment by alfredodeza** [comment]
known issue with the mons, a branch in ceph-ci may have the fixes: wip-fix-mon-bootstrap

**Comment by alfredodeza** [comment]
From a container ceph.conf, it seems that the ports need to be removed (both from `mon host` and `public bind addr`):

    # cat /etc/ceph/ceph.conf 
    [global]
    fsid                      = 7ef9273a-20e2-48ea-9642-870a6832468f
    run dir                   = /var/lib/rook/mon-a
    mon initial members       = a
    mon host                  = 10.111.223.178:6790
    log file                  = /dev/stderr
    mon cluster log file      = /dev/stderr
    public addr               = 10.111.223.178
    cluster addr              = 10.244.0.17
    mon keyvaluedb            = rocksdb
    mon_allow_pool_delete     = true
    mon_max_pg_per_osd        = 1000
    debug default             = 0
    debug rados               = 0
    debug mon                 = 0
    debug osd                 = 0
    debug bluestore           = 0
    debug filestore           = 0
    debug journal             = 0
    debug leveldb             = 0
    filestore_omap_backend    = rocksdb
    osd pg bits               = 11
    osd pgp bits              = 11
    osd pool default size     = 1
    osd pool default min size = 1
    osd pool default pg num   = 100
    osd pool default pgp num  = 100
    rbd_default_features      = 3
    fatal signal handlers     = false
    
    [mon.a]
    keyring          = /var/lib/rook/mon-a/keyring
    public bind addr = 10.244.0.17:6790


Only the IP should be used.

**Comment by travisn** [comment]
@alfredodeza Ok, we have certainly sprinkled the ports in many places. This was done for the case where there could be multiple mons on a single node, which is only a test scenario for really small (single-node) clusters. Does this mean it is not possible to use a different port now for the mons?

**Comment by liewegas** [comment]
let's table this for the moment.. i'm still working about the best way to define the mon_host config value when you have non-default ports and v2+v1 addrs at the same time.

**Comment by jtlayton** [comment]
FWIW, I hacked together a patch that made rook not put the ports into the mon's config file and it didn't seem to help.

**Comment by travisn** [comment]
For now, as @jtlayton found in a separate thread, a nautilus cluster can come up by changing the [default mon port](https://github.com/rook/rook/blob/d65713cc157e1045e8ca61d25073dc38a6822632/pkg/daemon/ceph/mon/init.go#L34) in rook to `6789`, which is expected as the default within ceph.
