### ISSUE TITLE
 How to copy files  into the PVC  provided  by  rook please?

### ISSUE THREAD

**Issue by GanKanTechnology** [rook/rook#2485]
### **Is this a bug report or feature request?**
Feature Request

### **What should the feature do:**
I  want  to move some backup  of  my  Mongodb    from other storage which uses ext4 files ystem to the PV&PVC  based  on  rook.io  so that the microservices on k8s-cluster may be able to  read the backup of my Mongodb. 
Can that  be able to achieve?

### **What is use case behind this feature:**
Move my whole services including data of mongodb from docker-compose to k8s based on rook.io.

### ** General  Steps to reproduce **
1. I had several microservices  running on a docker-compose platform which is a standalone server. I used docker exec to get  into the mongodb container and run mongodump to get a backup of the data then used docker cp to copy the dumped file to the host.

2. Then  copy them to the K8s server . When I use kubectl cp && kubectl exec to get into the  mongodb container and run mongorestore --drop , it processed without error and in the mongo shell I can find the databases and collections. But the microservices on the k8s cannot get and display the restored data.

3. The developer of microservices said that I would need to copy backup of  MongoDB into the PVC  so that Kubernetes can attach it to the Pod that will run mongorestore. I'm not sure how to copy that into the PVC based on rook.

### **Environment**:

CentOS Linux release 7.3.1611 (Core), 3.10.0-514.el7.x86_64
Docker :  18.06.1-ce
k8s:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
rook.git: release 0.9
rook/ceph: v0.9.1

**Comment by onedr0p** [comment]
@GanKanTechnology were you ever able to figure this out?

**Comment by galexrt** [comment]
You create your PVC(s) (for StatefulSet scale it up as needed once and scale it down again), then you can use the Rook Ceph toolbox to copy in the files by mounting the RBD block volume behind the PVC or CephFS depending on what you use.

You could also run a Pod on a certain on which you have the backup(s) mounted in using a `hostPath` volume and copy them to the PVC which could also be attached to the Pod as a volume.

Toolbox info: https://rook.io/docs/rook/v1.2/direct-tools.html
