### ISSUE TITLE
hardcoded path to rookflex

### ISSUE THREAD

**Issue by jan--f** [rook/rook#2486]
It is assumed that `rookflex` is installed in `/usr/local/bin`: https://github.com/rook/rook/blob/18b2da5fc5d7a303b9a48119ce55108b55af7f0e/pkg/daemon/ceph/agent/flexvolume/server.go#L45

Any reason `$PATH` is not used to locate it?
It's not a big deal but can be unexpected when packaging rook.

**Comment by MaZhuoFan** [comment]
Hi, I'm new to open source. Is it okay if take this issue? I want to get better at Go and programming in general and contribute to the community at the same time.

**Comment by ashishranjan738** [comment]
Maybe since we are installing the drivers in that location https://github.com/rook/rook/blob/18b2da5fc5d7a303b9a48119ce55108b55af7f0e/pkg/daemon/ceph/agent/flexvolume/server.go#L71 we don't need to locate it from $PATH.
