### ISSUE TITLE
Quickly creating many PVCs results gets stuck after binding only a few PVCs

### ISSUE THREAD

**Issue by travisn** [rook/rook#2487]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When many PVCs are quickly created (~100) without any delay, the operator stops responding to the requests to create the PVCs after binding only a few of them (the first six in this repro).

The operator log is filled with the following messages as K8s keeps retrying the operations:
```
I0114 16:41:36.821088       8 controller.go:1072] scheduleOperation[provision-cirros/cirros40[caeb899c-180e-11e9-9adf-0287988802f0]]
I0114 16:41:36.821098       8 controller.go:1072] scheduleOperation[provision-cirros/cirros51[cc7ec20a-180e-11e9-8b32-063df0a8d040]]
I0114 16:41:36.821110       8 controller.go:1072] scheduleOperation[provision-cirros/cirros55[cd1051cd-180e-11e9-8b32-063df0a8d040]]
I0114 16:41:36.821118       8 controller.go:1072] scheduleOperation[provision-cirros/cirros89[d2100f8c-180e-11e9-a678-0a5d884f71ec]]
...
```

After some period of time, a timeout message appears in the log and the influx of retries slows down. 
```
I0114 16:42:32.634844       8 leaderelection.go:198] stopped trying to renew lease to provision for pvc cirros/cirros68, task succeeded
I0114 16:42:32.834410       8 leaderelection.go:198] stopped trying to renew lease to provision for pvc cirros/cirros61, task succeeded
...
```

After these timeouts happen, the PVCs all soon complete the requests and all 100 PVCs show as bound.

**Expected behavior:**
The operator should be able to keep up with the PVC requests.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
@travisn Is this related to the closed #2007?

**Comment by travisn** [comment]
Yes, it does look related, although the operator is not crash looping in this case. Let's reopen the other one as well.

**Comment by travisn** [comment]
I was able to easily repro this locally in minikube.
- Create the operator and the default cluster.yaml
- Create the storageclass.yaml
- Create PVCs quickly in a loop. Below is the template. 
  - Creating two PVCs worked fine. 
  - Creating 20 PVCs hung after binding 5 PVCs, but then the rest were bound within about a minute. 
  - Creating 80 more PVCs hung after binding just 2 more PVCs. This time it took 30 minutes for the hang to clear up, then they were all immediately bound within a few minutes.

It appears to be an issue with the [provisioner locking code](https://github.com/rook/rook/blob/master/pkg/operator/ceph/provisioner/controller/leaderelection/leaderelection.go) that we picked up from K8s and we haven't maintained. Messages in the operator log reflect some of the messages in this source file.

Test PVC:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvclaim-$(CLAIM_NUMBER)
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
```

**Comment by jbw976** [comment]
Looks like the external provisioner that we originally took from the external-storage repo has [been moved](https://github.com/kubernetes-incubator/external-storage/tree/master/#how-to-use-the-library) to https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner.

We copied this code into our tree initially because the nightmare of k8s dependencies that were in the external-storage repo.  I wonder if we can now just use that new package as an import and remove the code from our source tree?  Worth a try to see if it builds and passing sanity testing, then go from there.

**Comment by travisn** [comment]
@jbw976 thanks for the pointer! I'll definitely start by seeing if we can reference it and remove from our tree.

**Comment by travisn** [comment]
Ok, i was able to successfully reference the external provisioner code after much struggle with the dependencies. Now I am able to see PVCs get bound without getting stuck. It took about a minute to bind 100 PVCs.
