### ISSUE TITLE
add ability to SIGHUP the ganesha daemon in cephnfs container

### ISSUE THREAD

**Issue by jtlayton** [rook/rook#2505]
The cephnfs CRD creates clusters of ganesha.nfsd daemons running in separate containers. All of the containers have a mostly-identical config that contains a %url include at the end that we point toward a RADOS object with the rest of the config (mostly EXPORT blocks).

Once we update those objects we need to be able to cue ganesha to reread its config to have them take effect. The usual way to do this is to send the daemon a SIGHUP.

After talking to @travisn, what we probably need to do is create a configmap that contains a cluster config generation number, and have a goroutine running in the rook task that watches it and sends SIGHUPs to ganesha as needed.

**Comment by kfox1111** [comment]
https://github.com/kubernetes/kubernetes/issues/22368#issuecomment-459030528 may help.

**Comment by jtlayton** [comment]
@kfox1111 thanks. I'm actually taking a different approach here and am working on a patchset to teach ganesha how to watch a RADOS object and reread its config when it gets a notification on that object. I think that's probably safer than doing any sort of signaling across containers. I'll go ahead and close this bug out for now.

**Comment by jtlayton** [comment]
FWIW, the patches for this have been merged into ganesha for v2.8, and the following PR should make rook add the necessary directive to its config file:

https://github.com/rook/rook/pull/2615
