### ISSUE TITLE
Progress info for long running client operations

### ISSUE THREAD

**Issue by jbw976** [rook/rook#251]
The `rook` tool can kick off some operations that run for a while (e.g., `rook filesystem create`).  There should be some sort of progress information available for these operations so the user knows what's going on.

**Comment by jbw976** [comment]
Progress callbacks at the rook client layer also has merit (that could be taken advantage of by both the rook tool and any other consumers of the rook client)

**Comment by travisn** [comment]
Closing all tickets related to standalone. See #985.
