### ISSUE TITLE
Consider allowing user to specify metadata and data pools when creating a shared filesystem

### ISSUE THREAD

**Issue by jbw976** [rook/rook#252]
With `rook filesystem create`, a metadata pool and a data pool are automatically created for the filesystem to use.  The user may want to specify pools that they have created already (with specific replication or erasure coding values).  Also, ceph supports multiple data pools under the covers, so the user may want to take advantage of that.

**Comment by bassam** [comment]
@travisn can this be closed?

**Comment by travisn** [comment]
Yes, this was done with #1029
