### ISSUE TITLE
[ceph] enable msgr2

### ISSUE THREAD

**Issue by leseb** [rook/rook#2525]
Ceph Nautilus added a new network protocol interface to communicate between daemons. As a result, Ceph Monitors now have to bind to a different IP than before (3300). Also the `ceph.conf` generation must change to accept the msgr2 style declaration.

Typically the `mon_host` section goes from something like this:

```
mon_host = 127.0.0.1
```

To:

```
mon_host = v2:127.0.0.1:3300/0
```

Upgrading from Mimic to Nautilus would require something like:

```
mon_host = v1:127.0.0.1:6789/0,v2:127.0.0.1:3300/0
```

So we can maintain backward compatibility and not break existing clusters.
I haven't look at the entire Rook code for this, but if Rook happens to generate a monmap 'manually' then the creation should be changed appropriately.

@liewegas am I missing something?

**Comment by leseb** [comment]
Hum it looks like we need `mon_host = v1:127.0.0.1:6789/0,v2:127.0.0.1:3300/0
`so older clients can still talk to the mon.

**Comment by leseb** [comment]
When multiple mons, we need brackets: 

`mon host = [v2:1.2.3.4:3300,v1:1.2.3.4:6789],[v2:1.2.3.5:3300,v1:1.2.3.5:6789]`

**Comment by liewegas** [comment]
- always put v2 before v1
- :+1: on the brackets
- we want the v2 + v1 addresses always, even for new clusters, since we need to support older clients (e.g., kernel) that only speak v1
- it's possible (likely?) that nautilus will default to having ``ms_bind_msgr2 = false`` by default and marked as experimental, at least for the first point release, so you may want to make this conditional.

**Comment by cerw** [comment]
After upgrading to v1.0.0 following https://rook.io/docs/rook/v1.0/ceph-upgrade.html, it seem my mon_host did not update and ceph status complaining about :

```
 health: HEALTH_WARN
            3 monitors have not enabled msgr2
```

mon_host:

```
v1:10.108.38.89:6790,v1:10.99.172.224:6790,v1:10.100.110.125:6790
```

**Comment by cerw** [comment]
Just noticed this one https://github.com/rook/rook/issues/3104
