### ISSUE TITLE
Revert mgr to minimal privs

### ISSUE THREAD

**Issue by travisn** [rook/rook#2529]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The mgr was given privileges for `mon "allow *"` instead of `mon "allow profile mgr"` temporarily to enable the dashboard to continue working until the [ceph fix]() has been released. We can revert #2523 after users move off ceph images that have this issue.

**Expected behavior:**
Mgr privileges should only include `mon "allow profile mgr"` instead of `mon "allow *"`

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by sebastian-philipp** [comment]
Just make sure, rbd mirroring actually works with profile mgr :smile:
