### ISSUE TITLE
Listing of shared filesystems should show more information

### ISSUE THREAD

**Issue by jbw976** [rook/rook#253]
With `rook filesystem ls`, only the filesystem name, metadata pool, and data pools are shown.  We could show more info/stats, particularly the local mount point of the shared filesystem (if it's mounted locally).

I don't see anywhere that is already tracking the local mount point, so we may need to add that at the `rook` layer.

`fs get` mon command could help here for status info: https://github.com/rook/ceph/blob/master/src/mon/MonCommands.h#L395

**Comment by travisn** [comment]
@jbw976 is this still relevant without standalone? we could use ceph tools now for more details as well.

**Comment by jbw976** [comment]
good point, this really isn't strictly necessary without the standalone scenario.  if a user is already in the rook toolbox, they have access to the full suite of ceph tools to augment `rookctl` functionality.
