### ISSUE TITLE
[cassandra] Add support for Prometheus/Grafana monitoring

### ISSUE THREAD

**Issue by yanniszark** [rook/rook#2530]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The cassandra operator should install the necessary plugins, in order for cassandra to export prometheus metrics. We only use plugins that will work as a javaagent. Currently there are various plugins doing that:
- [cassandra-exporter by Instaclustr](https://github.com/instaclustr/cassandra-exporter): Seems to be the best solution but is still a very early project with no Grafana dashboard. If it matures and is maintained, this will most likely be the right choice.
- [jmx-exporter by Prometheus](https://github.com/prometheus/jmx_exporter): Not made specifically for Cassandra, but it does the job. There is also a [Grafana dashboard](https://grafana.com/dashboards/5408) for it.

**What is use case behind this feature:**

Users should be able to monitor their Cassandra cluster.
Unfortunately, there's no clear cut solution.

:warning: If you have experience monitoring Cassandra using Prometheus and Grafana, please tell us your opinion.

**Comment by umangachapagain** [comment]
> The cassandra operator should install the necessary plugins, in order for cassandra to export prometheus metrics. We only use plugins that will work as a javaagent. Currently there are various plugins doing that:
> 
>     * [cassandra-exporter by Instaclustr](https://github.com/instaclustr/cassandra-exporter): Seems to be the best solution but is still a very early project with no Grafana dashboard. If it matures and is maintained, this will most likely be the right choice.
> 
Not experienced with Cassandra monitoring or cassandra-exporter, but with little experience that I have on monitoring with Prometheus & Grafana,  `cassandra-exporter` seems like a safe bet on long term.
Alerting and Dashboards can be maintained as a separate project and can mature parallel to the exporter. 

This is the way [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin) does it, and we at [gluster-mixins](https://github.com/gluster/gluster-mixins) do it.

**Comment by yanniszark** [comment]
@umangachapagain thanks for the input!
`cassandra-exporter` seems promising indeed, we could try to integrate it.

An outline of the changes for this feature is:
1. Add `cassandra-exporter` plugin in the operator image (`images/cassandra/Dockerfile`).
2. Add `cassandra-exporter` as a javaagent (`-javaagent:<plugin-dir-name>/cassandra-exporter.jar=--listen=:9180`) in [the sidecar's config setup code](https://github.com/rook/rook/blob/56461422c496c5e52418adf85a2705c4e651a906/pkg/operator/cassandra/sidecar/config.go#L138).
3. Add prometheus annotations:
   - `prometheus.io/scrape`
   - `prometheus.io/port`

to [the StatefulSet's PodSpec](https://github.com/rook/rook/blob/56461422c496c5e52418adf85a2705c4e651a906/pkg/operator/cassandra/controller/util/resource.go#L85) for port 9180.

After that we can try it out with [a basic helm installation of Prometheus](https://github.com/helm/charts/tree/master/stable/prometheus).

**Comment by umangachapagain** [comment]
@yanniszark I could look into it. But, since I do not have any idea on cassandra-exporter and javaagent etc, I will require some help setting things up and it definitely will take some time to have a complete feature.

**Comment by nabokihms** [comment]
@BlaineEXE is work on the issue in progress? I can take a look and do necessary changes if nobody minds.

**Comment by yanniszark** [comment]
I should give a little bit more context around this issue, since I have tried some things.
The problem isn't so much in integrating an exporter as in finding a good Grafana dashboard to go along with it.

The problem with the Cassandra metrics is that when exporting to Prometheus, the names aren't standard.
So two different exporters might generate a slightly different name for the same metric.
This breaks compatibility for Grafana dashboards, since they depend on the metric names.
In other words, a dashboard made for [jmx-exporter](https://github.com/prometheus/jmx_exporter) might not work for [cassandra-exporter](https://github.com/prometheus/jmx_exporter).

I tried to integrate cassandra-exporter a while back, but didn't find any compatible dashboard.
Considering that:
* cassandra-exporter hasn't seen much activity since its launch and also isn't compatible with many Cassandra versions
* cassandra-exporter has no compatible Grafana dashboard

it seems logical to reject it as an option for now and go for jmx-exporter.
It has [a compatible Grafana dashboard](https://grafana.com/dashboards/5408), can be run as a javaagent and is a mature project.

@nabokihms it would be great if you could give us a hand in getting this feature into Cassandra operator! :smile:

**Comment by nabokihms** [comment]
I think we need to keep the issue opened because of the pull request above.
