### ISSUE TITLE
CI: verify OSD API within the CephCluster CRD still works 

### ISSUE THREAD

**Issue by sebastian-philipp** [rook/rook#2545]
in the Rook orchestrator, at

https://github.com/ceph/ceph/blob/7e6783b8a82747c1ff66de391b95ad38a7da16f6/src/pybind/mgr/rook/rook_cluster.py#L340

we're using the 

```
"op": "add", "path": "/spec/storage/nodes/-", "value": {
    "name": "hostname",
    "devices": ["dev/sda1"],
    "storeConfig": {
        "storeType": "bluestore"
    }
}
```

API in the `CephCluster` CRD. 

1. Does this API still work, and 
2. is this part of the CI, and
3. does `storeConfig` support advances c-v features, like `encrypted, `db_slots` or `osds_per_device`?

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
@sebastian-philipp should this issue be open in the ceph repo to track with the mgr modules?
