### ISSUE TITLE
Batch deletion of all the pvs in oc doesnot delete all the rbd image in ceph side.

### ISSUE THREAD

**Issue by ramkiperiy** [rook/rook#2553]
[rook-ceph-operator-5c77c4bc4c-29m4b.log](https://github.com/rook/rook/files/2792895/rook-ceph-operator-5c77c4bc4c-29m4b.log)

[rbd_image__which_not_removed_in_ceph.log](https://github.com/rook/rook/files/2792901/rbd_image__which_not_removed_in_ceph.log)

**Bug Report**

Batch deletion of all the pvs in oc which has data got removed from OC but from ceph side observed around 25 rbd images not deleted.

most of the pv which not delete has below message in rook-operator log
```
E0124 14:17:15.610856       8 controller.go:769] volume "pvc-182fda8d-1fd9-11e9-a44f-0287988802f0" in work queue no longer exists
E0124 14:17:15.759511       8 controller.go:769] volume "pvc-182fda8d-1fd9-11e9-a44f-0287988802f0" in work queue no longer exists
```

**Logs:** 
operator log: http://rhsqe-repo.lab.eng.blr.redhat.com/cns/ocp-ceph-baseline/20190124/rook-ceph-operator-5c77c4bc4c-29m4b.log
list of pvs not removed in ceph http://pastebin.test.redhat.com/701623
Note: if link not accessible then check the attachment.

**How to reproduce it (minimal and precise):**
1. Create 200 or more pv 
2. mount all the 200 to pods
3. run IO's and make sure there is some data
4. delete all the pod from oc
5. delete all the pv from oc.

**Comment by nehaberry** [comment]
We are seeing similar issue again on a 3 node setup where infra, master and compute are all co-located.


Steps performed:

1. Initiated a delete of project with 200 pods and pvcs
2. Once the project is deleted, checked the pv list

Found some pvs in Released state but still present in OC. Corresponding rbd volumes were also existent in the ceph pods

**pvs not deleted from ceph side**

```
sh-4.2# rbd ls -p replicapool
pvc-07636ee6-38f4-11e9-a16b-0242b6b0b790
pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c
pvc-49a24f8e-38f4-11e9-8e4e-0637873265a6
pvc-d7107bb9-38f5-11e9-8e4e-0637873265a6
pvc-dc1d9577-38f5-11e9-a16b-0242b6b0b790
pvc-e4a3cbab-38f5-11e9-94f4-0a86a43d410c
pvc-ea2af932-38f4-11e9-8e4e-0637873265a6
```

**Released pv list**
```

[ec2-user@ip-172-31-1-106 ~]$ oc get pv -n baymax
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                           STORAGECLASS      REASON    AGE
pvc-07636ee6-38f4-11e9-a16b-0242b6b0b790   1Gi        RWO            Delete           Released   baymax/baymax036                                                rook-ceph-block             20h
pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c   50Gi       RWO            Delete           Released   openshift-monitoring/alertmanager-main-db-alertmanager-main-0   rook-ceph-block             22h
pvc-49a24f8e-38f4-11e9-8e4e-0637873265a6   1Gi        RWO            Delete           Released   baymax/baymax073                                                rook-ceph-block             20h
pvc-d7107bb9-38f5-11e9-8e4e-0637873265a6   1Gi        RWO            Delete           Released   shinchan/shinchan121                                            rook-ceph-block             20h
pvc-dc1d9577-38f5-11e9-a16b-0242b6b0b790   1Gi        RWO            Delete           Released   shinchan/shinchan128                                            rook-ceph-block             20h
pvc-e4a3cbab-38f5-11e9-94f4-0a86a43d410c   1Gi        RWO            Delete           Released   shinchan/shinchan140                                            rook-ceph-block             20h
pvc-ea2af932-38f4-11e9-8e4e-0637873265a6   1Gi        RWO            Delete           Released   baymax/baymax155                                                rook-ceph-block             20h

```


S```
ample logs from operator
=======================
0226 08:48:04.473436       9 controller.go:726] Retrying syncing volume "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c" because failures 2 < threshold 15
E0226 08:48:04.473472       9 controller.go:741] error syncing volume "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:48:04.466 7fbe1bfff700 -1 librbd::image::RemoveRequest: 0x55d1092f5670 check_image_watchers: image has watchers - not removing
I0226 08:48:04.473512       9 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c", UID:"22962509-38ea-11e9-94f4-0a86a43d410c", APIVersion:"v1", ResourceVersion:"269322", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:48:04.466 7fbe1bfff700 -1 librbd::image::RemoveRequest: 0x55d1092f5670 check_image_watchers: image has watchers - not removing
I0226 08:49:04.473752       9 controller.go:1097] delete "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": started
2019-02-26 08:49:04.476440 I | op-provisioner: Deleting volume pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c
2019-02-26 08:49:04.476476 I | exec: Running command: rbd rm replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
E0226 08:49:04.556248       9 controller.go:1120] delete "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": volume deletion failed: Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:49:04.548 7fa37effd700 -1 librbd::image::RemoveRequest: 0x558f9e2e86c0 check_image_watchers: image has watchers - not removing
W0226 08:49:04.556327       9 controller.go:726] Retrying syncing volume "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c" because failures 3 < threshold 15
I0226 08:49:04.556402       9 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c", UID:"22962509-38ea-11e9-94f4-0a86a43d410c", APIVersion:"v1", ResourceVersion:"269322", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:49:04.548 7fa37effd700 -1 librbd::image::RemoveRequest: 0x558f9e2e86c0 check_image_watchers: image has watchers - not removing
E0226 08:49:04.556424       9 controller.go:741] error syncing volume "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:49:04.548 7fa37effd700 -1 librbd::image::RemoveRequest: 0x558f9e2e86c0 check_image_watchers: image has watchers - not removing
I0226 08:51:04.556625       9 controller.go:1097] delete "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": started
2019-02-26 08:51:04.559208 I | op-provisioner: Deleting volume pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c
2019-02-26 08:51:04.559242 I | exec: Running command: rbd rm replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
E0226 08:51:04.640254       9 controller.go:1120] delete "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": volume deletion failed: Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:51:04.632 7f1242ffd700 -1 librbd::image::RemoveRequest: 0x55b5c9bca670 check_image_watchers: image has watchers - not removing
W0226 08:51:04.640317       9 controller.go:726] Retrying syncing volume "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c" because failures 4 < threshold 15
E0226 08:51:04.640407       9 controller.go:741] error syncing volume "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:51:04.632 7f1242ffd700 -1 librbd::image::RemoveRequest: 0x55b5c9bca670 check_image_watchers: image has watchers - not removing
I0226 08:51:04.640403       9 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c", UID:"22962509-38ea-11e9-94f4-0a86a43d410c", APIVersion:"v1", ResourceVersion:"269322", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:51:04.632 7f1242ffd700 -1 librbd::image::RemoveRequest: 0x55b5c9bca670 check_image_watchers: image has watchers - not removing
I0226 08:55:04.640669       9 controller.go:1097] delete "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": started
2019-02-26 08:55:04.643681 I | op-provisioner: Deleting volume pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c
2019-02-26 08:55:04.643710 I | exec: Running command: rbd rm replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
E0226 08:55:04.727032       9 controller.go:1120] delete "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": volume deletion failed: Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:55:04.719 7ff24affd700 -1 librbd::image::RemoveRequest: 0x55db6ac25740 check_image_watchers: image has watchers - not removing
W0226 08:55:04.727096       9 controller.go:726] Retrying syncing volume "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c" because failures 5 < threshold 15
E0226 08:55:04.727131       9 controller.go:741] error syncing volume "pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c": Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:55:04.719 7ff24affd700 -1 librbd::image::RemoveRequest: 0x55db6ac25740 check_image_watchers: image has watchers - not removing
I0226 08:55:04.727273       9 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c", UID:"22962509-38ea-11e9-94f4-0a86a43d410c", APIVersion:"v1", ResourceVersion:"269322", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' Failed to delete rook block image replicapool/pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c: failed to delete image pvc-227b70c3-38ea-11e9-94f4-0a86a43d410c in pool replicapool: Failed to complete '': exit status 16. 2019-02-26 08:55:04.719 7ff24affd700 -1 librbd::image::RemoveRequest: 0x55db6ac25740 check_image_watchers: image has watchers - not removing


```

**Operator logs attached:** 
[operatoor_logs_delete_issue.zip](https://github.com/rook/rook/files/2904650/operatoor_logs_delete_issue.zip)

**Comment by clkao** [comment]
This appears to be caused by rbd not properly unmounted and unmapped by agent after pod termination.
do you have the logs from agent?

we've also seen cases that rbd is umounted but not unmapped after pod termination, which causes fllesystem corruption as the pvc might be remounted by another node by a new pod.
