### ISSUE TITLE
rook-ceph-POD fails to start

### ISSUE THREAD

**Issue by dimthe** [rook/rook#2558]
Hello 

I have cloned tag 0.9.1 and I am trying to create a rook cluster following the docs. I have completed all the pod security policies from here : https://rook.io/docs/rook/v0.8/rbac.html#rbac-for-podsecuritypolicies

and all pods are running but one. 

```
`rook-ceph-system   rook-ceph-agent-dsxfh                      1/1     Running                           0          142m
rook-ceph-system   rook-ceph-agent-jxtnd                      1/1     Running                           0          142m
rook-ceph-system   rook-ceph-agent-pjgwr                      1/1     Running                           0          142m
rook-ceph-system   rook-ceph-agent-t9q9q                      1/1     Running                           0          142m
rook-ceph-system   rook-ceph-operator-68576ff976-sw29t        1/1     Running                           0          143m
rook-ceph-system   rook-discover-8rbcm                        1/1     Running                           0          142m
rook-ceph-system   rook-discover-r8nkl                        1/1     Running                           0          142m
rook-ceph-system   rook-discover-w57v8                        1/1     Running                           0          142m
rook-ceph-system   rook-discover-z2w2z                        1/1     Running                           0          142m
rook-ceph          rook-ceph-mgr-a-79564676c7-jrhm4           0/1     Init:CreateContainerConfigError   0          99m
rook-ceph          rook-ceph-mon-a-648fdc669d-kqs2m           1/1     Running                           0          141m
rook-ceph          rook-ceph-mon-b-6f67d56b8d-z9gqs           1/1     Running                           0          141m
rook-ceph          rook-ceph-mon-c-6dcb64d588-vvdzn           1/1     Running                           0          140m`

```

errors from the failing pod 

`Events:
  Type     Reason          Age   From               Message
  ----     ------          ----  ----               -------
  Normal   Scheduled       31s   default-scheduler  Successfully assigned rook-ceph/rook-ceph-mgr-a-79564676c7-8c84c to node3
  Normal   Pulled          4s    kubelet, node3     Container image "rook/ceph:v0.9.1" already present on machine
  Warning  Failed          4s    **kubelet, node3     Error: container has runAsNonRoot and image will run as root**
  Normal   SandboxChanged  3s    kubelet, node3     Pod sandbox changed, it will be killed and re-created.`

i would expect this error if i had not done all the podsecuritypolices but why this is failing ?  thanks

**Comment by dimthe** [comment]
i solved this by creating this yaml


`apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rook-rbac
  namespace: rook-ceph
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: rook-ceph-mgr
    # Reference to upper's `metadata.namespace`
    namespace: rook-ceph
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io`



on another note  the rest of the pods the documentation is showing as running are missing from my set up. I do not see osd pods running . Maybe because i have not labeled storage nodes ? i did not see this in the documentation 

`rook-ceph-system   rook-ceph-agent-dsxfh                      1/1     Running            0          4h22m
rook-ceph-system   rook-ceph-agent-jxtnd                      1/1     Running            0          4h22m
rook-ceph-system   rook-ceph-agent-pjgwr                      1/1     Running            0          4h22m
rook-ceph-system   rook-ceph-agent-t9q9q                      1/1     Running            0          4h22m
rook-ceph-system   rook-ceph-operator-68576ff976-sw29t        1/1     Running            0          4h22m
rook-ceph-system   rook-discover-8rbcm                        1/1     Running            0          4h22m
rook-ceph-system   rook-discover-r8nkl                        1/1     Running            0          4h22m
rook-ceph-system   rook-discover-w57v8                        1/1     Running            0          4h22m
rook-ceph-system   rook-discover-z2w2z                        1/1     Running            0          4h22m
rook-ceph          rook-ceph-mgr-a-79564676c7-sjsbw           1/1     Running            0          21m
rook-ceph          rook-ceph-mon-a-648fdc669d-kqs2m           1/1     Running            0          4h20m
rook-ceph          rook-ceph-mon-b-6f67d56b8d-z9gqs           1/1     Running            0          4h20m
rook-ceph          rook-ceph-mon-c-6dcb64d588-vvdzn           1/1     Running            0          4h19m`

**Comment by dimthe** [comment]
do we have an idea as to why osd pods are never created and there are no logs in kubectl events ? 
i tried to redeploy from master with the same results

**Comment by travisn** [comment]
@dimthe The operator logs likely show an error why the osds were not created. There may also be an issue with your cluster crd. Could you share the cluster.yaml and the operator log?

**Comment by travisn** [comment]
@dimthe I see in your cluster CRD you're setting the device name to be `/dev/loop0`. Rook actually needs to consume raw devices such as `sda` rather than a loopback. The devices cannot have any partitions or formatted filesystem either. Do you have a device to try that? You also don't need to specify the `/dev` prefix, so it would look like this in the CRD:
```
devices:
- name: sda
```

If you don't have a raw device, you could try defining a `directory` in the CRD.

**Comment by dimthe** [comment]
hello 

i did not have other devices to try that . These are virtual machines  and i ended up using a directory path for storage and all is good
