### ISSUE TITLE
rook-ceph v0.9.1 monitor failure on "service-monitor.yaml"

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#2560]
Yes

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

# kubectl create -f service-monitor.yaml
error: unable to recognize "service-monitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

**Expected behavior:**

"ServiceMonitor" should be created. 

Note: 

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"

* Kernel (e.g. `uname -a`):
# uname -a
Linux test-cluster-control-01 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
openstack
* Rook version (use `rook version` inside of a Rook Pod):
v0.9.1
* Kubernetes version (use `kubectl version`):
# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

# ceph -s
  cluster:
    id:     80e961b3-954c-4360-90dc-1e24eee69767
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum b,a,c
    mgr: a(active)
    osd: 3 osds: 3 up, 3 in
    rgw: 1 daemon active
 
  data:
    pools:   7 pools, 700 pgs
    objects: 236  objects, 4.3 KiB
    usage:   6.0 GiB used, 7.3 GiB / 13 GiB avail
    pgs:     700 active+clean

**Comment by galexrt** [comment]
This is not a Rook issue.

Have you followed the docs and created/applied the Prometheus operator manifest(s)? https://rook.io/docs/rook/v0.9/ceph-monitoring.html

**Comment by yan636** [comment]
Yes, please close the issue.
