### ISSUE TITLE
Kubelet not starting: traversing plugins directory

### ISSUE THREAD

**Issue by LittleFox94** [rook/rook#2568]
**Is this a bug report or feature request?**
* Bug Report

I'm not entirely sure if this is a kubernetes/kubelet or rook bug.

**Deviation from expected behavior:**

Error logged by kubelet, kubelet then crashed.

```
Jan 26 23:24:32 southern kubelet[23327]: F0126 23:24:32.810859   23327 kubelet.go:1401] failed to start Plugin Watcher. err: failed to traverse deprecated plugin socket path "/var/lib/kubelet/plugins", err: failed to watch /var/lib/kubelet/plugins/rook.io/rook/mounts/pvc-1914bbb7-bb83-11e8-abed-c6aec8d08f6d/updater-oc00f00d5632/backups/nextcloud-11.0.2.7/apps/files_texteditor/css, err: no space left on device
```

**Expected behavior:**

Kubelet not crashing due to lots of files in plugins directory.

**How to reproduce it (minimal and precise):**

* Have pods running on node which use volumes managed by rook.
* Have a volume with lots of files/data (in my case it's a nextcloud data volume).
* Restart kubelet

Workaround to get the kubelet working again: unmount all rbd volumes manually and start kubelet again.

**Environment**:
* OS (e.g. from /etc/os-release): Debian Stretch
* Kernel (e.g. `uname -a`): 4.9.0-8-amd64
* Cloud provider or hardware configuration: virtual machines, affected node has 8 cores and 16GB ram. Affected node changes with that pod
* Rook version (use `rook version` inside of a Rook Pod):  v0.9.0-68.g8d7302a
* Kubernetes version (use `kubectl version`): v1.13.2 (also seen in v1.12.5 before upgrading - upgraded today from v1.10.11 to 1.13.2 while installing the newest patch for every minor version)
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Custom-built plain kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTHY, everything fine

**Comment by mmack** [comment]
Nearly the same problem here. Kubelet crashes and does not came back.

```
 12379 kubelet.go:1401] failed to start Plugin Watcher. err: failed to traverse deprecated plugin socket path "/var/lib/kubelet/plugins", err: failed to watch /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-ae6778f9-1e2d-11e9-8db6-0050568460f6/scanfiles.154943984228764/reports/, err: no space left on device
```

fdisk states it's not full:
```
/dev/rbd3        976M   81M  828M   9% /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-ae6778f9-1e2d-11e9-8db6-0050568460f6
inodes:
/dev/rbd3          65536  20064    45472   31% /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-ae6778f9-1e2d-11e9-8db6-0050568460f6
``` 

Version infos:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

Rook: 0.8.1
```

**Comment by mmack** [comment]
For the record, i ran a fscheck over the device, and it was corrupted. After repairing it it works again:

```
k8s-worker-04 ~ # fsck /dev/rbd1 
fsck from util-linux 2.32
e2fsck 1.43.3 (04-Sep-2016)
/dev/rbd1 contains a file system with errors, check forced.
Pass 1: Checking inodes, blocks, and sizes

Running additional passes to resolve blocks claimed by more than one inode...
Pass 1B: Rescanning for multiply-claimed blocks
Multiply-claimed block(s) in inode 150: 4263
Multiply-claimed block(s) in inode 156: 4267
Multiply-claimed block(s) in inode 168: 4271
Multiply-claimed block(s) in inode 334: 4313
Multiply-claimed block(s) in inode 355: 4323
Multiply-claimed block(s) in inode 367: 4327
Multiply-claimed block(s) in inode 373: 4331
Multiply-claimed block(s) in inode 385: 4335
Multiply-claimed block(s) in inode 391: 4339
Multiply-claimed block(s) in inode 403: 4343
Multiply-claimed block(s) in inode 513: 34883
Multiply-claimed block(s) in inode 514: 4447
Multiply-claimed block(s) in inode 515: 4448
Multiply-claimed block(s) in inode 13480: 34883
Multiply-claimed block(s) in inode 13481: 4447
Multiply-claimed block(s) in inode 16385: 4263
Multiply-claimed block(s) in inode 16386: 4267
Multiply-claimed block(s) in inode 16387: 4271
Multiply-claimed block(s) in inode 16388: 4312
Multiply-claimed block(s) in inode 16389: 4313
Multiply-claimed block(s) in inode 16390: 4323
Multiply-claimed block(s) in inode 16391: 4327
Multiply-claimed block(s) in inode 16392: 4331
Multiply-claimed block(s) in inode 16393: 4335
Multiply-claimed block(s) in inode 16394: 4339
Multiply-claimed block(s) in inode 16395: 4343
Multiply-claimed block(s) in inode 16396: 4344
Multiply-claimed block(s) in inode 16848: 4448
Multiply-claimed block(s) in inode 24752: 4312
Multiply-claimed block(s) in inode 24760: 4344
Pass 1C: Scanning directories for inodes with multiply-claimed blocks
Pass 1D: Reconciling multiply-claimed blocks
(There are 30 inodes containing multiply-claimed blocks.)
...
```

**Comment by LittleFox94** [comment]
It works for me if the volume is not mounted before kubelet starts, may that be the same for you?

**Comment by mmack** [comment]
Yes same here...

**Comment by LittleFox94** [comment]
I suspect fsck only helped because of the side effect of unmounting the fs, hence my question. Is this possible?

**Comment by mmack** [comment]
Got you, good point. Restarting kubelet again does not work. Same error again:

```
 kubelet.go:1401] failed to start Plugin Watcher. err: failed to traverse deprecated plugin socket path "/var/lib/kubelet/plugins", err: failed to watch /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-ae6778f9-1e2d-11e9-8db6-0050568460f6/scanfiles.154947724132445/reports, err: no space left on device
```

umount the device and kubelet comes up again.

**Comment by eknudtson** [comment]
We ran into this with elasticsearch pods using rook/ceph RBD backed storage.  Our current workaround is to increase the `fs.inotify.max_user_instances` and `fs.inotify.max_user_watches` sysctls.

**Comment by clkao** [comment]
Apparently kubelet tries to probe for CSI registration socket in the plugin dir, and tries to watch recursively: https://github.com/kubernetes/kubernetes/issues/74669
