### ISSUE TITLE
Rook using root volume as OSD

### ISSUE THREAD

**Issue by immesys** [rook/rook#2569]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Even though I have no directories listed in the cluster CRD, if a node in the k8s cluster has no disks suitable for becoming OSDs, the prepare process randomly makes a directory-type OSD from the root volume

**Expected behavior:**
On a kubernetes cluster, for nodes that do not yet have disks suitable for OSD preparation, the prepare process will just do nothing.

**How to reproduce it (minimal and precise):**
Install rook on a cluster where some machines only have a root drive and no other disks.

**Environment**:
* Cloud provider or hardware configuration:
AWS
* Rook version (use `rook version` inside of a Rook Pod):
0.9.2
* Kubernetes version (use `kubectl version`):
1.11.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
KOPS

**Comment by immesys** [comment]
To give an idea of why this is so bad, what happened to me was the following:

I needed to upgrade the AMI for my 4-node ceph cluster, so my process was:

- Attach 4 new nodes with the new AMI
- Run the rook operator to install on the new machines
- Detach the EBS volumes from the old machines and attach to the new machines
- Restart rook operator it finds the OSDs, automatically adjusting the OSD tree

Unfortunately, what happened was that rook created four filestore OSDs on the new machines before the volumes were moved over.  THEN once the volumes were moved over it created four filestore OSDs on the old machines, and the OSDs on the new machines, *which now had placement groups on them* die and fail to restart with `global_init: unable to open config file from search list /var/lib/rook/osdXX/rook-ceph.config`

Now I don't event want these directory OSDs so I don't mind that they are not starting, except... there were four of them which means that I now have hundreds of placement groups that have lost every single copy and all of my pools are down

**Comment by clkao** [comment]
are you using ceph-volume based osd? seems similar to #2445. see also #2546

**Comment by immesys** [comment]
I am using ceph-volume osds, yes. This issue looks similar to both of those issues.

**Comment by travisn** [comment]
@immesys Thanks for taking a look. The conditional is wrong when checking for mon quorum [here](https://github.com/rook/rook/blob/ac0dfe12678c20c50dd61bc5b63f101fafb97399/pkg/operator/ceph/cluster/mon/mon.go#L606). We should likely be checking with `>=` instead of '!='. I still want to dig a bit more to see if there would be other side effects of that change.

**Comment by immesys** [comment]
@travisn are you perhaps referring to #2570? I'll try making that change and seeing what happens, but any time you spend on this is very appreciated

**Comment by travisn** [comment]
Ha, yes it was intended for #2570 thanks. Too many issues open...
