### ISSUE TITLE
Consider storing secrets for mounting storage in kernel keyring

### ISSUE THREAD

**Issue by jbw976** [rook/rook#257]
When block and file storage is mounted, appropriate cephx auth/secrets are needed.  In modern kernels, there is support to store the secret in the kernel keyring and then pass the name of the key (instead of its value) to the mapping/mounting of the storage.

A golang implementation:
https://github.com/jsipprell/keyctl

Relevant code in krbd: https://github.com/rook/ceph/blob/master/src/krbd.cc#L143

**Comment by travisn** [comment]
Closing all tickets related to standalone. See #985.

**Comment by jbw976** [comment]
I think this still has merit outside of the standalone scenario (e.g. when using `rookctl` or maybe the volume plugin could do it too)

**Comment by travisn** [comment]
@jbw976 where would we use this? since we're following k8s patterns, not sure what else there is to do

**Comment by jbw976** [comment]
We would use this in the rook-agents volume plugin when it is performing a mount.  This is still valid.
