### ISSUE TITLE
rook should expose "events" from the cluster

### ISSUE THREAD

**Issue by jbw976** [rook/rook#258]
rook should expose important events that occur in the cluster.  For example, new node added, disk failures, etc.

This should be exposed at all layers including the rook tool: `rook events ls`
rook API: `GET /events`

and golang rook client.

**Comment by thephred** [comment]
We should look at docker's API specifically around "logs" "events" and "attach" in the case of logs and attach it seems to "upgrade" the request into a persistent tcp connection over which stuff can be streamed.  In the case of the events it looks like it supports a "until" param that causes it to stream out results for a period of time (using http streaming response).  Either could be helpful here:
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/monitor-dockers-events
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/get-container-logs

**Comment by travisn** [comment]
we can accomplish this now by watching kubernetes objects. not sure there is more to do here
