### ISSUE TITLE
LVM prereq in doc missing

### ISSUE THREAD

**Issue by mhaluska** [rook/rook#2591]
Please update documentation. On my CentOS 7.6 non-LVM install I ended without OSDs after node reboot.

2019-01-30 05:17:56.749669 I |  stderr: failed to read label for /dev/ceph-839de169-4203-4156-811e-931a05741e95/osd-data-cec8622b-290f-49fd-84fa-29420d025686: (2) No such file or directory
2019-01-30 05:17:56.749673 I | 2019-01-30 05:17:56.744 7f2471a25a00 -1 bluestore(/dev/ceph-839de169-4203-4156-811e-931a05741e95/osd-data-cec8622b-290f-49fd-84fa-29420d025686) _read_bdev_label failed to open /dev/ceph-839de169-4203-4156-811e-931a05741e95/osd-data-cec8622b-290f-49fd-84fa-29420d025686: (2) No such file or directory
failed to activate osd. Failed to complete '': exit status 1.

So please put LVM package as prereq in your documentation.

**Comment by galexrt** [comment]
@mhaluska Can you please post the whole logs. LVM package(s) are installed inside the Ceph container image used.

What Rook version are you running?

**Comment by mhaluska** [comment]
Version 0.9.2, it was latest in time I created this issue.

**Comment by mhaluska** [comment]
@galexrt and sorry, logs are already removed after redploy. Machine was CentOS without LVM installed.

**Comment by kanjie128** [comment]
I have the same problem after node reboot.
the osd pod has the CrashLoopBackOff status on the reboot node.
`kubectl get pods -n rook-ceph -o wide`
```
NAME                                     READY   STATUS             RESTARTS   AGE    IP             NODE         NOMINATED NODE   READINESS GATES
rook-ceph-mgr-a-68bb465674-pdkbb         1/1     Running            0          7d9h   10.244.2.103   k8s.node1    <none>           <none>
rook-ceph-mon-a-7c85bf4c76-pdc4p         1/1     Running            0          7d9h   10.244.2.101   k8s.node1    <none>           <none>
rook-ceph-mon-b-699f8df495-pbtkj         1/1     Running            0          7d9h   10.244.1.205   k8s.node2    <none>           <none>
rook-ceph-mon-c-c45cdcfdd-rr85x          1/1     Running            0          7d9h   10.244.2.102   k8s.node1    <none>           <none>
rook-ceph-osd-0-7fdbbf884-8wjk2          1/1     Running            0          7d9h   10.244.1.207   k8s.node2    <none>           <none>
rook-ceph-osd-1-86b9b5688-ct5h8          1/1     Running            0          7d9h   10.244.2.105   k8s.node1    <none>           <none>
rook-ceph-osd-2-785c774b6d-6xkp4         0/1     CrashLoopBackOff   24         7d8h   10.244.0.70    k8s.master   <none>           <none>
rook-ceph-osd-prepare-k8s.master-kdwwf   0/2     Completed          0          93m    10.244.0.73    k8s.master   <none>           <none>
rook-ceph-osd-prepare-k8s.node1-8wxgz    0/2     Completed          0          93m    10.244.2.146   k8s.node1    <none>           <none>
rook-ceph-osd-prepare-k8s.node2-vckwd    0/2     Completed          0          93m    10.244.1.2     k8s.node2    <none>           <none>
rook-ceph-tools                          1/1     Running            0          7d9h   10.244.2.106   k8s.node1    <none>           <none>
```
 
`kubectl logs  rook-ceph-osd-2-785c774b6d-6xkp4 -n rook-ceph` 
```
2019-03-25 12:16:30.447529 I | rookcmd: starting Rook v0.9.0-305.gcbbfd6e with arguments '/rook/rook ceph osd start -- --foreground --id 2 --osd-uuid ff469fb1-8dd1-403f-96c1-f39c1fc0ce01 --conf /var/lib/rook/osd2/rook-ceph.config --cluster ceph'
2019-03-25 12:16:30.447628 I | rookcmd: flag values: --help=false, --log-flush-frequency=5s, --log-level=INFO, --osd-id=2, --osd-store-type=bluestore, --osd-uuid=ff469fb1-8dd1-403f-96c1-f39c1fc0ce01
2019-03-25 12:16:30.447636 I | op-mon: parsing mon endpoints: 
2019-03-25 12:16:30.447640 W | op-mon: ignoring invalid monitor 
2019-03-25 12:16:30.447891 I | exec: Running command: ceph-volume lvm activate --no-systemd --bluestore 2 ff469fb1-8dd1-403f-96c1-f39c1fc0ce01
2019-03-25 12:16:30.644157 I | -->  RuntimeError: command returned non-zero exit status: 1
2019-03-25 12:16:30.644379 I | Running command: /bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-2
2019-03-25 12:16:30.644393 I | Running command: /usr/sbin/restorecon /var/lib/ceph/osd/ceph-2
2019-03-25 12:16:30.644397 I | Running command: /bin/ceph-bluestore-tool --cluster=ceph prime-osd-dir --dev /dev/ceph-937efb4a-0ff9-44d7-8a28-59a7edb2f661/osd-data-ed45979d-84d1-4c1d-b28d-29c465361c64 --path /var/lib/ceph/osd/ceph-2 --no-mon-config
2019-03-25 12:16:30.644404 I |  stderr: failed to read label for /dev/ceph-937efb4a-0ff9-44d7-8a28-59a7edb2f661/osd-data-ed45979d-84d1-4c1d-b28d-29c465361c64: (2) No such file or directory
failed to activate osd. Failed to complete '': exit status 1. 
```
Besides, I'm using `/dev/vdb` as the device storage in cluster.yaml. 
```
...
- name: "k8s.master"
       devices: # specific devices to use for storage can be specified for each node
       - name: "vdb"
     - name: "k8s.node1"
       devices: # specific devices to use for storage can be specified for each node
       - name: "vdb"
     - name: "k8s.node2"
       devices: # specific devices to use for storage can be specified for each node
       - name: "vdb"
...
```
Is there any way to solve or debug this problem? thanks.

**Comment by mhaluska** [comment]
Try to install lvm on system, this solved my problem. What is your system? What is # lvs outpout?

**Comment by kanjie128** [comment]
@mhaluska tks for response. True that, I missed the LVM on centos7.
The first time I installed rook-ceph without LVM on my system. 
When the node reboot, the VG created by ceph was not mounted by default because of the missing of LVM. So, ceph-osd can not find the VG correctly. 
After I installed LVM, lvscan told me the LV was inactive:
```
# lvscan 
  inactive          '/dev/ceph-937efb4a-0ff9-44d7-8a28-59a7edb2f661/osd-data-ed45979d-84d1-4c1d-b28d-29c465361c64' [100.00 GiB] inherit
```
I guess the node need reboot again for LVM to find the VG(not tested). 
I active the VG manully by:
```
# vgchange -a y ceph-937efb4a-0ff9-44d7-8a28-59a7edb2f661
```
Then the CrashLoopBackOff ceph-osd restart successfully.

**Comment by wanghkkk** [comment]
yes,install the lvm,after reboot,is running.
yum install -y lvm2

**Comment by franznemeth** [comment]
We ran into the exact same issue on a stripped down ubuntu 18.04 without the lvm2 package.

Installing the lvm2 package and rebooting the node fixed the issue.

**Comment by BlaineEXE** [comment]
Do we know why `lvm2` is required on hosts? Lvm is installed in containers, but is there something else we can do to remove this dependency from the host?

**Comment by mhaluska** [comment]
@BlaineEXE: I'm not sure, but I think docker guest is not priviledged to modify devs. Actually you can try force lvm scan, but docker will not be able create/link new devs.

**Comment by andrewrynhard** [comment]
> Do we know why `lvm2` is required on hosts? Lvm is installed in containers, but is there something else we can do to remove this dependency from the host?

This is something I'm hoping to see as well. Having a host dependency doesn't work for us in https://github.com/talos/talos-systems. I have noticed that the rook `CSI` implementation also has host dependencies.

**Comment by bradbeam** [comment]
Worked a bit with @andrewrynhard on our cluster and the rook prepare pod is sufficient to do what is necessary. It seems like it mainly boils down to activating the volume group ( `vgchange -a y` ) and then the kernel does the rest. If lvm is installed on the host, the volume groups are typically auto activated on boot (configurable via lvm.conf) which creates the /dev/vgxx/lvxx device files. 

In looking through the [ceph-volume code](https://github.com/ceph/ceph/blob/master/src/ceph-volume/ceph_volume/api/lvm.py), it's effectively a wrapper around the lvm commands. So if ceph is able to make use of the lvm commands to create a volume group and do what is necessary to get the OSD running, we should be able to as well. 

```
[01:47:05] $ kubectl exec -it -n rook-ceph rook-ceph-osd-prepare-worker-02-brad -c provision /bin/bash

[root@rook-ceph-osd-prepare-worker-02-brad /]# vgs
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  VG                                        #PV #LV #SN Attr   VSize    VFree
  ceph-73075a08-cd85-4863-be84-95fcca597840   1   1   0 wz--n- <111.79g    0 
[root@rook-ceph-osd-prepare-worker-02-brad /]# ls -l /dev | grep ceph

[root@rook-ceph-osd-prepare-worker-02-brad /]# vgchange -ay
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  1 logical volume(s) in volume group "ceph-73075a08-cd85-4863-be84-95fcca597840" now active
[root@rook-ceph-osd-prepare-worker-02-brad /]# ls -l /dev | grep ceph
drwxr-xr-x  2 root root       60 Jun 26 06:47 ceph-73075a08-cd85-4863-be84-95fcca597840

[root@rook-ceph-osd-prepare-worker-02-brad /]# ls -l /dev/ceph-73075a08-cd85-4863-be84-95fcca597840
total 0
lrwxrwxrwx 1 root root 110 Jun 26 06:47 osd-data-b0b509db-c584-41ac-8f99-2d92f898bbc0 -> /dev/mapper/ceph--73075a08--cd85--4863--be84--95fcca597840-osd--data--b0b509db--c584--41ac--8f99--2d92f898bbc0
```

**Comment by bradbeam** [comment]
Perhaps we can add an init container to do the vg activation if `osd.CephVolumeInitiated` in pkg/operator/ceph/cluster/osd/spec.go#makeDeployment ?

**Comment by bradbeam** [comment]
Trying something like 
```
kubectl patch deployment -n rook-ceph rook-ceph-osd-0 -p '{"spec": { "template": { "spec": { "initContainers": [ { "name": "vgactivate", "image": "ceph/ceph:v13.2.5-20190319", "command": [ "vgchange" ], "args": [ "-a", "y" ], "securityContext": { "privileged": true, "readOnlyRootFilesystem": false, "runAsUser": 0 }, "volumeMounts": [ { "mountPath": "/run/udev", "name": "run-udev" } ] } ] } } } }'
```

**Comment by bradbeam** [comment]
Was missing the `/dev` mount in the previous patch. 
```
kubectl patch deployment -n rook-ceph rook-ceph-osd-0 -p '{"spec": { "template": { "spec": { "initContainers": [ { "name": "vgactivate", "image": "ceph/ceph:v13.2.5-20190319", "command": [ "vgchange" ], "args": [ "-a", "y" ], "securityContext": { "privileged": true, "readOnlyRootFilesystem": false, "runAsUser": 0 }, "volumeMounts": [ { "mountPath": "/run/udev", "name": "run-udev" }, { "mountPath": "/dev", "name": "devices" } ] } ] } } } }'
```
( or yaml to be more presentable )
```yaml
      initContainers:
      - args:
        - -a
        - "y"
        command:
        - vgchange
        image: ceph/ceph:v13.2.5-20190319
        imagePullPolicy: IfNotPresent
        name: vgactivate
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
          readOnlyRootFilesystem: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/udev
          name: run-udev
        - mountPath: /dev
          name: devices
```
works for creating the necessary volume group / logical volume special files

**Comment by AliMD** [comment]
I think I have the same problem, any solution? #3640

**Comment by mhaluska** [comment]
I think you can close this issue. LVM prereq is mentioned in doc now:
https://rook.io/docs/rook/v1.1/k8s-pre-reqs.html (section LVM package)

**Comment by travisn** [comment]
Yes, closing since it is added to the docs now

**Comment by ceyhunn** [comment]
After  restart, `/dev/ceph-....` directory disappears.  I have the same issue, but it doesn't work, neither patch nor init container, but `vgchange` makes `/dev/ceph-....` active, only problem I can't see the directory, that is why osd pod fails.  `/dev/ceph-....` can't be restored. I use rancher os. Please help me, what am I missing?
