### ISSUE TITLE
v0.9.2. , storage devices issues

### ISSUE THREAD

**Issue by dimthe** [rook/rook#2592]
3. Did you already search the existing open issues for anything similar? -->
i did but no help
**Is this a bug report or feature request?**
* maybe bug

**Expected behavior:**
rook-ceph-detect-version to run
**How to reproduce it (minimal and precise):**

setup a cluster with kubespray and set podsecuritypolicy: true and kubernetes 1.12.2

i am trying to get rook-ceph up and running . 
 
the operator.yaml runs ok  , the cluster.yaml ( with runAsUser: 1000 ) is giving this error

```
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       27m                    default-scheduler  Successfully assigned rook-ceph/rook-ceph-detect-version-rt6c5 to node4
  Normal   SandboxChanged  27m (x2 over 27m)      kubelet, node4     Pod sandbox changed, it will be killed and re-created.
  Warning  Failed          25m (x11 over 27m)     kubelet, node4     Error: container has runAsNonRoot and image will run as root
  Normal   Pulled          2m15s (x120 over 27m)  kubelet, node4     Container image "ceph/ceph:v13.2.4-20190109" already present on machine
ubuntu@node1:~/rook$
```

here is a list of my psp , 

```
kubectl get psp --all-namespaces
NAME          PRIV    CAPS   SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
permit-root   false          RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
privileged    true    *      RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
restricted    false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
```

and clusterrolebindings

```
rook-ceph-admin                                        5d
rook-ceph-detect-version                               24h
rook-ceph-detect-version-mrgsr                         56m
rook-ceph-global                                       159m
rook-ceph-system-psp                                   5d4h
rook-rbac                                              5d
rook-rbac-nfs                                          4d16h
```

what is wrong ?  thanks

**Comment by dimthe** [comment]
i gave it another try and started from scratch 
this time i have added loop0 devices for storage  and i have pasted my cluster.yaml here
https://pastebin.com/awEh5V1z
```

rook-ceph          rook-ceph-osd-prepare-node1-bmbsn          0/2     Completed   1          6m20s
rook-ceph          rook-ceph-osd-prepare-node2-ptvxm          0/2     Completed   1          6m20s
rook-ceph          rook-ceph-osd-prepare-node3-6wf8p          0/2     Completed   0          6m19s
rook-ceph          rook-ceph-osd-prepare-node4-k5d2v          0/2     Completed   0          6m19s
```

what is wrong in my crd please
thanks

**Comment by travisn** [comment]
@dimthe a few thoughts to consider...
- in the cluster.yaml, if you want to specify individual nodes in the `nodes` element, you'll need to set `useAllNodes: false`. Otherwise, the operator will ignore the `nodes` section of the crd.
- Rook won't recognize `loop0` as a valid device. In the log you pasted above, notice this message. Only raw block devices are recognized.
```
inventory: skipping device loop0: Failed to complete 'lsblk /dev/loop0': exit status 1. lsblk: /dev/loop0: not a block device
```
- If you want to get a cluster up and running, the default settings will start one osd on each node. But rather than consuming a device, it will create an OSD in the dataDirHostPath. It looks like you do have an OSD created already due to this default.

Is the issue that you want to create OSDs on devices rather than in the dataDirHostPath?

**Comment by dimthe** [comment]
> No, rook won't recognize the symlink in that case. If you don't have available devices in the VM, you can simply use directories on the local file system. The default rook already created for you is in dataDirHostPath. Will that work for you?

it will work as this is for testing now . So if i simply leave   dataDirHostPath: /var/lib/rook as is , is going to work ? 

can i edit the running pods or i should start from zero again 

thank you

**Comment by travisn** [comment]
This line in your log shows that you already have the dataDirHostPath configured, so it looks like you're already running:
```
cephosd: configuring osd dirs: map[/var/lib/rook:-1]
```

You can check the health of the cluster by starting the rook toolbox and running `ceph status`

**Comment by dimthe** [comment]
i should start the rook toolbox even with rook-osd-prepare-pods in 0/2 status ?

**Comment by dimthe** [comment]
here we are

```

[root@node4 /]# ceph status
  cluster:
    id:     64dd4ef6-df6d-4b17-80ae-20174795fb6f
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,c,b
    mgr: a(active)
    osd: 4 osds: 4 up, 4 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0  objects, 0 B
    usage:   44 GiB used, 111 GiB / 155 GiB avail
    pgs:
```

**Comment by dimthe** [comment]
look ok to me  now i need to figure out how to have dynamic pvs with ceph

**Comment by travisn** [comment]
@dimthe For an example of creating a storage class and provisioning the storage, see the [block storage docs](https://rook.io/docs/rook/v0.9/ceph-block.html). For more questions, I'd recommend the rook slack channel.

**Comment by travisn** [comment]
Sounds like this is resolved now.
