### ISSUE TITLE
ceph dashboard is not loading

### ISSUE THREAD

**Issue by dimthe** [rook/rook#2596]
hello 
i have this set to true in cluster.yaml

```
 # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
```
should at this point see a dashboard pod running in the rook namespace? If yes ,  there is not one . 

i have created the service from the existing yamls 

```
kubectl get service -n rook-ceph
NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
rook-ceph-mgr                            ClusterIP   10.233.38.146   <none>        9283/TCP         11h
rook-ceph-mgr-dashboard-external-https   NodePort    10.233.49.23    <none>        8443:31530/TCP   40m
rook-ceph-mon-a                          ClusterIP   10.233.14.85    <none>        6790/TCP         12h
rook-ceph-mon-b                          ClusterIP   10.233.56.31    <none>        6790/TCP         12h
rook-ceph-mon-c                          ClusterIP   10.233.44.9     <none>        6790/TCP         11h
```

telnet 10.100.1.201 31530
Trying 10.100.1.201...
telnet: Unable to connect to remote host: Connection refused

thanks

**Comment by travisn** [comment]
@dimthe You should see a dashboard service such as this:
```
rook-ceph-mgr-dashboard   ClusterIP   10.96.122.65     <none>        8443/TCP   145m
```

There is not an independent pod for the dashboard, as it is running as a module in the mgr pod. The operator must be failing to start the dashboard. What is your cephVersion.image in the cluster.yaml? What version of rook? Can you share the operator log?

**Comment by dimthe** [comment]
hello 
i am using the latest rook version with image: ceph/ceph:v13.2.4-20190109

the dashboard is now working. I had an error in the cluster yaml but i don't know if this was the cause for the dashboard not loading . 


i was using loop0 devices for storage and these were not working. i found out later when i used directories for storage and that time the dashboard worked
