### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by mhaluska** [rook/rook#2597]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
pod has unbound immediate PersistentVolumeClaims. Just tried to reboot node where wordpress has been scheduled with pv claim.

**Expected behavior:**
pod should be able to bound pv in case of node failure, unbound pv in case of node failure 

**How to reproduce it (minimal and precise):**

1. deploy rook on kubernetes cluster (in my case 3 masters and 3 nodes, each node has 2 disks for ceph)
2. create storageclass with replication 2, failureDomain host
3. deploy example mysql and wordpress app
4. execute "reboot" on node where wordpress is running
5. you should get same error 

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.6
* Kernel (e.g. `uname -a`): Linux pocmaster01 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: VMware
* Rook version (use `rook version` inside of a Rook Pod): rook: v0.9.2
* Kubernetes version (use `kubectl version`): 13.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
> ceph health
HEALTH_OK

**Comment by mhaluska** [comment]
My fault, enough is delete terminated pod:
kubectl delete pods <pod name> --force --grace-period=0

Seems on kubernetes issue not removed terminated pods and in my case blocking pv:
https://github.com/kubernetes/kubernetes/issues/51835

**Comment by alexcpn** [comment]
In my case the storage.yaml missed a space in key value and the logs of the rook operartor was complaining ; Please check logs `kubectl -n rook-ceph logs --tail=10  rook-ceph-operator-xxxx`
Error
`github.com/rook/operator-kit/watcher.go:76: Failed to list *v1.CephBlockPool: v1.CephBlockPoolList.Items: []v1.CephBlockPool: v1.CephBlockPool.Spec: v1.PoolSpec.Replicated: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|licated":"size:1"}}]|..., bigger context ...|7d-4e45-812f-b6f9f2ebc545"},"spec":{"replicated":"size:1"}}],"kind":"CephBlockPoolList","metadata":{|...`
Success (after correction)

`I0725 10:31:22.157055       6 controller.go:1196] provision "rook-cassandra/rook-cassandra-data-rook-cassandra-ndac-cl1-ndac-cl1-0" class "rook-ceph-block": started
`
