### ISSUE TITLE
When upgrading ceph to new version wait for OSD to be up again before removing next one

### ISSUE THREAD

**Issue by skippie81** [rook/rook#2600]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When upgrading to newer ceph version by changing the image in the CephCluster.rook.io crd data. the osd's all restarted using the new image. This is done one by one, and the next one is restated when the previous one has a pod status ready (or running). But this does not mean the osd is completely up and running again, it takes a while before the osd is back in status UP in the cluster. So we get to a point during the upgrade process where there are multiple ods's in status down and the cluster has PG's in state down.  At that point in time clients will have read errors.

output of ceph -s at that point in time in our minimal test cluster
```
kubectl --namespace=pnu-acc-rook exec -it rook-ceph-tools-58cff5bd4d-h5zgw -- ceph -s
  cluster:
    id:     e55cef19-0f7a-4bbf-84cb-2ea2167577ff
    health: HEALTH_WARN
            noscrub,nodeep-scrub flag(s) set
            3 osds down
            3 hosts (3 osds) down
            72/35346 objects misplaced (0.204%)
            Reduced data availability: 14 pgs inactive, 14 pgs down
            Degraded data redundancy: 23460/35346 objects degraded (66.372%), 497 pgs degraded

  services:
    mon: 3 daemons, quorum rook-ceph-mon51,rook-ceph-mon49,bb
    mgr: a(active)
    osd: 4 osds: 1 up, 4 in; 1 remapped pgs
         flags noscrub,nodeep-scrub

  data:
    pools:   1 pools, 512 pgs
    objects: 11.78 k objects, 46 GiB
    usage:   145 GiB used, 173 GiB / 318 GiB avail
    pgs:     2.734% pgs not active
             23460/35346 objects degraded (66.372%)
             72/35346 objects misplaced (0.204%)
             405 active+undersized+degraded
             92  stale+active+undersized+degraded
             10  stale+down
             4   down
             1   active+undersized+remapped
```
when all osd's are restarted and they have the time to fully be up and running again the cluster gets back to HEALTH_OK state

**Expected behavior:**
when restarting an osd during an upgrade process, wait for that osd to be marked as UP again in the ceph cluster status. (ceph osd tree -f json would give this information)

**How to reproduce it (minimal and precise):**

* run cluster with image     image: ceph/ceph:v13.2.2-20181023
* edit CephCLuster.rook.io resource and set image: ceph/ceph:v13.2.4-20190109

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Kernel (e.g. `uname -a`): Linux s1s0053z.be.srv.acc.sys 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Vmware
* Rook version (use `rook version` inside of a Rook Pod):  rook: v0.9.0
* Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Plain kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by christianhuening** [comment]
ping

**Comment by leseb** [comment]
This was fixed by https://github.com/rook/rook/pull/2901
