### ISSUE TITLE
Mon placement should respect failure domains

### ISSUE THREAD

**Issue by vreon** [rook/rook#2603]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

The operator can avoid placing two mons on the same host, but those hosts could still be in the same failure domain. The operator should take the `failure-domain.beta.kubernetes.io/region` and `failure-domain.beta.kubernetes.io/zone` labels into account when placing mons.

This feature was kicked around in [another issue's comments](https://github.com/rook/rook/issues/1193#issuecomment-341986819) a while back, but I didn't see a dedicated issue for it.

**What is use case behind this feature:**

Helps the Ceph cluster survive outages involving an entire failure domain.

**Environment**:
n/a

**Comment by mykaul** [comment]
Does that relate in any way, btw, to the CRUSH map? Will we be using logic and placement from K8S or Ceph (or both) ?

**Comment by vreon** [comment]
@mykaul it's similar but independent, I think. #1366 is the one for the CRUSH map

**Comment by noahdesu** [comment]
@travisn v1.1?

**Comment by travisn** [comment]
Actually, this should be covered by #3093. @vreon Could you review that change and confirm if it covers your scenario? Thanks!

**Comment by vreon** [comment]
@travisn Definitely! #3093 covers OSDs, fixing #2883 and #1366, but I don't think it covers this scenario (mon placement treating nodes as the failure domain rather than consulting labels).

**Comment by travisn** [comment]
Yep, that's only for OSDs, got my wires crossed. Added to the 1.1 milestone.

**Comment by noahdesu** [comment]
hey @galexrt as part of looking into this issue, I went through a lot of existing provisioning code from https://github.com/rook/rook/commit/2873558ecd61dfadc841a0c03e6b0e09c9485d0a and https://github.com/rook/rook/commit/e7d20647aa120dda0145a116b89943c83315f55b used to prefer that monitors not be scheduled on the same node.

when considering failure domains, i'm looking at some of the topology aware scheduling and anti-affinity features in k8s and to a first approximation it appears that these features may be able to express _both_ the existing anti-collocation and failure domain consideration for monitor placement.

it seems these k8s scheduling features may have been around when some of the monitor scheduling work was done, so I'm trying to understand if there are good reasons for not using these features that I'd discover if I went down that route. thoughts?

cc @travisn

**Comment by mmgaggle** [comment]
For consideration:

https://github.com/kubernetes/kubernetes/issues/68981

**Comment by noahdesu** [comment]
hey @mmgaggle thanks. the plan is to first adjust the existing explicit scheduling to handle AZ spreading. that code is done and under review. after (or during) the transition to running monitors on PVs, we're gonna look at ripping all the scheduling out and using k8s scheduling affinity features that you referenced. it's not immediately clear how hard/easy that is going to be.

**Comment by mmgaggle** [comment]
Sounds good, that link has some examples of how day 2 operations can be kinda sketchy so I wanted to let ya'll know there be dragons. :)
