### ISSUE TITLE
Reduce support scope of Host Networking

### ISSUE THREAD

**Issue by leseb** [rook/rook#2604]
As discussed in https://github.com/rook/rook/issues/2031, we decided to lower-down the supported scope of the Host Networking functionality.

Decision:

* do not allow more than one monitor with hostnetworking enabled on the same machine
* do not support multiple cluster on the same machine when hostnetworking is enabled
With that, we can keep decent support without introducing too much complexity in Rook's code.

**Comment by travisn** [comment]
Agreed on this change. If someone really wants to run multiple clusters with host networking, they would need more nodes so they could partition the mons and osds that would belong to each cluster. But my impression is that users generally only have a single cluster when using host networking.
