### ISSUE TITLE
Implement ceph-volume inventory command

### ISSUE THREAD

**Issue by leseb** [rook/rook#2606]
In recent development versions of c-v, a new sub-command has been introduced:

`ceph-volume inventory` which lists devices on a particular machine and report their availability by applying some filters.

The idea is to eventually replace the existing discovery code from `discover.go` with the new `ceph-volume inventory` command. Although both will co-exist depending on the Ceph version we are running on.

**Comment by sebastian-philipp** [comment]
The Ceph orchestrator need a reliable way to gather the ceph inventory for the Ceph Dasbhaord.

I can think of three reasons:

1. Right now, the Ceph orchestrator uses the private config maps with `app=rook-discover`. 
2. It also [blocks](https://trello.com/c/b5EBVEMp/87-change-inventorydevice-itself-to-mirror-c-v-inventory-closely) a refactoring within the Ceph orchestrator, as Rook is the only orchestrator still not using c-v inventory.
3. Using c-v inventory reduces the risk of API changes breaking the Ceph orchestrator by aligning with an existing standard.

cc @bk201 @BlaineEXE

**Comment by BlaineEXE** [comment]
I'm not sure `ceph-volume` is appropriate for the discover daemon, as that is backend-agnostic. For getting `ceph-volume inventory` information to the Ceph mgr, I think the `cmd-reporter` may be the right way forward.

**Comment by travisn** [comment]
I could see the discovery daemonset being enabled to have a backend-specific extension that runs with the device discovery. We already have this daemonset in place so extending it is a natural progression. 

Using the cmd-reporter would require running the job on each node to gather the device info. I'd like to avoid that if we already have the discovery daemonset running everywhere.

**Comment by leseb** [comment]
I've been thinking about this one and never actually updated this one. You're right @BlaineEXE, `discovery.go` using ceph-volume is not a good idea. That's why I was leaning towards extracting the discovery daemon into the Rook-Ceph piece and keep the existing one for other backends.

**Comment by sebastian-philipp** [comment]
Causes https://tracker.ceph.com/issues/41746

**Comment by leseb** [comment]
Closed via https://github.com/rook/rook/pull/4053.
