### ISSUE TITLE
A downgrade procedure/guide is needed 

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#2613]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
A downgrade guide is needed for backout, which can  backout the upgrade procedure ( https://rook.github.io/docs/rook/v0.9/ceph-upgrade.html). 

**What is use case behind this feature:**
If upgrade failed, the user can backout to its previous version.

**Environment**:

**Comment by travisn** [comment]
The upgrade is not transactional, so it is difficult to reverse an upgrade once it has started. Have you seen an issue with upgrade where it was necessary to stop and roll back? If so, I'd like to understand what went wrong so we can improve the upgrade.

**Comment by yan636** [comment]
In production, the rook-ceph will be upgraded with other application. If the application fails and needs to be backed out, rook-ceph has to be backed out as part of the release.

**Comment by yanchicago** [comment]
Rollback is useful whenever upgrade presents. Please keep the ticket open.

**Comment by yanchicago** [comment]
Any guidance or workaround on this? Tried to set the operator image back to old one and it failed.

**Comment by travisn** [comment]
@yanchicago What was the failure? The operator actually doesn't prevent a downgrade today. It will go ahead and deploy the version requested. While Ceph doesn't always support the downgrade, most of the time it should work if downgrading a patch release.

**Comment by dimm0** [comment]
How can I downgrade? Urgent!!
