### ISSUE TITLE
ceph-mgr dashboard also needs to have its backend set to "rook"

### ISSUE THREAD

**Issue by jtlayton** [rook/rook#2616]
For reasons that are not completely clear to me, we have to set the orchestrator backend in two different places. We already set it for the command line (`ceph orchestrator set backend rook`), but the dashboard also needs to be informed about the backend. Can we add this command to the mgr setup?

```
ceph dashboard set-orchestrator-backend rook
```
This may not be merged into ceph just yet, as I think it's being done as part of this PR: https://github.com/ceph/ceph/pull/25918. That should be merged within the next day or so though.

**Comment by sebastian-philipp** [comment]
if possible, Id prefer, if we have only one setting. I expect some kind of confusion when the cli and volumes module uses a different backend that the dashboard.

**Comment by jtlayton** [comment]
Ok, let me close this out and we can look at doing that instead.

**Comment by sebastian-philipp** [comment]
See http://tracker.ceph.com/issues/38223
