### ISSUE TITLE
Generic support for multi-homed Rook clusters

### ISSUE THREAD

**Issue by dyusupov** [rook/rook#2621]
**Is this a bug report or feature request?**
* Feature Request

Both EdgeFS and Ceph Rook operators will benefit from generic API to enable multi-homed network via existing Kubernetes solutions. One of them is https://github.com/intel/multus-cni.

**What should the feature do:**

Provide generic Rook API that would be called by EdgeFS and Ceph operators to enable multi-homed cluster namespaces.

**What is use case behind this feature:**

We'd like to solve most critical issue of client vs backend network separation. Kubernetes's simplistic flat model only good enough for limited use cases. Production environments often need strong isolation in terms of to reduce tail latency, improve QoS/SLA and data security.

**Environment**:

**Comment by BlaineEXE** [comment]
Related: https://github.com/rook/rook/issues/2031

**Comment by mykaul** [comment]
I believe Ceph strongly prefers host network. That being said, it'd still be interesting to support multi-home there (assuming there's no bond configured), but I'm not sure how much Ceph supports this.
