### ISSUE TITLE
Design Proposal: Rook-Ceph Object Bucket Provisioning

### ISSUE THREAD

**Issue by copejon** [rook/rook#2624]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Describe the purpose and implementation of dynamic bucket provisioning in the Rook-Ceph operator.

**What is use case behind this feature:**

As a Rook-Ceph user, I can already provision object stores and object store users via the Kubernetes API.  I want to provision a bucket in an object that I've created using these CRDs and have returned a Pod-attachable object containing connection data for the bucket.

**Comment by copejon** [comment]
cc @jvance @eboyd @liewegas @travisn @jbw976

**Comment by travisn** [comment]
Already completed in v1.1
