### ISSUE TITLE
cluster FSID is not defined in mgr pod

### ISSUE THREAD

**Issue by alfredodeza** [rook/rook#2628]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** the cluster FSID is not defined in mgr pods

**Expected behavior:**

**How to reproduce it (minimal and precise):** Dumping the /etc/ceph/ceph.conf will show that there is no fsid defined in the global section

**Environment**:
* OS (e.g. from /etc/os-release): minikube v0.33.1
* Kernel (e.g. `uname -a`): OSX Darwin papaya-2.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Jan 30 11:45:51 PST 2018; root:xnu-3248.73.8~1/RELEASE_X86_64 x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): release-0.9 (sha 2da0f82612b997711123f0a3a5df985a2b411c22)
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-30T14:36:33Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

This was found using ceph-medic

    $ ceph-medic check
    Host: rook-ceph-mon-a-65888bb8c8-7dwls  connection: [connected  ]
    Host: rook-ceph-mon-b-6d5b644b9b-jpj89  connection: [connected  ]
    Host: rook-ceph-mon-c-74b79cdcdf-gf9lb  connection: [connected  ]
    Host: rook-ceph-osd-0-568dc6c9f5-tc7lf  connection: [connected  ]
    Host: rook-ceph-mgr-a-5c8797779d-8wj9f  connection: [connected  ]
    Collection completed!
    
    =======================  Starting remote check session  ========================
    Version: 1.0.4    Cluster Name: "ceph"
    Total hosts: [5]
    OSDs:    1    MONs:    3     Clients:    0
    MDSs:    0    RGWs:    0     MGRs:       1
    
    ================================================================================
    
    ---------- managers ----------
     rook-ceph-mgr-a-5c8797779d-8wj9f
       ECOM5: fsid "" is different than host(s): rook-ceph-mon-a-65888bb8c8-7dwls,rook-ceph-mon-b-6d5b644b9b-jpj89,rook-ceph-mon-c-74b79cdcdf-gf9lb,rook-ceph-osd-0-568dc6c9f5-tc7lf
    
    ------------ osds ------------
     rook-ceph-osd-0-568dc6c9f5-tc7lf
       ECOM5: fsid "b62e002d-9492-4219-8448-f5b260acc93d" is different than host(s): rook-ceph-mgr-a-5c8797779d-8wj9f
       WOSD3: OSD nodes might not be enough for a healthy cluster (3 needed, 1 found)
       WOSD2: osd default pool size is set to 1, can potentially lose data
    
    ------------ mons ------------
     rook-ceph-mon-a-65888bb8c8-7dwls
       ECOM5: fsid "b62e002d-9492-4219-8448-f5b260acc93d" is different than host(s): rook-ceph-mgr-a-5c8797779d-8wj9f
     rook-ceph-mon-b-6d5b644b9b-jpj89
       ECOM5: fsid "b62e002d-9492-4219-8448-f5b260acc93d" is different than host(s): rook-ceph-mgr-a-5c8797779d-8wj9f
     rook-ceph-mon-c-74b79cdcdf-gf9lb
       ECOM5: fsid "b62e002d-9492-4219-8448-f5b260acc93d" is different than host(s): rook-ceph-mgr-a-5c8797779d-8wj9f
    
    49 passed, 7 failed, on 5 hosts

**Comment by alfredodeza** [comment]
If rook is going to allow more than one cluster, then the FSID should be defined in `ceph.conf`. @travisn I believe you said that the missing FSID doesn't create any issues, but how would one go about identifying what cluster does a pod belong to without an FSID? 

In any case, if this should *not* be considered a problem and rook is not going to support multiple clusters ever, we should close this ticket confirming the assumptions.

I think that defining an FSID is a good idea anyway, and in general, it is good to be able to identify cluster membership by going into a specific host without having to talk to the monitor to find about this

**Comment by leseb** [comment]
@alfredodeza almost all the daemons (excluding the OSDs) are using Ceph params in the CLI call, for instance a monitor will be:

```
ceph-mon --fsid=27fe6afb-a7c8-460f-9383-21eb53c8d56d --keyring=/etc/ceph/keyring-store/keyring --log-to-stderr=true --err-to-stderr=true --mon-cluster-log-to-stderr=true --log-stderr-prefix=debug  --mon-host=[v2:10.107.248.118:3300,v1:10.107.248.118:6789] --mon-initial-members=a --id=a --foreground --public-addr=10.107.248.118 --public-bind-addr=172.17.0.6
```

And the `ceph.conf` has:

```
[root@rook-ceph-mon-a-65cbbbd965-7c4dj /]# cat /etc/ceph/ceph.conf 
[global]
log_file                  = 
mon_cluster_log_file      = 
mon_allow_pool_delete     = true
mon_max_pg_per_osd        = 1000
osd_pg_bits               = 11
osd_pgp_bits              = 11
osd_pool_default_size     = 1
osd_pool_default_min_size = 1
osd_pool_default_pg_num   = 100
osd_pool_default_pgp_num  = 100
rbd_default_features      = 3
fatal_signal_handlers     = false
```

So parsing the `ceph.conf` will never work as a validation.

**Comment by alfredodeza** [comment]
If looking at the `ceph.conf` isn't a good way to do this, would looking into the socket a preferred alternative? or what would be the suggestion here?

**Comment by travisn** [comment]
@alfredodeza If the fsid is specified as a CLI arg as @leseb mentioned, should that fix the issue? I believe that was added in master since this issue was opened. Rook doesn't generate much in the ceph.conf anymore since we're moving to the CLI args. Does ceph medic look at those args?

**Comment by alfredodeza** [comment]
@travisn we are just trying to identify what cluster does a node (server/pod/container) belongs to. If using `ceph.conf` is no longer feasible, what would be the better way to do this? I don't know know how to look at the arguments on how a daemon is launched (perhaps parsing `ps` ?)

**Comment by travisn** [comment]
How is ceph medic connecting to a node? According to the [docs](http://docs.ceph.com/ceph-medic/master/), looks like you can give it ssh info for bare metal clusters. How does it work for containerized or k8s deployments? Ceph medic connects to the containers? Instead of connecting to the containers, my impression is that ceph medic could look at the k8s api to get args to the pods, but that's a much bigger design question.

**Comment by alfredodeza** [comment]
@travisn for kubernetes and openshift, ceph-medic uses the `exec` sub-command and shells out into the containers. To retrieve all the known containers we get all the ones that match the namespace, and then we do poke inside the JSON returned to understand what container is member of what group (OSD, MON, etc...).

Ideally, the way we collect information wouldn't change from containers to baremetal. E.g. `ceph --version` should work anywhere. Poking around at the args on how a daemon was launched seems brittle and very special-cased to rook. If there is any other way to understand what the cluster FSID of a daemon is, that would be great. I *think* that would be the socket (which would give us commonality) but I am just not sure.

**Comment by travisn** [comment]
Higher level question... Ceph medic is trying to catch user misconfiguration, right? If so, would it make sense to skip some checks if Rook configured the cluster? Certain settings like the FSID would already be automated for you and wouldn't be a cause for misconfiguration. It may not be worth the effort to jump through hoops to check something that isn't ever going to be incorrect.

**Comment by alfredodeza** [comment]
ceph-medic can be configured to ignore errors or warnings. The reason this is a check is because there have been deployments of clusters that have a mismatched FSID, which is a problem. Having something that makes sure that the cluster as a whole has the same FSID has been very useful in the past.

Are you confirming that it is impossible to run more than 1 cluster with Rook? If so, there might not be a need for this check and we can ignore. Since it is possible to have a mismatch in other systems I will see if there is a way to inspect the admin socket.

**Comment by travisn** [comment]
Rook will allow running multiple ceph clusters in the same K8s cluster. The point of separation is that they all run in their own k8s namespace. So all the ceph daemon pods running in the same namespace would be expected to have the same fsid.

**Comment by ktdreyer** [comment]
@alfredodeza , looks like a fix went into ceph-medic instead. Should we close this rook ticket now?
