### ISSUE TITLE
Rook should use aggregated roles to improve upgrades

### ISSUE THREAD

**Issue by travisn** [rook/rook#2634]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
During the upgrade between releases of Rook, we have to remove and create new Roles/ClusterRoles whenever there is an RBAC setting that changes, whether rook needs a new privilege or a privilege changes to a new api object, etc. Rook can use [aggregated roles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles) so that only the difference needs to be applied during upgrade instead of completely removing and adding roles with the same names.

**What is use case behind this feature:**
Improved upgrades

**Environment**:

**Comment by BlaineEXE** [comment]
Adding Ceph label so that we can track it easily w/ Ceph tag filter.

**Comment by kshlm** [comment]
Can I get this assigned to me? I'd like to take it up.

**Comment by kshlm** [comment]
I've been looking into this. One thing to note is that aggregated roles are only possible for ClusterRoles. It's pretty simple to add a `aggregationRule` with a specific labels property to the existing ClusterRole definitions. In future releases, to add new rules to a role, a new ClusterRole definitions can be created with correct labels, which will be aggregated with the existing roles.

Is this all that is required? Or is there something specific to the 1.0/1.1 releases to be done here. I believe that this is all, as no previous aggregated roles exist.

I'll be updating at the ceph definitions right now. I'll be creating the labels as 'rbac.ceph.rook.io/aggregate-to-<clusterrole-name>'. Should I also be looking at the other providers?

@travisn

**Comment by travisn** [comment]
@kshlm Yes, sounds great to have these labels added to all of the ClusterRole definitions. This will improve the upgrade guide in future releases. And if it's simple to add to ClusterRole definitions of other providers, makes sense to do it at the same time. Now if only they also applied to Roles instead of only ClusterRoles...
