### ISSUE TITLE
Multiple OSDs per device should only apply to fast device types

### ISSUE THREAD

**Issue by travisn** [rook/rook#2640]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The setting `osdsPerDevice` is only expected to be greater than 1 for fast devices such as NVMe. This setting will currently be applied to all devices at the scope of the setting. This would be much improved if we only applied this setting to fast devices.

```
  storage: # cluster level storage configuration and selection
    config:
      osdsPerDevice: "1" # this value can be overridden at the node or device level
```

The rook discovery pod retrieves properties of devices, which we should be able to use in the operator to decide when to apply this setting to fast devices. These are the properties currently retrieved:
```
  devices: '[{"name":"sdb","parent":"","hasChildren":false,"devLinks":"/dev/disk/by-id/ata-VBOX_HARDDISK_VB815300ba-d9a7e3e1
    /dev/disk/by-path/pci-0000:00:0d.0-ata-3","size":8589934592,"uuid":"1728990c-cd3f-43c8-8154-e4e3b6226600","serial":"VBOX_HARDDISK_VB815300ba-d9a7e3e1","type":"disk","rotational":true,"readOnly":false,"Partitions":null,"filesystem":"","
```

The question is what these properties look like for NVMe so we can reliably apply this behavior.

**What is use case behind this feature:**

**Environment**:

**Comment by AliMD** [comment]
+1

**Comment by leseb** [comment]
Shouldn't this be a property of c-v instead of Rook?
