### ISSUE TITLE
Flex driver permissions errors

### ISSUE THREAD

**Issue by leseb** [rook/rook#2641]
It looks like the RBAC needs to be updated on 1.13. However CSI is coming with 1.13 so perhaps we would let this as is and switch to CSI on 1.13.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

```
2019-02-10 12:42:34.969625 I | operator: rook-provisioner ceph.rook.io/block started using ceph.rook.io flex vendor dir
I0210 12:42:34.972260       7 leaderelection.go:187] attempting to acquire leader lease  rook-ceph-system/ceph.rook.io-block...
2019-02-10 12:42:34.987282 I | operator: rook-provisioner rook.io/block started using rook.io flex vendor dir
2019-02-10 12:42:35.002676 I | op-cluster: start watching clusters in all namespaces
E0210 12:42:34.987358       7 leaderelection.go:252] error retrieving resource lock rook-ceph-system/ceph.rook.io-block: endpoints "ceph.rook.io-block" is forbidden: User "system:serviceaccount:rook-ceph-system:rook-ceph-system" cannot get resource "endpoints" in API group "" in the namespace "rook-ceph-system"
```

**Expected behavior:**

Correct access to ressources.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): minikube
* Kernel (e.g. `uname -a`): `Linux minikube 4.15.0 #1 SMP Fri Jan 18 22:39:33 UTC 2019 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: single VM
* Rook version (use `rook version` inside of a Rook Pod): `rook: v0.9.0-135.g78a3995`
* Kubernetes version:
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Community
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): Ceph

**Comment by lbogdan** [comment]
I've been playing with rook on `1.11.3` for a few days, and everything's seems to be working fine so far.

**Comment by travisn** [comment]
@leseb It looks like you're adding [this line](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L283) in operator.yaml that was added recently in master. Do you not see it in your deployment?

**Comment by leseb** [comment]
Thanks @travisn my `operator.yaml` was missing this.

**Comment by eyinwag** [comment]
@travisn  I meet the same issue, I see that this line is " #       operator: Exists" ? I think that it is not correct, right ? Could you provide which line ?

**Comment by travisn** [comment]
@eyinwag hmm, I shouldn't use links from master since things change... 
Are you using manifests from the release branch? Please use the manifests from the [release branch](https://github.com/rook/rook/tree/release-1.2/cluster/examples/kubernetes/ceph) to avoid issues like this in master.

**Comment by eyinwag** [comment]
Thanks @travisn a lot. Will update our operator.yaml.
