### ISSUE TITLE
Add `s3cmd` into rook-ceph-tools image

### ISSUE THREAD

**Issue by hongkailiu** [rook/rook#2648]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add `s3cmd` into rook-ceph-tools image.

Current workaround:
```
# oc project rook-ceph
# oc rsh rook-ceph-tools-576bd57b66-xr8h8 
sh-4.2# yum install -y s3cmd
sh-4.2# s3cmd --version
s3cmd version 2.0.2
```

**What is use case behind this feature:**
On OCP 4.0, since we usually do not have network access on the jump node (a node where oc-client works) to svc `rook-ceph-rgw-my-store` or pod's (ip and port), eg, `172.30.178.33:8080`, we need to access ceph object storage via the exposed svc via route. I tested it and all works fine.

It would be more convenient if we have `s3cmd` pre-installed on the ceph-tool-box image. It does not depend on a working App sub-domain of the cluster and then routes.

**Environment**:

**Comment by travisn** [comment]
@hongkailiu Until the 0.8 release, rook actually produced a separate image for the toolbox that contained s3cmd. Since 0.9, the toolbox now just uses the same image as the rook operator so we aren't able to add other tools to the image that aren't core to the functionality of rook and ceph. You might consider running a different container for s3cmd instead of the toolbox. Searching dockerhub I see a few containers published that might work.

**Comment by hongkailiu** [comment]
@travisn 
I actually containerized `m3cmd` already.
Just thought it would be more convenient if tool box has it by default.

```
# oc new-project test
# oc create -f https://raw.githubusercontent.com/hongkailiu/svt-case-doc/master/files/dc_mycentos.yaml
```

Thanks for the reply.

Last try, object storage is part of ceph and s3cmd is the client to test its function. :)

**Comment by leseb** [comment]
@hongkailiu FYI this image has s3cmd as well ceph binaries: https://cloud.docker.com/u/ceph/repository/docker/ceph/daemon

**Comment by hongkailiu** [comment]
@leseb thanks for reply.
I got 404 on the link.
BTW, Is the image you pointed out deployable by rook in some way? Or it is some container as part of rook-ceph already? I will look into this today.

**Comment by leseb** [comment]
Oops that was the private link sorry, here is the public view: https://hub.docker.com/r/ceph/daemon
Yes, you can use it in Rook, change your `cluster.yaml` with `ceph/daemon:latest-master` (for Nautilus dev) or `latest-{luminous,mimic}` tag.

**Comment by hongkailiu** [comment]
OK. Thanks. @leseb 
Is it changing the content of [L164](https://github.com/rook/rook/blob/release-0.9/cluster/examples/kubernetes/ceph/cluster.yaml#L164)?
`image: ceph/ceph:v13.2.4-20190109` to eg, `image: ceph/daemon:latest-luminous`?

**Comment by leseb** [comment]
@hongkailiu Yup!
