### ISSUE TITLE
Ceph CSI feature parity: support mon failover

### ISSUE THREAD

**Issue by rootfs** [rook/rook#2649]
**Is this a bug report or feature request?**
feature request

* Feature Request

**What should the feature do:**
Support mon failover. Ceph csi supports embedding mon in Secret. Rook operator can update monitors in the Secret.

**What is use case behind this feature:**

**Environment**:

**Comment by jarrpa** [comment]
I was waiting for https://github.com/rook/rook/pull/2857 to merge before getting started on this Issue. I can probably get started on this early next week.

**Comment by travisn** [comment]
Ok great, we need this for 1.0.
