### ISSUE TITLE
rook toolbox should support performance benchmarking

### ISSUE THREAD

**Issue by bassam** [rook/rook#265]
`rook` cli should should performance benchmarking at the RADOS, file, block and object level. Ideally this would be written in golang natively and use goroutines for concurrency.

**Comment by bassam** [comment]
Repurposing the ticket to rook toolbox.

**Comment by travisn** [comment]
@bassam does this make sense for the toolbox? if you want to benchmark file and block you need to create a pod with pvc, then run the appropriate tools such as `fio`. This seems out of the scope of the toolbox. Seems like we could just provide a yaml with the pvc and document how to run perf tests

**Comment by bassam** [comment]
as long as we can make it easy for folks to benchmark the perf of the cluster, I think this could be an independent pod.
