### ISSUE TITLE
Q: why are 'rook ceph' CLI args hidden?

### ISSUE THREAD

**Issue by leseb** [rook/rook#2663]
In the `rook ceph`CLI, all the flags are hidden, is there any particular reason behind that?
Making flags visible could help curious user who don't want to look at the Cobra code.

**Comment by travisn** [comment]
This dates back to the original version of rook when we had a cmd line tool `rookctl` and we wanted to make it clear that the flags for running daemons weren't intended to be run. But now that we expect users to do everything with kubectl or ceph tools, I'd say it would be fine to show all the args. Only developers would be expected to view them and it would certainly be more convenient.

**Comment by leseb** [comment]
Sounds good let make them visible for developers then :).
