### ISSUE TITLE
Update cluster/examples (Cluster)Roles apiGroups

### ISSUE THREAD

**Issue by copejon** [rook/rook#2666]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
ClusterRoles and Roles under [./cluster/*](https://github.com/rook/rook/tree/master/cluster/examples) should be updated to reflect latest K8s API.  Currently the `apiGroups` is set to `extensions`; should be `apps`.

Attempting to create these resources results in the respective operator failing to start as it cannot create the resources (daemonsets, replicasets, deployments).

**How to reproduce it (minimal and precise):**

Spin up a K8s v1.10+ cluster

`$ minikube start --kubernetes-version=v1.10.0`

Create file with a role defining `daemonset` perms:

`$ kubectl create -f cluster/examples/kubernetes/ceph/operator.yaml`

Examine the failed operator pod.

`$ kubectl describe pod -n rook-ceph-system rook-ceph-operator-SUFFIX`

* Cluster Provider
minikube 
* Rook version (use `rook version` inside of a Rook Pod):
`rook: v0.9.0-161.g5646142`
* Kubernetes version (use `kubectl version`):
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by travisn** [comment]
@copejon I believe this was just completed with #2611. Please reopen if anything was missed.
