### ISSUE TITLE
rook-ceph stuck in Terminating state : unable to delete

### ISSUE THREAD

**Issue by ksingh7** [rook/rook#2668]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```
karasing-OSX-2:~/ocs4.0/rook$ oc get scc | grep -i ceph
rook-ceph          true      []        MustRunAs   RunAsAny           MustRunAs   RunAsAny    <none>     false            [configMap downwardAPI emptyDir flexVolume hostPath persistentVolumeClaim projected secret]
karasing-OSX-2:~/ocs4.0/rook$
```
```
karasing-OSX-2:~/ocs4.0/rook$ oc get ns | grep -i ceph
rook-ceph-system                             Terminating   6d11h
karasing-OSX-2:~/ocs4.0/rook$
```
```
karasing-OSX-2:~/ocs4.0/rook$ oc get all -n rook-ceph-system
No resources found.
karasing-OSX-2:~/ocs4.0/rook$
```
```
karasing-OSX-2:~/ocs4.0/rook$ oc get namespace rook-ceph-system -o json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"name\":\"rook-ceph-system\",\"namespace\":\"\"}}\n",
            "openshift.io/sa.scc.mcs": "s0:c21,c10",
            "openshift.io/sa.scc.supplemental-groups": "1000440000/10000",
            "openshift.io/sa.scc.uid-range": "1000440000/10000"
        },
        "creationTimestamp": "2019-02-09T13:37:33Z",
        "deletionTimestamp": "2019-02-09T14:35:59Z",
        "name": "rook-ceph-system",
        "resourceVersion": "192694",
        "selfLink": "/api/v1/namespaces/rook-ceph-system",
        "uid": "da82f47a-2c6f-11e9-8392-12645b59c006"
    },
    "spec": {
        "finalizers": [
            "kubernetes"  <===== This is the problem
        ]
    },
    "status": {
        "phase": "Terminating"
    }
}
karasing-OSX-2:~/ocs4.0/rook$
```
I have also gone throuth the comments https://github.com/rook/rook/issues/1488#issuecomment-397336663 however i do not have resources to run the patch command

```
karasing-OSX-2:~/ocs4.0/rook$ oc delete ns rook-ceph-system --grace-period=0 --force
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
Error from server (Conflict): Operation cannot be fulfilled on namespaces "rook-ceph-system": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
karasing-OSX-2:~/ocs4.0/rook$
```
```
karasing-OSX-2:~/ocs4.0/rook$ oc get crd | egrep -i "ceph|rook|system"
karasing-OSX-2:~/ocs4.0/rook$
```
**Expected behavior:**

Should be able to delete ``rook-ceph-system`` namespace

**How to reproduce it (minimal and precise):**

- Get OCP 4.0 on AWS
- `` oc create -f scc.yaml``
- `` oc create -f operator.yaml``
-  Try to delete/purge [ without running ``cluster.yaml`` ]

**Environment**:
* OS (e.g. from /etc/os-release): RHCOS
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):  ``rook/ceph:master``
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift 4.0
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by ksingh7** [comment]
Hi @travisn  i tried following your comment  https://github.com/rook/rook/issues/1488#issuecomment-397336663  but i do no have CRD and resources to patch this, so i am unable to delete ``rook-ceph-system`` namespace

**Comment by travisn** [comment]
@ksingh7 Where does the `kubernetes` finalizer come from? Rook doesn't create it. OpenShift must be adding it. As a workaround you should be able to remove the finalizer manually by editing the namespace.

**Comment by ksingh7** [comment]
@travisn  you might be correct. kubernetes finalizer must be added by openshift, but i don't know how it did that. I just ran ``scc.yaml`` and ``operator.yaml`` files and after that i tried to delete the namespace.

Anyways, can you help me how to delete that manually. As of now i tried the following steps

```
oc get ns rook-ceph-system -o json > todelete.json
```
```
karasing-OSX-2:~/ocs4.0/rook$ cat todelete.json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"name\":\"rook-ceph-system\",\"namespace\":\"\"}}\n",
            "openshift.io/sa.scc.mcs": "s0:c21,c10",
            "openshift.io/sa.scc.supplemental-groups": "1000440000/10000",
            "openshift.io/sa.scc.uid-range": "1000440000/10000"
        },
        "creationTimestamp": "2019-02-09T13:37:33Z",
        "deletionTimestamp": "2019-02-09T14:35:59Z",
        "name": "rook-ceph-system",
        "resourceVersion": "192694",
        "selfLink": "/api/v1/namespaces/rook-ceph-system",
        "uid": "da82f47a-2c6f-11e9-8392-12645b59c006"
    },
    "spec": {
        "finalizers": [
            "kubernetes" . <--- Removed this line
        ]
    },
    "status": {
        "phase": "Terminating"
    }
}
karasing-OSX-2:~/ocs4.0/rook$
```
- Removed ``kubernetes`` finalizer
```
karasing-OSX-2:~/ocs4.0/rook$ cat todelete.json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"name\":\"rook-ceph-system\",\"namespace\":\"\"}}\n",
            "openshift.io/sa.scc.mcs": "s0:c21,c10",
            "openshift.io/sa.scc.supplemental-groups": "1000440000/10000",
            "openshift.io/sa.scc.uid-range": "1000440000/10000"
        },
        "creationTimestamp": "2019-02-09T13:37:33Z",
        "deletionTimestamp": "2019-02-09T14:35:59Z",
        "name": "rook-ceph-system",
        "resourceVersion": "192694",
        "selfLink": "/api/v1/namespaces/rook-ceph-system",
        "uid": "da82f47a-2c6f-11e9-8392-12645b59c006"
    },
    "spec": {
        "finalizers": [
        ]
    },
    "status": {
        "phase": "Terminating"
    }
}
```
- Login with system:admin
```
karasing-OSX-2:~/ocs4.0/rook$ oc whoami
system:admin
karasing-OSX-2:~/ocs4.0/rook$
karasing-OSX-2:~/ocs4.0/rook$ curl -k -H "Content-Type: application/json" -X PUT --data-binary @todelete.json https://ocp4-api.ceph-s3.com:6443/api/v1/namespaces/rook-ceph-system/finalize
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "namespaces \"rook-ceph-system\" is forbidden: User \"system:anonymous\" cannot update resource \"namespaces/finalize\" in API group \"\" in the namespace \"rook-ceph-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "rook-ceph-system",
    "kind": "namespaces"
  },
  "code": 403
}
```
```
karasing-OSX-2:~/ocs4.0/rook$ oc get ns | grep -i rook
rook-ceph-system                             Terminating   6d11h
karasing-OSX-2:~/ocs4.0/rook$
```

**Comment by ksingh7** [comment]
BTW i followed this method https://github.com/kubernetes/kubernetes/issues/19317#issuecomment-180003984

**Comment by travisn** [comment]
@ksingh7 You might try the following command, delete the finalizer in the editor, and save your results: `oc edit namespace rook-ceph-system`. But I'm not sure that will help more than what you've already tried.

**Comment by ksingh7** [comment]
I can reproduce this on another OCP 4.0 cluster
- Tried ``oc edit namespace rook-ceph-system`` and deleted the finalizer but it didn't help

Side Note : Since my OCP4.0 is on AWS, to save cost i have powered off my OCP 4.0 instances and today morning i powered them on again. Tried deleting `` oc delete -f operator.yaml `` and it got stuck. I am not sure if this is a combination of stopping the OCP 4.0 cluster OR whatever. 

```
karasing-OSX-2:~/ocp4.0/rook/new$ oc get ns | grep -i ceph
rook-ceph-system                             Terminating   13h
karasing-OSX-2:~/ocp4.0/rook/new$
```

**Comment by hansbogert** [comment]
this gave me a lot of info as to why namespaces weren't automatically removed:

```
kubectl api-resources --verbs=list --namespaced -o name \
  | xargs -n 1 kubectl get --show-kind  --all-namespaces --ignore-not-found -n rook-ceph-system
```

in my case for example, it were the secrets and ingresses which I hadn't cleaned up yet.

**Comment by noahdesu** [comment]
```
[nwatkins@smash kubensis]$ kubectl api-resources --verbs=list --namespaced -o name \
>   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n rook-ceph
NAME                                 DATADIRHOSTPATH   MONCOUNT   AGE    STATE     HEALTH
cephcluster.ceph.rook.io/rook-ceph   /var/lib/rook     1          114m   Created   HEALTH_OK
```

**Comment by noahdesu** [comment]
Updating title: this is still an issue

**Comment by ClareChu** [comment]
kubectl -n rook-ceph patch cephclusters.ceph.rook.io rook-ceph -p '{"metadata":{"finalizers": []}}' --type=merge

**Comment by leseb** [comment]
This usually happens when the operator is deleted before the cluster CR. The doc already has a mention of that: https://rook.io/docs/rook/v1.0/ceph-teardown.html

**Comment by haslersn** [comment]
I experienced this problem many times when deleting a CephCluster CR, always without deleting the operator. I never deleted the operator.

Thus, I think this should be reopened.

**Comment by subhamkrai** [comment]
> I experienced this problem many times when deleting a CephCluster CR, always without deleting the operator. I never deleted the operator.
> 
> Thus, I think this should be reopened.

Please see https://rook.io/docs/rook/v1.0/ceph-teardown.html

**Comment by davesargrad** [comment]
This is also a problem for me. I think this should be reopened.

I was able to cleanly stand up a ceph cluster. However I followed the rip down procedures, and I see several resources hanging.

**Comment by divad1196** [comment]
Hi,

I am facing relatively the same issue:
I only have a CephBlockPool resource left and the namespace in terminating.
![image](https://user-images.githubusercontent.com/43037556/139542402-acd26b94-377f-4392-9edf-2962d8930062.png)

I tried to delete the CRD, the replicapool and the namespace, but they all keep hanging forever.
I don't have a /var/lib/rook folder and all solutions I found doesn't work even if i wait for more than 1h.

Here are the commands I am being stuck on:
```bash
kubectl delete -n rook-ceph cephblockpools.ceph.rook.io replicapool
kubectl delete customresourcedefinitions.apiextensions.k8s.io cephblockpools.ceph.rook.io
kubectl delete ns rook-ceph
```

I followed:
* For [install](https://rook.io/docs/rook/v1.7/quickstart.html#tldr)
* For [uninstall](https://rook.io/docs/rook/v0.8/ceph-teardown.html), except i manually deleted some resources manually before doing it.

Versions: 
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:44:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

```

I even tried to enter etcd pod to delete some data as explain in a page i can not find anymore.
Is there something more i can try?

Thank you for your response

**Comment by vyom-soft** [comment]
> this gave me a lot of info as to why namespaces weren't automatically removed:
> 
> ```
> kubectl api-resources --verbs=list --namespaced -o name \
>   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n rook-ceph-system
> ```
> 
> in my case for example, it were the secrets and ingresses which I hadn't cleaned up yet.

Still I cannot delete those. It just hangs.
