### ISSUE TITLE
Operator refuses to start after k8s node restart

### ISSUE THREAD

**Issue by hansbogert** [rook/rook#2669]
* Bug Report
After restarting a k8s node, the operator was restarted, but crashes, as can be seen by `kubectl get --all-namespaces pods`

**Deviation from expected behavior:**
Operator crashes. Operator show the following log:

```
kubectl logs -n rook-ceph-system rook-ceph-operator-789c78f6d-pkstz                                                                
2019-02-18 07:40:30.539453 I | rookcmd: starting Rook v0.9.2 with arguments '/usr/local/bin/rook ceph operator'
2019-02-18 07:40:30.539575 I | rookcmd: flag values: --alsologtostderr=false, --help=false, --log-level=INFO, --log_backtrace_at=:0, --log_dir=, --logtostderr=true, --mon-healthcheck-interval=45s, --mon-out-timeout=5m0s, --stderrthreshold=2, --v=0, --vmodule=
2019-02-18 07:40:30.573556 I | cephcmd: starting operator
failed to get pod. Get https://10.152.183.1:443/api/v1/namespaces/rook-ceph-system/pods/rook-ceph-operator-789c78f6d-pkstz: x509: certificate is valid for 192.168.1.185, 192.168.1.185, not 10.152.183.1
```

Problem seems to be that the operator suddenly uses the wrong IP to address the k8s master, to my knowledge, I haven't changed anything regarding IPs and such. The certificate seems correct, since the master is indeed reachable by the address `192.168.1.185`

**Expected behavior:**
Operator should restart even if  the node it was scheduled on reboots.

**How to reproduce it (minimal and precise):**
Unsure how I got in this state. Reproducing in the current *state* is easy, it continually errors, even when k8s restarts the operator

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
4.4
* Cloud provider or hardware configuration:
home lab with Ubuntu Maas - juju - Charmed Distribution of Kubernetes running on old office PCs with plain old sata disks.
* Rook version (use `rook version` inside of a Rook Pod):
0.9.2
* Kubernetes version (use `kubectl version`):
1.13
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
CDK
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
WARN, since the master was also running an OSD, which needs to be restarted, other than that, it should be healthy:

```
[root@node2 /]#  ceph status
  cluster:
    id:     977dfaff-9a9a-4ba8-8e3f-372504834af3
    health: HEALTH_WARN
            Reduced data availability: 60 pgs stale
 
  services:
    mon: 3 daemons, quorum b,a,c
    mgr: a(active)
    osd: 4 osds: 3 up, 3 in
 
  data:
    pools:   1 pools, 200 pgs
    objects: 53.25 k objects, 208 MiB
    usage:   5.4 GiB used, 3.6 TiB / 3.6 TiB avail
    pgs:     140 active+clean
             60  stale+active+clean
 

```

**Comment by travisn** [comment]
@hansbogert I would suspect there is some issue with the kubelet configuration if the pod isn't started with the correct info for the operator pod to contact the api server.

**Comment by hansbogert** [comment]
Seems it's a more fundamental problem with my cluster indeed and the error is just a symptom. Sorry for the noise.
