### ISSUE TITLE
Edgefs : error: unable to recognize "cluster.yaml": no matches for kind "PodSecurityPolicy" in version "apps/v1"

### ISSUE THREAD

**Issue by maurya-m** [rook/rook#2681]
Getting this error when running on K8s cluster with ssd volumes attached. 
kubectl apply -f cluster.yaml 

**error: unable to recognize "cluster.yaml": no matches for kind "PodSecurityPolicy" in version "apps/v1"**

Contents of cluster.yaml 

apiVersion: v1
kind: Namespace
metadata:
  name: rook-edgefs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs
rules:
- apiGroups: [""]
  resources: ["configmaps", "endpoints"]
  verbs: [ "get", "list", "watch", "create", "update", "delete" ]
- apiGroups: ["edgefs.rook.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: [ "get", "list" ]
---
# Allow the operator to create resources in this cluster's namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster-mgmt
  namespace: rook-edgefs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-edgefs-cluster-mgmt
subjects:
- kind: ServiceAccount
  name: rook-edgefs-system
  namespace: rook-edgefs-system
---
# Allow the pods in this namespace to work with configmaps
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-edgefs-cluster
  namespace: rook-edgefs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-edgefs-cluster
subjects:
- kind: ServiceAccount
  name: rook-edgefs-cluster
  namespace: rook-edgefs
---  
apiVersion: apps/v1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
  hostPID: true
  hostIPC: true
  hostNetwork: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privileged-psp-user
rules:
- apiGroups:
  - apps
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-edgefs-system-psp
  namespace: rook-edgefs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user
subjects:
- kind: ServiceAccount
  name: rook-edgefs-system
  namespace: rook-edgefs-system
---
apiVersion: edgefs.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-edgefs
  namespace: rook-edgefs
spec:
  edgefsImageName: edgefs/edgefs:latest   # specify version here, i.e. edgefs/edgefs:1.0.0 etc
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /var/lib/edgefs
  #dataVolumeSize: 10Gi
  #devicesResurrectMode: "restoreZapWait"
  #dashboard:
  #  localAddr: 10.3.30.75
  #network: # cluster level networking configuration aka "host network"
  #  serverIfName: "enp2s0f0"
  #  brokerIfName: "enp2s0f0"
  #skipHostPrepare: false
  storage: # cluster level storage configuration and selection
    useAllNodes: true
  #  directories:
  #  - path: /mnt/disks/ssd0
  #  - path: /mnt/disks/ssd1
  #  - path: /mnt/disks/ssd2
    useAllDevices: true
    config:
  #    rtVerifyChid: "0"           # may improve CPU utilization
  #    lmdbPageSize: "32768"       # larger value can improve stream operations, Acceptable values are 4096, 8192, 16384 and 32768.
      useMetadataOffload: "true"  # enable use of SSD device as metadata offload
  #    useBCache: "true"           # enable SSD cache device and read-cache
  #    useBCacheWB: "true"         # enable SSD write-cache
      useMetadataMask: "0xff"     # all metadata on SSD
  #    rtrdPLevelOverride: "4"     # enable large device partitioning, only needed if automatic not working
  #    sync: "0"                   # highest performance, consistent on pod/software failures, not-consistent on power failures
      useAllSSD: "true"           # use only SSDs during deployment
  #  nodes:
  #  - name: node3071ub16
  #  - name: node3072ub16
  #  - name: node3073ub16
  #  - name: node3074ub16 # node level storage configuration
  #    devices: # specific devices to use for storage can be specified for each node
  #    - name: "sdb"
  #    - name: "sdc"
  #    config: # configuration can be specified at the node level which overrides the cluster level config
  #      rtrdPLevelOverride: 8
  #resources:
  #  limits:
  #    cpu: "2"
  #    memory: "4096Mi"
  #  requests:
  #    cpu: "2"
  #    memory: "4096Mi"

**Comment by dyusupov** [comment]
thanks. meanwhile, change line 58 in cluster.yaml to namespace policy/v1beta1

**Comment by maurya-m** [comment]
@dyusupov thanks for responding back, do i need to re-intialize the efscli system init, also i am not able to the run "efscli cluster create cltest", where can i check for the logs?

**Comment by dyusupov** [comment]
> @dyusupov thanks for responding back, do i need to re-intialize the efscli system init, also i am not able to the run "efscli cluster create cltest", where can i check for the logs?

If you cannot do cluster I/O you'll likely need to review if networking.
There are 2 types of logs you can look at:

target level logs of the daemon that handles VDEVs:

kubectl logs -n rook-edgefs rook-edgefs-target-0 -c daemon

and client level logs which can be viewed by exporting some environment variables:

export CCOW_LOG_STDOUT=1
export CCOW_LOG_LEVEL=3
export CCOW_LOG_COLORS=1

and then running efscli command again.

**Comment by maurya-m** [comment]
Output of kubectl logs -n rook-edgefs rook-edgefs-target-0 -c daemon ( too long) so here is the last few lines:

Feb 21 10:02:40.499 rook-edgefs-target-0 ccowd[1] error   [2880] putcommon_client.c:2072 : failing I/O 0x7f7e9c86d658 type 3 error -5: status 0
Feb 21 10:02:40.499 rook-edgefs-target-0 ccowd[1] error   [2880]         ccow.c:3848 : failing I/O 0x7f7e9c86d550 (CCOW_PUT) error -5
Feb 21 10:02:40.499 rook-edgefs-target-0 ccowd[1] error   [2880]     btreecom.c:188  : failing I/O 0x7f7e9c86d448 type 3 error -5: status -5
Feb 21 10:02:40.499 rook-edgefs-target-0 ccowd[1] error   [62]        trput.c:1227 : Failed to update write marker for shard.leader.
Feb 21 10:02:47.903 rook-edgefs-target-0 ccowd[1] error   [27]        trput.c:831  : Cluster lookup error -2

**Comment by maurya-m** [comment]
Also here are the logs after export the log levels:

λ kubectl exec -it -n rook-edgefs rook-edgefs-target-0 -c daemon -- env COLUMNS=$COLUMNS LINES=$LINES TERM=linux toolbox

Welcome to EdgeFS Toolbox.
Hint: type efscli to begin

root@rook-edgefs-target-0:/opt/nedge# export CCOW_LOG_STDOUT=1
root@rook-edgefs-target-0:/opt/nedge# export CCOW_LOG_LEVEL=3
root@rook-edgefs-target-0:/opt/nedge# export CCOW_LOG_COLORS=1
root@rook-edgefs-target-0:/opt/nedge# efscli cluster create cltest
Feb 21 10:12:57.805 rook-edgefs-target-0 ccow[14204] info    [14204]         util.c:733  : Loading /opt/nedge//lib/libblake2_avx2.so
Feb 21 10:12:57.817 rook-edgefs-target-0 ccow[14204] info    [14210]         ccow.c:1597 : CCOW library main loop started
Feb 21 10:12:57.821 rook-edgefs-target-0 ccow[14204] info    [14210]         ccow.c:1631 : CCOW library main loop priority set to 99
Feb 21 10:12:57.821 rook-edgefs-target-0 ccow[14204] info    [14210]         ccow.c:1659 : tc 0x7f5943c00000 now elected as proc master on start
Feb 21 10:12:57.821 rook-edgefs-target-0 ccow[14204] info    [14210]         ccow.c:5960 : Creating tenant ucache size of 4096
Feb 21 10:12:57.821 rook-edgefs-target-0 ccow[14204] info    [14210]         ccow.c:5992 : Total ram memory on the server: 33256280064
Feb 21 10:12:57.821 rook-edgefs-target-0 ccow[14204] info    [14210]         ccow.c:6003 : Tenant ucache memory limits: 24942210048/0
Feb 21 10:12:57.821 rook-edgefs-target-0 ccow[14204] info    [14210]      cmcache.c:136  : Creating tenant cmcache hash size of 16384
Feb 21 10:12:57.821 rook-edgefs-target-0 ccow[14204] info    [14210]      network.c:312  : Using interface eth0 <fe80::1832:99ff:fe62:f8cd%eth0>, 10000 Mbps
Feb 21 10:12:57.821 rook-edgefs-target-0 ccow[14204] info    [14210]    replicast.c:3376 : Replicast(client-0) listens on UDP 100.97.213.131.50005, origin 100.97.213.131, scope_id=0
Feb 21 10:12:57.825 rook-edgefs-target-0 ccow[14204] info    [14204]     flexhash.c:1003 : Flexhash created. genid: 1 numdevices: 9  numrows: 8 hashmask: 0x7
Feb 21 10:12:57.825 rook-edgefs-target-0 ccow[14204] info    [14204]  server-list.c:485  : fetching latest FlexHash
Feb 21 10:12:57.825 rook-edgefs-target-0 ccow[14204] info    [14210]  server-list.c:159  : RT_SERVER_LIST_RESPONSE mcbase_addr ::ffff:ffff:0:ea.10399
Feb 21 10:12:57.825 rook-edgefs-target-0 ccow[14204] info    [14210]  server-list.c:168  : RT_SERVER_LIST_RESPONSE with missing parent_serverid = 00000000000000000000000000000000 fh_genid = 1550684883762839
Feb 21 10:12:57.825 rook-edgefs-target-0 ccow[14204] info    [14210]     flexhash.c:1003 : Flexhash created. genid: 1 numdevices: 2  numrows: 8 hashmask: 0x7
Feb 21 10:12:57.825 rook-edgefs-target-0 ccow[14204] info    [14210]  server-list.c:209  : Flexhash genid: 1550684883762839 actual numdevices: 2
Feb 21 10:12:57.825 rook-edgefs-target-0 ccow[14204] info    [14210]  server-list.c:210  : Flags 0 ckpread 1 msg 1
Feb 21 10:12:58.677 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 1 attempts seq id: 4.1
Feb 21 10:12:59.525 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 2 attempts seq id: 4.2
Feb 21 10:13:00.377 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 3 attempts seq id: 4.3
Feb 21 10:13:01.225 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 4 attempts seq id: 4.4
Feb 21 10:13:02.925 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 5 attempts seq id: 4.5
Feb 21 10:13:04.625 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 6 attempts seq id: 4.6
Feb 21 10:13:06.325 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 7 attempts seq id: 4.7
Feb 21 10:13:08.025 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 8 attempts seq id: 4.8
Feb 21 10:13:10.577 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 9 attempts seq id: 4.9
Feb 21 10:13:13.124 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 10 attempts seq id: 4.10
Feb 21 10:13:15.676 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 11 attempts seq id: 4.11
Feb 21 10:13:18.224 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 12 attempts seq id: 4.12
Feb 21 10:13:20.776 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 13 attempts seq id: 4.13
Feb 21 10:13:23.324 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 14 attempts seq id: 4.14
Feb 21 10:13:25.876 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 15 attempts seq id: 4.15
Feb 21 10:13:28.424 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 16 attempts seq id: 4.16
Feb 21 10:13:31.424 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 17 attempts seq id: 4.17
Feb 21 10:13:34.424 rook-edgefs-target-0 ccow[14204] warning [14210] putcommon_client.c:2064 : PUT PROPOSAL request timeout after 18 attempts seq id: 4.18

**Comment by maurya-m** [comment]
@dyusupov , having a 1master +3 worker nodes (100GB SSD provisioned ) and then ran the operator.yaml & cluster.yaml scripts.

**Comment by maurya-m** [comment]
some more logs when it timeout 

Feb 21 10:22:40.422 rook-edgefs-target-0 ccow[14204] error   [14210] putcommon_client.c:2070 : PUT PROPOSAL request timed out after 200 attempts seq id: 4.200. Failing 
I/O                                                                                                                                                                     
Feb 21 10:22:40.422 rook-edgefs-target-0 ccow[14204] error   [14210]         ccow.c:497  : Affected OID: cltest///, hashmask=7                                          
Feb 21 10:22:40.422 rook-edgefs-target-0 ccow[14204] error   [14210]         ccow.c:498  : Affected NHID: 81CCE6FDB970FF7444AA1868614A49DD5A597E9FBF301FB8CA7CACC90DC1E6
D50000000000000000000000000000000000000000000000000000000000000000 ROW: 4                                                                                               
Feb 21 10:22:40.422 rook-edgefs-target-0 ccow[14204] error   [14210]         ccow.c:502  : Affected CHID: B466B086A0B43E669D2F624A3B144273DF738CA488BAE1246BCBE47A7CB2B3
E00000000000000000000000000000000000000000000000000000000000000000 ROW: 6                                                                                               
Feb 21 10:22:40.422 rook-edgefs-target-0 ccow[14204] error   [14210] putcommon_client.c:2072 : failing I/O 0x7f5943c3b408 type 3 error -5: status 0                     
Feb 21 10:22:40.526 rook-edgefs-target-0 ccow[14204] info    [14210]         ccow.c:1811 : CCOW library main loop terminated                                            
Feb 21 10:22:40.574 rook-edgefs-target-0 ccow[14204] info    [14204]         util.c:705  : Unloading crypto library, err: 0                                             
Cluster create err=-5

**Comment by dyusupov** [comment]
OK. I think you'll need to wait for https://github.com/rook/rook/pull/2685 merged into the master. Then rebuild the setup using master operator. Do not forget to cleanup dataDirHostPath on all the target hosts!

Prior to re-running `efscli system init` make sure that `efscli system status -v1` looks sane.

**Comment by maurya-m** [comment]
@dyusupov , ok, when do think this merge will come into master? will re-test once you can confirm , will close thereafter.

**Comment by galexrt** [comment]
@dyusupov @maurya-m #2685 was merged. Could you please test again with current `master` and verify if the change fixes your issue.

**Comment by dyusupov** [comment]
this issue no longer can be reproduced with the latest operator in master. closing it tentatively.
