### ISSUE TITLE
Unexpected number of osd pods in a ceph cluster

### ISSUE THREAD

**Issue by adtrytech** [rook/rook#2689]
**Is this a bug report or feature request?**
* Bug Report
**Deviation from expected behavior:**
There are two nodes in the ceph cluster, one has two HDD devices and the other has one HDD. (All HDDs are empty, no partition)
After creating the ceph cluster by using "kubectl create -f cluster.yaml" (cluster.yaml is the default YAML file within the code base, and I modified the "useAllDevices: true"), there are only two osd pods.

**Expected behavior:**
After creating the ceph cluster, there should be 3 osd pods.

**How to reproduce it (minimal and precise):**

The "operator.yaml" and "cluster.yaml" are got from code base and only modified the "cluster.yaml" with "useAllDevices: true"
kubectl create -f operator.yaml
kubectl create -f cluster.yaml

**Environment**:
* OS (e.g. from /etc/os-release): "CentOS Linux 7 (Core)"
* Kernel (e.g. `uname -a`): Linux 8310-n1 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: 
Kubernetes cluster with three nodes.
node A=> master
node B=> ceph cluster with two HDD devices
node C=> ceph cluster with one HDD device
* Rook version (use `rook version` inside of a Rook Pod): rook-0.9.2
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
pure Centos servers, not VM
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by travisn** [comment]
@adtrytech Is it possible a device had a partition or formatted filesystem? In that case, rook will skip creating osds on those devices. Can you share the logs for the osd prepare pod on each of the two nodes? They would indicate what is happening. Towards the top of those logs, there should be messages about whether the devices were used for osds or whether they were skipped.

**Comment by adtrytech** [comment]
Hi travisn,

Thanks for your response. Provide some logs for your reference.
The HDD devices are all empty and no partitions. FYI. 
There are sdb and sdc attach to 8310-n2(ceph cluster node 1) and sdb attach to 8310-n3(ceph cluster node 2)


The pod information of ceph cluster:
kubectl -n rook-ceph get pod -o wide
NAME                                  READY   STATUS      RESTARTS   AGE     IP             NODE      NOMINATED NODE   READINESS GATES
rook-ceph-mgr-a-5c8797779d-ddtsp      1/1     Running     0          4m51s   10.244.1.223   8310-n2   <none>           <none>
rook-ceph-mon-a-dd67b6f98-5vzm9       1/1     Running     0          5m32s   10.244.1.221   8310-n2   <none>           <none>
rook-ceph-mon-b-65d9bd588c-kjtl4      1/1     Running     0          5m21s   10.244.2.119   8310-n3   <none>           <none>
rook-ceph-mon-c-77fc955675-4hzzq      1/1     Running     0          5m9s    10.244.1.222   8310-n2   <none>           <none>
rook-ceph-osd-0-6fdf4ff9fd-67tqz      1/1     Running     0          4m29s   10.244.1.225   8310-n2   <none>           <none>
rook-ceph-osd-1-5fd8c7f4f7-zg42n      1/1     Running     0          4m26s   10.244.2.121   8310-n3   <none>           <none>
rook-ceph-osd-prepare-8310-n2-mj67w   0/2     Completed   0          4m34s   10.244.1.224   8310-n2   <none>           <none>
rook-ceph-osd-prepare-8310-n3-52k26   0/2     Completed   0          4m33s   10.244.2.120   8310-n3   <none>           <none>

The logs of these two prepare pods:
kubectl -n rook-ceph logs rook-ceph-osd-prepare-8310-n2-mj67w
Error from server (BadRequest): a container name must be specified for pod rook-ceph-osd-prepare-8310-n2-mj67w, choose one of: [copy-bins provision]

kubectl -n rook-ceph logs rook-ceph-osd-prepare-8310-n3-52k26
Error from server (BadRequest): a container name must be specified for pod rook-ceph-osd-prepare-8310-n3-52k26, choose one of: [copy-bins provision]

**Comment by adtrytech** [comment]
Hi travisn,

Thanks for your help and I already let the OSD setup completely after using the "sgdisk --zap-all /dev/sdb" to clear backup GTP tables.

Regards
