### ISSUE TITLE
after creating ceph object store, cluster doesn't any effect

### ISSUE THREAD

**Issue by fisherwei** [rook/rook#2694]
I ran `kubectl create -f object.yaml` by example settings, but there is not new pod in cluster.

block storage is working fine.

how to troubleshooting or where can I find error log?

BTW:
I upgraded rook from master to 0.9.2 by `kubectl replace -f operator.yaml` and `cluster.yaml`.
before upgrading, object store is working fine.

**Comment by travisn** [comment]
@fisherwei Can you clarify the repro of this issue? You had the object store working ok, and then you changed the build from master to 0.9.2? This is actually a downgrade and not officially supported, although in this case I'm not sure that's related to your issue.

You might try restarting the operator pod to see if the object store is created again.

**Comment by fisherwei** [comment]
> @fisherwei Can you clarify the repro of this issue? You had the object store working ok, and then you changed the build from master to 0.9.2? This is actually a downgrade and not officially supported, although in this case I'm not sure that's related to your issue.
> 
> You might try restarting the operator pod to see if the object store is created again.

emmm, back to master, resolved.

but master version has another issue, i teardowned and recreate by 0.9.2, all problem resolved. :)
