### ISSUE TITLE
Include ceph-csi in the rook image

### ISSUE THREAD

**Issue by travisn** [rook/rook#2699]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Today ceph-csi is built into two separate images for rbd and cephfs, each containing their own build of the ceph-csi go binary. The docker images are almost the same as well, with only a couple packages different for cephfs and rbd. Do we really need these separate images when integrated with rook? I'm thinking it would simplify things to fully build it into rook. The test matrix would be simplified since we would have a consistent version of ceph-csi for a given version of rook, and there would be fewer images to manage with rook.

It seems straight-forward and desirable to take a source level dependency on ceph-csi. 
- ceph-csi would be built into rook's go binary. It would effectively be a Gopkg.toml dependency.
   - When updates are made to ceph-csi, rook would pick them up when a dev updates the go dependency version.
- The `rook/ceph` image would add packages that are needed for the csi drivers. It looks like these packages would be needed: `ceph-fuse`, `attr`, and `rbd-nbd`

@rootfs @humblec what are your thoughts?

**Comment by rootfs** [comment]
This is really good. It should be way to go. To make this happen, ceph-csi will have its own releases for Rook's Gopkg.toml to reference.

**Comment by humblec** [comment]
I do second this thought. The maintenance and dependency management becomes easy from rook pov. More or less, as we moving towards `csi` as the provisioner and mounter for rook ceph, this is a good thought.  The only overhead here is, when ceph cluster upgrade is performed by rook, it has to think about csi driver upgrade as well or iow, csi driver upgrade should be handled by rook.

**Comment by phlogistonjohn** [comment]
Maybe I'm not very informed about this subject but this strikes me as rather strange. Especially `ceph-csi would be built into rook's go binary.`
It seems to me that this would actually multiply the number of things that need to get tested and tracked by users.

Trying on my imaginary admin hat for a moment I don't think I'd like not knowing whether the ceph-csi I was using came from version X or version Y depending on whether I was trying to use it standalone or via rook. I'd rather simply have rook deploy known images (releases) of the csi component. This is especially true if the projects don't release in lockstep.

Please feel free to convince me that this would really be better.
(CC: @obnoxxx)

**Comment by jarrpa** [comment]
I'm also of the mind that we shouldn't be just bundling all the binaries into one single container image. It feels dirty. I second John's idea to just have Rook deploy and manage independent releases of the CSI driver.

**Comment by raghavendra-talur** [comment]
It would certainly be very tempting to merge the operator, provisioner and mounter code into one binary. As a developer it would simplify the workflow. 

As an admin, however, it would be very restrictive. An admin would want the following options:

- Ability to provision and mount volumes from manually deployed Ceph.
- Ability to check the version of ceph-csi independent of rook version.
- Ability to upgrade the operator more often than ceph-csi, considering that most of the improvements to come might be in operator land for next few releases. Being forced to update ceph-csi images(on every node) when trying to update only rook would make planning for updates more complex.

To come back to developer role, I would certainly want a coordination mechanism between rook and ceph-csi.

- Rook might have to send/get signals from ceph-csi in case of complex upgrades; if it wants mounts to behave a certain way for the duration of upgrade.
- Rook might want to have a monitor for ceph-csi if it wants to intelligently do load balance etc in future.

None of the developer requirements above call for them to exist is same binary though. The requirement would be more of an API.

**Comment by travisn** [comment]
One question that would answer it definitely is if we need the ability to support different versions of the CSI driver depending on K8s version. For example, if ceph-csi:v1.0 is needed when running on k8s 1.13, and in the future csi:v1.1 would be necessary to run on 1.14, Rook would need to deploy different versions of the csi driver. If Rook were to include the csi driver in its package, we wouldn't have that option. While we don't know the future, do we foresee this as a possibility with CSI? This does seem like a valid concern to me as well.

For Rook 1.0 the flex and csi drivers will both be available. Even if we do decide to make this packaging change, I'd suggest we not make this change in the 1.0 time. But we need to finalize this by the next release when flex is likely to be deprecated. 

Separately, I'd recommend we at least combine the rbd and cephfs drivers into the same image. They are built and released together and have 99.9% of the same content in the images, so it would really help with the image management to combine them.

**Comment by phlogistonjohn** [comment]
> One question that would answer it definitively is if we need the ability to support different versions of the CSI driver depending on K8s version. For example, if ceph-csi:v1.0 is needed when running on k8s 1.13, and in the future csi:v1.1 would be necessary to run on 1.14, Rook would need to deploy different versions of the csi driver. If Rook were to include the csi driver in its package, we wouldn't have that option. While we don't know the future, do we foresee this as a possibility with CSI? This does seem like a valid concern to me as well.
> 

I agree. While it does seem that the CSI spec has solidified recently I personally think it's a enough of a concern that we don't over-couple these components.

> For Rook 1.0 the flex and csi drivers will both be available. Even if we do decide to make this packaging change, I'd suggest we not make this change in the 1.0 time. But we need to finalize this by the next release when flex is likely to be deprecated.
> 

Agreed.

> Separately, I'd recommend we at least combine the rbd and cephfs drivers into the same image. They are built and released together and have 99.9% of the same content in the images, so it would really help with the image management to combine them.

That seems quite reasonable to me. The code is shared to a large degree and the roles they play are conceptually similar from a k8s viewpoint. While what they request from the ceph side isn't exactly the same that's more of an implementation detail from the k8s administrator POV (imo).

**Comment by rootfs** [comment]
I believe the goal is to allow Rook to deploy and run CSI drivers, and protect Rook from breaking changes in ceph-csi.  

Currently Rook deploys ceph-csi through templates, admin can fine tune those templates and ceph-csi images to stay away from any potential breaking changes in ceph-csi. However, with more integration underway, we'll have to expose more details to Rook, e.g.:

- In #2729, the new Rook provisioner resolves Rook's SC parameters and passes to ceph-csi provisioner. If changes are made to ceph-csi provisioners, such contract is broken.
- mon failover. Previously I attempted to use ceph-csi's `MonValueFromSecret` param to allow mons embeded in a Secret to allow Rook update mons on when failover occurs. This adds another dependency.

If Rook and ceph-csi binaries are released separately, we'll have the most updated features of both projects but admins have to be aware if the interfacing dependency between Rook and ceph-csi images are compatible. There is risk there.

On the other hand, if Rook and ceph-csi binaries are released in the same container image, though admins are not free to choose the drivers, they are not exposed to compatibility risks as well.

**Comment by travisn** [comment]
Current approach is to have the CSI image version separately rather than including everything in the same image. Will go ahead and leave this issue closed.
