### ISSUE TITLE
shasum required for development build but make will run without

### ISSUE THREAD

**Issue by colonwq** [rook/rook#2713]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Make will attempt to build containers if the shasum command output is not available. This will result in some build parameters being incorrect. Example: BUILD_ROOT will be set to "build-" if shasum is not available in build/common.sh

shasum does not seem to be installed by default on fedora 29

**Expected behavior:**
Make should exit the build if a required build condition is not met

**How to reproduce it (minimal and precise):**

- install git and golang
- clone the Rook repo
- cd rook
- run make

**Environment**:
* OS (e.g. from /etc/os-release):
cat /etc/os-release 
NAME=Fedora
VERSION="29 (Server Edition)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server

* Kernel (e.g. `uname -a`):
Linux kube-master 4.20.4-200.fc29.x86_64 #1 SMP Wed Jan 23 16:11:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
libvirt
* Rook version (use `rook version` inside of a Rook Pod):
current from the repo
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
not deployed yet
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
not deployed

**Comment by galexrt** [comment]
@colonwq Would you be up to provide a PR with a fix for this issue?
