### ISSUE TITLE
pgs inactive after long network outage

### ISSUE THREAD

**Issue by apacoco9861** [rook/rook#2718]
**Is this a bug report or feature request?**
* Bug Report
Yes

**Deviation from expected behavior:**
All OSD up, but some PG in unknown state.

**Expected behavior:**
OSD up and PG in active+clean state

**How to reproduce it (minimal and precise):**

After long network and power outage, our test environment rook-ceph cluster osd has 3 outage osd.1 osd.2, osd.3 and mon.b out of 5 osd.

Tried, firstly, to removed osd.1, osd.2, osd.3 from crushmap (already mark out, down, del auth, etc.), delete operator pod and kubeadm to reset relevent nodes, rejoin cluster, remove mon.b (because mon.b out of quorum after outage, causing rook-ceph deployment of osd.1, osd.2, osd.3 failed) not work. 97 unknown pgs persists. Found that re-created osd.1,2,3 do not have any pg creation.

![cephosdstatus](https://user-images.githubusercontent.com/5441738/53392093-5943a980-39d3-11e9-9758-202b54fed362.PNG)

Tried, secondly, to removed osd.1, osd.2, osd.3 from crushmap (already mark out, down, del auth, etc.), re-create OSD, drained node, delete /var/lib/rook and uncordon. all nodes join back k8s cluster. All osd.1,2,3 nodes /var/lib/rook directories recreated. But operator logs show
2019-02-26 06:32:54.868370 W | op-osd: waiting for the osd.3 to exceed the grace period
2019-02-26 06:33:55.269216 I | op-osd: osd.1 is marked 'DOWN'
2019-02-26 06:33:55.269252 W | op-osd: waiting for the osd.1 to exceed the grace period
2019-02-26 06:33:55.269261 I | op-osd: osd.2 is marked 'DOWN'
2019-02-26 06:33:55.269267 W | op-osd: waiting for the osd.2 to exceed the grace period
2019-02-26 06:33:55.269274 I | op-osd: osd.3 is marked 'DOWN'
2019-02-26 06:33:55.269280 W | op-osd: waiting for the osd.3 to exceed the grace period

one of the agent log show
2019-02-26 06:33:32.381974 I | exec: Timeout waiting for process rbd to return. Sending interrupt signal to the process
2019-02-26 06:33:32.383593 E | flexdriver: Attach volume replicapool/pvc-e622f6f8-2f71-11e9-a6ff-005056b277b2 failed: failed to attach volume replicapool/pvc-e622f6f8-2f71-11e9-a6ff-005056b277b2: failed to map image replicapool/pvc-e622f6f8-2f71-11e9-a6ff-005056b277b2 cluster rook-ceph. failed to map image replicapool/pvc-e622f6f8-2f71-11e9-a6ff-005056b277b2: Failed to complete 'rbd': signal: interrupt. . output:

Now the status is
[root@tst-docker-201-6 /]# ceph osd status
+----+------------------+-------+-------+--------+---------+--------+---------+----------------+
| id |       host       |  used | avail | wr ops | wr data | rd ops | rd data |     state      |
+----+------------------+-------+-------+--------+---------+--------+---------+----------------+
| 0  | tst-docker-201-6 | 31.9G |  455G |    0   |     0   |    0   |     0   |   exists,up    |
| 1  | tst-docker-201-7 | 28.6G |  458G |    0   |     0   |    0   |     0   | autoout,exists |
| 2  | tst-docker-201-4 | 28.9G |  458G |    0   |     0   |    0   |     0   | autoout,exists |
| 3  | tst-docker-201-3 | 28.5G |  458G |    0   |     0   |    0   |     0   |     exists     |
| 4  | tst-docker-201-5 | 27.8G |  459G |    0   |     0   |    0   |     0   |   exists,up    |
+----+------------------+-------+-------+--------+---------+--------+---------+----------------+

Any idea how to recover from this state?

Many thanks,

Paco

**Environment**:
* OS (e.g. from /etc/os-release):
[root@tst-docker-201-6 /]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (e.g. `uname -a`):
Linux tst-docker-201-6 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
 rook: v0.9.0-79.g1a1ffdd

* Kubernetes version (use `kubectl version`): 1.13.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
[root@tst-docker-201-6 /]# ceph health detail
HEALTH_WARN 3 osds down; 3 hosts (3 osds) down; Reduced data availability: 97 pgs inactive
OSD_DOWN 3 osds down
    osd.1 (root=default,host=tst-docker-201-7) is down
    osd.2 (root=default,host=tst-docker-201-4) is down
    osd.3 (root=default,host=tst-docker-201-3) is down
OSD_HOST_DOWN 3 hosts (3 osds) down
    host tst-docker-201-7 (root=default) (1 osds) is down
    host tst-docker-201-4 (root=default) (1 osds) is down
    host tst-docker-201-3 (root=default) (1 osds) is down
PG_AVAILABILITY Reduced data availability: 97 pgs inactive
    pg 1.8 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.16 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.17 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.18 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.1b is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.1c is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.1d is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.1e is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.1f is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.21 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.22 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.25 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.27 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.28 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.29 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.2a is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.2c is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.2d is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.61 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.62 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.64 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.66 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.67 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.68 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.69 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.6a is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.6b is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.6c is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.6d is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.6f is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.70 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.72 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.73 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.74 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.75 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.76 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.78 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.7a is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.7b is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.7d is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.7e is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.80 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.82 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.84 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.89 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.8a is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.8b is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.8f is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.91 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.93 is stuck inactive for 1077.791303, current state unknown, last acting []
    pg 1.95 is stuck inactive for 1077.791303, current state unknown, last acting []

**Comment by apacoco9861** [comment]
reset cluster already

**Comment by jacetyh** [comment]
I know it's oold topic but, have you then checked mgr's? I had the same issue lately and active mgr service was running but had errors, restart of the service helped
