### ISSUE TITLE
use 'batch report' with c-v 

### ISSUE THREAD

**Issue by leseb** [rook/rook#2720]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

`ceph-volume` has a `batch report` subcommand which tells you what's going to happen so I think at some point it will be nice to have it. So the logs would tell us: "here what c-v is going to do to your drives".

**What is use case behind this feature:**

Better information collection.

**Comment by travisn** [comment]
Would rook simply run this command and write it to the logs and then proceed? Or is there something more we could use it for?

**Comment by leseb** [comment]
Just run and print for now. We could use it for idempotency too but I don't think that needed in the context of Rook.
