### ISSUE TITLE
Add support for object gateway in the dashboard

### ISSUE THREAD

**Issue by arctiqtim** [rook/rook#2722]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
An option for Rook to integrate the object gateway management capability in the Ceph dashboard.

**What is use case behind this feature:**
The Ceph Dashboard is a great visual tool for managing Ceph.  A strong use case for Ceph is as an object store for things like registry etc, and as such it's useful to have management capabilities over the object store function using the Ceph Dashboard.  Currently this is possible through some manual configuration but not using Rook.

**Environment**:
The below commands were successful using a Rook 0.9 deployment in Openshift 3.10

**Commands to Enable Dashboard Support for Object Store**:
Login to the rgw pod after enabling the object store using Rook and create a new object user with the system flag:
```
radosgw-admin user create --uid=dashboard --display-name=dashboard --system
```

Execute the following against the toolbox pod (with ceph preconfigured etc for management):
```
oc exec rook-ceph-tools-5cb84cb5b4-np7dx ceph dashboard set-rgw-api-host rook-ceph-rgw-my-store
oc exec rook-ceph-tools-5cb84cb5b4-np7dx ceph dashboard set-rgw-api-port 8080
oc exec rook-ceph-tools-5cb84cb5b4-np7dx ceph dashboard set-rgw-api-access-key <access-key>
oc exec rook-ceph-tools-5cb84cb5b4-np7dx ceph dashboard set-rgw-api-secret-key <secret-key>
```

Once dashboard has been configured as per above, the object store functionality can be managed from the dashboard.

![image](https://user-images.githubusercontent.com/19749398/53422755-0efc0180-39ae-11e9-88b8-c53e990c5c90.png)

**Comment by travisn** [comment]
For the operator to automate this, what versions of ceph is it needed for? Is it mimic and newer? I don't recall seeing object in the luminous dashboard.

**Comment by arctiqtim** [comment]
I've only tested mimic with the steps above

**Comment by mitchellmaler** [comment]
I just tested these commands as well but ran them from the operator.

1. Exec into operator pod
2. Run this command to generate system object storage user providing the required variables

```bash
POOL_NAME=object-pool-1
NAMESPAVE=storage-system
radosgw-admin user create --uid=dashboard --display-name=dashboard --system --rgw-realm=$POOL_NAME --rgw-zonegroup=$POOL_NAME --cluster=$NAMESPACE --conf=/var/lib/rook/NAMESPACE/storage-system.config --keyring=/var/lib/rook/NAMESPACE/client.admin.keyring
```
That command will dump the access key and secret key in json

3. Run these commands to setup the dashboard providing the required variables

```bash
POOL_NAME=object-pool-1
ACCESS_KEY=...
SECRET_LEY=...
ceph dashboard set-rgw-api-host  rook-ceph-rgw-$POOL_NAME
ceph dashboard set-rgw-api-access-key ACCESS_KEY
ceph dashboard set-rgw-api-secret-key SECRET_KEY
```

4. Log into the dashboard and verify it can connect to the object gateway.

**Comment by yanchicago** [comment]
@arctiqtim 
1). "Login to the rgw pod" to run "radosgw-admin" command will fail with below message.
[root@rook-ceph-rgw-rook-ceph-store-c75587d4b-qldtn /]# radosgw-admin user create --uid=dashboard --display-name=dashboard --system
2019-05-02 21:46:37.224 7fabdb8dc680 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2). Run all the commands at toolbox. After that, the dashboard still can't display object store.

@mitchellmaler Tried your steps. Not sure if 3rd step is executed in operator pod or toolbox. But either way doesn't work for me. 
The rgw pod log shows "
2019-05-03 14:11:56.891 7f3187a2a700  1 ====== starting new request req=0x7f3187a21850 =====
2019-05-03 14:11:56.891 7f3187a2a700  1 ====== req done req=0x7f3187a21850 op status=0 http_status=403 ======"

Here's the settings:
------------------------
`
[root@ceph-oam-6888b674bd-ffl2b /]# ceph dashboard get-rgw-api-host
rook-ceph-rgw-rook-ceph-store
[root@ceph-oam-6888b674bd-ffl2b /]# ceph dashboard get-rgw-api-user-id
mytest2
[root@ceph-oam-6888b674bd-ffl2b /]# ceph dashboard get-rgw-api-access-key
1YXA0R1SNCHR535HOH3B
[root@ceph-oam-6888b674bd-ffl2b /]# ceph dashboard get-rgw-api-secret-key
8NdzgmBMsROB3HnBpTKEb7E58YxOTURzkNpMvKpl
[root@ceph-oam-6888b674bd-ffl2b /]#  ceph dashboard get-rgw-api-port
8080
[root@ceph-oam-6888b674bd-ffl2b /]# radosgw-admin user info --uid=mytest2
{
    "user_id": "mytest2",
    "display_name": "mytest2",
    "email": "",
    "suspended": 0,
    "max_buckets": 1000,
    "auid": 0,
    "subusers": [],
    "keys": [
        {
            "user": "mytest2",
            "access_key": "1YXA0R1SNCHR535HOH3B",
            "secret_key": "8NdzgmBMsROB3HnBpTKEb7E58YxOTURzkNpMvKpl"
        }
    ],
`
The mgr log has below issue
`
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib64/python2.7/ssl.py", line 934, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:618)
`

**Comment by alfonsomthd** [comment]
> For the operator to automate this, what versions of ceph is it needed for? Is it mimic and newer? I don't recall seeing object in the luminous dashboard.

@travisn Right, Mimic and newer.
With this `image: ceph/ceph:v14.2.1-20190430` it's working as expected.

**Comment by alfonsomthd** [comment]
@travisn label "wontfix" should be removed?

**Comment by travisn** [comment]
@thotz Could you take a look at this? Enabling the object store in the dashboard by default would be very helpful. It should be straight forward for the operator to automate the steps mentioned by @mitchellmaler. Thanks!

**Comment by thotz** [comment]
@travisn Yeah sure I will take look into this issue

**Comment by thotz** [comment]
I was able above commands currently from toolbox. Even though I have created the user the dashboard for object gateway throws following error

Information
--
RGW REST API failed request with status code 403 '{"Code":"AccessDenied","RequestId":"tx00000000000000000036d-005dfa0ba1-11e8-my-store","HostId":"11e8-my-store-my-store"}'Please consult the documentation on how to configure and enable the Object Gateway management functionality.
with same user I was able to access object store via s3cmd. Will debug further and update

**Comment by thotz** [comment]
It was mistake from my end while configuring the user
