### ISSUE TITLE
Openshift with ovs-multitenant SDN plugin

### ISSUE THREAD

**Issue by arctiqtim** [rook/rook#2723]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In an Openshift environment where ovs-multitenant plugin is used for SDN, by default pods can not communicate between namespaces/projects.  Due to this the example configurations don't work completely out of the box, in that the rook-ceph-system project where the operator lives can't communicate to the pods built in the rook-ceph project.

**Expected behavior:**
The cluster should come up and the operator can communicate with the clusters built in rook-ceph

**How to reproduce it (minimal and precise):**
Install into openshift using the example manifests:
 * oc create -f scc.yaml
 * oc create -f operator.yaml
 * oc create -f cluster.yaml

Upon install, the cluster will not be built due to the operator not being able to manage, the cluster.

**Fix:**
Would be good to add the following to the documentation for Openshift:
```
oc new-project rook-ceph-system
oc new-project rook-ceph
oc adm pod-network join-projects --to rook-ceph rook-ceph-system
```
The steps pre-build the namespaces/projects, and then join them together over the SDN, allowing network connectivity between the projects.

**Environment**:
Tested on Openshift 3.10 with Rook 0.9

**Comment by travisn** [comment]
Thanks, it would be great to add a section for this in the [OpenShift doc](https://rook.io/docs/rook/master/openshift.html). 

In addition to opening the networking between rook-ceph and rook-ceph-system, we would also need to open it between any namespace that wants to consume the Ceph storage, and the `rook-ceph` namespace so the Ceph daemons will be accessible to the clients. So the admin would either need to join each individual namespace to `rook-ceph` or I believe there is also an option to open up a namespace to all other namespaces. It would be good to document both options.

**Comment by arctiqtim** [comment]
@travisn for block, I was able to consume storage from a different non-connected namespace no problem.  I haven't tried file.  Likely the better bet is to make the rook-ceph namespace/project a global project in the SDN to allow communication from all projects.

**Comment by travisn** [comment]
Agreed, let's add this to the openshift.md topic as well:
```oc adm pod-network make-projects-global rook-ceph```
