### ISSUE TITLE
CephFS deactivate is obsolete in nautilus

### ISSUE THREAD

**Issue by travisn** [rook/rook#2725]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
According to the [Nautilus release notes](https://github.com/ceph/ceph/blob/ae95aebf155064427fb9df2e1b442e4687395268/doc/releases/nautilus.rst), the `ceph mds deactivate` command is obsolete. The operator is currently using this command to remove a filesystem [here](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/client/filesystem.go#L219).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by ajarr** [comment]
Basically need to stop manually descaling the MDS for versions greater than luminous, as descaling is done automatically from mimic onwards by setting max_mds with the desired number of MDSs.

Fixing the below TODO should fix the issue.
https://github.com/rook/rook/commit/96f9a9c4ad72057237b4c210bb8d31a890a73323#diff-3e7c210118e974b0c8c447ccf512e8e2R172

**Comment by batrick** [comment]
Does Rook actually know how to remove a file system? Or did you mean reduce `max_mds`?

**Comment by batrick** [comment]
See also the new commands `ceph fs fail <foo>` and `ceph fs set <foo> down true`.

**Comment by ajarr** [comment]
> Does Rook actually know how to remove a file system? Or did you mean reduce `max_mds`?

Meant reduce 'max_mds'

**Comment by ajarr** [comment]
> Does Rook actually know how to remove a file system? Or did you mean reduce `max_mds`?

I meant to reduce 'max_mds'.

**Comment by ajarr** [comment]
> See also the new commands `ceph fs fail <foo>` and `ceph fs set <foo> down true`.

@batrick, when deleting a filesystem, rook brings down the MDS cluster by setting 'cluster_down' flag to true and failing the MDS daemons individually.
https://github.com/rook/rook/blob/master/pkg/operator/ceph/file/filesystem.go#L221
https://github.com/rook/rook/blob/master/pkg/operator/ceph/file/filesystem.go#L102
Is this procedure OK for at least luminous? I see the luminous doc has a more complex procedure to bring a MDS cluster down, http://docs.ceph.com/docs/luminous/cephfs/administration/#taking-the-cluster-down ?

To bring down a MDS cluster for ceph versions >= mimic , is it OK to set 'joinable' flag to false and fail the MDS daemons individually, 
or is it preferred to use,
`ceph fs set <foo> down true`
or
`ceph fs fail <foo>`?
This is tracked here, 
https://github.com/rook/rook/issues/2841

**Comment by batrick** [comment]
> Is this procedure OK for at least luminous?

Yes, it still works for Nautilus too.

>I see the luminous doc has a more complex procedure to bring a MDS cluster down, http://docs.ceph.com/docs/luminous/cephfs/administration/#taking-the-cluster-down ?

Ya, it's not really necessary to do that (deactivate MDS) if you're going to just delete the FS.

> To bring down a MDS cluster for ceph versions >= mimic , is it OK to set 'joinable' flag to false and fail the MDS daemons individually,

It's probably not worth changing the code for Mimic. However, I'd recommend `fs fail` for nautilus as there is less MDSMap churn due to multiple separate updates.
