### ISSUE TITLE
Unable to mount volumes for pod "kube-registry-v0-5dlgz_rook-ceph(0b2ba978-3a84-11e9-9ecc-0a58ac1f0329)": timeout expired waiting for volumes to attach or mount for pod "rook-ceph"/"kube-registry-v0-5dlgz

### ISSUE THREAD

**Issue by shayshahak** [rook/rook#2727]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
unable to mount a Shared FileSystem to a client
**Expected behavior:**
a successful mount 
**How to reproduce it (minimal and precise):**

I followed the tutorial on AKS:
https://rook.github.io/docs/rook/v0.9/ceph-filesystem.html

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu
* Kernel (e.g. `uname -a`): 4.15.0-1037-azure #39~16.04.1-Ubuntu
* Cloud provider or hardware configuration: Azure AKS
* Rook version (use `rook version` inside of a Rook Pod): v0.9.2
* Kubernetes version (use `kubectl version`): v1.12.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
HEALTH_OK

[root@aks-agentpool-21100262-1 /]# ceph status
  cluster:
    id:     ec9f865b-4c8c-489c-8cc8-7558a636300b
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum c,b,a
    mgr: a(active)
    mds: myfs-1/1/1 up  {0=myfs-a=up:active}, 1 up:standby-replay
    osd: 3 osds: 3 up, 3 in

  data:
    pools:   2 pools, 200 pgs
    objects: 22  objects, 2.2 KiB
    usage:   32 GiB used, 55 GiB / 87 GiB avail
    pgs:     200 active+clean

  io:
    client:   852 B/s rd, 2 op/s rd, 0 op/s wr

[root@aks-agentpool-21100262-1 /]# ceph fs status
myfs - 0 clients
====
+------+----------------+--------+---------------+-------+-------+
| Rank |     State      |  MDS   |    Activity   |  dns  |  inos |
+------+----------------+--------+---------------+-------+-------+
|  0   |     active     | myfs-a | Reqs:    0 /s |   10  |   13  |
| 0-s  | standby-replay | myfs-b | Evts:    0 /s |    0  |    0  |
+------+----------------+--------+---------------+-------+-------+
+---------------+----------+-------+-------+
|      Pool     |   type   |  used | avail |
+---------------+----------+-------+-------+
| myfs-metadata | metadata | 2286  | 16.2G |
|   myfs-data0  |   data   |    0  | 16.2G |
+---------------+----------+-------+-------+
+-------------+
| Standby MDS |
+-------------+
+-------------+
MDS version: ceph version 13.2.4 (b10be4d44915a4d78a8e06aa31919e74927b142e) mimic (stable)

**Comment by shayshahak** [comment]
i tried both to the namespace of which the cluster is located ("rook-ceph") and also to the default namespace with the same results

**Comment by jtlayton** [comment]
From where did you try to mount it? (The toolbox container?)

How did you try to mount it and what happened? (please paste in the command line you used and the resulting output)

**Comment by shayshahak** [comment]
no, not the toolbox container.
from the sample K8s Registry Sample:
https://rook.io/docs/rook/v0.9/ceph-filesystem.html

the output is:

Unable to mount volumes for pod "kube-registry-v0-5dlgz_rook-ceph(0b2ba978-3a84-11e9-9ecc-0a58ac1f0329)": timeout expired waiting for volumes to attach or mount for pod "rook-ceph"/"kube-registry-v0-5dlgz

**Comment by galexrt** [comment]
@shayshahak Have you configured the flexvolume correctly for AKS? See https://rook.io/docs/rook/v0.9/flexvolume.html.
From Slack to another AKS user:
> Alexander Trost   [1 day ago]
> Looking at https://github.com/Azure/kubernetes-keyvault-flexvol#option-2---aks-azure-kubernetes-service-manually the path is flexvolume path is `/etc/kubernetes/volumeplugins`.

**Comment by shayshahak** [comment]
@galexrt AKS is not on the list of that article.
i followed FlexVol installation instructions here:
https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume

**Comment by galexrt** [comment]
@shayshahak So you have configured your kubelet as shown in the docs you linked, and you have also set `/etc/kubernetes/volumeplugins` as the flexvolume directory on the Rook Ceph operator? As shown in the documentation and/or https://github.com/rook/rook/blob/release-0.9/cluster/examples/kubernetes/ceph/operator.yaml#L418-L419.

**Comment by shayshahak** [comment]
no, i haven't. sorry.
I'll do that and update. thanks

**Comment by shayshahak** [comment]
ok, i have a progress but now i see a new error on the client pod:

Warning  FailedMount  48s  kubelet, aks-agentpool-21100262-0  MountVolume.SetUp failed for volume "volume" : mount command failed, status: Failure, reason: failed to mount filesystem myfs to /var/lib/kubelet/pods/c0955691-3a98-11e9-9ecc-0a58ac1f0329/volumes/ceph.rook.io~rook/volume with monitor 10.0.174.182:6789,10.0.109.223:6789,10.0.79.248:6789:/ and options [name=admin secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx mds_namespace=myfs]: mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/c0955691-3a98-11e9-9ecc-0a58ac1f0329/volumes/ceph.rook.io~rook/volume --scope -- mount -t ceph -o name=admin,secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,mds_namespace=myfs 10.0.174.182:6789,10.0.109.223:6789,10.0.79.248:6789:/ /var/lib/kubelet/pods/c0955691-3a98-11e9-9ecc-0a58ac1f0329/volumes/ceph.rook.io~rook/volume
Output: Running scope as unit run-r25710d274f5f4619bf9d9c116c42ad02.scope.
mount: mount 10.0.174.182:6789,10.0.109.223:6789,10.0.79.248:6789:/ on /var/lib/kubelet/pods/c0955691-3a98-11e9-9ecc-0a58ac1f0329/volumes/ceph.rook.io~rook/volume failed: Connection timed out

**Comment by shayshahak** [comment]
I'm having hard time understanding how to "Configuring the Kubernetes kubelet"
I know with AKS it should be --volume-plugin-dir="/etc/kubernetes/volumeplugins"
but i don't know how to update it

**Comment by shayshahak** [comment]
i deleted my cluster, made sure i followed the steps carefully with the operator settings:
- name: FLEXVOLUME_DIR_PATH
  value: "/etc/kubernetes/volumeplugins"
(no need to perform "Configuring the Kubernetes kubelet" on AKS)

and now everything is working just fine.

perhaps my problem was related to:
"if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster."

anyway thanks for your help!

**Comment by mykaul** [comment]
@shayshahak - if there are any steps that need to be documented to support AKS properly, we'd love to know!

**Comment by shayshahak** [comment]
hi @mykaul 
with regards to AKS the one action to be taken care of is setting the right "FLEXVOLUME_DIR_PATH" under the Operator exactly as described under:
 https://rook.io/docs/rook/v0.9/flexvolume.html#most-common-readwrite-flexvolume-path

the step of "Configuring the Kubernetes kubelet" is not necessary for AKS as mentioned here:
https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume
"config kubelet service to enable FlexVolume driver
Note: skip this step in AKS or from acs-engine v0.12.0"

thanks!
