### ISSUE TITLE
In kubernetes, rook sometimes fails to initialize internal etcd

### ISSUE THREAD

**Issue by travisn** [rook/rook#275]
Starting k8s sometimes fails to start the rook daemonset pod when initializing internal etcd with `error querying discovery service`. In many runs of the demo, I hit this less than 20% of the time. I have seen it be a blocking issue where the pods never failed to start, as well as an issue where the pod was able to recover and restart successfully.

```
$ kubectl logs rookd-lb8j3
2016-12-08 18:20:05.876641 I | util: loaded id from data dir
2016-12-08 18:20:05.876771 I | clusterd: Starting cluster. configDir=/var/lib/rook, nodeID=35aa2eb5880a, url=https://discovery.etcd.io/9c3a37dd489b0d16e155406b9b163c8a, members=, publicIPv4=10.2.51.2, privateIPv4=10.2.51.2, logLevel=INFO
error querying discovery service
```

**Comment by bassamtabbara** [comment]
Is there a way to wait for networking to be stable in a pod before running our code?

**Comment by jbw976** [comment]
Is that our error message "error querying discovery service"? if so, can we include the error object in the message?

**Comment by travisn** [comment]
@bassam, will look into that. @jared, yes i'll add the error object

**Comment by travisn** [comment]
for now i will go with retrying etcd calls to the discovery service with a small backoff. If several requests fail, then we'll fail rook and rely on k8s to restart the pod.
