### ISSUE TITLE
Publish Rook to OperatorHub.io

### ISSUE THREAD

**Issue by Prodian0013** [rook/rook#2750]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Publish rook operator on operatorhub.io

**What is use case behind this feature:**
Ease of distribution

**Environment**:

**Comment by mykaul** [comment]
https://github.com/operator-framework/community-operators/pull/78

**Comment by leseb** [comment]
Fixed via https://github.com/operator-framework/community-operators/pull/348
