### ISSUE TITLE
only one client (k8s node) is connected to the Ceph FileSystem

### ISSUE THREAD

**Issue by shayshahak** [rook/rook#2755]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
even though i have 3 workers in my cluster and the OSD, MON and MDS are running on all of them. only one node is able to be a client of the FileSystem. thus i have to use a nodeSelector and force all of my pods to run on the same Node
**Expected behavior:**
having all the nodes in the k8s cluster to be clients of the FileSystem thus having the ability to have pods on all of the clusters nodes
**How to reproduce it (minimal and precise):**

i used the configuration files located here:
https://github.com/shayshahak/Rook-for-AKS
they are exactly like the official uder rook.io only the Operator is tailored to Azure AKS (changed FLEXVOLUME_DIR_PATH)

**Environment**:
* OS (e.g. from /etc/os-release):  Ubuntu
* Kernel (e.g. `uname -a`):  4.15.0-1037-azure #39~16.04.1-Ubuntu
* Cloud provider or hardware configuration: Azure AKS
* Rook version (use `rook version` inside of a Rook Pod): v0.9.2
* Kubernetes version (use `kubectl version`):  v1.12.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK

**Comment by galexrt** [comment]
@shayshahak Could you post your Filesystem object yaml and an example application manifest.

Are you using a `volumes` entry for mounting the filesystem or "self made" CephFS PVCs?

**Comment by shayshahak** [comment]
@galexrt 
the Filesystem yaml: https://raw.githubusercontent.com/shayshahak/Rook-for-AKS/master/filesystem.yaml
application example: https://raw.githubusercontent.com/shayshahak/Rook-for-AKS/master/deploy.yaml

I'm using Volumes for the entry mounting, as shown in the "K8s Registry Sample"

**Comment by shayshahak** [comment]
i got it!
the problem was with the CephCluster configuration.

when using your example here for some reason only 1 Node is able to use the Shared FileSystem:
https://rook.io/docs/rook/v0.9/ceph-quickstart.html

when using your example here all Node are able to use the shared FileSystem:
https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/cluster.yaml

not sure what is the specific difference that causes the problem but the differences i found are:
"image: ceph/ceph:v13.2.4-20190109" vs "image: ceph/ceph:v13"
"allowUnsupported: false"

so my take is the problem could be with one of those

**Comment by shayshahak** [comment]
a tutorial for AKS can be found here:
https://cloudblogs.microsoft.com/opensource/2019/03/13/scaling-wordpress-using-rook-azure-kubernetes-service/
