### ISSUE TITLE
Intermittent failure with fs mount in TestFileStorageMountUser_SmokeTest

### ISSUE THREAD

**Issue by travisn** [rook/rook#2760]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
On March 1st, we started seeing intermittent failures in the master builds in the test `TestFileStorageMountUser_SmokeTest`. 

The issue has been seen in builds 977, 978, 979, and [984](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/984/pipeline/41/) thus far. Builds 980-983 did not hit this issue. Perhaps coincidentally, each failure always happened on K8s 1.11, but in the last build it also hit on K8s 1.12.

```
--- FAIL: TestSmokeSuite (462.26s)
    --- PASS: TestSmokeSuite/TestBlockCSI_SmokeTest (0.01s)
    --- PASS: TestSmokeSuite/TestBlockStorage_SmokeTest (116.38s)
    --- FAIL: TestSmokeSuite/TestFileStorageMountUser_SmokeTest (16.87s)
        require.go:765: 
            	Error Trace:	filesystem_mountuser_test.go:65
            	            				filesystem_mountuser_test.go:46
            	            				smoke_test.go:94
            	Error:      	Expected nil, but got: &errors.errorString{s:"kubectl exec command bash failed on pod rook-ceph-tools in namespace smoke-ns: Failed to run: kubectl [exec -n smoke-ns rook-ceph-tools -- bash -c mount -t ceph -o mds_namespace=smoke-test-fs-mountuser,name=admin,secret=$(grep key /etc/ceph/keyring | awk '{print $3}') $(grep mon_host /etc/ceph/ceph.conf | awk '{print $3}'):/ /tmp/testrook] : Failed to complete 'kubectl': exit status 2. . output: mount error 2 = No such file or directory\ncommand terminated with exit code 2"}
            	Test:       	TestSmokeSuite/TestFileStorageMountUser_SmokeTest
```

@BlaineEXE Could you take a look? The last PR merged around this time was #2702, though it's not clearly related to that either.

**Expected behavior:**
No intermittent CI issues

**Comment by BlaineEXE** [comment]
I'll start trying to debug this.
