### ISSUE TITLE
In Nautilus, CephFS standby-replay is now a setting on the file system

### ISSUE THREAD

**Issue by batrick** [rook/rook#2768]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

From the Nautilus release notes:

````
* The MDS mds_standby_for_*, mon_force_standby_active, and mds_standby_replay
  configuration options have been obsoleted. Instead, the operator may now set
  the new "allow_standby_replay" flag on the CephFS file system. This setting
  causes standbys to become standby-replay for any available rank in the file
  system.
````

**Expected behavior:**

Rook should stop using `mds_standby_for` configs (if it does) and use a setting on the file system to enable standby-replay.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by batrick** [comment]
Ceph PR that changed this behavior: https://github.com/ceph/ceph/pull/26638

**Comment by leseb** [comment]
@batrick so we don't need to set MDS ranks anymore too?

**Comment by ajarr** [comment]
> @batrick so we don't need to set MDS ranks anymore too?

are you talking about this setting that is no longer possible?
https://github.com/ceph/ceph/pull/26638/files#diff-2e5efbe2fdd0c77602a636291aefc637L12

**Comment by batrick** [comment]
> @batrick so we don't need to set MDS ranks anymore too?

What do you mean "set MDS ranks"? `standby_for_rank`?

**Comment by batrick** [comment]
> > @batrick so we don't need to set MDS ranks anymore too?
> 
> are you talking about this setting that is no longer possible?
> https://github.com/ceph/ceph/pull/26638/files#diff-2e5efbe2fdd0c77602a636291aefc637L12

@leseb if you mean this `ceph-mds` flag ^, then yes, you don't need to set the MDS rank.

**Comment by leseb** [comment]
Thanks @batrick @ajarr basically, we have this code: https://github.com/rook/rook/pull/2770/files#diff-88e122c59d793314e266aa0c55b610b9R87

I was wondering if we should ignore it for Nautilus and above too.

Here is the full function: https://github.com/rook/rook/blob/2af0be2cecc101a5dad5bfff454043bbe3d3726c/pkg/daemon/ceph/client/filesystem.go#L160
