### ISSUE TITLE
Mon 

### ISSUE THREAD

**Issue by zhangdaxian2017** [rook/rook#2771]
I used kubectl apply -f https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml,,created a rook-ceph-cluster.
But the pod is not running.
[root@master ~]# kubectl get pod -n rook-ceph
NAME                               READY   STATUS                  RESTARTS   AGE
rook-ceph-mon-a-88df95bf-kd7dh     0/1     Init:CrashLoopBackOff   10         29m
rook-ceph-mon-d-684d7b8c5-t4wmr    0/1     Init:CrashLoopBackOff   10         27m
rook-ceph-mon-f-7f75c756c7-drk4w   0/1     Init:CrashLoopBackOff   9          26m

So,I used "kubectl describe pod rook-ceph-mon-a-88df95bf-kd7dh" get message:"Warning  Failed                 3s                 kubelet, node      Error: failed to start container "init-mon-fs": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/kubelet/pods/767062aa-3f60-11e9-89b7-000c2942cae7/volumes/kubernetes.io~secret/rook-ceph-mons-keyring\\\" to rootfs \\\"/home/docker/overlay/6544598017aa57fcccc120b4be6202c679daab23ba05c601f73c88a21fd96807/merged\\\" at \\\"/home/docker/overlay/6544598017aa57fcccc120b4be6202c679daab23ba05c601f73c88a21fd96807/merged/etc/ceph/keyring-store\\\" caused \\\"mkdir /home/docker/overlay/6544598017aa57fcccc120b4be6202c679daab23ba05c601f73c88a21fd96807/merged/etc/ceph/keyring-store: read-only file system\\\"\"""

**Comment by galexrt** [comment]
@zhangdaxian2017 It seems that you created two issues with the same content. Can this one be closed in favor of #2772?

**Comment by zhangdaxian2017** [comment]
> @zhangdaxian2017 It seems that you created two issues with the same content. Can this one be closed in favor of #2772?

oh,i mistake
