### ISSUE TITLE
Operator hanging on creation of self-signed cert for the mgr dashboard

### ISSUE THREAD

**Issue by arctiqtim** [rook/rook#2784]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Dashboard will not deploy with building the Ceph cluster.  You need to disable dashboard, deploy the cluster, then enable dashboard.

**Expected behavior:**
Dashboard should be able to deploy with the cluster.

**How to reproduce it (minimal and precise):**
Attempt to create a Ceph cluster with the Rook operator with Ceph dashboard enabled.  The installer will not complete.  In order to complete you need to install the cluster with dashboard disabled first.  Then enable the dashboard.

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.5
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 0.90
* Kubernetes version (use `kubectl version`): 3.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by travisn** [comment]
I have seen this before that creating the self-signed cert would hang when initially configuring the dashboard. Can you share the operator log to confirm this?

**Comment by gouki777** [comment]
rook version 0.9   
I have the same problem.  
you need cluster.yaml  dashboard = false。
#2781

**Comment by sebastian-philipp** [comment]
the question is why? There may be a condition when the mon is not yet aware that all mgr daemons support the dashboard

**Comment by noahdesu** [comment]
It's hard to say exactly what happened in this ticket without additional information, but I can identify an entire class of scenarios into which this issue may fall that we might want to create an approach for dealing with.

When the operator starts the managers only a few things that may go wrong would result in the operator aborting the startup operation. These are things like encountering errors interacting with kubernetes itself (e.g. https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/mgr/mgr.go#L137). Important to this discussion is that complex operations like configuring the orchestrator and dashboard modules during startup do not abort operator operation when errors occur, but rather log the errors and move on:

```
	if err := c.configureDashboard(c.dashboardPort()); err != nil {
		logger.Errorf("failed to enable mgr dashboard. %+v", err)
	}
```

This means that only synchronous calls that hang when configuring the dashboard would result in what  @arctiqtim reported in this issue as:

> The installer will not complete.

The most likely culprits here are network connections that hang. Despite all invocations of `ceph` using a `connect-timeout=N` argument, these calls _can_ hang indefinitely.

It's easy to reproduce an indefinite hang with `cluster::createSelfSignedCert` by destroying the monitor quorum (e.g. killing 2 out of 3 monitors) and running the module command to generate the certs _before_ the monitors stop serving reads / accepting connections (which allows the command to proceed, but blocks when the operation attempts to a quroum write). That window might be 5-10 seconds, outside of which `connect-timeout` will function as expected. Technically the client connection is active, but the hang occurs between the manager and the monitor. Unfortunately these inter-daemon connections can block a long time. I let one go for an hour before killing it. It's not clear they even have timeouts. These hidden dependencies probably exist and can pop up in all sorts of situations.

*I think what we probably want to do is identify the set of operations that we are willing to forcefully abort without fully aborting an orchestration run. This would be the equivalent of ctrl-c'ing a manual command for setting up, say the dashboard, and then proceeding to setup OSDs.*

Talking to upstream about this would also be useful, I suppose. Ideally connection timeouts could be propogated end-to-end for a client context, but I have no idea if that would be feasible.

Thoughts?

**Comment by sebastian-philipp** [comment]
:+1: for not waiting indefinitely for any calls and instead log them

**Comment by travisn** [comment]
Agreed, the calls to configure the mgr modules should be cancelled after some timeout if we see them not responding for too long. The operator needs to not block for too long or else the rest of the orchestration will suffer.
