### ISSUE TITLE
PriorityClass support

### ISSUE THREAD

**Issue by vreon** [rook/rook#2787]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

The `CephCluster` CRD should have fields for setting `priorityClassName` on pods created by the operator. Ideally, users would be able to set `priorityClassName` for `mgr`, `mon`, and `osd` pods independently, just as they can today with `resources`.

**What is use case behind this feature:**

I'd like to ensure that Rook-created pods take precedence over lower-priority workloads when scheduling, even if those workloads have to be evicted.

Kubernetes [Pod Priority and Preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption) is currently in beta, but is [graduating to GA](https://github.com/kubernetes/kubernetes/pull/73555) in v1.14.

**Environment**:

n/a

**Comment by leojonathanoh** [comment]
agree, this is needed for existing clusters under resource pressure that want to add rook as their storage for some workload. Without `PriorityClass` support, some rook `mon`s might never be scheduled.

**Comment by dimm0** [comment]
Would be very useful
