### ISSUE TITLE
Ceph block storage not mount on pods schedule on infra nodes in OCP

### ISSUE THREAD

**Issue by arctiqtim** [rook/rook#2788]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
With a working Ceph cluster it's anticipated to mount storage in any pod.

**Expected behavior:**
With OCP, by default block devices can't be mounted by pods running on Openshift Infra nodes

**How to reproduce it (minimal and precise):**
Deploy the operator and rook-ceph cluster as per directions.  What ends up happening is that the agent and discover daemonsets do not run on nodes labelled with the infra role in OCP.  This is important for persistent storage for things like metrics/logging/registry as they run typically on infra nodes.  In order to get this to work you can follow the directions here:

```
oc label node node-role.kubernetes.io/rook=true -l node-role.kubernetes.io/infra=true
oc label node node-role.kubernetes.io/rook=true -l node-role.kubernetes.io/compute=true
oc patch namespace rook-ceph-system -p '{ "metadata": { "annotations": { "openshift.io/node-selector": "node-role.kubernetes.io/rook=true" } } }'

# If doing after the operator is deployed:
oc delete pods -l app=rook-ceph-agent
oc delete pods -l app=rook-discover
```
This will enable the daemonsets to run on both compute and infra nodes in the cluster, which will allow for pods to mount block pvs.

**Environment**:
* OS (e.g. from /etc/os-release): RHEL
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: N/A
* Rook version (use `rook version` inside of a Rook Pod): 0.9.3
* Kubernetes version (use `kubectl version`): 1.10-1.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by sgalla** [comment]
Has there been any update or has anyone solved this issue? I'm having the same problem trying to run OSD pods on infra nodes.

**Comment by sgalla** [comment]
Has there been any update or has anyone solved this issue? I'm having the same problem trying to run OSD pods on infra nodes

**Comment by AdlerFleurant** [comment]
Is there a plan to fix this?

**Comment by travisn** [comment]
We can add tolerations to the agent and discovery daemonsets with options in the operator deployment. See the [AGENT_TOLERATION_KEY](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator-openshift.yaml#L132) and [DISCOVER_TOLERATION_KEY](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator-openshift.yaml#L158). Are the tolerations sufficient for you? 

There isn't a plan for Rook to update the namespace annotations as suggested in this issue. That's something we could potentially get into the documentation if needed though.
