### ISSUE TITLE
Integration tests for EdgeFS

### ISSUE THREAD

**Issue by travisn** [rook/rook#2791]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The integration tests currently do not run the EdgeFS. This means that we don't have checks in place to know if a change will break EdgeFS with each PR that merges. With each PR there will be a risk of regression until the integration tests are added.
@dyusupov are these already in the plan? 

**What is use case behind this feature:**
Stability of the EdgeFS operator.

**Comment by dyusupov** [comment]
ack. I was just thinking about the same. thanks for bringing this up.
