### ISSUE TITLE
Edgefs-ui 1.0.0 container does not exist

### ISSUE THREAD

**Issue by dimm0** [rook/rook#2794]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When creating the edgefs cluster:

```
  Warning  Failed     15s                kubelet, dtn0.noc.ucdavis.edu  Failed to pull image "edgefs/edgefs-ui:1.0.0": rpc error: code = Unknown desc = Error response from daemon: manifest for edgefs/edgefs-ui:1.0.0 not found
```

**Expected behavior:**
According to https://github.com/rook/rook/blob/master/Documentation/edgefs-cluster-crd.md#cluster-metadata, "We recommend to specify particular image version for production use, for example edgefs/edgefs:1.0.0." - expect 1.0.0 version to exist for all components

**How to reproduce it (minimal and precise):**
Init the cluster according to docs, change "latest" version to "1.0.0"

**Comment by dyusupov** [comment]
Thank you for reporting the issue. It is possible that ui:1.0.0 wasn't tagged at the moment we marked 0.9. Could you please switch to master operator and edgefs/edgefs:1.0.1 version?

**Comment by dimm0** [comment]
I've left the latest, and there are 2 more issues... Now stuck with the latest I submitted

**Comment by dyusupov** [comment]
Ok. I tagged missing 1.0.0. Tentatively closing the issue and we will continue troubleshooting in the other one you reported. Thanks again.
