### ISSUE TITLE
Client pods can't write to NFS mount 

### ISSUE THREAD

**Issue by ldcastell** [rook/rook#2805]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Client pods can't write files to NFS mount. Getting 'Invalid argument' error on client pod. 
NFS server returning: 
```
mdc_lookup :INODE :DEBUG :Cache Miss detected for test.txt
12/03/2019 00:07:13 : epoch 5c86f6fb : rook-nfs-0 : ganesha.nfsd-1[work-81] lookup :FSAL :DEBUG :Failed to open stat test.txt: No such file or directory
```
**Expected behavior:**
Client pods should be able to write files to NFS mount
**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):  4.20.4-686.native
* Cloud provider or hardware configuration:  bare metal
* Rook version (use `rook version` inside of a Rook Pod): master
* Kubernetes version (use `kubectl version`):v1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox]
```
cluster:
    id:     57bf4663-cc9a-4b32-8a10-b7606cfb81a9
    health: HEALTH_WARN
            Degraded data redundancy: 182/513 objects degraded (35.478%), 123 pgs degraded, 200 pgs undersized
```
(https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by leseb** [comment]
@jtlayton can you help with this? Thanks!

**Comment by jtlayton** [comment]
@ldcastell : can you attach the ganesha.conf file from your ganesha pod here? Also if you have any configs that are included from RADOS, please copy those into files and paste them here as well.

**Comment by tombarron** [comment]
This *might* be the same issue [1]  we saw from manila serving shares to k8s from cephfs via ganesha where cephfs volumes had to be created mode 0775 instead of the default 0755 to be successfully mounted in k8s.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1643167

**Comment by ldcastell** [comment]
I've found what was wrong. I was following the guide at: https://rook.io/docs/rook/v0.9/nfs.html#accessing-the-export and I used the yaml file from there which is missing an annotation `volume.beta.kubernetes.io/mount-options: "vers=4.1"`. I noticed it once I look into the source, so this time used the yaml from nfs directory in source code and this time pods were able to write to the NFS mount.
