### ISSUE TITLE
edgefs Repo not found

### ISSUE THREAD

**Issue by ulrichSchreiner** [rook/rook#2816]
In the documentation there are  links to [EdgeFS Wiki](https://github.com/Nexenta/edgefs/wiki) but this links are dead. It would be great to update the links.

The whole repository for [edgefs](https://github.com/Nexenta/edgefs) returns a NotFound. Is this repo open or closed source?

**Comment by galexrt** [comment]
Ping @dyusupov

**Comment by dyusupov** [comment]
still working on fixing it. not rook's issue.
