### ISSUE TITLE
Ceph: Add details about cluster health and osd availability to CRD

### ISSUE THREAD

**Issue by rohantmp** [rook/rook#2824]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Automated fencing and upgrade of nodes using things like the [cluster-api](https://github.com/kubernetes-sigs/cluster-api) should respect the availability of storage/osds. For this, I propose monitoring the cluster health and updating the CRD with details like how many osds are down currently and which hosts they're on.

**What is use case behind this feature:**

This way, a fencing/upgrade agent could prevent data loss and loss of availability by:
- ensuring that not too many osds are affected at once.
- all data is sufficiently replicated. 
- no data is misplaced.

**Environment**:
Environments where nodes and backing storage are dynamically provisioned and fenced, but rook-ceph is used to provide replication.

**Comment by rohantmp** [comment]
I would like to be assigned to this.

**Comment by leseb** [comment]
Closed via https://github.com/rook/rook/pull/2938
