### ISSUE TITLE
Ceph: Mechanism to prevent ceph from marking osds out during upgrade

### ISSUE THREAD

**Issue by rohantmp** [rook/rook#2825]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Expose a mechanism to mark a node containing osds as "in-maintenance" to prevent osds from being marked out during planned downtime.

**What is use case behind this feature:**
Node upgrade.

**Comment by BlaineEXE** [comment]
Agreed, @rohantmp. I think this feature fits pretty squarely in the realm of Ceph's responsibilities. I imagine a user setting `noout` for a node's osds via Ceph's admin CLI (or the dashboard), doing maintenance, and then unsetting `noout` via the same method.

There is a corresponding Ceph issue here: https://tracker.ceph.com/issues/38940
