### ISSUE TITLE
pass env vars with rook-ceph-system namespace and API version to ceph-mgr containers

### ISSUE THREAD

**Issue by jtlayton** [rook/rook#2843]
The rook orchestrator in ceph-mgr has the following hardcoded values in it:
```
ROOK_SYSTEM_NS = "rook-ceph-system"
ROOK_API_VERSION = "v1"
```
We probably should have rook pass both of these values to the ceph-mgr container via a environment variable when starting it up. Once rook passes in the appropriate values in an environment var, we'll need to fix up the rook orchestrator in ceph to consume them.

**Comment by rohan47** [comment]
@jtlayton are you referring to the hardcoded value here https://github.com/ceph/ceph/blob/7ba6bece4187eda5d05a9b84211fe6ba8dd287bd/src/pybind/mgr/rook/rook_cluster.py#L29 right?

**Comment by jtlayton** [comment]
Yes, both values actually. ROOK_SYSTEM_NS and ROOK_API_VERSION should both be provided by environment variables.
