### ISSUE TITLE
Do not allow merging PR that are not rebased on top of master

### ISSUE THREAD

**Issue by leseb** [rook/rook#2849]
Currently, Rook's Github is not configured to show that a branch is not up to date with master. That's a big problem because some not up to date with master is not guaranteed to work.
So we need to display (setting on Github) the status of the branch and also implement a strict policy merging, for this we could use mergify.io.

**Comment by travisn** [comment]
In the past we had enabled the policy where everything had to be rebased on top before merging. However, this placed a restriction of re-running the CI between every merge and really slowed things down. Sounds great to have a merge tool help us out with this, although if it isn't triggering CI when it rebases before the merge to master, is there still a benefit?

**Comment by leseb** [comment]
Yes, always rebasing will re-trigger the CI, however, this will greatly improve the quality of the project. So yes, it costs more CI resources and slows things down but the outcome is a highly qualified and robust product so I'm personally willing to accept that trade-off.

The tool can do more than that, it can also do the backport for us and merge them once the CI passes which has proven to be extremely useful.

**Comment by travisn** [comment]
I could see this working with these steps:
1. The PR is approved
1. The maintainer clicks to merge
1. The tool rebased the PR if needed, kicks off the build, then merges automatically when the CI is done. 

With the length and unreliability of the integration tests, we would need to skip those. Only running the build and unit test steps would need to be sufficient.

Alternatively, I would argue that the likelihood of hitting a merge issue with today's approach is low enough that we don't need to make a change. Responding to master build failures just needs to be highest priority.

**Comment by leseb** [comment]
I'm sure to understand your suggestion, with mergify the steps will be:

1. The PR is approved
2. If the branch is up-to-date, we run the CI, if the CI passes it gets merged automatically
If the branch is not up-to-date, mergify rebases it, run the CI and if the CI passes it gets merged automatically

IMHO if the integration tests are unreliable then we should work on fixing that.

It's not about hitting a merge issue, it's more endup in a situation where we merge code with not up to date code.

**Comment by travisn** [comment]
Per earlier conversation, agreed that it would be great to have a bot help us manage this process.

The integration tests will always be imperfect as long as we are making changes. As soon as you work out the bugs from one integration test, another integration test is added that needs stabilization. No matter how much time we have spent fixing integration tests, there is always another random failure popping up with the CI or some new test. Perhaps we need a set of "stable" integration tests that should be used to block a merge if they fail. In any case, this is a long term area for improvement.

**Comment by galexrt** [comment]
Still a good to have
