### ISSUE TITLE
Wrong apiGroup specified in operator clusterRole in Chart v0.9

### ISSUE THREAD

**Issue by lewismarshall** [rook/rook#2853]
**Is this a bug report or feature request?**
* Bug Report
The apiGroup specified here:
https://github.com/rook/rook/blob/1fa68b368098da56e11cb2c027a487abca517809/cluster/charts/rook-ceph/templates/clusterrole.yaml#L147-L157
...needed to be changed to `policy` to prevent access problems with the operator.

I suspect this PR #2661 has fixed this for the v1.0 release but I suspect anyone deploying v0.9.3 will hit this problem.

**Deviation from expected behavior:**
Operator got RBAC failures when managing the cluster - sorry I don't have the details from when this occurred but we have a running cluster now this is changed.

**Expected behavior:**
The operator works without RBAC access problems.

**How to reproduce it (minimal and precise):**

1. Deploy the operator from the chart at version v0.9.3.
1. Create a cluster using the examples.

**Environment**:
* OS (e.g. from /etc/os-release): `Container Linux by CoreOS`
* Kernel (e.g. `uname -a`): `Linux dsp-ops3 4.14.96-coreos-r1 #1 SMP Tue Feb 12 21:16:22 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz GenuineIntel GNU/Linux`
* Cloud provider or hardware configuration: `Metal (Cisco UCS)`
* Rook version (use `rook version` inside of a Rook Pod): `v0.9.3`
* Kubernetes version (use `kubectl version`): `v.1.12.3`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `Custom PXE boot`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): `ceph status` didn't return as the deployments for monitors where not created.

**Comment by travisn** [comment]
@lewismarshall I wouldn't think this would affect the 0.9 release since the change from extensions to apps was only done in master since that release. Can you confirm if you are using the yamls all from the release-0.9 branch? If you're using the yamls from master you could certainly hit this issue though.

**Comment by lewismarshall** [comment]
Hi @travisn I can confirm I'm using the chart source from v0.9.3 with rook v0.9.3.

v0.9.3 chart source incorrectly specifies `extensions` (as tested on k8 v1.12.3) it needed to be changed to `policy` to work with rook v0.9.3. I acknowledge that this issue won't affect future releases (due to pr #2661) but would be an issue if any more v0.9.x releases are planned or the branch needs a patch.

**Comment by travisn** [comment]
@lewismarshall I'm still having a hard time seeing how this affects the v0.9 release. The changes you mentioned would only affect the sources in the `master` branch, which will be part of the v1.0 release. If you're using [these yamls](https://github.com/rook/rook/tree/release-0.9/cluster/examples/kubernetes/ceph) with the v0.9.3 helm chart, I wouldn't expect you'll hit this issue. I would have thought we would see more reports of this issue if it existed in the latest release. Is it possible for you to repro again and share the operator log with the failure?

**Comment by lewismarshall** [comment]
@travisn  - So it turns out I had subtly updated yamls from v0.9.3  - see diff output below where `cluster-rbac-upstream.yaml` are the rbac roles from v0.9.3 and `cluster-rbac.yaml` is our definition:
```
$ diff cluster-rbac.yaml cluster-rbac-upstream.yaml
152,196d151
< ---
< # Allow the default serviceAccount to use the privileged PSP
< apiVersion: rbac.authorization.k8s.io/v1
< kind: RoleBinding
< metadata:
<   name: rook-default-psp
<   namespace: rook-ceph
< roleRef:
<   apiGroup: rbac.authorization.k8s.io
<   kind: ClusterRole
<   name: rook-ceph-system-psp-user
< subjects:
< - kind: ServiceAccount
<   name: default
<   namespace: rook-ceph
< ---
< # Allow the rook-ceph-osd serviceAccount to use the privileged PSP
< apiVersion: rbac.authorization.k8s.io/v1
< kind: RoleBinding
< metadata:
<   name: rook-ceph-osd-psp
<   namespace: rook-ceph
< roleRef:
<   apiGroup: rbac.authorization.k8s.io
<   kind: ClusterRole
<   name: rook-ceph-system-psp-user
< subjects:
< - kind: ServiceAccount
<   name: rook-ceph-osd
<   namespace: rook-ceph
< ---
< # Allow the rook-ceph-mgr serviceAccount to use the privileged PSP
< apiVersion: rbac.authorization.k8s.io/v1
< kind: RoleBinding
< metadata:
<   name: rook-ceph-mgr-psp
<   namespace: rook-ceph
< roleRef:
<   apiGroup: rbac.authorization.k8s.io
<   kind: ClusterRole
<   name: rook-ceph-system-psp-user
< subjects:
< - kind: ServiceAccount
<   name: rook-ceph-mgr
<   namespace: rook-ceph
```

I think I was simplifying what RBAC roles would have been required given the operator rbac roles given by the Chart.  As our next step will be to upgrade the yaml to be in line with the latest release, I'm not sure if I'll get to repo this again - unless testing the update gives any rbac problems given my change.
