### ISSUE TITLE
Optionally collect successful logs from CI integration tests

### ISSUE THREAD

**Issue by travisn** [rook/rook#2856]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Since #2793 merged, I'm finding that when there is a failure, it is a lot more difficult to find the logs with the failure, than the behavior we had before where we only collected logs upon failure. While it is nice to have the successful logs on occasion, I'm wondering if we can do this so that it's still simple to find the failure logs. Here are a couple different possibilities:
- We could revert #2793 and not worry about the successful logs. Troubleshooting the failures is the critical path for CI.
- We could add a new flag to the CI such as `[all logs]` (similar to `[skip ci]`) such that when specified, the Jenkinsfile would pass an arg or env var to the integration tests that would indicate to collect all logs. 

@leseb @ZYecho thoughts?

**Comment by travisn** [comment]
I'm liking the option for `[all logs]` as suggested in the second bullet. Having the option to collect all logs would still be helpful, but to have only the failed logs by default would make troubleshooting the builds much better. The changes for this are likely limited to the [Jenkinsfile](https://github.com/rook/rook/blob/master/Jenkinsfile).

**Comment by sp98** [comment]
@travisn Can you please confirm if my understanding of the requirement is correct ?
- By default, user should only see all logs (GatherAll<>Logs) only when there is a failure. (this would involve reverting the changes made in #2793)
- Also, there would be an '[all logs]' option that would help the user see all the logs (GatherAll<>Logs), even if there is no failure.

**Comment by travisn** [comment]
@sp98 Yes, that sounds good. For the second bullet, it will probably require setting an env var (in the Jenkinsfile) that the tests will look for when they decide whether to collect all logs or only when there are errors
