### ISSUE TITLE
Multiple orchestrations are allowed at the same time

### ISSUE THREAD

**Issue by travisn** [rook/rook#2858]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Multiple orchestrations are allowed at a time, which has undesired side effects.
[This line](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/cluster.go#L148) allows every goroutine to start an orchestration at the same time.

**Expected behavior:**
Only one orchestration should be allowed at a time. Here is a prototype commit that worked locally for me in the integration test, I don't believe it is a complete solution.
https://github.com/travisn/rook/commit/1e463349dbeb3416b9751c8d3e28a7d9b99074e5

We need to call `setOrchestrationPending()` wherever it's intended to trigger an orchestration, such as where the crd is updated, or when a node is added. Looks like that method is not being called in those scenarios.

@shaas can you take a look at this? thanks

**How to reproduce it (minimal and precise):**

- kubectl create -f operator.yaml
- kubectl create -f cluster.yaml
- kubectl create -f filesystem.yaml
- restart the operator pod

There are at least a couple of side effects of the issue:
- Logs are in the operator log that show two orchestrations are happening simultaneously
- As seen in the upgrade integration test, you may see a panic inside the operator pod where the filesystem is not able to access the `clusterInfo` object because it hasn't been initialized since the mons are down. If only one orchestration is allowed, the operator is prevented from proceeding with the filesystem config.

**Comment by shaas** [comment]
> Only one orchestration should be allowed at a time. Here is a prototype commit that worked locally for me in the integration test, I don't believe it is a complete solution.

As you expected, this does not work as the for-loop in `createInstance()` will not get executed a second time (e.g. when adding a node or updating a crd). I will come up with a changed solution.

> We need to call setOrchestrationPending() wherever it's intended to trigger an orchestration, such as where the crd is updated, or when a node is added. Looks like that method is not being called in those scenarios.

All methods which handle CRD changes (`handleUpdate()` & `onAdd()`) or Node changes (`onK8sNodeUpdate()` & `onK8sNodeAdd()`) are calling `createInstance()` which does the `setOrchestrationPending()` call. Am I missing something important?
