### ISSUE TITLE
Ceph: Operator can only access one (colocated) of three mons. 

### ISSUE THREAD

**Issue by rohantmp** [rook/rook#2874]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Ceph can only access the mon with which it shares the host
All mons are up: `[root@rook-ceph-operator-b996864dd-bzl55 /]# ceph -s`
```
  cluster:
    id:     9bbcf85a-28d9-4d3b-8713-dc4a48e4bb32
    health: HEALTH_WARN
            114/681 objects misplaced (16.740%)
            Degraded data redundancy: 113/681 objects degraded (16.593%), 45 pgs degraded, 49 pgs undersized
 
  services:
    mon: 3 daemons, quorum e,f,c
    mgr: a(active)
    osd: 9 osds: 6 up, 6 in; 51 remapped pgs
 
  data:
    pools:   1 pools, 100 pgs
    objects: 227  objects, 458 MiB
    usage:   18 GiB used, 182 GiB / 200 GiB avail
    pgs:     113/681 objects degraded (16.593%)
             114/681 objects misplaced (16.740%)
             51 active+clean+remapped
             45 active+undersized+degraded
             4  active+undersized
```
But I can only ping mon.c. I bring mon.c down or bring the operator up on another node, ceph commands cease to work. mon.c is the mon that is on the same node as the operator.

`[root@rook-ceph-operator-b996864dd-bzl55 /]# ceph ping mon.e`
```
[errno 2] error calling ping_monitor
```
`[root@rook-ceph-operator-b996864dd-bzl55 /]# ceph ping mon.f`
```
[errno 2] error calling ping_monitor
```
`[root@rook-ceph-operator-b996864dd-bzl55 /]# ceph ping mon.c`
```
{
    "health": {
        "checks": {
            "OBJECT_MISPLACED": {
                "severity": "HEALTH_WARN",
                "summary": {
                    "message": "114/681 objects misplaced (16.740%)"

```

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)"
* Kernel (e.g. `uname -a`): 3.10.0-957.5.1.el7.x86_64
* Cloud provider or hardware configuration: vagrant-libvirt
* Rook version (use `rook version` inside of a Rook Pod): v0.9.0-244.gdcd24d3
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): `HEALTH_WARN 114/681 objects misplaced (16.740%); Degraded data redundancy: 113/681 objects degraded (16.593%), 45 pgs degraded, 49 pgs undersized`

(Health is degraded because 1 node has been brought down. There are 2 mons on one of the nodes.)

**Comment by leseb** [comment]
I can't reproduce, could it be an issue with your env?
Have you seen this again recently?

Thanks!

**Comment by rohantmp** [comment]
Looks like it was a problem with my env!
