### ISSUE TITLE
Quick question about the operator

### ISSUE THREAD

**Issue by mjschmidt** [rook/rook#2876]
Should the end state of the operator create a ceph cluster in the ceph-rook ns? Or does this only create the operator, discovery pods, and ceph-agents in the rook-ceph-system namespace.

Thanks!

**Comment by leseb** [comment]
The end state of the operator is to be deployed, running discovery pods and agents. Basically waiting for a CR request. You will only get a cluster if you ask for one via a CR.

**Comment by mjschmidt** [comment]
Thanks!
