### ISSUE TITLE
Set up ceph log directory, with log_to_file disabled

### ISSUE THREAD

**Issue by liewegas** [rook/rook#2881]
Starting in Nautilus, there is a new boolean ``log_to_file`` option that enables or disables logging to a file.

1. On cluster creation, set ``--default-log-to-file=false`` on CLI to each daemon
2. Leave ``log_file`` alone on the command line, so that ceph retains it's default log file names (``/var/log/ceph/$name.log`` inside the container)
3. Bind ``/var/log/ceph/$cluster_namespace`` on the host to ``/var/log/ceph`` in the container.

This will result in an empty and unused log directory, since logging to files is disabled.  However, if a cluster is ever in trouble, or we need to debug, and/or the EFK/ELK stack that normally consumes the logs from stderr is down or broken, we will be able to easily dump standard logs to standard files without jumping through additional hoops.

Note that the ``log_to_file`` option is only available in Nautilus.  If making the above behavior conditional in 1.0 is a challenge, we can backport it to Mimic as well.

**Comment by leseb** [comment]
It seems that `18df18aa4d69232f1e898c99522aad7444c9ff12` commit where `log_to_file` was introduced is not part of the `v14.2.0` tag, so that's difficult to test.

IIUC, `log_to_file` is set to `True` by default, and Rook forces `log_file` to null. We can change that. However, I believe the `ceph.conf` takes precedence over kv flags. So if we remove `log_file` and set `ceph config set global log_to_file false` the monitors will already be logging on files.

So I'm not sure how we can elegantly make this work.

**Comment by liewegas** [comment]
It'll be backported to nautilus shortly

**Comment by liewegas** [comment]
Hmm, yeah, the mons are awkward to bootstrap.  We could set log_to_file=false on teh comand line for the mons until we do the config set command, and then recreate the mon pods...

**Comment by leseb** [comment]
Or detect in Ceph that we run in a container and then apply `log_to_file=false`? Obviously, this has to:

* happen before the daemon starts logging
* only if the kv store does not have a different value
* only if the ceph.conf does not have a different value

Is it possible?

**Comment by liewegas** [comment]
Yeah.. but it's really a rook-behavior, not a container behavior.

Let me think more about this.  It would be nice to have the ability to set something on the commadn line but with a low config priority, so it could still be overridden by the mon.

**Comment by leseb** [comment]
All the containerized deployment of Ceph whether it's orchestrating by k8s or something else agree that logs are collected outside of the containers and that no log should happen inside the container. So I suspect it's safe to assume that's a container behavior.
Alternatively, we can override this with (yet...) another config option? :)

**Comment by liewegas** [comment]
Description updated to use ``--default-log-to-file=false``, which will work once https://github.com/ceph/ceph/pull/27278 merges

**Comment by BlaineEXE** [comment]
@liewegas or @leseb how does Ceph handle flags that it doesn't recognize? Can `--default-log-to-file=false` be specified on the command line for Luminous/Mimic without daemons failing?

**Comment by liewegas** [comment]
> @liewegas or @leseb how does Ceph handle flags that it doesn't recognize? Can `--default-log-to-file=false` be specified on the command line for Luminous/Mimic (or Nautilus 14.2.0) without daemons failing?

I think the result in a warning.  That doesn't help, though, since for older versions we need to do the same ``--log-file=`` thing we do now to turn the logging off the old way.

**Comment by leseb** [comment]
If the flag does not exist Ceph fails with `too many arguments: [--log-to-file=true]`. So my patch adds version support too.
