### ISSUE TITLE
Gather Ceph crash reports

### ISSUE THREAD

**Issue by liewegas** [rook/rook#2882]
When a Ceph daemon crashes, it writes a report to ``/var/lib/ceph/crash/$uniqueid/``.  The ``ceph-crash`` script is normally run by systemd every 10 minutes to scrape any new reports and send them to the monitor/manager.  (See ``ceph crash -h`` for what these look like.)

When deploying with rook, there is no systemd, and these crash reports are lost inside the individual daemon pods.

1. Bind the host ``/var/lib/ceph/$cluster_namespace/crash`` to the container ``/var/lib/ceph/crash``.
2. Rook should run ``ceph-crash -p /var/lib/ceph/$cluster_namespace/crash`` on every host where Rook's Ceph cluster has/had daemons running on a periodic basis.  (Every 10 minutes still sounds like a reasonable default to me.)

**Comment by leseb** [comment]
I think a sidecar container that runs the `ceph-crash` process is acceptable since it's tightened to any Ceph daemon.
The daemon itself scrapes for crash logs every 10 minutes, so we just need to run it forever in a container.

**Comment by liewegas** [comment]
We only need one scraper per host.  Also, we want to scrape even if the daemon pod is killed off for some reason.  I'm a bit worried about the sidecar not capturing that case.

**Comment by leseb** [comment]
Only one? What if we have more than one cluster per host? AFAIU `ceph-crash` needs to know to which `ceph-mgr` it should send out the crashes.

You're right it's probably better to have it outside of the pod, the sidecar has side-effects that might not get captured.
I'm just not sure how we can run that daemon alongside Ceph nodes since they might have different placement policy, running that pod everywhere certainly does not hurt, it's just not sophisticated.

**Comment by liewegas** [comment]
ceph-crash is a one-shot script, not a daemon, if that helps.  Having the 
rook operator do the equivalent of the systemd unit or cron would suffice.  
It would just need to pay attention to the set of all nodes we have had 
pods on during the last interval, and schedule a job every N minutes on 
that set.

**Comment by leseb** [comment]
It's not a daemon but running it with `-d 100000000000000000` makes it scrap for a veeeeeery long time, but after further investigation, it seems it'd be easier to simply rewrite `ceph-crash` scrapping logic in Go and simply call `ceph crash post -i`, the reason being that `ceph-crash` expects a `ceph.conf` to find mons etc and we don't provide any.

I was thinking having a pod running a daemon that scraps forever logs on every machines and then send crash logs whenever we find some.

**Comment by liewegas** [comment]
Yeah, it will need ``mon_host`` and a key, provided either via a file or via the environment.  Whatever works!  I figured a periodic job would be lower overhead but that is probably in the noise.

**Comment by liewegas** [comment]
Some preference for re-using ceph-crash instead of reimplementing, though, just to avoid confusion around multiple implementations of the same thing (trivial as they may be).

**Comment by leseb** [comment]
Yup, in that case, I'll see how we can make `ceph-crash` inheriting options from its parent when calling `ceph crash post`.
