### ISSUE TITLE
Translate node labels into crush_location when creating OSDs

### ISSUE THREAD

**Issue by liewegas** [rook/rook#2883]
There are several standard-ish and not-yet-conventional node labels used to indicate node location, failure domain, and so forth that we should pass through to Ceph so that the CRUSH hierarchy is built properly.

These labels include, on AWS,

- failure-domain.beta.kubernetes.io/region
- failure-domain.beta.kubernetes.io/zone

For bare metal, we might create our own convention, if there is not yet one under kubernetes.io:

- rook.io/rack
- rook.io/room
- rook.io/datacenter

(Alternatively/eventually, we can extend teh kubernetes.io namespace; see https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/)

The goal is that when the OSD pod and OSD are created, the OSD is placed correctly in the CRUSH hierarchy based on these labels.  From Ceph's perspective, this is normally done with a configuration variable like ``crush_location = rack=foo host=bar`` or ``crush_location = region=us-east-1 zone=whatever host=foo``.  That value needs to be present for the OSD the first time it starts up, presumably either via the command line (``--crush-location=rack=foo,row=bar``) or the ``CEPH_ARGS`` environment variable containing the same.

**Comment by mykaul** [comment]
Why can't we extend Kube's?
For example:
failure-domain.beta.kubernetes.io/rack
failure-domain.beta.kubernetes.io/room

(and I'm not sure we need datacenter? I'd argue it's a zone in AWS terms?)

**Comment by liewegas** [comment]
Yeah, extending the kube ones sounds much better!

**Comment by JohnStrunk** [comment]
> Why can't we extend Kube's?
> For example:
> failure-domain.beta.kubernetes.io/rack
> failure-domain.beta.kubernetes.io/room

Labels prefixed w/ DNS names are created specifically to avoid potential naming conflicts (i.e., to provide a namespace owned by a particular entity). We should not unilaterally add labels to the kubernetes.io namespace. That needs to be done as a community decision to avoid conflicts and incompatibilities in the future.

**Comment by liewegas** [comment]
found this: https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/

**Comment by mykaul** [comment]
Yes, of course we need to extend via Kube, not just add - my proposal is to push it via its community.

**Comment by liewegas** [comment]
@childsb ?

**Comment by obnoxxx** [comment]
@jarrpa @humblec - any comments / ideas / inputs?

**Comment by jarrpa** [comment]
This should be fairly doable. I can start asking around and looking into how to get into the API process.

**Comment by childsb** [comment]
@liewegas this sounds like topology aware scheduling:
https://kubernetes.io/blog/2018/10/11/topology-aware-volume-provisioning-in-kubernetes/

**Comment by jarrpa** [comment]
I just looked into this, too, and yeah we could make this work with topology aware provisioning. This would involve Rook setting it's labels on the node objects while coordinating with the Ceph-CSI driver to have it know how to translate the labels into Ceph topology.

**Comment by humblec** [comment]
@childsb @jarrpa afaict, this is different from `topology aware provisioning` , that said, topology aware provisioning lifecycle is mainly on provisioning of a volume/lwhen pod is scheduled. iiu @liewegas's request, the requirement or action of pool creation is before the ( pod/pvc lifecycle or IOW, it is when the pool (crush map) is formed in a cluster.  Please feel free to correct me if I misinterpreted it.

@mykaul as @JohnStrunk mentioned, we should keep away from extending kubernetes.io namespace as its kind of reserved for inbuilt/intree usage and not meant for external consumers.

**Comment by liewegas** [comment]
> @mykaul as @JohnStrunk mentioned, we should keep away from extending kubernetes.io namespace as its kind of reserved for inbuilt/intree usage and not meant for external consumers.

Bare metal location properties like rack, room, or datacenter seem like generic properties--more generic than aws zone and region--and perfect candidates for extending the kubernetes.io namespace.  I think key point is that the first step to doing so is probably a pull request to the kubernetes documentation to add them.

We can use a rook.io property in the meantime until that happens, or just start with the existing zone/region properties to start.

**Comment by mykaul** [comment]
Now that I'm reading again the topology aware provisioning - if we wait for the pod to be scheduled, it's up to use to create the PV properly, in the right location:
```
Topology specification is generalized and uses a similar label-based specification like in Pod nodeSelectors and nodeAffinity. This mechanism allows you to define your own topology boundaries, such as racks in on-premise clusters, without requiring modifications to the scheduler to understand these custom topologies.
```
So if the PVC waits for the PV to be scheduled, I *think* we might be OK.
It just sounds all backwards to me - the POD should be scheduled next to where its storage, not the other way around ;-)

Does that mean we can and should use Rook/Ceph specific specifications to configure our CRUSH map so pools will be in a specific affinity? Otherwise, I don't understand how we can do that.

**Comment by jarrpa** [comment]
I'm with @liewegas in that the on-prem properties are generic enough to be of use to the scheduler as well. However, there is the concern of where we draw the line on what level of tags to define. "rack" and "datacenter" may both apply to most cases, but "room" might not and some may want something like "row".

While there is a distinction between provisioning and storage topology, I believe there's nothing to say we couldn't update the CRUSH map based on new information coming in from Pods requesting volumes on new nodes.

> Does that mean we can and should use Rook/Ceph specific specifications to configure our CRUSH map so pools will be in a specific affinity? Otherwise, I don't understand how we can do that.

I'm not sure the idea of trying to play games with colocating storage to compute is of much benefit to us. I see two scenarios in which we could make use of this for provisioning:

1. Given a node in a given zone, replicate the data to nodes in at least one or two other zones.
2. Given a distributed application (e.g. DaemonSet), replicate data such that each node will always have a copy in its zone.

**Comment by mykaul** [comment]
@jarrpa - another use case:
3. Restrict replication to a specific rack / room / data-center / zone, to avoid inter rack / room / data-center / zone traffic. Or if a melt-down in a specific rack occurs (TOR switch dies), only specific pools are unavailable, etc.

**Comment by JohnStrunk** [comment]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/container-storage-interface.md provides an in-depth discussion of topology for CSI & kubernetes. The doc seems to be written from an "accessibility" standpoint--- This is understandable as that's what the cloud providers need it for.

An interesting question is if/how we could use this for our purposes of deploying/configuring the storage system.

At first look, I think it'll work for us... mirroring the topologies into the crush map and returning volumes from CSI that are essentially "you can access this from anywhere". By restricting the location, we could pull the workload to the storage, or, with the late binding, do the opposite at provisioning time.

As a benefit, we could use these labels to permit limited movement of OSDs across hosts once we move to raw block PVs in environments w/ movable back end storage.

**Comment by childsb** [comment]
> So if the PVC waits for the pod to be scheduled first, I think we might be OK.
It just sounds all backwards to me - the POD should be scheduled next to where its storage, not the other way around

To provide some history..... The reason for this design is that it guarantees that a POD is initially 
scheduleable to a node with available resources. With traditional DP/binding a nodes compute resources may be consumed in the time between PV provision, bind and POD use resulting in a POD that can't be scheduled.  Its especially a problem for local storage, but still a common issue for other topologies... It's an almost guaranteed problem in near capacity clusters.

Other designs (like reserving resources on a node) were discussed but untenable.

**Comment by liewegas** [comment]
I don't think the topology-aware scheduling is necessarily that helpful for us, except in the (somewhat) special case where we have localized pools.  That is going to be rare in all but large clusters.  In most cases, the pools will be spread across the entire cluster.

But this is all unrelated to this issue!

The only goal here is to pass any metadata that kube has about the physical layout of the cluster down to Ceph.  That's it.  Until we do that, none of the rest of this discussion is relevant at all.

**Comment by jarrpa** [comment]
> The only goal here is to pass any metadata that kube has about the physical layout of the cluster down to Ceph. That's it. Until we do that, none of the rest of this discussion is relevant at all.

Best I know the only way kube exposes that is via node labels. Currently I believe that the only cloud providers that provide any topology information are AWS and GCE. I'm considering submitting a proposal whereby cloud/platform providers could provide their own arbitrary topology information. It would then be up to the application developer and admin to know about and understand these labels (to use them, for example) in node affinity/anti-affinity).

The catch there is that while kube sends the full node object to the provisioner, in our case that information goes to the external-provisioner sidecar container which filters the labels based on the topology entries for the specific CSI driver found in the node's corresponding CSINode object. So we'd either have to have Rook map the kube topology labels into labels the CSI driver understands or see if we could request the external-provisioner pass through the kube topology labels as well.

**Comment by jarrpa** [comment]
After talking with @liewegas for a bit, I now have a better understanding of how CRUSH maps use crush_location and how they are configured. Sounds like it should be fairly straightforward, I can take this on and look into it.

**Comment by mykaul** [comment]
@jarrpa - any updates?

**Comment by jarrpa** [comment]
None at this time.
