### ISSUE TITLE
Improve Ceph upgrade pod recreation gates

### ISSUE THREAD

**Issue by liewegas** [rook/rook#2889]
When doing an upgrade, each pod is recreated with the updated image.  We should gate each pod recreate with the Ceph status to make sure we are giving Ceph enough time to settle between these restarts.

For monitor, restarts are fast, so it is usually not an issue.  However, we have a new command pending ``ceph mon ok-to-stop <id>`` to check whether stopping a given monitor will break quorum.  Sometimes that is necessary (e.g., if there is only 1 mon), but when there are 3 or more, we should be more gentle and wait between mon restarts.

For the mgr, no check is necessary--just restart the mgr pods.

For OSDs, we need to be careful.  There is an existing command, ``ceph osd ok-to-stop`` that checks whether stopping the given OSD will make any data go unavailable.  We should (generally) wait for this to become true.  Note, however, that if there are pools with 1 replica, or the cluster is degraded for other reasons, it may never become true, so we may want to have a 'force' mode, or have it proceed anyway if a timeout expires.

For MDSs, a new command is pending ``ceph mds ok-to-stop <id>``.

radosgw is stateless--restarting one at a time should be sufficient.

Same for rbd-mirror.

**Comment by leseb** [comment]
I guess, the only thing missing is a reasonable timeout for OSDs :). Is it really safe pursuing anyway if the number of PGs never settles?

**Comment by rohantmp** [comment]
I think it would be very useful to have an `ok-to-stop` for any level on the osd tree. Especially host. It would be the perfect for node level disruptions like kernel upgrade or fencing.

**Comment by liewegas** [comment]
@rohan47 that's a good point.  The current ok-to-stop command takes a list of OSDs, so you can currently do ``ceph osd ok-to-stop $(ceph osd crush ls $HOSTNAME)``.  This could be collapsed into a single command, perhaps.  Note that that also only covers the OSDs (which, to be fair, are usually the primary concern). Perhaps a host-level check for all daemons that checks whether a host restart is safe would nice.

**Comment by rohantmp** [comment]
@liewegas That command combination fulfils the exact function I was thinking of. Thanks!

P.S. I'm @rohantmp :P
