### ISSUE TITLE
Add crushDeviceClass pool property

### ISSUE THREAD

**Issue by liewegas** [rook/rook#2890]
The CephPool CRD (and probably others?) currently has ``crushRoot`` and ``failureDomain`` properties.  Add a ``crushDeviceClass`` or ``deviceClass`` to go with this.  This ultimately should map to the ``ceph osd crush rule create-* ...`` command, which takes a device class argument.

**Comment by hdave** [comment]
Would this ultimately result in multiple storage classes in k8s?  We are looking to have at least two -- for example:  `StorageClass:  nvme-retain` and maybe `StorageClass:  sata-retain`

If so, I give this issue a big +1.

**Comment by travisn** [comment]
Yes, a storage class maps to a single ceph pool (unless you're using erasure coding, in which case there are two pools for a storage class).

**Comment by sp98** [comment]
One query: 
Is there any difference between "create-simple" and "create-replicated" in "ceph osd crush rule create-*" command [here](https://github.com/rook/rook/blob/05b0166e4d2a1ab2dbdc0cb51a7c1ae8886d35e0/pkg/daemon/ceph/client/pool.go#L257)  ?
(Currently the code base uses "create-simple" but I think that option does not support device classes. I changed that to "create-replicated" and it works. )

**Comment by noahdesu** [comment]
It looks to me that if the optional device-class parameter is not specified when using `create-replicated` then it is equivalent to using `create-simple` with a fixed `firstn` mode. The use case you cited above is appears to be using the default mode (`firstn`), so I think your substitution of `create-simple` with `create-replicated` is correct. @liewegas ?

**Comment by liewegas** [comment]
> It looks to me that if the optional device-class parameter is not specified when using `create-replicated` then it is equivalent to using `create-simple` with a fixed `firstn` mode. The use case you cited above appears to be using the default mode (`firstn`), so I think your substitution of `create-simple` with `create-replicated` is correct. @liewegas ?

Agree!
