### ISSUE TITLE
mgr-pod, pod-osd not created in rook-ceph namespace with cluster-minimal

### ISSUE THREAD

**Issue by AsherShoshan** [rook/rook#2898]
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
Ability to create pvc

**How to reproduce it (minimal and precise):**
kubectl create -f cluster-minimal.yaml

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2023.5.0
VERSION_ID=2023.5.0
BUILD_ID=2019-03-09-0138
PRETTY_NAME="Container Linux by CoreOS 2023.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

* Kernel (e.g. `uname -a`):
Linux rose02 4.19.25-coreos #1 SMP Sat Mar 9 01:05:06 -00 2019 x86_64 Intel(R) Xeon(R) CPU E31280 @ 3.50GHz GenuineIntel GNU/Linux

* Cloud provider or hardware configuration:
NA
* Rook version (use `rook version` inside of a Rook Pod):
rook: v0.9.0-329.gc696ce2

* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox]
(https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by melosalz** [comment]
any update? met the same issue

**Comment by travisn** [comment]
If the mgr is not starting, there must be an issue forming the mon quorum. Please see the [troubleshooting guide](https://rook.io/docs/rook/v1.0/ceph-common-issues.html#monitors-are-the-only-pods-running) to see what might be happening with the mons. 

When cluster-minimal.yaml is created, it is actually not expected to create any OSDs as seen [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-minimal.yaml#L2). This is really a scenario for using the dashboard to configure the cluster, which still a work in progress. If your goal is to only use the dashboard to configure the cluster, use cluster-minimal.yaml. If your goal is to immediately have a cluster that can provision PVCs, use another yaml. See [the examples](https://rook.io/docs/rook/v1.0/ceph-examples.html) for more details.
