### ISSUE TITLE
Can't delete name spaces 

### ISSUE THREAD

**Issue by paulmorabito** [rook/rook#2912]
Hi,

I ran through the rook and ceph quick start guide and ended up adding a node and also removing one in my Rancher K8S cluster (Rancher 2.20 and kubernetes 1.13.4). The rook cluster pods were all failing so I thought I would remove my cluster and re-add as it was only being used for evaluation and only on one deployment.

I ran through the remove instructions and can confirm the PV, PVC, CRD etc. is all deleted.  However, I can't remove the two created name spaces. They are stuck at terminating.

If I edit the namespace, the only finalizer is Kubernetes which if I remove seems to do nothing. The name space is still stuck at terminating and the kubernetes finalizer is re-added.

Is there anything else I can check or do to remove this?

**Comment by aland-zhang** [comment]
exec   kubectl -n rook-ceph patch cephclusters.ceph.rook.io rook-ceph -p '{"metadata":{"finalizers": []}}' --type=merge

**Comment by paulmorabito** [comment]
paul@s:~$ exec kubectl -n rook-ceph patch cephclusters.ceph.rook.io
rook-ceph -p '{"metadata":{"finalizers": []}}' --type=merge
error: the server doesn't have a resource type "cephclusters"

Name spaces are still there.

**Comment by paulmorabito** [comment]
kubectl get ns | grep Terminating | awk '{print $1}' | gxargs  -n1 -- bash -c 'kubectl get ns "$0" -o json | jq "del(.spec.finalizers[0])" > "$0.json"; curl -k -H "Content-Type: application/json" -X PUT --data-binary @"$0.json" "http://127.0.0.1:8001/api/v1/namespaces/$0/finalize" '

This worked.

**Comment by ClareChu** [comment]
```bash
kubectl -n rook-ceph patch cephclusters.ceph.rook.io rook-ceph -p '{"metadata":{"finalizers": []}}' --type=merge
```
