### ISSUE TITLE
Helm chart support for csi drivers

### ISSUE THREAD

**Issue by mmack** [rook/rook#2913]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Install CSI version of ceph / rook

**Environment**:

**Comment by kfox1111** [comment]
Does it need anything that these https://hub.helm.sh/charts?q=ceph-csi don't provide?

**Comment by travisn** [comment]
This should just be a matter of adding the csi settings to the operator as seen [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator-with-csi.yaml#L43-L54). When these become the default in operator.yaml, they will also be set in the rook-ceph helm chart. This is expected with the 1.1 release.

**Comment by kfox1111** [comment]
Is it possible to have the rook-ceph helm chart just depend on the ceph-csi chart directly rather then load up the driver out of band?

**Comment by travisn** [comment]
The current approach is that when the operator starts, it should start related components so things work out of the box with a supported version, making it so the admin shouldn't have to worry about an extra step for the csi driver configuration. If the csi driver configuration is separate, it's another possibility for misconfiguration and headache. Do you have a suggestion for how to keep it independent, yet simple? We need to also consider users who aren't using helm charts. Thanks!

**Comment by travisn** [comment]
The CSI driver was already added to the helm chart in v1.1

**Comment by kfox1111** [comment]
Its more of a question of auditability/security. If the helm chart launches the driver, you can easily peak at what the chart will load and see. With the operator, you can't see what its going to do until after its done. I get that that has other benefits. Its a tradeoff between visibility though and flexibility. I'm thinking the driver doesn't need the operator level of flexibility?

**Comment by travisn** [comment]
@kfox1111 If you look at all the yamls under the [template folder](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph/csi/template) you can see what variables can be substituted. The configurable settings are exposed to the [helm settings](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/values.yaml#L53-L85). 

If you don't want rook to install the CSI driver there are settings that will tell Rook to not enable it: `enableRbdDriver` and `enableCephFSDriver`, then you could install the CSI driver separately.

**Comment by kfox1111** [comment]
This is kind of one of those philosophical questions that hasn't been answered in the k8s community yet. Installation.

In Windows, they use to use an "installer" for everything. A piece of Turing complete software to install other software. It was really hard to see what it was going to do, and harder to ensure when removed that it would totally clean up after itself.

Linux machines went to package management, where the package in most cases is not software but a description of the software to install. An admin can inspect the package and know exactly what is going to do and know in most cases that it will uninstall cleanly. Even windows I think has started moving this direction (msi's)

An operator is more like the windows installer and helm like the package.

There's a time and a place for a full windows installer. But most things are more secure if can be done in a package.
----
Being able to look at the source code is helpful, but harder then a chart to verify that it actually is going to do whats in the templates.

Being able to turn off the operator doing it is a good start. Can then launch the chart independently. If then the csi chart was added as an optional dep in the helm chart, then it would be easier still. The rook-ceph chart could contain the default values for launching the driver configured in a rook listening mode. That would be easier still.

Being able to separate the permissions of:
 * what can be done at install time with the installers credentials
vs
 * what can be done at runtime by the operator
Makes for a more secure system. Perhaps the rbac role of the operator can be tightened up significantly if the really security sensitive part (csi driver) is outside its control.
