### ISSUE TITLE
Ceph core dumps trying to compile crush map

### ISSUE THREAD

**Issue by alfredodeza** [rook/rook#2914]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** Rook fails to compile the crush map, causes Ceph to core dump:

    2019-03-29 12:26:03.777311 I | exec: Running command: ceph mon_status --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/166094062
    2019-03-29 12:26:05.823858 I | op-mon: Monitors in quorum: [a b c]
    2019-03-29 12:26:05.827845 I | op-cluster: creating initial crushmap
    2019-03-29 12:26:05.828063 I | cephclient: setting crush tunables to firefly
    2019-03-29 12:26:05.828197 I | exec: Running command: ceph osd crush tunables firefly --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format plain --out-file /tmp/061645173
    2019-03-29 12:26:06.529695 I | exec: adjusted tunables profile to firefly
    2019-03-29 12:26:06.529897 I | cephclient: succeeded setting crush tunables to profile firefly: 
    2019-03-29 12:26:06.530154 I | exec: Running command: crushtool -c /tmp/716323920 -o /tmp/165398383
    2019-03-29 12:26:07.334912 E | op-cluster: failed to create cluster in namespace rook-ceph. failed to create initial crushmap: failed to create initial crushmap: failed to compile crushmap from /tmp/716323920: Failed to complete '': signal: aborted. *** Caught signal (Aborted) **
     in thread 7f0eb8f7ed40 thread_name:crushtool
     ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)
     1: (()+0x12d80) [0x7f0eae5add80]
     2: (gsignal()+0x10f) [0x7f0eaca4d93f]
     3: (abort()+0x127) [0x7f0eaca37c95]
     4: (()+0x2d0fb8) [0x7f0eb01dffb8]
     5: (()+0x6d19b3) [0x7f0eb05e09b3]
     6: (CrushCompiler::parse_bucket(__gnu_cxx::__normal_iterator<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> >*, std::vector<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> >, std::allocator<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> > > > > const&)+0x163c) [0x7f0eb06f889c]
     7: (CrushCompiler::parse_crush(__gnu_cxx::__normal_iterator<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> >*, std::vector<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> >, std::allocator<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> > > > > const&)+0x160) [0x7f0eb06f9000]
     8: (CrushCompiler::compile(std::istream&, char const*)+0x10f0) [0x7f0eb06fb230]
     9: (main()+0x1aea) [0x55f829b50f7a]
     10: (__libc_start_main()+0xf3) [0x7f0eaca39813]
     11: (_start()+0x2e) [0x55f829b5588e]
    2019-03-29 12:26:07.314 7f0eb8f7ed40 -1 *** Caught signal (Aborted) **
     in thread 7f0eb8f7ed40 thread_name:crushtool
     ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)
     1: (()+0x12d80) [0x7f0eae5add80]
     2: (gsignal()+0x10f) [0x7f0eaca4d93f]
     3: (abort()+0x127) [0x7f0eaca37c95]
     4: (()+0x2d0fb8) [0x7f0eb01dffb8]
     5: (()+0x6d19b3) [0x7f0eb05e09b3]
     6: (CrushCompiler::parse_bucket(__gnu_cxx::__normal_iterator<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> >*, std::vector<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> >, std::allocator<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> > > > > const&)+0x163c) [0x7f0eb06f889c]
     7: (CrushCompiler::parse_crush(__gnu_cxx::__normal_iterator<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> >*, std::vector<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> >, std::allocator<boost::spirit::tree_node<boost::spirit::node_val_data<char const*, boost::spirit::nil_t> > > > > const&)+0x160) [0x7f0eb06f9000]
     8: (CrushCompiler::compile(std::istream&, char const*)+0x10f0) [0x7f0eb06fb230]
     9: (main()+0x1aea) [0x55f829b50f7a]
     10: (__libc_start_main()+0xf3) [0x7f0eaca39813]
     11: (_start()+0x2e) [0x55f829b5588e]
     NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
    --- begin dump of recent events ---
       -22> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command assert hook 0x55f82ac98be0
       -21> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command abort hook 0x55f82ac98be0
       -20> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command perfcounters_dump hook 0x55f82ac98be0
       -19> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command 1 hook 0x55f82ac98be0
       -18> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command perf dump hook 0x55f82ac98be0
       -17> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command perfcounters_schema hook 0x55f82ac98be0
       -16> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command perf histogram dump hook 0x55f82ac98be0
       -15> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command 2 hook 0x55f82ac98be0
       -14> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command perf schema hook 0x55f82ac98be0
       -13> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command perf histogram schema hook 0x55f82ac98be0
       -12> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command perf reset hook 0x55f82ac98be0
       -11> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command config show hook 0x55f82ac98be0
       -10> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command config help hook 0x55f82ac98be0
        -9> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command config set hook 0x55f82ac98be0
        -8> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command config unset hook 0x55f82ac98be0
        -7> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command config get hook 0x55f82ac98be0
        -6> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command config diff hook 0x55f82ac98be0
        -5> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command config diff get hook 0x55f82ac98be0
        -4> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command log flush hook 0x55f82ac98be0
        -3> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command log dump hook 0x55f82ac98be0
        -2> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command log reopen hook 0x55f82ac98be0
        -1> 2019-03-29 12:26:07.269 7f0eb8f7ed40  5 asok(0x55f82ac564d0) register_command dump_mempools hook 0x55f82aca2258
         0> 2019-03-29 12:26:07.314 7f0eb8f7ed40 -1 *** Caught signal (Aborted) **
     in thread 7f0eb8f7ed40 thread_name:crushtool
     ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)

**Expected behavior:**

**How to reproduce it (minimal and precise):** This happens while trying to deploy on OpenShift. 

**Environment**:
Rook Images built from master at sha: e28278578e2a712d67277d69e33951474d0d8515
rook image: docker-pullable://internal-registry/ceph/rook@sha256:62a3535ef5a5a5f7e7ffb64a8689ff9c553f3e7e5c5d34ccbabcb42209ae4293
rook version:  rook: 0.9.0-331.gdb218e42
rook package version: rook-0.9.0-331.gdb218e42.el8cp.x86_64

ceph image: docker-pullable://internal-registry/ceph/rhceph-4-rhel8@sha256:1b2154ef9552911a5a1b66695bd259698fb27c0bd10259dbcc8420d4f96d1f24
ceph version: ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)
ceph package version: ceph-common-14.2.0-0.el8cp.x86_64

minishift version: minishift v1.31.0+cfc599c
openshift image: docker-pullable://docker.io/openshift/origin-hypershift@sha256:dacc9d13c4cea6c72ea85445e00305a4d0b58acd1bff3ae18656240e7a5a4b0a
oc version:
  oc v3.11.0+0cbc58b
  kubernetes v1.11.0+d4cacc0
  features: Basic-Auth GSSAPI Kerberos SPNEGO
  
  Server https://192.168.42.229:8443
  kubernetes v1.11.0+d4cacc0

The following changes to operator.yml:

`ROOK_ALLOW_MULTIPLE_FILESYSTEMS`
`ROOK_HOSTPATH_REQUIRES_PRIVILEGED`

To cluster.yml we set the custom container locations for Rook and Ceph, so we have to do:

`allowUnsupported: true`

And because we use OpenShift, we call `create scc.yaml`.  Other than that, everything is else is vanilla files from rook.git

**Comment by travisn** [comment]
@alfredodeza Everything in your config sounds like a standard openshift deployment. There is no expected/known reason that we would be seeing the coredump. The one variable that looks different from other working deployments is the rhel8 base image. 
- Is this the first time running `crushtool` on rhel8? Or do we have other test environments on rhel8?
- Any chance we have a ceph-container build on rhel8 where we could compare if the same behavior is seen?
- Can we get the full stack trace in the core dump?

**Comment by alfredodeza** [comment]
I would assume this is the first time running crushtool on rhel8, other distros are fine (haven't been able to replicate).

How can we produce a full stack trace? What can we add to our job to get this?

**Comment by ktdreyer** [comment]
We are tracking the crushtool bug at http://tracker.ceph.com/issues/39174

The way that we debugged this was to run `crushtool` entirely outside of Rook (or containers), so we could manually capture backtraces. For the next Ceph crash we are not going to be that lucky; imagine if it was an Mon/OSD/Mgr crash.

This issue shows us we need a standard procedure for capturing Ceph crash information inside a running Rook cluster.

Alfredo do you think this is something ceph-medic should do, or where should we focus our efforts on this?

**Comment by alfredodeza** [comment]
@ktdreyer ceph-medic should just limit to capture runtime details of a ceph cluster, I think that capturing core dumps is a bit out of scope. 

I am not sure what could be done here. @travisn isn't there something that Ceph already has for capturing these? I can't remember if this is a systemd unit or something else that can capture and store
