### ISSUE TITLE
no osd or osd prepare pods  can be created, only ceph mon pods created

### ISSUE THREAD

**Issue by dazhaoyu** [rook/rook#2916]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804
* Kernel (e.g. `uname -a`): 3.10.0-862.el7.x86_64
* Cloud provider or hardware configuration: one k8s master and two k8s nodes
* Rook version (use `rook version` inside of a Rook Pod): Rook 1.0 master
* Kubernetes version (use `kubectl version`):  v1.13.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): no, just kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

the below is my step for deploy rook:
1. k8s nodes info: k8s-master, k8s-node1, k8s-node2
2. add sdb disk(30G), and "sgdisk --zap /dev/sdb", make sure "lsblk" can found sdb disk.
3. git clone https://github.com/rook/rook.git
4. cd rook/cluster/examples/kubernetes/ceph/
5. kubectl apply -f operator.yaml
6. edit cluster.yaml as attached file
[cluster-test.txt](https://github.com/rook/rook/files/3032111/cluster-test.txt)
7. kubectl apply -f cluster-test.yaml
8 use kubectl -n rook-ceph get pods command, only ceph-mon pods can be created, no osd\ceph mgr pods.

**Comment by dazhaoyu** [comment]
![image](https://user-images.githubusercontent.com/13358163/55379338-5c403580-554f-11e9-9b19-0d5a645c997e.png)
from ceph-operator logs， always have “Cluster connection interrupted or timed out” message

**Comment by mingxingshi** [comment]
`git checkout -b release-0.9 remotes/origin/release-0.9`<br>and then try to deploy again

**Comment by dazhaoyu** [comment]
> `git checkout -b release-0.9 remotes/origin/release-0.9`
> and then try to deploy again

hi  ming，
     I checkout the rook to release-0.9， after “create cluster.yaml”,  still not osd pods, only one mon pod be created, so could you  share your step and cluster.yaml info?

**Comment by mingxingshi** [comment]
**My steps are as follows, only for reference：**
### My k8s env:

hostname | OS | IP | Storage device
-- | -- | -- | --
Huawei-0001 | CentOS 7.5 64bit | 172.16.192.127 |  
Huawei-0002 | CentOS 7.5 64bit | 172.16.192.25 |  
Huawei-0003 | CentOS 7.5 64bit | 172.16.192.121 |  
Huawei-0004 | CentOS 7.5 64bit | 172.16.192.243 | /dev/vdb
Huawei-0005 | CentOS 7.5 64bit | 172.16.192.226 | /dev/vdb
```
[root@huawei-0001 ~]# kubectl get nodes
NAME             STATUS    ROLES     AGE       VERSION
172.16.192.121   Ready     master    3d        v1.11.1
172.16.192.127   Ready     master    3d        v1.11.1
172.16.192.226   Ready     node      3d        v1.11.1
172.16.192.243   Ready     node      3d        v1.11.1
172.16.192.25    Ready     master    3d        v1.11.1
```

### Enable ip_forward in all nodes:
```
cat <<EOF >  /etc/sysctl.d/ceph.conf
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system
```
### Label the nodes that will run ceph-mon:
`kubectl label nodes {172.16.192.243,172.16.192.226} ceph-mon=enabled`
### Label the nodes that will run ceph-osd:
`kubectl label nodes {172.16.192.243,172.16.192.226} ceph-osd=enabled`
### Label the node that will run ceph-mgr:
`kubectl label nodes 172.16.192.243 ceph-mgr=enabled`

### Deploy operator:
```
git clone https://github.com/rook/rook.git
cd rook
git checkout -b release-0.9 remotes/origin/release-0.9
cd cluster/examples/kubernetes/ceph
# edit operator.yaml if you need
kubectl create -f operator.yaml
```
[operator.zip](https://github.com/rook/rook/files/3037455/operator.zip)

### Deploy cluster:
```
kubectl apply -f cluster.yaml
```

[cluster.zip](https://github.com/rook/rook/files/3037470/cluster.zip)

**Comment by dazhaoyu** [comment]
install as provided steps,  still only mon pods can be created,  I dont not know why, I gave up to use rook.

**Comment by travisn** [comment]
@dazhaoyu Did you try [the common issues page](https://rook.io/docs/rook/v0.9/common-issues.html) to troubleshoot why the osds weren't starting? The most common issue is a networking issue for the operator pod to connect to the mons. If using host networking, the firewall might be blocking the ports, or if you have a network plugin that blocks access across namespaces, you would need to enable it.

**Comment by ben-le** [comment]
The issue is still existing; the operator.yaml and cluster.yaml files provided by @mingxingshi do not resolve the issue.

**Comment by travisn** [comment]
@ben-le This is typically an environmental issue where the networking needs to be configured differently. There is not a general known issue with OSDs not being created. Did you try the common issues page linked above?

**Comment by ben-le** [comment]
@dazhaoyu to resolve the issue; you just need to replace the IP addresses with hostnames in your cluster.yaml file
