### ISSUE TITLE
Operator 0.9.3 not starting 

### ISSUE THREAD

**Issue by holoGDM** [rook/rook#2919]
Im trying to start operator on kubernetes 1.14 cluster. When i will start opertator.yaml (without changes from 0.9.3 ceph example) im getting such error:

```
[root@kube00 ceph]# kubectl logs rook-ceph-operator-d97564799-jdt99 -f -n rook-ceph-system
2019-04-02 16:40:07.428258 I | rookcmd: starting Rook v0.9.3 with arguments '/usr/local/bin/rook ceph operator'
2019-04-02 16:40:07.428350 I | rookcmd: flag values: --alsologtostderr=false, --help=false, --log-level=INFO, --log_backtrace_at=:0, --log_dir=, --logtostderr=true, --mon-healthcheck-interval=45s, --mon-out-timeout=10m0s, --stderrthreshold=2, --v=0, --vmodule=
2019-04-02 16:40:07.430700 I | cephcmd: starting operator
failed to get pod. Get https://10.96.0.1:443/api/v1/namespaces/rook-ceph-system/pods/rook-ceph-operator-d97564799-jdt99: dial tcp 10.96.0.1:443: i/o timeout

[root@kube00 ceph]# 
```

On our other 1.14 it is working as it should. Why on that new one it doesn't?

**Comment by galexrt** [comment]
@holoGDM The error is about the operator being unable to talk to the Kubernetes API server.
Are you using NetworkPolicies that block traffic to the apiserver? Is your Kubernetes internal network working?

You can use https://github.com/apprenda/kuberang to verify the Kubernetes cluster network.

**Comment by holoGDM** [comment]
@galexrt I just figure it out. It was not Rook problem but my OS configuration. Im using Kubernetes with systemd-networkd and there was need to add to all .network files IPForward option like in bellow example .network file:

```
[root@kube00 kubernetes-prep]# cat /etc/systemd/network/vlan31.network 
[Match]
Name=vlan31

[Network]
VLAN=vlan31
IPForward=1

[Address]
Address=10.10.0.250/24

[Route]
Destination=0.0.0.0/0
Gateway=10.10.0.5
[root@kube00 kubernetes-prep]# 
```
systemd-networkd without that option will force interface to disable forwarding even if you will set it globally or for interface with sysctl. Now my syscalls looks like that:

```
net.ipv4.conf.all.forwarding = 1
net.ipv4.conf.bond0.forwarding = 1
net.ipv4.conf.cali4a36a9905a5.forwarding = 1
net.ipv4.conf.calid356aef822a.forwarding = 1
net.ipv4.conf.calif84735c2ec4.forwarding = 1
net.ipv4.conf.default.forwarding = 1
net.ipv4.conf.docker0.forwarding = 1
net.ipv4.conf.eno1.forwarding = 1
net.ipv4.conf.eno2.forwarding = 1
net.ipv4.conf.eno3.forwarding = 1
net.ipv4.conf.eno4.forwarding = 1
net.ipv4.conf.lo.forwarding = 1
net.ipv4.conf.tunl0.forwarding = 1
net.ipv4.conf.vlan31.forwarding = 1

```

**Comment by rohantmp** [comment]
Can we close this?
