### ISSUE TITLE
Ceph RBD PVC Pending forever

### ISSUE THREAD

**Issue by tbe** [rook/rook#2922]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After creating a new PVC, the controller provisions the PV instand:

```
2019-04-03 00:29:12.802031 I | op-provisioner: creating volume with configuration {blockPool:dbmspool clusterNamespace:rook-ceph fstype:xfs dataBlockPool:}
2019-04-03 00:29:12.802087 I | exec: Running command: rbd create dbmspool/pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33 --size 477 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
I0403 00:29:12.802170       6 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"consul", Name:"traefik-consul-data-consul-0", UID:"7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33", APIVersion:"v1", ResourceVersion:"31659", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "consul/traefik-consul-data-consul-0"
2019-04-03 00:29:13.222385 I | op-provisioner: Rook block image created: pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33, size = 500000000
2019-04-03 00:29:13.224041 I | op-provisioner: successfully created Rook Block volume &FlexPersistentVolumeSource{Driver:ceph.rook.io/rook-ceph-system,FSType:xfs,SecretRef:nil,ReadOnly:false,Options:map[string]string{clusterNamespace: rook-ceph,dataBlockPool: ,image: pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33,pool: dbmspool,storageClass: ceph-dbms,},}
I0403 00:29:13.224115       6 controller.go:1026] provision "consul/traefik-consul-data-consul-0" class "ceph-dbms": volume "pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33" provisioned
I0403 00:29:13.224151       6 controller.go:1040] provision "consul/traefik-consul-data-consul-0" class "ceph-dbms": trying to save persistentvolume "pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33"
I0403 00:29:13.371878       6 controller.go:1047] provision "consul/traefik-consul-data-consul-0" class "ceph-dbms": persistentvolume "pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33" saved
I0403 00:29:13.371948       6 controller.go:1088] provision "consul/traefik-consul-data-consul-0" class "ceph-dbms": succeeded
I0403 00:29:13.372053       6 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"consul", Name:"traefik-consul-data-consul-0", UID:"7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33", APIVersion:"v1", ResourceVersion:"31659", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33
```

But the PV and PVC stay pending forever:
```
Name:          traefik-consul-data-consul-0
Namespace:     consul
StorageClass:  ceph-dbms
Status:        Pending
Volume:        
Labels:        app=consul
               component=server
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ceph.rook.io/block
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason                 Age                     From                                                                                        Message
  ----       ------                 ----                    ----                                                                                        -------
  Normal     Provisioning           9m31s                   ceph.rook.io/block_rook-ceph-operator-64696dcb4-5x2bw_1f996ddc-55a7-11e9-9220-62d0547a0827  External provisioner is provisioning volume for claim "consul/traefik-consul-data-consul-0"
  Normal     ProvisioningSucceeded  9m30s                   ceph.rook.io/block_rook-ceph-operator-64696dcb4-5x2bw_1f996ddc-55a7-11e9-9220-62d0547a0827  Successfully provisioned volume pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33
  Normal     ExternalProvisioning   3m46s (x26 over 9m31s)  persistentvolume-controller                                                                 waiting for a volume to be created, either by external provisioner "ceph.rook.io/block" or manually created by system administrator
Mounted By:  consul-0
$ kubectl -n consul describe pv pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33
Name:            pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: ceph.rook.io/block
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    ceph-dbms
Status:          Pending
Claim:           consul/traefik-consul-data-consul-0
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        476Mi
Node Affinity:   <none>
Message:         
Source:
    Type:       FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
    Driver:     ceph.rook.io/rook-ceph-system
    FSType:     xfs
    SecretRef:  nil
    ReadOnly:   false
    Options:    map[pool:dbmspool storageClass:ceph-dbms clusterNamespace:rook-ceph dataBlockPool: image:pvc-7fb1a5d6-55a7-11e9-b595-0cc47a9b4b33]
Events:         <none>
```

**Expected behavior:**
The PVC becomse availible

**How to reproduce it (minimal and precise):**
Create a PVC having a storage class managed by rook-ceph

Maybe related to #2833

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): 4.18.0-16-generic
* Cloud provider or hardware configuration:  rook: 
* Rook version (use `rook version` inside of a Rook Pod): v0.9.3
* Kubernetes version (use `kubectl version`): 1.14.0, 1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare Metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK

**Comment by BlaineEXE** [comment]
A PV needs to be created for a claim (PVC) to be made against it.

This sounds like it ma be an issue with the flexvolume driver configuration in the Rook-Ceph operator or in Kubernetes itself. Make sure that the flex volume storage location is the same for both. If it is omitted for `kubelet`, it should be omitted for Rook as well, as Rook uses kubelet's default.

**Comment by tbe** [comment]
The paths are the same for both. Using the flexvolume for cephfs works, only RBD is affected

**Comment by BlaineEXE** [comment]
I'm not sure how I could repro this to figure out why it's an RBD only issue. You could try deleting the flexvolume dir on the hosts and restarting the operator and agents, but I'm not very hopeful that would fix the issue.

**Comment by jprukner** [comment]
Same issue here. Deleting flexvolume dir does not help. @BlaineEXE 
Ubuntu 18.04, Kubernetes 1.14.1.
However, it only fails when there is fsGroup set to 26. Please see https://github.com/CrunchyData/postgres-operator/blob/master/conf/postgres-operator/pgo.yaml#L69.
 When I deploy the mysql.yaml from the ceph example, everything is ok. Gonna check apparmor.

**Comment by jprukner** [comment]
@BlaineEXE Ok, so it was caused by capacity of pvc being configured in GB instead of GiB. Changing to GiB solved the issue. @BlaineEXE

**Comment by windworship** [comment]
@BlaineEXE Same issue here. In my case, it was caused by the check of devices configmaps. Disable the device hotplug solved the issue.
It turns out that only filtered out the rbd* devices is not enough to get rid of endless osds orchestrating due to device changing. There are other storages such as openebs which creates new volumes mounted as sd*.

**Comment by windworship** [comment]
Besides, I also followed @jprukner to change `GB` to `GiB`

**Comment by nodox** [comment]
I am having this issues as well on GKE.

**Comment by ddobrijalowski** [comment]
I had the same issue (capacity defined in G instead of Gi). Cluster deployed from release-0.9 branch works fine with G. After switching to release-1.0 I had to switch to Gi. In both cases I'm using the same patches applied on top of yamls and do a full wipe of disks (including system and ceph disks).

If this is not a bug then please consider adding a note to changelog and/or upgrade guide.

**Comment by travisn** [comment]
@ddobrijalowski This is a change in k8s 1.14 that requires `Gi`, independent from rook. This is certainly an unexpected change from rook's perspective. See https://github.com/kubernetes/kubernetes/issues/78669

**Comment by ddobrijalowski** [comment]
@travisn Thank you for the link. It cannot be completely independent from rook:
1. When I'm using as base those deployments:
- https://github.com/rook/rook/raw/release-0.9/cluster/examples/kubernetes/ceph/operator.yaml
- https://github.com/rook/rook/raw/release-0.9/cluster/examples/kubernetes/ceph/cluster.yaml
It works fine with G.
2. After switching base to:
- https://github.com/rook/rook/raw/release-1.0/cluster/examples/kubernetes/ceph/common.yaml
- https://github.com/rook/rook/raw/release-1.0/cluster/examples/kubernetes/ceph/operator.yaml
- https://github.com/rook/rook/raw/release-1.0/cluster/examples/kubernetes/ceph/cluster.yaml
PVCs and PVs created with G are pending forever and switching it to Gi resolves the issue.

Nothing else is different - they use the same OS (Cenots 7.6 with 5.1.8 kernel), kubernetes (v1.14.0 server), configuration, machines and devices. The only change I'm applying (using kustomize) to those base yamls is:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
spec:
  dashboard:
    enabled: true
    urlPrefix: /ceph
    port: 80
    ssl: false
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    deviceFilter: "nvme\\d+n1"
    location: site=FM
    config:
      osdsPerDevice: "1"
    directories:
```

**Comment by travisn** [comment]
Ok, thanks for the clarification that you only see this on rook v1.0. I'm sure somebody reported in the past that they didn't see this issue when they were running v1.0 on K8s 1.13, so there must be some combination of v1.14 and rook v1.0. Time spent on the flex driver is limited at this point as development is focused on the CSI driver, but if someone can track this down it would be most helpful in the meantime!

**Comment by mmiller1** [comment]
fwiw, I'm running kubernetes 1.13 & rook 1.0 and ran into this issue.

**Comment by nabokihms** [comment]
I have the same problem with Kubernetes 1.11.10 and Rook 1.0.2. Can it be because of updating kubernetes clienet from 1.11.3 to 1.14.0 in [Rook 1.0](https://github.com/rook/rook/releases/tag/v1.0.0)?
