### ISSUE TITLE
cephcluster CRD is missing properties in upgrade-from-v0.8-create.yaml file

### ISSUE THREAD

**Issue by yan636** [rook/rook#2924]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The dashboard config becomes empty after upgrade by following the upgrade procedure (https://rook.io/docs/rook/v0.9/ceph-upgrade.html)

**Expected behavior:**
The dashboard config can be carried forward during upgrade. 

**How to reproduce it (minimal and precise):**

There're 3 definitions  in rook v0.9.3 delivery.  They should be kept consistent. Among them, upgrade-from-v0.8-create.yaml is short of "port" property, which leads to not working dashboard.
 
upgrade-from-v0.8-create.yaml:
        dashboard:
              properties:
                enabled:
                  type: boolean
                urlPrefix:
                  type: string
operator.yaml
       dashboard:
              properties:
                enabled:
                  type: boolean
                urlPrefix:
                  type: string
                port:
                  type: integer
resources.yaml
            dashboard:
              properties:
                enabled:
                  type: boolean
                urlPrefix:
                  type: string
                port:
                  type: integer
                  minimum: 0
                  maximum: 65535

**Environment**:
* OS (e.g. from /etc/os-release): REHL 7.5
* Kernel (e.g. `uname -a`): Linux rook-control-01 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod): v0.9.3
* Kubernetes version (use `kubectl version`): v1.12.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by travisn** [comment]
@yan636 Were you updating from v0.9.3 to master? That is not supported yet. We are now starting to update the upgrade guide and these yaml files to support the upgrade from v0.9. Those yaml files you mentioned are for the upgrade from v0.8 -> v0.9

**Comment by yanchicago** [comment]
No. The file is used on upgrade from v0.8 -> v0.9. And the link I have referred is also for v0.8-> v0.9.
Understand those files will not be used for future upgrade.

**Comment by travisn** [comment]
Ah right, the `port` property was added after the initial 0.9 release. Were you able to get it working then? Want to open a PR with the fix? In this case, the PR could be opened directly against the release-0.9 branch since the upgrade won't apply to master. I believe `port:` and `ssl:` were both backported and should be added to `upgrade-from-v0.8-create.yaml`.  @noahdesu does that sound right?

**Comment by yanchicago** [comment]
Not sure if others care. In my case, I've updated the CRD to make dashboard accessible. But after upgrade, the dashboard has 500 issue ( ticket #2884). And I believe it's a different issue. May need to re-create/update a couple of secrets? Hopefully, there's some workaround.

**Comment by valentin-krasontovitsch** [comment]
Same as @yanchicago - had to manually go in and set dashboard props, it became empty for us as well. we did an upgrade from 0.8.? to 0.9.0.
and we're also getting the 500 errors...

so we would have definitely appreciated a fix, even though it was easy enough to fix ourselves, after short debugging.

**Comment by noahdesu** [comment]
@travisn yeh, that's right. i didn't know about the upgrade file.
