### ISSUE TITLE
Is there any plan to support openstack cinder volume ?

### ISSUE THREAD

**Issue by shamimgeek** [rook/rook#2925]
How is rook different than rexray project ? 

https://github.com/rexray/rexray

**Comment by BlaineEXE** [comment]
At a brief glance, rexray seems to be focused on providing existing storage to kubernetes via CSI drivers. https://github.com/rexray/rexray/blob/master/.docs/user-guide/storage-providers/ceph.md suggests that rexray does not use existing node storage to provide a Ceph cluster as Rook does. Rather, it simply manages a driver.

It's unclear what you mean by support for openstack cinder volume. 

For an OpenStack cluster running in kubernetes with Rook as the backing storage, OpenStack needs to have a driver for requesting kubernetes persistent volume block claims, or both OpenStack and Rook can use host networking and connect to each other as they usually do.

There is a design doc for using Cinder to act as a driver for legacy storage devices; however, the developers seem to have lost interest. https://github.com/rook/rook/pull/2328

**Comment by BlaineEXE** [comment]
For a formal feature request, please use the feature request issue template.
