### ISSUE TITLE
ceph: document encryption key handling

### ISSUE THREAD

**Issue by noahdesu** [rook/rook#2926]
I believe that the encrypted device support in rook/ceph handles keys according to: http://docs.ceph.com/docs/master/ceph-volume/lvm/encryption/

**Comment by travisn** [comment]
Since Rook doesn't do any handling of the keys and it's all handled by Ceph (osds, ceph-volume, etc), Ceph docs would hopefully be clear on this topic and Rook docs would just need a pointer to the ceph topic.
