### ISSUE TITLE
Consume deployment manifests from the Ceph-CSI project

### ISSUE THREAD

**Issue by nixpanic** [rook/rook#2929]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Reduce the [duplication of the manifests to deploy Ceph-CSI](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph/csi). Documentation should link to the Ceph-CSI project for deployment.

**What is use case behind this feature:**
Single source of manifests, maintained by the Ceph-CSI project.

**Additional info**:
Ceph-CSI is planning to provide manifests as part of their releases.
See-also: ceph/ceph-csi#307

**Comment by kfox1111** [comment]
having ceph-csi helm chart be a conditional dependency in the rook helm chart would also be good.

**Comment by travisn** [comment]
Agreed that the duplication is not a good thing and hopefully is only temporary. The goal is for install of the CSI driver to be as automated as possible. When the rook operator starts and creates the Ceph cluster, it should be able to automate the CSI driver so the user doesn't have to think about it. [This topic](https://rook.io/docs/rook/master/ceph-csi-drivers.html) was intended to be temporary until the automation is completed. Ideally admins won't even have to think about CSI when they're using Rook.

**Comment by kfox1111** [comment]
Please see https://github.com/kubernetes-csi/cluster-driver-registrar/issues/44 for a tangentially related issue. When deploying the rook operator with helm, deploying the csi driver with helm has the potential to help reduce the amount of privilege the operator needs in addition to reducing duplication.
