### ISSUE TITLE
memory tuning config for bluestore and OSDs

### ISSUE THREAD

**Issue by jbw976** [rook/rook#293]
I'm not sure of the available config options for memory tuning in OSDs, but the defaults may be quite large.  This often becomes an issue for us in memory constrained environments such as a kubernetes vagrant cluster where each VM has 2 GB or less.

Also consider rookd being able to be told how much maximum memory it can use and tuning its ceph usage based on that.

**Comment by bzub** [comment]
Ensuring there are a reasonable number of placement groups per OSD (~100) might have the most impact on this.  So I'm referencing #560

**Comment by jefflaplante** [comment]
I agree with @jbw976 in that OSDs are taking up more ram than I'd like in a small Kubernetes cluster with 2GB ram per host node. The OSD can easily take +700Mi which is daunting. Can this be tuned? What are the ramifications of limiting an OSD to less ram?

```
# kubectl top po -n rook
NAME                             CPU(cores)   MEMORY(bytes)
rook-ceph-osd-9hcjm              5m           740Mi
```
