### ISSUE TITLE
Unable to create operator with CSI

### ISSUE THREAD

**Issue by vitobotta** [rook/rook#2935]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I have just cloned the repo and have tried to create the operator with CSI enabled (ceph/operator-with-csi.yaml) but rook-ceph-operator remains stuck at "ContainerCreating" indefinitely. Before that I have created the other resources with ceph/common.yaml.

**Expected behavior:**

The Ceph based operator with CSI enabled should be created and up and running.

**How to reproduce it (minimal and precise):**

- Clone repo
- kubectl create -f rook/cluster/examples/kubernetes/ceph/common.yaml
- kubectl create -f rook/cluster/examples/kubernetes/ceph/operator-with-csi.yaml

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): Linux node1 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Hetzner Cloud, 16GB ram/4CPU x 3
* Rook version (use `rook version` inside of a Rook Pod): not sure since the operator is not created successfully
* Kubernetes version (use `kubectl version`): Client Version => v1.14.0, Server Version => v1.13.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): provisioned With Rancher 2.2.1
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): Ceph, can't check version because I can't install the rook toolbox without the operator etc

Thanks in advance for your help.

**Comment by travisn** [comment]
@vitobotta Did you see the instructions for configuring csi [here](https://rook.io/docs/rook/master/ceph-csi-drivers.html)? The steps at the top of the operator-with-csi.yaml are over-simplified. The operator is likely stuck waiting for the configmaps to be created as listed in those csi instructions.

**Comment by vitobotta** [comment]
> @vitobotta Did you see the instructions for configuring csi [here](https://rook.io/docs/rook/master/ceph-csi-drivers.html)? The steps at the top of the operator-with-csi.yaml are over-simplified. The operator is likely stuck waiting for the configmaps to be created as listed in those csi instructions.

Hi, thanks and sorry for the late reply - I hadn't seen the notification. I tried many things but I ended up just using the 0.9 release instead of master and the standard deployment as described in the docs and the yaml files, instead of CSI. Got it working eventually. Thanks :)
