### ISSUE TITLE
fsName no Effect

### ISSUE THREAD

**Issue by Stefanbs23** [rook/rook#2937]
I want to use more filesystems in my Ceph cluster.

With the option

ROOK_ALLOW_MULTIPLE_FILESYSTEMS defined in operator.yaml

Works great I can now create more filesystems with Ceph 13.2.4 version without problems and rook v0.9.3.

But the option fsName in the pods have now effect, when I change this to something random it always mount the first filesystem its don't check of it exist or other filesystems.

**Comment by galexrt** [comment]
@Stefanbs23 Check the logs of the Rook (Ceph) Agent and search for warning messages.

What kernel are the machines mounting the CephFS running? Below 4.7?
