### ISSUE TITLE
Manager Pod Dies in Cluster with 10 OSDs per node

### ISSUE THREAD

**Issue by sharkymcdongles** [rook/rook#2941]
**Is this a bug report or feature request?**
* Bug Report
**Deviation from expected behavior:**

**How to reproduce it (minimal and precise):**
In my cluster I am seeing my manager pod stop working but remaining in running state. After which, ceph becomes unhealthy until I manually restart the manager pod. I have a cluster with 15 nodes with 2 nvmes each that I split into 10 osds per node(5 per device). I have am using my journal to my osdisk with bluestore. Maybe I need to increase resource allocation to manager pod due to so many osds or something? Haven't found anything in the logs yet.

Mons also seem to have issues in a similar way. Any idea why? Maybe resources need to scale with osds per node?

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`):  4.18.0-1013-azure
* Cloud provider or hardware configuration: Azure Standard_L16s_v2
* Rook version (use `rook version` inside of a Rook Pod): rook: v0.9.2
* Kubernetes version (use `kubectl version`): 1.14.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray in Azure
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
[root@minion-12 /]# ceph health
HEALTH_WARN 25 slow ops, oldest one blocked for 37503 sec, daemons [mon.et,mon.gr,mon.gu] have slow ops.

**Comment by sharkymcdongles** [comment]
`apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # The container image used to launch the Ceph daemon pods (mon, mgr, osd, mds, rgw).
    # v12 is luminous, v13 is mimic, and v14 is nautilus.
    # RECOMMENDATION: In production, use a specific version tag instead of the general v13 flag, which pulls the latest release and could result in different
    # versions running within the cluster. See tags available at https://hub.docker.com/r/ceph/ceph/tags/.
    image: ceph/ceph:v13.2.5-20190319
    # Whether to allow unsupported versions of Ceph. Currently only luminous and mimic are supported.
    # After nautilus is released, Rook will be updated to support nautilus.
    # Do not set to true in production.
    allowUnsupported: false
  # The path on the host where configuration files will be persisted. If not specified, a kubernetes emptyDir will be created (not recommended).
  # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
  # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
  dataDirHostPath: /var/lib/rook
  # set the amount of mons to be started
  mon:
    count: 9
    allowMultiplePerNode: true
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # serve the dashboard using SSL
    # ssl: true
  network:
    # toggle to use hostNetwork
    hostNetwork: false
  rbdMirroring:
    # The number of daemons that will perform the rbd mirroring.
    # rbd mirroring must be configured with "rbd mirror" from the rook toolbox.
    workers: 0
  # To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
  # The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage-node' and
  # tolerate taints with a key of 'storage-node'.
#  placement:
#    all:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#          - matchExpressions:
#            - key: role
#              operator: In
#              values:
#              - storage-node
#      podAffinity:
#      podAntiAffinity:
#      tolerations:
#      - key: storage-node
#        operator: Exists
# The above placement information can also be specified for mon, osd, and mgr components
#    mon:
#    osd:
#    mgr:
  resources:
# The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
#    mgr:
#      limits:
#        cpu: "500m"
#        memory: "1024Mi"
#      requests:
#        cpu: "500m"
#        memory: "1024Mi"
# The above example requests/limits can also be added to the mon and osd components
#    mon:
#    osd:
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
      # Set the storeType explicitly only if it is required not to use the default.
      # storeType: bluestore
      databaseSizeMB: "15000" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "2048"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      walSizeMB: "2048"
      osdsPerDevice: "5" # this value can be overridden at the node or device level
# Cluster level list of directories to use for storage. These values will be set for all nodes that have no `directories` set.
#    directories:
#    - path: /rook/storage-dir
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    nodes:
    - name: "minion-0"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-1"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-2"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-3"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-4"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-5"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-6"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-7"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-8"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-9"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-10"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-11"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-12"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-13"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"
    - name: "minion-14"
      devices: # specific devices to use for storage can be specified for each node
      - name: "nvme0n1"
        config:
          osdsPerDevice: "5"
      - name: "nvme1n1" # multiple osds can be created on high performance devices
        config:
          osdsPerDevice: "5"`

My cluster config file.

**Comment by travisn** [comment]
@sebastian-philipp @leseb This is the second time I've seen this behavior in the last week where the mgr shows as down in the ceph status, but its pod is still running. How to diagnose the mgr in this state? And why would it affect the cluster health?

**Comment by leseb** [comment]
@travisn If the mgr is down we won't have any PG tracking. We need to logs of the pods dying in this case. @sharkymcdongles can you please provide that?

**Comment by sebastian-philipp** [comment]
And having only one mgr is also not really a good idea. There won't be any failover possible with only one mgr.

**Comment by sharkymcdongles** [comment]
How can I have more than one? I don't see a way to configure that like
mons.

**Comment by sharkymcdongles** [comment]
@sebastian-philipp

**Comment by sebastian-philipp** [comment]
Well, that's more like a thing that Rook needs to fix.

**Comment by travisn** [comment]
Long ago in #1048 and #1581 we had been running two mgrs with one in standby, but there was some issue with the prometheus module. It seems we should revisit that and figure out what the issue was so we can run a standby.

Currently I can't think of a way to get rook to run another mgr without a code change. 

Fundamentally the issue of the mgr hanging still exists and needs to be investigated. Otherwise, we might end up having two mgrs that are both hung eventually anyway.

**Comment by sebastian-philipp** [comment]
Yep, that's why we need the mgr logs here.

**Comment by sharkymcdongles** [comment]
[cephmgr.log](https://github.com/rook/rook/files/3084229/cephmgr.log)

Attached is the complete log from the most recent occurrence of this issue.

@sebastian-philipp

**Comment by sebastian-philipp** [comment]
```
$  grep -v -e ms_deliver_dispatch -e send_beacon -e _check_auth_rotating -e 'GET /metrics' -e STATE_ACCEPTING_WAIT_CONNECT_MSG_AUTH -e AuthAuthorizeHandler cephmgr.log       
2019-04-11 22:18:19.053 7f8d4a200700  0 client.0 ms_handle_reset on 10.233.14.142:6790/0
2019-04-11 22:18:19.053 7f8d4a200700  0 client.0 ms_handle_reset on 10.233.14.142:6790/0
2019-04-11 22:25:33.724 7f8d3e8af700  0 log_channel(audit) log [DBG] : from='client.2414911 10.233.79.128:0/2437544143' entity='client.admin' cmd=[{"prefix": "dashboard create-self-signed-cert", "target": ["mgr", ""], "format": "json"}]: dispatch
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer status'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer mode'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer on'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer off'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer eval'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer eval-verbose'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer optimize'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer show'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer rm'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer reset'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer dump'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'balancer execute'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'dashboard set-login-credentials'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'dashboard set-session-expire'
2019-04-11 22:25:33.732 7f8d3e8af700  1 mgr.server handle_command pyc_prefix: 'dashboard create-self-signed-cert'
2019-04-13 13:54:09.814 7f8d4ea09700  0 auth: could not find secret_id=865
2019-04-13 13:54:09.814 7f8d4ea09700  0 cephx: verify_authorizer could not get service secret for service mgr secret_id=865
2019-04-13 13:54:09.814 7f8d4ea09700  0 auth: could not find secret_id=865
2019-04-13 13:54:09.818 7f8d4ea09700  0 cephx: verify_authorizer could not get service secret for service mgr secret_id=865
```
Maybe related to #2784 @noahdesu ?

**Comment by noahdesu** [comment]
thanks @sebastian-philipp it's possible. #2784 doesn't have much context so this is helpful

**Comment by noahdesu** [comment]
This doesn't look like it is related to #2784 

https://github.com/rook/rook/issues/2888
https://tracker.ceph.com/issues/23460

**Comment by sebastian-philipp** [comment]
@noahdesu maybe http://tracker.ceph.com/issues/39335 is related?

**Comment by noahdesu** [comment]
@sebastian-philipp actually this might be related to #2784 but it could also be related to the tracker ticket you posted, too. It's tough to tell if this issue is related to authorization issues (seen in the log) or some other hang. There is a _class_ of hangs that can occur if a manager module tries to write to the monitors at _just the right moment_ https://github.com/noahdesu/rook/commit/e33eb980470be4ef157f511f75e00c7b1c6543ff
