### ISSUE TITLE
why rook can't deploy more than one mon on the same machine with host networking?

### ISSUE THREAD

**Issue by caisan** [rook/rook#2948]
This is question is about the rook design.
when i read the source code of the rook operator. i see
```golang
// fail if we were instructed to deploy more than one mon on the same machine with host networking
if c.HostNetwork && c.spec.Mon.AllowMultiplePerNode && c.spec.Mon.Count > 1 
      return nil, fmt.Errorf("refusing to deploy %d monitors on the same host since hostNetwork is %v and allowMultiplePerNode is %v. Only one monitor per node is allowed", c.spec.Mon.Count, c.HostNetwork, c.spec.Mon.AllowMultiplePerNode)
        }
```
but as we know, we can use vstart.sh to deploy an all-in-one , even it is a dev env.
so, i think that rook should also support deploy more than one Mon on the same machine with all-in-one mode.

**Comment by travisn** [comment]
@caisan There are a couple of options in the test scenario you described:
- You only need to create a single mon to create a test cluster. This can be set with the `mon.count: 1` in the cephcluster custom resource. 
- If you are not using host networking, you can create multiple mons on the same node if desired to test multiple mons in a single-node cluster. 

Does that help with your scenario, or can you elaborate more on what you are trying to accomplish?

**Comment by caisan** [comment]
> @caisan There are a couple of options in the test scenario you described:
> 
> * You only need to create a single mon to create a test cluster. This can be set with the `mon.count: 1` in the cephcluster custom resource.
> * If you are not using host networking, you can create multiple mons on the same node if desired to test multiple mons in a single-node cluster.
> 
> Does that help with your scenario, or can you elaborate more on what you are trying to accomplish?

hi, @travisn ,thanks for your comments. i have tried  you mentioned two above in your comments.
what i need is using host networking, and create multiple mons on the same node . So now, this is the limitation of rook . btw, does this scenario i need is meaningful ? thx

**Comment by caisan** [comment]
@travisn If you have the experience of use ceph [vstart.sh](https://github.com/ceph/ceph/blob/master/src/vstart.sh), you can build a ceph cluster on a single node, and the 3 mons(for example) bind different port(like 6789,6790,6791). rook also support this scenario, should we?

**Comment by leseb** [comment]
@caisan this is a scenario we are not willing to support at this point. People typically use hostnetworking with a single cluster only. If you want to run multiple clusters/mon on the same machine you need to use the overlay network.

`vstarts.sh` is a developer tool, Rook is intended to work on a realistic, production environment.
Thanks.
