### ISSUE TITLE
"500 Internal Server Error" accessing dashboard behind ingress

### ISSUE THREAD

**Issue by jmreicha** [rook/rook#2954]
**Is this a bug report or feature request?**

* Bug Report

**Deviation from expected behavior:**

Carrying over discussion from https://github.com/rook/rook/issues/2492, as the issue I am seeing is slightly different.

I ran into this while running the dashboard behind an ingress and turning off SSL for the dashboard.  I am able to login to the dashboard but getting the 500 internal server errors in the web UI as well as the pod logs as described below.

I discovered there are no OSD's running in the cluster (working on figuring that one out), I don't think it is relevant here but mentioning it just in case.

Logs from the ceph-mgr pod.

```
[09/Apr/2019:22:49:14] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib64/ceph/mgr/dashboard/controllers/summary.py", line 68, in __call__
    'rbd_mirroring': self._rbd_mirroring(),
  File "/usr/lib64/ceph/mgr/dashboard/controllers/summary.py", line 43, in _rbd_mirroring
    daemons = data.get('daemons', [])
AttributeError: 'NoneType' object has no attribute 'get'

[09/Apr/2019:22:49:14] HTTP
Request Headers:
  REFERER: https://internal.domain/ceph/
  X-FORWARDED-HOST: internal.domain
  Remote-Addr: 172.18.4.152
  X-REAL-IP: x.x.x.x
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
  COOKIE: csrftoken=U2XP5w7EXypGzEoEU2c27RaMZDS4sM0d9UY7gfyaUSLxfZgJWJ4jBzAcjlHolktb; session_id=8d9d350ab455355749c0ec87953c25dcd6219670
  ACCEPT: application/json, text/plain, */*
  X-FORWARDED-PROTO: https
  X-ORIGINAL-URI: /ceph/api/summary
  DNT: 1
  HOST: internal.domain
  X-SCHEME: https
  ACCEPT-LANGUAGE: en-US,en;q=0.9,fr;q=0.8
  X-FORWARDED-FOR: x.x.x.x
  X-FORWARDED-PORT: 443
  X-REQUEST-ID: 0e745f36f820f930f15d8ebb1c44b075
  ACCEPT-ENCODING: gzip, deflate, br
debug 2019-04-09 22:49:14.373 7ff9dfe34700  0 mgr[dashboard] [172.18.4.152:48554] [GET] [500] [5.003s] [admin] [1.1K] /ceph/api/summary
debug 2019-04-09 22:49:14.373 7ff9dfe34700  0 mgr[dashboard] ['{"status": "500 Internal Server Error", "version": "3.2.2", "detail": "The server encountered an unexpected condition
172.18.4.152 - - [09/Apr/2019:22:49:14] "GET /ceph/api/summary HTTP/1.1" 500 1127 "https://internal.domain/ceph/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36
```

Here is what the ceph config looks like (after following the suggestion from above to update the server_addr).

```
[root@worker1 /]# ceph config dump
WHO   MASK LEVEL   OPTION                     VALUE                                                        RO
  mgr      unknown mgr/dashboard/password     XXX *
  mgr      unknown mgr/dashboard/server_addr  172.18.1.43                                                  *
  mgr      unknown mgr/dashboard/server_addr  0.0.0.0                                                      *
  mgr      unknown mgr/dashboard/server_port  8443                                                         *
  mgr      unknown mgr/dashboard/ssl          false                                                        *
  mgr      unknown mgr/dashboard/url_prefix   /ceph                                                        *
  mgr      unknown mgr/dashboard/username     admin                                                        *
  mgr      unknown mgr/prometheus/server_addr 172.18.1.43                                                  *
``` 

**How to reproduce it (minimal and precise):**

* Set the dashboard CRD configuration to use `ssl: false` and the `urlPrefix: /ceph` options
* Deploy stock rook and a ceph operator and cluster with adapted configuration
* Add an ingress (Nginx) with an annotation for rewriting the /ceph url, e.g. `      nginx.ingress.kubernetes.io/rewrite-target: "/ceph"`
* Check the ceph-mgr logs for the error

**Environment**:
* OS (e.g. from /etc/os-release): `coreOS 2023.5.0`
* Kernel (e.g. `uname -a`): `4.19.25-coreos`
* Cloud provider or hardware configuration:`metal`
* Rook version (use `rook version` inside of a Rook Pod): `v0.9.3`
* Kubernetes version (use `kubectl version`): `v1.10`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `metal`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

```
[root@worker1 /]# ceph status
  cluster:
    id:     6e60a639-5ce7-4cb0-8707-5866ef75a93c
    health: HEALTH_WARN
            Reduced data availability: 100 pgs inactive

  services:
    mon: 3 daemons, quorum a,c,b
    mgr: a(active)
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   1 pools, 100 pgs
    objects: 0  objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             100 unknown
```

**Comment by jmreicha** [comment]
This issue does appear to be related to the OSD issues.  After getting OSDs up and running the 500 internal errors seem to have stopped.

**Comment by noahdesu** [comment]
thanks @jmreicha for the update.

**Comment by noahdesu** [comment]
@rjfd have you seen this sort of thing? sometimes it takes a while for the OSDs and other daemons to spin-up relative to the dashboard. And it seems that the dashboard has some issues when certain daemons aren't running. Is this something I should add to ceph upstream as an issue?

**Comment by rjfd** [comment]
@noahdesu yes, I think we should create an upstream ticket for this. The dashboard should be able to cope with a cluster that does not have OSDs yet.

**Comment by noahdesu** [comment]
Thanks for the triage @rjfd http://tracker.ceph.com/issues/39303
