### ISSUE TITLE
Increasing rgw pod count restarts all rgw pods

### ISSUE THREAD

**Issue by christianhuening** [rook/rook#2957]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I would expect to simply see 2 additional pods when increasing the RGW pod in the CRD from 3 to 5. Instead the 3 present pods were killed and then 5 new were started.
**Expected behavior:**

**How to reproduce it (minimal and precise):**

Use rook 0.9 and increase the instance count for a CephObjectStore from 3 to 5

**Environment**:
* OS (e.g. from /etc/os-release): ContainerLinux latest stable
* Kernel (e.g. `uname -a`): 
* Cloud provider or hardware configuration: bare-metal
* Rook version (use `rook version` inside of a Rook Pod): 0.9.0
* Kubernetes version (use `kubectl version`): 1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Upstream
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):HEALTH_OK

**Comment by leseb** [comment]
The reason why we do this is to keep the desired state uniform across all the deployments. So if you edit the spec and change something, all the pods must have their spec updated.
With https://github.com/rook/rook/pull/3283 we loop so pods are killed one by one, this means their should not be service interruption.

**Comment by christianhuening** [comment]
@leseb That would be fantastic and very useful indeed!

**Comment by leseb** [comment]
Closed via #3283.
