### ISSUE TITLE
Rook v0.9.3 Ceph object store dashboard 

### ISSUE THREAD

**Issue by meirhazonAnyVision** [rook/rook#2958]
Hello,

We are using Rook Ceph v0.9.3 (Ceph image: `v13.2.4-20190109`) on kubernetes v1.13.5 Ubuntu 18.4

No matter what I try I cannot make the object storage part in the dashboard work.

The Object Gateway seems to be working properly, buckets, files etc.

The other parts in the dashboard also work properly.

I am getting,
500 - Internal Server Error
RGW rest api failed request with status code 403

I am doing everything exactly as described in, http://docs.ceph.com/docs/mimic/mgr/dashboard/
The S3 access, secure keys etc. are accurate.

How should I address this issue? 

Thanks so much,

Meir

**Comment by galexrt** [comment]
Closing in favor of the newly created issue #3026.
