### ISSUE TITLE
Better default command for rook-tools kubernetes pod container

### ISSUE THREAD

**Issue by jbw976** [rook/rook#296]
Currently, the rook-client k8s demo container uses a default command of a very long sleep, to keep it alive so the user can connect to it and run `rook` client commands:
https://github.com/rook/rook/blob/master/demo/kubernetes/rook-client/rook-client.yml#L10

After discussion with @thephred, this could be improved, potentially by using the gcr.io/google_containers/pause binary as the default command.  See this thread for more discussion:
https://github.com/rook/rook/pull/294#discussion_r92678460

Maybe there's a better pattern to use here than that, but more research would be needed.

**Comment by travisn** [comment]
there is no sleep anymore since the toolbox.sh script never exits
