### ISSUE TITLE
Document or automate `ceph osd require-osd-release nautilus` for upgrade to Nautilus

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#2960]
Upgrade docs for v1.0 need to have the user issue the command `ceph osd require-osd-release nautilus` manually or automate issuing the command from the operator after Ceph cluster's OSDs are all healthy. Ceph's upgrade docs have full context:
http://docs.ceph.com/docs/master/releases/nautilus/#upgrading-from-mimic-or-luminous

**Comment by BlaineEXE** [comment]
This has been documented though untested in the current draft of #2965. I think we need to have #2973 fixed before we can call the documentation complete and is an obvious priority. I'm hopeful we will still have time to automate this command and be able to remove it from the guide before release.

**Comment by travisn** [comment]
@BlaineEXE This was documented in #2965, right?

**Comment by dimm0** [comment]
Is it safe to do having some older kernel clients? Like 3.10?
