### ISSUE TITLE
Make pool creation in `CephObjectStore` CRD optional

### ISSUE THREAD

**Issue by sebastian-philipp** [rook/rook#2963]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
When creating a `CephObjectStore`  CR, I also have to specify Ceph pool definitions. There should a setting to disable this.

I don't know how to handle realm, zone, and zone group here. this needs further discussion.

**What is use case behind this feature:**

There are three reasons to make pool creation optional:

1. `CephFilesystem`already supports `"onlyManageDaemons": True,` with a very similar reasoning behind it.
2. Form the Ceph orchestrator modules, there is no user friendly way to properly specify details of these pools. 
3. Users might have existing data imported and just want to set up an RGW for the data.

**Workaround**

> If you create the expected pools before creating the object store, rook would use those existing pools
> The replication (or EC) settings would need to be the same in the CR or else rook would try to change them
> I believe this should work, but I haven’t tested it

**Comment by sebastian-philipp** [comment]
For future reference: onlyManageDameon was never implemented. See rook/rook#1900 and https://github.com/ceph/ceph/commit/4a45b67a8c8b079a373e334f8bfd72cd97259853

**Comment by jmolmo** [comment]
I think this issue has some dependencies with https://github.com/rook/rook/pull/4520

**Comment by travisn** [comment]
Fixed with #5058
