### ISSUE TITLE
root-edgefs cluster deploy error

### ISSUE THREAD

**Issue by shaozi** [rook/rook#2970]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Ran `kubectl create -f operator.yaml` succesfully, then ran `kubectl create -f cluster.yaml` and the `mgr` and `target` pods were not created.

```sh
Name:         rook-edgefs
Namespace:    rook-edgefs
Labels:       <none>
Annotations:  <none>
API Version:  edgefs.rook.io/v1alpha1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2019-04-11T21:25:17Z
  Generation:          3
  Resource Version:    36721
  Self Link:           /apis/edgefs.rook.io/v1alpha1/namespaces/rook-edgefs/clusters/rook-edgefs
  UID:                 4d99b306-5ca0-11e9-985b-00505601dcca
Spec:
  Chunk Cache Size:  0
  Dashboard:
    Local Addr:
  Data Dir Host Path:  /var/lib/edgefs
  Data Volume Size:    0
  Edgefs Image Name:   edgefs/edgefs:latest
  Network:
    Broker If Name:
    Server If Name:
  Resources:
  Service Account:  rook-edgefs-cluster
  Storage:
    Config:           <nil>
    Use All Devices:  true
    Use All Nodes:    true
Status:
  Message:  giving up creating cluster in namespace rook-edgefs after 5m0s
  State:    Error
Events:     <none>
```

**Expected behavior:**

Should work as documented.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
* Kernel (e.g. `uname -a`): Linux dc1-n1 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: standalone node
* Rook version (use `rook version` inside of a Rook Pod): rook: v0.9.0-374.g2ca611a
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): edgefs

**Comment by dyusupov** [comment]
Thanks for the report. What errors do you see in the operator log? How is your Cluster CRD looks like (only Cluster CRD kind)?

**Comment by shaozi** [comment]
It's my first try. Can you tell me the command to get what you want?

**Comment by dyusupov** [comment]
No worries. It probably would be best if we continue the discussion on our Rook slack channel so to keep other people mailboxes sane.
