### ISSUE TITLE
cluster failed to create osds in one of nodes

### ISSUE THREAD

**Issue by sswangifly** [rook/rook#2979]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Use  release v0.9.3 cluster.yaml to create a ceph cluster. then only one node get the following error logs:
```logs
2019-04-11 11:38:37.178070 E | op-cluster: failed to create cluster in namespace rook-ceph. failed to start the osds. 2 failures encountered while running osds in namespace rook-ceph: orchestration for node node-03 failed: &{OSDs:[] Status:failed Message:failed to configure dirs map[/data/ceph:41]. failed to initialize OSD at /data/ceph/osd41: failed osd mkfs for OSD ID 41, UUID 1a9926df-75bd-404a-a9de-a1e65b41cfbe, dataDir /data/ceph/osd41: Failed to complete 'mkfs-osd41': exit status 250. }
orchestration for node node-03 failed: &{OSDs:[] Status:failed Message:failed to configure dirs map[/data/ceph:41]. failed to initialize OSD at /data/ceph/osd41: failed osd mkfs for OSD ID 41, UUID 1a9926df-75bd-404a-a9de-a1e65b41cfbe, dataDir /data/ceph/osd41: Failed to complete 'mkfs-osd41': exit status 250. }
```
This node retry to create osds and no one success. other node create only one osd and successed.
<pre>
[root@node-03 ceph]# ls
osd10  osd12  osd14  osd16  osd18  osd20  osd22  osd24  osd26  osd28  osd30  osd32  osd34  osd36  osd38  osd4   osd41  osd43  osd45  osd47  osd6  osd8
osd11  osd13  osd15  osd17  osd19  osd21  osd23  osd25  osd27  osd29  osd31  osd33  osd35  osd37  osd39  osd40  osd42  osd44  osd46  osd5   osd7  osd9

</pre>
**Expected behavior:**
all osds are created success.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
* Kernel (e.g. `uname -a`):4.20.3-1.el7.elrepo.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v0.9.3
* Kubernetes version (use `kubectl version`): v1.13.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by shivendrapro0** [comment]
Hi 
I am also facing this issue. 
Was this resolved ?

**Comment by travisn** [comment]
@sswangifly Can you share the logs for the osd prepare pod? It may show more details about the failure. A common failure for mkfs with filestore is if there is not at least 5GB free, alhthough hard to know if this is the same issue.
