### ISSUE TITLE
Support specifying images by sha256

### ISSUE THREAD

**Issue by dicarlo2** [rook/rook#2984]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Allow specifying a specific sha for a given image repository in the operators (in particular, the cassandra operator)

**What is use case behind this feature:**
Specifying a sha is more secure and in some environments the only way to specify an image.

**Comment by travisn** [comment]
@dicarlo2 Can you provide an example of what isn't working? Are you referring to specifying the image using hte sha256 in the [cassandra CR](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/cassandra/cluster.yaml#L73)?

**Comment by dicarlo2** [comment]
@travisn yes, exactly. Unless I'm missing something, the `version` attribute only allows specifying the tag, right?

**Comment by travisn** [comment]
@yanniszark If the `version` allows specifying the full image name, other docker registries, hash, etc, could be specified as requested, similar to the [ceph version spec](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L23)

**Comment by yanniszark** [comment]
@travisn not exactly.
Version is the tag indeed, but you can also specify repository.
A workaround for now would be to specify:
```
version: <sha256_hash>
repository: <myrepo>@sha256
```

**Comment by galexrt** [comment]
Stil needs to be improved.

**Comment by travisn** [comment]
The image can be specified by sha as mentioned in an earlier comment. Closing from further changes due to lack of activity.
