### ISSUE TITLE
Please remove use of the finalizer in CephCluster

### ISSUE THREAD

**Issue by sebastian-philipp** [rook/rook#2988]
I ran into the same deadlock and removing the finalizer fixed the issue for me.

See reasoning behind https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/339 and kubernetes/kubernetes#60538

**Comment by travisn** [comment]
The finalizer certainly causes headaches sometimes so if we can remove the requirement it would much better. The requirement for using the finalizer is that the operator needs to be running to unmount/detach the rbd volumes before the cephcluster CR is deleted. If the mon/osd pods are delected before the volumes are cleaned up, they will be hung until the host is restarted. I am not sure if CSI will help with this, but flex driver is definitely impacted.

**Comment by sebastian-philipp** [comment]
My workaround right now is to remove the finalizer manually:

https://github.com/sebastian-philipp/test-rook-orchestrator/blob/082b0667114fc279355fd8206edb618a3f529b17/undeploy-rook-ceph.sh#L10
