### ISSUE TITLE
Disk resize after OSD provisioning

### ISSUE THREAD

**Issue by PCatinean** [rook/rook#2997]
I am not sure if this is a feature request or a bug report.

When one attaches a disk to a VM that rook then picks up if one would resize the disk later rook does not pick up the extra space. Restarting the operator or cluster did not help.

Resized attached device from 80Gi to 100Gi and `ceph osd status` still shows 3 OSDs with 78.0 available space.

**Environment**:
* OS (e.g. from /etc/os-release):
Debian GNU/Linux 9 (stretch)
* Kernel (e.g. `uname -a`):
Linux node-1 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
* Cloud provider or hardware configuration:
Hetzner
* Rook version (use `rook version` inside of a Rook Pod):
 rook: v0.9.3
* Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Provisioned using Rancher v2.1.8
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
  cluster:
    id:     34126c04-c512-4f1a-8772-c9b134d51d11
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum c,b,d
    mgr: a(active)
    osd: 3 osds: 3 up, 3 in
 
  data:
    pools:   1 pools, 100 pgs
    objects: 639  objects, 1.1 GiB
    usage:   5.9 GiB used, 234 GiB / 240 GiB avail
    pgs:     100 active+clean
 
  io:
    client:   33 KiB/s wr, 0 op/s rd, 0 op/s wr

**Comment by travisn** [comment]
@alfredodeza @dmick What would it take to get the OSD to pick up on the additional space added to the volume?

**Comment by dmick** [comment]
I don't think there's any provision for doing this.  Easier to blow away the OSD, reprovision, and let backfill take its course.  I could be wrong, but I've never heard of any 'expand' operations.

**Comment by vitobotta** [comment]
Hi, I was just wondering about this. With OpenEBS I can easily live expand/resize a pool when I resize the disks with my cloud provider. If this is not possible, what should I do in order to increase capacity without downtime/loss of data? Thanks!

**Comment by vitobotta** [comment]
I just tried adding volumes with DigitalOcean and it seems to be creating the new OSDs automatically without me doing anything. Is this the right approach to add storage?

**Comment by schmitch** [comment]
@dmick what would be a common workflow to do that?

**Comment by dmick** [comment]
@schmitch not sure off the top of my head with Rook, but I'd assume "add/remove OSD" has to be in the documentation?

**Comment by BlaineEXE** [comment]
I'm not sure this is a supported case, and I don't believe we should go out of our way to support it. Ceph storage space can be easily expanded by adding more disks.

**Comment by PCatinean** [comment]
This provider does not have storage provision nor does it provide a kubernetes service. It's just an interface that provisions VM's with an API and can attach block storage devices to those VM's on command. Kubernetes was installed from scratch on them and then rook to allow usage of the storage within the k8s cluster.

It's the best solution I could find to use here, I wouldn't be crazy an try to reinvent the wheel if I was using AWS or GKE :)

**Comment by leseb** [comment]
Just FYI we do not support OSD online-resizing or OSD resizing at all. Ceph is not planning to support that any time soon and thus nor Rook. So I suggest we close this as *won't fix*. Thanks.

**Comment by PCatinean** [comment]
Not a problem, that's why I mentioned I was not sure if it was a bugfix or a feature request :)

**Comment by leseb** [comment]
@PCatinean thanks for your understanding :-)

**Comment by namaiiee2222** [comment]
> > If anybody is interested how to do it (using ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable) ) or later. Here is a short recepy:
> > 
> > 1. Enlarge disk (if virtual environment is used) where the OSD LV is located on.
> > 2. Make sure the os sees larger disk (for instance /dev/sdb; use lsblk for inspecton)
> > 3. pvresize /dev/sdb
> > 4. lvextend -l +100%FREE  (LV Path taken from output of "lvdisplay")
> > 5. restart OSD service: systemctl restart ceph-@osd..service
> > 
> > Voila, your OSD has more space.
> 
> That won't work for several reasons:
> 
> * Rook does not always use LVM to provision OSDs
> * Rook does not use systems to run the Ceph daemons
> 
> This example probably works but not when Ceph is deployed with Rook.

how we can resize(extend) osd in ceph cluster when deployed by rook?

**Comment by travisn** [comment]
> how we can resize(extend) osd in ceph cluster when deployed by rook?

If it's a raw disk, rook should have created an init container on the osd pod for expanding the osd at startup as seen [here](https://github.com/rook/rook/blob/3b5bbf28d5626a60d5889b6234acb1ef43b3d068/pkg/operator/ceph/cluster/osd/spec.go#L1118-L1128). 

If it's an OSD on a PVC, simply expanding the size of the volumeClaimTemplate in the storageClassDeviceSet should trigger the OSD to restart and automatically expand to the new size as well.

**Comment by HeroCC** [comment]
> > how we can resize(extend) osd in ceph cluster when deployed by rook?
> 
> If it's a raw disk, rook should have created an init container on the osd pod for expanding the osd at startup as seen [here](https://github.com/rook/rook/blob/3b5bbf28d5626a60d5889b6234acb1ef43b3d068/pkg/operator/ceph/cluster/osd/spec.go#L1118-L1128).

I tried this approach, and it appears the space is recognized, but as taken, not free space. I resized from 64GB to 128GB, but my `replicapool` is still the same size as it was before, and the 'Raw Capacity' says the new added space is taken.

There's a good chance I'm doing something wrong here, this is a test lab as I try to learn rook / ceph, but could you lend a hand? I'd appreciate some help debugging or pointers in the right direction -- seems to me that most of the docs for ceph assume dynamic resizing like this is impossible.

**Comment by travisn** [comment]
Do you see the increased OSD size reported by `ceph osd df`? And which ceph command is showing the added space is taken?

**Comment by rkrzewski** [comment]
I'm running a bare metal cluster using microk8s. The hosts don't have dedicated disks that I can use for Ceph but have a LVM setup and there are VGs with space I can use. I'm running TopoLVM as the local provisioner in the cluster and then I'm running PVC based rook-ceph on top of that to provide redundant, network attached storage to the apps.

Resizing worked fine for me out of the box. After provisioning the cluster I've run `kubectl edit -n rook-ceph pvc/set-1-data-xxx` and modified `Storage` field, then ran `kubectl rollout restart -n rook-ceph deployments.apps/rook-ceph-osd-n` for the OSD corresponding to modified PVC, and after a few seconds `ceph osd df` was showing increased free space for that OSD.

**Comment by fzyzcjy** [comment]
Hi, I am quite confused (I am new to rook). So, in my case, my disk attached to server A is running out of space. Then I enlarge that disk using consoles of my public cloud provider. Then what should I do in Rook to let it understand the disk is bigger? Will it remove all my data on the disk?

I have seen discussions above and seems that OSD does not allow resizing; but some people also suggests they have successfully done it. So I am quite confused.

**Comment by travisn** [comment]
I believe in that case you just need to restart the OSD pod after increasing the size and the OSD will update automatically. If you see otherwise, please open a new issue.

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by andy108369** [comment]
> > > how we can resize(extend) osd in ceph cluster when deployed by rook?
> > 
> > 
> > If it's a raw disk, rook should have created an init container on the osd pod for expanding the osd at startup as seen [here](https://github.com/rook/rook/blob/3b5bbf28d5626a60d5889b6234acb1ef43b3d068/pkg/operator/ceph/cluster/osd/spec.go#L1118-L1128).
> 
> I tried this approach, and it appears the space is recognized, but as taken, not free space. I resized from 64GB to 128GB, but my `replicapool` is still the same size as it was before, and the 'Raw Capacity' says the new added space is taken.
> 
> There's a good chance I'm doing something wrong here, this is a test lab as I try to learn rook / ceph, but could you lend a hand? I'd appreciate some help debugging or pointers in the right direction -- seems to me that most of the docs for ceph assume dynamic resizing like this is impossible.

Can confirm.

Once expanded the OSD, don't forget to tell bluestore about this, otherwise the newly added space will get reported as `RAW SIZE` only, without actually letting you use it as available/free space.

```
ceph-bluestore-tool bluefs-bdev-expand --path /var/lib/ceph/osd/ceph-<ID>
```

Ignore these errors:

```
2022-08-28T21:00:43.313+0000 7f59c45ad700 -1 bluestore(/var/lib/ceph/osd/ceph-<ID>) _read_bdev_label failed to read from /var/lib/ceph/osd/ceph-<ID>: (21) Is a directory
2022-08-28T21:00:43.313+0000 7f59c45ad700 -1 bluestore(/var/lib/ceph/osd/ceph-<ID>) unable to read label for /var/lib/ceph/osd/ceph-<ID>: (21) Is a directory
```

The reason for these errors is explained [here](https://youtu.be/e0J0gft2jEY?t=779)

cc @travisn

**Comment by kycfeel** [comment]
Thanks, @andy108369.

I was having the exact same issue and was able to fix it by running the `ceph-bluestore-tool` as you mentioned.

For those ones who are wondering how to run the `ceph-bluestore-tool` on the Kubernetes rook-ceph environment, you could modify the `deployment` of your OSDs to add it as an `initContainer`.

```
 - name: bluefs-bdev-expand
    image: quay.io/ceph/ceph:v17.2.3
    command:
      - ceph-bluestore-tool
    args:
      - 'bluefs-bdev-expand'
      - '--path'
      - /var/lib/ceph/osd/ceph-1
    resources: {}
    volumeMounts:
      - name: rook-data
        mountPath: /var/lib/rook
      - name: rook-config-override
        readOnly: true
        mountPath: /etc/ceph
      - name: rook-ceph-log
        mountPath: /var/log/ceph
      - name: rook-ceph-crash
        mountPath: /var/lib/ceph/crash
      - name: devices
        mountPath: /dev
      - name: run-udev
        mountPath: /run/udev
      - name: activate-osd
        mountPath: /var/lib/ceph/osd/ceph-<ID>
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      runAsUser: 0
      readOnlyRootFilesystem: false
```

Volla.

**Comment by samos667** [comment]
> Thanks, @andy108369.
> 
> I was having the exact same issue and was able to fix it by running the `ceph-bluestore-tool` as you mentioned.
> 
> For those ones who are wondering how to run the `ceph-bluestore-tool` on the Kubernetes rook-ceph environment, you could modify the `deployment` of your OSDs to add it as an `initContainer`.
> 
> ```
>  - name: bluefs-bdev-expand
>     image: quay.io/ceph/ceph:v17.2.3
>     command:
>       - ceph-bluestore-tool
>     args:
>       - 'bluefs-bdev-expand'
>       - '--path'
>       - /var/lib/ceph/osd/ceph-<ID>
>     resources: {}
>     volumeMounts:
>       - name: rook-data
>         mountPath: /var/lib/rook
>       - name: rook-config-override
>         readOnly: true
>         mountPath: /etc/ceph
>       - name: rook-ceph-log
>         mountPath: /var/log/ceph
>       - name: rook-ceph-crash
>         mountPath: /var/lib/ceph/crash
>       - name: devices
>         mountPath: /dev
>       - name: run-udev
>         mountPath: /run/udev
>       - name: activate-osd
>         mountPath: /var/lib/ceph/osd/ceph-<ID>
>     terminationMessagePath: /dev/termination-log
>     terminationMessagePolicy: File
>     imagePullPolicy: IfNotPresent
>     securityContext:
>       privileged: true
>       runAsUser: 0
>       readOnlyRootFilesystem: false
> ```
> 
> Volla.

Hi, i have use your example:
I stopped the OSD with kubectl -n rook-ceph scale deployment rook-ceph-osd-<id> --replicas=0
After i increment the disk in proxmox to add 50Gb
I check if fdisk -l show the correct new size
![image](https://user-images.githubusercontent.com/50653464/188909937-625ffbb3-8d85-44a9-a28c-a7adcd46ddd1.png)

I get the deployment YAML of the OSD with kubectl -n rook-ceph get deployment rook-ceph-osd-2 -o yaml > resize-osd-2.yaml
And modify it to add the initcontainer ceph-bluestore in the deployement (I have attached the modified deployment)
After deploy it i start the OSD again. But he cant start.

![image](https://user-images.githubusercontent.com/50653464/188909552-18ae580e-e6f7-446a-8e17-9ed33b01df3d.png)



Some logs:
![image](https://user-images.githubusercontent.com/50653464/188909038-6c892e5c-d475-4751-848f-33010e7d02a2.png)

Have you a idea to resolve my issue ?

**Comment by samos667** [comment]
> @samos667 what's your Ceph version/release? It looks like you are running `Pacific` (`v16.x`) Ceph while trying to run `Quincy` (`v17.x`) `image: quay.io/ceph/ceph:v17.2.3` in the `bluefs-bdev-expand` deployment manifest file, based on the `unrecognized op 12` error ([refs](https://tracker.ceph.com/issues/55407)). If you can determine you are running a different Ceph version, then simply reflect the correct version in the `image: ` tag of the deployment manifest file.

At present:
![image](https://user-images.githubusercontent.com/50653464/229838216-21a09239-c875-409c-8dbf-d18de7c1815c.png)

But from this issue i have redeploy rook a couple of time. I managed to convince my boss to use all the SSDs with proxmox disk passthrough(as advised in the ceph doc), so resizing is not longer a problem for us.
