### ISSUE TITLE
Suggestions on "rook pool create"

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#300]
Here are some suggestions on `rook pool create`.

1) I think we should eliminate the -n/--name parameter in favor of just specifying the pool name.  That is `rook pool create my-pool-name`.  It just feels more correct.  (That is to directly specify the subject of the verb).  This probably impacts other commands too.

2) We should eliminate the -t/--type option.  The type of pool is always known based on the other flags so this option is completely redundant.  Another criticism is that the parameter values are to verbose but that's irrelevant if you remove the option.

3) The -c/-d/--ec-coding-chunks/--ec-data-chunks options are OK in principle but these parameters are almost universally called K and M.  K are the data chunks and M are the coding chunks.  At the very least we should cite K and M in the help text for these options but I think we should consider renaming the options.  Perhaps --ec-k/--ec-m.  Certanly if we have one-letter options (-c/-d) they should be -k/-m.

**Comment by travisn** [comment]
with the pool CRD i'd recommend we not worry about this anymore. In fact, we should consider removing the pool create from `rookctl`
