### ISSUE TITLE
How to run operator in local ?

### ISSUE THREAD

**Issue by caisan** [rook/rook#3012]
when i change or add some code of operator. i have to do those step below to check if it works:
1) build a new binary file: ```make -j4```
2) docker build a new operator image: **rook/ceph**: ```docker build -t rook/ceph .```
3) launch operator and cluster by running: ```kubectl create -f operator.yaml```and ```kubectl create -f cluster.yaml```
IF something wrong or IF not works as expected. i have to do all the 3 step above again.
so, i wonder if there is a way to run ```rook```(operator) locally, just in bash.
thx.

**Comment by caisan** [comment]
if ```rook``` can run in ```bash```, it is convenient for developer to debug or check error quickly. dont need make docker images.

**Comment by travisn** [comment]
@caisan Great question, having an efficient development environment like that would be awesome. Unfortunately, there are just too many dependencies on K8s resources, ceph configuration, etc that makes it feasible. The only option to run outside a full environment is in the unit tests which mock k8s, process creation, etc.

**Comment by caisan** [comment]
@travisn thanks for your reply, you are right, run rook needs more dependencies than running a rbd-provisioner.
