### ISSUE TITLE
Ceph noout - reliable check for  node cordoned status does not exist

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#3014]
**Is this a bug report or feature request?**
* Bug Report

The binary check `k8sutil.GetNodeSchedulable(*newNode)` introduced in #2986 to test for node schedulability will also return true if the node has been tainted as having memory or disk pressure or any number of other well-known taints.

There is an unschedulable taint applied when `kubectl cordon` is used, but according to the k8s codebase, this taint can applied any time the node is unschedulable for any condition.
https://github.com/kubernetes/kubernetes/blob/4cd759dbe0a5239de01ea8ece2d4f73a5dd8706c/pkg/scheduler/api/well_known_labels.go#L35-L38

To my logic, there is no way for us to determine that a node has been specifically cordoned for maintenance versus made unschedulable for any number of other reasons. I think we should revert that PR and consider other ways we might be able to mark noout for users.

If it is to be a manual step, I think we might want to use a Ceph command to set noout on all the osds of a particular node. We might have to make an issue to get that added to Ceph.

**Comment by travisn** [comment]
@BlaineEXE Thanks for raising the issue. Knowing that an admin has intentionally put a node into maintenance mode vs a node being marked unschedulable is an important distinction to make. Without the ability to differentiate, it does seem we need to revert #2986. 

@rohantmp Any other thoughts on how to approach this?

**Comment by rohantmp** [comment]
Perhaps we could use a specific taint as a way of signaling maintenance?

**Comment by rohantmp** [comment]
Or we could check to see if the node is unschedulable AND all osds on the node are down.

**Comment by rohantmp** [comment]
To prevent rook from reverting a manual nout, we could also use a key set in the `ceph config key` key-value store with no out-set-by and set it only if it's set by rook.

**Comment by BlaineEXE** [comment]
> Perhaps we could use a specific taint as a way of signaling maintenance?

This was brought up in the huddle meeting, but I don't really like it. It's kind of indirect, and I don't think that makes for a good user interface. Again, if it is to be a manual step, I think we might want to use a Ceph command to set noout on all the osds of a particular node. We might have to make an issue to get that added to Ceph.

> Or we could check to see if the node is unschedulable AND all osds on the node are down.

Not good if a node is marked as having disk pressure due to failure of a disk controller. That would result in both of these conditions, and this would prevent Ceph from doing the right things to maintain data integrity.

> To prevent rook from reverting a manual nout, we could also use a key set in the ceph config key key-value store with noout-set-by and set it only if it's set by rook.

This seems like a good idea for when Rook does implement setting `noout`. Personally, I don't see it being Rook's place to set `noout` except during upgrades/updates or replacement-type actions on specific osds. `noout` can affect Ceph's ability to properly fail over data and maintain a high data resiliency, and I think we should consider it Rook's responsibility to not expose easy ways for users to make poor cluster management decisions.

**Comment by rohantmp** [comment]
>This was brought up in the huddle meeting, but I don't really like it. It's kind of indirect, and I don't think that makes for a good user interface.

I think it has to be indirect because there needs to be a common way of setting node maintenance that all operators can respond to. I guess manual intervention is not a solved problem in the operator model because infra needs manual intervention.

There are operators like the [Node Maintenance operator](https://github.com/kubevirt/node-maintenance-operator) that take care of that, but I don't know if it's a good idea to tie rook to it. Maybe we should until there's a consensus on how to set maintenance in Kubernetes.

Just brainstorming: Maybe we could reuse the NodeMaintenance CRD without the presence of it's operator. We could petition them to add a time-estimation field, so we could calculate whether to migrate the data or wait for the node to come back from maintenance. 

> Again, if it is to be a manual step, I think we might want to use a Ceph command to set noout on all the osds of a particular node. We might have to make an issue to get that added to Ceph.

I opened https://tracker.ceph.com/issues/38940 a while back.

> Not good if a node is marked as having disk pressure due to failure of a disk controller. That would result in both of these conditions, and this would prevent Ceph from doing the right things to maintain data integrity.

Agreed.

**Comment by rohantmp** [comment]
Working on a quickfix to use a specific taint for now. Will initiate further discussion soon after.


We still need to check if the operator is the one who set noout to avoid undoing a user noout.
@leseb is it safe for rook to use the arbitrary ceph key-value store manipulated by ceph config? For example: 
```
[root@rook-ceph-operator-9d67d94bb-c9fhr /]# ceph config-key set rook_set_noout maintenance
set rook_set_noout
[root@rook-ceph-operator-9d67d94bb-c9fhr /]# ceph config-key dump rook_set_noout
{
    "rook_set_noout": "maintenance"
}
```
