### ISSUE TITLE
Failed upgrading from Mimic to Nautilus - mgr unable to perform ceph config set

### ISSUE THREAD

**Issue by monester** [rook/rook#3030]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Upgrade stopped in middle of upgrading ceph version. In logs of init containers for rook-ceph-mgr-a it says:

```
2019-04-23 14:12:01.822040 I | cephmgr: setting server_addr for the prometheus and dashboard modules
2019-04-23 14:12:01.822153 I | exec: Running command: ceph config get mgr.a mgr/prometheus/server_addr --format json --out-file /tmp/263044874
2019-04-23 14:12:02.111017 I | exec: Running command: ceph config set mgr.a mgr/prometheus/server_addr 87.233.136.4 --format json --out-file /tmp/471276257
2019-04-23 14:12:02.397964 I | exec: Error EINVAL: unrecognized config option 'mgr/prometheus/server_addr'
setting prometheus server_addr failed. failed to set mgr config key mgr/prometheus/server_addr to "87.233.136.4": exit status 22
```

prometheus is enabled in mgr, I've tried to disable and enable it back - it doesn't help

```
ceph mgr module ls | jq '.enabled_modules'
[
  "dashboard",
  "iostat",
  "prometheus",
  "restful"
]
```

and container is doing crash loops.

**Expected behavior:**

Upgrade worked with no problems.

**How to reproduce it (minimal and precise):**
- Install rook-operator 0.9.3
- Install ceph-cluster with Mimic ceph release from tag: ceph/ceph:v13.2.5-20190410
- check that cluster is working
- Change version of ceph to ceph/ceph:v14.2.0-20190410

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2
* Kernel (e.g. `uname -a`): 4.15.0-47-generic
* Cloud provider or hardware configuration: HW config: 3 nodes, 3 disks
* Rook version (use `rook version` inside of a Rook Pod): rook: v0.9.3
* Kubernetes version (use `kubectl version`): v1.13.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):
```
HEALTH_WARN no active mgr; too few PGs per OSD (5 < min 30); 5 monitors have not enabled msgr2
```

**Comment by leseb** [comment]
You need to wait for Rook 1.0 which will contain Ceph Nautilus.

**Comment by monester** [comment]
Oh, I didn't know that Nautilus isn't supported by 0.9.3. And in my configuration it says:
```yaml
spec:
  cephVersion:
    image: ceph/ceph:v14.2.0-20190410
    allowUnsupported: false
```
So I thought it is supported. Do you know when 1.0 would be released?

**Comment by leseb** [comment]
That's for the Cluster image, I'm talking about the operator image :).
Hopefully this week.

Thanks!

**Comment by travisn** [comment]
@monester v1.0 is released. Let us know if you see any issues with the [upgrade](https://rook.io/docs/rook/v1.0/ceph-upgrade.html)!
