### ISSUE TITLE
ceph: allow udevmonitor filtering to be configured

### ISSUE THREAD

**Issue by noahdesu** [rook/rook#3033]
The udevmonitor filtering should be configurable. The current specification is a disjunction of regexes that must match, and a conjunction of regexes that must not match. This is used to filter events like `add` and reject events like adding an `rbd` device.

```diff
+       go rawUdevBlockMonitor(events,
+               []string{"(?i)add", "(?i)remove"},
+               []string{"(?i)dm-[0-9]+", "(?i)rbd[0-9]+"})
```

The two open questions are, do we want something with different semantics (e.g. a basic whitelist/blacklist), and given a specification, how will it be encoded via environment variable.

**Comment by leseb** [comment]
@noahdesu didn't you solve that recently?

**Comment by noahdesu** [comment]
a patch went in recently that should resolve all the issues that have been reported so far, but haven't yet exposed this configuration (we just have the big disable-hotplug button right now).

**Comment by leseb** [comment]
So closing this or not? :)

**Comment by noahdesu** [comment]
please leave open.
