### ISSUE TITLE
Failed CephCluster CR configuration continues looping even if update is committed

### ISSUE THREAD

**Issue by travisn** [rook/rook#3047]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When editing the CephCluster CR and an incorrect configuration is edited, the orchestration will continue in a failing loop. If the user fixes the config, the operator should notice the update and try again with the new config instead of continuing with the outdated, incorrect, config.

The bad configuration was to run on a single-node k8s cluster with:
```
  mon:
    count: 5
    allowMultiplePerNode: false
```

The fix was to change it to `allowMultiplePerNode: true`. The only way to get the operator to pick up the change without waiting a really long time (the timeout is an hour of retrying) was to restart the operator.

**Expected behavior:**
The operator should pick up CR changes as soon as applied as long as the operator is not in the middle of another orchestration.

The solution may need to involve configuring the cluster in a goroutine and then managing the CR update events ourselves. Currently the behavior is that each CR watcher is essentially single-threaded, which keeps it simple until we hit scenarios like this.

**Comment by kshlm** [comment]
@travisn I'd like to take this issue up. Can you assign it to me please?
