### ISSUE TITLE
Mgr won't start when upgrading from v0.9 to 1.0, then upgrading to Nautilus

### ISSUE THREAD

**Issue by travisn** [rook/rook#3049]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When following the upgrade guide (#2965) to upgrade from v0.9.3 to v1.0 (latest master), and then upgrading the ceph version from 13.2.4 mimic to 14.2.0 nautilus, the mgr is failing to start.

The mgr is stuck on the `init-set-dashboard-server-addr` init container, indefinitely waiting for the command to return:
```
    Command:
      ceph
    Args:
      --fsid=c44acee1-2bd3-4f49-9edb-4d8d876521d6
      --keyring=/etc/ceph/admin-keyring-store/keyring
      --log-to-stderr=true
      --err-to-stderr=true
      --mon-cluster-log-to-stderr=true
      --log-stderr-prefix=debug 
      --mon-host=$(ROOK_CEPH_MON_HOST)
      --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
      config
      set
      mgr.a
      mgr/dashboard/server_addr
      $(ROOK_POD_IP)
```

The logs for the init container are the same msgrv1 messages found in #3048, so perhaps it's the same root cause. Here is the head of the log:
```
$ kn logs rook-ceph-mgr-a-dd9c94b5d-tpqxd init-set-dashboard-server-addr
parsed_args: Namespace(admin_socket=None, block=False, cephconf=None, client_id=None, client_name=None, cluster=None, cluster_timeout=None, completion=False, help=False, input_file=None, output_file=None, output_format=None, period=1, setgroup=None, setuser=None, status=False, verbose=True, version=False, watch=False, watch_channel='cluster', watch_debug=False, watch_error=False, watch_info=False, watch_sec=False, watch_warn=False), childargs: ['--fsid=c44acee1-2bd3-4f49-9edb-4d8d876521d6', '--keyring=/etc/ceph/admin-keyring-store/keyring', '--log-to-stderr=true', '--err-to-stderr=true', '--mon-cluster-log-to-stderr=true', '--log-stderr-prefix=debug ', '--mon-host=[v2:10.109.181.220:3300,v1:10.109.181.220:6790],[v2:10.107.197.153:3300,v1:10.107.197.153:6790],[v2:10.103.185.75:3300,v1:10.103.185.75:6790]', '--mon-initial-members=a,b,c', 'config', 'set', 'mgr.a', 'mgr/dashboard/server_addr', '172.17.0.15', '--force']
debug 2019-04-25 05:12:36.503 7fbb5d61f700 -1 --2-  >> [v2:10.107.197.153:3300/0,v1:10.107.197.153:6790/0] conn(0x7fbb60155920 0x7fbb60155df0 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer [v2:10.107.197.153:3300/0,v1:10.107.197.153:6790/0] is using msgr V1 protocol
```

**Expected behavior:**
This common upgrade path from 0.9 to 1.0 and then to nautilus will be a common path and must work. This path is also tested by the integration test added with #3022, which is failing for this reason.

@leseb thoughts on why this command would hang?

**How to reproduce it (minimal and precise):**

- Install v0.9.3 with the default settings
- Follow the upgrade guide in #2965 to upgrade the operator to rook/ceph:master (instead of v1.0 which isn't released yet)
- Wait for the upgrade to master to complete
- Set the CephCluster version to `ceph/ceph:v14`
- After the mons are updated, see the mgr hang

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by travisn** [comment]
Also fixed with #3051

**Comment by alexcpn** [comment]
This is happening from v1.4.1 to v1.4.7 upgrade. 

```
rook-ceph-mgr-a-577f6db6c7-jc9cx                              0/1     Init:1/3    0          16m
```
I have put ceph dashboard to false, still 
```
describe manager pod output

message: 'containers with incomplete status: [init-set-dashboard-server-addr init-set-prometheus-server-addr]'


init-set-dashboard-server-addr:
    Container ID:  docker://49df9c03a8609390838d076a7c73680831d7de80566afc002b01b41cb2c55581
    Image:         ceph/ceph:v15.2.4
    Image ID:      docker-pullable://ceph/ceph@sha256:60780a9cfc474726c7f24737aa8001ef5464f9fa15f481184539956c98cb0368
    Port:          <none>
    Host Port:     <none>
    Command:
      ceph
    Args:
      --fsid=47c0fd9e-2eb4-4ce3-8860-ee3ecf30ed97
      --keyring=/etc/ceph/admin-keyring-store/keyring
      --log-to-stderr=true
      --err-to-stderr=true
      --mon-cluster-log-to-stderr=true
      --log-stderr-prefix=debug
      --default-log-to-file=false
      --default-mon-cluster-log-to-file=false
      --mon-host=$(ROOK_CEPH_MON_HOST)
      --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
      --setuser=ceph
      --setgroup=ceph
      config
      set
      mgr.a
      mgr/dashboard/a/server_addr
      $(ROOK_POD_IP)
      --force
      --verbose
    State:          Running
      Started:      Wed, 16 Dec 2020 10:42:49 +0530
    Ready:          False
    Restart Count:  0
````

**Comment by travisn** [comment]
@alexcpn The mons are likely not responding. What is the `ceph status` in the toolbox?

**Comment by alexcpn** [comment]
@travisn this was a development cluster and we could not recover. So we had to reinstall this. However ceph status was in HEALTH ERROR telling 'no active manager'

All the mons were running
```
[Yesterday 09:29] Punnen, Alex (Nokia - IN/Bangalore)
    
rook-ceph-crashcollector-da-cicd-enc1-bl10      req/upd/avl: 1/1/1      rook-version=v1.4.7
rook-ceph-crashcollector-da-cicd-enc1-bl6       req/upd/avl: 1/1/1      rook-version=v1.4.7
rook-ceph-crashcollector-da-cicd-enc1-bl7       req/upd/avl: 1/1/1      rook-version=v1.4.7
rook-ceph-crashcollector-da-cicd-enc1-bl9       req/upd/avl: 1/1/1      rook-version=v1.4.7
rook-ceph-mgr-a         req/upd/avl: 1/1/       rook-version=v1.4.7
rook-ceph-mon-c         req/upd/avl: 1/1/1      rook-version=v1.4.7
rook-ceph-mon-e         req/upd/avl: 1/1/1      rook-version=v1.4.7
rook-ceph-mon-f         req/upd/avl: 1/1/1      rook-version=v1.4.7
rook-ceph-osd-0         req/upd/avl: 1/1/1      rook-version=v1.4.1
rook-ceph-osd-1         req/upd/avl: 1/1/1      rook-version=v1.4.1
rook-ceph-osd-2         req/upd/avl: 1/1/1      rook-version=v1.4.1
rook-ceph-osd-3         req/upd/avl: 1/1/1      rook-version=v1.4.1
rook-ceph-rgw-rook-ceph-objstore-a      req/upd/avl: 1/1/1      rook-version=v1.4.7
```
Anytime there is some problem like this in rook-ceph, we are finding it very hard to recover. Basically, some Ceph command was hanging. This caused one of the PVC not to be attachable.


```
 Warning  FailedMount  16m (x281 over 10h)    kubelet  Unable to mount volumes for pod "freeipa-6f67c4dbcb-xwmjk_daas(65be8c38-cd47-43c5-902a-134f6f597c21)": timeout expired waiting for volumes to attach or mount for pod "daas"/"freeipa-6f67c4dbcb-xwmjk". list of unmounted volumes=[data]. list of unattached volumes=[monitor data cgroups run tmp default-token-s4lc5]
  Warning  FailedMount  2m23s (x327 over 10h)  kubelet  MountVolume.MountDevice failed for volume "pvc-d137f5ba-089b-11eb-83a3-2a1c3f9db5a1" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000003-11009d7c-089c-11eb-8d9e-9a9b3bc0fce7 already exists
```

Recovering from a rook-ceph error is very difficult practically. We have to delete the current installation, remove stubborn rook-ceph namespace that refuses to go , and clean the /var/lib/rook in all workers and zero-set the drive for proper reinstallation.

Quite a lot to improve in recovery and debugging message.

Is there a feature or feasible
  - not to write anything to /var/lib folder in host and use etcd storage for that
  - to attach back the OSD on delete and restore of the namespace, assuming all the mon maps can be taken from above storage
  - better debugging message for Ceph

I had dome the upgrade in test cluster and it was fine. Actually in the same cluster when we reinstalled 1.4.7 it went through fine.

**Comment by travisn** [comment]
@alexcpn If the ceph commands aren't responding, it really sounds like your mons are not in quorum. This is the most critical part of ceph. If the mons aren't responding, the PVs will be stuck, IO will not respond, and the operator cannot repair anything automatically. So if you're having this problem regularly, we need to understand why multiple mons are falling out of quorum in your cluster(s).

> Is there a feature or feasible
> * not to write anything to /var/lib folder in host and use etcd storage for that

If you don't want the critical data to be written to /var/lib/rook, you can create the cluster on a PVC. Have you looked at the [cluster-on-pvc.yaml](https://rook.github.io/docs/rook/v1.5/ceph-cluster-crd.html#pvc-based-cluster) scenario? If running in a cloud environment where PVs are available, it's definitely recommended so you don't have a dependency on the local storage.

> * to recover the OSD's - ie attach back the OSD on delete and restore of the namespace, assuming all the mon maps can be taken from above storage

Yes, if the mons can be restored, the OSDs are also expected to come back.

> * better debugging message for Ceph

There are many log messages for the different components and log levels for Ceph. You've probably already been through the [troubleshooting guide](https://rook.github.io/docs/rook/v1.5/ceph-common-issues.html) many times to look at the logs, but I assume the main probably is that it's just not clear what the problem is when Ceph is not responding. Again, the mon quorum are likely the issue.

**Comment by alexcpn** [comment]
thanks a lot. I will try this option or running in local persistent volume. I also found this TopoLVM onfluence.ext.net.nokia.com/display/NDAC/Infra+Items that I believe will make this Rook on PVC more stable
