### ISSUE TITLE
Ceph MGR Dashboard NFS access returns with 401

### ISSUE THREAD

**Issue by galexrt** [rook/rook#3052]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When trying to access the Ceph MGR dashboard "NFS" tab and the `/api/nfs-ganesha/export` API using the latest `master` manifests and Rook images, fails with 401 error.
API returned error:
```
Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 653, in respond\n    self.hooks.run('before_handler')\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 112, in run\n    raise exc\nHTTPError: (401, 'You are not authorized to access that resource')\n`
```

I'm only seeing "normal" access logs in the mgr logs:

```
debug 2019-04-25 15:29:56.753 7f9952120700  0 log_channel(cluster) log [DBG] : pgmap v44: 200 pgs: 200 active+clean; 9.5 KiB data, 108 MiB used, 1.9 TiB / 1.9 TiB avail; 1.2 KiB/s rd, 2 op/s
212.99.205.154 - - [25/Apr/2019:15:29:57] "GET /ceph-dashboard/api/summary HTTP/1.1" 200 252 "http://k8s-monitoring.acs-cloud.de/ceph-dashboard/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36"
212.99.205.157 - - [25/Apr/2019:15:29:57] "GET /ceph-dashboard/api/health/minimal HTTP/1.1" 200 426 "http://k8s-monitoring.acs-cloud.de/ceph-dashboard/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36"
212.99.205.156 - - [25/Apr/2019:15:29:57] "POST /ceph-dashboard/api/auth/check HTTP/1.1" 200 40 "http://k8s-monitoring.acs-cloud.de/ceph-dashboard/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36"
debug 2019-04-25 15:29:58.754 7f9952120700  0 log_channel(cluster) log [DBG] : pgmap v45: 200 pgs: 200 active+clean; 9.5 KiB data, 108 MiB used, 1.9 TiB / 1.9 TiB avail; 853 B/s rd, 1 op/s
```

**Expected behavior:**

Dashboard page for the NFS servers running and the API to return a successful result.

**How to reproduce it (minimal and precise):**

1. Start up current `master` images (`v0.9.0-493.g62dadab`).
2. Create Cluster, filesystem and nfs.yaml.
3. Navigate to dashboard, login and try to go to the "NFS" tab.
4. Get kicked back to login and see in browser console that a 401 error has occured (api just returns 401).

Or just follow https://ceph.com/community/deploying-a-cephnfs-server-cluster-with-rook/ post.

**Environment**:
* Ceph version: `ceph/ceph:v14.2.0-20190410`
* Rook version (use `rook version` inside of a Rook Pod): `v0.9.0-493.g62dadab`
* Kubernetes version (use `kubectl version`): `v1.14.1`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)): `HEALTH_OK`

**Comment by jtlayton** [comment]
This looks more like a bug in ceph-mgr or (more likely) one of its modules. I'd suggest moving this to a ceph bug instead. It's not clear to me what version of ceph you're running here either, so please do provide that info as well.

**Comment by galexrt** [comment]
@jtlayton I have added the Ceph version (`ceph/ceph:v14.2.0-20190410`) to the `environment` section of the description. I'll open an issue tomorrow.

This is from current `master` branch 5f16f8e27f568bd4f6952450180538ba0d43b246 / 62dadab2ba8e69b4cdda5ca7340f2954228bf409 of the Rook repo.

**Comment by sebastian-philipp** [comment]
@galexrt can you open a ticket in the ceph tracker?

**Comment by KM612** [comment]
I meet the same trouble

**Comment by gs80140** [comment]
same with me
