### ISSUE TITLE
Prototype RGW as a pod

### ISSUE THREAD

**Issue by travisn** [rook/rook#306]
When running in k8s, each system component should be its own pod and replication set, with rook being implemented as an operator (controller). RGW is the simplest to break off first to test this approach.

**Comment by hunter** [comment]
Interesting approach and closer to how Ceph on K8s is set to run in ceph-docker. It would mean that K8s can manage/optimize the resource limits and placement specifically for each component.

We've been working with Ceph on K8s with a large number of OSDs and splitting each disk/device across the nodes as a [DaemonSet](https://github.com/AcalephStorage/ceph-docker/blob/more-kube-examples/examples/kubernetes/host/ceph-osd-v1-ds-sdc-hdd.yaml) to allow finer control of an OSD lifecycle (rolling updates, crush location, etc). Would actually be better handled with an Operator though.

**Comment by travisn** [comment]
@hunter, that's right that we see k8s being able to have finer control of the lifecycle as the components are broken up. Mons, OSDs, MDS, RGW, etc all have different load and scale properties. For k8s to manage resources and place them optimally we see the benefits of breaking it down at that level. Rook has started with the scenario where k8s isn't in the picture so needs its own orchestration, but we can optimize with k8s.
