### ISSUE TITLE
Ceph cluster deployment is missing designation for critical pods

### ISSUE THREAD

**Issue by tlvenn** [rook/rook#3071]
The Ceph cluster deployment must use the scheduler.alpha.kubernetes.io/critical-pod annotation to prevent these critical pods to be evicted when a node reaches capacity.

**Comment by travisn** [comment]
Thanks for pointing this out, we should add these annotations to the mons and osds.

**Comment by tlvenn** [comment]
Happy to take care of this simple PR

**Comment by nzoueidi** [comment]
@tlvenn are you working on it? I am in the queue of taking this.

**Comment by tlvenn** [comment]
Please do @nzoueidi , thanks !

**Comment by kichristensen** [comment]
Please take into account that the annotation is deprecated as of K8S 1.13 and removed in 1.14 according to the documentation, instead pod priorities should be used, https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
