### ISSUE TITLE
Support NFS CRD update event

### ISSUE THREAD

**Issue by ashishranjan738** [rook/rook#3072]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Currently, NFS operator doesn't support the update event of NFS CRD. The update event has to be supported as this will be very useful for day2 operations.

**Expected behavior:**
The NFSServer deployment should get updated based on the new configuration of NFS CRD during update.

**How to reproduce it (minimal and precise):**
-> Deploy a NFSServer.
-> Change the configuration of NFS Server CRD.

**Comment by Steuf** [comment]
Should be great ! We can't add new exports on existing nfs server, when we need new nfs volume for a project we need to create a new nfsserver.

Must be great to just update an existing nfsserver with new export.

**Comment by Steuf** [comment]
Just according to this design document https://github.com/rook/rook/blob/master/design/nfs.md ;)

**Comment by RainingNight** [comment]
Any news?

**Comment by prksu** [comment]
Hi @RainingNight this feature already added by this PR https://github.com/rook/rook/pull/5650
