### ISSUE TITLE
Add configuration validation for NFS CRD

### ISSUE THREAD

**Issue by ashishranjan738** [rook/rook#3073]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Currently, we don't have any validation for NFS CRD regarding export configurations.
One possible validation can be:
-> Duplicate export should not be allowed.

**Expected behavior:**
Invalid configurations should be rejected during the object creation.

**Comment by travisn** [comment]
Fixed by #5650
