### ISSUE TITLE
Ceph Dashboard showing deleted persistent volumes

### ISSUE THREAD

**Issue by marcstreeter** [rook/rook#3080]
**Bug Report**
After deleting persistent volume instance, it is still showing in the rook dashboard
**Expected behavior:**
After deleting persistent volume instance, it does not show in the rook dashboard.
**Deviation from expected behavior:**
It shows in the rook dashboard.
**How to reproduce it (minimal and precise):**

1. Create dynamically provisioned persistent volume claim (set to retain after deletion).
2. Delete PVC
3. Delete PV
4. Check Rook Dashboard and still see PVC you deleted showing

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): Linux node4 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): 0.9.3
* Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] : dashboard says `HEALTH_OK`

**Comment by alfonsomthd** [comment]
@sebastian-philipp Provided rook version is 0.9.3 and for this version only ceph luminous and mimic are supported:
https://github.com/rook/rook/blob/v0.9.3/cluster/examples/kubernetes/ceph/cluster.yaml
We should determine which ceph version was running in order to know what dashboard version is.
