### ISSUE TITLE
cluster did not want to start - stuck job

### ISSUE THREAD

**Issue by davidkarlsen** [rook/rook#3081]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Cluster did not reach a started state

**Expected behavior:**
Cluster should be in started state

**How to reproduce it (minimal and precise):**
Unsure what triggered it.

**Environment**:
* OS (e.g. from /etc/os-release):
```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

* Kernel (e.g. `uname -a`):
```
uname -a
Linux main.lan.davidkarlsen.com 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

* Cloud provider or hardware configuration:
bare-metal x86

* Rook version (use `rook version` inside of a Rook Pod):
```
rook version
 rook: v0.9.3
```

* Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm on baremetal

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
N/A - failing state gone after deleting the version detect job

See thread in https://rook-io.slack.com/archives/C46Q5UC05/p1556566212170100
`kubectl -nrook-ceph describe cephcluster` gave:
```
  Message:  giving up creating cluster in namespace rook-ceph after 1h0m0s
```

Doing ` kubectl -nrook-ceph delete job rook-ceph-detect-version` and then deleting all rook pods made the cluster available again.

**Comment by travisn** [comment]
When the operator is detecting the ceph version, we should create a clean job instead of waiting for an existing one if found. This was in the log:
```
Found previous job rook-ceph-detect-version
```

The [RunReplaceableJob](https://github.com/rook/rook/blob/master/pkg/operator/k8sutil/job.go#L32) method should delete the job if it is found instead of waiting for it. The job to detect the ceph version doesn't have any state that would be at risk if the job is deleted. However, this same method is used for other daemons such as OSDs. We should be careful about deleting them in that case, so let's start by only making this change to detect the ceph version. `RunReplaceableJob` can have a param that indicates if the existing job should be always deleted if found.

**Comment by kshlm** [comment]
> `RunReplaceableJob` can have a param that indicates if the existing job should be always deleted if found.

@travisn If the param isn't set, and an existing job is found, then we need wait like as we do now. Right?

**Comment by travisn** [comment]
@kshlm Yes, let's leave the osd and mds jobs remain unaffected for now, thanks.

**Comment by Harold2017** [comment]
same problem but can NOT succeed to start after delete job and re-create rook-ceph pods.
got this log:
```bash
2019-05-16 10:21:54.557625 I | op-cluster: starting cluster in namespace rook-ceph
2019-05-16 10:21:54.561036 I | op-k8sutil: verified the ownerref can be set on resources
2019-05-16 10:21:54.569887 I | op-k8sutil: waiting for job rook-ceph-detect-version to complete...
```
- rook image: rook/ceph:master
- ceph image: ceph/ceph:v14.2.1-20190430

**Comment by travisn** [comment]
@Harold2017 Are the logs available for the rook-ceph-detect-version job pod?

**Comment by Harold2017** [comment]
@travisn no, since the pod is stuck at pending status, no logs for this pod.
always stuck here as following...
```bash
rook-ceph     rook-ceph-agent-mwttm                                   1/1     Running   0          3m7s
rook-ceph     rook-ceph-agent-n7rwv                                   1/1     Running   0          3m7s
rook-ceph     rook-ceph-agent-p6vp6                                   1/1     Running   0          3m7s
rook-ceph     rook-ceph-detect-version-8r4wv                          0/1     Pending   0          2m1s
rook-ceph     rook-ceph-operator-7b976856bf-fgcnc                     1/1     Running   0          3m31s
rook-ceph     rook-discover-88tdg                                     1/1     Running   0          3m7s
rook-ceph     rook-discover-kr4cm                                     1/1     Running   0          3m7s
rook-ceph     rook-discover-pwf2d                                     1/1     Running   0          3m7s
```

**Comment by travisn** [comment]
What does kubectl describe tell you about the pending pod?

**Comment by Harold2017** [comment]
Thanks for your fast response, i found if i turn change `hostNetwork` to `false`, it will not stuck here now..
