### ISSUE TITLE
ceph mon,OSD pods are not created after excecuting cluster.yaml file 

### ISSUE THREAD

**Issue by thundertiger825** [rook/rook#3082]
Emvironment:
OS   :4 fedora 29 server virtual machines 
RAM: 2GB
Storage: 20 GB with two 8GB extra storage attached for OSD

*****Cluster.yaml file***************

No osd and mon pods are created after executing cluster.yaml

kubectl get pods -n rook-ceph
NAME                                  READY   STATUS    RESTARTS   AGE
rook-ceph-agent-5f8vh                 1/1     Running   1          19h
rook-ceph-agent-ccw9k                 1/1     Running   0          20h
rook-ceph-agent-rbh85                 1/1     Running   0          20h
rook-ceph-operator-7b976856bf-gs7wc   1/1     Running   0          20h
rook-discover-899gk                   1/1     Running   0          20h
rook-discover-97rg9                   1/1     Running   1          19h
rook-discover-x759h                   1/1     Running   0          20h

**Comment by sp98** [comment]
@thundertiger825 Can you please add rook-ceph-operator logs as well.

**Comment by thundertiger825** [comment]
2019-04-29 09:22:59.105161 I | rookcmd: starting Rook v0.9.0-526.gb35615f with arguments '/usr/local/bin/rook ceph operator'
2019-04-29 09:22:59.106182 I | rookcmd: flag values: --alsologtostderr=false, --csi-attacher-image=quay.io/k8scsi/csi-attacher:v1.0.1, --csi-cephfs-image=quay.io/cephcsi/cephfsplugin:v1.0.0, --csi-cephfs-plugin-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin.yaml, --csi-cephfs-provisioner-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner.yaml, --csi-enable-cephfs=false, --csi-enable-rbd=false, --csi-provisioner-image=quay.io/k8scsi/csi-provisioner:v1.0.1, --csi-rbd-image=quay.io/cephcsi/rbdplugin:v1.0.0, --csi-rbd-plugin-template-path=/etc/ceph-csi/rbd/csi-rbdplugin.yaml, --csi-rbd-provisioner-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner.yaml, --csi-registrar-image=quay.io/k8scsi/csi-node-driver-registrar:v1.0.2, --csi-snapshotter-image=quay.io/k8scsi/csi-snapshotter:v1.0.1, --help=false, --log-flush-frequency=5s, --log-level=INFO, --log_backtrace_at=:0, --log_dir=, --log_file=, --logtostderr=true, --mon-healthcheck-interval=45s, --mon-out-timeout=10m0s, --skip_headers=false, --stderrthreshold=2, --v=0, --vmodule=
2019-04-29 09:22:59.112767 I | cephcmd: starting operator
2019-04-29 09:22:59.335087 I | op-agent: getting flexvolume dir path from FLEXVOLUME_DIR_PATH env var
2019-04-29 09:22:59.335152 I | op-agent: flexvolume dir path env var FLEXVOLUME_DIR_PATH is not provided. Defaulting to: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
2019-04-29 09:22:59.335175 I | op-agent: discovered flexvolume dir path from source default. value: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
2019-04-29 09:22:59.335195 I | op-agent: no agent mount security mode given, defaulting to 'Any' mode
2019-04-29 09:22:59.353818 I | op-agent: rook-ceph-agent daemonset started
2019-04-29 09:22:59.395317 I | op-discover: rook-discover daemonset started
2019-04-29 09:22:59.450052 I | operator: rook-provisioner ceph.rook.io/block started using ceph.rook.io flex vendor dir
2019-04-29 09:22:59.450478 I | operator: rook-provisioner rook.io/block started using rook.io flex vendor dir
2019-04-29 09:22:59.450505 I | operator: Watching the current namespace for a cluster CRD
2019-04-29 09:22:59.450514 I | op-cluster: start watching clusters in all namespaces
2019-04-29 09:22:59.450555 I | op-cluster: Enabling hotplug orchestration: ROOK_DISABLE_DEVICE_HOTPLUG=false
I0429 09:22:59.451595       6 leaderelection.go:217] attempting to acquire leader lease  rook-ceph/ceph.rook.io-block...
I0429 09:22:59.451906       6 leaderelection.go:217] attempting to acquire leader lease  rook-ceph/rook.io-block...
2019-04-29 09:22:59.487757 I | op-cluster: skipping watching for legacy rook cluster events (legacy cluster CRD probably doesn't exist): the server could not find the requested resource (get clusters.ceph.rook.io)
I0429 09:22:59.550286       6 leaderelection.go:227] successfully acquired lease rook-ceph/ceph.rook.io-block
I0429 09:22:59.577716       6 controller.go:769] Starting provisioner controller ceph.rook.io/block_rook-ceph-operator-7b976856bf-gs7wc_61591422-6a60-11e9-9314-0242ac1e1502!
I0429 09:22:59.577846       6 event.go:209] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"rook-ceph", Name:"ceph.rook.io-block", UID:"6169d871-6a60-11e9-8a40-0800279bc493", APIVersion:"v1", ResourceVersion:"2067280", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-7b976856bf-gs7wc_61591422-6a60-11e9-9314-0242ac1e1502 became leader
I0429 09:22:59.582112       6 leaderelection.go:227] successfully acquired lease rook-ceph/rook.io-block
I0429 09:22:59.582845       6 controller.go:769] Starting provisioner controller rook.io/block_rook-ceph-operator-7b976856bf-gs7wc_615e8930-6a60-11e9-9314-0242ac1e1502!
I0429 09:22:59.582903       6 event.go:209] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"rook-ceph", Name:"rook.io-block", UID:"616e02aa-6a60-11e9-8a40-0800279bc493", APIVersion:"v1", ResourceVersion:"2067281", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-7b976856bf-gs7wc_615e8930-6a60-11e9-9314-0242ac1e1502 became leader
I0429 09:22:59.684442       6 controller.go:818] Started provisioner controller ceph.rook.io/block_rook-ceph-operator-7b976856bf-gs7wc_61591422-6a60-11e9-9314-0242ac1e1502!
I0429 09:23:00.583085       6 controller.go:818] Started provisioner controller rook.io/block_rook-ceph-operator-7b976856bf-gs7wc_615e8930-6a60-11e9-9314-0242ac1e1502!
E0429 09:34:12.145380       6 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1.CephCluster.Spec: v1.ClusterSpec.Storage: v1alpha2.StorageScopeSpec.Selection: Directories: []v1alpha2.Directory: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ctories":{"path":"/v|..., bigger context ...|izeMB":"1024"},"deviceFilter":null,"directories":{"path":"/var/lib/test"},"location":null,"nodes":[{|...
E0429 09:34:12.153238       6 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1.CephCluster.Spec: v1.ClusterSpec.Storage: v1alpha2.StorageScopeSpec.Selection: Directories: []v1alpha2.Directory: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ctories":{"path":"/v|..., bigger context ...|izeMB":"1024"},"deviceFilter":null,"directories":{"path":"/var/lib/test"},"location":null,"nodes":[{|...
W0429 09:34:12.153924       6 reflector.go:289] github.com/rook/operator-kit/watcher.go:76: watch of *v1.CephCluster ended with: very short watch: github.com/rook/operator-kit/watcher.go:76: Unexpected watch close - watch lasted less than a second and no items received
E0429 09:34:13.159101       6 reflector.go:126] github.com/rook/operator-kit/watcher.go:76: Failed to list *v1.CephCluster: v1.CephClusterList.Items: []v1.CephCluster: v1.CephCluster.Spec: v1.ClusterSpec.Storage: v1alpha2.StorageScopeSpec.Selection: Directories: []v1alpha2.Directory: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ctories":{"path":"/v|..., bigger context ...|izeMB":"1024"},"deviceFilter":null,"directories":{"path":"/var/lib/test"},"location":null,"nodes":[{|...
E0429 09:34:14.162998       6 reflector.go:126] github.com/rook/operator-kit/watcher.go:76: Failed to list *v1.CephCluster: v1.CephClusterList.Items: []v1.CephCluster: v1.CephCluster.Spec: v1.ClusterSpec.Storage: v1alpha2.StorageScopeSpec.Selection: Directories: []v1alpha2.Directory: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ctories":{"path":"/v|..., bigger context ...|izeMB":"1024"},"deviceFilter":null,"directories":{"path":"/var/lib/test"},"location":null,"nodes":[{|...

**Comment by galexrt** [comment]
@thundertiger825 Can you post your Ceph `cluster.yaml`?

**Comment by thundertiger825** [comment]
#################################################################################################################
# Define the settings for the rook-ceph cluster with common settings for a production cluster.
# All nodes with available raw devices will be used for the Ceph cluster. At least three nodes are required
# in this example. See the documentation for more details on storage settings available.

# For example, to create the cluster:
#   kubectl create -f common.yaml
#   kubectl create -f operator.yaml
#   kubectl create -f cluster.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # The container image used to launch the Ceph daemon pods (mon, mgr, osd, mds, rgw).
    # v12 is luminous, v13 is mimic, and v14 is nautilus.
    # RECOMMENDATION: In production, use a specific version tag instead of the general v14 flag, which pulls the latest release and could result in different
    # versions running within the cluster. See tags available at https://hub.docker.com/r/ceph/ceph/tags/.
    image: ceph/ceph:v14.2.0-20190410
    # Whether to allow unsupported versions of Ceph. Currently luminous, mimic and nautilus are supported, with the recommendation to upgrade to nautilus.
    # Do not set to true in production.
    allowUnsupported: false
  # The path on the host where configuration files will be persisted. Must be specified.
  # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
  # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
  dataDirHostPath: /var/lib/rook
  # set the amount of mons to be started
  mon:
    count: 3
    allowMultiplePerNode: false
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # serve the dashboard using SSL
    # ssl: true
  network:
    # toggle to use hostNetwork
    hostNetwork: false
  rbdMirroring:
    # The number of daemons that will perform the rbd mirroring.
    # rbd mirroring must be configured with "rbd mirror" from the rook toolbox.
    workers: 0
  # To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
  # The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage-node' and
  # tolerate taints with a key of 'storage-node'.
#  placement:
#    all:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#          - matchExpressions:
#            - key: role
#              operator: In
#              values:
#              - storage-node
#      podAffinity:
#      podAntiAffinity:
#      tolerations:
#      - key: storage-node
#        operator: Exists
# The above placement information can also be specified for mon, osd, and mgr components
#    mon:
#    osd:
#    mgr:
  annotations:
#    all:
#    mon:
#    osd:
# If no mgr annotations are set, prometheus scrape annotations will be set by default.
#   mgr:
  resources:
# The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
#    mgr:
#      limits:
#        cpu: "500m"
#        memory: "1024Mi"
#      requests:
#        cpu: "500m"
#        memory: "1024Mi"
# The above example requests/limits can also be added to the mon and osd components
#    mon:
#    osd:
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    deviceFilter:
    location:
    config:
      # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
      # Set the storeType explicitly only if it is required not to use the default.
      # storeType: bluestore
       databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
       journalSizeMB: "1024"  # uncomment if the disks are 20 GB or smaller
      # osdsPerDevice: "1" # this value can be overridden at the node or device level
      # encryptedDevice: "true" # the default value for this option is "false"
# Cluster level list of directories to use for filestore-based OSD storage. If uncommented, this example would create an OSD under the dataDirHostPath.
    directories:
     path: "/var/lib/rook"
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    nodes:
    - name: "fed-worker"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/mnt/test"
      resources:
        limits:
          cpu: "500m"
          memory: "1024Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
#    - name: "172.17.4.201"
#      devices: # specific devices to use for storage can be specified for each node
#      - name: "sdb"
#      - name: "nvme01" # multiple osds can be created on high performance devices
#        config:
#          osdsPerDevice: "5"
#      config: # configuration can be specified at the node level which overrides the cluster level config
#        storeType: filestore
#    - name: "172.17.4.301"
#      deviceFilter: "^sd."






Here fed-worker is name of node for osd

**Comment by thundertiger825** [comment]
`#################################################################################################################
# Define the settings for the rook-ceph cluster with common settings for a production cluster.
# All nodes with available raw devices will be used for the Ceph cluster. At least three nodes are required
# in this example. See the documentation for more details on storage settings available.

# For example, to create the cluster:
#   kubectl create -f common.yaml
#   kubectl create -f operator.yaml
#   kubectl create -f cluster.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # The container image used to launch the Ceph daemon pods (mon, mgr, osd, mds, rgw).
    # v12 is luminous, v13 is mimic, and v14 is nautilus.
    # RECOMMENDATION: In production, use a specific version tag instead of the general v14 flag, which pulls the latest release and could result in different
    # versions running within the cluster. See tags available at https://hub.docker.com/r/ceph/ceph/tags/.
    image: ceph/ceph:v14.2.0-20190410
    # Whether to allow unsupported versions of Ceph. Currently luminous, mimic and nautilus are supported, with the recommendation to upgrade to nautilus.
    # Do not set to true in production.
    allowUnsupported: false
  # The path on the host where configuration files will be persisted. Must be specified.
  # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
  # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
  dataDirHostPath: /var/lib/rook
  # set the amount of mons to be started
  mon:
    count: 3
    allowMultiplePerNode: false
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # serve the dashboard using SSL
    # ssl: true
  network:
    # toggle to use hostNetwork
    hostNetwork: false
  rbdMirroring:
    # The number of daemons that will perform the rbd mirroring.
    # rbd mirroring must be configured with "rbd mirror" from the rook toolbox.
    workers: 0
  # To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
  # The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage-node' and
  # tolerate taints with a key of 'storage-node'.
#  placement:
#    all:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#          - matchExpressions:
#            - key: role
#              operator: In
#              values:
#              - storage-node
#      podAffinity:
#      podAntiAffinity:
#      tolerations:
#      - key: storage-node
#        operator: Exists
# The above placement information can also be specified for mon, osd, and mgr components
#    mon:
#    osd:
#    mgr:
  annotations:
#    all:
#    mon:
#    osd:
# If no mgr annotations are set, prometheus scrape annotations will be set by default.
#   mgr:
  resources:
# The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
#    mgr:
#      limits:
#        cpu: "500m"
#        memory: "1024Mi"
#      requests:
#        cpu: "500m"
#        memory: "1024Mi"
# The above example requests/limits can also be added to the mon and osd components
#    mon:
#    osd:
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
    deviceFilter:
    location:
    config:
      # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
      # Set the storeType explicitly only if it is required not to use the default.
      # storeType: bluestore
       databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
       journalSizeMB: "1024"  # uncomment if the disks are 20 GB or smaller
      # osdsPerDevice: "1" # this value can be overridden at the node or device level
      # encryptedDevice: "true" # the default value for this option is "false"
# Cluster level list of directories to use for filestore-based OSD storage. If uncommented, this example would create an OSD under the dataDirHostPath.
    directories:
     path: "/var/lib/rook"
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    nodes:
    - name: "fed-worker"
      directories: # specific directories to use for storage can be specified for each node
      - path: "/mnt/test"
      resources:
        limits:
          cpu: "500m"
          memory: "1024Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
#    - name: "172.17.4.201"
#      devices: # specific devices to use for storage can be specified for each node
#      - name: "sdb"
#      - name: "nvme01" # multiple osds can be created on high performance devices
#        config:
#          osdsPerDevice: "5"
#      config: # configuration can be specified at the node level which overrides the cluster level config
#        storeType: filestore
#    - name: "172.17.4.301"
#      deviceFilter: "^sd."
`

**Comment by thundertiger825** [comment]
Here fed-worker is name of node for osd

**Comment by leseb** [comment]
output of `kubectl -n rook-ceph get cephcluster.ceph.rook.io rook-ceph`?

**Comment by atagunduzalp** [comment]
Anything new on this topic ?

**Comment by foux** [comment]
I have the same issue with this cluster configuration : 
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.2-20190722
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
    # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
    # urlPrefix: /ceph-dashboard
    # serve the dashboard at the given port.
    # port: 8443
    # serve the dashboard using SSL
    # ssl: true
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  annotations:
  resources:
    mgr:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter: "sdb"
    config:
      nodes:
        - name: "kube02"
        - name: "kube03"
```

Output of `kubectl -n rook-ceph get cephcluster.ceph.rook.io rook-ceph` : 
```
NAME        DATADIRHOSTPATH   MONCOUNT   AGE    STATE   HEALTH
rook-ceph   /var/lib/rook     3          116s
```

@thundertiger825 did you manage to find the issue?

**Comment by atagunduzalp** [comment]
I have same issue, osd pods never starts running. Then I realized that the paths which are given in .yaml file does not exist on my nodes. 
Normally, it creates if does not exist but I dont why, it didnt.
So, after I added paths manually, it worked for me.

**Comment by foux** [comment]
Thanks @atagunduzalp. But what `path` are you talking about, the `dataDirHostPath` or the directories `path`? Because I d'ont have a directory `path` (I'm using devices), ans my `dataDirHostPath` exists on all nodes, but I still get the error : 
```github.com/rook/operator-kit/watcher.go:76: Failed to list *v1.CephCluster: v1.CephClusterList.Items: []v1.CephCluster: v1.CephCluster.Spec: v1.ClusterSpec.Storage: v1alpha2.StorageScopeSpec.Config: ReadString: expects " or n, but found [, error found in #10 byte of ...|{"nodes":[{"name":"k|..., bigger context ...|memory":"1024Mi"}}},"storage":{"config":{"nodes":[{"name":"kube02"},{"name":"kube03"}]},"deviceFilte|...
```
Thanks.

**Comment by atagunduzalp** [comment]
For me, on my nodes missing one is: 
> path: "/rook/storage-dir"

Also make sure nothing left from previous deployment trials. 
You may check:
> path: "/var/lib/rook"

Also in your operator yaml, check:
```
# - name: FLEXVOLUME_DIR_PATH
#   value: "<PathToFlexVolumes>"

```
If you did not specified a path, default one is:
> /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ 
Here is the link: [https://github.com/rook/rook/blob/master/Documentation/flexvolume.md](url)
After I deleted everything under these folder, it worked for me.
