### ISSUE TITLE
ceph-volume should reject metadataDevice which has same storage class as data devices

### ISSUE THREAD

**Issue by clkao** [rook/rook#3092]
(Followup to #2777)

OSDs are now bootstrapped with `ceph-volume`, with optional metadataDevice.   `ceph-volume` does all the magic putting db volume onto metadataDevice, if it is a faster device (eg ssd).  If one specify hdd for both metadataDevice, and device, `ceph-volume` will actually create two hdd OSDs, which is not what the user would expected.  In this case, the metadataDevice config should be rejected. it should warn the user, and proceed with bootstrapping the osd without metadataDevice.

**Comment by lewismarshall** [comment]
When devices are presented using RAID controllers or in cloud they will often present as non-rotational e.g. SSD even when they are either HDD or slow EBS:
```
# nvme1n1 is a 'standard' ebs (e.g. rotational HDD)
[root@ip-192-168-15-251 rook-ceph]# cat /sys/block/nvme1n1/queue/rotational
0
```

Would like to be able to override this behaviour to be able to add metadataDevice to existing clusters.

**Comment by hdimitriou** [comment]
So what if we have an SSD for OSD and a faster SSD we want to use for metadataDevice? 
My VM perceived both as rotational, so I used udev to change the medatadata volume as non-rotational, i guess that works?
