### ISSUE TITLE
log collection and aggregation

### ISSUE THREAD

**Issue by jbw976** [rook/rook#312]
Debugging issues across a multi machine cluster is difficult because we have no log collection or aggregation.  The logs must be looked at on each individual machine, which slows us down.

We should think through how best to collect and aggregate rook cluster logs so debugging issues that affect the cluster (instead of a single machine) is easier.

Sometimes, just knowing who the leader was during an orchestration is enough to quickly go to the right host and get good logs.  Maybe each node can log who the leader is at the start of each orchestration, that could get us by for a bit without implementing full log collection and aggregation.

**Comment by travisn** [comment]
with kubernetes the log collection is not a problem. This should only apply to standalone, which is gone now
