### ISSUE TITLE
The rook/ceph:v1.0.0 image has 3 high security vulnerabilities. 

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#3120]
**Is this a bug report or feature request?**
* Bug Report

Below 3 high vulnerabilities are identified with rook/ceph:v1.0.0 image.
1). https://access.redhat.com/errata/RHSA-2019:0710
package_name: python-libs
installed_version: 2.7.5-76.el7
cve_fixed_version:0:2.7.5-77.el7_6

2).  https://access.redhat.com/errata/RHSA-2019:0679
package_name: libssh2
installed_version: 1.4.3-12.el7
cve_fixed_version: 0:1.4.3-12.el7_6.2

3). https://access.redhat.com/errata/RHSA-2019:0710
package_name: python
installed_version: 2.7.5-76.el7
cve_fixed_version: 0:2.7.5-77.el7_6

**Deviation from expected behavior:**
The old release is used which involves vulnerabilities.

**Expected behavior:**
Please use updated release to eliminate the above vulnerabilities.

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@yanchicago The `rook/ceph` image is based on the `ceph/ceph` image. Could you open this issue in the [ceph/ceph-container](https://github.com/ceph/ceph-container) repo? Thanks!

**Comment by yanchicago** [comment]
@travisn I've scanned ceph image v14.2.1-20190430 and it doesn't have the above vulnerability. 
My understanding is that the rook image has "v14.2.0-20190319" as base which has the above issues. 
If you may build with v14.2.1, the issue should go away. Below is the Makefile.  Unfortunately, I haven't setup my dev env. Otherwise, I would help to fix it. 
---------------------------------------------
grep CEPH_VERSION /root/rook-release-1.0/images/ceph/Makefile
CEPH_VERSION = v14.2.0-20190319
BASEIMAGE = ceph/ceph-$(GOARCH):$(CEPH_VERSION)
