### ISSUE TITLE
rook toolbox: reports multiple ceph versions

### ISSUE THREAD

**Issue by diontje** [rook/rook#3121]
the ceph binary inside the toolbox reports multiple versions of ceph depending on how ceph version is called.

s1:~ # kubectl exec -n rook-ceph rook-ceph-tools-77fb5d749-bnnmp -- ceph version
ceph version 12.2.11 (26dc3775efc7bb286a1d6d66faee0ba30ea23eee) luminous (stable)
s1:~ # kubectl exec -n rook-ceph rook-ceph-tools-77fb5d749-bnnmp -- /usr/bin/ceph --version
ceph version 13.2.2 (02899bfda814146b021136e9d8e80eba494e1126) mimic (stable)

I would expect both command options if supported to return the same ceph installed version string.
For this case, I am running ceph/ceph:v12.2.11-20190319

**How to reproduce it (minimal and precise):**
Install ceph/ceph:v12.2.11-20190319 via rook/ceph:v0.9.3
Execute kubectl commands from above

**Environment**:
SLES15
* Kernel (e.g. `uname -a`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

s1:~ # kubectl exec -n rook-ceph rook-ceph-tools-77fb5d749-bnnmp -- /usr/bin/ceph status
  cluster:
    id:     a4f7df39-09aa-4ea5-b1b0-cf526f890b46
    health: HEALTH_WARN
            Degraded data redundancy: 192/597 objects degraded (32.161%), 88 pgs degraded, 100 pgs undersized
            clock skew detected on mon.b

  services:
    mon: 3 daemons, quorum c,a,b
    mgr: a(active)
    mds: myfs-1/1/1 up  {0=myfs-b=up:active}, 1 up:standby-replay
    osd: 2 osds: 2 up, 2 in

  data:
    pools:   3 pools, 300 pgs
    objects: 213 objects, 502MiB
    usage:   2.87GiB used, 37.1GiB / 40.0GiB avail
    pgs:     192/597 objects degraded (32.161%)
             200 active+clean
             88  active+undersized+degraded
             12  active+undersized

  io:
    client:   852B/s rd, 11.3KiB/s wr, 1op/s rd, 0op/s wr

**Comment by travisn** [comment]
@diontje There are several documented version arguments to `ceph`. While confusing at first glance, I believe what you're seeing is expected:
- `ceph --version`: The version of the client tools in the local container (will be constant for the toolbox pod in a given release of rook... mimic for 0.9 and nautilus for 1.0)
- `ceph version`: The version of running ceph mon daemons
- `ceph versions`: The version of each of the ceph daemons in the cluster

**Comment by diontje** [comment]
awesome. thanks for clarification.
