### ISSUE TITLE
rook mgr SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by NickUfer** [rook/rook#3122]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The mgr opens with the dashboard but it has just an empty page. After some time the web panel crashes. Something with the "rook" ceph module is not right. It cannot verify some certificate.
SSL/TLS is turned on for the mgr and it creates a new certificate on every pod recreation.

```
debug 2019-05-06 18:47:45.695 7f19e2794700  1 mgr[restful] server not running: no certificate configured
[06/May/2019:18:47:45] ENGINE Started monitor thread '_TimeoutMonitor'.
debug 2019-05-06 18:47:45.759 7f19e1f93700 -1 log_channel(cluster) log [ERR] : Unhandled exception from module 'rook' while running on mgr.a: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)
debug 2019-05-06 18:47:45.759 7f19e1f93700 -1 rook.serve:
[06/May/2019:18:47:45] ENGINE Bus STARTING
[06/May/2019:18:47:45] ENGINE Serving on :::9283
[06/May/2019:18:47:45] ENGINE Bus STARTED
[06/May/2019:18:47:45] ENGINE Started monitor thread '_TimeoutMonitor'.
debug 2019-05-06 18:47:45.759 7f19e1f93700 -1 Traceback (most recent call last):
  File "/usr/share/ceph/mgr/rook/module.py", line 280, in serve
    self._k8s.list_namespaced_pod(cluster_name)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12514, in list_namespaced_pod
    (data) = self.list_namespaced_pod_with_http_info(namespace, **kwargs)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 12617, in list_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 81, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 247, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)

[06/May/2019:18:47:45] ENGINE Serving on :::8443
[06/May/2019:18:47:45] ENGINE Bus STARTED
```

**Expected behavior:**

The mgr doesn't crash and the dashboard shows information.

**How to reproduce it (minimal and precise):**

Upgrade vom 0.9 to 1.0.

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 18.10 (Cosmic Cuttlefish)`
* Kernel (e.g. `uname -a`): `Linux <servername> 4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`): `rook: v1.0.0-9.g5060a89`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `Kubernetes`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): 
`HEALTH_ERR Module 'rook' has failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618); 1 monitors have not enabled msgr2`

**Comment by sebastian-philipp** [comment]
Looks like the mgr pod cannot validate the kubernetes ssl certificate. Could you verify that the kubernetes certificate can be validated from within the pods?

https://github.com/kubernetes-client/python/issues?utf8=%E2%9C%93&q=is%3Aissue+%22certificate+verify+failed%22

**Comment by NickUfer** [comment]
@sebastian-philipp Thanks :+1: That hint helped me to find the real problem. I've created the kubernetes CA as an intermediate CA of my own root CA and somehow this didn't work.

**Comment by hightoxicity** [comment]
Hi, I'm on the same boat here.
I use An intermediate CA signed under my company root CA.

The tools container is complaining the following:

>  health: HEALTH_ERR
>             Module 'rook' has failed: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)

I was wondering if the problem was not just my root CA (it should work with only this one) or intermediate CA missing in the mgr container cert trust bundle (/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem).

I imagine that the mgr container is using pod env vars to talk to kube?!

I was previously running a rook 0.9.3 with this same self signed CA binded as kube CA and there was no problem.
I think this issue should not be closed and a way to add custom CA certs in the cert bundle should be provided if the diagnostic is the good one.


Thx.

**Comment by sebastian-philipp** [comment]
The rook orchestrator is new in nautilus. With Nautilus, the mgr pod uses the Python client libraries within the rook-ceph-mgr pod to talk to the k8s API. And this failed.

**Comment by hightoxicity** [comment]
OK, I would have thought that the kube python client was just using a wrapper to the openssl library of the image, but I do not know much about python ... And since this version of openssl (centos) is a fips version, it is problematic for some CA roots depending how they have been generated...

**Comment by hightoxicity** [comment]
https://github.com/kubernetes-client/python-base/issues/136

**Comment by hightoxicity** [comment]
If some people hit the same issue using an intermediate CA, you can turn on PodPreset as an admission controller and inject the cert bundle (root ca + kube intermediate one) with :

```
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: fix-ceph-ca-bundle
  namespace: rook-ceph
spec:
  selector:
    matchLabels:
      app: rook-ceph-mgr
  volumeMounts:
     mountPath: /run/secrets/kubernetes.io/serviceaccount/ca.crt
      name: cabundle
      subPath: ca.crt
  volumes:
    - name: cabundle
      configMap:
        name: cabundle
```

**Comment by jr200** [comment]
Can this be re-opened?  Like @hightoxicity, I have a kubernetes cluster with an external intermediate CA. I'm trying to run the ceph dashboard.  The [mgr page](https://docs.ceph.com/docs/mimic/mgr/dashboard/#ssl-tls-support) describes how one can import custom certificates signed and issued by a CA, rather than using a self-signed certificate.  My cluster does not have the PodPreset admission controller enabled, so the above is not a solution.

In @whereisaaron, there is a [suggestion](https://github.com/rook/rook/issues/2433#issuecomment-451678763) to allow mounting a TLS secret into the pod as an override, which seems like a neater solution than the above.

Would there be any plans to implement this?

**Comment by sebastian-philipp** [comment]
Right, there is some work going on with https://github.com/ceph/ceph/pull/30482 . In a follow up PR, this could be made available for the dashboard, too.

**Comment by valentin2105** [comment]
If someone looking for a fix in this issue,

My Cluster is build on a intermediate CA  (Core CA => k8s-CA) and Python-requests need the fullchain to verify the API endpoint. 

If you don't have PodPreset  (deprecated), you can create manualy the `fullchain-ca.crt` file with the CoreCA and the k8s CA and give it to your `kube-controller-manager` 's `root-ca-file` argument,

That will create the ConfigMap `kube-root-ca.crt` and be mounted in your pod. 

(you can delete the old configmap to get the new one). 

It fix my issue for Ceph activate the rook module.

**Comment by allidoiswin10** [comment]
@valentin2105 thanks! Worked for me!
