### ISSUE TITLE
ROOK_ENABLE_FSGROUP prevents changing the root folder permissions of rook-block

### ISSUE THREAD

**Issue by dimm0** [rook/rook#3123]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Running a simple pod with rook-block PVC and user changed:

```
  securityContext:
    fsGroup: 100
    runAsUser: 1000
```

The mounted block device belongs to root.

The operator has ROOK_ENABLE_FSGROUP=false

**Expected behavior:**
The root folder should be chown'ed, the rest of folders should stay untouched

**How to reproduce it (minimal and precise):**

Run a pod with above securityContext defined, check block device permissions

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
1.0.0
* Kubernetes version (use `kubectl version`):
1.13.5

**Comment by travisn** [comment]
@dimm0 Thanks for the reminder on this, we need to revive #2564. Since #3086 was masking testing this issue, hopefully this will be more straight forward now.

**Comment by dimm0** [comment]
This was working ok in 0.9.3.. Some chowning was already fixed, and at least the rook folder was properly chowned. Now it's broken again...

**Comment by dimm0** [comment]
Just to remind: we want root folder to be chowned always, and all children depending on the flag

**Comment by travisn** [comment]
Since #2557 was backported to 0.9 and released with 0.9.3, I thought those options to disable fsgroup and selinux relabeling were broken. Are you sure 0.9.3 wasn't still always recursively labeling everything?

**Comment by dimm0** [comment]
Ah!! Makes sense now, yes, I think it was broken, and our users learned to get around it..

**Comment by dimm0** [comment]
Hmm... I'm trying to disable those now, and it's still not chowning the folder..

**Comment by dimm0** [comment]
> Hmm... I'm trying to disable those now, and it's still not chowning the folder..

Nevermind, I'm not patient enough, disabled fine.

**Comment by dimm0** [comment]
Full chown is working as expected, but root folder chown is now still broken

**Comment by dimm0** [comment]
Fixed in csi
