### ISSUE TITLE
Increase the number of CI runners

### ISSUE THREAD

**Issue by jbw976** [rook/rook#3130]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** The CI system has more work than it's current number of parallel runners can keep up with.  We should increase the number of CI runners from 2 -> 4.

**What is use case behind this feature:** Having more CI processing power will keep the CI queue running and allow moving features into master and releases more quickly.

**Comment by jbw976** [comment]
What exactly is involved in supporting this change? Is it just increasing a single number field or is it more involved?

**Comment by Defilan** [comment]
This is usually a really simple fix. In fact, I just changed the number of runners from 2 -> 4. That being said, this config of Jenkins is unique and I want to make sure to monitor it to see if that did the trick or if something else might be needed.

**Comment by travisn** [comment]
We have more runners now!
