### ISSUE TITLE
Ceph Octopus: HEALTH_WARN: crush map has legacy tunables (require firefly, min is hammer)

### ISSUE THREAD

**Issue by sebastian-philipp** [rook/rook#3138]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

```
[root@kubic-1 /]# ceph status
  cluster:
    id:     0268c660-555c-4fc3-8c56-34386f55ac08
    health: HEALTH_WARN
            crush map has legacy tunables (require firefly, min is hammer)
 
  services:
    mon: 1 daemons, quorum a (age 2m)
    mgr: a(active, since 99s)
    osd: 0 osds: 0 up, 0 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     
 
[root@kubic-1 /]# ceph osd crush dump | jq .tunables
{
  "choose_local_tries": 0,
  "choose_local_fallback_tries": 0,
  "choose_total_tries": 50,
  "chooseleaf_descend_once": 1,
  "chooseleaf_vary_r": 1,
  "chooseleaf_stable": 0,
  "straw_calc_version": 1,
  "allowed_bucket_algs": 22,
  "profile": "firefly",
  "optimal_tunables": 0,
  "legacy_tunables": 0,
  "minimum_required_version": "firefly",
  "require_feature_tunables": 1,
  "require_feature_tunables2": 1,
  "has_v2_rules": 0,
  "require_feature_tunables3": 1,
  "has_v3_rules": 0,
  "has_v4_buckets": 0,
  "require_feature_tunables5": 0,
  "has_v5_rules": 0
}
```

relates to #743

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**Environment**:
* Cloud provider or hardware configuration: Kubic
* Rook version (use `rook version` inside of a Rook Pod): 1.0
* Kubernetes version (use `kubectl version`): 1.14
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubernetes

**Comment by djgalloway** [comment]
I reproduced this (unintentionally) using OpenShift 4.2.

```
rook image: quay.io/rhceph-dev/rook@sha256:a3f00a6fb70fd6d4cf3fd6532de7e8f03d8f34e046595011a16eb4f4475cc08e
rook version:  rook: 1.0.0-81.ga7df349f
rook package version: rook-1.0.0-81.ga7df349f.el8cp.x86_64

ceph image: quay.io/rhceph-dev/rhceph-4.0-rhel-8@sha256:ef5c7109879bc2c14b934e7e920da7081d305c84587bb1fcfe5b3b1124b3c74f
ceph version: ceph version 14.2.1-385-g4ae8136 (4ae8136c865add0d5e4dc4feab44b5c77607eb4e) nautilus (stable)
ceph package version: ceph-common-14.2.1-385.g4ae8136.el8cp.x86_64

oc version:
  Client Version: version.Info{Major:"4", Minor:"2+", GitVersion:"v4.2.0", GitCommit:"75945bd89", GitTreeState:"clean", BuildDate:"2019-05-31T13:22:16Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0+8d0b5d2", GitCommit:"8d0b5d2", GitTreeState:"clean", BuildDate:"2019-06-03T10:39:04Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by leseb** [comment]
I'm gonna fix that one soon!

**Comment by djgalloway** [comment]
I'm still seeing this.

```
rook image: quay.io/rhceph-dev/rook@sha256:e710d83a67f5f1d650cdf6195784c5c32e22c6266644ba4a7e1c505bf8803014
rook version:  rook: 1.0.0-157.g18cca312
rook package version: rook-1.0.0-157.g18cca312.el8.x86_64

ceph image: quay.io/rhceph-dev/rhceph-4.0-rhel-8@sha256:5945ffbd936378e4458fad5cdc3673350d88b0376226f0782f83390743c15332
ceph version: ceph version 14.2.1-602-g51abe8f (51abe8f00e1a8f0b4408d67a6a6c08437c159de9) nautilus (stable)
ceph package version: ceph-common-14.2.1-602.g51abe8f.el8cp.x86_64
```

Here's the full archive of OpenShift and Rook logs: [archive.zip](https://github.com/rook/rook/files/3347844/archive.zip)

**Comment by djgalloway** [comment]
@leseb do you have any idea what could be happening here off the top of your head?  I don't see the word `firefly` almost anywhere in the rook repo that could be causing this at this point.  Is that tuneable a Ceph default or something?

**Comment by travisn** [comment]
@djgalloway was there an upgrade involved? Or this is just a clean install?

**Comment by djgalloway** [comment]
@travisn Clean install.

**Comment by leseb** [comment]
@djgalloway it'll be in 1.0.3.

**Comment by djgalloway** [comment]
https://github.com/rook/rook/commit/18cca312059f9699dd89165558c91b721ec5878b

**Comment by leseb** [comment]
@djgalloway new fix incoming.`

**Comment by djgalloway** [comment]
Fix confirmed! :champagne:

**Comment by jpiper** [comment]
I had this on upgrading to `1.0.4` and ceph version `14.2.2`

running `ceph osd crush tunables optimal` from the tools pod sorted it

**Comment by hansbogert** [comment]
> running `ceph osd crush tunables optimal` from the tools pod sorted it

this messed up my cluster even more, since my worker nodes, ubuntu 16.04 with kernel 4.4, could no longer mount rbd's since kernel 4.4 is only hammer-compatible.

after a long debug, the only thing I had to do was decompile my crush map, and change all the `straw` buckets to, `straw2`. The warnings in ceph are really bad in explaining that `straw` is a firefly setting.
Imo, this is the real fix without changing the compatibility of your cluster and its possible breakage for clients.

**Comment by jpiper** [comment]
Ah, I’m on 4.14. I’ll edit my comment to highlight it could mess things up

**Comment by sebastian-philipp** [comment]
> > running `ceph osd crush tunables optimal` from the tools pod sorted it
> 
> this messed up my cluster even more, since my worker nodes, ubuntu 16.04 with kernel 4.4, could no longer mount rbd's since kernel 4.4 is only hammer-compatible.
> 
> after a long debug, the only thing I had to do was decompile my crush map, and change all the `straw` buckets to, `straw2`. The warnings in ceph are really bad in explaining that `straw` is a firefly setting.
> Imo, this is the real fix without changing the compatibility of your cluster and its possible breakage for clients.

@dillaman  fyi. Is something were we can improve the usability?

**Comment by dillaman** [comment]
@sebastian-philipp This isn't really my area of expertise in Ceph

**Comment by airdos360** [comment]
I am running an upgraded install to 1.0.6 and  V14.2.4 and getting health warn: crush map has legacy tunables (require firefly, min is hammer)

How do I fix this error?

Should I run:
kubectl -n $ROOK_NAMESPACE exec -it $TOOLS_POD -- ceph stop creating initial crushmap
