### ISSUE TITLE
object store creation is failing on multi node bare metal cluster

### ISSUE THREAD

**Issue by jbw976** [rook/rook#314]
@DanKerns multi node bare metal cluster is running into a failure getting object store created and initialized.  The built in user creation is what appears to be failing (but RGW service gets running at least accessible from s3 tools?):
```
Dec 20 20:24:52 castle7 rkt[1887]: 2016-12-20 20:24:52.776900 E | cephmgr: Failed to configure object service. failed to enable the object store. failed to get create first user. failed to read user info. invalid character '-' after top-level value, result=2016-12-20 20:24:42.755728 bf75240  0 ERROR: failed to distribute cache for default.rgw.users.uid:rookadmin
Dec 20 20:24:52 castle7 rkt[1887]: 2016-12-20 20:24:52.764993 bf75240  0 ERROR: failed to distribute cache for default.rgw.users.keys:KF0VETTC2PZJNEQJ5RCM
```
We need to look into why we might be seeing the root cause of `failed to distribute cache for default.rgw.users.uid:rookadmin`.

**Comment by travisn** [comment]
we haven't seen this in kubenernetes. please reopen if we get a repro
