### ISSUE TITLE
Prometheus in rook-ceph not working due to missing rolebinding

### ISSUE THREAD

**Issue by sandrich** [rook/rook#3147]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After installing prometheus for rook-ceph I get the following errors in prometheus 

````
level=error ts=2019-05-09T13:46:01.727660291Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:302: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:rook-ceph:prometheus\" cannot list resource \"pods\" in API group \"\" in the namespace \"rook-ceph\""
````

````
[root@master monitoring]# kubectl get rolebinding -n rook-ceph
NAME                     AGE
rook-ceph-cluster-mgmt   4d4h
rook-ceph-mgr            4d4h
rook-ceph-mgr-system     4d4h
rook-ceph-osd            4d4h
rook-ceph-system         4d4h
````
**Expected behavior:**
Prometheus being able to function

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): centos-7
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod): 1.0
* Kubernetes version (use `kubectl version`): 1.14
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by galexrt** [comment]
@sandrich Which Manifests did you use? These https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph/monitoring.

**Comment by sandrich** [comment]
@galexrt no actially from the 1.0 release branch

https://github.com/rook/rook/tree/release-1.0?files=1

**Comment by sandrich** [comment]
@galexrt I checked out the master branch and applied the monitoring manifests. Now it works

```
[root@master rook]# cd cluster/examples/kubernetes/ceph/monitoring/
[root@master monitoring]# kubectl apply -f .
prometheusrule.monitoring.coreos.com/prometheus-ceph-rules created
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
service/rook-prometheus configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
serviceaccount/prometheus configured
clusterrole.rbac.authorization.k8s.io/prometheus configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
clusterrole.rbac.authorization.k8s.io/prometheus-rules configured
clusterrolebinding.rbac.authorization.k8s.io/prometheus configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
prometheus.monitoring.coreos.com/rook-prometheus configured
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
servicemonitor.monitoring.coreos.com/rook-ceph-mgr configured
```

**Comment by travisn** [comment]
the monitoring manifests are still the same between the release-1.0 branch and master. Is it possible you had some other version when it was failing?

**Comment by sandrich** [comment]
All I can think of is that I might forgot to apply a manifest. This time I did an apply to all manifest.

If you want I can try to reproduce it again

**Comment by sandrich** [comment]
@travisn I can't even reproduce myself. Removed all and reinstalled. Works like a charm.
