### ISSUE TITLE
Ceph Teardown instructions need updating due to manifest changes

### ISSUE THREAD

**Issue by galexrt** [rook/rook#3148]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The https://rook.io/docs/rook/v1.0/ceph-teardown.html page is outdated for the splitted manifest files.

**Comment by sebastian-philipp** [comment]
fyi, https://github.com/sebastian-philipp/test-rook-orchestrator/blob/master/undeploy-rook-ceph.sh  for my use case.
