### ISSUE TITLE
At startup, OSDs should regenerate the ceph conf file

### ISSUE THREAD

**Issue by travisn** [rook/rook#315]
In case the monitors changed (failover, or added more mons), the ceph config file should be regenerated when the osds (and other ceph services) start. If the change happens while the osd is still running, the active connection to the mon should update the live config in the osd so this is just an issue at restart.

**Comment by jbw976** [comment]
This may come along naturally with the whole "pods query the API server for their config upon start up" design that we've been chatting about in https://github.com/rook/rook/issues/397#issuecomment-289156161 and targeting for v0.5.

**Comment by bassam** [comment]
+1. Would be great if all "config" state was regenerable from TPRs and etcd (for standalone).

**Comment by travisn** [comment]
the config state should already be independent from the environment so it should be straight forward. To the daemon it just looks like command line arguments, which would change based on config maps and tprs in k8s, or etcd for standalone

**Comment by bzub** [comment]
When this is implemented be sure to warn users that if they have custom settings they might get changed/removed.  Maybe make a backup of the existing config files for them?

**Comment by jbw976** [comment]
good point @bzub.  We'll need to think through what those custom settings may be, hopefully they can be honored much like the existing `--ceph-config-override` flag is treated.  Let us know if there is specific configuration (outside of just ceph config file entries) that are important to you.  I'm also hoping that as the project continues to mature, the need for custom settings by the user (often to workaround Rook limitations) will become less frequent.
