### ISSUE TITLE
DEBUG=1 is not honored by the build

### ISSUE THREAD

**Issue by jbw976** [rook/rook#316]
`make DEBUG=1 build` is intended to keep full debugging symbols, but they are still being stripped.  At @bassam's suggestion, removing the '-s' from https://github.com/rook/rook/blob/master/build/makelib/golang.mk#L105 solves the issue and the resultant binary is not stripped.

I assume that '-s' should conditionally be included, but not certain of what the conditions are exactly.

**Comment by bassam** [comment]
related to #135

**Comment by bassam** [comment]
will track this in #135
