### ISSUE TITLE
Only reboot can add extra osd disk to ceph cluster

### ISSUE THREAD

**Issue by liuyongqing1** [rook/rook#3167]
yes
**Is this a bug report or feature request?**
* Bug Report

rook-ceph v0.9.3

I encountered the same problem with this issue, https://github.com/rook/rook/issues/2830, but I don't know how to solve it. Please help me solve it. I don't know much about how https://github.com/rook/rook/pull/2780 is solved.

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):    CentOS Linux release 7.3.1611 (Core)
* Kernel (e.g. `uname -a`):   Linux 172-20-50-178 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 13:29:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 0.9.3
* Kubernetes version (use `kubectl version`): 1.9.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] (https://rook.io/docs/rook/master/ceph-toolbox.html)): normal

**Comment by travisn** [comment]
@liuyongqing1 Can you provide more details about your scenario? Did you physically attach a new device to a node? Did you add the device to the cluster CR? Was the disk already there, but you decided later to add it to the cluster CR? 

If you update the cluster CR or you attach a new device, with the v1.0 release Rook will automatically create an OSD for the device if it matches the settings in the cluster CR.

**Comment by liuyongqing1** [comment]
@travisn 
I solved it, I use the zstack virtual machine, the newly added hard disk can be seen in lsblk. But apply -f cluster.yaml prepare is skipped. After that I tried to restore the cluster.yaml configuration, then apply -f cluster.yaml and then add the new disk to cluster.yaml and then apply -f will take effect.

**Comment by liuyongqing1** [comment]
I can't use rook ceph 1.0 because I am using kubernetes 1.9.11

**Comment by liuyongqing1** [comment]
In addition, I also found a problem. After configuring Separate Storage Groups, everything works fine, but after the three nodes are restarted, it becomes the following result. I don't know what is going on, and my data has been lost.

 rook-ceph -- ceph  osd tree
ID  CLASS WEIGHT  TYPE NAME               STATUS REWEIGHT PRI-AFF
 -9             0 root ssd
-10             0     host 192.168.100.12
-11             0     host 192.168.100.13
-12             0     host 192.168.100.14
 -1       1.20959 root default
 -3       0.40320     host 192-168-100-12
  0   hdd 0.11020         osd.0               up  1.00000 1.00000
  1   hdd 0.29300         osd.1               up  1.00000 1.00000
 -5       0.40320     host 192-168-100-13
  2   hdd 0.29300         osd.2               up  1.00000 1.00000
  3   hdd 0.11020         osd.3               up  1.00000 1.00000
 -7       0.40320     host 192-168-100-14
  4   hdd 0.11020         osd.4               up  1.00000 1.00000
  5   hdd 0.29300         osd.5               up  1.00000 1.00000



 rook-ceph -- ceph  osd status
+----+----------------+-------+-------+--------+---------+--------+---------+-----------+
| id |      host      |  used | avail | wr ops | wr data | rd ops | rd data |   state   |
+----+----------------+-------+-------+--------+---------+--------+---------+-----------+
| 0  | 192.168.100.12 | 5157M |  194G |    0   |     0   |    1   |    16   | exists,up |
| 1  | 192.168.100.12 | 11.0G |  288G |    0   |     0   |    1   |    90   | exists,up |
| 2  | 192.168.100.13 | 9.88G |  290G |    0   |     0   |    0   |     0   | exists,up |
| 3  | 192.168.100.13 | 6366M |  193G |    0   |     0   |    0   |     0   | exists,up |
| 4  | 192.168.100.14 | 5804M |  194G |    0   |     0   |    0   |     0   | exists,up |
| 5  | 192.168.100.14 | 10.4G |  289G |    0   |     0   |    0   |     0   | exists,up |
+----+----------------+-------+-------+--------+---------+--------+---------+-----------+



Previously osd1 3 4 was configured in root ssd. Now it has become default


After rebooting, the reboot state is
 Rook-ceph -- ceph health

HEALTH_WARN 13740/72930 objects misplaced (18.840%); Reduced data availability: 100 pgs inactive, 3 pgs peering

**Comment by liuyongqing1** [comment]
I re-added the previous three osds to the crush ssd, and that's fine. But I don't know why the whole cluster will be lost when it restarts together.

**Comment by travisn** [comment]
With rook 0.9, you will need to restart the operator in order to install the OSDs on new devices. Note that 1.0 should still technically run on K8s 1.9, we just don't run the tests on that version anymore. 

It certainly is not expected for the data to be lost in any reboot scenario. Did all the pods come back up? According to your screenshot it appears all the osds are up so the data should be available. What does `ceph status` show?

**Comment by liuyongqing1** [comment]
ceph status is 

HEALTH_WARN 13740/72930 objects misplaced (18.840%); Reduced data availability: 100 pgs inactive, 3 pgs peering

**Comment by caisan** [comment]
@liuyongqing1 this issue may help you : https://github.com/rook/rook/issues/2830

**Comment by caisan** [comment]
@liuyongqing1 you can also refer to this PR https://github.com/rook/rook/pull/2780

**Comment by liuyongqing1** [comment]
I still don't know what caused this reason until now. I didn't understand the two problems. As I wrote the first one
