### ISSUE TITLE
Rook operator looping on initialization

### ISSUE THREAD

**Issue by dab-q** [rook/rook#3185]
* Bug Report

When bringing up Rook/Ceph, the operator got stuck in a loop redoing the cluster initialization.  The osd-prepare pods were being restarted multiple times.  It didn't get to the point where it was watching for CRDs to create storageclasses, pools or filesystems.  The Ceph cluster itself came up, and all the OSDs joined the ceph cluster.

When I set ROOK_DISABLE_DEVICE_HOTPLUG=true, everything came up.

I'm attaching the operator debug log from an instance of it looping.

[rook-operator-log.txt](https://github.com/rook/rook/files/3184370/rook-operator-log.txt)

**Environment**:
* OS: SLES12SP3
* Kernel:Linux xxx 4.4.155-94.50-default #1 SMP Tue Sep 11 13:04:00 UTC 2018 (bc8c7c0) x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration: bare-metal
* Rook version: v1.0.1
* Kubernetes version: 1.13.3
* Kubernetes cluster type: bare-metal/kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
sh-4.2# ceph status
  cluster:
    id:     9b92d3e1-ec7d-423b-ab18-9e85f81ce9c7
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 6m)
    mgr: a(active, since 86s)
    osd: 16 osds: 16 up (since 3m), 16 in (since 3m)

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   16 GiB used, 29 TiB / 29 TiB avail
    pgs:

This is a four node cluster, with four 1.8 TB disks on each node, each configured with Bluestore.

**Comment by travisn** [comment]
Reopening for backport to 1.0

**Comment by leseb** [comment]
Closing since 1.0.2 is out.
