### ISSUE TITLE
Unexpected 500 error on api when monitor is restarting

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#319]
Node 10.1.1.7 was rebooting and I noticed that API calls to node 10.1.1.5 were failing with code 500 (Internal Server Error) which is unexpected.

Log shows:
`Dec 28 18:28:14 castle5 rkt[1887]: 2016-12-28 18:28:14.615596 I | api: b8f834b8-eac5-4ac1-a8fd-2fb72f281e15        GET        /status        GetStatusDetails        (start)
Dec 28 18:28:15 castle5 rkt[1887]: 2016-12-28 18:28:15.615854 E | api: failed to connect to cluster as admin: client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://10.1.2.7:53379 exceeded header timeout
Dec 28 18:28:15 castle5 rkt[1887]: 2016-12-28 18:28:15.615892 I | api: b8f834b8-eac5-4ac1-a8fd-2fb72f281e15        GET        /status        GetStatusDetails        500 Internal Server Error        1.000303613s`

The previous call to /status returned:

`OVERALL STATUS: WARNING

SUMMARY:
SEVERITY   MESSAGE
WARNING    pool Dan has many more objects per pg than average (too few pgs?)

USAGE:
TOTAL        USED         DATA         AVAILABLE
130.97 TiB   196.27 GiB   140.90 GiB   130.78 TiB

MONITORS:
NAME      ADDRESS           IN QUORUM   STATUS
mon2      10.1.1.5:6790/0   true        OK
mon0      10.1.1.7:6790/0   true        OK
mon4      10.1.1.8:6790/0   true        OK

OSDs:
TOTAL     UP        IN        FULL      NEAR FULL
40        40        40        false     false

PLACEMENT GROUPS (2148 total):
STATE          COUNT
active+clean   2148`

Which makes me think that mon0 is "special" in some way.  Note that node 10.1.1.5 was also a monitor.

**Comment by travisn** [comment]
Daemons are more isolated with kubernetes so I don't anticipate this is an issue now
