### ISSUE TITLE
`rook object connection` returns rotating values for AWS_ENDPOINT

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#320]
When using the `rook object connection` command on a multinode cluster, successive calls return different values for `AWS_ENDPOINT`.

Presumably the API server looks up the IP endpoints of RGW instances from etcd and just returns the first one.  The ordering isn’t guaranteed by etcd, so we don’t always return the same value.

This is very confusing to end users.

When running as a Kubernetes pod we should always return the single IP of the ingress controller.

**Comment by travisn** [comment]
Closing all tickets related to standalone. See #985.
