### ISSUE TITLE
Document ceph block provisioner xfs minimum size limitation.

### ISSUE THREAD

**Issue by stekylsha** [rook/rook#3207]
**Is this a bug report or feature request?**
* Feature Request
Add documentation regarding minimum persistent volume size for ceph block provisioner when fsyype is xfs.

**What should the feature do:**
Document that rook-ceph xfs persistent volumes must be at least 16Mi or formatting will fail, leaving the volume unformatted.   The volume mount will then fail since it is not xfs formatted.

**What is use case behind this feature:**
After spending days trying to figure out why a rook-ceph pvc of 10Mi would work when using ext4 but not with xfs, I thought it would be a Good Thing to make sure it is documented so others will learn from my mistake, misfortune, and misadventure.

**Environment**:
rook 0.9.0, 0.9.3, 1.0.0 where
```
provisioner: ceph.rook.io/block
```
and
```
parameters:
  fstype: xfs
```

**Comment by stekylsha** [comment]
This is a request to include the minimum size limitation for xfs volumes in the rook documentation.  Is there a better place to document it?

**Comment by leseb** [comment]
@stekylsha the Rook doc is good place for this, do you mind sending a pull request for this? Thanks.
