### ISSUE TITLE
Failed to bring up kube using minikube

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#3208]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
not able to deploy Kube cluster  using minikube script in the tests folder

**Expected behavior:**
should be able to bring up single node kube cluster using minikube

**How to reproduce it (minimal and precise):**

starting minikube is failing with below error  message
```
./tests/scripts/minikube.sh up

Error: specified key could not be found in config
```
**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
@travisn @kshlm I think am facing issue may be  because of https://github.com/rook/rook/commit/24d7c3059b8f5cf8fc92ce7659b31ebe6a151953

**Comment by kshlm** [comment]
Sorry! I'll fix that today.

**Comment by kshlm** [comment]
@Madhu-1 can you test the updated script?
