### ISSUE TITLE
Ceph MGR re-initializes every 60 seconds

### ISSUE THREAD

**Issue by mjrepo2** [rook/rook#3210]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** Ceph mgr resets every minute, resetting dashboard/flags, etc

**Expected behavior:** Ceph mgr stays stable

**How to reproduce it (minimal and precise):**
Rook/Ceph was simply deployed with common.yaml cluster.yaml & operator.yaml
We have two clusters, one of which is stable and one keeps resetting.
The mgr beacon is active as well.
Unfortunately the logs aren't showing very much - if someone knows which logs I should provide - I will.

**Environment**:
* OS (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"

* Kernel (e.g. `uname -a`):
Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 
* Kubernetes version (use `kubectl version`): 1.13.3
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox]
(https://rook.io/docs/rook/master/ceph-toolbox.html)):
ceph> health detail
HEALTH_WARN noout flag(s) set
OSDMAP_FLAGS noout flag(s) set
(the flags are falling on and off)

**Comment by leseb** [comment]
Looks more like a Ceph Mgr thing than a Rook one.
Can you elaborate, what do you exactly mean by resetting?

Thanks!

**Comment by travisn** [comment]
@mjrepo2 Are you running rook from `master`? If so, this could be related to the new liveness probe for the mgr
