### ISSUE TITLE
Difference in operator-openshift-with-csi.yaml and operator-openshift.yaml

### ISSUE THREAD

**Issue by vavuthu** [rook/rook#3211]
I see a difference in parameters in rook/cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml and rook/cluster/examples/kubernetes/ceph/operator-openshift.yaml

Mainly I am interested in parameters ROOK_LOG_LEVEL, ROOK_MON_HEALTHCHECK_INTERVAL, ROOK_MON_OUT_TIMEOUT, etc.. which are present in Flex based operator-openshift.yaml but not in operator-openshift-with-csi.yaml.

Are those removed intentionally or missed out ?

**Comment by petr-balogh** [comment]
I am also interested about some documentation which we can follow for those parameters.
When I looked at github repository and used search like this:
https://github.com/rook/rook/search?q=ROOK_LOG_LEVEL&unscoped_q=ROOK_LOG_LEVEL

But didn't find any documentation for this ENV parameter. I think that documentation [here](https://rook.io/docs/rook/v1.0/) is generated from the same repository. Is there some way how to search in the documentation? I didn't find it.

**Comment by travisn** [comment]
@petr-balogh The only documentation for the operator env vars is in the operator.yaml.

Closing this issue since the csi driver is enabled now by default and the operator-openshit-with-csi.yaml was removed.
