### ISSUE TITLE
Add support for openstack-helm usage

### ISSUE THREAD

**Issue by intelliguy** [rook/rook#3216]
hi, all

* Feature Request

**What should the feature do:**
I suggest a feature to support Prometheus in openstack-helm(aka. osh) project. 
https://docs.openstack.org/openstack-helm/latest/readme.html

**What is use case behind this feature:**
osh provide some module to support operations and Prometheus is provided for monitoring infra based on metric.
Prometheus in osh basically uses annotations for service discovery, but rook generates a ceph cluster without annotation.
A annotation on service accomplish this feature
```yaml
metadata:
  annotations:
    prometheus.io/scrape: "true"
```
Annotation in service doesn't affect any effect on kubernetes cluster, so this feature is safe.
This feature can be applied with a simple modification.

**Similar issues**:
This is very similar with #3204.
The only difference is that my use case needs a annotation on service.

**Comment by evrardjp** [comment]
I would also like to see this at the service level.
