### ISSUE TITLE
Rook v1.0.1 Unable to use Ceph CLI tool against mons from outside K8s cluster

### ISSUE THREAD

**Issue by iExalt** [rook/rook#3220]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

An external machine is unable to use the Ceph CLI tool to access the mons through a NodePort without a static route of `ip route add <ClusterIP>/32 dev ens3 via <kube_node_ip>>`. See https://github.com/rook/rook/issues/561#issuecomment-293979632: 
"Unfortunately Ceph clients don't like to talk to Mons through a proxy. If the destination IP doesn't match the Mon's real IP it will fail, at least when I tried using the kernel RBD client this way."

**Expected behavior:**

The Ceph CLI tool should be able to access the mons even from outside of the Kubernetes cluster i.e from a NodePort.

**How to reproduce it (minimal and precise):**

(Files taken directly from rook examples tag v1.0.1)

Run:
```
kubectl apply -f common.yaml
kubectl apply -f operator.yaml
kubectl apply -f cluster-test.yaml
kubectl apply -f toolbox.yaml
kubectl -n rook-ceph patch svc rook-ceph-mon-a --type='json' -p '[{"op":"replace","path":"/spec/type","value":"NodePort"}]'
ceph
```

```
telnet <kube_node_ip>:<NodePort>
Trying <kube_node_ip>...
Connected to <kube_node_ip>.
Escape character is '^]'.
ceph v027?
```

/etc/ceph/ceph.conf:
```
[global]
mon_host =<kube_node_ip>:<NodePort>

[client.admin]
keyring = /etc/ceph/keyring
```
/etc/ceph/keyring:
```
[client.admin]
key = <paste from tools pod>
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
* Kernel (e.g. `uname -a`): Linux test 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: OpenStack VM
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.0.1
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): [root@kube-node-3 ceph]# ceph health
HEALTH_OK

**Comment by travisn** [comment]
@iExalt If you want to connect from outside the cluster you will need to set `hostNetwork: true` in the cephcluster CR. Does that work for you?

**Comment by iExalt** [comment]
`hostNetwork: true` works as a quick and dirty fix, however it isn't ideal. Only the nodes running the mons will expose port 6789.

However I was able to hack together a method to allow the Ceph CLI to connect even without `hostNetwork: true`: I created a static route for the ClusterIP via a K8s master/worker.

**Comment by jbmcfarlin31** [comment]
@iExalt this doesn't answer or solve the problem - however I was curious, it sounds like you are able to access your ceph cluster deployed through rook external from your kubernetes cluster? The reason I ask is because I am looking for a way to leverage a dedicated k8s cluster (call it storage) that has rook deployed on it, and ceph via rook and another k8s cluster. I want to be able to have a cluster (call this one dev) leverage the ceph storage on the "storage" cluster using like an RBD provisioner or something.

Do you think this would be possible based off of the hack you have came up with and the `hostNetwork: true` setting?

**Comment by iExalt** [comment]
@jbmcfarlin31 I was holding off commenting until I had the full picture but I've come across a Good™ solution: Use something like [Calico](https://docs.projectcalico.org/v3.7/networking/service-advertisement#about-advertising-kubernetes-services-over-bgp) to expose the ClusterIP of the mons outside of the cluster. Host networking doesn't need to be on. Tested using Ceph admin cli/rbd cli to mount a block device, as well as external OpenStack Cinder/Glance/Nova services accessing the cluster. One thing that I didn't get around to testing is whether the K8s pods hosting the mons must be exposed as well (they are by default w/calico) or whether that's unnecessary.

**Comment by zhucan** [comment]
The same issue on rook v1.8.2

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/153811161-0afccbc6-1594-48b6-99fa-4ad511ff0e05.png)

**Comment by zhucan** [comment]
> * r Ceph use `ceph`

Can not resolve the problem.

**Comment by zhucan** [comment]
> @iExalt If you want to connect from outside the cluster you will need to set `hostNetwork: true` in the cephcluster CR. Does that work for you?

It doesn't work for me.

**Comment by zhucan** [comment]
If we want to use ceph cli tools from outside k8s cluster,  what can I do?  @leseb

**Comment by leseb** [comment]
> If we want to use ceph cli tools from outside k8s cluster, what can I do? @leseb

Assuming the network connectivity is in place and routing is configured, you can:

* run a toolbox pod in the k8s cluster
* copy the `/etc/ceph/ceph.conf` file outside of the cluster
* copy the `/etc/ceph/keyring` file outside of the cluster
* run ceph commands

**Comment by zhucan** [comment]
@leseb  ok, because of  the version between the client and server are too different.

**Comment by leseb** [comment]
> @leseb ok, because of the version between the client and server are too different.

Then you would need to update.
