### ISSUE TITLE
Retry detecting the Ceph version when the check fails

### ISSUE THREAD

**Issue by jhutar** [rook/rook#3227]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I have deployed Rook using script below and it failed waiting to "rook-ceph-tools" to come up:

https://github.com/openshift-metal3/dev-scripts/blob/master/10_deploy_rook.sh#L47

Problem was rook-ceph-tools pod hanged in "ContainerCreating" state, see: 
[oc_get_pods_n_openshift_stroage.log](https://github.com/rook/rook/files/3228178/oc_get_pods_n_openshift_stroage.log)

`rook-ceph-operator` have this error in the logs:

```
$ oc --config /home/kni/dev-scripts/ocp/auth/kubeconfig logs rook-ceph-operator-ddf6764c7-5cgpw  -n openshift-storage | grep ' E '
2019-05-27 13:51:59.898562 E | op-cluster: unknown ceph major version. failed to get version job log to detect version. failed to read from stream. Get https://worker-0:10250/containerLogs/openshift-storage/rook-ceph-detect-version-94v2t/version: remote error: tls: internal error
```

`rook-ceph-detect-version` seems to work fine:

```
$ oc --config /home/kni/dev-scripts/ocp/auth/kubeconfig logs pods/rook-ceph-detect-version-94v2t -n openshift-storage
ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)
```

Getting that version from inside `rook-ceph-operator` seems to be failing:

```
$ oc --config /home/kni/dev-scripts/ocp/auth/kubeconfig exec rook-ceph-operator-ddf6764c7-5cgpw  -n openshift-storage -ti /bin/bash
bash-4.2$ curl --insecure https://worker-0:10250/containerLogs/openshift-storage/rook-ceph-detect-version-94v2t/version; echo
Unauthorized
```

I have redeployed the Rook operator and it seems to be working: `oc delete -f operator-openshift-modified.yaml` and `oc create -f operator-openshift-modified.yaml` now: [oc_get_pods_n_openshift_stroage_fine.log](https://github.com/rook/rook/files/3228210/oc_get_pods_n_openshift_stroage_fine.log)

**Expected behavior:**
It should pass at a first try

**How to reproduce it (minimal and precise):**
This script was used and issue was reproduced by 2 different ppl:
https://github.com/openshift-metal3/dev-scripts/blob/master/10_deploy_rook.sh

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`):
```
Linux <fqdn> 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

* Cloud provider or hardware configuration: 10 x Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz, 256 GB RAM
* Rook version (use `rook version` inside of a Rook Pod): rook: v0.9.0-519.g111610e
* Kubernetes version (use `kubectl version`):
```
$ oc --config /home/kni/dev-scripts/ocp/auth/kubeconfig version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0", GitCommit:"cb455d664", GitTreeState:"clean", BuildDate:"2019-05-19T21:13:58Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+f2cc675", GitCommit:"f2cc675", GitTreeState:"clean", BuildDate:"2019-05-18T00:35:43Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
Looks like a retry would help in this situation instead of just immediately logging the error and returning [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/controller.go#L274).

**Comment by travisn** [comment]
Reopening for backport to 1.0

**Comment by leseb** [comment]
Closing again since the backport has merged and present in 1.0.2.

**Comment by lz006** [comment]
Also getting: "**op-cluster: unknown ceph major version. failed to complete ceph version job**" in conjunction with mon & osd pods not getting up.

Changing operator image from **rook/ceph:master** to **rook/ceph:v1.04** fixed it on kubernetes 1.14.3.

**Comment by travisn** [comment]
@lz006 Any chance you could repro the failure on rook/ceph:master again? It would be helpful to get the output for `kubectl describe <cephVersionJobPod>` to see what the failure was. There was a change in master in how the version is detected so it would be helpful to know if there is a lingering issue there. Thanks!

**Comment by lz006** [comment]
@travisn  when I change it the other way from rook/ceph:v1.04 to rook/ceph:master no error occurs. sorry. But once I'm setting up a new cluster from scratch I'll try to repro it and place the output here. (Probably next week)

PS: Saw you in Barca/kubecon this May, was a interesting session... little world :)
