### ISSUE TITLE
RBD CSI uses hardcoded monitor addresses.

### ISSUE THREAD

**Issue by mape90** [rook/rook#3236]
* Bug Report
**Deviation from expected behavior:**

RBD CSI uses hardcoded monitor addresses. This then causes problem when monitors get replaced.

There is already open issue in ceph-csi: https://github.com/ceph/ceph-csi/issues/13

Replacement of monitor happens when node where mon was running gets removed from cluster. If all monitors get replaced this will eventually cause that none of the mon addresses are valid. This then causes that none of the PVs that where provisioned with those monitors can not be used anymore. 

Scenarios were nodes are removed from cluster are:
- Cluster upgrade with node replacement. 
  - all nodes gets replaced -> all mons will be new ones -> you lose all your PVs
  - nodes might get back to cluster with same name or nodes will have totally new name. Depending on implementation
- Node fails permanently and is removed from cluster. 
  - Enough failures and you lose all your PVs.

This basically renders the current CSI plugin unusable in any production cluster. Luckily with flex plugin this do not happen as it seems to query monitor addresses from somewhere automatically. 

**Expected behavior:**
CSI should not relay on hardcoded monitor names as during cluster lifetime those might change. It should dynamically query current monitors.

Other possible solution might be that mon services would be static, so that DNS names would not change. However this would not work nicely if number of monitors would change. Also most likely the implementation would get more complex.

**How to reproduce it (minimal and precise):**
Easiest way is to delete all nodes where monitors are running. This would then cause recreation of all monitors and then all current PVs would get permanently corrupted as you can not edit PVs to fix them. 

**Environment**:
* Rook version: v1.0.1
* Kubernetes version: v1.13.5
* Kubernetes cluster type : custom

**Comment by travisn** [comment]
@mape90 This is tracked with #2649 and is highest priority for the CSI work for rook 1.1. We will track it with that issues, thanks!
