### ISSUE TITLE
useAllNodes getting removed by Operator

### ISSUE THREAD

**Issue by creiche** [rook/rook#3237]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When submitting a CRD for a new cluster, UseAllNodes is set to false but once the operator updates the CRD, the line is gone and it is trying to setup mons on nodes not specified.  They never deploy because they do not match the nodeselector.

**Expected behavior:**
useAllNodes: false forces setup on the specified nodes in the spec.

**How to reproduce it (minimal and precise):**
Using OKD 3.11 and set it up following the documentation.  Submit the following CRD:

```apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: 'ceph/ceph:v14.2.1-20190430'
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: false
    count: 3
    preferredCount: 0
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  storage:
    config: null
    useAllDevices: false
    useAllNodes: false
    nodes:
      - name: "compute-node01"
      devices:
      - name: "sdd"
```

CRD is updated by the operator missing useAllNodes line.  Deployments created are created with a nodeselector selecting infrastructure nodes.  NodeSelector:

`  nodeSelector:
    kubernetes.io/hostname: infranode01
    node-role.kubernetes.io/compute: 'true'`

So they never actually schedule.  I expect instead to have mon deployments created mapping to the nodes I specified.

**Environment**:  OKD 3.11
* OS (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Kernel (e.g. `uname -a`):  Linux compute-node01 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:  VMware ESXi 6.0
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.0.1
* Kubernetes version (use `kubectl version`):
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://openshift:8443
openshift v3.11.0+d0c29df-98
kubernetes v1.11.0+d4cacc0
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  OKD
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):  Never started

**Comment by travisn** [comment]
@creiche With openshift, all pods created in a namespace by default will be put on worker nodes. To change this default, see #3004, which we still need to get into the documentation. 

Note that the `useAllNodes` setting only applies to OSDs, not mons. Besides the openshift namespace issue, another way to specify placement of the mons on specific nodes is with the [placement](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L54) options.

**Comment by creiche** [comment]
Thanks @travisn for clarifying I will give those a try.  But I was still seeing my useAllNodes: false line disappear when the operator would update it.  Is that expected behavior if I have nodes defined?

**Comment by travisn** [comment]
If it's disappearing, it must be because `false` is the default value for a boolean. The operator doesn't update the contents of the CR other than the status section.

**Comment by creiche** [comment]
I am still running into issues with the selection of mons.  I have set:

```
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/compute
                  operator: In
                  values:
                    - 'true'
```
And yet the operator still creates mon deployments that point to the nodes that do not meet that node affinity:
```
      nodeSelector:
        kubernetes.io/hostname: infra-node01
```

I do see the affinity settings being set in the deployment spec:

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/compute
                    operator: In
                    values:
                      - 'true'
```

But obviously that node does not meet the affinity so it never schedules.

Here is my current CR:

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  creationTimestamp: '2019-05-30T13:12:12Z'
  generation: 1
  name: rook-ceph
  namespace: rook-ceph
  resourceVersion: '24852487'
  selfLink: /apis/ceph.rook.io/v1/namespaces/rook-ceph/cephclusters/rook-ceph
  uid: 89ba6115-82dc-11e9-b758-000c2947cac9
spec:
  cephVersion:
    image: 'ceph/ceph:v14.2.1-20190430'
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: true
    count: 3
    preferredCount: 0
  network:
    hostNetwork: false
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/compute
                  operator: In
                  values:
                    - 'true'
  rbdMirroring:
    workers: 0
  storage:
    config:
      databaseSizeMB: '1024'
      journalSizeMB: '1024'
    nodes:
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: sdd
        name: compute-node01
        resources: {}
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: sdd
        name: compute-node02
        resources: {}
      - config: null
        devices:
          - FullPath: ''
            config: null
            name: sdd
        name: compute-node03
        resources: {}
    useAllDevices: false
status:
  state: Creating
```

**Comment by creiche** [comment]
@travisn Any advice on this issue?  I am stuck here and unable to deploy.

**Comment by creiche** [comment]
@travisn I got this running today.  I did not realize that the operator does not look at the default project nodeselector when scheduling mons.  

Adding:

 scheduler.alpha.kubernetes.io/node-selector: node-role.kubernetes.io/compute=true

To the namespace fixed it and now it is scheduling mons on my compute nodes as desired.

**Comment by travisn** [comment]
OpenShift didn't add the default node selector to the namespace for compute=true? On a related note, we have this doc issue #3004 tracking what it takes in openshift if you don't want the worker nodes to be used. Could you comment on #3004 so we can update the docs around your scenario at the same time? Thanks!

**Comment by creiche** [comment]
Updated the issue with my findings.  Thanks!
