### ISSUE TITLE
PVC pending forever

### ISSUE THREAD

**Issue by kariae** [rook/rook#3242]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
PVC pending
**Expected behavior:**
PVC created
**How to reproduce it (minimal and precise):**

download the v1.0.0 release, create the `common.yaml`, `operator.yaml` and `cluster.yaml` ressources from the `cluster/examples/kubernetes/ceph` folder and run the `wordpress.yaml` example
**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`):Linux master-serv 4.9.93-mainline-rev1
* Cloud provider or hardware configuration: Scaleway
* Rook version (use `rook version` inside of a Rook Pod): v1.0.0
* Kubernetes version (use `kubectl version`): 1.14.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Single node cluster
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN Reduced data availability: 100 pgs inactive`

**Comment by Madhu-1** [comment]
@kariae have you created `storageclass` and `blockpool` from `https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/storageclass.yaml`

**Comment by kariae** [comment]
@Madhu-1 yes I created it from the example file `storageclass.yaml`

**Comment by travisn** [comment]
@kariae Since the PGs are all inactive, you likely don't have any OSDs created. The `ceph status` in the toolbox will show if this is the case. You'll need to attach devices to your nodes in order to create OSDs.
