### ISSUE TITLE
Some Ideas about Rook

### ISSUE THREAD

**Issue by timyinshi** [rook/rook#3249]
I'm an Inspur engineer and we decided to use root to manage CEPH. I have several questions that need your help. I hope to get your answers.
1. Blockstore, filesystem and objectstore services type are all clusterid by default, so that services outside the k8s cluster can not be accessed. Can we change the service type to nodeport or externaluip?
2. Ceph is divided into public network and cluster network. Rook's OSD is all pod network by default. Can you specify a fixed storage network card without using pod network? How to configure this cluster network?
3. For rook, deploy resources using k8s, upgrade, scaleup, scaledown and delete resources using k8s?

**Is this a bug report or feature request?**
* Feature Request
1、Can we change the service type to nodeport or externaluip?
2、How to configure this cluster network?
3、upgrade, scaleup, scaledown and delete resources using k8s?

**Comment by travisn** [comment]
@timyinshi To summarize the slack conversation, hopefully this answers the questions. Welcome to Rook!
1. If the services need to be accessible outside the cluster, you will likely need to set `hostNetwork: true` in the cluster CR. This way the host IPs will all be available externally. However, if you are only using object (rgw), then you would only need to create an external service endpoint for the rgw service.
1. To configure the cluster network, this topic should help: https://rook.io/docs/rook/v1.0/ceph-advanced-configuration.html#osd-dedicated-network
1. Yes, Rook uses K8s to create and delete resources. The operator is designed based on all the K8s pods, services, and other resources. To upgrade between rook or ceph versions, see this guide: https://rook.io/docs/rook/v1.0/ceph-upgrade.html

**Comment by timyinshi** [comment]
@travisn thanks
hostNetwork: true  ,There is a problem, it will directly change the pod IP to hostip, if both pod on a host, because the cause of the port conflicts, will lead to one of the pod can't start, I think it is not exposed to the outside of the cluster service good choice, and no load balancing ability to use the service, I think should revise the service type for the nodeport or externalip cluster external access way to solve the problem, what do you think, we are doing this part of the work, we would be happy to give this code contribution to rook

**Comment by timyinshi** [comment]
@travisn 
hostNetwork: true,This configuration will change the IP of osd and MGR to hostsip, but will not change the IP of mon to hostsip, so it cannot be accessed outside the cluster. Is this a bug?

**Comment by timyinshi** [comment]
@travisn 
I installed a ceph-common on the k8s cluster to connect to the ceph deployed by rook, and I found that to connect mon, you need to specify the mon-service clusterip:6789 to access it. Even if you change the type of mon-service to externalip, you cannot connect properly through hostip:6789, are you know the reason?Without this scaling, rook cannot be accessed outside the cluster.

**Comment by timyinshi** [comment]
@travisn Thanks for your help. Now I have access to ceph outside k8s cluster through the configuration of hostwork:true, and support cluster network through the configuration of rook-config-override, thanks
