### ISSUE TITLE
Idea: A way for Rook to report information to Ceph and/or users

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#3252]
**Feature Request**

Tangent to #3247

While writing up the design in #3247, I realized that if Ceph is requesting Rook to take certain actions, Rook may need to report information back to Ceph. For example, if there are errors during OSD provisioning, Rook should have a mechanism for reporting the error back to Ceph.

More than this, however, it would be very beneficial for users to be able to understand what Rook is currently doing. For example, Rook may be in the middle of orchestration, and it would be useful to know if it is currently orchestrating mons, osds, filesystems, rgws, or whatever. Further, Rook may be idle, and that is also important for a user to understand when Rook has finished upgrading to a new version or when Rook has finished applying recent changes to the Ceph cluster config. 

There are also many cases where rook reports a warning or an error in its logs, and the operator keeps going about its business.  As well it should. A mechanism for reporting these warnings and errors to the user would be great, as the messages may be actionable, even if they haven't caused the operator to crash entirely.

If such a reporting mechanism is in place, this would contain excellent information to display on a page of the Ceph dashboard. It also brings up the possibility of a very simple Rook monitoring dashboard which can be run standalone. It may be that Prometheus+Grafana would be a good, low-barrier-to-entry way to report Rook's current orchestration status and the list of Warnings/Errors which Rook has encountered recently.

Do these ideas sound good to others, and do others have thoughts for how this might be executed?

Also note, I imagine this feature not being implemented until after Ceph Octopus is released. I'd like to ask @travisn @leseb @sebastian-philipp and @liewegas for their thoughts.

**Comment by travisn** [comment]
Having more detailed status in the CR is something on my mind for a while. We've had several issues tracking such things at a high level like #2494. In 1.0 we added the ceph health status to the CR, which has been helpful. Adding more visibility to the operator internal status will make rook more debuggable for sure.

**Comment by leseb** [comment]
When it comes to exposing what Rook does, I think the orchestrator logs are saying enough, perhaps we could revisit our logging messages to make sure they are meaningful and consistent across different actions.
I agree we need a mechanism to highlight orchestration errors more clearly so that error logs don't get missed by the new info from the operator logs. Perhaps we can work on adding more info in `deployment.apps/rook-ceph-operator` just like we would do it for the Ceph's CR?
For exposing Ceph's internal status, CR properties are the way to go and we have been adding more information.

**Comment by sebastian-philipp** [comment]
And this is also true for the orchestrator modules: There is no way to report intermediate state: All we can return is an end-result. Meh.

**Comment by sebastian-philipp** [comment]
Relates to https://github.com/ceph/ceph/pull/29520
