### ISSUE TITLE
add ability to inject ceph conf settings for debugging/performance testing

### ISSUE THREAD

**Issue by bassam** [rook/rook#326]
we need a way to inject ceph conf file settings to each of the daemons to aid debugging/testing.

one idea would be to add something like:

```ROOKD_CEPH_OSD_CONF_FILE=/home/foo/myconf.conf```

and this file would be appended to the end of the OSD conf file.

**Comment by travisn** [comment]
we may also want to add settings to the other components. So we may also want a ROOKD_CEPH_MON_CONF_FILE, ROOKD_CEPH_MDS_CONF_FILE, and ROOKD_CEPH_RGW_CONF_FILE

Since there is such a small number of them, this seems better than trying to merge to a single property

**Comment by bassam** [comment]
we could also just start with a `ROOK_CEPH_CONF_OVERRIDE` and have it apply to all daemons globally.

**Comment by travisn** [comment]
Actually with our discussion to launch each daemon in its own container, the generic override setting would make more sense anyway. Each daemon could be passed its own config file if needed.

**Comment by jbw976** [comment]
Addressed with https://github.com/rook/rook/pull/335
