### ISSUE TITLE
Separate Storage Groups osd lost

### ISSUE THREAD

**Issue by liuyongqing1** [rook/rook#3267]
yes

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

Osd information will not be restored to default

**How to reproduce it (minimal and precise):**

After creating the ceph cluster, add ssd osd to ssd crush and create storageclass to specify ssd crush.
Create sts using storageclass.
Found that osd information is lost in ssd. Restore to default.

![image](https://user-images.githubusercontent.com/13477384/59005235-51579900-884f-11e9-9d3a-fd9aae1d7f96.png)

![image](https://user-images.githubusercontent.com/13477384/59005266-63393c00-884f-11e9-89b4-31276a4a5ba7.png)

![image](https://user-images.githubusercontent.com/13477384/59005272-6a604a00-884f-11e9-8dbb-cdb54287cf27.png)

![image](https://user-images.githubusercontent.com/13477384/59005540-98925980-8850-11e9-9f52-ec83185cbac0.png)

**Environment**:
* OS (e.g. from /etc/os-release):centos7.4
* Kernel (e.g. `uname -a`):Linux aps01 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:   
* Rook version (use `rook version` inside of a Rook Pod): 0.9.3
* Kubernetes version (use `kubectl version`): 1.9.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox]
(https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@liuyongqing1 To create pools based on different types of media, it's recommended to use the [device class](https://ceph.com/community/new-luminous-crush-device-classes/) and specify it in the pool as seen in #3146. While that feature didn't quite make it into 1.0, it is scoped enough that we should consider backporting to 1.0. @sp98 want to open a backport PR for it? thanks

@liuyongqing1 From your screenshots it also appears the osds you added to the ssd tree in the crush map are actually detected as hdds. Is this just an experiment where that's expected? Or are they actually ssds?

**Comment by liuyongqing1** [comment]
It is ssd but the display on the cloud is hdd,

**Comment by liuyongqing1** [comment]
After using the device class, restart a node, this node osd will still be restored @travisn 
![image](https://user-images.githubusercontent.com/13477384/59242589-ae33c480-8c3e-11e9-8202-b820fa0b35ad.png)

**Comment by pmorillon** [comment]
If i understand correctly, using classDevice instead of crushRoot, no need to separate hdd and ssd into the crushmap. The rook operator will always place the osd into `default` due to the generated `ceph.conf` with :

```
crush location            = root=default host=nodex
```

But the classDevice will modify the crush rule to use class device : 

```
step take default class ssd
```

instead of : 

```
step take ssd
```

Would be great to backport #3146 to 1.0

**Comment by liuyongqing1** [comment]
@pmorillon How should I solve this problem now?

**Comment by liuyongqing1** [comment]
My question has been processed at this address https://ceph.com/community/new-luminous-crush-device-classes/, except that it is manually edited by getcrushmap. I hope that at some point I can solve the problem of the official document providing method. Here I pass my crush file


```
# begin crush map
tunable choose_local_tries 0
tunable choose_local_fallback_tries 0
tunable choose_total_tries 50
tunable chooseleaf_descend_once 1
tunable chooseleaf_vary_r 1
tunable straw_calc_version 1

# devices
device 0 osd.0 class ssd
device 1 osd.1 class ssd
device 2 osd.2 class hdd
device 3 osd.3 class hdd
device 4 osd.4 class hdd
device 5 osd.5 class ssd

# types
type 0 osd
type 1 host
type 2 chassis
type 3 rack
type 4 row
type 5 pdu
type 6 pod
type 7 room
type 8 datacenter
type 9 region
type 10 root

# buckets
host 192-168-0-2 {
        id -3           # do not change unnecessarily
        id -9 class ssd         # do not change unnecessarily
        id -4 class hdd         # do not change unnecessarily
        # weight 0.137
        alg straw
        hash 0  # rjenkins1
        item osd.3 weight 0.093
        item osd.0 weight 0.044
}
host 192-168-0-3 {
        id -5           # do not change unnecessarily
        id -10 class ssd                # do not change unnecessarily
        id -6 class hdd         # do not change unnecessarily
        # weight 0.137
        alg straw
        hash 0  # rjenkins1
        item osd.1 weight 0.044
        item osd.4 weight 0.093
}
host 192-168-0-4 {
        id -7           # do not change unnecessarily
        id -11 class ssd                # do not change unnecessarily
        id -8 class hdd         # do not change unnecessarily
        # weight 0.137
        alg straw
        hash 0  # rjenkins1
        item osd.5 weight 0.044
        item osd.2 weight 0.093
}
root default {
        id -1           # do not change unnecessarily
        id -12 class ssd                # do not change unnecessarily
        id -2 class hdd         # do not change unnecessarily
        # weight 0.411
        alg straw
        hash 0  # rjenkins1
        item 192-168-0-2 weight 0.137
        item 192-168-0-3 weight 0.137
        item 192-168-0-4 weight 0.137
}

# rules
rule replicated_ruleset {
        id 0
        type replicated
        min_size 1
        max_size 10
        step take default class hdd
        step chooseleaf firstn 0 type host
        step emit
}
rule rule-ssd {
        id 1
        type replicated
        min_size 1
        max_size 10
        step take default class ssd
        step chooseleaf firstn 0 type host
        step emit
}
rule aps-metadata {
        id 2
        type replicated
        min_size 1
        max_size 10
        step take default class hdd
        step chooseleaf firstn 0 type host
        step emit
}
rule aps-data0 {
        id 3
        type replicated
        min_size 1
        max_size 10
        step take default class hdd
        step chooseleaf firstn 0 type host
        step emit
}

# end crush map
```
