### ISSUE TITLE
Enable usage of Metadata Only ISGW replication

### ISSUE THREAD

**Issue by dyusupov** [rook/rook#3273]
**Is this a bug report or feature request?**
* Bug Report

Property metadataOnly isn't applied correctly.

**Deviation from expected behavior:**

Metadata Only geo-replication should be enabled as a configurable "all" or "versions"

**Expected behavior:**

metadataOnly: all | versions

**How to reproduce it (minimal and precise):**

All v1.0.x affected.

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
Reopening for backport

**Comment by travisn** [comment]
Already included with v1.0.2
