### ISSUE TITLE
v14.2.1-20190430 mgr memory leak

### ISSUE THREAD

**Issue by carletes** [rook/rook#3285]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:

The Ceph `mgr` from image `ceph/ceph:v14.2.1-20190430` leaks memory, very much as described in https://github.com/ceph/ceph-container/issues/1320 for v13.2.4-20190109.

How to reproduce it (minimal and precise):

I set up a Kubernetes v1.14.3 cluster (controller node and 4 worker nodes) running stock Ubuntu 18.04.2 on OpenStack VMs using `kubeadm`. I'm using the Weave CNI plugin, and my `kube-proxy` is using IPVS (I mention these two networking details because the symptoms seem to be network related).

I set up a Rook v1.0.2 operator following the steps described in the documentation:

```
$ kubectl apply -f cluster/examples/kubernetes/ceph/common.yaml
$ kubectl apply -f cluster/examples/kubernetes/ceph/operator.yaml
```

I took `common.yaml` and `operator.yaml` from Git tag `v1.0.2` and applied them unmodified.

I then deployed a Rook Ceph cluster by doing the recommended step:

```
$ kubectl apply -f cluster/examples/kubernetes/ceph/cluster.yaml
```

I also took `cluster.yaml` from Git tag `v1.0.2`, but I did the following two changes:

* I set `network.hostNetwork` to `true`, because otherwise the OSD pods would not start with the default setting in a previous attempt, as described by #3140 (although, in my case, the OSD pods did start after specifying `hostNetwork: true`).
* I explicitly set the storage device I want to use.

```
$ git diff
diff --git a/cluster/examples/kubernetes/ceph/cluster.yaml b/cluster/examples/kubernetes/ceph/cluster.yaml
index cb130e88..e14a51a4 100644
--- a/cluster/examples/kubernetes/ceph/cluster.yaml
+++ b/cluster/examples/kubernetes/ceph/cluster.yaml
@@ -43,7 +43,7 @@ spec:
     # ssl: true
   network:
     # toggle to use hostNetwork
-    hostNetwork: false
+    hostNetwork: true
   rbdMirroring:
     # The number of daemons that will perform the rbd mirroring.
     # rbd mirroring must be configured with "rbd mirror" from the rook toolbox.
@@ -90,8 +90,8 @@ spec:
 #    osd:
   storage: # cluster level storage configuration and selection
     useAllNodes: true
-    useAllDevices: true
-    deviceFilter:
+    useAllDevices: false
+    deviceFilter: vdb
     location:
     config:
       # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
$
```

All pods started successfully:

```
$ kubectl -n rook-ceph get pods
NAME                                       READY   STATUS      RESTARTS   AGE
rook-ceph-agent-5kzbp                      1/1     Running     0          68m
rook-ceph-agent-7vwzt                      1/1     Running     0          68m
rook-ceph-agent-khzmv                      1/1     Running     0          68m
rook-ceph-agent-wcps4                      1/1     Running     0          68m
rook-ceph-mgr-a-774b6d6d78-qscl8           1/1     Running     0          58m
rook-ceph-mon-a-6bb6bdf97c-ppdsp           1/1     Running     0          59m
rook-ceph-mon-b-d9d898846-dk6f7            1/1     Running     0          59m
rook-ceph-mon-c-68d59df9f5-w2c86           1/1     Running     0          58m
rook-ceph-operator-54889dcbb-8jzn7         1/1     Running     0          69m
rook-ceph-osd-0-76bcb77688-gq6ln           1/1     Running     0          56m
rook-ceph-osd-1-6dfb7fd8cf-pb9jq           1/1     Running     0          56m
rook-ceph-osd-2-5dbcc8b98c-wdwpg           1/1     Running     0          56m
rook-ceph-osd-3-86dd498b-hkm9k             1/1     Running     0          56m
rook-ceph-osd-prepare-k8s-worker-0-zxzbd   0/2     Completed   0          57m
rook-ceph-osd-prepare-k8s-worker-1-6x74m   0/2     Completed   0          57m
rook-ceph-osd-prepare-k8s-worker-2-kn9hj   0/2     Completed   0          57m
rook-ceph-osd-prepare-k8s-worker-3-bmbtv   0/2     Completed   0          57m
rook-discover-chv5s                        1/1     Running     0          68m
rook-discover-mx9hv                        1/1     Running     0          68m
rook-discover-tglh6                        1/1     Running     0          68m
rook-discover-vfvbf                        1/1     Running     0          68m
$
```

At this point, even before making use of the Ceph cluster (by setting up a Ceph object store, which is what I'm after), I could already see the pod `rook-ceph-mgr-a-774b6d6d78-qscl8` emitting a constant stream of log messages like this

```
debug 2019-06-11 14:30:45.824 7fb48cc6f700  0 client.0 ms_handle_reset on v2:10.240.0.20:6800/1
debug 2019-06-11 14:30:44.824 7fb48cc6f700  0 client.0 ms_handle_reset on v2:10.240.0.20:6800/1
debug 2019-06-11 14:30:43.824 7fb48cc6f700  0 client.0 ms_handle_reset on v2:10.240.0.20:6800/1
debug 2019-06-11 14:30:42.824 7fb48cc6f700  0 client.0 ms_handle_reset on v2:10.240.0.20:6800/1
debug 2019-06-11 14:30:41.824 7fb48cc6f700  0 client.0 ms_handle_reset on v2:10.240.0.20:6800/1
debug 2019-06-11 14:30:40.824 7fb48cc6f700  0 client.0 ms_handle_reset on v2:10.240.0.20:6800/1
```

The memory usage of the `mgr` pod has grown from about 180 MB at start time to about 280 MB in one hour (about 100 MB per hour).

**Environment**:

* Kubernetes 1.14.3 set up with `kubeadm` on Ubuntu 18.04.2 VMs (running on OpenStack)
* Weave CNI plugin
* Docker 18.06.2-ce
* Linux kernel: `Linux k8s-worker-0 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Ceph version: Using image `ceph/ceph:v14.2.1-20190430`

```
$ kubectl -n rook-ceph exec rook-ceph-mgr-a-774b6d6d78-qscl8 -- ceph -v
ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)
$
```

**Comment by carletes** [comment]
Oops, should I have filed this issue under https://github.com/ceph/ceph-container/ instead?

**Comment by leseb** [comment]
If it's a memory leaks then please open an issue on Ceph https://tracker.ceph.com.

**Comment by BlaineEXE** [comment]
Closing this, as it is a Ceph bug.

**Comment by carletes** [comment]
Reported on Ceph as https://tracker.ceph.com/issues/40260 (thanks for the hint, @leseb!).

**Comment by alwinmarkcf** [comment]
As far as I understand, this is a ceph bug and can be prevented by adding another mgr. How can I achive this with rook?

**Comment by fritchie** [comment]
you may want to try 

hostPID: true

in the mgr deployment, see

https://review.opendev.org/#/c/744236/
