### ISSUE TITLE
Minio object store not deploying

### ISSUE THREAD

**Issue by jbmcfarlin31** [rook/rook#3286]
**Is this a bug report or feature request?**

* Bug Report

**Bug Report**
When deploying a minio object store, the `my-store-x` pods create but shortly after enter a `CrashLoopBackOff` state due to the liveliness check not being executed successfully.

**Expected behavior:**
Potentially not fail the pod, but alert that something isn't correct. The store should come up.

**Deviation from expected behavior:**

**How to reproduce it (minimal and precise):**

I deployed the example operator and example object-store under the [examples](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/minio) page. I changed the `storageClass` to be one that I created (also through rook, it is a ceph pool).

Firstly deploy the operator and wait for it to come up.

Secondly deploy the object-store and wait for it to come up. The PV's and PVC's become bound, and the `my-store-0` pod begins to create. It takes a while to mount the pod to the volumes but once it does, it shows as `running`. Shortly after, the state changes to `CrashLoopBackOff` and when running a `kubectl -n rook-minio describe pod my-store-0` it displays the following:
```Readiness probe failed: Get http://10.42.4.110:9000/minio/health/ready: dial tcp 10.42.4.110:9000: connect: connection refused```

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 16.04`
* Kernel (e.g. `uname -a`): `Linux 4.15.0-1045-azure #49-Ubuntu SMP Mon May 13 16:30:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): `1.0.2`
* Kubernetes version (use `kubectl version`): `1.13.5`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `RKE`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTHY`

**Comment by jbw976** [comment]
This looks similar to #3040, where the readiness probe was also failing.

Is there any more information in the the minio pod logs, e.g. `my-store-0`?

**Comment by jbmcfarlin31** [comment]
@jbw976 after leaving the pods up and running, it appears that it tries to create the minio cluster because subsequent pods get created (e.g. `my-store-0`, `my-store-1`, `my-store-2` etc) but they all result in the same `CrashLoopBackOff` status with the liveliness/readiness probe failed. 

I managed to grab the pod logs, this was in all of the pods that were created:
`kubectl -n rook-minio logs my-store-{0,1,2}`
OUTPUT:
```
Waiting for a minimum of 2 disks to come online (elapsed 0s)

Waiting for a minimum of 2 disks to come online (elapsed 1s)

Waiting for a minimum of 2 disks to come online (elapsed 2s)

Waiting for a minimum of 2 disks to come online (elapsed 6s)

Waiting for a minimum of 2 disks to come online (elapsed 7s)

Unable to connect to http://my-store-1.my-store.rook-minio.svc.cluster.local:9000/data/rook-minio-data1: Post http://my-store-1.my-store.rook-minio.svc.cluster.local:9000/minio/storage/v5/data/rook-minio-data1/getinstanceid?: dial tcp: lookup my-store-1.my-store.rook-minio.svc.cluster.local on 10.43.0.10:53: no such host

Unable to connect to http://my-store-2.my-store.rook-minio.svc.cluster.local:9000/data/rook-minio-data1: Post http://my-store-2.my-store.rook-minio.svc.cluster.local:9000/minio/storage/v5/data/rook-minio-data1/getinstanceid?: dial tcp: lookup my-store-2.my-store.rook-minio.svc.cluster.local on 10.43.0.10:53: no such host

Unable to connect to http://my-store-3.my-store.rook-minio.svc.cluster.local:9000/data/rook-minio-data1: Post http://my-store-3.my-store.rook-minio.svc.cluster.local:9000/minio/storage/v5/data/rook-minio-data1/getinstanceid?: dial tcp: lookup my-store-3.my-store.rook-minio.svc.cluster.local on 10.43.0.10:53: no such host

Waiting for a minimum of 2 disks to come online (elapsed 18s)

Unable to connect to http://my-store-1.my-store.rook-minio.svc.cluster.local:9000/data/rook-minio-data1: Post http://my-store-1.my-store.rook-minio.svc.cluster.local:9000/minio/storage/v5/data/rook-minio-data1/getinstanceid?: dial tcp: lookup my-store-1.my-store.rook-minio.svc.cluster.local on 10.43.0.10:53: no such host

Unable to connect to http://my-store-2.my-store.rook-minio.svc.cluster.local:9000/data/rook-minio-data1: Post http://my-store-2.my-store.rook-minio.svc.cluster.local:9000/minio/storage/v5/data/rook-minio-data1/getinstanceid?: dial tcp: lookup my-store-2.my-store.rook-minio.svc.cluster.local on 10.43.0.10:53: no such host

Unable to connect to http://my-store-3.my-store.rook-minio.svc.cluster.local:9000/data/rook-minio-data1: Post http://my-store-3.my-store.rook-minio.svc.cluster.local:9000/minio/storage/v5/data/rook-minio-data1/getinstanceid?: dial tcp: lookup my-store-3.my-store.rook-minio.svc.cluster.local on 10.43.0.10:53: no such host

Waiting for a minimum of 2 disks to come online (elapsed 32s)

ERROR Unable to initialize backend: Initializing data volumes gracefully stopped.
```

**Comment by jbmcfarlin31** [comment]
Just to update, I have redeployed the entire minio controller and object-store. These are my findings.

1) Upon first deployment of the object-store, the minio pods don't come up right away due to waiting to connect the pod to their associated PVs. After a couple of minutes, they finally come up. 
2) After those pods have been up for a few minutes, they begin the cycle of the `CrashLookBackOff` due to the errors mentioned above and have the output in the logs mentioned above. They continue this way until all of the pods needed for the object store are deployed. 
3) Once the `my-store-{0,1,2,3}` pods have been spun up and created they finally iron out and successfully deploy the minio object store, and the dashboard can then be accessed successfully.
