### ISSUE TITLE
Ceph CI: Additional Rook-Ceph CI outside of Rook CI and Teuthlogy

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#3287]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The Rook-Ceph project needs additional CI outside of the CI which runs as part of Rook. Rook's Ceph CI is already large enough. Teuthology is able to test bare-metal Ceph installs but unable to test against Rook-Ceph clusters -- and extending Teuthology to do so would be prohibitively difficult. 

We need a CI system capable of exercising the relevant parts of Ceph in the context of Rook. This should be much more than Rook's current smoke tests, and it should not be as powerful as much of the testing done by Teuthology.

Related : #1343, #992
These requirements hope to allow the related issues to be fulfilled.

--------------

## Initial Requirements

The functional requirements of a CI system requirements can be broken into a few logical areas
1. hardware-under-test requirements - requirements needed for hardware on which tests will be run
1. system requirements - requirements needed for the systems installed on the hardware (this might be the os for example)
1. platform requirements - requirements needed from the container platform installed on the hardware (this might be on top of the os, or system and platform might be one unit depending on the platform)
1. test framework requirements - requirements for the system which will organize and run the tests

### Requirements for hardware-under-test
These requirements are ideally simulated in software (from the system level) for ease of implementation and in order to be able to run more tests on real bare-metal systems, but some requirements may not be able to run on bare metal. Virtualized hardware will be required for some tests. "Nodes" here refer to virtual machines without opinion about software the node is running. 

- virtualized hardware (vs. bare metal)
    - testing on virtualized hardware is required and targeted initially
    - (in the future) testing on bare metal is a desired feature, so we should architect the solution in such a way to support this without too much work in the future
- ability to create a virtual test cluster with an arbitrary number of nodes
- ability to add disks to a subset of nodes
  - number of disks should be configurable
  - disk size should be configurable
  - (in the future)(if possible) we will desire the ability to add virtual SSDs in addition to virtual HDDs (also virtual NVMe devices?)
- ability to create at least one virtual network for each test cluster
  - (in the future) the ability to create multiple (at least 3, ideally at least 4) networks for each cluster
- ability to non-gracefully remove nodes from the cluster
- ability to add nodes to the cluster
- ability to configure CPU and RAM allocation for nodes
- (if possible) ability to artificially deprive Ceph processes of CPU time
  - this could be "killing" CPU cores or it could be introducing another process which is designed to consume a lot of CPU, depriving Ceph by extension
- (if possible) ability to artificially deprive Ceph processes of RAM
    - this could be "killing" some amount of RAM available to a given node, or it could be done by introducing another RAM-hungry process designed to deprive Ceph of RAM by extension (Kubernetes is designed to run on systems with swap off)
- ability to simulate or create network partitions between nodes
- ability to simulate disk failure events
  - trivially this is ungracefully removing the disk, but software methods may exist
- ability to remove a selected disk from the node and add a disk with a different ID into what appears to the system to be the same drive bay
    - probably this means disconnecting a virtual device and attaching a new virtual device to the same PCI device and location
- ability to remove a selected disk from one node and attach it to another node with data still intact
- ability to "kill" disk controllers
  - (if possible) the ability to replace a broken disk controller with a new controller that has attached the same previous disks
- ability to shut down (and restart) nodes gracefully and ungracefully
  - ungraceful shutdown could be an emulation of node removal in bare metal environments
  - restart might be needed to get the system to "see" updates to hardware like if udev doesn't pick up hot-add events
- ability to start nodes that have been shut down
- ability to destroy virtual hardware from these tests
  - we should assume we need to delete resources that haven't been properly cleaned up either due to a failure in the CI system or due to just accidentally not cleaning up the resource when appropriate
- (possibly) the ability to snapshot clusters to iterate on tests that use common hardware more quickly

### Requirements for systems
- ability to support installation of different OSes and distros configurably
  - centos
  - openSUSE 
  - downstream: Red Hat will want to support RHEL, SUSE to support SLE
- what we probably want here is essentially the ability to support adding systems extensibly

### Requirements for platforms
- ability to support installation of different Kubernetes-based platforms configurably
  - Rook will require upstream Kubernetes versions
  - SUSE will want to test upstream openSUSE Kubic versions (Kubic is an example of a platform which might still be a system+platform combined unit)
  - Red Hat will want to test openshift (is openshift a combined system+platform unit?)
- what we probably want here is essentially the ability to support adding platforms extensibly

### Requirements for test suite runner
I (Blaine) have a better understanding of the hardware, system, and platform requirements than requirements of the test system itself, and in reality, most CI systems probably are adequate for any needs we have here. 

- Ability to run tests selectively based on user selection
- (in the future) will want to automatically select tests based on environment (e.g., some tests will not apply on bare metal)
- (in the future) ability to run tests in parallel as a performance improvement
- Ability to arbitrarily execute steps from hardware, system, and platform needs in addition to needs for specific tests and in any order
  - e.g., at least one test will add a hardware node, configured with the system and with the platform installed such that the Kubernetes cluster gets the new node added

**Comment by BlaineEXE** [comment]
@travisn @leseb @liewegas @shaas @sebastian-philipp please take a look at the requirements and add thoughts you may have.

**Comment by leseb** [comment]
Thanks for the write-up @BlaineEXE, I'd like to simplify this a bit for the start with what I believe is crucial:

* testing against N numbers of Kubernetes version as well as 
* testing a real case scenario (3 nodes HCI with disks)
* testing upgrades
* testing with Ceph master as described in: https://github.com/rook/rook/issues/2828
* testing stable branches of rook
* pin a Rook version with a Ceph version to run nightlies against stable branches of Rook

The testing sequence should look like:

1. bootstrap VM resources
2. deploy Kubernetes on top
3. deploy Rook operator + CSI
4. deploy Ceph CR
5 run a validation suite for the health of the cluster
6. reboot the nodes
7. wait for the operator to reconcile
8. run the validation suite again

I'm not sure where to put the current validation suite to be honest.

I guess the error injection you suggested can wait a little bit.
