### ISSUE TITLE
Ceph OpenShift missing required field "priority" in SecurityContextConstraints

### ISSUE THREAD

**Issue by ron1** [rook/rook#3290]
**Deviation from expected behavior:**

Command execution `kubectl create -f operator-openshift.yaml` generates the following error:

error: error validating "operator-openshift.yaml": eror validating data: ValidationError(SecurityContextConstraints): missing required field "priority" in com.github.openshift.api.security.v1.SecurityContextConstraints; if you choose to ignore these errors, turn validation off with --validate=false

**Expected behavior:**

Command executes without error

**How to reproduce it (minimal and precise):**
Execute step `kubectl create -f operator-openshift.yaml` in Rook-Ceph installation instructions

**Environment**:
* OS (e.g. from /etc/os-release): CentOS/RHEL 7.6
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: OpenShift 3.11
* Rook version (use `rook version` inside of a Rook Pod): 1.0.2
* Kubernetes version (use `kubectl version`): v1.11.0+d4cacc0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
@netzzer have you ever seen that? Thanks.

**Comment by ron1** [comment]
I experienced the same problem with the Rook 1.1 upgrade running on OCP 3.11.
