### ISSUE TITLE
devices: incorporate reliable serial device parsing into hotplug

### ISSUE THREAD

**Issue by noahdesu** [rook/rook#3291]
thanks to @liewegas , we hit the jackpot on this obscure normalization logic

https://github.com/ceph/ceph/blob/master/src/ceph-volume/ceph_volume/util/device.py#L197
https://github.com/ceph/ceph/tree/master/src/test/common/blkdev-udevadm-info-samples

which will be useful to matching disk identities across device scans

**Comment by jbw976** [comment]
Is this logic something that could be ported to the common rook.io package(s)?

**Comment by noahdesu** [comment]
@jbw976 ahh, yeh for sure. ceph just happens to be the only current consumer.

**Comment by jbw976** [comment]
Awesome @noahdesu! The more value we can put into the common rook.io, the more folks will start consuming it and contributing to it and building a bigger ecosystem around it.  Love it!!
