### ISSUE TITLE
Log messages in Rook operator after node/OSD failure are unclear

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#3292]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When a Kubernetes node fails and Rook is waiting for the OSDs to come back online or to time out, the warning messages output to the operator log are unclear, and this has confused at least one user from Slack.

```
2019-06-12 20:53:09.332900 I | op-osd: osd.3 is marked 'DOWN'
2019-06-12 20:53:09.332914 W | op-osd: waiting for the osd.3 to exceed the grace period
```

**Expected behavior:**
The warning message is not very clear. It should state why Rook is waiting, what will happen after the grace period, what the grace period is, and how much time is left until the period is crossed. For example, ```OSD 3 is unavailable. Waiting for a grace period of GRACE_PERIOD seconds/minutes before assuming the OSD is gone forever, at which point the OSD will be removed from the Ceph cluster. TIME_REMAINING seconds/minutes remain in the grace period. It is natural to see the pod corresponding to this OSD waiting in "Pending" state at this time.```

When the OSD grace period is passed, I would expect the message to contain much of the same information. For example, ```OSD 3 has been unavailable for TIME_UNAVAILABLE seconds/minutes. This exceeds the allowed grace period of GRACE_PERIOD seconds/minutes. The OSD will now be removed from the Ceph cluster.```

It is also not clear whether Rook is observing its own grace period or whether it is allowing Ceph to mark the OSD `out` according to Ceph's own grace period.

**How to reproduce it (minimal and precise):**
Start a multi-node Rook cluster, and kill one of the nodes.

**Comment by travisn** [comment]
Rook doesn't really take action anymore on these. Several releases ago in "direct" rook mode (pre-k8s) i believe there was some side effect in place, but that was removed long ago. In any case, I believe #3117 will improve these error messages and take the correct action.

**Comment by BlaineEXE** [comment]
@travisn it looks like #3117 would indeed fix this. :)
