### ISSUE TITLE
rbd volume mapped on multiple nodes

### ISSUE THREAD

**Issue by dimm0** [rook/rook#3298]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I frequently see a single RBD mapped on multiple nodes. Usually after something is not working as expected, but today saw it right after creating a new PVC of 1TB.

Some protection against this is needed, since it usually corrupts the filesystem, and repair is not always possible

**Expected behavior:**
Rook watches the maps and doesn't allow multiple volume mappings in the cluster

**How to reproduce it (minimal and precise):**
Create a large volume - I suppose it will eventually timeout waiting and map on another node to format again?

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
1.0.1
* Kubernetes version (use `kubectl version`):
1.14.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by zerkms** [comment]
I reported something like this some time ago and it was closed due to inactivity https://github.com/rook/rook/issues/2535

**Comment by travisn** [comment]
Hmm, need to make sure this isn't overlooked, even if we are moving to the CSI driver soon!

**Comment by travisn** [comment]
@dimm0 I believe this is fixed by #4180. It will be included in v1.1.5.
