### ISSUE TITLE
CSI based RBD pods go into CrashLoopBackOff upon deployment

### ISSUE THREAD

**Issue by nehaberry** [rook/rook#3312]
**Description**

The recent changes in ceph/csi/rbd/templates folder and addition of ceph-csi-config (PR#[3271](https://github.com/rook/rook/pull/3271))  seems to be affecting rook-CSI deployment. The csi based rbd pods are unable to come up in Running state upon fresh deployment.

**Steps performed for creating the setup:**

1. Cloned the [rook repo](https://github.com/rook/rook)
2. Navigated to rook/cluster/examples/kubernetes/ceph
3. Ran common.yaml
  $oc create -f common.yaml
4. Applied rbac rules from csi folder
  $oc apply -f csi/rbac/rbd/
  $oc apply -f csi/rbac/cephfs/
5. Created operator pod
   $ oc create -f operator-openshift-with-csi.yaml 
6. Check the pods. The pods are either stuck in ContainerCreating state. 
7. Create ceph pods.
   $ oc create -f cluster.yaml

8. Re-check the pod status. The csi-rbdplugin-* pods go in CrashloopBackOff and finally into error state.
  
________________________________

Note: Tried similar steps in ocs-ci based setups as well, similar issue

**Till cluster.yaml is run to create ceph cluster, the csi-rbplugin pods were in ContainerCreating state:**

 $ **oc get pods -n rook-ceph**
  csi-rbdplugin-f999c                   0/2     ContainerCreating   0          53m   10.0.158.162   ip-10-0-158-162.us-east-2.compute.internal   <none>           <none>
csi-rbdplugin-pkzx7                   0/2     ContainerCreating   0          53m   10.0.168.120   ip-10-0-168-120.us-east-2.compute.internal   <none>           <none>
csi-rbdplugin-provisioner-0           0/4     ContainerCreating   0          53m   <none>         ip-10-0-158-162.us-east-2.compute.internal   <none>           <none>
csi-rbdplugin-st5jp                   0/2     ContainerCreating   0          53m   10.0.135.141   ip-10-0-135-141.us-east-2.compute.internal   <none>           <none>

**Pods in error state:**

```
csi-rbdplugin-f999c                           1/2     CrashLoopBackOff    4          66m
csi-rbdplugin-pkzx7                           1/2     CrashLoopBackOff    4          66m
csi-rbdplugin-provisioner-0                   3/4     CrashLoopBackOff    5          66m
csi-rbdplugin-st5jp                           1/2     CrashLoopBackOff    4          66m

```
**oc describe of one pod**

```
Events:
  Type     Reason       Age                   From                                                 Message
  ----     ------       ----                  ----                                                 -------
  Normal   Scheduled    45m                   default-scheduler                                    Successfully assigned rook-ceph/csi-rbdplugin-provisioner-0 to ip-10-0-158-162.us-east-2.compute.internal
  **Warning  FailedMount  15m (x23 over 45m)    kubelet, ip-10-0-158-162.us-east-2.compute.internal  MountVolume.SetUp failed for volume "ceph-csi-config" : configmaps "rook-ceph-mon-endpoints" not found**

  **Warning  FailedMount  5m26s (x18 over 43m)  kubelet, ip-10-0-158-162.us-east-2.compute.internal  Unable to mount volumes for pod "csi-rbdplugin-provisioner-0_rook-ceph(49342068-90c4-11e9-906d-0ac7385058d4)": timeout expired waiting for volumes to attach or mount for pod "rook-ceph"/"csi-rbdplugin-provisioner-0". list of unmounted volumes=[ceph-csi-config]. list of unattached volumes=[host-dev host-rootfs host-sys lib-modules socket-dir ceph-csi-config rook-csi-rbd-provisioner-sa-token-htkg5]**

```
$ **oc get cm -n rook-ceph**
```
NAME                                                      DATA   AGE
local-device-ip-10-0-135-141.us-east-2.compute.internal   1      68m
local-device-ip-10-0-158-162.us-east-2.compute.internal   1      69m
local-device-ip-10-0-168-120.us-east-2.compute.internal   1      68m
rook-ceph-config                                          1      4m36s
rook-ceph-mon-endpoints                                   4      4m36s
rook-config-override                                      1      4m36s
rook-crush-config                                         1      3m39s
```

$ **oc get nodes**
```
NAME                                         STATUS   ROLES    AGE   VERSION
ip-10-0-129-19.us-east-2.compute.internal    Ready    master   66m   v1.13.4+cb455d664
ip-10-0-135-141.us-east-2.compute.internal   Ready    worker   62m   v1.13.4+cb455d664
ip-10-0-149-108.us-east-2.compute.internal   Ready    master   66m   v1.13.4+cb455d664
ip-10-0-158-162.us-east-2.compute.internal   Ready    worker   62m   v1.13.4+cb455d664
ip-10-0-168-120.us-east-2.compute.internal   Ready    worker   62m   v1.13.4+cb455d664
ip-10-0-173-77.us-east-2.compute.internal    Ready    master   66m   v1.13.4+cb455d664

```
 **oc get pods -n rook-ceph**
```
NAME                                          READY   STATUS             RESTARTS   AGE
csi-cephfsplugin-fj7w6                        2/2     Running            1          70m
csi-cephfsplugin-lsc7f                        2/2     Running            0          70m
csi-cephfsplugin-provisioner-0                3/3     Running            0          70m
csi-cephfsplugin-xz5wx                        2/2     Running            0          70m
csi-rbdplugin-f999c                           0/2     CrashLoopBackOff   8          70m
csi-rbdplugin-pkzx7                           0/2     CrashLoopBackOff   8          70m
csi-rbdplugin-provisioner-0                   2/4     CrashLoopBackOff   12         70m
csi-rbdplugin-st5jp                           0/2     CrashLoopBackOff   8          70m
rook-ceph-agent-b5wdl                         1/1     Running            0          70m
rook-ceph-agent-w62wh                         1/1     Running            0          70m
rook-ceph-agent-zbjkg                         1/1     Running            0          70m
rook-ceph-mgr-a-7c9b5494dd-8lpbw              1/1     Running            0          4m43s
rook-ceph-mon-a-84bb86696c-t4hx4              1/1     Running            0          5m41s
rook-ceph-mon-b-79db689db5-wsmwt              1/1     Running            0          5m29s
rook-ceph-mon-c-5c995b74bb-5jrp9              1/1     Running            0          5m6s
rook-ceph-operator-5b6856f864-bm2rq           1/1     Running            0          71m
rook-ceph-osd-0-7d59d5b7b5-bghhd              1/1     Running            0          3m24s
rook-ceph-osd-1-677fdb8f9f-q77v5              1/1     Running            0          3m19s
rook-ceph-osd-2-78f5f56fd5-lfjgz              1/1     Running            0          3m14s
rook-ceph-osd-prepare-ip-10-0-135-141-8cj6b   0/2     Completed          0          4m12s
rook-ceph-osd-prepare-ip-10-0-158-162-c5qz9   0/2     Completed          0          4m12s
rook-ceph-osd-prepare-ip-10-0-168-120-5vspd   0/2     Completed          0          4m12s
rook-discover-c7qbb                           1/1     Running            0          70m
rook-discover-dg4ck                           1/1     Running            0          70m
rook-discover-g75qd                           1/1     Running            0          70m

```

**Deviation from expected behavior:**
The recent changes should not affect the deployment of csi-rbdplugin pods.

**Expected behavior:**
All  csi-rbdplugin pods should come up in Running state.

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux CoreOS 410.8.20190520.0 (Ootpa)   
* Kernel (e.g. `uname -a`): 4.18.0-80.1.2.el8_0.x86_64
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod):   rook: v1.0.0-122.g488fe64

* Openshift version (use `kubectl version`): 

```
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0-201905091432+4910781-dirty", GitCommit:"4910781", GitTreeState:"dirty", BuildDate:"2019-05-09T19:19:42Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+838b4fa", GitCommit:"838b4fa", GitTreeState:"clean", BuildDate:"2019-05-19T23:51:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift

 **oc get clusterversion**
```
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.1.0     True        False         83m     Cluster version is 4.1.0
```

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
ceph health
HEALTH_OK

**Comment by nehaberry** [comment]
Note: Logs attached:

1. Operator log
2. logs from cs-rbdplugin-* pods and their containers 
3.  oc get configmap -o yaml 
[logs-issue-3312.zip](https://github.com/rook/rook/files/3295669/logs-issue-3312.zip)

**Comment by ShyamsundarR** [comment]
The case seems to be due to missing configmap `ceph-csi-config` when bringing up the Ceph-CSI related pods. @phlogistonjohn the step that rus `oc create -f operator-openshift-with-csi.yaml` can create an empty config file for the pods to start successfully, is that feasible?

**Comment by nehaberry** [comment]
@ShyamsundarR it may be the case. I have attached the output of oc get configmap -o yaml in the logs for your reference. 

Thanks

**Comment by phlogistonjohn** [comment]
The configmap(s) don't get created until the cluster cr is created. Until then the csi pods will be in this state. I agree with linking this issue to #2939 as the csi is pretty useless without a cluster. 
I woudln't bother with trying to work around this for now, I just suggest ensuring the pods do come up after the cluster is established.

**Comment by nehaberry** [comment]
Yeah thats correct. But the csi-rbdplugin pods stayed in containerCreating state until the cluster CRD was created. Upon creation of cluster CR, they almost immediately went into Crashloop state, stating some connection error to unix socket. 
Atleast after creating cluser CR, the cluster-config should have got populated and the csi-rbdplugin podd should have come up :) 


Complete log attached in the issue.

Log snip

I0617 05:33:22.857987       1 connection.go:106] Connection timed out
I0617 05:33:22.858034       1 connection.go:270] GRPC call: /csi.v1.Identity/GetPluginInfo
I0617 05:33:22.858047       1 connection.go:271] GRPC request: {}
I0617 05:33:22.858952       1 connection.go:273] GRPC response: {}
I0617 05:33:22.859415       1 connection.go:274] GRPC error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /csi/csi-provisioner.sock: connect: no such file or directory"
E0617 05:33:22.859441       1 main.go:131] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /csi/csi-provisioner.sock: connect: no such file or directory"
==== END logs for container csi-snapshotter of pod openshift-storage/csi-rbdplugin-provisioner-0 ====
==== START logs for container csi-rbdplugin of pod openshift-storage/csi-rbdplugin-provisioner-0 ====
E0617 05:36:06.521999       1 util.go:65] failed to define cache persistence method: cache-persister: couldn't parse metadatastorage flag
==== END logs for container csi-rbdplugin of pod openshift-storage/csi-rbdplugin-provisioner-0 ====


The ligs from the podd are attached

**Comment by ShyamsundarR** [comment]
> ==== START logs for container csi-rbdplugin of pod openshift-storage/csi-rbdplugin-provisioner-0 ====
> E0617 05:36:06.521999 1 util.go:65] failed to define cache persistence method: cache-persister: couldn't parse metadatastorage flag
> ==== END logs for container csi-rbdplugin of pod openshift-storage/csi-rbdplugin-provisioner-0 ====

The issue seems to be that the CSI images in use still expect the `metadatastorage` flag in the parameters to the container, but the pod manifest has changed to not mention the same. The pod manifest is correct as master rook branch is getting integrated with the v1.1 CSI code (or CSI master at present), but the image specification in the case of openshift is incorrect.

The CSI images in use by the openshift instance of the yaml is incorrect, as in [here](https://github.com/rook/rook/blob/8da222129643350dfd066370f30488b2fff9f897/cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml#L125-L130) and should instead be changed to the image versions as specified in the non-openshift case, [like so](https://github.com/rook/rook/blob/8da222129643350dfd066370f30488b2fff9f897/cluster/examples/kubernetes/ceph/operator-with-csi.yaml#L43-L48).

IOW, use the value of `"quay.io/cephcsi/cephfsplugin:canary"` for `ROOK_CSI_CEPHFS_IMAGE` and the value of `"quay.io/cephcsi/rbdplugin:canary"` for `ROOK_CSI_RBD_IMAGE`

**Comment by nehaberry** [comment]
@ShyamsundarR thanks for the analysis. So, in that case if we just change the contents of "operator-openshift-with-csi.yaml" to include changes specified [here](https://github.com/rook/rook/blob/8da222129643350dfd066370f30488b2fff9f897/cluster/examples/kubernetes/ceph/operator-with-csi.yaml#L43-L48), we are good to go ?

I remember @Madhu-1 mentioning that the canary image is not yet 100% ready. So is that problem resolved now ?

regards,
Neha

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR thanks for the analysis. So, in that case if we just change the contents of "operator-openshift-with-csi.yaml" to include changes specified [here](https://github.com/rook/rook/blob/8da222129643350dfd066370f30488b2fff9f897/cluster/examples/kubernetes/ceph/operator-with-csi.yaml#L43-L48), we are good to go ?
> 
> I remember @Madhu-1 mentioning that the canary image is not yet 100% ready. So is that problem resolved now ?
> 
> regards,
> Neha

Changing the images to the mentioned values should help make forward progress in the openshift environment.

Note: jFYI for the moment, the mentioned canary images are a pre-version of 1.1 as the image name, in ceph-csi master, has changed (with some more configuration changes) to cephcsi, but rook has not caught up to these changes yet.

**Comment by Madhu-1** [comment]
we need code changes and also test changes to use the canary tagged images 
@phlogistonjohn we should use `cephcsi` image ( as we are deprecating `rbdplugin` and `cephfsplugin` images)

@ShyamsundarR @nehaberry am working on bringing the cephcsi v1.1.0 changes in rook
i will post a PR soon

**Comment by ShyamsundarR** [comment]
@Madhu-1 till the changes to bring in ceph-csi:v1.1 are being done, should we just fix the file `operator-openshift-with-csi.yaml` to use images as in this [comment](https://github.com/rook/rook/issues/3312#issuecomment-503044237)? (just to get things moving as till now it looks like 3 folks have hit this particular issue).

If affirmative, I would suggest using the images as in the other file (cephfsplugin/rbdplugin) and then catching up with the v1.1 image names and options as part of your change.

**Comment by Madhu-1** [comment]
yes, let's have a PR to make image changes from v1.0.0 to canary  for openshift and also we need to have a doc to fetch the clusterID in config map and use it in storage-class (i see we have not documented this step)

**Comment by nehaberry** [comment]
Thanks for raising the PR. Can you please let us know when we are good to go.

**Comment by Madhu-1** [comment]
@nehaberry can you verify this issue

**Comment by nehaberry** [comment]
It worked with following steps. Apart from changing the image name in operator-openshift-with-csi.yaml, we did not change anything else. USed the latest rbac files from rook repo.

1. Used the  following images in operator-openshift-with-csi.yaml:

```
        - name: ROOK_CSI_CEPHFS_IMAGE
          value: "quay.io/cephcsi/cephfsplugin:canary"
        - name: ROOK_CSI_CEPHFS_IMAGE
          value: "quay.io/cephcsi/cephfsplugin:canary"

```

2. Created the rook operator.
 $ oc create -f  operator-openshift-with-csi.yaml

3.  With new changes, the agent and csi pods came up after running cluster CRD
 $ oc create -f cluster.yaml ( Did not make any change to this file, its a 2 month old file)


4.  The pods came up and able to provision rbd volumes

Versions

**sh-4.2 rook version**
 rook: v1.0.0-139.g818ad9c

**sh-4.2 ceph versions**
{

    "overall": {
        "ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)": 9
    }

**$ oc describe pod csi-rbdplugin-provisioner-0 -n openshift-storage|grep -i image**
    Image:         quay.io/k8scsi/csi-provisioner:v1.0.1
    Image ID:      quay.io/k8scsi/csi-provisioner@sha256:7d7d832832b536f32e899669a32d4fb75ab972da20c21a2bd6043eb498cf58e8
    Image:         quay.io/k8scsi/csi-attacher:v1.0.1
    Image ID:      quay.io/k8scsi/csi-attacher@sha256:6425af42299ba211de685a94953a5c4c6fcbfd2494e445437dd9ebd70b28bf8a
    Image:         quay.io/k8scsi/csi-snapshotter:v1.0.1
    Image ID:      quay.io/k8scsi/csi-snapshotter@sha256:2668993c32cad68a5ce6f05ec26f6e6cdb9ae8460ec52ed0425aeaed0b588e23
    Image:         quay.io/cephcsi/rbdplugin:canary
    Image ID:      quay.io/cephcsi/rbdplugin@sha256:755eaedd35bfcfe147e8795e5e398a89028a0a88dd90d42cf03a64c8bed88414

**$ oc logs csi-rbdplugin-provisioner-0 -n openshift-storage -c csi-provisioner**
I0620 05:07:27.696681       1 csi-provisioner.go:82] Version: v1.0.1-0-g9a258a0a

**$ oc logs csi-rbdplugin-provisioner-0 -n openshift-storage -c csi-rbdplugin**
I0620 05:07:33.016570       1 rbd.go:191] Driver: rbd.csi.ceph.com version: 1.0.0

$ oc logs csi-cephfsplugin-b9pbj -n openshift-storage  -c driver-registrar |more
I0620 05:06:45.675415       1 main.go:108] Version: v1.0.2-rc1-0-g2edd7f10

```
oc get pods -o wide -n openshift-storage; oc get cephfilesystem -n openshift-storage                                                                    Thu Jun 20 11:55:41 2019

NAME                                            READY   STATUS      RESTARTS   AGE   IP             NODE                                         NOMINATED NODE   READINESS GATES
csi-cephfsplugin-b9pbj                          2/2     Running     0          79m   10.0.174.210   ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
csi-cephfsplugin-provisioner-0                  3/3     Running     0          79m   10.131.0.11    ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
csi-cephfsplugin-qrm88                          2/2     Running     0          79m   10.0.131.121   ip-10-0-131-121.us-east-2.compute.internal   <none>           <none>
csi-cephfsplugin-xkrrj                          2/2     Running     0          79m   10.0.154.97    ip-10-0-154-97.us-east-2.compute.internal    <none>           <none>
csi-rbdplugin-nrtzb                             2/2     Running     0          79m   10.0.131.121   ip-10-0-131-121.us-east-2.compute.internal   <none>           <none>
csi-rbdplugin-provisioner-0                     4/4     Running     0          79m   10.128.2.16    ip-10-0-131-121.us-east-2.compute.internal   <none>           <none>
csi-rbdplugin-sxg5d                             2/2     Running     0          79m   10.0.174.210   ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
csi-rbdplugin-zs4ns                             2/2     Running     0          79m   10.0.154.97    ip-10-0-154-97.us-east-2.compute.internal    <none>           <none>
rook-ceph-agent-pt75p                           1/1     Running     0          79m   10.0.174.210   ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
rook-ceph-agent-qcslq                           1/1     Running     0          79m   10.0.131.121   ip-10-0-131-121.us-east-2.compute.internal   <none>           <none>
rook-ceph-agent-wz689                           1/1     Running     0          79m   10.0.154.97    ip-10-0-154-97.us-east-2.compute.internal    <none>           <none>
rook-ceph-mds-ocsci-cephfs-a-5c4df6cc8d-pjq74   1/1     Running     0          74m   10.129.2.16    ip-10-0-154-97.us-east-2.compute.internal    <none>           <none>
rook-ceph-mds-ocsci-cephfs-b-5494857cd-psx7s    1/1     Running     0          74m   10.131.0.16    ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
rook-ceph-mgr-a-67b65dbb7f-h79f8                1/1     Running     0          77m   10.131.0.13    ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
rook-ceph-mon-a-69b5d6d7f7-sz8px                1/1     Running     0          78m   10.128.2.14    ip-10-0-131-121.us-east-2.compute.internal   <none>           <none>
rook-ceph-mon-b-695775c7d-lln6w                 1/1     Running     0          78m   10.129.2.13    ip-10-0-154-97.us-east-2.compute.internal    <none>           <none>
rook-ceph-mon-c-689f884f7f-kq6j8                1/1     Running     0          77m   10.131.0.12    ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
rook-ceph-operator-5cf6856646-cp2hg             1/1     Running     0          80m   10.128.2.11    ip-10-0-131-121.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-0-5dd6fb88fd-29r8h                1/1     Running     0          76m   10.128.2.18    ip-10-0-131-121.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-1-5d95647f98-72g59                1/1     Running     0          76m   10.129.2.15    ip-10-0-154-97.us-east-2.compute.internal    <none>           <none>
rook-ceph-osd-2-5cdfbb475b-xc877                1/1     Running     0          76m   10.131.0.15    ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-ip-10-0-131-121-t6q5j     0/2     Completed   0          76m   10.128.2.17    ip-10-0-131-121.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-prepare-ip-10-0-154-97-6vqwh	0/2     Completed   0          76m   10.129.2.14    ip-10-0-154-97.us-east-2.compute.internal    <none>           <none>
rook-ceph-osd-prepare-ip-10-0-174-210-586z6     0/2     Completed   0          76m   10.131.0.14    ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
rook-ceph-tools-76c7d559b6-jntg5                1/1     Running     0          75m   10.0.154.97    ip-10-0-154-97.us-east-2.compute.internal    <none>           <none>
rook-discover-4rrlt                             1/1     Running     0          79m   10.131.0.10    ip-10-0-174-210.us-east-2.compute.internal   <none>           <none>
rook-discover-5jj6n                             1/1     Running     0          79m   10.128.2.12    ip-10-0-131-121.us-east-2.compute.internal   <none>           <none>
rook-discover-zz2hq                             1/1     Running     0          79m   10.129.2.12    ip-10-0-154-97.us-east-2.compute.internal    <none>           <none>

```

**Comment by nehaberry** [comment]
@Madhu-1 

Adding the clusterroles output for your reference.


```

(ocs-ci) [nberry@localhost cephfs]$ oc get clusterrole -n openshift-storage|grep csi
cephfs-csi-nodeplugin                                                  90m
cephfs-csi-nodeplugin-rules                                            90m
rbd-csi-nodeplugin                                                     90m
rbd-csi-nodeplugin-rules                                               90m
system:csi-external-attacher                                           107m
system:csi-external-provisioner                                        107m
(ocs-ci) [nberry@localhost cephfs]$ oc get clusterrole -n openshift-storage cephfs-csi-nodeplugin -o yaml
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.ceph.rook.io/aggregate-to-cephfs-csi-nodeplugin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"aggregationRule":{"clusterRoleSelectors":[{"matchLabels":{"rbac.ceph.rook.io/aggregate-to-cephfs-csi-nodeplugin":"true"}}]},"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"cephfs-csi-nodeplugin"},"rules":[]}
  creationTimestamp: "2019-06-20T05:04:41Z"
  name: cephfs-csi-nodeplugin
  resourceVersion: "16983"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/cephfs-csi-nodeplugin
  uid: e9a5c49a-9318-11e9-85f1-025b78b65eae
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
(ocs-ci) [nberry@localhost cephfs]$ oc get clusterrole -n openshift-storage cephfs-csi-nodeplugin-rules -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"rbac.ceph.rook.io/aggregate-to-cephfs-csi-nodeplugin":"true"},"name":"cephfs-csi-nodeplugin-rules"},"rules":[{"apiGroups":[""],"resources":["nodes"],"verbs":["get","list","update"]},{"apiGroups":[""],"resources":["namespaces"],"verbs":["get","list"]},{"apiGroups":[""],"resources":["persistentvolumes"],"verbs":["get","list","watch","update"]},{"apiGroups":["storage.k8s.io"],"resources":["volumeattachments"],"verbs":["get","list","watch","update"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["get","list"]}]}
  creationTimestamp: "2019-06-20T05:04:42Z"
  labels:
    rbac.ceph.rook.io/aggregate-to-cephfs-csi-nodeplugin: "true"
  name: cephfs-csi-nodeplugin-rules
  resourceVersion: "16982"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/cephfs-csi-nodeplugin-rules
  uid: e9f62c8c-9318-11e9-85f1-025b78b65eae
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
(ocs-ci) [nberry@localhost cephfs]$ oc get clusterrole -n openshift-storage rbd-csi-nodeplugin-rules -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"rbac.ceph.rook.io/aggregate-to-rbd-csi-nodeplugin":"true"},"name":"rbd-csi-nodeplugin-rules"},"rules":[{"apiGroups":[""],"resources":["nodes"],"verbs":["get","list","update"]},{"apiGroups":[""],"resources":["namespaces"],"verbs":["get","list"]},{"apiGroups":[""],"resources":["persistentvolumes"],"verbs":["get","list","watch","update"]},{"apiGroups":["storage.k8s.io"],"resources":["volumeattachments"],"verbs":["get","list","watch","update"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["get","list"]}]}
  creationTimestamp: "2019-06-20T05:04:33Z"
  labels:
    rbac.ceph.rook.io/aggregate-to-rbd-csi-nodeplugin: "true"
  name: rbd-csi-nodeplugin-rules
  resourceVersion: "16920"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/rbd-csi-nodeplugin-rules
  uid: e4cc4d49-9318-11e9-a1ef-0a7533e00b86
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
(ocs-ci) [nberry@localhost cephfs]$ oc get clusterrole -n openshift-storage rbd-csi-nodeplugin -o yaml
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.ceph.rook.io/aggregate-to-rbd-csi-nodeplugin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"aggregationRule":{"clusterRoleSelectors":[{"matchLabels":{"rbac.ceph.rook.io/aggregate-to-rbd-csi-nodeplugin":"true"}}]},"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"rbd-csi-nodeplugin"},"rules":[]}
  creationTimestamp: "2019-06-20T05:04:33Z"
  name: rbd-csi-nodeplugin
  resourceVersion: "16921"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/rbd-csi-nodeplugin
  uid: e47c4242-9318-11e9-a1ef-0a7533e00b86
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list


```

**Comment by Madhu-1** [comment]
@nehaberry Thanks for confirming, 
@travisn can we close this issue or we have to keep it open?

**Comment by j-griffith** [comment]
This currently fails on kubernetes release 1.15 as well with the same error.

**Comment by Madhu-1** [comment]
@j-griffith hope your issue is resolved and we can close this one

**Comment by Madhu-1** [comment]
closing this as its  fixed
