### ISSUE TITLE
Very low performance of PVs with CephFS CSI driver

### ISSUE THREAD

**Issue by masantiago** [rook/rook#3315]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The performance of volumes dynamically created by CephFS CSI StorageClass is quite low compared to a traditional flexVolume. Find below some results obtained in a simple vagrant single-node test:

```
** Dynamic PV with CSI Storage Class **
dd if=/dev/zero of=tempfile bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 41.1444 s, **26.1 MB/s**

PV:
cephfs-pvc    Bound    pvc-df6483ad-8fca-11e9-b29f-02bca84242bc   50Gi       RWX            csi-cephfs     44h
```

```
** Static PV with Flex Volume **
dd if=/dev/zero of=tempfile bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.32337 s, **811 MB/s**

PV:
oe-scratch                                 40Gi       RWX            Recycle          Bound    default/oe-scratch    rook-cephfs             43m
```

**Expected behavior:**
Both use cases should perform likewise because they are using the same ceph file system and in the same environment (single-node)

**How to reproduce it (minimal and precise):**

1. Follow instruction of [tutorial](https://rook.io/docs/rook/v1.0/ceph-filesystem.html) to create a ceph file system in just one node.
2. Follow instructions of [Test CephFS CSI driver](https://rook.io/docs/rook/v1.0/ceph-csi-drivers.html#Test-CephFs-CSI-Driver) to create a storage class, pvc and pod using such pvc.
3. Follow instructions of [thread](https://github.com/rook/rook/issues/1125#issuecomment-469488011) to create a static PV using the same ceph file system. The PV is mounted inside the same pod.
4. Compute statistics in both mounted points.

**Environment**:
* OS (e.g. from /etc/os-release): VM created by vagrant with Ubuntu 16.04.6 LTS
* Kernel (e.g. `uname -a`): Linux k8s-master1 4.4.0-150-generic
* Cloud provider or hardware configuration:
```
app.vm.provider "virtualbox" do |v|
     		v.memory = 6144
      		v.cpus = 6
		end
```
* Rook version (use `rook version` inside of a Rook Pod): v1.0.0-122.g488fe64
* Kubernetes version (use `kubectl version`): v1.13.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): raw kubernetes with kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

The filesystem appears like:

```
RAW STORAGE:
    CLASS     SIZE       AVAIL      USED        RAW USED     %RAW USED 
    ssd       99 GiB     96 GiB     2.2 GiB      3.2 GiB          3.20 
    TOTAL     99 GiB     96 GiB     2.2 GiB      3.2 GiB          3.20 
 
POOLS:
    POOL                ID     STORED      OBJECTS     USED        %USED     MAX AVAIL 
    tcs-fs-metadata      1     171 MiB          69     172 MiB      0.18        91 GiB 
    tcs-fs-data0         2       2 GiB         512       2 GiB      2.15        91 GiB 
```

**Comment by masantiago** [comment]
I've found out that the PODs using dynamically created PVs are using **ceph-fuse** as filesystem:

```
ceph-fuse               50G  1.0G   49G   2% /var/lib/www/html
```

Therefore, I assume that the low throughput has to do with the user space as mounting point. Does it make sense to have such a difference of 30x? Or is there any parameter to configure?

**Comment by Madhu-1** [comment]
@ajarr can you help with this?

**Comment by BlaineEXE** [comment]
@travisn do we know if this is still an issue?

**Comment by travisn** [comment]
#3601 will help with performance, but I haven't heard beyond that. @ajarr are you aware of another issue here?

**Comment by ajarr** [comment]
It's recommended to use the CephFS kernel client mounter rather than FUSE client mounter for good performance. Since kernel clients >= 4.17 support quotas and snapshots, https://docs.ceph.com/docs/master/cephfs/kernel-features/#quotas, it's the mounter to use.

There is on-going discussion in the Ceph CSI community to used kernel as the default mounter for CephFS CSI. For now, you can set this by,
https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml#L31

**Comment by masantiago** [comment]
@ajarr, sure. I will give it a try by updating kernel in my VM and using kernel client mounter. 

The ceph image version in my deployment was: ceph/ceph:v14.2.1-20190430

Do you recommend using the same ceph and latest rook? Some days ago I tested a recent nautilus ceph version (14.2) with wrong behavior. I did not have time to make diagnostics, but rather not to mix things up.

**Comment by ajarr** [comment]
@masantiago, recommend using latest rook and its defaults. A CephFS issue in v14.2.2 was resolved by a temporary fix in rook master. Can you please give it an another try? The ceph-csi project's end to end CI that tests this configuration for basic PV creation and mount has been passing.

**Comment by masantiago** [comment]
I'm working on the test. After dealing with some issues for the kernel, I managed to do it:
```
NAME          STATUS   ROLES    AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION           CONTAINER-RUNTIME
k8s-master1   Ready    master   172m   v1.13.2   172.168.33.10   <none>        Ubuntu 16.04.6 LTS   4.17.19-041719-generic   docker://18.6.0
```
Now I'm facing the installation of rook:

- **helm installation**: from the release branch dated 2019-08-14T22:57:07.000Z 
```
rook-ceph          	1       	Fri Aug 16 11:21:32 2019	DEPLOYED	rook-ceph-v1.0.5         	           	tcs-ceph
```
- **ceph**: from the image ceph/ceph:v14.2.2-20190722

But, how do I install the csi plugins if used the helm package? The documentations seems to be no update as it refers to a file: operator-with-csi.yaml which no longer exists in latest master branch.

I have found out the templates: cluster/examples/kubernetes/ceph/csi/template/cephfs, but before any trial&error, I'd rather your suggestions.

**Comment by masantiago** [comment]
It seems that helm from master and from release are totally different right? I moved to release because version 1.0.5 was bigger than that of master 1.0.0. It made me some confusion.

As far I read, the master branch has CSI activated by default, and then there is no need any plugin.

I look forward to hearing from your comments.

**Comment by ajarr** [comment]
> I'm working on the test. After dealing with some issues for the kernel, I managed to do it:
> 
> ```
> NAME          STATUS   ROLES    AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION           CONTAINER-RUNTIME
> k8s-master1   Ready    master   172m   v1.13.2   172.168.33.10   <none>        Ubuntu 16.04.6 LTS   4.17.19-041719-generic   docker://18.6.0
> ```
> 
> Now I'm facing the installation of rook:
> 
> * **helm installation**: from the release branch dated 2019-08-14T22:57:07.000Z
> 
> ```
> rook-ceph          	1       	Fri Aug 16 11:21:32 2019	DEPLOYED	rook-ceph-v1.0.5         	           	tcs-ceph
> ```
> 
> * **ceph**: from the image ceph/ceph:v14.2.2-20190722
> 
> But, how do I install the csi plugins if used the helm package? The documentations seems to be no update as it refers to a file: operator-with-csi.yaml which no longer exists in latest master branch.

@Madhu-1 any ideas?

> 
> I have found out the templates: cluster/examples/kubernetes/ceph/csi/template/cephfs, but before any trial&error, I'd rather your suggestions.

**Comment by ajarr** [comment]
> It seems that helm from master and from release are totally different right? I moved to release because version 1.0.5 was bigger than that of master 1.0.0. It made me some confusion.
> 
Yeah, the naming is confusing. Master definitely is the latest. Can you use the image,
rook/rook:v1.0.0-409.gbfe867e ?

v1.0.5 doesn't have the commits to set up the CSI driver by default 

> As far I read, the master branch has CSI activated by default, and then there is no need any plugin.
> 
> I look forward to hearing from your comments.

Correct.
https://github.com/rook/rook/commit/0a3fbf62f37ee9

**Comment by masantiago** [comment]
Done. 
```
rook-ceph          	1       	Fri Aug 16 15:44:28 2019	DEPLOYED	rook-ceph-v1.0.0-409.gbfe867e	           	rook-ceph
```

csi cephfs plugin is running
```
rook-ceph        csi-cephfsplugin-2mh76                                    2/2     Running            0          33m
rook-ceph        csi-cephfsplugin-provisioner-0                            3/3     Running            0          33m
```

Unfortunately, something is missing in terms of RBAC permission as the containers inside the provisioner are complaining all the time:

```
kubectl -n rook-ceph logs -f csi-cephfsplugin-provisioner-0 -c csi-provisioner

E0816 14:24:12.263698       1 reflector.go:126] sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:806: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-cephfs-provisioner-sa" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope: RBAC: [clusterrole.rbac.authorization.k8s.io "psp:rook" not found, clusterrole.rbac.authorization.k8s.io "cephfs-external-provisioner-runner" not found]

E0816 14:24:12.265152       1 reflector.go:126] sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:800: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-cephfs-provisioner-sa" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope: RBAC: [clusterrole.rbac.authorization.k8s.io "cephfs-external-provisioner-runner" not found, clusterrole.rbac.authorization.k8s.io "psp:rook" not found]
```

That prevents from any PVC to work. Thank you very much for all your help!

**Comment by ajarr** [comment]
@masantiago , can you post your deployment issues on rook's slack  (and join #ceph-csi channel there) ? You'll have more eyes on your issue, and better responses.

https://github.com/rook/rook/blob/master/README.md#contact

**Comment by masantiago** [comment]
Ok. I have already suscribed to the channel and waiting replies...

BUT.. **I've got it!** I found a problem in helm construction of the master package. In template clusterrole.yaml, line 207, there is a if-clause :

```
{{- if ((.Values.agent) and .Values.agent.mountSecurityMode) and ne .Values.agent.mountSecurityMode "Any" }}
```
that, IMHO, should finish in line 237. Otherwise, there are many cluterrole's that are not created with the defaults. If not, please let me know the **mountSecurityMode** that I should select. I did not find the options.

And, going back to the point to the Issue, I can now confirm that with Kernel 4.17.19-041719-generic **performs much much better** as stated in #3619 as well.
