### ISSUE TITLE
Request for a new branch in this repo for CSI transition from Flex

### ISSUE THREAD

**Issue by humblec** [rook/rook#3323]
**What should the feature do:**

I would like to request a new branch in Rook to smooth the transition to Ceph CSI from "flex" based driver. That said, whatever changes we have to make on deployment artifacts can be done in this branch and later once its in shape we could merge back or retain the branch accordingly.

The suggested branch name is `csi` or `csi v.1.1.0`

**Comment by humblec** [comment]
@travisn @Madhu-1 FYI

**Comment by humblec** [comment]
Early bed for #https://github.com/ceph/ceph-csi/issues/353

**Comment by travisn** [comment]
I would recommend someone create a branch in their own fork and grant access to those who need to work there. We shouldn't need to create a branch in the main rook repo. Also to consider is that if we can do it with individual PRs, the changes could all go into master directly. But if multiple people are working on the effort, the branch could certainly be helpful.
