### ISSUE TITLE
No upgrade of rook-ceph cluster from v0.9.3 to v1.0.x in rook-ceph namespace

### ISSUE THREAD

**Issue by lewismarshall** [rook/rook#3327]
Searched for `ROOK_CURRENT_NAMESPACE_ONLY` with no results

**Is this a bug report or feature request?**
* Bug Report
Rook operator fails to update cluster to v1.0.2 from v0.9.3 when ceph cluster is deployed to `rook-ceph` namespace when using the chart yamls.

**Deviation from expected behavior:**
rook-ceph-mgr/mon/ods deployments left alone.

**Expected behavior:**
rook-ceph-mgr/mon/ods deployments upgraded rook image from v0.9.3 to v1.0.2

**How to reproduce it (minimal and precise):**

1. Deploy v0.9.3 operator and Ceph cluster using rook-ceph-system and rook-ceph namespaces respectively using the helm chart templates at version v0.9.3. 
1. Delete the [old permissions](https://github.com/rook/rook/blob/v1.0.2/Documentation/ceph-upgrade.md#2-update-modified-permissions)
1. Redeploy the charts using the manifests from v1.0.2 version of the charts.

**Note**
Easily worked around by updating the variable from 
https://github.com/rook/rook/blob/ecca2daaedd8982e87abef17acd57e76e049a1ec/cluster/charts/rook-ceph/templates/deployment.yaml#L30-L31

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
* Kernel (e.g. `uname -a`): `Linux ip-192-168-6-128.eu-west-2.compute.internal 4.14.106-97.85.amzn2.x86_64 #1 SMP Fri Mar 15 17:07:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
* Cloud provider or hardware configuration: `eks`
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.0.2`
* Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `EKS`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
  cluster:
    id:     0798b0ac-18b1-47bf-a887-b24ac20e18a0
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c
    mgr: a(active)
    osd: 5 osds: 5 up, 5 in

  data:
    pools:   1 pools, 100 pgs
    objects: 429  objects, 1.3 GiB
    usage:   8.4 GiB used, 5.0 TiB / 5.0 TiB avail
    pgs:     100 active+clean

  io:
    client:   11 KiB/s wr, 0 op/s rd, 1 op/s wr
```

**Comment by chh315** [comment]
I got this one too.

all osds not upgrated.
rook-ceph-mgr-a         req/upd/avl: 1/1/1      rook-version=v1.0.2
rook-ceph-mon-a         req/upd/avl: 1/1/1      rook-version=v1.0.2
rook-ceph-mon-b         req/upd/avl: 1/1/1      rook-version=v1.0.2
rook-ceph-mon-c         req/upd/avl: 1/1/1      rook-version=v1.0.2
rook-ceph-osd-0         req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-1         req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-2         req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-3         req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-4         req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-5         req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-6         req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-7         req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-8         req/upd/avl: 1/1/1      rook-version=
rook-ceph-osd-9         req/upd/avl: 1/1/1      rook-version=
rook-ceph-tools         req/upd/avl: 1/1/1      rook-version=

**Comment by chh315** [comment]
@lewismarshall
did you see this log at rook-operator?
>E | op-cluster: failed to create cluster in namespace rook-ceph. failed to start the osds. refuse to run the pod with 1024mb of ram, provide at least 4096mb. 

I cleared this one, and worked.

**Comment by mumrau** [comment]
@travisn You're the one that moved the logic from 2 namespaces back into one as a simplification of deployment, see here: https://github.com/rook/rook/commit/eb74bf5547d6056938376988dea64ecfba82af0e .

Nonetheless, I do believe than on upgrade using helm, which works pretty much flawlessly, users can be quite surprised to not see any activity once the daemonsets in `rook-ceph-system` are updated.
I found the environment variable `ROOK_CURRENT_NAMESPACE_ONLY` has been added to the deployment of the operator, and it wasn't configurable with `helm`.

I'm making a PR which I'll reference in this issue allowing the setup through `helm` for that variable.
Maybe we should update the upgrade documentation for `helm` as well?

**Comment by christianhuening** [comment]
well aside from the ENV flag i am having the same issue as @chh315 in that my OSDs are not updated. Mons and MGR are updated, but OSDs are not. 
The operator in DEBUG mode just has a lot of
`op-cluster: Skipping cluster update. Updated node node-7.<redacted> was and it is still schedulable`


Any ideas?
