### ISSUE TITLE
crashed osd pods should be deleted, and new osd pods should be spawned by rook

### ISSUE THREAD

**Issue by xenolinux** [rook/rook#3330]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After detaching and reattaching disk to a worker node, the pods which are in `CrashBackLoopOf` state are not getting deleted by Rook. Also if the disk is re-attached then new pod doesn't get spawned.

**Expected behavior:**
As soon as an osd is re-attached, a new osd pod should be created and old crashing pods should get deleted automatically.

**How to reproduce it (minimal and precise):**

1.  Detached volume attached to AWS instances. [ out of 3 worker nodes, detached disks of 2 nodes  2.  Marked 2 osds out the same osds (volumes) which were detached from AWS instances .
3.  OSDs became down.
4.  Kubernetes tried to restart the OSD pods but pods went into CrashLoopBackOff state. 

**Note**
the steps mentioned above must not in a strict sequence. It's more like an approach rather than a sequential path.

**Environment**:
* Rook version :  rook: v1.0.2
* Kubernetes version : 
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+7bd2e5b", GitCommit:"7bd2e5b", GitTreeState:"clean", BuildDate:"2019-05-19T23:52:43Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+838b4fa", GitCommit:"838b4fa", GitTreeState:"clean", BuildDate:"2019-05-19T23:51:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type : OpenShift

**Additional Information**
[root@ip-10-0-168-154 /]# ceph -s
  cluster:
    id:     0efeaa1d-3ae2-49af-8b6f-618f8ece982b
    health: HEALTH_WARN
            1 osds down
            1 host (1 osds) down
            Reduced data availability: 25 pgs inactive, 86 pgs stale
 
  services:
    mon: 3 daemons, quorum a,b,c (age 25h)
    mgr: a(active, since 25h)
    osd: 3 osds: 1 up (since 61m), 2 in (since 30m)
 
  data:
    pools:   2 pools, 192 pgs
    objects: 14 objects, 35 KiB
    usage:   1.0 GiB used, 98 GiB / 99 GiB avail
    pgs:     13.021% pgs unknown
             86 stale+active+clean
             81 active+clean 
             25 unknown =============================== After creating new pool and adding the data in new pool pgs went into unknown state

$  kubectl logs  -n rook-ceph rook-ceph-osd-0-67fc84f79-v5mxx 
2019-06-18 09:54:56.880489 I | rookcmd: starting Rook v1.0.0-122.g488fe64 with arguments '/rook/rook ceph osd start -- --foreground --id 0 --osd-uuid 40159abb-eca5-42f9-b7d3-fa1be2da47d7 --conf /var/lib/rook/osd0/rook-ceph.config --cluster ceph --default-log-to-file false'
2019-06-18 09:54:56.880578 I | rookcmd: flag values: --help=false, --log-flush-frequency=5s, --log-level=INFO, --osd-id=0, --osd-store-type=bluestore, --osd-uuid=40159abb-eca5-42f9-b7d3-fa1be2da47d7
2019-06-18 09:54:56.880586 I | op-mon: parsing mon endpoints: 
2019-06-18 09:54:56.880594 W | op-mon: ignoring invalid monitor 
2019-06-18 09:54:56.880817 I | exec: Running command: stdbuf -oL ceph-volume lvm activate --no-systemd --bluestore 0 40159abb-eca5-42f9-b7d3-fa1be2da47d7
2019-06-18 09:54:57.561634 I | -->  RuntimeError: could not find osd.0 with fsid 40159abb-eca5-42f9-b7d3-fa1be2da47d7
failed to activate osd. Failed to complete '': exit status 1.

**Comment by nehaberry** [comment]
Thanks for raising this bug. We have also seen this issue while adding new disks. The new disks are getting detected mostly after we perform a manual re-spin of operator pod, which shouldn't be the workaround.

**Comment by xenolinux** [comment]
Yes. Right !
