### ISSUE TITLE
mds active/standby lack anti-affinity

### ISSUE THREAD

**Issue by anguslees** [rook/rook#3332]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

```console
$ kubectl -n rook-ceph get pod -l app=rook-ceph-mds -o wide
NAME                                               READY   STATUS    RESTARTS   AGE   IP            NODE                               NOMINATED NODE
rook-ceph-mds-ceph-filesystem-a-7866d4cd68-mnlxz   1/1     Running   0          6m    10.244.8.22   0b5642a6cc18493d81a606483d9cbb7b   <none>
rook-ceph-mds-ceph-filesystem-b-56cf9d9986-fzn5p   1/1     Running   0          8m    10.244.8.21   0b5642a6cc18493d81a606483d9cbb7b   <none>
```

Both mds instances were scheduled on the same host.  This seems bad for something that exists to be a failover pair (aiui).

Sure enough, the k8s config for these pods has `affinity: {}`.

**Expected behavior:**

I think there should be a AZ/host pod anti-affinity rule configured.  Something like:

```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        app: rook-ceph-mds
      topologyKey: kubernetes.io/hostname
```

Alternatively, we could use a weaker `preferredDuringSchedulingIgnoredDuringExecution` with multiple AZ/host terms.

**How to reproduce it (minimal and precise):**

Straightforward `CephFilesystem` with
```yaml
  spec:
    dataPools:
    - replicated:
        size: 2
    metadataPool:
      crushRoot: ""
      erasureCoded:
        algorithm: ""
        codingChunks: 0
        dataChunks: 0
      failureDomain: ""
      replicated:
        size: 3
    metadataServer:
      activeCount: 1
      activeStandby: true
      placement: {}
      resources: {}
```

I imagine I can configure this myself with `metadataServer.placement` (I will try that next).  I suggest anti-affinity should be the default.

**Environment**:

operator = rook/ceph:v1.0.2
cephVersion.image = ceph/ceph:v13.2.5-20190410

**Comment by mmgaggle** [comment]
Similarity, the `failure-domain.beta.kubernetes.io/zone` toplogyKey should be an option here.

**Comment by travisn** [comment]
@anguslees What anti-affinity did you end up using for the mds daemons? Agreed that `requiredDuringSchedulingIgnoredDuringExecution` would be optimal here. 
@ashishranjan738 @sp98 @umangachapagain Could one of you take a look at this?

**Comment by mmgaggle** [comment]
It appears that #3659 does not handle failure-domain.beta.kubernetes.io/zone along the lines of #3355. Should this issue be re-opened or should I create a new distinct issue?

**Comment by umangachapagain** [comment]
This could be re-opened with details on the failure.
