### ISSUE TITLE
FlexVolume doesn't error for nonexistent CephFileSystem

### ISSUE THREAD

**Issue by iMartyn** [rook/rook#3335]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When specifying an incorrect CephFS using the CephFS FlexVolume, instead of failing, the pod starts and mounts ephemeral storage in it's place.

**Expected behavior:**
I would expect when mounting a CephFS FlexVolume in a pod that if I get the name of the CephFS wrong, the pod would not start and would remain in pending much like when a PV cannot be attached etc.

**How to reproduce it (minimal and precise):**
* On a running Rook cluster, create a cephFileSystem object with a known name
* Create a pod with a flexVolume mount of the same, but misspell the name
* Note that the pod runs and sees an empty directory, if you write to that directory, and restart the pod, that data is gone!

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
* Kernel (e.g. `uname -a`): Linux aks-nodepool1-27848402-1 4.15.0-1045-azure #49-Ubuntu SMP Mon May 13 16:30:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Azure
* Rook version (use `rook version` inside of a Rook Pod): ` rook: v1.0.2`
* Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):`HEALTH_OK

**Comment by iMartyn** [comment]
This also occurs if you specify a path that doesn't exist in the cephfs for reference.  e.g. I `mkdir /team.name/folder` and specify `/team.name/fodler` as the `Path:` element in options.

**Comment by travisn** [comment]
The core Rook team is focusing on the CSI driver now, but contributions are always welcome.
