### ISSUE TITLE
Rook 1.0.2 attaches unwanted drives

### ISSUE THREAD

**Issue by dimm0** [rook/rook#3337]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
With
```
    useAllNodes: false
    useAllDevices: false
```

rook attaches the drives on nodes I want, and also some small space from system drive that was unused (~50GB)

**Expected behavior:**
Rook only uses the space I told it to use

**How to reproduce it (minimal and precise):**
Not sure how to reproduce..

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
5.1.7
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
1.0.2
* Kubernetes version (use `kubectl version`):
1.15.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by noahdesu** [comment]
Does " also some small space from system drive that was unused " mean you see Ceph using some partition (on a drive with other partitions) to create an OSD? It would be helpful to produce a log or report of the devices, partitions, and how Ceph is using them for the node in question.

**Comment by dimm0** [comment]
> Does " also some small space from system drive that was unused " mean you see Ceph using some partition (on a drive with other partitions) to create an OSD

Yes

>It would be helpful to produce a log or report of the devices, partitions, and how Ceph is using them for the node in question.

That's actually all nodes... Which exactly logs should I send?
The provision pods are gone before I could get anything from them..

Does this look right?

https://gitlab.nautilus.optiputer.net/nrp/rook/blob/master/nrp-cluster.yaml

Or I missed something and it's still doing "all drives"?

**Comment by noahdesu** [comment]
I was thinking something like the output of `ceph-volume lvm list` might be helpful and `lsblk`. It'd be nice to see what devices / partitions are being automatically consumed that _shouldn't_ be consumed. i think only a single node with this behavior would be sufficient. for the logs, the operator, discover, and osd prepare pod logs should be good.

**Comment by noahdesu** [comment]
Hi @dimm0 I think what you might be seeing is that Rook is creating an extra OSD on the root drive, but not actually consuming a partition on the root device? that extra osd may come from here: https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-test.yaml#L37

**Comment by dimm0** [comment]
Hmm.. Are you saying it's expected?
I'm looking at logs, and 2nd OSDs don't have a record like the 1st ones do: `bluestore block path = /var/lib/ceph/osd/ceph-0/block`
So are those only to store some metadata?

**Comment by dimm0** [comment]
I'm glad I didn't delete those then 😅

**Comment by travisn** [comment]
@dimm0 In v0.9 and earlier an OSD was created by default under the dataDirHostPath. So if you upgraded from v0.9 that OSD would still exist and likely explains it. If you have a fresh install on 1.0 without the `directories` specified in the cluster.yaml, this OSD wouldn't be expected.

**Comment by dimm0** [comment]
I gave a link earlier to my config: https://gitlab.nautilus.optiputer.net/nrp/rook/blob/master/nrp-cluster.yaml

**Comment by noahdesu** [comment]
In 1.0 when I install with devices, I get an extra OSD if the directories entry is in the cluster yaml. You could look in the dataDirHostPath directory on a node and see if it is populated with files.

**Comment by dimm0** [comment]
I see standard files like before in it...
Ok, I guess it's expected then. Closing.
