### ISSUE TITLE
Custom InitContainer definition.

### ISSUE THREAD

**Issue by iMartyn** [rook/rook#3343]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Accept a custom initcontainer per pod type and add it in the operator.  If with volume support, even better.

**What is use case behind this feature:**

Use Case 1:
* Run manual prepare steps prior to running an OSD on a machine for cleanup (dangerous), attaching external disks, or other preparatory steps

Use Case 2:
* (with volume support) Specify a PVC to be used with rook (e.g. rook-on-azure-disk), find it's mount point, unmount and zap it so rook can use it.

Use Case 3:
* (whilst #3334 exists) Allow running of the command to set the mgr dashboard and prometheus IPs to the pod IP or 0.0.0.0

...and probably some more.

**Environment**:
Any rook-ceph cluster.  This would be really neat with volume support in cloud providers that mount PVCs as /dev/sd{x}

**Comment by travisn** [comment]
While powerful, this would be a pretty risky feature to provide that much flexibility. Rook wouldn't really be able to support the side effects of using that feature. 

Note that for use case 2, it's a work in progress to add support for mons and OSDs on top of PVCs. See #3306.

**Comment by iMartyn** [comment]
Yeah, I understand, and the risks should be accepted by whoever uses it, but right now we have a 3-stage Jenkins pipeline to do a whole load of prep and because we're in an auto-scaling environment, with the lack of `daemonJob` kinds in k8s, we're getting to the point where we write an operator for rook! I'm sure this would really be helpful in multiple use cases I think and the potential harm, as long as it is advertised correctly, should be minimal.
