### ISSUE TITLE
Rook assumes namespace = cluster name

### ISSUE THREAD

**Issue by leseb** [rook/rook#3344]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

In too many places, the namespace is treated as the cluster name.

**Expected behavior:**

Rook must not assume namespace = cluster name

**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
Rook requires the `clusterName` to be the same as the namespace. So it is only a naming issue where some variables are called `clusterName`, while others are called `namespace`.

**Comment by leseb** [comment]
It might require that but this requirement is not enforced as I can tell :/

**Comment by e-minguez** [comment]
Just in case https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/user/controller.go#L172

**Comment by travisn** [comment]
The `name` can be different from the `namespace`, but consider that the `name` is effectively ignored by rook. To clarify the rook requirement here:
- Only one rook cluster is supported per namespace. This requirement simplifies rook in a number of ways.
- Rook does not require the `name` to be the same as the `namespace`. Rather, rook will internally ignore the `name` and base all of the naming on the `namespace`. The storage class labels on the resources, etc, will refer to the namespace. Only in a couple of key places is the `name` used where required by k8s, such as for the `ownerReferences` (for garbage collection).

So I'm not sure there is even a bug here to fix other than some internal variable names in the code. @leseb is that fair?

**Comment by leseb** [comment]
@travisn I guess I'm fine with the rational, it's just that things like this: https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/admin.go#L27-L31 could/should be simplified.

The fix, as you said would be to switch some internal variables to prefer Namespace against ClusterName.
