### ISSUE TITLE
Support for custom pg_num in Ceph Block Pool CRD

### ISSUE THREAD

**Issue by iExalt** [rook/rook#3349]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
When creating a Ceph Block Pool through the CRD, there is currently no support for changing the number of placement groups. The [Ceph documentation](http://docs.ceph.com/docs/nautilus/rados/operations/placement-groups/#placement-groups-tradeoffs) stresses the importance of choosing a proper number of placement groups given the number of OSDs in the cluster. Pg_num can be changed after pool creation with the Ceph dashboard or the tools pod, however doing so incurs a performance hit.

In addition to supporting custom pg_nums, a possible stretch goal could be supporting [pg autoscaling](https://ceph.com/rados/new-in-nautilus-pg-merging-and-autotuning/)

**What is use case behind this feature:**
Sizing pools correctly at creation time for production Rook/Ceph deployments

**Comment by noahdesu** [comment]
Hi @iExalt you can change the number of placement groups manually using the Ceph toolbox. You can also set a default number of placement groups for new pools.

> In the near future, expect to see the pg_autoscaler module enabled by default

I think that is a +1 for not expanding the CRD, unless it becomes a big hassle for users.

**Comment by iExalt** [comment]
Closed for now. Didn't see that the pg_autoscaler is due to be enabled by default in newer versions of Ceph. That removes a lot of the need for specifying pg_num manually.

**Comment by noahdesu** [comment]
Cool. Certainly if that plan changes then this would become more useful.
