### ISSUE TITLE
ceph: mon's should use persistent volume storage

### ISSUE THREAD

**Issue by noahdesu** [rook/rook#3351]
Currently the storage that a monitor uses is based on the `dataDirHostPath` specified in the cluster CRD. This feature request will use the persistent volume abstraction to provide storage to monitors that are provisioned in the cloud (e.g. an ebs volume) or a local volume.

**note**: the `dataDirHostPath` should remain (perhaps renamed) to hold logging and crash data.

When backed by a network volume type this feature will free monitors from their strict host affinity. This is useful for migrating monitors efficiently during power down / upgrade / failure events as the block device can be moved to a new host without requiring a new monitor to be constructed.

Compared to PV storage for OSDs, (1) the requirements of monitor storage are modest (e.g. 10s of gigabytes), and (2) raw devices are unnecessary: monitors can consume a standard file system.

### Major changes:

* Transition to the use of StatefulSets rather than the current use of Deployment types. One StatefulSet per monitor will be the deployment strategy. By choosing a 1-1 mapping, managing the naming will be simplified, and StatefulSets themselves will also handle pvc creation, pod association, and management.

* The CRD will now contain a PVC template int he monitor spec

### Host Networking

Host network will not be supported for non-local PVCs (at least not yet) as this would require additional complexity in updating the IP address to which a monitor is associated when it is moved. When using non-host networking, the service object in k8s handles the IP migration transparently.

### Scheduling

This feature and the current implementation of monitor management in Rook relate to the feature request https://github.com/rook/rook/issues/2603 that adds support for scheduling to be failure-domain aware.

Baked into the design of the monitor orchestration is an assumption that (1) monitor pod scheduling/placement is performed manually and that (2) this allows the IP address of a monitor node to be node before pods are created.

Refactoring the design to loosen the requirement of knowing the IP address prior to pod creation would allow us to take full advantage of the k8s scheduler (in which case the IP address in host networking mode _would not be known_).

Since we are still supporting networking, prior to such a refactor we need to retain the explicit / manual scheduling of monitor pods, which https://github.com/rook/rook/issues/2603 covers.

**Comment by ron1** [comment]
Pls make this an optional feature in order to continue supporting older, non-cloud deployments without pvs.

**Comment by noahdesu** [comment]
@ron1 we plan to still support local devices using PVCs bound to devices in local storage classes. any issue there for your environment?

**Comment by ron1** [comment]
@noahdesu Local Persistent Volumes did not GA in Kubernetes until 1.14. I would hope Rook continues to support Kubernetes 1.11+ for a significant period of time. Is the Rook plan for supporting Kubernetes versions documented anywhere?

**Comment by whereisaaron** [comment]
@ron1 there is a handy tool that will create the local PV's for you:
    https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner

Good point about GA, although local PVs have been beta since 1.10 a year ago, so not too new-fangled 😄 
    https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/

1.15 is GA, so 1.11 is EOL already and no longer supported, by the [Kubernetes project at least](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew), some cloud providers are providing extended support for ~6 months past EOL. How long do you think projects like Rook should retain support for deprecated Kubernetes releases?

**Comment by noahdesu** [comment]
I believe that sig-storage-local-static-provisioner is going to be used for the OSD persistent volume work (https://github.com/rook/rook/blob/master/design/storage-class-device-set.md), and for monitors we don't actually need raw volumes--just a directory on the host will be fine.

**Comment by ron1** [comment]
@whereisaaron I would expect projects like Rook to support deprecated Kubernetes releases as long as the release is supported in at least one of the major Kubernetes distributions. I see Rook CI continues to test against Kubernetes 1.10+.

It seems like the community treats Kubernetes 1.11 in particular as an informal Long-Term Support version. On OperatorHub.io, I could only find one Operator that specifies a minKubeVersion > 1.11.0. So, I would hope Rook continues to support Kubernetes 1.11 for an extended period of time into the future.

**Comment by UnixBoy1** [comment]
> @noahdesu How difficult will it be to support both dataDirHostPath and PVCs for mon storage?

Yes this would be great to have both.

**Comment by whereisaaron** [comment]
> I see Rook CI currently tests against Kubernetes 1.10+

That's great @ron1. So if Rook tests local PV support with the automatic local provisioner on current CI, you'll know it will work for you too.

> I would expect projects like Rook to support deprecated Kubernetes releases as long as the release is supported in at least one of the major cloud or on-premise Kubernetes distributions.

Yep, that makes sense. But I personally don't see 1.11 support making it to Christmas 😄 

I had a quick look around at Cloud providers this morning. Azure has the longest tail, supporting four minor versions, everyone else I checked supports three minor versions. Cloud providers GA this support about 3-6 months behind K8s GA releases, effectively extending support back to 5-6 minor versions.
- K8s supports: 1.13, 1.14. 1.15
- IBM supports: 1.12, 1.13, 1.14
- AWS EKS supports: 1.11, 1.12, 1.13 (1.14 in Sep, 1.11 support ends in Sep)
- Google GKE supports: 1.11, 1.12, 1.13 (1.14 in preview, 1.11 support until ~Aug/Sep?)
- Azure AKS supports: 1.10, 1.11, 1.12, 1.13 (1.14 in preview, 1.11 support until ~Dec?) 
- DigitalOcean supports: 1.13, 1.14 (new kid)

**Comment by ron1** [comment]
@whereisaaron At least one relevant, non-cloud K8s provider plans to support their 1.11-based distribution until June 2022 according to https://access.redhat.com/support/policy/updates/openshift.

**Comment by whereisaaron** [comment]
Thanks @ron1, I have added Redhat in above. Nice to have a summary like this in one place.

That post explains that with OpenShift 4.x Redhat are also supporting only three minor versions at a time, same as other providers. It is true that the old OpenShift 3.x offered multi-year support for minor releases. Something they apparently regret doing. 😄
