### ISSUE TITLE
Issue with starting pod operator

### ISSUE THREAD

**Issue by giorgio076** [rook/rook#3356]
I'm not able to start pod operator.

Working on kubernetes version:

`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-docker-4", GitCommit:"3e62468863641262df4dfd2a66610d23d4d792dd", GitTreeState:"clean", BuildDate:"2019-01-15T17:33:26Z", GoVersion:"go1.10.6", Compiler:"gc", Platform:"linux/amd64"}`

Created commons and deployed operator:

`kubectl create -f common.yaml`

`kubectl create -f operator.yaml`

I've crated directories:  /var/lib/rook and /etc/ceph on all nodes with permissions `0777`

But I can't start operator.

Describe pod returns:

`Message:   failed to run operator. Error starting device discovery daemonset: Error starting discover daemonset: failed to create rook-discover daemon set. daemonsets.apps "rook-discover" is forbidden: user "system:serviceaccount:rook-ceph:rook-ceph-system" is not an admin and does not have permissions to use host bind mounts, privileged mode for resource` 

It seems there's a permission issue but I don't found any mistmatches on serviceaccounts, roles and rolesbinding

Any ideas?
Thanks in advance for cooperation

**Comment by galexrt** [comment]
This messages means that your cluster has PodSecurityPolicies in place to prevent the ServiceAccounts of Rook to run privileged and other points Pods in your cluster.

Try to setup PodSecurityPolicies as described in the documentation: https://rook.io/docs/rook/v1.0/psp.html#rbac-for-podsecuritypolicies

**Comment by giorgio076** [comment]
@galexrt  tanx a lot for suggestion.

I've created a PSP:

`$ kubectl get psp\
NAME         PRIV      CAPS      SELINUX    RUNASUSER   FSGROUP    SUPGROUP  READONLYROOTFS   VOLUMES
privileged   true                RunAsAny   RunAsAny    RunAsAny   RunAsAny   false       configMap,emptyDir,projected,secret,downwardAPI,hostPath,flexVolume
`

then I created roles:

`
\# privilegedPSP grants access to use the privileged PSP.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:rook-ceph
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
\-\-\-
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph-system
\-\-\-
\# Allow the rook-ceph-system serviceAccount to use the privileged PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rook-ceph-system-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:rook-ceph
subjects:
- kind: ServiceAccount
  name: rook-ceph-system
  namespace: rook-ceph
`

And add Role Binding to `common.yaml` :

\# Allow the default serviceAccount to use the privileged PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rook-default-psp
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:rook-ceph
subjects:
\- kind: ServiceAccount
  name: default
  namespace: rook-ceph
\-\-\-
\# Allow the rook-ceph-osd serviceAccount to use the privileged PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rook-ceph-osd-psp
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:rook-ceph
subjects:
\- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: rook-ceph
\-\-\-
\# Allow the rook-ceph-mgr serviceAccount to use the privileged PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rook-ceph-mgr-psp
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:rook-ceph
subjects:
\- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph

on manual [https://rook.io/docs/rook/v1.0/ceph-psp.html] there's a note:

> You will also require two more RoleBindings for each Rook Cluster you deploy: Create these two RoleBindings in the Namespace you plan to deploy your Rook Cluster into (default is “rook” namespace)

But I can't understand where "rook" (just rook not rook-ceph) namespace is referenced.

I still get error starting operator pod.

Thanks a lot for you support

**Comment by carlinhos700** [comment]
I have the same problem

**Comment by BlaineEXE** [comment]
For users running Docker enterprise, this may be the cuprit.
> For cluster security, only UCP admin users and service accounts that are granted the cluster-admin ClusterRole for all Kubernetes namespaces via a ClusterRoleBinding can deploy pods with privileged options.

From: https://docs.docker.com/ee/ucp/authorization/

Part of the error text from the description includes "...  is not an admin...", which I don't recall seeing in my PSP work, but this text shows up here in the Docker EE docs.

**Comment by giorgio076** [comment]
Thank you very much @BlaineEXE for tip!
Yes we've deployed Kubernetes cluster using UCP, so I've fixed all ClusterRoleBindings using cluster-admin as Cluster Role:
```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```
in `common.yaml`, I've also change Clusterolebindings name cause no more referencing to `psp`.
Thanks again for hint!

**Comment by francisfsjiang** [comment]
I met this issue too, on Rook release 1.3. I resolved this by adding option `--allow-privileged=true` to `kube-api` arguments.

I am using microk8s 1.18.2 on Ubuntu 2004. `--allow-privileged=true` can be added in `/var/snap/microk8s/current/args/kube-apiserver`.
