### ISSUE TITLE
RBD pvc not getting bound in rook-v1.0.0-154.g004f795 and rbd.csi.ceph.com version: 1.0.0

### ISSUE THREAD

**Issue by nehaberry** [rook/rook#3357]
**Description of problem:**

In the latest rook + csi setup (after PR -https://github.com/rook/rook/pull/3324 was merged) , rbd pvcs are not getting bound with below mentioned error message

$oc get pvc

rbd-pvc      Pending                                                                        csi-rbd
  18m

Events:
  Type       Reason                Age                From                                                                               Message
  ----       ------                ----               ----                                                                               -------
  Normal     Provisioning          26s (x6 over 57s)  rbd.csi.ceph.com_csi-rbdplugin-provisioner-0_6e128fc9-97f6-11e9-9393-0a580a80020a  External provisioner is provisioning volume for claim "test-csi/rbd-pvc"
  Warning    ProvisioningFailed    26s (x6 over 57s)  rbd.csi.ceph.com_csi-rbdplugin-provisioner-0_6e128fc9-97f6-11e9-9393-0a580a80020a  failed to provision volume with StorageClass "csi-rbd": rpc error: code = Internal desc = missing ID field 'userID' in secrets
  Normal     ExternalProvisioning  0s (x5 over 57s)   persistentvolume-controller                                                        waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator
Mounted By:  <none>

**Observation:**

1. The code seems to be looking for UserID In RBD secret. But rbd/secret.yaml doesn't have a separate field "userid" as cephfs/secret.yaml has.

**rbd_secret.yaml**

```
data:
  # Key value corresponds to a user name defined in Ceph cluster
  admin: BASE64-ENCODED-PASSWORD
  # Key value corresponds to a user name defined in Ceph cluster
  kubernetes: BASE64-ENCODED-PASSWORD
```

**cephfs_secret.yaml**

```
  userID: BASE64-ENCODED-USER
  userKey: BASE64-ENCODED-PASSWORD

  # Required if provisionVolume is set to true
  adminID: BASE64-ENCODED-USER
  adminKey: BASE64-ENCODED-PASSWORD

```

How reproducible:
=====================
100%

**Steps to Reproduce:**
1. Create a ceph based rook-csi cluster using the latest rook repo files (https://github.com/rook/rook) - master branch
2. Create a cephblockpool \
 $oc create -f pool.yaml (pool name =rbd)

3. Create a kubernetes user from the toolbox pod
  $ceph auth get-or-create-key client.kubernetes mon  "allow profile rbd" osd "profile rbd pool=rbd"

4. Create secret and storageclass. Yamls attached in next comment (from ceph/csi/examples/rbd)
  $oc create -f secret.yaml ; oc create -f storageclass.yaml

5. Create pvc
  $ oc create -f pvc.yaml

6. Check the status of pvc
  $oc get pvc; oc describe pvc $pvc-name

Actual results:
===================
The rbd pvc is not bound as the code looks for "clusterid" field in secret which is not present in yaml.

Expected results:
====================
PVC should get bound.

Version-Release number of selected component (if applicable):
=================================================

oc version

$ oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0-201905091432+4910781-dirty", GitCommit:"4910781", GitTreeState:"dirty", BuildDate:"2019-05-09T19:19:42Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+d4417a7", GitCommit:"d4417a7", GitTreeState:"clean", BuildDate:"2019-06-12T15:47:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.1.2     True        False         3h3m    Cluster version is 4.1.2

```
**Ceph and rook version**
-----------------------

sh-4.2# ceph version
ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)

sh-4.2# rook version
 rook: v1.0.0-154.g004f795


**CSI version**
-------------

$oc logs csi-rbdplugin-provisioner-0 -n openshift-storage -c csi-rbdplugin

I0626 09:40:26.830842       1 cephcsi.go:108] Starting driver type: rbd with name: rbd.csi.ceph.com
I0626 09:40:26.830922       1 rbd.go:104] Driver: rbd.csi.ceph.com version: 1.0.0

$ oc describe pod csi-rbdplugin-provisioner-0 -n openshift-storage|grep -i image
    Image:         quay.io/k8scsi/csi-provisioner:v1.2.0
    Image ID:      quay.io/k8scsi/csi-provisioner@sha256:0dffe9a8d39c4fdd49c5dd98ca5611a3f9726c012b082946f630e36988ba9f37
    Image:         quay.io/k8scsi/csi-attacher:v1.1.1
    Image ID:      quay.io/k8scsi/csi-attacher@sha256:e4db94969e1d463807162a1115192ed70d632a61fbeb3bdc97b40fe9ce78c831
    Image:         quay.io/k8scsi/csi-snapshotter:v1.1.0
    Image ID:      quay.io/k8scsi/csi-snapshotter@sha256:a49e0da1af6f2bf717e41ba1eee8b5e6a1cbd66a709dd92cc43fe475fe2589eb
    Image:         quay.io/cephcsi/cephcsi:canary
    Image ID:      quay.io/cephcsi/cephcsi@sha256:e832be9790bf12ab74c87217cce1dbd0a2416500e1d9a39af53b3fece414feac
```
**Rook image**
----------------------

$ oc describe pod rook-ceph-operator-5c6fd4b7db-rldcf -n openshift-storage|grep -i image
    Image:         rook/ceph:master
    Image ID:      docker.io/rook/ceph@sha256:4d0057e90c28a7bd8d3c3e9b13df40d0df1847567ef50a2a1e41dcea7ddb1d18
      ROOK_CSI_CEPH_IMAGE:                quay.io/cephcsi/cephcsi:canary
      ROOK_CSI_REGISTRAR_IMAGE:           quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
      ROOK_CSI_PROVISIONER_IMAGE:         quay.io/k8scsi/csi-provisioner:v1.2.0
      ROOK_CSI_SNAPSHOTTER_IMAGE:         quay.io/k8scsi/csi-snapshotter:v1.1.0
      ROOK_CSI_ATTACHER_IMAGE:            quay.io/k8scsi/csi-attacher:v1.1.1

**Comment by nehaberry** [comment]
Log snip
============

(new-ocs-ci) [nberry@localhost ocs-ci]$ oc logs csi-rbdplugin-provisioner-0 -n openshift-storage -c csi-provisioner -f --tail 10
I0626 11:17:16.536147       1 controller.go:442] CreateVolumeRequest {Name:pvc-e1ee1e2d-9803-11e9-9ad2-0a13693d844a CapacityRange:required_bytes:1073741824  VolumeCapabilities:[mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[adminid:admin clusterID:openshift-storage csi.storage.k8s.io/node-publish-secret-name:csi-rbd-secret csi.storage.k8s.io/node-publish-secret-namespace:default csi.storage.k8s.io/provisioner-secret-name:csi-rbd-secret csi.storage.k8s.io/provisioner-secret-namespace:default imageFeatures:layering imageFormat:2 pool:rbd userid:kubernetes] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0626 11:17:16.536377       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test-csi", Name:"rbd-pvc", UID:"e1ee1e2d-9803-11e9-9ad2-0a13693d844a", APIVersion:"v1", ResourceVersion:"54405", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "test-csi/rbd-pvc"
I0626 11:17:16.542395       1 connection.go:180] GRPC call: /csi.v1.Controller/CreateVolume
I0626 11:17:16.542416       1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-e1ee1e2d-9803-11e9-9ad2-0a13693d844a","parameters":{"adminid":"admin","clusterID":"openshift-storage","imageFeatures":"layering","imageFormat":"2","pool":"rbd","userid":"kubernetes"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
I0626 11:17:16.552610       1 connection.go:183] GRPC response: {}
I0626 11:17:16.553304       1 connection.go:184] GRPC error: rpc error: code = Internal desc = missing ID field 'userID' in secrets
I0626 11:17:16.553355       1 controller.go:979] Final error received, removing PVC e1ee1e2d-9803-11e9-9ad2-0a13693d844a from claims in progress
W0626 11:17:16.553366       1 controller.go:886] Retrying syncing claim "e1ee1e2d-9803-11e9-9ad2-0a13693d844a", failure 5
E0626 11:17:16.553389       1 controller.go:908] error syncing claim "e1ee1e2d-9803-11e9-9ad2-0a13693d844a": failed to provision volume with StorageClass "csi-rbd": rpc error: code = Internal desc = missing ID field 'userID' in secrets
I0626 11:17:16.554135       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test-csi", Name:"rbd-pvc", UID:"e1ee1e2d-9803-11e9-9ad2-0a13693d844a", APIVersion:"v1", ResourceVersion:"54405", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd": rpc error: code = Internal desc = missing ID field 'userID' in secrets
I0626 11:17:48.553800       1 controller.go:1196] provision "test-csi/rbd-pvc" class "csi-rbd": started
I0626 11:17:48.558848       1 controller.go:442] CreateVolumeRequest {Name:pvc-e1ee1e2d-9803-11e9-9ad2-0a13693d844a CapacityRange:required_bytes:1073741824  VolumeCapabilities:[mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[adminid:admin clusterID:openshift-storage csi.storage.k8s.io/node-publish-secret-name:csi-rbd-secret csi.storage.k8s.io/node-publish-secret-namespace:default csi.storage.k8s.io/provisioner-secret-name:csi-rbd-secret csi.storage.k8s.io/provisioner-secret-namespace:default imageFeatures:layering imageFormat:2 pool:rbd userid:kubernetes] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0626 11:17:48.559084       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test-csi", Name:"rbd-pvc", UID:"e1ee1e2d-9803-11e9-9ad2-0a13693d844a", APIVersion:"v1", ResourceVersion:"54405", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "test-csi/rbd-pvc"

**Comment by nehaberry** [comment]
Additional info:
=====================
Adding all the yamls

--------------------------------------------------------------

$$ cat secret.yaml 
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
data:
  # Key value corresponds to a user name defined in Ceph cluster
  admin: QVFCdVBSTmRxSFJTTmhBQVNGMmxlVkJkVGV3T3NBWFJHZnFxVXc9PQ==
  # Key value corresponds to a user name defined in Ceph cluster
  kubernetes: QVFDM1FCTmR4NzRmR0JBQVI1d1NVbkg3SjAvWFYyZUxLN1U4SWc9PQ==
  # if monValueFromSecret is set to "monitors", uncomment the
  # following and set the mon there
  #monitors: BASE64-ENCODED-Comma-Delimited-Mons


--------------------------------------------------------------

--------------------------------------------------------------

$$ cat storageclass.yaml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd
provisioner: rbd.csi.ceph.com
parameters:
    # Specify a string that identifies your cluster. Ceph CSI supports any
    # unique string. When Ceph CSI is deployed by Rook use the Rook namespace,
    # for example "rook-ceph".
    clusterID: openshift-storage 

    # Ceph pool into which the RBD image shall be created
    pool: rbd

    # RBD image format. Defaults to "2".
    imageFormat: "2"

    # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
    imageFeatures: layering

    # The secrets have to contain Ceph admin credentials.
    csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
    csi.storage.k8s.io/provisioner-secret-namespace: default
    csi.storage.k8s.io/node-publish-secret-name: csi-rbd-secret
    csi.storage.k8s.io/node-publish-secret-namespace: default

    # Ceph users for operating RBD
    adminid: admin
    userid: kubernetes
    # uncomment the following to use rbd-nbd as mounter on supported nodes
    #mounter: rbd-nbd
reclaimPolicy: Delete

--------------------------------------------------------------

--------------------------------------------------------------


$$ cat pvc.yaml 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd


--------------------------------------------------------------

Created storageclass
=================

$ oc get sc csi-rbd -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2019-06-26T11:16:33Z"
  name: csi-rbd
  resourceVersion: "54342"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/csi-rbd
  uid: da9794b5-9803-11e9-9e5b-069ed599aff0
parameters:
  adminid: admin
  clusterID: openshift-storage
  csi.storage.k8s.io/node-publish-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-publish-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  imageFeatures: layering
  imageFormat: "2"
  pool: rbd
  userid: kubernetes
provisioner: rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate


Created secret. UserID is not present in the secret
=====================================================

$ oc get secret/csi-rbd-secret -n default -o yaml
apiVersion: v1
data:
  admin: QVFCdVBSTmRxSFJTTmhBQVNGMmxlVkJkVGV3T3NBWFJHZnFxVXc9PQ==
  kubernetes: QVFDM1FCTmR4NzRmR0JBQVI1d1NVbkg3SjAvWFYyZUxLN1U4SWc9PQ==
kind: Secret
metadata:
  creationTimestamp: "2019-06-26T11:15:25Z"
  name: csi-rbd-secret
  namespace: default
  resourceVersion: "53982"
  selfLink: /api/v1/namespaces/default/secrets/csi-rbd-secret
  uid: b27c6d34-9803-11e9-9e5b-069ed599aff0
type: Opaque


But the secret of cephfs has the filed userid. Maybe this filed is being expected in rbd/secret as well.


$ oc get secret/csi-cephfs-secret -n default -o yaml
apiVersion: v1
data:
  adminID: YWRtaW4=
  adminKey: QVFCdVBSTmRxSFJTTmhBQVNGMmxlVkJkVGV3T3NBWFJHZnFxVXc9PQ==
  userID: a3ViZXJuZXRlcw==
  userKey: QVFDM1FCTmR4NzRmR0JBQVI1d1NVbkg3SjAvWFYyZUxLN1U4SWc9PQ==
kind: Secret
metadata:
  creationTimestamp: "2019-06-26T11:08:36Z"
  name: csi-cephfs-secret
  namespace: default
  resourceVersion: "51883"
  selfLink: /api/v1/namespaces/default/secrets/csi-cephfs-secret
  uid: be70d521-9802-11e9-9e5b-069ed599aff0
type: Opaque

**Comment by Madhu-1** [comment]
@nehaberry @ShyamsundarR will be  sending PR to fix this issue 

JFYI its  already discussed here https://rook-io.slack.com/archives/CG3HUV94J/p1561548666081000

**Comment by nehaberry** [comment]
Thanks Madhu for the heads up :)
