### ISSUE TITLE
The "host" signature in "ceph osd status" remains unchanged on moving an OSD disk from failed node to a new node

### ISSUE THREAD

**Issue by nehaberry** [rook/rook#3363]
**Description of problem:**

Rook csi ceph setup = latest rook + csi setup (after PR -https://github.com/rook/rook/pull/3324 was merged) 

When a node with OSD is removed permanently from OCP cluster, and the corresponding OSD disk is added to a new OCP node( through AWS console), the OSD is indeed recovered but the "host" name under "ceph osd status" still lists the hostname of the failed node instead of the new node.

**Details of steps performed added in the next comment.**

**Snip of output which shows inconsistency between host name from oc get pods and ceph osd status**

**sh-4.2$ ceph osd status**
```
+----+--------------------------------------------+-------+-------+--------+---------+--------+---------+-----------+
| id |                    host                    |  used | avail | wr ops | wr data | rd ops | rd data |   state   |
+----+--------------------------------------------+-------+-------+--------+---------+--------+---------+-----------+
| 0  | ip-10-0-149-134.us-east-2.compute.internal | 1025M | 97.9G |    0   |     0   |    1   |    16   | exists,up |
| 1  | ip-10-0-129-70.us-east-2.compute.internal  | 1025M | 97.9G |    0   |     0   |    0   |     0   | exists,up |
| 2  | ip-10-0-161-198.us-east-2.compute.internal | 1025M | 97.9G |    0   |     0   |    1   |    90   | exists,up |
+----+--------------------------------------------+-------+-------+--------+---------+--------+---------+-----------+

```

**$oc get pods -n openshift-storage -o wide|grep osd-**
```
rook-ceph-osd-0-cd8c5475d-pmzw5                1/1     Running     0          19h   10.129.2.17    ip-10-0-149-134.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-1-dd6754887-gssh2                1/1     Running     0          14h   10.130.2.9     ip-10-0-132-79.us-east-2.compute.internal    <none>           <none>
rook-ceph-osd-2-64c99cc4c6-hdmph               1/1     Running     0          19h   10.128.2.13    ip-10-0-161-198.us-east-2.compute.internal   <none>           <none>

```

**How reproducible:**
-------------------------

100%

**Steps to Reproduce:**
--------------------------

1. Create a ceph based rook-csi cluster using the latest rook repo files (https://github.com/rook/rook) - master branch

2. Remove one of the worker  machine which hosts an OSD
  $ date; time oc delete machine/nberry-jun26-1-mwzjg-worker-us-east-2a-4ppjb -n openshift-machine-api; date

3. After some time, confirm that a new OCP node is spun up and a new machine is added.

4. Once ceph marks the failed OSD as OUT, add the "Available" disk from failed node to the new node in AWS console
 
5. Check the following 
$oc get pods -o wide -n <openshift-storage>  ----> for osd-x again coming up without any issue

Within toolbox:

$ceph status

$ceph osd status

**Actual results:**

When a failed OSD is recovered by re-adding the disk to a new node, its "host" signature still shows the old hostname instead of the new. This can be misleading.

**Expected results:**

Ceph OSD status should get updated with new host name for the re-added OSD.

**Version-Release number of selected component (if applicable):**

```
$ oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0-201905091432+4910781-dirty", GitCommit:"4910781", GitTreeState:"dirty", BuildDate:"2019-05-09T19:19:42Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+d4417a7", GitCommit:"d4417a7", GitTreeState:"clean", BuildDate:"2019-06-12T15:47:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.1.2     True        False         21h     Cluster version is 4.1.2


Ceph and rook version
-----------------------

sh-4.2$ ceph version
ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)

sh-4.2$ rook version
 rook: v1.0.0-154.g004f795


CSI version
-------------

$oc logs csi-rbdplugin-provisioner-0 -n openshift-storage -c csi-rbdplugin

I0626 09:40:26.830842       1 cephcsi.go:108] Starting driver type: rbd with name: rbd.csi.ceph.com
I0626 09:40:26.830922       1 rbd.go:104] Driver: rbd.csi.ceph.com version: 1.0.0

$ oc describe pod csi-rbdplugin-provisioner-0 -n openshift-storage|grep -i image
    Image:         quay.io/k8scsi/csi-provisioner:v1.2.0
    Image ID:      quay.io/k8scsi/csi-provisioner@sha256:0dffe9a8d39c4fdd49c5dd98ca5611a3f9726c012b082946f630e36988ba9f37
    Image:         quay.io/k8scsi/csi-attacher:v1.1.1
    Image ID:      quay.io/k8scsi/csi-attacher@sha256:e4db94969e1d463807162a1115192ed70d632a61fbeb3bdc97b40fe9ce78c831
    Image:         quay.io/k8scsi/csi-snapshotter:v1.1.0
    Image ID:      quay.io/k8scsi/csi-snapshotter@sha256:a49e0da1af6f2bf717e41ba1eee8b5e6a1cbd66a709dd92cc43fe475fe2589eb
    Image:         quay.io/cephcsi/cephcsi:canary
    Image ID:      quay.io/cephcsi/cephcsi@sha256:e832be9790bf12ab74c87217cce1dbd0a2416500e1d9a39af53b3fece414feac

Rook image
----------------------

$ oc describe pod rook-ceph-operator-5c6fd4b7db-rldcf -n openshift-storage|grep -i image
    Image:         rook/ceph:master
    Image ID:      docker.io/rook/ceph@sha256:4d0057e90c28a7bd8d3c3e9b13df40d0df1847567ef50a2a1e41dcea7ddb1d18
      ROOK_CSI_CEPH_IMAGE:                quay.io/cephcsi/cephcsi:canary
      ROOK_CSI_REGISTRAR_IMAGE:           quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
      ROOK_CSI_PROVISIONER_IMAGE:         quay.io/k8scsi/csi-provisioner:v1.2.0
      ROOK_CSI_SNAPSHOTTER_IMAGE:         quay.io/k8scsi/csi-snapshotter:v1.1.0
      ROOK_CSI_ATTACHER_IMAGE:            quay.io/k8scsi/csi-attacher:v1.1.1
```

**Comment by nehaberry** [comment]
Some additional outputs

==============================

1. Initially in a a 3 master + 3 worker(ceph nodes) setup, there were 1 OSD in each worker node. 

rook-ceph-osd-0-cd8c5475d-pmzw5                1/1     Running     0          3h26m   10.129.2.17    ip-10-0-149-134.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-1-6d4f65667b-xw7w7               1/1     Running     0          3h26m   10.131.0.15    ip-10-0-129-70.us-east-2.compute.internal    <none>           <none>
rook-ceph-osd-2-64c99cc4c6-hdmph               1/1     Running     0          3h26m   10.128.2.13    ip-10-0-161-198.us-east-2.compute.internal   <none>           <none>


2. Deleted a worker machine(ip-10-0-129-70.us-east-2.compute.internal). The corresponding MON and OSD pods went into Pending state. But machineset added a new node to the cluster automatically and after some time, MON pod came up on the new node (expected) . 

3. The OSD from failed node was automatically removed from pod list(oc get pods) after the timeout specified as per rook-operator. Even ceph osd status only listed 2 OSDs and their hosts 

from logs
------------
2019-06-26 13:27:54.522051 I | op-osd: osd.1 is marked 'DOWN'

Remaining OSDs
-----------------------
rook-ceph-osd-0-cd8c5475d-pmzw5                1/1     Running     0          3h47m   10.129.2.17    ip-10-0-149-134.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-2-64c99cc4c6-hdmph               1/1     Running     0          3h47m   10.128.2.13    ip-10-0-161-198.us-east-2.compute.internal   <none>           <none>


sh-4.2# ceph osd status
+----+--------------------------------------------+-------+-------+--------+---------+--------+---------+----------------+
| id |                    host                    |  used | avail | wr ops | wr data | rd ops | rd data |     state      |
+----+--------------------------------------------+-------+-------+--------+---------+--------+---------+----------------+
| 0  | ip-10-0-149-134.us-east-2.compute.internal | 1025M | 97.9G |    0   |     0   |    1   |    16   |   exists,up    |
| 1  |                                            |    0  |    0  |    0   |     0   |    0   |     0   | autoout,exists |
| 2  | ip-10-0-161-198.us-east-2.compute.internal | 1025M | 97.9G |    0   |     0   |    1   |    90   |   exists,up    |
+----+--------------------------------------------+-------+-------+--------+---------+--------+---------+----------------+


4. On the new OCP node, re-added the 100GB OSD disk from AWS console as /dev/sdl. 

5. After some time, the disk was recognised by operator on its own (didnt have to wipefs the disk for OSD to come up) and the OSD pod came up on the new node


rook-ceph-osd-0-cd8c5475d-pmzw5                1/1     Running     0          19h   10.129.2.17    ip-10-0-149-134.us-east-2.compute.internal   <none>           <none>
rook-ceph-osd-1-dd6754887-gssh2                1/1     Running     0          14h   10.130.2.9     ip-10-0-132-79.us-east-2.compute.internal    <none>           <none>
rook-ceph-osd-2-64c99cc4c6-hdmph               1/1     Running     0          19h   10.128.2.13    ip-10-0-161-198.us-east-2.compute.internal   <none>           <none>

6. Checked the ceph osd status and it still lists the old host (ip-10-0-129-70.us-east-2) instead of the new host on which the disk is actually attached (i.e. ip-10-0-132-79.us-east-2)


sh-4.2# ceph osd status
+----+--------------------------------------------+-------+-------+--------+---------+--------+---------+-----------+
| id |                    host                    |  used | avail | wr ops | wr data | rd ops | rd data |   state   |
+----+--------------------------------------------+-------+-------+--------+---------+--------+---------+-----------+
| 0  | ip-10-0-149-134.us-east-2.compute.internal | 1025M | 97.9G |    0   |     0   |    1   |    16   | exists,up |
| 1  | ip-10-0-129-70.us-east-2.compute.internal  | 1025M | 97.9G |    0   |     0   |    0   |     0   | exists,up |
| 2  | ip-10-0-161-198.us-east-2.compute.internal | 1025M | 97.9G |    0   |     0   |    1   |    90   | exists,up |
+----+--------------------------------------------+-------+-------+--------+---------+--------+---------+-----------+
sh-4.2# ceph osd status


7. osd-1 config from node

sh-4.4# cat openshift-storage.config 
[global]
fsid                      = df477043-e540-4c35-baf4-92bde11e7ad0
run dir                   = /var/lib/rook/osd1
mon initial members       = c d b
mon host                  = v1:172.30.210.53:6789,v1:172.30.6.158:6789,v1:172.30.16.10:6789
public addr               = 10.130.2.9
cluster addr              = 10.130.2.9
mon keyvaluedb            = rocksdb
mon_allow_pool_delete     = true
mon_max_pg_per_osd        = 1000
debug default             = 0
debug rados               = 0
debug mon                 = 0
debug osd                 = 0
debug bluestore           = 0
debug filestore           = 0
debug journal             = 0
debug leveldb             = 0
filestore_omap_backend    = rocksdb
osd pg bits               = 11
osd pgp bits              = 11
osd pool default size     = 1
osd pool default min size = 1
osd pool default pg num   = 100
osd pool default pgp num  = 100
osd objectstore           = filestore
crush location            = root=default host=ip-10-0-132-79
rbd_default_features      = 3
fatal signal handlers     = false

[osd.1]
keyring              = /var/lib/ceph/osd/ceph-1/keyring
bluestore block path = /var/lib/ceph/osd/ceph-1/block

**Comment by nehaberry** [comment]
[bz-1724428.zip](https://github.com/rook/rook/files/3333168/bz-1724428.zip)

**Comment by noahdesu** [comment]
@nehaberry  It looks like this should be working correctly with `osd crush update on start` and the correct `crush location` specified in the ceph.conf. Would it be possible to get a log from the OSD with debug level turned up? This should dump out the command that the OSD is issuing to update its own location.

**Comment by noahdesu** [comment]
the only thing I see in rook that might be doing this is

```
pkg/daemon/ceph/osd/device.go:	args := []string{"osd", "crush", "create-or-move", strconv.Itoa(osdID), fmt.Sprintf("%.4f", weight)}
```

but this should only occur for new osds and i don't see this showing up in the logs.

**Comment by mykaul** [comment]
@noahdesu - any updates?

**Comment by noahdesu** [comment]
@mykaul seems to be an upstream ceph issue. i've updated https://bugzilla.redhat.com/show_bug.cgi?id=1724428 with details.

**Comment by galexrt** [comment]
@noahdesu Do you got a public bug for that as well? :wink:

> You are not authorized to access bug #1724428. To see this bug, you must first log in to an account with the appropriate permissions.

**Comment by leseb** [comment]
@galexrt http://tracker.ceph.com/issues/40871

**Comment by mykaul** [comment]
@galexrt - please see if you can access the BZ - it should not be private to Red Hat, as far a I can see.

**Comment by noahdesu** [comment]
@galexrt sorry about that. thought it was public :)
