### ISSUE TITLE
rook ceph mon cannot start

### ISSUE THREAD

**Issue by felixx** [rook/rook#3371]
OS: centos 7.6
[root@host1 ceph]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
k8s: v1.15.0
[root@host1 ceph]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

[root@host1 ceph]# kubectl get pod -n rook-ceph -o wide
NAME                                  READY   STATUS                  RESTARTS   AGE   IP             NODE    NOMINATED NODE   READINESS GATES
rook-ceph-agent-qmhmr                 1/1     Running                 0          84m   172.30.10.83   host3   <none>           <none>
rook-ceph-agent-s98qc                 1/1     Running                 0          84m   172.30.10.84   host4   <none>           <none>
rook-ceph-agent-trzlf                 1/1     Running                 0          84m   172.30.10.82   host2   <none>           <none>
**rook-ceph-mon-a-77bb8d68fb-rqqn6      0/1     Init:CrashLoopBackOff**   1          14s   10.44.0.3      host2   <none>           <none>
rook-ceph-operator-548b56f995-7mrzf   1/1     Running                 0          84m   10.42.0.1      host4   <none>           <none>
rook-discover-n4skq                   1/1     Running                 0          84m   10.36.0.1      host3   <none>           <none>
rook-discover-tbkvp                   1/1     Running                 0          84m   10.42.0.2      host4   <none>           <none>
rook-discover-xlj6b                   1/1     Running                 0          84m   10.44.0.1      host2   <none>           <none>

[root@host1 ceph]# kubectl describe pod rook-ceph-mon-a-77bb8d68fb-rqqn6 -n rook-ceph
Name:           rook-ceph-mon-a-77bb8d68fb-rqqn6
Namespace:      rook-ceph
Priority:       0
Node:           host2/172.30.10.82
Start Time:     Sat, 29 Jun 2019 04:22:01 +0800
Labels:         app=rook-ceph-mon
                ceph_daemon_id=a
                mon=a
                mon_cluster=rook-ceph
                pod-template-hash=77bb8d68fb
                rook_cluster=rook-ceph
Annotations:    <none>
Status:         Pending
IP:             10.44.0.3
Controlled By:  ReplicaSet/rook-ceph-mon-a-77bb8d68fb
Init Containers:
  init-mon-fs:
    Container ID:  docker://76f6daeb8e17d56590dfd5465902511c2d4418f879847974c5cff398a703dc40
    Image:         ceph/ceph:v14.2.1-20190430
    Image ID:      docker-pullable://docker.io/ceph/ceph@sha256:0d870d99a67ebc9a38c4855172f16e7f27a1b5d67945f056a88dce3bb99b2a29
    Port:          <none>
    Host Port:     <none>
    Command:
      ceph-mon
    Args:
      --fsid=0041d6b0-3322-42bb-8fc8-5aa67c6d2e28
      --keyring=/etc/ceph/keyring-store/keyring
      --log-to-stderr=true
      --err-to-stderr=true
      --mon-cluster-log-to-stderr=true
      --log-stderr-prefix=debug 
      --default-log-to-file=false
      --default-mon-cluster-log-to-file=false
      --mon-host=$(ROOK_CEPH_MON_HOST)
      --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
      --id=a
      --public-addr=10.109.57.240
      --mkfs
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 29 Jun 2019 04:22:16 +0800
      Finished:     Sat, 29 Jun 2019 04:22:16 +0800
    Ready:          False
    Restart Count:  2
    Environment:
      CONTAINER_IMAGE:                ceph/ceph:v14.2.1-20190430
      POD_NAME:                       rook-ceph-mon-a-77bb8d68fb-rqqn6 (v1:metadata.name)
      POD_NAMESPACE:                  rook-ceph (v1:metadata.namespace)
      NODE_NAME:                       (v1:spec.nodeName)
      POD_MEMORY_LIMIT:               node allocatable (limits.memory)
      POD_MEMORY_REQUEST:             0 (requests.memory)
      POD_CPU_LIMIT:                  node allocatable (limits.cpu)
      POD_CPU_REQUEST:                0 (requests.cpu)
      ROOK_CEPH_MON_HOST:             <set to the key 'mon_host' in secret 'rook-ceph-config'>             Optional: false
      ROOK_CEPH_MON_INITIAL_MEMBERS:  <set to the key 'mon_initial_members' in secret 'rook-ceph-config'>  Optional: false
    Mounts:
      /etc/ceph from rook-ceph-config (ro)
      /etc/ceph/keyring-store/ from rook-ceph-mons-keyring (ro)
      /var/lib/ceph/mon/ceph-a from ceph-daemon-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gftlx (ro)
Containers:
  mon:
    Container ID:  
    Image:         ceph/ceph:v14.2.1-20190430
    Image ID:      
    Port:          6789/TCP
    Host Port:     0/TCP
    Command:
      ceph-mon
    Args:
      --fsid=0041d6b0-3322-42bb-8fc8-5aa67c6d2e28
      --keyring=/etc/ceph/keyring-store/keyring
      --log-to-stderr=true
      --err-to-stderr=true
      --mon-cluster-log-to-stderr=true
      --log-stderr-prefix=debug 
      --default-log-to-file=false
      --default-mon-cluster-log-to-file=false
      --mon-host=$(ROOK_CEPH_MON_HOST)
      --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
      --id=a
      --foreground
      --public-addr=10.109.57.240
      --public-bind-addr=$(ROOK_POD_IP)
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      CONTAINER_IMAGE:                ceph/ceph:v14.2.1-20190430
      POD_NAME:                       rook-ceph-mon-a-77bb8d68fb-rqqn6 (v1:metadata.name)
      POD_NAMESPACE:                  rook-ceph (v1:metadata.namespace)
      NODE_NAME:                       (v1:spec.nodeName)
      POD_MEMORY_LIMIT:               node allocatable (limits.memory)
      POD_MEMORY_REQUEST:             0 (requests.memory)
      POD_CPU_LIMIT:                  node allocatable (limits.cpu)
      POD_CPU_REQUEST:                0 (requests.cpu)
      ROOK_CEPH_MON_HOST:             <set to the key 'mon_host' in secret 'rook-ceph-config'>             Optional: false
      ROOK_CEPH_MON_INITIAL_MEMBERS:  <set to the key 'mon_initial_members' in secret 'rook-ceph-config'>  Optional: false
      ROOK_POD_IP:                     (v1:status.podIP)
    Mounts:
      /etc/ceph from rook-ceph-config (ro)
      /etc/ceph/keyring-store/ from rook-ceph-mons-keyring (ro)
      /var/lib/ceph/mon/ceph-a from ceph-daemon-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gftlx (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  rook-ceph-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rook-ceph-config
    Optional:  false
  rook-ceph-mons-keyring:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-mons-keyring
    Optional:    false
  rook-ceph-log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/log
    HostPathType:  
  ceph-daemon-data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/mon-a/data
    HostPathType:  
  default-token-gftlx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gftlx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/hostname=host2
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                            From               Message
  ----     ------     ----                           ----               -------
  Normal   Scheduled  31s                            default-scheduler  Successfully assigned rook-ceph/rook-ceph-mon-a-77bb8d68fb-rqqn6 to host2
  Normal   Pulled     <invalid> (x3 over <invalid>)  kubelet, host2     Container image "ceph/ceph:v14.2.1-20190430" already present on machine
  Normal   Created    <invalid> (x3 over <invalid>)  kubelet, host2     Created container init-mon-fs
  Normal   Started    <invalid> (x3 over <invalid>)  kubelet, host2     Started container init-mon-fs
  Warning  BackOff    <invalid> (x4 over <invalid>)  kubelet, host2     Back-off restarting failed container

**Comment by leseb** [comment]
Please share the pod logs and format when you paste content. Thanks.

**Comment by felixx** [comment]
when I use `kubectl logs`, it just tell me pod not found
[root@host1 ceph]# kubectl logs -p rook-ceph-mon-a-77bb8d68fb-rqqn6 
Error from server (NotFound): pods "rook-ceph-mon-a-77bb8d68fb-rqqn6" not found
are there any other ways to collect the pod logs? thanks.

**Comment by leseb** [comment]
You forgot to specify the namespace, add `-n rook-ceph`.

**Comment by felixx** [comment]
thanks, when add namespace
[root@host1 ceph]# kubectl logs -p rook-ceph-mon-a-77bb8d68fb-rqqn6  -n rook-ceph
Error from server (BadRequest): previous terminated container "mon" in pod "rook-ceph-mon-a-77bb8d68fb-rqqn6" not found
[root@host1 ceph]# kubectl logs rook-ceph-mon-a-77bb8d68fb-rqqn6  -n rook-ceph
Error from server (BadRequest): container "mon" in pod "rook-ceph-mon-a-77bb8d68fb-rqqn6" is waiting to start: PodInitializing

**Comment by felixx** [comment]
after one hour, the mon started in other worker, but those workers have the same OS & k8s & docker
[root@host1 k8s]# kubectl get pod -o wide -n rook-ceph
NAME                                  READY   STATUS                  RESTARTS   AGE    IP             NODE    NOMINATED NODE   READINESS GATES
rook-ceph-agent-qmhmr                 1/1     Running                 0          146m   172.30.10.83   host3   <none>           <none>
rook-ceph-agent-s98qc                 1/1     Running                 0          146m   172.30.10.84   host4   <none>           <none>
rook-ceph-agent-trzlf                 1/1     Running                 0          146m   172.30.10.82   host2   <none>           <none>
rook-ceph-mon-a-77bb8d68fb-rqqn6      0/1     Init:CrashLoopBackOff   17         62m    10.44.0.3      host2   <none>           <none>
rook-ceph-mon-d-649db79d7-z58ck       1/1     Running                 0          7s     10.36.0.2      host3   <none>           <none>
rook-ceph-mon-f-6669588f59-lw2tc      1/1     Running                 0          7s     10.36.0.3      host3   <none>           <none>
rook-ceph-operator-548b56f995-7mrzf   1/1     Running                 0          147m   10.42.0.1      host4   <none>           <none>
rook-discover-n4skq                   1/1     Running                 0          146m   10.36.0.1      host3   <none>           <none>
rook-discover-tbkvp                   1/1     Running                 0          146m   10.42.0.2      host4   <none>           <none>
rook-discover-xlj6b                   1/1     Running                 0          146m   10.44.0.1      host2   <none>           <none>

[root@host1 k8s]# kubectl describe pod rook-ceph-mon-d-649db79d7-z58ck  -n rook-ceph
Name:           rook-ceph-mon-d-649db79d7-z58ck
Namespace:      rook-ceph
Priority:       0
Node:           host3/172.30.10.83
Start Time:     Fri, 28 Jun 2019 16:13:09 +0800
Labels:         app=rook-ceph-mon
                ceph_daemon_id=d
                mon=d
                mon_cluster=rook-ceph
                pod-template-hash=649db79d7
                rook_cluster=rook-ceph
Annotations:    <none>
Status:         Running
IP:             10.36.0.2
Controlled By:  ReplicaSet/rook-ceph-mon-d-649db79d7
Init Containers:
  init-mon-fs:
    Container ID:  docker://22d65cc659b8ba6b6a370856b824c70edefd02d10b79e93d3e44d55cd90d756c
    Image:         ceph/ceph:v14.2.1-20190430
    Image ID:      docker-pullable://docker.io/ceph/ceph@sha256:0d870d99a67ebc9a38c4855172f16e7f27a1b5d67945f056a88dce3bb99b2a29
    Port:          <none>
    Host Port:     <none>
    Command:
      ceph-mon
    Args:
      --fsid=0041d6b0-3322-42bb-8fc8-5aa67c6d2e28
      --keyring=/etc/ceph/keyring-store/keyring
      --log-to-stderr=true
      --err-to-stderr=true
      --mon-cluster-log-to-stderr=true
      --log-stderr-prefix=debug 
      --default-log-to-file=false
      --default-mon-cluster-log-to-file=false
      --mon-host=$(ROOK_CEPH_MON_HOST)
      --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
      --id=d
      --public-addr=10.104.154.7
      --mkfs
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 28 Jun 2019 16:13:10 +0800
      Finished:     Fri, 28 Jun 2019 16:13:11 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      CONTAINER_IMAGE:                ceph/ceph:v14.2.1-20190430
      POD_NAME:                       rook-ceph-mon-d-649db79d7-z58ck (v1:metadata.name)
      POD_NAMESPACE:                  rook-ceph (v1:metadata.namespace)
      NODE_NAME:                       (v1:spec.nodeName)
      POD_MEMORY_LIMIT:               node allocatable (limits.memory)
      POD_MEMORY_REQUEST:             0 (requests.memory)
      POD_CPU_LIMIT:                  node allocatable (limits.cpu)
      POD_CPU_REQUEST:                0 (requests.cpu)
      ROOK_CEPH_MON_HOST:             <set to the key 'mon_host' in secret 'rook-ceph-config'>             Optional: false
      ROOK_CEPH_MON_INITIAL_MEMBERS:  <set to the key 'mon_initial_members' in secret 'rook-ceph-config'>  Optional: false
    Mounts:
      /etc/ceph from rook-ceph-config (ro)
      /etc/ceph/keyring-store/ from rook-ceph-mons-keyring (ro)
      /var/lib/ceph/mon/ceph-d from ceph-daemon-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gftlx (ro)
Containers:
  mon:
    Container ID:  docker://f85ac52ca4e0fd19c022700a186daf1a65e6b43dfa854d0334e7484243520b31
    Image:         ceph/ceph:v14.2.1-20190430
    Image ID:      docker-pullable://docker.io/ceph/ceph@sha256:0d870d99a67ebc9a38c4855172f16e7f27a1b5d67945f056a88dce3bb99b2a29
    Port:          6789/TCP
    Host Port:     0/TCP
    Command:
      ceph-mon
    Args:
      --fsid=0041d6b0-3322-42bb-8fc8-5aa67c6d2e28
      --keyring=/etc/ceph/keyring-store/keyring
      --log-to-stderr=true
      --err-to-stderr=true
      --mon-cluster-log-to-stderr=true
      --log-stderr-prefix=debug 
      --default-log-to-file=false
      --default-mon-cluster-log-to-file=false
      --mon-host=$(ROOK_CEPH_MON_HOST)
      --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
      --id=d
      --foreground
      --public-addr=10.104.154.7
      --public-bind-addr=$(ROOK_POD_IP)
    State:          Running
      Started:      Fri, 28 Jun 2019 16:13:11 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      CONTAINER_IMAGE:                ceph/ceph:v14.2.1-20190430
      POD_NAME:                       rook-ceph-mon-d-649db79d7-z58ck (v1:metadata.name)
      POD_NAMESPACE:                  rook-ceph (v1:metadata.namespace)
      NODE_NAME:                       (v1:spec.nodeName)
      POD_MEMORY_LIMIT:               node allocatable (limits.memory)
      POD_MEMORY_REQUEST:             0 (requests.memory)
      POD_CPU_LIMIT:                  node allocatable (limits.cpu)
      POD_CPU_REQUEST:                0 (requests.cpu)
      ROOK_CEPH_MON_HOST:             <set to the key 'mon_host' in secret 'rook-ceph-config'>             Optional: false
      ROOK_CEPH_MON_INITIAL_MEMBERS:  <set to the key 'mon_initial_members' in secret 'rook-ceph-config'>  Optional: false
      ROOK_POD_IP:                     (v1:status.podIP)
    Mounts:
      /etc/ceph from rook-ceph-config (ro)
      /etc/ceph/keyring-store/ from rook-ceph-mons-keyring (ro)
      /var/lib/ceph/mon/ceph-d from ceph-daemon-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gftlx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  rook-ceph-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rook-ceph-config
    Optional:  false
  rook-ceph-mons-keyring:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-mons-keyring
    Optional:    false
  rook-ceph-log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/log
    HostPathType:  
  ceph-daemon-data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/mon-d/data
    HostPathType:  
  default-token-gftlx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gftlx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/hostname=host3
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  3m1s   default-scheduler  Successfully assigned rook-ceph/rook-ceph-mon-d-649db79d7-z58ck to host3
  Normal  Pulled     3m     kubelet, host3     Container image "ceph/ceph:v14.2.1-20190430" already present on machine
  Normal  Created    3m     kubelet, host3     Created container init-mon-fs
  Normal  Started    3m     kubelet, host3     Started container init-mon-fs
  Normal  Pulled     2m59s  kubelet, host3     Container image "ceph/ceph:v14.2.1-20190430" already present on machine
  Normal  Created    2m59s  kubelet, host3     Created container mon
  Normal  Started    2m59s  kubelet, host3     Started container mon

**Comment by leseb** [comment]
You don't need to search for the previous logs (don't use `-p` here). Without logs there is nothing we can do. I'm closing this, feel free to re-open if you can provide more mon pod logs. Thanks.

**Comment by felixx** [comment]
I found an error in docker logs:
ceph-mon: error opening mon data directory at '/var/lib/ceph/mon/ceph-a': (13) Permission denied
is it the root cause to this problem?

**Comment by felixx** [comment]
I found the cause is selinux need be disabled

**Comment by leseb** [comment]
Instead of disabling selinux, you can set container labels and/or verify permissions haven't changed?

**Comment by danilorsilva** [comment]
I have the same problem here:
50m         Warning   FailedMount         Pod          Unable to mount volumes for pod "rook-ceph-mon-a-58f9c5b7d9-2lwr5_rook-ceph(9a8740b7-a98d-11e9-be4c-42010a8e0fcf)": timeout expired waiting for volumes to attach or mount for pod "rook-ceph"/"rook-ceph-mon-a-58f9c5b7d9-2lwr5". list of unmounted volumes=[rook-ceph-config rook-ceph-mons-keyring rook-ceph-log ceph-daemon-data default-token-4qtvw]. list of unattached volumes=[rook-ceph-config rook-ceph-mons-keyring rook-ceph-log ceph-daemon-data default-token-4qtvw]

rook-ceph       rook-ceph-agent-7hf9c                       1/1     Running                 0          54m
rook-ceph       rook-ceph-mon-a-5b6c9fc58c-vrmfb            0/1     Init:CrashLoopBackOff   15         54m
rook-ceph       rook-ceph-operator-8bc78b546-sfc4r          1/1     Running                 0          54m
rook-ceph       rook-discover-7kvjt                         1/1     Running                 0          54m
