### ISSUE TITLE
Logging on ROOKD_CEPH_CONFIG_OVERRIDE

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#338]
There is a powerful environment variable option `ROOKD_CEPH_CONFIG_OVERRIDE`

If specified, it would be valuable if the contents of the specified file was written into the log.

**Comment by travisn** [comment]
You should already see the config file written to the log, including all the overridden settings. You're looking for a separate log entry that indicates which settings were overridden?

**Comment by DanKerns** [comment]
You do see the ultimate .conf files in the journal but you can't easily tell what was added by the override vs what was generated by rook.

An alternative would be to log a comment in the .conf file saying " # Following lines added from <filename>".

**Comment by DanKerns** [comment]
This works fine the way it is
