### ISSUE TITLE
rook-ceph-operator CrashLoopBackOff, parsing config file error

### ISSUE THREAD

**Issue by xieyanker** [rook/rook#3380]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Hi, I deploy rook on my k8s, but the pod `rook-ceph-operator-864d97965d-tmjvh` is not running
```shell
root@cks-20190619112856-983-master-1:~/rook-ceph# kubectl get pod -nrook-ceph
NAME                                  READY   STATUS             RESTARTS   AGE
rook-ceph-operator-864d97965d-tmjvh   0/1     CrashLoopBackOff   4          2m35s
```
I print its log as follows:
```
root@cks-20190619112856-983-master-1:~/rook-ceph# kubectl logs rook-ceph-operator-864d97965d-tmjvh  -nrook-ceph
2019-07-02 07:19:01.396432 7fe347861700 -1 Errors while parsing config file!
2019-07-02 07:19:01.396442 7fe347861700 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-07-02 07:19:01.396443 7fe347861700 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-07-02 07:19:01.396443 7fe347861700 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
Error initializing cluster client: ObjectNotFound('error calling conf_read_file',)
```

**Expected behavior:**
I deploy rook on some different k8s clusters, this is first I got ` Errors while parsing config file!`,
Who can help me what's wrong about it?

**How to reproduce it (minimal and precise):**

Not sure

**Environment**:
* OS (e.g. from /etc/os-release):
Ubuntu 16.04.4 LTS
* Kernel (e.g. `uname -a`):
4.4.0-116-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
1.0.0
* Kubernetes version (use `kubectl version`):
1.14.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
Are you still experiencing this issue?

**Comment by xieyanker** [comment]
@leseb I have never encountered a similar problem. Maybe I should close this issue.
