### ISSUE TITLE
Automatically manage secrets for Ceph-CSI

### ISSUE THREAD

**Issue by phlogistonjohn** [rook/rook#3387]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

As previously lightly discussed in #3373 and #3358 as part of making Ceph-CSI well integrated with Rook, Rook should automatically handle the secrets that need to be consumed by ceph-csi in order to provision volumes, etc.

Currently the workflow requires the human to run ceph commands (in a toolbox pod for example) to set up a user* and auth token and use those value to manually create a secret and then specify this secret in the storage class.

In order to make the workflow using ceph csi even smoother we propose that Rook automatically create/update the secrets as needed, similar to how recent changes automate the config map Rook uses to inform ceph-csi of mons.

We speculated that these secrets might be tied to particular pools and so when a pool cr is being processed it might also establish the user/token and provision the secret. Similarly, removing the pool cr would clean up the secret. However, I'm not particularly tied to this approach if we determine there's a better way to go. The gist is just that users of Rook ceph should not need to set these secrets up manually.

 [*] Apologies if I get some of the exact ceph terminology wrong.

**What is use case behind this feature:**

Avoiding extra manual steps needed when setting up Ceph-CSI with Rook.

**Environment**:

**Comment by phlogistonjohn** [comment]
Ping: @ShyamsundarR @Madhu-1 @travisn @humblec et al.

**Comment by humblec** [comment]
@phlogistonjohn Thanks for the abstract of the issue. 


>As previously lightly discussed in #3373 and #3358 as part of making Ceph-CSI well integrated with Rook, Rook should automatically handle the secrets that need to be consumed by ceph-csi in order to provision volumes, etc.
>
As discussed earlier, Indeed taking the control of secret to "Rook" would be the desired way. 

>We speculated that these secrets might be tied to particular pools and so when a pool cr is being processed it might also establish the user/token and provision the secret. Similarly, removing the pool cr would clean up the secret. However, I'm not particularly tied to this approach if we determine there's a better way to go. The gist is just that users of Rook ceph should not need to set these secrets up manually.
>

I think the approach of controlling `secret` based on  pool cr looks fine.  Are we foreseeing any issues with this approach? One caveat I can see here is, the lifecycle of these objects are not depended on each other , so there is a possibility for a race condition. If we are making sure the updates to the secrets are protected, I think we are fine.

**Comment by travisn** [comment]
What about the following flow?
- The operator creates the rook-ceph cluster
- The operator generates a cephx user called `client.rook-rbd` (or similar)
- The operator saves the user key in a secret called `csi-rbd-secret` in the same namespace as the cluster
- All storage classes would use the same well-known `csi-rbd-secret` for accessing pools in the cluster.

Seems like we can trust the csi driver to use the same secret for all storage classes that point to the same rook-ceph cluster. Why would we need to have a new user for every pool?

**Comment by ShyamsundarR** [comment]
Overall @phlogistonjohn I agree with the need and secret generation, to ease total steps before a StorageClass is created :+1: 

> Seems like we can trust the csi driver to use the same secret for all storage classes that point to the same rook-ceph cluster. Why would we need to have a new user for every pool?

I would say we can use this as the default, assuming we can grant this single user more rights as needed when other pools are created (in the RBD case).

For the advanced user (security conscious?) we possibly want an option to create a per rbd pool (or cephFS fs, in the future). Is that a feasible approach?
