### ISSUE TITLE
LoadBalancer IPs rather than ServiceIPs

### ISSUE THREAD

**Issue by ryholt** [rook/rook#3404]
Similar to #966, I'm looking for ways to access the rook-ceph storage inside of my k8s cluster from external. I'm using Metallb and would prefer to expose the service via a LoadBalancer IP configuration rather than using HostNetwork.

I don't believe this is currently an option as the [cluster.yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L44-L46) only appears to support a host-network configuration and nothing that would toggle ClusterIP to LoadBalancerIP.

Is there a way to configure LoadBalancerIP rather than ServiceIP for rook-ceph services?

**Comment by AkshatM** [comment]
After digging into this issue, I believe this can be done. 

Clients connect to Ceph monitors (`mons`) which are currently created as a Kubernetes service [here](https://github.com/rook/rook/blob/18cca312059f9699dd89165558c91b721ec5878b/pkg/operator/ceph/cluster/mon/service.go#L60).  The service definition in that file has access to the YAML definition, and can easily have a `loadBalancerIP` added to it. 

I will work on and file a PR for this.
