### ISSUE TITLE
Automatically determine best layout for OSDs depending on available hardware

### ISSUE THREAD

**Issue by jbw976** [rook/rook#341]
Related to #304, which is a manual/explicit implementation, rook should automatically determine an optimal layout of OSD partitions based on what hardware is available on the node.

Don mentioned this potential algorithm:
> (1) Introduce a "tray" (or some other more appropriate name if you have a preference)
         into the CRUSH map, one tray per SSD, just above the OSD level.
   (2) Divide up the HDDs in a node as evenly as possible among the trays
   (3) Partition the SSDs to support an independent OSD for each HDD in the tray
   (4) Ensure that storage pools identify the tray as the default failure domain

> This way, replicas (or EC stripes) for a given piece of data will be spread across OSDs in such a manner as to guarantee that no two land in the same tray (i.e., no two can be lost through a single SSD failure).

Multiple NVMe/SSD devices should be supported for storing bluestore metadata, instead of the single metadata device that's supported now.

An existing NVMe/SSD metadata device should be able to have more partitions added to it, if there is more space and it's not maxed out in terms of contention.

**Comment by travisn** [comment]
@jbw976 do we still need this?

**Comment by jbw976** [comment]
i think this idea/algorithm still has some merit for intelligently using the devices on a node when there is more than 1 SSD/NVMe.  With the upcoming cluster topology/placement efforts, I'd like to keep this one around still, until it becomes conclusively superseded by a new issue with more details.
