### ISSUE TITLE
rgw-store-main: error parsing int: 80+443s

### ISSUE THREAD

**Issue by strowi** [rook/rook#3411]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
object-store not available
```
k logs rook-ceph-rgw-store-main-a-585557fd59-mxvrj |grep error                                                             
error parsing int: 80+443s: Expected option value to be integer, got '80+443s'
```

**Expected behavior:**
s3 should be accessible

**How to reproduce it (minimal and precise):**
- have working ceph-object-store config on 1.0.2  (see here https://github.com/rook/rook/issues/3245), upgrade image to 1.0.3
- above error shows up in rgw-store logs and object-store is inaccessible

**Environment**:Environment:
OS (e.g. from /etc/os-release): ubuntu18.04
Kernel (e.g. uname -a): 4.15.0-50-generic
Cloud provider or hardware configuration: bare-metal, 3 nodes for ceph (1 SSD (raid1), 6hdds)
Rook version (use rook version inside of a Rook Pod): v1.0.2
Kubernetes version (use kubectl version): v1.13.5
Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher2
Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox): ceph health
HEALTH_OK

**Comment by galexrt** [comment]
@strowi Could you post your Ceph ObjectStore yaml here.

**Comment by strowi** [comment]
@galexrt here it is. The rest of the configuration can also be found in the above linked issue. 

```
#################################################################################################################
# Create an object store with settings for replication in a production environment. A minimum of 3 hosts with
# OSDs are required in this example.
#  kubectl create -f object.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: store-main
  namespace: rook-ceph
spec:
  # The pool spec used to create the metadata pools. Must use replication.
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  # The pool spec used to create the data pool. Can use replication or erasure coding.
  dataPool:
    failureDomain: host
    replicated:
      size: 3
  # The gaeteway service configuration
  gateway:
    # type of the gateway (s3)
    type: s3
    # A reference to the secret in the rook namespace where the ssl certificate is stored
    sslCertificateRef: chefkoch.net
    # The port that RGW pods will listen on (http)
    port: 80
    # The port that RGW pods will listen on (https). An ssl certificate is required.
    securePort: 443
    # The number of pods in the rgw deployment (ignored if allNodes=true)
    instances: 3
    # Whether the rgw pods should be deployed on all nodes as a daemonset
    allNodes: false
    # The affinity rules to apply to the rgw deployment or daemonset.
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: Exists
    #  tolerations:
    #  - key: rgw-node
    #    operator: Exists
    #  podAffinity:
    #  podAntiAffinity:
    # A key/value list of annotations
    annotations:
    #  key: value
    resources:
    # The requests and limits set here, allow the object store gateway Pod(s) to use half of one CPU core and 1 gigabyte of memory
    #  limits:
    #    cpu: "500m"
    #    memory: "1024Mi"
    #  requests:
    #    cpu: "500m"
    #    memory: "1024Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-store-main-external
  namespace: rook-ceph
  labels:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: store-main
    type: storage
spec:
  ports:
  - name: rgw
    port: 80
    protocol: TCP
    targetPort: 443
    nodePort: 30000
  selector:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: store-main
  sessionAffinity: None
  type: NodePort
```

**Comment by ron1** [comment]
According to the Ceph RGW http frontends doc http://docs.ceph.com/docs/master/radosgw/frontends/#id4, the beast frontend supports separate port properties named port and ssl_port while civetweb supports a single port property with 's' suffix to indicate ssl and '+' to separate multiple ports. Rook version 1.0.3 is the first to enable the beast frontend. In order to fix this problem, the operator will likely need some conditional logic around the frontend (ssl_)port properties and civetweb vs. beast.

**Comment by leseb** [comment]
@ron1 your analysis is correct, I'm writing a patch as we speak. Unfortunately, there is no workaround at this point, our only option is to release 1.0.4 rapidly.
