### ISSUE TITLE
rook delete osd without reason

### ISSUE THREAD

**Issue by caisan** [rook/rook#3423]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
1. ceph mark osd.x as out
2. rook delete the pod without any log or reason.

**Expected behavior:**
osd run as normal
**How to reproduce it (minimal and precise):**

1. create a rook cluster with multi-node by below command:
```kubectl create -f operator.yml```
```kubectl create -f cluster.yml```

**Environment**:
* OS centos 7.6 (e.g. from /etc/os-release):
* Kernel 3.10.0-957.21.2.el7.x86_64 (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version v1.0.0 (use `rook ve` inside of a Rook Pod):
* Kubernetes version v1.12.5 (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
Please share your operator's log.
