### ISSUE TITLE
topologyAware functionality not working

### ISSUE THREAD

**Issue by mmgaggle** [rook/rook#3430]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Setting topologyAware to true inside specs section of a cluster.yaml does not result in a cluster that has OSDs under zone or region buckets in the CRUSH map. As such, pools can be created that map replicas or EC chunks to a zone or region osd-failure-domain.

One problem is the 'zone' type is missing from the crushmap rook-ceph is feeding the cluster (see below). The secondary issue is that the osd_location is not being populated with zone and/or region buckets for each OSD.

**Expected behavior:**

Setting topologyAware to true inside specs section of a cluster.yaml should result in a cluster that has OSDs under zone or region buckets in the CRUSH map. Then pools cannot be created that map replicas or EC chunks to a zone or region osd-failure-domain.

**How to reproduce it (minimal and precise):**

1. Provision a three worker OpenShift cluster in EC2 such that each worker is in a distinct availability zone. 
2. Ensure cloud-provided is properly configured such that failure-domain.beta.kubernetes.io/{zone,region} labels are being properly applied to workers.
3. Deploy rook-ceph and create a cluster using a cluster.yaml that contains toplogyAware set to true in the specs.
4. Wait for cluster to finish provisioning
5. Create toolbox pod, rsh to it, and inspect the crushmap to see missing bucket type, and absence of zone or region buckets for pods running in workers with zone/region labels.

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux CoreOS 410.8.20190520.0 (Ootpa)
* Kernel (e.g. `uname -a`): 4.18.0-80.1.2.el8_0.x86_64
* Cloud provider or hardware configuration: 3x m4.large masters, 3x m5d.4xlarge workers (in distinct AZs), 
* Rook version (use `rook version` inside of a Rook Pod):

 rook: v1.0.0-187.gf0b0f0e  (f0b0f0e4f31140cc4b81453f1d918d988021db21)

* Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+cb455d664", GitCommit:"cb455d664", GitTreeState:"clean", BuildDate:"2019-05-19T23:03:23Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

OpenShift

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

HEALTH_WARN crush map has legacy tunables (require firefly, min is hammer)

**Other Information**

Rook-ceph operator log showing rook-ceph setting initial crushmap. I think this is overriding the upstream version that has the 'zone' crush type. Compare:

https://github.com/rook/rook/blob/1bf3cfa4bf6c19d350f6a3e02bc4846708e17898/pkg/daemon/ceph/client/crush.go#L50

With:

https://github.com/ceph/ceph/pull/27070/files

```
2019-07-08 21:20:54.221869 I | op-cluster: creating initial crushmap
2019-07-08 21:20:54.222002 I | exec: Running command: crushtool -c /tmp/264578157 -o /tmp/614087400
2019-07-08 21:20:54.252555 I | exec: Running command: ceph osd setcrushmap -i /tmp/614087400 --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/281646887
2019-07-08 21:20:55.132306 I | exec: 2
2019-07-08 21:20:55.132424 I | op-cluster: created initial crushmap
```

Crush map on freshly created rook-ceph cluster (note the missing zone type):
```
sh-4.2# cat crush.txt
# begin crush map
tunable choose_local_tries 0
tunable choose_local_fallback_tries 0
tunable choose_total_tries 50
tunable chooseleaf_descend_once 1
tunable chooseleaf_vary_r 1
tunable straw_calc_version 1

# devices
device 0 osd.0 class ssd
device 1 osd.1 class ssd
device 2 osd.2 class ssd
device 3 osd.3 class ssd
device 4 osd.4 class ssd
device 5 osd.5 class ssd

# types
type 0 osd
type 1 host
type 2 chassis
type 3 rack
type 4 row
type 5 pdu
type 6 pod
type 7 room
type 8 datacenter
type 9 region
type 10 root

# buckets
host ip-10-0-139-184 {
	id -3		# do not change unnecessarily
	id -4 class ssd		# do not change unnecessarily
	# weight 0.545
	alg straw
	hash 0	# rjenkins1
	item osd.3 weight 0.272
	item osd.0 weight 0.272
}
host ip-10-0-163-134 {
	id -5		# do not change unnecessarily
	id -6 class ssd		# do not change unnecessarily
	# weight 0.545
	alg straw
	hash 0	# rjenkins1
	item osd.2 weight 0.272
	item osd.5 weight 0.272
}
host ip-10-0-144-122 {
	id -7		# do not change unnecessarily
	id -8 class ssd		# do not change unnecessarily
	# weight 0.545
	alg straw
	hash 0	# rjenkins1
	item osd.1 weight 0.272
	item osd.4 weight 0.272
}
root default {
	id -1		# do not change unnecessarily
	id -2 class ssd		# do not change unnecessarily
	# weight 1.635
	alg straw
	hash 0	# rjenkins1
	item ip-10-0-139-184 weight 0.545
	item ip-10-0-163-134 weight 0.545
	item ip-10-0-144-122 weight 0.545
}

# rules
rule replicated_ruleset {
	id 0
	type replicated
	min_size 1
	max_size 10
	step take default
	step chooseleaf firstn 0 type host
	step emit
}

# end crush map
```

Example ceph.conf from an OSD pod, note the absence of zone or region in the crush_location parameter:
```
sh-4.2# cat /etc/ceph/ceph.conf
[global]
fsid                      = 46258bc3-62c5-4c59-b06d-51e5bda56cb0
run dir                   = /var/lib/rook/osd0
mon initial members       = a b c
mon host                  = v1:172.30.164.205:6789,v1:172.30.201.105:6789,v1:172.30.10.98:6789
public addr               = 10.130.4.12
cluster addr              = 10.130.4.12
mon keyvaluedb            = rocksdb
mon_allow_pool_delete     = true
mon_max_pg_per_osd        = 1000
debug default             = 0
debug rados               = 0
debug mon                 = 0
debug osd                 = 0
debug bluestore           = 0
debug filestore           = 0
debug journal             = 0
debug leveldb             = 0
filestore_omap_backend    = rocksdb
osd pg bits               = 11
osd pgp bits              = 11
osd pool default size     = 1
osd pool default min size = 1
osd pool default pg num   = 100
osd pool default pgp num  = 100
osd objectstore           = filestore
crush location            = root=default host=ip-10-0-139-184
rbd_default_features      = 3
fatal signal handlers     = false

[osd.0]
keyring              = /var/lib/ceph/osd/ceph-0/keyring
bluestore block path = /var/lib/ceph/osd/ceph-0/block
```

**Comment by mykaul** [comment]
@noahdesu  - you have something around this for the MONs, right?

**Comment by leseb** [comment]
dup of https://github.com/rook/rook/issues/3118?

**Comment by jarrpa** [comment]
I'd say related, but not dup.

**Comment by noahdesu** [comment]
@mykaul correct. #3355 allows rook to use k8s AZ labels when placing monitor pods.

**Comment by rohantmp** [comment]
I've slightly narrowed down the problem. I see that the osd initContainer is not being passed the ROOK_LOCATION environment variable. I see all the logic in place to pass it that variable, but I'm guessing there's a bug in there somewhere.

I tested with three nodes labeled with the key `failure-domain.beta.kubernetes.io/region` and distinct values.
