### ISSUE TITLE
Document how to add integration tests

### ISSUE THREAD

**Issue by leseb** [rook/rook#3433]
For people adding a feature, it is important to have some documentation/guidance on how to get started writing integration test so we can get coverage for new features in the CI.

**Comment by nabokihms** [comment]
Thanks :)

**Comment by satoru-takeuchi** [comment]
I'll do it. Currently, I'm working on adding a new test of OSD on LV-backed PVC. After that, I'll write add this document with the experience of that work.

**Comment by satoru-takeuchi** [comment]
> Currently, I'm working on adding a new test of OSD on LV-backed PVC. After that, I'll write add this document with the experience of that work.

I'll do after merging the following PR. It would be merged at the end of this month, in other words, in v1.4 release.

ceph: add osd on lv backed pvc test #5741
https://github.com/rook/rook/pull/5741

**Comment by satoru-takeuchi** [comment]
> I'll do after merging the following PR. It would be merged at the end of this month, in other words, in v1.4 release.

#5741  is blocked by #6421 which will be merged soon.

**Comment by satoru-takeuchi** [comment]
I'm writing...
