### ISSUE TITLE
In case of osd full scenario 100% pgs went to unknown state, when added more storage  

### ISSUE THREAD

**Issue by xenolinux** [rook/rook#3439]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After populating the more data, osds were being nearfull and full. When added more storage in this situation, all pgs went into unknown state. 

**Expected behavior:**
Cluster should be rebalanced. Data movement should happen.  100% pgs should not be going in unknown state.

**How to reproduce it (minimal and precise):**
1. Populate lots of data.
2. Wait for osds to be nearfull or full.
3. Add more storage into the cluster.
4. Watch ceph status to see pgs state.

* Kubernetes version : Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+7bd2e5b", GitCommit:"7bd2e5b", GitTreeState:"clean", BuildDate:"2019-05-19T23:52:43Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type : OpenShift
* Storage backend status : for Ceph use `ceph health`  [ in the Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)

**Comment by leseb** [comment]
I don't think this is a Rook issue, it's more a Ceph problem at this point, would you mind opening a tracker bug at https://tracker.ceph.com instead?
Thanks.

I'm leaving this open to see if in the intermediate Rook can do anything to mitigate that, but I doubt.

**Comment by xenolinux** [comment]
Sure. I will open a bug on Ceph tracker.

**Comment by galexrt** [comment]
@xenolinux Did you open a bug on the Ceph tracker? If so, please post the Ceph tracker issue link here so we can track it.

**Comment by xenolinux** [comment]
@galexrt Yes. I have opened a bug on Ceph tracker. Here's the link : https://tracker.ceph.com/issues/40785
