### ISSUE TITLE
serviceaccount "rook-ceph-cmd-reporter" not found

### ISSUE THREAD

**Issue by nnachefski** [rook/rook#3447]
I've been able to deploy rook-ceph on Openshift 4.1 for the past week (using operator-openshift.yaml), but that all changed this morning.  Now, i get this error:

20s   Warning   FailedCreate   job/rook-ceph-detect-version   Error creating: pods "rook-ceph-detect-version-" is forbidden: error looking up service account rook-ceph/rook-ceph-cmd-reporter: serviceaccount "rook-ceph-cmd-reporter" not found

**Comment by travisn** [comment]
@nnachefski You'll need to create the latest common.yaml in order to get the missing service account and related resources. If you are running with the `rook/ceph:master` image you may have experienced an unintentional upgrade, which is why upgrades are not supported build-to-build from master.

**Comment by nnachefski** [comment]
ah, got it.  Thanks!  closing...
