### ISSUE TITLE
WAL and DB optimization

### ISSUE THREAD

**Issue by dimm0** [rook/rook#3448]
**Is this a bug report or feature request?**
* Feature Request
Today I updated to Nautilus, and now every OSD is complaining:

`osd.32 spilled over 11 GiB metadata from 'db' device (1.9 GiB used of 20 GiB) to slow device`

I found this thread:

http://lists.ceph.com/pipermail/ceph-users-ceph.com/2019-February/033286.html

```
Bluestore/RocksDB will only put the next level up size of DB on flash if the whole size will fit.
These sizes are roughly 3GB,30GB,300GB. Anything in-between those sizes are pointless. Only ~3GB of SSD will ever be used out of a
28GB partition.
```

Rook by default creates a 20GB partitions, from which only 3 are actually used (not sure about the newer scheme, probably the same?)

I have the cluster with 1.7PB total, 700 TB used, installed long ago, so it has an old scheme with symlinks to partitions, and it would be really hard to delete and recreate the nodes to have the new scheme of WAL.

**What should the feature do:**
Would it be possible to migrate to the new scheme without deleting the current data? Also I'd like to use the https://github.com/rook/rook/pull/3213 to spread the WALs to several NVME's, again without the need to delete the whole node (those have 8*12 TB drives each, and take forever to backfill)

**What is use case behind this feature:**
Above

**Comment by dimm0** [comment]
@travisn

**Comment by travisn** [comment]
Hmm, what I see in in the docs is the only way to reconfigure the spillover size is to create new OSDs. This [link](https://github.com/ceph/ceph/blob/master/doc/rados/operations/health-checks.rst#bluefs_spillover) also mentions how to suppress the warning.

@liewegas What is the background on the 3/30GB step limit for spillover? There's no setting to use more of the space before spilling over if you don't have that exact space?

**Comment by liewegas** [comment]
- Short term solution is to just disable the warning.
- Allocating more flash is (almost) always better, but it is difficult to change after the OSD is provisioned.  Simplest way to add more flash to each OSD is to remove them and reprovision a new one; this is slow and time consuming :(.
- We're working on some bluestore changes that will be better behaved and use the available flash more effectively.  Rocksdb's placement is pretty primitive so we think we can do better.

**Comment by dimm0** [comment]
I actually have more space on the NVMEs to enable 30-GB partitions, and I can use more than one NVME. This is really critical for the cluster, now it explains why the writes are still slow and nodes sometimes restart with OOMKill - they're almost not using the NVME WAL (1-2 GB out of 20 allocated)

**Comment by dimm0** [comment]
I'm going to add another node to the cluster, and I'm confused what are my options now..
Will all 3 of `databaseSizeMB`, `walSizeMB` and `journalSizeMB` work? I thought those are now combined to a single partition?
Which scheme will be used for a new node?
What size should I choose considering the above?

**Comment by travisn** [comment]
@dimm0 With ceph-volume creating the OSD you don't need to worry about those size settings anymore. So no need to specify them in the cluster CR.

**Comment by dimm0** [comment]
How will it slice my NVME then?

**Comment by dimm0** [comment]
@travisn what's the current scheme for journals? I'd like to check it did the right thing after I add a node..

**Comment by travisn** [comment]
@dimm0 From slack conversation... Since you're on v1.0.x and nautilus, rook will call `ceph-volume` to create the OSDs instead of using its own partitioning scheme. I understand that `ceph-volume` will create LVs on the `metadataDevice` for the db/wal, divided proportionally depending on the number of (spinning) data devices. @alfredodeza correct?

**Comment by alfredodeza** [comment]
Just the block.db will be divided proportionally unless the bluestore_block_db_size gets changed in ceph.conf or on the CLI. It defaults to "as large as possible". Also note that *journals* have nothing to do with bluestore, so setting a size for journal will not do anything for block.db

**Comment by alfredodeza** [comment]
If data is spilling over, you must go through proper sizing. In Bluestore this is documented here: https://docs.ceph.com/docs/master/rados/configuration/bluestore-config-ref/#sizing for the minimum requirements you should have to avoid spilling over

**Comment by dimm0** [comment]
Is it possible to use several NVME devices for DB?

**Comment by alfredodeza** [comment]
> Is it possible to use several NVME devices for DB?

Yes. If you create them all at once, ceph-volume will create one VG with all of them. This might not necessarily be what you want though. You can by-pass this behaviour by matching devices with an nvme and running several times

**Comment by travisn** [comment]
In Rook, if you specify `metadataDevice` as the nvme, rook will call c-v once with that device and all the other devices on the node at the same time. A change would be needed in rook if we would need to support data devices each having a db on separate nvme.

**Comment by dimm0** [comment]
> If you create them all at once, ceph-volume will create one VG with all of them.

Is this possible in rook?

**Comment by travisn** [comment]
>> If you create them all at once, ceph-volume will create one VG with all of them.

> Is this possible in rook? Should I give all NVMEs as a list?

@dimm0 no, i believe we would need some changes to support this. @mvollman has been making changes in this area, he could correct me if i'm missing something.

**Comment by dimm0** [comment]
https://github.com/rook/rook/pull/3213 this has been merged already

**Comment by mvollman** [comment]
Yea #3213 will allow you to specify a `metadataDevice` per each OSD on a node.  It only accepts a single string argument, it does not currently allow for a list of metadata devices.

**Comment by dimm0** [comment]
Any estimate on when this could be implemented? I need to expand the storage, but would rather wait to add a node with multiple NVMEs...

**Comment by dimm0** [comment]
I was thinking, can't I create a VG myself and give it to rook? @mvollman

**Comment by travisn** [comment]
This is a low risk backport for 1.0

**Comment by travisn** [comment]
Will be in v1.0.6
