### ISSUE TITLE
expose various optimized configurations to rook users

### ISSUE THREAD

**Issue by jbw976** [rook/rook#346]
Building on top of #341, rook can provide an even better experience by exposing a set of optimized "configurations" that the user can choose.  For example: high IOPS, high throughput, high failure resiliency, etc.

rook should analyze (sample) the hardware, determine if the chosen configuration is feasible with the available hardware specs, and then determine the optimal layout to achieve the goals of the chosen configuration.

Background info: BlueFS exposes a single namespace that can span multiple devices and is the backing file system for rocksDB and OSD block storage.  rocksDB supports the notion of multiple paths for newer (fast) and older (slow/cold) data:
https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L979

We should think through how best to use the spanning features of BlueFS and rocksDB to expose varying "configurations" to rook users.

Note this could be folded into the disk "prepare" command that has been discussed before, as a separate step run before rookd starts.  After sampling the hardware in the "prepare" step, we could even show the user potential I/O numbers that they can expect.

**Comment by travisn** [comment]
@jbw976 is this still relevant? Seems like the declarative nature of the CRD is different from this approach.

**Comment by jbw976** [comment]
yes i agree @travisn that this is not the experience i envision for Rook with its declarative interface.
