### ISSUE TITLE
[ceph] Prepare OSD job cannot create rook-ceph-osd-config ConfigMap due to missing RBAC

### ISSUE THREAD

**Issue by ron1** [rook/rook#3466]
* Bug Report

**Deviation from expected behavior:**
osd-prepare job fails with the following error:
```
cephosd: saving osd dir map failed to save osd dir map. configmaps "rook-ceph-osd-<myhost1>-config" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>
```
This is caused by rook-ceph-osd service account missing the following RBAC:
```
apiGroups: ["ceph.rook.io"]
resources: ["*"]
verbs: ["*"]
```
**Expected behavior:**
osd-prepare job completes successfully

**How to reproduce it (minimal and precise):**
Define a CephCluster using Rook v1.0.4 on OCP 3.11.98.

**File(s) to submit**:
I fixed this bug by adding the following lines here: https://github.com/rook/rook/blob/9ce0f293fcfd6ba01fc032cf325c9fa067067b41/cluster/examples/kubernetes/ceph/common.yaml#L480
```
- apiGroups: ["ceph.rook.io"]
  resources: ["*"]
  verbs: ["*"]
```
* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
prepare-osd log final error entry:
```
cephosd: saving osd dir map failed to save osd dir map. configmaps "rook-ceph-osd-<myhost1>-config" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>
```

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.6
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.0.4
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.11+
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift 3.11.98
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by rajatsingh25aug** [comment]
I see you have fixed the bug, why don't you raise a PR?.

**Comment by rajatsingh25aug** [comment]
@ron1 I see the change that you mentioned is already in [here](https://github.com/rook/rook/blob/2878e3d2db0d56e2aea9d69f20394c913f2116c5/cluster/examples/kubernetes/ceph/common.yaml#L480).
Closing this issue.

**Comment by leseb** [comment]
@ron1 please submit a PR and we will take it from there.

**Comment by travisn** [comment]
@rajatsingh25aug The delete permission for configmaps was actually needed for a different `apiGroup`: `ceph.rook.io` instead of the blank api group in your link.

I'd still be curious on the repro. If this was hitting all versions of openshift, I would have thought we would hear more about this issue.

**Comment by rajatsingh25aug** [comment]
@travisn 
I tried it on openshift 4.1 and I see that osd job is getting created successfully.
I try and if it's hitting it on other versions on Openshift and raise a PR.

**Comment by ron1** [comment]
@travisn It would be great if the rook-ceph CI/CD infrastructure included an OKD or OCP 3.11 cluster since this kubernetes distribution has unique security requirements and is scheduled to be around for an extended period of time.

It seems this issue may be unique to OKD/OCP 3.x. I'll go ahead and raise a PR for it. Note the issue did not exist in v1.0.2.

**Comment by travisn** [comment]
Yeah, i would love to have every reasonable version/distro as part of the CI. It's just a matter of finding someone to get that done upstream.

If this only affects 3.11, perhaps we could have a separate manifest such as common-ocp-3.11.yaml instead of adding it to the common.yaml for everyone.

**Comment by ron1** [comment]
The Kubernetes code in question is here: https://github.com/kubernetes/kubernetes/blob/3f1cb97f9ad7b84176be30f85c7e10cc7bb1ff56/plugin/pkg/admission/gc/gc_admission.go#L120. If this issue is indeed the result of an OCP 3.x shortcoming, then I agree a separate common-openshift-3.x.yaml manifest should be created.

Based on the patch for a very similar issue encountered by the spotahome redis-operator: https://github.com/spotahome/redis-operator/issues/98, I suspect the proposed patch can be narrowed as follows:
```
apiGroups: ["ceph.rook.io"]
resources: ["cephclusters", "cephclusters/finalizers"]
verbs: ["*"]
```
I will test this narrowed patch and report back.

**Comment by luisrico** [comment]
I faced same issue with Rook v1.0.4 and OCP 4.1, after creating common.yml + operator-openshift.yaml + cluster-test.yaml, rook-ceph-osd-prepare fails and reach backoff limit so osd pods are not created. Slightly different log error  found in oc logs rook-ceph-operator- for all dataDirHostPath OSDs: 
```
2019-07-28 09:23:12.613839 I | op-osd: osd orchestration status for node ip-10-0-128-201 is failed
2019-07-28 09:23:12.613872 E | op-osd: orchestration for node ip-10-0-128-201 failed: &{OSDs:[] Status:failed Message:failed to save osd dir map. configmaps "rook-ceph-osd-ip-10-0-128-201-config" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>}
```
Applied the fix by modifying common.yaml and got Ceph cluster up and running.

**Comment by ron1** [comment]
Did you use the original patch or the narrowed patch?

**Comment by luisrico** [comment]
I applied original patch: adding these 3 lines after line 480 in common.yaml:
```
- apiGroups: ["ceph.rook.io"]
  resources: ["*"]
  verbs: ["*"]
```

**Comment by travisn** [comment]
@ron1 Given the repro on OCSP 4.1, sounds like we can go ahead and add this to common.yaml instead of keeping it separate. You're planning on opening a PR then?
