### ISSUE TITLE
set pool size fail after reboot rook node

### ISSUE THREAD

**Issue by caisan** [rook/rook#3468]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
set pool size fail after restart rook node
**Expected behavior:**
pool size is set as Expected after reboot
**How to reproduce it (minimal and precise):**

1. when rook cluster run(single node) and ceph health ok
2. check pool size before reboot
```ceph osd pool get replicapool size```
```
[root@node` /]# ceph osd pool get replicapool size
size: 1
```
3. log into toolsbox, and run the ceph command:
```ceph osd pool set replicapool size 2```
3. reboot the rook node(operator node):

4. check the pool size 
```
[root@node1 /]# ceph osd pool get replicapool size
size: 1
```
**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): centos 7.6
* Kernel (e.g. `uname -a`): 3.10.0-957.21.2.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.0.0-69.g4718797
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 13.2.5
* Kubernetes version (use `kubectl version`):v1.12.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by noahdesu** [comment]
I'm guessing that the pool size is being reset based on a setting in a crd. Can you provide the operator log produced after the operator reboot?

**Comment by leseb** [comment]
@noahdesu is right, @caisan I don't see this as a bug, in this case, Rook simply honors the desired state provided by the CR. Instead, you should update your CR and set a different pool size.

**Comment by leseb** [comment]
I'm closing this, feel free to re-open if you have any more concerns.
