### ISSUE TITLE
For single device bluestore OSDs, partitions are not necessary

### ISSUE THREAD

**Issue by jbw976** [rook/rook#347]
BlueFS file system allocator does not strictly need explicit partitions to separate rocksDB and block storage (potentially WAL too) for a bluestore OSD.  If an OSD is going to use a single device, consider removing the unnecessary partitions that rook creates now and just let BlueFS allocator manage the device itself.

Note we'd still need a consistent way to identify the device across reboots, but we could accomplish that by setting a label on the device.

**Comment by liewegas** [comment]
Note that this is exactly what ceph-volume does (with lvm labels).  I'm hoping we can use ceph-volume across the board so that rook isn't doing something unique here.

**Comment by leseb** [comment]
This should be solved naturally once we have https://github.com/rook/rook/issues/1342.
