### ISSUE TITLE
rbd unmap -o force device hung，can't unmap successful,but rbd image no longer exists

### ISSUE THREAD

**Issue by zhangxingdeppon** [rook/rook#3479]
**Is this a bug report or feature request?**
* Bug Report
Hi,buddy,I have encountered difficulties on a issue. when I did “rbd unmap -o force device” ，the command status  was hung,I have no idea about it,can you help me ,thanks.
Look at the screenshot below
![image](https://user-images.githubusercontent.com/16789841/61524055-2795b280-aa48-11e9-9951-a371c1aa04b9.png)

for example mapped "/dev/rbd0", corresponding to map "pvc-cbd4134c-97ff-11e9-b2f4-fa163efea19e " 
<pre><code>
sh-4.2# rbd showmapped
id pool            image                                    snap device    
0  replicapool-hdd pvc-cbd4134c-97ff-11e9-b2f4-fa163efea19e -    /dev/rbd0 
1  replicapool-hdd pvc-405d0aeb-9873-11e9-b2f4-fa163efea19e -    /dev/rbd1 
2  replicapool-hdd pvc-dc8acf73-9878-11e9-929d-fa163ebce782 -    /dev/rbd2 
3  replicapool-hdd pvc-fc24e51f-9878-11e9-929d-fa163ebce782 -    /dev/rbd3 
4  replicapool-hdd pvc-ba1a91f0-987a-11e9-929d-fa163ebce782 -    /dev/rbd4 
5  replicapool-hdd pvc-b28f1d50-987f-11e9-929d-fa163ebce782 -    /dev/rbd5 
6  replicapool-hdd pvc-563c6fdc-98ce-11e9-b974-fa163efea19e -    /dev/rbd6 
</code></pre>

and rbd image no longer exists,as follows:
<pre><code>
sh-4.2# rbd ls replicapool-hdd
pvc-1f210265-a9fb-11e9-9734-fa163ebce782
pvc-563c6fdc-98ce-11e9-b974-fa163efea19e
pvc-8c064410-a9fe-11e9-9734-fa163ebce782
pvc-ade8dea0-a9fe-11e9-9734-fa163ebce782
pvc-bf831264-a9fb-11e9-9734-fa163ebce782
pvc-bfd2b0fc-a9fb-11e9-9734-fa163ebce782
pvc-c01a1355-a9fb-11e9-9734-fa163ebce782
pvc-c358594d-aa04-11e9-9734-fa163ebce782
pvc-d41b5687-aa02-11e9-9734-fa163ebce782
pvc-f5f35e49-a9fb-11e9-9734-fa163ebce782
</code></pre>
after that,when execute the command "rbd unmap -o force /dev/rbd0 "  is hang
I tryed to look mon's log,but I can't found any details about it,can you give me some advice ,I want to resolve it,if need s more information ,please let me know ,I can provide it,thanks.
**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
Why is the image gone in the first place? Did you remove the image while it was mapped onto a node?

**Comment by zhangxingdeppon** [comment]
> Why is the image gone in the first place? Did you remove the image while it was mapped onto a node?

sorry.I also don't know when the image was deleted.but I want to  delete the dirty data about “map”，how can i do that?"force" is invalid,thanks
