### ISSUE TITLE
Ceph: Add schema validation to all CRDs

### ISSUE THREAD

**Issue by travisn** [rook/rook#3480]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
If a CR is created with an invalid type (e.g. string instead of int), the operator will continuously print errors to the log and will not be able to process other CRs of that type until the bad CR is deleted. 

For example, when creating the CephBlockPool with replicated.size that is not a number, we see:
```
E0719 16:19:08.663569       6 reflector.go:126] github.com/rook/operator-kit/watcher.go:76: Failed to list *v1.CephBlockPool: v1.CephBlockPoolList.Items: []v1.CephBlockPool: v1.CephBlockPool.Spec: v1.PoolSpec.Replicated: v1.ReplicatedSpec.Size: readUint64: unexpected character: �, error found in #10 byte of ...|:{"size":"badnumber"|..., bigger context ...|null,"failureDomain":"host","replicated":{"size":"badnumber"}}}],"kind":"CephBlockPoolList","metadat|...
```

This can be fixed with CRD schema validation. We have some [CephCluster CR validation](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml#L34-L84) already, we just need to add more validation to the other CRs, in particular where ints are required for pool count, etc.

**What is use case behind this feature:**
Better handling of CR errors.

**Comment by rajatsingh25aug** [comment]
@travisn Can you please assign this to me?.
Thanks!

**Comment by travisn** [comment]
Thanks @rajatsingh25aug for taking this. Here are a few more details for the approach to this... We need to add the validation to the CRD. We already have some [validation on the CephCluster](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml#L34-L86) CRD. Now we need validation for the pool, filesystem, and object store. Basically, look at pool.yaml, object.yaml, and filesystem.yaml for integers, then add the schema validation for those integers in the CRDs in common.yaml, similar to the CephCluster validation.

**Comment by rajatsingh25aug** [comment]
Okay, @travisn I'll look into it.
Thanks again!

**Comment by alexcpn** [comment]
Maybe yaml should be validated; I was getting this error as I missed a space  during edit ( I am also new to yamls and missed the trend of spaces before values followed)

`spec:
  replicated:
    size:1
`
`kubectl -n rook-ceph logs --tail=10  rook-ceph-operator-..`

> E0725 10:28:27.877072       6 reflector.go:126] github.com/rook/operator-kit/watcher.go:76: Failed to list *v1.CephBlockPool: v1.CephBlockPoolList.Items: []v1.CephBlockPool: v1.CephBlockPool.Spec: v1.PoolSpec.Replicated: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|licated":"size:1"}}]|..., bigger context ...|7d-4e45-812f-b6f9f2ebc545"},"spec":{"replicated":"size:1"}}],"kind":"CephBlockPoolList","metadata":{|...

Corrected to

`spec:
  replicated:
    size: 1
`
and things are fine 

> I0725 10:31:22.157055       6 controller.go:1196] provision "rook-cassandra/rook-cassandra-data-rook-cassandra-ndac-cl1-ndac-cl1-0" class "rook-ceph-block": starte

d
