### ISSUE TITLE
Operator looks for missing nodes forever

### ISSUE THREAD

**Issue by iMartyn** [rook/rook#3484]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
rook-ceph-opperator sits waiting for a node that doesn't exist in `kubectl get nodes` forever

**Expected behavior:**
rook-ceph-operator should check the list of nodes that actually exist even if it did at one point know about a node.

**How to reproduce it (minimal and precise):**
* Create a rook-ceph cluster in a k8s cluster that has lots of nodes, use allNodes and allDisks mode.
* Delete a node (kubectl delete node)
* restart the operator

**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
Sorry, didn't think to keep them
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
* Kernel (e.g. `uname -a`): Linux worker 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
* Cloud provider or hardware configuration: bare metal (k3s in this case)
* Rook version (use `rook version` inside of a Rook Pod): 1.0.2
* Storage backend version (e.g. for ceph do `ceph -v`): nautilus
* Kubernetes version (use `kubectl version`): "v1.11.1"
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): didn't check, sorry.

**Comment by travisn** [comment]
Specifically, the operator was waiting for an OSD to be installed. The configmap `rook-ceph-osd-<node>-status` existed for the missing node, but the node was never going to respond. The operator shouldn't stay blocked on a node that isn't responding, whether or not the node has been removed. A timeout should be sufficient here to remove the configmap and continue.
