### ISSUE TITLE
Deployment failure - First mon pod gets into Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by nehaberry** [rook/rook#3485]
Description:

During rook-ceph deployment, mon deployment is failing with following error message:

```
Events:
  Type     Reason     Age                  From                                                 Message
  ----     ------     ----                 ----                                                 -------
  Normal   Scheduled  26m                  default-scheduler                                    Successfully assigned rook-ceph/rook-ceph-mon-a-7bcd58b586-4mbjh to ip-10-0-175-110.us-east-2.compute.internal
  Normal   Pulled     25m (x5 over 26m)    kubelet, ip-10-0-175-110.us-east-2.compute.internal  Container image "ceph/daemon-base:latest-nautilus-devel" already present on machine
  Normal   Created    25m (x5 over 26m)    kubelet, ip-10-0-175-110.us-east-2.compute.internal  Created container chown-container-data-dir
  Normal   Started    25m (x5 over 26m)    kubelet, ip-10-0-175-110.us-east-2.compute.internal  Started container chown-container-data-dir
  Warning  BackOff    88s (x117 over 26m)  kubelet, ip-10-0-175-110.us-east-2.compute.internal  Back-off restarting failed container

```
```
$ oc get pods -n rook-ceph
NAME                                  READY   STATUS                  RESTARTS   AGE
csi-cephfsplugin-4qmng                2/2     Running                 0          27m
csi-cephfsplugin-dqvb6                2/2     Running                 0          27m
csi-cephfsplugin-provisioner-0        3/3     Running                 0          27m
csi-cephfsplugin-zt4np                2/2     Running                 0          27m
csi-rbdplugin-8zb78                   2/2     Running                 0          27m
csi-rbdplugin-9k4kv                   2/2     Running                 0          27m
csi-rbdplugin-mxsmn                   2/2     Running                 0          27m
csi-rbdplugin-provisioner-0           4/4     Running                 0          27m
rook-ceph-agent-pkm4p                 1/1     Running                 0          27m
rook-ceph-agent-rlmzf                 1/1     Running                 0          27m
rook-ceph-agent-s7xtz                 1/1     Running                 0          27m
rook-ceph-mon-a-7bcd58b586-4mbjh      0/1     Init:CrashLoopBackOff   10         27m
rook-ceph-operator-5c6fd4b7db-x4qpq   1/1     Running                 0          28m
rook-discover-dktsz                   1/1     Running                 0          28m
rook-discover-hd6bk                   1/1     Running                 0          28m
rook-discover-hrps6                   1/1     Running                 0          28m
```
**Environment**:
* OS (e.g. from /etc/os-release): **Red Hat Enterprise Linux CoreOS 410.8.20190627.0 (Ootpa)**

* Kernel (e.g. `uname -a`): **Linux ip-10-0-146-110 4.18.0-80.4.2.el8_0.x86_64 #1 SMP Fri Jun 14 13:20:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux**

*** Cloud provider or hardware configuration:**
* Rook version (use `rook version` inside of a Rook Pod):   rook: v1.0.0-268.g3f67e8f

```
$ oc describe pod rook-ceph-operator-5c6fd4b7db-x4qpq -n rook-ceph |grep -i image
    Image:         rook/ceph:master
    Image ID:      docker.io/rook/ceph@sha256:fadae8cbe112f2779f24cbe88430c730b965b249f2f5bf427602bce61926bbf8
      ROOK_CSI_CEPH_IMAGE:                quay.io/cephcsi/cephcsi:canary
      ROOK_CSI_REGISTRAR_IMAGE:           quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
      ROOK_CSI_PROVISIONER_IMAGE:         quay.io/k8scsi/csi-provisioner:v1.2.0
      ROOK_CSI_SNAPSHOTTER_IMAGE:         quay.io/k8scsi/csi-snapshotter:v1.1.0
      ROOK_CSI_ATTACHER_IMAGE:            quay.io/k8scsi/csi-attacher:v1.1.1
```
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph/daemon-base:latest-nautilus-devel
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.1.4     True        False         74m     Cluster version is 4.1.4

**Comment by nehaberry** [comment]
[logs.zip](https://github.com/rook/rook/files/3416140/logs.zip)

**Comment by nehaberry** [comment]
Steps Performed:

1.  Created an OCP cluster
2. Cloned rook-ceph master branch . yamls are attached here for reference.
3. Created rook ceph cluster
    $oc create -f common.yaml
     $ oc create -f operator-openshift-with-csi.yaml
     $ oc apply -f csi/rbac/rbd ; oc apply -f csi/rbac/cephfs
     $ oc create -f cluster.yaml.

We didn't  make any changes in the above yamls.
[yamls.zip](https://github.com/rook/rook/files/3416339/yamls.zip)

**Comment by nehaberry** [comment]
Please note: On changing the rook image to "rook/ceph:v1.0.4" in operator-openshift-with-csi.yaml, all mon and ceph pods came up. 

Hence, the problem is introduced in latest **rook/ceph:master** image

$ oc describe pod rook-ceph-operator-869b77695c-t5j44 -n rook-ceph|grep Image
    Image:         rook/ceph:v1.0.4
    Image ID:      docker.io/rook/ceph@sha256:823c302113bd1a6d97ce18685888962192adf18cccecec53143ca897fdf6fd47

**Comment by leseb** [comment]
Can we get the logs from the init container `chown-container-data-dir`? Thanks.

**Comment by nehaberry** [comment]
> Can we get the logs from the init container `chown-container-data-dir`? Thanks.

I deleted the setup. 
BTW, since the mon pod was stuck in Init failure, I was not able to collect any log from that pod. So how would I have collected the log from the "chown-container-data-dir" ? Please help as to how to get this specific log

**Error from server (BadRequest): container "mon" in pod "rook-ceph-mon-a-7bcd58b586-4mbjh" is waiting to start: PodInitializing**

**Comment by nehaberry** [comment]
@leseb  will sharing the setup info help ? If yes, let me know, I shall share it on PM .

Thanks,
Neha

**Comment by leseb** [comment]
@nehaberry typically you should be able to get the log using `-c chown-container-data-dir`.

**Comment by umangachapagain** [comment]
@leseb I see
```
oc logs rook-ceph-mon-a-65b9d47854-wjqdw -c chown-container-data-dir                                                  
failed to change ownership of '/var/lib/ceph/mon/ceph-a' from root:root to ceph:ceph
chown: changing ownership of '/var/lib/ceph/mon/ceph-a': Permission denied

```

**Comment by nehaberry** [comment]
[nberry@localhost logs]$ **oc get scc  rook-ceph -o yaml**
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: []
allowedFlexVolumes:
- driver: ceph.rook.io/rook
- driver: ceph.rook.io/rook-ceph
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  creationTimestamp: "2019-07-22T08:38:06Z"
  generation: 1
  name: rook-ceph
  resourceVersion: "63141"
  selfLink: /apis/security.openshift.io/v1/securitycontextconstraints/rook-ceph
  uid: 06eab455-ac5c-11e9-af3a-0a0c1609d552
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:rook-ceph:rook-ceph-system
- system:serviceaccount:rook-ceph:default
- system:serviceaccount:rook-ceph:rook-ceph-mgr
- system:serviceaccount:rook-ceph:rook-ceph-osd
volumes:
- configMap
- downwardAPI
- emptyDir
- flexVolume
- hostPath
- persistentVolumeClaim
- projected
- secret



[nberry@localhost logs]$ **oc get scc  rook-ceph-csi -o yaml**
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedFlexVolumes:
- driver: ceph.rook.io/rook
- driver: ceph.rook.io/rook-ceph
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups: []
kind: SecurityContextConstraints
metadata:
  creationTimestamp: "2019-07-22T08:38:06Z"
  generation: 1
  name: rook-ceph-csi
  resourceVersion: "63144"
  selfLink: /apis/security.openshift.io/v1/securitycontextconstraints/rook-ceph-csi
  uid: 0715f494-ac5c-11e9-af3a-0a0c1609d552
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:rook-ceph:rook-csi-rbd-plugin-sa
- system:serviceaccount:rook-ceph:rook-csi-rbd-provisioner-sa
- system:serviceaccount:rook-ceph:rook-csi-rbd-attacher-sa
- system:serviceaccount:rook-ceph:rook-csi-cephfs-plugin-sa
- system:serviceaccount:rook-ceph:rook-csi-cephfs-provisioner-sa
volumes:
- '*'

**Comment by yeganx** [comment]
same issue need help...

**Comment by pranavgaikwad** [comment]
I am seeing this issue on OpenShift 4.1.0 env deployed using `openshift-install`.

**Comment by leseb** [comment]
@yeganx @pranavgaikwad if you look at this issue, you will see that a PR with a fix is attached to it.

**Comment by pranavgaikwad** [comment]
@leseb thank you for such a quick turnaround. cheers !

**Comment by jasonbrooks** [comment]
I'm getting a similar with the rook-ceph-mgr pod. I want to test with privileged but I can't figure out how to change / override the operator! :)

```
  Warning  FailedPostStartHook  3m23s (x3 over 4m46s)  kubelet, worker-1.XXXXX  Exec lifecycle hook ([chown --recursive --verbose ceph:ceph /var/log/ceph]) for Container "mgr" in Pod "rook-ceph-mgr-a-64b9ff4898-b6ks6_rook-ceph(bd3390c5-accc-11e9-8c13-0cc47af7a78e)" failed - error: command 'chown --recursive --verbose ceph:ceph /var/log/ceph' exited with 1: chown: changing ownership of '/var/log/ceph': Permission denied
, message: "failed to change ownership of '/var/log/ceph' from root:root to ceph:ceph\nchown: changing ownership of '/var/log/ceph': Permission denied\n"
```

**Comment by travisn** [comment]
@leseb We need the fix like #3487 for all daemons, not just the mons, right? Otherwise, any of the chowing will fail on the logging host paths, for example for mgr and mds as well, right?

**Comment by leseb** [comment]
@jasonbrooks last fix here: https://github.com/rook/rook/pull/3498

**Comment by leseb** [comment]
Closing since https://github.com/rook/rook/issues/3499

**Comment by mhcastro** [comment]
@leseb at all, I think this issue needs to be re-opened. Noticed the error again ... but now on OpenShift 4.8.25. I used the latest code base from yesterday, Feb 8th 2021. 

```
oc logs rook-ceph-mon-a-6449746d58-7dc9c -c chown-container-data-dir -n rook-ceph
chown: changing ownership of '/var/log/ceph': Permission denied
failed to change ownership of '/var/log/ceph' from root:root to ceph:ceph
failed to change ownership of '/var/lib/ceph/crash' from root:root to ceph:ceph
chown: changing ownership of '/var/lib/ceph/crash': Permission denied
chown: changing ownership of '/var/lib/ceph/mon/ceph-a': Permission denied
failed to change ownership of '/var/lib/ceph/mon/ceph-a' from root:root to ceph:ceph
```

**Comment by mhcastro** [comment]
Found the fix. Need to change the `ROOK_HOSTPATH_REQUIRES_PRIVILEGED` value from `false` to `true` in the `operator.yaml`.
