### ISSUE TITLE
The customized ceph mgr port ( except 8443 ) is not working

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#3508]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
1). The dashboard can't be accessed if the mgr's port is configured as 8444.
2). With port "8444" the mgr pod log still shows serving on 8443.
<
[23/Jul/2019:15:54:58] ENGINE Started monitor thread '_TimeoutMonitor'.
[23/Jul/2019:15:54:58] ENGINE Serving on :::9283
[23/Jul/2019:15:54:58] ENGINE Bus STARTED
[23/Jul/2019:15:54:58] ENGINE Bus STARTING
[23/Jul/2019:15:54:58] ENGINE Started monitor thread '_TimeoutMonitor'.
[23/Jul/2019:15:54:58] ENGINE Serving on :::8443
[23/Jul/2019:15:54:58] ENGINE Bus STARTED

3). With port "8444" configured, the operator pod log shows correct port.
<
2019-07-23 17:37:32.485922 I | exec: Running command: ceph config set mgr.a mgr/dashboard/server_port 8444 --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/334100903

**Expected behavior:**
The dashboard port can be customized to be other port that's not 8443.
**How to reproduce it (minimal and precise):**

1). Deploy the regulster ceph cluster with dashport port "8444". The cephcluster has below config.
<
dashboard:
enabled: true
port: 8444
ssl: true
network:
hostNetwork: false

2). The service port is correctly configured.
<
$ kubectl -n rook-ceph get svc
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
rook-ceph-mgr ClusterIP 10.254.6.95 9283/TCP 4h52m
rook-ceph-mgr-dashboard ClusterIP 10.254.127.77 8444/TCP 4h52m
rook-ceph-mgr-dashboard-external NodePort 10.254.182.118 8444:31705/TCP 4h54m
rook-ceph-mon-a ClusterIP 10.254.42.221 6789/TCP,3300/TCP 4h54m
rook-ceph-mon-b ClusterIP 10.254.255.125 6789/TCP,3300/TCP 4h54m
rook-ceph-mon-c ClusterIP 10.254.152.224 6789/TCP,3300/TCP 4h53m
rook-ceph-rgw-rook-ceph-store ClusterIP 10.254.148.253 8080/TCP 4h51m

Note: The same deployment is successful with dashboard port "8443".

**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): centos 7
* Kernel (e.g. `uname -a`): 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 
* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod): v1.02
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.1
* Kubernetes version (use `kubectl version`): 1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

  cluster:
    id:     bcf1b712-1655-4f11-9d21-7a4e0e108b13
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 3h)
    mgr: a(active, since 3h)
    osd: 4 osds: 4 up (since 5h), 4 in (since 5h)
    rgw: 1 daemon active (radosgw.gateway)
 
  data:
    pools:   7 pools, 700 pgs
    objects: 202 objects, 4.1 KiB
    usage:   4.0 GiB used, 72 GiB / 76 GiB avail
    pgs:     700 active+clean

**Comment by noahdesu** [comment]
see: https://github.com/rook/rook/issues/3603
