### ISSUE TITLE
OSD Pod marked OUT immediately after creation and cleaned

### ISSUE THREAD

**Issue by umangachapagain** [rook/rook#3521]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSD got created and immediately terminated.

**Expected behavior:**
OSD once created should not be terminated immediately after creation.

**How to reproduce it (minimal and precise):**

Deploy rook/ceph:master on OCP 4.1. Create a ceph cluster and add disk after that.

**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
``` 2019-07-24 14:32:46.037192 I | op-osd: starting 0 osd daemons on node ip-10-0-154-87 2019-07-24 14:32:46.817564 I | op-osd: osd orchestration status for node ip-10-0-173-96 is computingDiff 2019-07-24 14:32:46.860323 I | op-osd: osd orchestration status for node ip-10-0-173-96 is orchestrating 2019-07-24 14:32:47.692036 I | op-osd: osd orchestration status for node ip-10-0-173-96 is completed 2019-07-24 14:32:47.692062 I | op-osd: starting 0 osd daemons on node ip-10-0-173-96 2019-07-24 14:33:04.468759 I | op-osd: osd orchestration status for node ip-10-0-138-2 is completed 2019-07-24 14:33:04.468784 I | op-osd: starting 1 osd daemons on node ip-10-0-138-2 2019-07-24 14:33:04.487880 I | op-osd: started deployment for osd 0 (dir=false, type=) 2019-07-24 14:33:04.495679 I | op-osd: 3/3 node(s) completed osd provisioning 2019-07-24 14:33:04.495747 I | op-osd: checking if any nodes were removed 2019-07-24 14:33:04.515317 I | op-osd: processing 0 removed nodes 2019-07-24 14:33:04.515338 I | op-osd: done processing removed nodes 2019-07-24 14:33:04.515357 I | exec: Running command: ceph versions --connect-timeout=15 --cluster=openshift-storage --conf=/var/lib/rook/openshift-storage/openshift-storage.config --keyring=/var/lib/rook/openshift-storage/client.admin.keyring 2019-07-24 14:33:05.902851 I | op-osd: completed running osds in namespace openshift-storage 2019-07-24 14:33:05.902901 I | rbd-mirror: configure rbd-mirroring with 0 workers 2019-07-24 14:33:05.909079 I | rbd-mirror: no extra daemons to remove 2019-07-24 14:33:05.909098 I | op-cluster: Done creating rook instance in namespace openshift-storage 2019-07-24 14:33:06.175036 I | op-osd: osd.0 is marked 'DOWN' 2019-07-24 14:33:06.175165 I | exec: Running command: ceph osd safe-to-destroy 0 --connect-timeout=15 --cluster=openshift-storage --conf=/var/lib/rook/openshift-storage/openshift-storage.config --keyring=/var/lib/rook/openshift-storage/client.admin.keyring --format json --out-file /tmp/056501664 2019-07-24 14:33:06.650451 I | op-osd: osd.0 is 'safe-to-destroy' 2019-07-24 14:33:06.657487 I | op-k8sutil: removing deployment rook-ceph-osd-0 if it exists 2019-07-24 14:33:06.670869 I | op-k8sutil: Removed deployment rook-ceph-osd-0 2019-07-24 14:33:06.678753 I | op-k8sutil: rook-ceph-osd-0 still found. waiting... 2019-07-24 14:33:08.844663 I | op-k8sutil: rook-ceph-osd-0 still found. waiting... 2019-07-24 14:33:10.857051 I | op-k8sutil: rook-ceph-osd-0 still found. waiting... 2019-07-24 14:33:12.862797 I | op-k8sutil: confirmed rook-ceph-osd-0 does not exist W0724 14:37:25.000912 6 reflector.go:289] github.com/rook/rook/pkg/operator/ceph/cluster/controller.go:159: watch of *v1.ConfigMap ended with: too old resource version: 150299 (154420) 2019-07-24 14:37:26.003235 I | op-cluster: device lists are equal. skipping orchestration 2019-07-24 14:37:26.003358 I | op-cluster: device lists are equal. skipping orchestration 2019-07-24 14:37:26.003525 I | op-cluster: device lists are equal. skipping orchestration 2019-07-24 14:38:13.408001 I | op-osd: osd.0 is marked 'DOWN' 2019-07-24 14:38:13.408126 I | exec: Running command: ceph osd safe-to-destroy 0 --connect-timeout=15 --cluster=openshift-storage --conf=/var/lib/rook/openshift-storage/openshift-storage.config --keyring=/var/lib/rook/openshift-storage/client.admin.keyring --format json --out-file /tmp/340746126 2019-07-24 14:38:13.854989 I | op-osd: osd.0 is 'safe-to-destroy' ```
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@rohan47 Looks like cleaning up the OSDs is too aggressive. Instead of adding back in something that keeps track for how long the osd has been out, what if we checked on the age of the pod? For example, when we get the deployment [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/health.go#L117) to delete it, we could check its age. If it's "new", we should not remove it. 

The next question is what the heuristic should be for "new", for example if its CreationTimestamp is less than an hour or two old.

**Comment by rohan47** [comment]
> @rohan47 Looks like cleaning up the OSDs is too aggressive. Instead of adding back in something that keeps track for how long the osd has been out, what if we checked on the age of the pod? For example, when we get the deployment [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/health.go#L117) to delete it, we could check its age. If it's "new", we should not remove it.
> 
Yes makes sense
> The next question is what the heuristic should be for "new", for example if its CreationTimestamp is less than an hour or two old.

I guess we should at least wait for around 20 to 30 min, Need suggestions here

**Comment by travisn** [comment]
I'd suggest we set the default to an hour
