### ISSUE TITLE
Rancher: wrong directory being used and FlexVol doc wrong

### ISSUE THREAD

**Issue by MaxDiOrio** [rook/rook#3522]
Rancher 2.3-alpha5, but this existed long before this version.

Documentation is wrong here:  https://rook.io/docs/rook/v1.0/flexvolume.html

Rancher's default FlexVol path is /var/lib/kubelet/volumeplugins

During Rook Operator Deployment, specify :

env:
[...]
- name: FLEXVOLUME_DIR_PATH
  value: "/var/lib/kubelet/volumeplugins"

(In the operator.yaml manifest replace <PathToFlexVolumes> with the path or if you use helm set the agent.flexVolumeDirPath to the FlexVolume path)

Plus, when the csi-cephfsplugin and csi-rbdplugin containers come up, they are using the wrong directory as well.

MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory

MountVolume.SetUp failed for volume "pods-mount-dir" : hostPath type check failed: /var/lib/kubelet/pods is not a directory

These directories don't exist on the RKE created worker nodes.  The equivalent path on RKE provisioned nodes is /opt/rke/var/lib/kubelet/pods/

On my RKE provisioned node, it is /opt/rke/var/lib/kubelet/pods/

**Comment by kd7lxl** [comment]
Thanks for this report. I'm seeing the same behavior with microk8s installed via snap. The paths differ and need to be overridden. Where is `/var/lib/kubelet/pods` defined? I can't figure out where to override it.

**Comment by mrvnklm** [comment]
@kd7lxl @MaxDiOrio Did you guys figure out a workaround? I am facing the same issue.

**Comment by Madhu-1** [comment]
if you are using cephcsi and kubelet dir is other than `/var/lib/kubelet` you need to configure https://github.com/rook/rook/blob/release-1.1/cluster/examples/kubernetes/ceph/operator.yaml#L184-L186 in operator

**Comment by yannleretaille** [comment]
As far as i can see the current doc on master has not changed, not sure if closing this was right.

**Comment by galexrt** [comment]
Reopening.

We are happy to see a PR to update the docs with the Rancher specific Flexvolume plugin directory and / or the CSI directory.

**Comment by stepanselyuk** [comment]
For MicroK8s `kubelet` path is `/var/snap/microk8s/common/var/lib/kubelet/`
need to change in `operator.yaml` (change and uncomment), or add in the deployment of the root-ceph-operator:
```
- name: ROOK_CSI_KUBELET_DIR_PATH
              value: /var/snap/microk8s/common/var/lib/kubelet/
```

**Comment by travisn** [comment]
@stepanselyuk We should really create a help topic for CSI configuration similar to the [flex configuration page](https://rook.github.io/docs/rook/v1.3/flexvolume.html) to include details like this for different platforms. Would you mind opening a new issue for that?

**Comment by stepanselyuk** [comment]
@travisn ok sure, created https://github.com/rook/rook/issues/5752
