### ISSUE TITLE
Add Prometheus support to Rook Operator

### ISSUE THREAD

**Issue by teralype** [rook/rook#3524]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add Prometheus support to the Rook Operator so that the operator itself can be monitored using Prometheus.

**What is use case behind this feature:**
I can't seem to find a way to monitor the Rook Operator using kube-prometheus because it does not `/metrics` (mostly because it does not expose any port).

All my attempts at creating a Kubernetes headless service and its Endpoint are fruitless. Prometheus detects the Rook Operator using Service Discovery but it always reports a target count of 0. I believe this is because there is no port to connect to.

I suggest that basic Prometheus exporter code is added to Rook Operator. Essentially, something like up/down, heathy/unhealthy, uptime in milliseconds, could be enough.

**Comment by chicofranchico** [comment]
Do we have any way to monitor the Rook operator itself?
