### ISSUE TITLE
Ceph NFS fails to start on OpenShift

### ISSUE THREAD

**Issue by travisn** [rook/rook#3525]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
NFS fails to start on OpenShift due to the recent change to run as the ceph user.

For example, the pod `rook-ceph-nfs-my-nfs-a-57bfb4bc95-sncvg` is in pending state due to:
```
Reason:       Error 
     Message:      failed to write connection config. failed to write keyring to /var/lib/rook/smoke-ns. failed to write monitor keyring to /var/lib/rook/smoke-ns/client.admin.keyring: ope
n /var/lib/rook/smoke-ns/client.admin.keyring: permission denied
```

**Expected behavior:**
The NFS pod spec needs the following, similar to #3498 
```
SecurityContext: PodSecurityContext(),
Lifecycle: opspec.PodLifeCycle(""),
```

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
No more reports of this, let's reopen if we can get a repro.

**Comment by likid0** [comment]
Hi,

I'm seeing rook-ceph-nfs CrashLoopBackOff on the  nfs-ganesha containers running OCP 4.2.2 and rook out of the master branch.

The config-init container runs and completes ok, but the nfs-ganesha cotainer fails with the following log:

$ oc logs pod/rook-ceph-nfs-my-nfs-a-55d54597c4-m2j6p -c nfs-ganesha
18/11/2019 13:28:07 : epoch 5dd29c67 : rook-ceph-nfs-my-nfs-a-55d54597c4-m2j6p : nfs-ganesha-1[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.8.1.2
18/11/2019 13:28:07 : epoch 5dd29c67 : rook-ceph-nfs-my-nfs-a-55d54597c4-m2j6p : nfs-ganesha-1[main] main :MAIN :FATAL :Can't open pid file /var/run/ganesha.pid for writing

Any chance this can be related?.

Thanks.


[output-logs-nfs-rook.txt](https://github.com/rook/rook/files/3858831/output-logs-nfs-rook.txt)

**Comment by leseb** [comment]
> Hi,
> 
> I'm seeing rook-ceph-nfs CrashLoopBackOff on the nfs-ganesha containers running OCP 4.2.2 and rook out of the master branch.
> 
> The config-init container runs and completes ok, but the nfs-ganesha cotainer fails with the following log:
> 
> $ oc logs pod/rook-ceph-nfs-my-nfs-a-55d54597c4-m2j6p -c nfs-ganesha
> 18/11/2019 13:28:07 : epoch 5dd29c67 : rook-ceph-nfs-my-nfs-a-55d54597c4-m2j6p : nfs-ganesha-1[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.8.1.2
> 18/11/2019 13:28:07 : epoch 5dd29c67 : rook-ceph-nfs-my-nfs-a-55d54597c4-m2j6p : nfs-ganesha-1[main] main :MAIN :FATAL :Can't open pid file /var/run/ganesha.pid for writing
> 
> Any chance this can be related?.
> 
> Thanks.
> 
> [output-logs-nfs-rook.txt](https://github.com/rook/rook/files/3858831/output-logs-nfs-rook.txt)

This seems unrelated to the original issue but there is clearly a problem. AFAIK `/var/run` is not bindmounted so any process should have access to it and thus be able to write a file.
Can reproduce this all the time?

Thanks.

**Comment by likid0** [comment]
> This seems unrelated to the original issue but there is clearly a problem. AFAIK `/var/run` is not bindmounted so any process should have access to it and thus be able to write a file.
> Can you reproduce this all the time?
> 
> Thanks.

Hi,

Yes, I have done a several installs on different envs and hitting the same issue all the time.

Like you mention, It seems just an issue that the user doesn't have perms to write to the /run fs.

[root@helper ceph]# oc debug pod/rook-ceph-nfs-my-nfs-a-55d54597c4-bzs4j  -c  nfs-ganesha
Starting pod/rook-ceph-nfs-my-nfs-a-55d54597c4-bzs4j-debug, command was: ganesha.nfsd -F -L STDERR
If you don't see a command prompt, try pressing enter.
sh-4.2$ id
uid=1000550000(1000550000) gid=0(root) groups=0(root),1000550000
sh-4.2$ ganesha.nfsd -F -L STDERR
01/12/2019 10:47:45 : epoch 5de39a51 : rook-ceph-nfs-my-nfs-a-55d54597c4-bzs4j-debug : nfs-ganesha-9[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.8.1.2
01/12/2019 10:47:45 : epoch 5de39a51 : rook-ceph-nfs-my-nfs-a-55d54597c4-bzs4j-debug : nfs-ganesha-9[main] main :MAIN :FATAL :Can't open pid file /var/run/ganesha.pid for writing

If started in debug mode with root user, it works like expected:

[root@helper ceph]# oc debug deployment/rook-ceph-nfs-my-nfs-a -c nfs-ganesha
Starting pod/rook-ceph-nfs-my-nfs-a-debug, command was: ganesha.nfsd -F -L STDERR
If you don't see a command prompt, try pressing enter.
sh-4.2# id
uid=0(root) gid=0(root) groups=0(root)
sh-4.2# ganesha.nfsd -F -L STDERR
01/12/2019 10:54:05 : epoch 5de39bcd : rook-ceph-nfs-my-nfs-a-debug : nfs-ganesha-8[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.8.1.2
01/12/2019 10:54:05 : epoch 5de39bcd : rook-ceph-nfs-my-nfs-a-debug : nfs-ganesha-8[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
.........
nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
01/12/2019 10:54:08 : epoch 5de39bcd : rook-ceph-nfs-my-nfs-a-debug : nfs-ganesha-8[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
01/12/2019 10:54:08 : epoch 5de39bcd : rook-ceph-nfs-my-nfs-a-debug : nfs-ganesha-8[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------

Regards.

**Comment by leseb** [comment]
@likid0 in your debug in non-root can you try setting `-p /var/run/ganesha/ganesha.pid` to the `ganesha.nfsd` CLI? Thanks

**Comment by likid0** [comment]
> -p /var/run/ganesha/ganesha.pid

sh-4.2$ ls -lZ / | grep run
drwxr-xr-x. root root system_u:object_r:container_file_t:s0:c5,c25 run
sh-4.2$ ls -lZ /var/ | grep run
lrwxrwxrwx. root root system_u:object_r:container_file_t:s0:c5,c25 lock -> ../run/lock
lrwxrwxrwx. root root system_u:object_r:container_file_t:s0:c5,c25 run -> ../run
sh-4.2$ ganesha.nfsd -F -L STDERR -p /var/run/ganesha/ganesha.pid
02/12/2019 13:37:12 : epoch 5de51388 : rook-ceph-nfs-my-nfs-a-55d54597c4-mqd4s-debug : nfs-ganesha-78[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.8.1.2
02/12/2019 13:37:12 : epoch 5de51388 : rook-ceph-nfs-my-nfs-a-55d54597c4-mqd4s-debug : nfs-ganesha-78[main] main :MAIN :FATAL :Can't open pid file /var/run/ganesha/ganesha.pid for writing

ganesha dir in /var/run is also configured with root 

sh-4.2$ ls -l /var/run/ | grep ganesha
drwxr-xr-x. 2 root    root             6 Jul 21 20:22 ganesha
sh-4.2$ 


If using another dir for the pid.

sh-4.2$ ganesha.nfsd -F -p /tmp/nfsd.pid  -L STDERR 
02/12/2019 13:50:42 : epoch 5de516b2 : rook-ceph-nfs-my-nfs-a-55d54597c4-mqd4s-debug : nfs-ganesha-23[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.8.1.2
02/12/2019 13:50:43 : epoch 5de516b2 : rook-ceph-nfs-my-nfs-a-55d54597c4-mqd4s-debug : nfs-ganesha-23[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
02/12/2019 13:50:43 : epoch 5de516b2 : rook-ceph-nfs-my-nfs-a-55d54597c4-mqd4s-debug : nfs-ganesha-23[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
02/12/2019 13:50:43 : epoch 5de516b2 : rook-ceph-nfs-my-nfs-a-55d54597c4-mqd4s-debug : nfs-ganesha-23[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
02/12/2019 13:50:43 : epoch 5de516b2 : rook-ceph-nfs-my-nfs-a-55d54597c4-mqd4s-debug : nfs-ganesha-23[main] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
02/12/2019 13:50:46 : epoch 5de516b2 : rook-ceph-nfs-my-nfs-a-55d54597c4-mqd4s-debug : nfs-ganesha-23[main] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE

Regards.

**Comment by leseb** [comment]
Ok so it seems `ganesha.nfsd` is not able to run with a different user than root. @likid0 pointed to https://github.com/nfs-ganesha/nfs-ganesha/issues/426. So we should wait a bit. In the meantime, my patch should solve your issue.
