### ISSUE TITLE
csi pv creation error: failed to provision volume with StorageClass "csi-cephfs": rpc error: code = InvalidArgument desc = error creating a temporary keyfile (open /tmp/csi/keys/keyfile-853935555: no such file or directory)

### ISSUE THREAD

**Issue by yydzhou** [rook/rook#3531]
Searched online, but didn't find similar report. was able to succeed yesterday. today just retry same code, then failed. After failure, pulled the most recent code and still see the issue. 

**Is this a bug report or feature request?**
* Bug Report
**Deviation from expected behavior:**

**Expected behavior:**
Expecting the pv creation success
**How to reproduce it (minimal and precise):**

On the rook master. Just follow the follow steps 
**using the most recent rook master repo.**
kubectl create -f “${rook_example}/common.yaml”
kubectl create -f “${rook_example}/csi/rbac/cephfs/”
kubectl create -f “${rook_example}/csi/rbac/rbd/”
kubectl create -f “${rook_example}/operator-with-csi.yaml”

wait for ready, then
kubectl create -f “${rook_example}/cluster.yaml”
kubectl create -f “${rook_example}/filesystem.yaml”

---
create secret
```
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
stringData:
  adminID: admin
  adminKey: AQAPMTpdTXRPDBAAM+f3tA9A5J8VWJr6t0EJ3Q==
```
and then

 kubectl create -f ${rook_example}/csi/example/cephfs/storageclass.yaml
 kubectl create -f ${rook_example}/csi/example/cephfs/pvc.yaml

**Environment**:
3-node:ec2-instance k8s cluster. 

** logs from csi-provisioner **
I0726 00:41:59.658453       1 controller.go:1196] provision "default/cephfs-pvc" class "csi-cephfs": started
I0726 00:41:59.662537       1 controller.go:442] CreateVolumeRequest {Name:pvc-e242c5a6-af33-11e9-b486-064517ab9db2 CapacityRange:required_bytes:1073741824  VolumeCapabilities:[mount:<fs_type:"ext4" mount_flags:"noexec" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[clusterID:rook-ceph csi.storage.k8s.io/node-stage-secret-name:csi-cephfs-secret csi.storage.k8s.io/node-stage-secret-namespace:default csi.storage.k8s.io/provisioner-secret-name:csi-cephfs-secret csi.storage.k8s.io/provisioner-secret-namespace:default fsName:myfs pool:myfs-data0] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0726 00:41:59.662686       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"cephfs-pvc", UID:"e242c5a6-af33-11e9-b486-064517ab9db2", APIVersion:"v1", ResourceVersion:"14450", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/cephfs-pvc"
I0726 00:41:59.663817       1 connection.go:180] GRPC call: /csi.v1.Controller/CreateVolume
I0726 00:41:59.663830       1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-e242c5a6-af33-11e9-b486-064517ab9db2","parameters":{"clusterID":"rook-ceph","fsName":"myfs","pool":"myfs-data0"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["noexec"]}},"access_mode":{"mode":1}}]}
I0726 00:41:59.666836       1 connection.go:183] GRPC response: {}
I0726 00:41:59.667155       1 connection.go:184] GRPC error: rpc error: code = InvalidArgument desc = error creating a temporary keyfile (open /tmp/csi/keys/keyfile-797660088: no such file or directory)
I0726 00:41:59.667191       1 controller.go:979] Final error received, removing PVC e242c5a6-af33-11e9-b486-064517ab9db2 from claims in progress
W0726 00:41:59.667200       1 controller.go:886] Retrying syncing claim "e242c5a6-af33-11e9-b486-064517ab9db2", failure 23
E0726 00:41:59.667215       1 controller.go:908] error syncing claim "e242c5a6-af33-11e9-b486-064517ab9db2": failed to provision volume with StorageClass "csi-cephfs": rpc error: code = InvalidArgument desc = error creating a temporary keyfile (open /tmp/csi/keys/keyfile-797660088: no such file or directory)
I0726 00:41:59.667236       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"cephfs-pvc", UID:"e242c5a6-af33-11e9-b486-064517ab9db2", APIVersion:"v1", ResourceVersion:"14450", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-cephfs": rpc error: code = InvalidArgument desc = error creating a temporary keyfile (open /tmp/csi/keys/keyfile-797660088: no such file or directory)

**Comment by Madhu-1** [comment]
Fixed in #3528
