### ISSUE TITLE
rook will not ignore nbd block device

### ISSUE THREAD

**Issue by james58899** [rook/rook#3540]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook refresh ceph cluster on mount volume using nbd block device

**Expected behavior:**
RBD can mount using nbd, so rook should be ignore nbd device and skip refresh cluster

**How to reproduce it (minimal and precise):**

Using ceph-csi and set mounter to rbd-nbd, rook will refresh ceph cluster every time mount volume.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
* Kernel (e.g. `uname -a`): 4.15.0-55-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.0.0-312.ge5779f7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph 14.2.2
* Kubernetes version (use `kubectl version`): 1.14.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by noahdesu** [comment]
This can be fixed by adding a regex string to match on ndb and ignore such updates. Here is where we do the same thing for RBD https://github.com/rook/rook/blob/master/pkg/daemon/discover/discover.go#L172.

I'll note that this might be a good time to factor out this ignore list and put it in the CRD so we can control this without altering any code.

**Comment by umangachapagain** [comment]
> I'll note that this might be a good time to factor out this ignore list and put it in the CRD so we can control this without altering any code.

What are your thoughts on this? @travisn @BlaineEXE @leseb

**Comment by noahdesu** [comment]
@umangachapagain see:

https://github.com/rook/rook/issues/3033
https://github.com/rook/rook/pull/3032/files#r277854515

**Comment by BlaineEXE** [comment]
Having the udev filtering be configurable seems a good decision to me.

**Comment by BlaineEXE** [comment]
Is this in progress and near ready for review? How important is this to the 1.1 release?

**Comment by BlaineEXE** [comment]
In 1.1: add `nbd` to the filter
For 1.2: implement the more configurable solution
