### ISSUE TITLE
Client Code Generation for Python 

### ISSUE THREAD

**Issue by sebastian-philipp** [rook/rook#3543]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Automatically generate Python client code

**What is use case behind this feature:**
Rook APIs are brittle
https://github.com/rook/rook/pull/3283#issuecomment-516419300
https://github.com/ceph/ceph/commit/4a45b67a8c8b079a373e334f8bfd72cd97259853
was never implemented in https://github.com/rook/rook/pull/1900

My hand-crafted approach is https://github.com/sebastian-philipp/rook-ceph-client-python which already helped me to quickly verify the CRD validations.

I'm open for suggestions. Looks like everyone else is leveraging swagger-codegen. But haven't looked into this, yet.

Relates to 

* https://github.com/kubeflow/tf-operator/issues/167
* https://github.com/kubernetes-client/gen/issues/59
* #3534
* #3526
* #3480

**Comment by travisn** [comment]
This is done and the python generation now lives in https://github.com/rook/rook-client-python
