### ISSUE TITLE
OSD maintenance impossible due to OSD daemon running (legacy bluestore statfs)

### ISSUE THREAD

**Issue by mumrau** [rook/rook#3552]
Hello everyone.

**What happened?**
I upgraded on one of my clusters the ceph version, from `v14.2.1-20190430` to `v14.2.2-20190722`, the upgrade was rolled-out flawlessly by the operator. It might be important to note that the cluster has previously been upgraded from `v13.x`, under which it was created.
Nonetheless, a few warnings appeared, all of them were extremely easy to fix except for one: ```BLUESTORE_LEGACY_STATFS: Legacy BlueStore stats reporting detected on 3 OSD(s)```.

**What is happening?**
The documentation is extremely clear about the warning (thanks ceph for that): https://docs.ceph.com/docs/master/rados/operations/health-checks/#bluestore-legacy-statfs 
This is where it hurts, in order to proceed withe the `ceph-bluestore-tool repair --path ...`, you need to have the `osd` stopped or halted, otherwise you get: ```error from fsck: (11) Resource temporarily unavailable
2019-07-31 14:43:08.473 7f7d6cc5bf00 -1 bluestore(/var/lib/ceph/osd/ceph-0) _lock_fsid failed to lock /var/lib/ceph/osd/ceph-0/fsid (is another ceph-osd still running?)(11) Resource temporarily unavailable```
I tried doing so in the container, but because of the `chroot` I'm getting the following message: `Running in chroot, ignoring request.`.

I felt like I needed to reproduce the volume mounts and disk state on the host, but I couldn't do so, I am both too scared of breaking something down and shattering my entire cluster, or to just completely destroy the node itself.

I'm using entire devices mounted on `vdb`, see the according part of the cluster CRD definition:
```
storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    devices:
    - name: "vdb"
    config:
      metadataDevice:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
```

**What do you expect?**
I expect a way to perform maintenant on a pod, especially for the OSDs. The monitors and manager are easy to replace and roll, but the OSD are very static by nature.
I thought about changing the deployment itself to replace the container command (the one initiated by `tini`) in order for it to hold on, for me to get into a `kubectl exec` and do my things before rolling back to the old deployment. Maybe it could be something we could explore. A way to replicate OSD file system without starting the `osd` daemon, on another container for maintenance.

I'm really looking forward to see how we can deal with this, the feature provided by the new bluestore stats looks great on a distributed environment, and I'm sure future updates of `ceph` could bring other situations where a similar maintenance would be useful.

It was hard to name this issue, feel free to categorize it/propose renaming.
Regards.

**Environment**:
* OS (e.g. from /etc/os-release): debian 9
* Kernel (e.g. `uname -a`): 4.9.0-7-amd64
* Cloud provider or hardware configuration: bare-metal kubernetes
* Rook version (use `rook version` inside of a Rook Pod):  v1.0.2
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)
* Kubernetes version (use `kubectl version`): 1.15.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal, kubeadm governed setup
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):HEALTH_WARN Legacy BlueStore stats reporting detected on 3 OSD(s)

**Comment by travisn** [comment]
@mumrau The approach for this issue with the osd warning is outlined in #3539 as it was just discovered a couple days ago from the v14.2.2 release. For now it is safe to ignore the warning, but we need to get the full solution automated since as you noted the osd maintenance is challenging today. Could you review #3539? thanks!

**Comment by mumrau** [comment]
Damn it's exactly what I wanted to underline.
I apologize, I started writing this issue 4 days ago but it took time for me to start playing around and I haven't done a new research before posting the issue.
I'm closing this one in favor of #3539 . Thanks.
