### ISSUE TITLE
[DOC] Create a 'simple' try-it configuration

### ISSUE THREAD

**Issue by iranzo** [rook/rook#3570]
**Is this a bug report or feature request?**
* Feature Request

Documentation and webpage at rook.io includes a 'try it' link which points to the github repo.

**What should the feature do:**

It should point to a step-by-step to  test rook on a demo environment with whatever links might be needed to 'dig deeper' on that area, but still provide a simple scenario to test.

**What is use case behind this feature:**

As a new user, approaching rook, seems a bit frustrating not finding that information, different documents, documentation points to latest, but then warns about using latest,etc.

It should be more consistent to allow 'non-devel' users to test the technology in a similar way to what kubevirt.io offers with the 'try-it' and 'labs' section

**Environment**:

**Comment by travisn** [comment]
@iranzo Agreed, the "Try it out now" should point to the quickstart guides, similar to the "Get Started" link in the top right corner of [rook.io](https://rook.io). Thanks for pointing this out!

**Comment by iranzo** [comment]
Want me to PR it?

**Comment by travisn** [comment]
@iranzo Yes, thanks! You probably already found it, but the website repo is here: https://github.com/rook/rook.github.io

**Comment by jbw976** [comment]
Fixed in https://github.com/rook/rook.github.io/pull/68
