### ISSUE TITLE
Orchestration is Add/Update/Delete triggered. It should check current state of the system.

### ISSUE THREAD

**Issue by rohantmp** [rook/rook#3577]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The orchestrators I've seen in the code all have different behaviour for Add/Update/Delete generated by a kubernetes client-go informer. The informer's [event handler](https://godoc.org/k8s.io/client-go/tools/cache#ResourceEventHandler) documentation states that several events are often coalesced, and events are sometimes missed. Most of our implementations of the update event handler check if the oldObj and the newObj are equal and skip if they are. There is a possibility that the client might miss this event.

I expect that restarting the operator pod will work as a workaround for most missed triggers.

I believe that this is the root cause of #2977, and undiscovered others.

**Expected behavior:**

The Kubernetes [controller pattern](https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-how-do-i-have-different-logic-in-my-reconciler-for-different-types-of-events-eg-create-update-delete) is to verify the actual state of the system each time.

I also do not know if simply triggering a check every time we get a cache event will be too noisy. The [controller-runtime library](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg) has some good abstractions over client-go for queuing reconcile requests in response to watched objects. It also suppoprts an arbitrary mapping between watched objects to reconcile functions. 

**How to reproduce it (minimal and precise):**

I believe that every orchestrator using this mechanism can unexpectedly fail to trigger in an unpredictable way. 

**Examples**:

https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/controller.go#L418
https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/controller.go#L622

Search the codebase for `UpdateFunc:`, and you'll find many examples of this practice.

**Comment by rohantmp** [comment]
I'm currently implementing a controller for [managedPDBs](https://github.com/rook/rook/blob/master/design/ceph-managed-disruptionbudgets.md). I'm going to follow the current goroutine pattern while accounting for coalesced update events.

Eventually, I want to propose a design for a new framework within rook for a controller-runtime based controllers. We can then slowly move the reconcile logic of orchestrators to this. I'm not sure how necessary this will prove. I also do not know how much time I will be able to spend on implementing this in the near future.

**Comment by mmack** [comment]
I'm not sure if that fits here but i always wondered what the reason is that rook creates multiple deployments for example for the mons and does not use kubernetes default ways of doing it. Like a deployment or daemonset for all mons...

I think it would remove a lot of "scheduling" complexity of the operator... But maybe there's a damn good reason for this i'm currently not aware of...

**Comment by rohantmp** [comment]
The managed PDBs PR #3596 will introduce a pattern within rook to shift controllers to switch from informers to controller-runtime controllers.
