### ISSUE TITLE
Cannot delete persistent volume when Ceph cluster is full

### ISSUE THREAD

**Issue by aplex** [rook/rook#3579]
Our test cluster filled up, and I want to delete some PVCs to free up the space. However, volumes cannot be deleted by rook with a message "not enough space left".  StorageClass reclaim policy is set to "Delete", so I would expect them to be immediately deleted from Ceph. But, from the logs it looks like Rook is trying to move them to some kind of recycle bin, instead of deleting them.

I'm running the version from master branch, as 1.0.4 version seems to be unusable on OKD due to https://github.com/rook/rook/issues/3140

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Volumes cannot be deleted when cluster is full.

**Expected behavior:**
I would expect that it would be possible to delete volumes from Ceph cluster when it is full. Otherwise, it is unclear how to recover from the full-cluster situation.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7.6
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: OKD 3.11
* Rook version (use `rook version` inside of a Rook Pod): v1.0.0-331.g7fb43d7
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.2
* Kubernetes version (use `kubectl version`): 1.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OKD (OpenShift)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_ERR 2 full osd(s); 1 nearfull osd(s); 1 pool(s) full; Degraded data redundancy: 14062/670125 objects degraded (2.098%), 4 pgs degraded, 4 pgs undersized; Degraded data redundancy (low space): 4 pgs backfill_toofull

```
kubectl get pv pvc-c6726862-b7d2-11e9-b851-4cd98f507b2b -o yaml                                                                              (default/vb0610-halxg-cloudera-com:8443/system:admin/alexanderprokofiev-scout)
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: ceph.rook.io/block
  creationTimestamp: "2019-08-05T22:45:57Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-c6726862-b7d2-11e9-b851-4cd98f507b2b
  resourceVersion: "2349014"
  selfLink: /api/v1/persistentvolumes/pvc-c6726862-b7d2-11e9-b851-4cd98f507b2b
  uid: ca431c01-b7d2-11e9-b851-4cd98f507b2b
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: worker-24-worker-20190805224528-0-ceph-ssd
    namespace: xxxx
    resourceVersion: "2007541"
    uid: c6726862-b7d2-11e9-b851-4cd98f507b2b
  flexVolume:
    driver: ceph.rook.io/rook-ceph
    fsType: xfs
    options:
      clusterNamespace: rook-ceph
      dataBlockPool: ""
      image: pvc-c6726862-b7d2-11e9-b851-4cd98f507b2b
      pool: ceph-ssd-pool
      storageClass: ceph-ssd
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ceph-ssd
status:
  phase: Released
```

From operator logs:

```
2019-08-06 18:36:06.232582 I | op-provisioner: Deleting volume pvc-c6726862-b7d2-11e9-b851-4cd98f507b2b
2019-08-06 18:36:06.232608 I | exec: Running command: rbd rm ceph-ssd-pool/pvc-c6726862-b7d2-11e9-b851-4cd98f507b2b --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring
E0806 18:36:06.349282       8 controller.go:1356] delete "pvc-c6726862-b7d2-11e9-b851-4cd98f507b2b": volume deletion failed: Failed to delete rook block image ceph-ssd-pool/pvc-c6726862-b7d2-11e9-b851-4cd98f507b2b: failed to delete image pvc-c6726862-b7d2-11e9-b851-4cd98f507b2b in pool ceph-ssd-pool: Failed to complete '': exit status 2. 2019-08-06 18:36:06.341 7f0246ffd700 -1 librbd::trash::MoveRequest: 0x555b1d867200 handle_trash_add: failed to add image to trash: (28) No space left on device
```

Storage class:
```
Name:            ceph-ssd
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"ceph-ssd"},"parameters":{"blockPool":"ceph-ssd-pool","clusterNamespace":"rook-ceph","fstype":"xfs"},"provisioner":"ceph.rook.io/block","reclaimPolicy":"Delete"}

Provisioner:           ceph.rook.io/block
Parameters:            blockPool=ceph-ssd-pool,clusterNamespace=rook-ceph,fstype=xfs
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

```

**Comment by candlerb** [comment]
I found a solution for this situation thanks to some [IBM documentation](https://www.ibm.com/docs/en/storage-ceph/6?topic=osds-deleting-data-from-full-storage-cluster):

* Check the osd full_ratio: `ceph osd dump | grep full_ratio`
* The default should be 0.95. Temporarily increase it to 0.97: `ceph osd set-full-ratio 0.97`
* Watch the cluster state with `ceph -w`
* When the cluster is healthy again, delete volume(s) as required to reduce storage utilisation (I don't know if rook will keep retrying automatically, or you'll need to `rbd rm ...` yourself)
* Revert the full_ratio: `ceph osd set-full-ratio 0.95`
