### ISSUE TITLE
Unable to mount volume for pod - mount command failed, structure needs cleaning

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#3580]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The pod failed to mount its pvc after restarting randomly
**Expected behavior:**
The pod should be able to mount its pvc after restarting consistently

**How to reproduce it (minimal and precise):**

The similar issue has been in discussion in rook slack ( https://app.slack.com/client/T47C56S7Q/C46Q5UC05/thread/C46Q5UC05-1563182392.429800 ).
The conclusion seems ending with "kubelet-wrapper". Unfortunately, we have the same issue without using kubelet-wrapper. 

Important note: The test done by @nikvoss indicating it's not PVC issue but the pod mounting issue, which caused by kubernetes wrapper.  
``
Ok, so I might have found the culprit:
1. I deleted an affected pod multiple times (belonging to a statefulset) and was able to reproduce the mount issues
2. Scheduled a test pod to node which does NOT use the CoreOS kubelet-wrapper, which mounts the affected PVC (from pod above)
3. Deleted affected pod again and cleaned up mounts manually
4. Test pod was able to mount the PVC, once pod was deleted umount was working without issues
5. Affected pod on different host still had mount issues afterwards
=> So without the kubelet-wrapper I am unable to reproduce the issues. So the root cause might the the rkt container and mount redundancy because of it.

``
'
[Service]
ExecStart=/usr/local/bin/kubelet \
  --pod-infra-container-image=registry:5000/gcr.io/google-containers/pause-amd64:3.1 \
  --kubeconfig=/etc/kubernetes/kubelet.kubeconfig \
  --config=/etc/kubernetes/kubelet-config.yml \
  --client-ca-file=/etc/kubernetes/ssl/ca.pem \
  --register-node=true \
  --rotate-certificates \
  --node-labels=is_control=true,is_worker=false,is_edge=false,is_storage=true,bcmt_storage_node=true \
  --register-with-taints=is_control=true:NoExecute \
  --allow-privileged=true \
  --docker-root=/data0/docker \
  --node-ip=172.16.1.26 \
  --network-plugin=cni \
  --cni-bin-dir=/opt/cni/bin \
  --cni-conf-dir=/etc/cni/kubernetes \
  --cloud-provider=openstack \
  --cloud-config=/etc/kubernetes/cloud.conf \
  --v=1
'

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

- Failure symptom 1: 
`
Message:      error setting label on mount source '/var/lib/kubelet/pods/4f13766a-b837-11e9-a2ce-fa163ef27ec8/volumes/ceph.rook.io~rook-ceph-system/pvc-176a8bb5-a22c-11e9-af13-fa163e3d4ff7': no such file or directory
`
-  Failure symptom 2:
`
  Warning  FailedMount  6m49s (x663 over 29h)  kubelet, neolab2-worker-01  Unable to mount volumes for pod
"csf-compaas-cluster-belk-elasticsearch-data-0_paas(446fc2d4-b76d-11e9-a2ce-fa163ef27ec8)": timeout expired waiting for volumes to attach or mount for
pod "paas"/"csf-compaas-cluster-belk-elasticsearch-data-0". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir ssl
searchguard-config elasticsearch-backup default-token-dffmn]
  Warning  FailedMount  113s (x980 over 29h)   kubelet, neolab2-worker-01  (combined from similar events): MountVolume.SetUp failed for volume
"pvc-174a1721-a22c-11e9-af13-fa163e3d4ff7" : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd3 [xfs] to
/var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-174a1721-a22c-11e9-af13-fa163e3d4ff7, error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for
/var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-174a1721-a22c-11e9-af13-fa163e3d4ff7 --scope -- mount -t xfs -o rw,defaults /dev/rbd3
/var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-174a1721-a22c-11e9-af13-fa163e3d4ff7
Output: Running scope as unit run-23989.scope.
mount: mount /dev/rbd3 on /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-174a1721-a22c-11e9-af13-fa163e3d4ff7 failed: Structure needs
cleaning
`
 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7
* Kernel (e.g. `uname -a`):3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod): v0.9.3
* Storage backend version (e.g. for ceph do `ceph -v`):  v13.2.4-20190109
* Kubernetes version (use `kubectl version`): v1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by RiaanLab** [comment]
Same here 
K8s 1.13.3 and rook 1.02

**Comment by noahdesu** [comment]
fyi @yanchicago use three single quotes instead of one when pasting logs: ``` ```

**Comment by yanchicago** [comment]
@noahdesu Any additional log you need?

**Comment by noahdesu** [comment]
@yanchicago no, sorry if i wasn't clear. in your post it is difficult to read the log output because you've used inline-style single quotes. using three single quotes will retain the new lines.

**Comment by yanchicago** [comment]
Can someone help to take a look at the issue? It blocks our field deployment.

**Comment by MichaelJiangPlus** [comment]
I also encountered this problem, and even more unfortunately the problem occurred in my production system.When I create a new pv, pvc, it works fine, but when I mount the previous pv, pvc, everything is messed up.

Environment:

- OS (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
- Kernel (e.g. uname -a):Linux BlackWalnutLabs-Headquarters004 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Cloud provider or hardware configuration: Super micro
- Rook version (use rook version inside of a Rook Pod): v0.9.0-329.gc696ce2
- Storage backend version (e.g. for ceph do ceph -v): ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)
- Kubernetes version (use kubectl version): v1.13.4
- Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
- Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox): HEALTH_OK

This is the output of the log：
```bash
Volumes:
  volume-michaeljiang:
    Type:        PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:   claim-michaeljiang
    ReadOnly:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age   From                                Message
  ----     ------       ----  ----                                -------
  Normal   Scheduled    36s   default-scheduler                   Successfully assigned online-labs/jupyter-michaeljiang to blackwalnutlabs-heroes002
  Warning  FailedMount  35s   kubelet, blackwalnutlabs-heroes002  MountVolume.SetUp failed for volume "pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110" : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd1 [xfs] to /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110, error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110 --scope -- mount -t xfs -o rw,defaults /dev/rbd1 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110
Output: Running scope as unit: run-r9ef3524762274456b5ee61aa75d08d6a.scope
mount: /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110: mount(2) system call failed: Structure needs cleaning.
  Warning  FailedMount  34s  kubelet, blackwalnutlabs-heroes002  MountVolume.SetUp failed for volume "pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110" : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd1 [xfs] to /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110, error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110 --scope -- mount -t xfs -o rw,defaults /dev/rbd1 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110
Output: Running scope as unit: run-rbdf2c2c1417941bc9d2b70cb153264b2.scope
mount: /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110: mount(2) system call failed: Structure needs cleaning.
  Warning  FailedMount  32s  kubelet, blackwalnutlabs-heroes002  MountVolume.SetUp failed for volume "pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110" : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd1 [xfs] to /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110, error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110 --scope -- mount -t xfs -o rw,defaults /dev/rbd1 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110
Output: Running scope as unit: run-r4ae409e1ee114dd98e1addab022f0044.scope
mount: /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110: mount(2) system call failed: Structure needs cleaning.
  Warning  FailedMount  30s  kubelet, blackwalnutlabs-heroes002  MountVolume.SetUp failed for volume "pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110" : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd1 [xfs] to /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110, error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110 --scope -- mount -t xfs -o rw,defaults /dev/rbd1 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110
Output: Running scope as unit: run-ra973dc47ae4240b4b44357ff78c73755.scope
mount: /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110: mount(2) system call failed: Structure needs cleaning.
  Warning  FailedMount  25s  kubelet, blackwalnutlabs-heroes002  MountVolume.SetUp failed for volume "pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110" : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd1 [xfs] to /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110, error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110 --scope -- mount -t xfs -o rw,defaults /dev/rbd1 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110
Output: Running scope as unit: run-r965509731edd46b1b5900a155408b8aa.scope
mount: /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110: mount(2) system call failed: Structure needs cleaning.
  Warning  FailedMount  17s  kubelet, blackwalnutlabs-heroes002  MountVolume.SetUp failed for volume "pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110" : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd1 [xfs] to /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110, error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110 --scope -- mount -t xfs -o rw,defaults /dev/rbd1 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110
Output: Running scope as unit: run-r6574f721c431424b9a24366bb711ccb7.scope
mount: /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110: mount(2) system call failed: Structure needs cleaning.
  Warning  FailedMount  0s  kubelet, blackwalnutlabs-heroes002  MountVolume.SetUp failed for volume "pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110" : mount command failed, status: Failure, reason: failed to mount volume /dev/rbd1 [xfs] to /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110, error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110 --scope -- mount -t xfs -o rw,defaults /dev/rbd1 /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110
Output: Running scope as unit: run-r813f6249f4ee414a831f092c5fbf9533.scope
mount: /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-59a842b8-5c32-11e9-adbc-0cc47ab3a110: mount(2) system call failed: Structure needs cleaning.
```

**Comment by yanchicago** [comment]
https://github.com/rook/rook/issues/2899
The above issue is also related.

**Comment by yanchicago** [comment]
[https://github.com/rook/rook/pull/3955](url)

**Comment by yanchicago** [comment]
[https://github.com/rook/rook/pull/3755](url)

**Comment by yanchicago** [comment]
The volume corruption observed again. And the volume can be reused after repair. 
Is it possible that rook agent overwrites some part of the volume during detach/attach? 

----------------------------------------------------------------------------------------------------
$ ls -l /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/
ls: cannot access /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-592c03d5-be72-11e9-a59e-fa163efb7ca9: Input/output error
total 0
d????????? ? ? ? ?            ? pvc-592c03d5-be72-11e9-a59e-fa163efb7ca9

$ ls -l /var/lib/kubelet/pods/6965b8c6-de1f-11e9-a59e-fa163efb7ca9/volumes/ceph.rook.io~rook-ceph-system/
ls: cannot access
/var/lib/kubelet/pods/6965b8c6-de1f-11e9-a59e-fa163efb7ca9/volumes/ceph.rook.io~rook-ceph-system/pvc-592c03d5-be72-11e9-a59e-fa163efb7ca9:
Input/output error
total 0
d????????? ? ? ? ?            ? pvc-592c03d5-be72-11e9-a59e-fa163efb7ca9

**Comment by travisn** [comment]
@yanchicago This sounds similar to #3298 which has been elusive to track down with the flex driver. Is it possible for you to test with the [CSI driver](https://rook.io/docs/rook/v1.1/ceph-block.html) instead of flex?

**Comment by yanchicago** [comment]
@travisn Thanks for your quick response. Is there an upgrade path from flex to CSI? Flex deployment is already in the fields.

**Comment by volvicoasis** [comment]
Hello, same, here in production due to pods evictions. some of pvc was corrupted, so we lost data with xfs repair. Do you think we can have same behaviour with ext4 ?

CentOS Linux 7 (Core)
Linux  3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
ceph HEALTH_OK
kube : v1.14.6
rook: v0.9.0-102.g8e263cd
ceph version 13.2.2 (02899bfda814146b021136e9d8e80eba494e1126) mimic (stable)

`6874583.869725] XFS (rbd9): Corruption warning: Metadata has LSN (121:19456) ahead of current LSN (91:17152). Please unmount and run xfs_repair (>= v4.3) to resolve.
[6874583.869838] XFS (rbd9): Metadata corruption detected at xfs_agi_read_verify+0x5e/0x110 [xfs], xfs_agi block 0x2
[6874583.871768] XFS (rbd9): Unmount and run xfs_repair
[6874583.871941] XFS (rbd9): First 64 bytes of corrupted metadata buffer:
[6874583.872088] ffff8a2fe773b400: 58 41 47 49 00 00 00 01 00 00 00 00 00 04 fc 00  XAGI............
[6874583.872272] ffff8a2fe773b410: 00 00 00 80 00 00 00 03 00 00 00 01 00 00 00 2b  ...............+
[6874583.872519] ffff8a2fe773b420: 00 00 20 40 ff ff ff ff ff ff ff ff ff ff ff ff  .. @............
[6874583.872718] ffff8a2fe773b430: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff  ................
[6874583.872956] XFS (rbd9): metadata I/O error: block 0x2 ("xfs_trans_read_buf_map") error 117 numblks 1
[6874583.873603] XFS (rbd9): xfs_do_force_shutdown(0x1) called from line 370 of file fs/xfs/xfs_trans_buf.c.  Return address = 0xffffffffc068b28a
[6874583.882316] XFS (rbd9): I/O Error Detected. Shutting down filesystem
[6874583.882740] XFS (rbd9): Please umount the filesystem and rectify the problem(s)
`

**Comment by yanchicago** [comment]
We were able to reproduce the issue and observed the volume detach and attach activities in the agents. The application pod was evicted from node 20 and started on node 10. 
**Agent 20 did the "unmount" 1 second **after** the agent 10 updated the volume attachment.**  

The related code ( v0.9.3) is at  "controller.go". The "orphaned" is incorrect as the dying pod is still working on the cleanup. Wait for a few cycles on checking the pod still exists. Then update if the pod goes away or error on timeout.   
```
if err != nil || (attachment.PodNamespace == attachOpts.PodNamespace && attachment.PodName == attachOpts.Pod) {
					if err != nil && !errors.IsNotFound(err) {
						return fmt.Errorf("failed to get pod CRD %s/%s. %+v", attachment.PodNamespace, attachment.PodName, err)
					}

					logger.Infof("volume attachment record %s/%s is orphaned. Updating record with new attachment information for pod %s/%s", volumeattachObj.Namespace, volumeattachObj.Name, attachOpts.PodNamespace, attachOpts.Pod)
```



agent 20 logs:
``` 
2019-10-02 04:28:24.435349 I | flexdriver: unmounting mount dir: /var/lib/kubelet/pods/deda737c-dbc0-11e9-9ea9-9cb65498ca68/volumes/ceph.rook.io~rook-ceph-system/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68
2019-10-02 04:28:24.615601 I | flexvolume: deleting attachment for mountDir /var/lib/kubelet/pods/deda737c-dbc0-11e9-9ea9-9cb65498ca68/volumes/ceph.rook.io~rook-ceph-system/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 from Volume attach CRD rook-ceph-system/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68
2019-10-02 04:28:24.620273 E | flexdriver: Unmount volume /var/lib/kubelet/pods/deda737c-dbc0-11e9-9ea9-9cb65498ca68/volumes/ceph.rook.io~rook-ceph-system/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 failed: volume CRD pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 found but attachment to the mountDir
/var/lib/kubelet/pods/deda737c-dbc0-11e9-9ea9-9cb65498ca68/volumes/ceph.rook.io~rook-ceph-system/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 was not found
2019-10-02 04:28:24.620414 I | flexdriver:
2019-10-02 04:28:24.620588 I | flexdriver: volume has been unmounted from /var/lib/kubelet/pods/deda737c-dbc0-11e9-9ea9-9cb65498ca68/volumes/ceph.rook.io~rook-ceph-system/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68
```
agent 10 logs:
```
2019-10-02 04:28:23.856329 I | flexdriver: calling agent to attach volume replicapool/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68
2019-10-02 04:28:23.863110 I | flexvolume: volume attachment record rook-ceph-system/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 exists for pod:
paas/csf-compaas-cluster-belk-elasticsearch-data-1
**2019-10-02 04:28:23.880543 I | flexvolume: volume attachment record rook-ceph-system/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 is orphaned. Updating record with new attachment information for pod paas/csf-compaas-cluster-belk-elasticsearch-data-1**
2019-10-02 04:28:23.888594 I | rook-ceph-agent-crd: updated Volumeattach CRD pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68
2019-10-02 04:28:23.888945 I | ceph-volumeattacher: attaching volume replicapool/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 cluster rook-ceph
2019-10-02 04:28:23.900461 I | cephmon: parsing mon endpoints: a=10.254.173.204:6790,b=10.254.189.165:6790,c=10.254.158.167:6790
2019-10-02 04:28:23.900589 I | op-mon: loaded: maxMonID=2, mons=map[a:0xc000a91ba0 b:0xc000a91be0 c:0xc000a91c20], mapping=&{Node:map[a:0xc000a95a70
b:0xc000a95b00 c:0xc000a95b30] Port:map[]}
2019-10-02 04:28:23.901958 I | exec: Running command: rbd map replicapool/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 --id=admin --cluster=rook-ceph
--keyring=/tmp/rook-ceph.keyring081947002 -m 10.254.173.204:6790,10.254.189.165:6790,10.254.158.167:6790 --conf=/dev/null
2019-10-02 04:28:26.294131 I | flexdriver:
2019-10-02 04:28:26.294438 I | flexdriver: Ignore error about Mount failed: exit status 32. Kubernetes does this to check whether the volume has been formatted.
It will format and retry again. https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/util/mount/mount_linux.go#L360
2019-10-02 04:28:26.294721 I | flexdriver: formatting volume pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 devicePath /dev/rbd0 deviceMountPath
/var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 fs xfs with options [rw]
2019-10-02 04:28:26.295073 I | flexdriver: mounting global mount path
/var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 on
/var/lib/kubelet/pods/121a1023-e4cd-11e9-9ea9-9cb65498ca68/volumes/ceph.rook.io~rook-ceph-system/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68
2019-10-02 04:28:26.321037 I | flexdriver:
2019-10-02 04:28:26.321265 I | flexdriver: volume replicapool/pvc-ded99f7f-dbc0-11e9-9ea9-9cb65498ca68 has been attached and mounted
```

**Comment by solovyevt** [comment]
Why is this issue closed? Still facing it
