### ISSUE TITLE
After operator restart, orchestration gets stuck if a mon is down

### ISSUE THREAD

**Issue by travisn** [rook/rook#3583]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When the operator restarts, an orchestration is triggered to ensure the cluster is in the desired state. If a mon is down, the orchestration is blocked from continuing and will attempt indefinitely to check if a mon can be stopped. The check is in case there is an upgrade, but there is no upgrade in this scenario. 

**Expected behavior:**
The orchestration should be allowed to complete as long as there is sufficient mon quorum.

**How to reproduce it (minimal and precise):**

- Start the cluster
- Cause a mon to go down (e.g. set its deployment replica count to 0)
- Restart the operator

See attached log of the operator retrying to start the cluster and finally gives up.
[MonDownBlocksOrchestration.log](https://github.com/rook/rook/files/3475137/MonDownBlocksOrchestration.log)

**Comment by mmack** [comment]
@travisn can you please try that with v1.0.4 again?
It looks pretty similar to my issue #3575. Wonder what happens with the cluster if you use that image.
However the image you're using here v1.0.0-319.g48c4fedd4 is not on dockerhub, so i can't do the cross check...

**Comment by noahdesu** [comment]
I think there is another failure mode I've been seeing that is very closely related. Start a new cluster but arrange for the monitors to not come up. This could simulate some storage issue, for example. After timeouts occur and one tries to resolve this potentially be restarting the operator, the cluster will enter a state I was never able to get it out of.

It appears to believe that a monitor exists, but cannot actually interact with it (e.g. to get version info on early operator startup). Deleting the monitor deployment doesn't resolve this issue either.

**Comment by travisn** [comment]
This particular issue is related to #2901, which is only in master and not backported to 1.0. But I'm looking at #3575 now too!

**Comment by leseb** [comment]
This is tricky, the error looks valid to me since one monitor is down. It's hard to detect that this is an operator restart and we shouldn't be doing anything and simply proceed. Let me look into this.

**Comment by travisn** [comment]
I see this as a critical issue for production and blocker for v1.1. I just hit this again in my test environment when testing mon failover. While my repro was contrived (deleted a mon deployment), in a production cluster a mon could be down for another reason.

An important point to consider is that it is common for the operator to run an orchestration even though something unrelated changed. The orchestration could be triggered when the operator is restarted, or when a device is detected (for deploying an OSD), or a new node was added to the cluster. In this case, there is no update to the mons, yet this check is still performed for ok-to-stop on the mons. There is no need for the orchestration to check it and block the orchestration. The mons won't actually be restarted in this case.

Even if a mon is down and we are updating the cluster, I don't think we should block the orchestration. The upgrade guide tells him to check the health status before he starts. But if the user chose to start an upgrade, we should honor that desired state even if the cluster is in an unhealthy state.

In this case, my mon would be healed if the orchestration were allowed to continue and attempt to start the mon again that is down. But when the orchestration is blocked, we don't have an opportunity to heal it. And in this test cluster there isn't even a realistic way to even heal that mon unless the orchestration is allowed to continue. 

One way to help the situation would be to re-order the mons so that if a mon is down, we try to heal that one first. Currently we are just starting with a random mon, which was healthy for me, and cannot be taken down because of the down mon which we haven't attempted to heal yet. But even so, if we have mon quorum currently, we should be allowed to continue. This behavior was introduced in a v0.9 patch release that really improved operator reliability. 

@leseb How can we make this ok-to-stop check more flexible while still retaining the benefits of #2901?

**Comment by leseb** [comment]
@travisn working on it!
