### ISSUE TITLE
Please update the NFS Docker Image with latest Version

### ISSUE THREAD

**Issue by gauravbist** [rook/rook#3588]
I found that Rook NFS  image still using the Old version of NFS-Ganesh ver 2.5.5

https://github.com/rook/rook/blob/master/images/nfs/Dockerfile

"&& echo "deb http://ppa.launchpad.net/gluster/nfs-ganesha-2.5/ubuntu xenial main" > /etc/apt/sources.list.d/nfs-ganesha-2.5.list \ "

Could you please update it with latest version:
Link: https://launchpad.net/~nfs-ganesha/+archive/ubuntu/nfs-ganesha-2.8
"ppa:nfs-ganesha/nfs-ganesha-2.8"

**Comment by leseb** [comment]
Which image are you looking at? If you use  `ceph/ceph:v14.2.2-20190722`, you will see the right version.

```
[root@624eeab67113 /]# rpm -qa|grep ganesha
nfs-ganesha-2.8.1.2-0.1.el7.x86_64
nfs-ganesha-rgw-2.8.1.2-0.1.el7.x86_64
nfs-ganesha-rados-grace-2.8.1.2-0.1.el7.x86_64
nfs-ganesha-ceph-2.8.1.2-0.1.el7.x86_64
```

We don't have Ubuntu images AFAIK.
I'm closing this, feel free to re-open if you have any more concerns.
