### ISSUE TITLE
osdsPerDevice config is broken after commit f3ef680

### ISSUE THREAD

**Issue by nktpro** [rook/rook#3599]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
osdsPerDevice is broken after this commit:

https://github.com/rook/rook/commit/f3ef680298c8b3da6aa09a52f028ee492cbccf0c

which was due to this change:

https://github.com/rook/rook/commit/f3ef680298c8b3da6aa09a52f028ee492cbccf0c#diff-715ffbe3e68cc184a213d04310c8e811R500

which was a variable scoping bug. `count` is always `1` in all constructed strings in `deviceNames` as a result.

**Expected behavior:**
osdsPerDevice should be respected.

**How to reproduce it (minimal and precise):**
Deploy rook on any version after the commit above and set `osdsPerDevice` to any value that isn't default of `1`

CC @mvollman

**Comment by mvollman** [comment]
@nktpro My apologies for missing the variable scoping.  I will have a patch up to correct the issue shortly.
