### ISSUE TITLE
RBD storageclass name in examples directory needs to be changed to csi-rbd

### ISSUE THREAD

**Issue by netzzer** [rook/rook#3615]
The storageclass name in ~/rook/cluster/examples/kubernetes/ceph/csi/rbd in storageclass.yaml and storageclass-test.yaml needs to be changed from 'rook-ceph-block' to 'csi-rbd', This storageclass name is consistent with 'csi-cephfs' and is used in the pod.yaml example in ~/rook/cluster/examples/kubernetes/ceph/csi/rbd.

**Comment by leseb** [comment]
It looks like a different approach was taken here: https://github.com/rook/rook/pull/3618/files
I'm closing this, feel free to re-open if you have any more concerns.

Closed by https://github.com/rook/rook/pull/3618
