### ISSUE TITLE
ceph slow performance

### ISSUE THREAD

**Issue by majian159** [rook/rook#3619]
cephfs pv 10mb/s,is this normal?
![image](https://user-images.githubusercontent.com/10176784/62995923-421b4a00-be95-11e9-8eff-cdfc53311154.png)
![image](https://user-images.githubusercontent.com/10176784/62995930-4d6e7580-be95-11e9-8502-edc77b7b82b9.png)

**Comment by Madhu-1** [comment]
this is PVC created by cephfs CSI?

**Comment by majian159** [comment]
node > node iperf3 test result:

![image](https://user-images.githubusercontent.com/10176784/62996036-c53ca000-be95-11e9-9a0e-14c7bf4f7d9e.png)

node dd test result:
![image](https://user-images.githubusercontent.com/10176784/62996061-dbe2f700-be95-11e9-9a5a-c800e0c3d4a7.png)

**Comment by majian159** [comment]
@Madhu-1 ye, storageclass yaml is:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2019-08-13T13:11:05Z"
  name: csi-cephfs
  resourceVersion: "26491325"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/csi-cephfs
  uid: cea81845-bdcb-11e9-b7f7-0cda411d7ac1
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-ceph-csi
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-ceph-csi
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  fsName: cephfs
  pool: cephfs-data0
provisioner: cephfs.csi.ceph.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

**Comment by Madhu-1** [comment]
@majian159 thanks for the info. is this related to https://github.com/rook/rook/issues/3315 ?

**Comment by majian159** [comment]
thanks, much like, i should update centos7 kernel to >=4.17 and set mounter: kernel?
@Madhu-1

**Comment by Madhu-1** [comment]
yes, look like that's the suggestion.

**Comment by majian159** [comment]
thank you very much, i try.
@Madhu-1

**Comment by majian159** [comment]
I upgraded the kernel to 5.x to solve this problem. If you use cephfs in a low kernel version, you can only use flexvolume.
RBD volume has no such troubles.

**Comment by masantiago** [comment]
@majian159 , did you install csi plugin using helm? Can you advise?

**Comment by gemfield** [comment]
With kernel 5.3.0-26-generic and kernel client, I got a 25x IO performance improvement. Here is a brief report: https://zhuanlan.zhihu.com/p/81417869
