### ISSUE TITLE
Perf test and analysis of reads

### ISSUE THREAD

**Issue by jbw976** [rook/rook#363]
With bluestore now doing async IO (https://github.com/ceph/ceph/pull/13066), we should test and analyze read performance again

**Comment by jbw976** [comment]
the read async IO changes have been backported to rook.  we can test a build with https://github.com/rook/ceph/commit/6d8d69fc8655ad89bb194de98ca99e02fc780454

**Comment by bassam** [comment]
also here https://github.com/ceph/ceph/pull/13210

**Comment by jbw976** [comment]
Partially blocked by #374

**Comment by jbw976** [comment]
closing this old perf issue.  block testing performance will be a focus in the 0.7+ roadmap and we will get new tickets opened soon with our current direction and plans.
