### ISSUE TITLE
Ceph CSI -pidlimit flag "not defined" error

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#3635]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
`csi-cephfsplugin-provisioner` and `csi-rbdplugin-provisioner` containers fail with message
```
flag provided but not defined: -pidlimit
Usage of /usr/local/bin/cephcsi:
  -alsologtostderr
    	log to standard error as well as files
  -containerized
    	whether run as containerized (default true)
  -drivername string
    	name of the driver
  -endpoint string
    	CSI endpoint (default "unix://tmp/csi.sock")
  -instanceid string
    	Unique ID distinguishing this instance of Ceph CSI among other instances, when sharing Ceph clusters across CSI instances for provisioning
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -log_file string
    	If non-empty, use this log file
  -log_file_max_size uint
    	Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
    	log to standard error instead of files (default true)
  -metadatastorage string
    	metadata persistence method [node|k8s_configmap]
  -mountcachedir string
    	mount info cache save dir
  -nodeid string
    	node id
  -pluginpath string
    	the location of cephcsi plugin (default "/var/lib/kubelet/plugins/")
  -skip_headers
    	If true, avoid header prefixes in the log messages
  -skip_log_headers
    	If true, avoid headers when opening log files
  -stderrthreshold value
    	logs at or above this threshold go to stderr (default 2)
  -type string
    	driver type [rbd|cephfs]
  -v value
    	number for the log level verbosity
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
  -volumemounter string
    	default volume mounter (possible options are 'kernel', 'fuse')
```

**How to reproduce it (minimal and precise):**
Install Rook master using default `operator.yaml` and `cluster.yaml`.

**File(s) to submit**:
**Environment**:
* OS (e.g. from /etc/os-release): openSUSE Leap 15.0
* Kernel (e.g. `uname -a`): Linux k8s-master-0 4.12.14-lp150.12.67-default #1 SMP Tue Jul 9 08:18:26 UTC 2019 (b610084) x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: libvirt
* Rook version (use `rook version` inside of a Rook Pod): v1.0.0-410.g07b56fb8
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.2
* Kubernetes version (use `kubectl version`): v1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by galexrt** [comment]
Interesting to see this after #3565 is already merged since two days.
Is there a Ceph CSI release that needs to be done for it to work? @Madhu-1

**Comment by Madhu-1** [comment]
@BlaineEXE do you have latest docker image in your environment?

**Comment by BlaineEXE** [comment]
> @BlaineEXE do you have latest docker image in your environment?

I don't know. Possibly not, but the user shouldn't have to manually update images to get a working environment. How can we make sure this doesn't happen for users?

**Comment by galexrt** [comment]
@BlaineEXE as far as I can tell, that is right now becuase `quay.io/cephcsi/cephcsi:canary` is used.
For `1.1` and already hopefully soon `master` that `canary` will be changed to, e.g., `v1.0.0` (and increased on every Ceph CSI release).

**Comment by trotyoung** [comment]
I have the same issue, do you find a workaround? I think the docker image was the problem .

**Comment by Madhu-1** [comment]
a workaround will be manually pulling cephcsi docker image on all nodes
