### ISSUE TITLE
CRUSH map should have option to be based on nodes for OSDs on PVs

### ISSUE THREAD

**Issue by travisn** [rook/rook#3648]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
When OSDs are based on PVs, the CRUSH map currently uses the name of the PVC in place of the host. This has the assumption that the OSDs will be portable across hosts. For example, in AWS or VMWare, the devices are not tied to a node and could move with the pod during maintenance.

However, in some scenarios, the PVs underlying OSDs will be tied to the hosts, such as when using the local provisioner. In this case there will be benefits of using the host name in the CRUSH map. For example, during maintenance, all the OSDs on the host could be marked as `noout` while the node is being upgraded. 

Since Rook will not be able to predict when the PVs will be tied to a node, we can expose a new property on the `StorageClassDeviceSet` named `portable`:
- `true`: The CRUSH map will use the PVC name in place of the host (already the behavior with the OSDs on PVCs)
- `false`: The CRUSH map will use the host name (the traditional behavior)
- unspecified: When the setting is not defined, the operator could make its best guess. For example if the storage class name includes the substring "local", it would set this to false, otherwise set it to true. In particular, this default would give the behavior for the `local-storage` storage class.

**What is use case behind this feature:**
Improved CRUSH map behavior depending on the environment.

@rohan47 Could you take a look at this?

**Comment by rohantmp** [comment]
Additional requirements for CRUSH and OSD:

- The OSD should be labeled with the value if it's portable or not.
- The OSD should expose in the label which failure domain it's in.
