### ISSUE TITLE
OSD pods went into crashloopbackoff when pvc are deleted

### ISSUE THREAD

**Issue by prsurve** [rook/rook#3651]
**Is this a bug report or feature request?**
* Bug Report

**Observed behavior:**
deleted all pvc, and osd pods went in crashloopbackoff

**Expected behavior:**
PVC should not get deleted rook should prevent deletion

**How to reproduce it (minimal and precise):**

oc create -f common.yaml
oc create -f operator-openshift.yaml
oc create -f cluster-on-pvc.yaml

oc delete pvc --all

**Comment by travisn** [comment]
There isn't a way to prevent deletion of K8s resources currently. If the admin issues a delete command, it will be deleted. We need support at the K8s for this feature. Here is a related request: https://github.com/kubernetes/kubernetes/issues/10179

**Comment by dkowsley** [comment]
Just passing through the issues list to keep up on whats going on and saw this. Running `oc delete pvc --all` blindly is an egregious misuse of the tool. This is no different than running `rm -rf /` as both `rm -rf /` and `oc delete pvc --all` are superuser-scoped commands. You can't blindly delete everything in a cluster-resource and expect the cluster to function normally.

**Comment by leseb** [comment]
This is not a Rook bug, I'm closing this. Feel free to re-open if you have any concerns.
