### ISSUE TITLE
All non-rotational devices consumed as metadataDevice when only one was specified

### ISSUE THREAD

**Issue by Confusingboat** [rook/rook#3652]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Ceph consumes all flash devices for block.db and wal when one specific device was configured as a `metadataDevice`.

**Expected behavior:**
Rook should configure Ceph to only use the device specified for block.db/wal.

**How to reproduce it (minimal and precise):**
Create a Rook Ceph cluster with two (or presumably more) non-rotational devices and one or more rotational devices, but only specify one of the flash devices to be used as the `metadataDevice` on the node.

**Other comments:**

```
c4tw8z1:~$ lsblk
NAME                                                MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                                                   8:0    0 238.5G  0 disk
└─sda1                                                8:1    0 238.5G  0 part /etc/ssl/certs/ca-certificates.crt.rancher
sdb                                                   8:16   0 372.6G  0 disk
└─ceph--block--dbs--06206d70--22ce--4a20--b035--68ad7aea3317-osd--block--db--c84de295--a8dd--4b0d--b3eb--29841b462991
                                                    252:3    0   558G  0 lvm
sdc                                                   8:32   0   9.1T  0 disk
└─ceph--block--22045f1b--507a--4f88--b078--27170fa79f40-osd--block--8e3152a5--5669--411b--93a4--c747e66dc1c3
                                                    252:2    0   9.1T  0 lvm
sdd                                                   8:48   0   9.1T  0 disk
└─ceph--block--3f4df301--a0f8--451d--b343--bf8eeee4c0cb-osd--block--43362e5b--9784--47be--a2b9--1f644ded681d
                                                    252:0    0   9.1T  0 lvm
nvme0n1                                             259:0    0 745.2G  0 disk
├─ceph--block--dbs--06206d70--22ce--4a20--b035--68ad7aea3317-osd--block--db--6c3403e9--513c--4b6d--99ee--87a7a6653f44
│                                                   252:1    0   558G  0 lvm
└─ceph--block--dbs--06206d70--22ce--4a20--b035--68ad7aea3317-osd--block--db--c84de295--a8dd--4b0d--b3eb--29841b462991
                                                    252:3    0   558G  0 lvm
```

It occurs to me there may also be more that contributed to this behavior (at least in my case), or it may be an entirely separate issue, as it looks like Rook is also not merging the cluster-level `storage.config` with my node-level `storage.node.config`, so the `databaseSizeMB` setting is getting ignored, and the metadata lvs are getting created as 50% of the sum of both non-rotational devices since there are two rotational devices. Not sure if this is intended behavior.

Based on the comments, I believe this issue may be a regression introduced by #2777 due to the apparent omission of the `--db-devices` argument when the change was made to use batch provisioning with ceph-volume, but I can't be certain because I haven't tested with a version prior to this PR. In either case, there are lots of juicy comments on this PR specifically pertaining to this issue, which appears to have been known before the PR was accepted.

Other possibly related issues: #3092, #3449

**File(s)**:
* Cluster CRD: [cluster.zip](https://github.com/rook/rook/files/3520956/cluster.zip) (use c4tw8z1 as a reference node)

**Environment**:
* OS: Rancher OS 1.5.3
* Kernel: 4.14.128-rancher
* Hardware configuration: Dell R320, 800GB NVMe, 400GB SATA SSD, 2x 10TB HDD
* Rook version: 1.0.2
* Storage backend version: Ceph v14.2.2
* Kubernetes version: 1.13.5
* Kubernetes cluster type: bare metal w/ Rancher
* Storage backend status: healthy

**Comment by travisn** [comment]
@Confusingboat This issue is known that we don't have a good way to instruct c-v on which device should be used for the db/wal. 
@mvollman Could you take a look at this? Thanks!

**Comment by mvollman** [comment]
As of ceph version 14.2.1, c-v now includes `--db-devices` and `--wal-devices` args that could be used to explicitly set `metadataDevice`, but older versions of ceph would not have support for these.  Does it make sense to use the args when available and default back to the current behavior for older ceph versions?

You are correct the node level databaseSizeMB config is currently ignored and only the cluster level config setting is used.  I can put a PR together that ensures these two settings are merged, giving preference to the more specific setting.

**Comment by Confusingboat** [comment]
I may be out of line here, but I think having the `metadataDevice` option available but no functional support for it (as is the current case) is rather silly. I think a more transparent option would be to bifurcate how metadata devices are handled based on Ceph version, and add a new, more generic config setting to the effect of `useAllNonRotationalDevicesForMetadata: true|false` that all supported versions of Ceph could use, and then reserve `metadataDevice` for versions that can support that level of specificity.

Or, if OSDs can be provisioned individually instead of as a batch, it looks like c-v lvm create/prepare has support for specifying db/wal devices per-OSD as far back as luminous.

Thanks for the feedback on the `databaseSizeMB` setting, I'll be looking forward to that so I can clean up my cluster CRD 👍

**Comment by travisn** [comment]
@Confusingboat Rook's support for metadataDevice is currently:
- metadataDevice can be specified per device (1:1)
- metadataDevice can be specified with multiple data devices (1:n)

If metadataDevice isn't specified, one OSD will be created per device, with db/wal/data all on the same device. 

To specify multiple db/wal devices we do need a newer version of ceph and a change in rook as @mvollman mentioned. Behaving differently based on the ceph version would be acceptable (and is done other places in rook)

**Comment by Confusingboat** [comment]
@travisn I think there may be a little confusion here; I understand the supported scenarios, and my intention was to leverage a single db/wal device, not multiple (1:n using an Intel P3700, which should be supported). The reason I created this issue is because Rook is not executing the config as described by the documentation.

The documentation states that a single device will be used for metadata if configured, but what actually happened was Ceph detected multiple non-rotational devices and used all of them for metadata.

I specified `metadataDevice: nvme0n1` for the node, and I want it and only it used as a db/wal device. The rest of the devices, including `sdb` (which is a SATA SSD), were supposed to be OSDs as per the `deviceFilter: ^sd[b-d]`.

**Comment by travisn** [comment]
@Confusingboat Aha, thanks for the clarification. Yeah, we definitely need to get this fixed to use the new ceph-volume options. Otherwise, ceph-volume makes the decision on its own about which volume(s) to use for the db/wal.

**Comment by mvollman** [comment]
I have a patch nearly ready that will implement `--db-devices` for ceph versions 14.2.2 and newer.   I have a few more scenarios to test before I create the PR.

**Comment by christianhuening** [comment]
not sure i am reading this right. So there's no patch coming for ceph 13.2.x ?

**Comment by travisn** [comment]
@alfredodeza is the flag `--db-devices` already backported to mimic, or planned for backport? If so, what version would include it? If so, we could update the rook version check to include that version of mimic for this feature.

**Comment by alfredodeza** [comment]
It was added to mimic in December of last year (https://github.com/ceph/ceph/commit/0c645faa845) so the most recent mimic release should have it.
