### ISSUE TITLE
Missing CRD valiation for storageClassDeviceSets

### ISSUE THREAD

**Issue by sebastian-philipp** [rook/rook#3653]
The `CephClusterCRD` doesn't have a openAPI validation specification. Not having this specification is probably going to block the Ceph orchestrator from creating those from Ceph. See 

See https://github.com/ceph/ceph/pull/29427 and #3534

@rohan47 , is this something for you?

**Comment by rohan47** [comment]
@ashishranjan738 can you have a look at this?
