### ISSUE TITLE
quay.io/k8scsi/csi-snapshotter:v1.1.1 not found

### ISSUE THREAD

**Issue by slieer** [rook/rook#3654]
**[root@serv20 ceph]# git config -l**
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/rook/rook.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
[root@serv20 ceph]# git branch
master
**[root@serv20 ceph]# git pull**
Already up-to-date.
**[root@serv20 ceph]# kubectl -n rook-ceph describe pods csi-rbdplugin-provisioner-0**
Name:           csi-rbdplugin-provisioner-0
Namespace:      rook-ceph
Priority:       0
........

Events:
  Type     Reason   Age                     From             Message
  ----     ------   ----                    ----             -------
  Normal   BackOff  5m18s (x12738 over 2d)  kubelet, serv22  Back-off pulling image "quay.io/k8scsi/csi-snapshotter:v1.1.1"
  Warning  Failed   20s (x12760 over 2d)    kubelet, serv22  Error: ImagePullBackOff
  
  
**[root@serv20 ceph]# kubectl -n rook-ceph get pod -o wide**
NAME                                  READY   STATUS             RESTARTS   AGE    IP            NODE     NOMINATED NODE   READINESS GATES
csi-cephfsplugin-27bjk                2/2     Running            0          2d1h   10.1.1.138    serv20   <none>           <none>
csi-cephfsplugin-provisioner-0        3/3     Running            0          2d1h   10.244.1.45   serv22   <none>           <none>
csi-cephfsplugin-wf8l2                2/2     Running            0          2d1h   10.1.1.141    serv21   <none>           <none>
csi-cephfsplugin-wmp4q                2/2     Running            0          2d1h   10.1.1.143    serv22   <none>           <none>
csi-rbdplugin-gjlh6                   2/2     Running            0          2d1h   10.1.1.138    serv20   <none>           <none>
csi-rbdplugin-h6z89                   2/2     Running            0          2d1h   10.1.1.143    serv22   <none>           <none>
**csi-rbdplugin-provisioner-0           3/4     ImagePullBackOff   0          2d1h   10.244.1.44   serv22   <none>           <none>**
csi-rbdplugin-ptgdj                   2/2     Running            0          2d1h   10.1.1.141    serv21   <none>           <none>
rook-ceph-agent-789ns                 1/1     Running            2          31d    10.1.1.143    serv22   <none>           <none>
rook-ceph-agent-lcntr                 1/1     Running            2          31d    10.1.1.138    serv20   <none>           <none>
rook-ceph-agent-v5kdf                 1/1     Running            2          31d    10.1.1.141    serv21   <none>           <none>
rook-ceph-mgr-a-75dfcffdfc-zzpcq      1/1     Running            4          28d    10.244.2.39   serv21   <none>           <none>
rook-ceph-mon-a-7ff57f9b49-4sk6q      1/1     Running            2          31d    10.244.0.28   serv20   <none>           <none>
rook-ceph-mon-b-f867cc96f-85wks       0/1     CrashLoopBackOff   623        2d5h   10.244.2.46   serv21   <none>           <none>
rook-ceph-mon-d-bc75d57b-2bds2        1/1     Running            1          28d    10.244.1.30   serv22   <none>           <none>
rook-ceph-operator-58f4b49c66-tgx22   1/1     Running            1          2d1h   10.244.1.43   serv22   <none>           <none>
rook-ceph-osd-0-75d9bb98db-gzggw      1/1     Running            2          31d    10.244.2.43   serv21   <none>           <none>
rook-ceph-osd-1-648d945c94-jn7d8      1/1     Running            1          28d    10.244.1.29   serv22   <none>           <none>
rook-ceph-osd-2-56997545c7-svk2p      1/1     Running            2          31d    10.244.0.27   serv20   <none>           <none>
rook-ceph-osd-prepare-serv20-nd8q8    0/2     Completed          0          23d    10.244.0.25   serv20   <none>           <none>
rook-ceph-osd-prepare-serv21-9nnp2    0/2     Completed          0          23d    10.244.2.37   serv21   <none>           <none>
rook-ceph-osd-prepare-serv22-bsml4    0/2     Completed          0          23d    10.244.1.27   serv22   <none>           <none>
rook-ceph-tools-7cf4cc7568-jhwn6      1/1     Running            2          31d    10.1.1.141    serv21   <none>           <none>
rook-discover-7xqxf                   1/1     Running            3          31d    10.244.0.26   serv20   <none>           <none>
rook-discover-c2jjp                   1/1     Running            2          31d    10.244.1.28   serv22   <none>           <none>
rook-discover-pt4zb                   1/1     Running            3          31d    10.244.2.38   serv21   <none>           <none>
  
  
**[root@serv20 ceph]# docker pull quay.io/k8scsi/csi-snapshotter:v1.1.1**
Error response from daemon: manifest for quay.io/k8scsi/csi-snapshotter:v1.1.1 not found

**Comment by travisn** [comment]
@slieer What build of rook were you using? I believe this has been fixed in master. If needed, you can override this to use a different property [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L167)

**Comment by slieer** [comment]
> @slieer What build of rook were you using? I believe this has been fixed in master. If needed, you can override this to use a different property [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L167)

OK, thanks.

**Comment by slieer** [comment]
> were
