### ISSUE TITLE
OSD PVC lookup is slow for large clusters

### ISSUE THREAD

**Issue by travisn** [rook/rook#3656]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Related to #3633 as seen in [this comment](https://github.com/rook/rook/pull/3633#discussion_r315376832), the lookup of PVCs corresponding to an OSD can be slow for large clusters. This is an infrequent operation, but since it's n^2 we would be looking at a slow loop if we had hundreds or thousands of OSDs.

**Expected behavior:**
To more efficiently look up the PVCs for the OSD, we could build a map for O(1) lookup for each PVC.

**Comment by BlaineEXE** [comment]
not stale
