### ISSUE TITLE
yum install fails from the ceph toolbox

### ISSUE THREAD

**Issue by travisn** [rook/rook#3662]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When attempting to install packages in the rook-ceph toolbox, it fails with the following error:
```
[root@minikube /]# yum install s3cmd
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
epel/x86_64/metalink                                                                                                                                                                                    |  16 kB  00:00:00     
 * base: mirrors.syringanetworks.net
 * epel: mirror.steadfastnet.com
 * extras: mirrors.syringanetworks.net
 * updates: mirrors.syringanetworks.net
Ceph                                                                                                                                                                                                    | 2.9 kB  00:00:00     
Ceph-noarch                                                                                                                                                                                             | 2.9 kB  00:00:00     
base                                                                                                                                                                                                    | 3.6 kB  00:00:00     
https://4.chacra.ceph.com/r/ceph-iscsi/master/ff5e6873c43ab6828d3f7264526100b95a7e3954/centos/7/flavors/default/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

 One of the configured repositories failed (ceph-iscsi packages for \x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=ceph-iscsi ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable ceph-iscsi
        or
            subscription-manager repos --disable=ceph-iscsi

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=ceph-iscsi.skip_if_unavailable=true

failure: repodata/repomd.xml from ceph-iscsi: [Errno 256] No more mirrors to try.
https://4.chacra.ceph.com/r/ceph-iscsi/master/ff5e6873c43ab6828d3f7264526100b95a7e3954/centos/7/flavors/default/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

**Expected behavior:**
Should be able to add packages during development to the toolbox. In particular, `s3cmd` is mentioned in the rook docs for consuming object storage.

**How to reproduce it (minimal and precise):**

- Install a cluster from master
- `kubectl create -f toolbox.yaml`
- `yum install s3cmd`

This does not repro with the v1.0.5 toolbox. There must be a change in the ceph/ceph:v14.2.2 base image that is causing this.

**Comment by dmick** [comment]
The root cause is that containers based on released ceph should not refer to chacra repos.   Why the code creates such an image is not yet clear.

**Comment by dmick** [comment]
So this https://docs.ceph.com/docs/master/rbd/iscsi-target-cli-manual-install/ sort of makes it seem that the various packages are not available, or not in late-enough versions, from normal repos.  That might mean the only option is from ceph builds, but it still doesn't explain why the repos aren't hosted on download.ceph.com.

**Comment by dmick** [comment]
@dillaman, any ideas?

**Comment by dillaman** [comment]
The container is pointing to a "latest" available build [1], but chacra only keeps a few around. Therefore, the container needs to be rebuilt so that it pulls the latest and greatest as a short-term. Longer term, we need to do an official release of the ceph-iscsi 3.x to download.ceph.com so that the ceph-container project can just point to it instead of chacra. 

[1] https://github.com/ceph/ceph-container/blob/532cef174636be11a541f9637784ef0373d50d5e/ceph-releases/ALL/centos/daemon-base/__DOCKERFILE_INSTALL__#L18

**Comment by dmick** [comment]
Yeah, I was aware of the latest avail problem, but more asking about "is it expected we don't have a release of ceph-iscsi and friends".  This is kind of a weird intermediate ground.

**Comment by dillaman** [comment]
It is indeed a weird intermediate ground -- just needs to be built and copied over there.

**Comment by dmick** [comment]
Who's responsible for that?

**Comment by dillaman** [comment]
Good question? If you can figure it out, here is the last official release repo [1] where the RPMs can get signed and copied over to download.ceph.com.

[1] https://3.chacra.ceph.com/r/ceph-iscsi/3/ec80bb1cc8b288b40bc35e03e4ba4c60daced938/centos/7/flavors/default/

**Comment by dillaman** [comment]
... I pinged David Galloway this morning to see if he can help sign and move the RPMs over.

**Comment by leseb** [comment]
Once RPMs move to download.ceph.com we can do the appropriate changes in the container image.

@djgalloway FYI. ^

**Comment by dillaman** [comment]
@leseb I wonder if it makes sense in the container image to add "enabled=0" for those ceph-iscsi related repos (at least for python-rtslib and tcmu-runner since we shouldn't be hosting third-party tools on "download.ceph.com" and they would still be pointing to chacra).

**Comment by leseb** [comment]
@dillaman makes perfect sense, I'll send a PR to disable the repos using chacra once the packages have been installed. That'll prevent further issues in the future.

**Comment by dillaman** [comment]
FYI -- new repo is ready @ http://download.ceph.com/ceph-iscsi/3/rpm/el7/noarch/

**Comment by leseb** [comment]
@dillaman can you confirm that ceph-iscsi 3 works with at least Nautilus and that for Octopus we should use `https://shaman.ceph.com/api/repos/ceph-iscsi/master/latest`? Thanks!

**Comment by dillaman** [comment]
@leseb Yes, using v3.x for Nautilus and pointing to the latest ceph-iscsi master for the in-development Octopus sounds good-to-me.

**Comment by leseb** [comment]
@dillaman as far as I can tell 2 things seem incorrect:

* https://download.ceph.com/ceph-iscsi/2/rpm/el7/ceph-iscsi.repo does not exist in ceph-iscsi 3
* https://download.ceph.com/ceph-iscsi/2/rpm/el7/ceph-iscsi.repo points to latest which points to ceph-isci 3

We need ceph-iscsi with its own ceph-iscsi.repo file I suppose.

**Comment by leseb** [comment]
Waiting for a new container build now.
