### ISSUE TITLE
pvc pending  waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually 

### ISSUE THREAD

**Issue by vinayjain15** [rook/rook#3664]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
pvc pending  waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system admin
**Expected behavior:**
pvc should be bound
**How to reproduce it (minimal and precise):**

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7
* Kernel (e.g. `uname -a`): 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):rook: v1.0.0-407.g6a6128
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.2
* Kubernetes version (use `kubectl version`): oc v3.11.82
kubernetes v1.11.0+d4cacc0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] : HEALTH_OK
(https://rook.io/docs/rook/master/ceph-toolbox.html)): 

Re-opening the issue #3127 ..

I am using image: ceph/ceph:v14.2.2-20190722

There is nothing in the logs, operator is running fine and no entry in operator log for the claim.
I was able to create volume and mount using rbd directly in toolbox pod

in osd log there is an entry stating: osd.2 10 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory

pvc has unit 20Gi

cluster.yaml:
storage: # cluster level storage configuration and selection
useAllNodes: false
useAllDevices: false
deviceFilter:
location:
config:

nodes:
- name: "node1"
  devices:
  - name: "sdc"
- name: "node2"
  devices:
  - name: "sdd"

- name: "node3"
  devices: # specific devices to use for storage can be specified for each node
  - name: "sdd"
[svctnsas@n01apl496 OpenShift]$ ./oc describe pvc wp-pv-claim
Name: wp-pv-claim
Namespace: rook-ceph
StorageClass: rook-ceph-block
Status: Pending
Volume:
Labels: app=wordpress
Annotations: volume.beta.kubernetes.io/storage-provisioner=rook-ceph.rbd.csi.ceph.com
Finalizers: [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
Type Reason Age From Message

Normal ExternalProvisioning 4s (x23 over 5m) persistentvolume-controller waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator

**Comment by Madhu-1** [comment]
@vinayjain15 can you provide rbd provisioner logs, just want to make sure everything is fine with rbd csi provisioner

**Comment by vinayjain15** [comment]
ah my bad .. i was supposed to use flex storageclass..

**Comment by glennodickson** [comment]
Hi

I received the same error "waiting for..." when creating two Ceph clusters in two namespaces one for apps (app-rook-ceph) and the other for Infra storage (infra-rook-ceph) on an openshift4.1 cluster. The cause and solution was in the cluster.yaml file. I've it described below :

Cause:
`Provisioner: rook-ceph.rbd.csi.ceph.com`

Solution:
`Provisioner: app-rook-ceph.rbd.csi.ceph.com`

Note: 
The prefix of the Provisioner needs to match the namespace I was defining for (app-rook-ceph) hence the prefix of 'app-'. Therefore:
`Provisioner: [namespace].rbd.csi.ceph.com`

**Comment by Madhu-1** [comment]
the provisioner namespace should be the namespace where operator pod is running not  the ceph cluster namespace

**Comment by vasanthaganeshk** [comment]
> Hi
> 
> I received the same error "waiting for..." when creating two Ceph clusters in two namespaces one for apps (app-rook-ceph) and the other for Infra storage (infra-rook-ceph) on an openshift4.1 cluster. The cause and solution was in the cluster.yaml file. I've it described below :
> 
> Cause:
> `Provisioner: rook-ceph.rbd.csi.ceph.com`
> 
> Solution:
> `Provisioner: app-rook-ceph.rbd.csi.ceph.com`
> 
> Note:
> The prefix of the Provisioner needs to match the namespace I was defining for (app-rook-ceph), therefore:
> `Provisioner: [namespace].rbd.csi.ceph.com`

@glennodickson, thank you. You saved so much time for me.
