### ISSUE TITLE
Unable to use separate external network post-cluster creation

### ISSUE THREAD

**Issue by echel0n** [rook/rook#3671]
Using the latest Rook v1.0.5 and hostNetwork set to true with the following override config below I am not able to get the OSDs to find an IP to bind to, I'm using Flannel for my CNI, any ideas ?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    public network =  10.0.0.0/24
    cluster network = 10.0.0.0/24
    public addr = ""
    cluster addr = ""
```

Environment:

Rook version (use rook version inside of a Rook Pod):
v1.0.5

Kubernetes version (use kubectl version):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by echel0n** [comment]
I ended up having to manually add "hostNetwork: true" to each OSD deployment spec and change the dnsPolicy from "ClusterFirst" to "ClusterFirstWithHostNet".

After doing the above I was able to delete the OSD pods and confirm that the OSDs were infact using a public and private IP address derived from my external 10Gb network.

I would of expected these changes to have been automatically applied by changing hostNetwork to true in the cluster CRD, perhaps this is a bug ?

**Comment by leseb** [comment]
1.0.5 has the following code: https://github.com/rook/rook/blob/5db568468e2d9a5fbc92944df0586570c29234be/pkg/operator/ceph/cluster/osd/spec.go#L259-L262 so I'd think this is supported.
