### ISSUE TITLE
Ceph dashboard not showing rbd provisioning status

### ISSUE THREAD

**Issue by mumrau** [rook/rook#3683]
* Bug Report

**Deviation from expected behavior:**
The `rbds` on the ceph dashboard are not showing usage.
![image](https://user-images.githubusercontent.com/14805850/63599965-f36f5d80-c5c2-11e9-80a3-b27cd2729e28.png)

**Expected behavior:**
On the other hand, `rbd --pool ony-of-my-pools du` shows perfect disk usage and provisioning state, including used storage.
I would expect the dashboard to show the same informations.
Output of the above command.
```NAME                                     PROVISIONED USED    
pvc-0b04007e-39ba-11e9-be2a-5254006f2ef9      50 GiB 4.0 GiB 
pvc-0b4697ca-39ba-11e9-be2a-5254006f2ef9      50 GiB 3.3 GiB 
pvc-0b85df53-39ba-11e9-be2a-5254006f2ef9      50 GiB 3.5 GiB 
pvc-46fc4c89-8c56-11e9-bff4-525400581905       5 GiB 128 MiB 
pvc-533bc3ff-9d9c-11e9-8803-5254006f0fb4       5 GiB 120 MiB 
pvc-65bd27ce-afb7-11e9-afc4-5254006f2ef9      10 GiB 2.9 GiB 
pvc-9739e0b3-b203-11e9-afc4-5254006f2ef9      25 GiB 232 MiB 
pvc-9d168d93-b203-11e9-afc4-5254006f2ef9     250 GiB  34 GiB 
pvc-b8bfd00d-38f8-11e9-be2a-5254006f2ef9     200 GiB  84 GiB 
pvc-c6b47fd2-935a-11e9-bff4-525400581905      10 GiB 148 MiB 
pvc-c82062af-935a-11e9-baba-5254006f0fb4       5 GiB 840 MiB 
pvc-f92225b6-516e-11e9-962a-52540021261d       4 GiB 500 MiB 
pvc-f9a4d8bb-516e-11e9-813a-5254006f2ef9      12 GiB 412 MiB 
<TOTAL>                                      676 GiB 134 GiB```


**Environment**:
* OS (e.g. from /etc/os-release): debian 9 (stretch)
* Kernel (e.g. `uname -a`): 4.9.0-8-amd64
* Cloud provider or hardware configuration: baremetal, on kubeadm
* Rook version (use `rook version` inside of a Rook Pod): v1.0.2
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.1
* Kubernetes version (use `kubectl version`): 1.15.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): OK

**Comment by ctrysbita** [comment]
Any update? Not resolved yet.

**Comment by ThomasJou** [comment]
I have the same problem on ceph-ansible nautilus version 14.2.5
any update ?

**Comment by mumrau** [comment]
Sorry to tag you on this @travisn , might not be the right way to get attention. But maybe you could give some insights about this issue?
It might be the normal behaviour though, and I couldn't confirm nor find the information about what we are supposed to expect.
You might as well close it if irrelevant, but I would believe that you might have the knowledge to do so.

**Comment by travisn** [comment]
Ah, this issue would be better opened in the Ceph dashboard instead of in Rook. 
@LenzGr Where is the best place to report dashboard issues?

**Comment by LenzGr** [comment]
> @LenzGr Where is the best place to report dashboard issues?

Sorry for the late reply. Please report Dashboard issues on the [Ceph tracker](https://tracker.ceph.com/projects/mgr/issues/new). Thank you!

**Comment by ctrysbita** [comment]
Ahh. Not solved yet.

**Comment by travisn** [comment]
As mentioned earlier, please open dashboard issue in the [Ceph tracker](https://tracker.ceph.com/projects/mgr/issues/new). Nothing we can do in rook for this issue.
