### ISSUE TITLE
OSDs are not starting on previous usad disks

### ISSUE THREAD

**Issue by holoGDM** [rook/rook#3687]
Hello

I created rook stack with operator one time but there was some unexpected behaviousr with mounting pvses. After that i removed all installation to try with newst version of rook - 1.0.5. Before next install I cleaned used raw  disks with:

```
dd if=/dev/zero of=/dev/sdX count=1 bs=1K
dd if=/dev/zero of=/dev/sdX bs=512 count=4096 seek=$(expr `blockdev --getsz /dev/sdX` - 4096)
```

But during second deployment of rook operator and cluster creation OSD started only on one previously not used server. After we clean again that disks and tried again OSDs not even want to try to start, after cluster creation MONs are created and its hanging. Im guesing it is because raw disks from previous installation are not properly cleaned. How to clear previously used disks by rook?

Right now it is hangin on such thing:

```2019-08-23 18:24:15.361835 I | exec: Running command: ceph-volume lvm batch --prepare
2019-08-23 18:24:18.340862 I | cephosd: device sdh to be configured by ceph-volume
2019-08-23 18:24:18.340895 I | cephosd: device sdi to be configured by ceph-volume
2019-08-23 18:24:18.340905 I | cephosd: device sdd to be configured by ceph-volume
2019-08-23 18:24:18.340912 I | cephosd: device sde to be configured by ceph-volume
2019-08-23 18:24:18.340920 I | cephosd: device sdf to be configured by ceph-volume
2019-08-23 18:24:18.340927 I | cephosd: device sdg to be configured by ceph-volume
2019-08-23 18:24:18.340936 I | cephosd: 0/0 pre-ceph-volume osd devices succeeded on this node
2019-08-23 18:24:18.349115 I | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/405599919
```

lsblk is not showing ceph volumes on thisk anymore but still there is some problem with them.

```# lsblk 
NAME          MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda             8:0    0  2.2T  0 disk 
├─sda1          8:1    0    1M  0 part 
├─sda2          8:2    0    1G  0 part /boot
├─sda3          8:3    0  500G  0 part /
├─sda4          8:4    0  500G  0 part /docker
└─sda5          8:5    0  500G  0 part /registry
sdb             8:16   0  3.3T  0 disk 
└─sdb1          8:17   0    3T  0 part /kafka
sdc             8:32   0  2.2T  0 disk 
└─sdc1          8:33   0    2T  0 part /data
sdd             8:48   0  1.1T  0 disk 
sde             8:64   0  1.1T  0 disk 
sdf             8:80   0  1.1T  0 disk 
sdg             8:96   0  1.1T  0 disk 
sdh             8:112  0  1.1T  0 disk 
sdi             8:128  0  1.1T  0 disk 
sdj             8:144  0 29.8G  0 disk 
├─sdj1          8:145  0  500M  0 part 
└─sdj2          8:146  0 29.3G  0 part 
  ├─rhel-root 253:0    0 26.3G  0 lvm  
  └─rhel-swap 253:1    0    3G  0 lvm  
```
rook config directory was clened before nesxt start of rook too

**Comment by echel0n** [comment]
`sudo sgdisk --zap /dev/sdX` and remove the osd folder from `/var/lib/rook`

**Comment by leseb** [comment]
If it's hanging on `2019-08-23 18:24:18.349115 I | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/405599919` it looks more like a network issue than a disk issue since the command tries to connect to a monitor.

**Comment by Confusingboat** [comment]
I'm running into this exact same error and I can't figure out what's going on. Everything was working fine until it wasn't. I tried rebuilding the host entirely, including `sgdisk -Z /dev/x`ing all the disks, clearing out the old OSDs, etc from the crush map, but I still receive the same error. The other six nodes are fine.
