### ISSUE TITLE
rook-ceph-tools container exposes the physical host

### ISSUE THREAD

**Issue by gbonazzoli** [rook/rook#3706]
The problem is very simple to reproduce:

We have a Rook installation running smoothly:

`
root@kube-master:~# kubectl get pods -n rook-ceph

NAME                                      READY   STATUS      RESTARTS   AGE
....
rook-ceph-tools-7cf4cc7568-jjwb6          1/1     Running     3          2d
....
`

If we enter in rook-ceph-tools-7cf4cc7568-jjwb6 we have:

`
root@kube-master:~# kubectl exec -it rook-ceph-tools-7cf4cc7568-jjwb6 -n rook-ceph sh
sh-4.2# ceph health detail
HEALTH_OK

sh-4.2# uname -a
Linux kube-node02 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

sh-4.2# id
uid=0(root) gid=0(root) groups=0(root)
`
so it is exposed directly the physical host with root privileges!!!

**Comment by leseb** [comment]
You can remove this https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/toolbox.yaml#L31-L32 and the container won't be privileged anymore.

I don't see this as a bug since the behavior can always be modified at will.

**Comment by travisn** [comment]
The example toolbox is being updated with #4318.

**Comment by travisn** [comment]
Fixed with #4318
