### ISSUE TITLE
k8s ceph.rook.io/block does not support block volume provisioning

### ISSUE THREAD

**Issue by AsherShoshan** [rook/rook#3719]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
PVC created

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
As a matter of fact, Rook does support block volume provisioning: https://rook.github.io/docs/rook/v1.0/ceph-block.html.

I'm closing this issue since there is no information being provided.

**Comment by AsherShoshan** [comment]
I have version 0.9 installed in openshift 4.2.
The issue is when I try to create a pvc with blockmode:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test2
spec:
  #storageClassName: k8srbd
#kubevirt-hostpath-provisioner
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 20Mi



Then describe the pvc , you'll see the message it's not supported:

Name:          test2
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner:
ceph.rook.io/block
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Block
Events:
  Type       Reason                Age                 From

Message
  ----       ------                ----                ----

-------
  Warning    ProvisioningFailed    116s
ceph.rook.io/block_rook-ceph-operator-7dc4fb9c9d-dkfqw_db1ee50e-ce05-11e9-8c49-0a580a810114
 ceph.rook.io/block does *not support block volume *provisioning
  Normal     ExternalProvisioning  11s (x8 over 115s)
 persistentvolume-controller
                   waiting for a volume to be created, either by external
provisioner "ceph.rook.io/block" or manually created by system administrator
Mounted By:  <none>



How can I find more information on this issue?
Please advise,

**Comment by leseb** [comment]
You should use Rook 1.0, get the latest here: https://github.com/rook/rook/releases/tag/v1.0.6

**Comment by AsherShoshan** [comment]
10x,
Is there a way to upgrade or just uninstall/install?

**Comment by leseb** [comment]
https://rook.io/docs/rook/v1.0/ceph-upgrade.html

**Comment by AsherShoshan** [comment]
10x,
Installed 1.0.6.
Still have the issue.
Pls look again at the pvc.yaml; have you tried this in your env?
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test2
spec:
  #storageClassName: k8srbd
#kubevirt-hostpath-provisioner
  accessModes:
    - ReadWriteOnce
*  volumeMode: Block*
  resources:
    requests:
      storage: 20Mi

**Comment by galexrt** [comment]
@AsherShoshan Rook Flexvolume does not support block devices attached in block mode.
This would need to be implemented in Ceph CSI, as I don't think we'll put too much work in to Flexvolume anymore.

Probably to good to check the Ceph CSI repo https://github.com/ceph/ceph-csi and / or open an issue if that feature is not implemented (partially related to, e.g., #2650). /cc @Madhu-1

**Comment by Madhu-1** [comment]
@galexrt @AsherShoshan block volume is supported in ceph-csi
