### ISSUE TITLE
pvc to pool

### ISSUE THREAD

**Issue by Liuxiayu** [rook/rook#3733]
hello everyone, I want to know how does PVC map to Pool? Can you tell me more about it ?

**Comment by leseb** [comment]
A PVC has a [storage class](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/rbd/pvc.yaml#L12) which maps to a [Ceph pool](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml#L22).
