### ISSUE TITLE
cmd reporter

### ISSUE THREAD

**Issue by mrmassis** [rook/rook#3736]
Hi everyone.
After enable the graylog in the lab my cluster broken. I tried delete and create a new cluster but it was unsesufull. The follow error message apper to me when I try create a cluster.

"op-cluster: unknown ceph major version. failed to extract ceph version. failed to parse version from: Error response from daemon: configured logging driver does not support reading"

I read that the problem is because the ceph versions is getting from logs in stdout. I read too than a new feature was release to fix it: cmd-reporter. In front off, I dont know how i cant fix it or enable the cmd-reporter. I has using the follow versions:
* rook/ceph:v1.0.2
* ceph/ceph:v14.2

Any suggestion? 
Tkz in advance

**Comment by leseb** [comment]
The cmd-reporter was introduced during the 1.1 cycle so in order to get it you need to upgrade your operator to 1.1 once released.

**Comment by mrmassis** [comment]
Tkz for answer,
where i can find the 1.1 image?
Tkz

**Comment by travisn** [comment]
@mrmassis For now you can test with the `rook/ceph:master` image. The v1.1 release is due out in less than two weeks.
