### ISSUE TITLE
Helm values.yaml is generated in place causing dirty builds

### ISSUE THREAD

**Issue by travisn** [rook/rook#3746]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The helm values.yaml is generated with version information during the build. When generated in place it causes the file to remain checked out. Developers unexpectedly see the diff in their local changes and the CI reports the build with a `dirty` suffix since a file remains checked out in the enlistment. This was overlooked in #3701. 

@k0da Either we will need to revert #3701 or generate the values.yaml to another file that is ignored or in a temp build directory. Can you take a look?

**Expected behavior:**
Files in the enlistment should not be modified in the build.

**How to reproduce it (minimal and precise):**

- Build Rook
- See values.yaml modified in the enlistment

**Comment by k0da** [comment]
@travisn oh, I'll take a look.

I there a simple command where I can verify it is fixed?

**Comment by travisn** [comment]
A simple build with a `make` command should show that there is not a file changed in the enlistment. Generating it to an ignored file like previously may be the easiest thing
