### ISSUE TITLE
Following official example results in `waiting for a volume to be created`

### ISSUE THREAD

**Issue by joshuacox** [rook/rook#3748]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Following the official docs does not result in a running mysql and wordpress. And ends with:

```
  Normal     ExternalProvisioning  14s (x8 over 119s)  persistentvolume-controller  waiting for a volume to be created, either by externalprovisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
```

**Expected behavior:**

Running mysql and wordpress like as the official [docs](https://rook.io/docs/rook/v1.1/ceph-block.html)

**How to reproduce it (minimal and precise):**

I have reproduced this in multiple k8s environments, perhaps the easiest to reproduce is to follow this [katacoda scenario](https://www.katacoda.com/thoth/scenarios/tryoutrook)

or manually run [this](https://gist.github.com/joshuacox/30c0b0871622b233195a8bb5229ee5e4) on a kubernetes cluster, perhaps a generic [katacoda k8s playground](https://www.katacoda.com/courses/kubernetes/playground)

This uses the `release-1.1` branch, you can specify a branch as well:

```
export ROOT_BRANCH=master ; curl -s https://gist.githubusercontent.com/joshuacox/30c0b0871622b233195a8bb5229ee5e4/raw/597f8e24fa5d053c184ee9259286370e4fd283dc/gistfile1.txt | bash
```

Both `master` and `release-1.1` fail in the same way as recorded above.

**Environment**:

#### OS (e.g. from /etc/os-release):

```
master $ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

#### Kernel (e.g. `uname -a`):

```
Linux master 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

#### Cloud provider or hardware configuration:

[katacoda](https://www.katacoda.com/courses/kubernetes/playground)

#### Rook version (use `rook version` inside of a Rook Pod):

`release-1.1`

####  Storage backend version (e.g. for ceph do `ceph -v`):

```
[root@node01 /]# ceph -v
ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)
```

#### Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

#### Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

[katacoda](https://www.katacoda.com/courses/kubernetes/playground)

#### Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

```
kubectl exec -n rook-ceph rook-ceph-tools-b8c679f95-hrlpw 'ceph health'
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"ceph health\": executable file not found in $PATH": unknown
command terminated with exit code 126
```

### Simlar Issues

https://github.com/rook/rook/issues/3744  This is very similar, however, I was unable to reproduce the workaround, and I'd rather stick as close to the documentation until I see consistent successful results.

https://github.com/rook/rook/issues/3664  Also very similar, but I'm uncertain that the CSI is to blame here.

**Comment by Madhu-1** [comment]
@joshuacox can you check all pods are in running state. PVC will go to bound state once all csi pods are in running state

the script you are  using does not wait till the cluster is created and all csi pods go to  running state

**Comment by joshuacox** [comment]
@Madhu-1 at which point in the script should I be introducing a wait?

**Comment by Madhu-1** [comment]
@joshuacox introducing wait can cause an issue when you have a slow network, better instead of introducing  wait, check  all pods related to ceph cluster is running  and also all csi pods are running

**Comment by joshuacox** [comment]
@Madhu-1 which pods specifically?  I don't see any rook/ceph pods in a non-`Running` state:

```
master $ kubectl get pods --all-namespaces|grep -v Running
NAMESPACE     NAME                                            READY   STATUS              RESTARTS   AGE
default       wordpress-595685cc49-vnlkk                      0/1     ContainerCreating   0          6m38s
default       wordpress-mysql-b78774f44-t88jf                 0/1     ContainerCreating   0          6m39s
rook-ceph     rook-ceph-osd-prepare-node01-77r6t              0/1     Completed           0          3m48s
```

and at which point do I need to introduce this conditional wait? 

I have updated the gist to include a wait function:

https://gist.github.com/joshuacox/30c0b0871622b233195a8bb5229ee5e4

But it doesn't seem to have made a difference.

**Comment by joshuacox** [comment]
@Madhu-1 I've wrapped the entire thing into a [katacoda scenario](https://www.katacoda.com/thoth/scenarios/tryoutrook), which should be free for anyone to try out and/or fork and modify yourself [here](https://github.com/joshuacox/katacoda-scenarios/tree/master/TryOutRook)

**Comment by alexcpn** [comment]
Maybe instead of shallow cloning  install like this; 

```
$ git clone https://github.com/rook/rook
$ cd rook/cluster/examples/kubernetes/ceph
$ git checkout remotes/origin/release-1.1
```

**Comment by joshuacox** [comment]
@alexcpn I added your modifications with a few other tweaks to the [gist](https://gist.github.com/joshuacox/30c0b0871622b233195a8bb5229ee5e4#file-gistfile1-txt-L65-L68) and tried:

```
curl -s https://gist.github.com/joshuacox/30c0b0871622b233195a8bb5229ee5e4/raw/57e3b0f8ac8539f9f534d2d57ac738df1cc5ea99/gistfile1.txt | bash
```

on a cluster here as well as the generic katacoda kubernetes scenario, both hang at waiting for the pvc claim as usual though, so I'm not certain the shallow checkout was to blame.

I went ahead and added it all to my [katacoda scenario](https://www.katacoda.com/thoth/scenarios/tryoutrook) as well though.

I'm still wondering if @Madhu-1 can suggest some pods that I might be missing in my [conditional waits](https://gist.github.com/joshuacox/30c0b0871622b233195a8bb5229ee5e4#file-gistfile1-txt-L44-L62).

**Comment by joshuacox** [comment]
If I let it run long enough it ends in:

```
Events:
  Type     Reason              Age                    From                         Message
  ----     ------              ----                   ----                         -------
  Warning  ProvisioningFailed  3m8s (x962 over 4h3m)  persistentvolume-controller  storageclass.storage.k8s.io "rook-ceph-block
" not found
```

**Comment by Madhu-1** [comment]
@joshuacox can you provide below output
* List pods in rook-ceph namespace
* Logs from the rbd provisioner logs

**Comment by joshuacox** [comment]
@Madhu-1 the full output is:

```
kubectl get pvc                 
NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE
mysql-pv-claim   Pending                                      rook-ceph-block   17h
wp-pv-claim      Pending                                      rook-ceph-block   13h
```
```
kubectl describe pvc wp-pv-claim                                                             :(
Name:          wp-pv-claim
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Pending
Volume:        
Labels:        app=wordpress
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    wordpress-8968cd5b6-wgslh
Events:
  Type     Reason              Age                 From                         Message
  ----     ------              ----                ----                         -------
  Warning  ProvisioningFailed  9s (x301 over 75m)  persistentvolume-controller  storageclass.storage.k8s.io "rook-ceph-block" not found
```

```
kubectl get pods -n rook-ceph   
NAME                                            READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-4cvrp                          3/3     Running   0          17h
csi-cephfsplugin-5b6wm                          3/3     Running   0          17h
csi-cephfsplugin-jhq5d                          3/3     Running   0          17h
csi-cephfsplugin-provisioner-69cf8dc7c4-8hgfl   4/4     Running   16         17h
csi-cephfsplugin-provisioner-69cf8dc7c4-zpn66   4/4     Running   7          17h
csi-rbdplugin-kwdll                             3/3     Running   1          18h
csi-rbdplugin-n2d4v                             3/3     Running   0          18h
csi-rbdplugin-provisioner-5ccc9f6d58-82927      5/5     Running   15         18h
csi-rbdplugin-provisioner-5ccc9f6d58-9fkm9      5/5     Running   22         18h
csi-rbdplugin-w67sr                             3/3     Running   0          18h
rook-ceph-agent-bxhg4                           1/1     Running   0          18h
rook-ceph-agent-q8wvh                           1/1     Running   0          18h
rook-ceph-agent-zqd2g                           1/1     Running   0          18h
rook-ceph-mon-a-67d45d7c8c-wksq6                1/1     Running   0          17h
rook-ceph-operator-8c596f798-2qp5t              1/1     Running   20         18h
rook-ceph-tools-6cf65f79d8-fv9zh                1/1     Running   0          17h
rook-discover-28cbv                             1/1     Running   0          18h
rook-discover-xg274                             1/1     Running   1          18h
rook-discover-xhjtk                             1/1     Running   0          18h
```

I am very happy to supply any other debugging logs that one might need.

**Comment by Madhu-1** [comment]
sure will debug it
is this storage-class created `rook-ceph-block` ? if yes please provide me the logs of
```
kubectl logs po/csi-rbdplugin-provisioner-5ccc9f6d58-82927  -c csi-provisioner -nrook-ceph
kubectl logs po/csi-rbdplugin-provisioner-5ccc9f6d58-9fkm9  -c csi-provisioner  -nrook-ceph
```

**Comment by joshuacox** [comment]
the storage class is created by this [line](https://gist.github.com/joshuacox/30c0b0871622b233195a8bb5229ee5e4#file-gistfile1-txt-L102)

I have also tried using other definitions of the storageclass as well (e.g storageclass.yaml right next to that storageclass-test.yaml and the others found under `ook/cluster/examples/kubernetes/ceph`). 

the output of `kubectl logs po/csi-rbdplugin-provisioner-5ccc9f6d58-82927  -c csi-provisioner -nrook` is:

```
I0915 15:23:54.237968       1 leaderelection.go:222] failed to acquire lease rook-ceph/rook-ceph-rbd-csi-ceph-com
I0915 15:24:04.127311       1 leaderelection.go:326] lock is held by csi-rbdplugin-provisioner-5ccc9f6d58-9fkm9 and has not yet
 expired
I0915 15:24:04.127344       1 leaderelection.go:222] failed to acquire lease rook-ceph/rook-ceph-rbd-csi-ceph-com
```
it's too large to post the complete log (~2M)

The second command 
`kubectl logs po/csi-rbdplugin-provisioner-5ccc9f6d58-9fkm9  -c csi-provisioner  -nrook-ceph` has stuff like this in it:

```
W0915 15:35:23.156137       1 controller.go:886] Retrying syncing claim "2b6eb79b-d55e-40ab-bdc1-1eaac38a66e9", failure 2
E0915 15:35:23.156176       1 controller.go:908] error syncing claim "2b6eb79b-d55e-40ab-bdc1-1eaac38a66e9": failed to provisio
n volume with StorageClass "rook-ceph-block": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0915 15:35:23.156472       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"m
ysql-pv-claim", UID:"2b6eb79b-d55e-40ab-bdc1-1eaac38a66e9", APIVersion:"v1", ResourceVersion:"262923", FieldPath:""}): type: 'W
arning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Deadline
Exceeded desc = context deadline exceeded
I0915 15:35:25.156652       1 controller.go:1196] provision "default/mysql-pv-claim" class "rook-ceph-block": started
I0915 15:35:25.162099       1 controller.go:471] CreateVolumeRequest {Name:pvc-2b6eb79b-d55e-40ab-bdc1-1eaac38a66e9 CapacityRan
ge:required_bytes:5000000000  VolumeCapabilities:[mount:<fs_type:"xfs" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:ma
p[clusterID:rook-ceph csi.storage.k8s.io/fstype:xfs csi.storage.k8s.io/node-stage-secret-name:rook-ceph-csi csi.storage.k8s.io/
node-stage-secret-namespace:rook-ceph csi.storage.k8s.io/provisioner-secret-name:rook-ceph-csi csi.storage.k8s.io/provisioner-s
ecret-namespace:rook-ceph imageFeatures:layering imageFormat:2 pool:replicapool] Secrets:map[] VolumeContentSource:<nil> Access
ibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0915 15:35:25.162360       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"m
ysql-pv-claim", UID:"2b6eb79b-d55e-40ab-bdc1-1eaac38a66e9", APIVersion:"v1", ResourceVersion:"262923", FieldPath:""}): type: 'N
ormal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/mysql-pv-claim"
I0915 15:35:25.167790       1 connection.go:180] GRPC call: /csi.v1.Controller/CreateVolume
I0915 15:35:25.167907       1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":5000000000},"name":"pvc-2b6e
b79b-d55e-40ab-bdc1-1eaac38a66e9","parameters":{"clusterID":"rook-ceph","imageFeatures":"layering","imageFormat":"2","pool":"re
plicapool"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"xfs"}},"access_mode":{"mode":1
}}]}
I0915 15:35:26.928919       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-rbd-csi-ceph-com
I0915 15:35:31.956058       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-rbd-csi-ceph-com
```
full output here:
http://dpaste.com/337T1FZ

**Comment by joshuacox** [comment]
I definitely messed up the storageclass somehow, as I did get a success from master just now on the katacoda plain jane kubernetes scenario:

```
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
mysql-pv-claim   Bound    pvc-cdf75d31-d7cd-11e9-98c1-0242ac110032   20Gi       RWO            rook-ceph-block   12m
wp-pv-claim      Bound    pvc-ce239dec-d7cd-11e9-98c1-0242ac110032   20Gi       RWO            rook-ceph-block   12m
```

**Comment by Madhu-1** [comment]
@joshuacox yeah some issue with storage-class

anything else is needed with this issue if not can you please close it?

**Comment by joshuacox** [comment]
@Madhu-1  Let me verify by reproducing the success in a few other environments, and then I will close this issue.

**Comment by Madhu-1** [comment]
@joshuacox sure :)

**Comment by 13567436138** [comment]
how to solve this problem，I am facing the same one

**Comment by Madhu-1** [comment]
@13567436138 what rook version you are using?

**Comment by joshuacox** [comment]
ya let's re-open this issue, as I'm no longer able to get a bound condition on my personal cluster.  I'll see if I can't reproduce the borkage in a publicly available setting.

**Comment by Madhu-1** [comment]
@joshuacox how it was working earlier? what issue you are facing now. need detail logs and steps to analyze the issue (if present)

**Comment by joshuacox** [comment]
@Madhu-1 I am not certain why it is not working, hence the reason why I opened this issue in the first place.  I cannot get rook to operate consistently across many different scenarios.  It seems to fail the most often on bare-metal, and rarely now in the katacoda scenario.  However, I have seen failure intermittently across everything in the past month or so.  This prevents me from using rook in production, though I continue to experiment with it.  To this day I am using [openebs](https://openebs.io/) for all my production storage, though I am looking for a stable alternative.  I will give all of this another shot next week and will post detailed logs here.
