### ISSUE TITLE
osd's migration

### ISSUE THREAD

**Issue by Liuxiayu** [rook/rook#3750]
If there are multiple osds running on a node, but this node is down, why not migrate this osd to another available node ？

**Comment by Liuxiayu** [comment]
In the rook cluster, if the previously assigned node fails, all pods running on non-master nodes are not migrated to another available node. Why?

**Comment by mykaul** [comment]
Can you specify how are you testing and which Rook version you are using, etc.?

**Comment by leseb** [comment]
> In the rook cluster, if the previously assigned node fails, all pods running on non-master nodes are not migrated to another available node. Why?

OSDs are not migrated because they are tight to a local disk on a physical machine unless you're running on a Cloud environment. When using OSD on PVC though the OSD will be rescheduled.

And yes, we need more context on your request.

**Comment by Liuxiayu** [comment]
> Can you specify how are you testing and which Rook version you are using, etc.?

I used version 0.9.2.

**Comment by Liuxiayu** [comment]
> > In the rook cluster, if the previously assigned node fails, all pods running on non-master nodes are not migrated to another available node. Why?
> 
> OSDs are not migrated because they are tight to a local disk on a physical machine unless you're running on a Cloud environment. When using OSD on PVC though the OSD will be rescheduled.
> 
> And yes, we need more context on your request.
Ok, thanks!If osd fails, how do you think you can failover and recover osd in a rook cluster?

**Comment by leseb** [comment]
> > > In the rook cluster, if the previously assigned node fails, all pods running on non-master nodes are not migrated to another available node. Why?
> > 
> > 
> > OSDs are not migrated because they are tight to a local disk on a physical machine unless you're running on a Cloud environment. When using OSD on PVC though the OSD will be rescheduled.
> > And yes, we need more context on your request.
> > Ok, thanks!If osd fails, how do you think you can failover and recover osd in a rook cluster?

Again, you need to be more precise, send the logs of the failing pod. Thanks.

**Comment by Liuxiayu** [comment]
Osd has been waiting for the old node to start without moving to other available nodes

**Comment by BlaineEXE** [comment]
OSDs do not fail over to other nodes because the OSDs require access to a particular disk which is likely still on the failed node. If the disk doesn't move to a new node, no failover can occur.
