### ISSUE TITLE
Operator crashing because leader election keeps failing

### ISSUE THREAD

**Issue by benceszikora** [rook/rook#3754]
Our operator is crashing with the following messages:
```
8 leaderelection.go:263] failed to renew lease rook-ceph/ceph.rook.io-block: failed to tryAcquireOrRenew context deadline exceeded
8 controller.go:847] leaderelection lost
8 leaderelection.go:263] failed to renew lease rook-ceph/rook.io-block: failed to tryAcquireOrRenew context deadline exceeded
```
This doesn't happen instantly when it starts up, it always works for a while and then crashes after a few minutes.

This is on a brand new cluster, it happens from the start, even while setting up the ceph cluster. I tried setting up the cluster again from scratch a few times, but I get the same issue.

Any idea what might be going on here?

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.5
* Cloud provider or hardware configuration:  bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.0.6
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.2
* Kubernetes version (use `kubectl version`): 1.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): vanilla kubernetes

**Comment by albertdb** [comment]
This is what happened in https://github.com/rook/rook/issues/3751#issuecomment-529866667

In my case is not constantly failing, but sometimes it does, leaving unusable the volumes that are being provisioned at the very same moment.

**Comment by rstcruzo** [comment]
@albertdb @benceszikora I have that issue too. Did you manage to fix it?

**Comment by Huihuihh** [comment]
> @albertdb @benceszikora I have that issue too. Did you manage to fix it?

so do i

**Comment by oiricaud** [comment]
what was the fix? Is this being maintained?

**Comment by travisn** [comment]
@oiricaud How often are you seeing this issue? Are you seeing side effects besides the operator restarting?

**Comment by leseb** [comment]
Since 1.3, we use the controller runtime so this bug does not exist anymore AFAIK.

**Comment by zeaone** [comment]
> Since 1.3, we use the controller runtime so this bug does not exist anymore AFAIK.

Can you describe in detail the changes in controller-runtime before v1.3? Like how was it implemented before v1.3?

**Comment by BlaineEXE** [comment]
Rook used Kubernetes' client-go watchers before controller-runtime IIRC.

**Comment by zeaone** [comment]
thanks, I would like to ask what is the function of `this(in pkg/operator/ceph/operator.go form line 134 to 144, code below)` before v1.3? Is the election of the operator guaranteed? When expanding Ceph, the operator restarted due to excessive pressure on etcd.
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/15962991/203687324-f1c0a4f5-d61f-4a7a-9360-d2df11ec233e.png">
