### ISSUE TITLE
OSD on PVC: Error while running ceph-osd daemon

### ISSUE THREAD

**Issue by sp98** [rook/rook#3756]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```
Getting following message while running the ceph-osd daemon
exec: Running command: ceph-osd --foreground --id 0 --osd-uuid 6d5b3b87-20cf-4b54-98a3-04d9b2adf721 --conf /var/lib/rook/osd0/rook-ceph.config --cluster ceph --setuser ceph --setgroup ceph --setuser-match-path /var/lib/rook/osd0 --default-log-to-file false --ms-learn-addr-from-peer=false
2019-09-03 09:37:00.706269 I | 2019-09-03 09:37:00.704 7ff9975d6d80 -1 Falling back to public interface
2019-09-03 09:37:01.414065 I | 2019-09-03 09:37:01.412 7ff9975d6d80 -1 osd.0 0 log_to_monitors {default=true}
2019-09-03 09:37:03.033637 I | 2019-09-03 09:37:03.032 7ff981966700 -1 osd.0 0 waiting for initial osdmap
2019-09-03 09:37:03.049690 I | 2019-09-03 09:37:03.046 7ff989be1700 -1 osd.0 16 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory

```
**Expected behavior:**
Not sure whether its a bug or if its impacting the OSD daemon in any way. Can someone confirm on this behavior?

**How to reproduce it (minimal and precise):**

- Setup a cluster (I'm using OC on AWS)
- Kubectl apply -f common.yaml
- kubectl apply -f operator.yaml
- kubectl apply -f cluster-on-pv.yaml. 

Observe the OSD pods output. 

**File(s) to submit**:
osd-daemon-pod-logs.txt

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by sp98** [comment]
Just confirmed. This is not an issue.

**Comment by NicolaiSchmid** [comment]
How was your problem resolved?
