### ISSUE TITLE
operator-openshift.yaml point to the master image  image: rook/ceph:master

### ISSUE THREAD

**Issue by tareqalayan** [rook/rook#3757]
It should be pinned to some tagged image.
This way you will get whatever in master which is moving target.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by mykaul** [comment]
Doesn't look like a bug to me. On master you get master. You may argue that on other branches you should get a stable build - have you checked it?

**Comment by tareqalayan** [comment]
i am talking about tag v1.1.0-beta.0

**Comment by mykaul** [comment]
So you expect image: rook/ceph:master to be instead using v1.1.0-beta.0? Makes sense... Can you test it? I can send a PR (it's a one-liner...)

**Comment by travisn** [comment]
There are a number of yamls that need to point to the new tag instead of master since the release-1.1 branch was just created. This was missed in the process to create a beta tag.

**Comment by travisn** [comment]
This was fixed by #3762
