### ISSUE TITLE
Mon canary pod remains pending even when not needed anymore

### ISSUE THREAD

**Issue by travisn** [rook/rook#3764]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The mon canary pod may remain in a pending state even if not needed. In the following pod status we see that mons a, b, and c have been restarted successfully while the canary pod remains pending. If the mons come back in quorum, the pending pod should be cleaned up.

```
rook-ceph-mon-d-canary remained in pending state even after other 3  rook-ceph-mon pods came up and running.


$ oc -n openshift-storage get pods | grep rook-ceph-mon
rook-ceph-mon-a-84ddfd7588-vvxr4                1/1     Running     1          5h53m
rook-ceph-mon-b-57b794b755-wx6x8                1/1     Running     0          4h38m
rook-ceph-mon-c-5bb7549576-cx4xr                1/1     Running     1          5h52m
rook-ceph-mon-d-canary-59d9d74795-k9s56         0/1     Pending     0          146m

```

**Expected behavior:**
The canary pod should not remain indefinitely even when not needed. The operator should remove it and abort the mon failover if the mons all return to quorum.

**How to reproduce it (minimal and precise):**

- Start a three node cluster
- Configure rook with `mon.allowMultiplePerNode: false` and `mon.count: 3`
- Cause a mon to fail (delete its deployment)
- Wait for the mon timeout (default is 10 minutes)
- See the mon failover start. The canary pod created
- The canary pod will remain pending indefinitely since there is not a fourth node that would satisfy the anti-affinity for mons to run on different nodes.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by noahdesu** [comment]
Hmm. The `assignMons` method has a deferred function that deletes canaries after the scheduling process is complete. I wonder if on the health check side of things there is a path that misses that cleanup?

**Comment by travisn** [comment]
The repro steps may have included losing power to a node. If the operator pod died like that, the canary pod wouldn't be cleaned up after operator restart, right?

**Comment by noahdesu** [comment]
Oh I must have missed that aspect of the repro. That sounds like a plausible scenario. 

Since the health checker takes a lock out on the orchestration process (?) it should be safe to delete any canaries that exist. Assuming that lock is taken so it doesn’t nuke canaries involved in an ongoing round of the main reconciliation loop.

**Comment by travisn** [comment]
fwiw, i observed that when a canary pod was pending and the operator was restarted, the canary pod was deleted and then re-created. However, this was in the startup case where the original quorum had never been formed instead of the failover scenario. I suspect this would only affect the failover scenario, but should not be a common occurrence in any case.

**Comment by mykaul** [comment]
Any updates on this one?

**Comment by bhavyanshu** [comment]
I am seeing the exact same thing in my deployment as @travisn explained. If I restart the operator, it brings back the mon pod. I upgraded from v1.0.4 to v1.1.0 and removed a node. Since then I am seeing a rook-ceph-mon-b-canary-66f788f58b-bctqg  in Pending state. It's surprising that I already have two monitors up:

```bash
csi-cephfsplugin-njfjr                                         3/3     Running     0          154m
csi-cephfsplugin-provisioner-0                                 4/4     Running     0          137m
csi-cephfsplugin-tg28q                                         3/3     Running     0          154m
csi-rbdplugin-kc7bv                                            3/3     Running     0          154m
csi-rbdplugin-nxrwb                                            3/3     Running     0          154m
csi-rbdplugin-provisioner-0                                    5/5     Running     0          137m
rook-ceph-agent-bmx6m                                          1/1     Running     0          154m
rook-ceph-agent-kqfk7                                          1/1     Running     0          154m
rook-ceph-mds-oneva-fs-a-6bc4895459-4zgvh                      1/1     Running     0          47d
rook-ceph-mds-oneva-fs-b-56fc45bd67-5krzm                      1/1     Running     0          47d
rook-ceph-mgr-a-854df4b466-gh7ls                               1/1     Running     0          99m
rook-ceph-mon-a-7dfbf9fc7-zhlhd                                1/1     Running     0          153m
rook-ceph-mon-b-canary-66f788f58b-bctqg                        0/1     Pending     0          3s
rook-ceph-mon-d-5875c86fd5-g5h8w                               1/1     Running     0          154m
rook-ceph-operator-5bdddc9f66-tcgwv                            1/1     Running     0          22s
rook-ceph-osd-0-694dc4f4d9-96rwb                               1/1     Running     0          98m
rook-ceph-osd-2-947cb54fc-rs75p                                1/1     Running     0          98m
rook-ceph-osd-prepare-c3ad995946f812d66335fc24071ffd57-ncwqd   0/1     Completed   0          98m
rook-ceph-osd-prepare-d6802bd12975b44c6553fd78c0a76d5f-vp6wv   0/1     Completed   0          98m
rook-ceph-tools-7f86b878fc-9bjwd                               1/1     Running     0          3d1h
rook-discover-57vsp                                            1/1     Running     0          137m
rook-discover-qk9mt                                            1/1     Running     0          137m
```

**Comment by jmolmo** [comment]
Unfortunately it has not been possible to reproduce the bug. I have tested with 4 different scenarios and in all the cases the canary pods were deleted.

We will need more info in order to diagnose and find out what is wrong. 
If anybody experiment this issue it will be nice to have at least the following information:
- kubernetes version
- Rook version
- The "description of the canary pod in Pending state. Use:
`# kubectl -n rook-ceph describe pod <canary-pod-in-pending-state>`
- The logs of the operator. Use:
`# kubectl -n rook-ceph logs <rook-ceph-operator-..............>`

A brief description of the situation..., a node was down/restarted, the operator was restarted, what was the sequence of facts... etc 



**Details about test performed:**
---------------------------------------

My Test environment:

- Lab with 4 vm's running CentOS Linux release 7.6.1810 (Core)

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

```
# rook version
rook: v1.2.0-10.g500198c
go: go1.11

```


### Test 1:
Delete a monitor deployment and wait 10 minutes for the failover

Note:I have used to delete the monitor:
`# kubectl -n rook-ceph delete deployment rook-ceph-mon-b`

**Result:**
No canary pods in Pending state. The deleted monitor deployment is recovered after 15 minutes.


Extract of the relevant operator logs (everything ok):

```
2019-12-11 07:53:44.861886 W | op-mon: mon a NOT found in quorum and timeout exceeded, mon will be failed over
2019-12-11 07:53:44.861910 I | op-mon: Failing over monitor a
2019-12-11 07:53:44.861934 I | op-mon: starting new mon: &{ResourceName:rook-ceph-mon-d DaemonName:d PublicIP: Port:6789 DataPathMap:0xc0008c5e90}
2019-12-11 07:53:44.867100 I | op-mon: sched-mon: created canary deployment rook-ceph-mon-d-canary
2019-12-11 07:53:44.880865 I | op-mon: sched-mon: waiting for canary pod creation rook-ceph-mon-d-canary
2019-12-11 07:53:49.892633 I | op-mon: sched-mon: canary monitor deployment rook-ceph-mon-d-canary scheduled to ku-worker-01.karmalabs.com
2019-12-11 07:53:49.892677 I | op-mon: assignmon: mon d assigned to node ku-worker-01.karmalabs.com
2019-12-11 07:53:49.892707 I | op-mon: assignmon: cleaning up canary deployment rook-ceph-mon-d-canary and canary pvc 
2019-12-11 07:53:49.892720 I | op-k8sutil: removing deployment rook-ceph-mon-d-canary if it exists
2019-12-11 07:53:49.899387 I | op-k8sutil: Removed deployment rook-ceph-mon-d-canary
2019-12-11 07:53:49.907742 I | op-k8sutil: rook-ceph-mon-d-canary still found. waiting...
2019-12-11 07:53:51.913738 I | op-k8sutil: rook-ceph-mon-d-canary still found. waiting...
2019-12-11 07:53:53.916377 I | op-k8sutil: confirmed rook-ceph-mon-d-canary does not exist
2019-12-11 07:53:53.925454 I | op-mon: mon d endpoint are [v2:10.96.79.253:3300,v1:10.96.79.253:6789]
2019-12-11 07:53:53.952911 I | op-mon: waiting for mon quorum with [d]
2019-12-11 07:53:53.988948 I | op-mon: mon d is not yet running
2019-12-11 07:53:53.988967 I | op-mon: mons running: []
2019-12-11 07:53:53.989069 I | exec: Running command: ceph quorum_status --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/295475575
2019-12-11 07:53:54.538100 I | op-mon: Monitors in quorum: [b c]
2019-12-11 07:53:54.538116 I | op-mon: mons created: 1
2019-12-11 07:53:54.538192 I | exec: Running command: ceph versions --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/034882154
2019-12-11 07:53:55.004500 I | op-mon: waiting for mon quorum with [d]
2019-12-11 07:53:55.009137 I | op-mon: mon d is not yet running
2019-12-11 07:53:55.009157 I | op-mon: mons running: []
2019-12-11 07:54:00.025702 I | op-mon: mons running: [d]
2019-12-11 07:54:00.026099 I | exec: Running command: ceph quorum_status --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/611451585
2019-12-11 07:54:07.215252 I | op-mon: Monitors in quorum: [b c d]
2019-12-11 07:54:07.215278 I | op-mon: ensuring removal of unhealthy monitor a
2019-12-11 07:54:07.217840 I | op-mon: dead mon rook-ceph-mon-a was already gone
2019-12-11 07:54:07.217964 I | exec: Running command: ceph mon remove a --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/488797851
2019-12-11 07:54:07.664429 I | exec: removing mon.a at [v2:10.96.167.131:3300/0,v1:10.96.167.131:6789/0], there will be 3 monitors
2019-12-11 07:54:07.664508 I | op-mon: removed monitor a
2019-12-11 07:54:07.711110 I | op-mon: saved mon endpoints to config map map[data:b=10.96.191.161:6789,c=10.96.110.94:6789,d=10.96.79.253:6789 maxMonId:3 mapping:{"node":{"b":{"Name":"ku-worker-00.karmalabs.com","Hostname":"ku-worker-00.karmalabs.com","Address":"192.168.122.34"},"c":{"Name":"ku-worker-02.karmalabs.com","Hostname":"ku-worker-02.karmalabs.com","Address":"192.168.122.62"},"d":{"Name":"ku-worker-01.karmalabs.com","Hostname":"ku-worker-01.karmalabs.com","Address":"192.168.122.243"}}} csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["10.96.191.161:6789","10.96.110.94:6789","10.96.79.253:6789"]}]]
2019-12-11 07:54:07.721704 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2019-12-11 07:54:07.721978 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
```




### Test 2:
Delete a mon deployment and restart the operator.

Used this commands:
```
# kubectl -n rook-ceph delete deployment rook-ceph-mon-b
# kubectl scale deployment rook-ceph-operator --replicas=0 -n rook-ceph
# kubectl scale deployment rook-ceph-operator --replicas=1 -n rook-ceph
```

**Result:**
No canary pods in Pending state. The deleted monitor deployment is recovered after 15 minutes.


### Test 3:
Kill a node where a mon pod lives, this is a different node from the one running the operator pod.

**Result:**
No canary pods in "pending" state. Only the pods in the stopped node are in "terminating" state. (because scheduled in the stopped node)
Once the node is recovered these pods are finally removed.

Check the reason of the pods in "Pending" state
```
# kubectl -n rook-ceph describe pod rook-ceph-mon-b-857cc869dd-55wrn

....
Node-Selectors:  kubernetes.io/hostname=ku-worker-00.karmalabs.com

Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 3 node(s) didn't match node selector.
```

### Test 4:
Kill a node (ku-worker-01) with a mon and the operator pod.

**Result:**
There are no pending canary pods, and the pods that remain in this is state is because they are scheduled for the Node stopped.
The pods in "Terminating" state, are removed when the stopped node is started again. 
```

# kubectl get pod -o=custom-columns=NAME:.metadata.name,STATUS:.status.phase,NODE:.spec.nodeName -n rook-ceph | grep ku-worker-01.karmalabs.com
csi-cephfsplugin-provisioner-6c7d6f4964-5kq9p                     Running     ku-worker-01.karmalabs.com
csi-cephfsplugin-z6698                                            Running     ku-worker-01.karmalabs.com
csi-rbdplugin-7tvfh                                               Running     ku-worker-01.karmalabs.com
rook-ceph-crashcollector-ku-worker-01.karmalabs.com-5df86bl5mcd   Running     ku-worker-01.karmalabs.com
rook-ceph-mgr-a-7864c6c598-8qgwx                                  Running     ku-worker-01.karmalabs.com
rook-ceph-mon-d-7845db97f-krc79                                   Running     ku-worker-01.karmalabs.com
rook-ceph-operator-7cbfbf4ddc-rbf8p                               Running     ku-worker-01.karmalabs.com
rook-ceph-osd-0-748f8d494c-lr9qj                                  Running     ku-worker-01.karmalabs.com
rook-ceph-osd-prepare-ku-worker-01.karmalabs.com-75tjt            Succeeded   ku-worker-01.karmalabs.com
rook-discover-qttss                                               Running     ku-worker-01.karmalabs.com


# kubectl -n rook-ceph get pods | grep Pending
rook-ceph-crashcollector-ku-worker-01.karmalabs.com-5df86bb8c68   0/1     Pending       0          25m
rook-ceph-mon-d-7845db97f-bwgzx                                   0/1     Pending       0          25m
rook-ceph-osd-0-748f8d494c-mb7r2                                  0/1     Pending       0          25m

# kubectl -n rook-ceph get pods | grep Terminating
csi-cephfsplugin-provisioner-6c7d6f4964-5kq9p                     4/4     Terminating   0          163m
rook-ceph-crashcollector-ku-worker-01.karmalabs.com-5df86bl5mcd   1/1     Terminating   0          162m
rook-ceph-mgr-a-7864c6c598-8qgwx                                  1/1     Terminating   0          63m
rook-ceph-mon-d-7845db97f-krc79                                   1/1     Terminating   0          147m
rook-ceph-operator-7cbfbf4ddc-rbf8p                               1/1     Terminating   0          131m
rook-ceph-osd-0-748f8d494c-lr9qj                                  1/1     Terminating   0          160m

```

Check reason of pods in "Pending" state:

```
# kubectl -n rook-ceph describe pod rook-ceph-mon-d-7845db97f-bwgzx

...

Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 3 node(s) didn't match node selector.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 3 node(s) didn't match node selector.

```

**Comment by travisn** [comment]
@jmolmo Try the following scenario, similar to your last scenario:
- Start a cluster with three worker nodes, three mons and `allowMultiplePerNode: false`. There will be no nodes for failover
- Stop one of the nodes. All the pods from that node will go to terminating/pending
- Wait for the mon timeout of 10 minutes (note that you can reduce this timeout for faster testing with [these settings](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L125-L131)
- After the timeout, see that the operator attempts to failover the mon and start a new mon. This mon canary will stay pending because there is no available node
- Start the failed node again. The original pods will all return to running state
- The new canary pod for the mon failover will remain in pending. The operator could delete it and abort the failover since the original mon came back up. But instead, the operator just ignores it and leaves it there. Perhaps during the operator's mon health check it needs to delete any extra mon canaries if a failover is no longer needed.

**Comment by kevinsingapore** [comment]
and now ,how to sovle the problem? i also have meet the error, and the osds art not in & up，then how to deal with it? thank u!

**Comment by travisn** [comment]
@kevinsingapore If the OSDs are not up, this is a different issue. Try the [troubleshooting guide](https://rook.github.io/docs/rook/v1.3/ceph-common-issues.html) or you can ask in the rook slack as well.
