### ISSUE TITLE
Handle errors reported by gosec tool

### ISSUE THREAD

**Issue by travisn** [rook/rook#3765]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
gosec reports ~100 issues of various severity levels.

**Expected behavior:**
When running the gosec tool we should see a clean report, or else suppress the failures that we don't expect to be fixed. 

**How to reproduce it (minimal and precise):**

```
$GOPATH/bin/gosec pkg/... -severity=medium
...

Summary:
   Files: 449
   Lines: 67632
   Nosec: 0
  Issues: 96
```
Results are in attached log:
[gosec.log](https://github.com/rook/rook/files/3571682/gosec.log)

Some of these failures we do not need to worry about and can suppress. For example, there are several complaints about hard-coded creds that are just variable names.
```
[/Users/travisn/src/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/dashboard.go:41] - G101: Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
  > dashboardPasswordName          = "rook-ceph-dashboard-password"
```

**Comment by mykaul** [comment]
Bad bot, how can I reopen this?

**Comment by nizamial09** [comment]
> [/Users/travisn/src/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/dashboard.go:41] - G101: Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
>   > dashboardPasswordName          = "rook-ceph-dashboard-password"
> ```

@travisn This is being detected by the `gosec` because the variable contains the phrase Password right? So, for these kind of issues we can just comment `#nosec` and it will ignore the check for the variables. Is that will be enough or we want to change the variable name everywhere?

**Comment by travisn** [comment]
Adding `#nosec` sounds good if that will suppress it. Obviously this isn't a password. It's a password name :)

**Comment by nizamial09** [comment]
> Adding `#nosec` sounds good if that will suppress it. Obviously this isn't a password. It's a password name :)

Obviosuly :D. I will make the necessary changes and push in a PR

**Comment by travisn** [comment]
Currently running the command gives this output:
```
$GOPATH/bin/gosec pkg/... -severity=medium
...
Summary:
   Files: 517
   Lines: 81048
   Nosec: 7
  Issues: 58
```

We should focus on fixing these issues:
- G104: Errors unhandled. These should only be suppressed if we really can ignore the errors. It is uncommon to ignore errors except in certain scenarios such as install that are "best-effort".
- G302: Expect file (or directory) permissions to be ... (tracked by #4580) 

These issues can be suppressed
- G204: Subprocess launching should be audited. All of these instances are expected, and neither is it configurable by the admin to input which process are launched. This is only an implementation detail of the operators.
- G304: Potential file inclusion via variable. These instances are expected and also not configurable by parameters to the operator.
- G101: Potential hardcoded credentials. These instances are just variable names, not any real secrets.

**Comment by subhamkrai** [comment]
We have other issues (error code) apart from other codes mentioned above like G109, G404, G601, G306, G307.
(for reference all [error code](https://github.com/securego/gosec#available-rules) explained.)

**Comment by travisn** [comment]
G109: Potential Integer overflow made by strconv.Atoi result conversion to int16/32
- Depends on the case, but we can suppress these unless they involve user input from a CR
G404: Insecure random number source (rand)
- IIRC we need to use `crypto/rand` instead of `math/rand`
G601: Implicit memory aliasing of items from a range statement
- Examples?
G306: Poor file permissions used when writing to a new file
- Covered by #4580
G307: Deferring a method which returns an error
- In test code we can ignore this, but need to see examples for production code

**Comment by subhamkrai** [comment]
G404: Yes, we need to use `crypto/rand` instead of `math/rand`.

G601:  example 
[file](https://github.com/rook/rook/blob/master/pkg/operator/ceph/test/containers.go#L231) - G601 (CWE-118): Implicit memory aliasing in for loop. (Confidence: MEDIUM, Severity: MEDIUM) 
```
    230: 	for _, c := range ct.containers {
  > 231: 		for _, v := range varNames(&c) {
    232: 
```

G307: example
[file](https://github.com/rook/rook/blob/master/pkg/daemon/ceph/osd/volume.go#L657) - G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File" (Confidence: HIGH, Severity: MEDIUM)
```  
  656: 	}
  > 657: 	defer cvLogFile.Close()
    658: 
```

**Comment by travisn** [comment]
Reopening until all are resolved...
