### ISSUE TITLE
Pick up ceph-csi v1.2.0 before Rook v1.1 release

### ISSUE THREAD

**Issue by travisn** [rook/rook#3766]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook is currently using the ceph-csi `canary` image tag. We cannot ship v1.1 with this version of the csi driver. We must reference a release version. We are dependent on the next version of csi which is v1.2 due anytime now.

**Expected behavior:**
Rook should reference ceph-csi v1.2
@Madhu-1 Could you update this in rook when the ceph-csi v1.2 release is cut? Thanks!

**How to reproduce it (minimal and precise):**

**Comment by Madhu-1** [comment]
yes @travisn will do it
