### ISSUE TITLE
Ceph Dashboard continually throwing Server Error 500

### ISSUE THREAD

**Issue by jedblack** [rook/rook#3783]
**Is this a bug report or feature request?**

* Bug Report

**Deviation from expected behavior:**
Yes
**Expected behavior:**
Not to throw server error 500

**How to reproduce it (minimal and precise):**
Deploy the latest version(at time of writing v1.06)

**File(s) to submit**:

Manager Pod Logs
[ceph-rook-mgr-pod-logs.txt](https://github.com/rook/rook/files/3580441/ceph-rook-mgr-pod-logs.txt)c

**Environment**:
* OS (e.g. from /etc/os-release):
`
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
`
* Kernel (e.g. `uname -a`):
`Linux kubenode01 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
`v1.06`
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
`
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
`upstream k8s on vmware vm's`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@jmolmo could you take a look?

**Comment by jedblack** [comment]
Thanks everyone, on the slack channel someone suggested I upgrade CEPH to fix this issue as its not related to rook specifically.  I upgraded to 14.2.3 and the issue is now resolved.
