### ISSUE TITLE
configure monmap, osdmap and crushmap

### ISSUE THREAD

**Issue by Liuxiayu** [rook/rook#3809]
Hi everyone, I want to know how to configure and where to configure monmap, osdmap and crushmap

**Comment by travisn** [comment]
@Liuxiayu Configuration of Ceph from Rook can be done with the [toolbox](https://rook.io/docs/rook/v1.0/ceph-toolbox.html) pod. But Rook does its best to hide the details of these configurations so it isn't expected you will commonly need to configure them. For further questions you can join the [Rook Slack](https://github.com/rook/rook#contact) where it would be great to discuss your requirements in more detail.
