### ISSUE TITLE
Scalability issue

### ISSUE THREAD

**Issue by DonAndrey** [rook/rook#3812]
* Bug Report

Hello, today I performed a test where basically I added a new node to the ceph cluster. As expected rook operator started all the necessary process to include the new node to the cluster.
After that process and do some tests, I decided to remove a node from the ceph cluster just to see the behavior of the rook operator and see if the corresponding osd pods was deleted, but nothing happened, the osd pod is still there and the osd deployment too. 
The rook operator logs show say that the node was removed, but the strange thing is it wasn't reflected on the pod or deployment.

**Expected behavior:**
I expected that pod and deployment were removed from the cluster.
**How to reproduce it (minimal and precise):**

- Edit the cephcluster: kubectl edit cephcluster rook-ceph -n rook-ceph
- Add a new node to the node list
- Then do the last two steps but to remove one of the nodes.

**Environment**:
* Rook version : rook/ceph:v1.0.3
* Storage backend version: ceph/ceph:v14.2.1-20190430
* Kubernetes version: 1.13.3

**Comment by leseb** [comment]
I don't remember exactly but I *think* we have a timeout to remove the old osd deployments, so yes I think it's accepted that it does not happen right away. I think it's an hour or something.

@travisn do you know?

**Comment by travisn** [comment]
In the v1.1 release we will remove the OSD pod if it is marked as safe-to-destroy (after all its data has been backfilled). The hour timeout is only used if the osd was just created less than an hour ago. @DonAndrey If you're running on v1.0.3, it's expected that the osd won't be removed.

**Comment by DonAndrey** [comment]
Thanks for the information @leseb  and @travisn .
