### ISSUE TITLE
Support Ceph iSCSI Gateway

### ISSUE THREAD

**Issue by aarnaud** [rook/rook#3831]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Kubernetes krbd driver doesn't support latest rbd imgae features. Although rbd-nbd driver supports those features, RHEL/Centos have builtin nbd driver, so it is not easy to use rbd-nbd driver.

We can use Ceph iSCSI gateway and iSCSI volume to use rbd images that have features not supported in krbd.

**What is use case behind this feature:**
We can add kubernetes windows node with iSCSI after.

**Environment**:
Hybrid cluster

**Comment by aarnaud** [comment]
Same as https://github.com/rook/rook/issues/1865

**Comment by aarnaud** [comment]
https://docs.ceph.com/docs/mimic/rbd/iscsi-overview/
https://docs.ceph.com/docs/mimic/rbd/iscsi-target-cli/

**Comment by nistiwar** [comment]
Any plans in the roadmap to support this..

**Comment by leseb** [comment]
> Any plans in the roadmap to support this..

Not really.

**Comment by jc-lab** [comment]
+1

If it supports iscsi gateway, third parties such as VMWare will be able to use ceph.

**Comment by abh** [comment]
See also #4334
