### ISSUE TITLE
Helm: Role bindings are missing for pod security policies

### ISSUE THREAD

**Issue by laevilgenius** [rook/rook#3851]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** Helm chart doesn't work with enabled Pod Security Policies

**Environment**:
* Rook version: v1.1.0
* Kubernetes version: v1.15.3

I believe these bindings are missing: https://github.com/rook/rook/blob/82a2d018a2fb201878a1169b897588580b38673d/cluster/examples/kubernetes/ceph/common.yaml#L1158-L1212

**Comment by laevilgenius** [comment]
@travisn can we fix it in a patch release for `v1.1`?

**Comment by travisn** [comment]
@jmolmo Is investigating it. I'd expect it to be in the next patch release.
