### ISSUE TITLE
OSD on PVC: Accommodate multiple devices per OSD when using a StorageClassDeviceSet

### ISSUE THREAD

**Issue by ron1** [rook/rook#3852]
* Feature Request

**What should the feature do:**
When using a StorageClassDeviceSet to configure OSDs, allow multiple volumeClaimTemplates with different storageClassNames to be defined as described in the following example: https://github.com/rook/rook/blob/master/design/ceph/storage-class-device-set.md#example-5-multiple-devices-per-osd. This is needed to achieve optimal performance by allowing metadata to be stored on an SSD PVC and data to be stored on a HDD PVC.

**Environment**:
Rook 1.1 on OCP 3.11

**Comment by leseb** [comment]
https://github.com/ceph/ceph/pull/32828

**Comment by leseb** [comment]
My thinking for this would be to have another `storageClass` from which we would request storage too, not a block device. Following the PVC mindset, we should be claiming for a certain amount of storage of a particular type, then we would use it as a metadata device for Bluestore.
We can have up to 3 `storageClass` in the end:

1. block: the main OSD data store
2. db: rocksdb database
3. wal: rocksdb write-ahead log

Currently, number 3 requires a super fast device and we won't likely get it from any cloud provider.
