### ISSUE TITLE
rook vs  ceph-ansible

### ISSUE THREAD

**Issue by Liuxiayu** [rook/rook#3853]
Hello, I wonder what benefits rook-ceph has compared to ceph-ansible

**Comment by joshuacox** [comment]
Does ceph-ansible work? 

I am very interested in utilizing ceph but I have yet to see rook-ceph work.  I have an [issue here](https://github.com/rook/rook/issues/3748), despite having tried it in many different environments the results are always the same.

**Comment by Liuxiayu** [comment]
I wonder what benefits rook-ceph has compared to ceph-ansible.

**Comment by leseb** [comment]
It's difficult to compare them, I'd say they are two different worlds. Rook leverages various Kubernetes features such as auto-scaling, healing, daemon's recovery, node discovery where ceph-ansible is more "static", if something fails only systemd will try to restart the daemon and it won't try to reschedule anything on another node. For node addition, you need to edit a yaml file.

ceph-ansible is really easy to get your hands on, Rook relies on Kubernetes as a foundation to run so you will need to ramp up on Kubernetes as well and maintain both wherewith ceph-ansible only Ceph needs to be learned. Also, it's much older as a project.

At the end of the day, both have their pros and cons so it's really up to you but I really encourage you to try both and see which one suits your needs best after testing.
