### ISSUE TITLE
Allow specification of CSI Docker image registry in Rook Helm Chart

### ISSUE THREAD

**Issue by stephan2012** [rook/rook#3855]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The Helm Chart for Rook v1.1.0 should include values for the CSI images so Rook with CSI can pull the required images from a private container registry. This is required when a Kubernetes cluster is not Internet connected. In `rook-ceph-v1.1.0-beta.0.79.gaf60060`, these values are not available.

At the moment, the deployment has to be patched to include environment variables for `ROOK_CSI_REGISTRAR_IMAGE`, `ROOK_CSI_PROVISIONER_IMAGE`, `ROOK_CSI_SNAPSHOTTER_IMAGE`, `ROOK_CSI_ATTACHER_IMAGE`, and `ROOK_CSI_CEPH_IMAGE`. More may be missing.

**What is use case behind this feature:**
Use Rook and Ceph on non-Internet connected (air-gap) Kubernetes clusters.

**Environment**:

See above.

**Comment by travisn** [comment]
@Madhu-1 could you take a look?

**Comment by Madhu-1** [comment]
@travisn sure

**Comment by stephan2012** [comment]
Cool, thanks!
