### ISSUE TITLE
Rename ClusterStatus.State to ClusterStatus.Phase in CephCluster CRD

### ISSUE THREAD

**Issue by umangachapagain** [rook/rook#3859]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Change the CephCluster CRD status spec from ClusterStatus.State to ClusterStatus.Phase. This does not bring in new functionality but helps to integrate CephCluster Status into OLM user Interface.

**What is use case behind this feature:**
Currently, CephCluster stores system state in .Status.State spec. However, OLM expects it to be at .Status.Phase (it is very opioniated). So, by renaming `state` to `phase`, we get the best of both worlds. This makes experience much smoother to the OLM users without any impact on others.

**Environment**:

Kubernetes/Openshift with OLM deployed.

**Comment by umangachapagain** [comment]
@travisn @leseb What do you guys think about this? Can we target this for 1.1.1? Or, since it is a CRD change, this should probably go in 1.2?

**Comment by leseb** [comment]
I guess I'm also worried about breaking backward compatibility, which might mean having both.

**Comment by umangachapagain** [comment]
Is having both a good idea? (Redundant Information)
We could add both and eventually deprecate use of .Status.State in later releases. But, this is not a "must have" so we can look at what is justified from Rook's perspective.

If we are fine with having both, I'd also like to propose adding .Spec.Version which is equivalent to .Spec.CephVersion. This will report Ceph Version to OLM UI.

These are the things being frequently requested by OLM UI users.

**Comment by umangachapagain** [comment]
@nizamial09 See this.

**Comment by leseb** [comment]
I guess I should have said "both for a certain period of time" :-). If there is a really high demand from OLM users then this could be a reason why Rook would do this.

**Comment by travisn** [comment]
@umangachapagain What are the requirements for the OLM `phase`? The status has custom behavior that may not be expected anyway so copying it over may not satisfy what OLM is looking for:
- Rook defines its own states. Does OLM expect certain states?
- Every time the operator starts an orchestration, the states are updated. This may cause confusion to the average user looking at the UI. To make it less confusing, we should review the behavior

**Comment by umangachapagain** [comment]
> @umangachapagain What are the requirements for the OLM `phase`? The status has custom behavior that may not be expected anyway so copying it over may not satisfy what OLM is looking for:
> 
>     * Rook defines its own states. Does OLM expect certain states?
> 
It just expects a .Status.Phase spec. We can choose what (string) values it can have. Since, we are trying to reflect the overall system status which .Status.State already does, copying it over shouldn't be an issue. 
>     * Every time the operator starts an orchestration, the states are updated. This may cause confusion to the average user looking at the UI. To make it less confusing, we should review the behavior
>
This is the most realistic system state information that we can provide. However, agreed that it will create confusion to a lot of users.

What do you suggest are the appropriate Phases?

My thought:
`Ignored` : For resources that are ignored. Like multiple CephCluster CR in same Namespace?
`Progressing` : When Reconcile starts
`Ready` : When Reconcile completes successfully
`Not Ready` : When Upgrading? Or when Upgrading is blocked? 
`Available or Healthy` : When Ceph Cluster is healthy
`Error` : When anything fails

Also, something that just came to my notice : https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
It advocates the use of .Status.Conditions and says .Status.Phase is deprecated due to some contradictions.

This does mean we break OLM compatibility by not having .Status.Phase but this could be the right thing to do (maybe  we can request OLM to change what they do).

**Comment by nizamial09** [comment]
Hey,
I am new to this Open source coding platform. This is my first project. Any way I added the ClusterStatus.Phase and assigned it with ClusterStatus.State. But when I try to build the file it returns the below error:

make[1]: *** [build/makelib/golang.mk:161: go.vet] Error 2
make: *** [Makefile:102: build.common] Error 2

Any idea why this issue pops up.

**Comment by travisn** [comment]
> This does mean we break OLM compatibility by not having .Status.Phase but this could be the right thing to do (maybe we can request OLM to change what they do).

What does it mean to break OLM compatibility? OLM still works without this, right? Seems like we aren't doing the right thing by adding a property that is deprecated. We should also review the values we actually want to show to the user. This seems like a bigger work item to do the right thing.

@nizamial09 Did you check out the [developer guide](https://rook.io/docs/rook/v1.1/development-flow.html) to setup your build environment?

**Comment by nizamial09** [comment]
@travisn Yeah I did everything as in the developer guide. I've tried cloning the repository into another directory and still it gives this error.

**Comment by umangachapagain** [comment]
> What does it mean to break OLM compatibility? 
>
I meant OLM UI.
>
> OLM still works without this, right?
>
Yes. It does.
>
> Seems like we aren't doing the right thing by adding a property that is deprecated. We should also review the values we actually want to show to the user. This seems like a bigger work item to do the right thing.
>
Agreed. We should look at enabling `status.Conditions` with necessary state information.

**Comment by nizamial09** [comment]
status.Conditions design document is being reviewed over here: https://github.com/rook/rook/pull/4066
Drop-in your suggestions over there. Thanks.
