### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by yizhishang** [rook/rook#3866]
| Unable to mount volumes for pod  "nginx-688c4d48cb-xljz9_default(a6cb67b2-d86d-11e9-a9a3-000c291bfc6d)":  timeout expired waiting for volumes to attach or mount for pod  "default"/"nginx-688c4d48cb-xljz9". list of unmounted  volumes=[http-file]. list of unattached volumes=[http-file  default-token-hmsm9]
-- | --
![image](https://user-images.githubusercontent.com/12756407/64951897-872a0600-d8b1-11e9-9790-0018cfcfafbe.png)
i install rook/ceph like this:
```shell
git clone https://github.com/rook/rook.git
git checkout remotes/origin/release-1.0
cd rook/cluster/examples/kubernetes/ceph

kubectl apply -f common.yaml
kubectl apply -f operator.yaml
kubectl apply -f cluster-test.yaml
kubectl apply -f storageclass-test.yaml
kubectl apply -f toolbox.yaml
kubectl apply -f dashboard-ingress-https.yaml
```
then i install an example like 
```shell
cat << EOF > nginx.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports: 
  - port: 80
    name: nginx-port
    targetPort: 80
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /html
          name: http-file
      volumes:
      - name: http-file
        persistentVolumeClaim:
          claimName: nginx-pvc
EOF

kubectl apply -f nginx.yaml
```

then i got this error "pod has unbound immediate PersistentVolumeClaims"

**Comment by galexrt** [comment]
@yizhishang You are not specifying the right `storageClassName` to use in the PVC.
The example file `storageclass-test.yaml` (https://github.com/rook/rook/blob/release-1.0/cluster/examples/kubernetes/ceph/storageclass-test.yaml) has a `StorageClass` named `rook-ceph-block` you are trying to use a StorageClass named just `ceph`, you need to change that to fit the `StorageClass` `rook-ceph-block` you created with the examples files.

**Comment by yizhishang** [comment]
@galexrt yes, you're right.
but even if i modify the storegeclass to "rook-ceph-block", it still go wrongs

**Comment by wigilanto** [comment]
Hello! I see you closed the subject. I would know if you found the solution by yourself please
