### ISSUE TITLE
Missing ServiceAccounts for csi

### ISSUE THREAD

**Issue by monester** [rook/rook#3868]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Service accounts `rook-csi-cephfs-provisioner-sa` and `rook-csi-rbd-provisioner-sa` for CSI aren't created after upgrade to 1.1, and there is no mention of manual creation requirement in upgrade documentation.
In replicasets on describe services following errors:
```
Events:
  Type     Reason            Age                 From                   Message
  ----     ------            ----                ----                   -------
  Warning  FailedCreate      20m (x21 over 75m)  replicaset-controller  Error creating: pods "csi-rbdplugin-provisioner-5dd69bb477-" is forbidden: error looking up service account rook-ceph/rook-csi-rbd-provisioner-sa: serviceaccount "rook-csi-rbd-provisioner-sa" not found
```

**Expected behavior:**
Service account for CSI is created by upgrade patch from 1.0 to 1.1

**How to reproduce it (minimal and precise):**

Install rook 1.0 using examples in `cluster/examples/kubernetes/ceph`, then follow upgrade procedure on https://rook.io/docs/rook/v1.1/ceph-upgrade.html.  

**File(s) to submit**:

No files to submit.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.2
* Kernel (e.g. `uname -a`): 4.15.0-47-generic
* Cloud provider or hardware configuration: On premiss
* Rook version (use `rook version` inside of a Rook Pod): 1.1.0
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.3
* Kubernetes version (use `kubectl version`): 1.14.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
It appears we missed adding the CSI RBAC to the upgrade-from-v1.0-create.yaml manifest. @Madhu-1 could you take a look?

**Comment by eknudtson** [comment]
It looks like a few other items from common.yaml are missing from the upgrade-from-v1.0-create.yaml, namely the `rook-privileged` podSecurityPolicy and associated RBAC resources

**Comment by Madhu-1** [comment]
@travisn this service account should be  created in v1.0 itself and its present in v1.0 rbac folder
https://github.com/rook/rook/blob/v1.0.6/cluster/examples/kubernetes/ceph/csi/rbac/rbd/csi-provisioner-rbac.yaml#L4 https://github.com/rook/rook/blob/v1.0.6/cluster/examples/kubernetes/ceph/csi/rbac/cephfs/csi-provisioner-rbac.yaml#L4

let me know anything else is required

**Comment by travisn** [comment]
@Madhu-1 Clusters that were created before v1.1 will not have the csi driver configured by default. We need all of those clusters to be configured for CSI during the upgrade process to v1.1. The method for doing this is described in the "Update Modified Permissions" section of the [Ceph Upgrade Guide](https://rook.io/docs/rook/v1.1/ceph-upgrade.html). In that section the admin is instructed to create new resources in `upgrade-from-v1.0-create.yaml`. So we will need to add the CSI resources to that file. So we'll need to add the CSI ServiceAccounts and other RBAC to this file. Could you open a PR for that? thanks

**Comment by Madhu-1** [comment]
@travisn before opening a PR I have few questions
* what if the csi driver is deployed with the release 1.0.x as CSI was experimental, to which file the CSI updates should go to.
* if CSI is not deployed to which file I need to add all CSI roles and SA
* if CSI was deployed by v1.0.x in Kubernetes 1.14.x (earlier we used to deploy provisioner as the statefulset with rook 1.1.0 we are deploying the provisioner as deployment if kube version is greater than 1.14.x (do we need to document the user to delete the statefulset which was created earlier as this can cause inconsistency in PVC creation)

**Comment by travisn** [comment]
> what if the csi driver is deployed with the release 1.0.x as CSI was experimental, to which file the CSI updates should go to.

If they deployed the 1.0 experimental driver, some/most/all of these service accounts and RBAC will already exist, right? I'd suggest we add them to the create.yaml and put a note in the upgrade guide that they can ignore errors about the resources already existing if they had installed the csi driver. But if the resources have changed and needed to be updated, we may need a new step in the upgrade guide just for the users who installed csi in v1.0. That extra step might be to just delete the csi resources before creating the new v1.1 resources, but it really depends on what is needed in this case.

> if CSI is not deployed to which file I need to add all CSI roles and SA

The create.yaml is likely the right place so the majority of users won't need an extra step for upgrade. If csi users need an extra step during upgrade that's fine.

> if CSI was deployed by v1.0.x in Kubernetes 1.14.x (earlier we used to deploy provisioner as the statefulset with rook 1.1.0 we are deploying the provisioner as deployment if kube version is greater than 1.14.x (do we need to document the user to delete the statefulset which was created earlier as this can cause inconsistency in PVC creation)

Yes, makes sense to document deleting the statefulset in this case.

**Comment by Madhu-1** [comment]
@travisn Thanks for clarifying the doubts I will make a PR
