### ISSUE TITLE
ceph-mgr errors with KeyError mimic in rook 1.1.0 and Nautilus 14.2.3

### ISSUE THREAD

**Issue by christianhuening** [rook/rook#3873]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After starting the mgr pod issues the following logs over and over again

```
[16/Sep/2019:14:44:33] HTTP
Request Headers:
  HOST: 10.6.70.14:9283
  X-PROMETHEUS-SCRAPE-TIMEOUT-SECONDS: 5.000000
  Remote-Addr: ::ffff:10.6.69.4
  ACCEPT: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
  USER-AGENT: Prometheus/2.12.0
  ACCEPT-ENCODING: gzip
::ffff:10.6.69.4 - - [16/Sep/2019:14:44:33] "GET /metrics HTTP/1.1" 500 1733 "" "Prometheus/2.12.0"
debug 2019-09-16 14:44:34.098 7f79b18b6700  0 log_channel(cluster) log [DBG] : pgmap v411: 1212 pgs: 1212 active+clean; 2.6 TiB data, 5.5 TiB used, 5.7 TiB / 11 TiB avail; 767 B/s rd, 11 MiB/s wr, 311 op/s
::ffff:10.6.70.1 - - [16/Sep/2019:14:44:34] "GET / HTTP/1.1" 200 155 "" "kube-probe/1.15"
[16/Sep/2019:14:44:34] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/prometheus/module.py", line 1054, in metrics
    return self._metrics(instance)
  File "/usr/share/ceph/mgr/prometheus/module.py", line 1068, in _metrics
    instance.collect_cache = instance.collect()
  File "/usr/share/ceph/mgr/prometheus/module.py", line 918, in collect
    self.get_mgr_status()
  File "/usr/share/ceph/mgr/prometheus/module.py", line 490, in get_mgr_status
    always_on_modules = mgr_map['always_on_modules'][ceph_release]
KeyError: 'mimic'
```

I did not yet run the feature update to nautilus since the upgrade is not yet completed.

**Expected behavior:**
ceph mgr works as normal without this error.

**Environment**:
* OS (e.g. from /etc/os-release): containerlinux
* Kernel (e.g. `uname -a`): 
* Cloud provider or hardware configuration: bare-metal
* Rook version (use `rook version` inside of a Rook Pod): v1.1.0
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.3
* Kubernetes version (use `kubectl version`): 1.15.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare-metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
> I did not yet run the feature update to nautilus since the upgrade is not yet completed.

@christianhuening The title of the issue says this happens with ceph v14.2.3, but your comment says you haven't yet updated to nautilus. Can you clarify the repro steps? thanks

**Comment by christianhuening** [comment]
@travisn I am halfway through. mgr and mons are on 14.2.4 already, 2 of the OSDs as well. The remaining bits not yet. This is the condition this is happening in.

**Comment by travisn** [comment]
@sebastian-philipp any ideas on this failure in the mgr modules?

**Comment by sebastian-philipp** [comment]
https://tracker.ceph.com/issues/41878

**Comment by christianhuening** [comment]
@sebastian-philipp sorry i have a typo in there where it says I would be on 14.2.4. of course I am on 14.2.3. I am afraid you copied that over to the ceph issue tracker.

**Comment by sebastian-philipp** [comment]
As a workaround, you could make sure, all host versions displayed in the ceph dashboard show `nautilus`

**Comment by christianhuening** [comment]
the login for the dashboard does not work sadly... 
Throws this:

> ERROR Error: "Uncaught (in promise): t: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"Internal Server Error","url":"https://ceph.dev.figo.systems/api/auth","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://ceph.dev.figo.systems/api/auth: 500 Internal Server Error","error":{"status":"500 Internal Server Error","version":"3.2.2","detail":"The server encountered an unexpected condition which prevented it from fulfilling the request.","traceback":"Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 656, in respond\n    response.body = self.handler()\n  File \"/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py\", line 188, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cptools.py\", line 221, in wrap\n    return self.newhandler(innerfunc, *args, **kwargs)\n  File \"/usr/share/ceph/mgr/dashboard/services/exception.py\", line 88, in dashboard_exception_handler\n    return handler(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py\", line 34, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"/usr/share/ceph/mgr/dashboard/controllers/__init__.py\", line 649, in inner\n    ret = func(*args, **kwargs)\n  File \"/usr/share/ceph/mgr/dashboard/controllers/__init__.py\", line 842, in wrapper\n    return func(*vpath, **params)\nTypeError: create() got an unexpected keyword argument 'stay_signed_in'\n"}}"

**Comment by sebastian-philipp** [comment]
```
"status":"500 Internal Server Error","version":"3.2.2",
"detail":"The server encountered an unexpected condition which prevented it from fulfilling the request.",
"traceback":"
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
     response.body = self.handler()
 File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in call
     self.body = self.oldhandler(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/cherrypy/_cptools.py", line 221, in wrap
     return self.newhandler(innerfunc, *args, **kwargs)
 File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 88, in dashboard_exception_handler
     return handler(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in call
     return self.callable(*self.args, **self.kwargs)
 File "/usr/share/ceph/mgr/dashboard/controllers/init.py", line 649, in inner
     ret = func(*args, **kwargs)
 File "/usr/share/ceph/mgr/dashboard/controllers/init.py", line 842, in wrapper
     return func(*vpath, **params)
TypeError: create() got an unexpected keyword argument 'stay_signed_in'
```

**Comment by epuertat** [comment]
Isn't this the same as https://github.com/rook/rook/issues/3424 (https://tracker.ceph.com/issues/40754) ? `stay_signed_in` is a login property from Mimic that was removed in Nautilus. It remains in the stale cached HTML/JS assets. Refreshing any intermediate proxy/caching layer should resolve this.

**Comment by christianhuening** [comment]
@epuertat yeah that was my local browser cache, sorry...

**Comment by sebastian-philipp** [comment]
Nevertheless, might make sense to improve the UX here.

**Comment by epuertat** [comment]
> @epuertat yeah that was my local browser cache, sorry...

Great, @christianhuening! Not sure how we can avoid these quirks without losing cache efficiency.

> Nevertheless, might make sense to improve the UX here.

Sure. A suggestion would be to introduce an API versioning (https://tracker.ceph.com/issues/40909), so we can easily detect front-end and back-end versions mismatches, and instead report a user-friendly actionable message (e.g.: "Please refresh your browser cache").

**Comment by sebastian-philipp** [comment]
> > Nevertheless, might make sense to improve the UX here.
> 
> Sure. A suggestion would be to introduce an API versioning (https://tracker.ceph.com/issues/40909), so we can easily detect front-end and back-end versions mismatches, and instead report a user-friendly actionable message (e.g.: "Please refresh your browser cache").

Yeah, the Dashboard is already tightly coupled to the backend. Might make sense to make sure, the frontend version exactly matches the backend version

**Comment by sebastian-philipp** [comment]
I expect the fix to end up in Nautilus 14.2.4

**Comment by travisn** [comment]
@sebastian-philipp Was it in today's release of 14.2.4? Or will it actually be in 14.2.5?

**Comment by christianhuening** [comment]
From the release notes 14.2.4 "only" includes this: https://tracker.ceph.com/issues/41660

**Comment by sebastian-philipp** [comment]
Hm, predicting the future always comes with a risk of being wrong.
