### ISSUE TITLE
Clarify CSI-based documentation for 1.1.x Ceph

### ISSUE THREAD

**Issue by eroji** [rook/rook#3875]
The current documentation for quickstart is more geared towards flex driver method of install for Ceph but the example YAML included has changed slightly, with added subdirectories. This created some confusion on which file is which, and which to use to stand up the cluster along with creating the storage class. It seems like some updates are needed for the documentation and explain which set of example YAMLs to use as the basis for a CSI driver install method.

**Comment by kadomino** [comment]
Another missing area is how to set a separate metadataDevice (or should I say metadataSet or metadataStorageClass?) for the OSDs when using the storageClassDeviceSets style of configuration.

**Comment by travisn** [comment]
@kadomino You're referring to [scenario 5](https://github.com/rook/rook/blob/master/design/storage-class-device-set.md#example-5-multiple-devices-per-osd) in the design doc? That isn't implemented yet. We will need to add this to a future release.

**Comment by kadomino** [comment]
> @kadomino You're referring to [scenario 5](https://github.com/rook/rook/blob/master/design/storage-class-device-set.md#example-5-multiple-devices-per-osd) in the design doc? That isn't implemented yet. We will need to add this to a future release.

Thanks travisn, this is exactly it. I think that it is worth mentioning in the doc - in an prominent spot - that this is not yet available. I spent some time trying to make it work, read the design scenario as well, but did not realize that it was not implemented. The reason I tried is because I have it working with the "device style" on Rook 0.9.3, so it's likely other people will try too...

**Comment by travisn** [comment]
I believe the original suggestion for this issue has been addressed. Since v1.1 in some patch release the docs were updated for CSI to be the main flow. 

In the v1.3 release we also have the additional scenario 5 implemented for OSDs on PVCs as requested above.
