### ISSUE TITLE
rook-ceph deployed ink8s，k8s cluster crashed because of insufficient memory，then allPVCs stay in pending state

### ISSUE THREAD

**Issue by yexia553** [rook/rook#3877]
**Is this a bug report or feature request?**
* No

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
 my cluster.yaml is original

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS ：k8s version is v1.13.4，one master and four-node
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.0.3
* Storage backend version (e.g. for ceph do `ceph -v`):    14.2.1
* Kubernetes version (use `kubectl version`):  v1.13.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  Tectonic
(https://rook.io/docs/rook/master/ceph-toolbox.html)):

* I am very sorry that I can't provide more information to you because the environment has been removed by me.

**Comment by leseb** [comment]
If you don't have enough memory to run k8s and it crashes, I don't see how this is a bug.
If you are running out of resource, the end result is expected.

I'm closing this as won't fix. Feel free to re-open if you have any more concerns.
