### ISSUE TITLE
Finding a better place for ceph-volume logs

### ISSUE THREAD

**Issue by sebastian-philipp** [rook/rook#3888]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Right now, ceph-volume logs are written to `/var/lib/rook/log/rook-ceph/ceph-volume.log` on the host machines. Having the logs stored there is cumbersome. 

Would it be possible to store the logs in a place accessible without SSH access?

We have the osd prepare pods. might make sense to add them there?

**Comment by travisn** [comment]
All the output from ceph-volume is written to the logs for the osd prepare pod and can be seen in the `provision` container logs. For example, you can access it like this: 
```
kubectl -n rook-ceph logs <osd-prepare-pod> provision
```
Is that sufficient, or are you seeing different logs written to disk on the host?

**Comment by sebastian-philipp** [comment]
perfect. Do we need the `/var/lib/rook/log/rook-ceph/ceph-volume.log` file then at all?

**Comment by leseb** [comment]
c-v generates this file. Also, the current location is more common than `kubectl -n rook-ceph logs <osd-prepare-pod> provision`. And I believe the output differs from the log (TBC), where the log file has more content/more verbose.

I'm not sure I fully understood the rationale behind that request.

**Comment by sebastian-philipp** [comment]
> I'm not sure I fully understood the rationale behind that request.

In general it's unusual for K8s PODs to write physical log files on the host system, as retrieving them is cumbersome as you need direct access to the machine.

**Comment by leseb** [comment]
We should decouple logs per daemon, that's easy to do. c-v already has an option for that?
