### ISSUE TITLE
mon  osd 

### ISSUE THREAD

**Issue by Liuxiayu** [rook/rook#3899]
Hello, where is the correspondence between mon and osd to be seen, for example, which osds does mon monitor

**Comment by sebastian-philipp** [comment]
https://docs.ceph.com/docs/master/start/intro/

**Comment by Liuxiayu** [comment]
> https://docs.ceph.com/docs/master/start/intro/
Hello, I mean in which configuration file you can see the osds that mon is monitoring？

**Comment by sebastian-philipp** [comment]
just run `ceph osd ls`

**Comment by Liuxiayu** [comment]
> just run `ceph osd ls`

Hi, how do you see what the disks are for each osd?  thanks

**Comment by travisn** [comment]
@Liuxiayu Could you join the [Rook slack](https://slack.rook.io/)? That is a better place for general questions. The github issues better for bugs and feature requests. Thanks!

**Comment by Liuxiayu** [comment]
> @Liuxiayu Could you join the [Rook slack](https://slack.rook.io/)? That is a better place for general questions. The github issues better for bugs and feature requests. Thanks!

okay，thanks！
