### ISSUE TITLE
Storage expansion and contraction  

### ISSUE THREAD

**Issue by Liuxiayu** [rook/rook#3905]
In the rook-ceph cluster, how to carry out dynamic expansion, how to increase osd, delete osd.Let's say I have three osds, how can I expand to four osds.

**Comment by leseb** [comment]
They are 2 differents options:

1. If you specified the devices "manually" in the CR, you need to edit the cluster CR and add a new device
2. If you have used `useAllDevices`, if a new device is plugged it'll be detected within the next hour IIRC

Also please read https://rook.io/docs/rook/v1.1/ceph-cluster-crd.html#settings.
