### ISSUE TITLE
Question: Mixed cluster

### ISSUE THREAD

**Issue by dkrizic** [rook/rook#3906]
Hi,

I have a generic question: I have a Kubernetes cluster. Some nodes (kube0 and kube1) provide storage. I would like to consume storage on the other nodes (kube2, kube3). What do I have to consider to make the storage (PVC via StorageClass) available? Should this work automatically or do I need the add the nodes kube2 and kube3 to a CephCluster?

**Comment by travisn** [comment]
@dkrizic To consume the storage from nodes kube2 and kube3 you don't have to add them to the CephCluster. The only thing that's needed is that the CSI (or flex) drivers are running on kube2 and kube3. By default the rook operator will start the driver(s) on all the nodes in the cluster.
