### ISSUE TITLE
Ceph Cluster migration

### ISSUE THREAD

**Issue by albertdb** [rook/rook#3911]
**Is this a bug report or feature request?**
* Feature Request (kind of, maybe there's a way already)

**What should the feature do:**

Allow migrating the Ceph Cluster from one Kubernetes Cluster to another.

**What is use case behind this feature:**

Rebuilding a Kubernetes Cluster while keeping PVs and PVCs.
Cold upgrades.

**Side notes**

I've already resolved (automated) OSD disks reuse across clusters, but as expected, `osd-prepare` do not spaws OSDs for disks from another cluster.

Would https://github.com/heptio/velero help in this task?

**Comment by albertdb** [comment]
Subcase of https://github.com/rook/rook/issues/1653

**Comment by pavgup** [comment]
I'm deep in the middle of exactly this strategy. Following this doc https://github.com/rook/rook/blob/master/Documentation/disaster-recovery.md you end up with a cluster that's maybe ready for consuming a previous ceph cluster, but when auth is finally removed and the mon is using the old fsid, the new cluster never attempts to attach previously functional OSDs.
