### ISSUE TITLE
Finalizer should check for csi volumes before allowing removal

### ISSUE THREAD

**Issue by travisn** [rook/rook#3913]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The operator adds a finalizer to the CephCluster so that when a cluster is deleted we can clean up the volumes before the cluster is stopped. Currently this check only happens for flex volumes in the [handleDelete()](https://github.com/rook/rook/blob/f7df86df16f75c25cf6195bcd8849beb399709e8/pkg/operator/ceph/cluster/controller.go#L757) method. 

**Expected behavior:**
The operator should check for volumes created by the csi driver and block the deletion if there are any active volumes.

**How to reproduce it (minimal and precise):**

- Create a ceph cluster
- Create a csi rbd or cephfs volume
- Delete the ceph cluster
- See the csi volumes hang

**Comment by ShyamsundarR** [comment]
**Requirement:** The operator should check for volumes created by the csi driver and block the deletion if there are any active volumes. (copied from issue description)

**Steps to check for active volumes:**
1. Determine if Ceph-CSI is managed/deployed by Rook
    - No: nothing to be done?
        - [Question] There can be a non-rook deployed CSI instance, that uses the current rook instance Ceph storage, should we do something about it?
    - Yes: Proceed
2. Determine CSI drivername for the deployed instance, call it `csiRookDriverName[]`
  
3. List all PVs that are created using the `csiRookDriverName` and if not empty return err/false from delete pre-flight finalizer check, else return success
    - [Question] Does rook have enough permissions/access on the kubernetes cluster to enumerate all PVs in the cluster?
    - `spec.csi.driver` of a PV contains the driver name
    - We maintain a singleton CSI instance, one for each CephFS and RBD, even when there are multiple clusters in play. This impacts the check for existing PVs as some could belong to a different cluster, rather than the one being deleted.
        - Ensure the `spec.csi.volumeAttributes.clusterID` matches the rook cluster namespace, as this is defaulted to the same
            - [Question] Is this allowed to be changed/edited by the admin?

**Other concerns:**
- External cluster
    - Procedure should not change even if Rook is managing/using an external Ceph cluster
- StorageClass is outside the scope of Rook
    - Should we check if StorageClass(es) present on the system use the rook deployed CSI drivername? and if so ensure there are no PVs from the said StorageClass?
- Race between checking PVs and finding none, to deletion of the rook-ceph cluster, between which a new PV can be created?
    - Should we fail earlier if there is a StorageClass with csiRookDriverName?
    - Should we enforce/check the same and error out stating there are StorageClasses using an instance of `csiRookDriverName`?

@travisn above is an attempt at providing a rough plan on how to get this done, and a few questions and cases that may need handling. Request a review of the same to see if this would work and what concerns need addressing.

Tagging other Ceph-CSI/Rook members: @Madhu-1 @humblec @phlogistonjohn

**Comment by travisn** [comment]
Overall I'd suggest the approach of looking at PVs to see if there are any for this instance of the local Ceph cluster. Hopefully the properties of the PVs can tell us sufficient info about the volumes for this cluster. 

> [Question] There can be a non-rook deployed CSI instance, that uses the current rook instance Ceph storage, should we do something about it?

Not sure what we can do about this case. This seems the same as the external cluster case. If the user is consuming this storage from another cluster, we won't be able to detect the PVCs from the other cluster. The only thing we could look at is the block images in the rbd pools, but we don't really know if they're still active, or if they just weren't reclaimed. This likely just needs to be left as a documentation solution.

> StorageClass is outside the scope of Rook
Should we check if StorageClass(es) present on the system use the rook deployed CSI drivername? and if so ensure there are no PVs from the said StorageClass?

I don't think we should look at storage classes. They only indicate the possibility of creating a PVC, but we only care if there are actually active PVCs bound to ceph PVs. 

> Race between checking PVs and finding none, to deletion of the rook-ceph cluster, between which a new PV can be created?
Should we fail earlier if there is a StorageClass with csiRookDriverName?
Should we enforce/check the same and error out stating there are StorageClasses using an instance of csiRookDriverName?

I wouldn't worry about this race. If they're creating a new PVC even while deleting the cluster, we can't prevent them from shooting themselves in the foot.

**Comment by ShyamsundarR** [comment]
> Overall I'd suggest the approach of looking at PVs to see if there are any for this instance of the local Ceph cluster. Hopefully the properties of the PVs can tell us sufficient info about the volumes for this cluster. Note that the operator has the sufficient RBAC to look at all PVs in the cluster.

One alternate mechanism to detect if there are allocated PVs, would be to inspect the CSI OMap journals for count of entries and detect any allocations. This would be much faster than iterating over the PVs themselves, as we would need to make just a single call to fetch the said OMap from the pool, and if empty pass back a success from the finalizer check.

The con of the above approach would be that, CSI internals/abstractions would be exposed to Rook, as it would be poking around the CSI journal on Ceph.

@travisn should we consider this from a performance/effectiveness perspective as the potential solution?

I further see `onDelete` methods for a filesystem and a pool, should these methods also ensure there are no PVs allocated before allowing the delete? (I do not see FlexVol related checks in these function, but checking if we need these for completion).
File: https://github.com/rook/rook/blob/ba2b8724ce34a6566d65917e51b910719b02a6d1/pkg/operator/ceph/file/controller.go#L184-L198
Pool: https://github.com/rook/rook/blob/ba2b8724ce34a6566d65917e51b910719b02a6d1/pkg/operator/ceph/pool/controller.go#L140-L150

@travisn requesting your feedback on the above as well.

**Comment by Madhu-1** [comment]
@ShyamsundarR @travisn can we check if images are present in the pool before deleting the pool instead of check PVC for deleting Pools? I believe this does not consume more time compare to  PV check

**Comment by Madhu-1** [comment]
@travisn and @ShyamsundarR I think we can use
```rbd pool stats  <pool-name>``` to check  if  there are any images or snapshot present on  the Pool, here  is  the PR for the same https://github.com/rook/rook/pull/3972

do we have some command to check if `filesystem` is in use? if yes we  can use it to avoid deletion of the filesystem

instead of checking the PV objects  created by the driver, can we check  if there are any pools or filesystem available in the cluster  if yes can stop the cluster deletion ( @travisn is this possible with current code structure)

question:
do we need  to allow the user to delete the  cluster if there are any pools or filesystem present in the cluster
