### ISSUE TITLE
CSI driver needs a configurable directory in place of /var/lib/kubelet

### ISSUE THREAD

**Issue by golpa** [rook/rook#3921]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@golpa Are you referring to the csi or flex driver? Can you provide more details for the scenario where it is not working with the defaults?

**Comment by golpa** [comment]
@travisn this is weird. Is my view messed up or is my original bug report missing all the details I typed in? For me, I'm now only seeing the original template without it filled out at all.

**Comment by golpa** [comment]
@travisn This is what I thought I originally submitted. Hopefully it answers your question.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
rook-ceph assumes kubernetes is running from `/var/lib/kubelet`. In our installation we run kubernetes outside of `/var/lib/kubelet`. As a result certain pods created by rook fail to start up because they attempt to mount directories under `/var/lib/kubelet`. 

We are working around this problem currently by symlinking `/var/lib/kubelet` to the actual location of our kubelet root directory.

**Expected behavior:**
We expected there to either be a configuration setting to specify where the kubelet path is or ideally, if possible, have rook auto detect the correct path.

**How to reproduce it (minimal and precise):**
Run kubelet with `--root-dir=/some/other/path` and submit a default run of rook-ceph

**File(s) to submit**:
We are using the default `common.yaml` and `operator.yaml` as provided [here](https://github.com/rook/rook/tree/release-1.1/cluster/examples/kubernetes/ceph). We are using the `cluster.yaml` as provided there with the only modification of setting `useAllDevices: false` and `deviceFilter: sdb2`.

The `csi-cephfsplugin` pods that are submitted fail to start with this in the kubectl logs:
```
$ kubectl describe pod -n rook-ceph csi-cephfsplugin-bg875 
...
Events:
  Type     Reason       Age               From                      Message
  ----     ------       ----              ----                      -------
  Normal   Scheduled    14s               default-scheduler         Successfully assigned rook-ceph/csi-cephfsplugin-bg875 to <node>
  Warning  FailedMount  14s               kubelet, <node>  MountVolume.SetUp failed for volume "csi-plugins-dir" : hostPath type check failed: /var/lib/kubelet/plugins is not a directory
  Warning  FailedMount  7s (x5 over 14s)  kubelet, <node>  MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory
  Warning  FailedMount  7s (x5 over 14s)  kubelet, <node>  MountVolume.SetUp failed for volume "pods-mount-dir" : hostPath type check failed: /var/lib/kubelet/pods is not a directory
```

**Environment**:
* OS (e.g. from /etc/os-release): `Debian 9`
* Kernel (e.g. `uname -a`): `Linux <node> 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `Baremetal Kubernetes Installation`
* Rook version (use `rook version` inside of a Rook Pod): `v1.1.0`
* Storage backend version (e.g. for ceph do `ceph -v`): `v14.2.4-20190917`
* Kubernetes version (use `kubectl version`): `1.15.3`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `Baremetal installation`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `N/A`

**Comment by bobelev** [comment]
I get same bad behaviour with installation outside `/var/lib/kubelet`

**Comment by travisn** [comment]
@golpa Thanks for all the details, that definitely explains the issue at hand. This does appear scoped to the csi driver. Sounds like we need the following:
- Env var in the operator.yaml such as `KUBELET_DIR_PATH`. The default would be `/var/lib/kubelet`
- When the CSI driver templates are evaluated, this variable should be used to replace the kubelet path
@Madhu-1 could you take a look?

**Comment by Madhu-1** [comment]
@travisn here is the PR https://github.com/rook/rook/pull/3927
