### ISSUE TITLE
rook-config-override is ignored in Rook v1.1.0

### ISSUE THREAD

**Issue by junhuihuang** [rook/rook#3926]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
* osd container did not binding cluster network
* Changing to Rook v1.0.4, osd is working well

**Expected behavior:**
* osd container should be binding cluster network

**How to reproduce it (minimal and precise):**

ConfigMap `rook-config-override` content

 
    config: |
       [global]
       public network = 10.99.252.0/24
       cluster network = 192.168.10.0/24
       public addr = ""
       cluster addr = ""

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by peterska** [comment]
I have experienced the same issue after upgrading to rook 1.1.1, I had 2 networks, 192.168.3.0/24 for the public  network and 192.168.4.0/24 for the cluster network. After the upgrade all traffic goes through the 192.168.3.0/24 network  my rook-config-override is identical to the one show above

**Comment by leseb** [comment]
If you exec into your osd pod, what do you see in your ceph.conf? Don't you see the settings? I just tried and I see them. In order to pick them up, you might need to restart the OSD process but if this was part of an upgrade this shouldn't be necessary.

**Comment by junhuihuang** [comment]
@leseb Thanks your reply.

After kubectl exec into my osd pod, I execute following command.

```shell
$ cat /etc/ceph/ceph.conf
[global]
public network = 10.99.252.0/24
cluster network = 192.168.10.0/24
public addr = ""
cluster addr = ""
```

But the osd is using another configure file, `/var/lib/rook/osd34/rook-ceph.config`

```shell
$ ps aux | grep ceph | grep "\-\-id 34"
root     22387  0.0  0.0   4364   632 ?        Ss   Sep24   0:02 /rook/tini -- /rook/rook ceph osd start -- --foreground --id 34 --osd-uuid a9f8fbc8-2784-40e0-a934-78611afd47de --conf /var/lib/rook/osd34/rook-ceph.config --cluster ceph --setuser ceph --setgroup ceph --setuser-match-path /var/lib/rook/osd34 --default-log-to-file false
root     22407  0.0  0.0 153148 38160 ?        Sl   Sep24   0:33 /rook/rook ceph osd start -- --foreground --id 34 --osd-uuid a9f8fbc8-2784-40e0-a934-78611afd47de --conf /var/lib/rook/osd34/rook-ceph.config --cluster ceph --setuser ceph --setgroup ceph --setuser-match-path /var/lib/rook/osd34 --default-log-to-file false
ceph     22553  4.9  1.6 5869884 4272752 ?     Sl   Sep24 140:52 ceph-osd --foreground --id 34 --osd-uuid a9f8fbc8-2784-40e0-a934-78611afd47de --conf /var/lib/rook/osd34/rook-ceph.config --cluster ceph --setuser ceph --setgroup ceph --setuser-match-path /var/lib/rook/osd34 --default-log-to-file false
```

**Comment by leseb** [comment]
Ahhh yes, good point, then something is wrong. Let me look into this.
