### ISSUE TITLE
allow rook pods to use different version than rook-operator

### ISSUE THREAD

**Issue by jbw976** [rook/rook#393]
The rook-operator and rook pods should be allowed to run with different versions.  Currently the operator expects the rookd container version to be the same as its own.

From @travisn:
> there is currently an expectation to have the same version for the operator and client. i need to add a new command line arg so they can be different

**Comment by travisn** [comment]
this is obsolete since the operator was merged to rookd

**Comment by bassam** [comment]
I assume we still want the operator to manage pods running different versions however, right?

**Comment by travisn** [comment]
agreed, that will be a different issue around upgrades rather than being tracked with this issue
