### ISSUE TITLE
rook ceph pv error

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#3930]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

```
Events:
  Type     Reason            Age                  From                       Message
  ----     ------            ----                 ----                       -------
  Warning  FailedScheduling  2m30s                default-scheduler          pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled         2m28s                default-scheduler          Successfully assigned dev/my-redis-redis-ha-server-0 to dev3.localdomain
  Warning  FailedMount       25s                  kubelet, dev3.localdomain  Unable to mount volumes for pod "my-redis-redis-ha-server-0_dev(53f2c61d-6e16-487d-8087-6dd56fbba894)": timeout expired waiting for volumes to attach or mount for pod "dev"/"my-redis-redis-ha-server-0". list of unmounted volumes=[data]. list of unattached volumes=[data config my-redis-redis-ha-token-p9hnc istio-envoy istio-certs]
  Warning  FailedMount       19s (x9 over 2m27s)  kubelet, dev3.localdomain  MountVolume.SetUp failed for volume "pvc-491a478e-a977-4109-8a53-f1c333b7b191" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume replicapool/pvc-491a478e-a977-4109-8a53-f1c333b7b191: failed to map image replicapool/pvc-491a478e-a977-4109-8a53-f1c333b7b191 cluster rook. failed to map image replicapool/pvc-491a478e-a977-4109-8a53-f1c333b7b191: Failed to complete 'rbd': exit status 2. . output: modinfo: ERROR: could not get modinfo from 'rbd': Exec format error
modprobe: ERROR: could not insert 'rbd': Exec format error
rbd: failed to load rbd kernel module (1)
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (2) No such file or directory
```

**Comment by leseb** [comment]
Is the `rbd` kernel module available on your host machine?

**Comment by 13567436138** [comment]
the rbd is runing in the container ,does it has relate with my host machine

**Comment by leseb** [comment]
It doesn't matter, if the kernel does not have the module, nothing will work.

**Comment by 13567436138** [comment]
how to solve my problem

**Comment by leseb** [comment]
https://rook.io/docs/rook/v1.1/k8s-pre-reqs.html
https://rook.io/docs/rook/v1.1/ceph-common-issues.html#rook-agent-modprobe-exec-format-error

**Comment by 13567436138** [comment]
the probem is my rook is ok,sometime ago.so the rbd module is presence.

**Comment by 13567436138** [comment]
please reopen this isusse,I still have problem

**Comment by 13567436138** [comment]
[root@dev3 ~]# lsmod |grep rbd
rbd                    83728  2 
libceph               301687  1 rbd

**Comment by leseb** [comment]
did you try what I linked in the doc?

**Comment by 13567436138** [comment]
the doc tell me to recompile the kernel.but I think my kernel is ok.It works well a couple hours ago.I can mount the ceph volumns,but now I cannt ,I dont know why

**Comment by 13567436138** [comment]
my system is ok now,thanks
