### ISSUE TITLE
Consider calling nsenter when configuring LVM

### ISSUE THREAD

**Issue by travisn** [rook/rook#3935]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:** 
We should consider nsenter when configuring LVM for OSDs on PVs. Then we can revisit the changes in #3755 and hopefully remove the workaround to kill the osd process during shutdown. 

Per @nixpanic's [comment](https://github.com/rook/rook/pull/3755#issuecomment-533460036):
Running LVM commands in a container is troublesome. It is better to run
the commands on the host directly. One way to do so, is with `nsenter`
(similar to `chroot` but with support for namespaces).

This will prevent issues where LVM and udev try to synchronize. LVM uses
both a locking file under `/run/lvm` and IPC/semaphores. udev events
will get handled on the host, and the LVM processes in the container may
not get the expected signals to proceed (correctly).

One other potetial issue, is that the LVM version on the host is (too)
different from the LVM version in the container. The versions may not
work well together; mixed versions of LVM is certainly not tested by LVM
developers (at least the ones we have at Red Hat).

Adding support for `nsenter` in `ceph-volume` could be an improvement in
the right direction, plus adding `nsenter` for all LVM related commands
in Rook.

**What is use case behind this feature:**
Properly configured LVM.

**Comment by rajha-korithrien** [comment]
Be aware that using ```nsenter``` fails on hosts that do not have the ```findmnt``` and ```stat``` binaries installed. Very light weight OS sometimes do not ship these. I have an issue where disabling nsenter is the only way to get Rook to upgrade from 1.0.6 to 1.1.0. See #3923 for more details.

**Comment by sp98** [comment]
Some comments to keep in mind while working on this PR: 
https://github.com/rook/rook/pull/3755#discussion_r326984589
https://github.com/rook/rook/pull/3755#discussion_r326984589

**Comment by phlogistonjohn** [comment]
This is probably still quite relevant, even if this issue is a bit stale. I hope no one minds me reopening this to get visibility about the general issue again.

**Comment by travisn** [comment]
@leseb Has done some work recently so we can run OSDs without LVM in most scenarios. At least the scenarios without LVM would not need a change here, but makes sense to continue tracking it until LVM is complete purged from Rook.

**Comment by phlogistonjohn** [comment]
Cool. The gluster+heketi stack got away with not dealing with the issue for a very long time but when it bit it bites hard. Either removing the need for lvm or using the host lvm should prevent these issues.

**Comment by leseb** [comment]
I'd like to go ahead and close since this was targeting the "on PVC" use-case which now is not using LVM anymore. Feel free to re-open if you have any more concerns.
