### ISSUE TITLE
run Cluster.yaml error

### ISSUE THREAD

**Issue by fedeostrit** [rook/rook#3940]
hello

I have installed kubernetes with RKE rancher and I am installing Rook v1.1.1 from helm chart but when I try to build the cluster by running "kubectl create -f cluster.yaml" I have the following error:

error: unable to recognize "cluster.yaml": no matches for kind "CephCluster" in version "ceph.rook.io/v1"

my cluster.yaml is attached
[cluster.txt](https://github.com/rook/rook/files/3638863/cluster.txt)

**Comment by leseb** [comment]
Please re-open a bug with the bug template fulfilled. Thanks.

**Comment by zsping1989** [comment]
我这好像也是同样的问题
 kubectl apply -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/cluster.yaml
error: unable to recognize "https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/cluster.yaml": no matches for kind "CephCluster" in version "ceph.rook.io/v1"

**Comment by Madhu-1** [comment]
Apply CRD first https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/crds.yaml , CRD is moved to a different file now

**Comment by zsping1989** [comment]
thank you

**Comment by huangyingxian** [comment]
> Apply CRD first https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/crds.yaml , CRD is moved to a different file now

thanks

**Comment by Bingmang** [comment]
从《深入剖析 Kubernetes》过来的可以 +1 ……

**Comment by ShuBo6** [comment]
> Apply CRD first https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/crds.yaml , CRD is moved to a different file now

thank U

**Comment by sunmiao0301** [comment]
for rook v1.2, the link is:[https://raw.githubusercontent.com/rook/rook/master/deploy/examples/crds.yaml](https://raw.githubusercontent.com/rook/rook/master/deploy/examples/crds.yaml)

**Comment by zsping1989** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mtn199300** [comment]
> 从《深入剖析 Kubernetes》过来的可以 +1 ……

+1  书本里的安装方式一直失败 参考这里的方式解决了

**Comment by zsping1989** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
