### ISSUE TITLE
unable to get monitor info from DNS SRV with service name: ceph-mon

### ISSUE THREAD

**Issue by yizhishang** [rook/rook#3965]
* Bug Report
unable to get monitor info from DNS SRV with service name: ceph-mon

**Deviation from expected behavior:**

can point the detail mon-point rook-ceph-mon-a/b/c/d

**Expected behavior:**

**How to reproduce it (minimal and precise):**
kubectl create -f common.yaml
kubectl create -f operator.yaml
kubectl create -f cluster-test.yaml

then run "ceph -s " in the "rook-ceph-mgr-a" pod, get the errors
![image](https://user-images.githubusercontent.com/12756407/65484598-0337d580-ded2-11e9-8c80-6decbac370e4.png)

**Environment**:
* OS: centos-7.4
* Kernel (e.g. uname -a): 3.10.0-957.el7.x86_64
* Rook version (use rook version inside of a Rook Pod): v1.1.1
* Storage backend version (e.g. for ceph do ceph -v): ceph version 12.2.12-48.el7cp 
* Kubernetes version (use kubectl version): v1.14.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): single node
* Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox): HEALTH_OK

**Comment by galexrt** [comment]
You shouldn't use the cluster components Pods to access Ceph, use the Rook Ceph toolbox instead: https://rook.io/docs/rook/v1.1/ceph-toolbox.html

**Comment by vvkkhjt** [comment]
@galexrt if i want use other rook to connect ceph cluster with rook,what should i do?

**Comment by Voolodimer** [comment]
I have the same problem, after logining in `rook-ceph-mon-c` container i try to get `monmap_config` using `ceph mon getmap` and i get similar error:
```
unable to get monitor info from DNS SRV with service name: ceph-mon
2022-11-11T08:08:33.060+0000 7fd224cd9700 -1 failed for service _ceph-mon._tcp
2022-11-11T08:08:33.060+0000 7fd224cd9700 -1 monclient: get_monmap_and_config cannot identify monitors to contact
```
I want to change ip-addresses on monitors.
Can anyone help me ?

**Comment by travisn** [comment]
@Voolodimer Mon IPs cannot be changed. If you need new IPs, you can [failover the mons](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor) to get new IPs. I'd suggest opening a new [Discussion](https://github.com/rook/rook/discussions) or joining the rook slack for further questions.
