### ISSUE TITLE
create admin socket for all ceph containers

### ISSUE THREAD

**Issue by mmgaggle** [rook/rook#3966]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

For every Ceph container we should configure an admin socket

**What is use case behind this feature:**

This would be useful for both troubleshooting, and so that we could injectargs in emergency situations.

Example of troubleshooting might be inspecting the admin socket of the monitors to see why they are unable to form quorum. Another might be inspecting the runtime memory_target setting on any given OSD.

The use of injectargs is very handy for large clusters when you need to quickly make a change to a daemons runtime without churning through deleting pods. Think dynamically changing recovery settings (max backfills).

**Comment by leseb** [comment]
As far as I can tell only OSDs don't have the socket at this point, do you experience the same?

**Comment by mmgaggle** [comment]
I noticed it with OSDs, as I was trying to inspect the memory_target, so "all ceph containers" may be a bit presumptuous :)

Happy to change it to "OSDs"

**Comment by leseb** [comment]
No worries, thanks for the confirmation :)/

**Comment by leseb** [comment]
Ok, so the socket is actually present, it's just a bit tricky, you can find it: `/var/lib/rook/osd$ID/ceph-osd.$ID.asok`. I'll fix that.
