### ISSUE TITLE
Updating from 1.0.6 to 1.1.1 (bunch of updates before, from early rook versions) - clusterrole not updated

### ISSUE THREAD

**Issue by dimm0** [rook/rook#3975]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After updating, operator was printing bunch of

```
E0924 19:41:34.576997       6 leaderelection.go:306] error retrieving resource lock rook-system/rook.io-block: endpoints "rook.io-block" is forbidden: User "system:serviceaccount:rook-system:rook-ceph-system" cannot get resource "endpoints" in API group "" in the namespace "rook-system": RBAC: clusterrole.rbac.authorization.k8s.io "rook-ceph-global" not found
E0924 19:41:34.713167       6 leaderelection.go:306] error retrieving resource lock rook-system/ceph.rook.io-block: endpoints "ceph.rook.io-block" is forbidden: User "system:serviceaccount:rook-system:rook-ceph-system" cannot get resource "endpoints" in API group "" in the namespace "rook-system": RBAC: clusterrole.rbac.authorization.k8s.io "rook-ceph-global" not found
```

I found that rook-ceph-global ClusterRole was old. Replaced with one from common, now operator is happy

I also have a set of other roles in kube-system, not sure which are still needed

**Expected behavior:**
All roles are updated properly

**How to reproduce it (minimal and precise):**
Go the full chain of updates from first rook versions

**Comment by travisn** [comment]
This was likely caused by an incompatibility with the aggregated rules for RBAC. We likely should revert the changes from #2975 since we fully control the RBAC rules. Aggregated rules are not about simplifying the upgrade (as was the hope).

**Comment by stephan2012** [comment]
While investigating volume attachment timeouts I found this in csi-attacher container of csi-cephfsplugin-provisioner:

```
E0205 09:08:19.974060       1 leaderelection.go:341] Failed to update lock: configmaps "external-attacher-leader-rook-ceph-cephfs-csi-ceph-com" is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-cephfs-provisioner-sa" cannot update resource "configmaps" in API group "" in the namespace "rook-ceph"
I0205 09:08:19.974082       1 leaderelection.go:222] failed to acquire lease rook-ceph/external-attacher-leader-rook-ceph-cephfs-csi-ceph-com
```

Is this the same issue?

**Comment by stephan2012** [comment]
In case there is no technical fix, maybe a pointer in the docs is sufficient?

**Comment by mauritsvdvijgh** [comment]
Certainly would have saved me some time, seems like a good way of at least addressing the issue with minimal effort, even just a pointer to this issue will probably help.

**Comment by dimm0** [comment]
Closing, hopefully everyone is past this version already :)
