### ISSUE TITLE
Support bluestore on top of a file

### ISSUE THREAD

**Issue by travisn** [rook/rook#398]
In the kubernetes deployment we only support bluestore devices. There may be scenarios where admins want to use directories on previously provisioned storage, in which case we could use filestore.

**Comment by bassam** [comment]
or use bluestore ontop of a file -- this is supported too.

**Comment by travisn** [comment]
@bassam, good point. i updated the title to remove the filestore suggestion

**Comment by hunter** [comment]
Does this mean that filestore won't be supported for this scenario? Bluestore is still new with quite a few rough edges and we'd still prefer to be using filestore for the near future (even post Luminous) for devices and directories. Could also mean we can independently look at ways of migrating from pure Ceph (since #278 isn't on the roadmap).

We're quite happy to provision filestores manually to avoid adding more code bloat but just adding our 2c that we'd still like filestore.

**Comment by bassam** [comment]
@hunter we're open to leaving the filestore. Not sure if you caught the subtlety but bluestore does run ontop of directories too.

Is you primary concern reliability of bluestore, or migration from existing deployments?

**Comment by hunter** [comment]
Yes, our primary concern is really with the reliability of BlueStore. Having spent a fair amount of time getting Ceph working on Kubernetes, we really like the integration and simplicity of Rook and would like to adopt the platform as it becomes more stable. What would prevent us using it early though would be the storage layer, we're happy to take a risk with the management layer but not the data stored on disk.

Migration would be a nice to have but not critical.

**Comment by bassam** [comment]
@hunter that's fair. We're currently on kraken and considering starting our stabilization journey on luminous as this is likely the ceph release we would GA with.

One issue we're discussing is whether to merge luminous into master and focus on getting to stability along with the ceph team. 

Alternatively we could maintain a rook-luminous branch and leave master on kraken. Maintaining long lived branches is a pain however.

We're leaning towards the early merge of luminous to master. The ceph team is targeting this spring for the LTS release of luminous.

Any thoughts? I completely hear you about a stable data layer being critical.

**Comment by hunter** [comment]
It sounds like there is a reasonable amount of [demand](https://news.ycombinator.com/item?id=13678979) for solid storage platform for Kubernetes. I would imagine getting Rook to market earlier would provide some first mover advantage? Is there anything that is required in Luminous?

**Comment by bassam** [comment]
Agree on the demand for storage and time to market. Luminous is the first LTS release with embedded ceph. We could stabilize on kraken but that's not an LTS release, and I think we would need to make filestore the default for kraken.

**Comment by hunter** [comment]
Over our time with Ceph, we've never really tracked the LTS releases since there were certain features we required in the non-LTS stable releases, I can't speak for others though.

**Comment by bassam** [comment]
related to #433 

@hunter thanks for the good feedback here. We're going to support both Kraken (default) and Luminous (a build option) in master (see #371). Also filestore (default) and bluestore (runtime option) see #433.

**Comment by hunter** [comment]
Great news! I'm looking forward to trying some deployments with filestore :)

**Comment by jbw976** [comment]
A lot of the work to support OSDs using directories was done in https://github.com/rook/rook/commit/c2d6f34fa81caa177762ea93f7b2ac77a225a09e.  I think the only part left really is to allow bluestore on top of a file as @bassam mentioned in https://github.com/rook/rook/issues/398#issuecomment-279772126.  Updating the title to reflect that.
