### ISSUE TITLE
Automate restoring of mon quorum for disaster recovery

### ISSUE THREAD

**Issue by travisn** [rook/rook#3985]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
If mon quorum is lost and at least one quorum is still running, mon quorum can be restored manually by following [these instructions](https://rook.io/docs/rook/v1.5/ceph-disaster-recovery.html#restoring-mon-quorum). This is a very tedious process. We need to automate this and add it to the integration tests so that it is a core supported feature to restore quorum in these disaster scenarios. 

The restoring of quorum would be triggered as a very explicit action by the admin. For example, connect to the toolbox pod, then run a new command such as:
```
rook operator ceph restore-quorum rook-ceph-mon-a
```

This command would then modify all the configmaps, mon deployments, etc. to automate the recovery.

**What is use case behind this feature:**
Simplification and automation of disaster recovery.

**Comment by travisn** [comment]
To clarify the design, we can implement this disaster recovery feature in the operator with a new command similar to the [osd purge job](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/osd-purge.yaml).
- Implement a new command in the operator that is triggered by a one-time K8s job
- As part of the operator, the new command will be able to run both K8s and Ceph commands to perform the various operations to reset the mon quorum to a single mon and then scale it back up to 3.
- Testing can follow all the patterns we already have for unit tests and integration tests.

**Comment by BlaineEXE** [comment]
Would it be better to do this via a command in the operator, or make a script that is set up similarly to the toolbox pod?

**Comment by travisn** [comment]
> Would it be better to do this via a command in the operator, or make a script that is set up similarly to the toolbox pod?

This is a one-time action to execute, so it makes sense as a job instead of trying to make it part of the operator. Trying to use desired state with a CR just doesn't fit a one-time action. As soon as the action is completed, the desired state of restoring quorum will be obsolete. 

Something to consider though is that the operator should not be running at the same time as this job. You'd want to stop the operator before running the job so they don't conflict. See the osd purge job referenced above that will run a command to remove an osd. We would want to implement a new command with that same pattern, that would restore the mon quorum.

**Comment by BlaineEXE** [comment]
Okay. Those were my thoughts as well that making it part of the operator seems kind of heavy.

**Comment by travisn** [comment]
This will be solved by a new command in the krew plugin. See https://github.com/rook/kubectl-rook-ceph/pull/61
