### ISSUE TITLE
OSD daemonset should be able to run unprivileged

### ISSUE THREAD

**Issue by travisn** [rook/rook#400]
The OSD containers should be able to run unprivileged in the following scenarios:
- The admin has already provisioned the storage devices on a node (for bluestore)
- Directories will be used for filestore

The default seems like it should be to run unprivileged. If the admin wants Rook to do the provisioning of the devices he could override it with a flag and run privileged.

**Comment by bassam** [comment]
related to #82

**Comment by bzub** [comment]
The privileged portion of the pods could be carried out by an [Init Container](https://kubernetes.io/docs/concepts/abstractions/init-containers/).

It seems like separating storage initialization/verification from OSD startup could be a smart thing to do.  At least in the case of Init Containers the OSD container wouldn't start without the initial formatting/verification returning success.
