### ISSUE TITLE
Operator is deleting the OSDs which are out and safe-to-delete, even if in CRD

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4000]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Operator can decide to remove an OSD which is defined in CRD, if it's out and safe-to-delete

**Expected behavior:**
All OSDs defined in CRD should stay in the cluster and not be removed until admin decides so

**Comment by travisn** [comment]
This is a result of the change from #2741. There is some discussion there about the intention. But from this report it is obvious that we can't automatically remove the OSDs in this case either. If the cluster is experiencing health issues (in this case from #3992), it isn't expected to remove any OSDs. The OSDs should not be deleted if there is some temporary cluster health issue. The admin should be able to express his intention that it's ok to remove the OSD(s). While I hesitate to add another property to the Cluster CR, it does appear to be another desired state setting such as `removeOSDsIfDownAndSafeToRemove`. The default could be false.

**Comment by travisn** [comment]
After giving it a bit more thought, this is my current view on the needed approach: 
- OSDs can be removed automatically with the current mechanism if a new setting `removeOSDsIfDownAndSafeToRemove` is set to `true`. The default for all new or upgraded clusters should be `false`.
- OSDs should not be automatically be removed by default. OSDs can get into error states (initial configuration fails, upgrade instability, etc) and it might appear that it's safe to remove them, but the operator doesn't know if that is the intention.
- The admin should be able to execute a command from the toolbox if he wants to remove the safe-to-destroy OSDs. This is a potential feature for the rook mgr module. For example, he could run something like:
```
ceph orchestrator remove-safe-to-destroy-osds
```

The first bullet is the recommended fix for this issue, with the last bullet being a separate feature suggestion.
@rohan47 @leseb @BlaineEXE @sebastian-philipp thoughts?

**Comment by leseb** [comment]
> After giving it a bit more thought, this is my current view on the needed approach:
> 
> * OSDs can be removed automatically with the current mechanism if a new setting `removeOSDsIfDownAndSafeToRemove` is set to `true`. The default for all new or upgraded clusters should be `false`.

Sounds acceptable to me as an initial step to fix that issue quickly.
The only thing that I'm not sure is that this might not be an all or nothing scenario.
There could be a desire to only remove particular OSDs that are "down and safe to remove" but not all of them.

> * OSDs should not be automatically be removed by default. OSDs can get into error states (initial configuration fails, upgrade instability, etc) and it might appear that it's safe to remove them, but the operator doesn't know if that is the intention.

Agreed.

> * The admin should be able to execute a command from the toolbox if he wants to remove the safe-to-destroy OSDs. This is a potential feature for the rook mgr module. For example, he could run something like:
> 
> ```
> ceph orchestrator remove-safe-to-destroy-osds
> ```

Same thing, probably not all of them.

> 
> The first bullet is the recommended fix for this issue, with the last bullet being a separate feature suggestion.
> @rohan47 @leseb @BlaineEXE @sebastian-philipp thoughts?

**Comment by sebastian-philipp** [comment]
> > After giving it a bit more thought, this is my current view on the needed approach:
> > 
> > * OSDs can be removed automatically with the current mechanism if a new setting `removeOSDsIfDownAndSafeToRemove` is set to `true`. The default for all new or upgraded clusters should be `false`.

If `false`, Rook simply won't remove OSDs? 

> 
> Sounds acceptable to me as an initial step to fix that issue quickly.
> The only thing that I'm not sure is that this might not be an all or nothing scenario.
> There could be a desire to only remove particular OSDs that are "down and safe to remove" but not all of them.
> 
> > * OSDs should not be automatically be removed by default. OSDs can get into error states (initial configuration fails, upgrade instability, etc) and it might appear that it's safe to remove them, but the operator doesn't know if that is the intention.
> 
> Agreed.
> 
> > * The admin should be able to execute a command from the toolbox if he wants to remove the safe-to-destroy OSDs. This is a potential feature for the rook mgr module. For example, he could run something like:
> > 
> > ```
> > ceph orchestrator remove-safe-to-destroy-osds
> > ```
> 
> Same thing, probably not all of them.

I don't see how this works. If I want to remove an osd: `ceph orchestrator osd remove osd.0`, I need to enable `removeOSDsIfDownAndSafeToRemove` setting, otherwise I won't be able to remove that particular OSD, right? But now this has the side effect of removing **all** other osds in that state as well. This looks more like a per-osd setting to me? Seconding @leseb here.

> 
> > The first bullet is the recommended fix for this issue, with the last bullet being a separate feature suggestion.
> > @rohan47 @leseb @BlaineEXE @sebastian-philipp thoughts?

**Comment by rohan47** [comment]
> > > After giving it a bit more thought, this is my current view on the needed approach:
> > > 
> > > * OSDs can be removed automatically with the current mechanism if a new setting `removeOSDsIfDownAndSafeToRemove` is set to `true`. The default for all new or upgraded clusters should be `false`.
> 
> If `false`, Rook simply won't remove OSDs?
> 
> > Sounds acceptable to me as an initial step to fix that issue quickly.
> > The only thing that I'm not sure is that this might not be an all or nothing scenario.
> > There could be a desire to only remove particular OSDs that are "down and safe to remove" but not all of them.
> > > * OSDs should not be automatically be removed by default. OSDs can get into error states (initial configuration fails, upgrade instability, etc) and it might appear that it's safe to remove them, but the operator doesn't know if that is the intention.
> > 
> > 
> > Agreed.
> > > * The admin should be able to execute a command from the toolbox if he wants to remove the safe-to-destroy OSDs. This is a potential feature for the rook mgr module. For example, he could run something like:
> > > 
> > > ```
> > > ceph orchestrator remove-safe-to-destroy-osds
> > > ```
> > 
> > 
> > Same thing, probably not all of them.
> 
> I don't see how this works. If I want to remove an osd: `ceph orchestrator osd remove osd.0`, I need to enable `removeOSDsIfDownAndSafeToRemove` setting, otherwise I won't be able to remove that particular OSD, right? But now this has the side effect of removing **all** other osds in that state as well. This looks more like a per-osd setting to me? Seconding @leseb here.
> 
What about removing the deployment manually when `removeOSDsIfDownAndSafeToRemove` is false? 
> > > The first bullet is the recommended fix for this issue, with the last bullet being a separate feature suggestion.
> > > @rohan47 @leseb @BlaineEXE @sebastian-philipp thoughts?

**Comment by rohan47** [comment]
And it should be `removeOSDsIfOutAndSafeToRemove` right?

**Comment by sebastian-philipp** [comment]
> > > > ```
> > > > ceph orchestrator remove-safe-to-destroy-osds
> > > > ```
> > > 
> > > 
> > > Same thing, probably not all of them.
> > 
> > 
> > I don't see how this works. If I want to remove an osd: `ceph orchestrator osd remove osd.0`, I need to enable `removeOSDsIfDownAndSafeToRemove` setting, otherwise I won't be able to remove that particular OSD, right? But now this has the side effect of removing **all** other osds in that state as well. This looks more like a per-osd setting to me? Seconding @leseb here.
> 
> What about removing the deployment manually when `removeOSDsIfDownAndSafeToRemove` is false?

You mean, by omitting the osd in the CRD, OSDs are getting deleted, if  removeOSDsIfDownAndSafeToRemove = true and osd is out and safe-to-remove? IMO we should never delete OSDs by omitting them in the CRD. Or do you have something else in mind?


> > > > @rohan47 @leseb @BlaineEXE @sebastian-philipp thoughts?

**Comment by rohan47** [comment]
> > > > > ```
> > > > > ceph orchestrator remove-safe-to-destroy-osds
> > > > > ```
> > > > 
> > > > 
> > > > Same thing, probably not all of them.
> > > 
> > > 
> > > I don't see how this works. If I want to remove an osd: `ceph orchestrator osd remove osd.0`, I need to enable `removeOSDsIfDownAndSafeToRemove` setting, otherwise I won't be able to remove that particular OSD, right? But now this has the side effect of removing **all** other osds in that state as well. This looks more like a per-osd setting to me? Seconding @leseb here.
> > 
> > 
> > What about removing the deployment manually when `removeOSDsIfDownAndSafeToRemove` is false?
> 
> You mean, by omitting the osd in the CRD, OSDs are getting deleted, if removeOSDsIfDownAndSafeToRemove = true and osd is out and safe-to-remove? IMO we should never delete OSDs by omitting them in the CRD. Or do you have something else in mind?
>
I meant `kubectl delete deployment <name of the OSD deployment>`  when `removeOSDsIfDownAndSafeToRemove = false`

When OSD is marked out and is safe to destroy, we use `k8sutil.DeleteDeployment()` function to delete the OSD deployment and we don't delete the osd from the crush map when `removeOSDsIfDownAndSafeToRemove = true`. So its like making the process manual in case of `false`
> > > > > @rohan47 @leseb @BlaineEXE @sebastian-philipp thoughts?

**Comment by rohan47** [comment]
> > > > What about removing the deployment manually when `removeOSDsIfDownAndSafeToRemove` is false?
> > > 
> > > 
> > > You mean, by omitting the osd in the CRD, OSDs are getting deleted, if removeOSDsIfDownAndSafeToRemove = true and osd is out and safe-to-remove? IMO we should never delete OSDs by omitting them in the CRD. Or do you have something else in mind?
> > 
> > 
> > I meant `kubectl delete deployment <name of the OSD deployment>` when `removeOSDsIfDownAndSafeToRemove = false`
> 
> We had a similar discussion in #3954 :
> 
>     * What about the [`local-devices-*` config maps](https://github.com/rook/rook/pull/3954#discussion_r329679342) with might need to get modified?
> 
>     * Who is supposed to run `ceph osd purge`?
> 
as per discussion in https://github.com/rook/rook/issues/2741#issuecomment-479219289 we were just removing the K8s artifacts when the OSD is cleaned up by Ceph and is safe-to-destroy

> 
> I'd favor to let the operator change the kubernetes primitives.
