### ISSUE TITLE
It is expected that rook ceph can customize the public network, not necessarily using the node ip address of k8s (pod uses host network mode)

### ISSUE THREAD

**Issue by weisongf** [rook/rook#4004]
**Is this a bug report or feature request?**

* feature request

**What should the feature do:**

I expect rook ceph to customize the public network, not necessarily using the node ip address of k8s (pod uses host network mode)

**What is use case behind this feature:**
```     
root@master1:/opt/rook-charts/rook-ceph/templates# kubectl get nodes -owide
NAME      STATUS   ROLES                 AGE   VERSION   INTERNAL-IP    EXTERNAL-IP     CONTAINER-RUNTIME
master1   Ready    master,monitor,node   30d   v1.14.3   172.16.2.111   <none>          docker://18.9.8
master2   Ready    master,monitor,node   30d   v1.14.3   172.16.2.112   <none>          docker://18.9.8
master3   Ready    master,monitor,node   30d   v1.14.3   172.16.2.113   <none>          docker://18.9.8

22: storpub: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1
    link/ether 16:23:51:58:62:50 brd ff:ff:ff:ff:ff:ff
    inet 172.16.4.111/24 brd 172.16.4.255 scope global data
       valid_lft forever preferred_lft forever
    inet6 fe80::1423:51ff:fe58:6250/64 scope link 
       valid_lft forever preferred_lft forever
19: storclus: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1
    link/ether 1e:43:dc:64:f8:1e brd ff:ff:ff:ff:ff:ff
    inet 172.16.5.111/24 brd 172.16.5.255 scope global storpub
       valid_lft forever preferred_lft forever
    inet6 fe80::1c43:dcff:fe64:f81e/64 scope link 
       valid_lft forever preferred_lft forever


```
Want to use a separate public storage network :172.16.4.0/24,cluster network:172.16.5.0/24

**Environment**:
* Rook version (use rook version inside of a Rook Pod):
1.0.3
* Storage backend version (e.g. for ceph do ceph -v):
v12.2.11-20190319
* Kubernetes version (use kubectl version):
v1.14.3

**Comment by leseb** [comment]
Rook cannot do this kind of decision for you. Rook has no idea that a particular interface should be used against another. You need to supply that information to Rook via a Config Override. Please read: https://rook.io/docs/rook/v1.1/ceph-advanced-configuration.html#custom-cephconf-settings
