### ISSUE TITLE
restart one node ceph become avariable

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#4015]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
image: rook/rook:master
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

old volume cannot write data
new volume cannot bind

```
 Warning  FailedMount  5m54s (x6 over 17m)  kubelet, dev6-localdomain  Unable to mount volumes for pod "harbor-harbor-database-0_harbor(af7172a4-c23d-4846-aff5-8b9e512b487f)": timeout expired waiting for volumes to attach or mount for pod "harbor"/"harbor-harbor-database-0". list of unmounted volumes=[database-data]. list of unattached volumes=[database-data default-token-c4kn5]
  Warning  FailedMount  5m (x10 over 18m)    kubelet, dev6-localdomain  MountVolume.SetUp failed for volume "pvc-3d165940-52ee-45d4-acad-9b4531a17c76" : mount command failed, status: Failure, reason: Rook: Mount volume failed: failed to attach volume replicapool/pvc-3d165940-52ee-45d4-acad-9b4531a17c76: failed to map image replicapool/pvc-3d165940-52ee-45d4-acad-9b4531a17c76 cluster rook. failed to map image replicapool/pvc-3d165940-52ee-45d4-acad-9b4531a17c76: Failed to complete 'rbd': signal: interrupt. . output:
```

**Comment by leseb** [comment]
Please re-open a bug with the template fulfilled.

**Comment by 13567436138** [comment]
restart the rook pod，solve my problem
