### ISSUE TITLE
CephBlockPool updating failureDomain

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#4029]
running rook 1.1.1.

In minikube I launched ceph. created 3 osds. then created a CephBlockPool with no failureDomain specified. It defaulted to host apparently. The cluster became unstable as it couldn't fully provision. I updated failureDomain to be osd and it did not apply the update. I deleted the operator and it relaunched, resetting things up and it still didn't apply. Manually editing the crushmap to fix the failure domain fixed it.

This field should probably be synced to the cluster on change.

**Comment by xenolinux** [comment]
@travisn Could you please assign this issue to me? I would like to work on it.

**Comment by xenolinux** [comment]
I tried to reproduce the issue, and it was reproducible.

The steps I used to reproduce are as below:
1. Created replicated CephBlockPool with default failureDomain `host`. https://rook.io/docs/rook/v0.9/ceph-pool-crd.html 
2. Changed `failureDomain` from `host` to `osd` in CephBlockPool 's CRD.
3. The applied changes didn't reflect in ceph CRUSH map when extracted in ceph toolbox.

**Comment by D13410N3** [comment]
Any news on this? Is failureDomain change possible on working pool?

**Comment by parth-gr** [comment]
cc @travisn we can change the device class,  By changing the crush rule,
Maybe we can do it same for failure domain

**Comment by travisn** [comment]
This is actually already possible now, fixed long ago with #9214.
