### ISSUE TITLE
CephBlockPool reuse safeness

### ISSUE THREAD

**Issue by albertdb** [rook/rook#4034]
Hi,

Is it safe to use the same CephBlockPool for several StorageClass?  E.g. one with fsType xfs and other with ext4.

Is it the same answer true for erasure coded StorageClasses?

Sorry if these are basic concepts, but I don't see them documented anywhere.

Thanks.

**Comment by travisn** [comment]
@albertdb Yes, it is fine to use the same CephBlockPool from multiple storage classes. As long as the same pool properties are desired, then you could use different storageclass properties to get the desired behavior. For quick questions in the future, feel free to join the [Rook Slack](https://slack.rook.io/)
