### ISSUE TITLE
Ceph-OSD-prepare Issue

### ISSUE THREAD

**Issue by NahaliY** [rook/rook#4035]
H Rook community, 
When attempting to deploy OSD pods, ceph-osd prepare launch the command  in all disks ````  lsblk --all --noheadings --list --output KNAME ```` , also when a filter on disks is created ```` deviceFilter: ^sd[b-c] ```` , In my case, the sod-prepare was blocked in checking a disk which is /dev/fd0 , https://gist.github.com/NahaliY/d50c466912daf892777c6c3fbce5d275
 I solved the problem by deleting the fd0.

**Comment by leseb** [comment]
This will likely go away once @jmolmo is done with https://github.com/rook/rook/issues/2606.

**Comment by galexrt** [comment]
@leseb #2606 has been closed by #4053. Can this be closed then or does this need to be tested?
