### ISSUE TITLE
Start using errors.Wrap() instead of fmt.Errorf

### ISSUE THREAD

**Issue by leseb** [rook/rook#4054]
Rook could benefit from using `errors.Wrap()` as well as `errors.Wrapf()` so the error formatting is handled by the package. Many projects under the Kubernetes umbrella use it. Also:

* from a formatting standpoint, the code will be cleaner
* reviews will be more focus since reviewers won't have to explicitly explain on to handle errors and which interface type to use (`%v` versus `+%` for example)

Currently, they are around 1414 occurrence of `fmt.Errorf` which should be changed so we need to decide as a group :).
This means using `"github.com/pkg/errors"`.

**Comment by travisn** [comment]
Agreed that this would be a better approach to error handling. Some thoughts:
- Can you show an example of what it looks like to print an error to the log? What will it look like compared to our current approach that has multiple sentences? For example, what do you see with err.String() if the error has been wrapped multiple times?
- Since this is such a big change we shouldn't backport it. This will likely cause merge conflicts for changes that are backported after this, so we should likely make it when we are closer to the v1.2 release. 
- It would be very tedious to update all these manually. The update could be (mostly) automated, right?

**Comment by leseb** [comment]
Inline:

> Agreed that this would be a better approach to error handling. Some thoughts:
> 
> * Can you show an example of what it looks like to print an error to the log? What will it look like compared to our current approach that has multiple sentences? For example, what do you see with err.String() if the error has been wrapped multiple times?

Snippet:

```golang
a := errors.New("an error")
err := errors.Wrapf(a, "%s", "oops")
fmt.Println(err)
```

This returns:

```
oops: an error
```

A more complex example:

```golang
package main

import (
	"fmt"
	"os"

	"github.com/pkg/errors"
)

func readConfig(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return errors.Wrapf(err, "%s", "error opening config file")
	}

	defer file.Close()
	return nil
}

func foo() error {
	err := readConfig("foobar")
	if err != nil {
		return errors.Wrapf(err, "%s", "error calling readConfig")
	}

	return nil
}

func main() {
	err := foo()
	if err != nil {
		fmt.Println(err)
	}
}
```

Will produce:

`error calling readConfig: error opening config file: open foobar: no such file or directory`.

> * Since this is such a big change we shouldn't backport it. This will likely cause merge conflicts for changes that are backported after this, so we should likely make it when we are closer to the v1.2 release.

Agreed.

> * It would be very tedious to update all these manually. The update could be (mostly) automated, right?

Yes, most of it *can* be automated but carefully verified.


Does that help?

**Comment by leseb** [comment]
> Ok, the only visible difference is really that the errors are printed separate by colons instead of periods. So the question really comes down to when to make the change to reduce the merge conflicts.

Correct, probably at the end of a cycle? Which means keeping it in sync or at least build the automation for this.

wdyt?

**Comment by travisn** [comment]
What if we just wait 4-6 weeks? By then the backports should at least be much less often.

**Comment by leseb** [comment]
Yes!
