### ISSUE TITLE
CSI CephFS driver is loading fuse driver regardless of kernel

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4055]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In csi-cephfsplugin-* logs I get:

```
volumemounter.go:77[] kernel version < 4.17 might not support quota feature, hence not loading kernel client
volumemounter.go:82[] loaded mounter: fuse
```

on nodes with 5.1.7 and 5.3.1 kernels

**Expected behavior:**
Use kernel client

**How to reproduce it (minimal and precise):**
Use CSI with 5.* kernels

**Environment**:
* OS (e.g. from /etc/os-release):
Centos 7.6
* Kernel (e.g. `uname -a`):
Linux k8s-haosu-01.sdsc.optiputer.net 5.1.7-1.el7.x86_64 #1 SMP Thu Jun 6 05:37:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):
1.1.2

**Comment by dimm0** [comment]
P.S. I'm getting 40 MB/s write speed in a cluster of 5 nodes with NVMEs 😂

**Comment by dimm0** [comment]
And 2.4GB/s write with kernel mount from tools pod

**Comment by travisn** [comment]
@ajarr could you take a look? though i'm assuming we should move this to the ceph-csi repo

**Comment by dimm0** [comment]
BTW having quotas isn't worth a 100x decrease in performance IMHO... I'd rather always use kernel, and disable features that it doesn't support

**Comment by Madhu-1** [comment]
This is fixed in csi master, missed to backport to 1.2.2 release

**Comment by Madhu-1** [comment]
We have added a parameter to force use kernel client, even if the kernel is less than 4. 17 this will be available in next csi release

**Comment by dimm0** [comment]
Can I switch ROOK_CSI_CEPH_IMAGE then?
I'm looking at https://quay.io/repository/cephcsi/cephcsi?tab=tags

**Comment by Madhu-1** [comment]
Canary image will be updated frequently and can break any time, if this is testing environment you can use it

**Comment by dimm0** [comment]
No, it's production cluster..

**Comment by Madhu-1** [comment]
Suggest to wait for next CSI release to fix this

**Comment by dimm0** [comment]
How long? I've already switched a bunch of users to the csi...

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/issues/639 csi 1.2.2 release date

**Comment by dimm0** [comment]
Could you make a release with just this https://github.com/ceph/ceph-csi/commit/197c8fcfcc73864061e91be59fb44625d9ea4eeb fix on top of current one? Please?

**Comment by dimm0** [comment]
Built my own. Closing.
