### ISSUE TITLE
Does rook support S3?

### ISSUE THREAD

**Issue by 1605200517** [rook/rook#4059]
While S3 is an important storage interface, implementations being available not only from the original vendor, is it possible to use it with Rook?

**Comment by leseb** [comment]
You should **really** consider reading the doc: https://rook.io/docs/rook/v1.1/ceph-object.html. Thanks.

As mentioned before, GitHub issues are **only** for opening bugs or features. The rest is either in the documentation or on Slack: https://slack.rook.io/.
