### ISSUE TITLE
The cluster is in "HEALTH_WARN" state after upgrade from v1.0.2 to v1.1.2

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#4079]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The health state became "HEALTH_WARN" after upgrade. It was "HEALTH_OK" before upgrade.
1).  "crush map has legacy tunables"
2). Too many PGs per OSD.  

```
2019-10-09 16:38:27.123404 I | exec: Error ERANGE: pool id 1 pg_num 100 size 3 would mean 2100 total pgs, which exceeds max 750
(mon_max_pg_per_osd 250 * num_in_osds 3)
2019-10-09 16:38:27.123534 E | op-pool: failed to create pool replicapool. failed to create pool replicapool. failed to set pool
property size on pool replicapool, exit status 34
 cluster:
    id:     986d30fb-334d-47a1-8789-0b0f6f316b68
    health: HEALTH_WARN
            crush map has legacy tunables (require firefly, min is hammer)
            too many PGs per OSD (700 > max 250)
 
  services:
    mon: 3 daemons, quorum a,b,c (age 4h)
    mgr: a(active, since 2h)
    osd: 3 osds: 3 up (since 21h), 3 in (since 22h)
 
  data:
    pools:   7 pools, 700 pgs
    objects: 203 objects, 4.1 KiB
    usage:   3.0 GiB used, 54 GiB / 57 GiB avail
    pgs:     700 active+clean
```
**Expected behavior:**
Need workaround/procedure to make the cluster as "HEALTH_OK".
Also, adjusting/lowering the PG number may not be a good solution for an existing field deployment. 

**How to reproduce it (minimal and precise):**

Deploy rook v1.0.2 then upgrade to v1.1.2. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by yanchicago** [comment]
Used below workaround in toolbox container:

1). ceph osd crush tunables optimal
2). for pool in `ceph osd pool ls` ; do ceph osd pool set $pool pg_autoscale_mode on ;  done
- Take some time to rebalance for ceph status to become "HEALTH_OK"

**Comment by petre** [comment]
If you'e running Ceph Nautilus you can enable pg_autoscaler module to fix this issue, more information here: https://rook.io/docs/rook/v1.1/ceph-configuration.html
