### ISSUE TITLE
Improvements for running integration-tests on minikube

### ISSUE THREAD

**Issue by OwenTuz** [rook/rook#4088]
**Is this a bug report or feature request?**
* Feature Request

Raising an issue to raise a PR against, hope this is ok. 
While setting up to run the integration tests using Minikube on a Linux machine, I came across two issues:

- dataDir settings for minikube are only set when `GOOS=darwin`, so by default minikube won't work unless you're using a Mac.
- The smoke tests for the Ceph object store fail when trying to PUT an object from the host. This is most easily solved by just running `minikube tunnel` while the tests are in progress.

As a quick fix, I'd suggest allowing users to set an environment variable such as `ROOK_K8S_IS_MINIKUBE=true`, and documenting both this and the use of `minikube tunnel`.

**Comment by travisn** [comment]
@OwenTuz It would be great to fix the integration tests to support more environments and document what is needed for different environments where we can't automatit, thanks!
