### ISSUE TITLE
Generate keyrings before creating deployments that depend on them

### ISSUE THREAD

**Issue by travisn** [rook/rook#4089]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Per discussion [here](https://github.com/rook/rook/pull/3554#discussion_r333745066), we should be able to generate a keyring before creating a deployment that depends on the keyring. This will help us avoid an intermittent pod failure condition that looks awkward. 

**Expected behavior:**
If we're just doing this in order to assign the owner reference to the deployment, I'd suggest we create the secret first, then update the secret with the owner reference if needed. Updating the secret is less intrusive than having the pod fail and restart.

**Comment by egafford** [comment]
This issue comprises multiple commits across several daemons, and was closed by a somewhat overeager bot. Reopening to post new commits.
