### ISSUE TITLE
Mon Canary pods sometimes take a long time to terminate

### ISSUE THREAD

**Issue by travisn** [rook/rook#4105]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The mon canary deployment is expected to be temporary. As soon as it starts, the operator tears it down so the mon daemon can be started. On occasion, it is seen that the canary pod can take over a minute to cleanup, which delays the operator unnecessarily.

Under normal execution the canary pods are deleted within a few seconds and the following entry is seen only a couple times. When the canary pod gets stuck, this message is seen for a minute for the timeout.
```
2019-10-14 23:17:17.191241 I | op-k8sutil: rook-ceph-mon-a-canary still found. waiting...
...
2019-10-14 23:18:15.273372 I | op-k8sutil: rook-ceph-mon-a-canary still found. waiting...
2019-10-14 23:18:17.273759 I | op-mon: assignmon: error deleting canary deployment rook-ceph-mon-a-canary. gave up waiting for rook-ceph-mon-a-canary pods to be terminated
```

This is also periodically causing the integration tests to fail the MultiClusterSuite. The additional time to start the cluster is causing a timeout in the test. For example, see [this build](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-4098/3/pipeline) with this [operator log](https://jenkins.rook.io/job/rook/job/rook/job/PR-4098/3/artifact/_output/tests/TestCephMultiClusterDeploySuite_aws_1.15.x_mrc-n1-system_rook-ceph-operator-599c546b5b-qdvz2_1571095223.log) where the [last message](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-4098/runs/3/nodes/55/steps/113/log/?start=0) in the test was that it gave up waiting for the mons in the second cluster:
```
2019-10-14 23:20:19.523071 I | testutil: waiting for 3 pods (found 0) with label app=rook-ceph-mon in namespace mrc-n2
```

**Expected behavior:**
The canary pods should more consistently be cleaned up quickly.

**How to reproduce it (minimal and precise):**

Start a cluster with three mons. Repeat a number of times until you see a canary pod that is delayed.

**Comment by BlaineEXE** [comment]
@shaas do you want to open a WIP PR for this with your current findings?

**Comment by shaas** [comment]
I will close this issue as it is not reproducible anymore with the latest release of rook.
