### ISSUE TITLE
Custom annotations not added to MGR deployment/pod

### ISSUE THREAD

**Issue by hmm01i** [rook/rook#4106]
Yes

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Custom annotations defined in CephCluster are not added to MGR deployment/pod. Only default Prometheus annotations are present.

**Expected behavior:**
Custom annotations should added to MGR deployment/Pod.

**How to reproduce it (minimal and precise):**

1. Add custom annotations to CephCluster (cluster.yaml). eg:
```
  annotations:
    all:
      comment: 'CephFS for Jenkins'
    mgr:
      ad.datadoghq.com/mgr.check_names: '["prometheus"]'
      ad.datadoghq.com/mgr.init_configs: '[{}]'
```

2. kubectl apply -f cluster.yaml
3. Only default prometheus annotations are present on mgr deployment/pod.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Container Linux by CoreOS (2135.6.0)
* Kernel (e.g. `uname -a`): Linux nonprodtest-worker0 4.19.56-coreos-r1 #1 SMP Tue Jul 30 06:40:10 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz GenuineIntel GNU/Linux
* Cloud provider or hardware configuration: Azure
* Rook version (use `rook version` inside of a Rook Pod): v1.0.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:30:22Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): (Custom / RKE)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by leseb** [comment]
I have a fix for this here: https://github.com/rook/rook/pull/4077/commits/02d34e5c300e1822dd84e5c8324d04f99f42bd7e

I will extract it from that PR since it's not ready yet.

**Comment by leseb** [comment]
Will be in 1.1.3.
