### ISSUE TITLE
hostnetwork public network

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#4117]
In a rook 1.1.2 cluster, I tried to setup a public/private network as described in the manual.

I have a 3rd network though I was using for backend kubelet traffic (internal).

Rook is using the kubelet ip as the ip for the mons which isn't necessarily the public ip. There should be a way to decouple this.

**Comment by travisn** [comment]
@kfox1111 With v1.3 there is now an option to use [multus](https://github.com/rook/rook/blob/release-1.3/cluster/examples/kubernetes/ceph/cluster.yaml#L73-L84) for more advanced networking. Is this an option?

**Comment by kfox1111** [comment]
I'm not sure. the cluster is set to net=host so that all the networks are available.

rook though is using the node ip for building the ceph configs.

I don't think I can change net=host to net!=host after deployment, which I think would be needed for multus. When I tried to do net!=host to net=host it went really poorly. I had to burn down the cluster.

**Comment by travisn** [comment]
Yeah it would only apply to new clusters. Changing a mon endpoint for any reason doesn't work since it's a part of the mon identity.
