### ISSUE TITLE
How to specify the apiserver address of the ceph connection

### ISSUE THREAD

**Issue by xiaoqge** [rook/rook#4122]
Our kubernetes cluster prohibits the use of svc services, so all of our services specify the apiserver fixed address at startup, but whether rook-ceph can specify the api-server IP address before starting, instead of getting the default apiserver address。

` rook-discover: failed to update device configmap: Get https://10.9.60.1:443/api/v1/namespaces/rook-ceph/configmaps/local-devic-oam-k8snode-test-0013.xxxx.com: dial tcp 10.9.60.1:443: connect: no route to host`

I want to specify the default kubernetes svc address obtained in the above error log before starting the service. We have the correct apiserver address. Is there a way? thank you very much

**Comment by travisn** [comment]
@xiaoqge Rook gets the cluster from `rest.InClusterConfig()` [here](https://github.com/rook/rook/blob/master/cmd/rook/rook/rook.go#L106). Try setting the env variables on the operator to override the defaults: `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`. However, Rook doesn't currently pass those onto other pods that access the k8s api (mgr and osd pods), so you may still run into an issue with this approach. It would be great to know what issues you run into so we can fix this scenario.

**Comment by xiaoqge** [comment]
@travisn You are right, I am starting rook-discove and can't connect to the api-server address. Can I pass the KUBERNETES_SERVICE_HOST variable to the rook-discove Pod?

**Comment by travisn** [comment]
Adding variables to the rook-discover (and other rook daemons) would require a code change unfortunately. But I’m surprised this would be needed. Are you not having similar issues with other K8s apps or operators?

Travis

**Comment by xiaoqge** [comment]
I use other components, such as the log els filebeat component that supports the incoming KUBERNETES_SERVICE_HOST variable to modify the address of the api server.

**Comment by xiaoqge** [comment]
I currently use components around k8s, which support the KUBERNETES_SERVICE_HOST variable to modify the address of the api server.

**Comment by xiaoqge** [comment]
Because of the particularity of the business, our k8s cni components use macvlan, and the environment does not use k8s svc service at all, no need to go through iptables, so we start the service directly to specify the address and port of k8s api server. The filebeat or prometheus we currently use support incoming variables to modify the address of the api server.

**Comment by travisn** [comment]
Ok, we would need the operator to pass on these variables to the pod specs for all the deployments that would need to access the k8s api. This would include at least the discovery, agent, mgr, and osds.

**Comment by xiaoqge** [comment]
Thank you very much.

**Comment by xiaoqge** [comment]
Since the rook must use the k8s service function, we have already opened it and the problem is solved.
