### ISSUE TITLE
Fresh Install: /var/lib/kubelet - Missing Directories

### ISSUE THREAD

**Issue by midacts** [rook/rook#4133]
* Bug Report

**Deviation from expected behavior:**

These containers stay in 'ContainerCreating'
```text
csi-rbdplugin-ft8hz        0/3     ContainerCreating   0          5m55s
csi-cephfsplugin-tfhkm     0/3     ContainerCreating   0          5m55s
```

Here is the errors:
```text
Events:
  Type     Reason       Age                    From                      Message
  ----     ------       ----                   ----                      -------
  Normal   Scheduled    5m51s                  default-scheduler         Successfully assigned rook-ceph/csi-cephfsplugin-tfhkm to midacts-k3stest
  Warning  FailedMount  101s (x10 over 5m51s)  kubelet, midacts-k3stest  MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /var/lib/kubelet/plugins_registry/ is not a directory
  Warning  FailedMount  101s (x10 over 5m51s)  kubelet, midacts-k3stest  MountVolume.SetUp failed for volume "pods-mount-dir" : hostPath type check failed: /var/lib/kubelet/pods is not a directory
  Warning  FailedMount  90s (x2 over 3m48s)    kubelet, midacts-k3stest  Unable to mount volumes for pod "csi-cephfsplugin-tfhkm_rook-ceph(3254e63f-c30c-46a7-b361-33ee21b154ae)": timeout expired waiting for volumes to attach or mount for pod "rook-ceph"/"csi-cephfsplugin-tfhkm". list of unmounted volumes=[registration-dir pods-mount-dir]. list of unattached volumes=[plugin-dir csi-plugins-dir registration-dir pods-mount-dir host-sys lib-modules host-dev mount-cache-dir ceph-csi-config keys-tmp-dir rook-csi-cephfs-plugin-sa-token-6bdhg]
```

**Expected behavior:**

Should just work

**How to reproduce it (minimal and precise):**

Running Linux mint 18.2 xfce on Hyper-V.
I installed k3s: `curl -sfL https://get.k3s.io | sh -`
then ran the following:
```bash
kubectl create -f common.yaml
kubectl create -f operator.yaml
kubectl create -f cluster-test.yaml
```

- [common.yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml)
- [operator.yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml)
- [cluster-test.yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/rbd/cluster-test.yaml)

**Environment**:
* OS (e.g. from /etc/os-release): Linux Mint 18.2
* Kernel (e.g. `uname -a`): Linux 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Hyper-V on Windows 10 desktop
* Rook version (use `rook version` inside of a Rook Pod): latest - 1.1
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher K3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by midacts** [comment]
After creating these directories:
- `/var/lib/kubelet/plugin_registry`
- `/var/lib/kubelet/pods`

The pods finally worked.

Is this something that should be manually created?
Or something that should be automatically done as part of the deploy?

**Comment by Madhu-1** [comment]
dup of https://github.com/rook/rook/issues/3921

RKE runs kubelet in a container with --root-dir=/opt/rke/var/lib/kubelet , you need to configure the operator
```
- name: ROOK_CSI_KUBELET_DIR_PATH
  value: "/opt/rke/var/lib/kubelet"
```

please reopen if the issue presists

**Comment by midacts** [comment]
Sorry for the duplicate issue. I wasn't sure if that issue was the same.

I checked my server and it doesn't have an `/opt/rke` directory?

**Comment by Madhu-1** [comment]
Please check kubelet runtime directory path, we should not manually create these directories

**Comment by midacts** [comment]
How can I find the root path i am looking for?

```text
find / -name kubelet
/var/lib/kubelet
/var/lib/rancher/k3s/agent.kubelet
```

**Comment by midacts** [comment]
kubelet before the k3s install:
```text
midacts-k3s-csi ~ # find / -name kubelet
find: ‘/run/user/1000/gvfs’: Permission denied
```

k3s install:
```text
midacts-k3s-csi ~ # curl -sfL https://get.k3s.io | sh -
[INFO]  Finding latest release
[INFO]  Using v0.9.1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.9.1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.9.1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink from /etc/systemd/system/multi-user.target.wants/k3s.service to /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
```

kubelet after the k3s install:
```text
midacts-k3s-csi ~ # find / -name kubelet
/var/lib/rancher/k3s/agent/kubelet
find: ‘/run/user/1000/gvfs’: Permission denied
```

Updating the `operator.yaml` file to this fixed it:
```text
- name: ROOK_CSI_KUBELET_DIR_PATH
  value: "/var/lib/rancher/k3s/agent/kubelet"
```

Thanks for your help on this

**Comment by seimsel** [comment]
For microk8s you need to change the following in the operator.yaml

ROOK_CSI_KUBELET_DIR_PATH: "/var/snap/microk8s/common/var/lib/kubelet"
