### ISSUE TITLE
Using ceph-objectstore-tool

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4134]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
How could I use the ceph-objectstore-tool with new style OSDs, when there's no datadir on the physical node, and everything is inside the pod? I need the OSD stopped when doing maintenance, and I can't find how I can run a container without actually starting an OSD

`/rook/rook ceph osd provision` seems to also start an OSD

**What is use case behind this feature:**
Need to do cluster maintenance when it breaks

**Comment by dimm0** [comment]
Copying files from running pod to the node helped

`kubectl exec rook-ceph-osd-106-6b98dc8b7f-kgwks -- tar cf - "/var/lib/ceph/osd/ceph-106/" > osd106.tar`

**Comment by dimm0** [comment]
Maybe there's something easier than installing ceph on the node and copying files from the OSD?
(Also can't copy from crashlooping pods)

**Comment by leseb** [comment]
What if you override the deployment command of the OSD? Just like explained here: https://rook.io/docs/rook/master/disaster-recovery.html with the `patch`? With that, you will get the extract same context.

Then simply run `ceph-volume lvm activate --no-systemd $OSD_ID` inside the container.
You should be able to play with `ceph-objectstore-tool `.

**Comment by dimm0** [comment]
Then the config folder is empty, tried that

**Comment by dimm0** [comment]
Ah! I didn't know about ceph-volume lvm activate
Is that what creates the files?

**Comment by leseb** [comment]
Yup.

**Comment by dimm0** [comment]
Great, will try. Thanks!

**Comment by dimm0** [comment]
Getting:

`ceph_volume.exceptions.MultipleLVsError: Got more than 1 result looking for None with path: None`

if running `ceph-volume lvm activate --no-systemd $ROOK_OSD_ID`

and `RuntimeError: could not find osd.47 with fsid 90a5afad-c313-4e49-9b5f-317100c6930e`

for `ceph-volume lvm activate --no-systemd $ROOK_OSD_ID $ROOK_FSID`

**Comment by dimm0** [comment]
Succeeded by actually running the original command, which failed, but created all files for me.
