### ISSUE TITLE
operator rook ceph rook-ceph-block has not create pv,pvc

### ISSUE THREAD

**Issue by duiniwukenaihe** [rook/rook#4154]
[my  environment is kubernetes 1.16.2 and rook commit is b7d8338d0c362ed7da5af28341ccc46410cb3e26  ,I have create rbd storageclass.yaml  default，but my pv,pvc i also pending .I have describe pvc 

>   Normal   Provisioning          66s (x9 over 3m14s)  rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-69c9869dc9-v4j7v_46988982-f585-11e9-82fc-7246f10449e2  External provisioner is provisioning volume for claim "default/rbd-pvc"
  Warning  ProvisioningFailed    66s (x9 over 3m14s)  rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-69c9869dc9-v4j7v_46988982-f585-11e9-82fc-7246f10449e2  failed to provision volume with StorageClass "rook-ceph-block": error getting secret rook-csi-rbd-provisioner in namespace rook-ceph: secrets "rook-csi-rbd-provisioner" not found
  Normal   ExternalProvisioning  6s (x14 over 3m14s)  persistentvolume-controller                                                                                 waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator

what can i do  for this problem

**Comment by Madhu-1** [comment]
please fill the bug template while reporting the bug

**Comment by frouzbeh** [comment]
@Madhu-1 Has this problem been fixed? I'm facing the same issue. The secret is in rook-ceph-cluster namespace (the same as the ceph cluster, rook operator is in rook-ceph namespace).

**Comment by steepestascent** [comment]
If you are deploying the cluster to a different namespace than `rook-ceph` there are 3 values you need to override:

```
csi.storage.k8s.io/provisioner-secret-namespace
csi.storage.k8s.io/controller-expand-secret-namespace
csi.storage.k8s.io/provisioner-secret-namespace
```

**Comment by travisn** [comment]
If using a namespace other than the default `rook-ceph`, see [this topic](https://rook.github.io/docs/rook/v1.7/ceph-advanced-configuration.html#using-alternate-namespaces) as well.
