### ISSUE TITLE
Helm chart index is delayed after a release due to caching

### ISSUE THREAD

**Issue by travisn** [rook/rook#4176]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The `promote` step in the CI pipeline will publish the helm chart and add it to the [index.yaml](https://charts.rook.io/release/index.yaml). However, the update to the index.yaml cannot be seen for some time period (~1 day) due to caching somewhere. We should find where this cache is so users can more promptly update their Rook install if they so desired.

**Expected behavior:**
The helm chart should be available for install immediately after the release.

**Comment by galexrt** [comment]
@travisn The Helm Charts are pushed to an AWS S3 bucket, so the caching is probably on AWS S3 side.

**Comment by Antiarchitect** [comment]
Hi guys. I've noticed that you're using CloudFront + AWS Bucket and having troubles with invalidating /release/index.yaml
My guess is to add special CloudFront Distribution Behavior for path /release/index.yaml and choose Object Caching -> Customise and set default and maximum TTLs not so high as the default (86400s or 24h I think) set it for example to 300s or 5m. This should help.
@travisn

**Comment by travisn** [comment]
@jbw976 Can you check the helm index.yaml and change the TTL? I don't believe I have access.

**Comment by jbw976** [comment]
great information @Antiarchitect, thank you for providing that! I have created a new cloudfront behavior for `*index.yaml` so it covers master, release, and any other channels we may use.  I have set default and maximum TTLs to 300.  Screenshot below for any other settings that I may have missed.  Hopefully this makes a difference, thanks a lot for the information! 🙇 

![Screen Shot 2020-04-08 at 7 40 58 AM](https://user-images.githubusercontent.com/4313439/78797535-b054d580-796c-11ea-941a-1f005c2b8380.png)

**Comment by Antiarchitect** [comment]
According to the docs: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesPathPattern
You can use `*.yaml` pattern for this purpose.

**Comment by jbw976** [comment]
I have edited the behavior rule to make it for `*.yaml` pattern instead 🚀

**Comment by obeyler** [comment]
may you have to regenerate the chart as after the 300s (5 min) the last version 1.3.0 in index.yaml isn't still present

**Comment by Antiarchitect** [comment]
For now, old cache is still present:
age: 119947
content-length: 10094
content-type: binary/octet-stream
date: Tue, 07 Apr 2020 19:27:02 GMT
etag: "03b8beb36d739169e909951347785a5c"
last-modified: Thu, 26 Mar 2020 23:52:24 GMT

It may need some time as a CloudFront is actually big. Another option is to forcefully invalidate it for the first time.

**Comment by jbw976** [comment]
I just kicked off an invalidation for `*` to hopefully just get everything fresh 😊

**Comment by obeyler** [comment]
Great it works !
