### ISSUE TITLE
VolumeSnapshots never go into Ready-To-Use state if using old CRDs

### ISSUE THREAD

**Issue by mohahmed13** [rook/rook#4178]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behaviour:**

We experimented with the CephCSI drivers back in Rook v1.0 so our cluster had some old CRDs. Specifically: 
* volumesnapshotclasses.snapshot.storage.k8s.io
* volumesnapshotcontents.snapshot.storage.k8s.io
* volumesnapshots.snapshot.storage.k8s.io

Upon running through an upgrade to Rook v1.1 and switching to using the CephCSI drivers for RBD, those CRDs don't get updated. Trying to take a volume snapshot produces this error in the csi-snapshotter logs: 

`E1015 20:47:13.057258       1 goroutinemap.go:150] Operation for "create-wordpress/mysql-csi-pvc[b1bc1c9d-ef8c-11e9-bdcd-901b0e6be2b4]" failed. No retries permitted until 2019-10-15 20:47:15.057225226 +0000 UTC m=+3214.959239580 (durationBeforeRetry 2s). Error: "snapshot controller failed to update wordpress/mysql-csi-pvc on API server: the server could not find the requested resource (put volumesnapshots.snapshot.storage.k8s.io mysql-csi-pvc)"`

Describing the VolumeSnapshot also show that the Ready To Use is false. 

**Expected behaviour:**

The Volumesnapshot should be created successfully without errors in the logs and the "Ready To Use" status should be set to true. 

The root cause was determined to be the old CRDs, as discussed here: https://github.com/kubernetes-csi/external-snapshotter/issues/147#issuecomment-513664310

Upon deleting the old CRDs and restarting the `csi-rbd-provisioner-0` pod, those CRDs were recreated with the new versions and the snapshots were successful. 

**How to reproduce it (minimal and precise):**

This issue was only reproducible due to the fact that we tested CephCSI functionality in v1.0. I reviewed the upgrade docs again and the upgrade-from-v1.0-crds.yaml but there's no mention of deleting the CRDs.

**Comment by mohahmed13** [comment]
I think a doc update would be sufficient. Since there is already a section about upgrading from previous Rook version when using CephCSI, it could be amended. Happy to draft up a PR for that if needed.

**Comment by Madhu-1** [comment]
@mohahmed13 can you  please send a PR for the same

**Comment by mohahmed13** [comment]
@Madhu-1 , I'll create a PR for the docs update to resolve this issue.

**Comment by Madhu-1** [comment]
Fixed in https://github.com/rook/rook/pull/4302
