### ISSUE TITLE
OSD on PVC: Support LVM's logical volume

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#4185]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Support LV with OSD on PVC.

**What is use case behind this feature:**

PV would be not only physical devices but also logical devices. For example,
there is a CSI plugin using LVM.

https://github.com/cybozu-go/topolvm

There is a PR to support LV with OSD. However, it's not for OSD on PVC,
but on normal block devices:
https://github.com/rook/rook/pull/2100

**Comment by travisn** [comment]
@satoru-takeuchi Can you add more details for this scenario? The CSI driver is independent from the OSDs, so I'm not sure what feature you're requesting. If this is for a feature request for  OSDs on PVCs, can you give an example for how it is related to the StorageClassDeviceSet in this [design doc](https://github.com/rook/rook/blob/master/design/storage-class-device-set.md)? Thanks!

**Comment by satoru-takeuchi** [comment]
@travisn OK, I should explain this issue in detail.

There is no problem with StorageClassDeviceSet level. However, there are several problems
to use LV-based PVC as OSD.

First, LV is not regarded as valid block device in PopulateDeviceInfo.

https://github.com/rook/rook/blob/master/pkg/clusterd/disk.go#L84

So `rook-ceph-osd-prepare` pod fails with the following log.

```
2019-10-17 02:59:50.640651 I | exec: Running command: lsblk /mnt/set1-0-data-kvd8t --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
failed to get device info for /mnt/set1-0-data-kvd8t. unsupported diskType lvm
```

Second, when executing `ceph-volume lvm prepare --data` , we should pass LV not as
`<path/to/device>`, but `<vg_name/pv_name>` way. However, there is no such logic.

I'm preparing a PR that solves these problems.

**Comment by R-omk** [comment]
@travisn, Please explain me.

Suppose I have two lvm groups vg-nvme and vg-hdd.

I can create PVs with different fast-block and slow-block classes and associate them with different lvs respectively vg-nvme / ceph-metadata and vg-hdd / ceph-data.

How can I configure CephCluster so that metadata (wal, db) is placed on the fast drive, and the data on the slow one.

Can I even use the existing lvm instead of the raw device for metadata?

**Comment by travisn** [comment]
@R-omk I believe what you're looking for isn't implemented yet with OSDs on PVCs. See "Example 5: Multiple devices per OSD" in the [design doc for storageClassDeviceSets](https://github.com/rook/rook/blob/master/design/ceph/storage-class-device-set.md). This work item is tracked by #3852. Until it is implemented, the separate of WAL/DB to a higher performance device is only available with raw devices via the `metadataDevice` property as documented in the [Cluster CR](https://rook.io/docs/rook/v1.2/ceph-cluster-crd.html).
