### ISSUE TITLE
Dashboard authentication fails when using kubectl proxy

### ISSUE THREAD

**Issue by zedtux** [rook/rook#4210]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Authenticating to the dashboard works but I'm then ejected so that I remain on the login page.

Looking at the web browser's console network tab, I can see a successful authentication:

![Screenshot 2019-10-29 at 12 45 23](https://user-images.githubusercontent.com/478564/67764332-03377200-fa4a-11e9-83d8-5f0f8a4dde2c.png)

But then there are 4 failing requests:

 - api/summary
 - api/settings/alertmanager-api-host
 - api/health/minimal
 - api/feature_toggles

Replying all with a 401 error similar to this:

```
{
    "status": "401 Unauthorized",
    "version": "3.2.2",
    "detail": "You are not authorized to access that resource",
    "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 653, in respond\n    self.hooks.run('before_handler')\n  File \"/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py\", line 112, in run\n    raise exc\nHTTPError: (401, 'You are not authorized to access that resource')\n"
}
```

FYI I tried to enter a wrong password and there I have an error message on the page which is correct.

**Expected behavior:**

Being able to login and enjoy the Ceph dashboard !

**How to reproduce it (minimal and precise):**

Don't really know how you could reproduce it as I guess the dashboard works for you 🤷‍♂.

What I did is deploying a Rook ceph cluster on my 1 master / 2 workers nodes with the dashboard SSL disabled, executed the `kubectl proxy` command and accessed the http://localhost:8001/api/v1/namespaces/rook-ceph/services/rook-ceph-mgr-dashboard:dashboard/proxy/ URL.

Don't know if this could help you.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
```
# rook version
rook: v1.1.0-beta.0.344.g30d019a
go: go1.11
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
# ceph -v
ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
```
* Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Private custom cluster with `kubeadm`.

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

**Comment by jouve** [comment]
i used this workaround:
```bash
socat TCP-LISTEN:8443,fork,reuseaddr EXEC:"kubectl exec -it debug-696994df8c-m74f7 'socat STDIO TCP:rook-ceph-mgr-dashboard.rook-ceph:8443'"
```

and I connect to the dashboard on https://127.0.0.1:8443

**Comment by zedtux** [comment]
Yep @stale, waiting the rook people to look at this.

**Comment by zedtux** [comment]
No more waiting for the Rook people, we're no more using it.

**Comment by thegreenbear** [comment]
Shame this issue was closed. I am facing the same problem.

**Comment by davidjsherman** [comment]
@thegreenbear For what it is worth I was able to access the dashboard using straightforward [k8s port forwarding](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#forward-a-local-port-to-a-port-on-the-pod):
```
kubectl port-forward -n rook-ceph svc/rook-ceph-mgr-dashboard 8443:8443
```
and connecting to https://localhost:8443.

**Comment by NeilBetham** [comment]
Ran into this as well. The root cause of the OP's issue is that `kubectl proxy` strips out the `Authorization` headers from the proxied request. As such after a successful login the requests to the Ceph API fail because it can't auth the request. This is intended behavior as per https://github.com/kubernetes/kubernetes/issues/38775.

**Comment by MurzNN** [comment]
I've got the same issue, but only when I try to access Dashboard via http protocol, opening using https protocol magically resolves the issue!

**Comment by gs80140** [comment]
have the same issue
