### ISSUE TITLE
Kubelet needs to mount modprobe command as a volume for pods to mount rbd blocks

### ISSUE THREAD

**Issue by kokhang** [rook/rook#423]
This issue is to track a workaround we are using on kubelet. In order to mount block images to hosts and have them consume by pods, kubelet needs to make /sbin/modprobe and /lib/modules available to each container who wants access to the block. This is done by feeding volume mount args to kubelet. https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/kubelet-wrapper.md#allow-pods-to-use-rbd-volumes.

The following track this issues in Kubernetes:
https://github.com/kubernetes/kubernetes/issues/23924
https://github.com/kubernetes/kubernetes/issues/36905

**Comment by bassam** [comment]
related to #432

**Comment by coresolve** [comment]
also related to https://github.com/coreos/tectonic-installer/issues/754

**Comment by philips** [comment]
What is the module and why isn't it loaded automatically by the kernel?

**Comment by kokhang** [comment]
The module is `rbd`. Currently Rook uses the Kubernetes [RBD volume plugin](https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/rbd) to attach/detach rook volumes. This plugin always tries to load the module every time an attachment is to be performed. It does this by shelling out to `modprobe rbd`. The problem with this is when kubelet runs self-hosted (in a container). As self-hosted, the container would need to mount /sbin/modprobe and /lib/modules so that the shell out call succeeds.

This has been recently changed. I submitted a PR so that if `modprobe rbd` fails, it does not fail the workflow. It would simply log a warning message. https://github.com/kubernetes/kubernetes/pull/46016

Loading a kernel module should be a one-time action and it should be done by an admin who is setting up the k8s hosts. Thats why I feel that modprobe failing should not fail the volume-attach workflow.

**Comment by kokhang** [comment]
With #882, this should be addressed
