### ISSUE TITLE
Delete  CSI driver when operator is deleted

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#4234]
**Is this a bug report or feature request?**
* Bug Report
Currently, CSI driver (deployment/stateful and deamonset) is not deleted when the rook operator is deleted

**Expected behavior:**
Deletion of the operator should cleanup the CSI driver if has deployed

**How to reproduce it (minimal and precise):**

* Create rook operator
* Create ceph cluster
* Delete ceph cluster
* Delete rook operator

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
I'd do this when there is no `CephCluster` too.

**Comment by travisn** [comment]
Currently we start the CSI driver when the first CephCluster CR is created. Agreed it would make sense to delete the CSI driver when the last CephCluster CR is deleted.

**Comment by yanchicago** [comment]
Doing an upgrade from earlier release to rook 1.1.4. The original deploy is with flexvolume. After upgrade, I would like to disable CSI related deploy,svc,ds as it's not being used. 
So I patched the operator to set below env variables and restart the operator. 

But "rbdplugin" was restarted after the operator restarts.  They were deleted before operator restarts.

Expects: With CSI flags turns off, CSI related deploy/svc/ds can be disabled permanently.

```
# kns get deploy rook-ceph-operator -o yaml  | grep -A1 CSI
        - name: ROOK_CSI_ENABLE_RBD
          value: "false"
        - name: ROOK_CSI_ENABLE_CEPHFS
          value: "false"
        - name: ROOK_CSI_ENABLE_GRPC_METRICS
          value: "false"

# kns get deploy,ds,svc
NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/csi-rbdplugin-provisioner   0/2     0            0           8m26s
deployment.extensions/rook-ceph-operator          1/1     1            1           13h

NAME                                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.extensions/csi-rbdplugin     0         0         0       0            0           <none>          8m26s
daemonset.extensions/rook-ceph-agent   7         7         7       7            7           <none>          13h
daemonset.extensions/rook-discover     7         7         7       7            7           <none>          13h

NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/csi-rbdplugin-metrics   ClusterIP   10.254.4.189   <none>        8080/TCP,8081/TCP   8m26s

```

**Comment by Madhu-1** [comment]
CSI Driver object which is added in https://github.com/rook/rook/pull/4172 needs to be removed when we are deleting CSI resources
