### ISSUE TITLE
Rook build needs a stable yq tool

### ISSUE THREAD

**Issue by travisn** [rook/rook#4241]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Today the Rook CI became broken across all builds when the yq tool changed its install requirements.

The failure is in the `generate-rook-csv.sh` script. 
```
cluster/olm/ceph/generate-rook-csv.sh: line 117: /home/rook/go/src/github.com/rook/rook/.cache/tools/linux_amd64/yq.v2: No such file or directory
```

For example: https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-3495/90/pipeline/

The related change in the yq repo can be seen [here](https://github.com/mikefarah/yq/commit/8020d4253bfb193edb37b7acfceff3a4a6e525b8).

**Expected behavior:**
Rook needs a stable CI and should be pinned to a version of the tools instead of being at the mercy of the latest changes.

**How to reproduce it (minimal and precise):**

Look at the Rook builds today

**Comment by egafford** [comment]
Further examination of yq confirms that we really do need to change out for another tool. It depends on companies as disparate as NYT and Uber, and a host of private repos with unknown maintenance, stability, and dependency management. It's handy, but it's not just following an enterprise dependency or release model.

Sadly, I don't see a fantastic pre-packaged alternative. This is one: https://github.com/kislyuk/yq
It has some serious drawbacks, though: it's in Python and it is also under very active development. On the upside, though, its dependency footprint is enormously more sane. It also has a much more modest mode of operation: it translates YAML and then hands off to jq to perform the actual transformations.

Alternatively, we can do the same thing ourselves. https://godoc.org/gopkg.in/yaml.v2 has a good pedigree and a sane dependency model, json support is built in, and jq installation is safe enough. It'd take a bit more wrangling than we might like, but it'd be Go ecosystem plus one ubiquitous package. From what I've seen while wrestling with the build trying to get a quick fix in, this is probably our best bet by my lights (though naturally I'd love to find out that we can do still better).

(We could also reimplement this logic. Well out of scope of the project; listed for completeness. Still, it's an option if none of the above are viable.)
