### ISSUE TITLE
OSD is keep getting crashing after deleting/adding back a Kubernetes node

### ISSUE THREAD

**Issue by zedtux** [rook/rook#4246]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Given a healthy kubernetes cluster, with a healthy Ceph cluster, I had to delete/re-install the OS/re-add the node as a Kubernetes worker, and all Rook/Ceph pods are coming back well, exception the OSD one.

I found the exact same logs out that #4215 but that issue is in another context.

**Expected behavior:**
Rook/Ceph to redeploy correctly the osd pod and get back on a healthy cluster.

**How to reproduce it (minimal and precise):**
1. Get a healthy Kubernetes and Ceph cluster
2. Shutdown and re-install the node's OS
3. Re-install the Kubernetes worker and join the cluster

**File(s) to submit**:

* Crashing pod(s) logs, if necessary

```
debug 2019-11-04 14:44:53.655 7f921f1a3dc0  0 set uid:gid to 167:167 (ceph:ceph)
debug 2019-11-04 14:44:53.655 7f921f1a3dc0  0 ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable), process ceph-osd, pid 6227
debug 2019-11-04 14:44:53.655 7f921f1a3dc0  0 pidfile_write: ignore empty --pid-file
debug 2019-11-04 14:44:53.691 7f921f1a3dc0 -1 missing 'type' file and unable to infer osd type
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian Stretch
* Kernel (e.g. `uname -a`):
```
Linux dev-k8s-worker-1 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux
```
* Rook version (use `rook version` inside of a Rook Pod):
```
rook version
rook: v1.1.0-beta.0.312.gb7d8338
go: go1.11
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
ceph -v
ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
```
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
HEALTH_WARN 1 osds down; 1 host (1 osds) down; Reduced data availability: 128 pgs inactive; Degraded data redundancy: 2308/4616 objects degraded (50.000%), 128 pgs degraded, 128 pgs undersized
```

**Comment by AXington** [comment]
I had to delete the deployment, then use the ceph toolbox to manually remove it, and delete the data from /var/lib/rook on the node. I found this https://gist.github.com/cheethoe/49d9c1d0003e44423e54a060e0b3fbf1 but this is really manual and would love to see this be automated in the future

**Comment by stephan2012** [comment]
I'm facing similar similar issues after a node failure test in a test cluster:

1. Killed storage node (Kubernetes worker node) VM
2. Deleted node from Kubernetes (`kubectl delete node`)
3. Re-created VM from snapshot and joined into the Kubernetes cluster (kubeadm).
    At this point, the block device used for Ceph was completely blank. Also, `/var/lib/rook` did not even exist on the node.
4. Rook Ceph Operator did nothing, OSD deployment keeps on crashing
5. After restarting the operator, it created a new OSD but does not remove the no longer existing one.

Current situation:

```
rook-ceph-osd-0-5f7677d564-zsfhk                0/1     CrashLoopBackOff   49         17h     172.30.197.9      n0205    <none>           <none>
rook-ceph-osd-1-7c84f56756-wlcnt                1/1     Running            0          19h     172.30.236.46     n0206    <none>           <none>
rook-ceph-osd-2-84748b68c6-wwzxr                1/1     Running            0          13h     172.30.7.149      n0207    <none>           <none>
rook-ceph-osd-3-65569f5f46-vw6tj                1/1     Running            0          13h     172.30.138.25     n0204    <none>           <none>
rook-ceph-osd-4-7667f59f9-b99wd                 0/1     Pending            0          13h     <none>            <none>   <none>           <none>
rook-ceph-osd-4-7667f59f9-ncfk7                 0/1     Evicted            0          17h     <none>            n0205    <none>           <none>
```

Ceph overall status:

```
[root@rook-ceph-tools-5b56c5b47c-8vgff /]# ceph status
  cluster:
    id:     2d57c69b-01d0-4783-b0d4-fbd5c7061fa9
    health: HEALTH_WARN
            1 pools have too few placement groups
            too few PGs per OSD (16 < min 30)
 
  services:
    mon: 3 daemons, quorum f,h,k (age 9h)
    mgr: a(active, since 13h)
    mds: cephfs:1 {0=cephfs-b=up:active} 1 up:standby-replay
    osd: 5 osds: 3 up (since 13h), 3 in (since 13h)
 
  data:
    pools:   3 pools, 24 pgs
    objects: 2.07k objects, 7.7 GiB
    usage:   18 GiB used, 54 GiB / 72 GiB avail
    pgs:     24 active+clean
 
  io:
    client:   1.2 KiB/s rd, 2.7 KiB/s wr, 2 op/s rd, 0 op/s wr
```

Ceph OSD status:

```
[root@rook-ceph-tools-5b56c5b47c-8vgff /]# ceph osd status
+----+-------+-------+-------+--------+---------+--------+---------+----------------+
| id |  host |  used | avail | wr ops | wr data | rd ops | rd data |     state      |
+----+-------+-------+-------+--------+---------+--------+---------+----------------+
| 0  |       |    0  |    0  |    0   |     0   |    0   |     0   | autoout,exists |
| 1  | n0206 | 6812M | 17.3G |    0   |     0   |    1   |    16   |   exists,up    |
| 2  | n0207 | 6866M | 17.2G |    0   |  9011   |    1   |    90   |   exists,up    |
| 3  | n0204 | 5221M | 18.9G |    0   |   132k  |    0   |     0   |   exists,up    |
| 4  | n0205 |    0  |    0  |    0   |     0   |    0   |     0   | autoout,exists |
+----+-------+-------+-------+--------+---------+--------+---------+----------------+
```

Device layout:

```
[root@rook-ceph-tools-5b56c5b47c-8vgff /]# ceph osd tree
ID  CLASS WEIGHT  TYPE NAME          STATUS REWEIGHT PRI-AFF 
 -1       0.11696 root default                               
 -4       0.07018     zone dc1                               
-11       0.02339         host n0204                         
  3   ssd 0.02339             osd.3      up  1.00000 1.00000 
 -3       0.04678         host n0205                         
  0   ssd 0.02339             osd.0    down        0 1.00000 
  4   ssd 0.02339             osd.4    down        0 1.00000 
 -8       0.04678     zone dc2                               
-13       0.02339         host n0206                         
  1   ssd 0.02339             osd.1      up  1.00000 1.00000 
 -7       0.02339         host n0207                         
  2   ssd 0.02339             osd.2      up  1.00000 1.00000 
```

Looks the operator does not really action on the deleted node. 

Operator version is 1.1.7, cluster never saw another version.

**Comment by Place1** [comment]
I've run into a similar problem where the operator keeps trying to deploy `mon-c` to the node i've removed from the cluster. I can see that there's a `rook-ceph-mon-endpoints` configmap that still contains the hostname/node-name of the node i removed from the cluster. The operator doesn't seem to update any state after a kubernetes cluster admin runs a `kubectl delete node <name>`.

**Comment by zedtux** [comment]
We decided to get ride of Rook so I'm no more following up this issue.

**Comment by r3dsm0k3** [comment]
I have this issue as well. In my case, the OSDs are in the Pending state. 

```
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  38m (x23 over 48m)    default-scheduler  0/5 nodes are available: 1 node(s) were unschedulable, 4 node(s) didn't match node selector.
  Warning  FailedScheduling  3m40s (x42 over 36m)  default-scheduler  0/4 nodes are available: 4 node(s) didn't match node selector.
```

**Comment by galexrt** [comment]
The operator will not do any desctructive action to OSDs, unless `removeOSDsIfOutAndSafeToRemove: true` is set.

Mons are failovered only if enough other nodes are available, e.g., if you have 3 nodes and removed the third node the operator will see the need for monfailover but not do anything due to not enough nodes being available.
A mon failover (new mon) must happen because an existing mon can't really join with an "empty data dir".

**Comment by KeithTt** [comment]
> The operator will not do any desctructive action to OSDs, unless `removeOSDsIfOutAndSafeToRemove: true` is set.
> 
> Mons are failovered only if enough other nodes are available, e.g., if you have 3 nodes and removed the third node the operator will see the need for monfailover but not do anything due to not enough nodes being available. A mon failover (new mon) must happen because an existing mon can't really join with an "empty data dir".

We run into the same problem,  there is a node crash down with disk issue, and we delete it from the cluster, then add it after repairation.

Here is my error message:
```text
WARNING: will not setuid/gid: /var/lib/rook/osd2 owned by 0:0 and not requested 167:167
debug 2021-10-21 07:10:13.512 7f6a98d7fa80  0 set uid:gid to 0:0 (:)
debug 2021-10-21 07:10:13.512 7f6a98d7fa80  0 ceph version 14.2.7 (3d58626ebeec02d8385a4cefb92c6cbc3a45bfe8) nautilus (stable), process ceph-osd, pid 40307
debug 2021-10-21 07:10:13.512 7f6a98d7fa80  0 pidfile_write: ignore empty --pid-file
debug 2021-10-21 07:10:13.538 7f6a98d7fa80 -1 missing 'type' file and unable to infer osd type
```

Maybe, setuid/git to 167:167 will solve this problem?
