### ISSUE TITLE
Document upgrade procedure for CSI

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#4248]
**Is this a bug report or feature request?**
* Bug Report
CSI nodeplugins, specifically when using `cephfs FUSE`  or `rbd-nbd` as the mounters, when upgraded, will cause existing mounts to become stale/not-reachable (usually connection timeout errors). This is due to losing the mount processes running within the CSI nodeplugin pods.

**Deviation from expected behavior:**

**Expected behavior:**
After Upgrade the pods which are using the PVC should be able  to  read/write without any issue

**How to reproduce it (minimal and precise):**

* Deploy Rook+CSI driver
* Update CSI  Driver version during rook upgrade

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/issues/703

**Comment by Madhu-1** [comment]
cc @travisn

**Comment by travisn** [comment]
@Madhu-1 Can we get documentation into Rook for this now? We should be clear on this since it's a severe issue for upgrades.

- On the ceph-filesystem.md page towards the top:
   - Users should be warned about using CephFS volumes with FUSE or rbd-nbd 
   - Users should know how to detect if they can use the kernel driver or if they will hit this issue
- The upgrade guide should warn that they have to restart the client pods if this scenario

**Comment by Madhu-1** [comment]
@travisn just now noticed you have self-assigned this one, as I have not completed by testing related to node draining, please feel free to close my PR

**Comment by travisn** [comment]
@Madhu-1 Sounds good I hadn't started on it, so will look at yours. I may just push changes to your PR instead of waiting over the weekend, thanks.
