### ISSUE TITLE
improve kubernetes readme sections for existing clusters

### ISSUE THREAD

**Issue by jbw976** [rook/rook#425]
There are likely a lot of Google Container Engine (GKE) users that have existing kubernetes clusters and want to try out Rook on them.  We should look into adding a readme section for with any necessary steps to get Rook running in GKE.

https://cloud.google.com/container-engine/

**Comment by jbw976** [comment]
The default node image ("Container-Optimized OS or just "gci") for Google Container Engine (GKE) does not support RBD nor CephFS, so it doesn't make a lot of sense to create a readme section for users of GKE: https://cloud.google.com/container-engine/docs/node-image-migration  

The intent of this ticket was to write a Rook readme section for existing Kubernetes users to get a big bang for buck in terms of large user base.  Perhaps we should still consider instructions for GCE or EC2, but I'm not sure how many Kubernetes users are on those platforms vs all the other options: https://kubernetes.io/docs/getting-started-guides/

It is a bit concerning that RBD and CephFS do not work in GKE, but I'm not sure what exactly we could do about it yet.  Perhaps we can look into what it takes to use other node images in GKE, but it's not clear yet if lack of RBD support is inherent to GKE or simply a restriction of their default node image "gci".

**Comment by jbw976** [comment]
While RBD make not work in GKE, it would still be nice to get some documentation to help existing users of other popular k8s platforms, such as Google Compute Engine and Amazon EC2.  Knowing the user breakdown between the platforms would be useful to help prioritize.

**Comment by josephjacks** [comment]
@jbw976 re: GKE support, have you looked at https://github.com/ceph/ceph-docker/tree/master/examples/kubernetes ?

**Comment by jbw976** [comment]
@josephjacks I had not read that yet, but thanks for the pointer!

@bzub suggested on gitter a few steps that could help make the `rbd` tool available in environments where `kubelet` is being invoked directly (instead of in a container).  When `kubelet` is run directly on the host, there's no need to add access to `modprobe` and `lib/modules`, but it does need `rbd` since the RBD volume plugin shells out to it.

Adding @bzub instructions here for reference (should be incorporated into the readme sometime):
```
sudo mkdir /opt/bin
cd /opt/bin
sudo wget https://raw.githubusercontent.com/ceph/ceph-docker/master/examples/kubernetes-coreos/rbd
sudo chmod +x /opt/bin/rbd
then to try it out
sudo /opt/bin/rbd
```
> then restart kubelet and I think you should be good

**Comment by luxas** [comment]
I think we should focus on integrating rook with kubeadm (https://kubernetes.io/docs/getting-started-guides/kubeadm/), I expect kubeadm to be the base building block for most kubernetes deployments in the future (http://blog.kubernetes.io/2017/01/stronger-foundation-for-creating-and-managing-kubernetes-clusters.html)

Bare-metal is the perfect usage for rook IMO, of course we should try to solve the GKE issues as well, but they have the GCE Persistent Disk feature that works OOTB already, something we really miss on bare metal.

**Comment by bassam** [comment]
@luxas good idea -- moving to #453. we'll put that on the agenda for SIG-lifecycle soon. We would love to get that in for 1.7

**Comment by jbw976** [comment]
#464 I believe will satisfy the original intent of this ticket, to make the experience smoother for users of existing kubernetes clusters.
