### ISSUE TITLE
`ceph-volume lvm list` doesn't work correctly inside ceph toolbox pod

### ISSUE THREAD

**Issue by xenolinux** [rook/rook#4250]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** 
`ceph-volume lvm list` doesn't work correctly in ceph toolbox pod

**Expected behavior:**
`ceph-volume lvm list` should work correctly in Rook Ceph toolbox pod. It should show all devices and logical volumes found in the system should be displayed.

**How to reproduce it (minimal and precise):**
Install Rook Ceph toolbox in rook cluster, run `ceph-volume lvm list` inside the toolbox pod.

**Environment**:
* OS (e.g. from /etc/os-release): fedora 29
* Kernel (e.g. `uname -a`): 4.18.16-300.fc29.x86_64 
* Cloud provider or hardware configuration: aws
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.1.0-beta.0.391.g1f788cf
go: go1.11
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+7bd2e5b", GitCommit:"7bd2e5b", GitTreeState:"clean", BuildDate:"2019-05-19T23:52:43Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift

**Comment by xenolinux** [comment]
The yaml file used to install Ceph toolbox : https://gist.github.com/xenolinux/c7c745647cbc11a8ac7bf90e5ce5ed09

**Comment by leseb** [comment]
What's your error?

`ceph-volume lvm list` is not a command you should run from the toolbox unless the toolbox is running on the host you are looking at listing OSDs.

I'd suggest, you exec into a running OSD pod and run the command.

**Comment by xenolinux** [comment]
@leseb yes. In OSD pods the command runs well. I think we can close this issue.
