### ISSUE TITLE
NFS server memory leak

### ISSUE THREAD

**Issue by graham-web** [rook/rook#4259]
**Is this a bug report or feature request?**
* Bug Report

**Bug Report**

After using a Rook-provisioned NFS server for a while, we have observed the memory usage growing very large - over 4GB in one case.

This is not the nfs-ganesha server itself, but the `rook` binary in the same container.

**How to reproduce it (minimal and precise):**

1. Deploy nfs operator and an NFSServer.
2. Create a workload with persistent storage using the NFS server.
3. Write a bunch of files into the share

e.g in workload container: 
```
cd /mounted/nfs/path
for i in {1..1000}; do dd if=/dev/zero of=test$i bs=20k count=1; done
```

Running `top` in the NFS server container at the same time, observe the RESident memory of the `rook` process increases - around 35MB each time here.

**Environment**:
* rook: v1.1.4
* Linux 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u1~bpo9+1 (2019-09-30) x86_64 x86_64 x86_64 GNU/Linux
* DigitalOcean Kubernetes Service

**Comment by galexrt** [comment]
Ping @rohan47

**Comment by chadmayfield** [comment]
We are seeing the same thing on rook-nfs v1.2.2.  Node running NFS server is using over 14G and running for about a week.

`top - 18:02:04 up 6 days, 20:33,  4 users,  load average: 3.27, 2.88, 1.75
Tasks: 463 total,   1 running, 462 sleeping,   0 stopped,   0 zombie
%Cpu0  :  4.2 us,  2.1 sy,  0.0 ni, 93.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  4.1 us,  4.1 sy,  0.0 ni, 91.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  4.2 us,  2.1 sy,  0.0 ni, 91.7 id,  0.0 wa,  0.0 hi,  2.1 si,  0.0 st
%Cpu3  :  2.1 us,  2.1 sy,  0.0 ni, 95.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :  4.2 us,  4.2 sy,  0.0 ni, 91.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :  4.2 us,  2.1 sy,  0.0 ni, 91.7 id,  0.0 wa,  0.0 hi,  2.1 si,  0.0 st
%Cpu6  :  2.1 us,  0.0 sy,  0.0 ni, 97.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :  4.1 us,  2.0 sy,  0.0 ni, 91.8 id,  0.0 wa,  0.0 hi,  2.0 si,  0.0 st
MiB Mem :  32003.7 total,   3507.5 free,  19070.1 used,   9426.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  12961.3 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                                                                  
16973 root      20   0   33.2g  14.1g  26244 S   0.0  45.0   5:57.65 /usr/local/bin/rook nfs server --ganeshaConfigPath=/nfs-ganesha/config/rook-nfs  `

**Comment by graham-web** [comment]
@chadmayfield Thanks for saving me the effort of testing a newer version - we’ve been holding off deployment of Rook NFS because of the issue.

I wondered if it may have something to do with the verbose logging the server outputs which the Rook binary tails, but not dug far enough to [dis]prove this.

**Comment by chadmayfield** [comment]
> Thanks for saving me the effort of testing a newer version - we’ve been holding off deployment of Rook NFS because of the issue.

@graham-web, yeah no problem. Same here hopefully we can get some traction on this issue.  We'd really like to use rook, but a possible memory leak this bad is going to force us to reevaluate that.

> I wondered if it may have something to do with the verbose logging the server outputs which the Rook binary tails, but not dug far enough to [dis]prove this.

Could be, based on the [startup options](https://github.com/rook/rook/blob/release-1.2/pkg/operator/nfs/server.go#L28) it looks like NFS is starting up in DEBUG, however I can't see anything actually being logged in the pod, nothing on `/dev/stdout` or any logs.

**Comment by jasonclinton** [comment]
We've seen the same issue. It grows until K8S eventually kills the Rook NFS pods.

<img width="817" alt="Screen Shot 2020-02-13 at 1 21 51 PM" src="https://user-images.githubusercontent.com/28311740/74475241-46381c80-4e64-11ea-9dbc-659cc39bc4ae.png">
pods. 

<img width="1793" alt="Screen Shot 2020-02-13 at 1 19 05 PM" src="https://user-images.githubusercontent.com/28311740/74474834-8945c000-4e63-11ea-93b3-47e2008d73a6.png">

**Comment by zeidlermicha** [comment]
Same here! Any news on this?

**Comment by prksu** [comment]
Just reproduced this issue as @chadmayfield said, it looks like because of the use of `NIV_DEBUG` log level when executing `ganesha.nfsd` and might be caused overflow when calling `exec.(*Cmd).CombinedOutput()` function.

![profile001](https://user-images.githubusercontent.com/43454825/82954630-5620da00-9fd7-11ea-876a-f7e8054568bb.png)

two things that might fix this issue are to remove `NIV_DEBUG` (ganeshaOptions) from this line https://github.com/rook/rook/blob/e9348070a7db307dfe8e5e3cab77bc0ca468c6a5/pkg/operator/nfs/server.go#L69-L72
or directly calling `cmd.Run()` instead of calling `exec.(*Cmd).CombinedOutput()` function.
i've tried both two things above and this issue seems doesn't appear. rook binary doesn't increase memory usage.

this is heap pprof after workload container write some file in nfs volume
[rook-nfs-heap-after-write.pb.gz](https://github.com/rook/rook/files/4685328/rook-nfs-heap-after-write.pb.gz)
