### ISSUE TITLE
monitoring: add support for ceph_exporter

### ISSUE THREAD

**Issue by jason-riddle** [rook/rook#426]
Are there any prometheus rules or grafana dashboards to help monitor this setup?

**Comment by bassam** [comment]
Not yet. It's on out short term roadmap. Please help us know which monitoring areas you care about most.

Note there is some basic health checking today through our rook cli

**Comment by hunter** [comment]
Any sense in exporting the ceph performance data via something like https://github.com/digitalocean/ceph_exporter? In theory ceph_exporter could be run outside of rook but would be useful to have some built in (simplified since the ceph metrics are confusing)

**Comment by bassam** [comment]
Agree we would likely fold this into the operator and/or API server. +1 for simplification
