### ISSUE TITLE
PVC status remains pending with PVC-based OSD.

### ISSUE THREAD

**Issue by tzkoba** [rook/rook#4271]
**Expected behavior:**
PVC(cluster/examples/kubernetes/ceph/csi/rbd/pvc.yaml) status will turn to Bound.
Ceph is built as PVC-based cluster.

**Deviation from expected behavior:**
PVC status remains pending with PVC-based OSD.
And I confirmed unexpected logs in csi-rbdplugin-provisioner.

**How to reproduce it (minimal and precise):**
1. kubectl apply -f common.yaml
2. kubectl apply -f operator.yaml
3. kubectl apply -f cluster-on-pvc.yaml
4. confirmed 3 MONs and 3 OSDs were running normally.
5. kubectl apply -f cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
6. kubectl apply -f cluster/examples/kubernetes/ceph/csi/rbd/pvc.yaml

```
$ kubectl get pvc -o wide
NAME      STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE    VOLUMEMODE
rbd-pvc   Pending                                      rook-ceph-block   177m   Filesystem
```

I got logs below from csi-rbdplugin-provisioner.
They said `an operation with the given Volume ID pvc-6c43ef8b-54f1-4673-8b69-484ddaae2bba already exists`.
But I don't understand what already existed.

```
I1106 07:44:30.052258 1 controller.go:1196] provision "default/rbd-pvc" class "rook-ceph-block": started
I1106 07:44:30.055114 1 controller.go:471] CreateVolumeRequest {Name:pvc-6c43ef8b-54f1-4673-8b69-484ddaae2bba CapacityRange:required_bytes:1073741824 VolumeCapabilities:[mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[clusterID:rook-ceph csi.storage.k8s.io/fstype:ext4 csi.storage.k8s.io/node-stage-secret-name:rook-csi-rbd-node csi.storage.k8s.io/node-stage-secret-namespace:rook-ceph csi.storage.k8s.io/provisioner-secret-name:rook-csi-rbd-provisioner csi.storage.k8s.io/provisioner-secret-namespace:rook-ceph imageFeatures:layering imageFormat:2 pool:replicapool] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1106 07:44:30.055315 1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"rbd-pvc", UID:"6c43ef8b-54f1-4673-8b69-484ddaae2bba", APIVersion:"v1", ResourceVersion:"269028", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/rbd-pvc"
I1106 07:44:30.057587 1 connection.go:180] GRPC call: /csi.v1.Controller/CreateVolume
I1106 07:44:30.057607 1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-6c43ef8b-54f1-4673-8b69-484ddaae2bba","parameters":{"clusterID":"rook-ceph","imageFeatures":"layering","imageFormat":"2","pool":"replicapool"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
I1106 07:44:30.065274 1 connection.go:183] GRPC response: {}
I1106 07:44:30.065770 1 connection.go:184] GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-6c43ef8b-54f1-4673-8b69-484ddaae2bba already exists
I1106 07:44:30.065810 1 controller.go:979] Final error received, removing PVC 6c43ef8b-54f1-4673-8b69-484ddaae2bba from claims in progress
W1106 07:44:30.065819 1 controller.go:886] Retrying syncing claim "6c43ef8b-54f1-4673-8b69-484ddaae2bba", failure 8
E1106 07:44:30.065839 1 controller.go:908] error syncing claim "6c43ef8b-54f1-4673-8b69-484ddaae2bba": failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-6c43ef8b-54f1-4673-8b69-484ddaae2bba already exists
I1106 07:44:30.066149 1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"rbd-pvc", UID:"6c43ef8b-54f1-4673-8b69-484ddaae2bba", APIVersion:"v1", ResourceVersion:"269028", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-6c43ef8b-54f1-4673-8b69-484ddaae2bba already exists
I1106 07:44:33.999762 1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-rbd-csi-ceph-com
```

**Environment**:
* OS (e.g. from /etc/os-release): Cent OS 7
* Kernel (e.g. `uname -a`): 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):  v1.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
* Kubernetes version (use `kubectl version`): 1.15.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN Reduced data availability: 8 pgs inactive; Degraded data redundancy: 8 pgs undersized; too few PGs per OSD (2 < min 30)

**Comment by tzkoba** [comment]
Here is Ceph Status.
I wonder Ceph cluster is broken.

```
# ceph status
  cluster:
    id:     015efc57-555d-4d08-a4b4-87b922ca44e5
    health: HEALTH_WARN
            Reduced data availability: 8 pgs inactive
            Degraded data redundancy: 8 pgs undersized
            too few PGs per OSD (2 < min 30)
 
  services:
    mon: 3 daemons, quorum a,b,c (age 3h)
    mgr: a(active, since 3h)
    osd: 3 osds: 3 up (since 3h), 3 in (since 3h)
 
  data:
    pools:   1 pools, 8 pgs
    objects: 0 objects, 0 B
    usage:   3.0 GiB used, 24 GiB / 27 GiB avail
    pgs:     100.000% pgs not active
             8 undersized+peered
```

**Comment by kevincoakley** [comment]
I would verify that the 3 PVCs that are used for the OSDs are not attached to the same k8s node. Running `ceph osd tree` will also show if the 3 OSDs are on the same node.

**Comment by tzkoba** [comment]
Thaks, and you are right. 
3 OSDs are in one node.
But is it wrong?
In a PVC-based cluster, I thought I could move osd to another node.
As a result, can there be multiple OSDs on one node?

**Comment by kevincoakley** [comment]
The pgs will stay undersized because Ceph cannot achieve 3 copy replication (the default) because all of the OSDs are in the same failure domain (node). If the one node with the 3 OSDs goes offline then all of your data will be inaccessible. You could set the size option for the pools to 1 or modify the CRUSH map so the failure domain is at the OSD level instead of the node level, but I don't recommend either. The real solution is to have the PVCs on different nodes. I couldn't find any documentation on how to specify which nodes the PVCs were bound to.

**Comment by satoru-takeuchi** [comment]
An additional explanation to Kevin's one.

Replacing preferredDuringSchedulingIgnoredDuringExecution with requiredDuringSchedulingIgnoredDuringExecution in cluster-on-pvc.yaml would help you. It enforces each OSD to the different nodes.

If your k8s cluster consists of just 1 node, the default setting doesn't work. You should remove `failureDomain` line from rbd/storageclass.yaml, or should change "replicated->size" to 1.
