### ISSUE TITLE
OSD not being created on a new node

### ISSUE THREAD

**Issue by foux** [rook/rook#4278]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
After adding a new node respecting storage settings, an OSD should be created on this node. It isn't, even the OSD discover pod isn't created (as referenced in [the docs](https://rook.io/docs/rook/v0.9/common-issues.html#osd-pods-are-not-created-on-my-devices)

**How to reproduce it (minimal and precise):**
Remove a node with an OSD so that the system is degraded. Add another node respecting the storage constraints.
Operator installed using helm chart

**File(s) to submit**:

* Cluster CR [cluster.yaml.zip](https://github.com/rook/rook/files/3820304/cluster.yaml.zip)
* Operator's logs [operatorlog.txt](https://github.com/rook/rook/files/3820313/operatorlog.txt)

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS : K8S cluster
* Kernel : 4.19.0-5
* Cloud provider or hardware configuration: baremetal K8S
* Rook version (use `rook version` inside of a Rook Pod): 1.1.0
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)`
* Kubernetes version (use `kubectl version`): 1.16.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): BareMetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN Degraded data redundancy: 587/1761 objects degraded (33.333%), 16 pgs degraded, 16 pgs undersized; mon c is low on available space; 1/3 mons down, quorum b,c`

**Comment by foux** [comment]
The issue really seems to be that the osd-prepare steps never gets done after the initial setup of the cluster. I'm using the helm operator with the default values

**Comment by travisn** [comment]
@foux The operator watches for events of nodes being added and will start and orchestration to create OSDs. However, there is a race condition that sometimes causes the event to be missed by the operator. The workaround is to restart the operator after adding the new node until we get this fixed.
