### ISSUE TITLE
Toolbox does not need to run privileged

### ISSUE THREAD

**Issue by travisn** [rook/rook#4297]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The toolbox doesn't have a need to run privileged. The toolbox should really only be used to execute `ceph` commands, rather than need to run privileged and access the host. 

**Expected behavior:**
The changes suggested would include:
- The [toolbox](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/toolbox.yaml) manifest can remove:
   -  `privileged: true`
   - `hostnetwork: true`
   -  All volume and mounts except `mon-endpoint-volume`
-  `direct-tools.md`: This help file does not follow recommended k8s approach for volumes. This really shouldn't be used anymore and we can remove this topic.

**How to reproduce it (minimal and precise):**

- Launch the toolbox pod
- See the mounts and privileged mode that aren't necessary

**Comment by leseb** [comment]
@rajatsingh25aug PTAL

**Comment by amiga23** [comment]
To toolbox needs to run privileged if you want to use rbd map, e.g. to manually repair a volume with fsck.

**Comment by travisn** [comment]
For those operations note that we still have the [direct mount example](https://github.com/rook/rook/blob/master/deploy/examples/direct-mount.yaml), which is just a modified toolbox that runs privileged.

**Comment by jansmets** [comment]
Can we please add the option to the helm chart to run the toolbox as privileged?

**Comment by travisn** [comment]
> Can we please add the option to the helm chart to run the toolbox as privileged?

@jansmets Please open a new issue that describes the need for a privileged toolbox. In the meantime, you might use the [direct-tools.yaml example](https://rook.io/docs/rook/latest/Troubleshooting/direct-tools/).
