### ISSUE TITLE
Ability to set device class on OSDs when on PVCs

### ISSUE THREAD

**Issue by travisn** [rook/rook#4298]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The device class property on an OSD is currently detected automatically when c-v initializes an OSD. The properties of the devices may not always be accurate, particularly when running in a cloud environment and/or backed by a PVC. For example, a `gp2` volume is detected as `ssd`, but may want to be treated as `hdd` when compared to provisioning an OSD with `io1`. 

In the storageClassDeviceSet, a new property might be:
`deviceClass: hdd | ssd`

**What is use case behind this feature:**
When pools are created, they can specify the desired `deviceClass` for the pool. If the device classes are not accurate, the performance for the pool will be impacted.

**Environment**:

**Comment by jdurgin** [comment]
Overriding the device class doesn't change the tunings - since it is user customizable, the osd determines ssd vs hdd by looking at /sys/block/$dev/queue/rotational. Instead of changing the device class, I'd suggest directly setting the osd background io configuration for gp2 devices, namely:

```
osd_recovery_sleep = 0.1
osd_snap_trim_sleep = 2
osd_delete_sleep = 2
```
