### ISSUE TITLE
No annotation propagation to CmdReporter job

### ISSUE THREAD

**Issue by redradrat** [rook/rook#4300]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Annotations are not propagated to the `CephCluster` owned job. In https://github.com/rook/rook/blob/0bb8000825055e45e6f58966ec1e47183391fa47/pkg/operator/k8sutil/cmdreporter/cmdreporter.go#L295-L299 I would expect annotations to be set or later enriched.

**Expected behavior:**
All of `CephCluster`s owned resources should be enriched with annotations from itself.

**How to reproduce it (minimal and precise):**
Create `CephCluster` with annotations, `kubectl get job <created detect-version job> -o yaml` doesn't contain annotation.

**File(s) to submit**:
-

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v1.1.6
* Kubernetes version (use `kubectl version`): v1.14.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): EKS

**Comment by aruniiird** [comment]
Taking a look into the issue...

**Comment by BlaineEXE** [comment]
What annotations do you feel are specifically missing?

**Comment by redradrat** [comment]
@BlaineEXE 
Yeah... you are right actually... Automatically propagating objectmeta to owned object should not be in scope for rook.

Basically the idea is to be able to add annotations to all pods created through rook... I get though that it might not really be rook's job.

https://github.com/rook/rook/blob/0bb8000825055e45e6f58966ec1e47183391fa47/pkg/operator/k8sutil/cmdreporter/cmdreporter.go#L301-L307

**Comment by BlaineEXE** [comment]
I understand the idea as a vague implementation, but in order for it to be considered for adding to Rook, we need to have a clear idea of how the feature would be used, what it would enable, and who would be using it. This helps us prioritize which features we can work on with the resources available.

**Comment by hmm01i** [comment]
Could this be related to the annotations being set in cluster.yaml? I just open a issue because annotations are not being set on mgr as requested in cluster.yaml. Thought I remember finding something in the code that was not propagating annotations when declaring cluster. Will see if i can find the line...
