### ISSUE TITLE
how to use ceph-volume properly ?

### ISSUE THREAD

**Issue by sokoow** [rook/rook#4306]
* Bug Report

**Deviation from expected behavior:**

ceph-volume is giving me this:

```
[root@node2 /]# ceph-volume lvm prepare --data /dev/vdb
Running command: /bin/ceph-authtool --gen-print-key
-->  NoOptionError: No option 'fsid' in section: 'global'
[root@node2 /]# ceph-volume lvm create --data /dev/vdb
Running command: /bin/ceph-authtool --gen-print-key
-->  NoOptionError: No option 'fsid' in section: 'global'
```
Also I'd expect for some step-by-step minimal readme on how to proceed if I want to create osds on VG/LVs.

**Expected behavior:**

I just expect that fsid label is finally there. I expected ceph-volume to work and give me OSDs

**How to reproduce it (minimal and precise):**
Take 3 nodes with one blank block volume on EC2, try to create osds 

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 18.04
* Kernel (e.g. `uname -a`): Linux node3 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: scaleway (shouldn't matter)
* Rook version (use `rook version` inside of a Rook Pod): 1.1.0
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)
* Kubernetes version (use `kubectl version`): 1.16
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): standalone
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN crush map has legacy tunables (require firefly, min is hammer)

**Comment by sokoow** [comment]
Seems like I got some progress, but still things are fuzzy:

```
# ceph status
  cluster:
    id:     d2a71c9c-a292-430f-8517-733640ad138f
    health: HEALTH_OK
 
  services:
    mon: 1 daemons, quorum a (age 4m)
    mgr: a(active, since 3m)
    osd: 0 osds: 0 up, 0 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     
 
[root@node3 /]# ceph-volume lvm prepare --data /dev/vdb --cluster-fsid d2a71c9c-a292-430f-8517-733640ad138f
Running command: /bin/ceph-authtool --gen-print-key
Running command: /bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 1c7c7460-62aa-40fb-81b2-d7cb5d5e3cc1
 stderr: [errno 95] error connecting to the cluster
-->  RuntimeError: Unable to create a new OSD id
```

**Comment by travisn** [comment]
ceph-volume is not expected to be executed from the toolbox. It will be run by rook when creating the OSDs.

> Also I'd expect for some step-by-step minimal readme on how to proceed if I want to create osds on VG/LVs.

Step 1: Merge #4219 so this scenario would be supported :)

**Comment by sokoow** [comment]
Cool, thanks for explaining. 

So, does that mean that currently rook isn't able to work with lvm just yet ?

**Comment by travisn** [comment]
@sokoow That's correct, hopefully it's coming soon!

**Comment by sokoow** [comment]
cool, nothing to see here then
