### ISSUE TITLE
Explore a rook volume plugin

### ISSUE THREAD

**Issue by jbw976** [rook/rook#432]
The built-in RBD plugin has some limitations and also has a dependency on the `rbd` tool being installed locally.

We should explore if there's any improvements we can make with a `rook` volume plugin and if that effort would be worthwhile.   One advantage of a `rook` volume plugin would be the potential removal of the user having to look up monitor IP addresses and secrets themselves, the plugin could do that.

This could also take our goal of deep integration with Kubernetes even further.

**Comment by kokhang** [comment]
Another use for the plugin would be for rook volume not to depend on modprobe and ceph modules. One potential solution would be to use sysfs.

Also we could us the volume to further extend Ceph capabilities and features such as cloning, and backups as well as supporting File System and object store all in one plugin.

**Comment by bassam** [comment]
Also use of the user-mode drivers for RBD (through NBD). I'd also like to look at merging the RBD and CephFS support into a single plugin.

**Comment by jbw976** [comment]
Help me understand how `modprobe` wouldn't be needed.  Doesn't the RBD kernel module need to get loaded eventually regardless of if management is done through sysfs?

**Comment by luxas** [comment]
Is there any work-in-progress PR for this one can look at?

I suppose this will be a flex volume and not built into the kubernetes core, right?

**Comment by DanKerns** [comment]
The plan is to do a first-class plugin (not a flex volume) and submit a pull request to core.

**Comment by luxas** [comment]
I'm very sceptical to doing that... I think it's best to be out of core as long as it's just possible tbh

What would you want to do that a flex volume can't do?

**Comment by kokhang** [comment]
@luxas here is a WIP rook volume. https://github.com/kokhang/kubernetes/tree/rook-plugin. I still want to make some changes before i submit a PR. Specially removing the `rbd` and `ceph-tools` dependency that `rbd` plugin has. 

As for flex, flex plugin is currently not in a state where it can be usable by rook. Users leverage the dynamic provisioning feature from kubernetes to create/delete images from Rook on demand (using storageclass and PVCs). This feature is currently not supported in Flex. There is a proposal to improve flex and make it more feature-parity with what is in-tree volume plugins but this proposal was just finalized and approved recently. It would still take a while until flex (or CSI) to be stable and be useful for Rook. Here is the flex-update proposal. https://github.com/kubernetes/kubernetes/pull/33538.

**Comment by kokhang** [comment]
Closing this since we are creating an external volume provisioner instead. https://github.com/rook/rook/issues/538

**Comment by kokhang** [comment]
Reopen this for creating a Rook volume plugin to handle the attaching and mounting for Rook volumes.

# Rook Volume Plugin
## Background:
Currently, to provision Rook volumes in Kubernetes, we use a external provisioner detailed in #538. For attaching this volume, we leverage the RBD in-tree volume plugin. Although this works well, using the RBD plugin has the following limitation:

- It requires ceph-tools to be installed. The RBD plugin shells out to `rbd` command to perform all the volume operation (create, delete, mount, unmount). This creates a dependency on the `ceph-tools` package to be installed in all the Kubernetes hosts as well as hosts that run the Control-manager.
- Kernel Version depdendency. The RBD command depends on the Kernel RBD module. This development and improvement of this module is very slow. There is an user-level modules that has a lot more features.
- It is also hard to leverage other client for accessing the RBD volumes. If we wanted to use NBD, this would not be possible.

We have also explored using Flexvolume but, as its current state, it is very limited and very invasive. One would have to copy the Flexvolume plugin to all nodes and restart Kubelet.

We also looked at CSI but this is not ready. It is still a long ways until we can start using it. It is now at the design stage for the API.

The goal is of this proposal is to create a Rook volume plugin that will live Kubernetes. This plugin will handle the attaching and detaching of the volumes. The volumes will still be provisioned using the external provisioner. 

During an attach/detach request from Kubernetes. the Rook plugin will collect all requirement information and delegate the request to the Rook-API to handle the request. The logic in the plugin will be minimal as it will only forward the request and data to the Rook-API. This will allow to have all the logic done by Rook, which will provide better way to scale functionality and development will not be tied down to a Kubernetes release.

## Design

The proposal consists of creating a Kubernetes volume plugin for Rook. The plugin will only be in charge of attaching and detaching volumes from the node. The attach and detach request from Kubernetes will be forwarded to the Rook-api and the Rook API will handle it by deploying a utility container on the node where the attaching and detaching is to be done. The container will have the necessary tooling, binaries and dependencies to perform the request. So no additional installation is needed to be done on the K8S nodes.

The following is a high level steps of a Attach request.
1- The Rook plugin receives a attach request from K8S.
2- The Rook plugin uses the Rook-client binding to delegate the attach request to the Rook-API
3- The rook plugin polls the rook-api until the volume is attached
4 - The Rook-API validates the request and creates an utility container on the node where the attach request is to be performed.
5- The utility container performs the attachment. The container can be short lived or be a long running agent.
6- The device is attached. The plugin will stop polling (from step #3). The plugin will then format and mount the device

**Comment by bassam** [comment]
How does the plugin know which device was actually attached for example /dev/rbd0?

**Comment by jbw976** [comment]
For #2, I'm wondering if just doing simple raw HTTP calls to the rook-api server (instead of using rook-client wrapper) would be better so that we can avoid introducing a dependency on rook-client wrapper into the Kubernetes tree.

@bassam I assume that since step 6 says the plug-in is performing the mounting (it will be running on the same node that the attach request is for, right?), It can check to see which device it was mapped to, either by udev or probing the `/sys/bus/rbd/devices/` tree similar to how the rook client tool does it.

**Comment by bassam** [comment]
> For #2, I'm wondering if just doing simple raw HTTP calls to the rook-api server (instead of using rook-client wrapper) would be better so that we can avoid introducing a dependency on rook-client wrapper into the Kubernetes tree.

that makes a lot of sense.

> It can check to see which device it was mapped to, either by udev or probing the /sys/bus/rbd/devices/ tree similar to how the rook client tool does it.

how would it know the identity of the device. Consider the case when multiple attaches are happening at the same time.

**Comment by jbw976** [comment]
> how would it know the identity of the device. Consider the case when multiple attaches are happening at the same time.
Multiple attaches to the same single image? i.e. is `ReadWriteMany` going to be supported with this effort?

Here's how `rook` tool does it, it matches on both the image name and pool name from within the `/sys/bus/rbd/devices` tree to find the correct one.  But that wouldn't work if the same image can be attached/mapped multiple times to multiple devices (`ReadWriteMany`):
https://github.com/rook/rook/blob/master/cmd/rook/block/map.go#L222

**Comment by bassam** [comment]
Update design based on discussions today.

## Design

- We will be creating a new in-tree volume plugin for Rook. 
- We will support both block and filesystem mounts using different presentations including rbd, cephfs, nbd and iscsi.
- We will support direct access to the storage cluster using existing kernel modules -- rbd.ko direct to ceph cluster and cephfs.ko direct to ceph cluster.
- We will also optionally support indirect access to the storage cluster by running a "storage proxy" pod on the host node mounting the volume. 
- Indirect mode will support the following use cases: 1) the appropriate kernel modules are not available or are incompatible, 2) the "storage proxy" is a faster path to the storage cluster (such as the case with SPDK/DPDK/RDMA kernel bypass 
- The Rook plugin is dumb and will rely on the Rook Operator for policy. This helps us improve our code without relying K8S release cycle.

## Details
- The rook plugin will implement create, delete, attach, detach, mount and unmount.
- We will no longer use the [external provisioner](https://github.com/rook/rook/blob/master/pkg/operator/provisioner.go) that was part of the 0.4 release -- that code and the associated packages will be removed.
- Create and Delete will work as they did with the external provisioner except will be invoked directly by the PVC controller from the controller-manager. 
- Attach and Detach will also be called by the controller-manager and rely on the [attach-detach-controller](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/attach_detach_controller.go)
- Attach will create an instance of a new TPR called `VolumeAttach` which contains the VolumeId, DevicePath, and NodeId. Detach will delete the `VolumeAttach` instance. 
- The Rook Operator will watch for `VolumeAttach` instances and perform what is needed to attach the volume on the node -- it will do this by launching a pod to the actual volume attach for direct access, and can launch the "storage proxy" for indirect access mode. Upon deleting the `VolumeAttach` TPR instance the Rook Operator can remove the attach on the device as needed.
- Mount and Unmount will be called by the kubelet
- The `VolumeAttach` TPR will also include all the information needed by the Rook plugin to perform the mount including whether to format/mount a file system (for block mounts) and other information needed to mount the filesystems like cephfs.
- The plugin only deals with the Kubernetes API and relies on the Rook operator to perform the actual work needed. It does not call the Rook API at all just creates and deletes TPR instances.
- Also all tools needed to attach/detach will be done inside containers relieving the Cluster operator from installing anything on the host. The only requirement is that a support block/fs kernel module be available (rbd,nbd,cephfs,fuse,iscsi, etc.).

**Comment by kokhang** [comment]
PR submitted to https://github.com/kubernetes/kubernetes/pull/46843. Most of the files are generated and docs. If you want to review, look at the files under pkg/volumes/rook and pkg/api/types.go.

**Comment by travisn** [comment]
Moving to 0.6 to track with K8s1.8
