### ISSUE TITLE
 "exec: \"ceph-crash\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by benwbooth** [rook/rook#4324]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

After installing rook/ceph, all the crashcollector pods are failing due to the following error:

```
Error: failed to start container "ceph-crash": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"ceph-crash\": executable file not found in $PATH": unknown
```

**Expected behavior:**

Pods don't crash
[rook-ceph.yaml.txt](https://github.com/rook/rook/files/3847979/rook-ceph.yaml.txt)

**How to reproduce it (minimal and precise):**

cd cluster/examples/kubernetes/ceph
kubectl create -f operator.yaml
kubectl create -f rook-ceph.yaml

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): 4.15.0-50-generic
* Cloud provider or hardware configuration: on-premises
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.1.0-beta.0.458.gb24a1e5
go: go1.11
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
* Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher 2.3
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN clock skew detected on mon.e, mon.d

**Comment by leseb** [comment]
Your Ceph version is too old. You need at least Nautilus. ceph-crash will come with Rook 1.2, which I believe will drop support for Mimic. @travisn thoughts?

**Comment by BlaineEXE** [comment]
Closing as invalid

**Comment by benwbooth** [comment]
Figured it out. I had tried to install rook using the master branch instead of one of the tags. Thanks!
