### ISSUE TITLE
[cephobjectstore]change replicated.size then apply -f，nothing happened

### ISSUE THREAD

**Issue by tarjintor** [rook/rook#4341]
I use cephobjectstore,and at first,I only store 1 replicate.
Now I wish to replicated 3 times,but this doesn't work
But when I change CephBlockPool's replicated.size,then apply ,it works?

Is this a bug or cephobjectstore can't update replicated.size dynamic?

**Comment by travisn** [comment]
@tarjintor Agreed, this should be a supported scenario to change the replication size in the object store, similar to the pools. @rajatsingh25aug Could you take a look at this issue? When the object store CR is updated with a new replica size, the pools should be updated with the new size. We're probably just skipping all updates to the CR currently

**Comment by rajatsingh25aug** [comment]
sure @travisn  would love to look into it! 😇

**Comment by rajatsingh25aug** [comment]
@tarjintor please try now. It's fixed.
Thanks
