### ISSUE TITLE
Improve restarting time for mgr,mon,toolbox pods running in a k8's "NotReady" node

### ISSUE THREAD

**Issue by jmolmo** [rook/rook#4342]
**Feature Request**

If one node is NotReady for Kubernetes it takes up to 5 minutes till the Pod eviction starts causing the MGR Pod to be unavailable for this time causes metrics to be lost which may be important to see what the issue is for a failure.

(For more info on Kubernetes node down detection and pod eviction, see https://fatalfailure.wordpress.com/2016/06/10/improving-kubernetes-reliability-quicker-detection-of-a-node-down/)

This feature request comes from:
[Run two MGRs to have one in standby mode](https://github.com/rook/rook/issues/1796)
Where it was decided not to continue trying to have two mgr pods.

**What should the feature do:**
Reduce the time needed to have new mgr, mon, toolbox pods running again in other nodes when the node used by this pods is not available because any cause.
In this moment the time needed is more that 5 minutes, because Kubernetes automatically adds a toleration for `node.kubernetes.io/not-ready` with `tolerationSeconds=300`

See: 
[Taints and Tolerations](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/)

**What is use case behind this feature:**
Reduce the time needed to return to a healthy state when a mgr or a mon pod is not running because a k8 node lost.

**Environment**:
a k8 cluster with several worker nodes and a rook-ceph cluster deployed.

**Comment by mykaul** [comment]
Is it taking the MONs 5 minutes as well?

**Comment by jmolmo** [comment]
> Is it taking the MONs 5 minutes as well?

Yes, the k8's DefaultTolerationSeconds admission controller adds a toleration for node.kubernetes.io/unreachable with tolerationSeconds=300 unless the pod configuration provided by the user already has a toleration for node.kubernetes.io/unreachable.
With #4243 this has been cahnge to 5 seconds in mgr, mon and cephtools pods.

See:
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#taint-based-evictions
