### ISSUE TITLE
Operator crashing on concurrent map read and map write

### ISSUE THREAD

**Issue by benceszikora** [rook/rook#4350]
* Bug Report

**Deviation from expected behavior:**
The operator is crashing sometimes shortly after coming up, sometimes later. I have attached the logs with a trace.
[rook-crash.txt](https://github.com/rook/rook/files/3869424/rook-crash.txt)

**Expected behavior:**
The operator does not crash.

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.5
* Kernel (e.g. `uname -a`): `3.10.0-862.3.2.el7.x86_64`
* Cloud provider or hardware configuration: `on-prem`
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.1.7`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)`
* Kubernetes version (use `kubectl version`): `v1.16.2`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `vanilla kubernetes`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
[root@rook-ceph-tools /]# ceph health
HEALTH_WARN BlueFS spillover detected on 25 OSD(s)
```

**Comment by travisn** [comment]
@benceszikora Can you provide any more details on the repro such as how often you have seen it or if you can find a consistent repro? How much later after startup have you seen it? Minutes? Hours? Days?

**Comment by benceszikora** [comment]
@travisn I don't really have a way to reproduce this unfortunately. I happens sometimes instantly after startup, sometimes hours later. It has been running for 2 days now without crashing.

**Comment by travisn** [comment]
@rohantmp This appears related to the disruption budget controller starting in its own goroutine. Here are the two goroutines that hit the concurrent map issue:

```
goroutine 94 [running]:
runtime.throw(0x1d81764, 0x21)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0007c4ee0 sp=0xc0007c4eb0 pc=0x42c2f2
runtime.mapaccess2(0x1a8f100, 0xc00037a6f0, 0xc0007c4fb0, 0x20a1540, 0x1c20fc0)
	/usr/local/go/src/runtime/map.go:453 +0x223 fp=0xc0007c4f28 sp=0xc0007c4ee0 pc=0x40dac3
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc000330b60, 0x204f720, 0xc00012a480, 0x1d501db, 0x6, 0xc0007c5060, 0x1, 0x1, 0xc000d30c00)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:256 +0x115 fp=0xc0007c5000 sp=0xc0007c4f28 pc=0x6a7295
```

and
```
goroutine 190 [runnable]:
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0xc000330b60, 0x1d596f8, 0xc, 0x1d4da1d, 0x2, 0x190f9b1, 0x13, 0x204be20, 0xc00032f7c0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:213 +0x57e
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0xc000330b60, 0x1d596f8, 0xc, 0x1d4da1d, 0x2, 0xc0007d7b50, 0xc, 0xc)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:180 +0x25d
github.com/rook/rook/pkg/apis/ceph.rook.io/v1.addKnownTypes(0xc000330b60, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/pkg/apis/ceph.rook.io/v1/register.go:55 +0x340
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(0x32aaa60, 0xc000330b60, 0x2047980, 0xc0009d8ce0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/runtime/scheme_builder.go:29 +0x6d
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme-fm(0xc000330b60, 0xc000330b60, 0x1)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/api/core/v1/register.go:41 +0x34
github.com/rook/rook/pkg/operator/ceph/disruption/clusterdisruption.Add(0x2090ba0, 0xc00032e640, 0xc0009e4d80, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/disruption/clusterdisruption/add.go:44 +0x82
github.com/rook/rook/pkg/operator/ceph/disruption.AddToManager(0x2090ba0, 0xc00032e640, 0xc0009e4d80, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/disruption/register_controllers.go:57 +0x92
github.com/rook/rook/pkg/operator/ceph.(*Operator).startManager(0xc0009de960, 0xc000982000)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cr_manager.go:48 +0x26f
created by github.com/rook/rook/pkg/operator/ceph.(*Operator).Run
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/operator.go:146 +0x4e6
```

**Comment by rohantmp** [comment]
Just saw this. Checking.

**Comment by rohantmp** [comment]
@travisn How did you determine that `goroutine 190` hit the panic?

I only see it in `goroutine 94`. Investigating that.

**Comment by rohantmp** [comment]
Oh, I started `ctrl+f`ing random memory values in the panicing gorouting, and I see that the *runtime.Scheme `0xc000330b60` is listed in both goroutine's stacktraces as args to functions.

Is that how you did it?

**Comment by rohantmp** [comment]
One access to Scheme is from the operator's default clientset:

https://github.com/rook/rook/blob/v1.1.7/pkg/operator/ceph/agent/agent.go#L265 using `context.Kubeconfig`

That clientset is generated here: 
https://github.com/rook/rook/blob/v1.1.7/cmd/rook/rook/rook.go#L150

The other is from the cr_manager adding the ceph scheme.

https://github.com/rook/rook/blob/v1.1.7/pkg/operator/ceph/disruption/clusterdisruption/add.go#L44

The cr_manager also uses `context.Kubeconfig` to instantiate it's client (not obviously):
https://github.com/rook/rook/blob/v1.1.7/pkg/operator/ceph/cr_manager.go#L34

I'll push a PR to use a DeepCopy of the Kubeconfig for the controller-runtime manager.
