### ISSUE TITLE
OSDs upgraded unnecessarily during rook upgrade due to requirement of activating LVM

### ISSUE THREAD

**Issue by travisn** [rook/rook#4363]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
During a Rook upgrade, there is no need to restart the Ceph daemons unless there is an important update to the daemon pod spec. If the rook image only changed, that only impacts the init container and basic daemon startup and there is not a need to restart the Ceph daemon. 

The remaining reason (after #4362) that we need the rook image in the osd daemon pod is in order to call `ceph-volume activate` so the osd can access the config from the `prepare`. If we can remove the need for the `ceph-volume activate` command, we could remove the need for the OSDs to be restarted during every rook upgrade. This can cause unnecessary downtime at least briefly during an upgrade. This would require changes to `ceph-volume` provide a different way to start the osd daemon without requiring the activate.

**Expected behavior:**
OSDs should not restart during every rook upgrade.

**How to reproduce it (minimal and precise):**

- Upgrade the rook version such as from v1.1.6 to v1.1.7.
- See the osd pods restarted

**Comment by travisn** [comment]
After discussing with @liewegas @sebastian-philipp we should actually be able to workaround this with the following:
- Use an EmptyDir in both the init container and the main container that is mounted to the path where the `c-v activate` would work with the files.
- Call `c-v activate` from an init container. Since the directory will be found already, c-v will use the directory instead of creating a tmpfs
- `ceph-osd` can be started directly from the container command instead of rook needing to create the process.

Then with the fix for #4362 we should be able to remove the rook image from the osd pod spec.

**Comment by leseb** [comment]
Unfortunately, this won't be enough, the last thing that cannot be fixed easily is the code that catches the stop signal and de-activate the LV and then kills the OSD process...
I can make it work with bash but that's over-engineering the solution.

**Comment by leseb** [comment]
> * Use an EmptyDir in both the init container and the main container that is mounted to the path where the `c-v activate` would work with the files.
> * Call `c-v activate` from an init container. Since the directory will be found already, c-v will use the directory instead of creating a tmpfs

This is not what I observed, c-v mounts the tmpfs even if the dir is already present.

**Comment by R-omk** [comment]
I found a bug in version 1.2.4 in the getVolumeGroupName function, but at the moment in the master branch it has slightly changed its format.

However, the function still expects lvPath with three parts 
`Assert that lvpath is in correct format /dev/<vg name>/<lv name> before extracting the vg name`

But osd deployment in pod spec template set the value in a different format
```
        - name: ROOK_LV_PATH
          value: vg0/lv0
```

which led to a fall.

When I manually changed the environment in the correct format
```
        - name: ROOK_LV_PATH
          value: /dev/vg0/lv0
```

another problem occurred (see: func StartOSD )

```
2020-02-18 09:29:47.967571 I | cephosd: Successfully updated lvm config file "/etc/lvm/lvm.conf"
2020-02-18 09:29:47.967610 I | exec: Running command: vgchange -an vg0
2020-02-18 09:29:48.035077 I |   Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
2020-02-18 09:29:48.035366 I |   Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
2020-02-18 09:29:48.044315 I |   Volume group "vg0" not found
2020-02-18 09:29:48.044337 I |   Cannot process volume group vg0
failed to deactivate volume group for lv "/dev/vg0/lv0": Failed to complete '': exit status 5. 


```

@leseb , please explain, is the current issue fixing this problem, or  vgchange can still cause a crash?

But what if the volume group has other volumes that are used separately from the ceph?
