### ISSUE TITLE
Missing securityContext for Init container 

### ISSUE THREAD

**Issue by iyurev** [rook/rook#4372]
I've tried install rook Ceph for test purposes , follow guide - https://rook.io/docs/rook/v1.1/ceph-examples.html  

It looks like missing securityContext  for init container - **chown-container-data-dir** , 
that causes  permissions error:

```
chown: cannot access '/var/log/ceph/ceph-volume.log': Permission denied
failed to change ownership of '/var/log/ceph/ceph-volume.log' to ceph:ceph
chown: cannot access '/var/log/ceph/rook-ceph-osd.0.log': Permission denied
chown: changing ownership of '/var/log/ceph': Permission denied
failed to change ownership of '/var/log/ceph/rook-ceph-osd.0.log' to ceph:ceph
failed to change ownership of '/var/log/ceph' from ceph:ceph to ceph:ceph
chown: changing ownership of '/var/lib/ceph/crash/posted': Permission denied
failed to change ownership of '/var/lib/ceph/crash/posted' from ceph:ceph to ceph:ceph
chown: changing ownership of '/var/lib/ceph/crash': Permission denied
failed to change ownership of '/var/lib/ceph/crash' from ceph:ceph to ceph:ceph
```

This's my initContainers:

       "initContainers": [
          {
            "args": [
              "/var/lib/ceph/crash/posted"
            ],
            "command": [
              "mkdir",
              "-p"
            ],
            "image": "ceph/ceph:v14.2.4-20190917",
            "imagePullPolicy": "IfNotPresent",
            "name": "make-container-crash-dir",
            "resources": {},
            **"securityContext": {
              "privileged": true**
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "volumeMounts": [
              {
                "mountPath": "/etc/ceph",
                "name": "rook-config-override",
                "readOnly": true
              },
              {
                "mountPath": "/var/log/ceph",
                "name": "rook-ceph-log"
              },
              {
                "mountPath": "/var/lib/ceph/crash",
                "name": "rook-ceph-crash"
              }
            ]
          },
          {
            "args": [
              "--verbose",
              "--recursive",
              "ceph:ceph",
              "/var/log/ceph",
              "/var/lib/ceph/crash"
            ],
            "command": [
              "chown"
            ],
            "image": "ceph/ceph:v14.2.4-20190917",
            "imagePullPolicy": "IfNotPresent",
            "name": "chown-container-data-dir",
            "resources": {},
            "securityContext": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "volumeMounts": [
              {
                "mountPath": "/etc/ceph",
                "name": "rook-config-override",
                "readOnly": true
              },
              {
                "mountPath": "/var/log/ceph",
                "name": "rook-ceph-log"
              },
              {
                "mountPath": "/var/lib/ceph/crash",
                "name": "rook-ceph-crash"
              }
            ]
          }
        ],

**Environment**:

OCP 4.1 
RHCOS 4.1

**Comment by leseb** [comment]
Fix by https://github.com/rook/rook/pull/4344/files
