### ISSUE TITLE
When upgrading 1.0 to 1.1 osd lifecycle hook is failing 

### ISSUE THREAD

**Issue by hannesrauhe** [rook/rook#4376]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
two of the osd pods went into a crashloop

**File(s) to submit**:
Events in OSDs
```
Events:
  Type     Reason               Age                   From                   Message
  ----     ------               ----                  ----                   -------
  Normal   Scheduled            14m                   default-scheduler      Successfully assigned rook-ceph/rook-ceph-osd-1-6b5445764-7m2d6 to dexxpl348408
  Normal   Created              14m                   kubelet, dexxpl348408  Created container config-init
  Normal   Started              14m                   kubelet, dexxpl348408  Started container config-init
  Normal   Pulled               14m                   kubelet, dexxpl348408  Container image "rook/ceph:v1.1.0" already present on machine
  Normal   Pulled               14m                   kubelet, dexxpl348408  Container image "rook/ceph:v1.1.0" already present on machine
  Normal   Created              14m                   kubelet, dexxpl348408  Created container copy-bins
  Normal   Started              14m                   kubelet, dexxpl348408  Started container copy-bins
  Warning  FailedPostStartHook  14m                   kubelet, dexxpl348408  Exec lifecycle hook ([chown --recursive --verbose ceph:ceph /var/log/ceph /var/lib/rook/storage/osd1]) for Container "osd" in Pod "rook-ceph-osd-1-6b5445764-7m2d6_rook-ceph(b4e43422-1054-11ea-a5ca-001999fe6488)" failed - error: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (16272795 vs. 8388608), message: ""
```

In order to get the cluster back in a working state I followed a hunch and removed the `--verbose` from the lifecycle section of the affected OSD deployments

**Environment**:
* OS: Ubuntu 16.04.6 LTS
* Cloud provider or hardware configuration: large baremetal servers 
* Rook version (use `rook version` inside of a Rook Pod): v1.1.7-6-g755b10a
* Kubernetes version (use `kubectl version`): v1.14.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadmin deployed

**Comment by leseb** [comment]
I think the fix is in master but hasn't been backported. 1.2 will be out mid-december I guess we can wait for it.

**Comment by hannesrauhe** [comment]
The problem is that the osds are re-created by the operator on configuration changes and failures, so the `--verbose` is always re-added. Any idea how I can fix this without switching to the master branch?

**Comment by leseb** [comment]
> Any idea how I can fix this without switching to the master branch?

Unfortunately no.
