### ISSUE TITLE
On image change, always run the ok-to-stop checks

### ISSUE THREAD

**Issue by leseb** [rook/rook#4379]
Currently, we only run the tests if the ceph version is different, we should not do that.
So if a new image is injected AND if that image has >= version then let's proceed. We still don't allow downgrade.

**Comment by BlaineEXE** [comment]
Given this comment (https://github.com/rook/rook/pull/4442#issuecomment-565406807) are we waiting to do this in a v1.2 patch release?

**Comment by leseb** [comment]
> Given this comment ([#4442 (comment)](https://github.com/rook/rook/pull/4442#issuecomment-565406807)) are we waiting to do this in a v1.2 patch release?

Yes, not in the initial 1.2 release, a one of the minor release.
