### ISSUE TITLE
Non-CSI storageclass for v1.1

### ISSUE THREAD

**Issue by ndik11** [rook/rook#4383]
How to set this up? I mean CephBlockPool + StorageClass without CSI There are examples about setting up CSI StorageClass, but I couldnt find example how to setup StorageClass like in v1.0.
Also I tried with template from v1.0 with Rook cluster v1.1. No luck, getting error:

`MountVolume.SetUp failed for volume "pvc-eb6ff144-10ed-11ea-b550-005056baf32d" : mount command failed, status: Failure, reason: Rook: Error getting RPC client: error connecting to socket /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ceph.rook.io~rook-ceph/.rook.sock: dial unix /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ceph.rook.io~rook-ceph/.rook.sock: connect: no such file or directory`

I think api changed or something like this.
Please help

**Comment by travisn** [comment]
@ndik11 To create a volume based on the flex driver, see the [flex driver](https://rook.io/docs/rook/v1.1/ceph-block.html#flex-driver) section in the docs. You should also be able to use the examples from the v1.0 docs, except 1) you need to enable the operator setting for the flex driver, and the example storage class moved to the `flex` subdir in the examples.

**Comment by ndik11** [comment]
> @ndik11 To create a volume based on the flex driver, see the [flex driver](https://rook.io/docs/rook/v1.1/ceph-block.html#flex-driver) section in the docs. You should also be able to use the examples from the v1.0 docs, except 1) you need to enable the operator setting for the flex driver, and the example storage class moved to the `flex` subdir in the examples.

it helped me. thx
