### ISSUE TITLE
Ceph: support topologySpreadConstraints

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#4387]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

It's necessary to support topologySpreadConstraints to spread OSDs among failure domains as much as possible. The detail is written in the following document.
https://github.com/rook/rook/blob/369958e08bbbd8f0058a288e2f4444246d22a391/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml#L54

In addition, the meaning of topologySpreadConstraints is written in the following document.
https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

**What is use case behind this feature:**

Spread OSDs among failure domains and permit multiple OSDs per one failure domain.

**Comment by satoru-takeuchi** [comment]
I have a question about how to implement topologySpreadConstraints support.

I found that Rook and operator-kit depend on kubernetes 1.14. However, topologySpreadConstraints is defined in kubernetes 1.16 or later. So, could you give me advice about what is the preferred way to support this feature?

a. Update dependency of the kubernetes version to 1.16 and implement this feature's support.
b. Write a document of a workaround for now, and support this feature when Rook starts to use kubernetes 1.16 . I'm now preparing a mutating admission webhook that injects TopologySpreadConstraints resource to OSD pods. I can share how to implement it in Rook's document.
c. Any other ways.

**Comment by travisn** [comment]
@satoru-takeuchi We can update the client to 1.16. I'll look at this update in the next day or two so we can have topology constraints in 1.2. thanks!

**Comment by travisn** [comment]
@satoru-takeuchi Updating to the 1.16 client is going to take some time to work through the dependencies as mentioned in #4408. If you want to continue looking at this feature, it would be great to get some early testing even before it's available through rook directly.

**Comment by satoru-takeuchi** [comment]
@travisn Yes, of course. I'll test PR#4408 and make my PR on top of your PR soon.

**Comment by BlaineEXE** [comment]
I think we should consider waiting to implement this until the feature goes into beta in k8s so we don't have to deal with any instabilities between alpha and beta.

**Comment by satoru-takeuchi** [comment]
I'll implement this feature soon in any case. It's because we're constructing a Ceph cluster and this feature is mandatory here. So sharing a draft PR here is nice, I think.

I expect the following scenario.

1. Make a PR on top of Travis's PR and use it for our cluster as a temporary solution.
2. After this feature goes beta, change my PR to conform to beta.
3. Try to merge the new version to upstream Rook.

**Comment by satoru-takeuchi** [comment]
One of my co-workers @tapih made a branch that enables topologySpreadConstraints.

https://github.com/cybozu-go/rook/commit/b4bd2eef5529290ccb317f3872649a96687cef01

This branch is on top of the following branch.

https://github.com/rook/rook/pull/4408

When topologySpreadConstraints goes into beta, I'll make a PR based on this branch.
Any comments are welcome.

NOTE:
Unfortunately, this feature and all other features in StorageClassDeviceSet.Placement doesn't work correctly without fixing the following issue.

https://github.com/rook/rook/issues/4582

**Comment by ymmt2005** [comment]
topologySpreadConstraints will become beta in Kubernetes 1.18.
https://github.com/kubernetes/enhancements/pull/1482

**Comment by moricho** [comment]
@satoru-takeuchi I updated the dependencies related to k8s and Rook supports k8s v1.17 now.

https://github.com/rook/rook/pull/4984

**Comment by satoru-takeuchi** [comment]
@moricho Thank you very much! I'll prepare the PR for this issue!

**Comment by satoru-takeuchi** [comment]
https://github.com/rook/rook/issues/4387#issuecomment-562342728
> I think we should consider waiting to implement this until the feature goes into beta in k8s so we don't have to deal with any instabilities between alpha and beta.

TopologySpreadConstraints will be beta and there would be no breaking changes. 

https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20190221-pod-topology-spread.md#graduation-criteria

Can I start to prepare PR, or should I wait for a while, for example, the release of K8s v1.18?

**Comment by travisn** [comment]
Sounds good to wait until 1.18 for this feature when it is in beta. I see 1.18.rc1 so it's getting close...
