### ISSUE TITLE
Errors upgrading Mimic to Nautilus on Rook 1.1.7

### ISSUE THREAD

**Issue by eknudtson** [rook/rook#4405]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
During an upgrade from Ceph Mimic to Nautilus on Rook 1.1.7, I ran into a few issues resulting in a stuck upgrade process.  Mons are n, o, and p.

The first sign of trouble showed up with the following command in the operator logs: 
```
ceph mon ok-to-stop p ...
```

which resulted in 

```Error EINVAL: invalid command```

This retried for a while before the operator bailed out and restarted the orchestration.

Somehow it now was able to progress, but now mon-p is looping with the following output : 

https://gist.github.com/eknudtson/5344fefdb6bcff341e84f45791d1c5f0

with mons o and n looping with variations on this output : 

`debug 2019-12-02 17:36:49.714 7f16e6439700  0 --1- [v2:10.23.128.65:3300/0,v1:10.23.128.65:6789/0] >> v1:10.23.181.186:6789/0 conn(0x5585a5e10800 0x5585a5edc000 :6789 s=ACCEPTING_WAIT_CONNECT_MSG_AUTH pgs=0 cs=0 l=0).handle_connect_message_2 accept peer reset, then tried to connect to us, replacing`

**Expected behavior:**

The Mimic -> Nautilus upgrade to complete successfully and automatically.

**How to reproduce it (minimal and precise):**
Create a v0.9 rook ceph cluster with rook-ceph and rook-ceph-system namespaces using Ceph Mimic.  Upgrade it to rook, v1.0 then v1.1.7.  Attempt to upgrade from Mimic to Nautilus

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
https://gist.github.com/eknudtson/59b12c725c8f5ba69c91a4a51a81d690
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7
* Kernel (e.g. `uname -a`):3.10.0-1062.4.3.el7.x86_64
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): 1.1.7
* Storage backend version (e.g. for ceph do `ceph -v`): upgrade from v13.2.6-20190830 to v14.2.4-20191112
* Kubernetes version (use `kubectl version`): 1.15.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm/baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```# ceph status
  cluster:
    id:     920f488f-a33b-471b-b449-c2d47114237a
    health: HEALTH_WARN
            1/3 mons down, quorum n,o

  services:
    mon: 3 daemons, quorum n,o (age 45m), out of quorum: p
    mgr: a(active)
    osd: 36 osds: 36 up, 36 in

  data:
    pools:   1 pools, 1024 pgs
    objects: 84.13k objects, 323 GiB
    usage:   1.4 TiB used, 12 TiB / 13 TiB avail
    pgs:     1024 active+clean

  io:
    client:   13 MiB/s wr, 0 op/s rd, 21 op/s wr
```

**Comment by eknudtson** [comment]
This was in our staging k8s cluster, but we need to upgrade our production cluster safely at some point.

**Comment by eknudtson** [comment]
I was able to fix this by reverting our CRD to the mimic version.  The operator attempted to update mon-p and failed.  At this point I re-upgraded our CRD to Nautilus and the cluster processed the upgrade successfully (though it did fail over mon-p to mon-q when it was done).

I'm still curious why this happened in the first place.

**Comment by travisn** [comment]
@eknudtson Are you saying that it upgraded successfully on the second attempt of the same upgrade path? Or did anything else change on the second upgrade attempt? Do you have the operator log from the failed upgrade?

**Comment by eknudtson** [comment]
The second attempt did work successfully (reverting CRD, operator gets stuck, upgrade CRD again, restart operator).

Unfortunately I don't have the operator logs due to all the restarts.

**Comment by eknudtson** [comment]
FWIW the operator did play it safe even when it got stuck, my PVCs were available the entire time during the upgrade failure.

**Comment by eknudtson** [comment]
Here is the operator log where it finally completed successfully.

Prior to this orchestration, I had set the CRD back to the Ceph Mimic version.  The operator got stuck at this point, but it seemed to break it out of the loop it had been in while trying to upgrade to Nautilus.

After setting the CRD back to Nautilus and restarting the operator again, here is the result : 

https://gist.github.com/eknudtson/c68ad4fd83fcb0a1a42ed010fd8972d2

**Comment by eknudtson** [comment]
It looks like it proceeded through the failed mon-p since it skipped the upgrade checks this time?  With mon-p being removed at the end in favor of mon-q.
