### ISSUE TITLE
Can't delete cephcluster rook-ceph even Removing the Cluster CRD Finalizer

### ISSUE THREAD

**Issue by tarjintor** [rook/rook#4410]
My rook version is 1.1.7
I am testing rook/ceph with bluestore, and clean up the cluster for serveral times,and I do the https://rook.io/docs/rook/v1.1/ceph-teardown.html process

And I can delete the rook-ceph namespace ,but every time I rebuild the cluster,I found 
cephcluster is still there

and the pre cluster config is auto working after I apply comon.yaml

I try to delete the crd, use 
`kubectl -n rook-ceph patch crd cephclusters.ceph.rook.io --type merge -p '{"metadata":{"finalizers": [null]}}'`

or restart my node, but none of these works.

Is there a way to force delete cephcluster ?

**Comment by WoohyungHan** [comment]
I think some resources are remain in /var/lib/rook. You would remove the directory in all kubernetes nodes. (and volumegroup and logicalvolume if it exists)

**Comment by tarjintor** [comment]
I delete these files 

> 
> 
> I think some resources are remain in /var/lib/rook. You would remove the directory in all kubernetes nodes. (and volumegroup and logicalvolume if it exists)

=====================================
Finnally, I found a way to delete this:
I use 
`kubectl -n rook-ceph edit cephcluster`
and then I delete all contents in nodes section,and delete the cluster again
This works.

**Comment by ilyesAj** [comment]
your solution did not work for me however i figure out that finalizer may also block the deletion of the ressource : 
````
kubectl -n rook-ceph get cephclusters.ceph.rook.io rook-ceph -o json
{
    "apiVersion": "ceph.rook.io/v1",
    "kind": "CephCluster",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"ceph.rook.io/v1\",\"kind\":\"CephCluster\",\"metad                   ata\":{\"annotations\":{},\"name\":\"rook-ceph\",\"namespace\":\"rook-ceph\"},\"spec\":{\"annotations\":null,\"cephVersion\":{\"allow                   Unsupported\":false,\"image\":\"ceph/ceph:v14.2.10\"},\"cleanupPolicy\":{\"confirmation\":\"\"},\"continueUpgradeAfterChecksEvenIfNot                   Healthy\":false,\"crashCollector\":{\"disable\":false},\"dashboard\":{\"enabled\":true,\"ssl\":true},\"dataDirHostPath\":\"/var/lib/r                   ook\",\"disruptionManagement\":{\"machineDisruptionBudgetNamespace\":\"openshift-machine-api\",\"manageMachineDisruptionBudgets\":fal                   se,\"managePodBudgets\":false,\"osdMaintenanceTimeout\":30},\"mgr\":{\"modules\":[{\"enabled\":true,\"name\":\"pg_autoscaler\"}]},\"m                   on\":{\"allowMultiplePerNode\":true,\"count\":3},\"monitoring\":{\"enabled\":false,\"rulesNamespace\":\"rook-ceph\"},\"network\":null                   ,\"placement\":{\"all\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpress                   ions\":[{\"key\":\"role\",\"operator\":\"In\",\"values\":[\"storage-node\"]}]}]}}}},\"rbdMirroring\":{\"workers\":0},\"removeOSDsIfOu                   tAndSafeToRemove\":false,\"resources\":null,\"skipUpgradeChecks\":false,\"storage\":{\"config\":null,\"nodes\":[{\"devices\":[{\"name                   \":\"vda\"}],\"name\":\"k8s-master-3\"}],\"useAllDevices\":false,\"useAllNodes\":false}}}\n"
        },
        "creationTimestamp": "2020-07-15T02:52:42Z",
        "deletionGracePeriodSeconds": 0,
        "deletionTimestamp": "2020-07-15T12:32:16Z",
        "finalizers": [
            "cephcluster.ceph.rook.io"  <--- thats what blocks the deletion 
        ],
        "generation": 70,
        "managedFields": [

````
you need to patch the ressource : 
`kubectl -n rook-ceph patch cephclusters.ceph.rook.io rook-ceph --type merge -p '{"metadata":{"finalizers":                    [null]}}'
`
and then delete crd

**Comment by vyom-soft** [comment]
> cephcluster.ceph.rook.io

I see the following
* metadata.finalizers: Invalid value: "": name part must be non-empty
* metadata.finalizers: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
* metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{""}

**Comment by smsmsajjad** [comment]
kubectl patch crd/cephclusters.ceph.rook.io -p '{"metadata":{"finalizers":[]}}' --type=merge

**Comment by travisn** [comment]
See the latest Rook documentation on [removing finalizers](https://rook.io/docs/rook/latest/Storage-Configuration/ceph-teardown/#removing-the-cluster-crd-finalizer) as well.

**Comment by vyom-soft** [comment]
> your solution did not work for me however i figure out that finalizer may also block the deletion of the ressource :
> 
> ```
> kubectl -n rook-ceph get cephclusters.ceph.rook.io rook-ceph -o json
> {
>     "apiVersion": "ceph.rook.io/v1",
>     "kind": "CephCluster",
>     "metadata": {
>         "annotations": {
>             "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"ceph.rook.io/v1\",\"kind\":\"CephCluster\",\"metad                   ata\":{\"annotations\":{},\"name\":\"rook-ceph\",\"namespace\":\"rook-ceph\"},\"spec\":{\"annotations\":null,\"cephVersion\":{\"allow                   Unsupported\":false,\"image\":\"ceph/ceph:v14.2.10\"},\"cleanupPolicy\":{\"confirmation\":\"\"},\"continueUpgradeAfterChecksEvenIfNot                   Healthy\":false,\"crashCollector\":{\"disable\":false},\"dashboard\":{\"enabled\":true,\"ssl\":true},\"dataDirHostPath\":\"/var/lib/r                   ook\",\"disruptionManagement\":{\"machineDisruptionBudgetNamespace\":\"openshift-machine-api\",\"manageMachineDisruptionBudgets\":fal                   se,\"managePodBudgets\":false,\"osdMaintenanceTimeout\":30},\"mgr\":{\"modules\":[{\"enabled\":true,\"name\":\"pg_autoscaler\"}]},\"m                   on\":{\"allowMultiplePerNode\":true,\"count\":3},\"monitoring\":{\"enabled\":false,\"rulesNamespace\":\"rook-ceph\"},\"network\":null                   ,\"placement\":{\"all\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpress                   ions\":[{\"key\":\"role\",\"operator\":\"In\",\"values\":[\"storage-node\"]}]}]}}}},\"rbdMirroring\":{\"workers\":0},\"removeOSDsIfOu                   tAndSafeToRemove\":false,\"resources\":null,\"skipUpgradeChecks\":false,\"storage\":{\"config\":null,\"nodes\":[{\"devices\":[{\"name                   \":\"vda\"}],\"name\":\"k8s-master-3\"}],\"useAllDevices\":false,\"useAllNodes\":false}}}\n"
>         },
>         "creationTimestamp": "2020-07-15T02:52:42Z",
>         "deletionGracePeriodSeconds": 0,
>         "deletionTimestamp": "2020-07-15T12:32:16Z",
>         "finalizers": [
>             "cephcluster.ceph.rook.io"  <--- thats what blocks the deletion 
>         ],
>         "generation": 70,
>         "managedFields": [
> ...
> ```
> 
> you need to patch the ressource : `kubectl -n rook-ceph patch cephclusters.ceph.rook.io rook-ceph --type merge -p '{"metadata":{"finalizers": [null]}}' ` and then delete crd

➜  ~ kubectl -n rook-ceph patch cephclusters.ceph.rook.io rook-ceph --type merge -p '{"metadata":{"finalizers": [null]}}'
The CephCluster "rook-ceph" is invalid:
* metadata.finalizers: Invalid value: "": name part must be non-empty
* metadata.finalizers: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
* metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{""}

**Comment by mrtshoot** [comment]
for CRD in $(kubectl get crd -n rook-ceph | awk '/ceph.rook.io/ {print $1}'); do
    kubectl get -n rook-ceph "$CRD" -o name | \
    xargs -I {} kubectl patch -n rook-ceph {} --type merge -p '{"metadata":{"finalizers": []}}'
done
