### ISSUE TITLE
New metadataDevice partitioned for single OSD

### ISSUE THREAD

**Issue by chaosaffe** [rook/rook#4413]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
New `metadataDevice` (1TB NVMe) specified at the node level is provisioned with a single partition using the whole device for a single OSD device (2.7TB HDD) when the OSD is removed and recreated.

**Expected behavior:**
A portion of the `metadataDevice` relative to the disk sync interval and expected throughput is partitioned on the `metadataDevice` for the newly created OSD

**How to reproduce it (minimal and precise):**

1. Fully provision a `CephCluster` without specifying a `metadataDevice` using Rook v1.1.7 (i.e. devices prepared using `ceph-volume` and LVM)
2. Add a `metadataDevice` to the `CephCluster`
3. Remove an OSD following https://gist.github.com/chaosaffe/0dfd92e6b5a3020f4efaaeba7c442c3a
4. Check the LVM partition size on the `metadataDevice`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
https://gist.github.com/chaosaffe/8a7eeced44ab8c4d5af01d1a7394a8e9
* Operator's logs, if necessary
N/A
* Crashing pod(s) logs, if necessary
N/A

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2247.7.0
VERSION_ID=2247.7.0
BUILD_ID=2019-11-19-2251
PRETTY_NAME="Container Linux by CoreOS 2247.7.0 (Rhyolite)"
COREOS_BOARD="amd64-usr"
```
* Kernel (e.g. `uname -a`):
`Linux node0.compute.chaosaffe.local 4.19.84-coreos #1 SMP Tue Nov 19 20:51:06 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2637 0 @ 3.00GHz GenuineIntel GNU/Linux`
* Cloud provider or hardware configuration:
Bare metal server, 1xNVMe device, 2x SSD devices, 5x HDD devices
* Rook version (use `rook version` inside of a Rook Pod):
```
rook: v1.1.7
go: go1.11
```
* Storage backend version (e.g. for ceph do `ceph -v`):
`ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)`
* Kubernetes version (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
`HEALTH_WARN Degraded data redundancy: 207/8587353 objects degraded (0.002%), 4 pgs degraded, 4 pgs undersized`

**Comment by travisn** [comment]
@chaosaffe With the latest rook and Ceph v14.2.8 partition support is available now. This means you should be able to create your own partitions and use them for the metadata device. It doesn't really solve your original request in this issue, but it's another option.
