### ISSUE TITLE
kubectl operator.yaml，rook-ceph-agent-xxx Not running

### ISSUE THREAD

**Issue by yq513** [rook/rook#4417]
-----Bug Report
# kubectl create -f operator.yaml 
rook-ceph-agent-xxx Not running
------should--------------------
[centos@k8s-master ~]$ kubectl get pod -n rook-ceph-system  -o wide
NAME                                  READY   STATUS    RESTARTS   AGE     IP              NODE         NOMINATED NODE   READINESS GATES
rook-ceph-agent-49w7t                 1/1     Running   0          7m48s   192.168.92.57   k8s-node1    <none>           <none>
rook-ceph-agent-dpxkq                 1/1     Running   0          111s    192.168.92.58   k8s-node2    <none>           <none>
rook-ceph-agent-wb6r8                 1/1     Running   0          7m48s   192.168.92.56   k8s-master   <none>           <none>
rook-ceph-operator-85d64cfb99-2c78k   1/1     Running   0          9m3s    10.244.1.2      k8s-node1    <none>           <none>
rook-discover-597sk                   1/1     Running   0          7m48s   10.244.0.4      k8s-master   <none>           <none>
rook-discover-7h89z                   1/1     Running   0          111s    10.244.2.2      k8s-node2    <none>           <none>
rook-discover-hjdjt                   1/1     Running   0          7m48s   10.244.1.3      k8s-node1    <none> 
-------actual-------
[centos@k8s-master ~]$ kubectl get pod -n rook-ceph-system  -o wide
NAME                                  READY   STATUS    RESTARTS   AGE     IP              NODE         NOMINATED NODE   READINESS GATES
rook-ceph-operator-85d64cfb99-2c78k   1/1     Running   0          9m3s    10.244.1.2      k8s-node1    <none>           <none>
rook-discover-597sk                   1/1     Running   0          7m48s   10.244.0.4      k8s-master   <none>           <none>
rook-discover-7h89z                   1/1     Running   0          111s    10.244.2.2      k8s-node2    <none>           <none>
rook-discover-hjdjt                   1/1     Running   0          7m48s   10.244.1.3      k8s-node1    <none> 

--------
After obtaining operator.yaml, I deployed kubectl create -f operator.yaml directly, but rook-ceph-agent-xxx Not running

--------
centos 7
Linux k8s-m 3.10.0-1062.4.1.el7.x86_64
vmware
nwe
new
Kubernetes 1.16.2
---------
What else needs to be modified in operator.yaml? I also tried to comment some, but it has no effect, ask everyone

**Comment by travisn** [comment]
@yq513 In v1.1 the flex driver (agent) is disabled by default. If you need the agent instead of using the recommended CSI driver, you'll need to enable the `ROOK_ENABLE_FLEX_DRIVER ` setting in operator.yaml as described in the [docs](https://rook.io/docs/rook/v1.1/ceph-block.html#flex-driver).

**Comment by yq513** [comment]
> @yq513 In v1.1 the flex driver (agent) is disabled by default. If you need the agent instead of using the recommended CSI driver, you'll need to enable the `ROOK_ENABLE_FLEX_DRIVER` setting in operator.yaml as described in the [docs](https://rook.io/docs/rook/v1.1/ceph-block.html#flex-driver).

To make pods use block storage, how is yaml configured?
My yaml created pods gives an error：

Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[default-token-gq92d wordpress-persistent-storage]: failed to get Plugin from volumeSpec for volume "pvc-c76c8cba-21d7-45da-ae8f-fadb97b28f83" err=no volume plugin matched
