### ISSUE TITLE
Is there a doc describe details of how operator works when cluster.yaml changed?

### ISSUE THREAD

**Issue by tarjintor** [rook/rook#4419]
Hello,

I used rook a lot, and it great to use it work with kubernetes

Recently I find its hard to figure out how operator works when cluster.yaml changes

My old cluster is too small and there are hdd rather than ssd are used. I bought some more devices（ssd）,but failed to update the cluster easily.

For example:
1.Can I delete a device in nodes section,so the osd on that device will be deleted?

2.when I delete a nodes in cluster.yaml,what will happened?

3.Can I change the cluster.yaml to add a metadata device to a already existed osd?

4.Can I change a filestore osd to a bluestore osd?

etc

I found this is quite complicated for the states of a cluster are countless and state to state conditions can be even much more。

So, if I want to know what will happened if I changed the cluster.yaml and apply it,the only way is to read the source code?

I guess for complicated case ,this is OK

but can there be a doc for some simple case?

Thx

**Comment by travisn** [comment]
The OSD documentation that we have is mainly found on the [Cluster CRD](https://rook.io/docs/rook/v1.1/ceph-cluster-crd.html) topic. Agreed that the documentation is not clear on the advanced usage. OSDs are complicated enough that we should likely dedicate a new help doc to answer questions like this. Contributions welcome! :)

There are many ways to change the cluster.yaml. Some are supported and some are not. It's a complicated matrix of possibilities. At least we should document which settings can be changed and which ones cannot. @galexrt Maybe this is something to include in your doc changes soon?

> 1.Can I delete a device in nodes section,so the osd on that device will be deleted?

OSDs will not be removed if individual devices are deleted from the cluster CR

> 2.when I delete a nodes in cluster.yaml,what will happened?

If nodes are deleted from the cluster CR, the OSDs would be automatically deleted

> 3.Can I change the cluster.yaml to add a metadata device to a already existed osd?

Metadata devices can only be used for newly created OSDs.

> 4.Can I change a filestore osd to a bluestore osd?

No, the OSD type cannot be changed.
