### ISSUE TITLE
The operator pod failed to recognize cephcluster image version change

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#4436]
**Is this a bug report or feature request?**
* Bug Report
After cephcluster is patched with new image v14.2.4-20190917. The rook operator didn't recognized the update. When the operator is restarted, the image update is identified and upgrade action is performed. 

**Deviation from expected behavior:**
1). Sunny day case operator log
```
2019-12-05 16:45:52.151985 I | op-cluster: finalizer already set on cluster rook-ceph
W1205 16:45:52.153560       6 reflector.go:289]
github.com/rook/operator-kit/watcher.go:76: watch of *v1.CephCluster ended with: too
old resource version: 88291997 (88303117)
2019-12-05 16:45:53.156544 I | op-cluster: The Cluster CR has changed.
diff={v1.ClusterSpec}.CephVersion.Image:
        -:
"ceph:v14.2.1-20190430"
        +:
"ceph:v14.2.4-20190917"
{v1.ClusterSpec}.SkipUpgradeChecks:
        -: false
        +: true
{v1.ClusterSpec}.Mgr.Modules:
        -: []v1.Module(nil)
        +: []v1.Module{{Name: "pg_autoscaler", Enabled: true}}
2019-12-05 16:45:53.156673 I | op-cluster: update event for cluster rook-ceph is
supported, orchestrating update now
2019-12-05 16:45:53.156717 I | op-cluster: the ceph version changed from
ceph/ceph:v14.2.1-20190430 to
ceph/ceph:v14.2.4-20190917
2019-12-05 16:45:53.156761 I | op-cluster: detecting the ceph image version for image
ceph/ceph:v14.2.4-20190917...
```
2). Rainy day case operator log. The patch happened at "03:07:58" based on /var/log/messages. 
```
W1205 03:07:57.160073       6 reflector.go:289] github.com/rook/operator-kit/watcher.go:76: watch of *v1.CephFilesystem ended with: too old resource version: 43824 (55287)
W1205 03:07:57.160136       6 reflector.go:289] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: watch of *v1.CephFilesystem ended with: too old resource version: 43824 (55287)
W1205 03:07:57.175522       6 reflector.go:289] github.com/rook/operator-kit/watcher.go:76: watch of *v1.CephNFS ended with: too old resource version: 55009 (55288)
W1205 03:07:57.196741       6 reflector.go:289] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: watch of *v1.CephObjectStore ended with: too old resource version: 43825 (55290)
W1205 03:07:57.196801       6 reflector.go:289] github.com/rook/operator-kit/watcher.go:76: watch of *v1.CephObjectStore ended with: too old resource version: 43825 (55290)
W1205 03:12:57.788578       6 reflector.go:289] github.com/rook/rook/pkg/operator/ceph/cluster/controller.go:174: watch of *v1.ConfigMap ended with: too old resource version: 43800 (56207)
```

**Expected behavior:**
The update should be recognized by the operator when patched. If not, the "auditing" should kick in to identify the change without manually restart the operator. 

**How to reproduce it (minimal and precise):**

The issue happened randomly in the same lab env. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): 3.10.0-957.21.3.el7.x86_64
* Cloud provider or hardware configuration: openstack 
* Rook version (use `rook version` inside of a Rook Pod): 1.1.7
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.4
* Kubernetes version (use `kubectl version`): 14.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by yanchicago** [comment]
Any insight on this issue?

**Comment by travisn** [comment]
It seems the operator was not informed by the CR update. Do you see any messages in the operator log about the `CephCluster` being `too old` such as this?
```
watch of *v1.CephCluster ended with: too old resource version:
```
