### ISSUE TITLE
NFS integration tests failing in master

### ISSUE THREAD

**Issue by travisn** [rook/rook#4437]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The NFS integration tests are failing consistently in master since *.

```
--- FAIL: TestNfsSuite (863.80s)
    --- FAIL: TestNfsSuite/TestNfsServerInstallation (814.52s)
        read_write.go:45: 
            	Error Trace:	read_write.go:45
            	            				nfs_test.go:114
            	Error:      	Should be true
            	Test:       	TestNfsSuite/TestNfsServerInstallation
            	Messages:   	Make sure there are two read-write-test pods present in Running state
        require.go:794: 
            	Error Trace:	nfs_test.go:145
            	            				nfs_test.go:116
            	Error:      	Received unexpected error:
            	            	unable to write data to pod -- : Failed to run: kubectl [exec read-write-test-5755fb789d-9z9q2 -- cat /mnt/data] : Failed to complete 'kubectl': exit status 1. 
            	Test:       	TestNfsSuite/TestNfsServerInstallation
```

**Expected behavior:**
Integration tests should pass

**How to reproduce it (minimal and precise):**

Look at the CI logs starting with master build [#1577](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/master/1577/pipeline/56)

This error is related:
```
2019-12-05 03:51:18.195066 I | exec: Running command: kubectl get pod -n default -l app=read-write-test -o jsonpath={.items[*].metadata.name}
2019-12-05 03:51:18.264858 I | exec: Running command: kubectl exec read-write-test-5755fb789d-9z9q2 -- cat /mnt/data
2019-12-05 03:51:18.364925 E | utils: Failed to execute: kubectl [exec read-write-test-5755fb789d-9z9q2 -- cat /mnt/data] : Failed to complete 'kubectl': exit status 1. . error: unable to upgrade connection: container not found ("alpine")
2019-12-05 03:51:18.364956 I | integrationTest: nfs volume read exited, err: unable to write data to pod -- : Failed to run: kubectl [exec read-write-test-5755fb789d-9z9q2 -- cat /mnt/data] : Failed to complete 'kubectl': exit status 1. . result: 
2019-12-05 03:51:18.364963 W | integrationTest: nfs volume read failed, will try again
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by rohan47** [comment]
there is an issue with the writing of data to the nfs volume.

**Comment by rohan47** [comment]
NFS server is failing with the following error only in the Integration Test, It works locally.
`nfs-ganesha-22[main] main :MAIN :FATAL :Can't open pid file /var/run/ganesha/ganesha.pid for writing`
[nfs-server log on jenkins](https://jenkins.rook.io/job/rook/job/rook/job/master/1577/artifact/_output/tests/TestNfsSuite_aws_1.14.x_nfs-ns_nfs-ns-0_1575519186.log)

**Comment by leseb** [comment]
@rohan47 strange, this PR passed CI... https://github.com/rook/rook/pull/4396

**Comment by leseb** [comment]
I guess I'm confused, is it ceph-nfs or the nfs backend for rook?

**Comment by travisn** [comment]
It's the NFS operator, rather than CephNFS, so not sure why #4396 would have impacted it.

**Comment by leseb** [comment]
@rohan47's comment led me to think #4396 was related since I changed the PID path.

**Comment by rohan47** [comment]
yes @leseb

**Comment by rohan47** [comment]
> @rohan47's comment led me to think #4396 was related since I changed the PID path.

Yes @leseb , but for https://github.com/rook/rook/pull/4450 the failures are not NFS operator related.

**Comment by leseb** [comment]
I guess I'm confused, is it related to my patch or not?

**Comment by rohan47** [comment]
Yes its related as your patch updates `pkg/operator/nfs/server.go`

**Comment by leseb** [comment]
Woops I didn't realize that, my bad. So you're fixing this @rohan47?

**Comment by rohan47** [comment]
@leseb  No, I just updated the nfs version, and you added the actual fix.

**Comment by travisn** [comment]
Even with #4450 merged to master, we're still seeing this failure. Seems like we need to revert the changes in `pkg/operator/nfs/server.go`
