### ISSUE TITLE
ERROR：Unable to attach or mount volumes，err=no volume plugin matched

### ISSUE THREAD

**Issue by yq513** [rook/rook#4438]
I deployed ceph, after creating the storage, the pod cannot be mounted on the PV, prompt
Unable to attach or mount volumes, err = no volume plugin matched

The main error message is as follows. What is the problem? Thank you.

Main------------
Created directory：
[root@k8s-m kubernetes]# cd /var/lib/kubelet/volumeplugins/
[root@k8s-m volumeplugins]# pwd
/var/lib/kubelet/volumeplugins

Added volume-plugin parameter：
[root@k8s-m kubernetes]# cat /opt/kubernetes/conf/kubelet.conf
KUBE_MASTER="--master=http://192.168.21.117:8080"
KUBELET_OPTS="--logtostderr=true \
--log-dir=/var/log/kubernetes/kubelet \
--v=4 \
--volume-plugin-dir=/var/lib/kubelet/volumeplugins \

ceph operator.ymal ：
- name: FLEXVOLUME_DIR_PATH
  value: "/var/lib/kubelet/volumeplugins"

After kubelet is started: Error getting volume limit for plugin：
[root@k8s-m kubernetes]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet Server
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 二 2019-12-03 22:15:09 CST; 2 days ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 3302 (kubelet)
    Tasks: 21
   Memory: 62.7M
   CGroup: /system.slice/kubelet.service
           └─3302 /opt/kubernetes/bin/kubelet --logtostderr=true --log-dir=/var/log/kubernetes/kubelet --v=4 --volume-plugin-dir=/var/lib/kubelet/volu...

12月 06 09:23:49 k8s-m kubelet[3302]: I1206 09:23:49.772993    3302 prober.go:162] Exec-Probe Pod: &Pod{ObjectMeta:{calico-node-q9qct calico...n-hash:7d
12月 06 09:23:49 k8s-m kubelet[3302]: I1206 09:23:49.940048    3302 exec.go:43] Exec probe response: "2019-12-06 01:23:49.890 [INFO][2258] h...ed = 2\n"
12月 06 09:23:49 k8s-m kubelet[3302]: I1206 09:23:49.940097    3302 prober.go:129] Readiness probe for "calico-node-q9qct_kube-system(d978de...succeeded
12月 06 09:23:50 k8s-m kubelet[3302]: I1206 09:23:50.267285    3302 kubelet.go:1988] SyncLoop (housekeeping)
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.273124    3302 kubelet.go:2184] Container runtime status: Runtime Conditions: RuntimeRe... message:
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.711001    3302 setters.go:757] Error getting volume limit for plugin kubernetes.io/cinder
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.711030    3302 setters.go:757] Error getting volume limit for plugin kubernetes.io/gce-pd
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.711040    3302 setters.go:757] Error getting volume limit for plugin kubernetes.io/aws-ebs
12月 06 09:23:51 k8s-m kubelet[3302]: I1206 09:23:51.711052    3302 setters.go:757] Error getting volume limit for plugin kubernetes.io/azure-disk
12月 06 09:23:52 k8s-m kubelet[3302]: I1206 09:23:52.267319    3302 kubelet.go:1988] SyncLoop (housekeeping)

pod mount PV error：
Unable to attach or mount volumes: unmounted volumes=[mysql-persistent-storage], unattached volumes=[default-token-gq92d mysql-persistent-storage]: 
failed to get Plugin from volumeSpec for volume "pvc-e4226e5f-04ec-4b4c-9884-53e46618a966" err=no volume plugin matched

Warning  FailedMount  31m (x610 over 10h)   kubelet, 192.168.21.118  Unable to attach or mount volumes: unmounted volumes=[mysql-persistent-storage], 
unattached volumes=[default-token-gq92d mysql-persistent-storage]: failed to get Plugin from volumeSpec 
for volume "pvc-9ec3d012-d434-4f8a-8791-33d3503b9316" err=no volume plugin matched
---------
CentOS Linux release 7.7.1908 (Core)
Linux k8s-m 3.10.0-1062.4.1.el7.x86_64
vmware
Rook version 1.1.7
ceph 1.14.2
Kubernetes 1.16.2
Storage backend status：
# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS      REASON   AGE
pvc-9ec3d012-d434-4f8a-8791-33d3503b9316   20Gi       RWO            Retain           Bound    default/mysql-pv-claim   rook-ceph-block            10h
pvc-af6818f9-2b21-461f-ad44-264d8ff294ff   20Gi       RWO            Retain           Bound    default/wp-pv-claim      rook-ceph-block            10h

**Comment by Madhu-1** [comment]
@yq513 any specific reason not to use CSI? please provide storageclass output you have used

**Comment by yq513** [comment]
> @yq513 any specific reason not to use CSI? please provide storageclass output you have used

I use    rook+ceph

[root@dk-node01 /]# ceph osd lspools 
6 wcl-pool
[root@k8s-m ceph]# kubectl get storageclasses
NAME              PROVISIONER          AGE
rook-ceph-block   ceph.rook.io/block   40s

[root@k8s-m kubernetes]# kubectl create -f wordpress.yaml     
service/wordpress created
persistentvolumeclaim/wp-pv-claim created
deployment.apps/wordpress created
[root@k8s-m kubernetes]# kubectl create -f mysql.yaml 
service/wordpress-mysql created
persistentvolumeclaim/mysql-pv-claim created
deployment.apps/wordpress-mysql created
[root@k8s-m kubernetes]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS      REASON   AGE
pvc-56ba158b-d26d-486e-89e9-fac52bf28eca   20Gi       RWO            Retain           Bound    default/wp-pv-claim      rook-ceph-block            10s
pvc-7ee6d95b-d9d4-4c29-95cd-0502367def27   20Gi       RWO            Retain           Bound    default/mysql-pv-claim   rook-ceph-block            7s
[root@k8s-m kubernetes]# kubectl get pod 
NAME                               READY   STATUS              RESTARTS   AGE
dnsutils-ds-4ds7w                  1/1     Running             70         2d20h
dnsutils-ds-fgck6                  1/1     Running             68         2d20h
dnsutils-ds-tvcrp                  1/1     Running             68         2d20h
wcl-nginx-886b56745-74z2k          1/1     Running             1          2d20h
wcl-nginx-886b56745-8hwm9          1/1     Running             1          2d20h
wordpress-578744754c-79fhz         0/1     ContainerCreating   0          4m24s
wordpress-mysql-5b697dbbfc-9s7vc   0/1     ContainerCreating   0          4m20s

[root@k8s-m kubernetes]# kubectl describe pod wordpress-578744754c-79fhz
Name:           wordpress-578744754c-79fhz
Namespace:      default
Priority:       0
Node:           192.168.21.118/192.168.21.118
Start Time:     Fri, 06 Dec 2019 15:02:24 +0800
Labels:         app=wordpress
                pod-template-hash=578744754c
                tier=frontend
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/wordpress-578744754c
Containers:
  wordpress:
    Container ID:   
    Image:          wordpress:4.8-apache
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      WORDPRESS_DB_HOST:      wordpress-mysql
      WORDPRESS_DB_PASSWORD:  <set to the key 'password' in secret 'mysql-pass'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gq92d (ro)
      /var/www/html from wordpress-persistent-storage (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  wordpress-persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  wp-pv-claim
    ReadOnly:   false
  default-token-gq92d:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gq92d
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From                     Message
  ----     ------            ----                ----                     -------
  Warning  FailedScheduling  <unknown>           default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Warning  FailedScheduling  <unknown>           default-scheduler        pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled         <unknown>           default-scheduler        Successfully assigned default/wordpress-578744754c-79fhz to 192.168.21.118
  Warning  FailedMount       12m (x7 over 16m)   kubelet, 192.168.21.118  Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[default-token-gq92d wordpress-persistent-storage]: failed to get Plugin from volumeSpec for volume "pvc-56ba158b-d26d-486e-89e9-fac52bf28eca" err=no volume plugin matched
  Warning  FailedMount       90s (x57 over 16m)  kubelet, 192.168.21.118  Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[wordpress-persistent-storage default-token-gq92d]: failed to get Plugin from volumeSpec for volume "pvc-56ba158b-d26d-486e-89e9-fac52bf28eca" err=no volume plugin matched

**Comment by Madhu-1** [comment]
have you enabled the FLEX driver during operator deployment https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L161

**Comment by yq513** [comment]
> have you enabled the FLEX driver during operator deployment https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L161

Yes, please see my kubelet and operator.ymal configuration below,
I created the directory and enabled the configuration. Is it correct?

Also, I execute kubectl create -f operator.yaml
Without rook-ceph-agent pods,

If my configuration is incorrect, what is the correct configuration?

Created directory：
[root@k8s-m kubernetes]# cd /var/lib/kubelet/volumeplugins/
[root@k8s-m volumeplugins]# pwd
/var/lib/kubelet/volumeplugins

Added volume-plugin parameter：
[root@k8s-m kubernetes]# cat /opt/kubernetes/conf/kubelet.conf
KUBE_MASTER="--master=http://192.168.21.117:8080"
KUBELET_OPTS="--logtostderr=true
--log-dir=/var/log/kubernetes/kubelet
--v=4
--volume-plugin-dir=/var/lib/kubelet/volumeplugins \

ceph operator.ymal ：
name: FLEXVOLUME_DIR_PATH
value: "/var/lib/kubelet/volumeplugins"

**Comment by yq513** [comment]
I researched it for two weeks and solved it. The reason is that in operator.yaml, you need to understand the difference between the drive modes of CSI and FLEX. When you choose FLEX, you need to annotate the CSI configuration.
I have seen https://github.com/rook/rook/issues/4139 during configuration, and also commented below after resolving

**Comment by karthikvee** [comment]
Any ideas on how to resolve this: The error I posted is of a pod/of a deployment of redis.


```
Warning FailedScheduling 50m (x2 over 50m)  default-scheduler pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
Normal  Scheduled     50m         default-scheduler Successfully assigned default/redis-master-0 to knode03
Warning FailedMount    46m (x3 over 47m)  kubelet, knode03  Unable to attach or mount volumes: unmounted volumes=[redis-data], unattached volumes=[redis-data config redis-tmp-conf default-token-jmhvk health]: failed to get Plugin from volumeSpec for volume "pvc-bc8dfea5-cbb6-4f7b-89fa-c74e18f0d437" err=no volume plugin matched
```

I deployed rook+ceph as per official documentation


Tried few things like : 
1. restarting kubelet 
2. adding plugins directory to kubeadm config as part of kublet args
but still facing the issue

**sudo cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf**
``` 
#Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml --volume-plugin-dir=/var/lib/kubelet/plugins"
#This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
#This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use
#the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
Environment="cgroup-driver=systemd/cgroup-driver=cgroupfs"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS


```

**kubectl get nodes**
```
NAME      STATUS   ROLES    AGE   VERSION
kmaster   Ready    master   25h   v1.16.3
knode01   Ready    <none>   25h   v1.16.3
knode02   Ready    <none>   25h   v1.16.3
knode03   Ready    <none>   20h   v1.16.3

```
**kubectl exec -it rook-ceph-tools-86d9c9d647-jzrl2 sh -n rook-ceph**
**sh-4.2# ceph -s**
  ```
cluster:
    id:     53eb670b-491e-49b8-8882-a1972edcca77
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 22h)
    mgr: a(active, since 2h)
    mds: myfs:1 {0=myfs-a=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 20h), 3 in (since 20h)
 
  data:
    pools:   3 pools, 144 pgs
    objects: 33 objects, 12 KiB
    usage:   3.0 GiB used, 294 GiB / 297 GiB avail
    pgs:     144 active+clean
 
  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr
```
 
**sh-4.2# ceph osd status**
```
+----+---------+-------+-------+--------+---------+--------+---------+-----------+
| id |   host  |  used | avail | wr ops | wr data | rd ops | rd data |   state   |
+----+---------+-------+-------+--------+---------+--------+---------+-----------+
| 0  | knode01 | 1026M | 97.9G |    0   |     0   |    2   |   106   | exists,up |
| 1  | knode02 | 1026M | 97.9G |    0   |     0   |    0   |     0   | exists,up |
| 2  | knode03 | 1026M | 97.9G |    0   |     0   |    0   |     0   | exists,up |
+----+---------+-------+-------+--------+---------+--------+---------+-----------+
```

**kubectl get pods -n rook-ceph**
```
NAME                                                READY   STATUS              RESTARTS   AGE
csi-cephfsplugin-89w42                              3/3     Running             0          23h
csi-cephfsplugin-jcxqw                              3/3     Running             0          23h
csi-cephfsplugin-provisioner-6c7d6f4964-fqg6j       4/4     Running             0          23h
csi-cephfsplugin-provisioner-6c7d6f4964-qtbbk       4/4     Running             0          23h
csi-cephfsplugin-v7r4t                              3/3     Running             0          20h
csi-cephfsplugin-xpkdw                              3/3     Running             0          23h
csi-rbdplugin-8lf4n                                 3/3     Running             0          20h
csi-rbdplugin-hljfs                                 3/3     Running             0          23h
csi-rbdplugin-provisioner-6ff4dd4b94-jcxnw          5/5     Running             0          23h
csi-rbdplugin-provisioner-6ff4dd4b94-ldz2n          5/5     Running             0          23h
csi-rbdplugin-v59st                                 3/3     Running             0          23h
csi-rbdplugin-zm2s4                                 3/3     Running             0          23h
rook-ceph-crashcollector-kmaster-569f6bdfb8-5qhmb   1/1     Running             0          23h
rook-ceph-crashcollector-knode01-c9f55c589-rzqs5    1/1     Running             0          23h
rook-ceph-crashcollector-knode02-85f4c4bc68-rds87   1/1     Running             0          23h
rook-ceph-crashcollector-knode03-7cbc6c8795-jrb29   1/1     Running             0          20h
rook-ceph-mds-myfs-a-c5d8cdbdd-6rrn5                1/1     Running             0          22h
rook-ceph-mds-myfs-b-54db4bfb7f-xvtsb               1/1     Running             0          22h
rook-ceph-mgr-a-6c9644f844-xws27                    1/1     Running             0          23h
rook-ceph-mon-a-7cb445d49b-76jhd                    1/1     Running             0          23h
rook-ceph-mon-b-85b67c8d87-rhtwb                    1/1     Running             0          23h
rook-ceph-mon-c-7b77f5cf67-65gsg                    1/1     Running             0          23h
rook-ceph-operator-84b88645f5-x9zcx                 1/1     Running             0          3h48m
rook-ceph-osd-0-7c878cdfdb-tfc86                    1/1     Running             0          20h
rook-ceph-osd-1-5978c69699-k6cvh                    1/1     Running             0          20h
rook-ceph-osd-2-7d9dcb8456-v4gbs                    1/1     Running             0          20h
rook-ceph-osd-prepare-kmaster-z4zl7                 0/1     Completed           0          148m
rook-ceph-osd-prepare-knode03-kmlz8                 0/1     Completed           0          148m
rook-ceph-tools-86d9c9d647-jzrl2                    1/1     Running             0          23h
rook-discover-64pb7                                 1/1     Running             0          20h
rook-discover-7rhkk                                 1/1     Running             0          23h
rook-discover-dff5k                                 1/1     Running             0          23h
rook-discover-nxs9c                                 1/1     Running             0          23h
wordpress-mysql-b9ddd6d4c-l925l                     0/1     ContainerCreating   0          91m
```

**kubectl get namespaces**
```
NAME              STATUS   AGE
default           Active   25h
kube-node-lease   Active   25h
kube-public       Active   25h
kube-system       Active   25h
rook-ceph         Active   24h
```
 **kubectl get pv**
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS      REASON   AGE
pvc-60d36b7d-71ff-47b2-9993-00f5dcd3a67c   20Gi       RWO            Delete           Bound    rook-ceph/mysql-pv-claim            rook-ceph-block            92m
pvc-bc8dfea5-cbb6-4f7b-89fa-c74e18f0d437   8Gi        RWO            Delete           Bound    default/redis-data-redis-master-0   rook-ceph-block            79m
pvc-fce7e569-787b-477d-8520-9d2c57c8db04   8Gi        RWO            Delete           Bound    default/redis-data-redis-slave-0    rook-ceph-block            79m
```

 **kubectl get pvc**
```
NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
redis-data-redis-master-0   Bound    pvc-bc8dfea5-cbb6-4f7b-89fa-c74e18f0d437   8Gi        RWO            rook-ceph-block   79m
redis-data-redis-slave-0    Bound    pvc-fce7e569-787b-477d-8520-9d2c57c8db04   8Gi        RWO            rook-ceph-block   79m
```

 **kubectl get pv -n rook-ceph**
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS      REASON   AGE
pvc-60d36b7d-71ff-47b2-9993-00f5dcd3a67c   20Gi       RWO            Delete           Bound    rook-ceph/mysql-pv-claim            rook-ceph-block            93m
pvc-bc8dfea5-cbb6-4f7b-89fa-c74e18f0d437   8Gi        RWO            Delete           Bound    default/redis-data-redis-master-0   rook-ceph-block            80m
pvc-fce7e569-787b-477d-8520-9d2c57c8db04   8Gi        RWO            Delete           Bound    default/redis-data-redis-slave-0    rook-ceph-block            80m
ubuntu@kmaster:~/rook/cluster/examples/kubernetes/ceph$ kubectl get pvc -n rook-ceph
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
mysql-pv-claim   Bound    pvc-60d36b7d-71ff-47b2-9993-00f5dcd3a67c   20Gi       RWO            rook-ceph-block   93m
```

**Comment by ztl8702** [comment]
@Madhu-1 

>  any specific reason not to use CSI?

One reason to use flexVolume is that a.t.m. ceph-csi is not quite as convinent with flexVolume when it comes to mounting a fixed path on a shared CephFS filesystem to Pods. 

The (Rook v1.2 doc CephFS example)[https://rook.io/docs/rook/v1.2/ceph-filesystem.html#consume-the-shared-filesystem-k8s-registry-sample] creates a dynamic PV, which will be stored at some unpredictable directory `/csi/<some generated path>/` within cephfs root, and that directory be deleted if the PV is not retained.

Whereas, the (Rook v1.0 CephFS example)[https://rook.io/docs/rook/v1.0/ceph-filesystem.html#consume-the-shared-file-system-k8s-registry-sample] using flexVolume, results in a predictable directory in cephfs being mounted to the pod, and which will not be deleted after the pod is deleted.

With Rook v1.2 + ceph-csi, the way to achieve the same behaviour as Rook v1.0 with Ceph + Flex is to create a secret, a PV and a PVC, and reference the PVC in the pod. (See https://github.com/rook/rook/issues/4064#issuecomment-540044819) This isn't quite as declarative or convenient as the Rook v1.0 Ceph + Flex approach. 

@yq513 Thanks, this tip saved me when trying to re-enable flex after deploying Rook v1.2.0 (Ceph) with CSI.

> researched it for two weeks and solved it. The reason is that in operator.yaml, you need to  understand the difference between the drive modes of CSI and FLEX. When you choose FLEX, you need to annotate the CSI configuration.

**Comment by ftab** [comment]
I'm running into the same issue, but I've deployed it with the flex driver enabled and CSI drivers disabled. I've chosen to do this at this time because of #1169 not being finished for the CSI driver (I may need to expand the volumes, which is not currently possible with CSI)

I'm so confused because my setup is so similar in another location except for the number of replicas (I have only one in this setup I'm trying to do now, I have 3 in a setup that's working fine with rook 1.1 which was upgraded to from 0.9...)

I have tried this with 1.1.8 and 1.2.2 to no avail.

So for this, I only have one node for now. I provisioned the cluster with kubespray v2.11.0, all of the default group_vars except the below:
```
helm_enabled: true
kube_network_plugin: flannel
kube_proxy_mode: iptables
dns_min_replicas: 1
```

inventory:
```
[all]
cassiopeia ansible_host=xxxxxxxx etcd_member_name=etcdc

[kube-master]
cassiopeia

[etcd]
cassiopeia

[kube-node]
cassiopeia

[k8s-cluster:children]
kube-master
kube-node
```

`ansible-playbook cluster.yml -b -i inventory/mine/inventory.ini`

and after this was set up, the first thing I installed to the cluster was MetalLB to have the cluster pick up my IP for the LoadBalancer service I plan to deploy. (I edited my IP into place in the contrib/metallb/roles/provision/defaults/main.yml file)
`ansible-playbook contrib/metallb/metallb.yml -b -i inventory/mine/inventory.ini`

Then I install rook and set up the ceph cluster and storage class (waiting some time between each step to watch the pods deploy):

```sh
helm install --name rook-ceph --namespace rook-ceph rook-release/rook-ceph --version v1.2.2 --set agent.flexVolumeDirPath=/var/lib/kubelet/volume-plugins --set csi.enableRbdDriver=false --set csi.enableCephfsDriver=false --set enableFlexDriver=true
cd clusters/examples/kubernetes/ceph
cat <<EOF > cluster-cassiopeia.yaml
```
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.6
    allowUnsupported: true
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false  # requires Prometheus to be pre-installed
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  crashCollector:
    disable: false
  mgr:
    modules:
    # the pg_autoscaler is only available on nautilus or newer. remove this if testing mimic.
    - name: pg_autoscaler
      enabled: true
  storage:
    useAllNodes: true
    useAllDevices: false
    config:
      #databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      #journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
      #osdsPerDevice: "1" # this value can be overridden at the node or device level
    directories:
    - path: /var/lib/rook
#    nodes:
#    - name: "minikube"
#      directories:
#      - path: "/data/rook-dir"
#      devices:
#      - name: "sdb"
#      - name: "nvme01" # multiple osds can be created on high performance devices
#        config:
#          osdsPerDevice: "5"
```
```sh
EOF
kubectl apply -f cluster-cassiopeia.yaml
cat <<EOF > storageclass-cassiopeia.yaml
```
```yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  replicated:
    size: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.rook.io/block
parameters:
  blockPool: replicapool
  clusterNamespace: rook-ceph
  fstype: ext4 # xfs causes deadlocks. see https://github.com/rook/rook/issues/3132
# Works for Kubernetes 1.14+
allowVolumeExpansion: true
```
```sh
EOF
kubectl apply -f storageclass-cassiopeia.yaml
```

Here's my pods in rook-ceph as of now:
```
$ kubectl get po -n rook-ceph
NAME                                                   READY   STATUS      RESTARTS   AGE
rook-ceph-agent-w426x                                  1/1     Running     0          32m
rook-ceph-crashcollector-cassiopeia-58cc675bf9-f5tmj   1/1     Running     0          31m
rook-ceph-mgr-a-698664b657-nf5wp                       1/1     Running     0          32m
rook-ceph-mon-a-77cb858c86-74jlt                       1/1     Running     0          32m
rook-ceph-operator-854686c684-gpscx                    1/1     Running     0          34m
rook-ceph-osd-0-799d865644-jrfzm                       1/1     Running     0          31m
rook-ceph-osd-prepare-cassiopeia-t5jl7                 0/1     Completed   0          31m
rook-discover-h757w                                    1/1     Running     0          34m
```

Unfortunately all my PVCs are getting provisioned but then cannot be mounted. As the systemctl status says, no volume plugin matched.

systemctl status kubelet and operator logs:
https://pastebin.com/Ez2yeyyY

**Comment by ftab** [comment]
Face, meet palm.

My problem was that kubespray changed at some point. The default is now to use the same volume plugin dir as rook expects by default. I was telling it the wrong plugin dir.

**Comment by galexrt** [comment]
@ftab Would you mind creaeting a PR to update the flexvolume dir docs for the Kubespray version in which it changed?

**Comment by ftab** [comment]
@galexrt - done, see #4746 and #4747 

I made a separate issue for doc update since I think now that I know what happened I'm only tangentially related to what's happened to the other folks in this thread. They are explicitly configuring the flexvolume path in kubelet and the rook flexvolume path, and I was just configuring rook flexvolume path according to the doc, not explicitly setting a flexvolume path in kubelet or my kubespray config.

**Comment by galexrt** [comment]
Thanks! Closing in favor of #4746 and #4747 then.

**Comment by galexrt** [comment]
@karthikvee Not knowing in what environment you run, have you set your flexvolume directory `/var/lib/kubelet/plugin` on the operator Deployment?

In your case looking at the pod list, you seem to have CSI enabled (default since v1.1) which means that flexvolume is disabled. Do you want to use flexvolume instead of Ceph CSI? If so then you need to set the env vars on the operator Deployment to disable CSI and enable flexvolume again.

Also if you don't want to use flexvolume, make sure you are using CSI StorageClasses as can be see in the documentation https://rook.io/docs/rook/v1.2/ceph-block.html.
