### ISSUE TITLE
Rook Operator not deploying ceph common.yaml

### ISSUE THREAD

**Issue by evannorstrand** [rook/rook#4444]
**Is this a bug report or feature request?**

* Bug Report
**Bug Report**
Ceph cluster doesn't deploy with the necessary common.yaml secrets, crd's, etc.

579c546f5-78hrs_876f2eec-184d-11ea-b3be-bea1114cbc47  failed to provision volume with StorageClass "rook-ceph-block": error getting secret rook-ceph-csi in namespace rook-ceph: secrets "rook-ceph-csi" not found

**Expected behavior:**
Secrets are not found
**Deviation from expected behavior:**
Secrets should be found

**How to reproduce it (minimal and precise):**
Deploy a cluster using the helm chart operator, try and create a PVC. It will fail.

**Comment by travisn** [comment]
@evannorstrand What storageclass.yaml are you using? It's possible your yaml is out of date from the examples. The example uses a different secret name now as seen [here](https://github.com/rook/rook/blob/release-1.1/cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml#L32).

**Comment by evannorstrand** [comment]
Turns out I was using an older version of the YAML from a previous deployment. Used the new YAML, all is good.
