### ISSUE TITLE
Local storage support in Rook through a new LVM provider

### ISSUE THREAD

**Issue by gbartolini** [rook/rook#4453]
Add support in Rook for **dedicated Logical Volumes created using LVM**.

The primary use case is a **database management system like [PostgreSQL](https://www.postgresql.org/) that uses its own replication system for disaster recovery**. This also applies primarily in a private cloud context.

The basic idea is to define a **storage class for LVM that is able to manage LVM Volume Groups** as defined by Kubernetes Cluster administrators. Kubernetes **Persistent Volumes will correspond to LVM Logical Volumes** based on Persistent Volume Claims requested by an external operator (for example, the PostgreSQL operator).

This would ideally allow administrators to define one or more storage classes in the cluster, depending on storage capabilities and characteristics (for example, NVMe, SSD, rotational disks) and define block volumes that can then be used for data storage (for example, the PostgreSQL data directory).

Having an efficient and performing way with LVM to store data on the same host where the Pod is running increases **flexibility** for database users and opens up for **expansion of Kubernetes adoption** in those database workloads where the orchestrator is freed by replication and disaster recovery duties, such as PostgreSQL’s.

**Comment by yydzhou** [comment]
Will this come with a local volume dynamic provisioner?

**Comment by gbartolini** [comment]
Ideally, in terms of LVM management, physical volumes and volume groups are manually managed by the Kubernetes cluster administrators. An idea is that storage classes somehow map volume groups and make them available to the cluster.

Logically speaking, the provisioner will need to manage LVMs Logical Volumes as Persistent Volumes for Pods.

**Comment by satoru-takeuchi** [comment]
@yydzhou 

> Add support in Rook for dedicated Logical Volumes created using LVM.

Does it mean supporting LVM as the new storage provider? If true, what are the pros of supporting this feature not by normal CSI driver, but by Rook?

For example, there is a CSI driver for local volume. It also has a dynamic provisioner.
https://github.com/cybozu-go/topolvm

**Comment by travisn** [comment]
@gbartolini With the existence of local storage operators already outside Rook, my view is that we would not create a new local storage operator in Rook. As @satoru-takeuchi mentioned there is [TopoLVM](https://blog.kintone.io/entry/topolvm) and another one is [Local Storage Operator](https://github.com/openshift/local-storage-operator). There may also be others out there. Rather than creating another one in Rook it seems a better effort to support an existing one.
