### ISSUE TITLE
Ceph Object Store CRD is missing deviceClass for store pools in rook-ceph Helm Chart

### ISSUE THREAD

**Issue by macgyver603** [rook/rook#4459]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Cannot specify the `deviceClass` for the data and metadata pools in a `CephObjectStore` resource. The operator has all the code necessary to interpret `deviceClass` and apply it to the CRUSH rules when deploying the pools, but the value will get filtered out and set to `default` before deployment since it is missing from that CRD.

**Expected behavior:**
`CephObjectStore` CRD should include `deviceClass` as a property for `metadataPool` and `dataPool`

**Comment by travisn** [comment]
@macgyver603 The CephObjectStore internally calls the same pool implementation as the CephBlockPool, so all the settings such as `deviceClass` should already apply. Are you just referring to adding the `deviceClass` in the object.yaml example?
