### ISSUE TITLE
Issues related to plugin_watcher.go error could not find plugin for deleted file

### ISSUE THREAD

**Issue by kchakry** [rook/rook#4468]
Yes , I did search but nothing coming up.

**Is this a bug report or feature request?**

* Bug Report
* Feature Request

**Bug Report**

**Expected behavior:**

Normally when pod is deleted another pod will be created and pvc will be attache without any problem.

**Deviation from expected behavior:**

We have done the kuberenetes upgrade in other environment but never experienced this kind of problem and we not even able to replicate it.

**How to reproduce it (minimal and precise):**
 This is happening while in the process of kubernetes upgrade to 13.4. While pod is deleted and we have seen timeout of ceph and below are the errors.

' flexdriver: volume replicapool/pvc-45 has been attached and mounted

 ceph-volumeattacher: volume replicapool/pvc-45 is already attached. The device path is /dev/rbd2

plugin_watcher.go:120] error could not find plugin for deleted file /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-45/test-permissions when handling delete event: "/var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-45/test-permissions": REMOVE

plugin_watcher.go:115] error dial failed at socket /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-45/test-permissions, err: failed to dial socket /var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-45/test-permissions, err: context deadline exceeded when handling create event: "/var/lib/kubelet/plugins/ceph.rook.io/rook-ceph-system/mounts/pvc-45/test-permissions": CREATE'

' Was there any suggested method to follow Kubernetes upgrade which uses Rook-Ceph cluster without data corruption and without Ceph issues?'

**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Feature Request**

**Are there any similar features already existing:**

**What should the feature do:**

**What would be solved through this feature:**

**Does this have an impact on existing features:**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by galexrt** [comment]
>We have done the kuberenetes upgrade in other environment but never experienced this kind of problem and we not even able to replicate it.

@kchakry So are you able to reproduce the issue or not?

Please fill out the issue description with your environment information.
