### ISSUE TITLE
ceph: use more common keyring path

### ISSUE THREAD

**Issue by leseb** [rook/rook#4474]
Currently, all the daemons use a non-standard ceph path to mount the keyring secrets. Keys should either go into /etc/ceph including a proper naming or in /var/lib/ceph/$daemon/$id/.

**Comment by leseb** [comment]
Currently, we have `/etc/ceph` as a place holder for `rook-config-override` which forbids us to use this path to store keys...

**Comment by BlaineEXE** [comment]
> Currently, we have `/etc/ceph` as a place holder for `rook-config-override` which forbids us to use this path to store keys...

Correct. That is why it gets placed in `/etc/ceph/keyring`. I don't consider it wrong, and if we place it in `/var/lib/ceph/$daemon/$id`, then it will get persisted to disk for mons, an unnecessary security risk.

**Comment by leseb** [comment]
I think it's still nice to use a more conventional path for keys inside the container. Even though in practice we don't care :).
