### ISSUE TITLE
use rook v1.1.7 version errors

### ISSUE THREAD

**Issue by sunhuaxu** [rook/rook#4481]
kubectl get node
NAME              STATUS   ROLES    AGE     VERSION
192.168.123.141   Ready    master   7h25m   v1.15.6
192.168.123.142   Ready    node     31m     v1.15.6
192.168.123.143   Ready    node     31m     v1.15.6

kubectl apply -f common.yaml
kubectl apply -f operator.yaml
kubectl get pod -n rook-ceph-system -o wide
提示：No resources found.

**Comment by leseb** [comment]
Please re-open using the bug template.

**Comment by sunhuaxu** [comment]
change template?
