### ISSUE TITLE
CSI and flex drivers are not removed when operator settings change

### ISSUE THREAD

**Issue by PCatinean** [rook/rook#4490]
I installed the operator via helm initially with the default arguments including csi.enableCephfsDriver = true.

After upgrade I changed this parameter to False but the pods for cephfs are still present.

If there are no active mounts on cephfs the operator should remove the pods.

**Comment by Madhu-1** [comment]
@travisn do we need to remove cephfs/rbd and rbd deployment and daemonset?

**Comment by travisn** [comment]
The operator currently only enables the CSI drivers, but doesn't actively disable them.
