### ISSUE TITLE
ceph: osd memory requested for pod is automatically computed if not set if IsAtLeastNautilus

### ISSUE THREAD

**Issue by ashangit** [rook/rook#4492]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
If ceph release IsAtLeastNautilus and no memory resources have been requested for osd the operator should assign an appropriate memory resource to it something like : <memory available on the server> - <a safe % or/fallback fix size to keep for the server>/<nb osds on the server>

**What is use case behind this feature:**
Since Nautilus the osd_memory_target is computed based on the cgroup limit which means that if no memory resource is requested, each osd can "see" the whole server memory and set the osd_memory_target to 80% of that memory which leads to osd beeing constantly killed by OOM killer.
It will provide to benefits:
* ensure stable run of osds out of the box
* if the cluster run on heterogeneous servers each osd will be assigned a different memory resources so better usingh the available memory

**Environment**:

**Comment by leseb** [comment]
The problem with falling back with defaults if no resources are specified is that Rook has no idea which value to set. Setting this value requires a bit of knowledge like number of CPU, amount of memory, use case of the platform, expected load. It's just too much to compute and we prefer to leave that to the admin.
Thus, we decided this is not something the Rook operator will implement.

You can always set the resource value from your cluster CR.

Thanks!

**Comment by ashangit** [comment]
Ok, so perhaps improving the documentation on that area will be fine as the osd resource memory limit doesn't seems to be optional with nautilus if there is more than one osd per host.
No?

**Comment by leseb** [comment]
What do you mean by "is not optional"? AFAIK it has always been optional.
If not running on Nautilus and memory limit is not set then we don't apply `--osd-memory-target`.

Am I missing something?

**Comment by ashangit** [comment]
What I mean is if running on nautilus the osd-memory-target is computed from the cgroup memory, right?
So if we don't set the resource memory it will ends up for each osd to automatically set osd-memory-target to 80% of the RAM available on the server. Which leads to thpose opsd beeing killed by oom killer when there are more than one running on a server
For ex. with a 376G server and 12 osd each osds have the osd-memory-target set more than 300G....
So with nautilus the memory resource must be set otherwise oom killer will kill osd leading to not stable cluster. That's why I'm saying "is not optional"
But perhpas I misunderstood the osd-memory-target behaviour and cgroup limit with nautilus :(

**Comment by leseb** [comment]
> What I mean is if running on nautilus the osd-memory-target is computed from the cgroup memory, right?

No, if running on Nautilus `osd-memory-target` is computed from the env variable `POD_MEMORY_REQUEST` or `POD_MEMORY_LIMIT`. If nothing is set, the osd will calculate it based on the amount of memory, it's not looking at cgroup.

> So if we don't set the resource memory it will ends up for each osd to automatically set osd-memory-target to 80% of the RAM available on the server. Which leads to thpose opsd beeing killed by oom killer when there are more than one running on a server
> For ex. with a 376G server and 12 osd each osds have the osd-memory-target set more than 300G....

That's pure theory IMHO, it's up to 300G. I've never seen an OSD taking that amount of memory.

> So with nautilus the memory resource must be set otherwise oom killer will kill osd leading to not stable cluster. That's why I'm saying "is not optional"
> But perhpas I misunderstood the osd-memory-target behaviour and cgroup limit with nautilus :(

You're right this could happen, this behavior is not different from when running on non-container. That's why you should be setting the resources in your CR.
