### ISSUE TITLE
failed to enable mgr module pg_autoscaler

### ISSUE THREAD

**Issue by sp98** [rook/rook#4497]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Error while enabling pg-autoscalar 

**Expected behavior:**
pg-autoscaler should be enabled successfully 

**How to reproduce it (minimal and precise):**

1. Kubectl apply common.yaml
2. Kubectl apply cluster-on-pvc.yaml 
(Enable mgr in cluster-on-pvc.yaml file by adding following
```mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
```
)
3. Kubectl apply operator.yaml. 
(use rook/ceph:v1.2.0-beta.0 image)
4. Kubectl apply pool.yaml
5. Observe the ceph status. 

Ceph Status output: 
``` sh-4.2$ ceph --conf=/var/lib/rook/openshift-storage/openshift-storage.config  status 
  cluster:
    id:     57127232-bf52-4d54-ada4-08cb120c9df8
    health: HEALTH_WARN
            too few PGs per OSD (24 < min 30)
 
  services:
    mon: 3 daemons, quorum a,b,c (age 7m)
    mgr: a(active, since 7m)
    mds: ocs-storagecluster-cephfilesystem:1 {0=ocs-storagecluster-cephfilesystem-b=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 5m), 3 in (since 5m)
 
  data:
    pools:   3 pools, 24 pgs
    objects: 91 objects, 72 MiB
    usage:   3.0 GiB used, 3.0 TiB / 3.0 TiB avail
    pgs:     24 active+clean
 
  io:
    client:   1.2 KiB/s rd, 7.7 KiB/s wr, 2 op/s rd, 0 op/s wr
 
sh-4.2$ 
```

Rook-ceph logs: 
```
019-12-12 13:43:19.869569 E | op-mgr: failed modules: mgr module(s) from the spec. exit status 2
failed to mgr module enable for pg_autoscaler
github.com/rook/rook/pkg/daemon/ceph/client.enableModule
	/home/rook/go/src/github.com/rook/rook/pkg/daemon/ceph/client/mgr.go:74
github.com/rook/rook/pkg/daemon/ceph/client.MgrEnableModule
	/home/rook/go/src/github.com/rook/rook/pkg/daemon/ceph/client/mgr.go:30
github.com/rook/rook/pkg/operator/ceph/cluster/mgr.(*Cluster).configureMgrModules
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/mgr.go:316
github.com/rook/rook/pkg/operator/ceph/cluster/mgr.(*Cluster).configureMgrModules-fm
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/mgr.go:265
github.com/rook/rook/pkg/operator/ceph/cluster/mgr.startModuleConfiguration.func1
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/mgr.go:275
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
failed to enable mgr module pg_autoscaler
github.com/rook/rook/pkg/operator/ceph/cluster/mgr.(*Cluster).configureMgrModules
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/mgr.go:317
github.com/rook/rook/pkg/operator/ceph/cluster/mgr.(*Cluster).configureMgrModules-fm
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/mgr.go:265
github.com/rook/rook/pkg/operator/ceph/cluster/mgr.startModuleConfiguration.func1
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/mgr.go:275
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
```

Ceph Tracker issue for this behavior: 
https://tracker.ceph.com/issues/38941

Possible Root cause:  " ceph mgr module enable <>` is happening very quickly after ceph mgr starts."

Possible solution:  wait for  ceph mgr dump | jq .available = "true" , before enabling pg-autoscalar.
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): - rook/ceph:v1.2.0-beta.0
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.14
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift 4.2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
I also saw this issue yesterday. The mgr modules defined in the CR don't have a retry. On the first run the modules will fail if they are enabled too soon after the mgr daemon is started. In my cluster enabling it a second time succeeded. Other mgr modules have a retry, but we need to add one for this.
