### ISSUE TITLE
Refusing to upgrade with skipUpgradeChecks: true

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4506]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook is refusing to upgrade ceph with `skipUpgradeChecks: true`:

```
2019-12-13 23:34:54.239557 I | cephconfig: generated admin config in /var/lib/rook/rook
2019-12-13 23:34:54.239834 I | exec: Running command: ceph versions --connect-timeout=15 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/044178800
2019-12-13 23:34:54.660288 I | op-cluster: image spec version 14.2.5 nautilus is higher than the running cluster version 14.2.4 nautilus, upgrading
2019-12-13 23:34:54.660417 I | exec: Running command: ceph status --connect-timeout=15 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring --format json --out-file /tmp/595899407
2019-12-13 23:34:55.167911 E | op-cluster: unknown ceph major version. ceph status in namespace rook is not healthy, refusing to upgrade. fix the cluster and re-edit the cluster CR to trigger a new orchestation update
```

**Expected behavior:**
Rook performs upgrade

**How to reproduce it (minimal and precise):**
Have cluster unhealthy. Try upgrade ceph version.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
1.1.7
* Kubernetes version (use `kubectl version`):
1.16.3

**Comment by leseb** [comment]
That's a different code path and perhaps `skipUpgradeChecks` is misleading here but `skipUpgradeChecks` means "Rook won't perform any `ok-to-stop` Ceph calls on each daemon before restarting it".

So Ceph being healthy is something different. So what's you're seeing is expected.

**Comment by travisn** [comment]
@dimm0 What ceph image are you using? I wouldn't expect the message `unknown ceph major version` with a `v14.2.5` ceph image.

**Comment by dimm0** [comment]
I was using 14.2.4, and first time I think it detected correctly. Not sure what happened here

>So Ceph being healthy is something different. So what's you're seeing is expected.

Can this option be also extended to the ceph upgrades? If ceph is broken, and new version is supposed to fix this, then I need an option to force the upgrade... Otherwise I'm stuck with the unhealthy cluster (or have to do it manually)

**Comment by leseb** [comment]
It's the first time I'm seeing this, out of curiosity what's broken and what's the fix?
I think it makes sense to extend this if you really know what you're doing.

**Comment by leseb** [comment]
hum actually I was wrong, it's already the default behavior, you should be able to force the upgrade with `SkipUpgradeChecks` to true.

**Comment by dimm0** [comment]
Ok, so why it didn't let me then? `unknown ceph major version`?

**Comment by travisn** [comment]
Ah, it looks like in the code `unknown ceph major version` is just a generic message for any error, so we can ignore it. The key is that the cluster wasn't healthy. @leseb This error should be ignored if `skipUpgradeChecks: true`, right?

**Comment by BlaineEXE** [comment]
Adding this to v1.2 release.

**Comment by dimm0** [comment]
@leseb 

> It's the first time I'm seeing this, out of curiosity what's broken and what's the fix?

https://tracker.ceph.com/issues/42223

**Comment by BlaineEXE** [comment]
From what is in the code, I don't see how the observed behavior is possible if `skipUpgradeChecks` is set. This was added with the commit that added the `skipUpgradeChecks` CR property and should have been there all along.

```go
		if !cephHealthy {
			if c.Spec.SkipUpgradeChecks {
				logger.Warning("ceph is not healthy but SkipUpgradeChecks is set, forcing upgrade.")
			} else {
				return errors.Errorf("ceph status in namespace %s is not healthy, refusing to upgrade. fix the cluster and re-edit the cluster CR to trigger a new orchestation update", c.Namespace)
			}
		}
```

**Comment by dimm0** [comment]
Is it possible that the operator is not re-reading the flag before updating?

**Comment by BlaineEXE** [comment]
Try an operator restart to check if you haven't already.

**Comment by dimm0** [comment]
It already updated the cluster during the weekend, when it became healthy again.. So can't check unfortunately

**Comment by BlaineEXE** [comment]
Okay. Then I will close this issue since I don't see anything to fix. Please feel free to reopen if it happens again or if there is more relevant info.

**Comment by leseb** [comment]
> Ah, it looks like in the code `unknown ceph major version` is just a generic message for any error, so we can ignore it. The key is that the cluster wasn't healthy. @leseb This error should be ignored if `skipUpgradeChecks: true`, right?

Yes.
