### ISSUE TITLE
build: create a symbol server hosted in S3

### ISSUE THREAD

**Issue by bassam** [rook/rook#451]
we should move the symbols to S3 and have them indexed by build-id. `gdb` has support for loading symbols from a symbol server.

**Comment by DanKerns** [comment]
A scan of the GDB documentation didn't explain how to do this.  Are you sure it's possible?

In any case just having the symbols somewhere (ex: s3) and indexed by build-id would be awesome.

**Comment by bassam** [comment]
yes it does not look like its possible. closing.
