### ISSUE TITLE
Recommendations for the Ceph operator upgrade

### ISSUE THREAD

**Issue by travisn** [rook/rook#4519]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
After reviewing the changes needed for #4518 and looking through the upgrade path in the Ceph operator, here are a few thoughts on how we can simplify the upgrade path.

1. The decision to call the upgrade checks should be based purely on whether the pod spec is going to be updated. If the pod spec is not being updated, the pod would not be restarted and we have no reason to perform the upgrade check.
2. After the first bullet is implemented, we have no reason to pass around the `isUpgrade` flag anywhere. We should be able to remove this flag. 
3. If mons are successfully upgraded, the other daemons should all proceed to attempt the upgrade. Even if some OSDs fail the upgrade, the MDS, RGW, and other daemons should all be updated. I believe this is the behavior already, but we should confirm. Within each daemon type we may want to prevent an upgrade from continuing if one daemon is not healthy after the upgrade, but I don't think we want one daemon type to affect another.

**Comment by leseb** [comment]
> **Is this a bug report or feature request?**
> 
> * Feature Request
> 
> **What should the feature do:**
> After reviewing the changes needed for #4518 and looking through the upgrade path in the Ceph operator, here are a few thoughts on how we can simplify the upgrade path.
> 
> 1. The decision to call the upgrade checks should be based purely on whether the pod spec is going to be updated. If the pod spec is not being updated, the pod would not be restarted and we have no reason to perform the upgrade check.

I don't think there is any logic in k8s to get a diff of 2 objects but we could search/build it.

> 2. After the first bullet is implemented, we have no reason to pass around the `isUpgrade` flag anywhere. We should be able to remove this flag.

Agreed.

> 3. If mons are successfully upgraded, the other daemons should all proceed to attempt the upgrade. Even if some OSDs fail the upgrade, the MDS, RGW, and other daemons should all be updated. I believe this is the behavior already, but we should confirm. Within each daemon type we may want to prevent an upgrade from continuing if one daemon is not healthy after the upgrade, but I don't think we want one daemon type to affect another.

There is no effect per se but since they are all part of the same orchestration flow then yes there are dependencies.
