### ISSUE TITLE
Enable dashboard with external ceph cluster

### ISSUE THREAD

**Issue by tuchinsky** [rook/rook#4521]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

If use rook with external ceph cluster - ceph dashboard does not deploying by operator. Need possibility to use ceph dashboard with external cluster

**Environment**:

ceph 14.2.4

rook 1.1.8

**Comment by travisn** [comment]
@tuchinsky Rook does not deploy the mons, mgr, or osds if it is an external cluster. So the dashboard will only be available with the mgr that is running in the external cluster. Is the dashboard not running in the external cluster?

**Comment by tuchinsky** [comment]
@travisn We want to have access to the ceph dashboard via kubernetes ingress and manage it from CR

**Comment by leseb** [comment]
@tuchinsky sorry but that's out of scope for the external functionality. Won't fix. Thanks.
