### ISSUE TITLE
Manager pod fails to update service monitor and deploy prometheus rule after rook-operator is restarted in the cluster.

### ISSUE THREAD

**Issue by vbnrh** [rook/rook#4528]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook fails to update/deploy the prometheus rule and service monitor

**Expected behavior:**
Rook should successfully detect service monitor & prometheus and update/deploy them accordingly.

**How to reproduce it:**

1. Deploy rook onto kubernetes cluster and wait for all the pods to be up
2. Scale down the rook-ceph-operator to 0 replicas and then scale it up to 1 again
```
oc scale --replicas=0 deployment/<your deployment> -n <your project>
oc scale --replicas=1 deployment/<your deployment> -n <your project>
```
3. On checking the logs we find the errors as below. 

Rook operator logs

```
2019-12-17 10:09:08.057532 E | op-mgr: failed to enable service monitor. service monitor could not be enabled. failed to update servicemonitor. resource name may not be empty
W1217 10:09:08.059014       7 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2019-12-17 10:09:08.075615 E | op-mgr: failed to deploy prometheus rule. prometheus rule could not be deployed. failed to update prometheusRule. prometheusrules.monitoring.coreos.com "prometheus-ceph-v14-rules" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

```

**Environment**:
* OS (e.g. from /etc/os-release): Fedora 30
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.1.4-27.gf20c056
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.4
* Kubernetes version (use `kubectl version`): openshift-clients-4.2.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift

**Comment by jmolmo** [comment]
Hi @vbnrh, as we commented this does not affect functionality, the service monitor and the prometheus rule already exits, and what we are seeing is just the errors in the log file when the operator is trying to create them again. Probably the only thing needed is to improve the log messages to make clear that "the work is done" .
