### ISSUE TITLE
Ignore removable devices for OSD deployment

### ISSUE THREAD

**Issue by bmillemathias-1a** [rook/rook#4529]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
We have a set of HP servers that expose an virtual embedded USB storage 8Gb drive, which was used as storage for OSD when we deployed rook/ceph, but as removable drive it should not.
as a workaround we setup a udev rule to prevent access to this device, but I think it should not be necessary to do that, except specfically requested.

**Expected behavior:**
Ignore removable drives for OSD deployment.

**How to reproduce it (minimal and precise):**
Deploy rook / ceph on bare metal with usb removable storage
we used the default cluster.yaml file

**File(s) to submit**:
* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

**Environment**:
* OS (e.g. from /etc/os-release): rhcos 4.2
* Kernel (e.g. `uname -a`): 2.6.78-80.11.2.el8_0.x86_64
* Cloud provider or hardware configuration: Bare metal HP DL 360 class
* Rook version (use `rook version` inside of a Rook Pod): 1.1.7
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.4
* Kubernetes version (use `kubectl version`):  v1.14.0+724e12f93f
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN Reduced data availability: 1 pg inactive`

**Comment by travisn** [comment]
@bmillemathias-1a To configure which devices Rook uses to create OSDs, please see the options in the [storage selection](https://rook.io/docs/rook/v1.2/ceph-cluster-crd.html#storage-selection-settings) topic. The default cluster.yaml is just an example and you will need to configure the settings according to your needs.

**Comment by BlaineEXE** [comment]
I don't think we can say exclusively that there is no use case for removable USB devices.

**Comment by leseb** [comment]
From an OS perspective, it's hard to make a distinction between an actual drive or a USB dongle. So the only thing we can do is treat by size or using excluding filters.
Just like Travis mentioned we have documentation for this, so I'm closing this.

**Comment by bmillemathias-1a** [comment]
> From an OS perspective, it's hard to make a distinction between an actual drive or a USB dongle

I don't know what are the OSes you target but there is a "removable" property available in udev for devices that's why I suggested such filter could be added by default.

**Comment by leseb** [comment]
> > From an OS perspective, it's hard to make a distinction between an actual drive or a USB dongle
> 
> I don't know what are the OSes you target but there is a "removable" property available in udev for devices that's why I suggested such filter could be added by default.
> 
> ```
> [bmillemathias@fedoravm ~]$ udevadm info --attribute-walk --name=/dev/sda | grep removable
>     ATTR{removable}=="0"
> ```

Unfortunately, our filter does not work with udev. The only thing we do is look at the naming on `/dev`, that's why I meant it's hard to tell is `/dev/sda` is an actual drive or a USB key.

**Comment by bmillemathias-1a** [comment]
> I meant it's hard to tell is `/dev/sda` is an actual drive or a USB key.

Yes exactly, on bare metal the usb drive can even change name over reboot.
does supporting udev filters could be a sensible feature request ?

**Comment by leseb** [comment]
The goal is to ultimately rely on `ceph-volume` to validate devices. I have some code for this pending. I don't think we went to go to the business of introspecting devices again. So c-v has filters already if they need to be expanded/altered/disabled then it's more a c-v feature request at this point. Once it's there we can expose those.
