### ISSUE TITLE
OSD pod fails to start when using disk encryption with rook 1.2

### ISSUE THREAD

**Issue by stefanfritsch** [rook/rook#4558]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

After the upgrade from 1.1 to 1.2 the encrypted OSDs fail to come up.

**Expected behavior:**

The cluster works after the upgrade.

**How to reproduce it (minimal and precise):**

Create an encrypted cluster in 1.0 then upgrade to 1.1 and then to 1.2 following the docs.

**Logs of activate-osd**:

```
+ OSD_ID=3
+ OSD_UUID=dad3f9a1-531f-46c4-9a08-86ed73e3268b
+ OSD_STORE_FLAG=--bluestore
++ mktemp -d
+ TMP_DIR=/tmp/tmp.UDQegCH1qj
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-3
+ ceph-volume lvm activate --no-systemd --bluestore 3 dad3f9a1-531f-46c4-9a08-86ed73e3268b
Running command: /bin/ceph --cluster ceph --name client.osd-lockbox.dad3f9a1-531f-46c4-9a08-86ed73e3268b --keyring /var/lib/ceph/osd/ceph-3/lockbox.keyring config-key get dm-crypt/osd/dad3f9a1-531f-46c4-9a08-86ed73e3268b/luks
 stderr: Error initializing cluster client: ObjectNotFound('error calling conf_read_file',)
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 9, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
    self.main(self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 341, in main
    self.activate(args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 265, in activate
    activate_bluestore(lvs, no_systemd=args.no_systemd)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 151, in activate_bluestore
    dmcrypt_secret = encryption_utils.get_dmcrypt_key(osd_id, osd_fsid)
  File "/usr/lib/python2.7/site-packages/ceph_volume/util/encryption.py", line 138, in get_dmcrypt_key
    raise RuntimeError('Unable to retrieve dmcrypt secret')
RuntimeError: Unable to retrieve dmcrypt secret
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS with the hwe kernel
* Kernel (e.g. `uname -a`): 5.0.0-37-generic
* Rook version (use `rook version` inside of a Rook Pod): 1.2.0 not working
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.4
* Kubernetes version (use `kubectl version`): v1.15.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Broken

**Comment by leseb** [comment]
Mouarf looks like the encrypted activate needs to read the config file. Looking into it.

**Comment by stefanfritsch** [comment]
This can be fixed by editing the osd deployment and adding the following to the `env` section of the `activate-osd` `initContainers`:

```
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
              optional: false
        - name: CEPH_ARGS
          value: -m $(ROOK_CEPH_MON_HOST)
```

And this to the `volumeMounts` of the same `initContainers`:

```
        - mountPath: /etc/ceph
          name: rook-config-override
          readOnly: true
```

Unfortunately this is not permanent and there is no easy fix using just kubernetes. Instead it has to be fixed in the source and the operator has to be recompiled and that new version applied. 

I.e., we can only hope for a quick 1.2.1 hotfix. Until then the installation will again destroy itself every time the operator touches the deployments.

Could you please add a big warning to the 1.2.0 release that it should not be applied to encrypted clusters?

**Comment by leseb** [comment]
@stefanfritsch I don't think we will be able to release a 1.2.1 quickly since everyone is almost on leave. I built a fix on top of 1.2, in the meantime here: `leseb/testing:fix-4558` if you're interested.

**Comment by stefanfritsch** [comment]
Hi @leseb,

thank you very much. Unfortunately your fix is not working. I still need to add

```
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
              optional: false
```

Could you please reopen?

**Comment by leseb** [comment]
Rargh!! Yes... Sending a new PR for this.

**Comment by stefanfritsch** [comment]
Apart from that, many, many thanks a lot for the quick `leseb/testing:fix-4558` build. 👍 

I hope you can provide one for the fix with `ROOK_CEPH_MON_HOST` as well.

It's not a nice feeling, knowing that the cluster can go offline any time if the operator relaunches the osd pods. It's not exactly production but a few people might notice. And the bug should affect more people as well.

**Comment by leseb** [comment]
Yes sorry about that, I should have paid more attention, so many things to finish before going on PTO. I just built `leseb/testing:fix-4558-2` I think this one is good now. Let's hope!

Yeah sorry about this issue, we should have caught that from our CI... We need to add an encrypted test.

**Comment by stefanfritsch** [comment]
Hi,

unfortunately, it's still not working. 

It has to be defined in this order:
```
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
              optional: false
        - name: CEPH_ARGS
          value: -m $(ROOK_CEPH_MON_HOST)
```

But it looks like this:
```
        - name: CEPH_ARGS
          value: -m $(ROOK_CEPH_MON_HOST)
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
```

This results in the error:

```
Running command: /bin/ceph --cluster ceph --name client.osd-lockbox.d6fc302c-b8a7-4513-8479-6908fbf41673 --keyring /var/lib/ceph/osd/ceph-5/lockbox.keyring config-key get dm-crypt/osd/d6fc302c-b8a7-4513-8479-6908fbf41673/luks
 stdout: server name not found: $(ROOK_CEPH_MON_HOST) (Name or service not known)
 stderr: unable to parse addrs in '$(ROOK_CEPH_MON_HOST)'
 stderr: [errno 22] error connecting to the cluster
```

**Comment by leseb** [comment]
Please try: `leseb/testing:fix-4558-3`.

**Comment by stefanfritsch** [comment]
That worked! Thanks so much. 

I'll put your image in the first post.
