### ISSUE TITLE
Insecure PRNG used to generate dashboard password

### ISSUE THREAD

**Issue by travisn** [rook/rook#4571]
**Is this a bug report or feature request?**
* Bug Report

Follow-up from security review with [TrailOfBits](https://www.trailofbits.com/):

When generating the Ceph dashboard username and password, the m​ ath/rand​ package is used to create the random values composing the password. However, the m​ ath/rand package is cryptographically insecure, which could allow an attacker to abuse the values it generates.

Need to follow a password standard for this, but it might be as simple as making it 20 characters long and adding special characters. 

<img width="852" alt="Screen Shot 2019-12-20 at 12 32 17 PM" src="https://user-images.githubusercontent.com/1048514/71287158-c76fa900-2324-11ea-81f7-735f44b28953.png">

**Comment by nizamial09** [comment]
How about instead of using `math/rand` package, we can use `crypto/rand` package to generate the Password. Its more secure and uses CSPRNG - Cryptographycally Secure Pseudo Random Number Generator. Its slower than `math/rand` but it provides the necessary security while generating a password.

**Comment by sebastian-philipp** [comment]
cc @lenzgr
