### ISSUE TITLE
Use a stronger hash algorithm for generating volume names

### ISSUE THREAD

**Issue by travisn** [rook/rook#4572]
**Is this a bug report or feature request?**
* Bug Report

Follow-up from security review with [TrailOfBits](https://www.trailofbits.com/):

MD5 is used to generate part of a volume name. Due to the ease of creating an MD5 collision, an attacker could generate an input that collides with an existing volume.

<img width="855" alt="Screen Shot 2019-12-20 at 12 36 33 PM" src="https://user-images.githubusercontent.com/1048514/71287359-6eecdb80-2325-11ea-97c4-19cc9c6e6729.png">

**Comment by crombus** [comment]
I wish to take up this issue

**Comment by leseb** [comment]
> I wish to take up this issue

It's yours now.
