### ISSUE TITLE
Ceph: Missing input and output encodings

### ISSUE THREAD

**Issue by travisn** [rook/rook#4575]
**Is this a bug report or feature request?**
* Bug Report

Follow-up from security review with [TrailOfBits](https://www.trailofbits.com/):

Across the Rook codebase there are components that will create structured content such as shell commands or JSON without a proper encoder, opting instead for ​sprintf​ or other similar construction methods. This could lead to an attacker-controlled input to influence the final result of the structured content in a malicious or unintended way.

<img width="851" alt="Screen Shot 2019-12-20 at 12 44 04 PM" src="https://user-images.githubusercontent.com/1048514/71287750-6c3eb600-2326-11ea-85c2-f018f280e82e.png">

Recommendation
Short term, use proper encoders to create structured content. Ensure values are properly escaped and validated.
Long term, centralize input and output encoding and decoding. Avoid construction and parsing outside of these central locations to ensure validations propagate throughout the project.

**Comment by crombus** [comment]
I wish take this up

**Comment by leseb** [comment]
> I wish take this up

Next time, don't ask, if there is no assignee and no PR just take it and leave a message here. Thanks.

**Comment by travisn** [comment]
After looking closer at this issue...
- If user input isn't being used, we are fine to use sprintf or other simple string construction methods. 
- The two examples above don't appear to involve user input so I don't believe we need a change for those.
- The only way users provide input to Rook is through the CRs. We need to search for other places where json might be constructed with CR input, if any.
- If we confirm json construction doesn't take input from the CR, let's add a comment next to the formatting code so we know for future reference that it is safe.
