### ISSUE TITLE
Remove use of MkdirAll

### ISSUE THREAD

**Issue by travisn** [rook/rook#4579]
**Is this a bug report or feature request?**
* Bug Report

Follow-up from security review with [TrailOfBits](https://www.trailofbits.com/):

The application makes use of `MkdirAll()`​, which has a subtle semantic issue: Errors are not returned when a directory exists but is not of the requested permission. This may lead to a situation wherein an attacker has created directories prior to Rook, and retains control of these directories. Examples of such locations are noted within the list above.

For example, Figure TOB-ROOK-006.1 shows how missing directories will be created with with ​0755​ permissions if they do not already exist.

<img width="849" alt="Screen Shot 2019-12-20 at 3 06 43 PM" src="https://user-images.githubusercontent.com/1048514/71295705-5affa480-233a-11ea-9d81-4d6cf57dbba4.png">

**Recommendation**
Short term, audit all locations within the codebase, to ensure the correct file system permissions are used. These should be the most narrow permissions possible; for example, wherever possible, change ​0644​ (group and world readable, user writable and readable) into 0​ 600​ (only the owner may read). This will ensure that only the user executing Rook will be able to access sensitive information.

**Comment by ashishranjan738** [comment]
i would like to work on this @travisn

**Comment by nizamial09** [comment]
> i would like to work on this @travisn

@ashishranjan738 Sorry. But I was already working on a similar issue related to this and made PR earlier.

**Comment by ashishranjan738** [comment]
not an issue @nizamial09 I will pick something else to work on.

**Comment by nizamial09** [comment]
@travisn While running the gosec tool, wherever the 0755 permission is coded, it is expecting a 0750 instead. This is the case for most of the directory permission that is set. What I am concerned is if we change the set permission, will it affect the overall working of the rook operator?

**Comment by nizamial09** [comment]
@ashishranjan738 Thank you.

**Comment by subhamkrai** [comment]
I believe #3765 resolve this as all the permission related issues checked by Gosec CI and we are getting a green check. And we have to use `MkdirAll` as if we use `mkdir` to create these nested directories individually, next time when loop will go and try to `mdkir` it will return `err` that `directory already exists` and we don't want to fail in this scenario.

**Comment by travisn** [comment]
> I believe #3765 resolve this as all the permission related issues checked by Gosec CI and we are getting a green check. And we have to use `MkdirAll` as if we use `mkdir` to create these nested directories individually, next time when loop will go and try to `mdkir` it will return `err` that `directory already exists`.

Agreed, let's close this since the minimal permissions are now being applied with the other changes. The remaining usages of `MkdirAll()` appear to be inside the container or else in test code where we have control of the filesystem.
