### ISSUE TITLE
When using encryption in rook i have to attach new volume every time i reinstall rook.

### ISSUE THREAD

**Issue by shikhar7** [rook/rook#4611]
I am using rook 1.1 with encryption when i am trying to re deploy rook after clearing the hostDirectoryPath the osd pods does not come up it says that volume attached is still being used.

So in order to deploy rook again i have to attach new volume.

Is there some way i can format or clean my previously attached volume.I am using rhel 7.6.

The screen shot of command lsblk after installing rook is: 
![image](https://user-images.githubusercontent.com/18174818/71768775-8344f100-2f3f-11ea-899b-4e27231eda87.png)

**Comment by travisn** [comment]
@shikhar7 Did you clean up the devices as described in the [Cleanup doc](https://rook.github.io/docs/rook/v1.3/ceph-teardown.html#delete-the-data-on-hosts)?
