### ISSUE TITLE
LIB_MODULES_DIR_PATH doesn't seem to propagate to csi-rdbplugin

### ISSUE THREAD

**Issue by edude03** [rook/rook#4622]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook `csi-rbdplugin` daemonset is created mounting `/lib/modules` for the `lib-modules` volume mount, despite setting `LIB_MODULES_DIR_PATH` to a different value in https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml

**Expected behavior:**
csi-rbdplugin should honor the `LIB_MODULES_DIR_PATH` setting. 

**How to reproduce it (minimal and precise):**
Deploy rook according to the documentation, using common.yaml and operator.yaml from examples.

Change the `LIB_MODULES_DIR_PATH` in operator.yaml. 

Notice that when when the csi-rbdplugin daemonset is deployed it still use `/lib/modules`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): 
* Kernel (e.g. `uname -a`): 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
@edude03 currently CSI is not handling lib modules form the operator.yaml . can you please tell us what issue you are facing is this cephfs or rbd?
