### ISSUE TITLE
Ceph operator: devicesInUse should be set to false when initialization fail

### ISSUE THREAD

**Issue by ahuret** [rook/rook#4633]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When initialization of cluster failed, `devicesInUse` variable can be set to `true` (if `spec.storage.useAllDevices` is set to true)  and then, when we update `CephCluster` k8s manifest (to get initialization to work), `devicesInUse` is already set to `true` and "using all devices in more than one namespace is not supported" error can happen.

**Expected behavior:**

When initialization of cluster failed, variables only process by code (not configuration) should be reset as default (in my case default is false).

**How to reproduce it (minimal and precise):**

- variable `spec.storage.useAllDevices` has to be defined as `true`.
- put another error in your `CephCluster` manifest (for exemple don't set `spec.storage.config` triggers an error)
- apply your manifest
- see that initialization failed
- get your manifest correct and re-apply it
- "using all devices in more than one namespace is not supported" error happen.

**Logs**

(first error was because spec.storage.config is null)

`2020-01-07 13:06:21.995063 E | op-cluster: failed to update cluster rook-ceph status: CephCluster.ceph.rook.io "rook-ceph" is invalid: spec.storage.config: Invalid value: "null": spec.storage.config in body must be of type object: "null"`

(then as explained above, I updated spec and added config field then this happened):

`2020-01-08 09:57:24.629863 I | op-cluster: Update event for uninitialized cluster rook-ceph. Initializing...
2020-01-08 09:57:24.629892 I | op-cluster: CephCluster rook-ceph status: Error. using all devices in more than one namespace is not supported
2020-01-08 09:57:24.664597 E | op-cluster: failed to configure local ceph cluster. using all devices in more than one namespace is not supported
2020-01-08 09:57:24.665640 I | op-cluster: Update event for uninitialized cluster rook-ceph. Initializing...
2020-01-08 09:57:24.665651 I | op-cluster: CephCluster rook-ceph status: Error. using all devices in more than one namespace is not supported
2020-01-08 09:57:24.676999 E | op-cluster: failed to configure local ceph cluster. using all devices in more than one namespace is not supported
`

**Environment**:
* OS (e.g. from /etc/os-release):
Container Linux by CoreOS 2345.0.0
* Kernel (e.g. `uname -a`):
4.19.87-coreos
* Cloud provider or hardware configuration:
online
* Rook version (use `rook version` inside of a Rook Pod):
v1.1.2 (but this part of code doesn't change in latest (v1.2.1)
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.4 - nautilus (stable)
* Kubernetes version (use `kubectl version`):
1.16.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
baremetal

**Comment by leseb** [comment]
What kind of initialization error are you referring too? Can you print an error?
But overall I understand the concern, it should be easy to fix this.
