### ISSUE TITLE
Ceph subsystem health in OCP 4.2 shows as "rook-cluster is not available" but works fine

### ISSUE THREAD

**Issue by VictorHavard** [rook/rook#4636]
**Is this a bug report or feature request?**
* Bug Report

**Bug Report**

**Expected behavior:**
Install rook/ceph on OCP 4.2 and it works

**Deviation from expected behavior:**
Dashboard under "Cluster Health" shows "rook-ceph is not available" even though the ceph cluster is up and healthy and I can successfully provision PVCs against it.

![image](https://user-images.githubusercontent.com/13053051/72016683-deb9fc00-3229-11ea-989e-9e555c004246.png)

![image](https://user-images.githubusercontent.com/13053051/72016721-ee394500-3229-11ea-8af7-3e1394fe1515.png)

![image](https://user-images.githubusercontent.com/13053051/72016771-0315d880-322a-11ea-8bcb-5d31cfc3485c.png)

![image](https://user-images.githubusercontent.com/13053051/72016797-0b6e1380-322a-11ea-8200-0b365b7929ae.png)

**How to reproduce it (minimal and precise):**
Clean install of OpenShift 4.2.  Install rook/ceph as per github instructions for that project.  Login to the UI as an administrator.

**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
```apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.5
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - storage-node
      podAffinity:
      podAntiAffinity:
      tolerations:
      - key: storage-node
        operator: Exists
  annotations:
  resources:
    mgr:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
  removeOSDsIfOutAndSafeToRemove: false
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    config:
    nodes:
    - name: "storage-0"
      devices: # specific devices to use for storage can be specified for each node
      - name: "sdb"
        config:
          osdsPerDevice: "1"
    - name: "storage-1"
      devices: # specific devices to use for storage can be specified for each node
      - name: "sdb"
        config:
          osdsPerDevice: "1"
    - name: "storage-2"
      devices: # specific devices to use for storage can be specified for each node
      - name: "sdb"
        config:
          osdsPerDevice: "1"
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api```

* Operator's logs, if necessary

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by nizamial09** [comment]
Try once after making the `monitoring: enable: true` in the cluster.yaml

**Comment by sbktc** [comment]
I've run across the same issue. Have changed the spec.monitoring.enabled to true. Howver I am still getting the message 'rook-ceph is not available', while storage can PV's can automatically be created. 
The build in prometheus is supposed to be for cluster monitoring, so I guess rook-ceph should fall within that category. Is it missing RBAC or service-monitor?

**Comment by sbktc** [comment]
It seems like I found a solution: 
1) The rook-ceph namespace should be labled cluster-monitoring=true, run: `oc label namespace rook-ceph "openshift.io/cluster-monitoring=true"`
2) Apply a slightly modified version of the RBAC file fount here: https://github.com/rook/rook/blob/release-1.2/cluster/examples/kubernetes/ceph/monitoring/rbac.yaml
The RBAC should be changed so that last role-binding applies to the openshift-monitoring namespace. 
After doing the above the status changed and the persistent storage tab now shows information about the rook-ceph cluster. :)

**Comment by travisn** [comment]
@umangachapagain can you take a look at this?
