### ISSUE TITLE
Document that the rbd volume plugin requires Ceph on the host

### ISSUE THREAD

**Issue by travisn** [rook/rook#464]
The rbd volume plugin requires Ceph to be installed on the host. Until the Rook volume plugin exists, we need to document on https://github.com/rook/rook/blob/master/demo/kubernetes/pre-reqs.md that Ceph is required.

**Comment by jbw976** [comment]
An attempt at summarizing the steps from @bzub from Gitter: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/rook-dev/I-I41ksZfvs
