### ISSUE TITLE
fs: LVM2_member, ownPartitions: true

### ISSUE THREAD

**Issue by valentinedy** [rook/rook#4640]
hello，my kubernetes version is 1.17.0，use rook-master
ceph/ceph                                                         v14.2.5             f676708b0232        4 weeks ago         825MB
quay.io/cephcsi/cephcsi                                           v1.2.2              d46311d35105        7 weeks ago         984MB
quay.io/k8scsi/csi-snapshotter                                    v1.2.2              538dbe77c2f9        3 months ago        47.6MB
quay.io/k8scsi/csi-provisioner                                    v1.4.0              2130c4e026a5        3 months ago        54.5MB
quay.io/k8scsi/csi-attacher                                       v1.2.0              eef7a9550ede        6 months ago        46.2MB
quay.io/k8scsi/csi-node-driver-registrar                          v1.1.0              a93898755322        9 months ago        15.8MB

kubectl apply -f  rook-master/cluster/examples/kubernetes/ceph/cluster.yaml
rook-ceph-osd-0-69dc6495dd-4pz6g                   1/1     Running     0          34m   192.168.200.28   master   <none>           <none>
rook-ceph-osd-prepare-master-pfftf                 0/1     Completed   0          13m   192.168.200.28   master   <none>           <none>
rook-ceph-osd-prepare-node1-mhnk7                  1/1     Running     0          35m   192.168.200.27   node1    <none>           <none>
rook-ceph-osd-prepare-node2-lt8jh                  0/1     Completed   0          13m   192.168.200.26   node2    <none>           <none>
rook-ceph-osd-prepare-node3-tvrjf                  0/1     Completed   0          13m   192.168.200.25   node3    <none>           <none>

only create one osd
node2 node3  reports
2020-01-09 08:13:34.089005 I | sys: Output: NAME="sdb" SIZE="53687091200" TYPE="disk" PKNAME=""
2020-01-09 08:13:34.089046 I | sys: Device found - sdb
2020-01-09 08:13:34.089066 I | exec: Running command: udevadm info --query=property /dev/sdb
2020-01-09 08:13:34.091681 I | cephosd: skipping device "sdb" that is in use (not by rook). fs: LVM2_member, ownPartitions: true
2020-01-09 08:13:34.091705 I | exec: Running command: lsblk /dev/sda --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2020-01-09 08:13:34.095956 I | sys: Output: NAME="sda" SIZE="53687091200" TYPE="disk" PKNAME=""
NAME="sda2" SIZE="52612300800" TYPE="part" PKNAME="sda"
NAME="centos-swap" SIZE="4160749568" TYPE="lvm" PKNAME="sda2"
NAME="centos-root" SIZE="48444211200" TYPE="lvm" PKNAME="sda2"
NAME="sda1" SIZE="1073741824" TYPE="part" PKNAME="sda"
2020-01-09 08:13:34.095988 I | sys: Device found - sda

**Comment by sp98** [comment]
`fs: LVM2_member` is suggesting that the device `sdb` already having a filesystem on it.  Rook can't create OSD on device that already has a filesystem.

**Comment by valentinedy** [comment]
i am use centos7 1908 
lsblk /dev/sdb --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
NAME="sdb" SIZE="53687091200" TYPE="disk" PKNAME=""

i don't see any filesystem
[root@node1 ~]# pvs
  PV         VG     Fmt  Attr PSize   PFree
  /dev/sda2  centos lvm2 a--  <49.00g 4.00m
[root@node1 ~]# lvs
  LV   VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root centos -wi-ao---- <45.12g                                                    
  swap centos -wi-a-----  <3.88g
@sp98

**Comment by valentinedy** [comment]
func GetDevicePartitions(device string, executor exec.Executor) (partitions []Partition, unusedSpace uint64, err error) {

	var devicePath string
	splitDevicePath := strings.Split(device, "/")
	if len(splitDevicePath) == 1 {
		devicePath = fmt.Sprintf("/dev/%s", device) //device path for OSD on devices.
	} else {
		devicePath = device //use the exact device path (like /mnt/<pvc-name>) in case of PVC block device
	}

	cmd := fmt.Sprintf("lsblk %s", devicePath)
	output, err := executor.ExecuteCommandWithOutput(false, cmd, "lsblk", devicePath,
		"--bytes", "--pairs", "--output", "NAME,SIZE,TYPE,PKNAME")
	logger.Infof("Output: %+v", output)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to get device %s partitions. %+v", device, err)
	}
	partInfo := strings.Split(output, "\n")
	var deviceSize uint64
	var totalPartitionSize uint64
	for _, info := range partInfo {
		props := parseKeyValuePairString(info)
		name := props["NAME"]
		if name == device {
			// found the main device
			logger.Info("Device found - ", name)
			deviceSize, err = strconv.ParseUint(props["SIZE"], 10, 64)
			if err != nil {
				return nil, 0, fmt.Errorf("failed to get device %s size. %+v", device, err)
			}
		} else if props["PKNAME"] == device && props["TYPE"] == PartType {
			// found a partition
			p := Partition{Name: name}
			p.Size, err = strconv.ParseUint(props["SIZE"], 10, 64)
			if err != nil {
				return nil, 0, fmt.Errorf("failed to get partition %s size. %+v", name, err)
			}
			totalPartitionSize += p.Size

			info, err := GetUdevInfo(name, executor)
			if err != nil {
				return nil, 0, err
			}
			if v, ok := info["PARTNAME"]; ok {
				p.Label = v
			}
			if v, ok := info["ID_PART_ENTRY_NAME"]; ok {
				p.Label = v
			}
			if v, ok := info["ID_FS_TYPE"]; ok {
				p.Filesystem = v
			}

			partitions = append(partitions, p)
		} else if strings.HasPrefix(name, cephLVPrefix) && props["TYPE"] == LVMType {
			p := Partition{Name: name}
			partitions = append(partitions, p)
		}
	}

	if deviceSize > 0 {
		unusedSpace = deviceSize - totalPartitionSize
	}
	return partitions, unusedSpace, nil
}

**Comment by leseb** [comment]
@valentinedy please `blkid` against your device and print the output.
