### ISSUE TITLE
Ceph 14.2.4 Seemingly Not Respecting osd_memory_target

### ISSUE THREAD

**Issue by jteeg** [rook/rook#4645]
**Is this a bug report or feature request?**
Bug Report

**Deviation from expected behavior:**
After upgrading to Rook 1.1.2 / Ceph 14.2.4 (Nautilus), we began noticing that the OSDs began consuming much more Memory than before (up to 50% on our 32 GB w4r nodes - aka 16 GB). After reaching out to the Rook Community, we were pointed at the new(?) memory auto-tuning and the `osd_memory_target` setting.

We confirmed that the `osd_memory_target` was set at the default of 4 GB, yet we were seeing OSDs consume up to 400% beyond this value (16 GB).

We're attempting to work-around this by setting Memory Limits on our OSDs of 6 GB (where our OSDs previously did not have any memory limits defined).

**How to reproduce it (minimal and precise):**

**File(s) to submit:**

**Operator's logs, if necessary**

**Crashing pod(s) logs, if necessary**

**OS (e.g. from /etc/os-release):**
cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2135.5.0
VERSION_ID=2135.5.0

**Kernel (e.g. uname -a):**
Linux 4.19.50-coreos-r1 #1 SMP Mon Jul 1 19:07:03 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz GenuineIntel GNU/Linux

**Cloud provider or hardware configuration:** On-prem

**Rook version (use rook version inside of a Rook Pod):**
1.1.2

**Storage backend version (e.g. for ceph do ceph -v):**
14.2.4

**Kubernetes version (use kubectl version):**
1.15.6

**Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):** CoreOS

**Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox):** Bluestore

**Comment by leseb** [comment]
What you're describing looks more like a Ceph issue than a Rook one.
Rook will pass limits and requests to the pod and Ceph should auto-tune based on those values.

I think you should also open an issue here: https://tracker.ceph.com/.
Thanks.

**Comment by leseb** [comment]
If this appears to be a bug in Ceph, we can try to quickly work around it in Rook.

**Comment by PavloZabudskyi** [comment]
Same with rook 1.2.3 and ceph 14.2.6

```
[root@server5 /]# ceph config get osd.4 osd_memory_target
4294967296
```
`rook-ceph-osd-4-74dd45cbcb-s86ll                     97m          17327Mi`

**Comment by travisn** [comment]
@jteeg @PavloZabudskyi Are you setting the [resource requests and limits](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L128) for the OSDs in the cluster CR? Rook passes these limits on to the OSD daemons to set the memory limits as expected. Even then, the memory will fluctuate even above the limits depending on load and whether the kernel is reclaiming memory. Closing this since Rook is configuring the OSDs as expected.
