### ISSUE TITLE
crashcollector deployments/pods not cleaned up after node removal

### ISSUE THREAD

**Issue by AXington** [rook/rook#4647]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After a node is removed, the relevant crashcollector deployments, replicasets, and pods are left around, with the pods in a 'pending state'

**Expected behavior:**
The crashcollector pods, rs's, and deployments are removed after the node is no longer part of the cluster.

**How to reproduce it (minimal and precise):**

Replace nodes with crashcollector pods associated from the cluster.

**Environment**:
* OS (e.g. from /etc/os-release): 
``` cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
* Kernel (e.g. `uname -a`):
```
Linux ip-10-0-156-103.ec2.internal 4.19.75-27.58.amzn2.x86_64 #1 SMP Tue Oct 1 22:37:56 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): v1.2.1
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph version 14.2.5 (ad5bd132e1492173c85fda2cc863152730b16a92) nautilus (stable)
* Kubernetes version (use `kubectl version`): v1.14.9-eks-c0eccc
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): EKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by AXington** [comment]
for now I've been using this command to clean them up:
```bash
 kubectl -n rook-ceph get pods --field-selector=status.phase=Pending | grep -vi name | awk '{ print $1 }' | xargs -I{0} /usr/bin/env bash -c "kubectl -n rook-ceph get pod {0} -o jsonpath='{.metadata.labels.node_name}' | xargs -I{1} kubectl -n rook-ceph delete deployments.apps -l node_name={1}"
```

**Comment by leseb** [comment]
@AXington can you share a log on that pod? Please use the `describe` subcommand. I'm wondering why the pod remains in pending.

**Comment by AXington** [comment]
@leseb the pod remains in pending because it's going to a specific node that no longer exists. And unfortunately I can't, it's been deleted now (has been 13 days).

**Comment by leseb** [comment]
Do you still have the op logs by any chance?

**Comment by sanchoooo** [comment]
I have seen similar behavior on a dhcp setup.
aws eks kubernetes v1.14
rook: 1.2.1

system was deployed with rook services.
all nodes except rook-osd were powered down for the weekend on friday
nodes were powered up on monday and 2 of the nodes obtained new ip addresses on the dhcp network which then assigned those 2 hosts, new host names

rook crashcollector was stuck in pending state as the 2 crashcollectors were setup with:
Node-Selectors: kubernetes.io/hostname=ip-100-97-7-118.us-west-2.compute.internal
Node-Selectors: kubernetes.io/hostname=ip-100-97-3-38.us-west-2.compute.internal

and those hostnames no longer existed on those machines after powerup on monday
The manual workaround was to delete the deployments for those 2 crashcollectors and let the 
system regenerate new ones for the new hostnames.

**Comment by leseb** [comment]
Fixed in https://github.com/rook/rook/pull/5069
