### ISSUE TITLE
rookd: --data-devices=all tries to use RBD devices

### ISSUE THREAD

**Issue by bzub** [rook/rook#465]
I know you're working on specifying disks via configuration in #397.

I like using the current `--data-devices=all` option but it would be nice if `/dev/rdb*` were excluded from possible drives to use. Other enhancements to the disk detection could come after fixing this. It's been a headache for me at least.

**Comment by travisn** [comment]
@bzub, you're right this would be a relatively simple fix. 

Using a regular expression we can have a powerful way to include or exclude devices. This seems like a nice long-term solution as well for homogenous environments until we have more flexibility with #397.

To the TPR `rook-cluster.yaml` we would add a new property for specifying the regular expression. 
```
  deviceFilter: <expression>
```
To include only devices `sda` through `sdd`:
```
^/dev/sd[a-d]$
```
To include all `/dev/` devices except those with a prefix of `/dev/r`:
```
^/dev/[^r]
```
The selected devices would still have the requirement that they not have partitions or filesystems created.

For the full golang regular expression syntax, see:
https://golang.org/pkg/regexp/#pkg-overview

To test your expressions try a tool such as:
https://regex-golang.appspot.com/assets/html/index.html
