### ISSUE TITLE
CephFS CSI volume expand capacity / quota

### ISSUE THREAD

**Issue by phal0r** [rook/rook#4669]
Hi,

I have provisioned a volume via CSI and CephFS backed storageclass. So far everything works fine. Now I want to expand the capacity of the volume. Mounting is done via ceph-fuse. Kernel version is 5.4.1.

What I did:
- change the capacity of the persistent volume in kubernetes
- change the requested capacity of the persistent volume claim
- rededployed the app

What needs to be done to update the mount with the new capacity? Any help is appreciated. Thanks.

**Comment by Madhu-1** [comment]
you may need to update the size of the backend cephfs subvolume then redeploy the app 

but I would suggest you wait for ceph-csi v2.0.0 release which supports official resize https://github.com/ceph/ceph-csi/issues/557#issuecomment-566493396

**Comment by phal0r** [comment]
@Madhu-1 
Thanks for the response. I am aware of the resize feature in the next release, but what if I need to resize the volume now?

There is an issue on how to do it for RBD and of course it is just a workaround, but it is still better than creating new volumes and copying all the content.

Do you know a way how to do it with ceph tools like it was discussed for rbd?

**Comment by Madhu-1** [comment]
@phal0r here  is the link fo slack discussion on how to resize cephfs  subvolume https://rook-io.slack.com/archives/CK9CF5H2R/p1578908578097600

**Comment by phal0r** [comment]
Thanks @Madhu-1 . This is what I was after. 

And for the sake of documentation:
- run ceph toolbox
- use this command to change the quota: `ceph fs subvolume create myfs csi-vol-44792a21-35de-11ea-b653-0a580a8002ae --size 5368709120 --group_name csi`
