### ISSUE TITLE
cephfs cannot mount 

### ISSUE THREAD

**Issue by foolwc** [rook/rook#4685]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```
[root@rook-02 ~]# mount -t ceph 10.107.84.71:6789:/ /mnt/cephFS -o name=admin,secret=XXX
mount: 10.107.84.71:6789:/: can't read superblock
[root@rook-02 ~]# dmesg | tail
[ 2513.327101] libceph: client4556 fsid e42ca33b-b198-4bde-af36-fffd1b138f55
[ 2513.327787] libceph: mon0 10.107.84.71:6789 session established
[ 2513.327867] libceph: mds0 10.0.10.33:6801 socket error on write
[ 2513.600100] libceph: mds0 10.0.10.33:6801 socket error on write
[ 2514.601084] libceph: mds0 10.0.10.33:6801 socket error on write
```
mds0 IP was  Node IP  but not mds pod IP.
**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
Linux 3.10.0-514.el7.x86_64 x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
iamge: rook/ceph:v1.1.0
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.3 (0f776cf838a1ae3130b2b73dc26be9c95c6ccc39) nautilus (stable)
* Kubernetes version (use `kubectl version`):
v1.10.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
sh-4.2# ceph -w    
  cluster:
    id:     e42ca33b-b198-4bde-af36-fffd1b138f55
    health: HEALTH_WARN
            too few PGs per OSD (4 < min 30)
 
  services:
    mon: 1 daemons, quorum a (age 38m)
    mgr: a(active, since 37m)
    mds: myfs:1 {0=myfs-a=up:active} 1 up:standby-replay
    osd: 4 osds: 4 up (since 12m), 4 in (since 36m)
 
  data:
    pools:   2 pools, 16 pgs
    objects: 22 objects, 2.2 KiB
    usage:   4.0 GiB used, 312 GiB / 316 GiB avail
    pgs:     16 active+clean
 
  io:
    client:   853 B/s rd, 1 op/s rd, 0 op/s wr

**Comment by beelzetron** [comment]
Hit the same issue on Openshift 3.11 with rook 1.2.2 and ceph 14.2.6.
