### ISSUE TITLE
rook-ceph: Error while deploying RGW(object-openshift.yaml) when using cluster-external.yaml

### ISSUE THREAD

**Issue by likid0** [rook/rook#4686]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When only deploying an external cluster with rook(so we have no previous internal ceph cluster) in the rook-ceph namespaces we get the following error when deploying the RGW services( object-openshift.yaml or object.yaml):

[root@helper ~]# oc get pods | grep rgw
rook-ceph-rgw-my-store-a-56b664447d-67rrf                         0/1     Init:0/1   0          17h
rook-ceph-rgw-my-store-b-6cff69f6d4-mmftg                         0/1     Init:0/1   0          17h
Warning  FailedMount      28s (x2 over 29s)    kubelet, worker2.ocp4.example.com  MountVolume.SetUp failed for volume "rook-config-override" : configmap "rook-config-override" not found

It seems that the cm rook-config-override doesn't get created by default like when we do a normal/internal deploy of ceph-rook.

If we create the rook-config-override cm by hand, the rgw pods start without issues:

[root@helper ceph]# oc create -f configmap-override.yaml
configmap/rook-config-override created
[root@helper ceph]# oc get pods | grep rgw
rook-ceph-rgw-my-store-a-56b664447d-67rrf                         1/1     Running    0          17h
rook-ceph-rgw-my-store-b-6cff69f6d4-mmftg                         1/1     Running    0          17h

Is this expected behaviour ?, it seems that maybe for an external cluster using the CM override isn't needed and could be removed from the pods RGW mount volumes definition?

Thanks.

**Expected behavior:**

The RGW pod mount definition removes the dependency to mount the CM rook-config-override or
The CM rook-config-override gets created during cluster-external.yaml deployment
and the RGW pods start without issues

**How to reproduce it (minimal and precise):**

1   oc create -f common.yaml
2   oc create -f operator.yaml
3   oc create -f cluster-external.yaml
4   oc create -f object-openshift.yaml
5.  RGW pods fail to start.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
Red Hat Enterprise Linux CoreOS 42.81.20191223.0 (Ootpa)
* Kernel (e.g. `uname -a`):
Linux worker1.ocp4.liquid.com 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Wed Nov 27 01:11:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
baremetal
* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.2.0
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.5 (ad5bd132e1492173c85fda2cc863152730b16a92) nautilus (stable)
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
Can you print your `cluster-external.yaml`? If the image is empty then the cm does not get created.

**Comment by leseb** [comment]
Also, I'd like to see your operator logs. Thanks

**Comment by likid0** [comment]
Hi, 

Thanks for taking a look, I was missing the point that the cm override should get created even during external deployment, so you can for example override an option on the RGW config that is on K8s and not on the external cluster?
[operator-log.txt](https://github.com/rook/rook/files/4067851/operator-log.txt)


this is the cluster-external.yaml file:

# cat cluster-external.yaml | grep -v ^\#
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  external:
    enable: true
  dataDirHostPath: /var/lib/rook
  # providing an image is optional, do this if you want to create other CRs (rgw, mds, nfs)
  cephVersion:
    image: ceph/ceph:v14.2.4 # MUST match external cluster version

In the operator logs I do have:

E | op-cluster: failed to determine if we should upgrade or not. image spec version 14.2.4-0 nautilus is lower than the running cluster version 14.2.4-85 nautilus, downgrading is not supported

Uploaded operator log during the cluster and rgw creation.

Thanks.

**Comment by leseb** [comment]
@likid0 managing resources like mds/rgw/nfs on k8s when using external cluster is not mandatory. That's why the cm is only created if an image is specified in the CR.

I think I've found the bug, sending a PR to fix it. Thanks for reporting.
