### ISSUE TITLE
Multi-Attach error

### ISSUE THREAD

**Issue by zionmenahem** [rook/rook#4699]
**Is this a bug report or feature request?**
* Bug Report
shutting down a node which runs a pod with a PV mount, requires PV re-mount by the new pod, however re-mount operation takes very long time (20 mins is the least observed, other times it's still stuck after several hours)

**Expected behavior:**
PV is re-mounted successfully on new pod, right after node failure is detected.

specifically, this procedure works fine on rook version 1.0.5 and ceph version 14.2.1 (FLEX driver), though other issues were experienced in such setups.
on a cluster upgraded to 1.1.7/14.2.4 (CSI driver), after shutting down the node, we're experiencing new pod that takes a lot of time to complete, waiting to mount an already mounted volume

**How to reproduce it (minimal and precise):**

reproducing this exact cluster is not so simple as many components are involved in the cluster creation. however, basically we're creating a 3 nodes cluster on Azure (non AKS). complete deployment also installs Istio, Postgres, EFK and more.

**File(s) to submit**:
events description of the pod having problem to start:
```
  Warning  FailedAttachVolume      50m                attachdetach-controller  Multi-Attach error for volume "pvc-6508c028-36aa-11ea-8679-000d3aad2fb7" Volume is already exclusively attached to one node and can't be attached to another
  Normal   Scheduled               50m                default-scheduler        Successfully assigned adc-controller-application/prometheus-0 to zmha122vm1
  Normal   SuccessfulAttachVolume  45m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-6508c028-36aa-11ea-8679-000d3aad2fb7"
  Warning  FailedMount             43m                kubelet, zmha122vm1      MountVolume.MountDevice failed for volume "pvc-6508c028-36aa-11ea-8679-000d3aad2fb7" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             42m (x7 over 43m)  kubelet, zmha122vm1      MountVolume.MountDevice failed for volume "pvc-6508c028-36aa-11ea-8679-000d3aad2fb7" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-c88f4d72-36ab-11ea-8cca-0a580ae9400c already exists
  Warning  FailedMount             32m (x8 over 48m)  kubelet, zmha122vm1      Unable to mount volumes for pod "prometheus-0_adc-controller-application(6437da13-3853-11ea-8c9c-000d3aad2fb7)": timeout expired waiting for volumes to attach or mount for pod "adc-controller-application"/"prometheus-0". list of unmounted volumes=[prometheus-data-volume]. list of unattached volumes=[prometheus-data-volume config scraping-files configmap-global-settings default-token-nxjnh istio-envoy sds-uds-path istio-token]
  Normal   Pulled                  31m                kubelet, zmha122vm1      Container image "alpine:3.9" already present on machine
  Normal   Created                 31m                kubelet, zmha122vm1      Created container
  Normal   Created                 31m                kubelet, zmha122vm1      Created container
  Normal   Started                 31m                kubelet, zmha122vm1      Started container
  Normal   Pulled                  31m                kubelet, zmha122vm1      Container image "docker.io/istio/proxyv2:1.4.2" already present on machine
  Normal   Started                 31m                kubelet, zmha122vm1      Started container
  Normal   Pulled                  31m                kubelet, zmha122vm1      Container image "prom/prometheus:v2.10.0" already present on machine
  Normal   Created                 31m                kubelet, zmha122vm1      Created container
  Normal   Started                 31m                kubelet, zmha122vm1      Started container
  Normal   Pulled                  31m                kubelet, zmha122vm1      Container image "reg.radware.com:18443/adcc/adcc_stan_prometheus/dev:100" already present on machine
  Normal   Created                 31m                kubelet, zmha122vm1      Created container
  Normal   Started                 31m                kubelet, zmha122vm1      Started container
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
* Kernel (e.g. `uname -a`):
`Linux rook-ceph-operator-778bd6f4c9-5khqs 5.0.0-1028-azure #30~18.04.1-Ubuntu SMP Fri Dec 6 11:47:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Azure, non-managed
* Rook version (use `rook version` inside of a Rook Pod): v1.1.7
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.4
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Madhu-1** [comment]
please provide below information

* Are  you suing cephfs and rbd 
* PVC is RWO or RWX
* iF RBD  PVC mode is  FileSystem  or Block

**Comment by zionmenahem** [comment]
Hi,
According to our settings:

  1.  We’re using cephfs driver. From our helm values:
csi:

  enableRbdDriver: false

  enableCephfsDriver: true

  enableGrpcMetrics: true

  1.  We use both. We have several PVs and PVCs, only one of them is RWX and the rest are RWO
  2.  We create both CephFileSystem and CephBlockPool storage class

Please let me know if there’s more information you need.

Thanks,
Zion

**Comment by Madhu-1** [comment]
RWO PVC can  be attached in multiple pods on the same nodes, if you try to attach RWO PVC on multiple nodes  you will face  this error

are you facing issue with RWX PVC?

**Comment by zionmenahem** [comment]
Currently it looks like there are no issues with the RWX PV.

Regarding our issue - those are our PVs and PVCs:

root@zmrook143vm2:~# kubectl get --all-namespaces pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                            STORAGECLASS       REASON   AGE
pvc-1fdb24ff-3b7a-11ea-88b4-000d3aaf9747   150Gi      RWO            Delete           Bound    central-logging/elasticsearch-data-volume-es-cluster-1           rook-ceph-pool-1            137m
pvc-4022df43-3b7a-11ea-a5b7-000d3aaf9746   3Gi        RWO            Delete           Bound    postgres/stolon-data-postgres-stolon-keeper-1                    rook-ceph-pool-1            136m
pvc-499f9c8a-3b7a-11ea-a5b7-000d3aaf9746   150Gi      RWO            Delete           Bound    central-logging/elasticsearch-data-volume-es-cluster-2           rook-ceph-pool-1            136m
pvc-56fd354b-3b79-11ea-a5b7-000d3aaf9746   150Gi      RWO            Delete           Bound    central-logging/elasticsearch-data-volume-es-cluster-0           rook-ceph-pool-1            138m
pvc-572db964-3b8c-11ea-a5b7-000d3aaf9746   5Gi        RWX            Delete           Bound    adc-controller-application/shared-storage-pvc                    rook-ceph-pool-1            6m45s
pvc-5ea336ed-3b7a-11ea-a5b7-000d3aaf9746   3Gi        RWO            Delete           Bound    postgres/stolon-data-postgres-stolon-keeper-2                    rook-ceph-pool-1            135m
pvc-ebe80bf1-3b78-11ea-88b4-000d3aaf9747   1Gi        RWO            Delete           Bound    kafka/data-pzoo-0                                                rook-ceph-pool-1            137m
pvc-ecae0726-3b78-11ea-88b4-000d3aaf9747   1Gi        RWO            Delete           Bound    kafka/data-pzoo-1                                                rook-ceph-pool-1            137m
pvc-ecd839a5-3b78-11ea-88b4-000d3aaf9747   1Gi        RWO            Delete           Bound    kafka/data-pzoo-2                                                rook-ceph-pool-1            137m
pvc-ed3c7850-3b78-11ea-88b4-000d3aaf9747   2Gi        RWO            Delete           Bound    kafka/data-kafka-0                                               rook-ceph-pool-1            136m
pvc-ed925a2d-3b78-11ea-88b4-000d3aaf9747   2Gi        RWO            Delete           Bound    kafka/data-kafka-1                                               rook-ceph-pool-1            137m
pvc-edc4becd-3b78-11ea-88b4-000d3aaf9747   2Gi        RWO            Delete           Bound    kafka/data-kafka-2                                               rook-ceph-pool-1            137m
pvc-ee43a4e6-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            Delete           Bound    etcd/etcd-data-volume-etcd-0                                     rook-ceph-pool-1            136m
pvc-f00ac142-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            Delete           Bound    etcd/etcd-data-volume-etcd-1                                     rook-ceph-pool-1            137m
pvc-f0296169-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            Delete           Bound    etcd/etcd-data-volume-etcd-2                                     rook-ceph-pool-1            137m
pvc-f042c9a1-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            Delete           Bound    postgres/stolon-data-postgres-stolon-keeper-0                    rook-ceph-pool-1            137m
pvc-f3a9773e-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            Delete           Bound    adc-controller-application/prometheus-data-volume-prometheus-0   rook-ceph-pool-3            136m

root@zmrook143vm2:~# kubectl get --all-namespaces pvc
NAMESPACE                    NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
adc-controller-application   prometheus-data-volume-prometheus-0      Bound    pvc-f3a9773e-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            rook-ceph-pool-3   146m
adc-controller-application   shared-storage-pvc                       Bound    pvc-572db964-3b8c-11ea-a5b7-000d3aaf9746   5Gi        RWX            rook-ceph-pool-1   7m12s
central-logging              elasticsearch-data-volume-es-cluster-0   Bound    pvc-56fd354b-3b79-11ea-a5b7-000d3aaf9746   150Gi      RWO            rook-ceph-pool-1   143m
central-logging              elasticsearch-data-volume-es-cluster-1   Bound    pvc-1fdb24ff-3b7a-11ea-88b4-000d3aaf9747   150Gi      RWO            rook-ceph-pool-1   137m
central-logging              elasticsearch-data-volume-es-cluster-2   Bound    pvc-499f9c8a-3b7a-11ea-a5b7-000d3aaf9746   150Gi      RWO            rook-ceph-pool-1   136m
etcd                         etcd-data-volume-etcd-0                  Bound    pvc-ee43a4e6-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            rook-ceph-pool-1   146m
etcd                         etcd-data-volume-etcd-1                  Bound    pvc-f00ac142-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            rook-ceph-pool-1   146m
etcd                         etcd-data-volume-etcd-2                  Bound    pvc-f0296169-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            rook-ceph-pool-1   146m
kafka                        data-kafka-0                             Bound    pvc-ed3c7850-3b78-11ea-88b4-000d3aaf9747   2Gi        RWO            rook-ceph-pool-1   146m
kafka                        data-kafka-1                             Bound    pvc-ed925a2d-3b78-11ea-88b4-000d3aaf9747   2Gi        RWO            rook-ceph-pool-1   146m
kafka                        data-kafka-2                             Bound    pvc-edc4becd-3b78-11ea-88b4-000d3aaf9747   2Gi        RWO            rook-ceph-pool-1   146m
kafka                        data-pzoo-0                              Bound    pvc-ebe80bf1-3b78-11ea-88b4-000d3aaf9747   1Gi        RWO            rook-ceph-pool-1   146m
kafka                        data-pzoo-1                              Bound    pvc-ecae0726-3b78-11ea-88b4-000d3aaf9747   1Gi        RWO            rook-ceph-pool-1   146m
kafka                        data-pzoo-2                              Bound    pvc-ecd839a5-3b78-11ea-88b4-000d3aaf9747   1Gi        RWO            rook-ceph-pool-1   146m
postgres                     stolon-data-postgres-stolon-keeper-0     Bound    pvc-f042c9a1-3b78-11ea-88b4-000d3aaf9747   3Gi        RWO            rook-ceph-pool-1   146m
postgres                     stolon-data-postgres-stolon-keeper-1     Bound    pvc-4022df43-3b7a-11ea-a5b7-000d3aaf9746   3Gi        RWO            rook-ceph-pool-1   136m
postgres                     stolon-data-postgres-stolon-keeper-2     Bound    pvc-5ea336ed-3b7a-11ea-a5b7-000d3aaf9746   3Gi        RWO            rook-ceph-pool-1   135m

and the events for the specific pod that is a single StatefulSet replica:

Events:
  Type     Reason              Age                   From                     Message
  ----     ------              ----                  ----                     -------
  Normal   Scheduled           13m                   default-scheduler        Successfully assigned adc-controller-application/prometheus-0 to zmrook143vm2
  Warning  FailedAttachVolume  13m                   attachdetach-controller  Multi-Attach error for volume "pvc-f3a9773e-3b78-11ea-88b4-000d3aaf9747" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedAttachVolume  78s (x10 over 7m43s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-f3a9773e-3b78-11ea-88b4-000d3aaf9747" : attachment timeout for volume 0001-0009-rook-ceph-0000000000000001-4171282e-3b7a-11ea-b5e5-0a580ae9420c
  Warning  FailedMount         28s (x6 over 11m)     kubelet, zmrook143vm2    Unable to mount volumes for pod "prometheus-0_adc-controller-application(2c083caf-3b8d-11ea-a5b7-000d3aaf9746)": timeout expired waiting for volumes to attach or mount for pod "adc-controller-application"/"prometheus-0". list of unmounted volumes=[prometheus-data-volume]. list of unattached volumes=[prometheus-data-volume config scraping-files configmap-global-settings default-token-nhtjx istio-envoy sds-uds-path istio-token]

I suppose this is the situation you mean.
Also, for CephBlockPool and for this specific pool (rook-ceph-pool-3) - spec.replicated.size is set to 3.

So, a solution for such case would be to make the ‘adc-controller-application/prometheus-data-volume-prometheus-0’ PV of type RWX?
Is there a right/better way to handle this issue?

Hope I’m clear.

Thanks,
Zion

**Comment by zionmenahem** [comment]
Just wanted to emphasise that in our 3 nodes cluster, a single pod (with a specific RWO PV attached) is running on a node we’re turning off. A new pod is created on one of the remaining nodes. This pod is not ready for quite a long time, waiting to attach to the same PV (events are attached in previous post).

Hope that clarifies our issue.

**Comment by Madhu-1** [comment]
This will be fixed once we fix https://github.com/ceph/ceph-csi/issues/578, to avoid this issue you need to use RWX, but RBD doesnot support Filesystem RWX PVC, you can switch to cephfs if you need Filesystem RWX.

**Comment by Siddhu1096** [comment]
@Madhu-1 - I'm facing the same issue. https://github.com/rook/rook/issues/6612 Could you take a look? It'll be a great help.

**Comment by Madhu-1** [comment]
> @Madhu-1 - I'm facing the same issue. #6612 Could you take a look? It'll be a great help.

#6612 is not cephcsi multi attach error.

**Comment by AbstractVersion** [comment]
same here!

**Comment by darzanebor** [comment]
same stuff, pod migrated to another worker but this issue appeared: Volume is already exclusively attached to one node and can't be attached to another

**Comment by KlavsKlavsen** [comment]
We just updated to latest ceph - and yet we 're still seing this when trying to drain a node with statefulset on - it doesn't let it go - even when pod is gone. This is with k8s 1.24 and containerd and ceph v1.10.4

**Comment by Madhu-1** [comment]
Some ideas are getting discussed here https://github.com/rook/rook/issues/1507#issuecomment-1122965274

**Comment by travisn** [comment]
> We recently updated to latest ceph - and yet we 're still seing this when trying to drain a node with statefulset on - it doesn't let it go - even when pod is gone. This is with k8s 1.24 and containerd and ceph v1.10.4

@KlavsKlavsen Is the node being drained while it is still online? #1507 is about dealing with unresponsive nodes, rather than draining nodes.
