### ISSUE TITLE
Update shouldn't change the default S3 zone

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4703]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Updating rook to 1.2.1 changed the default S3 zone to default.

**Expected behavior:**
Keep the current one, or let configure it in CRD

**How to reproduce it (minimal and precise):**
Initially I had the "default" and "rookS3" zones, and it was using rookS3 for everything. Then the pool got corrupted, I created new zone (nautilusS3) and removed the rookS3.

With last update, the default zone shifted to "default"

I had to do:

```
radosgw-admin  realm default --rgw-realm=nautiluss3
radosgw-admin  zonegroup default --rgw-zonegroup=nautiluss3
radosgw-admin zonegroup modify --rgw-zonegroup default --master=false
radosgw-admin period update --commit
```

to make it work again.

I'm not too familiar with S3, and not sure I'm doing the right thing, but I'd like to better understand rook behavior if I need to set it up differently.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
1.2.1

**Comment by travisn** [comment]
@thotz Can you take a look?

**Comment by dimm0** [comment]
Any update on this? Not sure it's safe to update to the new version...

**Comment by thotz** [comment]
@dimm0 
Sorry to reply lately. I missed  this one initially. 

At least from code reading in rook, objectstore will added to "default realm" if it was not able to find any existing realm. In r case may it was not able to do so.
And it looks straightway reproducible, but i am facing issue to set up rook due https://github.com/rook/rook/issues/4724. I will debug further after setting to rook enviroment.

And as of now the objectstore will be created in default zone and  planning to change it with https://github.com/rook/rook/pull/4520.

**Comment by dimm0** [comment]
Upgraded with no issues this time... Will keep the ticket open until you test this

**Comment by thotz** [comment]
@dimm0 even I was not able to hit issue while updating from 1.2.0 to 1.2.1 
Hence closing the same
