### ISSUE TITLE
rook v1.1.0 release notes misspelled 

### ISSUE THREAD

**Issue by weisongf** [rook/rook#4720]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Storage Class Device Sets(Hyperlinks). 404.
https://rook.io/docs/rook/v1.1/ceph-cluster-crd.htlm#storage-class-device-sets

**Expected behavior:**
Storage Class Device Sets(Hyperlinks).
https://rook.io/docs/rook/v1.1/ceph-cluster-crd.htlm#storage-class-device-sets 
to 
https://rook.io/docs/rook/v1.1/ceph-cluster-crd.html#storage-class-device-sets

**Comment by galexrt** [comment]
Thanks for reporting!

I have updated the v1.1.0 GitHub release notes, see https://github.com/rook/rook/releases/tag/v1.1.0.
