### ISSUE TITLE
Operator crashing when checking monitors quorum on ceph update

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4722]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Operator is producing a long stacktrace when updating ceph regarding monitors quorum

**Expected behavior:**
Checking monitors

**How to reproduce it (minimal and precise):**
Update ceph with 3 mons

**File(s) to submit**:

[log.txt](https://github.com/rook/rook/files/4084377/log.txt)

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
1.2.2

**Comment by dimm0** [comment]
Maybe not crashing... But is this stack trace expected?

**Comment by leseb** [comment]
It's not a crash. Fixed in https://github.com/rook/rook/releases/tag/v1.2.2 as part of https://github.com/rook/rook/pull/4617.
