### ISSUE TITLE
csi-rbdplugin missing after node failure

### ISSUE THREAD

**Issue by NurPech** [rook/rook#4733]
**Is this a bug report or feature request?**
* Bug Report
After a worker node fails there isn't any csi-rbdplugin pod anymore. How can I recreate them? For details see this output:

```
NAME                                                   READY   STATUS      RESTARTS   AGE
rook-ceph-crashcollector-vsrvk8w001-58b685f754-4862x   1/1     Running     0          7d8h
rook-ceph-crashcollector-vsrvk8w002-56f7cf79c-dp5g7    1/1     Running     0          7d8h
rook-ceph-crashcollector-vsrvk8w003-b6bc5db68-lmdqp    1/1     Running     0          33h
rook-ceph-mgr-a-5bcf49455f-kbpc5                       1/1     Running     0          7d8h
rook-ceph-mon-a-cfd699798-czw7b                        1/1     Running     0          7d8h
rook-ceph-mon-b-6c765d57d7-wcm5h                       1/1     Running     0          33h
rook-ceph-mon-c-549dc995fc-b64xf                       1/1     Running     0          7d8h
rook-ceph-mon-d-canary-5867bbd5c7-rvt9b                0/1     Pending     0          8m53s
rook-ceph-operator-6d8fb9498b-r9czf                    1/1     Running     1          3d5h
rook-ceph-osd-0-9445b78c-7kbgv                         1/1     Running     0          7d8h
rook-ceph-osd-1-85d485d67c-ftchf                       1/1     Running     0          7d8h
rook-ceph-osd-2-b4d7b8995-2lctw                        1/1     Running     0          33h
rook-ceph-osd-prepare-vsrvk8w001-2w827                 0/1     Completed   0          8h
rook-ceph-osd-prepare-vsrvk8w002-qsrlh                 0/1     Completed   0          8h
rook-ceph-tools-685d84df94-sr2xn                       1/1     Running     0          8m7s
rook-discover-5nrtr                                    1/1     Running     0          7d8h
rook-discover-cvsx2                                    1/1     Running     1          7d8h
rook-discover-gqfhw                                    1/1     Running     0          7d8h
```

**Deviation from expected behavior:**

**Expected behavior:**
There should be the csi plugins.

**How to reproduce it (minimal and precise):**
One worker runs out of memory so it stopped some pods.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
* Kernel (e.g. `uname -a`): 4.19.0-6-amd64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.2.1
* Storage backend version (e.g. for ceph do `ceph -v`):14.2.5
* Kubernetes version (use `kubectl version`):1.16.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN 2 slow ops, oldest one blocked for 116618 sec, mon.a has slow ops; too few PGs per OSD (8 < min 30); 1/3 mons down, quorum a,c

**Comment by Madhu-1** [comment]
if you restart operator pod the csi pods should get recreated. but can you paste `kubectl cm -n<rook-namespace>` output?

**Comment by NurPech** [comment]
Thank you, the pods were recreated.

Do you have a typing error in the command? kubectl doesn't know the subcommand `cm`

**Comment by Madhu-1** [comment]
sorry mybad typpo in above comment, that should get configmap `kubectl get cm -n<rook-namespace>`  and also `kubectl get cm rook-ceph-csi-config -o yaml <rook-namespace>`

**Comment by NurPech** [comment]
sure
`NAME                              DATA   AGE
local-device-vsrvk8w001           1      7d21h
local-device-vsrvk8w002           1      7d21h
local-device-vsrvk8w003           1      7d21h
rook-ceph-csi-config              1      7d21h
rook-ceph-mon-endpoints           4      7d21h
rook-ceph-osd-vsrvk8w001-config   1      7d21h
rook-ceph-osd-vsrvk8w002-config   1      7d21h
rook-ceph-osd-vsrvk8w003-config   1      7d21h
rook-config-override              1      7d21h`

`apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":["10.109.209.169:6789","10.101.248.244:6789","10.111.226.74:6789"]}]'
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-14T12:37:20Z"
  name: rook-ceph-csi-config
  namespace: rook-ceph
  resourceVersion: "2551726"
  selfLink: /api/v1/namespaces/rook-ceph/configmaps/rook-ceph-csi-config
  uid: 9b61cfc7-88b3-4aeb-8dc5-b5b4785f8c16`

**Comment by Madhu-1** [comment]
looks like https://github.com/rook/rook/issues/4590 and this one are similar?

**Comment by Antiarchitect** [comment]
Having a similar problem. RBD and CephFS pods are getting missing after a while. Not sure it's about the node failure.

**Comment by NurPech** [comment]
> looks like #4590 and this one are similar?

It seems so. My issue is solved now. Thank you very much

**Comment by Antiarchitect** [comment]
@NurPech How exactly you solved this issue? I still need to kill rook operator once a day for rbdplugin and cephfsplugin pods be reanimated.

**Comment by Madhu-1** [comment]
if anyone faces this issue again. can you please check daemonset object is deleted?  if not please  provide `kubectl describe` output of it

**Comment by Antiarchitect** [comment]
@Madhu-1 
`csi-cephfsplugin` and `csi-rbdplugin` daemonsets and `csi-cephfsplugin-provisioner` `csi-rbdplugin-provisioner` deployments are deleted when I restart the operator pod.

**Comment by Madhu-1** [comment]
@travisn @egafford any idea why this is happening?

**Comment by Antiarchitect** [comment]
@Madhu-1 I will try to catch ds/deploy when pods are gone if any and let you know.

**Comment by Antiarchitect** [comment]
Deployment and DS are gone with the pods - expectable (pods are not trying to regenerate). This thing is killing me guys :(

**Comment by travisn** [comment]
@Antiarchitect Have you deployed v1.2.3? The fix is included with #4788 in that release, I just missed tagging this issue with the fix.

**Comment by Antiarchitect** [comment]
@travisn I just deployed. Will watch for some time.

**Comment by Madhu-1** [comment]
closing this one as #4788 Fixed the issue, please feel free to reopen if the issue presists
