### ISSUE TITLE
OSDs crashing after applying memory limit

### ISSUE THREAD

**Issue by jti989** [rook/rook#4738]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSDs stay in CrashLoopBackOff state after adding a memory limit.

**Expected behavior:**
OSDs should come back up.

**How to reproduce it (minimal and precise):**
Create a CephCluster without memory/cpu limits.
Change the cluster.yaml to have memory limits, apply it.
Comment out memory limits and apply. Pods keep crashing

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
Attached, memory limit commented out again to test this.
[cluster.yaml.txt](https://github.com/rook/rook/files/4102029/cluster.yaml.txt)
* Operator's logs, if necessary
[operator.log](https://github.com/rook/rook/files/4102036/operator.log)
* Crashing pod(s) logs, if necessary
[osd-0.log](https://github.com/rook/rook/files/4102041/osd-0.log)

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
* Kernel (e.g. `uname -a`):
4.15.0-74-generic
* Cloud provider or hardware configuration:
OnPrem VMWare
* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.1.7
go: go1.11
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
* Kubernetes version (use `kubectl version`):
Major:"1", Minor:"15", GitVersion:"v1.15.5"
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN 1 filesystem is degraded; 1 MDSs report slow metadata IOs; 2 osds down; 3 hosts (3 osds) down; 1 root (3 osds) down; Reduced data availability: 144 pgs inactive

**Comment by leseb** [comment]
First, please upgrade to the latest stable Ceph version 14.2.6.
Then if not solved open an issue against https://tracker.ceph.com/ under RADOS.

Thanks.

**Comment by mjrepo2** [comment]
We updated our Rook/Ceph to latest versions, now when we edit the limits on the cephcluster resource they are not applied to the OSDs or the OSDs Replicasets.
We are doing this with: `"kubectl -n rook-ceph patch cephcluster rook-ceph -p '{\"path\": \"/spec/resources\", \"value\": {\"osd\": { \"limits\": {\"memory\": \"3Gi\"}, \"requests\": {\"memory\": \"3Gi\"}}}}' --type merge"`
