### ISSUE TITLE
Inject Config into mon

### ISSUE THREAD

**Issue by metti-himself** [rook/rook#4739]
**Is this a bug report or feature request?**
* Bug Report
Im trying to fix a health Warning:

```
HEALTH_WARN 1 pools have many more objects per pg than average
MANY_OBJECTS_PER_PG 1 pools have many more objects per pg than average
```
```
ceph tell mon.* injectargs '--mon_pg_warn_max_object_skew -1'
mon.e: injectargs:mon_pg_warn_max_object_skew = '-1.000000' (not observed, change may require restart) 
mon.f: injectargs:mon_pg_warn_max_object_skew = '-1.000000' (not observed, change may require restart) 
mon.h: injectargs:mon_pg_warn_max_object_skew = '-1.000000' (not observed, change may require restart)

```
**Deviation from expected behavior:**
The Warning is still ongoing, I restarted all mons, restarted the mgr. I tried to edit the rook-ceph-config and added the config option there, restarted the mons and mgr again but the warning is still there

**Expected behavior:**
The Warning disappears.

**How to reproduce it (minimal and precise):**
Ceph FS with lots of small files, and other pools that are not that high utilized

```
POOLS:
    POOL                          ID     STORED      OBJECTS     USED        %USED     MAX AVAIL 
    replicapool                    1     9.1 GiB       2.83k      27 GiB      0.77       1.1 TiB 
    s3-rgw.rgw.control             5         0 B           8         0 B         0       1.1 TiB 
    s3-rgw.rgw.meta                6     2.7 KiB           9     385 KiB         0       1.1 TiB 
    s3-rgw.rgw.log                 7     4.0 MiB         212     4.1 MiB         0       1.1 TiB 
    s3-rgw.rgw.buckets.index       8     538 MiB           9     538 MiB      0.01       1.1 TiB 
    .rgw.root                      9     3.7 KiB          16     720 KiB         0       1.1 TiB 
    s3-rgw.rgw.buckets.data       10     403 GiB     357.12k     1.2 TiB     25.66       1.1 TiB 
    s3-rgw.rgw.buckets.non-ec     11     6.6 KiB           4      70 KiB         0       3.4 TiB 
    cephfs-metadata        14     3.1 GiB       1.09M     3.6 GiB      0.10       1.1 TiB 
    cephfs-data0           15      69 GiB     915.57k     221 GiB      5.90       1.1 TiB

```
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* CentOS 7
* 5.3.9
* Custom Bare Metal Setup (1 Master + 3 Worker)
* v1.1.2
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.1
* Kubernetes version (use `kubectl version`): v1.15.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
ceph health
HEALTH_WARN 1 pools have many more objects per pg than average

**Comment by leseb** [comment]
Use `ceph config set` command instead.

**Comment by metti-himself** [comment]
> Use `ceph config set` command instead.

This fixed it: ceph config set mgr mon_pg_warn_max_object_skew 0

Thanks!
