### ISSUE TITLE
[CEPH:Mirroring] Failed to check ceph status from one ceph cluster to another ceph cluster

### ISSUE THREAD

**Issue by shaekhhasanshoron** [rook/rook#4749]
I was trying to implement mirroring feature between two ceph clusters deployed on kubernetes using rook on different data centers. But I am facing some issues with connection from master cluster to the remote cluster. I have copied the configuration and keyring file from toolbox pod of remote ceph cluster to the toolbox pod of master ceph cluster and saved as "remote.conf" & "remote.client.admin.keyring". Since the monitor pods are in two different kubernetes clusters with different networks, in remote.conf file I have updated the mon_host ip with the remote server ip and changed the port from default 6789 to a nodeport that targets 6798.

When I am trying to check the connection/status by the following command, it always gives timeout. In the following "124.92.94.105" is the server ip and "32201" is the nodeport
```
[root@rook-ceph-tools-58df7d6b5c-rpff4 ceph]#  ceph status --connect-timeout=30 --cluster=ceph --conf=/etc/ceph/remote.conf --keyring=/etc/ceph/remote.client.admin.keyring
timed out

[root@rook-ceph-tools-58df7d6b5c-rpff4 ceph]# curl -v 124.92.94.105:32201
* About to connect() to 124.92.94.105 port 32201 (#0)
*   Trying 124.92.94.105...
* Connected to 124.92.94.105 (124.92.94.105) port 32201 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 124.92.94.105:32201
> Accept: */*
>
ceph v027▒

```
Can anyone please give any idea what I am doing wrong or what should be done?
And, it will be very much helpful if anyone can provide the full procedure of how to do mirroring ceph with the above setup.

**Comment by vahide** [comment]
You shoud put master mon ip and **user** keyring in remote rook-config-override by command:
`kubectl -n rook-ceph edit configmap rook-config-override`
Follow ceph rbd mirroring URL:[https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html/block_device_guide/block_device_mirroring](url)
