### ISSUE TITLE
Ceph key user secret must be added in every namespace that is accessible to Rook clusters

### ISSUE THREAD

**Issue by kokhang** [rook/rook#475]
In order for the Kubernetes to attach/detach rook block images, a secret must be present containing the user ceph key in the namespace of the pod consuming the block image. Rook operator should watch for namespaces and create a ceph key secret for every namespace.

Currently, rook-operator creates an user and an associated secret for the `default` namespace. We should do the same for every namespace.

The rook-operator should create a ceph user and a equivalent secret for that user on that namespace.

**Comment by kokhang** [comment]
We could also incorporate a white list where we use labels to define which namespaces can have access to the cluster. We can also do this in a different PR.

**Comment by kokhang** [comment]
This is also needed for new volume plugin as well. https://github.com/rook/rook/issues/432

**Comment by jbw976** [comment]
Instead of adding the ceph key as a secret to every k8s namespace, could the provisioner in the operator check to see what namespace the pod with the PVC is running in?  Then, it could create the secret only in that namespace instead of all. I would assume this would be done in the Provision function: https://github.com/rook/rook/blob/master/pkg/operator/provisioner.go#L63

**Comment by kokhang** [comment]
@jbw976 Yes that could be done. Then it begs the question about how to manage this secret. Should the provisioner delete it once the pvc is deleted? 

I think it is more beneficial to do this on a namespace level. We can also provide while/black list so that we can specify which namespaces (whether they have been created or not) allow to consume Rook storages.

**Comment by bassam** [comment]
The approach taken by #870 suffers from race conditions where the PV might be created before the secret is propagated. To solve this we need to ensure that we are on the "attach" path for the volume which requires a rook specific plugin.

Stepping back a bit, we have a rook volume plugin in the works now and it does not need any secrets. If the flex volume holds it might be portable to older version of Kubernetes. Maybe we should just wait for that instead.

**Comment by liggitt** [comment]
FYI, copying secrets for a PV into the namespace of the PVC is not recommended, and is being corrected for ceph in https://github.com/kubernetes/kubernetes/pull/49502

**Comment by bassam** [comment]
@liggitt thanks for the update. More validation that we should abandon the approach of copying secrets around. Do you know if similar improvement is also planned for the RBD volume source?

**Comment by flemzord** [comment]
A workaround for this problem?

**Comment by jbw976** [comment]
Here's some documentation to help you copy the secret from the default namespace to the namespace that you will be declaring the PVC in: https://rook.io/docs/rook/master/k8s-block.html#secrets

**Comment by jbw976** [comment]
Note that this work won't be needed with the local agent design that handles Flexvolume requests described in #924

**Comment by calvix** [comment]
Is there any solution coming up? work around with copying secret is not a good solution for dynamic environments where namespaces are generated.

**Comment by galexrt** [comment]
@calvix I think the good thing about having to copy the secrets to every namespace in which you want to use storage is, that you have the control about who can create/use storage. Else this would be a problem for shared cluster in which not everyone may should have storage access.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/49502 allows putting ceph secrets for provisioned PVs in a namespace separate from the PVC namespaces

**Comment by jbw976** [comment]
@calvix yes, with the ongoing work on the Rook volume plugin, there will no longer be a need to copy secrets to other namespaces.  You can read about the design here:
https://github.com/rook/rook/blob/master/design/local-node-agent.md#improvements-over-rooks-current-support-for-persistent-volumes

The pull request for the code implementation (work in progress) can be found here:
https://github.com/rook/rook/pull/882

**Comment by kokhang** [comment]
With #882, this is no longer needed
