### ISSUE TITLE
Object store swift gateway

### ISSUE THREAD

**Issue by vahide** [rook/rook#4754]
I want to put ceph object store as openstack swift back end. I put keystone info in rook-config-override.
```
data:
  config: |
[client.rgw.swift.a]
    rgw keystone url =  http://X.X.X.X
    rgw keystone admin user = ADMIN
    rgw keystone admin password = ***************
    rgw keystone admin tenant = ADMIN
    rgw keystone accepted roles =  _member_,admin,swiftoperator
    rgw keystone token cache size = 200
    rgw keystone revocation interval = 300
```
 And put gateway type as swift in object store CRD.
```
 gateway:
    # type of the gateway (s3)
    type: Swift
```
When I curl ceph rgw endpoint, s3 type is responded.
How can I use swift gateway in object store?

**Comment by leseb** [comment]
Interestingly, as far as I can see, this option is not used anywhere. @travisn any idea?
So `type: Swift` does nothing.

**Comment by travisn** [comment]
Correct, only `s3` is currently supported by rook. @mkogan1 Thoughts on what it would take to support swift in place of s3?

**Comment by mattbenjamin** [comment]
@travisn it seems to involve (as hinted in the crd text) configuring the appropriate RGW conf params to attach to the corresponding openstack cluster (via its keystone)--support for all the options described here, most likely:  https://docs.ceph.com/docs/master/radosgw/keystone/
