### ISSUE TITLE
Slow operator restart

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4756]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The provision pods are running unnecessary commands which take lots of time. For example:

```
2020-01-28 18:05:41.624474 I | cephosd: configuring osd devices: {"Entries":{}}
2020-01-28 18:05:41.724306 I | exec: Running command: ceph-volume lvm batch --prepare
2020-01-28 18:07:14.824378 I | cephosd: no more devices to configure
2020-01-28 18:07:14.924304 I | exec: Running command: ceph-volume lvm list  --format json
```
If the list of OSDs to configure is empty, what is it doing for 2 minutes? Is it possible to skip the steps that are not needed?

**Expected behavior:**
Restarting operator without cluster modifications is quick

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
1.2.2

**Comment by dimm0** [comment]
Much better with

```
provision 2020-02-10 21:40:23.870244 I | cephosd: skipping device "sdg1" because it is a partition and ceph version is too old, you need at least ceph "14.2.8-0 nautilus"
provision 2020-02-10 21:40:23.870254 I | cephosd: skipping device "sdg2" because it is a partition and ceph version is too old, you need at least ceph "14.2.8-0 nautilus"
provision 2020-02-10 21:40:23.870262 I | cephosd: skipping device "sde2" because it is a partition and ceph version is too old, you need at least ceph "14.2.8-0 nautilus"
```

Closing

**Comment by dimm0** [comment]
Although it's interesting that it requires an unreleased version of ceph...

**Comment by travisn** [comment]
@dimm0 on a related note, once v14.2.8 is running, if you are using `useAllDevices: true` (or another `deviceFilter` that matches partitions, Rook will attempt to create OSDs on the partitions as long as they don't have a filesystem. Any concern with that? See #4724

**Comment by dimm0** [comment]
Looks fine for me. I'm only using full drives, and specifying all names explicitly per node
