### ISSUE TITLE
Rook-operator should watch mon pod IPs and create/update a configmap

### ISSUE THREAD

**Issue by kokhang** [rook/rook#476]
Currently, there is no easy way for user to find the mon-IPs. Currently the user has to query the mon pods and parse the IPs. This will cause issues if the Pod IPs changes. Rook-operator should watch the mon-pods and track their IPs in a configmap. With rook-operator watching the mon-pods, opens up the possibility to mon-pod migration when mon-pod dies.

**Comment by kokhang** [comment]
This is needed by the new rook volume plugin. https://github.com/rook/rook/issues/432

**Comment by travisn** [comment]
This was done as part of #356
