### ISSUE TITLE
OSD raw mode (no LVM) for the non-PVC devices

### ISSUE THREAD

**Issue by travisn** [rook/rook#4768]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
With the recent changes to the OSDs to remove use of LVM, this will be a very positive change also in other areas beyond what was done by #4435. The common case is where OSDs are running on a raw device or partition with no PVC, no metadataDevice specified, and no encryption required. We will still need c-v to create the LVs to support metadataDevice and encryption. But the common case without those options has no need to use LVM, so will benefit from using c-v raw mode.

**What is use case behind this feature:**
Removing LVM where not needed.

**Comment by leseb** [comment]
I think it's doable easily for the all-in-one use case where block/db/wal are on the same device. However, once people will try to allocate metadata device (because we don't run on PVC) we will fallback to the LVM mode. This might be confusing for some users...
We wait to hold on that transition once LSO is here and ready to use.

Still need more thoughts I guess but nothing really prevents us from doing this today.

**Comment by travisn** [comment]
> I think it's doable easily for the all-in-one use case where block/db/wal are on the same device. However, once people will try to allocate metadata device (because we don't run on PVC) we will fallback to the LVM mode. This might be confusing for some users...
> We wait to hold on that transition once LSO is here and ready to use.
> 
> Still need more thoughts I guess but nothing really prevents us from doing this today.

Using the whole device is the most common scenario, so if we can get rid of LVM in the most common case it would be a good thing, rather than waiting for all other scenarios to be covered. We would just need to still fall back to LVM if 1) using a separate metadata device (non-PV), 2) multiple OSDs per device, or 3) encryption. Any others?

If it's a complicated change to support, maybe we hold off for now, I'm just assuming it will be a reasonably small change.

**Comment by leseb** [comment]
Change needed in c-v https://github.com/ceph/ceph/pull/33371

**Comment by leseb** [comment]
Moving to 1.5.
