### ISSUE TITLE
OSD orchestration inconsistency

### ISSUE THREAD

**Issue by eknudtson** [rook/rook#4771]
**Is this a bug report or feature request?**
* Bug Report
OSDs are unnecessarily restarting during orchestrations due to what appears to be inconsistent ordering of crush map locations in the OSD command args.

**Deviation from expected behavior:**
OSDs are restarting during orchestrations when they should have no changes applied.

**Expected behavior:**
OSDs with no changes do not restart during an orchestration

**How to reproduce it (minimal and precise):**
Our OSDs have the following `--crush-location` flag variations: 

`--crush-location=root=default host=worker-blah zone=myzone region=myregion`
`--crush-location=root=default host=worker-blah region=myregion zone=myzone`

Note that the zone and region ordering are inconsistent.  The operator is restarting OSDs apparently randomly to swap this ordering, when no restarts should be happening.

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7.7.1908
* Kernel (e.g. `uname -a`):3.10.0-1062.9.1.el7.x86_64
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): 1.2.2
* Storage backend version (e.g. for ceph do `ceph -v`): ceph 1.14.5
* Kubernetes version (use `kubectl version`): 1.16.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): healthy

**Comment by travisn** [comment]
This was actually just fixed by #4729. It will be included in the v1.2.3 release, targeted for the next couple of days. Thanks!

**Comment by eknudtson** [comment]
Cool, I missed that. Much appreciated!
