### ISSUE TITLE
docs: write short guide for how to respond to Ceph HEALTH_WARN

### ISSUE THREAD

**Issue by riking** [rook/rook#4775]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Write a short guide and link it from the Ceph quickstart & other documents that talks about the dangers of ignoring a HEALTH_WARN and how to investigate and fix it when it occurs.

This can consist mostly of links to other existing resources, but it's important to be on the Rook Ceph site.

**What is use case behind this feature:**
Ignoring a HEALTH_WARN indefinitely will lead to a broken cluster and likely loss of data, and it's important that operators are informed and know to be watching out for it.

**Environment**:

Ceph

**Comment by travisn** [comment]
What about adding a section in the [common issues](https://rook.io/docs/rook/v1.2/ceph-common-issues.html) doc?
