### ISSUE TITLE
rook-ceph helm chart problem with kubernetes 1.17.1

### ISSUE THREAD

**Issue by pcornelissen** [rook/rook#4781]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Helm chart does not work with recent kubectl+kubernetes

**Expected behavior:**
It works ;-)

**How to reproduce it (minimal and precise):**
```
pcornelissen@orchit-mac:.../setup/maintenance$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
pcornelissen@orchit-mac:.../setup/maintenance$ helm install rook --namespace rook-ceph-system rook-stable/rook-ceph
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1"]
```
**Environment**:
* OS (e.g. from /etc/os-release): MAC
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.17.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Dragnell87** [comment]
Can confim:
OS: Ubuntu 18.04 & Centos 7
Kubernetes version (use kubectl version): 1.17.2
Kubernetes cluster Rancher

**Comment by greyman-hh** [comment]
Confirm:
OS CentOS 8
KRE 1.17.2, Rancher 2.3.5

Failed to install app rook-ceph. Error: validation failed: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1"]

**Comment by Dragnell87** [comment]
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

NetworkPolicy (in the extensions/v1beta1 API group)
Migrate to use the networking.k8s.io/v1 API, available since v1.8. Existing persisted data can be retrieved/updated via the networking.k8s.io/v1 API.

PodSecurityPolicy (in the extensions/v1beta1 API group)
Migrate to use the policy/v1beta1 API, available since v1.10. Existing persisted data can be retrieved/updated via the policy/v1beta1 API.

DaemonSet, Deployment, StatefulSet, and ReplicaSet (in the extensions/v1beta1 and apps/v1beta2 API groups)
Migrate to use the apps/v1 API, available since v1.9. Existing persisted data can be retrieved/updated via the apps/v1 API.

**Comment by travisn** [comment]
All of these updates were made long ago and I can't find any references in the code base to those obsolete api versions now. Our integration tests are also installing the helm chart on v1.17.2. I see a reference to the [PodSecurityPolicy](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/psp.yaml#L14-L15) in the helm chart that uses `apiVersion: policy/v1beta1`, but not the obsolete api version.

@Dragnell87 @greyman-hh Can you confirm which version of rook you're installing?

**Comment by pcornelissen** [comment]
My laptop is fairly new, so I used a new install of helm (3) and the rook-stable   	repo https://charts.rook.io/stable, so maybe the repo is out of date?

```
pcornelissen@orchit-mac:~$ helm install rook --namespace rook-ceph-system-test rook-stable/rook-ceph
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1"]

pcornelissen@orchit-mac:~$ helm search repo rook
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
rook-stable/rook-ceph	v0.9.3       	           	File, Block, and Object Storage Services for yo...
```

**Comment by Dragnell87** [comment]
Yes, using release repo, and not having this problem https://charts.rook.io/release.

**Comment by pcornelissen** [comment]
So maybe the release should be promoted to stable soon, so people can use it on recent kubernetes versions :-)

**Comment by travisn** [comment]
Aha! We need to remove the stable/beta/alpha channels. They have been obsolete for some time. Now we are only using the `release` channel. See the Rook helm docs [here](https://rook.io/docs/rook/v1.2/helm-operator.html) that discuss the release channel.

**Comment by pcornelissen** [comment]
Ah ok, yeah then it would be good to get rid of that old stuff. It just confuses people

**Comment by greyman-hh** [comment]
> All of these updates were made long ago and I can't find any references in the code base to those obsolete api versions now. Our integration tests are also installing the helm chart successfully on v1.17.2. I see a reference to the [PodSecurityPolicy](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/psp.yaml#L14-L15) in the helm chart that uses `apiVersion: policy/v1beta1`, but not the obsolete api version.
> 
> @Dragnell87 @greyman-hh Can you confirm which version of rook you're installing?

Ok, I loaded the wrong repo. V1.2.4 installs fine now.

**Comment by Dragnell87** [comment]
Same, using release now, But stuck at https://github.com/rook/rook/issues/4827 so there is that . This issue could be close

**Comment by pcornelissen** [comment]
I'd still suggest to remove the stable channel, as it is referenced in some blog posts regarding rook and this leads to unhappy rook newbies ;-)
