### ISSUE TITLE
build : docker image building fails while downloading tini

### ISSUE THREAD

**Issue by thotz** [rook/rook#4801]
While building image for rook/ceph fails with following error 
=== docker build build-6d836edb/ceph-amd64
Sending build context to Docker daemon  78.59MB
Step 1/10 : FROM ceph/ceph-amd64:v14.2.6-20200115
 ---> 0fe3d0247e54
Step 2/10 : ARG ARCH
 ---> Using cache
 ---> a0ac862376e8
Step 3/10 : ARG TINI_VERSION
 ---> Using cache
 ---> 43e024b070e1
Step 4/10 : RUN curl --fail -sSL -o /tini https://github.com/krallin/tini/releases/download/v0.16.1/tini-amd64 &&     chmod +x /tini
 ---> Running in 35161204c37a
curl: (6) Could not resolve host: github.com; Unknown error
The command '/bin/sh -c curl --fail -sSL -o /tini https://github.com/krallin/tini/releases/download/v0.16.1/tini-amd64 &&     chmod +x /tini' returned a non-zero code: 6
make[2]: *** [do.build] Error 6
make[1]: *** [ceph.linux_amd64] Error 2
make: *** [build] Error 2

manually executing the same step passes without any issue
# curl --fail -sSL -o /tini https://github.com/krallin/tini/releases/download/v0.16.1/tini-amd64 &&     chmod +x /tini
# echo $?
0
# ls /tini 
/tini

firewalld is disabled and selinux is permissive mode

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Build is failing

**Expected behavior:**
build should pass and image need to be created

**How to reproduce it (minimal and precise):**

clone the repo on rhel 7
swich to release 1.12 branch
make -j4 IMAGES="ceph

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): rhel 7
* Kernel (e.g. `uname -a`): 3.10.0-862.3.3.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.12
* Storage backend version (e.g. for ceph do `ceph -v`): 
* Kubernetes version (use `kubectl version`): v1.17.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
Did you try to re-run the build? Is it happening all the time? Or once?

**Comment by thotz** [comment]
> Did you try to re-run the build? Is it happening all the time? Or once?

it is reproducible on two machines, it happens when I clone the new repo and do make -j4 IMAGES="ceph". If I do make -j4 and followed by make -j4 "images=ceph". This is no seen IMO

I have another query do "make distclean" should remove all the files (including .cache directory created inside the repo) ?
@leseb

**Comment by leseb** [comment]
AFAICT this https://github.com/krallin/tini/releases/download/v0.16.1/tini-amd64 is reachable for me and the CI is passing that step all the time, so I believe it's on your side.

**Comment by thotz** [comment]
Exactly. I can do the same from my machine as well, Only from make I see this issue

curl --fail -sSL -o /tini https://github.com/krallin/tini/releases/download/v0.16.1/tini-amd64 && chmod +x /tini
echo $?
0

ls /tini
/tini


Firewall is disabled  and selinux is permissive mode as well

**Comment by thotz** [comment]
closing this issue, since I have seen it long time ago
