### ISSUE TITLE
Agent pods is not created after running kubectl -f apply operator.yaml

### ISSUE THREAD

**Issue by Jimmol-Singh** [rook/rook#4804]
OS: Ubuntu 16.04
Kernel: 4.4.0-170-generic
Rook version: v1.2.3

Hello,

I'm facing a problem where my agent pod is not created when I run kubectl -f apply operator.yaml

`kubectl get pods -n rook-ceph`

NAME                                  READY   STATUS    RESTARTS   AGE
rook-ceph-operator-79d66f97c8-cgsll   1/1     Running   1          45m
rook-discover-5nn6d                   1/1     Running   0          30m
rook-discover-8nrtq                   1/1     Running   0          30m
rook-discover-zwnqc                   1/1     Running   0          30m

I believe the operator pod  should automatically create the agent pod as seen in other example but I dont see it here.

Thanks!

**Comment by Madhu-1** [comment]
Flex driver is disabled by default, if you want to use it please enable it during operator deployment see
  https://github.com/rook/rook/blob/3a3394ae32f72525f49a5d5d230b366ae049aa00/cluster/examples/kubernetes/ceph/operator.yaml#L169

**Comment by Madhu-1** [comment]
CSI driver will be enabled by default in rook 1.2

**Comment by Jimmol-Singh** [comment]
Thanks! The agent pod is up and running after I ran cluster.yaml. Which is weird because I thought the operator.yaml file would start the agent pod along with the discover pod. Oh well, either way before I would ran the cluster.yaml file but the agent pod wouldn't show up but after changing line 169 in operator.yaml to 'true', the agent pod is running.

rook-ceph-agent-2ggnj                           1/1     Running             0          63s
rook-ceph-agent-tb22b                           1/1     Running             0          63s
rook-ceph-agent-wp8g2                           1/1     Running             0          63s
rook-ceph-operator-6d8b9d4d45-x5fx8             1/1     Running             3          70m
rook-discover-2vjm9                             1/1     Running             0          57m
rook-discover-6jtz6                             1/1     Running             0          57m
rook-discover-l4rlj                             1/1     Running             0          57m
