### ISSUE TITLE
unable to map block device with rbd tool in toolbox pod

### ISSUE THREAD

**Issue by jbw976** [rook/rook#481]
There are a few issues with trying to map a block device using the `rbd` tool in the toolbox pod. These are the steps as given by http://tracker.ceph.com/projects/ceph/wiki/Benchmark_Ceph_Cluster_Performance#Benchmark-a-Ceph-Block-Device:
```
root@rook-tools:/# ceph osd pool create rbdbench 100 100
root@rook-tools:/# rbd create image101 --size 1024 --pool rbdbench
root@rook-tools:/# rbd map image101 --pool rbdbench --name client.admin
```

Note that some extra volume mounts were added to the toolbox in the hopes of getting `rbd` working.  Basically everything in the rook-client pod starting from https://github.com/rook/rook/blob/master/demo/kubernetes/rook-client/rook-client.yml#L12.

**First**, the rbd kernel module needs to be loaded and `modprobe` is not found.  This should be able to rectified by `apt-get install kmod` but #480 is preventing that.  I worked around by running `sudo modprobe rbd` on the host machine that is running the pod.

**Second**, the generated ceph config file in the toolbox at `/etc/ceph/ceph.config` does not specify `rbd_default_features` so the image that `rbd` creates has a full feature set that is not compatible with the environment.  I worked around this by adding the following to the `[global]` config section of the `/etc/ceph/ceph.config` file **before** running `rbd create`
```
rbd_default_features = 3
```

**Third**, the `rbd map` command hangs and I have no idea why.  The `/dev/rbd0` device does get created and is visible with `lsblk` but it does not get mapped to ` /dev/rbd/rbdbench/image101` as expected.  One suggestion to look further would be to use `strace` as directed in http://ceph-users.ceph.narkive.com/xiTpiO1U/fwd-rbd-map-command-hangs:
> Can you run 'rbd map' under strace, and when it hangs do SysRq+w followed by SysRq+t and send along strace and SysRq outputs?

**Comment by jbw976** [comment]
another option here would be to perform the create and map with the rook tool, that does work at least in the rook-client pod.

**Comment by bzub** [comment]
Did you add any HostPath Volumes to rook-tools when testing this?  The version I see doesn't have any.

Mimicking containerized kubelet and rook-client, you could mount the host's `/lib/modules`, `/dev`, and optionally `/usr/bin/modprobe` to the rook-tools pod.  It would need to be privileged too.

**Comment by jbw976** [comment]
Yes @bzub, I was using a private version of the rook-tools.yml that included those volume mounts and privileged setting (stole it from the rook-client).  I added a note to the issue description stating such.

**Comment by bzub** [comment]
Regarding `rbd map` hanging I'd look at `dmesg -T` if you haven't already on the node the pod is running on and perhaps it works on the pod itself just the same.  Usually errors with kRBD pop up there.

**Comment by jbw976** [comment]
With the fix for #480 (in PR #489), the `rook` tool can create and mount RBD images.  This may help with the `rbd` tool as well, but I have not tried that yet.

**Comment by jbw976** [comment]
This could be the exact same hang we saw in the end to end testing pods, where `rbd map` is waiting on a socket with udev events from the kernel.  Try the toolbox pod with host networking and see if that fixes the `rbd map` hang.

**Comment by travisn** [comment]
@jbw976 is this an issue or do we even need to worry about it anymore with the new flex volume plugin?

**Comment by jbw976** [comment]
`rookctl` can map rbd block images inside the toolbox and that is sufficient for me.  i don't see a use case where we really need to worry about `rbd map` working.
