### ISSUE TITLE
PVC OSD prepare CrashLoopBackoff if PV not blank

### ISSUE THREAD

**Issue by michael-db** [rook/rook#4810]
Rook 1.2.3 but from a quick look at the source code the bug appears still to be present on master.
On this line in pkg/daemon/ceph/osd/daemon.go
```
	if agent.pvcBacked && !deviceOSDs[0].SkipLVRelease && !deviceOSDs[0].LVBackedPV {
```
deviceOSDs is empty.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```
kubectl -n rook-ceph logs pod/rook-ceph-osd-prepare-set1-0-data-crh7d-jfshs
...
2020-02-04 12:09:56.737181 I | cephosd: 0 ceph-volume osd devices configured on this node
2020-02-04 12:09:56.737271 I | cephosd: devices = []
2020-02-04 12:09:56.740326 I | cephosd: configuring osd dirs: map[]
2020-02-04 12:09:56.740338 I | cephosd: saving osd dir map
2020-02-04 12:09:56.740343 I | cephosd: device osds:[]
dir osds: []
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/rook/rook/pkg/daemon/ceph/osd.Provision(0xc0006dc0f0, 0xc000737c00, 0xc0006379a0, 0x1f, 0xc000620cc0, 0xf)
	/home/rook/go/src/github.com/rook/rook/pkg/daemon/ceph/osd/daemon.go:263 +0x15ef
github.com/rook/rook/cmd/rook/ceph.prepareOSD(0x32da040, 0x330c308, 0x0, 0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/cmd/rook/ceph/osd.go:264 +0x6e8
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).execute(0x32da040, 0x330c308, 0x0, 0x0, 0x32da040, 0x330c308)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x32dc3e0, 0x32dcfc0, 0x32dc640, 0x32dc8a0)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).Execute(0x32dc3e0, 0x4056a0, 0xc00008e058)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/rook/go/src/github.com/rook/rook/cmd/rook/main.go:35 +0x36
```

**Expected behavior:**

Clean failure instead of crash if the PV is not cleared for use.

**How to reproduce it (minimal and precise):**

Populate storageClassDeviceSets in the cluster yaml, count:1 is enough.
Provide a PV that is not blank, e.g., not wiped from a previous test cluster.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):Ubuntu 18.04.3
* Kernel (e.g. `uname -a`): Linux ubuntu2 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.2.3
* Storage backend version (e.g. for ceph do `ceph -v`):14.2.6
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
I guess I can fix it as part of https://github.com/rook/rook/issues/3852
