### ISSUE TITLE
Ceph volume attachment timeout

### ISSUE THREAD

**Issue by stephan2012** [rook/rook#4814]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When a Pod is created a CephFS volume attachment runs into a timeout. The csi-attacher logs in csi-cephfsplugin-provisioner show:

```
E0205 09:14:05.479583       1 leaderelection.go:341] Failed to update lock: configmaps "external-attacher-leader-rook-ceph-cephfs-csi-ceph-com" is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-cephfs-provisioner-sa" cannot update resource "configmaps" in API group "" in the namespace "rook-ceph"
I0205 09:14:05.479627       1 leaderelection.go:222] failed to acquire lease rook-ceph/external-attacher-leader-rook-ceph-cephfs-csi-ceph-com
```

Maybe #3975 is related.

**Expected behavior:**
Volume attachments succeed.

**How to reproduce it (minimal and precise):**

Not sure. Rook Ceph Operator was provisioned with some 1.2.x version and has since been upgraded to the latest version.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS
* Kernel (e.g. `uname -a`): `Linux n0200 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): `v1.2.3`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.6 (f0aa067ac7a02ee46ea48aa26c6e298b5ea272e9) nautilus (stable)`
* Kubernetes version (use `kubectl version`): 1.15.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `kubeadm`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN` (`1 pools have too few placement groups`)

**Comment by stephan2012** [comment]
Looks like roles `cephfs-external-provisioner-cfg` and `rbd-external-provisioner-cfg` lack the `update`verb for `configmap` resources. After 

```diff
--- a   2020-02-05 10:35:42.042991149 +0100
+++ b   2020-02-05 10:35:36.854940197 +0100
@@ -30,6 +30,7 @@
     - list
     - create
     - delete
+    - update
   - apiGroups:
     - coordination.k8s.io
     resources:
```

everything seems to work as expected.

**Comment by travisn** [comment]
@stephan2012 Did you enable the CSI 2.0 driver, or this is just with the rook defaults (that don't run CSI 2.0 yet)? 
@Madhu-1 Do you know the related change in the CSI driver that required updating the configmap? I'd like to understand what versions of csi/rook would be affected by this missing permission.

**Comment by stephan2012** [comment]
> @stephan2012 Did you enable the CSI 2.0 driver, or this is just with the rook defaults (that don't run CSI 2.0 yet)?

No, just defaults:

```yaml
        - name: ROOK_CSI_CEPH_IMAGE
          value: private.registry.local/quay.io/cephcsi/cephcsi:v1.2.2
        - name: ROOK_CSI_REGISTRAR_IMAGE
          value: private.registry.local/quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
        - name: ROOK_CSI_PROVISIONER_IMAGE
          value: private.registry.local/quay.io/k8scsi/csi-provisioner:v1.4.0
        - name: ROOK_CSI_SNAPSHOTTER_IMAGE
          value: private.registry.local/quay.io/k8scsi/csi-snapshotter:v1.2.2
        - name: ROOK_CSI_ATTACHER_IMAGE
          value: private.registry.local/quay.io/k8scsi/csi-attacher:v1.2.0
```

Helm values:

```yaml
image:
  repository: 'private.registry.local/rook/ceph'
  tag: 'v1.2.3'

hyperkube:
  repository: 'private.registry.local/hyperkube'

csi:
  cephcsi:
    image: private.registry.local/quay.io/cephcsi/cephcsi:v1.2.2
  registrar:
    image: private.registry.local/quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
  provisioner:
    image: private.registry.local/quay.io/k8scsi/csi-provisioner:v1.4.0
  snapshotter:
    image: private.registry.local/quay.io/k8scsi/csi-snapshotter:v1.2.2
  attacher:
    image: private.registry.local/quay.io/k8scsi/csi-attacher:v1.2.0

enableFlexDriver: false
```

(This is the full `values.yaml` file)

**Comment by Madhu-1** [comment]
leaderelection should be of type leases for external-attacher see https://github.com/kubernetes-csi/external-attacher/blob/v1.2.1/cmd/csi-attacher/main.go#L72

if the atttacher image is v1.2.0 we are setting the leaderelection type to leases in the template also https://github.com/rook/rook/blob/release-1.2/pkg/operator/ceph/csi/spec.go#L223  and https://github.com/rook/rook/blob/v1.2.3/cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml#L26

if you can provide the steps to reproduce it, I can check what is the exact issue, updating the configmap rules is not a fix for this one,  as using configmap for leader election is not a good option.

**Comment by stephan2012** [comment]
Using leases over configmaps perfectly makes sense.

However, I'd prefer a quick fix now and a general solution later. Right now it takes manual intervention to prevent volume attachment timeouts after updating the operator Helm chart.

**Comment by Madhu-1** [comment]
@stephan2012 can you please paste cephfs deployment template

**Comment by stephan2012** [comment]
@Madhu-1: Do you need more besides https://github.com/rook/rook/issues/4814#issuecomment-582973627?

**Comment by Madhu-1** [comment]
@stephan2012 yes I would like to see cephfs deployment and attacher built  version

```
kubectl get deployment csi-cephfsplugin-provisioner -nrook-ceph -oyaml
```
and also attacher version from attacher container
```
kubectl logs po/csi-cephfsplugin-provisioner-56c8b7ddf4-rb2cz -c csi-attacher -nrook-ceph
I0207 06:41:49.938934       1 main.go:95] Version: v1.2.0-0-g834bae5
```

**Comment by stephan2012** [comment]
Here we go. CephFS provisioner plugin:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-01-31T18:53:23Z"
  generation: 17
  name: csi-cephfsplugin-provisioner
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: core/v1
    kind: ConfigMap
    name: rook-ceph-csi-config
    uid: a3365443-0d18-4ff0-8de5-76a373cd95be
  resourceVersion: "15600146"
  selfLink: /apis/extensions/v1beta1/namespaces/rook-ceph/deployments/csi-cephfsplugin-provisioner
  uid: 18c98bcd-9404-4ad4-8ab7-8010a5e56511
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-cephfsplugin-provisioner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-cephfsplugin-provisioner
        contains: csi-cephfsplugin-metrics
    spec:
      affinity: {}
      containers:
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --leader-election=true
        - --timeout=150s
        - --leader-election-namespace=rook-ceph
        env:
        - name: ADDRESS
          value: /csi/csi-provisioner.sock
        image: private.registry.domain/quay.io/k8scsi/csi-attacher:v1.2.0
        imagePullPolicy: IfNotPresent
        name: csi-attacher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --v=5
        - --timeout=150s
        - --retry-interval-start=500ms
        - --enable-leader-election=true
        - --leader-election-type=leases
        - --leader-election-namespace=rook-ceph
        env:
        - name: ADDRESS
          value: unix:///csi/csi-provisioner.sock
        image: private.registry.domain/quay.io/k8scsi/csi-provisioner:v1.4.0
        imagePullPolicy: IfNotPresent
        name: csi-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --nodeid=$(NODE_ID)
        - --type=cephfs
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --controllerserver=true
        - --drivername=rook-ceph.cephfs.csi.ceph.com
        - --metadatastorage=k8s_configmap
        - --pidlimit=-1
        - --metricsport=9091
        - --forcecephkernelclient=true
        - --metricspath=/metrics
        - --enablegrpcmetrics=true
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CSI_ENDPOINT
          value: unix:///csi/csi-provisioner.sock
        image: private.registry.domain/quay.io/cephcsi/cephcsi:v1.2.2
        imagePullPolicy: IfNotPresent
        name: csi-cephfsplugin
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /sys
          name: host-sys
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /dev
          name: host-dev
        - mountPath: /etc/ceph-csi-config/
          name: ceph-csi-config
        - mountPath: /tmp/csi/keys
          name: keys-tmp-dir
      - args:
        - --type=liveness
        - --endpoint=$(CSI_ENDPOINT)
        - --metricsport=9081
        - --metricspath=/metrics
        - --polltime=60s
        - --timeout=3s
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi-provisioner.sock
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: private.registry.domain/quay.io/cephcsi/cephcsi:v1.2.2
        imagePullPolicy: IfNotPresent
        name: liveness-prometheus
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-csi-cephfs-provisioner-sa
      serviceAccountName: rook-csi-cephfs-provisioner-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: socket-dir
      - hostPath:
          path: /sys
          type: ""
        name: host-sys
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /dev
          type: ""
        name: host-dev
      - configMap:
          defaultMode: 420
          items:
          - key: csi-cluster-config-json
            path: config.json
          name: rook-ceph-csi-config
        name: ceph-csi-config
      - emptyDir:
          medium: Memory
        name: keys-tmp-dir
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-01-31T18:53:24Z"
    lastUpdateTime: "2020-02-01T07:19:14Z"
    message: ReplicaSet "csi-cephfsplugin-provisioner-75bc5868d5" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-02-06T12:51:05Z"
    lastUpdateTime: "2020-02-06T12:51:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 17
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
```
Attacher version:

```bash
$ kubectl logs csi-cephfsplugin-provisioner-75bc5868d5-rtl4m -c csi-attacher -n rook-ceph |grep -i version
I0206 09:46:47.783733       1 main.go:95] Version: v1.2.0-0-g834bae5
I0206 09:46:47.803929       1 connection.go:183] GRPC response: {"name":"rook-ceph.cephfs.csi.ceph.com","vendor_version":"v1.2.2"}
```

Please let me know if you need more input.

**Comment by Madhu-1** [comment]
as expected the leaderelection is not set in deployment thats why its using default type which is configmap

here is what is suggest you for a workaround

can you please update the attacher image to v2.1.0 and apply RBAC mentioned in https://github.com/rook/rook/blob/v1.2.3/Documentation/ceph-upgrade.md#enabling-the-csi-v20-driver

that should fix this issue.

@travisn do  you have any idea why this is not getting hit https://github.com/rook/rook/blob/v1.2.3/pkg/operator/ceph/csi/spec.go#L229

I wrote sample code just to test it https://play.golang.org/p/umTVUDNnLNh, its working 

and also in the above template deployment type is 
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
---
```
but we always deploy as apps/v1 https://github.com/rook/rook/blob/v1.2.3/cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml#L2


@stephan2012 can  you also compare the cephfs deployment template inside rook operator pod is matching https://github.com/rook/rook/blob/v1.2.3/cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml, in rook container, it will be at `cat /etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner-dep.yaml `

**Comment by travisn** [comment]
> @travisn do you have any idea why this is not getting hit https://github.com/rook/rook/blob/v1.2.3/pkg/operator/ceph/csi/spec.go#L229
> 
> I wrote sample code just to test it https://play.golang.org/p/umTVUDNnLNh, its working

Agreed, this code looks right as long as the v1.2 tag is being used for the attacher image

> and also in the above template deployment type is
> 
> ```yaml
> apiVersion: extensions/v1beta1
> kind: Deployment
> metadata:
> ---
> ```
> 
> but we always deploy as apps/v1 https://github.com/rook/rook/blob/v1.2.3/cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml#L2

That is certainly odd that the deployment type is `extensions/v1beta1`. Since the CSI driver has been deployed in Rook v1.0 it has always used `apps/v1`.

**Comment by stephan2012** [comment]
@travisn: I've upgraded to Rook v1.3.1 and CSI driver v2.0 and removed the manually added ConfigMap update permission. Looks good so far. Tomorrow, I will update two other clusters but don't expect to see this issue anymore.

**Comment by stephan2012** [comment]
Seems to be solved.
