### ISSUE TITLE
osd, mon and mds pods is not created when running cluster.yaml

### ISSUE THREAD

**Issue by Jimmol-Singh** [rook/rook#4837]
kernel: 4.7
Rook version: 1.2.3
Kuberentes version: 1.15.9

Hello, When I run kubectl apply -f cluster.yaml, I believe i should see the osd, mon and mds pods up and running but I dont. Instead. I see only the csi-cephfsplugin and csi-rbdplgin showing up. Any idea on what I might be doing wrong?

csi-cephfsplugin-provisioner-5849d8889f-w8xwn   0/4     Pending   0          19s
csi-rbdplugin-8tv9k                             0/3     Pending   0          19s
csi-rbdplugin-provisioner-78d84647f6-7qg5c      0/5     Pending   0          19s
rook-ceph-agent-5hdx8                           0/1     Pending   0          19s
rook-ceph-detect-version-c77lc                  0/1     Pending   0          24s

**Comment by nizamial09** [comment]
Follow this document.
https://rook.io/docs/rook/v1.1/ceph-quickstart.html

**Comment by galexrt** [comment]
@nizamial09 the link you posted points to Rook version 1.1 documentation.

@Jimmol-Singh Please use the latest release (1.2) documentation and `release-1.2` Git Branch for manifests, to install Rook Ceph https://rook.io/docs/rook/v1.2/ceph-quickstart.html

**Comment by nizamial09** [comment]
@galexrt Oh yeah. I bookmarked this thing long ago. Sorry for that. :)

**Comment by Jimmol-Singh** [comment]
Thanks for the response! 
I'm following the guide that is linked but unfornuately my operator pod keeps running into an error.

Name:           rook-ceph-operator-54588c89c8-bx46p
Namespace:      rook-ceph
Priority:       0
Node:           node-1/192.168.50.11
Start Time:     Fri, 28 Feb 2020 13:30:36 +0000
Labels:         app=rook-ceph-operator
                pod-template-hash=54588c89c8
Annotations:    cni.projectcalico.org/podIP: 192.168.84.131/32
Status:         Pending
IP:             192.168.84.131
Controlled By:  ReplicaSet/rook-ceph-operator-54588c89c8
Containers:
  rook-ceph-operator:
    Container ID:  
    Image:         rook/ceph:v1.2.4
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      ceph
      operator
    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Environment:
      ROOK_CURRENT_NAMESPACE_ONLY:               false
      ROOK_ALLOW_MULTIPLE_FILESYSTEMS:           false
      ROOK_LOG_LEVEL:                            INFO
      ROOK_CEPH_STATUS_CHECK_INTERVAL:           60s
      ROOK_MON_HEALTHCHECK_INTERVAL:             45s
      ROOK_MON_OUT_TIMEOUT:                      600s
      ROOK_DISCOVER_DEVICES_INTERVAL:            60m
      ROOK_HOSTPATH_REQUIRES_PRIVILEGED:         false
      ROOK_ENABLE_SELINUX_RELABELING:            true
      ROOK_ENABLE_FSGROUP:                       true
      ROOK_DISABLE_DEVICE_HOTPLUG:               false
      DISCOVER_DAEMON_UDEV_BLACKLIST:            (?i)dm-[0-9]+,(?i)rbd[0-9]+,(?i)nbd[0-9]+
      ROOK_ENABLE_FLEX_DRIVER:                   true
      ROOK_ENABLE_DISCOVERY_DAEMON:              true
      ROOK_CSI_ENABLE_CEPHFS:                    false
      ROOK_CSI_ENABLE_RBD:                       false
      ROOK_CSI_ENABLE_GRPC_METRICS:              true
      CSI_ENABLE_SNAPSHOTTER:                    true
      CSI_FORCE_CEPHFS_KERNEL_CLIENT:            true
      ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS:  5
      NODE_NAME:                                  (v1:spec.nodeName)
      POD_NAME:                                  rook-ceph-operator-54588c89c8-bx46p (v1:metadata.name)
      POD_NAMESPACE:                             rook-ceph (v1:metadata.namespace)
    Mounts:
      /etc/ceph from default-config-dir (rw)
      /var/lib/rook from rook-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-system-token-k4k7x (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  rook-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-config-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  rook-ceph-system-token-k4k7x:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-system-token-k4k7x
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  26s   default-scheduler  Successfully assigned rook-ceph/rook-ceph-operator-54588c89c8-bx46p to node-1
  Normal   Pulling    23s   kubelet, node-1    Pulling image "rook/ceph:v1.2.4"
  Warning  Failed     8s    kubelet, node-1    Failed to pull image "rook/ceph:v1.2.4": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     8s    kubelet, node-1    Error: ErrImagePull
  Normal   BackOff    8s    kubelet, node-1    Back-off pulling image "rook/ceph:v1.2.4"
  Warning  Failed     8s    kubelet, node-1    Error: ImagePullBackOff

any advice on how to fix this?
