### ISSUE TITLE
Revisist RBAC rules for ceph-csi

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#4841]
**Is this a bug report or feature request?**
* Bug Report

There are few RBAC which are not required are getting deployed when we use common.yaml, we need to remove the unwanted RBAC rules for cephcsi

**Deviation from expected behavior:**
There are more RBAC for cephcsi which are not required
**Expected behavior:**
only required RBAC should be granted for ceph-csi

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
Still need fix for this.

**Comment by Madhu-1** [comment]
Still I would like to see if we can reduce the rbac

**Comment by travisn** [comment]
@Madhu-1 Do you have an idea which RBAC is not needed, or it's just time to review thoroughly?

**Comment by Madhu-1** [comment]
i will take a look at it soon, Thanks for the reminder @travisn
