### ISSUE TITLE
Force balancer module enabling

### ISSUE THREAD

**Issue by leseb** [rook/rook#4842]
Reported by @paalkr 

I'm experimenting this feature in a test-cluster right now, and I'm not able to activate the balancer module due to some of my clients in kernel mode are reporting being jewel, due to the bug mentioned here. #4784 (comment)

I get this error in the logs
exec: Error EPERM: cannot set require_min_compat_client to luminous: 9 connected client(s) look like jewel (missing 0x800000000000000); add --yes-i-really-mean-it to do it anyway

So I used the toolbox to force setting the require_min_compat_client

ceph osd set-require-min-compat-client luminous --yes-i-really-mean-it
ceph osd dump|grep require_min_compat_client
require_min_compat_client luminous
But after restarting the operator I still get the same error, so I guess that enabling the balancer will try to execute the ceph osd set-require-min-compat-client luminous command, regardless of the current value. I think the operator should check for the current setting value before trying to apply ceph osd set-require-min-compat-client luminous, or allow to add the --yes-i-really-mean-it option through a setting in the cluster.yaml.

From https://github.com/rook/rook/pull/4784#issuecomment-583289674

**Comment by paalkr** [comment]
Thx. Looking forward to test this in the next release
