### ISSUE TITLE
rgw pod is restarting in rook ceph cluster

### ISSUE THREAD

**Issue by shikhar7** [rook/rook#4862]
I am having 3 rgw pod and it is restarting again and again and i am usinh rook 1.1.

Logs of rgw pod
debug 2020-02-13 07:17:22.284 7fae6be94700  0 ERROR: RESTFUL_IO(s)->complete_header() returned err=Bad file descriptor
--
  | debug 2020-02-13 07:17:22.284 7fae6be94700  0 iterate_obj() failed with -9
  | debug 2020-02-13 07:17:22.308 7fae82ec2700  1 ====== req done req=0x55d615d688e0 op status=-9 http_status=206 latency=15.3153s ======
  | debug 2020-02-13 07:17:22.427 7fae57e6c700  1 ====== req done req=0x55d619f4e8e0 op status=-9 http_status=206 latency=12.4313s ======
  | debug 2020-02-13 07:17:22.427 7faf037c3700  0 ERROR: RESTFUL_IO(s)->complete_header() returned err=Bad file descriptor
  | debug 2020-02-13 07:17:22.427 7faf037c3700  0 iterate_obj() failed with -9
  | debug 2020-02-13 07:17:22.537 7fae3de38700  1 ====== req done req=0x55d6196f48e0 op status=-9 http_status=206 latency=8.6792s ======
  | debug 2020-02-13 07:17:22.550 7fae6ce96700  1 ====== req done req=0x55d61b6b08e0 op status=-104 http_status=206 latency=14.4633s ======
  | debug 2020-02-13 07:17:23.126 7faeeef9a700  0 ERROR: RESTFUL_IO(s)->complete_header() returned err=Bad file descriptor
  | debug 2020-02-13 07:17:23.126 7faeeef9a700  0 iterate_obj() failed with -9
  | debug 2020-02-13 07:17:23.408 7fae2fe1c700  0 ERROR: RESTFUL_IO(s)->complete_header() returned err=Bad file descriptor
  | debug 2020-02-13 07:17:23.408 7fae2fe1c700  0 iterate_obj() failed with -9
  | debug 2020-02-13 07:17:23.581 7fae88ece700  0 ERROR: RESTFUL_IO(s)->complete_header() returned err=Bad file descriptor
  | debug 2020-02-13 07:17:23.581 7fae88ece700  0 iterate_obj() failed with -9
  | debug 2020-02-13 07:17:24.127 7fae996ef700  1 ====== req done req=0x55d614a088e0 op status=-9 http_status=206 latency=17.9354s ======
  | debug 2020-02-13 07:17:24.211 7fae1a5f1700  1 ====== req done req=0x55d61ef5a8e0 op status=-9 http_status=206 latency=8.08218s ======
  | debug 2020-02-13 07:17:24.263 7faf067c9700  0 ERROR: RESTFUL_IO(s)->complete_header() returned err=Bad file descriptor
  | debug 2020-02-13 07:17:24.263 7faf067c9700  0 iterate_obj() failed with -9
  | debug 2020-02-13 07:17:24.689 7faef2fa2700  0 ERROR: RESTFUL_IO(s)->complete_header() returned err=Bad file descriptor
  | debug 2020-02-13 07:17:24.689 7faef2fa2700  0 iterate_obj() failed with -9
  | debug 2020-02-13 07:17:24.801 7faf037c3700  1 ====== req done req=0x55d61425a8e0 op status=-9 http_status=206 latency=7.82218s ======
  | debug 2020-02-13 07:17:24.821 7faee6f8a700  0 ERROR: RESTFUL_IO(s)->complete_header() returned err=Bad file descriptor
  | debug 2020-02-13 07:17:24.821 7faee6f8a700  0 iterate_obj() failed with -9
  | debug 2020-02-13 07:17:24.940 7fae33e24700  1 ====== req done req=0x55d614b108e0 op status=-9 http_status=206 latency=9.65322s ======
  | debug 2020-02-13 07:17:25.057 7faf09fd0700  1 ====== req done req=0x55d6181ee8e0 op status=-9 http_status=206 latency=8.23919s ======
  | debug 2020-02-13 07:17:25.281 7fae6be94700  1 ====== req done req=0x55d61b6d88e0 op status=-9 http_status=206 latency=17.0334s ======
  | debug 2020-02-13 07:17:25.601 7faedf77b700  1 ====== req done req=0x55d6182b88e0 op status=-9 http_status=206 latency=7.61417s ======
  | debug 2020-02-13 07:17:25.908 7fae2fe1c700  1 ====== req done req=0x55d61ef288e0 op status=-9 http_status=200 latency=10.4632s ======
  | debug 2020-02-13 07:17:26.022 7faeeef9a700  1 ====== req done req=0x55d619ce88e0 op status=-9 http_status=206 latency=8.6682s ======
  | debug 2020-02-13 07:17:26.090 7faf067c9700  1 ====== req done req=0x55d619bba8e0 op status=-9 http_status=200 latency=9.24721s ======
  | debug 2020-02-13 07:17:26.229 7fae88ece700  1 ====== req done req=0x55d61593c8e0 op status=-9 http_status=206 latency=10.3512s ======
  | debug 2020-02-13 07:17:26.532 7faef2fa2700  1 ====== req done req=0x55d61433e8e0 op status=-9 http_status=206 latency=9.01021s ======
  | debug 2020-02-13 07:17:26.632 7faee6f8a700  1 ====== req done req=0x55d6182868e0 op status=-9 http_status=206 latency=8.9912s ======
  | debug 2020-02-13 07:17:26.762 7faf48426780  1 final shutdown

**Comment by leseb** [comment]
Please re-open the issue the bug template.

**Comment by sdgmf** [comment]
same problem

**Comment by subhamkrai** [comment]
@sdgmf please open a new issue with the template

**Comment by acejam** [comment]
@sdgmf @shikhar7 Did you ever figure this out?

**Comment by thenamehasbeentake** [comment]
![image](https://github.com/rook/rook/assets/36036872/0767e272-24f8-4fb3-b376-a26bd66afcdd)
Rgw progress was killed by livenessProbe and then `Bad file descriptor` logs Appeared.
