### ISSUE TITLE
Can I use rbd or cephfs outside the k8s cluster

### ISSUE THREAD

**Issue by zhifei92** [rook/rook#4870]
##### Are there any documents that can help me. Thanks

**Comment by zhifei92** [comment]
We are testing rook-ceph， wanted to use rook to deploy and manage the company's ceph cluster

**Comment by travisn** [comment]
@zhifei92 Take a look at the [External Cluster](https://rook.io/docs/rook/v1.2/ceph-cluster-crd.html#external-cluster) feature in Rook. For future questions like this, feel free to join the [Rook Slack](https://slack.rook.io/).

**Comment by zhifei92** [comment]
@travisn thank you, i got [External Cluster](https://rook.io/docs/rook/v1.2/ceph-cluster-crd.html#external-cluster). But I still have some questions, and it has been posted to slack
