### ISSUE TITLE
clock skew detected on mon.b, mon.c

### ISSUE THREAD

**Issue by kevinsingapore** [rook/rook#4875]
after initiating the rook-ceph service, the ceph-status health occurs the warning informatiion as below:
![image](https://user-images.githubusercontent.com/39163739/74600177-9e6f5880-50c8-11ea-8994-376661a9ff9f.png)
then how to solve? 
thank u!

**Comment by kevinsingapore** [comment]
i have solve the issue.
url->https://github.com/rook/rook/issues/2286#issuecomment-586712492

**Comment by leseb** [comment]
> i have solve the issue.
> url->[#2286 (comment)](https://github.com/rook/rook/issues/2286#issuecomment-586712492)

Closing then.

**Comment by kubecto** [comment]
This link cannot be opened：https://github.com/rook/rook/issues/4875#issuecomment-586899260

**Comment by kubecto** [comment]
Use the time synchronization server, which is configured on the k8s master node
` ` `
cat /etc/chrony.conf
server ntp.aliyun.com prefer iburst
server ntp.tencent.com iburst
server 10.102.28.80 iburst

driftfile /var/lib/chrony/drift
local stratum 8
manual
makestep 1.0 3
rtcsync
allow 0.0.0.0/0
logdir /var/log/chrony
` ` `
All node nodes are connected to master nodes
` ` `
cat /etc/chrony.conf
server 10.102.28.80 prefers iburst
server master iburst
driftfile /var/lib/chrony/drift
logdir /var/log/chrony
log measurements statistics tracking
makestep 1.0 3
rtcsync
logdir /var/log/chrony
` ` `
