### ISSUE TITLE
Supporting cluster provisioning in helm chart

### ISSUE THREAD

**Issue by woohhan** [rook/rook#4878]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
I've been actively using rook lately at my workplace. While enjoying working with rook, I was curious why helm chart is not provided for a cluster provisioning. So I implemented a simple helm chart for myself: [link](https://github.com/woohhan/rook-ceph-chart). I just notice that similar attempts have been made in #2109  and #1676. I'd like to advance the chart I created by taking note of #1676 and create a new pull request to start with adding fundamental cluster features.

Before that, I'd like to ask for a second opinion. There are some issues that I want to discuss as well.
- What features are definitely needed in values.yaml? I want to avoid helm chart gets too bigger.
- What version of helm chart should be used? I'm thinking of creating a new directory for the 3.0 version without modifying the existing helm chart.
- What would be the best way to manage CRD? Unfortunately, helm doesn't provide a feature to delete CRD/CR, so I use kubectl command through hyperkube container image (prometheus operator is using this way too: [link](https://github.com/helm/charts/blob/d58247103fafd5930792bb1fd3ac240547523200/stable/prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml#L33)) I don't like this approach, but I couldn't think of a better way to delete CRD/CR. Without this, rook-ceph namespace will be stopped at terminating status during helm uninstall, because cephclusters.ceph.rook.io won't be deleted. You could check my implementation from the following links.
  - https://github.com/woohhan/rook-ceph-chart/blob/master/templates/pre-delete.yaml
  - https://github.com/woohhan/rook-ceph-chart/blob/master/templates/post-delete.yaml
  - https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/

**What is use case behind this feature:**
Helm

**Environment**:
NONE

**Comment by travisn** [comment]
> * What features are definitely needed in values.yaml? I want to avoid helm chart gets too bigger.

Seems like the chart needs to expose all of the values in the CRs. Perhaps this is why the helm chart hasn't been created yet. By the time you expose all the options in the CRs, you end up with almost the same complexity as using the CRs directly.

And I still have a question for whether it makes sense to create a single helm chart for all of rook-ceph, or whether we should have helm charts for the operator and each CR. In [this comment](https://github.com/rook/rook/issues/2109#issuecomment-480085103) I thought having a single chart would be good. But would that make it too complex?  

> * What version of helm chart should be used? I'm thinking of creating a new directory for the 3.0 version without modifying the existing helm chart.

Is there not compatibility between helm 2 and 3? What happens if somebody installed a v2 chart? Can they use the v3 chart later?

> * What would be the best way to manage CRD? Unfortunately, helm doesn't provide a feature to delete CRD/CR, so I use kubectl command through hyperkube container image (prometheus operator is using this way too: [link](https://github.com/helm/charts/blob/d58247103fafd5930792bb1fd3ac240547523200/stable/prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml#L33)) I don't like this approach, but I couldn't think of a better way to delete CRD/CR. Without this, rook-ceph namespace will be stopped at terminating status during helm uninstall, because cephclusters.ceph.rook.io won't be deleted. You could check my implementation from the following links.
>   
>   * https://github.com/woohhan/rook-ceph-chart/blob/master/templates/pre-delete.yaml
>   * https://github.com/woohhan/rook-ceph-chart/blob/master/templates/post-delete.yaml
>   * https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/
> 

There has been a proposal that the CRDs shouldn't be included in the helm chart since they won't be managed by helm. Deleting them like this doesn't seem like a good thing in the general case. We have to be very careful about accidentally deleting resources.

**Comment by woohhan** [comment]
> And I still have a question for whether it makes sense to create a single helm chart for all of rook-ceph, or whether we should have helm charts for the operator and each CR. In [this comment](https://github.com/rook/rook/issues/2109#issuecomment-480085103) I thought having a single chart would be good. But would that make it too complex?

A single chart would be good for a simple project. however, I'd like to suggest two helm charts for managing CRD. one is rook-ceph-operator which includes CRD and operator(same with existing one) and another is rook-ceph-cluster for cluster.yaml and storageclass.yaml. If a user wants maximum freedom, just install rook-ceph-operator and manage cluster.yaml directly. But if the user wants to use it easily, the user can just install rook-ceph-cluster (which has dependencies on rook-ceph-operator). Please see this pull request: #4886  

> Is there not compatibility between helm 2 and 3? What happens if somebody installed a v2 chart? Can they use the v3 chart later?

In helm3 users can use helm2 chart however, the reverse is not. Since helm2 support is 9 months left, I'd like to migrate to helm3 first. There is a project for migrating helm2 to helm3, We can provide documentation for existing Helm2 users.

**Comment by galexrt** [comment]
Let's close this issue in favor of #2109 which has more people following it and I'm looking into right now :-)
