### ISSUE TITLE
Ceph Octopus and pool size 1

### ISSUE THREAD

**Issue by leseb** [rook/rook#4889]
Octopus is coming with this change https://github.com/ceph/ceph/pull/33281, which means that  CephBlockPool CRD with a size of 1 won't work without modification of the current code.

**Comment by travisn** [comment]
In Rook I'd vote to override this setting and allow setting the pool size to 1. We have warnings in the docs and example yamls that they shouldn't use pool size 1 in production, and the ceph health status would also show a warning. If we didn't override this restriction in rook, the only workaround would be to create a pool from the rook toolbox, which is not a reasonable ask.

**Comment by leseb** [comment]
Yes, we must ensure the desired state, no matter what I guess!

**Comment by travisn** [comment]
stalebot this is already closed, you can't close it again :)
