### ISSUE TITLE
Only one mon pod is created after running kubectl apply -f cluster.yaml

### ISSUE THREAD

**Issue by Jimmol-Singh** [rook/rook#4890]
Hello! 
As stated in the title, when I run the cluster.yaml file only one monitor pod is created and running. But, I'm supposed to have three  mon pod in total running along with  the osd pods, mds pods etc. From what I understand, the operator pod is having trouble communicating with the mon pod. How would I go about solving this issue?

Thanks!

**Comment by leseb** [comment]
Please re-open using the issue template for a bug report.
