### ISSUE TITLE
A simple question about the modification and writing of ceph's yaml file

### ISSUE THREAD

**Issue by huangweiboy2** [rook/rook#4892]
A simple question, I want to write and modify the yaml file. For example, I want to modify the cluster.yaml file in the ceph folder, but what I do n’t know is the meaning of some setting options in the file. I want to ask which URL I can find. Their explanation, because I didn't see it in the k8s API reference, maybe I ignored it, can you answer it? I am newbie

**Comment by leseb** [comment]
When you say "some setting options", which option is unclear?

**Comment by galexrt** [comment]
Have you checked the CRD documentations on the Rook homepage?
https://rook.io/docs/rook/v1.2/ceph-cluster-crd.html

**Comment by huangweiboy2** [comment]
@leseb @galexrt Thank you, I ignored it and didn't watch it
