### ISSUE TITLE
OSD pods isn't creating on Rke rancher

### ISSUE THREAD

**Issue by nzncngz** [rook/rook#4897]
**Is this a bug report or feature request?**
My K8s enviroment;
1 rke
3 masters
3 workers
1 NTP
RKE version(rke version v1.13.5)
I wanted rook-ceph on K8s rke.But OSD pool is not created.

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:
FAILED
(https://user-images.githubusercontent.com/22845579/74955697-19f93e80-5416-11ea-8c77-b3cdfadf752d.png)

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
osd prepare pods describe;
root@master1:~/rook/cluster/examples/kubernetes/ceph# kubectl describe pods rook-ceph-osd-prepare-worker2.5ghvl.local-d8fj7 -n rook-ceph
Name:               rook-ceph-osd-prepare-worker2.5ghvl.local-d8fj7
Namespace:          rook-ceph
Priority:           0
PriorityClassName:  <none>
Node:               worker2.5ghvl.local/10.154.2.175
Start Time:         Thu, 20 Feb 2020 18:51:40 +0300
Labels:             app=rook-ceph-osd-prepare
                    ceph.rook.io/pvc=
                    controller-uid=e22583db-53f8-11ea-aa59-566fe47a005f
                    job-name=rook-ceph-osd-prepare-worker2.5ghvl.local
                    rook_cluster=rook-ceph
Annotations:        cni.projectcalico.org/podIP: 10.52.5.68/32
Status:             Succeeded
IP:                 10.52.5.68
Controlled By:      Job/rook-ceph-osd-prepare-worker2.5ghvl.local
Init Containers:
  copy-bins:
    Container ID:  docker://c9ddca9fd0a15f93f57dd453509232719a43ea52fbe3404a74df222818f9aea1
    Image:         rook/ceph:v1.2.4
    Image ID:      docker-pullable://rook/ceph@sha256:abd9b6b6c356958eead449869f6a75f6e47e1d04d7bfc7bde69d87319e5fbf61
    Port:          <none>
    Host Port:     <none>
    Args:
      copy-binaries
      --copy-to-dir
      /rook
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 20 Feb 2020 18:51:41 +0300
      Finished:     Thu, 20 Feb 2020 18:51:41 +0300
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /rook from rook-binaries (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-osd-token-rqrhs (ro)
Containers:
  provision:
    Container ID:  docker://d921e8415be67e373c6d4e09676ec90d7c29981889b02dce8394e64bb6f7831f
    Image:         ceph/ceph:v14.2.6
    Image ID:      docker-pullable://ceph/ceph@sha256:82d0ea5dd95ccedb30e738ed4eac4b89cacc1f6b4b61e3bc45e4b6417f3b9430
    Port:          <none>
    Host Port:     <none>
    Command:
      /rook/tini
    Args:
      --
      /rook/rook
      ceph
      osd
      provision
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 20 Feb 2020 18:51:43 +0300
      Finished:     Thu, 20 Feb 2020 18:51:46 +0300
    Ready:          False
    Restart Count:  0
    Environment:
      ROOK_NODE_NAME:               worker2.5ghvl.local
      ROOK_CLUSTER_ID:              6f89711a-53f8-11ea-963b-566fe47a0061
      ROOK_PRIVATE_IP:               (v1:status.podIP)
      ROOK_PUBLIC_IP:                (v1:status.podIP)
      ROOK_CLUSTER_NAME:            rook-ceph
      ROOK_MON_ENDPOINTS:           <set to the key 'data' of config map 'rook-ceph-mon-endpoints'>  Optional: false
      ROOK_MON_SECRET:              <set to the key 'mon-secret' in secret 'rook-ceph-mon'>          Optional: false
      ROOK_ADMIN_SECRET:            <set to the key 'admin-secret' in secret 'rook-ceph-mon'>        Optional: false
      ROOK_CONFIG_DIR:              /var/lib/rook
      ROOK_CEPH_CONFIG_OVERRIDE:    /etc/rook/config/override.conf
      ROOK_FSID:                    <set to the key 'fsid' in secret 'rook-ceph-mon'>  Optional: false
      NODE_NAME:                     (v1:spec.nodeName)
      ROOK_CRUSHMAP_HOSTNAME:       worker2.5ghvl.local
      CEPH_VOLUME_DEBUG:            1
      CEPH_VOLUME_SKIP_RESTORECON:  1
      DM_DISABLE_UDEV:              1
      ROOK_DATA_DEVICE_FILTER:      all
      ROOK_CEPH_VERSION:            ceph version 14.2.6-0 nautilus
    Mounts:
      /dev from devices (rw)
      /etc/ceph from ceph-conf-emptydir (rw)
      /rook from rook-binaries (rw)
      /run/udev from udev (rw)
      /var/lib/ceph/crash from rook-ceph-crash (rw)
      /var/lib/rook from rook-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-osd-token-rqrhs (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  rook-data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook
    HostPathType:
  ceph-conf-emptydir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  rook-ceph-log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/log
    HostPathType:
  rook-ceph-crash:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/rook-ceph/crash
    HostPathType:
  rook-binaries:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  devices:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:
  udev:
    Type:          HostPath (bare host directory volume)
    Path:          /run/udev
    HostPathType:
  rook-ceph-osd-token-rqrhs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-osd-token-rqrhs
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/hostname=worker2.5ghvl.local
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                          Message
  ----    ------     ----  ----                          -------
  Normal  Scheduled  32m   default-scheduler             Successfully assigned rook-ceph/rook-ceph-osd-prepare-worker2.5ghvl.local-d8fj7 to worker2.5ghvl.local
  Normal  Pulled     32m   kubelet, worker2.5ghvl.local  Container image "rook/ceph:v1.2.4" already present on machine
  Normal  Created    32m   kubelet, worker2.5ghvl.local  Created container
  Normal  Started    32m   kubelet, worker2.5ghvl.local  Started container
  Normal  Pulled     32m   kubelet, worker2.5ghvl.local  Container image "ceph/ceph:v14.2.6" already present on machine
  Normal  Created    32m   kubelet, worker2.5ghvl.local  Created container
  Normal  Started    32m   kubelet, worker2.5ghvl.local  Started container

* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
root@master1:~/rook/cluster/examples/kubernetes/ceph# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):
root@master1:~/rook/cluster/examples/kubernetes/ceph# uname -a
Linux master1.5ghvl.local 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
Cluster has 8 vms.Vm is running on Ovirt.
* Rook version (use `rook version` inside of a Rook Pod):
root@master1:~/rook/cluster/examples/kubernetes/ceph# git branch -r
  origin/release-1.2

* Storage backend version (e.g. for ceph do `ceph -v`):
[root@rook-ceph-tools-f58c78956-d9ztn /]# ceph -v
ceph version 14.2.6 (f0aa067ac7a02ee46ea48aa26c6e298b5ea272e9) nautilus (stable)

* Kubernetes version (use `kubectl version`):
root@master1:~/rook/cluster/examples/kubernetes/ceph# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Rancher RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
(https://user-images.githubusercontent.com/22845579/74957117-24b4d300-5418-11ea-8af9-9503e789138c.png)

**Comment by BlaineEXE** [comment]
Please see related https://github.com/rook/rook/issues/3923

**Comment by nzncngz** [comment]
I tried but problem is countinue.

**Comment by nzncngz** [comment]
Hi again,
I am using on below cluster.yaml when ceph osd is running.
root@master1:~/rook/cluster/examples/kubernetes/ceph# cat cluster3.yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
    image: ceph/ceph:v14.2.7
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 3
    allowMultiplePerNode: false
  dashboard:
    enabled: true
    ssl: true
  network:
    hostNetwork: false
  storage:
    useAllNodes: true
    useAllDevices: true
    # Important: Directories should only be used in pre-production environments
    directories:
    - path: /var/lib/rook

Ceph status
(https://user-images.githubusercontent.com/22845579/75019663-5b373000-54a2-11ea-976e-946758e780cf.png)

I deployed mysql and wordpress app
Mysql and wordpress application source;

(https://github.com/rook/rook/files/4235190/wordpress.txt)
(https://github.com/rook/rook/files/4235193/mysql.txt)
(yaml is not supported issue platform)
root@master1:~/rook/cluster/examples/kubernetes# kubectl create ns wordpress
namespace/wordpress created
root@master1:~/rook/cluster/examples/kubernetes# kubectl create -f wordpress.yaml -n wordpress
service/wordpress created
persistentvolumeclaim/wp-pv-claim created
deployment.apps/wordpress created
root@master1:~/rook/cluster/examples/kubernetes# kubectl create -f mysql.yaml -n wordpress
service/wordpress-mysql created
persistentvolumeclaim/mysql-pv-claim created
deployment.apps/wordpress-mysql created
all resouce
(https://user-images.githubusercontent.com/22845579/75020211-532bc000-54a3-11ea-974c-31a12db8c2a1.png)

ERROR

 pod has unbound immediate PersistentVolumeClaims 
pod is runnning but;
root@master1:~/rook/cluster/examples/kubernetes# kubectl describe pods wordpress-7b6c4c79bb-7rkwg -n wordpress
Name:               wordpress-7b6c4c79bb-7rkwg
Namespace:          wordpress
Priority:           0
PriorityClassName:  <none>
Node:               worker2.5ghvl.local/10.154.2.175
Start Time:         Fri, 21 Feb 2020 12:12:40 +0300
Labels:             app=wordpress
                    pod-template-hash=7b6c4c79bb
                    tier=frontend
Annotations:        cni.projectcalico.org/podIP: 10.52.4.34/32
Status:             Running
IP:                 10.52.4.34
Controlled By:      ReplicaSet/wordpress-7b6c4c79bb
Containers:
  wordpress:
    Container ID:   docker://731db18f421f9b0da03a5aa1a55ac965e06a12c54f15740e806a96b287b4e944
    Image:          wordpress:4.6.1-apache
    Image ID:       docker-pullable://wordpress@sha256:44902067a29a0535bfcf97a7be489dba4d6bd5d74ccd4a86bfac9da4f3f1dc57
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 21 Feb 2020 12:13:23 +0300
    Ready:          True
    Restart Count:  0
    Environment:
      WORDPRESS_DB_HOST:      wordpress-mysql
      WORDPRESS_DB_PASSWORD:  changeme
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xtx82 (ro)
      /var/www/html from wordpress-persistent-storage (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  wordpress-persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  wp-pv-claim
    ReadOnly:   false
  default-token-xtx82:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xtx82
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                            From                          Message
  ----     ------                  ----                           ----                          -------
  Warning  FailedScheduling        <invalid> (x6 over <invalid>)  default-scheduler             pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled               <invalid>                      default-scheduler             Successfully assigned wordpress/wordpress-7b6c4c79bb-7rkwg to worker2.5ghvl.local
  Normal   SuccessfulAttachVolume  <invalid>                      attachdetach-controller       AttachVolume.Attach succeeded for volume "pvc-4c991a2a-548a-11ea-9ea7-566fe47a006a"
  Normal   Pulling                 <invalid>                      kubelet, worker2.5ghvl.local  pulling image "wordpress:4.6.1-apache"
  Normal   Pulled                  <invalid>                      kubelet, worker2.5ghvl.local  Successfully pulled image "wordpress:4.6.1-apache"
  Normal   Created                 <invalid>                      kubelet, worker2.5ghvl.local  Created container
  Normal   Started                 <invalid>                      kubelet, worker2.5ghvl.local  Started container

**Comment by BlaineEXE** [comment]
Do your worker nodes have disks attached to them that Rook can use?
