### ISSUE TITLE
Inconsistent owner references of resources created by the rook/ceph operator

### ISSUE THREAD

**Issue by TomHellier** [rook/rook#4905]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When I install the rook-ceph helm chart, which creates the rook-ceph operator, this operator creates a set of resources such as:
* discover
* agent
* CSIDrivers

The discover daemonset is created with the owner reference configured to [point to the operator](https://github.com/rook/rook/blob/3de5be0482a02e761ef91011e5024537f1807219/pkg/operator/discover/discover.go#L174-L180), but the agent and the csi daemonsets/statefulsets are not. 

This lack of ownership references may be intentional, if someone could advise whether this is intentional, else I could probably try to get the code into the operator to configure the ownership according to my needs.

I use [argocd](https://github.com/argoproj/argo-cd) as a tool to manage kubernetes clusters, and the way it visualises the applications it deploys depend on whether the manifests created by operators show correct ownership relationships. The cephcluster.ceph.rook.io CRD has the ownership references created correctly.

I had an issue today where 
1. The rook/ceph helm chart was installed
2. The rook/ceph helm installation was deleted, but it didn't remove the instances of the agent daemonset
3. The rook/ceph helm chart was installed again, the rook operator did not create new agents (as it saw that they already existed)
4. The agents did not allow the block storage created to be mounted by my application pods, with the error "Unauthorized", deleting the agents daemonset [as described in issue #2447](https://github.com/rook/rook/issues/2447), and then deleting the operator brought them all back up again successfully, and provisioned block storage could be mounted by my application pods

I suspect issues [4864 - Some resources are remain after `helm delete`](https://github.com/rook/rook/issues/4864), and [4824 - CSI driver no longer removed with uninstall](https://github.com/rook/rook/issues/4824) are somewhat related, although I believe my issue extends to all things created by the rook operator.

**Expected behavior:**
Ownership references exist for any resource created by rook operator on an install of the rook/ceph helm chart (without installing any cluster CRDs)

**How to reproduce it (minimal and precise):**
Helm install the stable rook/ceph helm chart, and see that not all resources created by the operator show ownership references to a resource created by the helm chart.

**File(s) to submit**:
n/a

**Environment**: (most are not applicable)
* Rook version (use `rook version` inside of a Rook Pod): 1.2
* Storage backend version (e.g. for ceph do `ceph -v`): nautilus
* Kubernetes version (use `kubectl version`): 1.16

**Comment by travisn** [comment]
- The CSI driver now properly has owner references since #4903 was just merged
- Agreed that owner references are needed for the discovery daemonset, similar to the CSI driver in #4903. 
- The agent is disabled by default now as it is preferred to use the CSI driver. We are not planning to fix issues around this driver unless absolutely necessary. That said, it should be trivial to add them at the same time as the discovery daemonset.
