### ISSUE TITLE
Document now to upgrade ceph from flex driver to CSI

### ISSUE THREAD

**Issue by abh** [rook/rook#4912]
We've upgraded from version 0.x (over time to v1.2.5. All our volumes were created by and are mounted by the flex volume driver.

What's the process for changing to using the CSI driver? Do we just edit or remove the storage class and update / create one with the CSI configuration?

**Comment by volvicoasis** [comment]
`#!/bin/bash
# author : JLE
# date : 02/04/20
#Debug
set -x

set -e
# Any subsequent(*) commands which fail will cause the shell script to exit immediately
# -e exits on error, -u errors on undefined variables, and -o (for option) pipefail exits on command pipe failures.
# disable this behavior with set +e

#Set rook
ROOK_SYSTEM_NAMESPACE="rook-ceph-system"
ROOK_NAMESPACE="rook-ceph"
TOOLS_POD=$(kubectl -n $ROOK_NAMESPACE get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}')

ENV=dev

if test -z "$1"
    then echo "pas de parametre" ; exit -42
    else echo "le paramètr deployement entré est \"${1}\" "  
fi
if test -z "$2"
    then echo "pas de parametre " ; exit -42
    else echo "le paramètr de claim name entré est \"2}\" "  
fi

if test -z "$3"
    then echo "pas de parametre" ; exit -42
    else echo "le paramètr de claim name entré est \"3}\" "
fi

set -u

STATEFULLNAME=$1
 
PVCNAME=$2

PVID=

STATEFULL=deploy

kubectl  -n ${ENV} get pvc

#TOREMOVE
#echo "#Create mysql exemple with flex"
#set +e
#kubectl  -n ${ENV} delete -f mysql.yaml
#set -e
#kubectl  -n ${ENV} create -f mysql.yaml
###DEMO

kubectl -n ${ENV} get pvc ${PVCNAME} -o jsonpath='{.spec.volumeName}'
kubectl -n ${ENV} get ${STATEFULL} ${STATEFULLNAME} -o jsonpath='{.spec.replicas}'

SCALENUM=$(kubectl -n ${ENV} get ${STATEFULL} ${STATEFULLNAME} -o jsonpath='{.spec.replicas}')

kubectl -n ${ENV} get ${STATEFULL} ${STATEFULLNAME}

kubectl -n ${ENV} describe ${STATEFULL} ${STATEFULLNAME}

echo "#scale down application pods which are using pvc"
kubectl -n ${ENV} scale ${STATEFULL} ${STATEFULLNAME} --replicas=0



echo "#Change reclaimpolicy of PVC to retain (as we dont want to delete PV and backend image)"
#TOTAL=$SCALENUM*30
#sleep ${TOTAL}

kubectl -n ${ENV} get ${STATEFULL} ${STATEFULLNAME}

read -p "Are you sure? " -n 1 -r

if [[ $REPLY =~ ^[Nn]$ ]]
then
    #Go away from that do dangerous stuff
    exit 42
fi


PVID=$(kubectl -n ${ENV} get pvc ${PVCNAME} -o jsonpath='{.spec.volumeName}')

kubectl patch pv ${PVID}  -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'

echo "#Save PVC to yaml"
kubectl -n ${ENV} get pvc ${PVCNAME} -o yaml --export | sed -e '/resourceVersion: "[0-9]\+"/d' -e '/uid: [a-z0-9-]\+/d' -e '/selfLink: [a-z0-9A-Z/]\+/d' -e '/status:/d' -e '/phase:/d' -e '/creationTimestamp:/d' -e '/last-applied-configuration:/d' -e '/finalizers/,/^ *[a-z0-9-]/d' -e '/annotations:/,/^ *[a-z0-9-]/d'  -e '/volume\.beta\.kubernetes\.io/d'  -e '/pv\.kubernetes.io/d' -e '/volumeMode/d' -e '/volumeName/d' > old-pvc-${ENV}-${PVCNAME}.yaml

echo "#Change SC before create it"
sed 's/storageClassName: rook-ceph-block\|storageClassName: xfs/storageClassName: rook-ceph-block-csi/g' old-pvc-${ENV}-${PVCNAME}.yaml > new-pvc-${ENV}-${PVCNAME}.yaml

echo "#Delete the PVC ( we still have PV and backend image)"
kubectl -n ${ENV} delete pvc ${PVCNAME}

set +e
echo "#Be sure is delete"
kubectl -n ${ENV} patch pvc ${PVCNAME} -p '{"metadata":{"finalizers": []}}' --type=merge
set -e

echo "#Create the new PVC with same name (let the CSI created pvc related metadata in rados omap and create new rbd image in backend)"
kubectl -n ${ENV} create -f new-pvc-${ENV}-${PVCNAME}.yaml
kubectl -n ${ENV} get pvc ${PVCNAME}
sleep 5
kubectl -n ${ENV} get pvc ${PVCNAME}
read -p "Wait 20 second more ? " -n 1 -r
if [[ $REPLY =~ ^[Nn]$ ]]
then
    #Go away from that do dangerous stuff
    exit 42
fi

kubectl -n ${ENV} get pvc ${PVCNAME}
read -p "Are you sure, to continue, still wait ? " -n 1 -r
if [[ $REPLY =~ ^[Nn]$ ]]
then
    #Go away from that do dangerous stuff
    exit 42
fi

sleep 10
kubectl -n ${ENV} get pvc ${PVCNAME}

read -p "Are you sure, to continue, check it again ? " -n 1 -r
if [[ $REPLY =~ ^[Nn]$ ]]
then
    #Go away from that do dangerous stuff
    exit 42
fi

NEWPV=$(kubectl -n dev get pvc ${PVCNAME} -o jsonpath='{.spec.volumeName}')
echo "New pv is :${NEWPV}"

#kubectl -n ${ROOK_NAMESPACE} exec -ti ${TOOLS_POD} rbd status replicapool/${PIVD}


read -p "Are you sure to remove imge on replicapool ? " -n 1 -r
if [[ $REPLY =~ ^[Nn]$ ]]
then
    #Go away from that do dangerous stuff
    exit 42
fi

echo ${NEWPV}
echo "# rename old volumes to csi-vol-UUID naming"
UUID=$(kubectl get pv ${NEWPV} -o jsonpath='{.spec.csi.volumeHandle}' | cut -d'-' -f6-)
echo "uuid is ${UUID}"

#kubectl -n ${ROOK_NAMESPACE} exec -ti ${TOOLS_POD} rbd rbd unmap -o force replicapool/${PIVD}



echo "deleting image on pool csi-vol-${UUID}"
kubectl -n ${ROOK_NAMESPACE} exec -ti ${TOOLS_POD} rbd rm replicapool/csi-vol-${UUID}
kubectl -n ${ROOK_NAMESPACE} exec -ti ${TOOLS_POD} rbd mv replicapool/${PVID} replicapool/csi-vol-${UUID}

#As the volume is renamed now delete the old PV
kubectl delete pv ${PVID}

#scale up application and see things are working fine
#kubectl -n dev scale deploy wordpress-mysql --replicas=1
echo "DONT FORGET TO ::: kubectl -n ${ENV} scale ${STATEFULL} ${STATEFULLNAME} --replicas=${SCALENUM}"
`

**Comment by volvicoasis** [comment]
We ve got another proc to repair/unamp/unwatch disk if needed

**Comment by Madhu-1** [comment]
dup of https://github.com/rook/rook/issues/4043
