### ISSUE TITLE
rook-ceph: Ceph External Cluster Multi-tenancy. Removing the need for using the Ceph external cluster admin key.

### ISSUE THREAD

**Issue by likid0** [rook/rook#4917]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Currently we need to configure the Ceph external Admin key in the Rook deployment to be able to connect to a external Ceph cluster.

If we wanted to run in a multi-tenant fashion were several K8s/Rook clusters wanted to connect to the same external ceph cluster, each K8s deployment would have the access to the External Ceph Admin key and could potentially access or delete the Data from pools that belong to other k8s/Rook Clusters.

For deployments were we’re not configuring RGW or MDS in rook, if we could remove the need to use the external ceph admin key, we could then configure a specific user for each k8s/rook deployment with a delimited set of caps that would only allow to access their data pools achieving data isolation per k8s/rook deployment

 
**What is use case behind this feature:**

Multi-Tenancy, Achieving Data Isolation For different tenants/k8s/rook deployments while sharing the same Ceph External Cluster.

**Environment**:

**Comment by mmgaggle** [comment]
I think even if you did need to configure RGW or MDS, you could use bootstrap keys instead of admin keys, right?

**Comment by leseb** [comment]
> I think even if you did need to configure RGW or MDS, you could use bootstrap keys instead of admin keys, right?

We fetch the bootstrap key with the admin one :-)

**Comment by mmgaggle** [comment]
What I'm saying is that you might want to only give the consuming cluster the bootstrap keys, in lieu of the admin key, least privilege principal.

**Comment by leseb** [comment]
> What I'm saying is that you might want to only give the consuming cluster the bootstrap keys, in lieu of the admin key, least privilege principal.

Ok but the current interface only accepts a single key.
