### ISSUE TITLE
Ability to create Cassandra table/keyspace via CRD

### ISSUE THREAD

**Issue by ar-mi6** [rook/rook#4929]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Provide  ability to create Cassandra table or keyspace via a `CassandraTable` or `CassandraKeyspace` CRD along with being able to use the command line utility against the cluster to create those resources.

**What is use case behind this feature:**
Setting up tables and keyspaces as a part of the same set of manifests to deploy the rook/cassandra operator.

**Comment by yanniszark** [comment]
Hi @manmeet326! Can you elaborate on why you need this feature instead of creating the keyspaces/tables through the Cassandra client?
