### ISSUE TITLE
Create credential ConfigMaps in all namespaces

### ISSUE THREAD

**Issue by luxas** [rook/rook#493]
I tested this even more and it worked fine on my kubeadm setup (guide incoming), but I had to fix one thing myself, namely that the ConfigMap that Rook somehow fetches credentials from is only available in the `default` namespace. When I tried to make a PV in the `kube-system` namespace (just an example), the kubelet started spawning errors that the ConfigMap isn't available.

It was an easy fix, just copy the ConfigMap from default to kube-system, but this is maybe something that should be exposed via the API (which namespaces to deploy credentials to)

Cheers!

**Comment by travisn** [comment]
Hi @luxas, great suggestion. Is this the same as creating the secrets in namespaces for #475?

**Comment by luxas** [comment]
Yes, indeed, didn't see that one.

Closing in favor of #475, thanks!
