### ISSUE TITLE
Use prometheus metrics/alerts to trigger scale up/down events on running cassandra cluster

### ISSUE THREAD

**Issue by vishwaskumar58** [rook/rook#4930]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
A prometheus alert (based on the cassandra cluster usage metrics in prometheus) should trigger either a scale up or scale down event on the running cassandra cluster via the operator.

**What is use case behind this feature:**
making cassandra auto-scalable without human intervention.

**Comment by karanmagdani1** [comment]
Would love this feature for Ceph clusters as well! 
Currently using setup similar to https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml

**Comment by travisn** [comment]
@karanmagdani1 I assume you're referring to adding more storage automatically if the storage is getting low? Would you mind opening a new issue to track this for the Ceph operator? thanks
