### ISSUE TITLE
Ceph CSI fails to start.

### ISSUE THREAD

**Issue by rohan47** [rook/rook#4934]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Ceph CSI is not deployed and the Ceph cluster doesn't come up.
As per the operator logs the following error is related to this issue
```
2020-03-02 10:40:40.681187 E | op-cluster: invalid csi version: failed to complete ceph CSI
version job: failed to run CmdReporter rook-ceph-csi-detect-version successfully. failed to run
job. jobs.batch "rook-ceph-csi-detect-version" is forbidden: cannot set blockOwnerDeletion if an
ownerReference refers to a resource you can't set finalizers on: , <nil>
```

**Expected behavior:**
Ceph CSI should be deployed and Ceph cluster should come up.

**How to reproduce it (minimal and precise):**

Follow the steps to deploy Rook with the current master.
`1. oc apply -f common.yaml`
`2. oc apply -f operator-openshift.yaml`
`3. oc apply -f cluster-on-pvc.yaml`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): Master
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.16
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
@shaas I think this is related to recent change, can You please take a look at it

**Comment by shaas** [comment]
This is related to my change. But it seems to be due to some special RBAC-handling of OpenShift.
Unfortunately, I have no access to a running OpenShift cluster.

**Comment by travisn** [comment]
@shaas When you assign the ownerReference, you'll just need to set BlockOwnerDeletion flag to false. When it is retrieved from the deployment/replicaset it would be true, but we need to change it to false.
