### ISSUE TITLE
Convert the NFS controller to the controller-runtime

### ISSUE THREAD

**Issue by travisn** [rook/rook#4950]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Convert the [NFS controller](https://github.com/rook/rook/blob/master/pkg/operator/nfs/controller.go) to be managed with the controller-runtime. 
Currently Rook only has a simple watch in an informer as seen [here](https://github.com/rook/rook/blob/master/pkg/operator/k8sutil/customresource.go#L54).

**What is use case behind this feature:**
The controller runtime will improve reliability of the operator in several areas:
- Events can be re-queued if failed or the operator is not able to complete the operation
- Exponential backoff is provided automatically for re-queued events
- Waiting for the next event does not need to block on the current event if it is taking a long time and the event can be re-queued.

Several controllers in Rook are using the controller runtime. For examples, see the [pool controller](https://github.com/rook/rook/blob/master/pkg/operator/ceph/pool/controller.go) or [disruption budget](https://github.com/rook/rook/blob/master/pkg/operator/ceph/disruption/clusterdisruption/reconcile.go) controller.

**Comment by moricho** [comment]
Hi @ashishranjan738 @jbw976 @rohan47  - I’d like to participate in GSoC 2020 at CNCF, especially “Rewrite NFS Operator to use controller runtime and fix other open issues along with it”.
I have some knowledge and experience with k8s CustomController. And also I'm now working on the following PR to understand the overall picture of Rook.
- https://github.com/rook/rook/pull/4984
Can you please tell me how to get started with this? Thanks.

**Comment by prksu** [comment]
Hi @travisn, I found this issue in GSoC 2020 project ideas.
I'm interested in working on this issue for GSoC and I've some experience with controller-runtime both using kubebuilder and operator-sdk.

**Comment by jbw976** [comment]
That's great @prksu, thank you for your interest in this issue! To give everyone a fair chance of working on this issue for the GSoC 2020 program, we would love if you could go through the official application process at https://summerofcode.withgoogle.com/get-started/.  Of course, you can contact us on the [Rook Slack](https://slack.rook.io/) to get feedback on your proposal before submitting.  Thanks for your interest!! 🚀

**Comment by prksu** [comment]
Hi @jbw976 thanks, yes i'll do.
i still deeping rook code base and will reach out to rook slack with my proposal draft for some feedback.
