### ISSUE TITLE
Make s3 client available in Rook Ceph Toolbox

### ISSUE THREAD

**Issue by ron1** [rook/rook#4968]
**Feature Request**
Make s3 client available in Rook Ceph Toolbox

**What should the feature do:**
Make an s3 client available in the Rook Ceph toolbox pod to support bucket creation and other s3-related troubleshooting tasks that are not supported by the radosgw-admin command. CephObjectStore doc https://github.com/rook/rook/blob/master/Documentation/ceph-object.md#install-s3cmd instructs to yum install s3cmd in the toolbox pod to accomplish this. However, it does not make sense to run the toolbox pod privileged just to yum install the s3cmd package. Furthermore, it is fragile for the toolbox pod to have a dependency upon an external yum repository in order to support critical troubleshooting activities.

The Rook Ceph Object Bucket Provisioner may report the error below during operation. In order to troubleshoot and resolve the issue, an s3 client was needed to manually create the bucket after which the s3 client or the radosgw-admin client was used to grant the appropriate accesses. Consider either adding the s3cmd python module to the rook/ceph image itself or adding the module to a new rook/ceph-toolbox image.
```
...
op-bucket-prov: initializing and setting CreateOrGrant services
op-bucket-prov: getting storage class "test1-bucket"
op-bucket-prov: Grant: allowing access to bucket "test1" for OBC "test1-lib-bucket-provisioner-obc"
op-bucket-prov: Checking for existing bucket "test1"
exec: Running comand: radosgw-admin bucket stats --bucket test1 --rgw-realm=object-store --rgw-zonegroup=object-store --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keying=/var/lib/rook/rook-ceph/client.admin.keyring
controller.go:243] "msg"="cleaning up reconcile artifacts" "error"="error granting access to bucket: bucket test1 does not exist: error getting ceph bucket \"test\": Bucket not found" "key"="test1/test1-lib-bucket-provisioner-obc"
controller.go:163] error syncing 'test1/test1-lib-bucket-provisioner-obc': error granting access to bucket: bucket test1 does not exist: error getting ceph bucket "test1": Bucket not found, requeuing
```

**Environment**:

OCP 3.11

**Comment by travisn** [comment]
In #2166 we made the change to base the toolbox only on the Ceph tools and use the same image for the toolbox as the operator. The workaround is to install s3cmd in the toolbox when needed, but it is inconvenient for several reasons as mentioned above.

If there is a common need for more troubleshooting tools for which a separate toolbox image is still necessary, we could bring back the rook/ceph-toolbox image. To start with it could just be the `rook/ceph` image plus `s3cmd`. But I'd still like to have the default toolbox.yaml example point to the rook/ceph image instead of the new toolbox image so it is faster to troubleshoot with the image that has already been pulled to the cluster. Before we create this image I'd like to confirm how much demand there would be for it and perhaps there are other tools to add at the same time.

Adding `s3cmd` to the existing `rook/ceph` is an alternative, but in a prototype it increased the uncompressed image size by about 100MB, which is too much impact IMO for a tool that will not be used in the common scenarios.

**Comment by kfox1111** [comment]
Another option is to use mc: https://docs.min.io/docs/minio-client-complete-guide.html
The images there are tiny. ~8.82mb.

**Comment by ron1** [comment]
@travisn As @kfox1111 mentioned, the golang-based Minio S3 client is small, functional, and reasonably easy to configure. After confirmation that all `mc` s3 operations work as expected against an `RGW` backend, would you consider adding it to the `rook/ceph` image?

**Comment by travisn** [comment]
@kfox1111 @ron1 Yes that's an interesting question about `mc`. If that image is readily available, is it an option for you to just pull that image? It doesn't seem like it would have much advantage of being included in the rook image if it's already available as its own image.

**Comment by kfox1111** [comment]
Another possibility is to include it as a second container in the reference ceph-toolbox deployment yaml. Then its easier for users to find?

**Comment by travisn** [comment]
What about a separate example? toolbox.yaml would be for running Ceph commands and a new s3-client.yaml would launch the `mc` image.

**Comment by ron1** [comment]
It would also be nice to pre-configure the MC client with the rgw admin user, the correct rgw endpoint, etc.

**Comment by travisn** [comment]
> It would also be nice to pre-configure the MC client with the rgw admin user, the correct rgw endpoint, etc.

We could load some of the connection info as env vars when we define s3-client.yaml. For example, the user creds in [this example](https://rook.io/docs/rook/v1.2/ceph-object.html#client-connections) could be retrieved from a secret into an [env var](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables). 

Other info such as the s3 endpoint needs to be retrieved from kubectl so I'm not seeing how we could pre-populate that.

**Comment by kfox1111** [comment]
Would the endpoint not be available through service discovery?

**Comment by travisn** [comment]
True, we would have the endpoint already as an env var for the service. The pod spec should have everything it needs.

Any chance you have an example of a pod spec for starting mc to help jump start this change?

**Comment by kfox1111** [comment]
I don't. Sorry.

**Comment by mmgaggle** [comment]
I have to say that it would be kinda nice to have it in the toolbox pod vs being a distinct pod, unless of course the new distinct pod also has radosgw-admin capabilities.

**Comment by ron1** [comment]
How about using the fast, fully-functional peakcom/s5cmd:v1.4.0 image whose s5cmd golang binary now has the required bucket management capabilities?
