### ISSUE TITLE
Operator is waiting on orchestration status for nodes indefinitely

### ISSUE THREAD

**Issue by rajatsingh25aug** [rook/rook#4975]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behaviour:**
The operator logs are filled with this logging message 
`2020-03-05 13:19:57.775652 I | op-osd: waiting on orchestration status update from 3 remaining nodes`. 
Also, my `cephcluster` is stuck in `pending` state.
**Expected behaviour:**
The orchestration should be completed and the ceph cluster should move to `created` state.
**How to reproduce it (minimal and precise):**

- oc create -f `commom.yaml`

- oc create -f `operator-openshift.yaml`

- oc create -f `cluster.yaml`

Check the logs of the `rook-ceph-operator`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): macOs Catlina
* Kernel (e.g. `uname -a`): Darwin Kernel Version 19.3.0
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):  rook: v1.1.0-beta.0.998.gb179cce
* Storage backend version (e.g. for ceph do `ceph -v`):  No output
* Kubernetes version (use `kubectl version`):v1.16.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): There was no output for `ceph health`, its just stucks after typing the command

**Comment by leseb** [comment]
Fill-up the template!

**Comment by rajatsingh25aug** [comment]
> Fill-up the template!

My bad that I missed it, updated it!.

**Comment by leseb** [comment]
Closed by https://github.com/rook/rook/pull/4972? @travisn?

**Comment by travisn** [comment]
Yes, this was fixed by #4972 after our discussion in slack yesterday, thanks!
