### ISSUE TITLE
Ceph OSD topology does not support GA topology.kubernetes.io keys

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#4980]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Ceph topology setting does not use the GA `"topology.kubernetes.io"` key in addition to the beta key `""failure-domain.beta.kubernetes.io"` which is deprecated in k8s 1.17.

**Expected behavior:**
Code in `pkg/operator/ceph/cluster/osd/topology.go` should support `"topology.kubernetes.io"` keys in addition to `"failure-domain.beta.kubernetes.io"` keys.

**Comment by travisn** [comment]
This had been implemented, but looks like a regression. The [nodeTopologyLocation()](https://github.com/rook/rook/blob/6f3db3df71b87de4f3950d2eda8a86aae720c8fe/pkg/operator/k8sutil/node.go#L281) method implements the new `topology.kubernetes.io` label, but nothing is calling that helper anymore.
