### ISSUE TITLE
rook-ceph.rbd.csi.ceph.com/csi.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by zhuaizhuaixi** [rook/rook#4985]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Fail to start up pod due to mounting volume failed.

**Expected behavior:**

Pod start up success and volume mount success.

**How to reproduce it (minimal and precise):**

    git clone --single-branch --branch release-1.2 https://github.com/rook/rook.git
    cd cluster/examples/kubernetes/ceph
    kubectl create -f common.yaml
    kubectl create -f operator.yaml
    kubectl create -f cluster-test.yaml
    kubectl create -f csi/rbd/storageclass.yaml
    kubectl create -f csi/rbd/pvc.yaml
    kubectl create -f csi/rbd/pod.yaml

I can see rbd-pvc is Bound, but pod start up failed.

**error description**

kubectl describe pod csirbd-demo-pod

    Name:         csirbd-demo-pod
    Namespace:    default
    Priority:     0
    Node:         worker2/10.172.0.67
    Start Time:   Mon, 09 Mar 2020 15:53:32 +0800
    Labels:       <none>
    Annotations:  <none>
    Status:       Pending
    IP:           
    IPs:          <none>
    Containers:
      web-server:
        Container ID:   
        Image:          nginx
        Image ID:       
        Port:           <none>
        Host Port:      <none>
        State:          Waiting
          Reason:       ContainerCreating
        Ready:          False
        Restart Count:  0
        Environment:    <none>
        Mounts:
          /var/lib/www/html from mypvc (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from default-token-6jtq8 (ro)
    Conditions:
      Type              Status
      Initialized       True 
      Ready             False 
      ContainersReady   False 
      PodScheduled      True 
    Volumes:
      mypvc:
        Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
        ClaimName:  rbd-pvc
        ReadOnly:   false
      default-token-6jtq8:
        Type:        Secret (a volume populated by a Secret)
        SecretName:  default-token-6jtq8
        Optional:    false
    QoS Class:       BestEffort
    Node-Selectors:  <none>
    Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                     node.kubernetes.io/unreachable:NoExecute for 300s
    Events:
      Type     Reason                  Age                 From                     Message
      ----     ------                  ----                ----                     -------
      Normal   Scheduled               15m                 default-scheduler        Successfully assigned default/csirbd-demo-pod to worker2
      Normal   SuccessfulAttachVolume  15m                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-f7d7743c-1ccc-4f5e-afc8-05af9aaa3c87"
      Warning  FailedMount             119s (x6 over 13m)  kubelet, worker2         Unable to attach or mount volumes: unmounted volumes=[mypvc], unattached volumes=[mypvc default-token-6jtq8]: timed out waiting for the condition
      Warning  FailedMount             59s (x15 over 15m)  kubelet, worker2         MountVolume.MountDevice failed for volume "pvc-f7d7743c-1ccc-4f5e-afc8-05af9aaa3c87" : rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock: connect: no such file or directory"

I see the main error is : rook-ceph.rbd.csi.ceph.com/csi.sock: connect: no such file or directory

Why this plugin missing and how can I get this plugin? 

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7
* Kernel (e.g. `uname -a`): Linux master 3.10.0-957.el7.x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):  v1.2.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph v14.2.7
* Kubernetes version (use `kubectl version`): v1.17.3

**Comment by Madhu-1** [comment]
can you please check csi-rbdplugin pod running on the worker2 node. if its running check all containers are running on daemonset pod

**Comment by zhuaizhuaixi** [comment]
@Madhu-1 
csi-rbdplugin pod is running normally:

    NAME                                                READY   STATUS      RESTARTS   AGE    IP             NODE      NOMINATED NODE   READINESS GATES
    csi-rbdplugin-tgjzg                                 3/3     Running     0          158m   10.172.0.67    worker2   <none>           <none>

and daemonset pods are running normally:

    NAME               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
    csi-cephfsplugin   5         5         5       5            5           <none>          160m
    csi-rbdplugin      5         5         5       5            5           <none>          160m
    rook-discover      5         5         5       5            5           <none>          160m

**Comment by Madhu-1** [comment]
can you restart the csi-rbdplugin pod on the node and see that fixes the issue

**Comment by zhuaizhuaixi** [comment]
@Madhu-1 
It does work, After I restart csi-rbdplugin on worker2, the pod begins to pull image.
Thank you very much!
And should I restart all csi-rbdplugin on each node?

**Comment by Madhu-1** [comment]
first of all, am not sure how you ended up in this situation. if you face the same issue on other nodes than restart it

**Comment by taupiknr26** [comment]
> @Madhu-1
> It does work, After I restart csi-rbdplugin on worker2, the pod begins to pull image.
> Thank you very much!
> And should I restart all csi-rbdplugin on each node?

hello can you please tell me how you restart the pods, on my cluster just pod and daemonset, there is no deployment for rollout. Thanks for your help
