### ISSUE TITLE
pvc pending despite of following official examples.

### ISSUE THREAD

**Issue by paulmorai4** [rook/rook#4987]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Following the official docs  to perform  'Ceph Storage' --> 'Block Storage'  setting, and ends with pvc in pending status:

` waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
Mounted By:  wordpress-mysql-6bb7b7f95d-fc2c6`

**Expected behavior:**
Running mysql and wordpress 

**How to reproduce it (minimal and precise):**

1.  in a brand new k8s cluster v1.12.10+1.0.10.el7
2. install rook-ceph
git clone --single-branch --branch release-1.2 https://github.com/rook/rook.git
cd cluster/examples/kubernetes/ceph
kubectl create -f common.yaml
kubectl create -f operator.yaml
kubectl create -f cluster-test.yaml

3. create toolbox and storageclass 

Change csi.storage.k8s.io/fstype in  storageclass-test.yaml  from ext4 to xfs, because lsblk -f command shows xfs.

kubectl create -f toolbox.yaml
kubectl create -f cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml

4. create mysql pod
kubectl create -f mysql.yaml

5.kubectl get pvc

NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE
mysql-pv-claim   Pending                                      rook-ceph-block   17m

6. also I noticed none csi nor provision pods are running.

> [root@k8s-master rbd]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                                     READY   STATUS      RESTARTS   AGE
default       wordpress-mysql-6bb7b7f95d-fc2c6                         0/1     Pending     0          20m
kube-system   coredns-6d5cc884f4-czj8x                                 1/1     Running     2          20d
kube-system   coredns-6d5cc884f4-s8mvz                                 1/1     Running     2          20d
kube-system   etcd-k8s-master                                          1/1     Running     4          20d
kube-system   kube-apiserver-k8s-master                                1/1     Running     2          20d
kube-system   kube-controller-manager-k8s-master                       1/1     Running     9          20d
kube-system   kube-flannel-ds-524zr                                    1/1     Running     0          19d
kube-system   kube-flannel-ds-pqmt7                                    1/1     Running     2          20d
kube-system   kube-proxy-659xz                                         1/1     Running     0          19d
kube-system   kube-proxy-zh899                                         1/1     Running     2          20d
kube-system   kube-scheduler-k8s-master                                1/1     Running     8          20d
kube-system   kubernetes-dashboard-f6b58ff9c-7v5jf                     1/1     Running     1          20d
rook-ceph     rook-ceph-crashcollector-k8s-master-7b6cd7f988-zn99m     1/1     Running     0          63m
rook-ceph     rook-ceph-crashcollector-worker-node1-64547b46d7-pkb8x   1/1     Running     0          63m
rook-ceph     rook-ceph-mgr-a-5cbbd84767-p6bqg                         1/1     Running     0          64m
rook-ceph     rook-ceph-mon-a-66f495cc79-dtlzr                         1/1     Running     0          64m
rook-ceph     rook-ceph-operator-ff977bff-frpwc                        1/1     Running     2          92m
rook-ceph     rook-ceph-osd-0-7f69f84b48-8dqw5                         1/1     Running     0          63m
rook-ceph     rook-ceph-osd-1-5d6497654f-2hh96                         1/1     Running     0          63m
rook-ceph     rook-ceph-osd-prepare-k8s-master-8x4p5                   0/1     Completed   0          63m
rook-ceph     rook-ceph-osd-prepare-worker-node1-gjdqp                 0/1     Completed   0          63m
rook-ceph     rook-ceph-tools-bf94c9dd8-tnv4g                          1/1     Running     0          59m
rook-ceph     rook-discover-2zjb7                                      1/1     Running     0          80m
rook-ceph     rook-discover-4d6zp                                      1/1     Running     0          80m

**File(s) to submit**:
None 

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Oracle Linux 7.7
* Kernel (e.g. `uname -a`): 4.14.35-1902.3.2.el7uek.x86_64
* Cloud provider or hardware configuration:  
* Rook version (use `rook version` inside of a Rook Pod):  rook 1.2
* Storage backend version (e.g. for ceph do `ceph -v`): 
* Kubernetes version (use `kubectl version`): v1.12.10+1.0.10.el7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
CSI pods will not be started if kubernetes version is less than `1.13.0` please enable flex driver during operator deployment https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L203-L204

and also use  flex driver examples not CSI

**Comment by paulmorai4** [comment]
After enable flex driver in operator.yaml and recreate storageclass with flex driver, problem solved.
Thanks for your quick reply!
