### ISSUE TITLE
Rook 1.12 install fail on GCP ( port overlap )

### ISSUE THREAD

**Issue by krokk** [rook/rook#4991]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
csi-cephfsplugin pod 2/3 CrashLoopBackOff.

**Expected behavior:**
csi-cephfsplugin running smoothly

**How to reproduce it (minimal and precise):**

install with Helm: Rook version 1.12. 
deploy CephCluster on pvc ( problem start from here )
deploy Ceph Filesystem

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

![image](https://user-images.githubusercontent.com/20528599/76262270-2aa21500-625c-11ea-8431-f99bb64e9c78.png)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: GCP
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.2.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.7 
* Kubernetes version (use `kubectl version`):  1.15.9-gke.12 
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
![image](https://user-images.githubusercontent.com/20528599/76262492-c6338580-625c-11ea-8d4a-d2dcc68d1986.png)

Rook still manage to create volume in the filesystem 
![image](https://user-images.githubusercontent.com/20528599/76262585-08f55d80-625d-11ea-8910-e8ff6ede6a7a.png)

but they can't be attached to pod 
![image](https://user-images.githubusercontent.com/20528599/76262665-478b1800-625d-11ea-8647-6b10b110805b.png)

i coudln't identify which pod is currently using the 9091.

Thanks for your help

**Comment by Madhu-1** [comment]
during operator deployment please make use of https://github.com/rook/rook/blob/b626de17586db02f99f51fb6f59dbe22a5dae512/cluster/examples/kubernetes/ceph/operator.yaml#L288-L296 to specify different port numbers

use netstat or other tools check which process is using the port on nodes

**Comment by krokk** [comment]
Thanks for your help
