### ISSUE TITLE
Make Rook APIs to be consistent and more restful

### ISSUE THREAD

**Issue by kokhang** [rook/rook#500]
Currently, the rook APIs doesnt seem to be consistent with their nouns and verbs. Also they are not using the correct verbs for managing the resources.

For example, name of resources should all be plural. Currently, there is /pool, /image, /node and /mon are all singular. 

We are also no using the `DELETE` verb for removing resources. Instead we have action verb that handles delete. For example `POST /objectstore/remove` and `POST /filesystem/remove`.

For reference, we can follow the Kubernetes rest API: https://kubernetes.io/docs/api-reference/v1.5/

**Comment by kokhang** [comment]
I am currently working on adding a Rook volume plugin to Kubernetes. This plugin will reside in Kubernetes and delegate requests to the rook-api. See https://github.com/rook/rook/issues/432.

Since Kubernetes will use the Rook-api, i would like to spend time and improve the consistency of our API. I want to focus on our Block API for now since this is what Kubernetes will be using first. Im proposing a major revamp our our block API. I will just focus more on the signature and query, rather than the body. This is what I proposing.

# Pools
## Create pool
### Post /v1/pools
Body should contains data about creating the pool, like the name, , type, replicationconfig, erasurecode etc. The return message should be a HTTP return code and if accepted, it should return the name or we can generate a unique ID for the pool.

## Get pool
### Get /v1/pools/{name or ID}
Returns a json with all the details about the pool

## Get all pools
### Get /v1/pools
Return a list of pools with either some data of the pools (name, id and  type) or all the data (name, id, type, replication config, erasure coding)

## Delete pool
### Delete /v1/pools/{name or ID}
Return HTTP code.

# Blocks
## Create block
### Post /v1/pools/{name or ID}/blocks
Body should contains data about creating the block, like the name, and size. For storage clients that dont have the concept of pools, we can assigned a default pool. But i think most storage solutions will have something equivalent to pools or groups.

## Get block
### Get /v1/pools/{name or ID}/blocks/{name or ID}
Returns a json with all the details about the block

## Get all blocks
### Get /v1/pools{name or ID}/blocks
Return a list of blocks.

## Delete block
### Delete /v1/pools/{name or ID}/blocks/{name or ID}
Return HTTP code.

# Block attachments.
The kubernetes plugin for Rook will call the Rook-api to attach a block to a node. Since Rook can support READ-WRITE-MANY attachment, i propose to have `attachment` as a REST resource in block.

## Attach block
### Post /v1/pools/{name or ID}/blocks/{name or ID}/attachments
Body should contains data about attaching the block, like the node name, mount options, read/write mode etc. This should return an ID that references this attachment or a name. Also returns the device path if available.

## Detach block
### Delete /v1/pools/{name or ID}/blocks/{name or ID}/attachments/{name of ID}
Detach the block from the node. 

## Get all node attachments to this block
### Get /v1/pools{name or ID}/blocks/{name or ID}/attachments
Return a list of attachments with information of which nodes they are attached to.

**Comment by travisn** [comment]
since the CRDs are the core api for rook, no need to make this change
