### ISSUE TITLE
Allow data stored in dataDirHostPath to be stored on a PV

### ISSUE THREAD

**Issue by garvincasimir** [rook/rook#5006]
* Feature Request
Allow data stored in dataDirHostPath to be stored on a PV

**What should the feature do:**
When you create a CephCluster you will have the option to specify a storage class that supports ReadWriteMany volumes. A shared pv will be created and mounted to all pods that use that path. 

Example storage plugins: 
* External CephFS
* Azure Files
* Aws S3

**What is use case behind this feature:**

For PV based clusters all data is stored on PVs except for crash dumps. However, the dataDirHostPath config is still required. This change will allow the cluster to be fully pv based. The added bonus for the security conscious folks is not requiring privileged access to host paths.

**Comment by leseb** [comment]
@anubhav-here will look into this.

**Comment by FruityWelsh** [comment]
Still tracking this issue as unresolved, but would help me to avoid having to grant a security exception for rook in my cluster.

**Comment by rgherta** [comment]
Mounting hostpath is a security nightmare and this is happening also for cluster on pvc... The storage type used for ceph must remain a choice of the cluster administrator. If you want to persist data across restarts, this is why we have PersistentVolume Reclaim Policies. Eitherway there are more secure options than hostpath.

**Comment by subhamkrai** [comment]
Based on an offline discussion with Santosh, assigning it to me.

**Comment by travisn** [comment]
While the security preference is clear not to use the host path, the reality is that at best this will be difficult to change. The host paths have been used in a number of places to shared data between ceph daemons, and also for OSDs to work with devices under /dev. While after much effort it may be possible to redesign them to run without the privilege to use the host path, it will come with risk of regression and may hit roadblocks in assumptions from Ceph that don't map to the PVC approach. 

Where the daemons share data, perhaps a RWX PVC could be created that could be shared by all Ceph daemon pods running on a given node. Let's take two examples and consider how they would be redesigned:
1. The crash collector daemon watches for any crash on the node and reports it to the Ceph mgr. If we had a single RWX PVC shared with all Ceph daemons, we would only need a single crash collector pod to collect them. This seems simple enough.
2. The ceph exporter daemon watches for metrics from daemons on the node and reports them. The whole point of this daemon is that it is per-node and would have the efficiency of a local disk, therefore we would not be able to consolidate to a single exporter daemon. If we then created a PVC per node, this means all Ceph daemons would need to have affinity to a specific node for that volume. This node affinity would really restrict the flexibility that the pods currently having, especially in cloud environments. But perhaps there may be another design where a PVC could be shared in some other way that keeps it simple and doesn't come with the node affinity restriction.

In both of those cases, the host path approach keeps the daemons quite simple. The data store on the host by these daemons is not critical if it is lost, so there is no benefit to improve the reliability of the cluster if it were moved to a PV.  

Here are some notes for where the host paths are used in various components:
- OSDs have various complexities and assumptions about using /dev. OSDs design is the most complex area of Rook and it comes with a great risk of regression if something this fundamental is changed.
    - Key rotation job: /dev, /run/udev, and a bridge
    - Provisioning: /dev, /run/udev, and “rootfs” for detecting the presence of LVM
    - Daemon
        - /dev, /run/udev
        - Activate OSD container
        - Device mapper volume (encrypted OSDs)
        - Data bridge: Allows OSD locking of the device to prevent multiple instances of an OSD pod from starting
- All Ceph Daemons
    - Path shared with the ceph exporter
    - Logging to host in case pod logs are lost
    - Crash directory, shared with crash collector
- Crash collector
    - Shares host path with the ceph daemons
- Exporter
    - Collects metrics from other daemons
