### ISSUE TITLE
Resource settings

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#5015]
We need to set resource requests/limits on all of the things we put in or production cluster to ensure reliability. Some things do not seem to be configurable such as the csi driver's resources. We need a wayto ensure all objects rook creates have the option to set the resource requests/limits.

**Comment by kfox1111** [comment]
This is still a big problem. In particular, the resource requirements for the node rbd driver is much different then the provisioner's resource requirements.

**Comment by kfox1111** [comment]
can rooks management of the driver be disabled and the external helm chart be used in its place without destroying volumes? That may be a way around it.

**Comment by Madhu-1** [comment]
@kfox1111 can you please provide me the list of resources you want to set(example). I will fix this

**Comment by kfox1111** [comment]
Looks like:

csi-cephfsplugin:
- driver-registrar
- csi-cephfsplugin
- liveness-prometheus

csi-cephfsplugin-provisioner
- csi-attacher
- csi-provisioner
- csi-cephfsplugin
- liveness-prometheus

csi-rbdplugin
- driver-registrar
- csi-rbdplugin
- liveness-prometheus

csi-rbdplugin-provisioner
- csi-provisioner
- csi-rbdplugin-attacher
- csi-snapshotter
- csi-rbdplugin
- liveness-prometheus

The node pods seem to need far less resource then the provisioners for rbd. the csi-rbdplugin in the provisioner needs way more memory then the same container in the nodeplugin.

Not sure about cephfs yet. Not suing that too heavily. As the node driver for cephfs typically is fuse based, I'm guessing the node driver for it will probably need the ability to have more then the provisioner.

**Comment by Madhu-1** [comment]
So if I add request and limit for cpu and memory should be fine.@kfox1111 Is there anything you want me to add or remove? Do we need limit?

**Comment by kfox1111** [comment]
I've been using both requests and limits for both cpu and memory to guarantee resources to pods/containers. Otherwise the pods can be bumped by other pods under resource contention. Maybe just pass through the whole resources yaml chunk? Would allow for other types of options if k8s adds more in the future without change.

**Comment by leojonathanoh** [comment]
> 
> 
> Looks like:
> 
> csi-cephfsplugin:
> 
>     * driver-registrar
> 
>     * csi-cephfsplugin
> 
>     * liveness-prometheus
> 
> 
> csi-cephfsplugin-provisioner
> 
>     * csi-attacher
> 
>     * csi-provisioner
> 
>     * csi-cephfsplugin
> 
>     * liveness-prometheus
> 
> 
> csi-rbdplugin
> 
>     * driver-registrar
> 
>     * csi-rbdplugin
> 
>     * liveness-prometheus
> 
> 
> csi-rbdplugin-provisioner
> 
>     * csi-provisioner
> 
>     * csi-rbdplugin-attacher
> 
>     * csi-snapshotter
> 
>     * csi-rbdplugin
> 
>     * liveness-prometheus
> 
> 
> The node pods seem to need far less resource then the provisioners for rbd. the csi-rbdplugin in the provisioner needs way more memory then the same container in the nodeplugin.
> 
> Not sure about cephfs yet. Not suing that too heavily. As the node driver for cephfs typically is fuse based, I'm guessing the node driver for it will probably need the ability to have more then the provisioner.

Agreed. Requests and limits should be set to guarantee these pods don't overload a node under resource pressure, and guarantee they dont get evicted. Seems like there's been a similar issue for csi plugins: https://github.com/rook/rook/issues/4113 

I would add to the list:

rook-discover
- [rook-discover](https://github.com/rook/rook/blob/6f3db3df71b87de4f3950d2eda8a86aae720c8fe/pkg/operator/discover/discover.go#L110-L140)

**Comment by Madhu-1** [comment]
am working making changes for CSI plugins, will send a PR soon
