### ISSUE TITLE
OSD Prepare pod is not created!

### ISSUE THREAD

**Issue by manavtidhan** [rook/rook#5028]
**Is this a bug report or feature request?**
* Bug Report : Its a bug report

**Deviation from expected behavior:**
There is no osd prepare pods are created after operator restart

**Expected behavior:**
I have Zap one of the only  disk in one of the nodes I didnot delte the /var/lib/rook directory as the same node is also serving as the MON pod..I was expecting that after restart the operator pod I will see the osd-prepare pod and then OSD pods on the node 

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
`apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.8
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  mon:
    count: 3
    allowMultiplePerNode: false
  # enable the ceph dashboard for viewing cluster status
  dashboard:
    enabled: true
    urlPrefix: /ceph-dashboard
    ssl: false
  disruptionManagement:
    managePodBudgets: false
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: topology.rook.io/datacenter
                  operator: In
                  values:
                    - dc1
                    - dc2
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: topology.rook.io/datacenter
                  operator: In
                  values:
                    - dc1
                    - dc2

    osd:
        nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                    - key: topology.rook.io/datacenter
                      operator: In
                      values:
                        - dc1
                        - dc2

  storage:
    useAllNodes: true
    topologyAware: true
    useAllDevices: true

`
* Operator's logs, if necessary
` op-k8sutil: Removing previous job rook-ceph-osd-prepare-avdhipldck030 to start a new one
2020-03-16 04:34:29.387186 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:31.396881 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:33.405840 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:35.413539 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:37.420794 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:39.427541 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:41.436159 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:43.443846 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:45.452942 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:47.462036 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:49.468333 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:51.474834 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:53.482211 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:55.488647 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:57.497864 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:34:59.506710 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:35:01.514417 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:35:03.523507 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:35:05.530101 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:35:07.538374 I | op-k8sutil: batch job rook-ceph-osd-prepare-avdhipldck030 still exists
2020-03-16 04:35:09.538615 W | op-k8sutil: gave up waiting for batch job rook-ceph-osd-prepare-avdhipldck030 to be deleted
2020-03-16 04:35:09.624094 I | op-osd: osd provision job started for node avdhipldck030
`
* Crashing pod(s) logs, if necessary

 Kubectl get pods -n rook-ceph

NAME                                                      READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-fzqzf                                    3/3     Running   0          118m
csi-cephfsplugin-g47hl                                    3/3     Running   0          118m
csi-cephfsplugin-j258q                                    3/3     Running   0          118m
csi-cephfsplugin-kkh8n                                    3/3     Running   0          118m
csi-cephfsplugin-provisioner-546f9cb5c5-pbz47             5/5     Running   0          118m
csi-cephfsplugin-provisioner-546f9cb5c5-td98v             5/5     Running   0          118m
csi-cephfsplugin-x4ljr                                    3/3     Running   0          118m
csi-rbdplugin-95dvb                                       3/3     Running   0          118m
csi-rbdplugin-cdlgj                                       3/3     Running   0          118m
csi-rbdplugin-cmzrw                                       3/3     Running   0          118m
csi-rbdplugin-fs6sg                                       3/3     Running   0          118m
csi-rbdplugin-jwbsr                                       3/3     Running   0          118m
csi-rbdplugin-provisioner-9c78b956f-7n6kl                 6/6     Running   0          118m
csi-rbdplugin-provisioner-9c78b956f-ck9hl                 6/6     Running   0          118m
rook-ceph-crashcollector-avdhipldck010-f58b8bbcd-nkvt7    1/1     Running   0          29m
rook-ceph-crashcollector-avdhipldck030-cc74b7854-l6fj8    1/1     Running   0          29m
rook-ceph-crashcollector-avkwhpldck020-78b78cccf6-z5nhr   1/1     Running   0          29m
rook-ceph-crashcollector-avkwhpldck030-7cd5fb7c9f-6ctff   1/1     Running   0          29m
rook-ceph-mds-myfs-a-b898bdc85-qq7jt                      1/1     Running   0          113m
rook-ceph-mds-myfs-b-fc5579c7d-qxjh9                      1/1     Running   0          113m
rook-ceph-mgr-a-6d46fcff4d-nfqlf                          1/1     Running   0          114m
rook-ceph-mon-a-7bf7d964b5-wsdwd                          1/1     Running   0          115m
rook-ceph-mon-b-56d7c6687-blch6                           1/1     Running   0          114m
rook-ceph-mon-c-7f7bc495bc-pclp9                          1/1     Running   0          114m
rook-ceph-operator-7cbb9dd98f-vm2jk                       1/1     Running   0          8m52s
rook-ceph-osd-0-6f768cff66-cmxx8                          1/1     Running   0          45m
rook-ceph-tools-7f9b9bfdb4-f9n2s                          1/1     Running   0          117m
rook-discover-8ckkz                                       1/1     Running   0          119m
rook-discover-gzmnp                                       1/1     Running   0          119m
rook-discover-h946b                                       1/1     Running   0          119m
rook-discover-hppdr                                       1/1     Running   0          119m
rook-discover-lpr5c                                       1/1     Running   0          119m
haavsg4@avppuppet01 ~/tmp/manav/onpremise_infra_deployments/k
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): rhel7
* Kernel (e.g. `uname -a`):3.10.0-957.10.1.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-docker-1", GitCommit:"8100f4dfe656d4a4e5573fe86375a5324771ec6b", GitTreeState:"clean", BuildDate:"2019-10-18T17:13:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Docker UCP
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
`[root@rook-ceph-tools-7f9b9bfdb4-f9n2s /]# ceph -s
  cluster:
    id:     6921ae33-eb9c-480e-83cd-30deaa7b21ef
    health: HEALTH_WARN
            2 MDSs report slow metadata IOs
            Reduced data availability: 64 pgs inactive
            Degraded data redundancy: 64 pgs undersized
            OSD count 1 < osd_pool_default_size 3

  services:
    mon: 3 daemons, quorum a,b,c (age 116m)
    mgr: a(active, since 6m)
    mds: myfs:1 {0=myfs-a=up:creating} 1 up:standby-replay
    osd: 1 osds: 1 up (since 47m), 1 in (since 47m)

  data:
    pools:   2 pools, 64 pgs
    objects: 0 objects, 0 B
    usage:   1.0 GiB used, 49 GiB / 50 GiB avail
    pgs:     100.000% pgs not active
             64 undersized+peered
`
currently onle two nodes have raw disk to have osd ..I was succesffull to create OSD on both of device at first but when I was trying to see how to re-use the disk  for osd creation ...I did not remove /var/lib/rook , however I do zap the raw disk as mentioned in the documents 
now the disk is clean and raw ...but I am not able to see any prepare pods are created for this node after operator restart

**Comment by travisn** [comment]
@manavtidhan It appears that the osd prepare jobs had some status from a previous run that is preventing the prepare pods from being launched again. Do you see any configmaps named `rook-ceph-osd-<nodeName>-status`? If so, delete them. Also, delete any osd prepare jobs for that node. Then restarting the operator should create it again.
