### ISSUE TITLE
tests: System disk using LVM will cause the Job of wipe devices failure

### ISSUE THREAD

**Issue by HaichaoLii** [rook/rook#5029]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In integration tests, it was found that the Job of disk-wipe needed to delete all existing LVM in the system, but the LVM of my system disk could not be deleted, so the tests failed. I've made some changes to the code to get rid of this bug. In order to complete this change, I think removing all LVM is dangerous. I need to know whether the purpose of the Job is to remove the LVM generated during the previous test, or just to create a non-intrusive initialization environment. Thank you!

**Job logs:**
![image](https://user-images.githubusercontent.com/49929365/76745225-769b0f80-67b0-11ea-8b50-11a565d8207d.png)

**Comment by satoru-takeuchi** [comment]
@HaichaoLii 

Hi, I'm trying to fix this problem.
https://github.com/rook/rook/pull/4966
