### ISSUE TITLE
prepare pods are trying to use root partition devices

### ISSUE THREAD

**Issue by sagyvolkov** [rook/rook#5036]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
no OSD pods are created
**Expected behavior:**
OSD pods to be create
**How to reproduce it (minimal and precise):**

when I tried to install rook (brand new cluster, never had rook/ceph installed before), the osd-prepare pods kept on run/error/crush until they quit and never got and OSD pods created.
**File(s) to submit**:
* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="43.81.202003052336.0"
VERSION_ID="4.3"
OPENSHIFT_VERSION="4.3"
RHEL_VERSION=8.0
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 43.81.202003052336.0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.3"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.3"
OSTREE_VERSION='43.81.202003052336.0'
* Kernel (e.g. `uname -a`):
4.18.0-147.5.1.el8_1.x86_64
* Cloud provider or hardware configuration:
AWS OCP4.3.5 cluster consist of 3 m5.4x nodes for applications and 3 i3en.2x nodes for rook/ceph.
* Rook version (use `rook version` inside of a Rook Pod): v1.2.6
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.8
* Kubernetes version (use `kubectl version`): v1.16.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
[rook_operator.log](https://github.com/rook/rook/files/4344852/rook_operator.log)
[osd-prepare_pod.log](https://github.com/rook/rook/files/4344853/osd-prepare_pod.log)
[cluster.yaml.txt](https://github.com/rook/rook/files/4344858/cluster.yaml.txt)

**Comment by leseb** [comment]
Dup of https://github.com/rook/rook/issues/5022
