### ISSUE TITLE
"rook block unmap" should support unmapping by image name

### ISSUE THREAD

**Issue by dab-q** [rook/rook#506]
One should be able to unmap a ceph block image by just specifying the name/pool:
    `rook unmap --name myimage1 [--pool-name mypool] [--all]`
If an image is mapped multiple times, the `--all` says to unmap all of them.  If `--all` isn't specified and there are multiple mappings, it should fail because of non-determinism of which device to unmap.

With that in mind, if unmapping by device name and there are multiple mappings for the underlying image, only the specific device should be unmapped, but a `--all` would unmap everything mapped to the underlying ceph block image.

**Comment by jbw976** [comment]
The rookctl tool will be removed in #1122
