### ISSUE TITLE
Add rook helm chart version 0.9.3 to rook-release repository

### ISSUE THREAD

**Issue by christianhuening** [rook/rook#5063]
Due to the removal of the `rook-stable` helm repository (https://github.com/rook/rook/pull/3061), the pre `1.0.0` versions of the helm chart als vanished. We're still on `0.9.3` and planned to update soon. 
It would be great if `0.9.3` could be re-added to the `rook-release` respository so we have our current dependency back.

CC: @travisn (ticked opened after discussion on slack)

**Comment by jbw976** [comment]
@christianhuening thanks for bringing this issue up and I definitely apologize for the hassle here. I just ran the promotion job on the 0.9 release branch and it appears to have worked OK.  I once again see a v0.9.3 entry for https://charts.rook.io/stable/.

```console
> helm repo add rook-stable https://charts.rook.io/stable
"rook-stable" has been added to your repositories
> helm search repo rook-ceph
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
rook-stable/rook-ceph	v0.9.3       	           	File, Block, and Object Storage Services for yo...
```

Hopefully this will work for you, please let me know if anything is still missing 🙇

**Comment by christianhuening** [comment]
Thanks a lot! You could've pushed this to rook-release as well. we can change the repo, that's not an issue. or don't you want to have it on the rook-release repo?

**Comment by jbw976** [comment]
the thinking was to just try to restore it to exactly how it was before to minimize any possible hiccups :slightly_smiling_face:

**Comment by christianhuening** [comment]
Thanks a lot! Will try our pipeline and then most likely close this ticket

**Comment by christianhuening** [comment]
Thanks a ton, that was successful!
