### ISSUE TITLE
Rook Ceph Mons unable to form quorum when using Calico CNI

### ISSUE THREAD

**Issue by galexrt** [rook/rook#5065]
**Is this a bug report or feature request?**
* Bug Report

**As of the current investigation this does not seem to be a Rook Ceph issue, just opening for documentation**

**Deviation from expected behavior:**

When using Calico as the CNI, it is not possible to have a Rook Ceph cluster formed (mons are created but the operator will timeout due to `quorum_status` failing; if the first mon is on the same node as the operator it works, so it seems node-to-node communication is broken Calico).

Testing with Flannel and Canal a Rook Ceph cluster can be formed.

Setting the default policy on the `FORWARD` chain (in case of k8s-vagrant-multi-node environment as the Docker version is a bit "ancient") didn't fix the issue. MTU also doesn't seem like the issue right now.

I'll continue my investigations today in the morning.

**Expected behavior:**

A Rook Ceph cluster to be able to form quorum and go through all other steps (MGR, OSDs, etc).

**How to reproduce it (minimal and precise):**

Create a Kubernetes cluster (with kubeadm and kubespray, doesn't seem to matter) and use Calico "default" YAMLs for installation (tested with Calico 3.9.5 and 3.5).
Try to create a normal Rook Ceph cluster using the default `common.yaml`, `operator.yaml`, `cluster.yaml`.

**File(s) to submit**:

TODO add some logs today morning

**Environment**:
* OS (e.g. from /etc/os-release): Tested with CentOS 7.6 and Fedora 30/31. An user has also reported the similar issue with Ubuntu 18.04.
* Kernel (e.g. `uname -a`): Varies. From 3.10.x to "latest" on Fedora.
* Cloud provider or hardware configuration: libvirt VMs and an OpenStack environment.
* Rook version (use `rook version` inside of a Rook Pod): `v1.2.6`
* Kubernetes version (use `kubectl version`): v1.16.x and v1.17.x
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm and kubespray

**Comment by mhwasil** [comment]
I tried with canal, flannel, and calico. None of them works for me.
I got the same problem. I also tried with Ubuntu 18.04, but I ended up in the same problem.
When I was using calico, I tried different calico configuratoon:
I have tried setting up calico with Ip-in-IP, and then tried `calico_endpoint_to_host_action: "ACCEPT"` as in [here](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/calico.md) , and then tried lowering `calico_mtu: 1300` from `default: 1440` as suggested in [here](https://github.com/projectcalico/calico/issues/1709#issuecomment-399350737).

chep status outputs nothing in the operaton pod:
```
[root@rook-ceph-operator-69f856fc5f-bzfqz /]# ceph -c /var/lib/rook/rook-ceph/rook-ceph.config -s


```


My environment:
```
Cloud provider openstack
OS: Centos 7.7
Rook branch: release-1.2
kube_version: v1.16.7
```

Operator log
```
2020-03-23 09:50:39.376485 I | exec: timed out
2020-03-23 09:50:44.420785 I | op-mon: mons running: [a d f]
2020-03-23 09:50:44.421170 I | exec: Running command: ceph quorum_status --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/260839454
2020-03-23 09:50:59.564974 I | exec: timed out
2020-03-23 09:51:04.587724 I | op-mon: mons running: [a d f]
2020-03-23 09:51:04.587981 I | exec: Running command: ceph quorum_status --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/231122149
2020-03-23 09:51:19.717371 I | exec: timed out
2020-03-23 09:51:24.765104 I | op-mon: mons running: [a d f]
2020-03-23 09:51:24.765453 I | exec: Running command: ceph quorum_status --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/798331136
2020-03-23 09:51:39.903774 I | exec: timed out
2020-03-23 09:51:44.957290 I | op-mon: mons running: [a d f]
2020-03-23 09:51:44.957649 I | exec: Running command: ceph quorum_status --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/741508703
2020-03-23 09:52:00.092990 I | exec: timed out
```

**Comment by alram** [comment]
:wave: I just made a PR to ceph-container that I believe should fix this. I don't have a rook environment but can you give it a shot?

You can confirm if that's the issue by looking at the logs for one of the ceph-mon Pod and looking for `unable to parse addrs in xxx` after the `ceph-mon <blabla> --mkfs <blabla>` command

**Comment by stv0g** [comment]
I can't reproduce this issue with my setup.

My environment is an **IPv6 only** network:

```
Bare metal
OS: Centos 8.1
Rook branch: v1.3.0-beta.1
kube_version: v1.18.0
Calico version: v3.13.1
kube_proxy mode: IPVS
```

**Comment by fasaxc** [comment]
I'm one of the Calico core developers but I don't know rook at all.  Please can you give me an overview of how your bootstrapping process works?  How do the rook pods connect to one another, do they go via a kubernetes service?  Are they host networked?

Calico and (recent versions of) flannel are routed networks so they don't support broadcast or multicast traffic, even on the same host (there is no bridge).  

One gotcha with services is the backing pods are only added to the service if they report ready on their healthcheck.

One gotcha with storage is that you can get bootstrapping issues if, say, kube-rpoxy or Calico needs storage to come up but rook needs kube-proxy/calico/core-dns to be running to bootstrap storage.

**Comment by orblazer** [comment]
@travisn Surely you can get a better answer than I can.

**Comment by travisn** [comment]
@fasaxc When Rook bootstraps a Ceph cluster, the sequence by the Rook operator is the following:
1. Create a k8s service for a Ceph mon daemon
1. Create a k8s deployment for a Ceph mon, which starts one pod. The pod backs the service from step 1.
1. Wait for the pod to start. The mon daemon pod internally binds to the **pod IP**.
1. Attempt to connect to the mon daemon via the **clusterIP** of the k8s service. The k8s service is expected to route the traffic to the mon daemon pod.

For example the service spec is:
```
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mon-a
  namespace: rook-ceph
spec:
  type: ClusterIP
  clusterIP: 10.96.19.219
  ports:
  - name: msgr1
    port: 6789
    protocol: TCP
    targetPort: 6789
  - name: msgr2
    port: 3300
    protocol: TCP
    targetPort: 3300
  sessionAffinity: None
```

@orblazer What does the liveness probe status show for the mon pod? And does your service description show the same? For example:
```
kubectl -n rook-ceph describe pod <mon-a-pod>
```

**Comment by fasaxc** [comment]
@travisn Thanks! On the face of it, that sounds like it should work absolutely fine with Calico.  With rook being a storage provider, could rook not being ready yet block one of Calico's dependencies from coming up (or is using this type of storage an opt-in)?

* Our calico/node daemonset depends on the API server and on kube-proxy being up (because we use the service account config in the pod, which references the kubernetes service IP).
* Core DNS depends on Calico being up (it's a good canary pod to tell if the Calico network is working properly in your cluster).

**Comment by orblazer** [comment]
@travisn That is my describe of pod `mon-a` : https://pastebin.com/XDb1yTGC

And that is describe of service `mon-a` :
```
Name:              rook-ceph-mon-a
Namespace:         rook-ceph
Labels:            app=rook-ceph-mon
                   ceph_daemon_id=a
                   mon=a
                   mon_cluster=rook-ceph
                   rook_cluster=rook-ceph
Annotations:       <none>
Selector:          app=rook-ceph-mon,ceph_daemon_id=a,mon=a,mon_cluster=rook-ceph,rook_cluster=rook-ceph
Type:              ClusterIP
IP:                10.96.184.201
Port:              msgr1  6789/TCP
TargetPort:        6789/TCP
Endpoints:         192.168.235.138:6789
Port:              msgr2  3300/TCP
TargetPort:        3300/TCP
Endpoints:         192.168.235.138:3300
Session Affinity:  None
Events:            <none>
```

**Comment by travisn** [comment]
> @travisn Thanks! On the face of it, that sounds like it should work absolutely fine with Calico. With rook being a storage provider, could rook not being ready yet block one of Calico's dependencies from coming up (or is using this type of storage an opt-in)?
> 
> * Our calico/node daemonset depends on the API server and on kube-proxy being up (because we use the service account config in the pod, which references the kubernetes service IP).
> * Core DNS depends on Calico being up (it's a good canary pod to tell if the Calico network is working properly in your cluster).

Calico shouldn't be blocked by Rook, but I'm not familiar with Calico dependencies either. If Calico is working for other components in the cluster, I don't see what the issue should be with Rook. 

@galexrt Did you perhaps get Rook working with Calico?

**Comment by galexrt** [comment]
@travisn Not having tried with the same versions Calico v3.13 and Rook v1.2.6 again (which was used during the creation of the ticket), using Calico v3.14 and latest Rook Ceph v1.3.4 works (cluster is coming up as expected spread over multiple nodes).

For whatever reason previously a Rook Ceph cluster would not start, due to the operator not being able to communicate with the mon(s).

Let's just close it as in at least multiple tests in my k8s-vagrant-multi-node environment where it wasn't working previously, it is working "now".

Thanks to everyone for commenting! :slightly_smiling_face:

**Comment by rangsaritv** [comment]
In my case, I setup my cluster wrong. I did kubeadm init  with --pod-network-cidr=192.168.0.0/16 while my master node ip is 192.168.1.29.  After I rebuild the cluster with ip not overlapped (pod-network-cidr=192.167.0.0/16), It seems to work for me.

**Comment by tadrian88** [comment]
Encountered this issue but resolved it like this:

VXLANCrossSubnet - pods weren't able to talk to each other.
After switching encapsulation to VXLAN, everything started to work correctly.

More info here:  https://github.com/projectcalico/calico/issues/6568
