### ISSUE TITLE
On the failure of Mount PVC by pod

### ISSUE THREAD

**Issue by jiayun1997** [rook/rook#5066]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Hello, everyone. Thank you for your help.
I use the [kube-registry.yaml](https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md#consume-the-shared-filesystem-k8s-registry-sample) file, create the registry service, and use cephfs as the persistent storage, but the container has been unable to mount cephfs.

All my steps and yaml files are deployed according to official [documents](https://rook.github.io/docs/rook/master/ceph-filesystem.html).

When I use the mds_namespace parameter, it will not mount.

**Expected behavior:**
Excuse me, is the problem that the registry service can't be mounted here？
What should I do next?

**File(s) to submit**:
```
$ kubectl describe pod kube-registry-65df7d789d-hbgdj
Events:
  Type     Reason       Age                   From                 Message
  ----     ------       ----                  ----                 -------
  Warning  FailedMount  52m                   kubelet, k8s-work-2  Unable to attach or mount volumes: unmounted volumes=[image-store], unattached volumes=[default-token-l7h54 image-store]: timed out waiting for the condition
  Warning  FailedMount  32m (x5 over 70m)     kubelet, k8s-work-2  Unable to attach or mount volumes: unmounted volumes=[image-store], unattached volumes=[image-store default-token-l7h54]: timed out waiting for the condition
  Warning  FailedMount  2m25s (x52 over 70m)  kubelet, k8s-work-2  (combined from similar events): MountVolume.MountDevice failed for volume "pvc-981a495f-9106-45f0-ae0b-1929c5f18dbe" : rpc error: code = Internal desc = an error occurred while running (7786) mount [-t ceph 10.240.133.189:6789,10.240.158.120:6789,10.240.10.151:6789:/volumes/csi/csi-vol-f1be7536-6cef-11ea-ab2e-b60ea5019489/db67eb8e-50d6-42aa-abf4-e308f76fecd0 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-981a495f-9106-45f0-ae0b-1929c5f18dbe/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-886796151,mds_namespace=myfs]: exit status 32: mount error 22 = Invalid argument
```
```
$ kubectl get sc
NAME              PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
rook-ceph-block   rook-ceph.rbd.csi.ceph.com      Delete          Immediate           false                  176m
rook-cephfs       rook-ceph.cephfs.csi.ceph.com   Delete          Immediate           false                  73m
```

```
$ kubectl get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
ceph-rbd-claim   Bound    pvc-c2cd2e71-4227-417c-bf69-04123d35591d   2Gi        RWO            rook-ceph-block   175m
cephfs-pvc       Bound    pvc-981a495f-9106-45f0-ae0b-1929c5f18dbe   1Gi        RWX            rook-cephfs       75m
```

Here are my actions in direct mount pod：
```
$ kubectl exec -it rook-direct-mount-85b9d79778-hst9t bash -n rook-ceph
[root@k8s-work-2 /]# mon_endpoints=$(grep mon_host /etc/ceph/ceph.conf | awk '{print $3}')
[root@k8s-work-2 /]# my_secret=$(grep key /etc/ceph/keyring | awk '{print $3}')
[root@k8s-work-2 /]# mount -t ceph -o mds_namespace=myfs,name=admin,secret=$my_secret $mon_endpoints:/ /tmp/registry
mount error 22 = Invalid argument
[root@k8s-work-2 /]# mount -t ceph -o name=admin,secret=$my_secret $mon_endpoints:/ /tmp/registry
[root@k8s-work-2 /]# touch /tmp/registry/test
[root@k8s-work-2 /]# ll /tmp/registry/
total 0
-rw-r--r-- 1 root root   0 Mar 23 11:21 test
drwxr-xr-x 1 root root 158 Mar 23 09:01 volumes
[root@k8s-work-2 /]# umount /tmp/registry/
[root@k8s-work-2 /]# ll /tmp/registry/
total 0
[root@k8s-work-2 /]# mount -t ceph -o name=admin,secret=$my_secret $mon_endpoints:/ /tmp/registry
[root@k8s-work-2 /]# ll /tmp/registry/
total 0
-rw-r--r-- 1 root root   0 Mar 23 11:21 test
drwxr-xr-x 1 root root 158 Mar 23 09:01 volumes
```
kubelet log:
```
Mar 23 20:08:15 k8s-work-2 kubelet: E0323 20:08:15.778692    5481 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-f1be7536-6cef-11ea-ab2e-b60ea5019489\"" failed. No retries permitted until 2020-03-23 20:10:17.778655998 +0800 CST m=+31241.527230031 (durationBeforeRetry 2m2s). Error: "MountVolume.MountDevice failed for volume \"pvc-981a495f-9106-45f0-ae0b-1929c5f18dbe\" (UniqueName: \"kubernetes.io/csi/rook-ceph.cephfs.csi.ceph.com^0001-0009-rook-ceph-0000000000000001-f1be7536-6cef-11ea-ab2e-b60ea5019489\") pod \"kube-registry-65df7d789d-hbgdj\" (UID: \"fe593ef8-1c8a-47f7-9697-9126c62b004a\") : rpc error: code = Internal desc = an error occurred while running (9784) mount [-t ceph 10.240.133.189:6789,10.240.158.120:6789,10.240.10.151:6789:/volumes/csi/csi-vol-f1be7536-6cef-11ea-ab2e-b60ea5019489/db67eb8e-50d6-42aa-abf4-e308f76fecd0 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-981a495f-9106-45f0-ae0b-1929c5f18dbe/globalmount -o name=csi-cephfs-node,secretfile=/tmp/csi/keys/keyfile-215630901,mds_namespace=myfs]: exit status 32: mount error 22 = Invalid argument\n"
Mar 23 20:09:01 k8s-work-2 systemd: Started Session 6249 of user root.
Mar 23 20:09:17 k8s-work-2 kubelet: E0323 20:09:17.867390    5481 kubelet.go:1680] Unable to attach or mount volumes for pod "kube-registry-65df7d789d-hbgdj_default(fe593ef8-1c8a-47f7-9697-9126c62b004a)": unmounted volumes=[image-store], unattached volumes=[image-store default-token-l7h54]: timed out waiting for the condition; skipping pod
```

**Environment**:
* OS (e.g. from /etc/os-release): Centos:7.7
* Kernel (e.g. `uname -a`): Linux  4.4.215-1.el7.elrepo.x86_64
* Cloud provider or hardware configuration: Local 4C8G
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.1.0-beta.0.1078.g695dc4f-dirty
* Storage backend version (e.g. for ceph do `ceph -v`): ceph : 14.2.8  nautilus (stable)
* Kubernetes version (use `kubectl version`):kubernetes: v1.17.2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
ceph -s
  cluster:
    id:     07108dd6-1d40-42bf-bb9b-364a833f6201
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 3h)
    mgr: a(active, since 2h)
    mds: myfs:1 {0=myfs-b=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 3h), 3 in (since 3h)

  data:
    pools:   3 pools, 96 pgs
    objects: 41 objects, 8.5 MiB
    usage:   3.0 GiB used, 297 GiB / 300 GiB avail
    pgs:     96 active+clean

  io:
    client:   1.2 KiB/s rd, 2 op/s rd, 0 op/s wr
```

**Comment by Madhu-1** [comment]
@joscollin can you check what's wrong here?

**Comment by joscollin** [comment]
The error message in evident. Check if you have myfs created.

**Comment by jiayun1997** [comment]
> 错误消息显而易见。检查是否创建了myfs。

$ ceph fs ls
name: myfs, metadata pool: myfs-metadata, data pools: [myfs-data0 ]

**Comment by jiayun1997** [comment]
The yaml file path I use is rook/cluster/examples/kubernetes/ceph.

**Comment by joscollin** [comment]
Check if the ceph version on the client is a compatible version as it doesn't recognize `mds_namespace` parameter.

**Comment by jiayun1997** [comment]
> Check if the ceph version on the client is a compatible version as it doesn't recognize `mds_namespace` parameter.

How can I check it? The version of CEPH for cluster installation is: 14.2.8 Nautilus (stable)

**Comment by jiayun1997** [comment]
> 检查客户端上的ceph版本是否为兼容版本，因为它无法识别`mds_namespace`参数。

Hello, what should I do next? I've been bothered by this problem for a day.

**Comment by jiayun1997** [comment]
This is what the dmesg command displays in the toolbox container
`libceph: bad option at 'mds_namespace=myfs'`

**Comment by joscollin** [comment]
I meant ceph version on the client not the Ceph cluster version.

**Comment by jiayun1997** [comment]
> I meant ceph version on the client not the Ceph cluster version.

I built a CEPH cluster (14.2.8 Nautilus) on the host computer. This problem also occurs when mounting with the kernel. I'm trying to lower the kernel and retest.
![image](https://user-images.githubusercontent.com/48053995/77410745-55f93800-6df6-11ea-9f54-712b5df902d8.png)

**Comment by jiayun1997** [comment]
I don't have the problem of invalid parameters on 3.10 kernel.

![image](https://user-images.githubusercontent.com/48053995/77426399-5c47de00-6e0f-11ea-98f0-b1711beea39d.png)

Next, I will try to test whether there is such a problem on the 5. X kernel.

**Comment by joscollin** [comment]
@jiayun1997 As I checked with my colleague, 
the mainline commit was 430afbadd6c885557ef2fb8c454bd5bba23a9850 so it looks like it went into kernel v4.10.

> OS (e.g. from /etc/os-release): Centos:7.7
Kernel (e.g. uname -a): Linux 4.4.215-1.el7.elrepo.x86_64

So probably this^ doesn't have a back-port of it.

**Comment by jiayun1997** [comment]
I have no problem mounting on the 5.5 kernel, that is, there is a problem with the 4.4 kernel. 
My friend has also tested that mount -o mds_namespace = foo cannot be used on the 4.4 kernel

![image](https://user-images.githubusercontent.com/48053995/77428977-ea25c800-6e13-11ea-8312-5634383f8025.png)

**Comment by joscollin** [comment]
@jiayun1997 Try 4.10 kernel

**Comment by jiayun1997** [comment]
> @jiayun1997 Try 4.10 kernel

Hello, do you mean `mds_ namespace` is OK on the 4.10 kernel? 
At the same time, kernel must be > = 4.10?

**Comment by joscollin** [comment]
> > @jiayun1997 Try 4.10 kernel
> 
> Hello, do you mean `mds_ namespace` is OK on the 4.10 kernel?
> At the same time, kernel must be > = 4.10?

Yes

**Comment by Madhu-1** [comment]
> > @jiayun1997 Try 4.10 kernel
> 
> Hello, do you mean `mds_ namespace` is OK on the 4.10 kernel?
> At the same time, kernel must be > = 4.10?

min kernel version required is 4.17 for cephfs

**Comment by jiayun1997** [comment]
> > > @jiayun1997 Try 4.10 kernel
> > 
> > 
> > Hello, do you mean `mds_ namespace` is OK on the 4.10 kernel?
> > At the same time, kernel must be > = 4.10?
> 
> min kernel version required is 4.17 for cephfs

So why do I have no problem operating on the 3.10 kernel?

**Comment by Madhu-1** [comment]
> > > > @jiayun1997 Try 4.10 kernel
> > > 
> > > 
> > > Hello, do you mean `mds_ namespace` is OK on the 4.10 kernel?
> > > At the same time, kernel must be > = 4.10?
> > 
> > 
> > min kernel version required is 4.17 for cephfs
> 
> So why do I have no problem operating on the 3.10 kernel?

kernel version < 4.17 might not support quota feature

**Comment by jiayun1997** [comment]
> > > > > @jiayun1997 Try 4.10 kernel
> > > > 
> > > > 
> > > > Hello, do you mean `mds_ namespace` is OK on the 4.10 kernel?
> > > > At the same time, kernel must be > = 4.10?
> > > 
> > > 
> > > min kernel version required is 4.17 for cephfs
> > 
> > 
> > So why do I have no problem operating on the 3.10 kernel?
> 
> kernel version < 4.17 might not support quota feature

Because my friend has been using the 3.10 kernel. 
No problem with his CEPH cluster, no problem with his look operator cluster, and cephfs can be used as expected, so I didn't realize it was caused by the kernel

**Comment by jiayun1997** [comment]
Thank you. I will try to change the kernel to a version smaller than 4.17 tomorrow. Is there any problem

**Comment by joscollin** [comment]
@jiayun1997 I think you meant greater than 4.17
