### ISSUE TITLE
Remove ceph rollback checking to allow minor release rollback

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#5070]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Rook should allow ceph minor release rollback. Currently, rook minor release rollback is not blocked. 
Here's the operator log showing the block. Instead of blocking, operator may display warning message saying it's not supported and up to the user's risk on rolling back. 

```
2020-03-23 20:09:45.058643 E | op-cluster: failed to determine if we should upgrade or not. image spec version 14.2.7-0 nautilus is lower than the running cluster version 14.2.8-0 nautilus, downgrading is not supported
```
**What is use case behind this feature:**
With the same rook release, ceph minor upgrade may be performed and rolled back for quick patch delivery.

**Environment**:

This is tested in rook 1.2.6 with ceph v14.2.8. Then try to downgrade ceph from v14.2.8 to v14.2.7.

**Comment by leseb** [comment]
@jdurgin thoughts?

**Comment by jdurgin** [comment]
There's no testing or guarantee that minor release downgrades work for ceph. It's not uncommon for downgrades to fail due to data format changes required by bug fixes.

**Comment by leseb** [comment]
> There's no testing or guarantee that minor release downgrades work for ceph. It's not uncommon for downgrades to fail due to data format changes required by bug fixes.

Thanks! Closing then :)
