### ISSUE TITLE
Failed to start the resizer container due to misinterpretation of the cephcsi version

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#5073]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The csi-rbdplugin-provisioner pod failed to start the resizer container due to mis-interpretation of the cephcsi version if the image registry includes ":" as part of name.  i.e., "bcmt-registry:5000/csi/cephcsi:v2.0.0". 

**Expected behavior:**
The cephcsi version can be parsed differently to get the correct cephcsi version. So the resizer container can be started as part of csi-rbdplugin-provisioner pod.
Would like to know if there's any workaround without changing the registry name. 

**How to reproduce it (minimal and precise):**

Deploy rook 1.2.5/ceph14.2.7 and cephcsi v2.0.0 version. The cephcsi's image registry has ":" as part of its name. The csi-rbdplugin-provisioner pod starts with 5 containers without resizer container. 

The code failed at file " ./operator/ceph/csi/spec.go" line 230.  The version should be in the last element: [len(csiPluginImage)-1], not necessarily the hardcoded 2nd element. 
Any possible to include the above code change? The similar issue happened at line 222 as well.
```
csiPluginImage := strings.Split(CSIParam.CSIPluginImage, ":")
        // as ceph-csi v2.x.x support resizer, enable it
        if len(csiPluginImage) > 1 {
                **if strings.HasPrefix(csiPluginImage[1], "v2.") {**
                        tp.EnableResizer = true
                }
        }
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.2.5
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.7
* Kubernetes version (use `kubectl version`): v1.17
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
Released in v1.2.7
