### ISSUE TITLE
Allow overriding minimum pod resource limits on small clusters

### ISSUE THREAD

**Issue by SerialVelocity** [rook/rook#5079]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add a flag/environment variable to stop enforcing minimum pod limits.

**What is use case behind this feature:**
I run ceph on 2GB hosts and require setting the resource limits way below what you currently allow. For instance, my cluster is currently using the following amount of memory for the different resources (these are the maximum values over all the hosts):
- OSD: 159Mi
- MON: 85Mi
- MDS: 157Mi
- MGR: 259Mi

I know it isn't the typical use-case which is why I think it might be better to have an extra environment variable like `DANGEROUS_DO_NOT_ENFORCE_MINIMUM_RESOURCES`.

**Environment**:

Using a VPS with 2 cores, 2GB RAM and a 10GB SSD dedicated to Ceph. I also have other dedi-hosts with 2 cores, 4GB RAM, and a 1TB HDD with a 750GB partition dedicated to Ceph.

**Comment by muhlba91** [comment]
We have similar situations with test clusters for development environments.
It would be great to be able to set a lower memory limit.

**Comment by KaelBaldwin** [comment]
The documentation says the minimum for mds pods is 4096 MB... the highest ours has reached in the past 15 days is 230 MB. I'm a little confused why the minimum is so high?

Would really like to lock down the memory on our cluster but reserving an extra 7000+ MB seems like a rather large waste of resources.

**Comment by SerialVelocity** [comment]
@KaelBaldwin If you want a temporary workaround, I publish https://github.com/SerialVelocity/rook-smallhost to https://hub.docker.com/r/chillichef/rook-smallhost

It disables:
 - The minimum memory limits
 - The "executable" liveness probes which cause much higher CPU usage in my cluster (encountered this with other software before too)

**Comment by travisn** [comment]
> The documentation says the minimum for mds pods is 4096 MB... the highest ours has reached in the past 15 days is 230 MB. I'm a little confused why the minimum is so high?
> 
> Would really like to lock down the memory on our cluster but reserving an extra 7000+ MB seems like a rather large waste of resources.

@KaelBaldwin It really does depend on load. Small clusters or smaller workloads really wouldn't have the same memory targets as larger clusters or workloads. If we're wasting resources in the case of smaller clusters, we really should just document the *recommended* minimums, but allow configuration to something smaller if desired.
@leseb Any reason to keep the required minimums? They are resulting in workarounds for small clusters. :)

**Comment by leseb** [comment]
I believe the intent to deliver software that is production quality ready, so once the cluster gets some write activity those limits make sense.
If Rook only gets deployed with no load on it then obviously they are less relevant.

We can always have a mode to disable this though.
