### ISSUE TITLE
Rook in Kubernetes example for object storage

### ISSUE THREAD

**Issue by rothgar** [rook/rook#509]
The example Kubernetes documents shows how to create a cluster and consume block storage within the cluster. There should also be an example of creating an object storage from a cluster for applications internal to the cluster to use.

Once a service endpoint is created it should be trivial to also expose that endpoint external to the cluster via a load balancer or ingress controller.

Would really like to have some examples on this because the existing `rook` commands in the documentation https://github.com/rook/rook/blob/master/Documentation/client.md#object-storage obviously don't work from outside the cluster.

**Comment by rothgar** [comment]
Here's what I did to expose the s3 endpoint outside the cluster.

I started the rook-client pod as describe [here](https://github.com/rook/rook/blob/master/Documentation/kubernetes.md#rook-client)
Then created the object storage described [here](https://github.com/rook/rook/blob/master/Documentation/client.md#object-storage)

Inside the pod I ran the `rook object connection rook-user --format env-var` so I can use it later outside the pod.

I then saved the existing service config with `kubectl get -n rook svc rgw -o yaml > rook-s3.svc.yaml` and edited the rook-s3.svc.yaml file. I change type to NodePort, renamed the service to rook-ext and deleted some lines that weren't needed (selfLink, uid, resourceVersion, etc.)

I then created this new service with `kubectl create -f rook-s3.svc.yaml` and then found what port the service got with `kubectl get svc -n rook rgw-ext`

Now I was able to use the environment variables I got from before with my AWS_ENDPOINT being a $NODE_IP:$SERVICE_PORT.

This seems to work fine for my testing needs.

**Comment by bassam** [comment]
Our plan it to expose a TPR for object storage going forward. You should be able to do something like:

```
kubectl create -f my-object-store.yaml
```

and there is not a service exposed in side the cluster with the AWS_ENDPOINT already setup.

**Comment by rothgar** [comment]
So you'll have another object store TPR on top of the existing cluster TPR?

**Comment by bassam** [comment]
Yes. The rook cluster TPR essentially defines the raw cluster. The object store would TPR would layer on top and reference the storage cluster it should use. Our operator will handle the managing both. Make sense?

**Comment by rothgar** [comment]
It makes perfect sense. I'm just impatient :shipit: 
Would it be worth it to sending a PR for the manual steps above or should I just close this and wait for the fully managed option with TPR + operator?

**Comment by bassam** [comment]
Sure i think its worth updating the docs to show the steps you followed. Thanks @rothgar.

**Comment by travisn** [comment]
@rothgar are you planning on a PR? If not I'll take a stab at it this afternoon.

**Comment by rothgar** [comment]
Sorry this fell off my radar. I'm not sure how far the group got with testing. Go ahead and add the steps to the doc if you have time.

**Comment by travisn** [comment]
no problem @rothgar, thanks for the input on the docs! feel free to add feedback to #578 if i missed anything.
