### ISSUE TITLE
Enhance CephBlockPools and CephFilesystem CRD to additionally support Bluestore compression enabled pools.

### ISSUE THREAD

**Issue by ShyamsundarR** [rook/rook#5116]
** Feature Request **
Enhance `CephBlockPools` and `CephFilesystem` CRD to additionally support Bluestore compression enabled pools.

**What should the feature do:**
The feature request is to add an additional `compression` parameter in the above CRDs that can be set to a desired compression mode as defined by Bluestore per pool compression [modes](https://docs.ceph.com/docs/master/rados/configuration/bluestore-config-ref/#inline-compression).

This enables creating backing pools for RBD and CephFS data, that are enabled for Bluestore compression.

**What is use case behind this feature:**
Compression helps reduce total storage in-use and thus provides a better usable capacity. The trade-off is between some lost CPU performance (the attempt to compress) to gain possible compression based storage usage reduction.

Thus, for users/workloads that either have compressible data, or are willing to make the performance trade-off, this feature would help setup pools with the said properties.

**NOTE**: Ideally to leverage these compressed pools, the kubernetes admin would have to create relevant StorageClasses that uses these compression enabled pools to provision from.

**Environment**:
I would state, this applies to all environments.

**Comment by mykaul** [comment]
Do we need anything for the RGW pool?

**Comment by ShyamsundarR** [comment]
> Do we need anything for the RGW pool?

The pool handling and its related attributes are common across CephFS, RBD and RGW. Thus, the PR that makes this change is applicable for RGW as well (both data and metadata pools, but one would assume the setting is meaningful for the data pool only).
