### ISSUE TITLE
Ceph: NFS-Ganesha config should be user modifiable

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#5122]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Ceph's NFS-Ganesha should have adjustable config so that NFS-Ganesha server instances can be tuned for workloads.

Currently the NFS-Ganesha config is very hardcoded and looks in code like this:
```go
NFS_CORE_PARAM {
	Enable_NLM = false;
	Enable_RQUOTA = false;
	Protocols = 4;
}

CACHEINODE {
	Dir_Chunk = 0;
	NParts = 1;
	Cache_Size = 1;
}

EXPORT_DEFAULTS {
	Attr_Expiration_Time = 0;
}

NFSv4 {
	Delegations = false;
	RecoveryBackend = 'rados_cluster';
	Minor_Versions = 1, 2;
}

RADOS_KV {
	ceph_conf = '` + cephconfig.DefaultConfigFilePath() + `';
	userid = ` + userID + `;
	nodeid = ` + nodeID + `;
	pool = "` + n.Spec.RADOS.Pool + `";
	namespace = "` + n.Spec.RADOS.Namespace + `";
}

RADOS_URLS {
	ceph_conf = '` + cephconfig.DefaultConfigFilePath() + `';
	userid = ` + userID + `;
	watch_url = '` + url + `';
}

%url	` + url + `
```

`CACHEINODE` will affect NFS performance, as it includes cache settings; changing this config is a must. But some investigation is still necessary. We should determine which configs need set and which ones do not need set and allow users to override some of them as desired. What are possible configs that are **not** part of the config here? I assume RADOS_URLS and RADOS_KV should not be modified by users, yes? Should we make it so users can supply a config section manually without making CRD configs for them individually?

**What is use case behind this feature:**

Tuning NFS-Ganesha servers for user workloads.

**Environment**:
Users of Ceph and NFS with performance needs, especially those needs which caching will help with. I don't know if other specifics exist currently.

**Comment by sebastian-philipp** [comment]
ping @varshar16

**Comment by varshar16** [comment]
There should be an option for user to manually pass config  options as a json file. But we definitely don't want them to modify RADOS_URLS, RADOS_KV or NFSv4 blocks. Apart from EXPORT_DEFAULTS block other config options needs to be set, right? @jtlayton 

Can `ceph_conf=` be set through `CEPH_CONF` environment variable in rook?

**Comment by jtlayton** [comment]
> There should be an option for user to manually pass config options as a json file. But we definitely don't want them to modify RADOS_URLS, RADOS_KV or NFSv4 blocks. Apart from EXPORT_DEFAULTS block other config options needs to be set, right? @jtlayton
> 

I wouldn't say "definitely". I think we probably need to allow for people to change more or less arbitrary settings in the config, as we don't know what we'll need to tweak to help performance or adapt this in real customer environments. Of course, doing that implies that "You Know What You Are Doing", and if you change it on your own and it breaks things, you get to keep both pieces.

**Comment by sebastian-philipp** [comment]
cc @mgfritch

**Comment by jtlayton** [comment]
>
> `CACHEINODE` will affect NFS performance, as it includes cache settings; changing this config is a must. But some investigation is still necessary. We should determine which configs need set and which ones do not need set and allow users to override some of them as desired. What are possible configs that are **not** part of the config here? I assume RADOS_URLS and RADOS_KV should not be modified by users, yes? Should we make it so users can supply a config section manually without making CRD configs for them individually?

CACHEINODE affects performance, but it also affects resource consumption by ganesha and cache coherency between servers when deployed in a clustered configuration. The settings we've recommended are mostly intended to disable caching in ganesha itself, primarily because:

libcephfs + FSAL_CEPH lack a mechanism for the library to request that ganesha release resources (caps, dentries, etc.), in response to resource pressures in the library or in the MDS. By keeping most of the caches in the libcephfs layer, we allow the normal cephfs mechanisms for this to work better.

This also means that we can ensure that the caches maintained by different heads in a cluster of ganeshas are more coherent. If we allow the ganesha servers to cache data beyond where libcephfs would normally allow it, then we risk data-integrity issues.

So, while I think there is benefit to allowing admins to change some of these settings, we need to make it _very_ clear that the defaults are set that way for a reason, and that if you change them you may encounter all sorts of problems, including silent data corruption.

**Comment by mgfritch** [comment]
NFS with `cephadm` has a similar issue: https://github.com/ceph/ceph/pull/34382

Maybe we allow these in an orchestrator service spec yaml:
```
service_type: nfs
service_id: cluster-foo
placement:
  host_pattern: '*'  
NFS_CORE_PARAM: 
  Enable_NLM: true
CACHEINODE:
  Dir_Chunk: 0
  NParts: 1
  Cache_Size: 1
```

... and then do an orchestrator apply/reconfig? 
Which could solve this issue for both rook and cephadm?

**Comment by BlaineEXE** [comment]
Would this handle the nested configs that NFS-Ganesha can use? e.g., `EXPORT { FSAL { FSAL {} } }`

https://github.com/nfs-ganesha/nfs-ganesha/blob/master/src/config_samples/config.txt

**Comment by BlaineEXE** [comment]
While Rook could overwrite those that are necessary, I am concerned about how users would add items to NFSv4 as an example. Rook could populate a configmap that users could modify afterwards, or the CRD option exists, but Rook would have to make sure to merge the configs delicately.

**Comment by mgfritch** [comment]
> Would this handle the nested configs that NFS-Ganesha can use? e.g., `EXPORT { FSAL { FSAL {} } }`
> 
> https://github.com/nfs-ganesha/nfs-ganesha/blob/master/src/config_samples/config.txt

it could be defined as a nested dictionary of dictionaies .. where each key generates another nested config block ?

> While Rook could overwrite those that are necessary, I am concerned about how users would add items to NFSv4 as an example. Rook could populate a configmap that users could modify afterwards, or the CRD option exists, but Rook would have to make sure to merge the configs delicately.

or could orchestrator generate a base config (for use by both rook and cephadm), and then allow for any user defined value(s) to take precedence over the ones contained in the base config? ... with the assumption that they "know" what they are doing ...

**Comment by BlaineEXE** [comment]
> > Would this handle the nested configs that NFS-Ganesha can use? e.g., `EXPORT { FSAL { FSAL {} } }`
> > https://github.com/nfs-ganesha/nfs-ganesha/blob/master/src/config_samples/config.txt
> 
> it could be defined as a nested dictionary of dictionaies .. where each key generates another nested config block ?
> 
> > While Rook could overwrite those that are necessary, I am concerned about how users would add items to NFSv4 as an example. Rook could populate a configmap that users could modify afterwards, or the CRD option exists, but Rook would have to make sure to merge the configs delicately.
> 
> or could orchestrator generate a base config (for use by both rook and cephadm), and then allow for any user defined value(s) to take precedence over the ones contained in the base config? ... with the assumption that they "know" what they are doing ...

I think that would work. We want to be careful to make sure the dictionary merging is recursive. Good unit tests, obviously. There is probably a go or even k8s library for that for Rook though.

**Comment by jtlayton** [comment]
I think it'd probably be good to start by identifying the differences in recommended settings between FSAL_RGW and FSAL_CEPH deployments, and ensure that those can be tuned appropriately. Once you have the infrastructure in place for that, you can always expand it to include other settings as needed.

**Comment by BlaineEXE** [comment]
Not stale.

**Comment by batrick** [comment]
> NFS with `cephadm` has a similar issue: [ceph/ceph#34382](https://github.com/ceph/ceph/pull/34382)
> 
> Maybe we allow these in an orchestrator service spec yaml:
> 
> ```
> service_type: nfs
> service_id: cluster-foo
> placement:
>   host_pattern: '*'  
> NFS_CORE_PARAM: 
>   Enable_NLM: true
> CACHEINODE:
>   Dir_Chunk: 0
>   NParts: 1
>   Cache_Size: 1
> ```
> 
> ... and then do an orchestrator apply/reconfig?
> Which could solve this issue for both rook and cephadm?

I don't think we want to get in the business of orchestrator managed configs. The orchestrator config (bootstrap config) should be as minimal as possible: let the higher level abstraction configure NFS-Ganesha.

@varshar16  is working on a ticket for user-defined NFS-Ganesha config adendums; https://tracker.ceph.com/issues/45747
