### ISSUE TITLE
Rook-ceph doesn't recognize our disks as ROOK_LV_BACKED_PV

### ISSUE THREAD

**Issue by internetionals** [rook/rook#5139]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After a succesfull initialization and fully working setup the operator updates our OSD deployments in a way that they fail to start.

**Expected behavior:**
The OSD pods start without error.

**How to reproduce it (minimal and precise):**
On our platform we've triggered this bug 2 times, but I don't know of a general reproduction.

Short description of our setup:
- Local block based PVs based on LVM logical volumes (using the local-static-provisioner with symlinks: /media/lbd/rook-ceph-data/d1 -> /dev/main/lbd_rook-ceph-data_d1)
- Rook-ceph initialized using 1.2.5 and recently upgraded to 1.2.7 (both exhibiting this problem)
- Each update by the operator sets `ROOK_LV_BACKED_PV="false"` on the OSD deployments, which we have to change to `ROOK_LV_BACKED_PV="true"` to make things work again

Additional information:

The first time the operator updated the OSD deployments it also configured the wrong `ROOK_LV_PATH` (it was `main/lbd_rook-ceph-data_d1` instead of `/dev/main/lbd_rook-ceph-data_d1`), which lead to it failing to parse LV information. But after we manually updated all deployments this error went away and it never again changed the `ROOK_LV_PATH` to the wrong value.

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
* Kernel (e.g. `uname -a`): 4.19.67-2 (from Debian)
* Cloud provider or hardware configuration: Azure VM
* Rook version (use `rook version` inside of a Rook Pod): v1.2.7
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.8
* Kubernetes version (use `kubectl version`): v1.14.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by morimoto-cybozu** [comment]
I also experienced this problem.  I implemented this function of LV_BACKED_PV and missed the case of restarting the OSD pod.  I'm going to send a PR to fix this soon.

@travisn 
This is a critical issue for using OSD on PVC with LVM.  Can we include the fix for 1.3?

**Comment by leseb** [comment]
> I also experienced this problem. I implemented this function of LV_BACKED_PV and missed the case of restarting the OSD pod. I'm going to send a PR to fix this soon.
> 
> @travisn
> This is a critical issue for using OSD on PVC with LVM. Can we include the fix for 1.3?

Quickly then :-), today.

**Comment by morimoto-cybozu** [comment]
@leseb 
I'm going to send the fix in a few hours.

**Comment by internetionals** [comment]
A cursory glance by me suggests that this would be fixing the problem we're experiencing. I'll try upgrading to the next 1.3 beta when this is merged.

**Comment by internetionals** [comment]
@moricho: Might the need for me to manually having to adjust ROOK_LV_PATH (by adding `/dev/` as prefix) after the first redeployment also be related? Not too big of an issue as it was a one time ordeal.

**Comment by morimoto-cybozu** [comment]
@internetionals 
Not exactly.  `ROOK_LV_PATH` does not seem to have importance in LV-backed-PV.  The path is used for activating a VG inside the target block device.  In the case of LV-backed-PV, the target device is LV and the VG is already activated.
So it should be OK to leave `ROOK_LV_PATH` in the form of "vg/lv".  It seems somewhat irregular, though.

**Comment by satoru-takeuchi** [comment]
@internetionals I added a `backport-release-1.2` tag to #5199 . So this problem will automatically be backported to v1.2 soon after merging this PR to master.

**Comment by leseb** [comment]
cherry-pick failed for 1.2 branch, https://github.com/rook/rook/pull/5199/checks?check_run_id=567343131.
You need to send a PR directly in release-1.2 if you want this or just get 1.3 when it gets out (really soon).

**Comment by satoru-takeuchi** [comment]
@leseb So, can I remove backport-release-1.2 from #5199 and make a PR for release-1.2 after releasing v1.3?

**Comment by satoru-takeuchi** [comment]
I found @internetionals said that he'll try v1.3 beta. So I remove backport-release-1.2 anyway.

**Comment by internetionals** [comment]
As soon as I'm able to install the v1.3.0 chart (currently not (yet) available in the helm index.yaml on the release site) I'll try that version. Thanks for the help.
