### ISSUE TITLE
cluster-on-pvc.yaml fails to be created with the topology constraints example

### ISSUE THREAD

**Issue by travisn** [rook/rook#5149]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
There is an error in the cluster-on-pvc.yaml example. There are extra spaces in the new topology constraints example, causing the resource creation to fail. Removing the extra spaces fixes the error.
```
kubectl create -f cluster-on-pvc.yaml 
error: error parsing cluster-on-pvc.yaml: error converting YAML to JSON: yaml: line 85: mapping values are not allowed in this context
```

@satoru-takeuchi Can you take a look?

**Expected behavior:**
Creating cluster-on-pvc.yaml should succeed.

**How to reproduce it (minimal and precise):**

kubectl create -f cluster-on-pvc.yaml

**Comment by satoru-takeuchi** [comment]
Oops, my fault. I'll send a PR soon.
