### ISSUE TITLE
The mon and/or osd pod memory consumption continue increases and not even 

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#5175]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
With an identical resource setup, the mon and/or osd memory consumption is not even. And one of them increased considerably. Will open a ceph ticket as well. 
**Expected behavior:**
With an identical resource setup, the mon/osd pod memory consumption should be similar.

**How to reproduce it (minimal and precise):**

Deployed the rook cluster with 3 OSDs and 3 MONs, ran some traffic. All in sunny day case.
1). Below is one example with the specified configuration.  The pod mon-a consumes about 50% RSS memory than the other two mon pods. All 3 mons are running on the identical hardware setup. 
```
# ceph status
  cluster:
    id:     1e2e65aa-0bd4-45fc-8517-7244ee30362b
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 22h)
    mgr: a(active, since 4m)
    osd: 3 osds: 3 up (since 22h), 3 in (since 30h)
    rgw: 1 daemon active (rook.ceph.store.a)
 
  data:
    pools:   8 pools, 256 pgs
    objects: 96.70k objects, 377 GiB
    usage:   1.1 TiB used, 1.6 TiB / 2.7 TiB avail
    pgs:     256 active+clean
 
# ceph osd status
+----+-----------------+-------+-------+--------+---------+--------+---------+-----------+
| id |       host      |  used | avail | wr ops | wr data | rd ops | rd data |   state   |
+----+-----------------+-------+-------+--------+---------+--------+---------+-----------+
| 0  | bcmt-control-01 |  378G |  552G |    0   |     0   |    0   |     0   | exists,up |
| 1  | bcmt-control-02 |  378G |  552G |    0   |     0   |    0   |     0   | exists,up |
| 2  | bcmt-control-03 |  378G |  552G |    0   |     0   |    0   |     0   | exists,up |
+----+-----------------+-------+-------+--------+---------+--------+---------+-----------+
# knc top pods | egrep "osd|mon"
rook-ceph-mon-a-57854657b8-8c8h9                   5m           951Mi           
rook-ceph-mon-b-655d5d4b97-krngs                   4m           632Mi           
rook-ceph-mon-c-6bcffb8cbf-p8nq9                   3m           624Mi           
rook-ceph-osd-0-5f76d76bfb-clpl7                   2m           2847Mi          
rook-ceph-osd-1-d96fbfd8d-s7g5r                    2m           2813Mi          
rook-ceph-osd-2-568d4ccd5b-6kx8r                   2m           2756Mi          

[root@bcmt-control-01 ~/rook245]# pidstat -r -p 3441
Linux 4.18.0-147.5.1.el8_1.x86_64 (bcmt-control-01)     04/04/2020      _x86_64_        (48 CPU)

07:00:39 PM   UID       PID  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
07:00:39 PM   167      3441     13.33      0.00 1119708 655796   0.25  ceph-mon

[root@bcmt-control-01 ~/rook245]# ssh -q -i ./0207.pem cloud-user@bcmt-control-02 "sudo pidstat -r -p 45329"  | grep ceph-mon
07:01:50 PM   167     45329     10.63      0.00 1117620 648360   0.25  ceph-mon
[root@bcmt-control-01 ~/rook245]# ssh -q -i ./0207.pem cloud-user@bcmt-control-03 "sudo pidstat -r -p 47131" | grep ceph-mon
07:02:24 PM   167     47131     18.86      0.00 1508912 983248   0.37  ceph-mon 

```
2). Below is another example running in openstack env. Both mon-a and osd-0 has exceptional ( about 50% more ) memory consumption. 
```
# knc top pods | egrep "mon|osd"
rook-ceph-mon-a-7c9648f5df-jrrtt                 7m           911Mi           
rook-ceph-mon-b-696cf6d8c5-mkjm6                 4m           620Mi           
rook-ceph-mon-c-5f95b66c69-kwtxr                 5m           621Mi           
rook-ceph-osd-0-7f6dddb4c7-6kczw                 142m         3982Mi          
rook-ceph-osd-1-64cd9cb4b8-znvx5                 86m          2831Mi          
rook-ceph-osd-2-89cfd8cb8-8q7z4                  109m         2055Mi          
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):  CentOS 7
* Kernel (e.g. `uname -a`): Linux bcmt-control-01 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: BareMetal
* Rook version (use `rook version` inside of a Rook Pod): v1.2.7
* Storage backend version (e.g. for ceph do `ceph -v`): v14.2.8
* Kubernetes version (use `kubectl version`): v1.17.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by yan636** [comment]
Same issue opened with ceph: https://tracker.ceph.com/issues/44939
