### ISSUE TITLE
Ceph: OSDs not deployed: "Used by ceph-disk"

### ISSUE THREAD

**Issue by fr3aker** [rook/rook#5209]
*Bug Report*

**Deviation from expected behavior:**
rook 1.3.0 fails to deploy OSDs for designated partitions with the error `skipping device "sda5": ["Used by ceph-disk"].`

[thread on Slack](https://rook-io.slack.com/archives/CK9CF5H2R/p1586287837229500)

**Expected behavior:**
Device should not be skipped. It is not being used by ceph-disk or anything else. Works with rook 1.2.7 + ceph 14.2.8.

**How to reproduce it (minimal and precise):**
rook was deployed using the example files:
https://github.com/rook/rook/blob/v1.3.0/cluster/examples/kubernetes/ceph/common.yaml
https://github.com/rook/rook/blob/v1.3.0/cluster/examples/kubernetes/ceph/operator.yaml
[cluster.yaml](https://gist.github.com/fr3aker/1a264d7ad28a04fb51f5247614702314)

[osd-prepare.log](https://gist.github.com/fr3aker/3b9f54b4ff3d6d965f12c40e58706b5c)
In this log sda5 and sdb5 should be used. They are referred to by /dev/disk/by-partlabel/ceph-sdx links.

**Environment**:
* OS: Fedora CoreOS 31.20200310.3.0
* Kernel: 5.5.8-200.fc31.x86_64
* hardware configuration: baremetal
* Rook version: 1.3.0
* Ceph version: 14.2.8 and 15.2.0 (both tested)
* Kubernetes version: 1.17.4

**Comment by leseb** [comment]
Do you have a label on that partition that includes keyword 'ceph'? That's the reason why c-v returns `Used by ceph-disk` IIRC.

**Comment by fr3aker** [comment]
Yes, the partition label starts with `ceph-`

**Comment by leseb** [comment]
Please remove it.

**Comment by ibotty** [comment]
I did not find that documented and had to search quiet a bit to find that bug report.  Can this be included in the documentation please?

**Comment by travisn** [comment]
@ibotty Hopefully #5256 will make it more discoverable

**Comment by fr3aker** [comment]
@travisn #5256 doesn't really add much useful information for cases like mine where you've willingly and purposely labeled a partition with something including the word "ceph". That has nothing to do with "cleaning a device".

And I'd like to add that it's quite unexpected to have rook fail because a partition you intend to use for ceph has the word "ceph" in the partition label.

**Comment by travisn** [comment]
Yeah if you created the partition, understood it is unexpected. Rook and Ceph err on the side of skipping volumes if they appear to be in use and sometimes skips when unexpected.
