### ISSUE TITLE
Helm release 1.3.0 not visible in index.yaml

### ISSUE THREAD

**Issue by muhlba91** [rook/rook#5212]
The recent release 1.3.0 is published as a Helm chart in your repository https://charts.rook.io/release properly. However, the `index.yaml` (https://charts.rook.io/release/index.yaml) file does not list `v1.3.0` as an available and latest version.
Therefore, updating or installing 1.3.0 the operator through Helm is not possible.

**Comment by travisn** [comment]
This is a dup of https://github.com/rook/rook/issues/4176, which hopefully was just fixed now.
