### ISSUE TITLE
secret "rook-ceph-crash-collector-keyring" not found

### ISSUE THREAD

**Issue by zxdyumiao** [rook/rook#5213]
ubuntu 19.10
kubernetes 1.16.8
rook v1.2.7

kubernetes apply -f cluster.yaml 
rook-ceph              csi-cephfsplugin-cfjpn                            3/3     Running    0          2m16s
rook-ceph              csi-cephfsplugin-dm98s                            3/3     Running    0          2m15s
rook-ceph              csi-cephfsplugin-provisioner-7b8fbf88b4-gq68w     4/4     Running    0          2m15s
rook-ceph              csi-cephfsplugin-provisioner-7b8fbf88b4-ptfk8     4/4     Running    0          2m15s
rook-ceph              csi-cephfsplugin-prxcv                            3/3     Running    0          2m15s
rook-ceph              csi-rbdplugin-d688h                               3/3     Running    0          2m16s
rook-ceph              csi-rbdplugin-dw5dl                               3/3     Running    0          2m16s
rook-ceph              csi-rbdplugin-k4k7f                               3/3     Running    0          2m16s
rook-ceph              csi-rbdplugin-provisioner-6b8b4d558c-cwq27        5/5     Running    0          2m16s
rook-ceph              csi-rbdplugin-provisioner-6b8b4d558c-fvbqv        5/5     Running    0          2m16s
rook-ceph              rook-ceph-crashcollector-node1-6cc484964c-j49bt   0/1     Init:0/2   0          112s
rook-ceph              rook-ceph-mon-a-55995f776f-ztt8w                  1/1     Running    0          112s
rook-ceph              rook-ceph-operator-b676fc78d-g25np                1/1     Running    0          7m29s
rook-ceph              rook-discover-b6j7h                               1/1     Running    0          7m2s
rook-ceph              rook-discover-n4cll                               1/1     Running    0          7m2s
rook-ceph              rook-discover-wb7vt                               1/1     Running    0          7m2s

no rook-ceph-osd  rook ceph-mgr create 

kubectl describe  pod rook-ceph-crashcollector-node1-6cc484964c-j49bt  -n rook-ceph 

Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    <unknown>            default-scheduler  Successfully assigned rook-ceph/rook-ceph-crashcollector-node1-6cc484964c-j49bt to node1
  Warning  FailedMount  41s                  kubelet, node1     Unable to attach or mount volumes: unmounted volumes=[rook-ceph-crash-collector-keyring], unattached volumes=[rook-config-override rook-ceph-log rook-ceph-crash default-token-b2gq6 rook-ceph-crash-collector-keyring]: timed out waiting for the condition
  Warning  FailedMount  36s (x9 over 2m44s)  kubelet, node1     MountVolume.SetUp failed for volume "rook-ceph-crash-collector-keyring" : secret "rook-ceph-crash-collector-keyring" not found

**Comment by wanghualei** [comment]
maybe clock synchronization,check date on all machine.

**Comment by zxdyumiao** [comment]
It’s about host network.
