### ISSUE TITLE
Cannot create object store buckets after upgrade to 1.2.7

### ISSUE THREAD

**Issue by chrono2002** [rook/rook#5216]
Hello guys!

Recently I have upgraded rook-ceph from 1.1.6 to 1.2.7.
Everything is ok besides new bucket creation in object store I've created long ago. It just fails.

I'm creating a new ObjectBucketClaim and it goes like this:

`2020-04-08T20:10:33.912550280+03:00 stderr F 2020-04-08 17:10:33.912510 I | op-bucket-prov: creating Ceph user "ceph-user-rOhD3xPY`
`2020-04-08T20:10:33.912550280+03:00 stderr F 2020-04-08 17:10:33.912533 I | op-object: Creating user: ceph-user-rOhD3xPY`
`2020-04-08T20:10:33.912599927+03:00 stderr F 2020-04-08 17:10:33.912553 I | exec: Running command: radosgw-admin user create --uid ceph-user-rOhD3xPY --display-name ceph-user-rOhD3xPY --rgw-realm=store-s3 --rgw-zonegroup=store-s3 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring`
`2020-04-08T20:10:34.417025308+03:00 stderr F 2020-04-08 17:10:34.416987 I | op-bucket-prov: successfully created Ceph user "ceph-user-rOhD3xPY" with access keys`
`2020-04-08T20:10:34.417087744+03:00 stderr F 2020-04-08 17:10:34.417078 I | op-bucket-prov: creating bucket "test5-e6facee9-e857-4c8e-8d2d-51b066380b1b"`
`2020-04-08T20:10:34.419384944+03:00 stderr F 2020-04-08 17:10:34.419367 I | op-bucket-prov: DEBUG: after s3 call, ok=true, aerr=InvalidAccessKeyId:`
`2020-04-08T20:10:34.419384944+03:00 stderr F status code: 403, request id: tx0000000000000000000cf-005e8e058a-93cf4e-store, host id:`
`2020-04-08T20:10:34.419430153+03:00 stderr F 2020-04-08 17:10:34.419419 E | op-bucket-prov: error creating bucket "test5-e6facee9-e857-4c8e-8d2d-51b066380b1b": bucket "test5-e6facee9-e857-4c8e-8d2d-51b066380b1b" could not be created: InvalidAccessKeyId:`
`2020-04-08T20:10:34.419430153+03:00 stderr F status code: 403, request id: tx0000000000000000000cf-005e8e058a-93cf4e-store, host id:`
`2020-04-08T20:10:34.419483886+03:00 stderr F E0408 17:10:34.419471 7 controller.go:243] "msg"="cleaning up reconcile artifacts" "error"="error provisioning bucket: error creating bucket \"test5-e6facee9-e857-4c8e-8d2d-51b066380b1b\": bucket \"test5-e6facee9-e857-4c8e-8d2d-51b066380b1b\" could not be created: InvalidAccessKeyId: \n\tstatus code: 403, request id: tx0000000000000000000cf-005e8e058a-93cf4e-store, host id: " "key"="rook-ceph/bucket-test5"`
`2020-04-08T20:10:34.419528336+03:00 stderr F E0408 17:10:34.419508 7 controller.go:163] error syncing 'rook-ceph/bucket-test5': error provisioning bucket: error creating bucket "test5-e6facee9-e857-4c8e-8d2d-51b066380b1b": bucket "test5-e6facee9-e857-4c8e-8d2d-51b066380b1b" could not be created: InvalidAccessKeyId:`
`2020-04-08T20:10:34.419528336+03:00 stderr F status code: 403, request id: tx0000000000000000000cf-005e8e058a-93cf4e-store, host id: , requeuing`

Why there is InvalidAccessKeyId error?

I have checked radosgw-admin on rook-ceph-operator and found that user was created but bucket wasn't. Even tried to create a brand new object store and claim there, it was successful. Looks like something was broken during upgrade.

Could you please advise? Dig into keyrings or something?

**Comment by chrono2002** [comment]
Looks like I've got it.

I have 2 stores.
One store just called "store".
Another one called "store-s3".
So when rgw pods starts for "store-s3" they somehow points to "store" realm:

`debug 2020-04-08 20:20:35.015 7f05d1883780  1 mgrc service_daemon_register rgw.store.s3.b metadata {arch=x86_64,ceph_release=nautilus,ceph_version=ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable),ceph_version_short=14.2.8,container_hostname=rook-ceph-rgw-store-s3-b-7f564d9d6d-phnnw,container_image=ceph/ceph:v14.2.8-20200305,cpu=Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz,distro=centos,distro_description=CentOS Linux 7 (Core),distro_version=7,frontend_config#0=beast port=80,frontend_type#0=beast,hostname=myhost,kernel_description=#1 SMP Debian, kernel_version=4x, mem_swap_kb=0,mem_total_kb=264032188,num_handles=1,os=Linux,pid=1,pod_name=rook-ceph-rgw-store-s3-b-7f564d9d6d-phnnw,pod_namespace=rook-ceph,zone_id=<id_here>,zone_name=store, zonegroup_id=<id of "store" here>,zonegroup_name=store}`

Parsers don't treat dashes correctly in store name?

**Comment by chrono2002** [comment]
Fixed this by editing rgw deployment and adding these params:

        - --rgw-zone=store-s3
        - --rgw-zonegroup=store-s3

Now it starts with correct zone.

**Comment by chrono2002** [comment]
Operator  deletes changes in deployment on daily basis.
Could you please fix this bug with dashes in next release?

**Comment by travisn** [comment]
The rgw-zone and rgw-zonegroup are set in the mon store starting in the 1.2 release as opposed to using the ceph.conf. The settings can be seen [here](https://github.com/rook/rook/blob/release-1.2/pkg/operator/ceph/object/config.go#L124). It appears that the issue is that during upgrade these settings will not be applied [here](https://github.com/rook/rook/blob/release-1.2/pkg/operator/ceph/object/rgw.go#L134) because the deployment still exists. As a workaround, you could delete the rgw deployment and restart the operator to get it to re-create the rgw daemon and then apply the settings. 

Upgrade should also ensure these settings are applied rather than skipping them every time.

**Comment by chrono2002** [comment]
> As a workaround, you could delete the rgw deployment and restart the operator to get it to re-create the rgw daemon and then apply the settings.

didn't work
thanks anyway
decided to recreate storage with name without dashes and migrate there
