### ISSUE TITLE
Possible improvement for the controller finalizer handler

### ISSUE THREAD

**Issue by zerkms** [rook/rook#5238]
**Is this a bug report or feature request?**
* Feature Request

At the moment finalizer handles the request this way:

```go
		err = c.handleDelete(newClust, time.Duration(clusterDeleteRetryInterval)*time.Second)
		if err != nil {
			logger.Errorf("failed finalizer for cluster. %v", err)
			return
		}
```

So it looks that if the cluster object is not updated anymore (unlikely, given it was requested for deletion?) - then if `c.handleDelete` fails - then cluster deletion would stuck forever.

**What should the feature do:**

it should improve the finalizer error handling

**What is use case behind this feature:**

I am actively experimenting with rook (1.3.0) at the moment and during another assessment iteration I have found that I cannot delete a cluster: I have removed all the pools and no pods had ceph volumes mounted. So at first glance everything looked clear. Unfortunately - I was silly enough to reboot nodes (when you don't have better ideas - just chaotically reboot things, yep), so I don't have any logs available.

**Environment**:

**Comment by zerkms** [comment]
I guess, it should be either confirmed or rejected by someone from a team.

**Comment by travisn** [comment]
@zerkms This behavior has actually been changed in master (soon v1.4). Now the check is done [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/controller.go#L284). The purpose of that check is to see if the cluster should be blocked from being removed if a volume still exists. 
```
		// Run delete sequence
		response, ok := r.clusterController.requestClusterDelete(cephCluster)
		if !ok {
			// If the cluster cannot be deleted, requeue the request for deletion to see if the conditions
			// will eventually be satisfied such as the volumes being removed
			close(stopCleanupCh)
			return response, nil
		}
```
Does that work better for you?

**Comment by zerkms** [comment]
@travisn I didn't have a problem initially actually :-) I was just researching code, and asked a question in the chat and you suggested to report it here :-) If you think I should close it now - I'll do for sure, it was more a reminder than a bug report perhaps.

**Comment by travisn** [comment]
Ha, that conversation was too long ago to remember. :) 
The changes we made in master are expected to be much improved, so sounds good to close it for now.
