### ISSUE TITLE
Invalid link in the v1.3.0 release page

### ISSUE THREAD

**Issue by binoue** [rook/rook#5242]
**Is this a bug report or feature request?**
* Bug Report
In [the v1.3.0 release page](https://github.com/rook/rook/releases/tag/v1.3.0), "network configuration doc" is linked to "https://github.com/rook/rook/blob/v1.3.0/Documentation/ceph-cluster-crd.html#network-configuration-settings", but it should be "https://github.com/rook/rook/blob/v1.3.0/Documentation/ceph-cluster-crd.md#network-configuration-settings"

**Deviation from expected behavior:**
Jump to 404 not found page

**Expected behavior:**
Jump to "https://github.com/rook/rook/blob/v1.3.0/Documentation/ceph-cluster-crd.md#network-configuration-settings"

**How to reproduce it (minimal and precise):**

Click 'network configuration doc' in [the v1.3.0 release page](https://github.com/rook/rook/releases/tag/v1.3.0)

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by galexrt** [comment]
Thanks for the info!

Updated v1.3.0 release notes entry.
