### ISSUE TITLE
Rook will not mark any disks as empty in 1.3 (works in 1.2)

### ISSUE THREAD

**Issue by remiphilippe** [rook/rook#5244]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Unable to configure disks in 1.3, disk will always show as Empty: false
```
2020-04-11 00:30:50.396237 I | rook-discover: available devices: [{Name:sdd Parent:. HasChildren:false DevLinks:/dev/disk/by-path/pci-0000:13:00.0-scsi-0:0:2:0 Size:68719476736 UUID:393dec6d-6734-4168-b489-9e18097de0aa Serial: Type:disk Rotational:true Readonly:false Partiti
ons:[] Filesystem: Vendor:VMware Model:Virtual_disk WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/sdd} {Name:sdb Parent:. HasChildren:false DevLinks:/dev/disk/by-path/pci-0000:13:00.0-scsi-0:0:0:0 Size:68719476736 UUID:279f1a85-2195-4d03-9ba3-eb2f4283a80
4 Serial: Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Vendor:VMware Model:Virtual_disk WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/sdb} {Name:sdc Parent:. HasChildren:false DevLinks:/dev/disk/by-path/pci-0000:13:00.0-scsi-0:0:1:0
 Size:68719476736 UUID:39713372-9774-4cd4-a649-922ccda82221 Serial: Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Vendor:VMware Model:Virtual_disk WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/sdc}]
```
Seems like in 1.3 the following field changed:
https://github.com/rook/rook/blob/release-1.3/pkg/clusterd/disk.go#L148 that was introduced in this commit: https://github.com/rook/rook/commit/ab83738aacf844c9727eadee699d41076cf690e7

This causes the Parent to be: `Parent:.` but in the device empty checks for: `device.Parent == ""`
https://github.com/rook/rook/blob/release-1.3/pkg/clusterd/disk.go#L39

So the device is never empty

**Expected behavior:**
Works in release 1.2, Empty is True for the same system:
```
2020-04-11 01:20:14.046335 I | rook-discover: available devices: [{Name:sdd Parent: HasChildren:false DevLinks:/dev/disk/by-path/pci-0000:13:00.0-scsi-0:0:2:0 Size:68719476736 UUID:sgdiskNotFound Serial: Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Vend
or:VMware Model:Virtual_disk WWN: WWNVendorExtension: Empty:true CephVolumeData: Label:} {Name:sdb Parent: HasChildren:false DevLinks:/dev/disk/by-path/pci-0000:13:00.0-scsi-0:0:0:0 Size:68719476736 UUID:sgdiskNotFound Serial: Type:disk Rotational:true Readonly:false Partiti
ons:[] Filesystem: Vendor:VMware Model:Virtual_disk WWN: WWNVendorExtension: Empty:true CephVolumeData: Label:} {Name:sdc Parent: HasChildren:false DevLinks:/dev/disk/by-path/pci-0000:13:00.0-scsi-0:0:1:0 Size:68719476736 UUID:sgdiskNotFound Serial: Type:disk Rotational:true
 Readonly:false Partitions:[] Filesystem: Vendor:VMware Model:Virtual_disk WWN: WWNVendorExtension: Empty:true CephVolumeData: Label:}]
```

**How to reproduce it (minimal and precise):**
initial deployment of kubectl apply -f cluster.yaml

**Comment by etrikp** [comment]
Encountered the same issue when trying 1.3.x. Good catch!

**Comment by dyusupov** [comment]
Hit same issue. And also another EdgeFS user hit similar issue just now...

**Comment by galexrt** [comment]
@remiphilippe Is that with Rook EdgeFS or Rook Ceph?

**Comment by remiphilippe** [comment]
@galexrt I've seen it with EdgeFS, didn't try with Ceph

**Comment by dyusupov** [comment]
@galexrt the code we use in discovery ds is shared between both EdgeFS and Ceph. So, a bit puzzled why we are not seeing it in Ceph. Did we change anything in discovery path in 1.3 that might potentially affect this?

**Comment by travisn** [comment]
@dyusupov This must not be affecting Ceph since creating OSDs not directly consume the results of the discovery daemon.
