### ISSUE TITLE
Upgrade fails when a second crush root with only one OSD exists

### ISSUE THREAD

**Issue by SerialVelocity** [rook/rook#5250]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Upgrade fails with:
```
2020-04-13 22:12:22.844699 I | op-mon: checking if we can stop the deployment rook-ceph-osd-5
2020-04-13 22:12:28.329643 E | op-osd: failed to update osd deployment 5. failed to check if deployment "rook-ceph-osd-5" can be updated. max retries exceeded, last err: exit status 16
deployment rook-ceph-osd-5 cannot be stopped
```

**Expected behavior:**
There to be downtime and the OSD to be restarted

**How to reproduce it (minimal and precise):**

```
[root@chillichef /]# ceph osd tree
ID  CLASS WEIGHT  TYPE NAME                 STATUS REWEIGHT PRI-AFF
-20       0.83569 root distributed-storage1
-28       0.83569     host 172-28-0-2
  5   hdd 0.83569         osd.5                 up  1.00000 1.00000
-19       0.83569 root distributed-storage2
-25       0.83569     host 172-28-0-3
  4   hdd 0.83569         osd.4                 up  1.00000 1.00000
-13       0.83569 root distributed-storage0
-14       0.83569     host 172-28-0-1
  3   hdd 0.83569         osd.3                 up  1.00000 1.00000
 -1       0.02728 root default
 -3       0.00909     host 172-28-1-1
  0   ssd 0.00909         osd.0                 up  1.00000 1.00000
 -5       0.00909     host 172-28-1-2
  1   ssd 0.00909         osd.1                 up  1.00000 1.00000
 -7       0.00909     host 172-28-1-3
  2   ssd 0.00909         osd.2                 up  1.00000 1.00000
```

You probably only need one extra root/osd (and a pool using it?)

**File(s) to submit**:

N/A. Above should be enough. Ask if more is required.

**Environment**:
* OS (e.g. from /etc/os-release):Fedora CoreOS 31.20200223.3.0
* Kernel (e.g. `uname -a`): 5.5.5-200.fc31.x86_64
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): On upgrade from 1.2.6 to 1.3.1
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.8
* Kubernetes version (use `kubectl version`): 1.18.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
HEALTH_WARN 1 daemons have recently crashed
```
Daemon crash is unrelated though and happened a few days before the upgrade.

**Comment by travisn** [comment]
@SerialVelocity There are two settings that will allow the upgrade to proceed with different levels of checking. See the `skipUpgradeChecks` and `continueUpgradeAfterChecksEvenIfNotHealthy ` [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L34-L40). I would expect `skipUpgradeChecks: true` is likely what you want.

**Comment by SerialVelocity** [comment]
Hey @travisn, I used `continueUpgradeAfterChecksEvenIfNotHealthy` to work around this issue for now but I am worried that having that flag set to true would cause the HA root to also upgrade even if it isn't healthy yet.

Shouldn't single replica roots be ignored in `osdDoNothing`?
https://github.com/rook/rook/blob/7caedefb4fd8de950634b1dccdd61e407587b129/pkg/daemon/ceph/client/upgrade.go#L369-L405

**Comment by travisn** [comment]
Rook is basically just querying ceph to know if it is safe to stop an osd, but doesn't analyze where that OSD is in the CRUSH map. @leseb any thoughts on how to handle this?

**Comment by leseb** [comment]
> Rook is basically just querying ceph to know if it is safe to stop an osd, but doesn't analyze where that OSD is in the CRUSH map. @leseb any thoughts on how to handle this?

`ok-to-stop` goes through CRUSH hierarchy so we don't need to, if it does not then a open should be opened on https://tracker.ceph.com/. Thanks!

**Comment by SerialVelocity** [comment]
@leseb `ok-to-stop` doesn't take into account single OSD roots. The `osdDoNothing` method in rook seems to deal with checking for things like that. Should that method check to see whether the OSD belongs to a crush root with less than 3 OSDs rather than there being less than 3 OSDs in general?

**Comment by SerialVelocity** [comment]
(also, as a sidenote that `err` check at the top seems a bit flawed. If there's a network blip you could end up with two OSDs shutdown and some pools going offline)

**Comment by thotz** [comment]
@travisn : I have a minikube setup with three osds and I seeing similar upgrade problem for both rook and ceph images. And both   skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
is this fine as well

**Comment by travisn** [comment]
> @leseb ok-to-stop doesn't take into account single OSD roots. The osdDoNothing method in rook seems to deal with checking for things like that. Should that method check to see whether the OSD belongs to a crush root with less than 3 OSDs rather than there being less than 3 OSDs in general?

Rook doesn't analyze the crush hierarchy. The fix really should be made on the ceph side.

> (also, as a sidenote that err check at the top seems a bit flawed. If there's a network blip you could end up with two OSDs shutdown and some pools going offline)

@leseb Can you take a look at this?

> @travisn : I have a minikube setup with three osds and I seeing similar upgrade problem for both rook and ceph images. And both skipUpgradeChecks: false
> continueUpgradeAfterChecksEvenIfNotHealthy: false
> is this fine as well

@thotz in minikube these checks should automatically be skipped when rook sees that there is only a single node. Are you saying your upgrade is blocked? That's unexpected in your single-node case.

**Comment by SerialVelocity** [comment]
> Rook doesn't analyze the crush hierarchy. The fix really should be made on the ceph side.

I think the ceph side is correct since a single OSD root is never "ok-to-stop". I can see that some people may want single OSD roots to stay up always anyway so Rook may not want to implement it by analysing the crush hierarchy.

Maybe a better solution would be to allow specifying which OSDs or nodes `continueUpgradeAfterChecksEvenIfNotHealthy` should apply to?

**Comment by thotz** [comment]
> > @leseb ok-to-stop doesn't take into account single OSD roots. The osdDoNothing method in rook seems to deal with checking for things like that. Should that method check to see whether the OSD belongs to a crush root with less than 3 OSDs rather than there being less than 3 OSDs in general?
> 
> Rook doesn't analyze the crush hierarchy. The fix really should be made on the ceph side.
> 
> > (also, as a sidenote that err check at the top seems a bit flawed. If there's a network blip you could end up with two OSDs shutdown and some pools going offline)
> 
> @leseb Can you take a look at this?
> 
> > @travisn : I have a minikube setup with three osds and I seeing similar upgrade problem for both rook and ceph images. And both skipUpgradeChecks: false
> > continueUpgradeAfterChecksEvenIfNotHealthy: false
> > is this fine as well
> 
> @thotz in minikube these checks should automatically be skipped when rook sees that there is only a single node. Are you saying your upgrade is blocked? That's unexpected in your single-node case.
Apparently my upgrades as seems to blocked in osds, both ceph and rook versions. I will open up different issue then

**Comment by SerialVelocity** [comment]
Still waiting for a reply

**Comment by SerialVelocity** [comment]
Ping

**Comment by travisn** [comment]
@SerialVelocity Basically, you'd like to skip upgrade checks for certain locations in the CRUSH hierarchy? I could see that working, it's just a matter of implementing. Note there are a couple related configuration issues that would potentially be good to take care of at the same time: #5790 #4380

**Comment by SerialVelocity** [comment]
Yes, one of two things should probably be done:
- Allow restarting single node OSDs
  - This probably is not the best solution as it takes down an OSD temporarily without the user saying it can be taken down whenever
  - But the other way of thinking about it is if they use a single OSD, they expect it to go down sometimes so why not support it automatically
- Allow specifying which locations in the CRUSH hierarchy are fine to stop even if `ok-to-stop` if false.
  - This allows finer grained control over what can be stopped even when the checks fail increasing safety.
  - I don't remember if there are any other checks that get disabled when you set this flag. Really, only the `ok-to-stop` check should be bypassed for this issue.

**Comment by SerialVelocity** [comment]
Looks like it is planned for 1.6?
