### ISSUE TITLE
Simplify cleaning up a failed OSD with a job that can be launched by the admin

### ISSUE THREAD

**Issue by travisn** [rook/rook#5258]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
When the device underlying an OSD fails, the OSD needs to be removed from the cluster. Currently this requires a number of steps with both `ceph` commands in the toolbox and `kubectl` as described in the [OSD management](https://rook.github.io/docs/rook/v1.3/ceph-osd-mgmt.html#remove-an-osd) doc. This is a tedious and non-k8s native process that needs simplification.

Removing an OSD does not follow the pattern of other desired state that the operator typically manages. The operator is expected to manage settings continuously, but in this case we want to perform a one-time operation to remove a failed OSD. Ideas have been considered for options in the cluster CR, but they do **not** make sense after all. For example:
- "remove failed OSDs automatically": This would be far too aggressive at removing OSDs automatically
- "remove OSD with ID 9": After an OSD is removed, Ceph re-uses OSD IDs. So a new OSD may again be immediately created with ID 9 and then be unexpectedly removed again by the operator.

## Proposed Design

A one-time action will be triggered by the administrator by triggering a K8s Job. By design, a Job executes once and then remains in the `completed` state rather than running continuously. The job could also be triggered by the Ceph Dashboard via the rook mgr module.

### Cleanup Job

Here is a skeleton of the job to illustrate the main idea. The job may need mounts and env vars similar to the operator that will allow it to have the needed context to call the K8s API and Ceph commands.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: rook-ceph-osd-remove-<ID>
  namespace: rook-ceph
spec:
  template:
    spec:
      containers:
      - name: remove-osd
        image: rook/ceph:master
        args: ["ceph", "osd", "remove", "<IDs>", "--yes-i-really-mean-it"]
```

### Rook Implementation

The job will launch a command in the same image that is running the operator pod. The `rook` binary in the operator image will support new command line arguments that will perform the operation to remove the OSD with the given ID. This is intentionally a very specific command for a single OSD to ensure that other OSDs are not accidentally removed.

```console
rook ceph osd remove <IDs> --yes-i-really-mean-it
```

Rook has the context necessary to call both K8s API and Ceph commands necessary to fully clean up the OSD.

Internally, Rook will implement the following when the new command is called:
- Check if the OSD is "down". If not "down", abort the cleanup operation in case the incorrect OSD ID was provided.
- Ensure the OSD is marked as "out": `ceph osd out <ID>`
- Purge the OSD: `ceph osd purge <ID> --yes-i-really-mean-it`
- Delete the OSD's K8s deployment 
- Clean any empty hierarchy from the CRUSH map. For example, if the last OSD on a node was removed, remove its node. If the last node was removed, remove its parent zone, etc.
- If the OSD was backed by a PVC, delete the PVC since it is no longer to be used
   - If in a dynamic env (AWS), the PV is expected to be released automatically. If on bare metal with local PVs, the PV may need another step for cleanup. Cleaning up the PV is outside Rook's scope. PV retention is a policy outside Rook's control.
- (optional) After #5257 is implemented, consider also following the same pattern to zap the device that was backing the OSD. We likely do not always want to zap the device. Likely we need another command line arg that indicates when to zap the device.

At this point the OSD has been removed completely from Rook and Ceph. 

## Starting a new OSD

The admin can choose to add a new OSD in its place depending on the settings of the cluster. During the next cluster reconcile loop, the operator will automatically create a new OSD (already implemented) under the following conditions:
- If the OSD was backed by a PVC, a new PVC will be created by the operator to replace the missing PVC and a new OSD will be created on it.
- If on bare metal and the physical device was replaced, the osd-prepare job will discover the clean device and initialize a new OSD.

**Comment by travisn** [comment]
@xenolinux @rajatsingh25aug @jarrpa per our discussions, please review

**Comment by jarrpa** [comment]
So rather than a standalone script or binary, just implement it in the rook-ceph operator... I like it! Certainly looks cleaner and makes feature delivery a no-brainer.

**Comment by BlaineEXE** [comment]
How are we handling the case where the rook operator might be doing OSD operations simultaneously to this imperative operation? Will this operation wait until OSD reconciliation is done in the main operator, and will the main operator wait if there is an osd rm op ongoing?

**Comment by rajatsingh25aug** [comment]
Also, how are we going to clean the PV and PVC of the removed OSDs?. Do we also need to write a job for that?.

**Comment by travisn** [comment]
> How are we handling the case where the rook operator might be doing OSD operations simultaneously to this imperative operation? Will this operation wait until OSD reconciliation is done in the main operator, and will the main operator wait if there is an osd rm op ongoing?

Synchronizing with the operator would indeed be complex. If at all possible I'd like to avoid the need to block OSD orchestration while this job is running. This seems possible by:
- If the OSD was on a PVC, the operator will skip reconcile of the OSD as long as the PVC still exists. So if the job removes the PVC as the last step there wouldn't be any conflict.
- If the OSD was on a failed device and if the operator creates the deployment again for the bad OSD after the job has purged the OSD, the OSD will simply fail to start. If the job wipes the device as part of the job and the operator reconciles after that, then you'll get a clean, working OSD as expected. So I believe if the job cleans the device as the last step of the OSD removal, everything will be fine. You would just have to trigger a new orchestration to re-provision the OSD again.
- In some scenarios as a last resort, we could document or even automate scaling down the operator so it isn't even running during the osd removal. But I hope we don't need this either.

**Comment by BlaineEXE** [comment]
Those sound reasonable, but I am concerned about what we might be missing in our analysis. But I think it makes sense to proceed with this general design for now, and if there are things we miss, we will eventually find them.

Something I wonder about is actual failed devices. We only have good devices to test with, and I think we tend to think about things in terms of good disks that we want to remove rather than actual failed disks. As such, zapping the device seems to make sense to us, but devices can fail in a lot of ways. They might not be able to be zapped if it fails in a way where it is read-only somehow. I would think that in the best case the device fails and no longer shows up to the OS, and zapping is not necessary. This note is a little bit tangential to the feature work, however; just something I wonder about.

**Comment by travisn** [comment]
> Something I wonder about is actual failed devices. We only have good devices to test with, and I think we tend to think about things in terms of good disks that we want to remove rather than actual failed disks. As such, zapping the device seems to make sense to us, but devices can fail in a lot of ways. They might not be able to be zapped if it fails in a way where it is read-only somehow. I would think that in the best case the device fails and no longer shows up to the OS, and zapping is not necessary. This note is a little bit tangential to the feature work, however; just something I wonder about.

Agreed, we should keep this in mind. As long as the zapping is a separate argument, at least the admin could decide if they want rook to attempt it.

**Comment by travisn** [comment]
The OSD purge job was added in v1.4 with #6127.
