### ISSUE TITLE
After Upgrade from 1.2.7 to 1.3.1 RGW with ssl are not working

### ISSUE THREAD

**Issue by deveshk0** [rook/rook#5265]
**Is this a bug report or feature request?**
* Bug Report

**After the rgw are not starting with ssl**

**After the upgrade rgw should work as it working before**

**How to reproduce it (minimal and precise):**
Have a cluster running with 1.2.7 rook and upgrade to 1.3.1 with ceph v15.2.0 
rgw with ssl starts to fail

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
```log
20-04-15T19:44:52.944+0000 7f6d11832240  0 set uid:gid to 167:167 (ceph:ceph)
debug 2020-04-15T19:44:52.944+0000 7f6d11832240  0 ceph version 15.2.0 (dc6a0b5c3cbf6a5e1d6d4f20b5ad466d76b96247) octopus (rc), process radosgw, pid 1
debug 2020-04-15T19:44:52.944+0000 7f6d11832240  0 framework: beast
debug 2020-04-15T19:44:52.944+0000 7f6d11832240  0 framework conf key: port, val: 8085
debug 2020-04-15T19:44:52.944+0000 7f6d11832240  0 framework conf key: ssl_port, val: 8843
debug 2020-04-15T19:44:52.944+0000 7f6d11832240  0 framework conf key: ssl_certificate, val: /etc/ceph/private/rgw-cert.pem
debug 2020-04-15T19:44:52.944+0000 7f6d11832240  1 radosgw_Main not setting numa affinity
debug 2020-04-15T19:45:03.272+0000 7f6d11832240  1 robust_notify: If at first you don't succeed: (110) Connection timed out
debug 2020-04-15T19:45:03.272+0000 7f6d11832240  0 ERROR: failed to distribute cache for widas-store.rgw.log:meta.history
debug 2020-04-15T19:45:03.547+0000 7f6d11832240  0 framework: beast
debug 2020-04-15T19:45:03.547+0000 7f6d11832240  0 framework conf key: ssl_certificate, val: config://rgw/cert/$realm/$zone.crt
debug 2020-04-15T19:45:03.547+0000 7f6d11832240  0 framework conf key: ssl_private_key, val: config://rgw/cert/$realm/$zone.key
debug 2020-04-15T19:45:03.547+0000 7f6d11832240  0 starting handler: beast
debug 2020-04-15T19:45:03.549+0000 7f6d11832240 -1 ssl_private_key was not found: rgw/cert/widas-store/widas-store.key
debug 2020-04-15T19:45:03.549+0000 7f6d11832240 -1 failed to use ssl_certificate=/etc/ceph/private/rgw-cert.pem as a private key: Permission denied
debug 2020-04-15T19:45:03.549+0000 7f6d11832240 -1 no ssl_certificate configured for ssl_port
debug 2020-04-15T19:45:03.550+0000 7f6d11832240 -1 ERROR: failed initializing frontend
terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_get>'
  what():  boost::bad_get: failed value get using boost::get
```

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

Cluster is in healthy state.

**Comment by travisn** [comment]
@thotz Can you look into this issue?

**Comment by obeyler** [comment]
@thotz @travisn @deveshk0 the dashboard doest work either with tls or without tls
It seem's that it not a service trouble because when I log inside the pod and just test it by a curl https://localhost:8443/ or without tls curl http://localhost/ the connection is refused

```
sh-4.2# curl https://localhost:8443
curl: (7) Failed connect to localhost:8443; Connection refused
```

**Comment by deveshk0** [comment]
@obeyler dashboard is working fine for me with ingress

**Comment by deveshk0** [comment]
@travisn @thotz is there any way I can revert to older version? Since this is still pending

**Comment by obeyler** [comment]
> 
> 
> @obeyler dashboard is working fine for me with ingress

@deveshk0 could you do a ps -ef inside your container to be able to compare why in my case the connection is refused ?

**Comment by thotz** [comment]
> @travisn @thotz is there any way I can revert to older version? Since this is still pending

I have never enabled ssl in rgw and let check whether it is happening in my setup. But from the looks like the ssl certificate got missing post upgrade, may be post upgrade new pod was not able to access the file

**Comment by deveshk0** [comment]
@thotz have you got some time to look into this?

**Comment by thotz** [comment]
> @thotz have you got some time to look into this?
Can please tell me how you have enabled ssl(steps) for the object cluster. I was not able to find any where documented. Did u use CRDs options or configured via toolbox?

**Comment by deveshk0** [comment]
So for SSL you need to create a cert with following yml - 
```yml
kind: Secret
apiVersion: v1
metadata:
  name: s3-cert
  namespace: rook-ceph
data:
  cert: >-
    cert(base64)
type: Opaque

```

Note- cert should all things like root ca intermediate  ca and actual cert .

and then enable secure port - 
```yml
gateway:
    # type of the gateway (s3)
    type: s3
    # A reference to the secret in the rook namespace where the ssl certificate is stored
    sslCertificateRef: s3-cert
    # The port that RGW pods will listen on (http)
    port: 80
    # The port that RGW pods will listen on (https). An ssl certificate is required.
    securePort: 9443
    # The number of pods in the rgw deployment
    instances: 1
    # The affinity rules to apply to the rgw deployment or daemonset.
    placement:
```

**Comment by thotz** [comment]
> So for SSL you need to create a cert with following yml -
> 
> ```yaml
> kind: Secret
> apiVersion: v1
> metadata:
>   name: s3-cert
>   namespace: rook-ceph
> data:
>   cert: >-
>     cert(base64)
> type: Opaque
> ```
> 
> Note- cert should all things like root ca intermediate ca and actual cert .
> 
> and then enable secure port -
> 
> ```yaml
> gateway:
>     # type of the gateway (s3)
>     type: s3
>     # A reference to the secret in the rook namespace where the ssl certificate is stored
>     sslCertificateRef: s3-cert
>     # The port that RGW pods will listen on (http)
>     port: 80
>     # The port that RGW pods will listen on (https). An ssl certificate is required.
>     securePort: 9443
>     # The number of pods in the rgw deployment
>     instances: 1
>     # The affinity rules to apply to the rgw deployment or daemonset.
>     placement:
> ```
> 
> @thotz let me know if you need anything else

for me rgw pod was not coming up at (without ssl it was)



```bash
# kubectl describe secret/my-tls-cert -n rook-ceph
Name:         my-tls-cert
Namespace:    rook-ceph
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  1415 bytes
tls.key:  1704 bytes
[root@localhost rook]# kubectl describe secret/s3-cert -n rook-ceph
Name:         s3-cert
Namespace:    rook-ceph
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
ceph-rgw-cert.key:  1704 bytes
ceph-rgw.crt:       1415 bytes
[root@localhost rook]# kubectl get pods -n rook-ceph
NAME                                                              READY   STATUS      RESTARTS   AGE
rook-ceph-crashcollector-localhost.localdomain-69ffcf5696-l27lh   1/1     Running     0          36m
rook-ceph-mgr-a-7cff7c6b79-56c9r                                  1/1     Running     0          148m
rook-ceph-mon-a-68c6547758-44txk                                  1/1     Running     0          148m
rook-ceph-operator-b67659694-lftqp                                1/1     Running     0          152m
rook-ceph-osd-0-5bd4cf7b46-6sdlt                                  1/1     Running     0          148m
rook-ceph-osd-prepare-localhost.localdomain-xk8xj                 0/1     Completed   0          148m
rook-ceph-rgw-my-store-a-86c6d9478-8c5w9                          0/1     Init:0/1    0          36m
```
I have used following command to create cert secret
kubectl create secret generic s3-cert --from-file=<path> since I was not able to create with yaml

**Comment by deveshk0** [comment]
@thotz Can you paste the logs?

**Comment by thotz** [comment]
> @thotz Can you paste the logs? and one more thing kubernetes secret with Type: kubernetes.io/tls is not supported.
> You need to create a bundle cert from all the cert and then from that file create a type: Opaque cert.
@deveshk0 
There was no logs from rgw pod. The operator pod last log message was object was created.

Created cert and key using openssl command. And given that path while creating secret and it was not tls. Am I missing something?

**Comment by thotz** [comment]
@deveshk0 

I was able to setup ssl configured object store in rook. The name of certificate file(or the bundles) need to "cert" while creating the secret , then that will look like ur secret.

I have used minikube to set up rook cluster. Created cluster with rook version 1.2.7 and ceph version 14.2.7. Then upgraded to rook version 1.3.1. Didn't face any issues. It came up properly
can give kubectl describe for the rgw pod and also try to enter into the pod and see whether /etc/ceph/private/rgw-cert.pem is present or not.

I faced issue while upgrading to ceph version, my whole cluster messed up. I will give another try including ceph upgrade

I am still guessing issue may not to be related with rgw.

BTW did u try to create new object store in upgrade set up?

**Comment by deveshk0** [comment]
> BTW did u try to create new object store in upgrade set up?

No not yet I will try that today.

**Comment by thotz** [comment]
@deveshk0 : I checked colleagues in rgw team, apparently in ceph octopus the "/etc/ceph/private/rgw-cert.pem" need to accessible by user named "ceph", will confirm whether ssl broken entirely ceph v15 and let u know

**Comment by deveshk0** [comment]
Thank you so much @thotz  Please Let me if you find any quick fix

**Comment by thotz** [comment]
@deveshk0 I have proposed a fix. The fix is add 167 as FsGroup in pod configuration, so that cert file will be accessible for the "ceph" user and permission denied can be resolved
