### ISSUE TITLE
Podantiaffinity for `csi-rbdplugin-provisioner`

### ISSUE THREAD

**Issue by zerkms** [rook/rook#5271]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

In my current cluster there is a `csi-rbdplugin-provisioner` deployment with 2 replicas. Both run on the same node.

I believe it would be better if it had `podAntiAffinity`, so that they at least were placed on different nodes (if > than 1 available).

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
@Madhu-1 the provisioners don't have anti-affinity?

**Comment by Madhu-1** [comment]
> @Madhu-1 the provisioners don't have anti-affinity?

@travisn we have only node affinity and toleration for CSI pods.
