### ISSUE TITLE
Support quota management for Ceph Object Gateway

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#5274]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
1. Support quota settings on users and buckets owned by users. ( CephObjectStoreUser)
Please refer https://docs.ceph.com/docs/master/radosgw/admin/#quota-management
```
 Below "bucket_quota" and "user_quota" can be part of user CR. Haven't used subuser.
{ "user_id": "johndoe",
"display_name": "John Doe",
"email": "john@example.com",
"suspended": 0,
"max_buckets": 1000,
"subusers": [],
"keys": [
{ "user": "johndoe",
"access_key": "11BS02LGFB6AL6H1ADMW",
"secret_key": "vzCEkuryfn060dfee4fgQPqFrncKEIkh3ZcdOANY"}],
"swift_keys": [],
"caps": [],
"op_mask": "read, write, delete",
"default_placement": "",
"placement_tags": [],
"bucket_quota": { "enabled": false,
"max_size_kb": -1,
"max_objects": -1},
"user_quota": { "enabled": false,
"max_size_kb": -1,
"max_objects": -1},
"temp_url_keys": []}
```
2. Support global quota settings. ( CephObjectStore)

**What is use case behind this feature:**
Co-ordinate the storage usage effectively.

**Environment**:

N/A

**Comment by thotz** [comment]
@yanchicago I can work on a design for quota wrt OBC not specific user though. Not sure whether it is help for ur usecase. So it will be bucket quota than user specific

**Comment by jeffvance** [comment]
In Kubernetes, storage quotas are managed by `ResourceQuota` and `LimitRange` resources. [Quota/counts](https://github.com/kubernetes/kubernetes/pull/72384)  are also supported for custom resources. For quotas unique to buckets is it possible to define this via the StorageClass `parameters` and the OBC `additionalConfig` fields?

**Comment by yanchicago** [comment]
[ceph:adding support for quota in object bucket claims(#5674 ](https://github.com/rook/rook/pull/5674#discussion_r450770488)
