### ISSUE TITLE
Deploying rook-ceph operator fails with runAsNonRoot

### ISSUE THREAD

**Issue by jhesketh** [rook/rook#5293]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After applying the `operator.yaml` manifest the rook-ceph-operator pod fails with:

`Error: container has runAsNonRoot and image will run as root`

**Expected behavior:**

The operator applies correctly and the pods start in running state.

**How to reproduce it (minimal and precise):**

1. On vanilla 3-node kuberenetes deployment
2. `cd cluster/examples/kubernetes/ceph`
3. `kubectl apply -f common.yaml`
4. `kubectl apply -f operator.yaml`
5. Observe failure

(As a note, deploying from v1.3.1 tag works fine).

**File(s) to submit**:

`kubectl describe pod/rook-ceph-operator-ff4fc4d9b-cbtqj`

```
Name:         rook-ceph-operator-ff4fc4d9b-cbtqj
Namespace:    rook-ceph
Priority:     0
Node:         josh-rookci-e1853ce3-worker-0/10.86.4.167
Start Time:   Mon, 20 Apr 2020 21:34:53 +1000
Labels:       app=rook-ceph-operator
              pod-template-hash=ff4fc4d9b
Annotations:  container.apparmor.security.beta.kubernetes.io/rook-ceph-operator: runtime/default
              kubernetes.io/psp: default
              seccomp.security.alpha.kubernetes.io/pod: docker/default
Status:       Pending
IP:           10.244.2.3
IPs:
  IP:           10.244.2.3
Controlled By:  ReplicaSet/rook-ceph-operator-ff4fc4d9b
Containers:
  rook-ceph-operator:
    Container ID:  
    Image:         rook/ceph:master
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      ceph
      operator
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Environment:
      ROOK_CURRENT_NAMESPACE_ONLY:               false
      ROOK_ALLOW_MULTIPLE_FILESYSTEMS:           false
      ROOK_LOG_LEVEL:                            INFO
      ROOK_CEPH_STATUS_CHECK_INTERVAL:           60s
      ROOK_MON_HEALTHCHECK_INTERVAL:             45s
      ROOK_MON_OUT_TIMEOUT:                      600s
      ROOK_DISCOVER_DEVICES_INTERVAL:            60m
      ROOK_HOSTPATH_REQUIRES_PRIVILEGED:         false
      ROOK_ENABLE_SELINUX_RELABELING:            true
      ROOK_ENABLE_FSGROUP:                       true
      ROOK_DISABLE_DEVICE_HOTPLUG:               false
      DISCOVER_DAEMON_UDEV_BLACKLIST:            (?i)dm-[0-9]+,(?i)rbd[0-9]+,(?i)nbd[0-9]+
      ROOK_ENABLE_FLEX_DRIVER:                   false
      ROOK_ENABLE_DISCOVERY_DAEMON:              true
      ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS:  5
      NODE_NAME:                                  (v1:spec.nodeName)
      POD_NAME:                                  rook-ceph-operator-ff4fc4d9b-cbtqj (v1:metadata.name)
      POD_NAMESPACE:                             rook-ceph (v1:metadata.namespace)
    Mounts:
      /etc/ceph from default-config-dir (rw)
      /var/lib/rook from rook-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-system-token-ltsv5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  rook-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-config-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  rook-ceph-system-token-ltsv5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-system-token-ltsv5
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age               From                                    Message
  ----     ------     ----              ----                                    -------
  Normal   Scheduled  34s               default-scheduler                       Successfully assigned rook-ceph/rook-ceph-operator-ff4fc4d9b-cbtqj to josh-rookci-e1853ce3-worker-0
  Normal   Pulled     6s (x4 over 33s)  kubelet, josh-rookci-e1853ce3-worker-0  Container image "rook/ceph:master" already present on machine
  Warning  Failed     6s (x4 over 33s)  kubelet, josh-rookci-e1853ce3-worker-0  Error: container has runAsNonRoot and image will run as root
```

**Environment**:
* `openSUSE Leap 15.1`
* `Linux josh-rookci-2e875dac-master-0 4.12.14-lp151.28.44-default #1 SMP Fri Mar 20 18:20:20 UTC 2020 (dbf1aea) x86_64 x86_64 x86_64 GNU/Linux`
* Private OpenStack cloud
* Rook version: `master` branch and master tags. Fails with both public container images and locally built ones.
* `Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type: Upstream `kubeadm` deployment

**Comment by travisn** [comment]
@jhesketh Are you saying this issue only happens with `rook/ceph:master`? But the `rook/ceph:v1.3.1` release works fine? I'm not sure what the difference would be in master. Did you change anything in the example operator.yaml?

**Comment by jhesketh** [comment]
> @jhesketh Are you saying this issue only happens with `rook/ceph:master`? But the `rook/ceph:v1.3.1` release works fine?

Yes, that's correct.

> I'm not sure what the difference would be in master. Did you change anything in the example operator.yaml?

No, I haven't changed anything in there. I just clone this repo straight from master and it fails to install (unless I check out the v1.3.1 tag).

I'm also unsure what it might be looking at the diff. I guess the question is whether others can reproduce or if this is something to do with my environment.

**Comment by HubertBos** [comment]
Same problem 

Debian 10 with k8s from kubspray 1.16 and Rook 1.3.1 

`
╰─$ kubectl -n rook-ceph get pods                                        
NAME                                  READY   STATUS                       RESTARTS   AGE
rook-ceph-operatorXXXXX   0/1     CreateContainerConfigError   0          7m53s
`

and 

`
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  <unknown>             default-scheduler  Successfully assigned rook-ceph/rook-ceph-operator-599765ff49-q2gcl to node6
  Normal   Pulling    3m44s                 kubelet, nodeX     Pulling image "rook/ceph:v1.3.1"
  Normal   Pulled     3m16s                 kubelet, nodeX     Successfully pulled image "rook/ceph:v1.3.1"
  Warning  Failed     68s (x12 over 3m16s)  kubelet, nodeX     Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     68s (x11 over 3m15s)  kubelet, nodeX     Container image "rook/ceph:v1.3.1" already present on machine

`

**Comment by HubertBos** [comment]
I'm sorry this was my bad 

I was on branch 1.3, my bad, strong appologies.

**Comment by jhesketh** [comment]
That's interesting that you're seeing similar errors though. Are you able to reproduce this reliably? Have you tried against master?

**Comment by HubertBos** [comment]
On master when I use tag 1.3.1 I have working operator now ( but still waiting for cluster to start ? ) but when I was on branch 1.3 I had an error about running as root user

**Comment by HubertBos** [comment]
However, if I check out to master I have again issue with running container as root 

`
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  <unknown>          default-scheduler  Successfully assigned rook-ceph/rook-ceph-operator-67959c6f49-qkrwh to node4
  Normal   Pulling    41s                kubelet, node4     Pulling image "rook/ceph:master"
  Normal   Pulled     37s                kubelet, node4     Successfully pulled image "rook/ceph:master"
  Warning  Failed     11s (x4 over 37s)  kubelet, node4     Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     11s (x3 over 36s)  kubelet, node4     Container image "rook/ceph:master" already present on machine

`

**Comment by jhesketh** [comment]
Great, thanks for that. Looks like the same issue that I've observed.

**Comment by HubertBos** [comment]
So looks like 1.3.1 works only on master branch when checkout to tag v1.3.1 however till now operator do not apply my cluster :-(

**Comment by HubertBos** [comment]
So after waiting whole night rook operator do not created ceph cluster. 

Rook 1.3.1 from master tag on k8s 1.16.8 from kubespray with podsecurity

**Comment by travisn** [comment]
@HubertBos Can you share the operator log? 
However, I'm confused when you say you have installed Rook 1.3.1 from the master tag. What do you mean? If you have checked out the release-1.3 branch, you would be installing v1.3.1. Or perhaps checkout the v1.3.1 tag instead of just the tip of release-1.3.

**Comment by HubertBos** [comment]
ok, so there is a problem with branch release-1.3 and master when you deploy operator from example YAML file you will have "Error: the container has runAsNonRoot and image will run as root" like the whole issue is about. To do not have this problem I did git checkout v1.3.1 and deploy operator there was a success. However, after applying cluster YAML nothing is happening.

Logs from operator pod:

```
╰─$ kubectl logs -n rook-ceph rook-ceph-operator-599765ff49-hz2mh
2020-04-23 02:04:19.685577 I | rookcmd: starting Rook v1.3.1 with arguments '/usr/local/bin/rook ceph operator'
2020-04-23 02:04:19.685639 I | rookcmd: flag values: --add_dir_header=false, --alsologtostderr=false, --csi-cephfs-plugin-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin.yaml, --csi-cephfs-provisioner-dep-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner-dep.yaml, --csi-cephfs-provisioner-sts-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner-sts.yaml, --csi-rbd-plugin-template-path=/etc/ceph-csi/rbd/csi-rbdplugin.yaml, --csi-rbd-provisioner-dep-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner-dep.yaml, --csi-rbd-provisioner-sts-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner-sts.yaml, --enable-discovery-daemon=true, --enable-flex-driver=false, --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-flush-frequency=5s, --log-level=INFO, --log_backtrace_at=:0, --log_dir=, --log_file=, --log_file_max_size=1800, --logtostderr=true, --master=, --mon-healthcheck-interval=45s, --mon-out-timeout=10m0s, --operator-image=, --service-account=, --skip_headers=false, --skip_log_headers=false, --stderrthreshold=2, --v=0, --vmodule=
2020-04-23 02:04:19.685643 I | cephcmd: starting operator
2020-04-23 02:04:19.723948 I | op-discover: rook-discover daemonset already exists, updating ...
2020-04-23 02:04:19.736062 I | operator: rook-provisioner ceph.rook.io/block started using ceph.rook.io flex vendor dir
I0423 02:04:19.736167       7 leaderelection.go:242] attempting to acquire leader lease  rook-ceph/ceph.rook.io-block...
2020-04-23 02:04:19.736250 I | operator: rook-provisioner rook.io/block started using rook.io flex vendor dir
2020-04-23 02:04:19.736262 I | operator: Watching all namespaces for cluster CRDs
2020-04-23 02:04:19.736268 I | op-cluster: start watching clusters in all namespaces
2020-04-23 02:04:19.736289 I | op-cluster: Enabling hotplug orchestration: ROOK_DISABLE_DEVICE_HOTPLUG=false
2020-04-23 02:04:19.736316 I | operator: setting up the controller-runtime manager
I0423 02:04:19.736375       7 leaderelection.go:242] attempting to acquire leader lease  rook-ceph/rook.io-block...
2020-04-23 02:04:19.740945 I | op-cluster: ConfigMap "rook-ceph-operator-config" changes detected. Updating configurations
2020-04-23 02:04:19.741150 I | op-cluster: skipping orchestration for cluster object "rook-ceph" in namespace "rook-ceph" because its cleanup policy is set
2020-04-23 02:04:20.189734 I | operator: starting the controller-runtime manager
I0423 02:04:35.747361       7 leaderelection.go:252] successfully acquired lease rook-ceph/ceph.rook.io-block
I0423 02:04:35.747453       7 controller.go:780] Starting provisioner controller ceph.rook.io/block_rook-ceph-operator-599765ff49-hz2mh_de25243d-40cb-44ae-9cf2-dcd3209f2256!
I0423 02:04:35.747499       7 event.go:281] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"rook-ceph", Name:"ceph.rook.io-block", UID:"58911f15-a218-4544-a47d-1d21bd7aecf7", APIVersion:"v1", ResourceVersion:"23094", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-599765ff49-hz2mh_de25243d-40cb-44ae-9cf2-dcd3209f2256 became leader
I0423 02:04:35.836433       7 leaderelection.go:252] successfully acquired lease rook-ceph/rook.io-block
I0423 02:04:35.836524       7 controller.go:780] Starting provisioner controller rook.io/block_rook-ceph-operator-599765ff49-hz2mh_54e12c59-a0a2-4827-9b2c-e2c4cebb0f9b!
I0423 02:04:35.836540       7 event.go:281] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"rook-ceph", Name:"rook.io-block", UID:"d66e60d9-7ff3-4362-8b93-c5eb8f86db08", APIVersion:"v1", ResourceVersion:"23096", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-599765ff49-hz2mh_54e12c59-a0a2-4827-9b2c-e2c4cebb0f9b became leader
I0423 02:04:35.847586       7 controller.go:829] Started provisioner controller ceph.rook.io/block_rook-ceph-operator-599765ff49-hz2mh_de25243d-40cb-44ae-9cf2-dcd3209f2256!
I0423 02:04:36.436659       7 controller.go:829] Started provisioner controller rook.io/block_rook-ceph-operator-599765ff49-hz2mh_54e12c59-a0a2-4827-9b2c-e2c4cebb0f9b!
```

**Comment by Madhu-1** [comment]
Isn't something related to psp?

**Comment by HubertBos** [comment]
This is my second cluster and without psp rook was working fine, with psp there are problems. Right now I can't find anything wrong by myself so I'm asking/reporting problem here.

**Comment by travisn** [comment]
@jhesketh Are you also using PSP? That could explain the difference rather than it being a difference between master and v1.3.1.

**Comment by BlaineEXE** [comment]
I'm seeing the same thing today starting with the manifests in master. Working on tracking this down.

**Comment by BlaineEXE** [comment]
@jhesketh I think I have figured out how to fix the issue. Can you verify that if you rename both instances of `rook-privileged` to `00-rook-privileged` the install succeeds?

**Comment by HubertBos** [comment]
@BlaineEXE on master, master with tag, branch, release-1.3?

**Comment by HubertBos** [comment]
I can confirm that if I checkout to release-1.3 and change the operator pod is running.

**Comment by HubertBos** [comment]
Good job to find this, if you will tell me why after applying cluster YAML noting happening I promise I will come back and update your docs page :-)

**Comment by HubertBos** [comment]
Ok, I have found what stop cluster to start: 

in common from line 1261 to 1267 there is comment out option for:  allowedHostPaths 

After changing this back operator start spinning rest of containers.

Thank all of you and case closed.

**Comment by jhesketh** [comment]
> @jhesketh Are you also using PSP? That could explain the difference rather than it being a difference between master and v1.3.1.

Yes, I am using PSP.

> @jhesketh and @HubertBos I think I have figured out how to fix the issue. Can you verify that if you rename both instances of `rook-privileged` to `00-rook-privileged` in `common.yaml` the install succeeds?

Yep, performing that rename allows the deployment to work.

**Comment by HubertBos** [comment]
Hello 

Apologies but problem do not look like is 100% resolved, I sumped on other error what in 99% is related. 

It started here https://github.com/rook/rook/issues/5329 with another issue however after hours of digging I have errors osd pods :+1: 

```
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       <unknown>              default-scheduler  Successfully assigned rook-ceph/rook-ceph-osd-1-69b84c8c6f-p8vjn to node4
  Normal   Pulled          5m47s (x4 over 6m36s)  kubelet, node4     Container image "ceph/ceph:v15.2.1" already present on machine
  Normal   Created         5m47s (x4 over 6m36s)  kubelet, node4     Created container activate
  Normal   Started         5m46s (x4 over 6m36s)  kubelet, node4     Started container activate
  Warning  BackOff         5m7s (x8 over 6m34s)   kubelet, node4     Back-off restarting failed container
  Warning  FailedMount     3m11s (x2 over 3m12s)  kubelet, node4     MountVolume.SetUp failed for volume "rook-config-override" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount     3m11s (x2 over 3m12s)  kubelet, node4     MountVolume.SetUp failed for volume "rook-ceph-osd-token-nz8x6" : failed to sync secret cache: timed out waiting for the condition
  Normal   SandboxChanged  3m9s                   kubelet, node4     Pod sandbox changed, it will be killed and re-created.
  Warning  BackOff         108s (x8 over 3m7s)    kubelet, node4     Back-off restarting failed container
  Normal   Pulled          96s (x4 over 3m9s)     kubelet, node4     Container image "ceph/ceph:v15.2.1" already present on machine
  Normal   Created         95s (x4 over 3m9s)     kubelet, node4     Created container activate
  Normal   Started         95s (x4 over 3m8s)     kubelet, node4     Started container activate

```

The most important part is "MountVolume.SetUp failed for volume "rook-ceph-osd-token-nz8x6" : failed to sync secret cache: timed out waiting for the condition"  

And going under this rabbit hole I have found this error https://github.com/kubernetes-sigs/external-dns/issues/961 what suggest there is still a problem with RBAC role bindings.

**Comment by HubertBos** [comment]
And quick TL;DR 

Node after restart MON is coming back to quorum however OSDs hang on crash loops. 

3 node cluster with 6 OSDs, 3 mon, ceph 15.2, rook 1.3.2 with hot fix, k8s 1.16.8 from kubespraay, AWS i3en instances.

**Comment by travisn** [comment]
> And quick TL;DR
> 
> Node after restart MON is coming back to quorum however OSDs hang on crash loops and this is NOT a problem without PSP

@HubertBos Do you have lvm2 installed on the hosts? If not, the OSDs can't restart when the node restarts. See the [prerequisites topic](https://rook.github.io/docs/rook/v1.3/ceph-prerequisites.html#lvm-package).

**Comment by HubertBos** [comment]
@travisn Thank you for the question. 

Yes, my playbook is taking care of this but to be sure if that is a case I run the same scenario with and without lvm2.  

I have the same behave  

```
╰─$ kubectl get pods -n rook-ceph           
NAME                                              READY   STATUS                  RESTARTS   AGE
csi-cephfsplugin-9jw6v                            3/3     Running                 0          30m
csi-cephfsplugin-k9422                            3/3     Running                 3          30m
csi-cephfsplugin-provisioner-77cd85b75b-kwpst     5/5     Running                 0          30m
csi-cephfsplugin-provisioner-77cd85b75b-x6qp8     5/5     Running                 0          30m
csi-cephfsplugin-qprzp                            3/3     Running                 0          30m
csi-rbdplugin-24rgk                               3/3     Running                 0          30m
csi-rbdplugin-45x9s                               3/3     Running                 0          30m
csi-rbdplugin-provisioner-545d7f76b8-ht79h        6/6     Running                 0          30m
csi-rbdplugin-provisioner-545d7f76b8-ql24c        6/6     Running                 0          19m
csi-rbdplugin-q6wtn                               3/3     Running                 3          30m
rook-ceph-crashcollector-node4-c6489d58b-x84f5    1/1     Running                 0          19m
rook-ceph-crashcollector-node5-556cbf6c59-lm6p8   1/1     Running                 0          28m
rook-ceph-crashcollector-node6-6688d5c5d4-w4ml7   1/1     Running                 0          28m
rook-ceph-mgr-a-7777b57578-p78pj                  1/1     Running                 0          28m
rook-ceph-mon-a-6bcd6b656d-7kt8c                  1/1     Running                 0          19m
rook-ceph-mon-b-74cd899bb6-gh6fd                  1/1     Running                 0          29m
rook-ceph-mon-c-6776f495b9-bzvj8                  1/1     Running                 0          28m
rook-ceph-operator-5f9b44f9cb-cp8b4               1/1     Running                 0          32m
rook-ceph-osd-0-6dbb777fbd-qzkmh                  0/1     Init:CrashLoopBackOff   6          19m
rook-ceph-osd-1-584d4f4856-k4zbj                  1/1     Running                 0          28m
rook-ceph-osd-2-6886485bc4-jlfbc                  1/1     Running                 0          28m
rook-ceph-osd-3-dbbf98774-xscpv                   1/1     Running                 0          28m
rook-ceph-osd-4-84b6b45b46-gg4fp                  1/1     Running                 0          28m
rook-ceph-osd-5-859cfc6d58-tzz2p                  0/1     Init:CrashLoopBackOff   6          19m
rook-ceph-osd-prepare-node5-wm822                 0/1     Completed               0          28m
rook-ceph-osd-prepare-node6-dpnfp                 0/1     Completed               0          28m
rook-ceph-tools-7798bd6fdf-8c5qp                  1/1     Running                 0          20m
rook-discover-55mlf                               1/1     Running                 1          31m
rook-discover-9fngn                               1/1     Running                 0          31m
rook-discover-tpss9                               1/1     Running                 0          31m

```

On node: 

```
admin@node6:~$ sudo lvm version
  LVM version:     2.03.02(2) (2018-12-18)
  Library version: 1.02.155 (2018-12-18)
  Driver version:  4.39.0
  Configuration:   ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --exec-prefix= --bindir=/bin --libdir=/lib/x86_64-linux-gnu --sbindir=/sbin --with-usrlibdir=/usr/lib/x86_64-linux-gnu --with-optimisation=-O2 --with-cache=internal --with-device-uid=0 --with-device-gid=6 --with-device-mode=0660 --with-default-pid-dir=/run --with-default-run-dir=/run/lvm --with-default-locking-dir=/run/lock/lvm --with-thin=internal --with-thin-check=/usr/sbin/thin_check --with-thin-dump=/usr/sbin/thin_dump --with-thin-repair=/usr/sbin/thin_repair --enable-applib --enable-blkid_wiping --enable-cmdlib --enable-dmeventd --enable-dbus-service --enable-lvmlockd-dlm --enable-lvmlockd-sanlock --enable-lvmpolld --enable-notify-dbus --enable-pkgconfig --enable-readline --enable-udev_rules --enable-udev_sync
``` 

To get this working I have to remove OSDs from CLI, then remove deployments ( even if I have removeOSDsIfOutAndSafeToRemove set to true ), then I have to kill operator pod ( because 8 hours is not long enough to pick up there are new drive in old node and yes I have "useAllDevices"  )

That is a lot of manual steps to recover a system what is created to be fault-tolerant and self-healing on top of the system what is created to be fault-tolerant and self-healing. I don't mind that I have to remove old OSDs I mind that operator do not find out there is a new empty block device and do not consume it.  

Right now I was testing another scenario when after node restart ( node4 in my case )  I just restart operator to notice that job "rook-ceph-osd-prepare-node4" was created again ( looks like for some reason was removed ) so operator was able to pick up there was empty storage. 

So let's paint here scenario, on your blog post ( https://blog.rook.io/run-your-own-high-performance-ebs-wherever-kubernetes-runs-798a136bd808 ) is a good example of how to use rook and ceph on top of k8s however restart any of server from the AWS console ( not OS ) or crash of host make all data from SSD gone also AWS have outages ( https://www.theregister.co.uk/2019/09/04/aws_power_outage_data_loss/ ) so the idea of the system what can a self come back and restore to new block drive is appealing however right now rook do not recognise new drives on "old" nodes. 

Maybe I have the wrong idea here so please correct me, is this correct behaviour for rook operator?

**Comment by travisn** [comment]
> So let's paint here scenario, on your blog post ( https://blog.rook.io/run-your-own-high-performance-ebs-wherever-kubernetes-runs-798a136bd808 ) is a good example of how to use rook and ceph on top of k8s however restart any of server from the AWS console ( not OS ) or crash of host make all data from SSD gone also AWS have outages ( https://www.theregister.co.uk/2019/09/04/aws_power_outage_data_loss/ ) so the idea of the system what can a self come back and restore to new block drive is appealing however right now rook do not recognise new drives on "old" nodes.

@HubertBos Can you confirm what is happening to the SSD drives after the nodes are restarted? The devices are wiped clean during the restart? Or new devices are attached in place of the old devices? That's not expected with the aws ephemeral storage. If the same instance is restarted, the ssd should still have the data. Rook is expected to work well when the local data is persistent and you can rely on it. If a drive is lost, Rook requires [manual intervention](https://rook.github.io/docs/rook/v1.3/ceph-osd-mgmt.html#remove-an-osd) to clean up the OSD.

Rook does watch for events of nodes being added to the cluster in order to configure the OSDs, and also events for new devices being attached. But watching for these events is not perfect, so you must be hitting a corner case with these watchers.

**Comment by HubertBos** [comment]
Hello 

Let's make it clear: 

1. Thank you all for fantastic work on Rook, this is an interesting piece of software. 
2. Thank you all @travisn @BlaineEXE @jhesketh your time is precious and I'm grateful for your support. 
3. I will open a new ticket to carry on the conversation about this case. 

Hands down you guys are amazing. :pray:
