### ISSUE TITLE
rook-ceph v1.3 couldn't work in Minikube without some must-have changes

### ISSUE THREAD

**Issue by brightzheng100** [rook/rook#5301]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

`rook-ceph` v1.3 couldn't work properly in Minikube because of errors or issues which include:
- port conflict on port `9090`
- no properly configured `cluster.yaml` file
- docs are not reflected on how to run `rook-ceph` in Minikube

**Expected behavior:**

By following the docs, we can easily setup `rook-ceph` in Minikube for evaluation/demo purposes.

**How to reproduce it (minimal and precise):**

Let's use the v1.3 release branch:

```
git clone --single-branch --branch release-1.3 https://github.com/rook/rook.git
```

Firstly, there is a known issue (#5299) of port conflict in both rook-cepth v1.2 and v1.3 in `cluster/examples/kubernetes/ceph/operator.yaml`, to avoid that, we need to make a change:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
data:
  ...
  # CSI_RBD_GRPC_METRICS_PORT: "9090"
  CSI_RBD_GRPC_METRICS_PORT: "9092"
```

Then go through the basic installation process:

```sh
kubectl create -f rook/cluster/examples/kubernetes/ceph/common.yaml
kubectl create -f rook/cluster/examples/kubernetes/ceph/operator.yaml   # with updated port
kubectl create -f rook/cluster/examples/kubernetes/ceph/cluster.yaml      # don't know why the cluster-test.yaml in v1.2 is gone
```

After a while, everything _looks_ good except one of the `mon` pod is pending:

```sh
$ kubectl get pod -n rook-ceph
NAME                                            READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-5xxf8                          3/3     Running   0          13m
csi-cephfsplugin-provisioner-5975ffc644-j4bjf   5/5     Running   0          13m
csi-cephfsplugin-provisioner-5975ffc644-x7gsk   5/5     Running   0          13m
csi-rbdplugin-8c269                             3/3     Running   0          13m
csi-rbdplugin-provisioner-dc8b4dd6-92h2x        6/6     Running   0          13m
csi-rbdplugin-provisioner-dc8b4dd6-cqrsj        6/6     Running   0          13m
rook-ceph-mon-a-canary-6b886f8946-9lvq7         1/1     Running   0          86s
rook-ceph-mon-b-canary-5bdd96f45-9dd9r          0/1     Pending   0          85s
rook-ceph-operator-599765ff49-qvjn5             1/1     Running   0          24m
rook-discover-h554n                             1/1     Running   0          22m

$ kubectl describe pod rook-ceph-mon-b-canary-5bdd96f45-9dd9r -n rook-ceph
...
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  66s   default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules.
```

Of course, because we have only one node here in Minikube so let's change a bit on the `cluster.yaml`:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  ...
  mon:
    count: 1  # reduced to 1 from 3
```

Now, let's delete the operator and cluster, together with Minikube's data folder and re-install:

```sh
kubectl delete -f rook/cluster/examples/kubernetes/ceph/cluster.yaml
kubectl delete -f rook/cluster/examples/kubernetes/ceph/operator.yaml
minikube ssh "sudo rm -rf /var/lib/rook"

kubectl create -f rook/cluster/examples/kubernetes/ceph/operator.yaml   # with updated port
kubectl create -f rook/cluster/examples/kubernetes/ceph/cluster.yaml      # with reduced mon
```

Then everything _looks_ great:

```sh
NAME                                                 READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-fr4qw                               3/3     Running     0          112s
csi-cephfsplugin-provisioner-5975ffc644-hd6n7        5/5     Running     0          112s
csi-cephfsplugin-provisioner-5975ffc644-njsgc        5/5     Running     0          112s
csi-rbdplugin-frzqr                                  3/3     Running     0          113s
csi-rbdplugin-provisioner-dc8b4dd6-bc5ws             6/6     Running     0          113s
csi-rbdplugin-provisioner-dc8b4dd6-xfs5b             6/6     Running     0          113s
rook-ceph-crashcollector-minikube-7ccc7494cf-2dt2n   1/1     Running     0          85s
rook-ceph-mgr-a-767878578c-hvwt6                     1/1     Running     0          85s
rook-ceph-mon-a-798b9fff44-tsddt                     1/1     Running     0          93s
rook-ceph-operator-599765ff49-4hn7r                  1/1     Running     0          2m14s
rook-ceph-osd-prepare-minikube-dztj7                 0/1     Completed   0          71s
rook-discover-zthzs                                  1/1     Running     0          2m13
```

And then install the `toolbox` and exec into it:

```sh
$ kubectl apply -f rook/cluster/examples/kubernetes/ceph/toolbox.yaml

$ kubectl -n rook-ceph exec -it $(kubectl -n rook-ceph get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}') bash
[root@rook-ceph-tools-877c4d966-k6bvg /]# ceph status
  cluster:
    id:     5195b163-c59b-494a-9a07-e273a533e349
    health: HEALTH_WARN
            OSD count 0 < osd_pool_default_size 3

  services:
    mon: 1 daemons, quorum a (age 3m)
    mgr: a(active, since 3m)
    osd: 0 osds: 0 up, 0 in

  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:
```

The status is `HEALTH_WARN` and no OSDs are there.

Let's check out the logs of the `rook-ceph-osd-prepare-minikube` job:

```sh
$ kubectl logs -n rook-ceph --all-containers rook-ceph-osd-prepare-minikube-dztj7
...
2020-04-21 08:03:09.836426 I | cephosd: configuring osd devices: {"Entries":{}}
2020-04-21 08:03:09.836538 I | cephosd: no new devices to configure. returning devices already configured with ceph-volume.
2020-04-21 08:03:09.836547 D | exec: Running command: ceph-volume lvm list  --format json
2020-04-21 08:03:10.438794 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2020-04-21 08:03:10.438851 W | cephosd: skipping OSD configuration as no devices matched the storage settings for this node "minikube"
```

Note here: `cephosd: skipping OSD configuration as no devices matched the storage settings for this node "minikube"`

So to make it work, we may have to follow one of below two things:
1. To use a folder in Minikube to create OSDs -- unfortunately, I didn't know how;
2. (recommended) To simply add an extra disk and attach it to Minikube's VM, which works.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): `MacOS`
* Kernel (e.g. `uname -a`): `Darwin Brights-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`
* Rook version (use `rook version` inside of a Rook Pod):
```
rook version
rook: v1.3.1
go: go1.13.8
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
```
* Kubernetes version (use `kubectl version`):
```
kubectl version --short
Client Version: v1.16.3
Server Version: v1.16.3
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Latest Minikube

**Comment by travisn** [comment]
@brightzheng100 The documentation is targeted for production, rather than a test minikube cluster. 

I do agree that the cluster-test.yaml is a nice example and will open a PR to restore it similar to how we had it in 1.2. I'll also add a note to the quickstart guide that cluster-test.yaml can be used for minikube.

**Comment by brightzheng100** [comment]
After applying a series workaround and fixes, `rook-ceph` could actually work well in Minikube as per what I've tested.
So I'd say it's more on documentation issue with some missing manifest files.

Do you think adding a dedicated doc for Minikube would help -- and people would learn from Minikube and apply to whatever they're using for evaluation?

**Comment by travisn** [comment]
While I hope #5305 will help improve the documentation, I don't see us changing the documentation to dedicate a topic to minikube. But please do comment on #5305 with other suggesitons.

**Comment by Obleskar** [comment]
@brightzheng100, thanks for the storage tip!

**Comment by omkarprabhu-98** [comment]
@brightzheng100 @travisn, could you please let me know 
1. how exactly to fix the problem of osd pod not coming up? 
2. And why does this happen?

I am running `minikube` and using `cluster-test.yaml`, with `dataDirHostPath` changed as:
```
  dataDirHostPath: /data/rook
```
The osd prepare pod logs as follows:
```
PS C:\Users\omkar\rook\cluster\examples\kubernetes\ceph> kubectl -n rook-ceph logs rook-ceph-osd-prepare-m01-c9mqc --tail=20
2020-05-11 10:39:25.671613 D | exec: Running command: lsblk /dev/ram15 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-05-11 10:39:25.674171 D | exec: Running command: ceph-volume inventory --format json /dev/ram15
2020-05-11 10:39:26.373145 I | cephosd: skipping device "ram15": ["Insufficient space (<5GB)"].
2020-05-11 10:39:26.373169 D | exec: Running command: lsblk /dev/sda --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-05-11 10:39:26.376218 D | exec: Running command: ceph-volume inventory --format json /dev/sda
2020-05-11 10:39:27.574940 I | cephosd: skipping device "sda": ["locked"].
2020-05-11 10:39:27.575186 D | exec: Running command: lsblk /dev/sdb --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-05-11 10:39:27.584418 D | exec: Running command: ceph-volume inventory --format json /dev/sdb
2020-05-11 10:39:29.051731 I | cephosd: skipping device "sdb": ["locked"].
2020-05-11 10:39:29.051778 D | exec: Running command: lsblk /dev/sdc --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-05-11 10:39:29.054248 D | exec: Running command: ceph-volume inventory --format json /dev/sdc
2020-05-11 10:39:30.135637 I | cephosd: skipping device "sdc": ["locked"].
2020-05-11 10:39:30.135761 D | exec: Running command: lsblk /dev/sdd --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-05-11 10:39:30.139760 D | exec: Running command: ceph-volume inventory --format json /dev/sdd
2020-05-11 10:39:31.077097 I | cephosd: skipping device "sdd": ["locked"].
2020-05-11 10:39:31.090767 I | cephosd: configuring osd devices: {"Entries":{}}
2020-05-11 10:39:31.090876 I | cephosd: no new devices to configure. returning devices already configured with ceph-volume.
2020-05-11 10:39:31.090953 D | exec: Running command: ceph-volume lvm list  --format json
2020-05-11 10:39:31.975605 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2020-05-11 10:39:31.975708 W | cephosd: skipping OSD configuration as no devices matched the storage settings for this node "m01"
```

**Comment by travisn** [comment]
@omkarprabhu-98 Looks like you don't have a raw device or partition available for creating an OSD. See the [prerequisites](https://rook.github.io/docs/rook/v1.3/ceph-prerequisites.html#ceph-prerequisites) for more details.

**Comment by umegaya** [comment]
https://github.com/rook/rook/issues/5301#issuecomment-626627623

recently I have run into similar issue (I used osx minikube with hyperkit driver), and it was hard to aware the real cause. so I will write my case for future visitors, though it seems to be a bit off-topic. 

on minikube, rook document https://rook.io/docs/rook/v1.10/Contributing/development-environment/#minikube recommend to create volumes for rook by using `--extra-disks` option, like this

```
minikube start --disk-size=40g --extra-disks=1 --driver hyperkit
```

I follow the instruction but minikube does not create extra disk (should be vdb), I re-create minikube cluster repeatedly, update minikube to latest version, but nothing helps.

the actual cause is, my local hyperkit minikube driver seems to be too old to support the feature that extra-disks require, , and minikube does not warn about it.

```
ls -al  /Users/$USER/.minikube/bin/docker-machine-driver-hyperkit 
-rwsr-xr-x  1 root  wheel  11434364  7 12  2020 /Users/$USER/.minikube/bin/docker-machine-driver-hyperkit
```

if it is too old, just remove it then minikube try to re-install with latest one.

hope this helps.
