### ISSUE TITLE
ceph tear down ssd

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#5307]
the documentation on the website should be updated to suggest using blkdiscard instead of dding over the disk when its an ssd.

**Comment by travisn** [comment]
@kfox1111 Have a suggestion for what exactly the instructions should be in the case of the ssd? If you can verify the command that works for you it'll be quicker to get the docs updated.

**Comment by kfox1111** [comment]
When I did it yesterday, it was just:
blkdiscard /dev/sdX
