### ISSUE TITLE
volumeSnapshot's readyToUse is stuck in false state and volumeSnapshotContent is not created

### ISSUE THREAD

**Issue by viveksinghggits** [rook/rook#5311]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Creating the volumeSnapshot using [the manifest](https://github.com/rook/rook/blob/release-1.3/cluster/examples/kubernetes/ceph/csi/rbd/snapshot.yaml) should create a volumeSnapshotContent successfully and the `readyToUse` status for the volumeSnapshot should be true, readyToUse is stuck in false state. 

**Expected behavior:**
`readyToUse` of `volumeSnapshot` should be changed to `true` and `volumeSnapshotContent` should be created. 

**How to reproduce it (minimal and precise):**
I have setup the operator using helm release installation and then created the cluster using the [manifest] (https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml) (after changing the storageclassname), after that I have also installed the `rook-ceph-block` storageclass using [the manifest](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml) and the volumesnapshotclass using [the manifest](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/rbd/snapshotclass.yaml).
Now when I try to follow the example manifest (pvc.yaml) that in the dir `cluster/examples/kubernetes/ceph/csi/rbd` and then to create the `volumeSnapshot` for this pvc I create volumesnapshot resource using (snapshot.yaml) that is in the same dir. The volumeSnapshot is created but its `status.readyToUse` is stuck in false state. How do I go about debugging this?

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
please provide csi-snapshotter logs from the rbd provisioner pod.


please feel the template with Environment details, without that its hard to figureout whats the exact issue

**Comment by viveksinghggits** [comment]
Hi @Madhu-1 
below are the logs, which seems pretty clear 
```

I0422 13:25:00.276407       1 snapshot_controller.go:615] createSnapshot: Creating snapshot rctest/rbd-pvc-snapshot through the plugin ...
I0422 13:25:00.353420       1 snapshot_controller.go:1138] Added protection finalizer to persistent volume claim rbd-pvc
E0422 13:25:03.322592       1 snapshot_controller.go:370] createSnapshot [create-rctest/rbd-pvc-snapshot[8e1bbd13-ac0e-431b-9190-247f4d90bccc]]: error occurred in createSnapshotOperation: snapshot controller failed to update rctest/rbd-pvc-snapshot on API server: the server could not find the requested resource (put volumesnapshots.snapshot.storage.k8s.io rbd-pvc-snapshot)
E0422 13:25:03.322642       1 goroutinemap.go:150] Operation for "create-rctest/rbd-pvc-snapshot[8e1bbd13-ac0e-431b-9190-247f4d90bccc]" failed. No retries permitted until 2020-04-22 13:25:03.822617271 +0000 UTC m=+26727.352074770 (durationBeforeRetry 500ms). Error: "snapshot controller failed to update rctest/rbd-pvc-snapshot on API server: the server could not find the requested resource (put volumesnapshots.snapshot.storage.k8s.io rbd-pvc-snapshot)"

```
but i am still not able to figure out the exact issue.

**Comment by viveksinghggits** [comment]
This issue seems to be related to another issue https://github.com/rook/rook/issues/4178, but I didnt install any other version I have been installing release-1.3 for all CRDs.

**Comment by viveksinghggits** [comment]
It does seem to be the `CRD` versions issue. I was installing CRDs separately and then the CRs. When I dont install the CRDs separately and let is install while creating cephcluster things work.
