### ISSUE TITLE
rgw doesn't treat mime.types right

### ISSUE THREAD

**Issue by chrono2002** [rook/rook#5312]
Cannot get .js file as application/javascript type. 
Always got text/plain. 
.png is working though.

root@test:~/scripts# ./s3_test.sh
INFO: Compiling list of local files...
INFO: Running stat() and reading/calculating MD5 values on 1 files, this may take some time...
INFO: Summary: 1 local files to upload
upload: 'test2.js' -> 's3://test-6dcb1fc7-9560-422c-9146-d347434d1252/test2.js'  [1 of 1]
 384254 of 384254   100% in    0s     4.31 MB/s  done
Public URL of the object is: http://rook-ceph-rgw-obj.rook-ceph.svc.cluster.test/test-6dcb1fc7-9560-422c-9146-d347434d1252/test2.js
2020-04-22 16:27    384254   s3://test-6dcb1fc7-9560-422c-9146-d347434d1252/test2.js

root@test:~/scripts# curl -v http://rook-ceph-rgw-obj.rook-ceph.svc.cluster.test/test-6dcb1fc7-9560-422c-9146-d347434d1252/test2.js 1>/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.240.143.239...
* TCP_NODELAY set
* Connected to rook-ceph-rgw-obj.rook-ceph.svc.cluster.test (10.240.143.239) port 80 (#0)
> GET /test-6dcb1fc7-9560-422c-9146-d347434d1252/test2.js HTTP/1.1
> Host: rook-ceph-rgw-obj.rook-ceph.svc.cluster.test
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 384254
< Accept-Ranges: bytes
< Last-Modified: Wed, 22 Apr 2020 16:27:27 GMT
< x-rgw-object-type: Normal
< ETag: "570fde503c170fc8f81a22211e93a08a"
< x-amz-meta-s3cmd-attrs: uid:0/gname:root/uname:root/gid:0/mode:33188/mtime:1571837567/atime:1587571883/md5:570fde503c170fc8f81a22211e93a08a/ctime:1587571862
< X-Amz-Storage-Class: STANDARD
< x-amz-request-id: tx00000000000000000f0b0-005ea070d0-569fb2-obj
< Content-Type: text/plain
< Date: Wed, 22 Apr 2020 16:29:04 GMT
< Connection: Keep-Alive

[root@rook-ceph-rgw-obj-a-7f5d7699f4-24gdv /]# cat /etc/ceph/rgw/mime.types | grep java
application/java-archive                        jar
application/java-serialized-object              ser
application/java-vm                             class
application/javascript                          js
`
rook-ceph               2               Mon Mar  2 18:30:49 2020        DEPLOYED        rook-ceph-v1.2.5

**Comment by leseb** [comment]
Isn't this more a rgw issue than a rook one? I remember we do things where we inject mime types but I don't think we are breaking anything...

**Comment by chrono2002** [comment]
Probably it's rgw issue, but I can't find where I can report it.
I dig into civetweb and beast. They are by design mime compatible but somehow crippled.
According to rgw documentation mime.types only works for swift but not s3.
Maybe there is an option to turn mime.types off completely instead of reporting incorrect ones?

**Comment by leseb** [comment]
@thotz thoughts on this?

**Comment by thotz** [comment]
Don't have much idea, @cbodley @mattbenjamin can u please validate [comment](https://github.com/rook/rook/issues/5312#issuecomment-629538761)

**Comment by cbodley** [comment]
radosgw just stores the `content-type` header given by the client during the upload, and serves that type back when it's downloaded

which s3 client is uploading the objects? it looks like s3cmd? s3cmd has several options that control what it sends for `content-type`:
```
  --default-mime-type=DEFAULT_MIME_TYPE
                        Default MIME-type for stored objects. Application
                        default is binary/octet-stream.
  -M, --guess-mime-type
                        Guess MIME-type of files by their extension or mime
                        magic. Fall back to default MIME-Type as specified by
                        --default-mime-type option
  --no-guess-mime-type  Don't guess MIME-type and use the default type
                        instead.
  --no-mime-magic       Don't use mime magic when guessing MIME-type.
  -m MIME/TYPE, --mime-type=MIME/TYPE
                        Force MIME-type. Override both --default-mime-type and
                        --guess-mime-type.
```
you can add the -d flag during upload to see which content-type s3cmd chooses - in your case, it's choosing `text/plain`
