### ISSUE TITLE
CRD for Ceph bucket notifications

### ISSUE THREAD

**Issue by guimou** [rook/rook#5313]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
In its new release, Ceph has introduced bucket notifications features.
Setup of those notifications are normally done by sending HTTP requests to the RGW, either to create/delete topics pointing to specific endpoints, or create/delete bucket notifications based on those topics.
The purpose of this feature would be to ease this process and avoid using external tools or scripts. It could instead be done by having new CRDs for topics and notifications.

**What is the use case behind this feature:**
This would be useful to streamline deployment of new buckets through OBCs and setup of related notifications, all from simple YAML file instead of turning to boto scripts, Postman,...

**Note**
We already have a small team ready to implement this, but contributions are always welcome! A document will be submitted to detail the proposition.

**Comment by guimou** [comment]
Documentation PR for comments: https://github.com/rook/rook/pull/5382

**Comment by yuvalif** [comment]
updated PR for comments: https://github.com/rook/rook/pull/6425

**Comment by yuvalif** [comment]
implemented in: https://github.com/rook/rook/pull/8426
