### ISSUE TITLE
When the network fluctuates, the mount will report an error

### ISSUE THREAD

**Issue by peacocktrain** [rook/rook#5316]
# Describe the bug #
When the network is suddenly disconnected and then restored, the file mount becomes unavailable. 
**Here is the error report**
> E0423 03:19:03.235751       1 utils.go:161] ID: 59294 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/37124b57-9d0d-4aea-8e42-488db9ae2e3d/volumes/kubernetes.io~csi/pvc-minio-0-copy/mount: permission denied

**the file on a physical machine**
![image](https://user-images.githubusercontent.com/15363932/80057012-36ba0b80-8558-11ea-9a41-37337a8fd717.png)

# Environment details #
- ceph 
14.2.8
- rook 
1.2.7
- Image/version of Ceph CSI driver
2.0.1
- Kubernetes cluster version
1.16
- Kernel
4.19.12-1.el7.elrepo.x86_64
# Steps to reproduce #

1. A file is mounted by csi, keeping read and write
2. Shut down the network
3. See error

# Expected behavior #

When the network is restored, the file is also restored
or
Manual recovery, but there is no need to restart the machine

**Comment by Madhu-1** [comment]
did the issue persist after restoring the network?

if yes please provide below details
* For how much time did you wait after restoring the network
* Provide csi-rbdplugin container logs from the node when the issue is happening
* Provide `mount |grep rbd` output from the csi-rbdplugin container from the node

**Comment by peacocktrain** [comment]
> did the issue persist after restoring the network?
> 
> if yes please provide below details
> 
> * For how much time did you wait after restoring the network
> * Is it for cephfs or rbd
> * Which mounter your are using
> * Provide csi-rbdplugin or cephfsplugin container logs from the node when the issue is happening

* The bad points were kept for a long time such as a few days
* cephfs
* kernel

`I0424 02:14:59.247988       1 utils.go:157] ID: 50350 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0424 02:14:59.248012       1 utils.go:158] ID: 50350 GRPC request: {}
I0424 02:14:59.248784       1 utils.go:163] ID: 50350 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]}
I0424 02:14:59.251660       1 utils.go:157] ID: 50351 GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0424 02:14:59.251686       1 utils.go:158] ID: 50351 GRPC request: {"volume_id":"0001-0009-rook-ceph-0000000000000001-0880755e-0453-11ea-8297-9641634adee4","volume_path":"/var/lib/kubelet/pods/a8c9d61f-b771-40bf-a0c6-ab8e3deb6b29/volumes/kubernetes.io~csi/pvc-240319e6-b0a4-4cb4-85dc-47899a5d1fec/mount"}
I0424 02:14:59.254924       1 mount_linux.go:162] Cannot run systemd-run, assuming non-systemd OS
I0424 02:14:59.254948       1 mount_linux.go:163] systemd-run failed with: exit status 1
I0424 02:14:59.254966       1 mount_linux.go:164] systemd-run output: Failed to create bus connection: No such file or directory
E0424 02:14:59.255022       1 utils.go:161] ID: 50351 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/a8c9d61f-b771-40bf-a0c6-ab8e3deb6b29/volumes/kubernetes.io~csi/pvc-240319e6-b0a4-4cb4-85dc-47899a5d1fec/mount: permission denied
I0424 02:15:43.330448       1 utils.go:157] ID: 50352 GRPC call: /csi.v1.Identity/Probe
I0424 02:15:43.330462       1 utils.go:158] ID: 50352 GRPC request: {}
I0424 02:15:43.331806       1 utils.go:163] ID: 50352 GRPC response: {}
I0424 02:15:54.458879       1 utils.go:157] ID: 50353 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0424 02:15:54.458899       1 utils.go:158] ID: 50353 GRPC request: {}
I0424 02:15:54.459573       1 utils.go:163] ID: 50353 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]}
I0424 02:15:54.462763       1 utils.go:157] ID: 50354 GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0424 02:15:54.462781       1 utils.go:158] ID: 50354 GRPC request: {"volume_id":"0001-0009-rook-ceph-0000000000000001-0880755e-0453-11ea-8297-9641634adee4","volume_path":"/var/lib/kubelet/pods/acf2e53b-ba48-4bad-b31e-0297ad0d863f/volumes/kubernetes.io~csi/pvc-240319e6-b0a4-4cb4-85dc-47899a5d1fec/mount"}
I0424 02:15:54.466082       1 mount_linux.go:162] Cannot run systemd-run, assuming non-systemd OS
I0424 02:15:54.466103       1 mount_linux.go:163] systemd-run failed with: exit status 1
I0424 02:15:54.466117       1 mount_linux.go:164] systemd-run output: Failed to create bus connection: No such file or directory
E0424 02:15:54.466160       1 utils.go:161] ID: 50354 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/acf2e53b-ba48-4bad-b31e-0297ad0d863f/volumes/kubernetes.io~csi/pvc-240319e6-b0a4-4cb4-85dc-47899a5d1fec/mount: permission denied
I0424 02:15:58.998474       1 utils.go:157] ID: 50355 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0424 02:15:58.998528       1 utils.go:158] ID: 50355 GRPC request: {}
I0424 02:15:58.999588       1 utils.go:163] ID: 50355 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]}
I0424 02:15:59.003127       1 utils.go:157] ID: 50356 GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0424 02:15:59.003139       1 utils.go:158] ID: 50356 GRPC request: {"volume_id":"0001-0009-rook-ceph-0000000000000001-6fc272f4-ef2d-11e9-bbb6-0e6410e8bfbb","volume_path":"/var/lib/kubelet/pods/4dbee996-52b6-4b87-9b40-7af9599de478/volumes/kubernetes.io~csi/pvc-minio-0-copy/mount"}
I0424 02:15:59.006122       1 mount_linux.go:162] Cannot run systemd-run, assuming non-systemd OS
I0424 02:15:59.006135       1 mount_linux.go:163] systemd-run failed with: exit status 1
I0424 02:15:59.006142       1 mount_linux.go:164] systemd-run output: Failed to create bus connection: No such file or directory
E0424 02:15:59.006173       1 utils.go:161] ID: 50356 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/4dbee996-52b6-4b87-9b40-7af9599de478/volumes/kubernetes.io~csi/pvc-minio-0-copy/mount: permission denied`
