### ISSUE TITLE
Upgrading to 1.3.2 required a manual step for one pool

### ISSUE THREAD

**Issue by dimm0** [rook/rook#5328]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
During the upgrade I saw the error:

```
2020-04-24 17:56:41.679629 E | ceph-object-controller: failed to reconcile failed to create object store deployments: failed to create object pools: failed to create metadata pools: failed to set pg_num_min on pool ".rgw.root" to "8": failed to set pool property pg_num_min on pool .rgw.root: exit status 22
```

The pool had pg_num = 4. After I changed it manually to 8, the upgrade continued. When I tried manually setting the pg_num_min to 8, ceph said it has to be 4.

**Expected behavior:**
Upgrade procedure requires no human intervention

**Comment by travisn** [comment]
@dimm0 a few questions
- Were you updating from Rook v1.2.x? Or were you already on v1.3? 
- What version of Ceph? Are you on Nautilus v14.2.x? 
- Had you ever changed the PG count of this pool before? Rook doesn't do PG management, so I'm not sure why this pool would be affected.

**Comment by dimm0** [comment]
from Rook v1.2.x
Was nautilus 14.2.6 at that time (I think..)
> Had you ever changed the PG count of this pool before? Rook doesn't do PG management, so I'm not sure why this pool would be affected.
I did a lot of manual management of PGs, and now a bunch of pools are complaining again, so I need to set those mins again

**Comment by travisn** [comment]
There were some PG changes in ceph 14.2.8 IIRC, so perhaps that update will help

**Comment by dimm0** [comment]
I updated to 14.2.9 right after
Want me to close the ticket?

**Comment by travisn** [comment]
Is your issue solved then after updating ceph? We'd need to rope in the right people from core ceph team or find a related Ceph issue to troubleshoot more.

**Comment by dimm0** [comment]
Once I manually fixed the number, the update continued and finished fine. So my cluster is good now

**Comment by dimm0** [comment]
Just wanted to warn you in case other people hit this (who don't watch the upgrade logs all the time..)
