### ISSUE TITLE
AWS odd Rook behaviour with labels

### ISSUE THREAD

**Issue by HubertBos** [rook/rook#5329]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behaviour:**

Rook does not recognise node labels on the new cluster on version 1.3.1

**Expected behaviour:**

Rook recognise node labels on the new cluster like on version 1.3.0

**How to reproduce it (minimal and precise):**

3 host node with labels for CRUSH map for failover, nothing fancy just common, operator and cluster YAML files 

**File(s) to submit**:

Information from ceph osd tree where you can see there is only one row:

```
[root@rook-ceph-tools-877c4d966-fzwcv /]# ceph osd tree
ID  CLASS  WEIGHT  TYPE NAME     STATUS  REWEIGHT  PRI-AFF
-1              0  root default                           
[root@rook-ceph-tools-877c4d966-fzwcv /]# ceph osd tree
ID   CLASS  WEIGHT    TYPE NAME               STATUS  REWEIGHT  PRI-AFF
 -1         13.64218  root default                                     
 -5         13.64218      row b                                        
 -4         13.64218          rack 1                                   
 -9          4.54739              host node4                           
  1    ssd   2.27370                  osd.1       up   1.00000  1.00000
  4    ssd   2.27370                  osd.4       up   1.00000  1.00000
 -3          4.54739              host node5                           
  0    ssd   2.27370                  osd.0       up   1.00000  1.00000
  3    ssd   2.27370                  osd.3       up   1.00000  1.00000
-11          4.54739              host node6                           
  2    ssd   2.27370                  osd.2       up   1.00000  1.00000
  5    ssd   2.27370                  osd.5       up   1.00000  1.00000
```

On another node ( in this case node4 you can see the label is there )

```
╰─$ kubectl describe node node4
Name:               node4
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=node4
                    kubernetes.io/os=linux
                    topology.rook.io/rack=1
                    topology.rook.io/row=a
```

Labels were added when the Kubernetes cluster was deployed automatically by kubespray.

**Environment**:
* OS (e.g. from /etc/os-release): Debian 10
* Kernel (e.g. `uname -a`):  4.19
* Cloud provider or hardware configuration: AWS, i3.en 2XL
* Rook version (use `rook version` inside of a Rook Pod): 1.3.1
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.1
* Kubernetes version (use `kubectl version`): 
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by HubertBos** [comment]
After a restart of one node by AWS console ROOK expect to node comeback with already storge within, however, because AWS provides a new VM with new drive Rook 1.3.1 stuck with Init:CrashLoopBackOff state and Rook 1.3.0 will add new drives with different OSD ID. Version 1.3.1 does not do that. The restart was to try to apply the label from host to rook.

**Comment by HubertBos** [comment]
Looks like the problem with re-adding storage is related to https://github.com/rook/rook/issues/3189 and this might be related with https://tracker.ceph.com/issues/40937

**Comment by HubertBos** [comment]
So after testing with other scenarios looks like rook can understand only one set of labels.

If I set on 3 nodes labels like: "pod: a pod: b and pod: c" only rook is able to correctly create CRUSH map and apply it to ceph, however, if I have second set of labels the same on all nodes like rack: 1  the rook will get random pod and apply all racks under the same pod.

```
root default
    pod c
        rack1 
            node4:
              osd.1
            node5:
              osd.2
            node6:
              osd.4
```

Instead: 

```
root default
    pod a
        rack1 
            node4:
              osd.1
    pod b
        rack1 
            node5:
              osd.2
    pod c
        rack1 
            node6:
              osd.4
```

According to your documentation ( https://rook.io/docs/rook/v1.3/ceph-cluster-crd.html )

The topology of the cluster is important in production environments where you want your data spread across failure domains. The topology can be controlled by adding labels to the nodes. When the labels are found on a node at first OSD deployment, Rook will add them to the desired level in the CRUSH map.

The complete list of labels in hierarchy order from highest to lowest is:

```
topology.kubernetes.io/region
topology.kubernetes.io/zone
topology.rook.io/datacenter
topology.rook.io/room
topology.rook.io/pod
topology.rook.io/pdu
topology.rook.io/row
topology.rook.io/rack
topology.rook.io/chassis
```

**Comment by travisn** [comment]
@HubertBos If believe the issue you're hitting is that Ceph requires unique names for every level of the CRUSH hierarchy. So if you have multiple racks named `rack1`, Ceph will put them all under the same place in the CRUSH hierarchy instead of under the different pods as you expect. You'll need to name your racks differently if they belong to different pods.

**Comment by HubertBos** [comment]
@travisn Thank you for the update, this is not a Ceph limitation as setting up CRUSH map like this was able before dashboard was even available. ( good old times in datacenter ) 

So do you suggest to set up like this?

```
root default
    pod a
        rack1a 
            node4:
              osd.1
    pod b
        rack1b 
            node5:
              osd.2
    pod c
        rack1c 
            node6:
              osd.4
```

A little bit redundant but might work if Rook can't mark them correctly.

**Comment by travisn** [comment]
Yes, that should work. 
Rook is just passing the detected labels to the OSD and Ceph constructs the CRUSH map. Not sure if it was a change in CRUSH map behavior, but Ceph has required unique names in the CRUSH map as long as I've been aware.

**Comment by HubertBos** [comment]
Hello 

Maybe my memory is rusted than I remember we have to drop crush map decode and upload back. 

If that is a limitation of Rook or ceph will be a good idea to add this edge case as a hint to documentation, maybe someone will save time in future. :-)
