### ISSUE TITLE
Add JSON formatted output from 'create-external-cluster-resources.sh' script

### ISSUE THREAD

**Issue by aruniiird** [rook/rook#5331]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The script `cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh` should be able to generate a json formatted output as well.

**What is use case behind this feature:**
This feature will help the Openshift UI to export/import of the ids and keys (generated by this script) in JSON format and avoids any manual conversion (into JSON file).

**Environment**:

**Comment by leseb** [comment]
Possible when using the `cluster/examples/kubernetes/ceph/create-external-cluster-resources.py`
