### ISSUE TITLE
CSI + flexvolumes 

### ISSUE THREAD

**Issue by abh** [rook/rook#5333]
Is it reasonable / supported to configure a storage class that uses flexvolumes (for existing PVCs) and another that uses CSI?

The migration instructions in #4043  seem complex, error prone and impossible to do without an extended outage (in particular without automation), so I was wondering if at least we could have new PVCs use CSI.

**Comment by travisn** [comment]
@abh Yes both flex and csi storage classes will work at the same time so you can have the existing flex volumes, with new volumes created with csi.
