### ISSUE TITLE
Pool configurations not fully applied when operator stop

### ISSUE THREAD

**Issue by ashangit** [rook/rook#5339]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
During pool creation for a new CephObjectStore the operator pod has been updated.
Due to that update the pod has been terminated just after having created the pool but not applied all configuration (Application tag was not set, but it seems that it could happens fr other parameters like compression, target size ratio...)
At restart the operator does not applied remaining configuration as it is only performed if the pool desn't exist, it just continue pool creation for that CephObjectStore.

**Expected behavior:**
Operator should check that pool configurations are fine at statup

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by ashangit** [comment]
Please assign this issue to me

**Comment by galexrt** [comment]
@ashangit assigned you.
