### ISSUE TITLE
Portable OSDs get stuck if a node is terminated abruptly

### ISSUE THREAD

**Issue by travisn** [rook/rook#5348]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
If a node is goes down and portable OSDs are running on that node, we would expect the OSDs to move to another available node. When the node is drained, the OSDs are rescheduled as expected. However, when the node is abruptly terminated (e.g. power outage), the OSD pod will remain indefinitely in the `terminating` stage because of the PV underneath the OSD that cannot be detached. 

Manual intervention is currently needed to force delete the pod. Kubernetes will wait indefinitely for the node to avoid a split brain scenario in case it comes back up as described in https://github.com/kubernetes/kubernetes/issues/65392. However, in the case of OSDs, Ceph is already designed to protect against the split brain and keeps track of the active OSD.

**Expected behavior:**
The portable OSDs should allow for automatic failover even in the scenario where a node was not terminated properly. This could be accomplished by:
- The operator would monitor the OSD pods 
- If 1) an OSD pod is portable, 2) the OSD is marked as `out`, 3) the OSD pod is stuck in `terminating` state, and 4) the node status is not available
   - Then force delete the OSD pod in an attempt to allow it to start on another node

**How to reproduce it (minimal and precise):**

- Start a K8s cluster in the cloud
- Create a rook cluster with a `storageClassDeviceSet` where `portable: true`
- Terminate a node ungracefully
- See the OSD be stuck indefinitely (unexpected)
- Notice that the mon will be automatically failed over as expected

**Comment by sagyvolkov** [comment]
What happens is the node failing is where the operator is running and also how long we wait to make the "call" to allow usage of the PVC? I mean, if for some reason if its only 5 seconds, do we start the process after 1 second or wait the 5 seconds?

**Comment by travisn** [comment]
If the operator was running on the failed node, the operator should be rescheduled without a problem. The issue will only happen for pods that have an attached volume and k8s can't clean them up because of the potential split brain issue, which depends on the implementation of the underlying storage. 

The proposal is only for the operator to force delete the OSD pod under certain conditions. It will still be up to EBS (or other underlying PV) to make the PV available to mount on another node. Rook won't worry about any timeouts unless it's useful when deciding to force delete the pod.
