### ISSUE TITLE
Document full CRDs in documentation

### ISSUE THREAD

**Issue by psarossy** [rook/rook#5350]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The documentation and the example files only show less than half of the crd proto spec variables available to be set, and the examples don't show the valid formatting of how to add these even if the user figures out that they exist.

![Screen Shot 2020-04-27 at 10 24 37 PM](https://user-images.githubusercontent.com/207358/80440115-0a92e780-88d6-11ea-851a-5877502ae96c.png)

**What is use case behind this feature:**
Example use case:
I'm trying to stand up a new cluster with a filesystem CRD that contains two pools, with different crush rules to put one on the available SSDs and the other on HDDs. None of the examples show how to add the storage class but after digging a bunch you can find it in the block store definition, but no hints on how to include it an still be valid. Also no example provided on how to add a second datapool in a valid format, and if you make any errors, it triggers #5315 currently making the orchestrator wedged.

If this is deemed useful for by the maintainers, I'm happy to propose the changes as well but CONTRIBUTING.md doesn't explain how to contribute to the documentation portion of the code tree.

**Environment**:
Rook v1.3 but I don't think it matters.

**Comment by travisn** [comment]
@psarossy What do you suggest for the examples? If all possible properties were added to the examples it would be confusing. For example, a pool can never be both replicated and erasure coded, so an example should only show one option or the other. The [Pool CRD doc](https://rook.github.io/docs/rook/v1.3/ceph-pool-crd.html) is intended to describe all the possible options. 

We can certainly add more examples in the documentation for the details that are missing, and look forward to your contribution here. The documentation html is all generated from the [Documentation](https://github.com/rook/rook/tree/master/Documentation) md files. You can open a PR with changes to the md files and the CI will regenerate the docs. Thanks!
