### ISSUE TITLE
mdadm-based node cannot clean reboot if RBD PVCs are open

### ISSUE THREAD

**Issue by briantopping** [rook/rook#5351]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When rebooting a node with `mdadm`-backed root disk, if RBD-backed PVCs are in use, the node will fail to cleanly reboot. My suspicion is the `/dev/rbd*` devices were previously managed by container-based agents, but those agents were killed and the orphan devices cause `mdadm` to be unable to get an exclusive lock on the array contents before shutting it down:
<img width="1026" alt="Screen Shot 2020-04-28 at 12 36 09 AM" src="https://user-images.githubusercontent.com/158115/80455702-7af73400-88e9-11ea-9350-52ee3f0a8d75.png">

If any pods with RBD-backed PVCs are stopped before rebooting the node, `mdadm` does not fail to get a device lock and proceeds in a orderly manner.

**Expected behavior:**
I suspect it's something like the RBD mounter needs to remove the RBD devices before giving up shutdown authority. If that happens, `mdadm` will not fail the exclusive lock test and shut down quickly. 

**How to reproduce it (minimal and precise):**
* Build a node with a mirrored root disk (mine has four drives in RAID10)
* Install k8s and Rook (I used kubeadm v1.17.4 + rook 1.3.0)
* Start a container with a RBD PVC mount
* Shut the system down via `shutdown -r now`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7
* Kernel (e.g. `uname -a`): 5.6.0-1.el7.elrepo.x86_64
* Rook version (use `rook version` inside of a Rook Pod): v1.3.0
* Storage backend version (e.g. for ceph do `ceph -v`):ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
* Kubernetes version (use `kubectl version`): v1.17.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN Degraded data redundancy: 345963/712878 objects degraded (48.530%), 64 pgs degraded, 64 pgs undersized; 64 pgs not scrubbed in time; 1 subtrees have overcommitted pool target_size_ratio; 2 daemons have recently crashed; mon b is low on available space

**Comment by travisn** [comment]
@briantopping Are the nodes being drained before the reboot? That should allow the pods to unmount the volumes.

**Comment by briantopping** [comment]
Hi @travisn, I did drain the nodes, although there may have been some workloads that did not stop. 

Is there some way to time out these workloads? I don't know about the full dependency chain, there may be no way to do this.

**Comment by travisn** [comment]
@Madhu-1 thoughts on getting a clean shutdown with the rbd volumes?

**Comment by briantopping** [comment]
Followup: One solution I ended up finding for this was to wire systemd to ignore the situation via `systemctl mask dracut-shutdown`.
