### ISSUE TITLE
External cluster configmap rook-ceph-mon-endpoints it will become an empty file

### ISSUE THREAD

**Issue by vvkkhjt** [rook/rook#5353]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When the ceph cluster is under stress and the state of the ceph cluster is not accessible, the contents of this file are changed to empty by rook-ceph-operator

**Expected behavior:**
When ceph is accessible, the rook-ceph-operator should restore this configuration file

**How to reproduce it (minimal and precise):**

Set up an external ceph cluster, and then put the ceph cluster under pressure,When I set rook-ceph-mon-endpoints file with 
```yaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":[]}]'
  data: "e=192.168.220.72"
  mapping: '{"node":{}}'
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-11T10:18:56Z"
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    kind: CephCluster
    name: rook-ceph-external
    uid: 8ee1ddc0-1035-11ea-ba1c-0050569110eb
  resourceVersion: "393507535"
  selfLink: /api/v1/namespaces/rook-ceph/configmaps/rook-ceph-mon-endpoints
  uid: a387b6b9-1bff-11ea-ba1c-0050569110eb
```
and restart rook-ceph-operator, It can go back to normal

**File(s) to submit**:
Logs:
```sh
2020-04-28 09:46:31.659877 E | op-cluster: failed to get ceph status. failed to get status: exit status 1
2020-04-28 09:46:36.620406 I | exec: unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] error connecting to the cluster
2020-04-28 09:46:36.620662 W | op-mon: failed to check mon health. failed to get mon status. mon status failed. exit status 1
2020-04-28 09:47:22.064701 I | exec: unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] error connecting to the cluster
2020-04-28 09:47:22.064945 W | op-mon: failed to check mon health. failed to get mon status. mon status failed. exit status 1
2020-04-28 09:47:32.093017 I | exec: unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] error connecting to the cluster
2020-04-28 09:47:32.093306 E | op-cluster: failed to get ceph status. failed to get status: exit status 1
```
rook-ceph-mon-endpoints
```yaml
apiVersion: v1
data:
  csi-cluster-config-json: '[{"clusterID":"rook-ceph","monitors":[]}]'
  data: ""
  mapping: '{"node":{}}'
  maxMonId: "-1"
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-11T10:18:56Z"
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: ceph.rook.io/v1
    blockOwnerDeletion: true
    kind: CephCluster
    name: rook-ceph-external
    uid: 8ee1ddc0-1035-11ea-ba1c-0050569110eb
  resourceVersion: "393507535"
  selfLink: /api/v1/namespaces/rook-ceph/configmaps/rook-ceph-mon-endpoints
  uid: a387b6b9-1bff-11ea-ba1c-0050569110eb
```

**Environment**:
* OS (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (e.g. `uname -a`):
Linux enet-220-62.dsky 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Rook version (use `rook version` inside of a Rook Pod):
v1.1.6

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.1 (d555a9489eb35f84f2e1ef49b77e19da9d113972) nautilus (stable)

* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
rke

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
Health

**Comment by travisn** [comment]
@leseb If the operator can't connect to the external cluster, it shouldn't update the configmap, correct? It should only update the configmap after a successful connection.

**Comment by leseb** [comment]
How you tried upgrading your Rook version? `v1.1.6` is pretty old and I suspect the recent code has fixed that issue already.

Thanks.

**Comment by vvkkhjt** [comment]
@leseb If I can't confirm that this problem has been resolved, I don't want to rush to upgrade, because this environment is already in use in the official environment
