### ISSUE TITLE
The API version should be v1alpha1, not v1beta1

### ISSUE THREAD

**Issue by luxas** [rook/rook#536]
You should reserve `v1alpha1` while in alpha, bump the last number whenever you make backwards-incompatible changes (if you think that bump is worth the effort)

Then when you actually graduate to beta, you should mark the API beta. To me, the current naming is confusing and violates the Kubernetes API versioning scheme: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md

There's nothing bad with marking it as alpha, I rather think that's very good for now.
Claiming a beta API level now is not good long-term, and makes (at least me) lose faith in your versioning scheme of the TPR.

@bassam WDYT? We hadn't time to cover this face-to-face, but do you get what I'm after?
I really want us to follow API conventions

**Comment by bassam** [comment]
yes agree. I think this was an oversight and some renaming from `v1beta` to `v1alpha` has already happened, and likely more to come. Assigning to @travisn

**Comment by luxas** [comment]
Side question, why was Cluster named to Rookcluster and why was Pool named Rookpool?
It seems like a lot of Rook duplication...

**Comment by bassam** [comment]
my understanding was that TPRs are global, so `kubectl get Cluster` might be ambiguous. I believe the etcd-operator ran into the same issue. @travis can add more context.

**Comment by travis** [comment]
afraid I don't know anything about this stuff, sorry! would appreciate more precision with the at-mentions. <3

**Comment by bassam** [comment]
sorry. /cc @travisn

**Comment by jbw976** [comment]
We have PR #524 open for this, so I'm marking this issue as v0.4 milestone

**Comment by travisn** [comment]
@luxas, @bassam is correct that the name is typically not used in the fully qualified namespace, so the commands could be ambiguous without the `rook` prefix. For the etcd operator discussion see https://github.com/coreos/etcd-operator/issues/861

**Comment by travisn** [comment]
fixed in #524
