### ISSUE TITLE
Push the rookd image to Docker Hub and create a manifest list

### ISSUE THREAD

**Issue by luxas** [rook/rook#537]
Title says it all.
Manifest list for at least amd64 and arm64. Hopefully arm as well: #497

**Comment by bassam** [comment]
anyone know if quay.io is planning similar support? Unfortunately the `rook` organization is taken on docker hub.

**Comment by luxas** [comment]
Checking if quay.io supports manifest lists, that would fix this use-case at least...

**Comment by luxas** [comment]
Quay.io doesn't support it currently, but sent a mail to fix that.
Will report back on details...

**Comment by bassam** [comment]
related to #751. We got the `rook` namespace on docker hub. I'm torn between using docker hub and quay.io. Both have pros and cons.

### Quay.io
pros:
 - better security scanning especially for public repos
 - better UX and more features
cons:
 - no manifest list support (possibly coming in the future)
 - no aggregate pull counts (although they say its coming in the next release)
 - `docker pull quay.io/rook/rook` vs. `docker pull rook/rook`

### Docker Hub
pros:
 - aggregate pull counts
 - shorter namespace (now that we have `rook`)
 - manifest lists supported 
cons:
 - tags using manifest lists show 0 size (opened a support ticket)
 - no public repo security scanning (even when paying)

Maybe in the short term we should publish to both.

Feedback welcome.

**Comment by luxas** [comment]
I think it makes sense to push to both for a while, then at a given point you'll notice which you like the better. We'll then also know if Quay.io added manifest list support and aggregate pull count and if Docker Hub added support for security scanning...

**Comment by hunter** [comment]
Another data point. Although we use it ourselves, Quay is fairly slow internationally.

For us in Asia, Docker Hub has a slight advantage for speed although we are starting to favour GCR for our own private projects that need a more local POP.
