### ISSUE TITLE
Logger line `Info` should be `Infof` for correct log formatting

### ISSUE THREAD

**Issue by krbcmt** [rook/rook#5371]
https://github.com/rook/rook/blob/d963311dfe28beef668a7f370c87576f34c56626/pkg/operator/ceph/object/user.go#L216

**Comment by leseb** [comment]
Thanks, I have a PR coming touching this code I'll fix it! Thanks for reporting.

**Comment by leseb** [comment]
Included in https://github.com/rook/rook/pull/5372
