### ISSUE TITLE
Enable allowVolumeExpansion provided secret is empty

### ISSUE THREAD

**Issue by Antiarchitect** [rook/rook#5379]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Operator crashes every 3 minuts

**Expected behavior:**
Operator stays stable. Volume expansion works

**How to reproduce it (minimal and precise):**
I've change my Storage class like this:
```
kubectl get storageclasses.storage.k8s.io core-rook-block -oyaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: core-rook
    meta.helm.sh/release-namespace: core-rook
  creationTimestamp: "2020-04-30T14:17:48Z"
  labels:
    app.kubernetes.io/instance: core-rook
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: core-rook
    app.kubernetes.io/version: 1.3.2
    helm.sh/chart: core-rook-0.1.0
  name: core-rook-block
  resourceVersion: "140083848"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/core-rook-block
  uid: 3bfe1971-d6fd-4c28-96c4-ef2803e52378
parameters:
  clusterID: core-rook
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-expand-controller
  csi.storage.k8s.io/controller-expand-secret-namespace: core-rook
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: core-rook
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: core-rook
  imageFeatures: layering
  imageFormat: "2"
  pool: core-rook
provisioner: core-rook.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
It now contains `allowVolumeExpansion: true` and
```
csi.storage.k8s.io/controller-expand-secret-name: rook-csi-expand-controller
csi.storage.k8s.io/controller-expand-secret-namespace: core-rook
```

But now secret with name `rook-csi-expand-controller` is created by the operator and it crashes.

Operator log (from the start to the crash): https://gist.github.com/Antiarchitect/756eab59382817e55a169cd3cb9e6ab3

**Environment**:
* OS (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

* Kernel (e.g. `uname -a`): `Linux worker-1.xxxxx 5.6.7-1.el7.elrepo.x86_64 #1 SMP Wed Apr 22 18:05:11 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Bare Metal
* Rook version (use `rook version` inside of a Rook Pod): 1.3.2 (official Helm chart)
* Storage backend version (e.g. for ceph do `ceph -v`): ceph/ceph:v15.2.1-20200410
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare Metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
  cluster:
    id:     a83d574a-7ca9-4389-bc1c-bdb0f999cfe0
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum ai,ak,al (age 3h)
    mgr: a(active, since 2d)
    mds: core-rook:1 {0=core-rook-b=up:active} 1 up:standby-replay
    osd: 15 osds: 15 up (since 3h), 15 in (since 2d)

  task status:
    scrub status:
        mds.core-rook-a: idle
        mds.core-rook-b: idle

  data:
    pools:   4 pools, 97 pgs
    objects: 36.04k objects, 100 GiB
    usage:   312 GiB used, 6.2 TiB / 6.5 TiB avail
    pgs:     97 active+clean

  io:
    client:   18 KiB/s rd, 1.6 MiB/s wr, 3 op/s rd, 201 op/s wr
```

Will provide any additional debug info

**Comment by Antiarchitect** [comment]
Just run operator with logLevel: DEBUG and it stays stable :))
Operator log: https://gist.github.com/Antiarchitect/b653382a9f1b213f9f2cf5189fa5f571

**Comment by Madhu-1** [comment]
I don't understand the issue at all. The storageclass creation should not affect the operator.

**Comment by Madhu-1** [comment]
The expand secret name you are using seems to be wrong, can you please verify it with storageclass.yaml in rook repo

**Comment by Antiarchitect** [comment]
> The expand secret name you are using seems to be wrong, can you please verify it with storageclass.yaml in rook repo

Hi, what do you mean by wrong? I just set the secret name in StorageClass and rook tries to create it. Or I should use some existing secret from my k8s cluster that is created somewhere else by k8s itself?

**Comment by Antiarchitect** [comment]
OK saw this https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
Will fix and report

**Comment by Antiarchitect** [comment]
Operator is now stable. But I haven't noticed any signs of resizing my pvcs.

**Comment by Madhu-1** [comment]
Operator is not responsible for resizing the pvc, there are CSI pods running. You need to mount your pvc to app pods to see resize in effect

**Comment by Antiarchitect** [comment]
Hmmmm, I've fixed:
```
csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
csi.storage.k8s.io/provisioner-secret-namespace: core-rook
```
Recreated deployment for csi-rbdplugin-provisioners, but still logs saying:
```
I0430 16:01:21.858090       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"core-prometheus", Name:"storage-volume-core-prometheus-server-1", UID:"5b7e9d18-19d8-4930-8782-4baedef3c2ea", APIVersion:"v1", ResourceVersion:"140151704", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume pvc-5b7e9d18-19d8-4930-8782-4baedef3c2ea failed: rpc error: code = Internal desc = provided secret is empty
```

**Comment by Madhu-1** [comment]
You can't resize the older pvc. If you create a new pvc with storageclass who has the expand secret than you can expand the pvc
