### ISSUE TITLE
Advanced features for RBD and intercluster replication

### ISSUE THREAD

**Issue by gagipro** [rook/rook#5387]
Yes I already tried setting up intercluster replication, it do work at Ceph level, not Rook level

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Allow advanced RBD features which are prereq for intercluster pool replication
begin to test as kernel 5.4 with object-map and fast-diff supports now prereq for Ceph

**What is use case behind this feature:**
allow disaster recovery when cluster loss

**Environment**:

**Comment by travisn** [comment]
@gagipro Are you referring to rbd mirroring? Today Rook will start the rbd mirroring daemons with [this setting](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L85-L88), then you need to configure the pools and images for replication in the toolbox. Some are already using this in their clusters and it is a work item to provide a more complete solution in Rook. Can you provide more details for what you tried in Rook so we can troubleshoot what didn't work?

**Comment by gagipro** [comment]
> @gagipro Are you referring to rbd mirroring? Today Rook will start the rbd mirroring daemons with [this setting](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L85-L88), then you need to configure the pools and images for replication in the toolbox. Some are already using this in their clusters and it is a work item to provide a more complete solution in Rook. Can you provide more details for what you tried in Rook so we can troubleshoot what didn't work?

Hi,

Yes RBD mirroring, it doesn't seem possible to setup other features than layering one at Rook level.

it seems exclusive-lock and journaling are prereq for rbd mirroring, you can set this up manually at Ceph level but it doesn't seem supported by Rook at the moment if I'm not wrong. Should it be in the roadmap for 1.4?

Thanks in advance for your help and clarification

**Comment by gagipro** [comment]
Perhaps duplicate of this one, and not rook related?

https://github.com/ceph/ceph-csi/pull/684

**Comment by travisn** [comment]
We will be looking into this for 1.5
