### ISSUE TITLE
docs: create a more detailed roadmap and version control it

### ISSUE THREAD

**Issue by luxas** [rook/rook#539]
The roadmap right now isn't detailed enough IMO (or we should split it out to a user-facing one and a technical one)

Putting it into the repo would be good I think, then other people could collaborate on it (and not maintainers only)

**Comment by luxas** [comment]
I'd like something like:
v0.4
 - Support for k8s v1.6 only
 - Technical thing one
 - Technical goal two etc.

**Comment by luxas** [comment]
And more detail about how to improve the k8s integration.
I talked with @bassam how you could (and really should) avoid creating a volume plugin for kubernetes, and the roadmap should include what you're gonna do instead

**Comment by luxas** [comment]
@bassam Anything concrete to look re this?
Not top priority but just looking though my issues...

**Comment by bassam** [comment]
yes had a good discussion this week about this. will create a ROADMAP.md and commit it to the tree with details.
