### ISSUE TITLE
Ship monitoring config with the helm chart

### ISSUE THREAD

**Issue by surajssd** [rook/rook#5400]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Right now the helm chart does not ship any **ServiceMonitor** or **PrometheusRule**. Add these configs to the chart and add a knob to install only these two.

**Note**: Other configs that installs prometheus operator can be optional because users might have such installations in place already.

Also ship Grafana Charts with the chart.

**Comment by surajssd** [comment]
@travisn is this in the roadmap? Should we reopen this?

**Comment by surajssd** [comment]
Not stale.

**Comment by travisn** [comment]
@surajssd We have released an [experimental helm chart](https://rook.github.io/docs/rook/v1.6/helm-ceph-cluster.html) for the cephcluster CR. Could you set `monitoring.enabled: true`? I believe that will satisfy your scenario.

**Comment by travisn** [comment]
Please reopen if something more than `monitoring.enabled` is needed.
