### ISSUE TITLE
ceph: The operator continues to run in spite of errors when launching the controller.

### ISSUE THREAD

**Issue by llamerada-jp** [rook/rook#5434]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
- The controller wasn't working because we missed to apply CRD(`CephRBDMirror`).
  - `status.phase` in `CephObjectStore` was not set.
  - Even though I prepared `ObjectBucketClaim`, `ConfigMap` was not created and S3 compatibility function was not available.
  - operator had output following error message, but it had not finished abnormally.

```
2020-05-07 06:56:54.141727 E | operator: unable to run the controller-runtime manager. no matches for kind "CephRBDMirror" i
n version "ceph.rook.io/v1"
```

- However, the result of `kubectl get cephclusters.ceph.rook.io` was HEALTH_OK.

**Expected behavior:**
I think it is better to terminate the Operator abnormally in the style Kubernetes if it encounters a serious error that can't provide service.

**How to reproduce it (minimal and precise):**

- Prepare a manifest for building Rook/Ceph environment, remove only CRD of CephRBDMirror and apply it.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
  - As noted above.
* Crashing pod(s) logs, if necessary
  - Pod was not crashed.

**Environment**:
* OS (e.g. from /etc/os-release): CoreOS 2345.3.0
* Kernel (e.g. `uname -a`): 4.19.106-coreos
* Cloud provider or hardware configuration: x86_64 Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
* Rook version (use `rook version` inside of a Rook Pod): 1.3.2 later https://github.com/rook/rook/commit/382c6c3610caa2218f7ccbc51777bc5f15c667e3
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.1
* Kubernetes version (use `kubectl version`): 1.17.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): [CKE](https://github.com/cybozu-go/cke)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by satoru-takeuchi** [comment]
@llamerada-jp 

> The controller wasn't working because we missed to apply CRD(CephRBDMirror).

Does it mean that you applied CephRBDMirror, which Rook v1.3.2 doesn't have, by mistake?

> Prepare a manifest for building Rook/Ceph environment, remove only CRD of CephRBDMirror and apply it.

Can you provide the exact claster.yaml? As I said above, Rook v1.3.2 doesn't have CephRBDMirror CRD. So, "remove only CRD of CephRBDMirror" looks odd to me. Normally, there wouldn't be that CR in your resource.

**Comment by llamerada-jp** [comment]
@satoru-takeuchi 
Thank you for your reply.

I was mistaken. We used the master branch specified bellow (and it is v1.3.2 later.)
https://github.com/rook/rook/commit/382c6c3610caa2218f7ccbc51777bc5f15c667e3

I think cluster.yaml is not related to this error because the error occurred before applying claster.yaml.

**Comment by satoru-takeuchi** [comment]
@llamerada-jp 

Ok.

> Prepare a manifest for building Rook/Ceph environment, remove only CRD of CephRBDMirror and apply it.

Could you provide me which manifests did you apply? Is it as follows?

- common.yaml under cluster/example/kubernetes/ceph/common.yaml with removing the definition of CephRBDMirror CRD
- opetator.yaml under the dame directory as common.yaml

If not, please show me the exact manifests you applied.

**Comment by llamerada-jp** [comment]
@satoru-takeuchi 

Thank you. I made a mistake with your intention.

I used `common.yaml` from the link below. And it is not containing CRD of CephRBDMirror.
https://github.com/cybozu-go/neco-apps/blob/2214fc52fb5b20c1d8873db138ce81ed84b0ddc8/rook/base/upstream/common.yaml

I used `operator.yaml` from the link below.
https://github.com/cybozu-go/neco-apps/blob/2214fc52fb5b20c1d8873db138ce81ed84b0ddc8/rook/base/upstream/operator.yaml
