### ISSUE TITLE
The Rookpool TPR's should have a StorageClass field

### ISSUE THREAD

**Issue by luxas** [rook/rook#544]
I think the StorageClass object should be created by the operator.
No need to force the user to do that.
Also if we do this, the operator can make sure that the Mon endpoints always are up-to-date.

I guess it makes sense to put this `storageClass` field on the Rookpool TPR, and allow some basic customization: name, what else?

I talked about this to @bassam as well -- your thoughts?

**Comment by kokhang** [comment]
Is there an use case where we would want to associate the same pool to different storageclasses?

**Comment by jbw976** [comment]
@travisn will look at this along with new TPR/CRD support for file/object storage. #697 and #698

**Comment by kokhang** [comment]
With the addition of the external-provisioner, the user doesnt need to provide monitor IPs. Also we also allow the flexibility to the user to create their own pools (along with their erasurecode config). If we make the operator create the storageclass, how would the user specify their pool.

**Comment by kokhang** [comment]
@luxas i think we all the new additions we have made to Rook, i believe this use case is been solved.  I will close this. Please feel free to reopen it if you have any other concern. Thanks
