### ISSUE TITLE
k8s/ceph: Recent change to priority classes introduces typo

### ISSUE THREAD

**Issue by immesys** [rook/rook#5442]
**Is this a bug report or feature request?**
* Bug Report

A recent PR (#5394) introduced some yaml syntax typos into the example k8s manifests for ceph.

In two places it reads:
```
  # (Optional) set user created priorityclassName for csi plugin pods.
  # CSI_PLUGIN_PRIORITY_CLASSNAME="system-node-critical"

  # (Optional) set user created priorityclassName for csi provisioner pods.
  # CSI_PROVISIONER_PRIORITY_CLASSNAME="system-cluster-critical"
```

But at that point in the file, it's yaml so it needs a `:` not `=`

Links:
[operator.yaml](https://github.com/rook/rook/commit/f82a07d44100473f7f7e99875cfdc4e1fd06d7c6#diff-fed38e73227bfb1e0c51f3621623fbf4R56-R61) 
and 
[operator-openshift.yaml](https://github.com/rook/rook/commit/f82a07d44100473f7f7e99875cfdc4e1fd06d7c6#diff-7cc49f0b9515cc41c7db745b668e5821R132-R137)

@Madhu-1 ^

**Comment by immesys** [comment]
Incidentally, this made it into the 1.3.3 release, so this isn't just master

**Comment by Madhu-1** [comment]
@immesys Thanks for pointing out , sent a patch for it.
