### ISSUE TITLE
The operator does not die normally after some trouble.

### ISSUE THREAD

**Issue by jc-lab** [rook/rook#5455]
**Is this a bug report or feature request?**
* Bug Report

Sorry, but there is not much information.
mgr and mon crashed.
And the order is unknown, but there is only information that the problem occurred because the abnormal rook-ceph-operator Pod and the newly created rook-ceph-operator Pod coexisted because the operator did not die properly. At that time, certain PVCs could not be connected.

After I kill forcibly the abnormal rook-ceph-operator pod, so it worked normally.

Is there anything I can do to determine the cause?

![image](https://user-images.githubusercontent.com/30275706/81627518-5480df00-9439-11ea-996a-305e6639d9ee.png)

# ceph crash ls
![image](https://user-images.githubusercontent.com/30275706/81627360-f9e78300-9438-11ea-899c-086d1afd8ccc.png)

ceph crash infos
![image](https://user-images.githubusercontent.com/30275706/81627416-1683bb00-9439-11ea-9368-c1a6e6353316.png)
![image](https://user-images.githubusercontent.com/30275706/81627425-1be10580-9439-11ea-8b66-59391e50fe52.png)

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): 4.15.0-88-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.2.6
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.8 (2d095e947a02261ce61424021bb43bb43bd3022d35cb)
* Kubernetes version (use `kubectl version`): v1.17.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): onpremise
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): 
```
HEALTH_WARN 6 daemons have recently crashed
```

**Comment by travisn** [comment]
@jc-lab Not sure what happened here. What do you mean there is an abnormal operator pod that coexisted? Instead of screenshots, please paste the contents of the logs. 

If there are crashes in the mon and mgr pods, you'll need to reach out to the ceph community unless there is a Rook misconfiguration. But there is not enough info to test what happened.

**Comment by badone** [comment]
Almost certainly https://tracker.ceph.com/issues/42026

**Comment by jc-lab** [comment]
Thank you
