### ISSUE TITLE
OBC creation not working after updating from 1.3.1 to 1.3.3

### ISSUE THREAD

**Issue by thotz** [rook/rook#5464]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OBC creation failed in new version
**Expected behavior:**
OBC creation should pass
**How to reproduce it (minimal and precise):**

Create a cluster in 1.3.1 and upgrade to 1.3.3
Create a storageclass and obc out of it

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
```logs
2020-05-12 12:24:31.677590 I | op-bucket-prov: deleting Ceph user ceph-user-F31VHpAv for bucket "ceph-bkt-9c28dfc0-1089-4583-ba9b-51820a069ae2"
2020-05-12 12:24:31.833066 I | op-bucket-prov: User ceph-user-F31VHpAv successfully deleted
2020-05-12 12:24:31.993863 I | op-bucket-prov: Bucket ceph-bkt-9c28dfc0-1089-4583-ba9b-51820a069ae2 successfully deleted
I0512 12:24:31.993945       7 resourcehandlers.go:253]  "msg"="removing ObjectBucket finalizer" "key"="default/ceph-delete-bucket2" "name"="obc-default-ceph-delete-bucket2"
I0512 12:24:31.997521       7 resourcehandlers.go:260]  "msg"="deleting ObjectBucket" "key"="default/ceph-delete-bucket2" "name"="obc-default-ceph-delete-bucket2"
I0512 12:24:32.001706       7 resourcehandlers.go:269]  "msg"="ObjectBucket deleted" "key"="default/ceph-delete-bucket2" "name"="obc-default-ceph-delete-bucket2"
I0512 12:24:32.003420       7 resourcehandlers.go:210]  "msg"="removing secret finalizer" "key"="default/ceph-delete-bucket2" 
I0512 12:24:32.008340       7 resourcehandlers.go:189]  "msg"="removing configmap finalizer" "key"="default/ceph-delete-bucket2" 
I0512 12:24:32.022141       7 resourcehandlers.go:231]  "msg"="removing obc finalizer" "key"="default/ceph-delete-bucket2" 
I0512 12:27:20.042866       7 controller.go:203]  "msg"="reconciling claim" "key"="default/ceph-delete-bucket" 
I0512 12:27:20.042884       7 helpers.go:80]  "msg"="getting claim for key" "key"="default/ceph-delete-bucket" 
I0512 12:27:20.044772       7 helpers.go:181]  "msg"="getting ObjectBucketClaim's StorageClass" "key"="default/ceph-delete-bucket" 
I0512 12:27:20.046476       7 helpers.go:186]  "msg"="got StorageClass" "key"="default/ceph-delete-bucket" "name"="rook-ceph-delete-bucket"
I0512 12:27:20.046507       7 controller.go:223]  "msg"="unsupported provisioner" "key"="default/ceph-delete-bucket" "got"="rook-ceph.ceph.rook.io/bucket"
```
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

Mostly probably,  due to change in operator.yaml    ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true" (wild guess though)

**Environment**:
* OS (e.g. from /etc/os-release):  fedora31
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: minkube
* Rook version (use `rook version` inside of a Rook Pod): 1.3.3
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.8
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
 cluster:
    id:     08df73c4-738b-454f-ba16-f3149f664db1
    health: HEALTH_WARN
            8 pool(s) have no replicas configured
 
  services:
    mon: 1 daemons, quorum a (age 46m)
    mgr: a(active, since 21m)
    osd: 1 osds: 1 up (since 45m), 1 in (since 45m)
    rgw: 1 daemon active (my.store.a)
 
  task status:
 
  data:
    pools:   8 pools, 81 pgs
    objects: 208 objects, 7.2 KiB
    usage:   1.0 GiB used, 9.0 GiB / 10 GiB avail
    pgs:     81 active+clean
 
```

**Comment by leseb** [comment]
Was the OBC already holding buckets? Did you use a new Operator yaml for upgrading?

**Comment by thotz** [comment]
> Was the OBC already holding buckets? Did you use a new Operator yaml for upgrading?
No

Post upgrade the provisioner for obc didn't change. Is this expected behavior 
```
2020-05-13 15:54:18.701258 I | op-k8sutil: ROOK_OBC_WATCH_OPERATOR_NAMESPACE="false" (default)
2020-05-13 15:54:18.701279 I | op-bucket-prov: ceph bucket provisioner launched watching for provisioner "ceph.rook.io/bucket"
2020-05-13 15:54:18.702782 I | op-cluster: ceph status check interval is 60s
I0513 15:54:18.703042       6 manager.go:118] objectbucket.io/provisioner-manager "msg"="starting provisioner"  "name"="ceph.rook.io/bucket"
2020-05-13 15:54:18.713529 I | op-cluster: finalizer already set on cluster rook-ceph
2020-05-13 15:54:21.752602 I | op-mgr: dashboard config has changed. restarting the dashboard module.
```
And new sc has `rook-ceph.ceph.rook.io/bucket`, hence obc created based new sc got failed

**Comment by leseb** [comment]
Oh ok, so you upgraded from the "old" provisioned with `"ceph.rook.io/bucket"` but you used the new SC that has `rook-ceph.ceph.rook.io/bucket`?

**Comment by thotz** [comment]
> Oh ok, so you upgraded from the "old" provisioned with `"ceph.rook.io/bucket"` but you used the new SC that has `rook-ceph.ceph.rook.io/bucket`?

Yes

**Comment by leseb** [comment]
Hum why? I mean if the OBC is already present, I assume you already had a SC `"ceph.rook.io/bucket"` so why injecting the new one?

**Comment by thotz** [comment]
> Hum why? I mean if the OBC is already present, I assume you already had a SC `"ceph.rook.io/bucket"` so why injecting the new one?

So it is not recommended to use new one. There is no specific reason, I accidentally saw this issue. I was working with 1.3.2 and then switched to 1.3.3 ( in my local VM) then  obc was not working.

I was using yamls in git repo that's why encountered this issue

**Comment by leseb** [comment]
If you had an existing OBC running, then it's expected to keep on using the same SC.
Just like you said it's more an accident than a bug.

I'm closing this, feel free re-open if you have any more concerns.

**Comment by vc43** [comment]
I tried to create new ObjectBucketClaim in new rook-ceph cluster v 1.3.3. I tried both provisioner "ceph.rook.io/bucket" and "rook-ceph.ceph.rook.io/bucket" , but I got an error "msg"="unsupported provisioner" in both cases until i removed the OOK_OBC_WATCH_OPERATOR_NAMESPACE from rook-ceph-operator deployment. After that it started to work only with provisioner "ceph.rook.io/bucket"
