### ISSUE TITLE
object store deployment failed to start on openshift

### ISSUE THREAD

**Issue by rootfs** [rook/rook#5468]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
object store should be created
**Expected behavior:**
failed to start object store deployment

**How to reproduce it (minimal and precise):**

Deploy Rook 1.3.3 on OpenShift 4.3.18
follow instructions [here](https://rook.io/docs/rook/v1.3/ceph-openshift.html)
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

```console
# oc get event |grep store-a
25m         Warning   FailedCreate             replicaset/rook-ceph-rgw-my-store-a-5d68c8f9d9                 Error creating: pods "rook-ceph-rgw-my-store-a-5d68c8f9d9-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{167}: 167 is not an allowed group spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed fsGroup: Invalid value: []int64{167}: 167 is not an allowed group]
```

Separately, I manually created a standalone deployment and force it to use SA `rook-csi-cephfs-provisioner-sa` (i.e. `rook-ceph-csi` scc instead of `rook-ceph` scc), the deployment then started:

```console
# oc get -n rook-ceph deployments |grep store
rook-ceph-rgw-my-store-a       0/1     0            0           23m
rook-ceph-rgw-my-store-a2      1/1     1            1           11m
``` 

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.3.3
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@thotz The RGW is failing on OpenShift due to #5362. Can you take a look? There seems to be a conflict between the privileged container and the pod spec with a different security context. On OpenShift notice that the `mon.PodSecurityContext()` method returns a privileged container.

**Comment by thotz** [comment]
@travisn :IMO mon.PodSecurityContext() should not conflict with my changes in #5362, since values represent in different fields of yaml file. But I found that when we set scc.yaml in openshift, it adds different value for security context
```yaml
 securityContext:
    fsGroup: 1000560000
    seLinuxOptions:
      level: s0:c24,c4
```
with my change I might overwrite this values. So I may to check whether existing value instead of blinding setting the fsgroup field. 

Any idea what does gid "1000560000" represents or it is just a junk value?

**Comment by rootfs** [comment]
I read the [rgw spec code](https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/spec.go#L66), it doesn't set any service account, as it does in e.g. [OSD deployment](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/spec.go#L423). This makes rgw deployment very fragile. @thotz

**Comment by travisn** [comment]
@thotz Let's not rely on the fsGroup ID to be the same. In OpenShift it will have a different value as we are seeing. We need to do something similar to the `c.makeChownInitContainer()` that is already applied to the pod. This init container uses `ceph:ceph` instead of a specific ID. Let's create another init container if there is a cert that needs to be chowned.

**Comment by leseb** [comment]
> @travisn :IMO mon.PodSecurityContext() should not conflict with my changes in #5362, since values represent in different fields of yaml file. But I found that when we set scc.yaml in openshift, it adds different value for security context
> 
> ```yaml
>  securityContext:
>     fsGroup: 1000560000
>     seLinuxOptions:
>       level: s0:c24,c4
> ```
> 
> with my change I might overwrite this values. So I may need to check whether existing value instead of blinding setting the fsgroup field.

I don't think this will make it work since the rgw process will still run under the 'ceph' user.

> 
> Any idea what does gid "1000560000" represents or it is just a junk value?

I believe it's generated per cluster? @rootfs do you know?

**Comment by rootfs** [comment]
@leseb 
> Any idea what does gid "1000560000" represents or it is just a junk value?
I think that's from openshift uid/gid range.

**Comment by thotz** [comment]
> I read the [rgw spec code](https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/spec.go#L66), it doesn't set any service account, as it does in e.g. [OSD deployment](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/spec.go#L423). This makes rgw deployment very fragile. @thotz

@rootfs : I am not openshift expert. But can please explain how service account will be useful and how it will be consume rgw pod. If I get more clarity I can work on that.

**Comment by rootfs** [comment]
@thotz I was thinking the missing SA in rgw spec caused missing SCC settings, but later I found the default SA is actually bound to `rook-ceph` SCC [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator-openshift.yaml#L50).
