### ISSUE TITLE
rook-ceph-mgr crash

### ISSUE THREAD

**Issue by ganeshr2** [rook/rook#5469]
1. For issues or feature requests, please create an issue in this repository.
2. For general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://slack.rook.io/).
3. Did you already search the existing open issues for anything similar?  Yes non found

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
rook-ceph-mgr crash

**Expected behavior:** Manager is expected not to crash.

**How to reproduce it (minimal and precise):**: Not sure:
"assert_msg": "/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.8/rpm/el7/BUILD/ceph-14.2.8/src/common/buffer.cc: In function 'const char* ceph::buffer::v14_2_0::ptr::c_str() const' thread 7fa8b4f4e700 time 2020-05-12 21:32:24.099706\n/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.8/rpm/el7/BUILD/ceph-14.2.8/src/common/buffer.cc: 578: FAILED ceph_assert(_raw)\n",

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**: Rook - ceph 14.2.8
* OS (e.g. from /etc/os-release): centos - 8.1
* Kernel (e.g. `uname -a`):  Linux mdabe2v-vnfmkt-master-1 4.18.0-147.5.1.el8_1.x86_64 
* Cloud provider or hardware configuration: Cloud - 
* Rook version (use `rook version` inside of a Rook Pod): 1.3
* Storage backend version (e.g. for ceph do `ceph -v`): ceph 14.2.8
* Kubernetes version (use `kubectl version`): 1.17.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Vanila K8's
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): i have cleared them now. health is good.

[ceph mgr down.txt](https://github.com/rook/rook/files/4618683/ceph.mgr.down.txt)

**Comment by leseb** [comment]
Is crash looping or just assert and start working again?

**Comment by ganeshr2** [comment]
Yes k8 restarted the pod and it started working fine. Any idea on root cause. Why does it show Prometheus in log

**Comment by leseb** [comment]
The bug has been fixed in Ceph https://tracker.ceph.com/issues/44726, we just need the backport.
