### ISSUE TITLE
rook on istio failed, a suggestion for adding annotations to rook created jobs

### ISSUE THREAD

**Issue by zh168654** [rook/rook#5470]
**Describe the bug**

When install rook-ceph on istio-injection namespace, it eventually will fail and osds never come up
because of a well known k8s jobs and istio sidecar problem:
A Job is not considered complete until all containers have stopped running, and Istio Sidecars run indefinitely. So the jobs never complete.
> https://github.com/istio/istio/issues/11045
> https://github.com/rook/rook/issues/2460#issuecomment-457919167

A solution might be support add annotations(sidecar.istio.io/inject: "false") for rook created jobs, is this reasonable and possible?

I found some related issues about annotations, but they are not for all rook created jobs. In my opinion rook-operator and all CephCluster pods could be istio injected except for jobs, until k8s has a better support for sidecar containers after v1.18
> https://github.com/rook/rook/issues/4300
> https://github.com/rook/rook/pull/1784

**How to reproduce it (minimal and precise):**
k8s version: < 1.18, I tested on 1.12 and 1.16
istio version: 1.5.2/1.4.4

It will be failed when install rook-ceph in namespace rook-ceph which istio-injection is enabled. But if istio-injection is disabled, all work well

**Comment by travisn** [comment]
@afflom Do you see this issue with jobs when using istio?

**Comment by afflom** [comment]
We were unable to install rook-ceph into an istio injection enabled namespace. We saw the same (or what we believe to be the same) behavior with rook-ceph as we did with other services that had non-istio compliant service port naming conventions.

Fortunately or maybe unfortunately for us, the rook-ceph operator is really good at identifying parameters that deviate from the desired state that it originally provisions and immediately changes the service port names back to what it originally set when at the time that the rook-ceph cluster was provisioned. 

We will be able to proceed to additional troubleshooting actions once we get the rook-ceph operator to provision services with istio compliant service port names.

**Comment by travisn** [comment]
@afflom Ok, looking forward to hearing how it looks after testing with the fix for the port naming. The fix has been backported to the 1.3 branch now. To test a pre-release of v1.3.6 you can use this tag: `rook/ceph:v1.3.5-12.g0222c6a`

**Comment by afflom** [comment]
@travisn ... I'll test it soonest. Thank you for your help.

**Comment by travisn** [comment]
Expecting this to be fixed now per earlier comments

**Comment by travisn** [comment]
@adrianog In the earlier comment it is expected to be working since v1.3. If you're seeing an issue, please do open a new issue, thanks!
