### ISSUE TITLE
Make full CephFS CSI volume details available on PVC details

### ISSUE THREAD

**Issue by mattirantakomi** [rook/rook#5472]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Full CephFS CSI volume details should be available through `kubectl describe pvc/pv`. At the moment second part of volume handle name/UUID is missing.

When PVC is mounted on pod, its path will be something like:

`/volumes/csi/csi-vol-211d8575-94df-11ea-9b70-ce3cc82ba7ff/83891b7f-4352-47ed-9575-2ab151e8bbcd`. First part of `csi-vol-` UUID `211d8575-94df-11ea-9b70-ce3cc82ba7ff` can be found from PVC/PV details but that second part `83891b7f-4352-47ed-9575-2ab151e8bbcd` is missing.

I don't even know where csi-attacher is getting it when mounting PVC to pod.

**What is use case behind this feature:**

Restore PVC/volume from full file level CephFS backup in a situation where PVC is already deleted.

**Environment**:

* OS (e.g. from /etc/os-release): `Amazon Linux 2`
* Kernel (e.g. `uname -a`): `Linux ip-10-128-9-190.eu-central-1.compute.internal 5.4.20-12.75.amzn2.x86_64 #1 SMP Thu Feb 27 20:41:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `AWS EKS, worker node EC2 instance type t3.large`
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.3.2, go: go1.13.8`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)`
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `AWS EKS`

**Comment by Madhu-1** [comment]
closing this as  we are  still analysing https://github.com/rook/rook/issues/5471
