### ISSUE TITLE
EdgeFS codebase is removed, missing docs

### ISSUE THREAD

**Issue by cbluth** [rook/rook#5482]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
broken github/docs links on http://edgefs.io/

**Expected behavior:**
existing codebase and docs

**How to reproduce it (minimal and precise):**
go to website
click here:
![image](https://user-images.githubusercontent.com/6709636/81917996-38667480-95d6-11ea-9fe3-c471d51f1ca6.png)

---
i was considering using edgefs and rook in a new environment, but i am seeing broken links and missing docs, and this concerns me.

**Comment by mykaul** [comment]
@cbluth  - that doesn't sound like a Rook bug though?

**Comment by travisn** [comment]
@dyusupov @sabbot FYI, but closing since the EdgeFS site does not belong to Rook.
