### ISSUE TITLE
docs: automate the process of generating docs

### ISSUE THREAD

**Issue by bassam** [rook/rook#549]
use mkdocs or equivalent to snapshot and version docs with each build. Our https://rook.io site should enable folks to see different versions of docs.

**Comment by bassam** [comment]
This can be done by adding a new `docs.sh` script to the build/release directory. The docs script would support the `build`, `publish`, `promote` and `cleanup` actions:

- on `build` it should do whatever preprocessing on the .md files if any and maybe put them all in a tarball in the `release/` directory.
- on `publish` it should push a snapshot of the docs to our rook.github.io repo and use the `RELEASE_VERSION` and `RELEASE_CHANNEL` to determine where it the docs go, i.e. master or a tagged release.
- on `promote` we would likely update a new static HTML page that shows which releases are alpha, beta or master
- on `cleanup` not sure if there's much to be done.

**Comment by ilovett** [comment]
Merged via #876
