### ISSUE TITLE
filesytem not installed when using kubespray 2.12

### ISSUE THREAD

**Issue by hezise** [rook/rook#5494]
* Bug Report
I'm using kubespary 2.9 and everything works fine with rook. when I upgraded to 2.12 I noticed that pods are in pending state waiting for pvc
looking in logs I see:

```
May 13 15:48:51 hezi-3nds-130520201134-vm1 kubelet[11793]: E0513 15:48:51.110158   11793 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock" failed. No retries permitted until 2020-05-13 15:50:53.110140488 +0000 UTC m=+25578.219649704 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
May 13 15:48:52 hezi-3nds-130520201134-vm1 kubelet[11793]: E0513 15:48:52.109711   11793 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock" failed. No retries permitted until 2020-05-13 15:50:54.109687699 +0000 UTC m=+25579.219196815 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```

looking at operator log I see
```
 I | exec: Error ENOENT: filesystem 'shared-storage' not found
```

in ceph status I don't see mds in services

```console
$ ceph status
  cluster:
    id:     b7f0e8eb-176a-401e-b7ac-82d6a615ca47
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,d (age 4h)
    mgr: a(active, since 4h)
    osd: 3 osds: 3 up (since 4h), 3 in (since 3d)
 
  data:
    pools:   5 pools, 160 pgs
    objects: 2.22k objects, 0 B
    usage:   3.0 GiB used, 1.2 TiB / 1.2 TiB avail
    pgs:     160 active+clean

$ k describe storageclasses.storage.k8s.io rook-ceph-pool-shared 
Name:                  rook-ceph-pool-shared
IsDefaultClass:        No
Annotations:           meta.helm.sh/release-name=adcc-infra-rook,meta.helm.sh/release-namespace=rook-ceph,storageclass.kubernetes.io/is-default-class=false
Provisioner:           rook-ceph.cephfs.csi.ceph.com
Parameters:            blockPool=pool-shared,clusterID=rook-ceph,csi.storage.k8s.io/node-stage-secret-name=rook-csi-cephfs-node,csi.storage.k8s.io/node-stage-secret-namespace=rook-ceph,csi.storage.k8s.io/provisioner-secret-name=rook-csi-cephfs-provisioner,csi.storage.k8s.io/provisioner-secret-namespace=rook-ceph,fsName=shared-storage,fstype=ext4
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
* Kernel (e.g. `uname -a`):
Linux hezi-3nds-130520201134-vm1 5.3.0-1020-azure #21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:

* Rook version (use `rook version` inside of a Rook Pod):
ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
* Storage backend version (e.g. for ceph do `ceph -v`):

* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubespray 12.2

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox]
HEALTH_OK
(https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by galexrt** [comment]
@hezise You have the issue in the cluster you upgraded and now it reports n filesystem or is that a newly setup cluster?

Does Kubespray reinstall the servers / wipe disks during upgrade?

From the `ceph status` output you have posted Ceph doesn't know about a Ceph Filesystem (anymore?).

**Comment by hezise** [comment]
Hi,
it's a new deployment using kubespray 2.12
I actually have 2 different deployments one is using kubespray 2.9 and one is using kubespray 2.12 
regarding the output of ceph status - this is also one of the reasons I raised it. the only thing that is different is the kubespray version and I couldn't find what is wrong.
rook version
rook: v1.2.6
go: go1.11

**Comment by hezise** [comment]
@galexrt didn't know if I should also add your user

**Comment by hezise** [comment]
I restarted the operator and I see the following:
2020-05-19 18:03:13.449728 I | exec: Running command: ceph fs new shared-storage shared-storage-metadata shared-storage-data0 --force --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/403037458

then I see 
 I | exec: Error EINVAL: pool 'shared-storage-metadata' (id '2') is an erasure-coded pool.  Use of erasure-coded pools for CephFS metadata is not permitted

I looked in my filesystem.yaml template file and I don't any erasure-coded there
{{ range $key, $val := .Values.filesystems }}
---

apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: {{ $val.name }}
spec:
  metadataPool:
    replicated:
      {{ if lt ( int $.Values.deployment.replicas ) ( int $val.replica ) }}
      size: {{ $.Values.deployment.replicas }}
      {{ else }}
      size: {{ $val.replica }}
      {{ end }}
  dataPools:
    - replicated:
        {{ if lt ( int $.Values.deployment.replicas ) ( int $val.replica ) }}
        size: {{ $.Values.deployment.replicas }}
        {{ else }}
        size: {{ $val.replica }}
        {{ end }}
  metadataServer:
    activeCount: 1
    activeStandby: true

**Comment by hezise** [comment]
I found the issue
in our helm command we set a replica according to number on node and we were relying on the role when getting the kubernetes cluster nodes, so it set it to 0 because it wasn't set in kubespray 2.12
