### ISSUE TITLE
Rook 1.3.4 does not build from release build tar

### ISSUE THREAD

**Issue by smijolovic** [rook/rook#5523]
1.3.4 tar.gz archive downloaded

make -j4 LDFLAGS="-X github.com/rook/rook/pkg/version.Version=1.3.4" build

=== helm package rook-ceph
=== ensuring modules are tidied
==> Linting /home/rpmbuild/nimbus8/rook-build/rook/_output/rook-ceph
Lint OK

1 chart(s) linted, no failures
Error: chart metadata (Chart.yaml) missing
make: *** [build/makelib/helm.mk:54: /home/rpmbuild/nimbus8/rook-build/rook/_output/charts/rook-ceph-.tgz] Error 1

**Comment by travisn** [comment]
@smijolovic Why not build from source?
