### ISSUE TITLE
Remove EdgeFS

### ISSUE THREAD

**Issue by stv0g** [rook/rook#5525]
DDN has issued DCMA requests against the EdgeFS Git repo and all forks of it:
https://gist.github.com/siepkes/8e1f51e2ce9e44ba7116ed79e49298f4

See also:
https://news.ycombinator.com/item?id=23113226

Any attempts to contact the maintainer were unsuccessful.
There is no official statement from Nexenta nor DDN about the current situation.

Does anybody have more insight into this mess?

I propose that EdgeFS support should be removed from the hext Rook release.
Remaining issues might also be closed?

**Comment by travisn** [comment]
@dyusupov Do you have more info?

@stv0g The EdgeFS operator has always existed under the ownership of Rook. The underlying EdgeFS storage provider was originally closed source even when it was orchestrated by Rook. The open-sourcing of EdgeFS under question was not related to the Rook codebase. Whether EdgeFS stays open or returns to be closed source can be an independent decision of whether it is removed from Rook. The Rook operator just runs the storage provider images and doesn't require the sources. But certainly we need more information from @dyusupov on the expected path forward.

**Comment by dyusupov** [comment]
Rook EdgeFS code has nothing to do with EdgeFS code base. In accordance to DCMA, DDN allows using EdgeFS binaries for non commercial purposes and encourages users to use published Docker image binaries!

Given the existing EdgeFS community, DDN may or may not consider future "proper" open sourcing plan again. I cannot comment on this as I'm really just following a directive of higher DDN officers and running Rook EdgeFS operator as well as using EdgeFS Docker images is perfectly legal under the conditions of DCMA.

Closing the issue for now.

**Comment by DjangoCalendar** [comment]
Is there any follow up on this issue @dyusupov ?
