### ISSUE TITLE
OSD Prepare reports failed to configure devices

### ISSUE THREAD

**Issue by YiannisGkoufas** [rook/rook#5553]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When creating a cluster the OSD prepare pod should either report that it cannot find any devices or that it succeeds to create one. In this case it does indeed create an osd in a device and then when it lists the volumes it fails to find one.

**Expected behavior:**

When listing the volumes the osd prepare pod should be able to pick it up.

**How to reproduce it (minimal and precise):**

The issue occurred when creating a Ceph Cluster within minikube started with `driver=none`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
[cluster.txt](https://github.com/rook/rook/files/4688298/cluster.txt)
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
[logs.txt](https://github.com/rook/rook/files/4688307/logs.txt)

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
* Kernel (e.g. `uname -a`):
```
Linux hermes008 4.15.0-48-generic #51~16.04.1-Ubuntu SMP Fri Apr 5 12:01:13 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
```
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
```
rook: 0bd9029-dirty
go: go1.13.6
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
ceph version 15.2.2-4-gebdad37c74 (ebdad37c740a7e72dc8d2166af6426ba1643a2eb) octopus (stable)
```
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/ppc64le"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/ppc64le"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
minikube with driver=none
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
OSD count 1 < osd_pool_default_size 3
```

**Comment by leseb** [comment]
So is this `failed to configure devices: failed to get devices already provisioned by ceph-volume lvm: failed to retrieve ceph-volume lvm list results: exit status 1` the last error message you got from the prepare pod?

**Comment by YiannisGkoufas** [comment]
Yeap exactly, it finished there.

**Comment by leseb** [comment]
are you running rook master?

**Comment by YiannisGkoufas** [comment]
rook 1.3

**Comment by YiannisGkoufas** [comment]
Just a bit more output by exec-ing into the toolbox pod:
```
root@rook-ceph-tools-d7c5c8cf6-ddflt:/$ lsblk
sdd                                                                                                    8:48   0    1T  0 disk 
`-ceph--9ba91769--e476--4faa--8b79--55db7be7bcc3-osd--data--f58f4d0b--f343--4442--8a6c--ab9934e217fd 253:0    0    1T  0 lvm  
root@rook-ceph-tools-d7c5c8cf6-ddflt:/# ceph-volume lvm list /dev/sdd
No valid Ceph lvm devices found

**Comment by leseb** [comment]
Is the toolbox running when the prepared job was running? Also I don't think this pod has the necessary permissions (/dev and privileged) to access local devices...

TBH it's the first time I'm seeing an issue like this :/
It would be nice to get into that prepare container and print the ceph-volume debug logs...

**Comment by YiannisGkoufas** [comment]
Inside the toolbox I was able to run `lsblk` and get the devices.
How can I highjack the osd prepare pod and get debug logs?

**Comment by leseb** [comment]
> Inside the toolbox I was able to run `lsblk` and get the devices.

Can you run again without the disk arg like: `ceph-volume lvm list`?

> How can I highjack the osd prepare pod and get debug logs?

That's the tricky part... Accessing the fs of a stopped container if not trivial... We have been discussing of printing that file at the end of the prepare job just in case, it would be handy right now...

**Comment by YiannisGkoufas** [comment]
`ceph-volume lvm list` returns no results

**Comment by YiannisGkoufas** [comment]
Maybe I can add a while true sleep command in here:

https://github.com/rook/rook/blob/master/pkg/util/sys/device.go#L437

And exec there before it dies?

**Comment by leseb** [comment]
> Maybe I can add a while true sleep command in here:
> 
> https://github.com/rook/rook/blob/master/pkg/util/sys/device.go#L437
> 
> And exec there before it dies?

That surely would work yes!
