### ISSUE TITLE
Compression not working with Rook Ceph 14.2.4

### ISSUE THREAD

**Issue by bmv126** [rook/rook#5574]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Compression not being applied on the objects uploaded to the bucket

**Expected behavior:**
Compression should be applied on the objects uploaded to the bucket.

**How to reproduce it (minimal and precise):**
I followed below documentation:
https://docs.ceph.com/docs/master/radosgw/compression/

I used the below command on the rook-toolbox
radosgw-admin zone placement modify --rgw-zone rook-ceph-store --placement-id default-placement --storage-class STANDARD --compression zlib

Below config is seen:
{
            "key": "default-placement",
            "val": {
                "index_pool": "rook-ceph-store.rgw.buckets.index",
                "storage_classes": {
                    "STANDARD": {
                        "data_pool": "rook-ceph-store.rgw.buckets.data",
                        "compression_type": "zlib"
                    }
                },
                "data_extra_pool": "rook-ceph-store.rgw.buckets.non-ec",
                "index_type": 0
            }
        }

File Info:
-rwxr-xr-x. 1 root root 5000000000 Jun 1 03:27 test.file

When I tried to upload the above 5GB file using s3cmd command, I dont see compression happening
s3cmd put test.file --no-ssl --host=${AWS_ENDPOINT} --multipart-chunk-size-mb=1000 --host-bucket= s3://bucket-with-zlib

I am not able to see any compression being applied, when i checked the stats on the bucket
rgw.main":
{
	"size": 5000000000,
	"size_actual": 5000003584,
	*"size_utilized": 5000000000,
	*"size_kb": 4882813,
	"size_kb_actual": 4882816,
	"size_kb_utilized": 4882813,
	*"num_objects": 1 *
}

Do I need to restart something (rgw) ? 

**Environment**:
* OS (e.g. from /etc/os-release): Rhel 7.7
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`): v1.1.7
* Kubernetes version (use `kubectl version`):  1.16
* Storage backend status:
  cluster:
    id:     b176e1f2-fd1f-4cae-9c3b-2e982e1d4f0f
    health: HEALTH_WARN
            2 pools have many more objects per pg than average

  services:
    mon: 3 daemons, quorum a,b,c (age 36h)
    mgr: a(active, since 36h)
    osd: 5 osds: 5 up (since 25h), 5 in (since 25h)
    rgw: 2 daemons active (rook.ceph.store.a, rook.ceph.store.replica.a)

  data:
    pools:   19 pools, 264 pgs
    objects: 10.63k objects, 39 GiB
    usage:   97 GiB used, 1.8 TiB / 1.9 TiB avail
    pgs:     264 active+clean

  io:
    client:   85 B/s rd, 50 KiB/s wr, 0 op/s rd, 0 op/s wr

**Comment by thotz** [comment]
@bmv126 : Please follow [advanced configuration](https://rook.io/docs/rook/v1.3/ceph-advanced-configuration.html#custom-cephconf-settings) for making daemon specific changes, I have never tried compression option but AFAIR for log level change I need to restart rgw pod, so it will be worth to try

**Comment by bmv126** [comment]
@thotz 
Not sure what configuration, I have to add to the config map. 

I tried below steps from the rook-toolbox,
 1) radosgw-admin zone placement modify --rgw-zone rook-ceph-store --placement-id default-placement --storage-class STANDARD --compression zlib

2) Deleted the rgw pod manually.

Even with the above changes, the compression was not happening.

In a non k8s setup, I was able to achieve the compression effect after following below steps:
1)  radosgw-admin zone placement modify --rgw-zone rook-ceph-store --placement-id default-placement --storage-class STANDARD --compression zlib
2) systemctl restart  ceph-radosgw

Not sure how to make this work on the rook-ceph setup.

**Comment by thotz** [comment]
@bmv126 I saw below mail thread about compression not working in rgw https://www.spinics.net/lists/ceph-users/msg56585.html, looks there is issue wrt compression in 14.2.4.
Can u please try to update the ceph version and try again?

**Comment by bmv126** [comment]
@thotz Thanks for the reply.
I had seen the thread https://www.spinics.net/lists/ceph-users/msg56594.html  

In that case the issue was with boto and swift client. 
The Work around suggested was to pass below header:
  headers={'x-object-storage-class': 'STANDARD'}

In my case, I am using s3cmd and the above mentioned header is already passed.

**Comment by thotz** [comment]
Compression worked in my set up in rook 1.3.5 and ceph 14.2.9 
at client side
```console
 ls -ltrh file
-rw-r--r--    1 root     root           0 Jun 11 09:50 file
/aws # truncate -s 2G file 
/aws # ls -ltrh file
-rw-r--r--    1 root     root        2.0G Jun 11 09:51 file
/aws # 
/aws # 
/aws # echo $BUCKET_NAME
ceph-bkt-1170ddb2-c78d-4d7b-8e07-72256b6f51dd
/aws # cat /data/aws-s3-command 
aws s3 ls --no-verify-ssl --endpoint-url http://$BUCKET_HOST:$BUCKET_PORT s3://$BUCKET_NAME
/aws # aws s3 ls --no-verify-ssl --endpoint-url http://$BUCKET_HOST:$BUCKET_PORT s3://$BUCKET_NAME
/aws # aws s3 cp file --no-verify-ssl --endpoint-url http://$BUCKET_HOST:$BUCKET_PORT s3://$BUCKET_NAME
upload: ./file to s3://ceph-bkt-1170ddb2-c78d-4d7b-8e07-72256b6f51dd/file
/aws # aws s3 ls --no-verify-ssl --endpoint-url http://$BUCKET_HOST:$BUCKET_PORT s3://$BUCKET_NAME
2020-06-11 09:59:09 2147483648 file
```
at toolbox
```console
# radosgw-admin zone placement list
[
    {
        "key": "default-placement",
        "val": {
            "index_pool": "my-store.rgw.buckets.index",
            "storage_classes": {
                "STANDARD": {
                    "data_pool": "my-store.rgw.buckets.data",
                    "compression_type": "zlib"
                }
            },
            "data_extra_pool": "my-store.rgw.buckets.non-ec",
            "index_type": 0
        }
    }
]
[root@rook-ceph-tools-7f96779fb9-sgpbq /]# radosgw-admin bucket stats --bucket ceph-bkt-1170ddb2-c78d-4d7b-8e07-72256b6f51dd
{
    "bucket": "ceph-bkt-1170ddb2-c78d-4d7b-8e07-72256b6f51dd",
    "num_shards": 0,
    "tenant": "",
    "zonegroup": "331800fa-8a59-4cd2-9cfa-f0787b38bfe7",
    "placement_rule": "default-placement",
    "explicit_placement": {
        "data_pool": "",
        "data_extra_pool": "",
        "index_pool": ""
    },
    "id": "99c087d5-bea6-49cb-877e-b64e43006f09.44278.1",
    "marker": "99c087d5-bea6-49cb-877e-b64e43006f09.44278.1",
    "index_type": "Normal",
    "owner": "ceph-user-ORkdBXwF",
    "ver": "0#260",
    "master_ver": "0#0",
    "mtime": "2020-06-11 09:45:00.645883Z",
    "max_marker": "0#",
    "usage": {
        "rgw.main": {
            "size": 2147483648,
            "size_actual": 2147483648,
            "size_utilized": 2089472,
            "size_kb": 2097152,
            "size_kb_actual": 2097152,
            "size_kb_utilized": 2041,
            "num_objects": 1
        },
        "rgw.multimeta": {
            "size": 0,
            "size_actual": 0,
            "size_utilized": 0,
            "size_kb": 0,
            "size_kb_actual": 0,
            "size_kb_utilized": 0,
            "num_objects": 0
        }
    },
    "bucket_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    }
}

from ceph df 
my-store.rgw.buckets.data     8  2.0 MiB      257   16 MiB   0.09     18 GiB
````

Please share the logs from rgwpods with higher debug level, let me see whether I can find anything from it

**Comment by thotz** [comment]
Please note ceph version is 15.2.1 not 14.2.9

**Comment by bmv126** [comment]
@thotz 
Thanks for the reply.
Currently I don't have 15.x setup. I will try to check this when I install 15.x ceph cluster.
