### ISSUE TITLE
Rook Services Integration with Istio

### ISSUE THREAD

**Issue by jpower432** [rook/rook#5587]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Change the port name format on Rook Kubernetes Services to integrate with newer version of Isitio.
Current example for rook-ceph-mon-a is name: mgr1
Istio requires protocol[-suffix]. For ex. tcp-mgr1

https://kiali.io/documentation/validations/#_kia0601_port_name_must_follow_protocol_suffix_form

**What is use case behind this feature:**

Allow Rook to integrate with Istio

**Environment**:

Kubernetes - 1.18.1
Istio - v1.5
Rook - v.1.2.6

**Comment by afflom** [comment]
+1 👍
