### ISSUE TITLE
Support fined grained encryption on PVC

### ISSUE THREAD

**Issue by leseb** [rook/rook#5589]
Ability to specify encryption per volumeClaimTemplates, so we can have a portion of the cluster with encrypted drives and another with non-encrypted drives (at-rest).

We need to enhance `StorageClassDeviceSet`  with a new `encrypted` field.

**Comment by leseb** [comment]
We might need to revisit our usage of `encryptedDevice` for this.

**Comment by leseb** [comment]
Part of https://github.com/rook/rook/issues/5590, same implementation.

**Comment by travisn** [comment]
Resolved by #5873
