### ISSUE TITLE
Placement Group Management

### ISSUE THREAD

**Issue by hunter** [rook/rook#560]
Following from some of the discussion in #554 (and #558), it may be useful to add PG configuration to the Pool TPR. That would give more control over the global default which are not a great fit for some of the default pools (the PG calc has some recommendations - http://ceph.com/pgcalc/)

One of the benefits of the dynamic nature of Rook is that some of the PG configuration could be automated. Since the PGs should change as more OSDs are added, we can get some of that info from the rook cluster and adjust if needed (assuming the PGs don't scale down).

The calculator uses the formula of `(( Target PGs per OSD ) x ( OSD # ) x ( %Data )) / ( Size )` so perhaps the estimated `%Data` could be specified in the Pool TPR to let Rook manage the PG Allocation across all the pools.

This also raises the question, when FS or RGW services are launched, should they pre-create the Pool TPRs to allow control over the smaller/less utilised pools.

**Comment by jbw976** [comment]
This is interesting @hunter, it seems like it has two separate parts:
1. When Rook creates a pool, it creates it with an intelligent number of PGs
1. As the number of OSDs increase in the cluster, the rook-operator could increase the number of PGs in existing pools

http://ceph.com/pgcalc/ can get a bit complicated as it depends on a fair amount of cluster "forecasting" knowledge to be known by the user, but I do like your thinking about trying to scope that down to a slim set of information that we'd need to collect from the user via the TPRs.

**Comment by bassam** [comment]
I think ceph needs to support shrinking pgs. Without this it would be hard to make things dynamic.

**Comment by DanKerns** [comment]
I don't think we should be exposing PG's to the end user.  I think we need to figure out how to do the "right thing."  One of the tenants of Rook is that we manage the SDS system so clients of storage don't need to be experts.

**Comment by hunter** [comment]
The difficulty in hiding the PGs is that we need some way of knowing the amount of data to be stored inside a pool. Exposing a % may be an option, although may confuse things since an end user won't know about the system pools (`.rgw.*`, etc). Perhaps a simplified bucket system may work (eg. small, medium, large) which can then calculate based on the existing pools.

Alternatively for smaller clusters, it is possible to use standard sizes - http://docs.ceph.com/docs/master/rados/operations/placement-groups/

**Comment by jpds** [comment]
Ceph appears to be recommending the following on my Luminous cluster:

```too few PGs per OSD (25 < min 30)```

Prehaps it'd be worth using the data from `ceph osd df tree` and the above to calculate the next power of two to use for the recommended PGs in a cluster?

**Comment by jpds** [comment]
Interesting and very relevant:

- http://ceph.com/community/new-luminous-pg-overdose-protection/

**Comment by whereisaaron** [comment]
It looks like ceph instends to add the option to autoscale placement groups, so rook may not need to attend to this. Rook could calculate a good starting, or just wait for the autoscaling to increase the default 100.

http://docs.ceph.com/docs/master/rados/operations/health-checks/?highlight=backfillfull%20ratio#pool-too-few-pgs
```
ceph osd pool set <pool-name> pg_autoscale_mode on
```

Don't see this in 13.2.2, so maybe a later version.

**Comment by travisn** [comment]
Need to confirm that the mgr module for placement mgmt solves this

**Comment by sebastian-philipp** [comment]
please keep in mind that the pg_autoscale mgr module is fairly new. (newly introduced in nautilus).

**Comment by dimm0** [comment]
https://ceph.com/rados/new-in-nautilus-pg-merging-and-autotuning/

**Comment by liewegas** [comment]
I think all we need is a CRD property (cluster or pool?) to enable/disable pg autoscaling.

**Comment by liewegas** [comment]
(or, rather, set the mode.. off, warn, on)

**Comment by sebastian-philipp** [comment]
> I think all we need is a CRD property (cluster or pool?) to enable/disable pg autoscaling.

do we need a generic way to enable or disable mgr modues? e.g. dashboard, prometheus, diskprediction, crash, influx, pg_autoscaler, etc.

**Comment by dimm0** [comment]
I had to enable the OSDs balancer in mgr manually... That's a super useful thing to have

**Comment by dimm0** [comment]
Although this stuff is heavily dependent on ceph features currently used...
After upgrading the ceph version, I had to update the straw to straw2 (whatever it means) and set the reweight-compat... And I'm still behind of what the newest features are. Not sure how you can deal with those updates in rook

**Comment by liewegas** [comment]
:+1: on adding a CRD property to enable mgr modules, as long as specifying some set of modules to enable does not make rook disable any modules not explicitly called out (since we tend to add new modules with each release).

As for converting straw to straw2, I think that's something that rook could do (as an opinionated operator), but it's also something that ceph-mgr could do for the benefit of all users.  I'll add a ticket for ceph to do this on its own...

**Comment by liewegas** [comment]
Ha, ceph already has a CLI command to do this: ``ceph osd crush set-all-straw-buckets-to-straw2``.  Rook could just run this at the end of an upgrade.  If existing buckets were straw there may be a small amount of data movement but it is generally pretty minimal.

**Comment by dimm0** [comment]
Yup, but as I said it's heavily dependent on tunables version, which is dependent on versions of client kernels.. Which you can see the current ones, but you don't know what user will want to connect

**Comment by mykaul** [comment]
> Ha, ceph already has a CLI command to do this: `ceph osd crush set-all-straw-buckets-to-straw2`. Rook could just run this at the end of an upgrade. If existing buckets were straw there may be a small amount of data movement but it is generally pretty minimal.

@travisn  - I assume the above is still relevant? Should we open this item? (it's not clear to me why it's 'done' under 1.1)

**Comment by travisn** [comment]
Agreed, reopening... the bot just closed it and marked it as done

**Comment by sebastian-philipp** [comment]
@lenzgr this might create conflicts between what the dashboard things and what rook things are enabled modules
