### ISSUE TITLE
how can use  customized ceph.conf to deploy ceph.cluster

### ISSUE THREAD

**Issue by saltFisher** [rook/rook#5604]
At now, we deploy ceph cluster by using cluster.yaml. 
In https://rook.io/docs/rook/v1.3/ceph-advanced-configuration.html#custom-cephconf-settings, i found we can use _**kubectl -n rook-ceph edit configmap rook-config-override**_ to update customized ceph.conf.
But there has one sentence, i don't understand, can you help me to understant it.
It wrote _**"To apply your desired configuration, you will need to update this ConfigMap. The next time the daemon pod(s) start, they will use the updated configs."**_, what does mean "The next time the daemon pods start" ? 
my ceph cluster has 3 mons, i deleted 2, then to check whether update customized ceph.conf, it updated. 
Is there means i only need to delete 1 mons, it will update ceph.conf for 3 mons ?

**Comment by leseb** [comment]
This means that  if you edit the configmap on a running cluster, you need to restart the daemons so that it can take affect.

If you are looking at changing the configuration of a daemon please use the `ceph config set` command from the toolbox.

Thanks

**Comment by saltFisher** [comment]
@leseb Han, what's your meaning of restart daemons ? do you mean i should crush this running ceph cluster and operator, then deploy a new one?
as i mentioned, i delete one mons and then it deploys a new mon, is it equal with you mentioned restart the daemons ?

**Comment by leseb** [comment]
By restarting I mean restart the container pod. Yes delete and start is a restart :)

**Comment by saltFisher** [comment]
@leseb Thank you Han, my confusion is whether i only need to restart one mon in three mons. 
In general, we use ceph.conf to config ceph cluster. In rook, i can't see it (i can see ceph.conf , but it doesn't have full configuration information), at now, i know we can use **_configmap rook-config-override_** to update customized ceph.conf.
But i still don't understand why ceph config info updated after i only delete one mon, the ceph cluster has 3 mons, why they updated synchronous ?
if you have some time ,can you tell me a more, thanks.

**Comment by leseb** [comment]
**all** the mons must be updated if you change something. But why not just using `ceph config set` instead? You don't need to restart the daemon with that command.

**Comment by saltFisher** [comment]
@leseb Han,because I will change a lot of items, it's easier to update config file.
 I only updated 2 mons, did not update 3 mons, but that it works in the ceph cluster. As you said, that should not happen. confusing

your advice is right, maybe i should update it as much as by using **_ceph config set_**.
