### ISSUE TITLE
hostnetwork support

### ISSUE THREAD

**Issue by hunter** [rook/rook#561]
We run some of our Ceph clusters in K8s with `hostNetwork`ing enabled to allow easier access to Ceph from external services along with faster network performance. With Kube 1.6 the `ClusterFirstWithHostNet` has been added to make it slightly easier to handle DNS lookups for hostNetworking.

Is this something to be supported in Rook?

**Comment by kokhang** [comment]
Hi @hunter, using `ClusterFirstWithHostNet` is something that i was going to experiment but instead im started working on a external Rook volume provisioner for Rook v0.4 (https://github.com/rook/rook/issues/538). With this provisioner, the monitor IPs would be discoverable by the operator and you would not need to rely on DNS lookups for the ceph mons.

**Comment by hunter** [comment]
The external provisioner will be a great addition :)

I do think a `hostNetwork` option will be a useful addition even with a new provisioner. Performance is pretty critical for running a stable production ceph cluster. I'd submit a patch but I'm not sure my Go knowledge is up to the task :)

**Comment by kokhang** [comment]
@hunter Apart from accessing the Ceph mons from external services, what other benefits would`hostNetwork` provide? Wouldnt a service with type loadbalancer or NodePort grant ceph access to the external services? I just want to understand the use case better and how it helps with performance :)

**Comment by bzub** [comment]
Unfortunately Ceph clients don't like to talk to Mons through a proxy.  If the destination IP doesn't match the Mon's real IP it will fail, at least when I tried using the kernel RBD client this way.  So it seems the only options are `hostNetwork`, or Pod IPs that are routable from outside of the cluster.

Overlay network performance is something that interests me but I haven't looked into it.  I'd love to see a comparison between Flannel, Calico, and no overlay.

**Comment by kokhang** [comment]
@bzub I got it to work using a headless service. The only issue was that the DNS name was not resolvable from the host. This should change with `ClusterFirstWithHostNet` in 1.6 as @hunter mentioned but i havent tried it. I mentioned this back a while ago in https://github.com/rook/rook/issues/355#issuecomment-283753241.

**Comment by bzub** [comment]
Oh right I forgot about a headless service. The pod IPs would still need to be routable outside the cluster unless I'm forgetting something else.

**Comment by bzub** [comment]
On gitter @TimJones brought up this use-case for hostNetwork support:
> I have a Ceph cluster on 3 bare-metal nodes, each with 2x1GbE and 2x10GbE. The 1GbE are for admin\service networks, and the 10GbE are for Ceph (public & cluster networks) and I would like Rook to be able to replicate the same using the dedicated links for cluster access and replication.

This could possibly be accomplished via Services that specify ExternalIPs, possibly as well.

**Comment by hunter** [comment]
Just looping back on this. We have a similar requirement to @TimJones.

Is it too hard/late to get something like this into 0.5?

**Comment by travisn** [comment]
@hunter I wonder if #806 will get us most of the way with this. With that change, there is now a stable ip address for monitors via a k8s service. The mon service looks like below. When `ClusterFirstWithHostNet` is enabled, would the ClusterIP on the service be the host ip? If that's the case, I think we're there.

```
$ kn get svc rook-ceph-mon0 -o yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-ceph-mon
    mon: rook-ceph-mon0
    mon_cluster: rook
  name: rook-ceph-mon0
  namespace: rook
spec:
  clusterIP: 10.3.0.232
  ports:
  - name: rook-ceph-mon0
    port: 6790
    protocol: TCP
    targetPort: 6790
  selector:
    app: rook-ceph-mon
    mon: rook-ceph-mon0
    mon_cluster: rook
  sessionAffinity: None
  type: ClusterIP
```

**Comment by hunter** [comment]
It’s definitely a move in the right direction but for our current implementation (with ceph-docker) we need to be able to avoid the overhead of the Kube network and run on a separate bonded network

**Comment by travisn** [comment]
Got it, it's about the host network. Perhaps if we added a setting `hostNetwork: true` in the rook-cluster.yaml, then the operator could coordinate:
- `hostNetwork: true` on all the pods 
- `ClusterFirstWithHostNet` for dns
- The mons would use the host ip instead of a service ip

**Comment by hunter** [comment]
Great!! Something very similar is done with ceph-docker. We found a few headaches with hostnames not matching pod name and monmaps/services but I think #806 will make a big difference there

**Comment by hunter** [comment]
Is it possible to bump this into 0.6? We'll try to contribute if we can get some spare cycles. For now we can't do any production hardware testing until we can run on the hostNetwork.

**Comment by bassam** [comment]
this would be a good addition to 0.6. @hunter do you think you can help with the implementation?

**Comment by hunter** [comment]
Our team is pretty busy but I'll see what can be done to help!

**Comment by galexrt** [comment]
Has anyone worked on adding `hostNetwork` feature? I have some time to try to add this.

**Comment by bassam** [comment]
@galexrt that would be awesome. its much needed!

**Comment by galexrt** [comment]
https://github.com/rook/rook/pull/975
As written in the PR, I couldn't test it yet. I'll try to upload a version to my Docker namespace, so anyone can test it :)

**Comment by galexrt** [comment]
The `hostNetwork` feature has now been implemented in https://github.com/rook/rook/pull/975.

***

Closed by https://github.com/rook/rook/pull/975.
