### ISSUE TITLE
Device and Crushmap management for common scenarios

### ISSUE THREAD

**Issue by hunter** [rook/rook#562]
With #520 landing, it got me thinking if there is a way to handling the most common use cases for devices, crushmaps and config.

Outside of journaling, SSDs are added as either a cache tier layer or as a performance pool. Managing crushmaps becomes a difficult task with dual roots and/or mixed nodes so there may be some benefit in abstracting some of that configuration away. Specifying the `type` of device (in storeconfig?) which would automatically create a hdd/ssd crushmap, adjust weights, tweak journaling, inject config, etc and allow simpler support for different devices without hacking crush locations/maps.

NVMe devices also may benefit for some additional configuration to the config. Intel has some useful [documentation](http://tracker.ceph.com/projects/ceph/wiki/Tuning_for_All_Flash_Deployments) around that.

This does make the config a little more opinionated but does make it a little easier to utilise mixed disk environments. Thoughts?

**Comment by bzub** [comment]
Is 520 the PR you meant to link?  Seems irrelevant.

I agree it would be great to use the information Rook collects about nodes and storage to help automate these things.  It seems to be so useful but has never been done with vanilla Ceph.

With a "DataPolicy" concept common scenarios like these could be pre-defined for users or shared easily, and specific settings overridden if needed.  Let me know your thoughts on my [DataPolicy proposal](https://gist.github.com/bzub/5d5f3cd06c6abf57dedbfdbaf5d33080) in this context.  You've given me the idea to add configurable weights for OSDs at least.

Also for reference, the [Storage Configuration Design](https://github.com/rook/rook/wiki/Storage-Configuration-Design) proposal.

**Comment by bzub** [comment]
With a concrete storage configuration definition in place, this would also pave the road for interactively configuring storage nodes and endpoints.  Via CLI or Web UI for example.  Exciting!

**Comment by jbw976** [comment]
Absolutely @hunter, I think this is a great idea.  Being able to separate out your storage resources for performance pools as well as pools with other characteristics is definitely in the top set of things I want to work on for v0.5.  While trying to finish off v0.4, I have not gotten back to updating the [Storage Configuration Design](https://github.com/rook/rook/wiki/Storage-Configuration-Design) proposal with all the latest thinking, but this along with @bzub's storage/data policies work and https://github.com/rook/rook/issues/397#issuecomment-289156161 are all on my list.

I hope by next week I'll be back to updating the proposal to encompass all of this thinking.  Thanks a lot for contributing your ideas, they are very valuable to the rook roadmap and upcoming milestones...

**Comment by patrickstjohn** [comment]
+1 Here, we're attempting to introduce rack aware failure domains for our deployment. It would be wonderful if rook handled this based on node labels that we could apply giving the system awareness of the topology. Something like the following:

```
kubectl label nodes node1  rook.io/rack=rack1
```

Currently, doing this manually for erasure coded shared filesystem and a replicated block pool and it would be great if rook handled those cases as seamlessly as osd/host failure domains.
