### ISSUE TITLE
Add option to enable stats during pool creation

### ISSUE THREAD

**Issue by umangachapagain** [rook/rook#5624]
**Is this a bug report or feature request?**
* Feature Request

**Background**
Retrieved from https://docs.ceph.com/docs/master/mgr/prometheus/#rbd-io-statistics

Prometheus module can optionally collect RBD per-image IO statistics by enabling dynamic OSD performance counters. The statistics are gathered for all images in the pools that are specified in the `mgr/prometheus/rbd_stats_pools` configuration parameter. The parameter is a comma or space separated list of `pool[/namespace]` entries. If the namespace is not specified the statistics are collected for all namespaces in the pool.

`ceph config set mgr mgr/prometheus/rbd_stats_pools "pool1,pool2,poolN"`

The module makes the list of all available images scanning the specified pools and namespaces and refreshes it periodically. The period is configurable via the `mgr/prometheus/rbd_stats_pools_refresh_interval` parameter (in sec) and is **300 sec (5 minutes) by default**. The module will force refresh earlier if it detects statistics from a previously unknown RBD image.

`ceph config set mgr mgr/prometheus/rbd_stats_pools_refresh_interval 600`

**What should the feature do:**
We should add an option to enable/disable collection of statistics per pool. Additionally, we should also make the refresh interval configurable.

For the former, we can add
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  ...
spec:
  enableRBDStats: true
  ...
```
Based on whether it is `true` or `false` we need to add or remove the pool from `rbd_stats_pools`.
We can **default to `false`** as we do not enable monitoring by default. Collecting stats from large number of pools could affect mgr performance and prometheus storage.

For the latter, we need to add a global config via Env Var in Deployment or Config Map like,
`RBD_STATS_POOLS_REFRESH_INTERVAL: 600`

**What is use case behind this feature:**
To enable collection of IO statistics per image and export to Prometheus.

**Environment**:

K8s/OpenShift using Block Pools and Monitoring enabled.

**Comment by leseb** [comment]
> The pool CR setting looks good. The default should just be false.
> 
> ```
> spec:
>   enableRBDStats: false
> ```
> 
> The refresh interval is a detailed setting. I would recommend that we don't expose it as a setting in Rook. If someone really wants to change the interval they can set it in the toolbox or else through the ceph config overrides. But if we decide it really is a common scenario to change the refresh interval, it should be a setting in the cluster CR.
> 
> > IIUC, this list can have pools configured already, and the append does not look trivial. We need to retrieve the existing pools and add our pool. Then more pools could be added (manually) by the admin, which leaves our pool in the middle of others. The tricky thing is during removal if we edit the CR and set enableRBDStats: false, we need to get the whole list of pools, remove ours and reply to the command.
> 
> @leseb To keep this simple, what about this proposal?
> 
> * If all pool CRs have this setting to false, Rook would never update the setting for rbd stats
> * If any pool CR sets the rbd stats to true, Rook would overwrite the setting to exactly the list of pools that have it set to true.

> 
> If the admin wants to specify a custom list, they would never set the pool CR value to true.

I guess I was thinking about a weird corner case with an external cluster scenario.
The current proposal looks good to me.

**Comment by umangachapagain** [comment]
> The refresh interval is a detailed setting. I would recommend that we don't expose it as a setting in Rook. If someone really wants to change the interval they can set it in the toolbox or else through the ceph config overrides. But if we decide it really is a common scenario to change the refresh interval, it should be a setting in the cluster CR.
>
Not all users will have access to toolbox.
ceph config overrides vs setting in cluster CR. Which one makes more sense?

I'm not very sure about a setting in Cluster CR.

We should probably allow setting interval because on clusters with large number of rbd images, stats collection could impact `mgr` and prometheus storage. Being able to set a larger interval should be a little better than the default.

**Comment by travisn** [comment]
> > The refresh interval is a detailed setting. I would recommend that we don't expose it as a setting in Rook. If someone really wants to change the interval they can set it in the toolbox or else through the ceph config overrides. But if we decide it really is a common scenario to change the refresh interval, it should be a setting in the cluster CR.
> 
> Not all users will have access to toolbox.
> ceph config overrides vs setting in cluster CR. Which one makes more sense?
> 
> I'm not very sure about a setting in Cluster CR.
> 
> We should probably allow setting interval because on clusters with large number of rbd images, stats collection could impact `mgr` and prometheus storage. Being able to set a larger interval should be a little better than the default.

I just want to be clear about whether it is a common enough scenario to change the default before exposing this in the cluster CR. It doesn't seem common enough to me. But we could always add it later if the community asks for it.
