### ISSUE TITLE
Got a ceph bug MDS_CLIENT_LATE_RELEASE and cluster status in WARN，Can I upgrade my rook?

### ISSUE THREAD

**Issue by tarjintor** [rook/rook#5641]
My ceph cluster is in HEALTH_WARN for
`    MDS_CLIENT_LATE_RELEASE: 1 clients failing to respond to capability release `
I got some bug ceph itself,and do some search

https://tracker.ceph.com/issues/18798

https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/6DHM7RPPMYZHGQFEAMFWDY2J3QOPTP37/

It seems the only thing I can do is upgrade my ceph cluster and fix this bug

But as I read from doc

rook upgrade need cluster health in OK status，but if I can't upgrade cluster for it's in HEALTH_WARN，how can I fix this bug?

**Comment by travisn** [comment]
@tarjintor A health warning actually does not block the upgrades. Only a health error blocks the upgrade. But if you have a health error you can allow the upgrade to proceed by setting [skipUpgradeChecks: true](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L34-L38)
