### ISSUE TITLE
After the rook CEPH redeployment, how can realize that my original data /dev/sdb will not be lost

### ISSUE THREAD

**Issue by ijackcy** [rook/rook#5648]
I have deployed the Rook CEPH on three nodes. Each node has a hard disk / dev / SDB. The Rook CEPH works normally, and NFS and object storage work normally.

After a while, my k8s cluster failed and I had to redeploy my k8s cluster.

When I deploy k8s again, my original Rook CEPH namespace is deleted. I redeploy rook CEPH. I follow rook.io Official website. In order to configure the Ceph storage cluster, at least one of these local storage options are required:

1、Raw devices (no partitions or formatted filesystems)
2、Raw partitions (no formatted filesystem)
3、PVs available from a storage class in block mode

After redeployment, the data on the original hard disk is lost. What should I do？After the rook CEPH redeployment, how can realize that my original data will not be lost

**Comment by travisn** [comment]
@ijackcy If the original data on the hard disk is lost, Rook cannot recover the cluster. But if the data on disk is not lost, you can attempt to recover it by following the [disaster recovery guide](https://rook.github.io/docs/rook/v1.3/ceph-disaster-recovery.html#adopt-an-existing-rook-ceph-cluster-into-a-new-kubernetes-cluster).

**Comment by travisn** [comment]
Closing since there is not a rook issue reported. For more questions, you can join the [Rook Slack](https://slack.rook.io) as well.
