### ISSUE TITLE
Disaster Recovery Procedure "Adopt an existing Rook Ceph cluster into a new Kubernetes cluster" does not work

### ISSUE THREAD

**Issue by sebschlue** [rook/rook#5649]
I have set up a Test Kubernetes Cluster with 3 nodes and a Test Rook-Ceph Cluster v.1.3.5 with 3 nodes and 1 block device per node (3 OSDs).

Then I have tried to simulate a Kubernetes Cluster Failure by completely removing the Kubernetes Cluster and reinstalling it from scratch and then following the procedure "Adopt an existing Rook Ceph cluster into a new Kubernetes cluster" at https://rook.io/docs/rook/v1.3/ceph-disaster-recovery.html

I currently believe that this procedure does not work, at least not exactly as described, it may have worked at some time in the past but it seems that it currently does no longer work this way, maybe additional steps are required. But unfortunately, I am not knowledgeable enough to get it to a working state. I have tried some slight variations like using v1 and v2 addresses for "monmaptool --add" in step 14.4 and deleting deployments as well as daemonsets in step 12 but I was not able to do a successful disaster recovery.

Following the procedure seems to work fine until steps 17-19 where the cluster is resurrected the first time. rook-ceph-operator pod starts and creates the following deployments and daemonsets:

```
[root@node1 ~]# kubectl -n rook-ceph get deployments,daemonsets
NAME                                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/rook-ceph-tools                              1/1     1            1           87m
deployment.apps/rook-ceph-operator                           1/1     1            1           92m
deployment.apps/csi-cephfsplugin-provisioner                 2/2     2            2           18m
deployment.apps/csi-rbdplugin-provisioner                    2/2     2            2           18m
deployment.apps/rook-ceph-mon-b                              1/1     1            1           17m
deployment.apps/rook-ceph-crashcollector-node1.localdomain   1/1     1            1           17m
deployment.apps/rook-ceph-mon-c                              1/1     1            1           17m
deployment.apps/rook-ceph-crashcollector-node3.localdomain   1/1     1            1           17m
deployment.apps/rook-ceph-mon-a                              1/1     1            1           17m
deployment.apps/rook-ceph-crashcollector-node2.localdomain   1/1     1            1           17m

NAME                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/rook-discover      3         3         3       3            3           <none>          18m
daemonset.apps/csi-rbdplugin      3         3         3       3            3           <none>          18m
daemonset.apps/csi-cephfsplugin   3         3         3       3            3           <none>          18m
```

But then the resurrection process gets stuck, no "prepare-osd" stage is performed and no OSD pods are being created/started.

rook-ceph-operator logs the following errors (duplicate messages removed for readability):

````
[root@node1 ~]# kubectl -n rook-ceph logs deployment.apps/rook-ceph-operator | grep " E "

2020-06-12 15:49:03.720836 E | op-cluster: failed to get ceph daemons versions. failed to run 'ceph versions: exit status 1

2020-06-12 15:49:13.295845 E | ceph-spec: "ceph-file-controller": ceph command error failed to get status. timed out

2020-06-12 15:49:51.473786 E | ceph-crashcollector-controller: node reconcile failed on op "unchanged": Operation cannot be fulfilled on deployments.apps "rook-ceph-crashcollector-node2.localdomain": the object has been modified; please apply your changes to the latest version and try again

2020-06-12 15:59:50.960265 E | op-cluster: failed to create cluster in namespace "rook-ceph". failed to start the mons: failed to start mon pods: failed to check mon quorum a: failed to wait for mon quorum: exceeded max retry count waiting for monitors to reach quorum

````

I don't know if these logs are particularly helpful but maybe this is already a known issue or maybe somebody can provide a working disaster recovery procedure.

**Comment by sebschlue** [comment]
I have successfully tested some other variant but it requires backup copies of /var/lib/rook of all nodes as well as backups of k8s configmaps, secrets and services in rook-ceph namespace.

1) create fresh k8s cluster

2) install rook-ceph

kubectl apply -f rook/cluster/examples/kubernetes/ceph/common.yaml
kubectl apply -f rook/cluster/examples/kubernetes/ceph/operator.yaml
kubectl apply -f rook/cluster/examples/kubernetes/ceph/cluster.yaml
kubectl apply -f rook/cluster/examples/kubernetes/ceph/toolbox.yaml

No OSDs will be created.

3)

scale deployment rook-ceph-operator to 0

delete all deployments and daemonsets from rook-ceph namespace except rook-ceph-operator and rook-ceph-tools

4) 

restore configmaps, secrets and services from backup. configmaps and secrets can be "patched", services must be deleted and re-created because the cluster-ip field is immutable.

5)

restore /var/lib/rook on all nodes from backups


6)

scale deployment rook-ceph-operator to 1

Now, OSDs will be created.

Check cluster health via "ceph status".


7) 

install additional stuff like

kubectl apply -f rook/cluster/examples/kubernetes/ceph/filesystem.yaml
kubectl apply -f rook/cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml




Although is procedure requires more ahead-of-time-preparation because of requirement for the saved k8s object definitions, it has the following advantages:

- you do no need to adjust anything using monmaptool
- you do not need to start with a single Mon first
- you do not need to start with authentication disabled first



Nevertheless, it would still be interesting to also have a working procedure like the one described in https://rook.io/docs/rook/v1.3/ceph-disaster-recovery.html where I still believe that it does not work as described.

**Comment by caffeinism** [comment]
I'm a beginner user of rook who had no knowledge of ceph, but had been struggling for about 3 weeks to get around and solve this problem. There was only one problem with that document. That is, port 3300 for using MESSENGER V2 is not added to monmap. (WTF!!) The rook-ceph-operator seems to check if the quorum is formed by accessing it using 3300 ports.

Therefore, if you fix part of commands in document
`monmaptool --add a 10.77.2.216:6789 monmap`
like
`monmaptool --addv a [v2:10.77.2.216:3300,v1:10.77.2.216:6789] monmap`
it works well.
