### ISSUE TITLE
Rook does not set ceph orchestrator backend

### ISSUE THREAD

**Issue by shaas** [rook/rook#5652]
Rook automatically sets itself as backend for the ceph orchestrator.

Ceph changed the way how to set the backend in the Octopus release.
It seems that the code block which is responsible for choosing the correct way to configure the ceph orchestrator backend according to the ceph version does not work correctly.

See
https://github.com/rook/rook/blob/3d8fd2ca5adb2db383d05790a31ac977b712eaa1/pkg/operator/ceph/cluster/mgr/orchestrator.go#L54

**Comment by travisn** [comment]
@shaas What is not working or what is the expected command? 

For Octopus or newer Rook is calling:
```
ceph orch set backend rook
```
instead of this for nautilus:
```
ceph orchestrator set backend rook
```

**Comment by bdowling** [comment]
Came here trying to see if I needed to do something in the helm charts to enable this by default.  Is this still a bug?

I built out a new cluster with the v1.13.4 helm charts and the orchestrator was not set.  I noticed this when i went to the dashboard and could not see a number of data elements, the dashboard kindly pointed me to the docs.

```
bash-4.4$ ceph orch status
Error ENOENT: No orchestrator configured (try `ceph orch set backend`)
bash-4.4$ ceph mgr module enable rook
bash-4.4$ ceph orch set backend rook
bash-4.4$ ceph orch status
Backend: rook
Available: Yes
bash-4.4$ ceph orch status
Backend: rook
Available: Yes
```
