### ISSUE TITLE
Raise alarm when not enough monitors are running

### ISSUE THREAD

**Issue by ibotty** [rook/rook#5654]
I configured rook to export metrics and alerts to prometheus as in
 https://rook.io/docs/rook/v1.3/ceph-monitoring.html#prometheus-alerts

I happened to encounter #5644.  This led me with only two monitors running.  Unfortunately I only noticed by chance that was a potential problem.  I did not get any alert.

**Comment by galexrt** [comment]
To note the Prometheus Rules for Ceph contain a `CephMonQuorumAtRisk` alert when the quorum is at risk, e.g., 2 mons running instead of 3.

See https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml#L76-L86

**Comment by ibotty** [comment]
This did not fire when rook decided to only let two monitors running (#5644).  It might be useful to generate the alerting rule dynamically and set the desired mon count to the cluster's configured number.
