### ISSUE TITLE
Allow setting tolerations on Ceph version detection job

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#5659]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The detect job doesn't allow setting tolerations. Thus it can not start on a cluster with all nodes tainted. 

**Expected behavior:**
Detect job should support same tolerations either as operator or as mon pods.

**How to reproduce it (minimal and precise):**

Taint all nodes
Start a cluster
See the version job will be pending indefinitely if all the nodes are tained.

Refer the existing ticket: https://github.com/rook/rook/issues/3976

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.3.5
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.9
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@yanchicago The tolerations from the mon placement are supposed to be applied on [this line](https://github.com/rook/rook/blob/1ea73ce1233fcaa4a1b5518967eef2dcbd0cade6/pkg/operator/ceph/cluster/version.go#L134). Did you already try the mon tolerations?

**Comment by rahulchheda** [comment]
Is this issue up for grabs, would like to contribute to it!

**Comment by travisn** [comment]
@rahulchheda Sounds good if you could investigate if a fix is needed based on my previous comment.

**Comment by rahulchheda** [comment]
Seems like tolerations are added, let me check what is missing.
Looking into it @travisn
