### ISSUE TITLE
Unable to mount volume - found errors on device but could not correct them

### ISSUE THREAD

**Issue by schnes4** [rook/rook#5665]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Volume could not be mounted although ceph status is clear.

Ceph satus message:
```
cluster:
    id:     b2524770-5277-4c29-87a2-4bce97bda9b9
    health: HEALTH_WARN
            15 daemons have recently crashed

  services:
    mon: 3 daemons, quorum f,h,j (age 4h)
    mgr: a(active, since 15h)
    osd: 3 osds: 3 up (since 15h), 3 in (since 15h)

  data:
    pools:   1 pools, 32 pgs
    objects: 38.96k objects, 148 GiB
    usage:   445 GiB used, 2.5 TiB / 2.9 TiB avail
    pgs:     32 active+clean

  io:
    client:   243 KiB/s wr, 0 op/s rd, 3 op/s wr
```

Ceph OSD status message:
```
+----+------------+-------+-------+--------+---------+--------+---------+-----------+
| id |    host    |  used | avail | wr ops | wr data | rd ops | rd data |   state   |
+----+------------+-------+-------+--------+---------+--------+---------+-----------+
| 0  | dev-k8s-w3 |  148G |  858G |    0   |  2457   |    1   |     0   | exists,up |
| 3  | dev-k8s-w1 |  148G |  858G |    0   |  2457   |    1   |     0   | exists,up |
| 4  | dev-k8s-w2 |  148G |  858G |    0   |  4915   |    0   |     0   | exists,up |
+----+------------+-------+-------+--------+---------+--------+---------+-----------+

``` 
Logs from pod which should mount the volume:
```
Events:
  Type     Reason       Age                From                 Message
  ----     ------       ----               ----                 -------
  Normal   Scheduled    <unknown>          default-scheduler    Successfully assigned sw-hc-jira/jira-software-0 to dev-k8s-w1
  Warning  FailedMount  16m                kubelet, dev-k8s-w1  Unable to attach or mount volumes: unmounted volumes=[jira-data-ceph], unattached volumes=[default-token-w48tl jira-data-ceph]: timed out waiting for the condition
  Warning  FailedMount  97s (x9 over 18m)  kubelet, dev-k8s-w1  MountVolume.MountDevice failed for volume "pvc-fb18b8a1-ec90-47cf-b7ee-081d06364a6c" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/rbd7 but could not correct them: fsck from util-linux 2.23.2
/dev/rbd7: Superblock needs_recovery flag is clear, but journal has data.
/dev/rbd7: Run journal anyway

/dev/rbd7: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
           (i.e., without -a or -p options)
  Warning  FailedMount  52s (x7 over 14m)  kubelet, dev-k8s-w1  Unable to attach or mount volumes: unmounted volumes=[jira-data-ceph], unattached volumes=[jira-data-ceph default-token-w48tl]: timed out waiting for the condition
```

**Expected behavior:**
Pod should mount volume without errors.

**Environment**:
* OS (e.g. from /etc/os-release): 
`Debian GNU/Linux 10 (buster)`
* Kernel (e.g. `uname -a`): 
`Linux dev-k8s-w1 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`
* Rook version (use `rook version` inside of a Rook Pod): 
`rook: v1.3.1`
* Storage backend version (e.g. for ceph do `ceph -v`): 
`ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)`
* Kubernetes version (use `kubectl version`): 
`Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T20:56:50Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): 
`HEALTH_WARN 15 daemons have recently crashed`

**Comment by galexrt** [comment]
@schnes4 The issue seems to be that the volume that is being mounted has gotten "corrupted" and needs a manual `fsck` run.
A volume being "corrupted" can happen due to many various scenarios, e.g., node power loss causing the fs to be in an "corrupted" state, which it can recover from in some cases but not in all if you are unlucky and other similiar ones.

To resolve the issue try to scale down the application (so that the volume is not being (tried to be) mounted on a node anymore) and then using the instructions here https://rook.io/docs/rook/v1.4/direct-tools.html to map the volume in the `direct-mount` tool Pod and then running `fsck` with the flags as needed on it to hopefully repair the FS on it.
