### ISSUE TITLE
Ceph: bump tools to Octopus image.

### ISSUE THREAD

**Issue by hansbogert** [rook/rook#5666]
**Is this a bug report or feature request?**
* Feature Request
bump the tools container to use ceph octopus images. 

**What should the feature do:**
Provide ceph cli tools for use with Octopus.

**What is use case behind this feature:**
That way my cli workflow can use Octopus functionality (which often still necessary e.g., rbd-mirror snapshotting functionality)

**Comment by travisn** [comment]
@hansbogert This is planned for v1.4 and will be merged to master soon with #5111.

**Comment by hansbogert** [comment]
Good to know! Thanks.
