### ISSUE TITLE
lifecycle rule dont work

### ISSUE THREAD

**Issue by mrmassis** [rook/rook#5676]
Hi,
Im trying setting a expiration days in a bucket. But i havent success. How i could set the retation day lifecycle in a buket?
Im using the cmd:
$ s3cmd expire s3://expiration --expiry-days 1

When i look to the lifecycle all look good
$ s3cmd getlifecycle  s3://expiration
<?xml version="1.0" ?>
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
        <Rule>
                <ID>6b3u6v4oxtfo9eduutn705dck68amv5f28jk6e86d8vpv65i</ID>
                <Prefix/>
                <Status>Enabled</Status>
                <Expiration>
                        <Days>1</Days>
                </Expiration>
        </Rule>
</LifecycleConfiguration>

But when i look to the file inside the bucker:
$  3cmd info s3://expiration/test.txt
s3://expiration/test.txt (object):
   File size: 8
   Last mod:  Thu, 18 Jun 2020 20:59:46 GMT
   MIME type: text/plain
   Storage:   STANDARD
   MD5 sum:   8f8d58b2a4c6620601186c564bc967f2
   SSE:       none
   Policy:    none
   CORS:      none
   ACL:       mrmassis: FULL_CONTROL
   x-amz-meta-s3cmd-attrs: atime:1592502058/ctime:1592502050/gid:0/gname:root/md5:8f8d58b2a4c6620601186c564bc967f2/mode:33188/mtime:1592502050/uid:0/uname:root
I cant find expiration tag. Where i have wrong. Iim used the rook-ceph master

**Comment by thotz** [comment]
@mrmassis , i have never tried lifecycle. But check it from radosgw-admin cli from ceph tool box
`radosgw-admin lc get/list`

**Comment by djhoese** [comment]
@mrmassis Did you ever get this to work as you expected? Did the expiration end up working/deleting your objects eventually?

**Comment by Raven888888** [comment]
Same, is it working?

**Comment by djhoese** [comment]
I've ended up using `aws s3api` with `put-bucket-lifecycle` with a JSON lifecycle configuration and it seems to be working for my installation.

**Comment by Raven888888** [comment]
Does it work on `object` level too?

**Comment by djhoese** [comment]
Not sure what you mean. The lifecycle configurations are defined by prefix...at least how I've used them:

```json
{
  "Rules": [
    {
      "Expiration": {
        "Days": 1
      },
      "Prefix": "geotiffs/",
      "Status": "Enabled"
    },
    {
      "Expiration": {
        "Days": 1
      },
      "Prefix": "netcdfs/",
      "Status": "Enabled"
    }
  ]
}
```
