### ISSUE TITLE
Move cephcsi snapshot from Alpha to Beta

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#5699]
kubernetes-csi supports snapshotter beta in kubernetes v.1.17 onwards.

The change from v1alpha1 to v1beta1 snapshot APIs is not backward compatible.

If you have already deployed v1alpha1 snapshot APIs and external-snapshotter sidecar controller and want to upgrade to v1beta1, you need to do the following:

* Delete volume snapshots created using v1alpha1 snapshot CRDs and external-snapshotter sidecar controller.
* Uninstall v1alpha1 snapshot CRDs, external-snapshotter sidecar controller
* Install v1beta1 snapshot CRDs, snapshot controller ( This has to be done by kubernetes distributor)

**Comment by Madhu-1** [comment]
cc @travisn

**Comment by tdmanv** [comment]
Hi @Madhu-1, thanks for all your work on this.

Quick Question: Is there a rough timeline for v1beta1 support? How long until 3.0.0 is released?

Thanks!

**Comment by Madhu-1** [comment]
> Hi @Madhu-1, thanks for all your work on this.
> 
> Quick Question: Is there a rough timeline for v1beta1 support? How long until 3.0.0 is released?
> 
> Thanks!

it will be part of rook 1.4 release

**Comment by travisn** [comment]
Closing since this was completed with #5686.

**Comment by tdmanv** [comment]
> > Hi @Madhu-1, thanks for all your work on this.
> > Quick Question: Is there a rough timeline for v1beta1 support? How long until 3.0.0 is released?
> > Thanks!
> 
> it will be part of rook 1.4 release

Thanks!
