### ISSUE TITLE
Cannot access rook-ceph-mgr-dashboard externally in OKD 4

### ISSUE THREAD

**Issue by khodayard** [rook/rook#5705]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When I expose the rook-ceph-mgr-dashboard in openshift I cannot access the dashboard via a web browser.
It returns a 504 gateway error.

**Expected behavior:**

To open the dashboard normally.

**How to reproduce it (minimal and precise):**

Just install rook on an OKD 4 in try to access the dashboard externally. Dashboard is fine internally, I can access it via a NodePort service, but it does not work externally as a route.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 I've tried it on two instances of the cluster and that was just the same.

**Environment**:
* OS (e.g. from /etc/os-release): FCOS 31
* Kernel (e.g. `uname -a`): 5.6.13-200.fc31.x86_64
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.3.0-beta.0.429.gc143bdb
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.9 (....) nautilus (stable)
* Kubernetes version (use `kubectl version`): Major:"1", Minor:"17+", GitVersion:"v1.17.1"
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OKD 4.4.0-0.okd-2020-05-23-055148-beta5
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] HEALTH_OK (https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@khodayard There are several different ways to expose the routes depending on the environment. What about the [ingress controller](https://rook.github.io/docs/rook/v1.3/ceph-dashboard.html#ingress-controller)?

**Comment by khodayard** [comment]
Hi Travis, yes I've seen it but I'd need to install both "nginx Ingress Controller" and "cert-manager", isn't there a simpler way to do that on openshift (e.g. a simple route)?
Honestly I don't know if this is a bug or a feature request :D

**Comment by khodayard** [comment]
Now I think it's a but, cause deploying "nginx ingress controller" over OpenShift or OKD is not possible because of security restrictions in OpenShift:


[root@okd4-services ~]# kubectl get events -n ingress-nginx 
LAST SEEN   TYPE      REASON              OBJECT                                           MESSAGE
16m         Warning   FailedCreate        job/ingress-nginx-admission-create               Error creating: pods "ingress-nginx-admission-create-" is forbidden: error looking up service account ingress-nginx/ingress-nginx-admission: serviceaccount "ingress-nginx-admission" not found
3m51s       Warning   FailedCreate        job/ingress-nginx-admission-create               Error creating: pods "ingress-nginx-admission-create-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 2000: must be in the ranges: [1000600000, 1000609999]]
16m         Warning   FailedCreate        job/ingress-nginx-admission-patch                Error creating: pods "ingress-nginx-admission-patch-" is forbidden: error looking up service account ingress-nginx/ingress-nginx-admission: serviceaccount "ingress-nginx-admission" not found
3m51s       Warning   FailedCreate        job/ingress-nginx-admission-patch                Error creating: pods "ingress-nginx-admission-patch-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 2000: must be in the ranges: [1000600000, 1000609999]]
3m51s       Warning   FailedCreate        replicaset/ingress-nginx-controller-58f68f5ccc   Error creating: pods "ingress-nginx-controller-58f68f5ccc-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 101: must be in the ranges: [1000600000, 1000609999] capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added]
16m         Normal    ScalingReplicaSet   deployment/ingress-nginx-controller              Scaled up replica set ingress-nginx-controller-58f68f5ccc to 1
[root@okd4-services ~]# 


So we should have an alternative way for OpenShift, in other words there's no way to access rook ceph dashboard externally when it's deployed over OpenShift or OKD and no LoadBalancer is available.
