### ISSUE TITLE
Add mon connection info to the user CRD

### ISSUE THREAD

**Issue by leseb** [rook/rook#5706]
So that when we create a CephUser CR we not only have the cephx user but also the monitor endpoint.
The goal is to consume the cluster with librados.

**Comment by travisn** [comment]
Is this referring to the CephClient CR? Why would the mon endpoints need to be duplicated to the CephClient CR? They can already be found separately in a configmap if needed. But if the client only has access to the CR, then this would certainly simplify things for the client.

**Comment by leseb** [comment]
Yes, I'm referring to the CephClient CRD. Yes, the endpoints are somehow available via an existing configmap but it's not straightforward.
Yes, we can encode the connection as part of the Secret so all the required information is available from a single place.

Agreed, we need to be cautious with monmap changes, it's fairly easy to reconcile the Secret if the operator configmap changes now. That flow should be quite smooth to implement.
