### ISSUE TITLE
Mons and OSDs need ability to be configured offline

### ISSUE THREAD

**Issue by travisn** [rook/rook#5709]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
In disaster recovery scenarios or other disruptive, but rare, occasions when the Ceph daemons need to be repaired, their backing store may need to be repaired while offline. In particular, the mons and OSDs may have repair operations to be run.

A simple design that may accomplish the goal is the following:
- Add a new init container to each of the mon and osd daemon deployments
- The init container will be a no-op for the common case
- If a certain variable is defined (perhaps a value in a configmap indicating that offline mode is needed), the init container will sleep infinitely.
- The admin can connect to the init container and access the same container environment as the daemon, but the daemon will not be running.
- When the admin is done with the offline configuration, they would unset the variable and restart the daemon pod.
- The pod would start normally

**Comment by jdurgin** [comment]
The design sounds good. It would be useful to be able to specify the image used for the init container separately as well, in case additional changes to the recovery tool are needed (e.g. accounting for a new situation to recover from without updating the rest of the cluster). I'm not sure if that implies any changes, or if that would already be possible.

**Comment by leseb** [comment]
I think this can be dealt with a `kubectl edit`? I had opened this one long ago https://github.com/rook/rook/issues/2716. I do agree that it'd be nice though. Maybe not an init container but a condition on the main container so we get the exact same context. We could respond to a label on the deployment and then replace the main daemon cli with a `sleep infinity`.

**Comment by mridulv** [comment]
@travisn @leseb Can i start working on this item or what is the process around picking any item.

**Comment by mridulv** [comment]
I am planning to take the approach mentioned by @leseb which is essentially 

Going to have a args as follows:
```if [ ! -z "$DEBUG_ENV" ]; then;  sleep infinity; else; ceph osd .....; end;```

Let me know if this approach seems correct to you. If yes then i would like to proceed ahead and start implementing it.

**Comment by leseb** [comment]
> I am planning to take the approach mentioned by @leseb which is essentially
> 
> Going to have a args as follows:
> `if [ ! -z "$DEBUG_ENV" ]; then; sleep infinity; else; ceph osd .....; end;`
> and this `DEBUG_ENV` would be fulfilled by the `configMap`
> 
> Let me know if this approach seems correct to you. If yes then i would like to proceed ahead and start implementing it.

I don't think we need a CM for this. Just reading a label on the deployment should be sufficient, it's much simpler IMO.

**Comment by mridulv** [comment]
@leseb got it. Makes sense, would do appropriate changes. Thanks !!!

**Comment by mridulv** [comment]
Proceeding on this one this weekend.

**Comment by travisn** [comment]
The [krew plugin](https://github.com/rook/kubectl-rook-ceph) has a new option for `debug start <deployment>` to start a pod for running commands against an offline mon or osd daemon. More documentation to come...
