### ISSUE TITLE
CI is failing frequently to setup K8s before Rook integration tests are run on K8s 1.11

### ISSUE THREAD

**Issue by travisn** [rook/rook#5711]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The CI is frequently, but intermittently, failing during the kubeadm setup step, even before any of the rook integration tests run.

```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
error: unable to recognize "https://cloud.weave.works/k8s/net?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxMSIsIEdpdFZlcnNpb246InYxLjExLjEwIiwgR2l0Q29tbWl0OiI3YTU3OGZlYmUxNTVhNzM2Njc2N2FiY2U0MGQ4YTE2Nzk1YTk2MzcxIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxOS0wNS0wMVQwNDoxNDozOFoiLCBHb1ZlcnNpb246ImdvMS4xMC44IiwgQ29tcGlsZXI6ImdjIiwgUGxhdGZvcm06ImxpbnV4L2FtZDY0In0K": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused
wait for K8s master node to be Ready
The connection to the server localhost:8080 was refused - did you specify the right host or port?
.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
.
```

For example, see [this build](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-5708/runs/2/nodes/59/steps/132/log/?start=0). It seems independent of the version of K8s being installed.

**Expected behavior:**
CI should successfully and reliably setup k8s.

**Comment by travisn** [comment]
In a [failed log](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/PR-5703/runs/3/nodes/65/steps/144/log/?start=0), the relevant failures seem to be these:

```
gpg: no valid OpenPGP data found.
...
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
...
Reading package lists...
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB
E: The repository 'http://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.
...
sudo: kubeadm: command not found
cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
chown: cannot access '/home/ubuntu/admin.conf': No such file or directory
W0626 22:28:12.135583   17834 loader.go:223] Config not found: /home/ubuntu/admin.conf
error: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
W0626 22:28:12.175509   17844 loader.go:223] Config not found: /home/ubuntu/admin.conf
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
```

The version of kubernetes that it affects appears random. Some builds don't hit it on any versions, but others hit it on several versions.

**Comment by akraitman** [comment]
Hi @travisn, I did some changes related to the apt sources in the test image please try now

**Comment by satoru-takeuchi** [comment]
@akraitman I reran my PR's CI. However, this problem still happens.

https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-5703/4/pipeline/59#step-141-log-327

```console
...
sudo: kubeadm: command not found
...
```

**Comment by travisn** [comment]
Reopening since #5734 was for an unrelated change

**Comment by satoru-takeuchi** [comment]
I guess the version of kubernetes-cni is > 0.7.5 when installing kubelet, in the CI environment. If it's correct, this problem would be fixed by treating aws_1.11.x test as a special case. More precisely, we should use kubernetes-cni 0.7.5-00 in this test.

In aws_1.1[4-8].x test, we use kubelet that depends on kubernetes-cni ">=" 0.7.5. However, in aws_1.11.x test, we use kubelet depends on kubernetes-cni "=" 0.7.5. Hence the following command fails and causes `sudo: kubeadm: command not found
`.

https://github.com/rook/rook/blob/master/tests/scripts/kubeadm-install.sh#L50
```
sudo apt-get install -y kubelet="${KUBE_INSTALL_VERSION}" kubeadm="${KUBE_INSTALL_VERSION}" nfs-common
```

# The dependencies of the kubelets

```
$ apt show kubelet=1.11.10-00
Package: kubelet
Version: 1.11.10-00
Priority: optional
Section: misc
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Installed-Size: 163 MB
Depends: iptables (>= 1.4.21), kubernetes-cni (= 0.7.5), iproute2, socat, util-linux, mount, ebtables, ethtool, conntrack, init-system-helpers (>= 1.18~)
...
$ apt show kubelet=1.13.12-00
Package: kubelet
Version: 1.13.12-00
Priority: optional
Section: misc
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Installed-Size: 113 MB
Depends: iptables (>= 1.4.21), kubernetes-cni (>= 0.7.5), iproute2, socat, util-linux, mount, ebtables, ethtool, conntrack
Homepage: https://kubernetes.io
Download-Size: 19.2 MB
APT-Sources: http://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
Description: Kubernetes Node Agent
 The node agent of Kubernetes, the container cluster manager
...
```

**Comment by satoru-takeuchi** [comment]
Here is my assumption of what has happened recently.

1. Everything worked fine.
2. CI image was updated, it caused failures in many tests (I don't know what was wrong here).
3. kubeadm-install.sh was updated to avoid downgrading packages.
4. CI images was fallen back to the old one.
5. Only aws_1.11.x started to fail because of the reason I mentioned in the last comment.

**Comment by travisn** [comment]
> I guess the version of kubernetes-cni is > 0.7.5 when installing kubelet, in the CI environment. If it's correct, this problem would be fixed by treating aws_1.11.x test as a special case. More precisely, we should use kubernetes-cni 0.7.5-00 in this test.
> 
> In aws_1.1[4-8].x test, we use kubelet that depends on kubernetes-cni ">=" 0.7.5. However, in aws_1.11.x test, we use kubelet depends on kubernetes-cni "=" 0.7.5. Hence the following command fails and causes `sudo: kubeadm: command not found `.
> 
> https://github.com/rook/rook/blob/master/tests/scripts/kubeadm-install.sh#L50
> 
> ```
> sudo apt-get install -y kubelet="${KUBE_INSTALL_VERSION}" kubeadm="${KUBE_INSTALL_VERSION}" nfs-common
> ```

@satoru-takeuchi In the release-1.3 branch, we are still installing the 0.6.0 kubernetes-cni as seen [here](https://github.com/rook/rook/blob/release-1.3/tests/scripts/kubeadm-install.sh#L50). You are saying we should change this to be 0.7.5 instead? To test a fix, want to open a PR directly against the release-1.3 branch so we can test against 1.11 before merging? Then we can port it to master after we confirm it works in the release branch.

**Comment by satoru-takeuchi** [comment]
> In the release-1.3 branch, we are still installing the 0.6.0 kubernetes-cni as seen here.

Oh, I didn't know the release branches use its own test scripts. I'm not familiar with the detailed CI process.

It seems that the situation is the same in the release-1.3's one because it doesn't allow downgrading.

> You are saying we should change this to be 0.7.5 instead?

Yes.

> To test a fix, want to open a PR directly against the release-1.3 branch so we can test against 1.11 before merging? Then we can port it to master after we confirm it works in the release branch.

Thank you for letting me know. I'll try it.

**Comment by travisn** [comment]
The Jenkinsfile in the release branches is just updated to run against more versions of Kubernetes. In master, we keep it smaller for the main development.

**Comment by satoru-takeuchi** [comment]
I've tested my hypothesis and it succeeded.

https://github.com/rook/rook/pull/5765
https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-5765/1/pipeline/59

Although aws_1.14.x failed, it apparently isn't related to this PR.

I'll make a PR to master branch.

**Comment by travisn** [comment]
> I've tested my hypothesis and it succeeded.
> 
> #5765
> https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-5765/1/pipeline/59
> 
> Although aws_1.14.x failed, it apparently isn't related to this PR.
> 
> I'll make a PR to master branch.

Looks great! We can go ahead and merge it then
