### ISSUE TITLE
ceph: updating object user is not working

### ISSUE THREAD

**Issue by thotz** [rook/rook#5713]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After creating object store user if I need to update any of its CR's, change is not getting updated for the actual ceph user. Same applies for obc and I guess for realm, zones too
**Expected behavior:**
changes in CR need to reflect in user as well 
**How to reproduce it (minimal and precise):**

* create user via `kubectl create -f object-user.yaml`
* edit the object-user.yaml for CR changes
* now update CR via `kubectl apply -f object-user.yaml`

**Comment by travisn** [comment]
@thotz What can be changed? The display name of the user? I don't see another field that makes sense to change.
And can you list the fields you see editable for the obc, realm, and zones?

**Comment by thotz** [comment]
> @thotz What can be changed? The display name of the user? I don't see another field that makes sense to change.
> And can you list the fields you see editable for the obc, realm, and zones?

Currently it's only disp name, but I am planning to add bucket policy. Also imo it might good to provide a way to rotate the credentials as well.
For obc, I am planning to add quota and may be policy as well. Rest I am not sure

**Comment by travisn** [comment]
Ok makes sense. How about in this issue if we only track the editing of the object user CR for an updated display name? Then we can add bucket policy and other fields to this and other CRs each with a separate issue.

**Comment by leseb** [comment]
I don't see this a major use case to change the display name but I guess it does not hurt to implement this...
