### ISSUE TITLE
Update CRDs to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by ckotzbauer** [rook/rook#5714]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Update the CRDs to use `apiextensions.k8s.io/v1`, because `apiextensions.k8s.io/v1beta1` is deprecated since K8s 1.16 and will be removed in the next release (1.19).

**What is use case behind this feature:**
Ensure compatibility for the next K8s releases.

**Environment**:
-

**Comment by travisn** [comment]
According to [this comment](https://github.com/kubernetes/kubernetes/issues/82022#issuecomment-636872808), the removal of the v1beta1 apiextensions has been delayed until 1.22. To continue supporting older versions of K8s at least until then and as mentioned in #5552, we will old off on this change. This already seems covered by #5552, but feel free to reopen if I missed something.

**Comment by ckotzbauer** [comment]
Thanks for clarification. I didn't knew that the removal has been delayed and I didn't find #5552 which already covers this topic :+1:
