### ISSUE TITLE
How to enable Online File System Expansion

### ISSUE THREAD

**Issue by konvergence** [rook/rook#5716]
Hi,

the feature-gates ExpandInUsePersistentVolumes is true since kubernetes 1.15.

on this [blog ](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/#online-file-system-expansion) it seem that Ceph RBD  plugin support it.

Does Rook allow to Expand volume in used ?

Regards

**Comment by travisn** [comment]
Yes, you can expand the volumes. See [this topic](https://rook.github.io/docs/rook/v1.3/ceph-csi-drivers.html#dynamically-expand-volume).

**Comment by konvergence** [comment]
Sorry travisn. May be my request was enought clear.

I know how to do it. We need to restary the pod to trigger the file system expansion.

Mu request is : get we do it without restart the pod ?

The feature ExpandInUsePersistentVolumes is not for that ?
