### ISSUE TITLE
no rook-ceph-osd-* and rook-ceph-mgr-*

### ISSUE THREAD

**Issue by chunyingli** [rook/rook#5722]
use the example to create ceph
when i kubectl create f cluster-test.yaml , i get this
  kubectl -n rook-ceph get pods
NAME                                            READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-47mrf                          3/3     Running   0          52m
csi-cephfsplugin-provisioner-7469b99d4b-4697t   5/5     Running   0          52m
csi-cephfsplugin-provisioner-7469b99d4b-8f2sd   5/5     Running   0          52m
csi-rbdplugin-2thqr                             3/3     Running   0          52m
csi-rbdplugin-provisioner-865f4d8d-cq2h5        6/6     Running   0          52m
csi-rbdplugin-provisioner-865f4d8d-rbkpl        6/6     Running   0          52m
rook-ceph-mon-a-6fd4c6f8bd-f9zd4                1/1     Running   0          51m
rook-ceph-operator-5b6674cb6-h9nst              1/1     Running   0          52m
rook-discover-6wnhd                             1/1     Running   0          52m

this is no rook-ceph-osd-* and rook-ceph-mgr-*, and  roo-ceph logs is empty, i cannot know where is error,

just find a error when  kubectl -n rook-ceph logs rook-ceph-operator-5b6674cb6-h9nst

 E | op-cluster: failed to create cluster in namespace "rook-ceph". failed to start the mons: failed to start mon pods: failed to check mon quorum a: failed to wait for mon quorum: exceeded max retry count waiting for monitors to reach quorum
 I | op-cluster: detecting the ceph image version for image ceph/ceph:v15...
 I | op-cluster: Detected ceph image version: "15.2.3-0 octopus"
 I | op-mon: parsing mon endpoints: a=10.108.126.208:6789
 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
E | op-cluster: failed to get ceph daemons versions. failed to run 'ceph versions: exit status 1

**Comment by leseb** [comment]
Please re-open using the provided bug template.
