### ISSUE TITLE
ceph: pod how can get privileged mode to access some host system resources, like Soft RoCE 

### ISSUE THREAD

**Issue by saltFisher** [rook/rook#5725]
Hi guys，

do we have some methods to access host system resources ? to use the kernel module. 
if we delpoy a pod in k8s, we can set securityContext to get the privileged mode, then we can access any system resources. do we have methods to do this by using rook ? 
at now ,when i config Soft RoCE in host, and then using host network to deploy a ceph cluster, it can't get this device.

securityContext:
    privileged: true

**Comment by travisn** [comment]
@saltFisher When Rook configures the Ceph OSDs on the devices, the "osd prepare" pods are always run privileged, and /dev is mounted. But are you referring to configuring the OSDs, or are you referring to something else? Please describe the scenario in more detail.

**Comment by saltFisher** [comment]
@travisn Travis, if we want to use Soft RoCE which provided by host network, i think all ceph pods（mon, osd, mgr, mds） need to run privileged. we need those pods connectted with Soft RoCE Network each other. i think add am item to allow all ceph pod run privileged is the simplest way.

**Comment by travisn** [comment]
@saltFisher You can try setting [ROOK_HOSTPATH_REQUIRES_PRIVILEGED=true](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L382-L383), but this should be separate from whether the host network is being used. Did you set [provider: host](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L72) for the network settings?

**Comment by saltFisher** [comment]
@travisn Yes, i set provider: host , you are right , ceph pod can run privileged after i set ROOK_HOSTPATH_REQUIRES_PRIVILEGED=true. Thanks.
