### ISSUE TITLE
The CephObjectStore cannot be accessed from outside the cluster

### ISSUE THREAD

**Issue by ijackcy** [rook/rook#5726]
I set up the object storage，in  the toolbox pod i can access the object storage, and i can get /put an object into the object storage.

But  applications are running outside the cluster, I need to access the object storage, from outside the cluster.

so i follow https://rook.io/docs/rook/v1.3/ceph-object.html, i setup an external service through a NodePort, expose RGW internal to the cluster.

kubectl create -f rgw-external.yaml

root@ubuntu-master:/home/xiaowei# kubectl -n rook-ceph get service rook-ceph-rgw-my-store rook-ceph-rgw-my-store-external
NAME                              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
rook-ceph-rgw-my-store            ClusterIP   10.10.24.172   <none>        80/TCP         4d12h
rook-ceph-rgw-my-store-external   NodePort    10.10.206.87   <none>        80:31105/TCP   15h

Outside the cluster, i access the website http://192.168.100.20:31105 (192.168.100.20 is my master node). but it didn't work.
i telnet 192.168.100.20 31105, it didn't work either.

then i access the object storage by hostname http://ubuntu-master:31105 (ubuntu-master is hostname of  master node).

rook :1.3
ceph :version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)
k8s: 1.18.1

[root@rook-ceph-tools-75f575489-vwm7k /]# radosgw-admin user list
[
    "ceph-user-0y5xMpLP",
    "my-user"
]

**Comment by thotz** [comment]
@ijackcy can u please share the following
* kubectl logs <logs of operator and rgw>
* kubectl describe pod <rgw>
* kubectl describe svc <rgw>
* yaml files for rgw and external service

last week I update doc wrt [port information](https://github.com/rook/rook/pull/5596) if possible please see check whether issue is related to that or not

**Comment by ijackcy** [comment]
> @ijackcy can u please share the following
> 
> * kubectl logs
> * kubectl describe pod
> * kubectl describe svc
> * yaml files for rgw and external service
> 
> last week I update doc wrt [port information](https://github.com/rook/rook/pull/5596) if possible please see check whether issue is related to that or not

thank you.

**Comment by XtremeOwnageDotCom** [comment]
@ijackcy 

Would be nice if you posted exactly what you did/found to resolve the issue... That way when other people, such as myself, find this issue from googling a very similar issue- it helps us too.
