### ISSUE TITLE
Rook reports missing module for influx: "influxdb python module not found"

### ISSUE THREAD

**Issue by Moep90** [rook/rook#5727]
I first asked in Slack https://rook-io.slack.com/archives/CK9CF5H2R/p1593088331292000

**Is this a bug report or feature request?**
* Please add support for the influx module out-of-the-box
* Also add some kind of documentation how to configure it

**What should the feature do:**
- install the influxdb python module into the mgr-container

**What is use case behind this feature:**
My company does not have prometheus in place but influx instead.

**Environment**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T07:39:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Executing the following command from the toolbox:
Cephs Version:
```
$ ceph version
ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)
```

Rooks Version:
```
$ rook version
rook: v1.3.6
go: go1.13.8
```

```
$ ceph mgr module ls |grep influx
            "name": "influx",
            "error_string": "influxdb python module not found",
```

**Comment by leseb** [comment]
Not why this is a Ceph bug. If the module is missing, this likely means we need to add something in https://github.com/ceph/ceph-container. Please open your request there.

Thanks.

**Comment by Moep90** [comment]
@leseb :1st_place_medal:  .... It was opened as a feature request not a bug.

**Comment by leseb** [comment]
Even so, it's not something we can fix in Rook, the feature has to be requested in https://github.com/ceph/ceph-container.

**Comment by leseb** [comment]
Once you have it ceph-container, you can active the module via the `mgr` section of the CephCluster CRD. So there is nothing to do in Rook if this is just able to enable the module.
