### ISSUE TITLE
The master MDS and its standby-replay SHOULD NOT run on the same node

### ISSUE THREAD

**Issue by norman-kern** [rook/rook#5731]
**Is this a bug report or feature request?**
No
**Feature Request**
The MDS master and its standby-replay run on different nodes.
**What should the feature do:**
The cluster mds can work correctly while the a node shutdown.
**What is use case behind this feature:**
Sometimes a node of MDS running on may crash
**Environment**:

**Comment by travisn** [comment]
@norman-kern Did you use the default filesystem.yaml? Or what yaml did you use? The default example sets the antiaffinity as seen [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/filesystem.yaml#L77-L85).

**Comment by norman-kern** [comment]
> @norman-kern Did you use the default filesystem.yaml? Or what yaml did you use? The default example sets the antiaffinity as seen [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/filesystem.yaml#L67-L76).

@travisn I use the default yaml, but I use the podAntiAffinity but no 'topologyKey: kubernetes.io/hostname' configed, Is the root cause? I have a try.

**Comment by norman-kern** [comment]
Maybe it's not a common sence, close the feature .
