### ISSUE TITLE
The CephObjectStore can be accessed by firefox，but AccessDenied

### ISSUE THREAD

**Issue by ijackcy** [rook/rook#5735]
I set up the object storage，and create object-user,in the toolbox pod i can access the object storage, and i can get /put an object into the object storage. and creat Bucket 's3://rookbucket/' , put object 'rookdata' into s3 rookbucket. the content of object rookdata:"This is test data from rook-toolbox. "
[root@slaver003 registry]# s3cmd ls --no-ssl --host=${AWS_HOST}
2020-06-27 12:09  s3://rookbucket

[root@slaver003 registry]#  radosgw-admin user list                          
[
    "my-user"
]

I follow https://rook.io/docs/rook/v1.3/ceph-object.html, i setup an external service through a NodePort, expose RGW internal to the cluster.

kubectl create -f rgw-external.yaml

root@ubuntu-master:/home/xiaowei# kubectl -n rook-ceph get service rook-ceph-rgw-my-store rook-ceph-rgw-my-store-external
NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
rook-ceph-rgw-my-store            ClusterIP   10.10.24.172    <none>        80/TCP         5d14h
rook-ceph-rgw-my-store-external   NodePort    10.10.250.135   <none>        80:32366/TCP   129m

when i open the web http://192.168.100.20:32366 (192.168.100.20 is master ip) by firefox. and the web display:

ListAllMyBucketsResult>
 Owner>
 ID>anonymous</ID>
 DisplayName/>
 /Owner>
 Buckets/>
 /ListAllMyBucketsResult>

 i open the web http://192.168.100.20:32366/rookbucket/rookdata by firefox. and the web display:

Error>
Code>AccessDenied</Code>
BucketName>rookbucket</BucketName>
RequestId>tx000000000000000000676-005efaae9d-568fc-my-store</RequestId>
HostId>568fc-my-store-my-store</HostId>
/Error>

Did I do something wrong or miss something？

rook-ceph:1.3
k8s:1.18.1

**Comment by thotz** [comment]
@ijackcy IMO it is expected behavior since from firefox as user u can are not permitted to access the bucket, unless specific policies or acl are set on that bucket to do. I am not sure whether how we can configure to do as well
