### ISSUE TITLE
after expand kubernetes nodes, not all ceph pods should be expanded to new nodes

### ISSUE THREAD

**Issue by hillbun** [rook/rook#5738]
* Bug Report

after expand kubernetes nodes, not all ceph pods should be expanded to new nodes

**Deviation from expected behavior:**

```
[root@node1 ~]# kubectl get node
NAME    STATUS   ROLES    AGE   VERSION
node1   Ready    master   11d   v1.17.6
node2   Ready    master   11d   v1.17.6
node3   Ready    <none>   11d   v1.17.6
node4   Ready    <none>   11d   v1.17.6
node5   Ready    <none>   11d   v1.17.6
node6   Ready    <none>   16h   v1.17.6
```

node6 is new expanded node.

```
kubectl get pods -n rook-ceph -o wide |grep node6
csi-cephfsplugin-v72q6                            3/3     Running     9          16h     192.168.100.78   node6   <none>           <none>
csi-rbdplugin-q2sk4                               3/3     Running     9          16h     192.168.100.78   node6   <none>           <none>
rook-discover-c2q7m                               1/1     Running     3          16h     10.233.108.26    node6   <none>           <none>
```

but only these pods are deployed to node6.

rook-ceph-operator
rook-ceph-osd
...

pods are not deployed.

**Expected behavior:**

after expand kubernetes nodes, all ceph related pods should be expanded to new nodes

**How to reproduce it (minimal and precise):**

expand kubernetes nodes

**Environment**:
* OS (e.g. from /etc/os-release):  CentOS 7.7 64bit
* Kernel (e.g. `uname -a`): Linux node1 3.10.0-1127.8.2.el7.x86_64
* Cloud provider or hardware configuration: aliyun
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.3.6
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)
* Kubernetes version (use `kubectl version`): v1.17.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@hillbun Are you saying you want the OSDs to be created automatically? There is a known issue that sometimes the OSDs are not automatically added when the node is added. 

A workaround is to restart the operator pod (delete the pod) and it will automatically check again if OSDs are needed on all the nodes according to the settings in the CephCluster CR.

It is expected that when a new node is added, by default the only pods that will be started on that new node immediately should be the CSI driver, discover, and OSDs, if applicable.

**Comment by hillbun** [comment]
it fixed
