### ISSUE TITLE
[cassandra] Cluster will not form

### ISSUE THREAD

**Issue by AceHack** [rook/rook#5745]
* Bug Report

**Deviation from expected behavior:**
When the 2nd node comes up I just constantly get
```
INFO  [HANDSHAKE-/172.20.174.61] 2020-07-01 00:15:44,981 OutboundTcpConnection.java:561 - Handshaking version with /172.20.174.61
 INFO  [HANDSHAKE-/172.20.174.61] 2020-07-01 00:15:44,984 OutboundTcpConnection.java:570 - Cannot handshake version with /172.20.174.61
```

And the nodes never join

**Expected behavior:**
Nodes to join cluster

**Comment by AceHack** [comment]
Any update?  This issue seems related to istio.

**Comment by jbguerraz** [comment]
interesting issue. keeping it alive!
@AceHack any news on your side about it ? how did it end up ?
