### ISSUE TITLE
Cannot use with LVM lv 

### ISSUE THREAD

**Issue by stepanselyuk** [rook/rook#5751]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

dm devices rejected without a reason (no reason stated)

**Expected behavior:**

OSD created

**How to reproduce it (minimal and precise):**

I ordered two additional disks (4TB each) for my bare-metal server, then put them in RAID 1, then created PV and VG and created LV with 1TB size, so I can use remain space for other needs. Then I installed Rook 1.3.6 according to the documentation.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

```
 storage:
    config: null
    devices:
    - config: null
      name: /dev/disk/by-id/dm-name-vg1-rook_device01
    storageClassDeviceSets: null
    useAllDevices: false
    useAllNodes: true
```

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
```
* Kernel (e.g. `uname -a`):
```
Linux vanessa 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
* Cloud provider or hardware configuration: Bare-metal server
* Rook version (use `rook version` inside of a Rook Pod):
```
rook version
rook: v1.3.6
go: go1.13.8
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
ceph -v
ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)
```
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): MicroK8s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): 
```
HEALTH_WARN OSD count 0 < osd_pool_default_size 3
```

=============

I still have an issue with using pre-created LV:

```
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646832 I | cephosd: creating and starting the osds
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646844 D | cephosd: desiredDevices are [{Name:/dev/disk/by-id/dm-name-vg1-rook_device01 OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false IsDevicePathFilter:false}]
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646850 D | cephosd: context.Devices are [0xc0001d7440 0xc0001d86c0 0xc00020bb00 0xc000272000 0xc0002725a0 0xc0001d85a0 0xc0001d25a0 0xc0001c4000 0xc0001c4360 0xc000142d80 0xc0001a8a20 0xc00022f320]
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646855 I | cephosd: skipping device "nvme0n1p1" because it contains a filesystem "linux_raid_member"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646860 I | cephosd: skipping device "nvme0n1p2" because it contains a filesystem "linux_raid_member"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646863 I | cephosd: skipping 'dm' device "dm-1"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646866 I | cephosd: skipping 'dm' device "dm-2"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646868 I | cephosd: skipping 'dm' device "dm-0"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646871 I | cephosd: skipping 'dm' device "dm-3"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646874 I | cephosd: skipping device "nvme1n1p2" because it contains a filesystem "linux_raid_member"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646877 I | cephosd: skipping 'dm' device "dm-1"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646879 I | cephosd: skipping 'dm' device "dm-2"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646882 I | cephosd: skipping 'dm' device "dm-0"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646885 I | cephosd: skipping device "nvme1n1p1" because it contains a filesystem "linux_raid_member"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.646890 I | cephosd: skipping 'dm' device "dm-3"
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.650766 I | cephosd: configuring osd devices: {"Entries":{}}
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.650780 I | cephosd: no new devices to configure. returning devices already configured with ceph-volume.
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.650786 D | exec: Running command: ceph-volume lvm list  --format json
[rook-ceph-osd-prepare-vanessa-tgnd2 provision] 2020-07-02 16:23:28.881510 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
```

I used branch 1.3 to get k8s configs. In the `CephCluster` I limited devices to one I need to use with rook (it does not work even if I sed: `useAllDevices: true`):

```
 storage:
    config: null
    devices:
    - config: null
      name: /dev/disk/by-id/dm-name-vg1-rook_device01
    storageClassDeviceSets: null
    useAllDevices: false
    useAllNodes: true
```

rook-ceph-osd-prepare uses ceph/ceph:v14.2.9

```
lsblk /dev/dm-3 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
SIZE="1099511627776" ROTA="1" RO="0" TYPE="lvm" PKNAME="" NAME="/dev/mapper/vg1-rook_device01"
```

**Comment by stepanselyuk** [comment]
I search over the codebase and found:
https://sourcegraph.com/github.com/rook/rook@release-1.3/-/blob/pkg/daemon/ceph/osd/daemon.go#L294:18

```
...
for _, device := range context.Devices {
// Ignore 'dm' device since they are not handled by c-v properly
// see: https://tracker.ceph.com/issues/43209
if strings.HasPrefix(device.Name, sys.DeviceMapperPrefix) && device.Type == sys.LVMType {
logger.Infof("skipping 'dm' device %q", device.Name)
continue
}
...
```

So how to use Rook with LV ?

**Comment by satoru-takeuchi** [comment]
There are two ways to consume devices for OSDs.

a. OSD on device: Create OSDs on top of the devices that are specified in cluster.yaml
b. OSD on PVC: Create OSDs on top of the raw block volume

Rook doesn't support (a) due to Ceph's issue(43209). As of (b), you can use LV by creating local persistent volumes.

Here is the example of your case.

```pv.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: <XXX>
spec:
  storageClassName: manual
  capacity:
    storage: <XXX>
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
  local:
    path: /dev/disk/by-id/dm-name-vg1-rook_device01
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hostname
                operator: In
                values:
                - <XXX>
```

```cluster.yaml
...
  storage:
    storageClassDeviceSets:
    - name: set1
      count: 1
      portable: false
      tuneDeviceClass: true
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: <XXX>
          storageClassName: manual
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
...
```

If you apply pv.yaml and cluster.yaml, a Rook cluster with 1 OSD pod backed by your LV will be created.

For more detail, please refer to the document of storageClassDeviceSets.

https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md#storage-class-device-sets

**Comment by satoru-takeuchi** [comment]
If you don't want to prepare PV one by one, the following tools would help you.

https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner

**Comment by stepanselyuk** [comment]
@satoru-takeuchi thank you. Do I need to specify `volumeName` in `volumeClaimTemplates`? I removed Rook as per cleanup documentation. Then recreated and specified cluster with storageClassDeviceSets and with `volumeName` in `volumeClaimTemplates`.

Now I see that PVC is bound. But pod `rook-ceph-osd-prepare-set1-data-0-mqfcc-55cws` with pending status:
```
status:
  phase: Pending
  conditions:
    - type: PodScheduled
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2020-07-02T19:16:01Z'
      reason: Unschedulable
      message: '0/1 nodes are available: 1 node(s) had volume node affinity conflict.'
  qosClass: BestEffort
```
I thought because of ReadWriteOnce and some other pod already used the PVC, but I checked and the PVC mounted by this very pod:
```
kubectl describe pvc set1-data-0-mqfcc -n rook-ceph
Name:          set1-data-0-mqfcc
Namespace:     rook-ceph
StorageClass:  manual
Status:        Bound
Volume:        rook-osd-on-lv
Labels:        ceph.rook.io/DeviceSet=set1
               ceph.rook.io/DeviceSetPVCId=set1-data-0
               ceph.rook.io/setIndex=0
Annotations:   pv.kubernetes.io/bind-completed: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Ti
Access Modes:  RWO
VolumeMode:    Block
Mounted By:    rook-ceph-osd-prepare-set1-data-0-mqfcc-55cws
Events:        <none>
```

All happens on one bare-metal machine, and the node name specified all right in the PV node affinity.

```
kubectl get node vanessa -o yaml | grep kubernetes.io/hostname
    kubernetes.io/hostname: vanessa
```

**Comment by stepanselyuk** [comment]
oh my bad, `kubernetes.io/hostname` label vs just `hostname` label. 
I added the label 
```
kubectl label nodes vanessa hostname=vanessa
```
and now all working!

**Comment by satoru-takeuchi** [comment]
@stepanselyuk Oh, sorry, kubernetes.io/hostname is correct. I forgot to add "kubernetes.io/".

Anyway, do you have more questions? If so, feel free to ask me. If not, please close this ticket.

**Comment by stepanselyuk** [comment]
@satoru-takeuchi thank you for your help! I close this ticket.

**Comment by mmalcek** [comment]
> There are two ways to consume devices for OSDs.
> 
> a. OSD on device: Create OSDs on top of the devices that are specified in cluster.yaml
> b. OSD on PVC: Create OSDs on top of the raw block volume
> 
> Rook doesn't support (a) due to Ceph's issue(43209). As of (b), you can use LV by creating local persistent volumes.
> 
> Here is the example of your case.
> 
> pv.yaml:
> 
> ```
> kind: StorageClass
> apiVersion: storage.k8s.io/v1
> metadata:
>   name: manual
> provisioner: kubernetes.io/no-provisioner
> volumeBindingMode: WaitForFirstConsumer
> ---
> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: <XXX>
> spec:
>   storageClassName: manual
>   capacity:
>     storage: <XXX>
>   accessModes:
>     - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Retain
>   volumeMode: Block
>   local:
>     path: /dev/disk/by-id/dm-name-vg1-rook_device01
>   nodeAffinity:
>       required:
>         nodeSelectorTerms:
>           - matchExpressions:
>               - key: hostname
>                 operator: In
>                 values:
>                 - <XXX>
> ```
> 
> cluster.yaml:
> 
> ```
> ...
>   storage:
>     storageClassDeviceSets:
>     - name: set1
>       count: 1
>       portable: false
>       tuneDeviceClass: true
>       volumeClaimTemplates:
>       - metadata:
>           name: data
>         spec:
>           resources:
>             requests:
>               storage: <XXX>
>           storageClassName: manual
>           volumeMode: Block
>           accessModes:
>             - ReadWriteOnce
> ...
> ```
> 
> If you apply pv.yaml and cluster.yaml, a Rook cluster with 1 OSD pod backed by your LV will be created.
> 
> For more detail, please refer to the document of storageClassDeviceSets.
> 
> https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md#storage-class-device-sets

This issue in ceph (https://tracker.ceph.com/issues/43209  fixed in 15.2.9 ) seems to be closed but latest rook still ignore dm devices in daemon.go

**Comment by morteza1131** [comment]
I can not use lvm as osd because of this issue, is this issue still exist? I use release-1.6 of rook-ceph
I locked at code and find this:
`for _, device := range context.Devices {
		// Ignore 'dm' device since they are not handled by c-v properly
		// see: https://tracker.ceph.com/issues/43209
		if strings.HasPrefix(device.Name, sys.DeviceMapperPrefix) && device.Type == sys.LVMType {
			logger.Infof("skipping 'dm' device %q", device.Name)
			continue
		}`

Could I use lvm as osd or not?
how about this doc? https://github.com/rook/rook/blob/master/design/ceph/ceph-volume-provisioning.md

**Comment by satoru-takeuchi** [comment]
@morteza1131 

> I can not use lvm as osd because of this issue, is this issue still exist?

Yes.

> Could I use lvm as osd or not?

In PVC-based cluster, yes. In host-based cluster, No.

> how about this doc? https://github.com/rook/rook/blob/master/design/ceph/ceph-volume-provisioning.md

Design documents are written when features will be implemented. So, sometimes, it doesn't reflect the newest version.

I have a PR to fix this problem but is in progress. 

https://github.com/rook/rook/pull/7967

**Comment by kompetenzlandkarte** [comment]
What about this pull request https://github.com/rook/rook/pull/7967? The issue creator is user an dm device.

**Comment by satoru-takeuchi** [comment]
@kompetenzlandkarte 

> What about this pull request #7967?

It's my PR which is to support OSD on LV in host-based clusters.
