### ISSUE TITLE
Help topic for CSI configuration

### ISSUE THREAD

**Issue by stepanselyuk** [rook/rook#5752]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

@travisn said:
```
We should really create a help topic for CSI configuration similar to the flex configuration page to include details like this for different platforms. Would you mind opening a new issue for that?
```

**What is use case behind this feature:**

In my case I use MicroK8s and have different from default kubelet path:

For MicroK8s `kubelet` path is `/var/snap/microk8s/common/var/lib/kubelet/`
need to change in `operator.yaml` (change and uncomment), or add in the deployment of the root-ceph-operator:
```
- name: ROOK_CSI_KUBELET_DIR_PATH
  value: /var/snap/microk8s/common/var/lib/kubelet/
```

**Environment**:
MicroK8s

**Comment by travisn** [comment]
We can turn this blog into rook docs: https://www.mrajanna.com/troubleshooting-cephcsi/
