### ISSUE TITLE
Failed upgrade to Octopus - -1 bluestore(/var/lib/ceph/osd/ceph-1) fsck warning: #2:89320fb6:::10000250e1c.00000000:head# has omap that is not per-pool or pgmeta

### ISSUE THREAD

**Issue by iMartyn** [rook/rook#5772]
**Is this a bug report or feature request?**
* Bug Report

Upgrading to ceph 15.2.4 from 14.2.10 by editing the CRD on rook 1.3.3 did not work.

**Deviation from expected behavior:**

After restarting the OSDs, they fail with __**many**__ log lines like : 
```
-1 bluestore(/var/lib/ceph/osd/ceph-1) fsck warning: #2:89320fb6:::10000250e1c.00000000:head# has omap that is not per-pool or pgmeta
```

**Expected behavior:**

OSDs should run successfully after an upgrade to octopus

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): `Debian GNU/Linux 9 (stretch)`
[podlog.txt](https://github.com/rook/rook/files/4881159/podlog.txt)

* Kernel (e.g. `uname -a`): `Linux worker 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.3.3 go: go1.13.8`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)`
* Kubernetes version (use `kubectl version`): `v1.17.2+k3s1`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `k3s`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN 1 MDSs report slow metadata IOs; 1 MDSs report slow requests; 1 osds down; 2 hosts (2 osds) down; 1 root (2 osds) down; Reduced data availability: 100 pgs stale; Degraded data redundancy: 4824104/9648208 objects degraded (50.000%), 100 pgs degraded, 100 pgs undersized; 3 pool(s) have non-power-of-two pg_num`

**Comment by travisn** [comment]
@jdurgin What would cause the OSDs to fail after upgrade to Octopus with this message? The OSDs were healthy on v14.2.10 before the upgrade to v15.2.4.
```
fsck warning: #2:89320fb6:::10000250e1c.00000000:head# has omap that is not per-pool or pgmeta
```

**Comment by jdurgin** [comment]
@travisn this would be the OSDs upgrading their on-disk format to add per-pool omap accounting - it'll take some time (minutes to potentially hours, depending on the amount of omap data) and may use a lot of memory during this process the first time the OSD starts running octopus.

If it's taking too long/causing issues, you can turn off the conversion as detailed in step 5 here: https://docs.ceph.com/docs/master/releases/octopus/#instructions

**Comment by iMartyn** [comment]
Thanks @jdurgin That does appear to be the case.

@travisn for record here, steps that got my cluster back up and running :

- Removed the liveness probe from the OSDs
- Let them complete the process (left them for about ~1hr)
- Upgraded to 1.3.7 of rook to get a better liveness probe
- Deleted OSD deployment and restarted operator (which unsurprisingly had gotten stuck)
- New OSD pods came up fine.

I think Rook might need a bit more process around upgrades of major ceph versions, something like per OSD (one at a time to avoid downtime)
- Delete old OSD
- Create new OSD with no livenessprobe to do migration
- Wait for OSD to actually join the cluster and settle
- Shut down new OSD
- Create new OSD with livenessprobe
- Wait for OSD to actually join the cluster and settle
- Proceed to next OSD

I appreciate that's a lot of steps but better in code than having people editing deploys to complete the conversions especially as rook will happily go causing all OSDs to get into a bad state at the moment leading to a broken cluster. (I assume because it's waiting for running status which is reached, but not ready for use, and then gets killed because of timeout on livenessprobe).

I also wonder if it's worth having a readinessprobe even though we don't have services in front of the OSDs, just for the operator to use as a real status, i.e. check if the OSD is `up` and `in`?

**Comment by travisn** [comment]
@iMartyn Great to hear the upgrade was successful after disabling the liveness probe. The rest of the process you suggest (besides creating the OSD without a liveness probe) is actually pretty much there. The operator upgrades one OSD at a time before continuing to the next one. @leseb Let's discuss how to handle the liveness probes during upgrades.

**Comment by leseb** [comment]
@travisn I'm working on a PR to expose more livenessprobe, this could help.
