### ISSUE TITLE
Rook support multi zones and zonegroups configuration on object stores

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#5776]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
There's no existing mechanism to configure multi zonegroups for object store. Below steps will need to recstart rgw pod to take effect. 
```
Create new Zonegroup Placement using below command

radosgw-admin zonegroup placement add --rgw-zonegroup rook-ceph-store --placement-id tpcds
Create new Zone Placement using below command

radosgw-admin zone placement add --rgw-zone rook-ceph-store --placement-id tpcds  --data-pool tpcds.rgw.data --index-pool tpcds.rgw.index --data-extra-pool tpcds.rgw.non-ec
Create new bucket

s3cmd -d mb s3://bucket-tpcds --no-ssl --region=":tpcds" 
Bucket creation failed with error "ERROR: S3 error: 400 (InvalidLocationConstraint): The specified location-constraint is not valid"

After this, we restarted the rgw pod (rook-ceph-rgw-rook-ceph-store-a-xxx). Once the pod was restarted, bucket creation command succeeded.
```

**What is use case behind this feature:**
Need an automatic way to create multi zonegoups and zones. 

**Environment**:

**Comment by thotz** [comment]
AFAIR @alimaredia [changes](https://github.com/rook/rook/pull/5377) already address above issue, will be part of 1.4 release

**Comment by travisn** [comment]
@yanchicago Feedback welcome on the experimental [rgw multisite](https://rook.github.io/docs/rook/v1.4/ceph-object-multisite.html) feature in the v1.4 release! Please open new issues that you may find.
