### ISSUE TITLE
CephFilesystem does not finalize deleting when it's not created on ceph

### ISSUE THREAD

**Issue by Pieter-Auqkwa** [rook/rook#5783]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
CephFilesystem does not remove from kubernetes when ceph is unable to create it in the first place
**Expected behavior:**
CephFilesystem being able to finalize delete, even if fs doesn't exist on ceph
**How to reproduce it (minimal and precise):**

I was setting up CephFilesystem according to docs, applied the first config, the pods did not come up.
So I checked the operator logs:
`ceph-file-controller: failed to reconcile failed to create filesystem "myfs": failed to create filesystem "myfs": failed to create metadata pool "myfs-metadata": failed to create replicated pool myfs-metadata. Error ERANGE:  pg_num 32 size 3 would mean 752 total pgs, which exceeds max 750 (mon_max_pg_per_osd 250 * num_in_osds 3)`

So then I did a delete of the applied config, then these errors showed up in operator:
`ceph-file-controller: failed to reconcile failed to delete filesystem "myfs". : failed to get filesystem "myfs": failed to get file system myfs: exit status 2`

I then tried to apply with lower replica set to circumvent the max_pg, but no difference, same error logs.

Temporary fix provided by @travisn :
`kubectl -n rook-ceph edit cephfilesystem myfs`
remove the finalizer metadata
then restart the rook-ceph-operator

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 1804
* Kernel (e.g. `uname -a`): Linux k-ash-01 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: E3 xeon 128gb ram 1nmve 1ssd node x3
* Rook version (use `rook version` inside of a Rook Pod): 1.3.6
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)
* Kubernetes version (use `kubectl version`): version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
The issue is that the operator should skip the query for the filsystem if it doesn't exist. But if there is any error, including if it doesn't exist, it will return an error on [this line](https://github.com/rook/rook/blob/master/pkg/operator/ceph/file/controller.go#L207). But if the filesystem does not exist the operator should continue with the cleanup instead of failing.

**Comment by rajatsingh25aug** [comment]
So I read the entire function of [reconcile.go](https://github.com/rook/rook/blob/master/pkg/operator/ceph/file/controller.go#L143), and as you said that the finalizer should only delete when operator catches any filesystem, what about [this](https://github.com/rook/rook/blob/master/pkg/operator/ceph/file/controller.go#L143) `GET()`, isn't that supposed to only catch if there's an existing cephFilesystem?.

My point here is that isn't this function was supposed to catch if there's a filesystem or not?.

**Comment by travisn** [comment]
The reconcile handles all creates, updates, and deletes to the filesystem CR. This issue in question is about the deletion scenario, which is only covered by [this code block](https://github.com/rook/rook/blob/master/pkg/operator/ceph/file/controller.go#L202-L218). If during the deletion, the filesystem is not found when queried from Ceph, the reconcile should proceed with the deletion of the CR, rather than fail. Currently it is failing and will retry indefinitely in the failed state.
