### ISSUE TITLE
smartmontools version < 7.0 osd health check error

### ISSUE THREAD

**Issue by gdtiti** [rook/rook#5784]
dashboard  disk health check tip error
Warning
Smartctl has received an unknown argument (error code -22). You may be using an incompatible version of smartmontools. Version >= 7.0 of smartmontools is required to successfully retrieve data.

osd pod smartmontools is 6.6

**Comment by leseb** [comment]
Please open an issue here instead, https://github.com/ceph/ceph-container thanks.
