### ISSUE TITLE
mgr crashing after upgrade

### ISSUE THREAD

**Issue by TfM2** [rook/rook#5787]
Question was asked on slack channel

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Mrg is crashing loopback after authentification
**Expected behavior:**
connect to mgr

**How to reproduce it (minimal and precise):**

We upgraded from version 1.2.7 to 1.30, and after to 1.3.7
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
"ebug    -15> 2020-07-07T15:08:20.536+0000 7f62edf7d700 10 monclient: _send_mon_message to mon.c at v2:10.233.22.136:3300/0
debug    -14> 2020-07-07T15:08:20.536+0000 7f62edf7d700  1 librados: init done
debug    -13> 2020-07-07T15:08:20.537+0000 7f62ecf7b700 10 monclient: _finish_auth 0
debug    -12> 2020-07-07T15:08:20.537+0000 7f62ecf7b700 10 monclient: _check_auth_rotating have uptodate secrets (they expire after 2020-07-07T15:07:50.538818+0000)
debug    -11> 2020-07-07T15:08:20.538+0000 7f62ecf7b700  4 mgrc handle_mgr_map Got map version 3297
debug    -10> 2020-07-07T15:08:20.538+0000 7f62ecf7b700  4 mgrc handle_mgr_map Active mgr is now [v2:10.233.82.37:6800/305229339,v1:10.233.82.37:6801/305229339]
debug     -9> 2020-07-07T15:08:20.538+0000 7f62ecf7b700  4 mgrc reconnect Starting new session with [v2:10.233.82.37:6800/305229339,v1:10.233.82.37:6801/305229339]
debug     -8> 2020-07-07T15:08:20.538+0000 7f6324caa700 10 monclient: get_auth_request con 0x55f37f62d400 auth_method 0
debug     -7> 2020-07-07T15:08:20.539+0000 7f6324caa700 10 monclient: get_auth_request con 0x55f37f62cc00 auth_method 0
debug     -6> 2020-07-07T15:08:20.541+0000 7f6325cac700 10 monclient: get_auth_request con 0x55f37f62d000 auth_method 0
debug     -5> 2020-07-07T15:08:20.543+0000 7f63254ab700 10 monclient: get_auth_request con 0x55f37f62d800 auth_method 0
debug     -4> 2020-07-07T15:08:20.546+0000 7f6324caa700 10 monclient: get_auth_request con 0x55f37f62dc00 auth_method 0
debug     -3> 2020-07-07T15:08:20.556+0000 7f6325cac700 10 monclient: get_auth_request con 0x55f37f698000 auth_method 0
debug     -2> 2020-07-07T15:08:20.565+0000 7f63254ab700 10 monclient: get_auth_request con 0x55f37f698400 auth_method 0
debug     -1> 2020-07-07T15:08:20.607+0000 7f62f3b08700  4 mgr get_store get_store key: mgr/dashboard/jwt_token_black_list
debug      0> 2020-07-07T15:08:20.619+0000 7f62f3b08700 -1 *** Caught signal (Segmentation fault) **
 in thread 7f62f3b08700 thread_name:dashboard
 ceph version 15.2.0 (dc6a0b5c3cbf6a5e1d6d4f20b5ad466d76b96247) octopus (rc)
 1: (()+0x12dc0) [0x7f6329837dc0]
 2: (PyObject_GetAttrString()+0x9) [0x7f632aaea549]
 3: (ActivePyModule::method_exists(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x49) [0x55f350319a69]
 4: (()+0x1795d6) [0x55f3503395d6]"

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
* Kernel (e.g. `uname -a`):
Linux XXXX 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
Kubernetes 1.16 
* Rook version (use `rook version` inside of a Rook Pod):
toolbox: rook: v1.3.0-beta.0.506.g9332d31
go: go1.13.8

operator: rook: v1.3.7
go: go1.13.8
* Storage backend version (e.g. for ceph do `ceph -v`):
toolbox: ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)
operator: version 15.2.3 (d289bbdec69ed7c1f516e0a093594580a76b78d0) octopus (stable)
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN clock skew detected on mon.c, mon.f, mon.h; mon c is low on available space; Reduced data availability: 10 pgs inactive, 1 pg down, 7 pgs stale; 7 pool(s) have no replicas configured; 1 pool(s) have non-power-of-two pg_num; 8 pools have too few placement groups; 8 slow ops, oldest one blocked for 883 sec, daemons [osd.6,osd.8,osd.9] have slow ops.

---
Version of ceph is:  ceph-version=15.2.0-0. We migrate also the csi driver to 2.1.2 (previous was 2.0.0).
ceph/ceph:v15.2.0-20200324
quay.io/cephcsi/cephcsi:v2.1.2
quay.io/k8scsi/csi-attacher:v2.1.0
quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
quay.io/k8scsi/csi-provisioner:v1.4.0
quay.io/k8scsi/csi-resizer:v0.4.0
quay.io/k8scsi/csi-snapshotter:v1.2.2
rook/ceph:master
rook/ceph:v1.3.7 

from get pod  jsonpath='{range .items[*]}{range .spec.containers[*]}{.image}{"\n"}' | sort | uniq
![image (1)](https://user-images.githubusercontent.com/68016121/86927378-8fe71380-c133-11ea-851d-c2e9492e4bd2.png)
![image (2)](https://user-images.githubusercontent.com/68016121/86927380-907faa00-c133-11ea-8fc3-0074d54a6d64.png)

**Comment by leseb** [comment]
This looks like a bug in one of the manager modules, could you please open a ticket here https://tracker.ceph.com/? Thanks

**Comment by travisn** [comment]
@TfM2 Looks like you are running ceph v15.2.0. Please update to the latest v15.2.4 and test again. This may be fixed already in the latest release.
