### ISSUE TITLE
Allow disk type to be specified in CRD

### ISSUE THREAD

**Issue by iMartyn** [rook/rook#5797]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Instead of relying only on a hard-coded list of devices rook can specifically work on, allow the user to add detail into the CRD to guide rook.  This would mean that rook can be used in "unusual" scenarios without knowing what they are in advance.

Alternatively, when specifying devices on nodes, a "force" flag could be added, but that would mean users in these scenarios couldn't use the `AllDevices` mode.

**What is use case behind this feature:**

Example 1: in certain scenarios you might have a Linux driver that provides disk but doesn't quite match the list, for example it may report as "3waredisk" on a certain 3ware raid controller (not real detail but possible)
Example 2: some users might want to use `mdraid` to increase resiliance or reduce the number of OSDs required on a machine
Example 3: given the dropping of file-based stores, a loop device on top of a file image could be used, but perhaps we don't want to hard-code an allow for `loop` devices

In all of the above scenarios, the only way to allow those to be used would be to run a fork or have rook update it's list of valid devices (which may not be a desired outcome anyway).

**Environment**:
I think this would be useful in many environments and solve quite a few use-case scenarios.

**Comment by travisn** [comment]
@iMartyn Sounds like what you want are drive groups, which will be coming in the v1.4 release soon. See #4916.
