### ISSUE TITLE
How to create the internal and external network of ROOK-CEPH？

### ISSUE THREAD

**Issue by luciferhs** [rook/rook#5798]
We want to deploy the hook CEPH to the production environment, but now our k8s cluster has only one intranet segment. We want to distinguish between the network segment of OSD data replication and the external network segment

But we don't know how to  configure it？ 
Please help us！

**Comment by leseb** [comment]
Please https://rook.io/docs/rook/v1.3/ceph-advanced-configuration.html#osd-dedicated-network or use Multus: https://rook.io/docs/rook/v1.3/ceph-cluster-crd.html
