### ISSUE TITLE
Rename Rookcluster back to Cluster to avoid stutter and use beta TPRs ASAP

### ISSUE THREAD

**Issue by luxas** [rook/rook#580]
The TPR to beta proposal is here: https://github.com/kubernetes/community/pull/524
It will allow us to customize the kubectl names easily without having to have an unique resource name cluster-wide.

Therefore I propose to rename things back to Cluster, Pool, etc.
In the meantime it's possible to do `kubectl get clusters.rook.io` which I think is reasonable (this is only given the corner case that the etcd operator also has the Cluster TPR registered)

**Comment by luxas** [comment]
Should target v0.4 I think @bassam

**Comment by travisn** [comment]
Agreed that the names with the Rook prefix feel unnatural. That proposal from last week does make it more obvious that we shouldn't worry about conflicts with other resources.

It seems like the best option is to rename back to `cluster` and `pool` and then always mention the fully qualified name in the docs and examples. If fully qualified you would never run into conflicts anyway, even if most people may not have conflicts for their scenarios.
