### ISSUE TITLE
Admission controller should verify PG count before before allowing pool creation

### ISSUE THREAD

**Issue by travisn** [rook/rook#5802]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The admission controller could improve the experience around creating pools by first checking if creating the pool will exceed the maximum PG count in Ceph. If creating the pool would exceed the max count allowed, the CR would be rejected.
- Pools: 32 PGs each
- Object Store: Five metadata pools with 8 PGs each and one data pool with 32 PG
- Filesystem: Two pools with 32 PGs each

When counting the PGs and reaching the max count, we also need to take into account the replica count for the pool.

This will be the first instance of the admission controller querying Ceph for status before accepting the request.

**What is use case behind this feature:**
Improved error checking for CRs including pools.

**Comment by pcuzner** [comment]
As a first step, could this simply use the metrics as the basis for the allow/deny? mgr/prometheus returns ceph_osd_numpg for all osd's for example, which could be the basis for a comparison given the 32 default pg's * replica size requirement?

**Comment by travisn** [comment]
Admission controllers are expected to perform very quick checks. Running any ceph commands will cause longer latency than expected so let's not plan on this.
