### ISSUE TITLE
Object store "port" in the CR should be optional if the securePort is specified

### ISSUE THREAD

**Issue by travisn** [rook/rook#5806]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The object store schema currently requires the `port` to be non-zero. This does not allow http access to the object store to be disabled. 
- The port minimum is set to 1 instead of 0 to allow it to be optional. See the object [schema](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml#L431).
- Other places in the object store might or might not allow one port, or the other. We should review the object controller for consistency
- The admission controller should add a check that at least one of the port or securePort are set

**Expected behavior:**
Either one or both of the `port` or `securePort` could be specified in the object store CR. This allows either http or https endpoints to be enabled or disabled. 

**How to reproduce it (minimal and precise):**

- Create a cluster
- Create an object store CR with port=0 and securePort=443
- The object store will be rejected by the schema

**Comment by leseb** [comment]
This PR contains a lot of background: https://github.com/rook/rook/pull/4694, I have not read it entirely but I believe it has some answers on why things are as they are today.
