### ISSUE TITLE
crushRoot missing in Pool CRDs

### ISSUE THREAD

**Issue by jeesmon** [rook/rook#5809]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

`crushRoot` is missing in following CRDs

* `cephfilesystems.ceph.rook.io`
* `cephblockpools.ceph.rook.io`
* `cephobjectstores.ceph.rook.io`

**Expected behavior:**

`crushRoot` is present in spec.validation.openAPIV3Schema

**How to reproduce it (minimal and precise):**

```
kubectl apply -f cluster/examples/kubernetes/ceph/common.yaml

kubectl get crd cephfilesystems.ceph.rook.io cephblockpools.ceph.rook.io cephobjectstores.ceph.rook.io -o yaml | grep crushRoot
```

**File(s) to submit**:

https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml

**Environment**:
N/A

**Comment by travisn** [comment]
Fixed by #6014
