### ISSUE TITLE
Rook CI framework hangs when deploying k8s 1.6

### ISSUE THREAD

**Issue by aramisjohnson** [rook/rook#581]
When deploying k8s v1.6, kubeadm hangs at the step "Waiting for kube-proxy and the nodes".

**Comment by aramisjohnson** [comment]
I fixed this, turns out Docker-CE 17, has networking issues when installing k8s v1.6. i installed an earlier version of Docker (1.12.6-0~ubuntu-xenial) and both k8s 1.5 and 1.6 clusters were successfully created. We just need to make sure that our Jenkins Ami instance is not using version 17.

**Comment by jbw976** [comment]
great find @aramisjohnson!
