### ISSUE TITLE
Improve the K8S in-tree RBD plugin to not depend on ceph-tools

### ISSUE THREAD

**Issue by kokhang** [rook/rook#583]
Rook uses the in-tree RBD plugin to map/unmap rook volumes. However this plugin uses the `rbd` command to map/unmap volumes. This makes it dependent on ceph-tools installed in all nodes.

**Comment by kokhang** [comment]
One of the biggest obstacle is finding a way to perform `rbd lock`. Currently the plugin uses `rbd lock/unlock` to lock volumes so that two hosts can attach them. There are some patches at the kernel level needed before we could remove this dependency completely. Some of these will become available on kernel v4.11. 

https://github.com/torvalds/linux/commit/ed95b21a4b0a71ef89306cdeb427d53cc9cb343f
https://github.com/torvalds/linux/commit/8767b293a4ab6632f9288f34bcf2ab9ba20dca3a
https://github.com/kubernetes/kubernetes/compare/master...rootfs:rbd-exclusive-lock
http://tracker.ceph.com/issues/17524

**Comment by kfox1111** [comment]
kolla-kubernetes worked around this in a rather novel way I think:
https://github.com/openstack/kolla-kubernetes/blob/master/helm/microservice/ceph-rbd-daemonset/templates/ceph-rbd-daemonset.yaml

It makes a rbd shell script available on the host and runs the actual rbd command in a container landed with a daemonset. It seems to be running pretty well.

**Comment by kokhang** [comment]
@kfox1111 That is a great workaround. Rook does something similar to run on minikube. https://github.com/rook/rook/blob/master/Documentation/k8s-pre-reqs.md#minikube. 

But i havent tested running this in a daemon-set. Does this work on cloud k8s environments like GKE?

**Comment by kfox1111** [comment]
I built it specifically for minikube initially. :)

I have not tried it on GKE, but it runs many times a day in the OpenStack gate which involves many different OpenStack clusters. So, should work similarly.

**Comment by kokhang** [comment]
Issue submitted to https://github.com/kubernetes/kubernetes/issues/45190

**Comment by jbw976** [comment]
Can this be closed with our Flexvolume and Rook agent design @kokhang?

**Comment by kokhang** [comment]
with #882 merged, this should not happen
