### ISSUE TITLE
Rook pods use the different timezone as their hosts

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#5831]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The rook pods use their own timezone which is different from the hosts. 

```
Host timezone across k8s cluster:
# ls -l /etc/localtime
lrwxrwxrwx. 1 root root 34 Apr 22 19:26 /etc/localtime -> /usr/share/zoneinfo/US/Pacific-New

# knc exec rook-ceph-operator-5985cdf6f8-cxq8f -- sh -c  'ls -l /etc/localtime'
lrwxrwxrwx. 1 root root 25 May  4 15:37 /etc/localtime -> ../usr/share/zoneinfo/UTC

# knc exec rook-ceph-mon-a-65d7449cb6-rxdrp -- sh -c  'ls -l /etc/localtime'
lrwxrwxrwx. 1 root root 25 May  4 15:37 /etc/localtime -> ../usr/share/zoneinfo/UTC

```
**Expected behavior:**
Rook pods use the same timezone as its host. At least, can be configured to use the same timezone as its host. 

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.3.5
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.9
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@yanchicago We need to use UTC to avoid time differences across the pods or issues when the daylight savings changes. Why would you want to change this? For log readability?

**Comment by yanchicago** [comment]
@travisn Yes, the log readability is the main reason and it's one of our project requirements too. So do you expect the hosts within k8s cluster having different timezone? Can it be configurable to use the host timezone?

**Comment by travisn** [comment]
No I don't expect it to be configurable. UTC helps avoid any issues related to time zones in the ceph cluster.
