### ISSUE TITLE
CI: Unable to delete pool CR in aws_1.14 CI

### ISSUE THREAD

**Issue by binoue** [rook/rook#5841]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

In CI, the pool resource CR can not be deleted because of the following error and aws_1.14 test can not be passed.

The error is like below
https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/master/runs/2078/nodes/59/steps/128/log/?start=0
```
2020-07-16 16:56:46.184518 E | integrationTest: failed to delete pool "multi-cluster-pool1". failed to delete pool CR. admission webhook "rook-ceph-admission-controller.mrc-n1-system.svc" denied the request: there is no content to decode
```

This is caused by the controller-runtime and the issue is already open [here](https://github.com/kubernetes-sigs/controller-runtime/issues/845).

**Expected behavior:**

The CR should be deleted as the CI test expected.

**How to reproduce it (minimal and precise):**

Run CI with the current master branch.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@binoue thanks for opening this, I just noticed this as well. 
@vbnrh I wonder if we need to disable the admission controller in the tests on k8s 1.14 or older.

**Comment by vbnrh** [comment]
Looking into it.
