### ISSUE TITLE
CephBlockPool not found to csi-provisioner after operator image upgrade from rook/ceph:v1.3.4 to rook/ceph:v1.3.6

### ISSUE THREAD

**Issue by matthew-mcdermott** [rook/rook#5843]
**Is this a bug report or feature request?**
Bug Report

**Deviation from expected behavior:**
PVC stays pending and csi-provisioner shows following error although the CephBlockPool named "replicapool" exists on the k8s cluster:

> 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Internal desc = pool (replicapool) not found in Ceph cluster

**Expected behavior:**
Expected a k8s PVC that has been able to be created and bound to a PV prior to upgrade to continue being able to be created and bound successfully.

**How to reproduce it (minimal and precise):**
1. Check out to the tag: v1.3.4 from this repo.
2. Navigate to the Rook/Ceph example located at "cluster/examples/kubernetes/ceph"
3. Edit the operator.yaml file and change the line "image: rook/ceph:v1.3.4" to read "image: rook/ceph:v1.3.6"
4. kubectl apply -f common.yaml
5. kubectl apply -f operator.yaml
6. kubectl apply -f cluster.yaml
7. kubectl apply -f csi/rbd/storageclass.yaml
8. Create a file called statefulset.yaml containing the following manifest:
```apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "rook-ceph-block"
      resources:
        requests:
          storage: 1Gi
```
9. kubectl apply -f statefulset.yaml
10. __kubectl get pods__ should show the first pod pending.
11. __kubectl get pvc__ should show the first pvc pending

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.4
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  crashCollector:
    disable: false
  cleanupPolicy:
    confirmation: ""
  resources:
  removeOSDsIfOutAndSafeToRemove: false
  storage: 
    useAllNodes: false
    useAllDevices: false
    nodes:  # Here I actually specify which nodes and devices to use for my test cluster
      - name: "storage1" 
        devices:
          - name: "sdb"
      - name: "storage2"
        devices:
          - name: "sdb"
      - name: "storage3"
        devices:
          - name: "sdb"
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```
* operator manifest 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
data:
  ROOK_CSI_ENABLE_CEPHFS: true
  ROOK_CSI_ENABLE_RBD: true
  ROOK_CSI_ENABLE_GRPC_METRICS: true
  CSI_ENABLE_SNAPSHOTTER: true

  CSI_LOG_LEVEL: "3"

  CSI_FORCE_CEPHFS_KERNEL_CLIENT: "true"

  # (Optional) Allow starting unsupported ceph-csi image
  ROOK_CSI_ALLOW_UNSUPPORTED_VERSION: "false"
  ROOK_CSI_CEPH_IMAGE: "quay.io/cephcsi/cephcsi:v2.1.2"

  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
---
# OLM: BEGIN OPERATOR DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
  labels:
    operator: rook
    storage-backend: ceph
spec:
  selector:
    matchLabels:
      app: rook-ceph-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: rook-ceph-operator
    spec:
      serviceAccountName: rook-ceph-system
      containers:
      - name: rook-ceph-operator
        image: rook/ceph:v1.3.7
        args: ["ceph", "operator"]
        volumeMounts:
        - mountPath: /var/lib/rook
          name: rook-config
        - mountPath: /etc/ceph
          name: default-config-dir
        env:
        - name: ROOK_CURRENT_NAMESPACE_ONLY
          value: "false"
     
        - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
          value: "false"

        # The logging level for the operator: INFO | DEBUG
        - name: ROOK_LOG_LEVEL
          value: "INFO"

        # The interval to check the health of the ceph cluster and update the status in the custom resource.
        - name: ROOK_CEPH_STATUS_CHECK_INTERVAL
          value: "60s"

        # The interval to check if every mon is in the quorum.
        - name: ROOK_MON_HEALTHCHECK_INTERVAL
          value: "45s"

        # The duration to wait before trying to failover or remove/replace the
        # current mon with a new mon (useful for compensating flapping network).
        - name: ROOK_MON_OUT_TIMEOUT
          value: "600s"

        # The duration between discovering devices in the rook-discover daemonset.
        - name: ROOK_DISCOVER_DEVICES_INTERVAL
          value: "60m"

        - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
          value: "false"

        - name: ROOK_ENABLE_SELINUX_RELABELING
          value: "true"

        - name: ROOK_ENABLE_FSGROUP
          value: "true"

        # Disable automatic orchestration when new devices are discovered
        - name: ROOK_DISABLE_DEVICE_HOTPLUG
          value: "false"

        - name: DISCOVER_DAEMON_UDEV_BLACKLIST
          value: "(?i)dm-[0-9]+,(?i)rbd[0-9]+,(?i)nbd[0-9]+"

        - name: ROOK_ENABLE_FLEX_DRIVER
          value: "false"

        - name: ROOK_ENABLE_DISCOVERY_DAEMON
          value: "true"

        - name: ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS
          value: 5

        # The name of the node to pass with the downward API
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # The pod name to pass with the downward API
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # The pod namespace to pass with the downward API
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      # Uncomment it to run rook operator on the host network
      #hostNetwork: true
      volumes:
      - name: rook-config
        emptyDir: {}
      - name: default-config-dir
        emptyDir: {}
# OLM: END OPERATOR DEPLOYMENT
```

* Operator's logs, if necessary
```
...
2020-07-15 19:49:44.008308 I | op-osd: 0/3 node(s) completed osd provisioning, resource version 159316
2020-07-15 19:49:44.067147 E | ceph-crashcollector-controller: ceph version not found for image "ceph/ceph:v15.2.4" used by cluster "rook-ceph". attempt to determine ceph version for the current cluster image timed out
2020-07-15 19:49:44.203814 I | op-mgr: setting ceph dashboard "admin" login creds
2020-07-15 19:49:45.400219 I | op-mgr: successfully set ceph dashboard creds
2020-07-15 19:49:48.155918 I | op-osd: osd orchestration status for node storage1 is computingDiff
2020-07-15 19:49:48.374728 I | op-osd: osd orchestration status for node storage1 is orchestrating
2020-07-15 19:49:48.725586 I | op-osd: osd orchestration status for node storage1 is completed
2020-07-15 19:49:48.725603 I | op-osd: starting 1 osd daemons on node storage1
2020-07-15 19:49:48.725614 I | cephclient: getting or creating ceph auth key "osd.1"
2020-07-15 19:49:49.260925 I | op-osd: deployment for osd 1 already exists. updating if needed
2020-07-15 19:49:49.362180 I | op-k8sutil: deployment "rook-ceph-osd-1" did not change, nothing to update
2020-07-15 19:49:49.362216 I | op-osd: started deployment for osd 1
2020-07-15 19:49:49.389341 I | op-osd: osd orchestration status for node storage2 is computingDiff
2020-07-15 19:49:49.853140 I | op-osd: osd orchestration status for node storage2 is orchestrating
2020-07-15 19:49:50.393207 I | op-mgr: dashboard config has changed. restarting the dashboard module.
2020-07-15 19:49:50.393220 I | op-mgr: restarting the mgr module
2020-07-15 19:49:50.884520 I | op-osd: osd orchestration status for node storage2 is completed
2020-07-15 19:49:50.884556 I | op-osd: starting 1 osd daemons on node storage2
2020-07-15 19:49:50.884576 I | cephclient: getting or creating ceph auth key "osd.2"
2020-07-15 19:49:51.714205 I | op-osd: deployment for osd 2 already exists. updating if needed
2020-07-15 19:49:51.805087 I | op-k8sutil: deployment "rook-ceph-osd-2" did not change, nothing to update
2020-07-15 19:49:51.805106 I | op-osd: started deployment for osd 2
2020-07-15 19:49:53.171357 I | op-osd: osd orchestration status for node storage3 is computingDiff
2020-07-15 19:49:53.274291 I | op-osd: osd orchestration status for node storage3 is orchestrating
2020-07-15 19:49:53.472207 I | op-mgr: successful modules: dashboard
2020-07-15 19:49:53.723067 I | op-osd: osd orchestration status for node storage3 is completed
2020-07-15 19:49:53.723103 I | op-osd: starting 1 osd daemons on node storage3
2020-07-15 19:49:53.723125 I | cephclient: getting or creating ceph auth key "osd.0"
2020-07-15 19:49:54.229104 I | op-osd: deployment for osd 0 already exists. updating if needed
2020-07-15 19:49:54.315840 I | op-k8sutil: deployment "rook-ceph-osd-0" did not change, nothing to update
2020-07-15 19:49:54.315853 I | op-osd: started deployment for osd 0
2020-07-15 19:49:54.323809 I | op-osd: 3/3 node(s) completed osd provisioning
2020-07-15 19:49:55.204763 I | cephclient: successfully disallowed pre-octopus osds and enabled all new octopus-only functionality
2020-07-15 19:49:55.204777 I | op-osd: completed running osds in namespace rook-ceph
2020-07-15 19:49:55.204782 I | rbd-mirror: configure rbd-mirroring with 0 workers
2020-07-15 19:49:55.217679 I | rbd-mirror: no extra daemons to remove
2020-07-15 19:49:55.217705 I | op-cluster: Done creating rook instance in namespace rook-ceph
```

* Crashing pod(s) logs, if necessary
```
output showing cephblockpool exists

$ kubectl -n rook-ceph get cephblockpools
NAME          AGE
replicapool   92m

$ kubectl -n rook-ceph describe cephblockpool replicapool
Name:         replicapool
Namespace:    rook-ceph
Labels:       <none>
Annotations:  <none>
API Version:  ceph.rook.io/v1
Kind:         CephBlockPool
Metadata:
  Creation Timestamp:  2020-07-16T12:52:08Z
  Generation:          1
  Managed Fields:
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:failureDomain:
        f:parameters:
          .:
          f:compression_mode:
        f:replicated:
          .:
          f:requireSafeReplicaSize:
          f:size:
    Manager:      OpenAPI-Generator
    Operation:    Update
    Time:         2020-07-16T12:52:08Z
    API Version:  ceph.rook.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:compressionMode:
        f:crushRoot:
        f:deviceClass:
        f:erasureCoded:
          .:
          f:algorithm:
          f:codingChunks:
          f:dataChunks:
        f:replicated:
          f:targetSizeRatio:
      f:status:
        .:
        f:phase:
    Manager:         rook
    Operation:       Update
    Time:            2020-07-16T12:52:08Z
  Resource Version:  476581
  Self Link:         /apis/ceph.rook.io/v1/namespaces/rook-ceph/cephblockpools/replicapool
  UID:               d28efb21-116e-4a7b-a2aa-d7033e710811
Spec:
  Annotations:     <nil>
  Failure Domain:  osd
  Parameters:
    compression_mode:  none
  Replicated:
    Require Safe Replica Size:  true
    Size:                       3
Status:
  Phase:  Created
Events:   <none>
```

```
csi-provisioner log (not crashing, just showing error)

$ kubectl -n rook-ceph logs csi-rbdplugin-provisioner-67c8c967f-vthfw csi-provisioner
I0715 18:47:52.507465       1 feature_gate.go:216] feature gates: &{map[]}
I0715 18:47:52.507534       1 csi-provisioner.go:98] Version: v1.4.0-0-g1d9bad3
I0715 18:47:52.507554       1 csi-provisioner.go:112] Building kube configs for running in cluster...
I0715 18:47:52.520697       1 connection.go:151] Connecting to unix:///csi/csi-provisioner.sock
I0715 18:48:01.649126       1 connection.go:261] Probing CSI driver for readiness
I0715 18:48:01.650906       1 csi-provisioner.go:152] Detected CSI driver rook-ceph.rbd.csi.ceph.com
I0715 18:48:01.653010       1 controller.go:680] Using saving PVs to API server in background
I0715 18:48:01.653255       1 leaderelection.go:241] attempting to acquire leader lease  rook-ceph/rook-ceph-rbd-csi-ceph-com...
I0715 18:48:01.730986       1 leaderelection.go:251] successfully acquired lease rook-ceph/rook-ceph-rbd-csi-ceph-com
I0715 18:48:01.731133       1 leader_election.go:172] new leader detected, current leader: csi-rbdplugin-provisioner-67c8c967f-vthfw
I0715 18:48:01.731199       1 leader_election.go:165] became leader, starting
I0715 18:48:01.731297       1 controller.go:770] Starting provisioner controller rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-67c8c967f-vthfw_52a7b163-ba1b-4585-bb93-72f4c9b6f165!
I0715 18:48:01.731377       1 volume_store.go:97] Starting save volume queue
I0715 18:48:01.732200       1 reflector.go:122] Starting reflector *v1.PersistentVolumeClaim (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:801
I0715 18:48:01.732251       1 reflector.go:122] Starting reflector *v1.StorageClass (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:807
I0715 18:48:01.732287       1 reflector.go:160] Listing and watching *v1.PersistentVolumeClaim from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:801
I0715 18:48:01.732301       1 reflector.go:160] Listing and watching *v1.StorageClass from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:807
I0715 18:48:01.732295       1 reflector.go:122] Starting reflector *v1.PersistentVolume (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:804
I0715 18:48:01.732339       1 reflector.go:160] Listing and watching *v1.PersistentVolume from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:804
I0715 18:48:01.832601       1 controller.go:819] Started provisioner controller rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-67c8c967f-vthfw_52a7b163-ba1b-4585-bb93-72f4c9b6f165!
I0715 18:52:33.095975       1 controller.go:1199] provision "default/www-web-0" class "rook-ceph-block": started
I0715 18:52:33.152237       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"www-web-0", UID:"acfa95c0-58de-4619-94dc-3f35d74f0be1", APIVersion:"v1", ResourceVersion:"140386", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/www-web-0"
I0715 18:52:33.704346       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"www-web-0", UID:"acfa95c0-58de-4619-94dc-3f35d74f0be1", APIVersion:"v1", ResourceVersion:"140386", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Internal desc = pool (replicapool) not found in Ceph cluster
```

**Environment**:
* OS (e.g. from /etc/os-release):

> NAME="Ubuntu"
> VERSION="18.04.4 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.4 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic`

* Kernel (e.g. `uname -a`):

> Linux c1master1 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:

> 7 nodes: 1 master, 3 compute, 3 storage (each has 1 extra HDD for osd usage)
> master is not tainted
> OSD's are only deployed on the 3 storage nodes

* Rook version (use `rook version` inside of a Rook Pod):

> $ rook version
> rook: v1.1.0-beta.0.1113.ge57073c
> go: go1.13.8

* Storage backend version (e.g. for ceph do `ceph -v`):

> $ ceph -v
> ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)

* Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

> Bare metal

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

>$ ceph status
>  cluster:
>    id:     c9f3b58a-fa46-4e2a-93b4-ea34efb00bf8
>    health: HEALTH_OK  services:
>    mon: 3 daemons, quorum a,b,c (age 96m)
>    mgr: a(active, since 36m)
>    osd: 3 osds: 3 up (since 95m), 3 in (since 95m)  data:
>    pools:   1 pools, 1 pgs
>    objects: 0 objects, 0 B
>    usage:   3.0 GiB used, 2.7 TiB / 2.7 TiB avail
>    pgs:     1 active+clean

**Comment by travisn** [comment]
@matthew-mcdermott Please take a look at the troubleshooting guide for [PVCs remaining pending](https://rook.github.io/docs/rook/v1.3/ceph-common-issues.html#pvcs-stay-in-pending-state) to see if that helps identify the issue.

**Comment by matthew-mcdermott** [comment]
@travisn I have gone through that for sure and I have included logs in this issue from the csi-provisioner. Unfortunately, none of that helped in any  way.

**Comment by obensouda** [comment]
I am experiencing a similar issue. In my logs I see the following:
I0801 20:20:01.072688       1 controller.go:1199] provision "lecket/afrijula-pv-claim" class "rook-ceph-block": started
I0801 20:20:01.075684       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"lecket", Name:"afrijula-pv-claim", UID:"32f2902f-6ff7-41e2-a840-18ceb333d309", APIVersion:"v1", ResourceVersion:"84902396", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "lecket/afrijula-pv-claim"
W0801 20:20:01.855343       1 controller.go:887] Retrying syncing claim "32f2902f-6ff7-41e2-a840-18ceb333d309", failure 10
E0801 20:20:01.855420       1 controller.go:910] error syncing claim "32f2902f-6ff7-41e2-a840-18ceb333d309": failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Internal desc = pool (replicapool) not found in Ceph cluster
I0801 20:20:01.855484       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"lecket", Name:"afrijula-pv-claim", UID:"32f2902f-6ff7-41e2-a840-18ceb333d309", APIVersion:"v1", ResourceVersion:"84902396", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Internal desc = pool (replicapool) not found in Ceph cluster
I0801 20:25:01.855688       1 controller.go:1199] provision "lecket/afrijula-pv-claim" class "rook-ceph-block": started
I0801 20:25:01.858584       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"lecket", Name:"afrijula-pv-claim", UID:"32f2902f-6ff7-41e2-a840-18ceb333d309", APIVersion:"v1", ResourceVersion:"84902396", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "lecket/afrijula-pv-claim"
W0801 20:25:02.973188       1 controller.go:887] Retrying syncing claim "32f2902f-6ff7-41e2-a840-18ceb333d309", failure 11
E0801 20:25:02.973241       1 controller.go:910] error syncing claim "32f2902f-6ff7-41e2-a840-18ceb333d309": failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Internal desc = pool (replicapool) not found in Ceph cluster
I0801 20:25:02.973325       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"lecket", Name:"afrijula-pv-claim", UID:"32f2902f-6ff7-41e2-a840-18ceb333d309", APIVersion:"v1", ResourceVersion:"84902396", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Internal desc = pool (replicapool) not found in Ceph cluster

It seams the error is ceph cannot create the replica pool when i apply csi/rbd/storageclass.yaml. When I rung ceph status I get:
[root@rook-ceph-tools-7959b9f77c-6dvrq /]# ceph -s
  cluster:
    id:     ad428ae7-7f8f-481c-8a84-0c8ef6010099
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 6h)
    mgr: a(active, since 5h)
    osd: 3 osds: 3 up (since 6h), 3 in (since 6h)
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   3.0 GiB used, 332 GiB / 335 GiB avail
    pgs:     
 
[root@rook-ceph-tools-7959b9f77c-6dvrq /]#

**Comment by obensouda** [comment]
Thought I would update. I overcame this problem by using the ceph tool to manually create the replicapool. Hope this helps.

**Comment by matthew-mcdermott** [comment]
@obensouda Thank you for that update. I really would like to avoid having to do that, but that information helps.

**Comment by Deaddy** [comment]
Hi,

I can confirm the issue with ceph/ceph-14.2.10 on kubernetes 1.16 running on centos with 3.10.0-1127.19.1.el7.x86_64 kernel, but with v1.3.6 instead of v1.3.8, with unversioned helm chart of rook-ceph and version 1.4.6. Going back to v1.3.4 did allevieate the issue. 

It does not seem to affect already existing clusters, but I have not tested this thoroughly.

The only giveaway that something did not work right in the logs was
> ceph version not found for image "ceph/ceph:v14.2.10" used by cluster "rook-ceph". attempt to determine ceph version for the current cluster image timed out
Everything else looked correctly, it was just completely silent about any created cephcluster crd.

**Comment by kktk-KO** [comment]
For those having `attempt to determine ceph version for the current cluster image timed out` with external cluster, this note may help.

Seems whenever CephBlockPool is created and [reconcile](https://github.com/rook/rook/blob/release-1.7/pkg/operator/ceph/pool/controller.go#L143) is called, [GetImageVersion](https://github.com/rook/rook/blob/release-1.7/pkg/operator/ceph/controller/version.go#L40) is called and `cephCluster.Status.CephVersion` is tested, but there is no guarantee that `CephVersion` exists with external cluster.

One of workaround I took to make it work is to take advantage of [this code](https://github.com/rook/rook/blob/release-1.7/pkg/operator/ceph/cluster/cluster_external.go#L139) which is called when **monitoring is enabled** which is disabled by default and in [the example](https://github.com/rook/rook/blob/release-1.7/cluster/examples/kubernetes/ceph/cluster-external.yaml#L29)
```
kind: CephCluster
...
  monitoring:
    enabled: true
```

I am not sure if this is expected behavior (weird to me), but this workaround works for me.
