### ISSUE TITLE
Adding metadataDevice to already provisioned cluster fdails

### ISSUE THREAD

**Issue by tibkiss** [rook/rook#5851]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Given a ceph cluster provisioned without dedicated metadataDevice.
When we add metadataDevice to the already provisioned OSDs, then the 
metadataDevice is recognised by prepare jobs, but not being activated and used by ceph.

**Expected behavior:**
Adding metadataDevice to a cluster is possible.

**How to reproduce it (minimal and precise):**
1. Create a ceph cluster without metadataDevice
2. Modify the cluster definition by adding metadataDevice
3. Apply the updated cluster definition
4. Validate that metadataDevice is not used.

**File(s) to submit**:
[cluster.yml.txt](https://github.com/rook/rook/files/4941634/cluster.yml.txt)
[rook-ceph-operator.log](https://github.com/rook/rook/files/4941636/rook-ceph-operator.log)
[rook-ceph-osd-prepare-rax.log](https://github.com/rook/rook/files/4941637/rook-ceph-osd-prepare-rax.log)

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 18.04.4 LTS`
* Kernel (e.g. `uname -a`): `Linux rax 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: 3 node bare-metal cluster
* Rook version (use `rook version` inside of a Rook Pod): `v1.3.7`
* Storage backend version (e.g. for ceph do `ceph -v`): 
   Inside rook-operator pod: `ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)`
   Image used for ceph & osds: `ceph/ceph:v15.2.4-20200630`
* Kubernetes version (use `kubectl version`): `v1.14.1`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `Vanilla kubernetes`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
  cluster:
    id:     ebb9d537-0b97-46bb-b477-6e1fbe29c1ac
    health: HEALTH_WARN
            4 daemons have recently crashed

  services:
    mon: 3 daemons, quorum b,c,d (age 3h)
    mgr: a(active, since 2h)
    osd: 6 osds: 6 up (since 3h), 6 in (since 3h)

  data:
    pools:   2 pools, 257 pgs
    objects: 445.84k objects, 1.4 TiB
    usage:   2.4 TiB used, 8.5 TiB / 11 TiB avail
    pgs:     257 active+clean

  io:
    client:   17 KiB/s rd, 834 KiB/s wr, 1 op/s rd, 75 op/s wr
```

**Comment by travisn** [comment]
Adding the metadata device isn't supported by ceph-volume. The layout of the db, wal, and data are really determined by ceph at OSD creation time, so not sure how feasible this would be for ceph to move the db/wal to the metadata device at a later time. @leseb thoughts?

**Comment by leseb** [comment]
The only way would be to destroy and re-create the OSD. I'm closing this since the behavior is expected (see @travisn explanation). Feel free to re-open if you have more concerns. Thanks.
