### ISSUE TITLE
Cluster fails to come up after a reboot

### ISSUE THREAD

**Issue by travisn** [rook/rook#586]
The mons are dependent on a constant network identity. If that identity changes, nobody will be able to connect to the mon. The mon will be rejected.

Ceph enforces that the mon endpoint is what the mon binds to. Putting a k8s service in front of a mon to have a consistent endpoint does not work. 

Currently the mons use the PodIP, which will change at every restart. We must either find a way to soften the ceph endpoint requirements to allow the service translation, or find a way to get a consistent endpoint for everyone to talk to the mons, even after reboot.

**Comment by kokhang** [comment]
We have talked about using a service IP for each mon IP and register each monitor using the service IP. Is that still the plan?

**Comment by travisn** [comment]
that didn't work because the ceph mon doesn't like having an address translation. It wants to bind to the same endpoint that is advertised for connections. There might be a way around that, but haven't found it yet

**Comment by kokhang** [comment]
That is what i mean. Using the service IP as the binding IP.

**Comment by bzub** [comment]
Maybe you could react to the k8s PreStop hook by deleting the mon from the monmap.  Then when a new mon comes up with the same fsid/cluster-name it gets added back into the monmap.  To handle cases where this hook doesn't work (node crash, etc), then using a StatefulSet would help because when the mon comes up again it will have a hostname matching the one that crashed, and some simple logic could be implemented to look for the old mon/IP, so if the IP changed then the replacement could remove the old monmap entry and get added back in with the newly assigned IP address.

**Comment by travisn** [comment]
thanks @bzub, those are good ideas on how to handle migrating between IPs if necessary for the same mon. Though I think we need to solve the problem to get mons to work with the same id across reboots. Otherwise it is a big risk when more than one mon goes down at a time that we won't get quorum after restart.

@kokhang, in the past i tried as well to give the service IP to the mon, but it would not start since it couldn't bind to a locally.

**Comment by bzub** [comment]
@travisn every option that's been passed around regarding this problem tries to avoid quorum loss, for example with three mons, removing a mon from the monmap when the pod is terminated temporarily creates a quarum of two healthy mons, so it would be protected from quorum loss if an unexpected loss of another mon occurred (1 of 2 healthy).

If we decide it's most important to avoid deleting/re-adding mons, one option I just stubled upon is the [multus-cni](https://github.com/Intel-Corp/multus-cni) plugin.  A relatively simple privileged container could put the user's existing CNI config into a multus-cni config, and add another plugin to give the mon pods static IP addresses.  Obviously there are drawbacks to this, most notibly having to support this on a wide variety of k8s deployment types, but other projects like Calico use this approach to modifying the CNI config and seem successful.  Using `HostNetworking` or patching Ceph sources have big drawbacks as well.

Obviously there's myriad ways to go about solving this.  For my own sake at least I'm going to organize the possible solutions and try to think of the pros/cons, maybe tomorrow.

**Comment by hunter** [comment]
We still use the pre-stop cleanup approach for plain ceph in docker. It has a few rough edges but will handle a full cluster reboot. Interesting timing with @bzub raising #592 though, I was thinking about doing a backup of the various 'maps' if the mon container lifecycle changes (a pre-stop hook). Not sure if they can fit directly into a configmap (can't recall if any are >1MB) but could be a slightly safer DR scenario

**Comment by bassam** [comment]
I wonder if we can modify ceph mons to bind to a local interface but still use the specified service IP in the monmap.

**Comment by travisn** [comment]
if we could find a way to use the service IP it would be ideal. Otherwise the options get complicated quickly. I'll sleep better at night knowing we have a simple solution to this.

**Comment by bassam** [comment]
I dont see why ceph monitors can have an option for a `listen-address` and `advertise-address` just like most container friendly services. I'll look into it.

**Comment by bassam** [comment]
I propose we make the following changes:
 * add a new config option to ceph `bind_addr` that is an entity_addr just like `public_addr`. If `bind_addr` is specified the MON will use it to bind locally. If not specified, the MON will default to `public_addr` as it does today. This change will go upstream to Ceph.
 * Rook operator always start the MONs with `public_addr` and `bind_addr` set. The former will be a realted to a K8S service, and the latter will be the private Pod IP.
 * the Rook operator will need to associate a service IP address with each MON (by name). The bind address could change at any time.

With this approach we should be able to move a MON across the cluster and have it continue functioning as expected. 

Thoughts?

/cc @hunter @bzub @travisn @kokhang

**Comment by bzub** [comment]
@bassam If Ceph upstream gives this an OK, then that's perfect.  Somehow I doubt they will, though, considering the insiders at ceph/ceph-docker are regularly pinged about this IP limitation.  Maybe they could be convinced of the change if they realize that the `ClusterIP`/`public_addr` is stable, just like they want for Paxos.  Maintaining a patched Ceph could be the workaround I suppose.

Have we mulled over the idea of adding a stable IP via privileged init container?  I'm in the process of testing this today.  It seems to be viable, I'm just trying to get a clean solution that doesn't touch the PodCIDR range but is still routable from other pods and kube-proxy.

**Comment by hunter** [comment]
Perhaps @leseb may have some thoughts or inputs as part of the ceph/ceph-docker teams

**Comment by bassam** [comment]
some discussion with @gregsforttwo:

```
<bassam> Bassam Tabbara gregsfortytwo: thanks. so would it be possible for a mon to bind to a local address that is different from its public address and have things continue to function correctly? this would be similar to the case where a mon is behind a NAT, the monmap would continue to have the public ip address, but the MONs bind to a private ip.
1:27 PM G<gregsfortytwo> bassam: uh, I think that would be bad if it bound to a different IP
1:28 PM B<bassam> Bassam Tabbara gregsfortytwo: what I'm exploring is that if messages contain a logical identity then the source IP address of a message should not matter. 
1:28 PM G<gregsfortytwo> ah
1:29 PM so, Ceph definitely expects OSDs and monitors to be listening at the advertised IPs
1:29 PM for OSDs, it'll just advertise whatever the daemon bound to on startup
1:29 PM for monitors though, they are identified in the monitor map by the IP address they belong to
1:30 PM so if it binds to a different address, the *messenger* will take it, but other things in the stack will be angry and everybody will just ignore that monitor
1:30 PM (actually I think it will kill itself, but not certain offhand)
1:33 PM B<bassam> Bassam Tabbara gregfortytwo: so if there was a new option bind_addr that enabled the mon to say bind to say 10.0.0.1 address locally but still use public_addr of  24.10.23.1 (which goes in the monmap), and the network layer (routing) can map 24.10.23.1 to 10.0.0.1 reliably, what would be angry?
1:41 PM G<gregsfortytwo> you are discussing more network than I can coherently discuss at that point
1:41 PM I'm not sure how the monitor itself would feel about it (it will try to bind to 24.10.23.1), but if that works then I don't think anybody else will care?
1:41 PM not sure
1:42 PM B<bassam> Bassam Tabbara gregsfortytwo: thanks for the input. I'll try it out. this a common issue when running in environments like Kubernetes.
```

**Comment by bzub** [comment]
**YAY!**

I'm now running my monitors bound to service IPs.  The key was to simply use a privileged init containter to create the service IP on the mon pod's loopback interface, then a sidecar container that uses `socat` to forward TCP from the pod IP to the loopback/service IP, and have the monitor daemon listen on the loopback/service IP.

It.. works!  It's rather simple, and requires no hand-added IPs.  I can't believe I'm not finding this solution in a google search, which is why I'm trying to figure out where the pitfalls are.  Can't find any so far in my testing.

I'm going to make another comment with the YAML files and modifications involved.

**Comment by travisn** [comment]
nice detective work @bzub! definitely some good lessons to learn here and even better if all the kinks get worked out.

**Comment by bzub** [comment]
The issue I was seeing was a typo.  The setup seems to work fine on my cluster.  It will need to be tested with Flannel networking and some networking related kubelet/kube-proxy settings.

Here's my [monitor pod/service definitions](https://gist.github.com/bzub/b1e21c222c195b7e9a2ae34b8f690ff5).

**Comment by leseb** [comment]
There is currently this proposal https://trello.com/c/mgmh0YGO/214-mon-ceph-mon-move that should ease move monitor around and/or at least just change the IP they are advertised with.
The `socat` hack is nice, I've been using something similar for another purpose but never thought about using it for ceph-mon -_-'. Anyway, the hack is fine but we really need to find something in Ceph.

**Comment by cornelius-keller** [comment]
I really think that the approach of @bzub can work, especially in the machine reboot / desater recovery case. 
The only issue I see is that with pods and kubernetes will not guarantee that there is only one instance of the pod running on node. Specially if a health check fails, k8s may shedule a new container even if the other process is still running. So there might be some locking machanism necessaray to ensure that only one process at a time is accessing the monitor volume mount at a time.

**Comment by travisn** [comment]
For context on the limitations of using a service ip for the purpose of a consistent endpoint for each mon... When a service is created for each mon pod, we get this error from the ceph mons trying to connect and create quorum:
```
2017-04-25 20:40:51.325158 7efbfc3fa700  0 -- 10.2.20.17:6790/0 >> 10.3.0.210:6790/0 conn(0xe75d000 :-1 s=STATE_CONNECTING_WAIT_BANNER_AND_IDENTIFY pgs=0 cs=0 l=0)._process_connection connect claims to be 10.2.20.16:6790/0 not 10.3.0.210:6790/0 - wrong node!
```
Here are the pods and services for the mon. From the error message, we see that it is complaining that mon0 claims to be the pod ip `10.2.20.16`, when it is expecting the service ip `10.3.0.210`.
$ kn get pod -o wide
NAME      READY     STATUS    RESTARTS   AGE       IP           NODE
mon0      1/1       Running   0          2m        10.2.20.16   172.17.4.99
mon1      1/1       Running   0          2m        10.2.20.17   172.17.4.99
mon2      1/1       Running   0          2m        10.2.20.18   172.17.4.99
$ kn get svc
NAME      CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
mon0      10.3.0.210   <none>        6790/TCP   2m
mon1      10.3.0.15    <none>        6790/TCP   2m
mon2      10.3.0.135   <none>        6790/TCP   2m
```

**Comment by bzub** [comment]
@cornelius-keller I know that communication (proxy) *to* a service endpoint is cut off if the pod is not healthy (non-`Ready` state).  So that should be OK, especially with well designed `livenessProbe`s and `readinessProbe`s  defined in the container spec.  I would assume k8s stops the proxy for traffic leaving the non-`Ready` pod as well, so if that naughty-mon-pod keeps trying to communicate to a client while being terminated it would look like it's coming from a non-monitor IP and I would hope the client would ignore it.  We should test that scenario though.

A locking mechanism is a good idea to shore-up any edge cases.  This could be implemented by rook-operator or ceph-docker, but I think k8s has that covered well enough with StatefulSets since they wait until a pod is terminated fully before creating its replacement.  So with a mon StatefulSet the only thing to get it working with the socat approach would be to dynamically (in pod) determine which `MON_SERVICE_HOST` to create and bind to, which is easily determined by the consistent hostname StatefulSets provide.  Literally just a simple case statement in the init container that puts the correct IP in a file, and then socat/mon containers use said IP in their configuration.  I'll get this new approach running and share it soon hopefully.

**Comment by bzub** [comment]
I should amend my StatefulSet idea because using the pod's hostname to find the right IP doesn't work with `hostPath` persisted mon data.  Instead it would need to use the `nodeName` of the pod and either check a remote database or configMap to find the IP mapped to it, or convert the nodeName to a standardized naming scheme compatible with mon names.

**Comment by travisn** [comment]
To follow up from the error message I posted yesterday, when that error is disabled in the ceph codebase and allowed to continue, everything seems to work. The mons formed quorum, the osds connected to the mons. 

This supports @bassam's approach for modifying ceph to accept `bind_addr` and `public_addr` and would allow us to rely on the service endpoint for a consistent identity in the mon map even across restarts.

There will still be scenarios where we will fail over monitors, but this way we wouldn't need any workarounds for the power loss (and related) scenarios.

**Comment by bassam** [comment]
After discussion with @travisn we think this can be solved completely in the rook operator. The operator could inject a monmap and get the MONs going again. @travisn will try the approach out and document it.

**Comment by travisn** [comment]
Injecting a monmap will require the coordination of the operator and the mon pods. The operator owns setting what should be in the monmap, while the mon owns deciding when it needs to inject a new monmap. We only need one healthy monitor to come online to restore the cluster.

The operator will decide on the expected monmap during the Operator health check. The sequence would be:
- Check if we have mon quorum. 
- If we have quorum
  - If a mon is down, bring up a new one and remove the bad one
  - If all mons are up, check again at the next health interval
- If we don't have quorum
  - Ensure the mon pods are in Running state. 
    - If any mon pods refuse to start, remove them from the monmap
  - If the running pod IPs don't match the expected pod IPs
    - Update the monmap that is stored in the configmap
  - The operator stops the mon pods and then restarts them. See below for the behavior inside the Rook mon when restarted.
  - Wait for the mons to form quorum again
  - If we have fewer mons than expected (3)
    - add new mons to restore redundancy

When the Rook monitor pod starts, it will compare its local monmap to what the operator desires the monmap to be. If the monmap is not exactly as specified by the operator, the mon will refuse to start and wait for the operator to reconcile the issue and restart the mon.
- If the local monmap does not exist, this is a new monitor
  - Start the mon. No more checks are necessary.
- Retrieve the desired monmap from the Rook API service. The API service gets the monmap from the configmap that the operator set.
- If the local monmap has the same ip as the podIP for this monitor:
  - If the podIP is the same as the desired podIP:
    - Start the mon
  - If the podIP is different than the desired podIP
    - Write an error to the log and wait to be shutdown by the operator
- If the local monmap has a different ip than the podIP:
  - If the podIP is the same as desired monmap
    - Inject the desired monmap using embedded ceph-mon
    - Start the mon
  - If the podIP is different from the desired monmap
    - Write an error to the log and wait to be shutdown by the operator

This has not yet been tested with a prototype. The Rook mon does not have access to the `ceph-mon` command line tool, so will require some basic implementation to test out with our embedded ceph to expose the ceph-mon tool to the Rook mon.

**Comment by travisn** [comment]
To follow up, we are now planning on pursuing the `bind_addr` and `public_addr` with changes to ceph that was described earlier

**Comment by jamiehannaford** [comment]
@travisn Thanks for the great summary and efforts to fix this. Is this under development for v0.5? Any ETA?

**Comment by travisn** [comment]
It is under development for 0.5 and we will hold the release for it. The timeline might still be a few weeks away though.

**Comment by xeor** [comment]
Any ETA? rook on k8s is hard to even test without a solution to this.
Based on https://github.com/rook/rook/projects/6 and the TODO list, I would guess still a couple of more weeks?

**Comment by bassam** [comment]
@xeor we're close now that the bind_addr work made it in into ceph #788 . I would guess an initial fix will go into master by next week. This is looking good for the 0.5 release

**Comment by travisn** [comment]
Good news, the rook changes on top of the bind_addr have shown that restarting a cluster will work when there is a power or other failure. The only assumption is that you set the `dataDirHostPath`  in the rook-cluster.yaml (which will be based on local storage in k8s 1.7 with #796).  Should have this merged in the next couple days.

**Comment by velo** [comment]
Is the v0.5 build available anywhere?
https://hub.docker.com/r/rook/rook/tags/ includes v0.4 only

**Comment by lorenz** [comment]
It appeared 7 minutes ago :)
