### ISSUE TITLE
ceph multisite follow up

### ISSUE THREAD

**Issue by leseb** [rook/rook#5871]
As per @travisn comment: https://github.com/rook/rook/pull/5719#pullrequestreview-452809747

- Refactoring per several suggestions for reducing duplication of parameters and code structure. No impact to functionality, but for code hygiene.
- Integration tests: Critical before the feature comes out of experimental mode.

**Comment by leseb** [comment]
@ alimaredia

**Comment by leseb** [comment]
@alimaredia

**Comment by alimaredia** [comment]
The issues raised in this issue have been split off into other Rook issues
https://github.com/rook/rook/issues/6401 is for Code cleanup & refactoring
https://github.com/rook/rook/issues/6399 is for integration tests
