### ISSUE TITLE
rook client is not needed in the rookd container

### ISSUE THREAD

**Issue by travisn** [rook/rook#588]
The `rook` client tool is not needed in the rookd container. We have a separate container for the client

**Comment by kokhang** [comment]
It was nice to have this in the rook-api. I just had to attach to the rook-api when i wanted to do ceph stuff. I guess i could deploy the rook-tool image but having it in the rook-api saved me a deployment :)

Im ok with this anyways

**Comment by travisn** [comment]
sorry no more undocumented shortcut :)

**Comment by bassam** [comment]
I wonder if we should create a new rook cli container that just has the rook cli and invokes it on the container entrypoint. Maybe this gets combined with the toolbox
