### ISSUE TITLE
OSD CrashLoop with no logs

### ISSUE THREAD

**Issue by nyxi** [rook/rook#5889]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSD enters CrashLoop with no log output after weeks of no issue uptime

**Expected behavior:**
OSD should at least log whatever issue is crashing it

**How to reproduce it (minimal and precise):**

I don't know about reproduction but my circumstances are:

Sometimes, after weeks of no issue uptime, a OSD will enter CrashLoop in our cluster. `kubectl logs` and `kubectl logs --previous=true` gives no output. Only clue is the failing liveness probe: `Liveness probe failed: admin_socket: exception getting command descriptions: [Errno 2] No such file or directory`

When the OSD is in a CrashLoop the CPU load of the node is rougly equal to the number of cores, a large part of the load is due to iowait which I guess makes sense? As there are other containers running on the node utilizing the ceph storage.

The error is preceded by `cluster [WRN] slow request osd_op (...) currently waiting for sub ops` from the monitors for the given osd.

So far the only way I have found to recover from this is to reboot the node. To be fair I haven't tried much else as I do not know what to try in times like these.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Fedora CoreOS 31.20200323.3.2
* Kernel (e.g. `uname -a`): Linux k8s-m2-uv 5.5.10-200.fc31.x86_64 #1 SMP Wed Mar 18 14:21:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: VM on Openstack
* Rook version (use `rook version` inside of a Rook Pod): v1.3.1
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.1
* Kubernetes version (use `kubectl version`): v1.17.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN when the OSD is in a CrashLoop, HEALTH_OK after reboot

**Comment by travisn** [comment]
@nyxi The OSD logging was not working properly until recently just fixed in the [v1.3.8 release](https://github.com/rook/rook/releases/tag/v1.3.8). Can you update to the latest release to see if you can capture better logs for this issue?
