### ISSUE TITLE
"Unable to attach or mount volumes: unmounted volumes" when my node goes down the pod is not recreating to other node 

### ISSUE THREAD

**Issue by jobin-AT** [rook/rook#5898]
Hello,

I have a kubernetes cluster installed and rook ceph deployed successfully.

When i try to create a pvc it works fine. I can see the pvc created also I mounted the storage to container successfully.

When my node goes down kubernetes is trying the recreate the pod on other  node but its not happening due  to storage side issue, please find the below error I am getting.

  Warning  FailedMount         66s   kubelet, test-14.64.local  Unable to attach or mount volumes: unmounted volumes=[mysql-persistent-storage], unattached volumes=[default-token-phmsf mysql-persistent-storage]: timed out waiting for the condition

i have installed the rook using the rook documentation, same steps i used  

I am using the ceph Block Storage in rook 

Anyone experiencing this problem? 

Thanks!

**Comment by jobin-AT** [comment]
please help me on this

**Comment by gulshan1040** [comment]
@jobin-AT 

Can you please share your cluster.yaml and the logs from the kubelet node where pod is trying to run on.

**Comment by jackbauer123** [comment]
@jobin-AT do you have resolved it? I have the same problem.
