### ISSUE TITLE
ceph rdb attached pod failover not happening when node goes down 

### ISSUE THREAD

**Issue by jobin-AT** [rook/rook#5902]
Hello,

I have a kubernetes cluster installed and rook ceph deployed successfully.

When i try to create a pvc it works fine. I can see the pvc created also I mounted the storage to container successfully.

When my node goes down kubernetes is trying the recreate the pod on other node but its not happening due to storage side issue, please find the below error I am getting.

Warning FailedMount 66s kubelet, test-14.64.local Unable to attach or mount volumes: unmounted volumes=[mysql-persistent-storage], unattached volumes=[default-token-phmsf mysql-persistent-storage]: timed out waiting for the condition

i have installed the rook using the rook documentation, same steps i used

I am using the ceph Block Storage in rook

Anyone experiencing this problem?

Thanks!

**Comment by travisn** [comment]
@jobin-AT If the node is not responding, this is a general K8s issue, not specific to rook or ceph. You can read about the details in https://github.com/ceph/ceph-csi/issues/578. If you know the node is gone, you can force delete the pod and K8s will free the volume to be mounted from another node. But if the node ever comes back online while the new pod is active, the volume could be corrupted so you must be careful with this option.
