### ISSUE TITLE
End-to-end / scenario testing

### ISSUE THREAD

**Issue by jhesketh** [rook/rook#5924]
Hi all,

Sorry if this isn't the best place for this, but I wanted to start a discussion
around further testing for rook.io. If this is better off on the mailing list or
elsewhere please let me know :-).

I want to introduce and let you all know about a tool we have been
working on at SUSE to help create scenario and end-to-end tests for rook.io.

The project is unimaginatively called rookcheck and can be round on github:
https://github.com/SUSE/rookcheck

Documentation is published here:
https://rookcheck.readthedocs.io/en/latest/index.html

The goal of rookcheck is to help write end-to-end blackbox tests. Most
of the framework is oriented around bringing up the required hardware,
operating systems, and kubernetes distributions. Each of these layers
can be changed so that it is possible to run scenario tests against both
upstream Kubernetes, SUSE's Containers as a Service Platform, and
(hypothetically in the future) OpenShift etc.

Each of the aforementioned layers is available as an abstraction in
rookcheck. The tests can access these abstractions and their provided
libraries (which, admittedly, still need more fleshing out as tests are
created). Through these libraries a test can do things such as provision
a new node, join it to the Kubernetes cluster, and check that the
appropriate OSD/mon containers are created (if expected).

rookcheck validates the end-to-end deployment by building its own
Kubernetes cluster to then deploy rook into. This can be useful to find
issues with particular distributions or Kubernetes configurations, but
it's also to allow tests to verify rook.io works as expected when the
underlying cluster changes.

rookcheck currently supports OpenStack and libvirt as hardware
providers. We hope that it's not too difficult to add another cloud
provider such as AWS to make it easier to run with existing CI
resources. Similarly, rookcheck is only running on openSUSE and SLES,
but we'd welcome any contributions that add more distributions.
Nevertheless, even without more supported OS's or providers, valuable
tests can be written to exercise and confirm rook.io is working as
expected (on the assumption that the underlying Kubernetes cluster is).

For more information on the approach, take a look at the docs:
https://rookcheck.readthedocs.io/en/latest/theory.html and
https://rookcheck.readthedocs.io/en/latest/structure.html

Currently there aren't very many tests as we are still building out the
framework. We have a few basic ones that demonstrate how future ones
might look. If you're interested in helping out or writing more scenario
tests then please reach out to me :-).

Some example/future tests may be simulating a kernel panic on a
Kubernetes node, abruptly removing an attached OSD volume, or verifying
mons are scheduled on the appropriate nodes etc.

Patches/help welcome of course! But even if you're just playing with it,
do let me know. There's likely some teething issues to be found, and
we'd love any feedback you might have.

Cheers,
Josh

**Comment by BlaineEXE** [comment]
I think @travisn has mentioned it could be good to get this integrated with Ceph's CI and start testing Ceph nightly builds. I think that is a good starting place to get this introduced more widely upstream and to vet out any issues in the project early. @leseb and I had a lot of discussion about the limitations of Rook's existing CI several months ago.

**Comment by travisn** [comment]
Yes, would be great to integrate this as a part of a nightly test run to start with. Then we don't have to sort out issues with the current integration tests compared to the new tests.

**Comment by BlaineEXE** [comment]
Who can Josh and I work with to get this integrated into Ceph's nightly test runs?

**Comment by travisn** [comment]
Today we don't have a nightly test run, we have just been talking about it for a while. A new pipeline would need to be created for running the nightly job, and the corresponding Jenkins config. Let's discuss in huddle.

**Comment by BlaineEXE** [comment]
Update: Sent an email to @akraitman and @jhesketh to make introductions and start planning how to integrate CI with nightly builds.

**Comment by jhesketh** [comment]
FYI I am still interested in trying to get this running for upstream. Things have been progressing slowly and timezones are making meetings difficult, but what is the best way for me to help get this into rook's infra?

**Comment by travisn** [comment]
@jhesketh I'd suggest we find how to do this with github actions. All the workflows have been recently added to Rook [here](https://github.com/rook/rook/tree/master/.github/workflows) that will run with each PR. For this effort though, instead of running with each PR, we might run with each merge to master, or daily, or some other trigger. It would be awesome to have github actions to run the tests against the different platforms instead of just the vanilla versions of k8s.
