### ISSUE TITLE
openshift: rook ceph toolbox container is not correctly loaded

### ISSUE THREAD

**Issue by kdoustar** [rook/rook#5941]
**Is this a bug report or feature request?**
* Bug Report

You are not a good root in this container:

❯ oc exec -it rook-ceph-tools-6b4889fdfd-kvplc -- bash
bash-4.4$ whoami
1000570000
bash-4.4$ sudo su -
sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted
sudo: no valid sudoers sources found, quitting
sudo: setresuid() [0, 0, 0] -> [1000570000, -1, -1]: Operation not permitted
sudo: unable to initialize policy plugin
bash-4.4$

No history, no change, no nothing

**Expected behavior:**
To have a correct and complete root access to the toolbox container 

**How to reproduce it (minimal and precise):**

Install an OKD 4.5 or OKD 4.4 cluster and lunch rook-ceph on it and run this command to login to the toolbox container:

oc exec -it -n rook-ceph rook-ceph-tools-6b4889fdfd-kvplc -- bash

**Environment**:
* OS (e.g. from /etc/os-release):
OKD 4.5 runs on FCOS 32

* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: Bare metal nodes
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.3.0-beta.0.632.gcf28b16
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.4
* Kubernetes version (use `kubectl version`): v1.18.2-0-g52c56ce
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OKD 4.5 GA
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] (https://rook.io/docs/rook/master/ceph-toolbox.html)): health: HEALTH_OK

**Comment by travisn** [comment]
@kdoustar The toolbox is not expected to elevate commands, it is just designed to run ceph commands. For an example of a more privileged toolbox, see the [direct tools](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/direct-mount.yaml) example.

**Comment by kdoustar** [comment]
But it's much better in a normal kubernetes cluster. For example in a Rancher kubernetes:

rke@inf:~$ kubectl exec -n rook-ceph -it rook-ceph-tools-6d659f5579-fcwjl -- bash
Defaulting container name to rook-ceph-tools.
Use 'kubectl describe pod/rook-ceph-tools-6d659f5579-fcwjl -n rook-ceph' to see all of the containers in this pod.
[root@rook-ceph-tools-6d659f5579-fcwjl /]# whoami
root
[root@rook-ceph-tools-6d659f5579-fcwjl /]#

**Comment by travisn** [comment]
What commands are you wanting to run as root? The ceph commands don't require root.
If you want to run privileged, you can always add this to the toolbox.yaml. The yamls in the rook repo are just examples.
```
        securityContext:
          privileged: true
```

**Comment by cangyin** [comment]
@travisn I tried that config with no luck, unfortunately. this is my `toolbox.yaml`
```yaml
          securityContext:
            runAsNonRoot: false
            # runAsUser: 2016
            # runAsGroup: 2016
            privileged: true
```

**Comment by leseb** [comment]
> @travisn I tried that config with no luck, unfortunately. this is my `toolbox.yaml`
> 
> ```yaml
>           securityContext:
>             runAsNonRoot: false
>             # runAsUser: 2016
>             # runAsGroup: 2016
>             privileged: true
> ```
> 
> after re-creating the toolbox deployment and `k exec` into it, I still got non `root` privilege.

What's the issue with the current template?

**Comment by cangyin** [comment]
I am running a kubernetes v1.22.4 cluster, and deployed rook v1.8

this is my retry steps:
![image](https://user-images.githubusercontent.com/50256182/146899141-82ad4ea6-3ddd-42ea-83d9-4ef18569f01a.png)

my modifications to `toolbox.yaml` is annotated in the screenshot.

**Comment by leseb** [comment]
> Thanks for replying.
> 
> I am running a kubernetes v1.22.4 cluster, and deployed rook v1.8
> 
> this is my retry steps: ![image](https://user-images.githubusercontent.com/50256182/146899141-82ad4ea6-3ddd-42ea-83d9-4ef18569f01a.png)
> 
> my modifications to `toolbox.yaml` is annotated in the screenshot.

The user is `rook` because this is the default user in the container image. See:
https://github.com/rook/rook/blob/7a4f3966c48fb9253c18d6958294249fdde22d76/images/ceph/Dockerfile#L33-L34

But what is the issue precisely? Thanks

**Comment by cangyin** [comment]
Just that I can't use `sudo` or `su` commands
![image](https://user-images.githubusercontent.com/50256182/146901063-ae038de4-d46c-49b7-b4a5-c01e9ae8e836.png)

Maybe I should turn to direct tools as @travisn suggested.

**Comment by leseb** [comment]
You can use `runAsUser: 0` in this case.

**Comment by cangyin** [comment]
@leseb Thanks! It works!
