### ISSUE TITLE
ceph: add `bind_addr` to ceph monitors

### ISSUE THREAD

**Issue by bassam** [rook/rook#595]
See https://github.com/rook/rook/issues/586#issuecomment-295394396

**Comment by bzub** [comment]
Is this p[roposed Ceph feature](https://trello.com/c/mgmh0YGO/214-mon-ceph-mon-move) close enough?

**Comment by bassam** [comment]
@bzub unfortunately not. I think the proposal of creating temp entries in the monmap seems complex for what we need here. I'm going to writeup a proposal/blueprint to submit upstream to ceph, but the idea is that if the ceph messenger can support 2 separate IP addresses -- `listen` and `advertise` then we can solve this problem with using K8S services.

**Comment by bassam** [comment]
After discussion with @travisn I think there might be a way to solve this in the rook operator. Essentially the operator would inject a monmap with the correct IP address to bring them back up in the event of power failure. @travisn will try this and document it.

**Comment by bassam** [comment]
For tracking here's the PR in ceph: https://github.com/ceph/ceph/pull/16189
