### ISSUE TITLE
Build fails on mac from invalid path to prometheus rules

### ISSUE THREAD

**Issue by travisn** [rook/rook#5958]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The build is failing on a mac due to an invalid path to prometheus rules:
```
=== container build build-a63aad4e/ceph-amd64
cp: ../../cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules-external.yaml: No such file or directory
cp: ../../cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v15-rules.yaml: No such file or directory
make[2]: *** [do.build] Error 1
make[1]: *** [ceph.linux_amd64] Error 2
make: *** [build] Error 2
```

**Expected behavior:**
The build should succeed on all dev platforms.

**How to reproduce it (minimal and precise):**

On a mac:
```
make build
```

**Comment by leseb** [comment]
I don't run Docker on Mac anymore, I build on Linux. Could it be an issue with the Docker version not follow the symlink relative path?
