### ISSUE TITLE
rook-ceph-mgr-a  pod :  "CrashLoopBackOff"   and possible memory leak. 

### ISSUE THREAD

**Issue by Ultra4life** [rook/rook#6000]
Hi to all,

It's **first time** i'm posting on github for help so sorry in advance if i forget important details, just ask for more if needed :)

Me and my collegue are trying to administrate a Devops Foundry using k8s and rook ceph.
_We actually have serious probleme getting the MGR working properly_.

**Expected behavior:**

The MGR pod should be running properly and not consume to much memory.   
(in crd)
mgr:
      limits:
      cpu: "500m"
     memory: "1024Mi"

**How to reproduce it (minimal and precise):**

On v1.1.7  the mgr pod were tacking way to much memory (possible memory leak) so we upgraded rook to version v1.3.7
but we may have f**** up the ServiceAccount for mgr in the process since its showing today : 

kind: ServiceAccount
metadata:
  creationTimestamp: "2019-12-06T15:22:52Z"
  labels:
    chart: rook-ceph-v1.1.7

* MGR's pod logs, if necessary

```
[06/Aug/2020:13:50:04] ENGINE Serving on http://0.0.0.0:9283
[06/Aug/2020:13:50:04] ENGINE Bus STARTED
debug 2020-08-06T13:50:05.319+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13147579 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.320+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13147483 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.320+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13204940 -' entity='client.crash' cmd=[{"prefix": "crash post", "target": ["mon-mgr", ""]}]: dispatch
debug 2020-08-06T13:50:05.322+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.12094283 -' entity='client.csi-rbd-provisioner' cmd=[{"image_spec": "builds-r1/csi-vol-b47fa0bd-d30a-11ea-a2eb-72f121e0663b", "prefix": "rbd task add remove", "target": ["mgr", ""]}]: dispatch
debug 2020-08-06T13:50:05.325+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13151851 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.326+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.12094511 -' entity='client.csi-rbd-provisioner' cmd=[{"image_spec": "monitoring-r1/csi-vol-5bb629a1-a733-11ea-91a6-1e72bbfcc7ba", "prefix": "rbd task add remove", "target": ["mgr", ""]}]: dispatch
debug 2020-08-06T13:50:05.326+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.12085737 -' entity='client.csi-rbd-provisioner' cmd=[{"image_spec": "monitoring-r3/csi-vol-5d68973b-c1ee-11ea-a223-da83f88a0486", "prefix": "rbd task add remove", "target": ["mgr", ""]}]: dispatch
debug 2020-08-06T13:50:05.327+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13153641 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.327+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13151859 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.328+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.12094483 -' entity='client.csi-rbd-provisioner' cmd=[{"image_spec": "monitoring-r3/csi-vol-b8922a57-c4f6-11ea-94aa-d27e431a096f", "prefix": "rbd task add remove", "target": ["mgr", ""]}]: dispatch
debug 2020-08-06T13:50:05.329+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13153809 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.329+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13133234 -' entity='client.crash' cmd=[{"prefix": "crash post", "target": ["mon-mgr", ""]}]: dispatch
debug 2020-08-06T13:50:05.330+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.12085889 -' entity='client.csi-rbd-provisioner' cmd=[{"image_spec": "monitoring-r1/csi-vol-8347786b-af0b-11ea-91a6-1e72bbfcc7ba", "prefix": "rbd task add remove", "target": ["mgr", ""]}]: dispatch
debug 2020-08-06T13:50:05.330+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.12085869 -' entity='client.csi-rbd-provisioner' cmd=[{"image_spec": "builds-r1/csi-vol-0526fe14-cd91-11ea-ae5b-a273a14ecc5d", "prefix": "rbd task add remove", "target": ["mgr", ""]}]: dispatch
debug 2020-08-06T13:50:05.330+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13153829 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.341+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13129366 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.342+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13141951 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.342+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13141967 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "target": ["mgr", ""], "mode": "upmap", "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.342+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13206803 -' entity='client.admin' cmd=[{"prefix": "osd ok-to-stop", "target": ["mgr", ""], "ids": ["7"], "format": "json"}]: dispatch
debug 2020-08-06T13:50:05.342+0000 7f400c724700 -1 mgr.server reply reply (11) Resource temporarily unavailable 191 pgs have unknown state; cannot draw any conclusions
debug 2020-08-06T13:50:05.343+0000 7f400c724700  0 log_channel(cluster) log [DBG] : pgmap v2: 191 pgs: 182 active+clean, 9 unknown; 103 GiB data, 317 GiB used, 467 GiB / 792 GiB avail
debug 2020-08-06T13:50:06.093+0000 7f401572a700  0 log_channel(cluster) log [DBG] : pgmap v3: 191 pgs: 182 active+clean, 9 unknown; 103 GiB data, 317 GiB used, 467 GiB / 792 GiB avail
debug 2020-08-06T13:50:07.273+0000 7f400c724700  0 log_channel(audit) log [DBG] : from='client.13158173 -' entity='client.crash' cmd=[{"prefix": "crash post", "target": ["mon-mgr", ""]}]: dispatch
debug 2020-08-06T13:50:08.094+0000 7f401572a700  0 log_channel(cluster) log [DBG] : pgmap v4: 191 pgs: 182 active+clean, 9 unknown; 103 GiB data, 317 GiB used, 467 GiB / 792 GiB avail
debug 2020-08-06T13:50:10.094+0000 7f401572a700  0 log_channel(cluster) log [DBG] : pgmap v5: 191 pgs: 182 active+clean, 9 unknown; 103 GiB data, 317 GiB used, 467 GiB / 792 GiB avail
debug 2020-08-06T13:50:12.095+0000 7f401572a700  0 log_channel(cluster) log [DBG] : pgmap v6: 191 pgs: 182 active+clean, 9 unknown; 103 GiB data, 317 GiB used, 467 GiB / 792 GiB avail; 20 KiB/s wr, 2 op/s
debug 2020-08-06T13:50:14.095+0000 7f401572a700  0 log_channel(cluster) log [DBG] : pgmap v7: 191 pgs: 182 active+clean, 9 unknown; 103 GiB data, 317 GiB used, 467 GiB / 792 GiB avail; 16 KiB/s wr, 1 op/s
10.233.94.75 - - [06/Aug/2020:13:50:15] "GET /metrics HTTP/1.1" 200 159028 "" "Prometheus/2.13.1"
debug 2020-08-06T13:50:16.096+0000 7f401572a700  0 log_channel(cluster) log [DBG] : pgmap v8: 191 pgs: 182 active+clean, 9 unknown; 103 GiB data, 317 GiB used, 467 GiB / 792 GiB avail; 42 KiB/s wr, 3 op/s
```

* Crashing pod(s) logs, if necessary

rook-ceph-mgr-a-7f598bdfd8-vzbkz                    --      0/1     CrashLoopBackOff   1758       7d3h

```
 State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
```

(limits are set in crd with valors you can see at the beguinning, nothing anormal) 

**Environment**:
Linux  3.10.0-862.el7.x86_64  2018 x86_64 x86_64 x86_64 GNU/Linux
REDHAT 7

*image
Image:         ceph/ceph:v15.2.4-20200630

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 10.2.5

* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2",  Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2",  Platform:"linux/amd64"}

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
`HEALTH_WARN no active mgr; clock skew detected on mon.af, mon.ag, mon.ah; mon ah is low on available space; Reduced data availability: 9 pgs inactive; 8 pool(s) have no replicas configured; 1 pool(s) have non-power-of-two pg_num; 1015 slow ops, oldest one blocked for 284432 sec, daemons [osd.4,osd.5] have slow ops.`

Thank in advance to all for your precious help :)

**Comment by Ultra4life** [comment]
Nobody ? =$

**Comment by leseb** [comment]
Hum a few questions:

* version of ceph: you mentioned `ceph/ceph:v15.2.4-20200630` as an image but later you wrote `ceph version 10.2.5`, which one is true?
* if the mgr memory keeps growing to the point it get OOMKiled I'd suggest either to upgrade to a new version of Ceph as well as opening a tracker issue on Ceph: https://tracker.ceph.com/, if the leak is real and not fixed in Ceph, there is nothing we can do in Rook. However, we haven't seen such report before.
* be careful if your mons are running out of space, a system running out of space falls apart really quickly

**Comment by Ultra4life** [comment]
"ceph version" in toolbox give me : ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)

Thank a lot for the answer.

**Comment by galexrt** [comment]
@Ultra4life The toolbox version is not the same as the Cluster.
Check your CephCluster object / yaml for the `cephVersion` struct that is the Ceph version that is being used.

**Comment by Ultra4life** [comment]
![wtf](https://user-images.githubusercontent.com/61144541/90792996-7678e000-e30b-11ea-865a-593aed850e0f.jpg)

I'm not sure what is happening, i though the command were the same but i'm getting two differente anwer

**Comment by leseb** [comment]
`ceph -v` is the binary version where `ceph version` is a call to the cluster and reports the ceph mon daemon running version.

**Comment by leseb** [comment]
I'd suggest opening an issue on https://tracker.ceph.com/, unfortunately, if the daemon consumes too much memory Rook cannot do anything about this.

**Comment by Ultra4life** [comment]
I'm about to try a downgrade version (CSI driver) in deploy of MGR, bacause that one of my last option to make it work.. 
Any other idea please ?

**Comment by leseb** [comment]
You could gradually downgrade to 15.2.3, 15.2.2 and so forth

**Comment by Ultra4life** [comment]
Again, thx a lot for answering and tacking time for my problemes :)

He is more detail about the cluster health :
`HEALTH_WARN no active mgr; clock skew detected on mon.az, mon.ba, mon.bc; mon ba is low on available space; Reduced data availability: 9 pgs inactive; 8 pool(s) have no replicas configured; 1 pool(s) have non-power-of-two pg_num; 8 pools have too few placement groups; 1543 slow ops, oldest one blocked for 340224 sec, daemons [osd.4,osd.5,osd.6] have slow ops.
`

**Comment by Ultra4life** [comment]
i posted a demand on Ceph-tracker ;)

**Comment by Ultra4life** [comment]
Here is a list of module for MGR
always_on_modules": [
        "balancer",
        "crash",
        "devicehealth",
        "orchestrator",
        "osd_support",
        "pg_autoscaler",
        "progress",
        "rbd_support",
        "status",
        "telemetry",
        "volumes"
    ],
    "enabled_modules": [
        "dashboard",
        "iostat",
        "orchestrator_cli",
        "prometheus",
        "restful",
        "rook" 

Can i desactivate some of them to gain performance ?

**Comment by leseb** [comment]
You can remove the dashboard if you don't use it.

**Comment by leseb** [comment]
I'm closing this now since a ceph tracker is handling this. Thanks
