### ISSUE TITLE
Option ROOK_HOSTPATH_REQUIRES_PRIVILEGED has vague description (doesn't mention SELinux)

### ISSUE THREAD

**Issue by vd-rd** [rook/rook#6009]
Hello,

When standing up a Rook cluster one can ignore the option above to be set to true when not on a Openshift install.
However, if you're running your cluster with SElinux enabled and enforcing the ceph-crash-collector pods will fail and block the overall deployment.

The current description states:
```
# Whether to start pods as privileged that mount a host path, which includes the Ceph mon and osd pods.
# This is necessary to workaround the anyuid issues when running on OpenShift.
# For more details see https://github.com/rook/rook/issues/1314#issuecomment-355799641
```
Please update it to reference SElinux mitigations as it is much simpler to keep it grouped with the other SElinux related options.
I managed to resolve this configuration issue after i have found  #1911 and #1314

**Environment**:
Kubernetes 1.18.6 with CRI-O 1.18.2
SELinux enforcing on hosts running Centos8

**Comment by travisn** [comment]
@vd-rd What wording would help clarify this for you in the comment? Or what do you mean to keep it grouped with the other SElinux options?

**Comment by vd-rd** [comment]
In the operator.yaml ROOK_ENABLE_SELINUX_RELABELING is also related to SELinux.

To answer your first question:
```
# Whether to start pods as privileged that mount a host path, which includes the Ceph mon and osd pods.
# Set true for SElinux enforcing or Openshift environments to workaround the anyuid issues.
# For more details see https://github.com/rook/rook/issues/1314#issuecomment-355799641
```
I guess even if you decide not to edit the description in operator.yaml some people that stumble upon the same problem will find this issue helpful.
