### ISSUE TITLE
Prometheus Rule failures with 'rook-ceph-prometheus-ceph-v15-rules.yaml;telemeter.rules' in 1.4.0

### ISSUE THREAD

**Issue by billimek** [rook/rook#6011]
* Bug Report

**Deviation from expected behavior:**

After upgrading rook from v1.3.9 to v1.4.0, there are Prometheus Rule failures with `rook-ceph-prometheus-ceph-v15-rules.yaml;telemeter.rules`

![image](https://user-images.githubusercontent.com/6393612/89651248-a6e36780-d891-11ea-9ea5-0da3c289d27d.png)

**Expected behavior:**

**How to reproduce it (minimal and precise):**

After manually executing all of the `telemeter.rules` PrometheusRule, I was able to narrow-down the issue to the following two rules:

```
sum(kubelet_volume_stats_used_bytes * on (namespace,persistentvolumeclaim) group_right() (kube_persistentvolumeclaim_info * on (storageclass)  group_left(provisioner) kube_storageclass_info {provisioner=~".*rbd.csi.ceph.com"}))
sum(kubelet_volume_stats_used_bytes * on (namespace,persistentvolumeclaim) group_right() (kube_persistentvolumeclaim_info * on (storageclass)  group_left(provisioner) kube_storageclass_info {provisioner=~".*cephfs.csi.ceph.com"}))
```

Which seem to have been introduced in a recent commit: https://github.com/rook/rook/commit/f3eea6ebb7c198871dd705bc67c0c2c43c1002b3

Added comments to the changes directly in the commit, but will recreate here as well:

For the new rules 

* `sum(kubelet_volume_stats_used_bytes * on (namespace,persistentvolumeclaim) group_right() (kube_persistentvolumeclaim_info * on (storageclass)  group_left(provisioner) kube_storageclass_info {provisioner=~".*rbd.csi.ceph.com"}))` 
* `sum(kubelet_volume_stats_used_bytes * on (namespace,persistentvolumeclaim) group_right() (kube_persistentvolumeclaim_info * on (storageclass)  group_left(provisioner) kube_storageclass_info {provisioner=~".*cephfs.csi.ceph.com"}))`

There seems to be a rule evaluation failure when a cluster has other storageclasses present (my guess - not sure what the root-cause is):

```
Error executing query: found duplicate series for the match group {namespace="default", persistentvolumeclaim="nfs-data-pvc"} on the left hand-side of the operation: [{__name__="kubelet_volume_stats_used_bytes", endpoint="https-metrics", instance="k3s-0", job="kubelet", metrics_path="/metrics", namespace="default", node="k3s-0", persistentvolumeclaim="nfs-data-pvc", prometheus="monitoring/prometheus-operator-prometheus", service="prometheus-operator-kubelet"}, {__name__="kubelet_volume_stats_used_bytes", endpoint="https", exported_namespace="default", instance="10.2.0.30:6443", job="apiserver", namespace="default", persistentvolumeclaim="nfs-data-pvc", prometheus="monitoring/prometheus-operator-prometheus", service="kubernetes"}];many-to-many matching not allowed: matching labels must be unique on one side
```

(for reference):

```console
➜ k get storageclasses.storage.k8s.io -o=wide
NAME                        PROVISIONER                            RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
rook-cephfs                 rook-ceph.cephfs.csi.ceph.com          Delete          Immediate           true                   186d
rook-ceph-block (default)   rook-ceph.rbd.csi.ceph.com             Delete          Immediate           true                   186d
nfs-client                  cluster.local/nfs-client-provisioner   Delete          Immediate           true                   300d
```

**File(s) to submit**:

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 20.04
* Kernel (e.g. `uname -a`): 5.4.0-42-generic
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod): 1.4.0
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.4
* Kubernetes version (use `kubectl version`): v1.18.6+k3s1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by billimek** [comment]
FYI @anmolsachan ^^^

**Comment by anmolsachan** [comment]
@travisn Please assign this to me. The rules creating the issue are no longer required.
I will send the fix with an explanation.
