### ISSUE TITLE
Rook keeps re-creating deleted OSD pods

### ISSUE THREAD

**Issue by psarossy** [rook/rook#6016]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I followed the OSD removal docs, then nuked the NVMe devices as usual, but the rook operator keeps recreating the deployments/pods for the OSDs that are no longer in the crushmap, or mentioned anywhere I could think of to look.

I can't readd my storage devices as the prepare pods pick the next available OSD number to provision, which is taken because the operator creates the pod and generates a key for the OSD before starting the prepare pod.

I've been able to add 7 of the 10 new devices without issues. It's scheduling pods on 3 different hosts. I spent the whole day trying to figure out where the hell it's getting the configuration data from as the pods always refer to the same OSD_UUIDs etc.

**Expected behavior:**
Deleted OSDs would not get recreated.

**How to reproduce it (minimal and precise):**
I'm not sure to be honest. I did everything like I do it every time when I add new devices to the nodes (zap, dd or discard, make sure there are no lvm volume references for them or /dev/ceph-*, then restart the operator)

**File(s) to submit**:

Cluster CR (the actual, I haven't used the yaml since creation): https://pastebin.com/kjccqZiL

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
* Kernel (e.g. `uname -a`): 4.15.0-112-generic #113-Ubuntu
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod):   v1.3.1
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.8
* Kubernetes version (use `kubectl version`): v1.18.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Baremetail with kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@psarossy Can you share the logs for the osd prepare job when the old osd is unexpectedly being detected? That log should give an indication why it discovered the old osd. `ceph-volume` reads the disk directly to see if it has been used in the current cluster or a different cluster. It seems that it is still detected some metadata on the disk and starting up the same osd.

**Comment by psarossy** [comment]
@travisn while gathering the info you asked for, I figured it out... The root cause is essentially #4529 I have a usb thumb drive in ever server on the motherboard used for disaster recovery.

So I went and wiped it manually and created a partition on it, then `ceph-volume` happily took that, and provisioned it as storage....

I guess this is my own fault, but the bash script to find out what osd is on which device doesn't work and I could have had and aha moment earlier, instead of searching for the ID by brute force and eventually finding the weird entry in /var/lib/rook/rook-ceph/log/ceph-volume.log will open a separate bug about that.
