### ISSUE TITLE
Ceph: implement event reporting for various CRs

### ISSUE THREAD

**Issue by rohantmp** [rook/rook#6042]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

We should report failures as events.
We should report successful completions as events where possible
This way, each action will eventually result in either a success or failure.

**What is use case behind this feature:**

Operator logs can get lost and/or be too verbose. Events persist failures and associate them with a CR.

**Comment by rohantmp** [comment]
** events are reported using [EventRecorder](https://godoc.org/k8s.io/client-go/tools/record#EventRecorder) which takes: **

`obj` :  a reference to an object to associate the event with.
`eventType`: a string used to group events. (So tools can display something like: `5 someEventType events`)
`msg`: a string for additional context
`annotations` : optional `map[string]string` the purpose of which I haven't explored wrt events

**controller-runtime implementation details:**

EventRecorder can be obtained from [manager](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/manager#Manager) using `manager.GetEventRecorderFor(name string) record.EventRecorder`

**addtional ideas:**

Events can be deduplicated depending on context some signature. Here's example in [local-storage-operator](https://github.com/openshift/local-storage-operator/blob/b3f091875c4b941364d1c0e16fd5138a31917082/pkg/diskmaker/controllers/lvset/event_reporter.go#L42)
there, an event is only reported once for each `Disk`, `eventType` and `Reason` unless the operator restarts and it occurs again.

**Comment by rohantmp** [comment]
closing temporarily as I don't know how to prevent this from blocking the release

**Comment by leseb** [comment]
Assigned to @iamniting, did you sync with @rohantmp that it was ok to work on this?

**Comment by iamniting** [comment]
Yes, I synced up with @rohantmp before working on it.
