### ISSUE TITLE
rook-ceph-crashcollector Pod pause in init

### ISSUE THREAD

**Issue by liyk1024** [rook/rook#6044]
kubectl get pod -n rook-ceph
rook-ceph-crashcollector-node1-6c49d6446f-mzhjj   0/1     Init:0/2

kubectl describe -n rook-ceph pod rook-ceph-crashcollector-node1-6c49d6446f-mzhjj
MountVolume.SetUp failed for volume "rook-ceph-crash-collector-keyring" : secret "rook-ceph-crash-collector-keyring" not found

secret is without this "rook-ceph-crash-collector-keyring"

**Comment by leseb** [comment]
Please re-open using the issue template.
