### ISSUE TITLE
Allow additional labels to be added to Components created by the Rook Operators

### ISSUE THREAD

**Issue by galexrt** [rook/rook#6050]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Allow additional labels to be specified for components created by the Rook (Ceph) operator.

**What is use case behind this feature:**

Additional labels allow for elaborate monitoring and logging setups, and can be useful for automatic component mappings (e.g., owner) of the component Pods.

**Comment by travisn** [comment]
This issue was completed by #6082
