### ISSUE TITLE
rook default version is master but not set

### ISSUE THREAD

**Issue by zhangjianweibj** [rook/rook#6051]
![image](https://user-images.githubusercontent.com/18585129/90006783-24f9a100-dccc-11ea-9acf-b9687135dbaa.png)

i run git clone project, and run helm install /rook/cluster/charts/rook-ceph.then find a error with image no version.and in readme file,tag default value should master value.

**Comment by AXington** [comment]
don't use master, use one of the version branches, 1.4 is latest
