### ISSUE TITLE
rook/cassandra Operator v1.4.0 is breaking when adding annotations to the rack level, whereas this works in operator v1.3.7

### ISSUE THREAD

**Issue by ssandanshi** [rook/rook#6054]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
It should support rack-level annotations as there have been no changes in operator except CVE fixes from v1.3.7 to v1.4.0

**Expected behavior:**
The Cassandra cluster should be successfully created with rack-level annotations

**How to reproduce it (minimal and precise):**

1. Install the cassandra operator v1.4.0
2. After the operator is running, apply the attached cluster.yaml using `kubectl apply -f cluster.yaml`
4. look at operator pod. It will be in a CrashLoopBackOff

Error message - 
`2020-08-12 16:05:25.844290 I | cassandra-controller: Attempting to create Rack us-east-1a
E0812 16:05:25.844450       6 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)`

Note: for detailed error message, look at attached logs
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary - 
[cluster.yaml.zip](https://github.com/rook/rook/files/5064346/cluster.yaml.zip)
 (unzip for yaml file)

* Operator's logs, if necessary - [cassandra_logs.txt](https://github.com/rook/rook/files/5064137/cassandra_logs.txt)
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Mac
* Kernel (e.g. `uname -a`): 19.6.0 Darwin Kernel Version 19.6.0
* Cloud provider or hardware configuration: docker desktop and eks.1
* Rook version (use `rook version` inside of a Rook Pod): v1.4.0
* Storage backend version (e.g. for ceph do `ceph -v`): N/A
* Kubernetes version (use `kubectl version`): 1.16.5 (1.16 for eks)
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): docker-desktop and eks
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): N/A

**Comment by vayyappaneni** [comment]
I am experiencing the same issue. I was able to set the annotations at rack level in 1.3.7 version. I recently upgraded to 1.4.0 and noticed operator is failing. As a work around I set the annotation at spec level and removed rack level annotations.

**Comment by travisn** [comment]
The fix will be in v1.4.1 (targeted for tomorrow) with #6056
