### ISSUE TITLE
existingSecret for ceph-dashboard

### ISSUE THREAD

**Issue by cyrilcros** [rook/rook#6055]
**Is this a bug report or feature request?**
* Feature Request 
Quite similar to [#2796](https://github.com/rook/rook/issues/2796#issue-419152078)

**What should the feature do:**
Allows user to set the ceph-dashboard admin password in the Rook operator chart, but by pointing to an existing secret with the password - and definitely not by keeping the password in clear text in the `values.yaml`, which is why #2796 was closed.
Alternatively, create a dedicated read only role from that password if admin is too strong.

**What is use case behind this feature:**
Ease of life improvement; you can keep safely the dashboard password in a password manager and go to the dashboard to quickly debug what is wrong. This is notably useful when exploring the chart configuration options for a first set up.

**Comment by cyrilcros** [comment]
Just tried this: merely creating a secret `rook-ceph-dashboard-password` with a `password` key in the right namespace also does the trick.
The password is set around that line: https://github.com/rook/rook/blob/dfc701805abdf852c4122dc6e5c75db9a303d372/pkg/operator/ceph/cluster/mgr/dashboard.go#L232 

The only effect seems to be a warning message.

**Comment by travisn** [comment]
@cyrilcros What warning message are you referring to? This one is just informational so it will be fine:
```
the dashboard secret was already generated
```

The expected way to set a desired password instead of a generated password is to create (or edit) the secret as you have done. How about if we just add a comment about this to the [Dashboard topic](https://rook.github.io/docs/rook/v1.4/ceph-dashboard.html#login-credentials)?

**Comment by cyrilcros** [comment]
@travisn Thanks for your reply. You are right, it isn’t a warning but just a log message. A comment in the docs will be perfect. 
I ended up using [SealedSecrets](https://github.com/bitnami-labs/sealed-secrets) to manage that secret and that works out fine.
