### ISSUE TITLE
Confusing error if block image already exists

### ISSUE THREAD

**Issue by BenHall** [rook/rook#606]
When using `rook block create`, if the name already exists it will return with a 500 error without an indication of why.

Here is my initial test case. 

```
root@rook-tools:/# rook block create --name test --size 1048
succeeded created image test
root@rook-tools:/# rook block create --name test --size 1048
failed to create new block image '{Name:test PoolName:rbd Size:1048 Device: MountPoint:}': HTTP status code 500 for query image: ''
root@rook-tools:/# rook block create --name test2 --size 1048
succeeded created image test2
root@rook-tools:/# rook block create --name test --size 1048
failed to create new block image '{Name:test PoolName:rbd Size:1048 Device: MountPoint:}': HTTP status code 500 for query image: ''
root@rook-tools:/# rook block create --name test2 --size 1048
failed to create new block image '{Name:test2 PoolName:rbd Size:1048 Device: MountPoint:}': HTTP status code 500 for query image: ''
root@rook-tools:/# rook block create --name test4 --size 1048
succeeded created image test4
```

**Comment by jbw976** [comment]
Thanks for reporting this @BenHall.  In general, the API server returns a status code only with no message and writes the error message to its logs.  This was a poor original design decision (my fault) that we should rectify across the entire API server code base.  That would be doable without an enormous amount of effort.

**Comment by travisn** [comment]
with the dynamic provisioner this is done differently now. Closing since the api has been deprecated
