### ISSUE TITLE
v1.4.1 K8s v1.17.5 v1beta1.VolumeSnapshotContent errors

### ISSUE THREAD

**Issue by Antiarchitect** [rook/rook#6067]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Errors in csi-rbdplugin-provisioner log:
```
E0813 11:41:22.198321       1 reflector.go:156] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
```

**Expected behavior:**
No errors in csi-rbdplugin-provisioner log
**How to reproduce it (minimal and precise):**
Just upgrade v1.3.9 to v1.4.x

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.4.0
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): v1.17.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
@Antiarchitect Have you followed the upgrade https://github.com/rook/rook/blob/master/Documentation/ceph-upgrade.md#csi-snapshots and snapshot pre-req https://github.com/rook/rook/blob/master/Documentation/ceph-csi-snapshot.md#prerequisites doc? you need to install snapshot beta CRD.

**Comment by Madhu-1** [comment]
@travisn I see a problem if we disable snapshotter based on the CRD.  Am not sure the snapshot client can be used for both beta and next version(when the snapshot is moved to GA) ( we may face difficulties in handling both cases). isn't it good to document it to install CRD if we face the problem?

**Comment by Antiarchitect** [comment]
When I try to create snapshotclass from cluster/examples/kubernetes/ceph/csi/rbd/snapshotclass.yaml moidfied according to my cluster I get this error on deploy:
```
no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1"
```

**Comment by Madhu-1** [comment]
@Antiarchitect have you create the snapshot class  CRD?

**Comment by Antiarchitect** [comment]
@Madhu-1 Where can I get the CRD, or should I enable something in Rook?

**Comment by Madhu-1** [comment]
see the second point in prereq https://github.com/rook/rook/blob/master/Documentation/ceph-csi-snapshot.md#prerequisites

you need to  create snapshot CRD and install snapshot controller
you can follow https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.1#usage

**Comment by Antiarchitect** [comment]
@Madhu-1 Thank you, I will experiment with this later

**Comment by Antiarchitect** [comment]
I thought (reading values.yaml) that Rook should run snapshotter by itself, am I wrong?
I created CRDs but the error stays (no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1")

**Comment by Madhu-1** [comment]
Have you deleted the alpha crd as its an upgrade cluster? Please check upgrade doc for that I mentioned above

**Comment by Madhu-1** [comment]
> I thought (reading values.yaml) that Rook should run snapshotter by itself, am I wrong?
> I created CRDs but the error stays (no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1beta1")

Its kubernetes distributor responsibility to create snapshot CRD and to install snapshot controller

**Comment by Antiarchitect** [comment]
Closing for now. Later I will have time to fight this

**Comment by Antiarchitect** [comment]
Stuck installing snapshotter CRDs:
Applying https://github.com/kubernetes-csi/external-snapshotter/tree/master/config/crd without modification:
```
[ERROR] templates/crds/snapshot.storage.k8s.io_volumesnapshotclasses.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiexte
nsions.k8s.io/v1 CustomResourceDefinition"
[ERROR] templates/crds/snapshot.storage.k8s.io_volumesnapshotcontents.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiext
ensions.k8s.io/v1 CustomResourceDefinition"
[ERROR] templates/crds/snapshot.storage.k8s.io_volumesnapshots.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiextensions
.k8s.io/v1 CustomResourceDefinition"
```
Changing `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`:
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiexte
nsions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-
apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver
.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.ap
iextensions.v1.CustomResourceDefinitionSpec]
helm.go:94: [debug] error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiextensi
ons-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-api
server.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pk
g.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiex
tensions.v1.CustomResourceDefinitionSpec]
helm.sh/helm/v3/pkg/kube.scrubValidationError
```

**Comment by Madhu-1** [comment]
> Stuck installing snapshotter CRDs:
> Applying https://github.com/kubernetes-csi/external-snapshotter/tree/master/config/crd (seems like last modification was at Feb 27) without modification:
> 
> ```
> [ERROR] templates/crds/snapshot.storage.k8s.io_volumesnapshotclasses.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiexte
> nsions.k8s.io/v1 CustomResourceDefinition"
> [ERROR] templates/crds/snapshot.storage.k8s.io_volumesnapshotcontents.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiext
> ensions.k8s.io/v1 CustomResourceDefinition"
> [ERROR] templates/crds/snapshot.storage.k8s.io_volumesnapshots.yaml: the kind "apiextensions.k8s.io/v1beta1 CustomResourceDefinition" is deprecated in favor of "apiextensions
> .k8s.io/v1 CustomResourceDefinition"
> ```
> 
> Changing `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`:
> 
> ```
> Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiexte
> nsions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-
> apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver
> .pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.ap
> iextensions.v1.CustomResourceDefinitionSpec]
> helm.go:94: [debug] error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiextensi
> ons-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-api
> server.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pk
> g.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiex
> tensions.v1.CustomResourceDefinitionSpec]
> helm.sh/helm/v3/pkg/kube.scrubValidationError
> ```

you need to open an issue in https://github.com/kubernetes-csi/external-snapshotter/issues

**Comment by Antiarchitect** [comment]
https://github.com/kubernetes-csi/external-snapshotter/issues/364

**Comment by Antiarchitect** [comment]
Closing. I've managed via upgrading to v1 CRDs for snapshot-controller as they appear.

**Comment by dimm0** [comment]
I followed the guide for installing the new cluster, and hit this error

**Comment by galexrt** [comment]
@dimm0 In this case I think it would be better to create a new issue so we get all your clusters information (e.g., K8S and Rook version) to be able to look into the issue. Thanks!

**Comment by dimm0** [comment]
I think it works in general, just the sidecar complains.. So I guess it's fine.

**Comment by prbakhsh** [comment]
I had Same Error. My issue solved just by install https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd 
Note: kustomization.yaml doesn't need install.
