### ISSUE TITLE
[Document] Refresh document about container linux.

### ISSUE THREAD

**Issue by OrwillT** [rook/rook#6071]
Since Container Linux reach it's end of life in May, CoreOS move itself to Fedora CoreOS and Container Linux Update Operator won't work anymore.

As member from FCOS said, the capabilities of [Container Linux Update Operator (CLUO)](https://github.com/coreos/container-linux-update-operator) have been embedded into the [Machine Config Operator (MCO)](https://github.com/openshift/machine-config-operator), so may be we could update the document under ceph_tools/container_linux to Fedora CoreOS.

**Comment by travisn** [comment]
Looks like [that topic](https://rook.github.io/docs/rook/v1.4/container-linux.html) hasn't been updated since Rook v0.8, so I'm sure it's in need of an update!

**Comment by travisn** [comment]
This doc doesn't really apply anymore. The solution to working well with updating K8s nodes is to use the pod disruption budgets, which are managed by Rook. Now we just need to enable the [PDB settings](https://github.com/rook/rook/blob/release-1.5/cluster/examples/kubernetes/ceph/cluster.yaml#L211-L215) by default.
