### ISSUE TITLE
Cassandra Tests are unstable

### ISSUE THREAD

**Issue by galexrt** [rook/rook#6085]
Cassandra integration tests are unstable (mostly observed on `aws_1.15.x`, but also on others).

* https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-6081/1/pipeline/
* https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-6081/3/pipeline/
* https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-6082/2/pipeline/
* https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-6082/3/pipeline/

**Comment by travisn** [comment]
Per discussion, these are actually other tests failing. The Cassandra tests just happen to be last after which the overall FAIL message is printed. Shall we close this issue?
