### ISSUE TITLE
s3cmd to be pre-installed on rook toolbox container

### ISSUE THREAD

**Issue by ksingh7** [rook/rook#6091]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
- s3cmd tool to be pre-installed on rook-toolbox container

**What is use case behind this feature:**
In order to test Ceph S3 object service, we required s3cmd tool. It will be very convenient if the rook toolbox container has s3cmd pre-installed.

**Environment**:

**Comment by galexrt** [comment]
Closing as duplicate of #4968.
