### ISSUE TITLE
Allow to auto grow OSDs on PVCs

### ISSUE THREAD

**Issue by paalkr** [rook/rook#6101]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
When an OSDs starts to fill up, the controller could auto provision a PVC resize by increasing the CephCluster storageClassDeviceSets size. How much to auto grow the PVCs could be controlled by a new config, allowing for 0% (disable) or bigger growth. It should be possible to specify a threshold for when to grow a PVC.

**What is use case behind this feature:**
Automatically increase the storage cluster capacity when the free space cross a configurable threshold.

**Environment**:

Cloud Providers allowing to grow block devices, like AWS EBS.

**Comment by travisn** [comment]
Storage that grows automatically, an interesting feature for sure. Here are some impressions at first glance.
1. I would see the auto-grow policy be for each individual storageClassDeviceSet. If one device set is defined, this is simple. If multiple device sets are found, this could lead to unexpected behaviors (or at least unbalanced clusters) if the device sets have different growth policies. 
1. OSDs don't fill up perfectly evenly. Should the growth be triggered based on the most full OSD in the device set, or overall cluster usage? I'm leaning towards overall cluster usage so that you'd get consistent growth across multiple device sets as raised in the first question.

**Comment by paalkr** [comment]
Thanks for answering @travisn 

I did think of the same cenarious, and I'm not quite sure what would be the best solution. In our case we do run with even sized storageClassDeviceSets and we also run quite aggressive settings for the balancer module. So our OSDs are usually filling up at that the same pace. But there are for sure other use cases out there.

Blow I have made a pseudo config to illustrate my thinking, and in this case grow and evaluate the need for growth separately pr OSD. The `minFreeSize `could be applied at the cluster level, and the some logic need to decide which (or all) storageClassDeviceSet to grow, and how much.
```
    storageClassDeviceSets:
    - name: zone-a-raw
      count: 1
      portable: true
      tuneDeviceClass: true              
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 100Gi
              maxSize: 16Ti | (100Gi, will disable auto growth as the requested and max size are equal. This should be the default if mazSize is not provided)
              growRate: 10% | 100Gi (percent growth or increase storage in fixed increments)
              minFreeSize: 20% | 50Gi (minimum free space in percent or fixed number)
          storageClassName: ebs-gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
    - name: zone-b-raw
    ...

```

**Comment by travisn** [comment]
Sounds good. I'm still not sure on the question of global cluster policy for growth vs the settings in device sets, but let's assume like you have it for now. We would just need to change the location of the settings slightly since internally we're using a K8s type for the volumeClaimTemplates so we can't add fields there.

```yaml
    storageClassDeviceSets:
    - name: zone-a-raw
      count: 1
      portable: true
      tuneDeviceClass: true              
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 100Gi
          storageClassName: ebs-gp2
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
      growthPolicy:
          maxSize: 16Ti | (100Gi, will disable auto growth as the requested and max size are equal. This should be the default if mazSize is not provided)
          growRate: 10% | 100Gi (percent growth or increase storage in fixed increments)
          minFreeSize: 20% | 50Gi (minimum free space in percent or fixed number)
    - name: zone-b-raw
    ...
```

**Comment by satoru-takeuchi** [comment]
Does Ceph allow the expansion of OSD devices? I've seen the following discussion.

http://lists.ceph.com/pipermail/ceph-users-ceph.com/2018-May/026495.html

```
> We are wondering if there is any way to expand OSD’s capacity. We are 
> studying about this and conducted an experiment. However, in the 
> result, the size of expanded capacity is counted on the USED part 
> rather than the AVAIL one.
...
you do not do this in ceph

you would most likely not partition the osd drive, you use the whole 
drive.  so you would never get into the position to need to increase.
you add space by adding osd's and adding nodes, so increasing osd size 
is not logical

if you must for some oddball reason...   you can remove (drain or 
destroy)  - repartition - add the osd and let ceph backfill the drive.
or you can just make a new osd with the remaining disk space.
```

**Comment by travisn** [comment]
@satoru-takeuchi Expanding OSDs is actually possible now, that's an old thread. For storageClassDeviceSets, the expansion was enabled by #5613.

**Comment by satoru-takeuchi** [comment]
@travisn Oops, sorry. I forgot the existence of `ceph-bluestore-tool bluefs-bdev-expand` although I looked into this command when reviewing #5613 .

**Comment by leseb** [comment]
Just a side note, expansion is not likely to work on encrypted devices...

**Comment by paalkr** [comment]
If you have turned on the volume encryption at the EBS Storage Class level it will work. But I guess you are referring to encryption managed by ceph?

**Comment by leseb** [comment]
> If you have turned on the volume encryption at the EBS Storage Class level it will work. But I guess you are referring to encryption managed by ceph?

Right, but I'm fixing it as we speak!

**Comment by paalkr** [comment]
What would it require to att the suggested features?

**Comment by travisn** [comment]
With #6126 the OSDs should at least all be expandable, but the auto-expansion is certainly still interesting. 
@satoru-takeuchi Is this a feature you'd be interested in implementing?

**Comment by satoru-takeuchi** [comment]
@travisn I'm not so interested in this feature since my cluster is on top of bare-metal servers. We'll increase the count of OSDs if we want more free space.

Just FYI, if I want this kind of feature, I'll implement it as an external tool.

1. Write a configuration file as 'growthPolicy'
2. Check the free space of OSD, for example, by 'ceph df'
3. Expand the corresponding PVC.

My team's PVC-autoresizer tool is implemented in very similar way.

https://github.com/topolvm/pvc-autoresizer

Although it can't be used for Rook/Ceph directly, it would be a hint to accomplish what @paalkr want to do.

**Comment by parth-gr** [comment]
> Storage that grows automatically, an interesting feature for sure. Here are some impressions at first glance.
> 
> 1. I would see the auto-grow policy be for each individual storageClassDeviceSet. If one device set is defined, this is simple. If multiple device sets are found, this could lead to unexpected behaviors (or at least unbalanced clusters) if the device sets have different growth policies.
> 2. OSDs don't fill up perfectly evenly. Should the growth be triggered based on the most full OSD in the device set, or overall cluster usage? I'm leaning towards overall cluster usage so that you'd get consistent growth across multiple device sets as raised in the first question.

For keeping the cluster balanced we should have equal growth rates for different `storageClassDeviceSet`.
 So we can have the following configuration present to store data in a balanced way so as to have equal growth rates for different `storageClassDeviceSet`.

1. [Automatic Balancing](https://docs.ceph.com/en/latest/rados/operations/balancer/#automatic-balancing) and [Automatic Scaling](https://docs.ceph.com/en/latest/rados/operations/placement-groups/#automated-scaling) should be enabled. 

2. [Weight Sets](https://docs.ceph.com/en/latest/rados/operations/crush-map/#weights-sets) should be enabled. `Weight sets allow the cluster to perform numerical optimization based on the specifics of your cluster (hierarchy, pools, etc.) to achieve a balanced distribution.`

And for adding this functionality we can check for the following checks/parameters:
1. We can set the utilization thresholds  [OSD_OUT_OF_ORDER_FULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-out-of-order-full) . 
[OSD_FULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-full), [OSD_BACKFILLFULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-backfillfull), [OSD_NEARFULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-nearfull) should tell the status of storage capacity available.

2. While increasing the storage size spec of `storageClassDeviceSet` we increase OSDs storage size, but we have to also need to increase the size of POOL Size, PGs present, Cache Pool size and which can be checked by [POOL_FULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#pool-full),[PG_recovery](https://docs.ceph.com/en/latest/rados/operations/health-checks/#pg-recovery-full),[TOO_FEW_PGS](https://docs.ceph.com/en/latest/rados/operations/health-checks/#too-few-pgs),[CACHE_POOL_NEAR_FULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#cache-pool-near-full).

We can create new property storage.Growth_Rate, by which we can set the % growth of storage in the cluster.
If we reach the storage thresholds then we can grow the size of storage by the %Growth_Rate set.

**Comment by travisn** [comment]
> For keeping the cluster balanced we should have equal growth rates for different `storageClassDeviceSet`.
> So we can have the following configuration present to store data in a balanced way so as to have equal growth rates for different `storageClassDeviceSet`.
> 
> 1. [Automatic Balancing](https://docs.ceph.com/en/latest/rados/operations/balancer/#automatic-balancing) and [Automatic Scaling](https://docs.ceph.com/en/latest/rados/operations/placement-groups/#automated-scaling) should be enabled.
> 2. [Weight Sets](https://docs.ceph.com/en/latest/rados/operations/crush-map/#weights-sets) should be enabled. `Weight sets allow the cluster to perform numerical optimization based on the specifics of your cluster (hierarchy, pools, etc.) to achieve a balanced distribution.`

The autobalancer and autoscaler modules are already enabled by default in Rook, so I think we're already ok from the Ceph perspective. I'm not sure we can optimize for weight sets. The default OSD weight is just based on the size of the OSD. We just need to confirm that weight grows when the OSD grows, or if we need to update it. 

> And for adding this functionality we can check for the following checks/parameters:
> 
> 1. We can set the utilization thresholds  [OSD_OUT_OF_ORDER_FULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-out-of-order-full) .
>    [OSD_FULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-full), [OSD_BACKFILLFULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-backfillfull), [OSD_NEARFULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-nearfull) should tell the status of storage capacity available.

If those limits are reached we would expect a Ceph health warning or error to be raised. It seems natural to go ahead and use the OSD_NEARFULL health warning as the detection to know when to trigger the growth of all the storageClassDeviceSets that have a growth policy. 

> 2. While increasing the storage size spec of `storageClassDeviceSet` we increase OSDs storage size, but we have to also need to increase the size of POOL Size, PGs present, Cache Pool size and which can be checked by [POOL_FULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#pool-full),[PG_recovery](https://docs.ceph.com/en/latest/rados/operations/health-checks/#pg-recovery-full),[TOO_FEW_PGS](https://docs.ceph.com/en/latest/rados/operations/health-checks/#too-few-pgs),[CACHE_POOL_NEAR_FULL](https://docs.ceph.com/en/latest/rados/operations/health-checks/#cache-pool-near-full).

I would expect the PG autoscaler to already take care of this in Ceph, hopefully we don't need anything additional in rook.

> We can create new property storage.Growth_Rate, by which we can set the % growth of storage in the cluster.
> If we reach the storage thresholds state then we can grow the size of storage by the %Growth_Rate set.

I'm thinking we need the growth rate for each storageClassDeviceSet, even if it seems counterintuitive. Someone might want to grow ssds at a different rate than hdds, or have a different max size.

**Comment by paalkr** [comment]
Auto resize of the pools should be already handled I believe. If anyone edit the PVC spec of a `storageClassDeviceSet` the underlying EBS volume is increased, the PVC is increased, the OSD is increased and the pool is increased. So mostly everything related to actually grow the storage should already work out of the box.

To the algorithm / threshold to decide when to increase the PVC spec part of a `storageClassDeviceSet` is whats missing, as far as I can tell.

**Comment by parth-gr** [comment]
For increasing the OSDs size by this [feature ](https://github.com/rook/rook/pull/5613), we should increase the PVC template and also need to restart the OSD?

Do we need to also update the [memory utilization](https://github.com/rook/rook/blob/master/design/ceph/storage-class-device-set.md#example-1-aws-cross-az)(resources->request->memory) as it depends on [Storage](https://github.com/rook/rook/blob/master/design/ceph/storage-class-device-set.md#example-3-different-resource-needs)?

Can we use [Prometheus monitoring](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml#L117) for checking OSD_Health or maybe [mon](https://github.com/rook/rook/blob/04a226ce5235f2255b7f6ba0602d51d44270095a/pkg/operator/ceph/cluster/monitoring.go#L111)?

>I'm thinking we need the growth rate for each storageClassDeviceSet, even if it seems counterintuitive. Someone might want to grow ssds at a different rate than hdds, or have a different max size.

As the  [VolumeClaimTemplate](https://github.com/rook/rook/blob/169b225be5a7fd0230ba1ac5a54422b03c946a24/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml#L118) spec of [StorageClassDeviceSet](https://github.com/rook/rook/blob/master/design/ceph/storage-class-device-set.md#storageclassdeviceset-struct) is a list of different devices (attached to a single OSD), so we need to also increase the size of all the devices linked to a single StorageClassDeviceSet, if devices used for `data storage`?

**Comment by travisn** [comment]
> For increasing the OSDs size by this [feature ](https://github.com/rook/rook/pull/5613), we should increase the PVC template and also need to restart the OSD?

The flow already implemented is basically:
- The admin updates the CephCluster CR with the new expected OSD size on the volumeClaimTemplate
- The operator updates the size of the PVC for the OSD
- The operator updates a size var on the OSD pod spec, which will cause the OSD to be restarted
- The OSD will apply the new volume size at pod start

The difference now is that the desired size of the OSD PVC is not directly in the CephCluster spec anymore. Now the desired size may be somewhere between the volumeClaimTemplate size and the max possible size. The operator will need to store the current desired size somewhere. I'm thinking the current expected size for a device set should be stored in the `status` section of the CR. If the status is empty, we just use the default value in the CephCluster spec. 

> Do we need to also update the [memory utilization](https://github.com/rook/rook/blob/master/design/ceph/storage-class-device-set.md#example-1-aws-cross-az)(resources->request->memory) as it depends on [Storage](https://github.com/rook/rook/blob/master/design/ceph/storage-class-device-set.md#example-3-different-resource-needs)?

For now, let's just recommend they set the limits as if they are the max size. 

> Can we use [Prometheus monitoring](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml#L117) for checking OSD-Usage or maybe [mon](https://github.com/rook/rook/blob/04a226ce5235f2255b7f6ba0602d51d44270095a/pkg/operator/ceph/cluster/monitoring.go#L111)?

Do we need to check OSD usage? I was thinking we were just looking for the "nearfull" health warning.

> > I'm thinking we need the growth rate for each storageClassDeviceSet, even if it seems counterintuitive. Someone might want to grow ssds at a different rate than hdds, or have a different max size.
> 
> As the [VolumeClaimTemplate](https://github.com/rook/rook/blob/169b225be5a7fd0230ba1ac5a54422b03c946a24/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml#L118) spec of [StorageClassDeviceSet](https://github.com/rook/rook/blob/master/design/ceph/storage-class-device-set.md#storageclassdeviceset-struct) is a list of different devices (attached to a single OSD), so we need to also increase the size of all the devices linked to a single StorageClassDeviceSet, if devices used for `data storage`?

Only one of the volumeClaimTemplates is for "data". The metadata and wal volumes would not be increased.

**Comment by parth-gr** [comment]
Hey @paalkr, We were discussing on feature for `Auto Growing the OSDs size`,  Wanted to know some scenarios when the functionality will be required/useful because Ceph performs better if we scale it Horizontally rather than Vertically, so if OSDs reached **Nearfull_Full** it's better to **add more OSDs** to it, rather than provisioning more Storage on the **same OSD**.

**Comment by travisn** [comment]
For a bit more perspective, today it is possible to update the cluster CR to add more OSDs (horizontal), or to grow the OSD sizes (vertical). Both could be valid to automate, depending on the real scenario. To keep it simple, we should just be clear about what scenarios really should be automated. The concern with growing the same OSDs is that they could get larger than will work well with Ceph. Having a max size for the auto growth can of course address that, but if OSDs are being added, the max size wouldn't even be a concern.

**Comment by travisn** [comment]
@parth-gr @paalkr How about if we move ahead with the following growth policy for the number of OSDs?
```yaml
count: 3 # the default number of OSDs in the device set
countGrowth:
  max: 15  # the max number of OSDs in the device set
  growRate: 3 # the number of OSDs to add during expansion. 
```

For now, OSD size growth can still be left as a manual update to the cephcluster CR. At a later time we may choose to implement a size growth such as:
```yaml
sizeGrowth:
  maxSize: 4Ti 
  growRate: 10% | 100Gi
```

**Comment by paalkr** [comment]
First of all, I'm absolutely no Ceph expert and I'm fully aware that I have a limited understanding of Ceph operations. @parth-gr , can you please elaborate on why scaling horizontally is preferred over scaling vertically? I understand thought, that at some point you will have to scale a Ceph cluster horizontally to increase capacity and performance.

In our scenario we have a setup where each PVC based OSD will run on dedicated nodes (the OSD CPU and Memory requests just fit one node, part of a dedicated Kubernetes instance group). So if I add more OSDs, the Kubernetes cluster autoscaler will add more nodes to accommodate the new OSDs.

When running with one OSD pr node my general understanding is that increasing the OSD size will add more storage capacity (and also some more IOPS due to larger EBS volumes), and adding more OSDs will add both storage capacity and bandwidth / throughput because we add more nodes as well.

In a case where we have say three OSDs of 2000GB each, one in each zone. The ceph cluster starts to fill up. Adding more OSDs will at the minimum add 2000GB of storage, and also add another node. Ideally you would probably like to add three OSDs to keep each zone balanced. While just increasing each OSD size with maybe 200GB (10% growth) would be enough to cover the increased storage needed, adding three new ODS with 2000GB of storage each and also adding three more nodes feels like dramatically over provisioning of the needed capacity.

Automatically scaling horizontally is probably a very good feature that will be useful for huge clusters with hundreds of OSDs. But our primarily goals is to vertically scale the storage in small increments to increase capacity when OSDs starts to fill up. And at some point when we reach iops, bandwidth and throughput limitations adding more OSDs will be required. Then we let the OSDs again auto grow vertically, until we again have to add more OSDs due to bandwidth and throughput, and so on.

**Comment by parth-gr** [comment]
> First of all, I'm absolutely no Ceph expert and I'm fully aware that I have a limited understanding of Ceph operations. @parth-gr , can you please elaborate on why scaling horizontally is preferred over scaling vertically? I understand thought, that at some point you will have to scale a Ceph cluster horizontally to increase capacity and performance.

@paalkr How Ceph store chunks of data in the storage devices? can answer why we need horizontal scaling.
As the logic it implements for storing the data makes the cluster self-healing and self-balancing.
 [Document](https://ceph.io/geen-categorie/how-data-is-stored-in-ceph-cluster/): It stores replicas of the same data onto different OSDs, So in the future, if there is a failure(ex: node down) we can still get/access the chunks of data stored.(self-healing)  

 
> In our scenario we have a setup where each PVC based OSD will run on dedicated nodes (the OSD CPU and Memory requests just fit one node, part of a dedicated Kubernetes instance group). So if I add more OSDs, the Kubernetes cluster autoscaler will add more nodes to accommodate the new OSDs.
> 
> When running with one OSD pr node my general understanding is that increasing the OSD size will add more storage capacity (and also some more IOPS due to larger EBS volumes), and adding more OSDs will add both storage capacity and bandwidth / throughput because we add more nodes as well.
> 
> In a case where we have say three OSDs of 2000GB each, one in each zone. The ceph cluster starts to fill up. Adding more OSDs will at the minimum add 2000GB of storage, and also add another node. Ideally you would probably like to add three OSDs to keep each zone balanced. While just increasing each OSD size with maybe 200GB (10% growth) would be enough to cover the increased storage needed, adding three new ODS with 2000GB of storage each and also adding three more nodes feels like dramatically over provisioning of the needed capacity.
> 
> Automatically scaling horizontally is probably a very good feature that will be useful for huge clusters with hundreds of OSDs. But our primarily goals is to vertically scale the storage in small increments to increase capacity when OSDs starts to fill up. And at some point when we reach iops, bandwidth and throughput limitations adding more OSDs will be required. Then we let the OSDs again auto grow vertically, until we again have to add more OSDs due to bandwidth and throughput, and so on.

Thanks for providing your scenario, Will get back to this after discussing more on it with the team what design we can have for the storage automation.

> @parth-gr @paalkr How about if we move ahead with the following growth policy for the number of OSDs?
> 
> ```yaml
> count: 3 # the default number of OSDs in the device set
> countGrowth:
>   max: 15  # the max number of OSDs in the device set
>   growRate: 3 # the number of OSDs to add during expansion. 
> ```
> 
> For now, OSD size growth can still be left as a manual update to the cephcluster CR. At a later time we may choose to implement a size growth such as:
> 
> ```yaml
> sizeGrowth:
>   maxSize: 4Ti 
>   growRate: 10% | 100Gi
> ```

Yes @travisn, a great idea we can have this combination for automating.
Okay, let's keep the OSD size growth manual for now.

**Comment by BlaineEXE** [comment]
IMO, it would be better to hook Prometheus into adjusting the CephCluster CRD based on events than to immediately work on baking this into Rook. We already have so many features we need to stay on top of, and it's rare that we have something that so nicely allows for a completely external implementation. 

I think it is still a valuable addition to the Rook codebase to have an example of hooking into Ceph metrics with Prometheus to change Rook's behavior. This would empower users to extend the example to their needs rather than relying on Rook devs to implement every similar feature internally. I think it would also be a good idea to also have something like this in an integration test to make sure our example doesn't get stale. 

I think we can treat this as a first-class citizen feature of Rook without needing to code the business logic where we don't need to.

**Comment by travisn** [comment]
It's an interesting thought to allow the desired state be modified automatically in the CephCluster CR based on some metrics. The example linked is about auto-scaling pods. How would this fit together in this scenario where the cluster CR would be updated based on a Ceph health warning?

Today we assume all the desired state lies with the admin, who carefully creates the CRs. Handing this responsibility over to some automation based on something external to Rook makes me nervous. :)

**Comment by jeanchlopez** [comment]
I do think that we should focus on expanding the cluster through an uodate of the count. If cloud based with dynamic provisioning it's an easy thing, if using LSO underneath it would just require pre-provisioning some LSO PVs and then expanding the cluster through the update of the count. All of this can easily be achieved by monitoring the alerts generated in K8S or OpenShift. I have put together a quick and dirty script that autoexpands PVCs based on alerts for PVCs in OCP that could easily be replicated for cluster nearfull or full alerts. I have attached my quick script to this comment at https://gist.github.com/jeanchlopez/fc38710147ea738be6920d05c8c756da

**Comment by travisn** [comment]
@jeanchlopez Nice to see an example of triggering a change to the CephCluster CR based on Ceph health warning, raised by a prometheus alert. This will be a good pattern that allows users to dynamically update the cluster CR based on alerts, without requiring a feature request and code change from Rook.

Still, if there is a specific feature like this one that upstream or downstream users are interested in, I see that it would be preferred to implement it in the Rook operator for better reliability and testability.

**Comment by parth-gr** [comment]
> I do think that we should focus on expanding the cluster through an uodate of the count. If cloud based with dynamic provisioning it's an easy thing, if using LSO underneath it would just require pre-provisioning some LSO PVs and then expanding the cluster through the update of the count. All of this can easily be achieved by monitoring the alerts generated in K8S or OpenShift. I have put together a quick and dirty script that autoexpands PVCs based on alerts for PVCs in OCP that could easily be replicated for cluster nearfull or full alerts. I have attached my quick script to this comment at https://gist.github.com/jeanchlopez/fc38710147ea738be6920d05c8c756da

Hey @jeanchlopez thanks for providing the example script that is using Prometheus metrics, 
I was not able to test the alerts for PVCs(`PersistentVolumeUsageCritical` ```PersistentVolumeUsageNearFull```) in OCP through the [script](https://gist.github.com/jeanchlopez/fc38710147ea738be6920d05c8c756da), 
And I was checking the [rules](https://github.com/openshift/cluster-monitoring-operator/blob/release-4.7/assets/prometheus-k8s/rules.yaml) present in Prometheus-K8s, but not able to find any alertname label for  `PersistentVolumeUsageNearFull`, can you please elaborate on how to use this script.

I guess it's not default configured and we should have to create a manual alert on OCP for using it, like this? https://github.com/rook/rook/blob/7dbaf0cce1d1c2b357b97f7f5865e596c3186f06/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml#L214-L226

**Comment by jeanchlopez** [comment]
NearFull in my OCS environment is defined as 
(kubelet_volume_stats_used_bytes * on(namespace, persistentvolumeclaim) group_left(storageclass, provisioner) (kube_persistentvolumeclaim_info * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~"(.*rbd.csi.ceph.com)|(.*cephfs.csi.ceph.com)"})) / (kubelet_volume_stats_capacity_bytes * on(namespace, persistentvolumeclaim) group_left(storageclass, provisioner) (kube_persistentvolumeclaim_info * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~"(.*rbd.csi.ceph.com)|(.*cephfs.csi.ceph.com)"})) > 0.75

Full as
(kubelet_volume_stats_used_bytes * on(namespace, persistentvolumeclaim) group_left(storageclass, provisioner) (kube_persistentvolumeclaim_info * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~"(.*rbd.csi.ceph.com)|(.*cephfs.csi.ceph.com)"})) / (kubelet_volume_stats_capacity_bytes * on(namespace, persistentvolumeclaim) group_left(storageclass, provisioner) (kube_persistentvolumeclaim_info * on(storageclass) group_left(provisioner) kube_storageclass_info{provisioner=~"(.*rbd.csi.ceph.com)|(.*cephfs.csi.ceph.com)"})) > 0.85

**Comment by parth-gr** [comment]
@jeanchlopez I have added the support for [expanding the cluster ](https://github.com/rook/rook/pull/8078) 
But I still struggle to test this [script](https://gist.github.com/jeanchlopez/fc38710147ea738be6920d05c8c756da), I want to check can the percentage value mentioned above  `> 0.75` can be lowered somehow so the PVC near-full condition can hit earlier?
I am testing it on Rook-Ceph cluster-on-PVC deployed on the OCP cluster and don't find any way to update the OCP metrics.

**Comment by jeanchlopez** [comment]
You will have to do an oc edit of your existing alerts and add the PVC alerts to the existing set of rules. e.g. oc edit prometheusrules prometheus-ceph-v14-rules -n {your-name-space}

**Comment by parth-gr** [comment]
> You will have to do an oc edit of your existing alerts and add the PVC alerts to the existing set of rules. e.g. oc edit prometheusrules prometheus-ceph-v14-rules -n {your-name-space}

Hey @jeanchlopez, thanks.
I investigated and got I was missing to [Enabling monitoring for user-defined projects ](https://docs.openshift.com/container-platform/4.6/monitoring/enabling-monitoring-for-user-defined-projects.html#enabling-monitoring-for-user-defined-projects_enabling-monitoring-for-user-defined-projects), which will be required to get the rook metrics alerts, for the PrometheusRule created in rook.

And secondly, I check that `PersistentVolumeUsageNearFull `
( expr: |          
         (kubelet_volume_stats_used_bytes * on (namespace,persistentvolumeclaim) group_left(storageclass, provisioner) (kube_persistentvolumeclaim_info * on (storageclass)  group_left(provisioner) kube_storageclass_info {provisioner=~"(.*rbd.csi.ceph.com)|(.*cephfs.csi.ceph.com)"})) / (kubelet_volume_stats_capacity_bytes * on (namespace,persistentvolumeclaim) group_left(storageclass, provisioner) (kube_persistentvolumeclaim_info * on (storageclass)  group_left(provisioner) kube_storageclass_info {provisioner=~"(.*rbd.csi.ceph.com)|(.*cephfs.csi.ceph.com)"})) &gt; 0.75 <br class="Apple-interchange-newline"> )
 did'nt provide any data points even I checked for `>=0`, need to check this condition.
         
 But I was successful for getting data points for   ` CephOSDNearFull `
 ```expr: |        (ceph_osd_metadata * on (ceph_daemon) group_right(device_class) (ceph_osd_stat_bytes_used / ceph_osd_stat_bytes)) &gt;= 0.75 ``` and it provide **enough labels information** to continue work on this PR.

**Comment by travisn** [comment]
@paalkr Have you tried the [auto expansion of OSDs](https://rook.github.io/docs/rook/v1.7/ceph-advanced-configuration.html#auto-expansion-of-osds) yet? I'm wondering how well it's working based on the prometheus events rather than being controlled by the operator.
