### ISSUE TITLE
Store encrypted OSD keys in Vault

### ISSUE THREAD

**Issue by mmgaggle** [rook/rook#6105]
**Feature Request**

Now that we have encrypted OSDs, it would be great if the encryption keys for the OSDs could optionally be stored in an external key / secrets engine like Vault.

**What should the feature do:**

Store OSD keys in Vault, in lieu of the Ceph monitor K/V store.

**What is use case behind this feature:**

Vault uses a variety of cryptographic techniques eg. Shamir's secret sharing to ensure sensitive information cannot be retrieved from any given disk. Ceph CSI already has integration with Vault for managing keys corresponding to encrypted RBD persistent volumes, and Ceph object has integration with Vault for SSE-KMS. A Vault integration for OSD keys would help round out the key management picture.

**Comment by leseb** [comment]
The encryption key is stored as a Kubernetes Secret, not in the Ceph Mon K/V store. We can certainly look into this, but I'd be nice to have a more generic common KMS approach which could have Vault as backend and potentially others.

**Comment by travisn** [comment]
Since the keys are stored in K8s secrets, I thought it was already possible to store them in Vault without writing any specific Rook code to handle that.

**Comment by travisn** [comment]
Vault integration is planned for v1.5, scratch my previous comment.
