### ISSUE TITLE
Apply latest changes in ceph k8s example manifest object.yaml to other object-prefixed example manifests

### ISSUE THREAD

**Issue by ron1** [rook/rook#6108]
**Is this a bug report or feature request?**
* Feature Request
Apply latest changes in ceph k8s example manifest object.yaml to other example object-prefixed manifests including object-ec.yaml, object-openshift.yaml, etc. These other manifests are missing latest changes including healthCheck property, pool parameters, and relevant comments.

**Comment by travisn** [comment]
The goal isn't necessarily to keep all the settings in sync in the different examples, but I can see that object.yaml, object-ec.yaml, and object-openshift.yaml would be best to keep mostly in sync, even while object-test.yaml stays simple without all the new settings.
