### ISSUE TITLE
failed to create rbd image

### ISSUE THREAD

**Issue by matejc** [rook/rook#611]
I have a simple busybox pod named teststorage and pvc named teststorage-claim, but it fails with:
```
$ kubectl describe -n default pvc/teststorage-claim
Name:		teststorage-claim
Namespace:	default
StorageClass:	rook-block
Status:		Pending
Volume:		
Labels:		app=teststorage
Annotations:	volume.beta.kubernetes.io/storage-class=rook-block
		volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  17s		17s		1	persistentvolume-controller			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "rook-block": failed to create rbd image: exit status 2, command output: 2017-04-25 15:14:26.250481 7fdc90efc3c0 -1 did not load config file, using default settings.
rbd: image format 1 is deprecated
2017-04-25 15:14:26.267600 7fdc90efc3c0 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
rbd: error opening pool replicapool: (2) No such file or directory

  5s	5s	1	persistentvolume-controller		Warning	ProvisioningFailed	Failed to provision volume with StorageClass "rook-block": failed to create rbd image: exit status 2, command output: 2017-04-25 15:14:38.885139 7feb2fc4b3c0 -1 did not load config file, using default settings.
rbd: image format 1 is deprecated
2017-04-25 15:14:38.895403 7feb2fc4b3c0 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin: (2) No such file or directory
rbd: error opening pool replicapool: (2) No such file or directory
```

I gather that ceph needs to be installed on nodes or at least on master node for this to work. I have compiled ceph 11.2.0 from source, installed it on all nodes, and add it to PATH variable of kubernetes systemd services. Since there is a `rbd: image format 1 is deprecated` message, there is a possibility of ceph version missmatch.

**Comment by matejc** [comment]
let me add some more context...
I am using Rook 0.3.1
teststorage deployment:
```
          "apiVersion": "extensions/v1beta1",
          "kind": "Deployment",
          "metadata": {
            "labels": {
              "app": "teststorage"
            },
            "name": "teststorage",
            "namespace": "default"
          },
          "spec": {
            "replicas": 1,
            "template": {
              "metadata": {
                "annotations": {},
                "labels": {
                  "name": "teststorage"
                }
              },
              "spec": {
                "containers": [
                  {
                    "command": [
                      "sh",
                      "-c",
                      "while true; do sleep 1; ls -la /dir; done"
                    ],
                    "env": [],
                    "image": "busybox:latest",
                    "imagePullPolicy": "Always",
                    "name": "teststorage",
                    "ports": [],
                    "resources": {
                      "limits": {},
                      "requests": {}
                    },
                    "securityContext": {
                      "capabilities": {
                        "add": []
                      },
                      "privileged": false
                    },
                    "stdin": false,
                    "tty": false,
                    "volumeMounts": [
                      {
                        "mountPath": "/dir",
                        "name": "storage",
                        "subPath": null
                      }
                    ]
                  }
                ],
                "imagePullSecrets": [],
                "nodeSelector": {},
                "restartPolicy": "Always",
                "volumes": [
                  {
                    "name": "storage",
                    "persistentVolumeClaim": {
                      "claimName": "teststorage-claim"
                    }
                  }
                ]
              }
            }
          }
        }
```
and pvc:
```
        "teststorage-claim": {
          "apiVersion": "v1",
          "kind": "PersistentVolumeClaim",
          "metadata": {
            "annotations": {
              "volume.beta.kubernetes.io/storage-class": "rook-block",
            },
            "labels": {
              "app": "teststorage"
            },
            "name": "teststorage-claim",
            "namespace": "default"
          },
          "spec": {
            "accessModes": [
              "ReadWriteOnce"
            ],
            "resources": {
              "requests": {
                "storage": "100M"
              }
            }
          }
        }
```

**Comment by bzub** [comment]
Can you post your storage class definition?

`kubectl get storageclass rook-block -o yaml`

The main issue is that the volume provisioner isn't getting any configuration. I don't know why that would be quite yet but the storage class definition might help when I look later. Thanks.

**Comment by jbw976** [comment]
@bzub i have seen the RBD volume plug-in log out warnings about not finding a config file and having to use default settings even though the correct settings (mon IPs, secret key, etc.) are being passed directly to it on the command line.

The message that pops out at me is:
```
rbd: error opening pool replicapool: (2) No such file or directory
```
Did that ceph storage pool exist and get created?  Running the rook-client pod from https://github.com/rook/rook/blob/master/Documentation/kubernetes.md#rook-client and then running `rook pool ls` could help answer that.

**Comment by matejc** [comment]
@bzub 
```
$ kubectl get storageclass rook-block -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    x-truder.net/dependencies: rookpools/replicapool
  creationTimestamp: 2017-04-22T16:01:37Z
  name: rook-block
  resourceVersion: "10652472"
  selfLink: /apis/storage.k8s.io/v1/storageclassesrook-block
  uid: f7295cdc-2774-11e7-b5af-b630ab73f2fa
parameters:
  adminId: admin
  adminSecretName: rook-admin
  adminSecretNamespace: rook
  monitors: 10.2.62.73:6790,10.2.62.74:6790,10.2.62.75:6790
  pool: replicapool
  userId: rook-rbd-user
  userSecretName: rook-rbd-user
provisioner: kubernetes.io/rbd
```

@jbw976 
```
$ kubectl exec -ti -n rook rook-client-2635445789-9wnrs -- rook pool ls
NAME      NUMBER    TYPE         SIZE      DATA      CODING    ALGORITHM
rbd       0         replicated   1
```

**Comment by matejc** [comment]
do not mind `x-truder.net/dependencies: rookpools/replicapool`, its just nix-kubernetes' dependency management helper annotation, just a quick intro: nix-kubernetes just takes nix modules (in Nix language described kubernetes resources) and makes json out of it and then pushes with kubectl create/apply command, all together or one by one, or by groups when some resource depends on other, there just wanted to clearify what that strange annotation is doing there

**Comment by jbw976** [comment]
So it looks like the main problem is that the `replicapool` storage pool isn't being created.  That's expected using v0.3.1 since in that release the pool was not created automatically for you.

Try creating the pool manually and then see how it goes?  There may be other issues with your storage-class/deployment, but I'm not sure just by glancing.

**Comment by matejc** [comment]
ok, finally made it, once you wrote that replicapool isnt created, I double checked the Rookpool resource named replicapool and saw that i kind of missed the change from spec.replication.size to spec.replication.count, thats why it was not created.

After replicapool was created the pod/teststorage was in "ContainerCreating" state, then after a bit of following the error to the source - kubelet, I saw that fsck.ext2 command was not in PATH, so I added it. 
the actual event in pod was:
```
  28s		11s		6	kubelet, x.com			Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/rbd/9ef05237-2a06-11e7-b5af-b630ab73f2fa-pvc-c6bfa75e-2a05-11e7-b5af-b630ab73f2fa" (spec.Name: "pvc-c6bfa75e-2a05-11e7-b5af-b630ab73f2fa") pod "9ef05237-2a06-11e7-b5af-b630ab73f2fa" (UID: "9ef05237-2a06-11e7-b5af-b630ab73f2fa") with: rbd: failed to mount rbd volume /dev/rbd0 [] to /var/lib/kubernetes/plugins/kubernetes.io/rbd/rbd/replicapool-image-kubernetes-dynamic-pvc-c6c335e1-2a05-11e7-8beb-b630ab73f2fa, error executable file not found in $PATH
```

and also noticed that setting metadata.namespace for Rookcluster, Rookpool (and possibly the StorageClass) to `default` (the one that rook-operator was living in) actually matters, when it was set to `rook`, the operator failed to detect those Rook* resources.

**Comment by matejc** [comment]
ok, I can confirm, works well

1. exec into container and created new file in mounted storage
2. I have deleted pod/teststorage a several times until it is spawned on another node
3. the file was inside
4. success and me goes to sleep :)

**Comment by travisn** [comment]
great to hear you got it working. Unfortunately you were caught in the middle of the TPRs changing this milestone. See https://github.com/rook/rook/wiki/v0.4-TPR-Breaking-Changes for the complete list of changes. They assume you are using the latest master, however.

**Comment by matejc** [comment]
Thanks all for the help!

Is there some kind of estimation date on when the v0.4 will be released? I kind of like the automatic discovery of the monitors.

and one more thing, is there or will there be some instructions on Rook upgrade procedure from 0.3.1 to 0.4, without loosing the container data?

**Comment by travisn** [comment]
we're on our last issue for 0.4, hoping to release by end of week. For your reference, we track the issues remaining for a release in the project board: https://github.com/rook/rook/projects/5

Unfortunately upgrades are not supported while we're in alpha.

**Comment by DanKerns** [comment]
Is this issue resolved?

**Comment by travisn** [comment]
looks like this is resolved
