### ISSUE TITLE
Where is the Ceph.conf or equivalent located in Rook Ceph?

### ISSUE THREAD

**Issue by Jimmyjim123** [rook/rook#6115]
Hey, hows it going. 

I'm currently using Rook to set up ceph to work as a volume for my single node Kubernetes cluster(minikube). I need to edit the ceph.conf file to fix an error that I'm facing. Where is ceph.conf file or what is the equivalent to the ceph.conf file with rook ceph?

**Comment by travisn** [comment]
@Jimmyjim123 If you cannot resolve the issue with `ceph` commands in the toolbox, you can apply ceph.conf overrides by creating a configmap with the settings as described [here](https://rook.github.io/docs/rook/v1.4/ceph-advanced-configuration.html#custom-cephconf-settings).
