### ISSUE TITLE
OSD is marked as down, but OSD daemon is running

### ISSUE THREAD

**Issue by georgr** [rook/rook#6132]
**Is this a bug report or feature request?**
* Bug Report

* The cluster got gracefully shut down due to power outage.
* After power up, the osd daemons kept crashing due to authentication errors to the monitor.
* I reimported the osd keys as in https://github.com/rook/rook/issues/4238#issuecomment-664627282.
* The OSDs got recognized and markes as "out" and "down".
* I marked the OSDs as "in" again.

**Deviation from expected behavior:**

* The OSDs are now marked as "in" but not as "up".

**Expected behavior:**

* The OSDs should get "up" again.

**How to reproduce it (minimal and precise):**

* Shutdown all k8s nodes in your cluster for 12 hours and start them again.

**File(s) to submit**:

osd-pod-log:
```
2020-08-19 17:20:37.009 7fe1ebb26a80 -1 Falling back to public interface
2020-08-19 17:20:38.937 7fe1ebb26a80 -1 osd.0 783 log_to_monitors {default=true}
2020-08-19 17:20:38.957 7fe1de127700 -1 osd.0 783 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory
2020-08-19 17:33:41.513 7fe1d5c9f700 -1 osd.0 783 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory
```

ceph osd tree:
```
[root@rook-ceph-tools-6d67f5bb96-xv2xm /]# ceph osd tree
ID CLASS WEIGHT  TYPE NAME                 STATUS REWEIGHT PRI-AFF 
-1       1.83018 root default                                      
-2       0.45479     host rancher-worker01                         
 0   hdd 0.45479         osd.0               down  1.00000 1.00000 
-3       0.46570     host rancher-worker02                         
 2       0.46570         osd.2               down  1.00000 1.00000 
-4       0.90970     host rancher-worker03                         
 1       0.90970         osd.1               down  1.00000 1.00000 
[root@rook-ceph-tools-6d67f5bb96-xv2xm /]# 
```

ceph auth ls (XX replaces with the actual key):
```
osd.0
        key: XX==
        caps: [mgr] allow profile osd
        caps: [mon] allow profile osd
        caps: [osd] allow *
osd.1
        key: XX==
        caps: [mgr] allow profile osd
        caps: [mon] allow profile osd
        caps: [osd] allow *
osd.2
        key: XX==
        caps: [mgr] allow profile osd
        caps: [mon] allow profile osd
        caps: [osd] allow *
```

![2020-08-19 20_08_25-Ceph](https://user-images.githubusercontent.com/229366/90673273-cac28800-e257-11ea-9852-700d9d418486.png)

**Environment**:
* OS (e.g. from /etc/os-release): NAME="RancherOS" VERSION=v1.5.5
* Kernel (e.g. `uname -a`): 4.14.138-rancher
* Cloud provider or hardware configuration: on-Premise
* Rook version (use `rook version` inside of a Rook Pod): 1.3.9
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.9
* Kubernetes version (use `kubectl version`): 1.17.9
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN 2 MDSs report slow metadata IOs; 3 osds down; 3 hosts (3 osds) down; 1 root (3 osds) down; Reduced data availability: 64 pgs inactive; 3 slow ops, oldest one blocked for 1593 sec, daemons [mon.a,mon.c] have slow ops.

**Comment by leseb** [comment]
Is the mgr up?

**Comment by leseb** [comment]
Output of `ceph -s` please

**Comment by georgr** [comment]
mgr is up but raises an exception

```
debug 2020-08-20 07:44:46.901 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8380: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:44:48.901 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8381: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:44:50.901 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8382: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:44:52.901 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8383: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:44:54.901 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8384: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
10.25.80.12 - - [20/Aug/2020:07:44:55] "GET / HTTP/1.1" 200 155 "" "kube-probe/1.17"
debug 2020-08-20 07:44:56.901 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8385: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:44:58.905 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8386: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:45:00.905 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8387: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:45:02.905 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8388: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:45:04.905 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8389: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
10.25.80.12 - - [20/Aug/2020:07:45:05] "GET / HTTP/1.1" 200 155 "" "kube-probe/1.17"
debug 2020-08-20 07:45:06.905 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8390: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:45:08.905 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8391: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:45:10.905 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8392: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:45:12.905 7fce17b7a700  0 log_channel(cluster) log [DBG] : pgmap v8393: 64 pgs: 64 unknown; 0 B data, 0 B used, 0 B / 0 B avail
debug 2020-08-20 07:45:14.133 7fce05042700  1 mgr[volumes] thread [puregejob.1] encountered fatal error: (attempt# 8/10)
debug 2020-08-20 07:45:14.133 7fce05042700  1 mgr[volumes] traceback: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/volumes/fs/async_job.py", line 36, in run
    vol_job = self.async_job.get_job()
  File "/usr/share/ceph/mgr/volumes/fs/async_job.py", line 121, in get_job
    (ret, job) = self.get_next_job(volname, running_jobs)
  File "/usr/share/ceph/mgr/volumes/fs/purge_queue.py", line 56, in get_next_job
    return get_trash_entry_for_volume(self.vc, volname, running_jobs)
  File "/usr/share/ceph/mgr/volumes/fs/purge_queue.py", line 16, in get_trash_entry_for_volume
    with open_volume_lockless(volume_client, volname) as fs_handle:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 300, in open_volume_lockless
    fs_handle = vc.connection_pool.get_fs_handle(volname)
  File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 162, in get_fs_handle
    raise VolumeException(-e.args[0], e.args[1])
TypeError: bad operand type for unary -: 'str'
debug 2020-08-20 07:45:14.141 7fce08088700 -1 client.0 error registering admin socket command: (17) File exists
debug 2020-08-20 07:45:14.141 7fce08088700 -1 client.0 error registering admin socket command: (17) File exists
debug 2020-08-20 07:45:14.141 7fce08088700 -1 client.0 error registering admin socket command: (17) File exists
debug 2020-08-20 07:45:14.141 7fce08088700 -1 client.0 error registering admin socket command: (17) File exists
debug 2020-08-20 07:45:14.141 7fce08088700 -1 client.0 error registering admin socket command: (17) File exists
```

ceph -s

```
root@rook-ceph-tools-6d67f5bb96-xv2xm /]# ceph -s
  cluster:
    id:     946ae57c-d29e-42d8-9114-0322847ecf69
    health: HEALTH_WARN
            2 MDSs report slow metadata IOs
            3 osds down
            3 hosts (3 osds) down
            1 root (3 osds) down
            Reduced data availability: 64 pgs inactive
            2 slow ops, oldest one blocked for 51574 sec, daemons [mon.a,mon.c] have slow ops.
 
  services:
    mon: 3 daemons, quorum c,a,b (age 4h)
    mgr: a(active, since 4h)
    mds: rook-fs:1 {0=rook-fs-a=up:creating} 1 up:standby-replay
    osd: 3 osds: 0 up, 3 in (since 11h)
 
  data:
    pools:   2 pools, 64 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             64 unknown
 
[root@rook-ceph-tools-6d67f5bb96-xv2xm /]#
```

**Comment by leseb** [comment]
The issue is coming from the mgr, have you tried to restart it? Have you found a similar issue in https://tracker.ceph.com/?

**Comment by georgr** [comment]
I restarted the mgr, but no success. ceph tracker was also no success. Is it possible to completly resetup (kubectl delete common.yml + delete the /var/lib/rook/ dirs on the nodes) the k8s part and "remount" the data on the disks in the new cluster?

**Comment by leseb** [comment]
> I restarted the mgr, but no success. ceph tracker was also no success. Is it possible to completly resetup (kubectl delete common.yml + delete the /var/lib/rook/ dirs on the nodes) the k8s part and "remount" the data on the disks in the new cluster?

I wouldn't do that if you have sensitive data.
Are you applying resources to your mgr deployment?

**Comment by georgr** [comment]
Yes the nodes are basically idling, there is no pressure on disk, cpu or ram. Also the containers has no special configuration, the deployment is standard as in the docs. I put in another hour to find a hint what´s wrong, but the logs do not provide any error as the one I posted.

If there is a way to redeploy the k8s part an remount the data disks, I would try it. The data is not that sensitive, it runs non critical services to test out if rook+ceph would be an option for production and everything is in backup. I would like to try if it is possible to recover that way. Are there any docs to try this?

**Comment by DWSR** [comment]
Running into this as well: Custom Resource and logs from the `mgr` and `osd` pods: https://gist.github.com/DWSR/35c22f7773bb827d61bfde593f0cdc04

Debug logs from an OSD pod: https://gist.github.com/DWSR/9a61a254f74fc3ac2e36548de6979bbc

**Comment by travisn** [comment]
> Running into this as well: Custom Resource and logs from the `mgr` and `osd` pods: https://gist.github.com/DWSR/35c22f7773bb827d61bfde593f0cdc04
> 
> Debug logs from an OSD pod: https://gist.github.com/DWSR/9a61a254f74fc3ac2e36548de6979bbc

@DWSR Can you also share the mon logs after increasing the mon log level?

**Comment by DWSR** [comment]
@travisn https://gist.github.com/DWSR/86cce02894909066a96c3456605a282f

**Comment by travisn** [comment]
@neha-ojha Anything helpful in these mon or other logs for the cause of OSDs not coming back in?

**Comment by neha-ojha** [comment]
> @neha-ojha Anything helpful in these mon or other logs for the cause of OSDs not coming back in?

unfortunately, it doesn't tell us much, perhaps also having debug_ms=1 on the mons and osds, can tell us more about the communication between them.

Also, what is the procedure being used to bring osds down/up? Can we reproduce this easily?

**Comment by DWSR** [comment]
@neha-ojha My case matches the OP. The OSDs are down because the Kubernetes cluster was offline for an extended period of time (I was re-racking my home lab). When I brought the K cluster back online, the OSDs were missing auth information. I reset the auth info as outlined [in this comment](https://github.com/rook/rook/issues/4238#issuecomment-664627282), but the OSDs are still not joining the cluster.

This is the second time that I've had this happen. The first time I recreated the Ceph cluster

More detailed logs are available here: https://gist.github.com/DWSR/445dbdf319ba5def7bddfc952e69514a

**Comment by DWSR** [comment]
So I just checked my Ceph Cluster this morning and it's reporting that all the OSDs are now up and in....

```
# ceph -s
  cluster:
    id:     fc848035-a70f-4869-9a08-2f85260c7195
    health: HEALTH_WARN
            Degraded data redundancy: 1 pg undersized

  services:
    mon: 3 daemons, quorum c,a,b (age 36s)
    mgr: a(active, since 4d)
    mds: nas-cluster:1 {0=nas-cluster-b=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 7h), 3 in (since 7h); 1 remapped pgs

  data:
    pools:   3 pools, 65 pgs
    objects: 38 objects, 5.1 MiB
    usage:   123 GiB used, 5.5 TiB / 5.6 TiB avail
    pgs:     8/90 objects misplaced (8.889%)
             64 active+clean
             1  active+undersized+remapped

  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
    ```

**Comment by neha-ojha** [comment]
> So I just checked my Ceph Cluster this morning and it's reporting that all the OSDs are now up and in....
> 
> ```
> # ceph -s
>   cluster:
>     id:     fc848035-a70f-4869-9a08-2f85260c7195
>     health: HEALTH_WARN
>             Degraded data redundancy: 1 pg undersized
> 
>   services:
>     mon: 3 daemons, quorum c,a,b (age 36s)
>     mgr: a(active, since 4d)
>     mds: nas-cluster:1 {0=nas-cluster-b=up:active} 1 up:standby-replay
>     osd: 3 osds: 3 up (since 7h), 3 in (since 7h); 1 remapped pgs
> 
>   data:
>     pools:   3 pools, 65 pgs
>     objects: 38 objects, 5.1 MiB
>     usage:   123 GiB used, 5.5 TiB / 5.6 TiB avail
>     pgs:     8/90 objects misplaced (8.889%)
>              64 active+clean
>              1  active+undersized+remapped
> 
>   io:
>     client:   852 B/s rd, 1 op/s rd, 0 op/s wr
>     ```
> ```

do you know what changed?

**Comment by DWSR** [comment]
I changed nothing and have since destroyed the cluster, so no.
