### ISSUE TITLE
rook-config-override is ignored in Rook v1.2.7

### ISSUE THREAD

**Issue by shikhar7** [rook/rook#6140]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I am not able to set osd memory target using rook-config-override configmap. I have to run commands manually from toolbox pod.

**Expected behavior:**
```
[global]
 osd max object name len = 2048
 osd max object namespace len = 256
 osd memory target = 2294967296
[osd] 
 bluestore cache size ssd = 1000000000 
 bluestore cache size hdd = 768000000
```
Above data in configmap should work.

**How to reproduce it (minimal and precise):**
Deploy a fresh cluster or tweak(add or remove) some parameters in rook-config-override configmap and restart the pod in my case i restarted osd-0 and ran the command `ceph config get osd.0 osd_memory_target` to validate the change but it didn't reflected changes.

**Comment by travisn** [comment]
@shikhar7 For the osd memory target, it's expected to be set internally by rook and ceph with the [resource limits](https://rook.github.io/docs/rook/v1.4/ceph-cluster-crd.html#cluster-wide-resources-configuration-settings) in the cluster CR. 

For the settings that you're trying to load through ceph.conf overrides, try connecting to the osd pod:
- Do you see the settings in /etc/ceph/ceph.conf?
- Do you see your settings with this command? **you need to replace the osd ID**
 `unset CEPH_ARGS; ceph daemon osd.0 config show`

**Comment by LittleFox94** [comment]
Those settings are given on the command line:
``` 
osd max object name len = 2048
 osd max object namespace len = 256
```

I have a changed 1.2.7 build for that: https://github.com/LittleFox94/rook/commit/b512059012b3f14522ea2fca6473781a68adfd86, https://hub.docker.com/r/littlefox/rook-ceph

**Comment by Sid-22** [comment]
Rook Operator version: v1.9.9
Ceph version: v17.2.3

Hi @travisn , We are able to see the changes  in the file /etc/ceph/ceph.conf in all pods (osd,mon,mgr) but still in rook-toolbox pod when we run below command, output shows default value

`ceph config get osd.2 bluestore_cache_size_ssd`

![image](https://user-images.githubusercontent.com/46243481/194317985-427fc12f-3516-4889-aa3e-dc25acd6822f.png)

We verified in osd.2 pod by looking at ceph.conf file and running below command (1st line of output)

![image](https://user-images.githubusercontent.com/46243481/194318155-99bd6387-2795-4906-b671-9fd3040fcbd5.png)

**Comment by travisn** [comment]
Looks good, the `ceph daemon` is the actual value, as the toolbox does not have daemon-specific settings that are overridden by ceph.conf.
