### ISSUE TITLE
Add storageClassDeviceSet label to osd(prepare) pods

### ISSUE THREAD

**Issue by andrewsali** [rook/rook#6146]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

When creating the osd prepare / osd pods, rook should label the pods with the name of the storageClassDeviceSet as well.

**What is use case behind this feature:**

We would like to achieve a zone-redundant configuration with multiple different storageClassDeviceSets. Setting up a topology constraint based on zone name seems currently only possible when using the 'app=...' label selector. This is however the same across different storageClassDeviceSets.

We therefore end up with certain storageClassDeviceSet pods being non-balanced across the different zones. If we could set up the topology constraint to include the name of the storageClassDeviceSet, we would be able to balance each of these sets across the zones.

**Environment**:

**Comment by travisn** [comment]
@andrewsali v1.4.2 will have a fix (#6118) for the topology spread constraints that may already improve your situation. Take a look at the discussion in #5586 to see if this helps. Otherwise, it's certainly simple enough to add the labels as you've suggested.

**Comment by andrewsali** [comment]
@travisn thanks I took a look, but I am not sure how exactly that would help.

The issue is that the osd-prepare pods seem to be generated essentially at the same time for all device sets. Any topological constraints that can be applied there seem to apply to the device sets jointly (as currently we can't apply device set specific labels), which means that individual different device sets might not be balanced across zones (only 'all device sets together' will be balanced).

We would like for example to have faster devices for OSDs that back CephFS metadata (than for the OSD-s that back the actual data), but at the same time guarantee that these OSDs are separately balanced across zones as well.

The current workaround we do is to set the initial count to '0' for the second device set and wait until the first one is provisioned in a balanced fashion. Then we increase the count for the second one which will then also be balanced. However we cannot seem to do it in a one-shot deploy step.

**Comment by travisn** [comment]
@andrewsali Thanks for describing the scenario, makes sense to have the labels so you can differentiate immediately.
