### ISSUE TITLE
Ability to set 'fast' deviceClass (tuneFastDeviceClass )

### ISSUE THREAD

**Issue by andrewsali** [rook/rook#6153]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

There is a tuneSlowDeviceClass option when the cloud provider is reporting SSD but performance is more like HDD. On Azure the inverse is true - all SSDs (even premium) are reporting as rotational disk. (https://github.com/MicrosoftDocs/azure-docs/issues/13958#issuecomment-430523880)

This feature would expose a tuneFastDeviceClass option where the inverse direction could be configured (tune for an SSD even if the cloud provider is reporting rotational)

**What is use case behind this feature:**

Currently performance will be suboptimal on Azure Kubernetes Deployments using SSDs and this flag would enable using the right tuning.

**Environment**:
Azure Kubernetes Service

**Comment by andrewsali** [comment]
Does that really affect the tuning as well? - this issue suggest otherwise: https://github.com/rook/rook/issues/4298

We have set the crushDeviceClass to ssd, the OSD devicelass is indeed showing SSD, but the dashboard still reports the OSDs as being rotational. It's unclear if the appropriate tuning is applied?

**Comment by leseb** [comment]
@andrewsali right, even if we change that, Ceph will still read the rota property of the osd disk.

@subhamkrai ok, here is what we need to do:

* Similarly to https://github.com/rook/rook/issues/4298 create a new CRD property `tuneFastDeviceClass`
* Find the default value for:
  - osd_recovery_sleep
  - osd_snap_trim_sleep
  - osd_delete_sleep
You can look at https://github.com/ceph/ceph/blob/master/src/common/options.cc for this.

* Then force set those values in the CLI run of the OSD process.

@jdurgin please correct me if I'm wrong :)

**Comment by jdurgin** [comment]
@leseb I think we'd want to set all the ssd tuned options - here's a list: https://gist.github.com/jdurgin/cf63bf0ec61bdc9a3ce4e60a5b0c4b30
