### ISSUE TITLE
Ceph cluster "healthCheck" field API modification to be more coherent

### ISSUE THREAD

**Issue by shellwedance** [rook/rook#6201]
**Suggestion**

Modify `disabled` key to `enabled` in `spec.healthCheck.daemonHealth` of CephCluster CRD

**Reason**

- `spec.dashboard` and `spec.monitoring` provide `enabled` field 
  - Because dashboard and prometheus modules are not in *always_on_modules* in mgr.
- `spec.crashCollector` provides `disable` field 
  - Because crash module is in *always_on_modules* in mgr.

From the perspective on above, Rook takes `disable` keyword if the field is set as default in Ceph. If any extra command or action is required, Rook takes `enabled`.

`spec.healthCheck` field requires extra actions of rook operator.
This field lets operator check health of daemons and mon quorum. If something is wrong, it makes operator try to fix the problem.
So, `enabled` is more adequate than `disabled`.

In addition, when `spec.healthCheck` field is blanked, the field is not configured at all.
It seems more proper the field would be configured with some value because default setting of `spec.healthCheck` is `disabled: false`. 
(Consider that rook-ceph-crashcollector is deployed although `spec.crashCollector` is blanked)
This can be solved by changing `spec.healthCheck`'s `disabled` to `enabled`.

If you agree, I can undertake this.

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
The reason why we use `disabled` instead of `enabled` is because we added these options after the healthcheck. Basically, the healthcheck has always been enabled and we don't want to disable it. Also, when upgrading we want to keep it running. And because it's a bool and its default value is false, it's just easier to manage it.
So I'd keep things as they are, also, this is in the API so we don't want to change the schema.

**Comment by shellwedance** [comment]
> Basically, the healthcheck has always been enabled and we don't want to disable it.

If then, I think some default values should be configured though `spec.healthCheck` is empty in yaml.

```yaml
# cluster.yaml
...
spec:
  ...
  healthCheck:   # empty
  disruptionManagement:
  ...
...
```
Currently no value is set in CephCluster CR if the field is empty.

```shell
$ kubectl get CephCluster -n rook-ceph rook-ceph -o yaml
...
    healthCheck:
      daemonHealth:
        mon: {}
        osd: {}
        status: {}
...
```
