### ISSUE TITLE
[Error -2 ] Name or service not known & Error resolving a server hostname

### ISSUE THREAD

**Issue by krishnadasari610** [rook/rook#6221]
**Is this a bug report or feature request?**
* Bug Report
![s3 bucket creation issue](https://user-images.githubusercontent.com/19946280/92591349-5bbadb00-f2bb-11ea-94cd-45dc4c56c3bc.jpg)

[s3cfg_configuration file.txt](https://github.com/rook/rook/files/5199588/s3cfg_configuration.file.txt)

**Deviation from expected behavior:**
![image](https://user-images.githubusercontent.com/19946280/92877427-c76e8680-f428-11ea-85ba-bc9d4e112441.png)

**Expected behavior:**
**this should display the s3 buckets information**
**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
   
![image](https://user-images.githubusercontent.com/19946280/92690029-cae90b80-f35d-11ea-9dc7-c1d6c46de72a.png)

* Kernel (e.g. `uname -a`):
![image](https://user-images.githubusercontent.com/19946280/92690045-d6d4cd80-f35d-11ea-9203-c4fbd6e2201f.png)

* Cloud provider or hardware configuration:
NA
* Rook version (use `rook version` inside of a Rook Pod):
NA
* Storage backend version (e.g. for ceph do `ceph -v`):
![image](https://user-images.githubusercontent.com/19946280/92690105-f23fd880-f35d-11ea-9e96-cfe5b230dec8.png)

* Kubernetes version (use `kubectl version`):
NA
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
NA

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
![image](https://user-images.githubusercontent.com/19946280/92690340-75f9c500-f35e-11ea-8b80-cb01f00ffa44.png)

**Comment by leseb** [comment]
You need to complete the bug template.

**Comment by krishnadasari610** [comment]
> You need to complete the bug template.

Hi @leseb - I have updated the required information to the ticket , can you please help me to resolve this error, and was there any configuration issue ?

**Comment by travisn** [comment]
@krishnadasari610 You followed all the steps in the [object storage guide](https://rook.github.io/docs/rook/v1.4/ceph-object.html)? It seems `s3cmd` isn't able to reach the dns entry for the rgw server. Where is your s3cmd running? Is it in the toolbox or some other pod? Or external to the cluster?
