### ISSUE TITLE
Build fails on Ubuntu 17.04

### ISSUE THREAD

**Issue by lorenz** [rook/rook#624]
Everything works fine up to building the cephd package, then I get
```
/usr/bin/ld: /home/lorenz/go/src/github.com/rook/rook/.work/build/x86_64-linux-gnu/lib/libboost_iostreams.so: undefined reference to symbol 'BZ2_bzDecompressEnd'
//lib/x86_64-linux-gnu/libbz2.so.1.0: error adding symbols: DSO missing from command line
```
I tried manually adding `-lbz2` but that does not affect the result, even though it is part of the command line (dumped from `make V=1`):
```
x86_64-linux-gnu-g++ -I . -fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -o $WORK/github.com/rook/rook/pkg/cephmgr/cephd/_obj/_cgo_.o $WORK/github.com/rook/rook/pkg/cephmgr/cephd/_obj/_cgo_main.o $WORK/github.com/rook/rook/pkg/cephmgr/cephd/_obj/_cgo_export.o $WORK/github.com/rook/rook/pkg/cephmgr/cephd/_obj/cephd.cgo2.o $WORK/github.com/rook/rook/pkg/cephmgr/cephd/_obj/malloc.cgo2.o $WORK/github.com/rook/rook/pkg/cephmgr/cephd/_obj/dummy.cc.o -L/home/lorenz/go/src/github.com/rook/rook/.work/build/x86_64-linux-gnu/lib -lbz2 -Wl,-Bstatic -ltcmalloc_minimal -Wl,-Bdynamic -Wl,-Bstatic -lcephd -Wl,-Bdynamic -lboost_system -lboost_thread -lboost_iostreams -lboost_random -lblkid -lcurl -lrocksdb -lz -lsnappy -lzstd -lcryptopp -lssl -lcrypto -laio -luuid -lexpat -ldl -lm -lresolv
```
libbz2-dev is installed and the files themselves are fine.

**Comment by bassam** [comment]
@lorenz have you tried using the build container? Try 'build/run make -j4' . Also see https://github.com/rook/rook/blob/master/build/README.md

**Comment by lorenz** [comment]
It worked with the container, thanks! Though I'm not sure why it wouldn't work on my host machine since I'm using exactly the same operating system.

**Comment by bassam** [comment]
@lorenz FWIW, I suspect that rook is picking up your system boost which seems to be compiled with bzip2. I sometimes build on my ubuntu box -- I'll take a look.
