### ISSUE TITLE
The minimum supported Ceph version for the External Cluster

### ISSUE THREAD

**Issue by runzhliu** [rook/rook#6249]
**Is this a bug report or feature request?**

* Bug Report
* Feature Request

No.

**Deviation from expected behavior:**

As the [Rook Document](https://rook.io/docs/rook/master/ceph-cluster-crd.html) introduces, the minimum supported Ceph version for the External Cluster is **Luminous 12.2.x**.

However, the code as follows shows the Nautilus is the minimum version for external cluster.

> https://github.com/rook/rook/blob/2052d5e657b748697a04e936409611daf2fbc909/pkg/operator/ceph/version/version.go#L273 

Does it mean at least Nautilus external cluster could be connected, or the documents were out of date?

Thanks :)

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

**Feature Request**

**Are there any similar features already existing:**

**What should the feature do:**

**What would be solved through this feature:**

**Does this have an impact on existing features:**

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
IIRC that Nautilus check is only triggered if the cephVersion is specified in the cluster CR. If it is not specified, it wouldn't be triggered. Correct @leseb?

**Comment by leseb** [comment]
Luminous is when you only consume the cluster, if you create resources on k8s (object/file CRs) then you need Nautilus.

**Comment by runzhliu** [comment]
> Luminous is when you only consume the cluster, if you create resources on k8s (object/file CRs) then you need Nautilus.

 Got it, thanks.
