### ISSUE TITLE
Consider possibility for same OSD ID on multiple nodes

### ISSUE THREAD

**Issue by troeger** [rook/rook#6257]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

It can happen that the same OSD ID shows up on multiple nodes. Depending on the order of OSD pod startup, the newest version or an older version of this OSD ID then tries to connect to the MON. In the former case, everything is fine. In the latter case, the CephX authentication fails and the OSD gets stucked in a crash loop. Restarting the (invalid) OSD pod keeps it on the same node, so the problem persists. This becomes especially painful during operator updates, since the permanent OSD restart produces increasing timeout waiting loops.

For the end user, this looks like a random flapping between "unhealthy" and "healthy" cluster state, which just depends on the (invisible) pod startup order. The (invalid) OSD pod only claims a failed MON authentication in the logs, so the problem is not directly identifiable.

**Expected behavior:**

Minimum: Rook should identify duplicate / ill-placed OSD IDs on nodes and produce an according warning in the logs. 
Optimum: Blacklist older duplicate OSD IDs automatically during the initial discovery on the node. 

Please note that Ceph simply expects the human administrator to not make such a mistake, so this is clearly the responsibility of the automated OSD deployment given by Rook.

**How to reproduce it (minimal and precise):**

One example for this scenario seems to be described in #5835. Here is mine:

- Node is split from the cluster.
- Administrator removes the OSDs from Ceph.
- New disks are added, removed OSD IDs are automatically recycled.
- Node comes back, administrator forgets to wipe the disks before re-join.
- Rook discovery finds the "old" OSD LVM disks with the recycled IDs.

The duplication can be detected by running _ceph-volume lvm list_ on the nodes, and search for duplicate OSD IDs. The 'true' OSD location can be obtained with _ceph osd find XXX_ in the toolbox.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04 LTS
* Kernel (e.g. `uname -a`): Linux 4.15.0 x86_64
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod):  1.4.3
* Storage backend version (e.g. for ceph do `ceph -v`):  Ceph 14.2.10
* Kubernetes version (use `kubectl version`): 1.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Healthy, after deleting the wrong OSD disk with _wipefs -a -f_

**Comment by travisn** [comment]
When an OSD is provisioned in the osd prepare job, ceph-volume requests a new osd id. This is expected to give a unique id, rather than causing duplicates. Not sure what we can do about this in Rook. It's been the same behavior for a long time and we have never seen it happen before, so perhaps there is a rare race condition.

**Comment by troeger** [comment]
Ceph promises to use the lowest available OSD ID, given what it knows about the cluster. OSD ID recycling here is an expected feature for keeping them during disk replacement:

https://docs.ceph.com/docs/master/rados/operations/add-or-rm-osds/#replacing-an-osd

The problem occurs with disks that are not part of the cluster in this moment, but return later without being wiped beforehand. This is clearly a violation of the Ceph manual, but specifically becomes a problem with automated OSD daemon deployment, as given by Rook.

I agree that the case is not very common, so maybe this documentation here (or some paragraph in the manual) is good enough as final solution.
