### ISSUE TITLE
parameter of mon is not referenced in operator deployment

### ISSUE THREAD

**Issue by hezise** [rook/rook#6264]
I upgraded from 1.2.6 to 1.4.3

although in documentation the following parameters displayed:

mon.healthCheckInterval | The frequency for the operator to check the mon health | 45s
-- | -- | --
mon.monOutTimeout | The time to wait before failing over an unhealthy mon | 600s

they are not referenced in values file nor in operator deployment file

they do exist in 1.2.6 values file and also in operator deployment file.

Are those parameters still relevant?

Thanks,
Hezy

**Comment by travisn** [comment]
Those values in the operator deployment are still supported. However, they have moved to the cluster.yaml, which is the preferred location for these settings in new clusters. Please see the [v1.4.0 release notes](https://github.com/rook/rook/releases/tag/v1.4.0) for more details.

**Comment by hezise** [comment]
I saw the health check section in cluster and configured them.
I asked that because I didn't find in deployment.yaml of the operator any reference to mon.healthCheckInterval nor mon.monOutTimeout and I suggested that maybe you forgot to remove them from documentation of 1.4
