### ISSUE TITLE
OSDs not getting upgraded from 1.3.x to 1.4.x

### ISSUE THREAD

**Issue by ecusnir** [rook/rook#6268]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
It is expected that OSDs would be upgraded to the newest rook version like the other rook components.

**How to reproduce it (minimal and precise):**

In my case, I am running rook v1.3.11 with k8s 1.17.6. 
I have tried to upgrade to both v1.4.3 and v1.4.4 and the same problem occurred. After upgrading the operator, all the resources except the OSDs are being upgraded to the newer version.
I am using both CephBlockPool and CephObjectStore. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary

`2020-09-16 08:21:32.252318 I | cephclient: getting or creating ceph auth key "osd.134"
2020-09-16 08:21:32.821676 E | op-osd: failed to update osd deployment 134. failed to calculate diff between current deployment "rook-ceph-osd-134" and newly generated one. Failed to generate strategic merge patch: The order in patch list:
[map[name:POD_NAMESPACE value:rook-ceph] map[name:POD_NAMESPACE valueFrom:map[fieldRef:map[fieldPath:metadata.namespace]]] map[name:ROOK_CEPH_USERNAME valueFrom:map[secretKeyRef:map[key:ceph-username name:rook-ceph-mon]]] map[name:ROOK_CEPH_SECRET valueFrom:map[secretKeyRef:map[key:ceph-secret name:rook-ceph-mon]]] map[name:ROOK_OSDS_PER_DEVICE value:1]]
 doesn't match $setElementOrder list:
[map[name:ROOK_NODE_NAME] map[name:ROOK_CLUSTER_ID] map[name:ROOK_PRIVATE_IP] map[name:ROOK_PUBLIC_IP] map[name:POD_NAMESPACE] map[name:ROOK_MON_ENDPOINTS] map[name:ROOK_MON_SECRET] map[name:ROOK_CEPH_USERNAME] map[name:ROOK_CEPH_SECRET] map[name:ROOK_CONFIG_DIR] map[name:ROOK_CEPH_CONFIG_OVERRIDE] map[name:ROOK_FSID] map[name:NODE_NAME] map[name:ROOK_CRUSHMAP_HOSTNAME] map[name:CEPH_VOLUME_DEBUG] map[name:CEPH_VOLUME_SKIP_RESTORECON] map[name:DM_DISABLE_UDEV] map[name:ROOK_OSDS_PER_DEVICE] map[name:ROOK_ENCRYPTED_DEVICE] map[name:TINI_SUBREAPER] map[name:CONTAINER_IMAGE] map[name:POD_NAME] map[name:POD_NAMESPACE] map[name:NODE_NAME] map[name:POD_MEMORY_LIMIT] map[name:POD_MEMORY_REQUEST] map[name:POD_CPU_LIMIT] map[name:POD_CPU_REQUEST] map[name:ROOK_OSD_UUID] map[name:ROOK_OSD_ID] map[name:ROOK_OSD_STORE_TYPE] map[name:ROOK_CEPH_MON_HOST] map[name:CEPH_ARGS]]`

* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
* Kernel (e.g. `uname -a`):
5.4.0-42-generic
* Cloud provider or hardware configuration:
on-prem
* Rook version (use `rook version` inside of a Rook Pod):
v1.3.11
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.10 (b340acf629a010a74d90da5782a2c5fe0b54ac20) nautilus (stable)
* Kubernetes version (use `kubectl version`):
1.17.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
on-prem
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_OK

**Comment by travisn** [comment]
Per discussion in Slack, this seems related to a [K8s issue](https://github.com/kubernetes/kubernetes/issues/86163) that can fail the patch diff check if there is a duplicated env var.

**Comment by travisn** [comment]
@ecusnir Until the 1.4.5 release is out, can you test the interim release builds to confirm the OSDs will be upgraded? You can use the operator image: `rook/ceph:v1.4.4-15.g7988123`.

**Comment by ecusnir** [comment]
I have updated to `v1.4.4-15.g7988123` and I can confirm that the OSDs are upgraded correctly. Thanks for helping!
