### ISSUE TITLE
Add tests for ceph orchestrator commands

### ISSUE THREAD

**Issue by varshar16** [rook/rook#6270]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Testing of various ceph orchestrator commands with rook module enabled

**What is use case behind this feature:**
To ensure ceph orchestrator commands work correctly

**Environment**:

**Comment by leseb** [comment]
We already have tests in the integration suite, they have been disabled since they are unstable and waiting for this fix: https://github.com/rook/rook/pull/5884.

I'm closing this since we have it. Feel free to re-open if you have any concerns. Thanks.

**Comment by travisn** [comment]
Per discussion yesterday there are additional orch commands that also need to be added to that test so we get better coverage of the orchestrator module. @varshar16 Can you list in this issue the commands that you found were not working?

**Comment by varshar16** [comment]
Following commands don't work:
`ceph orch ps`: https://tracker.ceph.com/issues/47387, https://tracker.ceph.com/issues/47513
`ceph orch status`: https://tracker.ceph.com/issues/47511
`ceph orch device ls`: https://tracker.ceph.com/issues/47495

PR https://github.com/rook/rook/pull/6269 fixed `ceph orch ls`: https://tracker.ceph.com/issues/47337

**Comment by varshar16** [comment]
@travisn I have updated list of issues.

Updated bug list:
https://tracker.ceph.com/issues/47923
https://tracker.ceph.com/issues/47924
https://tracker.ceph.com/issues/47922
https://tracker.ceph.com/issues/47922
https://tracker.ceph.com/issues/47513

Fixed issues:
https://tracker.ceph.com/issues/47511
https://tracker.ceph.com/issues/47337

**Comment by varshar16** [comment]
Don't close the issue
New rook mgr module issues:
https://tracker.ceph.com/issues/49127
https://tracker.ceph.com/issues/49126
https://tracker.ceph.com/issues/48534
