### ISSUE TITLE
rook-ceph-osd-prepare fails due to low aio-max-nr setting.

### ISSUE THREAD

**Issue by brianczapiga** [rook/rook#6279]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
osd-prepare errors and disk preparation fails

**Expected behavior:**
osd-prepare completes

**How to reproduce it (minimal and precise):**
set /proc/sys/fs/aio-max-nr to 131072 (in my case) or lower.

kubectl logs on the prepare pods return:

2020-09-17 00:30:12.819939 D | exec:  stderr: 2020-09-17T00:30:12.145+0000 7f0c17632f40 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _read_fsid unparsable uuid
2020-09-17 00:30:12.819947 D | exec:  stderr: 2020-09-17T00:30:12.145+0000 7f0c17632f40 -1 bdev(0x56212de88700 /var/lib/ceph/osd/ceph-0//block) _aio_start io_setup(2) failed with EAGAIN; try increasing /proc/sys/fs/aio-max-nr
2020-09-17 00:30:12.819955 D | exec:  stderr: 2020-09-17T00:30:12.145+0000 7f0c17632f40 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _minimal_open_bluefs add block device(/var/lib/ceph/osd/ceph-0//block) returned: (11) Resource temporarily unavailable

**Environment**:
* OS (e.g. from /etc/os-release): Debian 9 Stretch
* Kernel (e.g. `uname -a`): 4.9.0-13-amd64
* Cloud provider or hardware configuration: baremetal lenovo servers
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`): v1.4.4
* Kubernetes version (use `kubectl version`): v1.18.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

  cluster:
    id:     c5e99999-889c-4f98-a8f7-9bd5e29cd962
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 8m)
    mgr: a(active, since 7m)
    mds: cephfs:1 {0=cephfs-a=up:active} 1 up:standby-replay
    osd: 36 osds: 36 up (since 7m), 36 in (since 44m)
 
  task status:
    scrub status:
        mds.cephfs-a: idle
        mds.cephfs-b: idle
 
  data:
    pools:   4 pools, 97 pgs
    objects: 22 objects, 4.9 KiB
    usage:   36 GiB used, 131 TiB / 131 TiB avail
    pgs:     97 active+clean
 
  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr

**Comment by brianczapiga** [comment]
Issue is was fixed, but after a discussion with @travisn , documenting it here for other users.

I created a privileged daemonset to set aio-max-nr to a higher value and the osd-prepare completes successfully.

```apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rook-aio
  namespace: rook-ceph
spec:
  selector:
    matchLabels:
      name: rook-aio
  template:
    metadata:
      labels:
        name: rook-aio
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      initContainers:
      - name: create-sysctl-file
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', 'echo fs.aio-max-nr=262144 > /etc/sysctl.d/98-rook-ceph-aio.conf']
        volumeMounts:
        - name: sysctld
          mountPath: /etc/sysctl.d
      - name: run-sysctl
        image: alpine:3.6
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', 'sysctl -w fs.aio-max-nr=262144']
        securityContext:
          privileged: true
        volumeMounts:
        - name: sysctld
          mountPath: /etc/sysctl.d
        - name: modifysys
          mountPath: /sys
      containers:
      - name: rook-aio
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['/bin/tail']
        args: ['-f','/dev/null']
        volumeMounts:
        - name: sysctld
          mountPath: /etc/sysctl.d
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sysctld
        hostPath:
          path: /etc/sysctl.d
      - name: modifysys
        hostPath:
          path: /sys
```

**Comment by MrAmbiG** [comment]
The daemonset yaml file failed on my setup
k8s tool: rke
k8s version: 1.18
nodes: ubuntu 18.04
rook: current master branch [12/14/2020]
What worked for me
To set the aio-max-nr value, add the following line to the /etc/sysctl.conf file: fs.aio-max-nr = 1048576.
To activate the new setting, run the following command: # sudo sysctl -p /etc/sysctl.conf.

**Comment by brianczapiga** [comment]
The daemonset in the original comment above was misformatted and `apiVersion` was not visible. I've modified the comment to make it visible.

The reason you would want to use the daemonset is that if you scale and add a node, you would want to be sure this setting is applied to the new nodes. If you are not planning on scaling or If you can manage that setting on all nodes in a different way (for instance in configuration management like puppet, chef, ansible, salt, etc.), then the daemonset is not required.
