### ISSUE TITLE
"FailedMount" for rescheduled pods using cephfs due to mount IP not updated when 3 mon pods failover

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#6280]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When failover all 3 mon pods, their service IPs are changed. The existing application pod with cephfs volume mounted still uses the original service IPs and will fail to mount when rescheduled. 

Below shows the error message when discribing the pod which is in "ContainerCreating" state. 
```
Events:
  Type     Reason       Age                    From                     Message
  ----     ------       ----                   ----                     -------
  Normal   Scheduled    <unknown>              default-scheduler        Successfully assigned rook-ceph/testrookfs-0 to ceph-worker-01
  Warning  FailedMount  2m40s (x2 over 4m58s)  kubelet, ceph-worker-01  Unable to attach or mount volumes: unmounted volumes=[my-fs], unattached volumes=[default-token-tnwxg my-fs]: timed out waiting for the condition
  Warning  FailedMount  82s (x3 over 5m26s)    kubelet, ceph-worker-01  MountVolume.MountDevice failed for volume "pvc-b9a064b3-3e38-4420-b307-d420cae2ec24" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-349f8672-f876-11ea-8843-429266047c55 already exists
  Warning  FailedMount  24s (x2 over 7m12s)    kubelet, ceph-worker-01  Unable to attach or mount volumes: unmounted volumes=[my-fs], unattached volumes=[my-fs default-token-tnwxg]: timed out waiting for the condition
```

**Expected behavior:**
The application pod should have updated new mount IPs or not incluing the static mon IPs as part of the mount operation.  

**How to reproduce it (minimal and precise):**

1). Failover all 3 mon pods one by one
2). Re-schedule a pre-exisitng pod that mounted on a cephfs volume
Note: The configmap rook-ceph-csi-config has the updated mon IPs. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

Only additional logs appears in plugin pods or provisioner pods are as below.
```
E0917 19:15:40.809742       1 nodeserver.go:83] ID: 20 Req-ID: 0001-0009-rook-ceph-0000000000000001-349f8672-f876-11ea-8843-429266047c55 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-349f8672-f876-11ea-8843-429266047c55 already exists
E0917 19:15:40.810202       1 utils.go:163] ID: 20 Req-ID: 0001-0009-rook-ceph-0000000000000001-349f8672-f876-11ea-8843-429266047c55 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-349f8672-f876-11ea-8843-429266047c55 already exists
E0917 19:17:42.902586       1 nodeserver.go:83] ID: 26 Req-ID: 0001-0009-rook-ceph-0000000000000001-349f8672-f876-11ea-8843-429266047c55 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-349f8672-f876-11ea-8843-429266047c55 already exists
E0917 19:17:42.902874       1 utils.go:163] ID: 26 Req-ID: 0001-0009-rook-ceph-0000000000000001-349f8672-f876-11ea-8843-429266047c55 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-349f8672-f876-11ea-8843-429266047c55 already exists
```

**Environment**:
* OS (e.g. from /etc/os-release): centos7
* Kernel (e.g. `uname -a`): Linux ceph-control-01 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod):  v1.3.1
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.11
* Kubernetes version (use `kubectl version`): v1.18.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by danielzhanghl** [comment]
Rook team,
ceph csi use CM rook-ceph-csi-config to get the mon endpoint, but the csi pod did not get recreate automatically when this CM is updated by Rook operator, suggest to add  checksum/configmap  annotations to all CSI POD spec, like this:
https://github.com/helm/helm/issues/2639

**Comment by Madhu-1** [comment]
@danielzhanghl can you please provide the cat output of the file inside the cephcsi container when the configmap is updated? I believe its kubelet responsibilty to update the configmap mount in cephcsi pods if not we can have a watcher in rook to update the cephcsi pods when configmap changes.

@travisn any thoughts?

**Comment by danielzhanghl** [comment]
@Madhu-1  the  CM can't update automatically without this checksum/configmap annotations, the pod won't be recreated.

**Comment by yanchicago** [comment]
@Madhu-1  Not sure what's the output of the file, for csi-cephfsplugin? If you refer "/etc/ceph-csi-config/config.json", it's updated with configmap rook-ceph-csi-config as expected. 

Also, as reported, none of the csi pods will be recreated with configmap change and no logs either.

**Comment by yanchicago** [comment]
Here's the description of the failed pod which is in ContainerCreating state, similar message shown in cephfsplugin pod. 
```
1). describe the failed pod
Events:
  Type     Reason       Age              From                     Message
  ----     ------       ----             ----                     -------
  Normal   Scheduled    <unknown>        default-scheduler        Successfully assigned rook-ceph/testrookfs-1 to ceph-worker-01
  Warning  FailedMount  7s               kubelet, ceph-worker-01  MountVolume.MountDevice failed for volume "pvc-d3b52576-7deb-4c1c-a73b-c3b048a0d37c" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount  6s               kubelet, ceph-worker-01  Unable to attach or mount volumes: unmounted volumes=[my-fs], unattached volumes=[my-fs default-token-mzggq]: timed out waiting for the condition
  Warning  FailedMount  3s (x3 over 7s)  kubelet, ceph-worker-01  MountVolume.MountDevice failed for volume "pvc-d3b52576-7deb-4c1c-a73b-c3b048a0d37c" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 already exists
2). cephfsplugin log

E0918 15:42:01.022715       1 nodeserver.go:83] ID: 30 Req-ID: 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 already exists
E0918 15:42:01.022749       1 utils.go:163] ID: 30 Req-ID: 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 already exists
E0918 15:42:09.054814       1 nodeserver.go:83] ID: 32 Req-ID: 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 already exists
E0918 15:42:09.054865       1 utils.go:163] ID: 32 Req-ID: 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 already exists

```

**Comment by yanchicago** [comment]
After deleting the "FailedMount" pod and redeploy the statefulset, the pvc is in "Pending" state. 
The csi-cephfsplugin-provisioner pod shows below failure. Any workaround?
```
E0922 02:25:34.984667       1 controller.go:1334] delete "pvc-d3b52576-7deb-4c1c-a73b-c3b048a0d37c": volume deletion failed: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 already exists
W0922 02:25:34.984738       1 controller.go:936] Retrying syncing volume "pvc-d3b52576-7deb-4c1c-a73b-c3b048a0d37c", failure 8
E0922 02:25:34.984763       1 controller.go:954] error syncing volume "pvc-d3b52576-7deb-4c1c-a73b-c3b048a0d37c": rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-9f8bd31a-f9bc-11ea-812a-7e5e86ceb1e5 already exists
I0922 02:25:34.985429       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-0991a240-ce24-4f4d-9c16-d7cbfa00f038", UID:"43b6b98d-59ca-4aae-b510-e25e4cb75fbc", APIVersion:"v1", ResourceVersion:"20976091", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-d8ee4e7d-f927-11ea-812a-7e5e86ceb1e5 already exists
```

**Comment by galexrt** [comment]
@yanchicago Please post the logs of all containers from the rbd plugin Pod of the machine the volume can't be mounted and post the list of `volumeattachments.storage.k8s.io` (`kubectl get volumeattachments.storage.k8s.io`). In addition to that post the PersistentVolume names for the PVC(s) that are being mounted.

**Comment by yanchicago** [comment]
@galexrt Don't see any special logs in rbd plugin pods as its cephfs usage.  
1. During 3 mon failover, no logs shown in cephfsplugin or provisioner pods. 
```
# kubectl get volumeattachments.storage.k8s.io
NAME                                                                   ATTACHER                        PV                                         NODE             ATTACHED   AGE
csi-163c7a79e3a9a22448db464e4c9c58c7ee38e7fcae697456c1a1ab25ddb4f258   rook-ceph.cephfs.csi.ceph.com   pvc-1a3b99ce-6119-41f3-a938-727a99f86a38   ceph-worker-01   true       50m
csi-241436216234ab874aabe2305202aaa2be31abea3d4b937f946cdc438485088b   rook-ceph.cephfs.csi.ceph.com   pvc-8d15e9e9-6909-4c56-9e56-d8d7db5d440c   ceph-worker-01   true       50m

```
2. Delete the test pod, which was restarted on the same node and then stucked in "ContainerCreating" state due to "FailedMount". The cephfs plugin pod has below error logs.
```
E0922 15:09:05.269913       1 nodeserver.go:83] ID: 248 Req-ID: 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e already exists
E0922 15:09:05.269989       1 utils.go:163] ID: 248 Req-ID: 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e already exists
E0922 15:09:06.372761       1 nodeserver.go:83] ID: 250 Req-ID: 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e already exists
E0922 15:09:06.372859       1 utils.go:163] ID: 250 Req-ID: 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e already exists
E0922 15:09:08.483273       1 nodeserver.go:83] ID: 252 Req-ID: 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-c530ba07-fcdd-11ea-a0e2-4efdc282348e already exists
```
```
# kubectl get volumeattachments.storage.k8s.io
NAME                                                                   ATTACHER                        PV                                         NODE             ATTACHED   AGE
csi-163c7a79e3a9a22448db464e4c9c58c7ee38e7fcae697456c1a1ab25ddb4f258   rook-ceph.cephfs.csi.ceph.com   pvc-1a3b99ce-6119-41f3-a938-727a99f86a38   ceph-worker-01   true       61m
csi-241436216234ab874aabe2305202aaa2be31abea3d4b937f946cdc438485088b   rook-ceph.cephfs.csi.ceph.com   pvc-8d15e9e9-6909-4c56-9e56-d8d7db5d440c   ceph-worker-01   true       61m
```
3. Drain node to force the pod rescheduled on another node, both pods were able to be up and running and no logs printed in csi pods.

**Comment by galexrt** [comment]
@yanchicago Could you explain more what "3 mon failover" means for your case?
Did every mon get a "normal" failover by the Rook Ceph operator or where the mons completely recreated?

Run the following commands in the Rook Ceph toolbox and post the output:
```
ceph -s

ceph fs volume ls
# The above command should have returned one volume use it in the next one as the VOLUME_NAME
ceph fs subvolume ls VOLUME_NAME
```

**Comment by yanchicago** [comment]
3 mon pods failed over one by one so the existing IPs used on cephfs mount point become all invalid.  Everyting else is normal. 
Discussed the issue with @Madhu-1 and @travisn . This is an issue easy to be reproduced and cause is clear. Need to know, by design how this issue can be worked out.

**Comment by Madhu-1** [comment]
> generally speaking the IPs should not change frequently

as we are using Mon service IP the issue can happen. If your workload is moved to a new node this will be fixed as it fetches the new IPs from configmap. @travisn any idea/suggestion to fix this issue?

**Comment by travisn** [comment]
Does the cephfs volume only get the mons refreshed when the pod is mounted? Once the volume is mounted, it should keep a connection and ceph will update automatically on that connection. 

@yanchicago Are you simulating the mon failover, or you saw this happen in production? This has always been rook's design to rely on the mon service endpoints and mon failover, expecting the clients to refresh. If it helps, you can increase the mon failover time if the intermittent network issues are causing too much failover.

**Comment by yanchicago** [comment]
@travisn The issue was reported by the user and I was able to reproduce. But I don't see the client refresh regardless waiting time.
If the client doesn't refresh, the mon pods could failover eventually, even over months. One mon pod can fail, then 3 mon pods can fail.

**Comment by DomHoney** [comment]
Nothing useful to add other than that I have also been seeing this issue. Mons have been rescheduled because we've had to drain nodes recently, the provisioner still tries to use the old mon IPs and new PVCs hang which has caused some downtime for us.

**Comment by danielzhanghl** [comment]
@Madhu-1 could the mon cluster IP be as part of input when deployment? then it won't change during recreate.

**Comment by Madhu-1** [comment]
The Mon-IP's are updated in the configmap by the Rook. cephcsi won't cache the Mon Ip's. For each request, it will read the IP from the mounted configmap
