### ISSUE TITLE
Helm chart should add CSI settings to configmap instead of deployment

### ISSUE THREAD

**Issue by travisn** [rook/rook#6288]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The CSI settings have moved from the operator deployment to a [configmap](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L22) for operator settings to be more easily overridden. The [helm chart](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/deployment.yaml) should have a similar change instead of continuing to use the env vars.

**Expected behavior:**
Helm chart implementation should be consistent with the non-helm install.

**Comment by xiaods** [comment]
the chart is read the env from values.yaml,  don't need configmap. I don't think this is bug.

**Comment by travisn** [comment]
This is just an implementation detail. The same settings will still be available in the values.yaml after this change is made.

**Comment by xiaods** [comment]
> This is just an implementation detail. The same settings will still be available in the values.yaml after this change is made.

that's fine. need PR

**Comment by travisn** [comment]
This is really just an implementation detail. The only benefit of this change would be that the operator would not need to be restarted if some of the settings are updated, but the consistency in implementation is not important. Closing due to comments in #9074.
