### ISSUE TITLE
can't set the number of replica for csi-cephfsplugin-provisioner and csi-rbdplugin-provisioner

### ISSUE THREAD

**Issue by hezise** [rook/rook#6294]
I'm using rook1.4
when running tests I'm creating a cluster of 1 node.
before running the tests I'm validating that all pods are up and running
it seems that it tries to deploy more than one pod for the provisioner but since I have only one node it stays in pending state and therefor my test that validate all the pods are up fails and testing is not performed.
I couldn't find where can I set the number of pods

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
It's a known issue that doesn't affect the functionality of the cluster. However, it does cause confusion for those testing in single-node clusters so it would be nice to only run the provisioners with a single replica if there is only a single node.
