### ISSUE TITLE
Add pool usage statistics

### ISSUE THREAD

**Issue by leseb** [rook/rook#6295]
Let's report the used capacity in a CephBlockPool as part of the Status field.

**Comment by TonyBogdanov** [comment]
You could just use [Prometheus](https://prometheus.io/)? Rook already has an exporter, you just need to enable it in the manifests.

**Comment by leseb** [comment]
Yes, I'm aware of the exporter and prometheus. There are UIs for Kubernetes that are reading CR's status to display additional information. So it's a nice to have not necessarily a must-have.

**Comment by leseb** [comment]
As per discussion, we won't implement this as prometheus is the best place to gather these sort of metrics (through the exporter).
