### ISSUE TITLE
RGW crashlooping due to dynamic resharding on big bucket

### ISSUE THREAD

**Issue by ashangit** [rook/rook#6304]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When dynamic re-sharding of big bucket (more than 30 millions of objects) occurred a lock on the bucket can be held for long (15/20 min) time. Then the RGW can be killed by the livenessprobe as the RGW doesn't answer anymore or really slowly.
As the dynamic re-sharding is managed by the RGW it also means that it killed the re-sharding.
Then once the RGW is restarted it start again the re-sharding and is killed again and so on.
To resolve this we had to disable operator and remve livenessprobe from the rgw delpoyment

**Expected behavior:**
I would expect the RGW not to be killed so the re-shard can be achieved. I also agree that probably pre-sharding should be done on such bucket but having the re-shard constantly killed is not fine also.

Could we work on a way to disable  the livenesspobe or configure the livenesspobe timeout?

**How to reproduce it (minimal and precise):**

Create huge bucket and see how reshading impact the rgw (for 1k shards)

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@ashangit It is possible to disable the liveness probe on the rgw daemon with [this setting](https://github.com/rook/rook/blob/release-1.4/cluster/examples/kubernetes/ceph/object.yaml#L96-L97). You should also be able to change any of the liveness probe settings on the rgw, similar to [this example](https://rook.github.io/docs/rook/v1.4/ceph-cluster-crd.html#health-settings) in the cluster CR, but modifying for the rgw liveness probe. Is that what you're looking for?

@thotz Anything we can do about the responsiveness of rgw during a resharding?

**Comment by thotz** [comment]
@travisn I guess we can check the reshard status. And to skip `liveprobeness` during that time.Also need to  check other processes can effect liveprobeness

**Comment by travisn** [comment]
Changing the liveness probe requires an update to the deployment isn't very feasible since it would restart rgw. Is there a different check we should use in the liveness probe that is not affected by the reshard?

**Comment by thotz** [comment]
> Changing the liveness probe requires an update to the deployment isn't very feasible since it would restart rgw. Is there a different check we should use in the liveness probe that is not affected by the reshard?

will check in Monday's call and update

**Comment by leseb** [comment]
@ashangit can we get the rgw logs so we can see the latency on the swift/healthcheck path? Thanks

**Comment by ashangit** [comment]
@leseb sorry I don't have those logs anymore
I will try to reproduce this week or next one on our test env

**Comment by mkogan1** [comment]
@ashangit checkeed on a _vstart.sh_ cluster (HDDs) while resharding 10M objects bucket
the watchdog http GET operation to the _/swift/healthcheck_ url latency is not affected by ongoing resharding.

while resharding is in progress:
```
./bin/radosgw-admin reshard status --bucket=bp01000000000000
    {
        "reshard_status": "in-progress",
        "new_bucket_instance_id": "2a471994-4a83-482c-bc33-c8df9bfe83e8.58134.1",
        "num_shards": 9
    }
    ...
```
timing:
```
time curl -sv -D - "http://127.0.0.1:8000/swift/healthcheck"  
0.00s user 0.00s system 91% cpu 0.007 total
```
```
tail -F ./out/radosgw.8000.log
...
2020-10-14T17:00:53.213+0300 7f0d2938d700  1 ====== starting new request req=0x7f0d23b81a60 ===== 
2020-10-14T17:00:53.214+0300 7f0d2938d700  1 ====== req done req=0x7f0d23b81a60 op status=0 http_status=200 latency=0.001000005s ====== 
2020-10-14T17:00:53.214+0300 7f0d2938d700  1 beast: 0x7f0d23b81a60: 127.0.0.1 - - [2020-10-14T17:00:53.213368+0300] "GET /swift/healthcheck HTTP/1.1" 200 0 - "curl/7.66.0" - 
```
bringing attention to the `latency=` above.

Few questions please:
1. please send rgw logs to make sure that the watchdog is checking the designated url: `GET /swift/healthcheck` 
    and if so, please check the questions below:
2. this is dynamic resharding correct? (was not triggered by radosgw-admin command)
3. to how many shards is it resharding (output of this command from toolbox can provide this info `radosgw-admin reshard status --bucket=<bucket> | tail`) and also please output of `ceph df`

**Comment by ashangit** [comment]
Here are answers to the questions reproducing it on a test env:

1. Yes the watchdog is checking the swift URL and timeout are reached trying to request it:
Ex. of RGW log
_debug 2020-12-21 22:24:05.058 7f26b04fd700  1 beast: 0x561935ac8700: 10.225.78.17 - - [2020-12-21 22:24:05.0.058519s] "GET /swift/healthcheck HTTP/1.1" 200 0 - "kube-probe/1.14" -_
Health Check log
_I1221 22:21:06.058890   30223 prober.go:112] Liveness probe for "rook-ceph-rgw-shared-1-c-95b7d84c5-gw5js_rook-ceph(590914c3-3ad7-11eb-a6e0-b4a9fc43ee70):rgw" failed (failure): Get http://10.225.78.17:9001/swift/healthcheck: net/http: request canceled (Client.Timeout exceeded while awaiting headers)_
2. Yes it is dynamic resharding not triggered manually
RGW log
_debug 2020-12-21 22:19:36.784 7f4f3f350700 0 check_bucket_shards: resharding needed: stats.num_objects=95607742 shard max_objects=95600000
debug 2020-12-21 22:19:36.784 7f4f3f350700 1 check_bucket_shards bucket pixoriginalcache need resharding old num shards 956 new num shards 1912
...
debug 2020-12-21 22:28:46.295 7f661a2fd700  1 check_bucket_shards bucket pixoriginalcache need resharding  old num shards 956 new num shards 1921_
3. As you can see in the RGW log it tries to reshard to 1921 shards
```
[root@rook-ceph-tools-77dc8ff47c-8s8gp /]# radosgw-admin reshard status --bucket=pixoriginalcache
[
    {
        "reshard_status": "in-progress",
        "new_bucket_instance_id": "7fc62377-aa69-4bc2-ba9c-bc1cdd85429a.6566575.1",
        "num_shards": 1921
    },
    {
        "reshard_status": "in-progress",
        "new_bucket_instance_id": "7fc62377-aa69-4bc2-ba9c-bc1cdd85429a.6566575.1",
        "num_shards": 1921
    },
    {
        "reshard_status": "in-progress",
        "new_bucket_instance_id": "7fc62377-aa69-4bc2-ba9c-bc1cdd85429a.6566575.1",
        "num_shards": 1921
    },
    ....

[root@rook-ceph-tools-77dc8ff47c-8s8gp /]# ceph df
RAW STORAGE:
    CLASS     SIZE       AVAIL      USED       RAW USED     %RAW USED 
    ssd       52 TiB     35 TiB     16 TiB       17 TiB         32.99 
    TOTAL     52 TiB     35 TiB     16 TiB       17 TiB         32.99 
 
POOLS:
    POOL                            ID     PGS     STORED      OBJECTS     USED        %USED     MAX AVAIL 
    cephfs-metadata                 35      32      21 KiB          22     137 KiB         0       5.4 TiB 
    cephfs-data0                    36      32         0 B           0         0 B         0       5.4 TiB 
    shared-1.rgw.control            58       8         0 B           8         0 B         0       5.4 TiB 
    shared-1.rgw.meta               59       8     7.4 KiB          30     337 KiB         0       5.4 TiB 
    shared-1.rgw.log                60       8      34 KiB         214      58 KiB         0       5.4 TiB 
    shared-1.rgw.buckets.index      61       8      22 GiB       5.67k      22 GiB      0.13       5.4 TiB 
    .rgw.root                       62       8     3.7 KiB          16     180 KiB         0       5.4 TiB 
    shared-1.rgw.buckets.non-ec     63       8         0 B           0         0 B         0       5.4 TiB 
    shared-1.rgw.buckets.data       64     512     9.7 TiB      96.18M      16 TiB     49.83       9.7 TiB 
```

For the latency observed when the healthcheck failed I don't have any logs for it in the RGW log (as if it just failed to contact it):
HealthCheck log:
```
December 21st 2020, 22:21:26.05930223
I1221 22:21:26.058895   30223 prober.go:112] Liveness probe for "rook-ceph-rgw-shared-1-c-95b7d84c5-gw5js_rook-ceph(590914c3-3ad7-11eb-a6e0-b4a9fc43ee70):rgw" failed (failure): Get http://10.225.78.17:9001/swift/healthcheck: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
December 21st 2020, 22:21:36.05930223
I1221 22:21:36.058793   30223 prober.go:112] Liveness probe for "rook-ceph-rgw-shared-1-c-95b7d84c5-gw5js_rook-ceph(590914c3-3ad7-11eb-a6e0-b4a9fc43ee70):rgw" failed (failure): Get http://10.225.78.17:9001/swift/healthcheck: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
December 21st 2020, 22:21:46.05930223
I1221 22:21:46.058635   30223 prober.go:112] Liveness probe for "rook-ceph-rgw-shared-1-c-95b7d84c5-gw5js_rook-ceph(590914c3-3ad7-11eb-a6e0-b4a9fc43ee70):rgw" failed (failure): Get http://10.225.78.17:9001/swift/healthcheck: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

And here the RGW log (as you can see no call seen for those 3 calls)
```
December 21st 2020, 22:21:06.216rook-ceph-rgw-shared-1-c-95b7d84c5-gw5js
debug 2020-12-21 22:21:06.215 7f62ed69c700  1 beast: 0x55909757c700: 10.225.78.17 - - [2020-12-21 22:21:06.0.215794s] "GET /swift/healthcheck HTTP/1.1" 200 0 - "kube-probe/1.14" -
December 21st 2020, 22:21:15.878rook-ceph-rgw-shared-1-c-95b7d84c5-gw5js
debug 2020-12-21 22:21:15.877 7f624b558700  1 beast: 0x55909b640700: 10.225.78.17 - - [2020-12-21 22:21:15.0.877887s] "GET /swift/healthcheck HTTP/1.1" 200 0 - "kube-probe/1.14" -
December 21st 2020, 22:23:45.059rook-ceph-rgw-shared-1-c-95b7d84c5-gw5js
debug 2020-12-21 22:23:45.058 7f2730dfe700  1 beast: 0x56192b574700: 10.225.78.17 - - [2020-12-21 22:23:45.0.058326s] "GET /swift/healthcheck HTTP/1.1" 200 0 - "kube-probe/1.14" -
December 21st 2020, 22:23:55.058rook-ceph-rgw-shared-1-c-95b7d84c5-gw5js
debug 2020-12-21 22:23:55.058 7f269b4d3700  1 beast: 0x5619355d0700: 10.225.78.17 - - [2020-12-21 22:23:55.0.058422s] "GET /swift/healthcheck HTTP/1.1" 200 0 - "kube-probe/1.14" -
```

**Comment by satoru-takeuchi** [comment]
quoted from slack discussion

```
I encountered this problem and would like to fix it.

RGW crashlooping due to dynamic resharding on big bucket #6304
https://github.com/rook/rook/issues/6304

I tought that changing probe URL to "/"  seems to be good. However, I found the following commit.

https://github.com/rook/rook/commit/3c807688fe6a5fe5ce342221a77aac9a955bfe9

  to the RGWs swift objectstorage healthcheck api url [1]
 which resolves an OCS false-positive CLBO of the RGW pod.
 
 [1] https://docs.openstack.org/swift/latest/middleware.html#healthcheck

Does anybody know the detail of "false-positive" CLBO? And please let me know if you have any idea of preferable URL.
```

**Comment by satoru-takeuchi** [comment]
@mkogan1 

```
https://github.com/rook/rook/commit/3c807688fe6a5fe5ce342221a77aac9a955bfe9
  to the RGWs swift objectstorage healthcheck api url [1]
 which resolves an OCS false-positive CLBO of the RGW pod.
```

Did you remember why "/" is inappropriate for healthcheck?

**Comment by mkogan1** [comment]
> @mkogan1
> 
> ```
> https://github.com/rook/rook/commit/3c807688fe6a5fe5ce342221a77aac9a955bfe9
>   to the RGWs swift objectstorage healthcheck api url [1]
>  which resolves an OCS false-positive CLBO of the RGW pod.
> ```
> 
> Did you remember why "/" is inappropriate for healthcheck?

GET "/" is mapped to a list bucks operation that is propagated to the OSDs which depending on load (client load + deep scrub + backfill + etc...) can take longer time to respond than the health check timeout resulting in false failure indication.
The /swift/healthcheck API response is not dependant on OSD load.

**Comment by satoru-takeuchi** [comment]
```
GET "/" is mapped to a list bucks operation that is propagated to the OSDs which depending on load (client load + deep scrub + backfill + etc...) can take longer time to respond than the health check timeout resulting in false failure indication.
The /swift/healthcheck API response is not dependant on OSD load.
```

Thank you for your reply. I understood.

As I described in the previous post, "/swift/healthcheck/" would have a problem that it doesn't respons during bucket index resharding. Although I don't know the reason yet. Please let me if you know anything or know more proper endpoint.

Possibly it's better to report this problem in Ceph community.

**Comment by mkogan1** [comment]
> As I described in the previous post, "/swift/healthcheck/" would have a problem that it doesn't respons during bucket index resharding. Although I don't know the reason yet. Please let me if you know anything or know more proper endpoint.

Seems like a CPU starvation related performance issue during resharding.
There were improvements upstream to the reshard since the check time (sep 2020, the exact rgw version is not specified)
which potentially could improve CPU contention starvation situations.
may be worth our while to re-check with a current version.

**Comment by satoru-takeuchi** [comment]
Thank you! I encountered this issue recently. But it's octopus. I'll try to reproduce this problem with Pacific.

**Comment by satoru-takeuchi** [comment]
I'm trying to reproduce this problem in Pacific. Pleaae wait for a while.

**Comment by satoru-takeuchi** [comment]
@mkogan1 I'd like to take the further discussion in #8643 .
