### ISSUE TITLE
Rook.io Slack Workspace required @rook.io mail address for registration?

### ISSUE THREAD

**Issue by stv0g** [rook/rook#6308]
I am failing to register an account for the rook.io Slack channel via my mail address as it requires a mailbox at the @rook.io domain.

Can this requirement be lifted? I dont have a Google Account to use as a login.

**Comment by galexrt** [comment]
@stv0g Please use the Slack link on the homepage: https://slack.rook.io/
There you can register to get invite for the Rook slack.

Please let us know if that works for you.

**Comment by stv0g** [comment]
I already tried the link on the homepage.
After entering my mail it forwards me to https://rook-io.slack.com/ with the following dialog:

![image](https://user-images.githubusercontent.com/285829/93990358-4fd71a80-fd8b-11ea-8790-750697493b3a.png)

After I click on "Create an Account", I need to enter a @rook.io Mail address:

![image](https://user-images.githubusercontent.com/285829/93990470-6e3d1600-fd8b-11ea-85c4-0bf993c900c5.png)

**Comment by galexrt** [comment]
Going to the link I sent you (which is from the rook.io homepage), I get a form as the one in the screenshot I can enter my email address and after that I get no redirect, just an email with an invite link with which I can create an account.

![2020-09-23-111626_476x504_scrot](https://user-images.githubusercontent.com/3718398/93993104-a1cd6f80-fd8e-11ea-8fe9-07373e015be0.png)

When I follow the invite button in the email:

![image](https://user-images.githubusercontent.com/3718398/93993607-3df77680-fd8f-11ea-83b4-4bc16bf5d30e.png)

Creating the account works in my test right now without a @rook.io email address.

***

Could you post a screenshot of the link you are using from the Rook.io homepage? I'm trying to figure out where you got the "direct link" to `rook-io.slack.com`.

**Comment by stv0g** [comment]
Thanks, found the problem: I already hat an account on the Slack workspace and forgot about it 🙈
