### ISSUE TITLE
rook1.4.0 delete cephcluser at once without waiting  cleanup sanitize disks completed when cleanupPolicy turn on

### ISSUE THREAD

**Issue by little-guy-lxr** [rook/rook#6324]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

cephclster shouldn't be deleted at once before santize disk comleted if cleanup policy turn on

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@little-guy-lxr The operator actually cannot sanitize the disks until the cephcluster CR is deleted because it will cause all the ceph pods to be deleted, which frees up the disks for cleaning. The [documentation](https://rook.github.io/docs/rook/v1.4/ceph-cluster-crd.html#cleanup-policy) may help explain more.

What is your goal? Do you need to know when the sanitizing is completed? You could check for the completion of the sanitizing jobs.

**Comment by little-guy-lxr** [comment]
> @little-guy-lxr The operator actually cannot sanitize the disks until the cephcluster CR is deleted because it will cause all the ceph pods to be deleted, which frees up the disks for cleaning. The [documentation](https://rook.github.io/docs/rook/v1.4/ceph-cluster-crd.html#cleanup-policy) may help explain more.
> 
> What is your goal? Do you need to know when the sanitizing is completed? You could check for the completion of the sanitizing jobs.

I mean that when user delete cephcluster CR whose finalizer shouldn't remove until clean job completion

**Comment by leseb** [comment]
We cannot run the sanitize job if the finalized is still present and if the finalized is present we cannot do anything.
Back to @travisn's question, what's the concern?
