### ISSUE TITLE
[BUG] Delete namespace rook-ceph takes forever even GKE Dashboard don´t show any pod

### ISSUE THREAD

**Issue by WaterKnight1998** [rook/rook#6326]
**Is this a bug report or feature request?**
* Bug Report
 
`kubectl delete namespace rook-ceph` never finish. 

Even when kubernetes dashboard shows no pod running

**Expected behavior:**
Delete namespace as expected

**Environment**:
* Cloud provider or hardware configuration: GCE 1.15.12-gke.20 with Ubuntu Nodes
* Rook version (use `rook version` inside of a Rook Pod): 1.4.4
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE

**Comment by travisn** [comment]
It's likely there is a Rook CR with a finalizer that the operator has not cleaned up for some reason. Please review the [cleanup guide](https://rook.github.io/docs/rook/v1.4/ceph-teardown.html) for proper cleanup steps and how to workaround the finalizers if needed.
