### ISSUE TITLE
ceph crash periodic kubernetes cron job to prune crash

### ISSUE THREAD

**Issue by leseb** [rook/rook#6332]
After some time, we might want to prune the log from the collector.
For this, we could expand the `crash` section of the CephCluster CR and add an option to remove crashes older than X days.

We could then schedule a Kubernetes cron to perform the `ceph crash prune <keep>`, command.

**Comment by renan-campos** [comment]
Should the entry in /var/lib/ceph/crash/posted be removed as well?
