### ISSUE TITLE
Rook does not pick up old OSD when using directory option

### ISSUE THREAD

**Issue by lorenz** [rook/rook#634]
Running Rook latest-master on Kubernetes 1.6.1

Cluster configuration:
```
apiVersion: v1
items:
- apiVersion: rook.io/v1alpha1
  kind: Cluster
  metadata:
    creationTimestamp: 2017-04-21T01:19:40Z
    name: rook-temp
    namespace: rook-temp
    resourceVersion: "808748"
    selfLink: /apis/rook.io/v1alpha1/namespaces/rook-temp/clusters/rook-temp
    uid: 97ac3fde-2630-11e7-b3f6-82c874044ad8
  spec:
    dataDirHostPath: null
    storage:
      deviceFilter: null
      location: null
      metadataDevice: null
      nodes:
      - directories:
        - path: /mnt/ceph
        name: black
      - directories:
        - path: /mnt/ceph
        name: yellow
      - directories:
        - path: /mnt/ceph
        name: blue
      storeConfig:
        storeType: filestore
      useAllDevices: false
      useAllNodes: false
    versionTag: master-latest
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```
`/mnt/ceph` is a zvol XFS

If an OSD gets recreated, it does not recognize that there is already an OSD in `/mnt/ceph` and creates a new one. Example:

```
core@black ~ $ ls /mnt/ceph
osd0  osd1  osd4  osd6
```
The issue is that because all mons got scheduled to the same node (I'll open a separate issue for that) I had to restart some OSDs so that they picked up the mons again because of the constant IP issue. This resulted in more OSDs and not restarted ones so for example on the server above only `osd6` is actually running.

**Comment by travisn** [comment]
For the mons being scheduled on the same node, do you have at least three nodes? The anti-affinity should be applied in that case. 

Rook recognized that an osd already exists if it finds the configuration dir (such as `/var/lib/rook/osd6`) for the directory, with the mapping found in `/var/lib/rook/osd-dirs`. If those mappings don't exist, Rook assumes it needs to create a new osd. Can you confirm if those were preserved? It sounds like not.

**Comment by lorenz** [comment]
Yes, I do have 3 physical nodes. Where does the configuration dir go in the default configuration?

**Comment by travisn** [comment]
by default it goes in an EmptyDir created in `/var/lib/rook`. If you specify the `dataDirHostPath`, it will pick up the path from the host, which will be preserved beyond the lifetime of the osd pod.

**Comment by lorenz** [comment]
Where do I specify that?

**Comment by travisn** [comment]
for an example see https://github.com/rook/rook/blob/master/demo/kubernetes/rook-cluster.yaml, and documentation here: https://github.com/rook/rook/blob/master/Documentation/cluster-tpr.md#cluster-settings

**Comment by lorenz** [comment]
Thanks, specifying that should fix it.
