### ISSUE TITLE
rook-ceph operator take care of restarting the OSDs when the size of pvc changed

### ISSUE THREAD

**Issue by WaterKnight1998** [rook/rook#6349]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

The Rook Ceph operator should restart OSD's when the size of the pvc from cluster are edietd.

When I execute:
```
kubectl edit cephclusters.ceph.rook.io rook-ceph -n rook-ceph
```
Where I increase `spec.storage.storageClassDeviceSets.volumeClaimTemplates.spec.resources.requests.storage`.

I need to restart each osd one by one so the new size is shown from `ceph -s`.
**What is use case behind this feature:**

**Environment**:

**Comment by leseb** [comment]
This should not be the case. IIRC this was addressed in https://github.com/rook/rook/issues/5309.

**Fill the info template as requested. (rook version etc).**
