### ISSUE TITLE
csi-rbdplugin containers failing on arm64

### ISSUE THREAD

**Issue by stuartpb** [rook/rook#6368]
**Is this a bug report or feature request?**
* Bug Report

csi-rbdplugin pods are crashing on my Raspberry Pis because the driver-registrar container is dying with a `standard_init_linux.go:219: exec user process caused: exec format error`.

It seems like there was some discussion about this in #4051, but it's not clear to me from those comments how the problem could be solved, or even worked around.

**Environment**:
* OS (e.g. from /etc/os-release): OpenSUSE Kubic
* Kernel (e.g. `uname -a`): 5.8.10
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.4.5
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.5
* Kubernetes version (use `kubectl version`): 1.19.2 (and this time it's reporting it! :wink: )
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm

**Comment by Madhu-1** [comment]
Rook doesn't build or maintains the kubernetes sidecar image, in rook master we updated all the kubernetes sidecar images to the latest released versions https://github.com/rook/rook/blob/3e7e31fd3e24e8965fdc53eb8b78c021900eac65/pkg/operator/ceph/csi/spec.go#L99-L105
please check it deploying rook master helps for your testing.

**Comment by stuartpb** [comment]
I tried setting the `csi.*.image` values in my chart release to these by copying [the corresponding lines from the values.yaml in the repo](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/values.yaml#L241-L252), but the csi-resizer container failed with `flag provided but not defined: -csiTimeout` - I'm guessing this is something that's fixed in the current `master`?

**Comment by stuartpb** [comment]
The provisioner is also failing with `unknown flag: --enable-leader-election` - another thing I'm guessing is fixed in master.

**Comment by stuartpb** [comment]
Now I'm seeing issues in the attacher like this:

```
W1005 18:28:10.160804       1 trivial_handler.go:57] Error saving VolumeAttachment csi-6e5254814b54bfe79db9dd3d4aa2644cec19d607bebd4c0ab5a77fa9644a22a9 as attached: volumeattachments.storage.k8s.io "csi-6e5254814b54bfe79db9dd3d4aa2644cec19d607bebd4c0ab5a77fa9644a22a9" is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-rbd-provisioner-sa" cannot patch resource "volumeattachments/status" in API group "storage.k8s.io" at the cluster scope
```

Again, I'm assuming this is an error due to a major-version mismatch between 1.4.5 and master.

**Comment by jamesorlakin** [comment]
It's not a direct answer to your query, but I'm running the following images with 1.4.5 on my mixed NUC and Pi cluster:
```
  ROOK_CSI_ATTACHER_IMAGE: "raspbernetes/csi-external-attacher:2.2.0"
  ROOK_CSI_RESIZER_IMAGE: "raspbernetes/csi-external-resizer:0.5.0"
  ROOK_CSI_REGISTRAR_IMAGE: "raspbernetes/csi-node-driver-registrar:1.3.0"
  ROOK_CSI_PROVISIONER_IMAGE: "raspbernetes/csi-external-provisioner:1.6.0"
  ROOK_CSI_SNAPSHOTTER_IMAGE: "raspbernetes/csi-external-snapshotter:2.1.1"
```

I added these to the Raspbernetes project personally. The new default CSI images on GCR appear to have multiarch manifests but indeed failed to run for me with an exec error. When adding the images I found their build scripts do something funky (override GOARCH) and produce amd64 binaries even within an arm64 buildx environment. I had to patch that for the recent Raspbernetes releases - maybe that explains their images not working?

Provisoner v2.x changed the `--leader-selection` flag but I'm not sure if it's supported yet in an official release.

I'm intending on opening issues on the CSI repos but I need to verify all the images affected when I get time.

**Comment by Madhu-1** [comment]
> Rook doesn't build or maintains the kubernetes sidecar image, in rook master we updated all the kubernetes sidecar images to the latest released versions
> 
> https://github.com/rook/rook/blob/3e7e31fd3e24e8965fdc53eb8b78c021900eac65/pkg/operator/ceph/csi/spec.go#L99-L105
> 
> 
> please check it deploying rook master helps for your testing.

@stuartpb as I mentioned here  you need to use rook master, v1.4.5 cannot be used as this is not backported to 1.4 branch as it as breaking changes and RBAC changes

**Comment by Madhu-1** [comment]
> It's not a direct answer to your query, but I'm running the following images with 1.4.5 on my mixed NUC and Pi cluster:
> 
> ```
>   ROOK_CSI_ATTACHER_IMAGE: "raspbernetes/csi-external-attacher:2.2.0"
>   ROOK_CSI_RESIZER_IMAGE: "raspbernetes/csi-external-resizer:0.5.0"
>   ROOK_CSI_REGISTRAR_IMAGE: "raspbernetes/csi-node-driver-registrar:1.3.0"
>   ROOK_CSI_PROVISIONER_IMAGE: "raspbernetes/csi-external-provisioner:1.6.0"
>   ROOK_CSI_SNAPSHOTTER_IMAGE: "raspbernetes/csi-external-snapshotter:2.1.1"
> ```
> 
> I added these to the Raspbernetes project personally. The new default CSI images on GCR appear to have multiarch manifests but indeed failed to run for me with an exec error. When adding the images I found their build scripts do something funky (override GOARCH) and produce amd64 binaries even within an arm64 buildx environment. I had to patch that for the recent Raspbernetes releases - maybe that explains their images not working?
> 
> Provisoner v2.x changed the `--leader-selection` flag but I'm not sure if it's supported yet in an official release.
> 
> I'm intending on opening issues on the CSI repos but I need to verify all the images affected when I get time.

Yes it's good to open issue in  kubernetes-csi repo to get multi-arch  images help

**Comment by stuartpb** [comment]
For what it's worth, here's what I've got rolled out right now, and the only exec format failure I'm seeing is with the driver registrar (although my `csi-rbdplugin-provisioner` pods are only running on x64 right now, I have one `csi-cephfsplugin-provisioner` running on a Pi):

```yaml
csi:
  cephcsi:
    image: quay.io/cephcsi/cephcsi:v3.1.1
  registrar:
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v1.2.0
  provisioner:
    image: k8s.gcr.io/sig-storage/csi-provisioner:v1.6.0
  snapshotter:
    image: k8s.gcr.io/sig-storage/csi-snapshotter:v2.1.1
  attacher:
    image: k8s.gcr.io/sig-storage/csi-attacher:v2.1.0
  resizer:
    image: k8s.gcr.io/sig-storage/csi-resizer:v0.4.0
```

> @stuartpb as I mentioned here you need to use rook master, v1.4.5 cannot be used as this is not backported to 1.4 branch as it as breaking changes and RBAC changes

That's not an option here, as I intend to keep this cluster in operation long enough for Rook 1.5 to come out, and upgrades are not supported to or from master builds (or so [the documentation][1] tells me).

[1]: https://github.com/rook/rook/blob/master/Documentation/helm-operator.md
