### ISSUE TITLE
Migrating Rook from two namespaces to one causes pods with PVCs to get stuck

### ISSUE THREAD

**Issue by eknudtson** [rook/rook#6371]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Our rook installation began at version 0.9.x, and has the legacy `rook-ceph-system` and `rook-ceph` namespace split.  We migrated rook down to the single `rook-ceph` namespace as is the default for all new installs post 1.x.

While this worked and rook + ceph continued to operate properly, we found that any pods with existing PVC attachments were unable to be deleted or rescheduled.  The problem appears to be in the underlying PVs showing the wrong namespace for their CSI driver.

New PVC/PV creation happens as expected with the proper namespaces in various fields, and pods with those function as expected.

Examples from a PV created prior to the migration:

```
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph-system.rbd.csi.ceph.com
```

```
spec:
  csi:
    driver: rook-ceph-system.rbd.csi.ceph.com
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1571254575814-8081-rook-ceph-system.rbd.csi.ceph.com
```

If we force pod deletion and clean up its PVC / PVs, the underlying RBD image sticks around and we have to clean it up manually.  I _am_ able to rebuild PV/PVCs by utilizing information from existing PV/PVC resources and updating the csiProvisionerIdentity using the prefix from a new successfully created PV and the new namespace.  The recreated PV resource properly picks up the RBD image and works as expected, and a recreated PVC binds that PV.  This is far from ideal, however, since we often have to hop in to any watchers on the RBD image and forcefully unmount them after the pods they were attached to are force deleted.

**Expected behavior:**
Migrating rook to a single namespace from two namespaces should allow operations to continue without pods hanging on termination, nor should it require deleting + recreating PVCs/PVs.

**How to reproduce it (minimal and precise):**
For a Rook installation with Flexvolume driver disabled that is split across `rook-ceph-system` and `rook-ceph` namespaces:
1. Ensure ceph is healthy
1. Delete the rook operator deployment in `rook-ceph-system`
1. Ensure all CSI pods are also deleted
1. Delete any remaining deployments or daemonsets in `rook-ceph-system`
1. Delete any storageclasses referencing the `rook-ceph-system` namespace
1. Deploy common.yaml for the rook cluster version to the `rook-ceph` namespace
1. Deploy any storageclasses deleted previously, updating their provisioner namespace to `rook-ceph`
1. Deploy operator.yaml (with any cluster specific tweaks) to the `rook-ceph` namespace
1. Verify the operator runs successfully
1. Verify ceph is healthy
1. Attempt to delete a pod with a PVC created prior to the migration
1. Note that the pod hangs on termination during the PVC detach stage

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7
* Kernel (e.g. `uname -a`): 3.10.0-1127.19.1.el7.x86_64
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): 1.3.11
* Storage backend version (e.g. for ceph do `ceph -v`): v14.2.10-20200626
* Kubernetes version (use `kubectl version`): 1.17.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
The PV for the storage provider is immutable, so I'm not sure how we can support that conversion without the manual process. Leaving the old operator running would be good to try so the old volume could at least be removed.

**Comment by eknudtson** [comment]
Testing that now - so long as we're slowly able to migrate PVs one at a time we should be good to go here.

**Comment by eknudtson** [comment]
It looks like this won't work since `csi-rbdplugin-#####` daemonset pods are using host networking, attempting to spin up another will result in port collisions.

**Comment by travisn** [comment]
@eknudtson Try changing the csi driver ports as seen [here](https://github.com/rook/rook/blob/release-1.4/cluster/examples/kubernetes/ceph/operator.yaml#L244-L248).

**Comment by eknudtson** [comment]
Thanks for the tip, testing that out!

**Comment by eknudtson** [comment]
That worked:

- Set those ports in the rook operator configmap
- Don't delete `rook-ceph-system` operator deploy, just scale it to 1
- After applying common.yaml to `rook-ceph`, create temporary clusterrolebindings for the `rook-csi-rbd-plugin-sa` and `rook-csi-rbd-provisioner-sa` service accounts in `rook-ceph-system`.  I called mine `rbd-csi-nodeplugin-temp` and `rbd-csi-provisioner-role-temp`.
- One by one, recreate all PVC/PVs until everything is using the rook-ceph based storageclass provisioner.

**Comment by eknudtson** [comment]
This issue can be closed, I think we have a path forward here (and anyone else who's using CSI RBD, not sure about cephFS)

**Comment by travisn** [comment]
Great to hear it's working. Ideally we could add this to the Rook docs. However, it's not a common issue since most users have joined after 1.0 so we can refer to this issue instead of worrying about the docs.
