### ISSUE TITLE
Monitors still don't use letter consecutively

### ISSUE THREAD

**Issue by zerkms** [rook/rook#6373]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I think some time ago it was implemented that monitors were chosen letter consecutive indexes. While it looks like it does not really work.

This morning I had a little outage and out of 3 monitors: `mon-a`, `mon-b`, `mon-e` - the latter `mon-e` was unavailable. So after 10 minutes deadline `mon-f` was created. So I now run in a cluster with `a`, `b`, `f`.

What happens when I run out of alphabet?

**Expected behavior:**
I think letters should be assigned consecutively, if possible. In the case above it should be possible.

**How to reproduce it (minimal and precise):**

Make a monitor unavailable several times, and wait while it fails-over.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.3.5`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)`
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@zerkms When the single-letter alphabet is exhausted, a double-letter name will be used, then triple-letter, etc. The only time the letters increase is when there is a mon failover. What do you see is not working? Rook can't use the same mon name after a failover.

**Comment by zerkms** [comment]
@travisn I think I seen it in some other issue report several years ago: that in the deployment `a`, `b`, `e`, on failover `c` would be used, as it's available now. Or am I confusing it with something else?

**Comment by travisn** [comment]
@zerkms Rook has always added the next mon in alphabetical increasing order. There was a bug a few months back that caused rook to get confused about the index of the mon last used, but that was fixed.

**Comment by zerkms** [comment]
Okay, so if exhausting is not causing any troubles - I don't mind. Thanks! :-)
