### ISSUE TITLE
Support all the rook secrets to be stored in Vault

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#6374]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
There're 30+ secrets created by rook-ceph deploy in general. And some are the very sensitive information( password, admin-id/, adminkey, certificate). And the k8s secrets can be easily accessed/attacked as a week encryption algorithm is used. Need to enhance the security level by using Vault or similar methods. 

The sensitive information stored in secret can be retrieved easily by users. 
```
# knc get secret
NAME                                         TYPE                                  DATA   AGE
default-token-klbq8                          kubernetes.io/service-account-token   3      24h
rgw-cert                                     kubernetes.io/tls                     3      24h
rook-ceph-admin-keyring                      kubernetes.io/rook                    1      24h
rook-ceph-admission-controller-token-2jwht   kubernetes.io/service-account-token   3      24h
rook-ceph-cmd-reporter-token-tjz8h           kubernetes.io/service-account-token   3      24h
rook-ceph-config                             kubernetes.io/rook                    2      24h
rook-ceph-crash-collector-keyring            kubernetes.io/rook                    1      24h
rook-ceph-dashboard-password                 kubernetes.io/rook                    1      24h
rook-ceph-mds-myfs-a-keyring                 kubernetes.io/rook                    1      24h
rook-ceph-mds-myfs-b-keyring                 kubernetes.io/rook                    1      24h
rook-ceph-mgr-a-keyring                      kubernetes.io/rook                    1      24h
rook-ceph-mgr-token-89p5k                    kubernetes.io/service-account-token   3      24h
rook-ceph-mon                                kubernetes.io/rook                    4      24h
rook-ceph-mons-keyring                       kubernetes.io/rook                    1      24h
rook-ceph-oam-cert-token-qr859               kubernetes.io/service-account-token   3      24h
rook-ceph-osd-0-keyring                      kubernetes.io/rook                    1      24h
rook-ceph-osd-1-keyring                      kubernetes.io/rook                    1      24h
rook-ceph-osd-2-keyring                      kubernetes.io/rook                    1      24h
rook-ceph-osd-token-8j8p2                    kubernetes.io/service-account-token   3      24h
rook-ceph-rgw-cert                           Opaque                                1      24h
rook-ceph-rgw-rook-ceph-store-a-keyring      kubernetes.io/rook                    1      24h
rook-ceph-system-token-nhvhl                 kubernetes.io/service-account-token   3      24h
rook-csi-cephfs-node                         kubernetes.io/rook                    2      24h
rook-csi-cephfs-plugin-sa-token-kjzdz        kubernetes.io/service-account-token   3      24h
rook-csi-cephfs-provisioner                  kubernetes.io/rook                    2      24h
rook-csi-cephfs-provisioner-sa-token-l8hlf   kubernetes.io/service-account-token   3      24h
rook-csi-rbd-node                            kubernetes.io/rook                    2      24h
rook-csi-rbd-plugin-sa-token-4rvts           kubernetes.io/service-account-token   3      24h
rook-csi-rbd-provisioner                     kubernetes.io/rook                    2      24h
rook-csi-rbd-provisioner-sa-token-g4gbw      kubernetes.io/service-account-token   3      24h
```

**What is use case behind this feature:**
This is an extenstion of #6105 

**Environment**:

**Comment by yanchicago** [comment]
Vault integration is planned for v1.5, scratch my previous comment.

_Originally posted by @travisn in https://github.com/rook/rook/issues/6105#issuecomment-702857257_

**Comment by yanchicago** [comment]
> Vault integration is planned for v1.5, scratch my previous comment.
> 
> _Originally posted by @travisn in [#6105 (comment)](https://github.com/rook/rook/issues/6105#issuecomment-702857257)_

@travisn Any design or similar exists?

**Comment by leseb** [comment]
> > Vault integration is planned for v1.5, scratch my previous comment.
> > _Originally posted by @travisn in [#6105 (comment)](https://github.com/rook/rook/issues/6105#issuecomment-702857257)_
> 
> @travisn Any design or similar exists?

I'll soon open a PR which will serve as a foundation for supporting your use case.

**Comment by yanchicago** [comment]
@leseb Do you have update on this feature?

**Comment by leseb** [comment]
> @leseb Do you have update on this feature?

The PR is here: https://github.com/rook/rook/pull/6474.

**Comment by yanchicago** [comment]
@leseb #6476 ( related to OSD encription ) has different scope. This ticket is for store the rook secrets in Vault, i.e, user/passwd.

**Comment by leseb** [comment]
> @leseb #6476 ( related to OSD encription ) has different scope. This ticket is for storing the rook secrets in Vault, i.e, user/passwd.

Yes, but it will serve as a foundation for further improvements.
So once it merges you can start working on a broader implementation if you want.

**Comment by yanchicago** [comment]
Please keep it open.

**Comment by nasirudheen** [comment]
Any update on this issue ? Is there any plan to implement this feature ?

Thanks !

**Comment by sp98** [comment]
> Any update on this issue ? Is there any plan to implement this feature ?
> 
> Thanks !

Hi. I've started looking into it. Will update more about the progress.

**Comment by BlaineEXE** [comment]
I think using the vault agent injector would be one of the simplest ways for us to implement this feature. https://www.vaultproject.io/docs/platform/k8s/injector

From the Rook operator side, when we create/update a Secret, instead of creating/updating the secret, we would instead create/update the key in Vault (via Go API) from the operator, and then we would add labels onto the pod such that the vault agent injector will mount that secret into the pod.

We would only need the init container for our uses from what I can tell because we don't expect secrets to be updated at runtime.

**Comment by nasirudheen** [comment]
@BlaineEXE
+1
Running `init container` would be the easiest. And most of the solutions available for Vault integration already make use of init container/side car + labels/annotations.

**Comment by sp98** [comment]
@BlaineEXE @nasirudheen This got delayed as I was looking into some other tasks. I'll work on this in the coming weeks. 
Thanks for suggesting the vault agent approach for injecting secrets into pods. 
Any thoughts on [external secrets](https://external-secrets.io/v0.6.0-rc1/)?

**Comment by nasirudheen** [comment]
@sp98 
I think `ExternalSecrets` is not what we are looking for. Because `ExternalSecrets` will fetch the credentials from Vault(or other supported KMS) backend and create the corresponding secrets in Kubernetes cluster, in the usual `Base64` encoded format. What we need is some solution like init container or/and side car that will fetch the sensitive data from the Vault and make it available for the Pod at run time, _only for that pod_. `ExternalSecrets` will not eliminate the need for Base64 encoded secrets that are insecure _per se_, it just help you to avoid having the `Base64` encoded secrets stored in the Git repos when following GitOps.

**Comment by davidturner-sie** [comment]
As my company has been evaluating both Rook and CephADM for use with Ceph we've been blocked in both cases by security decisions made with them. CephADM requires passwordless sudo on commands that would easily compromise the the servers. Rook requires the Ceph admin keyring to be stored non-encrypted.

For other Ceph projects we use vault init containers to load them from vault before loading the Ceph container to run our application. Any solution that grabs the secure information from Vault and then stores it in Kubernetes secrets bypasses the reason for using Vault in the first place.

I've found that using a vault init container with an emtpydir volume and the init container generates a script that will create environment variables when run. That way you can get the secrets from vault store them temporarily, and load them in the actual daemon container.

I think we could get there pretty easily if we add a few things in values.yaml. This architecture in values.yaml and have the deployment chart take them into account.

**Comment by richardelling** [comment]
Kubernetes can encrypt secrets at rest. This is transparent to secret consumers, such as rook. Given that vault is moving away from being open source, you should consider CNCF-like projects which will remain open source.
