### ISSUE TITLE
Operatorhub does not have latest version of rook-ceph

### ISSUE THREAD

**Issue by ibotty** [rook/rook#6378]
On Operatorhub there is only rook 1.1.1.  It would be great to have the latest rook-ceph.

**Comment by leseb** [comment]
@ibotty are you consuming Rook from the operatorhub? Thanks

**Comment by ibotty** [comment]
No, I am not.  But I would be glad if it were possible.

**Comment by xiaods** [comment]
this is not a bug, please use the rook chart repository
```
## For Helm v3.x
helm install --namespace rook-ceph rook-ceph rook-release/rook-ceph
```
I search and read the rook docs. 
https://rook.io/docs/rook/v1.4/helm-operator.html

it contains many more outdated docs.
