### ISSUE TITLE
RPCSEC_GSS support for RookNFS / Ganesha

### ISSUE THREAD

**Issue by stv0g** [rook/rook#6394]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Support RPCSEC_GSS for RookNFS resources / clustererd Ganesha servers

See: https://github.com/nfs-ganesha/nfs-ganesha/wiki/RPCSEC_GSS

**What is use case behind this feature:**

Allow encrypted and authenticated connections to the Ganesha NFS server.

Possibly a way to extend ganesha.conf would already be helpful.
But right now, I dont have an idea how to extend the ganesha.conf file as the underlying ConfigMap would be overwritten by the reconciliation of Rooks ceph-operator?

**Comment by briantopping** [comment]
I'd still like to see this. It might be good to keep it active so someone with experience could find it.
