### ISSUE TITLE
Refreshing etcd clients when etcd membership changes

### ISSUE THREAD

**Issue by mazarmi** [rook/rook#64]
Each Castled server creates an instance of en etcd client and passes it to other parts of the code as a part of clusterd context. Since clusterd supports dynamic resizing of etcd cluster, the original etcd client could get outdated. This problem would lead to timeout and failure of castled. 
The fix should update the etcd client in the context when a change occurs in the etcd membership.

**Comment by travisn** [comment]
Closing all tickets related to standalone. See #985.
