### ISSUE TITLE
Air-Gapped/Offline installation require much effort currently

### ISSUE THREAD

**Issue by Moep90** [rook/rook#6406]
# Feature Request
I'm currently confronted with a project, where we dont have a network connection to the outer world.
Therefore we need to do a Air-Gapped (offline) installation of rook-ceph.

I currently dont know how to track down all images are used by rook-images per version.
All I can do is to go on an existing cluster and execute the following command:
```bash
$ kubectl get pods -n rook-ceph -o jsonpath="{..image}" |tr -s '[[:space:]]' '\n' |sort |uniq -c
    106 ceph/ceph:v14.2.9
     48 quay.io/cephcsi/cephcsi:v2.1.2
      8 quay.io/k8scsi/csi-attacher:v2.1.0
     16 quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
      8 quay.io/k8scsi/csi-provisioner:v1.4.0
      8 quay.io/k8scsi/csi-resizer:v0.4.0
      4 quay.io/k8scsi/csi-snapshotter:v1.2.2
     20 rook/ceph:v1.3.11
```

## What should the feature do:
Please release an ImageList for all your Versions.
rancher for example does that by:
https://github.com/rancher/kontainer-driver-metadata/blob/master/rke/k8s_rke_system_images.go
https://github.com/rancher/rancher/releases/download/v2.5.1/rancher-images.txt
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/

## What is use case behind this feature:
We're likely do execute an airgapped installation, but dont want to have a fully installed cluster to check which version of which image is required.

## Environment:
Offline.

**Comment by travisn** [comment]
Rook allows different versions of Ceph and the CSI driver to be deployed with a given version of Rook, but it is certainly reasonable to publish the list of default images.

**Comment by leseb** [comment]
```bash
$ awk '/image:/ {print $2}' cluster/examples/kubernetes/ceph/operator.yaml cluster/examples/kubernetes/ceph/cluster.yaml | tee -a rook-ceph-image.txt && awk '/quay.io/ || /k8s.gcr.io/ {print $3}' cluster/examples/kubernetes/ceph/operator.yaml | tr -d '"' | tee -a rook-ceph-image.txt                                                          
rook/ceph:master
ceph/ceph:v15.2.4
quay.io/cephcsi/cephcsi:v3.1.1
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
k8s.gcr.io/sig-storage/csi-resizer:v1.0.0
k8s.gcr.io/sig-storage/csi-provisioner:v2.0.0
k8s.gcr.io/sig-storage/csi-snapshotter:v3.0
```

We can start doing this as part of the release process and upload the file.

**Comment by xiaods** [comment]
> ```shell
> $ awk '/image:/ {print $2}' cluster/examples/kubernetes/ceph/operator.yaml cluster/examples/kubernetes/ceph/cluster.yaml | tee -a rook-ceph-image.txt && awk '/quay.io/ || /k8s.gcr.io/ {print $3}' cluster/examples/kubernetes/ceph/operator.yaml | tr -d '"' | tee -a rook-ceph-image.txt                                                          
> rook/ceph:master
> ceph/ceph:v15.2.4
> quay.io/cephcsi/cephcsi:v3.1.1
> k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
> k8s.gcr.io/sig-storage/csi-resizer:v1.0.0
> k8s.gcr.io/sig-storage/csi-provisioner:v2.0.0
> k8s.gcr.io/sig-storage/csi-snapshotter:v3.0
> ```
> 
> We can start doing this as part of the release process and upload the file.

the image list should be input in which file.  I can contribute it.

**Comment by leseb** [comment]
> > ```shell
> > $ awk '/image:/ {print $2}' cluster/examples/kubernetes/ceph/operator.yaml cluster/examples/kubernetes/ceph/cluster.yaml | tee -a rook-ceph-image.txt && awk '/quay.io/ || /k8s.gcr.io/ {print $3}' cluster/examples/kubernetes/ceph/operator.yaml | tr -d '"' | tee -a rook-ceph-image.txt                                                          
> > rook/ceph:master
> > ceph/ceph:v15.2.4
> > quay.io/cephcsi/cephcsi:v3.1.1
> > k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
> > k8s.gcr.io/sig-storage/csi-resizer:v1.0.0
> > k8s.gcr.io/sig-storage/csi-provisioner:v2.0.0
> > k8s.gcr.io/sig-storage/csi-snapshotter:v3.0
> > ```
> > 
> > 
> > We can start doing this as part of the release process and upload the file.
> 
> the image list should be input in which file. I can contribute it.

There is no file. A maintainer just needs to add it in the release.

**Comment by xiaods** [comment]
just need to add the above script to build steps.

**Comment by KlavsKlavsen** [comment]
What I do - is just to use ```helm template rook/rook --values myvalues.yaml | grep image```
That renders the complete yamls and shows the images used.. 
For offline usage - I then override each of these image values with my own (in my values file) - and point them to my local Helm repo in artifactory. That works great.

**Comment by willzhang** [comment]
> 我所做的 - 只是使用`helm template rook/rook --values myvalues.yaml | grep image`
> 它呈现完整的 yaml 并显示使用的图像..
> 对于离线使用 - 然后我用我自己的（在我的值文件中）覆盖这些图像值中的每一个 - 并将它们指向我的本地 Helm 存储库在人工制品。这很好用。

but helm just install rook operator, not install ceph cluster

**Comment by willzhang** [comment]
in china , we can't pull k8s.gcr.io , for chinese install rook More difficult!

```
[root@k8s-master1 ceph]# kubectl -n rook-ceph get pods
NAME                                                    READY   STATUS             RESTARTS   AGE
csi-cephfsplugin-84c7r                                  2/3     ImagePullBackOff   0          46m
csi-cephfsplugin-hskpv                                  2/3     ImagePullBackOff   0          46m
csi-cephfsplugin-hzj8p                                  2/3     ImagePullBackOff   0          46m
csi-cephfsplugin-provisioner-78d66674d8-mjtj5           2/6     ImagePullBackOff   0          46m
csi-cephfsplugin-provisioner-78d66674d8-qctjg           2/6     ImagePullBackOff   0          46m
csi-cephfsplugin-xmwdn                                  2/3     ImagePullBackOff   0          46m
csi-cephfsplugin-xvvdq                                  2/3     ImagePullBackOff   0          46m
csi-rbdplugin-5frd6                                     2/3     ImagePullBackOff   0          52m
csi-rbdplugin-fqh4l                                     2/3     ErrImagePull       0          52m
csi-rbdplugin-msslt                                     2/3     ImagePullBackOff   0          52m
csi-rbdplugin-ph4x4                                     2/3     ImagePullBackOff   0          52m
csi-rbdplugin-provisioner-687cf777ff-kkt82              2/6     ImagePullBackOff   0          52m
csi-rbdplugin-provisioner-687cf777ff-vv75g              2/6     ImagePullBackOff   0          52m
csi-rbdplugin-zvfcn                                     2/3     ImagePullBackOff   0          52m
rook-ceph-crashcollector-k8s-master1-6d5c845487-bhdnd   1/1     Running            0          82m
rook-ceph-crashcollector-k8s-master2-b7dc454db-cgfgt    1/1     Running            0          65m
rook-ceph-crashcollector-k8s-master3-85f6964c85-thm6f   1/1     Running            0          58m
rook-ceph-crashcollector-k8s-node1-7767f644fc-fskww     1/1     Running            0          82m
rook-ceph-crashcollector-k8s-node2-6c4756456d-6c55d     1/1     Running            0          82m
rook-ceph-mgr-a-5bbc46967b-9rrgh                        1/1     Running            0          83m
rook-ceph-mon-a-d4f9557cd-fnknw                         1/1     Running            0          89m
rook-ceph-mon-b-689dfdc6c9-cvkdr                        1/1     Running            0          88m
rook-ceph-mon-c-6d76d7d587-z8gwx                        1/1     Running            0          85m
rook-ceph-operator-bd65c695f-wfcfb                      1/1     Running            0          16h
rook-ceph-osd-0-6545496748-hzwnc                        1/1     Running            0          82m
rook-ceph-osd-1-75757b58bf-bpj9k                        1/1     Running            0          73m
rook-ceph-osd-2-598d87696-mgk69                         1/1     Running            0          66m
rook-ceph-osd-3-7d545ff8f-wkhgk                         1/1     Running            0          65m
rook-ceph-osd-4-7d6b8f45f6-vn6qg                        1/1     Running            0          58m
rook-ceph-osd-prepare-k8s-master1-lshqv                 0/1     Completed          0          58m
rook-ceph-osd-prepare-k8s-master2-dbhzl                 0/1     Completed          0          58m
rook-ceph-osd-prepare-k8s-master3-59s24                 0/1     Completed          0          58m
rook-ceph-osd-prepare-k8s-node1-c8nst                   0/1     Completed          0          58m
rook-ceph-osd-prepare-k8s-node2-hmcb2                   0/1     Completed          0          58m
[root@k8s-master1 ceph]#

```

pull error
```

Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  46m                   default-scheduler  Successfully assigned rook-ceph/csi-cephfsplugin-84c7r to k8s-node2
  Normal   Pulled     46m                   kubelet            Container image "quay.io/cephcsi/cephcsi:v3.3.1" already present on machine
  Normal   Created    46m                   kubelet            Created container liveness-prometheus
  Normal   Pulled     46m                   kubelet            Container image "quay.io/cephcsi/cephcsi:v3.3.1" already present on machine
  Normal   Created    46m                   kubelet            Created container csi-cephfsplugin
  Normal   Started    46m                   kubelet            Started container csi-cephfsplugin
  Normal   Started    46m                   kubelet            Started container liveness-prometheus
  Normal   Pulling    45m (x3 over 46m)     kubelet            Pulling image "k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0"
  Warning  Failed     44m (x3 over 46m)     kubelet            Failed to pull image "k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   BackOff    16m (x115 over 46m)   kubelet            Back-off pulling image "k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0"
  Warning  Failed     6m42s (x12 over 46m)  kubelet            Error: ErrImagePull
  Warning  Failed     110s (x179 over 46m)  kubelet            Error: ImagePullBackOff
[root@k8s-master1 ceph]#
```

1.6.6 images
```
[root@k8s-master1 rook-1.6.6]# awk '/image:/ {print $2}' cluster/examples/kubernetes/ceph/operator.yaml cluster/examples/kubernetes/ceph/cluster.yaml | tee -a rook-ceph-image.txt && awk '/quay.io/ || /k8s.gcr.io/ {print $3}' cluster/examples/kubernetes/ceph/operator.yaml | tr -d '"' | tee -a rook-ceph-image.txt
rook/ceph:v1.6.6
ceph/ceph:v15.2.13
quay.io/cephcsi/cephcsi:v3.3.1
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
quay.io/csiaddons/volumereplication-operator:v0.1.0
[root@k8s-master1 rook-1.6.6]#

```

**Comment by subhamkrai** [comment]
@willzhang since rook 1.6.5 we have an experimental feature for helm Ceph Cluster too. https://github.com/rook/rook/releases/tag/v1.6.5

**Comment by Madhu-1** [comment]
> in china , we can't pull k8s.gcr.io , for chinese install rook More difficult!
> 
> [root@k8s-master1 rook-1.6.6]# awk '/image:/ {print $2}' cluster/examples/kubernetes/ceph/operator.yaml cluster/examples/kubernetes/ceph/cluster.yaml | tee -a rook-ceph-image.txt && awk '/quay.io/ || /k8s.gcr.io/ {print $3}' cluster/examples/kubernetes/ceph/operator.yaml | tr -d '"' | tee -a rook-ceph-image.txt
> rook/ceph:v1.6.6
> ceph/ceph:v15.2.13
> quay.io/cephcsi/cephcsi:v3.3.1
> k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
> k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
> k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
> k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
> k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
> quay.io/csiaddons/volumereplication-operator:v0.1.0

@willzhang images in `k8s.gcr.io` are not maintained by the Rook team, these are maintained by https://github.com/kubernetes-csi team. You may need to check with the kubernetes CSI team to provide an alternative to use these images?

**Comment by willzhang** [comment]
i can find k8s.gcr.io/sig-storage/xxx  image in values.yaml，values.yml variable should map to template/xx.yml，but why this image can not found in template files.

```
[root@master charts]# pwd
/data/git/rook-master/cluster/charts
[root@master charts]# 
[root@master charts]# 
[root@master charts]# grep -rn image:
rook-ceph-cluster/templates/deployment.yaml:25:          image: {{ .Values.toolbox.image }}
rook-ceph-cluster/values.yaml:23:  image: rook/ceph:VERSION
rook-ceph-cluster/values.yaml:43:    image: ceph/ceph:v16.2.4
rook-ceph/templates/deployment.yaml:26:        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
rook-ceph/templates/resources.yaml:306:                          image:
rook-ceph/templates/resources.yaml:497:                    image:
rook-ceph/templates/resources.yaml:3746:                    image:
rook-ceph/templates/resources.yaml:9129:                image:
rook-ceph/values.yaml:5:image:
rook-ceph/values.yaml:273:    #image: quay.io/cephcsi/cephcsi:v3.3.1
rook-ceph/values.yaml:275:    #image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
rook-ceph/values.yaml:277:    #image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
rook-ceph/values.yaml:279:    #image: k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
rook-ceph/values.yaml:281:    #image: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
rook-ceph/values.yaml:283:    #image: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
rook-ceph/values.yaml:291:    #image: "quay.io/csiaddons/volumereplication-operator:v0.1.0"
[root@master charts]# 
```

what i want is pull k8s.gcr.io/xx to my private registry then run follow command , i don't want to edit yaml file by hand
```
helm install --namespace rook-ceph rook-ceph 
  --registry=  my-privite-registry \
  rook-release/rook-ceph
```

**Comment by Madhu-1** [comment]
these images https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/values.yaml#L272-L283  will be added as an ENV variables in Rook deployment https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/deployment.yaml#L153-L180. you can specify these images as you specify other options and documentation is available at https://github.com/rook/rook/blob/master/Documentation/helm-operator.md#configuration

**Comment by willzhang** [comment]
> these images https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/values.yaml#L272-L283 will be added as an ENV variables in Rook deployment https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph/templates/deployment.yaml#L153-L180. you can specify these images as you specify other options and documentation is available at https://github.com/rook/rook/blob/master/Documentation/helm-operator.md#configuration

greate，thanks, I didn't see it before
```
helm install rook-ceph \
  --version v1.6.7 \
  --namespace rook-ceph \
  --create-namespace \
  --set csi.pluginTolerations[0].key="node-role.kubernetes.io/master" \
  --set csi.pluginTolerations[0].operator=Exists \
  --set csi.pluginTolerations[0].effect=NoSchedule \
  --set csi.registrar.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-node-driver-registrar:v2.2.0 \
  --set csi.provisioner.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-provisioner:v2.2.2 \
  --set csi.snapshotter.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-snapshotter:v4.1.1 \
  --set csi.attacher.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-attacher:v3.2.1 \
  --set csi.resizer.image=registry.cn-shenzhen.aliyuncs.com/images_mirror/csi-resizer:v1.2.0 \
  rook-release/rook-ceph
```

```
helm install rook-ceph-cluster \
  --namespace rook-ceph \
  --create-namespace \
  --set operatorNamespace=rook-ceph \
  rook-master/rook-ceph-cluster
```

**Comment by danielburrell** [comment]
Hi we really need this too, normally we use `kbld` and produce a lockfile to automatically discover the images from a helm chart, but your image references are not in standard locations - they're in custom resources.
This makes it very difficult to manually curate and maintain a list of images. 
A simple list of images published with the release would be really beneficial for us.

**Comment by travisn** [comment]
@subhamkrai How about if we run [this command](https://github.com/rook/rook/issues/6406#issuecomment-707713095) as part of the tagged action? Then we can include the list of images in the release notes.

**Comment by danielburrell** [comment]
Would it be machine readable? (An artefact attached to the release, not just free text in the release description). Forgot to mention that caveat.

**Comment by travisn** [comment]
Right, as an artifact attached to the release. How about a simple text file with one image per line? Or is there a more specific format that would help?

**Comment by danielburrell** [comment]
That would be ideal. Plain text list of fully qualified image reference formatted strings e.g `quay.io/group/project:tag` 

Then anyone can take each of those reference strings and do what they need e.g `docker image save xxxxxxxx`
