### ISSUE TITLE
Logs from the operator spews pollEvent failure repeatedly 

### ISSUE THREAD

**Issue by kokhang** [rook/rook#641]
Deployed Rook on Minikube, created the mysql app (along with its pvc) and then deleted. Everything was successful. However, when i look at the operator's log, i see pollEvent failures flooding the logs. Here is the first part of the log before the flood happens.
https://gist.github.com/kokhang/805ea9a0b29342388db83228855c96f0

**Comment by kokhang** [comment]
The operation seems to be operational since i was able to create the mysql pvc again. Or at least the Volume provisioner is working.

**Comment by travisn** [comment]
the pool tpr watcher was not properly recovering from the case where the watch index is out of date and needs to be refreshed. This is a simple change to tell the operator to refresh the cache.
