### ISSUE TITLE
ceph-examples.md templating broken

### ISSUE THREAD

**Issue by tillhoff** [rook/rook#6411]
* Bug Report

**Deviation from expected behavior:**
Broken templating in documentation

**Expected behavior:**
Proper templating in documentation

**How to reproduce it (minimal and precise):**
Go to https://github.com/rook/rook/blob/master/Documentation/ceph-examples.md; there are several curly-braces which shouldn't be there.

**Comment by galexrt** [comment]
If you mean this part with the curly braces that is expected, the doc template engine interprets this accordingly, e.g., see https://rook.io/docs/rook/v1.4/ceph-examples.html

![image](https://user-images.githubusercontent.com/3718398/95508662-a495aa80-09b3-11eb-84d1-6426cfd665ad.png)

**Comment by tillhoff** [comment]
Ah, I see.
