### ISSUE TITLE
mon pod can't trigger failover when it's host/server fails in rook 1.4.5

### ISSUE THREAD

**Issue by huqiangjz** [rook/rook#6413]
**Is this a bug report or feature request?**
* Bug Report
mon pod can't trigger failover when it's host fails. therefore  the whole ceph cluster is stuck .(rook version 1.4.5)

**Deviation from expected behavior:**
the ceph cluster  is stuck. 
**Expected behavior:**
the mon pod will restart in another host , and the ceph cluster  is still working. 
**How to reproduce it (minimal and precise):**

1. gets the hosts(k8s-ceph-node1 and k8s-ceph-node2) which contain rook-ceph-mon-a/b via cmd "kubectl -n rook-ceph get pod -o wide"

rook-ceph-mon-a-9c459858f-z5p2d                             1/1     Running     0          17h   192.168.202.32    k8s-ceph-node2    <none>           <none>
rook-ceph-mon-b-7bb878c798-wzp6z                            1/1     Running     0          17h   192.168.149.31    k8s-ceph-node1    <none>           <none>

2. shut down the host of k8s-ceph-node1(or k8s-ceph-node2) 
3. the ceph cluster is stuck , no matter what command I use (ceph -s or ceph osd tree)

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
* Kernel (e.g. `uname -a`): Linux k8s-ceph-master 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod): 1.4.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.4
* Kubernetes version (use `kubectl version`): v1.17.3

**Comment by travisn** [comment]
@huqiangjz Three mons are required to handle the mon failover. Do you only have two mons? Rook should really prevent two mons. If there are two mons and one of them goes down, the quorum is lost since the quorum requires greater than half of the mons to be running.

**Comment by huqiangjz** [comment]
@travisn thank you for the reminding。now I use 3 mons, and the cluster is still alive after shuting down one host.
