### ISSUE TITLE
where do I change skipUpgradeChecks and continueUpgradeAfterChecksEvenIfNotHealthy in a provisioned cluster?

### ISSUE THREAD

**Issue by hezise** [rook/rook#6422]
I tried to find those flags but I couldn't.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by sp98** [comment]
In the cluster.yaml file. https://github.com/rook/rook/blob/e229a4f12e0ec5d5e3f09e204ade451ad7d3a065/cluster/examples/kubernetes/ceph/cluster.yaml#L37-L40

**Comment by leseb** [comment]
Closing as per https://github.com/rook/rook/issues/6422#issuecomment-706892634

**Comment by hezise** [comment]
so I need to change the parameters and redeploy it?

**Comment by leseb** [comment]
> so I need to change the parameters and redeploy it?

Just `kubectl -n rook-ceph edit cephcluster`, then change the value and the operator will do the rest.

**Comment by hezise** [comment]
thanks
