### ISSUE TITLE
go.mod error

### ISSUE THREAD

**Issue by umangachapagain** [rook/rook#6428]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
`go get github.com/rook/rook@v1.4.5` works but

`operator-sdk init` gives error while updating `go.mod`:

```
o: github.com/rook/rook@v1.4.5 requires
	k8s.io/kube-controller-manager@v0.0.0: reading k8s.io/kube-controller-manager/go.mod at revision v0.0.0: unknown revision v0.0.0

```

**Expected behavior:**
`operator-sdk init` shouldn't fail if `go get github.com/rook/rook@v1.4.5` doesn't fail.

**How to reproduce it (minimal and precise):**

`go get github.com/rook/rook@v1.4.5` (verify it works)
and, with rook as dependency in go.mod, run `operator-sdk init`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): **1.4.5**
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
* Operator SDK version: **v0.19.0**

**Comment by travisn** [comment]
@umangachapagain Interesting that you're just hitting this issue now, [that line](https://github.com/rook/rook/blob/master/go.mod#L42) has been there since the conversion to go modules seven months ago. It's later replaced [here](https://github.com/rook/rook/blob/master/go.mod#L68) with the correct version, but I don't recall why that was the pattern.

**Comment by umangachapagain** [comment]
> @umangachapagain Interesting that you're just hitting this issue now, [that line](https://github.com/rook/rook/blob/master/go.mod#L42) has been there since the conversion to go modules seven months ago. It's later replaced [here](https://github.com/rook/rook/blob/master/go.mod#L68) with the correct version, but I don't recall why that was the pattern.

Yeah, it worked 1 out of 10 tries. Weird.
if we are enforcing `v0.17.2` anyway, why not just `require` that version instead of `replace`?

**Comment by umangachapagain** [comment]
Just tried `go get` again and it worked, but `operator-sdk init` failed while trying to update `go.mod`.
Updated the bug description accordingly.

Raising an issue in Operator SDK as well too determine where the issue is.
