### ISSUE TITLE
Update the dashboard to work with ceph 15.2.x

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#6430]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The doc ( https://rook.io/docs/rook/v1.4/ceph-monitoring.html) refers to 3 dashboard pages. The existing 3 pages failed to display valid data with ceph 15.2.5. 
- ceph-cluster_rev11.json: 
Issue 1). "Status", "Cluster Capacity", "Used Capacity", "Available Capacity" failed with "Only queries that return single series/table is supported". 
Issue 2). "Average Monitor Latency" shows "N/A"

- ceph-osd_rev3.json
Issue 3). "Status", "Available" and "Utilization" failed with "Only queries that return single series/table is supported". 

- ceph-pools_rev3.json
Issue 4). "usage" shows "N/A"

**What is use case behind this feature:**
To integrates within prometheus/grafana. 

**Environment**:

**Comment by yanchicago** [comment]
Attach the pages. 

![ceph-osd](https://user-images.githubusercontent.com/36163095/95908390-a5875d00-0d62-11eb-9d02-afa6e5e54abe.png)
![ceph-cluster](https://user-images.githubusercontent.com/36163095/95908396-a61ff380-0d62-11eb-82dd-887117884024.png)
![ceph-pools](https://user-images.githubusercontent.com/36163095/95908398-a61ff380-0d62-11eb-9358-0812fe443c0a.png)

**Comment by galexrt** [comment]
The `Only queries that return single series/table is supported` can't really be fixed by the dashboard. There are multiple ways, one of them is to add a `relabelings` config to the ServiceMonitor and / or using a deduplication system such as Thanos, Cortex, etc. for Prometheus.

The Ceph Cluster dashboard has been updated https://grafana.com/grafana/dashboards/2842

The "Ceph - OSD" look good on my end with Thanos and that `relabelings` config.

I'll update the "Ceph - OSD" and "Ceph - Pools" dashboard over the next few days to hopefully be able to use the name of a pool for the variable instead of the id.

**Comment by yanchicago** [comment]
@galexrt Many thanks for your support. The new cluster dashboard(rev12) has below issues. 
1). "CLUSTER STATE" shows "0|0",  used to be  "HEALTH_OK"?
2).  Several fields seems showing the wrong number: "Cluster Capacity", "Used Capacity", "Number of Objects", "Available Capacity", "Monitors In Quorum", "Avg PGs", "Bytes Written" and "Bytes Read". "Read" or "Write" latency seems not correct.
3). The number in "red" ?
4). The panel: "Pool Bytes Recovered", "Pool Objects Recovered", "Objects Per Pool" lll showing "Duplicate" errors. 
![cluster_rev12](https://user-images.githubusercontent.com/36163095/96935128-1298a200-1489-11eb-87a8-e3d8cb3e4dbd.png)

**Comment by galexrt** [comment]
As I wrote the dashboard will not handle duplicate metric series, see my PR for a `relabelings` to only have one metrics series.

Which Grafana version are you on? I have imported the dashboard in two different Grafanas and they look as in my screenshots.

**Comment by yanchicago** [comment]
@galexrt Grafana version 6.6.2

**Comment by galexrt** [comment]
@yanchicago you need to have Grafana 7.2.0 please look at the pull request #6481 for that and also the ServiceMonitor.

**Comment by yanchicago** [comment]
Grafana 7.2.0 was released 9/23. The version I used was released 1/27. Any reason that it has to be on the exact latest release?

**Comment by yanchicago** [comment]
The revision14 doesn't work with Grafana 7.1.3 ( duplicate entries shown for some panels). Will have to wait to verify with Grafana 7.2 or later.
