### ISSUE TITLE
external cluster: failed to create crush rule

### ISSUE THREAD

**Issue by jouve** [rook/rook#6431]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I followed documentation from https://rook.io/docs/rook/v1.4/ceph-cluster-crd.html#external-cluster to create an external cluster.

I used both create-external-cluster-resources.sh & import-external-cluster.sh to generate secret.

rook fails when creating the pool with : `failed to create crush rule` (from [pool.go#L306](https://github.com/rook/rook/blob/4736ddcc877d4ebdb8fbda559408881bed6f30fd/pkg/daemon/ceph/client/pool.go#L306) )

on the machine running ceph, I see the following error :

```
Oct 13 21:40:52 xxx bash[2158366]: audit 2020-10-13T19:40:51.089052+0000 mon.xxx (mon.0) 2134 : audit [INF] from='client.? 192.168.23.141:0/1445394888' entity='client.healthchecker' cmd=[{"prefix": "osd crush rule create-replicated", "name": "replicapool", "root": "default", "type": "host", "format": "json"}]:  access denied
```

It looks like it's using `client.healthchecker` which I understand is mostly read-only.

I alteded `client.healchecker` to grant it the same caps as `client.admin` : `ceph auth caps client.healthchecker mds "allow *" mgr "allow *" mon "allow *" osd "allow *"` and it "fixed" the issue.

**Expected behavior:**

I think rook should use one of the other entities created by create-external-cluster-resources.sh.

**How to reproduce it (minimal and precise):**

* I created a single node ceph cluster using [cephadm](https://docs.ceph.com/en/latest/cephadm/)
* I created rook entities with create-external-cluster-resources.sh

* on k8s, I created an external cluster as documented on [rook.io](https://rook.io/docs/rook/v1.4/ceph-cluster-crd.html#external-cluster), yaml & import-external-cluster.sh

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary 

I used yaml files from `cluster/examples/kubernetes/ceph`

* Operator's logs, if necessary

```
2020-10-13 19:41:33.558745 E | ceph-block-pool-controller: failed to reconcile failed to create pool "replicapool".: failed to create pool "replicapool".: failed to create pool "replicapool": failed to create crush rule replicapool: exit status 13
```

* Crashing pod(s) logs, if necessary

**Environment**:
* OS (e.g. from /etc/os-release): centos 8 (ceph) & debian 10.6 (k8s)
* Kernel (e.g. `uname -a`): 4.18 (ceph) & 4.19 (k8s)
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.4.5
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.5
* Kubernetes version (use `kubectl version`): 1.19.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by leseb** [comment]
It is expected. The default generated client does not have enough permissions. The goal of the external mode is to **only** consume and not create/manage resources.

Just like you said, if you need more permissions you can always update the caps.
Closing since there is no bug.

**Comment by jouve** [comment]
@leseb , so why does it generates other entities besides client.healthchecker :
 ```
client.csi-cephfs-node
	key: xxx==
	caps: [mds] allow rw
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs *=*
client.csi-cephfs-provisioner
	key: xxx==
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs metadata=*
client.csi-rbd-node
	key: xxx==
	caps: [mon] profile rbd
	caps: [osd] profile rbd
client.csi-rbd-provisioner
	key: xxx==
	caps: [mgr] allow rw
	caps: [mon] profile rbd
	caps: [osd] profile rbd
```

**Comment by leseb** [comment]
It generates other entities for ceph-csi so that ceph-csi can authenticate to the cluster.
ceph-csi is used to provide persistent storage to container applications.

**Comment by jouve** [comment]
thanks !
