### ISSUE TITLE
monitoring: add metric for slow requests

### ISSUE THREAD

**Issue by jbw976** [rook/rook#644]
Consider porting this recent PR to ceph_exporter from https://github.com/digitalocean/ceph_exporter/pull/52

We should also think more about how best to stay in sync with ceph_exporter.

**Comment by kokhang** [comment]
I dont know much about how the ceph_exporter is consumed by Rook but is it something we can use as a library? ie added to glide and pin a version of it that works best for us?

**Comment by jbw976** [comment]
Fixed with #935
