### ISSUE TITLE
Disaster Recovery Without SSH to Nodes Not Working

### ISSUE THREAD

**Issue by tareqhs** [rook/rook#6442]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Can't restore a rook/ceph data to a different kubernetes cluster by following the guide because I can't SSH to the nodes in the new cluster.

**How to reproduce it (minimal and precise):**

I am trying to follow the disaster recovery guide for moving my rook/ceph 1.4.4 data to a new kubernetes cluster using standard kubernetes operations only, without ssh. Can't get it to work. Also the deployment `rook-ceph-tools` that is addressed in the guide does not exist in `rook-ceph` namespace.

https://github.com/rook/rook/blob/v1.4.4/Documentation/ceph-disaster-recovery.md#adopt-an-existing-rook-ceph-cluster-into-a-new-kubernetes-cluster

I'm doing the following:
*In the old cluster:*
1. Install rook/ceph with 3 mons and 3 OSDs. The OSDs are configured to use large PVCs that I provide myself (see yaml below).
1. Provision some RBD volumes then add files to them.
1. Take AWS snapshots of all the 6 volumes in rook-ceph namespace in the old cluster. (using velero)

*In the new cluster:*
1. Install rook/ceph with exactly the same setup.
1. Scale down the rook operator deployment and delete all other deployments (rook-ceph-mgr-a, .., rook-ceph-osd-0, ..)
1. Remove all the 6 PVCs (mons and osds) and replace with PVCs created from the AWS snapshots. (using velero)
1. Modify the secret `rook-ceph-mons-keyring`. Change the `keystring` value by overriding `[mon.]` section with the value in the corresponding secret in the old cluster. Also remove the section `[client.admin]`
1. Modify the secret `rook-ceph-mon`. Change `fsid` with the corresponding value in the old cluster.
1. Modify the configmap `rook-config-override`. Disable authentication as explained in the guide.
1. Scale up the rook operator and wait.

After a while, I see that the only pod that is up and running is `mon-a`  (no other mons, no OSDs, no mgr). The operator logs show that it is stuck an infinite loop and just print this line once every 20 seconds:
> 2020-10-15 19:01:49.957462 I | op-mon: mons running: [a]

Also once every 2-3 minutes it prints this line too:
> 2020-10-15 19:01:37.155224 E | ceph-block-pool-controller: failed to reconcile invalid pool CR "replicapool" spec: failed to get crush map: failed to get crush map. timed out
: exit status 1

The logs of the mon-a show thousands of lines like this
> debug 2020-10-15T19:08:22.121+0000 7f0c7dc76700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id

By the way, if I copy the configmap `rook-ceph-mon-endpoints` from the old cluster I do get 3 monds (a, b, c) running instead of just one, but still the loop in the operator is still there
> 2020-10-15 20:08:56.370771 I | op-mon: mons running: [b c a]

After A LOT of time I get this in the operator log and then the loop starts again.
> 2020-10-15 20:09:11.471190 E | ceph-cluster-controller: failed to reconcile. failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to start mon pods: failed to check mon quorum a: failed to wait for mon quorum: exceeded max retry count waiting for monitors to reach quorum

**Comment by travisn** [comment]
@tareqhs I believe the critical missing piece is preserving the mon endpoints, which are stored in the rook-ceph-mon-endpoints configmap and must correspond to the service endpoints that rook created for each mon. The operator is likely trying to connect to the wrong mon endpoints.

**Comment by tareqhs** [comment]
@travisn please notice the last part in the description. I did copy the endpoints configmap and this did not help. It only increased the number of mon pods to 3, still with same errors inside each of them.

**Comment by travisn** [comment]
@tareqhs What about the mon services? `kubectl -n rook-ceph get svc | grep rook-ceph-mon`. Those must have the same clusterIP when they are restored in the new cluster.

**Comment by tareqhs** [comment]
@travisn storing the cluster IP of mon services made it work! thanks a lot!
This means the guide can be simplified significantly for in-cluster disaster recovery - simply restore the mon/osd volumes, the secrets, and the clusterIPs of the mon services. All regular kubernetes resources without SSH or ceph commands.
