### ISSUE TITLE
add root ceph dashboard service type to helm chart values.yaml

### ISSUE THREAD

**Issue by willzhang** [rook/rook#6450]
add root ceph dashboard service type to helm chart values.yaml.
i want define nodeport type service.

**Comment by travisn** [comment]
None of the cluster CR settings are currently in the helm chart. We do have a design suggestion that will allow us to do more with helm charts in the future, see #6451. Closing this for now since we first need to get the cluster CR settings into a helm chart before considering this detail.

**Comment by willzhang** [comment]
> 当前没有任何特定的 CR 设置定位舵。因为我们确实有一个设计建议，可以让我们在未来使用舵图做更多的事情，请参阅#6451。暂时关闭它，在考虑细节之前，我们首先需要将夜景 CR 设置一个南极光。

can you reopen it?

**Comment by travisn** [comment]
Rook only creates the services that can be accessed within the cluster. There are so many other types of services, load balancers, etc, that Rook does not have those options in the CRs. Even though there is a helm chart now for the cluster CR, there is still not an option in the cluster CR for creating a nodeport service. This service will need to be created separately from Rook.

**Comment by willzhang** [comment]
20220313  can it support define nodeport service with dashboard ?

**Comment by BlaineEXE** [comment]
Which dashboard? If via the Ceph dashboard, no. If via the kubernetes dashboard, I think that may be possible
