### ISSUE TITLE
Rook-Ceph-Block: PVC gets resized, filesystem on it in POD does not get resized

### ISSUE THREAD

**Issue by pascal71** [rook/rook#6453]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In proza; I have created a PVC and a mariadb deployment/pod consuming the PVC.

E.g:

  PVC:
 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  labels:
    app: mariadb
    type: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Gi

```
The refered storageClass:

```
kubectl describe sc rook-ceph-block
Name:                  rook-ceph-block
IsDefaultClass:        No
Annotations:           storageclass.kubernetes.io/is-default-class=false
Provisioner:           rook-ceph.rbd.csi.ceph.com
Parameters:            clusterID=rook-ceph,csi.storage.k8s.io/controller-expand-secret-name=rook-csi-rbd-provisioner,csi.storage.k8s.io/controller-expand-secret-namespace=rook-ceph,csi.storage.k8s.io/fstype=ext4,csi.storage.k8s.io/node-stage-secret-name=rook-csi-rbd-node,csi.storage.k8s.io/node-stage-secret-namespace=rook-ceph,csi.storage.k8s.io/provisioner-secret-name=rook-csi-rbd-provisioner,csi.storage.k8s.io/provisioner-secret-namespace=rook-ceph,imageFeatures=layering,imageFormat=2,pool=replicapool
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

```
The MariaDB deployment yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy: {}
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:latest
        name: mariadb
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        volumeMounts:
        - name: mariadb-vol
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-vol
        persistentVolumeClaim:
          claimName: mariadb-pvc
```

K8S is 1.19.2
Rook-ceph is: 1.4.4 CEPH is: v15.2.4

Initial deploy all goes well. 
PV gets created of 2GiB, PVC is bound, mounted etc.

kubectl exec -it  mariadb-f4f99849f-tgj5q -- df -H /var/lib/mysql
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd4       2.1G  144M  1.9G   8% /var/lib/mysql

E.g. 2GiB as expected.

Now let's extend it;

## Patching the PVC storage size from 2 to 5Gi

kubectl patch pvc mariadb-pvc -p '{ "spec": { "resources": { "requests": { "storage": "5Gi"} } } } '

## Double check

It's 5GiB (forget about the age, I've copy-n-pasted it at a later time)

```
 kubectl describe pvc mariadb-pvc
Name:          mariadb-pvc
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Bound
Volume:        pvc-fcb1007a-d66e-4a37-9a9d-45da3f063b54
Labels:        app=mariadb
               type=db
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    mariadb-f4f99849f-tgj5q
Conditions:
  Type                      Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----                      ------  -----------------                 ------------------                ------  -------
  FileSystemResizePending   True    Mon, 01 Jan 0001 00:00:00 +0000   Sun, 18 Oct 2020 13:59:43 +0000           Waiting for user to (re-)start a pod to finish file system resize of volume on node.
Events:
  Type     Reason                    Age    From                                                                                                        Message
  ----     ------                    ----   ----                                                                                                        -------
  Normal   ExternalProvisioning      9m39s  persistentvolume-controller                                                                                 waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning              9m39s  rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-77459cc496-vx9kb_596fa6df-751d-4e78-a7af-ad59da13ab92  External provisioner is provisioning volume for claim "default/mariadb-pvc"
  Normal   ProvisioningSucceeded     9m38s  rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-77459cc496-vx9kb_596fa6df-751d-4e78-a7af-ad59da13ab92  Successfully provisioned volume pvc-fcb1007a-d66e-4a37-9a9d-45da3f063b54
  Warning  ExternalExpanding         1s     volume_expand                                                                                               Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                  1s     external-resizer rook-ceph.rbd.csi.ceph.com                                                                 External resizer is resizing volume pvc-fcb1007a-d66e-4a37-9a9d-45da3f063b54
  Normal   FileSystemResizeRequired  0s     external-resizer rook-ceph.rbd.csi.ceph.com                                                                 Require file system resize of volume on node

```

So; all is fine. Waiting for POD to finish is a little funny as this is 1.19.2 with the beta features gates openend
(as per documentation at kubernetios.io assumed)

A few blinks of an eye later:

```
kubectl describe pvc mariadb-pvc
Name:          mariadb-pvc
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Bound
Volume:        pvc-fcb1007a-d66e-4a37-9a9d-45da3f063b54
Labels:        app=mariadb
               type=db
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    mariadb-f4f99849f-tgj5q
Events:
  Type     Reason                      Age    From                                                                                                        Message
  ----     ------                      ----   ----                                                                                                        -------
  Normal   ExternalProvisioning        13m    persistentvolume-controller                                                                                 waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning                13m    rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-77459cc496-vx9kb_596fa6df-751d-4e78-a7af-ad59da13ab92  External provisioner is provisioning volume for claim "default/mariadb-pvc"
  Normal   ProvisioningSucceeded       13m    rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-77459cc496-vx9kb_596fa6df-751d-4e78-a7af-ad59da13ab92  Successfully provisioned volume pvc-fcb1007a-d66e-4a37-9a9d-45da3f063b54
  Warning  ExternalExpanding           3m34s  volume_expand                                                                                               Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                    3m34s  external-resizer rook-ceph.rbd.csi.ceph.com                                                                 External resizer is resizing volume pvc-fcb1007a-d66e-4a37-9a9d-45da3f063b54
  Normal   FileSystemResizeRequired    3m33s  external-resizer rook-ceph.rbd.csi.ceph.com                                                                 Require file system resize of volume on node
  Normal   FileSystemResizeSuccessful  2m22s  kubelet                                                                                                     MountVolume.NodeExpandVolume succeeded for volume "pvc-fcb1007a-d66e-4a37-9a9d-45da3f063b54"
```

Ergo; also that has been taken care for

kubectl get pvc mariadb-pvc
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
mariadb-pvc   Bound    pvc-fcb1007a-d66e-4a37-9a9d-45da3f063b54   5Gi        RWO            rook-ceph-block   27m

But -> 

 kubectl exec -it  mariadb-f4f99849f-tgj5q -- df -H /var/lib/mysql
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd4       2.1G  144M  1.9G   8% /var/lib/mysql

That's not what I expected. As per the docs ext3, ext4 (this one is ext4) and xfs should have been resized automagically.

**Expected behavior:**

The FS in the pod to be resized to 5G

 kubectl exec -it  mariadb-f4f99849f-tgj5q -- df -H /var/lib/mysql
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd4       5.1G  144M  1.9G   1% /var/lib/mysql

**How to reproduce it (minimal and precise):**

See above

**Environment**:
* OS (e.g. from /etc/os-release):

Ubuntu 18.04 on the worker nodes
Raspbian on the master node
* Kernel (e.g. `uname -a`):

Linux k8sc98n04 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:

KVM

* Rook version (use `rook version` inside of a Rook Pod):

Rook-ceph is: 1.4.4 CEPH is: v15.2.4
K8S is 1.19.2
* Storage backend version (e.g. for ceph do `ceph -v`):
v15.2.4
ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)

* Kubernetes version (use `kubectl version`):
1.19.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

[root@rook-ceph-tools-649c4dd574-db7t6 /]# ceph status
  cluster:
    id:     75901e80-81f5-49b8-ba90-a6cd62961bf8
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 7h)
    mgr: a(active, since 2h)
    mds: myfs:1 {0=myfs-a=up:active} 1 up:standby-replay
    osd: 6 osds: 6 up (since 13d), 6 in (since 13d)
    rgw: 1 daemon active (my.store.a)
 
  task status:
    scrub status:
        mds.myfs-a: idle
        mds.myfs-b: idle
 
  data:
    pools:   11 pools, 177 pgs
    objects: 9.89k objects, 16 GiB
    usage:   55 GiB used, 545 GiB / 600 GiB avail
    pgs:     177 active+clean
 
  io:
    client:   852 B/s rd, 5.7 KiB/s wr, 2 op/s rd, 0 op/s wr

**Comment by travisn** [comment]
@pascal71 Did you check if the secrets are set in the storage class as defined [here](https://rook.github.io/docs/rook/v1.4/ceph-csi-drivers.html#dynamically-expand-volume) to support resizing?

**Comment by travisn** [comment]
Actually I do see those now in the storage class above. @Madhu-1 Do you see what might be missing?

**Comment by Madhu-1** [comment]
If you are using 3.1.0 or 3.0.0 you may face this issue in kube 1.19 ,This should be fixed in cephcsi 3.1.1 can you please check https://github.com/ceph/ceph-csi/pull/1426

**Comment by pascal71** [comment]
Updated the operator.yaml; unsupported: true, ceph-csi:3.1.0 and th results is as expected, the FS in the POD gets extended.
Nice job! Thanks

**Comment by pascal71** [comment]
Updating the operator.yaml - 
  ROOK_CSI_ALLOW_UNSUPPORTED_VERSION: "true"
  ROOK_CSI_CEPH_IMAGE: "quay.io/cephcsi/cephcsi:v3.1.1"

Did the job. After this doing a new resize of the PVC resulted in the FS in the POD getting extended.

Can be closed.
