### ISSUE TITLE
Support static clusterIp for NFS service

### ISSUE THREAD

**Issue by tlvenn** [rook/rook#6454]
**Feature Request:**
Due to a[ know issue](https://github.com/kubernetes/minikube/issues/3417) with NFS and dns resolving, it is not currently possible to directly use the service name of a given nfs server to mount a volume. One [workaround](https://github.com/kubernetes/minikube/issues/3417#issuecomment-670005434) mentioned is to use a static IP when declaring the nfs service and then we can bypass the name resolution and use a known deterministic IP.

**What should the feature do:**
Add a property to the NFSServer CRD to set the service ClusterIP address.

**What is use case behind this feature:**
See above

**Comment by xiaods** [comment]
Due to a known issue with NFS and DNS resolving, it is not currently possible to directly use the service name of a given nfs server to mount a volume.
-----
it depends on your k8s environment. I don't think this is a parameter to add clusterIP

**Comment by tlvenn** [comment]
It should not really depends on the k8s env as discussed in the issue I linked, I believe this is broken in any scenario and at the same time you could want to have a static clusterIp for your nfs server regardless of this issue. If anything it adds flexibility and allow for some workarounds.

**Comment by xiaods** [comment]
@tlvenn if add ClusterIP to Service Object, it need a default value on it. how do that?
https://sourcegraph.com/github.com/rook/rook/-/blob/pkg/operator/nfs/spec.go#L52
