### ISSUE TITLE
cluster.yaml will not run when the network, provider: multus (set to Multus)

### ISSUE THREAD

**Issue by yoom2016** [rook/rook#6456]
** Bug Report.**
cluster.yaml will not run when the network,  provider: multus  (set to Multus)
It will not create pods or services

**Expected behavior:**
It should create pods with a second NIC (interface) for the Ceph cluster network.
It would create services, mon-xxx .....etc
Not sure if it ever work before

**How to reproduce it (minimal and precise):**

Use the provided info to reproduce it.   I attached the files with extension .txt,  just need to change it back to .yaml

**INFORMATION PROVIDE FOR REVIEW ** 

**BEFORE INSTALL MULTUS, NAD, WHEREABOUT, ROOK-CEPH**

**NAMESPACE       NAME                                            READY   STATUS      RESTARTS   AGE   IPn Oct 18 21:NODE1 2020        NOMINATED NODE   READINESS GATES**
`ingress-nginx   pod/ingress-nginx-admission-create-9drm5        0/1     Completed   0          47h   10.90.1.235   n2.auto.com   <none>           <none>`
`ingress-nginx   pod/ingress-nginx-admission-patch-cp46h         0/1     Completed   1          47h   10.90.1.104   n2.auto.com   <none>           <none>`
`ingress-nginx   pod/ingress-nginx-controller-59cf455c8f-b5kv9   1/1     Running     0          47h   10.90.2.27    n1.auto.com   <none>           <none>`
`ingress-nginx   pod/ingress-nginx-controller-59cf455c8f-xr6zf   1/1     Running     0          47h   10.90.1.33    n2.auto.com   <none>           <none>`
`kube-system     pod/cilium-4vmsj                                1/1     Running     38         17d   10.70.10.11   n1.auto.com   <none>           <none>`
`kube-system     pod/cilium-operator-df6dfbf9-4v4s4              1/1     Running     22         17d   10.70.10.11   n1.auto.com   <none>           <none>`
`kube-system     pod/cilium-operator-df6dfbf9-rf7zf              1/1     Running     25         17d   10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/cilium-qgrjc                                1/1     Running     25         17d   10.70.10.12   n2.auto.com   <none>           <none>`
`kube-system     pod/cilium-s4sh7                                1/1     Running     47         17d   10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/coredns-f9fd979d6-9859t                     1/1     Running     2          17d   10.90.0.72    m1.auto.com   <none>           <none>`
`kube-system     pod/coredns-f9fd979d6-wz5ts                     1/1     Running     2          17d   10.90.0.133   m1.auto.com   <none>           <none>`
`kube-system     pod/etcd-m1.auto.com                            1/1     Running     2          17d   10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/kube-apiserver-m1.auto.com                  1/1     Running     2          17d   10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/kube-controller-manager-m1.auto.com         1/1     Running     2          17d   10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/kube-proxy-85kr9                            1/1     Running     3          17d   10.70.10.11   n1.auto.com   <none>           <none>`
`kube-system     pod/kube-proxy-n4bhf                            1/1     Running     3          17d   10.70.10.12   n2.auto.com   <none>           <none>`
`kube-system     pod/kube-proxy-zz7zn                            1/1     Running     2          17d   10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/kube-scheduler-m1.auto.com                  1/1     Running     2          17d   10.70.10.10   m1.auto.com   <none>           <none>`

**NAMESPACE              NAME                                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE   SELECTOR**
`default                service/kubernetes                           ClusterIP      10.96.0.1       <none>        443/TCP                      17d   <none>`
`ingress-nginx          service/ingress-nginx-controller             LoadBalancer   10.104.117.4    10.70.50.1    80:30969/TCP,443:32602/TCP   47h   app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx`

`ingress-nginx          service/ingress-nginx-controller-admission   ClusterIP      10.98.241.68    <none>        443/TCP                      47h   app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx`

`kube-system            service/kube-dns                             ClusterIP      10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP       17d   k8s-app=kube-dns`

`kubernetes-dashboard   service/dashboard-metrics-scraper            ClusterIP      10.98.227.88    <none>        8000/TCP                     16d   k8s-app=dashboard-metrics-scraper`

`kubernetes-dashboard   service/kubernetes-dashboard                 LoadBalancer   10.99.161.154   10.70.50.3    443:30565/TCP                16d   k8s-app=kubernetes-dashboard`

#2
**/etc/cni/net.d/**
`Files in the folder before install`
ls
05-cilium.conf

`After install multus and whereabouts`
ls
`00-multus.conf  05-cilium.conf  multus.d  whereabouts.d`

#3
**kubectl logs -f kube-multus-ds-amd64-54229 -n kube-system | more**

`2020-10-19T01:44:09+0000 Generating Multus configuration file using files in /host/etc/cni/net.d...`
`2020-10-19T01:44:10+0000 Using /host/etc/cni/net.d/05-cilium.conf as a source to generate the Multus configuration`
`2020-10-19T01:44:10+0000 Config file created @ /host/etc/cni/net.d/00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "cniVersion": "0.3.1", "name": "cilium", "type": "cilium-cni", "enable-debug": false } ] }`
`2020-10-19T01:44:10+0000 Entering sleep (success)...`

#4
**kubectl logs -f whereabouts-5ccsl -n kube-system | more**
`Done configuring CNI.  Sleep=true`

#5
**kubectl logs -f rook-ceph-operator-6db6f67cd4-5gpms -n rook-ceph | more**
`2020-10-19 01:55:25.787663 I | rookcmd: starting Rook v1.4.5 with arguments '/usr/local/bin/rook ceph operator'

`2020-10-19 01:55:25.787711 I | rookcmd: flag values: --add_dir_header=false, --alsologtostderr=false, --csi-cephfs-plugin-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin.yaml, --csi-cephfs-provisioner-dep-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin
-provisioner-dep.yaml, --csi-cephfs-provisioner-sts-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner-sts.yaml, --csi-rbd-plugin-template-path=/etc/ceph-csi/rbd/csi-rbdplugin.yaml, --csi-rbd-provisioner-dep-template-path=/etc/ceph-csi/rbd/csi-rbd
plugin-provisioner-dep.yaml, --csi-rbd-provisioner-sts-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner-sts.yaml, --enable-discovery-daemon=true, --enable-flex-driver=false, --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-
flush-frequency=5s, --log-level=INFO, --log_backtrace_at=:0, --log_dir=, --log_file=, --log_file_max_size=1800, --logtostderr=true, --master=, --mon-healthcheck-interval=45s, --mon-out-timeout=10m0s, --operator-image=, --service-account=, --skip_headers=false,
 --skip_log_headers=false, --stderrthreshold=2, --v=0, --vmodule=`

`2020-10-19 01:55:25.787714 I | cephcmd: starting Rook-Ceph operator`
`2020-10-19 01:55:25.878041 I | cephcmd: base ceph version inside the rook operator image is "ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)"`
`2020-10-19 01:55:25.886445 I | op-discover: rook-discover daemonset started`
`2020-10-19 01:55:25.886456 I | operator: looking for secret "rook-ceph-admission-controller"`
`2020-10-19 01:55:25.887880 I | operator: secret "rook-ceph-admission-controller" not found. proceeding without the admission controller`
`2020-10-19 01:55:25.888440 I | operator: watching all namespaces for ceph cluster CRs`
`2020-10-19 01:55:25.888538 I | operator: setting up the controller-runtime manager`
`2020-10-19 01:55:25.889977 I | ceph-cluster-controller: ConfigMap "rook-ceph-operator-config" changes detected. Updating configurations`
`2020-10-19 01:55:26.541677 I | ceph-cluster-controller: successfully started`
`2020-10-19 01:55:26.541734 I | ceph-cluster-controller: enabling hotplug orchestration`
`2020-10-19 01:55:26.541746 I | ceph-crashcollector-controller: successfully started`
`2020-10-19 01:55:26.541796 I | ceph-block-pool-controller: successfully started`
`2020-10-19 01:55:26.541842 I | ceph-object-store-user-controller: successfully started`
`2020-10-19 01:55:26.541892 I | ceph-object-realm-controller: successfully started`
`2020-10-19 01:55:26.541932 I | ceph-object-zonegroup-controller: successfully started`
`2020-10-19 01:55:26.541969 I | ceph-object-zone-controller: successfully started`
`2020-10-19 01:55:26.542041 I | ceph-object-controller: successfully started`
`2020-10-19 01:55:26.542086 I | ceph-file-controller: successfully started`
`2020-10-19 01:55:26.542131 I | ceph-nfs-controller: successfully started`
`2020-10-19 01:55:26.542245 I | operator: starting the controller-runtime manager`

#6
**rook-ceph operator ERRORs logs after apply  kubectl create -f rook-ceph-cluster.yaml**

`1W1019 01:59:14.645553       6 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: watch of *v1.CephCluster ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: v1.CephC
luster.Spec: v1.ClusterSpec.Storage: v1.StorageScopeSpec.Config: ReadString: expects \" or n, but found [, error found in #10 byte of ...|{\"nodes\":[{\"devices\"|..., bigger context ...|pgradeChecks\":false,\"storage\":{\"config\":{\"nodes\":[{\"devices\":[{\
"name\":\"/dev/sdb\"}],\"name\":\"172.70.10|...") has prevented the request from succeeding`

`E1019 01:59:15.647563       6 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.CephCluster: v1.CephClusterList.Items: []v1.CephCluster: v1.CephCluster.Spec: v1.ClusterSpec.Storage: v1.StorageScopeSpec.Config:
ReadString: expects " or n, but found [, error found in #10 byte of ...|{"nodes":[{"devices"|..., bigger context ...|pgradeChecks":false,"storage":{"config":{"nodes":[{"devices":[{"name":"/dev/sdb"}],"name":"172.70.10|...`

`E1019 01:59:16.649362       6 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.CephCluster: v1.CephClusterList.Items: []v1.CephCluster: v1.CephCluster.Spec: v1.ClusterSpec.Storage: v1.StorageScopeSpec.Config:
ReadString: expects " or n, but found [, error found in #10 byte of ...|{"nodes":[{"devices"|..., bigger context ...|pgradeChecks":false,"storage":{"config":{"nodes":[{"devices":[{"name":"/dev/sdb"}],"name":"172.70.10|...`

`E1019 01:59:17.651081       6 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.CephCluster: v1.CephClusterList.Items: []v1.CephCluster: v1.CephCluster.Spec: v1.ClusterSpec.Storage: v1.StorageScopeSpec.Config:
ReadString: expects " or n, but found [, error found in #10 byte of ...|{"nodes":[{"devices"|..., bigger context ...|pgradeChecks":false,"storage":{"config":{"nodes":[{"devices":[{"name":"/dev/sdb"}],"name":"172.70.10|...`

**AFTER INSTALLED MULTUS, NAD, WHEREABOUT and ROOK-CEPH (common, operator and cluster manifest)** 

**NAMESPACE       NAME                                            READY   STATUS      RESTARTS   AGE     IP            NODE              NOMINATED NODE   READINESS GATES**
`ingress-nginx   pod/ingress-nginx-admission-create-9drm5        0/1     Completed   0          2d      10.90.1.235   n2.auto.com   <none>           <none>`
`ingress-nginx   pod/ingress-nginx-admission-patch-cp46h         0/1     Completed   1          2d      10.90.1.104   n2.auto.com   <none>           <none>`
`ingress-nginx   pod/ingress-nginx-controller-59cf455c8f-b5kv9   1/1     Running     0          2d      10.90.2.27    n1.auto.com   <none>           <none>`
`ingress-nginx   pod/ingress-nginx-controller-59cf455c8f-xr6zf   1/1     Running     0          2d      10.90.1.33    n2.auto.com   <none>           <none>`
`kube-system     pod/cilium-4vmsj                                1/1     Running     38         17d     10.70.10.11   n1.auto.com   <none>           <none>`
`kube-system     pod/cilium-operator-df6dfbf9-4v4s4              1/1     Running     22         17d     10.70.10.11   n1.auto.com   <none>           <none>`
`kube-system     pod/cilium-operator-df6dfbf9-rf7zf              1/1     Running     25         17d     10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/cilium-qgrjc                                1/1     Running     25         17d     10.70.10.12   n2.auto.com   <none>           <none>`
`kube-system     pod/cilium-s4sh7                                1/1     Running     47         17d     10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/coredns-f9fd979d6-9859t                     1/1     Running     2          17d     10.90.0.72    m1.auto.com   <none>           <none>`
`kube-system     pod/coredns-f9fd979d6-wz5ts                     1/1     Running     2          17d     10.90.0.133   m1.auto.com   <none>           <none>`
`kube-system     pod/etcd-m1.auto.com                            1/1     Running     2          17d     10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/kube-apiserver-m1.auto.com                  1/1     Running     2          17d     10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/kube-controller-manager-m1.auto.com         1/1     Running     2          17d     10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/kube-multus-ds-amd64-54229                  1/1     Running     0          18m     10.70.10.11   n1.auto.com   <none>           <none>`
`kube-system     pod/kube-multus-ds-amd64-bvd8b                  1/1     Running     0          18m     10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/kube-multus-ds-amd64-ttsc6                  1/1     Running     0          18m     10.70.10.12   n2.auto.com   <none>           <none>`
`kube-system     pod/kube-proxy-85kr9                            1/1     Running     3          17d     10.70.10.11   n1.auto.com   <none>           <none>`
`kube-system     pod/kube-proxy-n4bhf                            1/1     Running     3          17d     10.70.10.12   n2.auto.com   <none>           <none>`
`kube-system     pod/kube-proxy-zz7zn                            1/1     Running     2          17d     10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/kube-scheduler-m1.auto.com                  1/1     Running     2          17d     10.70.10.10   m1.auto.com   <none>           <none>`
`kube-system     pod/whereabouts-5ccsl                           1/1     Running     0          12m     10.70.10.11   n1.auto.com   <none>           <none>`
`kube-system     pod/whereabouts-gdzrk                           1/1     Running     0          12m     10.70.10.12   n2.auto.com   <none>           <none>`
`kube-system     pod/whereabouts-j8ppm                           1/1     Running     0          12m     10.70.10.10   m1.auto.com   <none>           <none>`
`rook-ceph       pod/rook-ceph-operator-6db6f67cd4-5gpms         1/1     Running     0          7m17s   10.90.1.72    n2.auto.com   <none>           <none>`
`rook-ceph       pod/rook-ceph-operator-6db6f67cd4-dh4xn         1/1     Running     0          7m17s   10.90.2.133   n1.auto.com   <none>           <none>`
`rook-ceph       pod/rook-discover-l5ffm                         1/1     Running     0          7m16s   10.90.1.63    n2.auto.com   <none>           <none>`
`rook-ceph       pod/rook-discover-xt9p8                         1/1     Running     0          7m16s   10.90.2.116   n1.auto.com   <none>           <none>`

**NAMESPACE              NAME                                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE   SELECTOR**
`default                service/kubernetes                           ClusterIP      10.96.0.1       <none>        443/TCP                      17d   <none>`
`ingress-nginx          service/ingress-nginx-controller             LoadBalancer   10.104.117.4    10.70.50.1    80:30969/TCP,443:32602/TCP   2d    app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx`

`ingress-nginx          service/ingress-nginx-controller-admission   ClusterIP      10.98.241.68    <none>        443/TCP                      2d    app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx`

`kube-system            service/kube-dns                             ClusterIP      10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP       17d   k8s-app=kube-dns`

`kubernetes-dashboard   service/dashboard-metrics-scraper            ClusterIP      10.98.227.88    <none>        8000/TCP                     16d   k8s-app=dashboard-metrics-scraper`

`kubernetes-dashboard   service/kubernetes-dashboard                 LoadBalancer   10.99.161.154   10.70.50.3    443:30565/TCP                16d   k8s-app=kubernetes-dashboard`

#8
** rook-ceph operator info:   kubectl describe pod rook-ceph-operator-6db6f67cd4-5gpms -n rook-ceph > rook-ceph-opertor-6db6f67cd4-5gpms **

[rook-ceph-opertor-6db6f67cd4-5gpms.txt](https://github.com/rook/rook/files/5398828/rook-ceph-opertor-6db6f67cd4-5gpms.txt)

#9
** rook-ceph cluster manifest:    rook-ceph-cluster.yaml **

[rook-ceph-cluster.txt](https://github.com/rook/rook/files/5398831/rook-ceph-cluster.txt)

#10
** NAD manifest:   multus-networkattachmentdefinition.yaml **

[multus-networkattachmentdefinition.txt](https://github.com/rook/rook/files/5398836/multus-networkattachmentdefinition.txt)

#11
** Enviroment (System Info) **
CentOS 8

kubectl get node
**NAME              STATUS   ROLES    AGE   VERSION**
`m1.auto.com   Ready    master   17d   v1.19.2`
`n1.auto.com   Ready    n1       17d   v1.19.2`
`n2.auto.com   Ready    n2       17d   v1.19.2`

`K8s v1.19.2 and cilium v1.8.4 ,  Ingress-Nginx v0.40.0, ceph version 15.2.4` 

`Three nodes bare metal K8s with 2 NIC interface per nodes.`
`Physical interface NIC1 assiged to network 10.70.0.0/16,  K8s pod-network-cidr 10.90.0.0/16`
`Physical interface NIC2 assiged to network 172.70.0.0/16  for CEPH cluster network`

**Storage:**
`Each physical nodes has an internal 14TBytes raw volume on either device sdb or sda`

**uname -a**
Linux m1.auto.com 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Please let me know what else you might want me to provide.   

Thank you
Yoom

**Comment by leseb** [comment]
Please use backticks to render logs and command properly. This issue is hard to read. Thanks.

**Comment by rohan47** [comment]
Please share your rook-ceph-cluster yaml and network-attachment-definition yaml

**Comment by yoom2016** [comment]
I can not upload the .yaml file format so I rename it into .txt file.  Please rename the file from  .txt   to  .yaml 

[rook-ceph-networkattachmentdefinition.txt](https://github.com/rook/rook/files/5405133/rook-ceph-networkattachmentdefinition.txt)
[rook-ceph-cluster.txt](https://github.com/rook/rook/files/5405134/rook-ceph-cluster.txt)

**Comment by yoom2016** [comment]
Any update?

**Comment by galexrt** [comment]
@yoom2016 The errors you posted indicate a indentation / formatting issue in the CephCluster yaml (e.g., either indentation, a field which must be a string is not quoted).

**Comment by yoom2016** [comment]
#6  above is the operator's log

**Comment by yoom2016** [comment]
**[rook-ceph-operator-6db6f67cd4-9tqld.txt](https://github.com/rook/rook/files/5435835/rook-ceph-operator-6db6f67cd4-9tqld.txt)**
**[rook-ceph-operator-6db6f67cd4-9tqld--describe.txt](https://github.com/rook/rook/files/5435836/rook-ceph-operator-6db6f67cd4-9tqld--describe.txt)**
**[rook-ceph-operator-6db6f67cd4-q6t28.txt](https://github.com/rook/rook/files/5435837/rook-ceph-operator-6db6f67cd4-q6t28.txt)**
