### ISSUE TITLE
pvc's not attacting to pods when using with csi volume(stuck in container creating phase)

### ISSUE THREAD

**Issue by vinayGudi** [rook/rook#6457]
Error saving VolumeAttachment csi-a51649fbff977029d18d2a46823d77fc6e08c8f17bad34bbc65f845f91c37e2d as attached: volumeattachments.storage.k8s.io "csi-a51649fbff977029d18d2a46823d77fc6e08c8f17bad34bbc65f845f91c37e2d" is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-rbd-provisioner-sa" cannot patch resource "volumeattachments/status" in API group "storage.k8s.io" at the cluster scope

with ceph-csi while provisioning block storage i am getting this  in logs of provisioner pod in attacher container
pvc got created and bounded but  when pods tried to attach that pvc ... pods got stuck in container creating
our cluster is in gke

Events:
  Type     Reason              Age                   From                                               Message
  ----     ------              ----                  ----                                               -------
  Warning  FailedScheduling    26m (x2 over 26m)     default-scheduler                                  pod has unbound immediate PersistentVolumeClaims (repeated 6 times)
  Normal   Scheduled           26m                   default-scheduler                                  Successfully assigned rook-ceph/mongodb-primary-0 to gke-cluster-2-default-pool-1b1c1623-wrd9
  Warning  FailedMount         4m31s (x3 over 24m)   kubelet, gke-cluster-2-default-pool-1b1c1623-wrd9  Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[default-token-dvs2t datadir]: timed out waiting for the condition
  Warning  FailedAttachVolume  2m42s (x10 over 24m)  attachdetach-controller                            AttachVolume.Attach failed for volume "pvc-fbb7d86d-91bf-41c1-9ff8-df0033ce7030" : attachment timeout for volume 0001-0009-rook-ceph-0000000000000002-708a35da-0ead-11eb-8912-1a88e82d77c5
  Warning  FailedMount         2s (x9 over 22m)      kubelet, gke-cluster-2-default-pool-1b1c1623-wrd9  Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[datadir default-token-dvs2t]: timed out waiting for the condition

we are using rook v1.4.5 and gke 1.16.13-gke.401

Solution:- 
- apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
need to  be added to rbd-external-provisioner-runner and cephfs-external-provisioner-runner ClusterRole

**Comment by Madhu-1** [comment]
rook 1.4.5 uses external-attacher 2.1.0 https://github.com/rook/rook/blob/v1.4.5/pkg/operator/ceph/csi/spec.go#L103 which does not need this permission, only external-attacher 3.x https://github.com/kubernetes-csi/external-attacher/blob/master/CHANGELOG/CHANGELOG-3.0.md#no-really-you-must-read-this-before-you-upgrade which is in rook master need this change, so this is not a bug if you use supported versions

**Comment by vinayGudi** [comment]
okay, thanks for information :+1:
