### ISSUE TITLE
ceph: Ceph external mode user unable to run 'ceph fs' commands

### ISSUE THREAD

**Issue by aruniiird** [rook/rook#6466]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In order to run create a `Cephfs Snapshotter`, the remote user should be able to run `ceph fs subvolume <commands>`.

Current setup:
RHCS Ceph Version:  14.2.4-125.el8cp
`**Note**:` Confirmed that the above ceph version supports the `ceph fs subvolume <commands>`. 

But from an external cluster we are getting the following error,

`createSnapshotWrapper: CreateSnapshot for content snapcontent-2230d792-fd24-4eca-83c9-c0bee028c324 returned error: rpc error: code = Fai
ledPrecondition desc = subvolume info command not supported in current ceph cluster`

Please note that, on the current RHCS cluster, the external user (username: `client.healthchecker`) has following permissions,

```
client.healthchecker
	key: AQDWTIhfdAeyLRAAAh6cxbI4zLkJgMuaFiw3ew==
	caps: [mgr] allow command config
	caps: [mon] allow r, allow command quorum_status, allow command version
	caps: [osd] allow rwx pool=default.rgw.meta, allow r pool=.rgw.root, allow rw pool=default.rgw.control, allow rx pool=default.rgw.log, allow x pool=default.rgw.buckets.index
```

**Expected behavior:**

Snapshotter feature should work as expected without any error

**How to reproduce it (minimal and precise):**

i. Create an external cluster (with the specified user)
ii. Try to create a `cephfs` snapshot

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by aruniiird** [comment]
@leseb , please take a look...

**Comment by Madhu-1** [comment]
@aruniiird the above log it's clear that the ceph fs subvolume info command is not supported. I don't think it's a permission issue , can you please run 'ceph fs subvolume info' in ceph cluster and paste the output here.

**Comment by leseb** [comment]
@aruniiird @Madhu-1 are we sure that this is the `client.healthchecker` executing the command and not a ceph-csi cephx user?

Since when ceph-csi is using that `client.healthchecker` cephx user? It is only for Rook.

**Comment by Madhu-1** [comment]
> @aruniiird @Madhu-1 are we sure that this is the `client.healthchecker` executing the command and not a ceph-csi cephx user?
> 
> Since when ceph-csi is using that `client.healthchecker` cephx user? It is only for Rook.

AFAIK we are not using `healthchecker` client for any operations. we use provisioner and node user what rook creates for cephfs

**Comment by leseb** [comment]
That's right, so the perm issue is on one of those ceph-csi keys and not `client.healthchecker`.

**Comment by Madhu-1** [comment]
> That's right, so the perm issue is on one of those ceph-csi keys and not `client.healthchecker`.

I don't think it's a permission issue. looks like the `subvolume info` command is not supported on the cluster.

**Comment by leseb** [comment]
> > That's right, so the perm issue is on one of those ceph-csi keys and not `client.healthchecker`.
> 
> I don't think it's a permission issue. looks like the `subvolume info` command is not supported on the cluster.

I misread the error message, then the external cluster version must be updated.

**Comment by aruniiird** [comment]
Closing the issue as it is not the case of missing permissions.
