### ISSUE TITLE
Adding gollvm into CI

### ISSUE THREAD

**Issue by advancedwebdeveloper** [rook/rook#6472]
it is related to an idea of supporting [gollvm](https://go.googlesource.com/gollvm/) compiler ("llvm-goc"), for x86_64 and Aarch64.

All your available demos and proven use-cases from the community.

I have different vision against VM configurations and container configurations.
Would be glad to explain that in a step-by-step manner.

**Comment by advancedwebdeveloper** [comment]
@travisn , ping on you

**Comment by travisn** [comment]
@advancedwebdeveloper What is your proposal?
