### ISSUE TITLE
Volume attachments fail to clear for StateFulSets

### ISSUE THREAD

**Issue by thlassche** [rook/rook#6486]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
- When the pod of a StateFulSet is deleted and a new pod is created, the volume attachments are not cleared from the deleted pod and thus the new pod can never get an attached volume

**Expected behavior:**
- When the old pod of a StateFulSet is removed, the volume attachment is cleared and attached to the new pod

**How to reproduce it (minimal and precise):**
- Create a StateFulSet with one replica
- Add a rook-ceph-block to the pod template
- See a pod being created, with name `<statefulset-name>-0`
- Delete that pod
- Wait for a new pod to be created
- See that the volume attachment fails with an already attached volume mount error

**Cause**:
This is caused by the fact that the new StateFulSetPod has the same name as the deleted one, both `<statefulsetname>-0`. And the controller checks using the pod name: https://github.com/rook/rook/blob/88434ceb5167ba9172d3c354f64cb513abee93ac/pkg/daemon/ceph/agent/flexvolume/controller.go#L144

I'd say that should be switched to the following:
- Get currently attached pod by name
- If it exists, get the UID of the current attachment and compare it with the UID of the pod thats wants the attachment (https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids)
- If the UIDs don't match, allow the mount

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): FCOS
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.4.6
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.9
* Kubernetes version (use `kubectl version`): v1.17.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): healthy

**Comment by travisn** [comment]
@thlassche Have you tried this scenario with the csi driver? I believe you'll get the desired behavior. The flex driver has limited support.

**Comment by thlassche** [comment]
@travisn No, not yet. Good to know that the flex driver has limited support
