### ISSUE TITLE
Make preservePoolsOnDelete default for CephFS

### ISSUE THREAD

**Issue by LalitMaganti** [rook/rook#6491]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
By default, if a CephFilesystem CRD is deleted, the underlying RADOS pools are also deleted. This is configurable through the `preservePoolsOnDelete` option (i.e. `preservePoolsOnDelete` is false by default).

IMO, the default should be changed so that `preservePoolsOnDelete` is true.

**What is use case behind this feature:**
My justification for this is that Rook generally tends to err on the side of *not* deleting user data by default. For example, with OSDs, the user needs to explicitly set a flag `removeOSDsIfOutAndSafeToRemove`. This flag is needed even though it is guarding against removing OSDs which are safe to remove. 

Therefore, it is really jarring that the default for CephFS pools is to delete all data by default. If the CephFilesystem CRD was ever accidentally deleted, I can easily see a big data loss waiting to happen if this flag is not set. I think in most production environments, you would want to set this flag and it's only in toy cases where it's fine to remove.

Comments and counterpoints very much appreciated :)

**Environment**:

**Comment by galexrt** [comment]
@LalitMaganti Sure, sounds good to change it to preserve the pools by default.

Do you want to open a PR to update the default to `true`?

**Comment by LalitMaganti** [comment]
I've ended up going down a very deep rabbit-hole here. Because of #6492, to me `preservePoolsOnDelete` does not even make sense because the data in the metadata pool is essentially irrecoverable without manual intervention.

My intuition is that we should instead have a `preserveFsOnDelete` option (or similarly named) which prevents an fs from being deleted when the CephFilesystem CRD is deleted.

I'm playing around with this now but I've run into #5846 so looking into that atm. Once I get to the bottom of this, I'll certainly send some PRs for discussion :)

**Comment by LalitMaganti** [comment]
We had this discussion on https://github.com/rook/rook/pull/6495 and I think we've come to consensus that we wouldn't make `preserveFilesystemOnDelete` (the replacement for `preservePoolsOnDelete` - see https://github.com/rook/rook/issues/6492 for motivations) default true but all examples would show it being true (which essentially makes the default true)
