### ISSUE TITLE
ceph: failed to remove healthy OSD

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#6509]
**Is this a bug report or feature request?**
* Bug Report

Failed to remove healthy OSD with referring the following document.

https://github.com/rook/rook/blob/3dccee9a42d09628e3570ecae99c99c9194de19f/Documentation/ceph-osd-mgmt.md#from-the-toolbox

When trying to down a healthy OSD from toolbox, it becomes up soon. 

**Deviation from expected behavior:**

Failed to down the OSD.

**Expected behavior:**

Succeed to down the OSD.

**How to reproduce it (minimal and precise):**

1. Make a OSD in a cluster.
2. Try to remove that OSD with referring [this document](https://github.com/rook/rook/blob/3dccee9a42d09628e3570ecae99c99c9194de19f/Documentation/ceph-osd-mgmt.md#remove-an-osd)

**Comment by travisn** [comment]
We also have some automation for removing an OSD, but it was missed in the documentation. See the example [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/osd-purge.yaml). We can remove an OSD by starting this job with the OSD ID. If the OSD is down, it will be purged.

It sounds like your OSD is not down. If you want to remove a healthy OSD, you need to bring it down manually. This likely means to scale down the deployment replicas to 0.

**Comment by satoru-takeuchi** [comment]
You mean a healthy OSD won't be up again after changing deployment replicas to 0?

**Comment by travisn** [comment]
The OSD will come back up if the operator reconciles the OSDs. However, editing the OSD deployment will not trigger a reconcile, so if you are removing the OSD(s) soon after scaling down the OSD, the OSD should still be down when it is removed. Note that deleting an OSD deployment will trigger a reconcile, so scaling down will be better than deleting the deployment.

**Comment by satoru-takeuchi** [comment]
Thank you! I'try this way!

**Comment by satoru-takeuchi** [comment]
It worked fine. Thanks again.
