### ISSUE TITLE
FailureDomain is not refected on CephBlockPool object

### ISSUE THREAD

**Issue by a2batic** [rook/rook#6512]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
CephBlockPool(s) created, doesn't get auto-populated with `failureDomain`.

**Expected behavior:**
Rook to populate `failureDomain` in CephBlockPool object CR.

**How to reproduce it (minimal and precise):**

1.Create a CephBlockPool with Ceph Cluster in ready state, for OSDs select nodes in 3 different zones
```
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: sc-pool
  namespace: openshift-storage
spec:
  replicated:
    size: 3
```
2. Once Pool is in ready state, describe Pool Object, `failureDomain` will be `" "`, instead of `zone`

**File(s) to submit**:

* Operator's logs,: https://pastebin.com/r1cd4cuQ
* Ceph OSD tree output :https://pastebin.com/rFTWn1XG

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux
* Kernel (e.g. `uname -a`): Linux ip-10-0-148-127 4.18.0-193.24.1.el8_2.dt1.x86_64 #1 SMP Thu Sep 24 14:57:05 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): v1.4.0-alpha.0.283.g4df2549
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
* Kubernetes version (use `kubectl version`): 1.15.8-beta.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@a2batic The default failureDomain for the pool is `host` if not specified. Rook does not have the full context to know if there should be some other failureDomain. In theory, Rook could potentially analyze the CRUSH tree and see what the highest level failure domain is that meets the replica setting. However, that tree could change if more OSDs are configured and the failure domain could be confusing or unpredictable. 

Even if Rook were to change the default, Rook will not update the CR settings since it is considered desired state that the operator should not change. The operator only updates the "status" fields on the CR for some status info.

Do you not have the context to detect and set the failure domain on the CR from the start?

**Comment by a2batic** [comment]
> @a2batic The default failureDomain for the pool is `host` if not specified. Rook does not have the full context to know if there should be some other failureDomain. In theory, Rook could potentially analyze the CRUSH tree and see what the highest level failure domain is that meets the replica setting. However, that tree could change if more OSDs are configured and the failure domain could be confusing or unpredictable.
> 
> Even if Rook were to change the default, Rook will not update the CR settings since it is considered desired state that the operator should not change. The operator only updates the "status" fields on the CR for some status info.

ack, thanks @travisn 
> 
> Do you not have the context to detect and set the failure domain on the pool CR when it is created?

Other way that we can get the failureDomains is by fetching value of `failure-domain.beta.kubernetes.io/region` label of PVs attached to `ocs-deviceset-*` PVCs, and assign the right failureDomain to pool based on the number of unique failure domains(least three zones, "zone"; if only one zone is there, "host", otherwise "rack").
Can we go with this approach? Do we have to do this failureDomain calculation once per cluster, or every time user creates a pool?

**Comment by travisn** [comment]
> > Do you not have the context to detect and set the failure domain on the pool CR when it is created?
> 
> Other way that we can get the failureDomains is by fetching value of `failure-domain.beta.kubernetes.io/region` label of PVs attached to `ocs-deviceset-*` PVCs, and assign the right failureDomain to pool based on the number of unique failure domains(least three zones, "zone"; if only one zone is there, "host", otherwise "rack").
> Can we go with this approach? Do we have to do this failureDomain calculation once per cluster, or every time user creates a pool?

You basically want to find the failure domain that ocs is using. Querying the labels on the PVs seems like too low level information. Talk to the owners of the ocs operator, they may have a simpler way to detect the failure domain such as on the status of an OCS CR.

**Comment by a2batic** [comment]
Thanks Travis, closing the bug here!
