### ISSUE TITLE
upgrade procedure does not upgrade toolbox

### ISSUE THREAD

**Issue by michael-db** [rook/rook#6514]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The toolbox pod (the deployment) is not updated by following the procedure at https://rook.io/docs/rook/v1.4/ceph-upgrade.html

**Expected behavior:**

The toolbox pod should be updated.

**How to reproduce it (minimal and precise):**

In the toolbox pod (Rook 1.3.5)
```
radosgw-admin --version
ceph version 14.2.9 (581f22da52345dba46ee232b73b990f06029a2a0) nautilus (stable)
```
Look at the image: field in the toolbox pod yaml.
Follow the upgrade procedure. Note that running the `watch` command makes it appear that everything has been upgraded to 1.4.6. However, the toolbox image remains the same 1.3.5, with the older version of Ceph.

**Attempted workaround**
I tried manually changing the image: version in the toolbox deployment yaml to 1.4.6, and that seemed to work.
However, when I ran a command in the toolbox, it failed
```
radosgw-admin zonegroup list    
2020-10-30T11:05:16.835+0000 7fd9c175b1c0 -1 auth: error parsing file /etc/ceph/keyring: buffer::malformed_input: cannot parse buffer
```
because
```
cat /etc/ceph/keyring
[]
key = 
```
I got the key from another pod and changed it to
```
key = AQBu71hf7VDr<...>
```
But then
```
radosgw-admin zonegroup list    
failed to fetch mon config (--no-mon-config to skip)

radosgw-admin --no-mon-config zonegroup list
2020-10-30T11:32:20.393+0000 7f71518fa1c0  0 ERROR: failed to start rados service ((1) Operation not permitted
2020-10-30T11:32:20.393+0000 7f71518fa1c0  0 ERROR: failed to init services (ret=(1) Operation not permitted)
couldn't init storage provider
```
In
```
cat /etc/ceph/ceph.conf
[global]
mon_host = 10.41.75.95:6789

[client.admin]
keyring = /etc/ceph/keyring
```
the mon_host IP is correct.

**Comment by travisn** [comment]
@michael-db Thanks for the suggestion, updating the toolbox is certainly missing in the upgrade guide. The toolbox spec changed in 1.4 so an update would be needed. Does this help get it working again?
```
kubectl -n rook-ceph delete deploy rook-ceph-tools
# Now create the new v1.4 toolbox on the latest tag
git clone --single-branch --branch v1.4.6 https://github.com/rook/rook.git
cd rook/cluster/examples/kubernetes/ceph
kubectl create -f toolbox.yaml
```

**Comment by michael-db** [comment]
Ah. Indeed, that fixed it. (Though for some reason I had to delete the pod after deleting the deployment before the new one would create a replacement.)
Thank you for the quick response, @travisn!

**Comment by galexrt** [comment]
Reopening as the issue is assigned.
