### ISSUE TITLE
Not able to create Rook-Ceph cluster

### ISSUE THREAD

**Issue by Siddhu1096** [rook/rook#6521]
We are trying to implement rook-ceph cluster on our AKS Cluster. We tried to follow as many documents as we can. The issue we are facing is - common.yaml and operator.yaml are working fine. But when we try to run cluster.yaml, the osd pods are not running. That is when we did through kubectl apply -f common.yaml, kubectl apply -f operator.yaml, kubectl apply -f cluster.yaml. 

But when I tried the create the yaml files using kubectl create -f common.yaml , operator.yaml and cluster.yaml , I am getting different error. The error is Error from server (NotFound): error when creating "cluster.yaml": the server could not find the requested resource (post cephclusters.ceph.rook.io)

Currently following https://dev.to/cdennig/using-rook-ceph-with-pvcs-on-azure-kubernetes-service-djc document 
Any help would be appreciated.

**Comment by travisn** [comment]
@Siddhu1096 If the OSDs are not being created, please see the troubleshooting guide for [creating OSDs](https://rook.github.io/docs/rook/v1.4/ceph-common-issues.html#osd-pods-are-not-created-on-my-devices).

If you're deploying on AKS, you likely want to dynamically provision storage underneath the Ceph OSDs. See the cluster-on-pvc.yaml example as also seen in the [docs](https://rook.github.io/docs/rook/v1.4/ceph-cluster-crd.html#pvc-based-cluster). This way you won't have to attach devices to the nodes, you can just request it from a storageclass for AKS storage.

**Comment by Siddhu1096** [comment]
Thanks. @travisn
