### ISSUE TITLE
Rook 1.4.5 - MGR restarted in a static environment more than 20 times

### ISSUE THREAD

**Issue by hezise** [rook/rook#6527]
Hi,
I'm running the cluster for 12d and I noticed that it has rebooted for 19 times. didn't find a reason why
I attached the mgr and operator logs.

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):
Linux node1 4.15.0-121-generic #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
1.4.5
* Storage backend version (e.g. for ceph do `ceph -v`):
15.2.4
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubespray 2.12

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_OK
[mgr-crash.zip](https://github.com/rook/rook/files/5473578/mgr-crash.zip)

**Comment by hezise** [comment]
[mgr-crash.zip](https://github.com/rook/rook/files/5479688/mgr-crash.zip)
wasn't sure I attached the logs, so I'm attaching again

**Comment by hezise** [comment]
regarding ceph version I see the following:
[root@rook-ceph-tools-86458b8968-v8dc6 /]# ceph version
ceph version 15.2.5 (2c93eff00150f0cc5f106a559557a58d3d7b6f1f) octopus (stable)
[root@rook-ceph-tools-86458b8968-v8dc6 /]# ceph -v     
ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)

**Comment by hezise** [comment]
found this in operator log:
2020-11-03 05:41:05.597327 I | op-mgr: successful modules: http bind settings
2020-11-03 05:41:07.799105 I | op-mgr: dashboard config has changed. restarting the dashboard module.
2020-11-03 05:41:07.799154 I | op-mgr: restarting the mgr module
2020-11-03 05:41:13.305270 I | op-mgr: successful modules: dashboard

the thing is that no one did anything

**Comment by hezise** [comment]
I found the corresponding events in mgr logs 
debug 2020-11-03T05:40:20.582+0000 7f751c440700  0 log_channel(audit) log [DBG] : from='client.2851385 -' entity='client.admin' cmd=[{"prefix": "balancer mode", "mode": "upmap", "target": ["mon-mgr", ""], "format": "json"}]: dispatch
debug 2020-11-03T05:40:20.582+0000 7f7515c3c700  0 [balancer WARNING root] Handling command: '{'format': 'json', 'mode': 'upmap', 'prefix': 'balancer mode', 'target': ['mon-mgr', '']}'
debug 2020-11-03T05:40:29.687+0000 7f751c440700  0 log_channel(audit) log [DBG] : from='client.2851415 -' entity='client.admin' cmd=[{"prefix": "balancer on", "target": ["mon-mgr", ""], "format": "json"}]: dispatch
debug 2020-11-03T05:40:29.687+0000 7f7515c3c700  0 [balancer WARNING root] Handling command: '{'format': 'json', 'prefix': 'balancer on', 'target': ['mon-mgr', '']}'
debug 2020-11-03T05:40:29.983+0000 7f751c440700  0 log_channel(audit) log [DBG] : from='client.2851409 -' entity='client.admin' cmd=[{"prefix": "dashboard set-login-credentials", "username": "admin", "password": "**********", "target": ["mon-mgr", ""], "format": "json"}]: dispatch

**Comment by leseb** [comment]
Some module require reloading the mgr so it's normal to have the container restarted. What's the periodicity of the restart?

**Comment by hezise** [comment]
here is the restart message since I created the cluster

2020-10-21 05:55:18.092130 I | op-mgr: restarting the mgr module
2020-10-21 06:52:44.806893 I | op-mgr: restarting the mgr module
2020-10-21 06:54:12.289343 I | op-mgr: restarting the mgr module
2020-10-22 02:40:15.098897 I | op-mgr: restarting the mgr module
2020-10-22 13:03:56.304570 I | op-mgr: restarting the mgr module
2020-10-22 23:27:12.702506 I | op-mgr: restarting the mgr module
2020-10-23 09:50:44.898153 I | op-mgr: restarting the mgr module
2020-10-23 20:14:25.706700 I | op-mgr: restarting the mgr module
2020-10-24 06:37:56.909842 I | op-mgr: restarting the mgr module
2020-10-24 17:01:36.497229 I | op-mgr: restarting the mgr module
2020-10-25 03:25:10.893145 I | op-mgr: restarting the mgr module
2020-10-25 13:49:04.904871 I | op-mgr: restarting the mgr module
2020-10-26 00:12:25.701344 I | op-mgr: restarting the mgr module
2020-10-26 10:36:02.486322 I | op-mgr: restarting the mgr module
2020-10-26 20:59:49.391243 I | op-mgr: restarting the mgr module
2020-10-27 07:23:32.900041 I | op-mgr: restarting the mgr module
2020-10-27 17:47:06.496851 I | op-mgr: restarting the mgr module
2020-10-28 04:10:39.603993 I | op-mgr: restarting the mgr module
2020-10-28 14:34:05.994212 I | op-mgr: restarting the mgr module
2020-10-29 00:57:57.698585 I | op-mgr: restarting the mgr module
2020-10-29 11:21:30.786884 I | op-mgr: restarting the mgr module
2020-10-29 21:44:55.589758 I | op-mgr: restarting the mgr module
2020-10-30 08:08:30.495834 I | op-mgr: restarting the mgr module
2020-10-30 18:32:21.799541 I | op-mgr: restarting the mgr module
2020-10-31 04:55:38.687687 I | op-mgr: restarting the mgr module
2020-10-31 15:19:31.110457 I | op-mgr: restarting the mgr module
2020-11-01 01:42:53.886026 I | op-mgr: restarting the mgr module
2020-11-01 12:06:47.690737 I | op-mgr: restarting the mgr module
2020-11-01 22:30:04.899935 I | op-mgr: restarting the mgr module
2020-11-02 08:53:48.694016 I | op-mgr: restarting the mgr module
2020-11-02 19:17:17.994991 I | op-mgr: restarting the mgr module
2020-11-03 05:41:07.799154 I | op-mgr: restarting the mgr module

**Comment by hezise** [comment]
looks like approximately every 10 hrs.

**Comment by travisn** [comment]
This sounds like the same as #3376 where the operator is restarting the mgr module during every reconcile, which we should be avoiding if there weren't any configuration changes to the module.

**Comment by leseb** [comment]
Non-trivial IMO.

**Comment by leseb** [comment]
@hezise how come do you have so many reconciles happening?

**Comment by hezise** [comment]
@leseb as part of stability test we have a setup that is up 24/7 and we just leave it there and we're checking it 
this is how we noticed those many restarts

**Comment by hezise** [comment]
this setup is located in Azure
we have the same setup in vmware and we didn't have any such issues

**Comment by leseb** [comment]
Would you mind turning on DEBUG logging on the operator and send as much log as possible so we can determine what's is kicking off the reconcile?
Thanks!

**Comment by hezise** [comment]
sure

**Comment by hezise** [comment]
@leseb Sorry for my late response
here is a debug log I used tgz to compress
[operator_log.gz](https://github.com/rook/rook/files/5588153/operator_log.gz)

**Comment by leseb** [comment]
> @leseb Sorry for my late response
> here is a debug log I used tgz to compress
> [operator_log.gz](https://github.com/rook/rook/files/5588153/operator_log.gz)

I just see a single instance of  `op-mgr: restarting the mgr module`, which does not me any lead on why it is restarting, just the:

```
op-mgr: dashboard config has changed. restarting the dashboard module.
```

We need to understand why the cluster reconciles every 24h...

**Comment by travisn** [comment]
> We need to understand why the cluster reconciles every 24h...

This is likely due to the controller runtime invalidating the watcher, and the operator basically has to create a new watcher. This has been the behavior as long as I can remember, although it's usually unpredictable in general when the watcher is invalidated.

**Comment by hezise** [comment]
@travisn so this is an expected behavior?
do you need more logs?

**Comment by travisn** [comment]
The expected behavior is that the reconcile will trigger periodically, once or twice a day is in the normal range. But the bug is that if there is nothing changing in the configuration, Rook shouldn't be restarting the dashboard. It would be good to understand why rook sees a configuration change: 
```
op-mgr: dashboard config has changed. restarting the dashboard module.
```
Can you change the [operator log level](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L383) to `DEBUG` and then let's look at the logs around the "dashboard config has changed" part of the log. You'll want to reset the logger to `INFO` again after that is captured.

**Comment by hezise** [comment]
I will update once I have it

**Comment by hezise** [comment]
@travisn attached the log file
[rook-logs.zip](https://github.com/rook/rook/files/5800359/rook-logs.zip)
It's tgz file

**Comment by travisn** [comment]
I see now, when the the `dashboard.ssl` is `false`, the dashboard module will always be restarted with every reconcile. Is it an option to set it to [true](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L60)? This is preferred in production. But in any case we will fix this.

**Comment by hezise** [comment]
I'm using istio

**Comment by hezise** [comment]
thanks for your reply :)
