### ISSUE TITLE
OSDs failing to be created in Ceph v14.2.13 when using ceph-volume batch mode (when not on PVCs)

### ISSUE THREAD

**Issue by travisn** [rook/rook#6532]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The v14.2.13 nautilus release images were published today, and since then the integration tests running nautilus are failing. The helm and upgrade tests install the latest nautilus (`v14` tag). 

As seen in the [test log](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/master/runs/2348/nodes/65/steps/135/log/?start=0), the test times out waiting for OSDs:
```
2020-11-02 20:20:18.428454 I | testutil: waiting for 1 pods (found 0) with label app=rook-ceph-osd in namespace helm-ns
```

The [OSD prepare log](https://jenkins.rook.io/job/rook/job/rook/job/master/2348/artifact/_output/tests/TestCephHelmSuite_aws_1.16.x_helm-ns_rook-ceph-osd-prepare-ip-172-31-32-185-qv9vv_1604348228.log) shows that the device is unavailable:
```
2020-11-02 20:14:46.587632 I | cephosd: configuring new device nvme0n1
2020-11-02 20:14:46.587655 I | cephosd: Base command - stdbuf
2020-11-02 20:14:46.587659 I | cephosd: immediateReportArgs - stdbuf
2020-11-02 20:14:46.587695 I | cephosd: immediateExecuteArgs - [-oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/nvme0n1]
2020-11-02 20:14:46.587709 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/nvme0n1 --report
2020-11-02 20:14:50.499101 D | exec: --> DEPRECATION NOTICE
2020-11-02 20:14:50.499152 D | exec: --> You are using the legacy automatic disk sorting behavior
2020-11-02 20:14:50.499157 D | exec: --> The Pacific release will change the default to --no-auto
2020-11-02 20:14:50.499160 D | exec: --> passed data devices: 0 physical, 0 LVM
2020-11-02 20:14:50.499163 D | exec: --> relative data size: 1.0
2020-11-02 20:14:50.499197 D | exec: --> All data devices are unavailable
2020-11-02 20:14:50.499356 D | exec: 
2020-11-02 20:14:50.499402 D | exec: Total OSDs: 0
```

Important to note is that the multi-cluster test suite also runs with nautilus, but it succeeds. The difference appears to be that it is configuring OSDs on local PVs rather than directly provisioning the device.

**Expected behavior:**
Integration tests should pass for the latest nautilus even when not on local PVs.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by satoru-takeuchi** [comment]
@travisn 

I  confirmed that this problem happens in CephHelmSuite with ceph v14.2.13. I'll try the same suite with ceph v14.2.12.

Here is the difference between v14.2.12 and v14.2.13.
https://github.com/ceph/ceph/compare/v14.2.12...v14.2.13

And here is the summary of changes.
https://docs.ceph.com/en/latest/releases/nautilus/

I suspect the following refactoring work cause this problem

> ceph-volume: the lvm batch subcommand received a major rewrite

IIRC, OSD on device uses `ceph-volume lvm batch` and OSD on PVC doesn't use it.

I'll submit an issue to Ceph's issue tracker after finding a bit more detail. However, I guess it takes at least some days to fix this problem in the stable release. So, how about changing the ceph's version tag in CI from v1.14 to v14.2.12 temporarily?

**Comment by travisn** [comment]
@satoru-takeuchi Yes, sounds like we will need to use v14.2.12 in the tests for now until the fix is out, and also we need a more general recommendation that 14.2.13 not be used in Rook.

**Comment by travisn** [comment]
Reopening until we have the full fix

**Comment by leseb** [comment]
PR upstream https://github.com/ceph/ceph/pull/37942

**Comment by satoru-takeuchi** [comment]
Additional input.

- The above-mentioned refactoring PRs are also in Octopus branch but it's not in the newest v15.2.5. Rook will hit this problem once Ceph v15.2.6 is released.
- This problem happens in non-CI environment.

**Comment by satoru-takeuchi** [comment]
Oops, thanks @leseb .

**Comment by leseb** [comment]
> Oops, thanks @leseb .

I think I can make a PR to fix this, unless you are working on it :)

**Comment by satoru-takeuchi** [comment]
@leseb I'm not working on it yet. I'll leave it to you.
