### ISSUE TITLE
MGR fails to send alert

### ISSUE THREAD

**Issue by pavanfhw** [rook/rook#6541]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Can't send alert emails using alert module
**Expected behavior:**
`ceph alerts send` command in the toolbox should send an alert.
**How to reproduce it (minimal and precise):**

Configure Alert module like https://docs.ceph.com/en/latest/mgr/alerts/

**Environment**:
* OS (e.g. from /etc/os-release): K3OS
* Kernel (e.g. `uname -a`): Linux hostname 5.4.0-37-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`): rook: v1.3.9/go: go1.13.8
* Kubernetes version (use `kubectl version`): 1.18
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
HEALTH_WARN unable to send alert email
ALERTS_SMTP_ERROR unable to send alert email
    [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:618)
```
Ceph does not know SSL protocol??

In MGR logs:

```
ceph_set_health_checks check ALERTS_SMTP_ERROR unexpected key count
```
Anyone with knowledge or successful experience can help with this?

**Comment by leseb** [comment]
For Ceph related issues, please open a bug here instead https://tracker.ceph.com/. Thanks.
