### ISSUE TITLE
Q - how to debug slow metadata IOs; 1108 slow ops, oldest one blocked for 15063 sec

### ISSUE THREAD

**Issue by hezise** [rook/rook#6542]
Hi,
I'm using rook 1.4.5 with ceph 15.2.5
I'm running a cluster for long run and monitoring it
I started to have issues and I looked into ceph-tools
I'd like to know how to debug the following:
ceph health detail
HEALTH_WARN 2 MDSs report slow metadata IOs; 1108 slow ops, oldest one blocked for 15063 sec, daemons [osd.0,osd.1] have slow ops.
[WRN] MDS_SLOW_METADATA_IO: 2 MDSs report slow metadata IOs
    mdsshared-storage-a(mds.0): 1 slow metadata IOs are blocked > 30 secs, oldest blocked for 15030 secs
    mdsshared-storage-b(mds.0): 1 slow metadata IOs are blocked > 30 secs, oldest blocked for 2817 secs
[WRN] SLOW_OPS: 1108 slow ops, oldest one blocked for 15063 sec, daemons [osd.0,osd.1] have slow ops.

**Comment by runzhliu** [comment]
Check if the Monitor time is synchronized.

**Comment by rajivml** [comment]
am also running into this, with rook 1.4.3,


```
sh-4.4# ceph health detail
HEALTH_WARN 1 MDSs report slow metadata IOs; 11 pool(s) have no replicas configured; 1198 slow ops, oldest one blocked for 54194 sec, osd.0 has slow ops
[WRN] MDS_SLOW_METADATA_IO: 1 MDSs report slow metadata IOs
    mdsrook-shared-fs-b(mds.0): 1 slow metadata IOs are blocked > 30 secs, oldest blocked for 54196 secs
[WRN] POOL_NO_REDUNDANCY: 11 pool(s) have no replicas configured
    pool 'device_health_metrics' has no replicas configured
    pool 'replicapool' has no replicas configured
    pool 'rook-ceph-store.rgw.control' has no replicas configured
    pool 'rook-shared-fs-metadata' has no replicas configured
    pool 'rook-shared-fs-data0' has no replicas configured
    pool 'rook-ceph-store.rgw.meta' has no replicas configured
    pool 'rook-ceph-store.rgw.log' has no replicas configured
    pool 'rook-ceph-store.rgw.buckets.index' has no replicas configured
    pool 'rook-ceph-store.rgw.buckets.non-ec' has no replicas configured
    pool '.rgw.root' has no replicas configured
    pool 'rook-ceph-store.rgw.buckets.data' has no replicas configured
[WRN] SLOW_OPS: 1198 slow ops, oldest one blocked for 54194 sec, osd.0 has slow ops
```

**Comment by galexrt** [comment]
@rajivml All your pools don't seem to have any replicas configured. What is the `replicated.size` in your CephBlockPool, CephObjectStore and CephCfilesystem objects?

Which yaml files did you use for your Rook Ceph cluster? The files ending in `-test.yaml`?
Are all your Ceph OSDs up'n'running? `ceph -s` and `ceph osd tree` can help here.

**Comment by Tank-Tong** [comment]
> Check if the Monitor time is synchronized.

In the single ceph node, also has this problem. How to debug which op slow
