### ISSUE TITLE
I want to safely update ceph cluster without uninstalling the old version of rook.

### ISSUE THREAD

**Issue by vdi-kakui** [rook/rook#6549]
I want to safely update ceph cluster without uninstalling the old version of rook.
Is there a way to do that?

Please let me know if there is a recommended way to update ceph cluster or rook.

**Comment by galexrt** [comment]
Yes, please follow the appropriate upgrade guide(s) https://rook.io/docs/rook/v1.4/ceph-upgrade.html
You must update from each version to the other, e.g., if you are still on 1.1, you must update 1.1 -> 1.2, 1.2 -> 1.3, 1.3 -> 1.4.

For general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://slack.rook.io/).
