### ISSUE TITLE
CephFS being to slow writing a git clone

### ISSUE THREAD

**Issue by BrunoFontainha** [rook/rook#6552]
**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel Linux 3.10.0-1127.19.1.el7.x86_64
* Cloud provider or hardware configuration: Azure Vms
* Rook version rook: v1.3.11
* Storage backend version: 14.2.10
* Kubernetes version: v1.19.3
* Kubernetes cluster type: Installed on azure vms
* Storage backend status HEALTH_WARN clock skew detected on mon.b, mon.c

**Environment:** 1 Master + 3 Slaves
**OSDs** 3 osd in a separated ssd with 100 GB

When doing a git clone of a 4gb repository to a mounted pvc in a pod, takes over 1h to finish the work.

After that running mvn clean install on top of these files takes another 1h

Doesn't look reasonable. would it have an alternative?

thanks

**Comment by galexrt** [comment]
Please fill out the whole issue template and for general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://slack.rook.io/).
