### ISSUE TITLE
I want to uninstall ceph-cluster, but I get an error.

### ISSUE THREAD

**Issue by vdi-kakui** [rook/rook#6554]
I want to uninstall ceph-cluster, but I get an error.

The version you are using is rook v1.1.
When I try to delete ceph-cluster, I get an error like the one below.

```
error: unable to recognize "cluster.yaml": no matches for kind "CephCluster" in version "ceph.rook.io/v1"
```

Due to this problem, ceph-cluster cannot be installed / uninstalled.

**Comment by galexrt** [comment]
Please fill out the whole issue template and for general technical and non-technical questions, we are happy to help you on our [Rook.io Slack](https://slack.rook.io/).
