### ISSUE TITLE
Set environment variables with the ceph and nfs-ganesha version

### ISSUE THREAD

**Issue by varshar16** [rook/rook#6565]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Ceph and nfs-ganesha version should be available as environment variables.
```
CEPH_VERSION=15.2.5-0
NFS_GANESHA_VERSION=3.3
```
**What is use case behind this feature:**
In ceph mgr rook module, `cephcluster` can be queried to fetch ceph version. Instead it would be good have an environment variable. And currently there is no nfs-ganesha version in the result of `cephnfses.ceph.rook.io`.

The version details are required by `ceph orch ps` command.
```
[root@rook-ceph-tools-78cdfd976c-4cdhr /]# ceph orch ps
NAME        HOST      STATUS         REFRESHED  AGE  VERSION    IMAGE NAME                           IMAGE ID   CONTAINER ID
mds.myfs-a  minikube  Running (8m)   0s ago     8m   <unknown>  192.168.0.138:5000/ceph/ceph:latest  <unknown>  rook-ceph-mds-myfs-a-6fb86c99ff-trzn7
mds.myfs-b  minikube  Running (8m)   0s ago     8m   <unknown>  192.168.0.138:5000/ceph/ceph:latest  <unknown>  rook-ceph-mds-myfs-b-768c9bf56c-vxmkm
mgr.a       minikube  Running (13m)  0s ago     13m  <unknown>  192.168.0.138:5000/ceph/ceph:latest  <unknown>  rook-ceph-mgr-a-6f7db564b8-gx4fw
mon.a       minikube  Running (13m)  0s ago     13m  <unknown>  192.168.0.138:5000/ceph/ceph:latest  <unknown>  rook-ceph-mon-a-f4b8cb9d5-zzgkr
nfs.a       minikube  Running (8m)   0s ago     8m   <unknown>  192.168.0.138:5000/ceph/ceph:latest  <unknown>  rook-ceph-nfs-my-nfs-a-976f579cc-g62kl
nfs.b       minikube  Running (8m)   0s ago     8m   <unknown>  192.168.0.138:5000/ceph/ceph:latest  <unknown>  rook-ceph-nfs-my-nfs-b-79b49674bf-5d8cl
nfs.c       minikube  Running (7m)   0s ago     7m   <unknown>  192.168.0.138:5000/ceph/ceph:latest  <unknown>  rook-ceph-nfs-my-nfs-c-58b658bdc7-5w6wj
osd.0       minikube  Running (12m)  0s ago     12m  <unknown>  192.168.0.138:5000/ceph/ceph:latest  <unknown>  rook-ceph-osd-0-bbfd9d6f6-swcj8
```

**Environment**:

**Comment by travisn** [comment]
Rook is already adding the ceph version to the mgr deployment labels, so it will be simple to also add as an env var on the mgr pod.

@varshar16 How can the nfs ganesha version be detected? Rook doesn't have that info today.

**Comment by varshar16** [comment]
> Rook is already adding the ceph version to the mgr deployment labels, so it will be simple to also add as an env var on the mgr pod.
> 
> @varshar16 How can the nfs ganesha version be detected? Rook doesn't have that info today.

In cephadm, they exec the nfs-ganesha container to get version info. We can probably do something similar.
https://github.com/ceph/ceph/blob/cc5ef565d4fad4528e2dd5130efe46c9ddec6778/src/cephadm/cephadm#L269-L279

**Comment by travisn** [comment]
If I exec to the mgr pod and run the same command as you linked, I get the ganesha version:
```
# /usr/bin/ganesha.nfsd -v
NFS-Ganesha Release = V3.3
```

For the operator to detect this version, it would have to launch a new job just like how the ceph version is detected. The ceph version is critical to the orchestration, which is why we do it, but nfs isn't critical to the main reconcile so I don't think the operator should do that. In the mgr pod instead of looking for an env var, why not run `/usr/bin/ganesha.nfsd -v` to get the version directly? The mgr pod is running the same ceph image that the nfs pod will run.

**Comment by varshar16** [comment]
> If I exec to the mgr pod and run the same command as you linked, I get the ganesha version:
> 
> ```
> # /usr/bin/ganesha.nfsd -v
> NFS-Ganesha Release = V3.3
> ```
> 
> For the operator to detect this version, it would have to launch a new job just like how the ceph version is detected. The ceph version is critical to the orchestration, which is why we do it, but nfs isn't critical to the main reconcile so I don't think the operator should do that. In the mgr pod instead of looking for an env var, why not run `/usr/bin/ganesha.nfsd -v` to get the version directly? The mgr pod is running the same ceph image that the nfs pod will run.

Yes, that can be done.

**Comment by batrick** [comment]
\

> If I exec to the mgr pod and run the same command as you linked, I get the ganesha version:
> 
> ```
> # /usr/bin/ganesha.nfsd -v
> NFS-Ganesha Release = V3.3
> ```
> 
> For the operator to detect this version, it would have to launch a new job just like how the ceph version is detected. The ceph version is critical to the orchestration, which is why we do it, but nfs isn't critical to the main reconcile so I don't think the operator should do that. In the mgr pod instead of looking for an env var, why not run `/usr/bin/ganesha.nfsd -v` to get the version directly? The mgr pod is running the same ceph image that the nfs pod will run.

I think it's really unlikely that a change having the ceph-mgr fork/exec `ganesha.nfsd` will be approved. Are there no other options here? Can the ceph-mgr run a Rook CRD to get the ganesha version on-demand?

**Comment by travisn** [comment]
> I think it's really unlikely that a change having the ceph-mgr fork/exec ganesha.nfsd will be approved. Are there no other options here? Can the ceph-mgr run a Rook CRD to get the ganesha version on-demand?

Rook doesn't know the ganesha version, so it wouldn't be stored anywhere in a Rook CR. Since the mgr is already running in the same image where the ganesha version can be detected it seems natural to do it there.

Another possibility is at build time to set the ganesha version in an env var in the Dockerfile for the `ceph/ceph` image, but that assumes the ganesha version is known or can otherwise be detected at build time.

**Comment by travisn** [comment]
Closing since Rook doesn't know the ganesha version to set
