### ISSUE TITLE
rook-ceph-mon-b CrashLoopBackOff and rook-ceph-mon-g-canary Pending

### ISSUE THREAD

**Issue by saraAlizadeh** [rook/rook#6577]
**Is this a bug report or feature request?**
* Bug Report
**Deviation from expected behavior:**
I had a working k8s cluster and storage works fine too. except that I see warning that indicated one of mons could not join quorum.
```
kubectl exec -it  rook-ceph-tools-f966bf497-s5bk8 -n rook-ceph -- ceph status
  cluster:
    id:     dedb80df-d16c-4a90-912e-a833a97c3f52
    health: HEALTH_WARN
            3958 daemons have recently crashed
            too few PGs per OSD (19 < min 30)
            1/5 mons down, quorum c,d,e,f
 
  services:
    mon: 5 daemons, quorum c,d,e,f (age 9m), out of quorum: b
    mgr: a(active, since 20h)
    osd: 5 osds: 5 up (since 3h), 5 in (since 2d)
 
  data:
    pools:   1 pools, 32 pgs
    objects: 4.56k objects, 14 GiB
    usage:   47 GiB used, 253 GiB / 300 GiB avail
    pgs:     32 active+clean
```
and these are my pods:
```
..
rook-ceph-mgr-a-755798b9d6-n7wz6                              1/1     Running            1          69d
rook-ceph-mon-b-9b456f8db-tz9d8                               0/1     CrashLoopBackOff   11         35m
rook-ceph-mon-c-7fd959cb88-x5mlx                              1/1     Running            0          8s
rook-ceph-mon-d-77dc858995-pfhwb                              1/1     Running            2          74d
rook-ceph-mon-e-5c4c65d9c8-74jcv                              1/1     Running            2          74d
rook-ceph-mon-f-85d89c878f-4hf9j                              1/1     Running            3          73d
rook-ceph-mon-g-canary-7c987f497-2bsq5                        0/1     Pending            0          2m16s
rook-ceph-operator-66965d7d48-8qhn5                           1/1     Running            0          20h
...
```

kubectl describe pod rook-ceph-mon-b-9b456f8db-tz9d8
```
Events:
  Type     Reason     Age                  From                        Message
  ----     ------     ----                 ----                        -------
  Normal   Scheduled  <unknown>            default-scheduler           Successfully assigned rook-ceph/rook-ceph-mon-b-9b456f8db-tz9d8 to worker1.xxx.ir
  Normal   Pulled     51m                  kubelet, worker1.xxx.ir  Container image "192.168.100.x:8083/ceph/ceph:v14.2.8" already present on machine
  Normal   Created    51m                  kubelet, worker1.xxx.ir  Created container chown-container-data-dir
  Normal   Started    51m                  kubelet, worker1.xxx.ir  Started container chown-container-data-dir
  Normal   Pulled     51m                  kubelet, worker1.xxx.ir  Container image "192.168.100.x:8083/ceph/ceph:v14.2.8" already present on machine
  Normal   Created    51m                  kubelet, worker1.xxx.ir  Created container init-mon-fs
  Normal   Started    51m                  kubelet, worker1.xxx.ir  Started container init-mon-fs
  Normal   Pulled     50m (x4 over 51m)    kubelet, worker1.xxx.ir  Container image "192.168.100.x:8083/ceph/ceph:v14.2.8" already present on machine
  Normal   Created    50m (x4 over 51m)    kubelet, worker1.xxx.ir  Created container mon
  Normal   Started    50m (x4 over 51m)    kubelet, worker1.xxx.ir  Started container mon
  Warning  BackOff    83s (x240 over 51m)  kubelet, worker1.xxx.ir  Back-off restarting failed container
```
 kubectl describe pod rook-ceph-mon-g-canary-7c987f497-xr86n
```
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/7 nodes are available: 2 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 5 node(s) didn't match pod affinity/anti-affinity, 5 node(s) didn't match pod anti-affinity rules.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/7 nodes are available: 2 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 5 node(s) didn't match pod affinity/anti-affinity, 5 node(s) didn't match pod anti-affinity rules.
```

my ceph config (/var/lib/rook/rook-ceph/rook-ceph.config): 
mon initial members = b c d f e

**Expected behavior:**
I expect mon-b to get created smoothly, since all other pods on worker1 work fine. with no issue.
I deleted mon-b pod or mon-g-canary pod , recreated operator pod , restart docker on worker, and they didn't help. No Change! 

**Environment**:
* OS (e.g. from /etc/os-release): centos 7.2
* Kernel (e.g. `uname -a`): 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: private vsphere 6.5
* Rook version (use `rook version` inside of a Rook Pod): 1.3
* Storage backend version (e.g. for ceph do `ceph -v`): v14.2.8
* Kubernetes version (use `kubectl version`): 1.18.5

**Comment by bradenwright** [comment]
If you are trying to setup a ceph cluster with 5 mons, I think you need 10 nodes.  In the example, or at least for me to setup 3 mons, 3 osd (example), I needed 6 nodes if `allowMultiplePerNode: false`

**Comment by travisn** [comment]
What do the logs for the mon-b pod show? It's certainly unexpected to be crashing. Did you perhaps reinstall? If so perhaps something needs to be cleaned from the node, see the [cleanup guide](https://rook.github.io/docs/rook/v1.5/ceph-teardown.html).

The operator sees mon-b down so it tries to start a new mon to replace it, but as @bradenwright said, you don't have enough nodes to support that failover. You could try deleting the mon-b deployment to see if that allows mon-g to be scheduled.

**Comment by saraAlizadeh** [comment]
> What do the logs for the mon-b pod show? It's certainly unexpected to be crashing. Did you perhaps reinstall? If so perhaps something needs to be cleaned from the node, see the [cleanup guide](https://rook.github.io/docs/rook/v1.5/ceph-teardown.html).
> 
> The operator sees mon-b down so it tries to start a new mon to replace it, but as @bradenwright said, you don't have enough nodes to support that failover. You could try deleting the mon-b deployment to see if that allows mon-g to be scheduled.

actually ```allowMultiplePerNode``` is false, yes! but my cluster was working fine with that config.
I had to changes, no reinstallation, to change in configs.
I deleted mon-b deployment or scaled it to 0, but mon-g kept staying pending, complaining about "didn't match pod anti-affinity rules".
So you think mon-g-canary is trying to create  mon-g, and there are 5 mons in cluster already (though b is crashed), hence it cannot do its job properly?
btw, you can see mon-b logs here: https://github.com/saraAlizadeh/logs/blob/main/mon-b.log

**Comment by travisn** [comment]
Can you try updating the version of Ceph from `ceph/ceph:v14.2.8` to `ceph/ceph:v14.2.12`?
