### ISSUE TITLE
Ceph v14.2.13 fails to expand OSD with >85% usage

### ISSUE THREAD

**Issue by terorie** [rook/rook#6584]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
My OSD grew slightly beyond 85% utilization, and a resize attempt failed with a crash in `expand-bluefs` after expanding the PVC the OSD is running on.

Even _after_ resizing the `expand-bluefs` container will still crash without the workaround mentioned below.

**Expected behavior:**
`expand-bluefs` expands the PVC without crashing.

**How to reproduce it (minimal and precise):**
I can't guarantee this works:
- Create a Ceph Cluster CRD based on K8s persistent volumes
- Allocate so much storage to force at least one OSD to go >85% utilization
- Expand the underlying PVC directly by editing the resource request
- Delete the OSD to recreate the pod and re-run the `expand-bluefs` container.

Ceph Tracker Bug report: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/TMKGRSLSLC5CQQXLSE5AHYPBURUU4WVS/?sort=date

**EDIT** It might be coincidental that the Ceph bug occured as the OSD grew beyond 85% utilization. 

**Workaround**

This is only temporary and will get overridden by rook-operator eventually.
1. `kubectl edit -n rook-ceph deploy/rook-ceph-osd-1` (your affected OSD)
2. Find `expand-bluefs` init container
3. Append string `--bluestore_hybrid_alloc_mem_cap=0` to the `args` list of the init container. (Credit to Igor Fedotov in the Ceph Tracker Bug report)
4. Delete the crashing pod to make space for the new pod.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

https://gist.github.com/terorie/22372ab8493f7db2a7ff037265d4ee2d

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS
* Kernel (e.g. `uname -a`): `Linux <redacted>-aqsn 5.4.0-1027-gke #28~18.04.1-Ubuntu SMP Thu Oct 1 13:13:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: GKE with default feature flags, e2-standard-8 machine type
* Rook version (use `rook version` inside of a Rook Pod): v1.4.6
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.13 (1778d63e55dbff6cedb071ab7d367f8f52a8699f) nautilus (stable)`
* Kubernetes version (use `kubectl version`): 
1.18.10-gke.601
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): WARNING (since one OSD is crashing)

**Comment by terorie** [comment]
It might be worth giving the user some control over the command-line arguments to the Ceph init containers to persist these kinds of workarounds, or at least injecting the Ceph "extra" ConfigMap using the `-c` argument.
https://github.com/rook/rook/blob/e3d032dbc151ee643478cddc913f32684c9d5520/pkg/operator/ceph/cluster/osd/spec.go#L1032

**Comment by leseb** [comment]
These workarounds are not trivial to implement. What do you mean by the CM and `-c`, will `ceph-bluestore-tool` read the ceph.conf file?

**Comment by terorie** [comment]
@leseb I think so, according to the Ceph documentation it looks like a config file flag will work: https://docs.ceph.com/en/latest/rados/configuration/ceph-conf/#config-sources

> Each Ceph daemon, process, and library will pull its configuration from several sources, listed below. Sources later in the list will override those earlier in the list when both are present.
>
> - the compiled-in default value
> - the monitor cluster’s centralized configuration database
> - a configuration file stored on the local host
> - environment variables
> - command line arguments
> - runtime overrides set by an administrator
>
> One of the first things a Ceph process does on startup is parse the configuration options provided via the command line, environment, and local configuration file.

**Comment by terorie** [comment]
Upgrading my cluster from Ceph v14 to Ceph v15 resolved the issue without needing a hacky workaround. Closing this issue since this isn't an issue with Rook, but a broken Ceph version.
