### ISSUE TITLE
Abort a CephCluster reconcile if the CR is updated while a reconcile is in progress

### ISSUE THREAD

**Issue by travisn** [rook/rook#6587]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The operator should abort a CephCluster reconcile if the cluster CR is updated. This is particularly an issue during upgrades where both the rook operator and the ceph image are updated at the same time. Both of them will start a new reconcile, and you might need to wait a long time for the second reconcile unnecessarily.

In a test log recently, we saw a 37 minute delay before the second reconcile:
```
# The first reconcile begins and the ceph version is detected:
2020-11-09T13:12:57.509119960Z 2020-11-09 13:12:57.509083 I | ceph-cluster-controller: cluster "openshift-storage": version "14.2.8-91 nautilus" detected for image "quay.io/rhceph-dev/rhceph@sha256:eafd1acb0ada5d7cf93699056118aca19ed7a22e4938411d307ef94048746cc8"

# The cluster CR is updated, which will start the second reconcile as soon as the first reconcile is done. Notice how this happens immediately after the first reconcile started, so we have to wait a long time.
2020-11-09T13:12:57.966652084Z 2020-11-09 13:12:57.966596 I | ceph-spec: CR has changed for "ocs-storagecluster-cephcluster". diff=  v1.ClusterSpec{

# The second reconcile finally starts 37 minutes later
2020-11-09 13:49:57.272222 I | ceph-cluster-controller: detected ceph image version: "14.2.8-111 nautilus"
```

We are printing that the cluster spec changed [here](https://github.com/rook/rook/blob/23108cc94afdebc8f4ab144130a270b1e4ffd94e/pkg/operator/ceph/controller/predicate.go#L275), but then we wait (potentially a long time) before we ever act on it.

The operator should check at various intervals to see if the cluster has been updated and therefore should abort the reconcile in progress. For example, we should check when:
- After the mons are updated
- In between each osd being updated, such as when we are checking if an osd is ok-to-stop. This tends to take the longest during a reconcile, and the reconcile can be aborted with low risk during OSD reconcile.

**What is use case behind this feature:**
More responsive reconcile, particularly during upgrades

**Comment by leseb** [comment]
We would need that also for Cluster Deletion requests. I don't see an easy way to fix this, also this would mean IMO a huge refactor of our `context` usage.
I'll take care of that for 1.6.

**Comment by leseb** [comment]
We agreed to take a simple approach for 1.5 for a small backport, so moving back to 1.5.
