### ISSUE TITLE
Cassandra Cluster - Mode:scylla - Readiness probe failed: HTTP probe failed with statuscode: 503 

### ISSUE THREAD

**Issue by vayyappaneni** [rook/rook#6590]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
* Cassandra Cluster is not up when I sett he mode to **scylla** - Readiness probe failed: HTTP probe failed with statuscode: 503 

**Expected behavior:**
* Cassandra cluster should be up and running

**How to reproduce it (minimal and precise):**
1. deploy the rook Cassandra operator 1.4.7  -[link](https://github.com/rook/rook/blob/v1.4.7/cluster/examples/kubernetes/cassandra/operator.yaml)
2. Once the operator up and running deploy the cluster by editing the following details from cluster.yaml under # Cassandra Cluster section. - [link](https://github.com/rook/rook/blob/v1.4.7/cluster/examples/kubernetes/cassandra/cluster.yaml)
         ```
spec:
           version: 4.2.0
           mode: scylla
```

**File(s) to submit**:

* Crashing pod(s) logs, if necessary

[cassandra-cluster_pod.logs.txt](https://github.com/rook/rook/files/5514078/cassandra-cluster_pod.logs.txt)

**Environment**:
* OS (e.g. from /etc/os-release): ProductName:	Mac OS X,  ProductVersion:10.15.7,  BuildVersion: 19H15 
* Rook version (use `rook version` inside of a Rook Pod): 1.4.7
* Kubernetes version (use `kubectl version`): v1.19.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Docker desktop

**Comment by yanniszark** [comment]
@vayyappaneni while this operator was originally made to support both Cassandra and Scylla, the Scylla part was eventually split into its own operator:
https://github.com/scylladb/scylla-operator

If you want to run Scylla on Kubernetes please use the aforementioned link, it is the officially supported way (afaik scylla engineers are actively ameliorating the operator).
