### ISSUE TITLE
rook ceph 1.1.7 on kubernetes 1.19.3 fails to run osd prepare job

### ISSUE THREAD

**Issue by raz3k** [rook/rook#6608]
YES

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
failed to create provision job for node worker-7f36eb8749789e6a06b8. Job.batch "rook-ceph-osd-prepare-worker-7f36eb8749789e6a06b8" is invalid: [spec.template.spec.volumes[6].hostPath.path: Required value, spec.template.spec.volumes[6].name: Required value, spec.template.spec.containers[0].volumeMounts[6].name: Required value, spec.template.spec.containers[0].volumeMounts[6].name: Not found: "", spec.template.spec.containers[0].volumeMounts[6].mountPath: Required value]

**Expected behavior:**
run prepare osd job
**How to reproduce it (minimal and precise):**

Run a rook ceph cluster 1.1.7 on kubernetes 1.19.3
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary 
https://pastebin.com/Zq8AkNyq
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 8.2
* Kernel (e.g. `uname -a`): Linux 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: OpenStack
* Rook version (use `rook version` inside of a Rook Pod): 1.1.7
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
* Kubernetes version (use `kubectl version`): 1.19.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Scratch
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@raz3k Is this a new install? If so, how about running on the latest release [v1.4.7](https://rook.github.io/docs/rook/v1.4/ceph-quickstart.html#tldr)? That error sounds vaguely familiar, related to host networking, but I can't find it in the old issues.
