### ISSUE TITLE
helm crd deletion

### ISSUE THREAD

**Issue by kfox1111** [rook/rook#6617]
* Feature Request

**What should the feature do:**

It would be nice if the helm crd's were marked as resource-policy: keep so they wont be accidently deleted on helm chart removal.

See:

https://helm.sh/docs/howto/charts_tips_and_tricks/ has a section:
"Tell Helm Not To Uninstall a Resource"
Should be something like:

```
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
[...]
```

And the corresponding total cleanup documentation should reflect:
kubectl delete -f crds.yaml

This would put another roadblock in place of accidentally deleting a production cluster.

Previously discussed in https://github.com/rook/rook/issues/4037

**Comment by onedr0p** [comment]
This is an excellent idea for the reasons you mentioned.
