### ISSUE TITLE
Branch v0.4.0 into a release-0.4 branch for easy creation of patch releases

### ISSUE THREAD

**Issue by luxas** [rook/rook#662]
So you can target v0.5@HEAD but still provide v0.4.x versions easily.

Also, it would be beneficial to lock the versions in the yaml files to the latest of the given branch, so that 
```console
$ curl -sSL kubectl apply -f https://raw.githubusercontent.com/rook/rook/release-0.4/demo/kubernetes/rook-operator.yaml
```
would return `quay.io/rook/rookd:v0.4.x` in the image field. Before every new patch release these numbers would be bumped to `v0.4.x+1`. At master, the tag would always be `master-latest`

@bassam ^

**Comment by webwurst** [comment]
@luxas i think there's a typo in the title -> `release-0.4 branch`

**Comment by luxas** [comment]
@webwurst Correct, indeed that was a typo ;)

@bassam ping ^

**Comment by bassam** [comment]
agree with the approach. However, we were thinking not to maintain release branches until beta.  Is this so that you can reference older yaml files? If so I'm happy to create 0.4 branch from the tag.

**Comment by luxas** [comment]
@bassam yes, for referencing the latest "stable" alpha version

**Comment by bassam** [comment]
ok. done. https://github.com/rook/rook/tree/release-0.4

**Comment by luxas** [comment]
The second request was to update the branch to reference v0.4.x images...

**Comment by bassam** [comment]
Oh right. I'll update. We obviously need more tooling around this - templating of the yaml.  I'll open a separate ticket for the tooling.

**Comment by bassam** [comment]
fixed.

**Comment by luxas** [comment]
Thanks! I'll update https://github.com/luxas/kubeadm-workshop to use these manifests now :clap:
