### ISSUE TITLE
Any chances of integrating with openshift ?

### ISSUE THREAD

**Issue by debianmaster** [rook/rook#664]
Can you help me integrate rook with openshift v3 ?
i'm trying to integrate but it does not seem to like rbac
i'm using k8s 1.5.2

```sh
$ oc create -f demo/kubernetes/rook-operator.yaml 
serviceaccount "rook-operator" created
unable to recognize "demo/kubernetes/rook-operator.yaml": no matches for rbac.authorization.k8s.io/, Kind=ClusterRole
unable to recognize "demo/kubernetes/rook-operator.yaml": no matches for rbac.authorization.k8s.io/, Kind=ClusterRoleBinding
unable to recognize "demo/kubernetes/rook-operator.yaml": no matches for apps/, Kind=Deployment
```

```sh
$ oc version
oc v3.6.0-alpha.1+46942ad
kubernetes v1.5.2+43a9be4
```

**Comment by travisn** [comment]
As seen in the [Quickstart](https://github.com/rook/rook/blob/master/Documentation/kubernetes.md#quickstart), Rook only supports Kubernetes 1.6. Is there an openshift plan to upgrade to k8s 1.6 soon?

**Comment by fire** [comment]
Openshift spent the last 4 months upgrading to 1.5. It's not going to upgrade for at least that long.

I looked into rook, but since rook is chasing versions, it doesn't seems to be viable to use.

**Comment by fire** [comment]
Actually, I looked into the apis, try removing ClusterRole, ClusterRoleBinding and switch the Deployment to using version `apiVersion: extensions/v1beta1`

**Comment by debianmaster** [comment]
in rook-operator.yaml & rook-cluster.yaml files ?

**Comment by travisn** [comment]
Yes, it should just be a matter of changes to the yaml. To see the complete list of changes where we converted to 1.6 see [this change](https://github.com/rook/rook/commit/59ffc06ad07e174640a1fdf8fb92ed91ce180900), or refer to the [demo files](https://github.com/rook/rook/tree/0554a83e3a3a0b3e176793d4ba4b7d14be97525d/demo/kubernetes) before that change.

**Comment by debianmaster** [comment]
```console
$ cd rook
$ git checkout  0554a83e3a3a0b3e176793d4ba4b7d14be97525d  #before kube1.6
$ oc new-project rook
project rook created
$ oc create -f demo/kubernetes/rook-operator.yaml 
deployment "rook-operator" created
$ oc get pods
NAME                            READY     STATUS    RESTARTS   AGE
rook-operator-393530897-dxhqn   1/1       Running   0          7h
$ oc create -f demo/kubernetes/rook-cluster.yaml 
error: unable to recognize "demo/kubernetes/rook-cluster.yaml": no matches for rook.io/, Kind=Cluster
```

I'm investigating more but want to update you with latest finding.

**Comment by debianmaster** [comment]
`error: unable to recognize "demo/kubernetes/rook-cluster.yaml": no matches for rook.io/, Kind=Cluster`

**Comment by travisn** [comment]
@debianmaster that error frequently happens if the rook-cluster.yaml is created too soon after the operator starts. Can you try creating it one more time in case that was the issue?

**Comment by debianmaster** [comment]
found the issue, openshift RBAC was blocking rook.  had to run these commands to get it to work.
```console
cd rook
git checkout  0554a83e3a3a0b3e176793d4ba4b7d14be97525d  #before kube1.6
oc new-project rook
oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:rook:default
oc adm policy add-scc-to-user anyuid -z default -n rook
oc adm policy add-scc-to-user privileged -z default -n rook
oc create -f demo/kubernetes/rook-operator.yaml
oc create -f demo/kubernetes/rook-cluster.yaml
```

**Comment by debianmaster** [comment]
let me know if you want me to send a pull request to README  to make it work in Openshift

**Comment by debianmaster** [comment]
Now tried creating some storage
```sh
rook block create --name test --size 10485760
```
This is what i got in operator log.  Guessing deployment is using latest version of rookd docker image
```console
2017-05-09 08:44:27.018069 I | op-api: creating cluster role rook-api
2017-05-09 08:44:27.022739 E | operator: failed to create cluster rook in namespace rook. failed to start the REST api. failed to init RBAC for the api service. failed to create cluster roles. the server could not find the requested resource
```

Complete log
```sh
2017-05-09 08:44:26.841163 I | op-mon: start running mons
2017-05-09 08:44:26.861624 I | cephmon: parsing mon endpoints: mon0=172.17.0.3:6790,mon1=172.17.0.14:6790,mon2=172.17.0.15:6790
2017-05-09 08:44:26.861654 I | op-mon: loaded: maxMonID=2, mons=map[mon0:0xc42079d4a0 mon1:0xc42079d4e0 mon2:0xc42079d520]
2017-05-09 08:44:26.867077 I | cephmon: connecting to ceph cluster rook with user admin
2017-05-09 08:44:26.874617 I | cephmon: successfully connected to cluster rook with user admin
2017-05-09 08:44:26.879278 I | op-api: starting the Rook api
2017-05-09 08:44:26.925289 I | op-api: api service already running
2017-05-09 08:44:27.018069 I | op-api: creating cluster role rook-api
2017-05-09 08:44:27.022739 E | operator: failed to create cluster rook in namespace rook. failed to start the REST api. failed to init RBAC for the api service. failed to create cluster roles. the server could not find the requested resource
```

**Comment by travisn** [comment]
bah, forgot about those embedded rbac permissions. We would need to make a code change to ignore that failure. In the meantime can you try using this tag `v0.3.1-105-ga19b5f6` instead of `master-latest` or `v0.4.0`? That tag was just the day before the release when that change was added.

**Comment by debianmaster** [comment]
trying `v0.3.1-105-ga19b5f6`

**Comment by travisn** [comment]
and you'll need that tag both in rook-operator.yaml and rook-cluster.yaml

**Comment by debianmaster** [comment]
Tried, did not work, seeing same RBAC error which were seen before.

branch `v0.3.1-105-ga19b5f6`  has many references to rbac  
for example:-  
`apiGroup: rbac.authorization.k8s.io`
`apiVersion: rbac.authorization.k8s.io/v1beta1`
is there any other branch i can try?

**Comment by travisn** [comment]
i was thinking you could use the same yaml files that you used to get the operator working, but in those yamls use the tag such as in rook-operator.yaml:
```
image: quay.io/rook/rookd: v0.3.1-105-ga19b5f6
```
and in rook-cluster.yaml:
```
versionTag: v0.3.1-105-ga19b5f6
```
Is that what you did? I'm surprised you would still see the rbac references.

**Comment by travisn** [comment]
btw you could also join our Gitter for more discussion. https://gitter.im/rook/rook

**Comment by debianmaster** [comment]
joining..

**Comment by debianmaster** [comment]
all the rook related items seem to work now.  i have documented exact steps here if anyone is interested  
https://github.com/debianmaster/openshift-examples/blob/master/rook/README.md

I'm struck on this error on openshift, may not be hook.io issue.  checking with openshift origin.
`Output: mount: unknown filesystem type 'ceph'`

**Comment by jbw976** [comment]
That may mean that the Kernel doesn't have the CephFS module built in.  It's needed when Rook tries to mount CephFS locally: http://docs.ceph.com/docs/jewel/cephfs/kernel/

What type of Kernel do these machines have?

**Comment by debianmaster** [comment]
@jbw976  thats my ignorance :)  i'm running on mac.  so its expected.    i'm going to try on CentOs

**Comment by debianmaster** [comment]
so i was able to successfully use storage w/  k8s-registry example listed in `rook`
I'm now getting error when creating more than one filesystems.

```sh
rook filesystem create --name testFS
successfully created
[root@ip-172-31-43-133 kubernetes]# rook filesystem create --name testF1
failed to create new file system '{Name:testF1 PoolName:testF1}': HTTP status code 500 for query filesystem: ''
```

**Comment by jbw976** [comment]
The error that the API server pod is seeing can be difficult to diagnose sometimes: `cephd: Invalid argument`

Was a shared filesystem already created with that name previously?  What's does this output:
```
rook filesystem ls
```

**Comment by debianmaster** [comment]
yes, will it allow only one filesystem?

**Comment by jbw976** [comment]
The Ceph docs are still showing that multiple CephFS filesystems in the cluster are currently an experimental feature: http://docs.ceph.com/docs/master/cephfs/experimental-features/#multi-mds-filesystem-clusters

That may be a bit out of date, but I believe there'd be some more work on the Rook side too to enable it: #231

**Comment by travisn** [comment]
@debianmaster with #670 merged now, is there anything remaining with this issue? By using the yaml files in the `demo/kubernetes/1.5` folder, and the `master-latest` tag it should basically work now.

**Comment by debianmaster** [comment]
`master-latest`   you sure about this?  did a quick try now,   everything except `rook-api`  got deployed.   investigating more.   i will send you my testing results day after tomorrow (currently in travel).

**Comment by debianmaster** [comment]
i will give a try with `v0.4.0-21-g5d619aa`   tag   on docker images

**Comment by debianmaster** [comment]
when tried with `v0.4.0-21-g5d619aa`  
1. Install is successfull.  
2. PVC claim is successfully
When actually mounting to a pod this is what i get

```sh
MountVolume.SetUp failed for volume "kubernetes.io/rbd/a17726a1-39d1-11e7-9025-02bd9be6a562-pvc-861e68b7-39d1-11e7-9025-02bd9be6a562" (spec.Name: "pvc-861e68b7-39d1-11e7-9025-02bd9be6a562") pod "a17726a1-39d1-11e7-9025-02bd9be6a562" (UID: "a17726a1-39d1-11e7-9025-02bd9be6a562") with: rbd: failed to modprobe rbd error:exit status 1
```   this in `default` namespace  w/  rook infra running under `rook` namespace


i have ceph-common installed.
I have tried to mount in both `rook` and `default` namespace.
In  `rook` namespace mount is timed out.

**Comment by jbw976** [comment]
It appears the RBD plug-in failed while trying to `modprobe` the RBD kernel module: `rbd: failed to modprobe rbd error:exit status 1`

Remind me again how the Kubelet is run in openshift?  Would the Kubelet have access to `modprobe` and `/lib/modules`?

Also feel free to direct message me (@jbw976), @travisn, or @kokhang connection information for your openshift cluster and we'd be happy to dig into it while you are traveling.

**Comment by bassam** [comment]
can this be closed now?

**Comment by debianmaster** [comment]
closed !   thanks for your help
