### ISSUE TITLE
Update snapshotterVersion from v2.1.0 to v3.0.0

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#6640]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behaviour:**
Currently, the integration test uses snapshotterVersion v2.1.0 [here](https://github.com/rook/rook/blob/master/tests/framework/utils/snapshot.go#L28)

**Expected behaviour:**
 It's expected to use snapshotterVersion v3.0.0 as seen [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L52).

**Comment by leseb** [comment]
I think you mean here: https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L51
