### ISSUE TITLE
I want to specify the node of the scheduling destination for all pods deployed in operator.yaml.

### ISSUE THREAD

**Issue by vdi-kakui** [rook/rook#6645]
I was able to deploy the Discover pod on the specified storage node by making the following settings in operator.yaml.

```
        # (Optional) Discover Agent NodeAffinity.
        - name: DISCOVER_AGENT_NODE_AFFINITY
          value: "role=storage"
```

```
  rook-ceph                   rook-discover-29qtt                                                0 (0%)        0 (0%)      0 (0%)      
```

I also want to deploy other operator-pods (csi-cephfsplugin / provider, csi-ebdplugin / provider) on the specified storage node. What yaml should I write?

**Comment by sp98** [comment]
check the `[placement](https://github.com/rook/rook/blob/26b575c2c6cdeec33f45c5b35cef856700fbf760/cluster/examples/kubernetes/ceph/cluster.yaml#L115-L133)` configuration in the cluster.yaml file.  That should help

**Comment by travisn** [comment]
@vdi-kakui Also check a new section in the [quickstart guide](https://rook.github.io/docs/rook/v1.5/ceph-quickstart.html#deploy-the-rook-operator) for the csi driver placement settings.

**Comment by vdi-kakui** [comment]
Thanks.

**Comment by sp98** [comment]
@vdi-kakui Rook slack channel https://slack.rook.io/ would be a good place for these questions and getting quicker responses.
