### ISSUE TITLE
Reinit list of OSD

### ISSUE THREAD

**Issue by osaffer** [rook/rook#6649]
Hi,

How may I reorganize my osd list ? 
How can I remove the destroyed OSD ? 
It is possible to reinit the sequence number ?

ceph osd df
ID  CLASS  WEIGHT   REWEIGHT  SIZE     RAW USE  DATA     OMAP     META      AVAIL    %USE   VAR   PGS  STATUS
 2    hdd  0.01949   1.00000   20 GiB  7.8 GiB  6.8 GiB  1.4 MiB  1023 MiB   12 GiB  38.96  1.01   52         up
 5    hdd  0.00980   1.00000   10 GiB  4.1 GiB  3.1 GiB  1.6 MiB  1022 MiB  5.9 GiB  41.32  1.07   25         up
 6    hdd  0.01949   1.00000   20 GiB  7.8 GiB  6.8 GiB  4.9 MiB  1019 MiB   12 GiB  39.20  1.02   50         up
 0    hdd  0.01949   1.00000   20 GiB  7.0 GiB  6.0 GiB  3.8 MiB  1020 MiB   13 GiB  35.05  0.91   45         up
 3    hdd  0.00980   1.00000   10 GiB  3.7 GiB  2.7 GiB  2.5 MiB  1022 MiB  6.3 GiB  36.71  0.95   21         up
 7    hdd  0.01949   1.00000   20 GiB  7.7 GiB  6.7 GiB  4.2 MiB  1020 MiB   12 GiB  38.43  1.00   47         up
 1    hdd  0.01949   1.00000   20 GiB  7.3 GiB  6.3 GiB  3.1 MiB  1021 MiB   13 GiB  36.53  0.95   49         up
 4    hdd  0.00980   1.00000   10 GiB  4.2 GiB  3.2 GiB  3.2 MiB  1021 MiB  5.8 GiB  42.38  1.10   22         up
 8    hdd  0.01949   1.00000   20 GiB  7.6 GiB  6.6 GiB  2.0 MiB  1022 MiB   12 GiB  38.12  0.99   48         up
15    hdd  0.00980   1.00000   10 GiB  4.3 GiB  3.3 GiB  1.2 MiB  1023 MiB  5.7 GiB  43.31  1.12   24         up
16    hdd  0.01949   1.00000   20 GiB  8.1 GiB  7.1 GiB  2.2 MiB  1022 MiB   12 GiB  40.33  1.04   48         up
17    hdd  0.01949   1.00000   20 GiB  7.5 GiB  6.5 GiB  3.4 MiB  1021 MiB   12 GiB  37.66  0.98   52         up
 **9               0         0      0 B      0 B      0 B      0 B       0 B      0 B      0     0    0  destroyed
10               0         0      0 B      0 B      0 B      0 B       0 B      0 B      0     0    0  destroyed
11               0         0      0 B      0 B      0 B      0 B       0 B      0 B      0     0    0  destroyed
12               0         0      0 B      0 B      0 B      0 B       0 B      0 B      0     0    0  destroyed
13               0         0      0 B      0 B      0 B      0 B       0 B      0 B      0     0    0  destroyed
14               0         0      0 B      0 B      0 B      0 B       0 B      0 B      0     0    0  destroyed**
                       TOTAL  200 GiB   77 GiB   65 GiB   33 MiB    12 GiB  123 GiB  38.61

Thank you very much

**Comment by osaffer** [comment]
ceph osd purge 9 --yes-i-really-mean-it
ceph osd purge 10 --yes-i-really-mean-it
ceph osd purge 11 --yes-i-really-mean-it
ceph osd purge 12 --yes-i-really-mean-it
ceph osd purge 13 --yes-i-really-mean-it
ceph osd purge 14 --yes-i-really-mean-it

**Comment by leseb** [comment]
You can re-org the list and remove destroyed id with `ceph osd rm <id>` if `purge` failed to do it.
Based on https://github.com/rook/rook/issues/6649#issuecomment-728908724 answer, closing this since the issue seems resolved.
