### ISSUE TITLE
ObjectBucketClaim is not properly created using 1.5.0: resource name may not be empty

### ISSUE THREAD

**Issue by acejam** [rook/rook#6650]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
`ObjectBucketClaim` is not properly created.

After creating an `ObjectBucketClaim` using v1.5.0, Rook operator begins to loop, repeatedly creating multiple Ceph users and attempting to create the same bucket over and over. Only the first create bucket call succeeds, the others throw 409 Conflicts. During this time, the operator is showing the following error:

```
2020-11-17 03:37:16.783858 I | op-bucket-prov: getting storage class ""
2020-11-17 03:37:16.783923 E | op-bucket-prov: error getting class "", retrying. resource name may not be empty
```
Of course, as shown in the reproduction steps below, a StorageClass does in fact exist prior to creating an `ObjectBucketClaim`.

**Expected behavior:**
An ObjectBucketClaim is properly created

**How to reproduce it (minimal and precise):**

1. Spin up the Rook operator using Helm chart v1.5.0
2. Create a `CephCluster` using YAML manifest from examples directory
3. Create a `CephObjectStore` with 2/1 EC
4. Create a `rook-ceph.ceph.rook.io/bucket` `StorageClass`
5. Create a `ObjectBucketClaim` with the `spec.bucketName` specified and `spec.storageClassName` pointing to the previously created `StorageClass` (`rook-ceph-bucket

This error happens during a fresh install of v1.5.0. When downgraded to v1.4.7 (after wiping everything, including CRD's) things work fine.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.1 LTS (Focal Fossa)
* Kernel (e.g. `uname -a`): `Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Bare Metal Dedicated Server using private LAN
* Rook version (use `rook version` inside of a Rook Pod): v1.5.0
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.5 (2c93eff00150f0cc5f106a559557a58d3d7b6f1f) octopus (stable)
* Kubernetes version (use `kubectl version`): v1.19.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare Metal via Kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by BlaineEXE** [comment]
@acejam it would be really helpful to have all of your object-related manifests so there is not guessing about what configurations you have set. Attaching files here is preferred over inline.

**Comment by BlaineEXE** [comment]
My steps on single-node k8s cluster:
1. create `cluster-test.yaml`
2. modify `object-ec.yaml` to be `failureDomain: osd`
3. apply `object-ec.yaml`
4. apply `storageclass-bucket-delete.yaml`
5. apply `object-bucket-claim-delete.yaml`

Things I notice:
- `E1117 21:56:00.014048       7 controller.go:197] error syncing 'default/ceph-delete-bucket': error composing bucket name: cannot define both bucketName and generateBucketName, requeuing` appears in the logs despite only `generateBucketName: ceph-bkt` being set in the manifest
- `kubectl describe objectbucketclaim ceph-delete-bucket`
  shows 
  ```
  Spec:
    Bucket Name:           ceph-bkt-0c4d1a1a-ad94-49f4-b71b-a1e0a8d4c0c3
    Generate Bucket Name:  ceph-bkt
    Storage Class Name:    rook-ceph-delete-bucket
  Status:
    Phase:  Pending
  Events:   <none>
  ```
- at some point, it seems as though the operator is setting the bucket name while still having the `generateBucketName` parameter be set, and this is causing some failures in the logs. This is still a different scenario than described by @acejam.

[manifests-and-logs.zip](https://github.com/rook/rook/files/5556533/manifests-and-logs.zip)

**Comment by BlaineEXE** [comment]
>How to reproduce it (minimal and precise):
>
>    Spin up the Rook operator using Helm chart v1.5.0
>   Create a CephCluster using YAML manifest from examples directory
>    Create a CephObjectStore with 2/1 EC
>    Create a rook-ceph.ceph.rook.io/bucket StorageClass
>    Create a ObjectBucketClaim with the spec.bucketName specified and spec.storageClassName pointing to the previously created StorageClass

Are you missing a step to create a bucket manually here in order to specify `spec.bucketName`? Are you also removing `spec.generateBucketName`?

**Comment by BlaineEXE** [comment]
Looking through this code, I see some things that are questionable. Starting with the function `initializeDeleteOrRevoke`. This function shouldn't need to exist. Why do we need to initialize the receiver based on information passed in as arguments to a function. I think this creates for code that is fragile and prone to these kinds of issues. I suspect that somewhere, the receiver's `p.setBucketName` isn't being called. Outside of fixing this bug, I would suggest that we can prevent issues like this from occurring in the future if we make a point to never set information in the receiver piecewise like we are doing with this code. We should just pass the object bucket struct around the code and use the `getBucketName` on it when we need the bucket name rather than having information stored in multiple places and having code that relies on devs to properly initialize a struct that shouldn't need to have that kind of piecewise information stored.

**Comment by BlaineEXE** [comment]
I created https://github.com/rook/rook/pull/6657 to explore this further with additional debugging.

**Comment by BlaineEXE** [comment]
I keep thinking about what Travis said in the huddle this morning. Why has behavior changed from 1.4 to 1.5 if the lib-bucket-provisioner hasn't changed in months? I want to also spin up a 1.4.7 cluster and observe what the cluster does around these OBCs.

**Comment by hjanuschka** [comment]
will there be a 1.5.x release for that?

**Comment by acejam** [comment]
Hi @BlaineEXE, I have attached my manifest and operator logs here. The Ceph docker image used to generate these logs is technically `ceph/daemon-base:latest-octopus` but the same results are returned with `ceph/ceph:v15.2.5`, which is what I normally use.

> Are you missing a step to create a bucket manually here in order to specify `spec.bucketName`? Are you also removing `spec.generateBucketName`?

I am only specifying `spec.bucketName`. This creates a bucket and a user with a keypair linked to the bucket, which is all I need.

I have noticed this issue happening once or twice on 1.4.7 recently, but it happens nearly 100% of the time with 1.5.1.
[rook-operator.zip](https://github.com/rook/rook/files/5619958/rook-operator.zip)

**Comment by BlaineEXE** [comment]
There is a fix at https://github.com/kube-object-storage/lib-bucket-provisioner/pull/198 which then needs incorporated into Rook via https://github.com/rook/rook/pull/6699. If all goes well, these fixes will probably make it into the next Rook release.
