### ISSUE TITLE
[ceph][1.5.0][olm] CSV Generation does not create correct RBAC Rules by default

### ISSUE THREAD

**Issue by RyuunoAelia** [rook/rook#6659]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After generating the CSV (using `make csv-ceph CSV_VERSION=1.5.0 CSV_PLATFORM=okd ROOK_OP_VERSION=rook/ceph:v1.5.0` ) and updating rook-ceph to 1.5.0 using OLM, attaching ceph volumes to pod was not working at all. After some debugging, the following log was found in the `csi-rbdplugin-provisioner` logs:
```
W1117 18:45:31.874621       1 trivial_handler.go:57] Error saving VolumeAttachment csi-da59f1c9718720b0bcef2aa540b11a896fbd31684178ffc2f458353bc2734433 as attached: volumeattachments.storage.k8s.io "csi-da59f1c9718720b0bcef2aa540b11a896fbd31684178ffc2f458353bc2734433" is forbidden: User "system:serviceaccount:rook-ceph:rook-csi-rbd-provisioner-sa" cannot patch resource "volumeattachments/status" in API group "storage.k8s.io" at the cluster scope
```
So the CSV was missing RBAC rules for `volumeattachments/status` manually modifying the ClusterRoles by adding this resource each time `volumeattachments` appeared fixed the issue.

Also adding `OLM_INCLUDE_CEPHFS_CSI="true" OLM_INCLUDE_RBD_CSI="true" OLM_INCLUDE_REPORTER="true"` to the make command creates the rules, but also duplicates CRDs in the CSV file.

My guess is that when CSI became the default and supported way to deploy rook-ceph, the generation of the CSV was not completely aligned and there are some leftovers.

**Expected behavior:**

The CSV should contain the correct RBAC rules for `volumeattachments/status` so that rook-ceph works out of the box when generating the CSV from sources using the default parameters.

**How to reproduce it (minimal and precise):**

* generate CSV using `make csv-ceph CSV_VERSION=1.5.0 CSV_PLATFORM=okd ROOK_OP_VERSION=rook/ceph:v1.5.0`
* see that the CSV does not contain RBAC rules for `volumesattachments/status`

**Comment by leseb** [comment]
To sum up, the "only" bug is on the duplication of CRDs but you're right it's probably time also to default CSI.

**Comment by leseb** [comment]
@RyuunoAelia which CRDs are duplicated?

**Comment by leseb** [comment]
FYI: I did not see any duplication.

**Comment by RyuunoAelia** [comment]
Here is a (partial) diff of the CSV:

 ```
spec:
   apiservicedefinitions: {}
   customresourcedefinitions:
     owned:
-    - kind: CephBlockPool
-      name: cephblockpools.ceph.rook.io
-      version: v1
-    - kind: CephClient
-      name: cephclients.ceph.rook.io
-      version: v1
-    - kind: CephCluster
-      name: cephclusters.ceph.rook.io
-      version: v1
-    - kind: CephFilesystem
-      name: cephfilesystems.ceph.rook.io
-      version: v1
-    - kind: CephNFS
-      name: cephnfses.ceph.rook.io
-      version: v1
-    - kind: CephObjectRealm
-      name: cephobjectrealms.ceph.rook.io
-      version: v1
-    - kind: CephObjectStore
-      name: cephobjectstores.ceph.rook.io
-      version: v1
-    - kind: CephObjectStoreUser
-      name: cephobjectstoreusers.ceph.rook.io
-      version: v1
-    - kind: CephObjectZoneGroup
-      name: cephobjectzonegroups.ceph.rook.io
-      version: v1
-    - kind: CephObjectZone
-      name: cephobjectzones.ceph.rook.io
-      version: v1
-    - kind: CephRBDMirror
-      name: cephrbdmirrors.ceph.rook.io
-      version: v1
     - kind: CephCluster
       name: cephclusters.ceph.rook.io
       version: v1
@@ -1439,8 +1140,6 @@
           verbs:
           - create
           - delete
-          - get
-          - update
         serviceAccountName: rook-ceph-system
       - rules:
         - apiGroups:
@@ -1657,12 +1356,6 @@
           - update
           - patch
         - apiGroups:
-          - storage.k8s.io
-          resources:
-          - volumeattachments/status
-          verbs:
-          - patch
-        - apiGroups:
           - ""
           resources:
           - nodes
@@ -1735,7 +1428,6 @@
           verbs:
           - get
           - list
-          - watch
         - apiGroups:
           - ""
           resources:
@@ -1768,12 +1460,6 @@
           - update
           - patch
         - apiGroups:
-          - storage.k8s.io
-          resources:
-          - volumeattachments/status
-          verbs:
-          - patch
-        - apiGroups:
           - ""
           resources:
           - nodes
[...]
```

**Comment by leseb** [comment]
Oh duplication **inside** the CSV, I thought duplication of the CRD files.

**Comment by leseb** [comment]
@RyuunoAelia please open a new issue for the duplication, thanks in advance.
