### ISSUE TITLE
ceph: support for luminous

### ISSUE THREAD

**Issue by bassam** [rook/rook#666]
In order to run recent builds of Ceph Luminous we have to bring in the ceph-mgr role. This role uses python modules which makes static linking of ceph more complicated. Ideally we would like to stay close to upstream Ceph with minimal changes, still be able to run small lean containers for Rook, and be able to configure and deploy the different roles with a great amount of flexibility.

Here's a sketch of an approach that could get us there:

- we continue to build ceph from our fork as we do, however instead of using libcephd we build the different daemons that we need (ceph-mon, ceph-osd, ceph-mds, radosgw, and ceph-mgr).
- the daemons will be built using our "externals" project and mostly statically link to enable running on small linux distributions like Alpine linux. some cmake changes will be needed to enable this in upstream ceph.
- rookd will no longer link in Ceph and instead run the required daemons as child processes. The rookd portion could do all the configuration necessary to setup the daemons as it does today. 
- our containers will contain rookd + ceph daemons + whatever else necessary. Target size is < 100MB compressed.

The biggest issues with this approach is rook standalone mode -- it would no longer be possible to distribute a single binary for `rookd`. Instead `rookd` in standalone mode would require a container runtime to be present and would launch the same containers used in kubernetes environments. This seems like a reasonabe tradeoff and most standalone environments support docker these days.

**Comment by jbw976** [comment]
When `rookd` is doing all the initialization/configuration work before ceph daemons can be run, how would it perform RADOS operations such as mon commands if libcephd is no longer linked in?  e.g., https://github.com/rook/rook/blob/master/pkg/cephmgr/cephd/cephd.go#L267

**Comment by bassam** [comment]
I think we would also link to librados.

**Comment by luxas** [comment]
I think requiring a container is a totally reasonable tradeoff. Just imagine the next time this happens (new runtime deps). Then you have to ask yourself this question again.

The less C, C++ and other code you link into your Go program the better. If you try to link everything in, you're probably have non-obvious issues to solve later with the Go runtime that may hold you back.
