### ISSUE TITLE
Mon pods not able to use image pull secrets

### ISSUE THREAD

**Issue by tareksha** [rook/rook#6673]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When a private docker registry is used and an image pull secret is specified in the chart, the mon pods fail to pull the image due to authentication issues. The reason is that mon and mon-canary pods do not use a custom service account like osd and other components but rather rely on the default service account which is not aware of the custom image pull secrets.

**Expected behavior:**
A service account for mon pods should exist and it should define image pull secrets like other service account in rook-ceph.

**How to reproduce it (minimal and precise):**
* Install rook-ceph and populate `imagePullSecrets` in values.yaml
* Define a CephCluster resource with a ceph/ceph image from a private docker registry
* mon pods will fail schedule with error _Failed to pull image ..._, with an authentication error that depends on the docker registry.

**Environment**:
Any kubernetes cluster installation

**Comment by travisn** [comment]
@tareqhs Does [this topic](https://rook.github.io/docs/rook/v1.5/k8s-pre-reqs.html#authenticated-docker-registries) help get it working? Generally, the rook-ceph namespace is solely for rook, so updating the default service account has been sufficient for the mons.

**Comment by tareqhs** [comment]
Hi @travisn AFAIK it is a best practice to fe define non-default service account for cudtomizations.I can make the chart modify default SA but I see two issues:
1. other components in rook already define service account and I try to keep it uniform
1. slightly confusing for a commom kubernetes developer

**Comment by travisn** [comment]
Agreed this would be an improvement. I'll comment on #6674 with more thoughts.

**Comment by travisn** [comment]
Reopening since the original fix has been reverted. See #7556 for more background.

**Comment by fzyzcjy** [comment]
Hi is there any updates?

**Comment by travisn** [comment]
Let's reopen this issue, agreed that using a non-default service account would still be preferred. There is just a related issue #10141 that we need to resolve first.

**Comment by parth-gr** [comment]
I guess this can be closed as we have #12786 for the tracker
