### ISSUE TITLE
Long Haul Tests - High level plan

### ISSUE THREAD

**Issue by dangula** [rook/rook#668]
This is high level test plan for  Rook Long haul testing

we want to run tests for and  extended period of time to validate reliability of storage provisioned by rook.  The intend of Long haul tests are going to measure reliability  and not performance. We will be monitoring the application and collecting metrics. The exact list of metrics  that will be measured is TBD at this point. 
 The plan is to run existing tests or portion of tests for extended periods of times ranging form a few hours to a week.  We may reuse existing test(and run them in a loop) or create new tests as needed. 
  We plan to use the existing e2e framework for long haul tests, but we are investigation load and performance testing tool as well. 
We will using existing monitoring provided by rook (https://github.com/rook/rook/blob/master/Documentation/k8s-monitoring.md) . Some metrics that will be monitored are up time rook and health of all rook components, ODS performance etc.

Here are a few sample long haul tests or block storage

Scenario 1 : Create a block storage and read/write to it for extended periods . 
	1. Create a block storage and mount it on a application (or pod in k8s)
	2. Write and read data to the block storage for expended period
	3. Monitor various metrics  metrics

Scenario 2:  Deploy application that uses block storage.
	1. Deploy mysql and work press app that provision and use a block storage
	2. Run the application and perform operations for extended period of time.

**Comment by dangula** [comment]
unlike functional end to end test were we are writing tests that run on any installation of rook - k8s or standalone. I feel like Long haul tests are harder to generalize, I am inclined to writing specific long haul test for specific platforms.

**Comment by bzub** [comment]
I'd be willing to lend hardware (computers + sata hdd/ssd drives) if there are any tests that should run on bare-metal. With a little work it's possible I could make such a test cluster available over the internet exposing a webhook or similar for automated test triggering. Let me know if I can help.

**Comment by bassam** [comment]
Are you planning on failing over pods while the tests are running?

**Comment by dangula** [comment]
Yes eventually, failing over and upgrading would be part/flavor of long haul testing.
