### ISSUE TITLE
Detect OSDs down more proactively to update PDBs during node drain

### ISSUE THREAD

**Issue by travisn** [rook/rook#6682]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
PDBs are only reconciled once a minute, and also would never be reconciled if the cephcluster [status check](https://github.com/rook/rook/blob/release-1.5/cluster/examples/kubernetes/ceph/cluster.yaml#L235) is disabled. This check should be decoupled from the status check and ideally be more responsive than every minute.

**Expected behavior:**
To follow up from [this comment](https://rook.github.io/docs/rook/v1.5/ceph-disaster-recovery.html#backing-up-and-restoring-a-cluster-based-on-pvcs-into-a-new-kubernetes-cluster), we need to decouple the triggering of PDB reconcile from the cephcluster status updates. 

Here was the original discussion... A potential design to trigger the pdb reconcile:
1. Watch for the OSD pods stopping
2. Watch for the cephcluster update
3. If the operator is reconciling the OSDs during a rook or ceph upgrade and restarting the OSDs, the pdbs should just have their default state with maxUnavailable=1. In other words, during upgrade let's not try to support node drains at the same time. I don't see the need to disallow them completely with maxUnavailable=0, but it's a possibility.
4. The reconciler would be waiting in a new goroutine for a signal.
   - Signaled by step 1 or 2
   - Signals would be ignored if step 3 is in progress. (This seems sufficient to address the concern about the pdbs being reconciled too often since osds shouldn't generally be restarting very often except during upgrades)

Alternatively, a simpler design may be to just periodically check (every ~30s by default) if any OSDs are down. This will also decouple the PDB updates from the cephcluster updates, which could actually be disabled by [this setting](https://github.com/rook/rook/blob/release-1.5/cluster/examples/kubernetes/ceph/cluster.yaml#L235) in the cluster CR.

**Comment by sp98** [comment]
Few things are tired this week:

1.  Watch for Nodes that are drained to trigger the reconcile:
    ```
if nodeOld.Spec !=  nodeNew.Spec:
      if nodeNew.Taint.Effect == NoScuedule:
          reconcile
```
This triggers reconcile when node is drained. But again not a good solution as the OSD pods would drain last and we might reconcile too soon.

2. Watch for only the Main PDB (maxUnavailable=1). This can be done by having a specific label for main PDB. 
   ```
if mainPDB.Status.PodDisruptionsAllowed == 0:
      reconcile
```
This should trigger reconcile only when first OSD goes down. 
 - Node is drained.
- One of the OSDs goes down in the drained node (having one or more OSDs)
- Drained OSD pod results in `PodDisruptionsAllowed` in the main PDB to become 0. 
- reconcile gets triggered.
- main PDB is deleted and blocking ones get created.
- drained failure domain info gets stored in the pdbStateMap. So Even if ceph is slow to detect pgs are not active+healthy in the first reconcile, [we still have the failure domain info stored that will cause reconcile every 30 seconds.](https://github.com/rook/rook/blob/54560250e92f8f7ee9fc774dfd410463119edc07/pkg/operator/ceph/disruption/clusterdisruption/reconcile.go#L194) 

3. I also like the alternative simpler design of waiting for 30 seconds, that you have proposed.

**Comment by travisn** [comment]
The more I think about this, the more I'm leaning towards the simple 30s periodic check.
- Draining/restarting nodes takes minutes, so waiting up to 30s for the reconcile is fine. 
- The time can be configurable in the cluster CR, 30s is just the default if not set
- This reconcile seems like it can run independently of the upgrades, no need to coordinate or disable the reconcile while upgrades are happening.
