### ISSUE TITLE
Discover / Ceph Agent should allow for annotations

### ISSUE THREAD

**Issue by DandyDeveloper** [rook/rook#6683]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
It looks like options have been added for all components to have annotations support but not the discover / agents: 

https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md#annotations-and-labels

https://github.com/rook/rook/blob/master/pkg/operator/ceph/agent/agent.go#L115

It would be nice to have this option. 

**What is use case behind this feature:**
We have a lot of nodes using with a discover pod which is spamming an excessively high amount of logs. We have a log aggregation system in place and it is consuming a ton of storage with relatively useless logs from the discover component. 

We can add an annotation to the DS to prevent the logs being scraped entirely, but right now this has to be done manually and cannot be done through the CRD. 

**Environment**:
Not relevant, but we're using Nautilus right now, so, if you can somehow retroactively apply this to some older versions, that'd be nice ;)!

**Comment by travisn** [comment]
@DandyDeveloper You could consider just disabling the discovery and agent daemons. In fact, as of Rook v1.5, the discovery daemon is now disabled by default (see [this doc](https://rook.github.io/docs/rook/v1.5/ceph-quickstart.html#deploy-the-rook-operator) on disabling it for an upgraded cluster). Is that sufficient, or do you still need it to be running?
