### ISSUE TITLE
How to access ceph-mon with Pod IP?

### ISSUE THREAD

**Issue by jc-lab** [rook/rook#6686]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**My purpose is** to use rook-ceph outside of cluster using SRV Host (Headless Service).

Inside the cluster for testing:

* Writing Cluster IP in mon_host in ceph.conf, it will work fine.
* But writing Pod IP in mon_host in ceph.conf, it will not works.
  - In this case, the error "send_auth_request get_initial_auth_request returned -2" is raised.

**Expected behavior:**

It should also work with PodIP. Why need a public-addr argument in ceph-mon?

**How to reproduce it (minimal and precise):**
I'll add it if necessary.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
spec:
  annotations:
    mon:
      cni.projectcalico.org/ipv4pools: '["k8s-rook-ceph-ip-pool"]'
    osd:
      cni.projectcalico.org/ipv4pools: '["k8s-rook-ceph-ip-pool"]'
```
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
```
rook: v1.5.0-alpha.0.26.g969225c
go: go1.13.8
```
* Storage backend version (e.g. for ceph do `ceph -v`):
```
ceph version 15.2.5 (2c93eff00150f0cc5f106a559557a58d3d7b6f1f) octopus (stable)
```
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On-premise
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
We need this `public-addr ` argument to advertised a different IP than the pod'IP. The Ceph mon uses sticky IPs, they own a record of their own IP address and that IP cannot change. Since the pod's IP can change on deployment restart we must advertise a sticky IP (the one from the Service).

Does that help?

Do you have SRV records for the monitors?

**Comment by jc-lab** [comment]
Thank you. I understanding a little. But can you explain why need sticky IPs?

Creating a headless service through a common label generates an SRV record. However, an error occurred in the authentication process because the record was created with Pod IP.

**Comment by leseb** [comment]
> Thank you. I understanding a little. But can you explain why need sticky IPs?

Well, I don't have all the background so I'd just say that this Ceph's design today.
Monitors must always have the same IP otherwise you need to create a new monitor.
It might be tight to the homemad-paxos implementation too.

> Creating a headless service through a common label generates an SRV record. However, an error occurred in the authentication process because the record was created with Pod IP.

Can't you create the record from the clusterIP instead?

**Comment by jc-lab** [comment]
Thank you!
Kubernetes does not support SRV Record over ClusterIP.

**Comment by leseb** [comment]
> Thank you!
> Kubernetes does not support SRV Record over ClusterIP.

That's too bad, do you know if they are any plans to support it?

**Comment by jc-lab** [comment]
#6688 
In order to access Cluster IP from the outside in K8s, will need this feature request.

**Comment by travisn** [comment]
Closing since the pod ip cannot be used for the mons. Following up on #6688.
