### ISSUE TITLE
I want to change the setting of pod that is placed in all nodes in node so that it is not placed in some nodes.

### ISSUE THREAD

**Issue by vdi-kakui** [rook/rook#6695]
I want to change the setting of pod that is placed in all nodes in node so that it is not placed in some nodes.

The types of pods placed on all nodes are as follows.

```
csi-cephfsplugin
csi-rbdplugin
rook-ceph-crashcollector
rook-ceph-osd-prepare
```

How can I set it so that it will not be placed on some nodes?
Also, does not place it cause technical problems?

**Comment by travisn** [comment]
@vdi-kakui The node affinity of all the rook and ceph daemons can be controlled. 
- [CSI node affinity](https://rook.github.io/docs/rook/v1.5/ceph-quickstart.html#deploy-the-rook-operator) is controlled by settings in operator.yaml
- rook-ceph-crashcollector: This daemon is only started on nodes where the ceph daemons are started by rook
- OSD: See the `osd` [placement settings](https://rook.github.io/docs/rook/v1.5/ceph-cluster-crd.html#placement-configuration-settings) in cluster.yaml.
