### ISSUE TITLE
Create new OSDs before checking whether existing OSDs need to be updated

### ISSUE THREAD

**Issue by travisn** [rook/rook#6716]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Create new OSDs before checking whether existing OSDs need to be updated. This will help the new OSDs be created sooner instead of waiting for the end of the reconcile loop.

**What is use case behind this feature:**
In large clusters it takes many minutes to add new OSDs when expanding the cluster. The operator should create new OSDs before checking whether existing OSDs need to be updated. This will help the new OSDs be created sooner instead of waiting for the end of the reconcile loop.

**Comment by BlaineEXE** [comment]
I think this is something I can pull of the to-do stack. I've spent a lot of time on the OSDs anyway. My first thoughts on this:

I don't think there are any parts of the prepare job that can be easily changed to yield faster results in the prepare phase. I think the OSD deployment update/create phase is the place where changes will have the largest effect. It should be relatively simple to list the existing OSD deployments and identify which OSDs already exist and therefore need to be updated (after non-existent OSD deployments are created).

I think there will be some complexity in deciding how we want to wait for OSD provisioning on nodes to complete while creating/updating deployments. While it might be most time-efficient for large clusters with nodes that have non-homogeneous disk layouts to keep a work queue of "create" OSDs and "update" OSDs, that seems like an edge case optimization. I would probably keep a list of "create" OSDs and a list of "update" OSDs, loop over the "create" list just as the code now does and only move on to the "update" list after (1) the "create" OSDs are already created and (2) all provision jobs are finished (and therefore all possible "update" OSDs have been determined).
