### ISSUE TITLE
S3 unavailabe during upgrade 1.3->1.4

### ISSUE THREAD

**Issue by dimm0** [rook/rook#6718]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
While the cluster is chubbing along upgrading our 4 ceph clusters with hundreds of OSDs from 1.3 to 1.4, S3 is unavailable because of https://github.com/rook/rook/pull/5942. The 3S RGW pods (which will be upgraded last I suppose) don't have this label, while operator keeps updating the service with it

**Expected behavior:**
S3 keeps working

**How to reproduce it (minimal and precise):**
Upgrade from 1.3 to 1.4

**Comment by travisn** [comment]
hmm, this was expected to be fixed by #5929 where the matchSelectors were not modified for any of the daemons with the new label introduced in #5909. The rgw daemon had the same fix as mons and other daemons, but certainly smells related...

**Comment by dimm0** [comment]
Not sure if you want to fix it, since 1.5 is current...
Manually adding the label to rgw deployment fixes it
