### ISSUE TITLE
 tcsetpgrp failed: Permission denied

### ISSUE THREAD

**Issue by kaydxh** [rook/rook#6732]
I  want to deploy ceph of object storage through using rook. 
I run the following command:
1. cd cluster/examples/kubernetes/ceph
2. kubectl create -f common.yaml
3.  kubectl create -f operator.yaml
4.  kubectl -n rook-ceph get pod
After that, the status of pod is CrashLoopBackOff,  then I  query log， showing this： [FATAL tini (8)] tcsetpgrp failed: Permission denied.
How can I slove it ?
Thanks

**Comment by leseb** [comment]
Please re-open using the provided template.

**Comment by kaydxh** [comment]
> Please re-open using the provided template.

Thanks,  which file is the provided template, can you give me the filepath in project rook?

**Comment by leseb** [comment]
@kaydxh when you open an issue, select between a "Bug" or a "Feature" type of issue. Click on "Bug" and the page will be fulfilled automatically, just complete it.
