### ISSUE TITLE
Slow snapshots after move from 1.3 alpha snapshots to 1.4.6 beta snapshots (an operation with the given Volume ID already exists)

### ISSUE THREAD

**Issue by mleklund** [rook/rook#6741]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After upgrade from 1.3 alpha snapshots to 1.4 beta snapshots, rook has trouble mounting the snapshot volumes.
Called for snapshot at 2020-11-25T21:22:27Z and the pod actually was able to start at 2020-11-25T21:35:25Z 

Snapshot pod describe result while failing:

```
Events:
  Type     Reason                  Age                   From                     Message
  ----     ------                  ----                  ----                     -------
  Warning  FailedScheduling        8m32s                 default-scheduler        persistentvolumeclaim "user-data-mysql-claim-dev" not found
  Warning  FailedScheduling        8m32s                 default-scheduler        persistentvolumeclaim "user-data-mysql-claim-dev" not found
  Warning  FailedScheduling        8m31s                 default-scheduler        0/8 nodes are available: 3 Insufficient cpu, 5 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               7m56s                 default-scheduler        Successfully assigned mysql/user-data-mysql-dev-0 to k8w02.phx.dealnews.net
  Normal   SuccessfulAttachVolume  7m56s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-851d710d-9e3a-4ed4-a085-a9ede9d332a0"
  Warning  FailedMount             5m53s                 kubelet                  Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[sql-initialize-volume tz-config default-token-9qbgc persistent-storage config-volume]: timed out waiting for the condition
  Warning  FailedMount             5m52s                 kubelet                  MountVolume.MountDevice failed for volume "pvc-851d710d-9e3a-4ed4-a085-a9ede9d332a0" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             102s (x9 over 5m52s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-851d710d-9e3a-4ed4-a085-a9ede9d332a0" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
  Warning  FailedMount             80s (x2 over 3m36s)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[config-volume sql-initialize-volume tz-config default-token-9qbgc persistent-storage]: timed out waiting for the condition
```

CSI logs while failing:

```
1125 21:23:07.139021   46119 util.go:226] kernel 4.19.106-coreos does not support required features
W1125 21:23:08.403054   46119 rbd_util.go:323] ID: 101204 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 access denied to Ceph MGR-based rbd commands on cluster ID (rook-ceph)
E1125 21:23:08.403128   46119 rbd_util.go:473] ID: 101204 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 task manager does not support flatten,image will be flattened once hardlimit is reached: an error (exit status 13) occurred while running ceph args: [rbd task add flatten replicapool/csi-vol-63d1f6ff-2f64-11eb-879b-b6eb818f5415 --id csi-rbd-node --keyfile=***stripped*** -m 10.132.119.111:6789,10.128.20.66:6789,10.142.91.69:6789]
E1125 21:25:07.762283   46119 nodeserver.go:141] ID: 101210 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:07.762346   46119 utils.go:163] ID: 101210 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:08.834703   46119 nodeserver.go:141] ID: 101213 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:08.834783   46119 utils.go:163] ID: 101213 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:10.989937   46119 nodeserver.go:141] ID: 101215 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:10.990023   46119 utils.go:163] ID: 101215 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:15.059101   46119 nodeserver.go:141] ID: 101217 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:15.059162   46119 utils.go:163] ID: 101217 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:23.108326   46119 nodeserver.go:141] ID: 101219 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:23.108404   46119 utils.go:163] ID: 101219 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:39.204879   46119 nodeserver.go:141] ID: 101223 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:25:39.204946   46119 utils.go:163] ID: 101223 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:26:11.352866   46119 nodeserver.go:141] ID: 101226 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:26:11.352968   46119 utils.go:163] ID: 101226 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:27:15.499356   46119 nodeserver.go:141] ID: 101229 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:27:15.499438   46119 utils.go:163] ID: 101229 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:29:17.572068   46119 nodeserver.go:141] ID: 101237 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:29:17.572148   46119 utils.go:163] ID: 101237 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:31:19.693283   46119 nodeserver.go:141] ID: 101243 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
E1125 21:31:19.693351   46119 utils.go:163] ID: 101243 Req-ID: 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415 already exists
```

node appeared to have the pvc mounted while failing, and the directory had valid data:

```
 ls -alh /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-851d710d-9e3a-4ed4-a085-a9ede9d332a0/globalmount/0001-0009-rook-ceph-0000000000000001-63d1f6ff-2f64-11eb-879b-b6eb818f5415
total 631M
drwxrwxrwx. 8 1001 1001 4.0K Nov 25 21:35 .
drwxr-x---. 3 root root 4.0K Nov 25 21:34 ..
-rw-r-----. 1 1001 1001   56 Nov 25 21:06 auto.cnf
-rw-r--r--. 1 1001 1001  490 Nov 25 20:41 backup-my.cnf
-rw-------. 1 1001 1001 1.7K Nov 25 21:06 ca-key.pem
-rw-r--r--. 1 1001 1001 1.1K Nov 25 21:06 ca.pem
-rw-r--r--. 1 1001 1001 1.1K Nov 25 21:06 client-cert.pem
-rw-------. 1 1001 1001 1.7K Nov 25 21:06 client-key.pem
-rw-r-----. 1 1001 1001 129M Nov 25 21:35 galera.cache
-rw-r-----. 1 1001 1001  117 Nov 25 21:35 grastate.dat
-rw-r-----. 1 1001 1001  170 Nov 25 21:35 gvwstate.dat
-rw-r--r--. 1 1001 1001  34K Nov 25 20:41 ib_buffer_pool
-rw-r-----. 1 1001 1001  48M Nov 25 21:35 ib_logfile0
-rw-r-----. 1 1001 1001  48M Nov 25 21:09 ib_logfile1
-rw-r--r--. 1 1001 1001 784K Nov 25 20:41 ib_lru_dump
-rw-r--r--. 1 1001 1001 290M Nov 25 21:35 ibdata1
-rw-r-----. 1 1001 1001  12M Nov 25 21:35 ibtmp1
drwxr-x---. 2 1001 1001 4.0K Nov 25 20:41 mysql
drwxr-x---. 2 1001 1001   20 Nov 25 20:41 percona
drwxr-x---. 2 1001 1001 8.0K Nov 25 20:41 performance_schema
-rw-------. 1 1001 1001 1.7K Nov 25 21:06 private_key.pem
-rw-r--r--. 1 1001 1001  452 Nov 25 21:06 public_key.pem
-rw-r--r--. 1 1001 1001 1.1K Nov 25 21:06 server-cert.pem
-rw-------. 1 1001 1001 1.7K Nov 25 21:06 server-key.pem
drwxr-x---. 2 1001 1001 8.0K Nov 25 20:41 sys
-rw-r-----. 1 1001 1001  177 Nov 25 21:35 user-data-mysql-dev-0-relay-bin.000001
-rw-r-----. 1 1001 1001   41 Nov 25 21:35 user-data-mysql-dev-0-relay-bin.index
-rw-r-----. 1 1001 1001    2 Nov 25 21:35 user-data-mysql-dev-0.pid
-rw-r-----. 1 1001 1001  154 Nov 25 21:06 user-data-mysql-replica-0-relay-bin.000001
-rw-r-----. 1 1001 1001  227 Nov 25 21:07 user-data-mysql-replica-0-relay-bin.000002
-rw-r-----. 1 1001 1001  45M Nov 25 21:22 user-data-mysql-replica-0-relay-bin.000003
-rw-r-----. 1 1001 1001  135 Nov 25 21:07 user-data-mysql-replica-0-relay-bin.index
-rw-r-----. 1 1001 1001    2 Nov 25 21:07 user-data-mysql-replica-0.pid
drwxr-x---. 2 1001 1001 8.0K Nov 25 21:07 user_data
-rw-r--r--. 1 1001 1001  143 Nov 25 21:35 version_info
drwxr-x---. 2 1001 1001   60 Nov 25 20:52 wsrep
-rw-------. 1 1001 1001 2.1K Nov 25 20:53 wsrep_recovery_verbose.BniFrL
-rw-------. 1 1001 1001 2.1K Nov 25 20:53 wsrep_recovery_verbose.Gky8ha
-rw-------. 1 1001 1001 2.1K Nov 25 20:55 wsrep_recovery_verbose.MqBPN2
-rw-------. 1 1001 1001 2.1K Nov 25 20:54 wsrep_recovery_verbose.adWC8g
-rw-------. 1 1001 1001 2.1K Nov 25 20:56 wsrep_recovery_verbose.fypzoU
-rw-------. 1 1001 1001 2.1K Nov 25 20:53 wsrep_recovery_verbose.rGSIxf
-rw-r-----. 1 1001 1001  30M Nov 25 21:35 xb_doublewrite
-rw-r--r--. 1 1001 1001   22 Nov 25 21:05 xtrabackup_binlog_info
-rw-r--r--. 1 1001 1001   22 Nov 25 21:05 xtrabackup_binlog_pos_innodb
-rw-r-----. 1 1001 1001  153 Nov 25 21:05 xtrabackup_checkpoints
-rw-r--r--. 1 1001 1001   47 Nov 25 20:53 xtrabackup_galera_info
-rw-r-----. 1 1001 1001   35 Nov 25 20:30 xtrabackup_host
-rw-r--r--. 1 1001 1001  479 Nov 25 20:52 xtrabackup_info
-rw-r--r--. 1 1001 1001 8.0M Nov 25 20:53 xtrabackup_logfile
-rw-r--r--. 1 1001 1001    1 Nov 25 21:05 xtrabackup_master_key_id
-rw-r--r--. 1 1001 1001    0 Nov 25 20:52 xtrabackup_slave_info
```

**Expected behavior:**
Rook should mount the snapshot volumes in a timely manor.

**How to reproduce it (minimal and precise):**
Attached yaml from pod/pvc source user-data-mysql-replica and the snapshot'd replica user-data-mysql-replica-0.
[cluster.yaml.txt](https://github.com/rook/rook/files/5631263/cluster.yaml.txt)
[csi-logs.txt](https://github.com/rook/rook/files/5631264/csi-logs.txt)
[dmesg.txt](https://github.com/rook/rook/files/5631265/dmesg.txt)
[operator-logs.txt](https://github.com/rook/rook/files/5631266/operator-logs.txt)
[snapshot-controller-logs.txt](https://github.com/rook/rook/files/5631267/snapshot-controller-logs.txt)
[user-data-mysql-replica-0.yaml.txt](https://github.com/rook/rook/files/5631301/user-data-mysql-replica-0.yaml.txt)
[user-data-mysql-dev-0.yaml.txt](https://github.com/rook/rook/files/5631276/user-data-mysql-dev-0.yaml.txt)

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2345.3.0
VERSION_ID=2345.3.0
BUILD_ID=2020-02-26-2211
PRETTY_NAME="Container Linux by CoreOS 2345.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

* Kernel (e.g. `uname -a`):
Linux k8w02 4.19.106-coreos #1 SMP Wed Feb 26 21:43:18 -00 2020 x86_64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz GenuineIntel GNU/Linux
* Cloud provider or hardware configuration:
bare metal dell poweredge M620 E5-2760 128G 

* Rook version (use `rook version` inside of a Rook Pod):
rook/ceph:v1.4.6

* Rook CSI versions:
quay.io/cephcsi/cephcsi:v3.1.1
quay.io/k8scsi/csi-attacher:v2.1.0
quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
quay.io/k8scsi/csi-provisioner:v1.6.0
quay.io/k8scsi/csi-resizer:v0.4.0
quay.io/k8scsi/csi-snapshotter:v2.1.1

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph/ceph:v15.2.4-20200630

* Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubeadm configured vanilla kubernetes

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
  cluster:
    id:     5660686e-762d-40e0-ad72-c02bacf75850
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum b,c,d (age 5w)
    mgr: a(active, since 5w)
    mds: cephfs:1 {0=cephfs-a=up:active} 1 up:standby-replay
    osd: 5 osds: 5 up (since 5w), 5 in (since 9M)

  task status:
    scrub status:
        mds.cephfs-a: idle
        mds.cephfs-b: idle

  data:
    pools:   4 pools, 97 pgs
    objects: 33.15k objects, 102 GiB
    usage:   315 GiB used, 4.1 TiB / 4.4 TiB avail
    pgs:     97 active+clean

  io:
    client:   15 KiB/s rd, 584 KiB/s wr, 2 op/s rd, 20 op/s wr

**Comment by mleklund** [comment]
I have this happening consistently on a cluster that we can use for debugging if needed.

**Comment by Madhu-1** [comment]
@mleklund with the new RBD snapshot and clone new design we added support to keep snapshot and pvc independent of each other `4.19.106` kernel doesn't support the mapping of rbd image with flattening feature. so to support the lower kernel version we first try to flatten the image first to remove the `deep-flatten` image feature on the image, flattening also depends on the size of data you have in your rbd image. https://github.com/rook/rook/pull/6765 will add permission to node user to add flatten task but that would not solve the issue, to take complete support of rbd clones and snapshot you need to have 5.1.0+ kernel

**Comment by Madhu-1** [comment]
if your kennel supports the mapping of rbd images with the deep-flatten image feature please let us know we will add it to the supported kernel list here https://github.com/ceph/ceph-csi/blob/11e1eda98b7b0850b92237825234a71525e61e41/internal/rbd/nodeserver.go#L73-L93

**Comment by Madhu-1** [comment]
can you please provide complete rbdplugin logs from the node, I want to see which command is hanging. cephcsi will return an operation already exists error if some command is still going on.

**Comment by mleklund** [comment]
Is the attached file csi-logs.txt not the rbdplugin logs?  Is there a kernel list, all I saw in the docs was [this](https://rook.io/docs/rook/v1.5/ceph-prerequisites.html#rbd) which mentions 4.17 for rookfs and the need for the rbd module, which is installed.

```
rbd                    81920  2
libceph               307200  2 ceph,rbd
```

I do plan a OS update, but am behind since the RedHat CoreOS acquisition.  I have been running through the merits of Fedora CoreOS vs Flatcar, but have not made a final decision yet.

**Comment by mleklund** [comment]
> if your kennel supports the mapping of rbd images with the deep-flatten image feature please let us know we will add it to the supported kernel list here https://github.com/ceph/ceph-csi/blob/11e1eda98b7b0850b92237825234a71525e61e41/internal/rbd/nodeserver.go#L73-L93

Is there any way to dump the rbd capabilities of my kernel module?

**Comment by Madhu-1** [comment]
> attached file csi-logs.txt not the rbdplugin logs? Is there a kernel list, all I saw in the docs was [this](https://rook.io/docs/rook/v1.5/ceph-prerequisites.html#rbd) which mentions 4.17 for rookfs and the need for the rbd mod

The attached log is not complete, the rook prereq is only for cephfs, for RBD everything work but it would be slow

**Comment by Madhu-1** [comment]
> > if your kennel supports the mapping of rbd images with the deep-flatten image feature please let us know we will add it to the supported kernel list here https://github.com/ceph/ceph-csi/blob/11e1eda98b7b0850b92237825234a71525e61e41/internal/rbd/nodeserver.go#L73-L93
> 
> Is there any way to dump the rbd capabilities of my kernel module?

no am not sure about the list

**Comment by mleklund** [comment]
> > attached file csi-logs.txt not the rbdplugin logs? Is there a kernel list, all I saw in the docs was [this](https://rook.io/docs/rook/v1.5/ceph-prerequisites.html#rbd) which mentions 4.17 for rookfs and the need for the rbd mod
> 
> The attached log is not complete, the rook prereq is only for cephfs, for RBD everything work but it would be slow

What pod specifically do you need logs from?  The csi-logs.txt is the complete log for the csi-rbdplugin container in the  csi-rbdplugin-gws76 pod which is running on the node which the snapshot was mounted.  Do you need all csi-rbdplugin container logs?  All csi-rbdplugin-XXXX pod logs?  All csi-cephfsplugin-provisioner-XXX logs?

**Comment by mleklund** [comment]
Just to update.  This ended up being a kernel version issue.  Once I upgraded to a 5.x kernel the problem went away.
