### ISSUE TITLE
rename Rook client tool to rookctl

### ISSUE THREAD

**Issue by travisn** [rook/rook#675]
The Rook client tool is currently named `rook`. It should be renamed to `rookctl` to follow the pattern of similar tools such as `kubectl`.

**Comment by bassam** [comment]
note that we might have to remove `main.go` in the root of the tree too. this was added to support `got get GitHub.com/rook/rook`

**Comment by travisn** [comment]
I'd propose these name changes:
- Command line tool: `rook` --> `rookctl`
- Container: `quay.io/rook/rook` --> `quay.io/rook/rookctl`
- Pod: `rook-client.yaml` (unchanged... this seems more consistent with other pod names than rookctl.yaml)

**Comment by bassam** [comment]
it might best to do this after #666 is merged.

**Comment by travisn** [comment]
sure, will wait on it to avoid merge conflicts

**Comment by travisn** [comment]
Included with #700
