### ISSUE TITLE
Unable to bring Mgr, prepare OSD and OSD pods

### ISSUE THREAD

**Issue by Sabarish41** [rook/rook#6760]
Hello,

Unable to create cluster anyway. I'm having issues in creating OSD pods and bringing up "crash collectors".

[root@1000282107-ceph-test-m1 ceph]# kubectl get pod -n rook-ceph
NAME                                                                                                                                        READY   STATUS     RESTARTS   AGE
csi-cephfsplugin-kdpz6                                                                                                                  3/3     Running    0          13m
csi-cephfsplugin-ncjzn                                                                                                                   3/3     Running    0          13m
csi-cephfsplugin-provisioner-6748bb9646-75qjd                                                                      5/5     Running    0          13m
csi-cephfsplugin-provisioner-6748bb9646-bfk2s                                                                      5/5     Running    0          13m
csi-rbdplugin-9pnfl                                                                                                                         3/3     Running    0          13m  
csi-rbdplugin-provisioner-78db9f787f-22fzp                                                                              6/6     Running    0          13m
csi-rbdplugin-provisioner-78db9f787f-2hx44                                                                             6/6     Running    0          13m 
csi-rbdplugin-xp9df                                                                                                                        3/3     Running    0          13m 
rook-ceph-crashcollector-1000282107-ceph-test-w1-67864cb748wbbs                               0/1     Init:0/2   0          12m
rook-ceph-crashcollector-1000282107-ceph-test-w2-5474d5d956bqpn                               0/1     Init:0/2   0          9m54s
rook-ceph-mon-a-5bc86f7844-bjnm2                                                                                         1/1     Running    0          13m
rook-ceph-mon-d-7bb4dbb59c-2fbv8                                                                                         1/1     Running    0          9m54s 
rook-ceph-operator-8d9bf87c-jf8wv                                                                                            1/1     Running    0          13m 
rook-discover-4kwl7                                                                                                                        1/1     Running    0          13m
rook-discover-dkcjs                                                                                                                         1/1     Running    0          13m

**Comment by travisn** [comment]
You can ignore the crash collector pods for now. The critical issue is that the mons are not starting properly. See the [troubleshooting guide](https://rook.github.io/docs/rook/v1.5/ceph-common-issues.html#monitors-are-the-only-pods-running) for mons.

**Comment by Sabarish41** [comment]
Hi Travis,

Thanks for the quick response.
I have 2 nodes attached and for each I have specified 2 mons in cluster.yaml which seems working fine.
But the problem is I'm not able to see OSD's also.

Regards,
Sabarish S S

**Comment by travisn** [comment]
If you are not seeing a mgr or osd pod, it is because the mons are not healthy. Please review the troubleshooting guide linked previously.

**Comment by Sabarish41** [comment]
Hello Travisn,

I have now rectified monitoring issues but however I'm still unable to see my OSD's coming up. please help me on this topic below.

https://github.com/rook/rook/issues/6832

Regards,
Sabarish S S

**Comment by leseb** [comment]
@Sabarish41 do you have disks? Where is the issue now? If the issue remaining is in #6832 then we explained what to do there and closed it, so doing the same here.
Feel free to re-open if you have any concerns.

Thanks.
