### ISSUE TITLE
Syntax error on cluster.yaml file

### ISSUE THREAD

**Issue by tpaoletto** [rook/rook#6762]
We just tried to use the new 1.5.2 version of cluster.yaml file for rook/ceph cluster.
We noticed a difference between the previous version on line 96

https://github.com/rook/rook/blob/d7e761ec246dab7a666b5c7579bb3c6416c98d6d/cluster/examples/kubernetes/ceph/cluster.yaml#L96

This comment will make the whole file not usable for kubectl.
Please review the "cleanupPolicy" stanza.

**Comment by leseb** [comment]
Good catch...
