### ISSUE TITLE
Fresh Install with microk8s: /var/lib/kubelet - Missing Directories

### ISSUE THREAD

**Issue by Dennis360ict** [rook/rook#6772]
**Is this a bug report or feature request?**
* Bug Report

**Bug Report**
I experience the same behaviour as #4133, so the containers `csi-rbdplugin` and `csi-cephfsplugin` stay in the 'ContainerCreating' state and the pods describe `FailedMount`. The reasons I'm creating a new issue is because I think it's not a duplicate issue:
- I did not change ROOK_CSI_KUBELET_DIR_PATH and left the defaults in operator.yaml, like in #6543
- The same behaviour as #4133 applies, but as I understand this should already be fixed in the master branch, but even with the master branch I experience the same behavior. 

**Expected behavior:**
following the rook documentation should give me a working cluster. 

**Deviation from expected behavior:**
The cluster does not form and the containers `csi-rbdplugin` and `csi-cephfsplugin` stay in the 'ContainerCreating' state and the pods describe `FailedMount`.

**How to reproduce it (minimal and precise):**
I installed cleanly multiple times and can reproduce it by:
* installing 3 VMs 
* creating a microk8s ha cluster
* installing rook-ceph with master-branch and [following the documentation](https://rook.io/docs/rook/master/ceph-quickstart.html) 

Creation of the directories 
```
/var/lib/kubelet/plugins_registry
/var/lib/kubelet/pods
```
will get the cluster in a running state. 

**Are there any similar features already existing:** #4133 and #6543

**Environment**:
the behaviour on:
* hardware configuration: hypervisor KVM on Ubuntu with Dell XPS9380
* OS: 3 VMs fully patched (4th of dec 2020) with Ubuntu 20.04.1
* kernel: 5.4.0-56-generic
* Rook version: v1.5.0-alpha.0.153.g6aab4f7 (tried it with branches 1.4 and 1.5 too, same behaviour) 
* Storage backend version: Ceph 15.2.7
* Kubernetes cluster type: microk8s
* Kubernetes version: microk8s v1.19.3 with snapd
* snapd: snapd/focal-security,now 2.45.1+20.04.2 amd64
* snapd core: 16-2.48
* rook-ceph master branch cloned on 4 dec 2020 
* Storage backend status: HEALTH_OK

**Comment by Madhu-1** [comment]
Please check https://github.com/rook/rook/issues/6155#issuecomment-738786474 on configuration of kubelet path for microk8s

**Comment by Dennis360ict** [comment]
Yes I think that is exactly my issue. I overlooked it. I think this should be in the documentation? Like here:
https://rook.io/docs/rook/master/ceph-quickstart.html#cluster-environments
for 1.4, 1.5 and the master branch? Do you agree?

If u agree, I'm willing to do this, how should I proceed?

**Comment by Madhu-1** [comment]
@travisn any suggestion?

**Comment by Dennis360ict** [comment]
I found out the documentation is in the source, so I'll create a pull request and close the issue to minimize the open issues.
