### ISSUE TITLE
Can't create operator with cri-o

### ISSUE THREAD

**Issue by leiw324** [rook/rook#6783]
Hello,

I am trying cri-o with Kubernetes cluster (3 master and 3 worker)
![image](https://user-images.githubusercontent.com/33790160/101279428-23b12e80-37fd-11eb-9cff-2522adf0d221.png)

I did the following crio.conf to change the cgroup_manager to cgroupfs:
/etcf/crio/crio.conf

cgroup_manager = "cgroupfs"

And then I used "git clone https://github.com/rook/rook.git" to download rook, I did cd rook/cluster/examples/kubernetes/ceph/ and then "kubectl create -f common.yaml, but when I did "kubectl create -f operator.yaml " that the operator pod showing Running > Crashloopbackoff > Error.
![image](https://user-images.githubusercontent.com/33790160/101279449-48a5a180-37fd-11eb-9457-5e87162ae276.png)

Also, Flannel network installed

Now I can run cri-o:

![image](https://user-images.githubusercontent.com/33790160/101278831-05e1ca80-37f9-11eb-9f6d-3836818d2f64.png)

crictl version
Version: 0.1.0
RuntimeName: cri-o
RuntimeVersion: 1.17.5
RuntimeApiVersion: v1alpha1

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:15:05Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

CentOS 7.8:
[root@cri-o01 ceph]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

uname -a:
[root@cri-o01 ceph]# uname -a
Linux cri-o01 5.8.0-1.el7.elrepo.x86_64 #1 SMP Sun Aug 2 18:18:16 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

KVM for testing

Log:
![image](https://user-images.githubusercontent.com/33790160/101279562-092b8500-37fe-11eb-81ec-8cb4882706c1.png)

Thanks

**Comment by subhamkrai** [comment]
@leiw324 I see you are using rook 1.5.0, we need to do
`kubectl create -f crds.yaml -f common.yaml `then `kubectl create -f operator.yaml`.
see this https://rook.github.io/docs/rook/v1.5/ceph-quickstart.html#deploy-the-rook-operator.

**Comment by leiw324** [comment]
@subhamkrai my kubernetes version is V1.19.4, why I have to use CRDs?
do you mean I have cri-o so have to use CRDs?
Thanks

**Comment by subhamkrai** [comment]
> do you mean I have cri-o so have to use CRDs?

@leiw324  No, it seems to be a more hardware/resourcing issue I see a number of issues opened related to `Throttling request took`. I'm not very clear why this happening but I'm looking to this to understand more https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718

**Comment by travisn** [comment]
@leiw324 Did you create the crds.yaml? It is necessary for any rook cluster.

**Comment by leiw324** [comment]
Hello all,

Because the stuck on poweroff issue https://github.com/rook/rook/issues/7338 , so I was trying cri-o, if can fix stuck on poweroff , I no need to try cri-o.

Thanks
