### ISSUE TITLE
kubernetes log statements missing

### ISSUE THREAD

**Issue by jbw976** [rook/rook#679]
For example when we create and start the volume provision controller from the rook-operator, I would expect the `glog.Infof` statements to appear in the rook-operator logs as well.

Create and start the provision controller here:
https://github.com/rook/rook/blob/master/pkg/operator/operator.go#L118

It should log here:
https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L392

But I don't see that in the rook-operator logs at all, like for example in this log: https://gist.github.com/sonamsamdupkhangsar/7876f3da3a2aa9d6847c45367ee79771

Do we need to do some extra config to make `glog` statements in the Kubernetes API show up in the rook pod logs that call into it?

**Comment by jbw976** [comment]
This appears to be fixed nowadays, I see glog statements in the operator logs.  I'm not sure of a specific change that fixed it though, any ideas?

**Comment by travisn** [comment]
I saw the log statements when we moved to the k8s 1.8 client, but not sure what part of that update triggered the log statements

**Comment by jbw976** [comment]
Ah okay thanks @travisn, there were a lot of moving parts in the update to k8s 1.8 client.  I'm glad whatever it was in there fixed it though, it's useful to have k8s logging in our components too.  Closing this issue.
