### ISSUE TITLE
Ceph: can't access ceph dashboard

### ISSUE THREAD

**Issue by winson08Li** [rook/rook#6791]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When I setup a ceph cluster from scratch using Rook, Im not able to access the dashboard,

**Expected behavior:**
Be able to access dashboard using http through default port 7000

**How to reproduce it (minimal and precise):**
- kubectl create -f crds.yaml -f common.yaml
- kubectl create -f operator.yaml
- kubectl create -f cluster.yaml 
- wait until everything is ok
- curl `<mgr-pod-ip>`:7000/ceph-dashboard # exec on one of k8s nodes

Thre result is:
```
{"status": "404 Not Found", "detail": "The path '/ceph-dashboard' was not found.", "request_id": "59b8b63b-a880-46db-8284-2b5688b8497b"}
```

**File(s) to submit**:

`cluster.yaml`
```
...
dashboard:
    enabled: true
    urlPrefix: /ceph-dashboard
    ssl: false
...
```
Other content in `cluster.yaml`  just the same as default.

logs from mgr pod when I tried to access dashboard:
```
debug 2020-12-08T08:35:09.645+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v688: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
10.244.1.1 - - [08/Dec/2020:08:35:09] "GET / HTTP/1.1" 200 176 "" "kube-probe/1.19"
debug 2020-12-08T08:35:11.645+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v689: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
debug 2020-12-08T08:35:13.645+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v690: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
debug 2020-12-08T08:35:15.645+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v691: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
debug 2020-12-08T08:35:17.645+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v692: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
debug 2020-12-08T08:35:19.649+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v693: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
10.244.1.1 - - [08/Dec/2020:08:35:19] "GET / HTTP/1.1" 200 176 "" "kube-probe/1.19"
debug 2020-12-08T08:35:21.649+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v694: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
debug 2020-12-08T08:35:23.649+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v695: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
debug 2020-12-08T08:35:25.653+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v696: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
debug 2020-12-08T08:35:27.653+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v697: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
debug 2020-12-08T08:35:29.649+0000 7ffac37a2700  0 log_channel(cluster) log [DBG] : pgmap v698: 33 pgs: 33 active+clean; 0 B data, 7.7 MiB used, 347 GiB / 350 GiB avail
```

**Environment**:
* OS: Ubuntu 20.04
* Kernel (e.g. `uname -a`): 5.4.0-56-generic
* Rook version (use `rook version` inside of a Rook Pod): rook v1.5.3, go 1.13.8
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.7
* Kubernetes version (use `kubectl version`): v1.19.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubernetes on VMs provided by VMWare EXSi
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by winson08Li** [comment]
btw, I can successfully run the mysql.yaml and wordpress.yaml, means ceph functionality should be ok except the dashboard

**Comment by travisn** [comment]
@winson08Li Does it work for you with the default path if you don't specify the `url_prefix`?

**Comment by winson08Li** [comment]
@travisn I tried, without prefix and it's ok, why? I have to use prefix become I served ceph behind a reverse proxy.

**Comment by travisn** [comment]
Something must be going wrong with the prefix. Perhaps try it without leading `/`. Rook basically sets the ceph config property `mgr/dashboard/url_prefix`. You could experiment in the toolbox setting it to different values with something like:
```
ceph config set mgr.a mgr/dashboard/url_prefix <prefix>
```
Then restart the dashboard module (or the mgr pod)

**Comment by winson08Li** [comment]
I finally found wht's wrong, the correct url is `http://$IP:$PORT/$PREFIX/`, not `http://$IP:$PORT/$PREFIX`, it's documented on ceph official docs.

**Comment by Saigut** [comment]
> I finally found wht's wrong, the correct url is `http://$IP:$PORT/$PREFIX/`, not `http://$IP:$PORT/$PREFIX`, it's documented on [ceph official docs](https://docs.ceph.com/en/latest/mgr/dashboard/#configuring-a-url-prefix).

Oh, what a foolish design!
