### ISSUE TITLE
1.5.3: Operator loops forever over existing nodes

### ISSUE THREAD

**Issue by schantaraud** [rook/rook#6796]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Operator loops forever, trying to add already-added nodes to the cluster.

Apparently, the cause is that to list the OSDs on a host it runs `ceph osd crush ls [node name]` instead of `ceph osd crush ls [host name]` (not sure of the naming), and misinterprets the resulting `ENOENT` as "the node doesn't exist in the cluster" every time. As a consequence, it goes into an infinite loop of mgr and  osd-prepare jobs restarts every few seconds.

In my case:
```
[root@rook-ceph-tools-65b6bd4d5c-kf8n2 /]# ceph node ls osd
{
    "ip-y-y-y-y.ca-central-1.compute.internal": [
        3
    ],
    "ip-z-z-z-z.ca-central-1.compute.internal": [
        0
    ],
    "ip-w-w-w-w.ca-central-1.compute.internal": [
        2
    ],
    "ip-x-x-x-x.ca-central-1.compute.internal": [
        1
    ]
}
```
but (note the dashes instead of the dots):
```
[root@rook-ceph-tools-65b6bd4d5c-kf8n2 /]# ceph osd tree
ID   CLASS  WEIGHT   TYPE NAME                                                       STATUS  REWEIGHT  PRI-AFF
 -1         6.91199  root default
 -5         6.91199      region ca-central-1
-10         1.72800          zone ca-central-1a
 -9         1.72800              host ip-w-w-w-w-ca-central-1-compute-internal
  2    ssd  1.72800                  osd.2                                               up   1.00000  1.00000
-14         1.72800          zone ca-central-1b
-13         1.72800              host ip-x-x-x-x-ca-central-1-compute-internal
  1    ssd  1.72800                  osd.1                                               up   1.00000  1.00000
 -4         3.45599          zone ca-central-1d
-17         1.72800              host ip-y-y-y-y-ca-central-1-compute-internal
  3    ssd  1.72800                  osd.3                                               up   1.00000  1.00000
 -3         1.72800              host ip-z-z-z-z-ca-central-1-compute-internal
  0    ssd  1.72800                  osd.0                                               up   1.00000  1.00000
```

Operator's logs:
```
2020-12-08 20:10:20.818527 D | exec: Running command: ceph osd crush ls ip-x-x-x-x.ca-central-1.compute.internal --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/478049405
2020-12-08 20:10:21.203786 D | exec: Error ENOENT: node 'ip-x-x-x-x.ca-central-1.compute.internal' does not exist
.
2020-12-08 20:10:21.203879 I | ceph-cluster-controller: node watcher: adding node "ip-x-x-x-x.ca-central-1.compute.internal" to cluster "rook-ceph"
....
```

In the tools pod:
```
[root@rook-ceph-tools-65b6bd4d5c-kf8n2 /]#  ceph osd crush ls ip-x-x-x-x.ca-central-1.compute.internal
Error ENOENT: node 'ip-x-x-x-x.ca-central-1.compute.internal' does not exist
```
but (note the dashes instead of the dots):
```
[root@rook-ceph-tools-65b6bd4d5c-kf8n2 /]# ceph osd crush ls ip-x-x-x-x-ca-central-1-compute-internal
osd.1
```

In prior releases, the ENOENT was interpreted as an error and the process was aborted. Since #6768, it actually tries to re-sync the cluster every time. Downgrading to 1.5.1 fixes the issue.

**Expected behavior:**

Operator properly detects existing OSDs on all nodes.

**How to reproduce it (minimal and precise):**

Install Rook 1.5.3 and create a cluster with `useAllNodes: true` (Ceph 15.2.x).

**Environment**:
* OS (e.g. from /etc/os-release): Linux Ubuntu 
* Kernel (e.g. `uname -a`): 5.4.0-1021-aws
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod):  1.5.3
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.7
* Kubernetes version (use `kubectl version`): 1.18.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kops
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@shaas Can you take a look? This seems to be a regression from #6768. There have been several reports of this, we need to get a fix into the next patch release.
