### ISSUE TITLE
provide manifests to deploy an operator to manage multiple Ceph clusters where the operator has a separate namespace

### ISSUE THREAD

**Issue by fantastic2085** [rook/rook#6799]
**Is this a bug report or feature request?**
* Feature Request
Rook can provide a K8S to deploy an operator to manage multiple Ceph clusters, and the operator does not share the same namespace with multiple Ceph clusters

**What should the feature do:**
Rook itself provides for deploying one operator to manage multiple Ceph clusters in a K8S cluster, and that the operator is not in the same namespace as multiple Ceph clusters

**What is use case behind this feature:**
Most of the production environment, deploy a k8s clusters to manage the production environment, so impossible to deploy multiple Rook corresponding multiple Ceph cluster map, so I need a k8s cluster to deploy a Rook operator to manage multiple Ceph cluster, and operator with multiple Ceph cluster is not in the same namespace, only in this way can reduce the resource utilization rate, lower TCO for the user

**Environment**:

centos7.8.2003
k8s 1.18.8

**Comment by BlaineEXE** [comment]
(Updated the description to be shorter)

I think this feature can be accomplished by another feature we have talked about: procedurally generating the example manifests by using Helm. If it is easy for us to generate example manifests using Helm charts, it would also be easy for us to instruct users how to generate their own manifests using Helm that meet requirements they have like this one. In this way, we can have the provided example manifests provide the easy one-operator-one-cluster example that most users likely want, and for users with more advanced desires (like this request) can generate manifests for their use-case.

I think the difficulty for development may lie primarily in making sure that we can provide helpful upgrade instructions for an advanced case like this one.

**Comment by travisn** [comment]
@fantastic2085 I believe this is sufficiently addressed with @BlaineEXE 's changes in #6809. With those changes, see the documentation explaining how to [handle multiple namespaces](https://rook.github.io/docs/rook/v1.5/ceph-advanced-configuration.html#using-alternate-namespaces). Please try that and let us know if you see any issues with it. The changes are in v1.5.

**Comment by fantastic2085** [comment]
> @fantastic2085 I believe this is sufficiently addressed with @BlaineEXE 's changes in #6809. With those changes, see the documentation explaining how to [handle multiple namespaces](https://rook.github.io/docs/rook/v1.5/ceph-advanced-configuration.html#using-alternate-namespaces). Please try that and let us know if you see any issues with it. The changes are in v1.5.

Very happy to hear this and thank the community@travisn

**Comment by travisn** [comment]
@fantastic2085 Shall we close this issue, or is there any other suggestion you have for this feature?
