### ISSUE TITLE
Hybrid storage pools

### ISSUE THREAD

**Issue by SleepingShell** [rook/rook#6805]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Enable the ability to create hybrid storage pools that span across more than one ``deviceClass``. This would allow specification of how many replicas should exist on each medium type.

**What is use case behind this feature:**
Hybrid storage pools, so one can take advantage of the speed of faster storage mediums without sacrificing the raw storage capacity.

For example, take a node with 2xSSDs and 2xHDDs.

A ``CephBlockPool`` with 2 replicas could be created that specify one replica should always exist on an SSD, and one on a HDD. 100% of the SSD raw capacity would be usable. Read speed should be equal to the SSD, and write speed would be roughly equal to HDD.

Currently, with the above setup the only option (natively) is to sacrifice 50% of the SSD capacity by specifying a ``deviceClass``.

An example of this natively in Ceph can be seen here: https://www.root314.com/ceph/2017/04/30/Ceph-hybrid-storage-tiers/

**Environment**:

Rook-ceph deployed on a cluster with nodes that have more than one storage media type.

**Comment by SleepingShell** [comment]
Hi is this feature still being planned? I see it is tagged "dontfix" in the v1.6 milestones @sp98

**Comment by travisn** [comment]
yes, still a good feature, the stale bot just caught up with it

**Comment by sp98** [comment]
@SleepingShell  is the two step ceph ruleset mentioned in the doc still relevant.  

It uses some sort of storage tier to classify `ssd` and `hdd`.  For example `root-ssd` and `root-hdd` in the sample ruleset mentioned in the doc. 

```
# Hybrid storage policy
rule hybrid {
  ruleset 2
  type replicated
  min_size 1
  max_size 10
  step take root-ssd
  step chooseleaf firstn 1 type host
  step emit
  step take root-hdd
  step chooseleaf firstn -1 type host
  step emit
}
```
Can we use the device class (like below) instead?

```# Hybrid storage policy
rule hybrid {
  ruleset 2
  type replicated
  min_size 1
  max_size 10
  step take default class ssd
  step chooseleaf firstn 1 type host
  step emit
  step take default class hdd
  step chooseleaf firstn -1 type host
  step emit
}```

**Comment by travisn** [comment]
LGTM, just one suggestion... instead of the `Enabled` property, how about if the `HybridStorage` is nullable like this?
```
type ReplicatedSpec struct {
	...
	// HybridStorage represents hybrid storage tier settings
	HybridStorage *HybridStorageSpec `json:"hybridStorage,omitempty"`
}
```
