### ISSUE TITLE
Mon Pod anti-affinity does not work on k8s 1.6

### ISSUE THREAD

**Issue by sputnick** [rook/rook#681]
I'm having the issue that the Rook operator will schedule Mon pods all on the same host regardless of them having anti-pod-affinity rules. The reason is likely that their yaml is still using the alpha annotation for the anti-affinity but podAffinity is now a stable spec feature. 
See https://github.com/kubernetes/kubernetes/issues/44339

This needs to be taken into account (if not already) with improvements like
https://github.com/rook/rook/pull/680

I'm on kubeadm created 3 node kubernetes 1.6.1 cluster with latest Rook master version deployed using the demo/ instructions. I verified that the mons get created on the same host more than once by deleting the mon Pods and then the "mon-config" configmap to force the operator to recreate them.

**Comment by travisn** [comment]
This issue will actually be fixed today with #680. Good timing :)

**Comment by bassam** [comment]
can we add an integration test for this?

**Comment by travisn** [comment]
#680 includes a unit test for the mon anti-affinity that seems sufficient.
