### ISSUE TITLE
an operation with the given Volume ID pvc-f8374bc7-e221-4862-8952-7d8144b29199 already exists

### ISSUE THREAD

**Issue by shibumi** [rook/rook#6812]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I am going through the rook tutorials/documentation with an Rancher (v2.4.4) Cluster,
on CentOS 7 (with XFS as filesystem) and Kubernetes Version 1.17.14.

What worked fine:

* Installing rook via Helm in rook-ceph namespace
* Deploying a cluster with the example cluster.yaml in rook-ceph namespace
* Creating a storageclass with the following Yaml:

```yaml
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
    clusterID: rook-ceph
    pool: replicapool
    imageFormat: "2"
    imageFeatures: layering
    csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
    csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Delete
```

What did not work?

Deploying the example applications with block storage (wordpress and mysql) in default(!) namespace.

Events for pods:

```
  Warning  FailedScheduling  18m   default-scheduler  error while running "VolumeBinding" filter plugin for pod "wordpress-5b886cf59b-pd8lh": pod has unbound immediate PersistentVolumeClaims
```

Events for PVCs:

```
  Warning  ProvisioningFailed    16m                   rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-747ffd4b5-fbt4b_002bd53b-2fc4-4278-828d-5094fa6b34da  failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   Provisioning          2m42s (x12 over 18m)  rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-747ffd4b5-fbt4b_002bd53b-2fc4-4278-828d-5094fa6b34da  External provisioner is provisioning volume for claim "default/wp-pv-claim"
  Warning  ProvisioningFailed    2m42s (x11 over 16m)  rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-747ffd4b5-fbt4b_002bd53b-2fc4-4278-828d-5094fa6b34da  failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-f8374bc7-e221-4862-8952-7d8144b29199 already exists
  Normal   ExternalProvisioning  2m31s (x62 over 18m)  persistentvolume-controller                                                                                waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
```

**Expected behavior:**

The documentation should lead me to a working rook/ceph installation.

**File(s) to submit**:

I am not sure which files logs you want in this case. Please ask for them and I am happy to provide them.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): 3.10.0-1127.19.1.el7.x86_64 
* Cloud provider or hardware configuration: VMs running in VMWare
* Rook version (use `rook version` inside of a Rook Pod): v1.5.3 / go1.13.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.7 (88e41c6c49beb18add4fdb6b4326ca466d931db8) octopus (stable)
* Kubernetes version (use `kubectl version`): v1.17.14
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)

The `ceph health` error message could be a reason:

```
Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)
```

**Comment by travisn** [comment]
@shibumi Try the [troubleshooting guide](https://rook.github.io/docs/rook/v1.5/ceph-common-issues.html#pvcs-stay-in-pending-state), it may have some pointers. For example, what is the output of `ceph status` from the toolbox? But your error about the pv already existing doesn't seem to indicate an error in ceph.

**Comment by shibumi** [comment]
@travisn  Thanks. I will have a look at it tomorrow at work and will provide feedback here.

**Comment by shibumi** [comment]
@travisn `ceph status` gives the same error:

Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)

**Comment by shibumi** [comment]
I had a deeper look into this.. and looks like there is no ceph.conf being generated by rook.

**Comment by travisn** [comment]
@shibumi What pods do you have running? If the ceph.conf isn't being generated and the `ceph status` does not respond in the toolbox, the mons have likely not formed quorum. [This doc](https://rook.github.io/docs/rook/v1.5/ceph-common-issues.html#monitors-are-the-only-pods-running) may help give some clues.

**Comment by shibumi** [comment]
@travisn 

```
❯ k get po
NAME                                                              READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-8nqcd                                            3/3     Running     0          9m55s
csi-cephfsplugin-8zfm7                                            3/3     Running     0          9m55s
csi-cephfsplugin-provisioner-c68f789b8-8lxdk                      6/6     Running     0          9m55s
csi-cephfsplugin-provisioner-c68f789b8-qcqk2                      6/6     Running     0          9m55s
csi-cephfsplugin-x7t2s                                            3/3     Running     0          9m55s
csi-rbdplugin-k4fvm                                               3/3     Running     0          9m56s
csi-rbdplugin-npwxl                                               3/3     Running     0          9m56s
csi-rbdplugin-pfn55                                               3/3     Running     0          9m56s
csi-rbdplugin-provisioner-6c75466c49-9sr7j                        6/6     Running     0          9m56s
csi-rbdplugin-provisioner-6c75466c49-qk6gt                        6/6     Running     0          9m56s
rook-ceph-crashcollector-k8sworker1.avency.com-75f6bf4554-twkzr   1/1     Running     0          7m45s
rook-ceph-crashcollector-k8sworker2.avency.com-5689f8d7cf-mst84   1/1     Running     0          9m57s
rook-ceph-crashcollector-k8sworker3.avency.com-57466bbf66-r7bdx   1/1     Running     0          9m40s
rook-ceph-mgr-a-7cb5fb5756-f5ftw                                  1/1     Running     0          7m45s
rook-ceph-mon-a-784cf46f49-vxhlm                                  1/1     Running     0          10m
rook-ceph-mon-b-5945887f96-sf5sr                                  1/1     Running     0          9m41s
rook-ceph-mon-c-6577d8cf56-dfmj6                                  1/1     Running     0          8m11s
rook-ceph-operator-6898d5b69b-dcmcq                               1/1     Running     0          13m
rook-ceph-osd-prepare-k8sworker1.avency.com-rgc6x                 0/1     Completed   0          7m44s
rook-ceph-osd-prepare-k8sworker2.avency.com-v87kf                 0/1     Completed   0          7m44s
rook-ceph-osd-prepare-k8sworker3.avency.com-v8zt6                 0/1     Completed   0          7m44s
```

```
  Warning  ProvisioningFailed    17s                   rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6c75466c49-qk6gt_05f37b38-a177-4005-89b4-46e3ec261dd0  failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   ExternalProvisioning  12s (x12 over 2m47s)  persistentvolume-controller                                                                                 waiting for a volume to be created, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning          3s (x6 over 2m47s)    rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6c75466c49-qk6gt_05f37b38-a177-4005-89b4-46e3ec261dd0  External provisioner is provisioning volume for claim "rook-ceph/mongo-pvc"
  Warning  ProvisioningFailed    3s (x5 over 17s)      rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6c75466c49-qk6gt_05f37b38-a177-4005-89b4-46e3ec261dd0  failed to provision volume with StorageClas
```

I have no idea how to debug this. I am really just following your tutorial.

**Comment by travisn** [comment]
@shibumi Did you run `ceph status` in the [toolbox](https://rook.github.io/docs/rook/v1.5/ceph-toolbox.html)? It won't work in a different pod. I don't see the toolbox pod running in your cluster. It would appear that you don't have any OSD pods created. Try [this guide](https://rook.github.io/docs/rook/v1.5/ceph-common-issues.html#pvcs-stay-in-pending-state). These are necessary for the core storage, and the CSI driver will fail to provision a volume if there are no OSDs.

**Comment by shibumi** [comment]
@travisn  found the issue. The bug lies on my side. I thought rook/ceph is able to use a directory on the root filesystem as data store. With an unpartitioned attached disk it works as expected, the OSD pods come up and the ceph cluster get's in a healthy state :) Thanks for your help.
