### ISSUE TITLE
I get an error when deploying an existing snapshotclass.yaml.

### ISSUE THREAD

**Issue by vdi-kakui** [rook/rook#6819]
I get an error when deploying an existing snapshotclass.yaml.

I want to do cehp rbd shap shot.
However, when deploying an existing snapshotclass.yaml, the following error occurs.
What CRD do I need to deploy an existing snapshotclass.yaml?

```
error: unable to recognize "snapshotclass.yaml": no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1"
```

**Comment by travisn** [comment]
@vdi-kakui Did you see the prerequisites in the [Snapshot documentation](https://rook.github.io/docs/rook/v1.5/ceph-csi-snapshot.html)? I believe that will help you install the needed CRDs.

**Comment by Madhu-1** [comment]
>`Install the new snapshot controller and snapshot beta CRD. More info can be found here` 

@vdi-kakui check the second point in the doc https://rook.github.io/docs/rook/v1.5/ceph-csi-snapshot.html
snapshot is a CRD based operation, you need to create snapshot CRD and install snapshot controller more info can be found at https://github.com/kubernetes-csi/external-snapshotter/tree/master#usage

**Comment by venkatsc** [comment]
Looks like some clusters need `/v1beta1` instead of `/v1`. See [v1beta1 VolumeSnapshotClass](https://github.com/openebs/cstor-operators/blob/master/docs/tutorial/volumes/snapshot.md#note-in-some-cluster-like-openshiftocp-45-which-only-installs-the-v1beta1-version-of-volumesnapshotclass-as-supported-version-then-you-may-get-the-api-error-like)

**Comment by niconical** [comment]
You may need to install snapshot CRD and controller on K8S:

kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml

**Comment by ngangadhar-pki** [comment]
Thanks @niconical. This worked for me
