### ISSUE TITLE
Deleted files in pvc mount are not deleted in ceph cluster. 

### ISSUE THREAD

**Issue by karasjoh000** [rook/rook#6823]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Deleted a 8GB file in a rbd pvc mount but the respective objects are not deleted in ceph cluster. 
**Expected behavior:**
Ceph cluster removes objects associated with the 8GB file and frees up space. 
**How to reproduce it (minimal and precise):**

1. create an external ceph cluster in `rook-ceph` namespace
2. create a pool on external cluster
3. create a storage class and pvc
4. mount pvc to a pod and download some large iso file into the mount point
5. delete the downloaded file. Space frees up in mount point but not in ceph cluster. 

**Environment**:
* OS (e.g. from /etc/os-release): `centos 8`
* Kernel (e.g. `uname -a`): `4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): not sure how to find this. 
* Storage backend version `ceph version 15.2.5 (2c93eff00150f0cc5f106a559557a58d3d7b6f1f) octopus (stable)`
* Kubernetes version (use `kubectl version`):
```shell
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `kubespray`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

**Comment by travisn** [comment]
Please see [this related issue](https://github.com/rook/rook/issues/3832#issuecomment-530720966) for the explanation and how to resolve it.
