### ISSUE TITLE
mon_memory_target defaults to 2GiB, while the docs say that a 1GiB mon memory limit is fine

### ISSUE THREAD

**Issue by teozkr** [rook/rook#6826]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

`mon_memory_target` is left at Ceph's default of 2GiB, causing the mon to eventually crash with OOM errors if the `CephCluster` memory limit is lower.

**Expected behavior:**

`mon_memory_target` should be based on the mon pod memory limit. Alternately, the docs should mention that Ceph targets 2GiB by default.

See https://docs.ceph.com/en/latest/rados/configuration/mon-config-ref/#miscellaneous, https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html#cluster-wide-resources-configuration-settings

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): 5.6.6-1.el7.elrepo.x86_64
* Cloud provider or hardware configuration: VMware
* Rook version (use `rook version` inside of a Rook Pod): 1.5.1
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.5
* Kubernetes version (use `kubectl version`): 1.16.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by teozkr** [comment]
I have some vague memory of this kind of adjustment already being a thing for OSDs, but I can't find where now..

**Comment by BlaineEXE** [comment]
@travisn I would maybe make a doc fix for this. Thoughts?

**Comment by travisn** [comment]
@BlaineEXE Looks like we need a code change. Since there is a `mon_memory_target` setting in ceph, I'm assuming we need to set it to the memory limit in the cluster CR, if it's set.

**Comment by BlaineEXE** [comment]
I'm open to it, but I think there might be reasons not to do this. Notably, the `mon_memory_target` means the mons will target an amount of memory, but it doesn't prevent them from exceeding the value to my knowledge. It also doesn't account for the memory that mons free in order to keep below their target but that the kernel does not clean up. This memory will still be around until the kernel frees it, and we don't actually have a way to know how much memory might be used up in this way. We shouldn't be setting the pod memory limit to the same value as the `mon_memory_target` because of this.

I think the best thing to do is to request a change in Ceph where the mons adjust their target based on the `POD_MEMORY_LIMIT` and `POD_MEMORY_REQUEST` env vars as OSDs do. Ceph should also factor in an overhead for time waiting on the kernel to free mem and set Ceph's internal limit lower than the pod limits.

For follow-up: Do all Ceph daemons observe those env vars? Could this be an issue with memory becoming too large because the kernel takes time to clean up memory?

**Comment by travisn** [comment]
Good question about whether Ceph can adjust this automatically based on the env vars, similar to how the OSDs handle it. I am not aware of the other daemons having a similar behavior. 

On a related note, Rook sets `mds_cache_memory_limit` for the filesystem if the resource limits are applied.

**Comment by BlaineEXE** [comment]
Okay, so setting the limit for mons has precedent in Rook. I think we can do that code change, but I would suggest that we 
1) set `mon_memory_target` = `<k8s memory _Request_>` one-to-one
2) set `mon_memory_target` = `<k8s memory _Limit_>` - 500MB (for kernel freeing overhead)
3) choose the lowest of (1) or (2)

**Comment by teozkr** [comment]
> Okay, so setting the limit for mons has precedent in Rook. I think we can do that code change, but I would suggest that we
> 
>     1. set `mon_memory_target` = `<k8s memory _Request_>` one-to-one
> 
>     2. set `mon_memory_target` = `<k8s memory _Limit_>` - 500MB (for kernel freeing overhead)
> 
>     3. choose the lowest of (1) or (2)
> 
> 
> We could also do (2) as a percentage of the memory limit like `<limit> / 1.25` or something.

The idea seems sound, but it would be nice if the overhead would either be dynamic or configurable. 500MiB is a pretty wide margin for a tiny testing cluster..

**Comment by BlaineEXE** [comment]
I think setting a percentage may be a better option then. I would hope leaving 25% overhead between `mon_memory_target` and the pod memory limit would be sufficient. Though the mon node resource requirements SUSE recommends might suggest 50% would be safer.

**Comment by teozkr** [comment]
FWIW, I get the feeling that there is some kind of overhead accounting in Ceph mons already; when I changed our memory target (at runtime) from 2GiB to 1GiB, the memory usage dropped nearly instantly from ~1.3GiB to ~600MiB.

Of course, engineering-by-hunch is about as valuable in itself as security-by-lawyer, but it might be worth looking into..

**Comment by leseb** [comment]
Personally, I would just push this as a Ceph tracker bug and let the mon handle its own memory management, just like it does today. On the Rook side, a doc fix should be enough.

@teozkr would you mind opening a bug in https://tracker.ceph.com/? And link this issue, thanks!

@BlaineEXE @travisn thoughts?

**Comment by travisn** [comment]
Rook does already set `POD_MEMORY_REQUEST` and `POD_MEMORY_LIMIT` on all the daemon pods, including the mons. @leseb Agreed that given these vars, the mon should be able to manage its own memory similarly to the OSDs.

**Comment by BlaineEXE** [comment]
I think baking it into Ceph is the better idea. It's a difficult pattern to maintain if we have to identify all the mem tunables for all daemons in Rook. For now, users can set Ceph configs via the CLI/toolbox or via the override configmap pretty easily.
