### ISSUE TITLE
Better cleanup documentation

### ISSUE THREAD

**Issue by sputnick** [rook/rook#683]
This is more of an improvement request and a question than an issue...

First the question. Is there anything that needs to be removed on the Nodes to fully remove Rook created resources after cleaning up a Kubernetes cluster e.g. some /dev or configs etc?

Second some cleanup pointers. Having had to remove rook and reinstall a few times I've had to search for rook related resources to delete that aren't obvious to find.

This is what the documentation says today:

```
kubectl delete -f rook-operator.yaml
kubectl delete -n rook cluster rook
kubectl delete -n rook serviceaccount rook-api
kubectl delete clusterrole rook-api
kubectl delete clusterrolebinding rook-api
kubectl delete thirdpartyresources cluster.rook.io pool.rook.io
kubectl delete secret rook-rook-user
kubectl delete namespace rook
```
Possible improvements at least for K8s 1.6
- There is no clusterrole called "rook-api" it seems on my cluster (changed to rook-operator?)

- Use "kubectl delete -f " rather than direct deletes because the instructions use "create -f" i.e.

```
kubectl delete -f rook-cluster.yaml
kubectl delete -f rook-storageclass.yaml

```
- Try using kubectl to find any strays. I have found that there is almost always some lingering "terminating" OSD, Mon pods so that the "rook" namespace cannot be deleted. You can force delete them and then remove the rook namespace.
Look for stuff:

```
kubectl get pods,svc,thirdpartyresources,clusterroles,clusterrolebindings,cm,pv,pvc,daemonset,serviceaccounts,rs,deployments --all-namespaces -oyaml | grep rook -C 5
```
For lingering pods force delete them

```
kubectl delete pod "the mon pod names and lingering osd" --grace-period=0 --force
```
Then

```
kubectl delete namespace rook
```

**Comment by travisn** [comment]
@sputnick Good suggestions on improving the cleanup documentation, thanks.
By default there is nothing to clean up on the nodes. The two areas where cleanup is necessary is if you use the `dataDirHostPath`, which would leave the configuration directories on the host. The other area is when devices are used to store data. Rook doesn't do anything to clean that up.

The intention is to use `kubectl delete -f` where possible, but many of the resources are created dynamically by the operator so there isn't a yaml to delete declaratively. Once we've implemented the `delete` for a cluster, the operator can clean up all these automatically. There isn't an issue tracking this work yet though if you'd like to open it

**Comment by sputnick** [comment]
When you day "once we've implemented the delete for a cluster" do you mean 
rook delete <pool,cluster,block,filesystem,objectstorage>
Or do you mean the Operator watching for the deletion of PVC, PV and the third party resource "cluster"

**Comment by travisn** [comment]
i'm referring to `kubectl delete -f rook-cluster.yaml`. It does delete the TPR, but the operator doesn't yet implement cleaning up the cluster resources. And this is actually independent of the PVC, which should be cleaned up before the cluster is removed.

**Comment by travisn** [comment]
#1026 will help greatly with this

**Comment by travisn** [comment]
Closing since #1026 and #1303 will help with this
