### ISSUE TITLE
Be able to use the k8s 1.20 fsGroupPolicy option via rook options

### ISSUE THREAD

**Issue by dimm0** [rook/rook#6830]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Kubernetes 1.20 allows disabling files chown on request from CSI drivers. Rook has to configure this option in the CSI driver daemonset.

https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/

**What is use case behind this feature:**
Fixes https://github.com/rook/rook/issues/2254

**Comment by dimm0** [comment]
I still can't make it work... Is it supposed to be working according to https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/ ?

**Comment by leseb** [comment]
> I still can't make it work... Is it supposed to be working according to https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/ ?

Can you detail what is not working? Thanks

**Comment by dimm0** [comment]
I have:

```
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  creationTimestamp: "2020-02-25T01:42:24Z"
  name: rook-system.rbd.csi.ceph.com
  resourceVersion: "3191393526"
  uid: 88e98dd3-56d0-48c5-94de-8d1f37f001e8
spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: false
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
```

When I create a pod with:

```
  securityContext:
    fsGroup: 100
    fsGroupChangePolicy: "OnRootMismatch"
```

All files inside the RBD volume change the owner

k8s v1.21.5, rook v1.5.8

**Comment by leseb** [comment]
@Madhu-1 thoughts on this? ^

**Comment by Madhu-1** [comment]
@dimm0 you need to set fsGroupPolicy to none if you don't want the permission to be changed? csi driver is not the one who is doing this. this is done at the kubelet level.

**Comment by Madhu-1** [comment]
tagging @humblec as he is debugging the same issue

**Comment by dimm0** [comment]
I can’t see that redhat ticket…
I need the volume ownership changed to non-root user once, on first launch, so that the user could write to it. But after that no chown should happen for the files inside.
I see the feature going GA in the current release of k8s, so I’m not sure why I can’t make it to work in 1.21..

**Comment by dimm0** [comment]
👀

**Comment by travisn** [comment]
@humblec Any update on this issue?

**Comment by dimm0** [comment]
...

**Comment by Madhu-1** [comment]
The feature got added in https://github.com/rook/rook/pull/6875 closing this one as it's a request to support adding the feature. if something is not working as expected we can track it in a different issue.

**Comment by dimm0** [comment]
@Madhu-1 is `fsGroupChangePolicy: "OnRootMismatch"` possible with the current CSI driver?

**Comment by Madhu-1** [comment]
@dimm0 `fsGroupChangePolicy` is the pod security context, you can configure CSI driver with values specified here https://kubernetes-csi.github.io/docs/support-fsgroup.html#supported-modes

**Comment by dimm0** [comment]
If I need `fsGroupChangePolicy: "OnRootMismatch"` to work in the pod security context, do values in CSI driver matter?
I jsut upgraded rook to 1.8.10, and still can't acieve the "OnRootMismatch"

**Comment by Madhu-1** [comment]
> If I need `fsGroupChangePolicy: "OnRootMismatch"` to work in the pod security context, do values in CSI driver matter? I jsut upgraded rook to 1.8.10, and still can't acieve the "OnRootMismatch"

Please set the csi fsgroup to `File` and check. tagging @humblec as is having PR https://github.com/rook/rook/pull/10503, he can provide more details.

**Comment by Madhu-1** [comment]
> > If I need `fsGroupChangePolicy: "OnRootMismatch"` to work in the pod security context, do values in CSI driver matter? I jsut upgraded rook to 1.8.10, and still can't acieve the "OnRootMismatch"
> 
> Please set the csi fsgroup to `File` and check. tagging @humblec as is having PR #10503, he can provide more details.

Please give a try with latest cephcsi:canary image also as its having few fixes related to chmod and cephfs subvolume permission

**Comment by dimm0** [comment]
Sorry, can't really test on production cluster... I'll wait until it's resolved in stable version.
