### ISSUE TITLE
Move mon to other node in k8s

### ISSUE THREAD

**Issue by samsonhyt** [rook/rook#6835]
We have a ceph cluster up and running on k8s,
We want to move ceph mon to other nodes with certain label in the cluster,
Tried to add nodeAffinity to the cluster, But seems mon is bind to a node.
Is it possible for us the bring down mon and copy host data dir "/var/lib/rook" to new node and change the hostname and IP in rook-ceph-mon-endpoints

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
@samsonhyt The mon ip address cannot change. If you keep the mon service with the same clusterIP, you could stop the mon and move the /var/lib/rook to a new node if you change the metadata in the rook-ceph-mon-endpoints configmap. You have already added the mon placement to the CephCluster CR? If so, you could also just take one mon down and the operator will start a new mon and failover the old one after 10 minutes on a node that matches the new placement.

**Comment by samsonhyt** [comment]
@travisn Thanks, I changed the nodeAffinity and mon can failover to new nodes after 10 mins
