### ISSUE TITLE
Can not use a StorageClass with retainPolicy: Delete for Ceph RBD Volumes

### ISSUE THREAD

**Issue by partcyborg** [rook/rook#6846]
**Is this a bug report or feature request?**
* Bug Report

I have discovered that with the `csidriver` created by Rook Ceph for RBD volumes, StorageClasses with `retainPolicy: Delete` are not supported.

This is because Rook creates a `csidriver` that looks like this:
```
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  creationTimestamp: "2020-11-16T22:18:55Z"
  name: rook-ceph.rbd.csi.ceph.com
  resourceVersion: "29863968"
  selfLink: /apis/storage.k8s.io/v1beta1/csidrivers/rook-ceph.rbd.csi.ceph.com
  uid: 2c4f98ec-95ab-4d00-8c14-ad9604a21adf
spec:
  attachRequired: true
  podInfoOnMount: false
  volumeLifecycleModes:
  - Persistent
```

However, in Kubernetes versions >1.16, for retainPolicy: Delete to be supported, the `csidriver` needs to have the following instead:
```
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
```

If you create a StorageClass that sets retainPolicy: Delete without the `volumeLifecycleMode` `Ephemeral`, containers will be unable to mount subsequent volumes.

I verified that manually deleting and recreating the RBD `csidriver` with both `volumeLifecycleModes` fixes the issue.

**Deviation from expected behavior:**

Scheduling a pod with a PVC using a `StorageClass` with `retainPolicy: Delete` will fail in the `ContainerCreating` stage with the following message:

```
error while running "VolumeBinding" filter plugin for pod "<pod name>": pod has unbound immediate PersistentVolumeClaims
```

**Expected behavior:**

Pods should be created successfully.

**How to reproduce it (minimal and precise):**

1. Create a Ceph `Filesystem` or `BlockPool`
2. Create the appropriate `StorageClass` with retainPolicy: `Delete`
3. Create a Job or Deployment that uses a PVC with the above StorageClass

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CoreOS-stable-2512.3.0
* Kernel (e.g. `uname -a`): Linux <hostname redacted> 4.19.123-coreos #1 SMP Fri May 22 19:21:11 -00 2020 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
* Cloud provider or hardware configuration: Self hosted Kubernetes on AWS EC2
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.5.1
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph version 15.2.5 
* Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.6-1+a8884f7132317c", GitCommit:"a8884f7132317cb20416de61547de1bcc11f0756", GitTreeState:"clean", BuildDate:"2020-07-24T02:22:06Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Self hosted vanilla Kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by partcyborg** [comment]
Somehow I am now unable to reproduce this issue.

**Comment by Madhu-1** [comment]
`volumeLifecycleModes: Ephemeral` is not supported by cephcsi driver only `Persistent` is supported.
