### ISSUE TITLE
Ceph CSI encryption passphrase secret overwritten by operator

### ISSUE THREAD

**Issue by CrossRoast** [rook/rook#6848]
**Is this a bug report or feature request?**
* Bug Report (or could be a feature request, depending how you look at it)

**Deviation from expected behavior:**
When encryptionPassphrase key is added to rook-csi-rbd-node and rook-csi-rbd-provisioner secrets, after a short time the secrets are updated by the operator to remove it.

**Expected behavior:**
The encryptionPassphrase key remains in the secrets and is used by the CSI to provision volumes.

**How to reproduce it (minimal and precise):**

Launch a Rook Ceph cluster and create a storageclass with encryption: "true" as one of the parameters. Patch the automatically created rook-csi-rbd-node and rook-csi-rbd-provisioner secrets to include a passphrase for volume encryption.

**Environment**:
* OS (e.g. from /etc/os-release): centos 8
* Kernel (e.g. `uname -a`): 5.4.0-1029-aws #30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.5.1, go: go1.13.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.7 (88e41c6c49beb18add4fdb6b4326ca466d931db8) octopus (stable)
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-14T14:49:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kops on AWS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by CrossRoast** [comment]
I guess I can create new secrets for ceph credentials and include the encryption passphrase in them, but I'm not sure if these credentials are rotated by the operator. Regardless, it's much nicer when no manual intervention is required.

**Comment by Madhu-1** [comment]
>Patch the automatically created rook-csi-rbd-node and rook-csi-rbd-provisioner secrets to include a passphrase for volume encryption.

Rook will revert back/update any changes done to the cephcsi secrets it's creating. 

Rook is not using the cephcsi Encryption Feature for now. we are working on adding support for the encryption with  KMS   in rook.
If you want to use the cephcsi kubernetes secret-based encryption you need to create your own secretes and add an encryption key to the secret and create a new storageclass to use those secrets.

**Comment by Madhu-1** [comment]
This is not a bug in Rook.

**Comment by CrossRoast** [comment]
I see. Thanks you for the reply. I wasn't sure if this was a bug because it looks like design choice.

So, support of CSI volume encryption with just a passphrase will not be supported? Also, is it safe to create new secrets with the credentials from the automatically created ones? Are the credentials static or do they get rotated over time?

**Comment by Madhu-1** [comment]
> I see. Thanks you for the reply. I wasn't sure if this was a bug because it looks like design choice.
> 
> So, support of CSI volume encryption with just a passphrase will not be supported? 

Yes, it will be supported but it will be less secured as we are using a single passphrase to encrypt all the pvc provisioned from the same secret.

>Also, is it safe to create new secrets with the credentials from the automatically created ones? Are the credentials static or do they get rotated over time?

As you will be creating a new secret from the existing ceph users. it will be static and it won't be rotated.

**Comment by CrossRoast** [comment]
> As you will be creating a new secret from the existing ceph users. it will be static and it won't be rotated.

I meant I wasn't sure if the operator rotates the passwords of ceph users. After searching through the code, it looks like you use `ceph auth get-or-create-key` and I couldn't find any `ceph auth import` lines, so it looks like the users don't change.

Please, let me know if I'm wrong. For now, I'll close the issue since all my questions were answered and I was able to get the CSI to use volume encryption via a different secret.
