### ISSUE TITLE
helm lint error: object name does not conform to Kubernetes naming requirements: "psp:rook"

### ISSUE THREAD

**Issue by tskdsb** [rook/rook#6851]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
What I did:
```
helm repo add rook-release https://charts.rook.io/release
helm pull --untar rook-release/rook-ceph
helm lint rook-ceph
==> Linting rook-ceph
[ERROR] templates/clusterrole.yaml: object name does not conform to Kubernetes naming requirements: "psp:rook": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253
Error: 1 chart(s) linted, 1 chart(s) failed
```

**Expected behavior:**
lint successfully

**How to reproduce it (minimal and precise):**

helm lint the chart of version v1.5.3
helm version:
```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `v1.5.3` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
>helm lint
==> Linting .
[ERROR] templates/clusterrole.yaml: object name does not conform to Kubernetes naming requirements: "psp:rook": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253

This should have been caught with `helm lint` in CI itself. @travisn any plan to add GitHub action for helm lint?

**Comment by Madhu-1** [comment]
added helm lint GitHub action in https://github.com/rook/rook/pull/6868

**Comment by Madhu-1** [comment]
This is a helm lint bug helm/helm#9197 not related to rook. closing for the same reason. please feel free to reopen if its not.
