### ISSUE TITLE
External cluster doesn't auto recover after mon failover and doesn't update entries

### ISSUE THREAD

**Issue by electrical** [rook/rook#6861]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Mon failover happened on the storage cluster, production cluster didn't automatically recover.

**Expected behavior:**

Production cluster would pick up new mon entry and keep functioning fine.

**How to reproduce it (minimal and precise):**

I was testing behaviour of rook/ceph when things fail so my first test was deleting an OSD pod.
This caused some issues which might be related to https://github.com/rook/rook/issues/6530.
Thanks to the help of @travisn I was able to recover it.
Then I reviewed the status of my other cluster that connects to ceph using the external cluster functionality.
before the test I had mon's a,b & c. After the test I ended up with mon's b,c & d.
I expected the endpoint names to be updated ( ip's remained the same ) but It didn't do that.
I also received this error in the CephClusters CRD:
https://gist.github.com/electrical/de7abc0890dee70ea513ed3f52646706
It's still very unclear what caused this specific error but it caused the production cluster not to be able to connect to my storage cluster.

After talking to Travis i mentioned that the operator should pick up the changes automatically.
For testing I removed the 'a' mon entry from the config map and then it did detect that the mon 'd' was missing and added that to the config map.
Unfortunately it did result into 2 entries having the same IP address as it only added the missing entry and not replaced it.
After updating the entries the cluster state finally recovered.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 8
* Kernel (e.g. `uname -a`): 4.18.0-193.28.1.el8_2.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.5.2
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.7
* Kubernetes version (use `kubectl version`): 1.19.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare-metal

rook-ceph runs with ceph on a storage cluster ( 3 nodes )
Production cluster is also 3 nodes that connects to ceph using the external cluster functionality.

**Comment by leseb** [comment]
Can you share some operator's logs?

**Comment by electrical** [comment]
Unfortunately I don't have the full logs anymore. 
All relevant info is in a slack thread https://rook-io.slack.com/archives/CK9CF5H2R/p1608322408345900
it contains some of the log entries.
