### ISSUE TITLE
op-mon missing mon deployment takes a long time to recover

### ISSUE THREAD

**Issue by electrical** [rook/rook#6862]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Missing mon instance takes forever to be recreated

**Expected behavior:**

Mon instance gets recreated faster

**How to reproduce it (minimal and precise):**
Related to https://github.com/rook/rook/issues/6861

When recovering my storage cluster the mon instance on the node failed and I deleted the deployment.
The operator tries to recreate the mon deployments for each node but it started with mon-c deployment which it wasn't allowed to delete until it finally times out.
Since it did detect which mon instance was gone `ceph-spec: object "rook-ceph-mon-a" matched on delete, reconciling` I would expect it to be much faster.
At the moment it takes about 5 minutes for it to timeout before it moves on to the next one.
Eventually it gave up and decided to start mon-d on the same host.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 8
* Kernel (e.g. uname -a): 4.18.0-193.28.1.el8_2.x86_64
* Rook version (use rook version inside of a Rook Pod): 1.5.2
* Storage backend version (e.g. for ceph do ceph -v): 15.2.7
* Kubernetes version (use kubectl version): 1.19.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare-metal

**Comment by travisn** [comment]
@electrical Did you try deleting the mon pod first, or just the deployment? The pod should recover immediately, while the delay for re-creating the deployment is harder to fix. Restarting the operator would be a workaround to create the mon more quickly, if that helps.

**Comment by electrical** [comment]
Hi @travisn I can't remember exactly but I most likely deleted the deployment so it would recreate the deployment it self.
