### ISSUE TITLE
Host based OSDs fails to create if a PVC based OSD is already being orchestrated

### ISSUE THREAD

**Issue by paalkr** [rook/rook#6867]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When running with OSDs on both PVCs and host devices (which was support with https://github.com/rook/rook/pull/6822), orchestration of host devices stops if PVC OSDs are orchestrated at the same "round". I believe this issue https://github.com/rook/rook/issues/4124 is the root cause.

The prepare does run and creates the local disk bluestore, but orchestration does not create the OSD due to the above described problem. Restarting the operator does not help, it just skips the 

**Expected behavior:**
I would expect orchestration of both PVC and host OSDs to succesm without this error message from the operator
`2020-12-20 21:28:20.076439 I | ceph-cluster-controller: hot-plug cm watcher: skip orchestration on device config map update for OSDs on PVC`

**How to reproduce it (minimal and precise):**
On a 3 node K8s cluster with on PVC based and one host based OSD on each node. Terminate one node and let the cloud provider replace the node with a new node. The discover pod discovers the new node and creates a new configmap, but the operator does not react to the new configmap because a PVC OSD is already being "orchestrated".

**Environment**:
See this issue https://github.com/rook/rook/issues/6836

**Comment by travisn** [comment]
@paalkr This is working for you now, right? We must have missed closing the issue, unless I'm forgetting something else...

**Comment by paalkr** [comment]
Hi, I believe so. But testing has been a little hard because of https://github.com/rook/rook/issues/7462
