### ISSUE TITLE
Unable to access bucket creating by object-bucket-claim-delete.yaml

### ISSUE THREAD

**Issue by winson08Li** [rook/rook#6871]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When I setup a ceph cluster from scratch using Rook, I follow this link [ceph-object](https://rook.io/docs/rook/v1.5/ceph-object.html) to setup the object storage, but when I exec `s3cmd list s3://bucketName`, it says`SignatureDoesNotMatch`

**Expected behavior:**
Be able to list bucket content using `s3cmd list s3://bucketName`

**How to reproduce it (minimal and precise):**
- kubectl create -f crds.yaml -f common.yaml
- kubectl create -f operator.yaml
- kubectl create -f cluster.yaml 
- kubectl create -f csi/rbd/storageclass.yaml
- kubectl create -f object-ec.yaml
- kubectl create -f storageclass-bucket-delete.yaml
- kubectl create -f object-bucket-claim-delete.yaml
- setup s3cmd using `s3cmd --configure` with infomation getting from configmap and secret
- **exec `s3cmd list` success**
- exec `s3cmd list s3://bucketName`

Thre result is:
```
$ s3cmd ls s3://ceph-bkt-8bf35a1c-10af-4308-99a7-f8d0fccd25af
ERROR: S3 error: 403 (SignatureDoesNotMatch)
```

**File(s) to submit**:
`.s3cfg`
```
...
access_key = xxx
secret_key = xxx
host_base = ip:port
host_bucket = ip/bucketName
use_https = False
...
```

I didn't change anything in other files except the deviceFilter in `cluster.yaml`, to let Rook be able to find my disks.

logs from rgw pod:
```
debug 2020-12-21T17:21:09.075+0000 7fbb33446700  1 beast: 0x7fbba2dbf6b0: 10.244.0.0 - - [2020-12-21T17:21:09.075122+0000] "GET /ceph-bkt-8bf35a1c-10af-4308-99a7-f8d0fccd25af/?delimiter=%2F HTTP/1.1" 403 197 - - -
```

**Environment**:
* OS: Ubuntu 20.04
* Kernel (e.g. `uname -a`): 5.4.0-56-generic
* Rook version (use `rook version` inside of a Rook Pod): v1.5.0-alpha.0.221.g423bc31, go 1.13.8
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.8
* Kubernetes version (use `kubectl version`): v1.19.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubernetes on VMs provided by VMWare EXSi
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by leseb** [comment]
Can you run s3cmd with a debug level?
