### ISSUE TITLE
Ceph-CSI support for Windows worker nodes

### ISSUE THREAD

**Issue by Sabarish41** [rook/rook#6872]
Hello Team,

Its glad working on Rook-ceph and the tool really seems very promising.
However we are looking to maintain a similar solution for Windows kubernetes nodes.
Could you please help me unblocking the solution and provide windows images for Operator and cluster.

@travisn Could you please comment on the same if there is a possibility.

Regards,
Sabarish S S

**Comment by travisn** [comment]
@Sabarish41 Ceph support for Windows clients isn't there. Are you trying the recent [Windows driver](https://ceph.io/planet/suse-publishes-first-steps-towards-windows-clients/)? Even if you're trying the client driver or another client protocol such as iSCSI or CIFS, I don't anticipate Ceph itself will be supported on Windows anytime soon.

**Comment by rwanito** [comment]
Hi !
If I create a kubeadm cluster with rook, can I use Ceph inside 3 linux workers and 3 windows workers without any adds ?
Or, I need to install something like the link you gave (it's not production ready) ?

Or, how can I have a cluster with ceph with linux/windows with kubernetes ?
Thanks for your help !

**Comment by travisn** [comment]
There is a consideration for the CSI driver supporting Windows worker nodes in the K8s cluster, but not the core Ceph daemons. Reopening this to keep track of that effort, but the timeline for this feature is still unknown.

**Comment by themonaminor** [comment]
hi is there any solution to consume PVC backed by ceph on windows nodes?
is there any attcaher/driver/provisioner for windows nodes that will mount PVC to windows node
