### ISSUE TITLE
Rook needs to support the mips64le build

### ISSUE THREAD

**Issue by weisongf** [rook/rook#6874]
**Is this a bug report or feature request?**

* feature 

**What should the feature do:**

Rook needs to support the mix64le build.

We need to deploy ceph clusters through rook under the mep architecture.

common.mk: add like this
```
ALL_PLATFORMS ?= darwin_amd64 windows_amd64 linux_amd64 linux_arm64 linux_mips64le

ifeq ($(PLATFORM),linux_mips64le)
CROSS_TRIPLE = mips64le-linux-gnu
endif
```

**What is use case behind this feature:**
```     
make PLATFORM=linux_mips64le go.build

```

**Environment**:
* Rook version (use rook version inside of a Rook Pod):
1.5.4
* Storage backend version (e.g. for ceph do ceph -v):
v14.2.12
* Kubernetes version (use kubectl version):
v1.14.3

**Comment by BlaineEXE** [comment]
Kubernetes isn't built for the mips64le platform. I don't personally see a strong need for Rook upstream to support building for a platform that Kubernetes itself doesn't support.
