### ISSUE TITLE
Allow using existing CephObjectStoreUsers for OBCs

### ISSUE THREAD

**Issue by predakanga** [rook/rook#6877]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
This feature would allow users to specify an owner COSU when creating an ObjectBucketClaim.

The resultant ObjectBucket would be created with the appropriate owner, and the related Secret would contain that user's credentials.

**What is use case behind this feature:**
Deploying applications which utilize multiple object buckets, but only take one set of credentials (i.e. Gitlab), or for simplicity of management.

**Environment**:
Rook 1.5.1 with internal RGW

**Comment by travisn** [comment]
@BlaineEXE Does the brownfield scenario for OBCs cover this case?

**Comment by BlaineEXE** [comment]
It does not. The brownfield scenario is only encountered when using a pre-existing bucket. There is no option for a pre-existing user. The configuration is actually done in the storageclass with `parameter:bucketName`, and the OBC library handles this case specially.

We have some options here:
1. bake the `userName` into the OBC config
2. allow OBC lib code to interpret a `userName` field in the `StorageClass`
3. allow Rook to take action on a `userName` being present in the `StorageClass` but ignore this in OBC lib code

TBH, I think option 1 is not good given the precedent set with `bucketName` in the StorageClass. I would like to get @jeffvance and/or @copejon 's opinion on option 2.

We can implement option 3 in Rook, as the OBC lib passes the `StorageClass`'s `parameter`s into Rook's provisioning code already. I believe OBC is designed to allow the backend (Rook in our case) to take special actions for additional `parameter`s which are not understood by OBC.

---

What I would like from OP @predakanga is a little more explanation about their use case so we can assess how to best implement this feature. It would be nice to get a more detailed explanation of how you want to use this in your GitLab example.

How are your Ceph users are created? Via Ceph CLI or dashboard? Rook CRDs?
What should happen if a Ceph user is deleted but the OBC still exists? (This may just be a question for us devs)

**Comment by jeffvance** [comment]
@BlaineEXE At first glance I prefer option  3. I agree user name handling should not be in the lib, and in general, the lib should not interpret _SC.parameters_, which we violate with brownfield bucket names.

**Comment by predakanga** [comment]
Apologies in advance for the long comment, I'll try to keep it clear.

### Usecases
- I run a service which accesses several buckets from a single container. The service only accepts one set of credentials. I would like to use ObjectBucketClaims to create these buckets, and the corresponding ConfigMap/Secret with envFrom to provide credentials to that container.
- I manage a local Gitlab deployment using Ceph/Rook for object storage. Gitlab doesn't support providing credentials through the environment so I manually create OBCs, then copy the credentials into a Helm values file. Because Gitlab uses 12 different buckets, I would like to use their [Consolidated Object Storage](https://docs.gitlab.com/charts/charts/globals.html#consolidated-object-storage) config, but that requires all the bucket to be accessible by a single set of credentials.

### Root problem
The root problem is that I need a way to have multiple buckets accessible by a single set of credentials.
The only way I know of doing this within Rook's workflow is to create an ObjectStoreUser and create the buckets under that account manually.
The three main problems with this are that the buckets aren't codified anywhere (why have a CRD and not use it), the ObjectStoreUser has to be created in the operator namespace (prefer to minimize permissions), and the corresponding secret is created in the operator namespace (cross-namespace secretRefs aren't allowed).

### Specific answers
How are my Ceph users created? They're created by Rook CRDs. This is the only place in which I use Ceph users, besides the admin account for the dashboard.
What should happen if a Ceph user is deleted? Ideally a retention policy would be set on user creation, specifying whether the buckets should be deleted or just re-parented. Failing that, given that the user "owns" the bucket, it seems reasonable that deletion should cascade.

### Discussion
I haven't read into Rook's design docs, but I get the impression you don't want to mix concerns by bringing Ceph specifics into the OBC. Would the ability to specify credentials on that CRD be an acceptable solution?
As a user, I should also say that the setting of bucket options in the StorageClass feels a bit out of place. It's always confused me why bucketName is an option there, though perhaps that's just a documentation issue?

Thanks for looking into this,
predakanga

**Comment by BlaineEXE** [comment]
A question for @jeffvance :  why was lib-bucket-provisioner not designed to take pre-existing bucket names and instead relegating that to a storageclass parameter? It seems to me that claiming an existing bucket is pretty directly related to OBCs. And I would think that specifying a bucket user also makes sense. Both bucket name and user are common to all object storage types, yes?

**Comment by jeffvance** [comment]
@BlaineEXE The bucket lib design handles brownfield relatively poorly. Our thinking was that the user/app developer may/should not know the name of an existing bucket. The main reason is that often bucket names are long and random, and needing to know an unintuitive bucket name in addition to the name of the SC seemed like an extra burden on the user. There are several downsides to putting the brownfield bucket name in the SC, and the worst (IMO) is the burden placed on the admin, and as a result, potential delays before the app can access the bucket.

COSI supports the name of the `Bucket` k8s instance in the `BucketRequest`. So, not the actual bucket name and, again, a burden is placed on the admin to create the brownfield `Bucket` instance.

**Comment by BlaineEXE** [comment]
I have asked a question about this in k8s slack's COSI channel. I think my understanding is that the COSI spec makes this use-case an option. IMO, the best thing that could happen is for Rook to convert OBCs to COSI resources. I'm not sure if COSI is ready for real-world use, but I foresee us proceeding similarly to the flexvolume to CSI conversion: add COSI integration into Rook alongside OBCs for a time until we are sure COSI is as or more stable than OBCs, then allow a period for users to convert OBCs to COSI resources, then remove OBC support.

**Comment by thotz** [comment]
Out of scope from the above discussions: I had a similar idea providing access to different buckets for [cephobjectstoreuser](https://github.com/rook/rook/blob/master/design/ceph/object/bucketpolicy.md#proposal-details) using bucket policy feature, but didn't progress much due to other priorities

**Comment by BlaineEXE** [comment]
From user wlan0 on the COSI slack:

Since we are automating the credential provisioning process along with the bucket provisioning process,  users should not need a mechanism to use an existing access token 

i.e. an access token created out of band of COSI and tokens from pre-existing BA (edited) 

In case you still want to get around this, an admin could manually create a BA object with the appropriate credentials

and while it is possible to refer to an existing BA from a new BAR, it would be circumventing a lot of checks and management that would otherwise be available

It could come at the cost of losing data, it is not recommended

The right solution is to utilize the service account method of access management, wherein a service account that has already been associated with cloud credentials such as IAM are specified in BAR (i need to verify if it is indeed BAR) (edited) 

I would also like to invite you to join our weekly meetings to stay up-to-date with all the happenings of COSI

**Comment by BlaineEXE** [comment]
COSI won't be available in k8s until 1.21 to my understanding. I think I should be able to enable OP's use-case fairly quickly using a `userName` field in the `StorageClass` to enable this for Rook with OBCs. I have a few items that have been in my backlog to get to, but I'm still hopeful we can get this into master in time for Rook v1.6
