### ISSUE TITLE
Rook Ceph - Resource Limits for OSDs

### ISSUE THREAD

**Issue by RyanW8** [rook/rook#6890]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

In the CephCluster CRD setting the OSDs resource requests/limitsl ike s
```
resources:
    osd:
      requests:
        memory: 3Gi
      limits:
        memory: 3Gi
```

results in all the containers in the OSD pod having those limits (Including the initContainers).

**Expected behavior:**

These resource requests/limits should only be set on the OSD container and not the initContainers within the pod.

**How to reproduce it (minimal and precise):**

Set the resources in the CephCluster CR to the above and wait for rook to schedule the OSD pods with the new resource constraints

**File(s) to submit**:

N.A

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (e.g. `uname -a`): Linux wkf-worker-6 5.9.13-1.el7.elrepo.x86_64 #1 SMP Mon Dec 7 11:44:47 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration: VMs running in VMWare vCD/vSphere
* Rook version (use `rook version` inside of a Rook Pod): v1.4.5
* Storage backend version (e.g. for ceph do `ceph -v`): Ceph 15.2.4
* Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): On Premise, deployed using KubeSpray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@RyanW8 The [K8s resource docs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources) mention that a pod will be scheduled based on the highest limit of the init containers, or the sum of the app containers, whichever is greater. Rook is currently setting the resource limits the same on all init containers and the daemon container, which means the OSD pod should be scheduled just based on the needs of the daemon container, while the init containers basically won't be a factor for scheduling. Are you seeing some side effect from this, or was it just unexpected to see the same limits on all the init containers?
