### ISSUE TITLE
Does Rook support Cinder Block Storage

### ISSUE THREAD

**Issue by SAshish19** [rook/rook#6892]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Need to check if Rook can be used by Cinder Block Storage

**What is use case behind this feature:**
Conformation on implementation with Cinder block storage

**Environment**:

Hi Team,

We have a 6 node Kubernetes cluster with 3 master and 3 worker nodes. All the worker nodes are having individual Cinder Block Storage volumes attached.At run time the pods will move dynamically from one worker to another (during the event of unavailability of one or more nodes). We want to check if we can use Rook provisioner with Cinder Block storage ?

Thanks & Regards

**Comment by travisn** [comment]
@SAshish19 See the [Rook prerequisites for disks](https://rook.github.io/docs/rook/v1.5/ceph-prerequisites.html#ceph-prerequisites). Is the storage from Cinder available from a storage class? If so, this should be simple with the [cluster-on-pvc](https://rook.github.io/docs/rook/v1.5/ceph-cluster-crd.html#pvc-based-cluster) scenario.

**Comment by BlaineEXE** [comment]
The state of OpenStack may have changed since I gave this talk, but it could provide some answers for you.

https://www.youtube.com/watch?v=mCljCGIE-hM

**Comment by leseb** [comment]
I would think that Cinder would connect to Ceph-CSI directly, not necessarily to Rook. @SAshish19 can you describe in more detail what you are trying to achieve? Thanks
