### ISSUE TITLE
Error when creating  csi-cephfsplugin-provisioner and  csi-rdb-plugin-provisioner

### ISSUE THREAD

**Issue by jakoberpf** [rook/rook#6894]
Hello, I have an issue with setting up rook ceph cluster on raspberry pis. Since there is no official arm support I am using the raspbernetes images like the guide [rook on arm](https://medium.com/swlh/how-to-develop-for-arm-on-a-budget-bfc433bdad07), I hope I am in the right place to ask for guidance. Similar guides like [G1](https://blog.codegiant.io/how-to-deploy-a-ceph-cluster-on-kubernetes-with-rook-daf24e6db914) and [G2](https://medium.com/@fdeantoni/running-rook-with-k3s-5e2c79159eaf) are doing the same thing basically, but without the arm considerations.

` ROOK_CSI_CEPH_IMAGE: "raspbernetes/ceph-csi:v3.1.0"
  ROOK_CSI_REGISTRAR_IMAGE: "raspbernetes/csi-node-driver-registrar:1.3.0"
  ROOK_CSI_RESIZER_IMAGE: "raspbernetes/csi-external-resizer:0.5.0"
  ROOK_CSI_PROVISIONER_IMAGE: "raspbernetes/csi-external-provisioner:1.6.0"
  ROOK_CSI_SNAPSHOTTER_IMAGE: "raspbernetes/csi-external-snapshotter:2.1.1"
  ROOK_CSI_ATTACHER_IMAGE: "raspbernetes/csi-external-attacher:2.2.0"`

When applying the default/example cluster.yaml i have a similar error in the cephfs and rdb provisioners.

`error: a container name must be specified for pod csi-cephfsplugin-provisioner-5cb7799c98-dp5tx, choose one of: [csi-attacher csi-snapshotter csi-resizer csi-provisioner csi-cephfsplugin liveness-prometheus]`

**Deviation from expected behavior:**
If I understand the error message correctly I have a missing definition in one of the examples .yamls, but I can't find out what I have to change exactly. The error also shows that it is not an architectural problem I think.

EDIT: according to this post [stackoverflow](https://stackoverflow.com/questions/47129376/kubernetes-kubectl-a-container-name-must-be-specified-but-seems-like-it-is), this error occurs when the pod of the container can be found among many. So I guess that I have to point the provisioner container to the applicable pods. But how? 

**Expected behavior:**
Simple deployment into the running status of cephfs and rdb provisioner.

**How to reproduce it (minimal and precise):**
3 or 6 raspberry pies with m.2 SATA SSDs and adapters, running ubuntu64 for arm. k3s kubernetes HA setup with external etcd cluster and multiple services running fine. Integration of rook-ceph via the guide [rook on arm](https://medium.com/swlh/how-to-develop-for-arm-on-a-budget-bfc433bdad07).

**Environment**:
* OS: Ubuntu64 focal for arm
* Kernel: Linux server-01 5.4.0-1025-raspi #28-Ubuntu SMP PREEMPT Wed Dec 9 17:10:53 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
* Cloud provider or hardware configuration: RaspberryPi4 8gb
* Rook version: master and rook/ceph:v1.5.4
* Storage backend version: ceph/ceph:v15.2.8
* Kubernetes version: v1.19.5+k3s2
* Kubernetes cluster type: k3s

**Comment by 2fst4u** [comment]
I am having the same issue but I thought it was down to one of my Raspberry Pi nodes being armhf (old 3B model) that it keeps starting on. I've been searching for the syntax for node affinity for these pods because it's completely different in the operator.yaml to see if forcing them to only start on my arm64 nodes fixed it.

But if you're getting this error on a purely arm64 cluster then it must be deeper.
