### ISSUE TITLE
Unable to get osd's on 3 different nodes in 3 different zones on Azure AKS

### ISSUE THREAD

**Issue by universenl** [rook/rook#6911]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After running cluster-on-pvc only 2 of the 3 storage nodes have osd's running.

**Expected behavior:**
All 3 storagenodes need to take care of osd's

**How to reproduce it (minimal and precise):**
Clean aks setup, create 1 more storage pool with 3 nodes in 3 zones and add: --node-taints storage-node=true:NoSchedule
then:
kubectl create -f crds.yaml -f common.yaml
kubectl create -f storageclass.yaml (aks premium LRS)
kubectl create -f operator.yaml
kubectl create -f cluster-on-pvc.yaml

**File(s) to submit**:
[common.txt](https://github.com/rook/rook/files/5775588/common.txt)
[crds.txt](https://github.com/rook/rook/files/5775589/crds.txt)
[storageclass.txt](https://github.com/rook/rook/files/5775591/storageclass.txt)
[operator.txt](https://github.com/rook/rook/files/5775590/operator.txt)
[cluster-on-pvc.txt](https://github.com/rook/rook/files/5775592/cluster-on-pvc.txt)
[Setuplog_operator.txt](https://github.com/rook/rook/files/5775596/Setuplog_operator.txt)
[pods_namespace.txt](https://github.com/rook/rook/files/5775599/pods_namespace.txt)

When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu18
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: Cloud provider Azure AKS
* Rook version (use `rook version` inside of a Rook Pod): rook/ceph:v1.5.4
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 18.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AKS

**Comment by sp98** [comment]
The `SetupLog_Operatore.txt` file does show that third OSD (`osd.2`) was started. 
```
2021-01-06 11:43:13.083153 I | op-osd: starting 1 osd daemons on pvc set1-data-0-p8vgr
2021-01-06 11:43:13.083163 I | op-osd: OSD will have its main bluestore block on "set1-data-0-p8vgr"
2021-01-06 11:43:13.083171 I | cephclient: getting or creating ceph auth key "osd.2"
2021-01-06 11:43:13.396018 I | op-osd: started deployment for osd 2 on pvc
```
Are you not seeing this the third OSD at all or is there a failure like `crashLoopBackoff` etc ?

**Comment by universenl** [comment]
The 3e osd is there but not on node 3. (aks-npstorage-19598758-vmss000000 in kube)
Here you can see that 2 osd's are on the same node:

```
rook-ceph-osd-0-7974dc54f5-r5pnv                                  1/1     Running     0          51m    10.0.0.8    aks-npstorage-19598758-vmss000001    <none>           <none>
rook-ceph-osd-1-8bf7457b4-92b9w                                   1/1     Running     0          49m    10.0.0.8    aks-npstorage-19598758-vmss000001    <none>           <none>
rook-ceph-osd-2-6bf7f87c75-fw8tg                                  1/1     Running     0          49m    10.0.0.9    aks-npstorage-19598758-vmss000002
```

**Comment by travisn** [comment]
@universenl There are a couple different things you could try:
1. Specify required pod antiaffinity for `rook-ceph-osd-prepare` to get one in each zone. No need for anti-affinity on the `rook-ceph-osd` since the osd daemons must start in the same AZ where its corresponding OSD prepare job ran
2. Since antiaffinity is not known to be perfect, you could create three different storageClassDeviceSets, each with nodeAffinity to a single AZ.

**Comment by universenl** [comment]
Thanks, i ll try that tomorrow when i am @work again.

**Comment by universenl** [comment]
Hi,
I created 3 different devicesets and lock them in to the aks zones:

` nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - npstorage
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - westeurope-1`

Only the first 2 zones are getting osd's on them and zone3 got this error: op-osd: no PVC available for storageClassDeviceSet "zone3"

Thanks!

**Comment by universenl** [comment]
I did create 3 devicesets in 3 different zones bound and that worked!
```
nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - npstorage
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - westeurope-3
```

Thank you!
