### ISSUE TITLE
Can't get ceph dashboards working with kubectl port-forward

### ISSUE THREAD

**Issue by knkarthik** [rook/rook#6924]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Connection refused when accessing dashboard. Tried with both ssl enabled and disabled
```
kubectl port-forward -n rook-ceph svc/rook-ceph-mgr-dashboard 7000:7000
Forwarding from 127.0.0.1:7000 -> 8443
Forwarding from [::1]:7000 -> 8443
Handling connection for 7000
E0107 18:25:26.702576   35971 portforward.go:400] an error occurred forwarding 7000 -> 8443: error forwarding port 8443 to pod fc5dbd56b06cff12421ca6e4ca1ffefe7ce66fb362b7387cfef25593af2de8ea, uid : exit status 1: 2021/01/07 23:25:26 socat[400] E connect(5, AF=2 127.0.0.1:8443, 16): Connection refused
```

**Expected behavior:**

Should open dashboard.

**How to reproduce it (minimal and precise):**

```
kubectl create -f crds.yaml -f operator.yaml -f common.yaml -f toolbox.yml cluster-on-pvc.yaml 
```

I tried workarounds mentioned in https://github.com/rook/rook/issues/2526 but still doesn't work.

**Comment by leseb** [comment]
I just re-opened #2526 and closing this, we don't need to re-open a new one. Please comment over there.
