### ISSUE TITLE
ceph: discovery daemon container is not changed after upgrading to v1.5

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#6936]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

If upgrade to v1.5.x, discovery daemons still use old Rook container. It happens because the discovery daemon is disabled in operator.yaml.

**Expected behavior:**

Upgrade the discovery daemon's container to.

**How to reproduce it (minimal and precise):**

1. Create a v1.4.x or older cluster with enabling discovery daemon.
2. Upgrade this cluster to v1.5.x.

**Comment by travisn** [comment]
In upgraded clusters, it's expected that `ROOK_ENABLE_DISCOVERY_DAEMON=true` by default. If the new value `false` is assigned, then the operator should remove the discovery daemonset, rather than update it.

**Comment by satoru-takeuchi** [comment]
I confirmed that rook-operator doesn't delete rook-discover daemonset after setting ROOK_ENABLE_DISCOVERY_DAEMON=false.
