### ISSUE TITLE
CI : Add new Jenkins slaves for various platform 

### ISSUE THREAD

**Issue by dangula** [rook/rook#694]
We need to qualify rook against various platforms - Kubernetes installations, linux distort and Cloud providers.  For this we need various Jenkins slaves for each kind of platform. Here is a list of platform we would like to test against

- Linux distros
   - Ubuntu
   - Fedora
- Public cloud 
    - AWS
    - GKE
    - GCE
    - Asure
- Kubernetes platforms 
    - kubeadm
    - minikube
    - coreos Kubernetes
    - Helm

**Comment by jpds** [comment]
Please also add ARM to the list, https://www.linaro.cloud/ can be used as a cloud for testing purposes.

**Comment by hunter** [comment]
GKE may be problematic as they don't include RBD/CephFS as part of their kernel in the newer container-os (it exists in the old debian VM images but that is now deprecated). 

As an aside, it may worth considering an additional External Storage provider that uses the FUSE drivers (unsure about NBD) as a fallback. Not as performant but may be more compatible

**Comment by bzub** [comment]
Bootkube/Tectonic and other self-hosted kubernetes  patterns are very popular I believe. I've heard that the coreos/kubernetes repo will be depreciated in favor of the the self-hosted route eventually.  So I'm just wondering if this platform is covered here? I think kubeadm will cover it someday but not everything works right now for self-hosted deployment.

**Comment by bassam** [comment]
@hunter regarding using NBD as a fallback, we're planning to do that once our Rook volume plugin is in place.

@bzub agree, we need to test on all popular platforms.

**Comment by bassam** [comment]
@jpds we're planning on using scaleway for both armhf and arm64 testing. Jenkins support for scaleway is a bit lagging, but we're gonna find a way around it. Also #700 adds armhf support.

**Comment by dangula** [comment]
added jenkins slaves on GCE and Azure
