### ISSUE TITLE
The clusterrole rook-ceph-global is out of sync between charts and common.yaml in rook1.5.4

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#6945]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The clusterrole rook-ceph-global defined in "clusterrole.yaml" ( rook-1.5.4/cluster/charts/rook-ceph/templates) is short of
"k8s.cni.cncf.io" apiGroups comparing to "common.yaml" file ( rook-1.5.4/cluster/examples/kubernetes/ceph/common.yaml ). 

**Expected behavior:**
Expect all the definition between the common.yaml/crd.yaml is the same as the chart definition.
If the common.yaml file is to be seperated, it may be worthy to use one set of files( clusterrole.yaml, role.yaml ....) as defined in chart. 

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.5.4
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@yanchicago You're referring to this? 
```yaml
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
```

I see in the helm chart that it is in the `Role` for `rook-ceph-system`, while in the common.yaml it is in the `ClusterRole` for `rook-ceph-global`.
@rohan47 Which is the correct location?

**Comment by yanchicago** [comment]
@travisn I'm referring clusterrole "rook-ceph-global" definition as stated.
