### ISSUE TITLE
rook-ceph: Bluestore: DISCARD Disabled: SSD Performance Degradation

### ISSUE THREAD

**Issue by lyind** [rook/rook#6964]
**Is this a bug report or feature request?**
* Bug Report

**Bug Report**

**Expected behavior:**
Rook-ceph configures Bluestore OSDs so that:
```
$ ceph config dump
WHO                            MASK  LEVEL     OPTION                              VALUE                                     RO
    osd.1                            advanced  bdev_async_discard                  true                                        
    osd.1                            advanced  bdev_enable_discard                 true    
    osd.10                           advanced  bdev_async_discard                  true                                        
...
```
Diagnostic tools show actual discards happening (**kB_dscd/s != 0**) on the DM devices:
```
$ iostat
...
Device             tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd
dm-0              7.77        47.53        16.88         0.52    3993657    1418064      44016
...
```

Ceph Bluestor OSDs performance stays within the same order of magnitude after a few months of IDLE load.

**Deviation from expected behavior:**

SSDs write performance slowly degrades with Bluestore on device mapper because of disabled TRIM/DISCARD support. Expected life of the storage device is very likely also reduced.

In my test a rook-ceph deployment suffered from **~30x** decreased write IOPS after **~3 Months of almost idling**. This caused **low IO latency** which would be unacceptable in production.

Between 4 to 8 TB were written to the SSD devices during the test period with slow rate (< 2MB/s most of the time), mostly by:
 * ETCD background noise
 * very frequent manual rocksdb compaction triggered by ?rook?
 * ceph balancer
 * some activity by Ceph mon pods
 * possibly some RGW reorganization and accesses
 * possibly a few accesses from idling RBD database pods

The SSDs used were *affordable* Samsung 860 QVO 2TB SATA drives, which seem to be allergic to being filled >= 90% (or overwritten without ranges being discarded via TRIM).

`iostat` on an affected node (with Bluestore discard still disabled by default):
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.01    0.00    0.83   13.31    0.00   84.84Device            r/s     rkB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wkB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dkB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
dm-0             1.80      7.20     0.00   0.00   88.67     4.00   17.80     42.40     0.00   0.00   66.43     2.38    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    1.34  99.56
dm-1             0.00      0.00     0.00   0.00    0.00     0.00    5.60     13.60     0.00   0.00    0.50     2.43    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.42
dm-2             0.20      0.80     0.00   0.00   95.00     4.00    7.40     17.60     0.00   0.00   68.38     2.38    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.53  47.36
dm-3             0.00      0.00     0.00   0.00    0.00     0.00    3.20      7.20     0.00   0.00    0.50     2.25    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.24
dm-4             0.00      0.00     0.00   0.00    0.00     0.00    5.60     13.60     0.00   0.00    0.50     2.43    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.42
dm-5             0.00      0.00     0.00   0.00    0.00     0.00    3.20      7.20     0.00   0.00    0.50     2.25    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.00   0.24
dm-6             1.80      7.20     0.00   0.00   88.67     4.00   17.80     42.40     0.00   0.00   66.44     2.38    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    1.34  99.56
dm-7             0.20      0.80     0.00   0.00   95.00     4.00    7.40     17.60     0.00   0.00   68.41     2.38    0.00      0.00     0.00   0.00    0.00     0.00    0.00    0.00    0.53  47.36
sda              0.00      0.00     0.00   0.00    0.00     0.00   15.20     80.80     0.60   3.80    0.57     5.32    0.00      0.00     0.00   0.00    0.00     0.00    9.20    0.76    0.02   1.74
sdb              1.80      7.20     0.00   0.00   88.78     4.00   33.00    250.40     3.80  10.33   73.41     7.59    0.00      0.00     0.00   0.00    0.00     0.00   14.80   67.72    3.58  90.22
sdc              0.00      0.00     0.00   0.00    0.00     0.00   12.80     74.40     0.60   4.48    0.56     5.81    0.00      0.00     0.00   0.00    0.00     0.00    8.00    0.75    0.01   1.54
sdd              0.20      0.80     0.00   0.00   95.00     4.00   22.00    219.20     3.80  14.73   60.73     9.96    0.00      0.00     0.00   0.00    0.00     0.00    9.80   84.31    2.18  65.96
```

`ceph osd perf` output on an the affected cluster:
```
osd  commit_latency(ms)  apply_latency(ms)
 30                   0                  0
 31                   0                  0
 29                   2                  2
 28                   3                  3
 27                   0                  0
 26                 346                346
 25                   2                  2
 24                   6                  6
 23                   0                  0
 22                   2                  2
 21                   7                  7
 20                   2                  2
 19                   2                  2
 18                   3                  3
 17                 331                331
 16                   2                  2
  5                 236                236
  4                   0                  0
  3                   2                  2
  2                   3                  3
  0                  44                 44
  1                   8                  8
  6                   3                  3
  7                   2                  2
  8                 341                341
  9                   2                  2
 10                   0                  0
 11                   4                  4
 12                   3                  3
 13                   3                  3
 14                   5                  5
 15                 384                384
```

**How to reproduce it (minimal and precise):**

Setup rook-ceph on SSD storage with Bluestore and encryption enabled and observe the amount of discards on "dm-0" using "iostat" or similar tools.

It is not necessary to wait for actual performance degradation to happen as that is known to occur after some time (TBs written without TRIM). It may happen earlier on cheaper SSD drives (slower NAND cells, less reserves), but should finally hit higher priced devices, too. 

**Does this have an impact on existing features:**
Trim/discard does not need to be enabled for HDDs (rotating media).

**Environment**:
* OS: Debian GNU/Linux bullseye/sid
* Kernel: 5.9.8 -> 5.10.7 (upgraded during the test)
* Cloud provider or hardware configuration: bare-metal, consumer SSDs (Samsung SSD 860 QVO 2TB SATA)
* Rook version: v1.4.3
* Storage backend version: 15.2.4
* Kubernetes version: v1.19.1
* Kubernetes cluster type: kubeadm
* Storage backend status: HEALTH_OK

**Comment by lyind** [comment]
Due to the complex nature of the matter and the SSD state/firmware being a bit of a blackbox, I may have misdiagnosed this issue.

Please correct me if I am wrong and this slowdown is related to some other issue.

After enabling TRIM via `rook-config-override` the performance seems to *very slowly* recover, but I will re-provision the cluster soon to quickly restore performance.

**Comment by lyind** [comment]
If ETCD is run on one of the storage nodes, too (converged architecture) these or similar messages are logged:
```
2021-01-14 09:49:41.724718 W | etcdserver: read-only range request "key:\"/registry/health\" " with result "error:context deadline exceeded" took too long (2.000077626s) to execute
2021-01-14 09:49:43.723562 W | etcdserver: request "header:<ID:8255510435077583436 username:\"kube-apiserver-etcd-client\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/services/endpoints/default/kubernetes\" mod_revision:47979972 > success:<request_put:<key:\"/registry/services/endpoints/default/kubernetes\" value_size:458 >> failure:<>>" with result "size:20" took too long (236.404143ms) to execute
```
I mention this just in case somebody suffers from a similar performance degradation issue and doesn't know where to look, only seeing the ETCD log messages.

**Comment by lyind** [comment]
This is one possible workaround:
```
---
apiVersion: v1
data:
  config: |
    [global]
    bdev_enable_discard = true
    bdev_async_discard = true
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
```

**Comment by travisn** [comment]
@bengland2 Thoughts on this perf issue? thanks

**Comment by bengland2** [comment]
@travisn thx for pointing this out to me, this is a very interesting problem that I haven't thought much about, synchronous trim is prohibitively expensive, not sure why the default options aren't working though.  What's alarming : the latency spikes up to 1/3 sec !   Not acceptable for etcd and for many other latency-sensitive apps.     Maybe this can be tuned somehow to trim more often but not hit the system as hard when the trim is happening?   Checking with some folks who know more than me about it...

**Comment by lyind** [comment]
> @travisn thx for pointing this out to me, this is a very interesting problem that I haven't thought much about, synchronous trim is prohibitively expensive, not sure why the default options aren't working though. What's alarming : the latency spikes up to 1/3 sec ! Not acceptable for etcd and for many other latency-sensitive apps. Maybe this can be tuned somehow to trim more often but not hit the system as hard when the trim is happening? Checking with some folks who know more than me about it...

To clarify:
This bug report is about Cephs **async TRIM feature** being apparently **not enabled by default** by rook-ceph setup, which leads to bad SSD performance (as time passes and the flash cells fill up). The `iostat` output posted comes from nodes already badly affected from disabled TRIM's consequences (the OSDs need to be re-created, SSDs cleared using secure-erase).

I doubt that the system performance would have deteriorated in this way if `bdev_enable_discard` and `bdev_async_discard` would have been enabled since OSD creation.
