### ISSUE TITLE
Expose more info for upgrade

### ISSUE THREAD

**Issue by jshen28** [rook/rook#6971]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Expose more info to the `CephCluster` status during osd upgrade. Such that cloud
operator has a chance to know which node/osd is being processed without turning
to the logs.

**What is use case behind this feature:**

Expose progress of current upgrade to the cephcluster status so that cloud operator
could easily aware of which node/osd is being processed

**Environment**:

all

**Comment by travisn** [comment]
Already fixed by #6972
