### ISSUE TITLE
Add common docker image labels

### ISSUE THREAD

**Issue by viceice** [rook/rook#6973]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add opencontainers docker image labels ( see [here](https://github.com/opencontainers/image-spec/blob/master/annotations.md)

**What is use case behind this feature:**
I'm using [renovatebot](/renovatebot/renovate) to update helm `values.yml` files. Renovate uses `org.opencontainers.image.source` label to fine the source code repo to fetch changelogs.

**Environment**:

I can send a pr if this is a accepted feature.

**Comment by leseb** [comment]
If it's just about adding labels that shouldn't be a problem, you can send a PR. Thanks
