### ISSUE TITLE
Dashboard switch from SSL true to false doesn't recreate the dashboard service

### ISSUE THREAD

**Issue by electrical** [rook/rook#6976]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I switched the SSL setting for the dashboard from true to false. It did restart the mgr process but didn't recreate the dashboard service to expose the http port

**Expected behavior:**
Expected behaviour was to recreate the dashboard service automatically.
Removing the service forced the operator to recreate it with the right port.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): 1.5.5

**Comment by electrical** [comment]
This should remain open as it's still an issue

**Comment by parth-gr** [comment]
@electrical, By [changing](https://github.com/rook/rook/blob/ccb4221cb3396d159e94553472777ccfe2f4d925/cluster/examples/kubernetes/ceph/cluster.yaml#L70) `ssl: false` and updating this change by `kubectl apply -f cluster.yaml ` , recreate the rook-ceph-mgr pod and also updates the service rook-ceph-mgr-dashboard PORT(S) to  7000/TCP  from 8443/TCP and now we can access the dashboard with HTTP at port 7000. 
```yaml
NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
rook-ceph-mgr-dashboard    ClusterIP   10.99.120.70    <none>        7000/TCP            19m
```
There is no need to recreate the rook-ceph-mgr-dashboard service as the service port is already getting updated :)

**Comment by parth-gr** [comment]
Closing this issue as it's not reproducible and the SSL setting is working fine.  
Please re-open with more details if still hitting this issue.

**Comment by parth-gr** [comment]
Closing this issue as it's not reproducible and the SSL setting is working fine.
Please re-open with more details if still hitting this issue.
