### ISSUE TITLE
Define a CRD for object storage

### ISSUE THREAD

**Issue by travisn** [rook/rook#698]
For api consistency, we need to create a TPR for object storage. The current implementation of starting the object storage through the api service is only intended for the standalone solution rather than also being the kubernetes implementation.

As part of this work we should also support multiple object stores. RGW supports it under the covers.

**Comment by DanKerns** [comment]
It should be possible to specify Erasure Coding or Replication for the object store along with the usual parameters for each.

**Comment by jbw976** [comment]
#310 may cover the work to support multiple object stores
#334 may cover the work to specify EC or replication config for the pools used by the object store being created
