### ISSUE TITLE
Allow setting the namespace for ServiceMonitors

### ISSUE THREAD

**Issue by predakanga** [rook/rook#6983]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The ServiceMonitor created when a CephCluster has monitoring enabled is always created in the CephCluster's namespace.

The admin should be able to specify which namespace to create the ServiceMonitor in through the CRD, as with rulesNamespace.

Happy to provide a PR if the feature is accepted.

**What is use case behind this feature:**
The default (and presumably intended) Prometheus-Operator deployment only monitors it's own namespace for ServiceMonitors.

As far as I can tell, this is the idiomatic way of deploying Prometheus-Operator, and is supported by the vast majority of Helm charts (see [ingress-nginx](https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-servicemonitor.yaml#L7))

**Environment**:
Rook-ceph v1.5.4
Kubernetes v1.19.2
Prometheus-Operator v0.44.0

**Comment by travisn** [comment]
@predakanga Should the service monitor namespace be the same as the rules namespace? Or it could even be a different namespace? If so, makes sense to add another setting in the CephCluster CR next to the rulesNamespace, then apply it [here](https://github.com/rook/rook/blob/3b9dad94c9243078b3974bebca29e9b1a422a439/pkg/operator/ceph/cluster/mgr/mgr.go#L353). Sounds good if you want to open a PR.

**Comment by umangachapagain** [comment]
> @predakanga Should the service monitor namespace be the same as the rules namespace? Or it could even be a different namespace?

It could be a different namespace. The main thing is that the intended Prometheus should be able to access it.

ServiceMonitors are namespaced. So it makes sense to make the namespace configurable.
But, I'd still prefer the default to be the namespace where CephCluster being monitored is deployed.
