### ISSUE TITLE
Remove YugabyteDB storage provider from Rook and point to the replacement operator

### ISSUE THREAD

**Issue by travisn** [rook/rook#6992]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The YugabyteDB storage provider has not had sufficient community or maintainer support to continue to release its operator as part of Rook. The proposal is to remove YugabyteDB from Rook in the v1.6 release (March timeline).

YugabyteDB has a competing operator [here](https://github.com/yugabyte/yugabyte-operator) maintained by their team. A discussion is still underway for whether the team wants to support the Rook operator or direct their energy solely to their other operator. If the YugabyteDB team decides to make the commitment to Rook, we will certainly keep it and close this issue. 

See the full proposal [here](https://docs.google.com/document/d/1TSPfqX3D08lN5RjIf2wbQideIMOv09bXreRMUFzIycY/edit).

**Expected behavior:**
Storage providers in Rook must have community and maintainer support. This has been discussed for the past two Rook community meetings as seen in the [notes](https://docs.google.com/document/d/1exd8_IG6DkdvyA0eiTtL2z5K2Ra-y68VByUUgwP7I9A/edit). Also see the related expectations for storage providers now being documented in #6989.

**Comment by iSignal** [comment]
@travisn : We (YugabyteDB) don't think we will be able to put in the effort needed to move the Rook YugabyteDB operator to Beta status, at least this year.

Like you mentioned, we maintain another k8s operator at https://github.com/yugabyte/yugabyte-operator. That operator has moved forward a bit compared to the Rook YugabyteDB operator and would provide community users with a better supported alternative (for example, it supports automated scale up and scale down of pods).

In the meantime, we are happy to answer any Rook YugabyteDB operator questions either in the Rook Slack community or on the YugabyteDB Slack community at https://www.yugabyte.com/slack.
