### ISSUE TITLE
Add CephFS stats per filesystem

### ISSUE THREAD

**Issue by leseb** [rook/rook#7003]
**Is this a bug report or feature request?**
* Feature Request

Just like we have RBD stats for images, we should be able to activate for CephFS so that Ceph-CSI/Prometheus can explore Filesystem metrics.
For more details: https://github.com/ceph/ceph/blob/master/doc/cephfs/cephfs-top.rst

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by travisn** [comment]
@leseb Thoughts on this one and who could take ownership?

**Comment by leseb** [comment]
Invalid, the best place is simply more metrics coming from the ceph manager prometheus module.
