### ISSUE TITLE
Allow configure cache tier for pool

### ISSUE THREAD

**Issue by jshen28** [rook/rook#7006]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

provide a way to configure cache tier pool for a give pool

**What is use case behind this feature:**

Sometimes users might want to accelerate write/read by adding
a cache tier. 

**Environment**:

**Comment by leseb** [comment]
I thought Ceph had abandoned this functionality long ago, did I miss something?

**Comment by jshen28** [comment]
Oh... this is really new to me.. this actually makes doubt why we use cache tier in production...

Btw would be appreciated to have some references on the reason of preventing use of cache tier...

**Comment by leseb** [comment]
Perhaps this would help? https://docs.ceph.com/en/latest/rados/operations/cache-tiering/#a-word-of-caution

**Comment by jshen28** [comment]
Hmm.. thank you very much for the link.

**Comment by HubertBos** [comment]
Well, on that note, can we have some updates if this feature will be added to ROOK, or can we make it work ourselves?

**Comment by travisn** [comment]
After the needed pools are created with the CephBlockPool CR, the cache tiering could be configured from the toolbox (or the krew plugin) according to the commands in that ceph doc previously linked.

**Comment by travisn** [comment]
In the Ceph Reef [release notes](https://ceph.io/en/news/blog/2023/v18-2-0-reef-released/#highlights), RADOS cache tiering is deprecated.
