### ISSUE TITLE
Rook Operator should run in HA mode

### ISSUE THREAD

**Issue by bassam** [rook/rook#701]
The Rook Operator should run in HA mode and support leader election.

**Comment by bassam** [comment]
examples to follow: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L186

**Comment by galexrt** [comment]
I think this would be something to implement in the operator-kit. So everyone using it will get this feature.

**Comment by jbw976** [comment]
As per @bassam:
> I believe this will no longer be needed once we switch to using API aggregation instead of CRD/operator pattern
