### ISSUE TITLE
Nonexistent ceph clusters reported after upgrading from 1.4.7 to 1.5.5

### ISSUE THREAD

**Issue by eknudtson** [rook/rook#7011]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After upgrading to rook 1.5.5, I see the following errors show up in the rook operator logs:

```
2021-01-19 21:09:52.722549 E | clusterdisruption-controller: cephcluster "kafka/" seems to be deleted, not requeuing until triggered again
2021-01-19 21:09:52.767254 E | clusterdisruption-controller: cephcluster "kafka/" seems to be deleted, not requeuing until triggered again
```

We have a separate `kafka` namespace that should be totally isolated from rook/ceph.  There is only one Ceph cluster resource in the cluster as reported by kubectl : 

```
 k get cephcluster -A
NAMESPACE   NAME        DATADIRHOSTPATH   MONCOUNT   AGE    PHASE   MESSAGE                        HEALTH
rook-ceph   rook-ceph   /var/lib/rook     3          560d   Ready   Cluster created successfully   HEALTH_OK
```

**Expected behavior:**
No unexpected errors arise in the rook operator log.

**How to reproduce it (minimal and precise):**

Upgraded from Rook 1.4.7 to 1.5.5 and these errors started to appear.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7
* Kernel (e.g. `uname -a`): 3.10.0-1127.19.1.el7.x86_64
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): 1.5.5
* Storage backend version (e.g. for ceph do `ceph -v`): v14.2.14-20201119
* Kubernetes version (use `kubectl version`): 1.18.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
This should just be an invalid log message. @sp98 Could you take a look?

**Comment by sp98** [comment]
was able to produce this 
`2021-02-02 13:30:44.034655 E | clusterdisruption-controller: cephcluster "test/" seems to be deleted, not requeuing until triggered again`. 

This happens because the `podDisruptionBudget` watcher watches in all the namespaces. So reconciler gets triggered if a PDB in a different namespace (other than rook-ceph) is changed. I'll try to raise a PR soon.
