### ISSUE TITLE
The operator pod failed to update mds and rgw deploy/pod automatically when "logCollector" is enabled or disabled.

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#7022]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When the cephcluster is updated with "logCollector" from "true" to "false" or "false" to "true", the mds and rgw deploy/pod were not updated. Note: the osd and mon deploy/pods were updated correctly. 

**Expected behavior:**
The mds and rgw deploy/pod can be updated automatically, similar to osd and mon deploy/pods. 

Note: Restart the operator, the mds/rgw deploy/pods will be updated correctly. 

**How to reproduce it (minimal and precise):**

Patch cephcluster to toggle "logCollector" field "enabled" from "false" to "true" or "true" to "false". 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.5.5
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.8
* Kubernetes version (use `kubectl version`): v1.18.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
Ahhh yes, this is because the other CR will only reconcile if there a cluster upgrade (image changes from the CephCluster CRD). Shame, I need to fix that.
