### ISSUE TITLE
Add support for RBD namespace creation

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#7035]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add support to create multiple RBD Namespace is a pool.
**What is use case behind this feature:**

This would allow multiple kubernetes clusters or multiple tenants in a kubernetes cluster to share one unique ceph cluster without creating a pool per kubernetes user. Pools in ceph can be computationally expensive as stated in documentation and namespaces are the recommended way to segregate tenants/users.

Once Rook supports this feature, we also need to allow users/admins to configure the csi configuration to use rbd namespaces.

cephcsi issue 
**Environment**:

**Comment by leseb** [comment]
I suspect that we would need to update the ceph-csi cephx caps to access any namespace, right?

**Comment by Madhu-1** [comment]
Yes, the current users should be able to access all the namespaces, but I would expect the user to create their own cephx users and secrets for secure-auth.

**Comment by leseb** [comment]
@Madhu-1 I have code for this already.

**Comment by leseb** [comment]
I'll submit it soon.

**Comment by Madhu-1** [comment]
@leseb Thank you. Assigned Yug to handle the CSI side of things to support multiple namespaces.

**Comment by leseb** [comment]
> @leseb Thank you. Assigned Yug to handle the CSI side of things to support multiple namespaces.

Sounds good!

**Comment by Madhu-1** [comment]
@leseb are you working on this one? if not I can take care of this one.
