### ISSUE TITLE
Add support to create multiple subvolume groups in a filesytem

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#7036]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
user should be able to create multiple subvolume groups within a  filesystem
**What is use case behind this feature:**

This would allow multiple kubernetes clusters or multiple users in a single kubernetes cluster to share one unique ceph cluster without creating multiple filesystems per kubernetes user/clusters. with subvolumegroup, we can isolate the tenants.

cephcsi supports multiple creating subvolumes on multiple subvolumegroups, we need to expose the configuration for the user to configure the same.

**Environment**:

**Comment by briantopping** [comment]
This would be essential in a multi-tenant environment that I'm trying to set up. Pacific has support for cephx caps on multiple CephFS deployments, either one of these solutions could provide the necessary isolation.

Question: Would it be possible to wrap existing upgrade existing CephFS PVCs with this functionality when it's ready? Or will everything need to be rebuilt?

**Comment by travisn** [comment]
@Rakshith-R What is the timeline for this?

**Comment by Rakshith-R** [comment]
> @Rakshith-R What is the timeline for this?

Sorry, I missed this ping.
I am not, at the moment, actively working on this but I'll summarise my findings so far below.

Ceph-CSI picks up subvolumegroup corresponding to PVC's clusterID from `rook-ceph-csi-configmap`, if it is not specified, defaults to `csi`.
(In addition, cephcsi creates subvolumegroup if it does not exist, whereas radosnamespace needs to be created beforehand)

Refer: https://github.com/ceph/ceph-csi/blob/64ce5e0949da0e1684456f56d18f89f5850076b1/examples/csi-config-map-sample.yaml#L22

To introduce new Subvolumegroup &/ radosnamespace (#7035) support, new `clusterID`  needs to be introduced into `rook-ceph-csi-configmap` with corresponding subvolumegroup and radosnamespace fields.
This also needs to updated whenever mon failover occurs, similar to how normal `clusterID`  mon ips are updated currently.

And for Rook to keep track of which `clusterID`'s mon ips to update, maybe use new field `rookClusterID`(which cephcsi will ignore).

A new namespaced CR `CephClusterTenant` which takes in subvolumegroup and radosnamespace and  a controller which creates an entry in `rook-ceph-csi-config`, manages them, ensures cleanup of PVC with new clusterID, etc maybe most suitable as per my opinion.

**Comment by travisn** [comment]
What about specifying the subvolume groups inside the CephFilesystem CRD? Then the storage class that consumes the cephfs could specify which subvolume group to use. Or if a new CRD is needed, we just need to be really clear why it is needed.

**Comment by Madhu-1** [comment]
>What about specifying the subvolume groups inside the CephFilesystem CRD? Then the storage class that consumes the cephfs could specify which subvolume group to use. Or if a new CRD is needed, we just need to be really clear why it is needed.

IMHO It should be part of the filesystem CRD  as subvolumegroups are created inside a filesystem and subvolumegroups cannot exist without a filesystem and moreover, the subvolumegroup is to provide isolation within the filesystem. the above is applicable for rados namespace and block pool also.

```json=
[{
	"clusterID": "<cephclusternamespace>-<poolname>-block-<radosnamespace>",
	"monitors": ["mon-ip:port", "mon-ip:port"]
}, {
	"clusterID": "<cephclusternamespace>-<poolname>-b the block CRDlock-<radosnamespace>",
	"monitors": ["mon-ip:port", "mon-ip:port"]
}, {
	"clusterID": "<cephclusternamespace>-<filesystemname>-file-<subvolumegroupname>",
	"monitors": ["192.168.121.236:6789"]
}, {
	"clusterID": "<cephclusternamespace>-<filesystemname>-file-<subvolumegroupname>",
	"monitors": ["mon-ip:port", "mon-ip:port"]
}, {
	"clusterID": "rook-ceph",  //default existing configurations 
	"monitors": ["192.168.121.236:6789"]
}]
```

The above is the CSI configuration am thinking about. the workflow is something like below

## support for Subvolumegroups
* New field will be added to the filesystem CRD which is going to be an array of strings (multiple subvolumegroups)
* When a new subvolume group is created, Rook can create the subvolumegroup (even csi can create subvolumegroup but it makes more sense for Rook to create it) and update the csi configurations and users can make use of the unique clusterID in the storageclass.
* When subvolumegroup is deleted Rook need to if the subvolumegroup is empty or not and take appropriate action

## support for radosnamespace
* New field will be added to the blockpool CRD which is going to be an array of strings (multiple radosnamespaces)
* When a new radosnamespace is created, Rook needs to create radosnamsapce(CephCSI does not create radosnamespace) and update the csi configurations and users can make use of the unique clusterID in the storageclass.
* When radosnamespace is deleted Rook need to if the radosnamespace is empty or not and take appropriate action

The above is a rough idea we can discuss more when its getting implemented.

**Comment by leseb** [comment]
I tend to think that subvolumegroups and rados namespace should have their own CRDs, for the following reasons:

* not clutter the respective CephBlockPool and CephFilesystem specs
* reduce reconcile loops lenght
* easier to react to create/update/delete event, when an array changes, it's not really clear. For instance, if an entry from the list is removed, should the subvolumegroup be removed? What if there is a new entry and one removed? I believe it makes the internal logic more difficult to handle
* subvolume groups and rados namespaces might have quota too, this would mean we need more than a list of names but much more properties. There is probably more as well
* for external mode, one could query the creation of a subvolume without touching the main cephfilesystem which is shared by all consumers

The only thing is the dependency with the CephFilesystem, this won't be the first time we need this, the CephNFS CR does that too.
