### ISSUE TITLE
Add support to create ceph users with different capabilities

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#7037]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

The admin/User should be able to create ceph users to the capabilities he wants.

**What is use case behind this feature:**

With support for rbd namespace https://github.com/rook/rook/issues/7035 and ceph subvolume group creation https://github.com/rook/rook/issues/7036. it makes more sense to expose some CRD to allow users to create users with Restricted capabilities to isolate from other users/tenants.

**Environment**:

**Comment by leseb** [comment]
Like the CephClient CRD?

**Comment by Madhu-1** [comment]
@leseb sorry I didn't notice that we already have a CRD for User creation. Anything pending on that. Maybe we can add more details on how users can customize the different capabilities or we can directly point to the ceph document for the same?

If we have the required support we can close this issue.

**Comment by leseb** [comment]
No worries :). I think we do have the support, last week I completed the migration to use controller-runtime in https://github.com/rook/rook/pull/6958. We have docs too https://rook.io/docs/rook/v1.5/ceph-client-crd.html.

I'd say that we have all we need at the moment. Feel free to close if we are on the same page.

**Comment by Madhu-1** [comment]
Thank you @leseb, Closing this one as we have the support for ceph user creation.
