### ISSUE TITLE
ceph: missing the process to restore mon quorum if all mon are unhealthy

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#7049]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Ceph has a process to restore cluster without healthy mons.

https://docs.ceph.com/en/latest/rados/troubleshooting/troubleshooting-mon/#recovery-using-osds

However, Rook only provides the restoring process with at least one healthy mon.

https://github.com/rook/rook/blob/master/Documentation/ceph-disaster-recovery.md

**What is use case behind this feature:**

**Comment by satoru-takeuchi** [comment]
I've already submitterd PR and it's under review.

**Comment by satoru-takeuchi** [comment]
I'd like to close this ticket for now. See #7154 for more information.

**Comment by travisn** [comment]
@satoru-takeuchi Instead of creating the script, is there some documentation we might create instead? Perhaps it could just point to the ceph documentation, with a few suggestions on how to modify it for Rook's case. It might give some hope of recovery in that disaster scenario.

**Comment by satoru-takeuchi** [comment]
@travisn OK, I'll do it later.

**Comment by satoru-takeuchi** [comment]
This issue will be handled in kubectl-rook-ceph.
https://github.com/rook/kubectl-rook-ceph/issues/74
