### ISSUE TITLE
Add support for CephFS mirroring peers configuration

### ISSUE THREAD

**Issue by leseb** [rook/rook#7063]
- Allow adding peers to configure mirroring between Ceph clusters.
- Add integration tests on Pacific

**Comment by leseb** [comment]
Waiting for https://github.com/ceph/ceph/pull/39050

**Comment by leseb** [comment]
> Waiting for [ceph/ceph#39050](https://github.com/ceph/ceph/pull/39050)

Merged!

Will resume soon.

**Comment by gokcesurenkok** [comment]
when will be this feature merged ?

**Comment by leseb** [comment]
> when will be this feature merged ?

Soon after Ceph 16.2.5 is released.
