### ISSUE TITLE
Can you dynamically resize ( auto-expand ) cephfs volumes ?

### ISSUE THREAD

**Issue by chromafunk** [rook/rook#7065]
I am setting up a cluster, and trying now to determine when to use block storage and shared storage. There are certainly a couple of places where dynamically resized cephfs would work well on our setup. Is this possible ? It's not clear to me if this only works with BRD, or also with CEPHFS ? Is there a document on how to make rook-ceph pvc's auto-expandable on demand ?

Thanks !

**Comment by travisn** [comment]
@chromafunk Yes, rbd and cephfs PVCs support resizing and can be resized as other [K8s volumes](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/). What auto-expansion are you referring to though?

**Comment by chromafunk** [comment]
sorry, but I just kinda started with k8s ... I was referring to, if there is some kind of policy where you can automatically resize volumes when it's reaching a certain threshold. Our first cluster is a centralized monitoring / logging cluster and volumes keep on aggregating data. I was wondering if there is a way to expand volumes on demand. Thank you !

**Comment by travisn** [comment]
No there is not auto-expansion for PVCs that I am aware. A simple solution may be to over-provision the volume. Ceph thinly provisions all volumes, meaning that you can create a volume much larger than you need without reserving space in the cluster.
