### ISSUE TITLE
E2E Framework: rook_test_infra::ValidateAndSetupTestPlatform method fails to "taint" master after k8s cluster creation

### ISSUE THREAD

**Issue by aramisjohnson** [rook/rook#707]
change

_, _, err := k8sClient.ExecuteCmd([]string{"taint", "nodes", "--all", "node-role.kubernetes.io/master--"})

to

_, _, err := k8sClient.ExecuteCmd([]string{"taint", "nodes", "--all", "node-role.kubernetes.io/master-"})

**Comment by dangula** [comment]
This was done as part of PR#699
