### ISSUE TITLE
ceph-volume: lvm batch --prepare failed to add new osds on the same metadata device

### ISSUE THREAD

**Issue by jshen28** [rook/rook#7121]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

ceph version: `ceph version 14.2.15-4`

during testing, we found that provisioning new devices failed on the existing metadata device with the following log,

> by saying existing metadata device, I mean db device that has been used by other osds but still got enough space to
hold other new ones.

```log
2021-02-02 07:32:45.688411 I | cephosd: configuring new device vde
2021-02-02 07:32:45.688442 I | cephosd: using vdd as metadataDevice for device /dev/vde and let ceph-volume lvm batch decide how to create volumes
2021-02-02 07:32:45.688462 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 --block-db-size 32212254720 /dev/vde --db-devices /dev/vdd --report
2021-02-02 07:32:58.652441 D | exec: --> passed data devices: 1 physical, 0 LVM
2021-02-02 07:32:58.652877 D | exec: --> relative data size: 1.0
2021-02-02 07:32:58.655261 D | exec: --> passed block_db devices: 1 physical, 0 LVM
2021-02-02 07:32:58.657862 D | exec: --> 1 fast devices were passed, but none are available
2021-02-02 07:32:58.660411 D | exec: 
2021-02-02 07:32:58.660430 D | exec: Total OSDs: 0
2021-02-02 07:32:58.660434 D | exec: 
2021-02-02 07:32:58.660439 D | exec:   Type            Path                                                    LV Size         % of device
2021-02-02 07:32:58.799061 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 --block-db-size 32212254720 /dev/vde --db-devices /dev/vdd --report --format json
2021-02-02 07:33:12.417586 D | cephosd: ceph-volume reports: []
failed to configure devices: failed to initialize devices: failed to create enough required devices, required: [], actual: []
```

```console
# lsblk
NAME                                                                                                  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vdf                                                                                                   252:80   0  100G  0 disk 
`-ceph--6f08cbde--0caf--4b76--bba6--c291ec63057e-osd--block--8b707153--28ff--4866--b206--6615ca56152f 253:0    0  100G  0 lvm  
vdd                                                                                                   252:48   0  100G  0 disk 
|-ceph--c02fcfce--755a--4bad--9860--382a22c489b2-osd--db--3a94ecb2--3879--43a4--85ee--7eda6102a99f    253:1    0   30G  0 lvm  
`-ceph--c02fcfce--755a--4bad--9860--382a22c489b2-osd--db--9c7531e5--fd68--4a00--8ee8--f8ae67b2ae65    253:5    0   30G  0 lvm  
vde                                                                                                   252:64   0  100G  0 disk 
vdc                                                                                                   252:32   0  100G  0 disk 
`-ceph--817ebec3--026c--42b2--a67b--5d916be298e0-osd--block--47334aa0--9fec--484c--a0d1--4b3a47f3f71c 253:4    0  100G  0 lvm  

# lvs
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  LV                                             VG                                        Attr       LSize    Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  osd-block-8b707153-28ff-4866-b206-6615ca56152f ceph-6f08cbde-0caf-4b76-bba6-c291ec63057e -wi-ao---- <100.00g                                                    
  osd-block-47334aa0-9fec-484c-a0d1-4b3a47f3f71c ceph-817ebec3-026c-42b2-a67b-5d916be298e0 -wi-ao---- <100.00g                                                    
  osd-db-3a94ecb2-3879-43a4-85ee-7eda6102a99f    ceph-c02fcfce-755a-4bad-9860-382a22c489b2 -wi-ao----   30.00g                                                    
  osd-db-9c7531e5-fd68-4a00-8ee8-f8ae67b2ae65    ceph-c02fcfce-755a-4bad-9860-382a22c489b2 -wi-ao----   30.00g                                                    
  lv-docker                                      vg-data                                   -wi-ao----  150.00g                                                    
  lv-kubelet                                     vg-data                                   -wi-ao----  149.00g     
```

Right now I am suspecting that [this](https://github.com/ceph/ceph/blob/391cd0cd46833cb6ad17680e9cf8f36528f99432/src/ceph-volume/ceph_volume/devices/lvm/batch.py#L514) and [this](https://github.com/ceph/ceph/blob/391cd0cd46833cb6ad17680e9cf8f36528f99432/src/ceph-volume/ceph_volume/devices/lvm/batch.py#L137) might cause unexpected behavior.

**Expected behavior:**

new osds could be provisioned on the used metadata device

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 18.04.3 LTS
* Kernel (e.g. `uname -a`):  Linux rookceph03 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.5.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.15-4
* Kubernetes version (use `kubectl version`): 1.14
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by jshen28** [comment]
I am thinking maybe we need to feed all devices, unavailable or not, to lvm batch...

**Comment by jshen28** [comment]
also, is it to good idea to switch to `lvm prepare` without **batch**?

**Comment by travisn** [comment]
@guits Is adding new OSDs with a db-device a supported scenario for c-v? I believe it wasn't supported. Any input on this issue? Thanks!

**Comment by jshen28** [comment]
hmm... btw is replacing a failed disk same as adding a new one?

**Comment by travisn** [comment]
> hmm... btw is replacing a failed disk same as adding a new one?

Correct, they are the same since ceph-volume basically only creates new OSDs for Rook. IIRC ceph-volume has an option to replace an OSD, but not sure it would work in this case either with the metadata device. 

A more robust solution for using the db/wal devices is to base them on PVCs as seen in the cluster-on-pvc.yaml example. In that case, you can have more fine-grained control over the db/wal devices since they each have their own PVC. In other words, you can have three PVCs for each OSD for the db/wal/data devices. If one of them fails, they don't affect other OSDs. You can just throw away the PVCs for that OSD and create new PVCs.

**Comment by jshen28** [comment]
the concern is will it sacrifice performance? will a pvc layer introduce extra latency to OSD? I think it will really nice to allow users adding new devices on the same metadata device.. since a failed device is pretty common scenario..

**Comment by jshen28** [comment]
besides, for c-v in v12.2.12 batch prepare will actually use & extend vgs if necessary, so do you think it sounds like a good idea to adopt c-v and allow using existing db devices again or somehow changes rook logic and switch to maybe directly prepare?

**Comment by jshen28** [comment]
I've created a pr https://github.com/ceph/ceph/pull/39286 and hopes it will make it work for cases of adding new osds.
test is still in progress.

**Comment by guits** [comment]
> @guits Is adding new OSDs with a db-device a supported scenario for c-v? I believe it wasn't supported. Any input on this issue? Thanks!

In fact, it works.

In your case, I guess `/dev/vdc` and `/dev/vdf` are the devices that were already deployed initially both using `/dev/vdd` as db device.
In a second step, you are trying to deploy a new osd `/dev/vde` with still `/dev/vdd` as db device since there's still 30Gb free.

I see the command run was :
```
ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 --block-db-size 32212254720 /dev/vde --db-devices /dev/vdd --report --format json
```
unless I'm missing something, it should have been :
```
ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 --block-db-size 32212254720 /dev/vdc /dev/vdf /dev/vde --db-devices /dev/vdd --report --format json
```

`ceph-volume lvm batch --prepare` expects you to keep passing it the full devices list, even though they are already prepared.

**Comment by jshen28** [comment]
@guits correct, but somehow it is not how rook uses it....

**Comment by guits** [comment]
> @guits hmm, but somehow it is not how rook uses it....

It means rook doesn't consume ceph-volume correctly

> another part is that when I need to have different device classes of osd using the same metadata device...

not sure I'm following you, could you elaborate a bit more?

```
[root@ceph-nautilus ceph_volume]# ceph-volume inventory

Device Path               Size         rotates available Model name
/dev/nvme0n1              10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n10             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n11             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n12             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n13             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n14             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n15             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n16             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n17             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n18             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n19             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n2              10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n20             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n21             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n22             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n23             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n24             10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n3              10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n4              10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n5              10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n6              10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n7              10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n8              10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/nvme0n9              10.74 GB     False   True      ORCL-VBOX-NVME-VER12
/dev/sdaa                 10.74 GB     True    True      VBOX HARDDISK
/dev/sdab                 10.74 GB     True    True      VBOX HARDDISK
/dev/sdac                 10.74 GB     True    True      VBOX HARDDISK
```

**Comment by jshen28** [comment]
@guits for example, I am using `sdb` as metadata device `sdc` & `sdd` will all use `sdb` as metadata device but they will have different device-class assigned.

**Comment by guits** [comment]
> @guits for example, I am using `sdb` as metadata device `sdc` & `sdd` will all use `sdb` as metadata device but they will have different device-class assigned.

@jshen28 sorry but what you say here is still lacking some clarifications, so it's still unclear to me, what do you mean by "but they will have different device-class assigned."?

If `sdc` and `sdd` are both either rotational disks or ssd disks, they will have the same class.

**Comment by jshen28** [comment]
@guits sorry for not being clear.  both `sdc` and `sdd` could be rotational disk but I would like to use different `crush-device-class` for them. such that `ceph osd tree` command could show something like, such that both `osd.1` and `osd.2` use the same 
metadata device

```console
root@stor-mgt01:~# ceph osd tree
ID CLASS WEIGHT   TYPE NAME          STATUS REWEIGHT PRI-AFF 
-1       6 root default                               
-5       6     host storage01                         
 1   hdd-b  3         osd.1          up  1.00000 1.00000 
 4   hdd-a  3         osd.2          up  1.00000 1.00000 
```

**Comment by jshen28** [comment]
Besides, I personally think using the command by enumerating every disk (potentially there could be 20 disks more per node) is pretty anti-intuitive and not very friendly to cloud operators. Why do I need to list all pre-existing disks to make it work?

In my own opinion, if I do not specify slots and give a specific metadata device size, lvm batch does not really need to compute data slots because prepare will not use it anyway. Could you please take look at https://github.com/ceph/ceph/pull/39286, but short circuiting data slots check if metadata device size is given, user/rook does not need to repeatedly input full list of disks.

**Comment by guits** [comment]
> @guits sorry for not being clear. both `sdc` and `sdd` could be rotational disk but I would like to use different `crush-device-class` for them. such that `ceph osd tree` command could show something like, such that both `osd.1` and `osd.2` use the same
> metadata device
> 
> ```
> root@stor-mgt01:~# ceph osd tree
> ID CLASS WEIGHT   TYPE NAME          STATUS REWEIGHT PRI-AFF 
> -1       6 root default                               
> -5       6     host storage01                         
>  1   hdd-b  3         osd.1          up  1.00000 1.00000 
>  4   hdd-a  3         osd.2          up  1.00000 1.00000 
> ```

@jshen28 not sure this is what you are looking for: https://docs.ceph.com/en/latest/ceph-volume/lvm/prepare/#crush-device-class ?
If so, @travisn does rook allow you to consume that option?

**Comment by guits** [comment]
> Besides, I personally think using the command by enumerating every disk (potentially there could be 20 disks more per node) is pretty anti-intuitive and not very friendly to cloud operators. Why do I need to list all pre-existing disks to make it work?
> 
> In my own opinion, if I do not specify slots and give a specific metadata device size, lvm batch does not really need to compute data slots because prepare will not use it anyway. Could you please take look at [ceph/ceph#39286](https://github.com/ceph/ceph/pull/39286), but short circuiting data slots check if metadata device size is given, user/rook does not need to repeatedly input full list of disks.

That's a good question, this is the way `ceph-volume lvm batch prepare` was implemented.
To be frank, I couldn't say why exactly, maybe @andrewschoen has a better insight?

**Comment by travisn** [comment]
> the concern is will it sacrifice performance? will a pvc layer introduce extra latency to OSD? I think it will really nice to allow users adding new devices on the same metadata device.. since a failed device is pretty common scenario..

@jshen28 No, the PVC layer doesn't add any performance overhead. The OSD still has direct access to the device.

> ceph-volume lvm batch --prepare expects you to keep passing it the full devices list, even though they are already prepared.

@guits Aha, that's what we are missing! Although, agreed with @jshen28 that it seems odd to require passing all the device names if they have already been configured.

> @jshen28 not sure this is what you are looking for: https://docs.ceph.com/en/latest/ceph-volume/lvm/prepare/#crush-device-class ?
If so, @travisn does rook allow you to consume that option?

@guits Yes, rook does pass the `--crush-device-class` flag. 
I believe @jshen28 's question is how to pass a different device class for each OSD in this scenario. If you have a single batch command that takes all the devices, they must have the same device class, correct? Or is there a way to specify a different `--crush-device-class` per OSD in the same batch command?

**Comment by guits** [comment]
I think https://github.com/ceph/ceph/pull/39286 addresses all of this

**Comment by travisn** [comment]
> I think [ceph/ceph#39286](https://github.com/ceph/ceph/pull/39286) addresses all of this

Perfect, I hadn't taken a look yet...

**Comment by jshen28** [comment]
@travisn thank you very much for the clarification. 
About the device class part, I guess I still need to issue batch prepare multiple times to use different device class per group of osd.
