### ISSUE TITLE
rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by anilthalari** [rook/rook#7124]
**pod describe**

  Normal   Scheduled               10m                   default-scheduler        Successfully assigned default/wordpress-7b989dbf57-q4mrk to k4
  Normal   SuccessfulAttachVolume  10m                   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-d9ebb103-cdd6-456b-9328-49e2ab27a12f"
  Warning  FailedMount             8m34s                 kubelet                  Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[default-token-xm7ln wordpress-persistent-storage]: timed out waiting for the condition
  Warning  FailedMount             8m29s                 kubelet                  MountVolume.MountDevice failed for volume "pvc-d9ebb103-cdd6-456b-9328-49e2ab27a12f" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             106s (x3 over 6m18s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[wordpress-persistent-storage], unattached volumes=[wordpress-persistent-storage default-token-xm7ln]: timed out waiting for the condition
  Warning  FailedMount             15s (x11 over 8m29s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-d9ebb103-cdd6-456b-9328-49e2ab27a12f" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000002-78f1f071-6145-11eb-b970-4ad523fb3381 already exists

* Bug Report

**Deviation from expected behavior:**
The pvc is not mounted
**Expected behavior:**
mount the pvc on node

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs:

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
lxd setup on bare metals
1 master & 3 workers
all lxc containers are ubuntu18.04
harddisks : 3 ssds 
* OS (e.g. from /etc/os-release):ubuntu 18.04
* Kernel (e.g. `uname -a`): 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.5.6
* Storage backend version (e.g. for ceph do `ceph -v`):15.2.5
* Kubernetes version (use `kubectl version`):1.20
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph  use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): 3 osds up

**Comment by travisn** [comment]
@anilthalari Does this [csi troubleshooting guide](https://www.mrajanna.com/troubleshooting-cephcsi/) help?

**Comment by anilthalari** [comment]
is there any extra configuration setup required for lxc kubernetes runtime(crio).

**Comment by Madhu-1** [comment]
@anilthalari take a look at https://github.com/ceph/ceph-csi/issues/1820 it might help.

**Comment by anilthalari** [comment]
> @anilthalari Does this [csi troubleshooting guide](https://www.mrajanna.com/troubleshooting-cephcsi/) help?

2021-02-03 12:18:42.347839 E | ceph-crashcollector-controller: node reconcile failed on op "unchanged": Operation cannot be fulfilled on deployments.apps "rook-ceph-crashcollector-k2": the object has been modified; please apply your changes to the latest version and try again

**Comment by anilthalari** [comment]
**operatorlogs**

2021-02-03 12:18:42.347839 E | ceph-crashcollector-controller: node reconcile failed on op "unchanged": Operation cannot be fulfilled on deployments.apps "rook-ceph-crashcollector-k2": the object has been modified; please apply your changes to the latest version and try again.
2021-02-03 12:18:39.893931 E | ceph-crashcollector-controller: node reconcile failed on op "unchanged": Operation cannot be fulfilled on deployments.apps "rook-ceph-crashcollector-k1": the object has been modified; please apply your changes to the latest version and try again
2021-02-03 12:17:30.420388 E | ceph-crashcollector-controller: node reconcile failed on op "unchanged": Operation cannot be fulfilled on deployments.apps "rook-ceph-crashcollector-k4": the object has been modified; please apply your changes to the latest version and try again

**Comment by anilthalari** [comment]
***ceph health detail***
unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] RADOS object not found (error connecting to the cluster)

**Comment by anilthalari** [comment]
[ceph-volume.log](https://github.com/rook/rook/files/5918604/ceph-volume.log)
stderr Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
stderr Failed to find physical volume "/dev/sdb".
Running command: /usr/bin/ceph-bluestore-tool show-label --dev /dev/sdb
stderr unable to read label for /dev/sdb: (2) No such file or directory
Running command: /usr/bin/ceph-bluestore-tool show-label --dev /dev/sdb
stderr unable to read label for /dev/sdb: (2) No such file or directory

**Comment by anilthalari** [comment]
[syslog.txt](https://github.com/rook/rook/files/5918821/syslog.txt)
[syslog.txt](https://github.com/rook/rook/files/5918857/syslog.txt)

**Comment by anilthalari** [comment]
***csi-provisioner***
1 csi-provisioner.go:121] Version: v2.0.0
I0203 12:15:23.097220       1 csi-provisioner.go:135] Building kube configs for running in cluster...
I0203 12:15:23.118155       1 connection.go:153] Connecting to unix:///csi/csi-provisioner.sock
I0203 12:15:25.025813       1 common.go:111] Probing CSI driver for readiness
W0203 12:15:25.029051       1 metrics.go:142] metrics endpoint will not be started because `metrics-address` was not specified.
I0203 12:15:25.036752       1 leaderelection.go:243] attempting to acquire leader lease  rook-ceph/rook-ceph-rbd-csi-ceph-com...
***csi-resizer***
I0203 12:15:23.525744       1 main.go:79] Version : v1.0.0
I0203 12:15:23.527588       1 connection.go:153] Connecting to unix:///csi/csi-provisioner.sock
I0203 12:15:24.528790       1 common.go:111] Probing CSI driver for readiness
W0203 12:15:24.558910       1 metrics.go:142] metrics endpoint will not be started because `metrics-address` was not specified.
I0203 12:15:24.566111       1 leaderelection.go:243] attempting to acquire leader lease  rook-ceph/external-resizer-rook-ceph-rbd-csi-ceph-com
***csi-snapshotter***
I0203 12:15:24.056389       1 main.go:87] Version: v3.0.0
I0203 12:15:24.057771       1 connection.go:153] Connecting to unix:///csi/csi-provisioner.sock
W0203 12:15:25.061732       1 metrics.go:142] metrics endpoint will not be started because `metrics-address` was not specified.
I0203 12:15:25.061777       1 common.go:111] Probing CSI driver for readiness
I0203 12:15:25.066921       1 leaderelection.go:243] attempting to acquire leader lease  rook-ceph/external-snapshotter-leader-rook-ceph-rbd-csi-ceph-com...
***driver-registrar***
I0203 12:15:15.585759    4780 main.go:112] Version: v2.0.1
I0203 12:15:15.586250    4780 connection.go:151] Connecting to unix:///csi/csi.sock
I0203 12:15:16.622781    4780 node_register.go:55] Starting Registration Server at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0203 12:15:16.623084    4780 node_register.go:64] Registration Server started at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0203 12:15:16.623709    4780 node_register.go:86] Skipping healthz server because port set to: 0
I0203 12:15:17.041497    4780 main.go:79] Received GetInfo call: &InfoRequest{}
I0203 12:15:17.121314    4780 main.go:89] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
***csi-attacher***
I0203 12:15:16.765492       1 main.go:91] Version: v3.0.0
I0203 12:15:16.771994       1 connection.go:153] Connecting to unix:///csi/csi-provisioner.sock
I0203 12:15:17.775128       1 common.go:111] Probing CSI driver for readiness
W0203 12:15:17.780936       1 metrics.go:142] metrics endpoint will not be started because `metrics-address` was not specified.
I0203 12:15:17.799913       1 leaderelection.go:243] attempting to acquire leader lease  rook-ceph/external-attacher-leader-rook-ceph-rbd-csi-ceph-com...
I0203 12:15:17.828686       1 leaderelection.go:253] successfully acquired lease rook-ceph/external-attacher-leader-rook-ceph-rbd-csi-ceph-com
I0203 12:15:17.828845       1 controller.go:121] Starting CSI attacher
