### ISSUE TITLE
Bucket quota can't be updated

### ISSUE THREAD

**Issue by tumido** [rook/rook#7146]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When creating `ObjectBucketClaim` user can specify `.spec.additionalConfig` values like `maxSize` and `maxObjects`. This value is enforced as a quota on the bucket. However if user later decides to update the spec and increase the quota, this change doesn't trigger reconciliation. New quota is not propagated to `ObjectBucket` resource or to the Ceph back-end bucket.

**Expected behavior:**
Quota should be updated.

**How to reproduce it (minimal and precise):**
1. Create`ObjectBucketClaim` with `maxSize` set to a value
2. `oc patch obc/RESOURCE_NAME -p '{"spec": {"additionalConfig": {"maxSize": "different value"}}
3. Compare `ObjectBucketClaim` and `ObjectBucket` and the actual quota. `maxSize` is changed only in `ObjectBucketClaim`

**File(s) to submit**:
n/a

**Environment**:
* OS (e.g. from /etc/os-release): RHEL
* Kernel (e.g. `uname -a`): 4.18
* Cloud provider or hardware configuration: Openshift 4.5
* Rook version (use `rook version` inside of a Rook Pod): `4.5-55.6dba87fd.release_4.5`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 14.2.8-111.el8cp (2e6029d57bc594eceba4751373da6505028c2650) nautilus (stable)`
* Kubernetes version (use `kubectl version`): client `v1.19.4`, server `v1.18.3`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

**Comment by 4n4nd** [comment]
still relevant
