### ISSUE TITLE
ceph: Rook should clean up OSD status ConfigMaps

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#7164]
**Is this a bug report or feature request?**
* Feature Request

Rook-Ceph often leaves dangling OSD status ConfigMaps from OSD provisioning. Occasionally these cause issues for users where they must delete configmaps before OSD provisioning can succeed successfully. 

Possible strategies Rook could take:
- remove ALL OSD provisioning status ConfigMaps after the OSD provisioning loop completes
   - this is good but possibly doesn't help since OSD provisioning must complete for the ConfigMaps to be deleted (maybe this should happen also on OSD provisioning timeout)
- make the ConfigMap owner reference be to the OSD Provisioning Job so that it gets deleted when the Job is deleted
   - this is good but doesn't help if Jobs are not deleted (like on an operator crash) 
- Other options?

**Comment by travisn** [comment]
> **Is this a bug report or feature request?**
> 
> * Feature Request
> 
> Rook-Ceph often leaves dangling OSD status ConfigMaps from OSD provisioning. Occasionally these cause issues for users where they must delete configmaps before OSD provisioning can succeed successfully.
> 
> Possible strategies Rook could take:
> 
> * remove ALL OSD provisioning status ConfigMaps after the OSD provisioning loop completes
>   
>   * this is good but possibly doesn't help since OSD provisioning must complete for the ConfigMaps to be deleted (maybe this should happen also on OSD provisioning timeout)
> * make the ConfigMap owner reference be to the OSD Provisioning Job so that it gets deleted when the Job is deleted

The OSD provisioning jobs don't ever get removed until the next time they run, so this won't be an option.

> * Other options?

I'm thinking that at the start of an OSD reconcile, we could delete all the existing status configmaps. My only hesitation about that is if an osd prepare job is still in progress, there may be a status misfire when it is completed. If an osd prepare job is still in progress we don't delete it, but otherwise we delete those jobs before starting new ones.

**Comment by BlaineEXE** [comment]
Maybe we can delete all configmaps that don't have a running prepare job associated with them. And we can furthermore check the prepare jobs and kill them and the configmaps if they aren't completed and were started more than some number of minutes ago (equal to OSD provisioning timeout?).

**Comment by BlaineEXE** [comment]
I did find something wrong in my testing. The below YAML doesn't propagate the `deviceFilter` to preparing OSDs on nodes. Somehow it is getting lost, as evidenced by the debug message at bottom. I don't think my changes would affect this, but I will investigate.

```yaml
  storage:
    useAllNodes: true
    useAllDevices: false
    deviceFilter: ^sd[a]
```

```
2021-02-10 00:45:43.440377 D | op-osd: storage nodes: [{Name:node1 Resources:{Limits:map[] Requests:map[]} Config:map[] Selection:{UseAllDevices:<nil> DeviceFilter: DevicePathFilter: Devices:[] Directories:[] VolumeClaimTemplates:[]}} {Name:node2 Resources:{Limits:map[] Requests:map[]} Config:map[] Selection:{UseAllDevices:<nil> DeviceFilter: DevicePathFilter: Devices:[] Directories:[] VolumeClaimTemplates:[]}} {Name:master Resources:{Limits:map[] Requests:map[]} Config:map[] Selection:{UseAllDevices:<nil> DeviceFilter: DevicePathFilter: Devices:[] Directories:[] VolumeClaimTemplates:[]}}]
```
