### ISSUE TITLE
Unable to delete replicapool on a ceph cluster

### ISSUE THREAD

**Issue by aasraoui** [rook/rook#7165]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by aasraoui** [comment]
root@rook-ceph-tools-664b7555b8-5bjdg /]# ceph version
ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

uname -a
3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux



ceph status
  cluster:
    id:     de2ab245-7f34-47ba-85fc-3e0e345b0c7c
    health: HEALTH_WARN
            clock skew detected on mon.b, mon.d
            Reduced data availability: 65 pgs inactive
            OSD count 0 < osd_pool_default_size 3  services:
    mon: 3 daemons, quorum a,b,d (age 26h)
    mgr: a(active, since 26h)
    osd: 0 osds: 0 up, 0 in  data:
    pools:   3 pools, 65 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             65 unknown

yaml file:
/rook/cluster/examples/kubernetes/ceph/cluster/cluster.yaml

**Comment by travisn** [comment]
@aasraoui Check the operator log, it likely shows an error about block images still existing in the pool so the pool cannot be deleted. If you want to override this and force delete the pool, you will need to remove the finalizer on the CR as described [here](https://rook.github.io/docs/rook/v1.5/ceph-teardown.html#removing-the-cluster-crd-finalizer).
