### ISSUE TITLE
Upgraded to 1.5.6: Pods still fail to mount volumes - 'fsGroupPolicy seen as nil or empty'

### ISSUE THREAD

**Issue by kyle-rf** [rook/rook#7175]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Fails to mount the volume to pod after latest version upgrade.

**Expected behavior:**
Creating pods can successfully mount rook-ceph-block PVCs.

**How to reproduce it (minimal and precise):**

Running Kubernetes Cluster Version 1.20.0
Performed Upgrade of Rook:
  Reapplied crds.yaml, skipped, common.yaml (no change)
  Changed rook/ceph image to "rook/ceph:v1.5.6-45.gac0d0d" in operator.yaml
  Ensured operator.yaml contains all additional new values, for example: 'CSI_RBD_FSGROUPPOLICY: "ReadWriteOnceWithFSType"' 
  Deleted csidriver.storage.k8s.io/rook-ceph.cephfs.csi.ceph.com
  Deleted csidriver.storage.k8s.io/rook-ceph.rbd.csi.ceph.com 
  Reapplied operator.yaml and referenced commands from https://github.com/rook/rook.github.io/blob/master/docs/rook/v1.5/ceph-upgrade.md  for monitoring and confirming all deployments have upgraded to 1.5.6-45.gac0d0d
Deleted all csi provisioner and plugin pods, and confirmed they were recreated.
Confirmed the active configmap for operator contains FSGROUPPOLICY variables:
`
$ kubectl -n rook-ceph get -o yaml configmap/rook-ceph-operator-config | grep "FSGROUPPOLICY"

 CSI_CEPHFS_FSGROUPPOLICY: ReadWriteOnceWithFSType
  CSI_RBD_FSGROUPPOLICY: ReadWriteOnceWithFSType
      {"apiVersion":"v1","data":{"CSI_CEPHFS_FSGROUPPOLICY":"ReadWriteOnceWithFSType","CSI_ENABLE_CEPHFS_SNAPSHOTTER":"true","CSI_ENABLE_RBD_SNAPSHOTTER":"true","CSI_FORCE_CEPHFS_KERNEL_CLIENT":"true","CSI_PLUGIN_NODE_AFFINITY":"node-role.kubernetes.io/ceph-infra=ceph-infra","CSI_PROVISIONER_NODE_AFFINITY":"node-role.kubernetes.io/ceph-infra=ceph-infra","CSI_RBD_FSGROUPPOLICY":"ReadWriteOnceWithFSType","ROOK_CSI_ALLOW_UNSUPPORTED_VERSION":"false","ROOK_CSI_ENABLE_CEPHFS":"true","ROOK_CSI_ENABLE_GRPC_METRICS":"true","ROOK_CSI_ENABLE_RBD":"true","ROOK_OBC_WATCH_OPERATOR_NAMESPACE":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"rook-ceph-operator-config","namespace":"rook-ceph"}}
        f:CSI_CEPHFS_FSGROUPPOLICY: {}
        f:CSI_RBD_FSGROUPPOLICY: {}
`

Checked the recreated CSI Drivers for spec.fsGroupPolicy being set.  It is a declared field, but still not set:
`apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  creationTimestamp: "2021-02-05T20:02:42Z"
  managedFields:
  - apiVersion: storage.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:attachRequired: {}
        f:fsGroupPolicy: {}
        f:podInfoOnMount: {}
        f:volumeLifecycleModes: {}
    manager: rook
    operation: Update
    time: "2021-02-05T20:02:42Z"
  name: rook-ceph.rbd.csi.ceph.com
  resourceVersion: "59482163"
  selfLink: /apis/storage.k8s.io/v1/csidrivers/rook-ceph.rbd.csi.ceph.com
  uid: d17c0cbe-4d8d-4b6b-9d4f-f4438ba76207
spec:
  attachRequired: true
  podInfoOnMount: false
  volumeLifecycleModes:
  - Persistent`

Attempted to create a test resource, to confirm mount will fail:
`---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-block-vol-3
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: block-volume-test
  namespace: default
spec:
  containers:
    - name: block-volume-test
      image: ubuntu
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: block-vol
          mountPath: "/tmp/persistent"
  volumes:
    - name: block-vol
      persistentVolumeClaim:
        claimName: ceph-block-vol-3`

A StorageClass: rook-ceph-block PVC is created, but still fails to mount the volume to the pod with the following info in pod description:
`
 Normal   SuccessfulAttachVolume  30m                   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-b80bab89-1380-48f3-93c7-03514eb31173"
  Warning  FailedMount             16m (x2 over 21m)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[block-vol], unattached volumes=[default-token-ctwgw block-vol]: timed out waiting for the condition
  Warning  FailedMount             7m48s (x8 over 28m)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[block-vol], unattached volumes=[block-vol default-token-ctwgw]: timed out waiting for the condition
  Warning  FailedMount             3m40s (x21 over 30m)  kubelet                  MountVolume.NewMounter initialization failed for volume "pvc-b80bab89-1380-48f3-93c7-03514eb31173" : kubernetes.io/csi: expected valid fsGroupPolicy, received nil value or empty string
`

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.2
* Kernel (e.g. `uname -a`): 5.4.0-65
* Cloud provider or hardware configuration: Baremetal
* Rook version (use `rook version` inside of a Rook Pod): v1.5.6-45.gac0d0d0
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.8
* Kubernetes version (use `kubectl version`): v1.19.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by kyle-rf** [comment]
After reviewing Rook's code, I suspected issue is actually directly related to Kubernetes.

Although the feature CSIFSGroupPolicy is supposed to be enabled by default in Kubernetes 1.20.  I had to explicitly set it on kubelet and kube-apiserver in order for the csidriver resources to successfully set the parameter.

I am able to set it now.  Not a bug in Rook, closing ticket.

**Comment by derek-eb** [comment]
Hi @kyle-rf , would you mind to let me know how do you set the parameter in detail?

**Comment by kyle-rf** [comment]
Hi @derek-eb,

On every node of my cluster I edited the "kubeadm-flags.env" file.  It was located at /var/lib/kubelet/kubeadm-flag.env on my systems.  Then restart the kubelet service on all nodes after editing the file.

For example, my file looks like this: 

`
KUBELET_KUBEADM_ARGS="--network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2 \
	--feature-gates=CSIVolumeFSGroupPolicy=true"
`

Then on the Control-Plane nodes I edited the "kube-apiserver.yaml" file.  This was located at /etc/kubernetes/manifests/kube-apiserver.yaml.  Under "spec.containers.command.kube-apisserver": Add another line for the feature gate.

It will look something like this:

`
spec:
   containers:
   - command:
      - kube-apiserver
      -  --feature-gates=CSIVolumeFSGroupPolicy=true
`

You do not need to restart anything after this change.  This component will pull in the change automatically.

Then try creating a new CSIDriver resource in Kubernetes and check to see that FSGroupPolicy is now being set.

**Comment by devlifealways** [comment]
Hi everyone, 
  I'm not sure if it's still a relevant matter, but tweaking [Kubernetes' feature-gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is not always an option, for instance, we're running Rook on OVH cloud, which is not an option. as all the control-plane is obfuscated (black-box). Is there anything else we can do ?

**Comment by kyle-rf** [comment]
> Hi everyone,
> I'm not sure if it's still a relevant matter, but tweaking [Kubernetes' feature-gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is not always an option, for instance, we're running Rook on OVH cloud, which is not an option. as all the control-plane is obfuscated (black-box). Is there anything else we can do ?

Hi @devlifealways,
The feature is enabled by default on Kubernetes v1.20.  So I believe if you're able to upgrade the Kubernetes cluster, then you will have fsGroupPolicy.  In the case of my own cluster, I later realized I had not completed the Kubernetes upgrade completely.  Though running a kubectl get nodes command would show a version 1.20.x, there were additional steps that needed to complete the upgrade.

You can see which version the cluster is actually running at with the command: **kubectl version**
Take a look at the **Server Version** section in the command output.  For me I was still on 1.19 in this output, despite the **get nodes** commands showing the nodes were on 1.20.  After fully completing the upgrade, I was able to remove the feature-gate from being set explicitly/manually.

With that, my guess is your cluster is on a lower version than 1.20.  If you can get the cluster upgraded, then fsGroupPolicy should be available without needing to set the feature-gate.
