### ISSUE TITLE
ceph: object store should support HTTPS-only gateways

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#7189]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently CephObjectStore supports `gateway:port` (HTTP) and optionally `gateway:securePort` (HTTPS).
Rook should support creating HTTPS-only CephObjectStores where gateways only have `securePort` connections (i.e., `gateway:port = 0`. Currently, setting `gateway:port = 0` gives an error that the required value is greater than `1`.

@subhamkrai added `securePort` functionality ~4 months ago I believe. @alimaredia may have input here also.

slack reference: https://rook-io.slack.com/archives/CK9CF5H2R/p1612890362394300

**Comment by BlaineEXE** [comment]
This may merely be an issue where the user needs to upgrade from Rook v1.4.x to v1.5.x.

**Comment by leseb** [comment]
I was under the impression this was already working...

**Comment by BlaineEXE** [comment]
@subhamkrai added this feature in PR https://github.com/rook/rook/pull/5986. I will close this as it should be included in Rook v1.5. If there are further issues, feel free to comment on this PR, and we will reopen it.

**Comment by ron1** [comment]
When I tried removing CephObjectStore spec.gateway.port on Rook 1.5.6, the rgw pods started crashlooping I think because the liveness probe was failing. Does that make sense?
