### ISSUE TITLE
Disable hostnetworking for CSI drivers

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#7203]
currently, cephcsi daemonset pods are using the hostnetworking by default. with https://github.com/ceph/ceph-csi/pull/1450 we don't need hostnetworking anymore for the RBD driver and the CephFS driver is already working fine without hostnetworking (tested during multus integration).

We can provide an option to disable the hostnetworking for now. For the existing cluster after the upgrade cephcsi will still use the hostnetworking (to avoid issues if something is present). 

If anyone wants to try out without hostnetworking we can have an option (`CSI_DISABLE_HOSTNETWORK`) to disable hostnetworking. Maybe after a few cycles, we can disable hostnetworking by default for CSI pods.

Note:-   For this feature, we need a new cephcsi release. This PR is not part of (v3.2.1)

cc @idryomov @dillaman @travisn @leseb @nixpanic

**Comment by Madhu-1** [comment]
cc @humblec

**Comment by leseb** [comment]
I thought we had discussed that is https://github.com/rook/rook/pull/6310, isn't this enough https://github.com/rook/rook/pull/6310#issuecomment-756718432?

**Comment by Madhu-1** [comment]
@leseb sorry I totally forgot about the effort. Thanks for the reminder. for the safer side. configuration to enable hostnetworking is missing in that.

**Comment by idryomov** [comment]
As I said in https://github.com/ceph/ceph-csi/pull/1450 more than once, I think we need to unify multus and non-multus configurations, i.e. use pod networking with noudev mapping option in all cases.

One particular issue with host networking that came up is host port allocation.  It appears that ceph-csi is using port tcp/9091 to its expose metrics but that port is going to be taken by ovn-kubernetes network provider.  Rather than picking another port for the next ceph-csi release and hoping it remains free for the foreseeable future, let's use this opportunity to move off of host networking and iron out any kinks associated with that.

**Comment by leseb** [comment]
> @leseb sorry I totally forgot about the effort. Thanks for the reminder. for the safer side. configuration to enable/disable hostnetworking is missing in that. Maybe someone wants to use pod networking instead of hostnetworking .

Right, we still need a flag to enable/disable host-networking on the Operator config.

**Comment by travisn** [comment]
> > @leseb sorry I totally forgot about the effort. Thanks for the reminder. for the safer side. configuration to enable/disable hostnetworking is missing in that. Maybe someone wants to use pod networking instead of hostnetworking .
> 
> Right, we still need a flag to enable/disable host-networking on the Operator config.

@Madhu-1 @leseb Can we just always disable host networking on the CSI driver as long as the CSI driver and Ceph version numbers have the required fixes? Or is there any scenario where host networking is still required?

**Comment by Madhu-1** [comment]
> > > @leseb sorry I totally forgot about the effort. Thanks for the reminder. for the safer side. configuration to enable/disable hostnetworking is missing in that. Maybe someone wants to use pod networking instead of hostnetworking .
> > 
> > 
> > Right, we still need a flag to enable/disable host-networking on the Operator config.
> 
> @Madhu-1 @leseb Can we just always disable host networking on the CSI driver as long as the CSI driver and Ceph version numbers have the required fixes? Or is there any scenario where host networking is still required?

No dependency with the cephcsi and ceph version because it's a CLI change as long as the base image of cephcsi has the flag it should work without any issue.

Hostnetworking might be required for some people https://github.com/rook/rook/pull/6310#issuecomment-697968329. we can disable it by default. if we don't provide the option to control it if someone wants to switch to hostnetworking either they have to use the old rook version or we need to do a new release.

The question is do we need to provide an option to enable or disable hostnetworking and go step by step or disable it completely?

**Comment by humblec** [comment]
> > > @leseb sorry I totally forgot about the effort. Thanks for the reminder. for the safer side. configuration to enable/disable hostnetworking is missing in that. Maybe someone wants to use pod networking instead of hostnetworking .
> > 
> > 
> > Right, we still need a flag to enable/disable host-networking on the Operator config.
> 
> @Madhu-1 @leseb Can we just always disable host networking on the CSI driver as long as the CSI driver and Ceph version numbers have the required fixes? Or is there any scenario where host networking is still required?

Yeah, imo, its good to disable it by default as we dont have the dependency any more for both of our plugins. But when we disable, its good to control it via knob so that if someone want to enable it, they could do so and we can also a fall back easily if needed by this  controlling option.

**Comment by travisn** [comment]
To capture a separate discussion:
- The default will be to disable host networking for the csi driver, starting in Rook v1.6
- Upgraded clusters will still default to host networking enabled in the csi driver, just to ensure no surprises
- Example manifests will set host networking to be disabled by default in the csi driver
- A setting will be available in the `rook-ceph-operator-config` configmap that allows enabling/disabling host networking on the csi driver

**Comment by phoenix-frozen** [comment]
I think this got broken? In Rook 1.18.7 the value `CSI_ENABLE_HOST_NETWORK` is only ever stored to `CSIParam.EnableCSIHostNetwork`, which value is in turn never read again. Is that intended?

**Comment by Madhu-1** [comment]
> I think this got broken? In Rook 1.18.7 the value `CSI_ENABLE_HOST_NETWORK` is only ever stored to `CSIParam.EnableCSIHostNetwork`, which value is in turn never read again. Is that intended?

@phoenix-frozen i replied on another bug you have opened, Lets use it for discussion
