### ISSUE TITLE
build: publish helm charts and other yaml

### ISSUE THREAD

**Issue by bassam** [rook/rook#721]
This can be done by adding a new helm.sh script to the build/release directory. The docs script would support the build, publish, promote and cleanup actions. 

We should also consider snapshotting all our yaml files, replacing the version numbers etc. and pushing them to our S3 bucket.

**Comment by jbw976** [comment]
This would be nice to have for 0.5, but not required.

**Comment by jbw976** [comment]
@bassam is there another ticket tracking the snapshotting/publishing with version numbers of our yaml files too?

**Comment by bassam** [comment]
no. I'll create one.
