### ISSUE TITLE
Extract API into separate module with minimal dependencies

### ISSUE THREAD

**Issue by abursavich** [rook/rook#7212]
Because this module imports `k8s.io/kubernetes`, its go.mod is a rats nest of gigantic dependencies and module replace hacks which are foisted upon any user that wants to use the rook API packages.

If the dependency on `k8s.io/kubernetes` cannot be removed, it would be kind to extract the API packages (i.e. `github.com/rook/rook/pkg/apis/...`) to their own module (e.g. `github.com/rook/api/...`) which would have minimal dependencies.

**Comment by travisn** [comment]
@abursavich Ddi you work through the rat's nest already? I don't see the refactoring happening unless there is more demand for it. Working with a single repo simplifies a lot of aspects.

**Comment by abursavich** [comment]
I did pull out `k8s.io/kubernetes` ~3mo ago: https://github.com/abursavich/rook/commits/remove-kk

I'll try to sync it up with master soon and send a PR if it'd be welcome.

**Comment by travisn** [comment]
@abursavich Looking at your branch, it is much simpler than I was imagining, or maybe I didn't follow what you were proposing initially. Yes please do open a PR, thanks!

**Comment by abursavich** [comment]
Moving the API to a module with minimal dependencies would be the ideal solution for users of the API, but understandably it's a pain to manage. Getting rid of `k8s.io/kubernetes` helps a lot, but I think there's still a hairy dependency left behind on `github.com/kubernetes-incubator/external-storage`. It's been deprecated and is being replaced out with another module, but I haven't been able to dig into that one yet.

**Comment by prazumovsky** [comment]
@leseb @travisn Can we backport this patch to 1.6 release?

**Comment by travisn** [comment]
I'm fine with the backport, our bot just can't open the PR since it includes a github action.
@abursavich Want to open the backport PR to release-1.6 with the commits cherry-picked?

**Comment by abursavich** [comment]
Sure, I can open a PR for that.

**Comment by prazumovsky** [comment]
@abursavich @travisn thanks!
