### ISSUE TITLE
publish on quay.io

### ISSUE THREAD

**Issue by ibotty** [rook/rook#7213]
With docker.io rate limits, it is sometimes not possible to fetch images.

**Comment by leseb** [comment]
Thanks for reporting this, we will investigate that possibility soon.

**Comment by jbw976** [comment]
Hey there @ibotty, thanks for bringing this up.  You've seen this in your clusters now? Any chance you can show what the error looks like? i haven't seen it yet myself and I'd love to know more about how it shows itself.  Thank you!

**Comment by ibotty** [comment]
Yes, I have seen that on several on my clusters.  Unfortunately I don't have any events anymore.  It was the usual 

```
kubelet: Failed to pull image XXX: rpc error: code = Unknown desc = Error reading manifest latest in docker.io/rook/ceph:v1.5.7: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Or similar.

**Comment by leseb** [comment]
@jbw976 do you know who owns Rook's quay org at the moment? Thanks!

**Comment by jbw976** [comment]
I think @travisn and I both have access to it as admins.  We can follow up privately for any chances needed :)

**Comment by travisn** [comment]
The rate limiting is supposed to be lifted now for the Rook project. @ibotty Shall we close this or are you still seeing any issues

**Comment by ibotty** [comment]
I only see it when updating rook.  I can try to simulate it again, but I would trust your assertion and reopen if I run into it again.
