### ISSUE TITLE
Update Disaster Recovery procedure for Mon Quorum - command terminated with exit code 137

### ISSUE THREAD

**Issue by mduasope** [rook/rook#7214]
* Feature Request

**What should the feature do:**
We have followed the steps from 
https://rook.io/docs/rook/v1.5/ceph-disaster-recovery.html
and we may fail to complete the whole procedure.

I tried to follow the steps assuming mon-c was the good one:

BUT I was stuck on this step:

Patch the rook-ceph-mon-b Deployment to run a sleep instead of the ceph mon command:
kubectl -n rook-ceph patch deployment rook-ceph-mon-b -p '{"spec": {"template": {"spec": {"containers": [{"name": "mon", "command": ["sleep", "infinity"], "args": []}]}}}}' 

After that I connected to the mon-c:

$ kubectl exec -it rook-ceph-mon-c-68656c784b-9d426  bash

...BUT after a few seconds (maybe 30 secs) the session finish with "command terminated with exit code 137"

So I had not enough time to perform all the steps required on that pod
and also some minutes later, the mon went into a "CrashLoopBackOff"
rook-ceph-mon-c-68656c784b-9d426                                  0/1     CrashLoopBackOff        5          7m22s

I recovered this with :
oc replace --force -f rook-ceph-mon-c-deployment-5Feb.yaml 

..and a new mon-c was restarted , ready to start the procedure again.

The reason for this pod mon-c crashing was the "livenessprobe" , the deploy spec we can see:

       livenessProbe:
          exec:
            command:
            - env
            - -i
            - sh
            - -c
            - ceph --admin-daemon /run/ceph/ceph-mon.c.asok mon_status
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

Solution is to disable it:
oc patch deployment rook-ceph-mon-c  --type json   -p='[{"op": "remove", "path": "/spec/template/spec/containers/0/livenessProbe"}]'

..and then run:

oc patch deployment rook-ceph-mon-c -p '{"spec": {"template": {"spec": {"containers": [{"name": "mon", "command": ["sleep", "infinity"], "args": []}]}}}}'

The purpose of this feature request is to enhance the document with this additional step after the sentence

Patch the rook-ceph-mon-b Deployment to run a sleep instead of the ceph mon command:

Disable "livenessprobe"  to avoid pod to crash after a few secs :
oc patch deployment rook-ceph-mon-c  --type json   -p='[{"op": "remove", "path": "/spec/template/spec/containers/0/livenessProbe"}]'

**What is use case behind this feature:**
N/A

**Environment**:
We have tried that on an env with OCS version: 4.6.

**Comment by travisn** [comment]
This doc was already updated with the removal of the liveness probe in #7029.
