### ISSUE TITLE
RBAC issues when creating ceph cluster on different namespace

### ISSUE THREAD

**Issue by Jasper-Ben** [rook/rook#7226]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The `rook-ceph-detect-version` job created by the rook operator fails with

```Warning  FailedCreate  1s (x2 over 11s)  job-controller  Error creating: pods "rook-ceph-detect-version-" is forbidden: error looking up service account rook-ceph-mirror/rook-ceph-cmd-reporter: serviceaccount "rook-ceph-cmd-reporter" not found```

**Expected behavior:**
Creating a ceph cluster within a namespace diverging from the one the rook operator resides in, should cause the rook operator to successfully initialize it, if `currentNamespaceOnly: false` is set during rook installation (helm default)

**How to reproduce it (minimal and precise):**
- Install the rook operator into the rook-ceph namespace, as described [here](https://rook.io/docs/rook/v1.5/helm-operator.html).
- Try to initialize a cluster on a diverging namespace (e.g. rook-ceph-mirror)

**File(s) submitted**:

* [Cluster CR (custom resource)](https://github.com/rook/rook/files/5981929/cluster-mirror.txt)

**Environment**:
* OS (e.g. from /etc/os-release): flatcar linux v2605.12.0
* Kernel (e.g. `uname -a`): 5.4.92-flatcar
* Cloud provider or hardware configuration: - 
* Rook version (use `rook version` inside of a Rook Pod): 1.5.6
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.8
* Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): -

**Comment by Jasper-Ben** [comment]
I tried to work around this issue by recreating the rules, rulebindings and serviceaccounts within the desired namespace. However now I run into https://github.com/rook/rook/issues/6448

**Comment by Jasper-Ben** [comment]
Found https://github.com/rook/rook/pull/5573, which would resolve this, but does not have a related issue, thus keeping this open.

**Comment by travisn** [comment]
@Jasper-Ben Does [this topic](https://rook.github.io/docs/rook/v1.5/ceph-advanced-configuration.html#using-alternate-namespaces) help for using a different namespace?

**Comment by Jasper-Ben** [comment]
@travisn using the helm chart for creating multiple operators breaks, as clusterroles are already defined (as is expected). It _might_ work using kubectl, but as my concept moved away from having multiple clusters, I will not pursue this any further, at least for now. Thanks for your help nevertheless! I will keep this issue open, as it relates to https://github.com/rook/rook/pull/5573.

**Comment by travisn** [comment]
@Jasper-Ben The helm chart should allow installing to a different namespace, just not multiple namespaces. Did you get the failure with multiple namespaces, or even just installing to a single namespace that wasn't `rook-ceph`?

**Comment by Jasper-Ben** [comment]
@travisn I was trying to install multiple clusters, so this was the issue then :) So as I understand installing multiple clusters is possible, just not with the helm chart.

**Comment by BlaineEXE** [comment]
If you look in the `common.yaml` for resources that are created in namespaces with comments `# namespace:cluster`, those need to be created in any namespace where the cluster should be run.

**Comment by travisn** [comment]
Note that a helm chart for the cephcluster CR (and support for different namespaces) is coming soon with #7778.
