### ISSUE TITLE
CSI_ENABLE_CEPHFS_SNAPSHOTTER is not assigned correctly by helm

### ISSUE THREAD

**Issue by toshipp** [rook/rook#7236]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The rendered deployment manifest for `rook-ceph-operator` has no value for a `CSI_ENABLE_CEPHFS_SNAPSHOTTER` environment variable.

**Expected behavior:**

`"true"` for `CSI_ENABLE_CEPHFS_SNAPSHOTTER` should be assigned as described in https://github.com/rook/rook/blame/a1b3682d9d31031f84879b681649f0c41a9d3517/Documentation/helm-operator.md#L104

**How to reproduce it (minimal and precise):**

Execute the following commands.
```bash
helm repo add rook-release https://charts.rook.io/release
helm template  --namespace rook-ceph rook-ceph rook-release/rook-ceph |grep -A1 CSI_ENABLE_CEPHFS_SNAPSHOTTER
```
Generated:
```
        - name: CSI_ENABLE_CEPHFS_SNAPSHOTTER
          value:
```

If I set enableCephfsSnapshotter manually, the value is assigned.

```bash
helm template --set csi.enableCephfsSnapshotter=true --namespace rook-ceph rook-ceph rook-release/rook-ceph |grep -A1 CSI_ENABLE_CEPHFS_SNAPSHOTTER
```
Generated:
```
        - name: CSI_ENABLE_CEPHFS_SNAPSHOTTER
          value: "true"
```

I think the case of `fs` in `enableCephfsSnapshotter` is ambiguous.
https://github.com/rook/rook/blob/475260de3547aad814ea4d24c30d079a9ce7d20f/cluster/charts/rook-ceph/values.yaml#L60
https://github.com/rook/rook/blob/f424a7abac674417423d2b26a3158005b330560d/cluster/charts/rook-ceph/templates/deployment.yaml#L114

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): c971b01b9e2024d270e022454adafb551ddc1144
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
Ah yes, it looks like the `enableCephFSSnapshotter` in values.yaml does not match the casing `enableCephfsSnapshotter` in deployment.yaml.
