### ISSUE TITLE
Use tini to prevent Zombie processes

### ISSUE THREAD

**Issue by f0** [rook/rook#724]
If you run a process as pid 1, it has special signal handling, this needs implementet in the process itself, or a init system must be used.

A simple (and docker default) init system is e.g https://github.com/krallin/tini

**Comment by bassam** [comment]
@f0 great. Sounds like we should add this to our containers (including the build container). This might explain some of the CTRL+C issues we've been seeing like #49

**Comment by bassam** [comment]
I'll address this as part of #700

**Comment by bassam** [comment]
Fixed in #700

**Comment by paroque28** [comment]
I got this error while running rook-operator container:

`[WARN  tini (5)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.`
Should I report the issue?

**Comment by paroque28** [comment]
It in on rook-toolbox container *
Apparently, PID 1 is assigned to pause
