### ISSUE TITLE
Error messages about non-existent cluster

### ISSUE THREAD

**Issue by mecseid** [rook/rook#7244]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The operator push this message on a daily approach:
```
clusterdisruption-controller: cephcluster "logging/" seems to be deleted, not requeuing until triggered again
```
I don't know why it thinks that I have a "logging" named cluster, because I only have one: (although I have a namespace with name logging)
```
$ kubectl get cephclusters.ceph.rook.io -A
NAMESPACE   NAME        DATADIRHOSTPATH   MONCOUNT   AGE    PHASE   MESSAGE                        HEALTH
rook-ceph   rook-ceph   /var/lib/rook     3          508d   Ready   Cluster created successfully   HEALTH_OK
```

**Expected behavior:**
Not see the messages about the non-existent clusters.

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v1.5.6
* Kubernetes version (use `kubectl version`): 1.17
* Rancher version: v2.5.5

I don't know it has some relation about this issue, but I get the following error for the logging namespace:
https://github.com/rancher/rancher/issues/30881

**Comment by travisn** [comment]
@sp98 It seems the pdb controller is printing messages for unrelated pdbs. How about we suppress this message?

**Comment by sp98** [comment]
This was fixed in https://github.com/rook/rook/pull/7128.  @mecseid  do you still see this issue?

**Comment by mecseid** [comment]
@sp98 Sorry for late response.
Checked the logs, and I didn't see any message about this error, so I think it's closable. 

Thanks a lot! 🎉
