### ISSUE TITLE
recover OSDs if their metadata/config is lost but their data still exists

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#726]

**Comment by travisn** [comment]
Are we saying we would periodically snapshot and backup the metadata from the config folders? Seems like a fully consistent solution would require ceph to write metadata to kubernetes.

**Comment by jbw976** [comment]
The scenario described here may be a good starting scope for this issue: https://github.com/rook/rook/issues/964#issuecomment-328931743

**Comment by jbw976** [comment]
I've been working on the scenario where an OSD's data devices still exist but it's metadata/config `/var/lib/rook` has been lost, trying to get the OSD running again using the data that still exists.

I'm to the point where a bluestore OSD can recreate its metadata (`whoami`, `fsid`, `keyring`, etc.), start running and return to both `UP` and `IN`.  However, all placement groups that were assigned to the OSD are stuck stale and remain that way.

Looking in the ceph codebase, I believe the `ceph-osd --mkfs` call I'm using to recreate the metadata is also wiping out the data and DB partitions inside `BlueStore::mkfs()`:
https://github.com/rook/ceph/blob/rook-luminous/src/os/bluestore/BlueStore.cc#L5147
https://github.com/rook/ceph/blob/rook-luminous/src/os/bluestore/BlueStore.cc#L4435
https://github.com/rook/ceph/blob/rook-luminous/src/os/bluestore/BlueStore.cc#L4511

I'm not sure if this is a supported scenario right now, but I've sent mail to the ceph-users list to get more information.
