### ISSUE TITLE
Remove CephCluster status Progressing Condition when reconciliation is completed

### ISSUE THREAD

**Issue by ron1** [rook/rook#7267]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When CephCluster reconciliation is completed, the Progressing Condition is set to false

**Expected behavior:**
When CephCluster reconciliation is completed, the Progressing Condition is removed

**How to reproduce it (minimal and precise):**

Allow CephCluster reconciliation to complete.

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.9
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.5.7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph v15.2.8
* Kubernetes version (use `kubectl version`): v1.18.12
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Healthy

**Comment by travisn** [comment]
Resolved by #7315 and will be included in v1.5.9...
