### ISSUE TITLE
ceph: Deprecate creating/configuring OSDs via Drive Groups config

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#7275]
## Proposal to deprecate configuring Ceph  OSDs via Drive Groups

Drive Groups were added to Rook-Ceph last July and included in Rook release v1.4 (https://github.com/rook/rook/pull/4916). Drive Groups give us another method for specifying how to configure OSDs on a node’s disks in a way that is quite complex but also flexible. We had hoped this would make integration with the Ceph [orchestrator framework](https://docs.ceph.com/en/latest/mgr/orchestrator_modules/) easier for Rook. In practice, we are finding that this has merely added complexity that is stretching thin our development and maintenance efforts, and we intend to deprecate the feature in the upcoming Rook v1.6 release.

Drive Groups have been a supported feature for only two Rook releases (v1.4 and v1.5), and they are quite complex for users to begin using. Because of these two reasons, we do not believe many users are likely to have chosen this option for configuring OSDs in their cluster. Additionally, we are not aware of any GitHub issues or Slack requests opened by users to indicate Drive Groups are being used in the wild.

Deprecating Drive Groups at this point does **not** mean that OSDs provisioned using this method will cease to operate. Existing OSDs will still run as normal, and Kubernetes Deployments for existing OSDs will still be updated. However, clusters that have used Drive Groups will need to use the long-standing `storage` config to add any new disks to their Rook-Ceph cluster. We will make it clear in documentation how to transition from using Drive Groups to using `storage`.

This deprecation is not something we take on lightly, and we want to hear from the community about any negative effects this may have on our users before we remove the feature. If you are using or have used Drive Groups, please let us know how this will affect you. We will do what we need to make sure there is a good transition path for your Rook-Ceph clusters.

**Comment by stuartpb** [comment]
I would have spoken out about this change if I knew it was happening: the `storage` parameter is significantly more rigid than I want my system's hardware configuration to be, and I greatly preferred the `driveGroups` spec.
