### ISSUE TITLE
Create ValidatingWebhookConfiguration to stop deletion of critical resources

### ISSUE THREAD

**Issue by briantopping** [rook/rook#7277]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Critical resources such as `CephCluster` are easily deleted if the user is in the wrong context. While the finalizer will stop the actual deletion of the resource until all child resources such as `PersistentVolumeClaim`s are removed, it is a little unnerving that the resources remain in the `Terminating` state. 

By creating a `ValidatingWebhookConfiguration` that checks critical resources for a confirmation annotation, the deletion can be rejected if the annotation does not exist. Ideally, there would be a timeout on the annotation so if it wasn't used within a timeframe such as a minute or so, it would be automatically removed. 

**What is use case behind this feature:**
In my case, I had the wrong kubectl context selected when I deleted a `CephCluster`. I meant to delete the external `CephCluster` in the cluster I was deleting and accidentally had the master cluster selected, wiping out all the clusters. 

The feature was considered in [this Slack discussion](https://rook-io.slack.com/archives/CK9CF5H2R/p1613860814002800).

**Comment by leseb** [comment]
Adding suggestion from the Slack thread.

> ymmt  21 hours ago
Just FYI, we have implemented a custom validating webhook for critical resources including CephCluster.
>
> ymmt  21 hours ago
> The webhook is open-sourced here: https://github.com/cybozu/neco-containers/tree/main/admission#deletevalidator
> 
> ymmt  21 hours ago
> and the configuration is here: https://github.com/cybozu-go/neco-apps/blob/main/neco-admission/base/webhook.yaml#L61-L96
