### ISSUE TITLE
make codegen is not failing the CI action when changes are needed

### ISSUE THREAD

**Issue by travisn** [rook/rook#7287]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
`make codegen` in master currently leaves some files changed since #7264 was merged. The codegen CI action should have failed before the merge, but it did not identify the problem. When #7264 was backported, the CI failure was detected as expected in #7274. So the `make codegen` validation is only broken in master.

**Expected behavior:**
The specific codegen issue is fixed with #7286, but we still need to fix the CI action to catch future issues.

**How to reproduce it (minimal and precise):**

- Make a change to the codegen types
- Run `make codegen`
- See the changed file(s) locally
- If the generated file(s) are not included in the PR, we expect the CI action to fail

**Comment by leseb** [comment]
It's interesting that https://github.com/rook/rook/pull/7264/checks?check_run_id=1937702846 didn't see any files:

```
Run tests/scripts/validate_modified_files.sh codegen
+ MOD_FILE=mod
+ CODEGEN_ERR='found codegen files! please run '\''make codegen'\'' and update your PR'
+ MOD_ERR='changes found by mod.check. You may need to run make clean'
+ case "$1" in
+ validate 'found codegen files! please run '\''make codegen'\'' and update your PR'
++ git status --porcelain
+ git=
```

**Comment by subhamkrai** [comment]
@leseb right, it wired that  `git` var is empty which means `git status --porcelain` showing no changes :thinking:? looking more in this.
