### ISSUE TITLE
Terraform destroy doesn't work properly for Rook-operator helm chart

### ISSUE THREAD

**Issue by ahmedTouati** [rook/rook#7289]
I'm using terraform to deploy a helm release of Rook-operator, however when i try to destroy it some errors occur but when i try to uninstall it manually (helm uninstall rook-ceph) it works!

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
terraform destroy fails

**Expected behavior:** 
terraform destroy uninstalls rook-operator helm release

**How to reproduce it (minimal and precise):**

**Here is my file**  :
```
resource "helm_release" "example" {
  name       = "rook-ceph"
  repository = "https://charts.rook.io/release"
  chart      = "rook-ceph"
  namespace = "default"
  version = "v1.5.7"
  values = [
    "${file("rook-values.yaml")}"
  ]
}
```

**This is what i get when i run terraform destroy** :
```
Error: manifest-10
manifest-11
manifest-12
manifest-13
manifest-14
manifest-15
manifest-16
manifest-17
manifest-18
manifest-19
manifest-20
manifest-21
manifest-22
manifest-23
```
**Environment**:
* Kernel (e.g. `uname -a`):  4.14
* Cloud provider or hardware configuration:  AWS EKS
* Rook version (use `rook version` inside of a Rook Pod):  v1.5.7
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.18
* Kubernetes version (use `kubectl version`): 1.18

**Comment by travisn** [comment]
@ahmedTouati In v1.5.7 annotations were added to the CRDs so that the helm chart would no longer delete them during uninstall. Perhaps terraform is failing due to that issue? See [this doc](https://rook.github.io/docs/rook/v1.5/helm-operator.html#uninstalling-the-chart) for uninstall of the helm chart.

**Comment by ahmedTouati** [comment]
@travisn i tried removing all CRDs created by rook helm chart beforing launching terraform destroy but i had the same issue
