### ISSUE TITLE
master is building dirty

### ISSUE THREAD

**Issue by jbw976** [rook/rook#731]
https://release.rook.io/master/ shows dirty release versions for the past few builds.  Looking into jenkin's local repo, it looks like a change is being introduced during the build due to a `gofmt` issue or an empty line with an indentation.

**Comment by bassam** [comment]
can we make gofmt fail but not change a file?

**Comment by jbw976** [comment]
our makefile is calling `go fmt` which under the covers calls `gofmt -l -w`.   The `-w` will "write result to (source) file instead of stdout".

so i think we'd need to call `gofmt` directly instead of going through `go fmt`.  I don't yet see how to get `gofmt` to return an error code, but if `gofmt -l` returns any output at all ("lists files whose formatting differes from gofmt's") then that would be an error.  Maybe there's an easy way in the makefile to test the output of `gofmt` and fail if it's not an empty string?

**Comment by jbw976** [comment]
another tricky part here is that `go fmt` allows package wildcards (e.g. `github.com/rook/rook/pkg/...`) while `gofmt` expects fully resolved paths.  After updating `golang.mk` to use `gofmt` directly, I get:
```
> build/run make go.fmt
stat github.com/rook/rook/cmd/...: no such file or directory
stat github.com/rook/rook/pkg/...: no such file or directory
build/makelib/golang.mk:180: recipe for target 'go.fmt' failed
```
