### ISSUE TITLE
Docs: ceph-teardown.md outdated and ignores cleanup-policy technique

### ISSUE THREAD

**Issue by ctrahey** [rook/rook#7312]
**Is this a bug report or feature request?**
* Bug Report (Docs)

**Deviation from expected behavior:**
[ceph-teardown.md](https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md) describes a painfully manual and outdated technique for cleaning disks.

**Expected behavior:**
Rook Docs, even early tutorials/walkthroughs, should include the latest, safest, idiomatic techniques.

**How to reproduce it (minimal and precise):**
1. Read [ceph-teardown.md](https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md)
1. Compare to [cleanup-policy feature](https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html#cleanup-policy)
1. Observe that teardown.md instructs more dangerous and manual steps than are required.

**Comment by travisn** [comment]
Yes, clearly we should be documenting in the cleanup procedure how to use the cleanup feature. :) 

I'd suggest we still keep the existing sections on the cleanup in case the cluster cleanup feature is not used, but the cleanup feature would be the first recommendation.
