### ISSUE TITLE
Zonegroup crd does not work on  rook 1.5.7 or higher.

### ISSUE THREAD

**Issue by ycy1766** [rook/rook#7318]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Zonegroup is not created using CephObjectZoneGroup crd.

**Expected behavior:**
Created a zonegroup using CephObjectZoneGroup crd.

**How to reproduce it (minimal and precise):**

I created a zonegroup using the CephObjectZoneGroup crd in rook 1.5.7 and 1.5.8.
```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: cy-realm
  namespace: rook-ceph
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: cy-zonegroup
  namespace: rook-ceph
spec:
  realm: cy-realm
```
However, realm is created, but zonegroup is not.
```
[root@rook-ceph-tools-875444c55-d8wh9 /]# radosgw-admin realm list
{
    "default_info": "51772ff3-390c-468e-b635-0b8ba67c07cb",
    "realms": [
        "cy-realm"
    ]
}
[root@rook-ceph-tools-875444c55-d8wh9 /]# radosgw-admin zonegroup list
{
    "default_info": "",
    "zonegroups": []
}
```
An error occurred in operator.
```
2021-02-26 06:54:24.800273 E | ceph-object-zonegroup-controller: failed to reconcile: failed to create ceph zone group: failed to parse `radosgw-admin period get` output: Failed to unmarshal json: invalid character 'p' looking for beginning of value
```

In the same way, when I created it in rook.1.5.6, a zone group was created.
This is the result o`f radosgw-admin period get`.(1.5.7,1.5.8)
```
[root@rook-ceph-tools-875444c55-d8wh9 /]# radosgw-admin period get
{
    "id": "085ec471-2517-4fe7-a96d-c0ebf06cb140",
    "epoch": 1,
    "predecessor_uuid": "",
    "sync_status": [],
    "period_map": {
        "id": "085ec471-2517-4fe7-a96d-c0ebf06cb140",
        "zonegroups": [],
        "short_zone_ids": []
    },
    "master_zonegroup": "",
    "master_zone": "",
    "period_config": {
        "bucket_quota": {
            "enabled": false,
            "check_on_raw": false,
            "max_size": -1,
            "max_size_kb": 0,
            "max_objects": -1
        },
        "user_quota": {
            "enabled": false,
            "check_on_raw": false,
            "max_size": -1,
            "max_size_kb": 0,
            "max_objects": -1
        }
    },
    "realm_id": "51772ff3-390c-468e-b635-0b8ba67c07cb",
    "realm_name": "cy-realm",
    "realm_epoch": 1
}
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):  ubuntu 20.04.1 LTS (Focal Fossa)"
* Kernel (e.g. `uname -a`):  5.4.0-66-generic
* Cloud provider or hardware configuration: on kvm 
* Rook version (use `rook version` inside of a Rook Pod):  rook 1.5.7 ,rook 1.5.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.9,ceph version 15.2.8
* Kubernetes version (use `kubectl version`):  v1.19.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):  vanila kubernetes 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): 

```
[root@rook-ceph-tools-875444c55-d8wh9 /]# ceph -s
  cluster:
    id:     7ed44bbf-9134-4d27-a60d-b0867a7d5bce
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 28m)
    mgr: a(active, since 27m)
    osd: 3 osds: 3 up (since 27m), 3 in (since 27m)

  data:
    pools:   2 pools, 33 pgs
    objects: 7 objects, 530 B
    usage:   3.0 GiB used, 57 GiB / 60 GiB avail
    pgs:     33 active+clean  
```

**Comment by travisn** [comment]
@alimaredia Any ideas on this error?
```
2021-02-26 06:54:24.800273 E | ceph-object-zonegroup-controller: failed to reconcile: failed to create ceph zone group: 
failed to parse `radosgw-admin period get` output: Failed to unmarshal json: invalid character 'p' looking for beginning of value
```

**Comment by alimaredia** [comment]
@travisn Let me see if I can recreate the issue. @ycy1766 Did you see this issue with any of the other multisite CRDs?

**Comment by ycy1766** [comment]
@alimaredia Yes, it happens on multisite crd.

**Comment by kadomino** [comment]
Hi, just in case you need another example - I have a similar thing in my logs (Rook v1.5.8, Ceph v15.2.9-20210224):
```sh
2021-03-10 08:53:18.943410 E | ceph-object-zone-controller: failed to reconcile: failed to create ceph zone: failed to parse `radosgw-admin zonegroup get` output: failed to unmarshal json: invalid character 'p' looking for beginning of value
```
The zonegroup is created, but fails to reconcile:
```yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"ceph.rook.io/v1","kind":"CephObjectZoneGroup","metadata":{"annotations":{},"name":"latinov-ch","namespace":"rook-ceph"},"spec":{"realm":"latinov"}}
  creationTimestamp: '2021-03-08T16:39:10Z'
  generation: 1
  managedFields:
    - apiVersion: ceph.rook.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:realm: {}
      manager: kubectl
      operation: Update
      time: '2021-03-08T16:39:10Z'
    - apiVersion: ceph.rook.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:phase: {}
      manager: rook
      operation: Update
      time: '2021-03-10T09:05:10Z'
  name: latinov-ch
  namespace: rook-ceph
  resourceVersion: '1154841'
  selfLink: /apis/ceph.rook.io/v1/namespaces/rook-ceph/cephobjectzonegroups/latinov-ch
  uid: f393f04d-26ba-4ba4-a215-7f2a805219ad
spec:
  realm: latinov
status:
  phase: ReconcileFailed
```
The Multisite config is a leftover from my previous attempt (with Rook v1.5.4) to use it for its replication functionality across sites. That attempt failed because my 2 sites cannot "see" each other's Service networks across the Internet.

Everything seems to be working fine (I use a few buckets), but I do not really use the multisite functionality on this cluster. I can provide more info if needed.

**Comment by alimaredia** [comment]
@kadomino @ycy1766 Could you give me steps to reproduce this issue or Rook and Ceph versions? I would think this issue occurs when you just try to create a new Zonegroup CR. I did that on the master branch of Rook (v1.6.1 I think) and the Zonegroup CR came back up just fine.

**Comment by kadomino** [comment]
Thanks for following up on this, @alimaredia. Unfortunately, I moved on since and no longer have an environment to reproduce it.

I was trying to use the multisite functionality to replicate some buckets to a remote site over the Internet for Disaster Recovery purposes. As I wrote before, I realized that this cannot be done because my two sites cannot access their respective K8S service networks across the Internet. Consequently, and after noticing this particular issue, I dropped the use of multisite and used RClone for my DR needs.

I dare venture that this issue is probably fixed in the 1.6.x releases, but cannot verify it at this point. Currently, I use v1.5.9 in production, without multisite.

**Comment by ycy1766** [comment]
Thanks for following up on this ,@alimaredia . I did the same in rook 1.5.9, but it was confirmed that it works normally.
```
root@cy02-ceph020:~# cat test.yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: cy-realm
  namespace: rook-ceph
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: cy-zonegroup
  namespace: rook-ceph
spec:
  realm: cy-realm


root@cy02-ceph020:~# kubectl create -f test.yaml
cephobjectrealm.ceph.rook.io/cy-realm created

root@cy02-ceph020:/home/test2-ob/rook-ceph-1.5.9# radosgw-admin realm list
{
    "default_info": "4354ba40-14fb-4f91-8af4-15e9ae43a40b",
    "realms": [
        "test-obs",
        "cy-realm"
    ]
}
root@cy02-ceph020:/home/test2-ob/rook-ceph-1.5.9# radosgw-admin zonegroup list
{
    "default_info": "ce2e9705-7add-4652-8f77-6aa76c391f8e",
    "zonegroups": [
        "test-obs",
        "cy-zonegroup"
    ]
}
```
There is no error in the operator.
```
2021-05-07 00:19:53.330651 I | ceph-object-zonegroup-controller: Realm "cy-realm" found in Ceph cluster to create ceph zone group "cy-zonegroup"
2021-05-07 00:19:53.339165 I | ceph-object-zonegroup-controller: creating object zone group "cy-zonegroup" in realm "cy-realm"
```

**Comment by alimaredia** [comment]
@ycy1766 @kadomino Thanks for the responses. I'm going to go ahead a close the issue. If you'd like it reopened or have additional feedback let me know.
