### ISSUE TITLE
PGs are stuck in unkown state after adding new device sets

### ISSUE THREAD

**Issue by ahmedTouati** [rook/rook#7321]
I had a ceph cluster with 3 OSDs belong to the same device set (set1), then i added two other device sets (set2 and set3) each with one OSD, So i had to decrease the number of OSDs in set1 from 3 to 1, but what i got is a list of OSDs (osd0, osd1,osd2, osd3,osd4) and 5 PVCs (set1xxx, set1yyy, set1zzz, set2xxx, set3xxx). what i expected is 3 osd (osd1,osd2,osd3) and 3 PVCs (set1,set2,set3). I tried to delete 3 OSDs deployment (osd0,osd2,osd4) and remove two device sets from set1 (set1yyy and set1zzz), I think i messed up with it a bit because i have an inactive cluster now and no OSDs are running because all PGs are in **UNKOWN** state.

Is there any possible way to recover the cluster like resetting all PGS or removing them ?

**ceph health detail**:
```
HEALTH_WARN 1 filesystem is degraded; 1 MDSs report slow metadata IOs; 1 osds exist in the crush map but not in the osdmap; Reduced data availability: 65 pgs inactive; 6
 daemons have recently crashed; OSD count 0 < osd_pool_default_size 3
[WRN] FS_DEGRADED: 1 filesystem is degraded
    fs test-fs is degraded
[WRN] MDS_SLOW_METADATA_IO: 1 MDSs report slow metadata IOs
    mds.test-fs-a(mds.0): 4 slow metadata IOs are blocked > 30 secs, oldest blocked for 1372 secs
[WRN] OSD_ORPHAN: 1 osds exist in the crush map but not in the osdmap
    osd.3 exists in crush map but not in osdmap
[WRN] PG_AVAILABILITY: Reduced data availability: 65 pgs inactive
    pg 1.0 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.0 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.1 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.2 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.3 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.4 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.5 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.6 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.7 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.8 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.9 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.a is stuck inactive for 23m, current state unknown, last acting []
    pg 2.b is stuck inactive for 23m, current state unknown, last acting []
    pg 2.c is stuck inactive for 23m, current state unknown, last acting []
    pg 2.d is stuck inactive for 23m, current state unknown, last acting []
    pg 2.e is stuck inactive for 23m, current state unknown, last acting []
    pg 2.f is stuck inactive for 23m, current state unknown, last acting []
    pg 2.10 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.11 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.12 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.13 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.14 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.15 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.16 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.17 is stuck inactive for 23m, current state unknown, last acting []
    pg 2.18 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.0 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.1 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.2 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.3 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.4 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.5 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.6 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.7 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.8 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.9 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.a is stuck inactive for 23m, current state unknown, last acting []
    pg 3.b is stuck inactive for 23m, current state unknown, last acting []
    pg 3.c is stuck inactive for 23m, current state unknown, last acting []
    pg 3.d is stuck inactive for 23m, current state unknown, last acting []
    pg 3.e is stuck inactive for 23m, current state unknown, last acting []
    pg 3.f is stuck inactive for 23m, current state unknown, last acting []
    pg 3.10 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.11 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.12 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.13 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.14 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.15 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.16 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.17 is stuck inactive for 23m, current state unknown, last acting []
    pg 3.19 is stuck inactive for 23m, current state unknown, last acting []
[WRN] RECENT_CRASH: 6 daemons have recently crashed
    osd.0 crashed on host rook-ceph-osd-0-66dfc848bd-nx4pv at 2021-02-17T16:14:22.461301Z
    osd.0 crashed on host rook-ceph-osd-0-66dfc848bd-nx4pv at 2021-02-17T16:14:24.974759Z
    osd.0 crashed on host rook-ceph-osd-0-79f848569-94brt at 2021-02-22T10:05:23.070919Z
    osd.0 crashed on host rook-ceph-osd-0-79f848569-94brt at 2021-02-22T10:05:23.077463Z
    mon.d crashed on host rook-ceph-mon-d-6c694594d9-6nx9m at 2021-02-22T10:07:33.135243Z
    mgr.a crashed on host rook-ceph-mgr-a-574979989f-xrj52 at 2021-02-22T21:43:44.632768Z
[WRN] TOO_FEW_OSDS: OSD count 0 < osd_pool_default_size 3
```
**rook-operator logs :***
```
clusterdisruption-controller: all osds are up. last drained failure domain: "eu-west-1c".  pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:65}]". waiting for PGs to be active+clean or PG health check to timeout
```
**Environment**:
* Kernel (e.g. `uname -a`): 4.14
* Cloud provider or hardware configuration: AWS EKS
* Rook version (use `rook version` inside of a Rook Pod): v1.5.7
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.18
* Kubernetes version (use `kubectl version`): 1.18

**Comment by leseb** [comment]
Output of `ceph -s` please.

**Comment by ahmedTouati** [comment]
> Output of `ceph -s` please.

cluster:
    id:     104d8c52-5ccf-4069-8d19-1509db40020b
    health: HEALTH_WARN
            1 filesystem is degraded
            1 MDSs report slow metadata IOs
            1 osds exist in the crush map but not in the osdmap
            Reduced data availability: 65 pgs inactive
            6 daemons have recently crashed
            OSD count 0 < osd_pool_default_size 3
 
  services:
    mon: 3 daemons, quorum c,i,j (age 9h)
    mgr: a(active, since 9h)
    mds: palmyra-fs:1/1 {0=palmyra-fs-a=up:replay} 1 up:standby
    osd: 0 osds: 0 up (since 2d), 0 in (since 2d)

  data:
    pools:   3 pools, 65 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             65 unknown

**Comment by ahmedTouati** [comment]
> Output of `ceph -s` please.

cluster:
    id:     104d8c52-5ccf-4069-8d19-1509db40020b
    health: HEALTH_WARN
            1 filesystem is degraded
            1 MDSs report slow metadata IOs
            1 osds exist in the crush map but not in the osdmap
            Reduced data availability: 65 pgs inactive
            6 daemons have recently crashed
            OSD count 0 < osd_pool_default_size 3
 
  services:
    mon: 3 daemons, quorum c,i,j (age 9h)
    mgr: a(active, since 9h)
    mds: test-fs:1/1 {0=test-fs-a=up:replay} 1 up:standby
    osd: 0 osds: 0 up (since 2d), 0 in (since 2d)

  data:
    pools:   3 pools, 65 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             65 unknown

**Comment by BlaineEXE** [comment]
It's hard to tell if any data will be recoverable. If you don't need to recover data, I might suggest deleting the whole rook cluster and creating a new one with the devices you want.

**Comment by travisn** [comment]
When removing the OSDs, this must be done very carefully to avoid data loss. Please see the guide on [removing OSDs](https://rook.github.io/docs/rook/v1.5/ceph-osd-mgmt.html#remove-an-osd).

**Comment by ahmedTouati** [comment]
> When removing the OSDs, this must be done very carefully to avoid data loss. Please see the guide on [removing OSDs](https://rook.github.io/docs/rook/v1.5/ceph-osd-mgmt.html#remove-an-osd).

Is there any way to recover old data ?

**Comment by ahmedTouati** [comment]
> It's hard to tell if any data will be recoverable. If you don't need to recover data, I might suggest deleting the whole rook cluster, wiping the data, and creating a new one with the devices you want.

Removing the whole cluster isn't an option because i need old data

**Comment by travisn** [comment]
You need to bring back the OSDs. Did you completely delete all of them? This says that there are no more OSDs:
```
TOO_FEW_OSDS: OSD count 0 < osd_pool_default_size 3
```

And from the status:
```
osd: 0 osds: 0 up (since 2d), 0 in (since 2d)
```

**Comment by ahmedTouati** [comment]
> You need to bring back the OSDs. Did you completely delete all of them? This says that there are no more OSDs:
> 
> ```
> TOO_FEW_OSDS: OSD count 0 < osd_pool_default_size 3
> ```
> 
> And from the status:
> 
> ```
> osd: 0 osds: 0 up (since 2d), 0 in (since 2d)
> ```

I deleted all of them but i expected rook-operator will bring them back

**Comment by travisn** [comment]
> I deleted all of them but i expected rook-operator will bring them back

Rook will bring them back if the underlying disk is still there and they're still registered with Ceph. But it looks like they have been purged from Ceph as well since it shows 0 OSDs. Check in the OSD prepare logs, they should show if the disks are found again.
