### ISSUE TITLE
Stuck on poweroff

### ISSUE THREAD

**Issue by leiw324** [rook/rook#7338]
Hello,

I am using KVM in Linux CentOS 7.8  to deployed Kubernetes 1.17 cluster, also deployed rook-ceph 1.5.x three nodes in this cluster.

After I deployed Deployment to mount pvc, when poweroff Linux will stuck on the following screen:
image.png
![image](https://user-images.githubusercontent.com/33790160/109629752-206cdb00-7b7f-11eb-813a-41c04b7691c9.png)

I have to enforce a hard reset to shutdown three nodes.

Thanks

**Comment by rohan47** [comment]
Can you please add more details?
The above information is vague and the error can be due to other reasons.

**Comment by jav333** [comment]
Hello,

![image](https://user-images.githubusercontent.com/79013136/109824288-a5d1b780-7c73-11eb-8b29-b5aa8e44df66.png)
![image](https://user-images.githubusercontent.com/79013136/109824315-ad915c00-7c73-11eb-8610-708e40868e68.png)
![image](https://user-images.githubusercontent.com/79013136/109824467-d1ed3880-7c73-11eb-840f-045e615efa82.png)
![image](https://user-images.githubusercontent.com/79013136/109824816-21336900-7c74-11eb-9c81-4bf9c84fab8d.png)
![image](https://user-images.githubusercontent.com/79013136/109825226-930bb280-7c74-11eb-9aed-6d572441c037.png)
![image](https://user-images.githubusercontent.com/79013136/109825313-ac146380-7c74-11eb-9985-f2ea1f83c1d3.png)
![image](https://user-images.githubusercontent.com/79013136/109825416-c5b5ab00-7c74-11eb-8e0c-51465c432536.png)
![image](https://user-images.githubusercontent.com/79013136/109825763-16c59f00-7c75-11eb-857d-ffc9d9f9925e.png)

**Comment by leiw324** [comment]
Hello,

![image](https://user-images.githubusercontent.com/33790160/109829513-9012c100-7c78-11eb-96b6-b6dd4179a5ab.png)
![image](https://user-images.githubusercontent.com/33790160/109829528-943ede80-7c78-11eb-8c90-3957aa7c9cee.png)
![image](https://user-images.githubusercontent.com/33790160/109829545-986afc00-7c78-11eb-8da9-523fb1163fdd.png)
![image](https://user-images.githubusercontent.com/33790160/109829569-9d2fb000-7c78-11eb-9c92-1e83e106373f.png)
![image](https://user-images.githubusercontent.com/33790160/109829583-a15bcd80-7c78-11eb-8ec1-5e8421589670.png)
![image](https://user-images.githubusercontent.com/33790160/109829607-a751ae80-7c78-11eb-8131-a49b46fa1126.png)
![image](https://user-images.githubusercontent.com/33790160/109829625-acaef900-7c78-11eb-98c5-7bad2e7d7186.png)
![image](https://user-images.githubusercontent.com/33790160/109829652-b173ad00-7c78-11eb-8853-237e7d2e84db.png)

**Comment by jav333** [comment]
Can someone help?

**Comment by leiw324** [comment]
No one can help?
