### ISSUE TITLE
FailedMount with "timed out waiting for the condition"

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#7342]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When pod was rescheduled, its volume was failed in mount with messages " Warning  FailedMount  60s (x8 over 39m)    kubelet, n05cicompute-worker-04  Unable to attach or mount volumes: unmounted volumes=[data backup], unattached volumes=[ckng-ccas-apache data backup default-token-56hhf]: timed out waiting for the condition"

**Expected behavior:**
The volume can be mounted successfully.

**How to reproduce it (minimal and precise):**

Delete the pod or drain the node to trigger the pod reschedule on a different node. 

**File(s) to submit**:
Attached is the completed rook pod logs that containing application pods reschedule event.
[rook-logs03-02-20-46.zip](https://github.com/rook/rook/files/6071837/rook-logs03-02-20-46.zip)
  
* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
1. The orchestration was started now and then with "op-cluster: Running orchestration for namespace rook-ceph after device change". But there's no deivce change in the system. 
2. There's error messages, which is similar to the previous tickets ( https://github.com/rook/rook/issues/2553)
```
E0201 04:24:04.540233       6 controller.go:1003] volume "pvc-6a293ce1-9f8c-4b13-bf20-535126a0fa2a" in work queue no longer exists
E0201 04:24:04.540234       6 controller.go:1003] volume "pvc-6a293ce1-9f8c-4b13-bf20-535126a0fa2a" in work queue no longer exists
E0201 04:24:04.540234       6 controller.go:1003] volume "pvc-6a293ce1-9f8c-4b13-bf20-535126a0fa2a" in work queue no longer exists
E0201 04:24:04.540327       6 controller.go:1003] volume "pvc-6a293ce1-9f8c-4b13-bf20-535126a0fa2a" in work queue no longer exists
E0224 07:09:42.340183       6 controller.go:1003] volume "pvc-0b9bc1fd-382f-4d55-a89b-d8bc45594fbd" in work queue no longer exists
E0224 07:09:42.340239       6 controller.go:1003] volume "pvc-0b9bc1fd-382f-4d55-a89b-d8bc45594fbd" in work queue no longer exists
E0225 12:28:37.940159       6 controller.go:1003] volume "pvc-110901de-72be-4c40-9c38-e2f45a462dfb" in work queue no longer exists
E0225 12:28:37.940182       6 controller.go:1003] volume "pvc-110901de-72be-4c40-9c38-e2f45a462dfb" in work queue no longer exists
```

* Crashing pod(s) logs, if necessary
No crash pods. 

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS-7
* Kernel (e.g. `uname -a`):Linux n05cicompute-control-01 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod):  1.2.7
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.7
* Kubernetes version (use `kubectl version`): v1.17.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):  "HEALTH_OK".

**Comment by Madhu-1** [comment]
@yanchicago please provide more details as below

* issue is in cephfs or rbd
* Is it happening frequently or always
* Provide logs from the plugin containers of the cephfs or rbd daemonset pod from the node where the mount is timing out
* provide dmesg logs from the node where mount is timing out.

**Comment by yanchicago** [comment]
1. Issue is in rbd
2. frequently
3. Rescheduled a pod with pvc ( pvc-dd4b03b3-29a2-4b68-a70a-1edf34ac631c and pvc-0c162899-e30e-47f9-aab4-d1c1a58482e1) to worker-05
4. Attached is the rbd-w05.log and dmesg.out on worker-05 node. 
[w05.tar.gz](https://github.com/rook/rook/files/6077298/w05.tar.gz)

```
[root@n05cicompute-worker-05 ~]# top
top - 16:00:26 up 84 days,  5:16,  1 user,  load average: 4.99, 5.72, 5.74
Tasks: 733 total,   2 running, 523 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.0 us,  3.7 sy,  0.0 ni, 89.8 id,  0.2 wa,  0.2 hi,  0.1 si,  0.0 st
KiB Mem : 17717571+total, 80237232 free, 14315888 used, 82622592 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 16171920+avail Mem
```

**Comment by yanchicago** [comment]
Any clue on what it waits for with message " timed out waiting for the condition"? 
Saw one scenario that the pod recovered after long time.

**Comment by neumantm** [comment]
I have the exact same problem.
Did you find any solution?
