### ISSUE TITLE
Rook should support the default storage class

### ISSUE THREAD

**Issue by luxas** [rook/rook#735]
Although `rook-block` is the default StorageClass, rook fails to notice that when depoying a PVC with an empty `storageClassName`:
```
E0614 11:59:57.584912       1 controller.go:464] Error getting claim "default/prometheus-sample-metrics-prom-db-prometheus-sample-metrics-prom-0"'s StorageClass's fields: StorageClass "" not found
```

cc @bassam

**Comment by kokhang** [comment]
@luxas shouldnt we let the admin decide what the default StorageClass?
https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

I just want to make sure we are not overwriting default value set or expected by the user.

**Comment by luxas** [comment]
@kokhang What I mean is that if the `storageClassName=""` and there is a Default StorageClass of type `rook.io/block`, you should go ahead and use that one.

**Comment by bassam** [comment]
This seems like a useful improvement.

**Comment by luxas** [comment]
Possible to get into v0.5?

**Comment by jbw976** [comment]
This is nice to have for 0.5 if the fix is straightforward.

**Comment by kokhang** [comment]
I cant repo this on Kubernetes 1.7.0.  On minikube, i deployed rook, created a rook-block storageclass, set it to be default and deleted the `standard` storageclass which was the default originally. I modified the mysql.yaml to not state a storageClassName. 

I deployed the mysql.yaml and everything came up fine. The volume created was of storageclass `rook-block`.

@luxas I will close this as no-repro. Feel free to reopen it if Im not able to doing the right thing to reproduce it.
