### ISSUE TITLE
Operator not reconciling due to "active+clean+remapped" PG

### ISSUE THREAD

**Issue by jmmaloney4** [rook/rook#7363]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Ceph cluster is in good health, except has one pg in "active+clean+remapped". However the MDS deployments are on the wrong ceph version. Rook continues to print this message:

```
all osds are up. last drained failure domain: "<node name>".  pg health: "cluster is not fully clean. PGs: [{StateName:active+clean Count:400} {StateName:active+clean+remapped Count:1}]". waiting for PGs to be active+clean or PG health check to timeout
```

I deleted one of the MDS deployments to see if that would trigger rook to recreate it, and it has not recreated it. 

**Expected behavior:**

Rook should update MDS deployments with PGs in "active+clean+remapped".

**How to reproduce it (minimal and precise):**

Upgraded to ceph 15.2.9 and Rook 1.5.8, MDS are still on ceph 15.2.8.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu server 18.04.5 LTS
* Kernel (e.g. `uname -a`): 4.15.0-136-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): v1.19.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN insufficient standby MDS daemons available`

**Comment by jmmaloney4** [comment]
No, just HEALTH_WARN because of the missing MDS.

**Comment by travisn** [comment]
Ok, HEALTH_WARN shouldn't block the reconcile. Could you share the full operator log after restarting the operator? Or did skipUpgradeChecks already fix it?

**Comment by jmmaloney4** [comment]
Now reading my logs more carefully, I'm realizing that I also updated my pools to have `deviceClass: hdd`, and there are some logs complaining about an ec profile. Is updating the device class after the creation of the pool not supported? Either way, here are my logs, and I'll try to revert those changes and see if that changes something.

[container.log](https://github.com/rook/rook/files/6102873/container.log)

**Comment by jmmaloney4** [comment]
After removing the `deviceClass: hdd` everything has figured itself out. Thanks for your help.
