### ISSUE TITLE
set max_mds to 1 before upgrade cephfs

### ISSUE THREAD

**Issue by jshen28** [rook/rook#7373]
**Is this a bug report or feature request?**
* Bug Report

By reading the official upgrade [guide](https://docs.ceph.com/en/latest/cephfs/upgrading/), it recommends to setting `max_mds` to 1 before upgrade. It also recommends to stop all standby daemons before upgrade active MDS. But it seems rook does not follow this pattern. Will this deviation cause unexpected behaviours?

**Deviation from expected behavior:**

Might be better set `max_mds` to 1 and then setting it back after upgrade completes.

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by BlaineEXE** [comment]
Rook used to do this. I wrote the initial code that did that, but it seems like it was removed at some point, though the code that sets `max_mds` back to the user's desired value still exists. I was under the expectation that Ceph would eventually not require `max_mds` to be set to `1` for updates/upgrades, but that isn't reflected in the latest docs. I'll try to ask someone working on Ceph MDS to see if the docs are up to date here, and then we'll know what to do for Rook.

**Comment by BlaineEXE** [comment]
Hey @batrick, would you be able to comment on whether setting `max_mds` to `1` is still necessary for MDS/cephfs upgrades?

**Comment by BlaineEXE** [comment]
This may have been the commit that removed the code. It's possible this was not the best thing. We may need to investigate this support again.
- https://github.com/rook/rook/commit/9feb0287c509dfead7245b8615ec9cafe03b5d7e

**Comment by batrick** [comment]
> Hey @batrick, would you be able to comment on whether setting `max_mds` to `1` is still necessary for MDS/cephfs upgrades?

It is.

**Comment by jshen28** [comment]
@batrick thank you for the clarification. After setting `max_mds` to **1** and wait for only rank 0, do I have to stop all standby MDS before upgrading active MDS? Or can I simply do a rolling upgrade on each of the existing MDS?

**Comment by BlaineEXE** [comment]
I don't believe it's necessary to wait for OSDs to be updated for MDS updates. Ceph should have +/-2 versions compatibility between daemons. @batrick would have a more definite answer.

**Comment by batrick** [comment]
> @BlaineEXE Thank you for the feedback. Another question is do we need to wait for all OSDs properly upgraded before upgrading MDS?

That is the routine recommendation. What I would suggest is that you set max_mds to 1 for all file systems before upgrading the OSDs. For large deployments, it make take quite a while for the other ranks to stop. You want to start the process as early as possible.

It is currently necessary to stop all standbys before doing upgrades but I have a ticket to fix that: https://tracker.ceph.com/issues/49719 I will finish this in time for Pacific.

Also, all standby-replay daemons should be stopped. Unfortunately, that's not as simple as just turning standby replay off for a file system. I have filed a bug for that too: https://tracker.ceph.com/issues/49719 It will be done for Pacific. So, you should be able to assume turning off the `allow_standby_replay` setting will also kill the standby-replay daemons (causing them to respawn as up:standby).

Now, when it's time to actually do the upgrade, keep in mind that if you do not upgrade all standbys together first then you run the risk of repeated failovers for rank 0. An old MDS version will replace rank 0 in a rolling fashion until an MDS running the newer version takes over.

**Comment by BlaineEXE** [comment]
Thanks, @batrick! It sounds like we need to do some work to adjust how MDSes are updated. I added this to the Rook v1.6 release milestone, and I'm hoping it's something that we'll be able to backport to v1.5 also.

Between v1.5 and v1.6, we will have to support upgrades for Nautilus, Octopus, and Pacific, so we'll still have to have a manual process for stopping standby replay daemons for N and O.

> What I would suggest is that you set max_mds to 1 for all file systems before upgrading the OSDs. For large deployments, it make take quite a while for the other ranks to stop. You want to start the process as early as possible.

We currently reconcile cephfs (and MDSes) in parallel with OSDs. I think it should be pretty safe to do these in parallel, even though the possibility exists that the MDS reconcile code might not set `max_mds` to **1** before the first OSDs are being updated. If updating a given MDS fails because it needs OSDs to be updated first, the MDS reconcile should fail and restart until its able to succeed (once OSDs are updated). Maybe @leseb has thoughts on this detail?

**Comment by jshen28** [comment]
@BlaineEXE Can I take this issue and implement the missing steps? we happen to have a internal use case and have to fix the steps...

**Comment by BlaineEXE** [comment]
I think that sounds good. I'll assign you to this issue. Feel free to reach out with questions either here or on the PR. I would suggest referencing https://github.com/rook/rook/commit/9feb0287c509dfead7245b8615ec9cafe03b5d7e as mentioned a couple days ago for what the code for this might look like.

**Comment by batrick** [comment]
> Also, all standby-replay daemons should be stopped. Unfortunately, that's not as simple as just turning standby replay off for a file system. I have filed a bug for that too: https://tracker.ceph.com/issues/49720 [<-- Blaine: updated link] It will be done for Pacific. So, you should be able to assume turning off the `allow_standby_replay` setting will also kill the standby-replay daemons (causing them to respawn as up:standby).

PSA: https://github.com/ceph/ceph/pull/40145

**Comment by batrick** [comment]
> It is currently necessary to stop all standbys before doing upgrades but I have a ticket to fix that: https://tracker.ceph.com/issues/49719 I will finish this in time for Pacific.

PSA: https://github.com/ceph/ceph/pull/40511

**Comment by jshen28** [comment]
@batrick is the upgrading process only necessary for a major ceph upgrade? for example when upgrading from 15.1.x -> 15.2.x, do I still need to stop standby-replay daemons?

**Comment by batrick** [comment]
> @batrick is the upgrading process only necessary for a major ceph upgrade?

No, it's necessary for all upgrades.

> for example when upgrading from 15.1.x -> 15.2.x, do I still need to stop standby-replay daemons?

Yes.

**Comment by jshen28** [comment]
@batrick thank you. still wants to double check one thing: can osd & mds be upgraded at the same time? or do I need to wait until all osds are upgraded before performing mds upgrade?

**Comment by batrick** [comment]
> @batrick thank you. still wants to double check one thing: can osd & mds be upgraded at the same time? or do I need to wait until all osds are upgraded before performing mds upgrade?

Yes, they could be. In fact, it's probably wise to at least do the MDS pre-upgrade sequence while the OSDs are being upgraded.
