### ISSUE TITLE
Create operator kit for common operations?

### ISSUE THREAD

**Issue by jamiehannaford** [rook/rook#740]
I'm wondering whether there is enough overlap in different operators to warrant some kind of common library that will make the lives of those who want to write an operator easier. Have you folks thought about doing this?

We've already discussed doing so for the [etcd-operator](https://github.com/coreos/etcd-operator/issues/1125) and I've recently written a proposal for an OperatorKit here:

https://docs.google.com/document/d/1NJhFcNezJyLM952eaYVcdfIQFQYWsAx4oTaA82-Frdk

Is this something that would benefit the wider operator community? If so, would love to hear your feedback in that proposal.

**Comment by travisn** [comment]
@jamiehannaford yes it's an interesting idea to pursue. With the rise of operators it has been on our mind. Good to see the thought you've already put into it! I'll add comments to the doc.

**Comment by travisn** [comment]
@jamiehannaford after a Rook operator refactor with the operator kit in mind, I've started a new repo with that work. Let's collaborate going forward on your design doc and/or in that repo. Looking forward to your feedback on if this is useful. https://github.com/rook/operator-kit
