### ISSUE TITLE
Guidelines for running Rook on AWS EBS Volumes.

### ISSUE THREAD

**Issue by FrederikNS** [rook/rook#741]
Recently I have been looking into running Rook or Ceph Standalone on our Kubernetes cluster.

We run our Kubernetes cluster in AWS using Kops as our cluster manager.

I would like to run Rook/Ceph using AWS EBS volumes as the actual backing stores. If I were to set up everything manually using plain Ceph, I would be able to just reference the EBS volumes in my volumes config for each of the osd pods, but it doesn't seem to be possible using Rook as it simply uses volumes mounted on the actual nodes.

Is it possible to run Rook on AWS EBS volumes? and if so, how?

**Comment by bzub** [comment]
In the [Cluster Configuration](https://github.com/rook/rook/blob/master/Documentation/cluster-tpr.md#storage-selection-settings) you can specify to use anything that shows up as a block device in addition to using a directory under a mounted filesystem.  Especially relevant are the `useAllDevices`, `deviceFilter`, and `storeConfig` settings if the EBS volumes show up as block devices under /dev/.

**Comment by FrederikNS** [comment]
@bzub: Thanks for the response, but If I provision an EBS volume using a Kubernetes Persistent Volume Claim, then the disk isn't mounted on any node until a pod requests it. So the volume would never show up in /dev/, unless I mount the disks manually into each node. Furthermore, if I perform a rolling upgrade of my cluster, the nodes will be replaced by new ones, and I will have to manually mount all the volumes once again. Am I missing something, or is there some way for Rook to create Persistent Volume Claims for the backing store, or use existing Persistent Volume Claims?

**Comment by bassam** [comment]
Agree that Rook should use PV underneath each OSD, including the new local storage PV support going into K8S 1.7. This would enable EBS underneath Rook and other scenarios.

**Comment by glerchundi** [comment]
WDYT if the issue is renamed to something like: "Use dynamic volume provisioning for rook itself". This would open up a wide range of possibilities by abstracting the backend store and keeping it simpler, I think (would solve #796).
