### ISSUE TITLE
Error in demo file

### ISSUE THREAD

**Issue by liu304424818** [rook/rook#7412]
```
[root@master01 ceph]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

[root@master01 ceph]# kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
master01   Ready    master   48m   v1.18.5
master02   Ready    master   46m   v1.18.5
master03   Ready    master   46m   v1.18.5

[root@master01 ceph]# kubectl get po -n rook-ceph 
NAME                                           READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-kv7b9                         3/3     Running   0          2m20s
csi-cephfsplugin-provisioner-c68f789b8-4dmj6   6/6     Running   0          2m20s
csi-cephfsplugin-provisioner-c68f789b8-jxs2q   6/6     Running   0          2m20s
csi-cephfsplugin-wvpmn                         3/3     Running   0          2m20s
csi-cephfsplugin-xh7nj                         3/3     Running   0          2m20s
csi-rbdplugin-4k2bf                            3/3     Running   0          2m21s
csi-rbdplugin-628wd                            3/3     Running   0          2m21s
csi-rbdplugin-provisioner-5bc97cdbb9-4wvrg     6/6     Running   0          2m21s
csi-rbdplugin-provisioner-5bc97cdbb9-blmc8     6/6     Running   0          2m21s
csi-rbdplugin-ssvh8                            3/3     Running   0          2m21s
rook-ceph-operator-5865fcf468-zvcn7            1/1     Running   0          9m25s
```

```
kubectl logs -n rook-ceph  rook-ceph-operator-5865fcf468-zvcn7  
2021-03-16 09:56:06.530342 E | ceph-cluster-controller: failed to reconcile. failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to perform validation before cluster creation: cannot start 5 mons on 3 node(s) when allowMultiplePerNode is false
```

But when I set it to true, a new problem arises

```
[root@master01 ceph]# cat cluster.yaml 
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 5
    allowMultiplePerNode: true
    stretchCluster:
      failureDomainLabel: topology.kubernetes.io/zone
      subFailureDomain: host
      zones:
      - name: a
        arbiter: true
      - name: b
      - name: c
  cephVersion:
    image:  ceph/daemon-base:latest-master
    allowUnsupported: true
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: ""  
  placement:
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
              - b
              - c

              - c
[root@master01 ceph]# kubectl apply -f cluster.yaml 
cephcluster.ceph.rook.io/rook-ceph unchanged


[root@master01 ceph]# kubectl get po -n rook-ceph 
NAME                                           READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-kv7b9                         3/3     Running   0          6m2s
csi-cephfsplugin-provisioner-c68f789b8-4dmj6   6/6     Running   0          6m2s
csi-cephfsplugin-provisioner-c68f789b8-jxs2q   6/6     Running   0          6m2s
csi-cephfsplugin-wvpmn                         3/3     Running   0          6m2s
csi-cephfsplugin-xh7nj                         3/3     Running   0          6m2s
csi-rbdplugin-4k2bf                            3/3     Running   0          6m3s
csi-rbdplugin-628wd                            3/3     Running   0          6m3s
csi-rbdplugin-provisioner-5bc97cdbb9-4wvrg     6/6     Running   0          6m3s
csi-rbdplugin-provisioner-5bc97cdbb9-blmc8     6/6     Running   0          6m3s
csi-rbdplugin-ssvh8                            3/3     Running   0          6m3s
rook-ceph-mon-a-canary-6ffc5846dc-k54wc        0/1     Pending   0          6s
rook-ceph-mon-b-canary-86666cddb4-p96lb        0/1     Pending   0          6s
rook-ceph-mon-c-canary-684b5569cc-927qx        0/1     Pending   0          6s
rook-ceph-mon-d-canary-58c558b5cd-5zdzs        0/1     Pending   0          6s
rook-ceph-mon-e-canary-787f6678dc-rbsfl        0/1     Pending   0          6s
rook-ceph-operator-5865fcf468-zvcn7            1/1     Running   0          13m
```
```
[root@master01 ceph]# kubectl describe po -n rook-ceph rook-ceph-mon-a-canary-6ffc5846dc-k54wc
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.
```

```
 kubectl logs -n rook-ceph  rook-ceph-operator-5865fcf468-zvcn7  

2021-03-16 10:00:36.316682 E | ceph-cluster-controller: failed to get ceph daemons versions, this typically happens during the first cluster initialization. failed to run 'ceph versions'. unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] RADOS object not found (error connecting to the cluster)
. : unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] RADOS object not found (error connecting to the cluster)
. 
2021-03-16 10:00:36.316712 I | ceph-cluster-controller: cluster "rook-ceph": version "17.0.0-2061 <unknown version>" detected for image "ceph/daemon-base:latest-master"
2021-03-16 10:00:36.374077 I | op-mon: start running mons
2021-03-16 10:00:36.379529 I | op-mon: parsing mon endpoints: 
2021-03-16 10:00:36.379546 W | op-mon: ignoring invalid monitor 
2021-03-16 10:00:36.391372 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":[]}] data: mapping:{"node":{}} maxMonId:-1]
2021-03-16 10:00:36.963888 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2021-03-16 10:00:36.964302 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2021-03-16 10:00:38.164468 I | op-mon: targeting the mon count 5
2021-03-16 10:00:38.171961 I | op-mon: sched-mon: created canary deployment rook-ceph-mon-a-canary
2021-03-16 10:00:38.180496 I | op-mon: sched-mon: created canary deployment rook-ceph-mon-b-canary
2021-03-16 10:00:38.192539 I | op-mon: sched-mon: created canary deployment rook-ceph-mon-c-canary
2021-03-16 10:00:38.207033 I | op-mon: sched-mon: created canary deployment rook-ceph-mon-d-canary
2021-03-16 10:00:38.218834 I | op-mon: sched-mon: created canary deployment rook-ceph-mon-e-canary
[root@master01 ceph]# 
```

**Comment by galexrt** [comment]
Whcih default files are you using? Because there is no default `cluster.yaml` with a `mon.count: 5`.

Be sure to follow the quickstart guides https://rook.io/docs/rook/v1.5/ceph-quickstart.html and use the right files for the release you are deploying https://github.com/rook/rook/tree/release-1.5/cluster/examples/kubernetes/ceph

Also your cluster should fulfill all pre-requisites, see https://rook.io/docs/rook/v1.5/k8s-pre-reqs.html and https://rook.io/docs/rook/v1.5/ceph-prerequisites.html

**Comment by liu304424818** [comment]
> 您正在使用哪个默认文件？因为没有默认`cluster.yaml`了`mon.count: 5`。
> 
> 确保遵循快速入门指南[https://rook.io/docs/rook/v1.5/ceph-quickstart.html，](https://rook.io/docs/rook/v1.5/ceph-quickstart.html)并为要部署的发行版使用正确的文件[https://github.com/rook/rook /tree/release-1.5/cluster/examples/kubernetes/ceph](https://github.com/rook/rook/tree/release-1.5/cluster/examples/kubernetes/ceph)
> 
> 此外，您的集群还应满足所有先决条件，请参阅https://rook.io/docs/rook/v1.5/k8s-pre-reqs.html和[https://rook.io/docs/rook/v1.5 /ceph-prerequisites.html](https://rook.io/docs/rook/v1.5/ceph-prerequisites.html)



I confirm that I have to meet conditions I use is https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html Stretch Cluster file

**Comment by liu304424818** [comment]
> > 您正在使用一个替代文件？因为没有替换`cluster.yaml`了`mon.count: 5`。
> > 确保遵循快速入门指南[https://rook.io/docs/rook/v1.5/ceph-quickstart.html，](https://rook.io/docs/rook/v1.5/ceph-quickstart.html)并为要部署的发行版使用正确的文件[https://github.com/rook/rook/树/版本1.5 /集群/示例/ kubernetes / ceph](https://github.com/rook/rook/tree/release-1.5/cluster/examples/kubernetes/ceph)
> > 此外，您的足以还应满足所有先决条件，请参见[https://rook.io/docs/rook/v1.5/k8s-pre-reqs.html和[https://rook.io/docs/rook /v1.5](https://rook.io/docs/rook/v1.5/k8s-pre-reqs.html%E5%92%8C%5Bhttps://rook.io/docs/rook/v1.5) /ceph-prerequisites.html]（https://rook.io/docs/rook/v1.5/ceph-prerequisites.html）
> 
> 我确认必须满足以下条件：[https：](https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html) //rook.io/docs/rook/v1.5/ceph-cluster-crd.html拉伸群集文件

Host-based clusters can succeed.
Stretch Cluster failed

**Comment by liu304424818** [comment]
> > > > 确保正在使用一个替代文件？因为没有替换`cluster.yaml`了`mon.count: 5`。确保连续快速入门指南[https://rook.io/docs/rook/v1.5/ceph-quickstart.html，](https://rook.io/docs/rook/v1.5/ceph-quickstart.html)并为要部署的发行版使用正确的文件[https://github.com/rook/rook/树/版本1.5 /进行/示例/ kubernetes / ceph](https://github.com/rook/rook/tree/release-1.5/cluster/examples/kubernetes/ceph)
> > > > 转换，您的完全还应满足所有先决条件，请参见[https://rook.io/docs/rook /v1.5/k8s-pre-reqs.html状语从句：[https://rook.io/docs/rook /v1.5](https://rook.io/docs/rook/v1.5/k8s-pre-reqs.html%E5%92%8C%5Bhttps://rook.io/docs/rook/v1.5) /ceph-prerequisites.html]（[https://rook.io/docs/rook/v1 ](https://rook.io/docs/rook/v1) [。 5 / ceph-prerequisites.html）](https://rook.io/docs/rook/v1.5/ceph-prerequisites.html%EF%BC%89)
> > > 
> > > 
> > > 我确认必须满足以下条件：[https：](https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html) //rook.io/docs/rook/v1.5/ceph-cluster-crd.html拉伸切片文件
> > 
> > 
> > 基于主机的群集可以成功。
> > 拉伸群集失败
> > allowMultiplePerNode：是否允许在单个节点上的多个阴阜的放置。生产的默认值为false。仅应在测试环境中设置为true。
> > 上面是https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html
> > 我将测试环境设置为true，但仍然失败

[root@master01 ceph]# 
[root@master01 ceph]# kubectl get po -n rook-ceph 
NAME                                           READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-bmzf5                         3/3     Running   0          7m1s
csi-cephfsplugin-mf5dn                         3/3     Running   0          7m2s
csi-cephfsplugin-provisioner-c68f789b8-f45f7   6/6     Running   0          7m1s
csi-cephfsplugin-provisioner-c68f789b8-rq9xf   6/6     Running   0          7m1s
csi-rbdplugin-jfv8x                            3/3     Running   0          7m2s
csi-rbdplugin-pj2v2                            3/3     Running   0          7m2s
csi-rbdplugin-provisioner-5bc97cdbb9-6czpg     6/6     Running   0          7m2s
csi-rbdplugin-provisioner-5bc97cdbb9-rcwwd     6/6     Running   0          7m2s
rook-ceph-mon-a-canary-6ffc5846dc-qbzlh        0/1     Pending   0          70s
rook-ceph-mon-b-canary-86666cddb4-6pgtf        0/1     Pending   0          70s
rook-ceph-mon-c-canary-684b5569cc-lrwgj        0/1     Pending   0          70s
rook-ceph-mon-d-canary-58c558b5cd-plczs        0/1     Pending   0          70s
rook-ceph-mon-e-canary-787f6678dc-pnnnx        0/1     Pending   0          70s
rook-ceph-operator-5865fcf468-bsbcx            1/1     Running   0          12m


 kubectl describe pod -n rook-ceph rook-ceph-mon-a-canary-6ffc5846dc-qbzlh  


Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.

**Comment by galexrt** [comment]
How many nodes do you have in your Kubernetes cluster? From what I can tell only 2 worker nodes and 1 master, right?

You need to have 5 or more nodes (that are eligible (no taints, e.g., kubeadm adds a taint to the master node(s) by default) to run the Ceph components) for running with `mon.count: 5` in your CephCluster CR (unless you set `allowMultiplePerNode: true`, which is not recommended for production).

**Comment by liu304424818** [comment]
> 您的Kubernetes集群中有多少个节点？从我只能告诉2个工作节点和1个主节点的角度来看，对吗？
> 
> 您需要有5个或更多节点（可以运行Ceph组件）（符合条件（默认情况下没有污点，例如kubeadm向主节点添加污点）才能运行Ceph组件）`mon.count: 5`（除非您进行设置`allowMultiplePerNode: true`，不建议将其用于生产）。

我有三个master 并且添加了污点

**Comment by liu304424818** [comment]
> > 您的Kubernetes扩展中有多少个计数器？从我只能告诉2个工作例程和1个主节点的角度来看，对吗？
> > 您需要有5个或更多例程（可以运行Ceph组件）（符合条件（有时情况下没有污点，例如kubeadm向主队列添加污点）才能运行Ceph组件）`mon.count: 5`（除非您进行设置`allowMultiplePerNode: true`，不建议将其有用生产）。
> 
> 我有三个主人且添加了污点

[root@master01 ceph]# kubectl get node
NAME       STATUS   ROLES    AGE   VERSION
master01   Ready    master   22h   v1.18.5
master02   Ready    master   22h   v1.18.5
master03   Ready    master   22h   v1.18.5

[root@master01 ceph]# kubectl describe nodes | grep Taint
Taints:             <none>
Taints:             <none>
Taints:             <none>
[root@master01 ceph]#

**Comment by liu304424818** [comment]
> > > 您的Kubernetes扩展中有多少个计数器？从我只能告诉2个工作例程和1个主例程的角度来看，对吗？
> > > 您需要有5个或更多例程（可以运行Ceph组件）（符合条件（有时情况下没有污点，例如kubeadm向主变量添加污点）能够运行Ceph组件）`mon.count: 5`（除非您进行设置`allowMultiplePerNode: true`，不建议将其有用的生产）。
> > 
> > 
> > 我有三个主人且添加了污点
> 
> [root @ master01 ceph]＃kubectl获取节点
> 名称状态角色年龄版本
> master01就绪主机22h v1.18.5
> master02就绪主机22h v1.18.5
> master03就绪主机22h v1.18.5
> 
> [root @ master01 ceph]＃kubectl描述节点| grep的污点
> 污点：
> 污点：
> 污点：
> [根@ master01 CEPH]＃
[root@master01 ceph]# cat cluster.yaml | grep true
    allowMultiplePerNode: true
        arbiter: true
    allowUnsupported: true
    useAllNodes: true
    useAllDevices: true
[root@master01 ceph]#

**Comment by liu304424818** [comment]
> > > > 您的Kubernetes扩展中有多少个计数器？从我只能告诉2个工作例程和1个主例程的角度来看，对吗？
> > > > 您需要有5个或更多例程（可以运行Ceph组件） （符合条件（有时情况下没有污点，例如kubeadm向主变量添加污点）能够运行Ceph组件）`mon.count: 5`（除非您进行设置`allowMultiplePerNode: true`，不建议将其有用的生产）。
> > > 
> > > 
> > > 我有三个主人且添加了污点
> > 
> > 
> > [root @ master01 ceph] ＃kubectl获取计数器
> > 名称状态
> > 角色年龄版本master01可用主机22h v1.18.5 
> > master02可用主机22h v1.18.5 
> > master03可用主机22h v1.18.5
> > [root @ master01 ceph] ＃kubectl描述例程| grep的污点的
> > 污点：
> > 污点：
> > 污点：
> > [根@ master01 CEPH]＃
> > [根@ master01头孢]＃猫cluster.yaml | grep是true 
> > allowMultiplePerNode：是
> > 仲裁者：是
> > allowUnsupported：是
> > useAllNodes：是
> > useAllDevices：是
> > [root @ master01 ceph]＃

  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.

**Comment by liu304424818** [comment]
> How many nodes do you have in your Kubernetes cluster? From what I can tell only 2 worker nodes and 1 master, right?
> 
> You need to have 5 or more nodes (that are eligible (no taints, e.g., kubeadm adds a taint to the master node(s) by default) to run the Ceph components) for running with `mon.count: 5` in your CephCluster CR (unless you set `allowMultiplePerNode: true`, which is not recommended for production).

 kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
master01   Ready    master   23h   v1.18.5
master02   Ready    master   23h   v1.18.5
master03   Ready    master   23h   v1.18.5

[root@master01 ceph]# kubectl describe nodes | grep Taint
Taints:             <none>
Taints:             <none>
Taints:             <none>

[root@master01 ceph]# cat cluster.yaml | grep true
    allowMultiplePerNode: true
        arbiter: true
    allowUnsupported: true
    useAllNodes: true
    useAllDevices: true

 kubectl describe po -n rook-ceph  rook-ceph-mon-a-canary-6ffc5846dc-5gmvw 

  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.

**Comment by travisn** [comment]
For a stretch cluster like this:
```yaml
  mon:
    count: 5
    allowMultiplePerNode: true
    stretchCluster:
      failureDomainLabel: topology.kubernetes.io/zone
      subFailureDomain: host
      zones:
      - name: a
        arbiter: true
      - name: b
      - name: c
```

You need 5 nodes: 1 node in zone a, 2 nodes in zone b, and 3 nodes in zone c. If you want to test with allowMultiplePerNode: true, you would still need at least 3 nodes, one in each zone. What zones do you have assigned to your nodes? But if you don't have 5 nodes, the stretch cluster is not recommended anyway unless you are just testing.

**Comment by liu304424818** [comment]
> For a stretch cluster like this:
> 
> ```yaml
>   mon:
>     count: 5
>     allowMultiplePerNode: true
>     stretchCluster:
>       failureDomainLabel: topology.kubernetes.io/zone
>       subFailureDomain: host
>       zones:
>       - name: a
>         arbiter: true
>       - name: b
>       - name: c
> ```
> 
> You need 5 nodes: 1 node in zone a, 2 nodes in zone b, and 3 nodes in zone c. If you want to test with allowMultiplePerNode: true, you would still need at least 3 nodes, one in each zone. What zones do you have assigned to your nodes? But if you don't have 5 nodes, the stretch cluster is not recommended anyway unless you are just testing.

Yes, I was just testing it, but it failed
