### ISSUE TITLE
OSD-Prepare pods fail when creating pvc-based Ceph cluster on SELinux enforcing Kubernetes

### ISSUE THREAD

**Issue by aniket202** [rook/rook#7413]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I am creating a PVC-based Ceph cluster on RKE2 Kubernetes. **SELinux** is enforced on the node, so I had to pass **ROOK_HOSTPATH_REQUIRES_PRIVILEGED** flag as true in the operator.yaml (otherwise init-containers were failing with the permission denied error). After this rest of the pods started successfully, but osd-prepare pods started failing.
Looking at the init container in the osd-prepare pods, I could see that the volumeDevice (from the PV) is not getting mounted correctly, because the init-container is starting in the privileged mode (this behavior is even mentioned in the comments [here](https://github.com/rook/rook/blob/93db66692d449edec13a8e2721876f35a56d3d26/pkg/operator/ceph/cluster/osd/spec.go#L767)). Looking at the code, seems like passing ROOK_HOSTPATH_REQUIRES_PRIVILEGED as true will always create the init container in privileged mode, which means volumeDevice can not be mount thus making osd-prepare pods to fail in case of pvc-based ceph (Is this understanding correct?)

It would be great if anyone can help me get this scenario working on SELinux enforcing cluster. Thanks.

PS : The exact same manifests work when I disable SELinux.

**Expected behavior:**
PVC based ceph cluster gets created successfully on a SELinux enforcing Cluster

**How to reproduce it (minimal and precise):**

Create a RKE2 Cluster with selinux: true on a SELinux enforcing VM (I used RHEL 8.2 from Azure)
Create PVC based Rook Ceph Cluster as mentioned [here](https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html#pvc-based-cluster)
(With ROOK_HOSTPATH_REQUIRES_PRIVILEGED as true and false both are failing)

**File(s) to submit**:

Logs from init container from osd-prepare pods -

```
+ PVC_SOURCE=/set1-data-0x8gxm
+ PVC_DEST=/mnt/set1-data-0x8gxm
+ CP_ARGS=(--archive --dereference --verbose)
+ '[' -b /mnt/set1-data-0x8gxm ']'
+ cp --archive --dereference --verbose /set1-data-0x8gxm /mnt/set1-data-0x8gxm
cp: cannot stat '/set1-data-0x8gxm': No such file or directory
```

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux 8.2 (Ootpa)
* Kernel (e.g. `uname -a`): 4.18.0-193.14.3.el8_2.x86_64
* Cloud provider or hardware configuration: Azure RHEL 8.2 VM
* Rook version (use `rook version` inside of a Rook Pod): v1.5.7
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.8
* Kubernetes version (use `kubectl version`): v1.19.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2

**Comment by travisn** [comment]
The scenario sounds the same as running on OpenShift where SELinux is enabled and we have many clusters running with the on-PVC option. Something must be different with your env though. @leseb any ideas?

**Comment by aniket202** [comment]
@travisn @leseb any other ideas please? Sorry to bother again. Please let me know if I can provide more information

**Comment by travisn** [comment]
@aniket202 Could you share the following details? 
- The job spec for the osd prepare that shows the mounts
- The deployment spec for the osd daemon that shows the mounts. 

The init container failure you see seems like from the osd daemon container, not the osd prepare job

**Comment by aniket202** [comment]
@travisn sorry for the delay in getting back, I was having different issues on the env. Following is the osd-prepare job, I see that osd daemon is still not created. And attaching logs screenshot. 

I have only set ROOK_HOSTPATH_REQUIRES_PRIVILEGED to true and using cluster-on-pvc.yaml 

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/64406697/114170953-45f4bd80-9951-11eb-8771-f15e3329501c.png">

[osd-prepare-job.yaml.txt](https://github.com/rook/rook/files/6285257/osd-prepare-job.yaml.txt)
