### ISSUE TITLE
Ceph: PG errors and PVC stuck at pending

### ISSUE THREAD

**Issue by mkl262** [rook/rook#7423]
Hi, I followed the instructions in [ceph-quickstart.md](https://github.com/rook/rook/blob/release-1.5/Documentation/ceph-quickstart.md), but the cluster starts with inactive and undersized PGs (the `ceph status` output is below), and when I try to create a pvc, it is stuck at pending, and I don’t see any errors in the logs.

edit: I noticed this error in the rook operator: `ceph-crashcollector-controller: node reconcile failed on op "unchanged": Operation cannot be fulfilled on deployments.apps "rook-ceph-crashcollector-10.50.11.2": the object has been modified; please apply your changes to the latest version and try again`

**Environment**:
* OS (e.g. from /etc/os-release): `Ubuntu 20.04`
* Kernel (e.g. `uname -a`): `5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: HP DL360 gen10, Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz, 96GB RAM
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.5.8 go: go1.13.8`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)`
* Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
  cluster:
    id:     88572381-6b89-4445-b774-827341d70eef
    health: HEALTH_WARN
            Reduced data availability: 32 pgs inactive
            Degraded data redundancy: 33 pgs undersized
 
  services:
    mon: 3 daemons, quorum a,b,c (age 116m)
    mgr: a(active, since 116m)
    osd: 4 osds: 4 up (since 116m), 4 in (since 116m); 1 remapped pgs
 
  data:
    pools:   2 pools, 33 pgs
    objects: 0 objects, 0 B
    usage:   4.0 GiB used, 4.4 TiB / 4.4 TiB avail
    pgs:     96.970% pgs not active
             32 undersized+peered
             1  active+undersized+remapped
 
  progress:
    Rebalancing after osd.1 marked in (116m)
      [............................] 

```

**Comment by travisn** [comment]
@mkl262 A few questions:
- What is your pool settings for `replicated.size`? Probably 3.
- What is the `failureDomain` for the pool? If you're using the default `host`, you need to have the OSDs spread across at least three nodes
- What does `ceph osd tree` show from the toolbox?

**Comment by mkl262** [comment]
- Yes, the size is 3
- Yes, I use the default, but I'm running on a single node
- `ceph osd tree` output:
`ID  CLASS  WEIGHT   TYPE NAME            STATUS  REWEIGHT  PRI-AFF
-1         4.36639  root default                                  
-3         4.36639      host 10-50-11-2                           
 0    hdd  1.09160          osd.0            up   1.00000  1.00000
 1    hdd  1.09160          osd.1            up   1.00000  1.00000
 2    hdd  1.09160          osd.2            up   1.00000  1.00000
 3    hdd  1.09160          osd.3            up   1.00000  1.00000`

**Comment by mkl262** [comment]
I will try using the `cluster-test.yaml` because I run on single node.
