### ISSUE TITLE
OSD removal docs and job seem incomplete

### ISSUE THREAD

**Issue by linkvt** [rook/rook#7434]
Thanks for this project, really appreciate how much it eases the use of our storage nodes within kubernetes!

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Docs about OSD removal seem incomplete, I needed to delete the OSD deployment manually (removeOSDSIfOutAndSafeToRemove didn't work) and also needed to remove the auth entry for the OSD. 
Link: https://rook.io/docs/rook/v1.5/ceph-osd-mgmt.html#remove-an-osd

**Expected behavior:**
Depends if I did everything correctly but if:
- OSD removal docs mention deletion of auth entry
- docs also mention that deployment needs to be deleted manually
- anything else that might need to be deleted?

**How to reproduce it (minimal and precise):**
We had an OSD pod in CrashLoopBackOff state, currently still investigating why, SMART looked good but there were some strange errors in the osd pod, unfortunately logs are gone for now...
We then tried to remove the OSD to basically simulate replacing the disk and followed the documentation.

First thing I noticed was that even with the option to remove safe and out OSDs (I did a ceph osd purge to remove it) the deployment was still there - not sure how (fast) this flag works.

Second thing was after deleting the OSD deployment, and cleaning the disk as in https://rook.io/docs/rook/v1.5/ceph-teardown.html#delete-the-data-on-hosts the fresh disk was detected again, a new OSD deployment was created which errored with references to the existing auth entry. Removing it with `ceph auth del osd.123` helped.

After around a day this OSD failed again, so not sure if this was all that was needed or if the disk is broken, currently watching it.
This time I used the purge job with the same result (deployment still existed and auth entry, too).

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.2
* Kernel (e.g. `uname -a`):  5.4.0-65-generic 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.5.8
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.9
* Kubernetes version (use `kubectl version`): 1.19.7
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Vanilla with Kubepray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

**Comment by travisn** [comment]
@linkvt Did you run the [OSD Purge job](https://rook.io/docs/rook/v1.5/ceph-osd-mgmt.html#purge-the-osd-from-the-ceph-cluster)? Even if you didn't run the job, the `ceph osd purge` command from the toolbox should have removed the OSD auth. It's not expected that the OSD auth would still be there. Immediately after you purge the OSD do you see the OSD auth still? It's possible that the OSD is being re-created since it may be discovered on the same disk, so you may need to wipe the disk to avoid re-creation.

**Comment by linkvt** [comment]
@travisn thanks for the quick reply, yes I tried it once manually and once with the purge job. It seems though that you are correct, directly after the removal the auth entry is missing:

```
# ceph osd down osd.14 && ceph osd purge osd.14 --yes-i-really-mean-it && ceph auth ls | grep 14 -A3
marked down osd.14. 
purged osd.14
installed auth entries:
```

Before doing that that downing the osd manually was not effective, after a few seconds something reverted it pretty quickly again, maybe the osd itself said it is up and ceph picked it up.
```
[root@rook-ceph-tools-75d599f794-l556d /]# ceph osd tree | grep 14                                 
 14    hdd    9.09569                      osd.14                          down   1.00000  1.00000
[root@rook-ceph-tools-75d599f794-l556d /]# ceph osd tree | grep 14
 14    hdd    9.09569                      osd.14                            up   1.00000  1.00000
```

I will try again on wednesday after few days of again if I can get the OSD into crashloopbackoff state, I guess just formatting the disk while everything keeps running will do that. I will then update here again.

**Comment by linkvt** [comment]
Tested again with the purge job, worked as it should, closing, Thanks!
