### ISSUE TITLE
Remove `c.spec.Storage.VolumeSources` from the user config?

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#7439]
What is the purpose of `c.spec.Storage.VolumeSources` to the user? Is it to support OSDs on PVC via brownfield cases? If it doesn't have a use to the user, Travis, Seb, and I talked about removing it from the cluster spec.

_Originally posted by @BlaineEXE in https://github.com/rook/rook/pull/7386#discussion_r592689508_

**Comment by BlaineEXE** [comment]
@jmolmo do you have any thoughts?

**Comment by travisn** [comment]
Already fixed by #7912
