### ISSUE TITLE
Third party resource kinds are too generic

### ISSUE THREAD

**Issue by TimJones** [rook/rook#744]
When a ThirdPartyResource is registered, it's Kind has to be unique cluster-wide. The Rook Operator uses the kind `Cluster` to mana. I think this is too generic and clashes with many other types of cluster (Redis Clusters, Kafka Clusters, ETCD Cluster etc). In fact, CoreOS already also uses `kind: Cluster` in their ETCD Operator.

Before a release to 1.0 I strongly believe that the Kind should be renamed something more specific like `RookCluster` to avoid such name clashes and confusion.

**Comment by travisn** [comment]
We have gone back and forth on this issue. See #580. Since k8s will be fixing the naming collision issues in 1.7 we will be fine to stay with the generic names.

**Comment by TimJones** [comment]
Great, thanks for the link!
