### ISSUE TITLE
Documentation: multi-site setup solutions supported?

### ISSUE THREAD

**Issue by KlavsKlavsen** [rook/rook#7447]
I have been trying to figure our WHICH multi-site setups is supported by Rook.

I see documentation explaining Ceph multi-site which is to have 2xCeph installations - one for each site - replicating to each other.
But I see absolutely no documentation of HOW to make this work with Rook - and failover?
Do you run 1 kubernetes cluster  across both sites (thats the norm described by  most that run multisite k8s) - and then 2xRook installations in same cluster? Or can Rook handle spanning the same Rook installation across 2xsites - and then with correct "labels/annotations" - ensure that a pod in site1 - only uses the PVC in site1.. But if scheduler decides to start this pod in site2 - point it to the PVC in site2 (the mirror PVC) - and ONLY IF the PVC in site1 is no longer open for writing (ie. ensure Ceph state is Primary on site2 now)?

And does rook operator handle switching Primary/Non-Primary state in a ceph multi-site setup? 

Site Failover COULD ofcourse (on ceph side) - be made totally manual.. and in such case - I would have to somehow change the storageclass name used in pods (as 2xRook in same cluster - I would have a storageclass for each.. rook-site1 and rook-site2.. and then on failover - figure out HOW to "fix" the mapping of CephFS filesystems to work on the new location (webserver files would need to be failed over to active on secondary and pods then started there - which get the same PVC from site2 storageclass) ?

I need to set this up - and will be playing with it with 3 servers in Helsinki and 3 servers in Germany (2xHetzner.com locations).
ALL hints appreciated..

**Comment by KlavsKlavsen** [comment]
I assume setting volumeBindingMode for the storage class to WaitForFirstConsumer, which delays the dynamic provisioning of a volume until a pod using it is created - would be the best way for Rook to be able to work with a single-cluster spanning 2 locations (multi-site / multi-zone) - as Rook can then KNOW which site the pod is in - and assign the corresponding storage (or NOT - if the site is in non-primary mode in ceph).

**Comment by KlavsKlavsen** [comment]
My current plan is to have a single server in Nurenburg (3rd Hetzner location) - and have that be a k8s-master.
This way - if just 2 of the datacenters can talk to each other - there will be no split-brain (and no lost quorum) and it'll be very cheap with just a single server in 3rd datacenter.

If ROOK - it could choose the Primary site (ceph wise) by asking which k8s-master is the lader - and get its location from annotation.. ? and simply follow that to decide where it runs.
This would require ROOK to run ceph-multi-site - in ONE Rook operator.. OR somehow work together with the Rook operator in the site - so they collaborate on which of them is Primary role ?

**Comment by travisn** [comment]
@KlavsKlavsen What really is the goal for your scenario? You are referring to a few different scenarios, not sure exactly what you're looking for:
- Rook primarily configures Ceph inside a single K8s cluster. Any data that needs to replicate across K8s clusters would need to use rbd/cephfs mirroring, or rgw multisite features of Ceph. Rook has CRDs to help support these scenarios, but there are some documented steps to get this working. Work is in progress with the CSI driver to make the failover more smooth when using rbd/cephfs mirroring since currently it is quite complex to configure.
- If you have two datacenters with a third K8s master in another datacenter, you may be interested in the [stretch cluster](https://rook.github.io/docs/rook/v1.5/ceph-cluster-crd.html#stretch-cluster) where data is only stored in two of the zones.
- Rook can connect to storage in an [external ceph cluster](https://rook.github.io/docs/rook/v1.5/ceph-cluster-crd.html#external-cluster)

**Comment by KlavsKlavsen** [comment]
@travisn I was looking for how best to solve this multi-datacenter setup - and whats actually "in use/supported".. I did find some documents specifying mirroring.. but it was unclear how failover then worked (as I understood it - it would be to a ceph setup, managed by a rook in a different k8s cluster)..

And as I read it - the preferred way of doing this for k8s, is using multi-zone setups (like done in multiple zones in AWS f.ex.) - where you stretch ONE cluster across multiple locations.. (and increase etcd leader election timeouts a bit to ensure it does not failover unnecessaryily).

That seems in conflict with having 2 Rook setups in the same cluster (as the cluster is stretched across the locations) and using mirroring.

I hadn't found the Rook Ceph Stretch solution.. and I will be looking forward to pacific release then :)
I will try to read up on how Ceph handles pulling data from the "local datacenter" hosts and how failover works - and what options there are regarding failover..

**Comment by travisn** [comment]
> @travisn I was looking for how best to solve this multi-datacenter setup - and whats actually "in use/supported".. I did find some documents specifying mirroring.. but it was unclear how failover then worked (as I understood it - it would be to a ceph setup, managed by a rook in a different k8s cluster)..
> 
> And as I read it - the preferred way of doing this for k8s, is using multi-zone setups (like done in multiple zones in AWS f.ex.) - where you stretch ONE cluster across multiple locations.. (and increase etcd leader election timeouts a bit to ensure it does not failover unnecessaryily).
> 
> That seems in conflict with having 2 Rook setups in the same cluster (as the cluster is stretched across the locations) and using mirroring.
> 
> I hadn't found the Rook Ceph Stretch solution.. and I will be looking forward to pacific release then :)
> I will try to read up on how Ceph handles pulling data from the "local datacenter" hosts and how failover works - and what options there are regarding failover..

@KlavsKlavsen There is some work going on related to the csi driver to make reads [topology aware](https://github.com/ceph/ceph-csi/issues/440). If there is a single cluster spread across multiple zones, ceph will still replicate the data across all the zones, meaning it will always end up with writes to all three zones (if you have 3 replicas). See the `failureDomain` property on the pools and the [topology labels](https://rook.github.io/docs/rook/v1.5/ceph-cluster-crd.html#osd-topology) on nodes to ensure the data is spread as expected.

**Comment by altrel-fero** [comment]
Is there any documentation for Rook-Ceph multi-site configuration?

We have two Rook-Ceph clusters, and we want to synchronize and replicate a bucket from one Rook-Ceph cluster to another.

**Comment by travisn** [comment]
@altrel-fero See the rgw multisite docs [here](https://rook.io/docs/rook/latest-release/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite/)
