### ISSUE TITLE
One bad disk prevents any new OSDs from being created on node

### ISSUE THREAD

**Issue by Confusingboat** [rook/rook#7449]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When a bad disk is present and selected for OSD deployment, the OSD prepare job for the node repeatedly fails. The job pod is never created, and the operator eventually logs a simple one-line error that the job failed because it could not initialize the devices due to an input/output error. Blank OSDs are still created in Ceph and show as down and out, but kubernetes deployments for the OSD are never created for any of the devices, good or bad.

**Expected behavior:**
OSD deployments should be created for all healthy disks and only the unhealthy ones should fail.

**How to reproduce it (minimal and precise):**
Add two or more empty disks to an existing node, one of which is not able to be initialized/spun-up (`fdisk` will be unable to identify the drive); then watch as Rook fails to create _any_ new OSD deployments on that node until the bad disk is removed. In my case I added six 400GB Intel S3610 SSD with the bad one having a status of `BAD CONTEXT` when checked with the `intelmas` utility.

I initially landed on #5028 upon first seeing that the job pod was not created, and then found one disk was bad after investigation stemming from observing further failures. After removing the failed disk and following the steps @travisn outlined in that issue to reset the OSD prepare job, the new OSD deployment went as expected with the remaining disks.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Server 20.04.2 LTS
* Kernel (e.g. `uname -a`): 5.10.17-051017-generic
* Cloud provider or hardware configuration: NR40700 chassis, 48GB RAM, Xeon E5-2650L v2, 250GB SSD boot drive, several 4TB HDDs (and now some 400GB SSDs after figuring out the issue)
* Rook version (use `rook version` inside of a Rook Pod): 1.5.8
* Storage backend version (e.g. for ceph do `ceph -v`): v14.2.10
* Kubernetes version (use `kubectl version`): v1.16.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by BlaineEXE** [comment]
Please post logs from both the `rook-ceph-operator` and failing `rook-ceph-osd-prepare` pods.

**Comment by travisn** [comment]
This may be fixed by #7608, which was included in v1.5.10 and v1.6.0. @Confusingboat Do you see an improvement with that fix?

**Comment by Confusingboat** [comment]
I'll try to test this again/get logs sometime this weekend and update this issue with my findings.

**Comment by travisn** [comment]
Please reopen if you find it is still needed
