### ISSUE TITLE
Idea: 10x READ performance increase for Ceph block reads?

### ISSUE THREAD

**Issue by KlavsKlavsen** [rook/rook#7452]
Under the assumption, that Ceph will serve a read from a block (such as a PVC created via rook/ceph) directly, if a replica exists on local node (where pod/docker instance is running) - at 10x higher speeds and lower latency (or more?) - because it does not need to do anything on the network for read case ?

Plan would be to either tell Ceph where to store atleast 1 of its block replicas (if that node has room ofcourse), or alternatively - we could expose (via labels) - which nodes a given PVC is located on - and make affinity rules, to make k8s scheduler allocate pod using that PVC - to nodes that has a replica locally.

This way - MOST reads would be served by local read (see assumption in beginning) - saving a HUGE deal of bandwidth - and allowing for kubernetes setups with rook+ceph on 1gb network interfaces - like what can be bought at f.ex. hetzner and OVH bare-metal servers (and others).. and then only the few situations where colocation of pod+block-replica isn't possible - will we incur the normal ceph read latency.

WDYT ?

**Comment by mykaul** [comment]
It's of course a very nice idea, but should be done in Ceph. There are (at least) two features that intend to deal with it - read from non primary is one of them (forgot what the 2nd one did) - and is in Pacific. It is very beneficial also in the cloud, where you actually pay for cross AZ traffic!

Note that we need to remember that pods may move and restart and re-run elsewhere, so we can't just continuously change the CRUSH map.

**Comment by KlavsKlavsen** [comment]
Can Rook "hint" to where Ceph should place a block / PVC device ? to make it place atleast ONE of the copies on the "hinted node" - where we're told the pod will start up ?
And then we can ask ceph WHERE the replica is located - and add a label to the PVC - and use affinity rules - to make the scheduler consider either of the X locations added in label on PVC - as possible nodes for scheduling of the pod..

**Comment by KlavsKlavsen** [comment]
Or Rook could implement a HintProvider for TopologyManager - to tell it where to "preferrably" place pods.. like CPU manager can do (based on CPU usage) https://github.com/kubernetes/kubernetes/pull/73920/files (if that API is flexible enough for this - otherwise I guesa labels FTW :)

**Comment by mykaul** [comment]
You assume the content of the PV that a pod is using is all in a single node, which is unlikely the case with Ceph, which distributes it all over.

**Comment by KlavsKlavsen** [comment]
I don't know the block size with which it would distribute them - but yes - each block would normally be on different hosts.. I don't know if ceph could be pursuaded to group blocks from same device/pvc "if asked".. this would decrease performance for "network reads" - as they would not be delivered from multiple hosts.. but if we KNOW we're going to use them "locally" - like this - it would be a fair price to pay, for having local disk-performance (and no network READ cost) for pods.

**Comment by mykaul** [comment]
Ceph uses RADOS blocks (which I believe are 4MB by default), so naturally, some of your data will be local and some not. This actually improves performance (bandwidth), as you'll get aggregated disk (and node - especially in the cloud you might be limited by disk and node limits!) performance.

**Comment by fritchie** [comment]
to be specific, RBD uses 4MB RADOS objects by default, other applications can use different sizes ... for RGW the default chunk and stripe size is also 4MB

**Comment by KlavsKlavsen** [comment]
> This actually improves performance (bandwidth), as you'll get aggregated disk

This is not the case, when you're bound by 1gb network interfaces which is whats offered in all bare-metal setups from bare-metal cloud-providers.. Which is why it would - as far as I can tell - be a huge benefit, it RGW could be hinted to "keep segment of this block device" - on a single-node.. (and the replica as well) - and then Rook could hint to k8s scheduler - where these replicas are - so it knows which nodes to preferrably schedule a pod to - giving local disk equivalent performance..
In 10Gb setups - the story is different surely.. Except if you want to lower the cross-cluster traffic..

**Comment by mykaul** [comment]
> > This actually improves performance (bandwidth), as you'll get aggregated disk
> 
> This is not the case, when you're bound by 1gb network interfaces which is whats offered in all bare-metal setups from bare-metal cloud-providers.. Which is why it would - as far as I can tell - be a huge benefit, it RGW could be hinted to "keep segment of this block device" - on a single-node.. (and the replica as well) - and then Rook could hint to k8s scheduler - where these replicas are - so it knows which nodes to preferrably schedule a pod to - giving local disk equivalent performance..
> In 10Gb setups - the story is different surely.. Except if you want to lower the cross-cluster traffic..

As I've explained earlier, this makes less sense due to several reasons: pod placement, the need to separate failure domains (you can't have all replicas on the same node, so it has to be over the network), the object size (not to mention, if it's RGW, other pools that are used, such as the index).
1Gb will give you very low performance anyway. We use multiple bare-metal cloud provider and they do provide 10g.

Lastly, as I've asked previously, this sounds like a Ceph request first of all - please file it over there.

**Comment by KlavsKlavsen** [comment]
@mykaul which bare-metal providers provide 10gb networking? I have found none in europe (and due to european legislation I'm bound to only using european providers) 
I would not have the replica on same node ofcourse - that would be stupid :) - the thought was merely to allow for normal reads to be served locally on the nodes that have "one of the copies" of the blockdevice. I'll go ask in Ceph.
