### ISSUE TITLE
Broken markdown link in ceph-quickstart.md

### ISSUE THREAD

**Issue by tibbe** [rook/rook#7461]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The HTML link generated from the markdown is broken.

**Expected behavior:**
Link should render properly.

**How to reproduce it (minimal and precise):**
Go to https://github.com/rook/rook/blob/master/Documentation/ceph-quickstart.md#tldr. Observe broken link.

**Comment by leseb** [comment]
@jbw976 any idea?

**Comment by galexrt** [comment]
@leseb That is expected, the docs are rendered to HTMl for the website. `{{ branchName }}` is the variable that returns the right "branch" name per release, same in the below `git clone` code snippet, etc.

The page looks good in the rendered docs: https://rook.io/docs/rook/v1.5/ceph-quickstart.html#tldr
