### ISSUE TITLE
k8s pod mount cephfs pvc fail !

### ISSUE THREAD

**Issue by hankedang** [rook/rook#7479]
**Environment**:
* OS (e.g. from /etc/os-release): centos7
* Kernel (e.g. `uname -a`): 3.10.0-693.2.2.el7.x86_64
* Rook version (use `rook version` inside of a Rook Pod): v1.5
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.9
* Kubernetes version (use `kubectl version`): v1.17.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE

I can create a pvc success, but , when I mount that pvc on pod , get error message

 **pod describe** 
![image](https://user-images.githubusercontent.com/8179609/112604598-4c633f80-8e51-11eb-9ad9-08e276fa1b23.png)

 **kublet logs** 
![image](https://user-images.githubusercontent.com/8179609/112604699-6ac93b00-8e51-11eb-862a-73ddc7960a80.png)

**Comment by hankedang** [comment]
@travisn @Madhu-1 Asking for help

**Comment by Madhu-1** [comment]
@hankedang can you please run the command manually in cephfs-plugin container or plugin pod and see what is the error? And checking dmesg logs on the node where the mounting is failing should also help

**Comment by hankedang** [comment]
Sorry !  I'm not careful enough. my kernel version is 3.10, cephfs quota is not supported in kernel version < 4.17, set CSI_FORCE_CEPHFS_KERNEL_CLIENT= "false" in operator.yaml, then mount success.
@Madhu-1 Thanks for your reply!
