### ISSUE TITLE
ceph osd reports slow ops

### ISSUE THREAD

**Issue by adabuleanu** [rook/rook#7485]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
On some of our deployments ceph health reports slow opts on some OSDs, although we are running in a high IOPS environment using SSDs.
**Expected behavior:**
I want to understand where this slow ops comes from. We recently moved from rook 1.2.7 and we never experienced this issue before.

**How to reproduce it (minimal and precise):**
This does not reproduce every time. I reproduced it in some of our pipelines

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
See attached file: [ceph-cluster.log](https://github.com/rook/rook/files/6210981/ceph-cluster.log)
* Operator's logs, if necessary
See attached file: [ceph-operator.log](https://github.com/rook/rook/files/6210984/ceph-operator.log)
* Crashing pod(s) logs, if necessary
See attached file: [ceph-mon-b.log](https://github.com/rook/rook/files/6210988/ceph-mon-b.log)

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
* Kernel (e.g. `uname -a`):  3.10.0-1127.el7.x86_64
* Cloud provider or hardware configuration: Openstack
* Rook version (use `rook version` inside of a Rook Pod): v1.5.0-alpha.0.608.g3f128a4
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)
* Kubernetes version (use `kubectl version`): v1.20.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Vanilla Kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
  cluster:
    id:     640e013d-976b-47b3-aa67-5a5ccb9d89cc
    health: HEALTH_WARN
            noout flag(s) set
            1 slow ops, oldest one blocked for 12411 sec, mon.b has slow ops
  services:
    mon: 3 daemons, quorum a,b,c (age 2h)
    mgr: a(active, since 3h)
    mds: rook-ceph-ceph-fs:1 {0=rook-ceph-ceph-fs-a=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 3h), 3 in (since 3h)
         flags noout
  data:
    pools:   4 pools, 97 pgs
    objects: 22 objects, 14 KiB
    usage:   3.0 GiB used, 57 GiB / 60 GiB avail
    pgs:     97 active+clean
  io:
    client:   852 B/s rd, 1 op/s rd, 0 op/s wr
```

**Comment by fritchie** [comment]
the command "ceph health detail" should indicate which osds have slow ops
