### ISSUE TITLE
rookd should use a more full-featured logging package

### ISSUE THREAD

**Issue by bassam** [rook/rook#75]
github.com/coreos/pkg/capnslog or something that support log levels, etc. Also would be good to tie that logging to ceph logging levels.

**Comment by jbw976** [comment]
Addressed by https://github.com/rook/rook/pull/192

**Comment by rohantmp** [comment]
Just noticed this @leseb  @jbw976 I don't see any releases or a go.mod file for capnslog. It doesn't look maintained. I've opened an issue there to ask. Do we need to migrate away?

**Comment by travisn** [comment]
It is working fine for now. We certainly might consider integrating a new logging package, but let's open a new issue if/when that issue arises.

**Comment by leseb** [comment]
It's funny that a few weeks ago I was wondering if we should move to more structured logging and looked into various loggers. However, I came to the same conclusion as @travisn, what we have now is not excessively elaborated, but it's nice and simple. Also, I don't clearly see the outstanding benefit of re-writing entirely our logging implementation. At least, until we come across a Go incompatibility I won't change it. Also, it's not like we log thousands of lines every second in the operator, so the performance aspect is not so much of a concern here.
