### ISSUE TITLE
Allow disabling the node watcher that triggers configuring OSDs

### ISSUE THREAD

**Issue by travisn** [rook/rook#7534]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The operator always watches for node events and starts a reconcile when a node is ready and does not have any OSDs (after #7462 is fixed). If the cluster is deployed with `storageClassDeviceSets` or if the admin has any other reason not to trigger the reconcile with new nodes, there should be an option to disable it.

**Expected behavior:**
Consider the following:
- Add a new property `storage.watchNodesForNewDevices`
- In the example cluster.yaml set `watchNodesForNewDevices: true`
- In the example cluster-on-pvc.yaml set `watchNodesForNewDevices: false` since this example uses device sets
- If watchnodesForNewDevices is not set, it should default to `true` for backward compatibility
- The [onK8sNode() method](https://github.com/rook/rook/blob/afcfe40b5e0efef01ca66a6569e36e482c990951/pkg/operator/ceph/cluster/watcher.go#L58) has a bug where it only triggers the reconcile for a single cluster. This should be changed to loop over each cluster, then skip the cluster if `watchNodesForNewDevices` is false.

**Comment by paalkr** [comment]
Is this actually true for ceph clusters with both PVC OSDs and Device OSDs? I would imagine that "mixed clusters" would benefit from  watching nodes even with `storageClassDeviceSets `specified in the cluster manifest. Wouldn't just relying on the existing `storage.useAllNodes: false` be enough to stop reconcile when a new node is added?

**Comment by travisn** [comment]
Title is updated now to better represent the suggestion. It would be best to enable by default, and clusters with device sets likely want to disable it.
