### ISSUE TITLE
Failed to get device "sda2" info on grub partition

### ISSUE THREAD

**Issue by mleklund** [rook/rook#7543]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Sometimes I receive the following error from a crashing `rook-ceph-osd-prepare-` after node reboot:
```
2021-04-07 16:30:00.800943 D | exec: Running command: udevadm info --query=property /dev/sda2
2021-04-07 16:30:00.807713 D | exec: Running command: lsblk /dev/sda2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2021-04-07 16:30:00.810444 D | exec: Running command: ceph-volume inventory --format json /dev/sda2
failed to get available devices: failed to get device "sda2" info: failed to determine if the device was available. failed to determine if the device "/dev/sda2" is available. failed to execute ceph-volume inventory on disk "/dev/sda2". exit status 1
```
In this case I am running flatcar linux and `/dev/sda2` is a grub partition for booting the operating system.  Further `/dev/sda2` is not in my list of devices for ceph consideration.  

**Expected behavior:**
I would expect rook/ceph to not even look at this device, as it is not in this list.  Maybe it should ignore all unidentified devices, but it certainly should not cause a crash in the `rook-ceph-osd-prepare-`.

**How to reproduce it (minimal and precise):**
I am not sure how to make it happen, as it does not always happen, just often enough to be annoying.  Often a reboot of the node cleans it up.  Maybe a busy device is causing the issue?  I am not sure what is happening.

**File(s) to submit**:

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2765.2.2
VERSION_ID=2765.2.2
BUILD_ID=2021-03-24-1749
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2765.2.2 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
```
* Kernel (e.g. `uname -a`): `Linux k8w05 5.10.25-flatcar #1 SMP Wed Mar 24 17:11:24 -00 2021 x86_64 Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz GenuineIntel GNU/Linux`
* Cloud provider or hardware configuration:  Dell M620 128GB Ram  E5-2670
* Rook version (use `rook version` inside of a Rook Pod): 1.5.9, also happened under 1.4.9
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)`
* Kubernetes version (use `kubectl version`):`Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubeadm, bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

[pod-logs.txt](https://github.com/rook/rook/files/6273344/pod-logs.txt)

[cluster.yaml.txt](https://github.com/rook/rook/files/6273348/cluster.yaml.txt)

**Comment by travisn** [comment]
Interesting that it fails intermittently and not consistently. Seems like the call to [CheckIfDeviceAvailable()](https://github.com/rook/rook/blob/fcf634e3b7808e4338e7fd261c047aae4793e99b/pkg/daemon/ceph/osd/daemon.go#L355) should set `isAvailable = false` and just log the error instead of failing the whole pod. Then the prepare job could finish its work instead of failing intermittently. @BlaineEXE @leseb @satoru-takeuchi  Do you see a reason why we would need to treat this as an error condition?

**Comment by mleklund** [comment]
I don’t have an idea why it fails, but once it starts failing it is not intermittent, it will continue to fail unt after reboot.

**Comment by satoru-takeuchi** [comment]
@travisn I guess it's enough to leave log than returning error.

This error handling code was introduced in this commit.
https://github.com/rook/rook/commit/fbd1a0ce91b663c6d71bffb3668852db4a5080a#diff-fec75260852a95ce5e6fff3db6aec0db4cc5fca300edef6ba8f02a9e73ab0241R90

It seems not to treat some bugs.

**Comment by mleklund** [comment]
It seems to be more frequent after an Omaha update of flatcar, to my knowledge the partition never gets rewritten after initial install and is a grub second stage partition for boot. ([partition info here](https://kinvolk.io/docs/flatcar-container-linux/latest/reference/developer-guides/sdk-disk-partitions/))

**Comment by satoru-takeuchi** [comment]
@mleklund I created a PR to fix this problem. I'll backport it to both v1.5 and v1.6.

**Comment by BlaineEXE** [comment]
I wonder if this is also what is behind https://github.com/rook/rook/issues/7449.
