### ISSUE TITLE
Unable to expose ceph mgr outside the cluster (advertises with pod address).

### ISSUE THREAD

**Issue by mazocode** [rook/rook#7550]
* Bug Report

**Deviation from expected behavior:**
cep-mgr is getting started with foreground public address set to the pod network.
 
**Expected behavior:**
ceph-mgr started with foreground public addr set to cluster ip.

**How to reproduce it (minimal and precise):**
Install a cluster and see the args passed to ceph-mgr. Here is an example with (172... being the pod network):
```
$ kubectl -n rook-ceph exec -ti pod/rook-ceph-mgr-a-6447ff58f7-wvccx -- cat /proc/1/cmdline
ceph-mgr--fsid=704c17c2-6e27-471e-8303-64359d976fdf--keyring=/etc/ceph/keyring-store/keyring--log-to-stderr=true--err-to-stderr=true--mon-cluster-log-to-stderr=true--log-stderr-prefix=debug --default-log-to-file=false--default-mon-cluster-log-to-file=false--mon-host=[v2:10.90.207.31:3300,v1:10.90.207.31:6789],[v2:10.90.140.166:3300,v1:10.90.140.166:6789],[v2:10.90.70.100:3300,v1:10.90.70.100:6789]--mon-initial-members=c,a,b--id=a--setuser=ceph--setgroup=ceph--client-mount-uid=0--client-mount-gid=0--foreground--public-addr=172.20.208.141
```
This won't cause any harm within the cluster but using the cluster as an external ceph cluster will fail if your pod network does not get routed on your network (which I guess is usually the case). The clusters ceph client will try to reach the mgr on it's internal address like here:

```
$ ceph device ls
2021-04-07T21:27:25.383+0000 7f1559f3e700  1 -- 172.28.199.192:0/1710760887 --> [v2:172.20.208.141:6800/3606154506,v1:172.20.208.141:6801/3606154506] -- mgr_command(tid 0: {"prefix": "device ls", "target": ["mon-mgr", ""]}) v1 -- 0x7f1554071a60 con 0x7f153402c960
```

Here is an old and unresolved (but closed) related issue https://github.com/rook/rook/issues/3284 This describes the situation with exposing ceph trough host networking while I am using multus but otherwise it looks the same .

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): 1.5.9
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.9
* Kubernetes version (use `kubectl version`): v1.20.2
* Storage backend status (e.g. for Ceph use `ceph health`): HEALTH_OK

**Comment by mazocode** [comment]
Looks like this is a bit more complicated than anticipated. The mon daemons are started with --public-addr=<ClusterIP> --public-bind-addr=<podIP>. Unfortunately this does not work with ceph-mgr. The mgr seems to ignore the --public-bind-addr and tries to bind to the --public-addr which fails with a ClusterIP.

**Comment by mazocode** [comment]
Here is some ugly hack I came up with as a temporary work around. Unfortunately, this only lasts as long as the deployment does not get recreated by the operator. 

This patch creates a wrapper script for calling ceph-mgr with --public-addr set to the address of the specified interface (replace net1 with whatever interface you need):

The wrapper script:
```
$ kubectl -n rook-ceph apply -f - <<EOS
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-mgr-wrapper
data:
  ceph-mgr.sh: |
    #!/bin/sh
    set -euo pipefail
    exec ceph-mgr \$* --public-addr=\$(ip -o -4 addr show dev net1 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
EOS
```

Patch to call the script:
```
$ kubectl patch -n rook-ceph deployment/rook-ceph-mgr-a --type=json -p '
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value: { "name": "ceph-mgr-wrapper", "mountPath": "/wrapper" }
- op: add
  path: /spec/template/spec/volumes/-
  value: { "name": "ceph-mgr-wrapper", "configMap": { "name": "ceph-mgr-wrapper", "defaultMode": 0744 } }
- op: replace
  path: /spec/template/spec/containers/0/command/0
  value: "/wrapper/ceph-mgr.sh"
'
```

Anyone with ideas on how to get something like this into the operator?

**Comment by leseb** [comment]
Isn't the POD_IP not the one coming from `net1` in your case? So basically the request is to have the `public-addr` set to a different IP? What about the mons, are they working?

**Comment by mazocode** [comment]
> Isn't the POD_IP not the one coming from `net1` in your case? So basically the request is to have the `public-addr` set to a different IP? What about the mons, are they working?

My net1 interface (storage network) is within the 10.132/15 range. 

I stumbled across this problem while trying to use a healthy rook ceph cluster as a storage backend with another k8 cluster. The mons are created with their POD address specified as public bind address but they are advertised with their service address. The external client can talk to the mon pods successfully using the cluster network. As for the mgr, rook does not create a service. I assume because there is no option to specify an address for advertising the mgr (at least I couldn't find one). Running 'ceph mgr dump' shows the POD network address the client tries to contact when running commands like 'device ls':

```
$ ceph mgr dump
{
    "epoch": 2697,
    "active_gid": 375134,
    "active_name": "a",
    "active_addrs": {
        "addrvec": [
            {
                "type": "v2",
                "addr": "10.132.0.16:6800",
                "nonce": 1472830463
            },
            {
                "type": "v1",
                "addr": "10.132.0.16:6801",
                "nonce": 1472830463
            }
        ]
    },
    "active_addr": "10.132.0.16:6801/1472830463",
```
This is the output from the external cluster after applying my wrapper and commands like 'device ls' succeed.

**Comment by leseb** [comment]
Ok thanks, I feel like if we add a service to the mgr this could help in "some" circumstances like running mon/mgr commands. However, interacting with OSDs via ceph-csi won't work since again we would need to add a service for each OSDs.

How are you planning on consuming that cluster?

**Comment by leseb** [comment]
Stay tuned, once Rook 1.6 is out it will include Ceph-CSI 3.3 which has all we need to support Multus properly. Also, make sure you use at least Ceph V15.2.8. Once in place along with Multus/Whereabouts, the NADs will be propagated to Ceph-CSI pods. So no matter how many clusters you have they will all get the NAD attached and will be able to consume the external Ceph. So we don't need to expose mgr/osd further through services.

**Comment by mazocode** [comment]
> Stay tuned, once Rook 1.6 is out 
Sounds awesome! Is there a timeline for this?

**Comment by leseb** [comment]
> > Stay tuned, once Rook 1.6 is out
> 
> Sounds awesome! Is there a timeline for this?

Within the next week or so.

**Comment by leseb** [comment]
I'm closing this for now. Thanks!
