### ISSUE TITLE
Support selector PVC config in rook.io/block provisioner

### ISSUE THREAD

**Issue by bzub** [rook/rook#756]
Just happened to notice this feature is missing in rook.io/block, and I didn't see an issue for it.

### Reference
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector

In this example the selector was empty (`Selector: {}`) but still raises the error.
```console
$ kubectl -n monitoring describe pvc
Name:           alertmanager-am-db-alertmanager-am-0 
Namespace:      monitoring                           
StorageClass:   rbd                                  
Status:         Pending                              
Volume:                                              
Labels:         alertmanager=am                      
                app=alertmanager                     
Annotations:    control-plane.alpha.kubernetes.io/leader={"holderIdentity":"3646686f-5894-11e7-8cfa-0a580a020107","leaseDurationSeconds":15,"acquireTime":"2017-06-24T16:40:00Z","renewTime":"2017-06-24T16:41:00Z","lea...                                               
                volume.beta.kubernetes.io/storage-class=rbd                                               
                volume.beta.kubernetes.io/storage-provisioner=rook.io/block                               
Capacity:                                            
Access Modes:                                        
Events:                                              
  FirstSeen     LastSeen        Count   From                                                                                    SubObjectPath   Type            Reason                  Message                      
  ---------     --------        -----   ----                                                                                    -------------   --------        ------                  -------                      
  3m            3m              1       rook.io/block rook-operator-579479322-vbvrh 3646686f-5894-11e7-8cfa-0a580a020107                        Normal          Provisioning            External provisioner is provisioning volume for claim "monitoring/alertmanager-am-db-alertmanager-am-0"                                
  3m            3m              1       rook.io/block rook-operator-579479322-vbvrh 3646686f-5894-11e7-8cfa-0a580a020107                        Warning         ProvisioningFailed      Failed to provision volume with StorageClass "rbd": claim Selector is not supported                                                    
  3m            3s              48      persistentvolume-controller                                                                             Normal          ExternalProvisioning    cannot find provisioner "rook.io/block", expecting that a volume for the claim is provisioned either manually or via external software
```

**Comment by lucasvel** [comment]
Any updates on this one? I'd like to use this feature for example when creating a k8s StatefulSet for running a MySQL Galera cluster and getting each pod (mysql-0, mysql-1, etc) to get its own block storage.

Thanks!

**Comment by kokhang** [comment]
@lucasvel ill take a look on this. Thanks

**Comment by abh** [comment]
Has this been fixed?

**Comment by ts-anzedovzanperovic** [comment]
Hi, I have exactly the same issue. I installed prometheus-stack via helm chart and for prometheus pvc the field selector was added (it is empty like that -> selector: {}) and the error from rook  is:  Failed to provision volume with StorageClass "rbd": claim Selector is not supported. Now in this helm chart (https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack, version 61.3.2, kubernetes version 1.32.2) there is also installed another pvc for grafana which does not have selector field and rook was manage to provision pv for that pvc. Now even if i edit the prometheus pvc and remove selector field it is added back automatically. I even comment out all selector in prometheus section for pvc inside values.yaml file but the field is keep getting added into pvc configuration. They funny thing is that I have the same rook and prometheus charts version in another cluster (but a little lower kubernetes version 1.31.5) and it works but there is no field selector in prometheus pvc definition.

**Comment by Madhu-1** [comment]
@ts-anzedovzanperovic what version of Rook you are using? This issue was created for flex driver and its deprecated and removed in kubernetes and csi is the way to consume the storage? can you please open a new issue you are facing any issue with csi pvc flow?
