### ISSUE TITLE
Ceph dashboard not showing up

### ISSUE THREAD

**Issue by CodingSpiderFox** [rook/rook#7576]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I cannot access the ceph dashboard from outside the cluster.

**Expected behavior:**
I want to be able to access the dashboard from all computers on my local network (not only the nodes in the kubernetes cluster)

**How to reproduce it (minimal and precise):**
Install 3 node cluster with kubespray. VMs have bridged network adapters directly to the network of my workstation
Install rook via helm via ansible

Create nodeport

```
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-mgr-dashboard-external-https
  namespace: rook-ceph
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
spec:
  ports:
  - name: dashboard
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  sessionAffinity: None
  type: NodePort
```

Got these services now: 

```
NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
csi-cephfsplugin-metrics                 ClusterIP   10.233.49.191   <none>        8080/TCP,8081/TCP   19h
csi-rbdplugin-metrics                    ClusterIP   10.233.7.219    <none>        8080/TCP,8081/TCP   19h
rook-ceph-mgr                            ClusterIP   10.233.4.76     <none>        9283/TCP            19h
rook-ceph-mgr-dashboard                  ClusterIP   10.233.45.113   <none>        7000/TCP            19h
rook-ceph-mgr-dashboard-external-https   NodePort    10.233.20.172   <none>        8443:30421/TCP      16m
rook-ceph-mon-b                          ClusterIP   10.233.2.81     <none>        6789/TCP,3300/TCP   19h
rook-ceph-mon-c                          ClusterIP   10.233.48.7     <none>        6789/TCP,3300/TCP   19h
rook-ceph-mon-d                          ClusterIP   10.233.51.132   <none>        6789/TCP,3300/TCP   17m
``` 

Looked up the node where ceph mgr is running on:

```
k describe pod -n rook-ceph rook-ceph-mgr-a-56f7598c6b-cwjfc               ✔  system ⬢ │ kubernetes-admin@cluster.local ⎈  13:50:48   
Name:         rook-ceph-mgr-a-56f7598c6b-cwjfc
Namespace:    rook-ceph
Priority:     0
Node:         node2/192.168.3.168
```

Execute `telnet 192.168.3.168 30421`

No connection can be established

**File(s) to submit**:

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Kernel (e.g. `uname -a`):
`Linux node2 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
VirtualBox VMs, 2 cores 6G RAM each
* Rook version (use `rook version` inside of a Rook Pod):
`k exec --stdin --tty -n rook-ceph rook-ceph-mon-b-689ff787fc-fjk8s /bin/sh´ -> `rook version` returns 
```
sh-4.4# rook
sh: rook: command not found
```

---> made the command work using rook toolbox. Please update template description to use rook toolbock below

rook: v1.6.0-alpha.0.18.gc17a344
go: go1.15.7

* Storage backend version (e.g. for ceph do `ceph -v`):
`ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)`
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Kubespray on local VMs
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN Reduced data availability: 1 pg inactive; OSD count 0 < osd_pool_default_size 3

**Comment by galexrt** [comment]
Your `NodePort` service is pointing at port `8443` and not `7000` which the Rook Ceph MGR dashboard is running on.

Check your CephCluster object for the `dashboard:` section and use the port which is specified there, and use that one in your NodePort service, see https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html#cluster-settings.

Also checkout https://rook.io/docs/rook/v1.5/ceph-dashboard.html

**Comment by CodingSpiderFox** [comment]
Yes, figured that out with a friend, too, thanks :)
