### ISSUE TITLE
Orchestrator not available after deploying rook-ceph with helm

### ISSUE THREAD

**Issue by CodingSpiderFox** [rook/rook#7577]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I cannot create OSDs from the dashboard. When clicking the "Create" button in the OSD section I get the following message

```
	Information
Orchestrator is not available. Please consult the documentation on how to configure and enable the functionality.```

**Expected behavior:**
I want to be able to configure everything from the dashboard

**How to reproduce it (minimal and precise):**
Install 3 node cluster with kubespray. VMs have bridged network adapters directly to the network of my workstation
Install rook via helm via ansible


**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Kernel (e.g. `uname -a`):
`Linux node2 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
VirtualBox VMs, 2 cores 6G RAM each
* Rook version (use `rook version` inside of a Rook Pod):
`k exec --stdin --tty -n rook-ceph rook-ceph-mon-b-689ff787fc-fjk8s /bin/sh´ -> `rook version` returns 
```
sh-4.4# rook
sh: rook: command not found
```

---> made the command work using rook toolbox. Please update template description to use rook toolbock below

rook: v1.6.0-alpha.0.18.gc17a344
go: go1.15.7

* Storage backend version (e.g. for ceph do `ceph -v`):
`ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)`
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Kubespray on local VMs
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN Reduced data availability: 1 pg inactive; OSD count 0 < osd_pool_default_size 3

**Comment by travisn** [comment]
@CodingSpiderFox You want to create OSDs from the Ceph dashboard? This is not currently supported. Using the CephCluster CR is still required.

**Comment by CodingSpiderFox** [comment]
Oh OK. What does CR stand for?

**Comment by travisn** [comment]
> Oh OK. What does CR stand for?

Custom Resource. The [docs](https://rook.github.io/docs/rook/v1.5/ceph-quickstart.html) walk through the setup, and see the example [CephCluster CR](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml), aka cluster.yaml.

**Comment by CodingSpiderFox** [comment]
OK thanks :)

**Comment by CodingSpiderFox** [comment]
> @CodingSpiderFox You want to create OSDs from the Ceph dashboard? This is not currently supported. Using the CephCluster CR is still required.

Doesn't the helm chart install a default cluster.yml?

**Comment by travisn** [comment]
> > @CodingSpiderFox You want to create OSDs from the Ceph dashboard? This is not currently supported. Using the CephCluster CR is still required.
> 
> Doesn't the helm chart install a default cluster.yml?

No, the helm chart creates the equivalent of crds.yaml, common.yaml, and operator.yaml

**Comment by CodingSpiderFox** [comment]
OK thanks for the clarification
