### ISSUE TITLE
Make use of Go v1.16 `embed` feature

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#7609]
**Is this a bug report or feature request?**
* Feature Request

Go v1.16 introduces a new `embed` feature that can embed files into Go binaries. We should consider doing this for the CSI template manifests since they are a strict requirement for the Go binary.

This is not something we **have** to do if having the files on the filesystem is a "feature," but it could be beneficial.

https://blog.golang.org/go1.16

**Comment by travisn** [comment]
Agreed that would be nice for the csi driver, easier to manage them as an embedded resource than assume a file structure in the image.
