### ISSUE TITLE
ci: test our CSV in the CI

### ISSUE THREAD

**Issue by leseb** [rook/rook#7638]
We need to setup a CI job to run our CSV and make sure it can deploy a basic cluster. Pasting a few links found from various sources, it looks like the community repo from the operatorhub.io has some githubactions:

* https://github.com/mvalarh/op-action-examples/blob/master/.github/workflows/main.yml#L24-L37
* https://github.com/operator-framework/community-operators/blob/master/.github/workflows/operator_test.yaml
* https://operator-framework.github.io/community-operators/action/

@subhamkrai want to give it a try?

**Comment by subhamkrai** [comment]
sure @leseb
