### ISSUE TITLE
Builds failing on Fedora 33 due to yq

### ISSUE THREAD

**Issue by alimaredia** [rook/rook#7658]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```
$ sudo make IMAGES=ceph build
[sudo] password for amaredia: 
=== helm package rook-ceph
==> Linting /home/amaredia/rook/_output/rook-ceph

1 chart(s) linted, 0 chart(s) failed
Successfully packaged chart and saved it to: /home/amaredia/rook/_output/charts/rook-ceph-v1.6.0-alpha.0.87.g432e42e04-dirty.tgz
=== helm index
=== ensuring modules are tidied
=== go vet
=== go build linux_amd64
{ \
	set -e ;\
	mkdir -p /home/amaredia/rook/.cache/tools/linux_amd64 ;\
	CONTROLLER_GEN_TMP_DIR=$(mktemp -d) ;\
	cd $CONTROLLER_GEN_TMP_DIR ;\
	go mod init tmp;\
	unset GOOS GOARCH  # avoid error: "cannot install cross-compiled binaries when GOBIN is set" ;\
	export CGO_ENABLED=0  # do not need gcc nor the errors that come with not having it ;\
	export GOBIN=$CONTROLLER_GEN_TMP_DIR  # go get dependencies into the temp dir ;\
	echo === installing controller-gen ;\
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.5.0;\
	mv $CONTROLLER_GEN_TMP_DIR/controller-gen /home/amaredia/rook/.cache/tools/linux_amd64/controller-gen-v0.5.0 ;\
	echo === installing yq ;\
	go get github.com/mikefarah/yq/v3;\
	mv $CONTROLLER_GEN_TMP_DIR/yq /home/amaredia/rook/.cache/tools/linux_amd64/yq-v3 ;\
	rm -rf $CONTROLLER_GEN_TMP_DIR ;\
}
go: creating new go.mod: module tmp
=== installing controller-gen
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.5.0
=== installing yq
go get github.com/mikefarah/yq/v3: module github.com/mikefarah/yq@upgrade found (v1.15.0), but does not contain package github.com/mikefarah/yq/v3
make[3]: *** [build/makelib/golang.mk:205: /home/amaredia/rook/.cache/tools/linux_amd64/yq-v3] Error 1
the new crd file must be smaller since the description fields were stripped!
length before 8552
length after 8552
make[2]: *** [Makefile:82: generate-csv-ceph-templates] Error 1
make[1]: *** [Makefile:30: ceph.linux_amd64] Error 2
make: *** [Makefile:119: build] Error 2

$ sudo make IMAGES=ceph INCLUDE_CSV_TEMPLATES="" build
=== helm package rook-ceph
==> Linting /home/amaredia/rook/_output/rook-ceph

1 chart(s) linted, 0 chart(s) failed
Successfully packaged chart and saved it to: /home/amaredia/rook/_output/charts/rook-ceph-v1.6.0-alpha.0.87.g432e42e04-dirty.tgz
=== helm index
=== ensuring modules are tidied
=== go vet
=== go build linux_amd64

NOT INCLUDING OLM/CSV TEMPLATES!

=== container build build-25e2a466/ceph-amd64
sha256:e4fdebfaf2b9b3d45c76621d0f3a35d4c3cd6477b6cba8657bc7e1a9176eabf8
{ \
	set -e ;\
	mkdir -p /home/amaredia/rook/.cache/tools/linux_amd64 ;\
	CONTROLLER_GEN_TMP_DIR=$(mktemp -d) ;\
	cd $CONTROLLER_GEN_TMP_DIR ;\
	go mod init tmp;\
	unset GOOS GOARCH  # avoid error: "cannot install cross-compiled binaries when GOBIN is set" ;\
	export CGO_ENABLED=0  # do not need gcc nor the errors that come with not having it ;\
	export GOBIN=$CONTROLLER_GEN_TMP_DIR  # go get dependencies into the temp dir ;\
	echo === installing controller-gen ;\
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.5.0;\
	mv $CONTROLLER_GEN_TMP_DIR/controller-gen /home/amaredia/rook/.cache/tools/linux_amd64/controller-gen-v0.5.0 ;\
	echo === installing yq ;\
	go get github.com/mikefarah/yq/v3;\
	mv $CONTROLLER_GEN_TMP_DIR/yq /home/amaredia/rook/.cache/tools/linux_amd64/yq-v3 ;\
	rm -rf $CONTROLLER_GEN_TMP_DIR ;\
}
go: creating new go.mod: module tmp
=== installing controller-gen
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.5.0
=== installing yq
go get github.com/mikefarah/yq/v3: module github.com/mikefarah/yq@upgrade found (v1.15.0), but does not contain package github.com/mikefarah/yq/v3
make[3]: *** [build/makelib/golang.mk:205: /home/amaredia/rook/.cache/tools/linux_amd64/yq-v3] Error 1
make[2]: *** [Makefile:71: do.build] Error 2
make[1]: *** [Makefile:30: ceph.linux_amd64] Error 2
make: *** [Makefile:119: build] Error 2
```

**Expected behavior:**
Running make with or without `INCLUDE_CSV_TEMPLATES=""` should succeed.

**How to reproduce it (minimal and precise):**

Build rook on Fedora 33.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Fedora 33
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
I think the issue goes away if you run `make crds`, can you confirm?

**Comment by alimaredia** [comment]
@leseb it does not :(. I get the same output:
[amaredia@fedora30alirook ~]$ git clone https://github.com/rook/rook.git ; cd rook
Cloning into 'rook'...
remote: Enumerating objects: 76392, done.
remote: Counting objects: 100% (1796/1796), done.
remote: Compressing objects: 100% (768/768), done.
remote: Total 76392 (delta 1064), reused 1490 (delta 940), pack-reused 74596
Receiving objects: 100% (76392/76392), 40.99 MiB | 20.33 MiB/s, done.
Resolving deltas: 100% (53034/53034), done.
[amaredia@fedora30alirook rook]$ make crds
{ \
	set -e ;\
	mkdir -p /home/amaredia/rook/.cache/tools/linux_amd64 ;\
	CONTROLLER_GEN_TMP_DIR=$(mktemp -d) ;\
	cd $CONTROLLER_GEN_TMP_DIR ;\
	go mod init tmp;\
	unset GOOS GOARCH ;\
	export CGO_ENABLED=0 ;\
	export GOBIN=$CONTROLLER_GEN_TMP_DIR ;\
	echo === installing controller-gen ;\
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.5.0;\
	mv $CONTROLLER_GEN_TMP_DIR/controller-gen /home/amaredia/rook/.cache/tools/linux_amd64/controller-gen-v0.5.0 ;\
	echo === installing yq ;\
	go get github.com/mikefarah/yq/v3;\
	mv $CONTROLLER_GEN_TMP_DIR/yq /home/amaredia/rook/.cache/tools/linux_amd64/yq-v3 ;\
	rm -rf $CONTROLLER_GEN_TMP_DIR ;\
}
go: creating new go.mod: module tmp
=== installing controller-gen
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.5.0
=== installing yq
go get github.com/mikefarah/yq/v3: module github.com/mikefarah/yq@upgrade found (v1.15.0), but does not contain package github.com/mikefarah/yq/v3
make: *** [build/makelib/golang.mk:202: /home/amaredia/rook/.cache/tools/linux_amd64/controller-gen-v0.5.0] Error 1

**Comment by alimaredia** [comment]
This issue went away after I removed the golang package I installed via `dnf` and installed go via `wget` like these instructions: https://tecadmin.net/install-go-on-centos/. Should I close the issue?

**Comment by leseb** [comment]
Glad the issue is gone, let's close. Thanks!
