### ISSUE TITLE
stderr is not being captured for some external commands

### ISSUE THREAD

**Issue by jbw976** [rook/rook#766]
When Rook calls `ceph` tool commands, stderr is captured and logged OK.  However, when `rbd` commands are called, we are not capturing stderr, which makes troubleshooting more difficult.

There may be another path or two where stderr is missed, so we should do an audit.  At least we have the vast majority of `ceph` commands capturing stderr OK already.

**Comment by bassam** [comment]
I changed executeCommand to use CombinedOutput:

```
func executeCommand(context *clusterd.Context, tool string, args []string) ([]byte, error) {
	output, err := context.Executor.ExecuteCommandWithCombinedOutput("", tool, args...)
	return []byte(output), err
}
```

and now can see the error

**Comment by jbw976** [comment]
That makes sense.  However, I don't think that's completely safe to do since the caller will try to unmarshal the output.  If the underlying call writes to stderr but doesn't return an error exit code (e.g. it writes a warning statement to stderr) then the caller will now try to unmarhsal the combined output of both stdout and stderr, which would be malformed.

I doubt that's a very common scenario though, but it could be possible.

**Comment by bassam** [comment]
@jbw976 it fails unit tests so I'm not committing it, but we do need a more robust approach.
