### ISSUE TITLE
v1.6.0 clean deploy fails to create bucket

### ISSUE THREAD

**Issue by ClaudiuLSH** [rook/rook#7660]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Creating ObjectBucketClaim fails with:
```
I0416 12:34:04.713663       7 controller.go:396]  "msg"="provisioning" "key"="velero/ceph-bucket" "bucket"="velero-5f88a094-8e28-4b29-af81-26a8020f390a"
2021-04-16 12:34:04.713683 I | op-bucket-prov: initializing and setting CreateOrGrant services
2021-04-16 12:34:04.713698 I | op-bucket-prov: getting storage class "rook-ceph-bucket"
2021-04-16 12:34:04.725843 I | op-bucket-prov: Provision: creating bucket "velero-5f88a094-8e28-4b29-af81-26a8020f390a" for OBC "ceph-bucket"
2021-04-16 12:34:06.717237 I | ceph-object-controller: retrying 'radosgw-admin' command with OMAP backend to work around FIFO file I/O issue
E0416 12:34:06.792933       7 controller.go:199] error syncing 'velero/ceph-bucket': error provisioning bucket: Provision: can't create ceph user: no user name provided and unable to generate a unique name: error getting ceph user "ceph-user-IOBsBnoQ": radosgw-admin command err. 2021-04-16T12:34:06.783+0000 7fd1d9d74340  0 failed reading zonegroup info: ret -2 (2) No such file or directory
2021-04-16T12:34:06.783+0000 7fd1d9d74340  0 ERROR: failed to start notify service ((2) No such file or directory
2021-04-16T12:34:06.783+0000 7fd1d9d74340  0 ERROR: failed to init services (ret=(2) No such file or directory)
couldn't init storage provider: exit status 5, requeuing
```

**How to reproduce it (minimal and precise):**
Apply the following manifest in a new namespace.
```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket
  namespace: velero
spec:
  generateBucketName: velero
  storageClassName: rook-ceph-bucket
```

**Environment**:
* Newly deployed rook v1.6.0 following quickstart, no custom configs.
* OS (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS
* Kernel (e.g. `uname -a`):  5.8.0-50-generic 
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.6.0 go: go1.16.3  
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.0 (0c2054e95bcd9b30fdd908a79ac1d8bbc3394442) pacific (stable) but I see ceph-version=15.2.9-0 while checking with `watch --exec kubectl -n rook-ceph get deployments -l rook_cluster=rook-ceph -o jsonpath='{range .items[*]}{.metadata.name}{"  \treq/upd/avl: "}{.spec.replicas}{"/"}{.status.updatedReplicas}{"/"}{.status.readyReplicas}{"  \tceph-version="}{.metadata.labels.ceph-version}{"\n"}{end}'`
* Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+rke2r1", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-04-02T03:22:00Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type: rke2
* Storage backend status:  `Error initializing cluster client: ObjectNotFound('RADOS object not found (error calling conf_read_file)',)`

**Comment by travisn** [comment]
@BlaineEXE Looks like a follow up from #7600 is needed, if you could take a look. I wonder if the pre-Pacific Ceph deployments are still all affected by this issue. In an upgrade test I also see a similar message where the operator keeps trying to reconcile:
```
2021-04-16 04:24:10.343292 I | ceph-object-controller: retrying 'radosgw-admin' command with OMAP backend to work around FIFO file I/O issue
2021-04-16 04:24:10.696724 I | ceph-object-controller: retrying 'radosgw-admin' command with OMAP backend to work around FIFO file I/O issue
...
```

**Comment by ClaudiuLSH** [comment]
While creating CephObjectStore following the [documentation](https://rook.io/docs/rook/v1.6/ceph-object.html) I see the following error:
```
2021-04-16 14:20:26.609762 E | ceph-object-controller: failed to reconcile failed to add finalizer: failed to add finalizer "cephobjectstore.ceph.rook.io" on "object-storage": CephObjectStore.ceph.rook.io "object-storage" is invalid: spec.dataPool.replicated.size: Invalid value: 0: spec.dataPool.replicated.size in body should be greater than or equal to 1
```

I am assuming the documentation is not yet updated? I deleted CephObjectStore, upgraded to ceph 1.6.0, recreated with corrected manifest and everything is back to normal now.

**Comment by travisn** [comment]
The docs look correct to me. Perhaps you have invalid whitespace from copying the example? Or did you use the [object-ec.yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/object-ec.yaml) from the examples folder? If you see the issue again, please open a separate issue. Thanks!

**Comment by BlaineEXE** [comment]
Please attach additional logs:
1. FULL Rook Operator logs with `ROOK_DEBUG_LEVEL: DEBUG`
2. CephObjectStore manifest
3. StorageClass for the above object store
4. ObjectBucketClaim manifest
5. CephCluster manifest

**Comment by ClaudiuLSH** [comment]
For now this cluster was fixed. I will deploy a new cluster with the same configuration on Monday or Tuesday, will get back with requested logs then. I will come back with a comment even if I can't reproduce the issue.

**Comment by BlaineEXE** [comment]
Thanks @ClaudiuLSH! I haven't been able to repro myself.

**Comment by ClaudiuLSH** [comment]
Everything started from this:
```
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: my-store
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    instances: 1
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
```

Which is in the docs [here](https://rook.io/docs/rook/v1.6/ceph-object.html).

That causes this error:
```
2021-04-19 17:11:21.464119 E | ceph-object-controller: failed to reconcile failed to add finalizer: failed to add finalizer "cephobjectstore.ceph.rook.io" on "object-storage": CephObjectStore.ceph.rook.io "object-storage" is invalid: spec.dataPool.replicated.size: Invalid value: 0: spec.dataPool.replicated.size in body should be greater than or equal to 1
```

If I use the example located at: `rook/cluster/examples/kubernetes/ceph/object.yaml` everything works fine.

So the initial report from this issue is due to this error, this worked fine with rook v1.5.9 and I did not bother to check logs of the operator after v1.6.0 release.

You can reproduce with this:
1. Install steps:
   ```
   cd rook/cluster/examples/kubernetes/ceph
   kubectl create -f crds.yaml -f common.yaml -f operator.yaml
   kubectl create -f cluster.yaml
   ```
2. Configure S3 with above `CephObjectStore`;
3. Create storage class:
   ```apiVersion: storage.k8s.io/v1
   kind: StorageClass
   metadata:
      name: rook-ceph-bucket
   provisioner: rook-ceph.ceph.rook.io/bucket
   reclaimPolicy: Delete
   parameters:
     objectStoreName: object-storage
     objectStoreNamespace: rook-ceph
     region: securdps-demo
   ```
4. Create a bucket, which will fail with initally reported error.

So I am closing the issue since this is a mistake on my part, while using examples from git with this release everything works fine.

**Comment by BlaineEXE** [comment]
I also believe this is a duplicate of #7661 .
