### ISSUE TITLE
Can't create an erasure coded CephBlockPool, CephObjectStore, or CephFilesystem

### ISSUE THREAD

**Issue by cyrilcros** [rook/rook#7661]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Can't create a CephFileSystem with erasure coding for my data pools. Really looks like a regression of #4750
See operator's logs below

**Expected behavior:**
The CephFileSystem is accepted as valid by the operator even if `spec.dataPools.replicated.size` is 0 (replicated: 0 / erasure coded 4 data chunks 2 data chunks for me).

**How to reproduce it (minimal and precise):**

- 1.6.0 helm chart; `csi.enableRbdDriver: false` only change. Clean install.
- 16.2.0 Ceph cluster with 6 HDD for data + 3SSD as metadata device across 3 nodes

I am using the config below:

    ---
    apiVersion: ceph.rook.io/v1
    kind: CephFilesystem
    metadata:
       name: rook-ceph-fs
       namespace: rook-ceph
    spec:
       metadataPool:
         deviceClass: ssd
         failureDomain: host
         replicated:
           size: 3
       dataPools:
       - erasureCoded:
           dataChunks: 4
           codingChunks: 2
         failureDomain: osd
         deviceClass: hdd
    metadataServer:
      activeCount: 1
      activeStandby: true

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary

 `2021-04-16 16:33:16.229404 E | ceph-file-controller: failed to reconcile failed to add finalizer: failed to add finalizer "cephfilesystem.ceph.rook.io" on "rook-ceph-fs": CephFilesystem.ceph.rook.io "rook-ceph-fs" is invalid: spec.dataPools.replicated.size: Invalid value: 0: spec.dataPools.replicated.size in body should be greater than or equal to 1`

* Crashing pod(s) logs, if necessary
No crashes seen. The cluster is created and healthy.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
* Kernel (e.g. `uname -a`):  `Linux arnold 5.8.0-26-generic #27-Ubuntu SMP Wed Oct 21 22:29:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux `
* Cloud provider or hardware configuration: Self hosted cluster; 3 SSD partition + 6 HDD across 3 nodes, not highly available and osd-level nly replication
* Rook version (use `rook version` inside of a Rook Pod): 1.6.0 helm chart; `csi.enableRbdDriver: false` only change
* Storage backend version (e.g. for ceph do `ceph -v`):  `v16.2.0`
* Kubernetes version (use `kubectl version`): `1.21.0`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): See hardware conf.
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN mon b is low on available space; Degraded data redundancy: 1 pg undersized; 1 slow ops, oldest one blocked for 1576 sec, mon.a has slow ops` not unusual for me

**Comment by travisn** [comment]
I see, this affects EC pools for all types of CephBlockPool, CephObjectStore, and CephFilesystem. We will need to get this fixed in v1.6.1. In the meantime, a workaround should be to change the `minimum: 1` property for pool size in crds.yaml to `minimum: 0`

**Comment by cyrilcros** [comment]
@travisn Thanks for looking into this!

**Comment by tibbe** [comment]
> I see, this affects EC pools for all types of CephBlockPool, CephObjectStore, and CephFilesystem. We will need to get this fixed in v1.6.1. In the meantime, a workaround should be to change the `minimum: 1` property for pool size in crds.yaml to `minimum: 0`

Where exactly in `crds.yaml` is that? Greping for `minimum: 1` doesn't make it easy to find (due to huge CRD definitions in that file).

**Comment by cyrilcros** [comment]
@tibbe See https://github.com/rook/rook/pull/7662/files if needed.
