### ISSUE TITLE
Error when applying v1.6.0 `crds.yaml` to `1.5.9` cluster

### ISSUE THREAD

**Issue by jmmaloney4** [rook/rook#7675]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When applying the `crds.yaml` file from the `v1.6.0` tag, get a large number of errors. Full output is attached here: [log.txt](https://github.com/rook/rook/files/6332034/log.txt).

```
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "cephobjectstores.ceph.rook.io", Namespace: ""
for: "./crds.yaml": CustomResourceDefinition.apiextensions.k8s.io "cephobjectstores.ceph.rook.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
Error from server (Invalid): error when applying patch:
```

**Expected behavior:**

`crds.yaml` should update without issue.

**How to reproduce it (minimal and precise):**

Checkout `v1.6.0` tag. Then `kubectl apply -f crds.yaml`

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
@jmmaloney4 This looks like the same as #7659. For now the workaround is to manually remove `preserveUnknownFields` from the CRDs before upgrading, still looking for an automated fix for this...
