### ISSUE TITLE
ci: add integration test for ceph object store TLS

### ISSUE THREAD

**Issue by leseb** [rook/rook#7695]
Set up rgw with TLS needs to be added in the CI.

**Comment by thotz** [comment]
@leseb : May I extend existing [ceph_base_object_test.go](https://github.com/rook/rook/blob/master/tests/integration/ceph_base_object_test.go) to include TLS cases than having entire new github action ?

**Comment by leseb** [comment]
Whatever is easier. For instance, ` ceph_base_object_test.go` could remain the way it is but the canary action here: https://github.com/rook/rook/blob/1e7f1b4ae0b49cba2e251ceb8fb6f27e8bb3874c/.github/workflows/canary-integration-test.yml#L15 could set up rgw with TLS.

What do you think?
