### ISSUE TITLE
Crashes Docker Kubernetes

### ISSUE THREAD

**Issue by chrispduck** [rook/rook#7696]
### Overview
Following the quickstart guide, I tried to install release 1.6 to my a Docker for Desktop Kubernetes cluster. After applying cluster.yaml, the kubernetes cluster ceases to function, with basic kubernetes commands such as ` kubectl get pods ` timing out or returning internal errors (see below). 

After applying the appropriate rook-ceph YAML files, the kubectl command stopped working
```
$ kubectl get pods
Unable to connect to the server: net/http: TLS handshake timeout
```

this later turned into
```
$ kubectl get pods 
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
```

However, the docker command `docker ps` outputs as normal. 

### Information
 The problem has also been reproduced on both the Windows setup below, and a version of Docker for Desktop Mac 

Note: the Mac error produced
```
Fatal Error
Docker daemon failed to start
2021-04-19T14:58:51Z dockerd time="2021-04-19T14:58:51.349982263Z" level=warning msg="Falling back to default propagation for bind source in daemon root" container=dddc0da7a1f740a2bb4976ab717dab9b0c38323b99660b382af5fd10159222c2 source=/
```

Docker is unable to reset the cluster, leaving it in a hanging broken state.

### Steps to reproduce the behaviour
  1. kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.6.0/cluster/examples/kubernetes/ceph/crds.yaml -f https://raw.githubusercontent.com/rook/rook/v1.6.0/cluster/examples/kubernetes/ceph/common.yaml -f https://raw.githubusercontent.com/rook/rook/v1.6.0/cluster/examples/kubernetes/ceph/operator.yaml

  2. kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.6.0/cluster/examples/kubernetes/ceph/cluster-test.yaml

### Environment
  - Windows Version: Windows 10 Enterprise, version: 20H2
  - Docker Desktop Version: v20.10.5
  - HyperV (WSL 1) 
 - kernel: Linux CJP2W10L 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
- Cluster type: Docker Desktop
- Kubectl Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", - GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- ceph version 12.2.13 (584a20eb0237c657dc0567da126be145106aa47e) luminous (stable)

**Comment by travisn** [comment]
Not sure you'll want to run Rook with docker in desktop anyway. Rook requires dedicated disk(s), which if you are just testing would be much safer in a VM. Ceph and Windows also don't get along, but not sure that plays into this issue since it's still on the linux kernel.
