### ISSUE TITLE
rook-ceph: failed to configure local ceph cluster with 1 monitor node

### ISSUE THREAD

**Issue by aasraoui** [rook/rook#7701]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
rook ceph fail to create ceph cluster with 1 monitor.
**Expected behavior:**
Ceph cluster 
**How to reproduce it (minimal and precise):**

Configure cluster.yaml with 1 mon node and enable host networking 

cluster.yaml config snapshots:

network:
    # enable host networking
        provider: host

mon:
    # Set the number of mons to be started. Must be an odd number, and is generally recommended to be 3.
    count: 1

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
*  centos 7.7
* Kernel (e.g. `uname -a`):
* 3.10.0-1062.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Rook v1.5.6
* Storage backend version (e.g. for ceph do `ceph -v`):
* 
* Ceph version "15.2.8-0 octopus"
* Kubernetes version (use `kubectl version`):

ceph monitor log + ceph operator log:

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

I can curl the mon node from the host network : curl http://10.x.x101:6789
curl http://10.x.x.101:6789 or 3300 port
ceph v2

**Comment by travisn** [comment]
@aasraoui What failure are you seeing? I was able to bring up a minikube cluster with host networking and didn't see any immediate issues.

**Comment by aasraoui** [comment]
from the operator log:
 ceph-cluster-controller: failed to reconcile. failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to start mon pods: failed to check mon quorum a: failed to wait for mon quorum: exceeded max retry count waiting for monitors to reach quorum



ceph operator + monitor log attached:

[ceph-operator-log.txt](https://github.com/rook/rook/files/6346084/ceph-operator-log.txt)
[monitor-log.txt](https://github.com/rook/rook/files/6346090/monitor-log.txt)

**Comment by travisn** [comment]
It seems the operator can't connect to the mon to confirm quorum is initialized. Do you have a firewall enabled? Or this [troubleshooting topic](https://rook.github.io/docs/rook/v1.6/ceph-common-issues.html#monitors-are-the-only-pods-running) may help.

**Comment by aasraoui** [comment]
@travisn yes firewall is enabled and 6789 and 3300 ports are open . i already re-started the cluster with 3 mons and they are in quorum. Perhaps this happens only with 1 mon..

**Comment by travisn** [comment]
Mons are created one at a time and join quorum before adding the next one. So if 3 mons worked, 1 mon must work as well. Something else must be happening to prevent the 1 mon case.
