### ISSUE TITLE
failed to set login credentials for the ceph dashboard

### ISSUE THREAD

**Issue by aasraoui** [rook/rook#7706]
**Is this a bug report or feature request?**
* Bug Report
operator fails to initialize dashboard 
op-mgr: failed modules: "dashboard". failed to initialize dashboard: failed to set login credentials for the ceph dashboard: failed to set login creds on mgr: failed to complete command for set dashboard creds
**Deviation from expected behavior:**

**Expected behavior:**
Cluster should be accessible via Dashboard
**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
cluster yaml config with 3 mon and host networking:
 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* centos 7
* Kernel (e.g. `uname -a`):
* 3.10.0-1062.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Rook v1.5.6 

* Storage backend version (e.g. for ceph do `ceph -v`):
* ceph version 15.2.8
* Kubernetes version (use `kubectl version`):
* v1.18.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

operator log:

**Comment by subhamkrai** [comment]
@aasraoui please paste debug logs and the above log is not complete. thanks

**Comment by aasraoui** [comment]
@subhamkrai operator log attached here ..

[operator-full-log.txt](https://github.com/rook/rook/files/6351423/operator-full-log.txt)

**Comment by subhamkrai** [comment]
@aasraoui sorry if I was not clear, can you please change https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L407 this to `DEBUG`

**Comment by aasraoui** [comment]
is operator restart needed to capture the debug log ?

**Comment by travisn** [comment]
> is operator restart needed to capture the debug log ?

When you update that setting on the operator deployment, the operator will automatically restart

**Comment by aasraoui** [comment]
i had to re-start the operator to see any changes in the log  , now the mons are not in quorum!!! attached are the logs:  
[operator-log-full2.txt](https://github.com/rook/rook/files/6354321/operator-log-full2.txt)

**Comment by aasraoui** [comment]
any other logs we need to capture ??

**Comment by aasraoui** [comment]
@subhamkrai @travisn 
on cluster re-build, osds orchestration is failing: 
below is operator log
[operator-log-osds.txt](https://github.com/rook/rook/files/6361350/operator-log-osds.txt)

**Comment by travisn** [comment]
In the log, looks like the mons are in quorum. What does `ceph status` show in the toolbox? And do you see failures in the osd-prepare pod logs?

**Comment by aasraoui** [comment]
@travisn they were heart beat ping issues between osds ..
When ports are open cluster is ready, but toolbox for ceph commands hangs:
NAME        DATADIRHOSTPATH   MONCOUNT   AGE     PHASE   MESSAGE                        HEALTH
rook-ceph   /var/lib/rook     3          6h51m   Ready   Cluster created successfully   HEALTH_OK


[root@rook-ceph-tools-664b7555b8-mzrfj /]# ceph status

**Comment by aasraoui** [comment]
@travisn ceph osd prep log for ceph-worker5 shows osd0 and osd1 are being skipped : 2021-04-23 16:40:20.851580 I | cephosd: skipping osd0: "f37529aa-ed24-422c-92b4-b200c6e935ab" running on a different ceph cluster "74d50638-f6d6-42fb-84ed-213109388990"
2021-04-23 16:40:20.851591 I | cephosd: Skipping osd0 as no instances are running on ceph cluster "ab65b727-c21b-4005-982e-deebd5665001"
2021-04-23 16:40:20.851596 I | cephosd: skipping osd1: "1c6031c5-58ea-49c0-b21b-d296e8c2a80b" running on a different ceph cluster "74d50638-f6d6-42fb-84ed-213109388990"
2021-04-23 16:40:20.851600 I | cephosd: Skipping osd1 as no instances are running on ceph cluster "ab65b727-c21b-4005-982e-deebd5665001"
2021-04-23 16:40:20.851610 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2021-04-23 16:40:20.851616 W | cephosd: skipping OSD configuration as no devices matched the storage settings for this node "ceph-worker5"

**Comment by travisn** [comment]
Did you reinstall the cluster? The OSDs still belong to a different cluster. I'd suggest you follow the [cleanup guide](https://rook.github.io/docs/rook/v1.6/ceph-teardown.html#delete-the-data-on-hosts) and then reinstall.

**Comment by aasraoui** [comment]
@travisn yes that is correct. re-zapping the disks. osds are back in service  thank you!

**Comment by aasraoui** [comment]
@travisn still not able to access dashboard rook ceph-mgr is not listening on port 8443:
 k -n rook-ceph logs rook-ceph-mgr-a-78c45f5c46-sql85 | grep Serving
[23/Apr/2021:16:40:26] ENGINE Serving on http://10.x.x.x:9283
not sure if there is a workaround for this ..

**Comment by travisn** [comment]
@aasraoui There have been multiple issues in your cluster and it's not clear what the latest status of your cluster is. Is your cluster working, except for the dashboard? Are you just seeing that error for the dashboard in the operator log? Or what happens if you curl the dashboard endpoint from the toolbox? See the [troubleshooting guide](https://rook.github.io/docs/rook/v1.6/ceph-common-issues.html#troubleshooting-techniques) for more ideas on finding the health of the cluster.

**Comment by aasraoui** [comment]
@travisn the cluster looks healthy: cluster:
    id:     ab65b727-c21b-4005-98-xxxxx
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,c,d (age 2h)
    mgr: a(active, since 3w)
    osd: 10 osds: 10 up (since 8h), 10 in (since 3w)

  data:
    pools:   3 pools, 65 pgs
    objects: 0 objects, 0 B
    usage:   10 GiB used, 190 GiB / 200 GiB avail
    pgs:     65 active+clean
k -n rook-ceph get svc
**rook-ceph-mgr                            ClusterIP      10.101.2.228     <none>        9283/TCP            25d
rook-ceph-mgr-dashboard                  ClusterIP      10.111.171.213   <none>        8443/TCP            25d**

[root@rook-ceph-tools-664b7555b8-jndss /]#  curl 10.111.171.213:8443 -v
* Rebuilt URL to: 10.111.171.213:8443/
*   Trying 10.111.171.213...
* TCP_NODELAY set
* connect to 10.111.171.213 port 8443 failed: Connection refused
* Failed to connect to 10.111.171.213 port 8443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 10.111.171.213 port 8443: Connection refused 


[root@rook-ceph-tools-664b7555b8-jndss /]#  curl 10.101.2.228:9283
<!DOCTYPE html>
<html>
    <head><title>Ceph Exporter</title></head>
    <body>
        <h1>Ceph Exporter</h1>
        <p><a href='/metrics'>Metrics</a></p>
    </body>

**Comment by travisn** [comment]
Similar to #7756 it could be an issue with opening the port

**Comment by aasraoui** [comment]
@travis both ports: 9283 & 8443 are Open.

**Comment by lknite** [comment]
@aasraoui do you recall how you fixed this?  experiencing the same issue ...

**Comment by smirnov-mi** [comment]
> @aasraoui do you recall how you fixed this? experiencing the same issue ...
> 
> ```
> 2023-09-18 19:42:38.054473 I | op-mgr: setting ceph dashboard "admin" login creds
> 2023-09-18 19:42:53.108023 I | cephclient: command failed for set dashboard creds. trying again...
> 2023-09-18 19:43:13.139669 I | cephclient: command failed for set dashboard creds. trying again...
> 2023-09-18 19:43:33.164227 I | cephclient: command failed for set dashboard creds. trying again...
> 2023-09-18 19:43:53.212463 I | cephclient: command failed for set dashboard creds. trying again...
> 2023-09-18 19:44:13.235207 I | cephclient: command failed for set dashboard creds. trying again...
> 2023-09-18 19:44:18.235772 E | op-mgr: failed modules: "dashboard". failed to initialize dashboard: failed to set login credentials for the ceph dashboard: failed to set login creds on mgr: max command retries exceeded
> ```

Hi @lknite , were you able to get the dashboard running? I'm getting the same errors after upgrading ceph from 17.2.6 to 18.2.0
