### ISSUE TITLE
Github actions for helm test suite in master are consistently failing

### ISSUE THREAD

**Issue by travisn** [rook/rook#7707]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The helm suite is almost always failing in master on every version of K8s for the new github actions. 
See [this example master test run](https://github.com/rook/rook/runs/2394844171?check_suite_focus=true).

**Expected behavior:**
Tests in master should pass consistently.

**How to reproduce it (minimal and precise):**

Look at the master github actions

**Comment by travisn** [comment]
Connecting to a [test runner](https://github.com/rook/rook/runs/2402689275?check_suite_focus=true), I see the osd pod is crash looping with this log:

```
runner@fv-az120-492:~/work/rook/rook$ kubectl -n helm-ns logs  rook-ceph-osd-0-866957ff9b-5xfsg                                                                                                                
debug 2021-04-21T18:27:44.948+0000 7f1542c47f40  0 set uid:gid to 167:167 (ceph:ceph)
debug 2021-04-21T18:27:44.948+0000 7f1542c47f40  0 ceph version 15.2.11 (e3523634d9c2227df9af89a4eac33d16738c49cb) octopus (stable), process ceph-osd, pid 1
debug 2021-04-21T18:27:44.948+0000 7f1542c47f40  0 pidfile_write: ignore empty --pid-file
debug 2021-04-21T18:27:44.948+0000 7f1542c47f40 -1 bluestore(/var/lib/ceph/osd/ceph-0/block) _read_bdev_label failed to open /var/lib/ceph/osd/ceph-0/block: (13) Permission denied
debug 2021-04-21T18:27:44.948+0000 7f1542c47f40 -1  ** ERROR: unable to open OSD superblock on /var/lib/ceph/osd/ceph-0: (2) No such file or directory
```

@leseb it seems to be the same race condition you were investigating?

**Comment by satoru-takeuchi** [comment]
> @leseb it seems to be the same race condition you were investigating?

Yes it's very similar to what he investigated (#7405) and if it's the same problem, it would be fixed by my recent PR (#7708 ). Hmm?

**Comment by travisn** [comment]
The test build I linked in the previous comment already had the fix for #7708, so it must be a different issue

**Comment by leseb** [comment]
I think this https://github.com/rook/rook/pull/7716/commits/a59df3c4dd7a2eb43d6ee878955eacf876a2bf48 (thanks @subhamkrai !) will fix the issue.

**Comment by leseb** [comment]
> I think this [a59df3c](https://github.com/rook/rook/commit/a59df3c4dd7a2eb43d6ee878955eacf876a2bf48) (thanks @subhamkrai !) will fix the issue.

All GREEN! https://github.com/rook/rook/actions/runs/774386033 so indeed it is fixed!

**Comment by satoru-takeuchi** [comment]
Oh, my PR was insufficient, I should read code carefully. Thanks @subhamkrai !
