### ISSUE TITLE
Improve integration test logging

### ISSUE THREAD

**Issue by dangula** [rook/rook#772]
switch to capnslog from Test.Log() which doesn't output to stdout in real-time. 
Also, improve logging on existing tests.

**Comment by bassam** [comment]
one minor issue is that `go-junit-report` does not seem to do well with log output. I suspect Test.Log() does this intentionally to not intermix log output between tests and make it parsable.

I wonder if we should go a different direction and make capsnlog write logs to Test.Log() instead when running the in the context of a go test.

**Comment by dangula** [comment]
go-junit-report doesn't seem to mind capnslog. The report is being generated and errors are being reported, I make sure we are logging all errors.
