### ISSUE TITLE
Operator being timeout sensitive

### ISSUE THREAD

**Issue by LittleFox94** [rook/rook#7751]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The rook-ceph-operator is kinda timeout sensitive, `panic`ing on lost leaderelection, when `radosgw-admin` takes too much time to exit

The operator exiting makes the problem worse, because it will have to scan a lot of things again after it's started again. It will also update things again (seeing nothing changed). All of that makes additional load on the already strained cluster.

**Expected behavior:**
I'd expect it to at least not panic on such timeouts but to try again later, with the state still in memory

**How to reproduce it (minimal and precise):**
My cluster runs mostly on HDDs, having 3 controller nodes (with each running an active etcd, kube-apiserver, kube-scheduler and kube-controller-manager (but scheduler and controller-manager doing leaderelection)) which are also worker nodes and two additional worker nodes (kube-proxy, kubelet).

When upgrading rook, creating the new deployments can make enough load to have etcd be a bit slow to respond, making lost leaderelections a thing that just happens .. also, with enough I/O load, the whole node gets slow, increasing the possibility of things just taking more time than usual to complete.

I sadly don't know any easy way to reproduce this.

**Environment**:
* OS (e.g. from /etc/os-release): Debian 10
* Kernel (e.g. `uname -a`): kinda irrelevant I guess, currently its a 5.10 one, debian backports
* Cloud provider or hardware configuration: virtual machines on netcup, mostly hard disks which is probably the most relevant thing here
* Rook version (use `rook version` inside of a Rook Pod): v1.6.1, but panic on lost leaderelection isn't new
* Storage backend version (e.g. for ceph do `ceph -v`): irrelevant for this
* Kubernetes version (use `kubectl version`): v1.21.1, but since "forever" (cluster exists since 1.8 IIRC)
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): vanilla kubernetes, custom deployment
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): irrelevant for this

I took the liberty to omit some things here. The logs are just "lost leaderelection" and then dozillion panic lines, same happened after some of those "exec: timeout waiting for process radosgw-admin to return. Sending interrupt signal to the process"

I'm happy to provide more info if needed. I can totally understand this being a "bad" bug report to do something on, but don't currently know how to improve it ^^'

**Comment by travisn** [comment]
This sounds similar to some reports in the past such as #3754, unfortunately it has certainly been difficult to repro. Is your cluster resource constrained such as small nodes running low on cpu/memory? Is it an option to try nodes with more resources?

**Comment by LittleFox94** [comment]
Faster nodes would definitely help, I think the biggest problem is I/O load on the nodes with HDDs. I plan to upgrade them to SSDs anyway and replacing a controller node by one with a SSD helped a lot already. Rook is definitely not at fault here, strictly, but I can think it might be able to be more tolerant and less reinforcing the problem.

More tolerance for leader elections for example: maybe check if there is even another operator running and if that check timeouts, assume there is a high-load scenario and just wait for a minute or two and try again to be elected as leader?

**Comment by travisn** [comment]
Agreed, greater tolerance would certainly help here so Rook wouldn't restart unnecessarily. We are at the mercy of the controller runtime, not sure how much flexibility we have here. 
@leseb Are you aware of any options that would allow us to recover better from etcd leader election issues?

**Comment by BlaineEXE** [comment]
You could try this also: https://etcd.io/docs/v3.4/tuning/#disk

**Comment by leseb** [comment]
> Agreed, greater tolerance would certainly help here so Rook wouldn't restart unnecessarily. We are at the mercy of the controller runtime, not sure how much flexibility we have here.
> @leseb Are you aware of any options that would allow us to recover better from etcd leader election issues?

I am not.
