### ISSUE TITLE
 failed to check if the device "vdc" is available

### ISSUE THREAD

**Issue by hankedang** [rook/rook#7754]
* Bug Report

The server have one raw device vdc.
use `lsblk`
```
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda          253:0    0  100G  0 disk 
└─vda1       253:1    0  100G  0 part /
vdb          253:16   0  500G  0 disk 
└─vg001-data 252:0    0  500G  0 lvm  /data
vdc          253:32   0  200G  0 disk 
```

but rook-ceph-osd-prepare job does't deploy osd deployment 
rook-ceph-osd-prepare logs:

```
{"log":"2021-04-26 09:27:23.538897 D | exec: Running command: ceph-volume inventory --format json /dev/vdc\n","stream":"stderr","time":"2021-04-26T09:27:23.53893951Z"}
{"log":"2021-04-26 09:27:23.718738 I | cephosd: skipping device \"vdc\": failed to check if the device \"vdc\" is available. failed to determine if the device was available. failed to determine if the dev
ice \"/dev/vdc\" is available. failed to execute ceph-volume inventory on disk \"/dev/vdc\". exit status 1.\n","stream":"stderr","time":"2021-04-26T09:27:23.718831724Z"}
{"log":"2021-04-26 09:27:23.722066 I | cephosd: configuring osd devices: {\"Entries\":{}}\n","stream":"stderr","time":"2021-04-26T09:27:23.722101788Z"}
{"log":"2021-04-26 09:27:23.722077 I | cephosd: no new devices to configure. returning devices already configured with ceph-volume.\n","stream":"stderr","time":"2021-04-26T09:27:23.72211121Z"}
{"log":"2021-04-26 09:27:23.722174 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json\n","stream":"stderr","time":"2021-04-26T09:27:23.722196697Z"}
{"log":"2021-04-26 09:27:23.904424 E | cephosd: failed to open ceph-volume log file \"/tmp/ceph-log/ceph-volume.log\". open /tmp/ceph-log/ceph-volume.log: no such file or directory\n","stream":"stderr","t
ime":"2021-04-26T09:27:23.904503692Z"}
```

**Environment**:
* OS (e.g. from /etc/os-release): centos7
* Kernel (e.g. `uname -a`): 3.10.0-693.2.2.el7.x86_64
* Rook version (use `rook version` inside of a Rook Pod): v1.6.1
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.11
* Kubernetes version (use `kubectl version`): v1.17.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE

**Comment by travisn** [comment]
@hankedang There may be more details in the ceph-volume log. Do you see this log on the host? `/var/lib/rook/rook-ceph/log/ceph-volume.log`

**Comment by hankedang** [comment]
@travisn log file `ceph-volume.log` does not exist in `/var/lib/rook/rook-ceph/log/`.  so I can't get other message for error.
prepare job's error , failed to open  ceph-volume log file `/tmp/ceph-log/ceph-volume.log`

**Comment by hankedang** [comment]
Maybe my docker image download is in complete.  I clean docker containers and images and reboot server, redeploy k8s worker node, then everything will be fine!
