### ISSUE TITLE
Mon failover should not be triggered during a node drain until a longer timeout

### ISSUE THREAD

**Issue by travisn** [rook/rook#7776]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
During a node drain, a node may commonly be down 10-15 minutes until it is ready again. With the default mon failover timeout of 10 minutes, this means frequently the mon on that drained node would be down for longer than the timeout and then it would be failed over. 

**Expected behavior:**
During a drain it is expected that a node would be down, so we should not failover within the default timeout. Increasing the timeout to double the default (20 min) seems more practical and will help avoid the unnecessary failover during maintenance.
@sp98 thoughts?

**How to reproduce it (minimal and precise):**

Start Rook on at least 3 nodes, drain a node with a mon, then keep the node down for over 10 minutes and see the mon failover be triggered.

**Comment by sp98** [comment]
Yes, it looks like a good approach to avoid mon failover if node is down for maintenance.

**Comment by sp98** [comment]
How about we prevent mon failover if the mon pod is not assigned to any node ?

**Comment by travisn** [comment]
> How about we prevent mon failover if the mon pod is not scheduled to any node ?

This is the state that the mon will be in after a node drain and until the node comes back up, right? I think we still need a timeout. If the node doesn't come up for a really long time, it's better to attempt to start another mon to ensure full quorum. Or is there another aspect of this scenario you're thinking?

**Comment by sp98** [comment]
> > How about we prevent mon failover if the mon pod is not scheduled to any node ?
> 
> This is the state that the mon will be in after a node drain and until the node comes back up, right?
Yes 
> I think we still need a timeout. If the node doesn't come up for a really long time, it's better to attempt to start another mon to ensure full quorum. Or is there another aspect of this scenario you're thinking?
The new failed over mon  might still be pending if there are no new nodes for it to be scheduled on.

**Comment by travisn** [comment]
> > I think we still need a timeout. If the node doesn't come up for a really long time, it's better to attempt to start another mon to ensure full quorum. Or is there another aspect of this scenario you're thinking?
> 
> The new failed over mon might still be pending if there are no new nodes for it to be scheduled on.

Agreed, if there is not another node available, the mon failover won't be able to start a new mon anyway. In that case, the new mon canary would get stuck pending. But if another node is available, we would still want to go ahead with the failover. The mon failover can deal with that detection.

**Comment by sp98** [comment]
> But if another node is available, we would still want to go ahead with the failover. The mon failover can deal with that detection.

Agreed. And when the new node is available, we won't have the situation that the current mon is pending waiting to be scheduled on a node. Failover would happen in that case. We only prevent mon failover if have a situation like `monPOD.spec.nodeName` is empty after the timeout.

**Comment by travisn** [comment]
> > But if another node is available, we would still want to go ahead with the failover. The mon failover can deal with that detection.
> 
> Agreed. And when the new node is available, we won't have the situation that the current mon is pending, waiting to be scheduled on a node. Failover would happen in that case. We only prevent mon failover if have a situation like `monPOD.spec.nodeName` is empty after the timeout.

Two scenarios to clarify:
1. If the mon is portable (using a PV that can move to another node like in AWS), mon failover likely won't be needed anyway since the mon could immediately be scheduled on another node if one is available. 
2. If the mon is not portable (using a local PV or dataDirHostPath), the original mon can't start again until the same node comes back online. In this case, mon failover is still needed to detect if another node is available for a mon.

**Comment by utp887** [comment]
Downstream BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1955834
