### ISSUE TITLE
cephmgr/client package cannot use cephmgr/client/test package due to cyclical dependency

### ISSUE THREAD

**Issue by jbw976** [rook/rook#78]
We can not use the mocked types from cephmgr/client/test to test the cephmgr/client package itself because of a cyclical dependency.  This indicates a layering issue.

We could move some of the helper methods (e.g. pool.go, auth.go) to a package that is a peer of cephmgr/client.  Essentially, usage of the cephmgr/client interfaces should not be within the same package, or else they cannot be tested using the mocked implementations of those interfaces.

```
/castle/pkg/cephmgr/client
> go test
# github.com/quantum/castle/pkg/cephmgr/client
import cycle not allowed in test
package github.com/quantum/castle/pkg/cephmgr/client (test)
    imports github.com/quantum/castle/pkg/cephmgr/client/test
    imports github.com/quantum/castle/pkg/cephmgr/client

FAIL    github.com/quantum/castle/pkg/cephmgr/client [setup failed]
```

**Comment by travisn** [comment]
we can refactor this if needed for tests in the future
