### ISSUE TITLE
Rook-ceph crds forbid deploying s3 storage without secure options

### ISSUE THREAD

**Issue by poul1x** [rook/rook#7803]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I had successfully deployed object store in rook-ceph cluster with version `release-1.4`. 
But in `release-1.6` deploy fails with error:

```bash
kubectl apply -f object_storage.yaml
The CephObjectStore "s3-storage" is invalid:
* spec.gateway.sslCertificateRef: Invalid value: "null": spec.gateway.sslCertificateRef in body must be of type string: "null"
* spec.gateway.securePort: Invalid value: "null": spec.gateway.securePort in body must be of type integer: "null"
```

**Expected behavior:**

Object storage is deployed successfully.

**Note**: This [sample](https://github.com/rook/rook/blob/release-1.6/cluster/examples/kubernetes/ceph/object.yaml) does not use secure port

**Temporary fix:**

1. Manually patch object storage crd: `kubectl edit crd cephobjectstores.ceph.rook.io`
2. Add `nullable: true` to the problematic fields

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): `v1.6.1`

**Comment by travisn** [comment]
@poul1x Are you seeing this in a fresh v1.6.1 cluster, or this cluster was upgraded? Can you share the object_storage.yaml where you hit this issue?

**Comment by poul1x** [comment]
> Are you seeing this in a fresh v1.6.1 cluster, or this cluster was upgraded?

Fresh cluster. 

> Can you share the object_storage.yaml 

You can use default: https://github.com/rook/rook/blob/release-1.6/cluster/examples/kubernetes/ceph/object.yaml
It will fail with error:
```
The CephObjectStore XXX is invalid:
* spec.gateway.sslCertificateRef: Invalid value: "null": spec.gateway.sslCertificateRef in body must be of type string: "null"
* spec.gateway.securePort: Invalid value: "null": spec.gateway.securePort in body must be of type integer: "null"
```

I inspected object storage CRD and found that these fields are mandatory. 
So, I patched them [here](https://github.com/rook/rook/blob/release-1.6/cluster/examples/kubernetes/ceph/crds.yaml#L6040) and [here](https://github.com/rook/rook/blob/release-1.6/cluster/examples/kubernetes/ceph/crds.yaml#L6024) (set `nullable=true`).

**Comment by travisn** [comment]
@poul1x We could add nullable to those fields, but I'm wondering why I can't repro that error. There have been similar issues for other settings, but only observed during upgrades.
