### ISSUE TITLE
Connect to External RGW Using SSL?

### ISSUE THREAD

**Issue by cpmoore** [rook/rook#7804]
This is really just a question, but i wasn't sure where else to ask.
We're in the process of implementing OpenShift Container Storage in our OpenShift cluster.  Having some issues connecting to the external RGW endpoint for object bucket provisioning using ssl.

If securePort is configured in the rook operator, does that mean it will connect to the external rgw endpoint using ssl as well? 
Couldn't find any documentation regarding this anywhere.

**Comment by leseb** [comment]
> This is really just a question, but i wasn't sure where else to ask.
> We're in the process of implementing OpenShift Container Storage in our OpenShift cluster. Having some issues connecting to the external RGW endpoint for object bucket provisioning using ssl.
> 
> If securePort is configured in the rook operator, does that mean it will connect to the external rgw endpoint using ssl as well?

If `securePort` is configured, the rgw process will listen on TLS (port 443). Does that answer your question?

> Couldn't find any documentation regarding this anywhere.

@thotz FYI

**Comment by cpmoore** [comment]
I saw that note in the documentation regarding the rook process itself but my question was what port/protocol is used to connect to the external object storage listed in the `externalRgwEndpoints` section?

**Comment by thotz** [comment]
The rook v1.6 has a lot of SSL fixes for connecting with RGW, but honestly, I didn't test it on the ceph external cluster. As per [documentation](https://rook.io/docs/rook/v1.6/ceph-object-store-crd.html#gateway-settings) u need to provide `securePort` and `sslSecretRef` secret which contains certs and intermediate cafiles(I guess for external cluster only cafile might be required)  need to be passed. Bucketchecker, OBC provisioning, liveness probe will refer the secret while sending requests to SSL enabled RGW. 
Please note OpenShift provides `service serving cert` features that automatically set up SSL certs for your service and RGW support this feature but it won't work with external ceph cluster

**Comment by thotz** [comment]
@cpmoore : Let me know if u face any issue while connecting to the external endpoint via RGW

**Comment by thotz** [comment]
@cpmoore: I was able to connect with SSL enabled RGW server in an external ceph cluster and the creation of OBC was also successful.
You need to authenticate the rgw-service running on k8s with CA with RGW for this need to work
after that u can pass `securePort` and `sslSecretRef` points to secret containing private.key, client.cert and cacert
