### ISSUE TITLE
MGR and MDS daemons not bound to multus interface address

### ISSUE THREAD

**Issue by mazocode** [rook/rook#7808]
**Deviation from expected behavior:**

The ceph-mgr and ceph-mds daemons are using the POD network instead of the specified multus interface. 

**Expected behavior:**

Both daemons should advertise with the multus interface address in case a multus network was specified.

**How to reproduce it (minimal and precise):**

Check the ceph-mgr and ceph-mds deployment. The value of --public-addr is set to $(ROOK_POD_IP).

**Use-case**

With multus we can specify a dedicated storage network. Reasons for using multus with rook might be

- Using a dedicated high performance / isolated network
- Accessing ceph from outside the cluster without routing the POD network (especially from another cluster with rook, using the external: true)

 **Workaround**

Here is my current workaround which works well for accessing the cluster from another cluster with rook (external:true) using a dedicated storage network shared between the clusters.

a) Wrapper for ceph-mgr which adds --public-addr with the interface address of net1

```
kubectl -n rook-ceph apply -f - <<EOS
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-mgr-wrapper
data:
  ceph-mgr.sh: |
    #!/bin/sh
    set -euo pipefail
    exec ceph-mgr \$* --public-addr=\$(ip -o -4 addr show dev net1 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
EOS
```

b) Wrapper for ceph-mds which adds --public-addr with the interface address of net1

```
kubectl -n rook-ceph apply -f - <<EOS
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-mds-wrapper
data:
  ceph-mds.sh: |
    #!/bin/sh
    set -euo pipefail
    exec ceph-mds \$* --public-addr=\$(ip -o -4 addr show dev net1 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
EOS
```

c) Patch for the mgr daemon deplyoment to use the wrapper

```
if [ "$(kubectl get -n rook-ceph deployment/rook-ceph-mgr-a -o jsonpath='{.spec.template.spec.containers[0].command[0]}')" != "/wrapper/ceph-mgr.sh" ]; then
    kubectl patch -n rook-ceph deployment/rook-ceph-mgr-a --type=json -p '
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value: { "name": "ceph-mgr-wrapper", "mountPath": "/wrapper" }
- op: add
  path: /spec/template/spec/volumes/-
  value: { "name": "ceph-mgr-wrapper", "configMap": { "name": "ceph-mgr-wrapper", "defaultMode": 0744 } }
- op: replace
  path: /spec/template/spec/containers/0/command/0
  value: "/wrapper/ceph-mgr.sh"
'
fi
```

d) Patch for all mds deployments to use the wrapper

```
for deployment in $(kubectl -n rook-ceph get deployment --selector=app=rook-ceph-mds -o jsonpath='{.items[*].metadata.name}'); do
	if [ "$(kubectl get -n rook-ceph deployment/$deployment -o jsonpath='{.spec.template.spec.containers[0].command[0]}')" != "/wrapper/ceph-mds.sh" ]; then
kubectl patch -n rook-ceph deployment/$deployment --type=json -p '
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value: { "name": "ceph-mds-wrapper", "mountPath": "/wrapper" }
- op: add
  path: /spec/template/spec/volumes/-
  value: { "name": "ceph-mds-wrapper", "configMap": { "name": "ceph-mds-wrapper", "defaultMode": 0744 } }
- op: replace
  path: /spec/template/spec/containers/0/command/0
  value: "/wrapper/ceph-mds.sh"
'
	fi
done
```

This needs to run whenever a new CephFilesystem was created.

**Related Issues**

https://github.com/rook/rook/issues/7563
https://github.com/rook/rook/issues/7550

**Environment**:

* Rook version (use `rook version` inside of a Rook Pod): 1.6.1
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.1
* Kubernetes version (use `kubectl version`): v1.20.2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@rohan47 We need this multus config, right?
