### ISSUE TITLE
Can Rook operator monitor all namespaces pvc creation.

### ISSUE THREAD

**Issue by citywander** [rook/rook#782]
I run rook operator in "default" namespace and create MariaDB in resource namespace. I found bind pvc error.
Whether I have to install operator in each namespace? Or some configuration to make operator monitor all namespaces?

**Comment by travisn** [comment]
@citywander i believe you're hitting #475. Can check if copying the secret to your namespace fixes the issue?

**Comment by citywander** [comment]
Yes, thanks.

2017-07-04 5:45 GMT-07:00 Travis Nielsen <notifications@github.com>:

**Comment by bassam** [comment]
duplicate of #475. tracking there.
