### ISSUE TITLE
No Metrics on OKD

### ISSUE THREAD

**Issue by thomaswoeckinger** [rook/rook#7827]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
No metrics found by prometheus. No cursor with name ceph_* available.

**Expected behavior:**
Metrics with name ceph_* available in prometheus.

**How to reproduce it (minimal and precise):**

Fresh setup of rook-ceph 1.6.1 (montoring in cluster.yaml is enabled) on OKD 4.7.

**Environment**:
* OS (e.g. from /etc/os-release):
FCOS 33
* Kernel (e.g. `uname -a`):
5.10.19-200.fc33.x86_64 #1 SMP Fri Feb 26 16:21:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.6.1 go: go1.16.3
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)
* Kubernetes version (use `kubectl version`):
Client Version: 4.7.0-0.okd-2021-03-28-152009
Server Version: 4.7.0-0.okd-2021-03-21-094146
Kubernetes Version: v1.20.0-1054+bafe72fb05eddc-dirty
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
OKD
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_OK

**Comment by thomaswoeckinger** [comment]
Forgot to mention that https://github.com/rook/rook/raw/release-1.6/cluster/examples/kubernetes/ceph/monitoring/rbac.yaml was applied before cluster creation

**Comment by thomaswoeckinger** [comment]
After enabling user defined project monitoring i had to delete and recreate the service monitor as found by https://github.com/rook/rook/raw/release-1.6/cluster/examples/kubernetes/ceph/monitoring/service-monitor.yaml.

I would suggest an OKD section in monitoring.md to describe the differences.

**Comment by travisn** [comment]
@thomaswoeckinger So there is an ordering issue when creating the service monitor for OKD? Want to provide the text that would help for OKD?

**Comment by thomaswoeckinger** [comment]
> @thomaswoeckinger So there is an ordering issue when creating the service monitor for OKD? Want to provide the text that would help for OKD?

For sure, should i create a PR containing the changes for monitoring.md and assign it to @travisn ?

**Comment by travisn** [comment]
> > @thomaswoeckinger So there is an ordering issue when creating the service monitor for OKD? Want to provide the text that would help for OKD?
> 
> For sure, should i create a PR containing the changes for monitoring.md and assign it to @travisn ?

Sounds good if you open the PR, then we will review it. No need to assign it, several maintainers are actively reviewing PRs.
