### ISSUE TITLE
How to Recover OSD data on Rook-Ceph in Kubernetes Cluster

### ISSUE THREAD

**Issue by anish-gupta1811** [rook/rook#7830]
**Is this a bug report or feature request?**

* Bug Report
Our master nodes went down to "NotReady" state and thus all application pods and rook-ceph pods went to Terminating state. 

Now after kubelet and docker service restart on both master nodes - our rook-ceph Pods are not Running but going either in Pending State or ContainerCreating or Terminating.

Need to make sure we haven't lost our OSD data or applications data.

**Bug Report**

**Expected behavior:**
Pods should have come up and running automatically once Nodes were back up.

**Deviation from expected behavior:**

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

```
[root@kubemaster1 ~]# kubectl get pods -n rook-ceph -o wide
NAME                                                    READY   STATUS              RESTARTS   AGE     IP             NODE          NOMINATED NODE   READINESS GATES
csi-cephfsplugin-c5zbx                                  0/3     Terminating         0          2d11h   10.10.73.52    kubemaster3   <none>           <none>
csi-cephfsplugin-provisioner-674847b584-c9hkq           0/5     Terminating         7          2d11h   <none>         kubemaster3   <none>           <none>
csi-cephfsplugin-provisioner-674847b584-vtbl9           0/5     Terminating         10         2d11h   <none>         kubemaster3   <none>           <none>
csi-cephfsplugin-rtbs6                                  0/3     Terminating         0          47d     10.10.73.50    kubemaster1   <none>           <none>
csi-cephfsplugin-vtt6r                                  3/3     Terminating         0          47d     10.10.73.51    kubemaster2   <none>           <none>
csi-rbdplugin-7b6kv                                     0/3     Terminating         0          2d11h   10.10.73.52    kubemaster3   <none>           <none>
csi-rbdplugin-djqst                                     0/3     Terminating         0          47d     10.10.73.50    kubemaster1   <none>           <none>
csi-rbdplugin-dzsbg                                     3/3     Terminating         0          47d     10.10.73.51    kubemaster2   <none>           <none>
csi-rbdplugin-provisioner-5777f9cf96-6snvk              0/6     Terminating         0          2d11h   <none>         kubemaster3   <none>           <none>
csi-rbdplugin-provisioner-5777f9cf96-h6mcf              0/6     Terminating         6          2d11h   <none>         kubemaster3   <none>           <none>
rook-ceph-crashcollector-kubemaster1-6f88957848-pvc9z   1/1     Running             0          2d12h   10.217.0.179   kubemaster1   <none>           <none>
rook-ceph-crashcollector-kubemaster2-646dcf7487-74q4v   0/1     Pending             0          21d     <none>         <none>        <none>           <none>
rook-ceph-crashcollector-kubemaster3-86954d8678-pmnbn   1/1     Running             0          27h     10.217.2.178   kubemaster3   <none>           <none>
rook-ceph-csi-detect-version-hgqbf                      0/1     Init:0/1            0          26h     <none>         kubemaster1   <none>           <none>
rook-ceph-detect-version-j9fhf                          0/1     Init:0/1            0          11m     <none>         kubemaster1   <none>           <none>
rook-ceph-mds-rookcephfs-a-66479b6bd8-29855             0/1     Pending             0          25h     <none>         <none>        <none>           <none>
rook-ceph-mds-rookcephfs-a-66479b6bd8-tz94n             0/1     Terminating         27         2d12h   10.217.0.180   kubemaster1   <none>           <none>
rook-ceph-mds-rookcephfs-b-6bd5dd944-9v8sm              0/1     Init:0/1            0          27h     <none>         kubemaster3   <none>           <none>
rook-ceph-mgr-a-6455c8d5cf-z5k2q                        0/1     Init:1/3            31         27h     10.217.0.187   kubemaster1   <none>           <none>
rook-ceph-mon-a-7f8dbf9c9c-jvkbl                        0/1     Init:0/2            0          27h     <none>         kubemaster3   <none>           <none>
rook-ceph-mon-b-f7b8c95bb-jqxkm                         0/1     Pending             0          21d     <none>         <none>        <none>           <none>
rook-ceph-mon-c-6f5d4fcd49-nd4bj                        1/1     Running             0          2d12h   10.217.0.181   kubemaster1   <none>           <none>
rook-ceph-operator-897c87dd6-dc7kg                      1/1     Running             1          2d10h   10.217.0.178   kubemaster1   <none>           <none>
rook-ceph-osd-0-7dff7758cb-gg88n                        0/1     Init:0/2            0          24h     <none>         kubemaster1   <none>           <none>
rook-ceph-osd-0-7dff7758cb-n78r9                        0/1     Terminating         37         2d12h   <none>         kubemaster1   <none>           <none>
rook-ceph-osd-1-6df95d874d-6t8jf                        0/1     CrashLoopBackOff    505        27h     10.217.2.177   kubemaster3   <none>           <none>
rook-ceph-osd-2-f89f86b59-bm7sp                         0/1     Pending             0          21d     <none>         <none>        <none>           <none>
rook-ceph-tools-7f96779fb9-8n5m2                        1/1     Running             0          27h     10.217.0.220   kubemaster1   <none>           <none>
rook-discover-444x5                                     0/1     Terminating         0          47d     <none>         kubemaster1   <none>           <none>
rook-discover-bh5j9                                     0/1     ContainerCreating   0          26h     <none>         kubemaster3   <none>           <none>
rook-discover-bnvtx                                     0/1     ContainerCreating   0          26h     <none>         kubemaster1   <none>           <none>
rook-discover-fcstx                                     1/1     Terminating         0          47d     10.217.1.215   kubemaster2   <none>           <none>
rook-discover-hpm8r                                     0/1     Terminating         0          2d11h   <none>         kubemaster3   <none>           <none>
[root@kubemaster1 ~]# 

```

`rook-ceph-osd-1-6df95d874d-6t8jf                        1/1     Running             507        27h     10.217.2.177   kubemaster3   <none>           <none>
`
This OSD is running but

`[root@kubemaster3 ~]# cd /var/lib/ceph
-bash: cd: /var/lib/ceph: No such file or directory
[root@kubemaster3 ~]# 

`

`kubectl describe pod rook-ceph-osd-0-7dff7758cb-gg88n -n rook-ceph`

`QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/hostname=kubemaster1
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                   From                  Message
  ----     ------       ----                  ----                  -------
  Warning  FailedMount  42m (x91 over 24h)    kubelet, kubemaster1  Unable to attach or mount volumes: unmounted volumes=[rook-ceph-log rook-ceph-crash run-udev activate-osd devices rook-config-override rook-ceph-osd-token-z57dj rook-data], unattached volumes=[rook-ceph-log rook-ceph-crash run-udev activate-osd devices rook-config-override rook-ceph-osd-token-z57dj rook-data]: timed out waiting for the condition
  Warning  FailedMount  21m (x88 over 24h)    kubelet, kubemaster1  Unable to attach or mount volumes: unmounted volumes=[activate-osd devices rook-config-override rook-ceph-osd-token-z57dj rook-data rook-ceph-log rook-ceph-crash run-udev], unattached volumes=[activate-osd devices rook-config-override rook-ceph-osd-token-z57dj rook-data rook-ceph-log rook-ceph-crash run-udev]: timed out waiting for the condition
  Warning  FailedMount  17m (x74 over 24h)    kubelet, kubemaster1  Unable to attach or mount volumes: unmounted volumes=[rook-config-override rook-ceph-osd-token-z57dj rook-data rook-ceph-log rook-ceph-crash run-udev activate-osd devices], unattached volumes=[rook-config-override rook-ceph-osd-token-z57dj rook-data rook-ceph-log rook-ceph-crash run-udev activate-osd devices]: timed out waiting for the condition
  Warning  FailedMount  12m (x81 over 24h)    kubelet, kubemaster1  Unable to attach or mount volumes: unmounted volumes=[rook-data rook-ceph-log rook-ceph-crash run-udev activate-osd devices rook-config-override rook-ceph-osd-token-z57dj], unattached volumes=[rook-data rook-ceph-log rook-ceph-crash run-udev activate-osd devices rook-config-override rook-ceph-osd-token-z57dj]: timed out waiting for the condition
  Warning  FailedMount  5m56s (x76 over 24h)  kubelet, kubemaster1  Unable to attach or mount volumes: unmounted volumes=[devices rook-config-override rook-ceph-osd-token-z57dj rook-data rook-ceph-log rook-ceph-crash run-udev activate-osd], unattached volumes=[devices rook-config-override rook-ceph-osd-token-z57dj rook-data rook-ceph-log rook-ceph-crash run-udev activate-osd]: timed out waiting for the condition
  Warning  FailedMount  84s (x75 over 23h)    kubelet, kubemaster1  Unable to attach or mount volumes: unmounted volumes=[rook-ceph-osd-token-z57dj rook-data rook-ceph-log rook-ceph-crash run-udev activate-osd devices rook-config-override], unattached volumes=[rook-ceph-osd-token-z57dj rook-data rook-ceph-log rook-ceph-crash run-udev activate-osd devices rook-config-override]: timed out waiting for the condition
[root@kubemaster3 ~]# 
`

`[root@kubemaster1 ~]# kubectl -n rook-ceph exec -it $(kubectl -n rook-ceph get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}') bash
bash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory
[root@rook-ceph-tools-7f96779fb9-8n5m2 /]# rook version
rook: v1.3.0-beta.0.173.g10d5631
go: go1.13.8
[root@rook-ceph-tools-7f96779fb9-8n5m2 /]# ceph -v 
ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
[root@rook-ceph-tools-7f96779fb9-8n5m2 /]# ceph status
`
**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.3.0-beta.0.173.g10d5631
go: go1.13.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)

* Kubernetes version (use `kubectl version`): v1.17.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): ceph status or ceph health - get stuck - no response.

**Comment by travisn** [comment]
Did the rest of the K8s cluster recover after the masters came back online? It's expected that the rook pods would all start back up after a total outage, and the mons and osds would find the same data since those pods are tied to their local disks (assuming you are using the cluster.yaml example, or if using the cluster-on-pvc.yaml example they would find their PVs).

What does the operator log show? Likely that the mons are not in quorum. It appears two of the mon pods are not running, so perhaps try resolve their issues first.

As a last resort, also see the [disaster recovery guide](https://rook.github.io/docs/rook/v1.6/ceph-disaster-recovery.html).
