### ISSUE TITLE
CronJob needs to be updated from v1beta1 to v1

### ISSUE THREAD

**Issue by travisn** [rook/rook#7837]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In K8s 1.21, the operator log shows the following warning:
```
W0505 23:52:56.480392       9 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

The crash collector cron job needs to be updated to v1 on K8s 1.21 and newer.

**Expected behavior:**
No warnings in the log about cron job v1beta1 being deprecated.

**How to reproduce it (minimal and precise):**

Install on K8s 1.21 and look at the operator log

**Comment by subhamkrai** [comment]
we also see this 
```
W0513 04:16:46.857358       9 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
``` 
in the log...will create a new issue

**Comment by subhamkrai** [comment]
> we also see this
> 
> ```
> W0513 04:16:46.857358       9 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
> ```
> 
> in the log...will create a new issue

#7941

**Comment by travisn** [comment]
To accommodate the v1 or v1beta1 versions of the CronJob, we likely need the following approach:
- Check the K8s version
- If less than 1.21, use the package `k8s.io/api/batch/v1beta1`
- Else use the package `k8s.io/api/batch/v1`

This may mean some (hopefully minimally) duplicated code to initialize the structs of the different versions.

The alternative is to use yaml templates similar to how we load the csi driver from yaml, while replacing variables. In the long term, this approach would help us be more independent from the version changes and may be more maintainable, but in the short term would be a bigger change.
