### ISSUE TITLE
Rook should reflect on Kubernetes 1.8 api changes

### ISSUE THREAD

**Issue by kokhang** [rook/rook#784]
There are a lot of moving parts in Kubernetes and we need Rook to reflect these changes.
These include but not limited to:

- kubernetes/client-go
- kubernetes/apimachinery
- kubernetes/api
- kubernetes/pkg/kubelet/apis

**Comment by travisn** [comment]
@kokhang while I assume we need the 1.8 apis to communicate with the volume plugin, how compatible is the 1.8 api with 1.6 and 1.7? Besides the test matrix hopefully it is not too much effort to support multiple versions of K8s.

**Comment by kokhang** [comment]
@travisn good question. We use client-go as binding to talk to k8s and client-go is backward compatible with previous version of kubernetes. Up to 4.

What i am worried about (and we have to test it) is communicating with the TPR API. Since TPR was alpha, backward compatibility is not guarantee.
