### ISSUE TITLE
Plan ingress controller behavior (for NFS and/or RGW)

### ISSUE THREAD

**Issue by liewegas** [rook/rook#7845]
Currently the ceph orchestrator abstractions for RGW and NFS deploy the backend services (radosgw zone or ganesha daemon(s)).  A new orchestrator ``ingress`` service abstracts an HA front-end.  In the case of cephadm, that is a combination of haproxy and keepalived.  In the case of kubernetes, this will presumably map to an ingress controller to provide HA, load-balanced access to the service to clients outside of kubernetes.

In order to make sure we get the orchestrator abstraction right, we need to understand a bit about how kubernetes ingress works.

- How are IPs assigned?  Presumably that depends on the environment and controller.
- Are there some controllers where you explicitly provide an IP, or are they always dynamically assigned?
- When they are dynamic, is the result an IP that you would query the k8s for after creating ingress, or is it sometimes a DNS name?  (And if it's a DNS name, does that mean that name might change to map to a different IP later or something?)
- Are there other (optional) fields we should collect on the orchestrator side to pass to the kubernetes ingress controller?  (In the case of cephadm, we have a ``virtual_ip`` property (IP + CIDR mask, e.g. ``192.168.0.10/24``) that is required.)

**Comment by richardelling** [comment]
There are many ways to do this. I can share what we normally do.
1. use MetalLB load balancer
2. in Layer2 mode https://metallb.universe.tf/concepts/layer2/
3. IP addresses are manually assigned when we create the ingress

There are various constraints to understand wrt how the internal cluster proxy works, but it can be done.

**Comment by travisn** [comment]
@liewegas Is the question ultimately how Rook can be aware of the RGW or NFS endpoint so it can orchestrate those services? I'm thinking Rook would require that a `virtualIP` property be specified in the CephObjectStore or CephNFS CRs. The admin would have to create the ingress first, then configure the object store or nfs with those IPs. 

Rook is largely unaware of the routing configuration external or even internal to the cluster. Besides the IPs and perhaps DNS names used by clients, not sure what other configuration would need to be discovered.

@richardelling Thanks for the example of using MetalLB, makes a lot of sense to me!

**Comment by liewegas** [comment]
> @liewegas Is the question ultimately how Rook can be aware of the RGW or NFS endpoint so it can orchestrate those services? I'm thinking Rook would require that a `virtualIP` property be specified in the CephObjectStore or CephNFS CRs. The admin would have to create the ingress first, then configure the object store or nfs with those IPs.
> 
> Rook is largely unaware of the routing configuration external or even internal to the cluster. Besides the IPs and perhaps DNS names used by clients, not sure what other configuration would need to be discovered.

I have no opinion about whether rook should be involved.  I think the ``mgr/rook`` module needs to be aware, though, so that it can set this up for the user.  That is the current plan, at least; if it turns out there are 100 different ingress options to worry about (and none that are more common than others) then perhaps this is a bust.  I'm guessing there are just a handful of common controllers, though!

**Comment by travisn** [comment]
I assume AWS, GCE, and nginx are the most common according to [this doc](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/), but the list of possible controllers is certainly long. For upstream, though I wonder how much we can generalize it. There are many K8s configurations out there. To get focus, it almost feels like we need downstream scenarios to drive what happens in the rook mgr module.

**Comment by richardelling** [comment]
A `virtualIP` might be better as an EndPoint or EndPointSlice reference
