### ISSUE TITLE
ceph mgr attempts to bind to the wrong pod IP for prometheus+dashboard

### ISSUE THREAD

**Issue by SleepingShell** [rook/rook#7854]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:** The rook-ceph-mgr cannot start the prometheus or dashboard endpoints, as they are attempting to bind to a different IP address than what the pod is currently running as.

**Expected behavior:** Bind to the correct pod IP

**How to reproduce it (minimal and precise):** Not sure how this situation happened. I had to resolve an unrelated issue with non-existent snapshots preventing the deleting of blocks. @travisn and I were troubleshooting my rook-ceph-mgr constantly restarting and it was due to to the livenessProbe failing. This probe is failing because of this issue.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

The Pod IP is **NOT** 10.0.0.3 . I believe this *used* to be the mgr IP until the deployment spun up a new pod.
```
debug 2021-05-03T19:36:53.550+0000 7f3a01938200  1 mgr[py] Loading python module 'status'
debug 2021-05-03T19:36:53.713+0000 7f3a01938200  1 mgr[py] Loading python module 'telegraf'
debug 2021-05-03T19:36:53.817+0000 7f3a01938200  1 mgr[py] Loading python module 'telemetry'
debug 2021-05-03T19:36:54.537+0000 7f3a01938200  1 mgr[py] Loading python module 'test_orchestrator'
debug 2021-05-03T19:36:54.837+0000 7f3a01938200  1 mgr[py] Loading python module 'volumes'
debug 2021-05-03T19:36:55.237+0000 7f3a01938200  1 mgr[py] Loading python module 'zabbix'
debug 2021-05-03T19:36:55.413+0000 7f39eebad700  0 ms_deliver_dispatch: unhandled message 0x5600e71186e0 mon_map magic: 0 v1 from mon.1 v2:10.43.254.127:3300/0
debug 2021-05-03T19:36:55.487+0000 7f39eebad700  1 mgr handle_mgr_map Activating!
debug 2021-05-03T19:36:55.487+0000 7f39eebad700  1 mgr handle_mgr_map I am now activating
debug 2021-05-03T19:36:55.510+0000 7f39a1614700  0 [balancer DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.510+0000 7f39a1614700  1 mgr load Constructed class from module: balancer
debug 2021-05-03T19:36:55.510+0000 7f39a1614700  0 [crash DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.510+0000 7f39a1614700  1 mgr load Constructed class from module: crash
debug 2021-05-03T19:36:55.513+0000 7f39a1614700  0 [devicehealth DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.513+0000 7f39a1614700  1 mgr load Constructed class from module: devicehealth
debug 2021-05-03T19:36:55.517+0000 7f39a1614700  0 [iostat DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.517+0000 7f39a1614700  1 mgr load Constructed class from module: iostat
debug 2021-05-03T19:36:55.517+0000 7f39a1614700  0 [orchestrator DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.517+0000 7f39a1614700  1 mgr load Constructed class from module: orchestrator
debug 2021-05-03T19:36:55.517+0000 7f39a1614700  0 [pg_autoscaler DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.517+0000 7f39a1614700  1 mgr load Constructed class from module: pg_autoscaler
debug 2021-05-03T19:36:55.523+0000 7f39a1614700  0 [progress DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.523+0000 7f39a1614700  1 mgr load Constructed class from module: progress
debug 2021-05-03T19:36:55.533+0000 7f39a1614700  0 [prometheus DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.533+0000 7f39a1614700  1 mgr load Constructed class from module: prometheus
debug 2021-05-03T19:36:55.540+0000 7f39a1614700  0 [rbd_support DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
[03/May/2021:19:36:55] ENGINE Bus STARTING
debug 2021-05-03T19:36:55.650+0000 7f39a1614700  1 mgr load Constructed class from module: rbd_support
debug 2021-05-03T19:36:55.650+0000 7f39a1614700  0 [restful DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.650+0000 7f39a1614700  1 mgr load Constructed class from module: restful
debug 2021-05-03T19:36:55.653+0000 7f39a1614700  0 [status DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.653+0000 7f39a1614700  1 mgr load Constructed class from module: status
debug 2021-05-03T19:36:55.653+0000 7f39a1614700  0 [telemetry DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.653+0000 7f39a1614700  1 mgr load Constructed class from module: telemetry
debug 2021-05-03T19:36:55.653+0000 7f39c7fcd700  0 [restful WARNING root] server not running: no certificate configured
debug 2021-05-03T19:36:55.657+0000 7f39a1614700  0 [volumes DEBUG root] setting log level based on debug_mgr: WARNING (1/5)
debug 2021-05-03T19:36:55.693+0000 7f39a1614700  1 mgr load Constructed class from module: volumes
debug 2021-05-03T19:36:55.697+0000 7f39c1fc1700 -1 client.0 error registering admin socket command: (17) File exists
debug 2021-05-03T19:36:55.697+0000 7f39c1fc1700 -1 client.0 error registering admin socket command: (17) File exists
debug 2021-05-03T19:36:55.697+0000 7f39c1fc1700 -1 client.0 error registering admin socket command: (17) File exists
debug 2021-05-03T19:36:55.697+0000 7f39c1fc1700 -1 client.0 error registering admin socket command: (17) File exists
debug 2021-05-03T19:36:55.697+0000 7f39c1fc1700 -1 client.0 error registering admin socket command: (17) File exists
CherryPy Checker:
The Application mounted at '' has an empty config.
[03/May/2021:19:36:55] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 225, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1836, in start
    self.prepare()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1791, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)
[03/May/2021:19:36:55] ENGINE Bus STOPPING
[03/May/2021:19:36:55] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('10.0.0.3', 9283)) already shut down
[03/May/2021:19:36:55] ENGINE Bus STOPPED
[03/May/2021:19:36:55] ENGINE Bus EXITING
debug 2021-05-03T19:36:55.720+0000 7f39b8faf700  0 [prometheus ERROR cherrypy.error] [03/May/2021:19:36:55] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 225, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1836, in start
    self.prepare()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1791, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)
[03/May/2021:19:36:55] ENGINE Bus EXITED
Exception in thread HTTPServer Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 225, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1836, in start
    self.prepare()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1791, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)
[03/May/2021:19:36:55] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f39d86db9e8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 184, in start
    self.wait()
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 246, in wait
    raise self.interrupt
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 225, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1836, in start
    self.prepare()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1791, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)
debug 2021-05-03T19:36:55.820+0000 7f39cf81c700  0 [prometheus ERROR cherrypy.error] [03/May/2021:19:36:55] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f39d86db9e8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpserver.py", line 180, in start
    super(Server, self).start()
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 184, in start
    self.wait()
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 246, in wait
    raise self.interrupt
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/process/servers.py", line 225, in _start_http_thread
    self.httpserver.start()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1836, in start
    self.prepare()
  File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1791, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)
[03/May/2021:19:36:55] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OSError("No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)",)
debug 2021-05-03T19:36:55.820+0000 7f39cf81c700  0 [prometheus ERROR cherrypy.error] [03/May/2021:19:36:55] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OSError("No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)",)
[03/May/2021:19:36:55] ENGINE Bus STOPPING
[03/May/2021:19:36:55] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('10.0.0.3', 9283)) already shut down
[03/May/2021:19:36:55] ENGINE Bus STOPPED
[03/May/2021:19:36:55] ENGINE Bus EXITING
[03/May/2021:19:36:55] ENGINE Bus EXITED
debug 2021-05-03T19:36:55.820+0000 7f39cf81c700 -1 log_channel(cluster) log [ERR] : Unhandled exception from module 'prometheus' while running on mgr.a: OSError("No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)",)
debug 2021-05-03T19:36:55.820+0000 7f39cf81c700 -1 prometheus.serve:
debug 2021-05-03T19:36:55.820+0000 7f39cf81c700 -1 Traceback (most recent call last):
  File "/usr/share/ceph/mgr/prometheus/module.py", line 1280, in serve
    cherrypy.engine.start()
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 283, in start
    raise e_info
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/usr/lib/python3.6/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OSError("No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)",)
```

**Environment**: RKE, Rook installed from Helm
* OS (e.g. from /etc/os-release): Arch Linux
* Kernel (e.g. `uname -a`): 5.10.10
* Cloud provider or hardware configuration: bare metal
* Rook version (use `rook version` inside of a Rook Pod):  v1.6.0
* Storage backend version (e.g. for ceph do `ceph -v`):  v15.2.11
* Kubernetes version (use `kubectl version`): v1.19.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare Metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_ERR, ``Module 'prometheus' has failed: OSError("No socket could be created -- (('10.0.0.3', 9283): [Errno 99] Cannot assign requested address)",)``

Additionally, for some reason the tools pod reports the wrong rook and ceph version

**Comment by SleepingShell** [comment]
> @SleepingShell Was this an upgraded cluster? Now I'm remembering that a few releases ago we used to set a ceph config option to which the mgr would be bound. Do you see these settings? If they are anything besides `0.0.0.0` try clearing them out.
> 
> ```
> ceph config get mgr.a mgr/dashboard/server_addr
> ceph config get mgr.a mgr/prometheus/server_addr
> ```

the dashboard addr returns as 0.0.0.0, the prometheus address returns blank

**Comment by aasraoui** [comment]
i'm having issues accessing the dashaboard, this might be similar, prometheus is returning blank and  dashboard  has ::                                                                                                                                                                [root@rook-ceph-tools-664b7555b8-jndss /]# ceph config get mgr.a mgr/prometheus/server_addr

[root@rook-ceph-tools-664b7555b8-jndss /]# ceph config get mgr.a mgr/dashboard/server_addr
::
[root@rook-ceph-tools-664b7555b8-jndss /]#

**Comment by SleepingShell** [comment]
> i'm having issues accessing the dashaboard, this might be similar, prometheus is returning blank and dashboard has :: [root@rook-ceph-tools-664b7555b8-jndss /]# ceph config get mgr.a mgr/prometheus/server_addr
> 
> [root@rook-ceph-tools-664b7555b8-jndss /]# ceph config get mgr.a mgr/dashboard/server_addr
> ::
> [root@rook-ceph-tools-664b7555b8-jndss /]#

Have you confirmed this is the same issue? Have you checked your mgr logs?

**Comment by travisn** [comment]
@sebastian-philipp Why would the dashboard/prometheus modules be remembering an old ip address to bind to?

**Comment by sebastian-philipp** [comment]
I can't think of a way to do that other than setting `server_addr`. 

https://github.com/ceph/ceph/blob/731f4f70ee58a5df63e1a7f46540005d1e7206f8/src/pybind/mgr/dashboard/module.py#L104-L136

maybe you want to do a `ceph config dump | grep 10.0.0.3` to be on the safe side here.

**Comment by hyperbolic2346** [comment]
I've run into this same issue on an upgrade. I have an error with IP 10.1.88.2, but otherwise this is the same. I believe this was the correct address at one point. Checking the config as requested results in `''` and and empty string, but with dump I get the following:
```
$ ceph config dump | grep 10.1.88.2
    mgr.a        advanced  mgr/dashboard/a/server_addr   10.1.88.2  *
    mgr.a        advanced  mgr/prometheus/a/server_addr  10.1.88.2  *
```
Running `ceph config rm mgr.a mgr/prometheus/a/server_addr` and `ceph config rm mgr.a mgr/dashboard/a/server_addr` has solved this issue for me.

**Comment by epuertat** [comment]
@travisn: as @sebastian-philipp mentioned, if 'someone' set this `mgr/dashboard/a/server_addr` option in the past, it'll remain set. If unset, [this will be used instead](https://github.com/ceph/ceph/blob/731f4f70ee58a5df63e1a7f46540005d1e7206f8/src/pybind/mgr/mgr_util.py#L383-L399) for guessing the address to bind to.

**Comment by aasraoui** [comment]
I'm similar issue with ceph-mgr not starting after master node failover:  ceph -s
   cluster
    id:     057caxxx-xxxxx-xxxx-xxxx
    health: HEALTH_ERR
            2 MDSs report slow metadata IOs
            1 MDSs report slow requests
            no active mgr
            Module 'prometheus' has failed: OSError("No socket could be created -- (('10.x.x.254', 9283): [Errno 99] Cannot assign requested address)",)
            clock skew detected on mon.d, mon.e
            Reduced data availability: 97 pgs inactive
 services:
    mon: 3 daemons, quorum b,d,e (age 24h)
    mgr: no daemons active (since 3m)
    mds: myfs:1 {0=myfs-b=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 9d), 3 in (since 9d)

  data:
    pools:   4 pools, 97 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             97 unknown

**Comment by aasraoui** [comment]
ceph config get mgr.a mgr/dashboard/server_addr
::
ceph config get mgr.a mgr/prometheus/server_addr
10.x.x.254

**Comment by travisn** [comment]
@aasraoui Did you remove the server_addr settings as suggested in [this comment](https://github.com/rook/rook/issues/7854#issuecomment-851182049)?

**Comment by aasraoui** [comment]
@travisn thanks Travis for the quick reply here .. removing the server_addr seetings as in config rm mgr.a mgr/prometheus/a/server_addr and ceph config rm mgr.a mgr/dashboard/a/server_addr
does not resolve the problem ..

**Comment by travisn** [comment]
After you restart the mgr pod, what does the mgr log show? The same error with "cannot assign requested address" for the port binding?

**Comment by jmolmo** [comment]
The error:
`Module 'prometheus' has failed: OSError("No socket could be created -- (('10.x.x.254', 9283): [Errno 99] Cannot assign requested address)",`)
seems to point that the port is already used...  
 I will do the following:
in the ceph toolbox:
`# ceph mgr module disable prometheus` 

Check the cluster health, do we have a manager active?
No:  
Where is running the manager pod? Could it be that you have a couple of manager pods running in the same node? if that happens kill one of the pods.
what is the log of the manager pod? (there must be only one manager pod running in your cluster)

yes: 
enable again the prometheus manager module:
ceph mgr module enable prometheus
Everything ok? if no please attach the manager module log.

**Comment by aasraoui** [comment]
ceph mgr logs atached
[ceph-mgr-log.txt](https://github.com/rook/rook/files/7488209/ceph-mgr-log.txt)

**Comment by jmolmo** [comment]
```
cherrypy.process.wspbus.ChannelFailures: OSError("No socket could be created -- (('10.101.22.254', 9283): [Errno 99] Cannot assign reques
ted address)",)
```

@aasraoui : Everything points that another instance of the prometheus module .. or something is using the port 9283 in the node where the manager pod wants to start. Please diagnose following the procedure I suggested to you.

**Comment by aasraoui** [comment]
@jmolmo this problem won't go away, tried all the above cases..

**Comment by echel0n-TR** [comment]
This issue is still present in latest version of rook-ceph, tried everything above and nothing seems to resolve this, its as if something is using the port?

**Comment by epuertat** [comment]
Based on [this](https://github.com/torvalds/linux/blob/457391b0380335d5e9a5babdec90ac53928b23b4/include/uapi/asm-generic/errno.h#L81-L82), errno 99 seems to have nothing to do with some other process already bound to that address (which could be errno 98, `EADDRINUSE`). 
```h
#define	EADDRINUSE	98	/* Address already in use */
#define	EADDRNOTAVAIL	99	/* Cannot assign requested address */
```

Can you check if that address is actually available from within that pod?
