### ISSUE TITLE
Pushing to the master branch of a private fork results in triggering github actions

### ISSUE THREAD

**Issue by travisn** [rook/rook#7871]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When pushing to the master branch of my private fork I saw a github action report failure. This was confusing since I only expect them to be run on the `rook` fork.

![Screen Shot 2021-05-10 at 12 24 49 PM](https://user-images.githubusercontent.com/1048514/117706620-c4c85a80-b18a-11eb-9908-fa2a5fd5ec90.png)

**Expected behavior:**
Pushing to a private fork should not result in github actions being run. It's only expected that github actions run on the rook fork.

I would expect [this list](https://github.com/travisn/rook/actions/workflows/push-build.yaml?query=branch%3Amaster+event%3Apush) to be empty.

**How to reproduce it (minimal and precise):**

Push to the master branch of a private fork

**Comment by subhamkrai** [comment]
@travisn [this](https://github.com/subhamkrai/rook/commit/ead876a8ab344d344088d35a18bf0b9daba922dc) changes I did while testing in the forked repo. Make sure `DOCKER_REGISTRY ?=` this is changed to right docker hub ID and I see the action failed when trying to login in container registry make sure these are set```username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}```

**Comment by travisn** [comment]
@subhamkrai Not sure we need to change variables or secrets. We need to just disable this action on all forks except `rook`.

**Comment by leseb** [comment]
I think it's because your fork is even with rook/rook so it's expected. We could do this in Rook https://github.community/t/stop-github-actions-running-on-a-fork/17965/2 to avoid confusion.

**Comment by travisn** [comment]
To capture my thoughts from discussion, I still see that this action should not be executed on a private fork. Only official builds (master/release branches on the main `rook` fork) should even attempt to publish.

**Comment by travisn** [comment]
Reopening since we need to revert #7887 after causing builds to not be pushed for master either.
