### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [rook/rook#7881]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Hello,

In order to combat dockerhub's imposed rate limits it would be great to host these images on ghcr or quay.io. It would be great to also use this new alternative location in the helm charts

**What is use case behind this feature:**

Dockerhubs 100/6hr pull rate-limits

**Comment by leseb** [comment]
We can explore quay.io but GHCR does not seem to be an option for now since it will require a paid plan.

**Comment by onedr0p** [comment]
I'm using GHCR in a bunch of open source projects for free, what makes you think you'll need to pay for it?

**Comment by leseb** [comment]
Oh wait I actually misread the billing page, it seems to be free for all open source projects :). I guess we will look into that then 👍🏻 . Thanks!

**Comment by leseb** [comment]
@subhamkrai please investigate https://ghcr.io, it looks like multi-arch support is available so that's the main thing to support. Thanks.

**Comment by subhamkrai** [comment]
> @subhamkrai please investigate https://ghcr.io, it looks like multi-arch support is available so that's the main thing to support. Thanks.

@leseb I had quick look on multi-arch...and yes multi-arch is supported https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

**Comment by leseb** [comment]
> > @subhamkrai please investigate https://ghcr.io, it looks like multi-arch support is available so that's the main thing to support. Thanks.
> 
> @leseb I had quick look on multi-arch...and yes multi-arch is supported https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

Yes, thanks for confirming, let's go ahead with a small prototype. Also, let's see if we can migrate most of our images to GHRC too, that could be beneficial.

**Comment by onedr0p** [comment]
I can confirm that multi-arch is definitely supported, I also do multi-arch container builds with open source projects.

**Comment by travisn** [comment]
@onedr0p The rook repos actually are not expected to be rate limited since a few months back. Just to be clear, you're seeing the rate limiting on the rook image and/or ceph image?

@jbw976 Can you give more details on the rate limits that should not exist anymore? I don't see it tracked in an issue, but maybe I'm overlooking it.

**Comment by onedr0p** [comment]
> @onedr0p The rook repos actually are not expected to be rate limited since a few months back. Just to be clear, you're seeing the rate limiting on the rook image and/or ceph image?

I did not know rook was part of Dockerhubs "Open-source" program. They don't make it easy for people to see this information.

**Comment by leseb** [comment]
@onedr0p based on your initial comment I was really under the impression you were hitting a limit. Anyway, I think we can close this.

**Comment by onedr0p** [comment]
@leseb can you confirm rook is still part of this program? I do not see the `SPONSORED OSS` badge on rook.

e.g. compare https://hub.docker.com/u/nodered to https://hub.docker.com/u/rook

**Comment by travisn** [comment]
@onedr0p Are you seeing any rate limiting issues? I'm not sure about that badge, but I haven't heard of this issue anytime recently.

**Comment by onedr0p** [comment]
False alarm, dockerhub is so strange. I just ran a script to pull and delete rook 200 times off the same egress IP and there were no Sorry. Sorry for the ping.
