### ISSUE TITLE
Cant cleanly delete rook-ceph resources.

### ISSUE THREAD

**Issue by davesargrad** [rook/rook#7890]
My issue is exactly the issue that is documented [here](https://github.com/rook/rook/issues/2668), yet this has been closed.

I installed the lastest rook-ceph just 20 days ago. I had no problems installing. I used the [provided documentation](https://rook.io/docs/rook/v1.6/ceph-quickstart.html) and that worked quite well.

However I tried to follow up the [teardown steps](https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md) today, and I find that the teardown hangs.

The commands I used thus far are:
```
kubectl delete -n rook-ceph cephblockpool replicapool
kubectl delete storageclasses.storage.k8s.io rook-ceph-block
kubectl -n rook-ceph delete cephcluster rook-ceph
 
 
kubectl delete -f operator.yaml
kubectl delete -f common.yaml
kubectl delete -f crds.yaml
```

I deleted the replicapool, rook-ceph-block, and rook-ceph after i performed deletes on operator.yaml, common.yaml, crds.yaml. I didnt know I had to delete anything more because on instantiation I only had to instantiate crds.yaml, common.yaml, and operator.yaml. I didnt explicitly create any additional resources on top of this, nor did I indirectly add resources through the PVC/PV allocated to apps. The cluster did not yet have OSD nodes.

The replicapool, rook-ceph-block, and rook-ceph are all hanging on delete. I am not quite sure how to resolve cleanly. I dont just want to ctrl-c kubectl

The current documentation and process is simply not yet adequate. Teardown deserves as much attention by a development team as standup. A system that cant be torn down cleanly is problematic.

**Comment by Madhu-1** [comment]
Do you have any PVC created using rbd storageclass?

**Comment by davesargrad** [comment]
> Do you have any PVC created using rbd storageclass?

Thanks for your quick response.. No I dont.

**Comment by davesargrad** [comment]
The following two commands eliminated my problem
```
kubectl patch cephblockpools.ceph.rook.io replicapool -n rook-ceph -p '{"metadata":{"finalizers":[]}}' --type=merge
 
kubectl patch  cephclusters.ceph.rook.io rook-ceph -n rook-ceph -p '{"metadata":{"finalizers":[]}}' --type=merge

```

**Comment by davesargrad** [comment]
I'll close this issue. The documentation actually made it clear that order was critical. I did not properly follow this order.

**Comment by Nathan-Nesbitt** [comment]
> > The following two commands eliminated my problem
> > ```
> > kubectl patch cephblockpools.ceph.rook.io replicapool -n rook-ceph -p '{"metadata":{"finalizers":[]}}' --type=merge
> >  
> > kubectl patch  cephclusters.ceph.rook.io rook-ceph -n rook-ceph -p '{"metadata":{"finalizers":[]}}' --type=merge
> > ```
> 
> Get all the hanging resources
> 
> ```
> kubectl api-resources --verbs=list --namespaced -o name \
>   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n rook-ceph
> ```
> 
> This is how I also got rid of the following Stuck resources
> 
> ```
> ➜  rook-ceph git:(main) ✗ kubectl api-resources --verbs=list --namespaced -o name \
>   | xargs -n 1 kubectl get --show-kind --ignore-not-found -n rook-ceph
> NAME                                DATA   AGE
> configmap/rook-ceph-mon-endpoints   4      21d
> NAME                   TYPE                 DATA   AGE
> secret/rook-ceph-mon   kubernetes.io/rook   4      21d
> NAME                                          ACTIVEMDS   AGE   PHASE
> cephfilesystem.ceph.rook.io/ceph-filesystem   1           21d   Ready
> NAME                                            PHASE
> cephobjectstore.ceph.rook.io/ceph-objectstore   Failure
> ```
> 
> ```
> kubectl patch cephobjectstore.ceph.rook.io ceph-objectstore -n rook-ceph -p '{"metadata":{"finalizers":[]}}' --type=merge
> kubectl patch cephfilesystem.ceph.rook.io ceph-filesystem -n rook-ceph -p '{"metadata":{"finalizers":[]}}' --type=merge
> kubectl patch secret rook-ceph-mon -n rook-ceph -p '{"metadata":{"finalizers":[]}}' --type=merge
> kubectl patch configmap rook-ceph-mon-endpoints -n rook-ceph -p '{"metadata":{"finalizers":[]}}' --type=merge
> ```

If you've got a lot running on the node, you can limit the results with grep:

```
kubectl api-resources --verbs=list --namespaced -o name | grep "ceph" | xargs -n 1 kubectl get --show-kind --ignore-not-found -n rook-ceph
```
