### ISSUE TITLE
Tags are missing from master push

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#7903]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Since we started using GitHub action for master push tags are missing.
for example,
it is showing like this e06c36d it should have tag+sha-id something v1.6.2-12.gd60ee0d
 
**Expected behavior:**
tags should be added in the master push

**Comment by subhamkrai** [comment]
@travisn ^^

**Comment by travisn** [comment]
The tag should be set by [this line](https://github.com/rook/rook/blob/49b5adda7dd8c31e39906f01855b96afd2805965/build/makelib/common.mk#L74) in the makefile:
```
VERSION := $(shell git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2' )
```

I'd suggest adding some logging in the action to see what the output of `git describe` is from the job, or if `VERSION` is somehow being overridden.

**Comment by subhamkrai** [comment]
I did add a log
 ```
 git describe
fatal: No names found, cannot describe anything.
```
