### ISSUE TITLE
Rook does not deploy on k8s 1.5 anymore.

### ISSUE THREAD

**Issue by kokhang** [rook/rook#791]
This is a regression. I think it was introduced with https://github.com/rook/rook/pull/715.

Rook does no longer deploy on 1.5. The rook-operator just keeps on cycling.

Step to reproduce:
- Build rook from master
- Deploy rook on a kubernetes 1.5 cluster using these manifests. https://github.com/rook/rook/tree/master/demo/kubernetes/1.5

**Comment by luxas** [comment]
@kokhang What is the problem. We decided that Rook would promise compability for the latest k8s minor version. That is v0.3.0 => k8s v1.5, v0.4.0 => k8s v1.6, v0.5.0 => k8s v1.7

Rook supporting older versions than that is on a "best-effort" level.

HEAD not supporting v1.5 is even less of a problem -- not even official k8s policy supports v1.5 anymore, only v1.6 and v1.7.
When v1.8 is released, k8s support for v1.6 is dropped etc.

cc @bassam

**Comment by kokhang** [comment]
@luxas I think the issue is not real since Rook HEAD does work with minikube k8s 1.5 (1.5.3). I tried it with kubeadm using docker-in-docker and got an issue 
```49s     18s     7   default-scheduler           Warning     FailedScheduling    pod (rook-ceph-mon0-j9kdk) failed to fit in any node
fit failure summary on nodes : MatchNodeSelector (2), PodToleratesNodeTaints (1)
parallels@ubuntu:~$ ```

But since it worked in minikube, it led me to believe it was an environment issue. I will close this for now.

As for compatibility, shouldnt rook follow K8s compatibility? I think k8s supports previous 4 versions. So that is why i think rook master should support 1.5. An example is client-go: https://github.com/kubernetes/client-go/#compatibility-matrix.

**Comment by bassam** [comment]
We [re]added support for 1.5 for OpenShift and other commercial distributions that tend to have a longer tail. As a policy I think it makes sense to support whatever versions `client-go` supports -- which from https://github.com/kubernetes/client-go/#compatibility-matrix looks like n-2, n-1, n (current), n+1 (alpha/beta)

Does that make sense?

**Comment by kokhang** [comment]
Closing this as 1.5 is still working for me
