### ISSUE TITLE
CSI volumes freeze cluster: PLEG is not healthy

### ISSUE THREAD

**Issue by stefanfritsch** [rook/rook#7914]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I upgraded a rook cluster from v1.5.9 to v1.6.2 and ceph from 15.2 to 16.2 following the docs on rook.io. The upgrade completed successfully. 

Since the upgrade the cluster is unusable. Nodes freeze with the message from the subject:

```
PLEG is not healthy
```

If I ssh into the nodes `df` hangs and `strace df` shows that it hangs at cephfs CSI volumes

```
[...]
stat("/run/docker/netns/5fffb2554c15", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/var/lib/docker/overlay2/5807c476813fd58d92c80f2de8a9b96100a97691cf7a904a2358833eeaacc2e0/merged", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/var/lib/kubelet/plugins/kubernetes.io/csi/pv/website-mariadb/globalmount", 
<hangs>
```

Rebooting the node helps for a few minutes. I assume until the next CSI volume is mounted. 

I changed the CSI images back to the versions listed in the docs for version 1.5 (which worked before) but that didn't help. That's why I'm posting this here. Mounting a dir manually in a pod from `direct-mount.yml` works fine. So it has to be related to CSI, though.

**Expected behavior:**

I have a working kubernetes cluster

**How to reproduce it (minimal and precise):**

I did nothing but the aforementioned upgrade.

It does show the following warning:

```
AUTH_INSECURE_GLOBAL_ID_RECLAIM_ALLOWED: mons are allowing insecure global_id reclaim
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

I couldn't find anything useful in the logs. But it's very late here and the CSI stuff is distributed across half a dozen containers. I'm happy to post any logs you think might be useful.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04 and 20.04
* Kernel (e.g. `uname -a`): 5.4.0-73-generic
* Cloud provider or hardware configuration: bare-metal
* Rook version (use `rook version` inside of a Rook Pod): 1.6.2
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.4
* Kubernetes version (use `kubectl version`): v1.20.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare-metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

```
HEALTH_WARN mons are allowing insecure global_id reclaim; mon k is low on available space
```

**Comment by Madhu-1** [comment]
@stefanfritsch looks like you are using static PV

* can you please paste the PV yaml?
* Provide cephfsplugin container logs from the node where the mount is failing (cephfs-plugin-xxx pod)
* kernel version from the node.
* ceph cluster health

**Comment by psavva** [comment]
For the health warn, check https://github.com/rook/rook/issues/7746
