### ISSUE TITLE
Implement encryption key rotation for cluster-wide (OSDs) encryption

### ISSUE THREAD

**Issue by leseb** [rook/rook#7925]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Ability to rotate OSDs key-encryption keys.

**What is use case behind this feature:**

Increase security.

**Environment**:

**Comment by parth-gr** [comment]
@travisn @leseb How is owning this,
Looks interesting to me I can take a look.

**Comment by parth-gr** [comment]
@Rakshith-R I see you working on it, Are you taking the rook part also?

**Comment by Rakshith-R** [comment]
> @Rakshith-R I see you working on it, Are you taking the rook part also?

Yes,

**Comment by Rakshith-R** [comment]
> From the top of my head, we would need:
> 
> * Ability to configure a retention policy
> * Use cronjob to create a new KEK, add it to the KEK to the LUKS slot, add it to the KMS (if any), remove the previous KEK from the slot
> * We need one job for each OSD PVC
> * We don't need to restart the OSD or stop it, this can be done on the fly

I am thinking of starting this implementation with a simpler use case of OSD backed by PVC in raw mode. Later on adding support to other kinds of storage that can back OSDs.

Instead of a cronjob, we can have a sidecar container running alongside OSD, coming alive only to rotate the KEK on the already open luks device and going to sleep. This sidecar would do its controlled by [cron format schedule](https://en.wikipedia.org/wiki/Cron#Cron_expression) like `@weekly`, `@monthly`, `@daily` etc. 

---

### KEK rotation logic would be as follows: 

| Step | Operation                 | Luks Slot 1 | Luks Slot 2 | Key in KMS |
|:---- |:------------------------- |:----------- |:----------- |:---------- |
| 1    | Obtain K1                 | K1          |             | K1         |
| 2    | Add K1 to slot 2          | K1          | K1          | K1         |
| 3    | Create K2 & add to slot 1 | K2          | K1          | K1         |
| 4    | Update K2 in KMS          | K2          | K1          | K2         |
| 5    | Remove K1 from slot 2     | K2          |             | K2         |
 
 Note: The above steps will ensure the KEK in kms will be able to open the encrypted device even if the operation is disrupted at any step.

Refer: [10 Linux cryptsetup Examples for LUKS Key Management (How to Add, Remove, Change, Reset LUKS encryption Key)](https://www.thegeekstuff.com/2016/03/cryptsetup-lukskey/)

---

### Cephcluster CR changes
We can add parameters `enableKeyRotation: <true|false>` and `schedule: <cron_format, default to @weekly>` to
security section of cephcluster spec here https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Advanced/key-management-system.md.
```
security:
  kms:
    connectionDetails:
      # new parameters for encryption key rotation
      enableKeyRotation: "true"
      schedule: "@monthly" 
    
      KMS_PROVIDER: vault
      ....
      tokenSecretName: rook-vault-token

```
cc @travisn @BlaineEXE

**Comment by Madhu-1** [comment]
>Instead of a cronjob, we can have a sidecar container running alongside OSD, coming alive only to rotate the KEK on the already open luks device and going to sleep. This sidecar would do be controlled by [cron format schedule](https://en.wikipedia.org/wiki/Cron#Cron_expression) like @weekly, @monthly, @daily etc.

What advantage we will get if we have a sidecar container instead of cronJob? if the osd is retarded the sidecar might lose time, and it will go to sleep the whole time again (if we dont store it somewhere),  should there be a lock b/w this sidecar, or cronjob should make sure the device is operated by only one process at a time?
 IMO cronJob makes it easier as kubernetes will take care of scheduling.

**Comment by Rakshith-R** [comment]
> > Instead of a cronjob, we can have a sidecar container running alongside OSD, coming alive only to rotate the KEK on the already open luks device and going to sleep. This sidecar would do be controlled by [cron format schedule](https://en.wikipedia.org/wiki/Cron#Cron_expression) like @Weekly, @monthly, @daily etc.


> What advantage we will get if we have a sidecar container instead of cronJob?

No need for remounting of PVC, opening of encrypted device again, most of the required state is already present if it exists as a sidecar of OSD.

> if the osd is retarded the sidecar might lose time, and it will go to sleep the whole time again (if we dont store it somewhere), 

what does retarded mean in this context ?  
(if we dont store it somewhere) we'll figure it out.

> should there be a lock b/w this sidecar, or cronjob should make sure the device is operated by only one process at a time? 

There's no need for that, We'll just be adding/removing keys to a already open luks device.

> IMO cronJob makes it easier as kubernetes will take care of scheduling.

I don't think we need to add complexity of adding a cronjob that needs to redo most the init process that's already done by OSD pod. This cronjob will need to create a pod, which will need to mount PVC, fetch key, open encryption, etc.

**Comment by Rakshith-R** [comment]
> Why can't the cronjob run alongside the OSD container? You don't need to remount the PVC since it's already consumed by the OSD, the cronjob code is simply creating a new KEK, adds it to a slot, and removes the previous key from the slot. If the OSD is running you should be able to interact with the PVC.

A normal pod cannot interact with PVC mounted to another pod.
It will have to mount it again and go through the init process.

> The problem with the sidecar is that if the pod crashes, we lose the history and we don't know if the rotation was performed or not, we just lost the state, and as @Madhu-1 said we postpone the rotation to one week (if it's weekly).
> 
> I think using a k8s cronjob is much easier, and less error-prone.

I guess the only concern with sidecar vs cronjob is storing last rotated state.
IMO, we can easily figure this out, maybe store it as annotation on OSD deployment ?
(the state does not have to be within the pod itself)
I think this is a good way to convey the key was rotated too.

**Comment by leseb** [comment]
> > Why can't the cronjob run alongside the OSD container? You don't need to remount the PVC since it's already consumed by the OSD, the cronjob code is simply creating a new KEK, adds it to a slot, and removes the previous key from the slot. If the OSD is running you should be able to interact with the PVC.
> 
> A normal pod cannot interact with PVC mounted to another pod. It will have to mount it again and go through the init process.

I don't think we can expect this pod to be a "normal" pod. I believe it will be privileged and bindmount /dev or something along those lines.
Also IIRC /var/lib/ceph is exposed on hostPath so the PVC block and the encrypted one should be present.

> 
> > The problem with the sidecar is that if the pod crashes, we lose the history and we don't know if the rotation was performed or not, we just lost the state, and as @Madhu-1 said we postpone the rotation to one week (if it's weekly).
> > I think using a k8s cronjob is much easier, and less error-prone.
> 
> I guess the only concern with sidecar vs cronjob is storing last rotated state. IMO, we can easily figure this out, maybe store it as annotation on OSD deployment ? (the state does not have to be within the pod itself) I think this is a good way to convey the key was rotated too.

**Comment by Rakshith-R** [comment]
> > > Why can't the cronjob run alongside the OSD container? You don't need to remount the PVC since it's already consumed by the OSD, the cronjob code is simply creating a new KEK, adds it to a slot, and removes the previous key from the slot. If the OSD is running you should be able to interact with the PVC.
> > 
> > 
> > A normal pod cannot interact with PVC mounted to another pod. It will have to mount it again and go through the init process.
> 
> I don't think we can expect this pod to be a "normal" pod. I believe it will be privileged and bindmount /dev or something along those lines. Also IIRC /var/lib/ceph is exposed on hostPath so the PVC block and the encrypted one should be present.

I think it's simpler to have sidecar container considering all these points. 

> > > The problem with the sidecar is that if the pod crashes, we lose the history and we don't know if the rotation was performed or not, we just lost the state, and as @Madhu-1 said we postpone the rotation to one week (if it's weekly).
> > > I think using a k8s cronjob is much easier, and less error-prone.
> > 
> > 
> > I guess the only concern with sidecar vs cronjob is storing last rotated state. IMO, we can easily figure this out, maybe store it as annotation on OSD deployment ? (the state does not have to be within the pod itself) I think this is a good way to convey the key was rotated too.
> 
> I think so too, something lastRotated: on the OSD or the PVC?

Yes,

**Comment by Rakshith-R** [comment]
### Cephcluster CR changes

 parameters `enabled: <true|false>` and `schedule: <cron_format, default to @weekly>` are added to
`security.keyRotation` section of cephcluster spec here https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Advanced/key-management-system.md.
```
security:
  kms:
    keyRotation: 
      enabled: "true"
      schedule: "@weekly" 
    connectionDetails:
      KMS_PROVIDER: vault
      ....
      tokenSecretName: rook-vault-token
```

---

### KMS changes

Support for `KMS.UpdateSecret()` is added.
Currently only default type/ k8s secret is supported
It will be extended in future to support other KMS such as vault,ibm hpcs, kmip etc.

---

### KEK Rotation logic would be as follows: 

| Step | Operation                 | Luks Slot 0 | Luks Slot 1 | Key in KMS |
|:---- |:------------------------- |:----------- |:----------- |:---------- |
| 1    | Obtain K1                 | K1          |             | K1         |
| 2    | Add K1 to slot 1          | K1          | K1          | K1         |
| 3    | Create K2 & add to slot 0 | K2          | K1          | K1         |
| 4    | Update K2 in KMS          | K2          | K1          | K2         |
| 5    | Remove K1 from slot 1     | K2          |             | K2         |
 
Note: The above steps will ensure the KEK in kms will be able to open the encrypted device even if the operation is disrupted at any step and all the edge cases from disrupted processes are handled.

`luksAddKey, luksChangeKey, luksKillSlot` commands are being used to achieve this.

Refer: [10 Linux cryptsetup Examples for LUKS Key Management (How to Add, Remove, Change, Reset LUKS encryption Key)](https://www.thegeekstuff.com/2016/03/cryptsetup-lukskey/)

---

### KEK Rotation Cron Job

- One Cron Job per encrypted PVC backed OSD is be created when key rotation is enabled with the given schedule.
- The Cron Job will use OSD pod affinity `requiredDuringScheduling..` using OSD's labels as selector to run on the same node as the OSD.
- The Cron Job will share the host bridge directory with the OSD which contains the enrcypted devices mapped to be able to rotate the KEK.

--- 

refer: #11749

**Comment by travisn** [comment]
@Rakshith-R Could you actually add this as a design document (perhaps to #11749 or a new PR)? It really would help to capture it under https://github.com/rook/rook/tree/master/design/ceph so it's not just in this issue. Then we can add to it in the future when key rotation designs are updated for KMS solutions.

**Comment by Rakshith-R** [comment]
> @Rakshith-R Could you actually add this as a design document (perhaps to #11749 or a new PR)? It really would help to capture it under https://github.com/rook/rook/tree/master/design/ceph so it's not just in this issue. Then we can add to it in the future when key rotation designs are updated for KMS solutions.

:+1:  added it as a new pr.  #11788
