### ISSUE TITLE
upgrade storage.k8s.io/v1beta1 to storage.k8s.io/v1

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#7941]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
the operator log shows the following warning:
```
W0513 04:16:46.857358       9 warnings.go:70] storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
```

**Expected behavior:**
No warning in the operator log expected

**Comment by Madhu-1** [comment]
Duplicate of https://github.com/rook/rook/issues/7020?

**Comment by subhamkrai** [comment]
> Duplicate of #7020?

right, I missed that.

**Comment by niwenjie996** [comment]
oh, i see, Thanks for your reply
