### ISSUE TITLE
CSI pods fail to start if the rook operator fails to read  `rook-ceph-operator-config`configmap.

### ISSUE THREAD

**Issue by Rakshith-R** [rook/rook#7950]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
CSI pods are not started if an error is encountered while reading the `rook-ceph-operator-config`configmap.

**Expected behavior:**
Rook operator must retry starting CSI Drivers when it encounters an error.

**How to reproduce it (minimal and precise):**
NA

**File(s) to submit**:
NA

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
```
2021-05-19 10:32:06.905743 I | ceph-csi: Kubernetes version is 1.20
2021-05-19 10:32:07.595903 E | ceph-csi: failed to start Ceph csi drivers. failed to load ROOK_CSI_RESIZER_IMAGE setting: error reading ConfigMap "rook-ceph-operator-config". etcdserver: leader changed

```
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by Rakshith-R** [comment]
Rook currently starts csi drivers in go routine(`go csi.ValidateAndConfigureDrivers`) to not block the cluster initialization, see  https://github.com/rook/rook/commit/6c249e751b12425602351eae6b393da6973ccaef. 
https://github.com/rook/rook/blob/fcf634e3b7808e4338e7fd261c047aae4793e99b/pkg/operator/ceph/operator.go#L258

This may lead to race conditions(when second configmap change go routine call finishes after the first ) and csi drivers not being started by rook. 

As far as i can understand, `csiconfigmap` creation is the reason callback is called before `initializeCluster` (?). 
If so, we can refactor to call create `csiconfigmap` before `initializeCluster` and move startdriver callback to after it having it in the same control flow(such that it is requeued if there is an error, no go routine).
https://github.com/rook/rook/blob/e1b64e3624114f94265b97f974813c5af847461b/pkg/operator/ceph/cluster/controller.go#L344-L360
 @travisn @leseb @Madhu-1

**Comment by travisn** [comment]
@Rakshith-R I'm not following the race condition. From the original issue, seems like if the [startDrivers()](https://github.com/rook/rook/blob/fcf634e3b7808e4338e7fd261c047aae4793e99b/pkg/operator/ceph/csi/csi.go#L43) method fails, we just need to try again several times in a `for` loop until it succeeds.

**Comment by Rakshith-R** [comment]
Actually go routine `csi.ValidateAndConfigureDrivers` fails inside startdriver(). 
I meant race condition may happen with the go routine function call. 
Looping over in a go routine will lead to more complications, like having a good stop condition and handling race condition with next config update.

**Comment by Rakshith-R** [comment]
@travisn We would need a mutex lock inplace to ensure one go routine is running at a time and we would also need to decide how to handle if another config update event triggers updatedriver function when one is running.

Any reason not to use the same reconciler for starting driver after cluster initialization?
It would be simpler to handle failures and multiple event triggers.

**Comment by travisn** [comment]
> Any reason not to use the same reconciler for starting driver after cluster initialization?
It would be simpler to handle failures and multiple event triggers.

Can you explain this more? What do you mean to use the same reconciler?

**Comment by Rakshith-R** [comment]
`startDrivers` is one of the callbacks here, which internally calls updatedriver which creates csiconfigmap then calls go routine `validateandconfiguredriver`.

The reason for placing it before `initialcluster` as I understand is we need the csicpnfigmap to be created first and usage of go routine is to not block cluster creation.

My proposal is to just create csicpnfigmap in the same position and move startdriver call to after `initializecluster` keeping it in a single control flow and returning error so it can be re-queued.

https://github.com/rook/rook/blob/e1b64e3624114f94265b97f974813c5af847461b/pkg/operator/ceph/cluster/controller.go#L344-L360

**Comment by travisn** [comment]
Rook has a number of goroutines to help make operations more parallel and unblocking. If we change the control flow for the csi driver, it will have other implications like delaying starting the csi driver until the end of the cluster reconcile, which isn't desired either. The CSI driver is really independent of the cluster CR, we just want to delay starting it until the first cluster is created. 

We don't need to prevent multiple callers to the goroutine, just multiple callers to the `startDrivers()` method since that's where the conflict could be. 

Wouldn't this be sufficient?
```golang
if CSIEnabled() {
	// TODO: Add a lock 
	// TODO: Add a for loop
	if err := startDrivers(context.Clientset, context.RookClientset, namespace, serverVersion, ownerInfo, v); err != nil {
		logger.Errorf("failed to start Ceph csi drivers. %v", err)
		return
	}
}
```
