### ISSUE TITLE
Fencing Question for rbd and cephfs to recover from node lost

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#7954]
Recently cephcsi pods in Rook have been updated to move away from host networking. I don't know we can/cannot hit this problem with multus networking.

As we are talking about recovery from node loss as mentioned at https://github.com/rook/rook/pull/7282. The node loss can happen for many reasons (Either kubelet is dead or whole node is dead etc)

The below problem might exist for both cephfs and RBD.

* As we are moving to the pod networking, the pod IP of rbdplugin and the cephfsplugin will be used as a watcher, we can fence that IP but the problem is what if the pod is just restarted and got a new IP? again the pods running on the node which is disconnected are going to get read and write access to the volumes and can corrupt the data?

* If the plugin pod on the other nodes is restarted and there is a slight chance that it can get the IP that is already fenced on the ceph side which can lead to read/write access denied to the existing applications on the node.

Ref https://github.com/rook/rook/pull/7282#issuecomment-839746053

cc @idryomov Can you please suggest that the above can cause an issue or not? is there an alternative way to fence the client from accessing the rbd images?

**Comment by Madhu-1** [comment]
CC @travisn @leseb @nixpanic @humblec @ShyamsundarR

**Comment by nixpanic** [comment]
Storage fencing (force detach) has been a proposal in the CSI Spec. We would get the node-id (ip-address or hostname) of the Pod that needs to be fenced. When using host-networking this should be stable and we can imagine this functioning correctly. However with non-hostnetworking it becomes questionable (asked for guidance at https://github.com/container-storage-interface/spec/pull/477#issuecomment-844854935).

**Comment by idryomov** [comment]
> The below problem might exist for both cephfs and RBD.
>
> * As we are moving to the pod networking, the pod IP of rbdplugin and the cephfsplugin will be used as a watcher, we can fence that IP but the problem is what if the pod is just restarted and got a new IP? again the pods running on the node which is disconnected are going to get read and write access to the volumes and can corrupt the data?

What is meant by "we can fence"?  If blocklisting via `ceph osd blocklist add` then you would be blocklisting a Ceph entity address (IP + unique nonce), not the entire IP address.  Blocklisting the entire IP address is also possible, but not common because the purpose of OSD-level blocklisting is to deal with split-brain scenarios: prevent a particular client instance that is _already_ connected to the cluster from flushing its buffered state that is no longer valid.  If the client process is restarted (whether after rebooting the node or without the reboot), it will get a new Ceph entity address.  No data corruption is possible because the restarted process wouldn't have any buffered state.

> 
> * If the plugin pod on the other nodes is restarted and there is a slight chance that it can get the IP that is already fenced on the ceph side which can lead to read/write access denied to the existing applications on the node.

If you don't blocklist entire IP addresses, you wouldn't run into this.

**Comment by idryomov** [comment]
Also, what is a watcher?  Are you talking about RADOS watches or something else?

**Comment by idryomov** [comment]
After skimming through linked issues, I see that it is RADOS watches.  Please note that relying on RADOS watches for telling what needs to be blocklisted is unreliable.  An image may still be mapped somewhere (and be written to!) with no watchers listed in `rbd status` output.

And there are no watches in the CephFS case at all.

**Comment by Madhu-1** [comment]
> After skimming through linked issues, I see that it is RADOS watches. Please note that listing watchers and relying on that for telling what needs to be blocklisted is unreliable. An image may still be mapped somewhere (and be written to!) with no watchers in `rbd status` output.
> 

We do check watchers at the CSI level before mapping an RWO(ReadWriteOnly) rbd PVC. Is there any way to block the client from reading and write access to the rbd image from a particular node in case of node lost scenerio?

> And there are no watches in the CephFS case at all.

Yes for CephFS I was talking about  https://docs.ceph.com/en/latest/cephfs/eviction/#manual-client-eviction client evection.

**Comment by idryomov** [comment]
> Is there any way to block the client from reading and write access to the rbd image from a particular node in case of node lost scenerio?

Yes, blocklisting.  The issue is knowing what to blocklist.  If you do the entire IP address, you run into IP address reuse issues.
Doing individual clients instances is much better but you need to know their entity addresses in advance.  Getting them right before blocklisting from `rbd status` or `rados listwatchers` is not reliable.

**Comment by Madhu-1** [comment]
> > Is there any way to block the client from reading and write access to the rbd image from a particular node in case of node lost scenerio?
> 
> Yes, blocklisting. The issue is knowing what to blocklist. If you do the entire IP address, you run into IP address reuse issues.
> Doing individual clients instances is much better but you need to know their entity addresses in advance. Getting them right before blocklisting from `rbd status` or `rados listwatchers` is not reliable.

With individual client instance blacklisting , Due to restart of rbdplugin ( pod ip might get change) and application pod will their be any chance to get read and write access again?

**Comment by idryomov** [comment]
> With individual client instance blacklisting , Due to restart of rbdplugin ( pod ip might get change) and application pod will their be any chance to get read and write access again?

If the pod is restarted, it will be able to read and write again even if the IP address remains the same because it will get a new Ceph entity address (same IP but different nonce).

**Comment by Madhu-1** [comment]
> > With individual client instance blacklisting , Due to restart of rbdplugin ( pod ip might get change) and application pod will their be any chance to get read and write access again?
> 
> If the pod is restarted, it will be able to read and write again even if the IP address remains the same because it will get a new Ceph entity address (same IP but different nonce).

Then using pod networking for CSI would be a problem? If we switch back to host networking and blacklist the IP will that problem be solved ( I think even in the case of some cloud providers the VM's (kubernetes nodes) might get the same IP even in the case of hostnetworking) or there any other solutions to fix this issue?

**Comment by Madhu-1** [comment]
> > The below problem might exist for both cephfs and RBD.
> > 
> > * As we are moving to the pod networking, the pod IP of rbdplugin and the cephfsplugin will be used as a watcher, we can fence that IP but the problem is what if the pod is just restarted and got a new IP? again the pods running on the node which is disconnected are going to get read and write access to the volumes and can corrupt the data?
> 
> What is meant by "we can fence"? If blocklisting via `ceph osd blocklist add` then you would be blocklisting a Ceph entity address (IP + unique nonce), not the entire IP address. Blocklisting the entire IP address is also possible, but not common because the purpose of OSD-level blocklisting is to deal with split-brain scenarios: prevent a particular client instance that is _already_ connected to the cluster from flushing its buffered state that is no longer valid. If the client process is restarted (whether after rebooting the node or without the reboot), it will get a new Ceph entity address. No data corruption is possible because the restarted process wouldn't have any buffered state.
> 

What I meant here was the inconsistent data as the application might writing some data from the disconnected node, Which will lead to inconsistent data on the RBD/CephFS volume.

> > * If the plugin pod on the other nodes is restarted and there is a slight chance that it can get the IP that is already fenced on the ceph side which can lead to read/write access denied to the existing applications on the node.
> 
> If you don't blocklist entire IP addresses, you wouldn't run into this.

**Comment by travisn** [comment]
I believe the goal of this discussion is to determine:
1. Is it ok to use pod networking, or do we need to use host networking as before?
2. Is there any risk of corruption when using pod networking, that we wouldn't see with host networking?
3. Document steps for an admin to ensure data safety when a node is lost.

If a pod is force deleted, after some timeout (~11 minutes), the pod will be allowed to start on a new node and mount the volume. In order for this to be safe, is it required that the original node be permanently offline so the old volume doesn't write and cause corruption? 

If the admin can't guarantee the node is permanently offline, this is when they need to blocklist the node, right? And in this case, it seems like we need to permanently blocklist either the node's ip address (if using host networking), or the pod's ip address (if not using host networking). In the latter case, if the pod could be restarted with a different ip address, the volume could come back online and cause corruption, right? So don't we need to use host networking and recommend users blocklist the node's ip? Blocklisting anything else seems like it wouldn't protect against corruption from two writers, as long as the failed node has the possibility of coming back online.

**Comment by Madhu-1** [comment]
@idryomov can you please provide your feedback?

**Comment by idryomov** [comment]
So far I don't see why host networking vs pod networking would play a role here.

If the original Ceph entity is blocklisted, that guarantees that the original pod wouldn't be able to come back online and cause corruption.  Unless we are considering the failed node going rogue to the extent where it can restart the original pod on its own, I don't see how two writers can arise -- blocklisting the Ceph entity (which is per-pod independent of the networking setup) should be sufficient.

Please correct me if I am misunderstanding the "threat" model.

**Comment by ShyamsundarR** [comment]
> So far I don't see why host networking vs pod networking would play a role here.
> 
> If the original Ceph entity is blocklisted, that guarantees that the original pod wouldn't be able to come back online and cause corruption. Unless we are considering the failed node going rogue to the extent where it can restart the original pod on its own, I don't see how two writers can arise -- blocklisting the Ceph entity (which is per-pod independent of the networking setup) should be sufficient.
> 
> Please correct me if I am misunderstanding the "threat" model.

What I see (unverified) is that pod network IPs can be assigned to pods across nodes at will. If a pod in a node is using `IP1` and the node is deemed unavailable, we would blocklist `IP1`. Nothing prevents `IP1` being reassigned to another pod in the cluster on another node. This is a denial of service rather than a potential data corruption issue.

If `IP1` was a node IP instead, this above not feasible, and hence safer once blocklisted.

The other case is, if the pod is restarted on the unavailable node due to any reason (local kubelet action on the node, again unverified), then it may use up a new pod IP and hence avoid the blocklist. In this situation we may end up with 2 writers.

Using the node IP resolves both (possible) edge cases.

**Comment by idryomov** [comment]
> What I see (unverified) is that pod network IPs can be assigned to pods across nodes at will. If a pod in a node is using `IP1` and the node is deemed unavailable, we would blocklist `IP1`. Nothing prevents `IP1` being reassigned to another pod in the cluster on another node. This is a denial of service rather than a potential data corruption issue.

I was suggesting blocklisting a Ceph entity address instead of the entire IP address, precisely to avoid the potential denial of service scenario.  But ...

> 
> The other case is, if the pod is restarted on the unavailable node due to any reason (local kubelet action on the node, again unverified), then it may use up a new pod IP and hence avoid the blocklist. In this situation we may end up with 2 writers.

... if this is something we need to guard against, blocklisting at the IP level is the only option.

I have a hard time wrapping my head around this though.  If workers can restart pods on their own without talking to the control plane, what is the procedure for adding a failed worker back to the cluster?  When readding the node at the Kubernetes level, who/what would know to unblocklist it at the Ceph level?

**Comment by Madhu-1** [comment]
> > What I see (unverified) is that pod network IPs can be assigned to pods across nodes at will. If a pod in a node is using `IP1` and the node is deemed unavailable, we would blocklist `IP1`. Nothing prevents `IP1` being reassigned to another pod in the cluster on another node. This is a denial of service rather than a potential data corruption issue.
> 
> I was suggesting blocklisting a Ceph entity address instead of the entire IP address, precisely to avoid the potential denial of service scenario. But ...
> 
> > The other case is, if the pod is restarted on the unavailable node due to any reason (local kubelet action on the node, again unverified), then it may use up a new pod IP and hence avoid the blocklist. In this situation we may end up with 2 writers.
> 
> ... if this is something we need to guard against, blocklisting at the IP level is the only option.
> 
> I have a hard time wrapping my head around this though. If workers can restart pods on their own without talking to the control plane, what is the procedure for adding a failed worker back to the cluster? When re-adding the node at the Kubernetes level, who/what would know to unblocklist it at the Ceph level?

Two cases. If only kubelet (control plane) was dead/not reachable it will get auto-added when it comes back. if the node was dead and the admin has to fix the problems manually, AFAIC based on the application logs or pod health he needs to unblocklist as the blacklisting is a manual process.

**Comment by gman0** [comment]
@ShyamsundarR sorry for resurrecting an old thread, but it seems there were some questions unanswered.

> The other case is, if the pod is restarted on the unavailable node due to any reason (local kubelet action on the node, again unverified), then it may use up a new pod IP and hence avoid the blocklist. In this situation we may end up with 2 writers.

Do you have any concrete examples of this happening? Wouldn't kubelet need to talk with the API to reconcile that Pod? If so, shouldn't that node be already back in the cluster?

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR sorry for resurrecting an old thread, but it seems there were some questions unanswered.
> 
> > The other case is, if the pod is restarted on the unavailable node due to any reason (local kubelet action on the node, again unverified), then it may use up a new pod IP and hence avoid the blocklist. In this situation we may end up with 2 writers.
> 
> Do you have any concrete examples of this happening? Wouldn't kubelet need to talk with the API to reconcile that Pod? If so, shouldn't that node be already back in the cluster?

What I was not able to verify at the time was if kubelet on the node would restart pods that it had assigned to it from a prior instance, or if it would reach out to the API server again to refresh its local cache. While I have not verified this later, it does look like kubelet on restart would check back with the API server on pods that need to be started on the node, and then start them.

Is there any configuration (cached) that is left on the node, that may cause a pod to start is another question that I do not have an answer for (hence the "unverified" in the comment).

If someone could answer this concretely it would help alleviate any concerns overall.

**Comment by gman0** [comment]
@ShyamsundarR thanks for the answer!

> Is there any configuration (cached) that is left on the node, that may cause a pod to start is another question that I do not have an answer for (hence the "unverified" in the comment).

AFAIK there are only [static Pods](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/), but their definitions must not reference anything that would require API, including PVCs, so I'd say using ceph-csi is out of question.
