### ISSUE TITLE
"Upgrade" CephFS storage class to support resizing

### ISSUE THREAD

**Issue by abh** [rook/rook#7962]
I have a rook / ceph installation that was installed about two years ago and incrementally upgraded since.

Our CephFS storageclass doesn't have the now required `csi.storage.k8s.io/controller-expand-secret-name` and `-namespace` parameters and kubernetes won't let us add them (`updates to parameters are forbidden`).

Is there an "upgrade path" for this? We've upgraded recently to Ceph v16, so I understand multiple CephFS'es are supported now and we could make a new one; but I'd rather change the existing one so we get resize support for the current PVCs (and don't forever have two CephFSes that only both exist because of this).

**Comment by abh** [comment]
From other issues I cut'n'pasted the patch command below (adjust if your cephfs storage class doesn't end in 'cephfs') that works for fixing each PV, but not any new ones of course.

```
#!/bin/sh

# This will add some missing metadata to PVs to allow them to resize.
# Our storage classes were configured before the parameters existed
# and can't be changed(?), but the created PVs can...
# https://github.com/rook/rook/issues/7962

set -euo pipefail

if [ -z "$2" ]; then
    echo "csi-expansion-patch [namespace] [pvc]"
    exit 2
fi

namespace=$1
pvcname=$2

pvc=$(kubectl -n $namespace get pvc $pvcname -o jsonpath='{.spec.volumeName}')
class=$(kubectl -n $namespace get pvc $pvcname -o jsonpath='{.spec.storageClassName}')

if [ $class == "*cephfs" ]; then
    kubectl patch pv $pvc \
      --patch '{"spec":{"csi":{"controllerExpandSecretRef":{"name":"rook-csi-cephfs-provisioner","namespace":"rook-ceph"}}}}'
else
    kubectl patch pv $pvc \
      --patch '{"spec":{"csi":{"controllerExpandSecretRef":{"name":"rook-csi-rbd-provisioner","namespace":"rook-ceph"}}}}'
fi
```

**Comment by Madhu-1** [comment]
https://github.com/rook/rook/issues/5670#issuecomment-646071304 PV patching is allowed for namespace update is not allowed. You need to delete and recreate the storageclass with the same details.

**Comment by abh** [comment]
Does deleting the storageclass affect the existing PVCs or PVs?

**Comment by Madhu-1** [comment]
@abh if you delete and recreate the storageclass, it won't. Don't change any other parameters except `allowExpansion`

**Comment by abh** [comment]
thanks @madhu-1.

**Comment by Links2004** [comment]
thanks for the script.
for mass updating this may help:
```bash
kubectl get pvc --all-namespaces  --output json | jq -r '.items[]  | select( .spec.storageClassName == "csi-rbd-sc"  )  | "\(.metadata.namespace) \(.metadata.name)"' | while read -r NS NAME ; do /tmp/fix_pvc.sh $NS $NAME ; done
```

`/tmp/fix_pvc.sh` is the script from https://github.com/rook/rook/issues/7962#issuecomment-845646556
