### ISSUE TITLE
1.6.3 panic runtime error

### ISSUE THREAD

**Issue by Antiarchitect** [rook/rook#7963]
1.6.2 -> 1.6.3 Operator upgrade:

```
panic: runtime error: index out of range [0] with length 0
goroutine 1138 [running]:
github.com/rook/rook/pkg/operator/ceph/controller.ConfigureExternalMetricsEndpoint(0xc0001f2360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc002fa61e
/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/controller/spec.go:684 +0x71f
github.com/rook/rook/pkg/operator/ceph/cluster/mon.(*Cluster).checkHealth(0xc002cae800, 0x0, 0x0)
 /home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/health.go:125 +0x2ad
github.com/rook/rook/pkg/operator/ceph/cluster/mon.(*HealthChecker).Check(0xc005e57060, 0xc005e33380) /home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/health.go:88 +0xce 
created by github.com/rook/rook/pkg/operator/ceph/cluster.(*ClusterController).startMonitoringCheck 
 /home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/monitoring.go:116 +0x43a
```

**Comment by travisn** [comment]
@Antiarchitect A few questions:
- This is an external cluster configuration, correct?
- Does the operator log show this error? `failed to get mgr map.` Are there other details with that error message?
- Have you specified the `monitoring.externalMgrEndpoints` in the CephCluster CR? This shouldn't be required, but it looks like the issue. If you specify a value here, hopefully it will workaround until this is fixed.

**Comment by Antiarchitect** [comment]
1. External ceph cluster - yes.
2. Sorry rolled back to 1.6.2 and didn't save full log
3. I didn't find this in my Helm chart configs and templates. Should I?
