### ISSUE TITLE
Child controllers should reconcile if the ceph image changed

### ISSUE THREAD

**Issue by travisn** [rook/rook#7964]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Currently the reconcile for child controllers such as file and object are only triggered if the Ceph version changed. 

The version check is currently only based on the build number.

In the repro seen where mds and rgw were not updated, the two versions before/after the upgrade were:
```
ceph version 14.2.11-139.0.hotfix.xxxxxxx.el8cp
(5c0dc966af809fd1d429ec7bac48962a746af243) nautilus (stable)": 7,
"ceph version 14.2.11-139.el8cp (b8e1f91c99491fb2e5ede748a1c0738ed158d0f5)
nautilus (stable)": 4
```

The build numbers 14.2.11-139 are all equivalent. The rest of the build version is ignored by Rook for the comparison.

**Expected behavior:**
The child controllers should all reconcile if the Ceph image changes, not just if the ceph version changed inside the image. The update to the image may not always include an update to the version number, at least in some downstream hotfix builds. 

**How to reproduce it (minimal and precise):**

For a simple repro:
- Deploy Rook with a ceph image such as `ceph/ceph:v16.2.4`
- Create object.yaml and filesystem.yaml to ensure child controllers are active
- Change the docker tag locally to simulate an image change: `docker tag ceph/ceph:v16.2.4 ceph/ceph:v16.2.4-alternate`
- Apply the new image to the CephCluster CR: `ceph/ceph:v16.2.4-alternate`
- Notice that all the daemons are updated except rgw and mds

**Comment by travisn** [comment]
The child controllers are triggered based on [this code block](https://github.com/rook/rook/blob/e115e0ada8507a506ddbc8adeb1e6e3bbd6389b5/pkg/operator/ceph/cluster/cluster.go#L127-L133). It seems `c.isUpgrade` also should be true if the image changed, not just if the ceph version changed.

**Comment by sp98** [comment]
looking into it.
