### ISSUE TITLE
cephfs-mirror: followup items

### ISSUE THREAD

**Issue by leseb** [rook/rook#7975]
A few follow-up items once the patches in Ceph are ready:

* reporting snapshot status is blocked by https://tracker.ceph.com/issues/50954

**Comment by travisn** [comment]
@leseb The tracker is resolved, shall we proceed with this?

**Comment by leseb** [comment]
> @leseb The tracker is resolved, shall we proceed with this?

Resolved but no backports. It looks like it will never be backported in Pacific...
Let's just close this.
