### ISSUE TITLE
cephfs plugin restarting

### ISSUE THREAD

**Issue by aasraoui** [rook/rook#7982]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
 k -n rook-ceph logs csi-cephfsplugin-x4tj4 liveness-prometheus
I0524 21:21:50.352838       1 connection.go:153] Connecting to unix:///csi/csi.sock
**F0524 21:21:50.353534       1 httpserver.go:24] failed to listen on address 10.x.x.4:9081: listen tcp 10.x.x.4:9081: bind:** address already in use
goroutine 1 [running]:

Checking the ports on firewall is open:
firewall-cmd --list-ports
 9081/tcp

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
csi cephfs logs attached

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

OS (e.g. from /etc/os-release):
centos 7
Kernel (e.g. uname -a):
3.10.0-1062.el7.x86_64
Cloud provider or hardware configuration:
Rook version (use rook version inside of a Rook Pod):
Rook v1.5.6
Storage backend version (e.g. for ceph do ceph -v):
ceph version 15.2.8
Kubernetes version (use kubectl version):
"v1.18.2"
Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
k8

**Comment by aasraoui** [comment]
attached csi-cephfsplugin;   
[csi-cephfsplugin-log.txt](https://github.com/rook/rook/files/6535149/csi-cephfsplugin-log.txt)

**Comment by travisn** [comment]
Try at least Rook version v1.5.9 where the grpc metrics port was disabled by default with #7379, or you could change that setting to disable the metrics.

**Comment by Madhu-1** [comment]
If you want to change the port number you can change it to something else here https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L273

**Comment by aasraoui** [comment]
@Madhu-1 changing the port works, why is the default port is in use ?

**Comment by Madhu-1** [comment]
@aasraoui default ports might be used by some other process.
