### ISSUE TITLE
configmap:rook-ceph-csi-config be changed by rook-ceph-operator when operator restart.

### ISSUE THREAD

**Issue by jpsn123** [rook/rook#7987]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
operator should init csi config at first start, but it will always reconfig configmap for me, and delete my modification, i add field like `radosNamespace` , `cephFS.subvolumeGroup`.

**How to reproduce it (minimal and precise):**
just restart it. then watch configmap changes.

**File(s) to submit**:
rook-ceph-csi-config before
```
[
  {
    "clusterID": "rook-ceph",
    "radosNamespace": "default",
    "monitors": [
      "10.16.1.103:6789",
      "10.16.1.102:6789",
      "10.16.1.101:6789"
    ],
    "cephFS": {
      "subvolumeGroup": "default"
    }
  },
  {
    "clusterID": "rook-ceph-base",
    "radosNamespace": "base",
    "monitors": [
      "10.16.1.103:6789",
      "10.16.1.102:6789",
      "10.16.1.101:6789"
    ],
    "cephFS": {
      "subvolumeGroup": "base"
    }
  }
]
```
after restart operator
```
[
  {
    "clusterID": "rook-ceph",
    "monitors": [
      "10.16.1.102:6789",
      "10.16.1.103:6789",
      "10.16.1.101:6789"
    ]
  },
  {
    "clusterID": "rook-ceph-base",
    "monitors": [
      "10.16.1.103:6789",
      "10.16.1.102:6789",
      "10.16.1.101:6789"
    ]
  }
]
```
some field disappeared

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 20.04.2
* Kernel (e.g. `uname -a`): Linux k8s-1 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: kvm
* Rook version (use `rook version` inside of a Rook Pod): 1.6
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph version 16.2.4 (3cbe25cde3cfa028984618ad32de9edc4c1eaed0) pacific (stable)
* Kubernetes version (use `kubectl version`):  v1.21.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): original
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):  HEALTH_OK

**Comment by Madhu-1** [comment]
@jpsn123 CSI configmap is not meant for manual editing, There is a separate issue opened for subvolumegroup and rados namespace https://github.com/rook/rook/issues/7035 https://github.com/rook/rook/issues/7036

**Comment by jpsn123** [comment]
@Madhu-1  thank your anwser. currently both issue have not been started yet since you open them, and now, i want to depoly rook for product. can make operator to avoid modifying CSI configmap if it exist?

**Comment by Madhu-1** [comment]
AFAIK Not possible for now. Modifying CSI configmap and adding some more fields might not be backward compatible we might break, Better to wait for official support in Rook.

**Comment by travisn** [comment]
@jpsn123 The operator updates the csi configmap to keep the list of mons updated in case a mon is failed over. Why do you want to modify the configmap?

**Comment by jpsn123** [comment]
@travisn  see this https://github.com/ceph/ceph-csi/issues/1884 , i want to isolate my company different business groups through `subvolumeGroup` or `namespace` whice concept in ceph. but now , I have modified the source code to prevent operator from modifying the configMap every time. this is temporary measure, and I hope see features of the first close as soon as possible. thanks guys!

**Comment by travisn** [comment]
@Madhu-1 Should we reopen this to allow the fields like that to be editable?

**Comment by Madhu-1** [comment]
> @Madhu-1 Should we reopen this to allow the fields like that to be editable?

@travisn it can lead to other compatibility problems. IMO it should be fine to wait for some time till we add the rbd namespace and cephfs subvolumegroup support in Rook.
