### ISSUE TITLE
Add `jq` to the Ceph toolbox

### ISSUE THREAD

**Issue by nixpanic** [rook/rook#7989]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Add the `jq` executable to the Ceph toolbox.

**What is use case behind this feature:**
Many Ceph commands allow outputting as JSON. For scripting actions, procedures or logging through the Ceph toolbox, it would be useful to have the `jq` executable available.

**Environment**:
Example for OpenShift Container Storage must-gather which gathers details about the Ceph cluster, see [`gather_ceph_resources`](https://github.com/openshift/ocs-operator/blob/master/must-gather/collection-scripts/gather_ceph_resources). 
If adding to the Ceph toolbox is not preferred, maybe it is recommended to add the executable to the [base Ceph container image(s)](https://github.com/ceph/ceph-container) instead?

**Comment by travisn** [comment]
@nixpanic The toolbox image is the same as the [Rook operator image](https://github.com/rook/rook/blob/master/images/ceph/Dockerfile), which only adds what is directly needed for Rook. Since jq would be for working with the ceph commands in the toolbox, adding jq to the base ceph image would be preferable.

**Comment by leseb** [comment]
> @nixpanic The toolbox image is the same as the [Rook operator image](https://github.com/rook/rook/blob/master/images/ceph/Dockerfile), which only adds what is directly needed for Rook. Since jq would be for working with the ceph commands in the toolbox, adding jq to the base ceph image would be preferable.

We could argue the same for the base ceph image :).
Also, wherever we add `jq` we will need to add it downstream as well.

Embedding `jq` in our makefile might be easier for both upstream and downstream.

**Comment by travisn** [comment]
If it's really only needed in the toolbox, I'm not against including it in the rook image. But if it's needed downstream only I'm not sure we need to include it upstream. Downstream has a slightly different build process so we should consult with the build team on that.

**Comment by agarwal-mudit** [comment]
One of the customer hit this issue (https://bugzilla.redhat.com/show_bug.cgi?id=1974959)
Can we move forward with this? @nixpanic @travisn

**Comment by travisn** [comment]
`jq` would certainly be useful in the toolbox, for me it's just a question of whether to push it into the base Ceph image, or include it in Rook. @leseb wdyt?

**Comment by agarwal-mudit** [comment]
Thanks @travisn if we can fix this in 4.8 timeframe then it would be good. Adding @b-ranto in case we need help from build side.

**Comment by leseb** [comment]
`jq` is already part of the upstream toolbox, so the request is really only for downstream. Closing this then. Let's follow up internally with the build team.

**Comment by obnoxxx** [comment]
> `jq` is already part of the upstream toolbox, so the request is really only for downstream. Closing this then. Let's follow up internally with the build team.

@leseb - from looking at the rook:images directory, do I get it right, that it is coming from the ceph base image?

**Comment by leseb** [comment]
> > `jq` is already part of the upstream toolbox, so the request is really only for downstream. Closing this then. Let's follow up internally with the build team.
> 
> @leseb - from looking at the rook:images directory, do I get it right, that it is coming from the ceph base image?

Yes.
