### ISSUE TITLE
rook-ceph upgrade from 1.0.6 to 1.1.9: MDS has slow request. The result is slow to return by using ls or mkdir command in the mounted cephfs

### ISSUE THREAD

**Issue by huangyc-11** [rook/rook#8015]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook upgraded from 1.0.6 to 1.1.9, although the cluster status is HEALTH_OK, but the read / write io of RBD and cephfs is very high, and the return time of ls, mkdir and other operations in cephfs is slow. After using RBD to mount PVC, it is observed that the read / write IO is very high, which leads to the service can not be used normally

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
`kubectl logs -f rook-ceph-osd-0-7545fd6585-qxhtq -n rook-ceph`
![image](https://user-images.githubusercontent.com/82072690/120131566-409e4b80-c1fb-11eb-9e12-f8c2458df229.png)
![image](https://user-images.githubusercontent.com/82072690/120131464-164c8e00-c1fb-11eb-9b16-4cd8382972ee.png)

The read and write io of the mounted RBD is very high：
![企业微信截图_0c8dc9a9-42ca-4a43-91c3-255208571743](https://user-images.githubusercontent.com/82072690/120132809-92e06c00-c1fd-11eb-9cd8-9eadf1d4e309.png)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`): 3.10.0-862.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.1.9
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.8
* Kubernetes version (use `kubectl version`): 1.13.12
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@huangyc-11 Can you continue updating to newer versions of Rook and Ceph, or is your cluster stuck? Rook v1.1 is quite old now.

**Comment by huangyc-11** [comment]
Can I only try to upgrade to an updated version to solve this problem

**Comment by travisn** [comment]
@huangyc-11 You would need to follow the [upgrade guide](https://rook.github.io/docs/rook/v1.6/ceph-upgrade.html#supported-versions) from one Rook version to the next. Skipping versions isn't supported. I'm not sure the underlying cause for what you're seeing though.
