### ISSUE TITLE
ceph: fetch `rook-ceph-operator` configmap once

### ISSUE THREAD

**Issue by Rakshith-R** [rook/rook#8032]
**Is this a bug report or feature request?**
* Enhancement

Rook currently fetches configmap for every getting operator setting.
https://github.com/rook/rook/blob/4cf43bef95621ae67af4d486940e1dfb05c88bbd/pkg/operator/k8sutil/configmap.go#L44-L50

Instead configmap can be fetched once and passed in to get  each operator setting.

**Comment by travisn** [comment]
This is being done with #8607
