### ISSUE TITLE
creating file system should not use --force

### ISSUE THREAD

**Issue by batrick** [rook/rook#8059]
https://github.com/rook/rook/blob/master/pkg/operator/ceph/file/filesystem.go#L278

> ('fs new' needs to be forced in order to reuse pre-existing pools)

This should not ever be done except during disaster recovery. I'm not sure why this code was written this way.

cc @ajarr

**Comment by travisn** [comment]
@batrick @ajarr This was the scenario we were trying to address with the --force is that during reinstall, the pools from the previous filesystem could be used again. I thought the intention was to also not delete the filesystem during uninstall, but looks like that is not the behavior. Rook does remove the filesystem [here](https://github.com/rook/rook/blob/2b9bd2af1a63e9e062e385c99eecda6a0d2a6a81/pkg/daemon/ceph/client/filesystem.go#L324), but leaves the pools intact. Then during reinstall the only way to create the filesystem again on the same pools was to use --force. Would you agree that we shouldn't remove the filesystem during uninstall in the first place? Then we shouldn't need to ever use --force unless there really is a disaster recovery scenario.

**Comment by batrick** [comment]
I agree: do not remove the file system during uninstall. Then `--force `will no longer be necessary.

**Comment by ajarr** [comment]
@travisn just curious. is this what preserveFsOnDelete: True already does?
https://github.com/rook/rook/pull/6495/files#diff-e7e1952f91a34f216e61da44c952c796fc630097402dd4b06a1b75274b5bb837R132

**Comment by travisn** [comment]
@ajarr Good point, the filesystem should already be preserved by that flag, so we just need to remove the --force option. I see now that the preserve filesystem flag was added in v1.5, while the --force flag was added back in v1.2. So we probably wouldn't repro this issue where the force will be a problem on 1.5 or newer. Sounds like this was reported from Rook v1.4 (OCS 4.6), which wouldn't be preserving the filesystem.

**Comment by ajarr** [comment]
@travisn got it. So to get around this issue, rook v1.4 users would have to upgrade to v1.5 (or later) or backport https://github.com/rook/rook/pull/6495 ?

**Comment by travisn** [comment]
> @travisn got it. So to get around this issue, rook v1.4 users would have to upgrade to v1.5 (or later) or backport #6495 ?

Yes, and #6495 is rather large to backport at this point. This will only be hit if the filesystem CR is deleted, but the CephCluster CR is not deleted, which I'm not sure why that would happen in normal usage.

**Comment by ajarr** [comment]
makes sense. thanks!
