### ISSUE TITLE
Ceph: Dependencies: 1: track for CephClusters

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#8065]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Block deletion of a CephCluster when there are other Rook-Ceph resources in the same namespace

Design: [design/ceph/resource-dependencies.md](https://github.com/rook/rook/blob/master/design/ceph/resource-dependencies.md)

**What is use case behind this feature:**

**Environment**:

**Comment by mykaul** [comment]
The design link is giving me 404.

**Comment by leseb** [comment]
> The design link is giving me 404.

Fixed!

**Comment by Madhu-1** [comment]
@BlaineEXE Like we are checking the PVC for both cephfs and rbd are we consider kubernetes volumesnapshots also?
