### ISSUE TITLE
Ceph: Dependencies: 4: CephBlockPool/CephFilesystem -> PersistentVolume

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#8068]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Block deletion of a CephBlockPool or CephFilesystem when there is a PersistentVolume reliant on it

Design: [design/ceph/resource-dependencies.md](https://github.com/rook/rook/blob/master/design/ceph/resource-dependencies.md)

**What is use case behind this feature:**

**Environment**:

**Comment by Madhu-1** [comment]
@BlaineEXE looks like the Design link is broken.

**Comment by Madhu-1** [comment]
@BlaineEXE also need to consider volumesnapshots?

**Comment by parth-gr** [comment]
@BlaineEXE I was asking for this ticket, can I take this one next?

**Comment by leseb** [comment]
> @BlaineEXE I was talking about this ticket, can I work upon this one next?

Go for it.

**Comment by Madhu-1** [comment]
@BlaineEXE @leseb Instead of PV objects dont we need to rely on check the images/subvolumes in the pool as a user can still use blockPools for 3 things

* Static provisioning ( the image will be created in the pool first and when it's required they will create the PVC and PV objects)
* User can create storageclass with retain policy. even if the PVC and PV are deleted the rbd images will be left in the pool and its needs manual cleanup from the admin.
* The rook create ceph cluster might be getting used by some other kubernetes cluster for storage consumption?

If we can have any kind of flag to allow deletion if there are no PVC objects but rbd images are present.

**Comment by Madhu-1** [comment]
> To help flesh the implementation out, are there any cases where user data can be added to a CephFilesystem without subvolumes being created

Yes, even with static PVC users can mount the `/` Root of the filesystem and mount it to the application pods. 

> For such a case, do we know which methods we can use to see if the FS root is storing data?

Am not aware of such functionality, @kotreshhr can you please help here?

**Comment by kotreshhr** [comment]
Not sure about CephNFS, @ajarr could you help here ?

**Comment by ajarr** [comment]
> > To help flesh the implementation out, are there any cases where user data can be added to a CephFilesystem without >subvolumes being created? I believe there is a case where this could happen: a user could create a CephNFS via the CLI or >Dashboard and use the CephFilesystem root (/) to store NFS data that not in a subvolume. For such a case, do we know which >methods we can use to see if the FS root is storing data?
> 
> Not sure about CephNFS, @ajarr could you help here ?

You can check the CephFS paths and FS volume name exported by a ganesha service/cluster.  Execute the following to get detailed information about all the exports of a NFS cluster/service.
$ ceph nfs export ls <nfs-cluster-name> --detailed --format=json

e.g.
```
$ ceph nfs export ls ganesha --detailed --format=json
[
  {
    "export_id": 1,
    "path": "/",
    "cluster_id": "ganesha",
    "pseudo": "/cephfs",
    "access_type": "RW",
    "squash": "none",
    "security_label": true,
    "protocols": [
      4
    ],
    "transports": [
      "TCP"
    ],
    "fsal": {
      "name": "CEPH",
      "user_id": "nfs.ganesha.1",
      "fs_name": "a"
    },
    "clients": []
  }
]
```

Look at each of the each of export dictionary's ["path"] and ["fsal"]["fs_name"] to determine the exported path and its file system (aka FS volume). This however won't let you know whether an export has been mounted and data has been stored in the file system. To do that you need to mount the file system, and verify the contents.

**Comment by parth-gr** [comment]
@BlaineEXE any update, can we please have a discussion regarding this?

**Comment by BlaineEXE** [comment]
This is on my to-do list for NFS. Has this come up again elsewhere @parth-gr ?
