### ISSUE TITLE
Ceph: Dependencies: 5: CephObjectStore -> CephObjectStoreUser

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#8069]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Block deletion of a CephObjectStore when there is a CephObjectStoreUser reliant on it

Design: [design/ceph/resource-dependencies.md](https://github.com/rook/rook/blob/x/design/ceph/resource-dependencies.md)

**What is use case behind this feature:**

**Environment**:

**Comment by thotz** [comment]
@BlaineEXE: The design link is pointing to "Not found"
