### ISSUE TITLE
Remove deprecated FlexVolume driver

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#8076]
We have been using CSI as the default driver for quite a while now, and it is now at feature parity with the FlexVolume or better. We can now stop supporting the old FlexVolume driver.

@Madhu-1 are you able to confirm CSI is at parity with FlexVolume?

**Comment by Madhu-1** [comment]
Yes, all the functionalities provided by FlexVolume are present in cephcsi and even more features like snapshots clones etc and many other features are available in cephcsi. But there is no way to handle PVC created from FlexDriver from cephcsi.

**Comment by Madhu-1** [comment]
@BlaineEXE this means there will be no support for mounting the existing flexVolumes in the next release?

**Comment by BlaineEXE** [comment]
Migration steps: https://github.com/rook/rook/issues/4043

**Comment by travisn** [comment]
As proposed in #8084, the flex driver would be removed from Rook in v1.8 (targeted for Nov 2021). A conversion tool will be provided in the v1.7 timeframe as under discussion with #4043.
