### ISSUE TITLE
Check volumesnapshot before deleting ceph cluster

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#8080]
Currently, we have only check for the PVC before deleting the ceph cluster its also good to check for the volume snapshot objects before deleting the ceph cluster.

**Comment by yati1998** [comment]
@Madhu-1 As it's no more required, can we close this issue?

**Comment by Madhu-1** [comment]
Yes, this can be closed as rook does not allow us to delete the cluster if we have rbd images/ceph fs subvolumes in the cluster.
