### ISSUE TITLE
rook-cluster.yaml only one node exists in K8 config 

### ISSUE THREAD

**Issue by dylanjohnsonsfo** [rook/rook#811]
I have a cluster manifest as seen below but when I create it there is only one node in the config on my k8 cluster. 

Manifest to apply / applies successfully but only one node on the k8 cluster - 
##### MANIFEST that I am applying ##########
Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    nodes:
    - name: "ip-172-17-20-190"
      directories:         # specific directores to use for storage can be specified for each node
      - path: "/ha-storage"
    - name: "ip-172-17-20-190"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "/dev/xvdf"
      storeConfig:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: filestore
    - name: "ip-172-17-20-190"
next node
    nodes:
    - name: "ip-172-17-20-221"
      directories:         # specific directores to use for storage can be specified for each node
      - path: "/ha-storage"
    - name: "ip-172-17-20-221"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "/dev/xvdf"
      storeConfig:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: filestore
    - name: "ip-172****"
next node
    nodes:
    - name: "ip-172****"
      directories:         # specific directores to use for storage can be specified for each node
      - path: "/ha-storage"
    - name: "ip-172***"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "/dev/xvdf"
      storeConfig:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: filestore
    - name: "ip-172*** "

Running kubectl edit clusters <clustername> only shows one node #########

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: 2017-07-14T22:51:31Z
  name: rook
  namespace: rook
  resourceVersion: "560679"
  selfLink: /apis/rook.io/v1alpha1/namespaces/rook/clusters/rook
  uid: fae3261e-68e6-11e7-9d54-12b793ef7f0a
spec:
  dataDirHostPath: null
  storage:
    deviceFilter: null
    location: null
    metadataDevice: null
    nodes:
    - directories:
      - path: /ha-storage
      name: ip-172****
    - devices:
      - name: /dev/xvdf
      name: ip-172****
      storeConfig:
        storeType: filestore
    - name: ip-172****
    storeConfig:
      databaseSizeMB: 1024
      journalSizeMB: 1024
      storeType: filestore
    useAllDevices: true
    useAllNodes: false
  versionTag: master
~

**Comment by jbw976** [comment]
hi @dylanjohnsonsfo, I'm having trouble reading this issue because the formatting is corrupted.  Can you please edit your post using github's markdown so that I can be sure i'm readying exactly what you intended?  Markdown help is here: https://guides.github.com/features/mastering-markdown/

The 2 things I can tell for sure that should be updated are:
1. The full Cluster manifest file should be posted, it looks like you're starting at just the nodes section.
1. Any line beginning with a '#' char is going to be interpreted as a Header, not what you want.
1. Any code blocks should be surrounded by triple back ticks.  Example:

\```
code block goes here
\```

Thanks a lot for making sure we're all on the same page so we can help!
