### ISSUE TITLE
stuck during read from rbd

### ISSUE THREAD

**Issue by golgotow** [rook/rook#8121]
**Is this a bug report or feature request?**
* Bug Report

Hello,

Main problem is that write to rbd with fs ext4 or xfs works without problem, I tried to fill 50G rbd and was ok.
Problem is that during copy files from rbd to local computer for example, this operation stuck and give no output, no errors, only rbd is frozen for some period of time +- 10 min, then process of copy can be canceled via ctrl+c. 
I look for any advice where to look for problem ,what logs to check from rook ceph cluster.
During this stuck, cluster do not report any errors, ceph -s is still OK, no errors visible in dmesg where osd are hosted.

**Expected behavior:**
rbd to not stuck during read from filesystem

**How to reproduce it (minimal and precise):**
problem appeared on ubuntu 20.04 with kubernetes k3s on arm64 hardware rock pi 4
rock1          Ready    <none>                      8d    v1.21.1+k3s1   192.168.13.167   <none>        Ubuntu 20.04.2 LTS   4.4.154-112-rockchip-gfdb18c8bab17   containerd://1.4.4-k3s2
rock2          Ready    <none>                      8d    v1.21.1+k3s1   192.168.13.166   <none>        Ubuntu 20.04.2 LTS   4.4.154-112-rockchip-gfdb18c8bab17   containerd://1.4.4-k3s2
rock3          Ready    <none>                      8d    v1.21.1+k3s1   192.168.13.165   <none>        Ubuntu 20.04.2 LTS   4.4.154-112-rockchip-gfdb18c8bab17   containerd://1.4.4-k3s2

Linux rock1 4.4.154-112-rockchip-gfdb18c8bab17 #1 SMP Thu Jan 21 04:50:13 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

rook installed on nvme devices, host network in use in this scenario, but works same on default rook cluster.

On this hardware problem appear every time I install cluster, before I tried to work on it with rook, this hardware provide me heketi glusterfs without any visible problems.

root@rock1:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Linux rock1 4.4.154-112-rockchip-gfdb18c8bab17 #1 SMP Thu Jan 21 04:50:13 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

rook version
rook: 0
go: go1.16.3

ceph -v --cluster rook
ceph version 15.2.11 (e3523634d9c2227df9af89a4eac33d16738c49cb) octopus (stable)

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7+k3s1", GitCommit:"aa768cbdabdb44c95c5c1d9562ea7f5ded073bc0", GitTreeState:"clean", BuildDate:"2021-05-20T01:07:13Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

k3s , same behavior on microk8s and k8s from rancher

[root@rook-ceph-tools-78cdfd976c-j9bjw /]# ceph health
HEALTH_OK

Best regards

**Comment by golgotow** [comment]
[cluster.yaml.zip](https://github.com/rook/rook/files/6642447/cluster.yaml.zip)

**Comment by travisn** [comment]
@golgotow So the rbd reads and writes are ok when writing within the volume? The issue only happens when you are reading from rbd to some external host? What command are you using? It seems related to that instead of something inside rbd.

**Comment by golgotow** [comment]
I will try with cephfs and back , now all test was via map rbd , format to ext4 or xfs and then mount and rsync files in both directions.
Same behavior is when rook mount pv from sc to pod, also write works, but when comes to read, this operation stuck after short time of start, and I have no idea where to look for any tip,

**Comment by golgotow** [comment]
there is exactly same behavior, transfer from cephfs to local mount starts, and stuck in short time +- 10 sec, during this via ceph -s no alerts or anything is pointed.
