### ISSUE TITLE
 set numreplicas for provisioner pods

### ISSUE THREAD

**Issue by hackaholic** [rook/rook#8153]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
set numreplicas for provisioner pods

**What is use case behind this feature:**
 If the no of nodes is more than one but still one want provisioner pods replica to be 1.
**Environment**:
K8s environment
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
Setup: 1 master , 1 worker
[root@pwconfig-k8s-master0 ~]# kubectl get nodes
NAME                        STATUS   ROLES    AGE   VERSION
k8s-test-worker0   Ready    <none>   17h   v1.18.1
k8s-master0        Ready    master   17h   v1.18.1
k8s-worker0        Ready    <none>   17h   v1.18.1

**Comment by Madhu-1** [comment]
@hackaholic why you think it's a useful feature? Can you please provide more details?

**Comment by hackaholic** [comment]
@Madhu-1 numreplicas for provisioner pods is not configurable, 
It can be made configurable, Like in my case I just wanted to run only one replica.

**Comment by travisn** [comment]
@hackaholic Can you expand on the scenario? Is the goal to run the minimal resources in the cluster instead of ensuring provisioning is HA? Or something else?

**Comment by hackaholic** [comment]
@travisn yes the goal is to run the minimum resources in the cluster without HA
