### ISSUE TITLE
Upgrading Chart from v1.5 to v1.6 fails on CRD preserveUnknownFields

### ISSUE THREAD

**Issue by tareqhs** [rook/rook#8154]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Chart fails to install when upgrading from v1.5.7 to v1.6.5

**Expected behavior:**

**How to reproduce it (minimal and precise):**
Existing v1.5.7 chart installed and RBD data exists so an upgrade is necessary (not clean installation). When upgrading to v1.6.5 some CRDs fail to apply with following error:
> CustomResourceDefinition.apiextensions.k8s.io "cephclusters.ceph.rook.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema

This relevant doc does not help because helm is being used https://github.com/rook/rook/pull/7757

**Environment**:
* Rook version: v1.5.7 -> v1.6.5
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version: 1.20.6
* Kubernetes cluster type: Gardener

**Comment by subhamkrai** [comment]
@tareqhs similar to this #7659

**Comment by subhamkrai** [comment]
@tareqhs did you try this https://github.com/rook/rook/issues/7659#issuecomment-849351883

**Comment by tareqhs** [comment]
thanks @subhamkrai this helped but this is a very complicated workaround because we try to maintain helm-only installations

**Comment by subhamkrai** [comment]
@travisn @BlaineEXE is there anything we can do to automate?

**Comment by travisn** [comment]
> @travisn @BlaineEXE is there anything we can do to automate?

We haven't found how to automate this yet. The change to the auto-generated CRDs has made this a challenge. 

@tareqhs To clarify, the workaround in #7659 does work for you? It would be a one-time workaround, not needed in future upgrades, but it's certainly something we would like to automate.

**Comment by tareqhs** [comment]
@travisn yes it worked for me
