### ISSUE TITLE
PrometheusRule CephMonQuorumAtRisk rule is wrong

### ISSUE THREAD

**Issue by martin31821** [rook/rook#8156]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The CephMonQuorumAtRisk rule is wrong. It alerts in case of a single-mon deployment and alerts too late for five or more mons.

**Expected behavior:**
1 mon: should not alert at all
5 mons: should alert when 3/5 are reachable, alerts at two mons reachable (quorum lost)
7 mons: should alert when 4/7 are alive, alerts at two mons reachable (quorum lost)

**How to reproduce it (minimal and precise):**
Spawn a five mon deployment, kill two mons, no alert is firing.
The alert rule deployed is: 
`count(ceph_mon_quorum_status{job=\"rook-ceph-mgr\"} == 1) <= ((count(ceph_mon_metadata{job=\"rook-ceph-mgr\"}) % 2) + 1)\n` which always evaluates to one or two on the right side regardless of the mon count.
I think it should be:
`count(ceph_mon_quorum_status{job=\"rook-ceph-mgr\"} == 1) <= (floor(count(ceph_mon_metadata{job=\"rook-ceph-mgr\"}) / 2) + 1)\n`.

Also for the case of a single-mon cluster, I think this should not be deployed at all.

**File(s) to submit**:

**Environment**:
- Independent from the environment. 
- Affetcs all rook versions

**Comment by leseb** [comment]
@anmolsachan PTAL

**Comment by anmolsachan** [comment]
@leseb Ack, Please assign this to me, I don't see the option. I will look into it.
