### ISSUE TITLE
Feature request: add toolbox pod to helm chart

### ISSUE THREAD

**Issue by jhoblitt** [rook/rook#8187]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Create the toolbox pod which is used from some examples (and is handle to have running).

**What is use case behind this feature:**
The toolbox is helpful for administration and manual status checks outside of the operator.

**Comment by travisn** [comment]
@jhoblitt The toolbox can be enabled with the new [cluster helm chart](https://rook.github.io/docs/rook/v1.6/helm-ceph-cluster.html). Does that work for you? The chart is just considered experimental until v1.7.

**Comment by jhoblitt** [comment]
@travisn I'm afraid I was ignorant as to the purpose of the cluster helm chart.  I noticed that it appeared in the repo but I didn't... and I still don't... understand how it is different than the original flavor chart.  Is the intent that it will completely replace the existing stable chart?  Is there a summary anywhere of what has changed or does one need to inspect the templates?

**Comment by jhoblitt** [comment]
Aww, I just looked at the chart... it is clearly not a replacement, just automation for creation of a cephcluster resource.  I see that there is `rook-ceph-tools` in `deployment.yaml`.  It looks like that covers this use case but I have not tested it yet.

**Comment by travisn** [comment]
> Aww, I just looked at the chart... it is clearly not a replacement, just automation for creation of a cephcluster resource. I see that there is `rook-ceph-tools` in `deployment.yaml`. It looks like that covers this use case but I have not tested it yet.

Correct, it is a new chart and does not replace the other chart. The CRDs must be defined in a different chart from the CephCluster CR.

**Comment by jhoblitt** [comment]
Is there a plan to publish a beta version of the `rook-ceph-cluster` chart? It does not appear to be published in the repo listed in the docs: https://github.com/rook/rook/blob/master/Documentation/helm-ceph-cluster.md

```bash
-bash-4.2$ helm search repo rook-release --devel 
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION                                       
rook-release/rook-ceph	v1.6.6       	           	File, Block, and Object Storage Services for yo...
-bash-4.2$ 
```

**Comment by travisn** [comment]
In v1.7 it's planned to be published to the `release` channel. In the meantime, it's in the `master` channel as found in [the release docs](https://rook.github.io/docs/rook/v1.6/helm-ceph-cluster.html#master-channel), which are slightly different from the master doc you referenced, which will become the v1.7 doc when it is released.

**Comment by jhoblitt** [comment]
@travisn Thank you yet again. I'm giving it a try now.

**Comment by jhoblitt** [comment]
I'm closing as this feature exists but there seems to be minor template bug. See #8251
