### ISSUE TITLE
Document how to migrate existing TPR's to CRD's

### ISSUE THREAD

**Issue by DanKerns** [rook/rook#819]
Version 1.7.1 removed support for TPR's. Rook needs to migrate any existing TPR's on a cluster to CRD's.

**Comment by jbw976** [comment]
We should document how a user would upgrade their Rook TPRs to CRDs after they have upgraded their Kubernetes cluster to 1.6 to 1.7+.

**Comment by paha** [comment]
Kubernetes has excellent [documentation](https://kubernetes.io/docs/tasks/access-kubernetes-api/migrate-third-party-resource/) on TPR to CRD migration. I don't think we need to document such migration for Rook.

A small section linking to the Kubernetes documentation can be added to the Rook upgrade documentation. Alternatively we can simply refer to this issue, which I think might be sufficient.
