### ISSUE TITLE
Helm test suites failing in master 

### ISSUE THREAD

**Issue by travisn** [rook/rook#8202]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The helm suites are failing in master since #8182 merged. As seen in the [first build after the merge](https://github.com/rook/rook/actions/runs/970549954):

```
Run tests/scripts/minikube.sh helm
+ tests/scripts/minikube.sh helm
 copying rook image for helm
X Exiting due to ENV_DRIVER_CONFLICT: 'none' driver does not support 'minikube docker-env' command
Error: Process completed with exit code 1.
```

@subhamkrai Did we miss something in that merge? Strange that the CI was green before merge and now failing.

**Expected behavior:**
The helm suites to pass

**Comment by subhamkrai** [comment]
hmm...right. For PRs, it will green as I removed the changes from there but missed to remove the changes for the release. here

https://github.com/subhamkrai/rook/blob/f90050c5b2dbe528b4a2bdb8c87834a66c9ae949/.github/workflows/integration-tests-on-release.yaml#L83-L85

I'll revert this too
