### ISSUE TITLE
ceph: mark OSD as DOWN on node shutdown or reboot as maintenance

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#8209]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

If we shutdown or reboot a node as maintenance, OSDs existing in this node will be marked as `DOWN` after a long time (15mins by default). During this time, I/Os, which primary replica is in these OSDs, will be blocked. This problem can be avoided if mark these OSDs as `DOWN` as soon as a node shutdown/reboot.

**Comment by ymmt2005** [comment]
I'd add some more contexts.

In our MySQL operator, the controller watches Pods, and when it detects a Pod is being deleted
(i.e. `metadata.deletionTimestapm != nil`), it automatically starts a switchover operation.

Each Pod has a preStop hook that executes `sleep 5` before sending SIGTERM to containers to
allow the controller to do the switchover gracefully.

When we want to reboot a Node, we drain Pods first.  Draining Pods is essentially equal to
deleting Pods, so our MySQLCluster can avoid sudden disruptions while maintaining Nodes.

It'd be great if Rook can do the same for OSD pods.

**Comment by travisn** [comment]
> If we shutdown or reboot a node as maintenance, OSDs existing in this node will be marked as DOWN after a long time (15mins by default). During this time, I/Os, which primary replica is in these OSDs, will be blocked. This problem can be avoided if mark these OSDs as DOWN as soon as a node shutdown/reboot.

@satoru-takeuchi Ceph is expected to mark OSDs `down` very quickly (seconds) after they go offline. The OSDs have [health checks](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-down) against one another to detect these conditions. Have you perhaps set `nodown` or `noout` in the cluster?

> When we want to reboot a Node, we drain Pods first. Draining Pods is essentially equal to
deleting Pods, so our MySQL clusters can avoid sudden disruptions while maintaining Nodes.

> It'd be great if Rook can do the same for OSD pods.

When a node is drained, if the OSDs are `portable: true` (using `storageClassDeviceSets`), the OSDs are expected to move to another node automatically and reduce downtime. This assumes another node is available that satisfies the placement. If the OSDs are `portable: false` or are not using device sets, then we rely on Ceph to mark the OSDs down with Ceph's internal OSD health checks. Rook should not have to do this.

**Comment by satoru-takeuchi** [comment]
@travisn Thank you for your comment. I'll confirm my configuration and will respond later.

**Comment by sp98** [comment]
> @satoru-takeuchi Ceph is expected to mark OSDs `down` very quickly (seconds) after they go offline. The OSDs have [health checks](https://docs.ceph.com/en/latest/rados/operations/health-checks/#osd-down) against one another to detect these conditions. Have you perhaps set `nodown` or `noout` in the cluster?

`noout` could have been set on the failure domain, if podDisruptionBudget is enabled for the cluster.

**Comment by satoru-takeuchi** [comment]
@travisn 

> The OSDs have health checks against one another to detect these conditions. Have you perhaps set nodown or noout in the cluster?

I checked my cluster but both flags are not set.

In addition, I failed to reproduce this problem by scaling down the replicas of an OSD pod, or by surprise node shutdown. I'll try this again later.

BTW, Could you tell me why `noout` afftects the transition `UP` and `DOWN? I thought it's only related to the transition between `IN` and `OUT`

> noout could have been set on the failure domain, if podDisruptionBudget is enabled for the cluster.

@sp98 Thank you for letting me know! Does it mean `osdMaintenanceTimeout` related behavior? 

https://github.com/rook/rook/blob/master/Documentation/ceph-cluster-crd.md

**Comment by travisn** [comment]
`noout` would not affect the `down` status, you're correct. 
In my minikube test cluster with 3 OSDs, if I stop one of the OSDs it immediately is marked down (no longer marked `up` in the `ceph osd status`), so I'm not clear why ceph wouldn't be marking your osd as down.

**Comment by satoru-takeuchi** [comment]
@travisn @sp98 I found that PDB is not set in my cluster. So some pgs might be less than `min_osds` during node reboot. I close this PR for now.
