### ISSUE TITLE
accidentally deleted rook-ceph-mgr-dashboard service

### ISSUE THREAD

**Issue by fzhan** [rook/rook#8217]
**Is this a bug report or feature request?**
* Feature Request
* This rook-ceph-mgr-dashboard service does not have a yaml file, if it is accidentally deleted, ceph operator does not recreate this service, and there's no example yaml to restore it.

**What should the feature do:**
include an example of the service in yaml file

**What is use case behind this feature:**
in case of accidental deletion

**Environment**:
Ubuntu 20.04, Microk8s

**Comment by travisn** [comment]
@fzhan Restarting the operator should result in a full reconcile and the dashboard service will be created again.
