### ISSUE TITLE
after one node of cluster is rebooted health status is Module 'devicehealth' has failed: [errno 110] RADOS timed out (error connecting to the cluster)

### ISSUE THREAD

**Issue by hezise** [rook/rook#8220]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

after one of the node was rebooted I saw that all is up but the status was health_err with description Module 'devicehealth' has failed: [errno 110] RADOS timed out (error connecting to the cluster)

after I rebooted the mgr health became OK
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).
attached
[mgr-issue.zip](https://github.com/rook/rook/files/6740884/mgr-issue.zip)

**Environment**:
* OS (e.g. from /etc/os-release):
* NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):
* Linux adccmulti-40-02 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* 
* Cloud provider or hardware configuration:
* VMWare
* 
* Rook version (use `rook version` inside of a Rook Pod):
* rook: v1.5.8
go: go1.13.8

* Storage backend version (e.g. for ceph do `ceph -v`):
* ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)
* 
* Kubernetes version (use `kubectl version`):
* Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Kubespray 2.15
* 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
* attached

**Comment by travisn** [comment]
So the cluster is healthy again now? From the operator log it looks like mon quorum was down for a while, but then looks like it recovered again since the `ceph status` is healthy from the toolbox. Since the ceph health warning is cleared up now, is there anything remaining to investigate?

**Comment by hezise** [comment]
currently it's healthy again.
I couldn't understand from the logs what is causing it.
I also tried to understand how to debug it.
is there a flag I can set that will restart the MGR in such case?

**Comment by travisn** [comment]
The mgr pod has a liveness probe that will restart it if it fails. But this is different from the health warning that is raised by the mgr.

**Comment by hezise** [comment]
I currently testing ha.
I'm shutting down servers and verify that all is still up then turn it on again and verify that it has recovered and everything is fine again and this is where I found the health_err. it stayed in that state for a few hours until I rebooted the mgr.
is there something I can check when this error occurs?
I prefer not to reset the mgr just like that.

**Comment by travisn** [comment]
The fundamental issue seems like the mons were out of quorum, not sure the health warning and the mgr are related to that. Did you only have a single node down? Could there have been two mons on the same node? You have `mon.allowMultiplePerNode: false` in the cluster CR, right?

**Comment by hezise** [comment]
Hi,
Yes I had only one node down.
and regarding the second question the answer is yes
