### ISSUE TITLE
rook external on pi4, no csi driver

### ISSUE THREAD

**Issue by golgotow** [rook/rook#8271]
Hello,

cluster microk8s 1.20.7, deployed on raspberry pi 4 8G with 3 nodes.

root@rpi8g-1:~# kubectl get nodes
NAME      STATUS   ROLES    AGE    VERSION
rpi8g-1   Ready    <none>   118d   v1.20.7-34+319a3a2dbb86f2
rpi8g-3   Ready    <none>   12d    v1.20.7-34+319a3a2dbb86f2
rpi8g-2   Ready    <none>   12d    v1.20.7-34+319a3a2dbb86f2

root@rpi8g-1:~# uname -a
Linux rpi8g-1 5.4.0-1038-raspi #41-Ubuntu SMP PREEMPT Thu Jun 17 14:14:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

root@rpi8g-1:~# kubectl get pods -n rook-ceph
NAME                                            READY   STATUS    RESTARTS   AGE
rook-ceph-operator-75c6d6bbfc-5scp9             1/1     Running   0          51m
csi-rbdplugin-provisioner-687cf777ff-57b4b      6/6     Running   0          40m
csi-cephfsplugin-provisioner-78d66674d8-h4689   6/6     Running   0          40m
csi-rbdplugin-qm6rd                             3/3     Running   0          31m
csi-cephfsplugin-57t62                          3/3     Running   0          31m
csi-rbdplugin-ssgcd                             3/3     Running   0          31m
csi-cephfsplugin-xnk89                          3/3     Running   0          31m
csi-rbdplugin-provisioner-687cf777ff-rx2f4      6/6     Running   0          24m
csi-cephfsplugin-provisioner-78d66674d8-prlt7   6/6     Running   0          24m
csi-cephfsplugin-wvgr9                          3/3     Running   0          24m
csi-rbdplugin-s6sgk                             3/3     Running   0          24m

root@rpi8g-1:~# kubectl get CephCluster -A
NAMESPACE            NAME                 DATADIRHOSTPATH   MONCOUNT   AGE   PHASE       MESSAGE                          HEALTH      EXTERNAL
rook-ceph-external   rook-ceph-external                                40m   Connected   Cluster connected successfully   HEALTH_OK   true
root@rpi8g-1:~# kubectl get csidriver 
NAME                            ATTACHREQUIRED   PODINFOONMOUNT   MODES        AGE
driver.longhorn.io              true             true             Persistent   21d
rook-ceph.rbd.csi.ceph.com      true             false            Persistent   39m
rook-ceph.cephfs.csi.ceph.com   true             false            Persistent   39m

All looks present, but when trying to get pv mounted into container, we end with below message from pod description.

  Type     Reason                  Age              From                     Message
  ----     ------                  ----             ----                     -------
  Normal   Scheduled               7s               default-scheduler        Successfully assigned default/test-5dcc956f5-mm67r to rpi8g-1
  Normal   SuccessfulAttachVolume  6s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-d6353694-918d-4b8f-8d34-f0a3c467f468"
  Warning  FailedMount             1s (x4 over 5s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-d6353694-918d-4b8f-8d34-f0a3c467f468" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.rbd.csi.ceph.com not found in the list of registered CSI drivers

Can you advice if this is bug or some problem on raspberry pi 4 build ?

Best regards

**Comment by Madhu-1** [comment]
https://github.com/rook/rook/issues/6772 or https://github.com/rook/rook/issues/6155#issuecomment-738786474 should help

**Comment by golgotow** [comment]
thank you
