### ISSUE TITLE
OSDs failed to upgrade to 1.6.7 due to disabling the insecure global id reclaim prematurely

### ISSUE THREAD

**Issue by ecusnir** [rook/rook#8307]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After setting ceph version 15.2.13 from 15.2.7, all the pgs become inactive. This happens after the monitors and managers are upgraded.

**Expected behavior:**
It is expected that all the ceph components to be upgraded without disruptions.

**How to reproduce it (minimal and precise):**

I have created a new cluster using rook v1.6.7 and ceph v15.2.7-20201201 with encrypted disks. After updating the ceph image in the CephCluster CR, the mons and mgrs are upgraded. Next, the pgs become inactive and the OSDs are not upgraded.
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
[cluster.txt](https://github.com/rook/rook/files/6809434/cluster.txt)
* Operator's logs, if necessary
[operator-logs.txt](https://github.com/rook/rook/files/6809436/operator-logs.txt)
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
 Ubuntu 20.04.2 LTS
* Kernel (e.g. `uname -a`):
5.4.0-70-generic
* Cloud provider or hardware configuration:
 on-prem
* Rook version (use `rook version` inside of a Rook Pod):
 v1.6.7
* Storage backend version (e.g. for ceph do `ceph -v`):
 15.2.7
* Kubernetes version (use `kubectl version`):
 v1.17.13
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
 on-prem
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN Reduced data availability: 33  pgs inactive

**Comment by travisn** [comment]
@ecusnir What does the full `ceph status` show in the toolbox? 

I wonder if the insecure global id connections were disabled prematurely before the OSDs were upgrades. See [this issue](https://github.com/rook/rook/issues/7746#issuecomment-859129752) if it needs to be reenabled for the upgrade to proceed.

**Comment by ecusnir** [comment]
```
[root@rook-ceph-tools-5b5d6b584-zlx5v /]# ceph -s -w
  cluster:
    id:     4d591369-efb1-484a-a53c-cc8e722555aa
    health: HEALTH_WARN
            Reduced data availability: 33 pgs inactive

  services:
    mon: 3 daemons, quorum a,b,c (age 4m)
    mgr: a(active, since 3m), standbys: b
    osd: 28 osds: 28 up (since 8m), 28 in (since 3h)

  data:
    pools:   2 pools, 33 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             33 unknown


2021-07-13T14:48:28.170229+0000 mon.b [INF] mon.b calling monitor election
2021-07-13T14:48:28.177963+0000 mon.a [INF] mon.a calling monitor election
2021-07-13T14:48:33.180654+0000 mon.a [INF] mon.a is new leader, mons a,b in quorum (ranks 0,1)
2021-07-13T14:48:33.188318+0000 mon.a [WRN] Health check failed: 1/3 mons down, quorum a,b (MON_DOWN)
2021-07-13T14:48:33.195349+0000 mon.a [WRN] Health detail: HEALTH_WARN 1/3 mons down, quorum a,b; Reduced data availability: 33 pgs inactive
2021-07-13T14:48:33.195370+0000 mon.a [WRN] [WRN] MON_DOWN: 1/3 mons down, quorum a,b
2021-07-13T14:48:33.195376+0000 mon.a [WRN]     mon.c (rank 2) addr [v2:10.200.68.193:3300/0,v1:10.200.68.193:6789/0] is down (out of quorum)
2021-07-13T14:48:33.195382+0000 mon.a [WRN] [WRN] PG_AVAILABILITY: Reduced data availability: 33 pgs inactive
2021-07-13T14:48:33.195387+0000 mon.a [WRN]     pg 1.0 is stuck inactive for 5m, current state unknown, last acting []
2021-07-13T14:48:33.195432+0000 mon.a [WRN]     pg 3.0 is stuck inactive for 5m, current state unknown, last acting []
2021-07-13T14:48:33.195438+0000 mon.a [WRN]     pg 3.1 is stuck inactive for 5m, current state unknown, last acting []
...
```
This is how the logs were looking like. 

I have checked that the clients are using the latest CSI version. This was a new rook deployment I used only for testing the upgrade.

**Comment by travisn** [comment]
@ecusnir Have all the OSD pods been upgraded now? (What does the ceph version label on the OSD deployments show?) If they are not upgraded, I still suspect the Insecure global id issue which I linked in the previous comment.

**Comment by ecusnir** [comment]
The OSDs were not upgraded because the operator detected that the cluster is unhealthy. 

I will try the fix in the issue mentioned above and come back with more details.

**Comment by ecusnir** [comment]
I managed to successfully upgrade the ceph version by adding to rook-config-override the setting:
```
  config: |
    [mon]
    auth_allow_insecure_global_id_reclaim = true
```
When I tried doing this using the toolbox, the operator was overwriting the value. Muting the alert didn't help, because it kept reappearing. Also, the alert can't be muted if it isn't triggered, so it is hard to prevent this issue using the toolbox.

In my opinion, the rook-operator should not change `auth_allow_insecure_global_id_reclaim` to false if the OSDs haven't been upgraded. This causes the OSDs to stop communicating with the mons, thus disrupting the whole cluster.

**Comment by travisn** [comment]
It is expected that the operator wouldn't disable the allow insecure global id setting if any clients are still actively connected like the OSDs. The OSDs were up during the upgrade? If they were down I could see why the ceph wouldn't report any active clients still need in upgrade. In any case, agreed that the operator should at an extra version check ensure the daemons are upgraded before disabling that setting.

**Comment by ecusnir** [comment]
The OSD pods were running when the flag was changed. The only visible problem that appears is the pgs becoming unknown, which I suspect is caused when the operator sets auth_allow_insecure_global_id_reclaim to false and the OSDs stop communicating with the upgraded mons.
