### ISSUE TITLE
Update packages version

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#8308]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
These warnings are frequent:

``` 
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

2592 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding

Warning: certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest

```
**Expected behavior:**

No such warnings should be displayed.

**How to reproduce it (minimal and precise):**

1. Setup Rook on K8s version v1.21+
2. Observe the operator logs.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.6.7
* Storage backend version (e.g. for ceph do `ceph -v`): 
* Kubernetes version (use `kubectl version`): v1.21
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
> rbac.authorization.k8s.io/v1beta1

What version of Rook was running? I don't see this upstream, perhaps it was an older downstream version? The other two examples look like a valid issue.

**Comment by parth-gr** [comment]
> > rbac.authorization.k8s.io/v1beta1
> 
> What version of Rook was running? I don't see this upstream, perhaps it was an older downstream version? The other two examples look like a valid issue.

I founded it on the GitHub action CI.
