### ISSUE TITLE
Flakiness in the CI on CephObjectStores

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#8309]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Integration test CephSmokeSuite fails with an error :
``` === CONT TestCephSmokeSuite/TestObjectStorage_SmokeTest
ceph_base_object_test.go:202:
	Error Trace:	ceph_base_object_test.go:202
	Error: 	Not equal:
	 	expected: "Connected"
	 	actual : "Failure"
	 	
	 	Diff:
	 	--- Expected
	 	+++ Actual
	 	@@ -1,2 +1,2 @@
	 	-(v1.ConditionType) (len=9) "Connected"
	 	+(v1.ConditionType) (len=7) "Failure"
	 	
	Test: 	TestCephSmokeSuite/TestObjectStorage_SmokeTest
 ```

**Expected behavior:**

Integration test CephSmokeSuite should run as expected.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):1.6.7
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):1.21
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by subhamkrai** [comment]
@parth-gr ci is failing on `CephHelmSuite` or `CephSmokeSuite`? I see they are failing in `CephSmokeSuite`.

**Comment by parth-gr** [comment]
> @parth-gr ci is failing on `CephHelmSuite` or `CephSmokeSuite`? I see they are failing in `CephSmokeSuite`.

Yes, Updated the test name

**Comment by parth-gr** [comment]
The frequent failure in CI is because of [verify CephObjectStore status](https://github.com/rook/rook/blob/38c4d524e6dbd8d0845dbc3f58f000a6480a807c/tests/integration/ceph_base_object_test.go#L192) test run, 
In this line [202](https://github.com/rook/rook/blob/38c4d524e6dbd8d0845dbc3f58f000a6480a807c/tests/integration/ceph_base_object_test.go#L202) is throwing error.
It's because we are checking `ConditionType` to "connected"  but sometimes it is not being created and showing "Failure".
