### ISSUE TITLE
Rook 1.6.7 running on fresh kubeadm-provisioned k8s fails to reconcile objectStore CR. 

### ISSUE THREAD

**Issue by birdiesanders** [rook/rook#8318]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rook operator logs this error when an objectStore CR is applied to the cluster.

`
2021-07-14 20:24:03.144365 E | ceph-object-controller: failed to reconcile failed to create object store deployments: failed to configure multisite for object store: failed create ceph multisite for object-store "demo-store": radosgw-admin realm get failed with code -1, for reason "": signal: interrupt`

**Expected behavior:**
objectStore CR application should spin up rgw deployment

**How to reproduce it (minimal and precise):**

Provision a basic k8s cluster using kubeadm on ubuntu 20.04, install flannel, apply the objectStore CR from the documentation. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
`
2021-07-14 20:24:03.144365 E | ceph-object-controller: failed to reconcile failed to create object store deployments: failed to configure multisite for object store: failed create ceph multisite for object-store "demo-store": radosgw-admin realm get failed with code -1, for reason "": signal: interrupt`

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04
* Kernel (e.g. `uname -a`): 5.4.0-77-generic
* Cloud provider or hardware configuration: KVM virtual machine
* Rook version (use `rook version` inside of a Rook Pod): 1.6.7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.2 (e8f22dde28889481f4dda2beb8a07788204821d3) pacific (stable)
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): 
 cluster:
    id:     c0e66cee-9c7c-4f2d-b43e-afdeb9d51058
    health: HEALTH_WARN
            Reduced data availability: 113 pgs inactive
            6 pool(s) have no replicas configured
            OSD count 0 < osd_pool_default_size 3
 
  services:
    mon: 3 daemons, quorum a,b,c (age 2h)
    mgr: a(active, since 2h)
    osd: 0 osds: 0 up, 0 in
 
  data:
    pools:   9 pools, 113 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             113 unknown

**Comment by travisn** [comment]
@birdiesanders The issue is that you don't have any OSDs. From the ceph status:
```
osd: 0 osds: 0 up, 0 in
```

The object store cannot complete configuration until there are three osds across different nodes. See [this topic](https://rook.github.io/docs/rook/v1.6/ceph-common-issues.html#osd-pods-are-not-created-on-my-devices) to create OSDs.
