### ISSUE TITLE
after one node is powered off and powered on sometimes it fails to mount pv

### ISSUE THREAD

**Issue by hezise** [rook/rook#8333]
we are testing stability and recovery.
one of the test we do is powering off one of the nodes and after a while powering it back on.
we have 2 topologies:

- all nodes are in the same network
- nodes are located at different subnets

we've noticed that sometimes where nodes are located at different subnets one of the pods stays in init state and one in Terminating state.  looking at the description, I get
Warning  FailedMount  107s (x474515 over 3d20h)  kubelet  MountVolume.MountDevice failed for volume "pvc-f6eafdba-e441-465a-bcfa-192dd742f1ad" : rpc error: code = Internal desc = rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f6eafdba-e441-465a-bcfa-192dd742f1ad/globalmount: permission denied

try to perform ls to that path I'm getting the following:

s -ltr /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f6eafdba-e441-465a-bcfa-192dd742f1ad/
ls: cannot access '/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f6eafdba-e441-465a-bcfa-192dd742f1ad/globalmount': Permission denied
total 4
d????????? ? ?    ?      ?            ? globalmount
-rw-r--r-- 1 root root 138 Jul 18 10:15 vol_data.json

while on other node it's ok:
ls -ltr /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f6eafdba-e441-465a-bcfa-192dd742f1ad/
total 4
drwxrwxrwx 1 root root   0 Jul 11 12:56 globalmount
-rw-r--r-- 1 root root 138 Jul 12 05:12 vol_data.json

looking at csi-cephfsplugin log I can see 
E0718 10:21:39.692364       1 nodeserver.go:117] ID: 1494825 Req-ID: 0001-0009-rook-ceph-0000000000000001-6ad53685-e247-11eb-8e14-4229ad9f9489 stat failed: rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f6eafdba-e441-465a-bcfa-192dd742f1ad/globalmount: permission denied
E0718 10:21:39.692418       1 utils.go:136] ID: 1494825 Req-ID: 0001-0009-rook-ceph-0000000000000001-6ad53685-e247-11eb-8e14-4229ad9f9489 GRPC error: rpc error: code = Internal desc = rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f6eafdba-e441-465a-bcfa-192dd742f1ad/globalmount: permission denied
E0718 10:21:39.752790       1 utils.go:136] ID: 1494826 Req-ID: 0001-0009-rook-ceph-0000000000000001-6ad53685-e247-11eb-8e14-4229ad9f9489 GRPC error: rpc error: code = Internal desc = an error (exit status 32) occurred while running umount args: [/var/lib/kubelet/pods/a6aa5755-3aa8-40c4-aaa9-8313db683c4d/volumes/kubernetes.io~csi/pvc-f6eafdba-e441-465a-bcfa-192dd742f1ad/mount]

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):
* Linux node1 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* 
* Cloud provider or hardware configuration:
* VW
* 
* Rook version (use `rook version` inside of a Rook Pod):
* rook: v1.5.8
go: go1.13.8

* Storage backend version (e.g. for ceph do `ceph -v`):
* ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)
* 
* Kubernetes version (use `kubectl version`):
* Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubespray 2.15

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

cluster:
    id:     07dc577c-85b1-450a-8fa4-bc76e64c8c94
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,e (age 3d)
    mgr: a(active, since 6d)
    mds: shared-storage:1 {0=shared-storage-a=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 3d), 3 in (since 3d)
 
  data:
    pools:   6 pools, 257 pgs
    objects: 129.10k objects, 447 GiB
    usage:   898 GiB used, 314 GiB / 1.2 TiB avail
    pgs:     257 active+clean
 
  io:
    client:   13 KiB/s rd, 37 MiB/s wr, 4 op/s rd, 230 op/s wr

**Comment by Rakshith-R** [comment]
hey @hezise , 
Can you try running cephcsi v3.3.0 by changing it here https://github.com/rook/rook/blob/b65e088ec3061f51fe146a5b0adbe4f4c9736cf6/cluster/examples/kubernetes/ceph/operator.yaml#L75
And this to true, if it throws (`unsupported version` in operator logs)
https://github.com/rook/rook/blob/b65e088ec3061f51fe146a5b0adbe4f4c9736cf6/cluster/examples/kubernetes/ceph/operator.yaml#L71
There was a bug related to 
`E0718 10:21:39.752790 1 utils.go:136] ID: 1494826 Req-ID: 0001-0009-rook-ceph-0000000000000001-6ad53685-e247-11eb-8e14-4229ad9f9489 GRPC error: rpc error: code = Internal desc = an error (exit status 32) occurred while running umount args: [/var/lib/kubelet/pods/a6aa5755-3aa8-40c4-aaa9-8313db683c4d/volumes/kubernetes.io~csi/pvc-f6eafdba-e441-465a-bcfa-192dd742f1ad/mount]`
https://github.com/ceph/ceph-csi/issues/1860 which has a fix in cephcsi v3.3.0 
And see if you encounter the same error.

**Comment by hezise** [comment]
Hey @Rakshith-R ,
I'll schedule this.
just one question, shouldn't 3.3.1 include 3.3.0?

**Comment by Rakshith-R** [comment]
> Hey @Rakshith-R ,
> I'll schedule this.
> just one question, shouldn't 3.3.1 include 3.3.0?

@hezise 
Yes cephcsi `v3.3.1` also has the fix but it may throw `Mons are allowing insecure global_id reclaim` (not entirely sure though) from this issue https://github.com/rook/rook/issues/7746. 
You can use `v3.3.1` and use the workaround(to mute warnings) https://github.com/rook/rook/issues/7746#issuecomment-859129752 if you encounter the same. 
Please do collect the logs before and after the node restart.

**Comment by hezise** [comment]
@Rakshith-R 
I updated the driver, I'll update if it helped

**Comment by hezise** [comment]
@Rakshith-R 
After updating the driver I didn't notice any issues
thanks for your help
