### ISSUE TITLE
Put PVC label(s) on persistent volumes

### ISSUE THREAD

**Issue by aaa8141** [rook/rook#8336]
Is is possible to have persistent volume labeled as the same label PVC has in provisioning state?

**Comment by Rakshith-R** [comment]
> Is is possible to have persistent volume labeled as the same label PVC has in provisioning state?

hey @aaa8141 , Can you be more elaborate about what is the feature you want and it's corresponding use cases ?

**Comment by hugotms** [comment]
Hi,

I'm actually really interested in this issue. Is it possible by any mean ? I want to add a custom label to `PersistentVolume` dynamically created by rook from a PVC. The idea being that I have several backup policies and I want to backup only PVs that matches a specific label.

**Comment by chr0n1x** [comment]
does anyone know if work surrounding this would be planned? Ive been clicking around going from issue to issue trying to figure out the current "active" thread of work/efforts around this and everything is closed ☹️
