### ISSUE TITLE
operator fails to delete cephcluster with non-csi osd/mon volumes

### ISSUE THREAD

**Issue by tareqhs** [rook/rook#8345]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The operator fails to delete the cephcluster resource and prints these errors in a loop:
> ceph-cluster-controller: Spec.CSI is nil for PV "..."

> ceph-cluster-controller: failed to check if volumes exist. waiting for csi volume attachments in cluster "rook-ceph" to be cleaned up

**Expected behavior:**

rook-ceph-operator should handle deletion of `cephcluster` resources with OSDs and Mons having PVCs provisioned by non-csi drivers, e.g. `kubernetes.io/aws-ebs`.

This started only after migrating to rook v1.6, did not happen in v1.5

**How to reproduce it (minimal and precise):**
1. Create a CephCluster resource and set `volumeClaimTemplates` for OSD device sets to a storage class that has a non-csi driver.
2. Wait for the ceph cluster to become ready
3. Delete the CephCluster resource

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Linux
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: aws, azure, ...
* Rook version (use `rook version` inside of a Rook Pod): v1.6.5
* Storage backend version (e.g. for ceph do `ceph -v`): ceph v16.2.4
* Kubernetes version (use `kubectl version`): 1.20
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): provisioned by Gardener 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTHY

**Comment by Rakshith-R** [comment]
> ceph-cluster-controller: Spec.CSI is nil for PV "..."

@tareqhs , the above msg is just a error log and can be ignored. However, there should be other PVs created with rook deployed drivers which causes the cluster deletion to fail/stall until they are deleted (or some other error has occurred). 
Please paste the entire logs.

https://github.com/rook/rook/blob/v1.6.5/pkg/operator/ceph/cluster/controller.go#L483-L506
