### ISSUE TITLE
failed to delete configmap rook-ceph-detect-version rook1.6.7

### ISSUE THREAD

**Issue by chinaboy007** [rook/rook#8349]
kubernetes 1.20.0
rook 1.6.7

failed to delete configmap rook-ceph-detect-version

**Comment by travisn** [comment]
@chinaboy007 Please open an issue with the template details that explain how to repro and more details about the failure. There are not enough details to troubleshoot this issue.

**Comment by chinaboy007** [comment]
Thank you. I've solved this problem. I uninstall istio and then install it

**Comment by chinaboy007** [comment]
Thank you. I've solved this problem. I uninstall istio and then install it
