### ISSUE TITLE
update jenkins slave packer image so its preloaded with docker images for tests

### ISSUE THREAD

**Issue by dangula** [rook/rook#845]
Update packer image for Jenkins slaves (aws,gce  and azure) such that they are preloaded with Docker images needed for tests. 
we need the following docker images to be preloaded
1. marintis/dind - v1.5,v1.5 and v1.7
2. ceph/base
3. busybox

**Comment by dangula** [comment]
also need to install kubectl

**Comment by bassam** [comment]
doesnt mirantis/dind install a matching kubectl already?

**Comment by dangula** [comment]
yes it does, under.cache. I should just export that instead of installing kubectl. On the CI slaves i see no issues when running tests with "build run make test-integration"(running in cross-build64 container), but when running tests from binary I see the following error.
```2017-07-28 06:11:07.164379 I | exec: Running command: kubectl config view -o json

**Comment by dangula** [comment]
However, i am going to set up GOPATH on the slaves and have github.com/jstemmer/go-junit-report. So I can convert the results to JUnit and archive them on the slaves, instead of stashing them on slaves and then unstashing them on worker node.

**Comment by dangula** [comment]
Closing this ticket, by moving to Kubeadm, there is no need to preload images.
