### ISSUE TITLE
pod pending and got error message “MountVolume.MountDevice failed for volume "pvc-c5a46b2b-0bec-48a8-8093-2f1571039873" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 95) occurred while running rbd args: [--id csi-rbd-node -m 10.61.110.128:6789,10.61.154.58:6789,10.61.177.62:6789 --keyfile=***stripped*** map replicated-metadata-pool/csi-vol-67da5f57-f1b5-11eb-a1a0-ea45a8cd7486 --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed rbd: map failed: (95) Operation not supported”

### ISSUE THREAD

**Issue by gaofengliu0** [rook/rook#8451]
help !!

E0731 02:05:48.567727 2658351 utils.go:171] ID: 533 Req-ID: 0001-0009-rook-ceph-0000000000000003-bdee4334-f1a3-11eb-a1a0-ea45a8cd7486 GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 95) occurred while running rbd args: [--id csi-rbd-node -m 10.61.110.128:6789,10.61.154.58:6789,10.61.177.62:6789 --keyfile=***stripped*** map replicapool/csi-vol-bdee4334-f1a3-11eb-a1a0-ea45a8cd7486 --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (95) Operation not supported
E0731 02:05:56.666008 2658351 util.go:233] kernel 4.18.9-1.el7.elrepo.x86_64 does not support required features
W0731 02:05:56.821536 2658351 rbd_attach.go:270] ID: 535 Req-ID: 0001-0009-rook-ceph-0000000000000003-bdee4334-f1a3-11eb-a1a0-ea45a8cd7486 rbd: map error an error (exit status 95) occurred while running rbd args: [--id csi-rbd-node -m 10.61.110.128:6789,10.61.154.58:6789,10.61.177.62:6789 --keyfile=***stripped*** map replicapool/csi-vol-bdee4334-f1a3-11eb-a1a0-ea45a8cd7486 --device-type krbd --options noudev], rbd output: rbd: sysfs write failed
rbd: map failed: (95) Operation not supported
E0731 02:05:56.821690 2658351 utils.go:171] ID: 535 Req-ID: 0001-0009-rook-ceph-0000000000000003-bdee4334-f1a3-11eb-a1a0-ea45a8cd7486 GRPC error: rpc error: code = Internal desc = rbd: map failed with error an error (exit status 95) occurred while running rbd args: [--id csi-rbd-node -m 10.61.110.128:6789,10.61.154.58:6789,10.61.177.62:6789 --keyfile=***stripped*** map replicapool/csi-vol-bdee4334-f1a3-11eb-a1a0-ea45a8cd7486 --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed
rbd: map failed: (95) Operation not supported
E0731 02:06:12.882926 2658351 util.go:233] kernel 4.18.9-1.el7.elrepo.x86_64 does not support required features
W0731 02:06:13.039895 2658351 rbd_attach.go:270] ID: 537 Req-ID: 0001-0009-rook-ceph-0000000000000003-bdee4334-f1a3-11eb-a1a0-ea45a8cd7486 rbd: map error an error (exit status 95) occurred while running rbd args: [--id csi-rbd-node -m 10.61.110.128:6789,10.61.154.58:6789,10.61.177.62:6789 --keyfile=***stripped*** map replicapool/csi-vol-bdee4334-f1a3-11eb-a1a0-ea45a8cd7486 --device-type krbd --options noudev], rbd output: rbd: sysfs write failed
rbd: map failed: (95) Operation not supported

Environment:

OS (e.g. from /etc/os-release): centos 7.6
Kernel (e.g. uname -a): 4.18.9-1.el7.elrepo.x86_64
Cloud provider or hardware configuration:
Rook version (use rook version inside of a Rook Pod): v1.7.0-alpha.0.37.g88adffb
Storage backend version (e.g. for ceph do ceph -v): ceph version 16.2.5
Kubernetes version (use kubectl version): v1.21.1
Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox): HEALTH_OK

**Comment by 2like** [comment]
how to slove?
