### ISSUE TITLE
[Question] Regarding bluestore disk partitioning

### ISSUE THREAD

**Issue by galexrt** [rook/rook#846]
I have taken a look at the docs anad code, but I couldn't answer the question what rook would do when pointing it to an existing disk for storage type `bluestore`.
Is rook just going to **add** the partitions on top of the existing ones (if there is still space left) or **zap/overwrite** the whole disk and then create the partitions begining from "zero".

**Comment by jbw976** [comment]
@galexrt, Rook takes a few precautions when being pointed at an existing disk, but if it looks to not already be in use then Rook will zap it and take full ownership of the entire device.  Those precautions are:

1. Does the device have any child partitions?  If so, are they already owned by Rook (as indicated by a label with prefix ROOK-OSD)?
1. Does the device not already have an existing filesystem?

If those precautions are satisfied, then Rook deems it OK to use the device as indicated by the user's config.  You can see the code for this logic here: https://github.com/rook/rook/blob/4d5818d49e7cd13cd5781f7816e50cff33f969a1/pkg/ceph/osd/device.go#L129

**Comment by galexrt** [comment]
Mhh from the code I can't use an disk with other partitions on it than `ROOK-OSD-*` ones.

From line https://github.com/rook/rook/blob/4d5818d49e7cd13cd5781f7816e50cff33f969a1/pkg/ceph/osd/device.go#L153 I see that it would be possible if the condition would be altered to check for the three partitions, when bluestore is used, and not return on the "first" partition that isn't prefixed by `ROOK-OSD`, so something like the partition table below would be possible to be used:

NUMBER | LABEL | SIZE
---------- | ------- | ----
1 | BOOT | 512MB
2 | ROOT | 80GB
3 | ROOK-OSD-WAL | ~576MB
4 | ROOK-OSD-DB | 20GB
5 | ROOK-OSD-BLOCK | Rest of space

(The sizes of the `ROOK-OSD-*` partitions are taken from a rook used 3TB disk).

Would it be okay to submit a PR to change this behaviour, to allow usage of "used" disks too?

**Comment by jbw976** [comment]
it is definitely OK to submit a PR to change the behavior! we love contributions from the community.

the big caveats i can think of here:

- when a device is already in use, but rook hasn't been installed yet, how do you determine that is OK to use the drive?
- when Rook preps the drive for use by OSDs, it assumes full ownership of the entire device.  This logic would need to updated (and maybe others too), to honor any existing partitions on the disk: https://github.com/rook/rook/blob/master/pkg/ceph/osd/scheme.go#L319

**Comment by travisn** [comment]
this would be simpler once #347 is done, so that an osd could work with a single partition. Then you could tell rook to use a partition such as `/dev/sdd3`.

**Comment by galexrt** [comment]
@travisn Then I'm going to close this and follow #347. Thanks for the info!

**Comment by travisn** [comment]
actually this might be a separate work item to be able to specify a partition, so let's keep it open until it's confirmed with #347

**Comment by travisn** [comment]
Actually, let's stick with #347
