### ISSUE TITLE
convert util.NewSet() to sets.NewString()

### ISSUE THREAD

**Issue by leseb** [rook/rook#8479]
The `k8s.io/apimachinery/pkg/util/sets` provides the same functionality with probably more. Our code uses both `util.NewSet()` and `sets.NewString()` at the same time. Let's convert to use `sets.NewString()` even if less instances but provides more functionality.

**Comment by parth-gr** [comment]
As discussed in the call, in a separate PR, we need to remove [Util Package Set.go](https://github.com/rook/rook/blob/master/pkg/util/set.go) as it will no longer be used in the code,
And also left to modify the [configMap set Instance](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/create.go#L37) to string Instance, which was throwing err while conversion.
