### ISSUE TITLE
Metrics collection updates for luminous

### ISSUE THREAD

**Issue by travisn** [rook/rook#849]
With PR-836 we are updating to ceph luminous RC, which includes a change that breaks our metrics collection. The work with ceph_exporter effectively all needs to be updated.

**Comment by travisn** [comment]
The only work remaining after the merge is to fix some unit tests, so we can remove this from 0.5.  The metrics are all expected to be working. Some of the mon metrics removed do not provide useful information so they were removed at the ceph layer. The remaining tests are in https://github.com/rook/rook/blob/master/pkg/ceph/collectors/health_test.go

**Comment by bassam** [comment]
possibly related to #869

**Comment by galexrt** [comment]
Is #891 also possibly related to this?

**Comment by jbw976** [comment]
It very well may be related @galexrt, thanks for reporting.  I'm going to be looking into these metrics regressions for a potential v0.5.1 minor release.
