### ISSUE TITLE
PrometheusRule labels not being overriden

### ISSUE THREAD

**Issue by LittleFox94** [rook/rook#8502]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I tried to configure the generated `PrometheusRule` to have the label `prometheus=prometheus`, following the documentation at the bottom of [this page](https://rook.io/docs/rook/v1.6/ceph-monitoring.html). (Looked at the v1.7 version of the docs, but no change in v1.6 - still running v1.6).

Due to being unable to change that label, my prometheus operator does not catch the rules - it filters by `prometheus=prometheus` (changed the default value `k8s`, which wouldn't have worked for the same reason).

**Expected behavior:**
I expected the documentation to be true (scnr), to be able to change the label and prometheus-operator catching these rules.

**How to reproduce it (minimal and precise):**
* Deploy a `CephCluster` with `labels.monitoring.prometheus` set to some value
* look at the generated `PrometheusRules` resource for that cluster and see the label `prometheus` not having the configured value

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
  - I think this is not helpful, but will upload happily if needed
* Operator's logs, if necessary
  - no errors or warnings reported in this regard
* Crashing pod(s) logs, if necessary
  - no crashes (yay, good work! :smiley_cat:)

**Environment**:
* OS (e.g. from /etc/os-release): Debian 10
* Kernel (e.g. `uname -a`): irrelevant
* Cloud provider or hardware configuration: irrelevant
* Rook version (use `rook version` inside of a Rook Pod): v1.6.2
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.2
* Kubernetes version (use `kubectl version`): 1.21.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): vanilla, custom built
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): all healthy

I think I found the cause.

* [pkg/operator/ceph/cluster/mgr/mgr.go:496](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/mgr/mgr.go#L496) calls `ApplyToObjectMeta`, which "adds labels to object meta unless the keys are already defined".
* The rule is loaded from a file, I think it is this one (with v16 linking to v14): [cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml) - which defines the label `prometheus` already, so that cannot be overriden.
* I'm not sure if that file is loaded, but contents look correct otherwise

**Comment by LittleFox94** [comment]
editing `/etc/ceph-monitoring/prometheus-ceph-v14-rules.yaml` in the running operator container, deleting the generated `PrometheusRules` resource and then changing anything in the `CephCluster` resource (to trigger a reconcile without restarting our hacky modified operator) indeed fixes this.

Used this command in the operator container:
`sed -i '/^    prometheus: rook-prometheus$/d' /etc/ceph-monitoring/prometheus-ceph-v14-rules.yaml`

For fixing this, I see two ways:
* change the default labels to be added in the golang code and remove them from the template
* add the two default labels (`prometheus` and `role`) to a list of "labels allowed to be overridden"
  - since the `ApplyToObjectMeta` function is generic and not only for this, adding this there would need an api change (adding a `allowOverride []string` argument)
 
The first one seems easier and correct enough. I'll prepare a pull request for this probably later today, if I miss anything, feedback before would be great - but in any case it's not "wasted" work from my view, even if not merged - finally a chance to fix something instead of only reporting x)

**Comment by travisn** [comment]
@LittleFox94 The request is to be able to customize the labels here?
```yaml
kind: PrometheusRule
metadata:
  labels:
    prometheus: rook-prometheus
    role: alert-rules
```

To add "labels allowed to be overridden", are you suggesting a new setting would be added to the cephcluster CR under the `monitoring` section? Then the operator would apply those settings at runtime when the rules are created? 

We have also been discussing the need to customize other settings in the prometheus rules for #9005, I wonder if we could have a more general solution that will allow replacing any variable inside the file. @aruniiird FYI

**Comment by LittleFox94** [comment]
Yes those labels, but setting them is already a feature via `CephCluster.spec.labels.monitoring` (iirc) - it's just that the labels set in template cannot be overridden by the user - which in turn means it's currently "impossible" to point an existing `kube-prometheus` stack at rook, they filter on the `prometheus` label by default

**Comment by travisn** [comment]
I see, we don't even need a new property in the cephcluster, we just need a code change that will allow those labels to be overridden.

**Comment by LittleFox94** [comment]
exactly :)

In [this](https://github.com/rook/rook/issues/8502#issuecomment-894131964) comment I wrote two ideas how this could be done, the first seeming to be easier - that's the one I would build and make a PR for, if that sounds sensible

**Comment by travisn** [comment]
> exactly :)
> 
> In [this](https://github.com/rook/rook/issues/8502#issuecomment-894131964) comment I wrote two ideas how this could be done, the first seeming to be easier - that's the one I would build and make a PR for, if that sounds sensible

Yes that first approach sounds good, thanks
