### ISSUE TITLE
CSI Drivers not deployed

### ISSUE THREAD

**Issue by hezise** [rook/rook#8512]
**Is this a bug report or feature request?**
* Bug Report
Sometimes when I deploy a cluster on azure the CSI is not deployed. there is an error in operator log but ceph status displays that health is OK
**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

it's not constant behavior 
[operator_log.zip](https://github.com/rook/rook/files/6952532/operator_log.zip)

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):
* Linux vmautoqadev808081 5.4.0-1055-azure #57~18.04.1-Ubuntu SMP Fri Jul 16 19:40:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
Azure

* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.5.8
go: go1.13.8

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)

* Kubernetes version (use `kubectl version`):
* Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
kubespray 2.15

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
cluster:
    id:     ad3f24c0-f0cf-4c5e-b865-35d5f1f38a0c
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 5h)
    mgr: a(active, since 6h)
    mds: shared-storage:1 {0=shared-storage-a=up:active} 1 up:standby-replay
    osd: 3 osds: 3 up (since 6h), 3 in (since 6h)
 
  data:
    pools:   6 pools, 161 pgs
    objects: 22 objects, 2.8 KiB
    usage:   3.0 GiB used, 1.2 TiB / 1.2 TiB avail
    pgs:     161 active+clean
 
  io:
    client:   853 B/s rd, 1 op/s rd, 0 op/s wr

**Comment by Madhu-1** [comment]
```log
2021-08-09 00:11:40.842336 E | ceph-csi: failed to start Ceph csi drivers. failed to apply network config to rbd plugin daemonset: &DaemonSet{ObjectMeta:{csi-rbdplugin  rook-ceph    0 ....
:[]DaemonSetCondition{},},}: failed to find CephClusters: etcdserver: request timed out
```

This is because of the ETCD timeout.

@Rakshith-R PTAL

**Comment by hezise** [comment]
but why ceph status is OK, when there's no CSI?

**Comment by Rakshith-R** [comment]
> ```log
> 2021-08-09 00:11:40.842336 E | ceph-csi: failed to start Ceph csi drivers. failed to apply network config to rbd plugin daemonset: &DaemonSet{ObjectMeta:{csi-rbdplugin  rook-ceph    0 ....
> :[]DaemonSetCondition{},},}: failed to find CephClusters: etcdserver: request timed out
> ```
> 
> This is because of the ETCD timeout.
> 
> @Rakshith-R PTAL

Yes, this is a intermittent k8s error.

Restarting rook operator should bring up - csi drivers or retries from https://github.com/rook/rook/pull/8020 fixes this. 

@hezise csi drivers are independent of ceph cluster. It just talks to ceph to create, delete volumes, snapshots, clones and mount, unmount them.

**Comment by hezise** [comment]
Thanks a lot for your response
Indeed restart operator solved it
