### ISSUE TITLE
Worked on AWS EC2 but not on Azure VM

### ISSUE THREAD

**Issue by raj-katonic** [rook/rook#8519]
Just few days ago I created a kubernetes cluster using 4 ec2 instances making one of them master and others were worker nodes. I tried rook-ceph  over there and it worked. I used v1.5.9 branch for that.
![rook-ceph](https://user-images.githubusercontent.com/81794052/128926640-65c338ec-88d9-49cd-b65a-3bfffa6aa29c.png)

Similarly, I created k8s cluster using Azure VMs and attached disks to the worker node. But this didn't workout.
In the first attempt I saw 
  1. the mgr (manager) pod didn't was stuck on init:1/3 
  2. out of 3 nodes only for one of them the osd-prepare worked, for others the job failed for 6 times and exceeded the limit, resulting in skipping of that particular osd.
  3. crashcollector pod was also stuck on init:0/2 

In the second attempt (created whole new cluster) I saw that the manager pod is note even scheduling same for osd-prepare.
![rook](https://user-images.githubusercontent.com/81794052/128926763-a3eed1c3-c006-4319-9795-cf09a8744528.png)

# By the way I also tried the latest branch but it also didn't work out in Azure VM case.

My nodes:
![temp-nodes](https://user-images.githubusercontent.com/81794052/128926880-744a6c92-4368-474b-8aa2-4062c2e8bab1.png)

Can you suggest any solution for this ?

**Comment by travisn** [comment]
@raj-katonic In azure it seems your mons are not forming quorum. See [this topic](https://rook.github.io/docs/rook/v1.7/ceph-common-issues.html#monitors-are-the-only-pods-running) to troubleshoot.

**Comment by raj-katonic** [comment]
Thanks for replying @travisn ...  I will try it now and let you know :)

**Comment by raj-katonic** [comment]
@travisn  I just used the same yamls on aws ec2, there everything is working
![aws-rook1](https://user-images.githubusercontent.com/81794052/129005401-e780df12-a45e-472d-b6d1-faa171ae7205.png)
![aws-rook-2](https://user-images.githubusercontent.com/81794052/129005429-5f4a469f-acff-4401-a5bf-d299dc19a19e.png)
The only difference here is that I enable all traffic from anywhere in the security groups of ec2 instances. Can this be a factor ?

Meanawhile, on azure vms,
As you said previously mon quorum could be an issue, so I tried the non-HA one cluster-test.yml
![non-HA](https://user-images.githubusercontent.com/81794052/129006017-5185675f-0cd9-42db-b72d-fa02707b2d40.png)
still the crashcollector is not running
![lookingforsecrets](https://user-images.githubusercontent.com/81794052/129006300-b92702e9-fcea-49e0-93ed-2ce571f884ff.png)
It is looking for some secret which is created in aws but not here. 
Here are the logs of operator
![mon-logs-mid](https://user-images.githubusercontent.com/81794052/129006914-1b2f3063-9e97-48cb-8179-e2dabdd66aa8.png)
![operator-logs](https://user-images.githubusercontent.com/81794052/129006956-cc881784-1ba7-493a-930a-bfccb01074c4.png)
![last-lines-of-operator-logs](https://user-images.githubusercontent.com/81794052/129006971-02b1a127-87b6-4bca-b90a-4e13824c12ee.png)

Please can you suggest any solution for this ? 
Can inbound outbound rules or Azure Premium SSD be a problem in this ?

**Comment by subhamkrai** [comment]
this secret is created just after mon pods are up and running

**Comment by raj-katonic** [comment]
So @subhamkrai, why the secret is getting created in the Kubernetes cluster created using EC2 instances And not getting created in Kubernetes cluster created using Azure VM ? 
# I'm using ubuntu 20.04

**Comment by raj-katonic** [comment]
@subhamkrai yeah actually first I tried cluster.yaml directly but it failed so I tried to debug that, raised this issue and by taking suggestion from @travisn I thought of creating the non-HA cluster-test.yaml but that failed too. And yeah in that you can see crashcollectors because it didn't work without them so I thought of enabling it but still results were the same

**Comment by raj-katonic** [comment]
Yeah @travisn  I agree but my question is that can anything else play a role in mon quorum like OS or networking at the VM level etc ? 
Because the same as it is works on cluster created on AWS

**Comment by travisn** [comment]
It must be something with Azure networking that is different in your environment. I know others have run Rook in Azure, but I'm not sure their network configuration.

**Comment by raj-katonic** [comment]
This is what I tried just now:
I had cluster.yaml applied in my kubernetes from a long time which was stuck after creating one mon as I said.
Now, I created the cluster-test.yml one again and restarted the operator. 
this is the result of get pods. (the non HA one)

![getpods](https://user-images.githubusercontent.com/81794052/129138932-6666036d-12a1-47b7-925d-387676cf0aec.png)

As I said this is something which occurs frequently when trying on azure. One osd is up and the rest are not.

This is the working osd (osd3). These are its logs.
![osd3-working](https://user-images.githubusercontent.com/81794052/129139130-a103cb8d-b968-4016-bbe8-fc3799c5f905.png)

![osd3-working1](https://user-images.githubusercontent.com/81794052/129139173-e16eb9cc-5b6c-43c4-b820-a09275e8036c.png)

![osd3-workin2](https://user-images.githubusercontent.com/81794052/129139189-38b9834d-be26-421a-834f-511da2ad56c7.png)

![osd3-working4](https://user-images.githubusercontent.com/81794052/129139196-3e72880f-6388-4c60-94fa-ea1a61dd452d.png)

And now here are the logs of osds which are failing

osd2

![osd2-not-working](https://user-images.githubusercontent.com/81794052/129139250-4eef227a-42c5-44cb-8852-14eab3b73cf0.png)

osd1

![osd1-not-working](https://user-images.githubusercontent.com/81794052/129139273-d9b813d1-c3e9-4e46-a318-5d3de8770de9.png)

Why is it that one osd is worked fine and the rest did'nt ?
