### ISSUE TITLE
CephFS creation with external cluster results in failures

### ISSUE THREAD

**Issue by electrical** [rook/rook#8538]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

In the Ceph UI we do find an entry under "filesystems"

log in the csi-provisioner:

```
W0812 10:28:26.719870 1 controller.go:943] Retrying syncing claim "96e6b191-152d-4869-94a3-aad45b910c9d", failure 10
E0812 10:28:26.719921 1 controller.go:966] error syncing claim "96e6b191-152d-4869-94a3-aad45b910c9d": failed to provision volume with StorageClass "rook-ceph-cephfs": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0812 10:28:26.720024 1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"tests", Name:"cephfs-storage-claim", UID:"96e6b191-152d-4869-94a3-aad45b910c9d", APIVersion:"v1", ResourceVersion:"100750026", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-ceph-cephfs": rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**
Apply config, create pvc.

**File(s) to submit**:

Configs: https://gist.github.com/electrical/9bc16361faa024d5a89eac9ddd1505bc

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu
* Kernel (e.g. `uname -a`): 5.4.0-74
* Rook version (use `rook version` inside of a Rook Pod): 1.6.4
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.13
* Kubernetes version (use `kubectl version`): 1.19.10

**Comment by electrical** [comment]
Running the following command takes a long time to return any data. Not sure if it's related

```
[root@rook-ceph-tools-5c69594764-dpvl5 /]# ceph fs status
ceph-rook-fs-staging - 0 clients
====================
RANK      STATE                MDS               ACTIVITY     DNS    INOS  
 0        active      ceph-rook-fs-staging-a  Reqs:    0 /s    10     13   
0-s   standby-replay  ceph-rook-fs-staging-b  Evts:    0 /s     0      3   
             POOL                TYPE     USED  AVAIL  
ceph-rook-fs-staging-metadata  metadata  78.6M  29.7T  
  ceph-rook-fs-staging-data0     data       0   29.7T  
MDS version: ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)
```

**Comment by electrical** [comment]
After some trial and error i've created the ceph filesystem on the storage cluster directly which seems to work fine.
This would indicate that there is an issue with the external cluster implementation.
We have no firewalls between the servers and they communicate over a private network.

**Comment by BlaineEXE** [comment]
@leseb would you be able to check this out?

**Comment by Peyoz** [comment]
Hi,
I'm having the same issue here, I just created a ceph cluster through cephadm.
I then run the necessary scripts to import in **rook-ceph** namespace the cluster, and it is connected successfully.
Unfortunately, I then tried to create a CephFS (with pretty much the same manifest as @electrical ) and I'm getting this error below
```
2021-09-13 20:10:36.063948 I | cephclient: setting pool property "compression_mode" to "none" on pool "sharedfs-metadata"
2021-09-13 20:10:37.090040 I | cephclient: creating replicated pool sharedfs-metadata succeeded
2021-09-13 20:10:39.119293 I | cephclient: setting pool property "compression_mode" to "none" on pool "sharedfs-data0"
2021-09-13 20:10:40.154025 I | cephclient: creating replicated pool sharedfs-data0 succeeded
2021-09-13 20:10:40.997986 I | cephclient: setting allow_standby_replay for filesystem "sharedfs"
2021-09-13 20:10:42.162670 I | ceph-file-controller: start running mdses for filesystem "sharedfs"
2021-09-13 20:10:42.602826 I | cephclient: getting or creating ceph auth key "mds.sharedfs-a"
2021-09-13 20:10:43.056663 I | op-mds: setting mds config flags
2021-09-13 20:10:43.056689 I | op-config: setting "mds.sharedfs-a"="mds_join_fs"="sharedfs" option to the mon configuration database
2021-09-13 20:10:43.417021 I | op-config: successfully set "mds.sharedfs-a"="mds_join_fs"="sharedfs" option to the mon configuration database
2021-09-13 20:10:43.427186 E | ceph-file-controller: failed to reconcile failed to create filesystem "sharedfs": failed to start deployment for MDS "a" for filesystem "sharedfs": failed to create mds deployment rook-ceph-mds-sharedfs-a: Deployment.apps "rook-ceph-mds-sharedfs-a" is invalid: [spec.template.spec.containers[0].image: Required value, spec.template.spec.initContainers[0].image: Required value]
2021-09-13 20:10:43.431796 I | op-mon: parsing mon endpoints: timatom-gluster-2=REDACTED:6789,timatom-gluster-3=REDACTED:6789,timatom-gluster-4=REDACTED:6789,timatom-gluster-5=REDACTED:6789,timatom-gluster-6=REDACTED:6789,timatom-gluster-1=REDACTED:3300
```
Does it Look like it is trying to deploy some mds in the cluster?
Anyway, I skipped and created the FS directly on the ceph cluster and added this simple storageclass.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-rook-managed-cephfs
provisioner: rook-ceph.cephfs.csi.ceph.com # driver:namespace:operator
parameters:
  clusterID: rook-ceph # namespace:cluster
  fsName: sharedfs
  provisionVolume: "true"
  pool: sharedfs_data
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph # namespace:cluster
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph # namespace:cluster
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph # namespace:cluster
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
volumeBindingMode: Immediate
```
Creating a simple pvc results in this error
```
E0913 20:52:18.034937       1 controllerserver.go:172] ID: 83 Req-ID: pvc-44dcf7c6-ea92-4814-b99f-e5d7bf81e47c an operation with the given Volume ID pvc-44dcf7c6-ea92-4814-b99f-e5d7bf81e47c already exists
E0913 20:52:18.034993       1 utils.go:185] ID: 83 Req-ID: pvc-44dcf7c6-ea92-4814-b99f-e5d7bf81e47c GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-44dcf7c6-ea92-4814-b99f-e5d7bf81e47c already exists
```
I don't know where is the issue :(

I also noticed that the mon discovered addresses are using the v1 port instead of v2.

**Comment by electrical** [comment]
@leseb in my case we do have that.
It's working fine for Block and object storage.

**Comment by electrical** [comment]
This is still an active issue. Can this please be reopened.

**Comment by travisn** [comment]
@leseb any more ideas?

**Comment by electrical** [comment]
Hi, just a friendly ping to keep it alive and check if there are any idea's or solutions. Thanks.

**Comment by Madhu-1** [comment]
>rpc error: code = DeadlineExceeded desc = context deadline exceeded

The above error will occur if the ceph cluster is not healthy of cephcsi is not able to reach the cephcluster.@electrical Do you check the [network connectivity](https://github.com/rook/rook/blob/master/Documentation/ceph-csi-troubleshooting.md#network-connectivity) b/w cephcsi and the ceph cluster? If it's working do you have the filesystem created?

**Comment by electrical** [comment]
Current versions because we did some upgrades since the original post:

Ceph: 16.2.6
Rook: 1.7.5
Kubernetes: v1.19.15

**Comment by electrical** [comment]
Updated log level to 5 and got this for log info: https://gist.github.com/electrical/498d5bfcf230ccbf1282d047969de1c1

**Comment by Madhu-1** [comment]
@kotreshhr @ajarr can someone from cephfs help here?

**Comment by electrical** [comment]
Any ideas about this issue? I have no idea how to progress this.

**Comment by travisn** [comment]
@electrical Is this a fair summary?
- CephFS volumes cannot be provisioned when the MDS is running in the local cluster while the mons/osds are in the external cluster
- CephFS volumes can be provisioned if the MDS is in the external cluster along with the mons/osds
- Block and Object store is working as expected from the rook cluster to the external ceph cluster, so the private network appears to be configured as needed.

The error does seem related to a network issue. I wonder if the mds needs additional connectivity to the external cluster, though if block is working fine I'm not sure what additional access mds would require.

For the scenario, why not just use the MDS in the external cluster if that configuration works for you? Architecturally it makes more sense to me if all the ceph daemons are all running in the same cluster even if we have attempted to allow them to be running separately.

**Comment by electrical** [comment]
Hi @travisn that is a correct summary yeah.
We configured the MDS to run on the external cluster but then don't work. Only when we configure them on the storage cluster it works. but I don't see how I then can have the external cluster connect to them.
Also we have multiple external clusters connecting to the storage cluster so not sure how that can be configured.

**Comment by electrical** [comment]
To clarify ( in case it got confusing ) 
we have 2 external clusters ( compute clusters ) and one storage cluster.
The external clusters connect to the storage cluster via the internal network. No firewalling in place.

At the moment we setup the MDS' and all the required cephfs & storage class on the external cluster which doesn't work.
If we setup it up on the storage cluster directly it all works, but this is not what we want.

**Comment by travisn** [comment]
If you setup the cephfs in the storage cluster, then you should be able to do the following in the external cluster:
- Start rook in [external mode](https://rook.github.io/docs/rook/v1.8/ceph-cluster-crd.html#external-cluster)
- Create the cephfs storage class, and set the [pool name](https://github.com/rook/rook/blob/master/deploy/examples/csi/cephfs/storageclass.yaml#L17) as needed for the cephfs data pool in the external cluster.
- Create the cephfs PVCs as usual

If this doesn't work, please share the cephfs csi logs, hopefully they show where the failure is.

**Comment by electrical** [comment]
We haven't tried it in this specific way. Will give this a try and report back

**Comment by electrical** [comment]
@travisn @Madhu-1 it works! We've created the CephFilesystem on the storage cluster and then the StorageClass on the compute clusters for 2 different environments.
Everything now works as expected.

I think it would be good to clarify this in the documentation when it comes to using external clusters for cephfs.

Thank you all so much for your assistance!
