### ISSUE TITLE
optional volume replication crds in helm chart

### ISSUE THREAD

**Issue by travisghansen** [rook/rook#8573]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Make the `openshift` `crds` optional in the helm chart.

**What is use case behind this feature:**

I run netapp `trident` in the same cluster with `rook` and `trident` currently checks for any `openshift` crds to alter it's installation process...`scc` or not etc.

**Environment**:

Running `rook` in a non-`openshift` environment in conjunction with netapp `trident`.

**Comment by travisn** [comment]
@travisghansen Are you referring to the volumereplication CRD? This is actually not specific to openshift, it just has the unfortunate naming for openshift. Can you provide more details on what the issue is with have the CRDs named as such? It causes `trident` to fail in some way?

**Comment by travisghansen** [comment]
@travisn yes and `volumereplicationclasses`. It causes the `trident` operator to *think* it's an `openshift` cluster and makes it behave badly in non-`openshift` clusters (tries to install an `scc` essentially).

```
time="2021-08-20T18:56:13Z" level=error msg="error syncing 'trident': reconcile failed; error re-installing Trident 'trident' ; err: reconcile failed; could not create the Trident OpenShift SCC; could not create OpenShift SCC; yamlDocument \napiVersion: security.openshift.io/v1\nkind: SecurityContextConstraints\nmetadata:\n  annotations:\n    kubernetes.io/description: 'trident is a clone of the privileged built-in, and is meant just for use with trident.'\n  name: trident\n  labels:\n    app: controller.csi.trident.netapp.io\n    k8s_version: v1.20.9\n    trident_version: v21.04.0\n  ownerReferences:\n  - apiVersion: trident.netapp.io/v1\n    controller: true\n    kind: TridentOrchestrator\n    name: trident\n    uid: ee383912-b13c-498c-a860-6078363093de\nallowHostDirVolumePlugin: true\nallowHostIPC: true\nallowHostNetwork: true\nallowHostPID: true\nallowHostPorts: true\nallowPrivilegeEscalation: true\nallowPrivilegedContainer: true\nallowedCapabilities:\n- '*'\nallowedUnsafeSysctls:\n- '*'\ndefaultAddCapabilities: null\nfsGroup:\n  type: RunAsAny\ngroups: []\npriority: null\nreadOnlyRootFilesystem: false\nrequiredDropCapabilities: null\nrunAsUser:\n  type: RunAsAny\nseLinuxContext:\n  type: RunAsAny\nseccompProfiles:\n- '*'\nsupplementalGroups:\n  type: RunAsAny\nusers:\n- system:serviceaccount:trident:trident-csi\nvolumes:\n- '*'\n was not created after 30.00 seconds, requeuing"
```

**Comment by travisghansen** [comment]
https://github.com/NetApp/trident/issues/639

**Comment by travisn** [comment]
@leseb What would it take to make the replication CRD optional? If we just don't install the CRD I believe the operator will at a minimum show failures in the log.

**Comment by travisghansen** [comment]
If NetApp is addressing it you may want to hold off. Who 'owns' those CRDs?

**Comment by leseb** [comment]
> @leseb What would it take to make the replication CRD optional? If we just don't install the CRD I believe the operator will at a minimum show failures in the log.

That's right if the CRD is not present the controller watching for that resource will print out a message that the CRD does not exist. It is another operator than Rook-Ceph that is watching for that CRD so nothing will be printed in the Rook-Ceph operator logs.

Honestly, I think Trident should fix this by adding this CRD in a list of known CRD not being an OpenShift cluster. However, it  is going to conflict with real OpenShift installation. I suppose they need to change the way they determine the cluster is an OpenShift cluster and that would solve the problem.

**Comment by leseb** [comment]
> If NetApp is addressing it you may want to hold off. Who 'owns' those CRDs?

This operator https://github.com/csi-addons/volume-replication-operator

**Comment by travisghansen** [comment]
Ah right. So I would suggest to make it optional in some shape or form but not because of the netapp issue (they are addressing it) but rather it would cause problems for me (and probably others) since I manage rook with gitops (argocd). If rook doesn’t ‘own’ the crd it shouldn’t be installing it imho.

The crd should be installed by my volume replication controller installation so I don’t have 2 apps fighting over the crd assets and possibly conflicting etc.

What does everyone else think about this?

**Comment by leseb** [comment]
@travisghansen that makes sense.

@Madhu-1 @Yuggupta27 why do we add that CRD from Rook btw? Is it because the operator will be activated by CSI based on the presence of the CRD?

**Comment by paalkr** [comment]
I absolutely agree with @travisghansen in this case. I would expect to deploy the CRDs in question when I deploy the volume replication controller. Not when I deploy the rook controller.

**Comment by BlaineEXE** [comment]
It sounds like we may want to instruct users to install (and possibly update) the CRDs for the replication controller by referencing the file link. 

The below snippet should install the CRDs as defined in the main branch for the repo.
```
kubectl apply -f https://raw.githubusercontent.com/csi-addons/volume-replication-operator/main/config/crd/bases/replication.storage.openshift.io_volumereplicationclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/csi-addons/volume-replication-operator/main/config/crd/bases/replication.storage.openshift.io_volumereplications.yaml
```

**Comment by travisn** [comment]
In reality the volume replication CRDs are owned by ceph CSI team, and will only ever be installed by Rook since Rook essentially owns deployment of the CSI driver. So the fact that Rook installs these CRDs is not going to cause a conflict with something else installing them. And this really means Rook is the owner of the CRDs, which really means they should be in the rook.io namespace instead of some other namespace. If not in the Rook namespace, Rook really shouldn't install them. But now that we are stuck with the naming since v1.6, it will be a challenge to rename them. At a minimum it does seem we should make them optional, not installed by default, and configure them to be enabled only when the volume replication sidecar of the csi driver is enabled.
@Madhu-1 thoughts?

**Comment by travisghansen** [comment]
Maybe I misunderstood. Are you suggesting the volume replication operator of csi *only* works (or perhaps better said is only meant to work) with `rook` and none of the other `csi` drivers?

**Comment by travisn** [comment]
> Maybe I misunderstood. Are you suggesting the volume replication operator of csi _only_ works (or perhaps better said is only meant to work) with `rook` and none of the other `csi` drivers?

Yes that's my understanding currently

**Comment by travisghansen** [comment]
As a developer of several csi drivers that seems like either a misnamed project or a misunderstanding somewhere :)

Regardless, the question at hand about what project should install the crds still seems like it should land in the csi project vs rook imo. Especially since (based on comments above) it’s not actually rook that watches the resources but rather the replication controller.

**Comment by BlaineEXE** [comment]
I'm also of the opinion that Rook shouldn't be installing CRDs at all, even if it's for CSI. They should be part of the `crds.yaml` so that only admins have the permissions to install them. CSI should be able to handle the case where the volume replication controller isn't installed.

**Comment by travisn** [comment]
The CRDs are currently only created by crds.yaml, and not the operator, so we don't have an issue there today. For this issue, if they are in Rook's crds.yaml, Rook by definition is considered the owner, and we need to clarify that nobody else will ever install them and why they have an openshift.io name.

**Comment by BlaineEXE** [comment]
Then we can remove these permissions, as they are not needed: https://github.com/rook/rook/pull/6017/files#diff-f42a0ce48bd8da0c47a289184183a132c97a98324de7eda474b33add69b66457R311-R313

**Comment by BlaineEXE** [comment]
I don't think rook is definitionally the owner though. A user might want to install the volumereplicationcontroller manually. Other storage systems might also use the volumereplicationcontroller, so if Rook is uninstalled, that could interfere with another project.

**Comment by travisn** [comment]
I share the concern, if Rook isn't really the owner, then Rook should not install the CRDs. But if the Ceph-CSI driver is the only consumer (and considered the proper owner), I would also argue that Rook is the owner of everything needed for Ceph-CSI, and we could keep installing it. Making it optional would still be a plus though.

**Comment by BlaineEXE** [comment]
But my point is that the Ceph-CSI driver is not intended to be the only consumer. It is an open specification, and any CSI driver can use it. We should be operating toward the intent of the project in this case.

**Comment by travisn** [comment]
Yes, that's my question for the CSI team. If any other CSI project is intended to use it, Rook can't install it, and it has to be optional since the admin may not install it separately if they don't need the feature.

**Comment by Madhu-1** [comment]
>But my point is that the Ceph-CSI driver is not intended to be the only consumer. It is an open specification, and any CSI driver can use it. We should be operating toward the intent of the project in this case.

Yes that's the plan

Currently, cephcsi/Rook is the only consumer of this one. and yes this is not specific to cephcsi we can make it optional. and any idea how to bundle this with OLM when Rook is deployed using OLM?

**Comment by paalkr** [comment]
If a person deploy rook/ceph using the yaml manifests, just removing the CRDs in question isn't a big deal (but of course not a preferred workflow). But if you deploy using helm, or other automaton tools, this becomes a more important issue.

**Comment by travisghansen** [comment]
@Madhu-1 should the replication controller be its own operator and then rook depend on that in olm? Logically it seems like a solid/proper approach.

https://github.com/operator-framework/operator-lifecycle-manager#dependency-model

**Comment by BlaineEXE** [comment]
@travisghansen that seems like the right approach to me. 💯

**Comment by Jean-Daniel** [comment]
I just ran into another case where these CRDs cause the very same issue than with `trident`. 

The crunchy postgres-operator also wrongly thinks it is running on OpenShift due to these CRDs and it fails deploying postgreSQL clusters.

Automatic detection can be disable on postgres-operator, so there is a simple workaround at least.
