### ISSUE TITLE
Support different components of CEPH deploy and upgrad separately.

### ISSUE THREAD

**Issue by devlikai** [rook/rook#8610]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Different components of CEPH are deployed and upgraded separately. 
**What is use case behind this feature:**
when we change the  code of a ceph component , such as fix a bug or launch a new feature for mds, we can upgrade mds only, and no need to upgrade all ceph.
**Environment**:

**Comment by BlaineEXE** [comment]
@devlikai what is the problem you are facing that makes this necessary? 

We understand that reconciles can take a while for Ceph updates, and we have been (and will continue) to try to make it possible to do as many updates in parallel as possible for all components to alleviate lengthy reconcile times for larger clusters.

In my estimation, the complexity of implementing this issue might not be worth what I perceive to be a small benefit. We would have to check the version of all images which are different and verify that Ceph versions don't diverge beyond just bug fix updates. Components shouldn't be running different major versions except during upgrade. That check plus that exception already increase complexity and possibility for errors quite a bit. I think it is safest overall to enforce that all components should be on the same Ceph version. I think it's a good assumption that Ceph bug fix updates are good to deliver to the whole cluster.

@travisn @leseb do you have other thoughts?

**Comment by travisn** [comment]
I share the concern that if different versions of Ceph are allowed for the daemons, it is much more risky than just going ahead with the upgrade of all daemons to maintain consistency. If restarting daemons is disruptive, we should fix those issues.
