### ISSUE TITLE
push-image-to-container-registry fails

### ISSUE THREAD

**Issue by leseb** [rook/rook#8616]
See:

```
Run tests/scripts/build-release.sh
+ tests/scripts/build-release.sh
+ SHOULD_PROMOTE=true
+ [[ refs/heads/master =~ master ]]
+ echo 'Publishing from master'
+ CHANNEL=master
+ publish
+ build
+ build/run make build.all
Publishing from master
build/run: line 22: DOCKER_HOST: unbound variable
```

In https://github.com/rook/rook/runs/3459319208?check_suite_focus=true
This is due to the recent bash refactor.

**Comment by BlaineEXE** [comment]
DOCKER_HOST seems like it isn't set on macos any more, so it's not really a valid check today. I think the lines involving DOCKER_HOST can just be removed.

I think we can also remove stuff involving KUBEADM_DIND_DIR since we removed DIND scripts a week or two ago.
