### ISSUE TITLE
Offline deployment of rook-ceph

### ISSUE THREAD

**Issue by yannick-peyrotau** [rook/rook#8651]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
ImagePullBackOff for ceph monitoring

**Expected behavior:**
defined imagePullSecret used by the cluster even for ceph monitoring

**How to reproduce it (minimal and precise):**
Put all images in the local repository.
Modify all (op et cluster) values with local images ans imagePullSecret.
Use helm to install rook-ceph with offline repository.

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: FlexibleEngine
* Kubernetes version (use `kubectl version`): v1.17.9-r0-CCE20.8.1.3.B001-17.36.5

**Comment by travisn** [comment]
@yannick-peyrotau To setup the pull secrets on the rook service accounts, see [this topic](https://rook.github.io/docs/rook/v1.7/k8s-pre-reqs.html#authenticated-docker-registries). Or can you suggest what is missing from that topic?

**Comment by yannick-peyrotau** [comment]
Ok I finnaly edit the default service account yes, but if you deploy from helm, the default is not updated.
