### ISSUE TITLE
Mgr suite fails intermittently

### ISSUE THREAD

**Issue by leseb** [rook/rook#8669]
Error example:

```
2021-09-08 23:50:50.723787 W | installer: Error executing command "ceph": <exit status 124>
    ceph_mgr_test.go:229: 
        	Error Trace:	ceph_mgr_test.go:229
        	Error:      	Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0009fc9f0), Stderr:[]uint8{0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x20, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x20, 0x77, 0x69, 0x74, 0x68, 0x20, 0x65, 0x78, 0x69, 0x74, 0x20, 0x63, 0x6f, 0x64, 0x65, 0x20, 0x31, 0x32, 0x34, 0xa}}
        	Test:       	TestCephMgrSuite/TestHostLs
2021-09-08 23:50:50.723897 I | integrationTest: output = [{"addr": "fv-az120-523", "hostname": "fv-az120-523", "labels": [], "status": ""}]
. command terminated with exit code 124
    ceph_mgr_test.go:237: 
        	Error Trace:	ceph_mgr_test.go:237
        	Error:      	Expected nil, but got: &json.SyntaxError{msg:"invalid character '.' after top-level value", Offset:84}
        	Test:       	TestCephMgrSuite/TestHostLs
    ceph_mgr_test.go:257: 
        	Error Trace:	ceph_mgr_test.go:257
        	Error:      	Not equal: 
        	            	expected: []string(nil)
        	            	actual  : []string{"fv-az120-523"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,4 @@
        	            	-([]string) <nil>
        	            	+([]string) (len=1) {
        	            	+ (string) (len=12) "fv-az120-523"
        	            	+}
        	            	 
        	Test:       	TestCephMgrSuite/TestHostLs
```

In this run: https://github.com/rook/rook/pull/8665/checks?check_run_id=3550575960
@jmolmo PTAL.

**Comment by jmolmo** [comment]
The error points towards "k8sutil.GetNodeHostNames" returns an empty list ... weird.. I am going to try to reproduce it locally.

**Comment by leseb** [comment]
> The error points towards "k8sutil.GetNodeHostNames" returns an empty list ... weird.. I am going to try to reproduce it locally.

Thanks, maybe this needs a retry?

**Comment by leseb** [comment]
> The error points towards "k8sutil.GetNodeHostNames" returns an empty list ... weird.. I am going to try to reproduce it locally.

Actually it's empty because ` s.execute([]string{"host", "ls", "json"})` fails but return a value we can see the `output` but then the unmarshal fails since the value returned is 

```
[{"addr": "fv-az120-523", "hostname": "fv-az120-523", "labels": [], "status": ""}]
. command terminated with exit code 124
```

Can you explain this?

**Comment by jmolmo** [comment]
Hey!! yes... thank you for the clue!!!.... I was totally wrong... the problem is not in the retrieval of k8 nodes... the problem must be directly in the json.Unmarshal method!!!

It seems that depending of the "source" of the string it can be properly terminated or not,  ... so it is safer to set explicitly the length of the string to parse. In our case it seems (i guess) that the previous conversion to "byte" adds some extra char at the end of the converted slice... (I do not know why or when happens this)

An example of the same error ( using different string source): 
https://stackoverflow.com/questions/25187718/invalid-character-x00-after-top-level-value

So i have set this value in all the "Unmarshal"... now lets see if this change avoids the intermittent fail. (it  looks very probable :-)..

**Comment by leseb** [comment]
I'm not sure this will help either. We need to understand why the command reported an error where it seems that it succeeded.
The command returned a non-nil `err` but the output seems correct. Rook merges the output and the error in case of an error because sometimes the error is in the output.

**Comment by jmolmo** [comment]
The error is reported by the _Unmarshal_ method. The orchestratos command and the _output_ is correct , what I suspect is that the conversion from string to bytes is adding at least 1 more element at the end of the Bytes slice, and that makes the Unmarshal method fail. 
I am not sure , but is the most probable cause. The change does not "break" anything andif we execute the test with this change we can see if the intermittent error return to appear or not. ( at least we will be able to discriminate more things).

**Comment by leseb** [comment]
> The error is reported by the _Unmarshal_ method. The orchestratos command and the _output_ is correct , what I suspect is that the conversion from string to bytes is adding at least 1 more element at the end of the Bytes slice, and that makes the Unmarshal method fail.
> I am not sure , but is the most probable cause. The change does not "break" anything andif we execute the test with this change we can see if the intermittent error return to appear or not. ( at least we will be able to discriminate more things).

That makes sense!
