### ISSUE TITLE
Monitoring - Prometheus not showing ceph metrics

### ISSUE THREAD

**Issue by marct83** [rook/rook#869]
I followed the monitoring instructions here:

https://github.com/rook/rook/blob/master/Documentation/k8s-monitoring.md

I am now able to bring up prometheus however I only see these metrics:
scrape_duration_seconds
scrape_samples_post_metric_relabeling
scrape_samples_scraped

The ceph metrics are not showing up. Any ideas what could be wrong.

**Comment by marct83** [comment]
Now randomly the ceph metrics are showing up. However none of them have datapoints. Also the rook-api endoint is showing as Down under Prometheus Targets.

**Comment by bassam** [comment]
@marct83 were you using the latest from master?

@travisn can you please take a look if this is a regression from luminous changes?

**Comment by marct83** [comment]
@bassam Yes cloned straight from master.

**Comment by bassam** [comment]
@marct83 do you mind trying again from master? we are unable to reproduce. Also make sure you are pulling the latest rook container from master.

**Comment by marct83** [comment]
I backed it right out and then started from scratch with a pull from master.

It's now working. So I'm not sure what the issue was exactly.

**Comment by bassam** [comment]
@marct83 thanks! we had a commit in master that did in fact break prometheus. you must of had that running.
