### ISSUE TITLE
wrong path to logs for log-collector sidecar generated by rook operator for RGW instance 

### ISSUE THREAD

**Issue by kacerr** [rook/rook#8692]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Incorrect path is being generated for logrotate configuration.
In my case logfile generated by radosgw sits in: /var/log/ceph/ceph-client.rgw.aspira.a.a.log,
while CEPH_CLIENT_ID generated by operator is: rgwceph.client.rook.ceph.rgw.aspira.a.a

and `/etc/logrotate.d/ceph` after sed replace points to file: /var/log/ceph/rgwceph.client.rook.ceph.rgw.aspira.a.a.log which is wrong name

**Expected behavior:**
rook operator generates correct CEPH_CLIENT_ID which is then used to generate correct logrotate configuration

**Other information**
cephcluster used by rook is configured as external

i suspect that problem might be here:
https://github.com/rook/rook/blob/94eb4519a09332b1ccbd8c4b8384a1f72dfba2f9/pkg/operator/ceph/object/spec.go#L115, it looks like generateCephXUser and then TrimPrefix makes the difference between what is generated and what the existing file on my system is.

**Comment by BlaineEXE** [comment]
I believe this is a follow-up from a slack issue

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/3989526/133642295-69009417-df8c-44eb-a904-9336c243ff99.png">
https://rook-io.slack.com/archives/CK9CF5H2R/p1631257737279800

**Comment by parth-gr** [comment]
@kacerr, please help me in reproducing the issue by providing more information,

Operator logs, your Cluster.yaml config, any specific configuration you applied.

I created [ObjectStore](https://github.com/rook/rook/blob/master/Documentation/ceph-object.md#create-a-local-object-store) and `sh` into it and in the current director, my log file was present, named `ceph-client.rgw.my.store.a.log` 

Is this correct location and naming as you mentioned?

**Comment by parth-gr** [comment]
The `CEPH_CLIENT_ID=rgwceph.client.rook.ceph.rgw.my.store.a ` & `LOG_ROTATE_CEPH_FILE=/etc/logrotate.d/ceph`
 & `logrotateFile: /var/log/ceph/ceph-client.rgw.my.store.a.log` are the following.
 
The above details are created correctly as per the code, 
may I know what should be changed or is incorrect? (or you mean Client_ID and log rotate file should be same as `/var/log/ceph/rgwceph.client.rook.ceph.rgw.aspira.a.a.log`)



And some other files in /var/log/ceph : 
```
 ceph-client.bootstrap-osd.log	ceph-mgr.a.log	ceph-osd.2.log			 openshift-storage-client.admin.log
ceph-client.rgw.my.store.a.log	ceph-mon.b.log	ocs-deviceset-gp2-1-data-068p5p
```

**Comment by kacerr** [comment]
And what `command` do you have generated for your `log-collector` container? Or can you show me full content of `/etc/logrotate.d/ceph` file? in my case that is different than the file that exists.

In my case actual log file is:
```bash
[root@rook-ceph-rgw-aspira-a-a-5bc7fd5d85-jx2vk /]# ls -la /var/log/ceph/
total 8874692
drwxr-xr-x 2 ceph ceph         44 Sep 21 10:48 .
drwxr-xr-x 1 root root         18 Sep 21 10:49 ..
-rw-r--r-- 1 ceph ceph 8592433886 Sep 27 20:47 ceph-client.rgw.aspira.a.a.log
```

and logrotate configuration is:
```bash
/var/log/ceph/rgwceph.client.rook.ceph.rgw.aspira.a.a.log {
    rotate 7
    daily
    compress
    sharedscripts
    postrotate
        killall -q -1 ceph-mon ceph-mgr ceph-mds ceph-osd ceph-fuse radosgw rbd-mirror || pkill -1 -x "ceph-mon|ceph-mgr|ceph-mds|ceph-osd|ceph-fuse|radosgw|rbd-mirror" || true
    endscript
    missingok
    notifempty
    su root ceph
}
```

obviously it is trying to work with incorrect file

**Comment by parth-gr** [comment]
Yes right `CEPH_CLIENT_ID=rgwceph.client.rook.ceph.rgw.my.store.a` is different from the log file created `ceph-client.rgw.my.store.a.log`.

I am inspecting if the naming should be like that or not.  


And I checked the problem is not at this place https://github.com/rook/rook/blob/94eb4519a09332b1ccbd8c4b8384a1f72dfba2f9/pkg/operator/ceph/object/spec.go#L115 
It gives correct formating similar to client id `rgwceph.client.rook.ceph.rgw.default`

**Comment by parth-gr** [comment]
@kaarolch  Changed the client_ID creation to the new name `ceph-client.rgw.my.store.a` so it can work on with the right ID, as the log file is named.
