### ISSUE TITLE
Remove definitly all remaining usage of context.TODO()

### ISSUE THREAD

**Issue by leseb** [rook/rook#8701]
This is a follow-up from https://github.com/rook/rook/pull/8607. Each function using `context.TODO()` internally must instead ask for a context. Top-level callers now have a `context.Context` available so let's use it. 

This **excludes** the `tests` package directory for now.

**Comment by leseb** [comment]
Closed in #9023

**Comment by leseb** [comment]
We still have some.

**Comment by weirdwiz** [comment]
I would like to take this up, if it's not been worked upon by someone else.

**Comment by subhamkrai** [comment]
> I would like to take this up, if it's not been worked upon by someone else.

@weirdwiz it's all yours now.
