### ISSUE TITLE
Validate yaml in the canary test is failing due to images.txt

### ISSUE THREAD

**Issue by travisn** [rook/rook#8707]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The canary test validation for yaml is failing due to the new images.txt, which is of course not yaml.
```
error: error validating "images.txt": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
```

For example, see [this CI run](https://github.com/rook/rook/pull/8705/checks?check_run_id=3589665873).

**Expected behavior:**
Passing yaml validation

**How to reproduce it (minimal and precise):**

Run the canary tests in the release-1.7 branch. It seems to be passing in master.

**Comment by subhamkrai** [comment]
#8710
