### ISSUE TITLE
Minimum support version of Ceph CSI under Rook 

### ISSUE THREAD

**Issue by humblec** [rook/rook#8709]
With the release of Ceph CSI 3.4.0 (https://github.com/ceph/ceph-csi/releases/tag/v3.4.0) , we came up with a new support policy where we support only versions `>= 3.3.0`

``` 
The supported window of Ceph CSI versions is known as "N.(x-1)": (N (Latest major release) . (x (Latest minor release) - 1)).

For example, if Ceph CSI latest major version is 3.4.0 today, support is provided for the versions above 3.3.0. If users are running an unsupported Ceph CSI version, they will be asked to upgrade when requesting support for the cluster.
```
Ref # https://github.com/ceph/ceph-csi/#known-to-work-co-platforms

however rook repo has listed for versions >=3.0.0 atm:

```
	//minimum supported version is 3.0.0
	minimum = CephCSIVersion{3, 0, 0}
	//supportedCSIVersions are versions that rook supports
	releasev310          = CephCSIVersion{3, 1, 0}
	releasev320          = CephCSIVersion{3, 2, 0}
	releasev330          = CephCSIVersion{3, 3, 0}
	releasev340          = CephCSIVersion{3, 4, 0}
	supportedCSIVersions = []CephCSIVersion{
		minimum,
		releasev310,
		releasev320,
		releasev330,
		releasev340,
	}
```

So, with this issue, I would like to check is it good enough to drop support for `<v3.3.0` in rook master ?  if agreed, I can drop a PR to address the changes in the CSI operator code.

**Comment by humblec** [comment]
Cc  @travisn @leseb

**Comment by leseb** [comment]
I'm fine having Rook (current master, upcoming 1.8 release) following the ceph-csi support policy so `as of v3.3.0` and above.

**Comment by travisn** [comment]
@leseb Any reason not to backport that to 1.7? I would think everyone would want to default to the CSI version that Rook has configured by default, at least upstream. In earlier versions of the driver it was more common for someone to need a different version, but I don't recall hearing about a need for a long time. The main reason for be flexible is downstream, but supporting `n-1` (v3.3.0) seems plenty flexible.

**Comment by leseb** [comment]
@travisn I don't recall anything that would break this in release 1.7. It's just easier sometimes to encourage people to upgrade too and not ending up with huge matrix support. Also upgrading the csi driver version to a major version during a rook minor upgrade, I wonder how much sense that makes?

**Comment by travisn** [comment]
The default CSI version with 1.7 is already 3.4.0, so we aren't changing the version of CSI, it's just bumping the minimum version of CSI supported from 3.1 to 3.3.

**Comment by leseb** [comment]
Oh that right, then I'm good with the backport.
