### ISSUE TITLE
Unable to create volume snapshot

### ISSUE THREAD

**Issue by Sg-23** [rook/rook#8728]
I am facing issue while creating a volume snapshot of pvc on Openshift cluster v4.6.29 .

I am unable to create volume snapshot with the following error in events :
Waiting for a snapshot test-project/k10-csi-snap-vtmhd4spq2bxc6rt to be created by the CSI driver.

The provisioner for the pv is rook-ceph.rbd.csi.ceph.com.
Below are the logs from rook-ceph pods
```
createSnapshotWrapper: Creating snapshot for content snapcontent-8c0ec68c-2df6-4c06-8d41-3507825d8066 through the plugin ...
I0914 13:52:47.295726       1 event.go:282] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"", UID:"", APIVersion:"snapshot.storage.k8s.io/v1beta1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to take snapshot of the volume, 0001-0009-rook-ceph-0000000000000009-d6bd4ea2-719f-11eb-b57f-0a580a830206: %!q(<nil>)
I0914 13:52:47.500050       1 snapshot_controller.go:292] createSnapshotWrapper: CreateSnapshot for content snapcontent-8c0ec68c-2df6-4c06-8d41-3507825d8066 returned error: rpc error: code = Internal desc = provided secret is empty
```

**Comment by Madhu-1** [comment]
@Sg-23 can you please provide the snapshotclass yaml output? Looks like the snapshotclass doesn't contains the secrets

**Comment by Sg-23** [comment]
`apiVersion: snapshot.storage.k8s.io/v1beta1
deletionPolicy: Delete
driver: rook-ceph.rbd.csi.ceph.com
kind: VolumeSnapshotClass
metadata:
  annotations:
    k10.kasten.io/is-snapshot-class: 'true'
  creationTimestamp: '2021-09-13T06:25:46Z'
  generation: 1
  managedFields:
    - apiVersion: snapshot.storage.k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:deletionPolicy': {}
        'f:driver': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:k10.kasten.io/is-snapshot-class': {}
      manager: Mozilla
      operation: Update
      time: '2021-09-13T06:29:18Z'
  name: ceph
  resourceVersion: '362100801'
  selfLink: /apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotclasses/ceph
`
Yes , seems so, do i need to add these two annotations?
  **csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: openshift-storage**

**Comment by Madhu-1** [comment]
https://github.com/rook/rook/blob/bcae365cb9c1d87a6fc9f43d3e8471df13858ae0/cluster/examples/kubernetes/ceph/csi/rbd/snapshotclass.yaml#L15-L16 this should be added to your snapshotclass

**Comment by Sg-23** [comment]
Thankyou, it's working now.

**Comment by Sg-23** [comment]
I am facing error when creating volume snapshot for provisioner **kubernetes.io/aws-ebs**, can I do directly from openshift using volume snapshot class or have to use aws?

**Comment by Madhu-1** [comment]
`kubernetes.io/aws-ebs` is not a CSI driver and you need to check with aws-ebs team.

**Comment by Sg-23** [comment]
okay thanks
