### ISSUE TITLE
provide option to deploy multinode kubernetes cluster in minikube.sh

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#8730]
>minikube start -h |grep nodes
  -n, --nodes=1: The number of nodes to spin up. Defaults to 1.

minikube supports starting multinode kubernetes. This issue is a tracker for adding the support in cephcsi. This helps us to bring up multinode kubernetes cluster with existing script

**Comment by BlaineEXE** [comment]
With https://github.com/rook/rook/issues/8691, the `minikube.sh` script may end up being unmaintained or removed. @travisn @leseb and I have been discussing this on and off for a couple weeks.

**Comment by BlaineEXE** [comment]
I see you added the `ci` label. Do you mean that you want the ability to bring up multi-node in CI?

**Comment by leseb** [comment]
So far all of our attempts to run multi-node on the CI have failed.
