### ISSUE TITLE
CephPoolQuotaBytesNearExhaustion and CephPoolQuotaBytesCriticallyExhausted rules should use ceph_pool_stored

### ISSUE THREAD

**Issue by zerkms** [rook/rook#8735]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Currently the alert expression is:

```
(ceph_pool_stored_raw * on (pool_id) group_left(name)ceph_pool_metadata) / ((ceph_pool_quota_bytes * on (pool_id) group_left(name)ceph_pool_metadata) > 0) > 0.70
```

The problem is the the pool quotas alert expression is set for `ceph_pool_stored_raw ` which includes replication factor, while the ceph quotes are set for logical data size (non-replicated).

**Expected behavior:**

It should use `ceph_pool_stored`, because that's what ceph takes into account when enforces the quota: only logical size, excluding replication factor.

**How to reproduce it (minimal and precise):**

Create a pool with a quota 100Mb.

Set replication factor 3.

Fill it by 50Mb.

See the rule is triggered, but ceph is healthy.

Now try to change the quota to 60Mb. See that ceph is still healthy again.

Now change it to 40Mb and see that only now ceph reports pool being over capacity.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
@anmolsachan PTAL

**Comment by anmolsachan** [comment]
CC @aruniiird @umangachapagain

**Comment by anmolsachan** [comment]
@leseb Can you please assign this to @aruniiird . I will coordinate with him to fix it.

**Comment by zerkms** [comment]
Uhm, can somebody please remove `wontfix`

**Comment by zerkms** [comment]
Not stale.

**Comment by zerkms** [comment]
Not stale.

**Comment by zerkms** [comment]
It indeed made it irrelevant, sorry.
