### ISSUE TITLE
Support seLinuxOptions for ceph osd pods created  via CephCluster(ceph.rook.io/v1)

### ISSUE THREAD

**Issue by abhijitchaudhari1** [rook/rook#8753]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently `seLinuxOptions`  under `securityContext` for  kubernetes resource `osd` (deployment) created via CRD: `CephCluster(ceph.rook.io/v1)` are not customisable. 

**What is use case behind this feature:**
 On selinux enabled systems,  the `block` device created under `dataDirHostPath` by the container gets random MCS label attached. If the osd pod using this device gets deleted , the new replacement pod will have a new MCS label and it will be denied the access to the block device when used without `privileged: true` config.

**Environment**:
Operator version: `rook/ceph:v1.5.9`
ceph osd version: `ceph/ceph:v15.2.9`

**Comment by leseb** [comment]
Can we force the same label?

**Comment by abhijitchaudhari1** [comment]
we need configurable `securityContext` option for this 

> Can we force the same label?

**Comment by travisn** [comment]
@abhijitchaudhari1 The OSDs should be run privileged currently. Are you not seeing them run privileged, or you want to remove the privileged mode and specify these specific privileges instead?

**Comment by FruityWelsh** [comment]
If this can help us move away from, ```privileged: true``` then this would be a huge help to me, as currently that is a big sticking point with security.

**Comment by leseb** [comment]
We are exploring reducing the permissions on various pods at the moment, this is not a trivial exercise but we hope to improve the situation. The goal is to remove the use of `privileged: true` whenever possible. As part of those investigation, we might need to expose `securityContext` for each daemon so that the SELinux options can be overridden.
