### ISSUE TITLE
cluster helm chart should support `mountOptions`.

### ISSUE THREAD

**Issue by Jean-Daniel** [rook/rook#8757]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

The helm chart to create block pools and associated storage class does not support specifying `mountOptions` in the storage class definition. (Values in cephBlockPools.storageClass.mountOptions are ignored).

**What is use case behind this feature:**

`mountOptions` is commonly use to set `discard` flag on mounted volumes, but can also be used to enforce some security restriction (`noexec`, …)

**Comment by leseb** [comment]
Just an FYI, it's not recommended to set `discard` as a mount option. It's really catastrophic for the performance and stability at scale. A better approach is to have a recurring job that reclaims space with `fstrim`. The Ceph-CSI is investigating this.

Other than that, seems like a legit request.
