### ISSUE TITLE
rgw-multisite-testing  CI failing on upstream PRs

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#8768]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

rgw-multisite-testing  CI fails with an error: 

```
+ CLUSTER_2_IP_ADDR=10.105.55.245
+ s3cmd --config=s3cfg --access_key=eVdyOkBVT3VRXjxEXSg= --secret_key=VUp8PEpXOmJfYj5hMnE2dEtlSC5KOy55OFhaNA== --host=10.105.55.245 get s3://bkt/1M.dat 1M-get.dat --force
ERROR: S3 error: 404 (NoSuchBucket)
+ diff 1M.dat 1M-get.dat
diff: 1M-get.dat: No such file or directory
+ echo 'Call to write_object_to_cluster1_read_from_cluster2 was not successful'
Call to write_object_to_cluster1_read_from_cluster2 was not successful
+ exit 1
```

Edit: `ERROR: S3 error: 403 (InvalidAccessKeyId)` at some runs it shows this message

**Expected behavior:**

Integration test rgw-multisite-testing should run as expected.

**How to reproduce it (minimal and precise):**
Some recent instances: https://github.com/rook/rook/pull/8646/checks?check_run_id=3661215439
                                      https://github.com/rook/rook/pull/8765/checks?check_run_id=3657616985

Maybe related to: https://bugzilla.redhat.com/show_bug.cgi

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by leseb** [comment]
Dup of https://github.com/rook/rook/issues/8671
