### ISSUE TITLE
outdated comment in mds code?

### ISSUE THREAD

**Issue by leseb** [rook/rook#8773]
Is this comment up to date?

https://github.com/rook/rook/blob/404dccdf2dc27ce028965e001b77bbf19a6e4c2b/pkg/operator/ceph/file/mds/mds.go#L252

Why don't we have any version check for Pacific?
Should we re-phrase/clarify?

@jshen28 @BlaineEXE

**Comment by jshen28** [comment]
I think we still need to wait for stand-replay daemon to become standby for pacific. the process might took sometime.
But honestly I haven't used pacific, so we might need another function to wait for completion..
