### ISSUE TITLE
CephObjectStore debugHTTPClient leaks admin credentials

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#8778]
The `debugHTTPClient` in the Ceph object store code can leak access credentials. See an operator log snippet below:

```
2021-09-21 17:41:27.430246 D | ceph-object-controller: creating s3 user object "rook-ceph-internal-s3-
user-checker-73dc21e6-95ec-49d6-a392-1ddeea6739de" for object store "ocs-storagecluster-cephobjectstor
e" health check
2021-09-21 17:41:27.430464 D | ceph-object-controller: 
GET /admin/user?display-name=rook-ceph-internal-s3-user-checker-73dc21e6-95ec-49d6-a392-1ddeea6739de&f
ormat=json&uid=rook-ceph-internal-s3-user-checker-73dc21e6-95ec-49d6-a392-1ddeea6739de HTTP/1.1
Host: rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc
User-Agent: Go-http-client/1.1
Authorization: AWS4-HMAC-SHA256 Credential=6ACH4N455IY3234IIFVP/20210921/default/s3/aws4_request, Sign
edHeaders=host;x-amz-content-sha256;x-amz-date, Signature=406e147687b0cc172c1fb6f49125a46ca5a4385af31f
9668499461550b4fea85
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210921T174127Z
Accept-Encoding: gzip


2021-09-21 17:41:27.475161 D | ceph-object-controller: 
HTTP/1.1 200 OK
Content-Length: 834
Connection: Keep-Alive
Date: Tue, 21 Sep 2021 17:41:27 GMT
X-Amz-Request-Id: tx000000000000000000004-00614a1947-1bce1-ocs-storagecluster-cephobjectstore

{"tenant":"","user_id":"rook-ceph-internal-s3-user-checker-73dc21e6-95ec-49d6-a392-1ddeea6739de","disp
lay_name":"rook-ceph-internal-s3-user-checker-73dc21e6-95ec-49d6-a392-1ddeea6739de","email":"","suspen
ded":0,"max_buckets":1000,"subusers":[],"keys":[{"user":"rook-ceph-internal-s3-user-checker-73dc21e6-9
5ec-49d6-a392-1ddeea6739de","access_key":"FAS2UVXRT8WTQDXOK89J","secret_key":"i9oZ97wZODWuzNfBNCTPixI3
MVbV831j5tqBQbXg"}],"swift_keys":[],"caps":[],"op_mask":"read, write, delete","system":"false","admin"
:"false","default_placement":"","default_storage_class":"","placement_tags":[],"bucket_quota":{"enable
d":false,"check_on_raw":false,"max_size":-1,"max_size_kb":0,"max_objects":-1},"user_quota":{"enabled":
false,"check_on_raw":false,"max_size":-1,"max_size_kb":0,"max_objects":-1},"temp_url_keys":[],"type":"
rgw","mfa_ids":[]}
```

### Initial analysis 
1. `"keys"` in the body at the bottom definitely leaks credentials. 

2. It is unclear to me whether the header log also is leaking sensitive credential info, but I do see that the `AWS4-HMAC-SHA256 Credential=6ACH4N455IY3234IIFVP/20210921/default/s3/aws4_request` line is consistent throughout the operator logs. This suggests to me that we should consider it sensitive info.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by BlaineEXE** [comment]
@leseb added this code in https://github.com/rook/rook/pull/8429. I'd like to get his opinions about how much of the debug info we need to keep in a redacted form.

**Comment by thotz** [comment]
Are you suggesting the `mask keys` info from the response given by RGW before dumping the response into log file

**Comment by leseb** [comment]
> Are you suggesting the `mask keys` info from the response given by RGW before dumping the response into log file

Can you clarify? I don't see this in the go-ceph binding nor in the API doc https://docs.ceph.com/en/mimic/radosgw/adminops/

**Comment by thotz** [comment]
> > Are you suggesting the `mask keys` info from the response given by RGW before dumping the response into log file
> 
> Can you clarify? I don't see this in the go-ceph binding nor in the API doc https://docs.ceph.com/en/mimic/radosgw/adminops/

Sorry, the above was kind of a question, whether masking is needed to resolve this issue. Like you mentioned I don't think currently adminops does not have the capability to do that.

**Comment by leseb** [comment]
> > > Are you suggesting the `mask keys` info from the response given by RGW before dumping the response into log file
> > 
> > 
> > Can you clarify? I don't see this in the go-ceph binding nor in the API doc https://docs.ceph.com/en/mimic/radosgw/adminops/
> 
> Sorry, the above was kind of a question, whether masking is needed to resolve this issue. Like you mentioned I don't think currently adminops does not have the capability to do that.

Right, I think it will be helpful. However, in some circumstances it's also useful to see which credentials are used...

**Comment by BlaineEXE** [comment]
Perhaps we can introduce TRACE logging to Rook and have this be part of that. I agree that it can be useful, but when we suggest users give us more info with DEBUG logs, it would be good not to leak sensitive info.

**Comment by leseb** [comment]
> Perhaps we can introduce TRACE logging to Rook and have this be part of that. I agree that the logging can be useful, but when we suggest users give us more info with DEBUG logs, it would be good not to leak sensitive info.
> 
> We should probably make the trace option be ROOK_LOG_LEVEL=INSECURE_TRACE or something similar so that it is clear from the option's input value that it is insecure.
> 
> For documentation, we could...
> 
> 1. Not document trace as a logging option in Rook
> 2. Document that trace logging exists and **is insecure**

TRACE looks good to me, I'd vote to hide it.
