### ISSUE TITLE
No RGW daemon found with user-defined host

### ISSUE THREAD

**Issue by 66545shiwo** [rook/rook#8782]
* Bug Report

Hi,
Ceph Dashboard can't display Object Gateway page and  I got a message :
```
The Object Gateway Service is not configured
No RGW daemon found with user-defined host: rook-ceph-rgw-my-store, port: 80
```

This is what i did : 
```
# get rgw service
kubectl get svc -n rook-ceph

rook-ceph-rgw-my-store             ClusterIP   10.101.150.150   <none>        80/TCP              45h
rook-ceph-rgw-my-store-external    NodePort    10.104.85.179    <none>        80:30255/TCP        44h

# into ceph-tools
kubectl -n rook-ceph exec -it $(kubectl -n rook-ceph get pod -l "app=rook-ceph-tools" -o jsonpath='{.items[0].metadata.name}') bash

# test rgw service in ceph-tools
curl rook-ceph-rgw-my-store.rook-ceph
<?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>anonymous</ID><DisplayName></DisplayName></Owner><Buckets></Buckets></ListAllMyBucketsResult>

# set rgw service host
ceph dashboard set-rgw-api-host rook-ceph-rgw-my-store.rook-ceph

# set rgw service port
ceph dashboard set-rgw-api-port 80

# set user access and secret
ceph dashboard set-rgw-api-user-id my-user
ceph dashboard set-rgw-api-access-key -i access.txt
ceph dashboard set-rgw-api-secret-key -i secret.txt

# restart dashboard
ceph mgr module disable dashboard
ceph mgr module enable dashboard
```
When i do these  using rook-ceph 1.6 , the Object Gateway page is OK.
But it doesn't work in rook-ceph 1.7.

**Environment**:
* OS (e.g. from /etc/os-release):  CentOS Linux release 7.9.2009 (Core)
* Kernel (e.g. `uname -a`):  4.19.12-1.el7.elrepo.x86_64 
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):  v1.7.3
* Storage backend version (e.g. for ceph do `ceph -v`):  ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable)
* Kubernetes version (use `kubectl version`):  v1.20.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by leseb** [comment]
@jmolmo PTAL.
