### ISSUE TITLE
Provide option to disable Liveness sidecar deployment in CSI

### ISSUE THREAD

**Issue by Madhu-1** [rook/rook#8783]
https://github.com/rook/rook/blob/6bcb569a888c5c9c132cd2c65ea2ceda419d2d52/pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml#L108-L129
https://github.com/rook/rook/blob/6bcb569a888c5c9c132cd2c65ea2ceda419d2d52/pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml#L158-L182
https://github.com/rook/rook/blob/master/pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml#L173-L192
https://github.com/rook/rook/blob/6bcb569a888c5c9c132cd2c65ea2ceda419d2d52/pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml#L109-L130

These are the sidecar containers that are deployed with the CSI pods and this is helpful to check csi driver is properly responding or not. and there is no liveness or readiness kubernetes probe added for this one. 
We can provide an option to Enable this sidecar deployment and disable it by default.

We don't need to create a [rbd service](https://github.com/rook/rook/blob/master/pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-svc.yaml) and [cephfs service](https://github.com/rook/rook/blob/master/pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-svc.yaml) if both liveness and GRPCmetrics are not enabled.

@travisn @leseb @BlaineEXE any comments?

**Comment by leseb** [comment]
Seems reasonable to me, any reason not to enable this by default?

**Comment by Madhu-1** [comment]
Not a problem to enable it by default. this is mostly useful for debugging. once we add liveness probe maybe we can enable it by default (just looking for an option to disable/enable)

**Comment by Madhu-1** [comment]
reopening this one, as its still makes sense to disable this one.

**Comment by travisn** [comment]
> reopening this one, as its still makes sense to disable this one.

Is there a particular need to disable the liveness probe? Or just nice to have as an option similar to the [cluster CR liveness probe options](https://github.com/rook/rook/blob/master/deploy/examples/cluster.yaml#L288-L294)?

**Comment by BlaineEXE** [comment]
From a previous discussion, should we disable the liveness probe by default and only enable it if requested?

**Comment by Madhu-1** [comment]
>Is there a particular need to disable the liveness probe? Or just nice to have as an option similar to the [cluster CR liveness probe options](https://github.com/rook/rook/blob/master/deploy/examples/cluster.yaml#L288-L294)?

> From a previous discussion, should we disable the liveness probe by default and only enable it if requested?

@travisn @BlaineEXE sorry missed replying here, this is not useful as it's not configured for the liveness probe or if someone's not consuming GRPC metrics for debugging. we should disable it by default as it avoids opening 2 node ports(one for cephfsplugin and one for rbdplugin) on all the nodes.

**Comment by travisn** [comment]
Sounds good to disable it by default, can we get this soon? Removed the keepalive label so the bot will remind us again if it's not done...

**Comment by Madhu-1** [comment]
@travisn https://github.com/rook/rook/pull/10647 is the fix for it
