### ISSUE TITLE
kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.rbd.csi.ceph.com not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by huangxuelun** [rook/rook#8791]
when ceph cluster is ready , I got an error- failed to provision volume with StorageClass "ceph-block": an operation with the given Volume ID pvc-ID already exists. then I run command in toolbox of rook **rbd pool init <pool>** ,then pv can be bounded to pvc. but got another error in pod kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.rbd.csi.ceph.com not found in the list of registered CSI drivers.
I use helm install the latest version of rook, just show toolbox, no other changes.
and I found the rook-ceph-mon-b and rook-ceph-osd-4 restarted a lot of times.
so How can I resolve it?

**Environment**:
* OS : CentOS Linux release 7.9.2009 (Core)
* Kernel : Linux 5.14.6-1.el7.elrepo.x86_64
* Cloud provider or hardware configuration: set up k8s 1.21.1 in virtualbox, 3 masters 3nodes.
* Rook version :ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable)
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.22.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): native k8s.
* ceph clust status:
HEALTH_WARN 1/4 mons down, quorum b,d,e; 1 osds down; 1 host (1 osds) down; Reduced data availability: 7 pgs inactive, 7 pgs peering; Degraded data redundancy: 3/63 objects degraded (4.762%), 2 pgs degraded; 33 daemons have recently crashed

**Comment by Madhu-1** [comment]
Do you have rbdplugin pod running on the node where pod is failing? If yes try to restart it (might help)

**Comment by huangxuelun** [comment]
csi-rbdplugin pod is running well. restarted them, the problem is still there.

**Comment by Madhu-1** [comment]
Can you please provide the log from all containers for the csi-rbdplugin pod?

**Comment by huangxuelun** [comment]
I0922 13:55:20.313472   24544 main.go:113] Version: v2.2.0
I0922 13:55:21.328708   24544 node_register.go:52] Starting Registration Server at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:21.329111   24544 node_register.go:61] Registration Server started at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:21.329371   24544 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I0922 13:55:20.013468   18764 main.go:113] Version: v2.2.0
I0922 13:55:21.025974   18764 node_register.go:52] Starting Registration Server at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:21.026409   18764 node_register.go:61] Registration Server started at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:21.027895   18764 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I0922 13:55:14.387272   22548 main.go:113] Version: v2.2.0
I0922 13:55:15.403607   22548 node_register.go:52] Starting Registration Server at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:15.404347   22548 node_register.go:61] Registration Server started at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:15.404637   22548 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I0922 13:55:12.922437     795 main.go:113] Version: v2.2.0
I0922 13:55:13.935952     795 node_register.go:52] Starting Registration Server at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:13.936586     795 node_register.go:61] Registration Server started at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:13.936798     795 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I0922 13:55:13.419224   23613 main.go:113] Version: v2.2.0
I0922 13:55:14.437896   23613 node_register.go:52] Starting Registration Server at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:14.438441   23613 node_register.go:61] Registration Server started at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:14.438809   23613 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I0922 13:55:12.113730    7799 main.go:113] Version: v2.2.0
I0922 13:55:13.140107    7799 node_register.go:52] Starting Registration Server at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:13.140682    7799 node_register.go:61] Registration Server started at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:13.141142    7799 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I0922 13:55:20.313472   24544 main.go:113] Version: v2.2.0
I0922 13:55:21.328708   24544 node_register.go:52] Starting Registration Server at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:21.329111   24544 node_register.go:61] Registration Server started at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0922 13:55:21.329371   24544 node_register.go:83] Skipping healthz server because HTTP endpoint is set to:

**Comment by Madhu-1** [comment]
Looks like the csidriver is not getting registered with kubelet. checking kubelet logs might help?  and also check if rbdplugin pod is getting restarted.

**Comment by huangxuelun** [comment]
Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2021-09-22 08:25:54 EDT; 2h 0min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 2032 (kubelet)
    Tasks: 21
   Memory: 206.6M
   CGroup: /system.slice/kubelet.service
           └─2032 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/ssl/bootstrap.kubeconfig --cert-dir=/etc/kubernetes/ssl --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/usr/local/bin/ --kubeconfig=/etc/kubernetes/ssl/kubelet.kubeconfig --config=/etc/kubernetes/kubelet.config.json --hostname-override=192.168.104.120 --pod-infra-container-image=192.168.104.122:5000/pause-amd64:3.1 --alsologtostderr=true --logtostderr=false --root-dir=/opt/kube-install/k8s/kubernetes/kubelet --log-dir=/opt/kube-install/k8s/kubernetes/kubelet --v=2

9月 22 09:56:02 master1 kubelet[2032]: I0922 09:56:02.523549    2032 container_manager_linux.go:510] "Discovered runtime cgroup name" cgroupName="/system.slice/docker.service"
9月 22 10:01:02 master1 kubelet[2032]: I0922 10:01:02.524115    2032 container_manager_linux.go:510] "Discovered runtime cgroup name" cgroupName="/system.slice/docker.service"
9月 22 10:06:02 master1 kubelet[2032]: I0922 10:06:02.528127    2032 container_manager_linux.go:510] "Discovered runtime cgroup name" cgroupName="/system.slice/docker.service"
9月 22 10:11:02 master1 kubelet[2032]: I0922 10:11:02.529863    2032 container_manager_linux.go:510] "Discovered runtime cgroup name" cgroupName="/system.slice/docker.service"
9月 22 10:14:53 master1 kubelet[2032]: I0922 10:14:53.933757    2032 logs.go:319] "Finished parsing log file" path="/opt/kube-install/k8s/docker/containerd/containers/088f3e08d228a996f0642044d7fcceba1e8aabf1ef872c607aa7ef78dfc6692d/088f3e08d228a996f0642044d7fcceba1e8aabf1ef872c607aa7ef78dfc6692d-json.log"
9月 22 10:14:53 master1 kubelet[2032]: I0922 10:14:53.956139    2032 logs.go:319] "Finished parsing log file" path="/opt/kube-install/k8s/docker/containerd/containers/6369bcf25605a0dee4db24948beda43cc1db039597fa3c8cf616c1abd5dace8b/6369bcf25605a0dee4db24948beda43cc1db039597fa3c8cf616c1abd5dace8b-json.log"
9月 22 10:14:53 master1 kubelet[2032]: I0922 10:14:53.997772    2032 logs.go:319] "Finished parsing log file" path="/opt/kube-install/k8s/docker/containerd/containers/e709165f4e0ae2d69292587203d3093bc9397074198bb10fecfb399226a25c1f/e709165f4e0ae2d69292587203d3093bc9397074198bb10fecfb399226a25c1f-json.log"
9月 22 10:16:02 master1 kubelet[2032]: I0922 10:16:02.531890    2032 container_manager_linux.go:510] "Discovered runtime cgroup name" cgroupName="/system.slice/docker.service"
9月 22 10:21:02 master1 kubelet[2032]: I0922 10:21:02.533975    2032 container_manager_linux.go:510] "Discovered runtime cgroup name" cgroupName="/system.slice/docker.service"
9月 22 10:26:02 master1 kubelet[2032]: I0922 10:26:02.540661    2032 container_manager_linux.go:510] "Discovered runtime cgroup name" cgroupName="/system.slice/docker.service"

**Comment by huangxuelun** [comment]
Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2021-09-22 08:25:52 EDT; 2h 1min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 2036 (kubelet)
    Tasks: 19
   Memory: 200.0M
   CGroup: /system.slice/kubelet.service
           └─2036 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/ssl/bootstrap.kubeconfig --cert-dir=/etc/kubernetes/ssl --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/usr/local/bin/ --kubeconfig=/etc/kubernetes/ssl/kubelet.kubeconfig --config=/etc/kubernetes/kubelet.config.json --hostname-override=192.168.104.121 --pod-infra-container-image=192.168.104.122:5000/pause-amd64:3.1 --alsologtostderr=true --logtostderr=false --root-dir=/opt/kube-install/k8s/kubernetes/kubelet --log-dir=/opt/kube-install/k8s/kubernetes/kubelet --v=2

9月 22 10:26:32 master2 kubelet[2036]: E0922 10:26:32.494353    2036 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"mon\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=mon pod=rook-ceph-mon-b-76986c5fd5-75dg9_rook-ceph(eb7e4400-6c7a-4610-add6-c0d60d62e715)\"" pod="rook-ceph/rook-ceph-mon-b-76986c5fd5-75dg9" podUID=eb7e4400-6c7a-4610-add6-c0d60d62e715
9月 22 10:26:47 master2 kubelet[2036]: I0922 10:26:47.491594    2036 scope.go:111] "RemoveContainer" containerID="cc18f615fd682c589dc759826950ae904c67eb037cd99a5ea113f78821df09d5"
9月 22 10:26:47 master2 kubelet[2036]: E0922 10:26:47.493218    2036 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"mon\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=mon pod=rook-ceph-mon-b-76986c5fd5-75dg9_rook-ceph(eb7e4400-6c7a-4610-add6-c0d60d62e715)\"" pod="rook-ceph/rook-ceph-mon-b-76986c5fd5-75dg9" podUID=eb7e4400-6c7a-4610-add6-c0d60d62e715
9月 22 10:26:54 master2 kubelet[2036]: I0922 10:26:54.918339    2036 reflector.go:225] Stopping reflector *v1.Secret (0s) from object-"rook-ceph"/"rook-ceph-config"
9月 22 10:27:00 master2 kubelet[2036]: I0922 10:27:00.491303    2036 scope.go:111] "RemoveContainer" containerID="cc18f615fd682c589dc759826950ae904c67eb037cd99a5ea113f78821df09d5"
9月 22 10:27:00 master2 kubelet[2036]: E0922 10:27:00.492500    2036 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"mon\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=mon pod=rook-ceph-mon-b-76986c5fd5-75dg9_rook-ceph(eb7e4400-6c7a-4610-add6-c0d60d62e715)\"" pod="rook-ceph/rook-ceph-mon-b-76986c5fd5-75dg9" podUID=eb7e4400-6c7a-4610-add6-c0d60d62e715
9月 22 10:27:14 master2 kubelet[2036]: I0922 10:27:14.494030    2036 scope.go:111] "RemoveContainer" containerID="cc18f615fd682c589dc759826950ae904c67eb037cd99a5ea113f78821df09d5"
9月 22 10:27:14 master2 kubelet[2036]: E0922 10:27:14.495622    2036 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"mon\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=mon pod=rook-ceph-mon-b-76986c5fd5-75dg9_rook-ceph(eb7e4400-6c7a-4610-add6-c0d60d62e715)\"" pod="rook-ceph/rook-ceph-mon-b-76986c5fd5-75dg9" podUID=eb7e4400-6c7a-4610-add6-c0d60d62e715
9月 22 10:27:26 master2 kubelet[2036]: I0922 10:27:26.494170    2036 scope.go:111] "RemoveContainer" containerID="cc18f615fd682c589dc759826950ae904c67eb037cd99a5ea113f78821df09d5"
9月 22 10:27:26 master2 kubelet[2036]: E0922 10:27:26.495324    2036 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"mon\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=mon pod=rook-ceph-mon-b-76986c5fd5-75dg9_rook-ceph(eb7e4400-6c7a-4610-add6-c0d60d62e715)\"" pod="rook-ceph/rook-ceph-mon-b-76986c5fd5-75dg9" podUID=eb7e4400-6c7a-4610-add6-c0d60d62e715

**Comment by Madhu-1** [comment]
Have you changed the kubelet path at https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L96 to `/opt/kube-install/k8s/kubernetes/kubelet` if not that is the issue

**Comment by huangxuelun** [comment]
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2021-09-22 08:25:52 EDT; 2h 13min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 2073 (kubelet)
    Tasks: 18
   Memory: 201.9M
   CGroup: /system.slice/kubelet.service
           └─2073 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/ssl/bootstrap.kubeconfig --cert-dir=/etc/kubernetes/ssl --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/usr/local/bin/ --kubeconfig=/etc/kubernetes/ssl/kubelet.kubeconfig --config=/etc/kubernetes/kubelet.config.json --hostname-override=192.168.104.122 --pod-infra-container-image=192.168.104.122:5000/pause-amd64:3.1 --alsologtostderr=true --logtostderr=false --root-dir=/opt/kube-install/k8s/kubernetes/kubelet --log-dir=/opt/kube-install/k8s/kubernetes/kubelet --v=2

9月 22 10:37:44 master3 kubelet[2073]: I0922 10:37:44.364683    2073 kubelet.go:1970] "SyncLoop (PLEG): event for pod" pod="rook-ceph/rook-ceph-osd-4-695bf8d478-dqnkj" event=&{ID:3e57fa54-4962-4c65-8012-634a5e88fb7a Type:ContainerDied Data:4ef53305d2b7e7cbb47686f5a88e5daab1523b18ec62867a188e0a97e1c891f8}
9月 22 10:37:44 master3 kubelet[2073]: I0922 10:37:44.364907    2073 kubelet.go:1970] "SyncLoop (PLEG): event for pod" pod="rook-ceph/rook-ceph-osd-4-695bf8d478-dqnkj" event=&{ID:3e57fa54-4962-4c65-8012-634a5e88fb7a Type:ContainerStarted Data:5a9e285fefe11cad367f814f84b6396c596c68752f19de06418c1706b5d82b73}
9月 22 10:37:44 master3 kubelet[2073]: I0922 10:37:44.364954    2073 scope.go:111] "RemoveContainer" containerID="a5b320b3721dc41d615e42744f997ee4b1dc53999bc751ddffb8fc087e27a6b3"
9月 22 10:38:33 master3 kubelet[2073]: I0922 10:38:33.096917    2073 prober.go:116] "Probe failed" probeType="Liveness" pod="rook-ceph/rook-ceph-osd-4-695bf8d478-dqnkj" podUID=3e57fa54-4962-4c65-8012-634a5e88fb7a containerName="osd" probeResult=failure output="admin_socket: exception getting command descriptions: [Errno 2] No such file or directory\n"
9月 22 10:38:43 master3 kubelet[2073]: I0922 10:38:43.201552    2073 prober.go:116] "Probe failed" probeType="Liveness" pod="rook-ceph/rook-ceph-osd-4-695bf8d478-dqnkj" podUID=3e57fa54-4962-4c65-8012-634a5e88fb7a containerName="osd" probeResult=failure output="admin_socket: exception getting command descriptions: [Errno 2] No such file or directory\n"
9月 22 10:38:53 master3 kubelet[2073]: I0922 10:38:53.134327    2073 prober.go:116] "Probe failed" probeType="Liveness" pod="rook-ceph/rook-ceph-osd-4-695bf8d478-dqnkj" podUID=3e57fa54-4962-4c65-8012-634a5e88fb7a containerName="osd" probeResult=failure output="admin_socket: exception getting command descriptions: [Errno 2] No such file or directory\n"
9月 22 10:38:53 master3 kubelet[2073]: I0922 10:38:53.134453    2073 kubelet.go:2026] "SyncLoop (probe)" probe="liveness" status="unhealthy" pod="rook-ceph/rook-ceph-osd-4-695bf8d478-dqnkj"
9月 22 10:38:53 master3 kubelet[2073]: I0922 10:38:53.136179    2073 kuberuntime_manager.go:683] "Message for Container of pod" containerName="osd" containerStatusID={Type:docker ID:5a9e285fefe11cad367f814f84b6396c596c68752f19de06418c1706b5d82b73} pod="rook-ceph/rook-ceph-osd-4-695bf8d478-dqnkj" containerMessage="Container osd failed liveness probe, will be restarted"
9月 22 10:38:53 master3 kubelet[2073]: I0922 10:38:53.136269    2073 kuberuntime_container.go:661] "Killing container with a grace period override" pod="rook-ceph/rook-ceph-osd-4-695bf8d478-dqnkj" podUID=3e57fa54-4962-4c65-8012-634a5e88fb7a containerName="osd" containerID="docker://5a9e285fefe11cad367f814f84b6396c596c68752f19de06418c1706b5d82b73" gracePeriod=30
9月 22 10:39:23 master3 kubelet[2073]: E0922 10:39:23.348095    2073 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"osd\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=osd pod=rook-ceph-osd-4-695bf8d478-dqnkj_rook-ceph(3e57fa54-4962-4c65-8012-634a5e88fb7a)\"" pod="rook-ceph/rook-ceph-osd-4-695bf8d478-dqnkj" podUID=3e57fa54-4962-4c65-8012-634a5e88fb7a

**Comment by huangxuelun** [comment]
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2021-09-22 08:25:48 EDT; 2h 18min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 1777 (kubelet)
    Tasks: 17
   Memory: 197.7M
   CGroup: /system.slice/kubelet.service
           └─1777 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/ssl/bootstrap.kubeconfig --cert-dir=/etc/kubernetes/ssl --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/usr/local/bin/ --kubeconfig=/etc/kubernetes/ssl/kubelet.kubeconfig --config=/etc/kubernetes/kubelet.config.json --hostname-override=192.168.104.125 --pod-infra-container-image=192.168.104.122:5000/pause-amd64:3.1 --alsologtostderr=true --logtostderr=false --root-dir=/opt/kube-install/k8s/kubernetes/kubelet --log-dir=/opt/kube-install/k8s/kubernetes/kubelet --v=2

9月 22 10:43:14 node3 kubelet[1777]: I0922 10:43:14.599243    1777 operation_generator.go:575] MountVolume.WaitForAttach entering for volume "pvc-f36a9010-6ae0-4d5e-99d7-214feeeaf84c" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a307a418-1add-11ec-bf51-6a9db92edd70") pod "nacos-0" (UID: "36556523-0a73-41f6-9c43-9a37558ed0df") DevicePath ""
9月 22 10:43:14 node3 kubelet[1777]: I0922 10:43:14.600123    1777 operation_generator.go:575] MountVolume.WaitForAttach entering for volume "pvc-69da3e22-ca10-48ed-a80a-5e4dbe32de99" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a307b7a8-1add-11ec-bf51-6a9db92edd70") pod "nacos-0" (UID: "36556523-0a73-41f6-9c43-9a37558ed0df") DevicePath ""
9月 22 10:43:14 node3 kubelet[1777]: I0922 10:43:14.609220    1777 operation_generator.go:585] MountVolume.WaitForAttach succeeded for volume "pvc-69da3e22-ca10-48ed-a80a-5e4dbe32de99" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a307b7a8-1add-11ec-bf51-6a9db92edd70") pod "nacos-0" (UID: "36556523-0a73-41f6-9c43-9a37558ed0df") DevicePath "csi-4ef4a2673af2433bee11faba2d7c419bea48d2ffdb75817c53600a8141004280"
9月 22 10:43:14 node3 kubelet[1777]: E0922 10:43:14.609735    1777 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a307b7a8-1add-11ec-bf51-6a9db92edd70 podName: nodeName:}" failed. No retries permitted until 2021-09-22 10:45:16.609692152 -0400 EDT m=+8367.257478350 (durationBeforeRetry 2m2s). Error: "MountVolume.MountDevice failed for volume \"pvc-69da3e22-ca10-48ed-a80a-5e4dbe32de99\" (UniqueName: \"kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a307b7a8-1add-11ec-bf51-6a9db92edd70\") pod \"nacos-0\" (UID: \"36556523-0a73-41f6-9c43-9a37558ed0df\") : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.rbd.csi.ceph.com not found in the list of registered CSI drivers"
9月 22 10:43:14 node3 kubelet[1777]: I0922 10:43:14.610095    1777 operation_generator.go:585] MountVolume.WaitForAttach succeeded for volume "pvc-8efb927d-c423-40d3-a9de-29cdc95ef3a7" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a3081c1d-1add-11ec-bf51-6a9db92edd70") pod "nacos-0" (UID: "36556523-0a73-41f6-9c43-9a37558ed0df") DevicePath "csi-883cc272bf92dd6a5d962777047336f78780f20835e6f46e1869c2a4d479fe8d"
9月 22 10:43:14 node3 kubelet[1777]: E0922 10:43:14.610575    1777 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a3081c1d-1add-11ec-bf51-6a9db92edd70 podName: nodeName:}" failed. No retries permitted until 2021-09-22 10:45:16.610531198 -0400 EDT m=+8367.258317380 (durationBeforeRetry 2m2s). Error: "MountVolume.MountDevice failed for volume \"pvc-8efb927d-c423-40d3-a9de-29cdc95ef3a7\" (UniqueName: \"kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a3081c1d-1add-11ec-bf51-6a9db92edd70\") pod \"nacos-0\" (UID: \"36556523-0a73-41f6-9c43-9a37558ed0df\") : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.rbd.csi.ceph.com not found in the list of registered CSI drivers"
9月 22 10:43:14 node3 kubelet[1777]: I0922 10:43:14.614731    1777 operation_generator.go:585] MountVolume.WaitForAttach succeeded for volume "pvc-f36a9010-6ae0-4d5e-99d7-214feeeaf84c" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a307a418-1add-11ec-bf51-6a9db92edd70") pod "nacos-0" (UID: "36556523-0a73-41f6-9c43-9a37558ed0df") DevicePath "csi-e63e1dc2a40ec5b4fa89891f0fdee26cc7ddfd513ff3b1409c19fc52f021af6d"
9月 22 10:43:14 node3 kubelet[1777]: E0922 10:43:14.615325    1777 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a307a418-1add-11ec-bf51-6a9db92edd70 podName: nodeName:}" failed. No retries permitted until 2021-09-22 10:45:16.615268534 -0400 EDT m=+8367.263054745 (durationBeforeRetry 2m2s). Error: "MountVolume.MountDevice failed for volume \"pvc-f36a9010-6ae0-4d5e-99d7-214feeeaf84c\" (UniqueName: \"kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000002-a307a418-1add-11ec-bf51-6a9db92edd70\") pod \"nacos-0\" (UID: \"36556523-0a73-41f6-9c43-9a37558ed0df\") : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name rook-ceph.rbd.csi.ceph.com not found in the list of registered CSI drivers"
9月 22 10:43:40 node3 kubelet[1777]: E0922 10:43:40.102884    1777 kubelet.go:1701] "Unable to attach or mount volumes for pod; skipping pod" err="unmounted volumes=[finder data logs], unattached volumes=[finder kube-api-access-zz57v data logs]: timed out waiting for the condition" pod="default/nacos-0"
9月 22 10:43:40 node3 kubelet[1777]: E0922 10:43:40.104255    1777 pod_workers.go:190] "Error syncing pod, skipping" err="unmounted volumes=[finder data logs], unattached volumes=[finder kube-api-access-zz57v data logs]: timed out waiting for the condition" pod="default/nacos-0" podUID=36556523-0a73-41f6-9c43-9a37558ed0df

**Comment by huangxuelun** [comment]
yes I changed the kubelet installation path.  what I should do?

**Comment by huangxuelun** [comment]
you're right. now works well. thanks.
