### ISSUE TITLE
stop using "tini"?

### ISSUE THREAD

**Issue by leseb** [rook/rook#8794]
We don't have anything in the rook operator that would either create zombie processes (no threads) or use `exec` (to fork). The Go binary has a really good signal handling mechanism. Honestly, I'm not why Rook ever needed to use `tiny` in the first place. Legacy maybe?

So I suggest we remove it, one less dependency to execute the operator.

All the other places using `tini` could implement a simple signal handler.

**Comment by leseb** [comment]
@BlaineEXE @travisn throughts?

**Comment by satoru-takeuchi** [comment]
I've also thought why Rook has used `tini`. It's nice to remove this if there is no strong reason.

**Comment by travisn** [comment]
As I recall, it was really a concern when ceph daemons were started by Rook. Now it's only the operator and toolbox pods that are even running the rook image with tini. 

The operator and toolbox pods do create a lot of processes though as they shell out to `ceph` and related commands. If we did remove tini, wouldn't we still be at risk of zombie processes over time?

**Comment by leseb** [comment]
> As I recall, it was really a concern when ceph daemons were started by Rook. Now it's only the operator and toolbox pods that are even running the rook image with tini.
> 
> The operator and toolbox pods do create a lot of processes though as they shell out to `ceph` and related commands. If we did remove tini, wouldn't we still be at risk of zombie processes over time?

We do shell out but we don't `exec` so there is no fork and the `rook` process is the parent
