### ISSUE TITLE
Can't connect to rook-ceph cluster from host network (outside kubernetes)

### ISSUE THREAD

**Issue by Azhdar1990** [rook/rook#8802]
Hello
I deployed rook-ceph in my kubernetes.
Ceph available in cluster.
I want to connect to ceph cluster and ceph  dashboard from host network.
I configured:

cluster.yaml
	network:
  	  provider:host
common.yaml
	hostNetwork: true
operator.yaml
	hostNetwork: true

After redeploy, ceph cluster still not available from host network.
I check it by using nmap

root@ubuntu:~# nmap 10.0.45.24 -p 6789
Nmap scan report for 10.0.45.24
Host is up (0.00014s latency).

PORT     STATE  SERVICE
6789/tcp closed ibm-db2-admin

Nmap done: 1 IP address (1 host up) scanned in 0.60 seconds

10.0.45.24 is ip of one worker node where ceph monitor is deployed.

Could you help ?

ENV
Kubernetes:
masternode1  v1.21.5   Ubuntu 21.04   containerd://1.4.9
masternode2  v1.21.5   Ubuntu 21.04   containerd://1.4.9
masternode3  v1.21.5   Ubuntu 21.04   containerd://1.4.9
workernode1  v1.21.5   Ubuntu 21.04   containerd://1.4.9
workernode2  v1.21.5   Ubuntu 21.04   containerd://1.4.9
workernode3  v1.21.5   Ubuntu 21.04   containerd://1.4.9

ceph:v16.2.5
3 mon
3 osd (one per worker node)

**Comment by travisn** [comment]
@Azhdar1990 When you redeployed, did you follow the [cleanup guide](https://rook.github.io/docs/rook/v1.7/ceph-teardown.html)? If not, perhaps the host network settings didn't fully take effect when you redeployed. Also, check the logs of the mgr pod to see what ip the dashboard service bound to.

**Comment by voarsh2** [comment]
Just chiming in here to ask if this all means that once you've deployed Rook Ceph you can't change it without tearing it all down (any data loss to the OSD's?)?

**Comment by travisn** [comment]
@voarsh2 Changing the host networking setting is not supported in a running cluster. It may be possible, but would be a complex process to update the mons with new ips.
