### ISSUE TITLE
Rook operator does not install all the required resources properly

### ISSUE THREAD

**Issue by Atharex** [rook/rook#8819]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The operator does not install necessary secrets & services properly and storage provisioning does not work.
e.g. 
`ResourceVersion:"509425", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-ceph-rwo": error getting secret rook-csi-rbd-provisioner in namespace rook-ceph: secrets "rook-csi-rbd-provisioner" not found`

After restarting the operator pod this secret is created and another error crops up:

```
debug 2021-09-24T09:38:27.918+0000 7fc9b5be8700 -1 log_channel(cluster) log [ERR] : Health check failed: 1 filesystem is offline (MDS_ALL_DOWN)
cluster 2021-09-24T09:38:27.920462+0000 mon.a (mon.0) 961 : cluster [ERR] Health check failed: 1 filesystem is offline (MDS_ALL_DOWN)
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] : Health detail: HEALTH_ERR 1 filesystem is offline; 1 filesystem is online with fewer MDS than max_mds; no active mgr; clock skew detected on mon.b, mon.c; 1441 slow ops, oldest one blocked for 3508 sec, mon.c has slow ops; OSD count 1 < osd_pool_default_size 3
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] : [ERR] MDS_ALL_DOWN: 1 filesystem is offline
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] :     fs rook-ceph-fs is offline because no MDS is active for it.
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] : [WRN] MDS_UP_LESS_THAN_MAX: 1 filesystem is online with fewer MDS than max_mds
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] :     fs rook-ceph-fs has 0 MDS online, but wants 1
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] : [WRN] MGR_DOWN: no active mgr
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] : [WRN] MON_CLOCK_SKEW: clock skew detected on mon.b, mon.c
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] :     mon.b clock skew 0.422085s > max 0.05s (latency 0.00116195s)
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] :     mon.c clock skew 5.69288s > max 0.05s (latency 0.00138403s)
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] : [WRN] SLOW_OPS: 1441 slow ops, oldest one blocked for 3508 sec, mon.c has slow ops
debug 2021-09-24T09:39:59.999+0000 7fc9b83ed700 -1 log_channel(cluster) log [ERR] : [WRN] TOO_FEW_OSDS: OSD count 1 < osd_pool_default_size 3
```

Taking a look at the manager pod it seems again some resources from the operator are missing:
```
kubectl logs -n rook-ceph rook-ceph-mgr-a-98bfc9f9c-hdwsw watch-active
2021-09-24 09:37:38.599773 I | op-flags: failed to set flag "logtostderr". no such flag -logtostderr
2021-09-24 09:37:38.601463 I | op-mon: parsing mon endpoints: a=10.80.95.127:6789,b=10.80.10.171:6789,c=10.80.205.181:6789
2021-09-24 09:37:38.601586 I | rookcmd: starting Rook v1.7.3 with arguments '/usr/local/bin/rook ceph mgr watch-active'
2021-09-24 09:37:38.601605 I | rookcmd: flag values: --ceph-version=ceph version 16.2.6-0 pacific, --cluster-id=ce46ba76-65d5-493b-a363-f746a0d6129b, --cluster-name=rook-ceph, --daemon-name=a, --dashboard-enabled=true, --help=false, --log-level=INFO, --monitoring-enabled=false, --operator-image=, --service-account=, --update-interval=15s
2021-09-24 09:37:38.612130 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2021-09-24 09:37:38.612229 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2021-09-24 09:37:38.614636 E | op-mgr: failed to check current mgr service, proceeding to update. services "rook-ceph-mgr" not found
2021-09-24 09:37:38.883945 E | cephcmd: failed to reconcile services. active mgr not found
2021-09-24 09:37:53.887481 E | op-mgr: failed to check current mgr service, proceeding to update. services "rook-ceph-mgr" not found
```

And even though my dashboard service is set to enabled, it is also missing in the deployment:
```
kubectl get svc -n rook-ceph
NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
csi-cephfsplugin-metrics   ClusterIP   10.80.120.111   <none>        8080/TCP,8081/TCP   88m
csi-rbdplugin-metrics      ClusterIP   10.80.15.132    <none>        8080/TCP,8081/TCP   88m
rook-ceph-mon-a            ClusterIP   10.80.95.127    <none>        6789/TCP,3300/TCP   88m
rook-ceph-mon-b            ClusterIP   10.80.10.171    <none>        6789/TCP,3300/TCP   88m
rook-ceph-mon-c            ClusterIP   10.80.205.181   <none>        6789/TCP,3300/TCP   88m
```

**Expected behavior:**
All necessary resources are present.

**How to reproduce it (minimal and precise):**
Installation steps:
`1) helm install rook-ceph rook-release/rook-ceph --create-namespace --namespace rook-ceph -f rook-config.txt  --version 1.7.3`
[rook-config.txt](https://github.com/rook/rook/files/7224939/rook-config.txt)

`2) kubectl apply -f ceph-cluster.txt`
[ceph-cluster.txt](https://github.com/rook/rook/files/7224954/ceph-cluster.txt)

`3) kubectl apply -f block-pool-txt`
[ceph-block-pool.txt](https://github.com/rook/rook/files/7224966/ceph-block-pool.txt)

`4) kubectl apply -f rwo-storage-class.txt`
[ceph-storage-class-rwo.txt](https://github.com/rook/rook/files/7224980/ceph-storage-class-rwo.txt)

`5) Install any deployment that provisions a PVC and see it stay in pending state`

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7 
* Kernel (e.g. `uname -a`): 3.10.0-1160.42.2.el7.x86_64
* Cloud provider or hardware configuration:  bare-metal
* Rook version (use `rook version` inside of a Rook Pod):  v1.7.3
* Storage backend version (e.g. for ceph do `ceph -v`):  v16.2.6
* Kubernetes version (use `kubectl version`): v1.19.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm
* Storage - empty disk device /dev/sdb on 4 worker nodes

**Comment by Madhu-1** [comment]
@Atharex can you please provide rook operator pod logs?

**Comment by Atharex** [comment]
Sure, here are the logs after the 2nd restart
[rook-operator-logs.txt](https://github.com/rook/rook/files/7225463/rook-operator-logs.txt)

**Comment by travisn** [comment]
@Atharex The operator seems stuck reconciling the mons, which usually means they are not forming quorum. 
- Are you able to get a response from `ceph status` or similar commands in the toolbox? 
- You have two mgr pods? How many OSD pods?

[This topic](https://rook.github.io/docs/rook/v1.7/ceph-common-issues.html#monitors-are-the-only-pods-running) may help troubleshooting the mon quorum.
