### ISSUE TITLE
Support for encrypted RBDs

### ISSUE THREAD

**Issue by CO-lhagman** [rook/rook#8822]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Implement an option to use encrypted RBDs that were introduced in Ceph Pacific https://docs.ceph.com/en/latest/rbd/rbd-encryption/ . Keys could be stored in a vault.

**What is use case behind this feature:**
This would allow for on-wire encryption of the traffic which would be useful in multi-tenant environments (especially with external ceph clusters).

**Comment by leseb** [comment]
If this has to be implemented it's a Ceph-CSI feature. Last time I discussed with them they had no plans to use the new "native" encryption since they already have more or less the same with crypsetup/LUKS/Device mapper.

Please open an issue at https://github.com/ceph/ceph-csi instead.
