### ISSUE TITLE
rook-ceph : How to redeploy MDS?

### ISSUE THREAD

**Issue by osaffer** [rook/rook#8826]
Hello,

How is it possible to redeploy the mds ? 

Thank you

**Comment by BlaineEXE** [comment]
This seems like it might be more appropriate as a https://github.com/rook/rook/discussions. 

My first question is "Why do you want to redeploy the mds?" In theory, you can just delete the deployment and restart the operator, but I can't guarantee that this won't break the cluster.

**Comment by BlaineEXE** [comment]
I'm going to close this. If you have further questions, please open a discussion for this.

**Comment by osaffer** [comment]
Thank you, this is what I did, I restarted the pod operator, but MDS have not been restarted.

I will open a discussion for that purpose.

Regards
