### ISSUE TITLE
Rook Operator should be included in OperatorHub for OKD

### ISSUE THREAD

**Issue by sandrobonazzola** [rook/rook#8894]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Rook Operator should be included in OperatorHub making it easy for OKD users to get it installed.

**What is use case behind this feature:**

Slelecting the storage provider for running VMs on OKD as part of OKD Virtualization.
The Kubevirt Hyperconverged Cluster Operator is available on OperatorHub but then when you need to select a storage provider for running VMs Rook is not available there.

**Environment**:
Bare metal UPI deployment for running OKD Virtualization.

**Comment by leseb** [comment]
It's already included I believe but it's really outdated https://operatorhub.io/operator/rook-ceph

**Comment by sandrobonazzola** [comment]
Here's the storage group in OKD 4.8
![Schermata da 2021-10-01 09-03-41](https://user-images.githubusercontent.com/937860/135579313-eada69bb-f74b-4ebe-bd8e-58287df24643.png)
:

**Comment by sandrobonazzola** [comment]
I think that OKD is not using https://operatorhub.io/ ; I see Ember CSI Operator 0.9.4 on https://operatorhub.io/ while in OKD there is 0.9.6.

**Comment by fabiand** [comment]
The rook-ceph operator that @leseb is referencin is quite old "2019-09-23T11-51-58Z", and it might simply be in the wrong catalog and therefore not turn up in OKD.

Because it's so old it does also not make sense to blindly included it.

@leseb who can help to get an up to date operator into the OKD catalog?

**Comment by leseb** [comment]
> The rook-ceph operator that @leseb is referencin is quite old "2019-09-23T11-51-58Z", and it might simply be in the wrong catalog and therefore not turn up in OKD.
> 
> Because it's so old it does also not make sense to blindly included it.
> 
> @leseb who can help to get an up to date operator into the OKD catalog?

I originally sent the PR in operator hub so I guess I can follow up whenever the time permits it.

**Comment by leseb** [comment]
Actually, this is a dup of https://github.com/rook/rook/issues/3197. @fabiand @sandrobonazzola do you mind continuing the discussion there and close this? Thanks.

**Comment by fabiand** [comment]
Please close it as a dupe, sounds fair
