### ISSUE TITLE
Size missing when PVC is not connected to any POD

### ISSUE THREAD

**Issue by grzesiekpaldyna** [rook/rook#8899]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

PVC Used metric is disappearing when it is not mounted on any pod.
![obraz](https://user-images.githubusercontent.com/82332465/135538764-29eb4a98-6d6e-4eb5-bd69-8bb59464fa1e.png)

**Expected behavior:**

PVC Used metric is still visable after deleting pod.
![obraz](https://user-images.githubusercontent.com/82332465/135539435-2046e210-3393-4ab5-bdef-c3830cda9dab.png)

**How to reproduce it (minimal and precise):**

1. Configure External Ceph Cluster.
2. Create StorageClass.
3. Create PVC.
4. Attach PVC to pod and add some files.
5. PVC Used size metric is showing correctly.
6. Delete pod.
7. PVC Used metric is showing - 

**Environment**:
* OS: CoreOS
* Rook version: v1.5.12
* Storage backend version: 15.2.13
* Kubernetes version: v1.20.0
* Kubernetes cluster type: OpenShift version 4.7.31
* Storage backend status: OK

**Comment by BlaineEXE** [comment]
@Madhu-1 is this a CSI behavior or a Kubernetes behavior?

**Comment by Rakshith-R** [comment]
@grzesiekpaldyna , volume metrics are only available when it is mounted to a pod.
