### ISSUE TITLE
PV creation failure after nodes restarted

### ISSUE THREAD

**Issue by mmueen** [rook/rook#8912]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After node restart ceph rbd plugin fails to provision any PV.

**Expected behavior:**
After node restarts PV / PVC creation should succeed normally.

**How to reproduce it (minimal and precise):**
A working rook-ceph cluster. nodes are restarted. Afterwards:

1. PVC created via manifest.
2. rbd-provisioner starts provisioning pv.
3. doesn't receive a response and errors out "deadline exceeded"
4. rbd-provisioner retries to provision PV.
5. gets error that an operation to create this PV already exists.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS
* Kernel (e.g. `uname -a`): 5.4.128-flush
* Cloud provider or hardware configuration: Dell R630 Server
* Rook version (use `rook version` inside of a Rook Pod): rook: 0 / go: go1.16.3
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.5
* Kubernetes version (use `kubectl version`): v1.19.7-gke.1200
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE / Anthos
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_WARN Reduced data availability: 14 pgs inactive; Degraded data redundancy: 17/78 objects degraded (21.795%), 11 pgs degraded, 55 pgs undersized; 61 slow ops, oldest one blocked for 54866 se
c, osd.3 has slow ops

Context:
A K8s cluster with 1 master / 2 worker is deployed. OSDs are created on the 2 worker nodes. rook ceph cluster is deployed (cluster information in environment section above). After nodes restarted recently PVC creation is failing with `context exceeded` errors. The pods in rook-ceph namespace seem to be running with no failed pod. 

Here are the logs from the `rbd-provisioner` pod logs 

```
I1004 15:37:07.143245       1 controller.go:1332] provision "default/test-pvc" class "rook-ceph-block": started
I1004 15:37:07.143364       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-pvc", UID:"c82b8132-a1ed-4ca0-ba9c-09e9f476fffb", APIVersion:"v1", ResourceVersion:"115592826", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test-pvc"
W1004 15:39:37.147065       1 controller.go:958] Retrying syncing claim "c82b8132-a1ed-4ca0-ba9c-09e9f476fffb", failure 0
E1004 15:39:37.147095       1 controller.go:981] error syncing claim "c82b8132-a1ed-4ca0-ba9c-09e9f476fffb": failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1004 15:39:37.147138       1 controller.go:1332] provision "default/test-pvc" class "rook-ceph-block": started
I1004 15:39:37.147138       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-pvc", UID:"c82b8132-a1ed-4ca0-ba9c-09e9f476fffb", APIVersion:"v1", ResourceVersion:"115592826", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = DeadlineExceeded desc= context deadline exceeded
I1004 15:39:37.147254       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-pvc", UID:"c82b8132-a1ed-4ca0-ba9c-09e9f476fffb", APIVersion:"v1", ResourceVersion:"115592826", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test-pvc"
W1004 15:39:37.151793       1 controller.go:958] Retrying syncing claim "c82b8132-a1ed-4ca0-ba9c-09e9f476fffb", failure 1
E1004 15:39:37.151812       1 controller.go:981] error syncing claim "c82b8132-a1ed-4ca0-ba9c-09e9f476fffb": failed to provision volume with StorageClass "rook-ceph-block": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-c82b8132-a1ed-4ca0-ba9c-09e9f476fffb already exists
```

Here is the manifest yaml used to create PVC and pod.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: test-pvc
spec:
 storageClassName: rook-ceph-block
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
    - name: test-pv-storage
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/mnt"
          name: test-pv-storage
```

Here is the display of pvc failures.

```
$ k get pvc -A
NAMESPACE     NAME                                                       STATUS    VOLUME              CAPACITY   ACCESS MODES   STORAGECLASS      AGE
default       test-pvc                                                   Pending                                                 rook-ceph-block   52m

$ k describe pvc test-pvc
Name:          test-pvc
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       test-pod
Events:
  Type     Reason                Age                    From                                                                                                        Message
  ----     ------                ----                   ----                                                                                                        -------
  Warning  ProvisioningFailed    50m                    rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6799bd4cb7-vc4c4_f142e3ec-e6de-484a-8155-e8c8bc592491  failed to provision volume with
StorageClass "rook-ceph-block": rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  ProvisioningFailed    26m (x14 over 50m)     rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6799bd4cb7-vc4c4_f142e3ec-e6de-484a-8155-e8c8bc592491  failed to provision volume with
StorageClass "rook-ceph-block": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-f70bb30c-df49-435c-803b-bc6eba233108 already exists
  Normal   ExternalProvisioning  2m26s (x203 over 52m)  persistentvolume-controller                                                                                 waiting for a volume to be creat
ed, either by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning          91s (x22 over 52m)     rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6799bd4cb7-vc4c4_f142e3ec-e6de-484a-8155-e8c8bc592491  External provisioner is provisio
ning volume for claim "default/test-pvc"
```

**Comment by travisn** [comment]
Please see #8696 as this seems like the same issue. This is expected to be fixed in v1.7.5 in the next few days...

**Comment by mmueen** [comment]
Thank you. I tried the workaround mentioned here but it doesn't seem to work.

```
[root@rook-ceph-tools-78cdfd976c-s8495 /]# ceph osd lspools
1 device_health_metrics
2 fs-metadata
3 fs-data0
5 replicapool

[root@rook-ceph-tools-78cdfd976c-s8495 /]# rbd pool init replicapool
[root@rook-ceph-tools-78cdfd976c-s8495 /]# exit

$ kubectl -n rook-ceph delete pods -l app=csi-rbdplugin-provisioner
pod "csi-rbdplugin-provisioner-6799bd4cb7-4dvjx" deleted
pod "csi-rbdplugin-provisioner-6799bd4cb7-b2qdr" deleted
```
Afterwards created a pvc and it still stays in pending state

```
$ k describe pvc test-pvc
Name:          test-pvc
Namespace:     default
StorageClass:  rook-ceph-block
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type    Reason                Age                From                                                                                                        Message
  ----    ------                ----               ----                                                                                                        -------
  Normal  Provisioning          27s                rook-ceph.rbd.csi.ceph.com_csi-rbdplugin-provisioner-6799bd4cb7-49vrs_aa93a5f2-247b-48c3-b677-620d182c0f95  External provisioner is provisioning
volume for claim "default/test-pvc"
  Normal  ExternalProvisioning  14s (x2 over 27s)  persistentvolume-controller                                                                                 waiting for a volume to be created, e
ither by external provisioner "rook-ceph.rbd.csi.ceph.com" or manually created by system administrator
```

**Comment by Rakshith-R** [comment]
@mmueen 

>Rook version (use rook version inside of a Rook Pod): rook: 0 / go: go1.16.3

Rook version is missing

>Storage backend status (e.g. for Ceph use ceph health in the Rook Ceph toolbox): HEALTH_WARN Reduced data availability: 14 pgs inactive; Degraded data redundancy: 17/78 objects degraded (21.795%), 11 pgs degraded, 55 pgs undersized; 61 slow ops, oldest one blocked for 54866 se
c, osd.3 has slow ops

Fix ceph health, then try again ? 

Bump up log level to 5
https://github.com/rook/rook/blob/00cef458af7dea94cac357c7c79b33aa10784e6c/cluster/examples/kubernetes/ceph/operator.yaml#L42

Then collect logs from csi-rbdplugin-provisioner pods(there should be two pods) csi-rbdplugin container after sometime.

**Comment by mmueen** [comment]
@Rakshith-R 

1. The rook version is 

```
# rook version
rook: v1.7.0-alpha.0.107.g5f64f5e
go: go1.16.3
```

2. I enabled the log level 5 and here are the logs from `csi-rbdplugin` container in the `csi-rbdplugin-provisioner` pod. however, one thing I noticed is that although I deleted the PVC some hours back, the csi-rbdplugin is still trying to create volumes.

```
I1006 22:23:36.360140       1 utils.go:176] ID: 323 Req-ID: pvc-48ef7cf6-ce6e-4bb3-a02e-c79ec463fb07 GRPC call: /csi.v1.Controller/CreateVolume
I1006 22:23:36.360263       1 utils.go:180] ID: 323 Req-ID: pvc-48ef7cf6-ce6e-4bb3-a02e-c79ec463fb07 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-48ef7cf6-ce6e-4bb3-a02e-c79ec463fb07","parameters":{"clusterID":"rook-ceph","csi.storage.k8s.io/pv/name":"pvc-48ef7cf6-ce6e-4bb3-a02e-c79ec463fb07","csi.storage.k8s.io/pvc/name":"test-pvc","csi.storage.k8s.io/pvc/namespace":"default","imageFeatures":"layering","imageFormat":"2","pool":"replicapool"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
I1006 22:23:36.360365       1 rbd_util.go:1109] ID: 323 Req-ID: pvc-48ef7cf6-ce6e-4bb3-a02e-c79ec463fb07 setting disableInUseChecks: false image features: [layering] mounter: rbd
E1006 22:23:36.360382       1 controllerserver.go:288] ID: 323 Req-ID: pvc-48ef7cf6-ce6e-4bb3-a02e-c79ec463fb07 an operation with the given Volume ID pvc-48ef7cf6-ce6e-4bb3-a02e-c79ec463fb07 already exists
E1006 22:23:36.360402       1 utils.go:185] ID: 323 Req-ID: pvc-48ef7cf6-ce6e-4bb3-a02e-c79ec463fb07 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-48ef7cf6-ce6e-4bb3-a02e-c79ec463fb07 already exists

$ k get pvc test-pvc
Error from server (NotFound): persistentvolumeclaims "test-pvc" not found
$ k get pvc -A | grep test-pvc
$
```

**Comment by andreamlin** [comment]
@Rakshith-R I have been getting a similar error. The CreateVolume request is fired off, and then several minutes later, it receives a gRPC deadline exceeded. Which pod is supposed to be handling the gRPC request, and what it is supposed to be executing (I assume some ceph command?) as part of fulfilling that request?

**Comment by Rakshith-R** [comment]
> @Rakshith-R I have been getting a similar error. The CreateVolume request is fired off, and then several minutes later, it receives a gRPC deadline exceeded. Which pod is supposed to be handling the gRPC request, and what it is supposed to be executing (I assume some ceph command?) as part of fulfilling that request?

@andreamlin Please go through https://github.com/rook/rook/blob/master/Documentation/ceph-csi-troubleshooting.md.

**Comment by andreamlin** [comment]
@Rakshith-R I'm running through the troubleshooting guide, and now am at the [part](https://github.com/rook/rook/blob/master/Documentation/ceph-csi-troubleshooting.md#rbd-commands) that suggests running the `rbd` command directly inside the csi-rbdplugin container of either of the csi-rbdplugin or csi-rbdplugin-provisioner pods :

```
$ sudo rbd ls -m 10.0.5.120:6789 --key AQBLCothutMVJxAA4s4CiW0+kntWnzI6WSVMjw== --id=csi-rbd-node
rbd: error opening default pool 'rbd'
Ensure that the default pool has been created or specify an alternate pool name.
rbd: listing images failed: (2) No such file or directory
```

Note that the key value is pulled from running this command in the toolbox pod: `ceph auth get-or-create client.csi-rbd-node mon 'profile rbd' osd 'profile rbd' mgr 'allow rw'`, and  the mon endpoint is either of the values in the rook-ceph-mon-endpoints configmap.

What is `rbd ls ...` supposed to return?

**Comment by andreamlin** [comment]
Also, is the `csi-provisioner` pod supposed to run a `ceph` or `rbd` command when it gets the `CreateVolume` grpc call?

**Comment by Rakshith-R** [comment]
> Also, is the `csi-provisioner` pod supposed to run a `ceph` or `rbd` command when it gets the `CreateVolume` grpc call?

Yes, provisioner creates/deletes/snapshot/clones volume while just csi rbdplugin (node daemonset) mounts/unmounts volumes to pod.


>What is rbd ls ... supposed to return?

The images in the pool, add -p <pool_name> to the command. 


The network connection seems to be fine, can you increase csi log level to 5 from rook-ceph-operator-override configmap and run create request + collect the entire logs from csi pods.

Paste output of these cmds too

`ceph status` , `rados lspools` with key and client args.

@andreamlin ^
