### ISSUE TITLE
Rook should use only controller-runtime Client

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#8913]
The Rook clusterd.Context has many different clients (see below). Newer controller unit tests use the controller-runtime (client `client.Client` below) to test controller behavior. Most older functions  and older unit tests use the `kubernetes.Interface` client or `rookclient.Interface` for unit testing. For wholistically testing controllers, unit tests can be much simpler if Rook were to only a single client interface like the one provided by controller-gen's `client.Client`.

Current clients:
```
	// Clientset is a connection to the core kubernetes API
	Clientset kubernetes.Interface

	// DynamicClientset is a dynamic connection to the Kubernetes API
	DynamicClientset dynamic.Interface

	// Represents the Client provided by the controller-runtime package to interact with Kubernetes objects
	Client client.Client

	// RookClientset is a typed connection to the rook API
	RookClientset rookclient.Interface
```

**Comment by leseb** [comment]
Ok one down, 3 more to go :) https://github.com/rook/rook/pull/8924
