### ISSUE TITLE
Error starting ceph monitor 

### ISSUE THREAD

**Issue by dylanjohnsonsfo** [rook/rook#892]
For some reason one of the nodes in my k8 cluster won't bring up ceph and throws the following error. the monitor pod are coming up fine on the other nodes which should be identical as regards version / configs etc. 

Her is the error ... 

rook error: mon-endpoints,mon-secret,admin-secret are required for mgr

**Comment by travisn** [comment]
Something seems corrupted in the rook-ceph-mgr pod spec. What does the spec show in the environment variables? This error is complaining that the ROOK_MON_ENDPOINTS, ROOK_MON_SECRET, and ROOK_ADMIN_SECRET variables are not found. 
```
kubectl -n rook describe pod <ceph-mgr-pod>
```

**Comment by dylanjohnsonsfo** [comment]
`djoh-mbr-11464:~` djohnson$ kubectl -n rook describe po/rook-ceph-mgr0-562916904-1gjmf
Name:		rook-ceph-mgr0-562916904-1gjmf
Namespace:	rook
Node:		ip-172-17-22-63/172.17.22.63
Start Time:	Thu, 10 Aug 2017 14:24:56 -0700
Labels:		app=rook-ceph-mgr
		pod-template-hash=562916904
		rook_cluster=rook
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"rook","name":"rook-ceph-mgr0-562916904","uid":"420eae38-7e0b-11e7-bef3-12b793ef7f...
Status:		Running
IP:		10.32.184.1
Created By:	ReplicaSet/rook-ceph-mgr0-562916904
Controlled By:	ReplicaSet/rook-ceph-mgr0-562916904
Containers:
  rook-ceph-mgr0:
    Container ID:	docker://fec002520b7e5d4356ae944579ecc24b9971c38354168beb4374e80e66333782
    Image:		rook/rook:master
    Image ID:		docker-pullable://rook/rook@sha256:181724cfa902c83e747301fe85aebd818fc5a6af539a72735c9796348b0ad24f
    Port:		<none>
    Args:
      mgr
      --config-dir=/var/lib/rook
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Thu, 10 Aug 2017 14:30:48 -0700
      Finished:		Thu, 10 Aug 2017 14:30:49 -0700
    Ready:		False
    Restart Count:	6
    Environment:
      ROOKD_MGR_NAME:			rook-ceph-mgr0
      ROOKD_MGR_KEYRING:		<set to the key 'keyring' in secret 'rook-ceph-mgr0'>	Optional: false
      ROOKD_CLUSTER_NAME:		rook
      ROOKD_MON_ENDPOINTS:		<set to the key 'endpoints' of config map 'mon-config'>		Optional: false
      ROOKD_MON_SECRET:			<set to the key 'mon-secret' in secret 'rook-ceph-mon'>		Optional: false
      ROOKD_ADMIN_SECRET:		<set to the key 'admin-secret' in secret 'rook-ceph-mon'>	Optional: false
      ROOKD_CEPH_CONFIG_OVERRIDE:	/etc/rook/override.conf
    Mounts:
      /etc/rook from rook-config-override (rw)
      /var/lib/rook from rook-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fr0v0 (ro)
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  rook-data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  rook-config-override:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	rook-config-override
    Optional:	false
  default-token-fr0v0:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-fr0v0
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath			Type		Reason			Message
  ---------	--------	-----	----				-------------			--------	------			-------
  6m		6m		1	default-scheduler						Normal		Scheduled		Successfully assigned rook-ceph-mgr0-562916904-1gjmf to ip-172-17-22-63
  6m		6m		1	kubelet, ip-172-17-22-63					Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "rook-data"
  6m		6m		1	kubelet, ip-172-17-22-63					Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "rook-config-override"
  6m		6m		1	kubelet, ip-172-17-22-63					Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-fr0v0"
  6m		6m		6	kubelet, ip-172-17-22-63					Normal		SandboxChanged		Pod sandbox changed, it will be killed and re-created.
  6m		32s		7	kubelet, ip-172-17-22-63	spec.containers{rook-ceph-mgr0}	Normal		Pulled			Container image "rook/rook:master" already present on machine
  6m		32s		7	kubelet, ip-172-17-22-63	spec.containers{rook-ceph-mgr0}	Normal		Created			Created container
  6m		32s		7	kubelet, ip-172-17-22-63	spec.containers{rook-ceph-mgr0}	Normal		Started			Started container
  6m		3s		35	kubelet, ip-172-17-22-63					Warning		FailedSync		Error syncing pod
  6m		3s		29	kubelet, ip-172-17-22-63	spec.containers{rook-ceph-mgr0}	Warning		BackOff			Back-off restarting failed container
djoh-mbr-11464:~ djohnson$`

**Comment by dylanjohnsonsfo** [comment]
not sure why they are empty vars as this did work once upon a time.

**Comment by travisn** [comment]
Did you upgrade the cluster? It looks like the variables have the `ROOKD` prefix instead of `ROOK`. This is a change we made recently. You must have a pod spec from a previous run, but a new version of the daemon.

**Comment by bassam** [comment]
closing. @dylanjohnsonsfo please reopen if this still an issue.

**Comment by jeonggyuchoi** [comment]
@travisn 
Hi travisn 
I really thanks for your reply and contribution.

I have some problem in my rook-ceph cluster

I update K8s TLS cert  key, 
and I recevied message  that    rook-ceph tool 
```
Error from server: error dialing backend: x509: cannot validate certificate for 172.17.58.48 because it doesn't contain any IP SANs
```
So,   I try to update the key,  
First delete  secret   operator, mgr,  osd      and restart  failed  osd , operator pod 

But still have problem  cannot connect the tool.

Accidentally,  I delete the  " rook-ceph-mon   secret "  // OMG - 

How do i recover the  rook-ceph-mon  secret // *.*

I'm beginer /  with rook-ceph  v1.0.4 / k8s v1.14.5
