### ISSUE TITLE
Build and deploy rook on AWS/Graviton (ARM64)

### ISSUE THREAD

**Issue by synarete** [rook/rook#8926]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Build and deploy rook on AWS Graviton-based (ARM64) EC2 instances. Expecting same functionality as common x86_64 machines.

**What is use case behind this feature:**
OpenShift cluster based on ARM64 instances

**Environment**:

AWS/Graviton

**Comment by leseb** [comment]
We already have arm64 builds, as well as a daily job running on arm64. @synarete have you been able to test that this is not working already? If so, what items do you see for the implementation? Thanks!
