### ISSUE TITLE
[Helm] Rook Operator upgrade (1.7.0 -> 1.7.4) throws error message but updates anyway

### ISSUE THREAD

**Issue by mway-niels** [rook/rook#8932]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When using Helm to upgrade the Rook-Ceph Operator from version 1.7.0 to 1.7.4, Helm throws an error (see logs below). Even though an error is raised, the Operator deployment is updated. This can be seen because the container image tag is reflecting the correct (new) version.

**Expected behavior:**
Since the [Rook-Ceph Upgrades](https://rook.io/docs/rook/v1.7/ceph-upgrade.html) documentation page doesn't mention specific (manual) steps for the upgrade from 1.7.0 to 1.7.4, I would expect the `helm install --upgrade` command to execute without throwing an error.

**How to reproduce it (minimal and precise):**

1. Install Rook-Ceph Operator v1.7.0 using Helm.
2. Set up a Ceph cluster using the Cluster CR (including block pools).
3. Upgrade the Helm release to v1.7.4.

**File(s) to submit**:
```
$ helm upgrade --install --namespace rook-ceph rook-ceph rook-release/rook-ceph --version 1.7.4 --wait
W1006 14:03:06.157286     118 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1006 14:03:06.161950     118 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1006 14:03:06.170100     118 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Error: UPGRADE FAILED: cannot patch "cephblockpools.ceph.rook.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "cephblockpools.ceph.rook.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema && cannot patch "cephfilesystems.ceph.rook.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "cephfilesystems.ceph.rook.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema && cannot patch "cephobjectstores.ceph.rook.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "cephobjectstores.ceph.rook.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema && cannot patch "cephobjectzones.ceph.rook.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "cephobjectzones.ceph.rook.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```

**Environment**:
* OS (e.g. from /etc/os-release): Amazon Linux 2
* Kernel (e.g. `uname -a`): 5.4.144-69.257.amzn2.x86_64
* Cloud provider or hardware configuration: AWS
* Rook version (use `rook version` inside of a Rook Pod): v1.7.4
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)`
* Kubernetes version (use `kubectl version`): v1.21.2-eks-0389ca3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AWS EKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `HEALTH_WARN 1 backfillfull osd(s); 1 osds down; 1 OSDs or CRUSH {nodes, device-classes} have {NOUP,NODOWN,NOIN,NOOUT} flags set; 1 host (1 osds) down; 1 nearfull osd(s); Reduced data availability: 45 pgs inactive, 25 pgs down, 23 pgs stale; Degraded data redundancy: 1659/24858 objects degraded (6.674%), 49 pgs degraded, 60 pgs undersized; 10 pool(s) backfillfull; 1 pool(s) have no replicas configured; 101 daemons have recently crashed; 391 slow ops, oldest one blocked for 70597 sec, daemons [osd.0,osd.1,osd.10,osd.11,osd.5,osd.6,osd.7,osd.8] have slow ops.`

**Comment by travisn** [comment]
The error just doesn't make sense since the `preserveUnknownFields` field hasn't existed since v1.5. Like mentioned in the workaround, if you manually edit the CRDs do you see that property and can you remove it?
