### ISSUE TITLE
CSI driver documentation on AZ read affinity

### ISSUE THREAD

**Issue by travisn** [rook/rook#8935]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The CSI driver supports AZ read affinity. We should document this in the ceph-csi-driver.md topic so the feature can be more discoverable and usable.

The approach from is linked from @idryomov and modified slightly for the more general rook case with AZs in [this comment](https://github.com/ceph/ceph-csi/pull/760#issuecomment-937778256):

I believe it can be tested today with the help of [mapOptions parameter](https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-rbd.md#configuration)  on the storage class. Stand up a cluster across multiple zones, make sure that the CRUSH map reflects that the cluster is split between e.g. zone "z1" and "z2" and set mapOptions to e.g. "read_from_replica=localize,crush_location=datacenter:z1". Any PV created from this storage class would simulate a client that is local to "z1" and reads from that client would go to OSDs located in "z1" (whenever possible -- in some cases the client doesn't get to choose and has to direct the read to the primary OSD).

**Comment by Rakshith-R** [comment]
#11631 provides for a easier, enhanced and more scaleable way to  achieve this issue's objective.
