### ISSUE TITLE
There is a conflict between the health check and the cephcluster phase modification during the ceph upgradeprocess.

### ISSUE THREAD

**Issue by fengjiankui121** [rook/rook#8989]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
Healthcheck should not modify cephcluster

**How to reproduce it (minimal and precise):**
step 1: enable Healthcheck of ceph status
step 2: upgrade ceph
step 3: PHASE of cephcluster will be Progressing
step 4:  Before the ceph upgrade is completed, the health check is triggered at this time, and the cephcluster will be modified back to ready.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by fengjiankui121** [comment]
1、During the upgrade process, if mgr already exists, a health check will be started. The code is as follows：

‘’‘’rook\pkg\operator\ceph\cluster\cluster.go‘’‘

mgrDeployments, err := c.context.Clientset.AppsV1().Deployments(cluster.Namespace).List(ctx, opts)
if err == nil && len(mgrDeployments.Items) > 0 && cluster.ClusterInfo != nil {
	c.configureCephMonitoring(cluster, clusterInfo)
}

2、Before upgrading mon, osd, and mgr, change the status of cephcluster to Progressing, and change it to Ready or Failure after completion. The code is as follows:

‘’‘’‘’rook\pkg\operator\ceph\cluster\cluster.go‘’‘’‘’

config.ConditionExport(c.context, c.namespacedName, cephv1.ConditionProgressing, v1.ConditionTrue, "ClusterProgressing", message)

// Run the orchestration
err = cluster.doOrchestration(c.rookImage, *cephVersion, cluster.Spec)
if err != nil {
config.ConditionExport(c.context, c.namespacedName, cephv1.ConditionFailure, v1.ConditionTrue, "ClusterFailure", "Failed to create cluster")
return errors.Wrap(err, "failed to create cluster")
}
// Set the condition to the cluster object
config.ConditionExport(c.context, c.namespacedName, cephv1.ConditionReady, v1.ConditionTrue, "ClusterCreated", "Cluster created successfully")

3、During the health check, the phase of cephcluster will be changed according to the status of ceph. The relevant code is as follows:

’‘’rook\pkg\operator\ceph\cluster\cephstatus.go’‘’

// Check ceph's status
status, err = cephclient.StatusWithUser(c.context, c.clusterInfo)
if err != nil {
logger.Errorf("failed to get ceph status. %v", err)
condition, reason, message := c.conditionMessageReason(cephv1.ConditionFailure)
if err := c.updateCephStatus(cephStatusOnError(err.Error()), condition, reason, message); err != nil {
	logger.Errorf("failed to query cluster status in namespace %q. %v", c.clusterInfo.Namespace, err)
}
return
}

**Comment by fengjiankui121** [comment]
@travisn

**Comment by travisn** [comment]
@fengjiankui121 Pleas share the CephCluster `status` as you see it, and then describe what you would expect. The `conditions` will reflect whether a reconcile is in progress for the upgrade. The `phase` is not intended to reflect whether the reconcile is currently in progress, so the behavior you are seeing may be expected.

**Comment by BlaineEXE** [comment]
I can confirm what @fengjiankui121 is reporting. I just installed a CephCluster with v15.2.11 and then updated to v16.2.6. The phase changed to `Progressing`. If the phase isn't intended to reflect the reconcile status, shouldn't it always report `Ready`?

```
NAME         DATADIRHOSTPATH   MONCOUNT   AGE   PHASE         MESSAGE                  HEALTH      EXTERNAL
my-cluster   /var/lib/rook     1          16m   Progressing   Detecting Ceph version   HEALTH_OK
```

**Comment by travisn** [comment]
> I can confirm what @fengjiankui121 is reporting. I just installed a CephCluster with v15.2.11 and then updated to v16.2.6. The phase changed to `Progressing`. If the phase isn't intended to reflect the reconcile status, shouldn't it always report `Ready`?
> 
> ```
> NAME         DATADIRHOSTPATH   MONCOUNT   AGE   PHASE         MESSAGE                  HEALTH      EXTERNAL
> my-cluster   /var/lib/rook     1          16m   Progressing   Detecting Ceph version   HEALTH_OK
> ```

Agreed it would be more consistent if the Phase were more consistent. To clarify my earlier statement, if anyone is relying on the status, the conditions are expected to be most accurate for tracking operator status. Is it worth fixing the phase? perhaps

**Comment by fengjiankui121** [comment]
it is worth fixing the phase

**Comment by parth-gr** [comment]
Reopen as it is not fixed yet

**Comment by parth-gr** [comment]
worth fixing so re-opening
