### ISSUE TITLE
Feature request: Add annotations to secrets and configmaps created by operator

### ISSUE THREAD

**Issue by fritchie** [rook/rook#8999]
It would be nice to be able to add annotations to secrets and configmaps created by the operator as can be done for pods:

https://rook.github.io/docs/rook/v1.7/ceph-cluster-crd.html#annotations-and-labels

My use case is that I would like to use [kubed](https://github.com/kubeops/kubed) to sync the  "rook-ceph-admin-keyring" secret and the "rook-ceph-mon-endpoints" configmap to another namespace for Openstack Cinder. To sync the resources kubed requires that an annotation be added.

**Comment by adamcstephens** [comment]
I'd like to second this. It's also a requirement for https://github.com/mittwald/kubernetes-replicator

**Comment by travisn** [comment]
@fritchie @adamcstephens Is it really just this one secret and configmap that needs the annotation? There are several other secrets and configmaps that are just basic configuration that likely don't need to be annotated.

What about a new category under annotations such as:
```yaml
  annotations:
    clusterMetadata
```

Then we could define exactly which configmaps/secrets make sense to be in that category.

**Comment by adamcstephens** [comment]
@travisn I'm currently trying to annotate secret `rook-ceph-mon` and configmap `rook-ceph-mon-endpoints` for running benji backup in another namespace.

**Comment by subhamkrai** [comment]
@adamcstephens @fritchie one question, we don't need to merge these annotations with `annotation.all` [this](https://github.com/rook/rook/blob/master/deploy/examples/cluster.yaml#L164) which are basically annotations for pods. right?

**Comment by adamcstephens** [comment]
@subhamkrai correct, this request is only to add them for secrets and configmaps

**Comment by DavidSpek** [comment]
This would also be very useful for the secret and configmap created by the operator when provisioning an ObjectBucketClaim.

**Comment by travisn** [comment]
> This would also be very useful for the secret and configmap created by the operator when provisioning an ObjectBucketClaim.

@DavidSpek Good idea, would you mind opening a new issue for this? Thanks!

**Comment by DavidSpek** [comment]
@travisn I've just created https://github.com/rook/rook/issues/9608. Hopefully it contains enough information.
