### ISSUE TITLE
Compatibility with kustomize 4.0.5

### ISSUE THREAD

**Issue by pfrenzel** [rook/rook#9002]
**Is this a bug report or feature request?**

* Bug Report
  * The bug does not affect rook, but kustomize. It is only triggered by the code (more precisely by the comments).

**Bug Report**

**Expected behavior:**
* kustomize is able to process the file

**Deviation from expected behavior:**
* error: yaml: invalid trailing UTF-8 octet

**How to reproduce it (minimal and precise):**
```
cat <<EOF >./kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 
resources: 
- https://raw.githubusercontent.com/rook/rook/v1.6.8/cluster/examples/kubernetes/ceph/common.yaml 
EOF
kustomize build .
```
kostumize version: 4.0.5

**Feature Request**

**What should the feature do:**
kustomize just can't handle the quotes in the comments. The current version 4.4. has no more problems here either. But maybe you can adjust the comments accordingly. The version 4.0.5 is certainly still quite common with Kubectl v1.21.
All quotation marks in the comments would have to be removed. I noticed this only in https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/common.yaml line 74ff

**What would be solved through this feature:**
* using kostumize without the need for an update, possibly affecting other existing setups.

**Does this have an impact on existing features:**
no

**Comment by leseb** [comment]
Fixed in https://github.com/rook/rook/pull/9009
