### ISSUE TITLE
Enable nfs mgr module configuration of CephNFS

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#9021]
**Is this a bug report or feature request?**
* Feature Request

The new nfs mgr module in Ceph makes managing NFS exports much easier from the CLI. We would like to allow users to manage NFS exports using this interface.

### Current state

In Octopus, users could create NFS exports from the dashboard only. They could do this via CLI using curl commands in what is frankly a pretty hacky experience as noted in the Octopus docs: https://docs.ceph.com/en/octopus/cephfs/nfs/#configure-nfs-ganesha-exports. Notably, the line below:
> We need to download and run this [script](https://raw.githubusercontent.com/ceph/ceph/master/src/pybind/mgr/dashboard/run-backend-rook-api-request.sh) to pass the JSON file contents.

Configuring the dashboard to "see" a manually-created CephNFS involves running the command found here (assuming multiple CephNFSes): https://rook.github.io/docs/rook/v1.7/ceph-nfs-crd.html#samples
> `ceph dashboard set-ganesha-clusters-rados-pool-namespace <cluster_id>:<pool_name>[/<namespace>](,<cluster_id>:<pool_name>[/<namespace>])*`

The dashboard interface continues to work when upgrading to Pacific v16.2.6. This also causes the `nfs-ganesha` pool to be created with with an empty conf for the NFS cluster, but no exports are migrated. (Update: `nfs-ganesha` pool might be created by Rook, not Ceph)

As of 21 Oct. 2021, the dashboard interface also continues to work when upgrading to latest-pacific-devel (will become v16.2.7), and still continues to work when upgrading to latest-master-devel (will become Quincy). This also causes the `.nfs` pool to be created with an empty conf for the NFS cluster, and again with no exports migrated. (Update: `.nfs` pool might be created by Rook, not Ceph)

As of Ceph v16.2.6, the `ceph nfs export apply <cluster>` command does not exist. It is added in the upcoming v16.2.7. The similar `ceph nfs export update` command exists, but it lacks the `<cluster>` argument, and I couldn't get it to work in my testing. This effectively means that currently, users cannot migrate existing exports to new pools until v16.2.7.

### Desired state

Ideally, we want to get into a state where the dashboard and nfs mgr module can observe and create the same NFS exports. Ceph seems to have made some efforts to align these in the Pacific release, and Rook is lagging behind on the effort.

Firstly, I am not certain that the Ceph dashboard and nfs mgr module are able to operate on NFS exports in the same way, even in Pacific/Quincy releases. Some of my investigation suggests that the nfs mgr module modifies the config object to add a URL for each export whereas the dashboard does not. This remains to be investigated.

In order to get to the desired state in Rook, Rook needs to be able to either (1) migrate NFS exports and config to the new pool layout automatically or (2) give users good documentation about how to migrate NFS exports and config to the new pool layout for themselves manually.

So far, we have been planning on option 2 given that we believe the NFS user base is small. There are some issues reported to Rook that indicate there are users of CephNFS. I linked some issues below and skipped issues reported by the same username.
- https://github.com/rook/rook/issues/8290
- https://github.com/rook/rook/issues/8234
- https://github.com/rook/rook/issues/8179
- https://github.com/rook/rook/issues/7779
- https://github.com/rook/rook/issues/6636

### Technical proposal
**CAVEAT: I still need to prove out that the below will actually work. The testing I have done so far suggests it will.**

In order to keep the NFS code legible around pool names/namespaces, when releasing Rook v1.8, I would like to be able to force all users to use the new `.nfs` pool if possible regardless of the Ceph version. I think this will be the best experience for users. They will ideally only have to migrate their pools ONCE. It will be a poor experience for users if they have to migrate to `nfs-ganesha` for v16.2.[0-6] and migrate again to `.nfs` for v16.2.7+. The migration will only be required when they upgrade to Rook v1.8 where they will have the Rook upgrade guide to help them. If we require the migration to happen only on changes to the Ceph version, users are more likely to miss the updates.

Given the state of the nfs mgr module in Pacific before v16.2.7, I believe we must instruct users that the dashboard method is the only usable method for NFS management until v16.2.7.

For users on v16.2.6 and below (including Octopus), this will mean copying `export-N` items to pool `.nfs` in namespace `<name-of-CephNFS>` and using `ceph dashboard set-ganesha-clusters-rados-pool-namespace` to change the pool configuration.

For users on v16.2.7, the `ceph nfs export apply` command is working, and users can use that to migrate pools. Even if users have previously migrated exports to `.nfs` before this using the method above, it may be necessary for the user to use `ceph nfs export apply` to re-consume the export configurations if the nfs mgr module still expects URL lines to be present in the NFS config.

Ideally, users should have to do nothing if they upgrade from an already-migrated v16.2.6- to v16.2.7+.

### Still to do
- [x] verify that it's possible to move exports to `.nfs` in Pacific 16.2.6 and below (including Octopus) and have the dashboard management continue working
- [x] verify that it's possible to move exports to `.nfs` in Pacific 16.2.7 and up using `ceph nfs export apply`
- [x] investigate the dashboard's management of the URL configuration line compared to the nfs mgr module's use of the line to ensure exports created with the dashboard can be managed via the nfs mgr module also (this may lead to a fix needed in Ceph)

### Alternatives
We could allow users to migrate only if they actually want to use the nfs mgr module. This would inconvenience fewer users, but this would also mean we need to keep and maintain the migration docs for much longer in Rook for the eventuality that users want to migrate later. That comes with risks that docs might get outdated, and we would have to spend more time maintaining them. It seems better overall to prove out the migration steps for v1.8 and not have to worry about it after v1.9 is released.

**Comment by BlaineEXE** [comment]
Even with `latest-master-devel`, the dashboard seems to want to use the `nfs-ganesha` pool rather than the `.nfs` pool. Is there a PR that still needs to make it into master?

![image](https://user-images.githubusercontent.com/3989526/139927732-c9f3ca37-86e3-465a-8ab7-e69a113b7b90.png)

This is from Ceph build `17.0.0-8135-gf5b96461 (f5b96461081c2f508d1393202ebcd94e6bd2ea3f)
quincy (dev)`

**Comment by alfonsomthd** [comment]
> Even with `latest-master-devel`, the dashboard seems (based on the error message reported) to be using the `nfs-ganesha` pool rather than the `.nfs` pool. Is there a PR that still needs to make it into master?

@BlaineEXE Somehow the container must be outdated (or at least the dashboard pkg) as that is the old exports list (i.e. in master the `Daemons` column no longer exists):
![nfs-export-list](https://user-images.githubusercontent.com/6780162/140058546-d92a7d90-7772-41ff-ac6c-7babb4b5fe60.png)

**Comment by BlaineEXE** [comment]
Everything looks to be working with the latest Pacific devel image (soon v16.2.7) and Rook v1.8 beta. Thanks everyone for your help. :)
