### ISSUE TITLE
rgw: add unit tests for the extrernal ceph object store reconciler

### ISSUE THREAD

**Issue by leseb** [rook/rook#9025]
`pkg/operator/ceph/object/controller_test.go` does not have any test for  an external CephObjectStore CR.

**Comment by rexagod** [comment]
@leseb I'm trying to pick something up to work on. Can you please assign me to this issue?

Thanks!

**Comment by subhamkrai** [comment]
> @leseb I'd like to pick this up, can you please assign me to this issue?
> 
> Thanks!

done.
