### ISSUE TITLE
Integrate with secrets-store-csi to support BYOK scenarios

### ISSUE THREAD

**Issue by romoh** [rook/rook#9032]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Integrate with [secrets store csi](https://github.com/kubernetes-sigs/secrets-store-csi-driver) for mounting of secrets using external secret stores. This can be used for secrets/encryption key used to encrypt Ceph OSDs.

**What is use case behind this feature:**
Currently Rook supports KMS like [Vault ](https://www.vaultproject.io/) for key management of the encryption key. However, the current implementation doesn't support an easy way to leverage enterprise grade cloud providers for key management. 

Supporting secrets-store-csi will allow customers to leverage external secrets stores and pick from the different existing providers based on their scenarios.
Supported providers include:
https://github.com/Azure/secrets-store-csi-driver-provider-azure
https://github.com/aws/secrets-store-csi-driver-provider-aws
https://github.com/googlecloudplatform/secrets-store-csi-driver-provider-gcp
https://github.com/hashicorp/vault-csi-provider

**Comment by leseb** [comment]
> I'm working on this one.

Thanks, please start with small design documentation before starting any implementation. See https://github.com/rook/rook/blob/master/design/design_template.md. Thanks

**Comment by travisn** [comment]
@romoh Are you still working on #9325? Thanks!

**Comment by romoh** [comment]
> @romoh Are you still working on #9325? Thanks!

yes, I'm still working on this and also key rotation support for PVC based clusters. I paused for a while after the holidays but should be resuming on that next week.
