### ISSUE TITLE
Simplify enabling encryption for data in transit with msgr2

### ISSUE THREAD

**Issue by travisn** [rook/rook#9054]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Enabling encryption for data on the wire requires some ceph settings such as:
```
[global]
ms_cluster_mode=secure
ms_service_mode=secure
ms_client_mode=secure
```

Instead of requiring separate Ceph settings, we should have a cluster CR setting to enable it. 

See [here](https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/4/html/data_security_and_hardening_guide/assembly-encryption-and-key-management#enabling-the-messenger-v2-protocol_sec) for some related docs on enabling the msgr2 encryption.

**What is use case behind this feature:**
Simplify enabling the msgr2 encryption with a cluster CR setting when clients support the msgr2 protocol. 

Still need to verify what client versions would support msgr2.

**Comment by Jiawei0227** [comment]
What is the default behavior  for msgr2? Do we enable or disable it by default?

**Comment by travisn** [comment]
The default settings for msgr2 are described [here](https://docs.ceph.com/en/latest/rados/configuration/msgr2/#connection-modes) in the Ceph docs. Basically, the default is `crc secure`, which means it will default first to use the "crc" mode, which does not encrypt all network traffic. To encrypt all traffic, it needs to be changed to "secure".
