### ISSUE TITLE
bump to go-ceph 0.13 and backport users caps update

### ISSUE THREAD

**Issue by leseb** [rook/rook#9066]
Re-run this backport https://github.com/rook/rook/pull/9058

**Comment by subhamkrai** [comment]
@leseb go-ceph 0.13 is out should we re-run #9058?

**Comment by leseb** [comment]
> @leseb go-ceph 0.13 is out should we re-run #9058?

Yes we can give it a try.

**Comment by travisn** [comment]
This is already in v1.8, I assume we don't need to backport to v1.7 at this point.
