### ISSUE TITLE
test: unable to run smoke tests with minikube: "insecure flag is not allowed"

### ISSUE THREAD

**Issue by jbw976** [rook/rook#907]
After running ` tests/scripts/minikube.sh up` to get minikube running, then trying to run the smoke tests, I see an issue with using the "insecure flag":
```
> make test-integration SUITE=SmokeSuite
...
2017-08-11 16:48:43.613290 I | testutil: Loaded kubectl context minikube at https://192.168.99.100:8443. secure=false
--- FAIL: TestSmokeSuiteK8s (0.09s)
        Error Trace:    smoke_test.go:47
            suite.go:63
            smoke_test.go:35
    Error:      Received unexpected error:
            failed to get clientset. specifying a root certificates file with the insecure flag is not allowed
```

This looks to be a regression from: https://github.com/rook/rook/commit/1c1470e28cadb6ba0273988545ffd21c00c166cd#diff-383b6743d9365674d5e23f7395a1b606R167

I commented out that hardcoding of `config.Insecure = true` and was able to run the smoke tests.

**Comment by travisn** [comment]
smoke tests seem to work fine with minikube now
