### ISSUE TITLE
Helm repo - 404

### ISSUE THREAD

**Issue by valentin2105** [rook/rook#908]
Hi,

I try to use Rook with helm but it seem that the repo described on Rook's docs seem doesn't work.

https://rook.io/docs/rook/master/helm-operator.html

```
14:30:25 › helm repo add rook-alpha http://charts.rook.io/alpha
Error: Looks like "http://charts.rook.io/alpha" is not a valid chart repository or cannot be reached: Failed to fetch http://charts.rook.io/alpha/index.yaml : 404 Not Found
```

Thanks !

**Comment by bassam** [comment]
thanks! we're working on a fix. should be out in 0.5.1 shortly.

**Comment by valentin2105** [comment]
Thanks a lot, I will try directly from yaml files for the moment.  :)
