### ISSUE TITLE
Customize Ceph PrometheusRule CRD

### ISSUE THREAD

**Issue by yuvalman** [rook/rook#9082]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Give the option to customize ceph PrometheusRule CRD.

There few options for achieving this feature, I'm suggesting here one of my ideas:

1. We can add a new field under [monitoring ](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-external.yaml#L28) section in the CephCluster CRD called prometheusRules. Under this section, we can add sections per alert name, and under this section, every field that will be mentioned in the CRD will overwrite the default values that we have now (using Go templates).

For example:
```
  .
  .
  .
 monitoring:
     enabled: true
     rulesNamespace: rook-ceph
    prometheusRules:
      CephOSDNearFull:
        for: 5m
        limit: 0.80
 .
 .
 .
```
In this case the CephOSDNearFull alert will be fired after the limit 0.80 instead of 0.75. Also, it will be fired after 5 minutes instead of the default value.

This feature can help users that use Ceph in Rook to modify the prometheus alerts as they want.

**What is use case behind this feature:**

Users cannot modify the prometheusRule CRD as they want.

**Environment**:

**Comment by leseb** [comment]
Isn't that what those YAML files do? https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph/monitoring

**Comment by leseb** [comment]
@aruniiird thoughts?

**Comment by leseb** [comment]
Rook does not manage the `PrometheusRule`. It merely helps with the ServiceMonitor resource and nothing more. If you want to modify the value of the rules, you will need to edit the YAML file instead.

**Comment by travisn** [comment]
Agreed that we need to find a way to make it customizable. Rook does actually install the rule [here](https://github.com/rook/rook/blob/a0cef3bc0b94a12448c62c0315374bce9e17614c/pkg/operator/ceph/cluster/cluster_external.go#L246). The hard coded settings have also been a concern as described in #9005.

**Comment by BlaineEXE** [comment]
I'm not so sure the CephCluster CRD is the best place to set custom prometheus metrics for Rook. Maybe it was a design flaw initially that Rook deployed Prometheus rules. I think it's good for Rook to have recommended rules (as examples or docs) that go pair with Ceph, but I'm not sure it's Rook's place to have such a tight coupling between Ceph and Prometheus by actually deploying and managing the rules itself. Can we separate responsibilities better? What would it look like to transition to a deployment method that had the users set prometheus rules with prometheus tooling?

**Comment by travisn** [comment]
Expected to be customizable after #9837.
