### ISSUE TITLE
unit tests for object store "user" fail to build

### ISSUE THREAD

**Issue by yuvalif** [rook/rook#9087]
under: `pkg/operator/ceph/object`
I get the following:
```
go test ./...
# github.com/rook/rook/pkg/operator/ceph/object/user [github.com/rook/rook/pkg/operator/ceph/object/user.test]
user/controller.go:301:40: r.objContext.AdminOpsClient.RemoveUserCap undefined (type *admin.API has no field or method RemoveUserCap)
user/controller.go:306:39: r.objContext.AdminOpsClient.AddUserCap undefined (type *admin.API has no field or method AddUserCap)
```

**Comment by subhamkrai** [comment]
@yuvalif Thanks for opening the issue. I also noticed today pinged @leseb about this

**Comment by leseb** [comment]
@yuvalif you need to add `-tags ceph_preview` to your command. It's only true for master and only temporary. Please close when this is resolved. Thanks

**Comment by leseb** [comment]
Config for vscode
![Screenshot 2021-11-03 at 09 08 54](https://user-images.githubusercontent.com/912735/140026814-cf128749-26ba-4f51-814b-f1e6d3ae1cca.png)

**Comment by yuvalif** [comment]
thanks @leseb !
fixed by running: `go test -tags ceph_preview  ./...`
