### ISSUE TITLE
Support Swift API and Keystone Integration

### ISSUE THREAD

**Issue by horazont** [rook/rook#9088]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Configure radosgw to interface with OpenStack Keystone for identity management and offer the Swift API.

**What is use case behind this feature:**
[We](https://gitlab.com/yaook) are developing a Kubernetes-native LCM for OpenStack and are supporting Rook for Ceph-based block storage already. We would like to have a recommended way for deploying Object Storage using Rook, too.

**Environment**:
Nothing specific I guess.

**Additional notes**:
- https://github.com/rook/rook/issues/4754 was autoclosed as ~wontfix (and I cannot see a way to reopen it): Does this mean that support for offering Swift API is out of scope for Rook?
- Having at least [some experience](https://github.com/rook/rook/pull/5483) with rook, we might contribute this ourselves, but as of the time of writing, I can't give a definitive timeline.

**Comment by leseb** [comment]
I think this just lacks traction but I don't see any reason why we wouldn't do it. Although rgw has many backends it interacts with to the point it's kinda clustering the CephObjectStore CRD a bit. So let's have a good API design if we decide to go ahead with this.

**Comment by horazont** [comment]
@leseb Thank you for the reply. I didn't look deeply into the Object Store CRD yet, beyond taking an example and shooting it at my cluster. What would be your preferred mode to discuss future API design?

**Comment by leseb** [comment]
@horazont we can start with a design doc PR, you can find the template here https://github.com/rook/rook/blob/master/design/design_template.md. Thanks

**Comment by sebastianriese** [comment]
We've added a PR with a first draft of the design document: #9444.

**Comment by sebastianriese** [comment]
I started working on the code and I discovered the issue, that go-ceph does not support all required RGW Admin Ops calls that are needed to implement the changes from the design document.

I've started [a discussion there](https://github.com/ceph/go-ceph/discussions/641) and hope to implement the required features.

**Comment by BlaineEXE** [comment]
Thanks for keeping us up-to-date @sebastianriese.

**Comment by horazont** [comment]
In the meantime, https://github.com/ceph/go-ceph/pull/644 has been proposed and merged, which means that our main focus of work is currently implementing the rook extension itself. I don't think there's a PR yet. @sebastianriese?

**Comment by mnaser** [comment]
👋 @sebastianriese -- have you had a chance to follow up on the rest of this?

**Comment by horazont** [comment]
We're still working on getting the tests right--as this will depend on Keystone for integration tests, much of the recent work has been on integrating that somehow sensible.

We've still got this on our list and intend to finish it before the end of the year.

**Comment by mnaser** [comment]
> We're still working on getting the tests right--as this will depend on Keystone for integration tests, much of the recent work has been on integrating that somehow sensible.
> 
> We've still got this on our list and intend to finish it before the end of the year.

awesome.  we've got a workaround that works for now at our side in the meantime.

**Comment by kayrus** [comment]
Do you have any updates about the keystone integration and native Swift API support? Is there any particular code that needs to be adjusted?

**Comment by jklippel** [comment]
Opened https://github.com/rook/rook/pull/13807 to implement authentication using keystone with s3 and swift.
