### ISSUE TITLE
I can't delete ceph cluster  althgouth I look around  the offical docs

### ISSUE THREAD

**Issue by kiddingl** [rook/rook#9103]
**Is this a bug report or feature request?**
  Bug Report

**Deviation from expected behavior:**
ceph-cluster can't delete
**Expected behavior:**
The ceph cluster is deleted
**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:

* OS (e.g. from /etc/os-release):
```
[root@ansible1 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@ansible1 ~]#
```
* Kernel (e.g. `uname -a`):
```
[root@ansible1 ~]# uname -a
Linux ansible1 5.4.143-1.el7.elrepo.x86_64 #1 SMP Wed Aug 25 18:15:50 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
[root@ansible1 ~]#
```
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
```
[root@ansible1 ~]# ls rook-ceph
rook-ceph/                    rook-ceph-cluster/            rook-ceph-cluster-v1.7.6.tgz  rook-ceph-v1.7.6.tgz
[root@ansible1 ~]# ls rook-ceph
```
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
```
[root@ansible1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:58:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
[root@ansible1 ~]#
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
binary
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

Other:  I can't delete the ceph-cluster in namespace defualt and rook-cluster
The  delete command hang the screen:
![image](https://user-images.githubusercontent.com/36329336/140379997-89f929ce-2d9a-4e9b-9a63-1e2c70b3c1e0.png)

**Comment by kiddingl** [comment]
![image](https://user-images.githubusercontent.com/36329336/140379418-47144534-60c0-4fa5-af5a-341af015f6b1.png)
I download pkg from the rook registry

**Comment by travisn** [comment]
@kiddingl Please see the [cleanup guide](https://rook.github.io/docs/rook/v1.7/ceph-teardown.html) to uninstall. Rook is trying to protect the data in the cluster by refusing to remove the finalizer. At the end of that doc there is a section on removing the finalizer on the CephCluster and other CRs if you want to force it.

**Comment by kiddingl** [comment]
I want to force remove  it,  I run the command from clean guide,  the command  hang on my screen:
[root@ansible1 ~]# kubectl  patch cephcluster default --type merge -p '{"spec":{"cleanupPolicy":{"confirmation":"yes-really-destroy-data"}}}'
cephcluster.ceph.rook.io/default patched (no change)
[root@ansible1 ~]# kubectl delete cephblockpools.ceph.rook.io ceph-blockpool
cephblockpool.ceph.rook.io "ceph-blockpool" deleted
^C
[root@ansible1 ~]# kubectl delete cephblockpools.ceph.rook.io ceph-blockpool
cephblockpool.ceph.rook.io "ceph-blockpool" deleted

**Comment by kiddingl** [comment]
> @kiddingl Please see the [cleanup guide](https://rook.github.io/docs/rook/v1.7/ceph-teardown.html) to uninstall. Rook is trying to protect the data in the cluster by refusing to remove the finalizer. At the end of that doc there is a section on removing the finalizer on the CephCluster and other CRs if you want to force it.

![image](https://user-images.githubusercontent.com/36329336/140447365-eb606d41-1380-4350-b9be-b678f31d6981.png)

**Comment by travisn** [comment]
To force the uninstall, you'll need to remove the finalizers from the CRs. See later in the cleanup guide for [removing finalizers](https://rook.github.io/docs/rook/v1.7/ceph-teardown.html#removing-the-cluster-crd-finalizer)

**Comment by kiddingl** [comment]
> To force the uninstall, you'll need to remove the finalizers from the CRs. See later in the cleanup guide for [removing finalizers](https://rook.github.io/docs/rook/v1.7/ceph-teardown.html#removing-the-cluster-crd-finalizer)

Thnak you

**Comment by kiddingl** [comment]
I has succed to remove ceph-cluster, So I want to restart ceph operator , the command:
```
[root@ansible1 ~]# helm install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "cephblockpools.ceph.rook.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "rook-ceph": current value is "default"
[root@ansible1 ~]#
```
I am confused it
