### ISSUE TITLE
No 1.7.7 image found

### ISSUE THREAD

**Issue by serewicz** [rook/rook#9111]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Expected various pods to start when creating a cluster. No working due to image pull errors. hub.docker.com does not show any 1.7.7 tags.  In fact all typical tags are gone. Now  they all seem to look like this: _v1.7.6-50.g4bfbb83_  from upboundpullbot.   There is no "latest" tag either, so leaving off the version and the suggested pull from hub.docker.com also fails. 

**Expected behavior:**
Various pods using the ceph image start as the cluster is created.

**How to reproduce it (minimal and precise):**

```
13  git clone --single-branch --branch release-1.7 https://github.com/rook/rook.git
14  cd rook/cluster/examples/kubernetes/ceph
15  kubectl create -f crds.yaml -f common.yaml -f operator.yaml

18  kubectl create -f cluster.yaml 
20 kubectl -n rook-ceph get pod
NAME                                  READY   STATUS             RESTARTS   AGE
rook-ceph-operator-6866d8fb9b-4tk9j   0/1     ImagePullBackOff   0          28m
21 kubectl -n rook-ceph get events
LAST SEEN   TYPE      REASON              OBJECT                                     MESSAGE
29m         Normal    Scheduled           pod/rook-ceph-operator-6866d8fb9b-4tk9j    Successfully assigned rook-ceph/rook-ceph-operator-6866d8fb9b-4tk9j to pool-g4xxf8tye-ufx0h
27m         Normal    Pulling             pod/rook-ceph-operator-6866d8fb9b-4tk9j    Pulling image "rook/ceph:v1.7.7"
27m         Warning   Failed              pod/rook-ceph-operator-6866d8fb9b-4tk9j    Failed to pull image "rook/ceph:v1.7.7": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rook/ceph:v1.7.7": failed to resolve reference "docker.io/rook/ceph:v1.7.7": docker.io/rook/ceph:v1.7.7: not found
27m         Warning   Failed              pod/rook-ceph-operator-6866d8fb9b-4tk9j    Error: ErrImagePull
4m17s       Normal    BackOff             pod/rook-ceph-operator-6866d8fb9b-4tk9j    Back-off pulling image "rook/ceph:v1.7.7"
27m         Warning   Failed              pod/rook-ceph-operator-6866d8fb9b-4tk9j    Error: ImagePullBackOff
29m         Normal    SuccessfulCreate    replicaset/rook-ceph-operator-6866d8fb9b   Created pod: rook-ceph-operator-6866d8fb9b-4tk9j
29m         Normal    ScalingReplicaSet   deployment/rook-ceph-operator              Scaled up replica set rook-ceph-operator-6866d8fb9b to 1
```

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04
* Kernel (e.g. `uname -a`): 5.4.0-88-generic
* Cloud provider or hardware configuration: Digital Ocean - Kubernetes 1.21.5-do.0
* Rook version (use `rook version` inside of a Rook Pod): Unable to get into pod, but 1.7.7 is expected
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): 1.21.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Digital Ocean
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): None, cluster  won't start
![Screenshot from 2021-11-04 15-19-23](https://user-images.githubusercontent.com/7537557/140413805-86a01f80-4ed7-4fe0-a325-5ebdfcafbe9e.png)

**Comment by travisn** [comment]
The v1.7.7 release is in process, will be out within the hour. For now, please use the v1.7.6 tag.

**Comment by serewicz** [comment]
Thank you for the response and information. If I can humbly request, could the newer image be made available prior to updating all the scripts and files?

**Comment by travisn** [comment]
The images are expected to be published at the same time as the docs that reference the new release, there was just a glitch in the release process today that caused the delay. Hopefully it will not happen again!

**Comment by travisn** [comment]
Although if you're pulling the head of the release branch from github, there will always be a small delay (~30 minutes) between the new version tag and the release images being pushed. Could you use a specific tag instead of the head of the release branch?

**Comment by travisn** [comment]
The v1.7.7 tag is pushed now.

**Comment by serewicz** [comment]
Yes, After going to hub.docker.com I tried a recent tag v1.7.0.566.gbe1c593  and it worked. But omitting the tag and using 1.7.7 did not.  Looks like 1.7.7 is available. Thanks for you help! Marking closed.
