### ISSUE TITLE
Enabling volumeexpansion of cephfs volumes via helm chart

### ISSUE THREAD

**Issue by timbrd** [rook/rook#9120]
I have set up a ceph cluster using the official helm charts. Everything works as expected and I can create block and cephfs volumes.

When I checked whether volume expansion was supported by the storage classes, k8s reported that it was only enabled for the cephblockpool, but not for the cephfs storage class. After editing the storage class and adding `allowVolumeExpansion: true`, I was able to resize an existing pvc without any issues.

Looking at the corresponding helm templates, there is an option for toggling the support of expanding [block volumes](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph-cluster/templates/cephblockpool.yaml#L24), but the [template for cephfs storageclass](https://github.com/rook/rook/blob/master/cluster/charts/rook-ceph-cluster/templates/cephfilesystem.yaml) is missing that option.

So, is the volume expansion of cephfs volumes officially supported?

**Comment by travisn** [comment]
Volume expansion with cephfs is supported, the helm chart is just new and that option was missed. Thanks for raising the issue!
