### ISSUE TITLE
Apply Recommended labels to  DaemonSets, Services, ConfigMaps, Jobs, etc

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#9148]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

This feature is an extension for https://github.com/rook/rook/pull/8678.
As discussed [here](https://github.com/rook/rook/pull/8678#pullrequestreview-801646947) we also need Recommended labels for DaemonSets, Services, ConfigMaps, Jobs,etc.
Currently, we have put these labels on the Deployments and pods.

**What is use case behind this feature:**

To take full advantage of using these Recommended labels, they should be applied on every resource object.

**Comment by aruniiird** [comment]
Taking this issue...

**Comment by travisn** [comment]
If there is a need for this, let's open a new issue with more scoped updates to the labels and the clear scenario description.
