### ISSUE TITLE
Rook-ceph-cluster chart, dashboard part: the ingress template points to the wrong service with SSL enabled

### ISSUE THREAD

**Issue by cyrilcros** [rook/rook#9152]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The ingress is not working, with a 503 error. I see a service `rook-ceph-mgr-dashboard` which exposes a port 8843 named `https-dashboard`. The ingress instead points to `http-dashboard`, no s. https://github.com/rook/rook/blob/480c7f89f223215dc108c0e6712ffd70bc2b30ed/cluster/charts/rook-ceph-cluster/templates/ingress.yaml#L27
Things may be okay with SSL off, I haven't tried it.

**Expected behavior:**
The ingress points to the right service.

**How to reproduce it (minimal and precise):**

Please do note this is with SSL turned on for the ingress/dashboard, I haven't tried without it. **EDIT:** with `ssl: false` the port name doesn't change, it is still https.

Using v1.7.7 of the `rook-ceph-cluster` chart. 
```
cephClusterSpec:
  dashboard: 
    urlPrefix: / 
    enabled: true 
    port: 8843
    ssl: true
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
Can confirm... :( Also the port should be 7000 as it seems?

```bash
ceph mgr services | jq .dashboard
"http://10.244.12.94:7000/"
```
