### ISSUE TITLE
OSD prepare job `blkdevmapper` missing required capabilities

### ISSUE THREAD

**Issue by Omar007** [rook/rook#9156]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSD prepare jobs are not run successfully because the `blkdevmapper` init container enters a crashloop due to missing but needed capabilities.

The init container in question relies on the presence of the `MKNOD` capability to do the desired copy operation but it does not currently request it.  
As such, it fails on runtimes that do not assign this capability by default, or Kubernetes clusters with tightened down default capabilities; any cluster that does not happen to assign the `MKNOD` capability to all containers by default.

**Expected behavior:**
The init container properly declares the capability in its securityContext and the OSD prepare jobs run successfully regardless of the cluster's/runtime's default assigned capabilities.

**How to reproduce it (minimal and precise):**
Either:
* Run a crio based cluster which does not grant the `MKNOD` capability by default
* Tighten down your cluster so pods do not get the `MKNOD` capability by default

**File(s) to submit**:

*blkdevmapper logs*
```
kubectl -n rook-ceph logs -f rook-ceph-osd-prepare-nvme-ssd-wal-0f6v8j--1-pm4b8 -c blkdevmapper
+ PVC_SOURCE=/nvme-ssd-wal-0f6v8j
+ PVC_DEST=/mnt/nvme-ssd-wal-0f6v8j
+ CP_ARGS=(--archive --dereference --verbose)
+ '[' -b /mnt/nvme-ssd-wal-0f6v8j ']'
+ cp --archive --dereference --verbose /nvme-ssd-wal-0f6v8j /mnt/nvme-ssd-wal-0f6v8j
'/nvme-ssd-wal-0f6v8j' -> '/mnt/nvme-ssd-wal-0f6v8j'
cp: cannot create special file '/mnt/nvme-ssd-wal-0f6v8j': Operation not permitted
```

**Environment**:
* Kubernetes version: 1.22.2
* Kubernetes cluster type: Bare metal
* Container runtime: crun (crio)
* Rook cluster type: PVC style backed by local storage.

**Comment by Omar007** [comment]
Did a quick search through the code and I think all the relevant stuff is in `pkg/operator/ceph/cluster/osd/spec.go`:
https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/osd/spec.go#L795
https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/osd/spec.go#L827
https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/osd/spec.go#L934
https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/osd/spec.go#L981
https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/osd/spec.go#L1015
https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/osd/spec.go#L1041
https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/osd/spec.go#L1075

I also spotted something else that seems slightly odd. For the first method it is mentioned in the preceding comment that it can't be mounted in a privileged container but the function it uses to get a securityContext object does not even guarantee that it will always be unprivileged (e.g. when deploying on OpenShift using the provided OpenShift examples):  
https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/osd/spec.go#L776
In theory that would mean this should be failing in those deployments :thinking:   

Assuming that comment is not valid (any more?) and mounting privileged is actually possible, as all of these occurrences are using the same function, it does seem like setting the OpenShift related hostPath setting might be a possible work-around.  
I'll give it a shot and provide an update once I know more. That said, just making it all completely privileged is not desirable or even needed in this case so it should still be addressed at some point imo.

**Comment by travisn** [comment]
> Assuming that comment is not valid (any more?) and mounting privileged is actually possible, as all of these occurrences are using the same function, it does seem like setting the OpenShift related hostPath setting might be a possible work-around.

I know this has been working on OpenShift where it has been privileged as you pointed out. The privileged mode on OpenShift shouldn't be needed in this init container though. The privileged was only intended for containers that mount a host path for logging, which this container wouldn't have. @leseb Any other concerns I'm missing?

**Comment by Omar007** [comment]
I gave it a go and setting that flag on the operator does work as a work-around for this problem. But the proper thing to do it is not.  
Since I did the quick search earlier I also decided to put up a PR with a shot at correcting this :+1:

**Comment by leseb** [comment]
> > Assuming that comment is not valid (any more?) and mounting privileged is actually possible, as all of these occurrences are using the same function, it does seem like setting the OpenShift related hostPath setting might be a possible work-around.
> 
> I know this has been working on OpenShift where it has been privileged as you pointed out. The privileged mode on OpenShift shouldn't be needed in this init container though. The privileged was only intended for containers that mount a host path for logging, which this container wouldn't have. @leseb Any other concerns I'm missing?

Right, this particular container does not need extra permissions or hostpath. It's good to reduce the permission scope to `MKNOD` only for this container.
