### ISSUE TITLE
Mons Cluster ClusterInfo gets updated with lesser Information

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#9159]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

The Mons Cluster ClusterInfo gets updated when `initClusterInfo` is called, which makes ClusterInfo deflected from what it was initialized from the actually cluster [here](https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/mon/mon.go#L190) https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/mon/mon.go#L210-L212

The `initClusterInfo`  calls the `CreateOrLoadClusterInfo` which in results intialize mon cluster with new clusterInfo struct fields.https://github.com/rook/rook/blob/c3b5d3b078f096e6eaa5d0b5d0fcbe1206b0b071/pkg/operator/ceph/cluster/mon/config.go#L116-L117

So as a result `cluster.objectmeta.name` is not being set, so producing panics when CR name is called while setting up the labels on the mon deployments.

**Expected behavior:**

Mons Cluster ClusterInfo should be updated properly. A small fix would just update the CR name on `cluster.objectmeta.name` when the `initClusterInfo` returns back.

@travisn but I think the `CreateOrLoadClusterInfo` code is called from multiple places which we need to look for, and also need to look for the other fields which are missed over-writing/re-initializing.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by travisn** [comment]
There are a number of places where `clusterInfo.SetName()` is called, we might just need to set it in a couple more places to get these scenarios to work. We hopefully don't need to touch all the places where LoadClusterInfo() is called.
