### ISSUE TITLE
[BUG] Following rook 1.7.0 quickstart on k3d 5.1.0 wipes entire disk / destroys host OS

### ISSUE THREAD

**Issue by neoakris** [rook/rook#9166]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
* Didn't expect quickstart to wipe entire disk / destroy host OS

**Expected behavior:**
* Expected quickstart to be a safe demo

**How to reproduce it (minimal and precise):**
1. Install Ubuntu 21.04 LTS
1. curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v5.1.0 bash
1. k3d cluster create
1. (Follow quickstart)
  1. git clone --single-branch --branch release-1.7 https://github.com/rook/rook.git
  1. cd rook/cluster/examples/kubernetes/ceph
  1. kubectl apply -f crds.yaml -f common.yaml -f operator.yaml
  1. kubectl apply -f cluster-test.yaml
(since cluster-test was recommended for minikube I figured it'd be fine for k3d)
(after about 3 minutes my computer crashed, and reboot just showed grub2 cli interface, messing around with cli showed no bootable partitions, so I booted from a live usb to inspect my partition using gnome-disk-utility. Instead of my host OS and data. I see the entire drive was wiped and replaced with Partition 1: 537MB fat, Partition 2: 500GB ceph_bluestore, 1.1mb free space. Luckily I use automatic data backup solutions, so I didn't really lose data, still though it's gonna suck reinstalling and customizing things how I like. Good excuse to check out OpenSUSE Tumbleweed though.)

I wonder if this is what did it? I'm not sure I'm new to ceph
https://github.com/rook/rook/blob/release-1.7/cluster/examples/kubernetes/ceph/cluster-test.yaml#L43-45
Mentions useAllNodes and useAllDevices true, so I guess it thought it could format the root partition? not sure.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 21.04 x64
* Kernel (e.g. `uname -a`): (unsure disk was wiped, all latest updates had been installed)
* Cloud provider or hardware configuration:  baremetal desktop
* Rook version (use `rook version` inside of a Rook Pod): 1.7
* Storage backend version (e.g. for ceph do `ceph -v`): unsure wiped disk before got that far
* Kubernetes version (use `kubectl version`): `k3d version`    
```
k3d version v5.1.0
k3s version v1.21.5-k3s2 (default)
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): unsure wiped disk before got that far

Note: I created matching issue on k3d github      
(https://github.com/rancher/k3d/issues/859)

**Comment by sp98** [comment]
I don't think rook on k3s with docker is supported. 

Another issue - https://github.com/rancher/k3d/issues/835

If not minikube, then you can try k3s

Some references:
https://itnext.io/using-rook-on-a-k3s-cluster-8a97a75ba25e
https://github.com/stblassitude/k3s-rook
https://itnext.io/using-rook-on-a-k3s-cluster-8a97a75ba25e

**Comment by leseb** [comment]
Sorry to hear that this happened, normally we should be immune to picking up the OS disk. The prepare job logs would be helpful to understand why the main device got picked but since everything is gone... I'll look at the code and see how we can prevent this even further.

**Comment by leseb** [comment]
Ok a bit more thoughts here, Rook relies on the ceph-volume tool (part of ceph) to determine whether a disk is available or not by issuing `ceph-volume inventory <dev>`. So if you can repro again, I'd suggest opening a tracker bug here https://tracker.ceph.com/. At this point, there is nothing Rook can do. Thanks for your understanding. Also, a general advise for next time, **never ever** deploy anything that could alter your own system, always use virtual machines. Our documentation also stipulates using minikube to quickly get started: https://github.com/rook/rook/tree/master/tests

**Comment by neoakris** [comment]
Thanks I agree with the bit about testing in VMs, it's what I normally do, ironically the one time I didn't is when this happened. "normally we should be immune to picking up the OS disk." That was what I was expecting too.

@leseb Before this gets closed closed could you reopen with the following easy to accomplish acceptance criteria? 
Update the rook quickstart be updated to warn people about this footgun, right next to the recommendation to use minikube, explicitly recommend against running on k3d/kind.

**Comment by leseb** [comment]
> Thanks I agree with the bit about testing in VMs, it's what I normally do, ironically the one time I didn't is when this happened. 

Yeah, it's always like this :(

>"normally we should be immune to picking up the OS disk." That was what I was expecting too based on my previous experience with openEBS (it too looks for unused partitions/disks, but if already in use didn't mess with them.)
> 
> @leseb Before this gets closed closed could you reopen with the following easy to accomplish acceptance criteria? Update the rook quickstart be updated to warn people about this footgun, right next to the recommendation to use minikube, explicitly recommend against running on k3d/kind.

Ok, I'll leave a warning in the doc.

**Comment by kconde2** [comment]
Hello, I just lost all my data while installing the demo on [KiND](https://kind.sigs.k8s.io) a cluster. I think people should be informed.

**Comment by travisn** [comment]
@kconde2 Sorry to hear that! There is a note in the [developer guide](https://rook.github.io/docs/rook/v1.8/development-environment.html#minikube) that warns to run in a VM and not on your host, but we need to make it more obvious in the main quickstart guide.
