### ISSUE TITLE
NFS Data-in-transit encryption  support for rook-ceph

### ISSUE THREAD

**Issue by hiteshmathur19** [rook/rook#9170]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Need to provide NFS Data-in-transit encryption support for rook-ceph

**What is use case behind this feature:**
For securing the data-in-transit for NFS backend in case of rook-ceph

**Comment by leseb** [comment]
For this request to be implemented, we would need either:

* NFS encryption which would be needed in Ganesha, I'm not sure if it's available and if ceph-nfs supports it
* use mTLS across the nodes, I believe https://istio.io/ could help with that. Then you don't need NFS encryption

In any case, the initial feature request is not in Rook. You can open an issue for Ceph here https://tracker.ceph.com/.

I'm closing this, feel free to re-open if the encryption is already available in Ceph-NFS and Ganesha but I doubt it is.
Thanks.
