### ISSUE TITLE
create-external-cluster-resources.py not respecting cluster_name in the output

### ISSUE THREAD

**Issue by CO-lhageman** [rook/rook#9192]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The json output of the generated Kubernetes resources does not append the cluster_name to userID of the Ceph Users. 
Example:
```
[...]
{
    "name": "rook-csi-rbd-provisioner",
    "kind": "Secret",
    "data": {
        "userID": "csi-rbd-provisioner",
        "userKey": "SOMEKEY"
    }
},
[...]
```
The Ceph auth keys look like this:
```
$ ceph auth ls 
[...]
client.csi-rbd-provisioner-k8s-stage
	key: SOMEKEY
	caps: [mgr] allow rw
	caps: [mon] profile rbd
	caps: [osd] profile rbd pool=somepool
```

It is also unclear to me what the --cluster-name parameter is supposed to achieve - The help text says "Ceph cluster name". While Ceph clusters can certainly have a name, it is not used anywhere in rook. It is only appended to the Ceph user IDs in the Ceph cluster. 
I am (mis-?)using it to create a multi-tenant cluster environment, the script can generate different users meant for different K8s clusters. If that is the intended use-case for this parameter the help text should be more along the lines of "K8s cluster name for multi-tenancy"

**Expected behavior:**
The secrets should look like this:
```
[...]
{
    "name": "rook-csi-rbd-provisioner",
    "kind": "Secret",
    "data": {
        "userID": "csi-rbd-provisioner-k8s-stage",
        "userKey": "SOMEKEY"
    }
},
[...]
```
**How to reproduce it (minimal and precise):**

`python3 create-external-cluster-resources.py --ceph-conf /etc/ceph/ceph.conf --run-as-user client.cn1000310-monitoring --cluster-name k8s-stage --namespace rook-ceph --restricted-auth-permission true --format json --cephfs-filesystem-name cn1000310_fs_01 --cephfs-metadata-pool-name cephfs.cn1000310_fs_01.meta --cephfs-data-pool-name cephfs.cn1000310_fs_01.data --rbd-data-pool-name cn1000310_rbd_01`

**Environment**:
* Script version: https://github.com/rook/rook/commit/7d106c8e21a203787e5a7347b1ea73e20916de60
This was introduced with https://github.com/rook/rook/pull/8994/ which also added restrictive ceph caps (thank you for that!)

**Comment by parth-gr** [comment]
@CO-lhagman , yes right ceph users-ID should also need to have the cluster-name.

>I am (mis-?)using it to create a multi-tenant cluster environment, the script can generate different users meant for different K8s clusters. If that is the intended use-case for this parameter the help text should be more along the lines of "K8s cluster name for multi-tenancy"

Yes, the intention is to separate the similar type users of different clusters.
ig this line makes it understandable in `help`,`Restricting the users per pool and per cluster`

**Comment by parth-gr** [comment]
@leseb @travisn @aruniiird I was thinking to have the 
Auth key client and user-ID of users as `client.csi-rbd-provisioner-clusterName-poolName` , `csi-rbd-provisioner-clusterName-poolName` resp.
So by this, we can restrict/distinguish users on the basis of different pools and clusters.

**Comment by leseb** [comment]
> @leseb @travisn @aruniiird I was thinking to have the Auth key client and user-ID of users as `client.csi-rbd-provisioner-clusterName-poolName` , `csi-rbd-provisioner-clusterName-poolName` resp. So by this, we can restrict/distinguish users on the basis of different pools and clusters.

I don't think we need to put the pool name in the keyring name since the keycap has the pool in it already. It's superfluous.

**Comment by CO-lhagman** [comment]
> I don't think we need to put the pool name in the keyring name since the keycap has the pool in it already. It's superfluous.

Adding the pool name in the keyring name would allow for the use of multiple Storage Classes with different pools (and therefor different users). You would need to change the cluster-name otherwise to accomplish this.

**Comment by leseb** [comment]
> > I don't think we need to put the pool name in the keyring name since the keycap has the pool in it already. It's superfluous.
> 
> Adding the pool name in the keyring name would allow for the use of multiple Storage Classes with different pools (and therefor different users). You would need to change the cluster-name otherwise to accomplish this.

Hum 🤔 , in theory, nothing prevents you from having multiple SCs consuming the same pool (not recommended) so I don't see the problem here. The name of the key does not really matter unless you have different clusters. If this is is the case, why not simply use a different "cluster name" to differentiate them? I think this is what `--cluster-name` is supposed to help achieve. Agree that the name can be confusing since Ceph cluster can have names, but this is not supported anymore and Rook does not use it. So in the case cluster name is helpful for multi-tenant env when you have multiple cluster with ceph-csi consume the same external ceph cluster.

**Comment by CO-lhagman** [comment]
> Hum thinking , in theory, nothing prevents you from having multiple SCs consuming the same pool (not recommended) so I don't see the problem here.

I don't want multiple SCs consuming the same pool, I want multiple SCs consuming different pools. Example:
SC rook-ceph-block-fast to pool "rbd-cluster1-fast" with high IOPS Quotas
SC rook-ceph-block-slow to pool "rbd-cluster1-slow" for a lower performance pool

**Comment by Madhu-1** [comment]
CSI supports pool name in the SC. so you can create multiple SC with different pool names but what matters here is the CSI secrets. If we are creating CSI secretes with with pool-name-cluster-name etc so we can add that to the SC

I think what you are looking at is as below
you need to pass different --cluster-name to have unique ceph user names or add pool name as part of the ceph user we are creating.

**Comment by leseb** [comment]
> CSI supports pool name in the SC. so you can create multiple SC with different pool names but what matters here is the CSI secrets. If we are creating CSI secretes with with pool-name-cluster-name etc so we can add that to the SC
> 
> I think what you are looking at is as below you need to pass different --cluster-name to have unique ceph user names if we are creating the secrets with unique names we are good (if not we need to fix it) or add pool name as part of the ceph user we are creating.

The --cluster-name value appended to the key name should be sufficient I believe since the pool name is already in the keyring caps.

**Comment by Madhu-1** [comment]
> > CSI supports pool name in the SC. so you can create multiple SC with different pool names but what matters here is the CSI secrets. If we are creating CSI secretes with with pool-name-cluster-name etc so we can add that to the SC
> > I think what you are looking at is as below you need to pass different --cluster-name to have unique ceph user names if we are creating the secrets with unique names we are good (if not we need to fix it) or add pool name as part of the ceph user we are creating.
> 
> The --cluster-name value appended to the key name should be sufficient I believe since the pool name is already in the keyring caps.

if we pass different cluster name values that should be fine. but it makes the identification very difficult

**Comment by parth-gr** [comment]
The conclusion from the discussion:

The security needs to improve, so we are coming up with having per `cluster` per `pool` per `rados namespace` the `keyrings`, the `users` and the `CSI secrets`
Keyring:                   "client.csi-rbd-provisioner-clustername-poolname-radosNamespace"
CSI-secret-name:    "rook-csi-rbd-provisioner-clustername-poolname-radosNamespace"
userID:                    "csi-rbd-provisioner-clustername-poolname-radosNamespace"

If cluster name, pool name, radosNamespace is not present we will not append it to the name.

**Comment by CO-lhagman** [comment]
The radosNamespace one is a good catch! Didn't know that was possible and now reading up on it, this seems like what we need/want in our usecase. OSD Caps also allow you to restrict them to namespaces.
