### ISSUE TITLE
Reduced data availability: 4 pgs inactive, 4 pgs incomplete;

### ISSUE THREAD

**Issue by hhy5861** [rook/rook#9194]
How to fix this kind of problem, please know the solution provided, thank you

```
[root@rook-ceph-tools-7f6f548f8b-wjq5h /]# ceph health detail
HEALTH_WARN Reduced data availability: 4 pgs inactive, 4 pgs incomplete; 95 slow ops, oldest one blocked for 13741 sec, daemons [osd.0,osd.4] have slow ops.
[WRN] PG_AVAILABILITY: Reduced data availability: 4 pgs inactive, 4 pgs incomplete
    pg 3.6 is incomplete, acting [0,1,2] (reducing pool ec-data-pool min_size from 2 may help; search ceph.com/docs for 'incomplete')
    pg 10.46 is incomplete, acting [4,3,2] (reducing pool bucket-store.rgw.buckets.data min_size from 2 may help; search ceph.com/docs for 'incomplete')
    pg 10.54 is incomplete, acting [0,1,2] (reducing pool bucket-store.rgw.buckets.data min_size from 2 may help; search ceph.com/docs for 'incomplete')
    pg 10.64 is incomplete, acting [0,3,2] (reducing pool bucket-store.rgw.buckets.data min_size from 2 may help; search ceph.com/docs for 'incomplete')
[WRN] SLOW_OPS: 95 slow ops, oldest one blocked for 13741 sec, daemons [osd.0,osd.4] have slow ops.
```

**Comment by travisn** [comment]
You are concerned about the slow ops? Check a few things:
- Does osd.0 or osd.4 have a healthy disk?
- Are those two osds on the same node? Any resource issues (high load) on them?
- I'd suggest looking at ceph issues such as [this one](https://tracker.ceph.com/issues/44184) for the slow ops troubleshooting.

**Comment by hhy5861** [comment]
> You are concerned about the slow ops? Check a few things:
> 
> * Does osd.0 or osd.4 have a healthy disk?
> * Are those two osds on the same node? Any resource issues (high load) on them?
> * I'd suggest looking at ceph issues such as [this one](https://tracker.ceph.com/issues/44184) for the slow ops troubleshooting.

The key problem should be this, which caused me to be unable to use it normally.
```
[WRN] PG_AVAILABILITY: Reduced data availability: 4 pgs inactive, 4 pgs incomplete
```

**Comment by varun-vyas** [comment]
I am also having same issue but won't able to find any solution. This issue has cropped up all of sudden...

**Comment by travisn** [comment]
@hhy5861 @varun-vyas 
- What version of rook and ceph are you running?
- Did you recently update the rook or ceph version and then saw this start to happen?
- Any other events that might have happened in your cluster? OSDs went down? Network issues? etc?
