### ISSUE TITLE
ceph cluster has not back up after storage node reboot

### ISSUE THREAD

**Issue by RomanKisilenko** [rook/rook#9217]
**Is this a bug report or feature request?**
* Bug Report

**How to reproduce it (minimal and precise):**
1. Install a single-node rook.io ceph cluster (I used 4 OSDs), make sure it is healthy
2. Reboot the storage node
3. Wait for the node to back up again and osd pods to restart

**Deviation from expected behavior:**
Cluster is not healthy after a restart.
```
$ kubectl -n rook-ceph exec deploy/rook-ceph-tools -- ceph status
  cluster:
    id:     dc7c6e61-4325-4b9e-84c3-6f4774a1737d
    health: HEALTH_WARN
            Reduced data availability: 128 pgs inactive
 
  services:
    mon: 3 daemons, quorum a,b,c (age 41m)
    mgr: b(active, since 44m), standbys: a
    osd: 4 osds: 4 up (since 24m), 4 in (since 73m)
 
  data:
    pools:   1 pools, 128 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             128 unknown
```
ceph osd df just hangs indefinitely

**Expected behavior:**
Cluster recovered and ready to serve requests again.

OSD logs seems fine.

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
* Kernel (e.g. `uname -a`):
Linux storage1.kube.domain.tld 5.4.0-90-generic Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
32 Gb RAM, 4x4TB HDD server
* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.7.8
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)
* Kubernetes version (use `kubectl version`):
v1.18.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
HEALTH_WARN Reduced data availability: 128 pgs inactive

**Comment by leseb** [comment]
Can the mgr pod communicate with the OSD containers?

**Comment by RomanKisilenko** [comment]
Most likely there was some communication issue between ceph pods, because after we rebooted the rest of the nodes in our cluster, the ceph status reports healthy again and the issue has gone.

I'm still concerned that a failure of storage node (like reboot) can lead to downtime which does not recover automatically once the faulty node is back up again. This issue increases downtime exposition on  typical failures from ~10 minutes to ~8 hours which is an issue for our production for e.g.

**Comment by leseb** [comment]
If they are communication issues between the component of the cluster that's hard to track. Typically `100.000% pgs unknown` means that the mgr container cannot communicate with the OSDs. 100% means all of them, if you restart a single node (assuming your cluster has more than one node and it should!) then this problem should not occur. You should see a small degradation only and after a timeout of 10min the cluster will start to backfill data onto other nodes.

**Comment by RomanKisilenko** [comment]
We are trying to use a cluster with a single storage node and 4 OSDs to save $ on hardware as our application can tolerate accidental (short) downtimes.

**Comment by leseb** [comment]
Ok so if there is a single node to run all the OSDs and this node reboots, the cluster will only be available once the node is done rebooting and containers are running again. I see 10min has been mentioned, but also 8 hours, what is the 8 hours?

**Comment by RomanKisilenko** [comment]
As mentioned in bug report the ceph was not recovered after reboot have completed and all osds have started, which takes 10 minutes. 8 hours is a time it took to figure out how to work around the issue (by rebooting the other nodes). Usually it takes time to be able to intervene manually which ranges from several hours to 8 hours depending on the time of the day.

**Comment by leseb** [comment]
> As mentioned in bug report the ceph was not recovered after reboot have completed and all osds have started, which takes 10 minutes. 

Makes sense indeed. If we reboot the **only** node that serves I/O then everything stops until this node is back online.

>8 hours is a time it took to figure out how to work around the issue (by rebooting the other nodes).

This part I don't understand. What do we need to work around? Why did we have to reboot other nodes?

Honestly, I'm not sure what different behavior is expected from the one that was experienced.

**Comment by RomanKisilenko** [comment]
Sorry for confusion. 

We are using a kubernetes 1.18.10 cluster provisioned with kubespray.

To recap:
1. We installed rook-ceph, verified that it was working fine.
2. We rebooted storage node. Once the node was back up again the ceph was not healthy. This lasted for many hours. Note, that at this stage connectivity across kubernetes nodes was not broken and other apps running on the worker nodes was able to communicate across the cluster.
3. We rebooted the other nodes on our cluster as a part of scheduled maintenance and figured out that rebooting other nodes has fixed the above ceph issue as well.

So based on your feedback this is obviously a network connectivity issue across rook-ceph pods in our kubernetes cluster.

The question i why did it happen. It can be a faulty kubernetes cluster (which I think is unlikely since it is just a plain kubespray cluster on top of Ubuntu 20.04). Or it can be some issue in rook-ceph.

If anything extra is needed from my side I'm ready to collect the information I can and provide to you.

**Comment by leseb** [comment]
Thanks for the clarification. Typically it's much easier to debug while the env is still broken so we can get logs. By any chance, do you still have the logs for all the mons, mgr and OSDs?
If not, I'm afraid it will be very difficult to help out.

Thanks.
