### ISSUE TITLE
Failed to provision volume with StorageClass "ceph-filesystem" due to Volume ID exists after clean up then relaunch cluster

### ISSUE THREAD

**Issue by morningspace** [rook/rook#9218]
**Is this a bug report or feature request?**

I follow the [doc](https://rook.io/docs/rook/v1.7/helm.html) to install ceph using helm and everything works fine. Then, follow the [doc](https://rook.io/docs/rook/v1.7/ceph-teardown.html) to clean up the cluster, and reinstall using the same helm approach.

But this time, I see my PVC reports an error event:
```console
ProvisioningFailed failed to provision volume with StorageClass "ceph-filesystem": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-ad525059-4fd7-4454-af37-87e3d8d70217 already exists
```

**Deviation from expected behavior:**

This blocks the PV to be created. BTW: I'm using ceph-filesystem only.

**Expected behavior:**

PV should be able to be created after clean up and reinstall.

**How to reproduce it (minimal and precise):**

One thing to note is that when I clean up the cluster by deleting the CephCluster instance, I didn't see the rook-ceph-cleanup jobs created even that I've applied:

```console
kubectl -n rook-ceph patch cephcluster rook-ceph --type merge -p '{"spec":{"cleanupPolicy":{"confirmation":"yes-really-destroy-data"}}}'
```

I guess that is the major cause to my issue. So, the question would be that:
1) How to get it back if in such a case? I have followed the guide to delete the contents such as `/var/lib/rook`, `/dev/ceph-*`, and `/dev/mapper/ceph--*`.
2) How to have the jobs to be triggered reliably? What I did is to delete the CephFilesystem instance first, then StorageClass, then CephCluster instance. It looks CephCluster was deleted too soon where the jobs did not get chance to be triggered.

Here is the ceph status output:
```console
sh-4.4$ ceph status
  cluster:
    id:     32f98c22-a1eb-438c-9e3f-6eaf88fe10e0
    health: HEALTH_WARN
            1 MDSs report slow metadata IOs
            Reduced data availability: 64 pgs inactive
            OSD count 0 < osd_pool_default_size 3
 
  services:
    mon: 3 daemons, quorum a,b,c (age 20m)
    mgr: a(active, since 19m)
    mds: 1/1 daemons up, 1 standby
    osd: 0 osds: 0 up, 0 in
 
  data:
    volumes: 1/1 healthy
    pools:   2 pools, 64 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs:     100.000% pgs unknown
             64 unknown
```

**Environment**:
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux CoreOS 48.84.202109210859-0
* Kernel (e.g. `uname -a`): Linux 4.18.0-305.19.1.el8_4.x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.7.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)
* Kubernetes version (use `kubectl version`): v1.21.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift 4.8.13
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
```console
ceph health
HEALTH_WARN 1 MDSs report slow metadata IOs; Reduced data availability: 64 pgs inactive; OSD count 0 < osd_pool_default_size 3
```

**Comment by travisn** [comment]
Look at the following logs for more details:
- Do the OSD prepare pod logs show any errors? If the disks were not fully cleaned up from the prior install, there should be errors about skipping the disks since they belong to another cluster. In that case, check again if you have fully wiped the devices.
- If you don't see the cleanup jobs created, there must be something else blocking them from starting during the cluster cleanup. The operator log should show what is not getting cleaned up.
