### ISSUE TITLE
rook fails to mount a volume

### ISSUE THREAD

**Issue by RomanKisilenko** [rook/rook#9219]
**Is this a bug report or feature request?**
* Bug Report

**How to reproduce it (minimal and precise):**
1. Set up took.io cluster and storage class (I used ec pool and storage class with compression enabled)
2. Try to allocate pvcs based on storage classs

**Deviation from expected behavior:**
The volume fails to mount with error:
Events:
  Type     Reason       Age                 From                                   Message
  ----     ------       ----                ----                                   -------
  Normal   Scheduled    <unknown>           default-scheduler                      Successfully assigned at-mt/ps-mt-37f711fe-751e-41e0-84ab-c50497fe5fbb-0-0 to worker3.domain.tld
  Warning  FailedMount  62s                 kubelet, worker3.domain.tld  Unable to attach or mount volumes: unmounted volumes=[ps-mt-37f711fe-751e-41e0-84ab-c50497fe5fbb-0-data], unattached volumes=[ps-mt-37f711fe-751e-41e0-84ab-c50497fe5fbb-0-data default-token-44wz5]: timed out waiting for the condition
  Warning  FailedMount  56s (x9 over 3m5s)  kubelet, worker3.domain.tld  MountVolume.MountDevice failed for volume "pvc-b65cb2b3-2f3f-437b-a097-523d1c2405f6" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000003-b58345f3-4af4-11ec-ba91-1e24cafcaceb already exists

**Expected behavior:**
1. Volume is created and mounted properly

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
1.7.8
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
1.18.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
HEALTH_OK

**Comment by Madhu-1** [comment]
@RomanKisilenko can you please check https://rook.io/docs/rook/v1.7/ceph-csi-troubleshooting.html helps?

**Comment by RomanKisilenko** [comment]
@Madhu-1 I think above link is of no much help. I followed https://rook.io/docs/rook/v1.7/ceph-csi-troubleshooting.html#provisioning-volumes and the only thing I can see is that kubectl logs csi-rbdplugin-bcfzv -c csi-rbdplugin -n rook-ceph logs are filled with lot of errors like above.

The issue reproduces with some probability which is less than 1 and greater than 0. Some of pods were able to mount volumes correctly, while others have stuck indefinitely with an error like above.

**Comment by Madhu-1** [comment]
@RomanKisilenko can you please increase the log level to `5` https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator.yaml#L40-L42  and try to mount again and paste the logs from the csi-rbdplugin plugin pod from the node where the application mount is failing here?

**Comment by RomanKisilenko** [comment]
@Madhu-1 OK, this is happened on our prod, so that we disabled the use of rook.io in our app for now. I will be able to check the above on coming weekends when no one will be using our app and impact will be minimal.

**Comment by Madhu-1** [comment]
Yes sure. a couple of questions 

* Is mounting working for other pools than EC?
* Mounting for rbd images in EC pool was working before?
* Is this a fresh ceph cluster or an upgraded one?
* Please provide `ceph -s` output

**Comment by RomanKisilenko** [comment]
@Madhu-1 
1. Is mounting working for other pools than EC? We did not check any other pools.
2. Mounting for rbd images in EC pool was working before? I think yes, because some of the volumes was mounted successfully on the same pool.
3. Is this a fresh ceph cluster or an upgraded one? This is a fresh ceph cluster.
```
  cluster:
    id:     dc7c6e61-4325-4b9e-84c3-6f4774a1737d
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum b,d,e (age 17h)
    mgr: a(active, since 18h), standbys: b
    osd: 4 osds: 4 up (since 18h), 4 in (since 22h)
 
  data:
    pools:   3 pools, 96 pgs
    objects: 822 objects, 2.3 GiB
    usage:   3.6 GiB used, 15 TiB / 15 TiB avail
    pgs:     96 active+clean
```

**Comment by Madhu-1** [comment]
okay got it. please provide the below details when you get time

* logs from all the containers for csi-rbdplugin pod (Damon set) running on the node where the mount is failing
* `ps -ef |grep rbd` output from the csi-rbdplugin container of the above pod
* dmesg logs from the node where the mount is failing.

**Comment by RomanKisilenko** [comment]
@Madhu-1 Is there any way I can send you the link to these in private (e.g. via email, so that I do not expose too much details about our servers in public)?

**Comment by Madhu-1** [comment]
If you are okay in sharing the details. You can share the logs in the email specified in  https://github.com/Madhu-1
