### ISSUE TITLE
Users created by create-external-cluster-resources.py --restricted-auth-permissions won't work for CephFS

### ISSUE THREAD

**Issue by CO-lhagman** [rook/rook#9227]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When creating a new deployment and using a pvc that references my cephfs storage class, the pvc errors out with the following warning: `failed to provision volume with StorageClass "rook-cephfs": rpc error: code = Internal desc = rados: ret=-1, Operation not permitted`
Using the admin keyring and not restricted users works fine.

**Expected behavior:**
I expect the PVC (and volume) to be successfully created.

**How to reproduce it (minimal and precise):**
create a external ceph cluster and generate the secrets with the create-external-cluster-resources.py in --restricted-auth-permissions mode. Then create a PVC with the rook-cephfs storage class.

**Additional Notes:**
While this should work in theory, has someone actually tested this and managed to get it working?
This might be related to https://github.com/ceph/ceph-csi/issues/2506 (though they are talking about subvolumes [which sound like a good approach to multi tenancy cephfs, maybe take a closer look at this in the future?])

**File(s) to submit**:

Ceph users:
```
client.csi-cephfs-node-co-staging-k8s
	key: somkey
	caps: [mds] allow rw
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs data=cephfs.co-staging-k8s_fs.data
client.csi-cephfs-provisioner-co-staging-k8s
	key: somkey
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs metadata=cephfs.co-staging-k8s_fs.meta
```

kubectl describe on pvc
```
$ ~ > kubectl describe pvc test-cephfs 
Name:          test-cephfs
Namespace:     default
StorageClass:  rook-cephfs
Status:        Pending
Volume:        
Labels:        cattle.io/creator=norman
Annotations:   field.cattle.io/creatorId: u-qgg6x4f6xn
               volume.beta.kubernetes.io/storage-provisioner: rook-ceph-external.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    test-cephfs-87d6c4f65-7wp9m
Events:
  Type     Reason                Age                    From                                                                                                                      Message
  ----     ------                ----                   ----                                                                                                                      -------
  Warning  ProvisioningFailed    58m (x14 over 77m)     rook-ceph-external.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-b55f5fc54-jwwrs_006741d9-8a23-442a-9c04-8749b082362f  failed to provision volume with StorageClass "rook-cephfs": rpc error: code = Internal desc = rados: ret=-1, Operation not permitted
  Normal   Provisioning          3m54s (x29 over 77m)   rook-ceph-external.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-b55f5fc54-jwwrs_006741d9-8a23-442a-9c04-8749b082362f  External provisioner is provisioning volume for claim "default/test-cephfs"
  Normal   ExternalProvisioning  2m16s (x303 over 77m)  persistentvolume-controller                                                                                               waiting for a volume to be created, either by external provisioner "rook-ceph-external.cephfs.csi.ceph.com" or manually created by system administrator
```

Storageclass:
```
$ ~ > kubectl get storageclasses.storage.k8s.io rook-cephfs -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2021-11-22T10:59:49Z"
  managedFields:
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:allowVolumeExpansion: {}
      f:parameters:
        .: {}
        f:clusterID: {}
        f:csi.storage.k8s.io/controller-expand-secret-name: {}
        f:csi.storage.k8s.io/controller-expand-secret-namespace: {}
        f:csi.storage.k8s.io/node-stage-secret-name: {}
        f:csi.storage.k8s.io/node-stage-secret-namespace: {}
        f:csi.storage.k8s.io/provisioner-secret-name: {}
        f:csi.storage.k8s.io/provisioner-secret-namespace: {}
        f:fsName: {}
        f:pool: {}
      f:provisioner: {}
      f:reclaimPolicy: {}
      f:volumeBindingMode: {}
    manager: HashiCorp
    operation: Update
    time: "2021-11-22T10:59:49Z"
  name: rook-cephfs
  resourceVersion: "8123725"
  uid: 0952fd2a-6315-443c-af7d-f10f01315e0b
parameters:
  clusterID: rook-ceph-external
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph-external
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph-external
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph-external
  fsName: co-staging-k8s_fs
  pool: cephfs.co-staging-k8s_fs.data
provisioner: rook-ceph-external.cephfs.csi.ceph.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian Bullseye
* Kernel (e.g. `uname -a`): 5.14.0-1-amd64 
* Rook version (use `rook version` inside of a Rook Pod): 2.7.8
* CSI Versions:
k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.0
quay.io/cephcsi/cephcsi:v3.4.0
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.6
* Kubernetes version (use `kubectl version`): v1.20.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher/Terraform managed K8s cluster

**Comment by leseb** [comment]
@CO-lhagman double-checking, the pools for data and metadata are correct right?
@ajarr anything wrong in the way we set the permissions?

**Comment by ajarr** [comment]
> @CO-lhagman double-checking, the pools for data and metadata are correct right? 
> @ajarr anything wrong in the way we set the permissions?

My guess is that the application tags weren't properly set on the file system's data and metadata pools . Can you please check the following,

```
# ceph osd pool application get <metadata-pool-name> cephfs
```
Output should be,
```
{
    "metadata": "<filesystem-name>"
}
```
If not, then execute the following,
```
ceph osd pool application set <metadata-pool-name> cephfs metadata <filesystem-name>
```

Similarly,
```
# ceph osd pool application get <data-pool-name> cephfs
```
Output should be,
```
{
    "data": "<filesystem-name>"
}
```
If not, then execute the following,
```
ceph osd pool application set <data-pool-name> cephfs data <filesystem-name>
```
@kotreshhr anything else comes to mind?

> 
> Thanks!

**Comment by CO-lhagman** [comment]
> @CO-lhagman double-checking, the pools for data and metadata are correct right?
```
$ ~ > ceph osd pool ls
device_health_metrics
co-staging-k8s_rbd
cephfs.co-staging-k8s_fs.meta
cephfs.co-staging-k8s_fs.data
```
Pool names seem to be correct.

About the applications:
```
$ ~ > ceph osd pool application get cephfs.co-staging-k8s_fs.meta cephfs
{
    "metadata": "co-staging-k8s_fs"
}
$ ~ > ceph osd pool application get cephfs.co-staging-k8s_fs.data cephfs
{
    "data": "co-staging-k8s_fs"
}
```
The pools were created by running `ceph fs volume create co-staging-k8s_fs`

**Comment by kotreshhr** [comment]
> @kotreshhr anything else comes to mind?

@CO-lhagman  Could you please create the subvolume group and subvolume manually with the `client.csi-cephfs-provisioner-co-staging-k8s` user on ceph cluster and check if it's successful ?

**Comment by CO-lhagman** [comment]
@kotreshhr I'm not quite sure how to do this, I haven't used cephfs a lot.
My guess is:
create a ceph.client.csi-cephfs-provisioner-co-staging-k8s.keyring file with the content:
```
[client.csi-cephfs-provisioner-co-staging-k8s]
	key = somekey
	caps mgr = "allow rw"
	caps mon = "allow r"
	caps osd = "allow rw tag cephfs metadata=cephfs.co-staging-k8s_fs.meta"
```
(somekey is a real key of course)
and the execute the following:
`ceph --keyring ceph.client.csi-cephfs-provisioner-co-staging-k8s.keyring fs subvolume create co-staging-k8s_fs testgroup`

If that is indeed the case, I receive a `[errno 13] error connecting to the cluster`
Verbose doesn't show any useful output either.

**Comment by kotreshhr** [comment]
@CO-lhagman 

You don't need to create a keyring as it should be done already by the steps you followed for setup. I am trying to debug where it's failing.  You can confim the same by following cmd.

```
ceph auth get client.csi-cephfs-provisioner-co-staging-k8s
```

You should do something like below.

```
ceph fs subvolumegroup create a group_1  --id csi-cephfs-provisioner-co-staging-k8s --keyring <keyring location>
ceph fs subvolume create a sub_1 --group-name=group_1 --id csi-cephfs-provisioner-co-staging-k8s --keyring <keyring location>
```
NOTE: You can ignore the keyring argument if the it's been added to default location.

**Comment by CO-lhagman** [comment]
@kotreshhr 

Thank you very much for your help, I was missing the --id parameter.
I was able to create the subvolumegroup and subvolume without errors:
![image](https://user-images.githubusercontent.com/69451843/144224647-22f0d11a-cea3-4499-845f-6e7c948b713f.png)

**Comment by kotreshhr** [comment]
@CO-lhagman CSI creates a rados object to store metadata. Probably it's failing there. Please try below and confirm.

```
rados create test -p <metadata-pool-name> --id=csi-cephfs-provisioner-co-staging-k8s --key=<key-of-the-user>  --namespace=csi
```

You can fetch the metadata-pool name the output of 
```
ceph fs ls
```

**Comment by CO-lhagman** [comment]
@kotreshhr Yup that seems to be the issue:
```
$ ~ > rados create test -p cephfs.co-staging-k8s_fs.meta --id=csi-cephfs-provisioner-co-staging-k8s --key=somekey  --namespace=csi
error creating cephfs.co-staging-k8s_fs.meta/test: (1) Operation not permitted
```

**Comment by kotreshhr** [comment]
Not sure why it's failing even with metadata access. Could you match the provisioner's caps to [1] and check?

[1] https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs

**Comment by CO-lhagman** [comment]
Permissions have been changed to whats listed in [1]:
```
[client.csi-cephfs-provisioner-co-staging-k8s]
	key = somekey
	caps mgr = "allow rw"
	caps mon = "allow r"
	caps osd = "allow rw tag cephfs metadata=*"
```
and I can successfully create the rados object

**Comment by kotreshhr** [comment]
Could you try PVC creation now ?

**Comment by CO-lhagman** [comment]
I can successfully create the PVC now and I see the subvolume get created in ceph. I cannot bind it to a deployment yet, I still get a permission error with that.

**Comment by kotreshhr** [comment]
> I can successfully create the PVC now and I see the subvolume get created in ceph. I cannot bind it to a deployment yet, I still get a permission error with that.

That's because the node caps are restricted, could you try matching the caps of `client.csi-cephfs-node-co-staging-k8s` to match the [1]

[1] https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs

**Comment by CO-lhagman** [comment]
@kotreshhr 
> That's because the node caps are restricted, could you try matching the caps of client.csi-cephfs-node-co-staging-k8s to match the [1] ?
yes, that works now. So we know it is related to the cap restrictions.

**Comment by parth-gr** [comment]
@kotreshhr Thanks for finding the actual issue, the restriction of permission for specific pools,

I see there is a problem with restricting caps permission,
So OSD cap doesn't work for a specific metadata pool `caps osd = "allow rw tag cephfs metadata=cephfs.co-staging-k8s_fs.meta" `  Pvc can not bind to the deployment, 
so its architecture is intended to behave like this, or we can do some workaround to have this working?
Or I guess creating CSI secret might be the issue depicted here, https://github.com/rook/rook/issues/9192?
 
@CO-lhagman can you confirm if the restriction works fine with the RBD provisioner.

**Comment by CO-lhagman** [comment]
> @CO-lhagman can you confirm if the restriction works fine with the RBD provisioner. 
@parth-gr I can confirm it works without issues with RBD Images

**Comment by CO-lhagman** [comment]
> Or I guess creating CSI secret might be the issue depicted here, #9192?

I changed the names to match the created ceph users as a workaround, that Issue should not be related to this issue

**Comment by kotreshhr** [comment]
> @kotreshhr
> 
> > That's because the node caps are restricted, could you try matching the caps of client.csi-cephfs-node-co-staging-k8s to match the [1] ?
> 
> yes, that works now. So we know it is related to the cap restrictions.

@CO-lhagman @parth-gr Sorry I could not get to this issue as I was busy with other things.
Yes, the issue is with caps restriction.  The caps setting for the users were incorrect w.r.t osd application tag.
The osd application tag takes the key value pair which `'data|metadata'=<filesystem-name>` not `data|metadata=<pool-name>`

Original user caps in your case
```
client.csi-cephfs-node-co-staging-k8s
	key: somkey
	caps: [mds] allow rw
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs data=cephfs.co-staging-k8s_fs.data
client.csi-cephfs-provisioner-co-staging-k8s
	key: somkey
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs metadata=cephfs.co-staging-k8s_fs.meta

```
Change above to below caps
```
client.csi-cephfs-node-co-staging-k8s
	key: somkey
	caps: [mds] allow rw
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs data=co-staging-k8s_fs
client.csi-cephfs-provisioner-co-staging-k8s
	key: somkey
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs metadata=co-staging-k8s_fs
```

This should work. Please validate.

**Comment by CO-lhagman** [comment]
@kotreshhr This does indeed work! Thank you very much for your support, I will create a PR.

**Comment by parth-gr** [comment]
@kotreshhr thanks for finding it.

> @kotreshhr This does indeed work! Thank you very much for your support, I will create a PR.

@CO-lhagman sure
