### ISSUE TITLE
Error creating rook-ceph-osd pods: MKNOD capability is not added

### ISSUE THREAD

**Issue by dominikhiebler** [rook/rook#9234]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Updating rook-ceph-operator to version 1.7.8 leads to security constraint exception in rook-ceph-osd pods. Version 1.7.7 is working fine.

**Expected behavior:**
The rook-ceph-osd pods should be created. 

**How to reproduce it (minimal and precise):**
Update rook-ceph-operator to version 1.7.8

**File(s) to submit**:
`Error creating: pods "rook-ceph-osd-1-59d9fb6f54-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[6]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, spec.initContainers[0].securityContext.capabilities.add: Invalid value: "MKNOD": capability may not be added, spec.initContainers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, spec.initContainers[2].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, spec.initContainers[3].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000800000, 1000809999], spec.initContainers[3].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, spec.containers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000800000, 1000809999], spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount, provider "rook-ceph-csi": Forbidden: not usable by user or serviceaccount]`

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): 1.7.8
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.6
* Kubernetes version (use `kubectl version`): v1.21.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OpenShift

**Comment by leseb** [comment]
There is a WIP here to fix this: https://github.com/rook/rook/pull/9175, I'll send a small PR to address that particular problem shortly.
