### ISSUE TITLE
minikube should use RBAC

### ISSUE THREAD

**Issue by jbw976** [rook/rook#925]
the handy `./tests/scripts/minikube.sh` script does not specify that minikube should use RBAC when it starts up minikube: https://github.com/rook/rook/blob/master/tests/scripts/minikube.sh#L58

It's useful to always be running with RBAC on so that we can catch any permissions regressions, new required permissions for new code, etc.

I thought this would be a simple fix to just pass `--extra-config=apiserver.Authorization.Mode=RBAC` as per https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md#examples.  This seems to work OK for Rook, but `kube-dns` is in a crash loop:
```
> kubectl -n kube-system get pod -l k8s-app=kube-dns
NAME                       READY     STATUS             RESTARTS   AGE
kube-dns-910330662-ccc9m   2/3       CrashLoopBackOff   53         2h
```

kubedns logs show that it's missing RBAC permissions:
```
> kubectl -n kube-system logs -lk8s-app=kube-dns -c kubedns
E0819 00:25:59.762761       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: User "system:serviceaccount:kube-system:default" cannot list endpoints at the cluster scope. (get endpoints)
E0819 00:25:59.762857       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: User "system:serviceaccount:kube-system:default" cannot list services at the cluster scope. (get services)
E0819 00:25:59.763025       1 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ConfigMap: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system". (get configmaps)
```

**Comment by blingwang** [comment]
Some workaround mentioned here: https://github.com/kubernetes/minikube/issues/1734

**Comment by bassam** [comment]
is this still the case? its not realistic to run with RBAC anymore.

**Comment by jbw976** [comment]
Do you mean it's unrealistic to run without RBAC?  Using minikube without RBAC is letting RBAC permissions issues slip through the cracks until a dev runs on another environment that uses RBAC.  It would be great to fix this so we are always running with RBAC on.

**Comment by jbw976** [comment]
Is this just working now?  Was there an update to minikube?  Running the integration tests today locally with minikube showed signs that RBAC was in place (the operator didn't have permissions to get roles in a namespace, so I had to update the operator's RBAC config).

I'm running minikube `v0.22.2`

**Comment by dangula** [comment]
i am running minikube v0.22.3 with RBAC enabled and integration tests are passing, even though the kube-dns pod going into CrashLoopBackOff.  Following the workaround mentioned  in  kubernetes/minikube#1734 is fixing the kube-dns crash loop.
