### ISSUE TITLE
after one node is disconnected and reconnected postgres can't lock data dir

### ISSUE THREAD

**Issue by hezise** [rook/rook#9254]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

sometimes when a node is disconnected and then reconnected one of the postgres pods fails because it can't lock data dir.
I saw an issue that a user asked postgres for a flag to disable the lock
[](https://github.com/sorintlab/stolon/issues/814
)

**File(s) to submit**:
I don't know which logs you need

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* Kernel (e.g. `uname -a`):
* Linux node1 4.15.0-162-generic #170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration: VW
* Rook version (use `rook version` inside of a Rook Pod):
* rook: v1.5.8
go: go1.13.8

* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 15.2.9 (357616cbf726abb779ca75a551e8d02568e15b17) octopus (stable)

* Kubernetes version (use `kubectl version`):
* Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* kubespray 2.15
* 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
HEALTH_OK

**Comment by leseb** [comment]
How many storage nodes do you have?

**Comment by hezise** [comment]
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ $.Values.sharedstoragename }}
   namespace: default
   annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  clusterID: rook-ceph
  blockPool: pool-shared
  fsName: shared-storage

**Comment by hezise** [comment]
I missed your first question.
we have 3 nodes and on each node we have an osd

**Comment by hezise** [comment]
Hi @leseb ,
Any idea?

**Comment by leseb** [comment]
If you have 3 OSDs and replica 3, losing one OSD should be possible and IO should not be stale. Can you share more logs from the postgres error lock? Also, is the mount point stale when you restart? Have you tried execing into the container and see if mountpoint is healthy? Thanks

**Comment by hezise** [comment]
Hi @leseb ,
sorry for my late response.
unfortunately the cluster was removed. currently I don't have a reproduction. once I have one, I'll update
