### ISSUE TITLE
realm controller failed to reconcile 

### ISSUE THREAD

**Issue by olivierbouffet** [rook/rook#9256]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Hello,

When I create a realm , after a restart of the operator the reconcile failed .

```
2021-11-25 11:34:24.675639 E | ceph-object-realm-controller: failed to reconcile: failed to create keys for realm: failed to save rgw secrets: secrets "realm-1-keys" already exists
```

**Expected behavior:**
It should not fail because the secret is already set.

**How to reproduce it (minimal and precise):**
create a realm : 
```
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: realm-1
  namespace: rook-ceph
```

realm is successfully created 

restart the operator 
```
2021-11-25 11:34:24.675639 E | ceph-object-realm-controller: failed to reconcile: failed to create keys for realm: failed to save rgw secrets: secrets "realm-1-keys" already exists
```

```
kubectl -- -n rook-ceph get cephobjectrealm realm-1 -oyaml
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ceph.rook.io/v1","kind":"CephObjectRealm","metadata":{"annotations":{},"name":"realm-1","namespace":"rook-ceph"}}
  creationTimestamp: "2021-11-25T09:42:37Z"
  generation: 1
  name: realm-1
  namespace: rook-ceph
  resourceVersion: "12771"
  uid: a5fad16e-2013-453e-8d50-3da5cee260b4
status:
  phase: ReconcileFailed
```

**Environment**: 
* OS (e.g. from /etc/os-release): debian 10  
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.7.8
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.6
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by alimaredia** [comment]
unstale
