### ISSUE TITLE
Cannot unmount /oldroot 

### ISSUE THREAD

**Issue by leiw324** [rook/rook#9265]
Hello,

If a pod mounted rook-ceph by PVC, shutdown worker node  that will one worker node will occurred this issue:

![image](https://user-images.githubusercontent.com/33790160/143683510-9bcfdf35-51e8-4a0c-9176-892bdaa09f23.png)

I used three worker to create rook-ceph:

Centos version:
CentOS Linux release 7.8.2003 (Core)

k8s version:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

Three worker nodes vdb1 information:
![image](https://user-images.githubusercontent.com/33790160/143683598-0916b155-dc67-4eac-b6f1-ed409f2b4d35.png)
![image](https://user-images.githubusercontent.com/33790160/143683611-e4b4386b-f4f0-4b04-842c-47851438835c.png)
![image](https://user-images.githubusercontent.com/33790160/143683629-5f7a6c9c-6b8f-423c-8c2e-b9d16123950b.png)

git clone https://github.com/rook/rook.git

https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/crds.yaml

cd rook/cluster/examples/kubernetes/ceph/
kubectl create -f common.yaml 
kubectl create -f operator.yaml
kubectl create -f cluster.yaml
![image](https://user-images.githubusercontent.com/33790160/143683792-1c37eb24-fbf5-4ce4-b1ca-fc0004a7bbb3.png)
![image](https://user-images.githubusercontent.com/33790160/143683798-83783d69-d04a-427b-a565-e908825a0615.png)

kubectl create -f rook/cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml 
![image](https://user-images.githubusercontent.com/33790160/143683821-76d500d6-16cb-4f49-ad2b-597f2231671f.png)

cephfs-filesystems.yam:
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: myfs # the name should be the same as the one in storageclass yaml
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - replicated:
        size: 3
  preservePoolsOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true

PVC:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs

**Comment by travisn** [comment]
@leiw324 If the node is shutdown, are you saying those mounts still exist after the node starts up again? Or the clean shutdown is not happening? Please also review the [CSI troubleshooting guide](https://rook.github.io/docs/rook/v1.7/ceph-csi-troubleshooting.html) for possible solutions.

**Comment by jav333** [comment]
Hello @travisn ,

I remember you, because I was asked this question．

I just shutdown worker nodes that will happen this issue, I don't have to wait 10 mins or more, and then force shutdown VM,  so I don't know "those mounts still exist after the node starts up again"

After force shutdown VM will not happen again.

Thanks

**Comment by jav333** [comment]
Hello,

You guys no this issue ?

Thanks

**Comment by leiw324** [comment]
Hello?

**Comment by travisn** [comment]
Sorry I don't really understand the question. If you are shutting down a node it is recommended to drain the pods so they can unmount properly. What are the repro steps to get the volume that is not unmounted?

**Comment by jav333** [comment]
Hi @travisn ,

Yes, I shutting down three worker nodes that will happen this issue, but not the same worker node, this is random...

Sorry, I don't understand the deeper concept of rook-ceph.

Thanks

**Comment by jav333** [comment]
And my testing env is cockpit.

**Comment by travisn** [comment]
@jav333 Do you have the pod disruption budgets enabled [here](https://github.com/rook/rook/blob/release-1.7/cluster/examples/kubernetes/ceph/cluster.yaml#L238-L241) for rook? The PDBs will ensure nodes are allowed to be drained so that it doesn't affect the health of the cluster. For more details about the PDB behavior, see the [PDB design doc](https://github.com/rook/rook/blob/master/design/ceph/ceph-managed-disruptionbudgets.md).

**Comment by jav333** [comment]
Hi @travisn ,

I don't have to enable PDB, so you guys need enable it for this issue?

Thanks

**Comment by travisn** [comment]
@jav333 If I understand correctly, your issue is that volumes hang randomly when workers are shut down? If that is the case, then you need to shut down workers in a way that Ceph can handle the failures. The PDBs will help ensure Ceph can stay healthy in this case.

**Comment by leiw324** [comment]
@travisn , oh, the disruptionManagement is default enabled, so I think created cluster also enabled.

What I need to do now?

Thanks

**Comment by travisn** [comment]
> @jav333 If I understand correctly, your issue is that volumes hang randomly when workers are shut down?

@leiw324 Can you confirm this is your issue? 
Can you say more about why the nodes are being shutdown? Are the nodes being drained according to the PDBs?

**Comment by jav333** [comment]
@travisn ,

Because I will shutdown all nodes before going to bed.

How to check PDBs, sorry I am new on PDBs.

Thanks

**Comment by travisn** [comment]
If you're shutting down all the nodes, you could first scale down all your application pods, then stop the nodes.

**Comment by jav333** [comment]
@travisn ,

Any guideline about handling this issue?

Thanks

**Comment by travisn** [comment]
If you're shutting down the nodes, the guideline is to stop the applications before shutting down the nodes. Otherwise, the applications may hang on the volumes during node shutdown.

**Comment by jav333** [comment]
@travisn ,

After scale all pods to 0, the worker nodes successfully shutdown !!! this problem is around one year .... 

Thanks!!!

**Comment by travisn** [comment]
@jav333 Sounds good, then I'll go ahead and close this issue.

**Comment by leiw324** [comment]
Thanks!!
