### ISSUE TITLE
Change operator to specify LVM VG for OSD

### ISSUE THREAD

**Issue by briantopping** [rook/rook#9267]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Small / hyperconverged environments often don't have an extensive storage device selection to install on. The storage devices that do exist often have to allocate to system requirements such as boot, root, var and other various volumes alongside usages such as Ceph OSD. This feature request attempts to recognize the pros and cons of Rook being able to allocate OSD space within existing LVM PVs and hopefully gain a following.

**What is use case behind this feature:**
One thing that is obvious from the outset is colocating OSD storage on system volumes is far from ideal. Resource contention issues will reduce performance. But this contention is also present when running Ceph from separate partitions of the same devices. In a node with limited resources, overloading devices may be unavoidable without prohibitive expense or wonky disk layouts.

Consider for instance a 1U twin configuration where each node has 4x SATA drives, what is the best configuration? Some configurations come readily to mind:
* One device for system storage, three devices for Ceph
* Two mirrored devices (ie `mdadm`) for system storage and two devices for Ceph
* Share all four devices by both system storage and Ceph using partitions on each device

The first configuration is quickly dismissed since the there is no redundancy for the system device. Recovery from a failed device requires rebuilding the device from source artifacts instead of replacing the device and letting replication restore it. The mirrored configuration means a failed system device can be easily replaced with no downtime. Spreading the system device over partitions of all four devices means we can (sometimes) lose up to two drives and recover with zero downtime, but at the cost of device contention between Ceph and system requests.

Ignoring the non-redundant first option, the primary difference between the remaining two configurations is the disk utilization potential – it's unlikely to use all the space in the mirrored system volumes. Worse, the unused space in the system storage is doubled in the mirror. 

In our experience, striping and mirroring (RAID10) the system storage across tuned partitions of all four disks is ideal. Common system installers (Ubiquity, Anaconda) do a good job of setting this up and can be declaratively configured at scale. Ubiquity tends to install with mdadm underneath the LVM PV, but it's also possible for recent versions of LVM to manage the mirror and striping of an LV with PVs that it has available. Ubiquity would use `mdadm` for the boot volumes, but direct PVs for the primary VG. This would entail [conversion of the linear devices](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/logical_volume_manager_administration/linear-to-raid) after installation is complete.

In a converged environment that must trade optimal datapaths for optimal device utilization, the system VG could also be used by Rook for OSD allocation instead of insisting on a private VG. As best I can tell, Bluestore on LVM only depends on the labels on the volume, this capability does not change. 

Thus, instead of two separate VGs (composed of partitions from each device), the monolithic VG aggregates all the space. Without this aggregation, installers must guess at how large their system VG might get and set their partitions accordingly. A bad guess leads to wasted space or an expensive process to out, down and remove the OSD+partition, change the system partition/VG size and finally recreate the OSD. In a situation where a single VG is used, this can all be done without modifying the partition map, a far more dangerous procedure than working with LVM LV commands. 

Another advantage to a unified VG is better support for systems like TopoLVM, which can easily allocate from the aggregated VG. In situations where ports are less of a constraint than capital, it is far easier to grow a system with more drives when they are simply added to the VG.

These primarily appear to be changes to the operator since the `BlockPath` abstracts away the VG that a device exists on.

**Comment by briantopping** [comment]
In thinking about it some, it seems like a great first step on this would be removing the 1:1 relationship between VG and LV, changing it to a single VG per host. Question for the great minds on the project: What are the architectural constraints to such a change?

**Comment by travisn** [comment]
Have you considered using TopoLVM as the backing provider for the OSDs? If you use the [cluster-on-pvc](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml) as the base cluster definition and modify to use the TopoLVM storage class with the desired VG, the OSDs could be provisioned with an LV. 

Since TopoLVM can be used as the backing store via the cluster-on-pvc approach, we haven't put effort into supporting OSDs on LVs with the non-pvc approach.

**Comment by briantopping** [comment]
Ah, got it! That would solve for all the requirements, just never thought about layering Rook on top of TopoLVM. Thanks!
