### ISSUE TITLE
The existing variable is the same as the package name in pkg\operator\ceph\file\filesystem.go

### ISSUE THREAD

**Issue by fengjiankui121** [rook/rook#9275]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**v
variables and package names should not be the same
**How to reproduce it (minimal and precise):**

The variable pool and the package name are the same, as shown below：

import (
"github.com/rook/rook/pkg/operator/ceph/pool"
)
...
...
for i, pool := range spec.DataPools {
......
......
}

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by parth-gr** [comment]
@fengjiankui121, I see it is not affecting the functionality for now, as this is done on different functions.

But it will be good to have the alias for the package name during import like, 
 `cephpool "github.com/rook/rook/pkg/operator/ceph/pool" ` something like this.
 
 Would you like to open a PR for that?
 Thanks!

**Comment by fengjiankui121** [comment]
Yes, I would like @parth-gr
