### ISSUE TITLE
Need to be able to support mount options with helm chart

### ISSUE THREAD

**Issue by TomHellier** [rook/rook#9286]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
It should be possible to specify the csi mount options using the ceph cluster helm chart.

**What is use case behind this feature:**
I am mounting a filesystem, and would like it to be mounted with `_netdev`, it looks like this feature should be supported as it is currently supported by the [ceph-csi-cephfs](https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-cephfs/templates/storageclass.yaml#L56-L61) and [ceph-csi-rbd](https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-rbd/templates/storageclass.yaml#L77-L82) helm charts.

**Environment**:
helm

**Comment by Madhu-1** [comment]
@TomHellier _netdev is added by default for both cephfs and rbd in cephcsi.

**Comment by TomHellier** [comment]
@Madhu-1  thanks, what about [the debug option](https://github.com/rook/rook/blob/master/deploy/examples/csi/cephfs/storageclass.yaml#L34-L36), its advertised as being available so I suspect it should be made available in the charts.

**Comment by Madhu-1** [comment]
its not enabled by default. you PR should helps in added that

**Comment by TomHellier** [comment]
@Madhu-1  I am getting problems with my filesystem just hanging completely, seems to happen once a week and requires a full hard reboot of the node (which appears to have been evicted)

I'd like to try this option
https://ceph.io/en/news/blog/2020/automatic-cephfs-recovery-after-blacklisting/

**Comment by Madhu-1** [comment]
@TomHellier i think you need to look at kernelmount options https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-cephfs/templates/storageclass.yaml#L23-L28
