### ISSUE TITLE
CephFS dataPools unordered and unnamed

### ISSUE THREAD

**Issue by degorenko** [rook/rook#9295]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Current implementation of CephFilesystem spec allows to specify multiple dataPools as an array list, but they don't have strong names and created based on index in array. Such behaviour doesn't allow to use static names or relay on already created names, since any newly added dataPool should be created after manual removal of previously added pool or added to the end of list. As an option we can add dataPools based on predefined pool name. Thus, usage of such pools is predictable and storage classes can be created with using static pool name.

**What is use case behind this feature:**
When env has a lot of applications, which are using CephFS, predictable pool names allow strong and reliable usage of PV/Storage classes. Also, changing number of pools specified in spec will not lead to additional manual actions like pool removal, crush map update and so on. This can be done manually in any time if case of need, regardless of spec changes.

**Environment**:

**Comment by travisn** [comment]
This was resolved by #9296 and will be included in v1.8.1
