### ISSUE TITLE
MDS not expose on hostport

### ISSUE THREAD

**Issue by sauber** [rook/rook#9297]
**Is this a bug report or feature request?**

* Bug Report

**Bug Report**

**Expected behavior:**

$ kubectl -n rook-ceph get deploy rook-ceph-mon-a -o json | jq .spec.template.spec.containers\[0\].ports
[
  {
    "containerPort": 6789,
    "hostPort": 6789,
    "name": "tcp-msgr1",
    "protocol": "TCP"
  }
]
$ kubectl -n rook-ceph get deploy rook-ceph-mds-myfs-a -o json | jq .spec.template.spec.containers\[0\].ports
[
  {
    "containerPort": 6800,
    "hostPort": 6800,
    "name": "tcp-mds-myfs-a",
    "protocol": "TCP"
  }
]

**Deviation from expected behavior:**

$ kubectl -n rook-ceph get deploy rook-ceph-mon-a -o json | jq .spec.template.spec.containers\[0\].ports
[
  {
    "containerPort": 6789,
    "hostPort": 6789,
    "name": "tcp-msgr1",
    "protocol": "TCP"
  }
]
$ kubectl -n rook-ceph get deploy rook-ceph-mds-myfs-a -o json | jq .spec.template.spec.containers\[0\].ports
null

**How to reproduce it (minimal and precise):**

Bring up kubernetes clusters with disks. Then:

$ git clone https://github.com/rook/rook.git
$ cd rook
$ git checkout release-1.7
$ cd cluster/examples/kubernetes/ceph
$ kubectl apply -f crds.yaml -f common.yaml -f operator.yaml
$ kubectl -n rook-ceph rollout status deploy/rook-ceph-operator
$ cp cluster.yaml demo.yaml
$ sed -i 's/#provider: host/provider: host/' demo.yaml
$ kubectl apply -f demo.yaml -f toolbox.yaml -f filesystem.yaml
$ sed '/created filesystem "myfs"/q' <(kubectl -n rook-ceph logs -f deploy/rook-ceph-operator)

**Environment**:
* OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
* Kernel (e.g. `uname -a`): Linux rook-m01 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: VMware Virtual Platform
* Rook version (use `rook version` inside of a Rook Pod): 
2021-12-02 14:42:27.321629 I | op-flags: failed to set flag "logtostderr". no such flag -logtostderr
rook: v1.7.8
go: go1.16.7
* Storage backend version (e.g. for ceph do `ceph -v`): *ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

**Comment by BlaineEXE** [comment]
@leseb is this behavior expected? For external clusters, do we expect that users will create a service for the MDS or something?

**Comment by leseb** [comment]
We don't really support creating resources when the external mode is turned on. It is somewhat possible but the implementation has holes I think.
When external mode is enabled, it is more a producer/consumer relationship and rook does not create resources.
