### ISSUE TITLE
Cluster TPR/CRD should support update so storage can be added and removed dynamically

### ISSUE THREAD

**Issue by jbw976** [rook/rook#934]
Updating a Rook Cluster TPR/CRD is not currently implemented:
https://github.com/rook/rook/blob/9d855e5bfe671ffa9328de3042cc416b58356033/pkg/operator/cluster/controller.go#L143

The Cluster TPR/CRD should be able to be updated over time so that more storage can be added to the cluster dynamically.

**Comment by jbw976** [comment]
Clarification from @travisn:
> Currently if you add a new node, Rook will automatically add new OSDs for that node as long as you have set useAllNodes in the cluster yaml. But if you are declaring specific nodes and devices, we don't yet add the OSDs.

**Comment by travisn** [comment]
how about if we track this with #1101.
