### ISSUE TITLE
rook-ceph-operator 's STATUS is CrashLoopBackOff

### ISSUE THREAD

**Issue by sunmiao0301** [rook/rook#9366]
**Is this a bug report or feature request?**
* Bug Report

Yes I think so

**Deviation from expected behavior:**

[root@ceph57 ceph]# kubectl -n rook-ceph get pod
NAME                                  READY   STATUS             RESTARTS          AGE
rook-ceph-operator-649f6f47c8-vsjcd   0/1     CrashLoopBackOff   284 (4m41s ago)   23h

**Expected behavior:**

[root@ceph57 ceph]# kubectl -n rook-ceph get pod
NAME                                  READY   STATUS             RESTARTS          AGE
rook-ceph-operator-649f6f47c8-vsjcd   1/1   Running   284 (4m41s ago)   23h

**How to reproduce it (minimal and precise):**

**[root@ceph57 ~]# mkdir summiao**

**[root@ceph57 ~]# cd summiao**

**[root@ceph57 summiao]# [root@ceph57 summiao]# git clone --single-branch --branch v1.7.9 git://github.com/rook/rook.git**

（I choosen Rook Ceph v1.7 for my 3 machines - 1 master as well as worker + 2 workers）

**[root@ceph57 summiao]# cd rook/cluster/examples/kubernetes/ceph**

**[root@ceph57 ceph]# kubectl create -f crds.yaml -f common.yaml -f operator.yaml**

PS：there was a warnings happening when I execute the command just above.

but I didn't find any solution about this...

Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

**[root@ceph57 ceph]# kubectl create -f cluster.yaml**

**[root@ceph57 ceph]# kubectl -n rook-ceph get pod** 

NAME                                  READY   STATUS             RESTARTS         AGE

rook-ceph-operator-649f6f47c8-vsjcd   0/1     CrashLoopBackOff   284 (3m6s ago)   23h

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* CentOS Linux release 7.9.2009 (Core)
* Kernel (e.g. `uname -a`):
* Linux ceph57 5.15.6-1.el7.elrepo.x86_64 #1 SMP Tue Nov 30 12:36:34 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* I tried to install Rook v1.7
* Storage backend version (e.g. for ceph do `ceph -v`):
* havent install successfully
* Kubernetes version (use `kubectl version`):
* Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
* Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by travisn** [comment]
@sunmiao0301 To troubleshoot this, we will need to see the reason for the operator failure. Either `kubectl describe` or `kubectl logs` of the operator log should show the failure details.

**Comment by sunmiao0301** [comment]
Thanks for your reply, actually, I had solved this problem, by:

[root@master ceph]# ↓
`rm -f /common.yaml`
`kubectl create -f common.yaml`
`kubectl apply -f common.yaml`

It looks weird but effective

**Comment by travisn** [comment]
Was it an upgraded cluster? In any case, I would expect `kubectl apply` would be sufficient instead of also creating. Shall we close this issue?

**Comment by sunmiao0301** [comment]
I don't remember about it because I had deleted them all to deploy again. 
Thank you anyway!
feel free to close it.
