### ISSUE TITLE
Upgrade to Ceph v16.2.7 may need to set mon_mds_skip_sanity

### ISSUE THREAD

**Issue by travisn** [rook/rook#9373]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In the Ceph thread [here](https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/7KSPSUE4VO274H5XQYNFCT7HKWT75BCY/), the recommendation is to set the following before the upgrade:
```
     ceph config set mon mon_mds_skip_sanity 1
```
Then after the upgrade remove the setting:
```
    ceph config rm mon mon_mds_skip_sanity
```

If this is not done, the mons may crash and these settings would need to be added to the ceph.conf overrides for the mon to recover at pod restart. 

In Rook CI upgrade testing, we at least have not seen this issue when upgrading from Octopus to 16.2.7. 

@batrick From which version of Ceph would you expect this to be necessary? Does it only affect prior versions of Pacific?

**Expected behavior:**
Rook should automate the upgrade if needed

**Comment by travisn** [comment]
I'm not able to repro this issue with the mons crashing during upgrade in several attempts with the follow upgrades of the Ceph version with the latest Rook:
- 15.2.15 --> 16.2.5 --> 16.2.7
- 16.2.5 --> 16.2.7

I'd still like to know better what cephfs clusters could potentially hit this issue so we know either to include these steps in the upgrade guide, or to automate it in rook.

**Comment by batrick** [comment]
> @batrick From which version of Ceph would you expect this to be necessary? Does it only affect prior versions of Pacific?

v16.2.4 and older.

**Comment by batrick** [comment]
How many monitors does the rook cluster have? You need at least 2. I would try upgrades from v16.2.4 to v16.2.7 to reproduce.

**Comment by travisn** [comment]
With three mons on 16.2.4, upgrading to v16.2.7 works for me. The mons were all on the same node with minikube, but not sure that's a factor.

There was already a [Slack report of a rook user hitting this](https://rook-io.slack.com/archives/C46Q5UC05/p1639183554216100) in their upgrade to 16.2.7, so in any case we need to automate it.

**Comment by travisn** [comment]
@batrick To clarify, would the mon_mds_skip_sanity need to be set during upgrades if upgrading in the future from any previous Ceph to any future Pacific version greater than or equal to v16.2.7? For example, in the future what if someone upgrades directly from v16.2.4 to v16.2.9? Should Rook just always set the flag during the ceph upgrade to be safe?
