### ISSUE TITLE
The Ceph cluster does not have a POD for OSD

### ISSUE THREAD

**Issue by yinmin2020** [rook/rook#9379]
**Is this a bug report or feature request?**
* Bug Report
When Ceph is deployed in RoOK mode, the cluster automatically adds data disks on nodes to initialize the OSD node. However, the POD of the OSD node is not generated. Disks on the host host have been detected by the cluster and successfully initialized to the LVM state, but the OSD state is still 0
* Crashing pod(s) logs, if necessary
![image](https://user-images.githubusercontent.com/65068467/145545439-daeac8f9-bf9c-4e47-bc9e-92ec754e1c75.png)
![image](https://user-images.githubusercontent.com/65068467/145545589-22340fab-6444-475e-8b1d-7656b9585090.png)
![image](https://user-images.githubusercontent.com/65068467/145545621-1c35a60b-7011-489d-99ce-d1b3dbcafa7d.png)

**Comment by travisn** [comment]
@yinmin2020 In the first log that you highlighted, the error message is that an OSD was configured for a different cluster. Did you reinstall the rook cluster? If so, you need to [cleanup the previous devices](https://rook.github.io/docs/rook/v1.8/ceph-teardown.html) before reinstalling.

**Comment by yinmin2020** [comment]
> @yinmin2020 In the first log that you highlighted, the error message is that an OSD was configured for a different cluster. Did you reinstall the rook cluster? If so, you need to [cleanup the previous devices](https://rook.github.io/docs/rook/v1.8/ceph-teardown.html) before reinstalling.

Thank you, I have cleaned the data disk through the script and remounted it successfully
