### ISSUE TITLE
Grafana Ceph dashboard not working

### ISSUE THREAD

**Issue by irizzant** [rook/rook#9381]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Grafana dasboards for Ceph reported [here](https://rook.io/docs/rook/v1.8/ceph-monitoring.html#grafana-dashboards) are all returning error in Grafana 8.3.1:
```
t=2021-12-10T12:10:21+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="failed to query data: time: invalid duration \"$interval\"" remote_addr=127.0.0.1
```

This is because of the Min Step reported in each panel:
![image](https://user-images.githubusercontent.com/15982257/145572603-11f963d1-87cd-407a-9cb8-62c76b673ec8.png)

Changing the value to `$__interval` fixes the dashboard:
![image](https://user-images.githubusercontent.com/15982257/145572755-41512a03-882e-48f7-966d-2803fe1dce96.png)

**Expected behavior:**
Grafana Ceph dashboards should work

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.3 LTS
* Kernel (e.g. `uname -a`): GNU/Linux 5.4.0-90-generic x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 
```
rook: v1.7.9
go: go1.16.7
```
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): `ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `HEALTH_OK`

**Comment by jmolmo** [comment]
@irizzant : Just for your information. There is an opened PR #8891, where you can find the instructions to setup the complete monitoring stack needed in the Ceph dashboard.
The Ceph dashboard provides a complete set of Grafana dashboards specially suited to monitor the whole Ceph cluster. 
So if it is useful for you, and you want to try it, It would be nice to have feedback about the documentation provided in PR #8891

**Comment by irizzant** [comment]
@jmolmo My monitoring stack is already in place and Prometheus is collecting metrics as expected, it's just a visualization issue in Grafana dashboard provided.
