### ISSUE TITLE
watch-active sidecar /var/lib/rook: permission denied on 1.8.0

### ISSUE THREAD

**Issue by onedr0p** [rook/rook#9385]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

```
─❯ k logs -f deploy/rook-ceph-mgr-a -c watch-active | grep failed
2021-12-10 14:12:17.780890 C | rookcmd: failed to write connection config: failed to write keyring "client.admin" to /var/lib/rook/rook-ceph: failed to create keyring directory for /var/lib/rook/rook-ceph/client.admin.keyring: mkdir /var/lib/rook: permission denied
```

**Expected behavior:**

Upgrade to 1.8.0 to be successful

**How to reproduce it (minimal and precise):**

Attempt to upgrade to 1.8.0

**File(s) to submit**: N/A

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Focal
* Kernel (e.g. `uname -a`): 5.4
* Cloud provider or hardware configuration: N/A
* Rook version (use `rook version` inside of a Rook Pod): 1.8.0
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.6
* Kubernetes version (use `kubectl version`): 1.22.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HealthOK

**Comment by travisn** [comment]
Until this is fixed in v1.8.1, the workaround would be to run a single mgr instead of two.
