### ISSUE TITLE
aarch64: toolbox: s5cmd bash: /usr/local/bin/s5cmd: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by manjo-git** [rook/rook#9387]
On aarch64 / arm64 the s5cmd command in toolbox seems to be for a wrong architecture? 

rook version: commit 6a10adc4fb19f7832f56f1aa81144ac69e85f92a (HEAD -> master, origin/master, origin/HEAD)

```
[rook@rook-ceph-tools-555c879675-r96c6 ~]$  s5cmd --endpoint-url http://$AWS_ENDPOINT ls
bash: /usr/local/bin/s5cmd: cannot execute binary file: Exec format error
[rook@rook-ceph-tools-555c879675-r96c6 ~]$ s5cmd --help
bash: /usr/local/bin/s5cmd: cannot execute binary file: Exec format error
[rook@rook-ceph-tools-555c879675-r96c6 ~]$
```

Looks like this command shipped in toolbox is intel binary.
```
[rook@rook-ceph-tools-555c879675-r96c6 ~]$ objdump -f  /usr/local/bin/s5cmd

/usr/local/bin/s5cmd:     file format elf64-x86-64
architecture: i386:x86-64, flags 0x00000102:
EXEC_P, D_PAGED
start address 0x000000000046d560

[rook@rook-ceph-tools-555c879675-r96c6 ~]$
```

**Comment by parth-gr** [comment]
@leseb I was not able to reproduce this type of behavior,

I verified it using printing S5CMD args used in [Dockerfile](https://github.com/rook/rook/blob/master/images/ceph/Dockerfile).

Added an extra step that prints the S5CMD_ARCH & S5CMD_VERSION: 
```
Step 4/14 : RUN bash -c 'echo -e $S5CMD_VERSION $S5CMD_ARCH'
 ---> Running in b4cef6cdddee
1.4.0 Linux-arm64
```
I got the correct variable data output.

@manjo-git  request you to provide more information if you still face it, and can you provide the output of ` go env GOHOSTARCH `  or `uname -m `

Also created a PR with some make [improvements](https://github.com/rook/rook/pull/9446).

**Comment by travisn** [comment]
@manjo-git Please let us know if this is still an issue for you, we were not able to repro
