### ISSUE TITLE
Provisioner wants to access config files which are not present

### ISSUE THREAD

**Issue by mrahbar** [rook/rook#939]
#### Problem description
When creating a rbd volume via storage-class and Persistentvolumeclaim I notice following error pattern:

> * 2017-08-23 22:05:34.121491 I | exec: Running command: rbd create replicapool/k8s-dynamic-pvc-6eebd260-884e-11e7-aeff-0026554d6342-2fa4d3de-884f-11e7-9367-52316add501e --size 2048 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring
> * E0823 22:05:34.386436      13 controller.go:796] Failed to provision volume for claim "rook-cluster/influxdb-pvc" with StorageClass "rook-storageclass": Failed to create rook block image replicapool/k8s-dynamic-pvc-6eebd260-884e-11e7-aeff-0026554d6342-2fa4d3de-884f-11e7-9367-52316add501e: failed to create image k8s-dynamic-pvc-6eebd260-884e-11e7-aeff-0026554d6342-2fa4d3de-884f-11e7-9367-52316add501e in pool replicapool of size 2147483648: Failed to complete : exit status 1. output:

Digging in into the shell out command I found that neither /var/lib/rook/rook/rook.config nor /var/lib/rook/rook/client.admin.keyring are present in the rook.operator pod where the provisioner is running. 

#### How is this supposed to work? 
Of course those files are present on my ceph nodes under the specified _dataDirHostPath: /opt/rook_ for the cluster _rook-cluster_: 
- /opt/rook/rook-cluster/client.admin.keyring'
- /opt/rook/rook-cluster/rook-cluster.config

After manually copying those files into the current instance of the rook-operator (and changing the different naming convention) the rbd volume was successfully created. 

#### Future steps
Did I miss something when provisioning my rook-cluster? I was following the kubernetes docs: https://rook.io/docs/rook/master/kubernetes.html

**Comment by travisn** [comment]
@mrahbar those config files are stored in an `emptyDir` in the operator pod when the cluster is created and in several scenarios where the cluster is updated. The config files are also generated if the operator restarts. I cannot repro the issue of those files not being present in the operator. Could you share your entire operator log on gist.github.com?

**Comment by jbw976** [comment]
docs to help you collect logs: https://rook.io/docs/rook/master/advanced-configuration.html#log-collection

**Comment by mrahbar** [comment]
Unfortunately I cant share the logs because if have already teared down the faulty cluster and redeployed it. I recreated the cluster (this time in the namespace **rook** instead of **rook-cluster** This time the files are there as expected:

mazad@kubernetesnode1:~/external-storage$ kubectl --namespace=rook exec -it rook-operator-3061223979-6zx95 -- ls -l /var/lib/rook/rook/
total 12
-rw------- 1 root root  160 Aug 24 19:39 client.admin.keyring
-rw------- 1 root root   79 Aug 24 19:19 mon.keyring
-rw-r--r-- 1 root root 1920 Aug 24 19:39 rook.config

I'm closing this one because it wasn't reproducible.
