### ISSUE TITLE
rbd commands fail if extra logging is on

### ISSUE THREAD

**Issue by jbw976** [rook/rook#942]
As @mrahbar found in https://gitter.im/rook/rook?at=599f301fa7b406262dc32732, extra logging turned on will cause `rbd` commands to fail.  This is because `rbd` does not support `--out-file` and both its logging and its output/result go to stdout.  We fail to parse the result that is mixed in with the logging.

It would be nice if upstream Ceph's `rbd` could support the `--out-file` argument.

**Comment by mrahbar** [comment]
### Suggesting 
Simple brackets regex with the assumption that the stdout contains the relevant informations as a json-block

### Working snippet
https://play.golang.org/p/v7Mvu_FOtc

**Comment by jbw976** [comment]
that seems fairly reasonable, thanks for trying that out!  it looks like that's the only spot in the code that we are unmarshalling output from `rbd`, so i think that's the only spot where that update would be needed.

**Comment by mrahbar** [comment]
PR #947
