### ISSUE TITLE
Enable per-volume encryption for RBD

### ISSUE THREAD

**Issue by Jiawei0227** [rook/rook#9424]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

RBD has encryption per Volume. However, this is not integrated with rook. It would be good to either integrate it with rook or make some documentation on how to make it work for rook.

Checking the ceph-csi rbd template: https://github.com/rook/rook/blob/master/pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml 

It seems `ceph-csi-encryption-kms-config` is missing. Wondering if this is intentional or something?

**What is use case behind this feature:**

Want to enable per-volume encryption

**Environment**:

**Comment by Madhu-1** [comment]
@Jiawei0227 what do you mean by per-volume encryption? in cephcsi we do support per-volume encryption for some KMS providers. how this is different from https://github.com/rook/rook/issues/7032

cc @nixpanic

**Comment by Jiawei0227** [comment]
This is very similiar to #7032 
But just want to mention that it seems the ceph-csi template is missing kms config file. So I think maybe it is worth adding it?

**Comment by Madhu-1** [comment]
@Jiawei0227 all encryption work will be covered in #7032
