### ISSUE TITLE
Unable to see the log for rook-ceph-purge-job

### ISSUE THREAD

**Issue by kumabuchi** [rook/rook#9429]
**Is this a bug report or feature request?**
* Bug Report (document)

**Deviation from expected behavior:**
* The command in the following document (step.2) could not see the log for rook-ceph-purge-osd job.
  * https://github.com/rook/rook/blob/master/Documentation/ceph-osd-mgmt.md#purge-the-osd-from-the-ceph-cluster
  ```
  $ kubectl -n rook-ceph get pod -o wide | grep rook-ceph-purge-osd
  rook-ceph-purge-osd--1-gg5fg     0/1   Completed   0   39s   10.244.64.212    node6.k8s.example.com   <none>   <none>

  $ kubectl -n rook-ceph logs -l app=rook-ceph-purge-osd
  No resources found in rook-ceph namespace.
  ```

**Expected behavior:**
* The log should be displayed.

**How to reproduce it (minimal and precise):**
* Run the rook-ceph-purge-osd job

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.9
* Kernel (e.g. `uname -a`): 3.10.0-1160.45.1.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.7.5
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.6
* Kubernetes version (use `kubectl version`): 1.22.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
@kumabuchi What labels do you see on the osd purge pod? That query should work according to the label that is specified [here](https://github.com/rook/rook/blob/master/deploy/examples/osd-purge.yaml#L20-L21). In any case, another way to see the logs would be: `kubectl -n rook-ceph logs <pod>`

**Comment by kumabuchi** [comment]
@travisn  As shown below, the job level was labeled, but the pod level was not.
```
# kubectl get job rook-ceph-purge-osd -nrook-ceph --show-labels
NAME                  COMPLETIONS   DURATION   AGE    LABELS
rook-ceph-purge-osd   1/1           11s        103s   app=rook-ceph-purge-osd

# kubectl get pod rook-ceph-purge-osd--1-d7r92 -nrook-ceph --show-labels
NAME                           READY   STATUS      RESTARTS   AGE    LABELS
rook-ceph-purge-osd--1-d7r92   0/1     Completed   0          2m3s   controller-uid=aad6f766-c05a-4f55-83c8-7a92a41ced2f,job-name=rook-ceph-purge-osd
```

By modifying `osd-purge.yaml` as shown below, I was able to add the label to pod as well and get the log using the command described in the document.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: rook-ceph-purge-osd
  namespace: rook-ceph
  labels:
    app: rook-ceph-purge-osd
spec:
  template:
+   metadata:
+     labels:
+       app: rook-ceph-purge-osd
    spec:
      serviceAccountName: rook-ceph-purge-osd
      containers:
        - name: osd-removal
(snip)
```

```
# kubectl get pod -nrook-ceph rook-ceph-purge-osd--1-mhsxz --show-labels
NAME                           READY   STATUS      RESTARTS   AGE    LABELS
rook-ceph-purge-osd--1-mhsxz   0/1     Completed   0          5m3s   app=rook-ceph-purge-osd,controller-uid=3a207421-4169-4707-85bb-71b09555b263,job-name=rook-ceph-purge-osd

# kubectl -n rook-ceph logs -l app=rook-ceph-purge-osd
2021-12-16 02:47:11.987719 I | op-k8sutil: Removed deployment rook-ceph-osd-3
(snip)
2021-12-16 02:47:16.552993 I | cephosd: no ceph crash to silence
2021-12-16 02:47:16.553046 I | cephosd: completed removal of OSD 3
```
