### ISSUE TITLE
host-based clusters can't have more than one OSD with metadataDevice

### ISSUE THREAD

**Issue by mikabytes** [rook/rook#9431]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Currently metadataDevice must be an LV due to [bug discussed here](https://github.com/rook/rook/discussions/7349). 

This works as long as it's only one OSD in the node. 

However, when 2 or more OSDs are in the system, ceph must have a partition in order to split it into LVs. An LV cannot be split further. 

**Expected behavior:**
Hard to say. Best would be if a partition could be used so ceph can create its volumes as per design. Another way would be to specify a metadataDevice for each OSD so that I can split it myself, but that doesn't seem to work either https://github.com/rook/rook/issues/9430

Due to the combination of bugs I'm slowly reaching the conclusion that Rook host-based clusters with rotational drives are unviable w/ Rook 1.8. I cannot place the DB on the rotational drives because that leads to write speeds around 3mb/s on a cluster with 6 drives, each capable of write speeds 100+ mb/s.

While I'm aware it might be possible to build a PVC-based cluster on bare metal, I feel it's way too much administration to justify the move to Rook.

I had a native Ceph implementation before attempting Rook that worked well. There are many gotchas going down the Rook path and I'm starting to feel that host-based clusters with rotational drives should be actively discouraged in the documentation.

**How to reproduce it (minimal and precise):**
1. Plug two slow rotational harddrives on /dev/sdb and /dev/sdc
2. Create a PV on a fast drive along with a VG called `vg0` and a LV called `scratch`
3. Use storage listed below for your `cluster.yaml` file

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 21.10
* Kernel (e.g. `uname -a`):  Linux h1 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.8.0 go: go1.16.10
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-2+99cec1949184b7", GitCommit:"99cec1949184b74601a9531944adad8813a0355a", GitTreeState:"clean", BuildDate:"2021-12-08T18:29:41Z", GoVersion:"go1.17.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-2+99cec1949184b7", GitCommit:"99cec1949184b74601a9531944adad8813a0355a", GitTreeState:"clean", BuildDate:"2021-12-08T18:26:16Z", GoVersion:"go1.17.4", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): microk8s

```
  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    #deviceFilter:
    config:
      metadataDevice: "vg0/scratch"
    nodes:
      - name: hp0
        devices:
          - name: sdb
          - name: sdc
```

```
2021-12-15 07:35:21.051228 I | cephosd: configuring new LVM device sdb
2021-12-15 07:35:21.051242 I | cephosd: using vg0/scratch as metadataDevice for device /dev/sdb and let ceph-volume lvm batch decide how to create volumes
2021-12-15 07:35:21.051252 I | cephosd: configuring new LVM device sdc
2021-12-15 07:35:21.051260 I | cephosd: using vg0/scratch as metadataDevice for device /dev/sdc and let ceph-volume lvm batch decide how to create volumes
2021-12-15 07:35:21.051299 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 --crush-device-class hdd /dev/sdb /dev/sdc --db-devices /dev/vg0/scratch --report
2021-12-15 07:35:21.833562 D | exec: --> passed data devices: 2 physical, 0 LVM
2021-12-15 07:35:21.833596 D | exec: --> relative data size: 1.0
2021-12-15 07:35:21.833602 D | exec: --> passed block_db devices: 0 physical, 1 LVM
2021-12-15 07:35:21.833606 D | exec: --> 1 fast allocations != 2 num_osds
2021-12-15 07:35:21.902057 C | rookcmd: failed to configure devices: failed to initialize osd: failed ceph-volume report: exit status 1
```

**Comment by travisn** [comment]
There are multiple limitations with the non-PV approach of creating OSDs. The recommended way to handle the complex metadata scenarios is to use the [storageClassDeviceSets that are backed by PVs](https://rook.github.io/docs/rook/v1.8/ceph-cluster-crd.html#dedicated-metadata-and-wal-device-for-osd-on-pvc). For bare metal, you can use a PV provider such as [TopoLVM](https://github.com/topolvm/topolvm). Have you looked at that? We should add an example to the docs using topolvm so it is much more clear how to do this for bare metal.

**Comment by mikabytes** [comment]
Those are some very nice suggestions. I will evaluate TopoLVM and if all goes smooth I'll make a PR for the docs :+1: 

Meanwhile, I did manage to get multiple OSDs per node to work with metadata devices today, thanks to your comment on my other issue #9430 , so I'll close this as it's no longer an issue for my host-based cluster.
