### ISSUE TITLE
Can't mount PV: globalmount does not exist on node

### ISSUE THREAD

**Issue by mikabytes** [rook/rook#9432]
This seems to already be reported #7520 however with different version and author closed their issue.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I set up Rook, `ceph status` reports everything is fine, then create the [K8s Registry Sample](https://rook.io/docs/rook/v1.8/ceph-filesystem.html) (scroll down) from documentation.

I see in Lens that the PV was crated and bound correctly. PVC likewise.

However, when pod attempts to start it fails with this event:
```
MountVolume.MountDevice failed for volume "pvc-3f35725e-ec90-429c-a230-b8c483f84a7c" : rpc error: code = InvalidArgument desc = staging path /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3f35725e-ec90-429c-a230-b8c483f84a7c/globalmount does not exist on node
```

**Expected behavior:**
The PVC should be mounted correctly.

**How to reproduce it (minimal and precise):**
Set up microk8s and install Rook, set everything up and make sure it's healthy. Then run the example from documentation as specified above.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Server 21.10
* Kernel (e.g. `uname -a`): `Linux hades 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: microk8s 1.23.0
* Rook version (use `rook version` inside of a Rook Pod): 1.18
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-2+99cec1949184b7", GitCommit:"99cec1949184b74601a9531944adad8813a0355a", GitTreeState:"clean", BuildDate:"2021-12-08T18:29:41Z", GoVersion:"go1.17.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-2+99cec1949184b7", GitCommit:"99cec1949184b74601a9531944adad8813a0355a", GitTreeState:"clean", BuildDate:"2021-12-08T18:26:16Z", GoVersion:"go1.17.4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): microk8s 1.23.0
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
have you configured https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml#L102-L103 Kubelet path to point to `/var/snap/microk8s/common/var/lib/kubelet`

**Comment by mikabytes** [comment]
@Madhu-1 Wow, I would never have found that on my own. Thanks, it works now!

**Comment by nihr43** [comment]
works for me too with rook 1.9 microk8s 1.24.  [here is a more stable link](https://github.com/rook/rook/blob/release-1.9/deploy/examples/operator.yaml#L117) to the parameter in 1.9.  I ended up deleting and recreating my operator which seems to be fine.

```
   # kubelet directory path, if kubelet configured to use other than /var/lib/kubelet path.
-  # ROOK_CSI_KUBELET_DIR_PATH: "/var/lib/kubelet"
+  ROOK_CSI_KUBELET_DIR_PATH: "/var/snap/microk8s/common/var/lib/kubelet"
```
