### ISSUE TITLE
helm install rook-master/rook fails if --version isn't specified

### ISSUE THREAD

**Issue by jbw976** [rook/rook#944]
The semantic version parsing/matching doesn't appear to work for helm charts from our master channel:
```
> helm repo add rook-master http://charts.rook.io/master
"rook-master" has been added to your repositories
> helm install rook-master/rook
Error: file "rook-master/rook" not found
```

This helm issue is tracking it on their side:
https://github.com/kubernetes/helm/issues/2797

A workaround for now is to specify the `--version` flag to a specific value from https://charts.rook.io/master/:
```
> helm install rook-master/rook --version v0.5.0-24.gccf1df3
```

**Comment by jfelten** [comment]
same issue here:

helm version
Client: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bassam** [comment]
passing the `--devel` flag seems to help.

**Comment by christhomas** [comment]
Using the following command worked for me too
```
helm --tiller-namespace=kube-system install rook-master/rook --version=v0.6.0-67.g2b0a0d9
```

Seems the versioning of the latest release is broken? should it start with 'v' ?

**Comment by StianOvrevage** [comment]
This should REALLY be present in the documentation. I came here to file this exact issue after messing around for an hour trying to find out what I was doing wrong.
