### ISSUE TITLE
Cannot remove a healthy OSD

### ISSUE THREAD

**Issue by kumabuchi** [rook/rook#9440]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
* I ran the following command to remove a healthy OSD on a PVC-based cluster, but the OSD pod is automatically restarted and cannot be stopped.

```
# kubectl get pod -nrook-ceph -owide | grep xk-node6
rook-ceph-crashcollector-xk-node6.k8s.example.com-54d8c9f4mqzzk   1/1     Running     0          132m    10.244.64.235    xk-node6.k8s.example.com   <none>           <none>
rook-ceph-osd-3-9b4799f75-nf6gx                                   1/1     Running     0          132m    10.244.64.234    xk-node6.k8s.example.com   <none>           <none>
rook-ceph-osd-prepare-set1-data-3vsh9x--1-2sf5z                   0/1     Completed   0          144m    10.244.64.231    xk-node6.k8s.example.com   <none>           <none>

# LANG=C date -u; kubectl -n rook-ceph scale deployment rook-ceph-osd-3 --replicas=0
Thu Dec 16 07:27:13 UTC 2021
deployment.apps/rook-ceph-osd-3 scaled

# kubectl get pod -nrook-ceph -owide | grep xk-node6
rook-ceph-osd-prepare-set1-data-3vsh9x--1-2sf5z                   0/1     Completed     0          145m    10.244.64.231    xk-node6.k8s.example.com   <none>           <none>
```

* After a short time...

```
# LANG=C date -u; kubectl get pod -nrook-ceph -owide | grep xk-node6
Thu Dec 16 07:29:42 UTC 2021
rook-ceph-crashcollector-xk-node6.k8s.example.com-54d8c9f4tfm2h   1/1     Running     0          112s    10.244.64.237    xk-node6.k8s.example.com   <none>           <none>
rook-ceph-osd-3-9b4799f75-npvc2                                   1/1     Running     0          112s    10.244.64.236    xk-node6.k8s.example.com   <none>           <none>
rook-ceph-osd-prepare-set1-data-3vsh9x--1-2sf5z                   0/1     Completed   0          147m    10.244.64.231    xk-node6.k8s.example.com   <none>           <none>
```

* The Operator log is shown below.
  * The reconciling will not be triggered by editing the OSD deployment, but it appears to be triggered by the deletion of the crashcollector deployment. Any good ideas on what to do to stop the healthy OSD?
```
2021-12-16 07:27:15.480047 I | ceph-crashcollector-controller: deleting deployment "rook-ceph-crashcollector-xk-node6.k8s.example.com" for node "xk-node6.k8s.example.com"
2021-12-16 07:27:15.534129 I | ceph-crashcollector-controller: successfully removed crash collector deployment "rook-ceph-crashcollector-xk-node6.k8s.example.com" from node "xk-node6.k8s.example.com"

2021-12-16 07:27:15.536184 I | ceph-spec: object "rook-ceph-crashcollector-xk-node6.k8s.example.com" matched on delete, reconciling
2021-12-16 07:27:15.536924 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2021-12-16 07:27:15.574911 I | op-mon: parsing mon endpoints: c=10.97.118.105:6789,a=10.107.128.101:6789,b=10.108.154.165:6789
2021-12-16 07:27:15.666740 I | ceph-cluster-controller: detecting the ceph image version for image quay.io/ceph/ceph:v16.2.6...
(snip)
```

**Expected behavior:**
* The osd should be down.

**How to reproduce it (minimal and precise):**
1. Prepare a node with only the OSD Pod running.
2. Remove the OSD as described in the documentation.
   * https://github.com/rook/rook/blob/master/Documentation/ceph-osd-mgmt.md#confirm-the-osd-is-down

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7.9
* Kernel (e.g. `uname -a`): 3.10.0-1160.45.1.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.7.5
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.6
* Kubernetes version (use `kubectl version`): 1.22.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): bare metal (on local pvc)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
Are the only Rook/Ceph pods on the node that one OSD and the crash collector? If so, I can see how the operator would see the OSD is scaled down, then delete the crash collector, then trigger a new reconcile, which would scale up the OSD again. To prevent this reconcile, you can scale down the operator until after you have purged the OSD.

**Comment by kumabuchi** [comment]
> Are the only Rook/Ceph pods on the node that one OSD and the crash collector?

Yes. If there are other pods on the node, such as other OSDs or MONs, the pod restart will not occur.

> To prevent this reconcile, you can scale down the operator until after you have purged the OSD.

It worked fine. Thank you.

**Comment by travisn** [comment]
Ok sounds like we can close the issue now, thanks.
