### ISSUE TITLE
How to find my disk in rook and mount it automatically?

### ISSUE THREAD

**Issue by 1998729** [rook/rook#9454]
hi I started the rook service in a k8s cluster, and during the first initialization, rook-ceph-osd-prepare worked successfully and found a usable disk and mounted it, but he did not automatically discover the new disk in the future.

**Comment by 1998729** [comment]
![image](https://user-images.githubusercontent.com/88186802/146477111-b9c9b3ea-e4cb-49b6-9596-fcbdf7634a3f.png)

**Comment by 1998729** [comment]
![image](https://user-images.githubusercontent.com/88186802/146477192-37ba5dc1-0840-4194-9b13-9ed010a98ea5.png)

**Comment by travisn** [comment]
@1998729 You will need to enable the discovery daemonset, which is disabled by default. See the [discovery operator setting](https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml#L328-L330).

**Comment by 1998729** [comment]
![image](https://user-images.githubusercontent.com/88186802/146918946-e723a32c-638c-4dac-acc2-8b27163b87dc.png)


> @1997729您需要能够默认使用的发现监护进程集。请参阅[发现相同的设置](https://github.com/rook/rook/blob/master/deploy/examples/operator.yaml#L328-L330)。
I have set it to true in operator.yml, but I still don’t find out. The available size of my cluster is already very small, and the current status is warning

**Comment by 1998729** [comment]
And I also tried to delete the ods pod of the current machine, but still to no avail

**Comment by travisn** [comment]
@1998729 Did you try restarting the operator pod? Every time the operator starts, it will look for new disks and add new OSDs.

If you want the auto-discovery to work, check again that the `ROOK_ENABLE_DISCOVERY_DAEMON` is enabled on the operator deployment (`kubectl -n rook-ceph get deploy rook-ceph-operator | grep DISCOVERY`). Perhaps it was just applied on your local yaml file.
