### ISSUE TITLE
Block storage mode results in RBD Read-Only file system error

### ISSUE THREAD

**Issue by snagiel** [rook/rook#9466]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I provisioned a fresh AWS EC2 node running CentOS 7, EBS volumes, and the latest kernel (5.15), Docker, Kubernetes (1.22), Minikube, and Rook (1.8) releases. Following the provided sample manifests and documentation for block storage, I am able to bind storage (PVCs) for a sample application (e.g. MySQL or Elasticsearch) but they immediately fail with the following error:

```
MountVolume.MountDevice failed for volume "pvc-10ffde33-7fa7-46e3-b5ac-73de0d336a8e" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 30) occurred while running rbd args: [--id csi-rbd-node -m 10.100.200.244:6789 --keyfile=***stripped*** map replicapool/csi-vol-a5df14d2-5e07-11ec-a985-0242ac110008 --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed rbd: map failed: (30) Read-only file system
```

Note: This problem seems suspiciously similar to https://github.com/kubernetes-sigs/kind/issues/745

**Expected behavior:**

Block storage is allocated with full R/W permissions.

**How to reproduce it (minimal and precise):**

The following manifest files were used to trigger this error:

- [crds.yaml](https://github.com/rook/rook/blob/release-1.8/deploy/examples/crds.yaml)
- [common.yaml](https://github.com/rook/rook/blob/release-1.8/deploy/examples/common.yaml)
- [operator.yaml](https://github.com/rook/rook/blob/release-1.8/deploy/examples/operator.yaml)
- [storageclass-test.yaml](https://github.com/rook/rook/blob/release-1.8/deploy/examples/csi/rbd/storageclass-test.yaml)
- [mysql.yaml](https://github.com/rook/rook/blob/release-1.8/deploy/examples/mysql.yaml)

**File(s) to submit**:

The only applicable error is seen in the event logs for the application using the `rook-ceph-block` storage class, as copied from above:

```
MountVolume.MountDevice failed for volume "pvc-a1e076ab-ffb4-430c-86e5-c9379ffc9539" : rpc error: code = Internal desc = rbd: map failed with error an error (exit status 30) occurred while running rbd args: [--id csi-rbd-node -m 10.103.246.119:6789 --keyfile=***stripped*** map replicapool/csi-vol-cf240e33-5ebe-11ec-8637-0242ac11000b --device-type krbd --options noudev], rbd error output: rbd: sysfs write failed rbd: map failed: (30) Read-only file system
```

From what I could gather, Ceph was/is healthy:

```
sh-4.4$ ceph status
cluster:
    id:     2a3418d3-dd53-4391-affb-844b27c2c684
    health: HEALTH_OK
 
  services:
    mon: 1 daemons, quorum a (age 24m)
    mgr: a(active, since 22m)
    osd: 1 osds: 1 up (since 23m), 1 in (since 23m)
 
  data:
    pools:   2 pools, 33 pgs
    objects: 13 objects, 67 B
    usage:   5.4 MiB used, 20 GiB / 20 GiB avail
    pgs:     33 active+clean

sh-4.4$ ceph osd status
ID  HOST       USED  AVAIL  WR OPS  WR DATA  RD OPS  RD DATA  STATE      
 0  minikube  5480k  19.9G      0        0       0        0   exists,up  
```

`dmesg` did not appear to show any obvious issues/errors. The only explicit references to this volume:
```
[22268.318264] nvme nvme1: pci function 0000:00:1f.0
[22268.323483] nvme 0000:00:1f.0: enabling device (0000 -> 0002)
[22268.337741] ACPI: \_SB_.LNKC: Enabled at IRQ 10
[22268.356764] nvme nvme1: 2/0/0 default/read/poll queues
```

...and no errors observed in the assorted pods running in the `rook-ceph` namespace. 

One thing I noticed -- possibly related? -- is that when the rook cluster is up and the PVC is bound, the volumes look like this:

```
$ lsblk -f
lsblk: dm-0: failed to get device path
lsblk: dm-0: failed to get device path
NAME        FSTYPE LABEL UUID                                 MOUNTPOINT
nvme0n1                                                       
+---nvme0n1p1 xfs          388a99ed-9486-4a46-aeb6-06eaf6c47675 /
nvme1n1  
```
... Note the "failed to get device path" errors, and the empty values for the nvme1n1 volume (the device that rook is using), but then if I reboot the node, it looks like this:
```
$ lsblk -f
NAME                                                                                                  FSTYPE      LABEL UUID                                   MOUNTPOINT
nvme0n1                                                                                                                                                        
+---nvme0n1p1                                                                                           xfs               388a99ed-9486-4a46-aeb6-06eaf6c47675   /
nvme1n1                                                                                               LVM2_member       ASWDcV-lUM3-gbMb-cq8i-a8i3-T12W-sYT8vv 
+---ceph--e3b8c678--d246--468e--9ecd--954b5907bf3a-osd--block--a7d90d9c--d7ae--44d8--b04e--d06bd3ddddaa 
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
* Kernel (e.g. `uname -a`): `Linux ip-10-xxx-xxx-xxx.xxxxx.org 5.15.9-1.el7.elrepo.x86_64 #1 SMP Thu Dec 16 09:01:13 EST 2021 x86_64 x86_64 x86_64 GNU/Linux`

* Cloud provider or hardware configuration: AWS EC2 / EBS
* Rook version (use `rook version` inside of a Rook Pod): `v1.8.0 go: go1.16.10`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
* Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Minikube
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `HEALTH_OK` (see more details above)

**Comment by snagiel** [comment]
Worth noting: Following the thread from https://github.com/kubernetes-sigs/kind/issues/745, I likewise found that switching to CephFS allowed things to work (i.e. full R/W permissions). However, block storage is a more appropriate model for our use-case, and obviously the sample configurations/apps should work out-of-the-box...

**Comment by Rakshith-R** [comment]
@nixpanic @Madhu-1 @humblec , Any clue on how to handle this issue? 
I am not sure about this error (especially on first mount)
`rbd error output: rbd: sysfs write failed rbd: map failed: (30) Read-only file system`

**Comment by nixpanic** [comment]
I guess that CentOS 7 does not allow `rbd map` to succeed, possibly due to SELinux. I am not sure what permissions are exactly required though...

**Comment by snagiel** [comment]
Thanks, @nixpanic. Is there a list of Linux distros that are tested/supported/recommended?

**Comment by nixpanic** [comment]
> Thanks, @nixpanic. Is there a list of Linux distros that are tested/supported/recommended?

For ceph-csi testing, we use CentOS-8. I think other users deploy with (recent versions of?) Ubuntu as that is sometimes mentioned in bug reports.
