### ISSUE TITLE
[question] Is the default replication size 1?

### ISSUE THREAD

**Issue by hansbogert** [rook/rook#948]
Did I miss some parts in the introductionary documentation? I created RGWs by using rookctl, and all the pools necessary were created with replication 1.

/edit

Only now I see the following docs: [1]
What would be idiomatic for Rook? First create a pools  which are necessary for a working RGW with CRD and replication size -- and then run the `rookctl object` create command? Though I wouldn't know (at least not by heart) which pools I would need to create.

Also if my understanding of Ceph is correct, then the following sentence from the page given in [1] should be revisited:

    When that’s done you will be able to lose 2/3 of your storage nodes 

First, this depends on the MIN_SIZE parameter of a pool. Second even if the MIN_SIZE=1 this would only hold in a three node cluster. Imagine a nine node cluster. Three nodes should be allowed to fail by the remark in [1]. However, statistically, it's possible that all replicas for an object are now offline.

[1] https://rook.io/docs/rook/master/advanced-configuration.html

**Comment by jbw976** [comment]
hi @hansbogert, yes the default replicated pool size is 1, but this default can be changed with the config override support described in https://rook.io/docs/rook/master/advanced-configuration.html#kubernetes-1.

A pool replica size can also be changed after it's created as described in https://rook.io/docs/rook/master/advanced-configuration.html#setting-the-number-of-replicas

We'll be working on a CustomResourceDefinition for object stores soon that will
* make this experience more native to the Kubernetes environment
* allow you to specify the replication or erasure coding values when creating the object store

Feel free to open a pull request to update some of the documentation wording to make things more clear as you've outlined, we're always accepting contributions! :)

**Comment by hansbogert** [comment]
> Feel free to open a pull request to update some of the documentation wording to make things more clear as you've outlined, we're always accepting contributions! :)
https://github.com/rook/rook/pull/951
