### ISSUE TITLE
Object Bucket Claim stuck on pending

### ISSUE THREAD

**Issue by mayzyo** [rook/rook#9486]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Using any value other than **us-east-1** for region in StorageClass as shown in Object Store quick start documentation would result in the ObjectBucketClaim getting stuck on pending.
**Expected behavior:**
Using a value other than **us-east-1** will result in ObjectBucketClaim being bound. e.g. region: **us-west-1**
**How to reproduce it (minimal and precise):**

I simply created a cluster loosely based on the quick start guide, then created an Object Store exactly as shown in the guide. 
**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Debian Bullseye
* Kernel (e.g. `uname -a`): 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.8
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`): v1.23.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): GKE maybe. The one from apt-get
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by thotz** [comment]
This may be related to https://github.com/rook/rook/discussions/9142

**Comment by mayzyo** [comment]
Yup, I think this is the same issue as in the discussion.

Would it be possible to add a comment in the quick start guide or examples to not mess with it? It was just not mentioned anywhere to leave it alone. The error was cryptic and it took hours to figure out this was the reason Object Store wasn't working for beginner :/

**Comment by thotz** [comment]
After discussing with Rook and ceph devs apparently `region` is not needed as the Storage Class parameter for RGW use case, hence we are planning to remove it from CRDs and documentation
