### ISSUE TITLE
Provisioner Pods not created when using helm chart

### ISSUE THREAD

**Issue by TroyDota** [rook/rook#9487]
**Deviation from expected behavior:**
None
**Expected behavior:**
The provisioner pods to be created
**How to reproduce it (minimal and precise):**
Apply the helm charts.

The rook-csi pods are not created at all, the cluster is created and the osd pods are created and complete assigning the OSDs to the physical disks but the provisioners are never created. Perhaps I am doing something wrong?

**Comment by TroyDota** [comment]
It turns out that https://github.com/rook/rook/blob/f746b502e0e570732b65b252423c9c92aa6b8d76/pkg/operator/ceph/cr_manager.go#L218 this line never completes it blocks for ever

**Comment by TroyDota** [comment]
I applied a dirty hack here, https://github.com/SevenTV/rook to get around the bug issue.

**Comment by parth-gr** [comment]
Can you provide the operator logs?

And on which rook version you are using?

**Comment by setiseta** [comment]
same here. after the upgrade from the operator v1.7.10 to 1.8.2 the csi daemonsets are gone.

I'm now back to 1.7.10.
It happened only on 1 of 3 installations.

**Comment by travisn** [comment]
@TroyDota @setiseta You have [enabled the csi driver(s) in the values.yaml](https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml#L58-L59), right? This is the default so I assume so. Please do provide the rook operator log. The links above for the workaround give a 404.

**Comment by setiseta** [comment]
yes the csi drivers are enabled by default, and was not changed.
since I'm gone back to 1.7.10, i have not saved the operator log.
I will do the update again later and provide the logs.

**Comment by TroyDota** [comment]
The only thing i changed in the yaml was the placement of nodes and drives. 
I too reverted back and the CSI driver was created successfully. 
The work around I did was to call the function (that created csi driver daemon set) manually 20s after the operator pod had started. 

I also redid my ceph cluster and no longer have the operator logs from the previous attempt at 1.8.2, i am currently running 1.8.1 and it seems fine.

**Comment by travisn** [comment]
Did you by chance try restarting the operator to see if it would create the csi driver after that? Anyway, looking forward to the operator logs next time it repros, thanks.

**Comment by TroyDota** [comment]
I did, i thought it was strange so i restarted the operator and also then deleted the helm deployment and tried to redeploy. (i also removed the ceph folder on each host machine if it was present)

**Comment by setiseta** [comment]
I have also restarted the operator without success.

Now I've retried the update, and the csi driver is not gone. very strange.
So I don't have any logs.

I've always done this with the rancher UI, maybe there was something wrong there on the first try.

**Comment by Madhu-1** [comment]
@setiseta what is the rook version you are using? can you please provide below to debug it

* rook operator pod logs
* `kubectl get deployment -nrook-ceph` output to check the deployment is created?

**Comment by setiseta** [comment]
@Madhu-1 its ok now. it was not ok on the first try. and a restart of the operator has not fixed it. 
on the second try there was no error anymore, so I don't have any log, I've not saved it on the first try.

**Comment by kasim457** [comment]
csi-rbdplugin and csi-cepfsplugin pods did not create in new  storage cluster configured using v1.8.0 version.


[operator-logs.txt](https://github.com/rook/rook/files/7860126/operator-logs.txt)

**Comment by BlaineEXE** [comment]
> csi-rbdplugin and csi-cepfsplugin pods did not create in new storage cluster configured using v1.8.0 version.
> 
> [operator-logs.txt](https://github.com/rook/rook/files/7860126/operator-logs.txt)

@kasim457 would you also care to show the `kubectl -n rook-ceph describe deploy rook-ceph-operator` as created by Helm?

**Comment by Hell-Fire** [comment]
I deleted my provisioner deployments, the daemonset, etc hoping to have the operator redeploy, but no such luck (while debugging another issue).  Restarted operator pod, changed ROOK_CSI_ENABLE_RBD and ROOK_CSI_ENABLE_CEPHFS through true > false, then false > true, changing CSI_PROVISIONER_REPLICAS, but nothing seems to get the reconcile to work.

I was hoping to trigger the delete driver path, then create again new, but no such luck.

Might need to bump up the log verbosity, but nothing at Info that seems to reveal what's going on.

[operator-deploy.txt](https://github.com/rook/rook/files/7900955/operator-deploy.txt)
[operator-logs.txt](https://github.com/rook/rook/files/7900956/operator-logs.txt)

**Comment by travisn** [comment]
@leseb and I were discussing, he had some idea of what it is and will see if we can get a fix into v1.8.3 tomorrow...

**Comment by leseb** [comment]
> I deleted my provisioner deployments, the daemonset, etc hoping to have the operator redeploy, but no such luck (while debugging another issue). Restarted operator pod, changed ROOK_CSI_ENABLE_RBD and ROOK_CSI_ENABLE_CEPHFS through true > false, then false > true, changing CSI_PROVISIONER_REPLICAS, but nothing seems to get the reconcile to work.
> 
> I was hoping to trigger the delete driver path, then create again new, but no such luck.
> 
> Might need to bump up the log verbosity, but nothing at Info that seems to reveal what's going on.
> 
> [operator-deploy.txt](https://github.com/rook/rook/files/7900955/operator-deploy.txt) [operator-logs.txt](https://github.com/rook/rook/files/7900956/operator-logs.txt)

Don't you use the CM to configure the operator? `rook-ceph-operator-config`? Thanks

**Comment by Hell-Fire** [comment]
> Don't you use the CM to configure the operator? `rook-ceph-operator-config`? Thanks

Honestly didn't realise it as an option, couldn't see in the chart that it deployed a CM and the operator doesn't make one.  Is just a little test Pi cluster I'm running at home so other than the time to reconsile on restart, not a big loss editing the deployment :)

**Comment by travisn** [comment]
> @leseb and I were discussing, he had some idea of what it is and will see if we can get a fix into v1.8.3 tomorrow...

Now targeting the release for Friday, with the combination of #9613 and #9704 to fix this
