### ISSUE TITLE
MON Application inside POD don't appear to be binding to NAD

### ISSUE THREAD

**Issue by ky-ma** [rook/rook#9488]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
whereabouts cluster IP is bound to MON pods, but Application doesn't seem to be binding to it.
Port 6789 and 3300

Quick test by lauching SSH using the same NAD and was able to SSH into it.

**Expected behavior:**
should be able to mount query cluster monitor from outside using the external IP of montiriong pods.

**How to reproduce it (minimal and precise):**

1. Clean deployment of kubernetes
2. whereabouts deployed
3. create NAD
4. deploy rook and rook-cluster, set for whereabouts pointed to NAD
5. everything configures, OSD's are on.
6. Check the pod description of MON-A and public IP is there.
7. Go to VM on same public network as the cluster and NMAP the MON IP and no ports or open.
8. SSH to node host MON-A, nmap same IP, no ports open. Now NAP the main IP.

**NMAP the MON using the NAD IP**
```
ubuntu@node1:~$ nmap 192.168.144.64 -p0-
Starting Nmap 7.80 ( https://nmap.org ) at 2021-12-26 10:09 CST
Nmap scan report for 192.168.144.64
Host is up (0.00015s latency).
All 65536 scanned ports on 192.168.144.64 are closed
```

**NMAP of MON using it's internal IP**
```
Nmap done: 1 IP address (1 host up) scanned in 2.01 seconds
ubuntu@node1:~$ nmap 10.233.126.26 -p0-
Starting Nmap 7.80 ( https://nmap.org ) at 2021-12-26 10:10 CST
Nmap scan report for 10.233.126.26
Host is up (0.00022s latency).
Not shown: 65534 closed ports
PORT     STATE SERVICE
3300/tcp open  ceph
6789/tcp open  ibm-db2-admin

Nmap done: 1 IP address (1 host up) scanned in 2.50 seconds
ubuntu@node1:~$
```

**Environment**:
* OS (e.g. from /etc/os-release):
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```
* Kernel (e.g. `uname -a`):
```Linux node1.gqma.maas 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
* Cloud provider or hardware configuration:
`BareMetal`
* Rook version (use `rook version` inside of a Rook Pod):
`go: go1.16.12`
* Storage backend version (e.g. for ceph do `ceph -v`):
`ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-17T02:23:27Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
```
HEALTH_OK

  cluster:
    id:     f741cb66-3dd3-430c-8634-2e3cf05e682b
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 46m)
    mgr: a(active, since 45m)
    osd: 6 osds: 6 up (since 44m), 6 in (since 12h)

  data:
    pools:   3 pools, 65 pgs
    objects: 906 objects, 1.6 GiB
    usage:   3.3 GiB used, 5.5 TiB / 5.5 TiB avail
    pgs:     65 active+clean

  io:
    client:   47 KiB/s wr, 0 op/s rd, 4 op/s wr

```

**Comment by leseb** [comment]
It's normal since monitors are using service IPs and these are not supported by Multus. So the NAD is attached but the daemon still binds to the internal/default SDN address. Once Multus supports kube-services we will change that. I'll send a PR to clarify this in the documentation.
