### ISSUE TITLE
Allow exposing the ceph-mgr dashboard

### ISSUE THREAD

**Issue by hansbogert** [rook/rook#949]
Does the current operator provide a way to see the ceph-mgr dashboard [1]?
If not, what would be a/the way to do this with Rook?

[1] http://docs.ceph.com/docs/master/mgr/dashboard/

**Comment by travisn** [comment]
would definitely be a nice-to-have. I could imagine a setting on the cluster.yaml that indicates the dashboard should be enabled. Not sure what it would take to include the module though.

**Comment by hansbogert** [comment]
@travisn you mean the actual module loaded by the manager? It is included with standard install of Ceph since Luminous. Isn't in there in the packages/images Rook uses?

**Comment by travisn** [comment]
I believe we just need to get the right python modules added to the image, similar to the work being done in #1154 to enable the prometheus module.
