### ISSUE TITLE
rgw: can not delete OBC when when trying to remove non-existent bucket 

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#9494]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Ceph's "remove bucket" API[1] returns ENOENT(NoSuchKey) when the target bucket doesn't exist. However, Rook expects NoSuchBucket here. Due to this problem, Rook always fails in the following code.

https://github.com/rook/rook/blob/90bea8a560355b829a257b5e1b0b44349c22f864/pkg/operator/ceph/object/bucket/rgw-handlers.go#L91-L98
```go
...
		err := p.adminOpsClient.RemoveBucket(context.TODO(), admin.Bucket{Bucket: bucketName, PurgeObject: &thePurge})
		if err == nil {
			logger.Infof("bucket %q successfully deleted", p.bucketName)
		} else if errors.Is(err, admin.ErrNoSuchBucket) {
			// opinion: "not found" is not an error
			logger.Infof("bucket %q does not exist", p.bucketName)
		} else {
			return errors.Wrapf(err, "failed to delete bucket %q", bucketName)
...
```

[1] https://docs.ceph.com/en/pacific/radosgw/adminops/#remove-bucket

**Expected behavior:**

Succeed to remove OBC.

**How to reproduce it (minimal and precise):**

Not sure yet but I hit this problem in the production environment.

**File(s) to submit**:

* Operator's logs, if necessary

Rook operator shows the following log continuously.

```
I1223 05:01:11.998347       7 helpers.go:107]  "msg"="getting claim for key" "key"="NAMESPACE/OBC_NAME"
I1223 05:01:12.003621       7 helpers.go:213]  "msg"="getting ObjectBucketClaim's StorageClass" "key"="NAMESPACE/OBC_NAME"
I1223 05:01:12.007829       7 helpers.go:218]  "msg"="got StorageClass" "key"="NAMESPACE/OBC_NAME" "name"="ceph-object-store-bucket"
I1223 05:01:12.007882       7 controller.go:246]  "msg"="OBC deleted, proceeding with cleanup" "key"="NAMESPACE/OBC_NAME"
I1223 05:01:12.007913       7 controller.go:509]  "msg"="syncing obc deletion" "key"="NAMESPACE/OBC_NAME"
I1223 05:01:12.007942       7 controller.go:640]  "msg"="getting objectBucket for key"  "key"="NAMESPACE/OBC_NAME"
I1223 05:01:12.018095       7 helpers.go:141]  "msg"="getting configMap for key"  "key"="NAMESPACE/OBC_NAME"
I1223 05:01:12.021781       7 helpers.go:154]  "msg"="getting secret for key"  "key"="NAMESPACE/OBC_NAME"
I1223 05:01:12.025933       7 resourcehandlers.go:463]  "msg"="updating status:" "key"="NAMESPACE/OBC_NAME" "new status"="Released" "ob"="OB_NAME" "old status"="Released"
I1223 05:01:12.034818       7 helpers.go:229]  "msg"="getting ObjectBucket's storage class" "key"="NAMESPACE/OBC_NAME" "name"="ceph-object-store-bucket"
I1223 05:01:12.039274       7 helpers.go:234]  "msg"="got StorageClass" "key"="NAMESPACE/OBC_NAME" "name"=null
2021-12-23 05:01:12.039310 I | op-bucket-prov: getting storage class "ceph-object-store-bucket"
2021-12-23 05:01:27.797138 I | op-bucket-prov: Delete: deleting bucket "BUCKET_NAME" for OB "OB_NAME"
2021-12-23 05:01:27.797175 I | op-bucket-prov: deleting Ceph user "ceph-user-uN273wK5" and bucket "BUCKET_NAME"
E1223 05:01:27.805393       7 controller.go:205] error syncing 'NAMESPACE/OBC_NAME': provisioner error deleting bucket failed to delete OBCResource bucket "BUCKET_NAME": failed to delete bucket "BUCKET_NAME": NoSuchKey tx0000000000000000125fa-0061c402a7-6f71a9-ceph-object-store-0 6f71a9-ceph-object-store-0-ceph-object-store-0, requeuing
```

**Environment**:
* OS (e.g. from /etc/os-release): flatcar
* Kernel (e.g. `uname -a`): 5.10.84-flatcar
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.7.7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph v16.2.6
* Kubernetes version (use `kubectl version`): v1.21.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): CKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

**Comment by satoru-takeuchi** [comment]
Please let me know if anyone has a good way to bypass this problem.

My ideas that I did not adopt:
- Analyze RemoveBucket()'s output: It's hard because go-ceph doesn't return a command log.
- Regard NoSuchKey(ENOENT) as "bucket doesn't exist": Ceph might return ENOENT when bucket exists.

The last resort is to use radosgw-admin command again.

**Comment by leseb** [comment]
> Please let me know if anyone has a good way to bypass this problem.
> 
> My ideas that I did not adopt:
> 
> * Analyze RemoveBucket()'s output: It's hard because go-ceph doesn't return a command log.

Yes, go-ceph just returns whatever the API returns. https://github.com/ceph/go-ceph/blob/0e3ed2982fed0628efab22238ad91e7be9b39dd9/rgw/admin/errors.go#L121

> * Regard NoSuchKey(ENOENT) as "bucket doesn't exist": Ceph might return ENOENT when bucket exists.
> 
> The last resort is to use radosgw-admin command again.

Why not use `errors.Is(err, admin.ErrNoSuchKey) || errors.Is(err, admin. ErrNoSuchBucket){` for this special case? It's not 100% accurate but better than using the radosgs-admin CLI again...

**Comment by satoru-takeuchi** [comment]
> Why not use errors.Is(err, admin.ErrNoSuchKey) || errors.Is(err, admin. ErrNoSuchBucket){ for this special case? It's not 100% accurate but better than using the radosgw-admin CLI again...

I'll check whether it's really safe. I'm afraid of the possibility of disaster when the target bucket exists but Ceph returns ENOENT(ErrNoSuckKey).

**Comment by thotz** [comment]
Sorry, I am a bit confused here. If RGW is sending `ENOENT` instead of `ERR_NO_SUCH_BUCKET` for bucket delete, then it is a bug in RGW, right?

**Comment by satoru-takeuchi** [comment]
@thotz Yes, It's a Ceph's bug. I sent a PR to fix this bug in Ceph.

https://github.com/ceph/ceph/pull/44413

I'm considering how to mitigate this bug in Rook.

**Comment by satoru-takeuchi** [comment]
@leseb @thotz 

> I'm considering how to mitigate this bug in Rook.

I found that [GET BUCKET](https://docs.ceph.com/en/latest/radosgw/s3/bucketops/#get-bucket) returns ERR_NO_SUCH_BUCKET correctly.

https://github.com/ceph/ceph/blob/375c22aba3ea1d4af6b05a3c83b0aee6ad2a0b6a/src/rgw/rgw_bucket.cc#L1249

I'll make a PR to bypass this problem by calling GET BUCKET after failing REMOVE BUCKET with ENOENT.
