### ISSUE TITLE
The reason for the rook prepare job exception is unclear.

### ISSUE THREAD

**Issue by fengjiankui121** [rook/rook#9498]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

rook prepare-job failed to update configmp during the process of creating osd, but there was no specific information that caused the exception in the exception information.

The code is as follows:
'''rook\pkg\operator\ceph\cluster\osd\status.go'''

	if err := kv.SetValueWithLabels(
		k8sutil.TruncateNodeName(orchestrationStatusMapName, node),
		orchestrationStatusKey,
		string(s),
		labels,
	); err != nil {
		// log the error, but allow the orchestration to continue even if the status update failed
		logger.Errorf("failed to set node %q status to %q for osd orchestration. %s err: %v", node, status.Status, status.Message)

exception log :  2021-12-13 03:00:30.263088 E | op-osd: failed to set node "master4" status to "completed" for osd orchestration.

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by parth-gr** [comment]
Is the next update was successful? 
this code is used to retry the update status process, can you also log the `exception log : 2021-12-13 03:00:30.263088 E | op-osd: failed to set node "master4" status to "completed" for osd orchestration.  ` error message after this?

And what version of rook you are in?
