### ISSUE TITLE
ceph-mon-a pod is trying to get wrong IP address when host network was enabled.

### ISSUE THREAD

**Issue by qkfrksvl** [rook/rook#9505]
****Is this a bug report or feature request?****
* Bug Report

****Deviation from expected behavior:****
ceph-mon-a pod is trying to get a pod network, not a host network.

****Expected behavior:****
host network ip address will be assigned

**How to reproduce it (minimal and precise):**

when I configure the network provider to host in cluster.yaml then apply, the only one mon(a) did try to get pod ip address.

**File(s) to submit**:

![image](https://user-images.githubusercontent.com/86870268/147638967-5035ce1c-4840-42d7-b157-431a6b17b03a.png)
![image](https://user-images.githubusercontent.com/86870268/147639071-5becade7-a696-484b-ae8a-cbe18fc9c89a.png)

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 8.4.2105
* Kernel (e.g. `uname -a`): 4.18.0-305.3.1.el8.x86_64
* Cloud provider or hardware configuration: No
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):v16.2.7
* Kubernetes version (use `kubectl version`):1.23.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):Native
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

[mon-a-pod-log.txt](https://github.com/rook/rook/files/7787807/mon-a-pod-log.txt)
[rook-operator-log.txt](https://github.com/rook/rook/files/7787808/rook-operator-log.txt)
[cluster.yaml.txt](https://github.com/rook/rook/files/7787810/cluster.yaml.txt)

**Comment by qkfrksvl** [comment]
ceph-mon-a pod information is corrected with public ip address.
![image](https://user-images.githubusercontent.com/86870268/147639769-bc670e1f-992b-4848-af9c-e061dff5a575.png)

**Comment by qkfrksvl** [comment]
also checked that whether host where ceph-mon-a pod running already use monitor pod port 3300, 6789
![image](https://user-images.githubusercontent.com/86870268/147640192-ab32f3e9-ef42-48b1-a900-2bd018fbd9db.png)

**Comment by qkfrksvl** [comment]
correct ip address that mon-a suppose to use is assigned to host interface.
![image](https://user-images.githubusercontent.com/86870268/147640479-fac94567-ea96-4d45-acb0-4167671e6037.png)

**Comment by leseb** [comment]
Please share the mon pod spec too. Also the op logs are truncated so it's missing some important logs.
