### ISSUE TITLE
How can I configure multiple metadata devices ?

### ISSUE THREAD

**Issue by qkfrksvl** [rook/rook#9507]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

As far as I know, cluster crd does not allow the array value on storage.metadataDevice. 
In my case, my server has 2 nvme disks and 8 ssd disks so then I need to use 2 nvme as metadata devices.

**Comment by leseb** [comment]
I don't think this is supported today. However, if you had the NVMe and SSDs as PVs you can use the cluster-on-pvc.yaml example or even take inspiration from https://github.com/rook/rook/blob/master/deploy/examples/cluster-on-local-pvc.yaml. Then you will have all the flexibility you need to deploy on both NVMe, they will need to be partitioned **beforehand**.
