### ISSUE TITLE
Create s3 buckets with predefined credentials

### ISSUE THREAD

**Issue by kolovo** [rook/rook#9509]
**Feature Request**
Allow the creation of s3 buckets with predefined credentials(AWS_ACCESS_KEY_ID , AWS_SECRET_ACCESS_KEY)

**What should the feature do:**
When creating an s3 bucket via objectbucketclaim or objectbucket it should be allowed to the end user to manual add AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY credentials

**What is use case behind this feature:**
Right now with the current implementation it is not possible for the apps that run in different namespaces to access the secret that holds the credentials for the bucket.
If the credentials are known in advance then the applications can access to AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY without accessing the secret.

**Comment by BlaineEXE** [comment]
Currently, the lib-bucket-provisioner library used to provide functionality for ObjectBucket{,Claims} is not in active development, and they are not taking new features unless they are critically necessary. As a replacement for lib-bucket-provisioner, Rook will be integrating with Container Object Storage Interface (COSI) as soon as we can once COSI is available: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1979-object-storage-support

However, to my knowledge, even COSI's alpha design doesn't allow requesting a bucket to have a specific access credential.  To my recollection, this may be a use-case that they have already rejected.

To accomplish what you want, you can use the S3 API to the object store to create a bucket with the credentials you desire, and then you can use the OBC brownfield use-case to give access to it.

However, I still have questions about your situation. You said:

> Right now with the current implementation it is not possible for the apps that run in different namespaces to access the secret that holds the credentials for the bucket.

Why is this currently impossible? It should be possible to create a Role that allows access to secrets in the OBC's namespace, and then use a ClusterRoleBinding to allow access to that from an app in another namespace, right?

**Comment by BlaineEXE** [comment]
Closing this as a wontfix since there is a way to accomplish cross-namespace access currently and with the upcoming COSI designs.
