### ISSUE TITLE
ceph device ls show no output

### ISSUE THREAD

**Issue by hackaholic** [rook/rook#9543]
**Is this a bug report or feature request?**

* Bug Report

**Bug Report**

**Expected behavior:**
Should list all disk devices

**Deviation from expected behavior:**
Empty output
**How to reproduce it (minimal and precise):**

lsblk output from ceph node:
```
[root@pwconfig-k8s-master0 apps]# ssh pwconfig-k8s-iond-worker0 lsblk
NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0              11:0    1  458K  0 rom
vda             252:0    0  200G  0 disk
|-vda1          252:1    0  512M  0 part /boot
|-vda2          252:2    0 99.5G  0 part
| |-vg-lv_root  253:0    0   15G  0 lvm  /
| |-vg-lv_pwcfg 253:1    0 12.9G  0 lvm
| |-vg-lv_var   253:2    0 14.9G  0 lvm  /var/log
| `-vg-lv_opt   253:3    0 56.7G  0 lvm  /opt
|-vda3          252:3    0   65G  0 part /pw
`-vda4          252:4    0   35G  0 part
```

vda4 is used by osd

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Feature Request**

**Are there any similar features already existing:**

**What should the feature do:**

**What would be solved through this feature:**

**Does this have an impact on existing features:**

**Environment**:
* OS (e.g. from /etc/os-release):
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Kernel (e.g. `uname -a`):
uname -a
Linux pwconfig-k8s-master0 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
{
    "mon": {
        "ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 3
    },
    "mgr": {
        "ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 2
    },
    "osd": {
        "ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 6
    },
    "mds": {
        "ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 2
    },
    "overall": {
        "ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 13
    }
}
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph -v
ceph version 16.2.2 (e8f22dde28889481f4dda2beb8a07788204821d3) pacific (stable)
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
 ceph health
HEALTH_OK

**Comment by BlaineEXE** [comment]
I don't think we really have enough information to understand the issue at hand. It looks like the cluster has 6 OSDs, and the lsblk command has output. What are you expecting to see differently?

**Comment by leseb** [comment]
Weird we had that fixed in https://github.com/rook/rook/pull/5001 already. I can repro on a local cluster too. Not sure what's missing yet.

**Comment by leseb** [comment]
@hackaholic is this a virtual machine?

**Comment by leseb** [comment]
My repro might just be an issue with my VM, Ceph looks for udev first and falls back to `sys/block` if fails, my udev reports:

```
[root@rook-ceph-osd-0-588fc55867-5wf4d ceph]# udevadm info -a -n /dev/ceph-ec14e5e9-437f-4b10-a488-06c708f64d63/osd-block-706c4839-a8fe-426c-b19c-39836d1b9f68 

Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key format.
A rule to match, can be composed by the attributes of the device
and the attributes from one single parent device.

  looking at device '/devices/virtual/block/dm-0':
    KERNEL=="dm-0"
    SUBSYSTEM=="block"
    DRIVER==""
    ATTR{alignment_offset}=="0"
    ATTR{capability}=="10"
    ATTR{discard_alignment}=="0"
    ATTR{ext_range}=="1"
    ATTR{hidden}=="0"
    ATTR{inflight}=="       0        0"
    ATTR{range}=="1"
    ATTR{removable}=="0"
    ATTR{ro}=="0"
    ATTR{size}=="83877888"
    ATTR{stat}=="   13106        0  1711328     2647  2358497        0 11914856  1674881        0  1602657  1677559        0        0        0        0"
```

And Ceph is searching for `ID_SERIAL`, my sys path is pretty lame too:

```
[root@rook-ceph-osd-0-588fc55867-5wf4d ceph]# cat /sys/block/vdb/device/vendor
0x1af4
[root@rook-ceph-osd-0-588fc55867-5wf4d ceph]# cat /sys/block/vdb/device/model 
cat: /sys/block/vdb/device/model: No such file or directory
[root@rook-ceph-osd-0-588fc55867-5wf4d ceph]# cat /sys/block/vdb/device/serial
cat: /sys/block/vdb/device/serial: No such file or directory
```

What does your env say @hackaholic ?

Thanks

**Comment by hackaholic** [comment]
@leseb  yes it the virtual machine

**Comment by hjjdreamer** [comment]
issue appear， deploy Ceph in VM, following is about the execute command
[root@serverc ~]# ceph orch host ls
HOST                     ADDR           LABELS  STATUS
clienta           172.25.250.10
serverc          172.25.250.12
serverd          172.25.250.13
servere          172.25.250.14
[root@serverc ~]# ceph -s
  cluster:
    id:     838bf6d2-8990-11ed-a0fe-52540000fa0c
    health: HEALTH_OK

  services:
    mon: 4 daemons, quorum serverc.lab.example.com,clienta,servere,serverd (age 2h)
    mgr: serverc.lab.example.com.qgsgxx(active, since 2h), standbys: servere.oyavuy, clienta.zdfhwz, serverd.ciatul
    osd: 20 osds: 20 up (since 57m), 20 in (since 94m)
    rgw: 2 daemons active (2 hosts, 1 zones)

  data:
    pools:   5 pools, 105 pgs
    objects: 221 objects, 4.9 KiB
    usage:   399 MiB used, 200 GiB / 200 GiB avail
    pgs:     105 active+clean

[root@serverc ~]# ceph device ls
DEVICE  HOST:DEV  DAEMONS  WEAR  LIFE EXPECTANCY

[root@serverc ~]# ceph orch device ls
Hostname                 Path      Type  Serial  Size   Health   Ident  Fault  Available
clienta.lab.example.com  /dev/vdb  hdd           10.7G  Unknown  N/A    N/A    No
clienta.lab.example.com  /dev/vdc  hdd           10.7G  Unknown  N/A    N/A    No
clienta.lab.example.com  /dev/vdd  hdd           10.7G  Unknown  N/A    N/A    No
clienta.lab.example.com  /dev/vde  hdd           10.7G  Unknown  N/A    N/A    No

**Comment by hjjdreamer** [comment]
issue appear， deploy Ceph in VM, following is about the execute command
[root@serverc ~]# ceph orch host ls
HOST                     ADDR           LABELS  STATUS
clienta           172.25.250.10
serverc          172.25.250.12
serverd          172.25.250.13
servere          172.25.250.14
[root@serverc ~]# ceph -s
  cluster:
    id:     838bf6d2-8990-11ed-a0fe-52540000fa0c
    health: HEALTH_OK

  services:
    mon: 4 daemons, quorum serverc.lab.example.com,clienta,servere,serverd (age 2h)
    mgr: serverc.lab.example.com.qgsgxx(active, since 2h), standbys: servere.oyavuy, clienta.zdfhwz, serverd.ciatul
    osd: 20 osds: 20 up (since 57m), 20 in (since 94m)
    rgw: 2 daemons active (2 hosts, 1 zones)

  data:
    pools:   5 pools, 105 pgs
    objects: 221 objects, 4.9 KiB
    usage:   399 MiB used, 200 GiB / 200 GiB avail
    pgs:     105 active+clean

[root@serverc ~]# ceph device ls
DEVICE  HOST:DEV  DAEMONS  WEAR  LIFE EXPECTANCY

[root@serverc ~]# ceph orch device ls
Hostname                 Path      Type  Serial  Size   Health   Ident  Fault  Available
clienta.lab.example.com  /dev/vdb  hdd           10.7G  Unknown  N/A    N/A    No
clienta.lab.example.com  /dev/vdc  hdd           10.7G  Unknown  N/A    N/A    No
clienta.lab.example.com  /dev/vdd  hdd           10.7G  Unknown  N/A    N/A    No
clienta.lab.example.com  /dev/vde  hdd           10.7G  Unknown  N/A    N/A    No
![Uploading Snipaste_2024-08-10_12-40-18.png…]()

**Comment by hjjdreamer** [comment]
![Snipaste_2024-08-10_12-40-18](https://github.com/user-attachments/assets/81335dc8-4127-4bad-8556-1c6d63c36bad)
picture is following

**Comment by hjjdreamer** [comment]
![Snipaste_2024-08-10_12-40-18](https://github.com/user-attachments/assets/c5ac4b5b-fbb0-42ba-8d00-1869b251a918)
picture is following

**Comment by hjjdreamer** [comment]
[root@serverc ~]# ceph -v
ceph version 16.2.0-117.el8cp (0e34bb74700060ebfaa22d99b7d2cdc037b28a57) pacific (stable)
[root@serverc ~]#

**Comment by BlaineEXE** [comment]
The `ceph orch` commands are no longer expected to work with Rook.
