### ISSUE TITLE
Security: Use subvolumegroups instead of new cephfs instances in scenario with external cluster

### ISSUE THREAD

**Issue by CO-lhageman** [rook/rook#9551]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
In a scenario with a single external Ceph cluster and n K8s clusters, you should be able to use a single CephFS with n subvolumegroups instead of n CephFS instances with one subvolumegroup ("csi") each.

**What is use case behind this feature:**
Creating multiple CephFS instances requires a lot of pools which drives up the amount of PGs needed to properly work with those pools. Depending on your amount of OSDs you run into a lot of overhead with this.

Afaik you are able to set permissions on a subvolumegroup level, this would still provide you with a way of seperating the environments.

**Comment by MiningPickaxe** [comment]
I just went over the Project board for 1.8 and noticed this might be somewhat of a duplicate to https://github.com/rook/rook/issues/7036

What is missing though is the support for this in the create-external-cluster-resources.py script - It did get support for rados namespaces which is awesome, but the subvolumegroups are missing.

**Comment by travisn** [comment]
> I just went over the Project board for 1.8 and noticed this might be somewhat of a duplicate to #7036
> 
> What is missing though is the support for this in the create-external-cluster-resources.py script - It did get support for rados namespaces which is awesome, but the subvolumegroups are missing.

Did you try the v1.8.2 release? The [subvolume group](https://rook.github.io/docs/rook/v1.8/ceph-fs-subvolumegroup.html) configuration was included there.

**Comment by leseb** [comment]
What are you expecting from the script? To create the subvolumegroup? How are you using the script? For ceph-csi to consume the subvolumegroup, we need to update the `rook-ceph-csi-config` configmap. I have this PR https://github.com/rook/rook/pull/9484 but it's for converged mode. For external mode we don't have anything despite updating the CM manually for now.

**Comment by CO-lhageman** [comment]
I would expect to do the following things manually:
Create a cephfs
Create a subvolumegroup

I would pass this along to the script; the script would generate the users with the correct caps and generate me the StorageClass with the subvolumegroup as a parameter - Or thats what I thought when I without a lot of research beforehand opened this issue.

I don't see a parameter in the StorageClass for Cephfs that would allow me to specify a subvolumegroup. 
How does this actually work if I were to manually use it?

I was expecting the seperation between tenants to take place at the StorageClass level: You give the StorageClasse to your tenant and hardcode the subvolumegroup into the Storageclass. Your tenant is then able to create the subvolumes via the storageclass and they get placed into the subvolumegroup. The tenants ceph users would be unable to view other subvolumegroups, only working within their assigned one.
If this is not how it works/how it was intended, can someone explain this to me again and help me clear my confusion?

**Comment by CO-lhageman** [comment]
Hello, its been a couple of weeks since the last message. 
Is there any new documentation on this I didn't find?

**Comment by leseb** [comment]
> Hello, its been a couple of weeks since the last message. Is there any new documentation on this I didn't find?

No updates so far, this has yet to be addressed. The SC from the JSON blob could certainly have the subvolumegroup but this won't solve the `rook-ceph-csi-config` ConfigMap aspect.

**Comment by leseb** [comment]
@CO-lhageman we are getting therewith https://github.com/rook/rook/pull/9694, if you create an external cephFilesystemSubVolumeGroup the ceph-csi will be done. I think this should solve your use case (despite the missing piece in the python script).

**Comment by CO-lhageman** [comment]
> @CO-lhageman we are getting therewith https://github.com/rook/rook/pull/9694, if you create an external cephFilesystemSubVolumeGroup the ceph-csi will be done. I think this should solve your use case (despite the missing piece in the python script).

How and where do you specify the Subvolumegroup when consuming it? Havent found that part in the docs yet

**Comment by leseb** [comment]
> > @CO-lhageman we are getting therewith #9694, if you create an external cephFilesystemSubVolumeGroup the ceph-csi will be done. I think this should solve your use case (despite the missing piece in the python script).
> 
> How and where do you specify the Subvolumegroup when consuming it? Havent found that part in the docs yet

Can you clarify the question? You need to create a CR and Rook will handle the rest. What's missing is the script creating the subvolumegroup in the external cluster. You can create it manually and use the same name for the CephFilesystemSubVolumeGroup CR name.

**Comment by Madhu-1** [comment]
> clarify the question? You need to create a CR and Rook will handle the rest. What's missing is the script creating the subvolumegroup in the external cluster. You can create it manually and use the same name for the CephFilesystemSubVolumeGroup CR name.

@leseb the handling of storageclass creation with proper cluster-ID is missing in doc or external script? without knowing what clusterID they need to use in storageclass makes it hard to consume this one.

**Comment by leseb** [comment]
> > clarify the question? You need to create a CR and Rook will handle the rest. What's missing is the script creating the subvolumegroup in the external cluster. You can create it manually and use the same name for the CephFilesystemSubVolumeGroup CR name.
> 
> @leseb the handling of storageclass creation with proper cluster-ID is missing in doc or external script? without knowing what clusterID they need to use in storageclass makes it hard to consume this one.

The clusterID is in the CephFilesystemSubVolumeGroup status. But true, it's not written anywhere :), will try to change that.

**Comment by CO-lhageman** [comment]
> the handling of storageclass creation with proper cluster-ID is missing in doc or external script? without knowing what clusterID they need to use in storageclass makes it hard to consume this one.

ooh ok, so the cluster-id changes in the StorageClass, there is no additional parameter.
So if my subvolumegroup looks like this:
```
status:
  info:
    clusterID: 4037d54a320a2d81d241414546f4e106
  phase: Connected
```
I use the cluster ID generated by this in the Storage Class. Instead of `rook-ceph-external` it is now `4037d54a320a2d81d241414546f4e106`

Yes that was exactly my question, I had no idea this is how it works.
Is the ClusterID generated by the subvolumegroup predictable/are you able to get the ID before applying? This would make automating this in terraform easier.

**Comment by leseb** [comment]
> > the handling of storageclass creation with proper cluster-ID is missing in doc or external script? without knowing what clusterID they need to use in storageclass makes it hard to consume this one.
> 
> ooh ok, so the cluster-id changes in the StorageClass, there is no additional parameter. So if my subvolumegroup looks like this:
> 
> ```
> status:
>   info:
>     clusterID: 4037d54a320a2d81d241414546f4e106
>   phase: Connected
> ```
> 
> I use the cluster ID generated by this in the Storage Class. Instead of `rook-ceph-external` it is now `4037d54a320a2d81d241414546f4e106`
> 
> Yes that was exactly my question, I had no idea this is how it works. Is the ClusterID generated by the subvolumegroup predictable/are you able to get the ID before applying? This would make automating this in terraform easier.

Yes, if you are familiar with Go: https://github.com/rook/rook/blob/4c637858676dad5b5c7e2f3ddf2d87caa6b5d53b/pkg/operator/ceph/file/subvolumegroup/controller.go#L332-L335

Otherwise, it's a truncated (first 16 bytes) sha256 sum of `cephFilesystemSubVolumeGroup.Namespace-cephFilesystemSubVolumeGroup.Spec.FilesystemName-cephFilesystemSubVolumeGroup.Name`.

Hope that helps. Thanks!
