### ISSUE TITLE
[Bug] Prepare doesn't match against all disks in the intended regex

### ISSUE THREAD

**Issue by crdnl** [rook/rook#9552]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Given disks `sda` -> `sdi`, and a device filter of `^sd[b-h]`, `sdb` isn't matched against

**Expected behavior:**
`sdb` through `sdh` is within the device filter regex, and should be included in OSD matching.

**How to reproduce it (minimal and precise):**
1. Modify `cluster-test.yaml` to disable `useAllNodes` and `useAllDevices`
2. Add the following block:
```
nodes:
- name: "ouroboros"
  devices:
  - name: "^sd[b-h]
```

**File(s)**:

* [Cluster CR](https://gist.github.com/crdnl/b557715a76a6a46fa348a3f920e8ccf8)
* [Prepare Logs](https://gist.github.com/crdnl/f63bc578e5108f72f4bfa0b405564368)

**Environment**:
* OS: `k3OS v0.22.2-k3s2r0`
* Kernel: `Linux ouroboros 5.4.0-88-generic #99 SMP Tue Oct 5 16:53:38 UTC 2021 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `Dell R630`
* Rook version: `v1.8.2`
* Storage backend version): `16.2.7`
* Kubernetes version: `v1.22.2+k3s2`
* Kubernetes cluster type: `k3s`
* Storage backend status: `HEALTH_WARN`

**Comment by travisn** [comment]
Try setting the `deviceFilter` instead of the specific device name:
```yaml
nodes:
- name: "ouroboros"
  deviceFilter: "^sd[b-h]"
```

**Comment by crdnl** [comment]
Yeah, that works.
