### ISSUE TITLE
`Make Crd` generation output differ with rook:master crds

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#9563]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
  
Running `make crd` in latest master, differ in the output generation
One Instance of local fedora: https://github.com/rook/rook/commit/58146670da222674001c862ed2fec07169574a2c

**Expected behavior:**

CRD generation should be the same as the master.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by BlaineEXE** [comment]
I was able to verify this behavior on a fresh Fedora VM locally also. I suspected it could be a region/locality issue, but that doesn't seem to be the case. It is working fine in our Ubuntu CI, but Fedora has a different behavior for some reason. 

The CRD generator doesn't use filename sorting like `gen-rbac` does, so it isn't likely to be that issue. It's possible that `controller-gen` or `yq` are behaving differently on Fedora, though I don't quite understand why they would. Both are golang tools and should be the same between Fedora and Ubuntu. Perhaps one or both rely on system behavior for their operation.

**Comment by BlaineEXE** [comment]
I downloaded an Ubuntu 20.04 image and also found that the issue appears there. CI uses Ubuntu 18.04, so it may be that something has changed between Ubuntu 18.04 and 20.04. Otherwise, I'm not sure how CI and MacOS would be giving one result -- and Fedora (latest) and Ubuntu 20.04 a different result.

**Comment by BlaineEXE** [comment]
Even testing this on a quick Ubuntu 18.04 install, I see the same behavior Parth mentioned. How is this working in our CI at all?

**Comment by BlaineEXE** [comment]
From what I can tell, this is likely to be a system issue. 

The `build-crds.sh` script processes the files with the following line.
```sh
$YQ_BIN_PATH eval-all '.' "$OLM_CATALOG_DIR/"*.yaml >> "$CEPH_CRDS_FILE_PATH"
```
Here, you can see there is a slight difference in ordering between MacOS (left) and Ubuntu 18.04 (right) at `...cephfilesystems` vs. `...cephfilessytemsubvolumegroups`.
![image](https://user-images.githubusercontent.com/3989526/149243435-33c34df7-e3cf-4bbd-ab92-fe6f0d602b26.png)
