### ISSUE TITLE
Deploy VolumeSnapshotClass with Helm release

### ISSUE THREAD

**Issue by brovoca** [rook/rook#9566]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

Automatically deploy the VolumeSnapshotClass during a Helm release deployment.

**What is use case behind this feature:**

Users manually need to deploy the VolumeSnapshotClass, but I would expect this to be a part of the Helm release [now that Volume Snapshots have been promoted to GA in K8s 1.20](https://github.com/kubernetes-csi/external-snapshotter/tree/release-5.0#overview). Helm's [.Capabilities.APIVersions.Has](https://helm.sh/docs/chart_template_guide/function_list/#capabilitiesapiversionshas) might be of use.

**Environment**:

N/A?

**Comment by Madhu-1** [comment]
what do you mean by VolumeSnapshot?
 even if required from Rook we can only create VolumeSnapshotClass. 
Today even we don't create default storageclass by default for both cephfs and rbd as filesystem and block pool need to be created.

cc @leseb @travisn can you please confirm?

**Comment by Madhu-1** [comment]
Even to create the VolumeSnapshotClass the VolumeSnapshotClass CRD should be first installed as its not installed by default in kubernetes

**Comment by brovoca** [comment]
@Madhu-1 please ignore the "VolumeSnapshot" part. I removed it. I was too quick during writing and so my brain lagged behind :-)

**Comment by brovoca** [comment]
@Madhu-1 Can't the VolumeSnapshotClass be created prior to the creation of the pools? I assume the Helm chart already has necessary data about the to-be-created pools in order to create a VolumeSnapshotClass in anticipation of them.

**Comment by Madhu-1** [comment]
okay we do have storageclasses created by default https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L319-L398 @travisn @leseb please ignore the above comment. Yes, it's possible to create the VSC also.

**Comment by travisn** [comment]
> okay we do have storageclasses created by default https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml#L319-L398 @travisn @leseb please ignore the above comment. Yes, it's possible to create the VSC also.

Yes, the helm chart will create a storage class for rbd or cephfs, depending on those settings in the chart. Similarly, I see the VolumeSnapshotClass could be created by the rook-ceph-cluster helm chart.

**Comment by brovoca** [comment]
Kindly see my comment in [#9586](https://github.com/rook/rook/pull/9586#issuecomment-1021972710).
