### ISSUE TITLE
Mon failover needs to be smarter instead of so agressive

### ISSUE THREAD

**Issue by travisn** [rook/rook#957]
Every 10s the operator performs a health check. If a mon is found out of quorum, it is immediately assumed to be dead. The operator will start a new mon, then after it is in quorum the bad mon will be removed from quorum. A few thoughts on making this smarter:
- Allow a longer grace period, such as 30s
- Detect the host node is rebooting, wait a bit longer for the node to come back up
- If using the dataDirHostPath and the node is up, the mon pod might be hung. Just delete the pod and let it try to restart

**Comment by galexrt** [comment]
I'll try to write a logic for the second point you mentioned. If the node with the mon is in state "NotReady" it'll wait a configurable longer timeout (a bit like the Ceph variables `mon osd report timeout` and/or`mon osd down out interval`  for OSDs).

**Comment by travisn** [comment]
Since #958 was merged, I'm less clear on the scenario where we really need a change here. Let's open a more specific issue when the scenario is clear.
