### ISSUE TITLE
pvc mount failure

### ISSUE THREAD

**Issue by czhfe** [rook/rook#9575]
pvc mount failure。

**Comment by czhfe** [comment]
![image](https://user-images.githubusercontent.com/19341806/149473505-2f0f30f8-0952-4bbf-ae00-37334196b8f1.png)

**Comment by travisn** [comment]
Not sure the issue, can you provide more repro steps? Here are some ideas:
- [PVCs staying in pending state](https://rook.github.io/docs/rook/v1.8/ceph-common-issues.html#pvcs-stay-in-pending-state)
- [CSI common issues](https://rook.github.io/docs/rook/v1.8/ceph-csi-troubleshooting.html)
- Is your ceph cluster healthy? What does `ceph status` in the toolbox show?

**Comment by czhfe** [comment]
> Not sure the issue, can you provide more repro steps? Here are some ideas:
> 
> * [PVCs staying in pending state](https://rook.github.io/docs/rook/v1.8/ceph-common-issues.html#pvcs-stay-in-pending-state)
> * [CSI common issues](https://rook.github.io/docs/rook/v1.8/ceph-csi-troubleshooting.html)
> * Is your ceph cluster healthy? What does `ceph status` in the toolbox show?

- cephfs mount occasionally fails to mount and prompts permission issues, check pvc mount path on kubernetes node prompts permission issues
- ceph cluster status is healthy

Detailed exceptions are as follows:
![image](https://user-images.githubusercontent.com/19341806/149687386-fb4ab513-9303-4478-a0c9-cc382d06e4a4.png)

![image](https://user-images.githubusercontent.com/19341806/149687326-a332eea6-e2e7-4cb2-ba62-156bbc46bc61.png)

**Comment by czhfe** [comment]
> > Not sure the issue, can you provide more repro steps? Here are some ideas:
> > 
> > * [PVCs staying in pending state](https://rook.github.io/docs/rook/v1.8/ceph-common-issues.html#pvcs-stay-in-pending-state)
> > * [CSI common issues](https://rook.github.io/docs/rook/v1.8/ceph-csi-troubleshooting.html)
> > * Is your ceph cluster healthy? What does `ceph status` in the toolbox show?
> 
> * cephfs mount occasionally fails to mount and prompts permission issues, check pvc mount path on kubernetes node prompts permission issues
> * ceph cluster status is healthy
> 
> Detailed exceptions are as follows: ![image](https://user-images.githubusercontent.com/19341806/149687386-fb4ab513-9303-4478-a0c9-cc382d06e4a4.png)
> 
> ![image](https://user-images.githubusercontent.com/19341806/149687326-a332eea6-e2e7-4cb2-ba62-156bbc46bc61.png)

**Comment by czhfe** [comment]
![image](https://user-images.githubusercontent.com/19341806/149687518-438fa495-6737-45e1-9130-3aaaab66f68e.png)

**Comment by czhfe** [comment]
![image](https://user-images.githubusercontent.com/19341806/149688123-efa9d091-ba5b-4f75-add5-ae7153562ad5.png)

**Comment by Madhu-1** [comment]
@czhfe are you using kernel mount or the fuse mount? and is SELinux enabled in your setup? it could be due to selinux

**Comment by czhfe** [comment]
> @czhfe are you using kernel mount or the fuse mount? and is SELinux enabled in your setup? it could be due to selinux

- This is a pod mount in kubernetes, which is mounted via kubelet and should use kernel mount
- Selinux is closed

![image](https://user-images.githubusercontent.com/19341806/149721162-625a7e89-3e50-4830-b36a-7591eacad4fc.png)
