### ISSUE TITLE
CSI drivers are not upgraded in 1.8.2

### ISSUE THREAD

**Issue by hezise** [rook/rook#9579]
**Is this a bug report or feature request?**
* Bug Report
I performed an upgrade. rook and ceph were upgraded but not the ceph drivers. I saw in documentation that the new version are stored in a config-map but I didn't see any config map called rook-ceph-operator-config 
rook-ceph-mds-shared-storage-a          req/upd/avl: 1/1/1      ceph-version=16.2.7-0
rook-ceph-mds-shared-storage-b          req/upd/avl: 1/1/1      ceph-version=16.2.7-0
rook-ceph-mgr-a         req/upd/avl: 1/1/1      ceph-version=16.2.7-0
rook-ceph-mon-a         req/upd/avl: 1/1/1      ceph-version=16.2.7-0
rook-ceph-mon-b         req/upd/avl: 1/1/1      ceph-version=16.2.7-0
rook-ceph-mon-c         req/upd/avl: 1/1/1      ceph-version=16.2.7-0
rook-ceph-osd-0         req/upd/avl: 1/1/1      ceph-version=16.2.7-0
rook-ceph-osd-1         req/upd/avl: 1/1/1      ceph-version=16.2.7-0
rook-ceph-osd-2         req/upd/avl: 1/1/1      ceph-version=16.2.7-0

rook-ceph-mds-shared-storage-a          req/upd/avl: 1/1/1      rook-version=v1.8.2
rook-ceph-mds-shared-storage-b          req/upd/avl: 1/1/1      rook-version=v1.8.2
rook-ceph-mgr-a         req/upd/avl: 1/1/1      rook-version=v1.8.2
rook-ceph-mon-a         req/upd/avl: 1/1/1      rook-version=v1.8.2
rook-ceph-mon-b         req/upd/avl: 1/1/1      rook-version=v1.8.2
rook-ceph-mon-c         req/upd/avl: 1/1/1      rook-version=v1.8.2
rook-ceph-osd-0         req/upd/avl: 1/1/1      rook-version=v1.8.2
rook-ceph-osd-1         req/upd/avl: 1/1/1      rook-version=v1.8.2
rook-ceph-osd-2         req/upd/avl: 1/1/1      rook-version=v1.8.2

I also got the warning ceph-cluster-controller: insecure clients are connected to the cluster, to resolve the AUTH_INSECURE_GLOBAL_ID_RECLAIM health warning please refer to the upgrade guide to ensure all Ceph daemons are updated.
and was stopped after setting the command ceph config set mon auth_allow_insecure_global_id_reclaim false manually

let me know if you want me to provide more details

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* OpenStack
* Rook version (use `rook version` inside of a Rook Pod):
* 1.8.2
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* kubespray 2.15
* cluster:
    id:     e3a7e62d-ca00-414f-aaa7-c202dadfda51
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum a,b,c (age 4h)
    mgr: a(active, since 4h)
    mds: 1/1 daemons up, 1 hot standby
    osd: 3 osds: 3 up (since 4h), 3 in (since 5h)
 
  data:
    volumes: 1/1 healthy
    pools:   7 pools, 193 pgs
    objects: 22.12k objects, 32 GiB
    usage:   64 GiB used, 236 GiB / 300 GiB avail
    pgs:     193 active+clean
 
  io:
    client:   9.7 KiB/s rd, 657 KiB/s wr, 2 op/s rd, 78 op/s wr
 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by Madhu-1** [comment]
>I performed an upgrade. rook and ceph were upgraded but not the ceph drivers. I saw in documentation that the new version are stored in a config-map but I didn't see any config map called rook-ceph-operator-config

This is not by default. if the configmap is created by the user the new configuration will be fetched from the configmap or else it will be read from ENV or defaults will be used. @travisn can you please correct me if am wrong?

**Comment by hezise** [comment]
hi @Madhu-1 and @travisn 

I rebooted the operator to see if it solve it.
I got the following error:

ceph-spec: failed to update cluster condition to {Type:Ready Status:True Reason:ClusterCreated Message:Cluster created successfully LastHeartbeatTime:2022-01-17 08:59:40.77117636 +0000 UTC m=+146.332337159 LastTransitionTime:2022-01-16 09:47:44 +0000 UTC}. failed to update object "rook-ceph/rook-ceph" status: Operation cannot be fulfilled on cephclusters.ceph.rook.io "rook-ceph": the object has been modified; please apply your changes to the latest version and try again

**Comment by travisn** [comment]
This sounds like the same issue as #9487. The CSI driver is just not updating in some clusters, not clear yet why.

That failure in the log looks independent and should be benign.

**Comment by BlaineEXE** [comment]
I just noticed that the default update policy for CSI DaemonSets is `OnDelete`. Does CSI update automatically if the configs `CSI_CEPHFS_PLUGIN_UPDATE_STRATEGY` and `CSI_RBD_PLUGIN_UPDATE_STRATEGY` are changed to `RollingUpdate`?

**Comment by hezise** [comment]
# CSI CephFS plugin daemonset update strategy, supported values are OnDelete and RollingUpdate.
  # Default value is RollingUpdate.

**Comment by travisn** [comment]
Fixed with the combination of #9613 and #9074, targeting v1.8.3 tomorrow...
