### ISSUE TITLE
Configure Audit logging

### ISSUE THREAD

**Issue by Jiawei0227** [rook/rook#9580]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The CephCluster API should include a field to enable audit logging. This should filter audit log from the mon logs and able to set log level. 

For example, something like this need to be configured on mon side:

```
  mon_cluster_log_to_file=true
  mon_cluster_log_file_level=info
  mon_cluster_log_file='default=/var/log/ceph/$cluster.$channel.log cluster=/var/log/ceph/$cluster.log'
```

Also, for the log collector feature, it should consider audit logging into logrotate configuration.
Also, for ceph dashboards, it should enable audit logging as well by `ceph dashboard set-audit-api-enabled true`

**What is use case behind this feature:**

The ceph cluster we need have strong security compliance requirement. Audit logging is one of them and rook is lacking this support.

**Environment**:

**Comment by leseb** [comment]
Thanks I have a few questions inline:

> **Is this a bug report or feature request?**
> 
> * Feature Request
> 
> **What should the feature do:** The CephCluster API should include a field to enable audit logging. This should filter audit log from the mon logs and able to set log level.
> 
> For example, something like this need to be configured on mon side:
> 
> ```
>   mon_cluster_log_to_file=true

I'm fine with that, we can easily add it. In the meantime, you can access the toolbox and run:

````
ceph config set global mon_cluster_log_to_file true
```

>   mon_cluster_log_file_level=info

Any reason to change Ceph's default? Currently, the default is `debug`.

>   mon_cluster_log_file='default=/var/log/ceph/$cluster.$channel.log cluster=/var/log/ceph/$cluster.log'

That's already Ceph's default.

> ```
> 
> Also, for the log collector feature, it should consider audit logging into logrotate configuration.

We need to update our script that changes which file we rotate.

> Also, for ceph dashboards, it should enable audit logging as well by `ceph dashboard set-audit-api-enabled true`

Ok only if the dashboard is enabled.

> 
> **What is use case behind this feature:**
> 
> The ceph cluster we need have strong security compliance requirement. Audit logging is one of them and rook is lacking this support.
> 
> **Environment**:

**Comment by leseb** [comment]
Oh, I actually missed something, today, the audit logs and mon logs are merged into a single stream. So the `ceph.audit.log` content is in `ceph-mon.a.log`. Also, all of this is being logged rotated.

I'm not sure if there is anything to do.

**Comment by Jiawei0227** [comment]
> Any reason to change Ceph's default? Currently, the default is `debug`.

In production, i will impact the performance from my understanding. And I found even enable it on the config file, it still print debug log to the container.

> That's already Ceph's default.

From what I observed, without this, mon will merge cluster log and audit log together. And that does not seem to be the default value from my experiment.

> today, the audit logs and mon logs are merged into a single stream. So the ceph.audit.log content is in ceph-mon.a.log. Also, all of this is being logged rotated.

Yes, it is true if the output log is merged as ceph-mon.a.log that we rotated the log. But once enable `mon_cluster_log_file='default=/var/log/ceph/$cluster.$channel.log cluster=/var/log/ceph/$cluster.log'` the audit log will be stored as `ceph.audit.log` which isnt part of the rotation process.

> Ok only if the dashboard is enabled.

Yeah, feels to me this should be associated with the audit logging API. So that user does not have to manually turn it on after the cluster is configured.



Another question I always have is that: is changing config from the toolbox actually takes effect? I feel like each container like mgr, mon have its own config, and modifying config in toolbox only applies to the toolbox itself? Please let me know if my understand is wrong. Thanks a lot for your help!

**Comment by leseb** [comment]
> > Any reason to change Ceph's default? Currently, the default is `debug`.
> 
> In production, i will impact the performance from my understanding. And I found even enable it on the config file, it still print debug log to the container.
> 
> > That's already Ceph's default.
> 
> From what I observed, without this, mon will merge cluster log and audit log together. And that does not seem to be the default value from my experiment.
> 
> > today, the audit logs and mon logs are merged into a single stream. So the ceph.audit.log content is in ceph-mon.a.log. Also, all of this is being logged rotated.
> 
> Yes, it is true if the output log is merged as ceph-mon.a.log that we rotated the log. But once enable `mon_cluster_log_file='default=/var/log/ceph/$cluster.$channel.log cluster=/var/log/ceph/$cluster.log'` the audit log will be stored as `ceph.audit.log` which isnt part of the rotation process.
> 
> > Ok only if the dashboard is enabled.
> 
> Yeah, feels to me this should be associated with the audit logging API. So that user does not have to manually turn it on after the cluster is configured.
> 
> Another question I always have is that: is changing config from the toolbox actually takes effect? I feel like each container like mgr, mon have its own config, and modifying config in toolbox only applies to the toolbox itself? Please let me know if my understand is wrong. Thanks a lot for your help!

No modifying the config from the toolbox using `ceph config set` will actually affect all daemons.
