### ISSUE TITLE
CephRGW Keycloak integration problems

### ISSUE THREAD

**Issue by degorenko** [rook/rook#9583]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Following official Ceph docs for Rgw+Keycloak integration https://docs.ceph.com/en/octopus/radosgw/keycloak/ and https://docs.ceph.com/en/octopus/radosgw/STS/ , i'm able to invoke AssumeRole. But AssumeRoleWithWebIdentity is getting 403. Rgw log from pod (debug level: debug_rgw 20): https://paste.openstack.org/show/812146/
Rgw configuration and role/policies: https://paste.openstack.org/show/812145/
Keycloak URL is available within rgw pod and no any ssl handshake problems.

**Expected behavior:**
AssumeRoleWithWebIdentity is working following provided examples on Ceph docs.

**How to reproduce it (minimal and precise):**
Follow instructions provided on Ceph docs.

Ceph Version: v15.2.13
Rook verion: v1.7.6

**Comment by thotz** [comment]
@degorenko : I am copy-pasting comment from ceph engineer :
` configure the token to have a field called client_id or clientId set to "my-test"`

**Comment by degorenko** [comment]
@thotz Hey, thanks for response. It's strange, but when i'm invoking token introspect manually i see that field (call inside RGW container):

```
curl -k -X POST -u "my-test:3f98e2dd-3d64-4206-a1c8-d707f5a12b32" "https://10.100.91.103/auth/realms/demo/protocol/openid-connect/token/introspect" -d "token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJsQUdkek1nN2tIb3JtQmRwZ0lhVnJzakUwYXhkaXloZ1k2OWxmNG1OYkJFIn0.eyJleHAiOjE2NDI0OTY2ODUsImlhdCI6MTY0MjQ5NjM4NSwianRpIjoiOTQyY2YxNTktNWM4Yi00ZmNlLThkZDAtN2ZjY2I0YTAxN2ZiIiwiaXNzIjoiaHR0cHM6Ly8xMC4xMDAuOTEuMTAzL2F1dGgvcmVhbG1zL2RlbW8iLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNTZkYTYyODQtMmFjNS00ODI0LWExYTktMjNlYjUxZWIwZmRlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibXktdGVzdCIsInNlc3Npb25fc3RhdGUiOiJlZTYzMjVjYS1kMjU0LTQ1NWMtOTg0Ny1kZDZhZGZmZWZkZTEiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3QtdXNlciJ9.M-2mWALDQc4xTEVQDaki2gVRci99HAA-e5wuG3tvm8wAh-qS9FZI2CzBikTb8p3Y2qq2FO_ji3TVJMfN3aZo_g2Mfk0vYNSzf1uEiflBAayOGTm5sklO_jFMSXkh7kA0VdRUTRUJjXRKTRS2sLCZzxJEV973Yp4XgZK9yPffCL89Xfv9SxMIGUPPDo9jCY4trY_dnbjXtkuyBmsko_hLzob0QxIrxXDyKfJW8DmdLG9sneHVb0Et1DlQ_KJC_wOQfgd8Ci9PcC7EVUzfAoxXk2R2tHnCZw6zNhH7HY08EiHLFPm5l_zMjnGC5YEE7yJGHLjOCGa33NsAN_soeX3AdQ""""
{"exp":1642496685,"iat":1642496385,"jti":"942cf159-5c8b-4fce-8dd0-7fccb4a017fb","iss":"https://10.100.91.103/auth/realms/demo","aud":"account","sub":"56da6284-2ac5-4824-a1a9-23eb51eb0fde","typ":"Bearer","azp":"my-test","session_state":"ee6325ca-d254-455c-9847-dd6adffefde1","preferred_username":"test-user","email_verified":true,"acr":"1","realm_access":{"roles":["offline_access","uma_authorization"]},"resource_access":{"account":{"roles":["manage-account","manage-account-links","view-profile"]}},"scope":"openid email profile","client_id":"my-test","username":"test-user","active":true}
```

When i'm checking RGW logs, with the same URL in config for token introspection, i dont see that field:

```
debug 2022-01-18T09:01:26.985+0000 7f4ab37f4700 20 req 85627 0s sts:assume_role_web_identity rgw::auth::sts::DefaultStrategy: trying rgw::auth::sts::WebTokenEngine
debug 2022-01-18T09:01:26.985+0000 7f4ab37f4700 20 req 85627 0s sts:assume_role_web_identity  payload = {"exp":1642496685,"iat":1642496385,"jti":"942cf159-5c8b-4fce-8dd0-7fccb4a017fb","iss":"https://10.10
0.91.103/auth/realms/demo","aud":"account","sub":"56da6284-2ac5-4824-a1a9-23eb51eb0fde","typ":"Bearer","azp":"my-test","session_state":"ee6325ca-d254-455c-9847-dd6adffefde1","acr":"1","realm_access":{"rol
es":["offline_access","uma_authorization"]},"resource_access":{"account":{"roles":["manage-account","manage-account-links","view-profile"]}},"scope":"openid email profile","email_verified":true,"preferred
_username":"test-user"}
```

As you see, "jti", "session_state" fields are the same. So, i'm not sure why RGW can't decode token with client_id field. Any suggestions?

**Comment by degorenko** [comment]
Ok, so i switched from "grant_type=password" to "grant_type=client_credentials" for token request and now it is working. But this is a way for service account. For end user it still is not working. What should be changed in configuration to work with end user tokens?

**Comment by thotz** [comment]
@degorenko again copy-pasting reply from ceph developer
```
the client_id field must appear in the token received by rgw. if he decodes the token received by rgw in an online tool, he will see client_id isn't there. the introspect URL returns slightly different fields which we do not use in rgw anymore, if he can use client mapper to add client id to a user token then
these things have been addressed in the latest ceph version, I have created backports for pacific, but the code hasn't been merged yet

something like this: https://stackoverflow.com/questions/66912222/how-to-create-mapper-for-each-user-attribute-in-keycloak-via-rest-api
```

**Comment by degorenko** [comment]
Thanks for response. Sadly, for Octopus this is not working. So, the only way is using only client_credentials grant_type for getting token, right?

**Comment by thotz** [comment]
@degorenko : Okay please try that workaround as well, if it is not working then I reach out to the ceph devs again

**Comment by degorenko** [comment]
@thotz additionally, to provided example in link, i've added to user attribute "client_id" with actual id. Now i'm able to invoke AssumeRoleWithWebIdentity for particular user. I think, now we can close issue. Thank you very much.

**Comment by thotz** [comment]
@degorenko Thanks.
Closing this issue based on last comment
