### ISSUE TITLE
Ceph multisite replication with ssl untrusted certs

### ISSUE THREAD

**Issue by eringet** [rook/rook#9584]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Allow self signed certificates to be used for ceph objectstore endpoint urls with multisite replication.

**What is use case behind this feature:**
Using ssl for all ceph object traffic improves security.

**Environment**:
Rook 1.7.9
Ceph 16.2.6-0
OS of K9s cluster nodes: RedHat 8.5
Kubernetes version: 1.20.2

We are using certs generated from vault for our objectstore urls on two clusters.   On the destination cluster, we have copied over the realm keys secret, then attempt to create a realm with a pull endpoint eg. 

```
---
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: ptx-prod
  namespace: rook-ceph
spec:
  pull:
    endpoint: https://dev-rgw.myk8sclustername.k8s
```

The creation fails, with the following operator log:
```
2022-01-07 22:18:41.199053 I | op-mon: parsing mon endpoints: j=<IP1>:6789,k=<IP2>:6789,h=<IP3>:6789,i=<IP4>:6789,f=<IP5>:6789
2022-01-07 22:18:42.280238 E | ceph-object-realm-controller: failed to reconcile: realm pull failed for reason: request failed: (5) Input/output error. : exit status 5
```

When I run a manual realm pull command from the tools pod, with a debug flag, I see the issue is the certificate
```
[root@rook-ceph-tools-54474cfc96-qzlz9 /]# radosgw-admin realm pull --url=https://dev-rgw.myk8sclustername.k8s --access-key=xxxx --secret=xxxx --debug-rgw=20
2022-01-07T21:41:33.620+0000 7f0128fd9340 20 check_secure_mon_conn(): auth registy supported: methods=[2,1] modes=[2,1]
2022-01-07T21:41:33.620+0000 7f0128fd9340 20 check_secure_mon_conn(): method 1 is insecure
2022-01-07T21:41:33.625+0000 7f0062ffd700 20 reqs_thread_entry: start
2022-01-07T21:41:33.625+0000 7f0128fd9340 20 > HTTP_DATE -> Fri Jan  7 21:41:33 2022
2022-01-07T21:41:33.625+0000 7f0128fd9340 10 get_canon_resource(): dest=/admin/realm
2022-01-07T21:41:33.625+0000 7f0128fd9340 10 generated canonical header: GET
Fri Jan  7 21:41:33 2022
/admin/realm
2022-01-07T21:41:33.625+0000 7f0128fd9340 15 generated auth header: AWS REMqOXsrLWorS3l4dzs=:mVi+tVLXe9qwPKp0VSrt1rOd1/U=
2022-01-07T21:41:33.625+0000 7f0128fd9340 20 sending request to https://dev-rgw.myk8sclustername.k8s/admin/realm
2022-01-07T21:41:33.625+0000 7f0128fd9340 20 register_request mgr=0x5646f65b70e0 req_data->id=0, curl_handle=0x5646f65b7ab0
2022-01-07T21:41:33.625+0000 7f0062ffd700 20 link_request req_data=0x5646f644fc50 req_data->id=0, curl_handle=0x5646f65b7ab0
request failed: 2022-01-07T21:41:34.654+0000 7f0062ffd700 20 ERROR: msg->data.result=60 req_data->id=0 http_status=0
(5) Input/output error
2022-01-07T21:41:34.654+0000 7f0062ffd700 20 ERROR: curl error: Peer certificate cannot be authenticated with given CA certificates req_data->error_buf=SSL certificate problem: unable to get local issuer certificate
```
 
I see two ways we might solve this - 
1) Add a parameter to the CephObjectRealm CRD that would set the ceph parameter, --rgw_verify_ssl=false
or
2) In the rook pod(s) that are doing this, use the ca trust bundle that the host operating system uses.  
From what I can tell, I think the pods are using a standard ca bundle to trust.  We have added trust for our internal CA that generated the ssl certs we are using, but do not see it from within the rook pods.

**Comment by leseb** [comment]
@alimaredia is it something you can look into? Thanks

**Comment by BlaineEXE** [comment]
@eringet, you can set `rgw_verify_ssl` in the `rook-config-override` configmap or set it using the `ceph` CLI from the toolbox pod if you wish to solve the issue that way.

This option may not be ideal for all users, so we will keep examining a broadly useful way to get certificates into the RGW pod so RGW will trust connections from nodes.

**Comment by BlaineEXE** [comment]
I believe that in the scenario outlined by @eringet, all that needs to be done is add a volume and mount to the `rook-ceph-operator` deployment that puts the CA's used by the cluster into the right location in the operator pod. If we assume the CAs are present on host machines, simply using a hostPath volume mount in read-only mode should do the trick.

**Comment by BlaineEXE** [comment]
If RGW pods need the certificates (I'm not sure why they would right now), then we may have to make code changes to rook and/or identify a good CA injector utility that users could use.

**Comment by eringet** [comment]
Hi all, sorry for the confusion but did something actually get implemented for this issue?  I don't see any PRs, but it did get the Done in 1.9 status.  I don't see a PR or updates where we could add a volume with certs(s) to trust.  

Thank you,
Eringet

**Comment by travisn** [comment]
@eringet No implementation, the stale bot closed the issue since there was no reply. Would you mind reviewing @BlaineEXE 's comments above?

**Comment by eringet** [comment]
hi @travisn and @BlaineEXE , thank you for following up.  I am not sure now, if we did try setting rgw_verify_ssl in the rook_config_override or not, as it has been a while.  We are going to setup a test, but it won't be until early next week.  If that does allow the replication over ssl, then that solves my use case, I do not have a hard requirement for the certs to be verified.  I will comment back next week.  
Thanks!

**Comment by eringet** [comment]
hi all, thank you again for looking into this.  While it still might be nice to have a way to trust self signed ssl certs, setting rgw_verify_ssl in rook-config-override does work for my use case.  Thanks!!

**Comment by mgugino-uipath** [comment]
The rgw already supports ca injection via a spec value ca_bundle_ref (I believe).  It uses an init side-car to inject a CA bundle into the rgw pods at startup.  We could adapt this to other pods deployed via rook as well.

Unfortunately, injecting just the rgw pods is insufficient.  I'm not sure what other pod needs the CA's injected, possibly the mgr pods?  I assumed the communication was rgw<->rgw, but it might be mgr<->rgw for replication traffic.  Any thoughts?

**Comment by enduity** [comment]
This issue has also affected my deployment. I could work around it if values like extraVolumes and extraVolumeMounts existed for the operator pod, but they don't, so currently I have no way to solve this by just modifying the helm values. I will also have to turn verification off for now, but I would like to avoid this if at all possible.

**Comment by josephineSei** [comment]
This issue seems to also affect us. We have a rook cluster and rook ceph object store wich uses a certificate from an internal authority. We encounter this connectivity issue:
```
Warning  ReconcileFailed  9m12s
  (x3307 over 39d)  rook-ceph-object-controller  failed to reconcile CephObjectStore "rook-ceph/object-storage". failed to create object store deployments: failed to get COSI user "cosi": Get "https://object-storage-backend.stkt-x-preprod.cloudandheat.com/admin/user?format=json&uid=cosi": tls: failed to verify certificate: x509: certificate signed by unknown authority
``

We definitely want our certificates to be verified, so the setting of `rgw_verify_ssl` is not an option.

**Comment by BlaineEXE** [comment]
I believe this feature was already implemented here: https://github.com/rook/rook/pull/8492

**Comment by josephineSei** [comment]
Hi @BlaineEXE this is what is causing this issue.

I roll out a rook ceph cluster and the object store. With https://github.com/rook/rook/pull/8492 I can add a custam ca_bundle to the object store - but not to every other resource of the cluster. So when the operator tries to connect to the object store, the connection fails.

I need a way to provide the ca_bundle also to the operator.

**Comment by BlaineEXE** [comment]
Rook operator doesn't connect to the other services that RGW connects to, so I suspect some kind of disconnect between how the CephObjectStore's two TLS/CA configs work and the docs, or a misunderstanding. Without more information I can't determine the source of the disconnect though
