### ISSUE TITLE
--upgrade flag in external cluster should be capable of upgrading clients.

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#9589]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

--upgrade flag should be robust

**What is use case behind this feature:**

https://github.com/rook/rook/pull/9571#issuecomment-1012331479
The upgrade function doesn't seem to be that smart for now so it can update the new auth caps listed with the existing one, it only compares the value of the current cap with the `MIN_USER_CAP_PERMISSIONS`,
https://github.com/rook/rook/blob/3b415ea15a412c233e05a62be1b622dc7fe29cbe/deploy/examples/create-external-cluster-resources.py#L1105

**Comment by parth-gr** [comment]
@leseb 
I want to understand why[ MIN_USER_CAP_PERMISSIONS](https://github.com/rook/rook/blob/7bfa3205280ff2fd01e7f4ceabf88b0dfa0e8641/deploy/examples/create-external-cluster-resources.py#L342), is listed like this,

Do we need to have this?

And why `--rgw-pool-prefix` flag is there, what does it depict?

**Comment by parth-gr** [comment]
And for upgrading the caps, 
I am thinking to have a separate function for `gettingCaps()` for every user,

And so while using the upgrade we can get the information of current caps that are listed.

**Comment by leseb** [comment]
> @leseb I want to understand why[ MIN_USER_CAP_PERMISSIONS](https://github.com/rook/rook/blob/7bfa3205280ff2fd01e7f4ceabf88b0dfa0e8641/deploy/examples/create-external-cluster-resources.py#L342), is listed like this,
> 
> Do we need to have this?
> 
> And why `--rgw-pool-prefix` flag is there, what does it depict?

@aruniiird please help since you wrote this.

**Comment by aruniiird** [comment]
> @leseb I want to understand why[ MIN_USER_CAP_PERMISSIONS](https://github.com/rook/rook/blob/7bfa3205280ff2fd01e7f4ceabf88b0dfa0e8641/deploy/examples/create-external-cluster-resources.py#L342), is listed like this,

`MIN_USER_CAP_PERMISSIONS` provides a minimum set of permissions required for each item (`mgr` , `mon` or `osd`) for the given user entity(provided by `--run-as-user` flag). That means, the provided user, require at least (minimum) those permissions to do the needed operations on the given pool (provided by `--rgw-pool-prefix` flag).

The function `upgrade_user_permissions()`, checks whether the user exists (if user don't already exists we throw an error). Then it checks the current permissions set for each item (`mgr` , `mon`  and `osd`) and merges it with minimum permissions (set by `MIN_USER_CAP_PERMISSIONS`).

> 
> Do we need to have this?

Yes (IMO). Do we have any other way to get / set permissions for the given user?

> 
> And why `--rgw-pool-prefix` flag is there, what does it depict?
(@leseb  can answer better) My understanding is it is the pool name (by default it's name is set to `default` depicting the default pool name).

**Comment by parth-gr** [comment]
Thanks, @aruniiird for the information,
I don't think so `upgrade_user_permissions()` we are using for upgrading it with minimum permission as we directly create the users by running the script,
And as far as the upgrade function is concerned it should be used during the user's upgrades while upgrading.

Will be good if you can look at the changes and also review https://github.com/rook/rook/pull/9609 I did for the same.
