### ISSUE TITLE
Failed to create new file system '{...}': HTTP status code 500 for query filesystem: ''

### ISSUE THREAD

**Issue by mafzst** [rook/rook#959]
Hi all!

I've created a rook cluster on a kubeadm kubernetes cluster by following the docs.  

When I want to create my first file system with the toolbox pod by running `rookctl filesystem create --name influx` I run into this issue `failed to create new file system '{Name:influx PoolName:influx}': HTTP status code 500 for query filesystem: ''`

I've tried to get logs from API or OSD by running `kubectl logs -f <pod_name> -n rook` but the connection is refused

I'm a rook newbie so tell me if you need more infos and where to grab them

Thanks in advance

**Comment by jbw976** [comment]
Hi @mafzst, you had the right instincts to try to get the logs from the API pod.  That would give us more details about the 500 error you saw from the `rookctl filesystem create` command.  I'm not sure what's up with the connection refused error when trying to get the logs though, that'd odd.

Can you share the output from the following commands?
```
kubectl -n rook get pod -o wide
kubectl -n rook logs $(kubectl -n rook get pod | grep rook-api | awk '{print $1}')
```

**Comment by mafzst** [comment]
Hi @jbw976 

Thanks for your fast reply ;)

Here the outputs: 
```
▶ kubectl -n rook get pod -o wide
NAME                              READY     STATUS    RESTARTS   AGE       IP           NODE
rook-api-1081531-8mfw8            1/1       Running   0          24m       10.42.0.5    2.nodes.oma.ovh
rook-ceph-mgr0-1574136682-jxvbf   1/1       Running   0          1h        10.42.0.4    2.nodes.oma.ovh
rook-ceph-mon0-h1mqt              1/1       Running   0          1h        10.42.0.1    2.nodes.oma.ovh
rook-ceph-mon1-3zbc5              1/1       Running   0          1h        10.42.0.2    2.nodes.oma.ovh
rook-ceph-mon2-wknq3              1/1       Running   0          1h        10.42.0.3    2.nodes.oma.ovh
rook-ceph-osd-2n7r8               1/1       Running   0          1h        10.42.0.6    2.nodes.oma.ovh
rook-operator-3627264571-7tqpp    1/1       Running   0          1h        10.44.0.11   1.nodes.oma.ovh
rook-tools                        1/1       Running   0          28m       10.44.0.13   1.nodes.oma.ovh
```
```
▶ kubectl -n rook logs $(kubectl -n rook get pod | grep rook-api | awk '{print $1}')
Error from server: Get https://10.3.94.139:10250/containerLogs/rook/rook-api-1081531-8mfw8/rook-api: dial tcp 10.3.94.139:10250: getsockopt: connection refused
```

**Comment by galexrt** [comment]
The `kubectl logs ...` error should be an issue with the Kubelet on your cluster, could you run `kubectl get nodes` and make sure all nodes are in `Ready` state?

**Comment by mafzst** [comment]
Yes my node seems to be ok

```
▶ kubectl get nodes
NAME                   STATUS    AGE       VERSION
1.nodes.oma.ovh        Ready     7d        v1.7.3
2.nodes.oma.ovh        Ready     5d        v1.7.4
master.nodes.oma.ovh   Ready     7d        v1.7.3
```

**Comment by galexrt** [comment]
Do you have a firewall in place between the servers?
From the master server(s), can you run `curl https://2.nodes.oma.ovh:10250/metrics -k`. If the command does not work, there seems to be an issue between the connectivity between your Kubernetes apiserver to the node(s) kubelet.

**Comment by mafzst** [comment]
Nope I haven't any firewall

When I curl :
```
root@master:~# curl https://2.nodes.oma.ovh:10250/metrics -k --resolve 2.nodes.oma.ovh:10250:163.172.183.172
Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=metrics)
```
Sounds like a clue. 
I'll get a look to my role bindings

**Comment by galexrt** [comment]
The "error" is okay. It just tells you that you/curl accessed the kubelet as user `system:anonymous` page `/metrics` as a `GET` request. 

It seems weird, that the apiserver returns the error it can't connect to the kubelet port 10250, but you are able to reach it manually.

You can try running a tool like https://github.com/heptio/sonobuoy to check if there is any other issue within your K8s cluster that prevents you from being able to access the Pod logs.

**Comment by mafzst** [comment]
Ok I've a problem with the ClusterRoleBinding. It was in the wrong namespace. But it wasn't the root cause of the problem.

I'll get a look at sonobuoy.

Thanks for your help

**Comment by galexrt** [comment]
Are you able to access logs from other Pods than rook with the `kubectl logs` command?

**Comment by mafzst** [comment]
Yes.

I've have also access to rook operators's logs. But none of api, osd, mons or mgr

**Comment by mafzst** [comment]
I've ran the sonobuoy quick start pod. Lot's of stuff !

I've rapidly browse results but I didn't find suspicious things except

- `hosts/2.nodes.oma.ovh/configz.json` contains only `null` while other nodes contain a big JSON
- `hosts/2.nodes.oma.ovh/healthz.json` contains `{}` while others contains `{200}`

I'll try to schedule pods to an other node to see if this can explain the problem
(But not now, I need to sleep a bit :stuck_out_tongue:)

**Comment by mafzst** [comment]
Ok, my node 2 have a problem. It not seems to be rook.

I've scheduled the API on another node and it becomes reachable. I now can view logs and rookctl can post queries.

I'll try to 

- Reinstall the node 2

- Create a rook cluster again

**Comment by mafzst** [comment]
It works with a freshly installed node
