### ISSUE TITLE
If mons are on the same node one of them should be rescheduled to an available node

### ISSUE THREAD

**Issue by yagooar** [rook/rook#961]
I've ran into the following issue: I deployed rook on a 2-worker-node setup, and it worked fine. Then, I removed the node with IP `10.10.116.115` and added a new one. Since the new worker node has a different IP address, the `Node-Selectors` bit does not match anymore, thus scheduling the `mon` pod is impossible and fails.

I'm not sure where to start debugging this, or what solution would be possible to this problem. We constantly replace our worker nodes, as they are immutable and get created from scratch with new IPs every time.

```
Node-Selectors:	kubernetes.io/hostname=10.10.116.115
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  7m		3s		29	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: MatchNodeSelector (1).
```

**Comment by travisn** [comment]
@yagooar Rook is intended to be run on a least 3 worker nodes. The node selector pins the mons to specific nodes so that if the `dataDirHostPath` is used, the mons can survive a node restart.

If there are only two workers, two of the mons will be scheduled on the same node. If you lose/replace the worker with two mons, you will lose the mon quorum and will be difficult to recover the cluster. 

If there are at least three workers and you replace a worker, mon quorum is still maintained with two mons running. Rook will create a new mon to replace the old one without any issues.

**Comment by yagooar** [comment]
Thank you @travisn 

We will try to test our setup with one additional worker node. It would be great if this was documented somewhere, though. It's not obvious from reading the docs, that there is a quorum requirement.

Still, the issue seems to be a different one, at least this is how I understand it. It's not that `ceph` complains about the quorum, it's `kubernetes` who refuses to start the `mon` pod because it's supposed to go to a node with a specific ip address (which does not exist anymore).

**Comment by travisn** [comment]
I'll look into writing a doc on the behavior of the monitors, you're right it's missing. 

Does the rook-operator log show any errors? I would expect it to indicate either that it can't connect to perform a health check (quorum is lost), or that it fails to start a new mon (quorum is still available).

**Comment by DanKerns** [comment]
@travisn documenting mon functionality/requirements is a good thing. I wonder if we need a section on system requirements that talks about the number of nodes, disks, etc.

**Comment by travisn** [comment]
@DanKerns agreed, i was thinking about a whole topic that addresses all the areas of reliability and durability that should be considered when setting up the storage cluster.

**Comment by yagooar** [comment]
One more question: if 2 mons get scheduled on one node (because one node out of three becomes unavailable), and then the cluster becomes healthy again (with 3 nodes), shouldn't the operator make sure that one of the mons get re-scheduled on the third node?

Otherwise, making something like a rolling update of worker nodes requires additional logic, such as killing one of the two mons on one node so that it gets rescheduled on a different node, maybe one would even need to add some affinity settings to make it work.

Sounds a bit complicated right now to me, don't know how you have designed this to work. Thanks a lot for all your help and inputs!

**Comment by travisn** [comment]
@yagooar correct, one of the mons should be ideally rescheduled after the third node comes back. Currently that is not the case since a mon is only rescheduled when an issue is found with the quorum. I'll update the title of this issue to make that change.
