### ISSUE TITLE
rbd image locked by other nodes

### ISSUE THREAD

**Issue by yagooar** [rook/rook#964]
I've been working on implementing rook on top of our Kubernetes cluster. The MVP of it would be the following:

(Our cluster runs on Kubernetes 1.7.5, and has 3 worker nodes, A, B & C)

- a PVC is created
- a Postgres pod is scheduled on node A
- data is written in Postgres
- the pod affinity is changed to node B
- the pod gets terminated on node A, and boots on node B
- data created in the Postgres pod on node A is available in the pod on node B

Unfortunately, when the Postgres pod is getting scheduled on node B, it gets stuck in the `ContainerCreating` status.

Using `kubectl describe` on it, yield an interesting info:

```
Warning		FailedMount
MountVolume.SetUp failed for volume "pvc-a4e6099d-92e0-11e7-9cff-005056013fed" : 
rbd: image k8s-dynamic-pvc-a4e6099d-92e0-11e7-9cff-005056013fed-a4edd45c-92e0-11e7-901d-423157ab3bac is locked by other nodes
```

After researching a bit, I found that there is a lock in `rbd`, which only allows node A to access the ceph volume. 

If I manually remove the lock with `rbd -p pool_name lock remove image_id ID Locker`, then the pod will successfully start on node B and the data will be there.

Unless this is a bug, is there a way to make Kubernetes aware of having to unlock the rbd image? Thank you.

**Comment by kokhang** [comment]
@yagooar This is definitely a bug. During the fail-over, Kubernete should've issued an `Detach()` on nodeA and thus, it should have removed the lock. Here is the code. https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/rbd/rbd_util.go#L357

Perhaps some error happened after detaching but before unlocking? Could you look at the kubelet.log?

You might also be running into https://github.com/kubernetes/kubernetes/pull/50142 .

Either way, I am working on a Rook volume plugin (instead of using the in-tree RBD plugin) and with that, we will revisit all fencing/locking features.

**Comment by yagooar** [comment]
Thanks @kokhang 

It definitely doesn't work correctly. I created the pod on node A, then removed the deployment + pods altogether. Changed the manifest to ensure it gets scheduled on node B next time and when creating the deployment + pod, it hangs again.

This is what `kubelet` logged when deleting the postgres pod:

> Sep 07 13:25:42 stage-k8s-worker-f81bcb84 kubelet[25154]: I0907 13:25:42.589595   25154 reconciler.go:290] Volume detached for volume "pvc-fad1aa8b-93be-11e7-9a04-005056011868" (UniqueName: "kubernetes.io/rbd/13514e3a-93bf-11e7-9a04-005056011868-pvc-fad1aa8b-93be-11e7-9a04-005056011868") on node "10.10.116.117" DevicePath ""

But when starting on the new node, the following error is logged:

> Error: MountVolume.SetUp failed for volume "pvc-fad1aa8b-93be-11e7-9a04-005056011868" (UniqueName: "kubernetes.io/rbd/79b95229-93bf-11e7-9a04-005056011868-pvc-fad1aa8b-93be-11e7-9a04-005056011868") pod "postgres-deployment-537659254-5ms8x" (UID: "79b95229-93bf-11e7-9a04-005056011868") : rbd: image k8s-dynamic-pvc-fad1aa8b-93be-11e7-9a04-005056011868-fb4873c0-93be-11e7-8d76-2e7402dd35f9 is locked by other nodes

**Comment by yagooar** [comment]
I've tried different things, and the lock stays there no matter what I do. Unless there is a fix that will become available in a few days, how would one proceed with working around this problem?

I thought about watching pods wiht a volume claim to make sure the lock is removed when the pod dies, but that is a fairly complex workaround as it would require deploying a script / application that would follow the Kubernetes events through the API to see what's going on and what needs to be done.

**Comment by DanKerns** [comment]
@kokhang isn't this something we're specifically fixing with the flex volume plugin work?

**Comment by kokhang** [comment]
@yagooar This should've definitely have worked. One issue with the RBD plugin is that the `is locked by other nodes` message could be misleading. This also happens when you dont have the rbd (or ceph-tools) installed. https://github.com/kubernetes/kubernetes/pull/48457#issuecomment-324288319. Make sure that all nodes have the `rbd` tool installed. on debian, you can do `apt-get install ceph-commons`.

@DanKerns Using the flexvolume plugin means we will not rely on the in-tree rbd plugin. So yes, this scenario should work.

**Comment by kokhang** [comment]
@yagooar if you are feeling adventurous enough, you can try an early preview of the rook flexvolume plugin. Use these manifests: https://github.com/kokhang/rook/tree/rook-flex/cluster/examples/kubernetes but change this line https://github.com/kokhang/rook/blob/rook-flex/cluster/examples/kubernetes/rook-operator.yaml#L119 to `kokhang:rook:master` and this https://github.com/kokhang/rook/blob/rook-flex/cluster/examples/kubernetes/rook-operator.yaml#L123 to `kokhang`.

- Create the operator: `kubectl create -f rook-operator.yaml`

- Restart kubelet on all nodes. This is needed to load the flexvolume plugin. But as of 1.8, flexvolume will be dynamically discovered and loaded. So restart would not be required: https://github.com/kubernetes/community/pull/833

- Proceed with the creation of `rook-cluster.yaml` and `rook-storageclass.yaml`.

**Comment by yagooar** [comment]
Thank you @kokhang 

I tried the new flexvolume plugin and it works like a charm :)

If the flexvolume plugin is the future, I guess we should wait for it to become available once K8S 1.8 is out. What is your roadmap for this?

Another slightly unrelated question. I created all the rook resources. Moving pods around would be no issue and the volumes would get properly mounted every time. Then, to test that flow again, I removed all the resources and created them from scratch. Now only one `mon` pod will boot. If I delete the ceph data folder, it will work again.

The question is: how would one proceed in case of disaster recovery? Say, I know I have the data on a volume attached to the node / machine and I want to get rook running again without losing the data. Is this case documented somewhere? Thanks!

**Comment by bassam** [comment]
> If the flexvolume plugin is the future, I guess we should wait for it to become available once K8S 1.8 is out. What is your roadmap for this?

The flex volume will work for K8S 1.7 and 1.6 too but it will require a kubelet restart as @kokhang described above. The flex volume will be part of our 0.6 release (see https://github.com/rook/rook/blob/master/ROADMAP.md)

**Comment by jbw976** [comment]
> The question is: how would one proceed in case of disaster recovery? Say, I know I have the data on a volume attached to the node / machine and I want to get rook running again without losing the data. Is this case documented somewhere? Thanks!

That's actually a really good question.  We were having a conversation yesterday about the scope of #726 for the 0.6 timeframe.  Perhaps that's the scenario we should start with: you have data disks but your Rook config/metadata disk was destroyed.  How would you get the cluster going again and reuse the data?

It might be a good place to start with some documentation around that scenario as well as bug fixes to support/allow it in the Rook codebase.  For example, the OSD pod starting up path would probably just reformat the data disks since the config/metadata is gone, so things like that would need to be fixed.

Look for more updates/progress on #726 soon.

**Comment by koalalorenzo** [comment]
I just ran into the same problem. (with kubernetes 1.7.5) 
Do we know when the plugin will be released properly? Should I still fix it manually?

**Comment by sean-brandt** [comment]
Same issue here, as well. An idea on the 0.6 release plan/schedule would be very helpful.

**Comment by kokhang** [comment]
@koalalorenzo @sean-brandt unfortunately there could be a number of things that could raise this error. The first thing `rbd` plugin in kubernetes does is to call `rbd lock`. So any error would result in 'rbd image is locked by'. Common problems are rbd tools not installed in the node, rbd kernel modules not loaded, user secret is invalid, mon IP is not valid etc. There was a fix in kubernetes for 1.8 that just adds more information to this error. https://github.com/kubernetes/kubernetes/pull/48457.

WRT to the flexvolume plugin, im just cleaning and adding some unit tests. I have already manually tested on k8s v1.6-1.8. Im pushing this flexvolume PR to be merged end of this week at the latest.

**Comment by koalalorenzo** [comment]
I will wait for the plugin then :) Hopefully that will fix it... 
Is there a better way to debug it?

**Comment by alhafoudh** [comment]
Any news?

**Comment by koalalorenzo** [comment]
How long should we wait for this?

**Comment by kokhang** [comment]
@koalalorenzo @alhafoudh the PR is pretty much ready and has been reviewed thoroughly by core reviewers. I just need one more approval and it should be in. https://github.com/rook/rook/pull/882

@koalalorenzo about debugging rbd plugin, unfortunately the best way to just to look at the kubelet logs. Making sure you have the ceph-tools installed. But the new flexvolume should address this issues

**Comment by koalalorenzo** [comment]
@kokhang ETA for the flex volume? :) 👍 well done btw

**Comment by kokhang** [comment]
@koalalorenzo just as soon as @bassam reviews it and approves it. He is the only one left who requested a change. :)

**Comment by tomciaaa** [comment]
I am experiencing a similar issue with the image being locked after following the demo setup, and am getting similar kubelet. Importantly I'm also getting 'Permission denied (13)' in kubelet logs when it's trying to release the lock as well as corresponding access denied logs in ceph-mon logs for the rook-rook-user. Seems like others are running into the same issue as well: (e.g. #1045).

Maybe it's not worth the hassle of fixing this is flexplugin is the new way forward, but would still be interesting to see why kubelet is failing to get access to ceph.

**Comment by kokhang** [comment]
@koalalorenzo @tomciaaa @alhafoudh @sean-brandt @yagooar  The PR for rook to use a flexvolume plugin has just been merged. This will use a different way to attach rbd volumes and no longer will use the kubernetes rbd plugin. https://github.com/rook/rook/issues/432

You shouldnt see this issue anymore. Please report back if you see any more issues. Thanks
