### ISSUE TITLE
Missing OSD's (some raw devices have "BlueStore device label") but aren't in ceph-volume raw list

### ISSUE THREAD

**Issue by paul-bormans** [rook/rook#9646]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
On a "test" cluster with 10 nodes on which Ceph runs, each node having 3 additional raw devices, so expecting 30 OSD's in total we see only for some of the raw devices an OSD is run. About 50%, but each new run seems to yield different results. Also we observe that for some hosts all 3 devices are taken in to account while others use only 2 or 1 or sometimes even 0.

Taking a closer look using K9S reveals that osd-prepare pods quickly go into an error state, get restarted, fail again and then after some seconds these pods are completely removed (all logging gone) and replaced by new instances. The replacements do actually run stable but the device configuration is then somehow already into an invalid state (having bluestate label) but these are not in the ceph-volume raw listing.

We are assuming it's ceph operator that removes the osd-prepare pods?

**Expected behavior:**
- All raw devices that pass filtering as setup in cluster.yaml (storage section) should be taken into account.
- Failing osd-prepare pods are not removed but are kept so these can be inspected.
- Ability to recover without manual cleaning of volumes.

**How to reproduce it (minimal and precise):**
Spin a ceph cluster with multiple disks on a single host.

**File(s) to submit**:

* Cluster CR (custom resource) [cluster.txt](https://github.com/rook/rook/files/7933618/cluster.txt)
* Operator's logs [operator.log](https://github.com/rook/rook/files/7933607/operator.log)
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
* Kernel (e.g. `uname -a`): Linux dev84-ctl1m 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: GCP vm's with network disks attached
* Rook version (use `rook version` inside of a Rook Pod): 2022-01-25 12:31:51.071728 I | op-flags: failed to set flag "logtostderr". no such flag -logtostderr
rook: v1.7.7
go: go1.16.7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)
* Kubernetes version (use `kubectl version`): rke2-v1.21.5+rke2r1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE2
* Storage backend status: HEALTH_OK

**Comment by leseb** [comment]
If the prepare job fails into a loop, we need the initial (very first) error log that was produced. It should be in the operator's log.

**Comment by paul-bormans** [comment]
From a different test/run i'm seeing these sections in the operator logging
`Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-0/activate.monmap
 stderr: got monmap epoch 3
Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-0/keyring --create-keyring --name osd.0 --add-key AQCvEPBhdTqCKhAA5K7hKm8m3SsFt/OWNpLyJg==
 stdout: creating /var/lib/ceph/osd/ceph-0/keyring
added entity osd.0 auth(key=AQCvEPBhdTqCKhAA5K7hKm8m3SsFt/OWNpLyJg==)
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/keyring
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid 5c178eea-ddef-45ec-95df-fdd63d803f82 --setuser ceph --setgroup ceph
 stderr: 2022-01-25T15:01:04.389+0000 7ff03e348080 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _read_fsid unparsable uuid
 stderr: 2022-01-25T15:01:04.406+0000 7ff03e348080 -1 bluefs _replay 0x0: stop: uuid 00000000-0000-0000-0000-000000000000 != super.uuid 9ae8ccb6-2920-4533-96e3-523116b679b9, block dump:
 stderr: 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: *
 stderr: 00000ff0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: 00001000
 stderr: 2022-01-25T15:01:04.901+0000 7ff03e348080 -1 rocksdb: verify_sharding unable to list column families: NotFound:
 stderr: 2022-01-25T15:01:04.901+0000 7ff03e348080 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _open_db erroring opening db:
 stderr: 2022-01-25T15:01:05.407+0000 7ff03e348080 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error
 stderr: 2022-01-25T15:01:05.407+0000 7ff03e348080 -1  ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-0/: (5) Input/output error
--> Was unable to complete a new OSD, will rollback changes
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.0 --yes-i-really-mean-it
 stderr: purged osd.0
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 169, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 480, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid 5c178eea-ddef-45ec-95df-fdd63d803f82 --setuser ceph --setgroup ceph: exit status 1}
`

I'm also trying to see if upgrading from 1.7.7 to 1.8.3 (and csi updates as well) would resolve this issue from happening.

Paul

**Comment by paul-bormans** [comment]
Could this be same as? : https://github.com/rook/rook/issues/8023

**Comment by paul-bormans** [comment]
Running rook v1.8.3 (ceph 16.2.7) yields the same results so far.

```
2022-01-25 18:38:32.269143 I | op-osd: OSD orchestration status for node dev2-cmp1l is "failed"
2022-01-25 18:38:32.269193 E | op-osd: failed to provision OSD(s) on node dev2-cmp1l. &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to initialize osd: failed to run ceph-volume raw command. Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new f4a0ae55-0b96-4304-a4cc-2f2f3d13a341
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-0
Running command: /usr/bin/chown -R ceph:ceph /dev/sde1
Running command: /usr/bin/ln -s /dev/sde1 /var/lib/ceph/osd/ceph-0/block
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-0/activate.monmap
 stderr: got monmap epoch 3
Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-0/keyring --create-keyring --name osd.0 --add-key AQClQ/Bhr58XLRAACuf8ROY8okq1izdbu4HZaQ==
 stdout: creating /var/lib/ceph/osd/ceph-0/keyring
added entity osd.0 auth(key=AQClQ/Bhr58XLRAACuf8ROY8okq1izdbu4HZaQ==)
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/keyring
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid f4a0ae55-0b96-4304-a4cc-2f2f3d13a341 --setuser ceph --setgroup ceph
 stderr: 2022-01-25T18:38:30.769+0000 7f89304df080 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _read_fsid unparsable uuid
 stderr: 2022-01-25T18:38:30.786+0000 7f89304df080 -1 bluefs _replay 0x0: stop: uuid 00000000-0000-0000-0000-000000000000 != super.uuid 6f36f879-3c86-4ae1-8b46-abf13cc438c7, block dump:
 stderr: 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: *
 stderr: 00000ff0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: 00001000
 stderr: 2022-01-25T18:38:31.281+0000 7f89304df080 -1 rocksdb: verify_sharding unable to list column families: NotFound:
 stderr: 2022-01-25T18:38:31.281+0000 7f89304df080 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _open_db erroring opening db:
 stderr: 2022-01-25T18:38:31.783+0000 7f89304df080 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error
 stderr: 2022-01-25T18:38:31.783+0000 7f89304df080 -1 [0;31m ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-0/: (5) Input/output error[0m
--> Was unable to complete a new OSD, will rollback changes
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.0 --yes-i-really-mean-it
 stderr: purged osd.0
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 169, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 481, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid f4a0ae55-0b96-4304-a4cc-2f2f3d13a341 --setuser ceph --setgroup ceph: exit status 1}
```
[operator2.log](https://github.com/rook/rook/files/7936372/operator2.log)

**Comment by paul-bormans** [comment]
I have retested with:

[root@rook-ceph-osd-4-fc8d7c788-hffgr ceph]# ceph --version
ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)

And i can confirm that:
- rook 1.8.3 / 16.2.7 still have this issue  [operator.log](https://github.com/rook/rook/files/7940459/operator.log)
- rook 1.8.3 / 16.2.7 + bluefs_buffered_io = false does not experience this issue.  [operator-no-buffering.log](https://github.com/rook/rook/files/7940461/operator-no-buffering.log)

Thanks to @satoru-takeuchi for mentioning the containment!

Paul

**Comment by leseb** [comment]
We might consider adding `bluefs_buffered_io = false`as a default flag then...

**Comment by paul-bormans** [comment]
@leseb Well, i certainly can't make a usefull proposal about this since i'm too new when it comes to Rook and Ceph.

Notice we are running Centos7 (kernel 3.10) and we have 3 spinning disks attached to each host. Maybe that combination triggered the issue somehow.

I will be opening a ticket for this on the Ceph ticket repository as well to see if i can assist with further debugging.

One more this to mention, just an observation probably not related to this issue; on the earlier version of Ceph we ran the devices were provisioned using LVM, today on the new version the default appears to have changed to run bluefs directly on the raw devices. I'm not sure what the implications are on this change, i would need to dive in further.

Paul

**Comment by satoru-takeuchi** [comment]
I reported this problem in the following similar issue.
https://tracker.ceph.com/issues/51034#note-12

**Comment by satoru-takeuchi** [comment]
@paul-bormans Do you still have this issue? If so, could you try the patch mentioned in the following link?

https://lists.ceph.io/hyperkitty/list/dev@ceph.io/message/2Z2GXOUCAKCKVKCBIRGHZLGYUPU7YSIL/

I can create a customer Ceph container image, if necessary.

**Comment by kehao95** [comment]
In my case it seem to be metadata volumes didn't got removed during scale in the cluster. Then got reused for new OSD when scale out. Causing the errors.
