### ISSUE TITLE
Mount the ceph file system outside k8s

### ISSUE THREAD

**Issue by timclu** [rook/rook#966]
The device we used is not in the k8s clusters and is already added into the calico network.
We need to find a way to mount the ceph file system created by rook. 

Here are the rook cluster info
Services:
```
rook-api         10.1.212.181   <nodes>       8124:30005/TCP   
rook-ceph-mon0   10.1.48.109    <none>        6790/TCP        
rook-ceph-mon4   10.1.59.106    <none>        6790/TCP        
rook-ceph-mon5   10.1.239.33    <none>        6790/TCP        

```

Pods:
```
NAME                              READY     STATUS    RESTARTS   AGE       IP            NODE
rook-api-1255117824-13d7f         1/1       Running   0          7h        10.2.18.202   10.128.112.28
rook-ceph-mon0-wzg8d              1/1       Running   0          2d        10.2.20.200   10.128.112.26
rook-ceph-mon4-vg96c              1/1       Running   0          21d       10.2.18.229   10.128.112.28
rook-ceph-mon5-r2s2l              1/1       Running   0          2d        10.2.23.40    10.128.112.27
rook-tools                        1/1       Running   0          7h        10.2.21.5     10.128.112.26
```

The Pod IPs were used to mount the ceph monitors.
```
sudo mount -t ceph -o name=admin,secret=xxxxxxx 10.2.20.200:6790,10.2.18.229:6790,10.2.23.40:6790:/ /test
```
But we got this error message `mount error 5 = Input/output error`

The `dmseg | tail` shows:
```
[1853650.593672] libceph: wrong peer, want 10.2.20.200:6790/0, got 10.1.48.109:6790/0
[1853650.593698] libceph: mon0 10.2.20.200:6790 socket error on read
[1853660.609423] libceph: wrong peer, want 10.2.23.40:6790/0, got 10.1.239.33:6790/0
[1853660.609445] libceph: mon2 10.2.23.40:6790 socket error on read
[1853670.626070] libceph: wrong peer, want 10.2.20.200:6790/0, got 10.1.48.109:6790/0
[1853670.626085] libceph: mon0 10.2.20.200:6790 socket error on read
[1853680.641739] libceph: wrong peer, want 10.2.20.200:6790/0, got 10.1.48.109:6790/0
[1853680.641763] libceph: mon0 10.2.20.200:6790 socket error on read
[1853690.657344] libceph: wrong peer, want 10.2.18.229:6790/0, got 10.1.59.106:6790/0
[1853690.657368] libceph: mon1 10.2.18.229:6790 socket error on read

```
Does rook provide a way to mount the cephfs outside the k8s?

**Comment by jbw976** [comment]
Hi @timclu, what happens if you use the IP addresses of the mon services instead of the mon pods when you are running the `mount -t ceph` command?  the mons are supposed to be bound/listening on the service addresses, so I'm hoping that will help you.

**Comment by timclu** [comment]
Hi @jbw976, the limitation is that the device could not reach the service ip of mons. 
The service IPs(ClusterIP) are only available in k8s. This is why I try to use the pods IP instead of service ip.
If there is no officially design to expose the ceph to external device. Maybe I should find some workarounds.

**Comment by hunter** [comment]
Sounds like similar issues we faced with ceph-docker and using Ceph outside of the Kubernetes network (in our case for Openstack). The only real solution we found was to expose the pods on the hostnetwork.

**Comment by travisn** [comment]
agreed, sounds like we need #561 for hostnetwork

**Comment by timclu** [comment]
@travisn  is there any one help on this feature? @hunter?

**Comment by hunter** [comment]
Unfortunately we've not had the time to look at it yet

**Comment by timclu** [comment]
1. I'm not familiar with ceph. I'll take a look into this and see if I could contribure a PR.

2. Loop back into this issue, I thought my case was not complicated. 
My device is already added into calico network. So there is no problem to access the **`Pod IP`** of mons.
But I still could not mount CephFS on my device due to the mons ip mismatched.
If I could change the Ceph server to bind mons with **`Pod IP`** instead of **`ClusterIP`**. My problem could be solved.

**Comment by jbw976** [comment]
@timclu the purpose of #806 was to make Monitors IP addresses stable even when the pod is terminated and recreated with a new IP.  The service IP is consistent and will always point to the pod IP even if the pod IP changes.  This is very useful for a healthy cluster because all clients and daemons always know where to find the monitors.

This is the first scenario I've personally seen where a client wants to access the cluster storage, but can only reach pod IPs and not service IPs.  That type of setup was not taken into account in #806.  I'm interested if it's more common than we anticipated.  Do you encounter network setups for Kubernetes like that very often in your experience?

I'm trying to think of a workaround right now but I'm coming up short.  The monitor's identities are very tied to their service IP.  I was thinking you could manually edit the monitor config files to use the pod IP for everything, but I'm not certain that would result in a healthy cluster when you change the monitors IP (and therefore its identity) on the fly :(

It does seem like the host network support in #561 would be the best fit for you unfortunately.

**Comment by valentin2105** [comment]
I'm really interested too about mounting Rook's volumes to Backup purpose.
From a pod, it's possible to mount any volume already bounded to a PVC ? 

Thanks !

**Comment by timclu** [comment]
@jbw976 
Our system is not purely microservice now. It needs time to migrate all services into k8s. In this transition, We'll need to a way to access the file storage both inside and outside k8s. 

Now we used NFS to handle files in our system. Of course, services are no problem to access files with NFS (inside and outside k8s), but we met some performance issues. This issue made our system unstable. After evaluation, Rook + Cephfs would be a one of the solution in our case.

Back to the question :
**_`Do you encounter network setups for Kubernetes like that very often in your experience?`_**
I think the company who wants to use Rook and faces a service transition would probably suffer in this situation.

**Comment by bassam** [comment]
I wonder if exposing NFS outside the Rook cluster is a better approach than relying on hostNetwork support for this.

**Comment by jpds** [comment]
I feel that the fix for this one would be to make the monitor IPs of type `LoadBalancer` and then using something like http://metallb.universe.tf/ to externally expose them outside the cluster.

**Comment by ssube** [comment]
I'm trying to do this as well, specifically `rbd map`ping to some of the cluster hosts. The problem I'm facing is the unpredictable IPs used by the mon services and pods after they restart, so any updates break volumes elsewhere.

I tried creating a set of services to route traffic to the mons on predictable addresses:

```
apiVersion: v1               
kind: Service                
metadata:                    
  name: rbd-ceph-mon-a       
  namespace: rook-ceph       
spec:                        
  selector:                  
    app: rook-ceph-mon       
    mon: a                   
    mon_cluster: rook-ceph   
    rook_cluster: rook-ceph  
  ports:                     
    - protocol: TCP          
      port: 6790             
      targetPort: 6790       
  clusterIP: 10.96.172.200   
                             
---                          
                             
apiVersion: v1               
kind: Service                
metadata:                    
  name: rbd-ceph-mon-b       
  namespace: rook-ceph       
spec:                        
  selector:                  
    app: rook-ceph-mon       
    mon: b              
    # etc...
```

But running `rbd` commands prints this error:

```
2019-02-08 20:36:29.558137 7fc4ddae20c0  0 monclient(hunting): authenticate timed out after 300
2019-02-08 20:36:29.558156 7fc4ddae20c0  0 librados: client.cerberus authentication error (110) Connection timed out
rbd: couldn't connect to the cluster!
```

and `dmesg | tail` shows:

```
[268512.427254] libceph: wrong peer, want 10.96.172.200:6790/0, got 10.104.8.149:6790/0 
[268512.427256] libceph: mon0 10.96.172.200:6790 wrong peer at address                  
[268513.418913] libceph: wrong peer, want 10.96.172.200:6790/0, got 10.104.8.149:6790/0 
[268513.418914] libceph: mon0 10.96.172.200:6790 wrong peer at address                  
[268514.378607] libceph: wrong peer, want 10.96.172.210:6790/0, got 10.106.72.222:6790/0
[268514.378609] libceph: mon1 10.96.172.210:6790 wrong peer at address                  
[268515.466684] libceph: wrong peer, want 10.96.172.210:6790/0, got 10.106.72.222:6790/0
[268515.466685] libceph: mon1 10.96.172.210:6790 wrong peer at address                  
```

It looks like the traffic is getting to the mons, but they are identified by their pod IP, so it fails. Is it possible to configure around this?

**Comment by travisn** [comment]
@ssube I would recommend the following configuration to get this working:
- In operator.yaml set `ROOK_MON_OUT_TIMEOUT` to something really large. This way the mons will never be automatically failed over and you can maintain the same set of mons. 
- In cluster.yaml set `hostNetwork: true`, which will give the mons the IP of the host machine

**Comment by conet** [comment]
> In cluster.yaml set hostNetwork: true, which will give the mons the IP of the host machine

Is it possible to do this for an existing cluster? I'm using `v1.0.0`, changed `hostNetwork: false` to `hostNetwork: true` but only the OSDs were properly recreated, the MONs still do no use the host network, I also tried to failover a MON to get it recreated only to find that it still did not use the host network. I'm trying to mount a cephfs from outside of the cluster.

**Comment by bogeit** [comment]
You can do these steps to meet your needs:
1. Create a cephfs by referring to https://rook.github.io/docs/rook/v0.9/ceph-filesystem.html
2, modify the hostNetwork: true in cluster.yaml, the default is:
   Network:
     # toggle to use hostNetwork
     hostNetwork: false

**Comment by conet** [comment]
@bogeit I did that:
```
kubectl get cephclusters.ceph.rook.io rook-ceph -n rook-ceph -o yaml
...
  network:
    hostNetwork: true
...
```
But the mon pods are still not using host network. The osd pods are recreated and use it but not the mons:

```
$ kubectl get pod rook-ceph-osd-0-6bb8d48b7b-5wpbv -n rook-ceph -o yaml | grep hostNetwork
  hostNetwork: true
$ kubectl get pod rook-ceph-mon-e-5c64cc68b8-xp2mz -n rook-ceph -o yaml | grep hostNetwork
$
```

Operator logs mention changing osds but never touch mons, from what I know for mounting I need the mons to be running on the host network, are you sure that toggling this flag is supported for existing clusters?

**Comment by bogeit** [comment]
@conet       
If this is the case, you can edit the service directly and change the type: ClustIP to NodePort.

**Comment by godocean** [comment]
@conet 
Did you resolve it? I met the same issue as you, could you give me some guidance if you have solved it successfully?
Thank you.

**Comment by conet** [comment]
I ended up abandoning the idea (and the project after a failed upgrade).

**Comment by zerols** [comment]
Is this possible ?   i found some related, he changed cluster.yaml 
network:
  hostNetwork: true
but i not found this key in cluster.yaml

**Comment by travisn** [comment]
@zerols A while ago the setting for host networking changed to:
```yaml
network:
  provider: host
```

And with host networking, this is most commonly the way cephfs can be exposed outside the cluster. Other network solutions may be possible now as well such as multus.

**Comment by zerols** [comment]
i had change cluster.yaml and apply, but pod mon don't work, maybe because of i had install kube-multus-ds and whereabouts, i'm not sure is there  connection between.
``` 
❯ kubectl get pods -n kube-system -o wide | grep -E 'multus|where'
kube-multus-ds-9skxf              1/1     Running             13         70d     192.168.20.226   node226   <none>           <none>
kube-multus-ds-lvk4b              1/1     Running             9          167d    192.168.20.223   node223   <none>           <none>
kube-multus-ds-r76nk              1/1     Running             19         167d    192.168.20.229   node229   <none>           <none>
kube-multus-ds-snz7c              1/1     Running             44         184d    192.168.20.228   node228   <none>           <none>
kube-multus-ds-sqv7g              1/1     Running             28         176d    192.168.20.222   node222   <none>           <none>
kube-multus-ds-z26w6              1/1     Running             49         184d    192.168.20.227   node227   <none>           <none>
whereabouts-b5t25                 1/1     Running             9          167d    192.168.20.223   node223   <none>           <none>
whereabouts-h8wj9                 1/1     Running             19         167d    192.168.20.229   node229   <none>           <none>
whereabouts-hqxbz                 1/1     Running             13         70d     192.168.20.226   node226   <none>           <none>
whereabouts-pjccs                 1/1     Running             18         169d    192.168.20.228   node228   <none>           <none>
whereabouts-r79j4                 1/1     Running             29         169d    192.168.20.227   node227   <none>           <none>
whereabouts-t2nb5                 1/1     Running             10         169d    192.168.20.222   node222   <none>           <none>
``` 
![image](https://user-images.githubusercontent.com/35661759/172531744-ef78e90e-e9aa-4cf1-8013-b0a3a99498b4.png)
pod logs:
``` 
[mds.myfs-b{0:94113} state up:active seq 3317 join_fscid=1 addr [v2:10.244.1.99:6800/1873726914,v1:10.244.1.99:6801/1873726914] compat {c=[1],r=[1],i=[7ff]}]



debug 2022-06-08T04:32:04.189+0000 7f6832e40880  0 mon.a@-1(???).osd e58 crush map has features 3314933000852226048, adjusting msgr requires
debug 2022-06-08T04:32:04.189+0000 7f6832e40880  0 mon.a@-1(???).osd e58 crush map has features 288514051259236352, adjusting msgr requires
debug 2022-06-08T04:32:04.189+0000 7f6832e40880  0 mon.a@-1(???).osd e58 crush map has features 288514051259236352, adjusting msgr requires
debug 2022-06-08T04:32:04.189+0000 7f6832e40880  0 mon.a@-1(???).osd e58 crush map has features 288514051259236352, adjusting msgr requires
cluster 2022-06-07T07:25:12.363227+0000 mgr.b (mgr.94107) 7154 : cluster [DBG] pgmap v7149: 65 pgs: 65 active+clean; 79 KiB data, 21 MiB used, 96 GiB / 96 GiB avail
audit 2022-06-07T07:25:12.517440+0000 mon.a (mon.0) 3468 : audit [INF] from='mgr.94107 10.244.5.234:0/1283469665' entity='mgr.b' cmd=[{"prefix":"config rm","who":"mgr","name":"mgr/rbd_support/b/mirror_snapshot_schedule"}]: dispatch
audit 2022-06-07T07:25:12.517557+0000 mon.a (mon.0) 3469 : audit [INF] from='mgr.94107 10.244.5.234:0/1283469665' entity='mgr.b' cmd=[{"prefix":"config rm","who":"mgr","name":"mgr/rbd_support/b/trash_purge_schedule"}]: dispatch
debug 2022-06-08T04:32:04.189+0000 7f6832e40880  1 mon.a@-1(???).paxosservice(auth 1..52) refresh upgraded, format 0 -> 3
debug 2022-06-08T04:32:04.193+0000 7f6832e40880 -1  Processor -- bind unable to bind to v2:10.107.89.244:3300/0: (99) Cannot assign requested address
debug 2022-06-08T04:32:04.193+0000 7f6832e40880 -1  Processor -- bind was unable to bind. Trying again in 5 seconds
debug 2022-06-08T04:32:09.193+0000 7f6832e40880 -1  Processor -- bind unable to bind to v2:10.107.89.244:3300/0: (99) Cannot assign requested address
debug 2022-06-08T04:32:09.193+0000 7f6832e40880 -1  Processor -- bind was unable to bind. Trying again in 5 seconds
debug 2022-06-08T04:32:14.193+0000 7f6832e40880 -1  Processor -- bind unable to bind to v2:10.107.89.244:3300/0: (99) Cannot assign requested address
debug 2022-06-08T04:32:14.193+0000 7f6832e40880 -1  Processor -- bind was unable to bind after 3 attempts: (99) Cannot assign requested address
debug 2022-06-08T04:32:14.193+0000 7f6832e40880 -1 unable to bind monitor to [v2:10.107.89.244:3300/0,v1:10.107.89.244:6789/0]
``` 
info ns rook-ceph 
``` 
❯ kubectl get pods -n rook-ceph -o wide
NAME                                            READY   STATUS             RESTARTS   AGE   IP               NODE      NOMINATED NODE   READINESS GATES
csi-cephfsplugin-9jpgc                          3/3     Running            0          35m   192.168.20.223   node223   <none>           <none>
csi-cephfsplugin-cxbxn                          3/3     Running            0          35m   192.168.20.229   node229   <none>           <none>
csi-cephfsplugin-fvp9p                          3/3     Running            0          35m   192.168.20.228   node228   <none>           <none>
csi-cephfsplugin-k2q6f                          3/3     Running            0          35m   192.168.20.226   node226   <none>           <none>
csi-cephfsplugin-kxv6n                          3/3     Running            0          35m   192.168.20.227   node227   <none>           <none>
csi-cephfsplugin-provisioner-7d6b6b6b45-nkfd8   6/6     Running            0          35m   10.244.0.21      node227   <none>           <none>
csi-cephfsplugin-provisioner-7d6b6b6b45-xg4wz   6/6     Running            0          35m   10.244.1.108     node228   <none>           <none>
csi-rbdplugin-6c2vf                             3/3     Running            0          35m   192.168.20.227   node227   <none>           <none>
csi-rbdplugin-pj558                             3/3     Running            0          35m   192.168.20.228   node228   <none>           <none>
csi-rbdplugin-provisioner-6c6f4f67c9-c5mk7      6/6     Running            0          35m   10.244.5.72      node226   <none>           <none>
csi-rbdplugin-provisioner-6c6f4f67c9-nnlrs      6/6     Running            0          35m   10.244.0.20      node227   <none>           <none>
csi-rbdplugin-rmgm7                             3/3     Running            0          35m   192.168.20.223   node223   <none>           <none>
csi-rbdplugin-sg5tb                             3/3     Running            0          35m   192.168.20.226   node226   <none>           <none>
csi-rbdplugin-tx5j4                             3/3     Running            0          35m   192.168.20.229   node229   <none>           <none>
rook-ceph-mon-a-6c77d694d5-6lb7g                0/1     CrashLoopBackOff   10         31m   192.168.20.226   node226   <none>           <none>
rook-ceph-mon-b-85f5978db-g77kj                 1/1     Running            0          23m   192.168.20.227   node227   <none>           <none>
rook-ceph-mon-c-6d8ddb8f9d-n4nf8                0/1     CrashLoopBackOff   7          12m   192.168.20.223   node223   <none>           <none>
rook-ceph-operator-7997c6b75b-pm2wv             1/1     Running            0          35m   10.244.5.69      node226   <none>           <none>
rook-ceph-tools-6944779c47-ssblr                1/1     Running            0          35m   10.244.0.22      node227   <none>           <none>
```

**Comment by travisn** [comment]
@zerols Applying the network settings is only expected to work in new clusters. Updating an existing cluster with different network settings isn't generally possible.

**Comment by voarsh2** [comment]
> @zerols Applying the network settings is only expected to work in new clusters. Updating an existing cluster with different network settings isn't generally possible.

Well, that's a shame...... how would one go about migration a cluster to a freshly installed one with host networking? That sounds like a huge pain, let alone expensive for large ceph clusters, extra hardware........... why can't it be in in-place?

**Comment by travisn** [comment]
> > @zerols Applying the network settings is only expected to work in new clusters. Updating an existing cluster with different network settings isn't generally possible.
> 
> Well, that's a shame...... how would one go about migration a cluster to a freshly installed one with host networking? That sounds like a huge pain, let alone expensive for large ceph clusters, extra hardware........... why can't it be in in-place?

The main complication is the [mon identity is tied to its IP address](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/#monitor-identity). 

It may be possible to convert the cluster from non-host networking to host networking by updating the host networking setting, then triggering [mon failover](https://rook.io/docs/rook/latest/Storage-Configuration/Advanced/ceph-mon-health/#failing-over-a-monitor) to get a new mon created with the host networking. But what we need to verify is that the existing mons won't be put in a broken state during that conversion. If you want to discuss more, how about creating a new [discussion item](https://github.com/rook/rook/discussions)?

**Comment by blackliner** [comment]
I am trying out if the migration from `hostNetwork: false` to `hostNetwork: true` works.
- First challenge were the rgw that were on the same host ad all had the default port 80. So needed to manually update them and make sure they have unique ports, i.e. 1080, 2080, 3080 ... (don't forget to update any users of your rgw endpoints!)
- Now I deleted one MON, let 10min pass and let the operator recreate it. And the new pod had `hostNetwork: true`, no issues so for the first one. I think this was because I also got operator messages about not putting multiple MONs on the same node etc. (it is a 3 node test cluster, but I had `allowMultiplePerNode: true`)
- The other two MON did not recover after deletion, but this was a good start: `kubectl rook-ceph mons restore-quorum <healthy_mon_character>` from https://rook.io/docs/rook/latest/Troubleshooting/disaster-recovery/#restoring-mon-quorum
Unfortunately, something within the operator blocks it from recreating more MONs
    ```
    2023-07-24 07:30:23.468085 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: refusing to deploy 3 monitors on the same host with host networking and allowMultiplePerNode is true. only one monitor per node is allowed
    2023-07-24 07:30:36.742611 I | op-mon: adding mons. currently 1 mons are in quorum and the desired count is 3.
    2023-07-24 07:30:36.754976 I | op-mon: created canary deployment rook-ceph-mon-e-canary
    2023-07-24 07:30:36.764371 I | op-mon: waiting for canary pod creation rook-ceph-mon-e-canary
    2023-07-24 07:30:36.774790 I | op-mon: created canary deployment rook-ceph-mon-f-canary
    2023-07-24 07:30:36.788326 I | op-mon: waiting for canary pod creation rook-ceph-mon-f-canary
    2023-07-24 07:30:41.778964 I | op-mon: canary monitor deployment rook-ceph-mon-e-canary scheduled to metal03
    2023-07-24 07:30:41.778978 I | op-mon: mon e assigned to node metal03
    2023-07-24 07:30:41.801357 I | op-mon: canary monitor deployment rook-ceph-mon-f-canary scheduled to metal02
    2023-07-24 07:30:41.801367 I | op-mon: mon f assigned to node metal02
    2023-07-24 07:30:41.809311 I | op-mon: cleaning up canary monitor deployment "rook-ceph-mon-e-canary"
    2023-07-24 07:30:41.818659 I | op-mon: cleaning up canary monitor deployment "rook-ceph-mon-f-canary"
    2023-07-24 07:30:42.658278 I | op-mon: creating mon e
    2023-07-24 07:30:42.660716 I | op-mon: ensuring the clusterIP for mon "g" is "192.168.1.112"
    2023-07-24 07:30:42.662164 W | op-mon: failed to check mon health. failed to init mon services: failed to create mon service: failed to create service for mon g: failed to create service rook-ceph-mon-g. Service "rook-ceph-mon-g" is invalid: spec.clusterIPs: Invalid value: []string{"192.168.1.112"}: failed to allocate IP 192.168.1.112: the provided IP (192.168.1.112) is not in the valid range. The range of valid IPs is 10.233.0.0/18
    2023-07-24 07:31:27.983251 I | op-mon: adding mons. currently 1 mons are in quorum and the desired count is 3.
    2023-07-24 07:31:28.002005 I | op-mon: created canary deployment rook-ceph-mon-h-canary
    2023-07-24 07:31:28.011086 I | op-mon: waiting for canary pod creation rook-ceph-mon-h-canary
    ```
- To be continued...

**Comment by travisn** [comment]
Did you change `mon.allowMultiplePerNode` to `false`? The first error looks like it's related to this, but then a later error seems to indicate that was resolved and is attempting to continue with the new mons.
