### ISSUE TITLE
Error mounting device (FS): running modprobe args: [ceph]

### ISSUE THREAD

**Issue by snagiel** [rook/rook#9671]
**Is this a bug report or feature request?**
* Bug Report

**Expected behavior:**
Pod with storage class utilizing Ceph FS (e.g. Elasticsearch) starts successfully and mounts the volume.

**Deviation from expected behavior:**
Pod stuck in init phase and reports:

`Warning  FailedMount             3s (x6 over 20s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-6bf68acb-b152-4161-9abe-c2e1f48a4823" : rpc error: code = Internal desc = an error (exit status 1) occurred while running modprobe args: [ceph]`

**How to reproduce it (minimal and precise):**
Note: This seems to be identical (or very similar) to issue [8575](https://github.com/rook/rook/issues/8575)

I am configuring a Rook-Ceph cluster on a single node test cluster, specifying a shared filesystem and then deploying a test app (Elasticsearch) that uses the storage class representing this filesystem. Using the same VM/node, this test works successfully with Minikube. However, with K3D, I'm seeing a different behavior.

The Ceph cluster and the filesystem seems to be healthy:

```shell
sh-4.4$ ceph status
  cluster:
    id:     b3ac5ec0-7ce6-4215-adb3-21a0bc7e8628
    health: HEALTH_OK
 
  services:
    mon: 1 daemons, quorum a (age 109s)
    mgr: a(active, since 51s)
    mds: 1/1 daemons up, 1 hot standby
    osd: 1 osds: 1 up (since 36s), 1 in (since 67s)
 
  data:
    volumes: 1/1 healthy
    pools:   3 pools, 65 pgs
    objects: 22 objects, 2.3 KiB
    usage:   5.1 MiB used, 20 GiB / 20 GiB avail
    pgs:     65 active+clean
 
  io:
    client:   853 B/s rd, 1 op/s rd, 0 op/s wr
 
sh-4.4$ ceph fs ls
name: solo-fs, metadata pool: solo-fs-metadata, data pools: [solo-fs-data0 ]
```
... yet the Elasticsearch nodes fail to start up and report:

`Warning  FailedMount             3s (x6 over 20s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-6bf68acb-b152-4161-9abe-c2e1f48a4823" : rpc error: code = Internal desc = an error (exit status 1) occurred while running modprobe args: [ceph]`

Similarly, I saw related messages in the `csi-cephfsplugin` pod/container:

```shell
$ kubectl -n rook-ceph logs csi-cephfsplugin-frczq -c csi-cephfsplugin | less
E0128 01:25:24.532971       1 nodeserver.go:180] ID: 7 Req-ID: 0001-0009-rook-ceph-0000000000000001-24d23ebf-7fd9-11ec-baef-8e0d76d0d315 failed to mount volume 0001-0009-rook-ceph-0000000000000001-24d23ebf-7fd9-11ec-baef-8e0d76d0d315: an error (exit status 1) occurred while running modprobe args: [ceph] Check dmesg logs if required.
E0128 01:25:24.533008       1 utils.go:185] ID: 7 Req-ID: 0001-0009-rook-ceph-0000000000000001-24d23ebf-7fd9-11ec-baef-8e0d76d0d315 GRPC error: rpc error: code = Internal desc = an error (exit status 1) occurred while running modprobe args: [ceph]
E0128 01:25:25.127449       1 nodeserver.go:180] ID: 9 Req-ID: 0001-0009-rook-ceph-0000000000000001-24d23ebf-7fd9-11ec-baef-8e0d76d0d315 failed to mount volume 0001-0009-rook-ceph-0000000000000001-24d23ebf-7fd9-11ec-baef-8e0d76d0d315: an error (exit status 1) occurred while running modprobe args: [ceph] Check dmesg logs if required.
...
```

Per @Madhu-1's advice in  [8575](https://github.com/rook/rook/issues/8575), I confirmed I am able to run `sudo modprobe ceph` on the host node without any issues, and verified it's installed:

```shell
$ find /lib/modules/$(uname -r) -type f -name '*.ko*' | grep ceph
/lib/modules/5.15.9-1.el7.elrepo.x86_64/kernel/fs/ceph/ceph.ko
/lib/modules/5.15.9-1.el7.elrepo.x86_64/kernel/net/ceph/libceph.ko
```

I'm happy to share any other configurations/log files that may help. Thanks!

**Environment**:
* OS (e.g. from /etc/os-release): `CentOS 7`
* Kernel (e.g. `uname -a`): `Linux ip-10-114-154-203.evoforge.org 5.15.9-1.el7.elrepo.x86_64 #1 SMP Thu Dec 16 09:01:13 EST 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: `AWS EC2`
* Rook version (use `rook version` inside of a Rook Pod): `rook: v1.8.2`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
* Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+k3s1", GitCommit:"ac70570999c566ac3507d2cc17369bb0629c1cc0", GitTreeState:"clean", BuildDate:"2021-11-29T16:40:13Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `K3D`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `HEALTH_OK`

**Comment by snagiel** [comment]
Also per [8575](https://github.com/rook/rook/issues/8575), I saw @Preisschild's comment:

> FWIW, i did set agent.libModulesDirPath (in the operator helm values) to /run/current-system/kernel-modules/lib/modules

... but I don't see that documented as a variable at https://rook.io/docs/rook/v1.8/helm-operator.html?

**Comment by Madhu-1** [comment]
@snagiel the `agent.libModulesDirPath` is for Rook flex its not applicable  for cephcsi. can you please exec into the csi-cephfsplugin container and run the mod probe manually and if it works?

**Comment by snagiel** [comment]
Hmm...

```shell
[root@k3d-elasticrypt-server-0 /]# modprobe ceph
modprobe: FATAL: Module ceph not found in directory /lib/modules/5.15.9-1.el7.elrepo.x86_64
[root@k3d-elasticrypt-server-0 /]# ls -l /lib/modules
total 0
```

... yet when I execute this directly on the host/node (as captured in the ticket above), that path exists and the module is available. So does this suggest I need to mount the `/lib/modules/5.15.9-1.el7.elrepo.x86_64` directory as a volume for the K3D cluster for all the modules to be available? Or maybe configure it somehow in Rook similar to the `agent.libModulesDirPath` variable?

**Comment by Madhu-1** [comment]
I haven't tried k3d no idea about it.

**Comment by snagiel** [comment]
The comment above helped point me in the right direction, and made me realize that this `csi-cephfsplugin` container required access to the list of available modules, which by default is not exposed to containers running within the k3d cluster. To fix that, you can mount it as a volume when launching the k3d cluster, e.g.

```shell
$ k3d cluster create my-cluster --servers-memory 16g --volume /lib/modules/:/lib/modules/:shared@all --volume /tmp/kubelet/pods:/var/lib/kubelet/pods:shared@all
```

(The other volume being mounted here relates to another problem discovered earlier, related to shared mounts; see [835](https://github.com/rancher/k3d/issues/835).)

If there is a "tips" section somewhere in Rook documentation land for specific k8s distros, let me know and I'm happy to contribute an update/MR.

**Comment by mvtab** [comment]
For anyone running into this with the latest example deployment, uncomment the following lines in operator.yaml:
```yaml
184   CSI_RBD_PLUGIN_VOLUME: |
185    - name: lib-modules
186      hostPath:
187        path: /run/current-system/kernel-modules/lib/modules/
188    - name: host-nix
189      hostPath:
190        path: /nix
```
It fixed the problem instantly for me.
