### ISSUE TITLE
Add ObservedGeneration to our status field?

### ISSUE THREAD

**Issue by leseb** [rook/rook#9673]
Using an `ObservedGeneration` field in our status field could be a piece of useful information to share on where the controller loop has left off. For instance, if the spec is updated by the user and the controller is reconciling, we can determine that the controller is working by looking at the Progressing state but also on the `ObservedGeneration`. It will be more precise and we know that the controller might be behind. There is also the case where the operator is down and the spec is updated, so the reconcile hasn't run yet. By comparing the `Generation` and the `ObservedGeneration` (set by the controller), we can determine that the desired state hasn't been fulfilled yet.

**Comment by travisn** [comment]
Will this help us skip reconciles that aren't necessary or what is the goal? I'd rather reconcile too often than skip reconciles. Particularly on operator restart it's good to have a full reconcile of all CRs.

**Comment by leseb** [comment]
The goal wouldn't so much of skipping reconciles but giving a good indication of the state of the reconcile. Essentially if `Generation` and `ObservedGeneration` are identical we know we have achieved the desired state, if they don't match then we don't. It's a more accurate way to surface that the reconcile is up to date and that the desired state has been achieved.

Makes sense?

**Comment by travisn** [comment]
Sounds good if it's for more accurate status on the reconcile.
