### ISSUE TITLE
rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-xxx External provisioner is provisioning volume for claim "claim_name""

### ISSUE THREAD

**Issue by manasjain0699** [rook/rook#9681]
getting the following error while looking at logs. not able to attach the volume to the new pods. 
already attached pods is working fine 

![test](https://user-images.githubusercontent.com/75062591/151762262-677a1e4a-0967-49c8-852a-3b577afeb79d.jpg)

any help would be appreciated

**Comment by Madhu-1** [comment]
@manasjain0699 is the ceph cluster healthy? what are the Rook and cephcsi versions you are using?
