### ISSUE TITLE
make codegen is not working

### ISSUE THREAD

**Issue by parth-gr** [rook/rook#9689]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I can see CI failing in my 2 recent PR  https://github.com/rook/rook/pull/9550, https://github.com/rook/rook/pull/9687
With the same error, in both the PRs I am updating the CR fields.
And running `make crds` and `make codegen`.
I guess the `make codegen` is not working as expected as I cannot see `pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go` 
getting updated.

Error:
For canary-integration CI: `https://github.com/rook/rook/runs/5022090325?check_suite_focus=true`

```
est_demo_mon
++ wait_for_daemon 'kubectl -n rook-ceph exec rook-ceph-tools-6c98756b79-l88xj -- ceph --connect-timeout 3 -s | grep -sq quorum'
++ timeout=90
++ daemon_to_test='kubectl -n rook-ceph exec rook-ceph-tools-6c98756b79-l88xj -- ceph --connect-timeout 3 -s | grep -sq quorum'
++ '[' 90 -ne 0 ']'
++ eval kubectl -n rook-ceph exec rook-ceph-tools-6c98756b79-l88xj -- ceph --connect-timeout 3 -s '|' grep -sq quorum
+++ kubectl -n rook-ceph exec rook-ceph-tools-6c98756b79-l88xj -- ceph --connect-timeout 3 -s
+++ grep -sq quorum
++ return 0
+ return
+ test_demo_mgr
++ wait_for_daemon 'kubectl -n rook-ceph exec rook-ceph-tools-6c98756b79-l88xj -- ceph --connect-timeout 3 -s | grep -sq '\''mgr:'\'''
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by travisn** [comment]
I'm not able to repro this and the CI for #9550 and #9687 looks ok now for the codegen and make crds.

**Comment by parth-gr** [comment]
Thanks, closing as it is not an issue.
