### ISSUE TITLE
AKS reports: Detected the use of APIs that will be deprecated in Kubernetes v1.22

### ISSUE THREAD

**Issue by brovoca** [rook/rook#9692]
**Is this a bug report or feature request?**

* Bug Report

**Deviation from expected behavior:**

Deprecated APIs appear to be used in either Rook 1.8.0 or 1.8.3. Unable to determine the version which caused this warning to appear as we upgraded the same day, but most likely 1.8.0 given the last seen timestamp in the image below. Madhu R. mentioned that this check seems to look wrong [operator/ceph/csi/spec.go#L233-L253](https://github.com/rook/rook/blob/d24eab2229a73a844ab8c5b3db9066e52051baee/pkg/operator/ceph/csi/spec.go#L233-L253).

![image](https://user-images.githubusercontent.com/95472556/152165182-eb3c0f75-f2dd-4524-99fa-896ba08b4474.png)

**Expected behavior:**

Deprecated APIs should not be used.

**How to reproduce it (minimal and precise):**

Deploy a cluster on AKS and install Rook-Ceph.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary: [cluster-release.yaml](https://github.com/rook/rook/files/7986898/cluster-release.txt) (FluxCD)
* Operator's logs, if necessary [rook-ceph-operator.log](https://github.com/rook/rook/files/7986904/rook-ceph-operator.txt)

**Environment**:
* OS (e.g. from /etc/os-release): N/A - AKS managed node
* Kernel (e.g. `uname -a`): N/A
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.8.0 or 1.8.3
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.6 (with 1.8.0) or 16.2.7 (with 1.8.3).
* Kubernetes version (use `kubectl version`): v1.21.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): AKS
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

**Comment by travisn** [comment]
I see, this is a `delete` command for the v1beta1 csi driver. You have the correct v1 csi driver installed, and Rook is just ensuring the old v1beta1 has been removed in case it was an upgrade. So this delete action is expected and benign.

**Comment by travisn** [comment]
@Madhu-1 From your comment in Slack, maybe there is something you want to follow up on with this?

**Comment by Madhu-1** [comment]
@travisn I will test this once and make sure everything is fine and will close it.

**Comment by Madhu-1** [comment]
Looks like I overlooked something but am clear now. below is my update.
As the kubernetes version is still `v1.21.2`  which is in this case and we are still allowed the use the `v1beta1` CSI CRD as its till not been deprecated yet in the kubernetes v1.21. But if the Kubernetes cluster is v1.22 and if you are seeing this deprecation then it's a problem. Once you upgrade your kubernetes cluster to `v1.22.0` rook will take care of deleting the `beta` CSI CRD and it will use `v1` CRD.  based on this one am closing this one.
