### ISSUE TITLE
rook-ceph-osd-1 deployment not created

### ISSUE THREAD

**Issue by raz3k** [rook/rook#9698]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
rook-ceph-osd-1 deployment not created

**Expected behavior:**
rook-ceph-osd-1 deployment created

**How to reproduce it (minimal and precise):**
I only saw it twice, even after restarting the operator the osd deployment still was not created, I had to do a full uninstall.

**File(s) to submit**:

* Operator's logs, if necessary - https://pastebin.com/YNppRJmY
* OSD prepare job for nodename-1: https://pastebin.com/9m920CZi
```
$ kubectl get deployments -n kube-system
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
coredns                               2/2     2            2           18h
csi-cephfsplugin-provisioner          2/2     2            2           18h
csi-rbdplugin-provisioner             2/2     2            2           18h
paas-hostpath-hostpath                1/1     1            1           18h
rook-ceph-crashcollector-nodename-0   1/1     1            1           18h
rook-ceph-crashcollector-nodename-1   1/1     1            1           18h
rook-ceph-crashcollector-nodename-2   1/1     1            1           18h
rook-ceph-mds-rook-ceph-ceph-fs-a     1/1     1            1           18h
rook-ceph-mds-rook-ceph-ceph-fs-b     1/1     1            1           18h
rook-ceph-mgr-a                       1/1     1            1           18h
rook-ceph-mon-a                       1/1     1            1           18h
rook-ceph-mon-b                       1/1     1            1           18h
rook-ceph-mon-c                       1/1     1            1           18h
rook-ceph-operator                    1/1     1            1           18h
rook-ceph-osd-0                       1/1     1            1           18h
rook-ceph-osd-2                       1/1     1            1           18h
```

**Environment**:
* OS (e.g. from /etc/os-release): RedHat 8.5
* Kernel (e.g. `uname -a`): 4.18.0-348.12.2.el8_5.x86_64
* Cloud provider or hardware configuration: BareMetal 
* Rook version (use `rook version` inside of a Rook Pod): 1.8.1
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.7
* Kubernetes version (use `kubectl version`): 1.22.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Multimaster, worker+master shared, 3 nodes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_WARN noout flag(s) set; OSD count 2 < osd_pool_default_size 3
[WRN] OSDMAP_FLAGS: noout flag(s) set
[WRN] TOO_FEW_OSDS: OSD count 2 < osd_pool_default_size 3

**Comment by travisn** [comment]
How about the logs for the osd prepare job on nodename-2? That's where the osd-1 was likely created. The nodename-1 log shows that osd.2 was successfully created.

**Comment by raz3k** [comment]
Unfortunately, I had to trash those machines. I will keep an eye open if it happens again. Thanks for the quick response.
