### ISSUE TITLE
Unable to upgrade from v1.6.7 to any later release - OSD pods can't initialize

### ISSUE THREAD

**Issue by bzakhar** [rook/rook#9712]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Current Rook Operator version is 1.6.7. Running

`helm upgrade -n rook-ceph rook-ceph rook-release/rook-ceph --version v1.6.8`

or any other later version. As part of the upgrade OSDs are recreated and enter CrashLoopBackOff due to

```
ceph -n client.admin auth get-or-create osd.0 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
Error EINVAL: key for osd.0 exists but cap mgr does not match
```

in `activate` container and OSD pod can't start. Rolling back to v1.6.7 restores the cluster to working state. Looks like #8155 is responsible for this error since it introduces the `ceph -n client.admin auth get-or-create ...` command in container init script. I am not very well versed in Ceph and can't figure out what causes `cap mgr` mismatch or how to fix it to allow this command to succeed.

**Expected behavior:**

Upgrade from v1.6.7 to a later release is successful without errors.

**How to reproduce it (minimal and precise):**
Not sure it's easily reproducible in a test environment - this deployment went through multiple upgrades to reach its current state. I suppose one can try to deploy a minimal cluster using helm chart v1.6.7 or earlier and then try to upgrade it to a later release. Maybe delete an OSD pod and let it be recreated before trying to upgrade.

**File(s) to submit**:

* Crashing pod(s) logs:
There's literally almost nothing in the logs since this happens very early in pod's activate container. Relevant (I believe) log lines are the last ones:
```
ceph -n client.admin auth get-or-create osd.0 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
Error EINVAL: key for osd.0 exists but cap mgr does not match
<<EOF here>>
```

**Environment**:
* OS (e.g. from /etc/os-release): `CentOS Linux release 7.9.2009 (Core)`
* Kernel (e.g. `uname -a`): `3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: on-premises bare-metal K8s
* Rook version (use `rook version` inside of a Rook Pod): `v1.6.7`
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)`
* Kubernetes version (use `kubectl version`): 1.20.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Bare-metal (deployed with kubeadm)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_WARN mons q,u,v are low on available space

**Comment by travisn** [comment]
@bzakhar You must have an older version of rook that created the OSDs with different auth so we will need to find how to update the auth so you can upgrade. 

What does `ceph auth ls` show for your OSD? In my test cluster the OSD auth shows:
```
osd.0
	key: <omitted>
	caps: [mgr] allow profile osd
	caps: [mon] allow profile osd
	caps: [osd] allow *
```

**Comment by bzakhar** [comment]
@travisn Weird as it is, I'm getting this error:

```
[root@rook-ceph-osd-0-69dfd6c847-q6g9b ceph]# ceph auth ls
2022-02-09T22:30:01.282+0000 7f28f0843700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2022-02-09T22:30:01.282+0000 7f28f0843700 -1 AuthRegistry(0x7f28ec05eb80) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx
2022-02-09T22:30:01.283+0000 7f28f0843700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2022-02-09T22:30:01.283+0000 7f28f0843700 -1 AuthRegistry(0x7f28f0841e90) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx
2022-02-09T22:30:01.285+0000 7f28ead9d700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]
2022-02-09T22:30:01.286+0000 7f28ea59c700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]
2022-02-09T22:30:01.287+0000 7f28e9d9b700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [1]
2022-02-09T22:30:01.287+0000 7f28f0843700 -1 monclient: authenticate NOTE: no keyring found; disabled cephx authentication
[errno 13] RADOS permission denied (error connecting to the cluster)
```
but the cluster operates normally.

**Comment by travisn** [comment]
Actually, try it from the toolbox instead of the osd pod

**Comment by bzakhar** [comment]
```
osd.0
        key: <<redacted>>
        caps: [mon] allow profile osd
        caps: [osd] allow *
```
So looks like mgr caps are missing altogether. This is the same for all 81 OSDs in the cluster...

**Comment by bzakhar** [comment]
Here's what I did to make my osd.N caps to look like yours:

`for i in {0..80}; do ceph auth caps osd.$i mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *'; done`

I then initiated helm upgrade to 1.6.8 and this time OSD pods are restarting without errors. 

Thanks for pointing me in the right direction!

Bob

**Comment by travisn** [comment]
Ok great to hear it's working now! To understand what clusters might be affect, do you recall from what version of Rook you first created the cluster?

**Comment by bzakhar** [comment]
It was almost two years ago, Helm didn't even retain the history that far, but I seem to recall it was v1.4.x, not sure about the x. Ceph itself was upgraded multiple times, all the way from Mimic if memory serves me right.
