### ISSUE TITLE
Add debug info to explain that node are not eligible to have OSDs

### ISSUE THREAD

**Issue by AlexisDucastel** [rook/rook#9716]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Currently operator does have an information log to show how many nodes are eligible for OSDs :
```
op-osd: 3 of the 6 storage nodes are valid
```

We think that it would help users to add a debug log level with every node found, indicating if it is eligible or not. (There is a similar behavior when node is under taint constraint (Ex : `ceph-cluster-controller: node watcher: node "XXXXX" is not tolerable for cluster "rook-ceph", skipping`). At least with the fact that it is eligible or not, and maybe (when possible) the reason why it is not eligible (even with just a reason like "not matching placement requirement" for example)

Thanks a lot.

**What is use case behind this feature:**

A bit of context : Right now, we have a cluster with every OSD bound on node with a label storage=yes, thus preventing OSD to come up in cloud instances in case of hybrid clusters (cloud/bare-metal). We had rough times debugging why operator wasn't taking our new node into account, showing `op-osd: 2 of the 6 storage nodes are valid` even if we had 3 nodes with disks available for OSDs. The main problem was just a placement requirement we set on CephCluster object, that was dodging our new node because of the lacking node label.

Users that are deploying adding new nodes may be "lost" by searching why the node is "ignored", as there is no log for this (of course, it's not an error), making debugging very tedious.

**Environment**:

I suppose it may impact every Rook Ceph cluster deployed on non-PVC based OSDs.

**Comment by AlexisDucastel** [comment]
Just awesome !! 

I think "INFO" level should be better, in production it would be better to not have to go DEBUG, else it would really overhelm with unwanted logs :) 

Thanks a lot for your reactivity !!

**Comment by travisn** [comment]
Ok, I updated it so the messages would always be logged at info level when they are skipped. I guess today I needed to work on something simple and useful. :)

**Comment by AlexisDucastel** [comment]
Maybe that's not the feature of the year, but I bet it will at least save a lot of time for every admin like us searching why the hell this damned node is not seen by operator :D

I think this issue can be closed as it is 100% covered by your actions :)

Thanks again :)
