### ISSUE TITLE
ceph cluster does not created properly

### ISSUE THREAD

**Issue by themonaminor** [rook/rook#9719]
**hi attached some data disk to my k8s nodes and ran crds.yaml, common.yaml, operator.yaml and cluster.yaml.

first time everything got deployed , i got mons, mgrs, osds all working fine.

then i deleted all crds, common.yaml, operator and cluster.yaml and again tried to deploy the cluster.
but this time it does not deploy the cluster properly.

here are the listed components of ceph only got deployed to k8s cluster this time:-**

NAME                                            READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-mbtwl                          3/3     Running   0          5m16s
csi-cephfsplugin-provisioner-6f54f6c477-n4s9x   6/6     Running   0          5m16s
csi-cephfsplugin-provisioner-6f54f6c477-pgmqs   6/6     Running   0          5m16s
csi-cephfsplugin-rdqcr                          3/3     Running   0          5m16s
csi-cephfsplugin-x7rj4                          3/3     Running   0          5m16s
csi-rbdplugin-6k9r2                             3/3     Running   0          5m17s
csi-rbdplugin-9hpmf                             3/3     Running   0          5m17s
csi-rbdplugin-provisioner-6d765b47d5-dp2kq      6/6     Running   0          5m17s
csi-rbdplugin-provisioner-6d765b47d5-n4k62      6/6     Running   0          5m17s
csi-rbdplugin-w7j9p                             3/3     Running   0          5m17s
rook-ceph-mon-a-6cbccd8496-rztbn                1/1     Running   0          5m10s
rook-ceph-operator-58cd47ddb8-rv6nx             1/1     Running   0          5m54s

**and here is the log of monitor pod:-**

debug 2022-02-10T06:44:48.961+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:44:50.361+0000 7f0642e8e700  0 log_channel(audit) log [DBG] : from='admin socket' entity='admin socket' cmd='mon_status' args=[]: dispatch
debug 2022-02-10T06:44:50.361+0000 7f0642e8e700  0 log_channel(audit) log [DBG] : from='admin socket' entity='admin socket' cmd=mon_status args=[]: finished
debug 2022-02-10T06:44:50.553+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:44:50.757+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:44:51.161+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:44:51.965+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:44:52.761+0000 7f063de07700 -1 mon.a@0(probing) e3 get_health_metrics reporting 52 slow ops, oldest is log(1 entries from seq 1 at 2022-02-10T06:40:10.366306+0000)
debug 2022-02-10T06:44:53.549+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:44:53.757+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:44:54.157+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:44:54.957+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:44:57.761+0000 7f063de07700 -1 mon.a@0(probing) e3 get_health_metrics reporting 52 slow ops, oldest is log(1 entries from seq 1 at 2022-02-10T06:40:10.366306+0000)
debug 2022-02-10T06:45:00.349+0000 7f0642e8e700  0 log_channel(audit) log [DBG] : from='admin socket' entity='admin socket' cmd='mon_status' args=[]: dispatch
debug 2022-02-10T06:45:00.349+0000 7f0642e8e700  0 log_channel(audit) log [DBG] : from='admin socket' entity='admin socket' cmd=mon_status args=[]: finished
debug 2022-02-10T06:45:01.689+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:45:01.893+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:45:02.297+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:45:02.761+0000 7f063de07700 -1 mon.a@0(probing) e3 get_health_metrics reporting 54 slow ops, oldest is log(1 entries from seq 1 at 2022-02-10T06:40:10.366306+0000)
debug 2022-02-10T06:45:03.101+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:45:04.693+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:45:04.897+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:45:05.297+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id
debug 2022-02-10T06:45:06.105+0000 7f063f60a700  1 mon.a@0(probing) e3 handle_auth_request failed to assign global_id

**Comment by travisn** [comment]
If the reinstall fails to create the mon quorum, likely some data on the hosts wasn't cleaned up. Please verify the host path was cleaned up, and the disks from the OSDs were wiped. See the [cleanup guide](https://rook.github.io/docs/rook/v1.8/ceph-teardown.html#delete-the-data-on-hosts) for more details.
