### ISSUE TITLE
After the osd host restarts abnormally, the osd cannot be started

### ISSUE THREAD

**Issue by clcc2019** [rook/rook#9747]
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/46099295/154208269-b799881b-dfd7-43f2-913f-d46b53108449.png">
reraise_fatal: default handler for signal 6 didn't terminate the process?

ceph 16.2.4

**Comment by leseb** [comment]
For daemon crashes please open a ticket at https://tracker.ceph.com/ and paste the full log. Thanks!
