### ISSUE TITLE
objectstore: provide way to give zone/zonegroup/realm for external ceph cluster

### ISSUE THREAD

**Issue by thotz** [rook/rook#9750]
**Is this a bug report or feature request?**
* Bug Report
For the RGW running in the external cluster, the only viable parameter is the `EndpointAddress`, but Rook sets zone/zone group/realm value as `objectstore` name in `objectContext`. This may fail internal s3 operations / `radosgw-admin` commands if there are multiple zonegroup/zones that exists in the external cluster. If it can be fixed by Zone/ZoneGroup/Realm CRs then we may need these changes. We need to evaluate multisite settings with the external cluster as well.

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by leseb** [comment]
Dup of https://github.com/rook/rook/issues/6342?

**Comment by leseb** [comment]
If so, please close an amend https://github.com/rook/rook/issues/6342 with more content if appropriate

**Comment by thotz** [comment]
> Dup of #6342?
#6342  is one way of doing it, other way is pass the zone/zone group/realm as part of external Spec in the objectstore CR, since we already have CRs for zone/zonegroup/realms and also support obc, cephobjectstoreuser for external rgw server. We use #6342 approach
