### ISSUE TITLE
osd is crashing after couple of hours

### ISSUE THREAD

**Issue by yuvalif** [rook/rook#9757]
**Is this a bug report or feature request?**
* Bug Report

**How to reproduce it (minimal and precise):**
instruction are [here](https://gist.github.com/yuvalif/becb7705b4626d3b302a1b2f5f9b56ec)
the crash is happening after a couple of hours. note that the instructions are for "master", but the issue happens in 1.8 as well

**File(s) to submit**:

* Cluster CR (custom resource): in the reproduction instructions
* Operator's logs: https://0x0.st/o8pl.log
* Crashing pod(s) log: https://0x0.st/o8pI.log

**Environment**:
* OS (e.g. from /etc/os-release): `Red Hat Enterprise Linux CoreOS 49.84.202201102104-0`
* Kernel (e.g. `uname -a`): `4.18.0-305.30.1.el8_4.x86_64`
* Cloud provider or hardware configuration:
```
 lsblk
NAME                                                                                                  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT                                                                                                    
vda                                                                                                   252:0    0   31G  0 disk                                                                                                               
|-vda1                                                                                                252:1    0    1M  0 part                                                                                                               
|-vda2                                                                                                252:2    0  127M  0 part                                                                                                               
|-vda3                                                                                                252:3    0  384M  0 part /boot                                                                                                         
`-vda4                                                                                                252:4    0 30.5G  0 part /sysroot                                                                                                      
vdb                                                                                                   252:16   0   30G  0 disk                                                                                                               
`-ceph--8cf210de--eb55--4a9d--b402--ceeba17f84ed-osd--block--9e44d522--1104--451e--ab13--ec1e1b8e8434 253:0    0   30G  0 lvm
```
* Rook version (use `rook version` inside of a Rook Pod): `master` and `1.8`
* Storage backend version (e.g. for ceph do `ceph -v`): `16.2.7`
* Kubernetes version (use `kubectl version`): 
```
Client Version: 4.9.5
Server Version: 4.9.15
Kubernetes Version: v1.22.3+e790d7f
```
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): CRC
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by leseb** [comment]
I see `(5) Input/output error`, could it be an issue with the underlying VM disk?

**Comment by yuvalif** [comment]
> I see `(5) Input/output error`, could it be an issue with the underlying VM disk?

any idea on how to debug that?

**Comment by praveenkumar** [comment]
> I see `(5) Input/output error`, could it be an issue with the underlying VM disk?

This error happen around ~2-3 hour later of running the operator, any info around understanding if underlying disk image is culprit would be useful.

**Comment by leseb** [comment]
> > I see `(5) Input/output error`, could it be an issue with the underlying VM disk?
> 
> any idea on how to debug that?

You can look at the kernel log in the VM for that.

**Comment by leseb** [comment]
> > I see `(5) Input/output error`, could it be an issue with the underlying VM disk?
> 
> This error happen around ~2-3 hour later of running the operator, any info around understanding if underlying disk image is culprit would be useful.

`(5) Input/output error` this **is** the information.

**Comment by yuvalif** [comment]
@praveenkumar is the issue fixed with the new CRC/OpenShift?

**Comment by yuvalif** [comment]
cannot reproduce anymore
