### ISSUE TITLE
cephfs-mirror

### ISSUE THREAD

**Issue by HYQ1314** [rook/rook#9772]
1、Although peers are configured in Filesystem,Cephfs-mirror still indicates that there is no external cluster kerring
/etc/ceph/ceph.client.mirror_remote2.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2、Filesystem After a mirror is configured，fsMirrorBootstrapPeerSecretName: fs-peer-token-myfs  Not created。
3、secondary-cluster-peer didn't work in filesystem

**Comment by leseb** [comment]
Please re-open using the "issue" template and fulfill all requested information. Thanks.
