### ISSUE TITLE
Unable to create a volume

### ISSUE THREAD

**Issue by valentin2105** [rook/rook#978]
Hi,

I'm trying Rook in my single node cluster, 
I have deployed Rook-storageclass, Rook-Operator and Rook-cluster, everything seem to run fine. 

When I create a volume (simple mysql) from the documentation example, 

I got a lot of errors and the volume can't be created ,

```
2017-09-11 21:37:04.057820 I | op-provisioner: creating volume with configuration {pool:replicapool clusterNamespace:rook clusterName:rook fstype:}

2017-09-11 21:37:04.057891 I | exec: Running command: rbd create replicapool/k8s-dynamic-pvc-4aaeeed3-9739-11e7-98b9-d61f6b0e3d31-5a3713d6-9739-11e7-b406-9e9692d0b400 --size 2048 --cluster=rook --conf=/var/lib/rook/rook/rook.config --keyring=/var/lib/rook/rook/client.admin.keyring

E0911 21:37:04.130974      13 controller.go:796] Failed to provision volume for claim "default/mysql-pv-claim" with StorageClass "rook-block": Failed to create rook block image replicapool/k8s-dynamic-pvc-4aaeeed3-9739-11e7-98b9-d61f6b0e3d31-5a3713d6-9739-11e7-b406-9e9692d0b400: failed to create image k8s-dynamic-pvc-4aaeeed3-9739-11e7-98b9-d61f6b0e3d31-5a3713d6-9739-11e7-b406-9e9692d0b400 in pool replicapool of size 2147483648: Failed to complete : exit status 2. output:

E0911 21:37:04.131139      13 goroutinemap.go:165] Operation for "provision-default/mysql-pv-claim[4aaeeed3-9739-11e7-98b9-d61f6b0e3d31]" failed. No retries permitted until 2017-09-11 21:37:06.131095158 +0000 UTC m=+140.464095987 (durationBeforeRetry 2s). Error: Failed to create rook block image replicapool/k8s-dynamic-pvc-4aaeeed3-9739-11e7-98b9-d61f6b0e3d31-5a3713d6-9739-11e7-b406-9e9692d0b400: failed to create image k8s-dynamic-pvc-4aaeeed3-9739-11e7-98b9-d61f6b0e3d31-5a3713d6-9739-11e7-b406-9e9692d0b400 in pool replicapool of size 2147483648: Failed to complete : exit status 2. output:

```
Any idea what's append ?

**Comment by jbw976** [comment]
@valentin2105 can you share the rest of the logs for your cluster?
https://rook.io/docs/rook/master/advanced-configuration.html#log-collection

Have you already been able to launch the Rook toolbox to get more status information about the cluster?
https://rook.io/docs/rook/master/toolbox.html

```
kubectl -n rook exec -it rook-tools -- rookctl status
```

**Comment by valentin2105** [comment]
Hi @jbw976 , Here is my  `rookctl status`


```
OVERALL STATUS: WARNING

SUMMARY:
SEVERITY   NAME           MESSAGE
WARNING    MON_DISK_LOW   mons rook-ceph-mon0,rook-ceph-mon1,rook-ceph-mon2 are low on available space

USAGE:
TOTAL       USED        DATA      AVAILABLE
39.12 GiB   30.62 GiB   0 B       8.50 GiB

MONITORS:
NAME             ADDRESS                IN QUORUM   STATUS
rook-ceph-mon2   10.32.87.196:6790/0    true        OK
rook-ceph-mon0   10.32.202.240:6790/0   true        OK
rook-ceph-mon1   10.32.204.172:6790/0   true        OK

MGRs:
NAME             STATUS
rook-ceph-mgr0   Active

OSDs:
TOTAL     UP        IN        FULL      NEAR FULL
1         1         1         false     false

PLACEMENT GROUPS (0 total):
STATE     COUNT
none
```
( I try to create a 2Gig volume only )

Here is the logs :  (at the end, I create the mysql example with PV) : 

https://pastebin.com/Pf6gBi1V

**Comment by jbw976** [comment]
I notice there aren't any placement groups created which implies there has been no storage pool created.  Did you run the step to create the Rook storage class (which also creates the storage pool)?

From https://rook.io/docs/rook/master/k8s-block.html#provision-storage:
```
kubectl create -f rook-storageclass.yaml
```

**Comment by valentin2105** [comment]
Great, I was missing this part ! 
My Mysql PVC is bounded and the pod correctly mount the volume. 

Small last question,

Why I got this PVC who stay in Pending mode : 

`data-redis-cluster-0   Pending                                                                       ceph-rbd`

Thanks for the Awesome Rook, It's Rocks ! 👍

**Comment by jbw976** [comment]
Glad your mysql PVC is working now.  I'm not quite sure about the `data-redis-cluster-0` PVC, I didn't see any references to it in the logs you shared on pastebin earlier.  Did you see references to it in the Kubelet journal/logs?

Can you share the following output?
```
kubectl get pvc data-redis-cluster-0 -o yaml
kubectl describe pod <pod using pvc>
```

**Comment by valentin2105** [comment]
Sorry, my fault, just an old PVC who stayed here. 

Thanks !
