### ISSUE TITLE
cephfs mount failure.permission denied

### ISSUE THREAD

**Issue by czhfe** [rook/rook#9782]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Unable to mount cephfs

**Expected behavior:**
It is possible to mount cephfs normally

**How to reproduce it (minimal and precise):**

```
E0210 20:38:31.292481       1 utils.go:185] ID: 44990 Req-ID: 0001-0009-rook-ceph-0000000000000002-bbb57db2-4684-11ec-a965-7a1a7a095897 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89e0b81a-c433-4971-b446-e9341d9ab148/globalmount: permission denied
E0210 20:40:33.398387       1 nodeserver.go:117] ID: 44994 Req-ID: 0001-0009-rook-ceph-0000000000000002-bbb57db2-4684-11ec-a965-7a1a7a095897 stat failed: stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89e0b81a-c433-4971-b446-e9341d9ab148/globalmount: permission denied
E0210 20:40:33.398454       1 utils.go:185] ID: 44994 Req-ID: 0001-0009-rook-ceph-0000000000000002-bbb57db2-4684-11ec-a965-7a1a7a095897 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89e0b81a-c433-4971-b446-e9341d9ab148/globalmount: permission denied
E0210 20:42:35.561473       1 nodeserver.go:117] ID: 44998 Req-ID: 0001-0009-rook-ceph-0000000000000002-bbb57db2-4684-11ec-a965-7a1a7a095897 stat failed: stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89e0b81a-c433-4971-b446-e9341d9ab148/globalmount: permission denied
E0210 20:42:35.561539       1 utils.go:185] ID: 44998 Req-ID: 0001-0009-rook-ceph-0000000000000002-bbb57db2-4684-11ec-a965-7a1a7a095897 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89e0b81a-c433-4971-b446-e9341d9ab148/globalmount: permission denied
E0210 20:44:37.732460       1 nodeserver.go:117] ID: 45002 Req-ID: 0001-0009-rook-ceph-0000000000000002-bbb57db2-4684-11ec-a965-7a1a7a095897 stat failed: stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89e0b81a-c433-4971-b446-e9341d9ab148/globalmount: permission denied
E0210 20:44:37.732528       1 utils.go:185] ID: 45002 Req-ID: 0001-0009-rook-ceph-0000000000000002-bbb57db2-4684-11ec-a965-7a1a7a095897 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89e0b81a-c433-4971-b446-e9341d9ab148/globalmount: permission denied
E0210 20:56:12.253793       1 nodeserver.go:117] ID: 45011 Req-ID: 0001-0009-rook-ceph-0000000000000002-bbb57db2-4684-11ec-a965-7a1a7a095897 stat failed: stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89e0b81a-c433-4971-b446-e9341d9ab148/globalmount: permission denied
E0210 20:56:12.253885       1 utils.go:185] ID: 45011 Req-ID: 0001-0009-rook-ceph-0000000000000002-bbb57db2-4684-11ec-a965-7a1a7a095897 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-89e0b81a-c433-4971-b446-e9341d9ab148/globalmount: permission denied
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7 X86
* Kernel (e.g. `uname -a`): 5.4.172
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.7.7
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.6
* Kubernetes version (use `kubectl version`): v1.16.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Native Kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

**Comment by parth-gr** [comment]
Can you share the operator logs and the configuration you used
I see somthing like PVC not able to bound, maybe the case of disk not permitting it to do,

Also please share the details of other pods.

**Comment by czhfe** [comment]
> Can you share the operator logs and the configuration you used I see somthing like PVC not able to bound, maybe the case of disk not permitting it to do,
> 
> Also please share the details of other pods.

**1、Rook Operator manifest**
```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  annotations: null
  cephVersion:
    allowUnsupported: false
    image: docker-prod-registry.cn-hangzhou.cr.aliyuncs.com/global/ceph:v16.2.6
  cleanupPolicy:
    allowUninstallWithVolumes: false
    confirmation: ""
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    disable: false
  dashboard:
    enabled: true
    ssl: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    manageMachineDisruptionBudgets: false
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
  labels: null
  mgr:
    count: 2
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    allowMultiplePerNode: false
    count: 3
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  network: null
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/fast
              operator: Exists
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/fast
        operator: Exists
  removeOSDsIfOutAndSafeToRemove: false
  resources:
    crashcollector:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    mgr:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
    mon:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi
    osd:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 2Gi
  skipUpgradeChecks: false
  storage:
    config: null
    nodes:
    - devices:
      - name: sdb
      name: 10.5.6.201
    - devices:
      - name: sdb
      name: 10.5.6.202
    - devices:
      - name: sdb
      name: 10.5.6.203
    onlyApplyOSDPlacement: false
    useAllDevices: false
    useAllNodes: false
  waitTimeoutForHealthyOSDInMinutes: 10
'''

**Comment by travisn** [comment]
Please also review the [CSI troubleshooting guide](https://rook.github.io/docs/rook/v1.8/ceph-csi-troubleshooting.html) to see if there is any resolution.

**Comment by defengnee** [comment]
I am also facing the mounting issue. 

Here is the link of some details. Not sure if I need to provide the same information in this thread. Please advise. 

https://stackoverflow.com/questions/71417480/ceph-shared-file-system-mounting-error-permission-denied

Tried the troubleshooting guide tips, but not helpful for this issue.

**Comment by czhfe** [comment]
> Please also review the [CSI troubleshooting guide](https://rook.github.io/docs/rook/v1.8/ceph-csi-troubleshooting.html) to see if there is any resolution.

Thanks. I've looked at this piece before, but I didn't find any available help

**Comment by Madhu-1** [comment]
This issue is same as https://github.com/ceph/ceph-csi/issues/970?

**Comment by defengnee** [comment]
No, the volume was never mounted. Not due to the network issue.

**Comment by czhfe** [comment]
> This issue is same as [ceph/ceph-csi#970](https://github.com/ceph/ceph-csi/issues/970)?

No, the kubernetes pod is not started yet, and the above exception is thrown when the volume is not mounted. The performance phenomenon looks the same.

![image](https://user-images.githubusercontent.com/19341806/158775041-fa5c1dfc-9afc-4f5a-91b6-9ba1dd90802e.png)
![image](https://user-images.githubusercontent.com/19341806/158775108-ffe4d019-5e2a-4f76-a7bc-7919f45610b7.png)

The problem I mentioned in #9575

**Comment by dinghui40** [comment]
I also encountered the same problem, I found that the mount directory permissions caused by the problem, my solution is.

 
![d75c38524eeefc831768da71832cfef](https://user-images.githubusercontent.com/102201557/172546005-d04f46eb-ea65-4940-be71-db6a1403b90e.png)
![ff79f94cedf30cd1dcc1e9a02fcc935](https://user-images.githubusercontent.com/102201557/172546024-aa63fb10-c776-451c-81bd-de3f5f69d5e4.png)
![cea37e7459570149f908dd725c9e416](https://user-images.githubusercontent.com/102201557/172546049-c81b0f54-900b-41cd-b57f-0c183add7d5b.png)
![b037c2bf67599302d96a6cf745c86ee](https://user-images.githubusercontent.com/102201557/172546056-7c26a38d-83b4-487d-97c3-293260f0e18d.png)

  
I found the directory reporting the error, Remove the POD from this node

umount -lf /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1739b858-93b0-4ac4-b59e-773a84d3ea83/globalmount
  
Migrate the POD back to the node and the problem is resolved

**Comment by jinwonkim93** [comment]
@PierreRAFFA @dinghui40 I guess many people are encountering this issue. Do you know the root cause of this problem?

**Comment by piersharding** [comment]
seeing what appears to be the same error:
```
bash: cd: /var/lib/kubelet/pods/af3cd2d8-947a-46c9-968a-ec7339294b5b/volumes/kubernetes.io~csi/shared-dp-dppt-peter-p/mount: Permission denied
root@sdhp-k8s-worker-0:/home/ubuntu# cd /var/lib/kubelet/pods/af3cd2d8-947a-46c9-968a-ec7339294b5b/volumes/kubernetes.io~csi/shared-dp-dppt-peter-p
root@sdhp-k8s-worker-0:/var/lib/kubelet/pods/af3cd2d8-947a-46c9-968a-ec7339294b5b/volumes/kubernetes.io~csi/shared-dp-dppt-peter-p# ls -l
ls: cannot access 'mount': Permission denied
total 4
d????????? ? ?    ?      ?            ? mount
-rw-r--r-- 1 root root 327 Jul 25 09:17 vol_data.json
```

**Comment by jinwonkim93** [comment]
i also encounter permission denied so i did this

umount -lf /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-1739b858-93b0-4ac4-b59e-773a84d3ea83/globalmount

so the permission does not show but i cant read the file.

![image](https://user-images.githubusercontent.com/26476095/180891902-fa1ed1e4-2ba7-483c-be9c-392f13362c9d.png)
