### ISSUE TITLE
Capture logs for test-pod and kubelet

### ISSUE THREAD

**Issue by kokhang** [rook/rook#980]
We need to capture the logs from the test pod in order to better debug if a failure happens.
I think 3 things we need:
- Kubeclt get logs test-pod
- kubeclt describe pod test-pod
- journalctl -u kubelet

**Comment by travisn** [comment]
@kokhang what pod are you referring to? I don't see any pod called `test-pod` in the repo

**Comment by galexrt** [comment]
@travisn Ping
Is this still needed?
