### ISSUE TITLE
rook-ceph-operator-config-controller fails to reconcile if configmap is missing

### ISSUE THREAD

**Issue by matthiasr** [rook/rook#9806]
Original bug report below. After investigation, @travisn found that this is a consequence of the rook-ceph-operator-config-controller not running if the configmap is missing altogether.

As a workaround, create an empty ConfigMap `rook-ceph-operator-config` in the operator namespace (typically `rook-ceph`). This also re-enables reading configuration from the environment.

---------

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

When configuring the operator through the environment, instead of the `rook-ceph-operator-config` config map, the value for `ROOK_ENABLE_DISCOVERY_DAEMON` is ignored.

**Expected behavior:**

Setting `ROOK_ENABLE_DISCOVERY_DAEMON=true` in the environment, the `rook-discover` daemonset is created.

**How to reproduce it (minimal and precise):**

Set `ROOK_ENABLE_DISCOVERY_DAEMON=true` in the operator environment, and remove it from the `rook-ceph-operator-config` ConfigMap. The `rook-discover` daemon is not created.

The operator logs

```
2022-02-25 14:17:05.264768 D | op-bucket-prov: operator's configmap resource not found. will use default value or env var.
[...]
2022-02-25 14:17:05.268040 D | ceph-csi: operator's configmap resource not found. will use default value or env var.
```

but does not mention the discover daemonset at all.

I believe this was introduced in #8607 (cc @leseb). It changed the DiscoveryDaemonEnabled method to [use passed-in configuration data](https://github.com/rook/rook/pull/8607/files#diff-d9bbbda1ff0c858da45b7e77f7cbfe0ee4281e369c596cd8c7df3ed349e59f66R93). This [comes from the ReconcileConfig](https://github.com/rook/rook/pull/8607/files#diff-d78b060c10b44e75f988282d1525dda79a60309ba1c13e2fd4741dab0ebe3481R161), which is [populated by fetching the config map](https://github.com/rook/rook/pull/8607/files#diff-d78b060c10b44e75f988282d1525dda79a60309ba1c13e2fd4741dab0ebe3481R112).

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
* Kernel (e.g. `uname -a`): `Linux <redacted> 5.8.4-18-soundcloud #19-Ubuntu SMP PREEMPT Tue Sep 8 14:48:18 UTC 2020 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: local tests in Docker (custom)
* Rook version (use `rook version` inside of a Rook Pod): 1.8.6
* Storage backend version (e.g. for ceph do `ceph -v`): 
* Kubernetes version (use `kubectl version`): 1.20
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): homegrown
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): N/A

**Comment by travisn** [comment]
@matthiasr 
- Does restarting the operator workaround the issue?
- Do you see the following messages in the operator log? If so, the setting should have been reconciled, otherwise it just isn't being triggered.
```
rook-ceph-operator-config-controller successfully started
rook-ceph-operator-config-controller done reconciling
```

**Comment by matthiasr** [comment]
> Does restarting the operator workaround the issue?

No, after a restart it's all the same.

> Do you see the following messages in the operator log?

I see `successfully started`, but not `done reconciling`. There are messages from various components about the config map not existing (which is true).

I cleaned up the full log so I can post it now:
[operator.log](https://github.com/rook/rook/files/8151956/operator.log)

Is the config map required now, or is configuring the operator through environment variables still supported? I could not find definitive documentation either way.

**Comment by travisn** [comment]
> Is the config map required now, or is configuring the operator through environment variables still supported? I could not find definitive documentation either way.

It's intended that the environment variables are still supported, and the configmap would just allow the env vars to be overridden. But I see now that in v1.8 changes, if the configmap doesn't exist the discovery daemon won't be started. As a workaround, does creating an empty configmap work?

**Comment by matthiasr** [comment]
Indeed, that got everything unstuck! I misunderstood the k8sutil code then, the discovery daemonset logic is sound but the data it references is not properly initialised if the configmap does not exist at all?

```log
2022-03-01 08:45:37.086637 D | operator: reconciling rook-ceph/rook-ceph-operator-config
2022-03-01 08:45:37.086731 I | op-k8sutil: ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS="15" (default)
2022-03-01 08:45:37.086805 I | op-k8sutil: ROOK_LOG_LEVEL="DEBUG" (env var)
2022-03-01 08:45:37.086860 I | op-k8sutil: ROOK_ENABLE_DISCOVERY_DAEMON="true" (env var)
2022-03-01 08:45:37.103485 I | op-discover: rook-discover daemonset started
2022-03-01 08:45:37.103540 I | operator: rook-ceph-operator-config-controller done reconciling
2022-03-01 08:45:37.108041 I | ceph-csi: successfully created csi config map "rook-ceph-csi-config"
```

**Comment by matthiasr** [comment]
Updated the title and description to match this finding.

**Comment by travisn** [comment]
I'm inclined to just document that the `rook-ceph-operator-config` must exist even if empty in order to configure the discover daemon. Clusters created with the helm chart will have the configmap, and upgraded clusters that had been created with [operator.yaml as old as v1.2](https://github.com/rook/rook/blob/release-1.2/cluster/examples/kubernetes/ceph/operator.yaml) would also have the configmap.

**Comment by matthiasr** [comment]
Works for me, PR created!
