### ISSUE TITLE
Define plugin for erasure code pools

### ISSUE THREAD

**Issue by spdfnet** [rook/rook#9832]
Erasure code plugins (and their settings) can not be set while creating CephFS data pools, getting the suboptimal defaults.
~~This is a problem with the CSI side of things if pools are created manually.~~

**Comment by travisn** [comment]
@spdfnet What is your filesystem CR? Are you following [this example](https://github.com/rook/rook/blob/master/deploy/examples/filesystem-ec.yaml#L25-L28) to create the filesystem with EC pools? More details are needed to know what is your issue.

**Comment by spdfnet** [comment]
Actually, this affect any kind of pool created via Rook.

**Comment by travisn** [comment]
@spdfnet You can set any pool property with the [parameters](https://github.com/rook/rook/blob/master/deploy/examples/pool-ec.yaml#L19-L22) on the pool. The example pool just shows compression as an example, but you can update any setting such as the compression algorithm. Is that what you're looking for?

**Comment by BlaineEXE** [comment]
@spdfnet could you be more clear as to which scenario you are attempting and what the failure mode is?

**Comment by Madhu-1** [comment]
>This is a problem with the CSI side of things if pools are created manually.

what is the exact problem with CSI?

**Comment by spdfnet** [comment]
Stumbled on this:
```
ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/cuac-rgw". failed to create object store deployments: failed to create object pools: failed to create data pool: failed to create pool "cuac-rgw.rgw.buckets.data": failed to create erasure code profile for pool "cuac-rgw.rgw.buckets.data": failed to look up default erasure code profile: failed to get erasure-code-profile for "default": exit status 2
```

Which means the default profile needs to exist before creating any pool with Rook.
That also means, the plugin and settings can be manually specified there... each time.

According to the documentation, this should be supported:
https://github.com/rook/rook/blob/master/design/ceph/data-model.md?plain=1#L25-L26

But only 'algorithm' is exposed
https://github.com/rook/rook/blob/master/pkg/apis/ceph.rook.io/v1/types.go#L963

I don't expect the Rook project to add another CRD or support all the Ceph features,
but having the possibility to define an EC profile would be nice.

**Comment by travisn** [comment]
hmm, not sure the algorithm is properly set anymore from rook, those may be a couple of old references you found. How did you get that error? You set the parameters in the pool CR? Could you share the pool CR?

**Comment by spdfnet** [comment]
You can get the same error by:
```
ceph osd erasure-code-profile rm default
```

**Comment by spdfnet** [comment]
@bot remove wontfix

**Comment by spdfnet** [comment]
> Why delete the default profile?
To prove the point that EC support is not configurable.

**Comment by spdfnet** [comment]
Yes, along with the [plugins](https://docs.ceph.com/en/latest/rados/operations/erasure-code/#table-of-content).

**Comment by bumarcell** [comment]
Was this added to some version? :D 
I had to create the ec-profile and pool with the same name rook will be generating, then create the cephfilesystem and hope it will be using that pool. 
Felt super wonky

**Comment by spdfnet** [comment]
@bumarcell I would advise you against using Rook for any serious production cluster that is not running inside OpenShift.

**Comment by travisn** [comment]
@bumarcell Rook will do the following:
1. Get the default profile: `ceph osd erasure-code-profile get default`
2. Create the EC profile based on the default plugin and technique

Is it an option to modify the plugin in the default profile? If that's not an option, sounds like we need to expose the setting in the cephblockpool CR and until then at least you found a wonky workaround.

**Comment by travisn** [comment]
> @bumarcell I would advise you against using Rook for any serious production cluster that is not running inside OpenShift.

@bumarcell Many are using rook in production across various K8s platforms. Do you have more context or why that comment is related to EC? I also happen to recommend OpenShift, but without details the community does not benefit, thanks.
