### ISSUE TITLE
ceph-object-controller-detect-version has been restarted without error

### ISSUE THREAD

**Issue by wolf27w** [rook/rook#9839]
ceph version 16.2.7
The service is always restarted. It will be automatically deleted after successful creation. There is no error. The event indicates that the creation is successful

**Comment by travisn** [comment]
If there is no error, what is the issue you are reporting? If you have a question, starting a [discussion](https://github.com/rook/rook/discussions/new) is preferred. If you have an issue, please provide the details that are in the issue template so we can understand the issue.

**Comment by wolf27w** [comment]
This error does not affect the use. It is built according to the official website and can be used normally after it is built. It only appears later. This is like the scheduled task check version. The pod log error is: unable to retrieve container logs for C ontainerd://b2761d674608f8445ae888f1c646e5b5304f22e5e4b56388e09ed6a96c7e37bc

**Comment by wolf27w** [comment]
rook version 1.8.2
ceph version 16.2.7

**Comment by BlaineEXE** [comment]
@wolf27w if you are experiencing an issue, it is not clear what that is from the description so far. If you wish to report a rook bug, please use "New Issue" and choose the "Bug Report" option. Fill out all fields so we can understand how to help.

**Comment by wolf27w** [comment]
My problem is that the CEPH object controller detect version service has been restarted, but it does not affect the use. I want to know whether the restart is normal
