### ISSUE TITLE
Startup probe failed: admin_socket: exception getting command descriptions: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by cdy07341** [rook/rook#9843]
**Is this a bug report or feature request?**

* Bug Report
* Feature Request

**Bug Report**
```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  2m37s                default-scheduler  Successfully assigned rook-ceph/rook-ceph-mon-a-canary-f9f496bdc-56g69 to rpm355.bddwd.baidu.com
  Normal   Killing    87s                  kubelet            Container mon failed startup probe, will be restarted
  Normal   Pulled     57s (x2 over 2m36s)  kubelet            Container image "bddwd-sys-rpm356.bddwd.baidu.com:8001/rook/ceph:v1.8.6" already present on machine
  Normal   Created    57s (x2 over 2m36s)  kubelet            Created container mon
  Normal   Started    56s (x2 over 2m35s)  kubelet            Started container mon
  Warning  Unhealthy  17s (x9 over 2m17s)  kubelet            Startup probe failed: admin_socket: exception getting command descriptions: [Errno 13] Permission denied
  Normal   Killing    12s                  kubelet            Stopping container mon
```

**Expected behavior:**

**Deviation from expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the GitHub UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Feature Request**

**Are there any similar features already existing:**

**What should the feature do:**

**What would be solved through this feature:**

**Does this have an impact on existing features:**

**Environment**:
* OS (e.g. from /etc/os-release):CentOS Linux release 7.5.1804 (Core)
* Kernel (e.g. `uname -a`): `Linux bddwd-sys-rpm356.bddwd.baidu.com 4.14.0_1-0-0-45 #2 SMP Tue Oct 19 18:27:28 CST 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):GKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by dmolik** [comment]
I'm also having this issue, I assume there's an issue with filesystem permissions someplace

**Comment by dmolik** [comment]
Is it possible the startup probe isn't being executed as the ceph user?

**Comment by dmolik** [comment]
if I exec into the container and run id, I'm the rook user

**Comment by dmolik** [comment]
this should work if we run as the ceph (167) user, right? so set it under the securitycontext, and then drop the `sh -c`?

**Comment by dmolik** [comment]
this is the patch I have going, haven't tested yet:
```
diff --git a/pkg/operator/ceph/cluster/mon/spec.go b/pkg/operator/ceph/cluster/mon/spec.go
index c817697dd..363223aab 100644
--- a/pkg/operator/ceph/cluster/mon/spec.go
+++ b/pkg/operator/ceph/cluster/mon/spec.go
@@ -210,6 +210,12 @@ func (c *Cluster) makeMonPod(monConfig *monConfig, canary bool) (*corev1.Pod, er
 	cephv1.GetMonAnnotations(c.spec.Annotations).ApplyToObjectMeta(&pod.ObjectMeta)
 	cephv1.GetMonLabels(c.spec.Labels).ApplyToObjectMeta(&pod.ObjectMeta)
 
+	if canary {
+		oneSixtySeven := int64(167)
+		pod.Spec.SecurityContext.RunAsUser = &oneSixtySeven
+		pod.Spec.SecurityContext.RunAsGroup = &oneSixtySeven
+	}
+
 	if c.spec.Network.IsHost() {
 		pod.Spec.DNSPolicy = corev1.DNSClusterFirstWithHostNet
 	} else if c.spec.Network.IsMultus() {
```

**Comment by BlaineEXE** [comment]
I'm a bit confused here. Are you seeing startup probe errors on canary pods?

**Comment by aBradleyUno** [comment]
👀 I'm following a tutorial and I found myself with this same message...

**Comment by parth-gr** [comment]
Do everyone see startup probe issue with canary pods,
The permission might look like a permission issue, have you tried restarting the pods which are in this state,
I hope it might work, otherwise, it might be something wrong with the keyring or maybe in ceph config.

**Comment by travisn** [comment]
As discussed separately, the startup probe needs to be removed from the mon canary pods.

**Comment by cellsbigoO** [comment]
I have such a problem. After waiting for a long time, started a mon-a. I checked `ceph statu` and displayed `mon is allowing secure global_ ID reclaim`, then I execute `ceph config set mon auth_ allow_ insecure_ global_ id_ reclaim false`
