### ISSUE TITLE
Ceph Rook crashes after 2 min of Healthy state

### ISSUE THREAD

**Issue by Alt-Shivam** [rook/rook#9844]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Kubernetes cluster as well as ubuntu machine crashes after 2 min of Ceph-Rook healthy run.

**Expected behavior:**
It should run continuously without any crashes,
as it runs in the beginning for 2 min.

**How to reproduce it (minimal and precise):**
Just create a 4 node kind cluster with 1 master and 3 worker nodes
Follow the official guide to deploy ceph-rook i.e https://rook.github.io/docs/rook/v1.8/quickstart.html

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

*can't submit any given files because machine crashes just after ceph-rook becomes healthy*

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu Focal 20.04
* Kernel (e.g. `uname -a`): Linux ubuntu 5.4.0-91-generic
* Cloud provider or hardware configuration: 20 cores, 32 GB of RAM and 250 GB storage
* Rook version (use `rook version` inside of a Rook Pod): v1.8
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.14
* Kubernetes version (use `kubectl version`): v1.23.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kind v0.11.1
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):
```
Sat Mar 5 1:20:32 PM
ubuntu: Sat Mar
5 07:50:31 2022

Python path configuration:
PYTHONHOME (not set)
PYTHONPATH = (not set)
program name = '/usr/bin/python3'
isolated 0
environment 1
user site = 1
import site 1
sys._base_executable '/usr/bin/python3'
sys.base_prefix = '/usr'
sys.base_exec_prefix = '/usr'
sys.executable = '/usr/bin/python3'
sys.prefix
'/usr'
sys.exec_prefix "/usr'
sys.path = [
"/usr/lib/python38.zip',
"/usr/lib/python3.8',
"/usr/lib/python3.8/lib-dynload',
]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'=15=T
Current thread 0x00007fba0792b740 (most recent call first):
<no Python frame>
```

**Comment by Alt-Shivam** [comment]
Also,
Here are some Screen Shots of Ubuntu machine
after rook-ceph crashes.
![Screenshot from 2022-03-05 13-34-01](https://user-images.githubusercontent.com/81817735/156874560-93a61caf-4f4c-4168-8c4b-f82475e15c69.png)
![Screenshot from 2022-03-05 13-33-46](https://user-images.githubusercontent.com/81817735/156874566-c9b0b832-7e9b-41b6-8965-ddb3b293a528.png)
![Screenshot from 2022-03-05 13-33-32](https://user-images.githubusercontent.com/81817735/156874575-fd997d97-940a-4a2b-b6e7-85ecc60047dc.png)

**Comment by Alt-Shivam** [comment]
Thanks @travisn for responding.
I am using a VM for this.

**Comment by Alt-Shivam** [comment]
Is there any way to change loopback device selection in Rook-Ceph ?
so that It cannot conflict with VM's operating system mount-points.

**Comment by travisn** [comment]
There are several ways to select which devices Rook should consume, such as with the `deviceFilter`. See the documentation [here](https://rook.github.io/docs/rook/v1.8/ceph-cluster-crd.html#storage-selection-settings).

**Comment by Alt-Shivam** [comment]
Got it,
Thanks @travisn

**Comment by Alt-Shivam** [comment]
Hey @travisn sir
I am facing an issue with ceph-mon 
showing CrashLoopBackOff due to some fssid error
could you please help me out.

**Comment by Alt-Shivam** [comment]
Logs

+ export LC_ALL=C
+ LC_ALL=C
+ : 1
+ : /etc/ceph/ceph.mon.keyring
+ : /etc/ceph/ceph.client.admin.keyring
+ : /var/lib/ceph/bootstrap-mds/ceph.keyring
+ : /var/lib/ceph/bootstrap-osd/ceph.keyring
+ : /etc/ceph/ceph.conf
+ [[ ! -e /etc/ceph/ceph.conf.template ]]
++ mon_host_from_k8s_ep ceph ceph-mon-discovery
++ local ns=ceph
++ local ep=ceph-mon-discovery
++ '[' -z ceph ']'
++ '[' -z ceph-mon-discovery ']'
++ kubectl get endpoints -n ceph ceph-mon-discovery -o 'go-template=
    {{- $sep := "" }}
    {{- range $_,$s := .subsets }}
      {{- $v2port := 0 }}
      {{- $v1port := 0 }}
      {{- range $_,$port := index $s "ports" }}
        {{- if (eq $port.name "mon-msgr2") }}
          {{- $v2port = $port.port }}
        {{- else if (eq $port.name "mon") }}
          {{- $v1port = $port.port }}
        {{- end }}
      {{- end }}
      {{- range $_,$address := index $s "addresses" }}
        {{- $v2endpoint := printf "v2:%s:%d/0" $address.ip $v2port }}
        {{- $v1endpoint := printf "v1:%s:%d/0" $address.ip $v1port }}
        {{- if (and $v2port $v1port) }}
          {{- printf "%s[%s,%s]" $sep $v2endpoint $v1endpoint }}
          {{- $sep = "," }}
        {{- else if $v2port }}
          {{- printf "%s[%s]" $sep $v2endpoint }}
          {{- $sep = "," }}
        {{- else if $v1port }}
          {{- printf "%s[%s]" $sep $v1endpoint }}
          {{- $sep = "," }}
        {{- end }}
      {{- end }}
    {{- end }}'
+ ENDPOINT='[v2:172.18.0.5:3300/0,v1:172.18.0.5:6789/0]'
+ [[ -z [v2:172.18.0.5:3300/0,v1:172.18.0.5:6789/0] ]]
+ /bin/sh -c -e 'cat /etc/ceph/ceph.conf.template | sed '\''s#mon_host.*#mon_host = [v2:172.18.0.5:3300/0,v1:172.18.0.5:6789/0]#g'\'' | tee /etc/ceph/ceph.conf'
[global]
cephx = true
cephx_cluster_require_signatures = true
cephx_require_signatures = false
cephx_service_require_signatures = false
debug_ms = 0/0
fsid = ${CEPH_FS_ID}
log_file = /dev/stdout
mon_addr = :6789
mon_cluster_log_file = /dev/stdout
mon_data_avail_warn = 15
mon_host = [v2:172.18.0.5:3300/0,v1:172.18.0.5:6789/0]
mon_osd_down_out_interval = 1800
mon_osd_down_out_subtree_limit = root
mon_osd_min_in_ratio = 0
mon_osd_min_up_ratio = 0
objecter_inflight_op_bytes = 1073741824
objecter_inflight_ops = 10240
osd_pool_default_size = 1
[osd]
cluster_network = 172.17.0.1/16
filestore_max_sync_interval = 10
filestore_merge_threshold = -10
filestore_split_multiple = 12
ms_bind_port_max = 7100
ms_bind_port_min = 6800
osd_crush_chooseleaf_type = 0
osd_deep_scrub_stride = 1048576
osd_journal_size = 10240
osd_max_object_name_len = 256
osd_mkfs_options_xfs = -f -i size=2048
osd_mkfs_type = xfs
osd_mount_options_xfs = rw,noatime,largeio,inode64,swalloc,logbufs=8,logbsize=256k,allocsize=4M
osd_pg_max_concurrent_snap_trims = 1
osd_recovery_max_active = 1
osd_recovery_op_priority = 1
osd_scrub_begin_hour = 22
osd_scrub_chunk_max = 4
osd_scrub_chunk_min = 1
osd_scrub_during_recovery = false
osd_scrub_end_hour = 4
osd_scrub_load_threshold = 10
osd_scrub_priority = 1
osd_scrub_sleep = 0.1
osd_snap_trim_priority = 1
osd_snap_trim_sleep = 0.1
public_network = 172.17.0.1/16
+ [[ -z 172.17.0.1/16 ]]
+ [[ -z 172.18.0.5 ]]
+ [[ 1 -eq 0 ]]
+ MON_NAME=kind-worker3
+ MON_DATA_DIR=/var/lib/ceph/mon/ceph-kind-worker3
+ MONMAP=/etc/ceph/monmap-ceph
+ /bin/sh -c 'mkdir -p "/var/lib/ceph/mon/ceph-kind-worker3"'
+ get_mon_config
++ ceph-conf --lookup fsid -c /etc/ceph/ceph.conf
parse error setting 'fsid' to '${CEPH_FS_ID}'
+ local 'fsid=$CEPH_FS_ID}'
+ timeout=10
+ MONMAP_ADD=
+ [[ -z '' ]]
+ [[ 10 -gt 0 ]]
+ [[ 1 -eq 0 ]]
++ kubectl get pods --namespace=ceph -l application=ceph -l component=mon -o template '--template={{range .items}}{{if .status.podIP}}--addv {{.spec.nodeName}} [v1:{{.status.podIP}}:6789,v2:{{.status.podIP}}:3300] {{end}} {{end}}'
+ MONMAP_ADD='--addv kind-worker3 [v1:172.18.0.5:6789,v2:172.18.0.5:3300]  '
+ ((  timeout--  ))
+ sleep 1
+ [[ -z --addvkind-worker3[v1:172.18.0.5:6789,v2:172.18.0.5:3300] ]]
+ [[ -z --addvkind-worker3[v1:172.18.0.5:6789,v2:172.18.0.5:3300] ]]
+ monmaptool --create --addv kind-worker3 '[v1:172.18.0.5:6789,v2:172.18.0.5:3300]' --fsid '$CEPH_FS_ID}' /etc/ceph/monmap-ceph --clobber
parse error setting 'fsid' to '$CEPH_FS_ID}'

monmaptool: monmap file /etc/ceph/monmap-ceph
monmaptool: generated fsid 4ad40559-a313-48ce-8379-accb18bb6da0
monmaptool: writing epoch 0 to /etc/ceph/monmap-ceph (1 monitors)
+ '[' '!' -e /var/lib/ceph/mon/ceph-kind-worker3/keyring ']'
+ '[' '!' -e /etc/ceph/ceph.mon.keyring.seed ']'
+ cp -vf /etc/ceph/ceph.mon.keyring.seed /etc/ceph/ceph.mon.keyring
'/etc/ceph/ceph.mon.keyring.seed' -> '/etc/ceph/ceph.mon.keyring'
+ '[' '!' -e /etc/ceph/monmap-ceph ']'
+ for KEYRING in ${OSD_BOOTSTRAP_KEYRING} ${MDS_BOOTSTRAP_KEYRING} ${ADMIN_KEYRING}
+ ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-osd/ceph.keyring
importing contents of /var/lib/ceph/bootstrap-osd/ceph.keyring into /etc/ceph/ceph.mon.keyring
+ for KEYRING in ${OSD_BOOTSTRAP_KEYRING} ${MDS_BOOTSTRAP_KEYRING} ${ADMIN_KEYRING}
+ ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /var/lib/ceph/bootstrap-mds/ceph.keyring
importing contents of /var/lib/ceph/bootstrap-mds/ceph.keyring into /etc/ceph/ceph.mon.keyring
+ for KEYRING in ${OSD_BOOTSTRAP_KEYRING} ${MDS_BOOTSTRAP_KEYRING} ${ADMIN_KEYRING}
+ ceph-authtool /etc/ceph/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring
importing contents of /etc/ceph/ceph.client.admin.keyring into /etc/ceph/ceph.mon.keyring
+ ceph-mon --setuser ceph --setgroup ceph --cluster ceph --mkfs -i kind-worker3 --inject-monmap /etc/ceph/monmap-ceph --keyring /etc/ceph/ceph.mon.keyring --mon-data /var/lib/ceph/mon/ceph-kind-worker3
parse error setting 'fsid' to '${CEPH_FS_ID}'
ignoring --setuser ceph since I am not root
ignoring --setgroup ceph since I am not root
2022-03-11T16:46:00.008+0000 7f27b67a0540 -1 ceph-mon: generated monmap has no fsid; use '--fsid <uuid>'
2022-03-11T16:46:00.008+0000 7f27b67a0540  1 initial generated monmap:
epoch 0
fsid 00000000-0000-0000-0000-000000000000
last_changed 2022-03-11T16:46:00.010288+0000
created 2022-03-11T16:46:00.010288+0000
min_mon_release 0 (unknown)
0: [v2:172.18.0.5:3300/0,v1:172.18.0.5:6789/0] mon.noname-a

2022-03-11T16:46:00.008+0000 7f27b67a0540  0  monmap addrs are v2:172.18.0.5:3300/0,v1:172.18.0.5:6789/0, checking if any are local
2022-03-11T16:46:00.008+0000 7f27b67a0540  0  have local addr v2:172.18.0.5:3300/0
2022-03-11T16:46:00.008+0000 7f27b67a0540  0 ceph-mon: mon.noname-a v2:172.18.0.5:3300/0 is local, renaming to mon.kind-worker3
2022-03-11T16:46:00.008+0000 7f27b67a0540 -1 ceph-mon: generated monmap has no fsid; use '--fsid <uuid>'

**Comment by Alt-Shivam** [comment]
Hey @travisn sir
While trying to deploy ceph, I came across an error with osd creation 
and I am using physical disks for osd creation.

LOGS:
+++osd-common-ceph-volume.sh:108:locked(): pvdisplay -ddd -v /dev/xvdb
File descriptor 10 (/var/lib/ceph/tmp/init-osd.lock) leaked on pvdisplay invocation. Parent PID 25891: /bin/bash
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
    Wiping internal VG cache
    Wiping cache of LVM-capable devices
++osd-common-ceph-volume.sh:572:get_lv_name_from_device(): pv_uuid=p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1
++osd-common-ceph-volume.sh:574:get_lv_name_from_device(): [[ -n p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1 ]]
++osd-common-ceph-volume.sh:575:get_lv_name_from_device(): echo ceph-lv-p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1
+init-ceph-volume.sh:156:create_lv_if_needed(): local lv_name=ceph-lv-p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1
++init-ceph-volume.sh:158:create_lv_if_needed(): locked lvdisplay
++init-ceph-volume.sh:158:create_lv_if_needed(): grep ceph-lv-p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1
++init-ceph-volume.sh:158:create_lv_if_needed(): awk '/LV Name/{print $3}'
++osd-common-ceph-volume.sh:108:locked(): lvdisplay
File descriptor 10 (/var/lib/ceph/tmp/init-osd.lock) leaked on lvdisplay invocation. Parent PID 25914: /bin/bash
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
+init-ceph-volume.sh:158:create_lv_if_needed(): [[ ! -n '' ]]
+init-ceph-volume.sh:159:create_lv_if_needed(): locked lvcreate --yes -l 100%FREE -n ceph-lv-p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1 ceph-vg-p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1
+osd-common-ceph-volume.sh:108:locked(): lvcreate --yes -l 100%FREE -n ceph-lv-p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1 ceph-vg-p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1
File descriptor 10 (/var/lib/ceph/tmp/init-osd.lock) leaked on lvcreate invocation. Parent PID 24486: /bin/bash
  WARNING: Failed to connect to lvmetad. Falling back to device scanning.
  /dev/ceph-vg-p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1/ceph-lv-p0Mx2B-8Q1P-j4de-TOyM-u7Py-peBK-J3eMj1: not found: device not cleared
  Aborting. Failed to wipe start of new LV.




lsblk:

NAME     MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0      7:0    0  61.9M  1 loop /snap/core20/1270
loop1      7:1    0  67.2M  1 loop /snap/lxd/21835
loop2      7:2    0  43.6M  1 loop /snap/snapd/15177
loop3      7:3    0  61.9M  1 loop /snap/core20/1376
loop4      7:4    0  43.6M  1 loop /snap/snapd/14978
loop5      7:5    0  67.9M  1 loop /snap/lxd/22526
loop10     7:10   0    10G  0 loop 
loop11     7:11   0     8G  0 loop 
xvda     202:0    0   150G  0 disk 
├─xvda1  202:1    0 149.9G  0 part /
├─xvda14 202:14   0     4M  0 part 
└─xvda15 202:15   0   106M  0 part /boot/efi
xvdb     202:16   0    50G  0 disk 
xvdc     202:32   0    50G  0 disk 
xvde     202:64   0    10M  0 disk 


Using xvdb and xvdc for osd



will really appreciate if you could help me out sir

**Comment by Alt-Shivam** [comment]
Thanks for the reply @travisn sir
will definitely try this out \
