### ISSUE TITLE
Keyring secrets no longer deleted with deployments

### ISSUE THREAD

**Issue by BlaineEXE** [rook/rook#9860]
**Is this a bug report or feature request?**
* Bug Report

At one time, keyring secrets `<deployment-name>-keyring` were created with an owner reference belonging to the deployment itself. This made deletion of keyrings implicit with deletion of a deployment. At some point, this was changed, and the keyring secrets are now owned by the resource itself (e.g., CephCluster, CephFilesystem, etc.). As a result, keyrings are not removed when deployments are removed. 

It's possible that other resources (services, configmaps, etc.) may once have been owned by deployments as well, and that may also have changed. I haven't yet tracked down the source of the change, though I suspect it may have some of @leseb 's work to change to controller-runtime or otherwise change the overall controller structure.

It would be good to audit what owner references changed and to update all the controllers to ensure keyring secrets get deleted with deployments, in addition to whatever other resources are now no longer implicitly removed. I first noticed this while working on https://github.com/rook/rook/pull/9859. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by travisn** [comment]
Just to be clear, which deployments have keyrings associated with them? mds? any others? I don't recall offhand.

**Comment by BlaineEXE** [comment]
All deployments, with a special exception for mons which all share a single keyring. 

During any reconcile, Rook uses `ceph auth get-or-create` to get (or create) the most up-to-date key for a daemon. It then puts the key into a secret with the name `<deployment-name>-keyring`. That secret is mounted into the deployment for the daemon inside to read in order to auth with the Ceph cluster.

**Comment by leseb** [comment]
The only thing I remember is that we ended up in some sort of a deadlock. Isn't that related to one of the things in https://github.com/rook/rook/issues/4089?

**Comment by BlaineEXE** [comment]
It does look related to #4089, but I don't think that's all of it. Elise Gafford updated the secret generation to be two-parted in response to that issue. One for creating the secret and the other to `associate` the secret. Those `associateX` methods seem like they have since been stripped out of Rook.

**Comment by BlaineEXE** [comment]
It looks like @leseb your PR https://github.com/rook/rook/pull/5319 removed those `associate` calls. It's not clear to me why though.
