### ISSUE TITLE
will add 'additionalPrinterColumns' for cephblockpool like "status"?

### ISSUE THREAD

**Issue by zhucan** [rook/rook#9883]

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/157637299-7dec6196-78f1-4124-bae7-3bdb9ce4f80c.png)

**Comment by travisn** [comment]
Can you be more specific? If you look at the status of the cephblockpool CR (`kubectl -n rook-ceph get cephblockpool -o yaml`), what fields do you see that would be useful to expose in the additional printer columns?

**Comment by zhucan** [comment]
Because of  we want to get the status not throught the "-o yaml" or "kubectl describe"
