### ISSUE TITLE
On edit of replica pool manifest, operator should resize pool accordingly

### ISSUE THREAD

**Issue by ftab** [rook/rook#989]
From [discussion on slack](https://rook-io.slack.com/archives/C46Q5UC05/p1505765559000473)

Steps:
1. kubectl edit -n rook pool _replicapool_
1. Change spec\replication\size parameter to something else, say 3

Expected result:
It does the `ceph osd pool set replicapool size 3` for you

**Comment by travisn** [comment]
note that the size can only be changed for pools that are already configured for replication. If you have an erasure-coded pool, you won't be able to change it to a replicated pool.

**Comment by kokhang** [comment]
CRDs should have validation we can leverage for this. https://github.com/kubernetes/kubernetes/pull/47263

**Comment by galexrt** [comment]
@kokhang Are you sure we already want to use this feature? The docs read:
