### ISSUE TITLE
Monitoring (mon, osd, status) does not start after stopping

### ISSUE THREAD

**Issue by manachyn** [rook/rook#9911]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

After reloading operator's CRDs manager and cancelling all orchestrations status monitoring does not start and Ceph status is not updated on the cluster CR

**Expected behavior:**

Ceph status is synchronized with the value in the cluster resource.

**File(s) to submit**:

* Cluster CR (custom resource)
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  annotations:
    meta.helm.sh/release-name: rook-cluster
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2022-03-15T12:13:07Z"
  finalizers:
  - cephcluster.ceph.rook.io
  generation: 7
  labels:
    app.kubernetes.io/managed-by: Helm
  name: rook-ceph
  namespace: kube-system
  resourceVersion: "21327"
  uid: 48270e97-00d9-493b-a565-058931f46800
spec:
  cephVersion:
    image: ceph:v16.2.7
  cleanupPolicy:
    sanitizeDisks: {}
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  crashCollector: {}
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement: {}
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        timeout: 6m
      osd: {}
      status: {}
  logCollector: {}
  mgr:
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
  monitoring:
    enabled: true
    rulesNamespace: kube-system
  network: {}
  resources:
    mon:
      requests:
        cpu: 100m
    osd:
      limits:
        memory: 8Gi
      requests:
        cpu: 100m
        memory: "0"
  security:
    kms: {}
  storage:
    nodes:
    - devices:
      - config:
          deviceClass: ssd
        name: sda
      - config:
          deviceClass: hdd
        name: sdc
      - config:
          deviceClass: hdd
        name: sdd
      - config:
          deviceClass: hdd
        name: sde
      - config:
          deviceClass: hdd
        name: sdf
      - config:
          deviceClass: hdd
        name: sdg
      - config:
          deviceClass: hdd
        name: sdh
      - config:
          deviceClass: hdd
        name: sdi
      name: server45
      resources: {}
    - devices:
      - config:
          deviceClass: ssd
        name: sdh
      - config:
          deviceClass: hdd
        name: sda
      - config:
          deviceClass: hdd
        name: sdb
      - config:
          deviceClass: hdd
        name: sdc
      - config:
          deviceClass: hdd
        name: sdd
      - config:
          deviceClass: hdd
        name: sdf
      - config:
          deviceClass: hdd
        name: sdg
      - config:
          deviceClass: hdd
        name: sdi
      - config:
          deviceClass: hdd
        name: sdj
      name: server46
      resources: {}
    - devices:
      - config:
          deviceClass: hdd
        name: sda
      - config:
          deviceClass: hdd
        name: sdb
      - config:
          deviceClass: hdd
        name: sdc
      - config:
          deviceClass: ssd
        name: nvme1n1
      name: server49
      resources: {}
    useAllDevices: false
status:
  ceph:
    capacity: {}
    details:
      TOO_FEW_OSDS:
        message: OSD count 0 < osd_pool_default_size 1
        severity: HEALTH_WARN
    health: HEALTH_WARN
    lastChanged: "2022-03-15T12:17:46Z"
    lastChecked: "2022-03-15T12:17:46Z"
    previousHealth: HEALTH_OK
    versions:
      mgr:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable): 1
      mon:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable): 1
      overall:
        ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable): 2
  conditions:
  - lastHeartbeatTime: "2022-03-15T12:42:46Z"
    lastTransitionTime: "2022-03-15T12:16:37Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
  message: Cluster created successfully
  phase: Ready
  state: Created
  version:
    image: ceph:v16.2.7
    version: 16.2.7-0
```

* Operator's logs
```
2022-03-15 12:18:45.017579 I | ceph-cluster-controller: CR has changed for "rook-ceph". diff=  v1.ClusterSpec{
2022-03-15 12:18:45.017732 I | operator: reloading operator's CRDs manager, cancelling all orchestrations!
2022-03-15 12:18:45.018036 I | op-osd: stopping monitoring of OSDs in namespace "kube-system"
2022-03-15 12:18:45.018102 I | ceph-cluster-controller: stopping monitoring of ceph status
2022-03-15 12:18:45.018111 I | operator: successfully started the controller-runtime manager
2022-03-15 12:18:45.018176 I | op-mon: stopping monitoring of mons in namespace "kube-system"
2022-03-15 12:18:45.027394 I | op-k8sutil: ROOK_CURRENT_NAMESPACE_ONLY="false" (env var)
2022-03-15 12:18:45.027416 I | operator: watching all namespaces for Ceph CRs
2022-03-15 12:18:45.027455 I | operator: setting up schemes
2022-03-15 12:18:45.030592 I | operator: setting up the controller-runtime manager
```

* Storage backend status

```
  cluster:
    id:     9b41a0ef-e917-4213-921b-2e6697c6bd5f
    health: HEALTH_OK
            (muted: MANY_OBJECTS_PER_PG(6d) PG_AVAILABILITY(6d) PG_DEGRADED(6d))
 
  services:
    mon: 3 daemons, quorum a,c,b (age 46m)
    mgr: a(active, since 64m)
    osd: 21 osds: 21 up (since 39m), 21 in (since 40m)
 
  data:
    pools:   11 pools, 2561 pgs
    objects: 1.02k objects, 3.2 GiB
    usage:   9.8 GiB used, 11 TiB / 11 TiB avail
    pgs:     2561 active+clean
 
  io:
    client:   362 KiB/s wr, 0 op/s rd, 1 op/s wr

```

**Environment**:
* OS

NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3033.2.3
VERSION_ID=3033.2.3
BUILD_ID=2022-03-02-2032
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3033.2.3 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"

* Kernel (e.g. `uname -a`):

Linux server45 5.10.102-flatcar #1 SMP Wed Mar 2 19:40:13 -00 2022 x86_64 Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz GenuineIntel GNU/Linux

* Cloud provider or hardware configuration:
Bare-metal

* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.8.7
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.4-dirty", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"dirty", BuildDate:"2022-02-18T07:23:07Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

**Comment by travisn** [comment]
So the issue is that you updated the CephCluster CR, then the operator just cancelled everything and stopped working? In this log snippet, I assume you removed the details about the update on the first line? Normally it is quite verbose for the changes.
```
2022-03-15 12:18:45.017579 I | ceph-cluster-controller: CR has changed for "rook-ceph". diff=  v1.ClusterSpec{
2022-03-15 12:18:45.017732 I | operator: reloading operator's CRDs manager, cancelling all orchestrations!
2022-03-15 12:18:45.018036 I | op-osd: stopping monitoring of OSDs in namespace "kube-system"
```

Did restarting the operator pod workaround the issue to get everything working again?

If this repro's consistently for you, it would be helpful if you could share the steps to do this. Normally the operator would of course continue monitoring after the update, and I have not seen this issue.

**Comment by manachyn** [comment]
Yes, this problem is reproduced constantly in my environment. Restarting the operator solves the problem.

[https://github.com/rook/rook/blob/v1.8.7/pkg/operator/ceph/cluster/monitoring.go#L40](url)

Looking at the code, it seems to me that the case is not processed if health.internalCtx.Err() != nil: when monitoring was stopped (the context was canceled, but the value of health remained in the map). In this case, monitoring is not restarted

**Comment by travisn** [comment]
Even though it's cancelled, the monitoring should be restarted by the next reconcile, so the issue seems that the next reconcile was not triggered. @leseb thoughts?

**Comment by manachyn** [comment]
Next reconcile is triggered, but it does not reach the monitoring enable point, because the memory entry remains with the old value of cluster.monitoringRoutines[daemon]
