### ISSUE TITLE
AccessDenied: UnknownError happens if creating bucket fails and re-create succeeds

### ISSUE THREAD

**Issue by toshipp** [rook/rook#9922]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Any requests to rgw using s3 API fail.

**Expected behavior:**
Requests to rgw using s3 API succeed.

**How to reproduce it (minimal and precise):**

1. Apply an obc to kubernetes

```
kind: ObjectBucketClaim
metadata:
  name: thumbnail-testing
spec:
  generateBucketName: thumbnail-testing
  storageClassName: ceph-object-store-bucket
```

2. rook fails to create a bucket for obc, but tries it again, then creates it successfully.
3. access to rgw using credential from secrets. this fails due to AccessDenied: UnknownError

```
export AWS_ACCESS_KEY_ID=<from a secret>
export AWS_SECRET_ACCESS_KEY=<from a secret>
aws --endpoint-url http://<bucket_host> s3 ls s3://
```

**File(s) to submit**:

operator log (omitted because it contains internal information)

```
I0317 01:29:22.805034       1 controller.go:218]  "msg"="reconciling claim" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:29:22.805054       1 helpers.go:107]  "msg"="getting claim for key" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:29:22.812076       1 helpers.go:213]  "msg"="getting ObjectBucketClaim's StorageClass" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:29:22.816557       1 helpers.go:218]  "msg"="got StorageClass" "key"="app-csa-thumbnail/thumbnail-testing" "name"="ceph-object-store-bucket"
I0317 01:29:22.816584       1 helpers.go:90]  "msg"="checking OBC for OB name, this indicates provisioning is complete" "key"="app-csa-thumbnail/thumbnail-testing" "thumbnail-testing"=null
I0317 01:29:22.816627       1 resourcehandlers.go:446]  "msg"="updating status:" "key"="app-csa-thumbnail/thumbnail-testing" "new status"="Pending" "obc"="app-csa-thumbnail/thumbnail-testing" "old status"=""
I0317 01:29:22.826855       1 controller.go:283]  "msg"="syncing obc creation" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:29:22.826923       1 controller.go:630]  "msg"="updating OBC metadata" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:29:22.826941       1 resourcehandlers.go:436]  "msg"="updating" "key"="app-csa-thumbnail/thumbnail-testing" "obc"="app-csa-thumbnail/thumbnail-testing"
I0317 01:29:22.837761       1 resourcehandlers.go:436]  "msg"="updating" "key"="app-csa-thumbnail/thumbnail-testing" "obc"="app-csa-thumbnail/thumbnail-testing"
I0317 01:29:22.848988       1 resourcehandlers.go:148]  "msg"="seeing if OB for OBC exists" "key"="app-csa-thumbnail/thumbnail-testing" "checking for OB name"="obc-app-csa-thumbnail-thumbnail-testing"
E0317 01:29:22.849300       1 controller.go:669]  "msg"="invalid changes to OBC. only additionalConfig can be updated" "error"=null "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:29:22.853199       1 controller.go:406]  "msg"="provisioning" "key"="app-csa-thumbnail/thumbnail-testing" "bucket"="thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d"
2022-03-17 01:29:22.853217 I | op-bucket-prov: initializing and setting CreateOrGrant services
2022-03-17 01:29:22.853231 I | op-bucket-prov: getting storage class "ceph-object-store-bucket"
2022-03-17 01:29:48.033936 I | op-bucket-prov: Provision: creating bucket "thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d" for OBC "thumbnail-testing"
2022-03-17 01:29:48.041265 I | op-bucket-prov: creating Ceph user "ceph-user-YeSVM3M2"
2022-03-17 01:29:48.878051 I | op-bucket-prov: successfully created Ceph user "ceph-user-YeSVM3M2" with access keys
2022-03-17 01:29:48.878291 I | ceph-object-controller: creating bucket "thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d"
2022-03-17 01:31:20.440703 E | op-bucket-prov: error creating bucket "thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d": failed to create bucket "thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d": RequestError: send request failed
caused by: Put "[http://rook-ceph-rgw-ceph-object-store-0.ceph-object-store.svc:80/thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d](http://rook-ceph-rgw-ceph-object-store-0.ceph-object-store.svc/thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022-03-17 01:31:20.440739 I | op-bucket-prov: deleting Ceph user "ceph-user-YeSVM3M2" and bucket ""
2022-03-17 01:31:20.466785 I | op-bucket-prov: user "ceph-user-YeSVM3M2" successfully deleted
E0317 01:31:20.466900       1 controller.go:205] error syncing 'app-csa-thumbnail/thumbnail-testing': error provisioning bucket: error creating bucket "thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d": failed to create bucket "thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d": RequestError: send request failed
caused by: Put "[http://rook-ceph-rgw-ceph-object-store-0.ceph-object-store.svc:80/thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d](http://rook-ceph-rgw-ceph-object-store-0.ceph-object-store.svc/thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d)": context deadline exceeded (Client.Timeout exceeded while awaiting headers), requeuing
...
I0317 01:32:14.995934       1 controller.go:218]  "msg"="reconciling claim" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:14.995940       1 helpers.go:107]  "msg"="getting claim for key" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:15.001476       1 helpers.go:213]  "msg"="getting ObjectBucketClaim's StorageClass" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:15.006663       1 helpers.go:218]  "msg"="got StorageClass" "key"="app-csa-thumbnail/thumbnail-testing" "name"="ceph-object-store-bucket"
I0317 01:32:15.006687       1 helpers.go:90]  "msg"="checking OBC for OB name, this indicates provisioning is complete" "key"="app-csa-thumbnail/thumbnail-testing" "thumbnail-testing"=null
I0317 01:32:15.006710       1 resourcehandlers.go:446]  "msg"="updating status:" "key"="app-csa-thumbnail/thumbnail-testing" "new status"="Pending" "obc"="app-csa-thumbnail/thumbnail-testing" "old status"="Pending"
I0317 01:32:15.017626       1 controller.go:283]  "msg"="syncing obc creation" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:15.017655       1 controller.go:630]  "msg"="updating OBC metadata" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:15.017673       1 resourcehandlers.go:436]  "msg"="updating" "key"="app-csa-thumbnail/thumbnail-testing" "obc"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:15.028200       1 resourcehandlers.go:148]  "msg"="seeing if OB for OBC exists" "key"="app-csa-thumbnail/thumbnail-testing" "checking for OB name"="obc-app-csa-thumbnail-thumbnail-testing"
I0317 01:32:15.032519       1 controller.go:406]  "msg"="provisioning" "key"="app-csa-thumbnail/thumbnail-testing" "bucket"="thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d"
2022-03-17 01:32:15.032531 I | op-bucket-prov: initializing and setting CreateOrGrant services
2022-03-17 01:32:15.032542 I | op-bucket-prov: getting storage class "ceph-object-store-bucket"
2022-03-17 01:32:34.629902 I | op-bucket-prov: Provision: creating bucket "thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d" for OBC "thumbnail-testing"
2022-03-17 01:32:34.637687 I | op-bucket-prov: creating Ceph user "ceph-user-dmhpCnSL"
2022-03-17 01:32:34.653003 I | op-bucket-prov: successfully created Ceph user "ceph-user-dmhpCnSL" with access keys
2022-03-17 01:32:34.653104 I | ceph-object-controller: creating bucket "thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d"
2022-03-17 01:32:49.721685 I | op-bucket-prov: set user "ceph-user-dmhpCnSL" bucket max to 1
I0317 01:32:49.721808       1 helpers.go:107]  "msg"="getting claim for key" "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:49.737721       1 resourcehandlers.go:187]  "msg"="creating Secret" "key"="app-csa-thumbnail/thumbnail-testing" "name"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:49.746780       1 resourcehandlers.go:210]  "msg"="creating ConfigMap" "key"="app-csa-thumbnail/thumbnail-testing" "name"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:49.752045       1 resourcehandlers.go:119]  "msg"="creating ObjectBucket" "key"="app-csa-thumbnail/thumbnail-testing" "name"="obc-app-csa-thumbnail-thumbnail-testing"
I0317 01:32:49.761042       1 resourcehandlers.go:463]  "msg"="updating status:" "key"="app-csa-thumbnail/thumbnail-testing" "new status"="Bound" "ob"="obc-app-csa-thumbnail-thumbnail-testing" "old status"=""
I0317 01:32:49.768961       1 resourcehandlers.go:436]  "msg"="updating" "key"="app-csa-thumbnail/thumbnail-testing" "obc"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:49.779162       1 resourcehandlers.go:446]  "msg"="updating status:" "key"="app-csa-thumbnail/thumbnail-testing" "new status"="Bound" "obc"="app-csa-thumbnail/thumbnail-testing" "old status"="Pending"
E0317 01:32:49.779471       1 controller.go:669]  "msg"="invalid changes to OBC. only additionalConfig can be updated" "error"=null "key"="app-csa-thumbnail/thumbnail-testing"
I0317 01:32:49.789089       1 controller.go:499]  "msg"="provisioning succeeded" "key"="app-csa-thumbnail/thumbnail-testing
```

**Environment**:
* OS (e.g. from /etc/os-release):Flatcar Container Linux by Kinvolk 3033.2.3 (Oklo)
* Kernel (e.g. `uname -a`):5.10.102-flatcar
* Cloud provider or hardware configuration:on-prem
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):1.8.3
* Kubernetes version (use `kubectl version`):v1.22.5
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

My observation:
1. Rook created user ceph-user-YeSVM3M2, but deleted it later because bucket creation was timed out. I assume this creation succeeds in ceph cluster.
2. On next reconcile, rook created another user ceph-user-dmhpCnSL and created the bucket again. This creation seemd to be failed due to AlreadyExist error but rook regards this as success.
https://github.com/rook/rook/blob/a99f8985b0785fc8ed8b7b55dae4bf8722761498/pkg/operator/ceph/object/s3-handlers.go#L109-L111
3. Rook stores credentials for ceph-user-dmhpCnSL to a secret, but the bucket is owed by old user ceph-user-YeSVM3M2.

```
kubectl exec -n ceph-object-store deploy/rook-ceph-tools -- radosgw-admin bucket stats --bucket=thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d
{
    "bucket": "thumbnail-testing-6d4449bb-b977-42fd-a74e-93f7f56abc8d",
    "num_shards": 11,
    "tenant": "",
    "zonegroup": "33d7fa87-da2e-4df7-9572-a8d939fc04fe",
    "placement_rule": "default-placement",
    "explicit_placement": {
        "data_pool": "",
        "data_extra_pool": "",
        "index_pool": ""
    },
    "id": "67ade7e7-b37b-486e-a969-5d39c507d06d.20209686.2",
    "marker": "67ade7e7-b37b-486e-a969-5d39c507d06d.20209686.2",
    "index_type": "Normal",
    "owner": "ceph-user-YeSVM3M2",
    "ver": "0#1,1#1,2#1,3#1,4#1,5#1,6#1,7#1,8#1,9#1,10#1",
    "master_ver": "0#0,1#0,2#0,3#0,4#0,5#0,6#0,7#0,8#0,9#0,10#0",
    "mtime": "2022-03-17T01:30:22.893637Z",
    "creation_time": "2022-03-17T01:30:19.006280Z",
    "max_marker": "0#,1#,2#,3#,4#,5#,6#,7#,8#,9#,10#",
    "usage": {},
    "bucket_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    }
}
```
4. credentials in the secret is invalid, so any access will be AccessDenied: UnknownError

**Comment by travisn** [comment]
@toshipp Some basic questions first... Does the `ceph status` show that the cluster is healthy? And you have at least three OSDs on separate nodes?

**Comment by toshipp** [comment]
When the issue happened, ceph status was HEALTH_WARN because of slow ops.
We deployed 24 osds on different nodes.

**Comment by thotz** [comment]
Yaa, Rook / adminsOps api `bucket Exist` as not error. IMO it is better to delete the backend bucket via `radosgw-admin` command. Also better to use  `generateBucketName`(prefix) to `bucketName`avoid such errors

**Comment by BlaineEXE** [comment]
I'm not sure how I missed this BZ. The behavior here is unexpected and obviously wrong. And very confusing. The log reports that Rook successfully deleted user `ceph-user-YeSVM3M2`.

I think you may be on the right track.

```go
_, err := s.Client.CreateBucket(bucketInput)
	if err != nil {
		if aerr, ok := err.(awserr.Error); ok {
			logger.Debugf("DEBUG: after s3 call, ok=%v, aerr=%v", ok, aerr)
			switch aerr.Code() {
			case s3.ErrCodeBucketAlreadyExists:
				logger.Debugf("bucket %q already exists", name)
				return nil
			case s3.ErrCodeBucketAlreadyOwnedByYou:
				logger.Debugf("bucket %q already owned by you", name)
				return nil
			}
		}
		return errors.Wrapf(err, "failed to create bucket %q", name)
	}

	if infoLogging {
		logger.Infof("successfully created bucket %q", name)
	} else {
		logger.Debugf("successfully created bucket %q", name)
	}
```

We should probably be treating `s3.ErrCodeBucketAlreadyExists` as an error but `s3.ErrCodeBucketAlreadyOwnedByYou` as a success. Furthermore, the underlying issue is likely that when we fail to create the bucket, we assume the bucket doesn't exist in Ceph, so we don't try to delete the bucket. But we probably do want to attempt to delete the bucket. This may be more complex that it first seems however. 

Perhaps @cbodley has some information about how Ceph RGW reports ErrCodeBucketAlreadyExists vs ErrCodeBucketAlreadyOwnedByYou that could help.

**Comment by thotz** [comment]
> I'm not sure how I missed this BZ. The behavior here is unexpected and obviously wrong. And very confusing. The log reports that Rook successfully deleted user `ceph-user-YeSVM3M2`.
> 
> I think you may be on the right track.
> 
> ```go
> _, err := s.Client.CreateBucket(bucketInput)
> 	if err != nil {
> 		if aerr, ok := err.(awserr.Error); ok {
> 			logger.Debugf("DEBUG: after s3 call, ok=%v, aerr=%v", ok, aerr)
> 			switch aerr.Code() {
> 			case s3.ErrCodeBucketAlreadyExists:
> 				logger.Debugf("bucket %q already exists", name)
> 				return nil
> 			case s3.ErrCodeBucketAlreadyOwnedByYou:
> 				logger.Debugf("bucket %q already owned by you", name)
> 				return nil
> 			}
> 		}
> 		return errors.Wrapf(err, "failed to create bucket %q", name)
> 	}
> 
> 	if infoLogging {
> 		logger.Infof("successfully created bucket %q", name)
> 	} else {
> 		logger.Debugf("successfully created bucket %q", name)
> 	}
> ```
> 
> We should probably be treating `s3.ErrCodeBucketAlreadyExists` as an error but `s3.ErrCodeBucketAlreadyOwnedByYou` as a success. Furthermore, the underlying issue is likely that when we fail to create the bucket, we assume the bucket doesn't exist in Ceph, so we don't try to delete the bucket. But we probably do want to attempt to delete the bucket. This may be more complex that it first seems however.
> 
> Perhaps @cbodley has some information about how Ceph RGW reports ErrCodeBucketAlreadyExists vs ErrCodeBucketAlreadyOwnedByYou that could help.

I have created a PR bit back to handle a similar situation https://github.com/rook/rook/pull/6619

**Comment by BlaineEXE** [comment]
> I have created a PR bit back to handle a similar situation #6619

I think the problems I see with that approach, given this PR are that we should keep in mind that operator behavior should default to being idempotent. I would instead treat `s3.ErrCodeBucketAlreadyExists` as an error and treat `s3. ErrCodeBucketAlreadyOwnedByYou` as a success so that calling `createBucket()` twice won't cause an error unnecessarily.

I think we also would want to handle the underlying issue I mentioned here:
> the underlying issue is likely that when we fail to create the bucket, we assume the bucket doesn't exist in Ceph, so we don't try to delete the bucket. But we probably do want to attempt to delete the bucket. This may be more complex that it first seems however.

**Comment by cbodley** [comment]
> I think we also would want to handle the underlying issue I mentioned here:
> 
> > the underlying issue is likely that when we fail to create the bucket, we assume the bucket doesn't exist in Ceph, so we don't try to delete the bucket. But we probably do want to attempt to delete the bucket. This may be more complex that it first seems however.

if you're deleting an rgw user that you know was created by rook (so doesn't own other unrelated buckets/data), you might consider doing that with `radosgw-admin user rm --purge-data` which also deletes the user's buckets/objects

**Comment by cbodley** [comment]
it probably returns ENOENT in that case

**Comment by thotz** [comment]
> > I have created a PR bit back to handle a similar situation #6619
> 
> I think the problems I see with that approach, given this PR are that we should keep in mind that operator behavior should default to being idempotent. I would instead treat `s3.ErrCodeBucketAlreadyExists` as an error and treat `s3. ErrCodeBucketAlreadyOwnedByYou` as a success so that calling `createBucket()` twice won't cause an error unnecessarily.
> 
> I think we also would want to handle the underlying issue I mentioned here:
> 
> > the underlying issue is likely that when we fail to create the bucket, we assume the bucket doesn't exist in Ceph, so we don't try to delete the bucket. But we probably do want to attempt to delete the bucket. This may be more complex that it first seems however.

There are other cases that need to be considered here like brownfield bucket, reclaim policy etc.

**Comment by toshipp** [comment]
I think this still opens.
