### ISSUE TITLE
 ceph rgw client version 0.12 does not have RemoveUserCap function

### ISSUE THREAD

**Issue by gongysh2004** [rook/rook#9938]
**Is this a bug report or feature request?**
* Bug Report

[{
	"resource": "/Users/yongshenggong/rook/pkg/operator/ceph/object/user/controller.go",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "MissingFieldOrMethod",
		"target": {
			"$mid": 1,
			"external": "https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#MissingFieldOrMethod",
			"path": "/golang.org/x/tools/internal/typesinternal",
			"scheme": "https",
			"authority": "pkg.go.dev",
			"query": "utm_source=gopls",
			"fragment": "MissingFieldOrMethod"
		}
	},
	"severity": 8,
	"message": "r.objContext.AdminOpsClient.RemoveUserCap undefined (type *admin.API has no field or method RemoveUserCap)",
	"source": "compiler",
	"startLineNumber": 312,
	"startColumn": 41,
	"endLineNumber": 312,
	"endColumn": 54
}]

https://github.com/rook/rook/blob/master/pkg/operator/ceph/object/user/controller.go#L312

the doc from https://pkg.go.dev/github.com/ceph/go-ceph@v0.14.0/rgw/admin shows this funciton is introduced by verion 0.14.0, but the rook go.mod is using its 0.12.0:
https://github.com/rook/rook/blob/master/go.mod#L9

**Expected behavior:**

the function can be used from right version. 

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by gongysh2004** [comment]
please have a look at my pull request https://github.com/rook/rook/pull/9939, thanks.

**Comment by thotz** [comment]
@gongysh2004 : I can see https://pkg.go.dev/github.com/ceph/go-ceph not listing caps API in v0.12 but this was added in https://github.com/ceph/go-ceph/blob/v0.12.0/rgw/admin/caps.go. The files had a `ceph_preview` build tag which was removed in a later release, this might be related to that. But irrespective of this issue it is always better to use the latest go-ceph API versions. So please correct the failures in PR
