### ISSUE TITLE
rook-ceph-rgw-my-store-a failed to start with host ip:80 no route to host

### ISSUE THREAD

**Issue by fzhan** [rook/rook#9945]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
1. following the example in deploy/
2. cluster setup with public network
3. object-test.yaml successfully created
4. rgw service with 1 daemon active
5. rgw svc pod failed to start, log:   Startup probe failed: dial tcp 10.173.59.205:80: i/o timeout; Startup probe failed: dial tcp 10.173.59.205:80: connect: no route to host
where 10.173.59.205 is the IP of the node hosting this pod

**Expected behavior:**
pod startup without error

**How to reproduce it (minimal and precise):**

everything default from v1.8.7, k8s with three ready nodes
1. kubectl create -f crds.yaml -f common.yaml
2. kubectl create -f operator.yaml
3. kubectl create -f object-ec.yaml
**File(s) to submit**:

* Operator's logs, if necessary
`ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/my-store". failed to get dependents of CephObjectStore "rook-ceph/my-store": failed to list buckets in CephObjectStore "rook-ceph/my-store": Get "http://rook-ceph-rgw-my-store.rook-ceph.svc:80/admin/bucket?": dial tcp: lookup rook-ceph-rgw-my-store.rook-ceph.svc on 127.0.0.53:53: read udp 127.0.0.1:43892->127.0.0.53:53: read: connection refused`
* Crashing pod(s) logs, if necessary
`  Normal   Pulled     36s                kubelet            Container image "quay.io/ceph/ceph:v16.2.7" already present on machine
  Normal   Created    36s                kubelet            Created container chown-container-data-dir
  Normal   Started    36s                kubelet            Started container chown-container-data-dir
  Normal   Pulled     34s (x2 over 35s)  kubelet            Container image "quay.io/ceph/ceph:v16.2.7" already present on machine
  Normal   Created    34s (x2 over 35s)  kubelet            Created container rgw
  Normal   Started    34s (x2 over 35s)  kubelet            Started container rgw
  Warning  Unhealthy  15s                kubelet            Startup probe failed: dial tcp 10.173.59.205:80: i/o timeout
  Warning  Unhealthy  6s                 kubelet            Startup probe failed: dial tcp 10.173.59.205:80: connect: no route to host
  Warning  BackOff    4s                 kubelet            Back-off restarting failed container
`
 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): ubuntu 20.04
* Kernel (e.g. `uname -a`): Linux s1 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): v1.8.7
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.7
* Kubernetes version (use `kubectl version`): 1.22
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Microk8s
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): `  cluster:
    id:     de3088e9-8756-4791-a0d2-b2a98fce8db8
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,c (age 60m)
    mgr: a(active, since 59m), standbys: b
    osd: 15 osds: 15 up (since 58m), 15 in (since 59m)
    rgw: 1 daemon active (1 hosts, 1 zones)

  data:
    pools:   14 pools, 153 pgs
    objects: 411 objects, 16 KiB
    usage:   239 MiB used, 90 TiB / 90 TiB avail
    pgs:     153 active+clean

  io:
    client:   1.1 KiB/s rd, 0 B/s wr, 1 op/s rd, 0 op/s wr
`

**Comment by fzhan** [comment]
After exec into toolbox, the error is clear:
 
`curl rook-ceph-rgw-my-store.rook-ceph.svc:80
curl: (6) Could not resolve host: rook-ceph-rgw-my-store.rook-ceph.svc
`
however

`curl 10.152.183.149
<?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>anonymous</ID><DisplayName></DisplayName></Owner><Buckets></Buckets></ListAllMyBucketsResult>[rook@rook-ceph-tools-5c6844fcd5-6jhd2 /]
`
which 10.152.183.149 is the ip address allocated to this service rook-ceph-rgw-my-store

**Comment by fzhan** [comment]
it appears to be a conflict between network set to host, and DNS module not being enabled by microk8s.

**Comment by irefaat** [comment]
I have the same issue; anyone found a way to resolve to it, please.
