### ISSUE TITLE
The node obtained by canary is consistent with the deployed mon

### ISSUE THREAD

**Issue by fengjiankui121** [rook/rook#9961]
**Is this a bug report or feature request?**
* Feature Request

The node ip obtained by canary will be recorded in rook-ceph-mon-endpoints, and the data in rook-ceph-mon-endpoints will be synchronized to rook-ceph-config, and the ip of rook-ceph-config is finally used to start ceph mon, osd, etc., it is necessary to ensure that the data in rook-ceph-config is consistent with the actual mon ip, so the node obtained by canary is consistent with the deployed mon.

#------------------The node obtained by canary is not used to deploy mon. The relevant code is as follows：

	if schedule == nil || schedule.Zone != "" {
		k8sutil.SetNodeAntiAffinityForPod(&d.Spec.Template.Spec, requiredDuringScheduling(&c.spec), v1.LabelHostname,
			map[string]string{k8sutil.AppAttr: AppName}, nil)
	} else {
		p.PodAffinity = nil
		p.PodAntiAffinity = nil
		k8sutil.SetNodeAntiAffinityForPod(&d.Spec.Template.Spec, requiredDuringScheduling(&c.spec), v1.LabelHostname,

**What should the feature do:**

**What is use case behind this feature:**

**Environment**:

**Comment by parth-gr** [comment]
We sync it here mon-ip with endpoint details here, https://github.com/rook/rook/blob/5a82a1cbd737a9062df883cb48c2785c253fa1f5/pkg/operator/ceph/cluster/mon/mon.go#L558

**Comment by travisn** [comment]
Let's use the discussion item #9960 for this question, thanks

**Comment by travisn** [comment]
Reopening after further discussion in #9960. 

From [this comment](https://github.com/rook/rook/discussions/9960#discussioncomment-2648277):

The operator was restarted before the reconcile of the mon failover was completed, and the mon canary chose a different node after the operator restart. The repro steps aren't going to be hit in production, but I could imagine an operator restart for some other reason to cause this.

**Comment by fengjiankui121** [comment]
> @fengjiankui121 What version of the code were you referring to? The code path is a bit different now. https://github.com/rook/rook/blame/release-1.9/pkg/operator/ceph/cluster/mon/mon.go#L1283-L1294
> 
> Does this issue still repro in v1.9 or master?

@travisn  I am referring to version 1.5，but but it still exists

**Comment by fengjiankui121** [comment]
1、Deploy rook-ceph to create mon.a, mon.b, mon.c
2、On the node of mon.a, copy /var/lib/rook/mon-a as /var/lib/rook/mon-d, and copy /var/lib/rook/mon for mon-a and mon-d -a/data/store.db is deleted, so that both mon-a and mon-d can't get up
3、Wait for the health check of rook-ceph to create the deploy of mon-d
4、Restart the operator, and wait for the operator to create a mon-d canary (this time it is in the pending state)
5、Delete /var/lib/rook/mon-d of mon-d, and restart mon-d， mon-d will be up and added to quorum
6、Restart the pod of mon-b, wait for mon-a to be deleted, and check the data information of rook-ceph-endpoint

@travisn  You can try to reproduce the problem with this step.
