### ISSUE TITLE
Implement Rook software upgrade automation

### ISSUE THREAD

**Issue by jbw976** [rook/rook#997]
The design has been written up and fleshed out with #983 

Next steps would be to get an implementation of upgrade automation, as described in:
https://github.com/rook/rook/blob/master/design/upgrade.md#next-steps

**Comment by jbw976** [comment]
This work is not completed yet, it was only partially addressed by #1473

**Comment by kfox1111** [comment]
Any update on this issue?

**Comment by travisn** [comment]
@kfox1111 automation for the upgrade has not been started yet. The plan is to work on the automation after a beta has been declared. Until then we are documenting the manual steps for upgrade with each release.

**Comment by kfox1111** [comment]
Any timeline on the beta (rough. like, 1 month, 6 months, a year... )?

**Comment by travisn** [comment]
For 0.9 the following is needed for upgrade:
- To help reduce the manual steps for upgrade, a small code change that will help tremendously is to update the deployment specs automatically for the ceph daemons. This is already done for the OSD deployments with the helper `k8sutil.UpdateDeploymentAndWait()` as seen [here](https://github.com/rook/rook/blob/master/pkg/operator/ceph/cluster/osd/osd.go#L330). If we call this same helper for the mon, mgr, rgw, and mds, the pod specs will automatically be taken care of during upgrade.
- Update the documentation in [upgrade.md](https://github.com/rook/rook/blob/master/Documentation/upgrade.md) and [upgrade-patch.md](https://github.com/rook/rook/blob/master/Documentation/upgrade-patch.md). We might not need `upgrade-patch.md` anymore with the improvements to the main upgrade guide and the code changes described in the previous bullet.

@BlaineEXE thanks for taking a look at this.

**Comment by travisn** [comment]
With improvements in v0.9 including #2314 let's close this issue and track improvements with more fine-grained issues as needed.
