### ISSUE TITLE
ceph disk usage reported by prometheus does not match linux df command output

### ISSUE THREAD

**Issue by hackaholic** [rook/rook#9971]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
prometheus **ceph_cluster_total_used_bytes**
![image](https://user-images.githubusercontent.com/3721438/161294490-4b1dbfff-bfcb-4aee-9c9d-693013da9366.png)

from df cmd after mounted ceph on host.
![image](https://user-images.githubusercontent.com/3721438/161295338-0223dc98-c43f-4823-95eb-57dfd6620750.png)

**Expected behavior:**
output from prometheus counter **ceph_cluster_total_used_bytes** should match the output  **df linux command**

**Environment**:
OS (e.g. from /etc/os-release):
    cat /etc/os-release
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

    Kernel (e.g. uname -a):
    uname -a
    Linux pwconfig-k8s-master0 3.10.0-1160.42.2.el7.x86_64 

https://github.com/rook/rook/pull/1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Cloud provider or hardware configuration:
Rook version (use rook version inside of a Rook Pod):
{
"mon": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 3
},
"mgr": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 2
},
"osd": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 6
},
"mds": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 2
},
"overall": {
"ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)": 13
}
}
Storage backend version (e.g. for ceph do ceph -v):
ceph -v
ceph version 16.2.2 (e8f22dde28889481f4dda2beb8a07788204821d3) pacific (stable)
Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

**Comment by travisn** [comment]
Where did you run `df` on the host? Not sure it's comparable to the total ceph bytes. The space reported by ceph is going to be different because of ceph's redundancy, some internal overhead, etc.

**Comment by hackaholic** [comment]
@travisn yes on the host
