### ISSUE TITLE
pv-migrator failure - rbd rename - error opening source image: (2) No such file or directory

### ISSUE THREAD

**Issue by abh** [rook/rook#9986]
* Bug Report

**Deviation from expected behavior: `pv-migrator` failed with an error, after completion the pvc can't be mounted.

**How to reproduce it (minimal and precise):**

I ran pv-migrator like this `pv-migrator --pvc=mailserver-rainloop  --pvc-ns=mailserver   --destination-sc=rook-ceph-block-repl` which resulted in the output below and upon scaling back the deployment it fails with

```
  Normal   SuccessfulAttachVolume  12s              attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-1f649c53-3f34-4108-bbef-9c924ea2edcb"
  Warning  FailedMount             1s (x4 over 5s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-1f649c53-3f34-4108-bbef-9c924ea2edcb" : rpc error: code = Internal desc = fail to check rbd image status: (image not found: RBD image not found)
```

**Environment**:
* Rook version: 1.7.11
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.6
* Kubernetes version (use `kubectl version`): v1.21.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Rancher / RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): Healthy

```
I0405 04:43:24.793208     159 log.go:34] Create Kubernetes Client
I0405 04:43:24.843531     159 log.go:34] List all the PVC from the source storageclass
I0405 04:43:24.849692     159 log.go:34] 1 PVCs found with source StorageClass
I0405 04:43:24.849716     159 log.go:34] Start Migration of PVCs to CSI
I0405 04:43:24.849728     159 log.go:34] migrating PVC "mailserver-rainloop" from namespace "mailserver"
I0405 04:43:24.849737     159 log.go:34] Fetch PV information from PVC mailserver-rainloop
I0405 04:43:24.861439     159 log.go:34] PV found "pvc-20059413-0a02-4dee-8a93-f276626230ac"
I0405 04:43:24.861466     159 log.go:34] Update Reclaim policy from Delete to Reclaim for PV: pvc-20059413-0a02-4dee-8a93-f276626230ac
I0405 04:43:24.880114     159 log.go:34] Retrieving old ceph volume name from PV object: pvc-20059413-0a02-4dee-8a93-f276626230ac
I0405 04:43:24.880143     159 log.go:34] rbd image name is "pvc-20059413-0a02-4dee-8a93-f276626230ac"
I0405 04:43:24.880151     159 log.go:34] Deleting pvc object: mailserver-rainloop
I0405 04:43:24.891942     159 log.go:34] waiting for PVC mailserver-rainloop in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteOnce],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},} to be deleted (0 seconds elapsed)
I0405 04:43:26.902082     159 log.go:34] waiting for PVC mailserver-rainloop in state &PersistentVolumeClaimStatus{Phase:Bound,AccessModes:[ReadWriteOnce],Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},Conditions:[]PersistentVolumeClaimCondition{},} to be deleted (2 seconds elapsed)
I0405 04:43:26.926254     159 log.go:34] Generate new PVC with same name in destination storageclass
I0405 04:43:26.926745     159 log.go:34] Create new csi pvc
I0405 04:43:26.954157     159 log.go:34] Waiting up to &PersistentVolumeClaim{ObjectMeta:{mailserver-rainloop  mailserver  20059413-0a02-4dee-8a93-f276626230ac  0 2020-04-26 08:54:58 +0000 UTC <nil> <nil> map[app.kubernetes.io/managed-by:Helm] map[] [] [kubernetes.io/pvc-protection]  []},Spec:PersistentVolumeClaimSpec{AccessModes:[ReadWriteOnce],Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},},VolumeName:,Selector:nil,StorageClassName:*rook-ceph-block-repl,VolumeMode:*Filesystem,DataSource:nil,},Status:PersistentVolumeClaimStatus{Phase:,AccessModes:[],Capacity:ResourceList{},Conditions:[]PersistentVolumeClaimCondition{},},} to be in Bound state
I0405 04:43:26.954193     159 log.go:34] waiting for PVC mailserver-rainloop (0 seconds elapsed)
I0405 04:43:28.960331     159 log.go:34] waiting for PVC mailserver-rainloop (2 seconds elapsed)
I0405 04:43:28.981319     159 log.go:34] Waiting for PV "pvc-1f649c53-3f34-4108-bbef-9c924ea2edcb" to bind to PVC "mailserver-rainloop"
I0405 04:43:28.981362     159 log.go:34] Waiting up to 30ms for PersistentVolumeClaims [mailserver-rainloop] to have phase Bound
I0405 04:43:28.987522     159 log.go:34] PersistentVolumeClaim mailserver-rainloop found and phase=Bound (6.138964ms)
I0405 04:43:28.987578     159 log.go:34] Waiting up to 3s for PersistentVolume pvc-1f649c53-3f34-4108-bbef-9c924ea2edcb to have phase Bound
I0405 04:43:28.998249     159 log.go:34] PersistentVolume pvc-1f649c53-3f34-4108-bbef-9c924ea2edcb found and phase=Bound (10.644331ms)
I0405 04:43:29.021248     159 log.go:34] New PVC with same name "mailserver-rainloop" created via CSI
I0405 04:43:29.021271     159 log.go:34] Extracting new volume name from CSI PV
I0405 04:43:29.021280     159 log.go:34] CSI new volume name: csi-vol-ef08539e-b49a-11ec-b827-3abbed756747
I0405 04:43:29.021287     159 log.go:34] Fetching csi pool name
I0405 04:43:29.021295     159 log.go:34] csi poolname: replicapool2020
I0405 04:43:29.021305     159 log.go:34] Create new Ceph connection
I0405 04:43:29.021315     159 log.go:34] csi poolname: replicapool2020
I0405 04:43:29.026497     159 log.go:34] clusterID: rook-ceph, monitors: 10.43.101.57:6789,10.43.113.191:6789,10.43.69.232:6789,10.43.245.153:6789,10.43.23.126:6789, poolname: replicapool2020
I0405 04:43:29.033776     159 log.go:34] New connection arg monitors: 10.43.101.57:6789,10.43.113.191:6789,10.43.69.232:6789,10.43.245.153:6789,10.43.23.126:6789, id: csi-rbd-provisioner, keyfile: /tmp/csi/keys/keyfile-234998742, pool: replicapool2020, datapool:
I0405 04:43:29.033820     159 log.go:34] Cluster connection created
I0405 04:43:29.033834     159 log.go:34] Delete the placeholder CSI volume in ceph cluster
I0405 04:43:29.394237     159 log.go:34] Successfully removed volume csi-vol-ef08539e-b49a-11ec-b827-3abbed756747
I0405 04:43:29.394269     159 log.go:34] Rename old ceph volume to new CSI volume
Error: failed to migrate PVC mailserver-rainloop : failed to rename old ceph volume pvc-20059413-0a02-4dee-8a93-f276626230ac to new CSI volume csi-vol-ef08539e-b49a-11ec-b827-3abbed756747: exit status 2. failed to rename rbd image, command output: rbd: rename error: (2) No such file or directory
2022-04-05T04:43:29.448+0000 7f85260a02c0 -1 librbd: error opening source image: (2) No such file or directory

Usage:
  migrate [flags]

Flags:
      --ceph-cluster-ns string   Kubernetes namespace where ceph cluster is created (default "rook-ceph")
      --destination-sc string    destination storageclass (CSI storageclass) to which all PVC need to be migrated
  -h, --help                     help for migrate
      --kubeconfig string        kubernetes config path
      --pvc string               Name of the specific pvc you want to migrate
      --pvc-ns string            Namespace of the specific pvc you want to migrate
      --rook-ns string           Kubernetes namespace where rook operator is running (default "rook-ceph")
      --source-sc string         source storageclass from which all PVC need to be migrated

Error: failed to migrate PVC mailserver-rainloop : failed to rename old ceph volume pvc-20059413-0a02-4dee-8a93-f276626230ac to new CSI volume csi-vol-ef08539e-b49a-11ec-b827-3abbed756747: exit status 2. failed to rename rbd image, command output: rbd: rename error: (2) No such file or directory
2022-04-05T04:43:29.448+0000 7f85260a02c0 -1 librbd: error opening source image: (2) No such file or directory
```

**Comment by Madhu-1** [comment]
@Yuggupta27 @subhamkrai PTAL

**Comment by Madhu-1** [comment]
@abh is your existing pvc in flex is using the same pool as the destination storageclass. can you please paste source and destination storageclass?

**Comment by abh** [comment]
Thanks @Madhu-1. I tried renaming the image manually, but that still left the PVC broken,

```
% kubectl -n mailserver describe pvc pvc-1f649c53-3f34-4108-bbef-9c924ea2edcb
Error from server (NotFound): persistentvolumeclaims "pvc-1f649c53-3f34-4108-bbef-9c924ea2edcb" not found
```

The pool in the flex storage class ("rook-ceph-block") is different than in CSI ("rook-ceph-block-repl"). When we setup CSI way back when it came out it wasn't clear to me that we could use the same pool.

It sounds like to fix this I need to setup a new CSI-based storageclass that's using the original pool?

Flex storage class:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  creationTimestamp: "2019-05-03T07:27:18Z"
  name: rook-ceph-block
  resourceVersion: "209089171"
  uid: e1ef5941-6d74-11e9-80e2-0cc47ab589c8
parameters:
  blockPool: replicapool
  clusterNamespace: rook-ceph
  fstype: xfs
provisioner: ceph.rook.io/block
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

CSI storage class:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2020-05-04T03:17:00Z"
  name: rook-ceph-block-repl
  resourceVersion: "209099323"
  uid: bd66e62f-3436-4fce-b3ef-c2799ab27d1b
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  imageFeatures: layering
  imageFormat: "2"
  pool: replicapool2020
provisioner: rook-ceph.rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by Madhu-1** [comment]
Yes @abh you need to use the same pool for the migration.

**Comment by Madhu-1** [comment]
This is because we cannot rename/move the images between pools? @Yuggupta27 @subhamkrai can we document this one, please.

**Comment by subhamkrai** [comment]
@Madhu-1 sure, will look into this

**Comment by abh** [comment]
Ah, ok. I imagine you aren't updating pv-migrator anymore but it'd be handy to have a check for that (or maybe just mention it in the documentation).

Two follow-up questions then:

1) Is there a reasonable way to recover the PVC that got lost in this migration? It's not super important, I intentionally tested first with one that's recoverable by other means.

2) If I `rbd cp` the old images to the new pool, is there a way to either edit the PVC to use the new pool / storageclass or setup a new PVC with an existing image? (My goal is to remove the old storageclass and pool).

**Comment by subhamkrai** [comment]
> Ah, ok. I imagine you aren't updating pv-migrator anymore but it'd be handy to have a check for that (or maybe just mention it in the documentation).

We can update pv-migrator depending on requiremt and uses :slightly_smiling_face: 

> 
> Two follow-up questions then:
> 
>     1. Is there a reasonable way to recover the PVC that got lost in this migration? It's not super important, I intentionally tested first with one that's recoverable by other means.
> 
>     2. If I `rbd cp` the old images to the new pool, is there a way to either edit the PVC to use the new pool / storageclass or setup a new PVC with an existing image? (My goal is to remove the old storageclass and pool).

**Comment by Madhu-1** [comment]
> Ah, ok. I imagine you aren't updating pv-migrator anymore but it'd be handy to have a check for that (or maybe just mention it in the documentation).
> 

This new one needs a lot of changes in the tool. I suggest documenting this one.

> Two follow-up questions then:
> 
> 1. Is there a reasonable way to recover the PVC that got lost in this migration? It's not super important, I intentionally tested first with one that's recoverable by other means.

Currently, there is no way, this is tracked with https://github.com/ceph/persistent-volume-migrator/issues/19

> 2. If I `rbd cp` the old images to the new pool, is there a way to either edit the PVC to use the new pool / storageclass or setup a new PVC with an existing image? (My goal is to remove the old storageclass and pool).

Yes, you can recreate the PVC and the PV objects manually but it's a tricky one as you need to regenerate the volumeHandle and update few VolumeAttributes in the PV object as the poolID  differs.

**Comment by abh** [comment]
> Yes, you can recreate the PVC and the PV objects manually but it's a tricky one as you need to regenerate the volumeHandle and update few VolumeAttributes in the PV object as the poolID differs.

Ok, great. Thank you! Right now the PVC I migrated (that failed) is "Lost" (but the image is still there, of course), so I'll experiment with that to see if I can get back by re-creating the PV / PVC manually.

**Comment by abh** [comment]
Alright, that was pretty easy.  My volumeHandle's are either `0001-0009-rook-ceph-0000000000000001` or the same but suffixed with `4` instead of `1`. I picked a random one and added the UUID / image name to the volumeHandle and created the PV and PVC and it came up ok.

Thank you for the brilliantly quick response to this issue!  I'll make a storageclass using the old ceph pool to migrate the flex PVCs to now. :-)

**Comment by Madhu-1** [comment]
>0001-0009-rook-ceph-0000000000000001

0000000000000001 is the poolID you can replace with the poolID of the new pool. if that solves the issue we can close this one?

**Comment by Yuggupta27** [comment]
> This is because we cannot rename/move the images between pools. @Yuggupta27 @subhamkrai can we document this one, please.

Sure Madhu! We can do that :+1:

**Comment by abh** [comment]
> 0000000000000001 is the poolID you can replace with the poolID of the new pool. if that solves the issue we can close this one?

oh, interesting. I actually used the wrong one but either it worked anyway or I had such a spectacular list of mistakes of mixed PVC IDs that I was mounting the old copy of the image (?!).

I got it sorted out now; again thank you for the quick help today (tonight for me).
