### ISSUE TITLE
Ceph OSD's class (`ssd`) is not the same as the one requested by OSD Pod (`nvme`)

### ISSUE THREAD

**Issue by nazarewk** [rook/rook#9987]
I've described it as i went at https://rook-io.slack.com/archives/CK9CF5H2R/p1649132093217969

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Having [NVMe partition used through a PV](https://github.com/nazarewk-iac/k8s-configs/blob/73c49bcd70ba498f21efa721ff60c600b1b7b707/services/rook/ceph/cluster/pvs.yaml#L10-L40), all steps on the way discover the partition as `nvme`, including the closes step to ceph:
```
kubectl get deployment rook-ceph-osd-1 -o json | jq '.spec.template.spec.containers[].env[] | select(.name == "ROOK_OSD_DEVICE_CLASS")'
{
  "name": "ROOK_OSD_DEVICE_CLASS",
  "value": "nvme"
}
```
The OSD gets created and registered properly in Ceph except for the class being `ssd`:
```
[rook@rook-ceph-tools-5b49ff9fc5-9npqx /]$ ceph osd tree
ID  CLASS  WEIGHT    TYPE NAME               STATUS  REWEIGHT  PRI-AFF
-1         11.95966  root default                                     
-3         11.95966      host nazarewk-krul                           
 3    hdd   3.63869          osd.3               up   1.00000  1.00000
 4    hdd   3.63869          osd.4               up   1.00000  1.00000
 0    ssd   1.81929          osd.0               up   1.00000  1.00000
 1    ssd   1.00000          osd.1               up   1.00000  1.00000
 2    ssd   1.86299          osd.2               up   1.00000  1.00000
```

**Expected behavior:**

Rook's OSD passes `nvme` as the device class properly to Ceph process/configuration.

**How to reproduce it (minimal and precise):**

I don't have much idea, it is the same (registering as SSD) every single time for me.

**File(s) to submit**:

I don't think this is needed as it's properly handled all the way down to the OSD Pod creation. You can find all my config at https://github.com/nazarewk-iac/k8s-configs/blob/main/services/rook/ceph/cluster/chart.yaml#L19

**Environment**:
* OS (e.g. from /etc/os-release): NixOS
* Kernel (e.g. `uname -a`): `5.16.15`
* Cloud provider or hardware configuration: bare-metal desktop machine
* Rook version (use `rook version` inside of a Rook Pod): `1.8.8`
* Storage backend version (e.g. for ceph do `ceph -v`): `16.2.7`
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `k3s`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by travisn** [comment]
Try the annotation seen [here](https://github.com/rook/rook/blob/master/deploy/examples/cluster-on-pvc.yaml#L123-L124) on the storageClassDeviceSet.volumeClaimTemplate:
```yaml
crushDeviceClass: hybrid
```

Looks like you're only setting this custom annotation instead:
```yaml
storage.nazarewk.pw/device-class: nvme
```

**Comment by jplitza** [comment]
I'm hitting the same problem.

@travisn It's not that the PVC uses the wrong OSDs, the problem is much earlier: The OSDs have the wrong device type inside the cluster!

**Comment by travisn** [comment]
@jplitza Yes, that's what my old comment was addressing. To be clear, there are two methods to set the deviceClass of the OSD:
1. If using the cluster-on-pvc, you need to set the annotation `crushDeviceClass: hybrid` as I mentioned previously
2. If using the host-based cluster, you need to set the property in the `storage` section:
```yaml
config:
    deviceClass: <value>
```

**Comment by jplitza** [comment]
Sorry, I didn't realize the PVC was the backing store for the OSD. I'll open a discussion for my host-based usecase.
